### ISSUE TITLE
Histogram Chart error Validation

### ISSUE THREAD

**Issue by vagish1101** [apache/superset#10038]
Hello Team,

Thanks for the wonderful App 

I am getting error only with the Histogram chart when Data array is empty and the error message coming on my browser 

error message: Typeerror: cannot read property 'map' of null

Please help

**Comment by willbarrett** [comment]
Hi @vagish1101 - please share your Superset version and the relevant backtrace from your Superset logs. That will help us point you in the right direction or fix the issue.
