### ISSUE TITLE
can not return future date values

### ISSUE THREAD

**Issue by ayushbilala** [apache/superset#10053]
My SQL query is supposed to return a date column with value '2500-01-01' but is returning '1915-06-14T00:25:26.290448384' via Superset. 
I get the correct result from other BI tools, be it Tableau or DBeaver.

On further research, I figured out the root cause. The reason Superset is displaying 1915-06-14 is because the date 2500-01-01 is going out of the range of date type of Superset. Superset’s supported date range is from 1677-09-21 – 2262-04-11, due to this any date after the max date starts again from 1677.
This is the same issue I have seen while working with Pandas (pandas.Timestamp.max)

**Comment by willbarrett** [comment]
Superset relies on Pandas for many of its transformations. I believe you are correct that this is a limitation of Pandas. Out of curiosity, what is your use-case for far-future dates? Climate projection?

**Comment by ayushbilala** [comment]
No not really. Our users do store some far-future dates instead of some NULL value which is why I am having a hard time :)

**Comment by junlincc** [comment]
@ayushbilala are those future dates just a 'place-holder' ? or projection?
