### ISSUE TITLE
Item with nordic letters is not properly sorted in lists

### ISSUE THREAD

**Issue by larsmars** [apache/superset#10064]
Item with nordic letters is not properly sorted in lists
Sort Ascending is selected

### Expected results
Correct sorting:
Æ - Ø - Å

### Actual results
Actual sorting:
Å - Ø 

The rest of the alphabet is ordered correct (A-Z)

#### Screenshots
![filter_let](https://user-images.githubusercontent.com/5154589/84767721-3461b400-afd3-11ea-84d1-0600db026fe5.png)

![sort_kom](https://user-images.githubusercontent.com/5154589/84768737-01b8bb00-afd5-11ea-8a0e-71125179da4a.PNG)

#### How to reproduce the bug
1. Go to dashbord with filter with items starting with Æ Ø Å
2. Observe list is not correctly sorted

### Environment
- superset version: 0.36.0
- python version: 3.6.10
- node.js version: 12.16.1
- npm version: 6.13.4

### Checklist
Make sure these boxes are checked before submitting your issue - thank you!
- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by larsmars** [comment]
bump

**Comment by nytai** [comment]
I could be mistaken, but isn't sorting handled by the database therefore it's the underlying database that is incorrectly sorting these results?

**Comment by larsmars** [comment]
You are right, but the dropdown sorting feature on chart in superset should work regardless of this. 
Code in parameters (edit chart, superset): `"filter_configs": [{"asc": true, `

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current-era Superset or not, but if it is, we probably need a new issue filed. Namely:
• The FilterBox component is on a path to deprecation
• The Select component has been consolidated and works pretty darn well these days
• Bug was reported for an old/unsupported version of Superset.
If it's still an issue, we need updated repro steps and screenshots on a new Issue.
