### ISSUE TITLE
Y Axis percentage (%) in Time-series Bar Chart do not respect Y Axis Format

### ISSUE THREAD

**Issue by larsmars** [apache/superset#10082]
Y Axis percentage (%) in Time-series Bar Chart do not respect Y Axis Format

### Expected results
Percentage to be displayed without decimals when .1s format is selected ie: 20%

### Actual results
Percentage is displayed with decimals ie: 20.0%

#### Screenshots
![percentage](https://user-images.githubusercontent.com/5154589/84889880-e4015980-b099-11ea-819a-c93fcbfe5c5f.PNG)

#### How to reproduce the bug
1. Create chart of type Time-series Bar Chart with percentage
2. Select Y Axis Format .1s
3. Observe numbers is displayet with decimals

### Environment
superset version: 0.36.0
python version: 3.6.10
node.js version: 12.16.1
npm version: 6.13.4

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by larsmars** [comment]
bump

**Comment by amitmiran137** [comment]
Bar chart is depracated and issues will not be addressed
