### ISSUE TITLE
Filter on bool column not working properly in SQL Lab -> Explore

### ISSUE THREAD

**Issue by dolorez** [apache/superset#10098]
When a query in SQL Lab is executed and a filter is applied to a boolean column, it errors out on datatype comparison (boolean vs string). 
Note - the behavior
### Expected results
The filter should work - the generated query should not enclose the field value in single quotes. 

### Actual results
The query generated encloses the filter value in single quotes so the where clause generated looks (some_bool_flag = 'true') and this that in turn generates type mismatch

#### How to reproduce the bug

1. Go to SQL Lab -> SQL Editor
2. Write a query that returns a boolean column
3. Execute the query
4. Click on Explore
5. Scroll down to filters
6. Add a filter on a boolean column and make sure you stay in Simple (not Custom SQL)
7. Use equals and set filter value to "true" (without double quotes)
8. Execute the query to see the error messge
9. Click on menu -> View query to inspect that the filter value was enclosed in single quotes

### Environment

(please complete the following information):

- superset version: `superset version
0.34.1
- python version: `python --version`
Python 3.6.9
- node.js version: `node -v`
v12.18.0
- npm version: `npm -v`
6.14.4
### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
I have no control over the environment :(
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

When the filter is entered using the Custom SQL instead of Simple, it works fine

**Comment by rumbin** [comment]
Could you add the type of database, please?

**Comment by dolorez** [comment]
It's presto and that particular query goes to hive

**Comment by bkyryliuk** [comment]
issue still persists on presto database. It's not possible to replicate for mysql as mysql interpret boolean as tinyint.

Selector looks like this:
![image](https://user-images.githubusercontent.com/5727938/96056939-b0162500-0e3c-11eb-99d8-b9349343cc21.png)

Clicking on it results in: 
![image](https://user-images.githubusercontent.com/5727938/96056973-bf956e00-0e3c-11eb-917e-167f4c515297.png)


@etr2460, @john-bodley  - curious if you have similar issue @ airbnb.

**Comment by eugeniamz** [comment]
I see the same issue with Vertica DB. It does not show the option but if you choose the second one you have a TRUE but the first is empty. I work around by going to CUSTOM SQL but this should be resolved. 
![2020-10-28_18-07-06 (1)](https://user-images.githubusercontent.com/58375897/97501996-a4e8ec00-1948-11eb-9367-aa4c0fd33032.gif)

**Comment by mistercrunch** [comment]
Maybe we need conditional operators based on data type. `BOOLEAN` should only offer `IS NULL` `IS TRUE` and  `IS FALSE`

**Comment by john-bodley** [comment]
@junlincc @zuzana-vej I wonder if we should prioritize this, i.e., not being able to filter on a boolean column using `IS TRUE`, `IS FALSE` etc. seems fairly problematic.

**Comment by junlincc** [comment]
@john-bodley @zuzana-vej we will work on this issue next week! 

@michael-s-molina @geido
