### ISSUE TITLE
ClickHouse IPv6 error

### ISSUE THREAD

**Issue by kanadaj** [apache/superset#10091]
When trying to query a ClickHouse database from SQL Lab with an IPv6 field, Superset gives the following error:
```
Could not convert ::ffff:0000:0000 with type IPv6Address: did not recognize Python value type when inferring an Arrow data type
```
(IP address data replaced with 0s). I can't see any stack traces in the console output.

#### How to reproduce the bug

1. Create a new ClickHouse database
2. Create a table with at least one IPv6 field
3. Insert some data
4. Add the database to Superset
5. Go to SQL Lab and try to query the data via `SELECT * FROM ...`

### Environment

(please complete the following information):

- superset version: Superset 0.999.0dev
- python version: Python 3.6.9
- node.js version: v10.19.0
- npm version: 6.13.4

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by john-bodley** [comment]
@kanadaj is this still an issue? I know that since you opened this issue we've bumped the version of PyArrow and there's been a few newer versions of the [clickhouse-sqlalchemy](https://pypi.org/project/clickhouse-sqlalchemy/#history).

**Comment by kanadaj** [comment]
@john-bodley I've no idea, the issue was around for long enough that ultimately we've switched to using Metabase for querying ClickHouse for an online interface
