### ISSUE TITLE
Error with Login on Windows 10 using Docker: sqlalchemy.exc.ProgrammingError

### ISSUE THREAD

**Issue by ckaldemeyer** [apache/superset#10132]
### Expected results

Successful docker login on localhost as described within the documentation: https://superset.incubator.apache.org/installation.html#start-with-docker

### Actual results

First problem: The user admin with password admin ist not working and no login possible as opposed to the documentation.

So I tried the following based on this question (https://stackoverflow.com/questions/55961428/default-login-for-docker-image-of-superset) in order to create a user admin with password admin:

    docker-compose exec superset bash -c "export FLASK_APP=superset && flask fab create-admin"

This seems to have succeeded:

      C:\Users\foo\Documents\Programmierung\incubator-superset>docker-compose exec superset bash -c "export FLASK_APP=superset && flask fab create-admin"
      Username [admin]: admin
      User first name [admin]: admin
      User last name [user]: admin
      Email [admin@fab.org]: bla@blub.com
      Password:
      Repeat for confirmation:
      Loaded your LOCAL configuration at [/app/pythonpath/superset_config.py]
      INFO:superset.utils.logging_configurator:logging was configured successfully
      /usr/local/lib/python3.6/site-packages/flask_caching/__init__.py:189: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
        "Flask-Caching: CACHE_TYPE is set to null, "
      Recognized Database Authentications.
      Admin User admin created.

After a "successfull" login, I get the following error:

    sqlalchemy.exc.ProgrammingError
    sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "user_attribute" does not exist

This is also included in the logs:

    sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "user_attribute" does not exist

and it seems as if there is a missing table. But I haven't even touched the database yet..

#### Screenshots

https://pasteboard.co/JeggARr.png

#### How to reproduce the bug

Just follow the official documentation using Windows 10: https://superset.incubator.apache.org/installation.html#start-with-docker

### Environment

(please complete the following information):

- superset version: 0.36.0
- python version: Python 3.7.6
- node.js version: ? 
- npm version: ?

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

The error log is identical to the one in this comment: https://github.com/apache/incubator-superset/issues/7637#issuecomment-498609977

Any hints?

**Comment by ckaldemeyer** [comment]
👍

**Comment by willbarrett** [comment]
@ckaldemeyer when you run `docker-compose up` please look carefully at the output from the `superset-init` container. This is the container responsible for running database migrations. Are there any errors, or does the container finish its work and exit with status 0?

**Comment by ckaldemeyer** [comment]
Here's the relevant part of the log file:

    $ docker-compose up
    Starting superset_db    ... done
    Starting superset_cache ... done
    Starting superset_init         ... done
    Starting superset_node         ... done
    Starting superset_app          ... done
    Starting superset_worker       ... done
    Starting superset_tests_worker ... done
    Attaching to superset_cache, superset_db, superset_tests_worker, superset_node, superset_worker, superset_app, superset_init
    superset_cache           | 1:C 25 Jun 11:20:04.394 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
    superset_cache           |                 _._
    superset_cache           |            _.-``__ ''-._
    superset_cache           |       _.-``    `.  `_.  ''-._           Redis 3.2.12 (00000000/0) 64 bit
    superset_cache           |   .-`` .-```.  ```\/    _.,_ ''-._
    superset_cache           |  (    '      ,       .-`  | `,    )     Running in standalone mode
    superset_cache           |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
    superset_cache           |  |    `-._   `._    /     _.-'    |     PID: 1
    superset_cache           |   `-._    `-._  `-./  _.-'    _.-'
    superset_cache           |  |`-._`-._    `-.__.-'    _.-'_.-'|
    superset_cache           |  |    `-._`-._        _.-'_.-'    |           http://redis.io
    superset_cache           |   `-._    `-._`-.__.-'_.-'    _.-'
    superset_cache           |  |`-._`-._    `-.__.-'    _.-'_.-'|
    superset_cache           |  |    `-._`-._        _.-'_.-'    |
    superset_cache           |   `-._    `-._`-.__.-'_.-'    _.-'
    superset_cache           |       `-._    `-.__.-'    _.-'
    superset_cache           |           `-._        _.-'
    superset_cache           |               `-.__.-'
    superset_cache           |
    superset_cache           | 1:M 25 Jun 11:20:04.398 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
    superset_cache           | 1:M 25 Jun 11:20:04.398 # Server started, Redis version 3.2.12
    superset_cache           | 1:M 25 Jun 11:20:04.398 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
    superset_db              |
    superset_db              | PostgreSQL Database directory appears to contain a database; Skipping initialization
    superset_db              |
    superset_db              | 2020-06-25 11:20:04.504 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
    superset_db              | 2020-06-25 11:20:04.504 UTC [1] LOG:  listening on IPv6 address "::", port 5432
    superset_cache           | 1:M 25 Jun 11:20:04.399 * DB loaded from disk: 0.001 seconds
    superset_cache           | 1:M 25 Jun 11:20:04.399 * The server is now ready to accept connections on port 6379
    superset_db              | 2020-06-25 11:20:04.507 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
    superset_db              | 2020-06-25 11:20:04.519 UTC [25] LOG:  database system was shut down at 2020-06-25 11:19:56 UTC
    superset_db              | 2020-06-25 11:20:04.526 UTC [1] LOG:  database system is ready to accept connections
    superset_init            | /usr/bin/env: ▒bash\r▒: No such file or directory
    superset_init exited with code 127

Any hints?

**Comment by willbarrett** [comment]
Your `superset_init` container is unable to find the program `bash` - this is a very odd error that I have not seen before. Perhaps some of the other folks who are running Superset on Windows in the community can shed some light. You may have a bad container build? Perhaps attempt to rebuild your containers from scratch with `docker-compose build` - that's a guess, I have no idea if it will help.

**Comment by rgarci** [comment]
#10547 Same issue, this is how I fixed it:

>  I guess you're running on windows, this is a problem caused by git cause it has a default configuration that changes Unix-style line breaks to windows ones, in order to surpass this you need to:
> 
> delete your current repo
> apply git config --global core.autocrlf false so it doesn't change the line breaks
> clone the repo again
> Now you won't be seing this error
> checkout : https://stackoverflow.com/questions/29045140/env-bash-r-no-such-file-or-directory
