### ISSUE TITLE
Closing many SQL Lab tabs in succession returns 404s

### ISSUE THREAD

**Issue by etr2460** [apache/superset#10181]
When you close many SQL Lab tabs in succession with SQL Lab backend persistence enabled, a lot of 404s are returned from the server. Sometimes this results in many toasts on the screen, sometimes not.

### Expected results

No errors

### Actual results

Errors

#### Screenshots
https://i.imgur.com/fw2qnsB.gif

#### How to reproduce the bug
Enable SQL Lab Backend persistence
Open a bunch of tabs, then close them

### Environment

(please complete the following information):

- superset version: master
- python version: 3.6

@betodealmeida can you take a look? Thanks!

**Comment by etr2460** [comment]
bumping this back up again @betodealmeida , any thoughts?

**Comment by betodealmeida** [comment]
I'm going to take a look at this.

**Comment by yousoph** [comment]
I haven't been able to repro this - going to close but feel free to reopen if you're still running into this!
