### ISSUE TITLE
Integrity error, probably unique constraint

### ISSUE THREAD

**Issue by yuexianchao** [apache/superset#10185]
For different dB, adding the same table name will result in an error. The source is two different dB, the index of tables table unique (table_ Name) should be changed to unique (database_id,table_name)I hope this problem can be corrected in the next version. Thank you

**Comment by rvanaalderen** [comment]
Same problem as #10428 ?
I face the same problem in release 0.36 and 0.37

**Comment by etr2460** [comment]
This looks like a duplicate of #10428 so closing
