### ISSUE TITLE
Time Grain Not Available in Azure Databricks 

### ISSUE THREAD

**Issue by rbk-paul** [apache/superset#10199]
The "Time Grain" filter does not have any options available (shows "0 Options"), despite detecting correct the various "Time Columns".
This problem exists for all Visualization Types.

Found a similar issue reported but was closed and marked stale:
https://github.com/apache/incubator-superset/issues/8009

Data Source is from Azure Databricks.

### Expected results
Time Grain filter shows different options like Year, Month, Day...

### Actual results
Shows "0 Options"

#### Screenshots
<img width="424" alt="Screenshot 2020-06-30 at 5 55 45 PM" src="https://user-images.githubusercontent.com/26905569/86118452-6448a580-bb03-11ea-966f-ae4cd70b517b.png">

#### How to reproduce the bug

1. Create any Visualization Type connecting to any tables from a Azure Databricks data source
2. "Time Grain" does not show options

### Environment

(please complete the following information):

- superset version: 0.36.0
- python version: 3.7.7
- node.js version: v13.11.0
- npm version: 6.13.7

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by MApeldoorn** [comment]
Hi,

I am having the same issue. Running SuperSet 0.36, but had the same problem in 0.29.

Connection to a sqlalchemy_sqlany backend. DATETIME_ID (type TIMESTAMP) and DAET_ID (type DATE) are giving 0 Time Grain option(s).
I have tried multiple datetime-translation, but no success.

With kind regards,
Mark

**Comment by mistercrunch** [comment]
What does your connection string look like? What SQL dialect is this most like? Hive?

You probably want to add a new module here:
https://github.com/apache/incubator-superset/tree/master/superset/db_engine_specs

**Comment by villebro** [comment]
@rbk-paul are you connecting using this connector? https://pypi.org/project/databricks-dbapi/

**Comment by rbk-paul** [comment]
@villebro.  yes, using the connector you specified.

@mistercrunch, connection string looks like this: 
databricks+pyhive://token:<databrick_access_token>@<databrick_host>:<port>/<database_name>

**Comment by MApeldoorn** [comment]
@mistercrunch : sqlalchemy_sqlany://...

**Comment by MApeldoorn** [comment]
> What does your connection string look like? What SQL dialect is this most like? Hive?
> You probably want to add a new module here:
> https://github.com/apache/incubator-superset/tree/master/superset/db_engine_specs

It worked for me. I copied the mssql.py db_engine_specs, renamed it to sqlalchemy_sqlany. Only thing I had to fix after that was replace the "0" within DATEADD and DATEDIFF. The results these functions get comparing to todays datetime is giving an error (probably too high value). Replacing "0" by e.g. '2020-01-01' did the trick.
