### ISSUE TITLE
Empty chart visuals on report emails

### ISSUE THREAD

**Issue by iercan** [apache/superset#10202]
I'm trying to configure email reports. I configured every settings as documented but created emails reports does not shows charts as you can see image below. I tried same thing with both dashboard and chart reports, results are same. 

### Expected results

Report emails with same visuals with superset ui. 

### Actual results

Empty visuals like below. 

#### Screenshots

![screenshot](https://user-images.githubusercontent.com/3406152/86138438-25acee00-baf7-11ea-97ab-3faf875a4c2d.png)

#### How to reproduce the bug

1. Create mail report and send test email. 

### Environment
I'm using superset 0.36.0 docker with amancevice/docker-superset  image based on debian with following packages

firefox-esr: 68.9.0esr-1~deb10u1
geckodriver: 0.26.0

alembic==1.3.2
amqp==2.5.2
apache-superset==0.36.0
apispec==1.3.3
asn1crypto==1.3.0
attrs==19.3.0
azure-common==1.1.25
azure-storage-blob==2.1.0
azure-storage-common==2.1.0
Babel==2.8.0
backoff==1.10.0
billiard==3.6.1.0
bitarray==1.2.1
bleach==3.1.0
blinker==1.4
boto3==1.12.47
botocore==1.15.47
cachetools==4.1.0
celery==4.4.0
certifi==2020.4.5.1
cffi==1.13.2
chardet==3.0.4
click==7.1.1
colorama==0.4.3
contextlib2==0.6.0.post1
croniter==0.3.31
cryptography==2.8
cx-Oracle==7.3.0
decorator==4.4.1
defusedxml==0.6.0
docutils==0.15.2
elasticsearch==7.6.0
elasticsearch-dbapi==0.1.1
Flask==1.1.1
Flask-AppBuilder==2.3.1
Flask-Babel==1.0.0
Flask-Caching==1.8.0
Flask-Compress==1.4.0
Flask-Cors==3.0.3
Flask-JWT-Extended==3.24.1
Flask-Login==0.4.1
Flask-Mail==0.9.1
Flask-Migrate==2.5.2
Flask-OAuth==0.12
Flask-OAuthlib==0.9.5
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.1
flask-talisman==0.7.0
Flask-WTF==0.14.2
flower==0.9.4
future==0.18.2
geographiclib==1.50
geopy==1.20.0
gevent==1.4.0
google-api-core==1.17.0
google-auth==1.14.1
google-cloud-bigquery==1.24.0
google-cloud-core==1.3.0
google-resumable-media==0.5.0
googleapis-common-protos==1.51.0
greenlet==0.4.15
gunicorn==20.0.4
httplib2==0.17.3
humanize==0.5.1
idna==2.9
ijson==2.6.1
importlib-metadata==1.4.0
impyla==0.14.0
infi.clickhouse-orm==1.0.2
iso8601==0.1.12
isodate==0.6.0
itsdangerous==1.1.0
Jinja2==2.10.3
jmespath==0.9.5
jsonschema==3.2.0
kombu==4.6.7
Mako==1.1.1
Markdown==3.1.1
MarkupSafe==1.1.1
marshmallow==2.19.5
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.21.0
more-itertools==8.1.0
msgpack==0.6.2
mysqlclient==1.4.2
numpy==1.18.1
oauth2==1.9.0.post1
oauthlib==2.1.0
oscrypto==1.2.0
pandas==0.25.3
parsedatetime==2.5
pathlib2==2.3.5
ply==3.11
polyline==1.4.0
prison==0.1.2
protobuf==3.11.3
psycopg2==2.7.6.1
py==1.8.1
pyarrow==0.16.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
PyAthena==1.5.1
pybigquery==0.4.13
pycparser==2.19
pycryptodomex==3.9.7
pydruid==0.5.7
PyHive==0.6.1
PyJWT==1.7.1
pyldap==2.4.28
pymssql==2.1.4
pyOpenSSL==19.1.0
pyrsistent==0.15.7
python-dateutil==2.8.1
python-dotenv==0.10.5
python-editor==1.0.4
python-geohash==0.8.5
python3-openid==3.1.0
pytz==2019.3
PyYAML==5.3
redis==3.2.1
requests==2.23.0
requests-oauthlib==1.3.0
retry==0.9.2
rsa==4.0
s3transfer==0.3.3
sasl==0.2.1
selenium==3.141.0
simplejson==3.17.0
six==1.14.0
snowflake-connector-python==2.2.4
snowflake-sqlalchemy==1.2.1
SQLAlchemy==1.3.12
sqlalchemy-clickhouse==0.1.5.post0
sqlalchemy-redshift==0.7.1
SQLAlchemy-Utils==0.36.1
sqlparse==0.3.0
tenacity==6.1.0
thrift==0.13.0
thrift-sasl==0.3.0
thriftpy==0.3.9
tornado==6.0.4
urllib3==1.25.8
vine==1.3.0
webencodings==0.5.1
Werkzeug==0.16.0
WTForms==2.2.1
WTForms-JSON==0.3.3
zipp==2.0.0
### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by bkyryliuk** [comment]
I am seeing similar issue sometimes, tweaking EMAIL_PAGE_RENDER_WAIT helps a bit to reduce the occurance

**Comment by ibotheperfect** [comment]
> I am seeing similar issue sometimes, tweaking EMAIL_PAGE_RENDER_WAIT helps a bit to reduce the occurance

When I increase it, I started to get this error

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/superset/app.py", line 114, in __call__
    return task_base.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/superset/tasks/schedules.py", line 374, in schedule_email_report
    deliver_slice(schedule)
  File "/usr/local/lib/python3.6/site-packages/superset/tasks/schedules.py", line 337, in deliver_slice
    email = _get_slice_visualization(schedule)
  File "/usr/local/lib/python3.6/site-packages/superset/tasks/schedules.py", line 305, in _get_slice_visualization
    driver.get(slice_url)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette
```

**Comment by singh-ab** [comment]
@iercan  : were you able to resolve the last error ? - `Failed to decode response from marionette` . I seem to be getting this when scheduling chart emails on superset - 1.0.0

**Comment by iercan** [comment]
@singh-ab using chrome webdriver solved issue for me.

**Comment by singh-ab** [comment]
I remember you mentioned this on one of the other issues I raised - https://github.com/apache/superset/issues/12867#issuecomment-770904265 

Gave that a try and doesn't help , any other inputs ?  probably I am missing some flag in the `config` ? 

I raised an issue specific to chart one with the details here - https://github.com/apache/superset/issues/12871
