### ISSUE TITLE
Autocopy link when clicking link or share buttons on Dashboards and Charts

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#10328]
**Is your feature request related to a problem? Please describe.**
As a dashboard producer / consumer, it'd be great if the UI can auto copy the link when selecting a share link or the link icon. 

**Describe the solution you'd like**
Users report that 90+% of the time, when they click on the little icon, they want to copy the link to my clipboard. It should autocopy the link, so that users don't need to click the 2nd icon. 

If user just wants to autocopy the link, autocopy automatically when clicking the first icon. A small message could display "link copied to clipboard". This will be 1-click solution instead of current 2-click solution.
If user wants to share via email, that can still remain as a 2-click solution. 

**Additional context**
![Screen Shot 2021-02-07 at 6 15 51 PM](https://user-images.githubusercontent.com/61221714/107168667-ceb2a580-6970-11eb-9942-5f686872c98d.png)

The exact same behavior should exist on Explore, and on Dashboard when user clicks "Share Chart"

**Comment by JunlinC** [comment]
🏷dashboard

**Comment by junlincc** [comment]
i can't believe this has not happened yet 🤦🏾‍♀️😆 @michael-s-molina can you squeeze this in this week? thank you so much!🙏

**Comment by junlincc** [comment]
closing in advance.
