### ISSUE TITLE
[SQL Lab] Make Query results table column width adjustable

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#10333]
**Is your feature request related to a problem? Please describe.**
As a data analyst I need to be able to modify the column width in SQL-lab results, so that my results are more readable.
Currently it's fixed width, and if I want to analyze / read data returned by a query it's difficult / impossible in some cases.

**Describe the solution you'd like**
Ideally I am able to adjust the column width in the result of a SQL Lab query.

**Comment by Steejay** [comment]
Heres an exploration that looks at introducing resizable column widths. feedback welcome! 

_default widths:_
default width = based on longest content in column
default max width = 360px

_resizable widths:_
min width = 32px
max width = none

_truncation+ellipsis:_
truncation + ellipsis is triggered anytime 
the cell content is cut off by the column

_tooltip:_
tooltip appears upon hover over a cell with 
truncated content. the tooltip will show the 
complete string.

![for Github](https://user-images.githubusercontent.com/60786102/107253121-db73df80-69ea-11eb-8571-364e7bf74c8f.jpg)


cc @zuzana-vej @yousoph @mihir174

**Comment by zuzana-vej** [comment]
closing as duplicate with https://github.com/apache-superset/superset-roadmap/issues/98
