### ISSUE TITLE
[SQL Lab] Copy SQL Lab result to clipboard in a way that you can paste directly into Google sheet 

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#10332]
**Is your feature request related to a problem? Please describe.**
As a superset user, I need the clipboard button which copies data, to copy the data in such a format that you can paste it right into a Google Sheet, including column names, without having first to save as CSV, then import the CSV, so that I save time while taking results from the SQL run.

**Describe the solution you'd like**
Feature expected requirements:
1. Copy will extract the resulting data (in table format) into the clipboard of the computer.
2. Pasting into a document should paste a table (not data which have spaces in between). Ideally it will be smart enough to limit the width of a column if there is massively long text in it.
3. Pasting into a spreadsheet should paste into correct individual cells (not one cell).
4. Ideally it should be smart enough not to pull quotation marks ("") that sometimes appear in the output of SQL lab when the value is numeric.
5. It should pull the entire dataset.
6. If the dataset is too large, it may be worth adding functionality to ask the user if they are sure they want to copy it (tell them it takes too long).
7. Data copied should include column names.
8. Ideally no 'formatting' is copied (eg., bold font).

**Comment by bkyryliuk** [comment]
+1 for this feature request

**Comment by yousoph** [comment]
I believe item 3 (Pasting into a spreadsheet should paste into correct individual cells (not one cell)) is solved by using "paste values only" (command + shift + V on a Mac) in Sheets. It's probably not obvious though so maybe there's more we can do to make it easier for the user.

**Comment by junlincc** [comment]
we should address 3 at product level as we have multiple clipboards buttons across the product.

**Comment by zuzana-vej** [comment]
duplicate with this roadmap item: https://github.com/apache-superset/superset-roadmap/issues/99
