### ISSUE TITLE
Boxplot is showing lines, and the min, max, median, 1st quantile, and 3rd quantile are the same.

### ISSUE THREAD

**Issue by edwardlxb** [apache/superset#10395]
Boxplot is showing lines instead of boxplots.
### Expected results
Show boxplot
what you expected to happen.
show boxplots
### Actual results
showed lines
what actually happens.
Standards
#### Screenshots
<img width="1179" alt="Screen Shot 2020-07-22 at 11 00 29 PM" src="https://user-images.githubusercontent.com/16586994/88192529-33294400-cc6f-11ea-9ca8-45717d423c0f.png">

#### How to reproduce the bug

1. Go to 'boxplot'
2. select 'Group by' numbers and 'matrices', then query.
3. See error

### Environment

(please complete the following information):

- superset version: `superset version`: 0.36.0
- python version: `python --version`: 3.6
- node.js version: `node -v` 14.0.0
- npm version: `npm -v`6.14.5

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [y] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [y] I have reproduced the issue with at least the latest released version of superset.
- [y] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
There was an issue in 2016, but it's closed. Now I'm facing the same issue. 

Appreciate all the hard work, and making this framework opensource!

**Comment by JunlinC** [comment]
Hi, we may not get to this issue as we will be replacing the current box plot with Echarts box plot soon.
