### ISSUE TITLE
Superset colors on deck.gl geojson

### ISSUE THREAD

**Issue by jbsilvalink** [apache/superset#10409]
After creating a data visualization in apache superset using the deck.gl geojson I was expecting to be able to change the colors of both the line and the fill of the polygon created using the color picker in the geojson settings.

### Expected results

Using the color picker the color would update to the color I selected.

### Actual results

Nothing happens, both the stroke and the fill remain black.

#### Screenshots

![geojson colors](https://user-images.githubusercontent.com/68691634/88281482-a8ccf880-ccdf-11ea-997e-fa4718225ee8.png)

#### How to reproduce the bug

1. Create a chart with the option deck.gl Geojson
2. After the map and the polygons are loaded change the colors in the picker provided

### Environment

- superset version: 0.36.0

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Are folks still seeing this in Superset 2.0.1? Hoping to validate that, but otherwise tempted to close it as stale.

**Comment by rusackas** [comment]
Perhaps @daniel10012 has the requisite data to test easily?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
