### ISSUE TITLE
Hide the 'Edit dashboard' button on standalone

### ISSUE THREAD

**Issue by aspedrosa** [apache/superset#10413]
**Is your feature request related to a problem? Please describe.**
On the project that I'm working on, when we want to display a dashboard we always use the standalone mode, since it removes the navbar from superset that we don't use while analyzing the data.
We are left with the header and the charts. The former has the title, published status, favorite star, the 'Edit dashboard' button and its dropdown.
Currently to hide some elements such as the favorite star we add some css to the dashboard (`display: none`).
However if we do the same to the 'Edit Dashboard' button, every time we need to edit the dashboard we need to comment the css from the button, edit the dashboard and then uncomment back.

**Describe the solution you'd like**
If the standalone flag was on the url, the 'Edit Dashboard' wouldn't be displayed/rendered.

**Describe alternatives you've considered**
Besides the 'Edit Dashboard' button I also thought on not rending the other elements, leaving just the dropdown. Don't know if this is to much though.

I checked the react code and the is no `standalone` prop on the component rending these elements ('Edit Dashboard' button and so on).

**Additional context**
:no_mouth:

**Comment by zufolo441** [comment]
Did you try with CSS?
.standalone button.slice-header-controls-trigger {
    display: none;
}

**Comment by aspedrosa** [comment]
It does hide the drop down on each chart but the 'Edit dashboard' its still being rendered

**Comment by zufolo441** [comment]
Sorry, wrong CSS.
This will hide the entire header, including menu:

.standalone .dashboard-header {
    display: none;
}

**Comment by aspedrosa** [comment]
Hmm, its an option to consider. Thanks :+1: 
But maybe I want to keep, at least, the dashboard title

**Comment by amitNielsen** [comment]
Maybe managing viewer/editor permission for a dashboard can work for you 
https://github.com/apache/incubator-superset/issues/10408

**Comment by aspedrosa** [comment]
@amitNielsen yeah, I think that might be a possible solution.
If you end up creating a PR link this issue. Or I can close it now and say that your SIP solves this.

**Comment by amitNielsen** [comment]
I already associated between the 2 
Basically what you're asking is just another filter type in the dashboard filter component

I'll let you know when you're specific feature can be implemented as part of that SIP

**Comment by aspedrosa** [comment]
#10408

**Comment by amitmiran137** [comment]
update: you can now use the following technique 
Standalone=1 (hide only navigation bar
Standalone=2 (hide navigation bar and dashboard title)

also there is a specific permission you can choose to assign/deassign from a role and it will show/hide the edit button accordingly

**Comment by qixinbo** [comment]
> 
> 
> update: you can now use the following technique
> Standalone=1 (hide only navigation bar
> Standalone=2 (hide navigation bar and dashboard title)
> 
> also there is a specific permission you can choose to assign/deassign from a role and it will show/hide the edit button accordingly

@amitmiran137 It seems that "Standalone=2" has a conflict with "Set auto-refresh interval". 
For example, the refresh interval is set to 10 seconds. With "standalone=1", the refresh goes well, but when "standalone=2", the refresh is deactivated.
May you please check it?
