### ISSUE TITLE
Integrity error, probably unique constraint

### ISSUE THREAD

**Issue by danilostochi** [apache/superset#10428]
### Expected results
save two tables with the same names but which have different schemes.

### Actual results
when trying to call as different schema tables, we have an error.
"Integrity error, probably unique constraint"

what actually happens.

#### Screenshots
![image](https://user-images.githubusercontent.com/68624533/88449957-88a55280-ce21-11ea-9f9c-63418c97bf3b.gif)

#### How to reproduce the bug

1. Go to 'Sources > Tables'
2. Click on '+New, Database-> Schema->Table Name '

### Environment

(please complete the following information):

- superset version: 0.36.0
- python version: Python 3.6.9
- node.js version: v8.10.0

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rvanaalderen** [comment]
Had the same problem in release 0.36 and 0.37. I hope it will be fixed soon.

**Comment by etr2460** [comment]
I think https://github.com/apache/superset/pull/5449 is related to this, will tag @john-bodley as an owner here to provide more context

**Comment by rusackas** [comment]
I don't _think_ this bug exists in newer/supported versions of Superset. As we no longer support 0.x.x versions, I'm going to go ahead and close this issue. If anyone sees this issue persisting in 1.5.x or 2.0.x releases, let's re-open with more current reproduction steps. Thank you!

**Comment by hanslemm** [comment]
I have this error too when trying to change roles. Do you guys have any clue on how to fix it? The error message is too broad and no logs to help.

**Comment by rusackas** [comment]
@hanslemm what version of Superset are you running. The prior comment was running 1.5, which hasn't been supported in quite some time. If this is an issue in 3.x, we can re-open (though it'd be MUCH nicer to open a fresh issue with updated context, rather than rekindling an antique issue)

**Comment by hanslemm** [comment]
Hey @rusackas, yes, my error is with the version 3.1.0, but started before even upgrading it, in the 2.1.0.

I will raise a ticket.
