### ISSUE TITLE
can not parse table if blank after punctuation while using sql_parse.py

### ISSUE THREAD

**Issue by SilvesSun** [apache/superset#10491]
take sql `select * from ods.  tmp_table a` for example. the sql_parse can not parse correct table name `ods.tmp_table` but return table as `set([])`

**Comment by willbarrett** [comment]
Thanks for the bug report @SilvesSun. If you have a recommended fix we'd be excited!

**Comment by SilvesSun** [comment]
@willbarrett sqlparse has method get_parent_name, why not use this to get parent name?

**Comment by rusackas** [comment]
This does not seem to be an issue in current-era Superset. If someone finds otherwise, please elaborate with updated version info and reproduction steps. Thanks!
