### ISSUE TITLE
[dashboard edit] No Switch to view mode option

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#10543]
#### How to reproduce the bug

1. Go to Dashboard
2. Click on "Edit", dashboard will be in edit mode
3. Now I want to switch back to view mode **without** any change:

### Expected results

<img width="1152" alt="Screen Shot 2020-08-06 at 2 56 24 PM" src="https://user-images.githubusercontent.com/27990562/89586701-0c354b00-d7f5-11ea-8ebb-1319c93dbf05.png">

<img width="378" alt="Screen Shot 2020-08-06 at 3 21 19 PM" src="https://user-images.githubusercontent.com/27990562/89588446-81564f80-d7f8-11ea-9679-328693d8dc1d.png">

### Actual results

<img width="1374" alt="Screen Shot 2020-08-06 at 2 44 50 PM" src="https://user-images.githubusercontent.com/27990562/89586272-3e927880-d7f4-11ea-98f4-07c4cfadfb4c.png">

Click "DISCARD CHANGES" will reload page, it will take some time (if dashboard is large). **And** if user was in a tab, reload page will lost user's previous focused tab.

The old behavior is, if there is no change in the dashboard, we show "SWITCH TO VIEW MODE" button, and click button will only switch mode, no page reload.

I understand Colors button is confusing. But now we do not want the functionality to change dashboard color-scheme?

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Related to #10394 

@mistercrunch

**Comment by graceguo-supercat** [comment]
ping @mistercrunch @rusackas What do you think of setting color scheme function for dashboard? Do we just remove it?

**Comment by junlincc** [comment]
> What do you think of setting color scheme function for dashboard?

do you mean, instead of setting it in the modal, have the setting on the dashboard?

**Comment by etr2460** [comment]
@graceguo-supercat could you reply to Junlin here? Thanks!

**Comment by graceguo-supercat** [comment]
Dashboard header controls are refactored. This is not an issue anymore.
