### ISSUE TITLE
Restrict number of failed login attempts

### ISSUE THREAD

**Issue by gk1089** [apache/superset#10560]
**Is your feature request related to a problem? Please describe.**
In its default state, the Superset login page permits any number of failed login attempts. This has been flagged as a security issue by our sysadmin team, and I agree with them. I have only tested users created in the database and have not tried other authentication methods.

**Describe the solution you'd like**
The login page should permit, say, 3 incorrect login attempts and should ask the user to try again after a period of time. This time should be customizable from the config file.

**Describe alternatives you've considered**
I am not sure if this already works for other authentication methods.

**Additional context**
None.

**Comment by JunlinC** [comment]
🏷 security

**Comment by nytai** [comment]
This issue is probably better suited for https://github.com/dpgaspar/Flask-AppBuilder. You could also implement your own custom security manager and override the login method, there should be info on how to do this in the flask_appbuilder docs.

**Comment by etr2460** [comment]
I'm going to close this since the issue should probably exist in Flask-AppBuilder instead. Feel free to file an issue in that repo, then once it's implemented there we can upgrade the version of FAB that Superset uses.

cc @dpgaspar
