### ISSUE TITLE
sslmode keyword is not recognized by superset

### ISSUE THREAD

**Issue by tiago-as** [apache/superset#10565]
I was trying to use mysqldb python module to connect to mariadb as I stated in this issue: https://github.com/apache/incubator-superset/issues/10495
After some research I figured why not try to use pymysql as shown here: https://docs.sqlalchemy.org/en/13/core/engines.html#mysql

I was getting some good feedback since the errors from the server were changing. Eventually Superset gave me an error requesting the pynacl module besause we are using ed25519 on the database I want to connect to. After installing the pynacl module I provided the following parameters to the connection:

URI: **mysql+pymysql://username:pwd@host/database**
Extra parameters (from here https://superset.incubator.apache.org/installation.html#ssl-access-to-databases ):
```
{
    "metadata_params": {},
    "engine_params": {
          "connect_args":{
              "sslmode":"require",
              "sslrootcert": "<path_to_file>"
        }
     }
}
```

When testing the connection, the server gave me this error:
```
Unexpected error __init__() got an unexpected keyword argument 'sslmode'
ERROR:superset.views.core:Unexpected error __init__() got an unexpected keyword argument 'sslmode'
INFO:werkzeug:127.0.0.1 - - [10/Aug/2020 12:50:25] "POST /superset/testconn HTTP/1.1" 400 -
```

Am I doing something wrong?

Thanks in advance for any help

**Comment by tiago-as** [comment]
I was using Ubuntu 20.04 without success. I downgraded the operating system to Ubuntu 18.04 and to use Python 3.6. I was able to connect using PyMySQL with the following URI: **mysql+pymysql://USERNAME:PASSWORD@IP_ADDRESS/DATABASE**

And with the following JSON in the extra field:

```
{
    "metadata_params": {},
    "engine_params": {
         "connect_args":{
              "ssl": {
              "sslca": "<PATH_TO_CERT>"
            }
        }
     },
    "metadata_cache_timeout": {},
    "schemas_allowed_for_csv_upload": []
}
```

**Comment by tiago-as** [comment]
I've found this bug report on the Ubuntu launchpad, can be related: https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1888101

**Comment by mak705** [comment]
import psycopg2

conn = psycopg2.connect(
    dbname='yourdb', user='dbuser', password='abcd1234',
    host='server', port='5432',
    sslmode='verify-ca', sslrootcert="server-ca.pe"
)

got the same error `issue in resolving  connect() got an unexpected keyword argument 'sslmode'`

**Comment by villebro** [comment]
We're currently adding native functionality for validating root certs to Postgres (See #11720). Once this gets merged I am happy to collaborate on adding support to other dbs (e.g. MySQL), as it is fairly simple due to the driver taking care of the majority of the heavy lifting.

**Comment by junlincc** [comment]
@tiago-as please let us know if you need help on adding support to mariadb. 
closing it for now.
