### ISSUE TITLE
Hiding "EDIT DASHBOARD" button in an iframe

### ISSUE THREAD

**Issue by Mahaswami** [apache/superset#10564]
How to hide the "EDIT DASHBOARD" button in an iframe for the public role users instead of disabling?

**Comment by amitNielsen** [comment]
#10408

**Comment by zufolo441** [comment]
adding ?standalone=true to URL and adding following CSS to dashboard:

.standalone button.slice-header-controls-trigger {
    display: none;
}
.standalone .dashboard-header {
    display: none;
}

this hides dashboard title, including button, and edit menu of charts.

**Comment by amitmiran137** [comment]
try standalone=2 as a query param
