### ISSUE TITLE
Click handler for slice/chart

### ISSUE THREAD

**Issue by Mahaswami** [apache/superset#10563]
We have an embedded dashboard using iframe. We need to trigger a function when clicking on chart. 
How to integrate click handler for a particular chart?

**Comment by JunlinC** [comment]
🙏 @willbarrett

**Comment by willbarrett** [comment]
Unfortunately my strong suit is not front-end. @rusackas or @nytai might be able to help.

**Comment by amitmiran137** [comment]
this is start to be adopted across the various charts
you can test it out with enabling the DASHBOARD_CROSS_FILTERS
and setting the Echart Piechart
