### ISSUE TITLE
deck.gl Polygon doesn't render anything, shows error

### ISSUE THREAD

**Issue by sazary** [apache/superset#10574]
When I try to render some polygons using deck.gl, it shows an error, noting that `TypeError: Cannot use 'in' operator to search for 'geometry' in undefined`.

### Expected results

Render polygons on screen. The datasource that I'm trying to render is this:

```
SELECT 
    now() as datetime, 
    name as name,
    ST_AsGeoJSON(polygon) AS polygon
FROM public.area_driverarea
WHERE 
    polygon IS NOT NULL 
    and not archived
limit 1
```

And the result is this:

```
2020-08-11T14:31:29.670272+04:30	اکباتان	{"type":"Polygon","coordinates":[[[51.302861661377,35.7162896874761],[51.310581661377,35.7169196869251],[51.3356516613769,35.7117596914374],[51.3371016613769,35.7024896995422],[51.3341916613769,35.6999797017365],[51.301661661377,35.6993497022872],[51.302861661377,35.7162896874761]]]}
```

Please note that I've included the `datetime` column just to make sure that lacking a time column isn't the source of error.

### Actual results

It shows an error. You can see it in the screenshot below and this is printed in the browser's console:

```
react_devtools_backend.js:2273 TypeError: Cannot use 'in' operator to search for 'geometry' in undefined
    at I (27.2a2d76d7d2deda70e1c0.chunk.js:1)
    at Array.flatMap (<anonymous>)
    at Function.getDerivedStateFromProps (27.2a2d76d7d2deda70e1c0.chunk.js:1)
    at new V (27.2a2d76d7d2deda70e1c0.chunk.js:1)
    at yo (explore.e9de4d7e8c553ec56a7b.entry.js:2)
    at Ii (explore.e9de4d7e8c553ec56a7b.entry.js:2)
    at gs (explore.e9de4d7e8c553ec56a7b.entry.js:2)
    at lu (explore.e9de4d7e8c553ec56a7b.entry.js:2)
    at su (explore.e9de4d7e8c553ec56a7b.entry.js:2)
    at $s (explore.e9de4d7e8c553ec56a7b.entry.js:2)
```

#### Screenshots

![image](https://user-images.githubusercontent.com/1304109/89883783-e4235e80-dbdd-11ea-879f-a7cdb8b5a644.png)

#### How to reproduce the bug

1. Explore a chart with deck.gl polygon type.
2. Set it's polygon type to JSON

### Environment

(please complete the following information):

- superset version: `0.36.0`
- python version: `3.6.11`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional Context

I've noted that in the response of `explore_json` request, the `data` field is as follows:

```
"data":{
   "features":[
      {
         "count":1,
         "__timestamp":null,
         "elevation":1000
      }
   ],
   "mapboxApiKey":"[redacted]",
   "metricLabels":[
      "count"
   ]
}
```

I guess that `features` should include `geometry` field, and it isn't.

**Comment by etr2460** [comment]
@sazary could you check and see if this issue still occurs in Superset 1.1? We've had a number of releases since you filed this issue and it might be resolved now

**Comment by ETselikov** [comment]
@etr2460 yep it is still an issue

**Comment by sarthak** [comment]
Hey, I faced a similar problem. Turns out if you rename  your column name from 'Polygon' to something different like 'Countour' it works.

**Comment by rusackas** [comment]
Since this thread contains a fix/workaround, has been inactive for so long, and refers to a no-longer-supported version of Superset, I'll close it out. If it's still an issue, we can re-open this, or open a new one with updated context.

**Comment by xavier-GitHub76** [comment]
@sazary : Could you test with a column renamed ?

The name "polygon" seems to be a problem

cf. https://github.com/apache/superset/issues/15965
