### ISSUE TITLE
TIME GRAIN should change when 'DATE FILTER' is modified

### ISSUE THREAD

**Issue by Mahaswami** [apache/superset#10585]
'DATE FILTER' to behave in an automated choosing the 'TIME GRAIN'

- if 'Last Year' is chosen then Time Garain has to set to Months
- if 'Last Month' is chosen then Time Garain has to set to Weeks
- if 'Last Week' is chosen then Time Garain has to set to Days

**Comment by JunlinC** [comment]
🏷 filter

**Comment by junlincc** [comment]
@Mahaswami Hey, thanks for suggesting. We are in the process of improving time picker in Superset and would like understand your use cases. can you elaborate why such feature will be important to you? Thanks!

**Comment by amitmiran137** [comment]
you should check out the new version of superset. I believe those aspect are covered within
