### ISSUE TITLE
[SIP] Network Labeling for Charts

### ISSUE THREAD

**Issue by juen1jp** [apache/superset#10582]
*Please make sure you are familiar with the SIP process documented*
(here)[https://github.com/apache/incubator-superset/issues/5602]

### Motivation

We currently use superset for graphing network traffic flows. This leads to charts having large numerical suffixes such as k, m etc. It would be nice to be able to label Bytes transferred as kB, MB, GB, TB etc as well as flows as kb/s, Mb/s, Gb/s etc. Furthermore, we could also support IEC (base 2 instead of base 10) ie 1 kB = 1024 Bytes. These additions would greatly benefit folks using Superset for network monitoring.

### Proposed Change

This appears to a relatively straightforward addition with the way the number formatting is written. I would just add a new number format factory that would implement a labeling type for Bytes, bits, bits/s and bytes/s. We could throw in the IEC as well. 

### New or Changed Public Interfaces

This should have minimal impact. The new labeling would be added to the Format options in the chart controls. 

### New dependencies

I would not anticipate needing any new dependencies. 

### Migration Plan and Compatibility

I would not anticipate changes.

### Rejected Alternatives

Not quite sure this is applicable.

**Comment by Praytic** [comment]
@amitmiran137 Also interested to know that.

**Comment by juen1jp** [comment]
pls let me know if this was merged somewhere. I actually did some work on it and could most likely get a PR together if it is still needed.
