### ISSUE TITLE
Getting query timeout on running cassandra queries to create chart on Superset dashboard

### ISSUE THREAD

**Issue by amritkrishan** [apache/superset#10596]
Hi,

The issue is cassandra is unable to run raw query which is sent from superset to presto as it requires allow filtering to process query. I need some mechanism to add allow filtering clause in superset query builder. Can anyone please help on this?

**Comment by eugeniamz** [comment]
🏷️  database

**Comment by etr2460** [comment]
In Superset you can add filters to your queries both in Explore and SQL Lab. This should be supported, so i'm going to close out this issue
