### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by OSINTAI** [apache/superset#10624]
Uploading a large log file (170 mb) took around 20 minutes.

The queries take around 2 minutes to generate the visualization (countries data on World Map)

After the completion of the question, the browser crashed. After refreshing the page, it jammed.

Running Apache Superset on "Ubuntu 20.04, VMware, CPU: i7, allocated cores: 4, allocated RAM: 8 GB" hosted in Windows 10.

Thanks.

**Comment by willbarrett** [comment]
@OSINTAI please share your Superset version and relevant stacktrace from Superset so that we can help you on this issue.

**Comment by OSINTAI** [comment]
@willbarrett 
Thanks for the reply.
I am using version: 0.37.0
![st](https://user-images.githubusercontent.com/5264558/90557173-5d045680-e19a-11ea-8cf7-e460026f84f5.png)

**Comment by mistercrunch** [comment]
I don't understand the issue, is it something related to "Timeout" as the title suggests, or something around uploading? or visualizing country data?

**Comment by OSINTAI** [comment]
This is a description of the file and what I did:
* I have uploaded a 161 MB CSV file.
* It contains 29 columns and "764930" rows
* The data is text and numbers
* The upload took around 15 minutes and it was successful (screenshot).

When I started querying the data (country name, imported items, dates, validity date and 5 other values) to project it on the World Map, the query took around 2 minutes then a red "timeout" ribbon appeared. (Unfortunately, I did not take a screenshot).
As a workaround, I have run a simple query (country name and COUNT of imported items) and it worked.

![Success](https://user-images.githubusercontent.com/5264558/90689270-16812b80-e270-11ea-87a8-7ecba0bf5ccd.png)

**Comment by willbarrett** [comment]
@OSINTAI Superset is currently optimized to display aggregated data - displaying 700k+ points on a single map will tax the available memory in the browser, I believe. I'd be interested to see how much memory your browser uses after loading all of that and the associated shapes for the map into memory. To support your use-case, we would likely need to render the map on the back-end and send the image to the browser, which is likely out of scope for this project.

Is there any way you could aggregate your data together for display?
