### ISSUE TITLE
Hi Team , I am embedding superset demo URL in our web app using iframe. I need to include a javascript file "iframeresizer.contentwindow.min.js" to fit the height to content height of the screen

### ISSUE THREAD

**Issue by pallaviMN** [apache/superset#10638]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by etr2460** [comment]
Closing with not enough details. Feel free to file a new issue with more details with exactly what bug you're running into here
