### ISSUE TITLE
Hide "Edit chart metadata" and "Explore Chart" options in SliceHeaderControls when we embed URL in iframe

### ISSUE THREAD

**Issue by pallaviMN** [apache/superset#10640]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Neel-rishabhsoft** [comment]
This can be done by adding css

**Comment by pallaviMN** [comment]
yes, using"standalone" css its possible, but along "Edit Chart" and "Explore Chart" we want other options to be present, If we are doing via CSS and in future if they change class, again i have to modify.

**Comment by Neel-rishabhsoft** [comment]
Yes true this would merely be a workaround.

**Comment by etr2460** [comment]
This should now be supported after @amitmiran137's work putting this behind a permission. Keep an eye out for a new release or deploy from master
