### ISSUE TITLE
% symbol not displayed correctly in partition chart

### ISSUE THREAD

**Issue by aman101097** [apache/superset#10654]
When I try to display % display, it is displayed in its code rather as '%' symbol

### Expected results

'%' symbol should have been displayed from result

### Actual results

a&#x2f;c is getting displayed instead of '%' but on hovering it is getting displayed correctly

#### Screenshots

![image](https://user-images.githubusercontent.com/58933394/90857756-6fe97780-e3a2-11ea-983e-6aa9293c3aed.png)

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by aman101097** [comment]
@mistercrunch any idea why?

**Comment by etr2460** [comment]
It looks like this is a bug in the rendering of the Partition viz. If someone wants to take on a fix, you can find the code here: https://github.com/apache-superset/superset-ui/tree/master/plugins/legacy-plugin-chart-partition

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
