### ISSUE TITLE
Making a timestamp a column in a pivot table

### ISSUE THREAD

**Issue by malcomwilk** [apache/superset#10666]
Hi there y'all I was wanting to know the SQL code I'd have to write in order to make a timestamp a column in Apache Superset. My idea is to have a time stamp that will show data for the current year and 2 previous years. I'd like to try and make it update as time moves forward so that when we hit 2021 the data base will then show 2021 as the current year.

Would I use a could similar to this? Or would I need something more extensive to get the features I'm looking for?

    SELECT  distinct(dt) FROM mytable
WHERE 
    dt >= date_add('day', -7, from_iso8601_timestamp('{{ to_dttm.isoformat() }}'))
    AND
    dt <= date_add('day', 0, from_iso8601_timestamp('{{ to_dttm.isoformat() }}'))

**Comment by junlincc** [comment]
@malcomwilk hey, you should be able to do so, in pivot table v2 now:)
