### ISSUE TITLE
Option to select Dashboard tabs instead of default tab while scheduling emails on a Dashboard

### ISSUE THREAD

**Issue by Energytechglobal** [apache/superset#10686]
As per the documentation on [Email reports](http://superset.apache.org/installation.html#email-reports) from Superset, we are able to schedule and receive them on Dashboards. In a dashboard, there are can be multiple tabs and in our case, we are having multiple tabs and we are seeing snapshots for the default tab of a Dashboard, there is no provision to select a Dashboard tab while configuring it for a dashboard.

Provide an option to select tabs in a Dashboard while configuring Dashboards for notifications.

Snapshot for "Schedule Email Reports for Dashboards"
Adding an option for selecting the dashboard tab or in the Dashboard list box itself will be helpful ![image](https://user-images.githubusercontent.com/40420807/91289924-977c7d80-e7b0-11ea-97bf-7c8fe67e815c.png)

**Comment by bkyryliuk** [comment]
+1 to this feature request, it would probably be really hard to implement but nice to have

**Comment by suddjian** [comment]
Closing this in favor of #14056
