### ISSUE TITLE
How to make a crosstab？

### ISSUE THREAD

**Issue by TdzWork** [apache/superset#10694]
I can't find the charting function to do crosstab

**Comment by willbarrett** [comment]
Hi @TdzWork - can you elaborate? I'm not sure what a crosstab is.

**Comment by zhaoyongjie** [comment]
@TdzWork may be pivot table?

**Comment by TdzWork** [comment]
> Hi @TdzWork - can you elaborate? I'm not sure what a crosstab is.

like this. 
The value of the column is the original value, not the aggregate value
![1598578465(1)](https://user-images.githubusercontent.com/22335038/91511326-032a2c00-e912-11ea-9497-e9502ebff565.jpg)

**Comment by TdzWork** [comment]
> @TdzWork may be pivot table?

pivot table column values are aggregate rather than raw, and there is no concept of dimensions or measures, I don't think it meets my needs.

**Comment by suddjian** [comment]
We recently added a new pivot table to Superset. If it does not address your needs feel free to open.
