### ISSUE TITLE
Color scale in calendar heatmap not reflective of the actual values in the heatmap

### ISSUE THREAD

**Issue by CurtLH** [apache/superset#10696]
I'm using a calendar heatmap to show the number of records per hour/day within my dataset.  Here is my query:

<img width="433" alt="image" src="https://user-images.githubusercontent.com/6969525/91464967-0b1a9b00-e842-11ea-9260-4690a90f6d65.png">

While a chart is rendered in the format that I would expect, the colors are not what I would expect.  It seems that the max value on the color scale 28, but the majority of my values are above 28, so nearly everything in the heatmap is red.

<img width="1361" alt="Screen Shot 2020-08-27 at 8 51 03 AM" src="https://user-images.githubusercontent.com/6969525/91465301-7a908a80-e842-11ea-83e3-9a958151d749.png">

I know that I can change the color scale, but when I do that, the majority of the colors in the heatmap still remain whatever the max color is.  Is there a configuration setting that I'm overlooking to readjust the color scale?  I've tried re-running the query, but the output in consistent.

**Comment by JunlinC** [comment]
🏷charts

**Comment by PowerPlop** [comment]
It seems the colors of the heatmap are based on the raw values before aggregation.
If I use a grouping by day, the colors use the min and max of the input values instead of the aggregated values.

**Comment by CurtLH** [comment]
Has there been on progress on this bug?

**Comment by maloun96** [comment]
@CurtLH Can you please provide sample data? In CSV or in TEXT format, it will be very helpfully.

**Comment by CurtLH** [comment]
@maloun96 -- here is a sample of the data.  I'm not sure if it matches exactly to what was seen in the initial issue, but it should be close enough to get an idea of what the data looks like. 

[date_posted.txt](https://github.com/apache/superset/files/5990088/date_posted.txt)

**Comment by maloun96** [comment]
@CurtLH

**Comment by suddjian** [comment]
should be fixed by https://github.com/apache/superset/pull/13233
