### ISSUE TITLE
Cursor move up in legend in Arc chart

### ISSUE THREAD

**Issue by GGPay** [apache/superset#10701]
Cursor move up when tick in legend in Arc chart 

![Superset_legent_issue](https://user-images.githubusercontent.com/17413180/91505987-99b90780-e896-11ea-88e5-e38db6f64883.gif)

#### How to reproduce the bug

1. Add legend in Arc chart 
2. In "Arc" section - add "Categorical color"  - in my case - "AIRLINE" - save.
2. Move Arc chart in bottom section in dashboard
2. Click on legend
3. Cursor move up

![image](https://user-images.githubusercontent.com/17413180/91506440-b0ac2980-e897-11ea-961e-5301608b8031.png)

**Comment by JunlinC** [comment]
Thank you for reporting!  Welcome to join our slack if you have not, to provide more product feedback. https://app.slack.com/client/T7GMC60JX/G017M6QNUKA,

**Comment by graceguo-supercat** [comment]
close this since no recent follow-up
