### ISSUE TITLE
Annotation don't update when filter change

### ISSUE THREAD

**Issue by Leandro-GPIN** [apache/superset#10713]
When select a filter region the annotation don't update. 

We selected for example: North America. 

### Expected results

Chart: "Growth Rate and Annotation Region": 
- Bermuda 
- Canada 
- United States 
- Annotation, North America

### Actual results

Chart: "Growth Rate and Annotation Region": 
- Bermuda 
- Canada 
- United States 
- Annotation, North America
- Annotation, East Asia & Pacific
- Annotation, Europe & Central Asia
- Annotation, Latin America & caribbean
- Annotation, Middle East & North Africa
- Annotation, South Asia
- Annotation, Sub-Saharan Africa

#### Screenshots

![annotation_filter_error16](https://user-images.githubusercontent.com/19553149/91585167-1517c900-e92a-11ea-814a-b847b2b95be8.gif)

#### How to reproduce the bug

1. Create a new chart line with region group.
2. Add the new chart as annotation in Growth Rate chart.
3. Save as "Growth Rate and Annotation Region".
4. Select region in Region Filter .
5. See error in  "Growth Rate and Annotation Region".
6. Annotation don't update when filter change.

####  Create a new chart line with region group

![chart_growth_rate_region](https://user-images.githubusercontent.com/19553149/91585088-f6b1cd80-e929-11ea-814a-e98f405889b5.png)

#### Add the new chart as annotation in Growth Rate chart.
![chart_growth_rate_and_annotation_region_config](https://user-images.githubusercontent.com/19553149/91571725-ce6fa200-e91c-11ea-9585-4692b7b870b3.png)

### Environment

- superset version: 0.37.0 with docker
- python version: 3.7
- node.js version: v14.8.0

### Checklist

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing this since:
* It hasn't had attention in years, sadly
* It's in reference to an old version of superset that is no longer supported.
* The FilterBox component referenced is on a path toward deprecation, in favor of Dashboard Native Filters.

If you're still experiencing this or similar issues using the new filters on a currently supported version of Superset, let's file a new issue or append updated details here, and we can re-open. Thanks!
