### ISSUE TITLE
Improve Custom D3 Formatting for Source Columns on table viz type

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#10729]
**Is your feature request related to a problem? Please describe.**
Currently not all viz types allows users to user d3 formatting for their data.  For example viz type big number with trendline allows this, but table viz type doesn't. There is a hacky workaround, where users can specify this in the edit Datasource --> Calculated Column section, but it would be much better user experience, is they can do it in the explore itself.

Current **hacky** solution:
![table viz 01](https://user-images.githubusercontent.com/61221714/91646367-33052c80-ea03-11ea-802a-b0c7d239f0cd.png)

**Describe the solution you'd like**
Enable users to easily define their column type on table viz, specifically custom d3 formatting. 

**Describe alternatives you've considered**
Current solution works but is really hacky and non intuitive for users.

**Option 1:**  Let users edit when clicking on column name in Explore table viz. 
![option 1](https://user-images.githubusercontent.com/61221714/91646356-136e0400-ea03-11ea-8a98-7378fac885ce.png)

**Option 2:** Add a dropdown with formatting options in Edit Datasource --> Calcualted Column section
![option 2](https://user-images.githubusercontent.com/61221714/91646359-1832b800-ea03-11ea-833f-f206419883f1.png)
.. Similar is available on big trendline viz type and other viz types

![trendline viz](https://user-images.githubusercontent.com/61221714/91646362-2385e380-ea03-11ea-965b-c0466f82009f.png)

**Option 3:** Enable both option (1) and (2), where option (1) saves the settings, but can also be visible and edited via option (2). This would provide users most flexibility.

**Additional context**
It would be great to also go through all the viz types and if there are other which don't allow this functionality, enable this for all viz types with as much consistency in the settings as possible across.

**Comment by vialcollet** [comment]
If my understanding is correct, this is still missing.
We can't specify any format in data table viz except if we setup calculated columns. This is resulting in such tables:

![image](https://user-images.githubusercontent.com/4971086/107810433-f177fc00-6d6c-11eb-9fff-19c32467ea30.png)

Or else I am missing somthing...

I am using 0.38.0
