### ISSUE TITLE
Data Preview Fails for Selected Tables

### ISSUE THREAD

**Issue by debbielee1996** [apache/superset#10735]
### Expected results

Data preview should show all tables in the same database without problems.

### Actual results

Table not loading for this particular table.
![image](https://user-images.githubusercontent.com/62943444/91693570-c96d5580-eb9d-11ea-94f9-911fca16f280.png)

**Error message in debug mode:**
Triggering query_id: 6
INFO:superset.views.core:Triggering query_id: 6
timeout can't be used in the current context
WARNING:superset.utils.core:timeout can't be used in the current context
signal only works in main thread
Traceback (most recent call last):
File "/amundsen/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/superset/utils/core.py", line 584, in enter
signal.signal(signal.SIGALRM, self.handle_timeout)
File "/usr/lib/python3.6/signal.py", line 47, in signal
handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
ERROR:superset.utils.core:signal only works in main thread
Traceback (most recent call last):
File "/amundsen/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/superset/utils/core.py", line 584, in enter
signal.signal(signal.SIGALRM, self.handle_timeout)
File "/usr/lib/python3.6/signal.py", line 47, in signal
handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
Query 6: Executing 1 statement(s)
INFO:superset.sql_lab:Query 6: Executing 1 statement(s)
Query 6: Set query to 'running'
INFO:superset.sql_lab:Query 6: Set query to 'running'
Query 6: Running statement 1 out of 1
INFO:superset.sql_lab:Query 6: Running statement 1 out of 1
Query 6: <class 'pyodbc.ProgrammingError'>
ERROR:superset.sql_lab:Query 6: <class 'pyodbc.ProgrammingError'>
INFO:werkzeug:172.22.0.6 - - [14/Aug/2020 09:15:10] "POST /superset/sql_json/ HTTP/1.1" 500 -

#### How to reproduce the bug

1. start docker-compose
2. start superset
3. navigate to tables under localhost:5000
4. certain tables will be able to allow users to preview, some others will fail... (I'm not sure but I'm guessing it might have to do with the data types of the tables?)

### Environment

- Amunsen version used: latest version I believe
- Ubuntu 18.04 LTS
- Firefox v79

- superset version: 0.36.0
- python version: 3.6.9

the commands to check versioning didn't work so I looked up on the docs at https://github.com/amundsen-io/amundsenfrontendlibrary
- node.js version: v10 or v12
- npm version: >- 6.x.x

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by vikalpmullick** [comment]
@debbielee1996 any success on this?

**Comment by debbielee1996** [comment]
unfortunately no...

**Comment by villebro** [comment]
@debbielee1996 can you test against a newer version of Superset? If this persists I can help figure out what needs to be changed either on Superset or Amundsen to make this work.

**Comment by vikalpmullick** [comment]
@villebro i have tried with superset 0.38. In my case the POST request from amundsen end is not reaching the superset end. 

//post req from superset client in amundsen//
requests.post(self.url, data=request_data, headers=headers)

Above returns with HTTPStatus.INTERNAL_SERVER_ERROR

I am using a superset with no authentication. (Public access)
