### ISSUE TITLE
Event to detect Superset Viz is loading/reloading & is loaded after filters applied/refreshed in custom JS used. 

### ISSUE THREAD

**Issue by Neel-rishabhsoft** [apache/superset#10734]
I have used a custom Javascript file to customise superset for client requirement which I have added in basic.html. But I am struggling to keep the changes on chart refresh as the charts get refreshed from superset side without any event on the windows. I have considered getting a on click/change event of filters but since everything is getting updated dynamically with react I am not able to do that either. 
Can anyone please suggest anything that I can use to detect the viz getting refreshed on my JS file.

Thanks.

**Comment by amitmiran137** [comment]
You can only get this type of event if you right you're own custom viz plugins
