### ISSUE TITLE
`Unknown Field` error when editing dashboards with `remote_id` and `import_time`

### ISSUE THREAD

**Issue by serenajiang** [apache/superset#10742]
When I try to edit the dashboard properties of a dashboard with the dashboard properties modal, if the dashboard has properties `remote_id` or `import_time` in the json metadata, I get the message `An error occurred`. The request error shows an `Unknown Field` error.

```json
{"message":{"json_metadata":[{"import_time":["Unknown field."],"remote_id":["Unknown field."]}]}}
```

### Expected results
The dashboard should save.

### Actual results
Error.

#### Screenshots
![image](https://user-images.githubusercontent.com/14146019/91745351-b2177380-eb6f-11ea-828c-453f9ee0ec30.png)

#### How to reproduce the bug

1. Import a dashboard (or use existing imported dashboard)
2. Navigate to imported dashboard, open dashboard properties modal (edit dashboard properties)
3. Check the json metadata (Advanced) and confirm `remote_id` and `import_time` are properties
4. Save the dashboard properties.
5. Observe error.

### Environment

(please complete the following information):

- superset version: Up to date with apache/master as of August 25, 2020
- python version: `python --version` 3.6

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

cc: @graceguo-supercat

**Comment by serenajiang** [comment]
@dpgaspar ?

**Comment by michellethomas** [comment]
Seeing this issue again. It looks like [validation](https://github.com/apache/superset/blob/2ff874124840561277b1c480803fda55d11fb0c5/superset/dashboards/schemas.py#L106) is happening on json_metadata when saving dashboard metadata. These fields are not in the valid schema so they are erroring.

@betodealmeida it looks like `remote_id` and `import_time` are related to import/export feature. I still see these fields used in the codebase, should they be added as a valid field in json_metadata? Or do you know who would know?
