### ISSUE TITLE
Superset Permissions 

### ISSUE THREAD

**Issue by Asturias-sam** [apache/superset#10749]
For Gamma Users we have given SQL LAB access and access to all the databases, so we have give the following roles :
`all_database access on all_database access , all_datasource access on all_datasource access, all_query access on all query access`

1. Now Gamma users can see the charts created by others but they can't see the dashboard created by others Is this expected ? 
2. Can we have some permissions to see dashboard from others as in the case of charts  ?
3. Can we restrict gamma users to see charts from other Gamma users with access to all data sources ?

**Comment by amitNielsen** [comment]
Here is a proposal on Dashboard access permission  that might help
https://github.com/apache/incubator-superset/issues/10408
