### ISSUE TITLE
superset-logo@2x.png static asset missing from pip distribution

### ISSUE THREAD

**Issue by brokenjacobs** [apache/superset#10756]
The logo is broken in the install from pip currently. Version 0.37.0

### Expected results
The log displays

### Actual results
You get a broken image.

#### Screenshots
![image](https://user-images.githubusercontent.com/3159463/91906705-e1a8a780-ec65-11ea-9073-6be58e74c75c.png)

#### How to reproduce the bug
Install superset and load it

### Environment
I downloaded the image from a site online and placed it in the static assets directory... and then I had a logo.

**Comment by brokenjacobs** [comment]
Dead project?

**Comment by amitmiran137** [comment]
could you check if this is still happening on a newer version?
