### ISSUE TITLE
Uncaught Error: Target container is not a DOM element.

### ISSUE THREAD

**Issue by badman-rodriguez** [apache/superset#10812]
When running `npm run dev-server` this route:
`http://localhost:9000/chart/add` Leads to a React JS error: Uncaught Error: Target container is not a DOM element.

Which indicates that the Dom isnt available yet for the React Scripts to kick off. 
This only happens when kicking off `webpack-dev-server`

It works just fine when running the app without webpack-dev-server.... so it must be a config issue, but not sure what it could be.

Any insight would be great on this.

Node: 12.14.1
typescript 3.8.3
Superset:  0.37.0 as of (2020/08/01 06:59 +00:00)

**Comment by thisishantzz** [comment]
I too am getting this error. It does not happen all the time. I encounter this only when try to add a chart (on the page /chart/add). Adding a database, table or dashboard works fine.

**Comment by rusackas** [comment]
Closing this as it should not be an issue in more current/supported versions. If anyone is seeing this in 1.5.x or 2.0.x, please say the word, and we'll re-open it!
