### ISSUE TITLE
Add description for "Hours offset" in datasource menu

### ISSUE THREAD

**Issue by zhaoyongjie** [apache/superset#10825]
Hi, All, "Hours offset" is newest introduce by Apache Supsert, I can not find any detail in document, any one can help me? 

<img width="899" alt="image" src="https://user-images.githubusercontent.com/2016594/92682431-e9053a80-f362-11ea-8eec-dbc3675bb2ee.png">

**Comment by JunlinC** [comment]
Thanks @zhaoyongjie for reporting. we will include details in our new doc, thanks!🙏  @eugeniamz

**Comment by mistercrunch** [comment]
Ideally it should be simple help-text bellow the form field. Should be something like "Number of hours to be added or subtracted from the time column. This can be used to move say UTC time to local time."

Longer term as we get deeper into time, the actually metadata we need is the timezone and for it to be defined at the column level.

**Comment by rajatRS** [comment]
Is this issue is fixed or anyone is working on this ? 
If not then may I look forward to solve the issue. :)

**Comment by JunlinC** [comment]
> Is this issue is fixed or anyone is working on this ?
> If not then may I look forward to solve the issue. :)

Thanks for offering help! please reach out to @srinify in slack.

**Comment by srinify** [comment]
Hey @rajatRS let me know how I can help! I'm Srini Kadamati in our Superset community Slack, feel free to DM me there!

Some helpful links:

- General contributing guide: https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#types-of-contributions
- Video guide on how to contribute: https://youtu.be/zAWVE0TwMiU
- Docs on our docs: https://github.com/apache/incubator-superset/tree/master/docs

**Comment by yousoph** [comment]
Proposed copy for the description: 

The number of hours, negative or positive, to shift the time column. This can be used to move UTC time to local time.

**Comment by majnun1337** [comment]
Why the Hours offset doesn't support float values? I need float values for IST (+5:30)
