### ISSUE TITLE
Add to Line Chart ability to select x-axis other than date field, or add a new Line Chart that is not time series

### ISSUE THREAD

**Issue by eugeniamz** [apache/superset#10828]
At the moment, Line chart is a time series chart and X-Axis always is the date in the time section 

![image](https://user-images.githubusercontent.com/58375897/92760106-611d3180-f35e-11ea-9ed0-81f2b712a8de.png)
 
It would be a great addition to have Line Chart that allows X-axis to be any filed so can be used to compare trends despite without link with dates. 

Use case at the moment, I  want to compare different customers' growth by the month of Customer Acquisition date but all of them have a different start dates. 

For example this dataset : 
![image](https://user-images.githubusercontent.com/58375897/92762932-105b0800-f361-11ea-8b52-e06594687d42.png)

This is the best chart that I can do with the Line Chart 
![image](https://user-images.githubusercontent.com/58375897/92763068-2e286d00-f361-11ea-9fef-c0a1c1663a23.png)

If I create a metric as the:  datediff('month', start_date,sales_date) I would like to be able to do a chart like this. 
![image](https://user-images.githubusercontent.com/58375897/92761791-0258b780-f360-11ea-9c8f-81b594343e1a.png)

It is possible with Bars but it is harder to see trends and do comparison with the bars, in addition, bars get even more confused when the field to breakdown has many distinct values 
![image](https://user-images.githubusercontent.com/58375897/92763917-f40b9b00-f361-11ea-8db8-f957977e88ea.png)

**Comment by bkyryliuk** [comment]
dropboxers are requesting a similar feature

**Comment by JunlinC** [comment]
🏷chart

**Comment by junlincc** [comment]
will implement numeric and categorical line chart with new echarts soon

**Comment by eugeniamz** [comment]
@junlincc  any ETD?

**Comment by amitmiran137** [comment]
this chart is support the above and more
https://5fec4c81935a8c002151e85f-nfsmejbgts.chromatic.com/?path=/story/plugins-composed-chart--all-types
https://github.com/nielsen-oss/superset-viz-plugins/

**Comment by x670** [comment]
> will implement numeric and categorical line chart with new echarts soon

how soon?

**Comment by stephanclaus** [comment]
Hi, this feature would be very much appreciated.

**Comment by villebro** [comment]
@x670 @stephanclaus this is being worked on right now (some recent development linked to this old issue: #822)

**Comment by villebro** [comment]
@ValentinC-BR , this is already fairly stable on master branch. Just enable the `GENERIC_CHART_AXES` feature flag.

**Comment by ValentinC-BR** [comment]
Didn't see that, thanks !

Since when (which version) is this feature available ? I have some troubles finding it, and we're still in 1.5 in our company.

**Comment by villebro** [comment]
I't not really ready on 1.5, so I do recommend waiting until the forthcoming 2.1 release (release date still unknown). But if you want to take a sneek peak and do some early testing, please try out master branch locally with the relevant feature flag enabled.

**Comment by ValentinC-BR** [comment]
Got it, thanks.

We'll wait for the 2.1 then.

**Comment by rusackas** [comment]
2.0.1 would be a good release for those looking to upgrade. Meanwhile, since this feature is out there in the wild, I'll go ahead and close the issue for now. Bugs and whatnot can be taken up in new threads! Thanks!

**Comment by Anandappak** [comment]
Line chart x-axes label without time: how to create?
