### ISSUE TITLE
Non-defined database in Datasource Editor if database not exposed in SQL Lab

### ISSUE THREAD

**Issue by john-bodley** [apache/superset#10833]
The same table selector component is used in both SQL Lab and the Datasource Editor for selecting the database, schema, and table. The issue is the same [filiters](https://github.com/apache/incubator-superset/blob/master/superset-frontend/src/components/TableSelector.jsx#L287-L292) are used for both which excludes databases which are not exposed in SQL Lab (I believe the component was primarily added for SQL Lab). 

This is problematic for the Datasource Editor if the underlying database is not exposed in SQL Lab and thus the database/schema fields are empty.

### Expected results

The table selector should show all the databases.

### Actual results

The table selector only shows the databases which are exposed in SQL Lab.

#### Screenshots

<img width="403" alt="Screen Shot 2020-09-10 at 3 32 41 PM" src="https://user-images.githubusercontent.com/4567245/92816972-f1696f80-f37a-11ea-8770-3938a8dcee62.png">

#### How to reproduce the bug

1. Go to a chart backed by a database not exposed in SQL Lab.
2. Click on "Edit Datasource" -> "Settings".
3. Observe that the database/schema fields are empty.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by lilykuang** [comment]
issue should be fixed on this pr https://github.com/apache/incubator-superset/pull/10914

**Comment by nytai** [comment]
@john-bodley would you mind verifying if this is still an issue on the latest version of master?

**Comment by john-bodley** [comment]
@nytai I'll verify this on Wednesday during our weekly deployment.
