### ISSUE TITLE
Shortcuts Ctrl + r, Ctrl + s, Ctrl + t of Explore & SQL Lab

### ISSUE THREAD

**Issue by eugene-belarus** [apache/superset#10832]
There's no **Ctrl + r** hot key & **Ctrl + s** invokes default Chrome save page in Explore.
**Ctrl + t** invokes default Chrome new tab in SQL Lab.

_There's one Chromium issue about Ctrl + t_
> Issue 33056: Ctrl keys: Ctrl-N, Ctrl-T and Ctrl-W no longer available to client side JavaScript in Chrome4

> In Chrome 4 it works similary to Firefox, except some keyboard combination:
> 
> - Ctrl + N
> - Ctrl + Shift + N
> - Ctrl + T
> - Ctrl + Shift + T
> - Ctrl + W
> - Ctrl + Shift + W
> 
> These combinations cannot get captured by Javascript.

### Expected results

All shortcuts work.

### Actual results

Explore hot key **Ctrl + r** does not exist.
Explore hot key **Ctrl + s** invokes default Chrome save page.
SQL Lab hot key **Ctrl + t** invokes default Chrome new tab.

#### Screenshots

Explore hot keys
![Screenshot 1](https://user-images.githubusercontent.com/71097330/92797918-2eeded00-f3bb-11ea-8481-9d7917ea972c.png)

SQL LAb hot keys
![Screenshot 2](https://user-images.githubusercontent.com/71097330/92797948-36ad9180-f3bb-11ea-9e2d-0df1ed38d34f.png)

#### How to reproduce the bug 1

1. Go to a chart
2. Press **Ctrl + r** & **Ctrl + s**
3. Hot key **Ctrl + r** does not exist
4. Hot key **Ctrl + s** invokes default Chrome save page

#### How to reproduce the bug 2

1. Go to SQL Lab
2. Press **Ctrl + t**
3. Hot key **Ctrl + t** invokes default Chrome new tab

**Comment by willbarrett** [comment]
Thanks for the bug report! We'll look into it.

**Comment by eschutho** [comment]
The UI has changed slightly, so I have created a new ticket to reflect the new UI: https://github.com/apache/superset/issues/12429

Can we close this ticket?

**Comment by junlincc** [comment]
> The UI has changed slightly, so I have created a new ticket to reflect the new UI: #12429
> 
> Can we close this ticket @junlincc?

yes! thank you so much @eschutho
