### ISSUE TITLE
[BUG] deck.gl scatterplot has black checkboxes instead of colored ones

### ISSUE THREAD

**Issue by s4ke** [apache/superset#10904]
On Chrome (Linux) Version 85.0.4183.83 (Official Build) (64-bit) the deck.gl scatterplot legend displays as black checkboxes instead of coloured ones. Firefox is unaffected.

### Expected results

Legend should have colored checkboxes instead of black checkboxes

### Actual results

Legend has black checkboxes

#### Screenshots

![image](https://user-images.githubusercontent.com/719760/93306201-d7f37800-f7ff-11ea-86de-6247dc201892.png)

#### How to reproduce the bug

1. Create a deck.gl scatterplot
2. Set Legend position to anything but none
3. Display data in the scatterplot

### Environment

- superset version: `0.37.0` (from amancevice/superset)
- python version: `3.6.12`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset. *(on 0.37.0)*
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by s4ke** [comment]
I just checked on a 0.36.0 installation and it has the same checkbox issues on Chrome.

**Comment by rusackas** [comment]
This issue is a bit of an antique, and I'm unable to reproduce it in the current version. If anyone sees this happening in 1.5.x or 2.0.x, please let us know proper repro steps and we can re-open it!
