### ISSUE TITLE
fix: don't force UPPER_CASE for adhoc metrics and filters

### ISSUE THREAD

**Issue by ktmud** [apache/superset#10920]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/335541/93391060-77763200-f823-11ea-835c-626cf968008f.png)

The select control forces UPPER_CASE for selected adhoc metrics/filters, which sometimes is inconsistent with the actual column names, filter values, and what would be showing in the chart.

**Describe the solution you'd like**

Remove `text-transform` for selected pills.

**Describe alternatives you've considered**

**Additional context**

**Comment by junlincc** [comment]
@eschutho
