### ISSUE TITLE
the picture is on the lower part of the web page

### ISSUE THREAD

**Issue by appleyuchi** [apache/superset#10927]
### Expected results
I want the picture to be in the center part of the web page.

#### Screenshots

![bug](https://user-images.githubusercontent.com/27613483/93437973-381d1380-f8ff-11ea-807b-f81468755925.png)

**Comment by appleyuchi** [comment]
if I press `Ctrl+0`,no luck...

**Comment by appleyuchi** [comment]
![bug](https://user-images.githubusercontent.com/27613483/93439399-17ee5400-f901-11ea-8279-3872f0cc44dc.png)

and words overlap with each other.

**Comment by zhaoyongjie** [comment]
Hi, @appleyuchi. have a trick, can do it.
1. append a "&standalone=true" parameter to explore url
2. zoom in / zoom out by browser can apply to sankey diagram

**Comment by appleyuchi** [comment]
Thanks for your replies,
but could you developers set it to center of the page automatically?
Much Thanks for your hard work~~~

**Comment by mistercrunch** [comment]
Can't reproduce, what version of Superset and Chrome is this?

**Comment by appleyuchi** [comment]
> Can't reproduce, what version of Superset and Chrome is this?

The Chrome is in Linux Desktop
Ubuntu Linux 20.04

The effect is in:
http://49.235.108.13:5000/superset/dashboard/2/

it's deployed in single node,so it's slow,
wait for 25 seconds please
