### ISSUE TITLE
Semicolon error in Explore

### ISSUE THREAD

**Issue by tooptoop4** [apache/superset#10945]
select * from table;

that query (with semicolon) runs fine in SQLLab but after clicking Explore on the results the Chart page gives an error about semicolon not allowed

**Comment by nytai** [comment]
@tooptoop4 I just tried this and was unable to repro. Can you confirm this is still an issue using the latest version of master?

**Comment by mistercrunch** [comment]
@tooptoop4 which version are you on?

**Comment by tooptoop4** [comment]
0.36

**Comment by amitmiran137** [comment]
@junlincc could we get a reproduction of this issue in a video?

**Comment by junlincc** [comment]
https://github.com/apache/superset/issues/12963 duplicate @amitmiran137 ^

**Comment by zuzana-vej** [comment]
addressed within https://github.com/apache/superset/issues/12963
