### ISSUE TITLE
SQL Lab does not show table names in the dropdown box

### ISSUE THREAD

**Issue by rimolive** [apache/superset#10940]
While selecting Database, schema, and table to inspect the table structure, I noticed that the table dropdown box only shows the schema name, not the table name. If I try selecting any of the options, I get an `An error occurred while fetching table metadata` error.

### Expected results

I can see the columns that belong to the table

### Actual results

An `An error occurred while fetching table metadata` error message appear

#### Screenshots

https://imgur.com/tfSfvyg

#### How to reproduce the bug

1. Go to 'SQL Lab > SQL Editor'
2. Click on any Database in the dropdown box
3. After refreshing the schema dropdown box, select any schema with tables
4. Check the tables dropdown box. It should appear only the schema name, not the tables name

### Environment

- superset version: `0.37.1`
- python version: `Python 3.6.12`
- node.js version: N/A
- npm version: N/A

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

N/A

**Comment by rimolive** [comment]
![](https://github.githubassets.com/images/icons/emoji/unicode/1f44d.png)

**Comment by mistercrunch** [comment]
What database engine is this?

**Comment by rimolive** [comment]
@mistercrunch The engine in question is Hive.

**Comment by bkyryliuk** [comment]
Hm, can't repro on the latest master for both hive & presto.
@rimolive maybe provide more info:
1. what hive version
2. what pyhive version

**Comment by fan-code** [comment]
> pyhive version is 0.6.1. As for hive version it's a bit more complicated. :)
> 
> Actually, we use Spark to enable a Hiveserver2 special implementation to run queries against it. Currently Spark 2.4.3 is being used but we have plans to use Spark 3.0.0.

I also find this question when I use superset to connect to SparkThrift server.
My  connection url is  hive://ip:port/default?auth=KERBEROS&kerberos_service_name=hive  . 
Spark version is 2.4.0, How can I solve this problem?

**Comment by fan-code** [comment]
> Hm, can't repro on the latest master for both hive & presto.
> @rimolive maybe provide more info:
> 
> 1. what hive version
> 2. what pyhive version

I also have the similar problem.  hive  connect is ok,  but when  connect to the sparkThrift，table scheme cann't appear table name, only  schema name and the schema_name's number is euqal to talbe_number. eg. ods database has 100 tables, now ,you will see 100 ods in table schema in superset's sqllab
url is hive://ip:10001/default?auth=KERBEROS&kerberos_service_name=hive 
hive version is 2.1.1+cdh6.2.0
pyhive version is 0.6.3

**Comment by rimolive** [comment]
Tracking requests from Superset UI, I see that when you select a Database the following URL is requested:
```
http://<superset-hostname><:superset_port>/superset/schemas/1/false/
```
Which returns a JSON with the following contents and populates the Schema selector:
```
{"schemas": ["main","examples"]} # This is just an example JSON output returned
```
When you select any schema, the following URL is requested:
```
http://<superset-hostname><:superset_port>/superset/tables/1/main/undefined/false/
```
This undefined in the URL clearly indicates that the Schema selector is not building the component correctly.

I'm still debugging the code and if I have a fix I'll cook a PR for it. Stay tuned!

**Comment by rimolive** [comment]
It is a bug in pyhive:

https://github.com/dropbox/PyHive/blob/master/pyhive/sqlalchemy_hive.py#L364

That line should not return `row[0]` since the result will be the schema name, not the table name. I'm going to propose a fix in pyhive.

Meanwhile, can this issue keep opened until pyhive team accept and fixes in latest releases?

**Comment by junlincc** [comment]
@rimolive Ricardo, any updates?

**Comment by rimolive** [comment]
Unfortunately, I did not have an answer from Spark community but definitely this is a compatibility issue between Spark HiveServer2 implementation and Hadoop one. For now, I have no idea how this can be fixed.

**Comment by WonderBeat** [comment]
Well, seems like we faced similar issue in Superset: 0.38.0
SQL Lab does not show tables. 
And as I can see it doesn't depend on DB (we use clickhouse and MSSQL)
Web UI behaviour is completely the [same:](https://github.com/apache/incubator-superset/issues/10940#issuecomment-700626663)
`http://<superset-hostname><:superset_port>/superset/tables/1/main/undefined/false/`

**Comment by sleshJdev** [comment]
The same issue for me. We use latest susperset container and clickhouse. Tables are not getting fetched in sql lab.
`http://172.28.128.14:30808/superset/tables/2/tutorial/undefined/false/` returns `{"tableLength": 0, "options": []}`

**Comment by codenamelxl** [comment]
This issue is because you use SparkSQL instead of HiveServer. Which give 
Check out: https://github.com/dropbox/PyHive/issues/150
There is a PR to add a SparkSQL Dialect to fix this issue: https://github.com/dropbox/PyHive/pull/247

**Comment by savermyas** [comment]
Confirming it's not working either with Superset `v1.3.2` and trino-python-client `0.306.0`

**Comment by srinify** [comment]
Removing this issue for now since it's been marked inactive, but please re-open with new re-production instructions if you're still encountering it on newer Superset versions! 🙏

**Comment by tikikun** [comment]
Hi I'm facing the same issue on superset 2.0.0 for Trino

**Comment by gerickt** [comment]
Same error here with Mysql on Azure

**Comment by rmannibucau** [comment]
My dirty fix in bootstrap script (docker) - but it is not compatible if the container is in readonly filesystem mode:

```sh
sed -i "380s/.*/        return [row[\"tableName\"] for row in connection.execute(text(query))]/" /app/.venv/lib/python3.10/site-packages/pyhive/sqlalchemy_hive.py
```
