### ISSUE TITLE
[Feature Request] Large CSV Dumps

### ISSUE THREAD

**Issue by kaplanmaxe** [apache/superset#10953]
Hey, all, I've talked to the Preset team a few times on this but wanted to formally document it here and have a place to discuss.

We run a Superset instance with 100+ users and one of the biggest issues users complain about **by far** is the lack of an ability to produce large CSV dumps. It really pains me to hear this as trust me, I cringe every time I hear this as well, however I've started to understand the use case a lot more. A lot of times users want to:

- Test POCs of integrations of third parties where they need to upload a CSV to an sftp bucket or something
- Export data to move it into another source
- Let's face it... some accountants are always going to use CSVs

**How we handle this today**

We have tables with well over 10 billion rows that are super wide and just increasing the row limit in Supeset doesn't work obviously because the browser can't handle it (not that a user is actually trying to export 10 billion rows, but 500k for example is very common).

We actually run Superset and metabase mainly because of the CSV issue. Metabase handles CSV dumps much better than superset atm. However druid is a very large part of our stack and metabase doesn't support druid SQL which makes the metabase feature very limiting as our end users don't want to learn druid native queries.

**Why this would be a really useful feature for superset**

You won't find a modern BI tool that's good for this feature, and for some reason, most OSS tools don't think about this use case. You won't find an OSS BI tool for example that's good for large Druid or Presto csv dumps (please correct me if I'm wrong :) ). This would be a really cool feature for Superset, especially since it's origins come from Druid.

**Comment by frafra** [comment]
Similar to #10331.

**Comment by zuzana-vej** [comment]
This has linked closed PRs, looks like majority of the request has been addressed. If any part of your request is still pending please reopen/open a new request with the trimmed description.
