### ISSUE TITLE
Attempting to edit a table column redirects to another table

### ISSUE THREAD

**Issue by jeremy-ecoenergy** [apache/superset#10965]
When trying to edit a table column, Superset redirects to another table's definition, followed by the table column listing. This happens across tables, regardless of the database type.

### Expected results

Being able to edit the table column.

### Actual results

It's redirected and I can't edit.

#### Screenshots

1. 
![Screenshot 2020-09-19 at 11 51 52 AM](https://user-images.githubusercontent.com/65153090/93661296-198a5a00-fa70-11ea-92c7-f523a17ad3ee.png)

2.
![Screenshot 2020-09-19 at 11 52 08 AM](https://user-images.githubusercontent.com/65153090/93661295-18f1c380-fa70-11ea-8aa3-98cc8b316d2b.png)

3.
![Screenshot 2020-09-19 at 11 52 12 AM](https://user-images.githubusercontent.com/65153090/93661292-155e3c80-fa70-11ea-8e23-e03d529a27d1.png)

#### How to reproduce the bug

1. Go to a table definition, then columns
2. Click on the edit button next to a column

### Environment

Present

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by JunlinC** [comment]
Thank you Jeremy for reporting, this issue will be prioritized. @benceorlai

**Comment by nytai** [comment]
This is weird indeed. @jeremy-ecoenergy as a work around you could use the datasource editor in explore to make changes to your table. 

<img width="1001" alt="Screen Shot 2020-09-22 at 6 38 15 PM" src="https://user-images.githubusercontent.com/10255196/93954613-e90e1e80-fd02-11ea-92c4-911a7ad623a4.png">
<img width="2325" alt="Screen Shot 2020-09-22 at 6 38 27 PM" src="https://user-images.githubusercontent.com/10255196/93954615-ea3f4b80-fd02-11ea-9077-d5b6d0014a52.png">
<img width="2480" alt="Screen Shot 2020-09-22 at 6 38 39 PM" src="https://user-images.githubusercontent.com/10255196/93954616-ead7e200-fd02-11ea-9b96-40d9dce6c430.png">

**Comment by mistercrunch** [comment]
This is happening in the "legacy table editor" which we're in the process of deprecating. It's related to an old bug in FAB where is stores the browser history in a session variable. The solution here is to deprecate the legacy table editor.

**Comment by jeremy-ecoenergy** [comment]
Explore -> edit datasource works fine for editing columns, but doesn't allow one to add new columns (which is why I'm trying to do). In this case it's a virtual table derived from an SQL query.

**Comment by benceorlai** [comment]
Hi @jeremy-ecoenergy 

There was a [pr](https://github.com/apache/incubator-superset/pull/10731) that fixed this in Superset 11 days ago. That improvement was made available in the cloud version a few days later so it should be working as expected. Could you confirm that it is now working?

**Comment by jeremy-ecoenergy** [comment]
It's not clear how this PR fixes the issue? The columns from the SQL query can't be synced.

I did find a workaround by using an incognito window and the legacy data source editor, but it was still buggy.

**Comment by benceorlai** [comment]
I might have misunderstood your explanation, sorry. You are correct, for *virtual* datasets, the column sync is not working at the moment. There is another PR [(PR-10645)](https://github.com/apache/incubator-superset/pull/10645) pending for that, we are working on it as we speak.

Additionally, this functional area is getting a lot of changes these weeks, the full extent of the work is shared publicly in the Superset roadmap here --> https://github.com/apache-superset/superset-roadmap/projects/1#card-45405983
