### ISSUE TITLE
Problem in scheduling email reports in superset 

### ISSUE THREAD

**Issue by kazemf78** [apache/superset#10996]
I want to enable scheduled email reports in superset (set up with docker). I installed geckodriver and firefox-esr but yet it doesn't work. It gives timeout (5min but the page itself loads less than 30s) or various other errors. Does anyone knows how to handle this or have a working config of superset inside docker which supports scheduled email reports?

### Expected results

i expected the dashboards and charts to be emailed properly with selenium webdriver!

### Actual results

some of errors i encountered

```NoSuchWindowException: Browsing context has been discarded```
```Failed to decode response from marionette```
```selenium.common.exceptions.InvalidSessionIdException: Message: Tried to run command without establishing a connection```
```selenium.common.exceptions.TimeoutException: Message: Timeout loading page after 300000ms```

#### How to reproduce the bug

just setup the superset or run its docker-compose with geckodriver and firefox-esr installed in Dockerfile and enable email scheduling and  try to schedule a dashboard email

and also I added following lines in Dockerfile to install firefox-esr and geckodriver
```
RUN apt-get update && apt-get install -y firefox-esr

RUN wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
RUN tar -x geckodriver -zf geckodriver-v0.24.0-linux64.tar.gz -O > /usr/bin/geckodriver
RUN chmod +x /usr/bin/geckodriver
RUN rm geckodriver-v0.24.0-linux64.tar.gz
```

and changed following lines in config.py
```
EMAIL_NOTIFICATIONS = True
ENABLE_SCHEDULED_EMAIL_REPORTS = True
WEBDRIVER_BASEURL = "http://superset:8088/"
```

**Comment by ali-bahjati** [comment]
I have the same problem.

@mistercrunch do you have any working Dockerfile and compose with that in Preset?

**Comment by aleksarias** [comment]
I'm also having the same issue. It only happens on one of the dashboards... the other dashboards send out fine.

**Comment by ali-bahjati** [comment]
@aleksarias could you say what is your config? (Because it doesn't work for me at all)

**Comment by aleksarias** [comment]
Relevant settings: 

> EMAIL_REPORTS_WEBDRIVER = "firefox"
> EMAIL_REPORTS_USER = "admin"
> WEBDRIVER_BASEURL = "https://mydomain.com/"
> WEBDRIVER_BASEURL_USER_FRIENDLY = WEBDRIVER_BASEURL

**Comment by singh-ab** [comment]
Was anyone able to get this fixed ? I am getting the same error - `Failed to decode response from marionette` after upgrading to `superset - 1.0.0` and using `python - 3.7.9`

**Comment by alafanechere** [comment]
Same error here using `superset v1.0.1`  with geckodriver `v0.29`. Webserver and  workers are running in Kubernetes. I tried to allocate `2G` of memory to my  worker pods but it did not change the problem, and the worker pod running the task is consuming way less than `2G` when I try to send a test email. 
I tried increasing render time related configs without more success :
* `SCREENSHOT_LOCATE_WAIT`
 * `SCREENSHOT_LOAD_WAIT`
 * `EMAIL_PAGE_RENDER_WAIT`

**Comment by alafanechere** [comment]
I finally got emailing working with a combination of the following steps : 
* Use new Alerts & Reports feature that comes with the v1 of Superset
* Install celerybeat to schedule the emailing and slack messaging according to the defined Alerts and Reports.
