### ISSUE TITLE
Feature Request: Add same chart to Tabbed Dashboard(multiple tabs)

### ISSUE THREAD

**Issue by junlincc** [apache/superset#11021]
Add charts to Tabbed Dashboard
Scenario:
- I have used the Tabs  feature to segregate various dashboards (Say Tab 1 and Tab 2).
- I have a couple of charts that are common to multiple dashboards(say date filter) and would like to add this multiple tabs.
**Current issue:**
- Charts used once in a tabbed dashboard cannot be used again in another tab.
![Screen Shot 2020-09-18 at 2 19 34 PM](https://user-images.githubusercontent.com/67837651/94039303-65911380-fd7c-11ea-809f-b83752bb8b7b.png)

(post on behalf)

**Comment by vialcollet** [comment]
Other use case would be to have the same chart but with different filters applied.
For example a line chart showing some stats for a given country and we would need several of these charts with each their own country filter.
In such case it will be required to have several instance of the line charts and several instance of the country filter with appropriate mapping.
This would be fantastic.

**Comment by Dirzel** [comment]
@junlincc, Would the solution suggested in #8303 work for this.

**Comment by junlincc** [comment]
> @junlincc, Would the solution suggested in #8303 work for this.

I believe #8303 is referring to a different request. @micimize but we would love to have your solution implemented in Superset.

**Comment by mona-mk** [comment]
This will be indeed useful. At the moment, we are repeating a lot of charts as a workaround, in order to accommodate having same charts in multiple tabs. I see that this issue is closed, does it mean no one cares about the feature request anymore? :)

**Comment by vialcollet** [comment]
Yes I think @junlincc closed the issue by mistake...

**Comment by nicklip** [comment]
@junlincc are there any plans to implement this feature? If not in SuperSet, maybe in Preset?

**Comment by machzqcq** [comment]
This is a basic feature for creating dashboards right ? Duplicating charts per dashboard seems very inefficient. Not sure why this issue is closed (and not reopened) without acknowledging the issue and neither fixing it ? I would definitely vote up for this.

**Comment by matteofazio** [comment]
Anyone find a solution for the above problem. I need to have the same filter box in 4 different tabs in order to visualize the selected filter in one tab also in others.

**Comment by kyledufrane** [comment]
This would be a great feature to get added!

**Comment by nategivens** [comment]
Just another vote to get this added as a basic feature.

**Comment by rusackas** [comment]
Agreed this makes sense as a feature... I hope someone reading this is willing to contribute it!

**Comment by DamiraReicherd** [comment]
This feature would be very useful!

**Comment by rusackas** [comment]
Anyone is welcome to contribute the feature, and/or start a Github Discussion if you want to seek input/help/volunteers.

**Comment by rfdccarvalho** [comment]
We need this feature

**Comment by alfredho811** [comment]
Having this feature added would be much appreciated
