### ISSUE TITLE
superset_node fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by codepic** [apache/superset#11043]
### Steps to repro

superset_node exits with code 1 when running the following command on Ubuntu 18.04

```bash
docker-compose up --build
```

### Expected results

```bash
superset_node            | No type errors found
superset_node            | Version: typescript 3.8.3
superset_node            | Time: 49404ms
superset_node            | <s> [webpack.Progress] 100% 
superset_node            | 
superset_node            |    7749 modules
```

### Actual results
```bash
superset_node            | 
superset_node            | npm ERR! code EBADPLATFORM
superset_node            | npm ERR! notsup Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
superset_node            | npm ERR! notsup Valid OS:    darwin
superset_node            | npm ERR! notsup Valid Arch:  any
superset_node            | npm ERR! notsup Actual OS:   linux
superset_node            | npm ERR! notsup Actual Arch: x64
superset_node            | 
superset_node            | npm ERR! A complete log of this run can be found in:
superset_node            | npm ERR!     /root/.npm/_logs/2020-09-24T13_16_42_389Z-debug.log
superset_node exited with code 1
```

#### How to reproduce the bug

1. Pull incubator-superset, branch master, commit 6181994084067a32883bb01db55356cc7aa4712b
2. cd incubator-superset
3. docker-compose up --build

### Environment

(please complete the following information):

- superset version: `6181994084067a32883bb01db55356cc7aa4712b`
- python version: `Python 2.7.17`
- node.js version: `v12.18.3`
- npm version: `6.14.6`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

superset_node succeeds with 8e9b0b3f1100120a14134c0ca0c5dd4dd4a9e8bb

**Comment by eschutho** [comment]
According to [FsEvents](https://www.npmjs.com/package/fsevents), that is a known warning, but should not fail the build. 
```
I'm getting EBADPLATFORM Unsupported platform for fsevents error.
It's fine, nothing is broken. fsevents is macos-only. Other platforms are skipped. If you want to hide this warning, report a bug to NPM bugtracker asking them to hide ebadplatform warnings by default.
```
Is this working on master? You mentioned that it's working on a fairly recent commit.

**Comment by villebro** [comment]
I assume this has resolved itself as we've bumped both Node and npm since this ticket was opened - @codepic please open a new ticket if this is still a problem.
