### ISSUE TITLE
Mongo and Cassandra connectors

### ISSUE THREAD

**Issue by joehoeller** [apache/superset#11053]
REQUEST: Ability to connect Superset to Mongo and Cassandra to run queries against it.
Apache Drill can connect to Mongo and Big Query can connect to Cassandra, so it's def possible.

There is Flask Mongo Alchemy - https://pythonhosted.org/Flask-MongoAlchemy/
SQLAlchemy can connect to Cassandra, apparently - https://www.cdata.com/kb/tech/cassandra-python-sqlalchemy.rst

How can we get this into Superset, even if we cant use sql syntax, cql is a fine option as well perhaps(?)

**Comment by mistercrunch** [comment]
We'd have to confirm that the implementation works for the type of queries that we run, with `.groupby(...)`, `.filter()`, and aggregation expressions like `SUM` and `COUNT`.
