### ISSUE TITLE
[table]Advanced Analytics for Table Viz

### ISSUE THREAD

**Issue by kkalyan** [apache/superset#11130]
**Is your feature request related to a problem? Please describe.**
As of now, there is no way to get Day over day or week over week increases (and percentages) in Table View. There is support for Time shift in Bar charts, but its not there in Table Visualization. 

**Describe the solution you'd like**
Table Viz needs to have Advanced Analytics section. This was described and attempted to implement earlier 
https://github.com/apache/incubator-superset/issues/2324
https://github.com/apache/incubator-superset/pull/2325

**Describe alternatives you've considered**
If backend support window functions like LAG, this would be possible. 
https://www.sisense.com/blog/computing-day-over-day-changes-with-window-functions/
Some of the backends (like MySQL, Druid) does not have support for windowing functions.

**Additional context**

**Comment by ktmud** [comment]
Could be related https://github.com/apache/incubator-superset/issues/9887

**Comment by junlincc** [comment]
@ktmud committed to this change from our end.

**Comment by ktmud** [comment]
Did I?

**Comment by ktmud** [comment]
Hi, @junlincc , I am indeed working on adding per-column adhoc formattting, but advanced analytics isn't planed for the near term or long term yet.

**Comment by rusackas** [comment]
I don't believe there's any current momentum to add this feature to the current Table plugin. I'll close this as a "won't fix" but if anyone is really clamoring for this feature, we should open it in an Ideas thread on Github Discussions and start the proposal there with updated context.
