### ISSUE TITLE
Prepared Statement/Stored Procedure support with Superset when using MySQL.

### ISSUE THREAD

**Issue by Neel-rishabhsoft** [apache/superset#11158]
I am trying to use prepared statement with superset, which is working fine when running on SQL Lab of superset. But, when moving to explore view the query is not working and superset is not able to visualize the data. 
### Expected results
The statements should work as a normal query works in MySQL and visualization should be possible.

### Actual results
This is my simple prepared statement:

**PREPARE stmt1 FROM 
	'SELECT 
   	    TaxName 
	FROM TaxRates
        WHERE Id = ?';
        
SET @ti = '1'; 

EXECUTE stmt1 USING @ti;**

Below is a screenshot of the Sql Lab view with results 

![image](https://user-images.githubusercontent.com/60099288/95048759-09c47400-0706-11eb-8f7a-ea25c0c2310d.png)

And this is a screenshot of results in explore view:

![image](https://user-images.githubusercontent.com/60099288/95048820-29f43300-0706-11eb-892b-409f58bef88f.png)

This is the query generated in explore view:

![image](https://user-images.githubusercontent.com/60099288/95048867-41cbb700-0706-11eb-8fb3-e484049dfed5.png)

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I am facing exactly similar issue when using a stored procedure.

Please let me know if I am doing anything wrong or if the Superset doesn't support such operations.
Hoping for a prompt reply from the community.

Thanks in advance.

**Comment by mare011rs** [comment]
Any update on this?

**Comment by Ananthagopi07** [comment]
is there any update on this?

**Comment by PriyaGanji** [comment]
![Screenshot (58)](https://user-images.githubusercontent.com/89193048/186584994-3673bb5a-f92e-4c9e-b010-29dd73810060.png)

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
