### ISSUE TITLE
Install results in broken welcome screen on MacOS

### ISSUE THREAD

**Issue by HappyMiner** [apache/superset#11171]
### Expected results

Following the steps on:
https://superset.apache.org/docs/installation/installing-superset-using-docker-compose

I expect to be able to use superset after doing "docker-compose up" and logging in.

### Actual results

I am able to login but only see a broken screen, displaying 3 items:
- "x" button
- "close" button
- broken image picture

#### Screenshots

Please see attached screenshot.
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/11057169/95200837-9c056e80-0811-11eb-861a-974a083737fd.png">

#### How to reproduce the bug

Follow instructions to install and run on MacOS as described in:
https://superset.apache.org/docs/installation/installing-superset-using-docker-compose

Login and find the broken page.

### Environment

(please complete the following information):

- superset version: `unknown`
There is no version information anywhere to be found. I did "git clone https://github.com/apache/incubator-superset.git" on TUE OCT 6th at around 08:27 New York time if that helps.

- python version: `python --version`: 
Python 2.7.16 but Python 3.7.6 is also installed

- node.js version: `node -v`:
I do not have node installed.

- npm version: `npm -v`
No NPM on Mac.

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
WHERE to find these?

- [X] I have reproduced the issue with at least the latest released version of superset.
I tried to do `docker-compose build` AND `docker-compose up --build` to see if this could fix the issue. No change.

- [X] I have checked the issue tracker for the same issue and I haven't found one similar.
I have found one issue from 2019: https://github.com/apache/incubator-superset/issues/8818
But nothing in there seemed to help me.

### Additional context

While I was typing this I saw the terminal showing additional information:

"superset_node            | npm WARN tarball tarball data for datamaps@0.5.9 (sha512-GUXpO713URNzaExVUgBtqA5fr2UuxUG/fVitI04zEFHVL2FHSjd672alHq8E16oQqRNzF0m1bmx8WlTnDrGSqQ==) seems to be corrupted. Trying one more time."

I then scrolled up to check if there was more and got to:

"superset_init            | Init Step 4/4 [Starting] -- Loading examples"

I did not find the related "[Complete]" tag however. Does this mean that there is still some kind of installation running in the background? If this is the case and the install is still running, why not tell the user clearly? Also why can I already open the URL if there is nothing there (yet)? Most likely something went wrong during the install and Step 4 never got completed I guess?

The terminal gets flooded with "superset_app             | INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 12:34:25] "GET /health HTTP/1.1" 200 -" which to me looks like an "is_alive" response, telling me, as the unsuspecting user, that everything is done.

**Comment by HappyMiner** [comment]
Just after I hit submit here, it seems that the terminal came alive again:
Seeing messages about a "webpack.Progress"... If the installation is not completed after... well, completing it, then the user should definitely be warned at least in the documentation. For me this whole thing has been going on for about at least an hour, I think, including one rebuild attempt because of this.

**Comment by srinify** [comment]
@HappyMiner hi there, this has actually been a common experience for many first time users of Superset via docker-compose. The Docker container for the frontend application is basically building frontend assets (hence the webpack.progress messages in the command line) but this build process often starts 10-15 mins after the rest of the containers are up (for some reason).

Once you see the frontend assets finish building, you should see the full Superset UI!

**Comment by mattarderne** [comment]
I encountered this and waiting for +20min without it resolving. What am I looking for to indicate it is finished building?

**Comment by nytai** [comment]
@mattarderne You're looking for the `superset_node` container to finish building the front end assets.

**Comment by mattarderne** [comment]
Per [this comment](https://github.com/apache/incubator-superset/issues/10773#issuecomment-688861590), working steps for me are as follows:
```
docker-compose build
docker-compose up
```
I also increased the ec2 instance size to medium, perhaps this helped.

**Comment by Bloomberg-zhong** [comment]
same quantity, what should I do to fix it?

**Comment by gamebusterz** [comment]
@Bloomberg-zhong 
Adding `docker-compose down` before the worked for me.

```
docker-compose build
docker-compose up
```

**Comment by fulviomascara** [comment]
I solved this problem in my Mac today, with these steps:

1. git clone https://github.com/apache/incubator-superset.git
2. cd incubator-superset
3. docker-compose build
4. docker-compose up

After terminal finishes Load Examples step (Step 4), enter in another session in terminal and
5.  npm ci && npm run build && rm -rf node_modules

**Comment by bharathi26** [comment]
> I solved this problem in my Mac today, with these steps:
> 
> 1. git clone https://github.com/apache/incubator-superset.git
> 2. cd incubator-superset
> 3. docker-compose build
> 4. docker-compose up
> 
> After terminal finishes Load Examples step (Step 4), enter in another session in terminal and
> **5. npm ci && npm run build && rm -rf node_modules**

Thanks a lot

**Comment by JoseCF** [comment]
> I solved this problem in my Mac today, with these steps:
> 
> 1. git clone https://github.com/apache/incubator-superset.git
> 2. cd incubator-superset
> 3. docker-compose build
> 4. docker-compose up
> 
> After terminal finishes Load Examples step (Step 4), enter in another session in terminal and
> 5. npm ci && npm run build && rm -rf node_modules

Could you tell us in which image do you open the terminal: superset-worker, superset-app????

**Comment by gamebusterz** [comment]
> Could you tell us in which image do you open the terminal: superset-worker, superset-app????

It clearly says you have to be in `incubator-superset`, which is just the root directory of the project

**Comment by lapalus** [comment]
Any update on this

> I solved this problem in my Mac today, with these steps:
> 
> 1. git clone https://github.com/apache/incubator-superset.git
> 2. cd incubator-superset
> 3. docker-compose build
> 4. docker-compose up
> 
> After terminal finishes Load Examples step (Step 4), enter in another session in terminal and
> 5. npm ci && npm run build && rm -rf node_modules

Any update on this case? I could not get it started on Mac. Tried the above steps but did not work.

**Comment by tomer-ben-david** [comment]
> npm ci && npm run build && rm -rf node_modules

I get then:

```

npm ci && npm run build && rm -rf node_modules                                                                               (base)
npm ERR! The `npm ci` command can only install with an existing package-lock.json or
npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
npm ERR! later to generate a package-lock.json file, then try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/..../.npm/_logs/2021-01-26T15_34_29_045Z-debug.log
```

**Comment by bobeal** [comment]
> > npm ci && npm run build && rm -rf node_modules
> 
> I get then:
> 
> ```
> 
> npm ci && npm run build && rm -rf node_modules                                                                               (base)
> npm ERR! The `npm ci` command can only install with an existing package-lock.json or
> npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
> npm ERR! later to generate a package-lock.json file, then try again.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/..../.npm/_logs/2021-01-26T15_34_29_045Z-debug.log
> ```

you have to first go into the `superset-frontend` directory (where the build files for the front end are located) and run the `npm ...` commands in it.

**Comment by huguiqi** [comment]
我是Mac电脑，我遇到同样的问题，登陆后一直loading。我的电脑环境：
macbook M1 Pro, 系统版本：13.0.1；
使用docker compose 部署superset版本是4.1.2；docker 是：28.0.1.

问题我已经解决了，我是这样解决的，docker目录中：
1. .env 文件修改：BUILD_SUPERSET_FRONTEND_IN_DOCKER=true; 
2. 修改 docker-frontend.sh 文件：
``` echo "Running `npm install`"
     # npm install
     npm ci
    echo "Start webpack dev server"
    # start the webpack dev server, serving dynamically at http://localhost:9000
    # it proxies to the backend served at http://localhost:8088
    echo "chmod root for node_modules"
    chmod -R a+x node_modules
    npm run dev-server
```
