### ISSUE TITLE
superset custom login using angular

### ISSUE THREAD

**Issue by dineshbhavsar** [apache/superset#11247]
I want to login and customization using angular like, I have one angualr application and thought that we want to call the superset login api and after that we can customize the superset charts

**Comment by kokila143** [comment]
Hi everyone,
I have been trying to achieve by pass login page in superset. I couldn't find the perfect source for this. I have tried so many methods still I couldn't achieve it. If anyone tried or found any useful links kindly share.
Thanks in advance.

**Comment by zs-err** [comment]
@kokila143 did you find any solution in the end?
