### ISSUE TITLE
[Bug] Area chart tooltip doesn't highlight a row anymore

### ISSUE THREAD

**Issue by bkyryliuk** [apache/superset#11245]
Area chart tooltip doesn't highlight a row anymore

## Screenshot
Current:

![image](https://user-images.githubusercontent.com/5727938/95800256-d789b800-0cab-11eb-8a1a-a4087ee3701f.png)

Previous:
![Screen Shot 2020-10-12 at 4 55 03 PM](https://user-images.githubusercontent.com/5727938/95800237-cc368c80-0cab-11eb-87c0-40bd48bffef9.png)

**Comment by bkyryliuk** [comment]
cc @junlincc @eugeniamz - please let me know who from engineering may have some context about it.

**Comment by bkyryliuk** [comment]
saw similar issue on the line chart as well

**Comment by junlincc** [comment]
@villebro

**Comment by villebro** [comment]
@bkyryliuk what browser is this on? I am unable to repro both on Chrome and Firefox running current master.

**Comment by bkyryliuk** [comment]
> @bkyryliuk what browser is this on? I am unable to repro both on Chrome and Firefox running current master.

it was latest master as of yesterday on chrome

**Comment by bkyryliuk** [comment]
Was able to get a bit more information:

Small number of values in the chart works:
![image](https://user-images.githubusercontent.com/5727938/96040247-d200af00-0e1e-11eb-8018-860976d5e7f6.png)

Bug larger does not:
![image](https://user-images.githubusercontent.com/5727938/96040312-eb096000-0e1e-11eb-806b-b25dfc230bc9.png)

I was able to replicate it in firefox, safari and chrome on mac

This is how to create a similar chart:
![image](https://user-images.githubusercontent.com/5727938/96040421-17bd7780-0e1f-11eb-8007-0ef1b7626114.png)

**Comment by bkyryliuk** [comment]
curious if https://github.com/apache-superset/superset-ui/pull/764 is a root cause

**Comment by junlincc** [comment]
As we are in the process of deprecating the NVD3 charts, we decide not to fix #11245, instead, we will work on the enhancement for ECharts area chart => highlight which series is hovered in tooltip to reach feature parity. 

Hope this work for the community!

**Comment by yousoph** [comment]
Closing, the time series area chart highlights rows: 
![image](https://user-images.githubusercontent.com/10627051/159844870-baabf4d5-2584-4af1-b4e1-78e48fefab7d.png)
