### ISSUE TITLE
Two time stamp formats displayed on time range selector

### ISSUE THREAD

**Issue by rusackas** [apache/superset#11275]
## Screenshot

![image](https://user-images.githubusercontent.com/812905/96051017-81de1880-0e2f-11eb-9c5c-66d2a44d9f6c.png)

## Description

When clicking the calendar, the date format changes to ISO time. We should only see/use ONE date format.

## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

**Comment by junlincc** [comment]
feel like it has been years when i last saw the old time picker.
