### ISSUE TITLE
How to get filter box time grain in SQL query

### ISSUE THREAD

**Issue by mavilar** [apache/superset#11406]
I was trying to write an SQL query to build a chart that gets affected by the time filters of a filter box in a dashboard. More specifically, I would like to get the time grain selection.

I found this next issue that leads me to believe that it would be possible to get the time grain with the expression `filter_values('__time_grain')`, but I tried and it doesn't work. The expression `filter_values('__time_range')` doesn't work either.
[https://github.com/apache/incubator-superset/issues/8183](url)

After finding out, I went to the function's (`filter_value`) code and saw that there is a call to a function called `merge_extra_filters` that removes this time filter from `form_data`, and so the call `filter_values('__time_grain')` returns nothing. I also reviewed the Git history, and found that this behavior was introduced in a commit on 20 April 2020, so it looks like this should work before this commit. Is this the expected behavior for an expression like `filter_values('__time_grain')`? If so, how do I get the time grain from a filter box to use it in an SQL query?

**Comment by krsnik93** [comment]
facing this as well, templating works for non time-related columns but not for time grain. This bit of code:
https://github.com/apache/superset/blob/24ad6063d736c1f38ad6f962e586b9b1a21946af/superset/utils/core.py#L1012-L1018
make me think that it should be doable to do `filter_values('time_grain_sqla')` but it's not working.

**Comment by isrkar** [comment]
I also need to pass the grain to query.
Has anyone figured out how to do this?

**Comment by cameronstonefinn** [comment]
Similar issue here, trying to pass a default `time_grain_sqla` to a filter box using the dashboard metadata with no success:

`"default_filters": "{\"4291\": {\"__time_grain\": \"week\"}}"`

Filter properties: 

![image](https://user-images.githubusercontent.com/77355693/124043321-a418c600-d9bf-11eb-9d1c-bfbb66a4b747.png)

Metadata: 

![image](https://user-images.githubusercontent.com/77355693/124043106-310f4f80-d9bf-11eb-9867-de51e6d9e1c9.png)

Result: 

<img width="554" alt="Screen Shot 2021-06-29 at 6 56 41 PM" src="https://user-images.githubusercontent.com/77355693/124043235-7895db80-d9bf-11eb-9339-72fd08d6f6b3.png">

Anyone else figured out what's going on?

**Comment by scimas** [comment]
Has anyone figured out how to get the time grain?

**Comment by amitmiran137** [comment]
Filter box is depracated and time grain is addressed property in native filters
