### ISSUE TITLE
[Echarts]Arbitrary expressions for rolling windows

### ISSUE THREAD

**Issue by asu04** [apache/superset#11436]
The rolling windows functionality for line charts is nice - but it'd be nice to either have more aggregation options (max, mins, percentiles), or be allowed to compute arbitrary expressions.

Ideally this just expands on the current list for rolling windows by aggregations types above, and also having an option for specifying custom expressions - this would let us generate more views and charts on the same underlying data without having to rely on ETL to compute it.

**Comment by mistercrunch** [comment]
The feature is based on pandas' `rolling` function https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rolling.html

It should be easy to expand it to support more options. Here's where it sits in the codebase https://github.com/apache/incubator-superset/blob/master/superset/utils/pandas_postprocessing.py#L307-L315

**Comment by junlincc** [comment]
We should include requested enhancement to Echarts time-series line. Will revisit when we get there

cc @zhaoyongjie
