### ISSUE TITLE
Refactor Cypress tests to make less page visits

### ISSUE THREAD

**Issue by ktmud** [apache/superset#11448]
**Is your feature request related to a problem? Please describe.**

Currently the Cypress tests are slow because many of them make new page requests for each test case. 

**Describe the solution you'd like**

A lot of those are not really necessary and can be eliminated by combining similar tests on the same page to run consecutively. We should also add a section in CONTRIBUTING to describe how to write efficient E2E tests.

Making consecutive test cases on the same page also most closely simulate real user actions.

**Describe alternatives you've considered**

**Additional context**

For example, a lot of these  `beforeEach` are not necessary:
<img src="https://user-images.githubusercontent.com/335541/97370050-65989d80-186b-11eb-8b39-834f66f533ae.png" width="400" />

**Comment by junlincc** [comment]
@rusackas on-boarding task for Bruno?

**Comment by rusackas** [comment]
I believe @geido took on the spirit of this issue in [this PR](https://github.com/apache/superset/pull/21332) and related efforts. I'll go ahead and close this for now, but just say the word if there's any reason to re-open this Issue, and we can dial in the scope a bit further.
