### ISSUE TITLE
Label_colors not work on Scatterplot

### ISSUE THREAD

**Issue by fedecere94** [apache/superset#11443]
I have a scatterplot chart in which I set the COLOR SCHEME to `D3 Category 10` and the CATEGORICAL COLOR is related to a column (named "ovt") that contains 2 possible values: "overtarget" and "non overtarget".
I set the variable **label_colors** in the JSON Metadata of my dashboard as following:
`"label_colors": {
    "overtarget": "red",
    "non overtarget": "green"
}` 
The problem is that the scatterplot in the dashboard is not affected by this rule (it takes the first two colors of the D3 Category 10 scheme: `#1f77b4` and `#ff7f0e`, ignoring my label_colors rule). But if choose I explore chart from dashboard in the new window the chart is affected by the rule and the colors being showed are `red` and `green` (in fact if I check the URL parameter form_data I see the label_colors rule with its fields)

How can I fix this problem?

**Comment by antobenve** [comment]
I confirm this issue on both the old version and the new 1.0.0 version.

**Comment by rusackas** [comment]
Closing as stale, but if this exists on the newer ECharts plugin, please file a new issue with updated context and repro steps. Thanks!
