### ISSUE TITLE
Error when adding a SQLite DB does not include message

### ISSUE THREAD

**Issue by earwig** [apache/superset#11462]
The error when adding a SQLite DB shows "Connection failed. [object Object]" instead of the real error message.

### Expected results

I see the real error message: "SQLite database cannot be used as a data source for security reasons."

### Actual results

I see "ERROR: Connection failed. [object Object]".

#### Screenshots

<img width="628" alt="superset-error-message" src="https://user-images.githubusercontent.com/637235/97478467-61ca5100-1927-11eb-937b-b7c91812bd4e.png">

<img width="1026" alt="superset-error-response" src="https://user-images.githubusercontent.com/637235/97478431-51b27180-1927-11eb-92e0-3d06ab90dbd3.png">

#### How to reproduce the bug

1. Try to add a database
2. Enter a `sqlite://` URI
3. Try to add the database

### Environment

- superset version: current master (894b94a3451d8c6fb6f55ea8d3725f1ecec2e9c4)
- python version: 3.7.9
- node.js version: 12.19.0
- npm version: 6.14.8

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by nytai** [comment]
I believe this was addressed in https://github.com/apache/incubator-superset/pull/11618 which also raised a few other issues

**Comment by rusackas** [comment]
I know these errors have been widely given a once-over by now, so I'll assume this one's all resolved. If people are seeing this in 1.5.x or 2.x.x releases, let's re-open with updated screenshots and repro steps.
