### ISSUE TITLE
Help needed in setting up dashboard emailing for Superset

### ISSUE THREAD

**Issue by DRavikanth** [apache/superset#11507]
Superset Version: 0.37.2
GeckoDriver: 0.26
Firefox: 68.12
Celery: 4.4.7(cliffs)

All the deployments are made in Kubernetes using docker image and helm charts.

Superset is setup correctly. Celery also works fine. Configured a Datasource to query in Async fashion and observed Celery picking up the queries and executing. Results also rendered to Superset

Problem:
Having issues configuring emailing for dashboards. Following are all the configurations added to config.py

> ENABLE_SCHEDULED_EMAIL_REPORTS = True
> 
>   EMAIL_NOTIFICATIONS = True # all the emails are sent using dryrun
> 
>   EMAIL_REPORTS_CRON_RESOLUTION = 15
> 
>   SMTP_HOST = "proxy.dummy.com"
>   SMTP_STARTTLS = False
>   SMTP_SSL = False
>   SMTP_USER = "superset"
>   SMTP_PORT = 25
>   SMTP_PASSWORD = "superset"
>   SMTP_MAIL_FROM = "superset-dev@dummy.com"
> 
>   EMAIL_REPORT_FROM_ADDRESS = "superset-dev@ dummy.com"
>   EMAIL_REPORT_FROM_ADDRESS = "superset-dev@ dummy.com"
>   EMAIL_REPORT_BCC_ADDRESS = None
> 
>   EMAIL_REPORTS_USER = "admin"
>   EMAIL_REPORTS_SUBJECT_PREFIX = "[Report] "
>   EMAIL_REPORTS_WEBDRIVER = "firefox"
>   WEBDRIVER_TYPE = "firefox"
> 
>   WEBDRIVER_WINDOW = {"dashboard": (1600, 2000), "slice": (3000, 1200)}
> 
>   WEBDRIVER_AUTH_FUNC = None
> 
>   WEBDRIVER_CONFIGURATION: Dict[Any, Any] = {}
> 
>   WEBDRIVER_OPTION_ARGS = [
>     "--force-device-scale-factor=2.0",
>     "--high-dpi-support=2.0",
>     "--headless",
>   ]
> 
>   WEBDRIVER_BASEURL = "instance of superset webserver"
> 
>   WEBDRIVER_BASEURL_USER_FRIENDLY = WEBDRIVER_BASEURL

Installed Firefox on the docker container & xvfb. 

When creating a test email from Manage -> Dashboard Emails, I get the following exception in the celery logs:

 

> [2020-10-30 23:48:29,345: INFO/ForkPoolWorker-7] Starting report for slack: None and recipients: hello@dummy.com
> .
> [2020-10-30 23:49:07,269: WARNING/ForkPoolWorker-7] Message: Unable to locate element: .grid-container
> , retrying in 30 seconds...
> [2020-10-30 23:49:37,339: ERROR/ForkPoolWorker-7] Task email_reports.send[87f68a8b-156b-4b5a-9f32-5f508b57fd02] raised unexpect
> ed: NoSuchElementException('Unable to locate element: .grid-container', None, None)
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task
>     R = retval = fun(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/superset/app.py", line 115, in __call__
>     return task_base.__call__(self, *args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__
>     return self.run(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/superset/tasks/schedules.py", line 518, in schedule_email_report
>     schedule.deliver_as_group,
>   File "/usr/local/lib/python3.6/site-packages/superset/tasks/schedules.py", line 299, in deliver_dashboard
>     get_element, fargs=["grid-container"], tries=2, delay=EMAIL_PAGE_RENDER_WAIT
>   File "/usr/local/lib/python3.6/site-packages/retry/api.py", line 101, in retry_call
>     return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)
>   File "/usr/local/lib/python3.6/site-packages/retry/api.py", line 33, in __retry_internal
>     return f()
>   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 564, in find_element_by_class_name
>     return self.find_element(by=By.CLASS_NAME, value=name)
>   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
>     'value': value})['value']
>   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> 
> [2020-10-31 00:01:00,231: INFO/ForkPoolWorker-7] Starting report for slack: None and recipients: hello@dummy.com
> .
> [2020-10-31 00:01:06,548: ERROR/ForkPoolWorker-7] Task email_reports.send[7348e4c4-f6fa-48ab-88c0-decc87f5404b] raised unexpect
> ed: WebDriverException('Failed to decode response from marionette', None, None)
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task
>     R = retval = fun(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/superset/app.py", line 115, in __call__
>     return task_base.__call__(self, *args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__
>     return self.run(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/superset/tasks/schedules.py", line 518, in schedule_email_report
>     schedule.deliver_as_group,
>   File "/usr/local/lib/python3.6/site-packages/superset/tasks/schedules.py", line 291, in deliver_dashboard
>     driver.set_window_size(*window)
>   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 1090, in set_window_size
>     self.set_window_rect(width=int(width), height=int(height))
>   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 1182, in set_window_rect
>     "height": height})['value']
>   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette

Stuck at this point and couldn't proceed any further. Any pointers in the right direction will be of great help. 

TIA

**Comment by DRavikanth** [comment]
@mahendra, Any help here?

**Comment by Kobe-Wang** [comment]
I also got the same error logs from the Celery worker when sending email reports from the Superset dashboard.

The related version is as the followings:
- Superset version is 0.37.2
- GeckoDriver is 0.26.0
- Firefox-esr is 78.4.0esr-1~deb10u2
- Celery is 4.4.7 (cliffs)

```
[2020-11-03 03:25:00,949: INFO/ForkPoolWorker-1] Starting report for slack: None and recipients: test@example.com.
[2020-11-03 03:25:52,047: WARNING/ForkPoolWorker-1] Message: Unable to locate element: .grid-container
, retrying in 30 seconds...
[2020-11-03 03:26:22,085: ERROR/ForkPoolWorker-1] Task email_reports.send[a338c5af-d945-4063-9531-6c5864806a0d] raised unexpected: NoSuchElementException('Unable to locate element: .grid-container', None, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/superset/app.py", line 115, in __call__
    return task_base.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/superset/tasks/schedules.py", line 518, in schedule_email_report
    schedule.deliver_as_group,
  File "/usr/local/lib/python3.6/site-packages/superset/tasks/schedules.py", line 299, in deliver_dashboard
    get_element, fargs=["grid-container"], tries=2, delay=EMAIL_PAGE_RENDER_WAIT
  File "/usr/local/lib/python3.6/site-packages/retry/api.py", line 101, in retry_call
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)
  File "/usr/local/lib/python3.6/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: .grid-container
```

**Comment by DRavikanth** [comment]
@Kobe-Wang, Please keep posted here if you are able to get around the problem. I will do the same.

**Comment by DRavikanth** [comment]
@Kobe-Wang, This is something found on SOF, https://stackoverflow.com/questions/27112731/selenium-common-exceptions-nosuchelementexception-message-unable-to-locate-ele

It looks like the code is loading faster than the webpage rendering causing some elements not to load.

**Comment by Kobe-Wang** [comment]
@DRavikanth I already tested to set up `EMAIL_PAGE_RENDER_WAIT` from 30 to 60 for solving the loading issue, and then I also got the same error message. Besides, I also changed the GeckoDriver version, such as 0.24.0, 0.25.0, and 0.27.0, and then I got the same error message again.

**Comment by DRavikanth** [comment]
Thanks for responding @Kobe-Wang. I did the same but still running into the exact same error. Have tried multiple combinations of Firefox & Gecko driver as well and no luck. It's kind of a black box at the moment.

**Comment by fdupuis659** [comment]
Are you running behind a reverse proxy? I had a setup with SSO configured running behind Nginx and ran into this. This may be the cause of it. In my case, the webdriver requests weren't getting past the identity provider login screen...

**Comment by farhat-nawaz** [comment]
I'm having the same issue on latest release 1.0.0. Was anyone able to solve this problem? I'm using `geckodriver`.

**Comment by singh-ab** [comment]
similar issue with `geckodriver` after the upgrade from 0.38.0 to 1.0.0

**Comment by francis-dupuis** [comment]
So I've used geckodriver and chrome on 1.0.0 and 0.38 and they've both worked. The problem is that a dashboard email job won't complete. You need to know how to debug this to get anywhere.

From a surface level, it could be a couple of things that are all speculatory...

- You're posting incorrect credentials with the webdriver
- The webdriver process isn't launching at all (incorrect webdriver URL config or permission issue)
- You're celery config is wrong

You can get started debugging via celery. Most of the email reporting configs are via a celery beat-scheduler and a celery worker.

If you're running a docker setup (which I'm assuming you are) you can try examining the logs in or outside of the docker container. What helped me out the most is launching a celery flower instance with docker-compose. Flower will allow you to monitor the success of these jobs as well as showing the traceback if a job fails. You can spin up Flower pretty easily with docker-compose. I configured flower to run on port 5555 (which is the default). Once Flower is running, navigate to it and inspect the job. Below is my compose setup. Replace the repo in the image name with one of your choice.

`version: '3'
services:
  redis:
    image: redis
    restart: always
    volumes:
      - redis:/data
  postgres:
    image: postgres
    restart: always
  superset:
    image: supers
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "8088:8088"
  worker:
    image: repo/superset
    restart: always
    depends_on:
      - postgres
      - redis
  beat_worker:
    image: repo/superset
    restart: always
    depends_on:
      - postgres
      - redis
  flower:
    image: repo/superset
    ports:
      - 5555:5555
    depends_on:
      - beat_worker
      - worker
volumes:
  postgres:
  redis:
`
After everything is spun up, try sending a test email on the scheduled dashboard UI.

![Screen Shot 2021-02-02 at 6 09 14 PM](https://user-images.githubusercontent.com/76928527/106674762-e14c6980-6581-11eb-8c81-fa5cad813baa.png)

![Screen Shot 2021-02-02 at 6 09 07 PM](https://user-images.githubusercontent.com/76928527/106674759-e01b3c80-6581-11eb-9f48-5a0539576697.png)

You would see a traceback if it failed. This is how I debugged originally when my emails wouldn't send. There's a bunch of possibilities why you

**Comment by DRavikanth** [comment]
This is the newest exception I am facing when running chrome driver. 

`[2021-02-10 23:13:32,755: WARNING/ForkPoolWorker-8] Message: no such element: Unable to locate element: {"method":"css selector","selector":".grid-container"}
  (Session info: headless chrome=88.0.4324.150)
, retrying in 120 seconds...
[2021-02-10 23:14:00,347: WARNING/MainProcess] Soft time limit (150s) exceeded for email_reports.send[48a4dc7e-c410-451e-b47e-d9a35faa0e94]
[2021-02-10 23:14:00,348: ERROR/MainProcess] Task handler raised error: TimeLimitExceeded(120)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/billiard/pool.py", line 684, in on_hard_timeout
    raise TimeLimitExceeded(job._timeout)
billiard.exceptions.TimeLimitExceeded: TimeLimitExceeded(120,)`

@Kobe-Wang , I see you faced a similar exception. Any luck in overcoming this?

**Comment by DRavikanth** [comment]
I am finally able to get the email functionality to work. Please find below exception I faced and solution that worked for me. 

**Exception:**
`ed: NoSuchElementException('Unable to locate element: .grid-container', None, None)`
**Solution:**
Superset Worker runs the web driver to scrape the visual from Superset UI. Superset needs an user who has access to all dashboards to scrape. In my case, the admin user is not assigned with the admin role(which lets him access for all the dashboards). All I did is to assign admin user to admin role and that did the trick. 
**Configs:**
`EMAIL_REPORTS_USER = "admin"
THUMBNAIL_SELENIUM_USER = "admin"`
**Note:**If webdriver is successfully able to communicate with the webserver then you should see the series of events in the action log in UI. 

**Exception:**
`smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.`
**Solution:**
Our SMTP server doesn't support auth. So, all I have to do is add the following properties in the config.
`  SMTP_USER = ""
  SMTP_PASSWORD = ""`

That's all needed to make email communication successfully work with Superset.

**Comment by AmarkhiS** [comment]
Still having that issue (release 1.0.0) with correct admin user on EMAIL_REPORTS_USER/THUMBNAIL_SELENIUM_USER
Test with geckodriver 0.29 & chromedriver 88

**Comment by alafanechere** [comment]
I used the new `Alert and reports` feature of v1 that has a different implementation of emailing from the classic `Report` feature. Emailing works for me now, no more selenium exceptions.

**Comment by DRavikanth** [comment]
@AmarkhiS Did you check if your admin user has access to open all the dashboards? I had to assign admin user to admin role to get this sorted.

**Comment by AmarkhiS** [comment]
@alafanechere I have tried this feature, but I'm unable to create an alert/report. Add button remains disabled 

@DRavikanth yes that's the first thing I checked after your answer

**Comment by vinitpradhn18** [comment]
Did anyone figure out how to setup Alerts & Reports, when running behind a SSO? Without SSO, with default Superset login, it seems to be working fine. With SSO, Selenium times out. Getting the following error - 

`Selenium timed out requesting url http://superset:8088/superset/dashboard/81`
`Report state: Report Schedule execution failed when generating a screenshot`

**Comment by oBoMBaYo** [comment]
Exception:
`smtplib.SMTPNotSupportedError: (535, b'5.7.8 credentials invalid')`
Can be fix by apply the solution on the exception that @DRavikanth posted above.
Hope this can help somesone who face the issue.

> Exception:
> smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.
> Solution:
> Our SMTP server doesn't support auth. So, all I have to do is add the following properties in the config.
> 
> SMTP_USER = ""
> SMTP_PASSWORD = ""
<img width="1286" alt="Screen Shot 2021-05-15 at 09 48 32" src="https://user-images.githubusercontent.com/10667447/118346042-db8ff800-b562-11eb-828a-1d61b47c945d.png">

**Comment by Asturias-sam** [comment]
@vinitpradhn18  did you resolve the issue ? facing the same thing

**Comment by vinitpradhn18** [comment]
@Asturias-sam We ran another VM instance without SSO but connected to same Postgres DB. It is a work around, but it resolved the our issue

**Comment by Asturias-sam** [comment]
@vinitpradhn18  For you the full dashboard snapshot is coming for me if the dashboard is too big as single browser page so it's getting chopped off ?
