### ISSUE TITLE
https://apache-superset.readthedocs.io/en/0.36/admintutorial.html docs have broken links to images

### ISSUE THREAD

**Issue by kiwimic** [apache/superset#11505]
Hey, 

I was taking first steps with apache superset, and was going to try tutorial on https://apache-superset.readthedocs.io/en/0.36/admintutorial.html but right now all images are not visible (links are broken, 'sorry this page does not exists') for example: https://apache-superset.readthedocs.io/en/0.36/_static/images/tutorial/tutorial_03_database_name.png

### Expected results

I would like to see a image :)

### Actual results

what actually happens.
![superset](https://user-images.githubusercontent.com/16867074/97748131-43ae4d80-1aed-11eb-9c06-b59e1204eef1.PNG)

**Comment by amitmiran137** [comment]
that documentation is deprecated . you can refer to the new one: https://superset.apache.org/docs/intro
