### ISSUE TITLE
Sorting charts by dataset is broken

### ISSUE THREAD

**Issue by betodealmeida** [apache/superset#11560]
When sorting charts by dataset the results are ordered by dataset ID instead of name.

### Expected results

Should sort by name.

### Actual results

Sorts by ID.

#### Screenshots

<img width="902" alt="Screen Shot 2020-11-04 at 2 57 00 PM" src="https://user-images.githubusercontent.com/1534870/98176751-03b0e700-1eae-11eb-916e-40b3a722b830.png">

Note that `energy_usage` has ID 1, and `wb_health_population` has ID 2.

#### How to reproduce the bug

1. Go to 'Charts'
2. Click on the 'Dataset' column
3. Sort is by ID

### Environment

- superset version: master
- python version: 3.8
- node.js version: v14.11.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

N/A

**Comment by nytai** [comment]
@betodealmeida this should be "fixed" in the latest master with https://github.com/apache/incubator-superset/pull/11370, we removed sorting on this column due to the non-standard/polymorphic nature of the dataset relation.
