### ISSUE TITLE
Improve selection of LIMIT in SQL Lab

### ISSUE THREAD

**Issue by betodealmeida** [apache/superset#11586]
**Is your feature request related to a problem? Please describe.**

In SQL Lab, to change the current limit the user needs to:

1. Click the LIMIT button
2. Click the input field
3. Delete the current value
4. Type in the new value
5. Press OK

This is a lot.

**Describe the solution you'd like**

In SQL Lab, after clicking the "LIMIT" button the input element in the dialog that pops should be focused and the current value selected. Pressing enter should apply and close the dialog, equivalent to clicking OK.

1. Click LIMIT button
2. Type in the new value
3. Press ENTER

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by Giphyn-nehboh-5qonhu** [comment]
https://t.me/Hos_144

**Comment by mistercrunch** [comment]
We have an internal design to improve the SQL Lab toolbar, and that includes improvement to the LIMIT control, it'd be great if we can share the design here in the open.

**Comment by Steejay** [comment]
hey @betodealmeida ! We're exploring this new limit design shown in the screenshot here. I agree that the current limit interaction should be simplified. We also saw an opportunity to eliminate some of the annoying error states a user might encounter (empty text field and integer over max limit). We believe that this dropdown of pre defined limits can help assuage some of these pain points. If a user wants to define a custom limit they still have the ability to do so in SQL Editor. 


![Frame 213 (1)](https://user-images.githubusercontent.com/60786102/98712579-5588bf80-233b-11eb-948d-d5ad37b00908.jpg)

cc @yousoph @mistercrunch

**Comment by betodealmeida** [comment]
This has been fixed.
