### ISSUE TITLE
Wrong SQL generated when filter is used

### ISSUE THREAD

**Issue by stone-bits** [apache/superset#11639]
I have a data table with a field that contains data with double quoted text at the end: 
```
some text "another text"
```
The last double quote is dropped in generated SQL when I use this field in a filter.

### Actual results
```
WHERE org_name IN ('some text "another text')
```

### Expected results
```
WHERE org_name IN ('some text "another text"')
```

#### How to reproduce the bug

1. Create dataset with data as above
2. Create chart
3. Create filter
4. Create dashboard
5. Use filter in dashboard
6. See chart is empty.
7. Explore chart. View chart SQL code in SQL Lab 

### Environment

- DB - PostgreSQL 10
- superset version: `0.37.2`
- python version: `3.6`

**Comment by aygiz** [comment]
Hi, any update on this? 
version 1.3.1 still has this issue.

**Comment by Qweyer** [comment]
I have the same issue, using 1.3.0 version with PostgreSQL connector
