### ISSUE TITLE
Give List and View access to a dashboard without adding it to owner

### ISSUE THREAD

**Issue by sarah012** [apache/superset#11654]
**Is your feature request related to a problem? Please describe.**
In my organization I have dashboard which I want to share with other users, I create a user name and gave that user gamma role with access to all datasources related to that board. I shared the dashboard url to the users. If the user is already logged in he/she is able to see the dashboard with edit button as disables. But if the user is not logged it redirects it to log in page, after user logs in, he sees dashboard tab with empty list which is quite confusing.

**Describe the solution you'd like**
 I want user to be able to view the same dashboard in list of dashboards and whenever he/she clicks on that dashboard he should be able to view the same without being able to edit it 

**Describe alternatives you've considered**
I added the user to owner of dashboard now the user is able to see the dashboard in list of dashboard tab. But when user opens the same he can see everything but edit button is also enabled which I don't want

**Additional context**

**Comment by amitNielsen** [comment]
https://github.com/apache/incubator-superset/issues/10408

**Comment by junlincc** [comment]
closing proposed issue, in favor of #10408, issue is resolved by https://github.com/apache/superset/pull/12680
thanks both! @sarah012 @amitmiran137
