### ISSUE TITLE
Chart can be added to Dashboard by Non-admin

### ISSUE THREAD

**Issue by kamalk-github** [apache/superset#11662]
If a user can access some dashboard(via access to underlying datasource(s)) where the user is not owner/admin, the user can create a new chart and add it to the dashboard without admin rights.

Follow below steps to reproduce:
1. A user who is not owner/admin of a dashboard can view it(via access to underlying datasource(s)).
2. Create a new chart from available datasources.
3. Edit the chart properties, and add the dashboard name to "Dashboards" section of "Edit Chart" screen.
4. New chart created by user is added to dashboard and can be seen on Dashboard by everyone.

This should not be allowed since the user is not owner/admin of Dashboard.

Superset version: 0.36.0

**Comment by zuzana-vej** [comment]
I couldn't see issue you are talking about in current behavior (on master). Here are the scenarios and results.

1. If you are dashboard owner - you can add chart from chart explore to dashboard directly. This works.
2. If you are NOT dashboard owner but are CREATOR of the dashboard (for example I created a dashboard, and then I asked an admin to remove me as owner, but I was still the creator of that dashboard) - I could still edit the dashboard (when on dashboard) and add charts, but I wasn't able to see this dashboard in the dropdown on chart explore, so I actually couldn't add chart directly from chart explore. --> assuming creator always keeps edit rights, this potentially might be a small bug, that creator can't add from chart explore directly (but simple workaround to add form dashboard)
3. And if I was not owner or creator, I couldn't edit dashboard and couldn't add chart into dashboard from chart explore. This is expected.

Unrelated thing I noticed, is that user (not admin) who is dashboard owner is not able remove themselves from dashboard owners (even if there are additional owners). This could be a bug.

**Comment by junlincc** [comment]
> Unrelated thing I noticed, is that user (not admin) who is dashboard owner is not able remove themselves from dashboard owners (even if there are additional owners). This could be a bug.

agreed that dashboard owner should be able to remove anyone, including themselves from dashboard owners. a strong case here is when there are personnel changes in the enterprise. 

cc. @benceorlai

**Comment by nytai** [comment]
Wouldn't an admin usually handle personnel changes?

**Comment by zuzana-vej** [comment]
Another point is: Should the creator of dashboard have edit rights forever? (e.g. just because you create the dashboard, should you forever have edit right even though admin removes you as one of the owners)?
