### ISSUE TITLE
[filter]Display label(value in different column) when filtering a specific column 

### ISSUE THREAD

**Issue by duynguyenhoang** [apache/superset#11705]
**Is your feature request related to a problem? Please describe.**

Currently selection box in FilterBox only filter by value from Column configuration. It would be nice to have label and value in configuration and in FilterBox render. Let assume we have merchant_name and id_merchant, we want to show merchant_name but when filter we filter by id_merchant.

**Describe the solution you'd like**

* This is my suggestion for configuration

![Screenshot_20201114_182431](https://user-images.githubusercontent.com/7106179/99146045-0b8b3b00-26a7-11eb-8ac7-64dad0dc2a8b.png)

* And from new configuration, we can change data in https://github.com/apache/incubator-superset/blob/master/superset/viz.py#L2003 and https://github.com/apache/incubator-superset/blob/master/superset/viz.py#L2009.

**Comment by Papipo** [comment]
I really need this!

**Comment by junlincc** [comment]
@simcha90 @amitmiran137
I think we can add this feature to native dashboard filter config modal -> use value in one column to filter the other column. 
Can we commit to this enhancement?

**Comment by suddjian** [comment]
Closing this in favor of #13398 as it has a more detailed description. This feature is in the roadmap.
