### ISSUE TITLE
Dashboard/Chart emails scheduled is not working

### ISSUE THREAD

**Issue by krishna9626** [apache/superset#11710]
### Expected results

The mail should be received once scheduled

### Actual results

While debugging, Succeeded status on log 

#### Screenshots

![issu1](https://user-images.githubusercontent.com/36255856/99245252-4cab5880-2829-11eb-8eef-98901f53d54f.PNG)
![issu3](https://user-images.githubusercontent.com/36255856/99245256-4ddc8580-2829-11eb-870d-eec3bc3e5a94.PNG)

#### How to reproduce the bug

1. Go to 'config.py' and follow the instruction for Email scheduling
2. Run the Celery worker and celery Beat command
3. Go to manage/email dashboard  then schedule
4. See error on celery worker terminal

### Environment

(please complete the following information):

- superset version: `0.37.2`
- python version: `python 3.6`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Using chrome as webdriver.

**Comment by junlincc** [comment]
@benceorlai

**Comment by dpgaspar** [comment]
Hi @krishna9626, on the logs it seems you have `dry run enabled` can you confirm?

**Comment by krishna9626** [comment]
@dpgaspar Yes it is enabled.

**Comment by willbarrett** [comment]
@krishna9626 please disable dry run and try again.
