### ISSUE TITLE
SQL Lab: widen left panel, limit type width

### ISSUE THREAD

**Issue by mistercrunch** [apache/superset#11725]
_I used the feature to create issue from comment on GitHub_, bypassed the template

@yousoph the bug is fixed, but the left panel still seems too crowded. I think the sql editor doesn't need that much of the space, but your call! 
<img width="320" alt="Screen Shot 2020-11-16 at 6 15 44 PM" src="https://user-images.githubusercontent.com/67837651/99337774-c64a4300-2837-11eb-8939-b99849f6b347.png">

_Originally posted by @junlincc in https://github.com/apache/incubator-superset/issues/11715#issuecomment-728641732_

**Comment by mistercrunch** [comment]
Some ideas:
- increase the left panel width by ~33%?
- map long type names like `TIMESTAMP WITHOUT TIME ZONE` to something like `TIMESTAMP...` with details on hover?

**Comment by junlincc** [comment]
@mihir14 what's the width are you setting? for the left panel in Explore(Data type fields + control)? 
i suggest to keep the left panel spaces in Explore and SQL lab the same! 
@mistercrunch

**Comment by mistercrunch** [comment]
For explore it's a responsive grid. For SQL Lab it's fixed I think

**Comment by ktmud** [comment]
We should make both resizable just like the SQL editor + result pane. Was actually working on that over the past weekend.

**Comment by junlincc** [comment]
can we coordinate to make that change?

**Comment by ktmud** [comment]
It was just an idea I've been wanting to do for a while but never committed to doing it. Feel free to create another github issue or roadmap item if you feel it's necessary.

**Comment by junlincc** [comment]
im trying to figure out a good timing to discuss major changes on those panels. @rusackas and I wont be able to dive deep  into until mid December, i also want to do a more throughout product discovery before our discussion. +1 on resizable though!

**Comment by yousoph** [comment]
Agreed that resizing would be a good first step! 

For the SQL Lab panel, I think it's worth revisiting how the column types are displayed (max character limit for column types, font styles, etc)
