### ISSUE TITLE
superset load examples fail

### ISSUE THREAD

**Issue by pengtaomach** [apache/superset#11735]
using superset load-examples  loading the examples data, an error was reported saying that the link timed out. Was the example data deleted at the target end

**Comment by junlincc** [comment]
can you provide more details? version, screenshot etc.

**Comment by willbarrett** [comment]
The example data is loaded as part of our CI runs - no, the example data has not been deleted.

**Comment by willbarrett** [comment]
Closing as requested additional information has not been provided.
