### ISSUE TITLE
Filter Box custom filter with date field showing epoch instead of human readable date

### ISSUE THREAD

**Issue by rwspielman** [apache/superset#11739]
When trying to create a date filter in a filter box that is separate of the time filter, it doesn't return a human readable version of the date.

### Expected results

a properly formatted human readable date to show in the dropdown list

### Actual results

epoch or unix date shows

#### Screenshots

<img width="743" alt="Screen Shot 2020-11-18 at 11 22 07 AM" src="https://user-images.githubusercontent.com/20442310/99574298-cf085980-299c-11eb-951e-bd8d5bffe74a.png">

#### How to reproduce the bug

1- Create a new filter box
2- Add a custom filter (not the one in the time section)
3- Select a date field for that filter
4- Run Query and use the dropdown for that filter
5- observe Epoch date instead of human readable date

 
### Environment

(please complete the following information):
- Data Source: MSSQL

- superset version: master 11/11/2020
- python version: python --version 3.6.9
- node.js version: node -v 8.10.0
- npm version: npm -v 3.5.2

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by amitmiran137** [comment]
filterBox is depracted, you should really check out the DASHBOARD_NATIVE_FILTERS ff . I believe that aspect was also covered under the new implementation of filters
