### ISSUE TITLE
dashboard owner is not able remove themselves from dashboard owners

### ISSUE THREAD

**Issue by junlincc** [apache/superset#11742]
_**using reference in new issue feature**_ 

_1. If you are dashboard owner - you can add chart from chart explore to dashboard directly. This works.
2. If you are NOT dashboard owner but are CREATOR of the dashboard (for example I created a dashboard, and then I asked an admin to remove me as owner, but I was still the creator of that dashboard) - I could still edit the dashboard (when on dashboard) and add charts, but I wasn't able to see this dashboard in the dropdown on chart explore, so I actually couldn't add chart directly from chart explore. --> assuming creator always keeps edit rights, this potentially might be a small bug, that creator can't add from chart explore directly (but simple workaround to add form dashboard)
3. And if I was not owner or creator, I couldn't edit dashboard and couldn't add chart into dashboard from chart explore. This is expected._

**Unrelated thing I noticed, is that user (not admin) who is dashboard owner is not able remove themselves from dashboard owners (even if there are additional owners). This could be a bug.** 🐛

_Originally posted by @zuzana-vej in https://github.com/apache/incubator-superset/issues/11662#issuecomment-730014498_

**Comment by rusackas** [comment]
I believe this has been resolved, but if not, let's freshen up the issue with current context and repro steps.
