### ISSUE TITLE
Bottom border missing from chart list

### ISSUE THREAD

**Issue by craig-rueda** [apache/superset#11756]
## Screenshot

<img width="392" alt="Screen Shot 2020-11-19 at 3 13 07 PM" src="https://user-images.githubusercontent.com/2595291/99735649-d5203800-2a79-11eb-8939-a8ae511f0908.png">

## Description

In the create/edit dashboard screen, the items in the chart list are missing their bottom border

**Comment by nytai** [comment]
Only seems to be an issue when there's only 1 chart
<img width="366" alt="Screen Shot 2020-11-19 at 3 20 19 PM" src="https://user-images.githubusercontent.com/10255196/99736159-c5edba00-2a7a-11eb-9672-6329cd2633b2.png">

**Comment by craig-rueda** [comment]
Yep. From your screenshot, it looks like there's double borders between the items as well. Prob need always need a top-border and only a bottom for the last...

**Comment by junlincc** [comment]
<img width="373" alt="Screen Shot 2020-11-19 at 3 24 19 PM" src="https://user-images.githubusercontent.com/67837651/99736491-50ceb480-2a7b-11eb-9939-479425ee5761.png">

happening to me when more than one chart.....

**Comment by nytai** [comment]
Yup, looks like we need to apply a border on the `last-of-type`

**Comment by nytai** [comment]
Looks like the issue is actually not accounting for the height of borders.

Bumping this line  +2 should account for the 1px border above and below 

https://github.com/apache/incubator-superset/blob/cdd01f4851d39d8d03dcd92653252cbbba52b6ed/superset-frontend/src/dashboard/components/SliceAdder.jsx#L67

**Comment by junlincc** [comment]
> Bumping this line +2 should account for the 1px border above and below

thank you @nytai for the hint 😉

**Comment by kgabryje** [comment]
Actually, it wasn't an issue with borders, but line height being inherited from `.ant-tabs`. It caused the cards to be far larger than before and they were overlapping each other. The fix is here: https://github.com/apache/incubator-superset/pull/11766

**Comment by junlincc** [comment]
> Actually, it wasn't an issue with borders, but line height being inherited from `.ant-tabs`. It caused the cards to be far larger than before and they were overlapping each other. The fix is here: #11766

Kamil, you are awesome and impressively fast i cant even catch up! thanks for the fix! @kgabryje

**Comment by junlincc** [comment]
spotted additional cosmetic issues, reopen it until they are addressed. 

fix: Chart select borders in BuilderComponentPane #11766
