### ISSUE TITLE
Database popup states in previous screen

### ISSUE THREAD

**Issue by eugeniamz** [apache/superset#11757]
## Screenshot

![2020-11-19_18-23-05 (1)](https://user-images.githubusercontent.com/58375897/99736508-7f0cbe00-2a94-11eb-902b-da7ef02ebae1.gif)

## Description
When adding or editing a database it always shows the previous tab. It should always show the first tab as it can confuse when adding a new one. 

## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

**Comment by junlincc** [comment]
@benceorlai

**Comment by willbarrett** [comment]
Team X can take this one

**Comment by willbarrett** [comment]
This is fixed.
