### ISSUE TITLE
HOW DO I? Looking forward for Apache Superset production deployment guide

### ISSUE THREAD

**Issue by bigbprp** [apache/superset#11761]
Dear Friends, 

I am looking for some guidelines on infrastructure sizing guidelines ( I know infra-sizing varies a lot based on the type of dashboards, refresh frequency, # of concurrent users, etc... ).

Any recommendations on how to deploy apache superset for 5000+ users?  high-level guideline on deployment architecture etc... 

That will be a great help.

**Comment by reignmaker** [comment]
I'm also very interested in how to setup/configure and deploy Superset in production, as I'm a new to python ecosystem and have a bit more knowlege in docker, docker-compose. I've been strugling for a week already trying to configure Superset for production with no luck. The official documentation is very poor and uninformative.
Greatly appreciate any help!

**Comment by reignmaker** [comment]
The main thing I can't handle is how to configure Superset via `superset_config.py`. I have no idea how to pass it into docker-compose.

**Comment by amitmiran137** [comment]
A deployment solution for production would be to deploy to kubernetes via helm.
you can get the helm chart in the helm folder in the root directory but there is a learning curve for kubernetes and helm in general

an alternative can be to use the **docker-compose-non-dev.yml** if you're using docker swarm or any other production solution based on docker-compose
