### ISSUE TITLE
SQL editing not obvious for metrics in datasource editor in explore view

### ISSUE THREAD

**Issue by bkyryliuk** [apache/superset#11768]
## Screenshot

![image](https://user-images.githubusercontent.com/5727938/99840863-2a178900-2b22-11eb-84fc-ead5acf76639.png)

## Description

Small piece of feedback for metric editor in the datasource editor for explore view. It looks a bit confusing, most of the fields are in the dropdown, but metric needs to be edited inline. E.g. metric is editable, but label next to it is not, also when creating a new metric - sql field is not showing u

**Comment by rusackas** [comment]
This is much clearer in the current/revamped design, I think you'll agree, so I'll close this. If it needs further design tweaks, however, let's take it up in an Ideas thread on GH Discussions. Thanks as always!
