### ISSUE TITLE
clickhouse  Unserializable object  of type <class 'ipaddress.IPv4Address'>

### ISSUE THREAD

**Issue by chen-ABC** [apache/superset#11777]
### Expected results
return data
use DBeaver can return data
![image](https://user-images.githubusercontent.com/30097790/99933828-17f25080-2d97-11eb-96fa-da94c4266d6d.png)

![image](https://user-images.githubusercontent.com/30097790/99933807-0ad56180-2d97-11eb-8c5a-3bbfbd0975fa.png)

### Actual results
![image](https://user-images.githubusercontent.com/30097790/99933626-97cbeb00-2d96-11eb-9496-55871550de97.png)

### Environment

(please complete the following information):

- superset version: `0.37`
- python version: `3.7.9`
- node.js version: `v12.18.3`
- sqlalchemy-clickhouse  `0.1.5`

**Comment by mistercrunch** [comment]
We've seen a fair amount of drivers returning non-native/serializable types, wondering how we should best handle this. @robdiciuccio any thoughts?

My guess is we need something in `db_engine_spec` that enables us to map types to a serialization method, but wondering if it's reasonable to just cast to string as a catchall.

**Comment by mistercrunch** [comment]
It's also apparent that the driver/dialect may need some work too, I'm guessing the driver return `NullType`.
