### ISSUE TITLE
Cannot login with default password

### ISSUE THREAD

**Issue by yshrotciv** [apache/superset#11788]
### Expected results

sucessfully login

### Actual results

Failed to login.

#### How to reproduce the bug

1. login with admin/admin

### Environment

(please complete the following information):

deployed with docker-compose
- superset version: `0.37.2`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

log from superset_init

Init Step 1/4 [Starting] -- Setting up admin user ( admin / admin )

######################################################################

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyarrow 0.17.0 (/usr/local/lib/python3.7/site-packages), Requirement.parse('pyarrow<1.1,>=1.0.1'), {'apache-superset'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/superset", line 33, in <module>
    sys.exit(load_entry_point('apache-superset', 'console_scripts', 'superset')())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1254, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1297, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 527, in get_command
    self._load_plugin_commands()
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 517, in _load_plugin_commands
    import pkg_resources
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3238, in <module>
    @_call_aside
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 569, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 582, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyarrow<1.1,>=1.0.1' distribution was not found and is required by apache-superset

**Comment by qiaofeng1227** [comment]
It is same with me, the command `superset` error when run, may be lack  the python  packages .

**Comment by AsjadMahmood** [comment]
Hey Guys i am having the issue. I completed the installation steps. And in the last step, i had to login. But i am unable to login with username="admin" and password="admin"

<img width="1440" alt="Screenshot 2020-12-14 at 12 51 45 PM" src="https://user-images.githubusercontent.com/38811693/102054672-8ad96f00-3e0b-11eb-8614-a84259479e5d.png">

**Comment by zhaoyongjie** [comment]
Hi @AsjadMahmood . Could you show me the Superset log output?

**Comment by AsjadMahmood** [comment]
> Hi @AsjadMahmood . Could you show me the Superset log output?

hey i solved the problem. The problem was not with superset, actually i was previously running a container of postgres which was kind of colliding with the the container of  superset-postres. so i resolved that. 
Thanks for the quick reply though.

**Comment by mayurnewase** [comment]
this could be closed

**Comment by rtjarvis** [comment]
I have this issue too

**Comment by dpgaspar** [comment]
Can you post the output from `flask fab list-users` please

**Comment by rtjarvis** [comment]
root@90da97871614:/app# flask fab list-users
Loaded your LOCAL configuration at [/app/pythonpath/superset_config.py]
INFO:superset.utils.logging_configurator:logging was configured successfully
/usr/local/lib/python3.7/site-packages/flask_caching/__init__.py:189: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  "Flask-Caching: CACHE_TYPE is set to null, "
List of users
-------------

**Comment by rtjarvis** [comment]
OK - a little more debugging. I tried `flask fab create-admin` and created an admin user. This is accepted by the UI but I get a stack trace response:

```sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "user_attribute" does not exist
LINE 2: FROM user_attribute
^

[SQL: SELECT user_attribute.welcome_dashboard_id AS user_attribute_welcome_dashboard_id
FROM user_attribute
WHERE user_attribute.user_id = %(user_id_1)s]
[parameters: {'user_id_1': '1'}]
(Background on this error at: http://sqlalche.me/e/f405)```

**Comment by willbarrett** [comment]
Closing as a stale issue - please let us know if the issue still exists on 1.1.0 and we will investigate further.

**Comment by lsh-0** [comment]
Followed the instructions here:
https://superset.apache.org/docs/installation/installing-superset-using-docker-compose/

using the `master` branch, and got the same screenshot as AsjadMahmood.

console output: 
[docker-compose-output.txt](https://github.com/apache/superset/files/8953563/docker-compose-output.txt)

**Comment by Dataabk** [comment]
Well the solution worked for me/ 12/June2024
User ID: Any12
Password: 10 Char  (Mandate)
email id = admin@fab.org   (Mandate)
