### ISSUE TITLE
Flaky test: test_get_report_schedule

### ISSUE THREAD

**Issue by etr2460** [apache/superset#11793]
It looks like the `test_get_report_schedule` test fails intermittently because the owners array isn't guaranteed to be in the same order every time. It's been preventing me from getting CI in https://github.com/apache/incubator-superset/pull/11785 to pass.

@dpgaspar, is this related to the FAB ModelRestApi?

**Comment by etr2460** [comment]
This is also blocking https://github.com/apache/incubator-superset/pull/11791

**Comment by amitmiran137** [comment]
is this still relevant?

**Comment by etr2460** [comment]
I would assume not since the PR i mentioned ended up getting merged. I'll close
