### ISSUE TITLE
[time-series]Echarts time-series contribution mode not working

### ISSUE THREAD

**Issue by junlincc** [apache/superset#11792]
![1-Time-series](https://user-images.githubusercontent.com/67837651/100057942-4561ed00-2ddd-11eb-8a27-7abbc1741887.gif)

to reproduce
- create a new chart
- select echarts time-series
- select metrics etc and select a `contribution mode` that is not `None`
- see error

**Comment by mayurnewase** [comment]
@junlincc could not reproduce on master (https://github.com/apache/incubator-superset/pull/11970)

**Comment by maloun96** [comment]
@junlincc Confirm that on latest master it's working

https://user-images.githubusercontent.com/8277264/111276665-3c24b680-8640-11eb-8de5-4760fc7e358f.mov

**Comment by alexamy** [comment]
Tried to reproduce last video, apparently no 'Total' contribution at all. Also tried to use it in other chart.
https://user-images.githubusercontent.com/596195/154355807-1ca34b3e-455d-4a0f-aff9-18b28aeebba0.mp4
