### ISSUE TITLE
In chart Maximize mode we are not able to see an error description

### ISSUE THREAD

**Issue by adam-stasiak** [apache/superset#11800]
### Expected results

Popup is displayed in maximize mode
### Actual results

Popup is displayed in the background
#### Screenshots
![image](https://user-images.githubusercontent.com/25153919/100126868-c9b87c80-2e7e-11eb-95f5-0095234b1ae9.png)
![image](https://user-images.githubusercontent.com/25153919/100126886-ce7d3080-2e7e-11eb-89b0-c78a3ca9263c.png)
![image](https://user-images.githubusercontent.com/25153919/100126909-d6d56b80-2e7e-11eb-942e-32c83d181e74.png)
![image](https://user-images.githubusercontent.com/25153919/100126953-e3f25a80-2e7e-11eb-9151-c2b9a80f2d0a.png)

#### How to reproduce the bug
Go to http://localhost:9000/superset/dashboard/tabbed_dash/#
Click on Tab menu
Choose maximize for chart which met unexpected error
In full screen mode tap on See more

### Environment
I run configuration SUPERSET_CONFIG=tests.superset_test_config
I run FLASK_ENV=development superset run -p 8088 --with-threads --reload --debugger
Then npm run dev-server 

- superset version: latest master
- python version: 3.7.7
- node.js version: 11.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by kgabryje** [comment]
I think it might be related to popups refactor. Can you assign me?

**Comment by junlincc** [comment]
it's in trello assigned to @kgabryje. thank you both for making my life easier 🙏
