### ISSUE TITLE
Improve loading state in the new doc site

### ISSUE THREAD

**Issue by ktmud** [apache/superset#11819]
## Screenshot

![image](https://user-images.githubusercontent.com/335541/100295368-49f1e700-2f3e-11eb-806b-e0191331d913.png)

## Description

The doc site looks broken when JS files are still loading.

To reproduce:

<img src="https://user-images.githubusercontent.com/335541/100295439-74dc3b00-2f3e-11eb-9f96-e775b0c1434f.png" width="500">

Go to Network tab, check "Disable cache" and "Fast 3G".

## Design input

No design input needed. Just fix the broken page by adding some sized placeholder elements or blocking the page from rendering when CSS/content is incomplete.

**Comment by junlincc** [comment]
@ktmud hey Jesse, we probably can't get to this issue by the EOY, if this is important to you and it doesn't take long to fix, do you mind.....

**Comment by rusackas** [comment]
I think this has been resolved with the docs site revamp that transpired since the issue was opened. If you still see anything like this, we can reopen or make a fresh issue. Thanks!
