### ISSUE TITLE
Saving an edit to an Annotation Layer redirects to an invalid page

### ISSUE THREAD

**Issue by etr2460** [apache/superset#11817]
I get redirected to http://localhost:8088/annotationmodelview/undefined/annotation/?filters=%5B%5D&pageIndex=0&sortColumn=short_descr&sortOrder=desc when i save an annotation layer.

### Expected results
Get redirected to a working page

### Actual results
Go to the link shown above

#### Screenshots
![image](https://user-images.githubusercontent.com/7409244/100293168-adc4e180-2f37-11eb-9604-e72a69c4afee.png)

#### How to reproduce the bug
- Edit an annotation layer in the new CRUD view
- Get redirected to the link above

### Environment
- superset version: `master`

@riahk it looks like you worked on this feature, any thoughts here?

**Comment by riahk** [comment]
I see the issue here, my one question is: when editing an annotation layer, should it redirect to that layer's page? This is what we do when creating a layer but I wasn't sure if we wanted the redirect on edit as well, or to stay on the main annotation layer list.

**Comment by nytai** [comment]
We probably don't want to redirect on edit, but we definitely don't want to redirect to a broken page.

**Comment by benceorlai** [comment]
The edit action opens a modal on top of the list of Annotation layers. The save action is supposed to take the user back to the  list view that is under the modal (and NOT redirect to that Layer's view. For that effect, the user needs to click on the Layer's name)

**Comment by willbarrett** [comment]
This is fixed.
