### ISSUE TITLE
dates not aligned in tables

### ISSUE THREAD

**Issue by squalou** [apache/superset#11823]
In a table with a column containing dates, data are misaligned.
Probably due to a bad font choice for number renderning.

Used to be fine in < 0.36 version if my memories are good

### Expected results

Cleanly verticallly aligned data

### Actual results

see screenshot

#### Screenshots

![image](https://user-images.githubusercontent.com/4623644/100318003-9c261d00-2fbd-11eb-8531-0c4ee364bad2.png)

#### How to reproduce the bug

1. Create any table containing date data, with for instance 2020 and 2019 year (as the "1" and the "0" wont have the same width)

### Environment

(please complete the following information):

- superset version: `superset version`

```bash
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Superset 0.38.0
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

- python version: `python --version`

```python
- Python 3.6.7
```

node.js version: `node -v`

```js
v12.16.3
```

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by squalou** [comment]
BTW : the font is "Inter", if I remove it (by editing css for instance, it's fine with Helvetica)

![image](https://user-images.githubusercontent.com/4623644/100318671-b6142f80-2fbe-11eb-9940-5c8776af4e9e.png)

**Comment by rusackas** [comment]
I'll try to get to this soon, but I'd like to keep Inter as the font, which [supports tabular numbers](https://rsms.me/inter/). We should be able to turn on the feature by setting the css `font-feature-settings` attribute to include "tnum". It *probably* makes sense to apply that style within any `table` elements, but this is where the real experimentation lies :D

**Comment by nytai** [comment]
bump @rusackas any update on this?

**Comment by squalou** [comment]
still no news ?
On 1.2.0-rc2 I still have to apply an ugly patch to change the fonts :-(
