### ISSUE TITLE
Categorical color/dimension issue

### ISSUE THREAD

**Issue by wildsonc** [apache/superset#11829]
## Screenshot

![NcAoRifnIK](https://user-images.githubusercontent.com/72408418/100382173-7ae32200-2ff9-11eb-92ab-d03b7c650824.png)

## Description
I'm not able to add any more columns in the dimension field, which was previously called a categorical color. I am also not able to add to the extra data field for js.

**Comment by sashankpappu** [comment]
Even i am facing the same issue . Can someone please help resolve this .

**Comment by wildsonc** [comment]
i found this solution https://github.com/apache/incubator-superset/pull/10277 but I couldn't solve it on my environment

**Comment by wildsonc** [comment]
> Even i am facing the same issue . Can someone please help resolve this .

i found this solution #10277 but I couldn't solve it on my environment

**Comment by junlincc** [comment]
To reproduce:

use long_lat datasource to create deck.gl.Scartterplot with LON as the longitude and LAT as the latitude
scroll down to the Point Color section and click DIMENSION
There supposed to be 15 options but nothing is showing

cc: @nikolagigic

**Comment by ali-hesham** [comment]
i'm facing the same issue on the latest version.

**Comment by nytai** [comment]
Closing at this appears fixed (using the repro steps mentioned above) in the latest version (master)
