### ISSUE TITLE
SqlLab ResultsTable Formatting long strings 

### ISSUE THREAD

**Issue by pabrahamusa** [apache/superset#11832]
## Screenshot

![image](https://user-images.githubusercontent.com/47830507/100398789-2dc57700-301e-11eb-991e-f81ae215d235.png)

## Description

I am using SqlLab to query my data that having very long String i.e. > 10000 , SqlLab results table at the moment truncates the string with ellipsis and the result table width is too big .This all makes it hard to read. I tried to add some word=wrap
in FilterableTableStyles.less , However it is overflowing and I was not able to fix it. Is there a way I can enable word wrap , reduce the result table width and stop overflow so all results appear nicely?

`.ReactVirtualized__Table__rowColumn {
  /* text-overflow: ellipsis; */
  /* white-space: nowrap; */
  white-space: pre-wrap !important;
  word-break: break-all !important;
  flex-wrap: wrap !important;`

**Comment by nytai** [comment]
@ktmud any thoughts on a way we could solve this issue? My instinct would be to add a tooltip for text that's truncated, as that preserves the layout but I'm unsure of how feasible that would be.

**Comment by pabrahamusa** [comment]
@nytai I finally fixed this issue my adding new CSS  inline style for rows in FilterableTableStyles.less . However it would be nice to control it somehow via superset config variable so that anyone wants data to appear in multiple rows they can enable it.

**Comment by rusackas** [comment]
Is anyone still seeing this as an issue in Superset 1.5.x or 2.0.x? Also, I'm on the fence as to whether this is truly a "bug" or more of a feature request. If this has been solved, @pabrahamusa, would you be interested in carrying your solution forward in a PR of some sort? Leaving this open for now, but will close it if nobody is interested in pursuing this.
