### ISSUE TITLE
clickhouse query problem

### ISSUE THREAD

**Issue by queerkid** [apache/superset#11841]
### Expected results
![capture2](https://user-images.githubusercontent.com/1643016/100582414-2951d480-3324-11eb-8dc0-987f49e159ca.png)
### Actual results
![capture](https://user-images.githubusercontent.com/1643016/100583567-d2e59580-3325-11eb-93ac-e63504acfc4e.png)

### Environment
    Operating System: CentOS Linux 7 (Core)
    Kernel: Linux 3.10.0-1062.el7.x86_64
    Architecture: x86-64
    python 3.6.8 
    superset 0.38

**Comment by poleft** [comment]
I found some unexpected case when query in SQL Lab. I can get the result when query in clickhouse client, but with the totally same sql script an "Database Error " occurs when querying in SQL Lab .
Eg. SELECT toDecimal32(toString(2516.9526), 5)
      select cast(123 as String)

**Comment by hi-crab** [comment]
I met the same problem.
I think Superset treat the first line of ClickHouse result as data header, so when resule has only 1 line, Superset return no data.
If ClickHouse return 5 line, Superset only display 4 line.

**Comment by queerkid** [comment]
I use sqlalchemy-clickhouse-timezone 0.1.4 and solved the problem.
