### ISSUE TITLE
[bar chart] Chart cannot scroll horizontally

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#11859]
#### How to reproduce the bug

1. create a time-series bar chart that can be wider than browser view area.

### Actual results

<img width="1584" alt="Screen Shot 2020-11-30 at 1 24 01 PM" src="https://user-images.githubusercontent.com/27990562/100667935-00bfdf80-3310-11eb-9ea8-db6fb1cb838a.png">

### Expected results
User should be able to scroll horizontally to see the right end.

### Environment

latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by graceguo-supercat** [comment]
closed this. reported in superset-ui repo: https://github.com/apache-superset/superset-ui/issues/844

**Comment by junlincc** [comment]
> closed this. reported in superset-ui repo: [apache-superset/superset-ui#844](https://github.com/apache-superset/superset-ui/issues/844)

i closed the other @graceguo-supercat. having all issues reported in the centralized place will help us tackle them quickly, as we have multiple external teams picking up issues. hope you can understand 🙏

**Comment by graceguo-supercat** [comment]
thanks @junlincc! good to know the rule.
