### ISSUE TITLE
Enabling Upload a CSV Functionality

### ISSUE THREAD

**Issue by DeivinsonSilva** [apache/superset#11867]
I am a novice user in Apache Superset, and my first obstacle was to upload a dataset to the system because I did not know the checbox to authorize the upload of .csv files (in the documentation it is described as: enabling the upload functionality of a CSV for your database)

An interesting solution to the problem exposed would be the provision of an authorization checbox for sending .csv files in the same file upload tab, that is, in the CSV data upload tab.
![Screenshot from 2020-11-30 20-55-20](https://user-images.githubusercontent.com/59543861/100680566-95e2c880-3350-11eb-8712-197c08d9b8ec.png)
![Screenshot from 2020-11-30 21-05-42](https://user-images.githubusercontent.com/59543861/100680567-9713f580-3350-11eb-9262-999aec465956.png)

**Comment by amitmiran137** [comment]
we got this documented here: https://superset.apache.org/docs/creating-charts-dashboards/exploring-data#enabling-data-upload-functionality
