### ISSUE TITLE
[explore] improve database error handling

### ISSUE THREAD

**Issue by mistercrunch** [apache/superset#11879]
## Screenshot

<img width="1171" alt="Screen Shot 2020-12-01 at 9 40 40 AM" src="https://user-images.githubusercontent.com/487433/100776417-60be9080-33b9-11eb-96dc-7b704721f98f.png">
<img width="432" alt="Screen Shot 2020-12-01 at 9 40 34 AM" src="https://user-images.githubusercontent.com/487433/100776421-61efbd80-33b9-11eb-8be9-cf00ef145b25.png">

## Description

This kind of error (DatabaseError) should be expected and handled well. It should really say something like `BigQuery error` and offer the right detail as well as monospace-formatted details.

Somehow SQL Lab does a better job at surfacing the error message from the database:
<img width="1155" alt="Screen Shot 2020-12-01 at 9 43 11 AM" src="https://user-images.githubusercontent.com/487433/100776664-a8451c80-33b9-11eb-9e6c-e568e5de2129.png">

We may need database-specific handling of error message strings, so that we can decompose a title, subtitle (one line message) and a longer description. For BigQuery for example, it'd be nice to show only that first string and allow to expand the longer multi-line blob.

**Comment by nytai** [comment]
This should be fixed by https://github.com/apache/superset/pull/14040. If I'm incorrect, please reopen
