### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by eugene-belarus** [apache/superset#11873]
I'm used the superset is released 1-2 years ago and I don't have untranslatable words but when I've updated superset to current version lots of words don't have translations.
Navigation bar ("Data", "Charts", "Dashboards", "SQL Lab", "Setting") can't also be translate for any languages.

### Expected results

There's no untranslatable words.

### Actual results

A lot of words don't have translations

#### Screenshots

![image](https://user-images.githubusercontent.com/71097330/100737956-f1ab6100-33e5-11eb-9098-d1d4e334a033.png)
![image](https://user-images.githubusercontent.com/71097330/100738009-0687f480-33e6-11eb-8044-6199bac4b7f3.png)

**Comment by nytai** [comment]
These menu items are wrapped in babel gettext statements, https://github.com/apache/superset/blob/df04c3af212a18c00a0bc97f8500317551016ce9/superset/app.py#L254

Translations are a community effort and we welcome PRs to add more translations but we are not actively maintaining translations as we make changes to the app.
