### ISSUE TITLE
superset memory is continuing increasing

### ISSUE THREAD

**Issue by zcfrank1st** [apache/superset#11870]
Running for a long time，the memory usage of superset is continuing increasing

### Expected results

the decrease of memory usage

### Actual results

memory usage of superset is continuing increasing

### Environment

(please complete the following information):
 
- python version: 3.6

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zhaoyongjie** [comment]
Hi @zcfrank1st , If you using Gunicorn as a webserver,  I offer a trick to avoid this problem. 

Gunicore provides some options for the restart web workers. you can add these option in your startup script

```
 --max-requests INT    The maximum number of requests a worker will process before restarting. [0]
--max-requests-jitter INT   The maximum jitter to add to the *max_requests* setting. [0]
```
