### ISSUE TITLE
[chart] New chart data API should format errors according to SIP-40

### ISSUE THREAD

**Issue by robdiciuccio** [apache/superset#11882]
Currently, requests to `/api/v1/chart/data` return an error response in the following format:
```
{ message: "error message text here" }
```
Error responses should be formatted according to [SIP-40](https://github.com/apache/incubator-superset/issues/9194) in order to enable rich error reporting for charts in the frontend. 

**Example of chart error reporting with legacy (`/superset/explore_json`) chart requests:**
<img width="458" alt="Screen Shot 2020-12-01 at 3 54 43 PM" src="https://user-images.githubusercontent.com/296227/100810629-bc0a7600-33ed-11eb-9d18-66b5d5690ec5.png">
<img width="595" alt="Screen Shot 2020-12-01 at 3 54 50 PM" src="https://user-images.githubusercontent.com/296227/100810653-c3ca1a80-33ed-11eb-8cba-09355bdd561c.png">

**Example of chart error reporting with new (`/api/v1/chart/data`) chart requests:**
<img width="460" alt="Screen Shot 2020-12-01 at 3 54 57 PM" src="https://user-images.githubusercontent.com/296227/100810727-ee1bd800-33ed-11eb-9190-fd61a1bfe8e5.png">
<img width="593" alt="Screen Shot 2020-12-01 at 3 55 19 PM" src="https://user-images.githubusercontent.com/296227/100810735-f247f580-33ed-11eb-9a90-fb1a1ce7b3d3.png">

**Additional context**
- https://github.com/apache/incubator-superset/issues/9298 (SIP-41)

**Comment by nytai** [comment]
this seems resolved by https://github.com/apache/superset/pull/14040 please reopen if it's not the case
