### ISSUE TITLE
[import]importing dashboard lost annotation on the charts 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#11906]
issue 1: annotation layers are not imported or shown when user import a dashboard with annotations on charts
issue 2: user can not explore the charts on an imported dashboard 

![ezgif-2-7102aefec615](https://user-images.githubusercontent.com/67837651/100951520-8f289280-34c3-11eb-9ab0-c15f7466844e.gif)

cc: @betodealmeida

**Comment by lilila** [comment]
Hello, 
Any news on this issue?

**Comment by michalgala** [comment]
I'm still experiencing the same issue with the latest version of Superset

**Comment by sowo** [comment]
Version 1.5.1 still has the same issue.

**Comment by rusackas** [comment]
We're now on 3.1, on the verge of 4.0, and not supporting 2.x  or prior versions actively. If folks are experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)
