### ISSUE TITLE
Allow to change number of rows in Time series table

### ISSUE THREAD

**Issue by eugeniamz** [apache/superset#11917]
By default time series table retrieve 5000 rows but it does not give the option of changing or show that you reach the limit (in other cases the number of rows are marked red) 

I know that it would better to process less number of rows but the chart is misleading if people do not know the limitation 

![image](https://user-images.githubusercontent.com/58375897/101078867-bb501c00-3574-11eb-82a1-4516316dd7cf.png)

If I filter the rows clearly show the misleading 
![image](https://user-images.githubusercontent.com/58375897/101079425-75e01e80-3575-11eb-817a-4ab3d54c5e59.png)

### Expected results

At least a red mark to show that the data hit or Limit of 5K or the ability to change the count
### Actual results
Show the chart with missing data in not a particular order so the chart is missliding 

#### How to reproduce the bug
Produce a Timer series chart with more than 5K rows

### Environment
0.38

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by maloun96** [comment]
@junlincc It was fixed https://github.com/apache/superset/pull/12887

**Comment by junlincc** [comment]
@eugeniamz we added row limit to time series table. please let me know if this solution is good enough. thanks @maloun96 
<img width="407" alt="Screen Shot 2021-02-07 at 8 31 47 PM" src="https://user-images.githubusercontent.com/67837651/107176186-881a7680-6983-11eb-8fd5-fde9709dc3d3.png">

**Comment by GeorgePearse** [comment]
How can I remove this row limit altogether? Or at least change it? 50000 is insufficient for my histogram, performance is very good.
