### ISSUE TITLE
Improve error message in Time Series Chart when there is not enough data points

### ISSUE THREAD

**Issue by eugeniamz** [apache/superset#11918]
## Screenshot

![image](https://user-images.githubusercontent.com/58375897/101079954-277f4f80-3576-11eb-8a2e-4df2a2103292.png)

## Description
When there are not enough data points, superset prints a weird react message. It would be less scary and preferable a message to said change the time range. 

## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

**Comment by junlincc** [comment]
resolved fix(explore): Error message not displayed correctly in Timeseries table chart #12659
