### ISSUE TITLE
style(sqllab): fix the action icons in table schema (SQL Lab west panel)

### ISSUE THREAD

**Issue by mistercrunch** [apache/superset#11941]
## Screenshot

<img width="344" alt="Screen Shot 2020-12-04 at 2 33 54 PM" src="https://user-images.githubusercontent.com/487433/101222040-cae76780-363d-11eb-9aea-795ea6fc6823.png">

## Description

The chevron icon is in the wrong place. I think it should be right (next to) the table name.

Also, I think it'd be safe to bump the width of the west panel by at least 33%.

**Comment by junlincc** [comment]
<img width="316" alt="Screen Shot 2020-12-04 at 2 38 27 PM" src="https://user-images.githubusercontent.com/67837651/101222542-d25b4080-363e-11eb-95e7-b9fcb3fb527f.png">

1.  action section should not drop lower if the table name is long
2. chevron should not be in the different line 

proposed solution:
1. increase the panel width as @mistercrunch suggested ^,  % is tbd, design should chime in
2. apply max width on the table name. @graceguo-supercat @ktmud any thought on the long title? 

will let @Steejay to take over the discussion

**Comment by yousoph** [comment]
Agreed that the icon doesn't feel like it's in the right place. 

Between these issues and #11725 and #11741, I think this left panel could use a little bit of design love. Will work with @Steejay to come up with a proposal

**Comment by Steejay** [comment]
Agreed. some alignment issues here. I think there are some layout options we can play around with regarding table name and associated dropdown info so we dont have to increase panel width (to preserve space in smaller screen widths). i'll investigate and propose some options here.

**Comment by junlincc** [comment]
> so we dont have to increase panel width 

i'd recommend to do some user research on how much space SQL Lab editor actually need. visually it gets really crowded when table, columns names are long, which is very common in larger organization.

**Comment by Steejay** [comment]
as a quick fix for this issue, we should align chevron with the table name, positioned to the far right (see attached screenshot). To accommodate large names we can increase side panel by 33% for now. that should give us more space. 

we will work with the community to continue exploring better ways to improve this side panel experience. 


<img width="439" alt="Screen Shot 2020-12-04 at 3 31 58 PM" src="https://user-images.githubusercontent.com/60786102/101225312-f8d0aa00-3645-11eb-9d15-374a79d00a05.png">

**Comment by junlincc** [comment]
@geido 🙏

**Comment by junlincc** [comment]
fyi @yousoph we fixed this issue in SQLlab. closing
