### ISSUE TITLE
SQLLAB - Postgres Error when column is not quotations

### ISSUE THREAD

**Issue by hughhhh** [apache/superset#11942]
### Expected results
User should be able to write a query without having to wrap all columns in quotations marks.

```
SELECT 
      DATE_TRUNC('week', year) AS __timestamp,
      SUM(NY_GNP_PCAP_CD) AS "(NY_GNP_PCAP_CD)"
FROM wb_health_population
GROUP BY DATE_TRUNC('week', year)
LIMIT 10000
```

### Actual results

When writing a query to postgres and the column doesn't have quotation the user will receive the following error:

```
postgresql error: column "ny_gnp_pcap_cd" does not exist
LINE 5:       SUM(NY_GNP_PCAP_CD) AS "(NY_GNP_PCAP_CD)"
                  ^
```

```
SELECT 
      DATE_TRUNC('week', year) AS __timestamp,
      SUM("NY_GNP_PCAP_CD") AS "(NY_GNP_PCAP_CD)" -- this works
FROM wb_health_population
GROUP BY DATE_TRUNC('week', year)
LIMIT 10000
```

#### How to reproduce the bug

1. Go to 'sqllab'
2. Select a postgres database
3. Write a query with columns not wrapped in columns (see the example above)

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by yousoph** [comment]
🏷️ sql_lab

**Comment by eschutho** [comment]
🏷 sql_lab

**Comment by eschutho** [comment]
🏷 sql_lab:editor

**Comment by rusackas** [comment]
This still seems to be the case these days. Adding a screenshot for good measure:
<img width="750" alt="image" src="https://user-images.githubusercontent.com/812905/211119205-585fde64-bfc7-4fb1-aaf3-d002b838a7a4.png">

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
