### ISSUE TITLE
SQL lab results cut off

### ISSUE THREAD

**Issue by tooptoop4** [apache/superset#11966]
1. returning 100 rows then can't scroll down to see the last row
2. wide columns (ie values of 5000 characters) show ... on the right and can't be clicked in to see the actual value (need to copy to clipboard, paste somewhere outside of superset to see)

**Comment by yousoph** [comment]
Hi @tooptoop4, could you clarify what you mean by #1 and include a screenshot if possible? Thanks!

**Comment by tooptoop4** [comment]
@yousoph https://github.com/apache/incubator-superset/issues/9869 has example for first point

**Comment by eschutho** [comment]
I'm working on this currently, fyi.

**Comment by nytai** [comment]
Fixed by ☝️
