### ISSUE TITLE
[explore]only fetch View Samples data when needed

### ISSUE THREAD

**Issue by junlincc** [apache/superset#11968]
Context - 

_Currently both results and samples are fetched when user expands Data panel. They are refetched when query params change. I'll try to optimize that so that Samples are fetched only when needed_

_I noticed that on current master, we send a request for samples not only when chart data changes, but every time we open a modal._

_I think that the "View Samples" use case is fairly uncommon. Also note that it only needs to be reprocess when the filters are altered, changing metrics and other query parameters don't require re-fetching/re-rendering._

_Originally posted by @mistercrunch in https://github.com/apache/incubator-superset/issues/11854#issuecomment-738606061_

cc: @kgabryje @mistercrunch

**Comment by ktmud** [comment]
The rendering performance is also not very great while the "View Samples" tab is open. Sorting that table and resizing the panes are almost unberable.

**Comment by ktmud** [comment]
And it stays slow even when I switched back to the View Results tab.

**Comment by kgabryje** [comment]
@ktmud Shall we open an issue for performance improvements?

**Comment by villebro** [comment]
> The rendering performance is also not very great while the "View Samples" tab is open. Sorting that table and resizing the panes are almost unbearably slow. Even adding/removing a metric also becomes slow.

Oh that's what that was. I hit this yesterday and wondered why everything became so sluggish all of a sudden.

> @ktmud Shall we open an issue for performance improvements?

Yeah, I think this is pretty important to fix, as the new layout will probably result in increased use of the Samples tab.
