### ISSUE TITLE
[cosmetic][dashboard] Filter dropdown options on time grain filter not visible

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#12004]
Filter dropdown options are not visible, making it hard for user to make their filter selection.

### Expected results

The filter dropdown should display in a way that it's possible for user to scroll through the options. Drop down should display at least 4 or 5 options, if not all, and give enough space to scroll down and see options easily. 

### Actual results

The filter dropdown displays improperly making very hard for user to select their filter, specifically Drop down for filters box does not allow to see more than 1.5 options, which makes it very hard to use

#### Screenshots

![Screen Shot 2020-12-10 at 11 43 06 AM](https://user-images.githubusercontent.com/61221714/101821791-4ed99d80-3add-11eb-9c27-b99714c5c2cc.png)

![filter-invisible](https://user-images.githubusercontent.com/61221714/101821834-5c8f2300-3add-11eb-8255-d8b15ee916b3.gif)

#### How to reproduce the bug

1. Go to Dashboard
2. Click on Filter box (this is specifically a time grain filter. From Dashboard layout perspective, this time grain filter is right above "Apply button" on filter box. Right below the filter box is "header" followed by charts.
3. When clicking to selecting time grain, See error it doesn't display properly

### Environment

(please complete the following information):

- superset version: `master`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

This was working fine last week, so likely is a regression.

**Comment by junlincc** [comment]
@adam-stasiak let's add this to our test case. 

@zuzana-vej thanks for reporting!

**Comment by junlincc** [comment]
@zuzana-vej btw, we recently fixed the filter box, it's scrollable when the size is small. have you tried it?

**Comment by zuzana-vej** [comment]
Here is a recording. I would expect the TIME GRAIN box behave same as the other dropdowns - see the difference on the video. 

![filterbox-issue](https://user-images.githubusercontent.com/61221714/102153088-42ca4480-3e2b-11eb-80ca-54ee6355bac3.gif)


Otherwise this happens when user resizes the filter box to a small size. The larger the size, the more dropdown option they see - specifically for TIME GRAIN. If the filter box has only TIME GRAIN and they resize it, they face the issue initially described. If the filter box has 10 other filters, or if they keep it large (height) they might not face this issue at all. Most users try to conserve space and make filter boxes as small as possible.

**Comment by zuzana-vej** [comment]
Just wanted to confirm this is still the issue and we are 100% up to date with mater now -- see the gif in above listed comment. it only happens for time grain, and when you don't have many other filter boxes below.

**Comment by zuzana-vej** [comment]
Tested - this looks resolved now on Dashboard (where we discovered the bug).
