### ISSUE TITLE
[global]menu item casing standard in Superset 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12023]
I scanned through most of the menu items in Superset, and found the casing is a mess across the product...
Is there a standard for capitalizing (or not capitalizing) each word in the menu item? if not, we should have one

<img width="155" alt="Screen Shot 2020-12-11 at 7 17 03 PM" src="https://user-images.githubusercontent.com/67837651/101971442-35704880-3be6-11eb-88c4-1bd1c70c1098.png">
<img width="165" alt="Screen Shot 2020-12-11 at 7 16 38 PM" src="https://user-images.githubusercontent.com/67837651/101971446-386b3900-3be6-11eb-871c-03240f40af1c.png">
<img width="163" alt="Screen Shot 2020-12-11 at 7 17 08 PM" src="https://user-images.githubusercontent.com/67837651/101971451-3ef9b080-3be6-11eb-908b-c2dd292e5fec.png">
<img width="245" alt="Screen Shot 2020-12-11 at 7 21 55 PM" src="https://user-images.githubusercontent.com/67837651/101971455-4325ce00-3be6-11eb-9301-7b2fdc0f721d.png">
<img width="241" alt="Screen Shot 2020-12-11 at 7 16 47 PM" src="https://user-images.githubusercontent.com/67837651/101971604-82a0ea00-3be7-11eb-98d7-efb9b1d1a6a4.png">

_Originally posted by @junlincc in https://github.com/apache/incubator-superset/issues/11993#issuecomment-743694009_

**Comment by junlincc** [comment]
@mihir174 @steejay please come up with a standard for Superset. Thanks!

**Comment by ktmud** [comment]
Airbnb convention is only capitalize the first letter. Same for GitHub. This is true for both menu, label, and CTA.

**Comment by rusackas** [comment]
I'm also leaning toward sentence case rather than title case. But I won't put up too much of a fight over it, as long as we're consistent one way or another.

**Comment by mistercrunch** [comment]
Personally I'm fine either way as long as we're consistent!

**Comment by Steejay** [comment]
thanks for flagging. type system review and fixes already in the works. 
cc @mihir174

**Comment by srinify** [comment]
Great idea @junlincc !! I also lean towards sentence case, but agree that consistency is king 👍

**Comment by junlincc** [comment]
+1 for sentence case 
this UI issue is quite noticeable and global which really should have been addressed a while ago. 
@Steejay @mihir174 the implementation is in queue, do you think we can get design input fairly soon?

**Comment by mihir174** [comment]
@junlincc we've scheduled a planning session for this + other global UI consistency issues tomorrow. will update you then!

**Comment by Steejay** [comment]
🗑🏷 needs:design-input

**Comment by junlincc** [comment]
<img width="991" alt="Screen Shot 2021-01-15 at 8 34 01 PM" src="https://user-images.githubusercontent.com/67837651/104798216-0e6ede80-5771-11eb-9d8d-4f0c41d044df.png">

Hey @michael-s-molina , dashboard native filter is under a feature flag currently, please make sure the casing in this modal is also following the design guideline @Steejay and @mihir174 provided. thank you all!
