### ISSUE TITLE
Custom datetype for Dataset is not passed to group by operation

### ISSUE THREAD

**Issue by 0xBADBAC0N** [apache/superset#12037]
### Expected results

If I use a custom temporal column (eG string type but contains %Y%m%d) the type is correctly set in the conditions (where clause) but should also be set correctly in all other locations (eG group by)
### Actual results

what actually happens:
I have set the correct settings for the dataset:
![image](https://user-images.githubusercontent.com/24916828/102083756-59b16c80-3e14-11eb-9e0f-f7daf17f6d9b.png)

and the changes where applied correct to the where clause, but not the group by clause.
![image](https://user-images.githubusercontent.com/24916828/102083788-6635c500-3e14-11eb-80d8-9c7100ff19b7.png)

This generated query would also not really work as in Hive select UNIX_TIMESTAMP('2012-05-10'); (=> NULL)
would break as the custom schema is not pushed down. With pushing down a proper schema, it would work like select UNIX_TIMESTAMP('2012-05-10', 'yyyy-MM-dd'); (=> 1336608000)

#### How to reproduce the bug

1. Create a temporal column as string and add the formatting manually.
2. Try to group by that column in Hive.
3. Click on View Query and see the raw query.

### Environment

(please complete the following information):

- superset version: 0.38
- python version: python 3
- node.js version: n/a

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
