### ISSUE TITLE
Data source password decryption

### ISSUE THREAD

**Issue by xiaoxingxing0** [apache/superset#12034]
The data source ’DBS‘  how to decrypt the 'password' field in the table
For example: DBS in the table:
Sqlalchemy_uri = "+ MSSQL pymssql: / / ifocuscode: XXXXXXXXXX @ host: port/db"
Password = "IgdTq3KqccuAr6wIlBhmtQ = ="
How the password decryption 'password'? The algorithm is what?

**Comment by stevensuting** [comment]
sha256 for the hash
aes-256-cbc to encrypt and decrypt

**Comment by junlincc** [comment]
tracking in #10483
