### ISSUE TITLE
[chart]:area chart tooltip missing highlight 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12031]
area chart has the same issue as [#12030 ](https://github.com/apache/incubator-superset/issues).But there's no highlight on the selected group/area even when the tooltip can fit the view.

<img width="2019" alt="Screen Shot 2020-12-13 at 8 58 56 PM" src="https://user-images.githubusercontent.com/67837651/102043253-c3843480-3d88-11eb-9e80-963a8017a53c.png">

<img width="2021" alt="Screen Shot 2020-12-13 at 9 22 43 PM" src="https://user-images.githubusercontent.com/67837651/102043473-5b821e00-3d89-11eb-92f1-1c5093d57e97.png">

**Comment by rusackas** [comment]
Closing as "won't do" for the same reasons as https://github.com/apache/superset/issues/12030 - namely that we'll be pouring support effort into the ECharts replacement and removing the Legacy chart(s) over time,
