### ISSUE TITLE
Autocomplete issue when searching in CRUD Views for query history

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#12047]
When users search for Query History by username, the autocomplete search doesn't work.

### Expected results
Same behavior as when user searched for example for Dashboards by Owner. When typing, the autocomplete displays the owner.

### Actual results
Nothing happens and user can't even select the owner they want.

#### Screenshots

Query history (issue):
![Screen Shot 2020-12-11 at 12 59 15 PM](https://user-images.githubusercontent.com/61221714/102151248-4f4c9e00-3e27-11eb-9674-ad89b52f7593.png)

Dashboards (correct):
![Screen Shot 2020-12-11 at 12 58 22 PM](https://user-images.githubusercontent.com/61221714/102151245-4d82da80-3e27-11eb-8cd6-8f9920f11c28.png)

#### How to reproduce the bug

1. Go to 'Data --> Datasets'
2. Click on 'Query history'
3. Click into 'user'
4. Start typing

### Environment

(please complete the following information):

- superset version: few days behind `master`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by nytai** [comment]
hmm, it should be working exactly as it does for owners. Thanks for reporting

**Comment by willbarrett** [comment]
Kicked this into our next sprint.

**Comment by zuzana-vej** [comment]
Confirmed the above linked PR fixed this issue.
