### ISSUE TITLE
SQL Lab UI cosmetic issues - buttons overlap when scrolling, results area doesn't adjust size

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#12046]
Few small UI cosmetic issues on SQL Lab:

1. When you scroll all the way down, buttons overlap with results.
![image (3)](https://user-images.githubusercontent.com/61221714/102146862-94200700-3e1e-11eb-96c0-0745f2090394.png)
video:
![SQLLab-UI](https://user-images.githubusercontent.com/61221714/102146568-0f34ed80-3e1e-11eb-8d8f-f1fe91b3b2ee.gif)

2. Some users reported that sometimes the buttons completely disappear.
![image (5)](https://user-images.githubusercontent.com/61221714/102146709-53c08900-3e1e-11eb-9d88-9b97e3137e11.png)

3. There are 3 scroll bars on the right hand side (seems unnecessary)
![image (4)](https://user-images.githubusercontent.com/61221714/102146777-72bf1b00-3e1e-11eb-84a4-d14ff41d2d39.png)

4. The results area doesn't adjust size - in this example, which has only 2 result columns which are both very short, it still display scroller at the bottom. At the same time, when resized to larger monitor, there is lot of white space (this is less annoying than the scroller then there are 2 columns as result)
![Screen Shot 2020-12-14 at 2 55 06 PM](https://user-images.githubusercontent.com/61221714/102146641-34296080-3e1e-11eb-8477-4817e9c42095.png)

![Screen Shot 2020-12-14 at 2 54 54 PM](https://user-images.githubusercontent.com/61221714/102146601-24118100-3e1e-11eb-8ebe-87bc5c2524df.png)

#### How to reproduce the bug

1. Go to 'SQL Lab'
2. Run a query which will return larger number of rows than what would fit on the scree
3. Scroll down to see the various issues
4. Resize your screen (try laptop size / monitor size / half laptop size) 

### Environment

- superset version: couple days behind `master` 
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Couple days behind master, but as per recently merged PRs, haven't noticed any addressing these.

**Comment by zuzana-vej** [comment]
I think the overlapping / disappearing buttons should get resolved. Rest of the items are things I noticed when trying to repro the issue with buttons, and they are nice to have in my opinion.

Browser details: Google Chrome latest version (Version 87.0.4280.88)

**Comment by yousoph** [comment]
Thanks for reporting! We will take a look. Haven't been able to repro the disappearing buttons yet but agreed overlap/disappearing buttons need to be fixed.

**Comment by junlincc** [comment]
@rusackas could it relate to any recent refactoring work we did?

**Comment by hughhhh** [comment]
@eschutho is working on this currently

**Comment by ktmud** [comment]
Closed by #12318
