### ISSUE TITLE
Getting 502 client not found error

### ISSUE THREAD

**Issue by thammanenitcs** [apache/superset#12058]
Hi Team,

I am using superset 0.36 version, have ran a query on sqlab having 13M rows and 25 columns. i am trying to download data using "CSV" download option. The response is giving back to "502 client not found" after sometime. 

When i checked pod logs, it shows "worker is getting rebooted" at some point of time.

### Expected results
CSV file with data of 13M rows.

what you expected to happen.
CSV file has to download.

### Environment
Kubernetes:
pod resource limits :-
resources:
  limits:
	cpu: '1'
	memory: 3000Mi
  requests:
	cpu: 100m
	memory: 400Mi

(please complete the following information):

- superset version: `superset version` 0.36.0
- python version: `python --version` 3.6
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ Y] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [Y ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by robdiciuccio** [comment]
@thammanenitcs The worker process is likely running out of memory if you're attempting to export 13M rows. Suggest you increase available memory or export data in chunks.

See also the `SUPERSET_WEBSERVER_TIMEOUT` config option.
