### ISSUE TITLE
[chart]:categorical color scales and color schemes is broken on treemap

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12068]
### Expected results

With a primary Group By, each region should have a different color label. e.g. South Asia - blue, Europe & Central Asia - yellow, East Asia - green
![image (2)](https://user-images.githubusercontent.com/67837651/102283237-d9a80700-3ee6-11eb-949d-c33cebf9a8e2.png)

### Actual results

everything is green...

<img width="1149" alt="Screen Shot 2020-12-15 at 2 42 46 PM" src="https://user-images.githubusercontent.com/67837651/102282712-dfe9b380-3ee5-11eb-854c-a94f990affc0.png">

This is not a recent regression.

cc: @kristw (we are planning to work on it, do you mind transferring some knowledge if needed? thanks! https://github.com/apache/incubator-superset/pull/5815)

**Comment by mistercrunch** [comment]
🏷️ visualization

**Comment by kristw** [comment]
The legacy treemap did not include a way to specify what to encode color by:
* Currently it is using the depth of the nodes in the tree.
* Prior alternative was to color node by its name, which was also not useful as each node pretty much have unique name and there will never be enough colors so the colors are reused. Then nodes with same color have nothing in common.

It would be best to modify this chart, so users can choose another field to encode color by.
