### ISSUE TITLE
Not able to view dashboards after integrating LDAP in superset

### ISSUE THREAD

**Issue by IamAnandGoudar** [apache/superset#12093]
With Authentication Type as DB, I was able to login with admin/admin. I had all the permissions.
Now I have changed my superset's config.py to use ldap server,
AUTH_TYPE = AUTH_LDAP
AUTH_LDAP_SERVER = "ldap://***.**.**.**"
AUTH_LDAP_SEARCH = "DC=example,DC=com"
AUTH_LDAP_BIND_USER = "ou=users,dc=example,dc=com"
AUTH_LDAP_BIND_PASSWORD = "**********"
AUTH_LDAP_UID_FIELD = "sAMAccountName"

After making these changes and installing pythonldap in my environment, I was able to successfully login.
But now, I dont have permission to view/create dashboards/charts or do any other thing 
<img width="928" alt="Superset_LDAP" src="https://user-images.githubusercontent.com/59425258/102458203-e99c2400-4069-11eb-9e17-4db35bdb455f.PNG">

**Comment by dpgaspar** [comment]
Hi,

Can you please fill all the fields necessary for a bug report, would be really helpful also to include server logs. Thank you!

**Comment by ImadYamane** [comment]
I have the same issue, @IamAnandGoudar  have you found a solution? 🙄
