### ISSUE TITLE
[cosmetic][dashboard] Expanding three dots on filter box is rendered behind, not all options visible

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#12108]
Cosmetic issue (regression) - when you click the three dots on a smaller filter box, the popup with list of options renders in the background (inside the filter box component) instead of over (previous behavior) meaning it's hard for user to select their action. This is especially visible on the filter box, (could be in small charts too in theory).

### Expected results

Render over so that all options are visible

### Actual results

renders behind (lilmited to filter box size)

#### Screenshots
![fikter-box-cosmetic](https://user-images.githubusercontent.com/61221714/102564943-537bf400-4091-11eb-8ac4-acb578aaed7f.png)
![filter-box-cosmetic](https://user-images.githubusercontent.com/61221714/102564944-5545b780-4091-11eb-8cee-1917b9627dc7.png)

#### How to reproduce the bug

1. Create a small (in terms of height) filter box
2. Click on the three dots
3. See issue

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Regression

**Comment by zuzana-vej** [comment]
This one is certainly low priority, probably introduced together with https://github.com/apache/incubator-superset/issues/12107 and https://github.com/apache/incubator-superset/issues/12105

**Comment by rusackas** [comment]
I think I see what's happening here... in `SliceHeaderControls.jsx` you can see that AntD's `getPopupContainer` is used to render the Dropdown within the chart, where it used to be rendered in the `body` (the default behavior). This happened to show/hide the menu when taking a screenshot, which was fixed in https://github.com/apache/incubator-superset/pulls/11778 

CCing for context: @kgabryje @nikolagigic @geido @maloun96

**Comment by kgabryje** [comment]
Most likely it's caused by `visibilty: hidden` in 1 of Antd's components. Overriding it to `visible` should do the trick. I can take a look once I'm done with tasks related to explore redesign

**Comment by maloun96** [comment]
https://github.com/apache/incubator-superset/issues/12108

**Comment by zuzana-vej** [comment]
fixed
