### ISSUE TITLE
[Explore]chart/data split view resizing height does not work properly 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12102]
Expected behavior:
when user resizes screen vertically, both Chart and Data section should adjust their height accordingly, making sure the data section is alway accessible to user despite the screen sizes. 

resizing from the bottom ❌
<img width="1572" alt="Screen Shot 2020-12-17 at 11 16 57 AM" src="https://user-images.githubusercontent.com/67837651/102532942-96ba7080-4059-11eb-8ab4-da5c23f22ea8.png">
<img width="1534" alt="Screen Shot 2020-12-17 at 11 17 20 AM" src="https://user-images.githubusercontent.com/67837651/102532950-991cca80-4059-11eb-8575-ca127fcb629b.png">
from the side ✅
<img width="718" alt="Screen Shot 2020-12-17 at 11 17 40 AM" src="https://user-images.githubusercontent.com/67837651/102533391-34ae3b00-405a-11eb-8ea9-273c3f832e48.png">
From the corner ✅ side first then bottom
From the corner ❌ bottom first then side
<img width="1417" alt="Screen Shot 2020-12-17 at 11 17 57 AM" src="https://user-images.githubusercontent.com/67837651/102532957-9de17e80-4059-11eb-853a-c31085d524e5.png">

**Comment by junlincc** [comment]
@maloun96 hey Victor, mind taking this on? please reach out to the feature owner @kgabryje if you have any questions. thanks!🙏

**Comment by zuzana-vej** [comment]
<img width="1107" alt="Screen Shot 2021-01-05 at 4 04 30 PM" src="https://user-images.githubusercontent.com/61221714/103712975-009aab80-4f70-11eb-8b5c-1669802a23a2.png">

Just noticed this on another chart also during resizing (adding screenshot just fyi)

**Comment by junlincc** [comment]
issue is fixed by#12250 but still follow up work need to be done https://github.com/apache/superset/issues/12296
