### ISSUE TITLE
[Cosmetic][SQL Lab] Don't capitalize SQL Lab tabs

### ISSUE THREAD

**Issue by ktmud** [apache/superset#12134]
#### Current

<img src="https://user-images.githubusercontent.com/335541/102665957-b4133b80-413a-11eb-8ffe-604157faa5db.png" width="600">

#### Proposed

<img src="https://user-images.githubusercontent.com/335541/102665928-a5c51f80-413a-11eb-9c91-695e7cdf754e.png" width="500">

## Description

We shouldn't capitalize user inputs. If it makes sense for users to capitalize, they will do it themselves!

This thing is tiny but following is the actual feedback we get from users when we reversed all caps (https://github.com/apache/incubator-superset/pull/11570) for dashboard tabs:

![image](https://user-images.githubusercontent.com/335541/102666158-2126d100-413b-11eb-9da8-e2a7016fe8ef.png)

## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

**Comment by junlincc** [comment]
+1

**Comment by Steejay** [comment]
Agreed @ktmud. Tab names should not force all caps.

**Comment by junlincc** [comment]
CC @yousoph   fixed closing
