### ISSUE TITLE
[explore]customize previous calendar week time range 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12141]
<img width="1180" alt="Screen Shot 2020-12-18 at 8 41 56 PM" src="https://user-images.githubusercontent.com/67837651/102680903-bfce2480-4171-11eb-8b1a-641cffd3dd0f.png">
<img width="543" alt="Screen Shot 2020-12-18 at 8 43 45 PM" src="https://user-images.githubusercontent.com/67837651/102680907-c2c91500-4171-11eb-946d-1f612ca45532.png">

also minor issue, need to set calendar week range from `Sunday to Saturday` instead of `Monday to Sunday `

latest master

**Comment by nytai** [comment]
I this this varies by locale, some start the week on Sunday and others on Monday. From [wikipedia](https://en.wikipedia.org/wiki/Week)

>While, for example, the United States, Canada, Brazil, Japan and other countries consider Sunday as the first day of the week, and while the week begins with Saturday in much of the Middle East, the international ISO 8601 standard and most of Europe has Monday as the first day of the week.

It's likely that whatever library is generating this range is following the ISO 8601 standard.

**Comment by junlincc** [comment]
enhancement request: allow user to customize "calendar week"

**Comment by nytai** [comment]
We could also try to detect the locale, but empowering the user is probably best for a BI tool.

**Comment by zhaoyongjie** [comment]
This is a problem that can be solved by introducing a config item. 

```
# Which is the first day of the week, the default set to 1 or 0
FIRST_DAY_OF_WEEK = [0-6]
```

**Comment by zhaoyongjie** [comment]
@nytai Since the server is often set to UTC time zone, it may not be easy to detect

**Comment by Beknazar19** [comment]
> This is a problem that can be solved by introducing a config item.
> 
> ```
> # Which is the first day of the week, the default set to 1 or 0
> FIRST_DAY_OF_WEEK = [0-6]
> ```

you want to say just add a line FIRST_DAY_OF_WEEK = [0-6]  and that's it? or something else needs to be added?
thanks
