### ISSUE TITLE
Add ErrorBoundary to page components

### ISSUE THREAD

**Issue by ktmud** [apache/superset#12149]
Sometimes pages go completely blank when a JS error happens (#11908, #11759 , #11568 ). 

We should wrap major subcomponents with `ErrorBoundary` so users can still navigate off the error state.

@nytai has [raised the issue](https://github.com/apache/incubator-superset/issues/11759#issuecomment-730714595) before. Creating a ticket to keep track of progress.

A recommended list of boundaries to add:

1. Explore
    - [ ] Datasource Column
    - [ ] Chart Control Column
    - [ ] Chart Header
    - [x] Chart Render
    - [ ] Chart Data Preview
    - [ ] DataSource Editor Modal
2. SQL Lab
    - [ ] Datasource Sidebar
    - [ ] SQL Editor
    - [ ] Query Results Preview
3. Dashboard
    - [x] Filters
    - [ ] Main dashboard body
3. List View Pages
    - [ ] Filters
    - [ ] List Table View
    - [ ] Thumbnails View
4. Home Page
    - [ ] Recents
    - [x] Charts
    - [ ] Dashboards
    - [ ] Saved Queries

**Comment by junlincc** [comment]
related? https://github.com/apache/incubator-superset/issues/12109

**Comment by zuzana-vej** [comment]
resolved by the linked PR?
