### ISSUE TITLE
CSRF Token Issue when embedding Superset in iFrame

### ISSUE THREAD

**Issue by skini-galaxia** [apache/superset#12150]
On embedding Superset in an HTML iframe, a 'Bad Request' is displayed.

The fixes mentioned in https://github.com/apache/incubator-superset/issues/8382 do not seem to fix this completely.

On completing the following steps, the issue was resolved:
- Create a new hostname using sudo nano /etc/hosts (eg foo.bar.com) with the IP address of the machine (use ifconfig).
- Run the command python -m http.server 8000 in the directory containing the file with the embedded iframe.
- Change `SESSION_COOKIE_SAMESITE = None ` in superset/config.py.

Requesting the following steps to be added in the documentation for some clarity or a fix/workaround for this issue.

**Comment by Riskatri** [comment]
hi, i have same issue. can you explain solution for this issue?

**Comment by Avinashbitm** [comment]
i am facing same issues

**Comment by etr2460** [comment]
`SESSION_COOKIE_SAMESITE` need to be set to `"None"` not `None`. That should resole your issue
