### ISSUE TITLE
rest api doc is incomplete

### ISSUE THREAD

**Issue by kurtiswen** [apache/superset#12173]
rest api doc is incomplete, many rest api are not on the swagger page.
is there any plan on refining this? cause it's very important for those who want to do integration with superset.

**Comment by dpgaspar** [comment]
I think that all the new `/api/v1/` API's have a OpenAPI spec. Other API's will eventually be refactored and land on `api/v1`.

is something is missing on `api/v1` or you would like to see improved?

**Comment by kurtiswen** [comment]
> I think that all the new `/api/v1/` API's have a OpenAPI spec. Other API's will eventually be refactored and land on `api/v1`.
> 
> is something is missing on `api/v1` or you would like to see improved?

hi dpgaspar,
thank you for your reply,  do you mean this /api/v1/_openapi for openApi spec? I think is contains just the same api list as in swagger. If OpenAPI spec can be found in other place, please let me konw.

**Comment by amitmiran137** [comment]
What @dpgaspar means is that only api's under the /api/v1 route are and will be documented and eventually all api's will migrate under that pattern
