### ISSUE TITLE
Superset slice API with standalone to true error

### ISSUE THREAD

**Issue by dpgaspar** [apache/superset#12176]
On thumbnails and alerts/reports screenshot use the following link:

`<server>/superset/slice/<slice_id>/?standalone=true`

But the link does not render a chart, with the following error:

![Screenshot 2020-12-22 at 14 07 07](https://user-images.githubusercontent.com/4025227/102896872-ff8d5880-445e-11eb-944f-cceb8011b711.png)

stands out to me:
```
Uncaught Error: Target container is not a DOM element.
```

When using `<server>/superset/slice/<slice_id>/` (without the standalone option) the chart renders has expected in a explore view

### Expected results

The chart is rendered in standalone and a screenshot can be taken by selenium

### Actual results

No chart is rendered and selenium errors out

#### How to reproduce the bug

1. Go to: `<server>/superset/slice/<slice_id>/?standalone=true`, eg: `http://localhost:9000/superset/slice/323/?standalone=true`

### Environment

- superset version: using master sha: 8d5dcc57849da9af1394f3d1e491fd08b2e88666, and latest
- python version: 3.7.6
- node.js version: v12.18.3

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by lilila** [comment]
Hi @dpgaspar , I have this problem as well with superset 0.38 but it only fails with safari in my case. It works properly with chrome or Firefox.

**Comment by dpgaspar** [comment]
@lilila there was a recent major refactor done that lead to this regression. So, not sure if the refactor (and fix) fixed the problem you're reporting or not. Something we need to test (I'll keep this issue open)

**Comment by amitmiran137** [comment]
Can someone screenshot how does a working slice with standalone=true looks like?

**Comment by junlincc** [comment]
fixed by https://github.com/apache/superset/pull/12179
