### ISSUE TITLE
hot update was not successful

### ISSUE THREAD

**Issue by hyouinKyouma** [apache/superset#12197]
I am trying to create a visulization plugin, for which I was following this link https://preset.io/blog/2020-07-02-hello-world/.

Here I am running the frontend via npm run dev-server
and the backend through docker-compose up

but when I run "npm run dev-server" and go to the http://localhost:9000

It gives me following error:

hot update was not successful
hot update failed for module "./src/views/App.tsx". Last file processed: "./src/views/App.tsx".

- superset version: `superset version`
- python version: `3.8.7`
- node.js version: `10.19.0`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
![Screenshot from 2020-12-23 21-51-50](https://user-images.githubusercontent.com/37413995/103017912-53d12f00-456a-11eb-8740-2b120de77dec.png)

**Comment by poppyc0ck** [comment]
anyone know it?

**Comment by poppyc0ck** [comment]
@hyouinKyouma refer to [this](https://github.com/gaearon/react-hot-loader/issues/1302#issuecomment-529851594)

it work for me. closed IDE !
