### ISSUE TITLE
[Chart]Use X-Y axis d3 formatting in tooltip

### ISSUE THREAD

**Issue by kamalkeshavani-aiinside** [apache/superset#12190]
**Is your feature request related to a problem? Please describe.**
Many charts allow to change formatting of X-Y axis values using d3 format. This updates the tick values shown on respective axis, but it still shows axis value with 'adaptive formatting' in tooltip.

**Describe the solution you'd like**
It would be better if the updated formatting gets reflected in tooltip as well.

**Describe alternatives you've considered**
In Pie chart, since there is no axis, formatting for tooltip value is allowed. Similarly it should be possible for other charts as well.

From Sample data(superset v0.999.0dev):
Changed the X-axis formatting to '%Y-%M-%D', but the tooltip shows X-axis value in 'Adaptive Formatting' applied.

![image](https://user-images.githubusercontent.com/74634977/102963551-b7d50280-452c-11eb-86d0-b19b12a6ba71.png)

**Comment by junlincc** [comment]
thanks for the request. it makes sense updating the tooltip as well to reflect the X AXIS FORMAT.
<img width="368" alt="Screen Shot 2020-12-26 at 7 32 37 AM" src="https://user-images.githubusercontent.com/67837651/103154525-aff3a900-474c-11eb-84dd-5ff01056b3f9.png">

**Comment by maoqin** [comment]
Also, in line charts, if you check rich tooltip,  the tooltip will use default format despite the X-axis formatting is '%Y-%M-%D'
![image](https://user-images.githubusercontent.com/3340437/103719113-4bb1ce80-5003-11eb-95f8-7106938d0876.png)
if you don't check rich tooltip, the tooltip will follow x-axis's format
![image](https://user-images.githubusercontent.com/3340437/103719184-6e43e780-5003-11eb-9dec-c17547a86303.png)

**Comment by kamalkeshavani-aiinside** [comment]
@maloun96 @junlincc 
As mentioned by @maoqin, this should work with Rich Tooltip as well. Please add the required changes.:pray:
