### ISSUE TITLE
[sqllab]Show number of rows returned in SQL Lab

### ISSUE THREAD

**Issue by tooptoop4** [apache/superset#12194]
Run a non-count query like: select * from table where x = 'y'

In addition to the table of rows returned, would like to have "x rows returned" (ie 863 rows returned)
JDBC tools currently have this.

**Comment by betodealmeida** [comment]
@yousoph do we have a plan for this in the new SQL Lab design?

**Comment by yousoph** [comment]
Thanks @tooptoop4 ! We don't have a design for this yet but I think this makes sense to add
cc @steejay

**Comment by yousoph** [comment]
Handling this work under #12436
