### ISSUE TITLE
[Explore]poor performance while query triggered without clicking "RUN QUERY" 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12207]
Adding or changing values(metics, filters and groupby values etc.) in Explore Query should not randomly trigger a new query until user clicks "RUN QUERY" button. 

https://user-images.githubusercontent.com/67837651/103155362-103a1900-4754-11eb-8622-05f84d991271.mov

https://user-images.githubusercontent.com/67837651/103155364-129c7300-4754-11eb-9630-bea5d5cfc07d.mov

**Comment by ktmud** [comment]
Do note that previously some controls will automatically trigger a re-render (in case of pure chart UI changes like changing axis labels, number formatting, etc) but never a new query.

**Comment by junlincc** [comment]
Confirming this issue is resolved in latest master 01/09/2021 @ 5:43pm (UTC)

![ezgif-3-1a56d7961c0d](https://user-images.githubusercontent.com/67837651/104104823-4c46a100-525f-11eb-8679-86b91df58f97.gif)

cc @graceguo-supercat @ktmud @zuzana-vej @mistercrunch
