### ISSUE TITLE
Superset doesnt start after centos reboot

### ISSUE THREAD

**Issue by nishwalshetty** [apache/superset#12209]
i am using the below command in python3.8 virtual environment manually by running the below command

superset run -p 8088 --with-threads --reload --debugger --host 10.10.11.64

### Expected results
Dashboard to be up and running

### Actual results

Stuck after "debugger is active warning", nothing after that

Console log

(superset) [root@superset ~]# superset run -p 8088 --with-threads --reload --debugger --host 10.10.11.64
logging was configured successfully
INFO:superset.utils.logging_configurator:logging was configured successfully
/root/superset/lib/python3.8/site-packages/flask_caching/__init__.py:191: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn(
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:werkzeug: * Running on http://10.10.11.64:8088/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
logging was configured successfully
INFO:superset.utils.logging_configurator:logging was configured successfully
/root/superset/lib/python3.8/site-packages/flask_caching/__init__.py:191: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn(
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 209-981-339

### Environment

(please complete the following information):

- superset version: `0.37.1`
- python version: `3.8.6rcl`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by nishwalshetty** [comment]
https://github.com/apache/incubator-superset/issues/9994#issue-631412402 just found a similar issue with no resolution

There is no error in console for me to debug!!!

Any suggestions to resolve this  ?

**Comment by zhaoyongjie** [comment]
Hey @nishwalshetty. What do you want to do? To start a Superset dev-sever? From your logs, the dev-server looks like it's up.

**Comment by nishwalshetty** [comment]
> Hey @nishwalshetty. What do you want to do? To start a Superset dev-sever? From your logs, the dev-server looks like it's up.
> Yes i want to start it
> If the browser does not have any content. You may need to compile the frontend by following commands
> Yes browser does not have any content, how do i compile the superset source code ?  i have installed superset in python virtual environment and im not using docker way of deployment.
> ```
> $ cd superset-frontend
> $ npm install
> $ npm run build
> ```

**Comment by nishwalshetty** [comment]
This is resolved now, issue was with firewall

Thanks for the support
