### ISSUE TITLE
[Explore]poor rendering performance while on "View Samples" tab

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12206]
The rendering performance is also not very great while the "View Samples" tab is open. Sorting that table and resizing the panes are almost unbearably slow. Even adding/removing a metric also becomes slow.

And it stays slow even when I switched back to the View Results tab.
_Originally posted by @ktmud in https://github.com/apache/incubator-superset/issues/11968#issuecomment-747945240_

**Comment by junlincc** [comment]
fixed

**Comment by ktmud** [comment]
fixed by #12257

**Comment by junlincc** [comment]
Confirming this issue is resolved/improved in latest master 01/09/2021 @ 5:36pm (UTC)

![ezgif-3-8745bc170a51](https://user-images.githubusercontent.com/67837651/104104627-2e2c7100-525e-11eb-83e7-be67eb390588.gif)

cc @graceguo-supercat @ktmud @zuzana-vej @mistercrunch
