### ISSUE TITLE
ImportError: cannot import name 'Any'  when start server

### ISSUE THREAD

**Issue by qinzl1** [apache/superset#12225]
- superset version: 3.7.2
- python version: 3.6.8

after  excute  "pybabel compile -d translations"
![image](https://user-images.githubusercontent.com/20242930/103326132-e6e9f780-4a89-11eb-9728-c943dbb20487.png)

**Comment by villebro** [comment]
I assume this is Superset version 0.37.2? Can you check what your `PYTHONPATH` env variable looks like? I also suggest switching to Python 3.7, as we've dropped support for 3.6 on master branch and upcoming versions.

**Comment by SahanaHandyal** [comment]
This is not an issue only with version 0.37.2 or with Python 3.7, I tried different versions of Superset and with Python 3.7/3.8. The issue is recurring. Please reopen this issue and suggest a resolution.

Note: versions 0.35.1 and below are working fine.
