### ISSUE TITLE
Update documentation for Custom OAuth2 Configuration for superset version >= 0.37.0

### ISSUE THREAD

**Issue by HUSSTECH** [apache/superset#12222]
### Expected results

Prerequisite: deployment is using a [Custom OAuth2 Configuration](https://github.com/apache/incubator-superset/blob/master/docs/src/pages/docs/installation/configuring.mdx)

After upgrading to `>= 0.37.0`, following notes in [UPDATING.md#0.37.0](https://github.com/apache/incubator-superset/blob/master/UPDATING.md#0370) and [updating](https://github.com/dpgaspar/Flask-AppBuilder/blob/v3.0.1/README.rst#change-log) the OAuth configuration in FAB for the breaking change, Superset should restart and function as normal.

### Actual results

Users unable to log in with an error message "invalid login please try again". Logs will show the following ERROR output
```
ERROR:flask_appbuilder.security.views:Error returning OAuth user info: 'Response' object has no attribute 'data'
```
### Solution

Due to the update of FAB to 3.0.0, we can see in their [`security/manager.py`](https://github.com/dpgaspar/Flask-AppBuilder/blob/22d546012c877773595c9d3c88c0be766f02fbbe/flask_appbuilder/security/manager.py#L513) module the updated call to get the response data directly from a requests.Response object. From `.data` to `.json()`.

For most people the change is simple enough. In your `CustomSsoSecurityManager` class, update the line from,
```python
me = self.appbuilder.sm.oauth_remotes[provider].get('userinfo').data
```
to
```python
me = self.appbuilder.sm.oauth_remotes[provider].get('userinfo').json()
```
> Note: I have seen implementations where `.get('userDetails')` or `.get('userinfo')` are used. Depends on your setup.

### Additional context

Searching the repo, I think an update to the docs is just required to the following files:
- docs/src/pages/docs/installation/configuring.mdx
- docs/installation.rst

**Comment by Bhavik-Ardeshna** [comment]
Hello I want to work on this is

**Comment by Bhavik-Ardeshna** [comment]
@HUSSTECH I am new to superset , Plz guide me

**Comment by zuzana-vej** [comment]
Hi @Bhavik-Ardeshna  are you still facing this issue / have this question? have you tried the Superset 1.0 release? Closing for now but please reopen if you face the issue on the latest Superset release as well.
