### ISSUE TITLE
[Explore]Data panel Metrics section should expand on click the caret 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12233]
Current behavior
1. Data panel shows first 50 columns in Columns section, and the section is open by default; Users have to scroll down to get to the Metrics section 
2. Metrics section is closed by default; Users click the caret to open Metrics section 
3. Section opens below but it is not expanded visibly; users have to scroll down to see Metrics list  
4. After scrolling down to view metrics, repeat the action, section now expands

Expected 
Data panel Metrics section should expand after the first click on caret without user scrolling down. 

https://user-images.githubusercontent.com/67837651/103448009-2b22f680-4c48-11eb-962c-36b74bb4f864.mov

**Comment by junlincc** [comment]
or maybe we should keep both sections open by default if it does not affect performance? @zhaoyongjie

**Comment by zhaoyongjie** [comment]
-  displaying many dimensions and metrics will affect the rendering efficiency
- but we should use other methods to control whether this data source displays these fields or not (e.g. add an option to control dimensions/metrics visible in explore)
- Before extra-control is done, it makes sense to expand both dimensions/metrics.

**Comment by junlincc** [comment]
I would not recommend compromising the performance to favor UX for this one. do you think we can address the original issue i filed for now? which is click to auto expand Metrics section?  @zhaoyongjie

**Comment by geido** [comment]
@junlincc Looking at the implementation this was made to work as an accordion (only one section can collapse at a time). However, the Antd Collapse component wasn't properly implemented in this PR #12008. That makes the accordion to fail. I will submit a PR to fix it. PR #12008 is also introducing a custom flavor of the Antd Collapse. This will need to be consolidated and moved to the enhanced one as I have also reported here #12218
