### ISSUE TITLE
Line_multi charts keeps refreshing after upgrade

### ISSUE THREAD

**Issue by maoqin** [apache/superset#12268]
line_multi charts keeps refreshing and sending xhr requests to backend, an error in the console: 
`Error: <g> attribute transform: Trailing garbage, "translate(0,NaN)".`
not sure if its related.

### Expected results
no refresh, works as before upgrading

### Actual results

charts keeps refreshing and flooded backend

#### Screenshots
![image](https://user-images.githubusercontent.com/3340437/103619644-10fd5700-4f6d-11eb-84de-4ef0f76aaf11.png)

#### How to reproduce the bug

1. create a line_multi chart
2. add first line chart
3. add second line chart
4. chart starts to refresh

### Environment

(please complete the following information):

- superset version: 0.38.0
- python version: 3.6
- node.js version: 9.9.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@adam-stasiak please help test it. i am not able to reproduce, @kgabryje fixed this earlier

**Comment by villebro** [comment]
Reproduced, fix coming up.
