### ISSUE TITLE
[dashboard] chart loading spinner didn't show

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#12264]
#### Screenshots
![83vMV7zabc](https://user-images.githubusercontent.com/27990562/103599937-20bc6300-4ebb-11eb-99c1-c91ecb92af62.gif)

#### How to reproduce the bug

1. Go to a dashboard with a lot of charts and less cached data.
2. You **should** see spinner when chart is loading, but it is not showing right now. When chart is loaded, the chart area is empty blank.
3. But you can see spinner when you force refresh a chart.

### Environment

latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

It looks not quite related, but actually this regression is caused by #11854.

cc @junlincc @zuzana-vej

**Comment by junlincc** [comment]
Thanks for reporting! This new feature did introduce some regressions in both Explore and Dashboard. (i still very much value the work though ♥️ @kgabryje)
@geido can you take this on just and get more familiar w Dashboard? Prioritizing it as P1 bug. 🙏
