### ISSUE TITLE
[dashboard]CSS Templates not working

### ISSUE THREAD

**Issue by syazwan0913** [apache/superset#12265]
### Expected results

Black background is preserved after refresh

### Actual results

Black background missing after refresh

#### Screenshots
![dsvyXHvQ1B](https://user-images.githubusercontent.com/28984703/103603819-74c25880-4f4a-11eb-9e1d-46f867b82954.gif)

#### How to reproduce the bug

1. Go to 'Any dashboard'
2. Click on 'Edit dashboard > Edit CSS'
3. Save CSS template
4. Refresh browser
5. See error

### Environment

(please complete the following information):

- superset version: `0.38.0`
- python version: `based on superset version 0.38.0`
- node.js version: `based on superset version 0.38.0`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
could it cause by our native filter feature flag? @rusackas
