### ISSUE TITLE
Roles (permissions) to avoid a user delete Datasets not created by him/her

### ISSUE THREAD

**Issue by akelai** [apache/superset#12262]
Does a way exist to allow a user to edit or delete a Datasource created in a (PostgreSQL) database with the Upload CSV feature, but not allowing him/her to edit or delete Datasources that have not been created by that same user?

For example, admin user could have created some demo Datasources. Also, some users may have created some useful Datasources.
A new registered user could have permissions to upload CSV and create a new Datasource, but shouldn't be able to delete or edit existing ones. Is that already feasible?

**Comment by amitmiran137** [comment]
basically datasets are managed by creator/owners , anyone which is not an owner cannot deletes other's datasets unless he is  admin
