### ISSUE TITLE
[dashboard]Add Chart filters displayed in Applied filters section

### ISSUE THREAD

**Issue by adam-stasiak** [apache/superset#12273]
**Is your feature request related to a problem? Please describe.**
When I set filter in explore view of chart then I would expect to see these filter in Applied (Not in not Applied) filters section.

**Describe the solution you'd like**
Please add an option to display in this section filters chosen for chart from explore view.
![image](https://user-images.githubusercontent.com/25153919/103643827-9bd25780-4f55-11eb-9157-625517eae2b0.png)
![image](https://user-images.githubusercontent.com/25153919/103643853-a4c32900-4f55-11eb-871d-1ce3364d2f58.png)
<img width="1177" alt="Zrzut ekranu 2021-01-5 o 12 58 57" src="https://user-images.githubusercontent.com/25153919/103643960-d76d2180-4f55-11eb-8767-1852991b759b.png">
![image](https://user-images.githubusercontent.com/25153919/103644006-ec49b500-4f55-11eb-8b2e-a12bfef212a1.png)

**Describe alternatives you've considered**
-
**Additional context**

**Comment by junlincc** [comment]
https://github.com/apache-superset/superset-roadmap/issues/96 We are committed to make this happen! thanks for suggesting! @adam-stasiak

**Comment by rusackas** [comment]
I know this filter indicator is in a bit of a redesign phase right now. @kasiazjc / @jess-dillard do we still want to pursue this? If so, we can migrate it to an Ideas discussion, and if not, I can close this out as a "won't do".

**Comment by jess-dillard** [comment]
@rusackas I think we can mark this one as "won't do".
