### ISSUE TITLE
Filtered chart in email

### ISSUE THREAD

**Issue by singh-ab** [apache/superset#12270]
**Is your feature request related to a problem? Please describe.**
While superset offers the functionality of scheduling a chart as an email. We cannot send an email with a filter , to achieve this we have to save the same chart with multiple names , have the filter attached and then schedule them

**Describe the solution you'd like**
It would be great to have the functionality extended with filters on chart .

**Comment by zhaoyongjie** [comment]
@singh-ab I am curious about the chart can not with filter, the filter is embedded in the charts, why is it not sending by email

**Comment by junlincc** [comment]
cc @benceorlai

**Comment by singh-ab** [comment]
@zhaoyongjie : thanks I will give this a try !
that said if anyone has examples around this feel free to share it here 😃  ?

**Comment by zuzana-vej** [comment]
Closing this in favor of this request: https://github.com/apache/superset/issues/13954 feel free to continue discussion there / tackle this specific feature request.
