### ISSUE TITLE
[Explore] Timepicker converts date range type on pill

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#12285]
#### How to reproduce the bug

1. Go to Explore view, from date picker, choose `Range Type`: Last, then choose `Last week`.
2. see `Time Range` display as `2020-12-29 <= col < 2021-01-05`.
3. The time range is correct, but it is **not** the option that user chosen: Last week.
4. The reason that we offered `Last` or `Previous` is these human readable time range is easier for user to get what the time range is. If user pick these Range Type, we should display as it. If user pick from custom type and pick same date, we should display the date.

#### Screenshots

![Screen_Shot_2021-01-05_at_10_24_20_AM-2](https://user-images.githubusercontent.com/27990562/103692850-3e3a0d00-4f4d-11eb-9938-8294f8f7d9b9.jpg)

### Environment

latest master

cc @junlincc @zhaoyongjie @zuzana-vej

**Comment by junlincc** [comment]
we display the actual time range on the pill as a validation. if that's compromising UX, we are happy to switch it back for `last` and `previous`

**Comment by graceguo-supercat** [comment]
yes, display `Last week` is old behavior. Even for the old date picker, you can pick "Last week" as option, and then we display "Last week" in the time range pill (as shown in screenshot).
when i run some old charts from latest master branch, all the "Last week" are displayed as actual date. I think this change is not necessary, will cause some confusion.

**Comment by junlincc** [comment]
Confirming all known issues around Explore Timepicker are resolved in latest master 
will implement tooltip for Advanced Time Range and new feature - customize timezone in Q1

cc @graceguo-supercat @ktmud @zuzana-vej @mistercrunch
