### ISSUE TITLE
GitHub repo move - rewire all reference from apache/incubator-superset to apache/superset

### ISSUE THREAD

**Issue by mistercrunch** [apache/superset#12286]
Repo has been moved to reflect our recent graduation, yet our repo is full of references to the old location. While GitHub handles all redirects properly, we should still update all of the references in the repo

```
12:05 $ git grep "incubator-superset" | wc -l
    5108
```

**Comment by amitmiran137** [comment]
![image](https://user-images.githubusercontent.com/47772523/103699490-afa8a880-4fab-11eb-9462-57a3c995c8ba.png)

**Comment by mistercrunch** [comment]
looks like things are moving here: https://github.com/apache/superset/pull/12284

**Comment by nytai** [comment]
I removed incubation/incubating in https://github.com/apache/superset/pull/12284, looks like @amitmiran137 removed incubator-superset in https://github.com/apache/superset/pull/12289
