### ISSUE TITLE
[Explore] Data pane in explore not resizing on widow resize

### ISSUE THREAD

**Issue by rusackas** [apache/superset#12296]
## Screenshot / Description

In Explore, the Data pane is not updating its height when the window is vertically resized. This has two easily reproduced cases:

1) Start with a TALL window and open the data pane. Shorten the window. You'll see that the entire chart+table area scrolls due to the lack of table resize. Collapse and re-open the Data area, and you'll see the height is adjusted (no more scrollbar).

https://user-images.githubusercontent.com/812905/103616825-fdf17500-4ee1-11eb-9970-919755364505.mp4

2) Start with a SHORT window an open the data pane. Lengthen the window. You'll see that the table is unnecessarily cropped off. Collapse and re-open the Data area, and you'll see the height is adjusted (no more cropping).

https://user-images.githubusercontent.com/812905/103616970-38f3a880-4ee2-11eb-86ba-40314038af30.mp4

**Comment by rusackas** [comment]
@maloun96 this stems from the other PR we just merged.

**Comment by junlincc** [comment]
confirmed that now datatable is resizing proof!! Thank you @kgabryje and @maloun96 !
