### ISSUE TITLE
[explore] datapanel search should not case sensitive

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#12299]
#### Screenshots

![fnLVBHBoVP](https://user-images.githubusercontent.com/27990562/103723210-65610080-4f86-11eb-88e1-80e33b21a0bb.gif)

#### How to reproduce the bug

1. Go to explore view, search "SUM" in datapanel
2. found no match
3. search "sum", you will find some results

### Environment

latest master

cc @junlincc @zuzana-vej

**Comment by ktmud** [comment]
I'd recommend utilize [match-sorter](https://www.npmjs.com/package/match-sorter) for things like this.

E.g.

https://github.com/apache-superset/superset-ui/blob/a4ecdb3d5a7791e864703318d6da9154bb842762/plugins/plugin-chart-table/src/DataTable/DataTable.tsx#L120-L123

**Comment by junlincc** [comment]
> I'd recommend utilize [match-sorter](https://www.npmjs.com/package/match-sorter) for things like this.
> 
> E.g.
> 
> https://github.com/apache-superset/superset-ui/blob/a4ecdb3d5a7791e864703318d6da9154bb842762/plugins/plugin-chart-table/src/DataTable/DataTable.tsx#L120-L123

we have the metric section search not case sensitive actually...
agree they should be same, will change it real quick~

**Comment by graceguo-supercat** [comment]
> we have the metric section search not case sensitive actually...
> agree they should be the same, will change it real quick~

in my screenshot you will see i am searching metrics name, and it is case sensitive right now.

**Comment by junlincc** [comment]
resolved, closing. thanks @pkdotson 🙏
