### ISSUE TITLE
[dashboard] spinner is overlaying with dashboard header

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#12298]
### Actual results

![hWrewMA6DM](https://user-images.githubusercontent.com/27990562/103719947-119ee900-4f7f-11eb-9543-623144a9e0ea.gif)

#### How to reproduce the bug

1. Go to  dashboard with a lot of charts
2. when charts are loading, scroll to the bottom of dashboard
3. you will see spinner is overlaying with dashboard header.

### Environment

lastest master

### Additional context

@junlincc @geido Thanks for fixing spinner issue. The issue reported here is not new, and it's not caused by #12288. It's low priority, but i think we should fix it.

**Comment by geido** [comment]
Tackling this
