### ISSUE TITLE
[Explore] Time picker custom setting for timezone 

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#12302]
- In Advanced range type, user can type in time with free text (**this is great! l like this design and implementation!!**): 

![advanced](https://user-images.githubusercontent.com/27990562/103743405-f1881d80-4fb0-11eb-8431-9ae1bbfa62a0.gif)

- But in Custom range type, user have to set time by click on hour/minute/second, free text will be overwritten when user close calendar. 
![b8psB5uD5r](https://user-images.githubusercontent.com/27990562/103743964-c9e58500-4fb1-11eb-8110-53192a9ceb51.gif)

- I think the 3 columns for hour/minute/second is a little extra. 
- The settings for Advanced vs Custom should be consistent: one place allow user type free text, the other is not, with no obvious reason or hint from UI. When i type in time in Custom range type and then get removed , i thought it was a bug.

### Environment

latest mater

@junlincc @zhaoyongjie

**Comment by junlincc** [comment]
Thanks for the nice comment for Advanced! @graceguo-supercat 
much more users can do in the free text input, but we haven't had a chance to better document the new features yet.  
if you think below would be useful for your users, pls also help test them and give us feedback  🙏 @zuzana-vej  @etr2460 
<img width="1001" alt="Screen Shot 2021-01-06 at 6 44 36 AM" src="https://user-images.githubusercontent.com/67837651/103781065-b0146400-4fea-11eb-97a1-949470e2f38c.png">

**Comment by junlincc** [comment]
again, thanks for the valuable feedback, we will get this enhancement done by 1.0 release. 
The settings for Advanced vs Custom should be consistent 

@zhaoyongjie 🙏

**Comment by graceguo-supercat** [comment]
This specifications for the new Timepicker is great. I will share with airbnb users after our next release.

**Comment by zhaoyongjie** [comment]
Hi, @graceguo-supercat. There are some UX usage issues here.

- In the Custom Frame:
The new Datepicker(Antd Datepicker) use mouse `onBlur event` as shortcut to cancel value input. (so the Datepicker value cannot be saved in time)
If you need to confirm the change, you need to use the `enter key` or mouse click the `Ok button`. (submitted Datepicker value)

https://user-images.githubusercontent.com/2016594/103897402-777da300-512e-11eb-80a8-4c428b91f533.mp4

- For Advanced Frame vs Custom Frame consistent
`Custom Frame` is just a subset of the `Advanced Frame` representation range, Advanced Frame has more rich datetime-expression

**Comment by graceguo-supercat** [comment]
Thanks @zhaoyongjie I didn't realize `enter key` is the key :)

I have a few other things to clarify:
1. Midnight in Custom type: is it Midnight UTC time zone? or user's local time zone? Is it the last midnight or the next midnight in the future? Please make it clear:
<img width="591" alt="Screen Shot 2021-01-07 at 3 56 48 PM" src="https://user-images.githubusercontent.com/27990562/103958272-708c6b80-5101-11eb-8e6d-25353a6a94af.png">

**Comment by junlincc** [comment]
> is it Midnight UTC time zone?

Yes, it's UTC time zone, and we have plan to allow user to set time zone.

**Comment by junlincc** [comment]
> Advanced date type has many new operators, like `dateadd`, `datetrunc` etc, which we don't have before. We should offer a full list of feature descriptions for users. Otherwise for those non-tech background users, they don't know how to use it or how to find the secret.

Yes! I am well aware of the need of adding tooltip of advanced syntax description, as I'm one of the non-tech background users😅. We will get both projects started within a couple weeks. @graceguo-supercat

**Comment by ThanhTrung90** [comment]
> > is it Midnight UTC time zone?
> 
> Yes, it's UTC time zone, and we have plan to allow user to set time zone. it's a committed enhancement in roadmap @graceguo-supercat

@junlincc Can user set time zone in superset right now?
If yes, how can user do that?
