### ISSUE TITLE
[explore] datapanel search: remove search input do not trigger new search

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#12303]
#### How to reproduce the bug

1. Go to  explore view, 
2. type in some long text in the search input box, you will see matched metrics and columns,
3. remove a few words in the search input box, you should see more matched metrics and columns
4. but there is no new search action triggered.
5. Note: in my screenshot, some very long metrics name got truncated. **Please add tooltip to display full name.**

![QlDwE7pJ7S](https://user-images.githubusercontent.com/27990562/103745781-ee8f2c00-4fb4-11eb-82ea-f155a246d22a.gif)

### Environment

latest master

cc @junlincc @zuzana-vej

**Comment by junlincc** [comment]
thanks for testing our new feature extensively and keeping the quality bar high for Superset @graceguo-supercat 🙏
Two issues here 
1. Deleting text to trigger new search action - P1 
2. Display super long column name - Our current solution is to implement resizable data panel. tooltip will not be ideal for UI/UX, as it will be added to all columns names and metrics. We should get to resizable in a couple weeks. hope that's not a deal breaker for you.  @graceguo-supercat

**Comment by junlincc** [comment]
@pkdotson Please take this one(Deleting text to trigger new search action), along with https://github.com/apache/superset/issues/12299 and https://github.com/apache/superset/issues/12233 
you have the most knowledge in this area. 🙏 


pls let me know

**Comment by graceguo-supercat** [comment]
1. resizable is good improvement. when there is a lot of long text, user want to resize wider. when the current dataset is small, user may want to keep it narrower.
2. but even when user set datapanel narrow, user should still be able to read full name by tooltip.

**Comment by junlincc** [comment]
We don't have a solution for showing tooltip only on the ones w titles that can not be fully displayed. This project's on the Q1 roadmap. I am afraid that adding tooltip on all columns and metrics despite their length isn't an optimized solution visually. 
Column titles were truncated. Only a limited number of columns and metrics were displayed in the previous versions, which means this feature is already a huge step forward in terms of the information's visibility. 
I understand your request, and we are committed to improving. Pls allow some time for research/design/technical discussion to happen on this one. 

@mihir174 

Old:
<img width="570" alt="Screen Shot 2021-01-06 at 10 59 29 AM" src="https://user-images.githubusercontent.com/67837651/103809371-4443f280-500e-11eb-86c6-ede8b65124f8.png">

**Comment by graceguo-supercat** [comment]
Can I have another request? Could you make the search input box stay, not scroll with the very long Columns and Metrics section?
Even we set only show max 50 entries, it is still over a page height. Scroll back and forth to find search input box is a little inconvenient.  thanks @junlincc and @pkdotson

**Comment by junlincc** [comment]
> Could you make the search input box stay, not scroll with the very long Columns and Metrics section?


yup! that makes perfect sense. im opening a new issue, as the original request has been addressed by https://github.com/apache/superset/pull/12319, i'm closing this one for now

**Comment by junlincc** [comment]
Confirming this issue is resolved in latest master 01/09/2021 @ 11:20am (UTC)
all designed and new functions are working properly in Explore DataPanel
follow up discussion for [[Explore]allow user to search metrics and columns by properties in data panel](https://github.com/apache/superset/issues/12376) in Q1

cc @graceguo-supercat @ktmud @zuzana-vej @mistercrunch
