### ISSUE TITLE
.dockerignore file problem

### ISSUE THREAD

**Issue by JayGuAtGitHub** [apache/superset#12304]
In my production superset website, I found that it still call the webpack debug server like 

http://localhost:9000/sockjs-node/info?t=1609923238691

After long time debug, I found that, in my project folder, /superset/static, there were debug js files in that folder like:

/superset/static/assets/dashboard.ede529be.entry.js

When run the docker build command, all these files will be copy to the docker environment via the line :

COPY superset /app/superset

I checked .gitignore file and found it contains (which .dockerignore doesn't contain) the following lines:

superset/static/assets
superset/static/version_info.json

Should it be also included in .dockerignore file?

before fix:

url: /superset/dashboard/20

the end of the html:

--
  |  
  | <script src="/static/assets/vendors-major.ede529be.chunk.js"></script>
  |  
  | <script src="/static/assets/vendors-addSlice-crudViews-dashboard-explore-menu-preamble-profile-showSavedQuery-sqllab.ede529be.chunk.js"></script>
  |  
  | <script src="/static/assets/vendors-addSlice-crudViews-dashboard-explore-menu-preamble-profile-sqllab.ede529be.chunk.js"></script>
  |  
  | <script src="/static/assets/vendors-addSlice-crudViews-dashboard-explore-menu-profile-showSavedQuery-sqllab.ede529be.chunk.js"></script>
  |  
  | <script src="/static/assets/vendors-addSlice-crudViews-dashboard-explore-menu-profile-sqllab.ede529be.chunk.js"></script>
  |  
  | <script src="/static/assets/vendors-addSlice-crudViews-dashboard-explore-menu-sqllab.ede529be.chunk.js"></script>
  |  
  | <script src="/static/assets/menu.ede529be.entry.js"></script>
  |  
  | 
  |  
  |  
  |  
  |  
  | 
  |  
  | <script src="/static/assets/0.ede529be.chunk.js"></script>
  |  
  | <script src="/static/assets/1.ede529be.chunk.js"></script>
  |  
  | <script src="/static/assets/5.ede529be.chunk.js"></script>
  |  
  | <script src="/static/assets/vendors-addSlice-crudViews-dashboard-explore-profile-showSavedQuery-sqllab.ede529be.chunk.js"></script>
  |  
  | <script src="/static/assets/vendors-addSlice-crudViews-dashboard-explore-profile-sqllab.ede529be.chunk.js"></script>
  |  
  | <script src="/static/assets/vendors-addSlice-crudViews-dashboard-explore-sqllab.ede529be.chunk.js"></script>
  |  
  | <script src="/static/assets/7.ede529be.chunk.js"></script>
  |  
  | <script src="/static/assets/vendors-addSlice-crudViews-dashboard-explore.ede529be.chunk.js"></script>
  |  
  | <script src="/static/assets/vendors-crudViews-dashboard-explore-sqllab.ede529be.chunk.js"></script>
  |  
  | <script src="/static/assets/9.ede529be.chunk.js"></script>
  |  
  | <script src="/static/assets/10.ede529be.chunk.js"></script>
  |  
  | <script src="/static/assets/vendors-dashboard-explore.ede529be.chunk.js"></script>
  |  
  | <script src="/static/assets/vendors-dashboard-sqllab.ede529be.chunk.js"></script>
  |  
  | <script src="/static/assets/vendors-crudViews-dashboard.ede529be.chunk.js"></script>
  |  
  | <script src="/static/assets/dashboard.ede529be.entry.js"></script>
  |  
  | 

wrong request example:

![image](https://user-images.githubusercontent.com/9403854/103761353-804c7700-5051-11eb-8c23-dfdea9f15f9b.png)

after fix 

url: the same url

end of html:

--
  |  
  | <script src="/static/assets/vendors-major.8bbbbd6861e6fcf3ab0a.p.chunk.js"></script>
  |  
  | <script src="/static/assets/vendors-addSlice-menu-preamble-profile.8691d15f3774d396769f.p.chunk.js"></script>
  |  
  | <script src="/static/assets/menu.34a393af25687694f53f.p.entry.js"></script>
  |  
  | 
  |  
  |  
  |  
  |  
  | 
  |  
  | <script src="/static/assets/1.73836e34a18efb7519a2.p.chunk.js"></script>
  |  
  | <script src="/static/assets/dashboard.ad893fc5e808044d0535.p.entry.js"></script>
  |  
  |

**Comment by willbarrett** [comment]
@craig-rueda do you think this change should be made?

**Comment by nytai** [comment]
If you're running from port 9000 you're likely running the webpack debug server. You should not be running the debug server in production as it is only meant for debugging (hence the calls to debug files). Instead if you run `npm run build` before building the docker container the production asset bundles will be outputted to `/superset/static/assets`.

**Comment by craig-rueda** [comment]
Agree with @nytai . Can you try using the official image? (https://hub.docker.com/r/apache/incubator-superset)

**Comment by JayGuAtGitHub** [comment]
> Agree with @nytai . Can you try using the official image? (https://hub.docker.com/r/apache/incubator-superset)

I didn't try but I'm definitely sure the official image will be OK. For some reasons I have to clone the repo and add customize functions. That's why I found this issue.

**Comment by JayGuAtGitHub** [comment]
> If you're running from port 9000 you're likely running the webpack debug server. You should not be running the debug server in production as it is only meant for debugging (hence the calls to debug files). Instead if you run `npm run build` before building the docker container the production asset bundles will be outputted to `/superset/static/assets` and the flask web server will be serving them instead of the webpack dev server.

I'm running in the production envrionment (with port 8088). These steps can explain how this problem appear:

Run "docker build -t superset:latest ./" to build a local docker image

in the Dockerfile

> FROM node:10-jessie AS superset-node
>
>......
>
>RUN cd /app/superset-frontend \
>        && npm run ${BUILD_CMD} \
>        && rm -rf node_modules

this command try to build the production js bundle

>FROM python:${PY_VER} AS lean
>
>......
>
>COPY --from=superset-node /app/superset/static/assets /app/superset/static/assets

this command try to copy all production js bundle from "superset-node" to "docker environment"

> COPY superset /app/superset

this command try to copy all python code from "packaging host machine envrionment" to "docker environment", in this command, there are some debug js file in the path superset/static/assets (I didn't check why it appears, I think maybe it is generated by docker-compose up). In this situation, the debug js is packaged into producton docker environment. And the js paths were put in the end of the dashboard page html.

I think another reason which cause the problem is that I don't have a CI envrionment. This won't appear in that envrionment beacause CI envionment will never pull the debug js and will never send the files to production environment. Maybe not all project can have a standard workflow especially for those quick-online startup project. Maybe this promotion can help those people to avoid some wired bugs. ( I have to say if you don't master webpack and docker at the same time, it's really hard to find the problem. Maybe the only way it clone project again-change the code-package)
