### ISSUE TITLE
[explore] datapanel: order of content section

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#12316]
#### Screenshots
![Screen_Shot_2021-01-06_at_1_56_49_PM](https://user-images.githubusercontent.com/27990562/103826096-0bfedd00-502b-11eb-9a55-d1ce1b40f2b7.jpg)

- in datapanel, it shows COLUMNS before METRICS
- in dataset editor, COLUMNS tab is after METRICS

Can we show METRICS before COLUMNS in datapanel?

### Environment

latest master

cc @junlincc

**Comment by graceguo-supercat** [comment]
This change is small. But may i know why you choose to change the order in dataset editor, instead of datapanel?
In my opinion, dataset editor has been there for year(s). Users knows the order of each tab. For active users, they may check dataset everyday. While datapanel is something very new, probably no real users yet.
If you prefer to change an existed behavior, may i know what is the advantage? cc @junlincc @lilykuang

**Comment by junlincc** [comment]
> Can we show METRICS before COLUMNS in datapanel?

we are making the change on data panel, moving METRICS about COLUMNS, please checkout https://github.com/apache/superset/pull/12335

**Comment by graceguo-supercat** [comment]
oh sorry....i misunderstood "tab" in the PR title 😢. Thank you so much! @junlin and @lilykuang

**Comment by junlincc** [comment]
done, closing! thank you @lilykuang again for the quick fix!
