### ISSUE TITLE
[Explore]Rolling Function in charts should have the option of using calendar dates for periods

### ISSUE THREAD

**Issue by cooley-pe** [apache/superset#12314]
**Is your feature request related to a problem? Please describe.**
Rolling sums (and the like) don’t handle sparse dates in an intuitive way. For example if you have one data point per year for 10 years, but want a 365 day rolling sum (time grain: day, Periods: 10 is for illustration purposes, as a 365 day rolling sum would be Period: 10), it will count all 10 of those data points, even though they’re over the span of 10 years.
![Screen Shot 2021-01-05 at 3 34 30 PM](https://user-images.githubusercontent.com/64038793/103822517-25048f80-5025-11eb-84d0-f1da8b0d9886.png)
![Screen Shot 2021-01-05 at 3 33 17 PM](https://user-images.githubusercontent.com/64038793/103822521-27ff8000-5025-11eb-9e0b-820e29dbac51.png)

**Describe the solution you'd like**
There should be an option (or it should be defaulted) to use calendar dates for the rolling calculation regardless of whether they appear in the data set. [Pandas rolling() function supports](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.rolling.html) this by making the date the Index.

**Describe alternatives you've considered**
Make this the default and only functionality. I can't think of a time that the current behavior would be preferable.

**Comment by junlincc** [comment]
thanks for suggesting! 

@zhaoyongjie do we fell comfortable including this in 2021 q2?

**Comment by zhaoyongjie** [comment]
In my Q2-Q3 plan, @junlincc

**Comment by cooley-pe** [comment]
Hi, I just wanted to bump this and see if this is still something that might get worked on? Thank you!

**Comment by rusackas** [comment]
Hi @cooley-pe - it doesn't sound like this is on anyone's immediate roadmap. Pinging @yousoph in case she knows anyone that'll be taking a close look at Advanced Analytics anytime soon. Meanwhile, we're trying to get our Issues back to bug reports, so since this has gone stale, I'll close it and encourage you to open a Github Discussion in the "Ideas" category if you're still looking for someone to pursue it. Thanks!
