### ISSUE TITLE
[explore] Update UI control should not trigger new query

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#12317]
#### How to reproduce the bug

1. Go to explore view of time-series chart,
2. change time range.
3. from browser console you will see when you updated the time picker, new query is triggered.
4. but this trigger won't update chart, there is an overlay on top of chart.
5. user has to click on `run query` button on overlay to trigger another query.

![JlAT3bEDfI](https://user-images.githubusercontent.com/27990562/103832160-80894a00-5032-11eb-9860-e5d376b2290c.gif)

### Environment

latest master

cc @junlincc @zhaoyongjie

**Comment by junlincc** [comment]
related https://github.com/apache/superset/issues/12207

**Comment by graceguo-supercat** [comment]
oh thanks for the updated. i just realize it's not timepicker cause this issue. This is a serious issue. thanks @junlincc

**Comment by junlincc** [comment]
> oh thanks for the updated. i just realize it's not introduced by timepicker. This is a serious issue. thanks @junlincc

Yes, will definitely get it fixed by Wednesday.

**Comment by kgabryje** [comment]
@junlincc Got it 👍
