### ISSUE TITLE
docker superset cannot create admin account

### ISSUE THREAD

**Issue by joebling** [apache/superset#12321]
when i create admin account，it reports an error. i can open the login web，but canot login in。
![image](https://user-images.githubusercontent.com/18331158/103857572-bb9e8280-50f1-11eb-8d90-0b801003c300.png)
![image](https://user-images.githubusercontent.com/18331158/103857733-04563b80-50f2-11eb-9e32-65403475b4a2.png)
![image](https://user-images.githubusercontent.com/18331158/103857747-0b7d4980-50f2-11eb-93b3-c10a4bd3c1c1.png)

**Comment by zhaoyongjie** [comment]
@joebling 
- which docker image do you use?
- please follow this manual to start docker-compose instance for Superset

**Comment by joebling** [comment]
@zhaoyongjie 
1）0.38
2) 我参考这篇文章 https://www.cnblogs.com/lanliying/p/12586498.html, 因为公司内部云用不了docker-compose up， 而且也连不了外网。

**Comment by zhaoyongjie** [comment]
@joebling 
Please refer to the following URL, how to use this image
https://hub.docker.com/r/amancevice/superset

这篇文章是用下面这个镜像, 你直接原镜像地址, 看下如何使用.
https://hub.docker.com/r/amancevice/superset

**Comment by joebling** [comment]
@zhaoyongjie 
参考docker-compose 里的init文件解决的
