### ISSUE TITLE
[Explore]add Annotation layers dropdowns do not respond for click

### ISSUE THREAD

**Issue by adam-stasiak** [apache/superset#12328]
I cannot modify dropdown options for annotation layers (chart explore view)
### Expected results

Dropdowns can be open.
### Actual results

Dropdowns do not react on click.

#### Screenshots

https://user-images.githubusercontent.com/25153919/103898333-108fc800-50f5-11eb-92d5-2697cb2fd092.mov

#### How to reproduce the bug

1. Launch application with: CYPRESS_CONFIG=true docker-compose up
2. Go to chart ```Rise & Fall of Video Game Consoles```
3. Click on Add annotation layer

### Environment

(please complete the following information):

commit master f48284909dde84d13276bb40ddd91ec6935f10e5

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@adam-stasiak Thanks for reporting 
@agatapst let's fix this one, I don't think it's a regression from your last PR, but you now have the most context. 

thanks both! 🙏

**Comment by geido** [comment]
Fixed by #12330 @junlincc 

![Num-Births-Trend](https://user-images.githubusercontent.com/60598000/104046448-655c3d00-51e0-11eb-9dff-8068d2d41150.gif)

**Comment by geido** [comment]
There might be another issue though. It seems the Popover is closed on every change without giving the user the ability to apply the changes @junlincc

**Comment by junlincc** [comment]
> There might be another issue though. It seems the Popover is closed on every change without giving the user the ability to apply the changes @junlincc

right, that's also happening in the LONGITUDE & LATITUDE popover in deck.gl chart 😭

**Comment by junlincc** [comment]
original issue is resolved thanks @geido and @adam-stasiak !
