### ISSUE TITLE
[Explore]Set default filterbox value using SQL statement

### ISSUE THREAD

**Issue by stevensuting** [apache/superset#12324]
**Describe the solution you'd like**
Currently Superset allows us to set static default values to the filter box:
<img width="297" alt="Screenshot 2021-01-07 at 1 07 35 PM" src="https://user-images.githubusercontent.com/8875448/103864959-76765280-50e9-11eb-8b32-88224d511b97.png">

What I would like is for this value to be dynamic based on some condition set via SQL.
For example, we have a column called Team with values (David's Team, Jack's Team, Tim's Team)
Team is used on a Filter Box for a dashboard.
- When David logs in, the value on the filterbox should be David's Team
- When Jack logs in, the value on the filterbox should be Jack's Team

A sample SQL for this could be:
`SELECT team_name from table where manager_name = '{{current_username()}}'`

**Describe alternatives you've considered**
A potential unclean solution that uses url parameters, like
http://localhost:8088/superset/dashboard/1/?preselect_filters={"1": {"Team": "David's Team"}}
http://localhost:8088/superset/dashboard/1/?preselect_filters={"1": {"Team": "Jack's Team"}}

Using Ngnix+Lua to do a URL redirect when a particular user logs in

**Comment by suddjian** [comment]
New filter features are being implemented under Native Filters rather than filter box
