### ISSUE TITLE
Changing the "Table Timestamp Format" gives incorrect results.

### ISSUE THREAD

**Issue by qyra** [apache/superset#12339]
I created a Table chart with a time column

With the default Adaptative formatting it displays correctly:
A `2020-11-30T20:37:30.122883`
B `2020-11-30T20:37:17.179797`
C `2020-11-30T20:31:41.414866`

When I change Table Timestamp Format to `%Y-%m-%d %H-%M-%S` I would expect that the decimal portion of the seconds should be removed, but that the actual date should be identical. Instead the times shift by many hours.
A `2020-12-01 01:37:30`
B `2020-12-01 01:37:17`
C `2020-12-01 01:31:41`

All of these timestamps are off by ~5:00:00 so presumably there's some odd behaviour related to timezones.

### Environment
- superset version: `superset version`
Superset 0.38.0

- python version: `python --version`
Python 3.7.5

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by ktmud** [comment]
The timestamps are always displayed as UTC times. This is by design. There are many challenges related to synching timezones between Superset, the datasources, and the client. We would need to think about this problem more thoroughly and come up with a comprehensive plan if we want to address this.

**Comment by qyra** [comment]
It seems to me like they are not being displayed as UTC times. The query itself returns correct data and the CSV export is also correct. I am in the ET timezone so it would make sense that a 5 hour offset would come up if something was trying to convert times to a local timezone or back.

**Comment by wisonwang** [comment]
i see the issue too.  And  maybe i found the reason:
When create a chart with time grains, superset will use it's default db_engine grains(mysql, db2, clickhouse...), like clickhouse:
[https://github.com/apache/superset/blob/master/superset/db_engine_specs/clickhouse.py](https://github.com/apache/superset/blob/master/superset/db_engine_specs/clickhouse.py)

code: 

> class ClickHouseEngineSpec(BaseEngineSpec):  # pylint: disable=abstract-method
>     """Dialect for ClickHouse analytical DB."""
> 
>     engine = "clickhouse"
>     engine_name = "ClickHouse"
> 
>     time_secondary_columns = True
>     time_groupby_inline = True
> 
>     _time_grain_expressions = {
>         None: "{col}",
>         "PT1M": "toStartOfMinute(toDateTime({col}))",
>         "PT5M": "toDateTime(intDiv(toUInt32(toDateTime({col})), 300)*300)",
>         "PT10M": "toDateTime(intDiv(toUInt32(toDateTime({col})), 600)*600)",
>         "PT15M": "toDateTime(intDiv(toUInt32(toDateTime({col})), 900)*900)",
>         "PT0.5H": "toDateTime(intDiv(toUInt32(toDateTime({col})), 1800)*1800)",
>         "PT1H": "toStartOfHour(toDateTime({col}))",
>         "P1D": "toStartOfDay(toDateTime({col}))",
>         "P1W": "toMonday(toDateTime({col}))",
>         "P1M": "toStartOfMonth(toDateTime({col}))",
>         "P0.25Y": "toStartOfQuarter(toDateTime({col}))",
>         "P1Y": "toStartOfYear(toDateTime({col}))",
>     }

to fix this issue , you can change the code to support your  local time zone. or if you just need dt grains, you can just let zhe chart's time grains to null.

**Comment by ITCheng0712** [comment]
I tried to modify the code for clickhouse.py, but the page display did not change

**Comment by rusackas** [comment]
FYI @lauderbaugh

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
