### ISSUE TITLE
[Design Proposal]Capitalization guidelines for consistency

### ISSUE THREAD

**Issue by mihir174** [apache/superset#12343]
This design proposal aims to make text consistently capitalized across the product, to address issues like https://github.com/apache/superset/issues/12023

Here are the guidelines @steejay and I developed, based on design systems from Google, IBM and Atlassian. 

### Sentence case
Use sentence-case capitalization for everything in the UI (except these **). 

Sentence case is predominantly lowercase. Capitalize only the initial character of the first word, and other words that require capitalization, like:
- **Proper nouns.** Objects in the product _are not_ considered proper nouns e.g. dashboards, charts, saved queries etc. Proprietary feature names eg. SQL Lab, Preset Manager _are_ considered proper nouns
- **Acronyms** (e.g. CSS, HTML)
- When referring to **UI labels that are themselves capitalized** from sentence case (e.g. page titles - Dashboards page, Charts page, Saved queries page, etc.)
- User input that is reflected in the UI. E.g. a user-named a dashboard tab

**Sentence case vs. Title case:**
Title case: "A Dog Takes a Walk in Paris"
Sentence case: "A dog takes a walk in Paris"

**Why sentence case?**
- It’s generally accepted as the quickest to read
- It’s the easiest form to distinguish between common and proper nouns

### How to refer to UI elements
When writing about a UI element, use the same capitalization as used in the UI. 

For example, if an input field is labeled “Name” then you refer to this as the “Name input field”. Similarly, if a button has the label “Save” in it, then it is correct to refer to the “Save button”. 

Where a product page is titled “Settings”, you refer to this in writing as follows: 
“Edit your personal information on the Settings page”.

Often a product page will have the same title as the objects it contains. In this case, refer to the page as it appears in the UI, and the objects as common nouns:

- Upload a dashboard on the Dashboards page
- Go to Dashboards
- View dashboard
- View all dashboards
- Upload CSS templates on the CSS templates page
- Queries that you save will appear on the Saved queries page
- Create custom queries in SQL Lab then create dashboards

### **Exceptions to sentence case:
- Input labels, buttons and tabs are all caps

**Comment by mihir174** [comment]
fyi @mistercrunch @zuzana-vej @graceguo-supercat

**Comment by junlincc** [comment]
Awesome! Thank you both. @mihir174 @Steejay Kicking off the implementation following this guideline!

**Comment by ktmud** [comment]
Thanks for the detailed proposal and the reasoning! I believe Superset will greatly benefit from more guidelines like this. Maybe we could even develop our own design system!

Do you think it makes sense to add following exception to the proposal as well?

> In general, user inputs should not change cases.

**Comment by junlincc** [comment]
+1 

> Thanks for the detailed proposal and the reasoning! I believe Superset will greatly benefit from more guidelines like this. Maybe we could even develop our own design system!
> 
> Do you think it makes sense to add following exception to the proposal as well?
> 
> > In general, user inputs should not change cases.

+1. no more forcing upper case in the product..

**Comment by mihir174** [comment]
@ktmud yes - totally agree with user inputs appearing exactly as they were inputted

**Comment by mihir174** [comment]
Made some minor additions + clarifications @amitmiran137 @michael-s-molina @ktmud 

Added under **Sentence case**: 
"User input that is reflected in the UI. E.g. a user-named a dashboard tab"

Clarified in **Exceptions to sentence case**:
_Input_ labels, buttons and tabs

**Comment by michael-s-molina** [comment]
Guidelines added to `CONTRIBUTING.md`.

**Comment by rusackas** [comment]
Moved to [Design Guidelines](https://github.com/apache/superset/wiki/Design-Guidelines) page on the Wiki, so I'll call this issue Closed.
