### ISSUE TITLE
[Explore]filter sql editor generated WHERE clause is invalid

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12340]
Go to Explore
Select a simple text filter like City
Switch to Custom SQL and change the value
It will present an error because the generated WHERE clause is invalid
To fix the user has to enter the quotes and double quotes manually
<img width="1789" alt="Screen Shot 2021-01-07 at 4 08 31 PM" src="https://user-images.githubusercontent.com/67837651/103944048-f4d1f500-50e7-11eb-9920-0c57d5393dcc.png">
<img width="1784" alt="Screen Shot 2021-01-07 at 4 09 17 PM" src="https://user-images.githubusercontent.com/67837651/103944080-fbf90300-50e7-11eb-8528-6fde02cc6822.png">
<img width="1778" alt="Screen Shot 2021-01-07 at 4 10 18 PM" src="https://user-images.githubusercontent.com/67837651/103944099-02877a80-50e8-11eb-9b5d-d3e1d35d6b42.png">

cc @villebro @kgabryje 
FYI @zuzana-vej @eugeniamz

_Originally posted by @junlincc in https://github.com/apache/superset/issues/12293#issuecomment-756382758_

**Comment by villebro** [comment]
@junlincc I might be wrong, but I don't think this is a regression, I believe it's always been like this:
![image](https://user-images.githubusercontent.com/33317356/103994980-72f1d280-51a0-11eb-990a-8ba278a50cca.png)
![image](https://user-images.githubusercontent.com/33317356/103995007-7be2a400-51a0-11eb-844d-68b3172c4d3b.png)

**Comment by junlincc** [comment]
Confirming this issue is resolved in latest master 01/09/2021 @ 11:11am (UTC)
related issues mentioned in [#12293 ](https://github.com/apache/superset/issues/12293#issuecomment-756382758) will be addressed in the near future 

cc @graceguo-supercat @ktmud @zuzana-vej @mistercrunch
