### ISSUE TITLE
how do I find the correct docker image for a certain superset release eg. 0.38.0?

### ISSUE THREAD

**Issue by crsantini** [apache/superset#12342]
hi there

I'm having issues to correlate the docker images released at https://hub.docker.com/r/apache/incubator-superset/ and the release tags in GitHub https://github.com/apache/superset/releases. For example, how do I know which docker image relates to the latest 0.38.0? 

Thanks

**Comment by jakubgs** [comment]
Same question. I'm not seeing any release tags on [Docker Hub](https://hub.docker.com/r/apache/superset/tags).

![image](https://user-images.githubusercontent.com/2212681/113135360-53f46100-9222-11eb-8c4d-cc69b5e8eca5.png)

How am I supposed to run a stable deployment if I don't know which image is which release?

**Comment by jakubgs** [comment]
The Docker Compose suggests using `latest`:
https://github.com/apache/superset/blob/d54cc6d82aa86444dff0eaff072ee9e8e9ea915f/docker-compose-non-dev.yml#L17
But that sounds like a very bad idea if you want your deployment to be stable:

![image](https://user-images.githubusercontent.com/2212681/113135842-f14f9500-9222-11eb-9513-6eff464d75d7.png)

What does `latest` follow? `master`?

And the Dockerfile steps in `latest` don't seem to match the [Dockerfile in the repo](https://github.com/apache/superset/blob/master/Dockerfile):

https://hub.docker.com/layers/apache/superset/latest/images/sha256-51e1171cfddefc61d5b131d2cc1714b092ce814be8cc2fbc42654e6ab203f995?context=explore

**Comment by nytai** [comment]
We recently moved docker repos after graduation, hence the lack of project history in the https://hub.docker.com/r/apache/superset repo. 

Latest does currently refer to latest master build, which is not guaranteed to be stable. For now I'd suggest using specific version tags.`1.0.1` is the latest release and we're in the process of voting in `1.1.0`

**Comment by jakubgs** [comment]
How is `1.0.1` the latest release if the repo clearly shows `0.38.1` to be the latest release?

![image](https://user-images.githubusercontent.com/2212681/113395755-a22c7000-939a-11eb-8372-689cb72e0c63.png)

**Comment by jakubgs** [comment]
Oh, I see it, there is `1.0.1`:

![image](https://user-images.githubusercontent.com/2212681/113395960-fdf6f900-939a-11eb-8ee8-fb5acb685c2a.png)

But it's CLEARLY __not__ marked as `Latest release`. Maybe you should fix that @nytai ?

Just yesterday I deployed `0.38.1` because it was marked as latest. Fun.

**Comment by jakubgs** [comment]
@villebro maybe you could fix this?

**Comment by nytai** [comment]
0.38.1 was a patch release. Github automatically tags latest by tag date, so there’s nothing we can really do here.

**Comment by jakubgs** [comment]
I see, that does make sense. It is very annoying how GitHub doesn't let you update it manually. Thanks.

**Comment by amitmiran137** [comment]
this will be fixed soon as we release 1.1
