### ISSUE TITLE
[Home] +DASHBOARD and +CHART button don't work

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12346]
![ezgif-4-6d28580b6945](https://user-images.githubusercontent.com/67837651/103974778-5feeec00-5127-11eb-817d-25091a996f01.gif)

Expected behavior:
when users click +DASHBOARD, it takes users to empty dashboard edit mode
when users click +CHATR, it takes users to Create a new chart page

![ezgif-4-e468e13b54d2](https://user-images.githubusercontent.com/67837651/103975023-03400100-5128-11eb-8c34-4a4d061a8b71.gif)

**Comment by junlincc** [comment]
@maloun96 you probably are still in the woods of the time-series issue, but please give this one a quick fix, should be pretty easy?

**Comment by nytai** [comment]
hmm, I'm not seeing this on the latest master

**Comment by rusackas** [comment]
I'm seeing it in the latest master on my side :/

**Comment by zhaoyongjie** [comment]
I am seeing this bug on the latest master with firefox browser.

**Comment by nytai** [comment]
ah, I just restarted the dev-server and was able to repro. I must have had a really out of date build, looks like it was introduced in https://github.com/apache/superset/pull/12060
