### ISSUE TITLE
[chart] Echarts time-series line chart does not have x-axis control

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#12355]
- nvd3 line chart has x-axis control:

<img width="1156" alt="Screen Shot 2021-01-08 at 9 14 03 AM" src="https://user-images.githubusercontent.com/27990562/104044300-0243b980-5192-11eb-8605-79bb051f376b.png">

- echart version does not have x-axis control:
<img width="1210" alt="Screen Shot 2021-01-08 at 9 14 37 AM" src="https://user-images.githubusercontent.com/27990562/104044392-1d162e00-5192-11eb-9ac9-870d62ef6266.png">

Could we add a-axis format in eChart version?
@junlincc @villebro

**Comment by junlincc** [comment]
Echarts 5.0 automatically cut the ticks optimally based on the data time range and time grain setting, that's why we are seeing "inconsistent" format on the x-axis. 

![image (2)](https://user-images.githubusercontent.com/67837651/104050550-a4b46a80-519b-11eb-9458-6ff5006b3343.png)
![image](https://user-images.githubusercontent.com/67837651/104050564-a847f180-519b-11eb-9b42-11048b611d64.png)

We can certainly add a formatter in the Echarts, but the question is, do we want them to work exactly as nvd3 charts? 
Can we schedule a session with your users to understand the request better before diving in any implementation. @graceguo-supercat @zuzana-vej

**Comment by graceguo-supercat** [comment]
> do we want them to work exactly as nvd3 charts?

No. We only want to have a control to format x-axis, for example to show only month, or month/year etc. 
<img width="341" alt="Screen Shot 2021-01-08 at 11 02 31 AM" src="https://user-images.githubusercontent.com/27990562/104054016-235fd680-51a1-11eb-937f-50468270fc7a.png">
Right now is nothing user can choose.

**Comment by junlincc** [comment]
we probably can do something simple for now. we don't have much planed around Echarts in Q1. do you have a timeline? @graceguo-supercat

**Comment by graceguo-supercat** [comment]
Not urgent at all. At least we have nvd3 line chart to use. If this request can be added to the long term roadmap will be great, at least before fully deprecating nvd3 line chart. Thank you @junlincc

**Comment by zufolo441** [comment]
Hi all, 
I'm searching for echarts version of line chart in chart list, but I'm not able to find it. git version of today.

![Screenshot_20210111_125631](https://user-images.githubusercontent.com/45826835/104179662-843f1700-540c-11eb-98cf-52f410ad3546.png)

**Comment by eugeniamz** [comment]
@zufolo441, it is a time series chart 
![image](https://user-images.githubusercontent.com/58375897/104180659-7cb34a00-53db-11eb-89be-4b24755f25a0.png)

**Comment by eugeniamz** [comment]
@junlincc  yes, I think x-axis control and customization should be useful

**Comment by villebro** [comment]
I believe @maloun96 is currently working on adding x-axis formatting support as a byproduct of another feature, so this may be fixed sooner rather than later.

**Comment by zufolo441** [comment]
@eugeniamz 

thanks!

**Comment by junlincc** [comment]
confirmed this feature is available in TimeSeries Echarts in master now. thank you @maloun96 for the enhancement! 
@graceguo-supercat @zuzana-vej 

https://user-images.githubusercontent.com/67837651/105637127-ada26e80-5e20-11eb-85b7-7d8e431af996.mov
