### ISSUE TITLE
[Explore] slice standalone mode doesn't work correctly after refresh browser

### ISSUE THREAD

**Issue by duynguyenhoang** [apache/superset#12358]
When going to standalone slice, for example http://localhost:9000/superset/slice/23/?standalone=true
We wil be redirect to http://localhost:9000/superset/explore/?form_data=%7B%22slice_id%22%3A%2023%7D&standalone=true
In explore screen, the url will be replaced by ful form_data. Currenly it doesn't include `standalone=true` in final url which cause problem when we refresh the browser. It brings us to visualization design screen instead of standalone chart.

### Expected results

Standalone slice should be shown when we refresh page http://localhost:9000/superset/slice/23/?standalone=true

### Actual results

Visualization design screen is shown.

#### How to reproduce the bug

1. Go to standalone slice, example http://localhost:9000/superset/slice/23/?standalone=true
2. Waiting it to be rendered fully
3. Refresh browser (F5 or Ctrl R)
4. See the page is now visualization design page, not standalone slice

### Environment

(please complete the following information):

- superset version: master
- python version: 3.8
- node.js version: 123

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
Issue fixed by #12359
