### ISSUE TITLE
[Explore] Metric control displayed value is not consistent with current query

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#12367]
#### How to reproduce the bug

1. Go to Explore view
2. open **METRIC** control, choose a different option. (in my screenshot, you will see my old option is `aws...net_cost`, new option is `aws...service_usage`).
3. Not clicking SAVE, just click CLOSE, since I do not want to change Metric anymore
4. open **METRIC** control again, you will see `aws_service_usage` is the chosen metric. actually it should still be `aws_net_cost` since i didn't submit the change.

![yWgEshuIzb](https://user-images.githubusercontent.com/27990562/104074169-46e84880-51c4-11eb-82aa-60a6761fcbb4.gif)

### Environment

Latest master

cc @junlincc @zuzana-vej @ktmud

**Comment by junlincc** [comment]
this one is bad. 🤦🏾‍♀️ 

![ezgif-3-2b9dcd39cfc8](https://user-images.githubusercontent.com/67837651/104078669-32ac4780-51d4-11eb-8201-35b026d62cdd.gif)

**Comment by junlincc** [comment]
Confirming this issue is resolved in latest master 01/09/2021 @ 11:06am (UTC)

Will open up a PR to resolve issue - 'mouse away popover to clear undesired changed input'

@graceguo-supercat @ktmud @zuzana-vej  @mistercrunch
