### ISSUE TITLE
[Cosmetic][Explore] "Add to dashboard" dropdown should have a placeholder

### ISSUE THREAD

**Issue by ktmud** [apache/superset#12366]
## Screenshot

<img src="https://user-images.githubusercontent.com/335541/104073894-b578d680-51c3-11eb-81c3-d2714db4bef6.png" width="600">

## Description

Two small cosmetic issues:

1. This dropdown should have a placeholder. 
2. The clear button (x) should hide when there is no value selected.

## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

**Comment by mihir174** [comment]
![Base Layout](https://user-images.githubusercontent.com/64227069/104076101-d7755780-51c9-11eb-8c00-d040d6649cb3.png)

**Comment by junlincc** [comment]
confirmed issue has been resolved. Thank you @nikolagigic!
