### ISSUE TITLE
[Explore] adhoc filter SAVED METRIC display

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#12363]
1. dropdown list:
<img width="666" alt="Screen Shot 2021-01-08 at 1 28 13 PM" src="https://user-images.githubusercontent.com/27990562/104065998-83607800-51b5-11eb-8073-56762ebc1169.png">

2. ad-hoc filter:
<img width="323" alt="Screen Shot 2021-01-08 at 1 42 39 PM" src="https://user-images.githubusercontent.com/27990562/104067186-907e6680-51b7-11eb-8c7f-0853cdf773aa.png">

screenshot explains. We have many saved metric that have long name. cc @junlincc @zuzana-vej @ktmud

**Comment by junlincc** [comment]
i tested master this morning and it was working normally. when did you see it happen?  @graceguo-supercat

**Comment by graceguo-supercat** [comment]
> i tested master this morning and it was working normally. when did you see it happen? @graceguo-supercat

Could you try master branch sha `7c8ead8`

**Comment by junlincc** [comment]
Will do!

just wanna confirm it works properly on master 
<img width="576" alt="Screen Shot 2021-01-08 at 6 07 59 PM" src="https://user-images.githubusercontent.com/67837651/104080400-7f941c00-51dc-11eb-980a-5b35a0ce2bae.png">

**Comment by graceguo-supercat** [comment]
could you create some long metric name? short metrics also works for me:

<img width="354" alt="Screen Shot 2021-01-08 at 11 02 15 PM" src="https://user-images.githubusercontent.com/27990562/104085598-aadf3100-5205-11eb-9a44-5f2f658824f8.png">

**Comment by junlincc** [comment]
<img width="861" alt="Screen Shot 2021-01-09 at 1 46 21 AM" src="https://user-images.githubusercontent.com/67837651/104088528-804ca280-521c-11eb-9cd4-49115ee32610.png">
<img width="825" alt="Screen Shot 2021-01-09 at 1 46 15 AM" src="https://user-images.githubusercontent.com/67837651/104088530-82166600-521c-11eb-84b7-50eaa94a7510.png">

yup, it's another long title not able to display issue 😔 on it

**Comment by junlincc** [comment]
<img width="688" alt="Screen Shot 2021-01-09 at 2 10 43 AM" src="https://user-images.githubusercontent.com/67837651/104089001-09190d80-5220-11eb-9ebd-cc8382d763ed.png">

old behavior did allow longer metrics display but also had over flow issue
