### ISSUE TITLE
[Explore]LONGITUDE & LATITUDE popover close after select

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12388]
> There might be another issue though. It seems the Popover is closed on every change without giving the user the ability to apply the changes @junlincc

right, that's also happening in the LONGITUDE & LATITUDE popover in deck.gl chart 

_Originally posted by @junlincc in https://github.com/apache/superset/issues/12328#issuecomment-756911674_

**Comment by geido** [comment]
I am working on this
