### ISSUE TITLE
Add user role programmatically

### ISSUE THREAD

**Issue by javidov** [apache/superset#12414]
Hello all,
Is it possible to create a new user role based on permissions programmatically using FAB? I mean without having to use the UI.

It would be nice if we can create the role, then create a user and assign the created role

**Comment by amitmiran137** [comment]
Will be addressed in roles and users API feature development

**Comment by vishalpai** [comment]
Below is what seemed to work for me. Need validation from Superset team if this approach is correct.

For non dynamic permissions e.g., 1. Create a new role that has permissions that are a union of gamma and sql_lab 2. Adding all database access / all data source access / all query access
- Create a custom security manager
- Override the sync_role_definitions method
- In the sync_role_definitions method call the method of the base class
- Post that write your code to add your role and set permissions

For dynamic permissions e.g., give user access to a specific dataset. This permission has a string like datasource access on DATABASE_NAME][DATASET_ID](id:<SomeNumber>). Value of id is dynamic.
- Perform same steps as above i.e. create custom security manager, override the same method, call the method of the base class.
- Create the database and dataset via superset rest api. This will give you the dynamic id.
- Write your code to add your role and set permissions.

The part that needs validation from Superset team is calling the rest api from the sync_role_defintions method. 

@amitmiran137 could you please help?

**Comment by sahana-bs** [comment]
Has this been addressed yet? I also want to create and assign roles dynamically during login for users
