### ISSUE TITLE
Email Report for Dashboard has */10 * * * * but only sent once per hour

### ISSUE THREAD

**Issue by norus** [apache/superset#12419]
I have the "latest" tag running inside Docker and the email functionality is working well. I'm using the default hourly schedule which is picked up by Beat just fine:

```
    CELERYBEAT_SCHEDULE = {
        'email_reports.schedule_hourly': {
            'task': 'email_reports.schedule_hourly',
            'schedule': crontab(minute='1', hour='*'),
        },
    }
```

However, when creating this email report, I specified crontab to run every 10 minutes (see screenshot).

### Expected results

Expecting Celery worker to run the Email Report as per the crontab (*/10 * * * *) and not once per hour.

### Actual results

Email Report is only sent once per hour.
```
[2021-01-11 19:01:00,223: INFO/MainProcess] Received task: email_reports.send[685edddf-e689-46e3-af7e-f21966004d61]  ETA:[2021-01-11 19:00:00+00:00]
[2021-01-11 19:01:00,227: INFO/ForkPoolWorker-1] Task email_reports.schedule_hourly[2edcfa44-76cb-44e8-a2f0-a67707550fec] succeeded in 0.024685528995178174s: None
[2021-01-11 20:01:00,152: INFO/MainProcess] Received task: email_reports.schedule_hourly[5ccec57b-a8f7-451e-8016-28d8b6ceca70]
[2021-01-11 20:01:00,172: INFO/ForkPoolWorker-1] Task email_reports.schedule_hourly[5ccec57b-a8f7-451e-8016-28d8b6ceca70] succeeded in 0.018417919003695715s: None
```

#### Screenshots

![Screen Shot 2021-01-11 at 9 53 31 PM](https://user-images.githubusercontent.com/234848/104237110-dbb6a480-5457-11eb-93cd-395c22384533.png)

### Environment

- superset version: 0.38.0
- python version: 3.7.9
- node.js version: v12.20.1

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by graceguo-supercat** [comment]
I had similar problem, so i created this PR to fix it: https://github.com/apache/superset/pull/11414, which is after release 0.38. You can try it.

**Comment by lilykuang** [comment]
It seems like you're using the older, deprecated alerts & reports functionality. have you tried the new Alerts and Reports functionality: https://superset.apache.org/docs/installation/alerts-reports
