### ISSUE TITLE
[Chart] Metric columns are not in the correct order in bar chart

### ISSUE THREAD

**Issue by duynguyenhoang** [apache/superset#12416]
When design a bar chart, I encounter problem with the order of metric columns. They are not in the correct order.

### Expected results

Metric columns are preserved correct order in the request

### Actual results

Metrics columns is sorted by alphabet

#### Screenshots

Before 
![Current Problem](https://user-images.githubusercontent.com/7106179/104222466-eb90b180-5474-11eb-9a8f-6fc4a9751aba.png)

After
![Expectation](https://user-images.githubusercontent.com/7106179/104222520-006d4500-5475-11eb-87bb-3f3608072443.png)

#### How to reproduce the bug

1. Go to explore window and design any bar chart
2. Create list of metrics, name them as any order in alphabet (Example: z_metric, a_metric, k_metric)
3. Run the visualization
4. See the problem, now the columns are: a_metric, k_metric, z_metrics which are not in correct order.

### Environment

- superset version: master branch
- python version: 3.8

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@duynguyenhoang thanks so much, Duy! Every issue you open comes with a fix! Appreciate your help to improve Chart and Explore lately. If you are looking into making a more significant impact on Superset, please reach out to me on slack!

**Comment by rusackas** [comment]
I believe this was resolved by the linked PR, but the issue was never closed out! Closing it now, but let's open a new one if anything resurfaces. Thanks again @duynguyenhoang for the fix, and as @junlincc said, if you ever want to get involved again, reach out to either of us on [Slack](https://join.slack.com/t/apache-superset/shared_invite/zt-1jp6hjzrq-H0PlFtToyLWuPiJDuRWCNw)!
