### ISSUE TITLE
[Dashboard][Native Filter] Field select in forever loading state when Datasource is not selected

### ISSUE THREAD

**Issue by ktmud** [apache/superset#12422]
## Screenshot

In the new native filter

"FIELD" in forever loading state when "DATASOURCE" is not selected:

![image](https://user-images.githubusercontent.com/335541/104243353-498dac80-5415-11eb-8261-de792cac80f0.png)

BTW, we should probably rename "DATASOURCE" to "Dataset".

Some other potential TODOs:

1. Automatically select the main datasource in the dashboard
2. Limit the datasource select to only those used in the dashboard (debatable)

**Comment by junlincc** [comment]
man!! i'm still in Explore and you already started on the Dashboard!!! @ktmud  😈

**Comment by simcha90** [comment]
We can't load fields of dataset if there is no dataset selected, some other thoughts:
About 2. There is can be charts and filters from different datasets, why need limit to 1?

But may be it good to implement item 1., but how we can now what is main dataset of dahsboard?

![image](https://user-images.githubusercontent.com/56388545/115991754-90716d80-a5d2-11eb-93ed-f0505c74051c.png)

Like take here ☝️ first one?
