### ISSUE TITLE
[Explore]Blank deck.gl Multiple Layers chart control(Old issue)

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12427]
<img width="2045" alt="Screen Shot 2021-01-11 at 4 28 20 PM" src="https://user-images.githubusercontent.com/67837651/104254289-5d440d80-542b-11eb-81fc-8b1d414ed6ee.png">
<img width="2046" alt="Screen Shot 2021-01-11 at 4 36 36 PM" src="https://user-images.githubusercontent.com/67837651/104254296-603efe00-542b-11eb-9fc1-91fe64e18722.png">

while we tested again, we found blank page of deck.glMultiple Layers🤦🏾‍♀️. and confirmed that this has been an issue, not related to recent PR. 

This PR is good to go if codes look ok!

_Originally posted by @junlincc in https://github.com/apache/superset/issues/12326#issuecomment-758315693_

**Comment by rusackas** [comment]
Fix is open on https://github.com/apache-superset/superset-ui-plugins-deckgl/pull/24 - if that gets approved/merged, I'll release a new package, and bump it in Superset to resolve this issue.
