### ISSUE TITLE
[Explore]Change Dataset search can't get back to default list view after filtering 

### ISSUE THREAD

**Issue by Steejay** [apache/superset#12424]
Once a user inputs copy to filter the list of datasources, the list successfully filters dynamically but they can't get back to the default state that shows all datasets. 

### Expected results

Once the user deletes the input, the list should automatically show all datasets again. 

### Actual results

The user is stuck with their first filter input and can't redo their search/filter.

#### Screenshots

<img width="1288" alt="Screen Shot 2021-01-11 at 2 56 28 PM" src="https://user-images.githubusercontent.com/60786102/104247742-3252bd00-541d-11eb-9722-44170b583649.png">

#### How to reproduce the bug

1. Go to 'Explore'
2. Click on the more icon next to the dataset name
3. Filter the list by typing a dataset name
4. Stuck (try to see the full list again).

**Comment by junlincc** [comment]
it's resolved already by chore: Show datasets when search input is empty

@Steejay thanks for filing this issue, still need to speed up a bit to catch up with the changes in the repo 😉
