### ISSUE TITLE
[sql_lab]Ctrl + t shortcut in SQL Lab opens new tab in Chrome/PC

### ISSUE THREAD

**Issue by eschutho** [apache/superset#12429]
The tooltip for the new tab instructs users to use `Ctrl + t` for a new tab, but this doesn't work on a PC. On a PC `Ctrl + t` opens a new browser tab.
<img width="585" alt="_DEV__Superset" src="https://user-images.githubusercontent.com/5186919/104260080-94202080-5437-11eb-8344-ed014ca9b5c0.png">

Suggested solution: change the tooltip to suggest using `Ctrl +q` for PC users and update the keyboard shortcuts. 

### Expected results

The instructions in the tooltip should open a new SQL Lab tab.

### Actual results

Following the instructions on a PC opens a new Chrome tab.

#### How to reproduce the bug

1. Go to `/superset/sqllab`
2. Hover over the "+" icon next to the tabs for the instructions
3. Hit `Ctrl + t` in Chrome on a PC
4. A new Chrome tab opens

### Environment

- superset version: `1.0`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar. (Closed that issue for this one which is more accurate given the recent changes)

**Comment by eschutho** [comment]
I'm going to claim this ticket for someone on my team.

**Comment by hughhhh** [comment]
@lyndsiwilliams is working on this now

**Comment by rumbin** [comment]
Not sure if this is caused by the same effects, but Ctrl+X for cutting is also not working on a PC in Chrome or Firefox.
Should I open a new ticket for this or is it closely related?

**Comment by eschutho** [comment]
@yousoph ?

**Comment by yousoph** [comment]
Hi @rumbin , a new issue would be good for the ctrl+x shortcut. This particular one should be resolved already with this change: https://github.com/apache/superset/pull/12772 

Thanks!

**Comment by rusackas** [comment]
The acute issue in the original report was closed by https://github.com/apache/superset/issues/12772

If there are related key command bugs, let's open those under separate cover, and add any feature requests as Discussions. Thanks all!
