### ISSUE TITLE
[Dashboard] Pie chart not visible to public user in 0.38

### ISSUE THREAD

**Issue by parakh30** [apache/superset#12438]
We are not able to see word cloud and pie chart in the dashboard when opening with a public user and without login

### Expected results

Should see all the Charts in public user

![image](https://user-images.githubusercontent.com/34987552/104185623-38579680-543b-11eb-86c3-f8cbf0326bdd.png)

### Actual results

Pie chart and Word Cloud not showing for public user

![image](https://user-images.githubusercontent.com/34987552/104185903-a1d7a500-543b-11eb-8876-c9bebac3c555.png)

#### How to reproduce the bug

Make csrf as false in config.py
also the permission to public user are as follows.
![image](https://user-images.githubusercontent.com/34987552/104186628-afd9f580-543c-11eb-93c3-16e144b41b28.png)

1. Go to Sample dashboard
2. Try opening in a browser without login
3. See error

### Environment

(please complete the following information):

Docker deployment
- superset version: `0.38.0`
- python version: `Python 3.8.6`
- node.js version: no node version

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [y ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [y ] I have reproduced the issue with at least the latest released version of superset.
- [ y] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Getting below error. Attached full log.

/superset/lib/python3.7/site-packages/flask_caching/__init__.py:192: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  "Flask-Caching: CACHE_TYPE is set to null, "
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:werkzeug: * Running on http://<ip>:<port>/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
INFO:superset.utils.logging_configurator:logging was configured successfully
/superset/lib/python3.7/site-packages/flask_caching/__init__.py:192: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  "Flask-Caching: CACHE_TYPE is set to null, "
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 264-265-859
DEBUG:superset.stats_logger:[stats_logger] (incr) log
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:15] "POST /superset/log/?explode=events&dashboard_id=12 HTTP/1.0" 302 -
DEBUG:superset.models.core:Database.get_sqla_engine(). Masked URL: sqlite:////root/.superset/superset.db
DEBUG:superset.models.core:Database.get_sqla_engine(). Masked URL: sqlite:////root/.superset/superset.db
DEBUG:superset.stats_logger:[stats_logger] (incr) dashboard
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:16] "GET /superset/dashboard/births/ HTTP/1.0" 200 -
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:16] "GET /login/?next=https%3A%2F%2Fcloudinsights-dev.ad.infosys.com%2Fsuperset%2Flog%2F%3Fexplode%3Devents%26dashboard_id%3D12 HTTP/1.0" 200 -
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:16] "GET /static/appbuilder/css/flags/flags16.css HTTP/1.0" 200 -
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:16] "GET /static/appbuilder/css/font-awesome.min.css HTTP/1.0" 200 -
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:16] "GET /static/assets/theme.f98be93b3b065d5e1cd8.entry.js HTTP/1.0" 200 -
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:16] "GET /static/assets/dashboard.373675593bb033daf70f.entry.css HTTP/1.0" 200 -
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:16] "GET /static/assets/theme.f98be93b3b065d5e1cd8.entry.css HTTP/1.0" 200 -
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:17] "GET /static/assets/900c70fc8df8f1cf5585.chunk.js HTTP/1.0" 200 -
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:23] "GET /static/assets/68216b70fb99294f28b7.chunk.js HTTP/1.0" 200 -
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:24] "GET /static/assets/menu.910d625aa4f006c11f8a.entry.js HTTP/1.0" 200 -
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:25] "GET /static/assets/add329496eaa4681a903.chunk.js HTTP/1.0" 200 -
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:25] "GET /static/assets/images/superset-logo-horiz.png HTTP/1.0" 200 -
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:25] "GET /static/assets/dashboard.373675593bb033daf70f.entry.js HTTP/1.0" 200 -
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:27] "GET /static/assets/images/icons/triangle_down.svg HTTP/1.0" 200 -
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:27] "GET /static/appbuilder/img/flags/flags16.png HTTP/1.0" 200 -
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:27] "GET /static/appbuilder/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.0" 200 -
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:27] "GET /csstemplateasyncmodelview/api/read HTTP/1.0" 200 -
DEBUG:superset.stats_logger:[stats_logger] (incr) log
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:29] "POST /superset/log/?explode=events&dashboard_id=12 HTTP/1.0" 302 -
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:29] "GET /login/?next=https%3A%2F%2Fcloudinsights-dev.ad.infosys.com%2Fsuperset%2Flog%2F%3Fexplode%3Devents%26dashboard_id%3D12 HTTP/1.0" 200 -
DEBUG:superset.stats_logger:[stats_logger] (incr) data
DEBUG:superset.stats_logger:[stats_logger] (incr) explore_json
DEBUG:superset.stats_logger:[stats_logger] (incr) data
DEBUG:superset.stats_logger:[stats_logger] (incr) data
DEBUG:superset.stats_logger:[stats_logger] (incr) explore_json
DEBUG:superset.stats_logger:[stats_logger] (incr) explore_json
**INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:37] "POST /api/v1/chart/data?dashboard_id=12 HTTP/1.0" 401 -**
DEBUG:superset.stats_logger:[stats_logger] (incr) explore_json
DEBUG:superset.stats_logger:[stats_logger] (incr) explore_json
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:37] "POST /api/v1/chart/data?dashboard_id=12 HTTP/1.0" 401 -
DEBUG:superset.stats_logger:[stats_logger] (incr) explore_json
DEBUG:superset.stats_logger:[stats_logger] (incr) explore_json
DEBUG:parsedatetime:eval now with context - False, False
DEBUG:parsedatetime:eval - with context - False, False
INFO:superset.viz:Cache key: c6a3f7148ccae936f72b8826c8eb0502
DEBUG:parsedatetime:eval now with context - False, False
DEBUG:parsedatetime:eval - with context - False, False
INFO:superset.viz:Cache key: 0070a845c57f54db0ba050dc9b0d8645
DEBUG:parsedatetime:eval now with context - False, False
DEBUG:parsedatetime:eval now with context - False, False
DEBUG:parsedatetime:eval - with context - False, False
DEBUG:parsedatetime:eval - with context - False, False
DEBUG:superset.models.core:Database.get_sqla_engine(). Masked URL: sqlite:////root/.superset/superset.db
INFO:superset.viz:Cache key: 42ad51739e718ad28416cb4f9e7ae0c2
INFO:superset.viz:Cache key: 677d47d9dd48abd361a0d7ce7d5b98a2
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:37] "POST /api/v1/chart/data?dashboard_id=12 HTTP/1.0" 401 -
INFO:superset.connectors.sqla.models:SELECT DATE(ds) AS __timestamp, SUM(num) AS sum__num
FROM birth_names
WHERE ds >= '1921-01-11 00:00:00.000000' AND ds <= '2021-01-11 13:20:37.000000' GROUP BY DATE(ds) ORDER BY sum__num DESC
 LIMIT 50000 OFFSET 0
DEBUG:parsedatetime:eval now with context - False, False
DEBUG:superset.models.core:Database.get_sqla_engine(). Masked URL: sqlite:////root/.superset/superset.db
DEBUG:parsedatetime:eval - with context - False, False
INFO:superset.connectors.sqla.models:SELECT name AS name, DATE(ds) AS __timestamp, sum(num) AS "Births"
FROM birth_names JOIN (SELECT name AS name__, sum(num) AS mme_inner__
FROM birth_names
WHERE ds >= '1921-01-11 00:00:00.000000' AND ds <= '2021-01-11 13:20:37.000000' GROUP BY name ORDER BY mme_inner__ DESC
 LIMIT 25 OFFSET 0) AS anon_1 ON name = name__
WHERE ds >= '1921-01-11 00:00:00.000000' AND ds <= '2021-01-11 13:20:37.000000' GROUP BY name, DATE(ds) ORDER BY "Births" DESC
 LIMIT 50000 OFFSET 0
INFO:superset.viz:Cache key: 876688f0d504ec21420fee83e5974099
DEBUG:superset.models.core:Database.get_sqla_engine(). Masked URL: sqlite:////root/.superset/superset.db
DEBUG:parsedatetime:eval now with context - False, False
INFO:superset.connectors.sqla.models:SELECT state AS state, sum(sum_boys) AS "Boys", sum(sum_girls) AS "Girls"
FROM birth_names
WHERE ds >= '1921-01-11 00:00:00.000000' AND ds <= '2021-01-11 13:20:37.000000' AND state NOT IN ('other') GROUP BY state ORDER BY "Boys" DESC
 LIMIT 50000 OFFSET 0
DEBUG:superset.models.core:Database.get_sqla_engine(). Masked URL: sqlite:////root/.superset/superset.db
INFO:superset.connectors.sqla.models:SELECT name AS name, sum(num) AS "Births", SUM(num) AS sum__num
FROM birth_names
WHERE ds >= '1921-01-11 00:00:00.000000' AND ds <= '2021-01-11 13:20:37.000000' AND gender = 'girl' GROUP BY name ORDER BY sum__num DESC
 LIMIT 50 OFFSET 0
DEBUG:superset.models.core:Database.get_sqla_engine(). Masked URL: sqlite:////root/.superset/superset.db
INFO:superset.connectors.sqla.models:SELECT name AS name, DATE(ds) AS __timestamp, sum(num) AS "Births"
FROM birth_names JOIN (SELECT name AS name__, sum(num) AS mme_inner__
FROM birth_names
WHERE gender = 'girl' AND ds >= '1921-01-11 00:00:00.000000' AND ds <= '2021-01-11 13:20:37.000000' GROUP BY name ORDER BY mme_inner__ DESC
 LIMIT 10 OFFSET 0) AS anon_1 ON name = name__
WHERE ds >= '1921-01-11 00:00:00.000000' AND ds <= '2021-01-11 13:20:37.000000' AND gender = 'girl' GROUP BY name, DATE(ds) ORDER BY "Births" DESC
 LIMIT 50000 OFFSET 0
DEBUG:parsedatetime:eval - with context - False, False
INFO:superset.viz:Cache key: 8337ab4f5a0db3260ae148f04c50da26
DEBUG:parsedatetime:eval now with context - False, False
DEBUG:parsedatetime:eval - with context - False, False
INFO:superset.viz:Cache key: 1df39dc9d400aead5a187cb52918c537
DEBUG:superset.models.core:Database.get_sqla_engine(). Masked URL: sqlite:////root/.superset/superset.db
DEBUG:superset.models.core:Database.get_sqla_engine(). Masked URL: sqlite:////root/.superset/superset.db
INFO:superset.connectors.sqla.models:SELECT name AS name, DATE(ds) AS __timestamp, sum(num) AS "Births"
FROM birth_names JOIN (SELECT name AS name__, sum(num) AS mme_inner__
FROM birth_names
WHERE gender = 'boy' AND ds >= '1921-01-11 00:00:00.000000' AND ds <= '2021-01-11 13:20:37.000000' GROUP BY name ORDER BY mme_inner__ DESC
 LIMIT 10 OFFSET 0) AS anon_1 ON name = name__
WHERE ds >= '1921-01-11 00:00:00.000000' AND ds <= '2021-01-11 13:20:37.000000' AND gender = 'boy' GROUP BY name, DATE(ds) ORDER BY "Births" DESC
 LIMIT 50000 OFFSET 0
INFO:superset.connectors.sqla.models:SELECT name AS name, sum(num) AS "Births"
FROM birth_names
WHERE ds >= '1921-01-11 00:00:00.000000' AND ds <= '2021-01-11 13:20:37.000000' AND gender = 'boy' GROUP BY name ORDER BY "Births" DESC
 LIMIT 50 OFFSET 0
DEBUG:superset.stats_logger:[stats_logger] (incr) loaded_from_source
DEBUG:superset.stats_logger:[stats_logger] (incr) loaded_from_source_without_force
DEBUG:superset.stats_logger:[stats_logger] (incr) set_cache_key
DEBUG:superset.stats_logger:[stats_logger] (incr) loaded_from_source
DEBUG:superset.stats_logger:[stats_logger] (incr) loaded_from_source_without_force
DEBUG:superset.stats_logger:[stats_logger] (incr) set_cache_key
DEBUG:superset.stats_logger:[stats_logger] (incr) loaded_from_source
DEBUG:superset.stats_logger:[stats_logger] (incr) loaded_from_source_without_force
DEBUG:superset.stats_logger:[stats_logger] (incr) set_cache_key
DEBUG:superset.stats_logger:[stats_logger] (incr) loaded_from_source
DEBUG:superset.stats_logger:[stats_logger] (incr) loaded_from_source_without_force
DEBUG:superset.stats_logger:[stats_logger] (incr) set_cache_key
DEBUG:superset.stats_logger:[stats_logger] (incr) loaded_from_source
DEBUG:superset.stats_logger:[stats_logger] (incr) loaded_from_source_without_force
DEBUG:superset.stats_logger:[stats_logger] (incr) set_cache_key
DEBUG:superset.stats_logger:[stats_logger] (incr) loaded_from_source
DEBUG:superset.stats_logger:[stats_logger] (incr) loaded_from_source_without_force
DEBUG:superset.stats_logger:[stats_logger] (incr) set_cache_key
DEBUG:superset.stats_logger:[stats_logger] (incr) loaded_from_source
DEBUG:superset.stats_logger:[stats_logger] (incr) loaded_from_source_without_force
DEBUG:superset.stats_logger:[stats_logger] (incr) set_cache_key
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:37] "POST /superset/explore_json/?form_data=%7B%22slice_id%22%3A150%7D&dashboard_id=12 HTTP/1.0" 200 -
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:37] "POST /superset/explore_json/?form_data=%7B%22slice_id%22%3A152%7D&dashboard_id=12 HTTP/1.0" 200 -
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:37] "POST /superset/explore_json/?form_data=%7B%22slice_id%22%3A146%7D&dashboard_id=12 HTTP/1.0" 200 -
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:37] "POST /superset/explore_json/?form_data=%7B%22slice_id%22%3A155%7D&dashboard_id=12 HTTP/1.0" 200 -
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:37] "POST /superset/explore_json/?form_data=%7B%22slice_id%22%3A148%7D&dashboard_id=12 HTTP/1.0" 200 -
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:37] "POST /superset/explore_json/?form_data=%7B%22slice_id%22%3A149%7D&dashboard_id=12 HTTP/1.0" 200 -
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:38] "POST /superset/explore_json/?form_data=%7B%22slice_id%22%3A154%7D&dashboard_id=12 HTTP/1.0" 200 -
DEBUG:superset.stats_logger:[stats_logger] (incr) log
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:40] "POST /superset/log/?explode=events&dashboard_id=12 HTTP/1.0" 302 -
INFO:werkzeug:<ip> - - [11/Jan/2021 13:20:40] "GET /login/?next=https%3A%2F%2Fcloudinsights-dev.ad.infosys.com%2Fsuperset%2Flog%2F%3Fexplode%3Devents%26dashboard_id%3D12 HTTP/1.0" 200 -
DEBUG:superset.stats_logger:[stats_logger] (incr) log
INFO:werkzeug:<ip> - - [11/Jan/2021 13:21:01] "POST /superset/log/?explode=events&dashboard_id=12 HTTP/1.0" 302 -
INFO:werkzeug:<ip> - - [11/Jan/2021 13:21:02] "GET /login/?next=https%3A%2F%2Fcloudinsights-dev.ad.infosys.com%2Fsuperset%2Flog%2F%3Fexplode%3Devents%26dashboard_id%3D12 HTTP/1.0" 200 -
DEBUG:superset.stats_logger:[stats_logger] (incr) log
INFO:werkzeug:<ip> - - [11/Jan/2021 13:21:06] "POST /superset/log/?explode=events&dashboard_id=12 HTTP/1.0" 302 -
INFO:werkzeug:<ip> - - [11/Jan/2021 13:21:07] "GET /login/?next=https%3A%2F%2Fcloudinsights-dev.ad.infosys.com%2Fsuperset%2Flog%2F%3Fexplode%3Devents%26dashboard_id%3D12 HTTP/1.0" 200 -

**Comment by duynguyenhoang** [comment]
Some of charts are using new Api endpoint `/api/v1/chart/data` to fetch data, explicitly cloud and pie chart  in this case.
To allow user to access this new endpoint, you have to add new permission `can read on Chart` to Public role

Hope it helps.

**Comment by dpgaspar** [comment]
on 0.38 should be `can list on SliceModelView`

**Comment by duynguyenhoang** [comment]
My bad, I checked master.

**Comment by parakh30** [comment]
Thank you guys,
can list on SliceModelView, this worked.
