### ISSUE TITLE
[sql_lab]Add back description column to saved queries

### ISSUE THREAD

**Issue by eschutho** [apache/superset#12431]
**Is your feature request related to a problem? Please describe.**
The description column was removed from the saved queries. We would like to add it back. 
Styling TBD

**Describe the solution you'd like**
Show the description of the saved query if it exists on the saved queries page.

**Describe alternatives you've considered**
Not showing the description, but it seems helpful.

**Additional context**
<img width="1779" alt="Banners_and_Alerts_and__DEV__Superset" src="https://user-images.githubusercontent.com/5186919/104261470-77d1b300-543a-11eb-8b91-0f0f13ff29be.png">

**Comment by eschutho** [comment]
@S-YOU can you help with designs? Thanks!

**Comment by Steejay** [comment]
@eschutho @yousoph yes! ill make a design ticket for this and coordinate w Sophie

**Comment by yousoph** [comment]
Let's add the column as the second column from the left (right after name) 

@khallon would love to be pinged when a PR is ready to take a look and give potential design feedback/tweaks :) Thanks!

**Comment by rusackas** [comment]
Anyone still planning to go after this, or should we close it as stale?

**Comment by imancrsrk** [comment]
@rusackas  I've never contributed to OSS. I would like to take a stab at this one if nobody is actively working on it.

**Comment by rusackas** [comment]
@imancrsrk go for it! In your eventual PR description, just add "Fixes #12431" to auto-close this issue upon merge. :)

**Comment by surapuramakhil** [comment]
@rusackas I would like to solve this. Can you assign this to me?

If possible can you share designs for this if they exist, I am assuming A new column with name "description" needs to be added between column "Name" and "Database"

**Comment by imancrsrk** [comment]
@rusackas I've raised PR - https://github.com/apache/superset/pull/28349. I see that 2 checks have passed but another 18 are waiting to be reported, hope this is ok. Hope to get a review soon! 

Thanks :-)

**Comment by rusackas** [comment]
Looks like the PR is super close... I just had a question about he renaming of the Name filter to Search, since it introduces an inconsistency between list views that may or may not be warranted.

**Comment by imancrsrk** [comment]
> Looks like the PR is super close... I just had a question about he renaming of the Name filter to Search, since it introduces an inconsistency between list views that may or may not be warranted.

I replied back. The search filter is already searching all text columns, name, description, etc. so @nytai suggested that we make the filter name more general, `search`

**Comment by imancrsrk** [comment]
@rusackas I've added the tooltip description. 
https://github.com/apache/superset/pull/28349#discussion_r1591651467

**Comment by imancrsrk** [comment]
@rusackas I had sent out a change that aligns the tooltip better. Hope you can take a look at it today and let me know if anything else is needed :-)
