### ISSUE TITLE
DOCUMENTATION_ICON and DOCUMENTATION_TEXT not supported

### ISSUE THREAD

**Issue by Asturias-sam** [apache/superset#12439]
### Expected results

When user sets the  DOCUMENTATION_ICON and DOCUMENTATION_TEXT it should be visible on top of the page 

### Actual results

DOCUMENTATION_URL is working fine, but not able to set DOCUMENTATION_ICON and DOCUMENTATION_TEXT, i guess this code needs to be fixed https://github.com/apache/superset/blob/6df822438121b02bdcb26108f41df0ad290703a4/superset-frontend/src/components/Menu/Menu.tsx#L247

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
You're right... I didn't even realize this was there! This seems like a bit of a vestigial feature. If it hasn't worked for a long time, and nobody is barking about it, I'm wondering if we should remove it or fix it.

CC @yousoph @kasiazjc @jess-dillard for context, and CC @betodealmeida since they wrote the feature in the first place and may have feelings on the fix vs remove question.

**Comment by rusackas** [comment]
Unless someone feels otherwise, I think we should remove this in 5.0. Closing this issue as stale, but adding it to that project board.

**Comment by qleroy** [comment]
Working fine for me ! @rusackas 
And I like the feature,
<img width="334" alt="Screenshot 2024-02-15 at 06 29 34" src="https://github.com/apache/superset/assets/9881262/2b6606ba-6d14-4dcc-9c31-420d57c29141">

`BUG_REPORT_ICON` and `DOCUMENTATION_ICON` are expected to be class icon.
In my case I use icons imported from my design system.

Excerpt of `superset_config_docker.py`:
```bash
# Send user to a link where they can read more about Superset
DOCUMENTATION_URL = "https://numerique-gouv.github.io/chartsgouv/blog/"
DOCUMENTATION_TEXT = "Documentation ChartsGouv"
DOCUMENTATION_ICON = "fr-icon-question-answer-fill"  # Recommended size: 16x16
 
 # Send user to a link where they can report bugs
BUG_REPORT_URL = "https://github.com/numerique-gouv/chartsgouv/"
BUG_REPORT_TEXT = "Signaler un bug"
BUG_REPORT_ICON = "fr-icon-github-fill"  # Recommended size: 16x16
```

**Comment by rusackas** [comment]
Thanks @qleroy! I'll take it off the chopping block, then : )
