### ISSUE TITLE
[data] Filter dropdowns are not in the line with filter name

### ISSUE THREAD

**Issue by adam-stasiak** [apache/superset#12442]
## Screenshot

![image](https://user-images.githubusercontent.com/25153919/104311694-dac45800-54d5-11eb-8c9f-aa9844771ae1.png)

## Description
Use 0f731f27e4b41ca63689094ad57c94cc5aa75b89 commit
Go to Data> Databases

You can see that Expose in SQL Lab is not straight with dropdown. It should be in the same line.

**Comment by rusackas** [comment]
These use a completely different UI component now, so I think we can call this one case closed ;)
