### ISSUE TITLE
[explore] Chart embed code modal glitch

### ISSUE THREAD

**Issue by adam-stasiak** [apache/superset#12445]
When I change size of code block then I can make this bigger than modal

### Expected results

Modal should react to code size change.

### Actual results

Code is outside the modal

#### Screenshots

https://user-images.githubusercontent.com/25153919/104322949-d607a000-54e5-11eb-9fb1-c1b27bea1459.mov

#### How to reproduce the bug

1. Go to chart
2. Click on embed code
3. adjust size

### Environment
commit 90915db60d0f330fd28a5fc2b7a6676944c4dbb5
docker

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Looks like the PR that closed this wasn't linked properly. Closing!
