### ISSUE TITLE
[explore] Scrolling not working on Chart Data section with Safari

### ISSUE THREAD

**Issue by adam-stasiak** [apache/superset#12444]
When I am using Safari then I am not albe to scroll this area.
### Expected results

it should be scrollable.
### Actual results

it is not scrollable.
#### Screenshots

https://user-images.githubusercontent.com/25153919/104316037-27129680-54dc-11eb-9ebf-f19ff21cb853.mov

#### How to reproduce the bug

1. Go to any chart
2. click on Data to expand
3. scroll data area

### Environment

docker build
commit 0f731f27e4b41ca63689094ad57c94cc5aa75b89
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x ] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sergereit** [comment]
Same with Chrome

**Comment by maahivikas** [comment]
Both in chrome and safari , once it goes on chart creation page , it's not scrolling down .
I am using it on kubernetes , from official documentation : https://superset.apache.org/docs/installation/running-on-kubernetes/.

**Comment by cnbhomia** [comment]
I'm facing the issue in Chrome, Safari and Firefox. 
Is there an timeline on the resolution?

**Comment by rusackas** [comment]
Unable to repro in current Superset. I think we're all good here!
