### ISSUE TITLE
[welcome] Share Success toast for sql query is displayed too right

### ISSUE THREAD

**Issue by adam-stasiak** [apache/superset#12441]
## Screenshot

Go to /superset/welcome
Tap on sql query share option

https://user-images.githubusercontent.com/25153919/104311125-0e52b280-54d5-11eb-94c6-90ad7223cf83.mov

## Description

You can see that success toast is displayed too right and not fully visible

**Comment by rusackas** [comment]
I believe this is no longer an issue, but if you ever see it again, let's re-open!
