### ISSUE TITLE
[dashboard] When adding two native filters (first ok,second one partially filled) I lost the first one

### ISSUE THREAD

**Issue by adam-stasiak** [apache/superset#12459]
When I add two new filters and:
* first is correctly filled
* second is partially filled
And I click on Save on first filter -> I do not get information that this SAVE will not keep my filter when I quit this modal.

### Expected results

We should indicate that progress will be lost and:
- force user to finish or remove remaining filters before exit
- discard not valid filter entries 
- keep them as draft not applicable for usage

@junlincc I think we should consider options for this.

### Actual results

I do not get information that this SAVE will not keep my filter when I quit this modal.

#### Screenshots

https://user-images.githubusercontent.com/25153919/102830600-f31ae880-43e9-11eb-9583-93dc47f5909d.mov

#### How to reproduce the bug
Enable Native filters
Go to filter adding on dashboard
I add two new filters and:
* first is correctly filled
* second is partially filled
click on Save on first filter 
### Environment
docker
sha 90915db60d0f330fd28a5fc2b7a6676944c4dbb5

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by agatapst** [comment]
Yeah, some info should be displayed here. I will take a look.
