### ISSUE TITLE
[dashboard] Long native filter name glitches Filter Configuration modal

### ISSUE THREAD

**Issue by adam-stasiak** [apache/superset#12458]
## Screenshot

![image](https://user-images.githubusercontent.com/25153919/104340240-c776b400-54f8-11eb-8b16-4150a537bfad.png)

## Description

When name is too long then right side of modal glitches. I guess we should prevent this behavior. My suggestion is to use "..." on filter name where it is too long or split this into lines.

**Comment by agatapst** [comment]
Good catch, I will take care of it soon.
