### ISSUE TITLE
[dashboard]Native filter FIELD loops when dataset in usewas removed

### ISSUE THREAD

**Issue by adam-stasiak** [apache/superset#12457]
You can see on dashboard that Filter loops and if you open this -> then FIELD dropdown has looped animation

### Expected results

Expected: We should indicate somehow that Filter is malformed(@junlincc) and do not propose not available options to set.

### Actual results

Observed: You can find that *FIELD has looped loading animation with name of not available field. After I choose different datasource I still see this old type of field as an option in field box.
#### Screenshots
![image](https://user-images.githubusercontent.com/25153919/104338408-c5135a80-54f6-11eb-8a34-b33468b33a75.png)

https://user-images.githubusercontent.com/25153919/104338901-4c60ce00-54f7-11eb-93c6-c369e89c9f27.mov

#### How to reproduce the bug
Scenario:
Create Filter with reference to dataset
Delete this dataset
Go back to Filter Configuration and Scoping:

### Environment

Please enable native filter first
Run code from commit 90915db60d0f330fd28a5fc2b7a6676944c4dbb5

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by agatapst** [comment]
I will check this issue

**Comment by junlincc** [comment]
thanks for the PR, testing, merging and closing! @agatapst @adam-stasiak @zhaoyongjie
