### ISSUE TITLE
[chart] Pie chart left side elements -> label disappears

### ISSUE THREAD

**Issue by adam-stasiak** [apache/superset#12456]
## Screenshot

Open chart Are you an ethnic minority in your city?
https://user-images.githubusercontent.com/25153919/104327526-2b927b80-54eb-11eb-89d0-1b3e90b12d86.mov

## Description

When you put mouse on left elements of chart then label dissapears. it should remain.

**Comment by junlincc** [comment]
resolved by bumping Echarts to 5.0.2
