### ISSUE TITLE
[explore]chart save modal scroll and dropdown

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12469]
https://user-images.githubusercontent.com/67837651/104363247-c5493100-54c9-11eb-9b6f-ded5f033985c.mp4

related to https://github.com/apache/superset/issues/12310(fixed issues in dashboard) 

obviously this behavior is global in Superset. addressing in one modal is not enough

@adam-stasiak pls give a round of audit in the product and look for all areas that are being affected, and list those in comment. 🙏

**Comment by kkucharc** [comment]
I mentioned this issue in exiting [PR-12410](https://github.com/apache/superset/pull/12410). After small change it will address problem from the video. Thanks to @geido 's work we may save a lot of time when we detect similar dropdown issues :)

**Comment by geido** [comment]
> obviously this behavior is global in Superset. addressing in one modal is not enough

We must be careful here though @junlincc. The most common solution might be to introduce the overflow visibility, however we might end up in a situation like the one depicted here https://github.com/apache/superset/pull/11770#issuecomment-741438519

**Comment by geido** [comment]
I am attempting a solution for this that uses the overflow visibility but in a way that should not reintroduce other issues.

**Comment by junlincc** [comment]
resolved
