### ISSUE TITLE
[listview] Please display message when chart cannot be open because of missing dataset

### ISSUE THREAD

**Issue by adam-stasiak** [apache/superset#12464]
Case is that when we delete dataset used by chart and then try to visit this chart - > we are sticked in listing view. Click on chart should redirect us to explore but does not.

### Expected results

I should see chart open with information saying about missingdataset.

### Actual results

Listing is refreshed
#### Screenshots

https://user-images.githubusercontent.com/25153919/104351996-6655dd00-5506-11eb-929d-a7c1593098e0.mov

#### How to reproduce the bug

1. Go to charts listing
2. Note name of dataset to remove
3. Go to dataset and remove this dataset
4. Go to chart listing and tap on chart name with empty dataset

### Environment

docker
90915db60d0f330fd28a5fc2b7a6676944c4dbb5
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@nytai just want to bring this to your attention. 

we will take this on. @kkucharc Thanks so much!

**Comment by nytai** [comment]
hmm, what should happen in this case? The chart would no longer be useable if the underlying dataset is missing.

**Comment by kkucharc** [comment]
@nytai Well when I refresh chart when dataset was already deleted, I had NotFound screen:
<img width="913" alt="Screenshot 2021-01-12 at 19 33 41" src="https://user-images.githubusercontent.com/2536609/104357228-2fcf9080-550d-11eb-9802-f8806039de00.png">
Maybe we should update state and not show chart on the lists anymore. Or we can have some error page.

**Comment by junlincc** [comment]
> hmm, what should happen in this case? The chart would no longer be useable if the underlying dataset is missing.

if the chart is no longer useable, should we still display it on the list view, or at least notify user? i would mistaken it as a bug in list view.

**Comment by junlincc** [comment]
> @nytai Well when I refresh chart when dataset was already deleted, I had NotFound screen:
> <img alt="Screenshot 2021-01-12 at 19 33 41" width="913" src="https://user-images.githubusercontent.com/2536609/104357228-2fcf9080-550d-11eb-9802-f8806039de00.png">
> Maybe we should update state and not show chart on the lists anymore. Or we can have some error page.

exactly

**Comment by nytai** [comment]
Well in that case should deleting a dataset cause all associated charts to be deleted? I know it's showing up as a UI bug but this is more of an api/data issue

**Comment by adam-stasiak** [comment]
Toast message for this would be ok @kkucharc

**Comment by junlincc** [comment]
We are putting a quick bandaid on this issue by adding a lightweight msg for now. I don't think we should hide or delete charts for the users at all. 

cc @steejay

**Comment by nytai** [comment]
I'm pretty sure this has always been an issue in some form. Deleting a dataset that's connected to a lot of charts affects those charts in weird ways. We've talked about not even allowing a user to delete a dataset until they've deleted all associated charts and dashboards.

Popping a toast would be nice, but I'm pretty sure those are just regular html links for the chart. The exception is on the backend. 

@mistercrunch or @zuzana-vej any thoughts on what should be correct behavior for this issue?

**Comment by junlincc** [comment]
i understand there's a bigger conversation behind, that's why we are not suggesting any significant changes. simply adding a notification will do more benefit than harm at this point.

**Comment by kkucharc** [comment]
I added notification message.

If I may have suggestion for the future discussions:
1. It would be good to introduce some error pages -> If someone would like share a chart's link and the chart is deleted in meantime, it would be great to show the user some user-friendly page.
2. Maybe it's not bad idea to give possibility to user to delete a datasource but also give some prompt "are you sure?" maybe even with the list of charts it will affect.

**Comment by ktmud** [comment]
Longer term solution should be allow Explore page to open without a datasource.

**Comment by nytai** [comment]
@kkucharc 2 is what happens now (at least from the list view).

<img width="1675" alt="Screen Shot 2021-01-12 at 12 00 46 PM" src="https://user-images.githubusercontent.com/10255196/104366200-dac05a00-54cd-11eb-91aa-9a2fc3b8dbf2.png">


> Longer term solution should be allowing Explore page to open without a datasource.

Yes, ideally the user could go in an fix the chart

**Comment by dpgaspar** [comment]
I vote for restricting it at the API level

**Comment by nytai** [comment]
@dpgaspar you mean just not allowing users to delete datasets that are connected to charts/dashboards? I think we've talked about this before. We should change the prompt, maybe provide links to the objects that need to be deleted first.

**Comment by Steejay** [comment]
I think preserving the chart would be ideal. Even though deleting the datasource will break the associated charts, i dont think we want charts to suddenly disappear for the user. 

Flow: Open chart > error message displayed in Explore that the associated dataset has been deleted.
