### ISSUE TITLE
[explore] Changing chart type with active annotation layer and filter causes missing chart

### ISSUE THREAD

**Issue by adam-stasiak** [apache/superset#12474]
When I set Annotation layer and filter and switch chart type then I got it missing.
### Expected results

proper chart should be displayed
### Actual results

chart is missing
#### Screenshots

https://user-images.githubusercontent.com/25153919/104376132-d70bf200-5524-11eb-9cf5-3bf90be33704.mov

Sorry for bad quality of video. It was long and I was not able to make this under 10MB limit.

#### How to reproduce the bug

add new line chart for random_time_series dataset
add annotation layer for this chart
add filter "ds is not null"
Run query
Change chart type to Area chart
Run Query
Change chart type to Line chart
Run Query

### Environment

docker run
commit 5f93a14f5dd422e6f9ed468390b128776f278b03

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing as stale, and I _seem to recall_ this being fixed. @adam-stasiak if you or anyone on the team can replicate this nowdays, please feel free to re-open.
