### ISSUE TITLE
[dashboard] including chart which is malformed (removed datasource) results in broken links

### ISSUE THREAD

**Issue by adam-stasiak** [apache/superset#12476]
When I open chart which is malformed because of deleted datasource I get error.

### Expected results

?? @benceorlai Could you define what is expected behavior for such case? In additional context section I described problem.

### Actual results

fatal error
#### Screenshots

<img width="1435" alt="Zrzut ekranu 2021-01-12 o 23 31 12" src="https://user-images.githubusercontent.com/25153919/104383477-2d326280-5530-11eb-91c8-3b1d6ffff97a.png">

#### How to reproduce the bug

Find chart with datasource X
Find dashboard with this chart
Remove datasource X
Open dashboard with this chart
See error

### Environment
docker commit e47350ef961917102c6319545e52df3961752a46

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x ] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

You can find similiar issue https://github.com/apache/superset/issues/12475 resolved in PR https://github.com/apache/superset/pull/12468 . But here situation is more difficult because I can imagine situation where dashboard is full of valid charts and only single one is malformed and then user cannot access this space. We should think about long term solution for this - consistent for both cases.

CC: @junlincc @kkucharc

**Comment by nytai** [comment]
I updated the title because this is really an issue with the dashboard itself, not the list view. The same error would happen if the user were visiting a bookmarked link to the dashboard. 

We should probably handle this the same way we're handling https://github.com/apache/superset/issues/12464 as it's just another symptom of the same problem.

**Comment by rusackas** [comment]
@adam-stasiak is there any reason to keep this Issue open?

**Comment by adam-stasiak** [comment]
we can close
