### ISSUE TITLE
Move CTAS Schema Field Closer to the "Allow Create Table As" In Edit Datasource Modal

### ISSUE THREAD

**Issue by yousoph** [apache/superset#12470]
## Screenshot

![Clipboard 2021-07-01 at 10 44 15 AM](https://user-images.githubusercontent.com/10627051/104364487-84521c00-54cb-11eb-960c-aea2504783ae.png)

## Description

It's not obvious that the CTAS Schema field is related to the Allow Create Table As option and might be easily missed by users. The text field should be closer to the Allow CTAS option visually so users know they're related and can change the options together.

**Comment by yousoph** [comment]
Will work with @steejay on a mock for this

**Comment by Steejay** [comment]
Here's a link to the prototype that addresses this pain point. The goal is to display only what the user needs to see at any given time in their flow to reduce visual clutter and information overload. 

Changes:
• Both Allow CTAS and CVAS are dependent on the 'Expose in SQL Lab' selection so they appear only when applicable
• The schema input field moved closer to its related context (CVAS and CTAS) 
• The schema input field copy is updated to address CTAS **and** CVAS

https://www.figma.com/proto/NbuTOMaUdv2GCBoDyihdLw/Database-CRUD-P0?node-id=475%3A1&scaling=min-zoom%5C

**Comment by Steejay** [comment]
@lyndsiWilliams @yousoph @hughhhh 

Here is an updated prototype that reflect some changes to the progressive disclosure.
https://www.figma.com/proto/NbuTOMaUdv2GCBoDyihdLw/Database-CRUD---P0?node-id=613%3A50&scaling=min-zoom

Figma spec:
https://www.figma.com/file/NbuTOMaUdv2GCBoDyihdLw/Database-CRUD---P0?node-id=479%3A39226

**Comment by Steejay** [comment]
![Add Modal - SQL Lab Settings @1456 (2)](https://user-images.githubusercontent.com/60786102/105777977-423fc600-5f20-11eb-9659-06e36f2a4cb0.jpg)
