### ISSUE TITLE
[explore]gallery is behind select dropdown 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12485]
![ezgif-6-57eaf4343712](https://user-images.githubusercontent.com/67837651/104417039-9f537900-5529-11eb-9a78-af4d12e6164b.gif)

see above.

**Comment by junlincc** [comment]
@kgabryje can you please take this one on? aiming v1.0.1 thanks!🙏

**Comment by kgabryje** [comment]
@junlincc 👍

**Comment by kgabryje** [comment]
@junlincc How can I reproduce it? The select dropdown closes itself when any area outside of dropdown is clicked.

**Comment by junlincc** [comment]
The issue has gone... what a miracle..😃 let's move on~ @kgabryje 
https://user-images.githubusercontent.com/67837651/104894535-b0392b80-5929-11eb-88f2-9a0e9636e0ed.mov

**Comment by kgabryje** [comment]
> are all dropdown in Superset now use the same component? or groupby has its own?
I think that we mix react-select and antd
