### ISSUE TITLE
Jinja templates not working in superset 1.0 rc1

### ISSUE THREAD

**Issue by lilila** [apache/superset#12487]
Queries using Jinja variables are not working anymore in Superset 1.0 rc1. 

For instance I have a dataset defined as follows : 

```
{% set title_target = ' "'  + filter_values("title_target", 'Joker')[0] + '" ' %}
{% set title_type =  'title' %}

{% if filter_values('title_target_original')|length > 0 %}
    {% set title_target =  ' "'  + filter_values("title_target_original", 'Joker')[0] + '" ' %}
    {% set title_type =  'title_original' %}
{% endif %}


SELECT {{title_target}} AS title_to_display
```

I use to work well but now I receive the following error: 
 
`Error: (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'%\n set title_target = \' "\' + filter_values("title_target", \'Joker\')[0] + \'" \' \' at line 4')`

If I move the Jinja parameters in the "template parameters" section: 

<img width="945" alt="Screenshot 2021-01-13 at 08 09 06" src="https://user-images.githubusercontent.com/607430/104418038-9e950400-5576-11eb-90dd-c677fb3a26ce.png">

I receive the following error: 
`Expecting property name enclosed in double quotes: line 1 column 2 (char 1)`

**Comment by junlincc** [comment]
@lilila thanks for reporting, we will get to it asap!

**Comment by villebro** [comment]
Thnks for reporting @lilila , going to work on this now.

**Comment by villebro** [comment]
@lilila I'm not able to reproduce the first case - I assume you've enabled the template processing feature flag?

```python
FEATURE_FLAGS = {
    "ENABLE_TEMPLATE_PROCESSING": True,
}
```

See #11172

**Comment by lilila** [comment]
@villebro , No I didn't , works when enabled ! Sorry and thank you

**Comment by villebro** [comment]
Great, no worries!

**Comment by annibac** [comment]
Just a quick question , how do I include this with Helm?
I tried to add this in values.yaml, but it seems to be ignored :

`configOverrides:
  my_override: |

    FEATURE_FLAGS = {
      "ENABLE_TEMPLATE_PROCESSING": True
    }`

When I try to use {{ filter_values("sampling")[0] }} I get the following postgresql error : `Postgresql Error : syntax error at or near "{" `

**Comment by abhiroop93** [comment]
Have the same question, how do I include this with Helm?

**Comment by annibac** [comment]
Hello !
I just found a way

In your folder, go to superset > template : there is a "_helpers.tpl" file which contains the superset_config.
Just add at the end:

```
FEATURE_FLAGS = {
    "ENABLE_TEMPLATE_PROCESSING": True,
}
```
And this will work. Not sure if this is the best way to do it, but works for me for now.

Regards
Celine

**Comment by mona-mk** [comment]
I think the correct place with docker nowadays is here:
<img width="1092" alt="Screenshot 2021-07-01 at 11 27 34" src="https://user-images.githubusercontent.com/59080347/124092360-6e2b1e80-da5f-11eb-8a3c-9406cf3cd832.png">

**Comment by NikosSpanos** [comment]
> @lilila I'm not able to reproduce the first case - I assume you've enabled the template processing feature flag?
> 
> ```python
> FEATURE_FLAGS = {
>     "ENABLE_TEMPLATE_PROCESSING": True,
> }
> ```
> 
> See #11172

Should be added on `superset_config.py` file and NOT on `config.py` file

**Comment by NikosSpanos** [comment]
> I think the correct place with docker nowadays is here: <img alt="Screenshot 2021-07-01 at 11 27 34" width="1092" src="https://user-images.githubusercontent.com/59080347/124092360-6e2b1e80-da5f-11eb-8a3c-9406cf3cd832.png">

This is the way to make it work. Kudos!

**Comment by blackmamba-ops** [comment]
> > @lilila I'm not able to reproduce the first case - I assume you've enabled the template processing feature flag?
> > ```python
> > FEATURE_FLAGS = {
> >     "ENABLE_TEMPLATE_PROCESSING": True,
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > See #11172
> 
> Should be added on `superset_config.py` file and NOT on `config.py` file

Didnt worked for me even after enabling 

    "ENABLE_TEMPLATE_PROCESSING": True
