### ISSUE TITLE
[Dashboard] Adding charts from new samples data in Dashboard edit mode throws unexpected error

### ISSUE THREAD

**Issue by ktmud** [apache/superset#12480]
#### Screenshots

![image](https://user-images.githubusercontent.com/335541/104391321-8086bf80-54f4-11eb-8fdb-e2b3fa1c18b2.png)

Adding the new sample charts from the `video_game_sales` dataset to a new dashboard in the Edit mode will render the chart with an `unexpected error`, which seems to come from trying to getting datasource:

<img src="https://user-images.githubusercontent.com/335541/104391375-a01de800-54f4-11eb-9937-cecd35d9926f.png" width="400">

The error message says "Cannot find viz object"

<img src="https://user-images.githubusercontent.com/335541/104391454-bdeb4d00-54f4-11eb-9536-5f3bd36cb1ee.png" width="600">

Saving the dashboard and refresh the whole page, the charts can correctly render.

#### How to reproduce the bug

1. Duplicate a sample dashboard (e.g. "Sales Dashboard" and "FCC New Coder Survey 2018") and check "Also duplicate chart":
   ![image](https://user-images.githubusercontent.com/335541/104405152-25af9100-5511-11eb-8672-abb7fb94d4cc.png)
2. Go to dashboard edit mode
2. Add the chart from the sample dataset

### Environment

Latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
i would consider this is another 1.0 release blocker

**Comment by junlincc** [comment]
<img width="1211" alt="Screen Shot 2021-01-12 at 10 42 30 PM" src="https://user-images.githubusercontent.com/67837651/104415803-7d58f700-5527-11eb-9e3a-6567a9e43772.png">

@ktmud do you know why the new samples data is not showing in the data table? is it also related?

**Comment by ktmud** [comment]
I'm not sure.

However, may I report another cosmetic issue:

![image](https://user-images.githubusercontent.com/335541/104418046-33721000-552b-11eb-8158-d17f8d8b6d65.png)

Is this drop-shadow intended?

**Comment by junlincc** [comment]
> Is this drop-shadow intended?

we didn't have a design for Data table section due to time constraints. we are merely using whatever comes with the component, i believe. it doesn't bother me much, but i agree the entire Explore page still needs a lot of cosmetic improvement. @mihir14
