### ISSUE TITLE
[Explore]Custom SQL COUNT_DISTINCT subtraction in metrics

### ISSUE THREAD

**Issue by bcbilgin** [apache/superset#12493]
Hi, 
It's version 0.36.0.
I try to subtract two metric columns; like column1-column2. I need distinct counts here so my first number will be COUNT_DISTINCT(column1) and second one is COUNT_DISTINCT(column2).
This works:
![superset2](https://user-images.githubusercontent.com/10693748/104449690-09166600-55b0-11eb-814a-f7bad25e9d12.PNG)
This does not work:
![superset3](https://user-images.githubusercontent.com/10693748/104449730-1af80900-55b0-11eb-96fc-20859e67be50.PNG)
The error is:
> druid error: Unknown exception (org.apache.calcite.tools.ValidationException): org.apache.calcite.runtime.CalciteContextException: From line 7, column 8 to line 7, column 30: No match found for function signature COUNT_DISTINCT(<CHARACTER>)

Note that COUNT_DISTINCT() function -like COUNT() function- works for both column1 and column2.

Is this intentional? What is the difference between subtraction on counts and subtraction on distinct counts?

**Comment by villebro** [comment]
`COUNT_DISTINCT(x)` is, I believe, a relic from old times, and should really be replaced by `COUNT(DISTINCT x)`. Regular count is used for counting rows, while distinct counting is used for counting unique values in the column.

**Comment by bcbilgin** [comment]
Yes, of course I need to count distinct values and I think you are right, but the reason I use `COUNT_DISTINCT(x)` instead of `COUNT(DISTINCT x)` is the following:
![superset4](https://user-images.githubusercontent.com/10693748/104453374-5d701480-55b5-11eb-9383-c2b616e1c106.png)
The default selection is `COUNT_DISTINCT`

**Comment by bcbilgin** [comment]
`COUNT(DISTINCT column1) - COUNT(DISTINCT column2)` did work for me, but I still believe a fix is needed here :)

**Comment by villebro** [comment]
Yes, I agree, the mapping from simple to custom filter for `COUNT_DISTINCT` is weird and should be changed. @junlincc let's fix this

**Comment by junlincc** [comment]
@zhaoyongjie @villebro let's include the fix it the metric refactoring project, which i wanna prioritize in Q1 before any further feature development

**Comment by rusackas** [comment]
Closing this since it hasn't seen any traction in over two years. If this is still an issue, let's just declare bankruptcy here and start a new Issue that's more pertinent to Superset 2.0.x. Thanks!
