### ISSUE TITLE
[dashboard] Impossible to edit imported dashboard data

### ISSUE THREAD

**Issue by agatapst** [apache/superset#12495]
When user exports and then imports a dashboard, it is impossible to change some data, i.e. name of the imported dashboard or name of the filter.

### Expected results
It should be possible to edit data of the imported dashboard, the same as it is possible to edit data of the existing dashboard (the one user exports).

### Actual results
When user changes some data, it is not presented. 
In case of changing the name in all dashboard panel, it is not possible to click "save" in editing modal.

#### Screenshots
Change name of the imported dashboard
![imported_dash_change_name](https://user-images.githubusercontent.com/47450693/104449615-25f66d80-559f-11eb-9209-6e9df82d9239.gif)

Change filter name of the imported dashboard
![imported_dash_filter](https://user-images.githubusercontent.com/47450693/104449754-635afb00-559f-11eb-903c-4f0aa7924dad.gif)

#### How to reproduce the bug
1. Export dashboard
2. Import this dashboard
3. Try to edit this dashboard - for example name in all dashboard panel or click dashboard name and change filter name

### Environment
Last commit:  [#407b194b15](https://github.com/apache/superset/commit/407b194b15)

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
I have noticed, that if I remove last lines from JSON metadata, editing works fine.
![imported_dash_json](https://user-images.githubusercontent.com/47450693/104452211-f2b5dd80-55a2-11eb-9ca7-70cd04d72587.gif)

**Comment by junlincc** [comment]
cc @betodealmeida

**Comment by rusackas** [comment]
Seems to be working just fine in newer versions, at least with the VERSIONED_EXPORTS flag enabled. Calling this one complete, but happy to re-open if anyone sees reason.

**Comment by hanslemm** [comment]
I've had the same problem with Superset 2.0.1dev in my production environment. Tried to investigate everything, from YAML files to backend, and couldn't explain why only imported dashboards don't work.

**Comment by pandeypranay** [comment]
I am facing the same issue, using Superset Version: 2.0.1

**Comment by rusackas** [comment]
I think it might be reasonable to strip `color_scheme_domain` automatically on import... though I'm not quite sure the intricacies/dangers in doing so. If anyone wants to open a PR with tests, that would be welcomed!
