### ISSUE TITLE
Line break tooltip

### ISSUE THREAD

**Issue by wildsonc** [apache/superset#12496]
Is it possible to insert a line break in tooltip?

I already tried:

- \n
- Edit css
- &#013

this is my function:

function getTooltip(tool) {
    return tool && `Title1 ${tool.object.extraProps.column1}:  ${tool.object.extraProps.column2}
    \n Title2: ${tool.object.extraProps.column3}
    \n Title3: ${tool.object.extraProps.column4}`;
}

**Comment by zhaoyongjie** [comment]
@wildsonc 
Could you complete the issue template?

**Comment by wildsonc** [comment]
´<p>String</p>´ Works for me
