### ISSUE TITLE
Sqllab query max limit in query dropdown

### ISSUE THREAD

**Issue by michellethomas** [apache/superset#12509]
Hi, With the new updates to sqllab (🎉 ) it looks like the max limit in the `limit` dropdown in sqllab is 100,000. Previously, we had the SQL_MAX_ROW config setting to set the max limit on sql queries. Can we allow users to type in their own limit into the limit dropdown (up to `SQL_MAX_ROW`) or make the dropdown options configurable? It's important for users to have the option of getting more results in sqllab.

![image](https://user-images.githubusercontent.com/817955/104539678-df226b00-55d2-11eb-8492-adebf20e1d7c.png)

**Comment by michellethomas** [comment]
@hughhhh looks like this was changed in your https://github.com/apache/superset/pull/12067 Sql toolbar PR, thoughts on how we can get a higher sqllab limit back? Maybe if `SQL_MAX_ROW` is > 100,000 we can make `SQL_MAX_ROW` the last option? Or make the dropdown options configurable?

**Comment by ktmud** [comment]
We should replace that dropdown with a `CreatableSelect`.

**Comment by zuzana-vej** [comment]
@yousoph

**Comment by hughhhh** [comment]
Just put up #12529 with the fix tell me what you think

@michellethomas

**Comment by yousoph** [comment]
Immediate solution: Show additional options in the LIMIT dropdown based on SQL_MAX_ROW 
If needed, users can customize to a different LIMIT in the query itself 
That should solve the most pressing issue but let us know if it doesn't

Also open to exploring a more configurable dropdown in the future if the above doesn't meet user's needs. (I'm always happy to chatting about problems / pain points / use cases if anybody has thoughts! 😄  )
