### ISSUE TITLE
[Explore] New time picker breaks old charts with "x days" in time picker start date

### ISSUE THREAD

**Issue by ktmud** [apache/superset#12508]
### Expected results

In 0.38 and earlier, if you set "30 days" or "5 months" in start date (without "ago", "before", or "last"), it will be automatically converted to the equivalent of "30 days ago". The new time picker will treat it as "30 days after today", causing an `Unexpected time range: From date cannot be larger than to date` error for some existing charts. 

Here are examples of time ranges that will break in the new time picker but are valid for the old one:

1. "30 days: "  -> "30 days ago : now"
3. "7 days: 7 days" -> "7 days ago : 7 days after today"

### Actual results

Existing charts with "x periods" set in start date should behave the same.

Since the original behavior is a little bit ambiguous, we may actually want to force users to use "30 days ago" or "- 30 days" for this use case. So I think it's OK to keep current logic, but to minimize disruption, we should do a db migration to automatically fix such charts and add a breaking change warning in the `v1.0` changelog (albeit numbers users who used this syntax is low).

### Environment

Latest master

**Comment by ktmud** [comment]
Thanks @michellethomas for spotting this issue!

**Comment by junlincc** [comment]
thanks for reporting! 
we are happy to include the proposed change in patch release, however, we recommend users to implement their own db migration to eliminate the migration risk. lmk if this sounds reasonable. @ktmud

**Comment by ktmud** [comment]
I think we should at least adding an entry in `UPDATING.md` to highlight this breaking change. DB migration script is a low priority considering the low volume of such charts, but it should be eventually committed to the Superset codebase because this is not a company-specific bug.

**Comment by zhaoyongjie** [comment]
I'm thinking of maybe doing some adaptations in `get_since_until` https://github.com/apache/superset/blob/241f380e2efe91ad58106cdb4848e0829f432e1e/superset/utils/date_parser.py#L135 @ktmud

**Comment by ktmud** [comment]
That works too. But I do find the previous behavior too ambiguous and somewhat confusing so would appreciate it if we can properly deprecate it. Maybe even throw an error message when "x periods" are used without the look back/forward descriptors.

**Comment by zhaoyongjie** [comment]
This is a good point. When we detect the user time range value is "X [dateunit]" then respond to an error message.
