### ISSUE TITLE
[Dashboard] FCC New Coder Survey 2018, Error: Columns missing in datasource: ['Gender']

### ISSUE THREAD

**Issue by zuzhi** [apache/superset#12505]
In this Gender slice in FCC New Coder Survey, uses wrong column name for group by cause an error.

Change 'Gender' to 'gender' should fix it.

#### Screenshots

![image](https://user-images.githubusercontent.com/11850845/104512031-8f6e8e80-5628-11eb-9ed3-fc7928da65aa.png)

![image](https://user-images.githubusercontent.com/11850845/104511978-782fa100-5628-11eb-88fb-a2d211c5422d.png)

#### How to reproduce the bug

1. Go to Dashboard 'FCC New Coder Survey 2018'
2. See error/Go to Gender Slice

### Environment

Latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Change 'Gender' to 'gender' should fix it.

![image](https://user-images.githubusercontent.com/11850845/104512750-a661b080-5629-11eb-8fb0-3c2154153b36.png)

**Comment by villebro** [comment]
@zuzhi on what database are you? I assume the problem is caused by how the database handles mixed case column names?

**Comment by zuzhi** [comment]
@villebro I use MySQL 8 as superset meta database

**Comment by zuzhi** [comment]
#12530 will fix this issue.
