### ISSUE TITLE
[Sample]View data section shows no data of new samples dataset

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12504]
View data section shows no data of new samples dataset imported recently 
This is not a functional issue. The table works perfectly on old dataset and charts.

<img width="1789" alt="Screen Shot 2021-01-13 at 1 15 50 PM" src="https://user-images.githubusercontent.com/67837651/104511480-a027f180-55a1-11eb-9f91-ff02fb213401.png">

<img width="1786" alt="Screen Shot 2021-01-13 at 1 24 32 PM" src="https://user-images.githubusercontent.com/67837651/104512197-b2565f80-55a2-11eb-87d7-84a4ce7c0dd9.png">

recent PR https://github.com/apache/superset/pull/12483 solved a possibly related issue in Dashboard.

**Comment by junlincc** [comment]
@betodealmeida @eschutho could you take a look at this issue as well? i received a couple report of this issues. thanks

**Comment by betodealmeida** [comment]
@junlincc can you post steps to repro or add more details? I don't understand the bug.

**Comment by junlincc** [comment]
@betodealmeida 
- Create a line chart with a new sample dataset 
- Open Data section and click View Samples - show no data 
- Try change to another new sample dataset in the modal, repeat steps - show no data 
- switch to one of the old sample datasets, VIEW SAMPLES works properly

**Comment by junlincc** [comment]
resolved, thanks @betodealmeida !
