### ISSUE TITLE
[SQL Lab] Split Run Button on Toolbar Missing Disabled State

### ISSUE THREAD

**Issue by yousoph** [apache/superset#12501]
## Screenshot
![image](https://user-images.githubusercontent.com/10627051/104499666-4b30af00-5592-11eb-8d4f-be78795e3528.png)

## Description
Prereqs: Have CTAS and/or CVAS enabled on a database 
In SQL Lab, delete all text in your query. The button should be showing a disabled state of the split run button but currently shows as the wrong width with the text cut off. 
The disabled state of the split run button shouldn't have a tooltip on hover.

## Design input
Mockup of the new disabled state for the split button would be helpful here @steejay, thank you!

**Comment by Steejay** [comment]
cc @yousoph @eschutho 

![Split button disabled](https://user-images.githubusercontent.com/60786102/105513467-32598500-5c87-11eb-9163-1742a8323ba5.png)

link to Figma:
https://www.figma.com/file/mPacKMIAXDpZMrQiGDeJMd/SQL-Toolbar-UX%2FUI---P0?node-id=1033%3A26744

**Comment by zuzana-vej** [comment]
looks fixed based on linked PR
