### ISSUE TITLE
[explore] switch between SIMPLE and CUSTOM SQL in ad hoc filter

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12512]
![ezgif-4-cd50b8c2a1f0](https://user-images.githubusercontent.com/67837651/104552675-15211880-55ee-11eb-908f-00ba77769d1e.gif)

Expected behavior:
select filter value in the SIMPLE tab should automatically update SQL expression in the CUSTOM tab

Actual behavior: 
Users have to click the input field to update the change 

To reproduce
- create a chart in Explore
- create a filter in SIMPLE 
- switch to CUSTOM SQL without clicking SAVE or CLOSE
- switch back to SIMPLE, change the filter value
- switch to CUSTOM again see expression

**Comment by junlincc** [comment]
@eschutho @willbarrett we discussed about investing in automated test rather than having both manual testing and automated test, do you guys think issues like this one can be easily caught? and how long will it take to get to that point?

**Comment by zhaoyongjie** [comment]
@junlincc 
we need to merge this [PR](https://github.com/apache/superset/pull/12446), before fix this bug.

**Comment by junlincc** [comment]
> we need to merge this [PR](https://github.com/apache/superset/pull/12446), before fix this bug.

will do @zhaoyongjie

**Comment by eschutho** [comment]
> @eschutho @willbarrett we discussed about investing in automated test rather than having both manual testing and automated test, do you guys think issues like this one can be easily caught? and how long will it take to get to that point?
> 
> cc @mistercrunch

Yes @junlincc I think once we start doing more integration tests with React Testing Library, we can focus on these types of assertions.
