### ISSUE TITLE
[chart] Replace Big Number with Big Card

### ISSUE THREAD

**Issue by kamalkeshavani-aiinside** [apache/superset#12516]
**Is your feature request related to a problem? Please describe.**
I would like to show a single metric/dimension value from db in a report. Currently the only option for that is Big Number chart type, which can work with only Numbers.

**Describe the solution you'd like**
Instead of Big Number, a new chart type like 'Big Card' or 'Big Value' should allow any data type like datetime, string, %, etc. along with some subheader text as it allows now.
And ofcourse, d3 formatting to set the Big Value formatting style.

**Describe alternatives you've considered**
An alternative could be supporting SQL query results in Markdown component of dashboard. Users can setup their formatting style in markdown, and get the values from SQL query. But this solution will need extra effort to support filtering effects.

**Comment by junlincc** [comment]
@maloun96 🙏

**Comment by inesplc** [comment]
Also could use this feature!
Our current work around is to use a word map chat in a dataset that returns only one series, but obviously this is not its intended use.

Similar issues were raised in https://github.com/apache/superset/issues/1784, https://github.com/apache/superset/issues/2919 and https://github.com/apache/superset/issues/6771 but were never finished.

**Comment by junlincc** [comment]
@kamalkeshavani-aiinside @inesplc can you send us the link to the library? thanks!

**Comment by kamalkeshavani-aiinside** [comment]
@junlincc what library are you asking about?

**Comment by jdbranham** [comment]
Related - https://github.com/apache-superset/superset-ui/pull/1390

**Comment by jhult** [comment]
Looks like there is some good activity happening on apache-superset/superset-ui#1390. We would love to see this feature.

**Comment by jhult** [comment]
Looks like the new PR (in this repo) is still active: https://github.com/apache/superset/pull/17903

**Comment by sfirke** [comment]
Here's a very minimal example of a Handlebars chart that makes a chart with a single text value:
![image](https://user-images.githubusercontent.com/7569808/192856267-199d438b-09ce-46b8-883c-904c3cf6ce40.png)

Data is "Raw Records" with a single row.  I wanted the value to look exactly like this and in order to get both the _$_ prefix and _B_ suffix I had to process the value into a string outside of Superset.

**Comment by kamalkeshavani-aiinside** [comment]
@sfirke Thank you.
With Handlebars I think we can achieve what is requested in this feature request, so closing this for now.
