### ISSUE TITLE
filter box's selector of time column in the dashboard is not show 

### ISSUE THREAD

**Issue by zhanggkaii** [apache/superset#12517]
in the chart:
![image](https://user-images.githubusercontent.com/28882694/104576234-e3ae5880-5692-11eb-80eb-3977e627a2cb.png)

in the dashboard:
![image](https://user-images.githubusercontent.com/28882694/104576217-dee9a480-5692-11eb-851c-a8bf7009735c.png)

**Comment by junlincc** [comment]
what version are you using? @zhanggkaii
