### ISSUE TITLE
[Sqllab] results table overlap buttons, horizontal scroll doesn't work when column is 50+ 

### ISSUE THREAD

**Issue by michellethomas** [apache/superset#12538]
If you run a query in sqllab that returns a large number of columns, the results header shows up on top of the "explore" and "csv" buttons making them not clickable. 

#### Screenshots
![image (4)](https://user-images.githubusercontent.com/817955/104688916-7e6c5e80-56b6-11eb-85f0-da948c7c53ae.png)

#### How to reproduce the bug

1. Run a select * statement on a table with 70+ columns
2. Results header will show up on top of the action buttons and you cannot click on the buttons

### Environment

- superset version: master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
<img width="1790" alt="Screen Shot 2021-01-15 at 10 10 13 AM" src="https://user-images.githubusercontent.com/67837651/104763022-29623400-571a-11eb-877a-787c6f97d142.png">

**Comment by betodealmeida** [comment]
Let me take a look, I worked on the height of the results recently and might've broken this.

**Comment by betodealmeida** [comment]
Looks like it happen when have more than `MAX_COLUMNS_FOR_TABLE` columns (which defaults to 50), and we invoke `renderGrid` in `FilterableTable.tsx`.
