### ISSUE TITLE
[code hygiene] Fully move Timeseries Table plugin to superset-ui 

### ISSUE THREAD

**Issue by ktmud** [apache/superset#12533]
Follow up for #12532 .

We need to fully move the Timeseries Table plugin to [`@superset-ui/legacy-plugin-chart-time-table`](https://github.com/apache-superset/superset-ui/blob/84a6d592b9470883150c1085dada740b69e46fe6/plugins/legacy-plugin-chart-time-table/) and delete related files in `superset-frontend`.

**Comment by amitmiran137** [comment]
I think this is not relevant after the monorepo work
