### ISSUE TITLE
[Dashboard]arrow sorting label drifted off the attribute text in dashboard table

### ISSUE THREAD

**Issue by amyshangshang** [apache/superset#12546]
## Screenshot

attached

## Description

1. click one dashboard
2. in the dashboard page, the table on the left part has the name and count attributes. next to the name attribute, the sorting label was placed too far away from its text. 

<img width="1402" alt="Screen Shot 2021-01-15 at 2 35 11 AM" src="https://user-images.githubusercontent.com/4502866/104715562-930f1d80-56db-11eb-8cb1-b2e21d3ceb90.png">
<img width="1405" alt="Screen Shot 2021-01-15 at 2 38 07 AM" src="https://user-images.githubusercontent.com/4502866/104715571-96a2a480-56db-11eb-970e-409d19822a36.png">

**Comment by junlincc** [comment]
good catch! thank you @amyshangshang for reporting it!
