### ISSUE TITLE
Change dataset header floats on top of table entries

### ISSUE THREAD

**Issue by villebro** [apache/superset#12541]
## Screenshot

![change_dataset](https://user-images.githubusercontent.com/33317356/104708014-d4c4b600-5725-11eb-9b3f-1e77344b75ba.gif)

## Description

When scrolling the change dataset table, the header floats above the table entries. Regression caused by #12432

## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

**Comment by junlincc** [comment]
this behavior is currently not in master and is mentioned in https://github.com/apache/superset/issues/12503 but yea it would have caused regression thus not including #12432 in v1.0. 😅

**Comment by villebro** [comment]
Closing as this recording does not reflect current state of master
