### ISSUE TITLE
[Dashboard] dashboard charts can't be shared by email

### ISSUE THREAD

**Issue by amyshangshang** [apache/superset#12543]
dashboard charts can't be shared by email

### Expected results

when user clicked the "share chart", it popped out a link with a copy thumbnail and a email thumbnail. when click the email thumbnail, it should launch the email app.

### Actual results

when click the email thumbnail, nothing happens.

#### Screenshots

attached

#### How to reproduce the bug

1. Go to 'dashboards'
2. Click on one of the dashboards
3. click the up-right corner of any one of the charts
4. click 'share chart'
5. click the email thumbnail

<img width="1435" alt="Screen Shot 2021-01-15 at 2 01 22 AM" src="https://user-images.githubusercontent.com/4502866/104712474-707b0580-56d7-11eb-92fb-57eefbec1996.png">

**Comment by junlincc** [comment]
@amyshangshang thanks for reporting the issue. I tested on master, the email redirect is working properly. im not able to repro this issue. could you please double check? thanks 


https://user-images.githubusercontent.com/67837651/104851827-c7cdd100-58a3-11eb-91dc-c15f3d754dfd.mov
