### ISSUE TITLE
How can I change the Timerange Defaults in Filterbox

### ISSUE THREAD

**Issue by durchgedreht** [apache/superset#12540]
We have the use case that we'd need to adjust the filtering for the defaults.
The day, week, month, ... preselection is good also for our use case but it limits the data to last midnight. We would also need the last actual data points!

Is there a way to change this by configuration somewhere?

Also it would be great to limit the defaults to e.g. last day, last week, last month only as data for last year is not available at all and doens't make sense from a users perspective.

<img width="246" alt="Screenshot 2021-01-15 at 10 24 01" src="https://user-images.githubusercontent.com/4490840/104707296-82cb6280-571c-11eb-8591-debd6490607f.png">

**Comment by nzewail** [comment]
I don't believe that you can change the defaults but this would definitely be a useful feature

**Comment by ktmud** [comment]
Related: https://github.com/apache/superset/issues/13125

**Comment by amitmiran137** [comment]
filterbox is depracted
you should checkout the DASHBOARD_NATIVE_FILTERS ff that contain the ability the have a default for each filter type
what you're asking might be included already
