### ISSUE TITLE
[Charts] In charts display page,  "data" part under the table has different layouts for different datasets

### ISSUE THREAD

**Issue by amyshangshang** [apache/superset#12545]
## Screenshot

attached screenshots

## Description

the data table displayed in 1 row or 3 rows for different datasets

<img width="1416" alt="Screen Shot 2021-01-15 at 2 25 20 AM" src="https://user-images.githubusercontent.com/4502866/104714314-ebddb680-56d9-11eb-9067-96300fdcee5c.png">
<img width="1430" alt="Screen Shot 2021-01-15 at 2 26 37 AM" src="https://user-images.githubusercontent.com/4502866/104714330-f13b0100-56d9-11eb-8210-5b8ecec19f75.png">
I

**Comment by junlincc** [comment]
thanks for reporting! @amyshangshang 

for the first chart(popular genres) you may wanna adjust the slide bar to see the full table.and we added pagination to tables that with 50+rows. double checked on master, they both work expected. 

<img width="1791" alt="Screen Shot 2021-01-17 at 9 12 30 AM" src="https://user-images.githubusercontent.com/67837651/104851968-8e499580-58a4-11eb-87a9-3895df3631c6.png">
<img width="1791" alt="Screen Shot 2021-01-17 at 9 12 57 AM" src="https://user-images.githubusercontent.com/67837651/104851970-8f7ac280-58a4-11eb-9449-c922f0bddb31.png">
