### ISSUE TITLE
[explore] Hover on (i) in dropdown renders tooltip behind the dropdown

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#12551]
When user hovers on the (i) to view description of a data field / calculation, the tooltip with description renders behind the dropdown box making the description unredable. 

### Expected results

Tooltip is over the dropdown

### Actual results

Tooltip is behind the dropdown

#### Screenshots
![Screen Shot 2021-01-15 at 7 37 29 AM](https://user-images.githubusercontent.com/61221714/104746962-cca84e80-5704-11eb-8f6a-8487eec17b77.png)

#### How to reproduce the bug

1. Go to Explore
2. Click on Any dropdown (for example GROUP BY
3. Scroll down to hover over (i) for field which was info
4. See issue

### Environment
latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zuzana-vej** [comment]
related issue: https://github.com/apache/superset/issues/12485

**Comment by kgabryje** [comment]
@zuzana-vej I cannot reproduce it 
![image](https://user-images.githubusercontent.com/15073128/104889863-11372280-596f-11eb-9c83-b56108995767.png)
Can you verify if the bug persists on latest master?
CC: @junlincc

**Comment by junlincc** [comment]
@zuzana-vej it does seem like it's fixed~ 

<img width="1065" alt="Screen Shot 2021-01-18 at 1 03 10 AM" src="https://user-images.githubusercontent.com/67837651/104893987-f8a41980-5928-11eb-948c-473a01e0d06a.png">

<img width="1028" alt="Screen Shot 2021-01-18 at 1 01 58 AM" src="https://user-images.githubusercontent.com/67837651/104894005-0063be00-5929-11eb-9ff6-2b5cbe056154.png">
