### ISSUE TITLE
[sample]The new "FCC 2018 Survey" data has bad calculated column

### ISSUE THREAD

**Issue by ktmud** [apache/superset#12559]
#### Screenshots

If you "View Samples" or select the "Highest Degree Earned" column in a table chart, you will see follow error:

![Snip20210115_170](https://user-images.githubusercontent.com/335541/104773866-91207b00-572a-11eb-800d-c90926d4f724.png)

![image](https://user-images.githubusercontent.com/335541/104774024-ccbb4500-572a-11eb-8f63-5c19c5da7c6e.png)

This is because the column expression used double quotes which will be considered column name escaping in most databases:

![image](https://user-images.githubusercontent.com/335541/104774132-f96f5c80-572a-11eb-9731-64b0d5b93ca9.png)

#### How to reproduce the bug

1. Choose "FCC 2018 Survey" dataset
2. Go to "View Samples" or use the "Highest Degree Earned" column anywhere in a chart

### Environment

Latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by betodealmeida** [comment]
@ktmud was this closed on purpose?

**Comment by ktmud** [comment]
@betodealmeida oh no... didn't know how I clicked on close..

**Comment by betodealmeida** [comment]
Cool, let me fix this.
