### ISSUE TITLE
typo in connections index in the documentation

### ISSUE THREAD

**Issue by aaronsdevera** [apache/superset#12574]
## Description

typo in `docs/src/pages/docs/Connecting to Databases/index.mdx`
the currently listed connection string for snowflake is "ssnowflake"
the correct driver is "snowflake," as verified on their sqlalchemy docs: [https://docs.snowflake.com/en/user-guide/sqlalchemy.html](https://docs.snowflake.com/en/user-guide/sqlalchemy.html)

**Comment by 96RadhikaJadhav** [comment]
@aaronsdevera  Can I work on the issue?
