### ISSUE TITLE
[chart] Y Axis Bounds in more charts (Bar Chart, Dual

### ISSUE THREAD

**Issue by kamalkeshavani-aiinside** [apache/superset#12588]
**Is your feature request related to a problem? Please describe.**
Currently Y-axis bounds option is available only for below Time-series charts:

- Line Chart
- Time-series Bar chart
- Time-series Percent Change
- Time-series Period Pivot

**Describe the solution you'd like**
I think it should be available in below charts as well:

- Dual Line Chart
- Bar Chart
- Multiple Line Chart

**Additional context**
The option of defining Y-bounds is really helpful to set min of Y-axis at 0 in Line charts, which will otherwise start at minimum marker value by default.
Similarly maximum value setting is very helpful in bar charts when there are 2 similar charts in a dashboard.

**Comment by junlincc** [comment]
https://github.com/apache-superset/superset-ui/pull/908 
we added y bounds for Bar Chart, Dual Line Chart & Multi Line Chart
feature should be available soon.

**Comment by kamalkeshavani-aiinside** [comment]
@junlincc This feature is added in superset-ui 17.0 release, but superset 1.0.1 includes superset-ui 16.9. So this feature will be visible in the next release of Superset, is that understanding correct?

**Comment by kamalkeshavani-aiinside** [comment]
It's available in latest release. Thank you!
