### ISSUE TITLE
[Explore]modal cancel button should come before the save button

### ISSUE THREAD

**Issue by geido** [apache/superset#12587]
## Screenshot

<img width="905" alt="Screen Shot 2021-01-18 at 21 35 04" src="https://user-images.githubusercontent.com/60598000/104960770-31013180-59d5-11eb-83ef-720f38a760c2.png">

## Description

The "SAVE" button should be the last button in the footer of the modal, just after the "CANCEL" one to make it consistent with the other modals in the project.

**Comment by geido** [comment]
I'll be fixing this one @junlincc

**Comment by junlincc** [comment]
please make sure changes apply to both edit and change dataset modal in Explore. thanks! @geido

**Comment by geido** [comment]
@junlincc it looks like the Change Dataset modal already has the buttons in the right position when you pick a new dataset. Is there anything else you are looking to change?
