### ISSUE TITLE
Scroll Bars on all charts even if they shouldn't be there

### ISSUE THREAD

**Issue by petervanstaaden** [apache/superset#12597]
I am having an issue where all user-made charts are scrollable no matter what, as you can imagine, this looks poopy for the user and it makes it difficult to scroll down the page. Any support or advice will be appreciated 
![image](https://user-images.githubusercontent.com/57384868/105044555-8b4ed080-5a6f-11eb-9e10-dec7784fc4b2.png)

**Comment by junlincc** [comment]
thanks for reporting. this issues should have been fixed in latest master. https://github.com/apache/superset/pull/12478
