### ISSUE TITLE
Unsafe attempt to load URL <URL> from frame with URL <URL>. Domains, protocols and ports must match.

### ISSUE THREAD

**Issue by liamnv** [apache/superset#12592]
When I use superset with https, superset  fetch /api/v1/dashboard/favorite_status from http, so throw this error

**Comment by nytai** [comment]
@ktmud a few users have reported this issue. The favorite_status is being fetched via the `makeApi` pattern. That's the only thing, that comes to mind, that's particular about this call. Any ideas what could be happening here?

**Comment by ktmud** [comment]
It's strange that this happens only with `/api/v1/dashboard/favorite_status`. `SupersetClient` uses the same as current `window.location`: https://github.com/apache/superset/blob/46664452a792ed56ac7faf50dd88d781e65df914/superset-frontend/src/setup/setupClient.ts#L29

@nytai do you have links to other reported issues?

**Comment by nytai** [comment]
A user also reported this in slack
https://apache-superset.slack.com/archives/C015WAZL0KH/p1611936487035400

**Comment by pl77** [comment]
I'm also encountering this, but otherwise the instance appears to be working as it should.  I have `superset init`'d my instance more times than I can count. I enabled the `ENABLE_PROXY_FIX = True` suggestion from Mistercrunch from this issue: https://github.com/apache/superset/issues/6824#issuecomment-485318807

I was next going to tinker with various CORS settings to see if I could corner this bug.

**Comment by mhconradt** [comment]
@pl77 were you successful with any CORS settings?

**Comment by pl77** [comment]
@mhconradt For some inexplicable reason I'm not noticing the error messages anymore.  I haven't updated the container holding it nor changed any CORS settings yet.  I got pulled away into another project for a couple of days and when I went back I stopped noticing the errors.  Very odd.

**Comment by mengzeyu** [comment]
I'm also encountering this, has anyone worked around this successfully?

**Comment by jawabuu** [comment]
Hey @mengzeyu
You need to set this;
`ENABLE_PROXY_FIX = True`
Your superset instance also must receive the following header
```
"X-Forwarded-Proto": "https"
```
The way to set it depends on which reverse proxy you use.

**Comment by mengzeyu** [comment]
Thanks a lot! @jawabuu 
I will try to set these configs.

**Comment by reignmaker** [comment]
The only thing that helped me is setting `X-Forwarded-Proto https;` **explicitly** (not the `$scheme` var), just as stated in the docs:

> In case the reverse proxy is used for providing SSL encryption, an explicit definition of the X-Forwarded-Proto may be required.

https://superset.apache.org/docs/installation/configuring-superset#configuration-behind-a-load-balancer

**Comment by pl77** [comment]
@jawabuu That makes sense.  I had it working perfectly under NGINX on one server and when I migrated it to a new server running Traefik this issue started to emerge.  

If the issue re-emerges for me I'll double-check that the headers are forwarded:
https://doc.traefik.io/traefik/v2.3/routing/entrypoints/#forwarded-headers

**Comment by jawabuu** [comment]
@pl77 You are correct.
If the header is not being forwarded, you can set it in traefik so that it is always passed to the application.
