### ISSUE TITLE
[explore] Store all tabs width in Explore view

### ISSUE THREAD

**Issue by adam-stasiak** [apache/superset#12599]
**Is your feature request related to a problem? Please describe.**
With https://github.com/apache/superset/pull/12593 it comes possibility to store locally width of native filter tab. I can modify the width and after revisit see this applied thanks to localStorage. 
**Describe the solution you'd like**
I would like to have similiar things for rest of the screen. For the middle part and for the chart area.
![image](https://user-images.githubusercontent.com/25153919/105047983-53458e80-5a6b-11eb-9fa9-a9a03900ace3.png)

**Describe alternatives you've considered**
nothing
**Additional context**

**Comment by junlincc** [comment]
@adam-stasiak thanks for the opening the issue! @nikolagigic let's tackle this one as well. thank you both! 🙏
@pkdotson fyi

**Comment by adam-stasiak** [comment]
@junlincc it is resolved now.
