### ISSUE TITLE
Providing Dashboard Access to a group 

### ISSUE THREAD

**Issue by Renganayaki1** [apache/superset#12590]
I can see support for users and different roles in superset. But What I need is, Consider, I have a set of dashboards for finance department. Only that department's members can view the dashboards and for any other departments, it should be restricted. 

I know we can restrict the dashboard access very easily, But One solution I need is to create a group with all the members I have and to add that group as a single user, while creating Rules and Users in Apache Superset.

One alternate solution is to create a Role as we want and add one or more users easily. 

But adding multiple number of users to multiple number of Roles is pretty difficult (Based on which department they belong to). So that the idea is to create a group for each group of Users and sharing dashboard to that group.

**Comment by amitmiran137** [comment]
duplicate https://github.com/apache/superset/issues/12910
