### ISSUE TITLE
How to enable query execution in sqllab for Anonymous user(public role) ?

### ISSUE THREAD

**Issue by vikalpmullick** [apache/superset#12618]
Superset version: 0.38

Superset config:
AUTH_ROLE_PUBLIC='Public'
PUBLIC_ROLE_LIKE='Admin'

After superset init, all admin permissions are copied to Public role.

In Sqllab query execution does not work for Public role

ERROR: superset.views.core:Query2: 'AnonymousUserMixin' object has no attribute 'username'

![20210120_165427.jpg](https://user-images.githubusercontent.com/68067507/105168488-3464fc00-5b40-11eb-8a89-6847ce19a86e.jpg)
Pls excuse me for image quality.

Query executes for admin user.

What need to be done to allow anonymous user to allow query execution in sqllab ?

**Comment by robdiciuccio** [comment]
@vikalpmullick A fix for this issue has been merged, but granting admin access to public users is obviously less than secure.
