### ISSUE TITLE
[Explore] Open existing adhoc metric should not open the SAVED tab

### ISSUE THREAD

**Issue by ktmud** [apache/superset#12614]
@kgabryje @junlincc Found a bug on this one: opening a selected adhoc metric should open the SIMPLE or CUSTOM tab, but now it always opens the SAVED tab.

_Originally posted by @ktmud in https://github.com/apache/superset/issues/12582#issuecomment-763202521_

**Comment by junlincc** [comment]
Previous behavior & correct behavior is always open up the same tab that user created the metric in. My bad, did not catch it when I tested.

**Comment by kgabryje** [comment]
Could you share steps to reproduce? It seems to work correctly for me
https://user-images.githubusercontent.com/15073128/105153415-b2a5ac00-5b08-11eb-9abb-5480b1a97a40.mov

**Comment by ktmud** [comment]
Weird, I could not reproduce it any more, either.

Maybe it's because I confused it with re-opening the popover after switching tabs but not save. The popover always opens at the last active tab before closing (which I think is fine). 

Sorry for the noise.

**Comment by kgabryje** [comment]
👍
