### ISSUE TITLE
[explore]Non-metric uniqueness in Explore

### ISSUE THREAD

**Issue by john-bodley** [apache/superset#12611]
It seems like metrics in explorer and keyed by name, however for charts which support multiple metrics, Superset cannot differentiate between selected saved metrics. This means if you add the same metric multiple times and change one of the metrics all references to said metric change. 

### Expected results

Either:

1. The same metric should not be able to be added multiple times (ensuring uniqueness).
2. Each selected metric should have a unique ID allow.

### Actual results

what actually happens.

#### How to reproduce the bug

1. Go to Explorer.
2. Choose a chart type which supports multiple metrics.
2. Add a saved metric.
3. Re-add the same saved metric.
4. Change one of the saved metrics.
5. Notice that both metrics changed.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
thanks for reporting! was able to reproduce. 
we will need a few days to come up with a solution and get to it. hope that works for your users🙏 @john-bodley 

https://user-images.githubusercontent.com/67837651/105119746-ce1ba300-5a85-11eb-8eae-dd67724e233c.mp4
