### ISSUE TITLE
[explore]switching viz type from/to filter box requires refreshing 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12624]
When user switch between viz type and filter box, it requires clicking refresh to run
![ezgif-4-d2bdf8af252c](https://user-images.githubusercontent.com/67837651/105218261-c7cf0a80-5b09-11eb-96e1-44abe0b50f85.gif)

To repro:
1. create a chart in Explore 
2. change data viz type to filterbox
3. click run - see page is hanging 
4. refresh the page to see viz type change

**Comment by junlincc** [comment]
top priority for quality `bash! `

**Comment by villebro** [comment]
This is caused by Filter Box having a non-standard data payload (Object as opposed to Array). Bullet chart also uses an Object instead of Array.

**Comment by junlincc** [comment]
resolved
