### ISSUE TITLE
[import]Dashboard import doesn't support multiple databases

### ISSUE THREAD

**Issue by bryanck** [apache/superset#12623]
If a dashboard uses datasets from multiple databases, then during import all datasets are assigned to the database specified in the import form. This causes the import to fail when a dataset doesn't exist in the specified database. Perhaps there should be an option to ignore the database override.

### Expected results

Expected that a dashboard that uses multiple databases wouldn't fail with an error.

### Actual results

Dashboard import fails with an error.

#### How to reproduce the bug

1. Create a dashboard
2. Add charts that use different databases
3. Export the dashboard
4. Delete the dashboard, charts, and datasets
5. Import the dashboard. You must select a single database here
6. Import fails. Or if it succeeds, it creates datasets all in the same database

### Environment

(please complete the following information):

- superset version: 1.0 RC4
- python version: 3.7.9
- node.js version: 12.14.1

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [*] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [*] I have reproduced the issue with at least the latest released version of superset.
- [*] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dtran-srev** [comment]
I tried to import a few dashboards from Superset version 0.37.1 to version 1.1.0 and got same error "An unknown error occurred. Please contact your Superset administrator" for both cases: 
a. dashboard connecting to multiple databases
b. dashboard connecting to single database
All datasets imported to version 1.1.0 for both cases but none of charts or dashboards 

Any ideas why a  single database dashboard didn't get imported?

Thanks

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, we don't support those versions of Superset anymore, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
