### ISSUE TITLE
Genders by State Example Charts Not Loading

### ISSUE THREAD

**Issue by yousoph** [apache/superset#12630]
### Expected results
Example chart should load properly in the chart and on the dashboard 

### Actual results
Genders by State chart shows an error with the column names - num_boys and num_girls don't exist anymore 

#### Screenshots

![image](https://user-images.githubusercontent.com/10627051/105225826-01a50e80-5b14-11eb-9cb2-a664622e8559.png)

#### How to reproduce the bug

1. Visit the Genders by State chart (Charts > Genders by State or Dashboards > Birth Names) 

### Environment

- superset version: master

### Checklist

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by yousoph** [comment]
@ktmud - I believe you updated the column names, do you mind taking a look?

**Comment by ktmud** [comment]
Yeah, dropping and reload the examples database should fix this. I just assumed examples are only used for developing/testing purpose and would not be used in any actual deployment therefore didn't do anything fancy about it.

**Comment by yousoph** [comment]
Ahh, got it, thanks!

**Comment by robdiciuccio** [comment]
PR that introduced the change: https://github.com/apache/superset/pull/12082
