### ISSUE TITLE
[metrics] metric select popover unexpectedly closes when using the scrollbar

### ISSUE THREAD

**Issue by ktmud** [apache/superset#12641]
## Screenshot

1. The metric select popover unexpectedly closes when using the scrollbar:

![unexpected-close](https://user-images.githubusercontent.com/335541/105269282-77c36880-5b48-11eb-91b3-1579c2ce8937.gif)

2. Previously the list also had autoresizable width when the list is short enough to not use virtual list where it always fits the longest option. This still works in SQL Lab table select: 

<img src="https://user-images.githubusercontent.com/335541/105268918-dd632500-5b47-11eb-9f9a-6e3000f15d68.png" width="500">

**Comment by junlincc** [comment]
1. The metric select popover unexpectedly closes when using the scrollbar
Does it happen only when you have list of metrics w long metric? 

can you file these two issues separately? it will help us faster get to them. thanks! @ktmud

**Comment by ktmud** [comment]
2 is related to #12640 so I don't think we need another issue.

**Comment by junlincc** [comment]
1 seems like a antd component related issue... 😔 let's try @villebro

**Comment by junlincc** [comment]
resolved
