### ISSUE TITLE
[explore]Error while rendering Time-series Table visualization

### ISSUE THREAD

**Issue by john-bodley** [apache/superset#12646]
I'm unsure under what circumstances this is occurring but there are instances where the "Time-series Table" visualization results in a React error. Note the result set contains two rows and thus I wonder if there may be insufficient data for the visualization. 

### Expected results

The chart should render or show a meaningful error if there is insufficient data for the visualization.

### Actual results

A React error is shown.

#### Screenshots

<img width="1361" alt="Screen Shot 2021-01-21 at 5 42 51 PM" src="https://user-images.githubusercontent.com/4567245/105281082-31d1d780-5c10-11eb-9fb9-bd3c89a787cd.png">

#### How to reproduce the bug

1. Create a "Time-series Table" visualization with a result set of two rows. 
2. Observe the error.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
`I wonder if there may be insufficient data for the visualization.` i think so. 
 could you try setting no filter on time and see if there's still an error? @john-bodley

**Comment by john-bodley** [comment]
This is an insufficient data issue. Removing the time granularity circumvented the issue, however the visualization types needs to gracefully handle the case of insufficient data.

**Comment by junlincc** [comment]
Right, we thought about changing the error message to more human readable. any other suggestions? @john-bodley

**Comment by junlincc** [comment]
cc @eugeniamz
