### ISSUE TITLE
[dashboard] Toggle Chart Description results in chart overflowing it's area

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#12643]
When a user clicks on "Toggle chart description", the description gets displayed bellow the chart title, and the chart shifts downwards, resulting in the bottom of the chart (the x axis and legend) overflowing out of the chart area

### Expected results
Chart doesn't overflows

### Actual results
Chart overflows

#### Screenshots
Before "Toggle Chart description"
![Screen Shot 2021-01-20 at 7 54 13 PM](https://user-images.githubusercontent.com/61221714/105278542-95013280-5b5a-11eb-8acc-819b1ba29ed0.png)

After "Toggle Chart description"
![Screen Shot 2021-01-20 at 7 54 06 PM](https://user-images.githubusercontent.com/61221714/105278657-d265c000-5b5a-11eb-9f56-fd93108db283.png)

#### How to reproduce the bug

1. Go to Dashboard
2. Click on '...' on a chart which has a description (can be added in chart explore edit properties)
3. Click on "Toggle Chart description"
4. See issue

### Environment
latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zuzana-vej** [comment]
Low pri bug, but just wanted to ping here for a reminder (@junlincc).

**Comment by michael-s-molina** [comment]
@junlincc Can you assign this to me? I'm working on it.

**Comment by zuzana-vej** [comment]
@michael-s-molina it looks like @m-ajay has a PR out for this item since yesterday

**Comment by michael-s-molina** [comment]
@zuzana-vej Thanks for letting me know. Luckily I hadn't started this yet.
