### ISSUE TITLE
bar chart: disabling "sort bars" doesn't reset sort order

### ISSUE THREAD

**Issue by villebro** [apache/superset#12650]
When enabling "sort bars" and disabling again, the order isn't reset to the original order.

### Expected results

The original order is restored.

### Actual results

The data is sorted by x-axis.

#### Screenshots

![bar-chart-sort](https://user-images.githubusercontent.com/33317356/105328638-ec45e800-5bd8-11eb-8652-018646c52ca5.gif)

#### How to reproduce the bug

1. Go to 'Genders by state' example chart
2. Click on 'Customize'
3. check 'sort bars'
4. uncheck 'sort bars'
4. See data ordered by x-axis

### Environment

(please complete the following information):

- superset version: `master` branch

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
@yousoph  this still seems to be a legit issue in the ECharts bar chart... I can't get the sorting to work. Holler if we need a ticket and a `preset:cares` label on this

**Comment by rusackas** [comment]
Given the feedback above, I think we can just close this. Please holler, anyone, if this needs re-opening.
