### ISSUE TITLE
Is Superset compatible with Web Accessibility Standards or Numeric Accessibility Standards ?

### ISSUE THREAD

**Issue by zsellami** [apache/superset#12656]
Hello,
Several companies perform an application audit before integrating them into their catalogs.
One of the criteria for the selection is digital accessibility for people with disabilities.
Is Superset compatible with accessibility standards like those proposed by W3C 
https://www.w3.org/WAI/standards-guidelines/wcag/
https://www.w3.org/WAI/fundamentals/accessibility-intro/ ?

**Comment by etr2460** [comment]
Superset is not currently compatible with accessibility standards. This sort of compatibility is something that the product certainly needs, but isn't currently being prioritized (as far as I know). I think we'd be happy if some community members wanted to step up and own a project around it

**Comment by mgifford** [comment]
A good start is to run the site against a browser tool like https://accessibilityinsights.io/ to check for and fix the low-hanging-fruit. It won't get you to meet WCAG 2.1 AA, but it will at least make some basic improvements that will benefit users with permanent, temporary & situational disabilities.

**Comment by zuzana-vej** [comment]
looks like this question has been answered --> closing this ticket

**Comment by bstolle** [comment]
Has this been addressed in the past 4 years? Perhaps an [accessibility statement](https://www.w3.org/WAI/planning/statements/) can be included publicly even if the answer is "not compliant"?
