### ISSUE TITLE
User can reset password without current password

### ISSUE THREAD

**Issue by liamnv** [apache/superset#12676]
### Expected results

User must provide current password to reset password

### Actual results

User can reset password without of current password

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by lamielle** [comment]
@liamnv can you provide a few more details on the bug you're reporting here?  This could be a serious security issue.  I'm relatively new to Superset but I think providing more information per the issue template would help the Superset team triage this bug.

**Comment by liamnv** [comment]
@lamielle I found this is an issue of Flask App Builder, I'm contributing for its here https://github.com/dpgaspar/Flask-AppBuilder/pull/1553

**Comment by mistercrunch** [comment]
@dpgaspar ^^^

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
