### ISSUE TITLE
SQL parser incorrectly identifies SQL reserved keywords as table names

### ISSUE THREAD

**Issue by john-bodley** [apache/superset#12677]
There's a few examples we've seen where the SQL parser incorrectly identifies SQL reserved keywords as tables when parsing the query. Note I've worked with `sqlparse` in another project and I sense we probably may need to complete rewrite Superset's parser in order for accurately extracting the table names leveraging more of the core `sqlparse`'s functionality.

### Expected results

The SQL parser should identify all data warehouse tables/views with no false positives.

### Actual results

The SQL parser misidentifies (under certain circumstances) SQL reserved keywords as table names.

#### How to reproduce the bug

```python
>>> from superset.sql_parse import ParsedQuery
>>> ParsedQuery(sql_statement="SELECT * FROM foo bar TABLESAMPLE BERNOULLI(50);").tables
{Table(table='TABLESAMPLE', schema=None, catalog=None), Table(table='foo', schema=None, catalog=None)}
```

Note adding the `AS` keyword results in a different result:

```python
>>> from superset.sql_parse import ParsedQuery
>>> ParsedQuery(sql_statement="SELECT * FROM foo AS bar TABLESAMPLE BERNOULLI(50);").tables
{Table(table='foo', schema=None, catalog=None)}
```

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by john-bodley** [comment]
@bkyryliuk and @villebro et al. any thoughts on this? Has Dropbox or Preset run into this issue?

**Comment by john-bodley** [comment]
@villebro or @dpgaspar has Preset experienced this issue?

**Comment by dpgaspar** [comment]
Not that I'm aware of. probably these keywords are not on `sqlparse`, not too familiar with it, with it make sense or solve the issue to extend those keywords?

**Comment by villebro** [comment]
@john-bodley I'm surprised adding that `AS` there makes a difference, I would have assumed it easily infers that's an alias in the first example. I assume this is a bug on `sqlparse`, maybe we should open a ticket there? I also haven't heard of anyone having this problem on Preset.

**Comment by john-bodley** [comment]
@rusackas, hopefully this issue will be resolved via @betodealmeida [SIP-117](https://github.com/apache/superset/issues/26786).

**Comment by rusackas** [comment]
This seems like it's either fixed or stale. Closing either way, but happy to reopen if I'm mistaken.
