### ISSUE TITLE
[chart]rich tooltip text overflows outside of the parent div for line chart

### ISSUE THREAD

**Issue by bryanck** [apache/superset#12688]
## Screenshot

![Screen Shot 2021-01-22 at 7 01 01 AM](https://user-images.githubusercontent.com/5475421/105507084-a09a4980-5c7f-11eb-95fe-9eda8b2d56b3.png)

## Description

The rich tooltip text renders in a table that is inside a parent div that has the max-width set. If the text in the table is too wide, then the text will render outside of the div.

This is being caused by this line setting the max width of the div:
https://github.com/apache-superset/superset-ui/blob/b7a2f5241b56ff78dfb3f53105383fc40b12e0e9/plugins/legacy-preset-chart-nvd3/src/utils.js#L317

You can reproduce this by creating a multiline chart, group by a field with longer strings, and then reducing the width of the chart by resizing your browser window.

**Comment by junlincc** [comment]
@bryanck hey, thanks for reporting issues lately! do you mind include Superset version? this looks like a good first issue, lmk if you would like to work on it.  :) 🙏

**Comment by bryanck** [comment]
This is version 1.0. I can create a PR in superset-ui. I was thinking to remove the `max-width` setting, which does resolve this.
