### ISSUE TITLE
MySQL Connection Fails If MySQL User Password Includes Special Characters

### ISSUE THREAD

**Issue by mariotalavera** [apache/superset#12691]
On **SQL Lab / SQL Editor**, the HTML element for schema dropdown fails (to fetch) schema list if the MySQL user password contains special characters.  

**Note** - Registering a database with a user whose password contains special characters works OK.

### Expected results

MySQL User Passwords should be allowed to contain special characters.

#### Screenshots

![image](https://user-images.githubusercontent.com/1094812/105527988-68f8c500-5cb2-11eb-8e00-180ae00d317d.png)

#### How to reproduce the bug

1. Register a MySQL database with a user whose password contains a special character.  This is successful.
2. Go to **SQL Lab / SQL Editor** and select database just registered from dropdown.
3. See popup error shared above.

### Environment
 
- environment: Amazon Linux 2
- docker: Docker version 19.03.13-ce, build 4484c46 
- docker-compose: docker-compose version 1.27.4, build 40524192
- superset version: 1.0.0
- python version: Python 3.7.9

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.

```
│superset_app             | DEBUG:superset.models.core:Database.get_sqla_engine(). Masked URL: mysql+pymysql://mario:XXXXXXXXXX@10.12.12.97:3306/st_utils?charset=utf8
│superset_app             | DEBUG:superset.stats_logger:[stats_logger] (incr) DatabaseRestApi.schemas.error
│superset_app             | DEBUG:superset.stats_logger:[stats_logger] (timing) DatabaseRestApi.schemas.time | 15.424574026837945 
│superset_app             | 10.12.21.136 - - [22/Jan/2021 18:15:09] "GET /api/v1/database/11/schemas/?q=(force:!f) HTTP/1.1" 500 -
│superset_app             | INFO:werkzeug:10.12.21.136 - - [22/Jan/2021 18:15:09] "GET /api/v1/database/11/schemas/?q=(force:!f) HTTP/1.1" 500 -
│superset_app             | DEBUG:superset.models.core:Database.get_sqla_engine(). Masked URL: mysql+pymysql://mario:XXXXXXXXXX@10.12.12.97:3306/st_utils?charset=utf8
│superset_app             | DEBUG:superset.stats_logger:[stats_logger] (incr) DatabaseRestApi.schemas.error
│superset_app             | DEBUG:superset.stats_logger:[stats_logger] (timing) DatabaseRestApi.schemas.time | 15.86733793374151 
│superset_app             | 10.12.21.136 - - [22/Jan/2021 18:15:09] "GET /api/v1/database/11/schemas/?q=(force:!f) HTTP/1.1" 500 -
│superset_app             | INFO:werkzeug:10.12.21.136 - - [22/Jan/2021 18:15:09] "GET /api/v1/database/11/schemas/?q=(force:!f) HTTP/1.1" 500 -
```

- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by aliamzhang** [comment]
I use the master branch to test without any problems
![image](https://user-images.githubusercontent.com/95735472/152649904-f3c158dc-4b8e-469c-954b-62af35fc8b40.png)
![image](https://user-images.githubusercontent.com/95735472/152650976-d1a0da6f-aad9-4f18-91bd-ca35ae8d1a60.png)

**Comment by zuzana-vej** [comment]
@mariotalavera  please reopen if you are still facing this issue
