### ISSUE TITLE
Installing Mac M1 with Docker Preview version 7

### ISSUE THREAD

**Issue by art-cg** [apache/superset#12697]
I failed by installing via Docker on Mac Os M1 with Docker Preview version 7.
Yes, i know it is a rare case.

### Expected results

Successfull install

### Actual results

Failed install.

Attaching to superset_cache, superset_db, superset_tests_worker, superset_worker, superset_node, superset_app, superset_init
superset_cache           | 1:C 22 Jan 19:51:04.667 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
superset_app             | Skipping local overrides
superset_db              | 
superset_db              | PostgreSQL Database directory appears to contain a database; Skipping initialization
superset_db              | 
superset_db              | 2021-01-22 19:51:04.825 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
superset_db              | 2021-01-22 19:51:04.825 UTC [1] LOG:  listening on IPv6 address "::", port 5432
superset_db              | 2021-01-22 19:51:04.985 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
superset_cache           |                 _._                                                  
superset_cache           |            _.-``__ ''-._                                             
superset_cache           |       _.-``    `.  `_.  ''-._           Redis 3.2.12 (00000000/0) 64 bit
superset_cache           |   .-`` .-```.  ```\/    _.,_ ''-._                                   
superset_cache           |  (    '      ,       .-`  | `,    )     Running in standalone mode
superset_cache           |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
superset_cache           |  |    `-._   `._    /     _.-'    |     PID: 1
superset_cache           |   `-._    `-._  `-./  _.-'    _.-'                                   
superset_cache           |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
superset_cache           |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
superset_cache           |   `-._    `-._`-.__.-'_.-'    _.-'                                   
superset_cache           |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
superset_cache           |  |    `-._`-._        _.-'_.-'    |                                  
superset_cache           |   `-._    `-._`-.__.-'_.-'    _.-'                                   
superset_cache           |       `-._    `-.__.-'    _.-'                                       
superset_cache           |           `-._        _.-'                                           
superset_cache           |               `-.__.-'                                               
superset_cache           | 
superset_app             | Starting web app...
superset_cache           | 1:M 22 Jan 19:51:04.678 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
superset_cache           | 1:M 22 Jan 19:51:04.678 # Server started, Redis version 3.2.12
superset_db              | 2021-01-22 19:51:05.121 UTC [25] LOG:  database system was shut down at 2021-01-22 19:45:31 UTC
superset_db              | 2021-01-22 19:51:05.231 UTC [1] LOG:  database system is ready to accept connections
superset_node            | npm WARN using --force I sure hope you know what you are doing.
superset_tests_worker    | Skipping local overrides
superset_cache           | 1:M 22 Jan 19:51:04.678 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
superset_tests_worker    | Starting Celery worker...
superset_worker          | Skipping local overrides
superset_worker          | Starting Celery worker...
superset_cache           | 1:M 22 Jan 19:51:04.678 * DB loaded from disk: 0.000 seconds
superset_cache           | 1:M 22 Jan 19:51:04.678 * The server is now ready to accept connections on port 6379
superset_init            | Skipping local overrides
superset_init            | 
superset_init            | ######################################################################
superset_init            | 
superset_init            | 
superset_init            | Init Step 1/4 [Starting] -- Applying DB migrations
superset_init            | 
superset_init            | 
superset_init            | ######################################################################
superset_init            | 
superset_app             |  * Serving Flask app "superset.app:create_app()" (lazy loading)
superset_app             |  * Environment: development
superset_app             |  * Debug mode: on
superset_app             |  * Running on http://0.0.0.0:8088/ (Press CTRL+C to quit)
superset_app             |  * Restarting with stat
superset_node            | /usr/local/bin/webpack -> /usr/local/lib/node_modules/webpack/bin/webpack.js
superset_node            | /usr/local/bin/webpack-cli -> /usr/local/lib/node_modules/webpack-cli/bin/cli.js
superset_node            | + webpack-cli@4.4.0
superset_node            | + webpack@5.17.0
superset_node            | updated 2 packages in 6.797s
superset_node            | npm WARN using --force I sure hope you know what you are doing.
superset_tests_worker    | INFO:superset.utils.logging_configurator:logging was configured successfully
superset_db              | 2021-01-22 19:51:23.523 UTC [32] FATAL:  database "test" does not exist
**superset_tests_worker    | /usr/local/lib/python3.7/site-packages/flask_caching/__init__.py:192: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.**
superset_tests_worker    |   "Flask-Caching: CACHE_TYPE is set to null, "
**superset_tests_worker    | ERROR:flask_appbuilder.security.sqla.manager:DB Creation and initialization failed: (psycopg2.OperationalError) FATAL:  database "test" does not exist**
superset_tests_worker    | 
superset_tests_worker    | (Background on this error at: http://sqlalche.me/e/13/e3q8)
superset_tests_worker    | Loaded your LOCAL configuration at [/app/docker/pythonpath_dev/superset_config.py]
superset_worker          | INFO:superset.utils.logging_configurator:logging was configured successfully
**superset_tests_worker exited with code 1
superset_worker          | qemu: uncaught target signal 4 (Illegal instruction) - core dumped**
superset_db              | 2021-01-22 19:51:25.820 UTC [33] LOG:  unexpected EOF on client connection with an open transaction
superset_worker          | /app/docker/docker-bootstrap.sh: line 45:    10 Illegal instruction     celery worker --app=superset.tasks.celery_app:app -Ofair -l INFO
superset_app             | INFO:superset.utils.logging_configurator:logging was configured successfully
superset_worker          | Skipping local overrides
superset_worker          | Starting Celery worker...
superset_init            | INFO:superset.utils.logging_configurator:logging was configured successfully
superset_app             | qemu: uncaught target signal 4 (Illegal instruction) - core dumped
superset_db              | 2021-01-22 19:51:30.125 UTC [34] LOG:  unexpected EOF on client connection with an open transaction
**superset_app             | /app/docker/docker-bootstrap.sh: line 45:    10 Illegal instruction     flask run -p 8088 --with-threads --reload --debugger --host=0.0.0.0**
superset_init            | qemu: uncaught target signal 4 (Illegal instruction) - core dumped
superset_db              | 2021-01-22 19:51:30.765 UTC [35] LOG:  unexpected EOF on client connection with an open transaction
**superset_init            | /app/docker/docker-init.sh: line 51:    16 Illegal instruction     superset db upgrade
superset_init exited with code 132**
superset_worker          | INFO:superset.utils.logging_configurator:logging was configured successfully
superset_app             |  * Serving Flask app "superset.app:create_app()" (lazy loading)
superset_app             |  * Environment: development
superset_app             |  * Debug mode: on
superset_worker          | qemu: uncaught target signal 4 (Illegal instruction) - core dumped
superset_db              | 2021-01-22 19:51:36.792 UTC [37] LOG:  unexpected EOF on client connection with an open transaction
**superset_worker          | /app/docker/docker-bootstrap.sh: line 45:    10 Illegal instruction     celery worker --app=superset.tasks.celery_app:app -Ofair -l INFO**
superset_app             |  * Running on http://0.0.0.0:8088/ (Press CTRL+C to quit)
superset_app             |  * Restarting with stat
superset_worker exited with code 132
superset_app             | INFO:superset.utils.logging_configurator:logging was configured successfully
superset_app             | qemu: uncaught target signal 4 (Illegal instruction) - core dumped
superset_db              | 2021-01-22 19:51:40.972 UTC [38] LOG:  unexpected EOF on client connection with an open transaction
**superset_app             | /app/docker/docker-bootstrap.sh: line 45:    10 Illegal instruction     flask run -p 8088 --with-threads --reload --debugger --host=0.0.0.0**
superset_app exited with code 132
superset_worker          | INFO:superset.utils.logging_configurator:logging was configured successfully
superset_worker          | qemu: uncaught target signal 4 (Illegal instruction) - core dumped
superset_db              | 2021-01-22 19:51:44.664 UTC [39] LOG:  unexpected EOF on client connection with an open transaction
**superset_worker          | /app/docker/docker-bootstrap.sh: line 45:    10 Illegal instruction     celery worker --app=superset.tasks.celery_app:app -Ofair -l INFO**
superset_worker exited with code 132
superset_app             |  * Serving Flask app "superset.app:create_app()" (lazy loading)
superset_app             |  * Environment: development
superset_app             |  * Debug mode: on
superset_app             |  * Running on http://0.0.0.0:8088/ (Press CTRL+C to quit)
superset_app             |  * Restarting with stat
superset_app             | INFO:superset.utils.logging_configurator:logging was configured successfully
superset_app             | qemu: uncaught target signal 4 (Illegal instruction) - core dumped
superset_db              | 2021-01-22 19:51:50.367 UTC [40] LOG:  unexpected EOF on client connection with an open transaction
**superset_app             | /app/docker/docker-bootstrap.sh: line 45:    12 Illegal instruction     flask run -p 8088 --with-threads --reload --debugger --host=0.0.0.0**
superset_app exited with code 132
superset_worker          | INFO:superset.utils.logging_configurator:logging was configured successfully
superset_worker          | qemu: uncaught target signal 4 (Illegal instruction) - core dumped
superset_db              | 2021-01-22 19:51:52.182 UTC [41] LOG:  unexpected EOF on client connection with an open transaction
superset_worker          | /app/docker/docker-bootstrap.sh: line 45:    10 Illegal instruction     celery worker --app=superset.tasks.celery_app:app -Ofair -l INFO

#### How to reproduce the bug

I followed the install notice from here
https://superset.apache.org/docs/installation/installing-superset-using-docker-compose

### Environment

- superset version: `dev-latest`
- python version: `3.7.9`
- node.js version: `12.20.1`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by nytai** [comment]
@art-cg This is a known issue. One of superset's dependencies (numpy or pyarray) are not compatible with Apple M1 chip. See https://github.com/numpy/numpy/issues/17807

**Comment by art-cg** [comment]
Thanks for the info. Sorry for the duplicate

**Comment by alecburnett** [comment]
@nytai Can you re-open this issue?

There is now a fix:

![image](https://user-images.githubusercontent.com/60477996/145633037-54b964c0-9698-49e1-9e5e-68c430beb31c.png)

**Comment by claytongulick** [comment]
Would love to see this issue re-opened, this is holding back development for my team
