### ISSUE TITLE
[explore]clear search input when switching dataset 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12708]
https://user-images.githubusercontent.com/67837651/105572965-16012b00-5d0f-11eb-88ec-b79899b00dcb.mov

requirement: clear search input in datapanel search bar when switching dataset

**Comment by pkdotson** [comment]
I'll take this! 1/2 story

**Comment by junlincc** [comment]
Awesome! thanks for being proactive!! @pkdotson

**Comment by pkdotson** [comment]
This was fixed with this ticket: https://github.com/apache/superset/pull/12909
