### ISSUE TITLE
[explore]cosmetic improvement suggestions 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12707]
<img width="1863" alt="Screen Shot 2021-01-23 at 12 31 48 AM" src="https://user-images.githubusercontent.com/67837651/105573577-6b3f3b80-5d13-11eb-85fd-1f084e669bc1.png">

1. decrease the spacing between VIEW RESULTS & VIEM SAMPLES tabs and caret & section title 
2. remove the frame(including drop-shadow) around data table and chart sections
3. move pagination down to create more space for the table 

cc @mihir174

**Comment by ktmud** [comment]
I think all of these are already fixed by #12649 .

The only thing I still don't like about this panel is the caret and the resize bar, it seems there is a lot of waste of space that could be optimized.

**Comment by junlincc** [comment]
> I think all of these are already fixed by #12649 .
for some reasons i couldn't see those changes on master...will confirm again...

**Comment by junlincc** [comment]
> I think all of these are already fixed by #12649 .

checked again, yes - mysterious frame and drop-shadow is gone.  
yup, we will kill some space between chart and the table

<img width="1134" alt="Screen Shot 2021-01-23 at 12 28 18 PM" src="https://user-images.githubusercontent.com/67837651/105613332-bc344b80-5d76-11eb-9b99-40f473052fb3.png">

**Comment by rusackas** [comment]
@junlincc Were there other issues that needed to be fixed to close this issue?
