### ISSUE TITLE
[dashboard]allow multiple default filter value select in native filter

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12713]
Filterbox allows user to set default filter value by typing in the default value in Explore, set value shows in the filter box dropdown select. - not intuitive at all. 

Native filter makes one big  step forward by allowing user to select default filter value from a dropdown list in dashboard filter modal. selected default value is carried to the native filter bar and can be instantly applied to dashboard. default value persists. wonderful job!! @agatapst 

Next step, please allow users to select multiple default values. 
<img width="1329" alt="Screen Shot 2021-01-23 at 3 53 42 PM" src="https://user-images.githubusercontent.com/67837651/105617441-2f4bbb00-5d93-11eb-8116-6b35e434a45c.png">

**Comment by villebro** [comment]
Closing, as this is already done
