### ISSUE TITLE
Wrong redirect link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by ayanginet** [apache/superset#12717]
## Description

CONTRIBUTING.md includes a link to OS dependencies that need to be installed before other dependencies. But the link is outdated.

### Expected results

Should redirect to 
https://superset.apache.org/docs/installation/installing-superset-from-scratch#os-dependencies

### Actual results

Instead redirects to installation with Docker Compose: 
https://superset.apache.org/docs/installation/installing-superset-using-docker-compose

### Additional Context
I verified that it is the right link by checking the previous version of the documentation website. The content is the same.
https://web.archive.org/web/20181103115231/https://superset.incubator.apache.org/installation.html#os-dependencies

**Comment by junlincc** [comment]
thanks for reporting and the fix! @ayanginet 🙏

**Comment by srinify** [comment]
Thank you for fixing! @ayanginet
