### ISSUE TITLE
[alert]can't add alerts and reports

### ISSUE THREAD

**Issue by code-snail** [apache/superset#12715]
can't add alerts and reports

**Comment by code-snail** [comment]
![image](https://user-images.githubusercontent.com/65579137/105622965-db9fa700-5e50-11eb-85b3-1177f388fc3c.png)

**Comment by dpgaspar** [comment]
@code-snail thank you for reporting it, could you please fill up the github issue bug template?

**Comment by code-snail** [comment]
@dpgaspar 
can't add new alert and report

### Expected results

expect to add new alert or report

### Actual results

actually, the ADD button is disabled.

#### Screenshots

If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/65579137/105786235-a2357b80-5fb7-11eb-96f5-a3d96c4785e3.png)


#### How to reproduce the bug

add alerts or reports: Settings -> Alerts&Reports -> +ALERT or +REPORT

### Environment

- docker image: apache/superset:latest
- superset version: Superset 0.999.0dev
- python version: Python 3.7.9

**Comment by nytai** [comment]
I did some poking around, it seems this issue only happens for production frontend builds (ie, `npm run build`)
