### ISSUE TITLE
[SIP] Add a top level data navigation to each chart

### ISSUE THREAD

**Issue by wernerdaehn** [apache/superset#12725]
### Motivation
Slice and dice is done by the chart consumer, not only(!) the chart developer.

I have been working for Business Objects and SAP and I am in the Business Intelligence Market for more than 20 years. I feel that the filter concept is too technical, the navigation within the data not suited for self service BI.

Imagine the FLIGHTS data in a real world scenario. You create a chart with the flight delays and this chart has certain configurations, e.g. group by AIRLINE, flight date is the time component. You might add filters as well, e.g. last year and delay >10 minutes.

If the created chart has a drop down box for each (useful) attribute above it, the user can easily move within the data. One drop down box is called ORIGIN_AIRPORT and shows the list of all airport codes to select from. Another are STATE, COUNTRY, DISTANCE,... all by which analyzing the data makes sense. "Show me the delays for one airport", "Should I pick SFO or San Jose?", "Does the time of the day play a role?"

The main problem of such navigation bar is that a normal table/view has thousands of columns the user might want to navigate within the data. This is when hierarchies come into play. In above example the COUNTRY, STATE, ORIGIN_AIRPORT are related to each other. It does not make sense to filter on a specific airport and then offer to filter the country also. Instead of rendering each attribute individually the attributes are organized in hierarchies:
COUNTRY->STATE->AIRPORT
Then the Location-of-Departure hierarchy dropdown is opened, at the first level all countries are shown. The user can select one country or multiple (checkboxes!) or expand one country to see its states etc.

### Proposed Change

1. On top of each chart is a horizontal, scroll-able list of columns the user might want to navigate within. This list contains attributes and measures.
2. Depending on the type of element different selectors are shown. For attributes like names a checkbox is rendered to select/deselect. For attributes that have an order like a date/time a from-to range selector is shown. Long/Lat has a rect shape selector,...
3. In the table definition hierarchies can be defined to group attributes together. Such hierarchies can either be
    * based on columns: GEOGRAPHY hierarchy is from COUNTRY to STATE to AIRPORT
    * based on parent-child relationships: PRODUCT_GROUP, PARENT_PRODUCT_GROUP
    * can contain alternative hierarchies also: GEOGRAPHY has an alternative using LONG/LAT columns
    * can be generated: TIMESTAMP has YEAR->MONTH->DAY->HOUR and as alternatives: WEEK, WEEKDAY, WORKDAY, QUARTER,...
4. It would be nice if the drop down list is sorted by relevance. For example you might have filtered on a regional airport and the plane type selector lets you chose a 747? Nothing is more demotivating as constantly getting a no-data chart.
5. Similarly showing the impact of a filter. If each filter value hints how much it will modify the diagram, e.g. airport1 has lots of delays, airport2 none that would help the user also.

Please let me know if you are interested and I would spend some time to work out the details.

**Comment by rusackas** [comment]
This seems to have slipped between the cracks. If you'd like to pursue this as a SIP, please fill out the remainder of the SIP template and post it to the dev@ emailing list. Otherwise, if you'd like to continue seeking community support of this feature request, please open a new [Ideas thread](https://github.com/apache/superset/discussions/categories/ideas) in our [Github Discussions](https://github.com/apache/superset/discussions) area.

**Comment by rusackas** [comment]
Happy to re-open this if it becomes a fully fleshed out SIP.
