### ISSUE TITLE
[chart]wrap metric text in chart tooltip

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12722]
looks like we set a max width in the chart tooltip, which cause long metrics name overflowing. Though this is another edge case of super long label name, we should wrap text still. 

<img width="1086" alt="Screen Shot 2021-01-24 at 9 08 49 AM" src="https://user-images.githubusercontent.com/67837651/105637748-e09a3180-5e23-11eb-9d49-4591cfb2d1d4.png">
<img width="1492" alt="Screen Shot 2021-01-24 at 9 08 25 AM" src="https://user-images.githubusercontent.com/67837651/105637749-e1cb5e80-5e23-11eb-8d44-9dcbf256fc2e.png">

**Comment by maloun96** [comment]
I checked from the latest master and seems that the tooltip is shown ok
@junlincc 

![image](https://user-images.githubusercontent.com/8277264/106380912-0f814c00-63be-11eb-99df-adbb63d1297f.png)
