### ISSUE TITLE
Filter not clean when remove value in annother 

### ISSUE THREAD

**Issue by Leandro-GPIN** [apache/superset#12735]
Filter not clean when remove value in annother 

### Expected results

![espected](https://user-images.githubusercontent.com/19553149/105711893-e82b0a80-5ef7-11eb-9515-8d76ac614830.png)

### Actual results

![current](https://user-images.githubusercontent.com/19553149/105711905-ec572800-5ef7-11eb-8852-9ba8d0691ff9.png)

#### Screenshots

![filter-problem](https://user-images.githubusercontent.com/19553149/105711258-10fed000-5ef7-11eb-904a-1908d3bb6f6e.gif)

#### How to reproduce the bug

1. Select East Asia & Pacific in region filter
2. Select North Americ in region filter
3. Select United States in country filter
4. Remove North Americ in region filter
5. See error.

### Environment

(please complete the following information):

- superset version: `37 docker version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
I believe you are expecting these two FilterBox work as cascading filters with workaround solution? We probably won't invest further in this solution as we recently roll out our new Dashboard native filter which does support this functionality.  It is currently behind a feature flag, and very close to be done.  to test - > https://github.com/apache/superset/issues/12148 @Leandro-GPIN

**Comment by suddjian** [comment]
This behavior is supported with cascading native filters.
