### ISSUE TITLE
[Question] How to avoid duplicate queries when one is running

### ISSUE THREAD

**Issue by hushaoqing** [apache/superset#12733]
In my case, I want to avoid duplicate queries when one is running.
Such as, when user open a dashboard:
1. A long query(3mins) for a chart is running
2. Another one trigger a same query when 1) is still running
3. result: there will be two same queries sent to database.

How to avoid duplicate queries in this case? Thanks.

**Comment by villebro** [comment]
This is a known limitation in the current architecture. However, this should be resolved once Global Async Queries become generally available: #9190 . If you feel like testing the feature, feel free to enable the `GLOBAL_ASYNC_QUERIES` feature flag. See the `CONTRIBUTING.md` documentation for details: https://github.com/apache/superset/blob/master/CONTRIBUTING.md#async-chart-queries
