### ISSUE TITLE
get_viz   viz_obj = viz.viz_types[viz_type](↵KeyError: 'yh_color_table'↵")

### ISSUE THREAD

**Issue by lcyh** [apache/superset#12732]
I customized a component yh_color_table，but  it was wrong,I don't know what's wrong？
error: "'yh_color_table'"
stacktrace: "Traceback (most recent call last):↵  File "/data/app/superset-web/superset/views/base.py", line 135, in wraps↵    return f(self, *args, **kwargs)↵  File "/data/app/superset-web/superset/utils/decorators.py", line 63, in wrapper↵    check_perms(*args, **kwargs)↵  File "/data/app/superset-web/superset/views/core.py", line 125, in check_datasource_perms↵    force=False,↵  File "/data/app/superset-web/superset/views/utils.py", line 120, in get_viz↵    viz_obj = viz.viz_types[viz_type](↵KeyError: 'yh_color_table'↵")

Ping gave me some suggestions on how to create a custom component？

### Environment
 superset --version                                                      
Python 3.7.8
Flask 1.1.2
Werkzeug 0.16.0

**Comment by junlincc** [comment]
do you mind updating the title to be more human readable? did you build it using dynamically imported viz plugins? @lcyh

**Comment by lcyh** [comment]
已收到，谢谢
