### ISSUE TITLE
[explore] scrolling left-right in dropdown causes layers glitch

### ISSUE THREAD

**Issue by adam-stasiak** [apache/superset#12746]
## Screenshot

https://user-images.githubusercontent.com/25153919/105764047-c14ff100-5f56-11eb-8112-409362f00d0a.mov

## Description

Go to chart Are you an ethnic minority in your city?
Tap on Customize
Click on Number Format dropdown
scroll left-right 

You can see content from layer below dropdown options
I would expect to not see them

**Comment by junlincc** [comment]
thanks for reporting @adam-stasiak! is this the only dropdown that has this behavior?

**Comment by adam-stasiak** [comment]
In other places as well

**Comment by junlincc** [comment]
@ktmud

**Comment by ktmud** [comment]
OK, I need to add a background to the menu.

**Comment by ktmud** [comment]
Thanks for reporting, @adam-stasiak ! I just pushed a fix.
