### ISSUE TITLE
[explore][adhoc filter] "use latest_partition" operator disappeared

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#12752]
in #9637 we added an optional operator for adhoc filter: use latest_partition. It will show up when datasource has single partition. This feature was lost since recent filter redesign work. Note: this feature is not enabled by feature flag. The operator should show up based on the attribute of dataset.

### Before
<img width="1113" alt="80538611-e4fbf180-895a-11ea-9e72-fbd1ebebb7e1" src="https://user-images.githubusercontent.com/27990562/105777614-8a121d80-5f1f-11eb-8532-b4a9524267b7.png">

### Current
 
<img width="1134" alt="Screen Shot 2021-01-25 at 1 32 32 PM" src="https://user-images.githubusercontent.com/27990562/105777689-ae6dfa00-5f1f-11eb-837a-b40d4a730a30.png">

#### How to reproduce the bug

1. Create a new chart from dataset which has single partition
2. Check adhoc filter operators
3. if you can choose use latest_partition, make sure it generate correct custom sql with `latest_partition` template.

### Environment

latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

cc @junlincc @zuzana-vej

**Comment by junlincc** [comment]
Got it!thanks for reporting and sorry about the regression, we will get to it asap. @graceguo-supercat
