### ISSUE TITLE
Timeseries table errors with multiple metrics and no groupby

### ISSUE THREAD

**Issue by michellethomas** [apache/superset#12750]
When you load an existing saved timeseries table with multiple metrics (and no groupby columns) the chart will error with `object of type 'NoneType' has no len()`.

This is an issue with existing saved Timeseries Table charts because they have groupby: null in the form data, new charts created are fine. The stacktrace shows where the error is:

  File "/srv/superset-internal/incubator-superset/superset/views/core.py", line 452, in generate_json
    payload = viz_obj.get_payload()
  File "/srv/superset-internal/incubator-superset/superset/viz.py", line 471, in get_payload
    payload["data"] = self.get_data(df)
  File "/srv/superset-internal/incubator-superset/superset/viz.py", line 833, in get_data
    is_group_by=len(fd.get("groupby", [])) > 0,
TypeError: object of type 'NoneType' has no len()

### Expected results

Chart should load

### Actual results

Chart errors

#### How to reproduce the bug

1. Load an existing time series table chart with multiple metrics and no groupby OR make a new chart with this format and replace `groupby: []` with `groupby: null` in the form data.
2. Run chart and see error.

### Environment

(please complete the following information):

- superset version: master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zuzana-vej** [comment]
This has been brought up by a user a while back (~December).

**Comment by junlincc** [comment]
thanks for filing the issue and the additional info which helps us trouble shooting, we will get to it very soon!

**Comment by michellethomas** [comment]
Hi, Sorry I think I need to do more digging to figure out when exactly this is happening. I see a number of existing charts with this error but creating new charts seems to work. I'll comment when I have more detailed steps to reproduce.

**Comment by michellethomas** [comment]
It looks like this is only an issue on existing time series table charts. These charts have `groupby: null` in the form data where as the new charts have `groupby: []` But I'm going to fix my dev environment so I can get more info later or tomorrow.

**Comment by michellethomas** [comment]
@junlincc looks like it is an issue with existing saved Timeseries Table charts because they have `groupby: null` in the form data, new charts created are fine, sorry for the mixup. The stacktrace shows where the error is (thanks Grace for the stacktrace). I'd put up a quick fix but I'm having trouble with my dev environment at the moment :( 

```
  File "/srv/superset-internal/incubator-superset/superset/views/core.py", line 452, in generate_json
    payload = viz_obj.get_payload()
  File "/srv/superset-internal/incubator-superset/superset/viz.py", line 471, in get_payload
    payload["data"] = self.get_data(df)
  File "/srv/superset-internal/incubator-superset/superset/viz.py", line 833, in get_data
    is_group_by=len(fd.get("groupby", [])) > 0,
TypeError: object of type 'NoneType' has no len()
```

**Comment by junlincc** [comment]
@michellethomas hey Michelle, thanks for the clarification. is it a regression we caused? if so, we are happy to take it on :)

**Comment by michellethomas** [comment]
I don't know what change led to this issue.

**Comment by junlincc** [comment]
@michellethomas got it, thanks for the additional info. we will look into it, since we are not able to reproduce from our end, may ping you for help. how urgent is this issue?

**Comment by michellethomas** [comment]
Yes sounds good let me know if you have any questions about the issue. There is a workaround (users can create a new chart or just add and remove a groupby to get the existing chart to work) so it's not urgent but not ideal to have existing charts breaking. We have it marked in our system as "medium" priority, so maybe P1?

**Comment by michellethomas** [comment]
Hi, FYI I got my dev environment working so I'm going to put up a fix for this issue.

**Comment by junlincc** [comment]
thank you Michelle 🙏 ! owe you a fix! @michellethomas
