### ISSUE TITLE
[explore]chart missing dataset open error msg

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12753]
We want to make sure PRs that introduce UI changes from the community are always welcome without follow strict guideline when they are first created. Design support will follow after these PRs are open if we can't provide Product and Design support upfront. tagging `design-sys-revisit `to track and prevent system level design debt. 

![image](https://user-images.githubusercontent.com/67837651/105782352-34db0980-5f29-11eb-84b6-c4d9df56f8fe.png)

https://github.com/apache/superset/pull/12705

'@junlincc @mihir174 feel free to create another issue to track followups if you want to update the design or copy.'
'A possible followup would be to add "Delete chart" shortcut CTA to make it easier for chart owners to delete outdated charts.'

**Comment by junlincc** [comment]
@ktmud @mistercrunch FYI ^ above is a temporary solution for balancing velocity and design quality, and for keeping OSS product development process transparent and open in the community.

**Comment by mistercrunch** [comment]
@junlincc I like it. 

Seems like the "CHANGE DATASET" button should be styled in orange/warning too to avoid blue-on-orange

**Comment by geido** [comment]
We are cleaning up the labels and trying to reduce the amount. I believe `design:review `is appropriate and generic enough to catch PRs that require design consideration, while `design:proposal `is appropriate for anything that does not require a PR review but design consideration.

**Comment by rusackas** [comment]
Much of this flow has been redesigned/re-engineered since this was open, and I believe the issue has been largely addressed. If there are nuances to the new flow that are perceived as bugs, or need hashing out as a design/feature discussion, let's open fresh Issues and Github Discussions accordingly. Thank you!
