### ISSUE TITLE
Unable to connect to athena and unable to find detailed logs

### ISSUE THREAD

**Issue by dz902** [apache/superset#12765]
Hi,

I followed official guide to use `docker-compose` to start superset.

I added "PyAthena>1.2.0" to `./docker/requirements-local.txt` and then `docker-compose up`, from the log PyAthena was installed correctly.

Then I access Superset, log in and add an database using connection string like `awsathena+rest://AKIAXXXX:XXXXXXXXXX@athena.us-east-1.amazonaws.com/AwsDataCatalog`, only to see:

```
HTTP 422
{
      "message": "Unexpected error occurred, please check your logs for details"
}
```

Then I go to the console and only sees:

```
DEBUG:superset.models.core:Database.get_sqla_engine(). Masked URL: awsathena+rest://AKIAXXXX:XXXXXXXXXX@athena.us-east-1.amazonaws.com/AwsDataCatalog
DEBUG:superset.stats_logger:[stats_logger] (incr) DatabaseRestApi.test_connection.error
DEBUG:superset.stats_logger:[stats_logger] (timing) DatabaseRestApi.test_connection.time | 7.465301001502667
172.19.0.1 - - [26/Jan/2021 09:55:03] "POST /api/v1/database/test_connection HTTP/1.1" 422 -
INFO:werkzeug:172.19.0.1 - - [26/Jan/2021 09:55:03] "POST /api/v1/database/test_connection HTTP/1.1" 422 -
```

With no further info. No matter what I use for the connection string after `rest://` I get the same error.

I searched for a long time and was to no avail.

Is there a way to debug this situation? Thanks.

**Comment by dz902** [comment]
Just found that the appending of `?s3_staging_dir=s3://xxx` is required to make it work.

Still I think this could use a better error message. Not sure whether this is to be done by the connector or superset.

Closing now.

**Comment by junlincc** [comment]
@srinify
