### ISSUE TITLE
Unable to change Time Range: Access is Denied

### ISSUE THREAD

**Issue by gorcurek** [apache/superset#12769]
While trying to create a chart for my dataset on the new **1.0** version of superset, for no apparent reason, I cannot change Time Range because I am getting an Access Denied error.

The **DATETIME** column in table is a TIMESTAMP format column of **Impala**.

I am able to query the table without any problems.

The table itself is an Impala table, connection provided by Impyla driver.

#### Screenshots

![why](https://user-images.githubusercontent.com/62286967/105857360-813a4e00-5fea-11eb-9426-88968f93614b.png)

### Environment

- superset version: 1.0
- python version: 3.7.4

**Comment by junlincc** [comment]
what's your permission setting in Superset? @gorcurek

**Comment by gorcurek** [comment]
Hi,

I have **Admin** role, as seen here:

![my-profile](https://user-images.githubusercontent.com/62286967/106138792-e027d080-616c-11eb-953d-4f79ca0120b5.png)

And these are the permissions for **Admin** role:

![admin-role](https://user-images.githubusercontent.com/62286967/106138902-051c4380-616d-11eb-8a59-77a1f6e964ec.png)

The other role I have, **Public**, has No permissions.

**Comment by junlincc** [comment]
time picker added a new api which requires running `superset init` to grant new permission. lmk if that works

**Comment by mbiberhofer** [comment]
Just FYI, we had the same issue and running `superset init` fixed it. Thanks for the advice!

**Comment by junlincc** [comment]
@zhaoyongjie Please open a PR to grant viewer/public access right as well. let's talk about permission setting for native filter in the near future.
