### ISSUE TITLE
[explore]specify Inclusive start, exclusive end in Timepicker Advanced input 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12784]
The actual time range that generated by new time picker in Explore sets Start date/time - inclusive and End date/time  - exclusive in all time range setting mode(e.g. last week => 2021-01-20 ≤ col < 2021-01-27, previous year => 2020-01-01 ≤ col < 2021-01-01). 
This has been the behavior in Superset since [SIP15](https://github.com/apache/superset/issues/6360) which ensures time Intervals consistency. Based on the amount of research conducted and user feedback, we agree that this should be a standard default behavior across all verticals in Superset for the long term.  

Feature request: In the time picker popover Advanced range type, we should specify that user's date string input in Start will be interpreted as inclusive, vs. date string in End will be interpreted as exclusive.  Design input is needed. 

<img width="586" alt="Screen Shot 2021-01-26 at 6 22 06 PM" src="https://user-images.githubusercontent.com/67837651/105934835-c7e97180-6005-11eb-8ebb-1ba98a1922f8.png">
Custom as well
<img width="587" alt="Screen Shot 2021-01-26 at 6 42 30 PM" src="https://user-images.githubusercontent.com/67837651/105935189-607ff180-6006-11eb-85ab-47d835787428.png">

Related projects are considering - 
1. Allow user to set time interval preference at system level 
2. Allow user to set time zone at system level

cc @mihir174 @zhaoyongjie @john-bodley

**Comment by john-bodley** [comment]
@junlincc I was thinking something of the form:

<img width="588" alt="Screen Shot 2021-01-27 at 3 43 45 PM" src="https://user-images.githubusercontent.com/4567245/105935239-7a790d00-60b6-11eb-8e80-18a2653c5213.png">

The time interval preferences and time zone topics should definitely be discussed via a SIP. 

The later is quite nuanced as there may be numerous times zones in consideration, i.e., i) the reference time zone of the data (e.g. what actual period a date represents), ii) the time zone of the Superset server (which is likely being used for all the server-side timestamps and the materialization of "now"), and iii) the time zone of the client. 

Ideally having (i), (ii), and (iii) use the safe reference is ideal and it ensures consistency throughout. It would be quite problematic if a chart was rendered based on the client time zone as two people in two different time zones would be seeing different renderings of the same chart.

**Comment by junlincc** [comment]
Thank you, John for your input! Agreed, both topics deserve a SIP to iron out all the considerations, possible solutions and their pros and cons. I consider time zone setting is a very important piece in Superset's international product strategy. I will do some research and put together a SIP soon. 
@john-bodley

**Comment by mihir174** [comment]
Hey, here's how tooltips can be set up to clarify the inclusion/exclusion of start and end dates after details are ironed out in the SIP(s).
![Slice 2](https://user-images.githubusercontent.com/64227069/106074857-72729a80-60c1-11eb-92a8-dfaece027825.png)

**Comment by ktmud** [comment]
@mihir174 I think John's proposal is cleaner and easier to comprehend. Users don't have to hover and it'd be more direct to see the difference between these two fields. What do you think of adding both the tooltips and the label change?

Btw, should we also replace "start date" with "start time" just to be consistent?

**Comment by junlincc** [comment]
i'm not sure regular users can easily understand the meaning of Start (inclusive) and End (exclusive). tooltips to explain what they actually mean could be helpful. @mihir174
