### ISSUE TITLE
Build charts on top of SQL queries

### ISSUE THREAD

**Issue by vlavorini** [apache/superset#12791]
**Is your feature request related to a problem? Please describe.**
I need to visualize the results of a query on periodic base

**Describe the solution you'd like**
I would like to create a chart to publish on a dashboard with the data which comes out of a query. That query should run periodically

I did not found suggestions in the documentation, and also generic search engines does not help.

**Comment by zhaoyongjie** [comment]
hi @vlavorini 
Do you want to dynamically generate Dashboard based on the SQL query?

**Comment by vlavorini** [comment]
exactly!

**Comment by junlincc** [comment]
@vlavorini This is something on our radar. could you elaborate your use case? that will help us prioritize. Thanks!

**Comment by vlavorini** [comment]
Sure!

The data we have to chart comes from joins and selections of three different tables.

As of today the analytics team uses Python scripts to make queries and create charts 'on demand'.

We already tried Bokeh, but it's too limited since it does not allow the stakeholders to make new charts based on their desires.

So, we would like to use a proper BI tool, like Superset, to can allow stakeholders to create/modify charts based on their intuition/fantasy/needs of the moment, without using developers' time.


P.S.

Maybe the most easy and coherent way is to use the results of a SQL query as "Datasource" for "Datasets"?

**Comment by rumbin** [comment]
I'm having trouble understanding this question.
In my understanding, you want your userst to be able to run arbitrary SQL queries and build charts out if them, so these charts can be out on a dashboard.
This is the standard workflow in SQLlab. You prepare a query there and when you are happy with the result,you click Visualize and create a chart out of it.
Or am I misunderstanding your demand entirely?

**Comment by eugeniamz** [comment]
I think that this can be done with Virtual Dataset. I did a [demo](https://youtu.be/UNSg4sye19M) for it, please let me know if I am missing something.

**Comment by vlavorini** [comment]
Actually this was exactly what I needed. I'm sorry to have not found it by myself.

**Comment by marituhone** [comment]
@EugeneTorap  @junlincc  @vlavorini how did you  solve it  i cant find the video too.....my requirement is writing Query on the sql lab and change that to chart but  i want parameters to be passed dynamically how can i do that (how do we pass parameters to the sql in other toolt it is passed from filter).
