### ISSUE TITLE
Unable login to the Superse when enabled CORS

### ISSUE THREAD

**Issue by weihaonan** [apache/superset#12790]
sueprset设置cors后，用qiankun引入一个主应用中，entry路径设置的是http://127.0.0.1:5000/login/?REMOTE_USER=admin，superset跳转到http://127.0.0.1:5000后报错 ，跨域了，有哪位大神知道如何解决

**Comment by zhaoyongjie** [comment]
Hi @weihaonan 
what is `qiankun`

In chinese
请填充问题模版. 多谢.
什么是 qiankun ?

**Comment by junlincc** [comment]
@zhaoyongjie thanks Yongjie for interacting with users. with your help i think Superset if ready to serve more users across the Pacific. 🙏

@weihaonan and yes please fill out the issue template in English or Chinese as much as you can, so that we can help! thanks!

**Comment by weihaonan** [comment]
@zhaoyongjie 官网的介绍：Qiankun is an implementation of Micro Frontends, which based on single-spa. It aims to make it easier and painless to build a production-ready microfront-end architecture system.
 i want to lead superset into qiankun as a sub application

**Comment by junlincc** [comment]
@suddjian  ^^^^^

**Comment by junlincc** [comment]
not sure how we could help you. but you need to use SSO on Superset, can consider our [cloud offering](https://preset.io/)

**Comment by amitmiran137** [comment]
There are quite a few which are using superset embedded in an iframe within another frontend application with SSO in a standalone mode

If you configure it correctly all should work for you
