### ISSUE TITLE
Cannot find Alerts/Reports tab in superset

### ISSUE THREAD

**Issue by singh-ab** [apache/superset#12794]
Following the tutorial at - https://superset.apache.org/docs/installation/installing-superset-using-docker-compose

I was able to get the superset UI

### Expected results

Alerts/reports option in settings menu

### Actual results

Alerts/reports option not visible 

#### Screenshots

![image](https://user-images.githubusercontent.com/70583041/106008788-f0ca3f00-60b7-11eb-92db-345473d10faa.png)

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zhaoyongjie** [comment]
Hi @singh-ab 
please check `config.py` or other config files. 

```
### default setting is False, please switch this setting to True
ENABLE_ALERTS = True
```

then run the following command to grant view permission
````
superset init
````

**Comment by dpgaspar** [comment]
Note that `ENABLE_ALERTS` is for the old implementation, for the new implementation included on 1.0.0 enable the feature flag: `ALERT_REPORTS`

https://github.com/apache/superset/blob/master/superset/config.py#L343

**Comment by singh-ab** [comment]
Thanks @zhaoyongjie and @dpgaspar !

@dpgaspar : I see that - https://github.com/apache/superset/blob/master/superset/config.py#L343 has both options `ENABLE_ALERTS` and `ALERT_REPORTS` in the latest master branch . 

are they related ? and how ?

**Comment by singh-ab** [comment]
Enabling `ENABLE_ALERTS =True` works for me on superset  - 1.0.0 . Wondering maybe `ALERT_REPORTS` is for the reports tab in this image - https://github.com/apache/superset/blob/master/RELEASING/release-notes-1-0/media/alerts_reports_2.png ? but that doesn't work.

**Comment by Asturias-sam** [comment]
@singh-ab  can you please post your config file not able to see the alerts tabs after configuring ENABLE_ALERTS =True

**Comment by dpgaspar** [comment]
@Asturias-sam have you done `superset init` after?

**Comment by singh-ab** [comment]
@Asturias-sam : there is a new menu for `Alerts and Reports` and I am using it . 
something like - https://docs.preset.io/docs/alerts-reports 

to have that enabled you can need to a have a `feature flag`  in your config . 

```
FEATURE_FLAGS = { 
    "ALERT_REPORTS": True,
    }
```

post this you need to `superset init` .

**Comment by Asturias-sam** [comment]
@singh-ab @dpgaspar 
I am using superset  Version: 1.0.0, below is my configuration 

```
ENABLE_ALERTS =True
ENABLE_SCHEDULED_EMAIL_REPORTS = True
FEATURE_FLAGS = {
    "ALERTS_REPORTS": True,
    "THUMBNAILS": True
}
```
I have done superset init  but still the Alerts are not visible
![Uploading Screenshot 2021-02-15 at 3.29.10 PM.png…]()

**Comment by singh-ab** [comment]
for checking on the `ENABLE_ALERTS`  some logs would help , can you post them here? 

while for `Alerts & Reports` menu I see that `ALERTS_REPORTS` has a typo , it should be `ALERT_REPORTS` . Can you retry the steps after fixing that ?

**Comment by louisjanin** [comment]
It would be easier to have a full docker image with this feature ready to be deployed no ? The setup is a bit of a struggle

**Comment by zhaoyongjie** [comment]
@louisjanin Some functions are experimental functions, so hidden in feature flag

**Comment by louisjanin** [comment]
@zhaoyongjie yes it's true I can't wait for this to be an official feature :) but it seems to require more than the feature flag to work (webdriver, celery, beat, etc).

**Comment by fancyfreeman** [comment]
You should set the environment vairable export SUPERSET_CONFIG_PATH=$/PATH/config.py first, then run superset init command

**Comment by tiran23** [comment]
check your "List Roles" and include point of alerts\reports menu in list of the role
