### ISSUE TITLE
[docs]API docs not clear about /dashboard/import

### ISSUE THREAD

**Issue by ktecho** [apache/superset#12808]
In the [documentation page about the API](https://superset.apache.org/docs/rest-api), there should probably be an entry about the import of dashboards: /api/v1/dashboard/import

That url is working, so I think it's lacking in the docs. It would be good to know the parameters that I need to pass to import dashboards programmatically.

**Comment by dpgaspar** [comment]
@ktecho thank you for reporting,

We will fix it, meanwhile you can access online API docs by accessing your superset on `api/v1/swagger/v1`

**Comment by ktecho** [comment]
For me it seems the online API docs are at just `/swagger/v1`. But thanks! That will help :)

**Comment by srinify** [comment]
Closing! It looks like this has since been updated!

![image](https://user-images.githubusercontent.com/801507/115878419-86a30b00-a416-11eb-9a2a-ef36c04f3bb9.png)
