### ISSUE TITLE
[explore]metrics list order should not change after editing metrics

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12802]
Currently, after user editing a metric in Edit dataset modal in Explore, the edited metric jump to the bottom of the metric list. 
it create a few issues: 
1) when the metric list is long, by dropping to the bottom, user might take a while to find it or think the most recent edited metic is lost. 
2) every time users edit a single metric, they see a different order of metric list showing in the panel, which can be confusing

Proposed short-term change: the metric list should be arranged in the order of creation time

https://user-images.githubusercontent.com/67837651/106104741-aff21a80-60f7-11eb-9f5d-4d874b1bd152.mov

**Comment by anushkrishnav** [comment]
If it hasn't been solved already , I can take up on it, is there any example I can refer to ?
