### ISSUE TITLE
sql lab--Database Error-Instance <Query at 0x1b00c574070> 

### ISSUE THREAD

**Issue by liuxp311** [apache/superset#12803]
SQL LAB --RUN:

Database Error
Instance <Query at 0x1b00c574070> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: http://sqlalche.me/e/13/bhk3)

**Comment by junlincc** [comment]
do you mind filling out the issue template? thanks! @liuxp311

**Comment by liuxp311** [comment]
close,the same question
