### ISSUE TITLE
[import]Importing a dashboard via API fails with error 500

### ISSUE THREAD

**Issue by ktecho** [apache/superset#12814]
While importing an exported dashboard (.json file) from an older version of Superset (0.36.0) through the API of a Superset 1.0.0 (using built in Swager), it errors out with Error 500 and this trace:

```
File is not a zip file
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_appbuilder/api/__init__.py", line 84, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/superset/views/base_api.py", line 79, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/superset/utils/core.py", line 1286, in time_function
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/superset/dashboards/api.py", line 705, in import_
    with ZipFile(upload) as bundle:
  File "/usr/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
127.0.0.1 - - [28/Jan/2021 14:37:07] "POST /api/v1/dashboard/import/ HTTP/1.1" 500 -
```

From the documentation, it seems that it should just accept the .json file and not need a .zip, but just in case the file should be .zipped, I made a .zip file and now the error changes:

```
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_appbuilder/api/__init__.py", line 84, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/superset/views/base_api.py", line 79, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/superset/utils/core.py", line 1286, in time_function
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/superset/dashboards/api.py", line 712, in import_
    json.loads(request.form["passwords"])
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
127.0.0.1 - - [28/Jan/2021 14:38:06] "POST /api/v1/dashboard/import/ HTTP/1.1" 500 -
```

### Expected results

My dashboard imported without problems.

### Actual results

At first, trying to import .json file, the error is: `zipfile.BadZipFile: File is not a zip file`
After zipping the exported dashboard, the error is: `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

#### How to reproduce the bug

1. Go to an older Superset (0.36.0)
2. Navigate to the `Dashboards` menu, then click over one of your dashboards then `Actions / Export`. Save the .json file.
3. Go to Superset 1.0.0 in a different machine
4. Navigate to the function `/dashboard/import/` in http://localhost:8180/swagger/v1
5. Choose the previously exported dashboard for the `formData` parameter and click Execute
6. You get the aforementioned bugs.

### Environment

- superset version: 1.0.0
- python version: 3.8.5
- node.js version: none

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by ktecho** [comment]
Now the entire description is ready.

**Comment by junlincc** [comment]
@betodealmeida Beto, mind helping? thanks!

**Comment by ktecho** [comment]
I've been checking the export dashboard in Superset 1.0.0 and it doesn't export a zip file.

So I've tested an empty dashboard export in 1.0.0 and import in the same installation (1.0.0) and that doesn't work.

**Comment by ktecho** [comment]
While looking at this, I found the Superset CLI, and it seems the dashboard stuff is not coherent:

```
root@docker_host:/# superset | grep dashboard
  export-dashboards         Export dashboards to JSON
  import-dashboards         Import dashboards from ZIP file
```

If the export is in JSON format (like in previous versions or when using the UI), the import should be JSON too, right?

**Comment by ktecho** [comment]
But using the command line, in the end works ok for JSON files this way:

`superset import-dashboards -p nyc.json`

So the API is broken (asks for a zipfile), but the CLI just have the description wrong:

`import-dashboards         Import dashboards from ZIP file`

should be:

`import-dashboards         Import dashboards from JSON file`

**Comment by ktecho** [comment]
Also, from the error messages during the process, I infered that you need `Pillow` module installed. Just in case you want to put it in the documentation somewhere.

I don't know why you need an image manipulation module to import a .json file into the database, but that's another story :)

**Comment by sann05** [comment]
I've debugged importing/exporting databases and dataset endpoints and that is what I figure out:
 - None of the export features works as expected
 - Zero documentation
 - If you do not debug into import endpoints you have 0 chance to prepare the appropriate file.
 
Why the hell airflow has 22.3k stars and much more stable documented than this almost 40k starred repo?

**Comment by rusackas** [comment]
Hi all! Sorry to be "that guy" but I'm closing this as stale since it fell through the cracks long ago, and is a little difficult to reconcile at this point. Most folks are using Superset with the `VERSIONED_EXPORT` feature flag turned on now, which is working pretty darn smoothly these days. I'd recommend that. 

Otherwise, it's _likely_ this has already been quietly resolved anyway. If folks are still having difficulties with the flag turned OFF in current era Superset (e.g. 2.0.x or on `master`) let's open a fresh Issue and update the context so we can tackle it more actively. Thanks!
