### ISSUE TITLE
[explore] missing saved metrics from the dropdown list 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12825]
In latest master, open METRICS popover, see missing saved metrics from the dropdown select. 

To reproduce: 

- Open any charts that use sample data(e.g. FCC2018 Survey)
- Go to Edit dataset. in metric tab, create 3 new metrics and Save
- Go back to the control panel, click the pre-filled saved metric in METRICS
- Save tab, click dropdown, see list missing the original one,

**Actual** 

https://user-images.githubusercontent.com/67837651/106222980-7112a200-6195-11eb-8652-8c8afb796876.mov

**Expected**
<img width="737" alt="Screen Shot 2021-01-28 at 6 08 30 PM" src="https://user-images.githubusercontent.com/67837651/106222908-4aed0200-6195-11eb-807d-2e64ee0cf909.png">

**Comment by villebro** [comment]
IMO this is working as intended - a selected saved metric should not be featured in the dropdown list to avoid duplication.

**Comment by ktmud** [comment]
Maybe we can add only the current selected metric in the list (with a selected state of course) just to avoid surprises?

**Comment by junlincc** [comment]
reopening. confirmed this is a regression 
<img width="1551" alt="Screen Shot 2021-01-29 at 8 48 34 AM" src="https://user-images.githubusercontent.com/67837651/106303339-e078a800-620e-11eb-900f-03ed7fab6f1b.png">
