### ISSUE TITLE
Error running SQL Lab

### ISSUE THREAD

**Issue by liuxp311** [apache/superset#12824]
Error running SQL Lab

### Expected results
Error message：

Database Error
Instance <Query at 0x1b00c574070> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: http://sqlalche.me/e/13/bhk3)

### Actual results

Unable to query

#### Screenshots

Database Error
Instance <Query at 0x1b00c574070> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: http://sqlalche.me/e/13/bhk3)

#### How to reproduce the bug

1. open sql lab
2. run
4. See error  :
Database Error
Instance <Query at 0x1b00c574070> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: http://sqlalche.me/e/13/bhk3)
### Environment

(please complete the following information):

- superset version: `superset version  1.0.0`
- python version: `python --version3.8.6`
- node.js version: `node -v12 1.8`

**Comment by liuxp311** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\13264\desktop\test\python\superset\venv\lib\site-packages\superset\views\base.py", line 180, in wraps
    return f(self, *args, **kwargs)
  File "c:\users\13264\desktop\test\python\superset\venv\lib\site-packages\superset\utils\log.py", line 164, in wrapper
    value = f(*args, **kwargs)
  File "c:\users\13264\desktop\test\python\superset\venv\lib\site-packages\superset\views\core.py", line 2418, in sql_json
    return self.sql_json_exec(request.json, log_params)
  File "c:\users\13264\desktop\test\python\superset\venv\lib\site-packages\superset\views\core.py", line 2564, in sql_json_exec
    return self._sql_json_sync(
  File "c:\users\13264\desktop\test\python\superset\venv\lib\site-packages\superset\views\core.py", line 2403, in _sql_json_sync
    logger.exception("Query %i failed unexpectedly", query.id)
  File "c:\users\13264\desktop\test\python\superset\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 294, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "c:\users\13264\desktop\test\python\superset\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 725, in get
    value = state._load_expired(state, passive)
  File "c:\users\13264\desktop\test\python\superset\venv\lib\site-packages\sqlalchemy\orm\state.py", line 652, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "c:\users\13264\desktop\test\python\superset\venv\lib\site-packages\sqlalchemy\orm\loading.py", line 942, in load_scalar_attributes
    raise orm_exc.DetachedInstanceError(
sqlalchemy.orm.exc.DetachedInstanceError: Instance <Query at 0x22638334df0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: http://sqlalche.me/e/13/bhk3)
INFO:werkzeug:127.0.0.1 - - [31/Jan/2021 10:48:14] "POST /superset/sql_json/ HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [31/Jan/2021 10:48:14] "GET /superset/queries/1612060970962.423 HTTP/1.1" 200 -

**Comment by eugeniamz** [comment]
which database do you use?

**Comment by liuxp311** [comment]
1)mysql or sqlite,the same question,2)Environment:Virtual environment    python -m venv venv

**Comment by liuxp311** [comment]
> which database do you use?

1)mysql or sqlite,the same question,2)Environment:Virtual environment python -m venv venv

**Comment by beautah** [comment]
I'm seeing the same issue using an oracle db connection, my python version is 3.8.4, using conda for env, but same set up otherwise.

**Comment by jokus-pokus** [comment]
Same issue here using a SQL Server and Apache Superset on Windows.
Everything works fine but i cant query in SQL Lab.
What can i do there to bound my query to a Session?

Thanks in advance!

**Comment by liuxp311** [comment]
@eugeniamz :can help to solve this question?

**Comment by liuxp311** [comment]
@ryw :can help to solve this question?

**Comment by mohimirza** [comment]
@liuxp311 @beautah The problem seems to be caused by SIGALRM. Here is a workaround which has worked for me.
In **Lib\site-packages\superset\utils\core.py** replace:

```
  def __enter__(self):
      try:
          signal.signal(signal.SIGALRM, self.handle_timeout)
          signal.alarm(self.seconds)
      except ValueError as e:
          logger.warning("timeout can't be used in the current context")
          logger.exception(e)

  def __exit__(self, type, value, traceback):
      try:
          signal.alarm(0)
      except ValueError as e:
          logger.warning("timeout can't be used in the current context")
          logger.exception(e)

```

with

```
    def __enter__(self):
        try:
            #signal.signal(signal.SIGALRM, self.handle_timeout)
            #signal.alarm(self.seconds)
            pass
        except ValueError as e:
            logger.warning("timeout can't be used in the current context")
            logger.exception(e)

    def __exit__(self, type, value, traceback):
        try:
            #signal.alarm(0)
            pass
        except ValueError as e:
            logger.warning("timeout can't be used in the current context")
            logger.exception(e)
```

**Comment by beautah** [comment]
Nice! Thanks for that @mohimirza , but I've decided to go ahead and get this set up on my linux server and keep it within the realm of supported devices, might just have to use this trick to have a working local development version though, it certainly works!

**Comment by liuxp311** [comment]
ok

**Comment by liuxp311** [comment]
ok

**Comment by liuxp311** [comment]
ok
