### ISSUE TITLE
[explore][ux]prompt user to save edited chart before leaving the page

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12826]
UX enhancement: after editing a chart, users leave from Explore to other product area without knowing their changes have been saved or not.(current behavior - not saved).
proposed change: if a chart is edited, before users leave Explore page, they should receive a message to confirm either to save or to abort changes. 

https://user-images.githubusercontent.com/67837651/106237595-fa38d180-61b3-11eb-8d6c-4a505d142769.mov

**Comment by rusackas** [comment]
This is done, thanks to @kgabryje!
