### ISSUE TITLE
Option to select limited values of filter

### ISSUE THREAD

**Issue by cnuonline** [apache/superset#12843]
*Please make sure you are familiar with the SIP process documented*
(here)[https://github.com/apache/superset/issues/5602]

### There are few usecases where the data sliced (pre-prepared) should not have multiple selection of filter values.

Description of the problem to be solved.

### Proposed Change

Dashboard filters should have option to select  the number of filter values associated to it.

**Comment by junlincc** [comment]
> having Radio button or dropdown or limit the user to select filter values

@cnuonline  it seems to me this is a proposal of UI change in filterbox, could you provide a wireframe? thanks!

**Comment by suddjian** [comment]
Closing this, feel free to reopen with more details if there is still an unsupported use case.
