### ISSUE TITLE
Update CTAS Schema from text field to a dropdown

### ISSUE THREAD

**Issue by yousoph** [apache/superset#12842]
## Description
Current CTAS Schema field is a text field but users need to input the name of an existing schema for CTAS/CVAS to work as expected. 
Instead of requiring the user to input the schema name, we should update the text field to a dropdown list of existing schemas
(This is a follow up to Issue #12470) 

## Screenshot
![Add Modal - SQL Lab Settings @1456 (1)](https://user-images.githubusercontent.com/10627051/106341138-07f06480-6251-11eb-961b-9c5bdf86dac4.jpg)

https://www.figma.com/file/NbuTOMaUdv2GCBoDyihdLw/Database-CRUD---P0?node-id=479%3A39226

**Comment by mistercrunch** [comment]
I think it's a jinja-templated field and allows something like `sandbox-{username}`, let's make sure to cover that use case and make it clear the help-text underneat!

**Comment by mistercrunch** [comment]
BTW this field is not used very often and typically only by admins, so it's probably not a big deal to have them type the name, still nice-to-have.

**Comment by Steejay** [comment]
@mistercrunch just to clarify, users can actually _create_ new schemas in this field not just select existing schemas?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue/Discussion/PR to address the problem.
