### ISSUE TITLE
Problem upgrading Superset from 0.38.0 (python 3.6) to 1.0.0 (python 3.8)

### ISSUE THREAD

**Issue by JeanBaptisteINITIATIVES** [apache/superset#12856]
Hi,

I'm facing an issue upgrading Superset from 0.38.0 to 1.0.0. Currently I have a 0.38.0 Superset version installed in a virtual env, on a Linux Ubuntu 18.04 server, with python 3.6. To upgrade to the new major 1.0.0 release, I have to upgrade to python 3.7 to make it works. For this reason, I upgraded the development server to an Ubuntu 20.04 with a python 3.8 distribution. But I can't find how to upgrade the Superset installation, how to upgrade the virtual environment with the Superset install...
Do I have to reinstall Superset from scratch ?

Any help will be appreciated ;-)

Best regards

**Comment by dpgaspar** [comment]
@JeanBaptisteINITIATIVES you don't have to install superset from scratch (it would be nice from a immutable infrastructure perspective). You need to update/reinstall superset's virtual environment, install superset, upgrade the db, superset init. The normal install steps

Note: Superset 1.0.0 has a dependency problem on python 3.8 and PyJWT, so use python 3.7 or pin PyJWT at 1.7.1

**Comment by JeanBaptisteINITIATIVES** [comment]
Hi @dpgaspar,

Thanks for the reply, I'll do all these steps and give some feedback if I encounter some problem during this process.

Best regards

**Comment by JeanBaptisteINITIATIVES** [comment]
For anyone concerned by kind of upgrading (Python + superset), following the install steps worked fine :
- reinstall the superset's virtual environment
- install superset (pip install apache-superset --upgrade)
- upgrade the db, changing if needed the sql alchemy url in the config.py file (superset db upgrade)
- initiate superset (superset init)
