### ISSUE TITLE
Table chart show raw records number columns become normalized value

### ISSUE THREAD

**Issue by hkfreenet** [apache/superset#12853]
Table chart show raw records number columns become normalized value

### Expected results

The number columns should be shown the same as value from db without normalized

### Actual results

The number columns become normalized value (no any setting can change the number columns)

#### Screenshots

![image](https://user-images.githubusercontent.com/621561/106406385-123e7880-6474-11eb-9b1b-45ec855c9201.png)

### Environment

Using superset v1.0  with postgresql db

**Comment by ktmud** [comment]
We are working on adding adhoc column formatting. For now you can specify custom d3 format in saved metrics/columns:

<img width="940" alt="custom-format" src="https://user-images.githubusercontent.com/335541/106410182-2001e880-63f7-11eb-860a-4b829c51456a.png">

**Comment by ktmud** [comment]
Hmm, I think I misunderstood what this bug was about earlier. Will push a fix soon.

**Comment by junlincc** [comment]
sorry this is a real P0.... @ktmud 🙏

**Comment by villebro** [comment]
Hmm, the fix should not affect 1.0, as it's not using the new table chart plugin that's on master, in which I assume the regression was.

**Comment by junlincc** [comment]
confirmed yes, not as reported in the issue. this bug is not affecting 1.0, I will revote
