### ISSUE TITLE
[database connection]Bar Chart with Presto does not add ORDER BY when using limit rows 

### ISSUE THREAD

**Issue by eugeniamz** [apache/superset#12850]
When creating a bar chart with the source database Presto / Athena, the SQL does not include ORDER BY with LIMIT rows. Not having ORDER BY with LIMIT does not warrant that the right data is shown. 

``` 
SELECT "country" AS "country",
       sum("new_cases") AS "SUM(new_cases)"
FROM "default"."cases_ts"
GROUP BY "country"
LIMIT 100
```
<img width="1010" alt="Screen Shot 2021-01-31 at 11 09 45 AM" src="https://user-images.githubusercontent.com/58375897/106390129-e6a88900-63b4-11eb-9886-841b55194114.png">

I tried Bar Chart with Vertica and the ORDER BY shows. 

I changed the chart to Pie with Presto Datasource and the ORDER BY Also shows 
```
SELECT "country" AS "country",
       sum("new_cases") AS "SUM(new_cases)"
FROM "default"."cases_ts"
GROUP BY "country"
ORDER BY "SUM(new_cases)" DESC
LIMIT 100
```
<img width="1101" alt="Screen Shot 2021-01-31 at 11 07 58 AM" src="https://user-images.githubusercontent.com/58375897/106390100-c4af0680-63b4-11eb-852b-a8fb6a659833.png">

#### How to reproduce the bug

1. Go to - Chart and select a datasource that is from Presto query engine and chart type ```bar chart```. Review query and query won't have the order by 
2. Change the chart type to ```Pie```, review the query and it will include the ORDER BY 

### Environment
Superset 1.0 
Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ X] I have reproduced the issue with at least the latest released version of superset.
- [ X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by KentonParton** [comment]
@eugeniamz thank you for adding this item.

It appears to be impacting Redshift, Postgres, and MySql in addition to Presto/Athena. There may be more databases.

To keep charts consistent, should we add a “Sort Descending” toggle as we have on the “Time-series Bar Chart”?

**Comment by junlincc** [comment]
Thank you both for reporting with details. We will look into it.
@zuzana-vej I know you guys use Presto, is it also affecting you? 

https://github.com/apache/superset/pull/12661 should be able to solve the sort descending issue, I will double check when can it get to next minor release. @KentonParton @eugeniamz

**Comment by daniel10012** [comment]
@KentonParton I have tested it on Postgres, Redshift, and MySQL and the Order By appears for bar charts and pie charts for me:
![image](https://user-images.githubusercontent.com/10360991/106406472-5cd5db80-6407-11eb-93be-969fbeaa3f6e.png)

@eugeniamz @junlincc

**Comment by zhaoyongjie** [comment]
@KentonParton I have tested it on Presto(0.235-cb21100), the query with `order by` and `limit` clause

![image](https://user-images.githubusercontent.com/2016594/106423324-2e094500-649b-11eb-8532-f1641804e249.png)

![image](https://user-images.githubusercontent.com/2016594/106423240-06b27800-649b-11eb-9685-80fbf1e04588.png)

**Comment by KentonParton** [comment]
@daniel10012 @zhaoyongjie  I have checked in LINT and LIVE environment and not seeing order by in the query as shown below. I am running release 1.0.0. Are there any recommendations to resolve this?

**Redshift/Postgres**
<img width="890" alt="Screen Shot 2021-02-01 at 11 29 12 AM" src="https://user-images.githubusercontent.com/20202312/106440003-3bf5a080-6470-11eb-85d7-f9e7d4665fa4.png">

**Athena**
![image](https://user-images.githubusercontent.com/20202312/106440224-824aff80-6470-11eb-8aab-32c46ce9d35a.png)

**Comment by zhaoyongjie** [comment]
@KentonParton @eugeniamz 
I reproduced this bug in 1.0, but the latest master code works fine. 

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/2016594/106463492-742dcb00-64d2-11eb-99fc-832e51f01bac.png">

![image](https://user-images.githubusercontent.com/2016594/106463552-8d367c00-64d2-11eb-9935-942e418fa9a7.png)

**Comment by KentonParton** [comment]
Thanks for verifying @zhaoyongjie

**Comment by bryanck** [comment]
FYI, this also impacts the word cloud chart, and the line charts that use group by. See:
https://github.com/apache/superset/pull/12674

**Comment by rusackas** [comment]
@villebro @beto @zhaoyongjie can any of you confirm whether this is still an issue or if it should be closed?

**Comment by villebro** [comment]
This issue is resolved
