### ISSUE TITLE
Presto incorrect order of column type mappings

### ISSUE THREAD

**Issue by rmgpinto** [apache/superset#12860]
Presto has incorrect order of column type mappings.
`timestamp` is overriden with `time` due to these lines:

```
(re.compile(r"^time.*", re.IGNORECASE), types.Time()),
(re.compile(r"^timestamp.*", re.IGNORECASE), types.TIMESTAMP())
```

causing incorrect query statement to be passed from superset to presto.

### Expected results

Query statements to have correct column type/cast.

### Actual results

The query is incorrect.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zuzana-vej** [comment]
has linked merge PR, assuming that this issue is resolved
