### ISSUE TITLE
Superset 1.0.0 load balancer unable to login

### ISSUE THREAD

**Issue by vineetalagh** [apache/superset#12866]
We have deployed Superset on EKS Load balancer but login doesn't work. 

### Expected results

Load balancer should work.
 
### Actual results

Getting different errors when trying to login to superset:

- Login doesn't work and page reloads.
- Login Failed when trying to login with correct admin credintals.
- The CSRF token is missing.

#### Screenshots

![image](https://user-images.githubusercontent.com/62997477/106461576-db289100-648c-11eb-8938-b4a26cb45e1d.png)

#### How to reproduce the bug

Pick up the latest 1.0.0 tag and deployed it behind a load balancer.

### Environment

- superset version: 1.0.0
- python version: 3.8
- node.js version: 12

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I have made the following changes in superset config

```python
WTF_CSRF_ENABLED = True

WTF_CSRF_EXEMPT_LIST = []

ENABLE_PROXY_FIX = True
```

Gunicorn Config 

```
bind = "0.0.0.0:8088"
workers = 10
threads = 4
timeout = 120

limit_request_line = 4094
limit_request_field_size = 8190
```

**Comment by emellojr** [comment]
Hi @vineetalagh! Did you solve the issue? I've the same problem, but in the superset 1.0.1.

Tks!!
