### ISSUE TITLE
Unable to send Dashboard emails

### ISSUE THREAD

**Issue by vinitpradhn18** [apache/superset#12863]
Hi I am unable to send Dashboard email with superset Docker installation at dev environment. I also have installed geckodriver in superset_worker container and set WEBDRIVER_BASEURL = "http://0.0.0.0:8088/"  from issue #9135
### Expected results

Receive reports by email
#### Screenshots

![Screenshot 2021-02-01 at 6 11 11 PM](https://user-images.githubusercontent.com/8949913/106460234-045f1680-64b9-11eb-841c-bda1c2899537.png)

#### Steps to reproduce

1. Navigate to superset folder
2. Run docker-compose up -d
3. Navigate to superset_worker container and Install geckodriver
4. Configure SMTP at superset/config.py and set Enable Alerts = True
### Environment

- superset version: `1.0`
- python version: `3.7.9`

How do I authenticate Webdriver? Didn't find any reference for it. Any help would be appreciated

**Comment by github-wcha** [comment]
Sorry, I couldn't get the alert and reports to work. How do you enable this feature please?

**Comment by vinitpradhn18** [comment]
you need to set `ENABLE_ALERTS = True` and set `ENABLE_SCHEDULED_EMAIL_REPORTS = True` for scheduling reports

**Comment by vinitpradhn18** [comment]
I figured it out. I had to change the `WEBDRIVER_BASEURL` and `SUPERSET_WEBSERVER_ADDRESS` to my host IP. Thanks

**Comment by leocape** [comment]
@vinitpradhn18 would you mind sharing your working `superset_config.py` please? Did you need to add `chromewebdriver` in the docker-compose?

**Comment by vinitpradhn18** [comment]
> @vinitpradhn18 would you mind sharing your working `superset_config.py` please? Did you need to add `chromewebdriver` in the docker-compose?

No I didn't have to add chromewebdriver in docker-compose. I'm using firefox for it. I did have to install geckodriver for that
