### ISSUE TITLE
[Superset SPA] merge various apps into a single entry (using lazy loading for each "app")

### ISSUE THREAD

**Issue by nytai** [apache/superset#12897]
Part of project 
https://github.com/apache/superset/projects/10

**Comment by nytai** [comment]
Actually, this is likely blocked by needing to normalize our store. Each app, aside from mounting a component, also sets up redux with an initial state.

**Comment by suddjian** [comment]
Closing this as part of issue cleanup, but keeping it in the SPA project tracker.
