### ISSUE TITLE
Last edited dates shown as invalid on welcome screen 

### ISSUE THREAD

**Issue by iercan** [apache/superset#12893]
I realized last edited dates can not be shown on welcome page. I checked web console and backend logs but didn't see any error shown. Problem occurs only in Recents tab, all other tabs works fine.  

### Expected results

Last modified date of charts and dashboards should be seen. 

### Actual results

They shown as invalid.

#### Screenshots
![image](https://user-images.githubusercontent.com/3406152/106612805-8f541580-657a-11eb-8bd4-11a4cc5f05b7.png)

#### How to reproduce the bug

Modify charts or dashboards and check welcome page. 

### Environment

Installed superset via apache/superset image with celery worker. 

- superset version: 1.0.0
- python version: 0.37
- metadata store: mysql 5.7.32

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
thanks for reporting! this is a duplicate issue of [[home]recent cards last edited time stamp is not working  ](https://github.com/apache/superset/issues/12880), so glad to see that the community is using home screen. 
@iercan besides this regression, can i schedule a user interview with you for home screen? thanks

**Comment by iercan** [comment]
@junlincc To be honest I opened this issue not because we are using home screen too much. It was just too easy to see and I wanted to inform community :) But sure we can still talk. You can reach me via ibrahim.ercan@vlmedia.com.tr

**Comment by iercan** [comment]
In version 1.0.1 problem seems resolved.

**Comment by junlincc** [comment]
> To be honest I opened this issue not because we are using home screen too much.
🤣 that was my guess too. thanks for opening the issue and confirming anyway! 
we will reach out for user interview for home screen soon. 

cc @mihir174
