### ISSUE TITLE
unhealthy "app" and "worker" docker containers

### ISSUE THREAD

**Issue by shemExelate** [apache/superset#12895]
after pulling latest and running `docker-compose up` inside `/docker` folder
`docker ps -a` prints 
```
CONTAINER ID   IMAGE                        COMMAND                  CREATED          STATUS                      PORTS                              NAMES
0974b8deb211   apache/superset:latest-dev   "/usr/bin/docker-ent…"   15 minutes ago   Up 15 minutes (unhealthy)   8080/tcp, 0.0.0.0:8088->8088/tcp   superset_app
998556009d30   apache/superset:latest-dev   "/usr/bin/docker-ent…"   15 minutes ago   Up 15 minutes (unhealthy)   8080/tcp                           superset_worker
8a3b7fc9dd0e   node:12                      "docker-entrypoint.s…"   15 minutes ago   Up 15 minutes                                                  superset_node
e16fc861fbf8   apache/superset:latest-dev   "/usr/bin/docker-ent…"   15 minutes ago   Exited (0) 6 minutes ago                                       superset_init
50c8ddf6536b   apache/superset:latest-dev   "/usr/bin/docker-ent…"   15 minutes ago   Exited (1) 15 minutes ago                                      superset_tests_worker
b98e572ece92   postgres:10                  "docker-entrypoint.s…"   15 minutes ago   Up 15 minutes               127.0.0.1:5432->5432/tcp           superset_db
963658d2a1a8   redis:3.2                    "docker-entrypoint.s…"   15 minutes ago   Up 15 minutes               127.0.0.1:6379->6379/tcp           superset_cache
```

### Expected results

they should be healthy :)

### Actual results

unhealthy, affects debugging 

#### How to reproduce the bug

1. git clone https://github.com/apache/superset.git
2. cd superset/docker
3. docker-compose up
4. wait for init container to finish (also unhealthy)

### Environment

dockerized

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by ansidev** [comment]
Ref Link: https://github.com/amancevice/docker-superset/issues/51#issuecomment-759349896

**Comment by nytai** [comment]
This may be due to a misconfigured health check for workers (celery beat and worker)

**Comment by ansidev** [comment]
> This may be due to a misconfigured health check for workers (celery beat and worker)

I 've updated my comment. The problem came from `Dockerfile`.

**Comment by nytai** [comment]
right, that healthcheck will work for the webapp contianer but not the worker containers since no server is running

**Comment by ansidev** [comment]
> right, that healthcheck will work for the webapp contianer but not the worker containers since no server is running

So the problem is we are using same Docker image for both `app` and `worker`. IMO, We should use separate Docker image for worker with different HEALTHCHECK command

**Comment by nytai** [comment]
You can override the healthcheck command using docker-compose

**Comment by nytai** [comment]
You can override the healthcheck command using docker-compose

**Comment by nytai** [comment]
something like this should work:
https://stackoverflow.com/a/62364527/13977852

**Comment by ansidev** [comment]
> something like this should work:
> https://stackoverflow.com/a/62364527/13977852

Yes, I can do that. But we need a solution for everyone, not only me.

**Comment by nytai** [comment]
When you get it working, please open a PR :)

**Comment by kopernic-pl** [comment]
@nytai I've actually supressed runnig main servier HCs on non-main containers in composes - for starters, in my opinion at least partially closes this issue. Pls take a look.
