### ISSUE TITLE
Consolidate SQL components

### ISSUE THREAD

**Issue by betodealmeida** [apache/superset#12899]
We currently have a few places where users can write SQL:

- SQL Editor
- When editing a virtual dataset
- When defining a custom metric
- Editing a metric in a dataset (https://github.com/apache/superset/issues/5417)

Each one uses a different component for the user to type SQL. Ideally, we should use a single component, making the experience consistent and having features available everywhere (for example, autocompleting function names is only available in SQL Editor).

### Expected results

Consistent UX and UI.

### Actual results

- NO autocomplete when editing a virtual dataset's query
- No autocomplete for *function names* when defining a custom metric via SQL

#### Screenshots

N/A

#### How to reproduce the bug

N/A

### Environment

(please complete the following information):

- superset version: master
- python version: N/A
- node.js version: N/A

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

N/A

**Comment by rusackas** [comment]
@betodealmeida  curious your thoughts on how to handle this issue since it's pretty stale, and not a bug, per se. I think the options are 
1) Convert it to a SIP and gather support (probably not needed, it doesn't seem controversial)
2) Convert it to an Ideas thread, and see if folks are interested/supportive.
3) Simply close it as stale, and revisit the topic when there's time/energy.

**Comment by rusackas** [comment]
Closing this as stale, but maybe we can move forward with this as a SIP when the time comes. There have been other related issues about moving from ACE editor to more modern alternatives, which would likely be a part of this.
