### ISSUE TITLE
[table]date time column format in vertica

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12904]
<img width="1423" alt="Screen Shot 2021-02-02 at 2 20 28 PM" src="https://user-images.githubusercontent.com/67837651/106673503-88230c80-6566-11eb-914d-b88235df6f5a.png">

lastest master

**Comment by ktmud** [comment]
Could you add more information on how to reproduce?

**Comment by zhaoyongjie** [comment]
@junlincc 
I guess that `date_added` is a metric, so formatted by `d3-format`. `view samples` showed the original integer without format

**Comment by junlincc** [comment]
This is in our production I couldn't repro from master either. the team thinks that s regression

**Comment by zhaoyongjie** [comment]
![image](https://user-images.githubusercontent.com/2016594/106687364-f3bcb680-6606-11eb-8056-d9c674b7a273.png)

This is not a regression bug, this is called `metric formatted`. I'll give you some demonstrations.

**Comment by ktmud** [comment]
<img width="935" alt="temporal-numeric" src="https://user-images.githubusercontent.com/335541/106688396-e2ca6180-6582-11eb-89ea-7654995259e1.png">

I think this could happen when you check "Is temporal" on a numeric column. We can count it as a regression (albeit a tricky one) if previously the table chart was able to treat it as a time column.

I'll see if I can make this more robust.
