### ISSUE TITLE
[async] error: component not found for job <id> 

### ISSUE THREAD

**Issue by rwspielman** [apache/superset#12913]
We are sporadically seeing the error 'component not found for job <id>' in the dev console when loading dashboards with Global Async turned on. The charts never loads. When searching through the network requests, we can see that the api request to async_event does in fact return the correct job and we can follow the result_url in that api response to the data of the missing chart. It does not make a call to the explore_json/data api for that chart. 

Just a shot in the dark: My thoughts are possibly a race condition between loading of the ui components and the return of the api response? It seems to always be the first charts that return from async_result api (and usually in a separate request from the others that do end up loading)

### Expected results

Charts to load properly

### Actual results

Chart never loads, and error 'component not found for job <id>' warning in console. 

#### Screenshots
<img width="491" alt="Screen Shot 2021-02-03 at 12 12 58 AM" src="https://user-images.githubusercontent.com/20442310/106706014-95ff7e80-65b4-11eb-9083-109ff2e44d3e.png">

<img width="534" alt="Screen Shot 2021-02-03 at 12 13 51 AM" src="https://user-images.githubusercontent.com/20442310/106706072-b4fe1080-65b4-11eb-8a92-c6f8ca44bb66.png">

#### How to reproduce the bug

1. Turn on Global Async
2. Create dashboard/charts
3. load dashboard
4. reload dashboard after cache
5. may need to refresh a couple of times and wait for a chart to continuously have the spinning loader / the error in the console show up. it is very sporadic

### Environment

(please complete the following information):

- superset version:  master 9fa52d3
- python version: 3.8
- node.js version: 12

postgres backend
redis cache storage
redis async storage

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rwspielman** [comment]
FYI @robdiciuccio - I saw you were in charge of the async feature commits

**Comment by robdiciuccio** [comment]
@rwspielman can you test the fix in #13350 to see if that resolves your issue?
