### ISSUE TITLE
Tooltip in multilayer map

### ISSUE THREAD

**Issue by Geethanjali11** [apache/superset#12912]
## Screenshot

[drag & drop image(s) here!]
![image](https://user-images.githubusercontent.com/78130557/106706634-fd014f80-6615-11eb-8c50-898786c61c3b.png)

## Description

I have three layers in this map. Scatterplot layer has customised tooltip as displayed. But the tooltip is displayed only when I hover over a point outside polygon layer. Ideally, I want the tooltip over every point irrespective of the layer over it. Any idea how to resolve this?

**Comment by rusackas** [comment]
I'm guessing this is still an issue in Superset 1.5.x and 2.0.x since these plugins aren't seeing a lot of maintenance support lately, but if anyone is able to confirm, it would be appreciated.

**Comment by Shazad-khan** [comment]
Hi it will be very help for us to resolve this issue if you provide the steps to reproduce this bugs with the detailed information,

**Comment by rusackas** [comment]
Agreed. Closing this issue since it's stale and there are no viable repro steps. Happy to re-open if that's added, or triage a new Issue if/when warranted..
