### ISSUE TITLE
Unable to import Postgresql table

### ISSUE THREAD

**Issue by aminhakimsazali** [apache/superset#12915]
### Expected results

Import table from Postgres Database

### Actual results

I created a PostgreSQL database using AWS RDS and then import the database into Superset. I've checked the connection and it prompted OK. 

![image](https://user-images.githubusercontent.com/32535528/106720516-8a589a00-663e-11eb-8831-1c29ae02940d.png)

The table 'test' is also detected. 

![image](https://user-images.githubusercontent.com/32535528/106720812-e15e6f00-663e-11eb-8467-77dee4b2cc26.png)

The issue is, I cant import the test table. It prompted an error as follows

![image](https://user-images.githubusercontent.com/32535528/106721026-166ac180-663f-11eb-8b48-b4a21a21c2cd.png)

Based on the pgAdmin structure, I think I've filled up the correct schema and table name. 

PgAdmin: 

![image](https://user-images.githubusercontent.com/32535528/106721431-a0b32580-663f-11eb-9a97-fa9ac576a1ea.png)

Superset import table: 

![image](https://user-images.githubusercontent.com/32535528/106721644-e374fd80-663f-11eb-895d-31b94b9f476e.png)

**Comment by junlincc** [comment]
looks like you are on a pretty old version, have you tried using v1.0? @aminhakimsazali i just connected to PostgresSQL today, and connection works fine

**Comment by rusackas** [comment]
This looks like it is indeed from an older and unsupported version of Superset. If anyone sees this issue in 1.5.x or 2.0.x, let's re-open with updated version information and reproduction steps/screenshots. Thanks!
