### ISSUE TITLE
Presto admin commands(set role, grant perms) not supported on Superset

### ISSUE THREAD

**Issue by ramyarajasekaran** [apache/superset#12929]
### Environment
- superset version: `0.37.2` I upgraded to 1.0.0 and still saw this issue.
- python version: `3.6`
- node.js version: `12`

**Is your feature request related to a problem? Please describe.**
Superset does not support Presto's administrative commands such as SET ROLE, GRANT PERMS ON ROLE, CREATE ROLE, etc. These commands work on Presto CLI. Are there plans to support this feature in future releases?

**Describe the solution you'd like**
Running administrative commands should result in altering a user's data permissions for a user's session on Superset. This should be handled through SQLAlchemy and PyHive. 

**Describe alternatives you've considered**
Potentially using Presto CLI to run administrative commands and grant admins another role for querying purposes since admin role cannot be assumed on Superset.

**Comment by zuzana-vej** [comment]
Please reopen in case you are still seeing the issue - as a bug, or if this is a question please use the "Discussions" section.
