### ISSUE TITLE
Error response 400 "unknown field" when setting filters_immune_slices in Dashboard metadata

### ISSUE THREAD

**Issue by krsnik93** [apache/superset#12938]
Trying to add `filter_immune_slices` to prevent chart from being affected by a `filter_box`. After clicking save in the Dashboard edit modal, there is no visual feedback, but after inspecting Network tab in Developer Tools I can see error response:
`{message: {json_metadata: [{filter_immune_slices: ["Unknown field."]}]}}`

### Expected results

Change gets applied to the dashboard.

### Actual results

No visual feedback after clicking save, HTTP response code 400 with "unknown field" for "filter_immune_slices".

#### Screenshots

![image](https://user-images.githubusercontent.com/13034472/106877508-bd4b6e00-66d0-11eb-823f-902bc835f44d.png)

#### How to reproduce the bug

Create a dashboard. Add a filter box to it. Add a chart with column filtered by the filter_box. Try to edit dashboard json metadata by adding the following key-value:
`"filter_immune_slices": [slice_id]` 
where slice_id is the id of the chart with column filtered by the filter_box. 

### Environment

(please complete the following information):

- superset version: `superset version`: Superset 1.0.0
- python version: `python --version`: Python 3.8.7
- node.js version: `node -v`: Node not installed.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by SubhajitdasBetterplace** [comment]
Can someone share the status on this? I have been facing the same bug. IS it being fixed?

**Comment by sfirke** [comment]
I tried to add `"filter_immune_slices": [565],` to my dashboard JSON.  It took but when I clicked Save I got a popup "Sorry, an unknown error occured".  So similar behavior.  BUT, my solution was to control which charts were filtered via the Filter GUI, and that worked.  Here I exempted the bottom chart on my dashboard:
![image](https://user-images.githubusercontent.com/7569808/169074459-cbb282fc-1e34-42a6-b6cc-ff2f791dcfb5.png)

**Comment by rusackas** [comment]
Closing this since it's gone stale, and the FilterBox is deprecated and will be gone in the forthcoming Superset 4.0. If people are still encountering this in current versions (currently 3.x) and need a patch on those, please reopen this, open a new Issue, or submit a PR to address the problem.
