### ISSUE TITLE
[multi-chart] Legend Keys are displaying incorrectly

### ISSUE THREAD

**Issue by rwspielman** [apache/superset#12935]
Looks like this line is the cause
https://github.com/apache/superset/blob/94b6b29362ffec0dffc623c002a2cfd2153a6807/superset/viz.py#L1459

### Expected results

Legends to show up as normal text

### Actual results

chart keys show up as tuples

#### Screenshots

<img width="342" alt="Screen Shot 2021-02-03 at 11 11 25 PM" src="https://user-images.githubusercontent.com/20442310/106847751-2a311a80-6675-11eb-8870-f24f313f8bb6.png">

#### How to reproduce the bug

1. Create 2 charts
2. make a multi line chart
3. observe legends keys displaying incorrectly 

### Environment

(please complete the following information):

- superset version: master 9fa52d3
- python version: 3.8
- node.js version: 12

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rwspielman** [comment]
#12660

**Comment by junlincc** [comment]
@rwspielman thanks for reporting! I was able to reproduce. tagged `good first issue`
We currently are short for help and if you already have a solution, we absolutely welcome your contribution. 🙏

<img width="984" alt="Screen Shot 2021-02-03 at 9 37 40 PM" src="https://user-images.githubusercontent.com/67837651/106849716-16cb8280-6668-11eb-9be6-0981536e1713.png">

**Comment by Rishabhraghwendra18** [comment]
Hey!!! May I work on this issue ?

**Comment by junlincc** [comment]
@Rishabhraghwendra18 Absolutely!thank you for contributing! if you are interested in working on more Superset dataviz project, please let me know. https://github.com/apache-superset/superset-roadmap/issues/150

**Comment by Rishabhraghwendra18** [comment]
@junlincc thanks buddy
