### ISSUE TITLE
Unable to Login after docker container connect to Postgres Container

### ISSUE THREAD

**Issue by PullGituser** [apache/superset#12941]
I have configured superset docker container and then change the URI in conifig.py to point to postgres. I am able to run the 'superset db upgrade' and could see tables are getting created under the database. Also able to create a new user in the postgres DB. But unable to login to the application using 'admin:admin'. 
### Expected results

what you expected to happen.
Should be able to login to application with dafult admin username and can add the postgres database in screen.
### Actual results
Invalid User name/password error
what actually happens.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
this is strange, i run the same steps on a daily basis but never encountered this issue. 
@dpgaspar @srinify do you guys know? thanks

**Comment by PullGituser** [comment]
I am using superset as a different container and postgres as a different container. (NOT USING Docker Compose). After updating the sqlalchemy connection string in config.py file to point to postgres container, I am not able to Login to application. Let me know if you need any additional details.

Note - Tables are and user entry details are present in Postgres DB...

**Comment by anilkulkarni87** [comment]
I get the same error. I am trying this on a Windows WSL2 Ubuntu. I am using docker-compose up after cloning the repo.

**Comment by dpgaspar** [comment]
@PullGituser,

make sure that when you update the config you reinstall superset `pip install -e .` or `python setup.py install` and then follow the init steps: `superset db upgrade`, `superset init` etc. What procedure did you use to create the user on Postgres?

**Comment by dheeraj-chaudhari** [comment]
I am facing the same issue. I am following the below link, In my case i am using postgres DB on host 
https://hub.docker.com/r/apache/superset

So before creating an admin user, i modified config.py in my container and then did "superset db upgrade". Upgrade went successful and i can see the tables get created. Then i create an admin user using below command, admin use was created successfully and i can see the user in ab_user table

docker exec -it superset superset fab create-admin \
               --username admin \
               --firstname Superset \
               --lastname Admin \
               --email admin@superset.com \
               --password admin

and then performed

docker exec -it superset superset init

**Comment by dheeraj-chaudhari** [comment]
I was getting the same issue. If you use docker image, then you must modify the config.py and delete superset_home/superser_db and then restart the container. After you restart the container you will see 8 tables created in your postgres. Then run the below commands

- superset db upgrade
   --you will see 57 tables created in Postgres

- superset fab create-admin \
               --username admin \
               --firstname Superset \
               --lastname Admin \
               --email admin@superset.com \
               --password admin
   -- you should see admin user created in ab_user table.

Make sure you should not have /app/superset_home/superser_db file created when you restart container else its still referring to sqlite

**Comment by rusackas** [comment]
Is anyone still seeing this issue in more current versions of Superset? If not, let's close it!
