### ISSUE TITLE
[Dashboard] Removing empty top level tabs crashes the dashboard builder

### ISSUE THREAD

**Issue by ktmud** [apache/superset#12959]
### Expected results

When removing empty top-level tab, the page should not crash

### Actual results

https://user-images.githubusercontent.com/335541/106976486-57c9a280-670d-11eb-8f97-09c692d796f9.mp4

There are a couple of bugs or inconveniences related to adding tabs in dashboard builder:

1. Adding top level tab does not have proper drop indicator
2. Collapsing the top level tab makes the whole page crush if you have deleted the all tabs in it
3. Deleting the last tab collapses the tab container to a weird-looking state. We should probably either redesign it or just disabling deleting the last tab

#### How to reproduce the bug

1. Try add a top-level tab

### Environment

Latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
I'm pretty darn sure this was fixed a long time ago, so I'll optimistically close it. Happy to re-open if it rears its ugly head again.
