### ISSUE TITLE
[explore]allow users to search "type""schema"'connection""creator" in Change dataset

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12952]
I connected to multiple different db for testing purposes. I wanted to test datasets that are from a presto db connection, but had a hard time looking for it. there is no way to search by "type", "schema","connection" and "creator" currently. 

proposed change - allow user to search by in columns. 

https://user-images.githubusercontent.com/67837651/106941138-4796d080-66d7-11eb-8201-0436cf54c58b.mov

**Comment by junlincc** [comment]
@ankh6 thank you for picking up the task! 

@ktmud can you help answer these technical questions ^^ 🙏

**Comment by ankh6** [comment]
@junlincc  any news :) ?

**Comment by ktmud** [comment]
Feel free to dig into the code. You'll know the answer when you see how current component is implemented.

**Comment by junlincc** [comment]
https://github.com/apache/superset/tree/master/superset-frontend/src/datasource please see link @ankh6

**Comment by zhaoyongjie** [comment]
> Hey @junlincc !
> I'd like to work on this issue if possible. Could you clarify these points:
> 
>     * Does this task also involve frontend work ?
> 
>     * Which modules are involved ?
> 
>     * Should we implement as a @classmethod in a base class so that we can search irregardless of the database?

Hi, there.
It is a frontend work, please explore the codebase here.

https://github.com/apache/superset/blob/a3b41e2bac554a097015cf73e950ca1fc5e43b6e/superset-frontend/src/datasource/ChangeDatasourceModal.tsx#L99
