### ISSUE TITLE
[chart]Time Series Table counts null as 0

### ISSUE THREAD

**Issue by pavlozt** [apache/superset#12962]
When I use Time-series Table , the grouping functions count the missing values as 0, but to be counted as NULL.

### Expected results

Traditional  sql-like behavior that avg() function not count nulls.

### Actual results

Too low values on period averages, that do not allow do right conclusions.

#### How to reproduce the bug

1. Choose Chart Type : Time-series Table 
2. group by Field
2. Time series columns
3. Type : Period Average 
4. time lag - any value choose any value that would grab the **missing** data
### Environment
- superset version: `1.0.0`
- python version: `Python 3.7.3`

### Checklist
- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
Obviously, the problem itself gets fixed as people accumulate more data.

**Comment by villebro** [comment]
@pavlozt I quickly looked at the code implementation of time series table, and I can't directly see where this error would occur in the code. Can you share some more context, e.g. a screenshot of your control panel?

**Comment by pavlozt** [comment]
![изображение](https://user-images.githubusercontent.com/55258742/107013486-79796700-67ab-11eb-931d-bb15d2ad6d1c.png)

and
![изображение](https://user-images.githubusercontent.com/55258742/107013532-86965600-67ab-11eb-98d2-7655f09d0e1a.png)

**Comment by pavlozt** [comment]
Hello, here is wrong code, values cannot be zeroed 

superset-ui\plugins\legacy-plugin-chart-time-table\src\TimeTable.tsx

    } else if (column.colType === 'avg') {
      // Average over the last {timeLag}
      v =
        reversedEntries
          .map((k: Entry, i: number) => (i < column.timeLag ? k[valueField] : 0))
          .reduce((a: number, b: number) => a + b) / column.timeLag;
    }

**Comment by zhaoyongjie** [comment]
hi @pavlozt 
TimeTable codebase at, instead of `superset-ui`
```
superset/superset-frontend/visualizations/TimeTable
```

**Comment by junlincc** [comment]
guys @villebro @zhaoyongjie  i was able to repro, Time series table does treat null as 0 in period average
 
<img width="1490" alt="Screen Shot 2021-02-07 at 8 04 30 PM" src="https://user-images.githubusercontent.com/67837651/107174796-f9f0c100-697f-11eb-9a99-6cf1537c3c82.png">

**Comment by junlincc** [comment]
resolved
