### ISSUE TITLE
[Chart]Option to set thresholds and Color coding in Big numbers 

### ISSUE THREAD

**Issue by maheshbelavadi** [apache/superset#12964]
**Is your feature request related to a problem? Please describe.**
I use Big numbers in my summary dashboard to show current status such as average production outcome, etc. If the number is less than a threshold, want to represent it in different color (red, green, amber). Currently there is not option to set thresholds in any of the charts.  

**Describe the solution you'd like**
Typically I would want to set thresholds levels for the BIG number chart, if the actual number is below the specified threshold, the Big chart background must be red or a different color opted by the user. 

**Describe alternatives you've considered**
Currently there is no alternative. I have added the the threshold text under SUBHEADER 

**Additional context**
Current this is how it is displayed.
![image](https://user-images.githubusercontent.com/13337408/107023721-084aab80-67cd-11eb-8fd6-bda67e26719c.png)

Expect a option to set thresholds and display it as below 
![image](https://user-images.githubusercontent.com/13337408/107024209-bd7d6380-67cd-11eb-8ee7-63d3ba3642f6.png)
![image](https://user-images.githubusercontent.com/13337408/107024556-3381ca80-67ce-11eb-8c74-5e942f9425a4.png)
![image](https://user-images.githubusercontent.com/13337408/107024651-51e7c600-67ce-11eb-8ebd-953a2c25a789.png)

**Comment by junlincc** [comment]
Thanks @maheshbelavadi for proposing changes! Definitely a valid request, high impact - low effort. There are a couple asks around Big Number charts, we can get to it safely in Q2-Q3. If you already have a solution in place, feel free to drop a PR. 😉

**Comment by maheshbelavadi** [comment]
@junlincc will be glad to contribute. I am bit new to superset UI. Is there any quick reference material which I can refer to. Just on where to start from, I will figure out my way if I can get some handle to start with.

**Comment by junlincc** [comment]
@maheshbelavadi sorry for the late reply! please reach out to me in Slack, I can point you to the right direction. 
@ktmud @maloun96 would you mind giving a tour in the codebase? many thanks!

**Comment by ktmud** [comment]
@maheshbelavadi You can start reading CONTRIBUTING.md , especially the section on [viz plugins](https://github.com/apache/superset/blob/master/CONTRIBUTING.md).

Currently you'd need to edit files in the superset-ui repo and wait for them to be published as npm packages in order to make the changes available to the superset repo.

**Comment by junlincc** [comment]
We are adding Andon with color indicator through dynamic viz plug-in system. Will be available in Q3
https://github.com/krsnik93/plugin-chart-status-indicator

**Comment by abhivickyvyas** [comment]
@junlincc Is this feature now available in the current master branch?
