### ISSUE TITLE
[Delete]Can't select for bulk delete in chart/dashboard list when using card view

### ISSUE THREAD

**Issue by michael-s-molina** [apache/superset#12965]
### Expected results

When using card view and bulk selecting, a click on the card should not navigate to detail page. The cards shouldn't flick left when bulk select is clicked.

### Actual results

When using card view and bulk selecting, a click on the card navigate to detail page and I can't make further selections. Also when I click in bulk selecting, the cards panel receive a right margin making the cards flick left.

#### Screenshots
![bulk](https://user-images.githubusercontent.com/70410625/107046375-50ee6e80-67a5-11eb-97f6-fdc5c3f42f7b.gif)
![chart](https://user-images.githubusercontent.com/70410625/107046407-59df4000-67a5-11eb-8429-101e8a0eaeec.gif)

#### How to reproduce the bug

1. Go to dashboard list
2. Click on card view
3. Click on bulk select
4. Try to select more than one card
5. You can't because the first selection triggers a navigation

### Environment
- superset version: `master`
- python version: `2.7.16`
- node.js version: `15.5.1`

### Checklist
- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
committing to this change. however, we wanna promote list view over card at this point due to the performance issues. may not get to it soon. marking `good first issue` if anyone from the community wanna work on it. thanks @michael-s-molina !

**Comment by Steejay** [comment]
Agreed. This is a bug and not the desired interaction. Original spec for bulk selecting one or multiple cards:

![Select](https://user-images.githubusercontent.com/60786102/107701362-a925e480-6c6d-11eb-9bec-8f71322ff2c1.jpg)


cc @mihir174

**Comment by nytai** [comment]
This was working previously. I think we made some changes to make the entire card clickable at some point which likely broke this.
