### ISSUE TITLE
[Explore] Chart should strip ending semicolon for virtual datasource queries

### ISSUE THREAD

**Issue by ktmud** [apache/superset#12963]
<img width="921" alt="semicolon" src="https://user-images.githubusercontent.com/335541/107020466-bf0c4480-6757-11eb-93a4-0c065aa97bca.png">

When a virtual datasource has ending semicolon in it's SQL query,

The generated queries for Explore will produce an error:
<img width="540" alt="error" src="https://user-images.githubusercontent.com/335541/107020521-cf242400-6757-11eb-8dd9-e7cf46a86787.png">

Because it didn't strip the semicolon from the original query:

<img width="486" alt="query" src="https://user-images.githubusercontent.com/335541/107020639-f549c400-6757-11eb-8405-07af26e8ce46.png">

The query engine should be smart enough to know semicolon is not needed.

**Comment by junlincc** [comment]
@ktmud would like to have this fixed. how often do you users bump into this error?

**Comment by villebro** [comment]
I run into this quite often actually. This fix should be very simple, low risk and have good overall effect on UX.

**Comment by pkdotson** [comment]
PR is out: https://github.com/apache/superset/pull/13801

**Comment by zuzana-vej** [comment]
PR was merged to address this (please reopen if that's not the case)
