### ISSUE TITLE
[SQL Lab] Split run button doesn't transition smoothly between disabled and enabled states 

### ISSUE THREAD

**Issue by yousoph** [apache/superset#12979]
## Screenshot
https://user-images.githubusercontent.com/10627051/107099586-ebab7500-67c6-11eb-94a0-dd87f325fcc8.mp4

## Description
When transitioning between a disabled and enabled state, the right side of the split run button in SQL Lab changes color/state a bit later than the left side. 

How to repro: 
* In SQL Lab, select a db where you have CTAS and/or CVAS enabled 
* Delete all the text in your SQL Lab tab to see the disabled state. Start typing to see the enabled state

**Comment by yousoph** [comment]
@AAfghahi - I noticed this with the new disabled state that you added

**Comment by AAfghahi** [comment]
oh yeah this looks bad, I will look through and work on it. Maybe I can just set a timeout or something.

**Comment by zuzana-vej** [comment]
resolved a while back based on the linked PR
