### ISSUE TITLE
In SQL Query page, editor can not display in safari, iPad or macOS 

### ISSUE THREAD

**Issue by bodhi52** [apache/superset#12986]
Editor can not display.

**Comment by junlincc** [comment]
I can't run Superset in Safari at all, page keeps crashing.......... Chrome and Firefox are fine.

**Comment by bodhi52** [comment]
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/1011470/107141565-868d8600-6964-11eb-9b13-3565255a487f.png">

**Comment by junlincc** [comment]
@yousoph  could you take a look? thanks.

**Comment by yousoph** [comment]
This was fixed recently: #12973
