### ISSUE TITLE
[chart]Label type selection not working on Pie chart

### ISSUE THREAD

**Issue by syazwan0913** [apache/superset#12989]
### Expected results

Label type changed

### Actual results

Label type doesn't changed

#### Screenshots

![ZOoO4Gkebk](https://user-images.githubusercontent.com/28984703/107134715-8de66c80-692f-11eb-8c36-4e474809ceea.gif)

#### How to reproduce the bug

1. Go to 'Charts'
2. Click on 'any Pie chart.'
3. Change Label Type

### Environment

(please complete the following information):

- superset version: `master`
- python version: `based on master`
- node.js version: `based on master`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
confirmed this is not working in master. also label disappear on hover. 

<img width="1073" alt="Screen Shot 2021-02-06 at 6 45 36 PM" src="https://user-images.githubusercontent.com/67837651/107134966-9c8b4000-68ab-11eb-83b3-d0b40dd9b230.png">
  
@villebro not sure it happens after we bumped echarts to 5.0.2? 
tagged `good first issue ` feel free to open a PR if you have a solution 😃

**Comment by villebro** [comment]
Bumping the version in the plugin here which fixes the issue: https://github.com/apache-superset/superset-ui/pull/942
