### ISSUE TITLE
Is there a way to add a hive database with kerberos authentication?

### ISSUE THREAD

**Issue by tsingmmy** [apache/superset#12990]
The superset version is 1.0.0.The  "add database" operation works good with mysql database,but I can't succeed to connect hive database enabled kerberos authentication.

![image](https://user-images.githubusercontent.com/33018526/107135829-0aca1400-6939-11eb-9303-6efac03b593b.png)

The response told me 'please check your logs for details',but there is only one line  in superset.log indicating "logging is configured successfully".
The configuration related with logging has been set as
ENABLE_TIME_ROTATE = Ture
TIME_ROTATE_LOG_LEVEL = "DEBUG"
LOG_LEVEL = "DEBUG"

I wonder how to specify user keytab and krb5.conf in the Add Database operation and how to enable the failing logs.
Could any one show me an example  to config the connection settings?

**Comment by juneauwang** [comment]
Your connection string is good for me. You can try to get a valid kerberos ticket in user superset on linux and run superset with user superset so that connection should be good.

**Comment by tsingmmy** [comment]
Thanks for your reply. 
I deploy superset on k8s and successfully use command 'kinit' to get   a kerberos ticket. The only difference with your advice is that both steps are with user root.However I still fail to connect to hive.
I have 2 questions :
1.Why  can't  superset print debug or even error massage in logs when failling to connect hive database ? If those logs are printed maybe I can know the reason.
2.How to use the following configuration ? The comments says it can be used to connect hive and It seems a better way to connect to hive.
![image](https://user-images.githubusercontent.com/33018526/108298738-68335000-71d8-11eb-843e-839b2efeafca.png)

**Comment by juneauwang** [comment]
1.Why can't superset print debug or even error massage in logs when failling to connect hive database ? If those logs are printed maybe I can know the reason.
You can find the reason in superset server log if you set your log LOG_LEVEL = "DEBUG" 

2.How to use the following configuration ? The comments says it can be used to connect hive and It seems a better way to connect to hive.
I don't use this so I can't answer

**Comment by tsingmmy** [comment]
I solved the problem by replacing the IP address with domain name. With IP address the kerberos  principal requested is incorrect. 
Thank you all the same.

**Comment by virtualb0x** [comment]
Hello!
@tsingmmy can you be so kind to explain where to put kerberos ticker in config?

**Comment by tsingmmy** [comment]
Sorry. After so many years I can't remember clearly how to do it.  Maybe I just used kinit command to get the ticket. This was not graceful and I did't use superset in product environment.
