### ISSUE TITLE
[Explore]user can not type filter values when above 10k option limit 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#13017]
In Explore control panel - adhoc filter, select a column, set operator to "equals", see user can not type to add filter value that's not in the 10k limit in the select dropdown. 
**Broken in equals and LIKE**

In `equals `
![ezgif-6-40b95e6e96db](https://user-images.githubusercontent.com/67837651/107299038-6f659b80-6a2b-11eb-8ac7-35a2fc4895b3.gif)

https://user-images.githubusercontent.com/67837651/107302092-a048cf00-6a31-11eb-9a92-b11985ecd8c7.mov

It works in `IN` though
In `IN`

https://user-images.githubusercontent.com/67837651/107295026-67a1f900-6a23-11eb-968a-134f407a1624.mov

**Comment by junlincc** [comment]
@kgabryje

**Comment by junlincc** [comment]
second issue - cosmetic 
Dashboard filter that's carried to Explore will not be saved in Chart. a warning message is attached to such filter. 
Expected behavior, warning sign should be in the field, in yellow. 
<img width="671" alt="Screen Shot 2021-02-08 at 6 20 55 PM" src="https://user-images.githubusercontent.com/67837651/107306848-7d6ee880-6a3a-11eb-8aa1-7aee526722c0.png">

**Comment by kgabryje** [comment]
On it

**Comment by junlincc** [comment]
resloved
