### ISSUE TITLE
Paired T-Test visualization is broken in 1.0.0

### ISSUE THREAD

**Issue by akud** [apache/superset#13011]
The Paired T-Test visualization type does not work in superset 1.0.0 when running from a fresh clone of the superset repo against one of the example datasets.

### Expected results

I expect the T-Test plugin to render a table with p-values.

### Actual results

I see an error message stating `An error occurred while rendering the visualization: TypeError: Cannot read property 'map' of undefined`

#### Screenshots
![Screenshot from 2021-02-08 10-53-43](https://user-images.githubusercontent.com/509910/107267613-fef35600-69fb-11eb-9bb3-404c1585989c.png)

#### How to reproduce the bug

1. Clone the superset repo: `git clone https://github.com/apache/superset.git`
2. Checkout the 1.0.0 tag: `cd superset && git checkout tags/1.0.0`
3. Start the superset server: `docker-compose up`
4. Go to http://localhost:8088 in a browser and click on "Datasets"
5. Click on the "Video Game Sales" Dataset
6. Click on the "Table" visualization type and change it to "Paired t-test"
7. Set up the visualization as follows: Time filter: `No filter`, metric: `sum(global_sales)`, group by `genre`
8. Click "Run Query"
9. Get the error

### Environment

(please complete the following information):

- superset version: `superset version`
```
Loaded your LOCAL configuration at [/app/docker/pythonpath_dev/superset_config.py]
INFO:superset.utils.logging_configurator:logging was configured successfully
/usr/local/lib/python3.7/site-packages/flask_caching/__init__.py:192: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  "Flask-Caching: CACHE_TYPE is set to null, "
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Superset 1.0.0
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```
- python version: `python --version`
```
Python 3.7.9
```
- node.js version: `node -v`
```
v12.20.1
```
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
Server logs:
```
superset_app             | DEBUG:parsedatetime:eval - with context - False, False
superset_app             | INFO:superset.viz:Cache key: 37e8c9c39567b33a73e84dd8215ca361
superset_app             | DEBUG:superset.models.core:Database.get_sqla_engine(). Masked URL: postgresql://superset:XXXXXXXXXX@db:5432/superset
superset_app             | INFO:superset.connectors.sqla.models:SELECT genre AS genre, year AS __timestamp, SUM(global_sales) AS sales 
superset_app             | FROM video_game_sales GROUP BY genre, year 
superset_app             |  LIMIT 10000
superset_app             | DEBUG:superset.stats_logger:[stats_logger] (incr) loaded_from_source
superset_app             | DEBUG:superset.stats_logger:[stats_logger] (incr) loaded_from_source_without_force
superset_app             | DEBUG:superset.stats_logger:[stats_logger] (incr) set_cache_key
superset_app             | DEBUG:superset.stats_logger:[stats_logger] (incr) explore_json
superset_app             | 172.18.0.1 - - [08/Feb/2021 18:56:16] "POST /superset/explore_json/ HTTP/1.1" 200 -
superset_app             | INFO:werkzeug:172.18.0.1 - - [08/Feb/2021 18:56:16] "POST /superset/explore_json/ HTTP/1.1" 200 -
superset_app             | DEBUG:superset.stats_logger:[stats_logger] (incr) log
superset_app             | 172.18.0.1 - - [08/Feb/2021 18:56:17] "POST /superset/log/?explode=events HTTP/1.1" 200 -
superset_app             | INFO:werkzeug:172.18.0.1 - - [08/Feb/2021 18:56:17] "POST /superset/log/?explode=events HTTP/1.1" 200 -
```

- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

This error comes from a fresh install of superset 1.0.0

**Comment by junlincc** [comment]
@akud Thank you so much for reporting issues at such detailed level! I am able to reproduce, this is happening to all dataset. 
we can't get to it soon unfortunately 😞 
If anyone would like to contribute, according to our committer, this is likely a frontend error caused by the server, and the broken line could be found in the ui plugin code. 🙏
