### ISSUE TITLE
[chart]x axis format is missing on the first date of each month

### ISSUE THREAD

**Issue by junlincc** [apache/superset#13019]
User now can change X AXIS FORMAT in time series charts and see date format on rich tooltip. However, the first date of the month is always missing its full time format in tooltip. (e.g. 1/1/2021 is displayed as Jan 2021) see video

https://user-images.githubusercontent.com/67837651/107318140-ef522c80-6a50-11eb-9447-3ee3be094592.mov

<img width="294" alt="Screen Shot 2021-02-08 at 9 05 58 PM" src="https://user-images.githubusercontent.com/67837651/107318625-080f1200-6a52-11eb-8497-a2695261f740.png">

to repro
- go to any legacy time series chart(line)
- select dataset that have datetime column 
- set time grain to day 
- hover on the series to see tooltip of the first day of each month 
- see x-axis format is missing

**Comment by iercan** [comment]
Same thing happen for 00:00 a.m. when time grain is hour.

**Comment by junlincc** [comment]
@maloun96 ^ let's tackle this one 🙏
