### ISSUE TITLE
Chart name looks as its id number when trying to edit an alert or report 

### ISSUE THREAD

**Issue by iercan** [apache/superset#13023]
When I try to edit an alert or report I realized selected chart name seems as id number. 

### Expected results
I should see selected chart name. 
![image](https://user-images.githubusercontent.com/3406152/107335208-b3f34480-6ac8-11eb-982f-7b177070cea0.png)

### Actual results
Chart name looks as chart id when trying to edit. 
![image](https://user-images.githubusercontent.com/3406152/107335148-a0e07480-6ac8-11eb-8b22-aa122477b6ca.png)

#### How to reproduce the bug

1. Create an alert/report. Choose a chart for message content
2. Save it and refresh page. 
3. Click edit to new saved alert/report

### Environment

- superset version: 1.0.1
- python version: 3.7
- mysql: 5.32.7
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zuzana-vej** [comment]
@iercan  can you confirm if this bug still exists / close the issue if it's resolved? thanks

**Comment by iercan** [comment]
I couldn't reproduce with version 1.1. Thanks
