### ISSUE TITLE
Wrap text results output for long textual outputs in SQL results tab 

### ISSUE THREAD

**Issue by ashishtadose** [apache/superset#13036]
Current any long textual output is displayed as a single line (with a scroll bar).

This behavior makes it cumbersome to read text outputs for frequently used SQL queries such as SHOW CREATE TABLE or EXPLAIN PLAN which contains text output. 
  
<img width="1599" alt="Screenshot 2021-02-10 at 12 25 43 AM" src="https://user-images.githubusercontent.com/1897846/107414101-8e515400-6b37-11eb-9295-5e270eb8e977.png">

**Comment by ashishtadose** [comment]
Is there any config to enforce text wrapping for superset text result output?

Thanks in advance.

**Comment by rusackas** [comment]
Closing this since it's stale, and because it's not a bug, but it's a legit concern! If you still want this tackled (or want to tackle it!) then please open a Github Discussion or join us on Slack to dig deeper.
