### ISSUE TITLE
i18n: translation of dashboards and charts

### ISSUE THREAD

**Issue by thelightbird** [apache/superset#13030]
I am currently investigating the use of Apache SuperSet at work.

**Is your feature request related to a problem? Please describe.**
An important feature for us is to be able to translate dashboards and charts in different languages.

**Describe the solution you'd like**
I've seen that SuperSet has an internationalization feature, but it seems that it is currently only used to translate the dashboard UI, not the custom text that users type to create new dashboards or charts.

:arrow_right: Are you planning to add this feature?
:arrow_right: Do you have any recommendations on how to implement such a feature?

**Comment by junlincc** [comment]
<img width="762" alt="Screen Shot 2021-02-09 at 11 59 22 AM" src="https://user-images.githubusercontent.com/67837651/107421016-595ce700-6ace-11eb-9c12-96517ddb3696.png">
@thelightbird custom text works for me, or maybe I didn't understand your request correctly?

**Comment by thelightbird** [comment]
I meant to say: for a given dashboard or chart, we would like to be able to specify text translations for each language without having to duplicate the whole dashboard or chart. For example: create the chart in the first language, then save it, change the language, and then edit the same chart and it will edit the translations of that selected language without losing previous language translations.

The goal is to have multiple translations (one per language) to avoid the duplication of the dashboard or chart components.
This way, for the same chart, changing the current language would change the text of the title, axis labels, etc.

**Comment by junlincc** [comment]
got it! unfortunately this is not in our roadmap in the near future. feel free to provide a SIP(Superset improvement proposal) and detailed plan to push this forward though!  @thelightbird

**Comment by icrc-fdeniger** [comment]
To propoe a workaround, is it possible to use macro in title ( panel / dashboard / Column) ? We can use this to propose translation  in some cases.

**Comment by geido** [comment]
Hey @thelightbird thanks for your idea here. As this is not part of our roadmap,the best approach would be to open a SIP as Junlin wrote before. I am closing this issue for now as there hasn't been any activity in a long time.

**Comment by Yisel-Ulloa** [comment]
Good morning @thelightbird, @geido, @icrc-fdeniger, @junlincc, @bgreenlee. Do you know if there is already an option to be able to translate these texts dynamically?
