### ISSUE TITLE
Error after install and upgrade of Superset DB  apache-superset 1.0.1 

### ISSUE THREAD

**Issue by GangadharGuska** [apache/superset#13038]
After install and upgrade of Superset DB  apache-superset 1.0.1 gets an error clicking on Charts or dashboard" Traceback (most recent call last):   File "/obi/ApacheSuperset/superset01/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context     cursor, statement, parameters, context   File "/obi/ApacheSuperset/superset01/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute     cursor.execute(statement, parameters) sqlite3.OperationalError: no such column: dbs.uuid"   

installed apache-superset 1.0.1 and done the DB upgrade with initlized after loading the samples we get error clicking on Chart or Dashboard"
 File "/obi/ApacheSuperset/superset01/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/obi/ApacheSuperset/superset01/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: saved_query.rows

moved long title to description. 
<img width="966" alt="Screen Shot 2021-02-09 at 12 02 18 PM" src="https://user-images.githubusercontent.com/67837651/107421415-ca040380-6ace-11eb-823d-9fb70a48f4fc.png">

**Comment by betodealmeida** [comment]
@GangadharGuska, did you run `superset db upgrade`?

**Comment by GangadharGuska** [comment]
> @GangadharGuska, did you run `superset db upgrade`?

"Yes i have"
