### ISSUE TITLE
[Explore] Time grain should match X-axis 

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#13040]
**Is your feature request related to a problem? Please describe.**
Currently when user selects monthly or weekly time grain in Explore, the X axis on the chart still displays all the days (if there is space for it - depending on time period overall selected). There is no way to change this currently in the Customize tab.

**Describe the solution you'd like**
If monthly time grain is selected, the X axis on the chart should just display months (January, February etc.) based on what formatting user selects in the Customize tab.
If weekly time grain is selected, the X axis on the chart should just display weeks. (e.g. date of the first day (Monday) in each week)

**Describe alternatives you've considered**
other option is to let user configure this in the "customize tab" 

**Additional context**
See two examples of the problem. 

My time grain is weekly, but I see all the days bellow, even though chart values are populated weekly.

![Screen Shot 2021-02-09 at 12 14 42 PM](https://user-images.githubusercontent.com/61221714/107423171-e3a64a80-6ad0-11eb-8079-98a71bf2f989.png)

My time grain is monthly but I see again all the days on X axis.
![Screen Shot 2021-02-09 at 12 14 55 PM](https://user-images.githubusercontent.com/61221714/107423216-ed2fb280-6ad0-11eb-83cc-0a226c095d5d.png)

**Comment by junlincc** [comment]
@zuzana-vej 
thanks for the request. Yes, x-axis is not picking up the time grain consistently in all the time series chart, not deal breaker but  it could get pretty annoying. 
Our plan is to implement this enhancement in Echarts only, along with advanced analytics(rolling window etc.) to reach full feature parity and deprecate NVD3 time series charts. We will add to roadmap when it gets closer. 

cc: @villebro @maloun96 let's aim for mid Q2

**Comment by villebro** [comment]
I think restricting the labels to the time grain makes sense when there are very few datapoints; however, it's not uncommon to e.g. have daily time grain for a full year of data, in which case we probably don't want one tick per grain. So perhaps we should introduce an additional customization option that makes it possible to force rendering one tick+label per time grain, and only make it visible if a time grain is selected?

**Comment by rusackas** [comment]
Closing this one out since it's been inactive for a few days shy of a year, is in reference to a deprecated plugin, and is more of a feature request than a bug, it seems. If this still needs to be considered for the ECharts plugin, I think we should open an Ideas thread and start tackling it there, with updated context. Thanks!
