### ISSUE TITLE
Filter Box incorrect 

### ISSUE THREAD

**Issue by Beknazar19** [apache/superset#13043]
Hello everybody.
I have a problem with the filter when I went from 0.38 to 1.0.0

ORA-00936: missing expression
This may be triggered by:
Issue 1002 - The database returned an unexpected error. 
![image](https://user-images.githubusercontent.com/45395471/107468027-70184200-6b91-11eb-8704-07e27745c826.png)

thanks...

**Comment by junlincc** [comment]
@Beknazar19 thanks for reporting, could you give clear steps to reproduce?

**Comment by Beknazar19** [comment]
I created filters in 0.38 as usual, everything worked.
Then I imported the dashboard to 1.0.0.
Diagrams were imported correctly, but filters with errors.

**Comment by villebro** [comment]
Are you getting errors when importing dashboards, or is this happening after you upgraded your superset installation from 0.38 to 1.0.0?

**Comment by Beknazar19** [comment]
an error occurs after importing the dashboard

**Comment by Beknazar19** [comment]
We use one host server, which have two superset release 0.38 with port 8080
and 1.0.0 with port 8088.
May be that's why error occurred?

ср, 10 февр. 2021 г., 16:13 Ville Brofeldt <notifications@github.com>:

**Comment by villebro** [comment]
@Beknazar19 a little more context would be needed to help debug this. Can you provide details on what the exact "Oracle Error" is (either by clicking on "See more" or in server logs)? Also, exporting and importing across different versions is not guaranteed to work; it may work, but in many cases it won't. To be able to import dashboards into your 1.0.0 version of Superset, you need to make sure the export has been generated using a Superset instance on the same version.

**Comment by Beknazar19** [comment]
> Can you provide details on what the exact "Oracle Error" is (either by clicking on "See more" or in server logs)?

it shows: 
ORA-00936: missing expression
This may be triggered by:
Issue 1002 - The database returned an unexpected error. 

I think the error is not related to the import of the dashboard.
When I create a new filter in version 1.0.0, an error appears.

**Comment by suddjian** [comment]
Closing as there does not appear to be enough information to address this.

**Comment by deepa091** [comment]
Getting this error while I created new calculated column in dataset and then tried using that column in Filterbox

**Comment by deepa091** [comment]
Hi,

I am creating one Calculated field. It is working fine in SQL Editor but when I am creating Filterbox I'm getting Error 1002.
Query is:
SELECT a.id FROM a,b WHERE a.id=b.id;

Please can anyone help me out to tell me how I can create this Calculated field.
