### ISSUE TITLE
[timezone]add timezone setting to chart and advanced analytics

### ISSUE THREAD

**Issue by amuluowin** [apache/superset#13045]
**Is your feature request related to a problem? Please describe.**
1.I have some statistics that require time zone conditions, but the time conditions use the service time zone by default
2.When I switch the time granularity in the dashboard, I cannot reset `Comparison Period Lag`

**Describe the solution you'd like**
1.Add timezone option to `Filter Box` and `Charts`.
2.The `Big Number with` Trendline option `Comparison Period Lag`

**Comment by junlincc** [comment]
timezone setting is highly requested lately and is something we are committed to implement in Q2-Q3. @amuluowin please help us by providing detailed use cases. thanks!

**Comment by amuluowin** [comment]
OK
