### ISSUE TITLE
when user doesn't have permission to access resource, http code 400 is returned 

### ISSUE THREAD

**Issue by duynguyenhoang** [apache/superset#13060]
Currently when user doesn't have permission to access resource, for example save a chart, the http code 400 is returned.

### Expected results

http code 403 is returned.

### Actual results

http code 400 is returned.

### Environment

- superset version:  master
- python version: 3.8
- node.js version: v12.19.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zuzana-vej** [comment]
based on the linked PR this was resolved a while back
