### ISSUE TITLE
Certification Icons not shown in metric popover select

### ISSUE THREAD

**Issue by etr2460** [apache/superset#13078]
## Screenshot
![image-2021-02-02-12-38-58-762](https://user-images.githubusercontent.com/7409244/107666682-a0b8b400-6c43-11eb-83ad-de1e2da4fad9.png)

## Description
For the same search query, we show certification icons for the metrics in the dataset sidebar, but not in the metric popover select. I believe this is a regression from previous behavior where we showed the certification icons in both places: see original implementation here: https://github.com/apache-superset/superset-ui/pull/748

**Comment by junlincc** [comment]
thanks for reporting! I believe we lost the certification icon for a while already sice AntD migration? We will bring it back soon.🙏

**Comment by zuzana-vej** [comment]
resolved by the above linked PR
