### ISSUE TITLE
It is not possible to edit a database if it is not accessible

### ISSUE THREAD

**Issue by iercan** [apache/superset#13089]
We have a database connection that is not accessible anymore. I want to remove it from sql lab view but since database is not accessible I'm getting error in the picture.  

### Expected results

Database should be saved successfully.  

### Actual results
Giving below error and doesn't save
![image](https://user-images.githubusercontent.com/3406152/107741456-404a7500-6d1e-11eb-88bf-451494630839.png)

#### How to reproduce the bug

1. Add any database 
2. Make database inaccessible 
3. Try to edit database sqllab settings (i.e. disable sql lab expose)

### Environment

(please complete the following information):

- superset version: 1.0.1
- python version: 3.7

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
Every DB connection you create is shown on SQLLab (if the user has permissions for it). On this case I think you actually want to remove the connection (delete the record from the db connection list)

**Comment by iercan** [comment]
No I don't want to remove database in case I may use it in future. Also this is not just about sqllab, database is not editable in anyway if it is inaccessible. I just gave sqllab situation  as an example.

**Comment by dpgaspar** [comment]
Yes, I understand now. By design when an update is done, superset fetches the existing schemas from the db and updates the necessary security permissions. This behaviour can probably be improved if it's a problem to not be able to edit for example SQLLab database properties.

Can you explain in more detail, your use case for editing SQLLab properties for a database that is not accessible?

**Comment by iercan** [comment]
I just wanted to disable it from sqllab for more clear view. I think there is no need to fail because of a connection issue for every update action while there is a 'test connection' button there.

**Comment by rusackas** [comment]
Closing this since it's been silent for two years, and sounds like it might be more of a feature request than a bug. Happy to revisit and reopen if that's warranted!
