### ISSUE TITLE
[Table]send empty filter value " " to query after default filter value is removed 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#13099]
User uses the same dataset to create a table chart, and a FilterBox with a default value in column. '
Add both to same dashboard. 
Go to dashboard, see default value and table chart ✅
User goes edit the FilterBox in Explore from Dashboard
Remove the original selected default filter value and save, go back to the same dashboard. 
See chart result is not showing after default value is removed -  see video

Expected: User should still see a chart that's not being filtered. 

Reasons: empty value " " is sent to the query, instead of no filter/where clause 
Workaround: delete the filter that had default value, and create a brand new same one, add to dashboard.. 

Not db specific. only happens on table chart. 

https://user-images.githubusercontent.com/67837651/107823877-62032680-6d35-11eb-936a-1357e2523966.mov

https://user-images.githubusercontent.com/67837651/107824879-046fd980-6d37-11eb-827a-56108e3a3dee.mov

**Comment by junlincc** [comment]
@ktmud 🙏 ^

**Comment by ktmud** [comment]
This is not unique to table chart, I'm seeing it for other charts as well:

https://user-images.githubusercontent.com/335541/107860660-5119ea00-6df5-11eb-9c37-5130f6dc07ac.mp4
