### ISSUE TITLE
2 TIme Column Filter for Superset Apache

### ISSUE THREAD

**Issue by alvinlabiano** [apache/superset#13115]
Is there are way to create a widget with Superset Apache where the SQL Query is based on 2 time columns?

Example Query:

"SELECT 
   title
  ,pipeline_id
  ,alc_production_status
  ,campaign_start_date
  ,campaign_end_date
  ,website_name
  ,performance_status_name
  ,sum(spend) AS spend
FROM superset_native_dashboard.v_content_list_with_facebook_ads_v1
WHERE ((campaign_start_date BETWEEN date '2020-12-27' AND date '2020-12-28') OR
     (campaign_end_date   BETWEEN date '2020-12-27' AND date '2020-12-28'))
GROUP BY
   title
  ,pipeline_id
  ,alc_production_status
  ,campaign_start_date
  ,campaign_end_date
  ,website_name
  ,performance_status_name

**Comment by amitmiran137** [comment]
You can just write custom SQL query that wraps that logic of a single time range bring pass to different where clause parts 
And saved it as a virtual dataset
