### ISSUE TITLE
Maximize charts: wrong height calculated

### ISSUE THREAD

**Issue by Arktiswind** [apache/superset#13128]
We have a fresh installation of superset. Our own and the example charts are only displayed with the upper half of the charts in maximized mode. 
We found the error in the following charts:
- bar charts
- line charts
- treemap
- area charts
- table (if set to enough entries per page)
- heatmap
- pie chart

### Expected results

The chart as it looks in normal mode.

### Actual results

The height of svgs is not calculated correctly in maximized mode and a good half of the charts is missing.

#### Screenshots
Should look like this:
[area chart](https://www.telesys.de/wp-content/uploads/superset1.png)

But looks like this:
[area chart](https://www.telesys.de/wp-content/uploads/superset2.png)
[bar chart](https://www.telesys.de/wp-content/uploads/superset3.png)
[heatmap](https://www.telesys.de/wp-content/uploads/superset4.png)

#### How to reproduce the bug

1. Go to an example dashboard like "Video Game Sales"
2. Click on "Maximize chart" by one of the chart types mentioned above

### Environment

- superset version: 1.0.1
- python version: 3.7.3

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
thanks for reporting, looks like this is only happening on that sample dashboard. Tested on a dashboard i created, these three charts works fine. can you verify? @Arktiswind 


https://user-images.githubusercontent.com/67837651/107968545-57c66f80-6f63-11eb-9a2a-495e45a0a2ba.mov

**Comment by Arktiswind** [comment]
You are right. I made a new dashboard with new charts and everything works fine. 
I will delete the example dashboard. 

Please excuse the hasty opening of a ticket.

**Comment by junlincc** [comment]
No worries, and thanks for choosing Superset🙂 I wonder why sample dashboards don't work properly though. Worth taking a look.

**Comment by Arktiswind** [comment]
Hi again, 
I unfortunately have to open this issue again. 
Told my colleague he can start building his own charts and the problem is back. Well, kind of...
On his PC the new barChart is cut off again in maximized mode:
https://www.telesys.de/wp-content/uploads/supersetBarChart2.png

On my PC everything is well with the same chart on the same dashboard:
https://www.telesys.de/wp-content/uploads/supersetBarChart1.png

We testet on Chrome, Firefox and Edge. All 3 latest version. All 3 behave the same: for me the chart looks great in maximized mode, for him not. It is a little strange ;-)

The only difference i see at first glance is our screen resolution: 
I have 2560x1440 with Windows scaling 125%.
He has 1920x1080 with a Windows scaling 150%
