### ISSUE TITLE
[Dataset][Time filter] Allow setting a global or dataset-level default time range

### ISSUE THREAD

**Issue by ktmud** [apache/superset#13125]
**Is your feature request related to a problem? Please describe.**

Currently new charts are created with the default time range filter value set to ["Last week"](https://github.com/apache-superset/superset-ui/blob/46f0a174fed7b7c518d078b0eb16b129183c3b9d/packages/superset-ui-chart-controls/src/shared-controls/index.tsx#L319). This may make sense for some businesses, but often cause confusion when users didn't notice this filter is being implicitly applied.  Experienced users may even have learned the first thing they do when creating a new chart is to reset this to `No filter` (or whatever is the best for their dataset).

**Describe the solution you'd like**

It would be ideal if we can provide a global, as well as database and dataset-level settings on the default Time Range filter when creating a new chart. For dataset-level configuration, we may even allow it to be configurable for each datetime column.

We can start simple with global level configuration that each business can adjust for their own needs. In the future, in the spirit of doing less implicit things, we should probably also consider setting the default global config to "No filter".

Or we can focus on implementing the dataset level config, and set it as "Last week" for all existing datasets.

**Describe alternatives you've considered**

Simply changing the default to "No filter" may not be desired because time filters have impact on the performance of db queries and setting "No filter" as global default may cause undesired long running queries, especially when a chart start running new queries right after creation (e.g. table chart).

**Additional context**

Ref: https://github.com/apache/superset/pull/13109#issuecomment-778928053

**Comment by junlincc** [comment]
I agree with this change - setting time range filter at the dataset-level. the reason we set filter to default "Last week" is to prevent users from running expensive explorational query. Not sure about changing default to"No filter" though, shouldn't we allow user to set default? or similar to ad-hoc filter, store value in local storage as user's own default?

**Comment by junlincc** [comment]
https://github.com/apache/superset/issues/12542 related

**Comment by ktmud** [comment]
@junlincc the idea IS to allow users to set default. I was just proposing we don't set the initial default. Once the global setting for default time filter is added, Superset may ship with the global config as "No filter" because it is the most neutral choice. It also forces organizations to pick a default value that makes the most sense to them.

We could also just focus on Dataset level settings and make the default time range filter a required field when creating a new dataset.

**Comment by junlincc** [comment]
> We could also just focus on Dataset level settings and make the default time range filter a required field when creating a new dataset.

@ktmud 
Will asking new users to setup default time range filter be too confusing at the first place? since the user need is coming from those who have been forced to switch range from "Last week" to "No Filter". Why not store new "default" at local storage?

**Comment by ktmud** [comment]
I think remembering users' last selected time filter MAY work, but it doesn't solve the problem of the initial default "last week" not making sense to certain datasets (i.e. those who don't update every week). We still need a dataset-level default.

We can drop the idea of making it a required field as I imagine it'd be quite hard to implement a good UX for it---especially considering most virtual datasets are created from SQL Lab.

**Comment by junlincc** [comment]
what about setting [max date -7, max date) of any dataset by default? @ktmud

**Comment by ktmud** [comment]
That's a great idea, but I'm not sure how easy it is implement, though--both engineering and design-wise. We need a clean design to communicate this default value to users clearly, and it's needs to be performant.

**Comment by junlincc** [comment]
engineering wise, shouldn't be too hard. and if min and max dates in dataset can be detected, do we still need any configuration?

**Comment by villebro** [comment]
I like the idea of being able to define a global default time range in `superset_config.py` (this would be the one e.g. the native filter defaults to), and then being able to override it per dataset.

**Comment by ktmud** [comment]
@junlincc It's not easy engineering wise.

**Comment by geido** [comment]
Thanks to everyone who has contributed to the discussion. Closing this issue as it seems this should be accounted for in most recent versions of Superset.
