### ISSUE TITLE
Issue in sql Editor on trying to run query or selecting table in SQL LAB

### ISSUE THREAD

**Issue by Newgin-sam** [apache/superset#13151]
### Screenshot
![screenshot](https://user-images.githubusercontent.com/60768808/108072203-99066e80-708c-11eb-88b4-1ed483d3855a.PNG)
### Description
When navigating to sql editor and trying to run a query or selecting table on left dropdown the error as above screen shot
I am able to create datasets create charts and display on dashboards but i colud'nt run any query in sql editor as the error comes

### Error

Database error
Instance <Query at 0x1b8f2ec1e50> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: http://sqlalche.me/e/13/bhk3)

**Comment by yousoph** [comment]
#13041 fixes this

**Comment by suzjstgithub** [comment]
https://github.com/apache/superset/issues/12824

ENV： WIN10、pyhon venv 3.7.1  superset 1.0.1
same bug：
Database error
Instance <Query at 0x243d3302ac8> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: http://sqlalche.me/e/13/bhk3)

fixbug：
Lib\site-packages\superset\utils\core.py 
![image](https://user-images.githubusercontent.com/62527347/108314748-60ce6f80-71f5-11eb-92e8-336c837bd853.png)
