### ISSUE TITLE
Couldn't able to add reports 

### ISSUE THREAD

**Issue by wargod797** [apache/superset#13172]
![image](https://user-images.githubusercontent.com/43702120/108200899-1c839680-7145-11eb-9841-96015ba52d24.png)

After following doc from below link setup email config 
https://superset.apache.org/docs/installation/email-reports

ENABLE_ALERTS = True
ENABLE_ALERTS = True

email schedule working fine 
Add button is gray couldn't able add any alerts or reports 

i'm using superset 1.0.0 Jan 21st Release
firefox-geckodriver = 0.29

OS: Ubuntu 20.04 LTS Linux Sub System

please help

**Comment by dpgaspar** [comment]
@wargod797 please fill out the issue bug form, specially interested on knowing you superset version or commit SHA.
Thank you

**Comment by wargod797** [comment]
@dpgaspar  I'm using superset 1.0.0 Jan 21 2021 Release facing same issue on 1.0.1 Feb 6 th Release also

**Comment by zuzana-vej** [comment]
This has been inactive for 2+months, if it is a question please open under Discussion, if a bug please reopen.
