### ISSUE TITLE
Support sending report in PDF & CSV

### ISSUE THREAD

**Issue by DRavikanth** [apache/superset#13177]
In the latest version of Superset we introduced Alerts & Reports new functionality for scheduled email of reports. However currently we are sending only a snapshot of the dashboard using the webdriver. Ask is to support sending the screenshot of the dashboard embedded in either CSV/PDF file. Most of the BI tools in the market support this functionality. It would be good to have this functionality supported in Superset as well.

**Comment by willbarrett** [comment]
Thanks for the @DRavikanth - I'm going to look into it.

**Comment by DRavikanth** [comment]
Thanks for taking a look at it @willbarrett. Please review the requirement and let me know when this can be targeted for.

**Comment by zuzana-vej** [comment]
The PDF is covered under this feature request https://github.com/apache/superset/issues/13954 (closing this, progress will be tracked under the consolidated GH#)
