### ISSUE TITLE
Feature ROW_LEVEL_SECURITY not working

### ISSUE THREAD

**Issue by carobaldino** [apache/superset#13188]
According to the [documentation here](https://github.com/apache/superset/blob/3a2300b84a710c381969ef0d5e8bf7408b5a9870/UPDATING.md) and to [this PR](https://github.com/apache/superset/pull/11575), `ROW_LEVEL_SECURITY` flag has been moved to `FEATURE_FLAGS`.
I have tried to add the flag into my `superset_config.py`, but it is not working. I do have others flags in the configuration file that are already working (such as `FAVICONS`, and `APP_ICON`), and logs says conf file is loading properly, so I think the problem is not related to the file itself.

I've tried the following with no success:
```
FEATURE_FLAGS = {
    'ROW_LEVEL_SECURITY': True,
    'ALERT_REPORTS': True
}

```
```
DEFAULT_FEATURE_FLAGS = {
    'ROW_LEVEL_SECURITY': True,
    'ALERT_REPORTS': True
}
```
### Expected results
Given the above configuration, I expect seeing the `Rol Level Security` and `Alerts` options under `Settings Menu`.

### Actual results
![image](https://user-images.githubusercontent.com/22280206/108262385-9dda2980-7143-11eb-8e6c-60e0d399e994.png)

### Environment
- docker version: `20.10.3`
- docker image: `apache/superset:1.0.1`
- superset version: `1.0.1`
- python version: The one included in the docker image
- node.js version: The one included in the docker image

#### How to reproduce the bug

1. Run 
```
docker run -v "${PATH_TO_SUPERSET_CONFIG}":/app/pythonpath/superset_config.py \
                  -p <host_port>:<docker_port> \
                  --name superset-dev \
                  apache/superset:1.0.1
```
2. Create admin user
```
docker exec -it superset-dev superset fab create-admin \
               --username admin \
               --firstname Superset \
               --lastname Admin \
               --email admin@superset.com \
               --password admin

```
3. Migrate local superset DB to latest
```
docker exec -it superset-dev superset db upgrade
```
4. Load examples
```
docker exec -it superset-dev superset load_examples
```
5. Initialize superset
```
docker exec -it superset-dev superset init
```
6. Check your app in `localhost:<your_port>`, login with `admin` `admin` and drop down the Settings Menu.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
If you have indeed run `superset init` and the problem persists, I would recommend verifying that `SUPERSET_CONFIG_PATH` environment variable is correctly set in the environment where `superset init` is being run.

**Comment by carobaldino** [comment]
Thank you very much @villebro ! 

Running `superset init` fixed my problem. But it brings me a question.. should I run `superset init` each time I modify my `superset_config.py`?

Thank you! :heart:

**Comment by villebro** [comment]
> Running `superset init` fixed my problem. But it brings me a question.. should I run `superset init` each time I modify my `superset_config.py`?

Not usually, no. Some feature flags, like the RLS one, populate asditional permissions that won't otherwise get populated. But this is actually a very good point, and one we could bring up in the documentation to highlight which flags require rerunning `superset init`.
