### ISSUE TITLE
IFrame chart is lost in 1.0.1

### ISSUE THREAD

**Issue by igor-tk** [apache/superset#13198]
IFrame chart is lost in 1.0.1. 
We used this chart type to include parts of dashboards from different sources.
Will IFrame chart come back? It would be very handy.

**Comment by villebro** [comment]
@igor-tk the IFrame chart has been replaced with a native dashboard component "Markdown". See the screenshot for details:
![image](https://user-images.githubusercontent.com/33317356/108327411-0f61b880-71d4-11eb-9887-5eeeb3259148.png)

**Comment by igor-tk** [comment]
It's strange but I can't find "Markdown" chart when I try to create new one.

**Comment by junlincc** [comment]
@igor-tk Markdown is not one of the chart types, you can add it from Dashboard -> Edit view -> Components tab. 🙂

**Comment by igor-tk** [comment]
Thanks! Works like a charm. 🙂 
There is my solution:
``` html
<iframe src="https://somepath/" width="100%" height="99%"></iframe>
```
