### ISSUE TITLE
Could not find a version that satisfies the requirement apache-superset==1.0.0

### ISSUE THREAD

**Issue by Fentonfi** [apache/superset#13197]
### Expected results

During the upgrade process from 0.36.0 I see this error(Could not find a version that satisfies the requirement apache-superset==1.0.0)
Though I have done the upgrade from 0.36.0 to 0.37.0 then 0.37.0 to 0.38.0 and then from 0.38.0 to 1.0.0

### Actual results

Shows error as "Could not find a version that satisfies the requirement apache-superset==1.0.0"
### Environment

(please complete the following information):

- superset version: `superset version - apache-superset==1.0.0`
- python version: `python --version - Python 3.7.5`

**Comment by villebro** [comment]
@Fentonfi are you trying to install via pip? Here's what I'm getting:

```
$ python --version
Python 3.7.9+
$ pip install apache-superset==1.0.0
Collecting apache-superset==1.0.0
  Downloading apache-superset-1.0.0.tar.gz (34.7 MB)
...
```

So it seems to work fine with 3.7. Btw, I would recommend using 1.0.1.

**Comment by Fentonfi** [comment]
Hi Villebro,

Thanks for your response. I am trying to install using pip.

I updated the python version to 3.7.9 but I could see same error.Tried with python 3.8 too, but no progress

**_ERROR: Could not find a version that satisfies the requirement apache-superset==1.0.0
ERROR: No matching distribution found for apache-superset==1.0.0**
root@ixxxxxxx:~# python --version
Python 3.7.9

**Comment by prb219** [comment]
I see the same issue for version 1.0.1 as well 
`ERROR: Could not find a version that satisfies the requirement apache-superset==1.0.1
ERROR: No matching distribution found for apache-superset==1.0.1`

**Comment by Fentonfi** [comment]
Hi,

python3 was pointing to older version of python (python 3.6.9), because of which we had seen the above error. Now python3 binary points to the correct version.
After making this change we had to install few pip packages as mention below
python -m pip install --upgrade pip
pip install --ignore-installed PyYAML
apt-get install build-dep python-psycopg2
pip install psycopg2
pip install psycopg2-binary
pip install apache-superset==1.0.1
superset db upgrade

this will install the latest version of apache-superset.

Thanks for your inputs Villebro. :)

Regards
