### ISSUE TITLE
[Explore]Customize X-axis debounce is broken

### ISSUE THREAD

**Issue by junlincc** [apache/superset#13191]
"it debounces input itself rather than rendering (in video I tried to type "Test", only "T" got in)." 

https://user-images.githubusercontent.com/67837651/108285059-2ef8d280-713b-11eb-975f-5b33d55b8bdf.mov

Thanks for spotting the issue! @kgabryje 

Need to test other input fields and chart too

**Comment by ktmud** [comment]
I also noticed this while reviewing the Graph chart: https://github.com/apache-superset/superset-ui/pull/918#discussion_r575774006

**Comment by junlincc** [comment]
resolved
