### ISSUE TITLE
[todo]Ability to re-rerun CI failed jobs

### ISSUE THREAD

**Issue by michael-s-molina** [apache/superset#13206]
Today when we need to re-run CI jobs we need to force a push or open/close a PR to trigger CI execution. It would be great if we could just re-run failed jobs.

As @villebro suggested, we can implement something like `/rerun failed` to accomplish that.

This functionally would improve CI processing time and speed up PR reviews.

@villebro @rusackas @junlincc

**Comment by junlincc** [comment]
@michael-s-molina thanks for suggesting! please go-ahead and make the improvement. anything that can improve developer experience and process efficiency make sense to be prioritized. 🙂

**Comment by rusackas** [comment]
The https://github.com/apache-superset/superset-github-bot could probably be leveraged here too, to perform some actions with emoji-driven processes. For example:

Restart failed CI jobs:
🤖🔄

Merge when CI passes
🤖🚀

Cancel CI Jobs
🤖🛑

**Comment by junlincc** [comment]
Let's move and add this to a Github project @rusackas
