### ISSUE TITLE
[Alerts & Reports]Allow 'Raw data' report for chart in new 'Alerts & Reports' UI.

### ISSUE THREAD

**Issue by kamalkeshavani-aiinside** [apache/superset#13202]
**Is your feature request related to a problem? Please describe.**
The old UI for 'Chart Email Schedules' has an option to send Visualization or Raw data in the email/slack. This option of sending 'Raw data'(csv) is not available in new UI.
Due to issue of too many repeat notifications using old UI, I cannot use old UI as well for now.

**Describe the solution you'd like**
When the user selects 'Message Content' as '**Chart**', another dropdown should allow the user to select the 'Message format' as 'Visualization' or 'Raw data'(with default of visualization).

**Describe alternatives you've considered**

**Additional context**

New UI:
![image](https://user-images.githubusercontent.com/74634977/108328195-a7c95e80-720f-11eb-9482-8815089af74e.png)

Old UI:
![image](https://user-images.githubusercontent.com/74634977/108328091-87999f80-720f-11eb-8baa-a3ee357c7204.png)

**Comment by willbarrett** [comment]
Hi @kamalkeshavani-aiinside thanks for the report! I've seen another request for CSV report types, so this is something we'll be looking into.

**Comment by kamalkeshavani-aiinside** [comment]
@willbarrett Just wanted to point that csv raw data reporting feature is lost(in a way) in Superset v1.0.x, since the old 'Chart Email Schedule' cron job has some issues.
So although I understand that PDF reporting(and maybe another option) is also under consideration, I would request to at least make csv reporting usable again in v1.1

**Comment by willbarrett** [comment]
Hi @kamalkeshavani-aiinside - thanks for clarifying the issue. We'll prioritize adding "Raw Data" export to the new reports, but it is unlikely to make v1.1 at this point given that the branch has been cut. However, knowing that this is functionality missing from the new Alerts & Reports that was in the old, I'll put it on the top of the stack for enhancements to this system for my team at Preset. I'm sorry that I can't provide an ETD at this point.

**Comment by lilykuang** [comment]
closing this issue since the feature was merged.
