### ISSUE TITLE
[Alerts & Reports] Can't switch 'Message content' from a Chart to a Dashboard

### ISSUE THREAD

**Issue by vnourdin** [apache/superset#13207]
When I configure an Alert or a Report from the new `ALERT_REPORTS` interface, I can change the chart that is sent ("Message content") but if I replace the chart by a dashboard, when saving, the alert/report switch back to the old chart.

### Expected results
I can modify an alert/report and switch from any chart to any dashboard and vice versa.

### Actual results
From what I've tested, the current state is:
* from a dashboard to another one :heavy_check_mark:
* from a dashboard to a chart :heavy_check_mark:
* from a chart to another one :heavy_check_mark: 
* from a chart to a dashboard :heavy_multiplication_x: 

#### Screenshots
![chart-to-dashboard](https://user-images.githubusercontent.com/11643685/108359740-ab012200-71f0-11eb-9356-293979b4b7af.gif)

#### How to reproduce the bug
1. Go to 'Settings' → 'Alerts & Reports'
2. Click on '+ Alert' to create a new one
3. Fill it and choose a 'Chart' as content
4. Save
5. Edit your alert, change content to a 'Dashboard'
6. Save
7. Edit your alert again, the content should be back to the old 'Chart'

### Environment
- superset version: `1.0.1`
- python version: `3.7.9`
- node.js version: doesn't apply, I run on Kubernetes, using gunicorn as server

**Comment by willbarrett** [comment]
Thank you for the bug report @vnourdin - we'll look into it!

**Comment by lilykuang** [comment]
this issue should be fixed. i will close this.
