### ISSUE TITLE
Table Viz errors with filters containing number column "IS NOT NULL" or "IS NULL"

### ISSUE THREAD

**Issue by michellethomas** [apache/superset#13229]
On the table viz if someone adds a filter with a numeric column and the filter type "IS NOT NULL" or "IS NULL". The chart errors on [this line](https://github.com/apache/superset/blob/master/superset/connectors/sqla/models.py#L1079) with:

```
File "superset/connectors/sqla/models.py", line 1080, in get_sqla_query
    eq = utils.cast_to_num(flt["val"])
KeyError: 'val'
```
I looked at this line and I don't see anything that has changed recently so I'm assuming that this is related to some change with the table viz. But I'm not sure how it should be handled, the filter has no "val" because it is just an "IS NULL" filter.

### Expected results

Chart should load

### Actual results

Chart errors

#### How to reproduce the bug

1. Create a table chart
2. Add a filter on a numeric column with column "IS NOT NULL"
3. Run query and see error

### Environment

(please complete the following information):

- superset version: `master`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

@ktmud do you have any ideas about whether a recent table change might have caused this issue?

**Comment by junlincc** [comment]
@ktmud please let us know if this is not related to your change. happy to take it on.

**Comment by ktmud** [comment]
@junlincc I'm working on it

**Comment by bkyryliuk** [comment]
@ktmud is it still smth you are working on ?

**Comment by ktmud** [comment]
Yes, a PR is almost ready
