### ISSUE TITLE
Actual time range Access is Denied 

### ISSUE THREAD

**Issue by userguy** [apache/superset#13236]
I am getting Access is Denied in Time Range . 

Actual time range
Access is Denied and Not able to apply the time selected . 

GET /api/v1/time_range/?q=%27DATEADD(DATETIME(%222021-02-19T00:00:00%22),%20-7,%20day)%20:%202021-02-19T00:00:00%27 HTTP/1.1" 401 -

INFO:werkzeug:10.25.210.220 - - [19/Feb/2021 20:45:53] "GET /api/v1/time_range/?q=%27DATEADD(DATETIME(%222021-02-19T00:00:00%22),%20-7,%20day)%20:%202021-02-19T00:00:00%27 HTTP/1.1" 401 -
INFO:werkzeug:10.25.210.220 - - [19/Feb/2021 20:48:20] "GET /api/v1/time_range/?q=%27previous%20calendar%20week%27 HTTP/1.1" 401 -
INFO:werkzeug:10.25.210.220 - - [19/Feb/2021 20:48:22] "GET /api/v1/time_range/?q=%27Last%20week%27 HTTP/1.1" 401 -
INFO:werkzeug:10.25.210.220 - - [19/Feb/2021 20:48:24] "GET /api/v1/time_range/?q=%27Last%20month%27 HTTP/1.1" 401 -

DB connection is mariadb . Works fine with 0.38

![image](https://user-images.githubusercontent.com/11783537/108523981-90b06c80-72f4-11eb-9584-863a327349d5.png)

**Comment by junlincc** [comment]
@userguy I believe 0.38 was the old time picker right? 
confirmed actual time range is working properly on the main dbs.

**Comment by userguy** [comment]
So i figured out , what was causing it , I think there was older version of superset which was previously running on the machine . I remove the superset.db and did user and init step again and that solved the problem . 

Thanks

**Comment by iercan** [comment]
We had same issue for some user roles and solved it by adding `can time range on Api` permission

version: 1.1.0

**Comment by fccoelho** [comment]
> We had same issue for some user roles and solved it by adding `can time range on Api` permission
> 
> version: 1.1.0

This permission is not available on 1.2 in the role configuration dialog

**Comment by zhaoyongjie** [comment]
> > We had same issue for some user roles and solved it by adding `can time range on Api` permission
> > version: 1.1.0
> 
> This permission is not available on 1.2 in the role configuration dialog

Could you try to run `superset init`?

**Comment by fccoelho** [comment]
I did run it, and it did solve the problem. Thank you.
