### ISSUE TITLE
Resizing row and column vs chart behaves differently in Dashboard Edit Mode

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#13240]
When a user is trying to resize charts on dashboards, they behave differently based on if it is a row or a column, or just a chart. 

Chart can be resized by going to the bottom right corner, in both directions (width or height).

If you add a row or a column on the dashboard, those can be resized (in one of the directions) by going to the size of the object.

In the two cases, the mouse hover will look differently (hard to see in the video recording). Users can't always figure out how to resize chart inside a row or column and assume the functionality is broken.

See the two behaviors:
![resizing_row_vs_chart](https://user-images.githubusercontent.com/61221714/108543252-af354a00-7299-11eb-8e92-4f08bc406f5b.gif)

**Describe the solution you'd like**
Consider making the resizing experience consistent.

**Comment by zuzana-vej** [comment]
Added the bug label since we confirmed with few users that in the past the experience was consistent across resizing chart and row / column.

**Comment by junlincc** [comment]
Expected behavior could have been changed by us bumping the drag and drop library by 9 major versions recently. 
is the new behavior problematic? or do you think users can slowly adapt? 
@zuzana-vej

**Comment by zuzana-vej** [comment]
Users can always adapt over time :). They found it confusing / thought there was a high pri bug, but if this is part of the library there might not be a lot we can do easily. We can all keep an eye on this and see if there are other user reports.

**Comment by zuzana-vej** [comment]
Based on our past discussion within Airbnb, @graceguo-supercat might look into this and either resolve or close this issue/request. (keeping open for now)

**Comment by junlincc** [comment]
resolved. closing
