### ISSUE TITLE
[explore] metadata panel should show numeric icon for `REAL` data type

### ISSUE THREAD

**Issue by mistercrunch** [apache/superset#13247]
<img width="704" alt="Screen Shot 2021-02-19 at 3 53 08 PM" src="https://user-images.githubusercontent.com/487433/108573976-e3752e80-72ca-11eb-9d7d-a9b81dc67236.png">

**Comment by junlincc** [comment]
@mistercrunch this one goes under a bigger epic 
https://github.com/apache/superset/issues/12961

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.

**Comment by mistercrunch** [comment]
time for some spring cleaning
![LbHKqMR](https://github.com/apache/superset/assets/487433/70b413e1-1366-42d7-b7b2-aa3cdef8cac0)
