### ISSUE TITLE
[Explore][Control] Allow selecting ad-hoc metrics in filters

### ISSUE THREAD

**Issue by ktmud** [apache/superset#13249]
When adhoc filters were first added ( #4909 ), it can select from selected adhoc metrics. Part of the code is also still there, but the feature somehow stopped working from certain point.

Could be related to #12095

**Comment by ktmud** [comment]
I discovered this while working on #13221 

Will take a look once more refactoring is done.

**Comment by junlincc** [comment]
> Will take a look once more refactoring is done.

happy to take it on while we are refractor the filter component in a few weeks. @ktmud 
@zuzana-vej can you provide a complete list of expected behavior in ad hoc filter and metric popover, + new features suggestion (i.e, in-place saving metric)?

**Comment by ktmud** [comment]
Two feature requests I've been thinking on for a while:

1. **Adhoc Column:** similar to adhoc metrics, users should also be able to create adhoc calculated columns (dimensions)
2. **Adhoc metric/column in other controls:** users should be able to select already created adhoc metrics and columns in other controls (e.g. sort by and filters).

**Comment by villebro** [comment]
> Two feature requests I've been thinking on for a while:
> 
> 
> 
> 1. **Adhoc Column:** similar to adhoc metrics, users should also be able to create adhoc calculated columns (dimensions)
> 
> 2. **Adhoc metric/column in other controls:** users should be able to select already created adhoc metrics and columns in other controls (e.g. sort by and filters).

Big +1 for adhoc columns!

**Comment by junlincc** [comment]
@villebro @ktmud take a look the draft 1 year roadmap for Explore.send me comments, thoughts before I finalize?

<img width="1510" alt="Screen Shot 2021-02-21 at 9 02 11 AM" src="https://user-images.githubusercontent.com/67837651/108632430-c142f400-7423-11eb-878b-034e4c46c0e9.png">
<img width="1484" alt="Screen Shot 2021-02-21 at 9 03 08 AM" src="https://user-images.githubusercontent.com/67837651/108632439-ce5fe300-7423-11eb-949d-f4086ea861a7.png">

**Comment by zhaoyongjie** [comment]
> Two feature requests I've been thinking on for a while:
> 
>     1. **Adhoc Column:** similar to adhoc metrics, users should also be able to create adhoc calculated columns (dimensions)
> 
>     2. **Adhoc metric/column in other controls:** users should be able to select already created adhoc metrics and columns in other controls (e.g. sort by and filters).

I'm trying to redesign the semantic layer, it might help. these are a good request.

**Comment by junlincc** [comment]
Thank you all for suggesting new features. 
committed to both.

**Comment by rusackas** [comment]
Since this has gone stale, and adhoc columns are effectively "a thing" nowdays, I'll close this out, but if there's more to track down, maybe we can open a fresh thread with updated context.
