### ISSUE TITLE
[explore] Show detailed data type tooltip when hovering type icon

### ISSUE THREAD

**Issue by mistercrunch** [apache/superset#13248]
Minor improvement: it would be nice to show the type as in `VARCHAR(50)` when hovering the icon in the metadata panel (`ABC` icon in the screenshot bellow)

<img width="372" alt="Screen Shot 2021-02-19 at 3 57 38 PM" src="https://user-images.githubusercontent.com/487433/108574083-364ee600-72cb-11eb-8bdd-d0e5ef993349.png">

**Comment by junlincc** [comment]
@mistercrunch 
one more related #13252 https://github.com/apache/superset/issues/13252

**Comment by ved-kashyap-samsung** [comment]
@junlincc Can you please assign this issue to me.
