### ISSUE TITLE
[Explore]severe input delay in Edit dataset modal 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#13251]
see video, getting 3s second delay after typing. can we have a standard across the entire product? 

https://user-images.githubusercontent.com/67837651/108576881-022bf300-72d4-11eb-94d2-1c6b9e6e1c9c.mov

**Comment by kgabryje** [comment]
Can't reproduce @junlincc 

https://user-images.githubusercontent.com/15073128/126130997-5cb08c2b-acf3-45ac-ab1f-6fffac7ef2aa.mov
