### ISSUE TITLE
[Explore][Time Picker] Tooltip should have a top and bottom border 

### ISSUE THREAD

**Issue by ktmud** [apache/superset#13263]
## Description

Currently the time picker help text tooltip does not have a top and bottom border, resulting this weird look:

![Snip20210221_23](https://user-images.githubusercontent.com/335541/108645569-23254d00-7468-11eb-82bd-b5c8d2c7badd.png)

We should add a padding to the tooltip content wrapper (the one with black background) and let the content itself scroll instead.

cc @zhaoyongjie

**Comment by rusackas** [comment]
This is likely fixed by now, and is quite outdated if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
