### ISSUE TITLE
calculated columns creation using datasetput api 

### ISSUE THREAD

**Issue by madhamanchiharsha** [apache/superset#13267]
HI,
I am automating our dashboard creation using apis. We have to create a calculated columns in our datasets. I have done the same from UI and added a sample image here.In order to create the calculated columns, I am using /api/v1/dataset/{pk} api. However these are the problems I am facing:
 When I try this in swagger: validation fails for override_columns (I have tried false/False/FALSE/0).
 When I try this is in postman. I get the following error saying "Datasource already exists".

### Expected results

we need to get response as 201 for creating calculated columns in dataset api

### Actual results

In swagger validation failing for override columns field.

#### Screenshots
![image](https://user-images.githubusercontent.com/14903753/108668971-240abd00-7502-11eb-8180-b284ea3d4207.png)

### Environment

(please complete the following information):

- superset version: 1.0
- python version: 3.8

**Comment by villebro** [comment]
@dpgaspar can you take a look at this?

**Comment by dpgaspar** [comment]
@madhamanchiharsha Can you please add few examples of the POST payload and response

**Comment by madhamanchiharsha** [comment]
headerPart:
http://127.0.0.1:8088/api/v1/dataset/72?override_columns=False
bodyPart:
{
  "database_id": 1,
  "schema": "null",
  "table_name": "examples",
  "columns": [
    {
      "column_name": "example1",
      "description": null,
      "expression": "split_part(\"IterationPath\", '\\', 3)",
      "filterable": true,
      "groupby": true,
      "python_date_format": null,
      "verbose_name": "example1"
    },
    {
      "column_name": "example2",
      "description": null,
      "expression": "split_part(\"IterationPath\", '\\', 4)",
      "filterable": true,
      "groupby": true,
      "python_date_format": null,
      "verbose_name": "example2"
    },
    {
      "column_name": "example3",
      "description": null,
      "expression": "split_part(\"AreaPath\", '\\', 2)",
      "filterable": true,
      "groupby": true,
      "python_date_format": null,
      "verbose_name": "example3"
    }
  ]
}

**Comment by one-data-cookie** [comment]
I'm facing the same issue. 😢 

Any news on this, @dpgaspar? Or any chance you got this resolved, @madhamanchiharsha?

**Comment by zuzana-vej** [comment]
@one-data-cookie @madhamanchiharsha please reopen this ticket/file new ticket if you are still facing the same issue on the latest version / master
