### ISSUE TITLE
Feature Request: Add last business day option to time range filter

### ISSUE THREAD

**Issue by amitmaharana** [apache/superset#13261]
**Is your feature request related to a problem? Please describe.**
I am working on a dataset that does not have data for weekends. Currently, the time range filters supported are based on the calendar irrespective of the presence of data. If I search on a Monday using the last day filter then no results were returned, as expected.

**Describe the solution you'd like**
It would be great if there was an option to filter based on availability of data or the `last business day`.

**Describe alternatives you've considered**
I have tried extracting the `maxTime` value from the Druid datasource metadata which gives me the `last business day` but haven't been successful in applying it as a filter within the `date_parser` code.

**Additional context**
![Image of Time Range](https://i.imgur.com/66nvROq.png)

**Comment by ktmud** [comment]
You can currently utilize the Advanced date functions to get this:

```python
dateadd(datetrunc(datetime('today'), week), 5, day)
```

Check out more about this functions in this tooltip:

<img src="https://user-images.githubusercontent.com/335541/108645303-44d20480-7467-11eb-9dc8-8689426ef6ac.png" width="500">

**Comment by NikolayZakharevich** [comment]
> You can currently utilize the Advanced date functions to get this:
> 
> ```python
> dateadd(datetrunc(datetime('today'), week), 5, day)
> ```


I don't understand how to use Advanced date functions to achieve the requested functionality as they don't support conditional expressions.

Let's say we have a dataset that does not have weekend data. The desired behaviour of the "last business day" option should return:
- on Monday: `Friday <= col <= Friday`
- on Tuesday: `Monday <= col <= Monday`
- on Wednesday: `Tuesday <= col <= Tuesday`
- on Thursday: `Wednesday <= col <= Wednesday`
- on Friday: `Thursday <= col <= Thursday`
- on Saturday: `Friday <= col <= Friday`
- on Sunday: `Friday <= col <= Friday`


The suggested expression works for Monday but not for the rest days of the week. What could be the alternative?
