### ISSUE TITLE
Filter Box - Horizontal Scroll Bar always visible

### ISSUE THREAD

**Issue by ValentinC-BR** [apache/superset#13279]
## Screenshot

![image](https://user-images.githubusercontent.com/79460908/108720808-9048e900-7521-11eb-81ba-e11bf9f66ab7.png)

## Description

In the "Filter Box" chart, the horizontal scroll bar is always visible, whatever the chart size is.
I've checked the possible values, they're not that large.

## Design input

/

## Environment

Superset version : 1.0.1

**Comment by jcalhinho** [comment]
same problem, fix with css template

**Comment by junlincc** [comment]
I believe this issue has been fixed in master, but for stability you may still wanna stay on v1.0.1 since this issue is trivial? 
<img width="1339" alt="Screen Shot 2021-02-22 at 9 54 56 PM" src="https://user-images.githubusercontent.com/67837651/108807203-9f975900-7558-11eb-8402-d3dfab4eda2a.png">

**Comment by scimas** [comment]
@junlincc Are you referring to #12621? That PR is closed and not merged. And the fix does not seem to be in 1.1.0 either. Apologies if it's fixed in a different PR/commit in master that isn't included in 1.1.0.

**Comment by kristw** [comment]
Still seeing the problem

**Comment by uhuhh** [comment]
in version 1.3.0 still appears.

**Comment by fritshermans** [comment]
> same problem, fix with css template

@jcalhinho, how did you adjust the CSS to solve this problem?

**Comment by scimas** [comment]
```
.filter_box > div {
  overflow-x: hidden !important;
}
```
Is one way to do it.
I don't believe it works without the `!important`
