### ISSUE TITLE
publish superset helm chart to https://artifacthub.io/ 

### ISSUE THREAD

**Issue by amitmiran137** [apache/superset#13287]
**Is your feature request related to a problem? Please describe.**
As a kubernetes based deployment provider, I would like to use the helm chart provided officially by superset instead copying source files to my deployment solution

**Describe the solution you'd like**
start publishing helm artifact to https://artifacthub.io/  on every change to the chart
manage versioning by bumbing the chart version

**Describe alternatives you've considered**
copying chart files and building the chart using helm 

**Additional context**
There are GitHub actions that support this:
option 1: https://github.com/helm/chart-releaser-action

#### existing helm chart(not official)
![image](https://user-images.githubusercontent.com/47772523/108751407-d5354580-754a-11eb-8b14-1bca31a303db.png)

Any other solution proposals will be welcomed: @Yann-J @craig-rueda @nytai @willbarrett @vnourdin

**Comment by jplanckeel** [comment]
Hi, i re-open this subject. I see for apache airflow, it publicate on artifacthub. can you see to integrate this ? I can help to write the PR.

**Comment by Yann-J** [comment]
I had a quick look at how the helm chart is being published, and it looks like auto-releasing of the Helm chart is already working pretty well, with packages being published as a Github release, and the registry manifest being exposed as Github Pages at http://apache.github.io/superset/index.yaml

So the only thing left to do is advertise this on https://artifacthub.io or other package indexers. These sites do not host anything they just scrape and index packages by reading the manifests.

So I think what needs to be done is to:

- Create an appropriate organization in Artifacthub => Done, see https://artifacthub.io/packages/search?org=superset&sort=relevance&page=1
- Add the Github pages repo manifest to scan => Done, see https://artifacthub.io/packages/helm/superset/superset

Next steps:
- Add an [artifacthub-repo.yml](https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml) metadata file to validate ownership and provide repo information. I've done this in PR #20722 
- Add the Artifacthub badge somewhere in the README / docs? [![Artifact Hub](https://img.shields.io/endpoint?url=https://artifacthub.io/badge/repository/superset)](https://artifacthub.io/packages/search?repo=superset)
- Clarify organization ownerhsip in artifacthub
- Beautify the publication - add a `README` to the Helm chart so it shows up in ArtifactHub, an icon in the `Chart.yaml`...

**Comment by Yann-J** [comment]
Looping in @craig-rueda for comments maybe?

**Comment by craig-rueda** [comment]
Thanks, @Yann-J . I left a comment over on #20722 for you.

**Comment by craig-rueda** [comment]
Also, did you need to create an account in artifacthub to get this working?
