### ISSUE TITLE
Can't see Manage > *Email*

### ISSUE THREAD

**Issue by dusatvoj** [apache/superset#13298]
### Expected results
As in [docs](https://superset.apache.org/docs/installation/email-reports)

### Actual results

Can't see any settings related to emails

#### Screenshots

![image](https://user-images.githubusercontent.com/11560794/108840375-89c87900-75d6-11eb-8663-8c41f7fb4149.png)

#### How to reproduce the bug

Folow the docs but no `Manage > *Email*` section

### Environment

(please complete the following information):

- superset version: `1.0.1`
- python version: `3.8.7``
- node.js version: `v12.18.4`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by willbarrett** [comment]
Hi @dusatvoj - I would wager that the relevant configuration flag is not enabled, or your server has not been restarted after the configuration was edited. Please ensure that you have the configuration flags referenced in the documentation set to `True`, and perform a restart of the Superset process. Let us know if that does not resolve your issue.

**Comment by dusatvoj** [comment]
```
#---------------------------------------------------------
# Enable email notifications and reports
#---------------------------------------------------------
ENABLE_SCHEDULED_EMAIL_REPORTS = True
EMAIL_NOTIFICATIONS = True
```
My server was restarted :thinking:

**Comment by dusatvoj** [comment]
Oh, I've found an issue. I haven't run `superset init` again :O
