### ISSUE TITLE
pie chart date format

### ISSUE THREAD

**Issue by Riskatri** [apache/superset#13293]
hi, i make a pie chart using apache superset and have a periode data but the data getting value 1491829101010 not a date format. if i want to change the value to date format as my data in database. what should i do?

**Comment by junlincc** [comment]
Hi @Riskatri please fill out the issue template with details, screenshot, reproduce steps, and your current version. if you are not on the latest v1.0.1, please do check it out and lmk.

**Comment by Riskatri** [comment]
> Hi @Riskatri please fill out the issue template with details, screenshot, reproduce steps, and your current version. if you are not on the latest v1.0.1, please do check it out and lmk.

hi, i use apache superset version 1.0.1, 
i have data period as datetime in my database and then i create a pie chart but the periode value like this 
![Capture](https://user-images.githubusercontent.com/59104917/108808516-5f2bef80-75d9-11eb-9260-dbcd8446435e.PNG)

period value in my database like this '2019-02-23'

**Comment by 0101Unkown0101** [comment]
Ummm how did you get my email and who are you????

**Comment by eugeniamz** [comment]
@junlincc  I verified this issue

**Comment by rosemarie-chiu** [comment]
This is still an issue:
<img width="1791" alt="CleanShot 2021-12-06 at 20 00 38@2x" src="https://user-images.githubusercontent.com/52086618/144842580-9c69c2c3-873a-45aa-a8d0-101404eb955c.png">
![Uploading CleanShot 2021-12-06 at 20.01.19@2x.png…]()

**Comment by stephenLYZ** [comment]
@rosemarie-chiu @eugeniamz Heya, I'm following this issue, but I cannot reproduce. Can I get more reproduce paths?

**Comment by villebro** [comment]
@kgabryje I think you did some related work fairly recently, do you remember if you were able to fix this?

**Comment by kgabryje** [comment]
I can reproduce this issue on latest master. @stephenLYZ Have you tried grouping by a temporal column?
![image](https://user-images.githubusercontent.com/15073128/148071764-ae15a831-3b9e-4a82-ad8e-c2258e4a936a.png)

@villebro I worked on Big Number and Calendar, looks like Pie chart also needs some polishing

**Comment by stephenLYZ** [comment]
@kgabryje yeah. Weird, latest master branch
![image](https://user-images.githubusercontent.com/11830681/148356181-00cfb268-7c1a-4506-b6a5-79b3ccd71e6e.png)

**Comment by rusackas** [comment]
I just tried @stephenLYZ 's example on my local, and it's broken. I'm not sure what's special about your environment/setup that might make it different. Are you hosting the examples data in an unusual database or something?

**Comment by rusackas** [comment]
@kgabryje will take a look if @stephenLYZ can't reproduce this.
