### ISSUE TITLE
Follow up to: #13128 Maximize charts: wrong height calculated 

### ISSUE THREAD

**Issue by Arktiswind** [apache/superset#13297]
Hi again,
I unfortunately have to open a new issue. The problem is similar to my old issue 8 days ago.
Told my colleague he can start building his own charts and the problem is back. Well, kind of...
On his PC the new barChart is cut off again in maximized mode:
https://www.telesys.de/wp-content/uploads/supersetBarChart2.png

On my PC everything is well with the same chart on the same dashboard:
https://www.telesys.de/wp-content/uploads/supersetBarChart1.png

We testet on Chrome, Firefox and Edge. Latest version each. All 3 behave the same: for me the chart looks great in maximized mode, for him not. It is a little strange ;-)

The only difference i see at first glance is our screen resolution:
I have 2560x1440 with Windows scaling 125%.
He has 1920x1080 with a Windows scaling 150%

### Expected results

maximized mode works for both of us.

### Actual results

see above

#### Screenshots

https://www.telesys.de/wp-content/uploads/supersetBarChart2.png
https://www.telesys.de/wp-content/uploads/supersetBarChart1.png

#### How to reproduce the bug

I really don't know...

### Environment

(please complete the following information):

- superset version: 1.0.1
- python version: 3.7.3

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by khaa-dv** [comment]
Hey! I have a similar problem. 
To reproduce the problem, you need to place the chart below the visible area of the screen so that the vertical scroll bar appears. If the chart is at the top and there is no scroll bar, then there is no problem.
@junlincc, @Arktiswind

**Comment by khaa-dv** [comment]
@Arktiswind , @jeremi , @junlincc, @moonboots 
I seem to have found a solution.

1. In the directory where install superset open directory 
`#>  ./static/assets/`
2. open the file for editing **dashboard123123123.js**
_(the name of the dashboard123123123.js file may differ for everyone)_
3. find the phrase **document.body.clientHeight-32** in it and replace it with **window.innerHeight-32**
4. Save the file and refresh the page via **Shift + F5**

**Comment by junlincc** [comment]
@khaa-dv confirmed the issues on master, thanks for proposing the solution, you are welcome to push a fix. 🙏
