### ISSUE TITLE
apache superset datetime format

### ISSUE THREAD

**Issue by Riskatri** [apache/superset#13295]
hi, i use apache superset version 1.0.1,
i have data period as datetime in my database and then i create a pie chart but the periode value like this
![Capture](https://user-images.githubusercontent.com/59104917/108809763-25101d00-75dc-11eb-89ff-f4b3479cbf1d.PNG)

the periode value in database like this 
![periode](https://user-images.githubusercontent.com/59104917/108809828-45d87280-75dc-11eb-802b-3ed0c93fabf5.PNG)

**Comment by villebro** [comment]
Thanks for reporting this @Riskatri . We've recently added better column typing metadata to the chart requests, so we should be able to add proper date formatting to the labels now. @junlincc I propose trying to tackle this soon to set a precedent for how charts should handle temporal columns in labels.

**Comment by Riskatri** [comment]
thankyou @villebro but i need the visualization data right now. any solution to solve this problem? i have tried to change datetime format to string format. its work for label pie chart, but it cannot be filtered using filter box time range

**Comment by villebro** [comment]
@Riskatri please be mindful that this is an open source project, hence we have limited resources to respond to community feature requests. In the meantime I recommend creating a calculated column in which you format the dates as strings and then group by them instead of the original temporal column.

**Comment by Riskatri** [comment]
thankyou @villebro , your recommend work for me 
![date](https://user-images.githubusercontent.com/59104917/108817271-33fdcc00-75ea-11eb-8c65-f55fdec2daa8.PNG)

**Comment by zuzana-vej** [comment]
This looks resolved; if you still have a feature request @Riskatri please open an Idea under Discussion section.
