### ISSUE TITLE
Unable to Use Jinja Context for "url_param" 

### ISSUE THREAD

**Issue by ranggarppb** [apache/superset#13315]
### Expected results

It gives 'rangga' as the parameter of username in url

### Actual results

It returns None

#### Screenshots

![image](https://user-images.githubusercontent.com/44335152/108995403-a694a780-76cf-11eb-9ac5-69e87f27dfea.png)

#### How to reproduce the bug

0. Activate your jinja context in superset/docker/pythonpath_dev/superset_config.py by adding "ENABLE_TEMPLATE_PROCESSING" : True in dictionary of FEATURE_FLAGS
![image](https://user-images.githubusercontent.com/44335152/108995785-29b5fd80-76d0-11eb-90d1-649de0704a90.png)

1. Go to sqllab
2. Edit your url and add '?username' argument
3. Reload the page
4. Write the query using jinja context of url_param and run the query

### Environment

(please complete the following information):

- superset version: 1.0.1 (docker version)
- python version: 3.7.9

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by robdiciuccio** [comment]
Confirmed

**Comment by maltoze** [comment]
The bug was caused by this PR: https://github.com/apache/superset/pull/8256

https://github.com/apache/superset/pull/8256/files#diff-adb44dfd0f0ed41256a2b5aa78da261268394042c37c2adbff36775f628ead5aL223
