### ISSUE TITLE
cannot display label percentage value in pie chart

### ISSUE THREAD

**Issue by Riskatri** [apache/superset#13310]
Hi, i want to change label to percentage value in pie chart. but the percentage cannot display here. i am using apache superset version 1.0.1 
![turjawali](https://user-images.githubusercontent.com/59104917/108958124-19d4f400-76a5-11eb-8138-8dab059bf4f4.PNG)

**Comment by junlincc** [comment]
Hi @Riskatri, thanks for reporting. this issue has been fixed in master. :) 

https://user-images.githubusercontent.com/67837651/109409788-5ffeb180-794a-11eb-9cab-2a2f13fb82da.mov
