### ISSUE TITLE
value of result timestamp in chart big number with trendline doesnt match with database

### ISSUE THREAD

**Issue by Riskatri** [apache/superset#13328]
- i am using apache superset version 1.0.1
- i create chart big number with trendline
i have database like this 
![image](https://user-images.githubusercontent.com/59104917/109099810-48f76e00-7756-11eb-9a61-2f0a7448a874.png)

but when i am using chart big number with trendline, value of periode doesnt match with my data 
![image](https://user-images.githubusercontent.com/59104917/109099991-94aa1780-7756-11eb-80d7-8007a97d046c.png)

value of periode or timestamp in chart minus one year from my database, but i want the timestamp value match with my data in database

**Comment by zuzana-vej** [comment]
@Riskatri  are you still experiencing this issue? Noticed this is over a year old report. Please confirm - thanks!

**Comment by rusackas** [comment]
Since this is now going on two years old with no additional context, I'm inclined to close it out. Happy to re-open if anyone is able to repro in current Superset.
