### ISSUE TITLE
Bug: dashboard color scheme doesn't apply to charts

### ISSUE THREAD

**Issue by amitmiran137** [apache/superset#13335]
When updating a color scheme it is only applied on the fly
but when refreshing the page. the chosen color scheme is not applied although it is the selected one in the dashboard metadata

### Expected results
upon page refresh selected color scheme should be applied
### Actual results

color scheme changes to default

#### Screenshots

https://user-images.githubusercontent.com/47772523/109135692-033fa300-7760-11eb-9a8d-7f7dbbf852aa.mov

#### How to reproduce the bug

1. Edit dashboard color scheme and save
2. refresh the dashboard page
4. see that the color scheme doesn't get applied

### Environment

(please complete the following information):

- superset version: master and 1.0.1
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
Thanks for reporting! confirmed that this is an issue on master.  this behavior used to be the opposite, meaning, colors change don't get saved on SAVE, user has to refresh page to see change, which is less problematic.

Tagging P1. 

@geido Diego, sorry for pulling you out from the testing project, could you help on this one? many thanks!

**Comment by geido** [comment]
Sure I'll have a look @junlincc

**Comment by amitmiran137** [comment]
this was fixed
