### ISSUE TITLE
Can not connect to Mysql 8 database in Docker

### ISSUE THREAD

**Issue by darksgit** [apache/superset#13333]
I am trying to setup simple installation with Superset and Mysql 8 in docker
Initially I tried amancevice/superset:1.0.1 and 1.0.0 images and after facing the error I switched to  [docker-compose-non-dev.yml](https://github.com/apache/superset/blob/master/docker-compose-non-dev.yml) compose file. It uses 

_apache/superset:latest_ 

image, superset version returns 

_Superset 0.999.0dev._

I added mysql 8 to the compose file:

  _db8:
    container_name: db8
    image: mysql:8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      --general_log=1 --general_log_file=/var/lib/mysql/mysql.log
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: superset
      MYSQL_USER: superset
      MYSQL_PASSWORD: superset_

When I tried to connect to the mysql 8 database using connection string:

_mysql://superset:superset@db8/superset_

 I got error message at superset ui:

_ERROR: Connection failed, please check your connection settings_

Mysql log file for the connection attempt:

_2021-02-25T08:55:39.695099Z         9 Connect   superset@172.22.0.8 on superset using TCP/IP
2021-02-25T08:55:39.695151Z         9 Connect   Access denied for user 'superset'@'172.22.0.8' (using password: NO)_

Superset log:

_172.22.0.1 - - [25/Feb/2021:09:08:27 +0000] "POST /api/v1/database/test_connection HTTP/1.1" 422 71 "http://localhost:8088/databaseview/list/?pageIndex=0&sortColumn=changed_on_delta_humanized&sortOrder=desc" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0"_

From mysql log it seems like password from connection string was not used.

I tried to create mysql user without password:

_CREATE USER 'user'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'user'@'%';_

and connect using this user, connection string is:

_mysql://user@db8/superset_

got same error from superset ui and same line at superset log, but no 'Access denied' message at mysql log this time:

_2021-02-25T09:13:34.063123Z        12 Connect   user@172.22.0.8 on superset using TCP/IP_

When I tried the same with mysql 5 everything worked perfect.

I also found older issue that may be related - #1070

whole compose file:

x-superset-image: &superset-image apache/superset:latest
x-superset-depends-on: &superset-depends-on
  - db
  - redis
x-superset-volumes: &superset-volumes
  - ./docker:/app/docker
  - superset_home:/app/superset_home

version: "3.7"
services:
  redis:
    image: redis:3.2
    container_name: superset_cache
    restart: unless-stopped
    volumes:
      - redis:/data

  db:
    env_file: docker/.env
    image: postgres:10
    container_name: superset_db
    restart: unless-stopped
    volumes:
      - db_home:/var/lib/postgresql/data

  superset:
    env_file: docker/.env-non-dev
    image: *superset-image
    container_name: superset_app
    restart: unless-stopped
    ports:
      - 8088:8088
    depends_on: *superset-depends-on
    volumes: *superset-volumes

  superset-init:
    image: *superset-image
    container_name: superset_init
    command: ["/app/docker/docker-init.sh"]
    env_file: docker/.env-non-dev
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes

  superset-worker:
    image: *superset-image
    container_name: superset_worker
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    env_file: docker/.env-non-dev
    restart: unless-stopped
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes

  superset-worker-beat:
    image: *superset-image
    container_name: superset_worker_beat
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    env_file: docker/.env-non-dev
    restart: unless-stopped
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes

  db8:
    container_name: db8
    image: mysql:8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      --general_log=1 --general_log_file=/var/lib/mysql/mysql.log
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: superset
      MYSQL_USER: superset
      MYSQL_PASSWORD: superset

volumes:
  superset_home:
    external: false
  db_home:
    external: false
  redis:
    external: false

**Comment by eschutho** [comment]
@yousoph

**Comment by betodealmeida** [comment]
We had a similar problem authenticating against MySQL 8 because of a new plugin. I solved by using the `mysql-connector-python` module, and changing the URI to `mysql+mysqlconnector://...`.
