### ISSUE TITLE
filter box with an option to 'group by' the data

### ISSUE THREAD

**Issue by hyouinKyouma** [apache/superset#13369]
Hi all,
Filterbox is a great feature to filter data but there are features that can make it better.
Here is my used case:
So lets say that I have a 100 products of different colors, red = 40, blue=20, green=20, , yellow= 20.

I am using 'Table' visualization in dashboard with metric = count

Now when no filter is applied it will show me all the 500 products in the table, and I can select any color from the drop down, lets say that I selected yellow so it will show me the count of 100 for yellow.

But here is the problem I can't have a group by option in the filter box to count of products in the 'Table' for different colors. so I can never see count for all the products for different colors. One option here is to have group by filter applied on the 'table'. but it soon starts to get complicated when working with more than single group by options.

Wouldn't it be nice to have a checkbox beside the filter box drop down to specify the group by category for the data?

Here I have added the pics for giving the rough idea of my proposition,

![githubq3](https://user-images.githubusercontent.com/37413995/111031113-eaa3de00-842b-11eb-8b45-09892d51ac29.png)

In current implementation following steps had to be followed:
1.. add the color category to group by.
2.. select all the colors in the dashboard in the filterbox

![githubQ6](https://user-images.githubusercontent.com/37413995/111031117-ed9ece80-842b-11eb-8764-c12e85d1df08.png)

desired implementation:
1.. have a checkbox to dyanamically group by based on the category.
2.. default state should be all.

**Comment by yashsaxena** [comment]
Hey @amitmiran137 looking forward to see this feature in superset !!! :)

**Comment by amitmiran137** [comment]
resolves https://github.com/apache/superset/pull/14217
