### ISSUE TITLE
[SQL Lab] Copy partition to clipboard doesn't work in left SQL Lab panel

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#13386]
The action "Copy partition to clipboard" on the left side of SQL Lab doesn't work.

### Expected results

record is in clipboard

### Actual results

nothing (old value remains, even though bottom of the page says "copied to clipboard!"

#### Screenshots

![Screen Shot 2021-03-01 at 8 51 50 AM](https://user-images.githubusercontent.com/61221714/109530453-95e78700-7a6b-11eb-9719-0629ceda5c58.png)
![image (7)](https://user-images.githubusercontent.com/61221714/109530460-9aac3b00-7a6b-11eb-8c62-c66548a950c3.png)

#### How to reproduce the bug

1. Go to 'SQL Lab'
2. In left panel select schema and table
3. Click down arrow to see details of the table
4. Click on "copy" next to latest partition info
5. See error

### Environment

(please complete the following information):

- superset version: `master`
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zuzana-vej** [comment]
cc @yousoph

**Comment by etr2460** [comment]
Any updates here yet?

**Comment by michael-s-molina** [comment]
@junlincc Can you assign this to me?

**Comment by michael-s-molina** [comment]
@etr2460 Is someone from Airbnb already working on this? I just found out that I'll need to install all the backend infrastructure (Presto or Hive) to simulate the partitions. If you already have this environment working it will be fairly easy to fix the bug.

In `TableElement.jsx`:

```
renderWell() {
    const { table } = this.props;
    let header;
    if (table.partitions) {
      let partitionQuery;
      let partitionClipBoard;
      if (table.partitions.partitionQuery) {
        ({ partitionQuery } = table.partitions);
        const tt = t('Copy partition query to clipboard');
        partitionClipBoard = (
          <CopyToClipboard
            text={partitionQuery}
            shouldShowText={false}
            tooltipText={tt}
            copyNode={<i className="fa fa-clipboard" />}
          />
        );
      }
...
```
I simulated on the client side a `table` with `partitions` and `partitionQuery` and the copy and paste is working.

**Comment by graceguo-supercat** [comment]
@michael-s-molina no one in airbnb was working on this. Thanks!

**Comment by zuzana-vej** [comment]
Github issue triaging:: bug still there (latest screenshot)

**Comment by rusackas** [comment]
Assigning to @michael-s-molina since you were interested way back when. This probably needs re-validation by now.

**Comment by michael-s-molina** [comment]
Assigning this to @betodealmeida who may have the necessary infrastructure already installed.

**Comment by rusackas** [comment]
CC @bkyryliuk and @nytai who also have some Presto/Hive chops, if I'm not mistaken.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
