### ISSUE TITLE
superset  Version1.01 How to integrate Echarts

### ISSUE THREAD

**Issue by winterliebe** [apache/superset#13383]
superset  Version1.01 How to integrate Echarts

**Comment by junlincc** [comment]
@winterliebe 

if you are asking how to contribute ... we are on ECharts 5.0.2 already, and please check out ECharts plugin directory
- https://github.com/apache-superset/superset-ui/tree/master/plugins/plugin-chart-echarts 

Sample PR 
- https://github.com/apache-superset/superset-ui/pull/918
