### ISSUE TITLE
DOCS: git checkout latest doesn't include docker-compose-non-dev.yml

### ISSUE THREAD

**Issue by shapiroj18** [apache/superset#13390]
I was installing superset for the first time and followed the instructions to `git checkout latest`. However, doing this gave me a checkout to `c9a755f25`. However, this checkout did not include `docker-compose-non-dev.yml`, so I had to re-checkout to master in order to start the services.

### Expected results
`docker-compose-non-dev.yml` on all lasest checkouts, or docs changed to just use the master branch.

### Actual results
```ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker-compose-non-dev.yml'```

### Environment

Mac OS Terminal

### Screenshot
<img width="959" alt="Screen Shot 2021-03-01 at 3 24 40 PM" src="https://user-images.githubusercontent.com/55108156/109554660-7f105700-7aa2-11eb-9556-68666bb48e16.png">

**Comment by nytai** [comment]
This is because the docs were published before there was a new release. The upcoming release should include this change, for now you can either use master or use the dev docker-compose workflow.

**Comment by srinify** [comment]
Closing, as this is now fixed!
