### ISSUE TITLE
Hiding Slicer Header Title

### ISSUE THREAD

**Issue by JosephTheuri** [apache/superset#13397]
## Screenshot

![image](https://user-images.githubusercontent.com/32618888/109565965-40a38800-7af4-11eb-8aca-e1eae2497c62.png)

## Description

I am not able to hide the chart-title on the slicer using CSS. I would like to do this since the chart-label is there and it would be repetitive to have both

**Comment by junlincc** [comment]
We are not likely to further invest in FilterBox as Dashboard native filter is available(behind a feature flag), and this is not an issue in native filter :) @JosephTheuri

**Comment by JosephTheuri** [comment]
Thanks for this, very helpful

**Comment by JosephTheuri** [comment]
Perhaps then we should have the native filter available by default....
