### ISSUE TITLE
big number with trendline

### ISSUE THREAD

**Issue by Riskatri** [apache/superset#13405]
why chart big number with trendline in apache superset minus one year from actual data and always get timestamp at 31 december 17:00:00 when i choose time grain 'year' ?? can the timestamp match with actual data from database? 

for example:
in my case, i have a period like this: 
![image](https://user-images.githubusercontent.com/59104917/109597153-40ce7280-7b4a-11eb-94cf-8a9bf3f813d3.png)

but in chart big number with trendline, the value of timestamp like this:
![image](https://user-images.githubusercontent.com/59104917/109597306-8c811c00-7b4a-11eb-951d-cea051c24fe2.png)

My expectation was that big num with trendline would show  same year from database

**Comment by junlincc** [comment]
@riahk 
checked the sample dataset and chart, things look right from my end. could you please provide more details and confirm year 2014 is not in your dataset?

https://user-images.githubusercontent.com/67837651/109604590-a124cc00-7ad8-11eb-9bb9-07c529af6db6.mov

**Comment by Riskatri** [comment]
yes, 2014 is not my dataset, only 2015 in my dataset.

**Comment by junlincc** [comment]
which db are you connecting to?

**Comment by Riskatri** [comment]
i am connecting to postgresql. can you selected the time grain to year at your example? because if time grain is a day or month is look right.

**Comment by zuzana-vej** [comment]
If you are still facing this bug, please reopen with details - thank you
