### ISSUE TITLE
[Explore]Chart Gridlines

### ISSUE THREAD

**Issue by JosephTheuri** [apache/superset#13400]
## Screenshot

[drag & drop image(s) here!]
![image](https://user-images.githubusercontent.com/32618888/109572955-2ae79000-7aff-11eb-91f7-7ed99d9dcd5e.png)

## Description

Gridlines can sometimes make charts look less presentable and as such it would be great to have more control over them.

## Design input
 `design:suggest`: 
 - Include gridline (on/off) toggle for both y-axis and x-axis under the customize tab

**Comment by junlincc** [comment]
Agreed. We should allow users to hide at least the vertical gridlines.

**Comment by lstroud** [comment]
+1

**Comment by jogendra-jsc** [comment]
+ Much needed.

**Comment by DanielLyi** [comment]
+1

**Comment by Khawn** [comment]
Any solutions so far?looking for method get rid of those girdlines.

**Comment by cafenoirdesign** [comment]
+1

**Comment by WanjohiWanjohi** [comment]
Some CSS styling should get you there :
What worked for me in particular :
`line{
  display:none !important;
}`

**Comment by dustin-liu-bgl** [comment]
why closed

**Comment by hajira-novopay** [comment]
Why is it closed 
Css is not working for grid lines 

Please suggest

**Comment by juanmantelli** [comment]
+1

**Comment by rusackas** [comment]
Well, this is a very old issue, but these days, we'd suggest either opening a PR to add a checkbox that enables gridlines for ECharts plugins, or opening a GItHub discussion of the Ideas type to get opinions and seek volunteers. In general, I think folks would be onboard as long as it's applied to all ECharts plugins in a consistent manner.
