### ISSUE TITLE
[Explore]metrics list in left panel is messed up after dnd

### ISSUE THREAD

**Issue by junlincc** [apache/superset#13429]
See video. it happens when FF = False. 
It's not affecting users on query building yet, but this is a very noticeable issue. 

https://user-images.githubusercontent.com/67837651/109749396-5dd96480-7b8f-11eb-911a-682cef6f498c.mov

cc @zhaoyongjie @kgabryje

**Comment by zhaoyongjie** [comment]
Associate #13449, so close this issue.
