### ISSUE TITLE
[pivot] Order of metrics is incorrect when using 'Combine Metrics'

### ISSUE THREAD

**Issue by kamalkeshavani-aiinside** [apache/superset#13427]
In pivot table the order of metrics in the chart should be same as the order seen in control panel on left. But when using 'Combine Metrics' option, this does not work.

### Expected results

Order of metrics can be changed by user.

### Actual results

Order of metrics can not be changed by user.

#### Screenshots
From examples table birth_names:

Order as expected:
![image](https://user-images.githubusercontent.com/74634977/109743105-81de8980-7c13-11eb-94b1-147585e75636.png)

Order not as expected with 'Combine Metrics':
![image](https://user-images.githubusercontent.com/74634977/109742986-4f349100-7c13-11eb-904b-2c891c531dff.png)

#### How to reproduce the bug

1. Create a pivot table with multiple metrics.
2. Change the order of metrics in control panel by drag-&-drop
3. Enable 'Combine Metrics' option from 'Pivot Options'.
4. Change the order of metrics

### Environment

(please complete the following information):

- superset version: `v1.0.1`
- python version: `3.7`
- node.js version: `v14.15.5`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
Thanks for reporting! @kamalkeshavani-aiinside confirmed this issue is also on master 

<img width="928" alt="Screen Shot 2021-03-02 at 7 47 36 PM" src="https://user-images.githubusercontent.com/67837651/109749850-45b61500-7b90-11eb-8d73-6c83cc384cee.png">

**Comment by geido** [comment]
I'll have a look

**Comment by geido** [comment]
The ordering seems to happen on viz.py but it is not applied when `combine_metric` is set.

**Comment by suddjian** [comment]
I can take a look and try to fix this, hopefully today but it may need to wait longer

**Comment by zhaoyongjie** [comment]
> I can take a look and try to fix this, hopefully today but it may need to wait longer

It's a small task, so I do a quick fix. could you review this PR, Thanks.

**Comment by kamalkeshavani-aiinside** [comment]
Thank you for the fix!
