### ISSUE TITLE
[Dashboard]native filter to support freeForm values 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#13428]
Posting on behalf of users 

Feedback 1: AFAIK Superset prefetchs all the distinct values of filters by running a separate query for each filter. 
I'm looking for a way to implement an instant filter (filter as you type).Is there a way to achieve that? My dataset contains at least 2 millions of records so, I think prefeching all different values for each filter is not the best way for UX AND performance. My first guess is to use the data API but i'm not sure if this is the correct path to follow. Any suggestion? 

Feedback 2: I've been using the new Dashboard native filters. I like them very much. One feature that is no longer available is entering freeForm values like it was possible with FilterBox. Is there plans to support free from values in native filters. Perhaps a configuration option? In our use cases it's not possible to provide a list of all possible values in the UI. So having the ability to enter arbitrary values is crucial.

Proposed solution
- configuration to 'uncheck' autocomplete filter, similar to the setting in Explore. 
- Allow user to type instant filter value

**Comment by villebro** [comment]
Implemented in #14314
