### ISSUE TITLE
docker-compose-non-dev.yml

### ISSUE THREAD

**Issue by tronicum** [apache/superset#13432]
https://superset.apache.org/docs/installation/installing-superset-using-docker-compose

### Expected results

actually read the manual this time before installing. copy and pasted it

### Actual results

docker-compose-non-dev.yml missing

#### Screenshots

not needed

#### How to reproduce the bug

1. Go to https://superset.apache.org/docs/installation/installing-superset-using-docker-compose
try to spinup the docker image
3. miss the non-dev yml.

### Environment

- superset version: git

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

can i create an PR for the doc file?

**Comment by tronicum** [comment]
find -name 'docker*.yml'
./scripts/databases/hive/docker-compose.yml
./.github/workflows/docker-release.yml
./.github/workflows/docker.yml
./docker-compose.yml

**Comment by rvabhijith** [comment]
docker-compose-non-dev.yml added to the master branch only 14 days ago and is not available in the latest tag.

Try to use _docker-compose -f docker-compose-non-dev.yml up_ on the master tag
