### ISSUE TITLE
'Recents' section shows a deleted dashboard on the welcome screen 

### ISSUE THREAD

**Issue by KrupaVadher** [apache/superset#13447]
After deleting a dashboard from Superset welcome screen's Dashboard section, 'Recents' section still shows that dashboard which leads to an on-click error page.

NOTE: 'Recents' section shows the deleted dashboard until the screen is refreshed.

### Expected results

After deleting a dashboard from Welcome screen's Dashboard section, that dashboard details should also be removed from the 'Recents' section.

### Actual results

After deleting a dashboard from Welcome screen's Dashboard section, 'Recents' sections shows the details about that deleted dashboard until the screen is refreshed.

#### Screenshots

<img width="1417" alt="Screen Shot 2021-03-03 at 4 22 38 PM" src="https://user-images.githubusercontent.com/57817186/109894787-f54bbf80-7c42-11eb-8e9e-fae12a73f0b5.png">

On clicking the deleted dashboard from the 'Recents' section leads to the below error-screen.

<img width="834" alt="Screen Shot 2021-03-03 at 4 52 24 PM" src="https://user-images.githubusercontent.com/57817186/109894855-0eed0700-7c43-11eb-9480-b1592bfff18b.png">

#### How to reproduce the bug

1. Go to Superset's Welcome screen
2. Scroll to the 'Dashboard' section
2. Delete an already existing dashboard from the 'Dashboard' section which is also present in 'Recents' section
3. If no dashboard is present, add a new dashboard by clicking on '+ Dashboard' button in 'Dashboard' section and delete it
4. Scroll up to the 'Recents' section
5. Click on the recently deleted dashboard from the 'Recents' section
6. You should see an error page in a new tab
7. Close the error-page
8. Navigate to the previous tab of Superset Welcome screen
9. Refresh the page
10. The deleted dashboard should disappear from the 'Recents' section 

### Environment

(please complete the following information):

- superset version: commit#  `c9a755f25`
- python version: `Python 2.7.16`
- node.js version: `v13.11.0`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
confirmed this is an issue. 

We should do an audit to make sure deleting dashboards and charts from different entry points in the product actually update the Recent cards. low priority, not immediate need, should address it when we have the new design for "more recent cards"

cc @rusackas @pkdotson (Phillip, please keep track of this issue. Thanks!)

**Comment by rusackas** [comment]
This no longer seems to be the case in current Superset
