### ISSUE TITLE
Filter box value does not update annotation layer on line chart [v1.0 and v1.0.1]

### ISSUE THREAD

**Issue by quadh** [apache/superset#13451]
Created a line chart with annotation layers (time series - line charts) and added a filter box (with the appropriate filter mappings), however, changes to the filter box dropdown value are not applied to the chart's annotation layers at all. The filtered column is set to 'Filterable' in the dataset configuration and is present in the chart and annotation layer sub-charts as well.

Issue occurs on Superset v1.0 and v1.0.1.

Are there any configuration options which I missed? Is this a bug?

**Comment by junlincc** [comment]
related to https://github.com/apache/superset/issues/10817 
Thanks for filing the issue. This is not a bug, we have been looking for opportunity to implement the enhancement, but now it make more sense to add it to native-filter. 

cc @villebro @rusackas  (bringing it to your attention, not a priority yet)

**Comment by MTereM** [comment]
Hi , I'm having the same issue in Superset v2.0.0.1 any solution in sight?

**Comment by rusackas** [comment]
Since we're now on 3.1, on the verge of 4.0, we're not supporting 2.x  or prior versions actively. If anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)
