### ISSUE TITLE
PostgreSQL connection string fails if  the uri contains '%'.

### ISSUE THREAD

**Issue by skini-galaxia** [apache/superset#13456]
When the password required to connect to a PostgreSQL database engine contains '%', the code throws an error.

### Expected results
Handle the encoding of '%' in the password string. Encoding done with libraries like urllib does not seem to fix this.

### Actual results
ValueError: invalid interpolation syntax in 'postgresql://superset_admin:Secret~!%@#^&*-_;:.superset@<HOST_NAME>:5432/superset_db' **at position 36**.

**Comment by junlincc** [comment]
Thanks for reporting. i dont think this is a priority, but i am curious to understand if this is intentional or a bug? @dpgaspar @craig-rueda 🙏

**Comment by junlincc** [comment]
tracking this issue in #10483
