### ISSUE TITLE
Add multiple results view into the SQL Lab. 

### ISSUE THREAD

**Issue by clear-m** [apache/superset#13453]
**Is your feature request related to a problem? Please describe.**
In the SQL Lab (in the Superset 1.0.1), we have the ability to see the results of only the last statement that produces result.

**Describe the solution you'd like**
Maybe there should be multiple results views when users decide to fetch data from DB with different SELECT statements?

**Additional context**
![VirtualBox_debian_10_8_04_03_2021_13_12_34](https://user-images.githubusercontent.com/20908177/109948415-5f1fa400-7ceb-11eb-80f6-42eb636ba6a4.png)

**Comment by clear-m** [comment]
> thanks for suggesting. do you mean fetching results from multiple statements in the same editor, and compare the results below?
> cc @yousoph

@junlincc Thanks for the answer! Yes, I mean that in the case of multiple statements (in SQL Lab) that produce result data (e.g. multiple SELECTs), those rows of data can be visualized in separate result tables (under the editor). Now (Superset v1.0.1) there is only one result view that contains rows from the last statement executed.
Well, it seems very natural and convenient to add multiple result tables (in the SQL Lab UI) that the user can interact with (because this is not a common result table (with concatenated rows for each query), but different result tables for each statement with data ...
Thanks a lot in advance, viewing multiple results is a feature I am missing and I hope other users found it helpful too.

**Comment by junlincc** [comment]
This request did come up a multiple times. With semicolons, user can write multiple queries in the editor, which is great.. user can view one of the query results by highlighting the statement, also great. but in order to compare, user have to switch tabs...

ability to compare result tables that has only few rows of data make sense, and I assume that's your case. what about large result tables that barely fit in the view? @clear-m

**Comment by clear-m** [comment]
> what about large result tables that barely fit in the view?

@junlincc Of course, there is some problem with rendering a large dataset that the user has to manipulate: if the user really needs a large dataset to view, then there is already a virtualized view there, but to be able to render even more data (actually an unlimited number of rows) in the table (more than  ~ 5MB of data) we need to dig deeper into virtualization (one of the good examples of how this can be done is here https://www.ag-grid.com/javascript-grid/server-side-model/ ).
And my guess is that in this particular case (large tables of results) a scrollbar (the one that already used in table previews) can be used. Even more scrollbars can be used: one for the results view, limiting the rows in one result view, and one for all result views (for example, like in table previews, see image below).
![VirtualBox_debian_10_8_10_03_2021_12_10_31](https://user-images.githubusercontent.com/20908177/110607959-d26a5f80-819c-11eb-927d-6651f18ed106.png)

**Comment by clear-m** [comment]
> > what about large result tables that barely fit in the view?
> 
> @junlincc Of course, there is some problem with rendering a large dataset that the user has to manipulate: if the user really needs a large dataset to view, then there is already a virtualized view there, but to be able to render even more data (actually an unlimited number of rows) in the table (more than ~ 5MB of data) we need to dig deeper into virtualization (one of the good examples of how this can be done is here https://www.ag-grid.com/javascript-grid/server-side-model/ ).
> And my guess is that in this particular case (large tables of results) a scrollbar (the one that already used in table previews) can be used. Even more scrollbars can be used: one for the results view, limiting the rows in one result view, and one for all result views (for example, like in table previews, see image below).
> ![VirtualBox_debian_10_8_10_03_2021_12_10_31](https://user-images.githubusercontent.com/20908177/110607959-d26a5f80-819c-11eb-927d-6651f18ed106.png)

I will add UI diagrams to clarify the idea this weekend

**Comment by clear-m** [comment]
Sorry this is what I meant, hope this helps.
![wireframe](https://user-images.githubusercontent.com/20908177/112277646-02345f80-8c93-11eb-9034-79826d842414.png)

**Comment by junlincc** [comment]
ah! thanks for mocking the idea. How many tables do you think we should support viewing side by side? i wouldn't recommend more than 2. tbh.

bringing @steejay to the conversation

**Comment by rumbin** [comment]
How about showing the multiple results tables in tabs, allowing to group them side by side by dragging the tabs?
The tables should be labeled on their tabs, e.g. by using the first N characters of their queries.
So if the user puts a comment in front of a single statement, we would display the beginning of this comment, stripping the comment chars (--), or so.

**Comment by rumbin** [comment]
When talking about having multiple statements in a single script, I think we should also consider having distinct keyboard shortcuts for running _all_ statements at once, or running solely the one where the cursor currently is positioned, starting from the previous and spanning to the following semicolon.
I'd opt for Ctrl+Shift+Enter and Ctrl+Enter, respectively.

**Comment by Steejay** [comment]
@clear-m thanks for the suggestion and the mock up your created. I'd love to learn more about this idea! Can you tell me more the last time you wanted to see multiple results views in the same context? What tasks were you trying to accomplish? How would seeing multiple views assuage some of the challenges you were experiencing at this time? How are you currently solving this problem without having multiple views?

**Comment by rusackas** [comment]
This seems to have gone stale, and we've since moved feature requests over to Github's Discussions tab in the Ideas section. I'll close this since it's not a bug, but I encourage you to start a discussion there if you want to continue to pursue this.
