### ISSUE TITLE
select * with the Chart Data API

### ISSUE THREAD

**Issue by suedschwede** [apache/superset#13476]
I want to use the chart data api without defining the column names
In the schema definition columns is not mandatory

```
 columns = fields.List(
        fields.String(),
        description="Columns which to select in the query.",
        allow_none=True,
    )
```
I want to use following query object 
```
{
  "datasource": {
      "id": 3,
      "type": "table"
  },
  "queries": [
      {
          "row_limit": 10,
          "row_offset": 1
      }
  ],
  "result_format": "json",
  "result_type": "results"
}
```

I made a quick fix on my system
superset/common/query_context.py

```
def get_single_payload(
   .....
   if len(query_obj.columns) < 1:
          query_obj.columns = [o.column_name for o in self.datasource.columns]
   ......
```

**Comment by suedschwede** [comment]
![image](https://user-images.githubusercontent.com/25843519/110100215-74a3d500-7da2-11eb-9c38-63e97fe9c9ff.png)
We did you change it to a question ?

**Comment by dpgaspar** [comment]
I see, my mistake.

@villebro can you offer some help here?

**Comment by villebro** [comment]
@suedschwede do I understand you correctly that you want to find a convenient method to do a `select *` without explicitly naming the columns you wish to query?

**Comment by suedschwede** [comment]
Yes that is what I want,

**Comment by villebro** [comment]
While the endpoint is pretty versatile, it's not really designed for `select * from table` type queries. If you're using the chart data endpoint programmatically, you can first fire off a query to get all columns in the table like so:
```json
{
   "datasource": {
      "id": 1,
      "type": "table"
   },
   "queries": [
      {
         "result_type": "columns"
      }
   ]
}
```
This will render the following payload:
```json
{
  "result": [
    {
      "data": [
        {
          "column_name": "source",
          "verbose_name": null,
          "dtype": 1
        },
        {
          "column_name": "target",
          "verbose_name": null,
          "dtype": 1
        },
        {
          "column_name": "value",
          "verbose_name": null,
          "dtype": 0
        }
      ]
    }
  ]
}
```

**Comment by suedschwede** [comment]
We want that users can define their own RESP APIs in superset

In your example I would need 2 rest calls to ge a result ( that is to complicated)

The Rest API should be as simple as possble - I don't understand why it is a problem to return all columns

**Comment by villebro** [comment]
The endpoint is primarily intended for charts to be able to request very specific data from tables. We could potentially introduce new functionality (a new result type for example), but given that this endpoint is already fairly complex, but I'm not sure if this is something that this endpoint should do vs calling one of the endpoints SQL Lab uses.

**Comment by suedschwede** [comment]
At the moment there is no other possibility

The endpoint "explore_json" doesn't support paging
/explore_json/?form_data=%7B"slice_id"%3A201%7D&results=true  

I would prefer a data endpoint to saved queries

**Comment by villebro** [comment]
Can you explain what your use case is in detail? I'd like to help out, but I'm still not entirely sure what the use case is and whether or not this endpoint is the right solution to your problem.

**Comment by suedschwede** [comment]
We want to give our customer the possibility to define their own REST APIs to fetch data

The API call should be as simple as possible
e.g.: https://hostname/superset?id=3&offset=0&limit=10

We can transform the REST Call on our API Gateway  to
```
{
  "datasource": {
      "id": 3,
      "type": "table"
  },
  "queries": [
      {
          "row_limit": 10,
          "row_offset": 1
      }
  ],
  "result_format": "json",
  "result_type": "results"
}
```
 
I don't want to enumerate every coumn in the Rest Call.

**Comment by villebro** [comment]
@suedschwede I think we can solve this by calling the chart data api with the `SAMPLES` datatype. I'll post an example shortly and can add offset support if that's currently not supported.
