### ISSUE TITLE
[Explore][Line Viz] "Sort by" not applied when series limit is not set

### ISSUE THREAD

**Issue by ktmud** [apache/superset#13472]
## Actual Results

In Line chart, there is a "Sort by" field, but it is only applied when series limit is set. I.e. it has not affect on the generated query if series limit is empty or 0.

<img src="https://user-images.githubusercontent.com/335541/110074610-57d1b800-7d36-11eb-8c3c-bf72a513bf16.png" width="600">

This works somewhat differently than the "Sort by" field that [recently added](https://github.com/apache/superset/pull/13057) to other multi-series charts. E.g. Area chart:

<img src="https://user-images.githubusercontent.com/335541/110073332-10e2c300-7d34-11eb-9bdc-dc13861ba375.png" width="400">

For those, "Sort by" will also apply when series limit is not set. In combination with row limit, the query results may be different:

<img src="https://user-images.githubusercontent.com/335541/110075861-5a351180-7d38-11eb-8dbb-286fb8227fc2.png" width="600">

## Expected Results

Line chart should also respect "Sort by" when series limit is not set.

**Comment by junlincc** [comment]
Thanks for reporting and sorry about the series of new bugs recently. please give us a couple of weeks to get to those. 

cc @rusackas @villebro @maloun96
