### ISSUE TITLE
I want more charts

### ISSUE THREAD

**Issue by winterliebe** [apache/superset#13475]
system environment: win 10 64-bit
way to install: pip install
python version:3.7
superset version:1.01

   I want more charts,like Mixed Line and Bar,Stacked Horizontal Bar...but superset charts haven't.How to add Mixed Line and Bar,Stacked Horizontal Bar?

**Comment by srinify** [comment]
Hi @winterliebe if you're fluent with frontend engineering, you can add custom viz plugins. The community is in the process of migrating to Echarts, which will eventually unlock more charts (https://echarts.apache.org/examples/en/index.html). 

Here's some places to get started for building custom viz plugins:

- https://superset.apache.org/docs/installation/building-custom-viz-plugins
- https://medium.com/nmc-techblog/apache-superset-manage-custom-viz-plugins-in-production-9fde1a708e55

**Comment by junlincc** [comment]
Thank you Srini @srinify for answering the questions 
Stacked Horizontal Bar is something missing from the roadmap. should be a toggle away from vertical Echarts bar chart once we have it.

**Comment by ValentinC-BR** [comment]
Hi all,
If I'm not wrong, horizontal bar chart is something that is missing from the current version of Superset (1.0.1 I mean).

And I think it would add value. Sometimes, an horizontal bar chart is more pleasant to read than a vertical one :)

**Comment by amitmiran137** [comment]
our composed chart supports horizontal bar chart, but it is only designated for non temporal X-Axis columns
https://github.com/nielsen-oss/superset-viz-plugins/tree/master/plugins/plugin-chart-composed

you can try it out from the storybook: https://5fec4c81935a8c002151e85f-qigjnxoxyc.chromatic.com/?path=/story/plugins-composed-chart--bars

**Comment by Bonifacio2** [comment]
Hello @srinify . Is there a place where we can follow the progress of the echarts migration?

**Comment by Bonifacio2** [comment]
For those interested, there's a 2021-2022 roadmap here: https://docs.google.com/spreadsheets/d/1V82lxvWeWJK48o8S0OkeTnlL409DbtZSa9qTzdSHx6I/edit#gid=0
