### ISSUE TITLE
[dashboard]Create color mappings for quick update of dashboard colors

### ISSUE THREAD

**Issue by opus-42** [apache/superset#13486]
**Is your feature request related to a problem? Please describe.**
Configuring dashboard with custom colors is quite painful and requires manually updates. Moreover, these labels usually refers to known context and may repeat over different board for visual consistency.

Current way of creating label_colors is updating the dashboard JSON Metadata :
```JSON
{
    "label_colors": {
        "Girls": "#FF69B4",
        "Boys": "#ADD8E6"
    }
}
```

**Describe the solution you'd like**

A solution would be define general **color mappings** which would basically be a list of key-value items and could be add through UI to the dashboards:
* One menu for creating color mappings
* One bouton in dashboard config to apply the dashboard 

Exemple of a color mappings:
```JSON
{
    "US": "#000000",
    "FR": "#000000",
}
```

In this proposal the dashboard wouldn't be directly linked to the color mappings.
Color mappings would simply updated dashboard metadata once, that is to say future changes in the color mappings won't apply to the dashboard.

**Describe alternatives you've considered**
An alternative that is already used in my company is to use the dashboard REST API and define colors mapping and update via Custom CLI / Python Scripts. This alternative would requires to Open-Source our CLI and Python Superset Client.

There would be a gain to directly integrate this in Superset.

I am ready to develop that feature if there is a boarder community need for it.

**Comment by junlincc** [comment]
@opus-42 Thank you so much for filing the request and offering contribution! This issue has been on our radar and we recently kick off the discussion. @geido is the engineer assigned to this project and can lead the implementation. 

can I schedule a meeting with you both later this week? many thanks!

**Comment by opus-42** [comment]
@junlincc. Yes I would be available for a meeting and eager to discuss it. Let me know for organization details and how I can send contact information (I'd prefer not to publish personal / pro email here).

**Comment by junlincc** [comment]
@opus-42 maybe you can drop-in our weekly office hour to share. 

@srinify @garden-of-delete Do we publish upcoming Superset office hours calendar somewhere?

**Comment by opus-42** [comment]
@junlincc I have just sent you an email on your preset-io for direct contact / followup to setup this meeting

**Comment by lilila** [comment]
Dear @opus-42 , 

Could you please give us some examples on how you manage to do this: 
`An alternative that is already used in my company is to use the dashboard REST API and define colors mapping and update via Custom CLI / Python Scripts. This alternative would requires to Open-Source our CLI and Python Superset Client.
`
It would be very appreciated

**Comment by opus-42** [comment]
Dear @lilila, I have started to develop an open-source API client. You can find it [here](https://pypi.org/project/superset-api-client/), you may find an example use case for color in the description.

The idea is to get and then update the dashboard metadata using the REST API.

NB: it is still under development and may not be fully fonctional.

**Comment by lilila** [comment]
Merci!

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. This area has been improved a LOT since this was opened. If people are still encountering issues in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
