### ISSUE TITLE
Jinja template not working in SQL LAB v1.0.1

### ISSUE THREAD

**Issue by asdi744** [apache/superset#13480]
Jinja template not working in SQL LAB

### Expected results

should return user id/name of currently logged in user

### Actual results

DB engine Error: [Statement 1 out of 3] postgresql error: syntax error at or near "{" LINE 1: SELECT {{ current_user_id() }} ^

#### Screenshots

<img width="858" alt="Screenshot 2021-03-05 at 16 32 36" src="https://user-images.githubusercontent.com/4865462/110110502-bba8bf00-7dd0-11eb-92dd-481af4a57a01.png">

#### How to reproduce the bug

1. Go to 'SQL LAB'
2. Execute the query: 'SELECT {{ current_user_id() }};'
3. Click 'Run Selection'

### Environment

- superset version: `1.0.1`
- python version: `3.7.3`
- Flask version: `1.1.2`
- Werkzeug version: `1.0.1`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Please help.

**Comment by chaymaalyoubi** [comment]
hello, in your superset config.py file you should enable  ENABLE_TEMPLATE_PROCESSING (set it to TRUE) in the DEFAULT_FEATURE_FLAGS.
by default its false in the newest versions of superset.

**Comment by asdi744** [comment]
It worked. Many thanks!
