### ISSUE TITLE
Energy Force chart showing an error on the Misc Charts example dashboard

### ISSUE THREAD

**Issue by yousoph** [apache/superset#13494]
#### How to reproduce the bug

1. Click on Dashboards
2. Click the Misc Charts example dashboard

### Expected results

All charts on the example dashboard load without errors

### Actual results

The Energy Force chart shows an error 

#### Screenshots

![image](https://user-images.githubusercontent.com/10627051/110186308-a8debc00-7dc9-11eb-9097-c4c52af58152.png)

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
thanks for reporting. FYI.
Cause and solution can both found in the comment. We also flag this PR as risk a couple times. 
https://github.com/apache/superset/pull/13111

**Comment by yousoph** [comment]
ah, thanks
