### ISSUE TITLE
[chart]"Unexpected error" in Dashboard thumbnails (Superset 1.0.1)

### ISSUE THREAD

**Issue by mrshu** [apache/superset#13490]
Although the thumbnails have (seemingly) been set up properly (as outlined in https://github.com/apache/superset/issues/12867#issuecomment-771770878), the thumbnail image still shows an error, saying "Unexpected error".

This is difficult to debug, as the logs do not show anythings suspicious. I have also tried to increase the values of `SCREENSHOT_LOCATE_WAIT` and `SCREENSHOT_LOAD_WAIT` to `120` and `600`, respectively, but it did not seem to help.

### Expected results

The screenshot/thumbnail of a dashboard. Something like the following:

![Screenshot from 2021-03-05 12-58-16](https://user-images.githubusercontent.com/461491/110174490-7ac89e80-7e00-11eb-870e-1c27fbc3124d.png)

### Actual results (+ screenshot)

The screenshot/thumbnail contains just the error pill:

![8964f231-5cef-44a5-a2ac-96f3bcd91f01](https://user-images.githubusercontent.com/461491/110171548-2b806f00-7dfc-11eb-8cfb-1b9b22db6a0c.png)

### Environment

- superset version: 1.0.1
- python version: 3.8

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
#12867 (comment) seems unrelated to this issue, they were for the home screen configuration. can you expand the "unexpected error" and provide more details? is it only happening on pie chart?

**Comment by mrshu** [comment]
Thanks @junlincc!

Would you mind providing a bit more details as to how to do that? As this is being opened in the headless Chrome, I am not certain how to go about reproducing it.

Thanks!

**Comment by junlincc** [comment]
I am not sure how to help you reproduce.......but i can confirm that Pie chart is working properly. 
whats your db connection?
click see more in the top right conner?

**Comment by mrshu** [comment]
Thanks for your reply @junlincc.

As I mentioned in the previous message, I am not certain how to reach the top-right corner in the headless Chrome where this scrrenshot is from -- when I open the actual URL which is being scrrenshoted (essentially `/superset/dashboard/4/?standalone=true`) the chart works without issues. This particular chart uses the Athena connection.

However, when trying the very same URL in a private window (without Superset's session cookies), I was able to reproduce the issue (i.e. I got the same "Unexpected error" as in the screenshot above). As such, it seems this is a permissions issue in the end. Sorry for not starting with that -- it would be great if the error message could be a bit more descriptive in this regard.

That said, I am still not sure how to resolve this issue and would very much appreciate any further pointers. The `THUMBNAIL_SELENIUM_USER` variable is set to the `admin` user in our config and hence I was under the impression permissions should not be an issue. The `admin` use is also the owner of this dashboard -- I am not exactly sure what further permissions could they need.

I would be very grateful if you could provide some more pointers.

Thanks!

**Comment by ankargren** [comment]
I have the same issue, but with another type of plot. I'm posting here as my guess is that they are related to the same problem, but if you'd prefer that I open up a new issue just let me know!

To reproduce the problem:

- Create a chart using the wb_health_population example data
- Create a time-series chart as follows and save to a new dashboard:
![bild](https://user-images.githubusercontent.com/14996051/113988202-81a75e80-984f-11eb-8abc-9d8e6e82120b.png)
- Create a line chart with the exact same specifications and save to the same dashboard
- Expected output (logged in, as admin in my case) is:
![bild](https://user-images.githubusercontent.com/14996051/113988403-bb786500-984f-11eb-9f70-6a9276d4efdc.png)
- Now opening up a fresh browser and visiting the dashboard without logging in, I get:
![bild](https://user-images.githubusercontent.com/14996051/113988642-f4183e80-984f-11eb-839f-6d8d721ce29e.png)

My expectation here would be that both should be visible. Toggling "See more" gives no additional information as the box is empty. The public role I use is configured as follows:
![bild](https://user-images.githubusercontent.com/14996051/113988895-3477bc80-9850-11eb-89ef-43e26f6e90a0.png)

**Comment by junlincc** [comment]
@villebro @zhaoyongjie looks like echarts and nvd3 have different permissions?

**Comment by villebro** [comment]
Reproduced - investigating

**Comment by mrshu** [comment]
Thanks @villebro, even on the Admin user though? That's rather surprising to be honest.

**Comment by ankargren** [comment]
@villebro This solved the issue and example I posted, so thanks a lot!

**Comment by mrshu** [comment]
@villebro Upon further reflection it does seem that the the Admin role, which the `admin` user has assigned. I am therefore not sure where I'd add this permission -- I'd be very grateful for any pointers.

Thanks!

![Screenshot from 2021-04-09 13-39-21](https://user-images.githubusercontent.com/461491/114174531-07530900-9939-11eb-947d-f23769b195ee.png)

**Comment by villebro** [comment]
You need to add it to the Public role.

**Comment by mrshu** [comment]
Thanks @villebro -- will try that out.

I just don't seem to be able to wrap my head around `THUMBNAIL_SELENIUM_USER` and what is it good for then, if the `Public` role needs the "read on Chart" permission.

**Comment by villebro** [comment]
@dpgaspar you have more familiarity with this - can you help out?

**Comment by riazarbi** [comment]
@mrshu did the suggested fix work? I'm encountering the same error after upgrading my helm chart. I've added `can read on Chart` to both public and admin to no avail.

**Comment by riazarbi** [comment]
I think there are two distinct problems in this thread. 

@ankargren has a problem with the permissions of the public user in the superset UI. 

@mrshu has a problem with the permissions of the selenium user, which is resulting in errors in the PNG images that are snapshotted.

I think that the fix suggested by @villebro fixes @ankargren 's problem, but not @mrshu 's

**Comment by riazarbi** [comment]
I have managed to resolve the issue referenced by @mrshu (i.e specifically for screenshotting operations) by incorporating the code from this comment -

https://github.com/apache/superset/issues/14330#issuecomment-885656343

**Comment by ravneet05** [comment]
I am also seeing a similar issue after creating a superset 1.3.1 setup using helm. 
![image](https://user-images.githubusercontent.com/9279979/134893443-04c2a56c-79e2-4762-a63d-b36bc44b98c9.png)
This issue is happening after the welcome screen shows up and i try to list the dashboards/charts. Upon a few refreshes, it works fine.
Please suggest a fix.

**Comment by etadelta222** [comment]
I'm getting same error. It's not consistent for all users accessing the dashboard though. A force refresh seems to fix it but there's no actual explanation for the 'unexpected error' or in the log itself. 

version:1.1.0

**Comment by nguyenluongky** [comment]
I also facing the same issue with @ravneet05 currently I have to refresh it a few time, don't know what root cause to solve it.
Hope anyone can suggest how to fix that soon. 
I'm using superset version 1.2.0.

**Comment by Hu-WF** [comment]
I got Unexpwcted error like that:
![image](https://user-images.githubusercontent.com/30825060/175292511-82c9c24a-44e9-48ef-92f3-0412e8e01ad3.png)

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long (perhaps no longer an issue?). If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.  We could also re-open this one, but I'm guessing starting from scratch might be easier at this point.
