### ISSUE TITLE
Menu items have mouseover/highlighting display error

### ISSUE THREAD

**Issue by rusackas** [apache/superset#13492]
## Screenshot

![image](https://user-images.githubusercontent.com/812905/110177168-62816100-7db9-11eb-800c-58093ecc1d40.png)
![image](https://user-images.githubusercontent.com/812905/110177182-68774200-7db9-11eb-9d93-74013f7f5da3.png)
![image](https://user-images.githubusercontent.com/812905/110177196-6e6d2300-7db9-11eb-9135-0564c331c2de.png)

## Description

Menu items in superset show a faint blue bar that's very tight to the text. The intent was to have the full item "bar" be that color, from left to right, with a little padding above/below.

## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

**Comment by mohansaimandalapu** [comment]
Hi rusackas

I am interested in solving this issue, this is my first OSP, can you please explain how to solve this issue. Thank you

**Comment by rusackas** [comment]
Effectively resolved by #14184
