### ISSUE TITLE
Error on importing a dashboard from JSON File over https.

### ISSUE THREAD

**Issue by skini-galaxia** [apache/superset#13511]
I am seeing an error in the Chrome console on importing a dashboard on Superset (image attached).
### Expected results
Dashboard import should work properly over https by default.
what you expected to happen.

#### Screenshots
![IMG-20210308-WA0050](https://user-images.githubusercontent.com/76421853/110290543-e5502900-8010-11eb-95cd-a682362426c7.jpg)

**Comment by yousoph** [comment]
Hi @skini-galaxia, have you tried this with VERSIONED_EXPORT = True ? That's the updated import and export, please update here if you're still seeing the issue there. Thanks!

**Comment by rusackas** [comment]
Closing since it's stale and VERSIONED_EXPORT is the way to go from here on out!
