### ISSUE TITLE
[documentation]: updating db migration in contribution file

### ISSUE THREAD

**Issue by mayurnewase** [apache/superset#13522]
Currently, contribution.md suggests merging db migration heads in case of conflicts, which creates 2 migration files for single feature/pr which works perfectly, but may not be ideal to merge in master.

### Expected results
The contribution file should have notes about how to fix migration for pr by using positioning current migration on the top by changing parent revision to latest head or making new migration after merging.

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@mayurnewase feel free to add notes. 🙏

cc @ktmud

**Comment by ktmud** [comment]
Like this: https://github.com/apache/superset/pull/13498 ?

**Comment by mayurnewase** [comment]
Yeah exactly.
Sorry didn't see that pr.

**Comment by ktmud** [comment]
No need to feel sorry and thanks for raising this issue! Great minds think alike 😉
