### ISSUE TITLE
Not able to download large CSV file

### ISSUE THREAD

**Issue by SyamprasadNakka** [apache/superset#13528]
We are trying to download 300 MB to 500 MB size file from SQL_LAB and Chart and the database connection is Oracle, but we are getting page crash error. 
We are able to download max of 90 MB CSV file only.

### Expected results

It should be able to download huge files of sizes > 500 MB also.

### Actual results

We are able to download max of 90 MB CSV file only.

### Environment

(please complete the following information):

- superset version: `0.36`
- python version: `3.7`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@SyamprasadNakka thanks for reporting. what error are you getting and can you attach a screenshot? 
I don't think there's a size limit in download.

**Comment by SyamprasadNakka** [comment]
> 
> 
> @SyamprasadNakka thanks for reporting. what error are you getting and can you attach a screenshot?
> I don't think there's a size limit in download.

![image](https://user-images.githubusercontent.com/35252020/110588399-fb89f080-819a-11eb-9360-68fa990b814e.png)
Hello  junlincc, 
It says "the site can't be reached", after refresh able to see the page. Please find attached the snapshot for reference.

Regards,
Syam

**Comment by rusackas** [comment]
I haven't heard of this as a problem lately, and we no longer support 0.x versions. If you're still seeing this in 2.x.x versions, let's re-open this ticket or a new one with updated context. Thanks!
