### ISSUE TITLE
Unable to pass boolean values to connect_args of database connections

### ISSUE THREAD

**Issue by cccs-jc** [apache/superset#13531]
Unable to pass boolean values to database connections. When configuring mysql+mysqlconnector I'm able to do the following in the python interpreter

```
import sqlalchemy as db
engine = db.create_engine('mysql+mysqlconnector://<user>:<pass>@<host>', connect_args={
'auth_plugin':'mysql_clear_password', 
'ssl_verify_cert':  False , 
'ssl_ca': '/etc/ssl/certs/Entrust_Root_Certification_Authority.pem'})
con = engine.connect()
```
Note I'm passing a certificate just to appease the mysqlconnector, strangely even if ssl_verify_cert is turned of it wants a cert.

However when I try to do the same thing via the database connect of superset it refuses the boolean value
  
```
{
    "metadata_params": {},
    "engine_params": {
          "connect_args": {
		    "auth_plugin":"mysql_clear_password", 
		    "ssl_verify_cert": False, 
		    "ssl_ca": "/etc/ssl/certs/Entrust_Root_Certification_Authority.pem"
		  }
     }
}
```

If I change the value to be a string either "False" or "false" then the connector rejects the configuration saying ssl_verify_cert should be a boolean.

### Expected results

Able to pass boolean configurations to underlying connection library. I looks like there needs to be interpretation of the values to try and convert them to boolean flags. This is actually done explicitly for the allows_virtual_table_explore value.

**Comment by rusackas** [comment]
Closing as stale, but if this is still an issue you ever run into, try passing `false` rather than `False` or `"False"` or `"false"`. Happy to reopen this for further discussion if warranted.
