### ISSUE TITLE
[Dashboard]Show relevant datasets ONLY in native filter dataset select

### ISSUE THREAD

**Issue by junlincc** [apache/superset#13536]
Dashboard native filter enhancement 

Must have -In Datasource field, user should only see the list of datasets that are relevant (being used on the charts in dashboard) in select dropdown.

Should have - add sort to value list to reach feature parity 
Nice to have - If all charts use the same dataset, preselect the one for user. 

To do: 
1. change label "Datasource" to "Dataset"
2. set Allow multiple selections by default 

https://user-images.githubusercontent.com/67837651/110543448-2f9fdb80-80df-11eb-9f0d-8d7028cd4134.mov

**Comment by junlincc** [comment]
@simcha90 Hey Simcha, we would really appreciate if you can help adding a couple of above features. 
Priority : Sort, default for multi select, narrow down relevant option list. 🙏

cc @amitmiran137 @villebro

**Comment by villebro** [comment]
Closing as this was tackled by #14374
