### ISSUE TITLE
Helm chart not adhering to additionalRequirements for drivers

### ISSUE THREAD

**Issue by deworkman** [apache/superset#13539]
Hi, I need a superset cluster that can hit pinotdb, but why does adding pinotdb to helm chart’s values file additionalRequirements not install the driver and how do I do so please? Thanks!

### Helm chart does not appear to adhere to additionalRequirements section.

Tried with user-supplied values file.
```
helm upgrade --install --namespace superset --values values-dev.yaml superset . --debug
USER-SUPPLIED VALUES:
additionalRequirements:
- psycopg2==2.8.5
- redis==3.2.1
- sqlalchemy-trino
- pinotdb==0.3.3
- pyhive==0.6.3
- ibm_db_sa
```

Tried without user-supplied values file.
```
helm upgrade --install --namespace superset superset . --debug
COMPUTED VALUES:
additionalRequirements:
- psycopg2==2.8.5
- redis==3.2.1
- sqlalchemy-trino
- pinotdb==0.3.3
- pyhive==0.6.3
- ibm_db_sa
```
### Expected results

Expected `pinotdb` and `ibm_db_sa` to be pip installed

### Actual results

No pip install

```
[root@10-222-77-102 xxxxx]# kubectl get pods -n superset
NAME                              READY   STATUS      RESTARTS   AGE
superset-7bb7c98bbc-7pjpk         1/1     Running     0          99s
superset-7bb7c98bbc-982fc         1/1     Running     0          99s
superset-init-db-2pjxs            0/1     Completed   0          98s
superset-postgresql-0             1/1     Running     0          98s
superset-redis-master-0           1/1     Running     0          98s
superset-worker-6b5947658-247p4   1/1     Running     0          99s
superset-worker-6b5947658-lfdfs   1/1     Running     0          99s
[root@10-222-77-102 xxxxx]# kubectl exec -it pod/superset-7bb7c98bbc-7pjpk -n superset -- pip list | grep pinotdb
[root@10-222-77-102 xxxxx]# kubectl exec -it pod/superset-7bb7c98bbc-7pjpk -n superset -- pip list | grep ibm_db_sa
[root@10-222-77-102 xxxxx]#
```

Also the GUI errors. Attempting to add Database via the GUI like this:
pinot+http://[pinot-broker]:30099/query/sql?server=http://[pinot-controller]:31000/
…yields:
ERROR: Could not load database driver: pinot+http

### Additional context

No logs print when the error occurs.

Original logs look fine
```
$ kubectl logs pod/superset-7bb7c98bbc-2bbch -n superset -f
: not found /app/pythonpath/superset_bootstrap.sh:
: not found /app/pythonpath/superset_bootstrap.sh:
ERROR: Invalid requirement: ''
: not found /app/pythonpath/superset_bootstrap.sh:
[2021-03-09 22:59:24 +0000] [12] [INFO] Starting gunicorn 20.0.4
[2021-03-09 22:59:24 +0000] [12] [INFO] Listening at: http://0.0.0.0:8088 (12)
[2021-03-09 22:59:24 +0000] [12] [INFO] Using worker: gthread
[2021-03-09 22:59:24 +0000] [15] [INFO] Booting worker with pid: 15
logging was configured successfully
INFO:superset.utils.logging_configurator:logging was configured successfully
Loaded your LOCAL configuration at [/app/pythonpath/superset_config.py]
```

**Comment by kompetenzlandkarte** [comment]
I am also looking into this feature. Did you find a solution? I am looking for this [section](https://superset.apache.org/docs/installation/running-on-kubernetes#dependencies).

**Comment by samudurand** [comment]
Looking into the values.yaml from superset I can see that there is no section called additionalRequirements, nor in any of the templates. I think what they expect us to use is the bootstrapScript section, or more precisely to replace it by building a new Docker image and building it ourselves. See the comment in that section: 

```
# Install additional packages and do any other bootstrap configuration in this script
# For production clusters it's recommended to build own image with this step done in CI
bootstrapScript: |
```

**Comment by jiajie999** [comment]
The official doc is not updated and the stable version 1.0's helm chart code is also not updated.  If you use branch 1.3, you will find the helm chart's 'values.yaml' has removed 'additionalRequirements' and replace it with 'bootstrapScript'.

**Comment by stringang** [comment]
you can extend the official image.

```
FROM apache/superset
# Switching to root to install the required packages
USER root
# Example: installing the MySQL driver to connect to the metadata database
# if you prefer Postgres, you may want to use `psycopg2-binary` instead
RUN pip install mysqlclient
# Example: installing a driver to connect to Redshift
# Find which driver you need based on the analytics database
# you want to connect to here:
# https://superset.apache.org/installation.html#database-dependencies
RUN pip install sqlalchemy-redshift
# Switching back to using the `superset` user
USER superset
```

[reference](https://hub.docker.com/r/apache/superset)

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for over two years, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
