### ISSUE TITLE
Cached results do not check user permissions

### ISSUE THREAD

**Issue by razzius** [apache/superset#13538]
If a user does not have permission to view a chart, but the chart is cached, the cached chart will display for the user.

### Expected results

The chart should error.

### Actual results

The chart displays the cached result. If the user force refreshes the chart data, the chart will error.

#### How to reproduce the bug

1. Enable caching via DATA_CACHE_CONFIG in superset_config.py
2. Log in a user that can see a chart
3. View the chart, which will cache its result data
4. Log out and log in as a user that should not be able to see that chart
5. View the same chart, and observe that it loads (it should not load)
6. (optional) click "cached" button to force refresh, and observe that it errors (as expected)

### Environment

- superset version: Superset 1.0.1
- python version: Python 3.7.3
- node.js version: v10.21.0

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by nytai** [comment]
@razzius We're unable to reproduce, could you provide a little more info here? Are you referring to the chart itself, if so, which view (dashboard, explore), or are you referring to the chart screenshot? Which role do each of the users have?

**Comment by razzius** [comment]
@nytai the chart data, whether viewed from a dashboard or the explore view. I think one thing that was ambiguous in my description is this: the error that I expect to see is a Presto error, since the logged in user does not have access to the underlying data.

Here's the error that we should see:

<img width="809" alt="image" src="https://user-images.githubusercontent.com/2244895/110553874-553cdd00-80ff-11eb-9d98-b61a5c04f6a5.png">

I'm realizing it's a nontrivial issue, since Presto is totally left out of the picture when the result is cached. The requesting user could be incorporated into the cache key, but that wouldn't work with use cases such as Celery requesting data so that it is cached.

**Comment by nytai** [comment]
So the user does not have access via presto permissions to the underlying data, but the user does have superset permission access to that chart object?

**Comment by razzius** [comment]
@nytai that’s right. I suppose we could restrict access to the chart object as one way to deal with this issue.

**Comment by nytai** [comment]
It seems like your just having superset fallback on the db's access control for this use case. Since supperset has its own permission model, I'm not so sure this is a bug with superset and more of an edge case with your current permission set up.
