### ISSUE TITLE
[Time-series Table] Multiple cosmetic issues in Time-series Table

### ISSUE THREAD

**Issue by kamalkeshavani-aiinside** [apache/superset#13543]
## Screenshots

1. Tooltip
![image](https://user-images.githubusercontent.com/74634977/110591424-6697ef00-81bc-11eb-9454-d679a1e2e48d.png)

2. Half cut bottom axis value
![image](https://user-images.githubusercontent.com/74634977/110591705-becef100-81bc-11eb-992f-c64a6b5864e5.png)

3. Missing bottom axis
![image](https://user-images.githubusercontent.com/74634977/110592033-1ec59780-81bd-11eb-8c18-7b9329dcc252.png)

## Description

1. Tooltip can be in a position, where the value is not visible.
2. The bottom half of bottom axis value is hidden.
3. In some cases, the bottom axis and value is missing.

Checked in v1.0.1 and master.

**Comment by junlincc** [comment]
thanks for reporting, confirm 1 & 2. should be an easy fix. can't repro 3....

**Comment by kamalkeshavani-aiinside** [comment]
@junlincc I used 'cleaned_sales_data' table in examples db with below config to reproduce all 3 issues. You can try at your end.
![image](https://user-images.githubusercontent.com/74634977/110731377-89321280-8265-11eb-97dc-b1bd67d40541.png)

**Comment by kamalkeshavani-aiinside** [comment]
Found 2 more related issues:

4. The column header for time-series column type Sparkline gets cluttered with the data. This happens only in dashboard view.
![image](https://user-images.githubusercontent.com/74634977/118073455-d1e18580-b3e6-11eb-84d9-58c15d499e4e.png)

5. In some cases, the Y-axis value is partially hidden due to insufficient margin on the right side.
![image](https://user-images.githubusercontent.com/74634977/118070897-b922a100-b3e1-11eb-8e81-5298f44a5963.png)

Confirmed on v1.1.0 and master.

**Comment by kamalkeshavani-aiinside** [comment]
Issue 1,2,3,4 are still reproducible on version 1.5.0

**Comment by rusackas** [comment]
I'm not sure if these are still issues in current versions of Superset (3.x). If it is, we can re-open this, but it might be better to open new issues for each problem with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
