### ISSUE TITLE
Safari: 'explore-container' div has more height than 'app' div on Dataset Explore page 

### ISSUE THREAD

**Issue by KrupaVadher** [apache/superset#13542]
## Description

Safari Version: 14.0.3 (16610.4.3.1.4)
Superset Commit hash: c9a755f25

As seen in the below video, after changing any chart type or running an invalid query, the height of 'explore-container' div gets larger than 'app' div. Hence, the screen becomes ineffective if we want to run another query since the controls like 'Run' and 'Save' gets hidden.

https://user-images.githubusercontent.com/57817186/110589449-4835e300-812b-11eb-86b5-2225f70b3291.mp4

Tested with Google Chrome and Firefox where it works fine. 

#### Expected Screen:

Google Chrome:

<img width="1434" alt="Preset_io_Dataset_expected" src="https://user-images.githubusercontent.com/57817186/110590155-43256380-812c-11eb-994c-810a02e48c9d.png">
 

## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

**Comment by junlincc** [comment]
Thanks for reporting @KrupaVadher ♥️

**Comment by rusackas** [comment]
Closing since this is stale (2 years old), Safari has gone up a couple of Major versions, and Superset's matured quite a bit, too. If it's still an issue, I'm happy to revisit!
