### ISSUE TITLE
[SQLlab]Parameters Modal Not Appearing

### ISSUE THREAD

**Issue by yousoph** [apache/superset#13540]
#### How to reproduce the bug

Prereq: set ENABLE_TEMPLATE_PROCESSING = True 
1. Go to SQL Lab 
2. Click the overflow menu on the right of the toolbar 
3. Click "Parameters" 

### Expected results
Modal appears to set Parameters 

### Actual results
No modal appears and screen is blank other than the toolbar 

#### Screenshots

![image](https://user-images.githubusercontent.com/10627051/110580202-04d47800-811d-11eb-8f3b-a637bc6984cf.png)

### Environment
- superset version: `master`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@yousoph this should be a quick fix. added P2 based on the severity. thanks
