### ISSUE TITLE
Get Started link to docker-compose instructions is broken

### ISSUE THREAD

**Issue by ohaddahan** [apache/superset#13567]
### Expected results

Going into : https://superset.apache.org/docs/intro and clicking the link `Setup Superset locally with one command using Docker Compose` should send me to a working instructions page.

### Actual results

404 Not Found Error when clicking https://superset.apache.org/docs/docs/installation/installing-superset-using-docker-compose

#### Screenshots

![docker-compose](https://user-images.githubusercontent.com/20769037/110754592-ac05fc00-8250-11eb-8150-a893048aac00.png)

#### How to reproduce the bug

1. Go to 'https://superset.apache.org/docs/intro'
2. Click on 'Setup Superset locally with one command using Docker Compose'

**Comment by srinify** [comment]
Hi @ohaddahan thanks for raising this! Ill get this fixed.

In the meantime, you can use this url; https://superset.apache.org/docs/installation/installing-superset-using-docker-compose

**Comment by junlincc** [comment]
https://github.com/apache/superset/pull/13861 

fixed! thank you both
