### ISSUE TITLE
Support to postgis

### ISSUE THREAD

**Issue by fccoelho** [apache/superset#13573]
Is there a way to generate a Choropleth map base on a PostGIS layer? PGAdmin4 does this out of the box. All Python GIS libraries do as well, but I couldn't find a way to do this with superset. Apparently, All map based visualizations are thought for point data, not for polygons. even `deck.gl Polygon` does not recognize the geometry columns of a Postgis table.

**Comment by junlincc** [comment]
@fccoelho thanks for suggesting! moving/consolidating the discussion to #13552. we will keep you updated.
