### ISSUE TITLE
Wrong color for bar charts

### ISSUE THREAD

**Issue by ValentinC-BR** [apache/superset#13579]
## Screenshot

![Présentation sans titre](https://user-images.githubusercontent.com/79460908/110811066-a75c3a80-8286-11eb-80f4-0d3e8cffcc78.png)

## Description

I've set custom colors in the Dashboard properties.
Those colors seems to be pretty well taken into account but bar charts kind of convert them into "pastel colors" (see screenshot).

By the way, the pie chart colors are not exactly the good ones (#f97f44 instead of #ff7f44 in this example) but the difference is not visible, contrary to bar charts.  

## Environment

superset version: 1.0.1
browser : chrome 89.0

**Comment by mohansaimandalapu** [comment]
Hi ValentinC-BR

I am interested in solving this issue. this is my first OPS can you help in solving this issue. Thank you

**Comment by ValentinC-BR** [comment]
Hi,
Actually, as a data analyst, I'm an end-user of Superset, and I don't think I'll be of any help on this ! 

If you think I can help you with feedback, let me know.

**Comment by amitmiran137** [comment]
This issue got resolved by the latest color consistency PRs
