### ISSUE TITLE
Dashboards not loading in Mozilla Firefox Private Window

### ISSUE THREAD

**Issue by rvabhijith** [apache/superset#13571]
Why the superset dashboards are not loading in mozilla firefox private window
PFA
![Screenshot 2021-03-11 at 2 55 51 PM](https://user-images.githubusercontent.com/39004901/110765773-87267e80-827a-11eb-82a6-fd72d562f08c.png)

**Comment by cleman95** [comment]
Hello, 
I have the same issue with superset version 1.0.1. I can't access any databases or dashboards in private window on Firefox but i can in normal windows and in Chrome (normal and private windows).


I get a log in the browser: "DOMException: The operation is insecure."
in the sql lab i can't access my databases i got "error while fetching database list" "error while fetching schema list"

**Comment by ErinYener** [comment]
We're experiencing the same issue on Superset 1.0

**Comment by srinify** [comment]
Are y'all logged into Superset in these private window sessions? @ErinYener @cleman95 @rvabhijith 

That would be my first instinct / thing to rule out! The errors could definitely be better though, even for the logged out case

**Comment by bereal** [comment]
We have the same issue with 1.2.0. Yes, I'm logged in. The async transport is default, e.g. polling, so it has nothing to do with web sockets.

**Comment by cotsuka** [comment]
A little more detail from the Firefox console:

```
DOMException: The operation is insecure. 4305.79cd83c67e38663e612e.entry.js:362:20470
    C https://domainwashere.com/static/assets/4305.79cd83c67e38663e612e.entry.js:362
```

**Comment by tweinreich** [comment]
Same issue here when opening Superset in a private window.

- **OS:** macOS Big Sur (11.6.2)
- **Superset version:** 1.3.2
- **Firefox version:** 95.0.1

![photo_2021-12-23 18 59 33](https://user-images.githubusercontent.com/4059641/147277068-d092240d-51d2-4a4b-908e-78c3505c1f86.jpeg)

**Comment by d9k** [comment]
May it be connected with https://github.com/apache/superset/issues/7364#issuecomment-508494849 (caches frontend API)?

**Comment by elestranobaron** [comment]
same error right here with firefow on apache2 ssl reverse proxy

**Comment by torryDou** [comment]
Same issue as "DOMException: The operation is insecure.", is there a solution?

**Comment by elestranobaron** [comment]
Hi, any news on this one ?

**Comment by rusackas** [comment]
Hopefully this isn't an issue any more, and this thread has gone silent. I'm closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
