### ISSUE TITLE
[SQL Lab] Double click to select cell bleeds into adjacent cell

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#13589]
Description:
When user wants to copy individual cell contents from the results of a query in SQL Lab, they often double click the cell to select the value. Often (not always) it selects that value plus part of the next column too -  bleeding into the adjacent cell and selecting a mix of both. Selecting by clicking and dragging is equally unreliable.

### Expected results
Selection spans more than the selected cell.

### Actual results
Selects content of that column + part of next column. 

Workaround - only option is Export it to csv.

#### Screenshots
video 1:
![issue-002](https://user-images.githubusercontent.com/61221714/110886235-31af9900-829d-11eb-9707-ddd73688f3f3.gif)
video 2:
![issue-001](https://user-images.githubusercontent.com/61221714/110886242-33795c80-829d-11eb-818f-8c6761c31e60.gif)

#### How to reproduce the bug
1. Run a query in SQL Lab.
2. Try to select a cell's contents by double clicking the cell. 
3. In case you can't repro the bug, try to run a larger query (e.g. more columns)

### Environment

(please complete the following information):

- superset version: `master`
- Browser: Chrome

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zuzana-vej** [comment]
FYI @yousoph 
Unsure if this is regression or not (haven't noticed this in the past). Pretty minor bug, but the workaround (csv download) kind of sucks.

**Comment by yousoph** [comment]
Weird! It seems like triple clicking is giving the expected double click behavior right now... will look into it.

**Comment by yousoph** [comment]
Having trouble repro-ing this now, let me know if you're still seeing it!

**Comment by geido** [comment]
I can still reproduce with large results. I am having a look

**Comment by yousoph** [comment]
@geido and I have both been unable to repro this now. Closing out but @zuzana-vej please reopen if you're still able to repro! Thanks!!
