### ISSUE TITLE
Display actual value (in tooltip) for 100% stacked bar charts

### ISSUE THREAD

**Issue by ValentinC-BR** [apache/superset#13580]
### Feature Request 

The 100% stacked bar chart (bar chart > Contribution) only display the percentage in the tooltip when you hover on the bars.

Displaying (by default or not) the actual value of the bar would be a great enhancement.

### Example

Let's say I have : 
* 5 female & 5 male viewers on Monday (50/50) 
* 15 female & 5 male viewers on Tuesday (75/25)

Currently, the 100% staked bar chart only display "50%" and "75%" if I hover on the "female viewers" bars

What I'd like (in the tooltip) : 
* "5 (50%)" 
OR
*  "50% (5)" 
OR
*  "[Name of the metric] : 5, Contribution : 50%"

**Comment by junlincc** [comment]
@ValentinC-BR Thanks for suggesting! it makes sense. we will include it in the new Echarts bar.
