### ISSUE TITLE
Issues in editing dashboard properties

### ISSUE THREAD

**Issue by abhi-quinyx** [apache/superset#13582]
Cannot edit the properties for all the dashboard  which have been migrated from 0.38.0 to 1.0.1 

### Expected results

Edit the dashboard properties for existing dashboards

### Actual results

404 BAD Request.

#### Screenshots

![image](https://user-images.githubusercontent.com/70583041/110827620-8e5b8580-8296-11eb-9a6b-2b2d9834954c.png)

#### How to reproduce the bug

1. Go to any dashboard created before the upgrade
2. Click on "edit dashboard properties" & try to edit the name or click advanced to change other options
3. Click on "Save"
4. Nothing happens on the UI , the background error ( attached as screenshot )

### Environment

(please complete the following information):

- superset version: `1.0.1`
- mysql version: `5.7.12`
- alembic version: `c878781977c6`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

An interesting observation which works as a fix ( not the correct way , since that doesn't explain the issue ) 

Follow until step-2 on "How to reproduce the bug" section  , after that : 

1. Expand the "Advanced" section.
2. Remove the "import_time" & "remote_id" keys 
3. Clicking on save should work .

Example : 

doesn't work : 
```
{
    "timed_refresh_immune_slices": [],
    "expanded_slices": {},
    "refresh_frequency": 0,
    "default_filters": "{}",
    "color_scheme": null,
    "import_time": 1551707490,
    "remote_id": 24,
}

```

works:
```
{
    "timed_refresh_immune_slices": [],
    "expanded_slices": {},
    "refresh_frequency": 0,
    "default_filters": "{}",
    "color_scheme": null
}
```

**Comment by amitmiran137** [comment]
Is resolved in 1.4
