### ISSUE TITLE
Paired t-test Table can't render 

### ISSUE THREAD

**Issue by code-snail** [apache/superset#13594]
### Expected results

It should show table values like p-value、lift.

### Actual results

show empty table.

#### Screenshots
![image](https://user-images.githubusercontent.com/65579137/110917902-6d0d9e80-8355-11eb-8907-637564d4db9c.png)

![image](https://user-images.githubusercontent.com/65579137/110917870-60894600-8355-11eb-86ab-5874555d46de.png)

#### How to reproduce the bug

1. create Paired t-test Table chart
2. select metrics and group fields
3. click run

### Environment

(please complete the following information):

- superset version: 0.17.12
- python version: Python 3.7.9
- node.js version: v14.0
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by suddjian** [comment]
Closing this as I don't believe it's an issue on the latest version of Superset. Feel free to reopen if this is incorrect.

**Comment by D3nn3** [comment]
We currently use v1.3.0 and the problem still seems to be present. Doesn't matter which settings, metrics or group by we choose, no data is actually rendered. Also the chart type isn't in the deprecated category.

Is it supposed to work? Does anyone have more information on that? Couldn't really find any current information on that.

**Comment by fazilhero** [comment]
Im using latest version v2.1.0 and this issue persists. I see empty graph
