### ISSUE TITLE
[🎉New feature for testing]Dashboard native filter phase 2(Full feature parity & Enhancement) 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#13591]
We have been iterating on Dashboard native filer behind the feature flag after announcing phase 1 testing https://github.com/apache/superset/issues/12148

All bugs that are identified have been fixed, lots of new features have been added since then, based on request and feedback from the community. We are heavily testing this week and will make all features fully available in days. 

Many thanks to all the contributors(phase 2) 🙏
Project lead: @villebro 
@simcha90 @agatapst @zhaoyongjie @amitmiran137 @suddjian

<img width="1892" alt="Screen Shot 2021-03-11 at 9 44 42 PM" src="https://user-images.githubusercontent.com/67837651/110897832-06d03f80-82b3-11eb-8d4b-03e563b5bb73.png">

1. Range filter!! 
User now can set up a range filter by selecting a numeric column. filter detects min and max values as DEFAULT VALUE. Set filter range by sliding.  
<img width="405" alt="Screen Shot 2021-03-11 at 9 18 19 PM" src="https://user-images.githubusercontent.com/67837651/110895963-80fec500-82af-11eb-9583-1a8b1225cdc7.png">

2. Native time column select- Support multiple time columns!! 
<img width="1885" alt="Screen Shot 2021-03-11 at 9 08 03 PM" src="https://user-images.githubusercontent.com/67837651/110896105-c3280680-82af-11eb-8e4b-e72809573463.png">

3. Native time grain filter!!! 
<img width="398" alt="Screen Shot 2021-03-11 at 9 22 19 PM" src="https://user-images.githubusercontent.com/67837651/110896187-ef438780-82af-11eb-81ee-6192203c0a4f.png">

 4. Native new time filter - support LAST, PREVIOUS, CUSTOM, free text and ADVANCED syntax!! 
<img width="777" alt="Screen Shot 2021-03-11 at 9 23 45 PM" src="https://user-images.githubusercontent.com/67837651/110896580-c079e100-82b0-11eb-9265-9f2a8df126f8.png">

5. Sort value and multiple select by default
<img width="963" alt="Screen Shot 2021-03-11 at 9 47 11 PM" src="https://user-images.githubusercontent.com/67837651/110898042-60386e80-82b3-11eb-9000-b08eb9bada67.png">

To test, set "DASHBOARD_NATIVE_FILTERS": True in config.py 

Please comment in the thread if you find any issues. We will address reported issues(bug) ASAP! 
New feature requests will be considered, and implemented for next iteration in the future. 🙏

**Comment by junlincc** [comment]
request: 
Display actual range value on filter for Range filter 
<img width="1178" alt="Screen Shot 2021-03-12 at 9 42 29 AM" src="https://user-images.githubusercontent.com/67837651/110977709-52b4d000-8317-11eb-909b-f786bc6d3e2b.png">

**Comment by junlincc** [comment]
Request:

Instead of showing "no result" in the loading state, can we use the infinity loading logo?

https://user-images.githubusercontent.com/67837651/110978057-c2c35600-8317-11eb-8b96-6691f5a7853d.mov

**Comment by junlincc** [comment]
<img width="1773" alt="Screen Shot 2021-03-12 at 1 46 00 PM" src="https://user-images.githubusercontent.com/67837651/111001855-683af180-8339-11eb-9a91-cfe185193b2d.png">

Request:
Prompt user to change filter name if is duplicate

**Comment by junlincc** [comment]
<img width="1200" alt="Screen Shot 2021-03-12 at 9 49 57 AM" src="https://user-images.githubusercontent.com/67837651/111002072-a59f7f00-8339-11eb-9c30-90ae7e7c39bc.png">

Request: makes field collapsible

**Comment by mihir174** [comment]
UX Issue:

There are 2 'Apply' buttons in the flow of modifying a Time Range native filter - 
1. In the filter bar
2. In the Time Range filter popover
The one in the popover (shown in screenshot) is misleading because it doesn't actually apply the filter, and is clicked first.
<img width="592" alt="Screen Shot 2021-03-12 at 3 04 39 PM" src="https://user-images.githubusercontent.com/64227069/111007783-79d5c680-8344-11eb-8c68-097cc4f91c34.png">

**Comment by mihir174** [comment]
These buttons don't appear to be clickable because the cursor doesn't change to a pointer when hovering over them

<img width="246" alt="Screen Shot 2021-03-12 at 3 09 41 PM" src="https://user-images.githubusercontent.com/64227069/111008015-0b453880-8345-11eb-9820-7efeb4bbc48c.png">

**Comment by mihir174** [comment]
Question: should the available list of datasources here be limited to those referenced by charts on this dashboard?

<img width="977" alt="Screen Shot 2021-03-12 at 3 12 32 PM" src="https://user-images.githubusercontent.com/64227069/111008188-6119e080-8345-11eb-93ee-f4d1c4a6f6d4.png">

**Comment by mihir174** [comment]
After x-ing out of the warning message that appears when you click 'Cancel' with unsaved changes, the main Save and Cancel buttons disappear and the main modal X doesn't work until another edit is made
https://user-images.githubusercontent.com/64227069/111008347-c1a91d80-8345-11eb-9d4a-fff52834f0c2.mov

**Comment by suddjian** [comment]
Suggestion: when the filters sidebar is empty, instead of a pencil icon it should have a plus

<img width="265" alt="Screen Shot 2021-03-12 at 3 21 51 PM" src="https://user-images.githubusercontent.com/1858430/111009071-76900a00-8347-11eb-9118-cc4bb79a3e4b.png">

**Comment by daniel10012** [comment]
@junlincc 
all datasets don't show in filter dropdown
![image](https://user-images.githubusercontent.com/10360991/111009383-7997f400-8361-11eb-8fb1-e05b2d536501.png)

**Comment by suddjian** [comment]
Suggestion: the Parent Filter dropdown should allow you to enter a name that does not exist to create a new filter. (similar to how in Explore you can enter a name and create a dashboard when saving the chart)

**Comment by daniel10012** [comment]
Cascading filter indicator needs to be different than the regular filter indicator
![image](https://user-images.githubusercontent.com/10360991/111009695-5e79b400-8362-11eb-95e2-a3062eae853b.png)

**Comment by suddjian** [comment]
Suggestion: layout change. The organizing factor being data on the left, behavior on the right.

<img width="949" alt="Screen Shot 2021-03-12 at 3 30 45 PM" src="https://user-images.githubusercontent.com/1858430/111009588-e5219780-8348-11eb-8cf4-1d40a757866e.png">

**Comment by daniel10012** [comment]
Parent and child switch randomly 
![image](https://user-images.githubusercontent.com/10360991/111009872-c16b4b00-8362-11eb-9349-b72d6e3956c4.png)

**Comment by suddjian** [comment]
All my filters have "Apply changes instantly" enabled, but the "Apply" button is still enabled (does nothing)

<img width="261" alt="Screen Shot 2021-03-12 at 3 44 46 PM" src="https://user-images.githubusercontent.com/1858430/111009956-e2737200-8349-11eb-891b-c36b42e94854.png">

**Comment by daniel10012** [comment]
Remove parent filter when doing a time range
![image](https://user-images.githubusercontent.com/10360991/111010025-47879180-8363-11eb-8645-a7ff11e379a2.png)

**Comment by suddjian** [comment]
Non-blocking suggestion: There is no indication on hover that these icons are interactive. They should use `cursor: pointer` and should probably have a popover explaining what they do.

<img width="253" alt="Screen Shot 2021-03-12 at 3 48 39 PM" src="https://user-images.githubusercontent.com/1858430/111010178-91b04900-834a-11eb-8ebd-1064493e5cec.png">

**Comment by suddjian** [comment]
Clicking on the label does not activate the radio button

<img width="318" alt="Screen Shot 2021-03-12 at 4 02 19 PM" src="https://user-images.githubusercontent.com/1858430/111010775-56af1500-834c-11eb-810f-90051566d7d2.png">

**Comment by mihir174** [comment]
We can get rid of 'Time Column' as a filter type and instead add a field under the 'Time Range' filter type to select a time column.

Time Column is currently redundant as a filter type, and the system currently chooses a potentially undesirable default time column for Time Range when there is more than 1 time column

**Comment by suddjian** [comment]
The Filter Type input should only offer filter types that are compatible with one of the dashboard's datasets

**Comment by junlincc** [comment]
@graceguo-supercat @zuzana-vej @ktmud 
As promised, dashboard filter has reached feature parity and beyond, tested internally. we identify quite a few non-blocker issues above^^^^. While we address those remaining issues, I wonder if we can start filter migration as discussed last year?

**Comment by PowerPlop** [comment]
@junlincc  will the viz 'filter_box' be deprecated in the future or will it stay? I would say that the filter box viz is preferred for very simple filters.

Is there already an option to save a dashboard with preselected native filters (as with filter box)?

**Comment by junlincc** [comment]
@PowerPlop 

> will the viz 'filter_box' be deprecated in the future or will it stay? I would say that the filter box viz is preferred for very simple filters.

It's still in discussion when we are gonna deprecate it, but yes, very likely we will. what do you mean by _very simple filters_? 

> Is there already an option to save a dashboard with preselected native filters (as with filter box)?
good point. not yet, but we will add it before deprecating the FilterBox.

**Comment by PowerPlop** [comment]
@junlincc  Some elaboration on 'simple filter:

The native filter groups all filters in one generic sidebar which might be useful if you have a lot of filters that apply to all slices. 
If however you have only a small set of filters (or just one), the side bar layout is in my opinion unneccesary and less user friendly. Currently we use for example one filter box with 2 entries at the top of page.
Or we use multiple filter boxes (different tabs) that each filter only a specific set of slices. The position of the filterbox makes it clear to the user which slices will be filtered.
When using the sidebar it is unclear which filter will apply to which slice (only visible after you applied it).
Other BI tools such as Tableau keep the dasbhoard filter as a dashboard component that has to be positioned somewhere on the dashboard instead of external sidebar.

**Comment by villebro** [comment]
> @junlincc Some elaboration on 'simple filter:
> 
> The native filter groups all filters in one generic sidebar which might be useful if you have a lot of filters that apply to all slices.
> If however you have only a small set of filters (or just one), the side bar layout is in my opinion unneccesary and less user friendly. Currently we use for example one filter box with 2 entries at the top of page.
> Or we use multiple filter boxes (different tabs) that each filter only a specific set of slices. The position of the filterbox makes it clear to the user which slices will be filtered.
> When using the sidebar it is unclear which filter will apply to which slice (only visible after you applied it).
> Other BI tools such as Tableau keep the dasbhoard filter as a dashboard component that has to be positioned somewhere on the dashboard instead of external sidebar.

FYI we've retained the possibility of adding native filters as regular chart components, in which case they work much like filter boxes (in this case they become charts with cross filters rather than native filters). We still need to refine the UX, but check this PR to see how this feature is progressing (in the example the native select filter is added to the dashboard): https://github.com/apache/superset/pull/13625

**Comment by PowerPlop** [comment]
@villebro If there is still a separate filter viz, that you can ignore my comments. 
Adding an option to disable the native dashboard filter sidebar on a dashboard might make sense, if you have cross filters in the dashboard. Or how do you plan to sync both filter options?

**Comment by villebro** [comment]
@PowerPlop native filters (the one on the left) will be the preferred way to add filters to a dashboard, as the majority of users want to target all charts in a dashboard. However, for the use case you are facing it will be possible to use filter plugins that support cross filtering mode as chart elements (e.g. range and select support it), in which case they are cross filtering charts. If a dashboard doesn't have any native filters, the filter tab is collapsed by default.

**Comment by junlincc** [comment]
Uploading Screen Recording 2021-03-31 at 2.35.29 PM.mov…

better error message for non compatible time grain filter.

**Comment by ronaldvanrij** [comment]
Blocking issue: when using the Filter Type "Select filter" there is a limit of autocomplete items, currently set to 10,000. This is fine, however I am unable to filter to the 10,001th item, even when I force the exact value I want to filter to. The filter simply states "No Data".

**Comment by unreal-altran** [comment]
@junlincc , @ronaldvanrij (vote +1) 

In the standard filterboxes it is possible to enable the search on very voluminous comboboxes (> 10000 elements) as per the attached image. Is it possible to replicate this functionality in phase 2 of the native filter and cascade filter? Today, if the filter dataset exceeds 10,000 elements, it is a proboem. I have also not found a configuration that allows to alter this limit, it seems that the ROW_LIMIT, FILTER_SELECT_ROW_LIMIT,VIZ_ROW_LIMIT are ignored.

standard filterboxes
![Cattura](https://user-images.githubusercontent.com/52736907/117775902-411a7680-b23b-11eb-87ed-4cf628f00d99.PNG)

native filter and cascade filter
![Immagine 2021-05-11 092548](https://user-images.githubusercontent.com/52736907/117775913-44156700-b23b-11eb-930f-8f3c4a383820.png)

**Comment by jessicaxyl** [comment]
Suggestion: Allow the dashboard native filter to be closed/opened by default when you first load the dashboard. Currently it is opened every time you load or refresh the dashboard, and it is quite tedious to keep on closing it

**Comment by tejaskumar-cm** [comment]
Hi team,
I was using this feature for a use case, where I need to select one or list of user id within a date range and visualise their order details.

To achieve this when I included date filter and user id filter (with parent filter as date filter), in the back-end a query has been ran to select all distinct dates and user id. This indirectly scanning my entire table.

But like we have a option in filter box, I want to have a default date range when the UI open/loads and only for this date range distinct user id should be listed. When date range is changed the user id list should also change accordingly. I tried using default value, since it is date format in milliseconds i was able to provide only 1 value and not a range and hence it is only giving 1 result.

Is there an option to achieve this, and if not can it be included as feature in upcoming release? Because every time when I open my dashboard is it overloading my db.

**Comment by villebro** [comment]
@tejaskumar-cm this is already possible. Just check "Pre-filter available values" and specify the time range: 
![image](https://user-images.githubusercontent.com/33317356/122358593-74000a80-cf5d-11eb-9396-8d9e7ffdc0a0.png)

**Comment by avant-garde-cracker** [comment]
Hi All,

With the native filters I am not getting all the new features(Advanced features) of filter configurations and scoping. I have upgraded the superset and have added the following to the config file :-
FEATURE_FLAGS = {
    "ENABLE_TEMPLATE_PROCESSING": True,
    "DASHBOARD_NATIVE_FILTERS":True,
    "DASHBOARD_CROSS_FILTERS":True
}
But the Advanced Features like  "Pre-filter available values" isn't available. Could you please help me with this. I am attaching the screenshot of the features available to me.
![Screenshot from 2021-06-17 14-46-11](https://user-images.githubusercontent.com/47210155/122372189-1a5c0800-cf7e-11eb-8357-94f34d03cbcc.png)

**Comment by villebro** [comment]
My screenshot was from master branch, which won't be available in an official release until 1.3 comes out (the feature flag will be enabled by default then).

**Comment by airliquide31** [comment]
Thanks for all the work done it's awesome.

But I've not found the contextualised Filter.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/FRANCO~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/FRANCO~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Value1 | Value2 | Metric
-- | -- | --
Green | AAAA | 1
Green | BBBB | 6
Green | AAAA | 10
Green | BBBB | 11
Green | CCCC | 11
Pink | AAAA | 56
Pink | DDDD | 11



</body>

</html>
  If a Put a filter on value1 & value2.

Is it possible to only have value1 corresponding to the selected value in value2. And same way of working on the other way ? With hierachical filterting it's a drop down Parent -> Child. But contextual filtering is all elements filtered by item selected.

thx again for the hudge improvement !

**Comment by mdeshmu** [comment]
Allow to re-arrange the display sequence of the filters.
![image](https://user-images.githubusercontent.com/57723564/134775984-b4c1d92e-ac6a-453a-bc87-10bf17aacff5.png)

**Comment by mbtronics** [comment]
I am looking for a way to search a column with ILIKE (free text search).
Is that something that could be supported by native dashboard filters?

**Comment by usamaB** [comment]
How users other than the owner can see the filters on a dashboard. Only the owner of the dashboard or Admin(s) can see the filters. Is the Filter UI/View/Acess tired to some special permissions? If so which ones? I couldn't find much in the doc.

**Comment by falgunifb** [comment]
How we can pass native filter through URL

**Comment by bryan-oliveira** [comment]
> @amitmiran137 How non-admin users other than the owner can see the filters on a dashboard. Only the owner of the dashboard or Admin(s) can see the filters. Is the Filter UI/View/Acess tired to some special permissions? If so which ones? I couldn't find much in the doc. ![Screenshot 2022-01-18 at 17 51 42](https://user-images.githubusercontent.com/13015524/149982154-45e64c09-136a-4b1c-a844-9b5a8f7e37ea.png)

Ran into same issue here. Users with the Gamma role can't access column values. Giving users the `can get column values on Datasource` permission changes the `GET api/v1/datasource/table/23/column/asset/values/` request from a 403 Forbidden to a 500 Fatal Error.

**Comment by aibunny** [comment]
> Suggestion: Allow the dashboard native filter to be closed/opened by default when you first load the dashboard. Currently it is opened every time you load or refresh the dashboard, and it is quite tedious to keep on closing it

Is this implemeted yet?
