### ISSUE TITLE
[sql_lab]refresh metadata when user input non-select statement

### ISSUE THREAD

**Issue by junlincc** [apache/superset#13590]
<img width="1666" alt="Screen Shot 2021-03-11 at 7 08 14 PM" src="https://user-images.githubusercontent.com/67837651/110886293-45f39600-829d-11eb-81c4-5d35d9e26bf4.png">

I dropped a table named "calcs" in SQL editor and it ran successfully. what I expected was 
1) "calcs" is removed from the dropdown list in "SEE TABLE SCHEMA" ✅
2) "calcs" table metadata preview is removed from the left panel. ⛔️ Refreshing metadata should also be applied in any other DML, e.g. ALTER 

cc @eschutho @betodealmeida @mistercrunch

**Comment by rusackas** [comment]
This is still the case in 2.0.1. FYI @yousoph @eschutho

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
