### ISSUE TITLE
Need range highlighting like grafana and excel

### ISSUE THREAD

**Issue by snehlata08** [apache/superset#13597]
I want to highlight one of the columns in my table depending on the value. 
Means if the value is between 0 - 50 I want to put background color as red, between 50 - 100 as green and so on. 
I have not been able to find any correct visualization for this. So let me know how can we achieve this in superset.

**Comment by junlincc** [comment]
@snehlata08 thanks for requesting! color coding/conditional formatting is in our 1 year roadmap. 🙏 closing issue for now, will give you update once it's available.
