### ISSUE TITLE
Setup Auto-Deploy Superset Documentation

### ISSUE THREAD

**Issue by srinify** [apache/superset#13599]
Since we've moved over to DocZ for the Apache site (superset.apache.org), we've had to manually build and git push assets to the `superset-site` folder (https://github.com/apache/superset-site).

@nytai mentioned that we could setup auto deploy so this step would be eliminated. Creating this issue to keep track of this work / request! 🙏

**Comment by nytai** [comment]
Opened https://issues.apache.org/jira/browse/INFRA-21607 as the fist step
