### ISSUE TITLE
[chart]multiple charts broken on maximizing 

### ISSUE THREAD

**Issue by vivekdixit2510** [apache/superset#13600]
## Screenshot
Without Maximize 
![max1](https://user-images.githubusercontent.com/80536487/110966903-ca1c4b00-837b-11eb-98ef-8017e1df7067.PNG)
With Maximize 
![max2](https://user-images.githubusercontent.com/80536487/110966937-d56f7680-837b-11eb-8a17-6b4d4f3adc39.PNG)

Without Maximize (bar graph)

![max3](https://user-images.githubusercontent.com/80536487/110967599-942b9680-837c-11eb-9774-86095b20b390.PNG)

With Maximize (scroll till bottom)
![max4](https://user-images.githubusercontent.com/80536487/110967648-a4437600-837c-11eb-94d4-1a913fd2415c.PNG)

[drag & drop image(s) here!]

## Description

Pie Charts and Bar Graphs have broken on maximizing. 

## Design input
Pie Chart: It should not disappear from the screen.
Bar Graph: It should fit on the page. 
@slayerjain

**Comment by vivekdixit2510** [comment]
Is there a way to disable the maximize option in superset?

**Comment by junlincc** [comment]
thanks for reporting! this is a known issue. if you already have a solution to fix either or both charts, we will make sure your PR is reviewed. 🙏 @vivekdixit2510

**Comment by slayerjain** [comment]
@junlincc is it possible to disable the maximise button in dashboards for the time being?

**Comment by junlincc** [comment]
i dont think so, unfortunately. @slayerjain 🙏

**Comment by junlincc** [comment]
worldmap is also broken

**Comment by amitmiran137** [comment]
Resolved #14371
