### ISSUE TITLE
The SQL is incorrect using the time type field

### ISSUE THREAD

**Issue by chen-ABC** [apache/superset#13609]
![image](https://user-images.githubusercontent.com/30097790/111022080-853ff500-840b-11eb-9d53-0fc0861f1747.png)

```
SELECT toStartOfMinute(toDateTime(toDateTime((timestamp/1000)))) AS timestamp,
       COUNT(*) AS count
FROM pupuolap.component_dependency_records_distributed
WHERE timestamp >= 1614960000000
  AND timestamp < 1615564800000
GROUP BY toStartOfMinute(toDateTime(toDateTime((timestamp/1000))))
ORDER BY count DESC
LIMIT 10000;
```
![image](https://user-images.githubusercontent.com/30097790/111021831-05fdf180-840a-11eb-8cb2-506f9ad581be.png)

The alias name should not match the original field name.

### Environment

(please complete the following information):

- superset version: `0.38.0`
- python version: `3.7.9`
- node.js version: `v12.18.3`

**Comment by zhaoyongjie** [comment]
hi @chen-ABC 
Why is `date picker` generated long int in `where clause`? could you show me the full screenshot on the explore page?
Could you test this dataset in Superset 1.0?

**Comment by chen-ABC** [comment]
@zhaoyongjie   
Because my time field is a timestamp,
![image](https://user-images.githubusercontent.com/30097790/111023493-567a4c80-8414-11eb-8d50-953201c147ae.png)

**Comment by zhaoyongjie** [comment]
From the CK error log seems that you use incompatible data type calculation. please double check table schema in clickhouse
