### ISSUE TITLE
[chart]KeyError in Bar Chart if value is null

### ISSUE THREAD

**Issue by zufolo441** [apache/superset#13612]
Starting from version 1.0.1 Bar chart graph stopped working if one  metric value is null.
I have a metric so defined: 
AVG(indicatore) FILTER (WHERE codlivterr = '15' and selezionato = 1) AS "Italia selezionata" 
if the result is null I obtain this error:
KeyError: "['Italia selezionata'] not in index"
I had to modify in: 
coalesce(AVG(indicatore) FILTER (WHERE codlivterr = '15' and selezionato = 1),0) AS "Italia selezionata" 

Up to v. 1.0 null values were accepted.

DB is PostgreSQL.

**Comment by geido** [comment]
Closing in favour of #13968
