### ISSUE TITLE
Add example for deck.gl geojson

### ISSUE THREAD

**Issue by riazarbi** [apache/superset#13618]
**Problem**
I have been trying to plot a simple deck.gl geojson chart for a few days and have not yet been able to. I am assuming it's something I'm not doing correctly on my side. I can't find a working geojson example anywhere online to show me how to do it correctly

**Describe the solution you'd like**
Inclusion of a geojson-driven example in the standard superset chart gallery

**Describe alternatives you've considered**
I have search high and low for examples in the wild. 

**Additional context**
To be honest, I haven't been able to get any deck.gl charts to work, but at least I have examples to work with for the other deck.gl chart types. In general, the data interop between what my spatial database sends to superset and what deck.gl can plot is pretty bad. If we adopt superset as a produciton solution I would create a feature request to support the parsing of EWKT and WKT format straight to the deck.gl plots. EWKT and WKT are good solutions because they work well with any tabular storage format and most geospatial databases support an st_totext method or similar.

**Comment by riazarbi** [comment]
After having browsed the issues, I'd like to mention issues #13552 and #6373 - these are good suggestions as WKT is highly portable and supported by a lot of databases.

**Comment by junlincc** [comment]
@riazarbi https://www.youtube.com/watch?v=b3YEzpwBUXk hope this video help. 

we may look into adding WKT polygons.
