### ISSUE TITLE
[Explore]add SQL expression validator to metric popover and Edit dataset modal 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#13633]
Currently user can create saved from edit dataset modal, and ad hoc metrics from control panel popover using SQL expression. There's no way to validate the expression before saving. Invalid ones cause error when click RUN QUERY. 

Proposed change: Alarm user the syntax error on save metric(in both popover and edit dataset modal), instead of on RUN QUERY 

https://user-images.githubusercontent.com/67837651/111210889-083b8980-858b-11eb-8a61-e085d95ad980.mov

https://user-images.githubusercontent.com/67837651/111210943-1689a580-858b-11eb-8b4a-cfbab55a2a06.mov

**Comment by junlincc** [comment]
@kgabryje if it takes less than 1 day to complete, let's tackle it. otherwise, @zhaoyongjie include this functionality in your redesign?

**Comment by rusackas** [comment]
Closing as stale, but wondering if anyone still wants to tackle this. Let's take it up, or start a discussion if anyone is interested.
