### ISSUE TITLE
Pie chart LABEL TYPE does not work

### ISSUE THREAD

**Issue by cccs-jc** [apache/superset#13645]
The Pie chart has a customization which lets you choose the label to display. The control has no effect.

### Expected results

Expecting the labels to display % and/or category based on LABEL TYPE selection.

### Actual results

Nothing happens.

#### Screenshots

![image](https://user-images.githubusercontent.com/56140112/111327282-a2f79f00-8643-11eb-9dd5-b9c2bc5f0372.png)

### Environment

- superset version: `1.0.1`
- python version: `3.7`
- node.js version: `v14.15.5`

**Comment by junlincc** [comment]
i believe this has been fixed in master. please double check and lmk~🙏
