### ISSUE TITLE
[SQL Lab] Colors on SQL Lab tabs - Very small UI enhancement - 

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#13648]
Currently the tabs on SQL Lab queries show green circle when a query is running as well as when a query has successfully finished. 

The green circles for "query running" and "query completed" could be made more distinct - different color, or having the "query running" circle be hollow, and the "query completed" one filled in. This would enable users, who might go to SQL Lab and trigger few queries and then want to view results, visually see which of their queries are still running vs. finished.

Screenshot current state:
One query is running one has finished. User sees both as just a green circle.
![image](https://user-images.githubusercontent.com/61221714/111344909-08df2900-863a-11eb-943f-4928154c4aa4.png)

**Comment by yousoph** [comment]
#11123 covers this! :)

**Comment by zuzana-vej** [comment]
closing this because it's duplicate with https://github.com/apache/superset/issues/11123
