### ISSUE TITLE
Could not load database driver: TrinoEngineSpec

### ISSUE THREAD

**Issue by mschuch** [apache/superset#13640]
I followed the trino tutorial and started superset with the Docker Compose of the latest git repository.
And now i get always the error:

ERROR: Could not load database driver: TrinoEngineSpec 

### Expected results

I have access to trino database

### Actual results

Error Message

#### How to reproduce the bug

1. Clone git repo
2. Add sqlalchemy-trino to requirements-local.txt  (https://superset.apache.org/docs/databases/dockeradddrivers)
3. Execute "docker-compose -f docker-compose-non-dev.yml up"
4. Add trino://{username}:{password}@{hostname}:{port}/{catalog} to database and see error

### Environment

(please complete the following information):

- superset version: `docker version:  latest`
- python version: `python --version`
      Python 3.7.9
      Flask 1.1.2
      Werkzeug 1.0.1

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

```
pip freeze output of worker:
simplejson==3.17.2
six==1.15.0
slackclient==2.5.0
SQLAlchemy==1.3.20
sqlalchemy-trino==0.2.0
SQLAlchemy-Utils==0.36.8
sqlparse==0.3.0
tableschema==1.20.0
tabulator==1.52.5
thrift==0.13.0
thrift-sasl==0.4.2
trino==0.305.0

```

**Comment by liamnv** [comment]
@dungdm93

**Comment by manuelreis** [comment]
same issue here

**Comment by dungdm93** [comment]
Are you install superset from [pypi](https://pypi.org/project/apache-superset/) or GitHub?

**Comment by mschuch** [comment]
@dungdm93 
I installed superset from the GitHub repo with docker-compose
`docker-compose -f docker-compose-non-dev.yml up`

**Comment by dungdm93** [comment]
I just check it out, there is no package `sqlalchemy-trino` installed inside `apache/superset:latest` image.
![Screenshot from 2021-03-18 18-08-12](https://user-images.githubusercontent.com/6848311/111616973-1e5c7a80-8815-11eb-8607-415398a3cff2.png)
In this case, I'd like to suggest u using a custom image with `pip install apache-superset[trino]`

**Comment by mschuch** [comment]
@dungdm93  But i added "sqlalchemy-trino" to the  requirements-local.txt, is that not sufficient?

**Comment by dungdm93** [comment]
Sorry, I forgot `Add sqlalchemy-trino to requirements-local.txt`. It's MUST work.

**Comment by dungdm93** [comment]
@mschuch I just realize that `superset-webserver` in the docker-compose use default command (`docker/docker-entrypoint.sh`)
which don't load `docker/docker-bootstrap.sh` file, and then don't install the dependencies is defined in `requirements-local.txt`
https://github.com/apache/superset/blob/adc247b7e4fade7ef0d68cb07df5e3aa6bf9a677/docker-compose-non-dev.yml#L43-L51

For now, you could workaround by overriding docker command like this:
![Screenshot from 2021-03-18 21-01-13](https://user-images.githubusercontent.com/6848311/111638709-2c1dfa00-882d-11eb-89f8-755b2c24f144.png)

**Comment by mschuch** [comment]
@dungdm93 
Thank you now it works as intended.

**Comment by manuelreis** [comment]
@dungdm93 I was using the helm chart contained in this repo.

**Comment by dungdm93** [comment]
@manuelreis you shoud add `sqlalchemy-trino` to `additionalRequirements`

**Comment by praveenks18375** [comment]
@dungdm93 Is there any way we can check all the installed database drivers in Superset? I have installed SUperset with docker on ubuntu. Can you please help me with the commands? or the path where I can find the installed drivers?

**Comment by srmalsallout** [comment]
No need to update docker-compose-non-dev.yml 
since the latest docker-compose already has the docker-bootstrap.

You need to access the docker container (of the image "superset_app") using bash and install the trino driver using pip
1- Get Container name:
`docker ps`
in my case see the attached image my container name is "099a15407304"

2- Connect to container using bash
`docker exec -u 0 -it <container_name> bash`
in my case
`docker exec -u 0 -it 099a15407304 bash`

3- Install Trino Driver
`pip install trino`

No you are ready to go

![image](https://user-images.githubusercontent.com/62013676/229311621-ab0a8d15-9dce-401f-967a-8737b59bf602.png)

**Comment by cesar-loadsmart** [comment]
Just updated to Superset 2.1.0 and got the same error when creating a new connection.

**Comment by mainakg-dev** [comment]
facing the same error
