### ISSUE TITLE
[sql-lab]Pyarrow to pandas fails when timestamp is out of bounds

### ISSUE THREAD

**Issue by cabo40** [apache/superset#13661]
When querying from a database with a timestamp column with [us] granularity and missing data as zero dates the query cannot be completed

### Expected results

The query result with full precision of dates

### Actual results

`pyarrow.lib.ArrowInvalid: Casting from timestamp[us] to timestamp[ns] would result in out of bounds timestamp`

#### How to reproduce the bug

Tested with a DB2 database, select a timestamp from 1900-01-01 in sql-lab

### Environment

(please complete the following information):

- superset version: `0.38.0`
- python version: `3.7.9`
- node.js version: `16.14.0`

**Comment by cabo40** [comment]
Hi @junlincc . I am very very sorry for not answering sooner. 

I tested with a fresh installation and could reproduce by querying in sql lab on the `examples` database:
```sql
SELECT TIMESTAMP '01-01-1000';
```
result:
![image](https://user-images.githubusercontent.com/1605852/112705667-71fa4400-8e65-11eb-93cc-9386b1757396.png)

**Comment by junlincc** [comment]
Thanks for the additional details and contributing a fix PR, we will get it reviewed asap! 
@cabo40 🙏

**Comment by cabo40** [comment]
Thanks to you for reviewing and contributing this great tool!
