### ISSUE TITLE
Clarify Superset Version Number in the UI

### ISSUE THREAD

**Issue by srinify** [apache/superset#13674]
## Screenshot

<img width="214" alt="Screen Shot 2021-03-17 at 2 23 08 PM" src="https://user-images.githubusercontent.com/801507/111518504-82efda80-872c-11eb-9fe0-bfb2fd23c5e3.png">

## Description

I've been seeing Superset users, at least once a week, get tripped by the fact that the Version number displayed in the Superset UI is always `0.999.0dev` if people are using the `latest` tag or using bleeding edge master from Github.

Here's a recent user that was confused, wondering why they aren't on Superset v1.1: https://apache-superset.slack.com/archives/C0170U650CQ/p1616004990065000

## Potential Solutions

**Ideal User Experience:**
It Just Works (TM). Wherever possible, show the real version (using the git sha as the 'data source') for this. No doubt this will require extra work, but this would enhance the first day / first week user experience!

**Less than ideal but more helpful**
Keep the git sha but remove the version number from the UI

**Comment by junlincc** [comment]
this seems to be a highly requested change and will benefit all Superset users. @mayurnewase can you take a look? 🙏

**Comment by zhaoyongjie** [comment]
In order to convenient debugging, not only add the current version but also show the commit hash here.

**Comment by rusackas** [comment]
I'm not quite sure the best way to handle this, but I think the release maker script might be one option to set/bump this number in the file. It would still be overridable by orgs by changing the config of their deployment.

**Comment by villebro** [comment]
Let me review and test the PR by @mayurnewase this week so we can get it merged. I think the PR should work in most cases, but I just want to test a few more edge cases.

**Comment by layoaster** [comment]
Not exactly the same issue but deeply related: It is also important to start support for versioned tags on official Docker images.

Not being able to pin down to a specific Superset (Docker image) version is really frustrating and insecure.

**Comment by sanjayssk** [comment]
Having same problem where embedDashboard works on an earlier image and fails on the latest one with 403. How do I find the exact version of the earlier image?

**Comment by muneerj** [comment]
I can see this issue still exists in the 3.0.0 release. Any chance of having this rolled out to the latest build? We really should be able to show the correct version in the front-end.

**Comment by rusackas** [comment]
The 3.0 (or any) release should have the proper version number if you're running the actual release. Anything pulled from `master` is not an official version, so it will show a placeholder and a (hopefully) correct SHA. 

Lately, it shows `0.0.0-dev` as the placeholder. I wonder if we should just say "Unofficial Release" here or something, so people are less confused by it. Thoughts @kasiazjc @eschutho @michael-s-molina ?

**Comment by rusackas** [comment]
Closing as stale... As I said about 9 months ago, we can replace the placeholder version with something else (e.g. just the SHA or "Unofficial") but that's about the best we could do. Anyone can bring the issue to a Town Hall sync or force the discussion via a PR or SIP if they'd like.
