### ISSUE TITLE
Can't access database in SQL lab 

### ISSUE THREAD

**Issue by liamnv** [apache/superset#13689]
I'm create a role to access a database schema, assign this role to a user, but user can query this table in `CREATEA TABLE AS

### Expected results

User can run this query

### Actual results

Superset return you need access to the following tables: xxx, all_database_access or all_datasource_access

#### Screenshots

<img width="1497" alt="Screen Shot 2021-03-18 at 15 55 14" src="https://user-images.githubusercontent.com/8578629/111611882-7f814f80-880f-11eb-8801-7b7d052a451e.png">
<img width="1173" alt="Screen Shot 2021-03-18 at 15 55 20" src="https://user-images.githubusercontent.com/8578629/111611899-84de9a00-880f-11eb-839a-663d0e6315f0.png">

#### How to reproduce the bug

1. Connect Superset to Trino
2. Add database A & B from Trino to Superset
3. Create Role `test`, assign permission `schema acccess con A.xxx`, assign to user X
4. Run query similar to screenshot

### Environment

- superset version: 1.0.1
- python version: 3.8

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing as stale since the issue is over 2 years old, but if you're still facing this, let's revisit it!

**Comment by xujipm** [comment]
I'm still facing this on version 3.1.3

**Comment by rusackas** [comment]
@xujipm do you have any more context to add to the issue? It seems like nobody else ran into this issue for over three years.

**Comment by xujipm** [comment]
> @xujipm do you have any more context to add to the issue? It seems like nobody else ran into this issue for over three years.

I have authorized the permissions of sample.main to this user, but this account still cannot be queried in sql_lab 

![image](https://github.com/apache/superset/assets/3202911/b22b9700-0731-4a33-a27b-07034700895f)

![image](https://github.com/apache/superset/assets/3202911/8ee587d1-b20e-4383-8ae7-d3a75c3f9b97)
