### ISSUE TITLE
How to setup Superset and setup embeded charts

### ISSUE THREAD

**Issue by Riskatri** [apache/superset#13697]
Hi iam using superset version 1.0.0 but when i am trying to run with superset run -p 8088 --with-threads --reload --debugger i have an error 

![image](https://user-images.githubusercontent.com/59104917/111727268-22cc7600-889d-11eb-8e04-94e28aa5c977.png)

can someone help me?

**Comment by zhaoyongjie** [comment]
Hi @Riskatri , did you change the `sueprset/config.py` file?

**Comment by Riskatri** [comment]
@zhaoyongjie this issue has been solve. thankyou. but did you know about embed superset with iframe? i am trying to embed but i have an error like this 

![image](https://user-images.githubusercontent.com/59104917/111741247-beb7ab00-88b8-11eb-9ccb-2110bab2aa5c.png)

i follow to change the config like this https://github.com/apache/superset/issues/8830 . but didn't work for me.

**Comment by zhaoyongjie** [comment]
@Riskatri 
A quick solution is to set `WTF_CSRF_ENABLED = False` in config.py, or any overwrite config file.

**Comment by Riskatri** [comment]
@zhaoyongjie i've tried it, but then i logged in there was no response and went back to login like this 
![image](https://user-images.githubusercontent.com/59104917/111749678-b1a0b900-88c4-11eb-9cc2-dfb6a5bfdc9d.png)

**Comment by anphamvn** [comment]
I had the same problem when embedding the superset dashboard in my web, I have tried many ways but with no luck hix
Can someone help me to solve it?

**Comment by Riskatri** [comment]
@anphamvn follow the step here :
-	Set ROLE_PUBLIC as public and PUBLIC_ROLE_LIKE = ‘Gamma’ in file config.py
-	Add datasource access in public role
-	Re-launch superset with superset init
-	If have an error ' the csrf token is missing' , set WTF_CSRF_ENABLED = False in config.py

**Comment by anphamvn** [comment]
> @anphamvn follow the step here :
> 
> * Set ROLE_PUBLIC as public and PUBLIC_ROLE_LIKE = ‘Gamma’ in file config.py
> * Add datasource access in public role
> * Re-launch superset with superset init
> * If have an error ' the csrf token is missing' , set WTF_CSRF_ENABLED = False in config.py

Thanks @Riskatri 
i followed your instructions but still no luck :)

1. Set ROLE_PUBLIC as public and PUBLIC_ROLE_LIKE = ‘Gamma’ in file config.py

**Comment by Riskatri** [comment]
@anphamvn try to add PUBLIC_ROLE_LIKE_GAMMA = True in file config.py and re-launch again.

**Comment by albertwgchu** [comment]
I added the following to my config:

WTF_CSRF_ENABLED = False
SESSION_COOKIE_SAMESITE = None
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = False
AUTH_ROLE_PUBLIC = 'Public'
PUBLIC_ROLE_LIKE = 'Gamma'

I don't get the login screen and I can see that the api requests for charts, datasets and dashboard succeed.  However I'm getting a javascript error.  @Riskatri did you run into this?

![image](https://user-images.githubusercontent.com/11964537/118336041-26abfb80-b4ce-11eb-9eb5-d8255440cfd1.png)

29db33713260b5a6d757.chunk.js:2 TypeError: Cannot convert undefined or null to object
    at values (<anonymous>)
    at spa.3b0a2a722a47bd99984d.entry.js:558
    at spa.3b0a2a722a47bd99984d.entry.js:1436
    at spa.3b0a2a722a47bd99984d.entry.js:558
    at spa.3b0a2a722a47bd99984d.entry.js:1098
    at 7ee55ea40fa185cf788d.chunk.js:1
    at au (29db33713260b5a6d757.chunk.js:2)
    at mc (29db33713260b5a6d757.chunk.js:2)
    at t.unstable_runWithPriority (29db33713260b5a6d757.chunk.js:2)
    at Ia (29db33713260b5a6d757.chunk.js:2)

**Comment by anilvpatel21** [comment]
Hi, @albertwgchu @Riskatri 
I am getting a similar issue, I check the logs its says 

`2021-07-15 15:32:54,576:WARNING:root:Class 'werkzeug.local.LocalProxy' is not mapped`

**Comment by HariniPuppala** [comment]
Hi, @albertwgchu @Riskatri @anilvpatel21 

I am getting the similar issue as you all mentioned.

Below are my Superset setup details:
Configured LDAP Authentication in superset.
Enabled a Custom Security Manager to authenticate based on a jwt-token.
The jwt-token based authentication is working as expected and we are able to redirect to the dashboards without the login page
The same is not working when passed in an iframe.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/87519153/125913801-8201011c-928b-4b43-b159-646d1f81875f.png)

I can see a warning message in the logs as below:
WARNING:root:Class 'werkzeug.local.LocalProxy' is not mapped

Can anyone please help. Thanks in advance!

**Comment by anilvpatel21** [comment]
It's might be a problem with Flask Appbuilder recently upgraded in superset 1.2

For a while use superset 1.1, with your config. It will works out.

**Comment by Xx0w0wxX** [comment]
@HariniPuppala 

I had a same error and solved as follows

- remove redis cache

**Comment by jhult** [comment]
Related: #8382

**Comment by handita** [comment]
How to remove redis cache I have experiencing same problem.. @Xx0w0wxX

**Comment by Xx0w0wxX** [comment]
@handita In my case, remove the mounted volume

**Comment by jhult** [comment]
Also related to #15737 and #16718.

**Comment by vikas-nykaa** [comment]
I am also getting same error on google chrome while iframe superset url

**Comment by Kingflyinger** [comment]
> @anphamvn maybe, you are wrong. just uncomment it in the AUTH_ROLE_PUBLIC section, don't rewrite it and for PUBLIC_ROLE_LIKE. You can find it on line 265 _
> 
> > PUBLIC_ROLE_LIKE: Optional [str] = 'Gamma'
> 
> _. change it there, don't rewrite it. and always re-launch again after change the file config.py. if still no successful, try to add PUBLIC_ROLE_LIKE_GAMMA = True in file config.py and re-launch again.

thanks a lot.it solved my problem

**Comment by anonymouse-jj** [comment]
> 

The superset installation using helm overrides the default value for WTF_CSRF_EXEMPT_LIST in superset/config.py and leaves it as an empty list.

I think this is a mistake but at the very least there should be some sort of documentation on the change

**Comment by mcgorias** [comment]
> Hi, @albertwgchu @Riskatri @anilvpatel21
> 
> I am getting the similar issue as you all mentioned.
> 
> Below are my Superset setup details: Configured LDAP Authentication in superset. Enabled a Custom Security Manager to authenticate based on a jwt-token. The jwt-token based authentication is working as expected and we are able to redirect to the dashboards without the login page The same is not working when passed in an iframe.
> 
> ![MicrosoftTeams-image](https://user-images.githubusercontent.com/87519153/125913801-8201011c-928b-4b43-b159-646d1f81875f.png)
> 
> I can see a warning message in the logs as below: WARNING:root:Class 'werkzeug.local.LocalProxy' is not mapped
> 
> Can anyone please help. Thanks in advance!

I had the same issue, 
  According to the ["Manage access to Dashboards part"](https://superset.apache.org/docs/creating-charts-dashboards/creating-your-first-dashboard/#manage-access-to-dashboards) of the documentation, you should [enable DASHBOARD_RBAC feature flag] (https://superset.apache.org/docs/installation/configuring-superset/#feature-flags)

I followed the docker-compose install guide, so I had to edit `./docker/pythonpath_dev/superset_config.py` and add

**Comment by anilvpatel21** [comment]
Please update your superset.

**Comment by fabioselau077** [comment]
> Hi, @albertwgchu @Riskatri I am getting a similar issue, I check the logs its says
> 
> `2021-07-15 15:32:54,576:WARNING:root:Class 'werkzeug.local.LocalProxy' is not mapped`

same here, resolved? i'm using ec2 aws

**Comment by fabioselau077** [comment]
> I am also getting same error on google chrome while iframe superset url WARNING:root:Class 'werkzeug.local.LocalProxy' is not mapped But on firefox and safari it is working fine. Any suggestions

resolved?
