### ISSUE TITLE
Getting fatal error while creating the chart from dataset

### ISSUE THREAD

**Issue by vishalsawale9** [apache/superset#13706]
### Expected results

Charts should be saved when we add it using dataset

what you expected to happen.

### Actual results

We are getting fatal error whilst creating the chart after creation of dataset.

#### Screenshots

Fatal error

<img width="1473" alt="Screenshot 2021-03-19 at 7 23 26 PM" src="https://user-images.githubusercontent.com/70691901/111790795-9778d200-88e8-11eb-97e4-e4cf344a3d18.png">

NOAUTH error

![image](https://user-images.githubusercontent.com/70691901/111790926-bb3c1800-88e8-11eb-830c-83f4c4c32cb4.png)

However we are able to user SQL lab on same database/schems as below screenshot.

![image](https://user-images.githubusercontent.com/70691901/111791045-d7d85000-88e8-11eb-8524-c12a68dc512c.png)

#### How to reproduce the bug

1. Go to '

### Environment

(please complete the following information):

- superset version: `FROM apache/superset:1.0.0 in our docker file`
- python version: `python --version 3.8`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by kittylon** [comment]
> This was an configurational issue. Same has been resolved now. Hence closing the same.

Hello, what was missing in the configuration? I am encountering the same issue

**Comment by vishalsawale9** [comment]
> > This was an configurational issue. Same has been resolved now. Hence closing the same.
> 
> Hello, what was missing in the configuration? I am encountering the same issue

It was related to OAUTH, as I remember vaguely.
