### ISSUE TITLE
The CSRF session token is missing when embed superset to frontend web

### ISSUE THREAD

**Issue by Riskatri** [apache/superset#13700]
Hi, i am using apache superset version 1.0.0 and i want to embed dashboard to my frontend web using iframe but iam getting error 

![image](https://user-images.githubusercontent.com/59104917/111744779-54096e00-88be-11eb-90ed-a3c00f22c0ca.png)

what i do : 
- run superset run -p 8088 --with-threads --reload --debugger
- put url to iframe like this 

**<iframe width="100%"
    height="800"
    seamless
    frameBorder="0"
    scrolling="no" src="http://127.0.0.1:8088/superset/dashboard/11"></iframe>**

**Comment by zhaoyongjie** [comment]
linked to #13697

**Comment by rusackas** [comment]
Closing as stale... Embedded thankfully seems to be working pretty reliably these days
