### ISSUE TITLE
Keep config, users, databases, datasets, charts, dashboards when container stops

### ISSUE THREAD

**Issue by msanzoo** [apache/superset#13710]
Not sure if its bug. I just don't know how to do it 
### Expected results
Save config, users, databases, datasets, charts, dashboards outside of container so when container stops I can reload it back.
what you expected to happen.
Reload everything back when container starts.
### Actual results
I keep loosing everything.
what actually happens.
when I execute following:
"sudo docker run -d -v /superset:/superset -p 82:8088 --rm --name  superset apache/superset"
it seems to keep user but that's all, no databases connections, datasets ...
### Environment
https://hub.docker.com/r/apache/superset
ubuntu serve 20.04
(please complete the following information):

- superset version: https://hub.docker.com/r/apache/superset:latest
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by danielewood** [comment]
The `--rm` on your docker command means the container is deleted upon termination. 

See: https://docs.docker.com/engine/reference/run/#clean-up---rm

**Comment by msanzoo** [comment]
Thanks for your help. Indeed when I remove --rm I can restart container without loosing data/charts. 
I also wonder what exactly would I have to do or copy from existing container if I wanted to migrate container from one server to another and keep users, databases, datasets, charts and dashboards?
