### ISSUE TITLE
cx_Oracle installation malfunctioning in docker vm

### ISSUE THREAD

**Issue by gnoopy** [apache/superset#13721]
To install a few python packages in the docker vm, I followed instructions as guided in the page https://superset.apache.org/docs/databases/dockeradddrivers 
However, cx_Oracle installation keep failed whenever I restart the superset docker container. 
Is there any recommendation to install jdbc driver for oracle ?

### Expected results
docker vm should start successfully with cx_Oracle

### Actual results

superset_worker_beat     | ERROR: Could not find a version that satisfies the requirement cx_Oracle
superset_worker_beat     | ERROR: No matching distribution found for cx_Oracle
superset_worker          | WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb3ee561550>: Failed to establish a new connection: [Errno 111] Connection refused')': /simple/cx-oracle/
superset_worker          | ERROR: Could not find a version that satisfies the requirement cx_Oracle
superset_worker          | ERROR: No matching distribution found for cx_Oracle

#### Screenshots

![image](https://user-images.githubusercontent.com/11220690/111868604-3de2d700-89be-11eb-8e7f-0f54bfac366a.png)

#### How to reproduce the bug
1. modify ./docker/requirements-local.txt as follows
>> cx_Oracle
sqlalchemy-teradata
hdbcli
sqlalchemy-hana
pybigquery
gsheetsdb

2. docker-compose build --force-rm
3. docker-compose up

### Environment

(please complete the following information):

- superset version:  master branch lastest version on 20 March. 2021
- python version:  n/a
- node.js version: n/a

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by lrbsantos** [comment]
Hi @gnoopy 

I also had some issues trying to install cx_Oracle in docker vm. My solution was to extend the image creating a Dockerfile like this:

FROM apache/superset

USER root

# Install Oracle Instant Client 18.5 (by LRBS)
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
         unzip libaio1 \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -pv /opt/oracle \
    && chown -R "superset:root" /opt/oracle \
    && cd /opt/oracle \
    && curl -Lf "https://download.oracle.com/otn_software/linux/instantclient/185000/instantclient-basic-linux.x64-18.5.0.0.0dbru.zip?xd_co_f=<oracle-random-key>" \
         --output oracle-instantclient-18-5.zip \
    && unzip ./oracle-instantclient-18-5.zip \
    && rm -f ./oracle-instantclient-18-5.zip \
    && echo "/opt/oracle/instantclient_18_5" > /etc/ld.so.conf.d/oracle-instantclient.conf \
    && ldconfig

USER superset 

RUN pip install --no-cache-dir -t /app/superset/pythonpath  cx-Oracle==8.1.0

Then I build a new image from this Dockerfile and my Oracle connections were sucessful.

I hope I'd helped you in something.

Best Regards, Ricardo.

**Comment by JunTech** [comment]
you should run :  ldconfig   to make your dynamic .so  effect,you can  look:  https://blog.csdn.net/march0310/article/details/111374520

**Comment by rusackas** [comment]
Closing as inactive, and hoping that one of the provided solutions worked out :)
