### ISSUE TITLE
How can I delete the login function of superset?

### ISSUE THREAD

**Issue by Dalei1001** [apache/superset#13747]
I want to directly delete the login function of superset instead of automatic login and not use SecurityManage.Thank you.

**Comment by amitmiran137** [comment]
answered by @dpgaspar on slack
_You can create your own Auth view_: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/views.py#L483
(or just override appbuilder/general/security/login_db.html)
_then on your custom security manager (can be really thin) override this_: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/manager.py#L173
_referencing you Auth view_
