### ISSUE TITLE
Frontend tries to fetch faviorite_status over http (not https)

### ISSUE THREAD

**Issue by wowo** [apache/superset#13746]
I'm keep getting 2 error toasts on /superset/welcome: "There was an error fetching the favorite status: NetworkError when attempting to fetch resource."

In js console I see that it tries to reach `/api/v1/dashboard/favorite_status/?q=%21%2849%2C48%2C47%29` over http, but I'm running that on https on custom domain behing Cloudflare. I'm runinng that via docker-compose, everything else works ok.

### Expected results

No error messages, frontend fetches via https.

### Actual results

AJAX fetch calls being blocked due to violating https -> http.

#### How to reproduce the bug

1. Go to welcome dashboard
2. See error "There was an error fetching the favorite status: NetworkError when attempting to fetch resource."

### Environment

(please complete the following information):

- superset version: c64fcd2ba443
- python version: Python 3.7.9
- node.js version: v10.19.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I have `SUPERSET_WEBSERVER_PROTOCOL = "https"` in `docker/pythonpath_dev/superset_config.py` and I've built frontend with `npm run prod`

**Comment by nytai** [comment]
This should be fixed in the next release

**Comment by wowo** [comment]
@nytai do you have any suggestion how to quick fix that? I've been looking in SupersetClient but was struggling to with build... Is it right clue?

**Comment by nytai** [comment]
https://github.com/apache/superset/issues/12592

**Comment by wowo** [comment]
Thanks! Setting `ENABLE_PROXY_FIX=True` in `docker/pythonpath_dev/superset_config.py` helped!
