### ISSUE TITLE
Native select filter does not support arbitrary values like the FilterBox did

### ISSUE THREAD

**Issue by cccs-jc** [apache/superset#13754]
<img width="316" alt="native-filter" src="https://user-images.githubusercontent.com/56140112/112216875-66561580-8bf8-11eb-9a71-a0b2adcd2a41.png">

Unable to enter arbitrary values in the new select native filter. This was possible in the FilterBox. You could select from dropdown or enter new values.

**Comment by villebro** [comment]
Implemented in #14314
