### ISSUE TITLE
Excel upload menu option is missing from master

### ISSUE THREAD

**Issue by cemremengu** [apache/superset#13766]
Is excel upload a (undocumented) feature flag? For some reason it is visible in latest docker distribution but not in master.

Checked but couldn't spot any switches in code

### Expected results

![image](https://user-images.githubusercontent.com/1297759/112272809-b337fb80-8c8d-11eb-9b91-e1f17a516a09.png)

### Actual results

![image](https://user-images.githubusercontent.com/1297759/112272907-ca76e900-8c8d-11eb-8a16-0574a8a41f29.png)

**Comment by junlincc** [comment]
Please checkout, https://github.com/apache/superset/pull/11736 . both should be supported :)

**Comment by cemremengu** [comment]
Reopening since I don't know your workflow, feel free to close.

As a side note, I think the naming changes in PR #11736 should also be applied to excel upload code since it can be a bit confusing. I will send a PR

![image](https://user-images.githubusercontent.com/1297759/112594832-90871d80-8e1a-11eb-8989-40fa801bfa65.png)
