### ISSUE TITLE
How do I add support for a new DBMS?

### ISSUE THREAD

**Issue by clear-m** [apache/superset#13771]
**Is your feature request related to a problem? Please describe.**
I want to investigate the requirements for the official integration of our not yet publicly released [database (DBMS)](http://raijin.co/) with the Superset.

**Describe the solution you'd like**
I have already implemented a Python module that speaks through DBAPI with our DBMS and capable to be used with the Superset locally.
I want to officially integrate this module with Superset in order to provide better support for our customers and to promote our DBMS with the possible addition of a logo to the Superset web page.

Please advise on the exact steps to implement this kind of integration with Superset.

**Comment by srinify** [comment]
Hi @clear-m happy to help with this, I recently published this tutorial post actually: https://preset.io/blog/building-database-connector/ but it looks like the technical part isn't an issue for you!

You can open a PR with the relevant changes. Some things to include:

- Add the database library to `setup.py`, adding a new db_engine_spec in `superset/db_engine_specs/{your_db}.py`
- Add database specific tests to `tests/db_engine_specs/{your_db}_tests.py`
- Add documentation, create a new entry here: `superset/docs/src/pages/docs/Connecting to Databases/` I can help with docs if needed

**Use this PR by @villebro and I as a guide: https://github.com/apache/superset/pull/13152/files **
