### ISSUE TITLE
[SQL Lab] Can't scroll in SQL Lab Query History (again)

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#13789]
Can't scroll in SQL Lab query history - the scroll bar is not there.

**Expected results**
User was previously able to scroll using a scoler on the right side.

**Actual results**
User can't scroll to see previous query history details

**Screenshot**
<img width="1146" alt="Screen Shot 2021-03-24 at 5 23 01 PM" src="https://user-images.githubusercontent.com/61221714/112400549-d2eb1600-8cc5-11eb-9530-427c16e1e372.png">

**Comment by zuzana-vej** [comment]
FYI @yousoph

**Comment by zuzana-vej** [comment]
This was resolved last month and now recently the regression happened again: https://github.com/apache/superset/issues/12922

**Comment by yousoph** [comment]
Fixed with: https://github.com/apache/superset/pull/13822
