### ISSUE TITLE
superset-frontend]# npm run dev-server     ERR

### ISSUE THREAD

**Issue by tlkzzz** [apache/superset#13791]
npm run dev-server     ERR

version:1.0.1   master

![QQ图片20210325131841](https://user-images.githubusercontent.com/10111244/112446431-25dad100-8d8b-11eb-85cf-0ca3449f9579.png)

**Comment by cemremengu** [comment]
This is probably related to #13744

**Comment by ouydon** [comment]
I have modified the file  【webpack.config.js】
![image](https://user-images.githubusercontent.com/1456271/112464642-b838a000-8d9e-11eb-945a-3237e2aafdca.png)
but npm run dev-server ERR
![image](https://user-images.githubusercontent.com/1456271/112465030-3137f780-8d9f-11eb-8b4f-cf0b2e8321b0.png)
![image](https://user-images.githubusercontent.com/1456271/112465058-3a28c900-8d9f-11eb-8651-7c6980337d6c.png)

windows  10
node        v14.15.0 
superset  master

 thanks ：）

**Comment by cemremengu** [comment]
Not sure about this since I can run fine but since superset does not officially support windows builds, any undefined behavior is possible

**Comment by tlkzzz** [comment]
> Not sure about this since I can run fine but since superset does not officially support windows builds, any undefined behavior is possible

My system version is CentOS, which is the same as windows, My first picture is CentOS
CentOS Linux release 7.2.1511 (Core)
node: v14.5.0
