### ISSUE TITLE
[Idea] Improve user system to better integrate with SSO or different login methods

### ISSUE THREAD

**Issue by juneauwang** [apache/superset#13804]
While integrating Superset and Azure SSO, I find there is an annoying point after integration that: If you were using LDAP and put your SAMAccountName as username in Superset while Azure doesn't provide such thing, you might need to clean all existing users and start user registration from scratch.

It will be better if Superset check both username and emails in ab_user and link the existing account when user is trying to login if one is matched so that superset can better work with different login methods. 

It will be even great so that superset can provide multi-login methods so that user can choose which methods will be suitable. Don't know if flask appbuilder allowing this.

**Comment by sfirke** [comment]
Possibly related: when Superset is configured with Azure OAuth, it populates usernames with long Azure ID strings, not the sAMAccountName which would be much better.  I opened a question about this here: https://stackoverflow.com/questions/73254549/get-proper-usernames-to-populate-on-superset-with-azure-sso-instead-of-id-string

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and seems more like a feature request than a bug. If this is relevant in current versions (currently 3.x) please open a new discussion (rather than Issue) or a PR to address the problem.
