### ISSUE TITLE
[SQL lab]Strange horizontal scrolling on SqlLab table

### ISSUE THREAD

**Issue by michael-s-molina** [apache/superset#13817]
Look at this video:

https://user-images.githubusercontent.com/70410625/112677607-bb886600-8e48-11eb-98fc-1025ef640926.mov

At the beginning of the video, you can see that the last column requires horizontal scrolling but none is available. The user cannot see all the data. This is happening because the horizontal scroll is being applied to the page and not to the table like Explore. When the tabs require more space, then the horizontal scroll appears on the page, but as a result, the buttons disappear to the right.

Probably related with https://github.com/apache/superset/issues/13789

### Expected results

Horizontal scrolling is applicable to the table and not the page. Similar to Explore.

#### How to reproduce the bug

1. Go to SqlLab
2. Select many tables
3. Watch the scroll behavior

@junlincc 

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
Thanks for reporting! 
@AAfghahi @eschutho could we push a fix for this issue? 🙏

**Comment by eschutho** [comment]
Thanks @junlincc, yes, we’ll take a look at this and the other one. @yousoph

**Comment by yousoph** [comment]
@michael-s-molina are you still seeing the issue with not being able to see the last column? I'm still seeing that the save button is getting pushed off to the side when there are a lot of preview tabs open, but can't repro the column getting cut off anymore.

**Comment by michael-s-molina** [comment]
@yousoph The issue with the last column has been resolved on `master`. Only the buttons problem remaining.
