### ISSUE TITLE
Charts with spaces in metric names generate Unexpected Errors

### ISSUE THREAD

**Issue by filippociceri** [apache/superset#13812]
After updating to the latest version of superset (master), several BigNumber charts stop working. Note I am using BigQuery as a datasource.

### Expected results
Charts displayed as in previous versions.

### Actual results
Charts are no longer displayed. An error is shown instead, containing the name of the metric (with spaces). The following error is shown in superset logs when I try to access the chart:
```
superset_1  | INFO:superset.viz:Cache key: 5bcc722ea51102014c910e2e3b8eae85
superset_1  | 'Active users'
superset_1  | Traceback (most recent call last):
superset_1  |   File "/app/superset/views/base.py", line 183, in wraps
superset_1  |     return f(self, *args, **kwargs)
superset_1  |   File "/app/superset/utils/log.py", line 217, in wrapper
superset_1  |     value = f(*args, **kwargs)
superset_1  |   File "/app/superset/utils/cache.py", line 153, in wrapper
superset_1  |     return f(*args, **kwargs)
superset_1  |   File "/app/superset/views/utils.py", line 446, in wrapper
superset_1  |     return f(*args, **kwargs)
superset_1  |   File "/app/superset/views/core.py", line 618, in explore_json
superset_1  |     return self.generate_json(viz_obj, response_type)
superset_1  |   File "/app/superset/views/core.py", line 455, in generate_json
superset_1  |     payload = viz_obj.get_payload()
superset_1  |   File "/app/superset/viz.py", line 518, in get_payload
superset_1  |     payload["data"] = self.get_data(df)
superset_1  |   File "/app/superset/viz.py", line 1255, in get_data
superset_1  |     aggfunc=np.min,  # looking for any (only) value, preserving `None`
superset_1  |   File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 7038, in pivot_table
superset_1  |     observed=observed,
superset_1  |   File "/usr/local/lib/python3.7/site-packages/pandas/core/reshape/pivot.py", line 89, in pivot_table
superset_1  |     raise KeyError(i)
superset_1  | KeyError: 'Active users'
superset_1  | ERROR:superset.views.base:'Active users'
superset_1  | Traceback (most recent call last):
superset_1  |   File "/app/superset/views/base.py", line 183, in wraps
superset_1  |     return f(self, *args, **kwargs)
superset_1  |   File "/app/superset/utils/log.py", line 217, in wrapper
superset_1  |     value = f(*args, **kwargs)
superset_1  |   File "/app/superset/utils/cache.py", line 153, in wrapper
superset_1  |     return f(*args, **kwargs)
superset_1  |   File "/app/superset/views/utils.py", line 446, in wrapper
superset_1  |     return f(*args, **kwargs)
superset_1  |   File "/app/superset/views/core.py", line 618, in explore_json
superset_1  |     return self.generate_json(viz_obj, response_type)
superset_1  |   File "/app/superset/views/core.py", line 455, in generate_json
superset_1  |     payload = viz_obj.get_payload()
superset_1  |   File "/app/superset/viz.py", line 518, in get_payload
superset_1  |     payload["data"] = self.get_data(df)
superset_1  |   File "/app/superset/viz.py", line 1255, in get_data
superset_1  |     aggfunc=np.min,  # looking for any (only) value, preserving `None`
superset_1  |   File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 7038, in pivot_table
superset_1  |     observed=observed,
superset_1  |   File "/usr/local/lib/python3.7/site-packages/pandas/core/reshape/pivot.py", line 89, in pivot_table
superset_1  |     raise KeyError(i)
superset_1  | KeyError: 'Active users'
```

Modifying the metric's name by removing the spaces - `ActiveUsers`, effectively using camel case instead, displays the chart as expected. Inspecting the query, I can see that the label for my metric is mutated in the former case, while it stays the same in the latter.

#### How to reproduce the bug

1. Create a BigNumber chart using a BigQuery table as a datasource
2. Add a metric with a space in the name (for example, `A B`)
3. Click the Run button to generate a preview

### Environment

(please complete the following information):

- superset version: `1.0.0`
- python version: `3.7.9`
- node.js version: `10.24.0`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by filippociceri** [comment]
I forgot to mention that there are a couple of customizations in place, so the stacktrace line numbers may not match.

**Comment by filippociceri** [comment]
I took some more time to analyze this point. I think this is caused by the following lines changed in #13434 

https://github.com/apache/superset/blob/d54cc6d82aa86444dff0eaff072ee9e8e9ea915f/superset/connectors/sqla/models.py#L521-L524

https://github.com/apache/superset/blob/d54cc6d82aa86444dff0eaff072ee9e8e9ea915f/superset/connectors/sqla/models.py#L1097

where the labels_expected seems to be referencing mutated column names instead of the original/actually expected ones.

Was this change intended?

**Comment by villebro** [comment]
@filippociceri please see #14095 for a fix for this

**Comment by filippociceri** [comment]
Hey @villebro, the fix works, thanks!
