### ISSUE TITLE
Big Number viz doesn't allow you to change the time series formatting like you can with the Big Number.

### ISSUE THREAD

**Issue by rbalsick-saatva** [apache/superset#13819]
I can change the Big Number format (e.g. to $) but I can't change the time series date to a different format (e.g. 10/01/2021).

Can someone add this format option to Superset?

**Comment by Alxander64** [comment]
I'm also interested in this, it would be helpful to just display a max(timestamp) as the current date and time. Only time option right now is to show a duration.

This is my first time looking at the Superset codebase so I'm unfamiliar with it. Where would the existing formatting options be found?

**Comment by zhar97** [comment]
It has been almost a year since this issue was raised. Any update?

**Comment by rusackas** [comment]
<img width="774" alt="Pasted_Image_1_11_23__4_22_PM" src="https://user-images.githubusercontent.com/812905/211939362-44923f72-2a21-4e28-a2da-122a51678adc.png">

It's there now!
