### ISSUE TITLE
[Report] Can't send a Email Report for a Pie Chart 

### ISSUE THREAD

**Issue by younsb** [apache/superset#13814]
VERSION : 1.0.1

![image](https://user-images.githubusercontent.com/81430164/112659648-deb91280-8e54-11eb-8832-8369083d6e40.png)

I try to schedule an attachement with RAW DATA  report using  "Manage Email Reports for Charts" for different type of visualizations.

- Pie chart :-1:  didn't work (see traceback 1)
- Word Cloud :-1: didn't work (see traceback 2)
- table :+1:  worked
- Big Number :+1: worked 

I tried also for Pie chart an attachement with "Email Format: vizualisation" and didnt work ; I get traceback 3 

### Expected results

4 mails received with raw data for every chart 

### Actual results

2 mails received with table raw data  and Big number raw data 

##### Picture 1

![image](https://user-images.githubusercontent.com/81430164/112662984-9865b280-8e58-11eb-957c-ad65df11a7a4.png)

##### Picture 2 : traceback 1

![image](https://user-images.githubusercontent.com/81430164/112663204-d4007c80-8e58-11eb-9a79-082d48ed9afa.png)

#####  Traceback 2

INFO:werkzeug:127.0.0.1 - - [25/Mar/2021 17:36:23] "GET /sliceemailscheduleview/list/ HTTP/1.1" 200 -
infos viz pie
INFO:superset.views.utils:infos viz pie
'pie'
Traceback (most recent call last):
  File "/home/ybarie/Documents/superset1.0/superset1-dev/lib/python3.7/site-packages/superset/views/base.py", line 181, in wraps
    return f(self, *args, **kwargs)
  File "/home/ybarie/Documents/superset1.0/superset1-dev/lib/python3.7/site-packages/superset/utils/log.py", line 164, in wrapper
    value = f(*args, **kwargs)
  File "/home/ybarie/Documents/superset1.0/superset1-dev/lib/python3.7/site-packages/superset/utils/cache.py", line 172, in wrapper
    response = f(*args, **kwargs)
  File "/home/ybarie/Documents/superset1.0/superset1-dev/lib/python3.7/site-packages/superset/views/utils.py", line 451, in wrapper
    check_perms(*args, **kwargs)
  File "/home/ybarie/Documents/superset1.0/superset1-dev/lib/python3.7/site-packages/superset/views/utils.py", line 520, in check_datasource_perms
    force=False,
  File "/home/ybarie/Documents/superset1.0/superset1-dev/lib/python3.7/site-packages/superset/views/utils.py", line 125, in get_viz
    viz_obj = viz.viz_types[viz_type](
KeyError: 'Cloud word'

#####  Traceback 3

![image](https://user-images.githubusercontent.com/81430164/112665327-3bb7c700-8e5b-11eb-862f-63787ebbf648.png)

#### How to reproduce the bug

1. Go to 'Chart Email schedules'
2. Add a pie chart (error for any pie chart) in 'Schedule Email Reports for Charts'
3. check Send Test Email and add a mail
4. error in the logs (traceback 1)

### Environment

- superset version: `1.0.1`
- python version: `Python 3.7.6`
- node.js version: `v14.16.0`

### Additional context

I am using geckodriver. the "Schedule Email Reports for Charts" is working for all charts except the pie chart and word cloud in both cases (Raw data, vizualisation) didn't work

**Comment by younsb** [comment]
@junlincc, can you explain to me why for you it's not a bug ?

**Comment by junlincc** [comment]
hey @younsb sorry i was validating the issue.. Have you tried the new reporting feature that's behind a feature flag? We will not likely to maintain the old one. LMK. 
https://preset.io/blog/2021-01-18-superset-1-0/
https://www.youtube.com/watch?v=p2gpzQcxsXs&t=209s 
https://superset.apache.org/docs/installation/alerts-reports

**Comment by suddjian** [comment]
Closing this, feel free to reopen if the issue persists under the new reporting feature.

**Comment by younsb** [comment]
VERSION : 1.1.0
@junlincc @suddjian 
I just test it in the new feature same problem for this type of charts.
And it's not related to the type of message content (CSV or png). It didn't work for both of them. 

For pie chart (CSV) : 
 
![pie-chart-csv](https://user-images.githubusercontent.com/81430164/116228718-f5090580-a755-11eb-9b7c-1fe37c68ef35.png)

Error in Superset :

![error-superset](https://user-images.githubusercontent.com/81430164/116228837-1669f180-a756-11eb-9d52-445bc83eb794.png)
 
Error in Gui : 

![erorr-gui](https://user-images.githubusercontent.com/81430164/116228915-2f72a280-a756-11eb-80cd-9f05cb61bd4f.png)

Error in Celery : 

![error-schedule](https://user-images.githubusercontent.com/81430164/116229118-66e14f00-a756-11eb-9ccd-7bfa70fdd2a4.png)

For pie chart (png) :

![pie-chart](https://user-images.githubusercontent.com/81430164/116239013-6ea6f080-a762-11eb-82a0-558f6d3e8449.png)

Error in Gui : 

![image](https://user-images.githubusercontent.com/81430164/116238895-461ef680-a762-11eb-8dbf-b4ee64efe931.png)

Error in Celery : 

![image](https://user-images.githubusercontent.com/81430164/116229587-fbe44800-a756-11eb-8727-221949a9e389.png)

**Comment by nadgirsanket** [comment]
@younsb How did you enable PNG and CSV options under Message Content? 

I am using Superset v1.1.0 too. I only see Dashboard and Chart options.

Thanks!

**Comment by younsb** [comment]
@nadgirsanket You have to click on chart option to have PNG and CSV options
