### ISSUE TITLE
[SQL Lab] UnicodeDecodeError when querying blob data and DB has asynchronous query execution enabled

### ISSUE THREAD

**Issue by cabo40** [apache/superset#13829]
When a DB has asynchronous query execution enabled the json dumper doesn't honor the default parser because `encoding` is not `None`
https://github.com/apache/superset/blob/18ff4841862cd53c92614805ae6db188e3379850/superset/views/core.py#L2214
Steps to reproduce on vanilla installation:
1. Set sample DB to async execution in Data / Databases
2. Query in SQL Lab the following: 
```sql
select decode('DEADBEEF', 'hex');
```
Result:
![image](https://user-images.githubusercontent.com/1605852/112706151-efbf4f00-8e67-11eb-9451-0bdee3ddc096.png)

**Comment by junlincc** [comment]
cc @robdiciuccio
