### ISSUE TITLE
[menu]combine upload CSV/Excel in menu

### ISSUE THREAD

**Issue by junlincc** [apache/superset#13834]
<img width="592" alt="Screen Shot 2021-03-26 at 11 07 10 PM" src="https://user-images.githubusercontent.com/67837651/112711751-08d7f800-8e88-11eb-9f46-a5623529b3ea.png">
"Current Menu - "Upload Csv" and "Upload Excel" looks clunky. I never used them before - but think there are identical format. Probably those one possible to merge into one form  "Upload CSV/Excel" and specify format inside the form by radio button. "

cc @steejay

**Comment by Steejay** [comment]
thanks @junlincc. we'll take a look into this. there are some differences between both forms but I agree that they could be consolidated better.

**Comment by villebro** [comment]
@junlincc I agree, having a single upload form that dynamically updates based on the selected type would be optimal.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for a year and a half, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
