### ISSUE TITLE
[explore] Certified metric icons are various sizes on Metric control

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#13831]
## Screenshot

<img width="362" alt="Screen Shot 2021-03-26 at 2 05 55 PM" src="https://user-images.githubusercontent.com/61221714/112709504-7891b700-8e77-11eb-984a-3458332ea4ca.png">

## Description
The 1st metric on the metric control has the certification icon as a little dot - circled in red on the image. The other metric later in the list has a normal sized icon.

Both icons should be the same size (the 1st icon should be same size as the later metric)

**Comment by zuzana-vej** [comment]
Similar issue in the past (but on search left tab) https://github.com/apache/superset/pull/12690

**Comment by michael-s-molina** [comment]
@junlincc Can you assign this to me? I'm working on it.

**Comment by junlincc** [comment]
Thank you Michael, noted!
