### ISSUE TITLE
[listview]inconsistent filter dropdown component 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#13835]
https://user-images.githubusercontent.com/67837651/112711829-8dc31180-8e88-11eb-81b7-5d434e8f212a.mov

Not sure if the design of listview filter dropdown is intentional.. 1)it's definitely not consistent with other dropdown cosmetic in the product 2)looks pretty broken 3) filterable items should be spaced out..... 

@steejay

**Comment by Steejay** [comment]
@junlincc the designs should be consistent between all crud views. thanks for the recording. What filterable items are you referring to re spacing? The items in the dropdown or the spacing between filters in the bar?

**Comment by junlincc** [comment]
the spacing between filters in the bar @Steejay 🙏 but it's your call! just my suggestion :)
