### ISSUE TITLE
Support custom SQL filters on calculated columns

### ISSUE THREAD

**Issue by etr2460** [apache/superset#13848]
**Is your feature request related to a problem? Please describe.**
In Explore you can create custom SQL filters to apply to the query. However, referencing calculated columns from this filter doesn't work.

**Describe the solution you'd like**
Support filtering by calculated columns by mapping the calculated column name to it's SQL query before running the query

**Describe alternatives you've considered**
Alternatively, if supporting this isn't possible:
- add warnings that you can’t use derived column names in the Custom SQL
- stop it from auto-populating derived fields when switching from Simple to Custom SQL

cc @junlincc

**Comment by ShaliniIruvuru** [comment]
Working fine in  latest release of superset version 2.1.0 .From the referencing calculated columns which we created ,those columns are working.

Screenshots:-
![image](https://user-images.githubusercontent.com/115684419/227119677-6465e28b-527b-464f-8a49-22dc4f0cc58a.png)
![image](https://user-images.githubusercontent.com/115684419/227119710-a41e1d21-1819-48d9-b8e5-dfc3074b8ad9.png)

**Comment by rusackas** [comment]
Sounds like this is likely resolve by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
