### ISSUE TITLE
[table]0 values instead on Null in table charts

### ISSUE THREAD

**Issue by Sipondo** [apache/superset#13847]
Upgraded Superset main branch, but now my Date columns in tables show the unix epoch time for Null instead of just N/A.
Values are correct (N/A) in the SQL Editor.

### Expected results

Null values

### Actual results

0 values (Unix epoch time 1970-01-01)

#### Screenshots

![image](https://user-images.githubusercontent.com/6222286/112863545-41a9e400-90b7-11eb-97c5-35508a7647d8.png)

#### How to reproduce the bug

1. Have a dataset with a date field that can be null
2. Make a table chart with the dataset
3. See issue

### Environment

(please complete the following information):

- superset version: Current main branch (as of writing)
- python version: 3.8

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x ] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Discussed on Slack: https://apache-superset.slack.com/archives/C016B3LG5B4/p1617025314056300

**Comment by junlincc** [comment]
@Sipondo thanks for reporting, when was the last time it works/displays properly?

**Comment by Sipondo** [comment]
We pulled the most recent master branch last Friday. Our deployment before that was from the end of January.

**Comment by kamalkeshavani-aiinside** [comment]
I can see this fixed in master.
@junlincc I am not sure which PR fixed this, but if you can find then please tag it for 1.4. Thanks!

**Comment by junlincc** [comment]
https://github.com/apache-superset/superset-ui/pull/1315 ?

**Comment by rusackas** [comment]
I believe this should have been closed as fixed ages ago. Thanks folks!
