### ISSUE TITLE
Adding calculated field to dataset : changing this dataset is forbidden

### ISSUE THREAD

**Issue by helo-ch** [apache/superset#13846]
SuperSet users want to add calculated fields to their datasets, but they run into an error :
`Changing this dataset is forbidden`

Users have the following roles :
* Gamma
* tables_modify : [can tables on Superset, can save on Datasource, can get on Datasource, can datasources on Superset, menu access on Tables, can fetch datasource metadata on Superset, can read on Dataset, can write on Dataset]
* DB_ACCESS : [database access on [their TimeScale DB], datasource access on [the dataset they want to edit]]
* sql_lab

Is there a missing permission for them to be able to edit their own datasets? They have read and write permission on it, and are the ones creating the datasets in the first place.

I looked into the database properties but could not find any setting there either. Moreover with admin role I am able to edit datasets so I guess what's missing here is a user role, I just can't find which one.

### Environment

- superset version: `1.0.1`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rosemarie-chiu** [comment]
Is this still an issue? I don't reproduce this bug.
