### ISSUE TITLE
NULL, NULL does not get shown when grouping by a column in line chart

### ISSUE THREAD

**Issue by bkyryliuk** [apache/superset#13850]
Opening a clone of the https://github.com/apache/superset/issues/2110 per @junlincc  request.
More context can be found in that issue.

### Expected results

null, null values are shown on the line chart rather than omitted

### Actual results

![image](https://user-images.githubusercontent.com/5727938/112874335-ac3b2f80-9077-11eb-908d-d55e65ff6f07.png)

#### How to reproduce the bug

1. create table
```
create table null_bug_report as 
SELECT substr(strftime('%Y', year),0,4) || "0" as decade, country_name, "dim" as dim, count(*) as count_per_year from wb_health_population where country_name in ('Ukraine', 'Germany') group by 1,2 
union select "1960", NULL, NULL, 100
```

2. add it as a datasource
3. define datetime virtual column

![image](https://user-images.githubusercontent.com/5727938/112874449-d1c83900-9077-11eb-9621-70ba66f172de.png)
4. create line chart over time with no datetime filter that is grouped by `country_name` and `dim`
5. 
![image](https://user-images.githubusercontent.com/5727938/112874716-1eac0f80-9078-11eb-908d-c262801da8d9.png)
6. notice that null, null value is not shown on the line chart

### Environment

latest master as of March 29 2021

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@villebro @zhaoyongjie let's make sure we address this in new echarts line(when we break down the new time series chart)

**Comment by rusackas** [comment]
Closing as stale, assuming all is well with the newer chart, as we work to deprecate the old one.
