### ISSUE TITLE
I'd love search in Superset to be fuzzier

### ISSUE THREAD

**Issue by srinify** [apache/superset#13857]
**Is your feature request related to a problem? Please describe.**
I wanted to search for pie charts and I typed in "pie " (note the extra space). This returned 0 results. "Pie Ch" also returned 0 results. If I shorten back to just "pie" then it worked fine.

<img width="1493" alt="Screen Shot 2021-03-29 at 5 11 16 PM" src="https://user-images.githubusercontent.com/801507/112900694-cf82d080-90b1-11eb-889e-b2ba579360c0.png">

<img width="1495" alt="Screen Shot 2021-03-29 at 5 10 46 PM" src="https://user-images.githubusercontent.com/801507/112900699-d0b3fd80-90b1-11eb-9919-cd1d8c24e331.png">

**Describe the solution you'd like**
I wish search was fuzzier.

**Comment by junlincc** [comment]
I have a similar request for the south data table in Explore. There's currently no consistency in all the filter bars in the product. but we should use the left data pane search as the standard, with relevancy ranking, debounce and search all objects etc.
