### ISSUE TITLE
[dashboard] No left padding in dashboard

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#13863]
#### Screenshots

- There is no left padding in dashboard, so the content is not center aligned. 
- Open in edit mode, there is no controls to drag the whole row:
 

<img width="1136" alt="Screen Shot 2021-03-29 at 6 37 49 PM" src="https://user-images.githubusercontent.com/27990562/112920714-5d64b880-90be-11eb-95f4-a10e5b451c61.png">
<img width="1137" alt="Screen Shot 2021-03-29 at 6 38 18 PM" src="https://user-images.githubusercontent.com/27990562/112920735-6786b700-90be-11eb-81fd-d36e44ea6530.png">

#### How to reproduce the bug

1. Go to any dashboard
2. Edit dashboard

### Environment

latest master

cc @junlincc

**Comment by junlincc** [comment]
this is bad... will push a fix asap

**Comment by junlincc** [comment]
https://github.com/apache/superset/pull/13723 
looked at relevant changes in last few days, probably this is the one? @villebro lmk~

**Comment by rusackas** [comment]
PR open - #13884
