### ISSUE TITLE
Helm chart is configured to run as root without ability to override

### ISSUE THREAD

**Issue by megakoresh** [apache/superset#13869]
Helm is [configured](https://github.com/apache/superset/blob/9d0bb3a3ba38c2289d77e87dfe572c57c51ef7c7/helm/superset/templates/deployment.yaml#L53) to run containers as root so that it can [install packages](https://github.com/apache/superset/blob/9d0bb3a3ba38c2289d77e87dfe572c57c51ef7c7/helm/superset/templates/_helpers.tpl#L52). This is against security best practices and to top it all off, the chart does not allow editing this setting, and neither can the bootstrap be edited, so it doesn't crash when running as non-root. This makes the helm chart not suitable for secure production environments.

To fix this, it would be enough to allow editing the `runAsUser` field and the bootstrap script from `values.yaml`. Although in my opinion bad practices like this should not be promoted by the upstream, so it would be preferable if non-root was the default option, with [documentation](https://superset.apache.org/docs/installation/running-on-kubernetes#running-on-kubernetes) reflecting this.

I may have time to fix this later this week, but my schedule is quite tight so if someone has time to do this, please post here so I don't start duplicating someone's work.

**Comment by amitmiran137** [comment]
@craig-rueda  WDYT?

**Comment by craig-rueda** [comment]
Yep, totally agree.

**Comment by megakoresh** [comment]
Ok, working on it
