### ISSUE TITLE
[todo]update apache/superset docs - install steps in dockerhub 

### ISSUE THREAD

**Issue by preetdeepkumar** [apache/superset#13867]
Team,

While following the steps as mentioned in https://hub.docker.com/r/apache/superset -> "Initialize a local Superset Instance", when I opened Superset via http://localhost:8080/login/, after login, I saw a lot of error messages pop up in UI.
![Capture](https://user-images.githubusercontent.com/10060103/112970573-f56cab80-916b-11eb-9a6f-f752d1e9f4a7.PNG)

After few tries when I changed the sequence by running "Step 4 Setup roles" before "Step 3 Load Examples", then everything worked as expected.
![Capture_After](https://user-images.githubusercontent.com/10060103/112970817-3cf33780-916c-11eb-835b-4029128d053f.PNG)

It will be good if you can swap Step 3 and Step 4 so that Load Examples is the last step.

**Comment by junlincc** [comment]
thanks for pointing it out! 

@srinify could we validate the suggestions and update the doc accordingly? thanks!

**Comment by sfirke** [comment]
I can't speak to whether this change is needed or not, but can confirm the Docker Hub instructions have stayed the same as described in original post.

**Comment by rusackas** [comment]
I'm not sure how necessary or actionable this is at this point (I'm tempted to close it as stale, but it's likely still relevant). I think @mistercrunch was trying to figure out how to make edits to this file. I'm assuming we should have this page point to the docs site rather than providing instructions at all.

**Comment by mistercrunch** [comment]
Where's the docker README stored? We should kill it and point to the official docs in there.

**Comment by rusackas** [comment]
@craig-rueda you happen to know how to edit this? I imagine it's buried in DockerHub.

**Comment by craig-rueda** [comment]
Yep, I have access to it. What should the updated content be?

**Comment by mistercrunch** [comment]
@craig-rueda I'd say just point to the right page in the docs, I'd say here -> https://superset.apache.org/docs/installation/docker

**Comment by sfirke** [comment]
Could it say:

> See the Apache Superset project's documentation for guidance on [installing Superset using Docker](https://superset.apache.org/docs/installation/installing-superset-using-docker-compose) and for [details on the various Docker images and tags](https://superset.apache.org/docs/installation/docker/).

That has the link Max suggested as well as a link to our Docker installation guide.

**Comment by rusackas** [comment]
I think we need to spread access to the credentials for this account... I'll see if I can work with @craig-rueda to make that happen.

**Comment by rusackas** [comment]
Dockerhub now just points to the (much more current) documentation. That _should_ effectively solve this. Thanks all!
