### ISSUE TITLE
Can't sync column from source on complex queries

### ISSUE THREAD

**Issue by ValentinC-BR** [apache/superset#13865]
I can't use "sync column from source" on virtual datasets whose query doesn't start with SELECT.

### Expected results

Whatever my query is, I should be able to sync column from source for my virtual datasets.

### Actual results

When my query starts with SELECT, there's no problem.
When my query start with "WITH" statements : 
* I can create a virtual dataset using the "EXPLORE" feature in SQL Lab
* I can't update it and sync columns from source : I get the "ONLY SELECT STATEMENTS ARE ALLOWED" error

I'm forced to re-run the query in SQL Lab, and save is over the previous virtual dataset 

What's more, contrary to the previous version of superset (0.x.x), the time columns are not detected, but this seems to be a different issue.

#### Screenshots

![image](https://user-images.githubusercontent.com/79460908/112947293-e7506800-9136-11eb-87ac-900a30d68fc4.png)

#### How to reproduce the bug

1. Run a query in SQL Lab starting with a "WITH" statement
2. Click on Explore and create a virtual dataset
3. Go to dataset, update the query (you can add/remove/modify a column, anything works, even a mere filter)
4. Save
5. Click on 'Sync Columns from source' (it should get your new column list)
6. See error

### Environment

(please complete the following information):

- superset version: 1.0.1
- python version: 3.7.9
- node.js version: doesn't apply, I run on Kubernetes, using gunicorn as server
- source : Athena

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Nothing to report

**Comment by betodealmeida** [comment]
Taking a look.

**Comment by betodealmeida** [comment]
I tested with a simple query and it worked:

```sql
WITH RAW AS (SELECT name, color FROM bart_lines)
SELECT * FROM RAW
```

We've had problems in the past with our SQL parser not being able to identify CTEs as `SELECT` statements correctly, and I fixed a few of them lately:

- https://github.com/apache/superset/pull/16769
- https://github.com/apache/superset/pull/17654
- https://github.com/apache/superset/pull/17329

I suspect the original SQL that triggered this problem fell into this category.

@ValentinC-BR I'm going to close the ticket, but feel free to reopen if you can still repro it — if I have the SQL of the virtual dataset I can fix it.

**Comment by ValentinC-BR** [comment]
My bad, it didn't come from queries that don't start with SELECT, but with queries with comments.
.
It seems that the comments (-- MY COMMENT HERE) are not well supported.

**Comment by ValentinC-BR** [comment]
The title of this issue could be changed, as it is not related to complex queries.

**Comment by betodealmeida** [comment]
No worries, sorry for the delay, this ticket fell under my radar.

If the problem was comments then https://github.com/apache/superset/pull/16769 should fix it. :)
