### ISSUE TITLE
NotImplementedError for Opendistro

### ISSUE THREAD

**Issue by Jimmy-Newtron** [apache/superset#13866]
I want to create a chart **Big Number with Trendline** that must use a custom datetime column (different from @timestamp) field from an opendistro dataset

![image](https://user-images.githubusercontent.com/24460646/112965075-369f9400-9149-11eb-8aaf-cdaa92e2fc8d.png)
![image](https://user-images.githubusercontent.com/24460646/112964554-ba0cb580-9148-11eb-99f9-5fcbf288d558.png)
![image](https://user-images.githubusercontent.com/24460646/112965112-4028fc00-9149-11eb-9b24-d281b3cf14f8.png)

Using the **timestamp** field it gets the error while with the **firstEventEpochSession** it works correctly
![image](https://user-images.githubusercontent.com/24460646/112965016-28517800-9149-11eb-91d5-92267f513bc1.png)

### Expected results

Chart is able to render the data

### Actual results & screenshots

![image](https://user-images.githubusercontent.com/24460646/112962496-ba0bb600-9146-11eb-9fe5-5afa3ea444fb.png)

#### How to reproduce the bug

1. Create a dataset from an opendistro index (with a custom datetime field)
2. Create a chart of type **Big Number with Trendline**
3. Select the custom datetime field into the time section
4. Run the query & see error

### Environment

- helm chart (latest)

- superset version: `superset version`
```
root@superset-67bcb48445-hgvw9:/app# superset version
Loaded your LOCAL configuration at [/app/pythonpath/superset_config.py]
logging was configured successfully
INFO:superset.utils.logging_configurator:logging was configured successfully
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Superset 0.999.0dev
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

- python version: `python --version`
```
root@superset-67bcb48445-hgvw9:/app# python
Python 3.7.9 (default, Feb  9 2021, 08:33:04) 
[GCC 8.3.0] on linux
```

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset source code

https://github.com/apache/superset/blob/9fa52b50edaa2e42b7d064139ddb41d329aa1344/superset/db_engine_specs/base.py#L502

https://github.com/apache/superset/blob/9fa52b50edaa2e42b7d064139ddb41d329aa1344/superset/db_engine_specs/elasticsearch.py#L67

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
