### ISSUE TITLE
why user npm 7.5.4

### ISSUE THREAD

**Issue by oushu1jinliujie1** [apache/superset#13870]
according this link https://nodejs.org/zh-cn/download/releases/

Node.js 14.15.5 | Fermium | 2021-02-09 | 8.4.371.19 | 6.14.11
-- | -- | -- | -- | -- |

nodejs 14.15.5 is bounding to npm 6.14.11 , it is not 7.5.4

@ktmud

**Comment by ktmud** [comment]
Because it's the default version when you run `npm install npm`.

npm 7 has been [promoted](https://github.blog/2021-02-02-npm-7-is-now-generally-available/) to the default `latest` version and is considered stable.
