### ISSUE TITLE
npm run build Failed

### ISSUE THREAD

**Issue by oushu1jinliujie1** [apache/superset#13880]
```
± |tag:1.1.0rc1 U:2 ✗| → node --version
v14.15.5
± |tag:1.1.0rc1 U:2 ✗| → npm --version
6.14.11
```
OS: MAC
after run command ```npm ci```  i run command  ```npm run build``` but there is some error:
```
ERROR in ./node_modules/@superset-ui/chart-controls/esm/constants.js
Module not found: Error: Can't resolve '@superset-ui/core/src/query/buildQueryObject' in '/Users/jinliujie/go/src/github.com/oushu-io/superset/superset-frontend/node_modules/@superset-ui/chart-controls/esm'

ERROR in ./node_modules/@superset-ui/chart-controls/esm/shared-controls/components/ColumnConfigControl/constants.js
Module not found: Error: Can't resolve 'react-icons/fa' in '/Users/jinliujie/go/src/github.com/oushu-io/superset/superset-frontend/node_modules/@superset-ui/chart-controls/esm/shared-controls/components/ColumnConfigControl'

ERROR in ./node_modules/@superset-ui/plugin-chart-table/esm/TableChart.js
Module not found: Error: Can't resolve 'react-icons/fa' in '/Users/jinliujie/go/src/github.com/oushu-io/superset/superset-frontend/node_modules/@superset-ui/plugin-chart-table/esm'
```

**Comment by junlincc** [comment]
please fill out one of the issue template with clear step to reproduce.

**Comment by tlkzzz** [comment]
> ```
> ± |tag:1.1.0rc1 U:2 ✗| → node --version
> v14.15.5
> ± |tag:1.1.0rc1 U:2 ✗| → npm --version
> 6.14.11
> ```
> 
> 操作系统：
> 运行命令后`npm ci` 我运行命令， `npm run build`但有一些错误：
> 
> ```
> ERROR in ./node_modules/@superset-ui/chart-controls/esm/constants.js
> Module not found: Error: Can't resolve '@superset-ui/core/src/query/buildQueryObject' in '/Users/jinliujie/go/src/github.com/oushu-io/superset/superset-frontend/node_modules/@superset-ui/chart-controls/esm'
> 
> ERROR in ./node_modules/@superset-ui/chart-controls/esm/shared-controls/components/ColumnConfigControl/constants.js
> Module not found: Error: Can't resolve 'react-icons/fa' in '/Users/jinliujie/go/src/github.com/oushu-io/superset/superset-frontend/node_modules/@superset-ui/chart-controls/esm/shared-controls/components/ColumnConfigControl'
> 
> ERROR in ./node_modules/@superset-ui/plugin-chart-table/esm/TableChart.js
> Module not found: Error: Can't resolve 'react-icons/fa' in '/Users/jinliujie/go/src/github.com/oushu-io/superset/superset-frontend/node_modules/@superset-ui/plugin-chart-table/esm'
> ```

请问你解决了这个问题没 ? 我也是跟你同样的问题

**Comment by tlkzzz** [comment]
> 请使用清晰的步骤填写问题模板之一，以进行复制。

操作系统：
运行命令后npm ci我运行命令，npm run build但有一些错误：

ERROR in ./node_modules/@superset-ui/chart-controls/esm/constants.js
Module not found: Error: Can't resolve '@superset-ui/core/src/query/buildQueryObject' in '/Users/jinliujie/go/src/github.com/oushu-io/superset/superset-frontend/node_modules/@superset-ui/chart-controls/esm'

ERROR in ./node_modules/@superset-ui/chart-controls/esm/shared-controls/components/ColumnConfigControl/constants.js
Module not found: Error: Can't resolve 'react-icons/fa' in '/Users/jinliujie/go/src/github.com/oushu-io/superset/superset-frontend/node_modules/@superset-ui/chart-controls/esm/shared-controls/components/ColumnConfigControl'

ERROR in ./node_modules/@superset-ui/plugin-chart-table/esm/TableChart.js
Module not found: Error: Can't resolve 'react-icons/fa' in '/Users/jinliujie/go/src/github.com/oushu-io/superset/sup

最新master分支 在linux环境中直接编译前端项目就会报这个问题,希望能帮助解决一下
