### ISSUE TITLE
[SQL Lab] Resizing browser window cuts off result without adding scroller

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#13881]
## Screenshot

<img width="441" alt="Screen Shot 2021-03-30 at 9 09 10 PM" src="https://user-images.githubusercontent.com/61221714/113089315-43010c80-919c-11eb-8ded-5d07eac3da36.png">

![result-cropped](https://user-images.githubusercontent.com/61221714/113089255-2369e400-919c-11eb-8d82-3becc4626a5e.gif)

## Description

At the bottom of the SQL Lab result section, you can see there is one more record which isn't visible, and user has no ability to scroll to see it since there is no scroll bar on the side.

How to repro this:
1. run query in SQL Lab
2. resize Chrome window
3. see the issue

**Comment by junlincc** [comment]
@eschutho 🙏

**Comment by zuzana-vej** [comment]
Different issue but also related to scroll bars in SQL Lab query result area: https://github.com/apache/superset/issues/14455

**Comment by rusackas** [comment]
Fixed by https://github.com/apache/superset/pull/14490 - @zuzana-vej can you confirm?

**Comment by Animesh384** [comment]
# - - - - - - []()_****_@_****_

**Comment by eschutho** [comment]
@yousoph should we take this or @amitmiran137 are you working on it?

**Comment by amitmiran137** [comment]
We tried reproducing unsuccessfully

**Comment by zuzana-vej** [comment]
Yes, seems fixed now
