### ISSUE TITLE
[listview] not able to show properly after removing search term

### ISSUE THREAD

**Issue by rosemarie-chiu** [apache/superset#13902]
### Repo steps:
1. Go to Dashboards list view
2. Enter search term (that has zero result) and hit search
3. Instead of clicking X to remove the search term, delete string with delete button

### Expected results
Dashboard list should show again as if no search term was entered

### Actual results
Stuck on empty dashboards list. The only way out is go to other page then come back or refresh

https://user-images.githubusercontent.com/52086618/113227553-ca578a00-9247-11eb-98bd-96baf2188366.mov

**Comment by junlincc** [comment]
Thank you for filing the first issue 🙏 @rosemarie-chiu 
I believe it never worked as expected. 😅 tagged `good first issue `
