### ISSUE TITLE
[SQL Lab] Expand/Collapse Arrow is not working

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#13903]
SQL Lab - Expand/Collapse arrow is not working in left sidebar

#### How to reproduce the bug

1. Select a table from SQL Lab
2.Click expand/collapse arrow

### Expected results

On expand/collapse: should show/hide table columns

### Actual results

 Expand/Collapse arrow is not doing anything, user need to click on table name to show/hide table columns

<img width="1622" alt="Screen Shot 2021-03-31 at 4 49 22 PM" src="https://user-images.githubusercontent.com/81597121/113237806-6095ab00-925c-11eb-9039-7b6ec1d884cc.png">

### Environment

superset version:  with (Preset Cloud Beta 3/31/2021 - Test on Development)

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

 

- [x]  I have reproduced the issue with at least the latest released version of superset.
- [x]  I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
thank you for filing your first issue! @jinghua-qa 🙏
to whomever is gonna tackle this `good first issue`, please check all area listed in 
https://github.com/apache/superset/pull/12920

cc @amitmiran137

**Comment by mk-94** [comment]
Hi, i am new in this project and also in python. But i would like to solve it. :)

**Comment by suddjian** [comment]
fixed
