### ISSUE TITLE
Fetch dashboard not happening properly with different type of login 

### ISSUE THREAD

**Issue by madhamanchiharsha** [apache/superset#13907]
1. login user who have admin rights in browser and fetch multiple dashboard's.
2. now login same user in postman with (bearer token type authentication) and now try to call same api for multiple dashboards. 

### Expected results
both web and postman should fetch same data or same number of dashboards.

### Actual results
in web all dashboards are fetched properly. whereas in postman only world bank data dashboard is fetched.

### Environment

- superset version: `1.0`
- python version: `python 3.8`

**Comment by dpgaspar** [comment]
@madhamanchiharsha 

Can you add more details, your getting the JWT token on `api/v1/security/login` first? with provider `db`?

**Comment by madhamanchiharsha** [comment]
Hi @dpgaspar 

i am using postman and also there issue with cookie when i copy cookie from browser it is working fine, but i want to automate it in programming language but due to this cookie copy we  are blocked can we have work around for this ?

**Comment by hitzelc** [comment]
I am having something similar happen -- though the CSRF token appears to be respected within my requests session, the Authorization header seems to fail to set the User (all my API requests show up in Security -> Action Log as User = "None"). More info is available here: #15460

**Comment by dobleme** [comment]
Hi, we are having the exact same problem. 

It was all working well with the admin user and auth type provider `db`. But once we replaced the auth type with `ldap` and remove the default admin user and begin to use LDAP users the auth token begin to doesn't work at all.

Now we are forced to use puppeteer to get the session logged cookie and do the API requests with a session cookie.

### Environment
We have superset installed in a  docker-compose way. And we are pinned `master` branch `commit #2e11b05d73992037e7d905e4e5a4f9ea3ecffa5c`

**Comment by vladoklimo** [comment]
can just confirm ... still pending in 1.5.2

**Comment by rusackas** [comment]
Closing since this thread hasn't had any activity in over a year. If this is still an issue in 2.0.x, we can re-open or open a new issue with updated context.

**Comment by zachoooo** [comment]
I'm still having issues with this on the latest version
