### ISSUE TITLE
Junior Trying to upload CSV files 

### ISSUE THREAD

**Issue by CharlotteBIjunior** [apache/superset#13910]
Hi,
First of all, I'm french, so sorry if I make mistake.
Within the scope of my internship, I have to learn Apache Superset. I'm on  windows so I use "Ubuntu" to access to Apache Superset. When I want to connect my CSV, this message appears : "ERROR: No database is allowed for your csv upload"
When I click to the tab "database" to modify the right and click on "Extra"> Authorize upload of data, I have another message : "An error occurred when searching for databases: "sqlalchemy_uri":["The SQLite database cannot be used as a data source for security reasons."]"
I'm junior in code and I don't know what to do. Can you help me please ?

The tuto I've followed : https://medium.com/@vishalsingh_86781/apache-superset-installation-in-windows-492cf85535a7

### Expected results 
Connect my CSV

![ERROR CSV](https://user-images.githubusercontent.com/81742358/113264897-ca9d6700-92d3-11eb-8d3e-8f3206c4157a.png)
![ERROR MODIF DATABASE](https://user-images.githubusercontent.com/81742358/113264900-cb35fd80-92d3-11eb-81e9-acf9cc4e0432.png)

**Comment by junlincc** [comment]
https://www.youtube.com/watch?v=G7kVeONipsQ

@CharlotteBIjunior This will help, LMK!
