### ISSUE TITLE
BUG: Filterbox, when "allow multiple selections" AND "required" are enabled, then "required" doesn't work

### ISSUE THREAD

**Issue by VladislavJansky** [apache/superset#13913]
As the title explains:

when "allow multiple selections" AND "required" are enabled in the filter box settings (filter configuration), then "required" doesn't work.

**Comment by amitmiran137** [comment]
FilterBox is deprecated and you should start evaluating DASHBOARD_NATIVE_FILTERS by toggling the ff, it is close to maturity and will be released in the 1.2 version 

If you start providing feedback about missing abilities in the native filters it is more likely you'll get a solution to your requests

**Comment by VladislavJansky** [comment]
Thank you for your reply.
Are there any other handy charts hidden in the dark realm of the config file?

Kifflom brother.

**Comment by suddjian** [comment]
There are lots of cool new feature flags, but none to my knowledge that enable new charts. See https://github.com/apache/superset/blob/master/RESOURCES/FEATURE_FLAGS.md
