### ISSUE TITLE
[Alert]Increase the resolution of alert email screenshot 

### ISSUE THREAD

**Issue by fancyfreeman** [apache/superset#13912]
## Description
The screenshot in the alert email  is very fuzzy. The size of the screenshot image is only 800*600, can I make it clear？

**Comment by junlincc** [comment]
@fancyfreeman my understanding is you wanna push a PR to make the enhancement 😀 YES!

**Comment by fancyfreeman** [comment]
I'm sorry I didn't make it clear. I'm not an experienced Python programmer. I found a temporary solution. Modify the file located in site-package/superset/utils/screenshots.py
https://github.com/apache/superset/blob/956f276e70cd167cd62f6a65585dd88830821d0c/superset/utils/screenshots.py#L206
Change the WindowSize to a larger size, maybe （3200,2400） is OK .

**Comment by zuzana-vej** [comment]
merged this request into this list: https://github.com/apache/superset/issues/13954
