### ISSUE TITLE
[chart]Big number display tooltip with incorrect time granularity in dashboard

### ISSUE THREAD

**Issue by kristw** [apache/superset#13924]
## Expected results

A big number chart is added to a dashboard with "time grain" override. 
The tooltip of the big number chart in the dashboard should show the data point with respect to the selected "time grain" in dashboard.
For example,
* When select `week`, the tooltip should show `start date -- end date`, e.g. 2021-04-19 -- 2021-04-23.
* When select `day`, the tooltip should show `date`, e.g. 2021-04-19.

## Actual results

When looking at the chart on explore page, it works correctly.

![Pasted_Image_4_1_21__4_46_PM](https://user-images.githubusercontent.com/1659771/113365017-d3109480-9309-11eb-825c-10e6d3feef07.png)

However, the same chart in the dashboard behave unexpectedly.
* When select `week`, the tooltip show `month`, e.g. Mar 2020
* When select `day`, the tooltip shows `month`, e.g. Mar 2020.

![Pasted_Image_4_1_21__4_44_PM](https://user-images.githubusercontent.com/1659771/113364968-bbd1a700-9309-11eb-9159-7d6ff7b905e5.png)

#### How to reproduce the bug

1. Create a big number chart.
2. Put it in a dashboard with time grain override.
3. Set time grain.
4. Check tooltip.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Only the first chart's tooltip is wrong, all the other charts in the same dashboard are correct.

**Comment by kristw** [comment]
I inspected the react component with chrome debugger and the first chart received "P1M" while the second chart received "P1W".

![Pasted_Image_4_1_21__4_53_PM](https://user-images.githubusercontent.com/1659771/113365356-d7897d00-930a-11eb-94b3-6a12af4c745e.png)

**Comment by junlincc** [comment]
@kristw thanks for the details~ are you planning to fix it 😅

cc @EBoisseauSierra

**Comment by villebro** [comment]
I was able to repro, and noticed it affects both legacy and V1 charts. Here the weekly time grain should also be showing up on the table time col (which it does in Explore):
![image](https://user-images.githubusercontent.com/33317356/117781102-f0aa1580-b248-11eb-966f-eca0ff63fddb.png)
