### ISSUE TITLE
Unnecessary horizontal scrollbar in filter

### ISSUE THREAD

**Issue by kristw** [apache/superset#13925]
There is an unnecessary horizontal scrollbar in the filter in a superset dashboard

### Expected results

No scrollbar

### Actual results

visible horizontal scrollbar when it is not necessary.

#### Screenshots

![Pasted_Image_4_1_21__5_01_PM](https://user-images.githubusercontent.com/1659771/113365746-fb998e00-930b-11eb-8848-29d2efbefcdf.png)

#### How to reproduce the bug

1. Create dashboard
2. Create wide filterbox.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by suddjian** [comment]
Filter box is deprecated in favor of native filters, so this will likely not be fixed.
