### ISSUE TITLE
[Design Proposal] Add Database Improvements

### ISSUE THREAD

**Issue by Steejay** [apache/superset#13922]
![Frame 284 (1)](https://user-images.githubusercontent.com/60786102/113363940-246b5480-9307-11eb-9ba1-e8213e4c0652.jpg)
_Dynamic form option (Default)_

![Frame 246](https://user-images.githubusercontent.com/60786102/113364112-888e1880-9307-11eb-919f-3c03679b59e4.jpg)
_SQLAlchemy URI option_

This mock introduces a UX update to the add database flow. The following updates have been introduced:

1. Users can select a database from a grid/list of available databases (installed db drivers)
2. A dynamic form will appear displaying all of the required fields for the specific database selected. The SQLAlchemy URI path is still available. The user may choose to connect a db using either the dynamic form _or_ the SQLAlchemy URI.
3. Once the user successfully completes the required fields and connects the db, they have the option to adjust any additional/optional fields before completing the process.

The motivation for this design includes some of the following:

1. There is no way a user knows what databases are currently supported when adding a new database until they try to connect and get an error that the driver is missing.
2. What fields are required versus optional are vague. Different databases have different requirements. Some may only require a URI while others might require additional information found in other tabs not currently marked w the required asterisk(*).

Here were some of the design goals:

1. Respect the user's time and attention
make the form as short and simple as possible

2. Minimize the number of form inputs
avoid asking other user to do unnecessary work

3. Indicate what is required and what is optional
indicate what fields must be filled out as courtesy and to prevent usability errors

**Comment by rusackas** [comment]
Closing as stale... I do believe the vast majority of this has been tackled anyway.
