### ISSUE TITLE
Issue with logs table - user_id is NULL

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#13935]
Since 03-11 we are seeing user_id in the Superset logs table is NULL. 

This regression was likely caused by https://github.com/apache/superset/pull/13441 since it correlates exactly with our release on 3-10 which included this PR.
This issue is happening when filtering on `action  = 'save_dash'`

Here is a screenshot from the logs table:
![Screen Shot 2021-04-02 at 9 36 31 AM](https://user-images.githubusercontent.com/61221714/113435114-0816f880-9397-11eb-923c-2d9598db7435.png)

The dashboard was in fact edited on the days when it says NULL and the user_id who eddited the dashboard is correctly listed in the dashboards table changed_by_fk

![Screen Shot 2021-04-02 at 9 38 46 AM](https://user-images.githubusercontent.com/61221714/113435267-4c09fd80-9397-11eb-861a-691feed69ee4.png)

**Comment by zuzana-vej** [comment]
Cc: @junlincc @hughhhh @betodealmeida @graceguo-supercat

**Comment by zuzana-vej** [comment]
The user_id NULL only happens for few dashboard events; the save_dash is the one which is a bit problematic because it's the log of who edited the dashboard when. 
These events have NULL user_id (but some not every time)
![Screen Shot 2021-04-05 at 4 47 41 PM](https://user-images.githubusercontent.com/61221714/113639969-429ac280-962f-11eb-82f4-f87ab44b5183.png)

**Comment by eschutho** [comment]
@hughhhh is looking into this
