### ISSUE TITLE
SQL Lab fails to detect select statement when using "WITH RECURSIVE"

### ISSUE THREAD

**Issue by cccs-jc** [apache/superset#13938]
In the sql lab view using the examples postgesql database. Enter the following statements:

```
select n from (values(1)) as t(n)
```
Works fine

```
WITH t(n) AS ( VALUES (1) )
SELECT n FROM t
```
Works fine

```
WITH RECURSIVE t(n) AS (
    VALUES (1)
  UNION ALL
    SELECT n+1 FROM t WHERE n < 100
)
SELECT sum(n) FROM t
```
Returns an error "Only `SELECT` statements are allowed against this database"

Debug the code a bit. The sqlparser can't determine the type of query. sql_parser.py line 133

    def is_select(self) -> bool:
        return self._parsed[0].get_type() == "SELECT"

The type returned is 'UNKNOWN'

Forcing the is_select(self) to return True will make the query execute correctly. So it's is just the check that is failing.

WITH RECURSIVE is very handy in parent/child and graph datasets.

**Comment by cccs-jc** [comment]
The same issues occurs when using `SET @myvariable` statements. Superset fails to recognize it as a select query.

```
SET @slope = (select (sum(xy)-sum(received_on)*sum(count))/(sum(x2)-power(sum(received_on),2)) as slope from
(select received_on, count, received_on * count as xy, power(received_on, 2) as x2
from table1
group by received_on) T1);

SET @offset = (select (sum(count)-sum(received_on)*@slope)/count(*) as offset
from table1);

select date(received_on) as date, @slope*received_on+@offset as trendline from table1;
```

**Comment by mayurnewase** [comment]
So should we add,is_recursive check in `ParsedQuery`,and use it which checking `is_read_only_query` or add PR to `sqlparse` at `https://github.com/andialbrecht/sqlparse/blob/23d29933ddc4272b495d36e0e32d3eaf0c3ef76d/sqlparse/sql.py#L425` to check recursive queries correctly?

**Comment by mayurnewase** [comment]
@betodealmeida
Also on an unrelated note check for `is_select` only checks for first query,but other queries can mutate data is it expected?

**Comment by yousoph** [comment]
This looks to have been fixed!

**Comment by rusackas** [comment]
> The same issues occurs when using `SET @myvariable` statements. Superset fails to recognize it as a select query.
> 
> ```
> SET @slope = (select (sum(xy)-sum(received_on)*sum(count))/(sum(x2)-power(sum(received_on),2)) as slope from
> (select received_on, count, received_on * count as xy, power(received_on, 2) as x2
> from table1
> group by received_on) T1);
> 
> SET @offset = (select (sum(count)-sum(received_on)*@slope)/count(*) as offset
> from table1);
> 
> select date(received_on) as date, @slope*received_on+@offset as trendline from table1;
> ```

@cccs-jc if this is still an issue worth pursuing, would you mind filing an additional ticket?

**Comment by Ashish7129** [comment]
@cccs-jc Can you please suggest the changes you have done in which version? My query is not working "WITH RECURSIVE TableName ***"
