### ISSUE TITLE
User can see dataset without permission in chart creating page

### ISSUE THREAD

**Issue by thangman22** [apache/superset#13944]
### Expected results

Users can access only allow data set. If you see on the screenshot it should available only campaign_30067_posts. In another screenshot, I can change only the dataset that I have permission

### Actual results

User is possible to see no access dataset in create chart menu even it disappear from dataset menu but not in another page

#### Screenshots

![Screen Shot 2564-04-03 at 22 27 54](https://user-images.githubusercontent.com/806893/113483467-bc1a9f80-94cd-11eb-8fb2-0874944dc96b.png)

![Screen Shot 2564-04-03 at 22 42 24](https://user-images.githubusercontent.com/806893/113483509-026ffe80-94ce-11eb-833f-da3ed8d5d7b3.png)

#### How to reproduce the bug

1. Go to 'Charts'
2. Click on ' + Chart'
3. Click 'Choose a dataset'
4. See not allow dataset on dropdown menu

### Environment

- superset version: `1.1.0`
- node.js version: `14`
- Run via docker-compose

**Comment by mayurnewase** [comment]
But if you try to explore, it will show not authorized.

**Comment by mayurnewase** [comment]
@junlincc if this is a valid issue, I can work on it.

**Comment by thangman22** [comment]
@mayurnewase even it is not work in explore by listing the none access dataset is not secure

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.  That said, if it's a security problem, please do NOT open issues, and instead report it to security@superset.apache.org
