### ISSUE TITLE
Lack of Permission "function_name" after upgrade.

### ISSUE THREAD

**Issue by eriendeng** [apache/superset#13947]
well, I upgraded Superset from 0.38 to 1.1 and, when I enter sql-lab I got "An error occurred while fetching function names.
" Error in page message and the backend route `/api/v1/database/1/function_names/` return 401.
I wonder maybe there is some data (permission) missing in the db upgrade command?

**Comment by dpgaspar** [comment]
@eriendeng have you executed `superset init` after the upgrade?

**Comment by eriendeng** [comment]
Thanks to @dpgaspar and it seems ok after I executed `superset init`. But what confused me is that I think `init` is an action for a totally new db and adding perm during upgrade should be done within `upgrade`, and there is not sth detail in the docs(maybe?).

Anyway, Thanks again.

**Comment by nytai** [comment]
@eriendeng there is some docs around this under "upgrading" 

https://superset.apache.org/docs/installation/upgrading-superset#updating-superset-manually

In short, `superset db upgrade` and `superset init` should be run every time code changes (ie, you upgrade). `db upgrade` migrates the database and `init` syncs all the permissions with the default roles.
