### ISSUE TITLE
Filters should be considered handled when jinja templates uses them

### ISSUE THREAD

**Issue by cccs-jc** [apache/superset#13943]
Virtual tables let you use jinja templates to apply your own filtering. For example take this SQL query which finds all the superiors to of an employee. The filter has to be applied inside the WITH RECURSIVE. So it's a great application of jinja templating.

```

WITH RECURSIVE superiors(employee_id, manager_id, full_name, level) AS (
	SELECT
		employee_id,
		manager_id,
		full_name,
    1 as level
	FROM
		employees
	WHERE
		full_name in ( {{ "'" + "', '".join(filter_values('full_name')) + "'" }} )
	UNION ALL
		SELECT
			e.employee_id,
			e.manager_id,
			e.full_name,
      s.level + 1 as level
		FROM
			employees e,
		  superiors s 
		WHERE s.manager_id = e.employee_id
) 
SELECT
	employee_id, manager_id, full_name, level, concat(repeat('....', level), full_name) as description
FROM
	superiors

```

The pie chart shows some statistics about employees. When you click on a given employee cross filtering sends the filter to the table. The jinja template inserts the user to filter inside the WITH RECURSIVE.

![jinja-filter-virtual-table](https://user-images.githubusercontent.com/56140112/113480915-d2404580-9464-11eb-89a6-eee5d15030cf.png)

However the result is incorrect. It only shows the employee and none of the superiors. Looking at the SQL generated explains why.

```

SELECT employee_id AS employee_id,
       manager_id AS manager_id,
       level AS level,
                description AS description,
                full_name AS full_name
FROM
  (WITH RECURSIVE superiors(employee_id, manager_id, full_name, level) AS
     (SELECT employee_id,
             manager_id,
             full_name,
             1 as level
      FROM employees
      WHERE full_name in ('Frank Tucker')
      UNION ALL SELECT e.employee_id,
                       e.manager_id,
                       e.full_name,
                       s.level + 1 as level
      FROM employees e,
           superiors s
      WHERE s.manager_id = e.employee_id ) SELECT employee_id,
                                                  manager_id,
                                                  full_name,
                                                  level,
                                                  concat(repeat('....', level), full_name) as description
   FROM superiors) AS virtual_table
WHERE full_name IN ('Frank Tucker')
LIMIT 10000;
```

Jinja applied the filter correctly however Superset applied the default behaviour which is to apply a filter to the result of the virtual table. I believe that in most cases if a filter is handled by jinja you probably don't want the default behaviour.

This can be worked around by renaming the column `full_name` to something like `display_full_name` and setting the sql expression to be `full_name`. Effectively hiding the column from Superset's default handling.

![trick](https://user-images.githubusercontent.com/56140112/113481043-61e5f400-9465-11eb-970f-dc5e854b24b4.png)
 
And now you get the correct results.

![correct-results](https://user-images.githubusercontent.com/56140112/113481049-6ad6c580-9465-11eb-906a-032ce7ee317d.png)

The query is properly rendered

```

SELECT employee_id AS employee_id,
       manager_id AS manager_id,
       level AS level,
                description AS description,
                full_name AS full_name
FROM
  (WITH RECURSIVE superiors(employee_id, manager_id, full_name, level) AS
     (SELECT employee_id,
             manager_id,
             full_name,
             1 as level
      FROM employees
      WHERE full_name in ('Frank Tucker')
      UNION ALL SELECT e.employee_id,
                       e.manager_id,
                       e.full_name,
                       s.level + 1 as level
      FROM employees e,
           superiors s
      WHERE s.manager_id = e.employee_id ) SELECT employee_id,
                                                  manager_id,
                                                  full_name,
                                                  level,
                                                  concat(repeat('....', level), full_name) as description
   FROM superiors) AS virtual_table
LIMIT 10000;
```

However this is a bit of a hack. You can't use the `full_name` filter in the explore because Superset does not know of it. I would propose that filters handled by jinja be marked as "handled" and not post processed by the sqla/models.py. Or that there be a way to mark them as "handled" from the jinja template.

**Comment by ptheru** [comment]
Hi there!

I have similar scenario like yours @cccs-jc 
my query -
P.S - time_filter() in the below query is a custom function in jinja_context.py
```
{% set dttm = time_filter() %}

WITH User_purchased_within_30_days as (
...) 
SELECT UserID,
       month,                                                                                             
       count_if(Matched = 1)/count(distinct PRODUCT_LANDED) as conversion_per_user
   FROM User_purchased_within_30_days
   WHERE Purchase_date {{ dttm }} #jinja
   GROUP BY UserID,
            month
   HAVING count_if(Matched = 1) > 0
   ORDER BY UserID,
            month
```
            
The jinja is applied correctly in the query generated by superset inside the explore view -

```
SELECT "MONTH" AS "MONTH"
       , CASE
           WHEN COUNT(DISTINCT USERID) = 0 THEN 0
           ELSE SUM(CONVERSION_PER_USER)/COUNT(DISTINCT USERID)
       END AS "Rate"
FROM
(WITH User_purchased_within_30_days as (
...) 
select UserID,
       month,                                                                                             
       count_if(Matched = 1)/count(distinct PRODUCT_LANDED) as conversion_per_user
   from User_purchased_within_30_days
   where Purchase_date >= '2021-04-02'
     AND Purchase_date < '2021-04-09'
   group by UserID,
            month
   having count_if(Matched = 1) > 0
   order by userid,
            month) AS virtual_table
```

In the dashboard view, the filter values do not pass through the chart. I get an incompatible filter warning.
![image](https://user-images.githubusercontent.com/47907051/114221410-eab3d280-9932-11eb-827f-dd453c9fe08d.png)

I tried adding a calculated column as I do not want my query to be split by date. I just want it to be filtered by date.
![image](https://user-images.githubusercontent.com/47907051/114221565-1636bd00-9933-11eb-81fb-6ad7e8228b9a.png)

Generated SQL query -

```
SELECT "MONTH" AS "MONTH"
       , CASE
           WHEN COUNT(DISTINCT USERID) = 0 THEN 0
           ELSE SUM(CONVERSION_PER_USER)/COUNT(DISTINCT USERID)
       END AS "Rate"
FROM
(WITH User_purchased_within_30_days as (
...) 
select UserID,
       month,                                                                                             
       count_if(Matched = 1)/count(distinct PRODUCT_LANDED) as conversion_per_user
   from User_purchased_within_30_days
   where Purchase_date >= '2021-04-02' #jinja
     AND Purchase_date < '2021-04-09' #jinja
   group by UserID,
            month
   having count_if(Matched = 1) > 0
   order by userid,
            month) AS virtual_table
WHERE Purchase_date >= '2021-04-02 00:00:00.000000' #do not want this line as jinja is already applied above
AND Purchase_date < '2021-04-09 00:00:00.000000' #do not want this line as jinja is already applied above
```
Is there a work around for me to get superset to hide those two last lines?
Thanks.

**Comment by cccs-jc** [comment]
I see @ptheru in your case being able to "mark" the purchased_date time range has "handled" would enable you to signal to the sqla/models.py not to generate filters for that column.

So maybe this is the better option. Having a means for a jinja templated query to inform the sqla/models.py which columns it should ignore because they have already been handled by the template.

**Comment by suddjian** [comment]
Related: #13942

**Comment by villebro** [comment]
I think there are two solutions to this. One is to collect "used" filters as proposed here, much like how `cache_key_wrapper` does. If we decide to do that I'd almost recommend adding it as an optional argument to the `filter_values` hook, something like `filter_values('full_name', remove_filter=True)`, after which the filter is removed from the filter list.

Another approach would be to make it possible to emit selected values as key-value pairs into `custom_form_data` in `ExtraFormData`, and then add a function to the Jinja context that can pick those up. This way they wouldn't interfere with regular filters. In the above case, the Pie chart would call the `setDataMask` hook with something like
```
{
  custom_form_data: {
    employees: ['Employee 1', 'Employee 2']
  },
}
```
after which we could pick those up in Jinja, something like
```
 {{ "'" + "', '".join(custom_form_data_values('employees')) + "'" }} 
```
I'd personally vote for the latter approach, as removing filters could have security implications, especially for deployments utilizing RLS or other similar means of automated data filtering.

**Comment by cccs-jc** [comment]
The issue with the second approach is that a viz needs to handle these type of filters specifically. The generic adhoc filtering capabilities would be lost. I think this would also not work with native filters since I assume these emit regular filters.

Option 1 treats filters generically. From a UI point of view it does not  distinguish between a filter which will be applied by sqla/models.py and one applied by the jinja template.

Roughly speaking, the sqla/models.py adds where conditions around the virtual table in the following order:

1. add conditions corresponding to UI filter (adhoc filters etc)
2. add conditions specified in RLS
3. add conditions for Extras
4. add conditions for apply_fetch_values_predicate
5. add conditions for granularity 
 
Option 1's propositions is:
Since a jinja template handles a filter (at step 0) it informs (can inform) the sqla/models.py to skip step 1 (and only step 1). 

I don't believe option 1 would break RLS. I'm I missing something?

**Comment by ptheru** [comment]
I agree with @cccs-jc 
Option 1 is simplistic approach and makes sense. 

@villebro In Option2, does it mean the filter "employees" can take only the ones hardcoded in this dictionary? Meaning jinja will pick values from the values that you hardcode in custom_form_data? In my case, it is a "date" so I am not sure how this would pan out.
'''
{
  custom_form_data: {
    employees: ['Employee 1', 'Employee 2']
  },
}
'''
I am new to Superset and please let me know if I have understood it as I am supposed to.

**Comment by cccs-jc** [comment]
@ptheru  Option 2 that Ville proposes does not mean the values would be hard coded.

@villebro I'm going to make a prototype of option 1. Having a working example might be the best way to understand the implications. I will do as you suggest with the remove_filter=True. I'll have to take a look at cache_key_wrapper.

**Comment by villebro** [comment]
@cccs-jc sounds good - keep me in the loop and feel free to reach out if you have questions! We can keep this behind a feature flag until we're certain that it doesn't pose security concerns.
