### ISSUE TITLE
Docker Compose with no example data

### ISSUE THREAD

**Issue by alexkreidler** [apache/superset#13957]
When I followed the recommended instructions for running Superset with Docker Compose, it took quite a while to load the example data. On a subsequent try it took 6 minutes and the HTTP endpoint provided no response (it just hung).

```
curl -vv http://0.0.0.0:8088/                                                                                                                                                                           (base) 
*   Trying 0.0.0.0:8088...
* TCP_NODELAY set
* Connected to 0.0.0.0 (127.0.0.1) port 8088 (#0)
> GET / HTTP/1.1
> Host: 0.0.0.0:8088
> User-Agent: curl/7.68.0
> Accept: */*
> 
```

It would be great if there was a version of the Docker Compose with no Postgres container, no example data from the init script, just a minimal installation. I think this could really help folks get started on devices with less resources, or who might already have a database they want to use rather than examples.

As a side note, there is not much documentation on what each container does, and whether it is necessary. Adding this would really help folks like me who want to customize the docker-compose config.

Thanks a ton!

**Comment by alexkreidler** [comment]
Ok I've realized you can set `SUPERSET_LOAD_EXAMPLES=no` in `.env-non-dev` to disable loading the examples. The `docker-compose down -v` command is also helpful to remove previous volumes.

I'll leave this open to track adding a note for this in the docs.

**Comment by nytai** [comment]
@alexkreidler docker-compose provides a simple way to bring up a fully functional version of superset with a single command. Redis and Postgres are used by the application for caching and storing metadata, if you would like to bring your own instances of these, running docker containers directly might be a better fit https://hub.docker.com/r/apache/superset. 

The docs could always be better. Having a section for "Debugging docker-compose" and "Customizing docker-compose" would be useful. Would you be interested in contributing in this area?

**Comment by alexkreidler** [comment]
Sure, PR incoming.
