### ISSUE TITLE
[Dashboard] Tooltips disappear on loading dashboards

### ISSUE THREAD

**Issue by serenajiang** [apache/superset#13952]
In a dashboard, if you mouse over a chart while *other charts* on the same tab are loading, the tooltip is visible. However, once at least one other chart loads, mousing over the original chart no longer displays the tooltip, and it won't come back unless you reload the dashboard, force refresh the chart, or inspect element.

### Expected results

Tooltip appears:
![image](https://user-images.githubusercontent.com/14146019/113604881-bbcbf280-95fa-11eb-8707-1ddc91199552.png)

### Actual results

Tooltip does not appear:
![image](https://user-images.githubusercontent.com/14146019/113604984-e3bb5600-95fa-11eb-9de1-83ed632943e5.png)

#### How to reproduce the bug
1. Open any superset Dashboard (preferably with lots of charts to load)
2. While charts are loading, mouse over an "already loaded" chart to engage the tooltips
3. Once another chart has loaded, the tooltip for the "first-loaded" chart will no longer be visible.

### Environment

(please complete the following information):

- superset version: `superset version`: up-to-date as of 2021-04-02
- python version: `python --version`: 3.7
- node.js version: `node -v`: `v14.16.0`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@serenajiang thanks for reporting! which charts are you seeing this issue? I assume it's NVD3 line?

**Comment by iercan** [comment]
We also face this issue with line charts.

**Comment by D3nn3** [comment]
Same here. Happens at least for line charts and time-series bar charts (currently only have these two types).

**Comment by etr2460** [comment]
This is resolved in master now!
