### ISSUE TITLE
[Drilldown]Support mapping of source/target columns in Cross-Filters

### ISSUE THREAD

**Issue by cccs-jc** [apache/superset#13966]
This is mock-up of a dashboard with two Charts. The first chart is a table of flights between a originating airport and a destination airport. Columns include ORIGINATING_AIRPORT, DESTINATION_AIRPORT

The second chart gives details about a given airport. Columns include AIRPORT, LOCATION, BUILT

The idea would be to use cross-filtering in order to display the details of the airport selected in the flights table.

Notice that the datasets used in the charts do not share a common airport column name. Currently cross-filter require matching source/target column names.

![Flights](https://user-images.githubusercontent.com/56140112/113712853-a0bdb900-96b4-11eb-9702-b38b4a2bb92c.png)

You can also imagine a Slack dataset where columns might be "USER_MENTION", "USER_REACTION", "USER_COMMENT" and a user details table keyed on "USER_ID".

In the cross-filtering mechanism it would be great to have a means to map a given source column to a target filter column.

**Comment by junlincc** [comment]
hey jc, the feature you are proposing is called 'drilldown', similar to cross-filtering. instead of changing a 'where clause', drill down is basically changing the dimension. enabling it is now our top priority and would love to use some help from you. 
lmk your plan on contributing 🙏 @cccs-jc

**Comment by cccs-jc** [comment]
Proposing to augment the Explore CUSTOMIZE COLUMNS. Adding a means to specify the emitted filter name.
 
 ![Specify_Emitted_Filter_Name_Airport](https://user-images.githubusercontent.com/56140112/119170190-e77f2c80-ba30-11eb-9ad0-65cf8252b851.png)
 
 @villebro's comment:
That’s a good approach. To avoid cluttering the UI, we need to start working on dynamic controls to be able to do “progressive disclosure” of fields. In this case, the emitted filter option would be shown only if “Emit filters” is enabled

**Comment by jhult** [comment]
@junlincc and @cccs-jc, did apache-superset/superset-ui#1157 ever make its way into Superset? I don't see anything on a table chart (even with "Emit Dashboard Cross Filters" enabled).

It would also be nice to have this for other (all?) chart types (such as a pie chart).

**Comment by rusackas** [comment]
Spoke with @cccs-tom and @geido about this on [Superset Slack](http://bit.ly/join-superset-slack), and it sounds like it's still valid.

**Comment by rusackas** [comment]
I'm tempted to close this since it's more of a proposal than a bug report, and I'm not sure anyone's planning to work on the effort. I'd propose closing this and revisiting the effort with a new Issue/PR when relevant. Any objections?

**Comment by cccs-rc** [comment]
No objections from us. :)
