### ISSUE TITLE
[dashboard]Filter boxes are difficult to use with long text in filters

### ISSUE THREAD

**Issue by octaviancorlade** [apache/superset#13967]
## Screenshot

This is from an example dashboard using the current master in Firefox
![long text in filter box](https://user-images.githubusercontent.com/15089539/113718614-1d6c8980-96ed-11eb-80bb-41ea0a1039d3.gif)

## Description

Long strings in filter boxes are hard to deselect: one has to scroll right, remove a filter entry, and scroll left again to click "Apply"

## Design input
Removing `white-space: nowrap` seems to improve things:
![image](https://user-images.githubusercontent.com/15089539/113718529-062d9c00-96ed-11eb-90e3-2331d98d4487.png)

**Comment by junlincc** [comment]
thanks for reporting! 

@octaviancorlade i believe displaying long text is not an issue in dashboard native filter. feel free to check it out and confirm as we will stop maintaining filterbox in a few month. 🙏

**Comment by octaviancorlade** [comment]
Hi @junlincc , thanks, just to confirm it works better with native filters:

![image](https://user-images.githubusercontent.com/15089539/113836613-54927780-978d-11eb-84cf-cd92ecca9a49.png)
