### ISSUE TITLE
[cross-filter]Pie chart not displayed in visualization type if DASHBOARD_CROSS_FILTERS is not enabled

### ISSUE THREAD

**Issue by maltoze** [apache/superset#13962]
Does this is expected?

I found it here:
https://github.com/apache-superset/superset-ui/blob/master/plugins/plugin-chart-echarts/src/Pie/index.ts#L46
```javascript
behaviors: [Behavior.CROSS_FILTER]
```
Is it necessary here?

**Comment by Hemant0601** [comment]
I'm using helm installation on Kubernetes and it suddenly stopped showing pie chart in visualization. 
Do you get any solution?

**Comment by maltoze** [comment]
@Hemant0601 Just enable `DASHBOARD_CROSS_FILTERS` in `superset/config.py`
https://github.com/apache/superset/blob/762101018b64e8d9edd4ad0a28363b96b3c9e9e5/superset/config.py#L344

**Comment by Hemant0601** [comment]
@maltoze I am using helm chart. Can you suggest where to change this in values.yaml file.

**Comment by maltoze** [comment]
@Hemant0601 Sorry, I'm not familiar with helm.

**Comment by junlincc** [comment]
@simcha90 @villebro @zhaoyongjie can any of you pick this up? thanks! 🙏

**Comment by villebro** [comment]
@maltoze can you provide more detailed reproduction steps? I am unable to reproduce the problem on `master` branch

**Comment by maltoze** [comment]
@villebro I'm on master branch too...
![image](https://user-images.githubusercontent.com/18044730/113828107-9be12e00-97b6-11eb-98f2-a0c2b0da304d.png)

**Comment by Hemant0601** [comment]
@villebro I am using helm, please also suggest a patch for values.yaml
What change do i need to do in values.yaml file for this?

**Comment by Hemant0601** [comment]
@zhaoyongjie @villebro I am using helm, please also suggest a patch for values.yaml
What change do i need to do in values.yaml file for this?

Any update on this ??

**Comment by villebro** [comment]
@Hemant0601 please cherry-pick #13987 into your deployment, that should fix it.

**Comment by ptheru** [comment]
> @villebro I'm on master branch too...
> 
> ```python
> # superset/config.py
> DEFAULT_FEATURE_FLAGS: Dict[str, bool] = {
>     # ...
>     "DASHBOARD_CROSS_FILTERS": False,
>     # ...
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/18044730/113832302-0f853a00-97bb-11eb-94da-d4f0a9d81dff.png)
> 
> ```python
> # superset/config.py
> DEFAULT_FEATURE_FLAGS: Dict[str, bool] = {
>     # ...
>     "DASHBOARD_CROSS_FILTERS": True,
>     # ...
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/18044730/113828617-304b9080-97b7-11eb-905f-08cd051bc8c0.png)

This worked! Thank you
