### ISSUE TITLE
[chart]Columns with all NA values should not be silently dropped

### ISSUE THREAD

**Issue by octaviancorlade** [apache/superset#13968]
#8040 restored dropping columns that are all NA, but it is problematic in some visualization types. 
There is already #13612 for this issue in Bar Charts, for which I opened a PR, but the same applies to dual line charts if one of the lines has only null values. 
The error is also not informative, since it only shows the name of the column.

### Expected results

The null values should be shown as nulls, without data points on the charts

![image](https://user-images.githubusercontent.com/15089539/113723675-df259900-96f1-11eb-8dab-f30953fd44d1.png)

### Actual results

The null series is dropped by `pandas.pivot_table` calls which use `dropna=True` as default, and the user can only see the text of a `KeyError`:

![image](https://user-images.githubusercontent.com/15089539/113723786-fa90a400-96f1-11eb-96ba-19d3f3b06586.png)

The stacktrace for the dual line chart:
```
ERROR:superset.views.base:'metric1'
Traceback (most recent call last):
  File "/app/superset/views/base.py", line 181, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/utils/log.py", line 164, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/utils/cache.py", line 152, in wrapper
    return f(*args, **kwargs)
  File "/app/superset/views/utils.py", line 451, in wrapper
    return f(*args, **kwargs)
  File "/app/superset/views/core.py", line 619, in explore_json
    return self.generate_json(viz_obj, response_type)
  File "/app/superset/views/core.py", line 456, in generate_json
    payload = viz_obj.get_payload()
  File "/app/superset/viz.py", line 464, in get_payload
    payload["data"] = self.get_data(df)
  File "/app/superset/viz.py", line 1531, in get_data
    chart_data = self.to_series(df)
  File "/app/superset/viz.py", line 1500, in to_series
    ys = series[m]
KeyError: 'metric1'
```

#### How to reproduce the bug

1. Open a bar chart, a dual line chart, or other charts that use `pandas.pivot_table` in `viz.py`
2. Choose a metric that only returns null values for the selected period. This is true for e.g. `sum(1)+null` in most SQL dialects

### Environment

I used the latest master with docker

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@octaviancorlade thank you so much for reporting! do you mind confirming what charts are being affected? 

@villebro @zhaoyongjie @kgabryje what's the behavior in echarts and pivot table do you guys know? 🙏

**Comment by kgabryje** [comment]
In the case of Echarts, Timeseries displays null values as zeros. Pie and Graph charts display nothing (just white background) and Box chart displays an error `Error: No numeric types to aggregate`

**Comment by octaviancorlade** [comment]
Here are some screenshots and links to reproduce locally with the example data of the ones using `df.pivot_table()` in `viz.py`, only Big Number and Time-series Period Pivot seem to handle the situation currently. 
I am not sure if I'm missing something since the Pivot Table generates errors here, maybe the screenshots by @kgabryje are both not yet in master?
 
[Time-series Table](http://localhost:8088/superset/explore/?form_data=%7B%22viz_type%22%3A%22time_table%22%2C%22datasource%22%3A%2219__table%22%2C%22slice_id%22%3A82%2C%22url_params%22%3A%7B%7D%2C%22time_range_endpoints%22%3A%5B%22inclusive%22%2C%22exclusive%22%5D%2C%22granularity_sqla%22%3A%22time_start%22%2C%22time_grain_sqla%22%3A%22P1D%22%2C%22time_range%22%3A%22No+filter%22%2C%22metrics%22%3A%5B%7B%22expressionType%22%3A%22SQL%22%2C%22sqlExpression%22%3A%22COUNT%28%2A%29+%2B+NULL%22%2C%22column%22%3Anull%2C%22aggregate%22%3Anull%2C%22isNew%22%3Afalse%2C%22hasCustomLabel%22%3Afalse%2C%22label%22%3A%22COUNT%28%2A%29+%2B+NULL%22%2C%22optionName%22%3A%22metric_k65my36ei5e_qiwcw5ofy4m%22%7D%5D%2C%22adhoc_filters%22%3A%5B%5D%2C%22groupby%22%3Anull%2C%22limit%22%3A100%2C%22column_collection%22%3A%5B%7B%22key%22%3A%22jTqUEXjNb%22%7D%5D%2C%22row_limit%22%3A10000%2C%22extra_form_data%22%3A%7B%22custom_form_data%22%3A%7B%7D%2C%22override_form_data%22%3A%7B%7D%2C%22append_form_data%22%3A%7B%7D%7D%7D)

![image](https://user-images.githubusercontent.com/15089539/113845157-7e4f9c80-9795-11eb-89af-74d23999fd5b.png)

[Pivot Table](http://localhost:8088/superset/explore/?form_data=%7B%22viz_type%22%3A%22pivot_table%22%2C%22datasource%22%3A%2219__table%22%2C%22slice_id%22%3A82%2C%22url_params%22%3A%7B%7D%2C%22time_range_endpoints%22%3A%5B%22inclusive%22%2C%22exclusive%22%5D%2C%22granularity_sqla%22%3A%22time_start%22%2C%22time_grain_sqla%22%3A%22P1D%22%2C%22time_range%22%3A%22No+filter%22%2C%22metrics%22%3A%5B%7B%22expressionType%22%3A%22SQL%22%2C%22sqlExpression%22%3A%22COUNT%28%2A%29+%2B+NULL%22%2C%22column%22%3Anull%2C%22aggregate%22%3Anull%2C%22isNew%22%3Afalse%2C%22hasCustomLabel%22%3Afalse%2C%22label%22%3A%22COUNT%28%2A%29+%2B+NULL%22%2C%22optionName%22%3A%22metric_k65my36ei5e_qiwcw5ofy4m%22%7D%5D%2C%22adhoc_filters%22%3A%5B%5D%2C%22groupby%22%3A%5B%22marital_status%22%5D%2C%22columns%22%3A%5B%5D%2C%22row_limit%22%3A10000%2C%22order_desc%22%3Atrue%2C%22pandas_aggfunc%22%3A%22sum%22%2C%22pivot_margins%22%3Atrue%2C%22number_format%22%3A%22SMART_NUMBER%22%2C%22date_format%22%3A%22smart_date%22%2C%22extra_form_data%22%3A%7B%22custom_form_data%22%3A%7B%7D%2C%22override_form_data%22%3A%7B%7D%2C%22append_form_data%22%3A%7B%7D%7D%7D)

![image](https://user-images.githubusercontent.com/15089539/113845377-bce55700-9795-11eb-9cf8-c9c5bbec1de2.png)

[Big Number](http://localhost:8088/superset/explore/?form_data=%7B%22viz_type%22%3A%22big_number_total%22%2C%22datasource%22%3A%2219__table%22%2C%22slice_id%22%3A82%2C%22url_params%22%3A%7B%7D%2C%22time_range_endpoints%22%3A%5B%22inclusive%22%2C%22exclusive%22%5D%2C%22granularity_sqla%22%3A%22time_start%22%2C%22time_range%22%3A%22No+filter%22%2C%22metric%22%3A%7B%22expressionType%22%3A%22SQL%22%2C%22sqlExpression%22%3A%22COUNT%28%2A%29+%2B+NULL%22%2C%22column%22%3Anull%2C%22aggregate%22%3Anull%2C%22isNew%22%3Afalse%2C%22hasCustomLabel%22%3Afalse%2C%22label%22%3A%22COUNT%28%2A%29+%2B+NULL%22%2C%22optionName%22%3A%22metric_egnne5z0946_d0cm4i01bm7%22%7D%2C%22adhoc_filters%22%3A%5B%5D%2C%22y_axis_format%22%3A%22SMART_NUMBER%22%2C%22header_font_size%22%3A0.4%2C%22subheader_font_size%22%3A0.15%2C%22extra_form_data%22%3A%7B%22custom_form_data%22%3A%7B%7D%2C%22override_form_data%22%3A%7B%7D%2C%22append_form_data%22%3A%7B%7D%7D%7D) looks OK to me

![image](https://user-images.githubusercontent.com/15089539/113847040-5b25ec80-9797-11eb-93a4-c88c910ce9da.png)

[Dual Line Chart](http://localhost:8088/superset/explore/?form_data=%7B%22viz_type%22%3A%22dual_line%22%2C%22datasource%22%3A%2219__table%22%2C%22slice_id%22%3A82%2C%22url_params%22%3A%7B%7D%2C%22time_range_endpoints%22%3A%5B%22inclusive%22%2C%22exclusive%22%5D%2C%22granularity_sqla%22%3A%22time_start%22%2C%22time_grain_sqla%22%3A%22P1D%22%2C%22time_range%22%3A%22No+filter%22%2C%22color_scheme%22%3A%22supersetColors%22%2C%22label_colors%22%3A%7B%7D%2C%22x_axis_format%22%3A%22smart_date%22%2C%22metric%22%3A%22count%22%2C%22y_axis_format%22%3A%22SMART_NUMBER%22%2C%22y_axis_bounds%22%3A%5Bnull%2Cnull%5D%2C%22metric_2%22%3A%7B%22expressionType%22%3A%22SQL%22%2C%22sqlExpression%22%3A%22COUNT%28%2A%29+%2B+NULL%22%2C%22column%22%3Anull%2C%22aggregate%22%3Anull%2C%22isNew%22%3Afalse%2C%22hasCustomLabel%22%3Afalse%2C%22label%22%3A%22COUNT%28%2A%29+%2B+NULL%22%2C%22optionName%22%3A%22metric_y1k9ywww97r_ydides4be9%22%7D%2C%22y_axis_2_format%22%3A%22SMART_NUMBER%22%2C%22y_axis_2_bounds%22%3A%5Bnull%2Cnull%5D%2C%22adhoc_filters%22%3A%5B%5D%2C%22annotation_layers%22%3A%5B%5D%2C%22extra_form_data%22%3A%7B%22custom_form_data%22%3A%7B%7D%2C%22override_form_data%22%3A%7B%7D%2C%22append_form_data%22%3A%7B%7D%7D%7D)

![image](https://user-images.githubusercontent.com/15089539/113845874-38df9f00-9796-11eb-826c-4cb6edd99e3b.png)

[Time-series Period Pivot](http://localhost:8088/superset/explore/?form_data=%7B%22viz_type%22%3A%22time_pivot%22%2C%22datasource%22%3A%2219__table%22%2C%22slice_id%22%3A82%2C%22url_params%22%3A%7B%7D%2C%22time_range_endpoints%22%3A%5B%22inclusive%22%2C%22exclusive%22%5D%2C%22granularity_sqla%22%3A%22time_start%22%2C%22time_grain_sqla%22%3A%22P1D%22%2C%22time_range%22%3A%22No+filter%22%2C%22metric%22%3A%7B%22expressionType%22%3A%22SQL%22%2C%22sqlExpression%22%3A%22COUNT%28%2A%29+%2B+NULL%22%2C%22column%22%3Anull%2C%22aggregate%22%3Anull%2C%22isNew%22%3Afalse%2C%22hasCustomLabel%22%3Afalse%2C%22label%22%3A%22COUNT%28%2A%29+%2B+NULL%22%2C%22optionName%22%3A%22metric_3k6ay6ex9gu_2er2f7kq0kc%22%7D%2C%22adhoc_filters%22%3A%5B%5D%2C%22freq%22%3A%22W-MON%22%2C%22line_interpolation%22%3A%22linear%22%2C%22color_picker%22%3A%7B%22r%22%3A0%2C%22g%22%3A122%2C%22b%22%3A135%2C%22a%22%3A1%7D%2C%22x_axis_label%22%3A%22age%22%2C%22bottom_margin%22%3A%22auto%22%2C%22x_axis_format%22%3A%22smart_date%22%2C%22y_axis_label%22%3A%22count%22%2C%22left_margin%22%3A%22auto%22%2C%22y_axis_format%22%3A%22SMART_NUMBER%22%2C%22y_axis_bounds%22%3A%5Bnull%2Cnull%5D%2C%22extra_form_data%22%3A%7B%22custom_form_data%22%3A%7B%7D%2C%22override_form_data%22%3A%7B%7D%2C%22append_form_data%22%3A%7B%7D%7D%7D) also looks OK to me

![image](https://user-images.githubusercontent.com/15089539/113846206-878d3900-9796-11eb-8985-7ce10812e0ea.png)

[Bar Chart](http://localhost:8088/superset/explore/?form_data=%7B%22viz_type%22%3A%22dist_bar%22%2C%22datasource%22%3A%2219__table%22%2C%22slice_id%22%3A82%2C%22url_params%22%3A%7B%7D%2C%22time_range_endpoints%22%3A%5B%22inclusive%22%2C%22exclusive%22%5D%2C%22granularity_sqla%22%3A%22time_start%22%2C%22time_range%22%3A%22No+filter%22%2C%22metrics%22%3A%5B%7B%22expressionType%22%3A%22SQL%22%2C%22sqlExpression%22%3A%22COUNT%28%2A%29+%2B+NULL%22%2C%22column%22%3Anull%2C%22aggregate%22%3Anull%2C%22isNew%22%3Afalse%2C%22hasCustomLabel%22%3Afalse%2C%22label%22%3A%22COUNT%28%2A%29+%2B+NULL%22%2C%22optionName%22%3A%22metric_u5cuk4h7i48_nopwaswccig%22%7D%5D%2C%22adhoc_filters%22%3A%5B%5D%2C%22groupby%22%3A%5B%22marital_status%22%5D%2C%22columns%22%3A%5B%5D%2C%22row_limit%22%3A10000%2C%22order_desc%22%3Atrue%2C%22color_scheme%22%3A%22supersetColors%22%2C%22label_colors%22%3A%7B%7D%2C%22y_axis_format%22%3A%22SMART_NUMBER%22%2C%22y_axis_label%22%3A%22count%22%2C%22y_axis_bounds%22%3A%5Bnull%2Cnull%5D%2C%22x_axis_label%22%3A%22age%22%2C%22bottom_margin%22%3A%22auto%22%2C%22x_ticks_layout%22%3A%22auto%22%2C%22extra_form_data%22%3A%7B%22custom_form_data%22%3A%7B%7D%2C%22override_form_data%22%3A%7B%7D%2C%22append_form_data%22%3A%7B%7D%7D%7D)

![image](https://user-images.githubusercontent.com/15089539/113846480-cde29800-9796-11eb-9b07-5efd0ed890b7.png)

[Paired t-test Table](http://localhost:8088/superset/explore/?form_data=%7B%22viz_type%22%3A%22paired_ttest%22%2C%22datasource%22%3A%2219__table%22%2C%22slice_id%22%3A82%2C%22url_params%22%3A%7B%7D%2C%22time_range_endpoints%22%3A%5B%22inclusive%22%2C%22exclusive%22%5D%2C%22granularity_sqla%22%3A%22time_start%22%2C%22time_range%22%3A%22No+filter%22%2C%22metrics%22%3A%5B%7B%22expressionType%22%3A%22SQL%22%2C%22sqlExpression%22%3A%22COUNT%28%2A%29+%2B+NULL%22%2C%22column%22%3Anull%2C%22aggregate%22%3Anull%2C%22isNew%22%3Afalse%2C%22hasCustomLabel%22%3Afalse%2C%22label%22%3A%22COUNT%28%2A%29+%2B+NULL%22%2C%22optionName%22%3A%22metric_u5cuk4h7i48_nopwaswccig%22%7D%5D%2C%22adhoc_filters%22%3A%5B%5D%2C%22groupby%22%3A%5B%22marital_status%22%5D%2C%22limit%22%3A100%2C%22order_desc%22%3Atrue%2C%22row_limit%22%3A10000%2C%22significance_level%22%3A0.05%2C%22pvalue_precision%22%3A6%2C%22liftvalue_precision%22%3A4%2C%22extra_form_data%22%3A%7B%22custom_form_data%22%3A%7B%7D%2C%22override_form_data%22%3A%7B%7D%2C%22append_form_data%22%3A%7B%7D%7D%7D)

![image](https://user-images.githubusercontent.com/15089539/113846620-f5396500-9796-11eb-8f76-4ea364d39f6b.png)

**Comment by junlincc** [comment]
Thanks for all the details @octaviancorlade Pivot table will be merged soon this week. And we will look at the NA issues in all charts. 
@villebro @rusackas let's move and stage it to the main repo for testing.

**Comment by rusackas** [comment]
I see this issue has gone cold for quite a while, but I suspect it's still valid. Does anyone have bandwidth to take stock of the situation in newer versions of Superset (e.g. 2.0.1 or higher) to see if/where this is still breaking? It would be great to update this ticket with more granular details of exactly which charts/areas need attention.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
