### ISSUE TITLE
[Explore] data table unnecessary re-render

### ISSUE THREAD

**Issue by michael-s-molina** [apache/superset#13978]
## Description

Avoid unnecessary re-render of the data table in Explore. As we can see in the video below, the data table is re-rendered even if the control being applied is not related to the table. We can improve the user experience by only re-rendering the data table if the modified control affects the table data.

## Screenshot

https://user-images.githubusercontent.com/70410625/113782575-d1c7d900-9708-11eb-8135-b2c982073bd8.mov#13974 

@junlincc @rusackas

**Comment by junlincc** [comment]
Make sense, thanks for suggesting! 

cc @kgabryje (not urgent, let's wait for next quality bash :) )

**Comment by Nicke7117** [comment]
Could I try to fix this?

**Comment by michael-s-molina** [comment]
@junlincc After careful investigation, we'll need some API changes to fix the re-render problem. In talks with @rusackas we decided to postpone the fix.
