### ISSUE TITLE
[homescreen]500 error when deleting dashboards

### ISSUE THREAD

**Issue by jonathanmorais** [apache/superset#13977]
Error 500 when trying to delete dashboards 
### Expected results

Dashboard deletion

### Actual results

There was an issue deleting [ <dashboard> ]: Fatal error

#### Screenshots

![Captura de tela de 2021-04-06 17-16-04](https://user-images.githubusercontent.com/12867382/113774036-249b9380-96fd-11eb-805d-66a1a4cf2ec2.png)

![superset_500](https://user-images.githubusercontent.com/12867382/113773922-0170e400-96fd-11eb-9795-2c4db7a3bde1.png)

### Environment

- superset version: `1.0.1`

**Comment by nytai** [comment]
can you post the server logs for this? A stack trace would be helpful

**Comment by jonathanmorais** [comment]
Sure, the only log that the application gives us, here is:

![superset_log](https://user-images.githubusercontent.com/12867382/113775103-988a6b80-96fe-11eb-8b18-19e025b1ace6.png)

**Comment by rusackas** [comment]
@andrey-zayats took a look at this and was unable to reproduce the issue. I'm going to go ahead and remove the `validation:required` label and close the issue. If anyone sees this happening in Superset 2.0.x or later, or on `master`, we're open to revisiting this conversation, re-opening the ticket, or triaging a new Issue with updated context. Thank you!
