### ISSUE TITLE
[dashboard]'go back' button causes page crash in dashboard

### ISSUE THREAD

**Issue by junlincc** [apache/superset#13976]
See video

https://user-images.githubusercontent.com/67837651/113766859-ca85d880-96d2-11eb-8be8-4307b552e061.mov

#### How to reproduce the bug

1. Go to Dashboards
2. Click on any dashboard
3. Click on go back button "<- "

### Environment 
master

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by nytai** [comment]
That exception looks related to async queries
