### ISSUE TITLE
`ALLOW CROSS FILTER` option not work on Table.

### ISSUE THREAD

**Issue by maltoze** [apache/superset#13988]
### Expected results

`ALLOW CROSS FILTER` should be work on Table.
### Actual results

`ALLOW CROSS FILTER` not work on Table chart.

#### Screenshots

![image](https://user-images.githubusercontent.com/18044730/113836527-891f2700-97bf-11eb-9957-5422bd8cc8eb.png)

#### How to reproduce the bug

1. Add a Table chart and enable `ALLOW CROSS FILTER`
2. Add it to dashboard
3. Click on a cell

### Environment

(please complete the following information):

- superset version: I'm on `master` branch
- python version: `Python 3.7.8`
- node.js version: `v14.16.0`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
The error occurred here:
https://github.com/apache/superset/blob/a82d72fef60dc88511409405d81cc13efce3bba7/superset-frontend/src/dashboard/reducers/dashboardFilters.js#L104

**Comment by maltoze** [comment]
Fixed by this PR: https://github.com/apache-superset/superset-ui/pull/1041

**Comment by jeisonki** [comment]
****
