### ISSUE TITLE
cannot display label percentage value in pie chart 

### ISSUE THREAD

**Issue by ivanku99** [apache/superset#13982]
I can't display values and percentage in pie chart
the category was fixed -Category,value,percentage but nothing changed
![WhatsApp Image 2021-04-06 at 18 55 59](https://user-images.githubusercontent.com/82075724/113811142-78ee5400-978d-11eb-9969-6e8d07ac3801.jpeg)
![WhatsApp Image 2021-04-06 at 18 55 23](https://user-images.githubusercontent.com/82075724/113811144-7a1f8100-978d-11eb-941a-e83312261ad0.jpeg)

**Comment by junlincc** [comment]
what version are you at? i believe it's fixed a while ago.

**Comment by ivanku99** [comment]
Version: 1.0.1

**Comment by ivanku99** [comment]
it happend after dawnloading  a new version. the old version  worked correctly

**Comment by octaviancorlade** [comment]
I'm not sure about 1.0.1 but it works with the current master, also with non-latin alphabets:

![image](https://user-images.githubusercontent.com/15089539/113925695-9f42dc80-97eb-11eb-8336-397da050a4d5.png)

**Comment by ivanku99** [comment]
what kind of type is this column in russian?  varchar?

**Comment by octaviancorlade** [comment]
@ivanku99 yes that's right, I used the one defined [here](https://github.com/apache/superset/blob/master/superset/examples/configs/datasets/examples/unicode_test.test.yaml#L55) from the example data

**Comment by ivanku99** [comment]
I used the same Varchar and russian font like the upper left line 
But it dosn't work now. The old version of superset did not have tis problem

**Comment by rusackas** [comment]
@andrey-zayats took a look at this and was unable to reproduce the issue. I'm going to go ahead and remove the `validation:required` label and close the issue. If anyone sees this happening in Superset 2.0.x or later, or on `master`, we're open to revisiting this conversation, re-opening the ticket, or triaging a new Issue with updated context. Thank you!
