### ISSUE TITLE
Allow password to be specified for redis

### ISSUE THREAD

**Issue by caleb15** [apache/superset#13995]
**Is your feature request related to a problem? Please describe.**
https://github.com/apache/superset/blob/master/helm/superset/values.yaml says you can set a password for redis. (search for `Redis password`)
However, the superset helm chart does not appear to accept a redis password configuration.
See https://github.com/apache/superset/blob/master/helm/superset/templates/_helpers.tpl#L60 and 
https://github.com/apache/superset/blob/master/helm/superset/templates/secret-env.yaml

**Describe the solution you'd like**
Helm chart modified to allow passwords.

**Describe alternatives you've considered**
Redis can be locked down in a VPC. This doesn't completely eliminate the need for passwords but it helps protect it.

**Additional context**
Related issue: https://github.com/apache/superset/issues/13541

**Comment by caleb15** [comment]
Related PR: https://github.com/apache/superset/pull/8420/files (for just docker though, it doesn't include the helm chart)

**Comment by julianbei** [comment]
You missed something: https://github.com/apache/superset/pull/14274/files#issuecomment-827038300

**Comment by caleb15** [comment]
@robdiciuccio there's a minor change left (see above). Can this be reopened please? If you want I can create another ticket.
