### ISSUE TITLE
Images broken in documentation 

### ISSUE THREAD

**Issue by mrengy** [apache/superset#13990]
In some (maybe all) pages in https://apache-superset.readthedocs.io/en/0.36/usertutorial.html , images are broken.

### Expected results

A screenshot should appear where there is a broken image icon

### Actual results

A broken image icon and image file path appears in place of the image

#### Screenshots

<img width="773" alt="Screen Shot 2021-04-07 at 10 43 28 AM" src="https://user-images.githubusercontent.com/2223603/113886065-5f014100-978e-11eb-9d25-f0b79b4f5926.png">

#### How to reproduce the bug

1. Go to https://apache-superset.readthedocs.io/en/0.36/usertutorial.html#markup

**Comment by srinify** [comment]
Hi there @mrengy the Superset docs have actually moved over to their own site and the page you're on is no longer maintained.

Here's the new link!

https://superset.apache.org/docs/creating-charts-dashboards/first-dashboard
