### ISSUE TITLE
[Homescreen] Dashboard thumbnail is gone when toggling between favorite and mine

### ISSUE THREAD

**Issue by rosemarie-chiu** [apache/superset#14000]
Pre-Condition:
being the owner of a dashboard

Steps:
1. Open homescreen, observe in dashboard section there is a dashboard in mine
2. Toggle to Favorite
3. Toggle back to mine, observe in mine, no dashboard show up

### Expected results
Togging back to mine dashboard should show dashboard thumbnails that I own

### Actual results
No dashboard thumbnail shows up in mine unless I refresh
what actually happens.

#### Screenshots

https://user-images.githubusercontent.com/52086618/113937164-99c6a180-97ad-11eb-9ab3-083fc230b60e.mov

**Comment by yousoph** [comment]
Can't repro this anymore, closing.
