### ISSUE TITLE
Dashboard properties do not update in dashboard list UI

### ISSUE THREAD

**Issue by samtfm** [apache/superset#14001]
Editing dashboard properties does not cause an update in the dashboard list UI until the page is refreshed.

### Expected results

Dashboard is updated in the ui with new title and owners.

### Actual results

Edits are saved, but don't show up unless you refresh the page.

#### Screenshots

![Screen Shot 2021-04-07 at 2 41 07 PM](https://user-images.githubusercontent.com/12817097/113938374-62f18b00-97af-11eb-9c78-316dd4ab9e6f.png)

#### How to reproduce the bug
1. Go to Dashboards list view.
2. Open edit modal for a dashboard (pencil icon)
3. Edit Title or Owners fields.
4. Press save.
5. See dashboard in list with outdated details

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rosemarie-chiu** [comment]
🏷 preset-QA
