### ISSUE TITLE
Link broken in top-level documentation 

### ISSUE THREAD

**Issue by richlysakowski** [apache/superset#14012]
The third bullet on Page 1 of the main Apache / Superset documentation has a broken link [Documentation | Superset](https://superset.apache.org/docs/docs/installation/installing-superset-using-docker-compose), which leads to an error "Not Found The requested URL was not found on this server."  I want to install Superset into Windows using Docker Desktop.   

I am using Firefox on Windows 10.

From the page [Superset Introduction](https://superset.apache.org/docs/intro)

```
What is Apache Superset?

Apache Superset is a modern, enterprise-ready business intelligence web application. It is fast, lightweight, intuitive, and loaded with options that make it easy for users of all skill sets to explore and visualize their data, from simple pie charts to highly detailed deck.gl geospatial charts.

Here are a few different ways you can get started with Superset:

    Download the source from Apache Foundation's website
    Download the latest Superset version from Pypi here
    Setup Superset locally with one command [using Docker Compose]  
    Download the Docker image from Dockerhub
    Install bleeding-edge master version of Superset from Github

```
https://superset.apache.org/docs/docs/installation/installing-superset-using-docker-compose

**Comment by srinify** [comment]
Thank you @richdevboston I will fix this today!

**Comment by suddjian** [comment]
@srinify was this fixed? If so can we close this issue?

**Comment by rusackas** [comment]
This seems to be resolved in the updated documentation
