### ISSUE TITLE
Can we embed images in Pivot table in Superset?

### ISSUE THREAD

**Issue by Renganayaki1** [apache/superset#14019]
![image](https://user-images.githubusercontent.com/77659418/114002526-93522b80-987a-11eb-93df-f6bdb549e192.png)

As you can see above, If I add the image column in pivot table, Instead of images, I'm getting the same HTML formatted column. 

Can we add/embed image in Pivot table? 
Because the same method is working well with straight table but not working with pivot table.

First of all, can we do this? Whether Pivot table in Superset supports this or not? 
If yes, How to do it? 

Thanks in advance. 
Rens.

**Comment by mayurnewase** [comment]
I think for now you have escape html from backend when pandas generate html.
This plugin might be getting rewritten,so this could change sooner.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
