### ISSUE TITLE
Metadata browser in SQL Lab not rendering nicely in Safari

### ISSUE THREAD

**Issue by srinify** [apache/superset#14022]
## Screenshot
<img width="3000" alt="Screen Shot 2021-04-08 at 8 09 38 AM" src="https://user-images.githubusercontent.com/801507/114024385-fc697d00-9841-11eb-8e4e-7aa8524d7cc5.png">
<img width="1488" alt="Screen Shot 2021-04-08 at 8 08 26 AM" src="https://user-images.githubusercontent.com/801507/114024387-fd021380-9841-11eb-823f-acc48277804b.png">

## Description

Latest Superset master

**Comment by yousoph** [comment]
Closed by https://github.com/apache/superset/pull/18855
