### ISSUE TITLE
[Explore] Single metric selector is inoperable if the referenced metric no longer exists

### ISSUE THREAD

**Issue by john-bodley** [apache/superset#14034]
If a metric is removed from a datasource the single metric widget is inoperable if saved slice or URL references the previously defined metric. Note this isn't a problem for visualization types which support multiple metrics.

### Expected results

The metric widget to render correctly.

### Actual results

The metric widget in inoperable (see attached screenshot).

#### Screenshots

<img width="944" alt="Screen Shot 2021-04-09 at 8 24 04 AM" src="https://user-images.githubusercontent.com/4567245/114091733-220f8880-990d-11eb-8fce-1ad089bdf846.png">

#### How to reproduce the bug

1. Using the example data visit the "Number of Girls" chart.
2. Edit the datasource by deleting the `sum_num` metric and then clicking `SAVE`.
3. Reload the page.
4. Verify the METRIC widget is inoperable (see screenshot).

### Environment

(please complete the following information):

- superset version: `master`
- python version: `3.7`
- node.js version: `14`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by Bonifacio2** [comment]
I'll take a look at this over the weekend.

**Comment by Bonifacio2** [comment]
I wasn't able to reproduce the error. After deleting the metric the save button is disabled and I get the following warning:

<img width="624" alt="supersetbug" src="https://user-images.githubusercontent.com/852540/118331836-8bbc1d00-b4df-11eb-80d6-86f018491ab8.png">

**Comment by john-bodley** [comment]
@Bonifacio2 I was missing a step (now updated). After deleting the metric you'll need to reload the page and then the metric selector will be inoperable.

**Comment by Bonifacio2** [comment]
Thank you for the update. I'll take a second look at it tomorrow.

**Comment by Bonifacio2** [comment]
Still unable to reproduce. :(
I'm guessing the change is only persisted to the database when you click the save button and not right when you remove the metric. After reloading the page it looks exactly like the first time it was loaded.
Are you using superset's latest code?

**Comment by john-bodley** [comment]
@Bonifacio2 this is reproducible using the latest code (cut from `master` on/around the 2nd of June).

**Comment by john-bodley** [comment]
@Bonifacio2 I was wondering whether there was any update on this? I rebased from `master` today and rebuilt my environment from scratch and was able to reproduce the issue as outlined in the description.

**Comment by junlincc** [comment]
@john-bodley did you have any feature flag enabled?

**Comment by Bonifacio2** [comment]
Hello, everyone. Sorry, but I no longer have the time to take care of this issue. I guess this it is up for grabs again.
