### ISSUE TITLE
Package helm chart

### ISSUE THREAD

**Issue by caleb15** [apache/superset#14037]
**Is your feature request related to a problem? Please describe.**
The helm chart is not packaged, so it can't be installed directly

**Describe the solution you'd like**
The helm chart packaged so it can easily be installed via helm/helmfile

**Describe alternatives you've considered**
We copied https://github.com/apache/superset/tree/master/helm/superset into our own chart repo and packaged it ourselves.

**Additional context**

**Comment by amitmiran137** [comment]
hey @caleb15 ,
could you elaborate what should be the steps for packaging the helm chart?
Do we need to add an helmFile.yaml?
what else?

**Comment by caleb15** [comment]
Something like the below:

`helm dependency update superset`
`helm package superset`
`helm repo index ????`

I don't know the exact commands you need unfortunately - for us we upload to S3 but I'm not sure where you would store the artifact. There's probably plenty of guides on how to do it though.

**Comment by amitmiran137** [comment]
@caleb15 if you could start a PR experimenting this we would support you getting the package into https://artifacthub.io/ or other package hub

**Comment by caleb15** [comment]
I don't think I'll be getting around to that, sorry. I already have some other open-source work I need to catch up on.

**Comment by amitmiran137** [comment]
resolved #14163 #14223

**Comment by caleb15** [comment]
Thanks! :)
