### ISSUE TITLE
Import datasets with dict in metrics: extra

### ISSUE THREAD

**Issue by GGPay** [apache/superset#14041]
If datasets has a dict in yaml file - metrics: extra  - that cause the unknown error when import datasets using UI.

![image](https://user-images.githubusercontent.com/17413180/114126680-89521c00-98be-11eb-93f6-fe3339e851c9.png)

### Actual results

Failed import datasets

#### Screenshots

![image](https://user-images.githubusercontent.com/17413180/114126842-cae2c700-98be-11eb-80d4-043487637ff8.png)

Server log

![image](https://user-images.githubusercontent.com/17413180/114127058-447ab500-98bf-11eb-86fa-1a4a9d48d698.png)

![image](https://user-images.githubusercontent.com/17413180/114127924-dafba600-98c0-11eb-8ed1-022c07c675e5.png)

#### How to reproduce the bug

1. Edit any Virtual datasets
2. Click on Metrics tab
3. Click on "Add Item" - create any new item - or even add item and click delete - it also create dict in extra field.
4. Save datasets
5. Click on Action - Export
6. Click Import  - choose zip file previously exported
7. enter "OVERWRITE"
8. See error

### Environment
- superset version: `superset version 1.0.1`
- docker-compose-non-dev.yml

### Additional context

If change dict to null in yaml file - import works as expected.

**Comment by rusackas** [comment]
Closing this since it's stale and referring to an old version of Superset. I'm more than happy to re-open this and give it some attention if anyone on this thread can validate that it's still an issue with Superset 2.1.0.
