### ISSUE TITLE
language switch disappeared | default language badly set - no way to get back to 'en'

### ISSUE THREAD

**Issue by squalou** [apache/superset#14058]
I can't change my UI language anymore, and default is badly set.

After reading a bit the code and issues ( commits from #11227 for instance ), I understand that only 'EN' should be displayed.
This is all very well.

``` python
#config.py
BABEL_DEFAULT_LOCALE = "en"
# Turning off i18n by default as translation in most languages are
# incomplete and not well maintained.
LANGUAGES = {}
```

### Expected results

Have a way to set language to appropriate 'en' default !

### Actual results

I didn't find any mean to change the language

#### Screenshots

before

![image](https://user-images.githubusercontent.com/4623644/114228446-b3671500-9976-11eb-9e2c-4159dbb6228c.png)

now

![image](https://user-images.githubusercontent.com/4623644/114228380-a21e0880-9976-11eb-97e4-532cc913564e.png)

#### How to reproduce the bug

1. Just login

### Environment

(please complete the following information):

- superset version: `Superset 1.0.1`
- python version: `Python 3.7.9`
- node.js version: `not present inside container`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Migration from 0.38.0
Using Chromium or Firefox.

Is there a remnant of lang auto-detection ? Or a badly set cookie somewhere that should be ignored in new version ?

**workaround** go to https://my-superset/lang/en/   does seem to set the language.

**Comment by squalou** [comment]
note that the url `https://my-suerset-host/lang/en` works and sets language to `en` so maybe it's more UI related than anything. Yet I have no idea what may be preventing the dropdown to display

**Comment by squalou** [comment]
Tested with these versions : same issue

- superset version ` Superset 1.1.0 (rc2)`
- python version `Python 3.7.9`

**Comment by suddjian** [comment]
Can you explain what it means that "the default is badly set"? The default in `config.py` is `en`. Did you have some user value set from a previous version that was causing the language to be different than the default?

**Comment by squalou** [comment]
The more I think about it, the more my guess is that the *browser* session was set to French.

It's very weird because I use my production superset in english only, but that was on a test setup so maybe it was set on french at a given moment on 0.38.

No language change made in server side config.

So, best bet is
- user browser session in some language on version 0.38
- server is upgraded
- user then has its UI still in its language of choice (but honestly well known translations should be a motivation to switch to en)
- ... and no way to change it.

I don't know how it would be possible tn *enforce* language in such situations.

**Comment by robdiciuccio** [comment]
You should be able to re-enable the language selector in the UI overriding the `LANGUAGES` config in your `superset_config.py` to include more than one language, if that's what's desired. Example config: https://github.com/apache/superset/blob/master/superset/config.py#L295:L295

**Comment by squalou** [comment]
Great !

Indeed, I did that and asked everyone to switch back to 'en', then removed the config again.

**Comment by DEVLHK** [comment]
> You should be able to re-enable the language selector in the UI overriding the `LANGUAGES` config in your `superset_config.py` to include more than one language, if that's what's desired. Example config:

I have try, it doesn't work.
