### ISSUE TITLE
[poll📊]Tell us your need of sharing public visualizations

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14055]
**Do you have use cases to share any of your visualizations to the public?** 
Comment with use cases and thoughts around how interactive you'd want them to be 

[![](https://api.gh-polls.com/poll/01F2VV8RGNNDG7XXRPMZTCZZGW/yes%3B%20static%20screenshot)](https://api.gh-polls.com/poll/01F2VV8RGNNDG7XXRPMZTCZZGW/yes%3B%20static%20screenshot/vote)
[![](https://api.gh-polls.com/poll/01F2VV8RGNNDG7XXRPMZTCZZGW/yes%3B%20interactive%20visualization%20with%20tooltip%20hovering)](https://api.gh-polls.com/poll/01F2VV8RGNNDG7XXRPMZTCZZGW/yes%3B%20interactive%20visualization%20with%20tooltip%20hovering/vote)
[![](https://api.gh-polls.com/poll/01F2VV8RGNNDG7XXRPMZTCZZGW/yes%3B%20interactive%20visualization%20with%20tooltip%20and%20filter)](https://api.gh-polls.com/poll/01F2VV8RGNNDG7XXRPMZTCZZGW/yes%3B%20interactive%20visualization%20with%20tooltip%20and%20filter/vote)
[![](https://api.gh-polls.com/poll/01F2VV8RGNNDG7XXRPMZTCZZGW/no%20need%20to%20share%20with%20the%20public)](https://api.gh-polls.com/poll/01F2VV8RGNNDG7XXRPMZTCZZGW/no%20need%20to%20share%20with%20the%20public/vote)

If your answer is yes above, what business sector are you in? 
[![](https://api.gh-polls.com/poll/01F2VVGC30JN67DWNT04BMVZ9F/public%20sector)](https://api.gh-polls.com/poll/01F2VVGC30JN67DWNT04BMVZ9F/public%20sector/vote)
[![](https://api.gh-polls.com/poll/01F2VVGC30JN67DWNT04BMVZ9F/private%20business)](https://api.gh-polls.com/poll/01F2VVGC30JN67DWNT04BMVZ9F/private%20business/vote)
[![](https://api.gh-polls.com/poll/01F2VVGC30JN67DWNT04BMVZ9F/others)](https://api.gh-polls.com/poll/01F2VVGC30JN67DWNT04BMVZ9F/others/vote)

**Comment by cemremengu** [comment]
Public sharing is good for company wide or external user (such as field workers) general monitoring and status check cases such as showing them on big screens

**Comment by Avinashbitm** [comment]
interactive chart sharing is widely requirement for any organization...it is always required in product industries
