### ISSUE TITLE
Add feature flag to enable/disable creation of 'examples' database.

### ISSUE THREAD

**Issue by skhortiuk** [apache/superset#14050]
### Motivation

When I import datasets, superset creates an 'examples' database even if it not listed in the database configuration files.

### Proposed Change

Add feature flag to allow disabling the creation of 'examples' database during datasets import.

**Comment by robdiciuccio** [comment]
Dataset exports are currently coupled to the database definition that they were exported from. I don't believe it's possible to import a dataset into an arbitrary database. Is that the intention?

**Comment by skhortiuk** [comment]
No, the intention is to import datasets for database without creation of "examples" database, e.g:
I have one database "my db" and I want to import datasets for it, during the import, superset creates "examples" db by default, even if tehre's no datasets for it.

**Comment by rusackas** [comment]
Closing this since it's been inactive for so long, and isn't a "bug" per se. If we want to carry this forward as a feature, I'd suggest rekindling in an "Ideas" thread on Discussions.
