### ISSUE TITLE
Totals in Pivot table are incorrect 

### ISSUE THREAD

**Issue by Artem-fb** [apache/superset#14065]
### Expected results

the sum function must aggregate the sum of the column, 
the mean function must aggregate the mean of the column, 
etc

### Actual results
sum, max, mean, std, var aggregation functions shows  max values in pivot table 

#### Screenshots
http://prntscr.com/118rk0k
http://prntscr.com/118rkhu
http://prntscr.com/118rkvx

#### How to reproduce the bug

1. Go to 'chart explore'
2. choose vizualization type - Pivot table
3. Scroll down to Pivot Options
4. choose "show totals" and aggregation function sum, max, mean, std, var

### Environment

- superset version: `superset version` 1.01 
- python version: `python --version` 3.8.5
- node.js version: `node -v` v10.19.0

**Comment by pavlozt** [comment]
looks like the error is related to #11658

**Comment by ErinYener** [comment]
I am also having this issue. I was having it on 0.38 and am still experiencing it on 1.0.

**Comment by junlincc** [comment]
@Artem-fb thanks for reporting, could you test it in Pivot Table 2? This should not be an issue in the new plug-in.

**Comment by Artem-fb** [comment]
@junlincc  thank you for the answer. I'm not sure that I understand what is plug-in? I just have to update my version from 1.01 to 1.10 or install something additionally?

**Comment by rusackas** [comment]
Please consider adopting Pivot Table V2, and let us know if you see any similar issue there.

**Comment by rusackas** [comment]
Closing since this has gone silent for over a year now. Hopefully everyone's happy with Pivot Table V2.... we'll likely deprecate the legacy one before long!
