### ISSUE TITLE
Data not aligned (bad choice of font)

### ISSUE THREAD

**Issue by squalou** [apache/superset#14060]
## Screenshot

Using Superset 1.0.1

Here for dates fields : 

![image](https://user-images.githubusercontent.com/4623644/114230646-b0215880-9979-11eb-83e8-f5440b74f30c.png)

Here for some prices

![image](https://user-images.githubusercontent.com/4623644/114230724-ccbd9080-9979-11eb-9ac3-26838c6f3c34.png)

## Description

When analysing data in a table, one **expects** them to be nicely aligned.

It's especially the case regarding money amounts.

Fonts should be monospace.

**Comment by mohansaimandalapu** [comment]
Hi squalou

I am interested in solving this issue, this is my first  PR, can you explain how to solve this issue.

**Comment by squalou** [comment]
I did an ugly fix on my side, and it's probably NOT the way to go, nevertheless here's what I did.

in file `superset-frontend/stylesheets/less/variables.less` I removed 'Inter' font entirely

```
< @font-family-sans-serif: 'Inter', Helvetica, Arial;
---
> @font-family-sans-serif: Helvetica, Arial;
```

it works but ... it has effects everywhere. (which is fine on my setup)

**Comment by squalou** [comment]
Are there any update ?
I'm testing 1.2.0-rc2 with my patch, would be glad to get rid of it.

**Comment by rajpratyush** [comment]
can i take this issue up?

**Comment by rusackas** [comment]
@geido I think you took a look at this quite some time ago using the monospaced variant of Inter. Do you remember where that landed? I seem to recall the difficulty being around knowing/mapping which columns to which we should apply the styling/class

**Comment by geido** [comment]
@rusackas the fix was applied to the table in this PR https://github.com/apache/superset/pull/19668. There's probably more work to do to make sure this works fine everywhere but as far as I remember it should look good now in most places.

**Comment by rusackas** [comment]
Ok, closing this for now then... @squalou please feel free to open a fresh issue with updated specifics if we need to investigate this further! Thank you!

**Comment by squalou** [comment]
Great news of sort :)
Is there an easy way to know in which release this PR has landed ? (if it has already).

I remember trying 2.0.1-rc1 last October, it was not yet right.

**Comment by squalou** [comment]
I"ll sadly open a fresh issue :/

![image](https://user-images.githubusercontent.com/4623644/213417833-b0ea2afe-4206-4442-b2a9-0d6bc7b1470f.png)

**Comment by squalou** [comment]
I'll sadly have to open a fresh issue,
here is a 2.0.1 table with dates

![2023-01-19_11-2superset-2 0 2-misaligned](https://user-images.githubusercontent.com/4623644/213418045-8acf6276-1b8d-4468-80c4-49df512ec61b.png)
