### ISSUE TITLE
[Table][feedback needed] 'SHOW TOTALS' in Table chart

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14061]
**Is your feature request related to a problem? Please describe.**

We recently added SUM/total control along with other enhancement to table chart, 
however, not all aggregations can be or should be summed, like average, max and min. 
In the second screenshot below, when the SHOW TOTALS check box is enabla the Totals row shows an average of the first column for AVG, max of the second column for COUNT, and the max of the third column for MAX. which are all very confusing. 

<img width="1417" alt="Screen Shot 2021-04-09 at 1 15 47 PM" src="https://user-images.githubusercontent.com/67837651/114235991-d1f8ec00-9935-11eb-8381-6047412159d3.png">
<img width="1414" alt="Screen Shot 2021-04-09 at 1 24 38 PM" src="https://user-images.githubusercontent.com/67837651/114236871-1d5fca00-9937-11eb-934d-b742fa75900f.png">

**Describe the solution you'd like**
This was a known issue when we implement the enhancement, but there's no clear solution how we should approach it. 
we could either 
- add tooltip to the SHOW TOTALS checkbox to clarify some "Totals" would not make sense and allow users to use their best judgement. 
- make check box dynamic, only shows up on applicable aggregation/metrics.
- allow user to show total only for selected metics. 

**Community, please try this new feature out and let us know how you would like us to improve the table chart.** 

_appreciation to engineers who contributed to this enhanced, robust table viz. @villebro @ktmud @kgabryje_

**Comment by junlincc** [comment]
Also, if we want to keep the AVG function, i notice we treated N/A value as 0. not sure this is ideal. thoughts?

**Comment by pavlozt** [comment]
@junlincc 
1.  treating N/A as 0 it totally incorrect . Please don't do same mistakes again  ( #12962 ) 
2. it seems some strange things happened with sql alchemy and sums - #11658

**Comment by junlincc** [comment]
@pavlozt re: 1, thanks for the feedback that's what I thought as well :) 
cc @kgabryje @villebro

**Comment by zhaoyongjie** [comment]
I don't think it needs to change.

1. In industry, `Total` does not mean arithmetically sum, but worthy of column(dimension) aggregation.
For instance, `Max measure` in Tableau ground total:

![image](https://user-images.githubusercontent.com/2016594/115330432-9c21f600-a1c6-11eb-8c61-33b25bc56963.png)

cc: @junlincc

**Comment by junlincc** [comment]
Related https://github.com/apache/superset/issues/13847

**Comment by ktmud** [comment]
One bug report from our users:

<img width="1611" alt="Xnip2021-04-21_17-33-50" src="https://user-images.githubusercontent.com/335541/115638723-c60f1180-a2c7-11eb-8f5b-6af0a9b81dd1.png">

Per-column custom formatting is not applied to totals.

**Comment by mistercrunch** [comment]
For "show total" to be summing numeric fields regardless of whether the column is logically additive is totally ok. I believe that's what pivot tables do and what people expect.

`NULL != 0`!

**Comment by betodealmeida** [comment]
@junlincc we could always ask the user if the metric is additive:

1. If the user adds a metric explicitly to the dataset we can have a checkbox asking if the metric is additive.
2. For metrics defined on-the-fly with the "SIMPLE" tab we know if they're additive (`COUNT`, `SUM`) or not (`COUNT DISTINCT`, `AVG`, `MIN`, `MAX`).
3. For metrics defined on-the-fly under "CUSTOM SQL" we can have a checkbox asking the user.


 we can also have a checkbox in the metric configuration dialog asking if the metric is additive, and have it disabled for aggregation functions that we know are not additive, like `AVG` and enabled for those we know are additive. This would work for the

**Comment by junlincc** [comment]
moving comments here 

Hi, I has just learn Superset apache and I has one trouble
In Pivot Chart option, I chose:

Aggregation Function: Sum
Check Show Total
But in row All and column All are Max, not Sum
Please help me. Thanks a lots.

**Comment by kidbabyvu** [comment]
> moving comments here @Phuc0077 let's continue discussion.
> #14639
> 
> Hi, I has just learn Superset apache and I has one trouble
> In Pivot Chart option, I chose:
> 
> Aggregation Function: Sum
> Check Show Total
> But in row All and column All are Max, not Sum
> Please help me. Thanks a lots.

hi, I have stuck with this issue too,

when I tick on Show total checkbox with the Sum function, my expectations are the Total Column show the aggregation of the previous columns.

![image](https://user-images.githubusercontent.com/84488736/118915431-2345c380-b957-11eb-9032-2f0f2f911af8.png)

![image](https://user-images.githubusercontent.com/84488736/118915462-33f63980-b957-11eb-9975-269e4bbf204e.png)

btw, could you show me how to change the name of Column All

besides, when I try the other function, suggest avg, It couldn't show the average value.

tks

**Comment by junlincc** [comment]
thank you everyone, for feedback! 

@kidbabyvu please see video :) 

https://user-images.githubusercontent.com/67837651/118920959-2d7ea800-b8ec-11eb-9354-114c5423cf25.mov

**Comment by junlincc** [comment]
btw, changing column name/adding label really should be an instant change. we should have the functionality in column formatting section.

**Comment by lameapparition** [comment]
Hello, I'm new into Superset. Trying to move our analytics to this platform, but i met a fundamental problem as I see no possibility of making Total row correct for non-countable (or non-additive) metric, guess it's related to this topic
Example:
I have three metrics grouped by month:
1. "spend plan" – amount of money company was planning to spend
2. "spend fact"  – amount of money company actually spended
3. "spend rate" – ratio of spend fact and spend plan 
So, I created pivot table and added totals. "spend plan" and "spend fact" are ok – its totals are sums of all values
but for "spend rate" I also see sums of all values instead of ratio of "spend fact" and "spend plan" totals
<img width="1415" alt="image" src="https://github.com/apache/superset/assets/108183770/d47cbf45-407d-4555-84df-4038d97f2b12">
<img width="366" alt="image" src="https://github.com/apache/superset/assets/108183770/b20c64e4-526e-43f3-8b6c-b3f93e4f92b7">

Expected result (using Google Spreadsheets):
<img width="1176" alt="image" src="https://github.com/apache/superset/assets/108183770/fa0b9f10-79b9-42dc-b582-58935b16432c">
Maybe I'm missing something, hope to get help

**Comment by rusackas** [comment]
Closing this in favor of #25747. This one is a feature request rather than a bug. If this is relevant in current versions (currently 3.x) please open a new Ideas discussion for a feature request or a PR to address the problem.
