### ISSUE TITLE
superset new country map

### ISSUE THREAD

**Issue by SAVE-POlNT** [apache/superset#14079]
hello , i wanted to create a map for my country to add to the country maps 
the map is created and here is the result of it (Algeria)
![image](https://user-images.githubusercontent.com/44881216/114321989-2232a280-9b1e-11eb-9219-37da9f7445c2.png)
rather than recompiling the frontend , i changed the Germany geojson compiled file
i tested one with no internal polygons
and it worked normally

### Expected results
i'm expecting it to work normally and showing the full country map 

### Actual results
the result is that i get a giant rectangle surrounding my country 
![image](https://user-images.githubusercontent.com/44881216/114322094-b56bd800-9b1e-11eb-93bf-64fb52d90fdc.png)
algeria is situated at the right corner of the rectangle ans it is really small, i started removing some polygones , but nothing changed

#### How to reproduce the bug

try to export a geojson file with qgis and put it in a geojson file in assets folder

### Environment

- superset version: `0.999dev`
- python version: `python3.7`
- node is not installed it is a docker version

### Checklist

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.
- i found one talking about the uk , removing a polygon solved the problem , not for me

**Comment by zufolo441** [comment]
check that map SR is EPSG:4326 - WGS84

**Comment by SAVE-POlNT** [comment]
this is how my file starts 
![image](https://user-images.githubusercontent.com/44881216/114369586-d5cb7f00-9b7e-11eb-9a0b-164bf4e07c1c.png)
and this is the map SR
![image](https://user-images.githubusercontent.com/44881216/114369944-35c22580-9b7f-11eb-8016-b5b80cb55840.png)

i played around for like 8 hours with no success , i took the map of morroco , the learest to algeria and added one polygon from the algeria map that i created and the square appeared

**Comment by SAVE-POlNT** [comment]
i think i found where is the problem , the problem , i assume , was a small non finished segment , that causes this 
i think superset tried to limit the size of the area by finishing the non finished segment by a rectangle that takes a huge space 
thank you

**Comment by angel1369** [comment]
Hi @SAVE-POlNT , 
first, thank you for sharing your work simplified data.json.
when i call your map in php using amcharts 4 (map.js) i had a big square colored and one province "adrar" too small in the square?

how can i fixe it to show all province and fill the polygone with my color not square

**Comment by angel1369** [comment]
> i think i found where is the problem , the problem , i assume, was a small non finished segment, that causes this
> i think superset tried to limit the size of the area by finishing the non-finished segment by a rectangle that takes a huge space
> thank you
Hi @SAVE-POlNT , could you put the new map of Algeria  , i had some troubles with your simple-data.json 

PS: i call the map with amcharts 4 map  properties

**Comment by rukshn** [comment]
I don't think it's an non finished segment, facing similar issue for custom map in Sri Lanka, the geojsons taken from **https://data.humdata.org/dataset/geoboundaries-admin-boundaries-for-sri-lanka** does not seem to work and facing similar issue
