### ISSUE TITLE
# [Codecov](https://codecov.io/gh/apache/superset/pull/13974?src=pr&el=h1) Report

### ISSUE THREAD

**Issue by Terrica12** [apache/superset#14071]
# [Codecov](https://codecov.io/gh/apache/superset/pull/13974?src=pr&el=h1) Report
> Merging [#13974](https://codecov.io/gh/apache/superset/pull/13974?src=pr&el=desc) (c68c779) into [master](https://codecov.io/gh/apache/superset/commit/bfa6140b1596682800b9412939a6f076dda0519e?el=desc) (bfa6140) will **decrease** coverage by `0.11%`.
> The diff coverage is `57.14%`.

> :exclamation: Current head c68c779 differs from pull request most recent head 300769d. Consider uploading reports for the commit 300769d to get more accurate results
[![Impacted file tree graph](https://codecov.io/gh/apache/superset/pull/13974/graphs/tree.svg?width=650&height=150&src=pr&token=KsB0fHcx6l)](https://codecov.io/gh/apache/superset/pull/13974?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master   #13974      +/-   ##
==========================================
- Coverage   79.50%   79.39%   -0.12%     
==========================================
  Files         938      940       +2     
  Lines       47517    47593      +76     
  Branches     5939     5962      +23     
==========================================
+ Hits        37778    37786       +8     
- Misses       9618     9685      +67     
- Partials      121      122       +1     
```

| Flag | Coverage Δ | |
|---|---|---|
| cypress | `56.05% <35.71%> (-0.01%)` | :arrow_down: |
| hive | `80.46% <81.81%> (-0.01%)` | :arrow_down: |
| mysql | `80.73% <81.81%> (-0.01%)` | :arrow_down: |
| postgres | `80.77% <81.81%> (?)` | |
| presto | `?` | |
| python | `81.15% <81.81%> (-0.16%)` | :arrow_down: |
| sqlite | `?` | |

Flags with carried forward coverage won't be shown. [Click here](https://docs.codecov.io/docs/carryforward-flags#carryforward-flags-in-the-pull-request-comment) to find out more.

| [Impacted Files](https://codecov.io/gh/apache/superset/pull/13974?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [...rset-frontend/src/SqlLab/components/QueryTable.jsx](https://codecov.io/gh/apache/superset/pull/13974/diff?src=pr&el=tree#diff-c3VwZXJzZXQtZnJvbnRlbmQvc3JjL1NxbExhYi9jb21wb25lbnRzL1F1ZXJ5VGFibGUuanN4) | `66.66% <ø> (ø)` | |
| [...et-frontend/src/SqlLab/components/TableElement.jsx](https://codecov.io/gh/apache/superset/pull/13974/diff?src=pr&el=tree#diff-c3VwZXJzZXQtZnJvbnRlbmQvc3JjL1NxbExhYi9jb21wb25lbnRzL1RhYmxlRWxlbWVudC5qc3g=) | `89.02% <ø> (ø)` | |
| [.../nativeFilters/FilterBar/FilterSets/utils/index.ts](https://codecov.io/gh/apache/superset/pull/13974/diff?src=pr&el=tree#diff-c3VwZXJzZXQtZnJvbnRlbmQvc3JjL2Rhc2hib2FyZC9jb21wb25lbnRzL25hdGl2ZUZpbHRlcnMvRmlsdGVyQmFyL0ZpbHRlclNldHMvdXRpbHMvaW5kZXgudHM=) | `16.66% <0.00%> (ø)` | |
| [...erset-frontend/src/datasource/DatasourceEditor.jsx](https://codecov.io/gh/apache/superset/pull/13974/diff?src=pr&el=tree#diff-c3VwZXJzZXQtZnJvbnRlbmQvc3JjL2RhdGFzb3VyY2UvRGF0YXNvdXJjZUVkaXRvci5qc3g=) | `65.96% <ø> (ø)` | |
| [superset-frontend/src/common/components/Card.tsx](https://codecov.io/gh/apache/superset/pull/13974/diff?src=pr&el=tree#diff-c3VwZXJzZXQtZnJvbnRlbmQvc3JjL2NvbW1vbi9jb21wb25lbnRzL0NhcmQudHN4) | `20.00% <20.00%> (ø)` | |
| [.../src/explore/components/ControlPanelsContainer.tsx](https://codecov.io/gh/apache/superset/pull/13974/diff?src=pr&el=tree#diff-c3VwZXJzZXQtZnJvbnRlbmQvc3JjL2V4cGxvcmUvY29tcG9uZW50cy9Db250cm9sUGFuZWxzQ29udGFpbmVyLnRzeA==) | `94.63% <50.00%> (-2.72%)` | :arrow_down: |
| [superset/connectors/sqla/models.py](https://codecov.io/gh/apache/superset/pull/13974/diff?src=pr&el=tree#diff-c3VwZXJzZXQvY29ubmVjdG9ycy9zcWxhL21vZGVscy5weQ==) | `88.24% <81.81%> (-1.91%)` | :arrow_down: |
| [superset-frontend/src/common/components/index.tsx](https://codecov.io/gh/apache/superset/pull/13974/diff?src=pr&el=tree#diff-c3VwZXJzZXQtZnJvbnRlbmQvc3JjL2NvbW1vbi9jb21wb25lbnRzL2luZGV4LnRzeA==) | `100.00% <100.00%> (ø)` | |
| [...set-frontend/src/components/ListViewCard/index.tsx](https://codecov.io/gh/apache/superset/pull/13974/diff?src=pr&el=tree#diff-c3VwZXJzZXQtZnJvbnRlbmQvc3JjL2NvbXBvbmVudHMvTGlzdFZpZXdDYXJkL2luZGV4LnRzeA==) | `100.00% <100.00%> (ø)` | |
| ... and [15 more](https://codecov.io/gh/apache/superset/pull/13974/diff?src=pr&el=tree-more) | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/apache/superset/pull/13974?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/apache/superset/pull/13974?src=pr&el=footer). Last update [bfa6140...300769d](https://codecov.io/gh/apache/superset/pull/13974?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

_Originally posted by @codecov[bot] in https://github.com/apache/superset/issues/13974#issuecomment-814374670_

**Comment by amitmiran137** [comment]
is there a statement here?

**Comment by ManishKumarKeshri** [comment]
I am still facing this issue.
https://github.com/pravega/pravega/pull/5948
