### ISSUE TITLE
[Annotation] Annotations don't show up unless full time interval is included in chart

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#14085]
#### Description
If you use a Superset Annotation, using the Interval type, the annotation doesn't show up unless you include the full time interval in the chart. This means that annotations that impact a long time interval often won't show up. 

#### How to reproduce the bug & Screenshots
1. Create an annotation layer which impacts longer period - all data prior 03/09/2021. One of the events basically impacts all data prior to 3/9/2021. So user created the annotation in for 3/1/2020 (date of the first partition) to 3/9/2021. 

 2. When user applied this annotation layer to this chart, they expected to see two annotation events for the two events they created (screenshot from annotation layer not included). Instead, only the later annotation is on the chart. 
![Screen Shot 2021-04-12 at 10 10 44 AM](https://user-images.githubusercontent.com/61221714/114434071-70c05b00-9b77-11eb-8631-3cd06ff11aa2.png)
![Screen Shot 2021-04-12 at 10 11 16 AM](https://user-images.githubusercontent.com/61221714/114434073-728a1e80-9b77-11eb-8da4-63c62c0e0733.png)

3. When user expands the time range of the chart to go all the way back to 3/1/2020 (which was the first day of the first annotation), then they see both annotation layers on their chart.
![Screen Shot 2021-04-12 at 10 11 07 AM](https://user-images.githubusercontent.com/61221714/114434084-74ec7880-9b77-11eb-8c7e-bb6790ab223c.png)
![Screen Shot 2021-04-12 at 10 11 10 AM](https://user-images.githubusercontent.com/61221714/114434095-77e76900-9b77-11eb-94fd-ced75a1a1683.png)

#### Expected Behavior
The annotation layer should show up even if the start date of the annotation is not in range of the displayed chart. 

### Environment

master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
I believe @villebro fixed this one. Please confirm. 🙏

**Comment by zuzana-vej** [comment]
Yay It looks resolved to me thanks!
