### ISSUE TITLE
Dashboard SPA refactor broke basic functionality

### ISSUE THREAD

**Issue by amitmiran137** [apache/superset#14094]
The dashboard used to hide menu items for the dashboard and charts when removing permissions from your role like:
can_csv
can_explore
this stopped working after https://github.com/apache/superset/pull/13306 was merged

I believe that the new  HYDRATE_DASHBOARD action doesn't propagate as it should

### Expected results
permissions should effect menu items visibility

### Actual results
permissions should doesn't effect menu items visibility

#### Screenshots

https://user-images.githubusercontent.com/47772523/114509961-cad82380-9c3e-11eb-8d5e-6c5c188e3636.mov

#### How to reproduce the bug

1. Go to Admin role
2. remove can csv on superset and can explore on superset
3. go to a dashboard and refresh the page
4. check out for the menu items of explore and csv

### Environment

(please complete the following information):

- superset version: `master`
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by suddjian** [comment]
Thank you for catching this, and for the quick fix! Reviewing the PR first thing today.
