### ISSUE TITLE
Get chart SQL with API

### ISSUE THREAD

**Issue by supermarin1** [apache/superset#14097]
Is there any way to get SQL chart based on through the API?
If no - would be great and helpful to have it

![image](https://user-images.githubusercontent.com/24755510/114538112-a9396500-9c5b-11eb-9bf2-fee23d849cb4.png)

**Comment by villebro** [comment]
@supermarin1 can you explain in more detail what you want to do? Do you want a rendered chart via an API, or the SQL that's used to retrieve the data for the cart?

**Comment by supermarin1** [comment]
I'm interested in SQL that's used to retrieve the data for the chart

**Comment by maltoze** [comment]
![image](https://user-images.githubusercontent.com/18044730/114641659-1c4ae600-9d05-11eb-849d-2b4565f7b75f.png)

![image](https://user-images.githubusercontent.com/18044730/114641732-3c7aa500-9d05-11eb-823f-7fcb74f7b114.png)

Hope this can help you.

**Comment by villebro** [comment]
Thanks for the help @maltoze ! Closing for now as this is really a question, not a bug, and can be better addressed in Discussions.

**Comment by supermarin1** [comment]
created https://github.com/apache/superset/discussions/14134
