### ISSUE TITLE
Data too long for column 'type' at row 1

### ISSUE THREAD

**Issue by ddxdental** [apache/superset#14105]
As described in issue #5018 and #4271 this is still an problem.  I am working againt a MariaDB table that uses the ENUM type and pretty verbose ENUM options.  

Bumping the `type` column to `varchar(1024)` did it for me (with plenty of room to spare).

`ALTER TABLE `superset`.`table_columns` CHANGE `type` `type` varchar(64) DEFAULT NULL`

**Comment by rusackas** [comment]
Closing this since it's 2 years stale, but if you're still experiencing this in current versions of Superset, let's revisit for sure!
