### ISSUE TITLE
Installation Error - Docker-Compose Up on Apple M1 - superset-app exited with code 132

### ISSUE THREAD

**Issue by amruizva** [apache/superset#14104]
System Software Overview:

      System Version: macOS 11.2.3 (20D91)
      Kernel Version: Darwin 20.3.0

Superset version: Latest version as of 13/04/2021

Steps to reproduce error:

1. ```$ git clone https://github.com/apache/superset.git```
2.  ```$ cd superset```
3. ```$ git checkout latest```
4. ```$ docker-compose up```

![Screenshot 2021-04-13 at 10 07 19](https://user-images.githubusercontent.com/16844254/114519626-e3493d80-9c40-11eb-8945-6077411aa26e.png)

**Comment by junlincc** [comment]
https://github.com/apache/superset/issues/12697 

@amruizva let us know if the conversation helps?

**Comment by johnnyheineken** [comment]
@junlincc
I encountered the same error. 
the main problem is probably with qemu:
> qemu: uncaught target signal 4 (Illegal instruction) - core dumped

it is probably related to this issue: https://github.com/docker/for-mac/issues/5232
in short, as is written in the docker docs:
> However, attempts to run Intel-based containers on Apple Silicon machines under emulation can crash as qemu sometimes fails to run the container. In addition, filesystem change notification APIs (inotify) do not work under qemu emulation.
