### ISSUE TITLE
[chart]Treemap not rendering

### ISSUE THREAD

**Issue by lamb-russell** [apache/superset#14101]
Rendering tree map results in an error 

### Expected results

render a tree map

### Actual results

`Unexpected error
An error occurred while rendering the visualization: TypeError: t.data.name.lastIndexOf is not a function
`

#### Screenshots

![image](https://user-images.githubusercontent.com/79713964/114568841-7d5db580-9c42-11eb-95a3-641b55318084.png)

#### How to reproduce the bug

1. Explore a query from sql lab
2. change chart type to Treemap
3. set metrics and group by 
4. Run Query
5. See error

### Environment

(please complete the following information):

- superset version: 1.0.1
- python version: 3.7
- node.js version: not sure

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
i can't reproduce this issue consistently. could it because there's null value in the groupby column? @zhaoyongjie @villebro ?

https://user-images.githubusercontent.com/67837651/114637078-596b9580-9c7d-11eb-92fc-551d984e73fa.mov

**Comment by zhaoyongjie** [comment]
Hi @junlincc @lamb-russell 

Looks like when using a numeric column by `Groupby` raising this exception.

How to reproduce
- on the latest master branch
- Pick `Treemap` viz
- pick a `numeric column `to the `Groupby` pill

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/2016594/114640580-fe7c8180-9d02-11eb-8e6c-8e5ed96ffb16.png">

**Comment by andrewscarani** [comment]
I found that the issue was being caused on my end when one of the columns grouped-by had a NULL value. I think the Treemap visualization should be fixed to support NULL values.
