### ISSUE TITLE
[db specific] Big number aggregations show undefined in Athena 

### ISSUE THREAD

**Issue by jafournier** [apache/superset#14119]
Hi,

While drawing a basic big number chart, I got an `undified` output although data is a defined number (16 here) . Please see the screenshot below.

![Screenshot 2021-04-14 at 10 33 25](https://user-images.githubusercontent.com/16292862/114680797-d3e3f600-9d0d-11eb-8114-a88404beaef6.png)

I am experiencing this bug with athena datasets, and with all aggregation functions (MAX, SUM, MIN, MAX, AVG, COUNT_DISTINCT). No issues with postgres datasets though.

I am using the current latest image (`Digest:sha256:3d9c6413c0d4bf0f11feefbb2636d96cbafd1158dc6fade4a3a0970a69bf1d27`), and the version in the front interface is `0.999.0dev`.

Thanks

**Comment by junlincc** [comment]
@jafournier thanks for reporting! we currently don't have a good plan to support different drivers in all product aspects. If you have a solution already, we will make sure the PR is reviewed and merged.
