### ISSUE TITLE
superset-1.1.0 - helm install - getting 404

### ISSUE THREAD

**Issue by sathyendrasaran** [apache/superset#14141]
I installed superset 1.1.0 and the db is set to postgres, the installation succeded with no errors<br> 
but i am receving the error below and not able to get the live dashboard<br>
Stack:
EKS, alb, ingress controller, helm install

![image](https://user-images.githubusercontent.com/16977700/114743872-b5f8ae80-9d6a-11eb-83cf-22eb4b8ee51c.png)

**Comment by junlincc** [comment]
by live dashboard, you mean the sample dashboards?

**Comment by sathyendrasaran** [comment]
I mean the home page of the superset is not loading <br>
when i checked the backend i see the following error in the superset pod <br>
not sure if i have to configure something <br>
Now i checked the postgres pod as well and it has bunch of errors<br>
All other pods are fine<br>
Postgres logs below<br>
I am assuming there is an error in setup but not sure how to debug it <br>

![image](https://user-images.githubusercontent.com/16977700/114748087-2f929b80-9d6f-11eb-8935-4ee61d340ae7.png)

**Comment by betodealmeida** [comment]
@sathyendrasaran can you give more details how you're running Superset and how we can repro this?

**Comment by V1ki** [comment]
Same ; use Traefik as Ingress Controller
