### ISSUE TITLE
[dashboard] edit dashboard will automatically become owner and not able to self remove ownership in Dashboard properties

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#14157]
modify data dashboard properties will automatically become owner and then can not self remove ownership

### Expected results

can self remove dashboard ownership in dashboard properties

### Actual results

can not self remove dashboard ownership in dashboard properties

#### Screenshots

<img width="1600" alt="Screen Shot 2021-04-14 at 10 25 04 PM" src="https://user-images.githubusercontent.com/81597121/114818268-62895f00-9d70-11eb-8035-d0d277fa475a.png">

https://user-images.githubusercontent.com/81597121/114818323-7634c580-9d70-11eb-8cbd-0731f6e00615.mov

#### How to reproduce the bug

1. Go to dashboards
2. Click on edit icon on the right of a dashboards with owner (not you)
3. Change dashboard name in properties 
4. Save and refresh the list, will automatically become an owner of the modified dashboard
5. go back to properties to self remove ownership and save
6. refresh the list and ownership can not be removed

This seems a bug to me since any modification in dashboard properties will add ownership and then can not remove.

### Environment

- superset version: preset 2021.15.0 Development

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [Y] I have reproduced the issue with at least the latest released version of superset.
- [Y] I have checked the issue tracker for the same issue and I haven't found one similar.

https://user-images.githubusercontent.com/81597121/114818953-813c2580-9d71-11eb-939e-4f78fcfdf4c5.mov

**Comment by junlincc** [comment]
Depends on whether it's FE or BE issue.. Please self assign the task @kgabryje(FE) @zhaoyongjie (BE)

**Comment by michael-s-molina** [comment]
@villebro Closed in https://github.com/apache/superset/pull/15149
