### ISSUE TITLE
[dashboard] dashboard card view is not showing thumbnail in dashboard list

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#14158]
dashboard card view is not showing thumbnail in preset

### Expected results

dashboard card view will show thumbnail

### Actual results

dashboard card view is not showing thumbnail

#### Screenshots

<img width="1792" alt="Screen Shot 2021-04-14 at 10 49 05 PM" src="https://user-images.githubusercontent.com/81597121/114820541-00caf400-9d74-11eb-92c8-898c613a496d.png">

#### How to reproduce the bug

1. Go to 'Dashboards
2. Click on card view icon on the left corner  of the tool bar

### Environment

- superset version:  preset 2021.15.0 Development

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [Y] I have reproduced the issue with at least the latest released version of superset.
- [Y] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by nytai** [comment]
should be fixed by https://github.com/apache/superset/pull/14013
