### ISSUE TITLE
https://superset.apache.org/docs/intro has a dead link (404)

### ISSUE THREAD

**Issue by kelvin1794** [apache/superset#14160]
Link to docker compose is dead.

#### Screenshots

<img width="686" alt="image" src="https://user-images.githubusercontent.com/28013335/114848157-ff033e00-9e10-11eb-99a5-3397e3c2732b.png">

**Comment by junlincc** [comment]
it works perfectly fine from my end. do you mind checking in a different browser?

**Comment by kelvin1794** [comment]
> it works perfectly fine from my end. do you mind checking in a different browser?

I tried on Firefox and Chrome. Both didn't work.

It brings me to https://superset.apache.org/docs/docs/installation/installing-superset-using-docker-compose

We can notice that there are two `docs/` in the URL.
