### ISSUE TITLE
OAuth not working unless I have authlib and flask_oauthlib installed for superset 1.0.1

### ISSUE THREAD

**Issue by niteshb3495** [apache/superset#14165]
I was trying to implement Google OAuth with Superset 1.0.1. In the end, I found that the below packages must be installed for OAuth to work. 
```
flask_oauthlib
authlib
```

As the above modules are missing in the requirements, adding them will help people integrate the OAuth without any extra effort. 

I used the helm repo "stable" to install the superset. 

I used my customized values.yaml file to install superset with below command. 
```
helm install superset -f values.yaml stable/superset
```

**Comment by amitmiran137** [comment]
this is by design
you create a continuation dockerFile to install the dependencies you need on top of the base image

**Comment by niteshb3495** [comment]
Can we just add it somewhere in the notes? maybe a comment just above the OAuth configuration? If someone is new to the configuration, it takes time to debug the issue and solve the problem. I had been in the situation so very well aware of the trouble.

**Comment by samudurand** [comment]
Yes, and the docs need to have AdditionalRequirements section removed, since it's not part of the Helm charts anymore, and does not allow to install extra packages.

**Comment by Bonifacio-Oliveira** [comment]
The instructions here might be useful: https://github.com/apache/superset/issues/13445
