### ISSUE TITLE
[chart]Error loading graph when IS (NOT) NULL filter is present

### ISSUE THREAD

**Issue by dusatvoj** [apache/superset#14173]
`Table` chart created before upgrade to `1.1.0` but after upgrade there's error.

### Expected results

`Table` chart shown ok

### Actual results

Not working `Table` chart

#### Screenshots

![image](https://user-images.githubusercontent.com/11560794/114939076-389f6d80-9e40-11eb-8f70-76979fb229c5.png)

#### How to reproduce the bug

1. Open dashboard with already created `Table` chart
2. See error

### Environment

(please complete the following information):

- superset version: `1.1.0`
- python version: `3.8.7`
- node.js version: `v12.21.0`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Log:
```
Apr 15 21:02:42 node6 python3.8[1195778]: 'val'
Apr 15 21:02:42 node6 python3.8[1195778]: Traceback (most recent call last):
Apr 15 21:02:42 node6 python3.8[1195778]:   File "/usr/local/lib/python3.8/site-packages/superset/common/query_context.py", line 361, in get_df_payload
Apr 15 21:02:42 node6 python3.8[1195778]:     query_result = self.get_query_result(query_obj)
Apr 15 21:02:42 node6 python3.8[1195778]:   File "/usr/local/lib/python3.8/site-packages/superset/common/query_context.py", line 114, in get_query_result
Apr 15 21:02:42 node6 python3.8[1195778]:     result = self.datasource.query(query_object.to_dict())
Apr 15 21:02:42 node6 python3.8[1195778]:   File "/usr/local/lib/python3.8/site-packages/superset/connectors/sqla/models.py", line 1313, in query
Apr 15 21:02:42 node6 python3.8[1195778]:     query_str_ext = self.get_query_str_extended(query_obj)
Apr 15 21:02:42 node6 python3.8[1195778]:   File "/usr/local/lib/python3.8/site-packages/superset/connectors/sqla/models.py", line 772, in get_query_str_extended
Apr 15 21:02:42 node6 python3.8[1195778]:     sqlaq = self.get_sqla_query(**query_obj)
Apr 15 21:02:42 node6 python3.8[1195778]:   File "/usr/local/lib/python3.8/site-packages/superset/connectors/sqla/models.py", line 1080, in get_sqla_query
Apr 15 21:02:42 node6 python3.8[1195778]:     eq = utils.cast_to_num(flt["val"])
Apr 15 21:02:42 node6 python3.8[1195778]: KeyError: 'val'
Apr 15 21:02:42 node6 python3.8[1195778]: ERROR:superset.common.query_context:'val'
Apr 15 21:02:42 node6 python3.8[1195778]: Traceback (most recent call last):
Apr 15 21:02:42 node6 python3.8[1195778]:   File "/usr/local/lib/python3.8/site-packages/superset/common/query_context.py", line 361, in get_df_payload
Apr 15 21:02:42 node6 python3.8[1195778]:     query_result = self.get_query_result(query_obj)
Apr 15 21:02:42 node6 python3.8[1195778]:   File "/usr/local/lib/python3.8/site-packages/superset/common/query_context.py", line 114, in get_query_result
Apr 15 21:02:42 node6 python3.8[1195778]:     result = self.datasource.query(query_object.to_dict())
Apr 15 21:02:42 node6 python3.8[1195778]:   File "/usr/local/lib/python3.8/site-packages/superset/connectors/sqla/models.py", line 1313, in query
Apr 15 21:02:42 node6 python3.8[1195778]:     query_str_ext = self.get_query_str_extended(query_obj)
Apr 15 21:02:42 node6 python3.8[1195778]:   File "/usr/local/lib/python3.8/site-packages/superset/connectors/sqla/models.py", line 772, in get_query_str_extended
Apr 15 21:02:42 node6 python3.8[1195778]:     sqlaq = self.get_sqla_query(**query_obj)
Apr 15 21:02:42 node6 python3.8[1195778]:   File "/usr/local/lib/python3.8/site-packages/superset/connectors/sqla/models.py", line 1080, in get_sqla_query
Apr 15 21:02:42 node6 python3.8[1195778]:     eq = utils.cast_to_num(flt["val"])
Apr 15 21:02:42 node6 python3.8[1195778]: KeyError: 'val'
```

**Comment by junlincc** [comment]
@dusatvoj thanks for reporting. do you mind testing latest master see if this is still an issue? thanks!

**Comment by dusatvoj** [comment]
IDK how. I'm usually using `pip` installation :thinking: But I'm if you tell me how :grinning:

**Comment by nedvedad** [comment]
The error is resolved by removing "IS NOT NULL" condition from the filters. The chart worked just fine before the update.

![Screenshot 2021-04-17 at 16 44 23](https://user-images.githubusercontent.com/29985549/115116981-b4163180-9f9c-11eb-91a2-83a07b833758.png)

**Comment by rumbin** [comment]
I also noticed that IS (NOT) NULL Filters cause errors in version 1.0.1, but I haven't had the time for reporting it. I think that this bug is not related to any particular kind of chart, though.
Maybe you should consider updating/renaming this issue?!

In the meantime you can work around this issue by creating a custom filter that reads "(my_column is null) = true)" or so.

**Comment by dusatvoj** [comment]
@rumbin 
Better? :D

**Comment by rusackas** [comment]
@andrey-zayats took a look at this and was unable to reproduce the issue. I'm going to go ahead and remove the `validation:required` label and close the issue. If anyone sees this happening in Superset 2.0.x or later, or on `master`, we're open to revisiting this conversation, re-opening the ticket, or triaging a new Issue with updated context. Thank you!
