### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'index' - Export CSV on filter box

### ISSUE THREAD

**Issue by jerwen** [apache/superset#14189]
An error happens when trying to export a filter box to CSV.

### Expected results

My opinion would be to discard the Export CSV button for filter BOX since, it has never worked and no one seems to have ever required it.

### Actual results

An html page with an error message when clicking on the Export CSV button

#### Screenshots

<img width="1440" alt="Capture d’écran 2021-04-16 à 11 07 55" src="https://user-images.githubusercontent.com/20145870/115001583-117a8780-9ea4-11eb-9a9c-124767b130af.png">

#### How to reproduce the bug

1. Click on the Export CSV button of a filter box

<img width="340" alt="Capture d’écran 2021-04-16 à 11 12 44" src="https://user-images.githubusercontent.com/20145870/115002285-d7f64c00-9ea4-11eb-8b3a-f46ff8ec2477.png">

2. See error

<img width="1440" alt="Capture d’écran 2021-04-16 à 11 07 55" src="https://user-images.githubusercontent.com/20145870/115001583-117a8780-9ea4-11eb-9a9c-124767b130af.png">

### Environment

- docker image : `apache/superset:1.0.1`
- superset version: `1.0.1`
- python version: `3.7`
- node.js version: `unknown`

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
```
Traceback (most recent call last):
  File "/app/superset/views/base.py", line 181, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/utils/log.py", line 164, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/utils/cache.py", line 152, in wrapper
    return f(*args, **kwargs)
  File "/app/superset/views/utils.py", line 451, in wrapper
    return f(*args, **kwargs)
  File "/app/superset/views/core.py", line 618, in explore_json
    return self.generate_json(viz_obj, response_type)
  File "/app/superset/views/core.py", line 440, in generate_json
    viz_obj.get_csv(),
  File "/app/superset/viz.py", line 622, in get_csv
    include_index = not isinstance(df.index, pd.RangeIndex)
AttributeError: 'NoneType' object has no attribute 'index'
```
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.
An existing issue which has been closed due to inactivity : #7734 

### Additional context

RAS

**Comment by suddjian** [comment]
Could you provide some information on the use case for exporting a filter box to a CSV? There is a new Native Filters feature that will not use the filter box, and currently exporting a Native Filter to a CSV is not possible.

**Comment by jerwen** [comment]
Thank you for your answer.
My point is that there are no known use case at this time for exporting a filter box to a CSV. Thus my request to simply discard the option in the dropdown menu for filter box, so we can avoid irritating error message for our users who often click on that button.
