### ISSUE TITLE
Bulk selection option is not functional in "Card" view

### ISSUE THREAD

**Issue by KrupaVadher** [apache/superset#14185]
There is no presence of functionality to select any item in 'Card' view (Chart or Dashboard). 

### Expected results

UI should allow user to select the items in bulk selection mode in 'Card' view 

### Actual results

UI doesn't allow user to select the items in bulk selection mode in 'Card' view 

<img width="1426" alt="BulkSelection" src="https://user-images.githubusercontent.com/57817186/114984593-c0887600-9e46-11eb-9398-45f05b15081e.png">

#### How to reproduce the bug

1. Go to Charts from toolbar and select the 'Card' view
2. Click on 'Bulk Select' button from the top
3. UI will show '0 selected' but doesn't have checkboxes to select in bulk as shown in above screenshot

### Environment

(please complete the following information):

- superset version: commit# c9a755f25
- python version: `Python 2.7.16`
- node.js version: `v13.11.0`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@lilykuang @nytai ^ 🙏

**Comment by lilykuang** [comment]
@KrupaVadher thank you for your feedback. There is no checkboxes for card view,  user can click on each individual card for bulk select, see the video below
https://www.loom.com/share/134e046ea14742bb9ec69410d0820033
cc @junlincc

**Comment by lilykuang** [comment]
This issue doesn't seems like a bug, I will close it. Feel free to reopen if there's any concern.

**Comment by KrupaVadher** [comment]
Thank you, @lilykuang , for your comments and clarification. This surely isn't a bug :D
