### ISSUE TITLE
Non Persistent selection after changing sort criteria

### ISSUE THREAD

**Issue by KrupaVadher** [apache/superset#14186]
UI does not retain the selection of the items (chart or dashboard) in the list view after a user changes sort parameters.

### Expected results

Selection should persist throughout all the sort parameter changes 

### Actual results

All selected items change their state back to unselected 

https://user-images.githubusercontent.com/57817186/114986649-1b22d180-9e49-11eb-82ad-db378c98451e.mov

#### How to reproduce the bug

1. Go to Dashboards from the toolbar
2. Click on 'Bulk Select' button from the top
3. Select the dashboard items from the list
4. Sort by any list parameter (e.g: 'Title', 'Modified by')
5. Selected items will change their state back to the unselected lists

### Environment

- superset version: commit# `c9a755f25`
- python version: `Python 2.7.16`
- node.js version: `v13.11.0`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by Shazad-khan** [comment]
This issue has been already fixed and merged to the main branch so please close this ticket
