### ISSUE TITLE
OAuth configuration does not trigger login via custom oauth server

### ISSUE THREAD

**Issue by pr0base** [apache/superset#14206]
1. Followed instruction in Wiki to complete OAuth2 setup with CustomSecurityManage. Login page shows icon for external login but click action does not redirect. 
2. Further when trying to bypass the login click by calling manually http://myoauthserver/OAuth2/Authorize?client_id=<myclientId>&redirect_uri=http%3A%2F%2F<supersethost>%3A8088%2Foauth-authorized%2F<myservice>&scope=Api/User&response_type=code

### Expected results

1. When i click the oauth login button, i am redirect to the oauth server
2. When I come back fromt he oauth with a code the token is requested

### Actual results

1. click on oauth provider icon is ignored by /login
2. The token request is issued but only the grant_type & code are part of the request body. 

### Environment

https://github.com/apache/superset/commit/c7112d1c48205eceda97968cded63e40c83cf86e
docker
ubuntu 16

- superset version: `0.999`
- python version: `docker`
- node.js version: `docker`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

When returing from oauth i receive in the browser 
{"errors": [{"message": "Expecting value: line 5 column 1 (char 8)", "error_type": "GENERIC_BACKEND_ERROR", "level": "error", "extra": {"issue_codes": [{"code": 1011, "message": "Issue 1011 - Superset encountered an unexpected error."}]}}]}

Logs 
```
superset_app             | 2021-04-16 20:05:04,926:DEBUG:authlib.integrations.base_client.base_app:Retrieve temporary data: {'code': 'ltOJ!IAAAAM9lBRocy5aM9W6IzLMV2fHEqTLdtFErfjYuCR0k5Ljn8QAAAAE359NolvtIuSgCtE62S7-3CyqAqqvLcvozrVJwuX-MzrS1pkamm2M7_0krZsdrPE-H-NGOm6-97uqssdDBMrUw358UyAkJ7t3YeN9llIqf_e5Rl8FHqSQM1cT1mpwxv-1SEzLR5F1PrQM9GWiATBMZRt0Wdh2zAZJL9coCqH6J9z-3Xx-cgv4Ay7YceiQAkwRrMKoIj9v9kDFRdTxuXxt-l-UY1xNySJMcHxhlX23V_JrtA-UhD7IWz-OAZG1paZvJovC9ipq14u-v3raGU7zMqgQFcUe1H7PSJVlkuTLwk-hoHabcb4JHaxGp9KnSk28'}
superset_app             | 2021-04-16 20:05:04,928:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): oauth.m-anage.com:443
superset_app             | 2021-04-16 20:05:04,964:DEBUG:urllib3.connectionpool:https://....:443 "POST /OAuth2/Token HTTP/1.1" 200 8495
superset_app             | 2021-04-16 20:05:04,967:WARNING:superset.views.base:Expecting value: line 5 column 1 (char 8)
superset_app             | 172.50.200.10 - - [16/Apr/2021 20:05:04] "GET /oauth-authorized/myservice?code=ltOJ%21IAAAAM9lBRocy5aM9W6IzLMV2fHEqTLdtFErfjYuCR0k5Ljn8QAAAAE359NolvtIuSgCtE62S7-3CyqAqqvLcvozrVJwuX-MzrS1pkamm2M7_0krZsdrPE-H-NGOm6-97uqssdDBMrUw358UyAkJ7t3YeN9llIqf_e5Rl8FHqSQM1cT1mpwxv-1SEzLR5F1PrQM9GWiATBMZRt0Wdh2zAZJL9coCqH6J9z-3Xx-cgv4Ay7YceiQAkwRrMKoIj9v9kDFRdTxuXxt-l-UY1xNySJMcHxhlX23V_JrtA-UhD7IWz-OAZG1paZvJovC9ipq14u-v3raGU7zMqgQFcUe1H7PSJVlkuTLwk-hoHabcb4JHaxGp9KnSk28 HTTP/1.1" 500 -
superset_app             | 2021-04-16 20:05:04,968:INFO:werkzeug:172.50.200.10 - - [16/Apr/2021 20:05:04] "GET /oauth-authorized/myservice?code=ltOJ%21IAAAAM9lBRocy5aM9W6IzLMV2fHEqTLdtFErfjYuCR0k5Ljn8QAAAAE359NolvtIuSgCtE62S7-3CyqAqqvLcvozrVJwuX-MzrS1pkamm2M7_0krZsdrPE-H-NGOm6-97uqssdDBMrUw358UyAkJ7t3YeN9llIqf_e5Rl8FHqSQM1cT1mpwxv-1SEzLR5F1PrQM9GWiATBMZRt0Wdh2zAZJL9coCqH6J9z-3Xx-cgv4Ay7YceiQAkwRrMKoIj9v9kDFRdTxuXxt-l-UY1xNySJMcHxhlX23V_JrtA-UhD7IWz-OAZG1paZvJovC9ipq14u-v3raGU7zMqgQFcUe1H7PSJVlkuTLwk-hoHabcb4JHaxGp9KnSk28 HTTP/1.1" 500 -
```

superset config
```import logging
import os

from cachelib.file import FileSystemCache

from flask import Flask
from flask_appbuilder.security.manager import AUTH_OID, AUTH_REMOTE_USER, AUTH_DB, AUTH_LDAP, AUTH_OAUTH
from superset.security import SupersetSecurityManager
import logging
from flask_appbuilder import SQLA, AppBuilder

FEATURE_FLAGS = {
    'DASHBOARD_NATIVE_FILTERS': True,
    'ROW_LEVEL_SECURITY': True,
    'ENABLE_TEMPLATE_PROCESSING': True,
}
AUTH_TYPE = AUTH_OAUTH
OAUTH_PROVIDERS = [
    {   'name':'myservice',
        'token_key':'access_token', # Name of the token in the response of access_token_url
        'icon':'fa-address-card',   # Icon for the provider
        'remote_app': {
            'client_id':'super id',  # Client Id (Identify Superset applica$
            'client_secret':'super secret', # Secret for this Client Id$
            'client_kwargs':{
                'scope': 'Api/User'               # Scope for the Authorization
            },
            'access_token_method':'POST',    # HTTP Method to call access_token_url
#            'access_token_params':{        # Additional parameters for calls to access_token_url
#                'client_id':'myClientId'
#            },
#            'access_token_headers':{    # Additional headers for calls to access_token_url
#                'Authorization': 'Basic Base64EncodedClientIdAndSecret'
#            },
            'request_token_url': None,
            'base_url':'https://..../api/custominterfaces/oauth/UserData/UserData',
            'access_token_url':'https://.../OAuth2/Token',
            'authorize_url':'https://.../OAuth2/Authorize'
        }
    }
]

from myservice_sss_security_manager import CustomSsoSecurityManager
CUSTOM_SECURITY_MANAGER = CustomSsoSecurityManager
```

Custom Security Manager
```

from superset.security import SupersetSecurityManager

class CustomSsoSecurityManager(SupersetSecurityManager):

    def oauth_user_info(self, provider, response=None):
        logging.debug("Oauth2 provider: {0}.".format(provider))
        if provider == 'myservice':
            # As example, this line request a GET to base_url + '/' + userDetails with Bearer  Authentication,
    # and expects that authorization server checks the token, and response with user details
            me = self.appbuilder.sm.oauth_remotes[provider].get('userDetails').data
            logging.debug("user_data: {0}".format(me))
            return { 'name' : me['firstname'], 'email' : me['email'], 'id' : me['id'], 'username' : me['email'], 'first_name': me['firstname'], 'last_name': me['surname'] }
```

Thanks for your support.

**Comment by junlincc** [comment]
@nytai @dpgaspar 🙏

**Comment by dpgaspar** [comment]
@pr0base difficult to know the root cause since this seems like a custom OAuth provider, the error `Expecting value: line 5 column 1 (char 8)` can you check if that is thrown from `oauth_user_info`?

**Comment by pr0base** [comment]
@dpgaspar thanks for your followup.
The error does not happing with the custom implementation as far as I can tell. I added with my little python knowledge a try/except block as

`from superset.security import SupersetSecurityManager

class CustomSsoSecurityManager(SupersetSecurityManager):

    def oauth_user_info(self, provider, response=None):
        try:
            logging.debug("Oauth2 provider: {0}.".format(provider))
            if provider == 'providername':
                # As example, this line request a GET to base_url + '/' + userDetails with Bearer  Authentication,
                # and expects that authorization server checks the token, and response with user details
                me = self.appbuilder.sm.oauth_remotes[provider].get('userDetails').data
                logging.debug("user_data: {0}".format(me))
                return { 'name' : me['firstname'], 'email' : me['email'], 'id' : me['id'], 'username' : me['email'], 'first_name': me['firstname'], 'last_name': me['surname'] }
        except:
            e = sys.exc_info()[0]
            logging.error("CustomSsoSecurityManager - Error: {0}".format(e))
`
in the logs i can not see a message.

The error is happing when I start the OAuth flow manually via https://myOAuthServer/OAuth2/Authorize?client_id=60A62F84-28D1-458D-80ED-D350893C1940&redirect_uri=http%3A%2F%2F172.50.20.10%3A8088%2Foauth-authorized%2Fprovidername&scope=Api/User&response_type=code

See 
![image](https://user-images.githubusercontent.com/33983292/115720505-6c691e80-a37d-11eb-81f9-08a6d807b378.png)

When looking into our backend infrastructure I see superset requesting the token, but the request is declined because parameters are missing on the body to request the token.
![image](https://user-images.githubusercontent.com/33983292/115721034-eb5e5700-a37d-11eb-8e1e-ce8a94956255.png)

Working example to retrieve the token issued via Postman looks like
![image](https://user-images.githubusercontent.com/33983292/115722512-5bb9a800-a37f-11eb-8c5b-f2173749b973.png)

Comparing the two scenarios the Token Request issued does not include the values for

redirect_uri, client_id & client_secret.

**Comment by pr0base** [comment]
token request is now working. the click is working on the login page when i first click on my custom icon and then select sign in
![image](https://user-images.githubusercontent.com/33983292/115867323-3f7b4100-a43b-11eb-9e8c-7f300045873d.png)

No I receive the following error 
`{"errors": [{"message": "argument of type 'NoneType' is not iterable", "error_type": "GENERIC_BACKEND_ERROR", "level": "error", "extra": {"issue_codes": [{"code": 1011, "message": "Issue 1011 - Superset encountered an unexpected error."}]}}]}`

which reflects on the superset logs as 

`
CTNVYh75SZf7seA2Ncy8vusRYondT6FHrWB8QAAAAEcBuJO1CdpP9CM31FMvY6y1rUt8og-yRnCte2lvb5kg67aK1MpO_EbyCSDiIo1HhBdRbRfHQvbAgS1EvcUFU0nMa-wFGSEkg8e8Ddzfh8l3H948xVQgdvCY-vAdFAum3LA5YRjnoPtL4EtGJ_L95EB-wX0MvE8eOj9Db0NTlfHRXUYG9ub90A5xk7tQr4dqSb-CoXN0NHp2lHBmOUK9BwjcoXLMJIBzkkr4179msai3Qy2qnONAt3_tdlEldVhlJACVmlvib61VlXXM3yLBOm5b7akRVKCcZ1AsW91yDPHBbTSf07tVu0A2aTVSHfyojE', 'state': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuZXh0IjpbIiJdfQ.fdfto7RZFzoca-BIwMaXI9t-jsGjhSPMH_ltWoj85-Y', 'redirect_uri': 'http://172.50.20.10:8088/oauth-authorized/myprovider'}
superset_app             | 2021-04-23 11:53:25,785:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): myprovider:443
superset_app             | 2021-04-23 11:53:26,737:DEBUG:urllib3.connectionpool:https://myprovider:443 "POST /OAuth2/Token HTTP/1.1" 200 942
superset_app             | 2021-04-23 11:53:26,740:DEBUG:root:Oauth2 provider: myprovider.
superset_app             | 2021-04-23 11:53:26,740:ERROR:root:CustomSsoSecurityManager - Error: <class 'requests.exceptions.MissingSchema'>
superset_app             | 2021-04-23 11:53:26,741:WARNING:superset.views.base:argument of type 'NoneType' is not iterable

`

So now the error is clearly in my custom security manager. Currently reviewing.

**Comment by pr0base** [comment]
Ok, now working. Sorry but my Python knowledge was to limited to understand the dependencies in play.

I changed my custom auth handler as
```import sys
import logging
import requests
from flask_appbuilder import SQLA, AppBuilder

logger = logging.getLogger()

from superset.security import SupersetSecurityManager

class CustomSsoSecurityManager(SupersetSecurityManager):

    def oauth_user_info(self, provider, response=None):
        try:
            logging.debug("Oauth2 provider: {0}.".format(provider))
            if provider == 'wwwmanagecom':
                # As example, this line request a GET to base_url + '/' + userDetails with Bearer  Authentication,
                # and expects that authorization server checks the token, and response with user details
                res = self.appbuilder.sm.oauth_remotes[provider].get('my userinfo info endpoint')
                logging.info(" {0}".format(res))
                res.encoding = 'utf-8'
                if res.status_code != 200:
                  logger.error('Failed to obtain user info: %s', res.text)
                  return
                logging.info("user_data: {0}".format(res.json()))
                lUserInfo = res.json()
                return { 'name' : lUserInfo['firstname'], 'email' : lUserInfo['email'], 'id' : lUserInfo['id'], 'username' : lUserInfo['em$
        except:
            e = sys.exc_info()[0]
            logging.error("CustomSsoSecurityManager - Error: {0}".format(e))
```
Changes that mattered
* The userinfo endpoint needs to be set here. I am not are how to access the base_url setup in superset_config.py
* Reviewed the repsonse object documentation and found there is no data attribute. text and json() work nicely

For the first topic in regards to the click using http://172.50.20.10:8088/login/myprodivder?next= directly solves the issue that I have to click on the buttons.

Thank you in any case for hand holding :)
