### ISSUE TITLE
Docker image apache/superset:1.1.0 doesn´t start the web server

### ISSUE THREAD

**Issue by lrbsantos** [apache/superset#14210]
I tried to use the image `apache/superset:1.1.0`, but it seems that it doesn´t start the web server (UI).

### Expected results

Access the SuperSet UI via browser.

### Actual results

The Superset UI is unreachable.

#### Screenshots

None.

#### How to reproduce the bug

$ docker run -d -p 8080:8088 --name superset apache/superset:1.1.0

$ docker exec -it superset superset fab create-admin \
                   --username admin \
                   --firstname Superset \
                   --lastname Admin \
                   --email admin@superset.com \
                   --password admin

$ docker exec -it superset superset db upgrade

$ docker exec -it superset superset load_examples

$ docker exec -it superset superset init

Try Login and take a look -- navigate to http://localhost:8080/login/ -- u/p: [admin/admin]

### Environment

(please complete the following information):

- superset version: `1.1.0`
- docker image: `apache/superset:1.1.0`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

This issues doesn't occur in `latest` tag .

**Comment by qlands** [comment]
That Docker image using the docker run you provided runs Superset in port 8080. If you remove the current container and do:

`sudo docker run -p 8080:8080 --name superset apache/superset:1.1.0`

Superset will be available at http://localhost:8080/login/

**Comment by lrbsantos** [comment]
Thanks @qlands ... now it´s all working fine.
