### ISSUE TITLE
Couldn't add clickhouse databases

### ISSUE THREAD

**Issue by Michaelsky0913** [apache/superset#14229]
I try to add clickhouse database, but I got an error: DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name (version 21.3.4.25 (official build))
![image](https://user-images.githubusercontent.com/40595864/115187067-4d685380-a115-11eb-9dfc-71c263cb342e.png)

        I think the result it's not true, because I try to use a linux shell command to connect my clickhouse database, it succeed! The command is ```echo 'SELECT 1' | curl 'http://192.168.13.251:8123/' -udefault:123qwe --data-binary @-```. Look the picture:
![image](https://user-images.githubusercontent.com/40595864/115190705-0715f300-a11b-11eb-9f44-0ffd7f86e69c.png)

### Expected results

what you expected to happen.
Successfully add clickhouse database

### Actual results

what actually happens.
     I got an error: DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name (version 21.3.4.25 (official build))
    But I think the result it's not true.

#### Screenshots

![image](https://user-images.githubusercontent.com/40595864/115187058-47727280-a115-11eb-9bd9-1937139f237d.png)

#### How to reproduce the bug

1. Go to fronted page
2. Click on "Data -> Databases -> +DATABASE"
3. Type DATABASE NAME: clickhouse, and SQLALCHEMY URI: clickhouse://default:123qwe@192.168.13.251:8123/dbtest

### Environment

(please complete the following information):

- superset version: `superset version`
0.999.0dev
- python version: `python --version`
Python 3.7.9
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I builded the docker image with docker-compose use the latest branch.

**Comment by Michaelsky0913** [comment]
If I don't set password for user default, everything is ok. otherwise, the superset could not add clickhouse database.

**Comment by Michaelsky0913** [comment]
sorry, I use a wrong linux command to test, the correct is:
```
echo 'SELECT 1' | curl 'http://localhost:8123/' -udefault:123qwe --data-binary @-
```
![image](https://user-images.githubusercontent.com/40595864/115190606-e2218000-a11a-11eb-8308-d1d1d322460a.png)

**Comment by HeinzMayer** [comment]
The driver "sqlalchemy-clickhouse" doesn't work if the default user has a password 

Workaraound
install "pip install infi.clickhouse_orm==1.0.4"

I recommend to use the driver "clickhouse-sqlalchemy"

**Comment by jcalhinho** [comment]
try to go in sqlalchemy_clickhouse/connector.py 
in line 104, try to comment "database._send = _send" and restart superset.

**Comment by Michaelsky0913** [comment]
> try to go in sqlalchemy_clickhouse/connector.py
> in line 104, try to comment "database._send = _send" and restart superset.

thanks, it's ok now.

**Comment by Michaelsky0913** [comment]
> try to go in sqlalchemy_clickhouse/connector.py
> in line 104, try to comment "database._send = _send" and restart superset.

thanks, it's ok now.
