### ISSUE TITLE
Standardize permissions and executions on MySQL schemata: Char %60 (`)

### ISSUE THREAD

**Issue by qlands** [apache/superset#14233]
Current permissions on MySQL schemata do not include character %60 (`) but SuperSet uses such character in the Preview option of SQL Lab. Therefore even if a user has access to a schema the preview option will fail due to permissions. 

Bug present on SuperSet 1.1.0 installed from PyPi

**Comment by qlands** [comment]
This happens with both mysqlclient and PyMySQL drivers.

**Comment by junlincc** [comment]
@dpgaspar may be able to help answer 🙏

**Comment by dpgaspar** [comment]
@qlands I was able to reproduce, possible bug

**Comment by codenamelxl** [comment]
https://github.com/apache/superset/blob/3456dd571ca705699766473e55ededd36c6f4dc7/superset/sql_parse.py#L212

This uses sqlparse.sql.remove_quotes() which does not remove backtick `` ` ``
https://github.com/andialbrecht/sqlparse/issues/628

Maybe can override that function or send a PR to sqlparse instead.

**Comment by qlands** [comment]
This has been fixed in sqlparse 0.4.3 but testing is required to check if sqlparse 0.4.3 does not break things

**Comment by rusackas** [comment]
It seems we're using sqlparse 0.4.3, so I'm going to _optimistically_ close this as resolved. If anyone still sees an issue (particularly in Superset > 1.5.2), I'm more than happy to re-open this and get more eyes on it!
