### ISSUE TITLE
How to Single logout in Superset

### ISSUE THREAD

**Issue by CaptainHoangLe** [apache/superset#14239]
I have a SSO server integrated to superset . I have an api check access token is valid or not. I want to logout in main server making logout in superset. However , i don't know when and where i can call this api . So , Anyone please help me. I am looking forward to hearing from you.
Thanks all

**Comment by dpgaspar** [comment]
@CaptainHoangLe this depends on your specific implementation, is the authentication still being made with a cookie?

**Comment by CaptainHoangLe** [comment]
> this depends on your specific implementation, is the authentication still being made with a cookie?

I solved my problem with  @app.before_request and  @app.after_request. Thank you very much for your care

**Comment by dpgaspar** [comment]
nice! going to close
