### ISSUE TITLE
[Explore]can not reopen and edit ad-hoc filter in drag and drop mode

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14242]
When "ENABLE_EXPLORE_DRAG_AND_DROP": True, user can not click the dropped filter value to reopen and edit. 
see video. User has to delete filter and recreate if change is desired. 

https://user-images.githubusercontent.com/67837651/115349116-4c144680-a168-11eb-8f79-7c0291a55d4f.mov

cc: @kgabryje 🙏

**Comment by kgabryje** [comment]
On it

**Comment by junlincc** [comment]
resolved 🙏 @kgabryje
