### ISSUE TITLE
[Native Filters] Hardcoded height for native filters is 20px

### ISSUE THREAD

**Issue by MatanBobi** [apache/superset#14247]
I'm trying to implement my custom plugin as a native filter but it looks like the `height` defined for every native filter is `20px`, unlike the correct height when the plugin is defined in the dashboard.

Here's the relevant code:
https://github.com/apache/superset/blob/8ef572a4121ffd2fec6f64d0a053218dbf98308a/superset-frontend/src/dashboard/components/nativeFilters/FilterBar/FilterControls/FilterValue.tsx#L147

This is a cosmetic issue but also a bug so I wasn't sure how to label it.

### Expected results

My custom plugin in the filters bar should have the correct height:
![image](https://user-images.githubusercontent.com/12711091/115420208-a1516600-a203-11eb-8af4-d77d2868f718.png)

### Actual results

The height defined is `20px`:
![image](https://user-images.githubusercontent.com/12711091/115420312-b5956300-a203-11eb-885f-83c3e9b34154.png)

#### How to reproduce the bug

1. Create a custom plugin with a height higher than `20px` and try to implement it as a native filter.

### Environment

(please complete the following information):

- superset version: `master`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

I'm available to help with anything needed :)

**Comment by Ayushsunny** [comment]
Hello @MatanBobi I would like to work in issue

**Comment by MatanBobi** [comment]
Hi @Ayushsunny, I'm not managing this repo, I think @rusackas is the one to ask :)

**Comment by junlincc** [comment]
@Ayushsunny sorry for the late response, we are implemented new modal design, which will cover this change. thank you for volunteering, and feel free to pick up some other good first issue :)
