### ISSUE TITLE
[Dashboard][tabs]Top level tabs can't be added as a tab component anymore

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14254]
### Expected results
User should be able to add top level tabs to the dashboard. The previous top level tab UI looks below, open any sample tabbed dashboard with tabs to verify. 

<img width="2040" alt="Screen Shot 2021-04-20 at 2 13 48 PM" src="https://user-images.githubusercontent.com/67837651/115465023-cbdef700-a1e2-11eb-8cc4-68b02d0006de.png">

### Actual results
When user create a new dashboard, and add a tab component, it doesn't goes to the top level anymore. 
Though UI changed, the functionality is not being affected.  
<img width="1660" alt="Screen Shot 2021-04-20 at 2 14 39 PM" src="https://user-images.githubusercontent.com/67837651/115465118-f2049700-a1e2-11eb-921f-b37574c4eeb1.png">

Not sure which recent change caused it. There might be other unknown minor behavior changes in this area, so worth investigating. 

#### How to reproduce the bug

https://user-images.githubusercontent.com/67837651/115465564-a999a900-a1e3-11eb-9ba0-f12854bb6643.mov

1. Go to 'Dashboards' and create new
2. Add a tab component 
3. See it no longer goes to the dashboard top level

cc @amitmiran137 @suddjian

**Comment by graceguo-supercat** [comment]
ping @junlincc this is an important feature regression for over 2 week. could someone prioritize this?

**Comment by mistercrunch** [comment]
It also appears like there is no way to remove a tabs component from a dashboard, the like trashcan icon just doesn't show while in edit mode

**Comment by rusackas** [comment]
Done!
