### ISSUE TITLE
Share Dashboard / chart  to specific users with only read access

### ISSUE THREAD

**Issue by Sreekrishnanchidambaram** [apache/superset#14260]
We are currently amidst a situation, where we want our Dashboard/chart owners to share their dashboard to  only a specific set of user, to whom the owner decides to share it with (also some sort of audit for the owners to know who and all have access to dashboard ) .  

Version: 0.37.2 
Deployed: Google Kubernetes engine & on prem
Authentication: Oauth
Role: Custom role for all normal users  (Gamma + sql lab role)
Database: Connection to presto only
Meta store : Postgres (stand alone outside Gke)

Notes : Each user have their own  unique database connection to the same presto . Hence the data source permissions for charts are assigned manually for now . We need to automate the permission .

Primary concern :  The user should to whom the dashboard is shared should only have read access . also some sort of audit for the owners to know who and all have access to dashboard

**Comment by junlincc** [comment]
@Sreekrishnanchidambaram 
https://github.com/apache/superset/issues/10408 will be a better thread to discuss this request. would you mind commenting in the SIP? :)
