### ISSUE TITLE
[Chart edition][Dataset][Search] The list of available datasets is incomplete

### ISSUE THREAD

**Issue by ValentinC-BR** [apache/superset#14262]
When using the "Change dataset" feature, the list of datasets is incomplete.

### Expected results

There should either be a pagination or a way to filter by datasource, dataset type, etc... (or both)

### Actual results

I see an incomplete list, and I can't filter precisely enough to see my dataset (many dataset have the same keywords, especially the virtual ones)

#### Screenshots

_I can't post a screenshot here, as it contains names of our customers_

#### How to reproduce the bug

0. Make sure you have many datasets with the same names (eg. "user_account", user_account_Valentin_1", etc...)
1. Open a chart in edition (actually, there must be the same issue in creation)
2. Click on '"Change dataset"
3. Type the name of your dataset (eg. "user_account")
4. See error : If your dataset was the oldest one, it won't appear in the list

### Environment

(please complete the following information):

- superset version: 1.0.1
- python version: 3.7.9
- node.js version: doesn't apply, I run on Kubernetes, using gunicorn as server
- source : Athena

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

/

**Comment by junlincc** [comment]
@ValentinC-BR thanks for reporting, this is a known issue, and we have plan to improve it but may not be soon enough. Feel free to open a PR if it's urgent.

**Comment by junlincc** [comment]
<img width="582" alt="Screen Shot 2021-06-03 at 3 25 20 PM" src="https://user-images.githubusercontent.com/67837651/120719999-23c67a00-c480-11eb-8a4f-0fed83f8233b.png">

Related request: show all datasets in list view dropdown
