### ISSUE TITLE
There is no option in TIME GRAIN

### ISSUE THREAD

**Issue by ljclour** [apache/superset#14263]
I haved successful connect **DB2** and added a database  yet. When i use a dataset to create a line chart,there is no option in **TIME GRAIN**.Is anything wrong?
![TIME GRAIN](https://user-images.githubusercontent.com/45123712/115514238-7b38ce00-a2b6-11eb-9087-29947bdfc56a.png)

**Comment by junlincc** [comment]
Hi @ljclour We may not support Time grain in DB2 yet, I'm not sure. Contribution from the community is welcome! :) 

cc @cabo40

**Comment by ljclour** [comment]
> Hi @ljclour We may not support Time grain in DB2 yet, I'm not sure. Contribution from the community is welcome! :)
> 
> cc @cabo40
Thanks for the reply!If it does not support DB2,i haved to choose another way to fit it.

**Comment by villebro** [comment]
@ljclour what does your connection string look like, specifically the part before `://`?

**Comment by srinify** [comment]
@junlincc it looks like we actually *do* support time grains for db2. You can tell by the presence of `_time_grain_expressions` dictionary in `db2.py` but no idea if they actually work!

https://github.com/apache/superset/blob/master/superset/db_engine_specs/db2.py

But just for future reference :D

**Comment by villebro** [comment]
I seem to recall that the DB2 SQLA connector has a few aliases for the dialect, and we may need to add those to the `engine_aliases` property. See how Postgres does it: https://github.com/apache/superset/blob/852e840575cf5ec6e1ad2780c986972619c8666f/superset/db_engine_specs/postgres.py#L148

**Comment by cabo40** [comment]
@junlincc , thanks.
Hi, I will go with what  @villebro said, there are two aliases for DB2 connections https://superset.apache.org/docs/databases/ibm-db2 and they handle datetimes and limits in a different manner.
@ljclour , does the sql lab allows you to do raw queries or fails with the limit? Also, can you try any of this?
```sql
SELECT current date FROM sysibm.sysdummy1 
SELECT current time FROM sysibm.sysdummy1 
SELECT current timestamp FROM sysibm.sysdummy1
```

**Comment by ljclour** [comment]
> @ljclour what does your connection string look like, specifically the part before `://`?

Thanks!It does work when i choose another connection, like `ibm_db_sa`. @cabo40

**Comment by villebro** [comment]
@ljclour I opened a PR #14295 to add support for both `db2` and `ibm_db_sa` engine names, let me know if this works for you.
