### ISSUE TITLE
Dashboard filters unset on force refresh and dashboard refresh

### ISSUE THREAD

**Issue by alexs95** [apache/superset#14266]
Dashboard filters are unset inside the chart(s) on force refresh or dashboard refresh. When a dashboards filters are set and apply is clicked the filters are applied as expected. If a single chart is force refreshed the filters become unset for that chart when it is refreshed. If the entire dashboard is refreshed (using Refresh dashboard in the menu) the filters are unset for each chart.
Note: the filter values are still set, just they become unset on the charts.

### Expected results

The charts to be refreshed with the filters set as they were.

### Actual results

Charts are refreshed but filters are unset.

#### How to reproduce the bug

1. Create a dashboard with a filter and any other chart.
2. Set filters to appropriate values and click apply. (the other chart will update)
3. Force refresh the other chart.

### Environment

- superset version: 1.1.0, 1.0.1 (based on [amancevice/superset](https://hub.docker.com/r/amancevice/superset/)

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [y] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [y] I have reproduced the issue with at least the latest released version of superset.
- [y] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by amitmiran137** [comment]
Could you take a screen recording for the entire flow?
It would be easier then asking a bunch of questions
