### ISSUE TITLE
Async queries sometimes fail when retrieving cached query results

### ISSUE THREAD

**Issue by benjreinhart** [apache/superset#14289]
This bug effects both the polling and WebSocket implementations of the async queries experience introduced in SIP-39.

### Expected results

When clients are notified of query completion (either by polling or WS message), they should be able to retrieve the results of that query using the `result_url` value the server gave them. The server should respond with a 200 and the cached query results. This should be the case for all charts in Superset.

### Actual results

When a client is notified the query has completed, the client initiates the call to the backend with the `result_url`. For some charts, the server is responding with a 400 bad request because it could not find the cached results.

#### Screenshots

<img width="1322" alt="Screen Shot 2021-04-21 at 6 57 40 PM" src="https://user-images.githubusercontent.com/606233/115644471-7d5d5580-a2d3-11eb-9e2c-3979657d9553.png">

#### How to reproduce the bug

There are a few charts/dashboards where this is happening. One example is:

1. With the `GLOBAL_ASYNC_QUERIES` feature flag turned on, using either websocket or polling transport...
2. Visit `/superset/dashboard/deck/`
3. Notice that after some time, all charts render an "Unexpected error" message.

### Environment

Latest master

**Comment by rusackas** [comment]
Pinging/assigning @villebro since he might be well positioned to validate that this bug is behind us. That said, I'm _optimistic_ that this was closed by https://github.com/apache/superset/pull/14291 and left open unintentionally. I'll close it as stale, just to be safe, and I'm more than happy to reopen this if anyone thinks it's warranted.
