### ISSUE TITLE
Sorting Charts/Dashboards makes the applied filters ineffective

### ISSUE THREAD

**Issue by KrupaVadher** [apache/superset#14292]
Charts/Dashboard's card view: After applying any filter (e.x Favorite=Yes); if we select any sorting option from the sort dropdown menu, the filtered list get reset and the entire list is shown.

### Expected results

If any filter is applied to the list, then sorting that list should retain the applied filters.

### Actual results

The applied filter to the list gets reset to its original state after selecting any sort criteria.

In the video below, if we apply a filter (Favorite = Yes) to the list of charts, then selecting sort = Alphabetical will reset the filters and show the list with all charts (Starred and Un-Starred)

#### Screenshots

https://user-images.githubusercontent.com/57817186/115641067-353b3480-a2cd-11eb-8506-6a9607091393.mov

#### How to reproduce the bug

1. Go to Charts from toolbar and select the 'Card' view
2. Apply a filter by selecting Favorite = Any from the list headers. Make sure you have few favorite/starred charts to see the results
3. Select Sort = Alphabetical
4. You will see that the entire list is shown even though we have applied the filter to show only favorite charts 

### Environment

- superset version: commit# `c9a755f`
- python version: `python 2.7.16`
- node.js version: `v13.11.0`

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
Thanks for reporting @KrupaVadher ! I can confirm the bug.

**Comment by MM-Lehmann** [comment]
please reactivate.
I can confirm this in 1.4.2

**Comment by rusackas** [comment]
Looks like this is still an issue in 2.0.1 :(
