### ISSUE TITLE
[SQL Lab] Backtick in SQL preview query making it fail when user only have schema access

### ISSUE THREAD

**Issue by codenamelxl** [apache/superset#14294]
When user is only granted schema access, preview query is generated in from of `SCHEMA_NAME`.TABLE_NAME which failed the query.

### Expected results

Preview query success when user only have schema access.

### Actual results

Preview query failed

#### Screenshots

![image](https://user-images.githubusercontent.com/9434559/115651513-e4275100-a35d-11eb-8557-a530c86d871b.png)

#### How to reproduce the bug

1. Grant only schema access to user
2. Go to SQLLab
3. Choose the DB and the granted schema
4. Choose any table.
5. See the error.

### Environment

(please complete the following information):

- superset version: `> 1.1 (current master) (<1.1 should also have this problem)`
- python version: `3.7`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by codenamelxl** [comment]
This can be fixed by either:
- Changing the sql_parse to strip backtick.
- Changing the frontend to make the query without backtick.

**Comment by dpgaspar** [comment]
duplicate for #14233

**Comment by rusackas** [comment]
Closing in favor of https://github.com/apache/superset/issues/14233
