### ISSUE TITLE
[dashboard] anonymous users be not able to view dashboards.

### ISSUE THREAD

**Issue by code-snail** [apache/superset#14296]
anonymous users be not able to view dashboards.

### Expected results

anonymous users be able to view dashboards.

### Actual results

anonymous users be not able to view dashboards

#### Screenshots

![image](https://user-images.githubusercontent.com/65579137/115652923-c90a1080-a360-11eb-8023-f321e74df458.png)

#### How to reproduce the bug

1. login with admin user and create dashboard
2. logout admin
3. access dashboard that create before

### Environment

(please complete the following information):

- superset version: Superset 0.999.0dev
- python version: Python 3.7.9
- node.js version: v14.16.0
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
@code-snail I was able to reproduce the issue

**Comment by zufolo441** [comment]
me too.... with git version as of today. in 1.0.1 it was working.
![Screenshot_20210514_111202](https://user-images.githubusercontent.com/45826835/118249019-3bc06480-b4a5-11eb-8e5f-0e6c31af54d4.png)

**Comment by zufolo441** [comment]
the problem is still present: 
Uncaught TypeError: can't convert undefined to object
    isUserAdmin findPermission.ts:39
    canUserEditDashboard findPermission.ts:52
    hydrateDashboard hydrate.js:325
    createThunkMiddleware Redux
    DashboardPage DashboardPage.tsx:70
    commitHookEffectListMount react-dom.development.js:19765
    commitPassiveHookEffects react-dom.development.js:19803
    callCallback react-dom.development.js:189
    invokeGuardedCallbackDev react-dom.development.js:238
    invokeGuardedCallback react-dom.development.js:293
    flushPassiveEffectsImpl react-dom.development.js:22885
    unstable_runWithPriority scheduler.development.js:653
    runWithPriority$1 react-dom.development.js:11062
    flushPassiveEffects react-dom.development.js:22852
    commitBeforeMutationEffects react-dom.development.js:22731
    workLoop scheduler.development.js:597
    flushWork scheduler.development.js:552
    performWorkUntilDeadline scheduler.development.js:164
    EventHandlerNonNull* scheduler.development.js:187
    <anonymous> scheduler.development.js:857
    node_modules vendors.ff448c0c.chunk.js:22005
    __webpack_require__ spa.ff448c0c.entry.js:85
    <anonymous> index.js:6
    node_modules vendors.ff448c0c.chunk.js:22017
    __webpack_require__ spa.ff448c0c.entry.js:85
    <anonymous> react-dom.development.js:21
    <anonymous> react-dom.development.js:25105
    node_modules vendors.ff448c0c.chunk.js:21969
    __webpack_require__ spa.ff448c0c.entry.js:85
    <anonymous> index.js:37
    node_modules vendors.ff448c0c.chunk.js:21981
    __webpack_require__ spa.ff448c0c.entry.js:85
    <anonymous> index.tsx:1
    tsx spa.ff448c0c.entry.js:2539
    __webpack_require__ spa.ff448c0c.entry.js:85
    5 spa.ff448c0c.entry.js:2576
    __webpack_require__ spa.ff448c0c.entry.js:85
    checkDeferredModules spa.ff448c0c.entry.js:46
    <anonymous> spa.ff448c0c.entry.js:250
    <anonymous> spa.ff448c0c.entry.js:253
findPermission.ts:39

**Comment by albertojarabo** [comment]
I can't view dashboards with an anonymous user. If I assign the 'Public' role to AUTH_ROLE_PUBLIC (and copy all the permissions from the 'Admin' role to 'Public'), I can see everything except the Dashboards. However, if I assign the 'Admin' role to AUTH_ROLE_PUBLIC, I can also see the Dashboards with the anonymous user.

**Comment by rusackas** [comment]
@dpgaspar this seems to have gone silent for upward of six months. Do you think this is an issue we want to keep open?
