### ISSUE TITLE
filter type are listed as viz type

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#14308]
open chart list view and check **viz type** dropdown list:

Select filter, Time column, Time filter etc, are filter type not viz type. 

#### Screenshots

<img width="1088" alt="Screen Shot 2021-04-22 at 8 59 02 PM" src="https://user-images.githubusercontent.com/27990562/115816497-cb468c00-a3ad-11eb-86b3-353a23d0079e.png">

### Environment

latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

cc @junlincc @villebro

**Comment by villebro** [comment]
thanks for reporting this @graceguo-supercat !

**Comment by amitmiran137** [comment]
Should we have a config saying use native filters as Viz type?
This can be useful when there is a need to use one of the the native filter as a chart next/above/below a other chart where visual proximity to the chart might be useful in specific use-cases

**Comment by junlincc** [comment]
<img width="1154" alt="Screen Shot 2021-04-27 at 10 39 46 PM" src="https://user-images.githubusercontent.com/67837651/116352073-7c339900-a7a9-11eb-8eb3-be3fb2aca18a.png">
this is problematic as well 🤣 @simcha90 @amitmiran137 by default, we should hide all the filter types from all UI except in the filter itself. could we open a PR to add the config?

**Comment by villebro** [comment]
IMO there's two things here:
1) The viz type gallery should have a separate tab/section for plugins that are primarily native filters but can be added as regular viz components to a dashboard (for the use case @amitmiran137 described above). I'm ok to add a config to enable/disable native filters as regular viz components, but I think it should be enabled by default. I don't see the harm in having the option to place native filters on the dashboard as opposed to the filter tab.
2) Regarding the problem stated in the original issue, that dropdown needs to list all viz types that are supported in the viz type gallery.

**Comment by rusackas** [comment]
@suddjian this may relate to other work you're looking into regarding plugin metadata options

**Comment by junlincc** [comment]
let's move group-by, drill-down, filter chart components behind a new leading edge feature-flag. 

@villebro @simcha90 @amitmiran137 @zhaoyongjie

**Comment by villebro** [comment]
Sounds good - I propose calling the feature flag `DASHBOARD_NATIVE_FILTERS_EXPERIMENTAL` and having all unpolished features there.
