### ISSUE TITLE
Time-series bar chart -- series order

### ISSUE THREAD

**Issue by WeirdAnalyst** [apache/superset#14316]
Hello,
When using time-series bar charts with sort option for series enabled, series bar bar charts are4 not drawn in order.

### Expected results

Draw series bar charts in the order the series are sorted.

### Actual results

Series are drawn in a random order.

#### Screenshots

![image](https://user-images.githubusercontent.com/83085223/115902279-921c2380-a462-11eb-811f-7439188d1de9.png)

#### How to reproduce the bug

Self explanatory

### Environment

- superset version: "Superset 0.999.0dev"
- python version: "Python 3.9.4"
- node.js version: "v15.9.0"

Grateful if you can correct the bug.

**Comment by junlincc** [comment]
thanks for reporting! we may not fix this issue as we are migrating away from nvd3 to echarts. https://github.com/apache/superset/projects details in here

But feel free to open a PR though :)
