### ISSUE TITLE
Unable to install Database drivers except MySQL

### ISSUE THREAD

**Issue by yograjpshinde** [apache/superset#14315]
I followed the steps given at https://superset.apache.org/docs/installation/installing-superset-using-docker-compose to install Superset in Redhat Linux VM using docker. Superset is up and running and I could installed MySQL driver and could connect to database also by following the steps at https://superset.apache.org/docs/databases/dockeradddrivers.
When i followed the same steps given for mysql for Dremio and Snowflake it fails to install driver and Superset does not comes up. 

### Expected results
Dremio and Snowflake driver should have been installed.

### Actual results
Fails to install database drivers except MySQL

#### Screenshots

Please find screenshot attached. 

#### How to reproduce the bug
![Superset error](https://user-images.githubusercontent.com/83073007/115890072-2cd02e80-a472-11eb-9db9-e8c5e3605ca5.png)

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by srinify** [comment]
Hi @yograjpshinde when you add a new database driver to local-requirements.txt, it gets installed via pip (https://pip.pypa.io/en/stable/cli/pip_install/),

If you look at the error message, you're encountering:

`
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by ConnectTimeOutError(<pip._vendor.urllib3.connection.HTTPSConnection object at .....>, Connection to pypi.org timed out.`

... then you'll notice the key issue. **Connection to pypi.org timed out**. 

It seems like your Docker compose stack running within your Redhat Linux VM isn't able to connect to pypi.org. I would investigate your IP & networking rules to make sure Superset can talk to pypi.org

**Comment by srinify** [comment]
Closing, as this isn't a Superset specific issue. @yograjpshinde StackOverflow could be a better place to debug your networking setup:

- https://stackoverflow.com/questions/57648998/connection-to-pypi-org-timed-out
- https://stackoverflow.com/questions/55382620/what-is-wrong-with-pip/55383071

Or create a new question there.
