### ISSUE TITLE
no such table: report_schedule

### ISSUE THREAD

**Issue by vincentytran** [apache/superset#14329]
I followed the instructions on https://superset.apache.org/docs/installation/alerts-reports using the latest 1.1.0 version of superset. The superset worker says that it cannot find report_schedule table.

[SQL: SELECT report_schedule.created_on AS report_schedule_created_on, report_schedule.changed_on AS report_schedule_changed_on, report_schedule.id AS report_schedule_id, report_schedule.type AS report_schedule_type, report_schedule.name AS report_schedule_name, report_schedule.description AS report_schedule_description, report_schedule.context_markdown AS report_schedule_context_markdown, report_schedule.active AS report_schedule_active, report_schedule.crontab AS report_schedule_crontab, report_schedule.sql AS report_schedule_sql, report_schedule.chart_id AS report_schedule_chart_id, report_schedule.dashboard_id AS report_schedule_dashboard_id, report_schedule.database_id AS report_schedule_database_id, report_schedule.last_eval_dttm AS report_schedule_last_eval_dttm, report_schedule.last_state AS report_schedule_last_state, report_schedule.last_value AS report_schedule_last_value, report_schedule.last_value_row_json AS report_schedule_last_value_row_json, report_schedule.validator_type AS report_schedule_validator_type, report_schedule.validator_config_json AS report_schedule_validator_config_json, report_schedule.log_retention AS report_schedule_log_retention, report_schedule.grace_period AS report_schedule_grace_period, report_schedule.working_timeout AS report_schedule_working_timeout, report_schedule.created_by_fk AS report_schedule_created_by_fk, report_schedule.changed_by_fk AS report_schedule_changed_by_fk ,
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: report_schedule

Superset runs fine but reporting doesn't work. Is the documentation missing a step to create the necessary reporting tables?

### Environment

- superset version: 1.1.0
- python version: 3.7.9

**Comment by Omnipos-lab** [comment]
Looks like you've upgraded from previous version and didn't do db upgrade and init (?)

**Comment by vincentytran** [comment]
I did all three of these commands against the 1.1.0 container

docker exec -it superset_superset_1 superset db upgrade
docker exec -it superset_superset_1 superset init
docker exec -it superset_superset_1 superset fab create-admin

There wasn't any errors that I could see. I attached the output to the console when I ran the commands, a few warnings but nothing report_schedule related that I can see. 

[upgrade and init log output.txt](https://github.com/apache/superset/files/6372401/upgrade.and.init.log.output.txt)

**Comment by vincentytran** [comment]
I was able to resolve the issue by adding one line to the superset_config.py file, my guess is even though the docker compose includes postgres, maybe the defaults don't use it. Perhaps alerts/reporting only works when you don't use the embedded database but work fine with postgres.

SQLALCHEMY_DATABASE_URI = "postgresql+psycopg2://superset:superset@superset_postgres_1/superset"
