### ISSUE TITLE
Gamma user can see all datasets in the dropdown menu of the creation chart page

### ISSUE THREAD

**Issue by cyanoboy** [apache/superset#14324]
A user with the following roles:

- `Gamma`
- `Custom` with `schema access on [database_name].[schema]`, `database access on [database_name].(id:2)`

is able to see all datasets listed in the dropdown "Choose a dataset" of the "Create a new chart" page, also datasets that belong to database that the user hasn't the permission to see.

### Expected results

- see all the datasets from `database_name` in the Datasets page
- see all the charts built on datasets that belong to `database_name`
- in the "Create a new chart" page user can see in the dropdown list **only** datasets that belong to `database_name`

### Actual results

- see all the datasets from `database_name` in the Datasets page
- see all the charts built on datasets that belong to `database_name`
- in the "Create a new chart" page user can see in the dropdown list datasets that belong to **all databases** connected to Superset

#### Screenshots

![bug_superset](https://user-images.githubusercontent.com/13133966/115955557-79aa1880-a4f7-11eb-8b9f-d4a156689af4.png)

#### How to reproduce the bug

1. Create a user with gamma and custom roles as in the description of the issue
2. Click on '+ Chart' in the Charts page
3. Click on the dropdown menu 'Choose a dataset'
4. You will see all datasets

### Environment

- superset version: `1.0.0`, `1.1`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by arcuellar88** [comment]
Hello,

I have been tracking this issue for some time now. It was solved at some point but it came back again. 

https://github.com/apache/superset/pull/6356
https://github.com/apache/superset/issues/1434

Hope this helps...

**Comment by rusackas** [comment]
This version of Superset is no longer supported. If anyone is still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
