### ISSUE TITLE
Some of the columns in Pivot table rounded off automatically (like 6.7--7)

### ISSUE THREAD

**Issue by ivanku99** [apache/superset#14344]
I have a tabe.
All collums in the table is float4
when i use the pivot table 
Some of the columns in Pivot table rounded off automatically (like 6.7--7)  version 1.0.1.
the parametr in the options is fixed (,d 123- 12б345)
![WhatsApp Image 2021-04-26 at 11 03 51](https://user-images.githubusercontent.com/82075724/116031299-34185780-a67f-11eb-94c5-9700ff59b62a.jpeg)
![WhatsApp Image 2021-04-26 at 11 03 50](https://user-images.githubusercontent.com/82075724/116031313-37abde80-a67f-11eb-9e84-bad5555e9fe2.jpeg)

**Comment by junlincc** [comment]
@ivanku99 thanks for reporting. try using Pivot Table v2 in the Gallery. I'm pretty sure the rounding issue was being addressed when we merge the PR. lmk if that's not the case.
