### ISSUE TITLE
Need Dashboard to view as standard alone like chart. 

### ISSUE THREAD

**Issue by queppelin-dev** [apache/superset#14341]
Hi all,
 How can I show Dashboard as standard alone in an iframe without a Header? 
For the Chart i use URL/superset/explore/?r=165&standalone=true.
![withheader](https://user-images.githubusercontent.com/56347200/116030567-72ab1380-a679-11eb-821b-2ef0fccc7391.png)
![without header](https://user-images.githubusercontent.com/56347200/116030571-7474d700-a679-11eb-9cbc-30ff9a08b9c6.png)

Please check the files and let me know if I can achieve this by any idea.
wherein image 1 is with a header which I have to remove like image 2.
Thanks

**Comment by nytai** [comment]
Does appending `?standalone=true` to the dashboard url not work?
