### ISSUE TITLE
Dissuade users from modifying roles through UI if AUTH_ROLES_SYNC_AT_LOGIN is enabled

### ISSUE THREAD

**Issue by cccs-rc** [apache/superset#14352]
**Is your feature request related to a problem? Please describe.**
As of 3.2.0, FAB has supported an AUTH_ROLES_SYNC_AT_LOGIN flag, which re-syncs a user's roles every time they login. This means that, if an admin has manually modified a user's roles through the UI, those modifications won't persist between logins. This can cause some confusion!

**Describe the solution you'd like**
A warning on the "Edit User" page indicating that AUTH_ROLES_SYNC_AT_LOGIN is set to true and any changes made to a users' roles won't persist between logins. 

**Describe alternatives you've considered**
One alternative might be to disable the editable "Roles" field in the "Edit User" page if AUTH_ROLES_SYNC_AT_LOGIN is enabled (or have a flag to optionally disable the field), but this seems a bit restrictive. It can be useful to manually add a role either as a temporary measure to allow a user to do something they wouldn't normally do, or for testing purposes to verify if an added role will, in fact, allow a user to do what they want to do. 

**Additional context**
To illustrate what I was loosely imagining: 
![image](https://user-images.githubusercontent.com/62034438/116111912-1221d380-a685-11eb-8d2a-ac12f1225501.png)

Alternatively, maybe a message that appears only if/when someone modified the Role field would be an option. 

![image](https://user-images.githubusercontent.com/62034438/116112438-8e1c1b80-a685-11eb-8a1c-979766e53c4f.png)

**Comment by dpgaspar** [comment]
@cccs-rc good point, thanks for your suggestion. Since this is 100% FAB related, can you please reopen this on: https://github.com/dpgaspar/Flask-AppBuilder

Closing this issue here.
