### ISSUE TITLE
ArangoDB driver

### ISSUE THREAD

**Issue by itsezc** [apache/superset#14378]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
A connector for ArangoDB to use as a data source

**Describe alternatives you've considered**
Currently there are no alternatives

**Additional context**
No resources on this issue, the closest project that comes to SQLAlchemy is https://github.com/threatify/arango-orm

**Comment by junlincc** [comment]
@itsezc Hi, anyone from the community is welcome to open a PR for adding new datasource connector. :)
