### ISSUE TITLE
Custom plugins entry not visible in settings menu after enabling feature flag

### ISSUE THREAD

**Issue by krsnik93** [apache/superset#14373]
I have added `"DYNAMIC_PLUGINS": True` to my `superset_config.py`, but the Plugins entry does not appear in the Settings menu. I have previously enabled `ROW_LEVEL_SECURITY` and can toggle it and see the effect. My feature flags:
```
FEATURE_FLAGS = {
    "ROW_LEVEL_SECURITY": True,
    "VERSIONED_EXPORT": True,
    "DYNAMIC_PLUGINS": True,

    "THUMBNAILS": True,
    "THUMBNAILS_SQLA_LISTENERS": True,
    "LISTVIEWS_DEFAULT_CARD_VIEW": True,
}

```
I have also inserted `pdb` into the backend and can see that it can read the flag as `True`. So perhaps the issue is somewhere in `superset-frontend`.

### Expected results

Expect Plugins to appear in Settings menu, section Manage.

### Actual results

No entry in the menu.

#### Screenshots

![image](https://user-images.githubusercontent.com/13034472/116237343-00f5c700-a758-11eb-9d99-77802442f470.png)

#### How to reproduce the bug

1. Create `superset_config.py` with the feature flags and include it in `PYTHONPATH`.
2. `superset run -p 8088 --with-threads --reload --debugger` in one window
3. `npm run dev-server --superset=http://localhost:8088` from `/superset-frontend` in another window
4. Login and click on Settings to verify no change

### Environment

(please complete the following information):

- superset version: 0.999.0dev
- python version: 3.8.7
- node.js version: v14.16.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@krsnik93 thanks for reporting, do you consider it as a blocker for the project?

**Comment by krsnik93** [comment]
@junlincc not a huge blocker, but wanted to verify it's a real issue.

**Comment by krsnik93** [comment]
Resolved, a `superset init` after setting the flag was needed.
