### ISSUE TITLE
Enable ROW_LEVEL_SECURITY option in menu

### ISSUE THREAD

**Issue by soubhikbasu** [apache/superset#14397]
Hi,

I am installed superset from the scratch level option. But Currently i am not able to access ROW_LEVEL_SECURITY option under Setting>>Security. I am attached screenshot of setting section where "ROW_LEVEL_SECURITY" should come.

Please help me to how to do that

![image](https://user-images.githubusercontent.com/56683353/116474380-09ecb280-a896-11eb-9873-17653a854b82.png)

**Comment by aleksandrgordienko** [comment]
You should set ROW_LEVEL_SECURITY flag to TRUE in your config.py. Row level security is disabled by default.

**Comment by soubhikbasu** [comment]
@aleksandrgordienko 
i am attached my config.py file as PDF
Please check
[config.py.pdf](https://github.com/apache/superset/files/6396801/config.py.pdf)

In this file where do i add that ?

**Comment by villebro** [comment]
@soubhikbasu do the following:
1. In your `superset_config.py` file, add the following:
```python
FEATURE_FLAGS = {
    "ROW_LEVEL_SECURITY": True,
}
```
1. run `superset init`

FYI: In the forthcoming Superset 1.2 version, RLS will be enabled by default, but I consider it to have been fully stable since 1.0.

**Comment by soubhikbasu** [comment]
@villebro 
in my installation dont have superset_config.py
should i put that in /.local/lib/python2.7/site-packages/setuptools/config.py ?

Thanks in advance
