### ISSUE TITLE
Jinja templating for Groupby fields

### ISSUE THREAD

**Issue by prb219** [apache/superset#14395]
**Describe the solution you'd like**
Hi, I am trying to create a filter in my dashboard to choose various groupby fields to be applied to my charts. My approach to this was to try using jinja templating in my charts to pick the value chosen in the filter to be applied as groupby field. However, I do not see a 'custom sql' option to provide jinja template to a group by field. Can you please suggest me a workaround to solve this usecase ? 

**Describe alternatives you've considered**
As an alternative I must be able to use jinja templating in my datasource itself but then it might not be the best idea. 

Superset version in use is 0.37.0

**Comment by nytai** [comment]
have you tried using a calculated column in the dataset definition? "Edit dataset" in explore
