### ISSUE TITLE
CSV upload for on-premise Hadoop cluster block through erroneous code

### ISSUE THREAD

**Issue by 0xBADBAC0N** [apache/superset#14392]
Hi guys,
I have the issue that I can not upload a CSV to Hive through Superset as our Hadoop is not running on S3.
I hunted it down to this line in the code: https://github.com/apache/superset/blob/master/superset/db_engine_specs/hive.py#L65
The following settings in the config are all related to the bucket: https://github.com/apache/superset/blob/master/superset/config.py#L781
The issue is my Hive is running on-premise therefore I have no bucket.

### Expected results
Uploading a CSV through the frontend should end up putting the file to Hadoop and make it accessible through a table.

### Actual results
Uploading the CSV will cause an error like
```Unable to upload CSV file "kc_house_data.csv" to table "hendrik_house_test" in database "Hive Production". Error message: No upload bucket specified. You can specify one in the config file.```

#### Screenshots

![image](https://user-images.githubusercontent.com/24916828/116415675-ed229180-a839-11eb-8c21-1af613b1674b.png)

#### How to reproduce the bug

1. Go to the main dashboard
2. Click on Data
3. Click on Upload a CSV
4. Enter Table name and Choose file etc
5. Save 
6. See error

### Environment

- superset version: `1`
- python version: `Python 3.7.3`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stack traces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
It seems like the current upload functionality does only work as long the related cluster is cloud based. It looks like this bug is only affecting on-premise clusters therefore we would highly appreciate to get this fixed :)

**Comment by srinify** [comment]
Any helpful tips here @etr2460 ? I know y'all use CSV upload to hive a bit

**Comment by 0xBADBAC0N** [comment]
bump :)

**Comment by 0xBADBAC0N** [comment]
@etr2460 Any idea for this one or even plans? : )
If you would give us some hands we also could start fixing this : )

**Comment by livwel-populus** [comment]
Any word on this feature or how to fix it?

**Comment by campi01** [comment]
Is this even on the radar for getting looked at, or is it not to be supported at all?

**Comment by rusackas** [comment]
> Is this even on the radar for getting looked at, or is it not to be supported at all?

It doesn't seem to be on anyone's radar. Any interest in diagnosing/contributing?

If nobody has interest in picking this up, we might close it as stale before long, as we're trying to steer toward a more actionable backlog of issues.

**Comment by rusackas** [comment]
As the prophecy has foretold, I'll close this as stale. If anyone wants to tackle it, we can certainly reopen this.
