### ISSUE TITLE
[Report] Can't send a Email Report for a Pie Chart using the new reporting feature

### ISSUE THREAD

**Issue by younsb** [apache/superset#14407]
VERSION : 1.1.0

I try to schedule a  report using  "Alerts and reports" for different type of visualizations.

- Pie chart :-1:  didn't work (see traceback 1)
- Word Cloud :-1: didn't work (see traceback 2)
- table :+1:  worked
- Big Number :+1: worked 

### Expected results

4 mails received  for every chart 

### Actual results

2 mails received with table chart  and Big number chart 

#### Screenshots
For pie chart (CSV) : 
 
![pie-chart-csv](https://user-images.githubusercontent.com/81430164/116228718-f5090580-a755-11eb-9b7c-1fe37c68ef35.png)

Error in Superset :

![error-superset](https://user-images.githubusercontent.com/81430164/116228837-1669f180-a756-11eb-9d52-445bc83eb794.png)
 
Error in Gui : 

![erorr-gui](https://user-images.githubusercontent.com/81430164/116228915-2f72a280-a756-11eb-80cd-9f05cb61bd4f.png)

Error in Celery : 

![error-schedule](https://user-images.githubusercontent.com/81430164/116229118-66e14f00-a756-11eb-9ccd-7bfa70fdd2a4.png)

For pie chart (png) :

![pie-chart](https://user-images.githubusercontent.com/81430164/116239013-6ea6f080-a762-11eb-82a0-558f6d3e8449.png)

Error in Gui : 

![image](https://user-images.githubusercontent.com/81430164/116238895-461ef680-a762-11eb-8dbf-b4ee64efe931.png)

Error in Celery : 

![image](https://user-images.githubusercontent.com/81430164/116229587-fbe44800-a756-11eb-8727-221949a9e389.png)

#### How to reproduce the bug

1. Go to 'Reports & Alerts'
2. Go to Report
3. Add a report for a pie chart (error for any pie chart) as message content 
4. choose PNG or CSV 
5.  add a mail and save 
6. error in the logs when superset will try to send report

### Environment

- superset version: `1.1.0`
- python version: `Python 3.7.6`
- node.js version: `v14.16.0`

### Additional context

I am using geckodriver. the "Report and alerts" is working for all charts except the pie chart and word cloud in both cases (CSV, png) didn't work

**Comment by younsb** [comment]
@suddjian @junlincc  related to #13814

**Comment by duynguyenhoang** [comment]
I have seen it before, not in the Email report but in cache warmup.
We have pie char defined as `DistributionPieViz` class in `viz_sip38.py` and had been removed in newest Superset version.
I am working on it to fix that issue and hopefully I can have a PR next couple of day

**Comment by yousoph** [comment]
Unable to repro so closing, please reopen with more details if you're still seeing this issue!
