### ISSUE TITLE
address family not supported by protocol by Installing Superset Locally Using Docker Compose

### ISSUE THREAD

**Issue by huailide** [apache/superset#14400]
When I use command "docker-compose -f docker-compose-non-dev.yml up", I got the message as below, how should I do?:
[root@KSSHV125814 superset]# docker-compose -f docker-compose-non-dev.yml up
Removing superset_appsuperset_cache is up-to-date
superset_db is up-to-date
Starting 38ac440aca23_superset_app ...Starting superset_init             ...
superset_worker is up-to-date
Starting 38ac440aca23_superset_app ... errorWARNING: Host is already in use by another container

ERROR: for 38ac440aca23_superset_app  Cannot start service superset: driver failed programming external connectivity on endpoint 38ac440aca23_superset_app (07c605f2faStarting superset_init             ... done

ERROR: for superset  Cannot start service superset: driver failed programming external connectivity on endpoint 38ac440aca23_superset_app (07c605f2fab03aec19914261f60b469cb0de5b0103a2922acb81bfaf05fd119e): Error starting userland proxy: listen tcp6 [::]:8088: socket: address family not supported by protocol
ERROR: Encountered errors while bringing up the project.

**Comment by huailide** [comment]
OS: CentOS Linux release 7.6.1810 (Core)

**Comment by jagamts1** [comment]
@huailide Looks like port 8088 already used by some other instance on your system. You could identify those instance by running `lsof -i :8088`

**Comment by huailide** [comment]
> @huailide Looks like port 8088 already used by some other instance on your system. You could identify those instance by running `lsof -i :8088`
Same problem, but this time without 'Starting 38ac440aca23_superset_app ... errorWARNING: Host is already in use by another container'

**Comment by srinify** [comment]
Jagadish is right that there's a port conflict here!

You have a few options from my estimation:

- Run the `superset` container on a different port. Here's the Docker documentation on manually mapping ports for containers: https://docs.docker.com/compose/reference/run/
- Change the port in `docker-compose.yml` or `docker-compose-non-dev.yml` from `8088:8088` to something else. Here's the line of code you need to edit for that:

https://github.com/apache/superset/blob/master/docker-compose.yml#L56 or https://github.com/apache/superset/blob/master/docker-compose-non-dev.yml#L51

**Comment by srinify** [comment]
Closing as this is not a Superset related issue
