### ISSUE TITLE
Enable ROW_LEVEL_SECURITY option in menu #14397

### ISSUE THREAD

**Issue by soubhikbasu** [apache/superset#14404]
@villebro
in my installation dont have superset_config.py
should i put that in /.local/lib/python2.7/site-packages/setuptools/config.py ?

https://github.com/apache/superset/issues/14397

you closed this issue, but its not solved yet

Thanks in advance

**Comment by villebro** [comment]
@soubhikbasu this is not a bug, but a question regarding how to configure Superset - please refer to the documentation (https://superset.apache.org/docs/installation/configuring-superset), post on the Discussions page (https://github.com/apache/superset/discussions) or post a question on the `#beginner-questions` channel on the Superset Slack.

**Comment by soubhikbasu** [comment]
@villebro
i am not say that is a bug, i am not able to fix that thats why i rise the issue, i am already go throgh these docs, but not find out proper way

**Comment by villebro** [comment]
This might in fact be a bug in the documentation, which only references the `PYTHONPATH` environment variable, not `SUPERSET_CONFIG_PATH`. Can you create the file and add it to the environment variable, like so (example of my env local variable):
```
SUPERSET_CONFIG_PATH=/Users/ville/superset/superset_config.py
```

**Comment by soubhikbasu** [comment]
@villebro
Thanks for the help.

Any specific location need to place superset_config.py or anywhere keep that file for better or quick response or error free response

**Comment by villebro** [comment]
No, any place that is convenient for you. If this works feel free to open up a PR to improve the docs; if not I can also do it.

**Comment by soubhikbasu** [comment]
@villebro

Many Thanks,

First i will try with that, then i will inform you, as i have note done before

**Comment by soubhikbasu** [comment]
@villebro

I have added that config file to env and after that run superset init, not oked as well

then i kill the superset procees then restart again, after that not working as well

![image](https://user-images.githubusercontent.com/56683353/116535533-781a8f00-a901-11eb-9e91-e8abbd053bbc.png)

Please help me to get out of this

**Comment by villebro** [comment]
Are you running via docker? If so, the file needs to go in `docker/pythonpath_dev/superset_config_docker.py` I believe

**Comment by soubhikbasu** [comment]
@villebro

No I am not running with docker, i am following following installation to install superset
https://superset.apache.org/docs/installation/installing-superset-from-scratch

**Comment by jagamts1** [comment]
@soubhikbasu 
1. First check which version superset are using it.  1.0.0 < superset  >  1.0.0 
2. Then add RLS FLAG inside the config file and define config path.
`SUPERSET_CONFIG_PATH=<your_file_path>/superset_config.py
`
3. Run 
`superset init`

For Superset >= 1.0.0 Then
```
FEATURE_FLAGS = {
    "ROW_LEVEL_SECURITY": True,
}
```
For Superset < 1.0.0 Then

```
ENABLE_ROW_LEVEL_SECURITY = True
```

**Comment by soubhikbasu** [comment]
@jagamts1 

Hi,

Thanks for the reply but still not fixed yet

i am share my "superset_config.py" file and share my superset version as well. SO it would be helpful for you to better suggestion what i am doing wrong here

[superset_config.py.pdf](https://github.com/apache/superset/files/6403893/superset_config.py.pdf)
![image](https://user-images.githubusercontent.com/56683353/116668371-fd15af00-a9ba-11eb-9986-23bcaf02c198.png)

I have placed my superset_config.py in following location
/home/soubhik/.local/lib/python3.6/superset_config.py

**Comment by jagamts1** [comment]
@soubhikbasu Just follow the above order, which we shared will work without any issue. I guess still you are making mistake on setting-up config path. Once config path set properly, it'll show in the logs after we launch the server otherwise it will take default config file.
 
![Screenshot from 2021-04-30 18-19-50](https://user-images.githubusercontent.com/17809881/116697749-3103cb00-a9e1-11eb-9691-6b5ec7158ede.png)

Just follow GIF for superset 0.38.1. 
![RLS](https://user-images.githubusercontent.com/17809881/116696768-f3eb0900-a9df-11eb-82dc-1fde00b828ca.gif)

**Comment by soubhikbasu** [comment]
@jagamts1 

Hi Jagadish

You made my day! Its works as you directed. Its very helpful  with your gif tutorial.

@villebro
@aleksandrgordienko

Thanks a lot all of you

without your help i am not able to solve my issue

**Comment by sebastianliebscher** [comment]
@sfirke I think this issue can be closed
