### ISSUE TITLE
Can't visualize data from Gsheets

### ISSUE THREAD

**Issue by paumillet** [apache/superset#14406]
Hello,

Following [this tutorial on Preset blog](https://preset.io/blog/2020-06-01-connect-superset-google-sheets/), I managed to connect to the example spreadsheet, as well as my own ones, with simple queries via the SQL editor as 
```sql
SELECT
    *
FROM "https://docs.google.com/spreadsheets/d/1_rN3lm0R_bU3NemO0s9pbFkY5LQPcuy1pscv8ZXPtg8/edit#gid=0"
```

I got the results correctly returned.  
But every time I try to "Explore" my dataset then, I get the following error `no such table`:

![image](https://user-images.githubusercontent.com/43337673/116518805-00cd0700-a8d1-11eb-86d4-e8c67db34637.png)

When I try to build a bar chart, as suggested in the tutorial, I noticed that the query Superset was applying was :
```sql
SELECT 
  country AS country,
  COUNT(*) AS count
FROM "https://docs.google.com/spreadsheets/d/1_rN3lm0R_bU3NemO0s9pbFkY5LQPcuy1pscv8ZXPtg8/edit#gid=0"
GROUP BY country
ORDER BY count DESC
LIMIT 10000
```
I indeed have the same error when reproducing that query in the SQL editor.  
But I don't have error anymore if I just query without the `ORDER BY` statement! and my results are correctly displayed.

Any idea on how to deal with this trouble to be able to visualize my data from Gsheets?
I'm using Superset version 1.0.1, let me know if you need more information about the setup.

Thanks in advance for helping,
Pauline

**Comment by betodealmeida** [comment]
@paumillet can you try again but using `shillelagh` instead of `gsheetsdb`? 

[shillelagh](https://github.com/betodealmeida/shillelagh/) is a new library that replaces `gsheetsdb`, and it's much more robust. I'll work with @srinify to update our documentation.

**Comment by paumillet** [comment]
Thanks @betodealmeida for your reply

Am I supposed to change anything in the database and dataset configuration then? I was adding a database by adding `gsheets://`in the SQL Alchemy URI field, should I follow the same process?

**Comment by srinify** [comment]
@paumillet I just tried replacing `gsheetsdb` with `shillelagh` and it worked like a charm!

![image](https://user-images.githubusercontent.com/801507/116785611-8a630d00-aa68-11eb-9da8-897c1e9461a6.png)

<img width="548" alt="Screen Shot 2021-05-01 at 10 33 05 AM" src="https://user-images.githubusercontent.com/801507/116785627-a1a1fa80-aa68-11eb-94dd-d60a4d106bf6.png">

<img width="1664" alt="Screen Shot 2021-05-01 at 10 32 51 AM" src="https://user-images.githubusercontent.com/801507/116785629-a36bbe00-aa68-11eb-8570-bad34e486dd6.png">

**Comment by srinify** [comment]
@paumillet closing this issue for now. If you need more debugging help, I would recommend creating a Github Discussion: https://github.com/apache/superset/discussions

**Comment by paumillet** [comment]
Finally works for me too, thank you for helping
