### ISSUE TITLE
Need improved translation into Russian 

### ISSUE THREAD

**Issue by aleksandrgordienko** [apache/superset#14405]
## Description

Many of the strings ID should be translated into Russian. This is the first step for turning on i18n by default and include Russian translation into it.

**Comment by srinify** [comment]
Linked PR by @aleksandrgordienko 

https://github.com/apache/superset/pull/14412

**Comment by aleksandrgordienko** [comment]
> Linked PR by @aleksandrgordienko
> 
> #14412
> 
> Hi there, do we need this issue if you have a PR? :)

Hey @srinify,
I've just followed [Pull Request Guidelines](https://github.com/apache/superset/blob/master/CONTRIBUTING.md#pull-request-guidelines):

> Before creating a PR, create an issue 

Should I close this issue and unlink PR with it?

**Comment by srinify** [comment]
AH I got you, lets leave it for now. Sorry!
