### ISSUE TITLE
dashboard export in xls and xml format

### ISSUE THREAD

**Issue by corrad82-4s** [apache/superset#14415]
**Is your feature request related to a problem? Please describe.**
As Microsoft Excel, and its xls/xlsx file types, is a common standard among business analysis and business intelligence teams, and xml is one of the formats in use for data exchange and interoperability, the possibility of having an export of dashboards in those formats. 

**Describe the solution you'd like**
In addition to already present icons to export in json and csv, two further intuitive icons might be placed, once clicked an export in xml or xls is triggered.

**Describe alternatives you've considered**
Considered alternatives are related to the possibility of a post-transformation of already available outputs, i.e. from json to xml or from csv to excel, but I think having the possibility directly in superset instead of applying post transformation with other tools might be better. 

**Additional context**
I am aware of issue https://github.com/apache/superset/issues/11162. 
Is anyone already working on this feature and/or can provide any suggestion about how to implement it? And / Or might be interested in a contribution?

**Comment by srinify** [comment]
Hi @corrad82-4s to clarify this, do you want users to be able to explore datasets in XLS format and charts / dashboards in XML format? Or just datasets in XLS / XML?

**Comment by corrad82-4s** [comment]
Hi @srinify , thank you for your answer. We want users to be able to export charts content in xls and xml file in addition to already existing possibilities of exporting them in json or csv

**Comment by srinify** [comment]
Sorry, to be 100% clear ... what do you mean by 'charts  content'? 

A screenshot / image of the chart? The JS code behind the chart? The underlying data for the chart?

**Comment by corrad82-4s** [comment]
@srinify sorry to you for not being so clear. 
In short, I mean the underlying data, the same data that would be exported in json or csv from dashboard edit page
![image](https://user-images.githubusercontent.com/70699836/116583815-06e5d680-a917-11eb-9bf7-ae88cb4e9a2d.png)

or from csv export from dashboard's chart menu
![image](https://user-images.githubusercontent.com/70699836/116583954-2846c280-a917-11eb-9de2-5033ef792517.png)

**Comment by srinify** [comment]
Got it, I'm with you now :]

**Comment by srinify** [comment]
@junlincc I wonder if this could be a good medium-complexity "first issue" for someone 🤔

**Comment by exemplary-citizen** [comment]
I'd be happy to take this on. We can use the same pattern that is in place for downloading CSVs https://github.com/apache/superset/blob/master/superset/views/base.py#L560 and adapt it to xml and xlsx by adding `XmlResponse` and `XlsxResponse` classes. Do you think this should get split up into two seprate PRs? one for each file type?

**Comment by arojoal** [comment]
+1

**Comment by LalaGabor** [comment]
+1

**Comment by Qweyer** [comment]
+1 for this feature

**Comment by iyakhiev** [comment]
I need this feature too.

**Comment by romanbody** [comment]
+1 for this feature
is there any plan/update regarding this feature?

**Comment by h0rn3t** [comment]
+1

**Comment by amravazzi** [comment]
+1

**Comment by pdakkata-quot** [comment]
+1

**Comment by Neel-rishabhsoft** [comment]
+1

**Comment by timnick-snow** [comment]
+1

**Comment by timnick-snow** [comment]
Hope to have this feature

**Comment by mkhayom** [comment]
+1

**Comment by andrey-mikhailov** [comment]
+1

**Comment by msaifi255** [comment]
+1

**Comment by DiegoQ77** [comment]
+1

**Comment by rpmulya** [comment]
+1

**Comment by rasharp** [comment]
+1

**Comment by oyasuyuki** [comment]
+1

**Comment by jordiisidro** [comment]
+1

**Comment by distrx01** [comment]
+1

**Comment by BlessMario** [comment]
+ 1 (would be very nice)

**Comment by scr1ble** [comment]
+1

**Comment by itziarmj** [comment]
The excel export is available in the edit chart, but not in the charts in the dashboard.
Could it be possible to add this functionality also to the charts included in a dashboard?
This way, users that do not have edit permission can also access this feature.

**Comment by MaheshKungaria** [comment]
+1 need Export to Excel option on Superset 2.0.0 reports

![pic](https://github.com/apache/superset/assets/112639146/3725a85b-0277-4fd1-a3ab-70bb1fe185fa)

**Comment by rusackas** [comment]
I'm tempted to close this out since it's both a stale/silent thread (it's been silent well over a year), and a feature request rather than a bug. Clearly there's a lot of interest in the feature, however. Is anyone willing to contribute the remaining parts?

**Comment by rusackas** [comment]
Ok, I'm closing this as stale. If anyone wants to tackle parts of what's left, I'd advise just doing so on a PR, or opening "Ideas" threads on GitHub Discussions for any additional feature requests. Thanks to all those who participated in this thread and all the PRs that have been merged toward the effort thus far.
