### ISSUE TITLE
Wrong SQLAlchemy driver of Apache Impala in driver list

### ISSUE THREAD

**Issue by Luoxihan** [apache/superset#14423]
安装impala时名字不对, 官网给出的是 pip install impala , 实际上是pip install impyla
地址: https://superset.apache.org/docs/databases/installing-database-drivers
给使用者造成了一定程度上的不必要时间浪费

**Comment by jagamts1** [comment]
#14425

**Comment by jagamts1** [comment]
Thanks raising this @Luoxihan . Updated docs and created PR https://github.com/apache/superset/pull/14425

**Comment by zhaoyongjie** [comment]
Hi @Luoxihan, Thank you for reporting this issue of docs. Community is public intelligence, you are welcome to contribute PR to fix any bug or add a new feature.

十分感谢报告此问题. 社区是群体智慧, 除了使用也请您贡献一份力气.

**Comment by zhaoyongjie** [comment]
This issue fixed by https://github.com/apache/superset/pull/14425, so close this.
