### ISSUE TITLE
[native filter] can not set filter scope: JS errors

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#14422]
#### How to reproduce the bug

1. Enable native filter feature flag,
2. open World Bank's Data dashboard,
3. open filter bar, set filter scope for "country name", for example, remove scope for "%Rural" chart.
4. Config panel has not response, 
5. If you open dev console, will see JS error thrown.

#### Screenshots

<img width="590" alt="Screen Shot 2021-04-29 at 6 05 11 PM" src="https://user-images.githubusercontent.com/27990562/116636179-8672a600-a915-11eb-9585-c961a30f5f5d.png">

### Environment

latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
Thanks for reporting, filter scoping is broken in master. 
@villebro @kgabryje 
https://user-images.githubusercontent.com/67837651/116653472-1f1c1c80-a93c-11eb-920d-7f86b56442ae.mov
