### ISSUE TITLE
Time range filter applied across all charts, independently of the chosen variable

### ISSUE THREAD

**Issue by michalgala** [apache/superset#14430]
When a value is selected in a time range filter (in a filter box), the time is applied across all the line charts, even if the time variable composing the X axis of the line chart is not the same as the one selected.

### Expected results

When a time variable is set in a filter box, It should filter the database based on the chosen variable (let's say X), and therefore only filter the time axis of the line charts if the time axis is composed by the same variable.

### Actual results

All the time variables used by the charts inherits from the chosen Time Range.

#### Screenshots

This is the filter box where I choose the time filter
![image](https://user-images.githubusercontent.com/44247532/116702961-14936e80-a9a0-11eb-9ce9-8f9392b3c035.png)

The time filter should be applied on the variable that I choose in the chart UI (releasedate in my example)
![image](https://user-images.githubusercontent.com/44247532/116703080-3a207800-a9a0-11eb-8eb4-ebf0f9e5a272.png)

However, this charts inherits from the filter that I applied, despite the time variable not being the same (fakedate here in my example)
![image](https://user-images.githubusercontent.com/44247532/116702901-047b8f00-a9a0-11eb-8487-02ceb6f42dbe.png)

#### How to reproduce the bug

1. You need a table with at least two time columns
2. Create a time filter using the first time variable
3. Create a line chart using the second variable
4. See how the time axis of the line chart is filtered

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by geido** [comment]
Hey @michalgala closing this as stale as filter box is deprecated and will be removed in 4.0. If you still have any issue with any of the recent Superset versions (3.x), please feel free to open a new issue. Thank you!
