### ISSUE TITLE
docker-compose: Custom python package installation will fail via requirements-local.txt

### ISSUE THREAD

**Issue by azadsagar** [apache/superset#14459]
Latest docker image uses non root user (superset). Hence any customer packages that are added to requirements-local.txt will fail to install with pip error stating OS error, permission issue.

```
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/home/superset'
Check the permissions.

```

adding --user to docker-bootstrap.sh won't help as the /home/superset directory does not exist.
https://github.com/apache/superset/blob/9a22fb00d9a94ab9f7aac41ca8915952ed8a75b6/docker/docker-bootstrap.sh#L34

**Comment by jagamts1** [comment]
@azadsagar By default docker-compose service are defined with root user. It's working without any issue. Tested right now also with master. Could you provide what setup did you followed after cloned the repo, it will make easier to identify issue.

**Comment by nytai** [comment]
Docker compose files have the user set as root for the superset services

**Comment by srinify** [comment]
hi @azadsagar are you using Docker or Docker Compose? These are very different things!

If you're running Docker images, you may need to make sure root user is set. For Docker Compose, as @nytai mentioned, it's set automatically.

**Comment by srinify** [comment]
Closing for now as this thread has gone stale, feel free to re-open @azadsagar !
