### ISSUE TITLE
Extra scrollbars in SQL lab

### ISSUE THREAD

**Issue by kristw** [apache/superset#14455]
## Screenshot

![Pasted_Image_5_3_21__5_41_PM](https://user-images.githubusercontent.com/1659771/116949394-e24f6e80-ac36-11eb-823e-1bb81b6c849b.png)

## Description

Unnecessary scrollbar

## Design input

Please remove them.

cc @yousoph

**Comment by rusackas** [comment]
cc @AAfghahi

**Comment by AAfghahi** [comment]
THis gets fixed in https://github.com/apache/superset/pull/14381
