### ISSUE TITLE
[Explore] Tab Animation on Metric popover flies out of the box

### ISSUE THREAD

**Issue by ktmud** [apache/superset#14475]
## Screenshot

https://user-images.githubusercontent.com/335541/117076337-171cfd80-aceb-11eb-8639-399533d653a7.mp4

## Description

Was it even intentional to enable tab switch animation? IMO they are kind of distracting.

**Comment by ktmud** [comment]
I don't see any mention of animation in https://github.com/apache/superset/pull/14048 so maybe it's not intented.

**Comment by junlincc** [comment]
Thanks for reporting. it was not intended, we didn't know the popover could be affected. 
@jinghua-qa 
Please add to test case and note that explore metric popover tab share the same component with global nav, any changes made in either area, test need to be done in the other. 

@pkdotson please push a quick fix. 🙏

**Comment by pkdotson** [comment]
pr is out: https://github.com/apache/superset/pull/14478

**Comment by junlincc** [comment]
resolved
