### ISSUE TITLE
[SIP-66] Dynamic control panel

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14473]
Note: This is 2/3 of a greater proposed effort in Data Visualization Enhancement, Reorganization and Revamp 

**Background** 
As of today, Superset has grown from a hackathon project to a full-fledged BI tool with over 50 out-of-the-box visualization plugins offered. Users appreciate Superset for providing a variety of visualization options, though the organic growth of the product throughout the years has led to increasing difficulty in navigating in the gallery page, and creating visualizations efficiently. 

**Goal** 
Posting 3 SIPs in related areas, and the shared end goal of SIP [65](https://github.com/apache/superset/issues/14472), 66 and [67](https://github.com/apache/superset/issues/14474) is to improve the time-to-value in creating meaningful charts using Superset. 
|Less disorganized and stand alone plug-ins| Cleaner Gallery modal and control layout | More powerful charts! 

### **Problem 2 - Control Panel Inconsistencies** 
Another challenge we face is that there is no systematic design pattern in the control panel to follow when a plug-in is added to Superset. All the plug-ins have their own set of control panel layout, and each set has 15 to 40 controls and labels, where even similar chart types don’t always share the same patterns. As a result, the overall learning curve of creating charts in Superset is relatively steep, and the chart creation process itself is also confusing, despite relatively limited chart customizability. In order to optimize time-to-chart and time-to-dashboard, all while improving chart customizability, we’ve identified a clear need of redesigning and strengthening commonly used charts by making controls more dynamic and standardizing chart control layouts. 

### **Proposed Solutions for Problem Dynamic controls**
Solution: Implement Dynamic controls in the Explore control panel. To minimize the distraction caused by controls that are either irrelevant to the current selection or are of lesser importance, the control panel should adapt to only show options that are relevant and downplay less important choices. Furthermore, options that are dependent on a “parent” option should visually indicate that they are part of a hierarchy, instead of both parent and child options being listed one after another on the control panel in a 1-dimensional manner.
Some pain points we have been experiencing in Explore

- New users usually spend a long time figuring out what each control does in the context of different plug-ins. 
- Users are forced to interact with the static Time Section or a specific control every time even though those controls are not relevant,
- Selection of control values are pre-populated, e.g. “Last Week” in the Time Range filter by default for performance despite the size of data or series type. 
- Users have to constantly switch between DATA and CUSTOMIZE tabs to tweak the series cosmetic lightly. 
- Users are given the option to select AGGREGATE FUNCTIONS that may not make sense to the dataset and query. 
- It takes multiple clicks and a full scroll down in a dropdown list to select a value that’s being used 95% of the time. 
- Users are confused by the select option of  5000 in row limit while there are only 200 rows in the dataset.
- ……….

The goal of this project is to only show the controls that are relevant to the selected dataset and chart type, dynamically and progressively within context; to show or pre-populate select values intuitively.

Furthermore, to be able to unleash the full potential of ECharts (see SIP-50), the control panel should make as many customization options available in the library as possible, while providing good default values out of the box. This will ensure that users get a good default chart with minimal effort, while still making it possible to customize the chart where needed. 

Currently Superset offers only a fraction of the available visual customization options made available by ECharts. For example, see the full list of customizations that are specific to line charts in ECharts: https://echarts.apache.org/en/option.html#series-line (this list excludes generic options, such as those relating to the axes, legends, titles etc). By creating a control panel that mostly follows the structure of the ECharts option object, we can ensure that all relevant options are made available to the user, and new ones are easily added as new versions of ECharts become available.

We will follow up with a detailed technical proposed solution.

Thanks for brainstorming: @villebro @mistercrunch @rusackas 🙏

**Comment by junlincc** [comment]
**Issue**
As a new user to Superset, I have been confused by the default behaviour in the Explore mode.

### Suggestions
**Time section**
issue: By default, only “last week”'s data are used. This filter is applied silently: a new user might not immediately notice that “Time range: Last week” means some data are not considered. And this can be quite puzzling if one deals with forecast (i.e. future) data, as the user then gets a “No Results” error.
suggestion: Don't apply filters by default — or if so, let the user know about them.
**Query/Metrics section**
issue: By default, COUNT(*) is selected (as the only pre-defined “metric”). This feels counter-intuitive to me, as I mostly know what chart I want to build, and it's almost never using COUNT(*) as main KPI. I then have the surprise/frustration of having a chart populated with something different from what I have in mind.
suggestion: Could we prevent the chart from “trying to be smart”, and:
have “metrics” non pre-filled,
don't run the query straight away, but wait for the user to first specify the chart/dashboard and them to click “run”.
The “Run” button could be greyed out/disabled as long as mandatory fields for the chart aren't populated yet.
**Query/Metrics section**
issue: I don't want to be forced to chose an aggregate. Indeed, the data I query are sometimes already “aggregated” (say I want to plot temperature over time by location and I have only one reading per location and per hour (at the *:00.000 timestamp)), and in that case “aggregating” seems counter-intuitive (even if, I agree, SUM, AVG, MIN, and MAX would return the same value). Yet when adding a Metric / Simple, the “Save” button is greyed out after I select a column, until I choose an aggregate.
suggestion: Allow users to not select any aggregate, and fail if multiple record for the same index are returned.
**Dataset / Columns panel**
issue: While most data types have an “icon” next to the column name (str ￫ ABC, timestamp ￫ 🕘 , int ￫ #), PostgreSQL “Double Precision” don't.
suggestion: Define an icon for it (same as float if exist, or something like #.##)?
Customize / {x, y} Axis / {x, y} axis format input
issue: I have metrics that have a unit (e.g. physical dimensions). Yet I am unable to specify this unit on the axis (e.g. .2f °C for temperature).
suggestion: Allow for adding arbitrary prefix/suffixes on top of the D3 formatting (… or provide an example in case it's already possible, as “some users” — read: myself — haven't been able to find how to) — cf. #14550.
Customize / {x, y} Axis / {x, y} axis format input
issue: The axis formatting allow for custom user inputs (when one simply type in the box). However, once one has typed a format string (say: ,.3f), it is not possible to correct it (e.g. to change it into ,.2f). Indeed, as soon as one type in the box again, the whole content is erased. This behaviour isn't error friendly and force the user to memorize what was the previous format string.
suggestion: Don't erase former input, but rather enable users to amend/modify the existing value.
Explore a whole dataset
issue: First go to the Data/Dataset menu. Then when clicking on a given dataset, the Explore panel opens. Yet the default query is basically SELECT COUNT(*) WHERE (timestamp ≥ now() - 7 AND timestamp < now()), in the Table chart's “Aggregate” query mode. As detailed above, this can cause some confusion.
suggestion: Set default query to SELECT * (possibly appending a LIMIT 100) and set the table in “Raw records” mode. Indeed, when I click on a dataset, I expect to see what's inside, raw — not an aggregate.

**Comment by cccs-jc** [comment]
Just wanted to up-vote this one
suggestion: Set default query to SELECT * (possibly appending a LIMIT 100) and set the table in “Raw records” mode. Indeed, when I click on a dataset, I expect to see what's inside, raw — not an aggregate.

**Comment by zhaoyongjie** [comment]
> Just wanted to up-vote this one
> suggestion: Set default query to SELECT * (possibly appending a LIMIT 100) and set the table in “Raw records” mode. Indeed, when I click on a dataset, I expect to see what's inside, raw — not an aggregate.

This feature can be use in sqllab instead of explore

**Comment by rusackas** [comment]
@junlincc is this still needed and is there any intent to carry it forward, or should we close it out and open a new one later if needed?

**Comment by villebro** [comment]
@rusackas @junlincc let's close it, this is such a big (and delicate) task I don't consider this realistic in the near term.

**Comment by rusackas** [comment]
Closing this and the SIP process on the project board. Holler if this needs further revisit/discussion!
