### ISSUE TITLE
no action option when hover over to left edge of a row in dashboard edit mode.

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#14479]
when the mouse hover over to the left edge of a row in dashboard  edit mode, action option, for example, delete  is not shown.

### Expected results
what you expected to happen:

action option (delete/setting) will show when hover over to the left edge of a row in dashboard edit mode

<img width="1391" alt="Screen Shot 2021-05-04 at 5 30 38 PM" src="https://user-images.githubusercontent.com/81597121/117087522-923edd80-ad04-11eb-8eff-390fdcec1bc6.png">

### Actual results

no action option showed when hover over to the left edge of a row in dashboard edit mode

https://user-images.githubusercontent.com/81597121/117087762-4b051c80-ad05-11eb-894b-51b01e308b16.mov

#### How to reproduce the bug

1. Go to dashboard 
2. Click on edit button and edit dashboard
3. add a row to the dashboard
4. hover over to the left edge to the new row

### Environment

- superset version: master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [Y] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rosemarie-chiu** [comment]
I found this is due to `DASHBOARD_NATIVE_FILTERS` feature flag. I only repo when that feature flag is on.

**Comment by rusackas** [comment]
This has been resolved with and without the `DASHBOARD_NATIVE_FILTERS` flag, so I'll call it closed. Please let me know if this rears its ugly head once again.
