### ISSUE TITLE
[bug] Although Slice model can not exists without datasource (sqltable) it possible to create model without datasource type

### ISSUE THREAD

**Issue by ofekisr** [apache/superset#14482]
Slice related and depend on it's datasource, it can't live without It. 
When we take attention to the code inside the Slice model, you can notice 
```python
 sqla.event.listen(Slice, "before_insert", set_related_perm)

def set_related_perm(_mapper: Mapper, _connection: Connection, target: Slice) -> None:
    src_class = target.cls_model
    id_ = target.datasource_id
    if id_:
        ds = db.session.query(src_class).filter_by(id=int(id_)).first()
        if ds:
            target.perm = ds.perm
            target.schema_perm = ds.schema_perm

@property
def cls_model(self) -> Type["BaseDatasource"]:
    return ConnectorRegistry.sources[self.datasource_type]

```
datasource_type is mandatory so it can't be null, it should be enforced 

### Expected results
when Inserting new slice without datasource type, exception should be raised 

(please complete the following information):

- superset version: 0.999.0dev
- python version: 3.8.6
- node.js version: `node -v`

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
