### ISSUE TITLE
Dremio does not support timestamp with microseconds precision

### ISSUE THREAD

**Issue by insatomcat** [apache/superset#14518]
Right now for almost any query in Dremio involving a timestamp, I get this error : 
`Error: gRPC returned internal error, with message: SYSTEM ERROR: GandivaException: Invalid millis for timestamp value 2021-04-30 00:00:00.000000 SqlOperatorImpl FILTER Location 0:0:7 Fragment 0:0 [Error Id: 44890e01-0767-4c25-9564-1ca746914fae on pf9bdanode106.applispfref.sipfref.local:0] (org.apache.arrow.gandiva.exceptions.GandivaException) Invalid millis for timestamp value 2021-04-30 00:00:00.000000 org.apache.arrow.gandiva.evaluator.JniWrapper.evaluateFilter():-2 `

This makes superset unusable with Dremio.

Is there any way to make superset not go above milliseconds precision with Dremio ?
Thanks a lot.

**Comment by insatomcat** [comment]
Thanks ! just to let you know that I tried your patch and that it indeed solves the problem !
Hopefully it will make it to master and then to release soon :)

**Comment by villebro** [comment]
Thanks for the help testing it - I'm sure it will make it into master soon and Superset 1.2 (I added the label so it will be cherried in)
