### ISSUE TITLE
[thumbnail]incorrect thumbnail is displayed until page refresh 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14532]
https://user-images.githubusercontent.com/67837651/117531028-3e96f300-af95-11eb-9f69-8ef9d0d8c4f0.mov

**Comment by felipekbca** [comment]
Try disable Flag CLIENT_CACHE in your superset_config.py.

```
DEFAULT_FEATURE_FLAGS = {
    "CLIENT_CACHE": False
}
```

or 

```
FEATURE_FLAGS = {
    "CLIENT_CACHE": False,
}
```
