### ISSUE TITLE
[Funnel]bug and enhancement request 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14534]
1. Add ORDER BY to get the top values when user select a row limit, currently showing random values

<img width="456" alt="Screen Shot 2021-05-07 at 11 38 22 PM" src="https://user-images.githubusercontent.com/67837651/117531503-98002180-af97-11eb-9c66-7ecbe5597325.png">

2. proper treatment for null value, currently funnel doesn't show when there's a null value 
<img width="1376" alt="Screen Shot 2021-05-07 at 11 32 37 PM" src="https://user-images.githubusercontent.com/67837651/117531567-e9101580-af97-11eb-92d0-028079d9b4e8.png">

**Comment by xiezhongfu** [comment]
The related discussion is https://github.com/apache-superset/superset-ui/pull/1006#discussion_r599332138
I misunderstood the discussion....   SHOULD add `orderby in SQL` to avoid random values
