### ISSUE TITLE
Improvement suggestions for the Explore mode

### ISSUE THREAD

**Issue by EBoisseauSierra** [apache/superset#14548]
## Issue

As a new user to Superset, I have been confused by the default behaviour in the Explore mode.

## Suggestions

1. _Time_ section
  * issue: By default, only “last week”'s data are used. This filter is applied silently: a new user might not immediately notice that “Time range: Last week” means some data are not considered. And this can be quite puzzling if one deals with forecast (i.e. future) data, as the user then gets a “No Results” error.
  * suggestion: Don't apply filters by default — or if so, let the user know about them.
2. _Query/Metrics_ section
  * issue: By default, `COUNT(*)` is selected (as the only pre-defined “metric”). This feels counter-intuitive to me, as I mostly know what chart I want to build, and it's almost never using `COUNT(*)` as main KPI. I then have the surprise/frustration of having a chart populated with something different from what I have in mind.
  * suggestion: Could we prevent the chart from “trying to be smart”, and:
    * have “metrics” non pre-filled,
    * don't run the query straight away, but wait for the user to first specify the chart/dashboard and them to click “run”.
  The “Run” button could be greyed out/disabled as long as mandatory fields for the chart aren't populated yet.
3. _Query/Metrics_ section
  * issue: I don't want to be forced to chose an aggregate. Indeed, the data I query are sometimes already “aggregated” (say I want to plot temperature over time by location and I have only one reading per location and per hour (at the `*:00.000` timestamp)), and in that case “aggregating” seems counter-intuitive (even if, I agree, `SUM`, `AVG`, `MIN`, and `MAX` would return the same value). Yet when adding a Metric / Simple, the “Save” button is greyed out after I select a column, until I choose an aggregate.
  * suggestion: Allow users to _not_ select any aggregate, and fail if multiple record for the same index are returned.
4. _Dataset / Columns_ panel
  * issue: While most data types have an “icon” next to the column name (str ￫ `ABC`, timestamp ￫ :clock9: , int ￫ `#`), PostgreSQL “Double Precision” don't.
  * suggestion: Define an icon for it (same as float if exist, or something like `#.##`)?
5. _Customize / {x, y} Axis / {x, y} axis format_ input
  * issue: I have metrics that have a unit (e.g. physical dimensions). Yet I am unable to specify this unit on the axis (e.g. `.2f °C` for temperature).
  * suggestion: Allow for adding arbitrary prefix/suffixes on top of the D3 formatting (… or provide an example in case it's already possible, as “some users” — read: myself — haven't been able to find how to) — cf. #14550.
6. _Customize / {x, y} Axis / {x, y} axis format_ input
  * issue: The axis formatting allow for custom user inputs (when one simply type in the box). However, once one has typed a format string (say: `,.3f`), it is not possible to _correct_ it (e.g. to change it into `,.2f`). Indeed, as soon as one type in the box again, the whole content is erased. This behaviour isn't error friendly and force the user to memorize what was the previous format string.
  * suggestion: Don't erase former input, but rather enable users to amend/modify the existing value.
7. Explore a whole dataset
  * issue: First go to the Data/Dataset menu. Then when clicking on a given dataset, the Explore panel opens. Yet the default query is basically `SELECT COUNT(*) WHERE (timestamp ≥ now() - 7 AND timestamp < now())`, in the Table chart's “Aggregate” query mode. As detailed above, this can cause some confusion.
  * suggestion: Set default query to `SELECT *` (possibly appending a `LIMIT 100`) and set the table in “Raw records” mode. Indeed, when I click on a dataset, I expect to see what's inside, raw — not an aggregate.

## Context

Observations above are based on Superset `1.1.0`.

**Comment by mistercrunch** [comment]
About "Last week" default filter the original intent was to be a bit defensive against full scan, but I do feel like it's falling short on this intention, especially as it may not hit an indexed or partitioned field. Some ideas:
- to prevent a "regression" or undesired change of behavior, we could have a "default time filter" global environment configuration, set the default to "No filter"
- datasets could have a default time range filter or default chart, so that a new chart flow would land on something that makes sense
- magic? introspect the dataset to define good default filters?

**Comment by nytai** [comment]
Can we make the default time filter smarter? Sending a preflight query to figure out the last timestamp in the dataset and then do a - 1 week from there or something reasonable. The time filter often ends up filtering out all data and it takes the user a while to figure out why the chart is blank despite all the form fields being populated

**Comment by mistercrunch** [comment]
Ideally we'd know things like:
- what's the main/most important datetime column here? (first one in the dataset flagged as temporal is likely to be good but not guaranteed to be that most important time column)
- what's the latest data point for that column? (depending on the indexing/partionning, figuring that out may require a full table scan and take some time, we could read the index definition if we wanted to do some magic)
- what's the time grain? (unclear how to figure that out reliably)

In any case, having that metadata for dataset is useful, and could be set by users. Things like primary metric, primary time column, default time filter, expected freshness, primary dimension, ...Then we can use these dataset settings to set defaults when creating new charts. We could also have a way to detect/guess these upon dataset creation, but let user alter/tweak them.

**Comment by EBoisseauSierra** [comment]
You are right that mileages may vary, and sending a full `SELECT *` without any filter (other than [the “last resort” ones](https://github.com/apache/superset/blob/3f6bd1e4a4498de765ce0ebd4c7700f3bdbfe0bb/superset/config.py#L125-L126)) isn't ideal! (Plus my suggestions don't take backward compatibility into consideration)
But as you mention, the “Last week” default isn't perfect, either because of too old data (cf. demo datasets)… or because — as in my particular `weather_forecast` scenario — we don't have _past_ data (I agree this isn't the most common, though).

I quite like the idea of being able to define a meaningful filter (or representative subset) per dataset (plus a global default setting — defined in `config.py` — for the whole instance). It could be via a filter on the most representative timestamp column, or simply a `LIMIT`.

However, I believe the main point I was trying to raise with §1 is that it's applying a filter _silently_ that affects the (new) user experience the most, as it's doing something they don't expect.
Not applying any filter is only one approach to tackle this. Other approaches could be informing the user more pro-actively ; or (visibly) applying the filter by default, but waiting for the user to (go through all settings/parameters and) click on “Run” to execute the query.

Shall we continue the discussion on #14473 (SIP-66) instead, where @junlincc has kindly cross-posted this issue?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and is more about feature requests than bug reporting. If you want to pick up the discussion relevant to more current versions (currently 3.x) please open a new Ideas discussion or a PR to address the problem.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and is a feature request rather than a bug. If this is relevant in current versions (currently 3.x) please open a new Ideas discussion or a PR to address the problem.
