### ISSUE TITLE
Improvement suggestions for the visualization type selector

### ISSUE THREAD

**Issue by EBoisseauSierra** [apache/superset#14549]
## Issue

As a new user to Superset, I have been a bit confused when selecting a visualization type.

## Suggestions
1. Be automagical!
  * issue: It is a bit confusing to have to select between two (or more) types of line charts — especially as there are little information available about how to decide when having to chose about it. Plus one may not know in advance which one to use, or one may change their mind after having clicked.
  * suggestion: Allow the user to simply select “line chart” as automagically use a regular line chart or a time-series line-chart, depending on whether the abscissa is of a Timestamp data type.
2. Group chart types
  * issue: The “Select a visualization type” tile is a list of all visualisations available. There are a lot of possibilities and one might not notice a given type of chart.
  * suggestions:
    * group charts per categories: Line charts, Bar charts, Maps, etc.
    * group charts per “function”/usage: e.g. one KPI only (big number, big number with line, indicator, bullet), one KPI vs time, data distribution, geographical data, etc. 

## Context

Observations above are based on Superset `1.1.0`.

**Comment by junlincc** [comment]
@EBoisseauSierra do you mind comment this in SIP-67? thanks
