### ISSUE TITLE
Password and Confirm Password missing while adding User in version 1.1.0

### ISSUE THREAD

**Issue by shikhnu** [apache/superset#14543]
Hi,

I am working with two different versions of the superset. One is 0.999.0dev and another 1.1.0. While working on RLS, in "Add User" I found some things missing in version 1.1.0 that was present in 0.999.0dev. The section where it was possible to add a password and confirm the password, is missing in version 1.1.0. I have attached screenshots for the same. I would like to know if it's the limitation of the version or is there a different way to achieve the goal.
Version 1.1.0
![Without pass](https://user-images.githubusercontent.com/56694179/117637398-63f74d00-b19f-11eb-8a57-8a17a4456def.PNG)
Version 0.999.0dev
![With pass](https://user-images.githubusercontent.com/56694179/117637406-65287a00-b19f-11eb-9425-4350355dfe4e.PNG)

Thank you in advance.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
