### ISSUE TITLE
Improvement suggestions for the “Edit Dataset” mode

### ISSUE THREAD

**Issue by EBoisseauSierra** [apache/superset#14550]
## Issue

As a keen user of Superset, I'd love to make the experience even better!

## Suggestions

1. Disable formatting timestamp for non-time columns
  * Issue: When customising a non-timestamp column (e.g. Text, or Integer), I am able to specify a Datetime format for this column… yet this doesn't make sense really.
  * Suggestion: Display the “Datetime format” input box for Timestamp-like (or “Is Temporal == True”) columns only.
2. Add a “Format” input for non-temporal columns
  * Issue: some of my columns represent physical dimensions or have units. Yet when building charts, they are displayed as “basic numbers”.
  * Suggestion: Add a “Format” imput box for non-temporal columns (and custom metrics) to allow users to define a default formatting for values and aggregates of this column (D3 formatting + prefix/suffix: e.g. `.2f °C` for a `temperature` column). When using this column in graphs (e.g. hourly average temperature vs. time), this configuration would be picked up automatically (unless locally overriden) to format the axes.

## Context

Observations above are based on Superset `1.1.0`.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and is a feature request rather than a bug. If this is relevant in current versions (currently 3.x) please open a new Ideas discussion or a PR to address the problem.
