### ISSUE TITLE
[Dashboard] The left side actions of a row are not showing when editing a dashboard

### ISSUE THREAD

**Issue by geido** [apache/superset#14554]
When editing a dashboard the left side actions of a row disappeared.

### Expected results

The left side actions of a row should appear on hover

### Actual results

The left side actions do not appear

<img width="1676" alt="Screen Shot 2021-05-10 at 20 40 25" src="https://user-images.githubusercontent.com/60598000/117701627-22cb6100-b1d0-11eb-85d9-eceeab2c73b6.png">

#### How to reproduce the bug

1. Go to a dashboard and enable the edit mode
2. Hover a row
3. You will observe no actions showing up on the left of the row

**Comment by geido** [comment]
@rusackas @junlincc

**Comment by junlincc** [comment]
Thank you for reporting! this is very valuable. :)

**Comment by pkdotson** [comment]
pr is out: https://github.com/apache/superset/pull/14587

**Comment by rusackas** [comment]
Closed by #14587
