### ISSUE TITLE
[User feedback] Tell me about your experience using the Superset home screen.

### ISSUE THREAD

**Issue by Steejay** [apache/superset#14552]
Hello Superset community! I'm a Product Designer that works on the design behind some of the features in Superset.

**I'd love to learn about your experience using the Superset home screen**.

Home screen experience without thumbnails

![image (31)](https://user-images.githubusercontent.com/60786102/117692746-2d570d80-b172-11eb-9435-87a32d194eee.png)

Home screen experience with thumbnails

![image (30)](https://user-images.githubusercontent.com/60786102/117692762-2fb96780-b172-11eb-98f9-77ef92a54c6b.png)

**Here are some questions we'd love to learn more about:**

- Tell me about the last time you used the home screen. What task were you trying to accomplish? What worked well? What didn't?
- What feature(s) are missing on the home screen?
- Is there anything on the home screen that isn't needed for you?
- If you could change the home screen in any way, what would you change?
- What is your favorite part of the home screen? Least favorite?
- Tell me about the last time you had a hard time using the home screen. What happened? How did you end up solving the issue?

**Please add your responses to the above questions in this thread and add a "👋🏼" at the end of your comment if you're interested in participating in continued user research in this area!** 

Your feedback is invaluable.  Thank you!

**Comment by junlincc** [comment]
@srinify let's including this user research in our next news letter if it's not too late? 🙏

**Comment by junlincc** [comment]
https://github.com/apache-superset/superset-roadmap/issues/106

**Comment by mistercrunch** [comment]
- page load is jittery, objects reposition themselves as they load/get filled in, we should use skeletons to prevent that
- On my favorite Superset instance, I always click on "Dashboard > Favorite" first to get to my most visited dashboards and I wish it would remember that. Let's make those toggles sticky across visits
- that dashboard that is my top-favorite is actually one of "mines" (should show on that default selected) but it's just not top 3. Showing only one row and 3 per row is very limited, I may have 9 favorite dashboards, I certainly have more than 3! My expectation would be to see at least 5 dashboards per row, and at least two rows, maybe 3, maybe more and scollable? I  just generally want to see a lot more thumbnails on that page!!!
- shouldn't carets be on the right side of the labels? seems inconsistent with how we use them elsewhere
- padding looks funky on no-thumb cards, seems like left-right should be higher number than top-bottom or something

**Comment by mistercrunch** [comment]
Usage metrics would really help here to sort things out. It seems it'd be keep tab of views `(user, object, objet_type, day, count)` or something like that to be able to sort based on overall popularity or on personal usage frequencies.

**Comment by radhakvnr** [comment]
Hi one note from my side. If I am a gamma user without having access to SQL lab. I still see the "Saved Queries" section in home screen which will provide the link to SQL lab. But in Menu I will not have the SQL lab but through home screen I can click on SQL lab and it will open a SQL lab. Hope this should be consider in next release

**Comment by EBoisseauSierra** [comment]
> <sub>_This one might be a little bit out of topic, so don't hesitate to let me know whether I'd rather should raise a new issue._</sub>

When “View[ing] all” {charts, dashboards}, we have filters on the top bar:

![Screenshot from 2021-06-03 13-16-39_shadow](https://user-images.githubusercontent.com/37387755/120636536-0983a080-c46e-11eb-898d-983c21f218b5.png)

However, there is little difference when no filter is applied (see above) vs when one looks at a _subset_ of “all” the dashboards:

![Screenshot from 2021-06-03 13-18-15_shadow](https://user-images.githubusercontent.com/37387755/120636685-346df480-c46e-11eb-803a-6773a2e3d5a8.png)

(Did you spot “Favourite: Any” changed to “Favourite: Yes”? It took me 3 days!)

Because filtering is persistent from one session to the other (as far as I can tell), it can be a bit confusing (as I'd naively expect to see _every_ dashboard when I click on “View All”).

➥ I don't think that making filtering persistent across session is a bad thing, but perhaps **“dimming” non-active filters could help make filters which actually filter out some dashboards standout more**.

**Comment by vladsocaciu** [comment]
I think every app home page should be the page that users click to navigate to most often, and we as app designers should save them this click.

Personally, I log in to build dashboards, and my users log in to view them. Saved queries and charts are just tools to build dashboards, but I never go to the home page to pick one up. Considering this, I would set the Dashboards list as the default home page and, in the same spirit of reducing clicks, enhance it with a small top list of the most recently updated dashboards, as thumbnails.

I may be biased against dashboards though, I think they tend to be used as duplicated (, cluttered and less functional) navigation.

The other common use case for dashboards is showing application specific metrics, like most active users, latest content changes, etc. But I think this should also be a standalone page, unless that info is very important and should be reviewed often and by most users.

Another approach would be to give admins control over which url is the home page. They could set it to load the dashboards list, or even a custom built dashboard.

👋🏼

**Comment by MM-Lehmann** [comment]
I would quite love an announcement bar/banner at the top just below the navigation bar.
This could be used to inform users of pending server maintenance or recent events.
I am currently playing around with the LOGO_RIGHT_TEXT variable in `config.py` but its not flexible enough and uses to little space.

**Comment by simonvanderveldt** [comment]
+1 for what @vladsocaciu described.
Pretty much never use the dashboard, always go via the menu to the place I'm trying to go. This is not always the same thing though, so not sure a sane default is possible. But even if the default would be the dashboard list at least in some cases it would be the correct starting point, whereas right now it never is :)
