### ISSUE TITLE
duckdb as DataSource

### ISSUE THREAD

**Issue by ravikishorer** [apache/superset#14563]
**Is your feature request related to a problem? Please describe.**
To be able to connect to Duckdb as datasource.

**Describe the solution you'd like**
To be able to connect to Duckdb just like how easy it is to connect to sqlite currently.

**Describe alternatives you've considered**
Sqlite is an alternative. But as Duckdb is more performant for analytical use cases, it will be a great addition.

**Additional context**
DuckDB is an in-process SQL OLAP database management system - https://duckdb.org/. It is much faster than sqlite for analytical purposes. 

From https://duckdb.org/docs/api/python,
_The standard DuckDB Python API provides a SQL interface compliant with the DB-API 2.0 specification described by PEP 249 similar to the SQLite Python API._

**Comment by srinify** [comment]
hi @ravikishorer this is cool! Do you know how mature the sqlalchemy dialect is for duckdb? This thread seems to imply its still very early: https://github.com/duckdb/duckdb/issues/305

I should have some time next week to play with DuckDb <> Superset

**Comment by ravikishorer** [comment]
@srinify I'm not fully aware. Based on the documentation, it is based on postgres dialect and in the issue you have attached, someone has implemented a very basic engine wrapping postgres one - https://pypi.org/project/duckdb-engine/

**Comment by Mause** [comment]
That someone was me - if you have any questions or suggestions for how I have implemented it, feel free to tag me :)

**Comment by terekete** [comment]
Q. With DuckDB I see its has some support for Apache Arrow. Is there some capabilities between DuckDB and Superset to take advantage of arrow format ?

**Comment by armando-fandango** [comment]
> I forked both [duckdb-engine](https://github.com/alitrack/duckdb_engine) and [superset](https://github.com/alitrack/superset), and made superset support duckdb now.
> 
> [db_engine_specs/duckdb.py](https://github.com/alitrack/superset/blob/master/superset/db_engine_specs/duckdb.py) is simply copy and modify from db_engine_specs/sqlite.py
> 
> and here is the video https://www.bilibili.com/video/BV1zQ4y1q7ti/

@alitrack Did you send the pull request in for your solution for duckdb please ?

**Comment by alitrack** [comment]
> > I forked both [duckdb-engine](https://github.com/alitrack/duckdb_engine) and [superset](https://github.com/alitrack/superset), and made superset support duckdb now.
> > [db_engine_specs/duckdb.py](https://github.com/alitrack/superset/blob/master/superset/db_engine_specs/duckdb.py) is simply copy and modify from db_engine_specs/sqlite.py
> > and here is the video https://www.bilibili.com/video/BV1zQ4y1q7ti/
> 
> @alitrack Did you send the pull request in for your solution for duckdb please ?

yes, I did.

**Comment by alitrack** [comment]
@armando-fandango my PR is merged.

**Comment by rwhaling** [comment]
took the liberty of opening up a PR from @alitrack's fork, since this is awesome and it looks like the sqlalchemy side is unblocked.
