### ISSUE TITLE
Keyboard navigation in Explore control panel

### ISSUE THREAD

**Issue by GregOnEvo** [apache/superset#14574]
Keyboard navigation in the control panel of the Explore view is difficult.

### Expected results

You should be able to move focus between adjacent controls in the control panel with a single Tab key press
and visually distinguish what element has focus. You should be able to interact with controls the keyboard
(Enter or space bar for button-like things).

### Actual results

Several tab key presses are required to move between controls, and focus is not always visible.

#### How to reproduce the bug

1. Go to a chart in Explore view (from Welcome or Chart List).
2. Click on a control in the control panel (e.g. 'TIME COLUMN') to focus that control.
3. Press the tab key
4. The next control (e.g. 'TIME GRAIN') should be focused, but focus seems to disappear. (in this case,
   a second tab press will move focus to the expected place).

### Environment

(please complete the following information):

- superset version: `master` branch, but has been present since at least `0.38`
- python version: `3.7.10`
- node.js version: `v14.6.1`
- npm version: `7.12.1`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

This seems to mostly stem from `ControlHeader` being treated as a button (including `tabindex` and `role`) in 
order to emulate the browser's behavior when clicking on a form `label` for custom elements. For most
controls, including the HTML `for` attribute will result in the desired behavior (some components, like
`Checkbox`, will still need the click handler).

For components that correctly get focus (most notably here the `CollapsePanel` headers), there needs to be a
visual indicator, possibly the same as the hover style.

Some of the more complex components will be affected by the outcome of [SIP-62](https://github.com/apache/superset/issues/14114)

**Comment by junlincc** [comment]
@maxhui this one is in your domain. let's try 😉

**Comment by Dapid** [comment]
Is there any planned work? This would go a long way towards WACG accessibility.

**Comment by rusackas** [comment]
There has been a fair amount of work here, and more progress being made. That said, this issue isn't a bug, and is fairly out of date. Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people want to contribute, please open small issues about specific shortcomings, or open some PRs to whittle away at things!
