### ISSUE TITLE
[setting] edges were cutting on settings menu

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#14599]
## Screenshot

<img width="1773" alt="Screen Shot 2021-05-12 at 9 33 49 PM" src="https://user-images.githubusercontent.com/81597121/118078008-1e3ab000-b36a-11eb-955b-94fcd3c89956.png">

## Description

Right edge and bottom of the settings menu are cut

**Comment by junlincc** [comment]
Right edge is looking ok on master, the bottom does need some paddddddding. 🤦🏾‍♀️

**Comment by geido** [comment]
Having a look

**Comment by geido** [comment]
@junlincc 

The menu looks fine on master

![Screen Shot 2021-05-17 at 14 21 10 (2)](https://user-images.githubusercontent.com/60598000/118480660-38361300-b71b-11eb-96c5-d81d1e52eb34.png)

**Comment by michael-s-molina** [comment]
@junlincc @geido https://github.com/apache/superset/pull/14557 fixed the `About` padding.  We can close this issue.

**Comment by jinghua-qa** [comment]
Verified fixed
