### ISSUE TITLE
Unable to change database from Edit Dataset modal

### ISSUE THREAD

**Issue by yousoph** [apache/superset#14592]
When using the Edit Dataset modal to change a dataset to a table in a different database, the changes do not get saved. 

#### How to reproduce the bug

1. Go to the Datasets page
2. Click the edit icon on an existing Physical dataset
3. In the Edit Dataset modal, click the lock icon to make changes to the dataset 
4. Select a different database from the current database. Then select a schema/table 
5. Save changes
6. Open the Edit Dataset modal again

### Expected results
The changes should be reflected and the user should see the new database/schema/table in the Edit Dataset modal

### Actual results
The previous database name is still displayed and the dataset didn't get updated with the changes that were made 

### Environment
- superset version: `master`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
just realized this bug was priporized 2 months ago but didn't make it into the bash project broad. @yousoph we will take care of it :) 

@geido 🙏
