### ISSUE TITLE
Metrics sidebar isn't sorts by metric name, even if the label is what's visible in the sidebar.

### ISSUE THREAD

**Issue by cooley-pe** [apache/superset#14594]
## Screenshot

![Screen Shot 2021-05-12 at 3 26 57 PM](https://user-images.githubusercontent.com/64038793/118051839-8c657f80-b336-11eb-866c-d979ba829744.png)

![Screen Shot 2021-05-12 at 3 23 24 PM](https://user-images.githubusercontent.com/64038793/118051853-925b6080-b336-11eb-96f4-d71d0f5c53f3.png)

## Description

When a label is a applied to a saved dataset metric, the metrics sidebar is sorted by the **metric name** event though the **label name** is what's shown.

## Design input

Personally, I would prefer to use the metric name in the sidebar and the label in the chart. This would allow for operational names (i.e. Long, alpha-friendly names) in the metrics sidebar and shorter, user-friendly labels in the charts themselves. 

At the very least the sorting should be based on what is shown in the sidebar.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
