### ISSUE TITLE
[Explore]scroll bar overlay in edit dataset modal

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14596]
<img width="1391" alt="Screen Shot 2021-05-12 at 5 11 28 PM" src="https://user-images.githubusercontent.com/67837651/118059339-2cc2a080-b345-11eb-8389-fe84b1c98829.png">

**Comment by pkdotson** [comment]
@junlincc is there particular browser this is happening in because i can't repo it in chrome or firefox

**Comment by pkdotson** [comment]
This seems to only happen in chrome and it's not the datasetmodal select scroll, it's the controls tabs scroll that overlays  if i resize the page but it goes away as you stop resizing the page. This seems to be more of a browser issue than it is code.

https://user-images.githubusercontent.com/17326228/118564337-ff9b3700-b724-11eb-8b62-11950a22a6ce.mov

**Comment by junlincc** [comment]
Hi @pkdotson this happens when there is a long enough dropdown select open in the modal AND when you hover out side the modal to scroll. it's hard to reproduce, but i assume you can find out what's wrong in the code? idk. 🤔

**Comment by junlincc** [comment]
really hard to repro, letting it go for now.
