### ISSUE TITLE
[SQL lab] 3 dot menu in SQL editor 

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#14600]
## Screenshot

<img width="1358" alt="Screen Shot 2021-05-12 at 1 39 34 PM" src="https://user-images.githubusercontent.com/81597121/118082044-5a254380-b371-11eb-9b06-65fbe6af43f1.png">

## Description
3 dot menu dislocated

**Comment by junlincc** [comment]
lol... that's a regression from menu refractoring... i think

@rusackas

**Comment by geido** [comment]
I am having a look at this

**Comment by geido** [comment]
@junlincc this issue looks resolved in master

<img width="1396" alt="Screen Shot 2021-05-13 at 13 22 39" src="https://user-images.githubusercontent.com/60598000/118112955-5aafef80-b3ee-11eb-8ab3-f4e8ac0226fc.png">

**Comment by junlincc** [comment]
Thank you @geido i believe this solved by your PR. https://github.com/apache/superset/pull/14566
