### ISSUE TITLE
[cosmetic] deck.gl arc chart has elements overlapped in explore panel

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#14606]
## Screenshot
<img width="1792" alt="Screen Shot 2021-05-12 at 3 45 26 PM" src="https://user-images.githubusercontent.com/81597121/118101725-c19cbc80-b38c-11eb-8139-5ec18cf5020a.png">

**Comment by rusackas** [comment]
Relates to #14605, #14607

**Comment by geido** [comment]
I am checking this out

**Comment by geido** [comment]
It will be resolved when both PRs #14663 - #14655 get merged

**Comment by geido** [comment]
@jinghua-qa This should be solved by now. Please have a look
