### ISSUE TITLE
[explore] grouped bar chart can not be saved

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#14603]
after changing bar chart to be grouped, tried save the change, but the bar chart still showed in stacked. 

### Expected results

grouped bar chart can be saved.

### Actual results

grouped bar chart can not be saved.

#### How to reproduce the bug

repo steps:
1, open a bar chart (i used Total Sales per Market)
2, click on the Group option in the chart
3, save the changes

https://user-images.githubusercontent.com/81597121/118100289-23f4bd80-b38b-11eb-818e-d7dae02cf3f2.mov

### Environment

- superset version: master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [Y] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
thanks for reporting. unfortunately, we are not planning to fix this issue. 😞
