### ISSUE TITLE
[cosmetic] deck.gl grid chart have elements overlapped in explore panel

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#14607]
## Screenshot
<img width="323" alt="Screen Shot 2021-05-12 at 3 50 38 PM" src="https://user-images.githubusercontent.com/81597121/118102081-31ab4280-b38d-11eb-9083-d3196d8a22e0.png">

**Comment by rusackas** [comment]
Relates to #14605, #14605

**Comment by geido** [comment]
I am checking this out
