### ISSUE TITLE
[cosmetic] deck.gl scatterplot explore panel have some elements overlap

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#14605]
## Screenshot

<img width="1789" alt="Screen Shot 2021-05-12 at 3 59 55 PM" src="https://user-images.githubusercontent.com/81597121/118101258-3fac9380-b38c-11eb-9841-6de2cce3ee5e.png">

**Comment by rusackas** [comment]
Relates to #14606, #14607

**Comment by geido** [comment]
I am checking this out
