### ISSUE TITLE
[explore] multi-line chart disappear when unselect the markers in CUSTOMIZE

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#14608]
when unselect the markers in multi-line chart, the chart disappear

### Expected results

marker will disappear by unselect the marker option in customer

### Actual results

the chart with the marker disappear

#### How to reproduce the bug

1. open a multi line chart in explore
2. go to 'CUSTOMIZE'
3. select 'show markers'
4. unselect 'show markers'

https://user-images.githubusercontent.com/81597121/118103092-5f44bb80-b38e-11eb-8f1c-d9b66954b963.mov

### Environment

- superset version: master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [Y] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
thanks for reporting, no plan to address this issue. chart will be gone soon😉.  🙏
