### ISSUE TITLE
[cosmetic] 3 dot menu in dashboard dislocated

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#14613]
3 dot menu in dashboard dislocated
## Screenshot
<img width="1786" alt="Screen Shot 2021-05-13 at 2 29 24 AM" src="https://user-images.githubusercontent.com/81597121/118107077-3115aa80-b393-11eb-96a5-806b0c4bd7b9.png">

**Comment by junlincc** [comment]
https://github.com/apache/superset/pull/14566 resolved in master
