### ISSUE TITLE
[cosmetic][sql lab] tooltip of table title dislocated

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#14614]
## Screenshot
<img width="1789" alt="Screen Shot 2021-05-12 at 9 46 53 PM" src="https://user-images.githubusercontent.com/81597121/118107612-d3ce2900-b393-11eb-8fd6-f9ff98f2e171.png">

**Comment by zhouyao1994** [comment]
looks gread

**Comment by junlincc** [comment]
lol...... 
@jinghua-qa can you validate issues on master when filing a bug. they might have been resolved.....

**Comment by jinghua-qa** [comment]
This issue persist in master

**Comment by junlincc** [comment]
@eschutho Hi Elizabeth, could we bash on this one?

**Comment by eschutho** [comment]
hi, yes, are you asking if we can fix it?

**Comment by geido** [comment]
I am fixing this one
