### ISSUE TITLE
[cosmetic] 3 dot menu of the chart in dashboard dislocated

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#14612]
## Screenshot
<img width="576" alt="Screen Shot 2021-05-11 at 8 24 31 PM" src="https://user-images.githubusercontent.com/81597121/118106323-57871600-b392-11eb-8f1b-626931c205ec.png">

**Comment by junlincc** [comment]
<img width="1644" alt="Screen Shot 2021-05-14 at 8 11 11 AM" src="https://user-images.githubusercontent.com/67837651/118291023-f6436d80-b48b-11eb-8225-92a3e1dd8e0a.png">
fixed in master
