### ISSUE TITLE
[share chart] share chart email message is not correct

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#14611]
When user share chart in dashboard, the email message is not correct.  See screenshot

### Expected results

share email show correct message with share chart information

### Actual results
share email message is not correct 

#### Screenshots

<img width="1756" alt="Screen Shot 2021-05-11 at 8 21 38 PM" src="https://user-images.githubusercontent.com/81597121/118105660-82bd3580-b391-11eb-8c14-1fc1bd93b908.png">

#### How to reproduce the bug

repo steps
1, go to dashboard with charts
2, click on the 3 dot menu on one of the chart
3, select share chart by mail
4, wait for the mail to pop with message of the share

### Environment

(please complete the following information):

- superset version: master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [Y] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
cc @willbarrett

**Comment by willbarrett** [comment]
This is not part of the alerts system @junlincc

**Comment by michael-s-molina** [comment]
@junlincc Working on it.
