### ISSUE TITLE
[cosmetic][Alerts & Reports] Submenu of Alert and Report execution log is off

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#14616]
## Screenshot
Alerts
<img width="1786" alt="Screen Shot 2021-05-13 at 1 02 06 AM" src="https://user-images.githubusercontent.com/81597121/118109215-bef29500-b395-11eb-89ff-2bf5b7dbd35d.png">

Reports
<img width="1792" alt="Screen Shot 2021-05-13 at 1 08 53 AM" src="https://user-images.githubusercontent.com/81597121/118109496-2577b300-b396-11eb-84c3-a5856da13eb8.png">
## Description

Submenu of the alert execution log separated into 2 lines

repo:
1, go to Alerts, hoover over 'action' and click on the 'execution log'
2, go to Reports, hoover over 'action' and click on the 'execution log'

**Comment by pkdotson** [comment]
pr is out: https://github.com/apache/superset/pull/14631

**Comment by rusackas** [comment]
Closed by #14631. We can always reopen if anything needs further attention.
