### ISSUE TITLE
[cosmetic] Submenu on Annotation page is off

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#14617]
## Screenshot
<img width="1792" alt="Screen Shot 2021-05-12 at 8 45 27 PM" src="https://user-images.githubusercontent.com/81597121/118109883-974ffc80-b396-11eb-923f-713ba67b7bed.png">

## Description
Submenu on Annotation menu is off

repo:
1, go to Annotation page in Annotation layer, look for submenu

**Comment by pkdotson** [comment]
thanks for reporting this

**Comment by pkdotson** [comment]
pr is out: https://github.com/apache/superset/pull/14631

**Comment by rusackas** [comment]
Closed by #14631. We can always reopen if anything needs further attention.
