### ISSUE TITLE
User Input acquisition through dashboard 

### ISSUE THREAD

**Issue by EBoisseauSierra** [apache/superset#14622]
## Issue

As a dashboard designer, I want users to input parameters to increase dashboard interactivity.

## Wished for solution

I would like to be able to retrieve parameters passed by a dashboard user in the following form:

* Number input
  _Example:_ Define the initial offset to pass to a cumulative-sum graph.
* Slider
  _Example:_ Let the user play around forecast's interval confidence
* Toggle switch
  _Example:_ Whether to display advanced metrics, show forecast, split by categories, etc.
* Radio items
  _Example:_ Switch the currency graphs are reported in.
* Tick boxes
  _Example:_ Select metrics to plot on a multi-KPI line chart.

In a nutshell, most of the various types of the [HTML `<input>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input).

The parameters could have pre-defined default values or not. They should affect the user session only — but we might want to have values persist over subsequent sessions. List of checkboxes/radio items should be either dashboard-designer defined, or dynamically generated from a data table (say using `SELECT DISTINCT` to get the various possible options).

The user inputs could be used either as parameters in:

- query,
- charts parameters,
- dashboard contents (with logic like: if toggle on, then this chart, else that one).

## Alternatives

* Filters are not exactly the solution here, as it's not about about slice & dice.
* We have hacked a way to define constants to be later reused in charts (for “start of the day stock” offset) by piggybacking on a dataset metrics, but it isn't really sustainable.

**Comment by EBoisseauSierra** [comment]
Note that I am aware that this feature request isn't a minor addition to Superset, and that even in itself, some of the features (e.g. logic to control dashboard content) are more complex/long term ambitions than others (e.g. use a number input to define `LIMIT <x>` in a query).

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and is a feature request rather than a bug. If there is still interest in making this happen in current versions (currently 3.x, soon 4.0) please open a new Ideas discussion or a PR to address the solution.
