### ISSUE TITLE
Unable to send email report , getting "535, b'5.7.0 authentication failed'"

### ISSUE THREAD

**Issue by dba1307** [apache/superset#14623]
Hi Guys,
I am running SuperSet v1.1.0 on docker compose and it is running fine except the reporting and alerting. I have try schedule the report but I am getting this msg "535, b'5.7.0 authentication failed'". I have check the SMTP setting on my server and It doesn't require any login id and password, so I have remove the parameter from the config as well. Can anyone please let me know how I can fix this issue 

Please find the config what I am using as of now with my docker images

from celery.schedules import crontab
from cachelib.redis import RedisCache
#SQLALCHEMY_DATABASE_URI = "postgresql+psycopg2://pguser:pgpwd@some.host/superset"
SQLALCHEMY_ECHO = True

FEATURE_FLAGS = {
    "ALERT_REPORTS": True,
    "THUMBNAILS": True,
    "LISTVIEWS_DEFAULT_CARD_VIEW" : True,
    "THUMBNAILS_SQLA_LISTENERS": True,
}

SIP_15_ENABLED = True

CACHE_CONFIG = {
    'CACHE_TYPE': 'redis',
    'CACHE_DEFAULT_TIMEOUT': 60 * 60 * 24, # 1 day default (in secs)
    'CACHE_KEY_PREFIX': 'superset_results',
    'CACHE_REDIS_URL': 'redis://<hostname>:6379/0',
}

DATA_CACHE_CONFIG = {
    'CACHE_TYPE': 'redis',
    'CACHE_DEFAULT_TIMEOUT': 60 * 60 * 24, # 1 day default (in secs)
    'CACHE_KEY_PREFIX': 'superset_results',
    'CACHE_REDIS_URL': 'redis://<hostname>:6379/0',
}

REDIS_HOST = "<hostname>"
REDIS_PORT = "6379"

class CeleryConfig:
    BROKER_URL = 'redis://%s:%s/0' % (REDIS_HOST, REDIS_PORT)
    CELERY_IMPORTS = ('superset.sql_lab', "superset.tasks", "superset.tasks.thumbnails", )
    CELERY_RESULT_BACKEND = 'redis://%s:%s/0' % (REDIS_HOST, REDIS_PORT)
    CELERYD_LOG_LEVEL = 'DEBUG'
    CELERYD_PREFETCH_MULTIPLIER = 10
    CELERY_ACKS_LATE = True
    CELERY_ANNOTATIONS = {
        'sql_lab.get_sql_results': {
            'rate_limit': '100/s',
        },
        'email_reports.send': {
            'rate_limit': '1/s',
            'time_limit': 600,
            'soft_time_limit': 600,
            'ignore_result': True,
        },
    }
    CELERYBEAT_SCHEDULE = {
        'cache-warmup-hourly': {
        'task': 'cache-warmup',
        'schedule': crontab(minute=0, hour='*'),  # hourly
        'kwargs': {
            'strategy_name': 'top_n_dashboards',
            'top_n': 5,
            'since': '7 days ago',
            },
          },
        'reports.scheduler': {
            'task': 'reports.scheduler',
            'schedule': crontab(minute='*', hour='*'),
        },
        'reports.prune_log': {
            'task': 'reports.prune_log',
            'schedule': crontab(minute=0, hour=0),
        },
       'email_reports.schedule_hourly': {
            'task': 'email_reports.schedule_hourly',
            'schedule': crontab(minute=1, hour='*'), # At minute 1, every hour
        },
    }

CELERY_CONFIG = CeleryConfig
RESULTS_BACKEND = RedisCache(host='<hostname>', port=6379, key_prefix='superset_results')

SCREENSHOT_LOCATE_WAIT = 100
SCREENSHOT_LOAD_WAIT = 600

# Slack configuration
SLACK_API_TOKEN = "xoxb-"

# Email configuration
SMTP_HOST = "<smtp.address>" #change to your host
SMTP_STARTTLS = True
SMTP_SSL = False
SMTP_PORT = 25 # your port eg. 587
SMTP_MAIL_FROM = "xxx@xxx"
EMAIL_REPORT_FROM_ADDRESS = "xxx@xxx"
EMAIL_REPORTS_SUBJECT_PREFIX = "[Report] "

ENABLE_SCHEDULED_EMAIL_REPORTS = True
EMAIL_NOTIFICATIONS = True
ENABLE_ALERTS = True

WEBDRIVER_TYPE = "firefox"
WEBDRIVER_WINDOW = {"dashboard": (1600, 2000), "slice": (3000, 1200)}
WEBDRIVER_OPTION_ARGS = [
    "--force-device-scale-factor=2.0",
    "--high-dpi-support=2.0",
    "--headless",
    "--disable-gpu",
    "--disable-dev-shm-usage",
    "--no-sandbox",
    "--disable-setuid-sandbox",
    "--disable-extensions",
]

# This is for internal use, you can keep http
WEBDRIVER_BASEURL="http://superset_app:8080"
# This is the link sent to the recipient, change to your domain eg. https://superset.mydomain.com
WEBDRIVER_BASEURL_USER_FRIENDLY="http://localhost:8088"
#SUPERSET_WEBSERVER_DOMAINS = ['0.0.0.0']

Please find the Screenshot for your reference.

![image](https://user-images.githubusercontent.com/3584207/118150923-fcddd080-b40a-11eb-8b82-41905d6bf200.png)

**Comment by oBoMBaYo** [comment]
@dba1307 I'm facing the same issue. How to solve it?

**Comment by dba1307** [comment]
In my config only EMAIL_REPORTS_USER = '<username>' was missing after adding this parameter its working for me.

**Comment by oBoMBaYo** [comment]
@dba1307 Thank you.
