### ISSUE TITLE
Connect to AWS Elasticsearch instance

### ISSUE THREAD

**Issue by vineetalagh** [apache/superset#14642]
I am trying to create a new database connection to AWS Elasticsearch instance. Following the documentation, I tried the connection URL :
elasticsearch+host:443

 host is  AWS ES Endpoint. 

No user password is there for the AWS ES Endpoint. AWS ES VPC is paired with VPC where Superset is running so a network connection is accessible.

### Actual results

It should connect

#### How to reproduce the bug

1. Go to 'Databases' --> Create a new database connection to AWS Elastic Endpoint.
2. See error

### Environment

- superset version: 1.0.1
- python version: 3.8
- node.js version: 12

**Comment by scimas** [comment]
You need to use a different connection string for AWS ES. https://github.com/preset-io/elasticsearch-dbapi#special-case-for-sql-opendistro-endpoint-aws-es
