### ISSUE TITLE
API Datetime values do not contain timezone

### ISSUE THREAD

**Issue by mgorsk1** [apache/superset#14645]
I have noticed that when using Superset REST API returned results do not contain timezone information for attributes related to time.

### Expected results

When i query `api/v1/dashboard/1` the returned result contain `changed_on` with timezone information.

### Actual results

```
 'result': {'changed_by': None,
            'changed_by_name': '',
            'changed_by_url': '',
            'changed_on': '2021-05-14T16:15:18.161551',
            'charts': ['Region Filter',
```

#### Screenshots

n/a

#### How to reproduce the bug

1. Checkout superset code
2. Run `docker-compose -f docker-compose-non-dev.yml up -d`
3. Run below code:

```
import requests

s = requests.Session()

token = s.post('http://localhost:8088/api/v1/security/login', json=dict(username='admin', password='admin', provider='db'))
token = token.json()['access_token']

print(s.get('http://localhost:8088/api/v1/dashboard/1', headers={'Authorization': f'Bearer {token}'}).json()['result']['changed_on'])
```
4. Notice value without timezone info

### Environment

(please complete the following information):

- superset version: latest master (`74473e2ad1975150a6dc578d67aae05de5ba4b02`)

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by nytai** [comment]
Unfortunately the timestamps are being stored without timezone, for this reason we suggest keeping the server in UTC and basing everything off of that assumption

**Comment by mgorsk1** [comment]
thanks @nytai , uderstood
