### ISSUE TITLE
[cosmetic] submenu spacing 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14643]
Expected ui
<img width="641" alt="Screen Shot 2021-05-14 at 8 02 02 AM" src="https://user-images.githubusercontent.com/67837651/118289977-c2b41380-b48a-11eb-8825-d9d104e84fb6.png">

Current
<img width="746" alt="Screen Shot 2021-05-14 at 8 01 54 AM" src="https://user-images.githubusercontent.com/67837651/118290000-c9428b00-b48a-11eb-82a4-05212c56de1d.png">

**Comment by pkdotson** [comment]
pr is out: https://github.com/apache/superset/pull/14631

**Comment by rusackas** [comment]
Closed by https://github.com/apache/superset/pull/14631
