### ISSUE TITLE
[Tree chart] metric control disappeared

### ISSUE THREAD

**Issue by stephenLYZ** [apache/superset#14654]
The tree chart's metric control disappeared when switching from pie chart to tree chart.

### Expected results
![image](https://user-images.githubusercontent.com/11830681/118390772-77a12880-b663-11eb-8486-eb02eeb8a37d.png)

### Actual results
![image](https://user-images.githubusercontent.com/11830681/118390755-57716980-b663-11eb-9671-a886abd1c007.png)

#### How to reproduce the bug

1. Go to 'Explore'
2. Select 'Pie Chart'
3. Switch to 'Tree Chart'

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by stephenLYZ** [comment]
Not only pie chart. It can be reproduced that as long as a single metric chart is switched to a tree chart.

**Comment by michael-s-molina** [comment]
@junlincc Working on it.

**Comment by junlincc** [comment]
thank you team for reporting and picking it up proactively! @stephenLYZ @michael-s-molina 🙏
