### ISSUE TITLE
[Explore] Display a user friendly prompt to select required fields when new chart is created

### ISSUE THREAD

**Issue by kgabryje** [apache/superset#14669]
## Screenshot

![image](https://user-images.githubusercontent.com/15073128/118528200-5a8f5700-b742-11eb-9dff-f8b5ae460281.png)

## Description

After changes introduced in https://github.com/apache/superset/pull/14661, an initial state of a newly created chart is blank - no metrics are preselected. Since metrics are required in most of the viz types, the first thing that user sees is a warning message (see the screenshot). We probably should use a more user-friendly message component, like some blueish info alert (and maybe something like a short tutorial to create a chart?), to prompt them to fill the controls.

**Comment by junlincc** [comment]
@mihir174 @steejay 

Responding to user requests, we removed default time filter value” last week” along with “COUNT()” in metric. user will no longer need to start with removing all the annoying default values when making a query but the downside is, when user enter into Explore, the first thing they see is a yellow warning message promoting for metrics, or whatever the required field is. we would need some help on designing the empty state UI. 🙏

**Comment by Steejay** [comment]
For sure. An empty state for this makes sense. For now can we hide errors and alerts at this stage? If a new chart is created and the user hasn't hit 'run' yet we shouldn't show error states in the control panel and an alert message in the chart area.

**Comment by junlincc** [comment]
@Steejay yes we can, will it make sense to have a blue/green msg to prompt user input though?

**Comment by Steejay** [comment]
I dont think so. When a user creates a new chart, the workspace presented shows a multitude of options in the control panel to fill in. My assumption is that a user will know that to visualize any data they would need to first define the constraints in the panel. as an mvp solution we can hide alerts/errors at this state so the user starts off with a clean canvas. 

If we reveal from the mvp that users need more guidance we can design an empty state that provides additional context in the empty chart space.

**Comment by rusackas** [comment]
I do believe this has all been tackled! Closing.
