### ISSUE TITLE
AWS ES - Datetime Field is imported as String in Explore Screen

### ISSUE THREAD

**Issue by vineetalagh** [apache/superset#14662]
When Querying an index alias on AWS ES instance with a timestamp datatype field, SQL LAB displays the correct column datatype. But when using explore to create a chart, the field is imported as a String.

### Expected results

It should be imported as Date/Time.

### Actual results

Imported as String.

#### Screenshots

SQL LAB:

![Screenshot 2021-05-17 at 11 22 50](https://user-images.githubusercontent.com/62997477/118473849-54798600-b702-11eb-8000-9252295ee355.png)

Explore:

![Screenshot 2021-05-17 at 11 24 13](https://user-images.githubusercontent.com/62997477/118473973-77a43580-b702-11eb-8ca5-5ffb95e6cf51.png)

### Environment

(please complete the following information):

- superset version: 1.0.1
- python version: 3.8
- node.js version: 12

**Comment by zhaoyongjie** [comment]
resolved by: https://github.com/apache/superset/pull/14894

**Comment by rusackas** [comment]
Looks like this was resolved, but never closed.
