### ISSUE TITLE
Keep dashboard's "View chart in Explore" from opening a new tab

### ISSUE THREAD

**Issue by rusackas** [apache/superset#14672]
Currently, when you navigate from a chart in a Dashboard to Explore via the "view chart in Explore" menu item, it opens a new tab. 

Let's do a little detective work in git blame to reach out to the original author(s) and find out if/why this behavior was intended. For now, I think we should keep everything in one tab/window.

### Expected results

The link should keep you in the same tab, navigating away from the dashboard, rather than opening a new tab.

### Actual results

A new tab is opened

CC @steejay @mihir174 @mistercrunch @junlincc in case you're aware of any existing counter arguments against this change.

**Comment by geido** [comment]
I'll have a look. I love the detective work 🕵️

**Comment by john-bodley** [comment]
@rusackas per the comments in https://github.com/apache/superset/pull/14778 this is not a bug but actually a desirable behavior and thus I think we should revert change.
