### ISSUE TITLE
[homescreen] Make all Home Page tabs "sticky"

### ISSUE THREAD

**Issue by rusackas** [apache/superset#14670]
**Is your feature request related to a problem? Please describe.**
When using the home page, users navigate away, and when they come back, the tabs they clicked on (e.g. recent, favorite) are not saved. This makes users have to re-navigate to their facorite areas all the time.

**Describe the solution you'd like**
Use the localstorage helper utility to store these tab selections whenever they're changed. When you visit the home page, go to the last state.

**Describe alternatives you've considered**
Consult with @nytai about alternate plans involving database storage rather than localstorage, but localstorage sounds like a relatively easy task.

**Additional context**

**Comment by nytai** [comment]
yup, localstorage seems like a good enough solution here. I would only add that we should create a module or class called `SettingStorage` with get/set methods so there's a nice interface wrapper. That would allow us to switch out the underlying storage type from localstorage to the db

**Comment by rusackas** [comment]
For now, we can use 
```
import {
  getFromLocalStorage,
  setInLocalStorage,
} from 'src/utils/localStorageHelpers';
```
