### ISSUE TITLE
[CSS template]don't apply CSS template on menu, submenu and page background 

### ISSUE THREAD

**Issue by xch-jack** [apache/superset#14681]
## Screenshot
This is my custom css template
![image](https://user-images.githubusercontent.com/81534879/118873231-10fa6400-b91c-11eb-95a4-ab5735b84a4b.png)
Return to the dashboards from my custom css template dashboard
![image](https://user-images.githubusercontent.com/81534879/118874042-08eef400-b91d-11eb-9aff-6b1e3467c42e.png)

## Description
1. Opening the custom css template dashboard 
2. Open the following panels: dashboards, charts, databases, datasets, SQL saved query/query history .
3. See to error

##Environment
superset version:master
## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

**Comment by junlincc** [comment]
@xch-jack you mean making chart theme-able?

**Comment by xch-jack** [comment]
hi,
What I mean is that when the custom CSS template is switched to other sections, as long as it is not refreshed, the definitions in the custom CSS template will affect other sections, including dashboards, charts, databases, data sets, SQL queries/historical queries.
My English is very poor, I don’t know if the description is clear.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/superset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月18日(星期二) 下午3:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/superset] Jump page no refresh loading error (#14681)





 
@xch-jack you mean making chart theme-able?
