### ISSUE TITLE
[explore]Can't remove unnecessary Datetime column from time filter

### ISSUE THREAD

**Issue by poleft** [apache/superset#14683]
Hello guys,
I have the issue that I can't remove unnecessary Datetime column from time filter while there are more than 1 Datetime column.  For example, there are two datetime columns named TradingTime and UpdateTime(which represent when to insert the record), only TradingTime is needed for time filter.

Steps to reproduce:

1. Add any datasource withmore than 1 Datetime column.
2. Explore the datasource, and note the time range is automatically applied as "Last week"
3. Edit datasource and uncheck "Is temporal/Is Filterable" with the column 'UpdateTime'
4. Viw quey sqls, 'UpdateTime' still in the where clause

Besides, I have tried another ways but  still not solved yet:

- Remove the column UpdateTime
- modify the type of column UpdateTime as String

**Comment by zhaoyongjie** [comment]
Hi @poleft try to remove `UpdateTime` from dataset. May be need a "hidden column" option for such columns.
cc @junlincc

**Comment by junlincc** [comment]
remove unnecessary column from dataset increases time-to-chart, and takes user out of the application, so this is not ideal . "hidden column"  sounds hacky 😅. 
uncheck "Is temporal/Is Filterable" should remove the column from both date column and filter select dropdown, this is more a bug than feature request. @poleft would you like to work on it?
