### ISSUE TITLE
[Explore] make Table chart column formatting section dynamic

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14699]
To reproduce: in Table Raw record mode, when columns are added but user doesn't run the query, they see a line showing in column formatter section. 

Formatting section should be part of the dynamic control project, it should only shows when it's applicable. 

https://user-images.githubusercontent.com/67837651/118720094-0934a580-b7de-11eb-9a8c-e243218765af.mov

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
