### ISSUE TITLE
[Explore] Explore column icon got lost in icon color change

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14697]
Current Behavior 
<img width="333" alt="Screen Shot 2021-05-17 at 3 18 17 PM" src="https://user-images.githubusercontent.com/67837651/118599669-c5ea2080-b764-11eb-8765-6db8e6cecc7d.png">

Expected Behavior 
<img width="315" alt="Screen Shot 2021-05-18 at 1 38 50 PM" src="https://user-images.githubusercontent.com/67837651/118720402-66c8f200-b7de-11eb-9829-27bb30798692.png">

<img width="291" alt="Screen Shot 2021-05-18 at 1 38 54 PM" src="https://user-images.githubusercontent.com/67837651/118720428-6f212d00-b7de-11eb-8632-0108ee458781.png">

**Comment by geido** [comment]
@junlincc would you mind changing the title as this is _not_ related to the icon migration, as I reported in the issue #14679. This is related to PR #14674 and I am already working on a fix as you requested. 

@pkdotson would you mind dropping this to me? Thanks

**Comment by junlincc** [comment]
@geido thanks for the details. feel free to pick up the ticket.
