### ISSUE TITLE
how to use time-based charts without time

### ISSUE THREAD

**Issue by zufolo441** [apache/superset#14692]
Hi, I know that is a long-time problem. I'm trying to use time-based charts without a time dimension.
Here I have an index from 1 to 26. Now i try to transform it to integer to date with postgres function make_date(index, 1,1), but the result is a strange timestamp.
is there a way to have to X axis at least numbers from 1 to 26? thanks.
![Screenshot_20210518_172330](https://user-images.githubusercontent.com/45826835/118679405-27aa9900-b7fe-11eb-9a77-c20a05eda636.png)

**Comment by junlincc** [comment]
currently no, but you should expect it to be available in next 3 months.
