### ISSUE TITLE
Cannot save native filter

### ISSUE THREAD

**Issue by Riskatri** [apache/superset#14705]
I am using apache superset version 1.1.0, when I am trying to make a native filter.
when I click "save", application not response and got an error like this

https://user-images.githubusercontent.com/59104917/118748119-764f4600-b885-11eb-807b-efefdfc4167c.mp4

**Comment by junlincc** [comment]
this issue should have been fixed in latest master.

**Comment by CarlKarlssonSchmidt** [comment]
Which commit solved the issue? Are there any workarounds?
