### ISSUE TITLE
Possible/How can a visualization internally execute a query that appends additional data to the currently displayed data

### ISSUE THREAD

**Issue by cccs-jc** [apache/superset#14709]
**Is your feature request related to a problem? Please describe.**
The Viz framework is designed to fetch data using the Run button. However some use cases would benefit from the ability to append additional data or additional details to the view based on user interactions.

**Describe the solution you'd like**
Would like to be able to trigger a query from within an existing viz and concatenate the returned results to the results currently shown.

**Describe alternatives you've considered**
This might already be possible in the viz framework. Just not sure how to go about doing this in a custom viz implementation.

Here's a little mockup illustrating the use case. Say you have a huge hierarchy or graph of data. Querying the entire tree is costly or maybe it's too large to load entirely in the client. The idea would be to load a few degrees out from a starting point.

![fetch-more-1](https://user-images.githubusercontent.com/56140112/118799192-71ca6380-b86c-11eb-9d14-07cb4f16f1d0.png)

A user might be interested to dig down into certain branches. The user would be able to select a node and trigger a query which returns children of that node.

![fetch-more-2](https://user-images.githubusercontent.com/56140112/118799232-7bec6200-b86c-11eb-8fee-7708bac12ded.png)

Does the visualization framework already support this? Any example visualization already do something like this?

**Comment by villebro** [comment]
Something quite similar is already being leveraged in a few plugins, although in a slightly different context. As you may know, it's possible to fetch results for multiple queries in a single query context in `buildQuery`:

```
queryContext = {
    queries: [
      queryObject1,
      queryObject2,
    ],
}
```

Now, to be able to add more query objects based on chart interaction you can call `setDataMask` and pass it a JSON object called `ownState`. Something like this:
`setDataMask({ ownState: ['node1'] });`

When you do that, `buildQuery` is retriggered, and you are able to access the `ownState` object in buildQuery like this:

```ts
export default function buildQuery(formData: TableChartFormData, options) {
  const { ownState } = options;
  ...
}
```

So anything that you've passed to `ownState` can be used to modify or add queries to the query context.

**Comment by rusackas** [comment]
Closing this as it's not a bug, and quite old, but happy to revisit the discussion in our normal Slack conversations if needed!
