### ISSUE TITLE
[native filter] Instant filter component will generate 2x more fetch

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#14706]
#### How to reproduce the bug

1. Go to dashboard
2. add native filter component and add a value
3. Check `Apply changes instantly`
4. reload dashboard. You will see every charts are loaded 3 times. This issue cause dashboard load really slow.

#### Screenshots

![G7lm7HcLC7](https://user-images.githubusercontent.com/27990562/118768535-fb117400-b833-11eb-9110-16a5cac801ff.gif)

### Environment

(please complete the following information):

latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

cc @junlincc @villebro This issue is reported by open source user.

**Comment by zhaoyongjie** [comment]
I have reproduced this bug, it depends on the default value whether populated.

**Comment by junlincc** [comment]
Thanks for reporting and debugging @zhaoyongjie ! is expected behavior triggering query once or twice(with default value set up)?  

@michael-s-molina though `Apply changes instantly` has been problematic, we may not remove it YET, since cascading filter ing built upon this logic.
