### ISSUE TITLE
Integration of Open Source Reporting Engines

### ISSUE THREAD

**Issue by hamin123** [apache/superset#14707]
Hi,

I am in process of evaluating Superset. In this process, I am finding that it does not seem to have integration with open source reporting engines such as BIRT, Jasper etc. This is very important for generating printable reports, that are needed frequently.

Reference : https://www.analyticsinsight.net/top-10-best-open-source-reporting-tools-to-lookout-for-in-2021/

These are already part of SpagoBI, which was a great tool but has been discontinued in Open Source community.

Regards,

Hassan Amin

**Comment by rvsoni** [comment]
H @hamin123 

BIRT, Jasper are java based reporting frameworks, Superset is a Python-based reporting tool. 

BIRT, Jasper report generate based on the report design (called Template) and process using Java libs of that framework, a lot more development work needed for it generate reports, 

looks very difficult to incorporate the Superset with those report generation engines. 

You may look into Pentaho (Hitachi Vantara) BI tools for such report generation products.

Ravi

**Comment by rusackas** [comment]
Closing this since it's gone so long without activity, but also since this is more of a feature request than an issue report. If there's still a need for this sort of integration, let's hash it out in an [Ideas DIscussion](https://github.com/apache/superset/discussions/categories/ideas)
