### ISSUE TITLE
[SQL_lab]sql editor page crash 

### ISSUE THREAD

**Issue by pinduvn** [apache/superset#14711]
HI, the lastest tag of docker updated 5 hours before, not work **SQL Lab** -> **SQL Editor**

**Comment by junlincc** [comment]
yes, im seeing it the same on master as well 

Uploading Screen Recording 2021-05-18 at 2.39.43 PM.mov…

**Comment by pinduvn** [comment]
Hi, the tag of docker apache/superset:master-dev have the same problem.

**Comment by eschutho** [comment]
Thank you for reporting @pinduvn. The latest version should be working now. Please let us know if there are any other issues that you find.

**Comment by pinduvn** [comment]
hi, thank!!! now I check the latest version in docker hub.
Best regards

**Comment by pinduvn** [comment]
I checked the latest  version tag in https://hub.docker.com/r/apache/superset but this go on whit the same problem. It seem to me that this is not updated.
Regards
