### ISSUE TITLE
Do not have function of Upload Excel

### ISSUE THREAD

**Issue by Phuc0077** [apache/superset#14712]
Dear all,

I's using Version 1.1.0, it do not have Upload Excell

Is the reason Version? If yes, so which version has this function?

THanks for your supports
Best regards,
![image](https://user-images.githubusercontent.com/84174643/118823235-04a5e500-b8e3-11eb-9130-e61900732ed1.png)

**Comment by junlincc** [comment]
try update to latest master? should have been fixed

**Comment by Phuc0077** [comment]
Thanks for your support

My version is 1.1.0. It's the last version.

Best regards,
