### ISSUE TITLE
OpenAPI specification returned by /api/v1/_openapi contains errors and numerous warnings

### ISSUE THREAD

**Issue by jtornblad** [apache/superset#14715]
Operating system name and version: MacOS 10.15 but n/a 
Superset version: 1.10

Detailed steps to reproduce the bug:

1. Save JSON response from http://SUPERSET_HOST/api/v1/_openapi to file
2. Import JSON file with https://editor.swagger.io/

Observe these errors:

Structural error at paths./chart/import/.post.requestBody.content.multipart/form-data.schema.properties.overwrite.type
should be equal to one of the allowed values
allowedValues: array, boolean, integer, number, object, string
Jump to line 4973
Structural error at paths./dashboard/import/.post.requestBody.content.multipart/form-data.schema.properties.overwrite.type
should be equal to one of the allowed values
allowedValues: array, boolean, integer, number, object, string
Jump to line 5818
Structural error at paths./database/import/.post.requestBody.content.multipart/form-data.schema.properties.overwrite.type
should be equal to one of the allowed values
allowedValues: array, boolean, integer, number, object, string
Jump to line 6260
Semantic error at paths./database/{pk}/select_star/{table_name}/.get.parameters.2.name
Path parameter "schema_name" must have the corresponding {schema_name} segment in the "/database/{pk}/select_star/{table_name}/" path
Jump to line 6566
Structural error at paths./dataset/import/.post.requestBody.content.multipart/form-data.schema.properties.overwrite.type
should be equal to one of the allowed values
allowedValues: array, boolean, integer, number, object, string
Jump to line 6948
Semantic error at paths./dataset/{pk}.put.parameters.1.name
Path parameter "override_columns" must have the corresponding {override_columns} segment in the "/dataset/{pk}" path
Jump to line 7118
Structural error at paths./dataset/{pk}.put.parameters.1.schema.type
should be equal to one of the allowed values
allowedValues: array, boolean, integer, number, object, string
Jump to line 7121

Additionally, there are many warnings about unused object definitions.

**Comment by betodealmeida** [comment]
I fixed the API. The only error that I see now is:

> Semantic error at paths./database/{pk}/select_star/{table_name}/.get.parameters.2.name
Path parameter "schema_name" must have the corresponding {schema_name} segment in the "/database/{pk}/select_star/{table_name}/" path
Jump to line 7650

Which I'm not sure how to handle since a single method is exposed in 2 different paths (one without `schema_name`).

**Comment by rusackas** [comment]
Sounds like this was resolved... closing.
