### ISSUE TITLE
[chart]Pivot Table v2 Labeling Issue

### ISSUE THREAD

**Issue by jamesrayoub** [apache/superset#14716]
#### Issue 
When using the Pivot Table v2 viz, it seems to be displaying the column name rather than the label specified in the dataset; this departs from the behavior in the existing Pivot Table viz. Also, the v2 viz is not rendering the labels for the boolean column.

#### Screenshots

![image](https://user-images.githubusercontent.com/31777200/118853413-b91f1700-b8a1-11eb-94b0-1645d2430583.png)

![image](https://user-images.githubusercontent.com/31777200/118853206-81b06a80-b8a1-11eb-8eca-dc1d032f7227.png)

### Environment

Preset cloud

**Comment by junlincc** [comment]
thanks for reporting! we will add this feature asap. sorry for missing in the new version

**Comment by kgabryje** [comment]
@jamesrayoub @junlincc PR with a fix is open, sorry for the issue! https://github.com/apache-superset/superset-ui/pull/1132

**Comment by jamesrayoub** [comment]
Hi, the pivot table is now displaying the label rather than the field name as expected, but I'm still seeing issues rendering the boolean field... not sure what's happening

**Comment by daniel10012** [comment]
@junlincc @-rusackas

**Comment by rusackas** [comment]
Tracking @jamesrayoub 's comment in a new Issue linked above ^^^

cc @kgabryje

**Comment by kgabryje** [comment]
@rusackas I'll pick that up as soon as possible. 1 additional issue: boolean values are displayed as zeroes (regardless if True of False). I'll fix that as a part of this issue 
![image](https://user-images.githubusercontent.com/15073128/122936801-bb2d3780-d371-11eb-92a7-ff8746c1e784.png)
