### ISSUE TITLE
There was an issue fetching the favorite status of this dashboard.

### ISSUE THREAD

**Issue by xch-jack** [apache/superset#14720]
When the anonymous user opening the dashboard, Display an error"There was an issue fetching the favorite status of this dashboard"

#### Screenshots

![image](https://user-images.githubusercontent.com/81534879/118871127-d98ab800-b919-11eb-8da9-4999178f94be.png)

#### How to reproduce the bug

1.the anonymous user opening the dashboard
2.See error

### Environment

(please complete the following information):

- superset version: `superset master`
- python version: `python --3.7.4`
- node.js version: `node -V14.15.5`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
Hi @xch-jack,

Can you share your configuration for the `Public` role, list of permissions. Are you using `PUBLIC_ROLE_LIKE` config key?

**Comment by xch-jack** [comment]
Hi，
My&nbsp;&nbsp;PUBLIC_ROLE_LIKE&nbsp;are the default.I have tried&nbsp;configuration&nbsp;Public&nbsp;role&nbsp;with administrator permissions,But the error still appears to be.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/superset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月20日(星期四) 晚上6:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/superset] There was an issue fetching the favorite status of this dashboard. (#14720)





 
Hi @xch-jack,
 
Can you share your configuration for the Public role, list of permissions. Are you using PUBLIC_ROLE_LIKE config key?

**Comment by dpgaspar** [comment]
The default for PUBLIC_ROLE_LIKE has no permissions https://github.com/apache/superset/blob/master/superset/config.py#L284 this means that non authenticated don't have access to any resource.

Please share your `Public` role permissions, goto Security -> List Roles -> Edit (Public Role)

**Comment by xch-jack** [comment]
Hi,
This is My&nbsp;&nbsp;Public&nbsp;role permissions,same as admin&nbsp;Public&nbsp;role permissions.
But the error remains








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/superset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月21日(星期五) 下午4:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/superset] There was an issue fetching the favorite status of this dashboard. (#14720)





 
The default for PUBLIC_ROLE_LIKE has no permissions https://github.com/apache/superset/blob/master/superset/config.py#L284 this means that non authenticated don't have access to any resource.
 
Please share your Public role permissions, goto Security -&gt; List Roles -&gt; Edit (Public Role)

**Comment by dpgaspar** [comment]
Fix merged, closing. Feel free to re open if the problem persists
