### ISSUE TITLE
Filtering Data 

### ISSUE THREAD

**Issue by musduo** [apache/superset#14738]
## Screenshot

![git](https://user-images.githubusercontent.com/78935007/118997246-32e1fe00-b991-11eb-85f5-09c1a0ce7bf8.png)

## Description

1)I'm new to apache superset. I'm having a problem with filtering. The filters I choose don't affect other filters, so I get a no data warning on some charts. For example, when you enter a value for the country code, all city data in the database are displayed instead of cities that are suitable for it. 

2)Also, when you stretch the filter down, the whole row lengthens accordingly, causing a problem in this view. Can I stretch the filter independently of the row?

**Comment by junlincc** [comment]
1. can you click top right corner(filter indicator) to see if COUNTRY CODE is applied? did you set instant change? the apply button is missing from the view..
2. we are in the process of deprecating the legacy filter box, please try using native dashboard filter by enabling "DASHBOARD_NATIVE_FILTERS": True,
