### ISSUE TITLE
There was an error fetching the favorite status: NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by Kamakshi12** [apache/superset#14730]
There was an error fetching the favorite status: NetworkError when attempting to fetch resource (or) There was an error fetching the favorite status: Failed to fetch

### Expected results

Pop up (the black message attached in the screenshots) shouldn't occur

### Actual results

The above mentioned error occurs.

#### Screenshots

![image](https://user-images.githubusercontent.com/78851183/118927525-889db280-b95f-11eb-8103-87e3a0341c9a.png)
![image](https://user-images.githubusercontent.com/78851183/118927574-9d7a4600-b95f-11eb-9ae6-192afd8a4664.png)

#### How to reproduce the bug
Any of the following gives the error:

1. Login to the superset account
2. Navigate between other tabs like 'Charts' or 'Data' and then click back on 'Dashboard' tab.

P.S.: The error is seen only in the landing page after entering the credentials (home page) and 'Dashboards' list page. Upon every refresh of the page, the error occurs again.

### Environment

(please complete the following information):

- superset version: `1.1.0`
- python version:  `3.7.9`
- node.js version:  `v14.16.1`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Have referred to similar issues reported before #6824 , #8121, #13746. They all seem to be pointing out to almost the same solution of changing `ENABLE_PROXY_FIX=True` in the superset config.py file and doing a `superset init` command, both of which I tried and it didn't work. More details - I am running the Superset on a Linux ec2 machine.

**Comment by dequn** [comment]
set ENV `FORWARDED_ALLOW_IPS=*`  when starting gunicorn will solve it.
This issue is caused by lacking of trailing slash of `favorite_status` endpoint, and flask will append "/" and respond a redirection. But if flask can not detect it's under `https` scheme, you will get a `http` scheme location, then caused the error.

**Comment by connorwang** [comment]
> set ENV `FORWARDED_ALLOW_IPS=*` when starting gunicorn will solve it.
> This issue is caused by lacking of trailing slash of `favorite_status` endpoint, and flask will append "/" and respond a redirection. But if flask can not detect it's under `https` scheme, you will get a `http` scheme location, then caused the error.

We're having the similar issue here https://github.com/apache/superset/issues/16050. May I ask where did you add the ENV varaible exactly?

Thanks

**Comment by geido** [comment]
Closing this as stale. If you encounter this issue in any recent version (currently 3.x) please open a new Issue or a PR to address the problem. Thanks @Kamakshi12!
