### ISSUE TITLE
[native filters] Select filter should allow user pick time column

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#14744]
Current Select type filter component has `time range` control, but doesn't offer a `time column` control. For a dataset has multiple time columns, this will introduce a potential data quality issue.

![Screen_Shot_2021-05-21_at_12_01_48_AM-2](https://user-images.githubusercontent.com/27990562/119096567-9b000680-b9c8-11eb-84e1-28a6ffc7651f.jpg)

#### Screenshots
This is screenshot to explain how filter_box is used in airbnb: A filter field, which is not a `Date filter`, it can still have `time range` and `time column` to limit the available choices.  For example, with "Last 180 days" time range, this filter has 6 options, while without 180 days limit, it will show 8 options:
![Screen_Shot_2021-05-20_at_11_25_40_PM-3](https://user-images.githubusercontent.com/27990562/119095758-88390200-b9c7-11eb-82a2-932fe1237214.jpg)

### Environment

latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I remember we discussed this issue in the next version of filter configure modal design. So i assume @junlincc is aware of this issue. I created an issue is to make sure backend can handle the extra query parameter for native filter component. cc @villebro

**Comment by junlincc** [comment]
hi @graceguo-supercat i do remember you brought this up in the discussion. can you further explain what potential data quality issue means? 😅

**Comment by villebro** [comment]
Good catch - do I understand correctly, that the need is to add the Time Column control to the Select and Range filters?

**Comment by graceguo-supercat** [comment]
> can you further explain what potential data quality issue means?

for example, i have 2 time column in the dataset, `updated_time` and `created_time`. I used old filter_box, I can set time range as `last 6 months` and time column as `updated_time`. If native filter component not having time column control, this time range may add to `created_time` column, which is wrong.

**Comment by graceguo-supercat** [comment]
> add the Time Column control to the Select and Range filters

yes. thank you!!

**Comment by junlincc** [comment]
@villebro @zhaoyongjie this is problematic, can we simply add a column select when there's 2 and more dataset is available, and make it dynamic?

**Comment by villebro** [comment]
We could fairly easily add a time column dropdown above "Time Range" here where the user could specify an optional time column if there are two or more time columns in a dataset:
![image](https://user-images.githubusercontent.com/33317356/121124122-0d783f80-c82d-11eb-939f-5fe0d93c6c6d.png)

**Comment by junlincc** [comment]
For quick fix that's ok.. eventually we need to remove the time range and blend it into a regular filter though. let's go for the easy solution for now! 😛
