### ISSUE TITLE
Inconsistent MySQL recommended connector

### ISSUE THREAD

**Issue by JPonte** [apache/superset#14746]
Two different documentation pages recommend different MySql connectors.
https://superset.apache.org/docs/databases/mysql recommends `mysql-connector-python`
https://superset.apache.org/docs/databases/installing-database-drivers recommends `mysqlclient`

Which one is the current recommended one or is it indifferent?

### Expected results

Both pages recommend the same, either `mysql-connector-python` or `mysqlclient`. 

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by betodealmeida** [comment]
Good catch! We should use `mysql-connector-python`, it works better with newer versions of MySQL. I'll update the docs.

**Comment by betodealmeida** [comment]
Actually, I just saw this in the SQLAlchemy docs:

> The MySQL Connector/Python DBAPI has had many issues since its release, some of which may remain unresolved, and the mysqlconnector dialect is not tested as part of SQLAlchemy’s continuous integration. The recommended MySQL dialects are mysqlclient and PyMySQL.

So I'll make `mysqlclient` the default. Though we had problems with it at Preset, and we had to switch to `mysql-connector-python`.

**Comment by betodealmeida** [comment]
Updated docs.
