### ISSUE TITLE
[Explore]Search data panel column by key words 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14751]
Related project: 1) Drag and Drop control panel, 2) Remove 50 columns/metrics showing limit on left data panel
Motivation: Improve Time to Chart
As a user, I would like to easily search column by column type to drag and drop into the right control field faster. 
Currently, user can search column/metric by column/metric name, label name, description, info, and all metadata. It will be helpful to make the search even fuzzier. 
e.g. 
user filter to time related columns when they type time, temporal, date, year, month, ds etc. non case sensitive
user filter to numeric columns when they type -> https://docs.snowflake.com/en/sql-reference/data-types-numeric.html

@cccs-rc @cccs-jc Is it possible for your team to implement this change along with the other project?

**Comment by junlincc** [comment]
@cccs-rc @zhaoyongjie

**Comment by zhaoyongjie** [comment]
closed by https://github.com/apache/superset/pull/15153#event-4944281888
