### ISSUE TITLE
[native filter] highlight charts do not work

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#14757]
Please see a very simple test. related to #14693 @kgabryje 

![q5zuKIEkuN](https://user-images.githubusercontent.com/27990562/119174658-b6493100-ba1d-11eb-8ac4-3320a4a3324a.gif)

### Environment
 latest master

### Additional context

Question to @junlincc: When chart is grey-out, does it mean in-scope or out-of-scope?
I know this design is introduced by #10936, but this is really hard to see the UI difference, do you really feel the  applicable charts get **highlight** ? the original behavior is to show a more visible bright border around charts, which is much more apparent than grayscale change:

![95769754-38de6680-0c6d-11eb-9cd7-6fc1e76d9176](https://user-images.githubusercontent.com/27990562/119175950-55baf380-ba1f-11eb-93c5-791c35b0fb51.gif)

This is current **highlight** behavior when user open a deep-linked chart, and I think we should use this highlight style for charts (which will be impacted by currently focused filter):
![8PZcfMPJ6S](https://user-images.githubusercontent.com/27990562/119178056-0de99b80-ba22-11eb-9b4e-b00659174002.gif)

**Comment by kgabryje** [comment]
@graceguo-supercat That is very strange, I replicated your test and it works exactly as expected... I also tested more complex scenarios on Tabbed Dashboard from sample data and it also worked fine.

https://user-images.githubusercontent.com/15073128/119318616-d2e1a500-bc79-11eb-9728-95cbc8b34509.mov

**Comment by graceguo-supercat** [comment]
😿

**Comment by junlincc** [comment]
tested in nested tabs as well, it work as expected. 😅
