### ISSUE TITLE
Superset certain time loads slow on browser using docker-compose

### ISSUE THREAD

**Issue by syazwan0913** [apache/superset#14769]
### Expected results

Superset will always load smoothly all the time

### Actual results

Certain time Superset will load very slow. Expected is because of `healthcheck`

#### Screenshots

```
May 21 00:57:44 DASH dockerd[1802]: time="2021-05-21T00:57:44.656147370+08:00" level=warning msg="Health check for container 4de589c58da10216ab70c29258676123f94494eafce619382e4d2b6b532a2558 error: context deadline exceeded"
```
#### How to reproduce the bug

1. Install Superset `1.0.1` using docker-compose
2. Run Superset using Gunicorn
3. After certain time, Superset will load very slow and go back to normal once Gunicorn container is restarted
4. Error is found out in syslog that related to healthcheck

### Environment

(please complete the following information):

- superset version: `1.0.1`
- python version: `based on 1.0.1`
- node.js version: `based on 1.0.1`
- docker engine version: `20.10.3`
- docker-compose version: `1.28.2`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by srinify** [comment]
hi @syazwan0913 how much RAM have you allocated to Docker Compose? Some of these Docker compose issues I've resolved in the past by increasing the RAM allowed for Docker Compose to use. For Mac OS X, I recommend at least 8 GB if not even more (I use 16 myself)

**Comment by srinify** [comment]
Ah I see, ignore my advice then!
