### ISSUE TITLE
[native filter] prefer fetch all charts before fetch filters

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#14761]
The new build-in filter components design bring all the filters into one places. This design will bring more queries on user open dashboard, because many filters was hidden inside tab now will be loaded all together. So I prefer to load charts before start to load filter queries.  It seems PR #14734 broke this order. 

#### Screenshots

**before**
![8kwt3wPHKn-1](https://user-images.githubusercontent.com/27990562/119206915-51a7c980-ba51-11eb-86dc-31f8583aca00.gif)

**after**
![9OJLC6C08o-1](https://user-images.githubusercontent.com/27990562/119206800-0b526a80-ba51-11eb-9d49-c7b83184edc5.gif)

### Environment

latest master

**Comment by junlincc** [comment]
filters should load when user click Apply, even there's default values set.

**Comment by junlincc** [comment]
@simcha90 please help with the fix fetch chart data first then filter value 🙏
