### ISSUE TITLE
[tab]flaky behavior in tab component

### ISSUE THREAD

**Issue by alderson59** [apache/superset#14763]
Installed using the instructions on here:
https://superset.apache.org/docs/installation/installing-superset-using-docker-compose

https://user-images.githubusercontent.com/69715968/119220148-9f890400-bb1b-11eb-8265-2531a295449e.mp4

Didn't do anything to get here other than get install (with examples loaded, using the docker-compose-non-dev.yml file)
And then clicked into dataset to explore and found this funny thing which continues on forever.

Checked with Brave browser, Chrome, guest mode, private mode and normal.

Let me know if I could help provide any logs, configs etc and where to get them.

**Comment by alderson59** [comment]
If I dragged the column to be wider, the spazzing stops. Nevertheless, it shouldn't have been spazzing as such. I think it's confused and trying to show the three dots but keeps reverting.

**Comment by junlincc** [comment]
@alderson59 im not able to reproduce it on master, can you repo step?

**Comment by junlincc** [comment]
@geido 🙏 high priority, very visible bug

**Comment by rusackas** [comment]
![glitch](https://user-images.githubusercontent.com/812905/119418855-d131d480-bcad-11eb-9e4a-d8c04118bb0e.gif)

**Comment by rusackas** [comment]
cc @michael-s-molina in case this is somehow obvious in relation to recent work.

**Comment by geido** [comment]
I am having a look

**Comment by geido** [comment]
I am working on this issue. There is a problem with applying a custom width to the tabs as this interferes with the calculation of the widths that Antd does on the fly. However, this issue does not seem to be produced by any recent change.

**Comment by geido** [comment]
I can't really reproduce the exact behavior though. The problem for me is only visible when dragging the column but it does not show up otherwise so I am not sure if the fix I am working on will be sufficient. I can't reproduce for both the Explore and the filters modal that Evan is showing up there. I tried with different resolutions as well. Please check the video


https://user-images.githubusercontent.com/60598000/119497765-9b542500-bd6d-11eb-990a-c37ea73ee795.mp4

@michael-s-molina could you please verify if you are reproducing the issue fully?

**Comment by michael-s-molina** [comment]
> I can't really reproduce the exact behavior though. The problem for me is only visible when dragging the column but it does not show up otherwise so I am not sure if the fix that I am working on will be sufficient. I can't reproduce for both the Explore and the filters modal that Evan is showing up there. I tried with different resolutions as well. Please check the video
> 
>  DEV.Age.distri.mp4 
> @michael-s-molina could you please verify if you are reproducing the issue fully?

For me is only visible when dragging the column also.
