### ISSUE TITLE
Legend overflowing into the stacked bar chart in superset version 1.1.0

### ISSUE THREAD

**Issue by Kamakshi12** [apache/superset#14777]
## Screenshot

![image](https://user-images.githubusercontent.com/78851183/119307259-0c6ddc80-bc89-11eb-9960-6ff4cc29391f.png)

## Description

My data has a lot of categories. Hence when I turn on Legends for the stacked bar chart it overflows on the bars. No matter how big I make the chart, the bar size increases, however the overlap on the chart stays put. I need to have the legends and don't want to turn it off. Please advice. 

## Design input
Ideally would like a top positioning of the legends with the scroll option when there are more legend labels just like how they have altered it for the pie/donut chart. Example below:
![image](https://user-images.githubusercontent.com/78851183/119307790-d8df8200-bc89-11eb-829b-e257cf3f8f88.png)

**Comment by junlincc** [comment]
@Kamakshi12 this shouldn't be an issue if you choose Times-series chart(bar as series type). lmk
