### ISSUE TITLE
Weird dot on Echarts timeseries annotation

### ISSUE THREAD

**Issue by syazwan0913** [apache/superset#14772]
### Expected results

No dots on echarts annotation

### Actual results

Got dots on annotation

#### Screenshots

![image](https://user-images.githubusercontent.com/28984703/119286088-294ce480-bc76-11eb-8f1c-182926cee5ef.png)

#### How to reproduce the bug

1. Go to 'Echarts timeseries'
2. Create 'Annotation' as below
![image](https://user-images.githubusercontent.com/28984703/119420904-04b54300-bd30-11eb-97d7-bfe24e9e7bee.png)
3. See the dot

### Environment

(please complete the following information):

- superset version: `1.0.1`
- python version: `based on 1.0.1`
- node.js version: `based on 1.0.1`
- superset-ui version: `0.16.9`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@syazwan0913 thanks for reporting, please provide more details of this issue, reproduce step, and confirm issue still exists in master.

**Comment by syazwan0913** [comment]
When hover the mouse on the annotation, it will show weird dot. This issue doesn't happen in `master` branch. I tried to figure out to fix this in `1.0.1`

**Comment by villebro** [comment]
I vaguely remember this bug. It was present in ECharts 5.0.0 but was fixed in one of the subsequent patch releases IIRC. I suggest upgrading to Superset 1.1.0, it should not be present there.

**Comment by syazwan0913** [comment]
If I don't upgrade the Superset, can I just upgrade the Echarts only? I plan not to upgrade the Superset yet since it is stable in our company environment.

**Comment by villebro** [comment]
That could be difficult. You can potentially checkout the 1.0.1 tag and then manually upgrade the ECharts dependency, but that may be introduce other risk factors. I'd almost recommend looking into upgrading to 1.1.0.

**Comment by syazwan0913** [comment]
Okay noted. I will check it out. Thanks
