### ISSUE TITLE
Unable to save a chart: Cannot read property 'slice_url' of undefined

### ISSUE THREAD

**Issue by DominikPalo** [apache/superset#14781]
I'm trying to change the dataset in existing charts (owned by me), but I'm not able to save the changes. As a workaround, I have to delete the old chart and create a new one.

### Expected results

The chart is updated/saved.

### Actual results

After I click on the "Save" button, changes are not saved - the "Save chart" modal window just closes without any warning and I'm back in the explore mode. When I try it for a second time, the "Save chart" window shows an error: "Failed to save slice" (but I'm still not able to save it). Also, there is a bunch of errors in the console (see the screenshot).

#### Screenshots

![image](https://user-images.githubusercontent.com/1623257/119347455-d71eba00-bc9b-11eb-8654-5083e473cf36.png)

#### How to reproduce the bug

1. Click on "View chart in Explore"
2. Change the dataset (by "Change dataset")
3. Adjust other chart settings (like query)
4. Click "Save"
5. Choose "Save (Overwrite)" or "Saves as..."
6. Click "Save" or "Save & go to dashboard"

### Environment

(please complete the following information):

- superset version: 1.1.0
- python version: 3.8.9-slim

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by yousoph** [comment]
Closing as we've been unable to repro. Please reopen with more details if you're still seeing this issue, thanks!
