### ISSUE TITLE
[dashboard]Charts Sort-by in Edit mode get cut off

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14799]
## Screenshot

<img width="2021" alt="Screen Shot 2021-05-24 at 4 13 35 PM" src="https://user-images.githubusercontent.com/67837651/119417645-27e9df00-bcab-11eb-8543-e1d42763548d.png">
Please test on resizing window when opening a PR

## Description
Suggest to 
1) remove "Sort by" in each option 
2) or open select from the left, instead of from the right
3) or add horizontal scroll.....

**Comment by junlincc** [comment]
@geido

**Comment by geido** [comment]
Just for transparency. We have decided to tackle this and more select-related issues in the Select component refactoring that is undergoing.

**Comment by rusackas** [comment]
We'll leave this open until the new Select component replaces it. Thanks, @geido !
