### ISSUE TITLE
[explore]resizable Edit Dataset modal

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14794]
## Screenshot

<img width="1772" alt="Screen Shot 2021-05-24 at 3 15 24 PM" src="https://user-images.githubusercontent.com/67837651/119413644-e5bc9f80-bca2-11eb-9193-392e59c88184.png">

## Description
As a data scientist, I would like to be able to resize the Edit Dataset modal, especially when I'm writing long sql expression to create new metrics.  I simple solution would be similar to the metrics/filter pop over. 

https://user-images.githubusercontent.com/67837651/119413833-464bdc80-bca3-11eb-8b87-9825b4affe9a.mov

**Comment by zhaoyongjie** [comment]
There is an HTML resize icon at the edge of the SQL text area.
cc: @junlincc 

![image](https://user-images.githubusercontent.com/2016594/119459810-9fce0d00-bd70-11eb-8585-1f19a8681d74.png)

**Comment by aonurdemir** [comment]
In version 1.5.0, there is not resize icon. Related issue is here: https://github.com/apache/superset/issues/20200

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and is a feature request rather than a bug (plus, there's been a PR to resolve at least some of it!). If this is relevant in current versions (currently 3.x) please open a new Ideas discussion or a PR to address the problem.
