### ISSUE TITLE
[FilterBox] Filter indicator shows that FilterBox time filter is 'applied' even when no filter is applied

### ISSUE THREAD

**Issue by rusackas** [apache/superset#14796]
### Expected results

Filter indicator should show the `Time range` filter as Unset, not applied, when it is set to `no filter`.

### Actual results

Filter indicator still shows 1 applied filter, even though the data is not actually being filtered, and the filter is unset.

#### Screenshots

![image](https://user-images.githubusercontent.com/812905/119419133-67fe9100-bcae-11eb-8a5b-38aa44a66740.png)

![image](https://user-images.githubusercontent.com/812905/119415960-76957a00-bca7-11eb-8053-0b145d0c48af.png)

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
cc @junlincc

**Comment by rusackas** [comment]
Also, @graceguo-supercat, the reason I'm tagging you here is a related peculiarity...

It seems that (at least in this example) the Filter Box filter (`no filter`) overrides the dashboard native filter. That is, if I set the Dashboard Native filter do the last 7 years, the charts _appear_ unfiltered, since the `no filter` filter wins.

If you change the Filter Box filter to the last 7 years, the data updates as expected. Again, changing the Native Filter config to "no filter" does not override that Filter Box selection, either.

**Comment by junlincc** [comment]
filed one for Native filter. let's address it in Native filter only. [native-filters]"No filter" state in wrong section of filter indicator
