### ISSUE TITLE
[Treemap v2]selected color scheme can't be saved in chart 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14793]
See video, it also happens in Treemap v1(no need to fix it)
please also check the behavior in other new ECharts

https://user-images.githubusercontent.com/67837651/119404983-6e344380-bc95-11eb-8d1f-79a8267d82f8.mov

**Comment by rusackas** [comment]
I think this is in regards to the legacy one that was replaced. Closing, but we can re-open if needed.
