### ISSUE TITLE
[Bar]show total bar value of stacked bar series in new Bar(Echarts)

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14795]
<img width="1137" alt="Screen Shot 2021-05-24 at 3 22 00 PM" src="https://user-images.githubusercontent.com/67837651/119414282-1fda7100-bca4-11eb-8913-16473a9d7b53.png">

Legacy Bar offers the option to show total value of stacked bar, but not in the Time-series(Bar) 
We wanna make sure we offer this solution when Echarts Bar is released.

**Comment by andrewscarani** [comment]
It would be great to offer this as a setting in **all** Time-Series charts whenever "GROUP BY" is used

**Comment by michael-s-molina** [comment]
Closing this as the feature is already available.
