### ISSUE TITLE
[native filter] filter component can not force refresh options

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#14791]
User can not force refresh data for filter component, it only re-run query and get cached results.

#### Screenshots
How about force run query in populate/refresh action?
<img width="563" alt="Screen Shot 2021-05-24 at 12 16 45 PM" src="https://user-images.githubusercontent.com/27990562/119396612-edbc1580-bc89-11eb-8e20-0ac3472c67df.png">

### Environment

latest master

### Additional context

cc @junlincc @villebro

**Comment by michael-s-molina** [comment]
@graceguo-supercat @villebro @junlincc https://github.com/apache/superset/pull/14824 removed the Populate and Refresh buttons to facilitate the user experience when retrieving the values. If we want to support force refresh we have some options:
- Leave as it is and use the search when looking for a specific value 
- Disable cache for specific selects
- Create a refresh button specifically for this page
- Create some sort of refresh button as a native feature of our selects

**Comment by villebro** [comment]
I think the best solution here is adding a 🔄  type of button next to the filter to make it possible to trigger a `force=true` query.

**Comment by michael-s-molina** [comment]
> think the best solution here is adding a 🔄 type of button next to the filter to make it possible to

Did you mean to create a button specifically for this page? How common is this requirement throughout the application?

**Comment by villebro** [comment]
> > think the best solution here is adding a 🔄 type of button next to the filter to make it possible to
> 
> Did you mean to create a button specifically for this page? How common is this requirement throughout the application?

I think we could reuse this one from SQL Lab:
![image](https://user-images.githubusercontent.com/33317356/121905147-82b6a980-cd32-11eb-9298-20d7b54a0d56.png)

**Comment by michael-s-molina** [comment]
> > > think the best solution here is adding a 🔄 type of button next to the filter to make it possible to
> > 
> > 
> > Did you mean to create a button specifically for this page? How common is this requirement throughout the application?
> 
> I think we could reuse this one from SQL Lab:
> ![image](https://user-images.githubusercontent.com/33317356/121905147-82b6a980-cd32-11eb-9298-20d7b54a0d56.png)

My question is more about if this should be a native feature of our selects or something specific for this page.

**Comment by villebro** [comment]
Ah, right. If we add it as a native feature, we need to make sure we make it possible to pad selects that don't have the refresh enabled to align them with others that have it, like here:

![image](https://user-images.githubusercontent.com/33317356/121907746-0376a500-cd35-11eb-891c-7c25e5a45e07.png)

Also, if we do add it, we'll have to make sure the hook for it is easy and straight forward to implement and causes minimal code duplication (not saying it can't be done, just haven't thought it through yet).
