### ISSUE TITLE
official site document need to be updated?

### ISSUE THREAD

**Issue by kurtiswen** [apache/superset#14808]
https://superset.apache.org/docs/frequently-asked-questions
first FAQ, the answer says superset can only query a single table at one time

### Expected results

as my understanding, there is no such limitation. we can join multiple table in sql editor and execute the query.
so is this document need to be updated?

**Comment by srinify** [comment]
@kurtiswen actually, the description written there seems to match what you just said!

"Not in the Explore or Visualization UI..."

The docs instead mention materializing a view, but doesn't explicitly mention SQL Lab. So the action item here could be to specifically call out SQL Lab as an option + the virtual dataset layer.

Do you want to make a contribution here to the docs @kurtiswen :)?

This is the file you'd need to edit & then you can submit a PR: https://github.com/apache/superset/blob/master/docs/src/pages/docs/frequently-asked-questions-page.mdx
