### ISSUE TITLE
[native filter] Should not show empty filter indicator when no filters applicable (see comment)

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#14807]
I created a filter_box, and I set it's not applicable to any charts in the dashboard. So there is **no filter indicator** showing up for the chart. This is correct behavior:
<img width="1149" alt="Screen Shot 2021-05-25 at 1 17 36 AM" src="https://user-images.githubusercontent.com/27990562/119464665-d156c200-bcf7-11eb-91a9-d746ce576639.png">

But for native filter component, even i set filter scope is not applicable for any charts, the chart still show an empty filter indicator:
<img width="1150" alt="Screen Shot 2021-05-25 at 1 19 29 AM" src="https://user-images.githubusercontent.com/27990562/119464912-0fec7c80-bcf8-11eb-8b75-4d2f3f255a7f.png">

This behavior is **misleading**. **Empty filter indicator** means the filter field is applicable to this chart, but currently there is **_no value applied_**. 

### Environment

latest master.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

cc @junlincc

**Comment by junlincc** [comment]
New native filter component only allows compatible filters to be added to the filter bar, meaning user can only select from datasets that power at least one chart on the dashboard. there will be no more incompatible filters in this case. We can remove that.... 
Expected behavior: When user open a new dashboard, there should be no indicator showing until use click Apply. @michael-s-molina @kgabryje let's double check later this week.

**Comment by graceguo-supercat** [comment]
> there will be no more incompatible filters in this case.

This statement is not true: remember what is jinja template? see [SIP-45](https://github.com/apache/superset/issues/9935). filter compatible or not **can not** be decided by front-end.

**Comment by graceguo-supercat** [comment]
> New native filter component only allows compatible filters to be added to the filter bar, meaning user can only select from datasets that power at least one chart on the dashboard.

This statement is not true. User can, and they should be allowed to, add filter component from all dataset.

**Comment by junlincc** [comment]
I have a hard time to think of the use case that i create a filter with dataset that's not being used in any charts on the dashboard??

**Comment by junlincc** [comment]
> > there will be no more incompatible filters in this case.
> 
> This statement is not true: remember what is jinja template? see [SIP-45](https://github.com/apache/superset/issues/9935). filter compatible or not **can not** be decided by front-end.

we will solve that issue separately, we have looked into solutions

**Comment by graceguo-supercat** [comment]
> I have a hard time to think of the use case that i create a filter with dataset that's not being used in any charts on the dashboard??

1. i can create a small dataset only used by filter, so that i don't have to offer long list of options from original table.
2. i can create filter first, then add chart later.
