### ISSUE TITLE
[filter-box]Application of filter issue

### ISSUE THREAD

**Issue by matthew-red** [apache/superset#14804]
I have an issue regarding applying a filter to my charts on my dashboard. Basically when I click apply the updates are not reflected on the charts itself. However, when I click explore on a chart, the filter update is reflected on the chart. Hope you are able to find a solution

### Expected results
I am using a big number chart: The chart should reflect the number the filter contains. I have other charts below, but this is just for the general idea. 
<img width="1363" alt="Screen Shot 2021-05-24 at 5 49 38 PM" src="https://user-images.githubusercontent.com/74437505/119423608-7e114f00-bcb8-11eb-97c9-1467f9098684.png">

### Actual results
When I change the filter value, the changes are not reflected on the charts
<img width="1346" alt="Screen Shot 2021-05-24 at 5 58 51 PM" src="https://user-images.githubusercontent.com/74437505/119424121-b6655d00-bcb9-11eb-823a-40d27f7ec52a.png">

Also: it says the filter is being applied, but its not actually being updated: 
<img width="758" alt="Screen Shot 2021-05-24 at 5 59 40 PM" src="https://user-images.githubusercontent.com/74437505/119424179-d1d06800-bcb9-11eb-82a4-edac6212501d.png">

Also: When I explore the chart, the chart reflects the filter change. 

<img width="613" alt="Screen Shot 2021-05-24 at 6 02 51 PM" src="https://user-images.githubusercontent.com/74437505/119424425-4acfbf80-bcba-11eb-81a9-69219527e348.png">

<img width="299" alt="Screen Shot 2021-05-24 at 6 03 28 PM" src="https://user-images.githubusercontent.com/74437505/119424452-5a4f0880-bcba-11eb-9924-a6bddb3929f1.png">

#### How to reproduce the bug

1. The filter just contains a range of numbers 1-100
2. The big number chart to the left should just reflect the same number as the filter value. 
3. I applied a new value in the filter

### Environment

(please complete the following information):

- superset version: Whatever is the most recent version of Preset. (Using preset, not superset)
- python version: N/A
- node.js version: N/A
- Database: Postgresql

**Comment by daniel10012** [comment]
@junlincc

**Comment by matthew-red** [comment]
Hello, 

Unfortunately, I already had the filter set as apply only a single value. I tried deleting and readding the filter to the dashboard. But it did not seem to work. Not sure what the issue could be. 

https://user-images.githubusercontent.com/74437505/119742160-0409d300-be3c-11eb-8fea-a9564b9a6447.mov

When I explore the chart the filter is applied properly: 

https://user-images.githubusercontent.com/74437505/119742448-ad50c900-be3c-11eb-9a75-9ff6b0001c67.mov

**Comment by zhaoyongjie** [comment]
closes by: https://github.com/apache/superset/pull/14841
