### ISSUE TITLE
[dashboard]charts in nested tab is missing control and filter indicator 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14801]
😅🤦🏾‍♀️
<img width="1414" alt="Screen Shot 2021-05-24 at 4 47 57 PM" src="https://user-images.githubusercontent.com/67837651/119419893-ff181880-bcaf-11eb-82cd-af7536425c19.png">

**Comment by geido** [comment]
Could not reproduce

![Screen Shot 2021-06-02 at 19 24 01](https://user-images.githubusercontent.com/60598000/120516546-29688500-c3d8-11eb-8abb-6074ae880364.png)

**Comment by stephenLYZ** [comment]
Steps to reproduce:

1. Edit dashboard.
2. Drag a tab.
2. Add a new tab.
3. Drag any chart to the new tab.
4. Save dashboard.

**Comment by stephenLYZ** [comment]
I am working on it.

**Comment by rusackas** [comment]
The issue happens with **nested** tabs, just to clarify.

**Comment by stephenLYZ** [comment]
fixed #15134
