### ISSUE TITLE
[listview]remove unnecessary scroll bar and empty space from list view 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14800]
https://user-images.githubusercontent.com/67837651/119418133-27057d00-bcac-11eb-9652-5ab9f0542278.mov

**Comment by geido** [comment]
I am picking this up

**Comment by eschutho** [comment]
@AAfghahi also took a look at this but neither of us were able to reproduce.

**Comment by geido** [comment]
Same. Could not reproduce even in different resolutions

**Comment by pkdotson** [comment]
Can't reproduce. Gonna close this for now!
