### ISSUE TITLE
Hide "Upload CSV" or "Upload Excel" when no database can handle it

### ISSUE THREAD

**Issue by squalou** [apache/superset#14810]
## Screenshot

![image](https://user-images.githubusercontent.com/4623644/119474534-8adf8280-bd4c-11eb-989e-09ba994f9aab.png)

![image](https://user-images.githubusercontent.com/4623644/119474472-7b603980-bd4c-11eb-9ed8-4ae39e78235b.png)

## Description

I do NOT want to enable Upload CSV feature. So I disabled it in all Databases connexions. Fine.

Yet : it's still present in the menu.

It leads to an error if I click on it, which is fine.

I would rather have a way to *Hide* entirely  the "Upload " in the menus. Could be automatically hidden if no DB allows it, or I could add a parameter somewhere.

**Comment by squalou** [comment]
after reviewing the sources I see a

```python

if self.config["CSV_EXTENSIONS"].intersection(
            self.config["ALLOWED_EXTENSIONS"]
        ):
# etc...        
            if self.config["EXCEL_EXTENSIONS"].intersection(
                self.config["ALLOWED_EXTENSIONS"]
            ):
# etc...
```

So maybe the configuration can be used already ? 

If so feel free to close the issue.

**Comment by raags** [comment]
@squalou Thanks, this worked for me!
