### ISSUE TITLE
[Pivot V2] Set D3 format from metrics parameters

### ISSUE THREAD

**Issue by ETselikov** [apache/superset#14812]
Pivot table v1 could show unique D3 format for every metric but v2 dont have this feature

### Expected results

Having an ability to specify D3 format for every metric in pivot table

### Actual results

I can choose format option for every metric or just leave them for thrmselves

#### Screenshots

![issue_1](https://user-images.githubusercontent.com/17961175/119495840-85ddfb80-bd6b-11eb-8ac9-da0777ea702a.png)
![issue_2](https://user-images.githubusercontent.com/17961175/119495850-88405580-bd6b-11eb-98f1-be8d5fbd13be.png)

### Environment
- superset version: `1.1`

**Comment by kgabryje** [comment]
done
