### ISSUE TITLE
[native filters] Selected values cover other filter name

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#14819]
![9roCYpxsz2](https://user-images.githubusercontent.com/27990562/119534589-ee14e900-bd3b-11eb-971e-51716ce7054b.gif)

### Environment

latest master

### Additional context

cc @junlincc

**Comment by junlincc** [comment]
@michael-s-molina let's unify the select behavior. "...+4" solution seems fine, as long as the selected value are at the top on expand. 

https://user-images.githubusercontent.com/67837651/119539607-384c9900-bd41-11eb-98db-0ec0421feb88.mov

**Comment by junlincc** [comment]
<img width="247" alt="Screen Shot 2021-06-07 at 1 43 32 PM" src="https://user-images.githubusercontent.com/67837651/121085164-61841500-c796-11eb-9872-f78c6aafe7d2.png">
fixed
