### ISSUE TITLE
[Explore] Long title in Explore field cosmetic glitch 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14825]
<img width="2041" alt="Screen Shot 2021-05-25 at 1 25 48 PM" src="https://user-images.githubusercontent.com/67837651/119563762-d568fb00-bd5c-11eb-82c2-99d9836d0e8d.png">

Long title doesn't fid in Bar chart SERIES in SELECT field. **Will not fix**
It's not an issue in Drag and Drop. 

https://user-images.githubusercontent.com/67837651/119564465-ad2dcc00-bd5d-11eb-99df-7c3f2b8fad4d.mov

But there's a different cosmetic issue for long title in Drag and drop - **Should fix** 

https://user-images.githubusercontent.com/67837651/119564475-b028bc80-bd5d-11eb-9bcb-40d2a98712fd.mov

**Comment by geido** [comment]
I am having a look
