### ISSUE TITLE
[Tab]sub-level tabs can not be removed

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14820]
Expected behavior 
User can click on Trash icon in the action bar to delete dashboard components 

https://user-images.githubusercontent.com/67837651/119538546-0f77d400-bd40-11eb-88a1-b39944b5a996.mov

**Comment by junlincc** [comment]
@geido

**Comment by geido** [comment]
I am having a look at this

**Comment by geido** [comment]
@junlincc I can't reproduce. However, there is an annoying issue when a sub-tab is empty and it has another sub-tab down below. You can never reach the trash icon with your mouse :D

Check the video. I am solving that one


https://user-images.githubusercontent.com/60598000/119869024-735cf100-bf28-11eb-8d82-b52f76a3f147.mp4
