### ISSUE TITLE
[Tab]Add tab component in row/ resizable, and boarder 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14821]
**Is your feature request related to a problem? Please describe.**
Pain 1 I'm always frustrated when Tab component takes up the whole row when added in the dashboard. As a user, I would like the Dashboard layout to be more flexible, and/or to be able to insert tab in Row. 
Pain 2. I can not visually distinguish dashboard and Tabgroup easily as tab use white background as charts 

Task: 1. The goal is for Tab not to take up the entire row, whether to make resizable(preferred) or Tab inside Row, doesn't really matter 
<img width="1456" alt="Dashboards_ Filters - Global Open@2x (2)" src="https://user-images.githubusercontent.com/67837651/119544073-3b965380-bd46-11eb-87ee-66ce813194b9.png">

Task 2. add ability to name the second level tab component 

Task 3. add grey background/boarder/padding to sub-level tab chart

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
