### ISSUE TITLE
Long column names wrap and get cut off in Explore column list

### ISSUE THREAD

**Issue by cccs-rc** [apache/superset#14866]
## Screenshot

![image](https://user-images.githubusercontent.com/62034438/119823881-4de9cc00-bec3-11eb-9d4a-b1cd9014622d.png)

## Description

If column names are too long to fit on one line in the Explore view's "Column list", they wrap onto the next line and get partially cut off at the top and bottom. 

## Design input
I see two possible remedies for this. 

1) Don't wrap long text and instead have a horizontal scroll bar appear if the panel isn't wide enough to accommodate the text. 
<img src="https://user-images.githubusercontent.com/62034438/119825463-f6e4f680-bec4-11eb-91fc-16063451a808.png" height="350">

2) Increase the height of of the labels if/when the text wraps. 
<img src="https://user-images.githubusercontent.com/62034438/119827579-4c220780-bec7-11eb-9e8b-0b82c555f582.png" height="350">

Our users have requested Option 1. 

If we can get a green light for one of these options (or a better option not yet considered), we're happy to submit a PR!

**Comment by junlincc** [comment]
hi @cccs-rc, thanks for offering help! we are aware of this issue when drag and drop feature is enabled and we have been discussing the right solution for long title across the product, cosmetic issue around long title is everywhere. 
horizontal scroll is one of the options but not in favor. other options : 1) show tooltip on truncated titles, 2) increase the panel resizable max width. UI/UX Consistency is the key in the product
we will let you know once we have a design guideline. meanwhile, please feel free to start working on the "show all" column and improving search in the left panel. thank you so much for your help!! 

cc @michael-s-molina @rusackas @villebro
