### ISSUE TITLE
[native-filter]direct user to *required field when fail to Save filter configuration 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14860]
User completed creating filter A, and started create filter B without filling out all the required fields in the CONFIGURATION tab for filter B, user switches to the SCOPING tab to scope filter B to charts, user clicks SAVE but fail without any notification. 

Expected Behavior: Instead of user being stuck in the SCOPING tab, we should bring user back to required fields to complete the configuration for a successful save. 

https://user-images.githubusercontent.com/67837651/119773342-57e4de00-be75-11eb-806d-58c79695bfeb.mov

**Comment by junlincc** [comment]
resolved

**Comment by michael-s-molina** [comment]
@junlincc This was fixed in https://github.com/apache/superset/pull/14854
