### ISSUE TITLE
Error adding MySQL DB

### ISSUE THREAD

**Issue by erikgardea** [apache/superset#14862]
I did spin up a superset instance with docker-compose on my MacBookPro, and I am trying to add a dockerized MySQL DB(in the same network),and even though the test connection succeeds, I am getting an error when I click on the "Connect" button:
These are the logs:

          | 2021-05-27 08:04:39,040:DEBUG:superset.models.core:Database.get_sqla_engine(). Masked URL: mysql://remote:XXXXXXXXXX@mysql1:3306/product_usage
superset_app             | 2021-05-27 08:04:39,092:DEBUG:superset.stats_logger:[stats_logger] (incr) test_connection_success
**superset_app             | 2021-05-27 08:04:39,118:DEBUG:superset.stats_logger:[stats_logger] (incr) DatabaseRestApi.test_connection.success**
superset_app             | 2021-05-27 08:04:39,119:DEBUG:superset.stats_logger:[stats_logger] (timing) DatabaseRestApi.test_connection.time | 90.08369999355637 
superset_app             | 172.21.0.1 - - [27/May/2021 08:04:39] "POST /api/v1/database/test_connection HTTP/1.1" 200 -
superset_app             | 2021-05-27 08:04:39,123:INFO:werkzeug:172.21.0.1 - - [27/May/2021 08:04:39] "POST /api/v1/database/test_connection HTTP/1.1" 200 -
superset_app             | 2021-05-27 08:04:43,935:DEBUG:superset.stats_logger:[stats_logger] (incr) DatabaseRestApi.post.error
**![Screen Shot 2021-05-27 at 1 13 48 AM](https://user-images.githubusercontent.com/84901205/119790541-deef8180-be88-11eb-817a-0b94526af2e6.png)
![Screen Shot 2021-05-27 at 1 13 39 AM](https://user-images.githubusercontent.com/84901205/119790543-df881800-be88-11eb-8ea8-f9a3f291735c.png)
**
superset_app             | Traceback (most recent call last):
superset_app             |   File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/api/__init__.py", line 85, in wraps
superset_app             |     return f(self, *args, **kwargs)
superset_app             |   File "/app/superset/views/base_api.py", line 85, in wraps
superset_app             |     raise ex
superset_app             |   File "/app/superset/views/base_api.py", line 82, in wraps
superset_app             |     duration, response = time_function(f, self, *args, **kwargs)
superset_app             |   File "/app/superset/utils/core.py", line 1409, in time_function
superset_app             |     response = func(*args, **kwargs)
superset_app             |   File "/app/superset/utils/log.py", line 228, in wrapper
superset_app             |     value = f(*args, **kwargs)
superset_app             |   File "/app/superset/databases/api.py", line 241, in post
superset_app             |     item = self.add_model_schema.load(request.json)
superset_app             |   File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 728, in load
superset_app             |     data, many=many, partial=partial, unknown=unknown, postprocess=True
superset_app             |   File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 850, in _do_load
superset_app             |     PRE_LOAD, data, many=many, original_data=data, partial=partial
superset_app             |   File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 1101, in _invoke_load_processors
superset_app             |     partial=partial,
superset_app             |   File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 1227, in _invoke_processors
superset_app             |     data = processor(data, many=many, **kwargs)
superset_app             |   File "/app/superset/databases/schemas.py", line 271, in build_sqlalchemy_uri
superset_app             |     parameters
superset_app             |   File "/app/superset/db_engine_specs/base.py", line 1363, in build_sqlalchemy_uri
superset_app             |     host=parameters["host"],
**superset_app             | KeyError: 'host'**

**Comment by srinify** [comment]
Hi @erikgardea if you look at the error message, you'll notice the following error from `superset_app` (which corresponds to the superset python service + container):

```
KeyError: 'host'
```

This is an important clue! This means that your HOST in your SQLAlchemy connection string is missing, as far as superset is concerned! 

Now, if we look at the [recommended SQLAlchemy string in the documentation](https://superset.apache.org/docs/databases/mysql):

```
mysql://{username}:{password}@{host}/{database}
``

andddd compare it to what your logs are showing:

```
mysql://remote:XXXXXXXXXX@mysql1:3306/
```

... you may notice the issue! After the `@` symbol, you need to put the HOST value. The HOST is usually:

- `localhost` if Superset & MySQL are running in the same networking setup. It looks like that's not exactly the case for you since you're using Docker Compose for Mac to run Superset and MySQL
- The host as a URL `20230dlslls.amazon.aws.com` or something like that
- **A shortcut that RESOLVES to a HOST value, like `docker.for.mac.internal`**

I would try the 3rd option and see what happens.

**Comment by erikgardea** [comment]
Thanks for the quick response Srini.
I tried the 3rd option but it didn't make a difference.  
Here is the connection string:
-mysql://remote:XXXXXXX@docker.for.mac.host.internal/product_usage?charset=utf8
The outcome  is the same:
1. I am able to Test the Connection  
2. When clicking on the Connect button  I get the same error.
So, it seems like the driver is there, it's able to test the connection, but when it gets to scqalchemy, something happens to the host  parameter, BTW, on the first connection string I shard, **mysql1** is the actual docker host name, so that parameter is valid.  
One interesting thing though this that, I tried to duplicate the already existing Postgres database  by adding the exact same parameters  and I got the same behavior meaning, I am able to test the connection, but when clicking on the Connect button, it throws the same error. 

Thanks in advance. 
Erik Gardea

<img width="1065" alt="Screen Shot 2021-05-28 at 12 09 39 PM" src="https://user-images.githubusercontent.com/84901205/120031427-a39aa300-bfad-11eb-9b7a-09c3ed60d121.png">

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
