### ISSUE TITLE
[cosmetic][dashboard] sort chart drop down menu is cut in dashboard edit mode

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#14875]
## Screenshot
<img width="1792" alt="Screen Shot 2021-05-27 at 1 26 32 AM" src="https://user-images.githubusercontent.com/81597121/119864397-724ba580-becf-11eb-9f65-e1d540db72d5.png">

**Comment by junlincc** [comment]
https://github.com/apache/superset/issues/14799 

duplicate, please look for existing ticket before filing in case duplicate. :)
