### ISSUE TITLE
[cosmetic][filter box] columns overlap in filter configuration in filter box chart

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#14879]
## Screenshot
<img width="1792" alt="Screen Shot 2021-05-26 at 4 11 51 PM" src="https://user-images.githubusercontent.com/81597121/119871813-b04cc780-bed7-11eb-89a7-4a25a11f00fd.png">

**Comment by jinghua-qa** [comment]
the overlap issue can be resolved by enlarge the size of the panel, just by default size the columns are overlapping

**Comment by junlincc** [comment]
resolved by https://github.com/apache/superset/pull/14921
