### ISSUE TITLE
[explore][area chart] graph disappear when selecting 'Y LOG SCALE' in CUSTOMIZE panel

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#14889]
For area chat, when the 'Y LOG SCALE'  is selected in CUSTOMIZE panel, the graph in viz will disappear 

### Expected results

graph will change by Y LOG SCALE

### Actual results

graph disappear when Y LOG SCALE is selected

#### Screenshots

https://user-images.githubusercontent.com/81597121/119907757-d7ba8900-bf05-11eb-9261-2c3bca54d0b5.mov

#### How to reproduce the bug

1. open a area chart
2. go to CUSTOMIZE panel
3. check on 'Y LOG SCALE'

### Environment

(please complete the following information):

- superset version: master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
-  I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by xiezhongfu** [comment]
I am working in it.

**Comment by jinghua-qa** [comment]
Still saw this issue in area chart

**Comment by eschutho** [comment]
@jinghua-qa @rusackas is this one of the charts that is being deprecated? Should we still try to fix it?

**Comment by kgabryje** [comment]
This issue is related to a deprecated chart (Area Chart). In the new one (Time-Series Area Chart) log scale seems to work fine.
CC @rusackas @jinghua-qa

**Comment by yousoph** [comment]
Closing as won't fix since the Time Series Area chart is working as expected
