### ISSUE TITLE
[home page] favorite tab in dashboard section is not showing favorite dashboard

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#14887]
favorite tab in dashboard section is not showing favorite dashboard.  this issue consistently reproduce when refreshing the home page

Expected results
favorite tab in dashboard section should show favorite dashboard in home page

Actual results
favorite tab in dashboard section not showing favorite dashboard in home page

#### Screenshots
https://user-images.githubusercontent.com/81597121/119906627-6e397b00-bf03-11eb-95b2-da31ee331462.mov

#### How to reproduce the bug
pre-condition:
user have favorite dashboard

steps:
1, go to home page and click on the 'favorite' tab in dashboard section
2, refresh the home page

### Environment

- superset version: master

### Checklist

- [ ] I have checked the superset logs for python stack traces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by pkdotson** [comment]
fix out: https://github.com/apache/superset/pull/14823
