### ISSUE TITLE
[home page] favorite tab in chart section is not showing favorite chart

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#14886]
favorite tab in chart section is not showing favorite chart, instead it show charts for 'Mine', this issue consistently reproduce when refreshing the home page

### Expected results
favorite tab in chart section should show favorite chart in home page

### Actual results

favorite tab in chart section not showing favorite chart in home page

### Screenshots
https://user-images.githubusercontent.com/81597121/119899184-a63ac100-bef7-11eb-8d7d-a50602b16205.mov

### How to reproduce the bug

steps:
1, go to home page and click on the 'favorite' tab in chart section
2, refresh the home page

### Environment

(please complete the following information):

- superset version: `master`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stack traces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [Y] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by pkdotson** [comment]
fix out: https://github.com/apache/superset/pull/14823

**Comment by junlincc** [comment]
resolved
