### ISSUE TITLE
[Bar Chart] Null Value bar for no data

### ISSUE THREAD

**Issue by musduo** [apache/superset#14893]
Hi, I have a bar chart and i am grouped this. But where there is no data, it displays a null value. How can I solve this?

### Expected results

I was expecting it to not generate a bar instead of a null value where there is no data. 

#### Screenshots

![slt](https://user-images.githubusercontent.com/78935007/119946666-8c54b900-bf9f-11eb-8c90-219d56f2c46f.png)

### Environment

(please complete the following information):

- superset version: `1.1.0`
- python version: `3.7.6`

**Comment by junlincc** [comment]
let's continue convo in #14929
