### ISSUE TITLE
CI: test built docker image with container-structure test

### ISSUE THREAD

**Issue by shawnzhu** [apache/superset#14904]
**Is your feature request related to a problem? Please describe.**
There is no test case to verify changes against `Dockerfile`. E.g.,  #14736 and #14903 

Which will defer verification of container image to the integration test or manual test.

**Describe the solution you'd like**
I'd like to introduce a new step to the Action workflow [`docker.yml`](https://github.com/apache/superset/blob/master/.github/workflows/docker.yml) to test built container with container structure test. For example:

https://github.com/IBM/docker-prestodb/blob/45544ec3b42bd594fee8e84e71f57a612c6c7f11/.github/workflows/test.yml#L28-L31

So that it can show test result and guard changes to `Dockerfile`. e.g.,

```
=========================================
====== Test file: test_config.yaml ======
=========================================
=== RUN: File Existence Test: superset-home
--- PASS


=========================================
================ RESULTS ================
=========================================
Passes:      1
Failures:    0
Total tests: 1

PASS
```

**Describe alternatives you've considered**
Document it so that contributors could manually test it.

**Additional context**
https://github.com/GoogleContainerTools/container-structure-test

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this today, please open a new Issue or a PR to address the problem.  

CC @mistercrunch for good measure in case this warrants any further follow-up

**Comment by rusackas** [comment]
Of course, let me know if I need further context and this needs to be reopened. If you do want to add more tests or other stability efforts, we're always appreciative of it, @shawnzhu - thanks!
