### ISSUE TITLE
Document Level Security is not honoured when running a query with superset and opendistro.

### ISSUE THREAD

**Issue by syamat** [apache/superset#14901]
When running a query against a opendistro instance (both in Chart  and SQL Lab)  all the records are fetched even though Document Level Security is applied on the index.

### Expected results

The query should run using the logged in user and not the user which is used to connect to the database.

### Actual results

The query is run using the user that connects to the database instead of the logged in user which is also present in the opendistro instance. 

### Environment

(please complete the following information):

- superset version: `1.1.0`
- python version: `Python 3.8.5`
- node.js version: `v14.15.5`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
