### ISSUE TITLE
non-interactice create-admin on installation

### ISSUE THREAD

**Issue by EMCP** [apache/superset#14913]
**Is your feature request related to a problem? Please describe.**

I am following https://superset.apache.org/docs/installation/installing-superset-from-scratch
```
$ export FLASK_APP=superset
superset fab create-admin
```

it is here I was hoping to do a non-interactive installation of the admin user.. I looked quickly but couldn't see a way to do this anywhere.. if it doesn't exist it'd be really welcome

**Describe the solution you'd like**

```
superset fab create-admin --file setup_credentials.txt 
```
inside this `setup_credentials.txt` we'd have some way to do the required pieces of data for the first admin user installation

**Describe alternatives you've considered**

For now I am installing this application and then pausing the installation and forcing users to ssh into the box and use their keyboard

**Additional context**

**Comment by nytai** [comment]
It exists, you can run `flask fab --help` for docs

**Comment by EMCP** [comment]
Interesting, I could have sworn I did that but it wasn't quite there.  Will
check again right away, thank you.
