### ISSUE TITLE
add support for preselect_filters to the dashboard native filters 

### ISSUE THREAD

**Issue by cccs-jc** [apache/superset#14918]
**Is your feature request related to a problem? Please describe.**

Not possible to share links to pre-filtered dashboards when using native filters. Only filter box works.

For example when the covid vaccine dashboard is configured with a country name filter box and you share your dashboard this link is produce and will open the dashboard with the appropriate filter.
 
http://localhost:8088/superset/dashboard/7/?preselect_filters=%7B%22119%22%3A%7B%22country_name%22%3A%5B%22Canada%22%5D%7D%7D

However this does not work in dashboards that use native filters. preselected_filters remains empty
http://localhost:8088/superset/dashboard/13/?preselect_filters=%7B%7D

**Comment by junlincc** [comment]
@cccs-jc good catch! This is definitely in our plan. do you guys have time to help implement this feature? 😄 cc @villebro

**Comment by villebro** [comment]
Discussed this with @cccs-jc - His team will take this on with support from me.
