### ISSUE TITLE
deck.gl demo seems not to fully render

### ISSUE THREAD

**Issue by EMCP** [apache/superset#14916]
### Expected results
I open the deck.gl demo, and should see for instance the san francisco map layer...

### Actual results

Seems some layers don't get rendered

I am on Ubuntu 20.04, Firefox

#### Screenshots

![image](https://user-images.githubusercontent.com/3691722/120085929-a34cf580-c0dc-11eb-82d4-957a476b5e40.png)

#### How to reproduce the bug

install fresh on ubuntu 20.04, using Firefox browser with latest updates as of todays date

### Environment

(please complete the following information):

- superset version: `v1.1.0`
- python version: `v3.8.5`
- node.js version: `n/a`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ X] I have reproduced the issue with at least the latest released version of superset.
- [ X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I searched the tickets and saw quite a few posts on deck.gl.. and understand it's a bit panicky.. but saw no one was getting quite as far as I was.. and yet not getting the full rendered maps.. so here we are.

**Comment by EMCP** [comment]
I think I've found the reason.. and perhaps I simply need to configure a mapbox API token.. maybe a warning on this demo would suffice to explain the lack of mapping

![image](https://user-images.githubusercontent.com/3691722/120111879-ee661780-c173-11eb-9864-470f87c7e2b7.png)

**Comment by EMCP** [comment]
Additionally, when I am in the Misc Charts demo, I see a warning about MapBox.. but when I click the link it 404's

![image](https://user-images.githubusercontent.com/3691722/120112004-5c124380-c174-11eb-9503-2d2ac1988361.png)

https://uber.github.io/react-map-gl/#/Documentation/getting-started/about-mapbox-tokens

![image](https://user-images.githubusercontent.com/3691722/120112023-6af8f600-c174-11eb-80ef-2f052c9382b3.png)

**Comment by roycegeo** [comment]
@junlincc I have the same issue that the map doesn’t display in these demos. I’ve added the mapbox token and it works on the demo labeled mapbox but the ones labeled deck.gl still don’t render the map. Any thoughts or suggestions would be greatly appreciated
