### ISSUE TITLE
unable to see public dashboards in Firefox anonymous session

### ISSUE THREAD

**Issue by zufolo441** [apache/superset#14912]
Hi,
we have lots of dashboards publicly available. In config.py there is PUBLIC_ROLE_LIKE ="Gamma".
when I try to see them in anonymous session I obtain following error.
In normal session they work.
I tried the git version of yesterday too.
![Schermata 2021-05-29 alle 08 37 31](https://user-images.githubusercontent.com/45826835/120060696-7c011480-c059-11eb-99c4-f3996fee5a10.png)

**Comment by junlincc** [comment]
@zufolo441 does it work in other browers? 

cc @amitmiran137 @simcha90 you may know

**Comment by suddjian** [comment]
Hi Francesco, could you please update the issue with the version of Superset that you're using?

**Comment by zufolo441** [comment]
Hi, I tried with Chrome and works.
Version is from git: 4f5c5372, but I tried version of 5 days ago too.

Thanks!

**Comment by zufolo441** [comment]
I've just tried the actual version:  a90e1685 . Same problem.
![Screenshot_20210607_085914](https://user-images.githubusercontent.com/45826835/120973029-b2801300-c76e-11eb-84e0-897f02a8271f.png)

**Comment by lilila** [comment]
I have the same problem, with Chrome, Firefox and Safari (haven't tried other browser). 
I have PUBLIC_ROLE_LIKE: Optional[str] = 'Gamma' and AUTH_ROLE_PUBLIC = 'Public' in config.py. 

When not logged I can access the list of published dashboards but when I want to open one get the following error: 
<img width="714" alt="image" src="https://user-images.githubusercontent.com/607430/122368538-b88ba600-cf5d-11eb-8d32-afae53c20f8d.png">

<img width="655" alt="image" src="https://user-images.githubusercontent.com/607430/122368718-de18af80-cf5d-11eb-84df-c7c498fd1ff8.png">

**Comment by villebro** [comment]
Let me try to reproduce this

**Comment by aspedrosa** [comment]
I think I was able to find the source for the problem.
The information of the user present on the state is empty (Maybe saying something wrong related to react concepts :sweat_smile: ).

![empty_user_on_state](https://user-images.githubusercontent.com/23409890/122455632-85b8d080-cfa4-11eb-9a79-f1d0a8535f3e.png)

At least its roles need to be present. Just to test I applied these changes to [superset/views/utils.py](https://github.com/apache/superset/blob/1.2.0rc2/superset/views/utils.py#L63)

![no_dashboard_on_public](https://user-images.githubusercontent.com/23409890/122455964-e47e4a00-cfa4-11eb-8385-32baaabfdedd.png)

**Comment by lilila** [comment]
fantastic, thank you!

**Comment by zufolo441** [comment]
For me, it didn't solve...
![Screenshot_20210618_172146](https://user-images.githubusercontent.com/45826835/122583588-b3138600-d059-11eb-991c-e557f04f4782.png)

**Comment by aussat** [comment]
I experienced the same issue after upgrading to 1.2.0 (installed using pip). The solution above worked perfectly for me. @aspedrosa thanks a lot!

**Comment by suddjian** [comment]
@aspedrosa great job! Would you mind opening a PR with your fix? I'd be happy to review and help get it merged.

**Comment by aspedrosa** [comment]
@zufolo441 
![image](https://user-images.githubusercontent.com/23409890/124917643-f8d5c580-dfeb-11eb-9e4c-fda7acc62327.png)
All the permissions I added to public

@suddjian sure :+1:
