### ISSUE TITLE
[Cosmetic][Bar chart]  Null bar values 

### ISSUE THREAD

**Issue by MustafaBulu** [apache/superset#14929]
How can I change viz.py to prevent it from showing null where there is no data in the grouped bar graph.I want it to print 0 instead of the null value. 

I think this is the part related to it 

```
#pandas will throw away nulls when grouping/pivoting,
        # so we substitute NULL_STRING for any nulls in the necessary columns
        filled_cols = self.groupby + columns
        df = df.copy()
        df[filled_cols] = df[filled_cols].fillna(value=NULL_STRING)
```

I'm writing 0 instead of NULL_STRING, but that doesn't have any effect.

**Comment by junlincc** [comment]
link https://github.com/apache/superset/issues/14893

**Comment by episkey24** [comment]
Hi, were there any updates on this one? How can we replace the null values with 0?

**Comment by episkey24** [comment]
@junlincc can you help?
