### ISSUE TITLE
Redirect to /login page if not logged in?

### ISSUE THREAD

**Issue by fmaritato** [apache/superset#14936]
**Is your feature request related to a problem? Please describe.**
We use okta for authentication, but right now, you have to know to click the login link in the upper right before you can access any dashboards. It's super confusing to our non-technical people who just get a link to a dashboard because it just shows a bunch of errors if they arent logged in.

**Describe the solution you'd like**
Is there a way to force superset to redirect to the /login page if they are not logged in?
I am using a custom superset_config.py and custom_sso_security_manager.py for okta anyway, maybe there is some way to accomplish this in there?

**Comment by nytai** [comment]
You should be able to achieve this with the custom security manager. I'm not sure how you're loading the user, but it should be simple to add a redirect in that method if no user is found.
