### ISSUE TITLE
Security Vulnerabilities In 1.1.0

### ISSUE THREAD

**Issue by kozelok** [apache/superset#14935]
Hello,

Following a security scan, we found these issues with the docker container:
![scan](https://user-images.githubusercontent.com/61063455/120377633-6276fb80-c2eb-11eb-8d67-e0fc47ac14ee.png)

Is it possible to resolve the security alerts?

Thank you

**Comment by junlincc** [comment]
@kozelok thanks for reporting, we will investigate and get back to you.
