### ISSUE TITLE
Error connecting Superset to SQL Server (pyodbc)

### ISSUE THREAD

**Issue by luisyuburi** [apache/superset#14944]
I am trying to connect Superset to MSSQL, I am using the pyodbc driver since pymssql gave me an error.

The error it hosts is the following:
ERROR: (pyodbc.InterfaceError) ('28000', "[28000] [Microsoft] [ODBC Driver 17 for SQL Server] [SQL Server] Login failed for user 'myUser. (18456) (SQLDriverConnect)")
(Background on this error at: http://sqlalche.me/e/13/rvf5)

I've been searching the internet about this problem and it seems to be a parameterization problem that usually occurs in python (UID and PWD settings), but in this case I'm trying to enter from Superset, so I don't know how to fix that .

It should be noted that from my Django project, I was able to connect without problems using pyodbc, the problem is to connect from Superset.

### Expected results

Connection OK with MSQQL

what you expected to happen.

Successfully connect to my database

### Actual results

ERROR: (pyodbc.InterfaceError) ('28000', "[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'rpa'. (18456) (SQLDriverConnect)")
(Background on this error at: http://sqlalche.me/e/13/rvf5)

what actually happens.

It does not allow me to connect to SQL Server from Superset

#### Screenshots

https://i.stack.imgur.com/BAJhl.png

(please complete the following information):

- superset version: `Superset 0.999.0dev`
- python version: `Python 3.7.9`
- node.js version: `I dont have node`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sfirke** [comment]
This is an old issue but as of Superset 2.0.0 I'm connecting fine to MSSQL databases in Superset, running on docker.  I'm using pymssql.

I have `pymssql` in a line in the file */docker/requirements-local.txt* so it gets installed, then in Superset my SQLALCHEMY URI is `mssql+pymssql://username:pwd@database_path:1433/database_name`.

If you or others are unable to connect to Microsoft SQL Server (as a database source, not as the metadata store which is not supported) in Superset 2.0.0 please reply and this can be reopened.

**Comment by rusackas** [comment]
Thanks for the tip, @sfirke - closing for now
