### ISSUE TITLE
On Refreshing Dashboards and Charts tab, UI layout changes

### ISSUE THREAD

**Issue by ukm21** [apache/superset#14946]
superset version :- 1.1.0
when I open the Dashboards tab for the first time the UI layout is as mentioned below
![image](https://user-images.githubusercontent.com/15329626/120475489-07b2d200-c3c7-11eb-9b9b-1e4686f09ba3.png)

But when I refresh this page the UI layout changes as mentioned below
![image](https://user-images.githubusercontent.com/15329626/120475564-244f0a00-c3c7-11eb-972d-aaec281e2c7a.png)

On Refresh new UI is reverting to Old layout

### Expected results
UI should not change on refresh

### Actual results
Dashboards and Charts UI layout is changing on browser refresh 

#### How to reproduce the bug

1. Go to Dashboards tab
2. Note the UI layout
3. Refresh the browser
4. See the Layout changes

### Environment

(please complete the following information):

- superset version: 1.1.0
- python version: 3.8.9
- node.js version: 12

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
should have been fixed in latest master🙏

**Comment by ukm21** [comment]
can you let me know the files where this issue have been fixed

**Comment by pawankurmi** [comment]
I am also facing same issue can someone guide on this.
