### ISSUE TITLE
Annotation Layer Date Clarity

### ISSUE THREAD

**Issue by matthewphua** [apache/superset#14958]
There is a little unclarity in setting the data range in the Annotation Layer. I'm assuming it should be [start date, end date). At one point, for some reason the start date was set to a day before the start date I entered. 

### Expected results
Assuming that it should be [start date, end date)

### Actual results
When I enter the end date first and then the start date second and then click save, the start date is the day before the start date I entered.

<img width="581" alt="image" src="https://user-images.githubusercontent.com/85198947/120567535-e6ea7c80-c3c6-11eb-8be0-ba259c7f615b.png">

<img width="874" alt="image" src="https://user-images.githubusercontent.com/85198947/120567540-eb169a00-c3c6-11eb-97fb-9a1e78b8e989.png">
You can see above that the start date is 1999 instead of 1-1-2000 which was the date I entered. Also the end date being exclusive is a little unclear, I set the date to be the 18th but the actual end date is the 17th. It would be great if exclusivity is specified.

#### How to reproduce the bug

1. Create an annotation layer
2. Enter end date first, then enter start date. I specifically entered 1-1-2000 for the start date and when I clicked save it 
3. Click save. 

### Environment

(please complete the following information):

- superset version: N/A
- python version: N/A
- node.js version: N/A

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@lilykuang Hi Lily, is it a known issue?

**Comment by nytai** [comment]
I think this might be related to some UTC conversion

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
