### ISSUE TITLE
[viz][treemap v2] click on corner the chart will move around and the section color is not correct with the represented number scale

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#14962]
2 issues seeing in the Treemap V2
1, the Treemap chart will move if clicking on the corner section of the chart
2, the bigger the number, the lighter the color in the treemap section, should i expect the other way?

### Expected results

1, click on the corner of the chart will not move it
2, color is darker with larger number?

### Actual results
1, chart is shifting position when click on the corner section
2, color is lighter with larger number

#### Screenshots

https://user-images.githubusercontent.com/81597121/120585338-663b7880-c3e6-11eb-8a51-fb76a0c0126c.mov

#### How to reproduce the bug

1. Open treemap v2 chart
2. Click on the corner or edge of the chart
3. observe

### Environment

(please complete the following information):

- superset version: master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by stephenLYZ** [comment]
fixed https://github.com/apache-superset/superset-ui/pull/1151

**Comment by rusackas** [comment]
Closing due to provided fix. Please re-open if the situation persists.
