### ISSUE TITLE
[native-filters]expanding filter bar should push top-level tabs along with main dashboard to the right 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14973]
https://user-images.githubusercontent.com/67837651/120715264-3ab59e00-c479-11eb-9ed0-aa98238b1b85.mov

<img width="1763" alt="Screen Shot 2021-06-03 at 2 35 29 PM" src="https://user-images.githubusercontent.com/67837651/120715290-430dd900-c479-11eb-98f7-b3a1bdb886d1.png">

@michael-s-molina @villebro 🙏

**Comment by michael-s-molina** [comment]
On it!
