### ISSUE TITLE
[Explore]sortby control for multiple metrics in Echarts timeseries 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14972]
Expected: selected sortby column should be desc

<img width="1494" alt="Screen Shot 2021-06-03 at 2 03 23 PM" src="https://user-images.githubusercontent.com/67837651/120713446-c37f0a80-c476-11eb-9074-dd3bb202461d.png">

**Comment by junlincc** [comment]
@villebro @zhaoyongjie  it turns out it's happening in NVD3 as well. very high priority. 
please make sure to check legacy and new chart, checkbox for single metric, and metric for multiple metrics 🙏

**Comment by junlincc** [comment]
Confirmed that sortby is broken in all charts ..🤦🏾‍♀️ @villebro @zhaoyongjie

**Comment by villebro** [comment]
On it

**Comment by villebro** [comment]
Fix: https://github.com/apache-superset/superset-ui/pull/1156

**Comment by junlincc** [comment]
can we double check it works in NVD3 as well? we can get it to the main repo for testing first

> Fix: [apache-superset/superset-ui#1156](https://github.com/apache-superset/superset-ui/pull/1156)

**Comment by villebro** [comment]
Confirmed to work as expected on both plugins:
NVD3:
![image](https://user-images.githubusercontent.com/33317356/130218737-8994f772-82d0-4435-b625-7d3f328d8265.png)
ECharts:
![image](https://user-images.githubusercontent.com/33317356/130218804-183a5511-0a51-474e-ab9b-c06fbdbb63b0.png)
