### ISSUE TITLE
[native-filters]close indicator popover on resize

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14974]
resizing window causes indicator popover disconnected. having it to follow the icon could be hard, we can at least close the popover  when start resizing 

https://user-images.githubusercontent.com/67837651/120716291-b06e3980-c47a-11eb-8bdf-c59cd4772ac6.mov

**Comment by BA1RY** [comment]
Hi @junlincc , I would like to work on this. How would you want me to proceed? 😃
