### ISSUE TITLE
[native-filters]upscope chart if the filter uses a different dataset? 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14977]
When creating a new filter, in the scoping tab, should we uncheck the checkbox if the chart is using a different dataset than the filter uses. In this case, the default radio select should be set in `Apply to specific panels`. 
Currently with the new out of scope filter section, even if a filter is completely incompatible with a chart, user can still scope it and the incompatible filter would show in the scoped section(on the top open by default), which is somewhat confusing. 

<img width="1784" alt="Screen Shot 2021-06-03 at 3 56 29 PM" src="https://user-images.githubusercontent.com/67837651/120722508-ad784680-c484-11eb-92e2-d7055a4ecd26.png">

<img width="1654" alt="Screen Shot 2021-06-03 at 4 13 42 PM" src="https://user-images.githubusercontent.com/67837651/120723604-e9aca680-c486-11eb-90a6-d9b9f75afec1.png">

Edge case: both available datasets have common column state.  

<img width="299" alt="Screen Shot 2021-06-03 at 4 17 52 PM" src="https://user-images.githubusercontent.com/67837651/120723826-5889ff80-c487-11eb-9ea5-d17b387bbea3.png">
<img width="299" alt="Screen Shot 2021-06-03 at 4 19 14 PM" src="https://user-images.githubusercontent.com/67837651/120723876-75263780-c487-11eb-9da9-fffcf826ffe4.png">

@villebro @kgabryje @michael-s-molina this proposed solution may not be ideal either, anything thoughts team?

**Comment by michael-s-molina** [comment]
I can help with the scoping tab.

**Comment by kgabryje** [comment]
I agree that it is confusing and the chart is definitely not _in scope_ of those filters. In my opinion we should implicitly exclude from filter's scope charts that use a different dataset than the filter (even when user selects "Apply to all panels"). If user selects "Apply to specific panels", charts that use a different dataset should not be shown in the tree. WDYT?

**Comment by villebro** [comment]
My suggestion would be as follows:
- Reword the subheader "All panels with this column will be affected by this filter" to "All panels with referencing this dataset will be affected by this filter"
- Do the following pruning to the scoping tree:
  1. Add the certification icon to charts that reference the same dataset
  2. Show the charts that are referencing a *different* dataset but containing the same column name. These would be unchecked by default, but could be forcefully applied, e.g. in the case where we want to construct a filter from a small static dimension table but should apply to a large fact table. This is a common use case, so it should be possible, but not the default behavior IMO.
  3. Hide charts that don't feature the same column name.

A few miscellaneous thoughts:
- Time grain and time column should probably only be applicable to charts with a dataset that features a temporal column (I'd leave this out of scope for now).
- We need to figure out a good way to encode this behavior into the dashboard metadata. Right now I believe we're always recording the excluded charts in the metadata; AFAIK the "Apply to all panels" option isn't explicitly recorded in the metadata and separable from the "Apply to specific panels" option. Let's discuss this more.

**Comment by michael-s-molina** [comment]
As discussed, let's freeze this issue for now until we have more context to work on a solution.

**Comment by villebro** [comment]
Additional task: remove charts from scope that don't support the filter component's emitted filter. For example: when adding a time range filter, remove charts that don't contain a temporal column.
