### ISSUE TITLE
[Explore] Cannot set y-axis lower bound to 0 on Line Chart

### ISSUE THREAD

**Issue by michellethomas** [apache/superset#14998]
On the Line Chart ("viz_type": "line") you cannot use the controls to set a y-axis lower bound of 0. As a hacky workaround you could set the lower bound to a small number (0.0001) or manually update the form data.

### Expected results

Setting y-axis lower bounds should update the form data and change the y-axis lower bound to 0.

### Actual results

Setting y-axis lower bounds to 0 keeps the form data as: "y_axis_bounds":[null,null] and nothing changes

#### Screenshots

![image](https://user-images.githubusercontent.com/817955/120872015-3a3d0600-c552-11eb-8d5d-c7294d738f61.png)

#### How to reproduce the bug

1. Create a line chart
2. Try to set the y-axis lower bound to 0

### Environment

(please complete the following information):

- superset version: master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zhaoyongjie** [comment]
closed by: https://github.com/apache/superset/pull/15091
