### ISSUE TITLE
[Dashboard]Native filter scoping tab should capture chart title change on dashboard

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14999]
In below video you can see that table "Publishers With Most Titles" had a title changed to "Top 10 Games (by Global Sales)" on Dashboard. Filter scoping only picks up the original titles in the config modal, which caused some confusion.....

Expected behavior: chart title change on dashboard should also update the chart name, vise versa. Filter scoping tab should capture and show the latest title whether user changes it from Explore or Dashboard. 

https://user-images.githubusercontent.com/67837651/120873157-d0266000-c555-11eb-873a-7c0a37c591bd.mov

**Comment by yousoph** [comment]
This has been fixed / can no longer repro this issue
