### ISSUE TITLE
Dynamic header component in dashboards

### ISSUE THREAD

**Issue by cccs-jc** [apache/superset#15006]
**Is your feature request related to a problem? Please describe.**
The Header component is a great way to add titles to dashboards however the text is static.

**Describe the solution you'd like**
We would like to dynamically show the category selected by the user. For example in this dashboard a sector is chosen. The charts update accordingly. However it would be much clearer if the chosen category was clearly visible in a dynamic header component.

**Describe alternatives you've considered**
Did not find any alternatives.

![dynamic-dashboard-header](https://user-images.githubusercontent.com/56140112/120892859-2e972100-c5de-11eb-941f-c6a94b600f74.JPG)

**Comment by rusackas** [comment]
@cccs-jc Is this issue still of interest to y’all? Tempted to close it as stale, but also willing to convert it to an “Ideas” thread if that’s relevant. Nielsen made it possible to add such dynamic dashboard components, but I’m not sure if that scratched the issue for you. If you do have such a feature built out, it might be an interesting OSS contribution!

**Comment by rusackas** [comment]
Heard back that this isn't a priority for now, but since the framework for such a feature now exists, it'll get re-opened with updated context if it becomes a priority again.

**Comment by kyle-kent** [comment]
Interested!

**Comment by antonio-olleros** [comment]
Interested also here!

**Comment by liany-dropit** [comment]
We would love to have this capability

**Comment by mccuartero1103** [comment]
Hope to have this soon! <3

**Comment by rfdccarvalho** [comment]
Interested!

**Comment by Ayoub-BOUCHACHIA** [comment]
Interested !!

**Comment by skannan-maf** [comment]
Interested! The same for "Chart title" as well

**Comment by fletcherdemeoliq** [comment]
interested

**Comment by huafist** [comment]
Absolutely interested

**Comment by masterworgen** [comment]
Absolutely interested

**Comment by PutingZhao** [comment]
Interested !!

**Comment by ajpanwar** [comment]
interested

**Comment by tabgruedksr** [comment]
Interested!

**Comment by guillaumerue82** [comment]
Dying for it !
