### ISSUE TITLE
Have no change language option

### ISSUE THREAD

**Issue by lx1054331851** [apache/superset#15018]
![image](https://user-images.githubusercontent.com/12423206/121031671-248f4100-c7dd-11eb-89fc-c509715d9c16.png)

**Comment by raito4** [comment]
I have the same question and I modified the config.py then restart the server it also won't change languages.
![image](https://user-images.githubusercontent.com/22333642/148174350-804521d9-2b12-4a7d-807d-7f9121e5392a.png)

**Comment by hbruch** [comment]
For configuration questions, you probably should rather start a GitHub discussion or join the superset slack.

Concerning your config, be sure you have not overridden your config by LANGUAGES = {} a [few rows below](https://github.com/apache/superset/blob/b3db6140c88106fedebe91db0ca817eca4234dc8/superset/config.py#L329).
I added my LANGUAGES config to `superset_config_docker.py`(as I use the docker-compose setup) and it works as expected.

**Comment by raito4** [comment]
> 

Hi, Holger:
I use docker too, could you please tell me where I can find the superset_config_docker.py? I can only find the superset_config.py. Thank you.

**Comment by liuyong888** [comment]
> Hi @raito4 
This is the config I wrote.
Is work！

![image](https://user-images.githubusercontent.com/45752479/197250272-efd97d80-f1bb-4826-ad81-52c8a7654be9.png)

It is worth noting that the superset cache is very severe and requires all data to be cleared in the site Settings.

![image](https://user-images.githubusercontent.com/45752479/197251102-9ca8012e-40fe-4c06-88e3-86362c260abc.png)

### Bingo!

![image](https://user-images.githubusercontent.com/45752479/197251403-a93d0961-75f0-42e5-ae5e-c2815959045f.png)

If you want better Chinese effect, Run the following command inside the Docker container
`pybabel compile -d superset/translations`
