### ISSUE TITLE
[native-filters][select]multiple select dropdown open from the top 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#15029]
Expected behavior: when user reopen the select dropdown with a bunch of selected filters, the dropdown should have a initial focus at the top to show all the selected items. 
Current behavior: drop down takes user to the bottom. :( 

https://user-images.githubusercontent.com/67837651/121098597-10325080-c7ab-11eb-88fb-dca5d032959d.mov

@geido @michael-s-molina @villebro 🙏

**Comment by michael-s-molina** [comment]
Wow, nice catch!
