### ISSUE TITLE
[native-filters]magnifier in filter indicator is not connected to range, time filter etc. 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#15030]
In the Native filter project, we use different components (tabs & charts highlighter, filter locator-magnifier, upscoped filter section etc) to visualize the relation between charts/tabs and filters. 

Expected behavior: When user click on the magnifier 🔎 icon of any filter in the filter indicator popover, we should place the curse in the same filter on the left panel, and highlight the filter field. It works at value filter, but not for range, time filter and more. 

<img width="1548" alt="Screen Shot 2021-06-07 at 4 25 06 PM" src="https://user-images.githubusercontent.com/67837651/121100560-001c7000-c7af-11eb-852c-1b92cd47d6bb.png">

https://user-images.githubusercontent.com/67837651/121099098-1117b200-c7ac-11eb-9786-1af83ef7daa7.mov

**Comment by rusackas** [comment]
This is likely dealt with by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
