### ISSUE TITLE
I want to specify custom time grain

### ISSUE THREAD

**Issue by EBoisseauSierra** [apache/superset#15037]
## Issue

I would like to aggregate my time-series charts on custom time grains. Currently only “1 unit” grains are available: 1s, 1min, 1h, 1 day, etc.

Yet I would like to be able to aggregate by, e.g., 5-minute, 15-minute, 6-hour time buckets.

## Requested feature

I want to be able to define custom time grains.

This could happen either:

* as a Superset instance specific variable (i.e. defining new time grains in `superset_config.py`): this has the advantage of ensuring that only admin specify time grains (greater chance for the definition to be correct and less burden on users) and enable it for any user in the already existing dropdown.
* in the Explore panel:
  * let the user specify a “magic string” (e.g. `15T`, `6H`, etc. : easiest to implement, greatest flexibility, yet risk of parsing garbage)
  * build a GUI for it (number input to specify `5`, `6`, or `15` + dropdown menu to select the unit `minute`, `hour`, etc.)

## Alternative

None that I'm aware of.

## Additional info

We'd like to have these time grains available to `pandas.resample` advanced feature as well.

**Comment by junlincc** [comment]
@EBoisseauSierra thanks for the request. i like the idea we have been thinking about blending all time controls including time grain into one time range popover, eventually remove the concepts of time, and have it be a part of regular filter in Explore. this will be the next long tail project which requires lots of planning and design. lmk if your team is interested in collaborating

**Comment by EBoisseauSierra** [comment]
Actually, shouldn't it already possible via [the `TIME_GRAIN_ADDONS` variable in `config.py`](https://github.com/apache/superset/blob/master/superset/config.py#L542-L565)?!

(I haven't successful in trying it myself yet, but I'll raise a separate issue if required.)

**Comment by lelelethu** [comment]
> Actually, this is already possible via the `TIME_GRAIN_ADDONS` and `TIME_GRAIN_ADDON_EXPRESSIONS` variables [in `config.py`](https://github.com/apache/superset/blob/master/superset/config.py#L542-L565), thanks to @villebro!

When i using that but not working.
This my code in config.py:
TIME_GRAIN_ADDONS = {
    'PT2S': '2 second',
    "PT6H": "6 hours",
    "PT15M": "15 minutes",
}

TIME_GRAIN_ADDON_EXPRESSIONS = {
    'postgresql': {
        'PT2S': 'toDateTime(intDiv(toUInt32(toDateTime({col})), 2)*2)',
        'PT6H': "date_trunc('day', {col}) + date_trunc('hour', {col})::int / 6 * interval '6 h'",
        'PT15M': "date_trunc('hour', {col}) + date_part('minute', {col})::int / 15 * interval '15 min'",
    }
}

What am I wrong?

**Comment by janajay** [comment]
@lelelethu you need to use this in file superset_config.py it will get reflect
TIME_GRAIN_ADDONS = {"PT2S": "2 second"}

TIME_GRAIN_ADDON_EXPRESSIONS = {
    "clickhouse": {
        "PT2S": "toDateTime(intDiv(toUInt32(toDateTime({col})), 2)*2)",
    }
}

**Comment by GODFATHRII** [comment]
I used this in superset_config.py file, it doesn't work and show me any options for some reason.
TIME_GRAIN_ADDONS = {"WS_WED": "Week starting Wednesday", "WS_THURS": "Week starting Thurday"}

TIME_GRAIN_ADDON_EXPRESSIONS = {
    "clickhouse": {
        "WS_WED": """
            toDateTime(
                intDiv(
                    toUInt32(
                        toDateTime(
                            addDays({col}, 3 - toDayOfWeek(toDateTime({col})))
                        )
                    ),
                    2
                ) * 2
            )
        """,
      "WS_THURS": """
            toDateTime(
                intDiv(
                    toUInt32(
                        toDateTime(
                            addDays({col}, 4 - toDayOfWeek(toDateTime({col})))
                        )
                    ),
                    2
                ) * 2
            )
        """,
    }
}

**Comment by eschutho** [comment]
It could be not working for clickhouse specifically because clickhouse has two db engine specs. Make sure that your db connection is using the `clickhouse://` dialect and not `clickhousedb://`. Otherwise you'll want to use `clickhousedb` as the key in your `TIME_GRAIN_ADDON_EXPRESSIONS` dict.

**Comment by eschutho** [comment]
Same for postgres. Check that your dialect in your connection is `postgresql` and not `postgres`
