### ISSUE TITLE
Add Netezza in supported databases in superset

### ISSUE THREAD

**Issue by abhishekjog** [apache/superset#15039]
https://superset.apache.org/docs/databases/installing-database-drivers states list of supported databases and drivers in superset. Netezza now has fully functional SQLAlchemy dialect with DB API 2.0 compliant nzpy driver. Request you to add it in supported databases.

When I install superset and try connection string "netezza+nzpy://user:password@hostname:port/database", I get error "ERROR: Could not load database driver: netezza+nzpy"
 
### Expected results

netezza+nzpy should work in superset. 

### Actual results

ERROR: Could not load database driver: netezza+nzpy

#### How to reproduce the bug

(prerequisite: you need a Netezza database)
On any system: 
1. run superset container with docker-compose
2. from browser "hostname:8088", login to superset
3. add new database. 
4. In connection string: netezza+nzpy://username:password@hostname:port/database

I was hoping, installing nzalchemy in superset container would solve it. So I installed nzalchemy and nzpy in the container. Checked sample query execution using SQLAlchemy, it worked fine. But from browser, still getting the error.

### Environment

(please complete the following information):
```
root@195cd43c0a7d:/# superset --version
Python 3.8.6
Flask 1.1.2
Werkzeug 1.0.1
```
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

https://superset.apache.org/docs/databases/installing-database-drivers states 
```
If your database or data engine isn't on the list but a SQL interface exists, please file an issue on the Superset GitHub repo, so we can work on documenting and supporting it.
```
Hence this issue.

**Comment by junlincc** [comment]
Thanks for suggesting! this feature request sounds reasonable, please feel free to open a PR for the new connection along with documentation separately. We will get those review timely :)

**Comment by srinify** [comment]
Closing since @abhishekjog took on the work of adding docs + a db engine spec!

https://github.com/apache/superset/pull/15450
