### ISSUE TITLE
no time grain available when using odelasticsearch

### ISSUE THREAD

**Issue by furyou81** [apache/superset#15034]
Hi, 

I am using Superset with an odelasticsearch databases. I have a DateTime column and I am able to make queries in SQL Lab and to display graph. But I don't have any Time Grain available in the dropdown (it is working fine when using other databases).

[
![Screenshot 2021-06-08 at 11 37 48](https://user-images.githubusercontent.com/33728425/121162447-378e2980-c84e-11eb-94fd-1e154e03796c.png)
](url)

**Comment by furyou81** [comment]
I am on version 1.0.1 and my connection string is as follow: odelasticsearch+https://xxx-xxx.eu-west-1.es.amazonaws.com:443/

**Comment by junlincc** [comment]
@furyou81 try v1.2 or latest master?

**Comment by furyou81** [comment]
so when using v1.2 I the time grain are there but I have an other issue.

I have a field called DATETIME. I noticed that when the request was done it is using "DATETIME" and it fails as it is a reserved SQL word so I added a calculated column which modifies it so `DATETIME`. And everything is working fine until I try to add a time range.

If I add a time range, it is adding an additiona "DATETIME" as bellow:

`SELECT date_format(`DATETIME`, 'yyyy-MM-dd 00:00:00.000') AS __timestamp,
       COUNT(*) AS count
FROM "default"."psr-2021-06"
WHERE "DATETIME" >= '2021-05-31T00:00:00'
  AND "DATETIME" < '2021-06-07T00:00:00'
  AND `DATETIME` >= '2021-05-31T00:00:00'
  AND `DATETIME` < '2021-06-07T00:00:00'
GROUP BY __timestamp
LIMIT 10000;`


I also tried to use an other field but it still tries to add "DATETIME". I also tried to delete DATETIME from the dataset on Superset and then it complains that the field DATETIME is not found event if I am not asking to use it

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
