### ISSUE TITLE
Time-Series Chart Showing Min/Max X-Axis Values Even Though Disabled

### ISSUE THREAD

**Issue by jamesrayoub** [apache/superset#15042]
## Screenshot

![image](https://user-images.githubusercontent.com/31777200/121226613-c30cb800-c858-11eb-9811-b5c262a44e40.png)

## Description

By default, the min & max x-axis values appear to be showing despite the fact that they are disabled. I am able to remove by enabling then disabling again using the checkboxes. I'd imagine the default behavior is to not show those values but if it is, then perhaps the checkboxes should be marked by default...

**Comment by junlincc** [comment]
thanks for reporting
please see video for more context. @xiezhongfu can you take this on? 🙏
Expected behavior: when user first interact with Timeseries echarts, Min and Max on x-axis should show by default, 2 checkboxes should be checked by default/ 

https://user-images.githubusercontent.com/67837651/121228730-f6901800-c841-11eb-894c-18fa4664fbc3.mov

**Comment by xiezhongfu** [comment]
#### superset
- firstly, rendered the `table` chart which has not `xAxisShowMinLabel` control.
- when we chose `Time-series Chart`, and rendered it. `Time-series Chart` has a `xAxisShowMinLabel` control. But the `value` property is `undefined`
![image](https://user-images.githubusercontent.com/10264972/121389263-cbf7a980-c97e-11eb-8e1d-e0ef9ee0eda3.png)
![image](https://user-images.githubusercontent.com/10264972/121389285-d31eb780-c97e-11eb-84ec-9342cec8786c.png)

- we can set `value` by `mapStateToProps` or `default function`
![image](https://user-images.githubusercontent.com/10264972/121388117-c8175780-c97d-11eb-9dd8-7f10402d5574.png)

#### suyperset-ui
But **default is false** refer: https://github.com/apache-superset/superset-ui/blob/master/plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx#L343


#### solution
All in total, we can set `value` by mapStateToProps.

**Comment by zhaoyongjie** [comment]
I can not reproduce in the latest master and `Time-series Chart`

![image](https://user-images.githubusercontent.com/2016594/121461905-545b6600-c9e2-11eb-8c14-0cee9931f2cc.png)

**Comment by junlincc** [comment]
@villebro can you clarify what's the expected behavior?

**Comment by xiezhongfu** [comment]
https://echarts.apache.org/en/option.html#xAxis.axisLabel.showMinLabel.  
The options of showMinLabel are `true, false, null`.  

So, I think `undefine` is invalid, We should correct it in any case.
