### ISSUE TITLE
[import/export][native-filters]import/export is incompatible with Native filters

### ISSUE THREAD

**Issue by junlincc** [apache/superset#15050]
to reproduce: Export dashboard with native filters locally and import to a Preset workspace
Currently behavior: When user create a dashboard with dashboard native filters, it can't be exported and imported properly in JSON format. 
Expected behavior: dashboard with native filters should be able to import and export. 

https://user-images.githubusercontent.com/67837651/121264492-11778200-c86c-11eb-860d-960b5e1808f6.mov

**Comment by junlincc** [comment]
another issue, unrelated to filter~ 
every click to import the JSON file, trigger a toast message, and same dashboard gets imported. 

Expected behavior, only import once with multiple clicks.

**Comment by villebro** [comment]
No action needed - exporting from local instance and importing to both local instance (after first deleting original chart and dashboard) and Preset confirmed to work as expected.

See below screenshot of imported dashboard with a Value filter with predefined default values:
![image](https://user-images.githubusercontent.com/33317356/122521986-213a5780-d01e-11eb-9206-4461726e1a46.png)

**Comment by villebro** [comment]
Reopening - table references need to be updated in native filter metadata
