### ISSUE TITLE
[native-filters*1]Multiple dashboard native filter UX improvement 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#15067]
DONE - 1. Filter bar open by default if the dashboard has filters 
When user open a dashboard that has filters attached, most likely the user will interact with those filters. with each time user collapse and open the bar, all charts on the dashboard get re-render. Leaving the filter bar open by default could prevent unnecessary performance issue. 

@kgabryje 🙏

**Comment by junlincc** [comment]
2. Imagine user have 5 filters scoped to tab A, 25 filters scoped to tab B and tab C, and user is currently in tab A. 25 out of scope filters will hide in a collapsible section with a number indication for the total number of out of scope filters. 
1) don't run query for those 25 out of scope filters until user open the collapsible section 
2) if user want to interact with/select a filter value in filters that are scoped to tab B & C in tab A, tab B & C will be highlighted, all charts in tab A will be "greyed out" as an indication the interaction will not take effect. note: the apply button remains blue at the initial state, turn grey on click. edge case: what if user also select a value in one of the in scope filters?

**Comment by junlincc** [comment]
3. the current highlighting color is not strong enough as indicator, let's change to a different one in product color scheme 
@rusackas 🙏
https://projects.invisionapp.com/share/BNVBOEJRWQ2#/screens/398392085

**Comment by junlincc** [comment]
4. change modal name from Filters configuration to Filters configuration and scoping

**Comment by junlincc** [comment]
5. Remove instant apply checkbox  @villebro 
*please convert comment into issue once PR is open, and tag issue

**Comment by junlincc** [comment]
historically, in the dashboard area, there's a mysterious drop shadow under neath top level tab. As we are releasing dashboard native filter, Dashboard layout will be clearly divided into 2 areas -> filter bar and main dashboard. For consistency and better UIWe should either wrap the dashboard with drop shadow all around, or remove the one on top for constancy.  

<img width="1786" alt="Screen Shot 2021-06-09 at 1 58 50 PM" src="https://user-images.githubusercontent.com/67837651/121427779-f5d2b100-c929-11eb-85f6-cafca7b719ea.png">


*please convert comment into issue once PR is open, and tag the new issue

**Comment by kgabryje** [comment]
> 1. Filter bar open by default if the dashboard has filters
>    When user open a dashboard that has filters attached, most likely the user will interact with those filters. with each time user collapse and open the bar, all charts on the dashboard get re-render. Leaving the filter bar open by default could prevent unnecessary performance issue.
> 
> @kgabryje 🙏

@junlincc It seems that it's already been implemented and is on master since June 7th.

**Comment by michael-s-molina** [comment]
> 1. change modal name from Filters configuration to Filters configuration and scoping
> 
> @villebro

Done in https://github.com/apache/superset/pull/15115

**Comment by michael-s-molina** [comment]
> historically, in the dashboard area, there's a mysterious drop shadow under neath top level tab. As we are releasing dashboard native filter, Dashboard layout will be clearly divided into 2 areas -> filter bar and main dashboard. For consistency and better UIWe should either wrap the dashboard with drop shadow all around, or remove the one on top for constancy.
> 
> <img alt="Screen Shot 2021-06-09 at 1 58 50 PM" width="1786" src="https://user-images.githubusercontent.com/67837651/121427779-f5d2b100-c929-11eb-85f6-cafca7b719ea.png">
> 
> @michael-s-molina
> 
> *please convert comment into issue once PR is open, and tag the new issue

Done in https://github.com/apache/superset/pull/15115

**Comment by michael-s-molina** [comment]
> 1. the current highlighting color is not strong enough as indicator, let's change to a different one in product color scheme
>    @rusackas 🙏
>    https://projects.invisionapp.com/share/BNVBOEJRWQ2#/screens/398392085
> 
> * please convert comment into issue once PR is open, and tag issue

Done in https://github.com/apache/superset/pull/15192
