### ISSUE TITLE
Helm installation pauses at superset-init-db

### ISSUE THREAD

**Issue by pavimimos** [apache/superset#15061]
The helm installation stops at superset-init-db.

I tested it in k8s cluster and microk8s cluster, same results.

#### Screenshots
![image](https://user-images.githubusercontent.com/74908755/121337623-51fbfc00-c94f-11eb-888d-a7c50328c1b8.png)

_i checked the redis logs and found this:_

![image](https://user-images.githubusercontent.com/74908755/121337467-2711a800-c94f-11eb-86c2-0f74d50fcb09.png)

**Comment by mvoitko** [comment]
Why have you closed the bug?
