### ISSUE TITLE
Permissions issue with superset- DataSource

### ISSUE THREAD

**Issue by prachir1501** [apache/superset#15066]
We need help with permisions for our superset usecase. We want each user to upload csv to default database but other users should not see that csv table. Here is high level permission that we want to setup:

- create new data source
- create new chart
- create new dashboard
- cannot see other users data source
- cannot see other users chart
- cannot see other users dashboard
- can upload csv only to data source that he/she created

A problem which arose was with the charts when we use same database, different gamma users can see the tables created by other users when selecting a table for chart, on the Create Chart page.

Should we have new database for every user to achieve that? Can it be achieved using same default data source for every user?

**Comment by russmatney** [comment]
I think this is the same issue as described here: https://github.com/apache/superset/issues/13944 This is definitely a problem, and a blocker for use cases where users shouldn't be able to see each other's data sources.

**Comment by prachir1501** [comment]
I have figured out a workaround as follows (for the charts) -
In the file `superset/lib/python3.6/site-packages/superset/views/chart/views.py`,
 we can modify the add function as follows-
```
def add(self) -> FlaskResponse:
    from flask import g
    from superset.views.utils import bootstrap_user_data
    temp = ConnectorRegistry.get_all_datasources(db.session)
    temp2 = []
    for d in temp:
        if(str(d.created_by) == str(g.user)):
            temp2.append(d)

    datasources = [
        {"value": str(d.id) + "__" + d.type, "label": repr(d)}
        for d in temp2
    ]

    payload = {
        "datasources": sorted(datasources, key=lambda d: d["label"]),
        "common": common_bootstrap_payload(),
        "user": bootstrap_user_data(g.user),
    }
    return self.render_template(
        "superset/add_slice.html", bootstrap_data=json.dumps(payload)
    )
```

**Comment by russmatney** [comment]
@prachir1501 nice - thanks for sharing. Probably something similar could prevent exposing all the users to each other as well (https://github.com/apache/superset/issues/15026).

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for over two years, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
