### ISSUE TITLE
PRESTO_EXPAND_DATA for athena connector

### ISSUE THREAD

**Issue by fxgsell** [apache/superset#15077]
**Is your feature request related to a problem? Please describe.**
Support the Expand data feature for Athena.

**Describe the solution you'd like**
Either add a ff ATHENA_EXPAND_DATA or reuse the existing PRESTO_EXPAND_DATA.

**Additional context**
Athena is based on Presto, therefore the presto solution might be easily reusable for Athena too.

**Comment by villebro** [comment]
Great idea! I think it's ok to reuse the `PRESTO_EXPAND_DATA` FF for now (we can later separate them if needed). Would you be willing to open a PR to add this functionality to the Athena connector?

**Comment by rumbin** [comment]
It would be great to have this feature...

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and is a feature request rather than a bug. If anyone wants to pick this back up (which I hope is the case) please open an Ideas discussion or a PR to add the feature. Thanks!
