### ISSUE TITLE
support the tree catalog classification management

### ISSUE THREAD

**Issue by snycc15** [apache/superset#15083]
Is there a plan to support the tree catalog classification management function to store and retrieve data models, indicators, visualizations, dashboards and other resources?

**Comment by rusackas** [comment]
Not quite understanding your proposal, but it's not a bug, so I'll close this as stale since it's been silent for so long. Please pick this up on Github Discussions or [Slack](http://bit.ly/join-superset-slack) if you want to investigate further.
