### ISSUE TITLE
Superset breaks after proxy adds a `X-Content-Type-Options: nosniff` header

### ISSUE THREAD

**Issue by krish7919** [apache/superset#15089]
1. I set up Superset without any auth and everything runs fine.
2. Post this, I introduced a proxy in between which also handles auth. This proxy inserts the `X-Content-Type-Options: nosniff` header as is the standard way to force browsers to not interpret code.

In scenario 2, the browser (I have checked with Edge and Firefox), the content is not rendered with an error on the browser console as `The resource from “https://X.Y.Z” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).`

As per https://stackoverflow.com/a/53062522, we need to explicit identify these sources and add the mime types for them accordingly.

#### How to reproduce the bug

Add the `nosniff` option for the browser as a header and open superset on any of the browsers.

### Environment

(please complete the following information):

- superset version: `superset version`

```
superset@a1df89430550:/app/superset$ superset --version
Python 3.7.9
Flask 1.1.2
Werkzeug 1.0.1
```

- python version: `python --version`

```
superset@a1df89430550:/app/superset$ python --version
Python 3.7.9
```

- node.js version: `node -v`

```
superset@a1df89430550:/app/superset$ node -v
bash: node: command not found
```

This is running in the oficial Superset container.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any. **Not applicable**
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by krish7919** [comment]
Bump someone?

**Comment by rusackas** [comment]
Closing this issue as stale since it's been over a year and a half, with sadly little corroboration from others. Holler if you're still facing this in current-era Superset (e.g. 2.0.x) and we'll revisit/reopen as warranted!
