### ISSUE TITLE
Dashboard metadata UI save unexpected behavior

### ISSUE THREAD

**Issue by krsnik93** [apache/superset#15085]
I wanted to update dashboard metadata through the UI. I changed JSON metadata and clicked save in the modal (photo 1 below). Modal closed and then I clicked Save in the dashboard header (photo 2 below).

Photo 1:
![image](https://user-images.githubusercontent.com/13034472/121518383-50cadd80-c9e8-11eb-8532-efac3fe89dae.png)

Photo 2:
![image](https://user-images.githubusercontent.com/13034472/121518416-5aecdc00-c9e8-11eb-8349-a7c97bf5e859.png)

### Expected results

Expect changes to be applied.

### Actual results

Save number 2 cancels out changes from save number 1. Way to mitigate is to do save number 1 and then, when the modal closes, hit refresh. This is not intuitive at all. Another way to mitigate could be to perform save number 1 and then click Discard changes, but I haven't tested this and it's not intuitive either.

### Environment

- superset version: 1.1.0
- python version: 3.7.10

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by yousoph** [comment]
Should be fixed by #17392
