### ISSUE TITLE
Stale documentation on filter_immune_slice_fields

### ISSUE THREAD

**Issue by krsnik93** [apache/superset#15086]
## Screenshot

![image](https://user-images.githubusercontent.com/13034472/121519597-cf744a80-c9e9-11eb-8683-82500d880c73.png)

## Description

Superset documentation at https://superset.apache.org/docs/frequently-asked-questions mentions `filter_immune_slice_fields` as a top-level key in dashboard metadata JSON. However, the key was dropped in favour of `filter_scopes`. Using `filter_immune_slice_fields` to modify dashboard metadata results in 400 response code with `filter_immune_slice_fields: unknown_field` validation error.

**Comment by rusackas** [comment]
Closing this issue here, and moving it to BugHerd, where we keep our docs requests. We could use help opening PRs to fix these things, if you have interest in this area. 

CC @sfirke — https://www.bugherd.com/projects/334204/tasks/127
