### ISSUE TITLE
Publish Release Candidate Docker Images

### ISSUE THREAD

**Issue by andreas-eberle** [apache/superset#15087]
The master builds are published as docker images on dockerhub. However, I cannot find the release candidates. I think those should be easy to test to allow people to easily test them before the actual release. For that, it would be helpful if you can publish the release candidate docker images on dockerhub with their respective tag.

**Comment by andreas-eberle** [comment]
I just noticed that the 1.0 RCs had been published to dockerhub. Unfortunately, the 1.2 RCs aren't.

**Comment by D3nn3** [comment]
Bump.

v1.3.0 has been released 8 days ago but unfortunately there still isn't any docker image available.

**Comment by michael-s-molina** [comment]
Closing this issue as RC tags are being published to docker hub:
[2.0.1rc6](https://hub.docker.com/r/apache/superset/tags?page=1&name=2.0.1rc6)
[1.5.3rc1](https://hub.docker.com/r/apache/superset/tags?page=1&name=1.5.3rc1)
