### ISSUE TITLE
Cascade native dashboard filter with default value does not load the default value during initial load

### ISSUE THREAD

**Issue by ankitmani2004** [apache/superset#15088]
### Expected results

During initial load, default value should populate in cascading filter and should load the charts in dashboard according to filter value.

### Actual results

Cascade filter shows "No Results" unless you click on the filter once(expand button to see the cascade filter values) and only then it loads the default value automatically.

#### How to reproduce the bug

1. create a cascading filter (filter with parent filter)
2. Set aa default value for the parent filter
3. refresh the dashboard
4. you will see "No Result" on cascade filter
5. click on expand button, now the default value will be populated and dashboard will be loaded as per filter

![image](https://user-images.githubusercontent.com/16845460/121537136-aa73dd80-c9d1-11eb-869e-41379aaf0f90.png)
![image (1)](https://user-images.githubusercontent.com/16845460/121537142-ac3da100-c9d1-11eb-9176-9a66844baadb.png)

**Comment by villebro** [comment]
What version are you on @ankitmani2004 ? I am unable to reproduce on master (the parent value populated via default value, with child values being filtered by parent as expected):

![image](https://user-images.githubusercontent.com/33317356/121994854-afa8a200-cdae-11eb-8822-7a1f4c74b97d.png)

**Comment by ankitmani2004** [comment]
Thanks. I am  using latest apache:superset image. 
how to reproduce: 1) define a cascade filter, 2) Define a default value for the filter 3) refresh the page.
How it behaves: Default value will not load and will show "No Results". 
You click on 3 lines sign, to expand the cascade filter, then the value will refresh and will show in the filter

**Comment by yousoph** [comment]
Can no longer repro this
