### ISSUE TITLE
Native Filter not applying filters to Big Number and Time Series Bar Charts

### ISSUE THREAD

**Issue by saultawil** [apache/superset#15094]
### Expected results

When filtering using native filter should apply filter to all charts

### Actual results

Filter applies to Time Series Line Charts and Pie Charts only but not to Big Number and Time Series Bar Charts

#### Screenshots

![image](https://user-images.githubusercontent.com/60597083/121561684-690b1e80-ca21-11eb-8574-36a7779961b7.png)

#### How to reproduce the bug

1. Go to Native Filter and filter on one of select filters
2. Click on Applied Filters icon for Big Number chart
3. See that the filter exists with the value in Unset Filters but is incorrectly not being applied

### Environment

- superset version: 1.1.0
- python version: Python 2.7.5
- node.js version: v14.17.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ Y] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ Y] I have reproduced the issue with at least the latest released version of superset.
- [ Y] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
thanks for reporting. this should have been addressed if you are on 1.1 currently.🙏

**Comment by saultawil** [comment]
(venv) [centos@ip-172-31-40-12 ~]$ superset version
/home/centos/venv/lib/python3.7/site-packages/pandas/compat/__init__.py:97: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
logging was configured successfully
INFO:superset.utils.logging_configurator:logging was configured successfully
No PIL installation found
INFO:superset.utils.screenshots:No PIL installation found
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Superset 1.1.0
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

**Comment by saultawil** [comment]
Interestingly when I go into explore I see the filter applies:
![image](https://user-images.githubusercontent.com/60597083/121574317-cd80aa80-ca2e-11eb-9e3d-e40893ce3d02.png)

Why doesn't it work from the dashboard? What can be wrong?

**Comment by saultawil** [comment]
@junlincc - I dont think this should be closed and I cannot reopen this - should I open a new issue?

**Comment by saultawil** [comment]
For the benefit of others I found that the following bug was caused by setting feature flags "CLIENT_CACHE" or "DASHBOARD_CACHE" to true; when I set them to false the issue went away.
