### ISSUE TITLE
[dashboard]Toasts when saving/adding to dashboard are duplicated and get overlaid on themselves

### ISSUE THREAD

**Issue by junlincc** [apache/superset#15099]
Expected behavior: When user save a chart to dashboard, only one toast msg should show, and only once. 🤦🏾‍♀️
toast msg: Chart[chart_name] has been saved and added to dashboard [dashboard_name]

https://user-images.githubusercontent.com/67837651/121575564-64704700-c9dc-11eb-99df-a2120228d355.mov

**Comment by junlincc** [comment]
@stephenLYZ 🙏

**Comment by stephenLYZ** [comment]
working on it.

**Comment by stephenLYZ** [comment]
fixed #15138

**Comment by stephenLYZ** [comment]
Closes: https://github.com/apache/superset/pull/15137

**Comment by junlincc** [comment]
Hi @stephenLYZ we will need to combine two toast messages aw well, sorry if my instruction was not clear.

**Comment by stephenLYZ** [comment]
sorry i didn't notice it should show only one toast. I will open a pr to fix it.

**Comment by stephenLYZ** [comment]
The message seems to be a backend control, can @zhaoyongjie help me take a look?
