### ISSUE TITLE
Hometabs are not sticky 

### ISSUE THREAD

**Issue by matthewphua** [apache/superset#15104]
Hometabs are not sticky. 

### Expected results
1) user choose options in different sections, for example, choose 'Edited' in recent and choose 'favorite' in dashboard
2) refresh the page
3) home page should stay on 'Edited' in recent and choose 'favorite' in dashboard

### Actual results
Does not remain on same tabs. 
Before refresh:
<img width="872" alt="image" src="https://user-images.githubusercontent.com/85198947/121605274-fb4efa80-ca00-11eb-903b-868e102ac822.png">
After refresh:
<img width="881" alt="image" src="https://user-images.githubusercontent.com/85198947/121605285-fee28180-ca00-11eb-875f-88d928ab6927.png">

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
hi @matthewphua i believe this issue only happens in Preset env. closing here. works properly in Superset master. 🙏

https://user-images.githubusercontent.com/67837651/121608048-07898680-ca06-11eb-802d-01ecbcba759d.mov
