### ISSUE TITLE
[native filter] Time range native filter is not sticky

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15102]
Time range native filter is not sticky, filter value will be reset to default when page refresh, can we make it sticky?

https://user-images.githubusercontent.com/81597121/121587994-3d207680-c9ea-11eb-9377-63f445985b26.mov

**Describe the solution you'd like**
Make time range filter sticky, so that user choice would stay when page refresh

**Describe alternatives you've considered**
Is that possible user can have a list of the time range filter that have been set before? so that if user set different time range filter before can go back and select from the history list and do not need to configure the filer every time.

**Comment by junlincc** [comment]
actually the Last week default time range has been removed. i was thinking about making all filter values sticky but it's in conflict with the filter default value select. meaning, if we set default values in a filter, user change it from the filter bar, what should be showing after refreshing the page? but i agree, not able to preserve filter values is annoying so....
