### ISSUE TITLE
[viz_plug-ins]help me!!error when npm link @superset-ui/core

### ISSUE THREAD

**Issue by bonniePxx** [apache/superset#15116]
ExploreViewContainer.jsx?2c1c:80 Uncaught TypeError: Cannot read property 'grayscale' of undefined

**Comment by junlincc** [comment]
@rusackas any ideas?

**Comment by bonniePxx** [comment]
i just clone the main project superset and superset-ui project in 2021/6/11. which is the most new version. but i face the emotion theme problem.

1. in superset-ui project. run yarn.yarn build.
2 . in superset project.   go into superset-frontend dirctory.  
     run npm install.  
     npm link ../..superset-ui/packages/superset-ui-core
     npm run devserver
3. i got the error. 
![image](https://user-images.githubusercontent.com/27723852/121767079-c2da2880-cb88-11eb-8a55-5aa0a6553f34.png)

i know it's something about emotion. but i dont know how to fix it... it cost me much time...help me
if i have miss other important info.just let me know.many thanks!

**Comment by rusackas** [comment]
Is there a particular page in Superset that's throwing this error? I'm thus far unable to replicate, but maybe I'm just looking at a different page with different components.

To retrace your steps, I did the following:
* Pull `master` on `superset-ui`
* Pull `master` on `superset`
* in `superset-ui` run `yarn` and then `yarn build`
* in `superset` cd into `superset-frontend` and run `npm link ../../superset-ui/packages/superset-ui-core`
* when it's done, run `npm run dev-server`

FWIW, I'm running the docker build of `superset` by going into that directory and doing `docker-compose up`

**Comment by bonniePxx** [comment]
> doing

thanks for your replay!  i just try the steps on others's computer and there have no bug. so i Speculate it's about the npm version. becase i run npm link in several project it my cause the Global node_moudle pollution. by the way i use npm v7+.
i don't know if the npm high version cause the problem.but when i delete the node 14 and reinstall it. i get npm 6+. and everything looks good !
