### ISSUE TITLE
[dashboard][3 dot menu] Option of 'toggle fullscreen' should be 'toggle normal screen' in fullscreen mode

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15110]
when dashboard were toggled fullscreen, the option for toggle back to normal screen should name as something like 'toggle normal screen'

### Expected results
option of toggle to normal screen in dashboard should name as something like 'toggle normal screen' in dashboard 3 dot menu

### Actual results
option of toggle to normal screen in dashboard name as 'toggle fullscreen' in dashboard 3 dot menu now

#### Screenshots
<img width="1792" alt="Screen Shot 2021-06-10 at 10 13 30 PM" src="https://user-images.githubusercontent.com/81597121/121634331-32d99900-ca39-11eb-811d-9d6db867de56.png">

#### How to reproduce the bug

1. Go to dashboard 3 dot menu, click 'toggle fullscreen'
2. After dashboard become fullscreen, click on 3 dot menu again
3. Observe the last option to toggle back to normal screen, 

### Environment

- superset version: master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!
[Y] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@zhaoyongjie just wanna make sure you are still on the Advanced analytics project and have communicated with @villebro about the scope. these tickets can be handled by @xiezhongfu and @stephenLYZ

**Comment by junlincc** [comment]
@xiezhongfu please take this ticket.

**Comment by xiezhongfu** [comment]
@jinghua-qa  I think this is something about semantics. Shall we call `Request fullscreen` and `Exit fullscreen`?

**Comment by jinghua-qa** [comment]
@xiezhongfu shall we call 'Enter fullscreen' and 'Exit fullscreen'?

**Comment by zhaoyongjie** [comment]
closed by:  https://github.com/apache/superset/pull/15139

**Comment by rambhandare** [comment]
is there any url parameter to load dashboard in enable full screen mode default
