### ISSUE TITLE
[native-filters]scoping section shows uuid when dashboard with tabs shared the same name

### ISSUE THREAD

**Issue by rosemarie-chiu** [apache/superset#15126]
when multiple tab is generated in a dashboard they share same default name and then in the native filter scoping page those tabs are shown in TAB+ID which is confusing

### Expected results
I think we should have different name for new tab ( like tab1, 2, 3) and if user has not rename it yet, in native filter scope page also show tab 1, 2, 3 rather than show the tab ID
what you expected to happen.

### Actual results
<img width="1789" alt="multi tab" src="https://user-images.githubusercontent.com/52086618/121753129-880fbc00-cac6-11eb-8487-dbf0497773e1.png">

**Comment by junlincc** [comment]
Thanks for filing! 
Changes should be made on the tab 
Expected behavior: user should not be able to create tabs with the same tab name. by clicking "+", user should see default tab name like Tab 1, Tab 2

**Comment by villebro** [comment]
Breaking out issue for automatically naming new duplicate name tabs "Tab title (1)", "Tab title (2)" into a separate ticket.
