### ISSUE TITLE
[native-filters] interacting w native filter sidebar should not change dashboard ownership

### ISSUE THREAD

**Issue by rosemarie-chiu** [apache/superset#15125]
Simply expand / retract native filter sidebar should not make you the owner of the dashboard
### Steps
1. Observe that you are not the owner of the dashboard in test
2. Open the dashboard
3. Expand and retract native filter 
4. Return to dashboard list

### Expected results
There should be no ownership change on the dashboard

### Actual results
I became the owner of the dashboard

https://user-images.githubusercontent.com/52086618/121752140-61e91c80-cac4-11eb-984f-dfb2ec1bac12.mp4

**Comment by villebro** [comment]
It appears ownership is added when the dashboard is opened, so this isn't directly related to expanding/collapsing the filter tab.

**Comment by villebro** [comment]
This happens even without the native filter feature flag being enabled, so removing the native filter tag.

**Comment by villebro** [comment]
Re-adding the label and issue to the native filter board due to the problem being related to a native filter feature PR (apologies for the label/project board flip-flop)
