### ISSUE TITLE
Superset memory leak

### ISSUE THREAD

**Issue by chen-ABC** [apache/superset#15132]
After querying the same chart for a long time, the available memory continues to decrease until the system runs out of memory

### Expected results

Recycle memory after querying the chart

### Actual results

The available memory keeps decreasing

#### Screenshots

I started a scheduler job to query chart
![image](https://user-images.githubusercontent.com/30097790/121766019-b1415280-cb81-11eb-9f05-5e0d959cac9f.png)

#### How to reproduce the bug
1.force refresh of the chart in Dashboard
2. use memory profile
![image](https://user-images.githubusercontent.com/30097790/121766100-3b89b680-cb82-11eb-82c1-0b67c15dfec2.png)
3. see log 

![image](https://user-images.githubusercontent.com/30097790/121766178-c10d6680-cb82-11eb-8b38-c6e48821cf3d.png)
After many times
![image](https://user-images.githubusercontent.com/30097790/121766271-590b5000-cb83-11eb-8e57-e95885bf30c4.png)

use gc.collect() at end line, But the memory is not reclaimed

### Environment

- superset version: `1.1.0`
- python version: `3.7.9`
- node.js version: `12.18.3`

**Comment by zhaoyongjie** [comment]
Hi @chen-ABC. I also found this problem a long time ago when using Superset in a production environment. My strategy is to restart the gunicorn process periodically. for instance:
```
gunicorn --max-requests 1024 ....
```

**Comment by chen-ABC** [comment]
@zhaoyongjie   Thanks, This is useful for HHTP requests.  but it has no effect on apscheduler  job(Internal calls)

**Comment by zhaoyongjie** [comment]
> @zhaoyongjie Thanks, This is useful for HTTP requests. but it has no effect on apscheduler job(Internal calls)

The Superset only exposes an HTTP service, so I guess that it will work either way you call it.

**Comment by chen-ABC** [comment]
> > @zhaoyongjie Thanks, This is useful for HTTP requests. but it has no effect on apscheduler job(Internal calls)
> 
> The Superset only exposes an HTTP service, so I guess that it will work either way you call it(either external job request or common HTTP request).

thanks, That's right

**Comment by chen-ABC** [comment]
@zhaoyongjie    
I think I found the cause of the memory leak.
```
 @utils.memoized(watch=("impersonate_user", "sqlalchemy_uri_decrypted", "extra"))
    def get_sqla_engine(
```
memoized use tuple key , The keys for the same query are different.
![image](https://user-images.githubusercontent.com/30097790/138015661-ff373e15-e89a-4e55-81b8-c28d3c104033.png)

 I think we have the same problem  in superset 1.3.0
example:
![image](https://user-images.githubusercontent.com/30097790/138015360-5a873831-8b46-48c8-90a3-dfd2c6004647.png)

**Comment by villebro** [comment]
Thanks for investigating this @chen-ABC ! I can try to repro and help get this fixed and released soon if this is indeed the culprit!

**Comment by jhult** [comment]
It looks like PR #17319 is still open and needs to be merged.

**Comment by zhaoyongjie** [comment]
@jhult I will follow this issue recently.

**Comment by mdeshmu** [comment]
I am also observing memory leak

![image](https://user-images.githubusercontent.com/57723564/177714758-08cfba56-ddfb-4238-9008-771abb6431e6.png)
