### ISSUE TITLE
Helm: Postgres password override is not get picked up

### ISSUE THREAD

**Issue by prashant-shahi** [apache/superset#15133]
### Expected results

Expected helm chart to work with default/updated values.

### Actual results

It throws `password authentication failed` for both default superset helm
setup as well as updated `values.yaml` where postgres password is overridden.

```
ERROR:flask_appbuilder.security.sqla.manager:DB Creation and initialization failed:
(psycopg2.OperationalError) FATAL: password authentication failed for user "superset"
```

#### How to reproduce the bug

We can reproduce the same by following the official documentation:
https://superset.apache.org/docs/installation/running-on-kubernetes

We can use the [default my-values.yaml]() or the version where postgresPassword is updated.

```
$ helm repo add superset https://apache.github.io/superset
"superset" has been added to your repositories


// updated postgresPassword from my-values.yaml file
$ helm upgrade --install --values my-values.yaml superset superset/superset
Release "superset" does not exist. Installing it now.
coalesce.go:163: warning: skipped value for extraEnv: Not a table.
NAME: superset
LAST DEPLOYED: Sat Jun 12 10:26:42 2021
NAMESPACE: superset
STATUS: deployed
REVISION: 1
TEST SUITE: None


// list pods
$ helm get pods


// show log from superset pod
$ helm log -t superset-<pod-id>
...
[2021-06-12 10:24:07 +0000] [1092] [INFO] Worker exiting (pid: 1092)
Loaded your LOCAL configuration at [/app/pythonpath/superset_config.py]
[2021-06-12 10:24:07 +0000] [1094] [INFO] Booting worker with pid: 1094
logging was configured successfully
2021-06-12 10:24:08,970:INFO:superset.utils.logging_configurator:logging was configured successfully
2021-06-12 10:24:08,976:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
2021-06-12 10:24:09,007:ERROR:flask_appbuilder.security.sqla.manager:DB Creation and initialization failed: (psycopg2.OperationalError) FATAL:  password authentication failed for user "superset"
...
```

### Environment

- superset version: `superset-helm-chart-0.1.4` (latest docker tag)

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by aboutphilippe** [comment]
Just ran into similar issue due to the supersetNode.connections.db_pass still set to "superset" even if using postgresql.postgresqlPassword

A workaround is to password the same password you set in postgresql.postgresqlPassword to supersetNode.connections.db_pass

I've made a PR to use by default the postgresql values.
This should still allow custom connections to an external postgres but not have to add duplicate values if using postgres within the same chart.

**Comment by vikiscience** [comment]
@prashant-shahi Have you tried installing Superset in its own K8S namespace? It solved the issue for me, so that at least the default DB password works as expected...

**Comment by abhishek-ch** [comment]
I am not able to override affinity or tolerations by using master.affinity/tolerations

**Comment by mayurnewase** [comment]
any update here, I am also facing same issue.

**Comment by prashant-shahi** [comment]
It worked after setting both `postgresql.postgresqlPassword` and `supersetNode.connections.db_pass`.

```
helm upgrade --install superset superset/superset --set postgresql.postgresqlPassword=my-password --set supersetNode.connections.db_pass=my-password
```
