### ISSUE TITLE
How to hide a specific legend in chart

### ISSUE THREAD

**Issue by guoguoguilai** [apache/superset#15136]
## Screenshot

![image](https://user-images.githubusercontent.com/47267017/121794140-967de500-cc38-11eb-8526-62671cc8c03c.png)

## Description

Just as the image shown above, I want to get the percentage of Andrea in the sum of Andrea and Andrew without showing Andrew in chart. Is it possiable?

**Comment by suddjian** [comment]
I don't think this is currently possible, but if you or anyone else wants to try implementing it in https://github.com/apache-superset/superset-ui/ and open a PR, I'll give it a review

**Comment by Shazad-khan** [comment]
![image](https://user-images.githubusercontent.com/100838455/225286728-b7316f3b-420c-4b39-aeb1-954002f90a68.png)

This issue has been fixed in the recent update

**Comment by rusackas** [comment]
Looks like this should've been closed a long time ago!
