### ISSUE TITLE
[dashboard][edit]change name of dashboard is not reflected instantly

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15130]
change name of dashboard is not reflected instantly, user need refresh page to see name change, can we make the change instantly

**Comment by junlincc** [comment]
https://user-images.githubusercontent.com/67837651/121760576-573c8080-cae0-11eb-9e53-b4cf1cd572fc.mov
let's also place the cursor at the end of the text instead for easier delete.

**Comment by junlincc** [comment]
@stephenLYZ 🙏

**Comment by stephenLYZ** [comment]
@junlincc I think it can be forced to refresh after changing the name of dashboard.

**Comment by zhaoyongjie** [comment]
closed by https://github.com/apache/superset/pull/15186#event-4998136264
