### ISSUE TITLE
Adding custom viz plugin bug 

### ISSUE THREAD

**Issue by beltramem** [apache/superset#15148]
I add trubles to install a custom viz plugin. I followed the documentation here : https://superset.apache.org/docs/installation/building-custom-viz-plugins

every steps are looking good and I encounter no error by runing `npm run dev-server`

but when I try to connect on superset every pages are blank and i got an error on JS log.

### Actual results

Uncaught SyntaxError: Unexpected token '!'
    at Object../src/visualizations/presets/MainPreset.js (65.601d1ea3.chunk.js:6478)
    at __webpack_require__ (crudViews.601d1ea3.entry.js:85)
    at Module.eval (setupPlugins.ts?0860:1)
    at eval (setupPlugins.ts:39)
    at Module../src/setup/setupPlugins.ts (65.601d1ea3.chunk.js:6346)
    at __webpack_require__ (crudViews.601d1ea3.entry.js:85)
    at Module.eval (App.tsx?9011:1)
    at eval (App.tsx:183)
    at Module../src/views/App.tsx (crudViews.601d1ea3.entry.js:2711)
    at __webpack_require__ (crudViews.601d1ea3.entry.js:85)

#### Screenshots

![image](https://user-images.githubusercontent.com/32321438/121888566-732a6700-cd18-11eb-9c83-bd97c9ee1ac6.png)

### Environment

(please complete the following information):

- superset version: `superset 1.0.1`
- python version: `Python 3.8.5`
- node.js version: `v14.16.1`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by suddjian** [comment]
Can you share the source code of `MainPreset.js`? It looks like something is wrong in that file.

**Comment by beltramem** [comment]
I found the issue thank

**Comment by guipalazzo** [comment]
Hello @beltramem , I've got the same error here. Could you please share the solution with us?

**Comment by pavankanth1985** [comment]
I'm facing the same error. Can you share how did you resolve it.

**Comment by maverick-netizen** [comment]
I was able to resolve this. In case anyone is interested, I was having this issue running on mac.  I had to edit webpack.config.js. to change the port from 9000 to 9001 and run npm run dev-server. The reason is mac has predefined apps running on port 9000.

Hope it helps.
