### ISSUE TITLE
[Pivot v2]Combine Metrics

### ISSUE THREAD

**Issue by kamalkeshavani-aiinside** [apache/superset#15159]
**Is your feature request related to a problem? Please describe.**
In the previous version of Pivot chart, we had a great feature of 'Combine Metrics', which is not available in new Pivot Table v2.

**Describe the solution you'd like**
Please add the 'Combine Metrics' feature in Pivot Table v2 as well.

**Describe alternatives you've considered**

**Additional context**
Pivot Table
![image](https://user-images.githubusercontent.com/74634977/121981435-9c0a3500-cdc8-11eb-9fa0-b4179257b610.png)

Pivot Table v2
![image](https://user-images.githubusercontent.com/74634977/121981504-bb08c700-cdc8-11eb-9476-a6977f7f6638.png)

**Comment by kgabryje** [comment]
Done by https://github.com/apache-superset/superset-ui/pull/1217
