### ISSUE TITLE
[Dashboard] Add more features for Dashboard Design

### ISSUE THREAD

**Issue by kamalkeshavani-aiinside** [apache/superset#15161]
**Is your feature request related to a problem? Please describe.**
I feel like we still miss a lot of features in terms of designing the dashboard. I would like to start a discussion in the community(if not existing already) about in what ways users would like to be able to edit/design their Superset dashboard.

**Describe the solution you'd like**
Some of the features I would like to see:
- Add border to dashboard components like charts,markdown,row,column, etc.; along with control of border width,type, color
- Control the chart header font style, size, color
- Have more granular control of horizontal size of chart. Not sure what happened about https://github.com/apache/superset/issues/4014
- Add custom background color, pattern, image for the dashboard

**Additional context**
I could not find any similar issue already open, so created this. Let me know if any such request is already open, I can add my requests there.
Also not sure if this should be SIP or not.

**Comment by amitmiran137** [comment]
You can start a discussion on github
