### ISSUE TITLE
Your dashboard is too large. Please reduce the size before save it.

### ISSUE THREAD

**Issue by ramesh2744** [apache/superset#15169]
### Expected results

Dashboard should allow to add the new charts and resizing the charts after clicking save button.

### Actual results:
I have an existing dashboard created and contains some charts. Now, I'm trying to add the new charts to it.
Dashboard is not allowing me to save after adding the new charts. Instead, it shows a pop up as shown in below screenshot.

#### Screenshots

![image](https://user-images.githubusercontent.com/59677029/122011620-eb0c9600-cdd9-11eb-818e-dfd76b4a8fc9.png)

### Environment

- superset version: `1.0.1`
- python version: `python 3.7`
- OS: Ubuntu 16.04

### Checklist

- [ ] I have checked the superset logs for python stack traces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by ramesh2744** [comment]
I got confusion in adding  for this one as bug or improvement. For now, I Kept as bug. Please change it accordingly as needed.

**Comment by yousoph** [comment]
Hi @ramesh2744 , have you run into this issue recently? If so, can you give a bit more info about your dashboard? How many charts, tabs, types of charts, etc 
Thanks!

**Comment by yousoph** [comment]
Closing as we've been unable to repro. Please reopen with more details if you're still able to reproduce this issue, thanks!

**Comment by kaspergaj** [comment]
I still experience the issue with the latest Superst 1.3.2.

We're making dashboards where clients can only view and apply filters (not create their own charts). Therefore the dashboards have to be extensive to support any desired visualisation.

One of the impacted dashboards have 5 main tabs, about 75 charts, and 10 filterboxes. It's mainly bar charts in this one, but other impacted dashboards have time-series charts.

**Comment by Kingflyinger** [comment]
> I still experience the issue with the latest Superst 1.3.2.
> 
> We're making dashboards where clients can only view and apply filters (not create their own charts). Therefore the dashboards have to be extensive to support any desired visualisation.
> 
> One of the impacted dashboards have 5 main tabs, about 75 charts, and 10 filterboxes. It's mainly bar charts in this one, but other impacted dashboards have time-series charts.

this issue has been closed,if you need help please open a new issue

**Comment by Kingflyinger** [comment]
> I still experience the issue with the latest Superst 1.3.2.
> 
> We're making dashboards where clients can only view and apply filters (not create their own charts). Therefore the dashboards have to be extensive to support any desired visualisation.
> 
> One of the impacted dashboards have 5 main tabs, about 75 charts, and 10 filterboxes. It's mainly bar charts in this one, but other impacted dashboards have time-series charts.

I searched the code,and found edit the config.py can solve it.
![1642055089495_466A4241-3C35-47e5-A82F-B6D6F4602773](https://user-images.githubusercontent.com/41682019/149277483-7712b0ab-461f-453c-b5c5-816c6e58188f.png)

SUPERSET_DASHBOARD_POSITION_DATA_LIMIT = 85195

**Comment by Kingflyinger** [comment]
> @Kingflyinger FYI, you can modify that parameter in your `superset_config.py`. The default value is set based on the maximum size of the `TEXT` column type in an old MySQL version: https://stackoverflow.com/questions/6766781/maximum-length-for-mysql-type-text#:~:text=TEXT%20is%20a%20string%20data,maximum%20length%20of%204%2C294%2C967%2C295%20characters. For Postgres or a newer version of MySQL I believe this is around 1Gb, so you can safely add a few zeros to the current default value which is 65535.

thank you for your information, I searched DB storage and found nothing. happy to know I can just add  zeros

**Comment by Hu-WF** [comment]
nice

**Comment by himanshudube97** [comment]
@Kingflyinger hey, so i added the configuration but it was not working. If you look closely we have two values for SUPERSET_DASHBOARD_POSITION_DATA_LIMIT. one is the default value and other is the one that i added to superset_config.py file. But as per the code snippet its taking the default value only. That's why Its not working for me. 

<img width="1396" height="788" alt="Image" src="https://github.com/user-attachments/assets/cdf502b2-4c35-4229-ab69-fbc8fd600888" />

**Comment by rusackas** [comment]
Wait are people still using 1.0.1?! If there are any issues in the modern era, please open a new Issue thread. Locking this ancient one for now.
