### ISSUE TITLE
[Bar Chart] Rich tooltip does not work

### ISSUE THREAD

**Issue by kamalkeshavani-aiinside** [apache/superset#15162]
The option of 'Rich Tooltip' does not work with Stacked Bar Chart.

### Expected results

Expected to show Rich Tooltip like shows in Line/Area chart
![image](https://user-images.githubusercontent.com/74634977/121988422-396b6600-cdd5-11eb-87d9-67e6f5661e45.png)

### Actual results

Shows only one value at a time when enabled for Bar Chart with "Stacked Bars" option.
![image](https://user-images.githubusercontent.com/74634977/121988503-6750aa80-cdd5-11eb-8f65-8604b82dcc46.png)

#### How to reproduce the bug

1. Create a stacked bar chart
2. Enable Rich Tooltip from options and check tooltip

### Environment

- superset version: `v1.1.0` and `master`
- python version: `3.7`
- node.js version: `14.15.5`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closed by https://github.com/apache/superset/pull/17615
