### ISSUE TITLE
Compute and cache a screenshot using apache superset rest api

### ISSUE THREAD

**Issue by pritypriya25** [apache/superset#15164]
I am trying to hit the get api  /chart​/{pk}​/cache_screenshot​/  on my localhost. But the error 404 message : "Not found" is been showing. I am able to run other APIs like chart/{pk} and get /dashboard/. But some APIs are showing the same error. Can someone tell me what I am doing wrong over here. I am attaching the ss of my postman.
![screenshot](https://user-images.githubusercontent.com/85749375/121990499-85a9ac80-cdbb-11eb-8b77-978abd1acc7e.png)

**Comment by Hvitgar** [comment]
see https://github.com/apache/superset/issues/15118#issuecomment-910199827

**Comment by rusackas** [comment]
Seems this was answered (on the linked thread) quite some time ago. Thanks for that @Hvitgar, and I'm hopeful that someone can move this into the docs so others don't run into the same issue :D
