### ISSUE TITLE
Creating users in Bulk, role based data restrictions through API, apache superset version 1.1.0

### ISSUE THREAD

**Issue by ghost** [apache/superset#15170]
**Is your feature request related to a problem? Please describe.**
I have to create users for apache superset==1.1.0 , manually creating users via console is tedious problem. I am looking for API to create users and assign roles using APIs.
OR something like this https://github.com/apache/superset/issues/3083
OR If there is even a better solution please let me know.

**Describe the solution you'd like**
I have to create users for apache superset==1.1.0 , manually creating users via console is tedious problem. I am looking for API to create users and assign roles using APIs.
OR something like this https://github.com/apache/superset/issues/3083
OR If there is even a better solution please let me know.

**Describe alternatives you've considered**
For now I am creating users using Superset console.

**Additional context**
NA

**Comment by rusackas** [comment]
We no longer officially support 1.x (we're currently on 3.x), and we're moving feature requests to Github Discussions, so I'll close this. Please open a discussion over there if this is still needed.
