### ISSUE TITLE
Dynamic plugin not showing up in VizTypeControl

### ISSUE THREAD

**Issue by krsnik93** [apache/superset#15174]
I am trying to load a plugin via url. 

### Expected results

Expect plugin to appear in the list of viz types.

### Actual results

Plugin is not showing up in viz type list. I can see that a request is made to `https://mysupersethost/dynamic-plugins/api/read` and response contains:
```
{
  "count": 1, 
  "label_columns": {
    "bundle_url": "Bundle URL", 
    "changed_by": "Changed By", 
    "changed_by_fk": "Changed By Fk", 
    "changed_on": "Changed On", 
    "created_by": "Created By", 
    "created_by_fk": "Created By Fk", 
    "created_on": "Created On", 
    "id": "Id", 
    "key": "Key", 
    "name": "Name"
  }, 
  "list_columns": [
    "name", 
    "key", 
    "bundle_url", 
    "id"
  ], 
  "modelview_name": "DynamicPluginsView", 
  "order_columns": [
    "name", 
    "key", 
    "bundle_url", 
    "id"
  ], 
  "page": null, 
  "page_size": null, 
  "pks": [
    15
  ], 
  "result": [
    {
      "bundle_url": "url_from_which_plugin_is_served", 
      "id": 15, 
      "key": "superset-indicator-chart", 
      "name": "Indicator Chart"
    }
  ]
}

```
However, the plugin chart does not appear in the modal. I believe this could be a recent regression because I remember being able to use this feature.

#### How to reproduce the bug

1. Write your own plugin using https://github.com/apache-superset/dynamic-import-demo-plugin as template
2. Run `npm install` and `npm run build`, then `npm run serve` to serve `dist` dir
3. Expose port via HTTP server
4. Enable feature flag on Superset host, run `superset init`
5. Go to 'Settings -> Plugins' and create a plugin entry containing plugin url 
6. Go to 'Chart -> Create New' and verify that your plugin does not appear in the list of viz types

### Environment

(please complete the following information):

- superset version: latest master as of now, latest commit 57035c1b93331b925e9bf91f757f365807ca70ab
- python version: 3.8.7
- node.js version: v14.16.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I have verified that the plugin is working when imported directly in source and linked as here: https://superset.apache.org/docs/installation/building-custom-viz-plugins. 

I also debugged and stepped over the piece of code importing the plugin (https://github.com/apache/superset/blob/9773aba522e957ed9423045ca153219638a85d2f/superset-frontend/src/components/DynamicPlugins/index.tsx#L150) and made sure there is no error upon importing.

I have also made sure that the name of the plugin in the package.json is the same as the one in Superset.

**Comment by krsnik93** [comment]
I have debugged this further and the piece of code selecting charts that will be displayed in the modal:
https://github.com/apache/superset/blob/e466066229ec8262583bc118af1f39e2dbf77bcf/superset-frontend/src/explore/components/controls/VizTypeControl/index.jsx#L167-L190
is executed before the
``` MyPlugin().configure({ key: 'my_plugin' }).register()```

So the plugin gets registered into `ChartMetadataRegistry` **after** the registry is used to list viz types in `VizTypeControl`.

I would really appreciate if someone could take a look into this.

**Comment by suddjian** [comment]
Thank you so much for your debugging efforts @krsnik93! I think I understand the problem before even needing to repro 😁  I am actively working on this file so I should be able to address the problem quite soon.

**Comment by krsnik93** [comment]
Hi @suddjian I tried testing the changes and the plugin is still not showing up in the modal. I think the listener in:
https://github.com/apache/superset/blob/b489cffb570c4d078ec982fd11c3e46dd0310f24/superset-frontend/src/components/DynamicPlugins/index.tsx#L215-L220
might not be working as the action is not dispatched after the plugin is registered into the `metadataRegistry`.

**Comment by suddjian** [comment]
Just to make sure, did you run `npm install`?

**Comment by krsnik93** [comment]
yup...

**Comment by krsnik93** [comment]
@suddjian hello, any updates on this issue?

**Comment by elyzov** [comment]
@suddjian I have the same issue on latest superset version - dynamic plugins are successfully loaded (without any errors in log), its but not listed.
