### ISSUE TITLE
[explore][time-series] marker option is not work when rich tooltip option is unselected.

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15189]
### Description
In time series chart, marker option is not work when rich tooltip option is unselected.
### Screenshot or Video
https://user-images.githubusercontent.com/81597121/122186275-bd0f6c00-ce42-11eb-8886-448806d93993.mov

### Repro steps
1, create time series chart using random_time_series data
    Select "random_time_series" dataset
    Select "Time Series Chart" as your chart type
    In Time, select Time Column "ds" and Time Grain "week"
    Select "No Filter" in Time Range
    Select count as metrics
    run query
2, go to CUSTOMIZE panel and select/unselect 'MARKER'
3, Unselect 'Rich tooltip' and try select/unselect 'MARKER'

### Expected results
'MARKER' option should work

### Actual results
'MARKER' option only work when 'Rich tooltip' is selected

### Environment

(please complete the following information):

- superset version: master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by stephenLYZ** [comment]
working on it.

**Comment by stephenLYZ** [comment]
fixed https://github.com/apache-superset/superset-ui/pull/1187. @jinghua-qa cc

**Comment by jinghua-qa** [comment]
Verified fixed
