### ISSUE TITLE
[annotation] click on the edit button two times, the current preferences of the annotation layer disappear.

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15205]
click on the edit button two times, the current preferences of the annotation layer disappear.

#### Screenshots

https://user-images.githubusercontent.com/81597121/122306246-f258a000-cebc-11eb-8245-71e002109f7e.mov

#### How to reproduce the bug
Precondition:
User have annotation created already

1. Go to annotation and click pencil icon on the right to edit annotation
2. go out without changing and enter annotation edit modal again
3. observe error

### Expected results

Will be able to edit annotation and update current annotation preferences.

### Actual results

click on edit two times the current preferences of the annotation layer disappear.

### Environment

(please complete the following information):

- superset version: master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by stephenLYZ** [comment]
working on it

**Comment by stephenLYZ** [comment]
closes: https://github.com/apache/superset/pull/15359

**Comment by michael-s-molina** [comment]
Fixed in https://github.com/apache/superset/pull/15359
