### ISSUE TITLE
 [chart-viz][time-series bar chart] SORT DESCENDING did not take effect when selected

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15212]
SORT DESCENDING did not take effect when selected

### Expected results

When 'SORT DESCENDING' is selected , expect SQL query and Data will sort in descending order

### Actual results

When 'SORT DESCENDING', did not see DES in expect SQL query and Data is not sorted in descending order

#### Screenshots
<img width="1779" alt="Screen Shot 2021-06-11 at 2 21 33 PM" src="https://user-images.githubusercontent.com/81597121/122332686-b38e0e80-ceeb-11eb-85c6-98ef2836449e.png">
<img width="1785" alt="Screen Shot 2021-06-11 at 2 23 51 PM (1)" src="https://user-images.githubusercontent.com/81597121/122332692-b688ff00-ceeb-11eb-9e21-a5f650600b95.png">

#### How to reproduce the bug

1. Open time-series-bar chart
2. Click on 'SORT DESCENDING'
3. Select 'View query' and observe data

### Environment

- superset version: master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
I believe you need to populate the metric that you wish to sort by in the "Sort by" control for "Descending" to take effect. See here:

![image](https://user-images.githubusercontent.com/33317356/122342072-d69cda80-cf4c-11eb-925c-fd7e568d9531.png)

**Comment by jinghua-qa** [comment]
@villebro so should we disable the SORT option if SORT By is not configured?

**Comment by villebro** [comment]
@jinghua-qa that's probably a good idea 👍 I'll do that unless there is a reason why it should be active.
