### ISSUE TITLE
[native-filters] hide non-numeric columns in numeric range filter

### ISSUE THREAD

**Issue by villebro** [apache/superset#15226]
Currently the numeric range filter supports selecting a non-numeric column, which isn't supported by the filter. It would be preferable to only list compatible columns so the user can more easily find the relevant columns and avoid unnecessary errors.

## Screenshot

![image](https://user-images.githubusercontent.com/33317356/122391401-a3257480-cf7b-11eb-9170-7acf855b9c1a.png)

**Comment by kgabryje** [comment]
Should we disable this type of filter if there are no numeric columns in the dataset? Similar to https://github.com/apache/superset/issues/15068

**Comment by kgabryje** [comment]
@villebro This feature requires changes in the response from `/dataset/{id}` endpoint, as it doesn't return `type_generic` field for columns 
![image](https://user-images.githubusercontent.com/15073128/123081673-7f9c7700-d41e-11eb-9a23-dde9b9dc1d53.png)
