### ISSUE TITLE
Data results appear as 'undefined'

### ISSUE THREAD

**Issue by helo-ch** [apache/superset#15227]
Data results below visualisation appear as 'undefined' when field name contains a dot.

### Expected results

When there is no dot in field name, data results below visualisation contain values from dataset, as is expected.

<img width="838" alt="superset_ok" src="https://user-images.githubusercontent.com/28846165/122392577-46728b80-cf74-11eb-8721-051e508489ed.PNG">

### Actual results

However, when field name contains a dot (`field.name` for example), values from this field appear as `undefined` in data results. 
Note that it seems to be the case only in data results shown below visualisation, the request in SQL Lab or the actual visualisation are not affected and return the expected values.

<img width="834" alt="superset_undefined" src="https://user-images.githubusercontent.com/28846165/122392625-52f6e400-cf74-11eb-9a6a-55d181b5172d.PNG">

#### How to reproduce the bug

1. Create a dataset with a `.` in one field name, on TimeScale DB
2. Create any chart using that field
3. Look at Data Results below chart

### Environment

(please complete the following information):

- superset version: `1.0.1`

**Comment by suddjian** [comment]
Does this happen on other DB engines, or just TimeScale?

**Comment by junlincc** [comment]
https://github.com/apache/superset/pull/15817 
resolved by ^ thanks @zhaoyongjie closing issue
