### ISSUE TITLE
Cards link to a 404 page while loading

### ISSUE THREAD

**Issue by suddjian** [apache/superset#15239]
While loading, cards link to an undefined page causing a 404.

### Expected results

There should not be an active link while the cards are in a loading state

### Actual results

The cards attempt to link to their relevant resource, but instead link to e.g. `/chart/list/undefined`. If you click a card while it's loading you get a 404 page.

#### How to reproduce the bug

1. Go to the chart list view in card mode
2. Refresh the page
3. While the results are not yet loaded, click on a card
4. See 404 page

### Environment

(please complete the following information):

- superset version: 1.1.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by xiezhongfu** [comment]
working on it.

**Comment by zhaoyongjie** [comment]
closed by https://github.com/apache/superset/pull/15526
