### ISSUE TITLE
Chart does not cover the entire page with Standalone=1

### ISSUE THREAD

**Issue by nraschi** [apache/superset#15252]
When Standalone=1 (or standalone=true) is passed in query string the chart does not fit the full page like used to do in the previous version.

### Expected results (Superset v. 0.37.2)
In this case the chart area is 1920 x 937 and fit the entire page:

![image](https://user-images.githubusercontent.com/26787281/122533448-dd495180-d021-11eb-823a-6b8367a202b0.png)

### Actual results (Superset v. 1.1.0)
In this case the chart area is 1890 x 806 and does not fit the entire page:

![image](https://user-images.githubusercontent.com/26787281/122533886-4d57d780-d022-11eb-96f3-62e0dc170430.png)

#### Screenshots
In line with comments

#### How to reproduce the bug

1. Create and save a chart
2. Generate a link to view/share the chart
3. Get the chart id and point to standalone version: https://superset_v_1_1_0/superset/explore/?r=100&standalone=1
4. See that the chart will not fit the entire page

### Environment
- superset version: Superset 1.1.0
- python version: Python 3.8.9
- node.js version: -

### Checklist
- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
--

**Comment by nraschi** [comment]
Hi, is there any chance that this issue will be addressed shortly?

**Comment by nraschi** [comment]
Hi @suddjian, could you point us where this problem could be? 
We can check and eventually create a merge request if we solve it...

Thank you

**Comment by suddjian** [comment]
Hi @nraschi, I would start by looking here: https://github.com/apache/superset/blob/master/superset-frontend/src/explore/components/ExploreChartPanel.jsx#L161

If you open a PR, ping me and I will be happy to review.

**Comment by nraschi** [comment]
Hi @suddjian, thank you very much! I let you know.

**Comment by nraschi** [comment]
Hi @suddjian, can you pin this issue please, I'm trying to resolve "pull request" problems.

Thank you very much

**Comment by rusackas** [comment]
Just checked this on the current version, and it no longer seems to be an issue.
