### ISSUE TITLE
row level security rule not working in sql lab

### ISSUE THREAD

**Issue by layasail** [apache/superset#15251]
When I set up the row level security rule for one user role, the user attached to the role use the sql lab but tried anyway can't get result in any sql even no conflicts with the row security rule

### Expected results
sql lab should also works well under row security rule

### Actual results

no result anyway I tried

#### How to reproduce the bug

1. Go to 'row level security to set a rule to one role'
2. Click on 'sql lab and input a sql without conflicts'
3. Scroll down to 'run'
4. offline with no result

### Environment

(please complete the following information):

- superset version: `0.999dev`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [V] I have reproduced the issue with at least the latest released version of superset.
- [V] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mayurnewase** [comment]
Hey @layasail can you provide more info (equivalent dummy) type of filter, query, table, role?
I tried in latest master and  it works as expected.

**Comment by layasail** [comment]
Hi, thanks for reply.
Here is the setting:
1.superset version: Version: 0.999.0dev,  this is the latest version in docker shows
![image](https://user-images.githubusercontent.com/84129749/123392891-23795480-d5d0-11eb-9fff-9ea009b695a5.png)

2.filter in row level security:`name=Aaron` to the role "sqllab test"
![image](https://user-images.githubusercontent.com/84129749/123393017-4572d700-d5d0-11eb-9182-1d1468ae06e9.png)


3.role:copy from "sqllab" role name as "sqllab test", added the dataset/datasource/table access to table:birth_name
user assigned to this role
4.query sample as below:
expected result: shows only the name=Aaron record
result still contain Aaron
![image](https://user-images.githubusercontent.com/84129749/123393406-a6021400-d5d0-11eb-95fb-f967c4ba170c.png)

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
