### ISSUE TITLE
[chart] Pivot table V2 not rendering boolean fields

### ISSUE THREAD

**Issue by rusackas** [apache/superset#15269]
Opening this ticket to address an issue brought up in this PR: https://github.com/apache/superset/issues/14716

*********** 
Hi, the pivot table is now displaying the label rather than the field name as expected, but I'm still seeing issues rendering the boolean field... it's still blank

![image](https://user-images.githubusercontent.com/31777200/121059175-28947200-c78f-11eb-99d3-dc160c1ab361.png)

_Originally posted by @jamesrayoub in https://github.com/apache/superset/issues/14716#issuecomment-856100472_

**Comment by rosemarie-chiu** [comment]
🏷 bash!

**Comment by kgabryje** [comment]
fixed
