### ISSUE TITLE
[dashboard][edit] Sort chart menu is cut on dashboard edit panel

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15268]
## Screenshot
<img width="1790" alt="Screen Shot 2021-06-18 at 11 36 58 AM" src="https://user-images.githubusercontent.com/81597121/122604382-b93e3e00-d02a-11eb-9a3b-8902eab35e96.png">

##  Enviroment
Superset master

**Comment by stephenLYZ** [comment]
same to https://github.com/apache/superset/issues/14799

**Comment by jinghua-qa** [comment]
Close as it is duplicated
