### ISSUE TITLE
/api/v1/dataset/import/ has no effect

### ISSUE THREAD

**Issue by mmatela** [apache/superset#15263]
I'm trying to import a CSV file as a dataset following the instructions here: https://stackoverflow.com/questions/66015739/use-apache-superset-api-to-feed-a-dataset
At first id failed with a very generic error message, but after some investigation I realized that the `meatada.yaml` file should be inside the datasets folder instead of the root of the zip.
Now the request is accepted, but the 200 OK response comes back immediately (certainly not enough time to download the SCV file) and no dataset is created in Superset.

Sample file: [channels1.zip](https://github.com/apache/superset/files/6678278/channels1.zip) (it's a file from the examples folder, with `dabase_uuid` taken from my Superset's `dbs` table)

	curl -X 'POST' \
	  'http://127.0.0.1:8088/api/v1/dataset/import/' \
	  -H 'accept: application/json' \
	  -H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MjQwMzMzMzMsIm5iZiI6MTYyNDAzMzMzMywianRpIjoiZWJkZjAxZjItNzNiYy00YmQ2LTk5MjUtYzdlNWVjMjFiNjU3IiwiZXhwIjoxNjI0MDM0MjMzLCJpZGVudGl0eSI6MiwiZnJlc2giOnRydWUsInR5cGUiOiJhY2Nlc3MifQ.W6QkmZWxEMH15aDMNqwhuXPqd10l1r9xQR2XdhlK-ls' \
	  -H 'Content-Type: multipart/form-data' \
	  -F 'formData=@channels1.zip;type=application/x-zip-compressed' \
	  -F 'overwrite=true'

Response body:

	{
	  "message": "OK"
	}

Nothing shows up in logs except for the standard access-log line.

This is a test instance started using docker-compose, with the master branch cloned two days ago.

**Comment by mmatela** [comment]
It may be because I missed the first step from the instruction - adding the VERSIONED_EXPORT flag (if so, the system could inform about it).
But how can I do this with a docker instance? When I try to add this

    FEATURE_FLAGS: Dict[str, Any] = {
        "VERSIONED_EXPORT": True,
    }

in `superset/docker/pythonpath_dev/superset_config.py` or `superset_config_dokcer.py`, Superset doesn't start, because of errors:
`NameError: name 'Dict' is not defined`

**Comment by mmatela** [comment]
OK, I found there's already `FEATURE_FLAGS` definition in `superset/docker/pythonpath_dev/superset_config.py`, so I added `"VERSIONED_EXPORT": True` there and it started. Nothing changed in the behavior though.

**Comment by pedrohdemedeiros** [comment]
Hi! I am currently having the same problem, did you get any improvement on it?

Best Regards

**Comment by rusackas** [comment]
@mmatela this issue seems to have gone cold for quite a while. Are you still facing this problem in newer versions of Superset, or can we call this case closed?

**Comment by mmatela** [comment]
I'm not working with Superset currenlty, so I can't confirm if the problem still persists.
