### ISSUE TITLE
Pivot table V2 not formating timestamp

### ISSUE THREAD

**Issue by squalou** [apache/superset#15277]
In Pivot Table v1, TIMESTAMP columns are nicely displayed as dates.
In v2 : the `long` value is displayed as-is.

### Expected results

Having timestamp displayed as human readable dates.

### Actual results

`long` numerical value is displayed

#### Screenshots

The `created_at` value in this example is a timestamp.

Pivot V1 :

![image](https://user-images.githubusercontent.com/4623644/122742794-9c9e4200-d286-11eb-92db-be97964c5f79.png)

Pivot V2 :

![image](https://user-images.githubusercontent.com/4623644/122742585-6365d200-d286-11eb-964c-0c00a71813b9.png)

### Environment

(please complete the following information):

- superset version:  `Superset 1.2.0`  (note : its the RC2)
- python version: `Python 3.7.9`
- node.js version: `not present inside container`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by kgabryje** [comment]
Done by https://github.com/apache-superset/superset-ui/pull/1217
