### ISSUE TITLE
Getting incompatible package errors while installing Superset from scratch

### ISSUE THREAD

**Issue by sedat-eyuboglu** [apache/superset#15275]
When i tried to install Superset according to the steps at https://superset.apache.org/docs/installation/installing-superset-from-scratch, i get following errors and installation can not success.

ERROR: flask 1.1.4 has requirement itsdangerous<2.0,>=0.24, but you'll have itsdangerous 2.0.1 which is incompatible.
ERROR: flask-appbuilder 3.3.1 has requirement Flask-WTF<0.15.0,>=0.14.2, but you'll have flask-wtf 0.15.1 which is incompatible.
ERROR: flask-appbuilder 3.3.1 has requirement SQLAlchemy<1.4.0, but you'll have sqlalchemy 1.4.18 which is incompatible.

I used the Ubuntu 20.04 in a Virtual Box environment. I think Ubuntu already have some packages with incompatible version.
I created pythone virtual environment as described but it can not solve this issue. 

#### How to reproduce the bug

1. Install Ubuntu 20.04 from https://ubuntu.com/download/server into a Virtual Box environment.
2. Flow the instaructions https://superset.apache.org/docs/installation/installing-superset-from-scratch

**Comment by sedat-eyuboglu** [comment]
I also tried installing on Debian 10, and get the same errors.
After spending one day, the only installation i could do is docker compose. And it has limitations to connect databases out side of the docker-compose environment.

How can i install Superset and make it connect to my already installed mssql and apache druid instances on other servers in my loacal network? any idea?

**Comment by ghrom** [comment]
I was able to replicate the issues reported by @sedat-eyuboglu exactly. Superset installation as per official documentation https://superset.apache.org/docs/installation/installing-superset-using-docker-compose is broken.

**Comment by ghrom** [comment]
After upgrading to pip apache-superset 1.2.0 it worked again!

**Comment by jots** [comment]
> After upgrading to pip apache-superset 1.2.0 it worked again!

How do you do that?

**Comment by jots** [comment]
I installed like `pip install apache-superset==1.2.0`
and still get the error:
```
ERROR: flask 1.1.4 has requirement itsdangerous<2.0,>=0.24, but you'll have itsdangerous 2.0.1 which is incompatible.
ERROR: flask-appbuilder 3.3.1 has requirement Flask-WTF<0.15.0,>=0.14.2, but you'll have flask-wtf 0.15.1 which is incompatible.
```

also getting errors like:
`error: invalid command 'bdist_wheel'`
on install

**Comment by fuomag9** [comment]
Same issue here, installation guidelines are incorrect and I did not manage to fix this

**Comment by barryrowlingson** [comment]
Installing these versions of Flask-WTF and itsdangerous got me past this error:

```
python -m pip install apache-superset==1.2.0
python -m pip install Flask-WTF==0.14.3
python -m pip install itsdangerous==1.1.0
```

but only got me to more errors when trying to run `superset load_examples`. Oh well.

**Comment by rusackas** [comment]
I think at this point, this thread is too stale to be relevant/useful in current Superset. If folks are still facing this issue in 2.0.1 we should open a new Issue with updated context, and link this one to it for historical reference. Thanks!
