### ISSUE TITLE
Superset configuration on a production version of superset in docker

### ISSUE THREAD

**Issue by adhip94** [apache/superset#15286]
### Expected results
The ability to add a superset configuration on a production version of superset running on docker.

### Actual results
Unable to configure a superset configuration on docker.

### Environment

- superset version: `1.1.0`
- python version: `3.8.5`
- node.js version: `10.19.0`

### Additional context
I am new to superset, I have followed the steps from [here](https://superset.apache.org/docs/installation/installing-superset-using-docker-compose) and I am successfully running a non-dev version of superset on docker. Now I wanted to enable a configuration `ENABLE_TEMPLATE_PROCESSING` which is set to `False` by default. How do I do this? I have read this [section](https://superset.apache.org/docs/installation/configuring-superset) but it only says _you need to create a file superset_config.py and add it to your `PYTHONPATH`_. I am not a python dev so I do not know how to do this and how this works with the docker container. Anyone can help?

**Comment by nytai** [comment]
You can volume mount a superset config into the container

**Comment by adhip94** [comment]
@nytai  Could you please give me an example of it?

**Comment by squalou** [comment]
Hi,
I have a similar setup, here's what I did

Dockerfile :

```Dockerfile
FROM .......superset parent image you want

ADD superset_config.py  /app/pythonpath/

```

and the file `superset_config.py` itself contains your configuration



```python
FEATURE_FLAGS = {
    "ENABLE_TEMPLATE_PROCESSING": True
}

```

less flexible than a mounted volume but works in a serverless environment.

**Comment by adhip94** [comment]
> Hi,
> I have a similar setup, here's what I did
> 
> Dockerfile :
> 
> ```dockerfile
> FROM .......superset parent image you want
> 
> ADD superset_config.py  /app/pythonpath/
> ```
> 
> and the file `superset_config.py` itself contains your configuration
> 
> ```python
> FEATURE_FLAGS = {
>     "ENABLE_TEMPLATE_PROCESSING": True
> }
> ```
> 
> less flexible than a mounted volume but works in a serverless environment.
> Just `docker build` from this Dockerfile and you can deploy on your production env.

Thanks, but I am already running superset using docker-compose and I was trying to figure out on which path to mount it to.

**Comment by adhip94** [comment]
Got it, I added the FEATURE_FLAG in the `superset_config.py` which was present in the cloned repository path `superset/docker/pythonpath_dev`.
