### ISSUE TITLE
Init database with admin user

### ISSUE THREAD

**Issue by himanshumps** [apache/superset#15284]
I am trying to setup the admin user with following Dockerfile

```
FROM apache/superset:latest
USER superset
RUN superset db upgrade && superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin && superset init
```

### Expected results

The admin user should be added.

### Actual results
The admin user gets added but I get readonly database error while adding dashboard

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
