### ISSUE TITLE
jinja templating not working (1.2.0-rc2) requires undocumented config

### ISSUE THREAD

**Issue by squalou** [apache/superset#15283]
### Expected results

Following documentation, running for instance this query should work (from sql lab)

```
SELECT  *
FROM mytable
WHERE username = '{{ current_username() }}'
```

should work and return results.

### Actual results

`{{ current_username() }}` is not interpreted at all, is considered as a String. Hence the result does not work.

Note that ` '{{ url_param('myparam') }}' ` does not work either

looks like no templating interpretation is done.

Used to work fine in 0.38

Does not work in 1.2.0-RC2

I don't know where to look for detailed executions logs. I had a look un `query` table of `superset` schema, query was not traced interpreted there but maybe it's the expected result.

#### How to reproduce the bug

1. Go to 'SQL Lab'
2. Enter a query using Jinja templating
4. See issue

### Environment

(please complete the following information):

- superset version: `Superset 1.2.0` (1.2.0-RC2 actually)
- python version: `Python 3.7.9`
- node.js version: not present in container

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by squalou** [comment]
Another example ... disclaimer : I'm not certain it was supposed to work, using the templating in the 'select'.

I can't find any other 'visually' self-explaining screenshot of the issue.

![image](https://user-images.githubusercontent.com/4623644/122792417-72667780-d2ba-11eb-8647-8d6f050d0f21.png)

**Comment by squalou** [comment]
I've found this : 

https://github.com/apache/superset/issues/12487


but nowhere in the documentation I can find how to enable

**Comment by squalou** [comment]
for the records, this works in `superset_config.py`

It should really be added here : https://superset.apache.org/docs/installation/sql-templating


```
FEATURE_FLAGS = {
    "ENABLE_TEMPLATE_PROCESSING": True
}
```

**Comment by maltoze** [comment]
#15246

**Comment by NikosSpanos** [comment]
> for the records, this works in `superset_config.py`
> 
> It should really be added here : https://superset.apache.org/docs/installation/sql-templating
> 
> ```
> FEATURE_FLAGS = {
>     "ENABLE_TEMPLATE_PROCESSING": True
> }
> ```
> 
> _BUT_ it _still doesn't_ work in SQL LAB. It works when used elsewhere

Thanks a lot for this post @squalou ...Firstly, I added the _ENABLE_TEMPLATE_PROCESSING_ in the ```config.py```  file which didn't help at all. Then I saw your post and added the same property on the ```superset_config.py``` and made the Jinja templating available through Virtual SQL. You may want to check [this](https://www.youtube.com/watch?v=dE1QlhunWMs) video on YouTube and see how you can use the templating and dunamic filtering with Filter Boxes.

Hope it helps. Kudos!!

**Comment by D0mc3k** [comment]
Hi Guys, 
I´m using the default docker-compose from the superset git repository and enabled Template Processing in the superset_config.py file
```
FEATURE_FLAGS = {
    "ENABLE_TEMPLATE_PROCESSING": True
}
```

But I still cannot use jinja templates e.g. current_username()
![image](https://user-images.githubusercontent.com/4028192/164220752-d82f1239-8808-4785-bf88-3a31e12d7a6d.png)

I have also tested it with a virtual dataset but it´s also not working. Anything I am missing especially in regards to enable Jinja Templates with Docker?

Thanks in advance

**Comment by rusackas** [comment]
Between the PR that appears to resolve the issue, the other help docs in the thread, and the relatively long silence on this thread, I'll go ahead and call this one case-closed. If there are indeed clarifications that need to be made in the documentation, would anyone be willing to open up a small PR and help add some clarity? It would be much appreciated!

**Comment by 1sarah** [comment]
Hello everyone ..I have question concerning jinja template (url_param)    i have a an sql(and a dataset too )that have populated
but when a request is made from the frontend am getting missing the right paranthesesis.Any help will be kindly appreciated


#passing params from portal to dashboard
