### ISSUE TITLE
Custom Color Theming Not working for embedded chart

### ISSUE THREAD

**Issue by laveenamurjani789** [apache/superset#15299]
While adding custom color theme for dashboard using below (where testpart23456789,Info,due,beforeTime,High are label names), the colors are getting applied only when charts are seen in the dashboard or during dashboard embed.
Issue we are facing is that when chart is explored or embedded, these label colors are getting overridden by default theming.

Also, while exploring chart, these label colors appear when "Superset Colors" theme is chosen but after saving, again the label colors get overridden by default theming.

 "label_colors": {
    "testpart23456789": "#FFFF00",
    "Info": "#FFFF00",
    "due": "#8B0000",
    "beforeTime": "#008000",
    "High": "#8B0000"
  }
  
 We got reference for above from FAQ- https://superset.apache.org/docs/frequently-asked-questions ( Is there a way to force the use specific colors?)

### Expected results

While chart embed or explore, the label colors should appear as provided i.e should follow below:

 "label_colors": {
    "testpart23456789": "#FFFF00",
    "Info": "#FFFF00",
    "due": "#8B0000",
    "beforeTime": "#008000",
    "High": "#8B0000"
  }

### Actual results

While adding custom color theme for dashboard using below (where testpart23456789,Info,due,beforeTime,High are label names), the colors are getting applied only when charts are seen in the dashboard or during dashboard embed.
Issue we are facing is that when chart is explored or embedded, these label colors are getting overridden by default theming.

Also, while exploring chart, these label colors appear when "Superset Colors" theme is chosen but after saving, again the label colors get overridden by default theming.

#### Screenshots

![image](https://user-images.githubusercontent.com/72306573/122956919-11649f80-d39f-11eb-8ad4-36f32a7622da.png)

#### How to reproduce the bug

1. Edit dashboard to add above provided config in Advanced Dashboard properties and save.
2. Open dashboard and explore any chart under it.
3. You will see that the colors provided are not being followed for labels.

### Environment

(please complete the following information):

- superset version: 1.1.0
- python version: 3.8.5
- node.js version: v14.17.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by amitmiran137** [comment]
This should be solved in 1.4
