### ISSUE TITLE
Custom sequential color schemes can not be added

### ISSUE THREAD

**Issue by sonyasha** [apache/superset#15312]
### A clear and concise description of what the bug is.
When new sequential color scheme is added to the `EXTRA_SEQUENTIAL_COLOR_SCHEMES` variable in `config.py` it does not appear in the list of linear color schemes.

### Expected results
New sequential color scheme appears in the linear color schemes.

### Actual results
New sequential color scheme does not appear in the linear color schemes dropdown, instead it can be found in the list of categorical color schemes.

#### How to reproduce the bug

1. Add
```
EXTRA_SEQUENTIAL_COLOR_SCHEMES = [
{
    "id": "GnYlRd",
    "label": "green/yellow/red",
    "colors": ['#006837','#1a9850','#66bd63','#a6d96a','#d9ef8b','#fee08b','#fdae61','#f46d43','#d73027','#a50026'],
    "isDiverging": True,
    "description": "",
  }
]
```
to the `config.py` file
2. Once the `superset_app` container reloads, open any visualization that uses sequential schemes, e.g. Country of Citizenship from examples.
3. Click `COUNTRY COLOR SCHEME` dropdown and ensure that there is no green/yellow/red color scheme.
4. Open any visualization that uses categorical schemes, e.g. Age distribution of respondents from examples.
5. Click Customize tab and `COLOR SCHEME` dropdown, green/yellow/red scheme will be there.

### Environment
- superset version: `1.2.0rc2`
- python version: `3.7.9`
- node.js version: `14.15.5`

### Additional context
It should be a one line fix in `setupColors.ts`, new sequential color schemes are currently registered in `categoricalSchemeRegistry` instead of `sequentialSchemeRegistry`.

**Comment by sonyasha** [comment]
Pushed a PR https://github.com/apache/superset/pull/15314

**Comment by zhaoyongjie** [comment]
> Pushed a PR #15314

Thanks for your contribution!

**Comment by sonyasha** [comment]
The change has been merged, the issue can be closed.
