### ISSUE TITLE
Cannot save dashboard properties when dashboard has been imported

### ISSUE THREAD

**Issue by stevensuting** [apache/superset#15317]
When a dashboard is exported and imported, it imports successfully, however it does not allow changes to dashboard properties to be saved.

### Expected results
Imported dashboards should behave like created dashboards. 

### Actual results

The save button is clickable but there is no response on the UI, no logs are generated when the save button is clicked. 

#### Screenshots

<img width="872" alt="Screenshot 2021-06-23 at 9 27 37 AM" src="https://user-images.githubusercontent.com/8875448/123033816-fda05400-d405-11eb-9bae-395437bfa1f0.png">

#### How to reproduce the bug

1. Export a dashboard
2. Import the same dashboard
3. Try changing the URL slug then try saving it. 
4. Save button is clickable but does not complete the save.

### Environment

(please complete the following information):

- superset version: `1.1.0`
- python version: `3.8`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [Y] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [Y] I have reproduced the issue with at least the latest released version of superset.
- [Y] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

It does allow saving other aspects, like dashboard layout, add/remove chart etc

**Comment by stevensuting** [comment]
@betodealmeida FYI

**Comment by ValentinC-BR** [comment]
I've got the same issue on 1.0.1 verison.

**Comment by aleksandrgordienko** [comment]
Same issue on 1.1.0

**Comment by d9k** [comment]
:cry:

**Comment by wiktor2200** [comment]
Hi! Do you have any updates on that? I've noticed in 1.4.0 that importing "Slug" setting doesn't work at all. When you export dashboard with slug set it exists in JSON file, but when imported it gets lost and it's saved nowhere.

**Comment by ValentinC-BR** [comment]
I think this was solved in the 1.5 release, but we're still in 1.4, so I can't confirm

**Comment by rusackas** [comment]
I tried this in 2.0.1, and it's all good now-a-days! If anyone finds I'm mistaken, let's re-open!
