### ISSUE TITLE
docker build failed (with fix)

### ISSUE THREAD

**Issue by juleslagarde** [apache/superset#15329]
Command `docker build` failed

### Expected results

build sucessfull

### Actual results

error
    In file included from Modules/LDAPObject.c:9:0:
    Modules/errors.h:8:18: fatal error: lber.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1

#### How to reproduce the bug

1. Git clone https://github.com/apache/superset
1. run docker build
1. See error

### Environment

- superset version: `1.2.0`
- python version: `Python 3.7.9`

### Fix found

added package `libldap2-dev` [in Dockerfile at line 30](https://github.com/apache/superset/blob/387d93302fa2f4f475cd572b62d0908615e67919/Dockerfile#L30)

**Comment by Hermain** [comment]
I also get the same error when I try to install python-ldap==3.3.1
