### ISSUE TITLE
Query on table from multiple databases

### ISSUE THREAD

**Issue by blackhawk28** [apache/superset#15327]
If i have 1 table in one database and 2nd table is in another database, can we join these 2 tables in superset? basically is it possible to join tables from multiple databases ?

**Comment by zhaoyongjie** [comment]
Please use Drill or Trino as federated query data warehouse

**Comment by blackhawk28** [comment]
> 
> 
> Please use Drill or Trino as federated query data warehouse

Thanks,but can you tell me, would it be configured with company specific(internal) superset?
and wouldn't there be any data privacy issue?
