### ISSUE TITLE
Line chart tooltip doesn't show on Chrome

### ISSUE THREAD

**Issue by kitkat73** [apache/superset#15332]
Similar to [this issue on Firefox](https://github.com/apache/superset/issues/7822), the tooltip on line charts is sometimes missing. The behavior is rather stochastic, see the description.

### Expected results

On hover over a datapoint on a line chart, display tooltip with exact values.

### Actual results

The data point is highlighted but no tooltip. Alternatively, it flashes for a second and then disappears (see the video below). The only solution is to force-refresh the chart - then the tooltip temporarily works. If you leave the dashboard tab and come back, the tooltip is gone and the chart needs to be force-refreshed again.

#### Screenshots
<img width="681" alt="Screen Shot 2021-06-23 at 16 39 45" src="https://user-images.githubusercontent.com/42228832/123117053-b6d04f80-d441-11eb-875f-38a6eeb0f698.png">

My colleague recorded this video clearly showing the issue (password: 2pQcGv8V):
https://cisco-collab.webex.com/recordingservice/sites/cisco-collab/recording/53432c86b65a1039bab50050568f1ab8/playback

#### How to reproduce the bug

It is hard to reproduce because the problem occurs for certain dashboards, and for certain not. Also on the dashboard from the video, some charts are sometimes working fine and some are missing it, next time it's not working for any. However, we were able to reproduce the missing tooltip behavior for at least 3 different users, all on Chrome.
1. Go to a dashboard containing line charts
2. Hover over a time point
3. Observe the tooltip flashing and disappearing or not showing at all

### Environment

- superset version: `Version: 1.1.0`
- python version: `python:3.8.9-slim`

### Checklist

- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar. - I found one, it's linked at the top, but it's for Firefox and it looks like it's been solved for that browser.

**Comment by zhaoyongjie** [comment]
We recommend you to use `Time-series Chart` instead of `Line Chart`, because the line chart is going to be deprecated.

**Comment by etr2460** [comment]
This bug is fixed in the master branch, and will hopefully be released soon (not sure if it's included in 1.2 @amitmiran137 do you know?) see here: https://github.com/apache/superset/pull/15073 and here: https://github.com/apache/superset/issues/13952

**Comment by amitmiran137** [comment]
Not in 1.2

**Comment by kitkat73** [comment]
> We recommend using `Time-series Chart` instead of `Line Chart`, because the line chart is going to be deprecated.

@zhaoyongjie Thank you for the suggestion. The issue with the Time-series Chart is that the auto-formatting of the X axis doesn't work well, whereas with Line Chart it's great. See the same chart displayed as Line chart (month names + years) and as Time-series Chart (very long, rotated labels). I tried to setting a custom time format, but nothing is as good by far (and one needs to set it for every chart..).

<img width="1121" alt="Screen Shot 2021-06-30 at 09 36 09" src="https://user-images.githubusercontent.com/42228832/123921274-20db7e00-d987-11eb-9333-66e41720c761.png">
<img width="1121" alt="Screen Shot 2021-06-30 at 09 36 37" src="https://user-images.githubusercontent.com/42228832/123921283-233dd800-d987-11eb-93ca-0aebb723f496.png">
