### ISSUE TITLE
Cannot enter more than one character at a time in simple filter text box

### ISSUE THREAD

**Issue by serenajiang** [apache/superset#15335]
In charts, when adding a simple filter, you cannot type more than one character at a time into the value text box. After you type one character, the text box is deselected, and you must click the text box again in order to type another character.

This occurs if the column + the operator is selected, and occurs for all operators except `IN` and `NOT IN`.

### Expected results

Text box should not be deselected after one character is entered.

### Actual results

https://user-images.githubusercontent.com/14146019/123159110-77920680-d421-11eb-82f6-f0c564de6c36.mov

#### How to reproduce the bug

1. Go to chart explore
2. Add a filter
3. Select a column and select "equals" as the operator
4. Try to type into the textbox

### Environment

(please complete the following information):

- superset version: up-to-date with master as of 2021-06-22
- python version: `python --version` 3.8
- node.js version: `node -v` v14.16.1

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ X] I have reproduced the issue with at least the latest released version of superset.
- [ X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zhaoyongjie** [comment]
@serenajiang, Thanks for the reporting. PR merged
