### ISSUE TITLE
[explore][mixed time series chart] 'Sort by' function is not taking effect  

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15345]
'Sort by' function is not taking effect when sort by metrics is defined

### Expected results

data will sort in order

### Actual results

data is not sorted in order

#### Screenshots

<img width="1758" alt="Screen Shot 2021-06-23 at 9 27 41 PM" src="https://user-images.githubusercontent.com/81597121/123203743-aa60ec80-d46b-11eb-88d1-295fc43cf680.png">

#### How to reproduce the bug

1, use dataset 'clean_sales_data'
2, select 'Mixed time series chart as view type
3, for query A, select metrics 'Max(sales)'
4, for query B, select metrics 'Min(sales)'
5, select 'Max(sales') in 'Sort by'
6, select SORT DESCENDING option
7, create chart and observe Data panel

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zhaoyongjie** [comment]
closed by https://github.com/apache-superset/superset-ui/pull/1206
