### ISSUE TITLE
[cosmetic][dashboard] chart 3 dot menu is behind the chart title panel in chart maximize mode

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15348]
## Screenshot

<img width="1792" alt="Screen Shot 2021-06-23 at 10 45 23 PM" src="https://user-images.githubusercontent.com/81597121/123209110-ffedc700-d474-11eb-91f1-16002273460a.png">

## Description

chart 3 dot menu is behind the chart title panel in chart maximize mode

**Comment by stephenLYZ** [comment]
working on it

**Comment by stephenLYZ** [comment]
fixed by #15384

**Comment by junlincc** [comment]
Thanks @stephenLYZ ! closing issue
