### ISSUE TITLE
[SIP-70] Secret keys rotations and stop using single SECRET_KEY

### ISSUE THREAD

**Issue by ofekisr** [apache/superset#15362]
### In short
* Instead of using one master key aka flask.secret_key use different key for each use case
* support key rotation

### In long
Our organization security policies require to meet constraints in regard to using secret keys and credentials
* Our products should use a different key for each use so in case a specific key is stolen, all other objects are kept safe.
* Key can be changed or rotated at any time, so fresh keys can be maintained all the time.
* When Superset is crashed or exited, the keys cannot be lost so encrypted data could be decrypted.

## Proposed Change

* Each library/module which uses the master key by accessing app.secret_key will access the key by calling a get key method
* Use cases consisting of encryption-decryption flows will define methods handling procedures of rotations, means decrypt with old keys and re-encryption with a new key 
* Adding endpoints to declare rotations, they will trigger the declared procedures. 
* Easy way to define new dedicated keys in the future features 

## Guidelines
* Use feature flag
* Incremantaly by phases, each phase can consist of a series of PRs, PR for each specific secret-key use 
* Default values will be the current master key
* Can be customized for each use-case 
* Contribute to depended libraries 

## Plan
P1 - adapting required infrastructure without any usage yet
P2 - migrate using the new infrastructure
P3 - adding infrastructure to support key-changed declarations 
P4 - upgrade the dependent libraries that adapt the same mechanism 

### P1 - https://github.com/apache/superset/pull/15423
* Adapting the https://pypi.org/project/keys-management/ package 
   https://github.com/nielsen-oss/keys-management
* defining feature flag  

### P2 
for each dedicated key: 
 - add temporary code to inject secret key method instead of value - based on inheritance the current client's classes
 - define specific configurations for the specific key while the default value will be the master key
 - if necessary defining rotation methods 
 * review phase four why I said "temporary code"

#### P2 implementations
* Dedicated key for singing cookies: https://github.com/apache/superset/pull/15296
* Dedicated key for encryption-decryption insert and fetching "databases" rows (models)
* Dedicated key for Oauth login flow
* Dedicated key for Fab login and decorators

### P3
will be incrementally too, first adding REST API endpoints, then refactor or add more safe and robust way
such as CLI - 
first, support only an offline mode. 
Then build a small CLI socket-based service to support key rotations in runtime 

### P4
We plan to contribute the same mechanism directly to the dependent libraries.
for each adapted dependent library 
- remove the temporary code added in phase three 
- upgrade the library

**Comment by michael-s-molina** [comment]
Thanks for the SIP @ofekisr. 

Currently, we have some very mature solutions regarding the management of secret keys like [Keywhiz](https://github.com/square/keywhiz), [Vault](https://github.com/hashicorp/vault), [Confidant](https://github.com/lyft/confidant), [Knox](https://github.com/pinterest/knox), etc. Can you provide more context on which solutions were considered, why they don't fit our case, and why did you choose to implement your own package? It would be awesome to add this information to the **Rejected Alternatives** section of the SIP.

**Comment by ofekisr** [comment]
Hi @michael-s-molina 
none of the solutions you suggest is a python based except for Confidant.
My solution support secret-keys-rotations assistance.
[keys-management](https://pypi.org/project/keys-management/) package  does not claim to be responsible for storing keys, there are so many solution for it

**Comment by craig-rueda** [comment]
I'm all for this one, as long as the final impl is pluggable. I think I share @michael-s-molina 's concern in that the implementation shouldn't prevent us from being able to adapt the secret backend to whatever provider a user needs. I suggest adding the ability to configure different "providers" that can be overridden in configuration, with the default implementation just delegating to `SECRET_KEY` for backwards compatibility.

**Comment by ofekisr** [comment]
As I had already said, the keys-management package does not claim to be responsible for storing keys, but it fetches the key by key-store - a function that return keys, so each client can define its key-store to fetch keys from a specific provider

**Comment by rusackas** [comment]
@ofekisr is there any intent to complete the vote for this SIP and follow through on it, or should we close it out?

Does anyone else here have interest in picking it up if not?

**Comment by rusackas** [comment]
Closing as discarded. If there is any intent to complete the VOTE process and move this SIP forward, we'll be more than happy to re-open it.
