### ISSUE TITLE
[native filter] enlarged window of value filter will block the filter underneath

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15360]
when select more than 5 value in value filter, the enlarged window of value filter will block the filter 

### Expected results

enlarged filter window will not block other filter

### Actual results

enlarged filter window  block filter underneath

#### Screenshots

<img width="1772" alt="Screen Shot 2021-06-24 at 2 30 57 AM" src="https://user-images.githubusercontent.com/81597121/123242829-448a5a00-d497-11eb-82cf-d65ddde2b36d.png">

#### How to reproduce the bug

1. create value filter first then create a time range filter
2. select 5+ in value filter and see the select window enlarge
3. See error

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
This is technically the same bug as #15322 , but for transparency, it's probably good to keep these as separate tickets.
