### ISSUE TITLE
[native filter] 'Clear All' will show error in value filter 

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15361]
when setup a value filter + numerical filter in a dashboard, set both filter 'Apply changes instantly', then select value for each filter and then click 'Clear All', value filter will show error of too many updates

### Expected results
value filter and numerical filter can be clear 

### Actual results

value filter show error, numerical filter can be clear to origin state

#### Screenshots

<img width="1791" alt="Screen Shot 2021-06-24 at 3 04 35 AM" src="https://user-images.githubusercontent.com/81597121/123245125-6258be80-d499-11eb-9bab-466930c66435.png">

https://user-images.githubusercontent.com/81597121/123245951-270abf80-d49a-11eb-859b-0e95a2e2489d.mov

#### How to reproduce the bug

1. Go to USA birth name dashboard
2. Setup a value filter, select 'apply change instantly'
3. Setup a numerical filter, select 'apply change instantly'
4. go to dashboard and select some value for both filter and see changes 
5. click 'Clear All' and see error in value dashboard

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
Reproduced

**Comment by villebro** [comment]
As per the plan to deprecate support for instant filtering outlined in #15067, this bug likely won't need to be addressed (removing P1).
