### ISSUE TITLE
[sqllab] when I try to create a  new query using button on homepage then I should see new tab with empty editor

### ISSUE THREAD

**Issue by adam-stasiak** [apache/superset#15370]
When I open homepage and then click on +sql query under saved queries section I expect to see fresh tab of editor instead of existing one.

### Expected results

See new tab to start writing sql.
### Actual results
I can see existing tab
#### Screenshots
<img width="1179" alt="Zrzut ekranu 2021-06-24 o 20 14 50" src="https://user-images.githubusercontent.com/25153919/123312669-f02fba80-d528-11eb-8255-66b94d1e3e53.png">
<img width="1206" alt="Zrzut ekranu 2021-06-24 o 20 15 10" src="https://user-images.githubusercontent.com/25153919/123312673-f0c85100-d528-11eb-9be8-82c24cc037cf.png">

#### How to reproduce the bug

1. Go to homepage
2. Go to saved queries section
3. Click on +sql query
4. Check the content of sql editor

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by stephenLYZ** [comment]
fixed #15492

**Comment by stephenLYZ** [comment]
fixed #15492

**Comment by pkdotson** [comment]
This has been fixed. Closing this issue
