### ISSUE TITLE
[native filter] 'Clear All' for time range filter with required option will make red high light without error message 

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15375]
'Clear All' for time range filter with required option will make red high light without error message

### Screenshot or Video
https://user-images.githubusercontent.com/81597121/123336949-6a494a80-d4fb-11eb-99db-ba0746353875.mov

### Repo steps
1, create a time range filter with 'Required ' option selected
2, go to the dashboard and click ' Clear All'
3, observe the time range filter

### Expected result
'time range is required' error message showed when 'Clear All' of required time range filter

### Actual result
'Clear All' of required time range filter only make red highlight of the filter but not indicator the error

### Environment

- superset version: `master`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by geido** [comment]
@jinghua-qa It appears this is the wanted behavior. What we have agreed is to show a tooltip that shows the error when hovering the time range. Can we prioritize this work? @junlincc
