### ISSUE TITLE
BigQuery Shared DataSets Schema is Not Showing in SQL Lab 

### ISSUE THREAD

**Issue by codegeekjk** [apache/superset#15382]
### Expected results

I have datasets belongs to some other GCP Project, which has been shared to our in house GCP Project, our service account has access to it.

We Created  a connection to our GCP Project, which was successful and on SQL Lab we are able to run the queries to datasets belongs to other GCP PROJECT. 
i.e select * from some_other_project.data_set.schema.

But in SQL LAB  i.e in Schema and Table Drop Down those datasets are not visible. 

How we can create a new data connection which can show us the schemas and tables belong to the other GCP PROJECT as our service account has access to it ?

From the logs it try to query this :

`"POST /bigquery/v2/projects/My_other_GCP Project/jobs` getting  403 None as we don't have job permission to that project 

My Connection :
bigquery://MY_OTHER_GCP_PROJECT

Provided our service account json in extra parameters. 

### Actual results

Able to connect to other shared GCP project using  service account json which has access to the datasets.

**Comment by Guillaume-bytel** [comment]
It's working with your trick but in this case Bigquery processing cost is apply on second projet.

It's also not possible to have sql query join data from multiple projets.

**Comment by ad-m** [comment]
I would like to add that using shared datasets will allow easy try to use Superset, thanks to public datasets of BigQuery: https://cloud.google.com/bigquery/public-data

**Comment by rusackas** [comment]
Tempted to close this one as stale and semi-resolved anyway... does anyone see value in keeping this open? CC @betodealmeida

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
