### ISSUE TITLE
[sqllab] Stop button should kill running query in the database

### ISSUE THREAD

**Issue by koszti** [apache/superset#15402]
**Is your feature request related to a problem? Please describe.**

SQL Lab has Stop button but it only updates state of superset without actually stopping the database query. Leaving the queries running in the background affect database performance.

Running queries should be killed automatically in the database if the stop button pressed, the browser window closed or navigated to another site.

**Describe the solution you'd like**

Pressing the stop button in SQL Lab should trigger a mechanism to kill the running query in the database.  The same function should be called when the browser windows closed or navigated to another site.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by rusackas** [comment]
Looks like the fix was merged and this was just never closed.

**Comment by RamyR** [comment]
Hey @rusackas 

Dashboard Limitation: The developer mentioned they planned to add similar functionality for Explore/Dashboards, but given the timeline (from 2021), it appears this feature is still limited to SQL Lab.

Any idea on when this could be available please 🙏
