### ISSUE TITLE
markdown table without border

### ISSUE THREAD

**Issue by zhugw** [apache/superset#15421]
I'm using version `1.1.0`, find the table markdown without border 

```
Colons can be used to align columns.

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

There must be at least 3 dashes separating each header cell.
The outer pipes (|) are optional, and you don't need to make the 
raw Markdown line up prettily. You can also use inline Markdown.

Markdown | Less | Pretty
--- | --- | ---
*Still* | `renders` | **nicely**
1 | 2 | 3
```

result:
![image](https://user-images.githubusercontent.com/4953871/123624812-a0f7cb80-d841-11eb-90c1-dec4bdb5b64e.png)

but I want the real effect like below:
![image](https://user-images.githubusercontent.com/4953871/123624886-ba007c80-d841-11eb-8b08-85cf3e35d80c.png)

**Comment by srinify** [comment]
Hi @zhugw I'm a bit confused about your question! 

- Do you want to render a table in a markdown component?
or
- Do you hope to not have borders in a table viz?

**Comment by zhugw** [comment]
@srinify I want to render a table in a markdown component and have borders with it

**Comment by vmgustavo** [comment]
Just ran into this issue. Markdown tables are not rendered properly, it would be nice to have a fully functional markdown system.

To render a table in a markdown component IMO has nothing to do with rendering a table component. In markdown I expect to simply display static information specified in the text and not connect it to any data source.

**Comment by marcos-mendez** [comment]
Up please this is so TRUE

**Comment by rusackas** [comment]
The tables are rendering correctly. They just don't have a border. You can open a PR to change that, or you can [customize your dashboard with CSS](https://preset.io/blog/customizing-superset-dashboards-with-css/).

**Comment by sfirke** [comment]
Evan's answer closes this issue, I believe.  I just used it to deal with this myself.  For the sake of knowledge capture here is the CSS I've added to the dashboard:
```
table {
    border-collapse: collapse;
}

table, th, td {
    border: 1px solid black;
    padding: 4px;
}
```

**Comment by soham-dasgupta** [comment]
To just target markdown table, Thanks @sfirke 
```
.dashboard-markdown * table {
    border-collapse: collapse;
}

.dashboard-markdown * table, .dashboard-markdown * th, .dashboard-markdown * td {
    border: 1px solid black;
    padding: 4px;
}
```
