### ISSUE TITLE
[Dashboards] Can't assign new owner to a dashboard that has been imported.

### ISSUE THREAD

**Issue by lctdulac** [apache/superset#15428]
Hi team,

We've encountered an issue where we can't assign a new Dashboard Owner on dashboard that we create through importing.

### Expected results

Click SAVE actually adds an Owner.

### Actual results

Nothing happens. Click is useless, window stays open and action is not done.

#### Screenshots

![Screenshot 2021-06-28 at 16 34 50](https://user-images.githubusercontent.com/46674763/123663060-51f86900-d836-11eb-8f6b-4cbc3a4640f4.png)

SAVE button clicked: nothing happens.

#### How to reproduce the bug

1. Try to assign a new owner to an existing dashboard. It should work.
2. Export the dashboard (has to contains several charts) with the export button in the dashboard list
3. Create a new dashboard through importing (settings) 
4. Try to assign a new owner. It shouldn't work.

### Environment

Version: 1.1.0

Any idea what might be causing this? Are you able to reproduce?

**Comment by amitmiran137** [comment]
Related https://github.com/apache/superset/pull/15292

**Comment by sfirke** [comment]
This affects a very old version of Superset and has not had activity in almost two years.  I'm going to close it; anyone experiencing this issue should please verify that it persists in a current version of Superset and open a new issue, please.
