### ISSUE TITLE
Alerts and Reporting Whole Dashboard is not Coming in Reporting 

### ISSUE THREAD

**Issue by codegeekjk** [apache/superset#15449]
While Sending Reports, Superset is not able to captured the Whole dashboard, only the charts present in the browser size window is captured in the screenshot, if dashboard has charts which need to scrolled down i.e In browser dashboard is not in full page, then those charts are not there

**Comment by rusackas** [comment]
This is likely fixed by now, and is super stale if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
