### ISSUE TITLE
Add support for IBM Netezza

### ISSUE THREAD

**Issue by abhishekjog** [apache/superset#15452]
**Is your feature request related to a problem? Please describe.**
IBM Netezza now has a python DB API driver (nzpy) and SQLAlchemy dialect (nzalchemy). Need to add support for IBM Netezza in Superset.

**Describe the solution you'd like**
Superset installation should install nzalchemy and nzpy. 
Netezza logo is shown on Superset readme.
Superset should be able to connect to Netezza and execute queries, create charts etc.

**Describe alternatives you've considered**
There is no alternative.

**Additional context**
NA

**Comment by srinify** [comment]
Closing since @abhishekjog took on the work of adding docs + a db engine spec!

#15450
