### ISSUE TITLE
[Echarts]Time-series chart renders chart vertically when orderby

### ISSUE THREAD

**Issue by villebro** [apache/superset#15469]
When setting the series limit orderby metric in the "Time-series chart", the lines draw from top to bottom/bottom to top. This is due to ECharts rendering the line in the order that the points are provided. In the outer orderby we should probably always force the temporal column to be the first orderby to avoid this problem.

### Expected results

Line should render from left to right

### Actual results

![image](https://user-images.githubusercontent.com/33317356/123917566-9cd7c500-d98b-11eb-9f72-47f98dcf6bf0.png)

what actually happens.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
Can we make this change in Echarts repo?

**Comment by Shazad-khan** [comment]
![image](https://user-images.githubusercontent.com/100838455/225287510-7df22966-b8f2-43c1-a5e6-32c985f629d1.png)
This issue has already been addressed in the recent release

**Comment by villebro** [comment]
Thanks @Shazad-khan , I'll close this 👍
