### ISSUE TITLE
[Clickhouse] [Feature Request]  SQL editor autocomplete for functions and args

### ISSUE THREAD

**Issue by asafcombo** [apache/superset#15477]
I saw that this is currently only supported in hive connections (see below for reference).

This feature is important for data exploration purposes 

https://github.com/apache/superset/blob/e466066229ec8262583bc118af1f39e2dbf77bcf/superset/db_engine_specs/hive.py#L508

**Comment by junlincc** [comment]
@asafcombo we would love a contribution from the community 🙏😬
