### ISSUE TITLE
chart page filters set is null show err

### ISSUE THREAD

**Issue by 1758973467** [apache/superset#15474]
when set filters control 
column is number and op is IS NULL or IS NOT NULL then show error
#### Screenshots

![SharedScreenshot1](https://user-images.githubusercontent.com/16133508/123958778-0c779f80-d9e0-11eb-9604-3909f82a4656.jpg)
![SharedScreenshot2](https://user-images.githubusercontent.com/16133508/123958783-0da8cc80-d9e0-11eb-9df7-27a1d084a75b.jpg)
![SharedScreenshot](https://user-images.githubusercontent.com/16133508/123958961-38932080-d9e0-11eb-874f-42879e173b7a.jpg)

#### How to reproduce the bug

1. select example exist  Treemap
2.  set filters NY_GNP_PCAP  IS NOT NULL (using simple )
3.  then click run 

### Environment

- superset version: 1.1.0
- python version: 3.7.9
- node.js version: 14.16.1

**Comment by junlincc** [comment]
<img width="1664" alt="Screen Shot 2021-06-30 at 5 34 16 PM" src="https://user-images.githubusercontent.com/67837651/124047629-789ad900-d9c9-11eb-9840-146482125f9a.png">
Should have been fixed in later version :) feel free to reopen if that's not the case.

**Comment by 1758973467** [comment]
OK, i will switch to 1.2.0

**Comment by 1758973467** [comment]
OK, i will switch to 1.2.0,thanks
