### ISSUE TITLE
[native-filters]GroupBy filter Badge is wrong

### ISSUE THREAD

**Issue by simcha90** [apache/superset#15488]
Indicator is showing as not applied for GroupBy filter:
> ![image](https://user-images.githubusercontent.com/33317356/124077300-0a4d2980-da50-11eb-9033-73e00f6f8658.png)

**Comment by rusackas** [comment]
I don't think this bug is still relevant and is most certainly stale, so I'll go ahead and close it. Happy to discuss with more current context if it needs revisiting.
