### ISSUE TITLE
Hierarchical filters hang when filters are made parents of one another

### ISSUE THREAD

**Issue by vermilioncity** [apache/superset#15483]
Suppose you have Filter A and Filter B.  You set Filter A to be a hierarchical filter and its parent to be Filter B.  Then you set Filter B to be a hierarchical filter and its parent to be Filter A.  The app hangs.  If you open up the dev console, you will see errors printed out complaining about maximum recursion depth exceeded.

### Expected results

Filters with already assigned relationships should be excluded from the drop down.

### Actual results

All available filters are shown and the app goes into a recursive loop if you fatfinger and select a preexisting child.

#### How to reproduce the bug

1. Create two filters (filter A and B)
2. Set filter A to be hierarchical and parent as Filter B
3. Set Filter B to be hierarchical and parent to be Filter A
4. Watch app hang forever :(

### Environment

- superset version: 1.3 branch
- python version: Python 3.7.9
- node.js version: 14

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@vermilioncity thanks for reporting. I was able to reproduce. 
This case is tricky! We can't really check both filters as hierarchical and parent. 
However, ideally there should be two hierarchical filter sets showing on the filter bar with A as parent, B as child & B as parent A as child. And user can switch between 2 groups. But right now, when I create two groups separately, all the filters become children of A... see video

Have you tried using filter sets (behind another feature flag) as an alternative? 

https://user-images.githubusercontent.com/67837651/124045932-a4b45b00-d9c5-11eb-87f9-e3aebee078ef.mov

this seems quite hard to fix and it's really an edge case. @villebro wdyt?
