### ISSUE TITLE
[Export Dashboard][Native Filter] Column selection is not saved in export file, and saving dataset id in export file doesn't seem to be a correct approach

### ISSUE THREAD

**Issue by rosemarie-chiu** [apache/superset#15484]
Column selection is not saved in export file, and saving dataset id in export file doesn't seem to be a correct approach

### Expected results
Import a dashboard with native filter to a new workspace should work seemlessly.

### Actual results
1. Selected column is not present in the export file, resulting in new dashboard native filter error with missing column selection.
2. Saving dataset id in the export file is an incorrect approach. The dataset id in a different workspace is different. In my example, dataset id =29 is already taken in the new workspace, this result in the imported dashboard showing the wrong dataset selection in native filter.

#### Screenshots
![image](https://user-images.githubusercontent.com/52086618/124030259-e1268d80-d9aa-11eb-9497-f373eb670a65.png)
![Clipboard 2021-30-06 at 1 44 38 PM](https://user-images.githubusercontent.com/52086618/124030653-411d3400-d9ab-11eb-954f-382602aee88c.png)

#### How to reproduce the bug
1. Create a dashboard
2. Create a value native filter and select dataset and column
3. Export this dashboard
4. Import this dashboard to a new workspace

**Comment by junlincc** [comment]
thanks for reporting the issue!! could you double check if filterbox work in this case? @rosemarie-chiu 🙏 it would help set the priority, whether it's for feature parity or a new feature request.

**Comment by rusackas** [comment]
Duplicates #15531

**Comment by rosemarie-chiu** [comment]
@junlincc @rusackas this should be a bug to fix not an enhancement. From my screenshot you can see that the exactly same filter, filterbox works just fine after export / import but native filter doesn't.
![CleanShot 2021-07-21 at 15 51 57](https://user-images.githubusercontent.com/52086618/126569901-ea1b717b-b876-490e-8b9c-dc0bfe3cfc98.png)

The root cause of this is that `filterbox` exported yaml refer to dataset by it's `uuid`
![CleanShot 2021-07-21 at 15 54 36](https://user-images.githubusercontent.com/52086618/126570094-e92d81d9-1eac-498e-89a3-cdc75f27226b.png)

whereas `native filter` exported yaml file refer to dataset by it's `datasetId`
![CleanShot 2021-07-21 at 15 56 42](https://user-images.githubusercontent.com/52086618/126570240-9f9d59f4-8c93-4b52-afbc-7bea02e50a1b.png)

This is wrong because datasetId is different in every workspace. So I believe making that uuid instead of datasetId will solve this issue.

**Comment by rosemarie-chiu** [comment]
cc @villebro https://github.com/apache/superset/pull/15253/files I think it is this PR we added mapping to datasetId.

**Comment by villebro** [comment]
This has been reproduced and is only affecting installations that have enabled the "VERSIONED_EXPORT" feature flag - with the feature flag disabled this works correctly. The solution is to port the logic from the legacy JSON-based export to the new YAML-based export (working on it now).

**Comment by michael-s-molina** [comment]
Beautiful investigative work and issue description @rosemarie-chiu 👏🏼
