### ISSUE TITLE
Set dynamically default value of Time filter 

### ISSUE THREAD

**Issue by liuyong888** [apache/superset#15499]
apache superset 1.1.0
Time filter sets **dynamic default values**.
e.g.
**"time range" : {
  from: ‘The first day of this year‘
to: ‘now’**
} @zhaoyongjie

**Comment by zhaoyongjie** [comment]
Hi, there. Is it ?

![image](https://user-images.githubusercontent.com/2016594/124119183-c59fad80-daa4-11eb-8639-eb9ef8ce1885.png)

**Comment by liuyong888** [comment]
Yep!
