### ISSUE TITLE
cache key for warm_up_cache and explore_json are not matching

### ISSUE THREAD

**Issue by ukm21** [apache/superset#15497]
Both the /warm_up_cache/ and /explore_json/ API endpoints should produce the same cache key for a given slice

### Expected results

should return same cache key 

### Actual results

different cache key are getting generated

#### How to reproduce the bug

1. run cache warmup for a slice
2. check the cache key value
3. explore the same slice in browser
4. different cache key will be generated so query will be fired.

### Environment

(please complete the following information):

- superset version: `1.1.0`
- python version: `3.8.9`
- node.js version: `12`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

**Json_Data for Explore chart**

{"changed_on":1621922272000.0,"columns":["app_name"],"datasource":"1__table","extra_cache_keys":[],"extras":{"having":"","having_druid":[],"time_grain_sqla":"P1D","time_range_endpoints":["inclusive","exclusive"]},"filter":[],"granularity":null,"groupby":[],"is_rowcount":false,"is_timeseries":false,"metrics":[{"aggregate":"COUNT_DISTINCT","column":{"column_name":"app_id","description":null,"expression":null,"filterable":true,"groupby":true,"id":5,"is_dttm":false,"python_date_format":null,"type":"STRING","verbose_name":null},"expressionType":"SIMPLE","hasCustomLabel":false,"isNew":false,"label":"COUNT_DISTINCT(app_id)","optionName":"metric_6qp914zxuux_o2r0useg7ob","sqlExpression":null}],"order_desc":true,"orderby":[[{"aggregate":"COUNT_DISTINCT","column":{"column_name":"app_id","description":null,"expression":null,"filterable":true,"groupby":true,"id":5,"is_dttm":false,"python_date_format":null,"type":"STRING","verbose_name":null},"expressionType":"SIMPLE","hasCustomLabel":false,"isNew":false,"label":"COUNT_DISTINCT(app_id)","optionName":"metric_6qp914zxuux_o2r0useg7ob","sqlExpression":null},false]],"rls":[],"row_limit":100,"row_offset":0,"time_range":"Last week","timeseries_limit":0,"timeseries_limit_metric":null}

**Json Data for warmup** 

{"changed_on":"2021-05-25T05:57:52","datasource":"1__table","extra_cache_keys":[],"extras":{"druid_time_origin":"","having":"","having_druid":[],"time_grain_sqla":"P1D","time_range_endpoints":["inclusive","exclusive"],"where":""},"filter":[],"granularity":null,"groupby":["app_name"],"is_timeseries":false,"metrics":[{"aggregate":"COUNT_DISTINCT","column":{"column_name":"app_id","description":null,"expression":null,"filterable":true,"groupby":true,"id":5,"is_dttm":false,"python_date_format":null,"type":"STRING","verbose_name":null},"expressionType":"SIMPLE","hasCustomLabel":false,"isNew":false,"label":"COUNT_DISTINCT(app_id)","optionName":"metric_6qp914zxuux_o2r0useg7ob","sqlExpression":null}],"order_desc":true,"orderby":[[{"aggregate":"COUNT_DISTINCT","column":{"column_name":"app_id","description":null,"expression":null,"filterable":true,"groupby":true,"id":5,"is_dttm":false,"python_date_format":null,"type":"STRING","verbose_name":null},"expressionType":"SIMPLE","hasCustomLabel":false,"isNew":false,"label":"COUNT_DISTINCT(app_id)","optionName":"metric_6qp914zxuux_o2r0useg7ob","sqlExpression":null},false]],"rls":[],"row_limit":100,"time_range":"Last week","timeseries_limit":0,"timeseries_limit_metric":null}

**Comment by t0il3ts0ap** [comment]
Facing the same issue, I hit `warm_up_cache` endpoint and it generates new key in redis.
Also, the celery job hits `explore` endpoint  to warm_up_cache which is non functional as well.

@ukm21 were you able to solve this ?
