### ISSUE TITLE
Superset URL - connection refused

### ISSUE THREAD

**Issue by ag-supersetuser** [apache/superset#15503]
Hi, first time poster so please forgive if I miss out anything obvious that should be included.

We have a two main instances of Superset installed, used to visualise business data. Version 1.0.1, in Ubuntu using venv. Python version is 3.8. They are port forwarded through our firewall and DNS is attached from an external provider. Each instance is held on a separate server, and located in separate buildings. 

We have a third version, setup the same as above but used only for testing and training and this is also on a separate server in a separate building.
Also, we run an older version of Superset from previous installations, which is version 0.36.

Yesterday (June 30, 2021), all instances of Version 1.0.1 were working as expected and we were able to use each separate URL to view and edit charts and dashboards.
Today however (July 1), each separate URL of the V1.0.1 instance is inaccessible via external browsers and also the internal IP addresses. **The older V0.36 version still works**.

The browser error is pointing to a network issue but we have ruled out internal network issues as these V1.0.1 instances are on 3 separate sites with 3 separate networks. We have also isolated a Superset version on a home network and found the same issues between older versions and newer versions.

Could there be an issue with any external library files that Superset connects to?

We have tried upgrading one of the v1.0.1 instances to v1.1.0 but this action has had no effect.

Screenshots below of Chrome and Firefox.

Thanks in advance for any advice or help you can give.

<img width="973" alt="Firefox" src="https://user-images.githubusercontent.com/86788923/124143720-43eb5800-da83-11eb-97da-1f37d079d904.png">

![Chrome](https://user-images.githubusercontent.com/86788923/124143725-451c8500-da83-11eb-9a60-a75dafdecb50.png)

**Comment by nytai** [comment]
This seems specific to your installation of superset or networking set up

**Comment by ag-supersetuser** [comment]
> This seems specific to your installation of superset or networking set up

Hi @nytai , you think so, even though nothing in our setup or network has changed overnight? All fine one day, broken the next.

**Comment by ag-supersetuser** [comment]
just an update for anybody that views this.
This wasn't a network issue at all, as we kind of new from the beginning.
We have run some upgrades today and discovered a new version of Superset has been released, v1.2.0 which fixes this problem. The issue itself is better explained by another user who posted today, here: https://github.com/apache/superset/issues/15524
Release announcement here: https://github.com/apache/superset/releases
