### ISSUE TITLE
[native-filters]The modal for deeply nested hierarchical filters slowly and visibly expands in width

### ISSUE THREAD

**Issue by vermilioncity** [apache/superset#15517]
## Screenshot
![image](https://user-images.githubusercontent.com/35211278/124193605-17d8d280-da95-11eb-9084-c4bb520d0658.png)
![image](https://user-images.githubusercontent.com/35211278/124193541-0394d580-da95-11eb-8c6e-fe117a7d2091.png)

## Description

If you have a deeply nested hierarchy, it promptly and visibly begins to slowly expand in width.

**Comment by michael-s-molina** [comment]
This was fixed in https://github.com/apache/superset/pull/15433.
