### ISSUE TITLE
[native-filters]Out of scope hierarchical filters do not show as being out of scope

### ISSUE THREAD

**Issue by vermilioncity** [apache/superset#15516]
I have a dashboard with two tabs, and a set of hierarchical filters.  The last filter in the hierarchy is only applied to the second tab (all of its parents apply to both tabs).  I expect the child to be considered out-of-scope, but it instead is listed for both tabs anyway.

### Expected results

The hierarchical filter that is out-of-scope for the tab should be hidden.

### Actual results

The out-of-scope hierarchical child filter is visible across all tabs.

#### Screenshots
![image](https://user-images.githubusercontent.com/35211278/124193452-d47e6400-da94-11eb-8bff-3db64e145a3e.png)
![image](https://user-images.githubusercontent.com/35211278/124193225-76ea1780-da94-11eb-80a4-81a8b8f0d88d.png)

#### How to reproduce the bug

1. Create a two-tabbed dashboard with one chart each
2. Create a hierarchical filter
3. Set one of the children to apply to the second tab only
4. Have it be visible anyway

### Environment

- superset version: 1.3 branch
- python version: Python 3.7.9
- node.js version: 14

### Checklist

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
This version of Superset is no longer supported, and the cascading filgers feature has been significantly revamped since it was opened. If anyone is still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
