### ISSUE TITLE
Chart loading issue on html iframe

### ISSUE THREAD

**Issue by snv1914** [apache/superset#15529]
Hi,

I am trying to load chart and dashboard inside iframe.
Displaying an error inside iframe.
Here, one chart is loading and other charts getting error inside iframe. 
Loading charts to anonymous user inside iframe issue:
![image](https://user-images.githubusercontent.com/4299134/124297457-b5f19900-db78-11eb-8825-7a17205cbd84.png)

Also showing cookie related issues:
![image](https://user-images.githubusercontent.com/4299134/124296862-0ddbd000-db78-11eb-86a6-4ad1f2f3f60b.png)

Also used this SESSION_COOKIE_SAMESITE = "None" in superset/config.py.
But not worked.

But same url, at external window for anonymous user, all charts are displaying correctly:
![image](https://user-images.githubusercontent.com/4299134/124297928-44661a80-db79-11eb-876f-3005d61f0d37.png)

can someone please help to resolve charts loading issue inside iframe.

Thanks

**Comment by etr2460** [comment]
Do you have domain sharding enabled? if so, you may need to configure cross-site cookies for the other domains you shard to as well

**Comment by rusackas** [comment]
Looks like this thread has an open question that's gone unanswered for over a year, so we'll call this one closed. Please update the context on the issue if you'd like to revisit/reopen the issue around a more current version of Superset. Thanks!
