### ISSUE TITLE
[SQLLab] query history and preview not working when upgrading to v1.2

### ISSUE THREAD

**Issue by thetko85** [apache/superset#15538]
- When using the apache/superset:1.2.0 image, the query history and preview tabs in the sqllab view are blank.

what you expected to happen.

- Query history tab should show the historical queries and preview should show the preview of the table

Note:
The actual query history view actually works and lists the historical queries correctly. ie: "superset/sqllab/history/"

what actually happens.

#### Screenshots

![query-history](https://user-images.githubusercontent.com/10606114/124402301-c705fa00-dd72-11eb-8f48-e008ce600f7f.png)

#### How to reproduce the bug

1. Go to 'sqllab'
2. Choose a schema, table 
3. Click on Query history is blank
4. Click on Preview is blank

### Environment

(please complete the following information):

- superset version: 1.2.0
- python version: 3.7.9

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by shashankkoppar** [comment]
I am facing the same issue as well! I am getting this error message when selecting the preview. 

![image](https://user-images.githubusercontent.com/14154688/126968644-e1acb8cc-76ca-406b-b7b0-a182fa57c9c3.png)

**Comment by shashankkoppar** [comment]
How can I make it load https endpoint instead of http one?

**Comment by connorwang** [comment]
We're having the same issue :( Running on K8s (Rancher).

**Comment by yl2982** [comment]
Go to `superset-frontend/src/components/Tabs/Tabs.tsx` and remove 'animated' property can simply solve the problem.
`Tabs.defaultProps = {
  fullWidth: true,
};`
