### ISSUE TITLE
[dashboard]Broken OMNIBAR feature

### ISSUE THREAD

**Issue by kamalkeshavani-aiinside** [apache/superset#15539]
This experimental feature is broken in latest versions.
https://github.com/apache/superset/pull/6745

### Expected results
When typing in Omnibar, a dropdown should appear to select from search results.

### Actual results
The window with search text box and dropdown is very small, making it hard to use the dropdown.

#### Screenshots
From PR:
![image](https://user-images.githubusercontent.com/74634977/124430089-b0c76080-dda9-11eb-9d4b-ede69fcd8666.png)

Current situation in Master:
![image](https://user-images.githubusercontent.com/74634977/124430176-cdfc2f00-dda9-11eb-90bf-30e90f56953e.png)

#### How to reproduce the bug

1. Enable `OMNIBAR` feature flag.
2. Go to any dashboard and press Cmd + K
3. Type any text and it should show available dashboards
![omnibar](https://user-images.githubusercontent.com/74634977/124429087-65608280-dda8-11eb-9b97-c46507a7cf4f.gif)
### Environment

- superset version: `master`
using image from docker hub

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I would also request a feature here:
Close the OMNIBAR when ESC key is pressed. Currently Omnibar cannot be closed without refreshing the page.

**Comment by junlincc** [comment]
sorry for breaking the feature, i didn't know this feature exists😅 , we will bring it back soon. 
@rosemarie-chiu @jinghua-qa please add this test case. 🙏

**Comment by geido** [comment]
I am having a look

**Comment by geido** [comment]
I am moving away from this one as I have got priority items to solve. I will wait for your decision concerning prioritization for this one @junlincc

**Comment by geido** [comment]
I am back on this one now
