### ISSUE TITLE
Welcome_dashboard_id/slug not passed to http calls

### ISSUE THREAD

**Issue by SimonSmeets** [apache/superset#15549]
When a user logs in that has a welcome dashboard assigned to it, the calls to fetch the corresponding data do not include the id/slug and thus fail to fetch the dashboard.
### Expected results

The welcome dashboard assigned to the user is shown

### Actual results

Unexpected error message is shown

#### Screenshots
error message:
![image](https://user-images.githubusercontent.com/26030809/124570703-6d233400-de47-11eb-9b77-f22c6b02e396.png)
calls: 
expected calls:
![image](https://user-images.githubusercontent.com/26030809/124571713-57fad500-de48-11eb-89ff-5c7c1b08061a.png)
![image](https://user-images.githubusercontent.com/26030809/124571645-46193200-de48-11eb-907b-82b3eef72fc6.png)

actual calls:
![image](https://user-images.githubusercontent.com/26030809/124571784-65b05a80-de48-11eb-9885-5db11b83f9c8.png)
![image](https://user-images.githubusercontent.com/26030809/124571839-7234b300-de48-11eb-9008-01d072c916d0.png)
![image](https://user-images.githubusercontent.com/26030809/124571887-79f45780-de48-11eb-8cef-12f59018c5e3.png)

#### How to reproduce the bug

1. Create dashboard
2. Create new user
3. Assign dashboard as welcome dashboard to new user
4. Log in as new user
### Environment

- superset version: `1.2.0`
- python version: `3.7.9`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Uses the latest docker image

**Comment by rusackas** [comment]
This version of Superset is no longer supported. If anyone is still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
