### ISSUE TITLE
[table&pivot table]conditional formatting 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#15559]
![image (1)](https://user-images.githubusercontent.com/67837651/124669232-e716e580-de66-11eb-83d7-37fce79af851.png)

As a table user, I would like to highlight cells by according to positive and negative values or using conditional formatting. 
for example, i would like to see cells that contain below zero temperature number are highlighted _in red_ as a visual warning indicator, vs. temperature above 0 are showed _in green_ as expected. The further the number is from the anchor point the darker the color should be. user should be able to set the anchor to besides zero as well.

**Comment by benkramer-paypay** [comment]
hello, was this implemented?

**Comment by ns-abhijeet-bajpai-89** [comment]
Hi @junlincc , how to do it? I need to work on If you could help me with the same, that would be really great.
