### ISSUE TITLE
[user flow]Improve Cloning Chart Flow

### ISSUE THREAD

**Issue by andrewscarani** [apache/superset#15562]
**Is your feature request related to a problem? Please describe.**
The current flow used to clone a chart allows for one to mistakenly overwrite the existing chart and isn't intuitive to new users. Current flow involves the following steps:
- Click `View chart in Explore` from chart's dropdown
- Click `Save`
- Click `Save as...` (This is the step that's often forgotten)
- And then begin to make changes to the chart

If you click `View chart in Explore` and then forget to save first, you may make changes to an existing chart someone else is using and thus cause issues in your instance.

**Describe the solution you'd like**
It would be great to have an item on the charts dropdown, right under "View query" called "Clone":
![Screen Shot 2021-07-06 at 4 10 39 PM](https://user-images.githubusercontent.com/4078980/124677175-b63dad00-de74-11eb-9737-004c6d22b8b2.png)
that, when clicked, brings-up the "Save As" modal for a chart (but without the radio button allowing you to rename the chart), and allows you to instantly clone the one you're looking at:
![Screen Shot 2021-07-06 at 4 12 24 PM](https://user-images.githubusercontent.com/4078980/124677289-f56bfe00-de74-11eb-931a-1b0cef88ec30.png)

An example of the "Clone" button existing on the dropdown menu in Chartio:
![Screen Shot 2021-07-06 at 4 10 08 PM](https://user-images.githubusercontent.com/4078980/124677120-a32add00-de74-11eb-99f9-f469345f077d.png)

**Comment by junlincc** [comment]
thanks for suggesting! we have a discussion thread in Superset roadmap repo, which is a bit outdated. https://github.com/apache-superset/superset-roadmap/issues/109 
all good ideas, but we are slow in implementing the solution. If you would like to open a PR that can cover most of the concerns in the thread, we are happy to help push it forward. 🙏

**Comment by andrewscarani** [comment]
Please don't close this issue.

**Comment by MarcinZegar** [comment]
Any progress on this?

**Comment by rusackas** [comment]
This isn't a bug, but a feature request. If anyone wants to open a PR that does this, that'd be great! Or, feel free to create a github discussion if you're looking to find additional support for it. Meanwhile, closing since it's been dormant for so long, and we're whittling the Issues backlog to actual bugs.
