### ISSUE TITLE
Add "Advanced Analytics" functionality from legacy charts to Time-Series ECharts

### ISSUE THREAD

**Issue by andrewscarani** [apache/superset#15564]
**Is your feature request related to a problem? Please describe.**
Creating a stacked bar chart with a period-over-period line chart overlaid on top is currently very difficult to do in Superset using the `Mixed Time Series Chart`, as it requires you to calculate period-over-period metrics as a series as part of your dataset, rather than allowing you to calculate it after-the-fact as part of chart-creation.

**Describe the solution you'd like**
It would be great to add the `Advanced Analytics` tab functionality (e.g. Rolling Window, Time Comparison, and pandas) to the ECharts Time-Series Charts (both single and mixed) as this is **incredibly** useful functionality, especially to easily create a YOY chart on top of a stacked bar chart (a very common chart type in many tools like Chartio, Excel, etc.)
![Screen Shot 2021-07-06 at 4 35 57 PM](https://user-images.githubusercontent.com/4078980/124678863-3fa2ae80-de78-11eb-8f6d-d4e942f6b07c.png)

E.g. in Chartio:
![Screen Shot 2021-07-06 at 4 34 51 PM](https://user-images.githubusercontent.com/4078980/124678782-17b34b00-de78-11eb-9da8-ad8e887f2aed.png)

**Describe alternatives you've considered**
Currently, we use the existing legacy `Line Chart`'s "Advanced Analytics" functionality to build a separate YOY chart (1 year time shift + percentage change) that we express separately from our bar chart, but it's not always as useful.

**Comment by junlincc** [comment]
https://github.com/apache-superset/superset-ui/pull/1170 

@andrewscarani hi! we actually have a PR open, please help review if you can :)

**Comment by andrewscarani** [comment]
@junlincc This is awesome! I'll try to review this some when I get some time

**Comment by zhaoyongjie** [comment]
I have finished advanced analytics on the time-series chart. @junlincc @andrewscarani  

server-side codes at: apache/superset#15279
client-side codes at: https://github.com/apache-superset/superset-ui/pull/1170


### YTD(year-to-date) + time shift
![image](https://user-images.githubusercontent.com/2016594/124909695-58989480-e01d-11eb-940f-0c459e22fdbf.png)

### YoY(year-over-year) / MoM / QoQ ....
![image](https://user-images.githubusercontent.com/2016594/124910780-8b8f5800-e01e-11eb-8090-11e657a937a4.png)

**Comment by zhaoyongjie** [comment]
closed by https://github.com/apache/superset/pull/15279

**Comment by andrewscarani** [comment]
I'm seeing that this was completed for all time-series charts, except for the Mixed Time Series chart

**Comment by andrewscarani** [comment]
@junlincc Is it possible to reopen this issue until support has been added to the `Mixed Time Series Chart` as well?
