### ISSUE TITLE
Add "Extra Controls" to "Time-Series (Bar) Chart"

### ISSUE THREAD

**Issue by andrewscarani** [apache/superset#15565]
**Is your feature request related to a problem? Please describe.**
Legacy bar chart has a cool functionality to allow the end-viewer to toggle between a "Grouped" or "Stacked" view of a bar chart by enabling "Extra Controls" under "Customize"

![Screen Shot 2021-07-06 at 4 39 07 PM](https://user-images.githubusercontent.com/4078980/124679099-b049cb00-de78-11eb-9e31-cbce8e581843.png)

![Screen Shot 2021-07-06 at 4 38 55 PM](https://user-images.githubusercontent.com/4078980/124679081-a922bd00-de78-11eb-977a-d567348949c0.png)

**Describe the solution you'd like**
It would be great to add this feature to both the `Time-Series Chart` and `Mixed Time-Series Chart` to allow end-users to more flexibly change their view of data in the new ECharts.

**Comment by junlincc** [comment]
we have the same feature goal! the only thing im not sure is having the radio buttons shown by checking the EXTRA CONTROLS box, since this behavior is inconsistent with others.

**Comment by jhult** [comment]
It would be great to have this feature!

This is related to #16298 (which is for area charts). It has more details and open pull requests.

**Comment by andrewscarani** [comment]
Bump! This is still a useful feature to have

**Comment by rusackas** [comment]
I think this is a fine idea. That said, it's gone stale and isn't a bug, so I feel obliged to close it. Please open an "Ideas" thread in Github Discussions to make a feature request, or open a PR to implement it, and we'll be happy to help it along!
