### ISSUE TITLE
Accessing database is blocked by Chrome's new policy when deploying Superset using K8s / Helm

### ISSUE THREAD

**Issue by fzhan** [apache/superset#15570]
When deploy using kubernete/helm, ingress being handled by external ingress-controller using https/TLS, accessing to datatbase is blocked by chrome's new policy "strict-origin-when-cross-origin"

### Expected results
The requesting url is https://mydomain/api/v1/database/available
The response url should have been https://mydomain/api/v1/database/available/

### Actual results
The response url is http://mydomain/api/v1/database/available/

#### How to reproduce the bug

1. Install using helm, config with external ingress controller for https
2. Click on Data > Database
3. Click on + Database

### Environment
Chrome

- superset version: `apache/superset:latest`

**Comment by junlincc** [comment]
@dpgaspar do you happen to know?

**Comment by rusackas** [comment]
This seems to be more of a configuration question than a bug report, so I'd suggest taking this to a "Q&A / Help" thread on Discussions or join the #deploying-superset channel on Slack.
