### ISSUE TITLE
[Dashboard] Dashboard image download does not contain image I inserted in CSS editor

### ISSUE THREAD

**Issue by rosemarie-chiu** [apache/superset#15596]
I inserted a image in markdown and that image is not in the dashboard image download

### Expected results
Image inserted from CSS template contain in dashboard download image

### Actual results
Image is blank

#### How to reproduce the bug
1. In markdown: `<div class="image-container"></div>`
2. In CSS editor: 
```
.image-container {
  background-image: url('https://cdn.vox-cdn.com/thumbor/5VGuWp5szQWExUnPTbsA0wXYoQI=/1400x1050/filters:format(png)/cdn.vox-cdn.com/assets/755523/netflix-logo-705px.png');
  background-size:cover;
  background-repeat:no-repeat;
  width:100%;
  height:100%;
} 
```
https://user-images.githubusercontent.com/52086618/124988101-6e449480-dff2-11eb-9b2c-24963051e92b.mp4

**Comment by junlincc** [comment]
there are two ways to insert images to dashboard, 1. markdown syntax(most case) e.g. ![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png) 2.css editor. only image inserted thru 1 can be downloaded. 
given there's a workaround, we will not prioritize this issue atm. please comment in the thread which route your normally take to help us adjust prioritization.

**Comment by cchristofr** [comment]
Hi all
I've have also this problem.
If possible I use markdown, but I also have to use CSS to put images over charts in the dashboard. So these images are not exported if:
 - I download the chart as an image
  - I download the dashboard as an image

**Comment by geido** [comment]
@yousoph FYI

**Comment by chkang-idk2** [comment]
I've have also this problem.

**Comment by geido** [comment]
Hello. The image download is being reworked completely here https://github.com/apache/superset/pull/29272. Closing this for now and keeping an eye on this use case.
