### ISSUE TITLE
[native-filter][ux]hard to specify the min and max in slider when the range is huge

### ISSUE THREAD

**Issue by junlincc** [apache/superset#15605]
Currently, if user wants to set a very specific range filter(e.g. 150-18,999) in a wide range of number(e.g. min=0 max=20,000) using the slider, it's extremely hard by just moving the points. workaround is to use arrow on keyboard. but to get to min=150, user has to hit 150 times, and max = 19,000 users has to hit keyboard close to a 1,000 times to get there...

Propose: also support number input in the background? 
Ideas are welcome! 

@yousoph thanks for the feedback ❣️

**Comment by rusackas** [comment]
Closing since it's not a bug and has been stale for so long. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
