### ISSUE TITLE
Date Formatting in Pivot Table Doesn't Work? 

### ISSUE THREAD

**Issue by matthewphua** [apache/superset#15604]
The date formatting for a pivot table does not appear to be working 
### Expected results

Date/timestamp values to be properly formatted by the customize -> date formatting dropdown.

### Actual results

Nothing gets affected 

#### Screenshots

https://user-images.githubusercontent.com/85198947/125004652-d86b3280-e00e-11eb-9d60-df9cdee2a5a1.mov

#### How to reproduce the bug
1. Create a pivot table with time columns 
2. Navigate to customize tab and change dates
3. See error

**Comment by junlincc** [comment]
Thanks Matt for filing! we are working on it.

**Comment by kgabryje** [comment]
We don't have date formatting in Pivot Table v2. Should I add it to our todo/must have list?

**Comment by junlincc** [comment]
> Should I add it to our todo/must have list?

Yes, to-do and must-have, and only in Pivot Table v2. Thanks!

**Comment by kgabryje** [comment]
Date formatting seems to work fine in Pivot Table v1. @matthewphua Are you sure that you used a temporal column rather than string column? cc @junlincc 

https://user-images.githubusercontent.com/15073128/125274531-5892e000-e30e-11eb-93ed-cd23177c988a.mov

**Comment by kgabryje** [comment]
Closed by https://github.com/apache/superset/pull/15742

**Comment by cajitkr** [comment]
Please update us on this as this feature is important when displaying the date , please let us know if there is any workaround .

**Comment by gmilman** [comment]
It would also be great to display actual dates in the core of the pivot table; at the moment when i do max(date) it displays the date as a long integer
