### ISSUE TITLE
Unable to generate chart from Snowflake database dataset - Time field is not getting substituted

### ISSUE THREAD

**Issue by salano21** [apache/superset#15601]
<img width="1632" alt="Screen Shot 2021-07-08 at 6 14 49 PM" src="https://user-images.githubusercontent.com/11878458/125001511-744d6c00-e018-11eb-83f4-e4e35bee5bd4.png">

### Expected results
 Generated query has time field substituted correctly.
what you expected to happen.

### Actual results
```
Snowflake Error
000904 (42000): 019d756b-0502-2751-0000-66f9009ef836: SQL compilation error: error line 1 at position 7 invalid identifier '"DATE_TRUNC('DAY', {COL})"'
```

This may be triggered by:
Issue 1002 - The database returned an unexpected error. 

See less
what actually happens.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by salano21** [comment]
I am not sure if this needs some custom connection parameters. Seeing the error it appears python f-string is not getting substituted.

**Comment by yousoph** [comment]
Unable to repro this issue, so closing it. If you're still running into it, please reopen with more details. Thanks!
