### ISSUE TITLE
How do I get current datetime in the SQLTemplate?

### ISSUE THREAD

**Issue by liuyong888** [apache/superset#15613]
@zhaoyongjie 
Hi
**Is your feature request related to a problem? Please describe.**
Superset 1.1.0
I want to get current datetime in SQL Template

**Additional context**
That seems like the wrong way to go.
It says datetime is Undefined.
![image](https://user-images.githubusercontent.com/45752479/125019981-90015280-e0aa-11eb-9303-6ffca38347ec.png)

**Comment by srinify** [comment]
Was this documentation useful at all?

https://superset.apache.org/docs/installation/sql-templating#available-macros

**Comment by zhaoyongjie** [comment]
we can make macros in the `config.py`, for instance:

```
from datetime import datetime

def current_datetime():
    return datetime.now().strftime("%Y-%m-%d")

JINJA_CONTEXT_ADDONS = {
    "current_datetime": current_datetime
}
```

Then use in SQLLab

```
select ....
from ....
where start > {{ current_datetime() }}
```
