### ISSUE TITLE
[Upcoming UI/UX change]Homepage v2

### ISSUE THREAD

**Issue by junlincc** [apache/superset#15625]
Based on user feedback and research, we are making following changes on current Homepage in Superset. Implementation will start on **_July 15_**, please comment before the date if you have any ideas, questions, objections. 

**General** 
1. Show 5 cards per row in each section, instead of 3; dynamically adjust the number of card depends on the screen size
2. Remove Examples from Recents section and add Examples to Dashboards, Charts and Saved queries
3. Move Save queries section to the bottom 
4. Tab selection in all sections will be 'sticky'

**First time experience** 
1. Show Example cards in Dashboards and Charts 
2. Recents collapses by default to avoid showing an empty section
3. Saved queries collapses by default to avoid showing an empty section

<img width="465" alt="Screen Shot 2021-07-09 at 3 22 50 PM" src="https://user-images.githubusercontent.com/67837651/125142822-850be980-e0cd-11eb-8147-ce2b93196424.png">

**Comment by ktmud** [comment]
These changes make sense.

**Comment by srinify** [comment]
Love it! Excited for this

**Comment by aloneworld** [comment]
- [ ] Thanks. And When could enable Bar Chart 's cross-filtering

**Comment by junlincc** [comment]
> * When could enable Bar Chart 's cross-filtering

Mid-Late August! only on Echarts(time-series bar) though, major reconstruction on Time-series chart ATM. @aloneworld

**Comment by junlincc** [comment]
@pkdotson 
just a quick note you might be aware of it already. in v1 currently, charts/dashboards user created are showing in Examples tab. let's make sure it's fixed in v2. 🙏

**Comment by mistercrunch** [comment]
One super minor comment would be around using vertical dots for the sub-menu as opposed to horizontal ones to save a few pixels. I think in general we should standardize on the vertical dots for sub-menu triggers.

**Comment by EBoisseauSierra** [comment]
I'm afraid I'm a little late to the party, but I believe the UX could be a bit improved by preselecting the left-most tab (that “makes sense”) by default.

Indeed, preselecting the right-most tab doesn't feel very intuitive to me.

Thus, I'd suggest to pre-select:

1. _Favourite_ if any,
2. else _Mine_ if any,
3. else _Example_ if any,
4. else _Favourite_ (left-most default).
