### ISSUE TITLE
[native filters] Default value of time range filter "No filter" is not accepted

### ISSUE THREAD

**Issue by adam-stasiak** [apache/superset#15637]
Initial value No Filter should be accepted as it is valid filter value.

### Expected results

Initially chosen value - no filter should be accepted. Going back to No filter value from any other chosen also should work.

### Actual results

Initial value of default value filter is not processed. If I set Last day filter and switch back to No filter - I cannot proceed.

#### Screenshots

![image](https://user-images.githubusercontent.com/25153919/125346155-b1d43100-e359-11eb-8f8a-1f3ea4ccdabf.png)

#### How to reproduce the bug

1. Go to dashboard
2. Add native filter
3. Select Time range filter and any filter name
4. click on Filter has default value
5. Set any value of filter and switch back to no filter.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by michael-s-molina** [comment]
@adam-stasiak @junlincc Currently the "No Filter" is the visual representation of no value assigned. It's the same as an empty Select. Unless we decide to change how the component behaves, this does not seem to be a bug.
