### ISSUE TITLE
[native filters] Numerical range initial default value should be accepted as filled one

### ISSUE THREAD

**Issue by adam-stasiak** [apache/superset#15638]
Initial value of this filter which is expressed by edge values of data should be accepted as default one.
### Expected results
Accept initial value retrieved after click on Filter has default value.
### Actual results
Value is not accepted.
#### Screenshots

![image](https://user-images.githubusercontent.com/25153919/125346525-25763e00-e35a-11eb-878c-b46e4b4bc177.png)
#### How to reproduce the bug

1. Go to any dashboard
2. Add native filter with filter type numerical range
3. Fill rest of the required filled
4. Under basic section click on Filter has default value -> check retrieved value (should be not 0 as maximum)

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by jinghua-qa** [comment]
This issue maybe related too:
when numerical range filter is required, can not set as max range
<img width="1792" alt="Screen Shot 2021-07-13 at 7 44 33 PM" src="https://user-images.githubusercontent.com/81597121/125552769-154e3729-9095-494f-9575-da2e496899f2.png">

**Comment by michael-s-molina** [comment]
@villebro I remember I talked to you about this behavior and you mentioned it was a design decision when implementing the plugin. Can you post what was the reasoning so we can check if it needs to change?

**Comment by villebro** [comment]
> @villebro I remember I talked to you about this behavior and you mentioned it was a design decision when implementing the plugin. Can you post what was the reasoning so we can check if it needs to change?

The motivation for leaving the edge values as undefined filters is as follows:
- We need a way to leave the filter undefined similar to how can be done in all other native filters
- By making the edge values emit filters that include both the lower and upper bound, we add filters to the query object that don't change the result but will cause a cache miss (=a filter clause that is always true).

I agree that the current design isn't optimal - however, in the absence of an alternative mechanism for leaving 1) the lower bound 2) the upper bound or 3) both bounds undefined, I think this is the best solution for now.
