### ISSUE TITLE
[native filters] Filter has default value checkbox value is not remembered after revisit

### ISSUE THREAD

**Issue by adam-stasiak** [apache/superset#15639]
When I revisit native filter configuration then I can't see that this filter was configured with default value. When I click on this again - the previous value is retrieved.
### Expected results

Component should show that someone configured this filter with some value.
### Actual results

Component state is not set correctly. I have to click on this.
#### Screenshots

https://user-images.githubusercontent.com/25153919/125347356-1d6ace00-e35b-11eb-9c94-22a3ad9e6981.mov

#### How to reproduce the bug

1. Go to dashboard
2. Add native filter with value added in "Filter has default value"
3. Save
4. Revisit filters configuration panel and check if checkbox is set.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
Welcome back to our issue page and thanks for spotting it Adam! @adam-stasiak 
Hi @michael-s-molina, adding it to backlog, just need to make sure this is fixed by end of July is fine. Many thanks!

**Comment by michael-s-molina** [comment]
This was fixed here https://github.com/apache/superset/pull/15572. But this PR also introduced another bug when canceling that was fixed here https://github.com/apache/superset/pull/15644
