### ISSUE TITLE
Chart name change could be reflected in Altered section

### ISSUE THREAD

**Issue by adam-stasiak** [apache/superset#15641]
**Is your feature request related to a problem? Please describe.**
When I edit name of chart I would like to have this change saved. Without click on SAVE button I will lost my change.
**Describe the solution you'd like**
When I edit name and click enter then this change should be displayed in Altered component to show me that it will be saved after click on save. 
After edition via this component we could display altered to indicate that change was commited.
![image](https://user-images.githubusercontent.com/25153919/125350117-9ae40d80-e35e-11eb-9bcd-7efbb3fb5f6f.png)
![image](https://user-images.githubusercontent.com/25153919/125350130-a0415800-e35e-11eb-9c2b-740467ac1f03.png)

**Describe alternatives you've considered**
Save name when user leaves this edit field.

**Additional context**
We have three ways of name change on this view:
- via mentioned component
- via Edit chart properties button
- via Save name

Each of them except 1. option is clear dialog showing that you have to Click on save. it is smart because this change could be destructive and could affect many dashboards and users. having this info kept in altered section could be safe in terms of not modifying too much.
<img width="879" alt="Zrzut ekranu 2021-07-12 o 22 13 54" src="https://user-images.githubusercontent.com/25153919/125350237-c9fa7f00-e35e-11eb-9ce6-d520d90b6aa8.png">

**Comment by rusackas** [comment]
This is indeed the case nowdays, it seems! Done!
