### ISSUE TITLE
The chart in the report screenshot is sent before the animation is finished.

### ISSUE THREAD

**Issue by u-aiaa** [apache/superset#15649]
The chart in the report screenshot is sent before the animation is finished.

### Expected results

Take a screenshot of the chart with the chart animation finished and send the report.

### Actual results

Before the chart animation is finished, a screenshot is taken and a report is sent.

#### Screenshots

Image sent as a report

![report](https://user-images.githubusercontent.com/72971834/125386015-893e4c80-e3d6-11eb-8f8b-c2b4f2623c50.png)

### Environment

- superset version: Superset 1.2.0 + https://github.com/apache/superset/blob/f52b6715cf2d9da8455a7a62d0c1d9cab64bf5aa/superset/utils/webdriver.py
- python version: Python 3.7.9
- node.js version:

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
    - There was no stack trace.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Pull request submitted. https://github.com/apache/superset/pull/15610

**Comment by junlincc** [comment]
@u-aiaa can you clarify what "animation" means in a video or gif? thanks!

**Comment by u-aiaa** [comment]
@junlincc 

This is a video of the chart when viewed in a browser.

![animation](https://user-images.githubusercontent.com/72971834/125552121-795fbf06-19d0-48e2-940f-511aa5b077ff.gif)

When submitting a report, I wondered if a screenshot would be taken before this animation was finished. Therefore, I added a wait time to the pull request.
Instead of a wait time, should it not animate when sending a report?

**Comment by junlincc** [comment]
makes sense! thanks!

**Comment by u-aiaa** [comment]
#15610 merged.
