### ISSUE TITLE
[Bug] Total values overlap X-axis labels on stacked Time-series Bar Chart

### ISSUE THREAD

**Issue by nickdomnin** [apache/superset#15656]
## Screenshot

![Screenshot from 2021-07-13 11-57-03](https://user-images.githubusercontent.com/39625071/125431455-743e1891-3890-47bd-85a3-d094fe298178.png)

## Description

On Time-series Bar Chart in stacked mode total values of bars may overlap X-axis labels and make them unreadable if total values are negative. This happens for all X Ticks layouts.

## How to reproduce
1. Create Time-series Bar Chart on `cleared_sales_data`
2. At Time block select `order_date` as time column, month at Time grain and custom time range from `2004-01-01` to `2004-12-31`
3. Set `-SUM(sales)` as metric and select `deal_size` in GROUP BY
4. Also turn on Bar values and Stacked bars at Customize tab
5. Press RUN

**Comment by junlincc** [comment]
hey @nickdomnin thanks for filing the issue, could you specify the version you are on? latest master, 1.2, 1.1? thanks

**Comment by nickdomnin** [comment]
@junlincc Reproducible on all mentioned versions: 1.1, 1.2.
Latest master (9c854ff1f1ab80b26438a3b6d91ca9b44b5f2a7a) node container now crushes for me with *FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory*

**Comment by rusackas** [comment]
This does not seem to be an issue in 2.0.1. Not sure about 1.5.x, but I think we can call this cloesed, as the bar values now appear at the top of the chart and there's no chance of collision
