### ISSUE TITLE
Add a dropdown list for comparator/filter value in Explore's filters section

### ISSUE THREAD

**Issue by jessicaxyl** [apache/superset#15677]
It would be great if there's a dropdown list as you type the values in the Explore's filter section. Just like how there's a dropdown for the column and operator part, so that users would have an idea if the value they are inserting exists or not.

Here's an example of what I mean. Below is a screenshot of the dashboard native filter. And the filter section in Explore should have this dropdown feature too.

![image](https://user-images.githubusercontent.com/81961241/125601846-dabe73ff-e527-47e7-94e3-7c45438f1cad.png)

Expected Result
![image](https://user-images.githubusercontent.com/81961241/125601873-f8588fe4-360e-4424-acd2-3979c2b937f9.png)

I'm assuming it can be done in superset/superset-frontend/src/explore/components/controls/FilterControl/AdhocFilterEditPopoverSimpleTabContent/index.tsx ?
Along the lines of line 419-457?

**Comment by junlincc** [comment]
Try checking the autocomplete box in Edit Dataset modal? 
<img width="1206" alt="Screen Shot 2021-07-14 at 11 49 25 AM" src="https://user-images.githubusercontent.com/67837651/125676476-b0730d53-f5be-448f-83ca-0e797fbf89e6.png">

**Comment by junlincc** [comment]
see https://github.com/apache/superset/issues/15694

**Comment by jessicaxyl** [comment]
Thank you!
