### ISSUE TITLE
[dashboard] can not discard changes in a empty dashboard 

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15673]
After create a new dashboard through through global + button or +dashboard button, click on 'DISCARD CHANGE' has no effect

### Expected results

click on 'DISCARD CHANGE' will bring user out of dashboard edit mode

### Actual results

click on 'DISCARD CHANGE' has no effect, user still at dashboard edit mode

#### Screenshots

https://user-images.githubusercontent.com/81597121/125559236-ebb18f6a-851f-4206-a88c-fde7ab410335.mov

#### How to reproduce the bug

1. Click on global + button and create new dashboard or click on +dashboard in dashboard page
2. Do not add anything to the new dashboard and click on 'DISCARD CHANGE' in dashboard edit mode
3.See error

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
consider this is a major ux issue in dashboard creation flow. @geido can you take a look?

**Comment by geido** [comment]
Sure, having a look now
