### ISSUE TITLE
superset-frontend can't run

### ISSUE THREAD

**Issue by piewaer** [apache/superset#15681]
### Expected results

I want to run the superset-frontend only.

### Actual results
Get lots of errors

#### Screenshots
![image](https://user-images.githubusercontent.com/87263497/125627666-d5f72ce0-591f-44aa-bc77-9a745e58047c.png)

#### How to reproduce the bug
1. In the superset-frontend folder, npm ci
2. npm run dev-server
3. 98% of the process, get lots of errors, includes the type error of the data and the error not found by the module

### Environment
- superset version: `Latest version - https://github.com/apache/superset -master branch`
- python version: `python --version`
- node.js version: `14.17.`
- npm version: `7.19.1`

### Specific error report
[error info.txt](https://github.com/apache/superset/files/6816368/error.info.txt)

**Comment by piewaer** [comment]
Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
98% after emitting SizeLimitsPluginNo type errors found
Version: typescript 4.0.3
Time: 38916ms
× ｢wdm｣:    10567 modules

WARNING in ./src/featureFlags.ts 1:295-359
"export 'FeatureFlagMap' was not found in '@superset-ui/core'

WARNING in ./node_modules/@superset-ui/chart-controls/esm/types.js 1:0-43
"export 'Metric' was not found in '@superset-ui/core'

WARNING in ./src/components/Icons/index.tsx 157:0-20
"export 'default' (reexported as 'IconType') was not found in './IconType'

WARNING in ./src/utils/textUtils.ts
Module not found: Error: Can't resolve '../../../superset_text' in 'E:\someOthers\superset\superset-master\superset-frontend\src\utils'

ERROR in ./src/datasource/DatasourceEditor.jsx 113:2
Module parse failed: Unexpected token (113:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| const checkboxGenerator = (d, onChange) => (
>   <CheckboxControl value={d} onChange={onChange} />
| );
| const DATA_TYPES = ['STRING', 'NUMERIC', 'DATETIME'];

ERROR in ./src/visualizations/TimeTable/TimeTable.jsx 118:10
Module parse failed: Unexpected token (118:10)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         },
|         Header: () => (
>           <>
|             {columnConfig.label}{' '}
|             {columnConfig.tooltip && (

ERROR in ./src/middleware/loggerMiddleware.js 119:45
Module parse failed: Unexpected token (119:45)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   }
|
>   if (eventData.target_id && dashboardLayout?.present?.[eventData.target_id]) {
|     const { meta } = dashboardLayout.present[eventData.target_id];
|     // chart name or tab/header text

ERROR in ./src/visualizations/FilterBox/FilterBox.jsx 122:27
Module parse failed: Unexpected token (122:27)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   }
|
>   onCloseDateFilterControl = () => this.onFilterMenuClose(TIME_RANGE);
|
|   getControlData(controlName) {

ERROR in ./src/chart/chartAction.js 127:43
Module parse failed: Unexpected token (127:43)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   const allowDomainSharding =
|     // eslint-disable-next-line camelcase
>     domainShardingEnabled && requestParams?.dashboard_id;
|   const url = getExploreUrl({
|     formData,

ERROR in ./src/dashboard/components/PropertiesModal/index.jsx 142:41
Module parse failed: Unexpected token (142:41)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     const colorChoices = getCategoricalSchemeRegistry().keys();
|     const { json_metadata: jsonMetadata } = this.state.values;
>     const jsonMetadataObj = jsonMetadata?.length
|       ? JSON.parse(jsonMetadata)
|       : {};

ERROR in ./src/dashboard/actions/dashboardState.js 185:54
Module parse failed: Unexpected token (185:54)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|       const { chartId } = filter;
|       const componentId = filter.directPathToFilter.slice().pop();
>       const directPathToFilter = (layout[componentId]?.parents || []).slice();
|       directPathToFilter.push(componentId);
|       dispatch(updateDirectPathToFilter(chartId, directPathToFilter));

ERROR in ./src/explore/exploreUtils/index.js 219:57
Module parse failed: Unexpected token (219:57)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| }) => {
|   const buildQuery =
>     getChartBuildQueryRegistry().get(formData.viz_type) ??
|     (buildQueryformData =>
|       buildQueryContext(buildQueryformData, baseQueryObject => [

ERROR in ./src/visualizations/TimeTable/transformProps.js 23:28
Module parse failed: Unexpected token (23:28)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   const { columnCollection = [], groupby, metrics, url } = formData;
|   const { records, columns } = queriesData[0].data;
>   const isGroupBy = groupby?.length > 0;
|
|   // When there is a "group by",

ERROR in ./src/visualizations/FilterBox/controlPanel.jsx 25:38
Module parse failed: Unexpected token (25:38)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| const appContainer = document.getElementById('app');
| const bootstrapData = JSON.parse(appContainer.getAttribute('data-bootstrap'));
> const druidIsActive = !!bootstrapData?.common?.conf?.DRUID_IS_ACTIVE;
| const druidSection = druidIsActive
|   ? [

ERROR in ./src/components/CopyToClipboard/index.jsx 39:12
Module parse failed: Unexpected token (39:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| const defaultProps = {
>   copyNode: <span>Copy</span>,
|   onCopyEnd: () => {},
|   shouldShowText: true,

ERROR in ./src/showSavedQuery/index.jsx 39:4
Module parse failed: Unexpected token (39:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
|   ReactDom.render(
>     <div>
|       <Form
|         schema={config.JSONSCHEMA}

ERROR in ./src/explore/index.jsx 42:16
Module parse failed: Unexpected token (42:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| );
|
> ReactDOM.render(<App store={store} />, document.getElementById('app'));
|

ERROR in ./src/components/ErrorBoundary/index.jsx 50:8
Module parse failed: Unexpected token (50:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|       const firstLine = error.toString();
|       const message = (
>         <span>
|           <strong>{t('Unexpected error')}</strong>
|           {firstLine ? `: ${firstLine}` : ''}

ERROR in ./src/explore/components/ControlHeader.jsx 53:8
Module parse failed: Unexpected token (53:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     if (this.props.hovered) {
|       return (
>         <span
|           css={theme => css`
|             position: absolute;

ERROR in ./src/SqlLab/App.jsx 74:24
Module parse failed: Unexpected token (74:24)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|       });
|
>       if (subset.sqlLab?.user) {
|         // Don't persist the user.
|         // User should really not be stored under the "sqlLab" field. Oh well.

ERROR in ./src/dashboard/components/Dashboard.jsx 76:21
Module parse failed: Unexpected token (76:21)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| class Dashboard extends React.PureComponent {
>   static contextType = PluginContext;
|
|   static onBeforeUnload(hasChanged) {

ERROR in ./src/components/Select/OnPasteSelect.jsx 79:11
Module parse failed: Unexpected token (79:11)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   render() {
|     const { selectWrap: SelectComponent, ...restProps } = this.props;
>     return <SelectComponent {...restProps} onPaste={this.onPaste} />;
|   }
| }

ERROR in ./src/explore/components/controls/TextAreaControl.jsx 87:8
Module parse failed: Unexpected token (87:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|       }
|       return (
>         <TextAreaEditor
|           mode={this.props.language}
|           style={style}

ERROR in ./src/components/AsyncSelect/index.jsx 88:6
Module parse failed: Unexpected token (88:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   render() {
|     return (
>       <Select
|         placeholder={this.props.placeholder}
|         options={this.state.options}

ERROR in ./src/dashboard/actions/hydrate.js 90:15
Module parse failed: Unexpected token (90:15)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   // Priming the color palette with user's label-color mapping provided in
|   // the dashboard's JSON metadata
>   if (metadata?.label_colors) {
|     const scheme = metadata.color_scheme;
|     const namespace = metadata.color_namespace;
i ｢wdm｣: Failed to compile.

**Comment by junlincc** [comment]
moving issue to Q&A
