### ISSUE TITLE
"ERROR: Failed to fetch schemas allowed for csv upload in this database!" when trying to upload CSV

### ISSUE THREAD

**Issue by fuomag9** [apache/superset#15692]
"ERROR: Failed to fetch schemas allowed for csv upload in this database!" when trying to upload CSV

### Expected results

No error should happen when uploading CSV to the default docker-compose database. 

### Actual results

I receive an error stating `ERROR: Failed to fetch schemas allowed for csv upload in this database! Please contact your Superset Admin!`

Terminal error:

```
192.168.165.1 - - [14/Jul/2021:19:51:12 +0000] "GET /csvtodatabaseview/form HTTP/1.1" 200 27340 "http://192.168.165.128:8088/databaseview/list/?pageIndex=0&sortColumn=changed_on_delta_humanized&sortOrder=desc" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"
superset_app            | can only concatenate str (not "list") to str
superset_app            | Traceback (most recent call last):
superset_app            |   File "/app/superset/views/core.py", line 3121, in schemas_access_for_csv_upload
superset_app            |     schemas_allowed = database.get_schema_access_for_csv_upload()
superset_app            |   File "/app/superset/models/core.py", line 675, in get_schema_access_for_csv_upload
superset_app            |     allowed_databases += extra_allowed_databases
superset_app            | TypeError: can only concatenate str (not "list") to str
superset_app            | 2021-07-14 19:51:12,677:ERROR:superset.views.core:can only concatenate str (not "list") to str
superset_app            | Traceback (most recent call last):
superset_app            |   File "/app/superset/views/core.py", line 3121, in schemas_access_for_csv_upload
superset_app            |     schemas_allowed = database.get_schema_access_for_csv_upload()
superset_app            |   File "/app/superset/models/core.py", line 675, in get_schema_access_for_csv_upload
superset_app            |     allowed_databases += extra_allowed_databases
superset_app            | TypeError: can only concatenate str (not "list") to str
```

#### Screenshots

![image](https://user-images.githubusercontent.com/1580624/125684249-4dc971ae-f535-42c2-b720-10cd3a32803c.png)

#### How to reproduce the bug

1. Enable `data upload` for the default database
2. Go to http://IP:8088/csvtodatabaseview/form

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

See https://github.com/apache/superset/blob/070f0b6cb2a1c3385bc2a7ed2448aa7eb1251666/docker-compose-non-dev.yml for the used versions since I ran this with docker-compose

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by danzinger** [comment]
Same problem here. Also the `Edit Database` UI has changed and is not consistent with the [tutorial](https://superset.apache.org/docs/creating-charts-dashboards/exploring-data) anymore.

**Comment by junlincc** [comment]
`superset version` means latest master? @danzinger 

https://www.youtube.com/watch?v=G7kVeONipsQ mind double checking if this tutorial work for you?

**Comment by fuomag9** [comment]
> Edit: The value of the field `schemas_allowed_for_csv_upload` changes anytime the modal is opened again. There seem to be a problem with escaping the value which may ruin the datatype of the value whend parsed, resulting in the problem.
> 
> 
> 
> Value on first opening: `"[]"`
> 
> Value on second opening: `"\"[]\""`
> 
> Value on third opening: `"\"\\\"[]\\\"\""`
> 
> 

I've noticed this as well, every time it seems to increase in terms of expansion (but the issue still remains even if blank)

**Comment by danzinger** [comment]
I am not the OP, but for me this happens on version `0.999.0dev` which was installed by `docker-compose` when following [the official install with docker guide](https://superset.apache.org/docs/installation/installing-superset-using-docker-compose). Did not see that I wasn't on the latest stable release then. Shouldn't the latest master be pulled by `docker-compose`?

docker Version: `20.10.7` 
docker-compose version: `1.29.2`

**Comment by yousoph** [comment]
Created #15716 for the issue reported for the schemas_allowed_for_csv_upload, thanks 

For the CSV upload itself, do you have anything set in the schemas_allowed_for_csv_upload when seeing this error?

**Comment by fuomag9** [comment]
> Created #15716 for the issue reported for the schemas_allowed_for_csv_upload, thanks 
> 
> 
> 
> For the CSV upload itself, do you have anything set in the schemas_allowed_for_csv_upload when seeing this error? 

Nothing more than the first mandatory modal opening for allowing the csv upload (I'm not actually writing anything there by myself assuming #15716 gets fixed, by default it's blank for me)

**Comment by myheartsgoon** [comment]
I also encounter the same problem when using latest 1.2.0. 
Below is my setting: 
![image](https://user-images.githubusercontent.com/24839228/126030862-b408c785-38c4-4abf-8e47-45d744ec61fa.png)

Below is the error in the superset logs when opening the "Upload CSV" page:

![image](https://user-images.githubusercontent.com/24839228/126031264-e4e3d166-4017-4f96-883f-6aa66e071647.png)



I checked the put request that sent to the backend for enabling csv upload: `https://{superset_url}/api/v1/database/13`
In the request payload, the parameter "schemas_allowed_for_csv_upload" in `extra` was incorrectly set. It will cause `schemas_allowed_for_csv_upload` gets json parsed into string type instead of list type (source code in `superset.models.core.Database.get_schema_access_for_csv_upload` function). 


`extra` in the request payload in my case:
`"{\"metadata_params\":{},\"engine_params\":{},\"schemas_allowed_for_csv_upload\":\"[\\\"superset_upload\\\"]\"}"`

and after json parsing :

`>>> json.loads("{\"metadata_params\":{},\"engine_params\":{},\"schemas_allowed_for_csv_upload\":\"[\\\"superset_upload\\\"]\"}")
{'metadata_params': {}, 'engine_params': {}, 'schemas_allowed_for_csv_upload': '["superset_upload"]'}`

You can see `schemas_allowed_for_csv_upload` became a string instead of list. And it will raise the error `TypeError: can only concatenate str (not "list") to str`

![image](https://user-images.githubusercontent.com/24839228/126027778-912a8ffb-3dc9-4f8c-9dbd-4dca7d3870ec.png)

```python 
    def get_schema_access_for_csv_upload(  # pylint: disable=invalid-name
        self,
    ) -> List[str]:
        allowed_databases = self.get_extra().get("schemas_allowed_for_csv_upload", [])
        if hasattr(g, "user"):
            extra_allowed_databases = config["ALLOWED_USER_CSV_SCHEMA_FUNC"](
                self, g.user
            )
            allowed_databases += extra_allowed_databases
        return sorted(set(allowed_databases))
```

**Comment by myheartsgoon** [comment]
Currently I fixed this issue temporarily by adding below code to the funtion `get_schema_access_for_csv_upload ` on backend and rebuilt the image.
```
from ast import literal_eval
allowed_databases = literal_eval(allowed_databases)
```

full code of function `get_schema_access_for_csv_upload` now.
```python
    def get_schema_access_for_csv_upload(  # pylint: disable=invalid-name
        self,
    ) -> List[str]:
        allowed_databases = self.get_extra().get("schemas_allowed_for_csv_upload", [])
        from ast import literal_eval
        allowed_databases = literal_eval(allowed_databases)
        if hasattr(g, "user"):
            extra_allowed_databases = config["ALLOWED_USER_CSV_SCHEMA_FUNC"](
                self, g.user
            )
            allowed_databases += extra_allowed_databases
        return sorted(set(allowed_databases))
```

![image](https://user-images.githubusercontent.com/24839228/126039760-56ceeab5-9f37-40d6-aa84-4df4bdeacea7.png)

**Comment by fuomag9** [comment]
> ```python
>     ) -> List[str]:
> ```

I can attest that did made indeed the error disappear and the upload work

**Comment by SoryEscobar** [comment]
> > ```
> >     def get_schema_access_for_csv_upload(  # pylint: disable=invalid-name
> >         self,
> >     ) -> List[str]:
> >         allowed_databases = self.get_extra().get("schemas_allowed_for_csv_upload", [])
> >         from ast import literal_eval
> >         allowed_databases = literal_eval(allowed_databases)
> >         if hasattr(g, "user"):
> >             extra_allowed_databases = config["ALLOWED_USER_CSV_SCHEMA_FUNC"](
> >                 self, g.user
> >             )
> >             allowed_databases += extra_allowed_databases
> >         return sorted(set(allowed_databases))
> > ```
> 
> I can attest that did made indeed the error disappear and the upload work

Hi @fuomag9, how did you did this? i tried to recompile docker image changing the described function but apparently broke something because now the container is not starting.

**Comment by fuomag9** [comment]
> > > ```
> > >     def get_schema_access_for_csv_upload(  # pylint: disable=invalid-name
> > >         self,
> > >     ) -> List[str]:
> > >         allowed_databases = self.get_extra().get("schemas_allowed_for_csv_upload", [])
> > >         from ast import literal_eval
> > >         allowed_databases = literal_eval(allowed_databases)
> > >         if hasattr(g, "user"):
> > >             extra_allowed_databases = config["ALLOWED_USER_CSV_SCHEMA_FUNC"](
> > >                 self, g.user
> > >             )
> > >             allowed_databases += extra_allowed_databases
> > >         return sorted(set(allowed_databases))
> > > ```
> > 
> > 
> > I can attest that did made indeed the error disappear and the upload work
> 
> Hi @fuomag9, how did you did this? i tried to recompile docker image changing the described function but apparently broke something because now the container is not starting.

This is what I'd do and it builds, but it seems that the "fix" does not work anymore or I'm messing something up (even though I made that work some time ago!)

`git clone https://github.com/apache/superset`
substitute the `get_schema_access_for_csv_upload` function in ./superset/models/core.py
`sed -i "s_apache/superset:latest-dev_superset:localbeta_g" docker-compose-non-dev.yml`
`sudo docker build -t superset:localbeta .`
`sudo docker-compose -f docker-compose-non-dev.yml up`

**Comment by zhengr** [comment]
You can copy the modified core.py file to **<superset_app>** container directly, it works for me.

eg,
docker cp superset/models/core.py **<container-id>**:/app/superset/models/

**Comment by fuomag9** [comment]
Fixed with the latest superset:latest-dev

**Comment by sriram1204** [comment]
is this fixed in the latest code?
