### ISSUE TITLE
[Dashboard builder] add more draggable areas for resizing chart

### ISSUE THREAD

**Issue by ktmud** [apache/superset#15695]
**Is your feature request related to a problem? Please describe.**

Not sure whether this was the original behavior but it surprises me that currently we cannot drag the borders of chart containers to resize them (only the bottom right corner is draggable). See video behow:

https://user-images.githubusercontent.com/335541/125695660-c82b66d3-fff7-4538-83b9-f3c2fdff29d3.mp4

**Describe the solution you'd like**

In additional to dragging the botton-right corner, users should also be able to drag other corners to resize chart diagonally, AND drag the borders to resize horizontally or vertically.

**Describe alternatives you've considered**

N/A

**Comment by junlincc** [comment]
It is annoying but has been this way for a long time....
