### ISSUE TITLE
[annotation][time-series chart] Annotation on time-series chart will fail initially

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15697]
Annotation on time-series chart will fail and show error message initially, then change chart type to line chart, the same annotation will show and then change back to time-series chat, annotation will show correctly 

### Expected results

Annotation will show correctly on time-series chart initially

### Actual results

Annotation not show correctly on time-series chart initially

#### Screenshots
<img width="1792" alt="Screen Shot 2021-07-13 at 11 06 19 PM" src="https://user-images.githubusercontent.com/81597121/125706493-08d1f2f4-6a00-4cd3-b04d-8c4b36ba21d7.png">

https://user-images.githubusercontent.com/81597121/125705583-bc576a0d-fb80-46b0-8c98-5c0d848b47d4.mov

#### How to reproduce the bug

1. Create an annotation with time range 2000-2004
2. Open time-series chart (use cleaned_sales_data, metric: sum(sales)) and apply the annotation
3. See error
4. change the chart type to line chart and apply annotation again
5. change the chart type to time series chart and apply annotation again

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
thanks for filing! @jinghua-qa 

note: this only happens on the time related annotation. formula works alright.

**Comment by rusackas** [comment]
Seems to be working now! Closing as fixed.

![annotations_working](https://user-images.githubusercontent.com/812905/211605400-c5053ec3-7339-4c1d-a92b-4bcc32978724.gif)
