### ISSUE TITLE
[cosmetic][south table]unequal space in Table chart and data/sample table

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15691]
Should be equal vertical spacing of data/sample table and table chart
<img width="818" alt="Screen Shot 2021-07-09 at 11 58 49 AM (1)" src="https://user-images.githubusercontent.com/81597121/125676605-429bf2ec-d153-4be1-a8fc-48fd237fa546.png">

<img width="819" alt="Screen Shot 2021-07-09 at 11 57 22 AM" src="https://user-images.githubusercontent.com/81597121/125677475-ec7b35f4-5927-4181-9e2e-159895030ecf.png">

**Comment by junlincc** [comment]
Issue 1: decrease spacing in the south table( view result, view sample) to be the same as table chart. 
Issue 2: add spacing between tab and error msg.
