### ISSUE TITLE
[chart] Chart that's using a virtual dataset with an orderby breaks

### ISSUE THREAD

**Issue by rosemarie-chiu** [apache/superset#15693]
I suspect this is broke by this PR https://github.com/apache/superset/pull/15343
I have a virtual dataset that is order by a date column in the virtual dataset. It used to work but not anymore.

### Expected results
screenshot of how it used to be working
![CleanShot 2021-07-14 at 13 53 35](https://user-images.githubusercontent.com/52086618/125691410-71c4579e-7c48-4de8-8597-9feeb4b649f1.png)

### Actual results
It is complaining unknown column used by "order by"
![CleanShot 2021-07-14 at 13 56 56](https://user-images.githubusercontent.com/52086618/125691891-4a88474b-a45c-4d43-a31e-c637df976e88.png)

**Comment by junlincc** [comment]
Issue: Chart that's using a virtual dataset with an orderby breaks

**Comment by zhaoyongjie** [comment]
@rosemarie-chiu Could you share this dataset with me? It seems to have a bug with the `window function`(sum over ....) as a metric.
