### ISSUE TITLE
Superset swagger API /dashboard/import overwrite param doesn't work

### ISSUE THREAD

**Issue by xingyc15** [apache/superset#15701]
I am using the latest superset with the /dashboard/import API under <my_host>/swagger/v1. 

I export the json file of my dashboard, and import it. The import succeed. 

But it create a duplicated dashboard in my dashboard list. I have set the overwrite to be true but it doesn't work. it still create the duplicated one. Same owner, same dashboard json file.

![image](https://user-images.githubusercontent.com/33602700/125720763-04641ec3-5973-42f3-8366-a74309298d32.png)

![image](https://user-images.githubusercontent.com/33602700/125721368-9501e4d0-c079-4ad6-ab91-7fe8702699de.png)

### Environment

- superset version: `latest`

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by lubumu** [comment]
I'm facing the same issue. It seems that "dashboard/import" creates a new dashboard id with the imported content. But I need a way to overwrite a dashboard with an existing id. (Reason: deployment from DEV environment to PROD environment) .

**Comment by srinisubramanian** [comment]
@srinify I am able to reproduce the same issue in 1.4.1.  Its easy to reproduce, just export a dashboard and import it.  Then reimport it and a duplicate dashboard is created.  Looks like the overwrite flag works for database/datasource but not dashboard.

In the database I also noticed that the uuid in the source DB is different from the destination database (dashboards table, uuid column) and a new uuid is generated everytime.  Also in the exported file the uuid is not present?

**Comment by jmaebrancke** [comment]
Same issue in version 1.5.1.

**Comment by rusackas** [comment]
We're now on 3.1, on the verge of 4.0, and not supporting 2.x  or prior versions actively. If folks are experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)
