### ISSUE TITLE
Schema Preview doesn't work

### ISSUE THREAD

**Issue by zacharyzhao** [apache/superset#15705]
Hi guys, I got a issue here.

I upgraded Superset from `0.37.0`  to `1.2.0` , everything seems ok until I try to browser data from `SQL Lab` - `SQL Editor` : when I select schema on the left side, a `PREVIEW` tab appears under the editor, but nothing in that tab. I can see that query in `Query History` Page. And, there aren’t any ERROR logs found from webserver or celery-worker.

However, I can see query result by inputing some queries and press `RUN` button.

Can someone tell me what happen? There aren’t any error logs, it really confusing me.

**Comment by rosemarie-chiu** [comment]
I think this issue is already fixed in latest master. I don't repo such issue.

https://user-images.githubusercontent.com/52086618/125864499-960697df-760a-49a0-b089-15f4f30fa8f9.mp4

**Comment by junlincc** [comment]
Thanks for reporting! both left panels and table got updated on schema select. the bug should have been fixed in master. i would say 1.3 is more stable than 1.2. 

https://user-images.githubusercontent.com/67837651/125864364-2a586cef-cdab-4144-8cca-1b53f86c800d.mov
