### ISSUE TITLE
[Explore] Server Pagination is not working

### ISSUE THREAD

**Issue by RossMoir** [apache/superset#15706]
Backend server pagination option for the table chart is unresponsive and does not work. Explained in the previous issue #15478 which was prematurely and wrongly closed, when the option is enabled Superset correctly paginates for the first page of the table but is completely unresponsive when a new page flip is selected. 

#### Screenshots

https://user-images.githubusercontent.com/44472119/125763717-0fdc73ce-e066-44b5-a1a4-bd8124ec8307.mov

### Environment

- superset version: `1.2` and `master`
- backends tested: `Apache Druid 0.21.1`,`PostgreSQL`, `MySQL` 

@aelich

**Comment by aelich** [comment]
@RossMoir I agree with everything you stated here, it would be great if Server pagination would work again, I have the same bug.

**Comment by junlincc** [comment]
That's weird, we verified the issue was resolved on master 2 days ago... @jinghua-qa can we double check on master?

**Comment by Veonms** [comment]
@junlincc As stated in issue #15478 once it was closed, the video you sent didn't have the server pagination enabled as explained in this comment, https://github.com/apache/superset/issues/15478#issuecomment-879761261. Once the checkbox  on the left is enabled, pagination fails to work after the first page, as shown in the OP

**Comment by david-zh-cn** [comment]
我也碰到了同样的问题

**Comment by quangpx** [comment]
I have the same issue too! Please help me to fix it.

**Comment by pabrahamusa** [comment]
Anyone know whether it is working in 1.2.0 release?

**Comment by RossMoir** [comment]
@pabrahamusa we tested on 1.2 release and it didn't work, also not functioning on master currently. #15857 #15860

**Comment by RossMoir** [comment]
Update: Server side pagination is functional on 1.2 but requires the below feature flags set as `True`. Closing the issue due to it working. Although documentation for this would have been helpful.

https://github.com/apache/superset/blob/eb78f4332fd931b8f8990c9d177b990fa49f189c/superset/config.py#L368-L370

**Comment by pabrahamusa** [comment]
Thats is a good find. Thanks @RossMoir for sharing..!

**Comment by aelich** [comment]
This is a shocking, that it wasn't documented anywhere, the only place i could find on google is:
https://fossies.org/linux/superset/RESOURCES/FEATURE_FLAGS.md

And this one is also not clear... How on earth did you find out this one @RossMoir I'm so curious ? 

WOW, bravo!!!

**Comment by RossMoir** [comment]
Glad others can confirm this works too. We have been following issue #15860 closely and noticed the breif mention of the above feature flags and decided to try them out. Again, even in this issue, they do not explicitly mention the requirement of the feature flags and we agree this is extremely poor communication and documentation.

**Comment by Veonms** [comment]
As mentioned in @RSanjeevi issue, for server pagination to work you, annoyingly, first have to save the chart. Just a heads up for anyone who gets stuck on that issue. Same issue as #14727

**Comment by ktmud** [comment]
> Update: Server side pagination is functional on 1.2 but requires the below feature flags set as `True`. Closing the issue due to it working. Although documentation for this would have been helpful.

If server side

**Comment by villebro** [comment]
This has already been done (already on master): https://github.com/apache-superset/superset-ui/pull/1251

**Comment by ktmud** [comment]
Ah nice, sorry for not checking the latest master!
