### ISSUE TITLE
Modifying a connection's meta data not working after creation

### ISSUE THREAD

**Issue by kevinwenglu** [apache/superset#15729]
Go to /databaseview/list/. Add a new database connection. A new database connection is created. Click on the edit button on the right and bring up the modal for the connection. Change something and click save button. 
I expected that the changes is updated and the modal should disappear.

However, A error message pops up and the modal stays.
![Screen Shot 2021-07-15 at 11 26 34 PM](https://user-images.githubusercontent.com/81392331/125904151-746b2956-aeb8-4b3e-a8bf-eb6da14a340e.png)

(please complete the following information):

I took a snapshot from master at May, pretty closed to 1.2. I saw the same code in 1.2 too. It throws an error for an existing connection with parameters at line 262 in the file: https://github.com/apache/superset/blob/latest/superset/databases/schemas.py

There is an exception for Mysql because Mysql is the direct dependent of BaseParametersMixin.

I'm using python 3.8.10

**Comment by nytai** [comment]
Cannot repro against the latest master or 1.2. Can you please post more info and confirm that this is an issue with latest master or 1.2? A “snapshot from master at May” is not enough info.

**Comment by kevinwenglu** [comment]
There is no actual trace stack on the page because the frontend captures that and display as an error message, but the screenshot shows the stack until the exception is raised.
As I said, we captured the master in May. I haven’t had time to test 1.2 yet, but seems like the logic is the same. I also see that the superset/databases/schemas.py in 1.3 and the current master is using the different condition to check against the validity of the engine spec.
https://github.com/apache/superset/blob/master/superset/databases/schemas.py
https://github.com/apache/superset/blob/1.3/superset/databases/schemas.py
https://github.com/apache/superset/blob/1.2/superset/databases/schemas.py

![Screen Shot 2021-07-16 at 12 42 54 PM](https://user-images.githubusercontent.com/81392331/126002064-20958d1e-1b91-4d1f-a058-8b3896e85a1a.png)
![Screen Shot 2021-07-16 at 12 45 54 PM](https://user-images.githubusercontent.com/81392331/126002078-4cc0e615-f849-4b07-b6b5-fcf50304754e.png)
[superset.databases.schemas.in_may.py.txt](https://github.com/apache/superset/files/6833085/superset.databases.schemas.in_may.py.txt)
[superset.databases.schemas.1.2.py.txt](https://github.com/apache/superset/files/6833086/superset.databases.schemas.1.2.py.txt)

**Comment by nytai** [comment]
cannot repro in 1.2
