### ISSUE TITLE
[pivot table2]make column row header sticky on scroll

### ISSUE THREAD

**Issue by junlincc** [apache/superset#15722]
As a user, I would love to have sticky header to view large table on scroll
might be hard, depending on the limitation of the component itself

https://user-images.githubusercontent.com/67837651/125860766-8ac99ef0-4136-4468-b191-e7d44084b4a1.mov

if it takes more than half day to implement, which is likely be the case, then let's wait. @kgabryje

**Comment by kgabryje** [comment]
Done by https://github.com/apache-superset/superset-ui/pull/1232
