### ISSUE TITLE
Editing dataset to change database it points on

### ISSUE THREAD

**Issue by helo-ch** [apache/superset#15733]
We use several Timescale DB databases. 
Some tables have been migrated from one DB (DB1) to another (DB2). 
There are datasets pointing on tables from DB1, that we would like to edit to point on DB2. 

### Expected results

The Dataset editing window seemingly allows us to edit the Database, schema and table, so that we could edit a dataset to point on a table from DB2 rather than from DB1. 

<img width="324" alt="superset_edit_dataset_window" src="https://user-images.githubusercontent.com/28846165/125913483-dbec087c-aab2-43c7-b937-44013c925b3d.PNG">

### Actual results

But when we click save on that window, nothing happens and the dataset is unchanged, it still points to the same table from DB1. We tried syncing columns from datasource before saving, the result is still the same.
It doesn't seem to be linked to roles or permissions, as it happens even with admin role.

To clarify, table name and table schema are the same in DB1 and DB2, the only part that we need to change is the Database.

### Environment

(please complete the following information):

- superset version: `1.0.1`

Is it possible to edit a dataset to point on a table from a different database? If it is not possible, it should be made clearer in the editing window.

**Comment by srinify** [comment]
hey @junlincc if I squint, I believe this issue was mentioned / fixed in the last month or 2 right? Or am I mis-remembering

**Comment by CollinKendor** [comment]
I am experiencing the same issue in the dockerized version of superset. Is there any fix to the docker version?

**Comment by CollinKendor** [comment]
@srinify i can't find any other mention of this in the issue list.

**Comment by cccs-tom** [comment]
I just experienced this as well On Superset 1.2.0. The UI reports that the changes were saved successfully, but nothing actually changes. I checked the logs and I see no errors.

**Comment by igudav** [comment]
Same issue on dockered version 1.2.0

**Comment by vnktsh** [comment]
I have same issue, both in New and LegacyDataEditor.

**Comment by rusackas** [comment]
@cccs-tom / @hughhhh are either of you able to confirm/deny whether or not #17265 does indeed effectively close this, or if there are more nuances that need to be dealt with here?

**Comment by cccs-tom** [comment]
@rusackas I just re-tested this and it seems to work as expected. Unfortunately, I can't remember the exact scenario I encountered (in July 2021) which prompted me to add my +1 to this bug report! But it looks fixed to me!

**Comment by rusackas** [comment]
Well that's great news! Closing it out then, but happy to revisit if needed.
