### ISSUE TITLE
[Native filter] I cannot filter a boolean column

### ISSUE THREAD

**Issue by rosemarie-chiu** [apache/superset#15746]
**Is your feature request related to a problem? Please describe.**
I have a boolean column that I wish to filter on. But I cannot find a way to filter with that column and I have to change that column to a string column. 
![CleanShot 2021-07-16 at 10 25 12](https://user-images.githubusercontent.com/52086618/125986040-8a7d7383-e155-4667-92b9-7869fa1b9d5b.png)
![CleanShot 2021-07-16 at 10 25 50](https://user-images.githubusercontent.com/52086618/125986089-7e2b5ae6-3181-4fba-9341-367dd1c64b64.png)

**Describe the solution you'd like**
Be able to filter with a boolean column

**Comment by daniel10012** [comment]
@junlincc

**Comment by junlincc** [comment]
Just wanna make sure this is a feature request of adding a new filter type, instead of a bug, and we have workaround currently which is to change the datatype. @daniel10012 what database is the user using?

**Comment by daniel10012** [comment]
This is more a bug as users would expect to filter by this datatype in general.
The problem is database agnostic

**Comment by villebro** [comment]
Oh we probably forgot to add booleans as a supported type for the select filter. Should be a one-liner fix
