### ISSUE TITLE
Deck GL.Grid height is not correct

### ISSUE THREAD

**Issue by jaksmid** [apache/superset#15748]
I am using deck gl grid visualization to show the price per square meter in real estates properties. I noticed that sometimes height is calculated incorrectly. E.g. if I want to show the max price per sq. meter and I have filters that limit rows used such as `price_per_sq_m < 40000`, the height that is shown still exceeds this limit. 

I managed to reproduce the bug using the sample dataset shipped with superset. 

### Expected results

I would expect that height respects both filters and used aggregated function.

### Actual results

Height does not correspond to the filters and aggregate function. See screenshot.
The height where the mouse is hovering is clearly above the filter. Max function used for aggregation does not change the maximum either and should not exceed the set filter.

#### Screenshots

<img width="1477" alt="Screenshot 2021-07-16 at 21 58 21" src="https://user-images.githubusercontent.com/3618465/126002280-57fdfe1e-8f9a-4ee5-88ad-5a5668eef0c5.png">

#### How to reproduce the bug

* Open the deck gl dashboard and explore the grid chart. 
* Change the height metric to max(occupancy)
* Set the filter to limit occupancy (e.g. 70).
* Observe heigh of certain areas still exceeding 70.

### Environment

(please complete the following information):

- superset version: `Superset 1.2.0`
- python version: `Python 3.9.5`
- node.js version: `v16.3.0`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Observed this problem even before 1.0

**Comment by jaksmid** [comment]
I checked what is coming from the backend and all values seem to be fine.

I suspect the problem is in the rendering - the deck grid is probably performing aggregation of nearby locations using own metrics - https://deck.gl/docs/api-reference/aggregation-layers/grid-layer, section elevationAggregation.

By default, a sum is used on the frontend aggregation.

It could be non trivial to make sure the backend and frontend aggregations are in sync.

**Comment by jaksmid** [comment]
Could an interim solution be to expose the options for the deck grid in the superset UI? It would be up to the user to select a combination of backend/frontend aggregation that makes sense.

**Comment by gustavscholin** [comment]
Any updates on this issue?

**Comment by rusackas** [comment]
Is this still an issue in current-era Superset? I'm tended to close this as stale, but if there's a data truthfulness problem... well, that warrants keeping around. 

Curious if @Mattc1221 has run into this... not sure who else is putting a lot of miles on the DeckGL plugins these days :)

**Comment by rusackas** [comment]
Ok, it's been a few more months. Closing this as stale if nobody is worried enough to reproduce the issue in supported versions, much less open a PR :)

**Comment by rusackas** [comment]
Happy to reopen if anyone's still affected and/or interested in tackling it 🤞
