### ISSUE TITLE
[chord diagram]missing tooltip on chart when hovering/clicking 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#15751]
Current Behavior: 

https://user-images.githubusercontent.com/67837651/126019534-016d19c0-06fd-432a-957e-ebdb85852a2f.mov

Expected Behavior:
https://docs.preset.io/docs/chord-diagram 

@kgabryje thanks for spotting it! 
@xiezhongfu please work on this after the gallery project 🙏

**Comment by geido** [comment]
Hello @junlincc. I don't see this issue in master. It appears that the tooltips are appearing on hover. The experience looks ok compared to this video https://docs.preset.io/docs/chord-diagram. Let me know what do you think. CC @rosemarie-chiu @jinghua-qa

<img width="1680" alt="Screen Shot 2021-07-21 at 13 57 07" src="https://user-images.githubusercontent.com/60598000/126485165-a304bd0e-c15d-4f37-b80f-c0d65c3e2d27.png">

**Comment by kgabryje** [comment]
That's strange. For me they don't show up at all. I tested in Chrome and Safari, private mode and with different settings of the chart.

**Comment by geido** [comment]
Tested again @kgabryje on the latest master. It appears to me. Are you giving it enough time to show up? It takes a bit to show fade in when hovering.
 
<img width="1680" alt="Screen Shot 2021-07-22 at 18 41 57" src="https://user-images.githubusercontent.com/60598000/126676663-21dc4679-37fb-4ff7-82f3-fa7c3d8ac831.png">

**Comment by rosemarie-chiu** [comment]
I do see tooltips on latest master. But I think it takes too long to show. Have to be very patient and stick mouse over there for like 2 secs.

https://user-images.githubusercontent.com/52086618/126752811-87733ce6-aee9-4c85-bfe0-b04d8d16c31d.mp4

**Comment by geido** [comment]
@rosemarie-chiu I believe this is a very resource intensive chart. Not sure if improving the performance should be in scope for the bug bashing.

**Comment by kgabryje** [comment]
@geido @rosemarie-chiu Yes, that was the case - I expected the tooltip to appear either on click or immediately on hover rather than 2 seconds later

**Comment by geido** [comment]
I think we can close this one as there is no actual bug
