### ISSUE TITLE
"Share chart by email" from chart menu generates broken URL

### ISSUE THREAD

**Issue by sfkeller** [apache/superset#15766]
If in a chart on (a dashboard) one clicks on the menu (the vertical ellipsis, Unicode U+22EE) a broken link with is being generated starting with 'undefined' before "https...".

### Expected results

Generate a valid URL "https://potm.osm.ch/r/6".

### Actual results

A broken URL like "undefinedhttps://potm.osm.ch/r/6" is being generated.

#### How to reproduce the bug

1. Go to example Dashboard https://potm.osm.ch/superset/dashboard/13/  
2. Click on vertical ellipsis of any chart, like the one upper right.
3. See result (in mail text ): "undefinedhttps://potm.osm.ch/r/6"

### Environment

Superset version: 1.2.0rc2 and before

**Comment by junlincc** [comment]
I believe we have fixed it. @sfkeller please confirm in master.
