### ISSUE TITLE
Add  cascading link between 2 filterboxes

### ISSUE THREAD

**Issue by jianxia84** [apache/superset#15771]
**Is your feature request related to a problem? Please describe.**  

I wish there could be a cascading link between 2 filterboxes

**Describe the solution you'd like**  

I have 2 filterboxes, the first has 1,2; the second has a,b,c and x ,y,z . When the first filterbox is 1, the second one shows a,b,c. When the first filterbox is 1, the second one shows a,b,c. When the first filterbox is 2, the second one shows x,y,z but keeps the previous a. I don't want to keep the a. 

**Describe alternatives you've considered**

No good ones come to mind at the moment

**Additional context**

![image](https://user-images.githubusercontent.com/28744116/126084892-19e34773-b6a2-4e7c-ab21-4254aa4b59c2.png)

![image](https://user-images.githubusercontent.com/28744116/126084904-8df63548-665a-4e49-b8c7-bf118dfd0507.png)

**Comment by zhaoyongjie** [comment]
Please use `Native filter` instead of `Filterbox`, community will be deprecated filterbox.

**Comment by srinify** [comment]
To add a bit more color to @zhaoyongjie 's comment -- currently the Filter Box is a viz type, which has many quirks. The future is something the Superset community calls Dashboard Native Filters, which will live in dashboard UI itself!

Here's a preview of what that UX looks like: https://www.youtube.com/watch?v=BLp_oQGHpSE 

To enable native filters for testing, you need to enable the `DASHBOARD_NATIVE_FILTERS` feature flag.

You can read more about how to enable feature flags here: https://superset.apache.org/docs/installation/configuring-superset#feature-flags

Soooo with all this context in mind, the community is trying to push people away from Filter Box (which will be deprecated) and towards Dashboard Native Filters.
