### ISSUE TITLE
[edit dataset modal] After changing database, columns are not sync and require manual resync

### ISSUE THREAD

**Issue by rosemarie-chiu** [apache/superset#15789]
We recently fix https://github.com/apache/superset/issues/14592 with PR https://github.com/apache/superset/pull/15770
However, I found that when I explore that dataset, columns need to manually resync

### Expected results
After changing database of a dataset, column should be resync from the source automatically.

### Actual results
Need manual re-sync of column from the source

#### How to reproduce the bug

1. Edit any dataset, change the database source
2. explore that dataset
3. Observe that columns are not synced automatically

![CleanShot 2021-07-19 at 16 20 52](https://user-images.githubusercontent.com/52086618/126239612-b710dab2-cf8e-4413-ab03-a59e79af1e35.gif)

**Comment by zhaoyongjie** [comment]
There are some limitations in the function of "re-reference dataset"(reassign database/schema/table name for a dataset entity in the Superset)

1. No identical dataset can exist (the other words are two datasets cannot have the same database/schema/table name)
if you do that, the database will return a constraint error

2.
