### ISSUE TITLE
ab_view_menu and ab_permissions_view tables are getting loaded with numerous amount of rows

### ISSUE THREAD

**Issue by radhakvnr** [apache/superset#15782]
ab_view_menu and ab_permissions_view tables are getting loaded with numerous amount of rows when a new database connection has been created.

### Expected results

FAB should create the permissions based on the database specified or the tables that have been imported

### Actual results

FAB is creating the permissions for all the schemas inside a database.

#### Screenshots

the database connection presto://host:port/database/     has 230 schema's. Once the Database connection has been saved it is automatically adding the 230 rows in ab_view_mneu table and gradually increasing # of rows in ab_permission_view table of metadata.

#### How to reproduce the bug

1. Go to 'Create database and enter the database connection where it has multiple schemas'
2. Click on 'Add Database'
3. Scroll down to 'Metadata tables and query the ab_view_menu and ab_permission_view tables '
4. See error:- you will get the increasing in number of rows than expected.

### Environment

(please complete the following information):

- superset version: `1.1.0 and 1.2.0`
- python version: `3.7`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by radhakvnr** [comment]
Hi any luck?

**Comment by srinify** [comment]
Tagging @dpgaspar

**Comment by rusackas** [comment]
@dpgaspar @john-bodley are either of you aware of any changes in this area since the bug report was opened? And is this indeed a bug, or is it by design?

**Comment by rusackas** [comment]
Since we're now on 3.1, on the verge of 4.0, we're not supporting 2.x  or prior versions actively. If anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)
