### ISSUE TITLE
Add Alpha users access to all dashboards when DASHBOARD_RBAC is enabled

### ISSUE THREAD

**Issue by xneg** [apache/superset#15797]
**Is your feature request related to a problem? Please describe.**
According to [documentation](https://superset.apache.org/docs/security) 

> Alpha users have access to all data sources, but they cannot grant or revoke access from other users. 

When enabling the DASHBOARD_RBAC setting, Alpha users lost access to dashboards they don't own. Only admin users have full access to all dashboards. Our BI command has had an Alpha role to create and setup dashboards but they are not admins. After enabling DASHBOARD_RBAC they can't see draft dashboards.

**Describe the solution you'd like**
I suggest to add [here](https://github.com/apache/superset/blob/ffa51753e3cfdc401ca976e66e5b85cda032dc08/superset/security/manager.py#L1181) another check 

```
can_access = (
                is_user_admin() or is_user_alpha()
                ...
```

**Describe alternatives you've considered**
An alternative is to add in every newly created dashboard access roles Alpha role. But it seems fiddly and easy to miss.

**Comment by amitmiran137** [comment]
you can just assign the Alpha role with all databases permissions and that will do it

**Comment by xneg** [comment]
Oh, ok, thank you!

**Comment by xneg** [comment]
Sorry, but your suggestion doesn't work.
If we look at [this filter](https://github.com/apache/superset/blob/a39dd4493e8b40cc142451bc71e4d1d4f2705d3f/superset/dashboards/filters.py#L62) code we'll see that
> List dashboards with the following criteria:
        1. Those which the user owns
        2. Those which the user has favorited
        3. Those which have been published (if they have access to at least one slice)
  **If the user is an admin then show all dashboards.**

I think that if the alpha user is somewhat like the administrator in regards to viewing data sources, then they could list all dashboards too.

So my suggestion to change [this line](https://github.com/apache/superset/blob/a39dd4493e8b40cc142451bc71e4d1d4f2705d3f/superset/dashboards/filters.py#L75) to
```
if is_user_admin() or is_user_alpha():
    return query
```
P.S. I added all database permissions to alpha users but with RBAC enabled they can't see all dashboards.

**Comment by jtotoole** [comment]
@xneg we've got the same issue, did you find a way to handle it?

**Comment by xneg** [comment]
@jtotoole Because we don't use a vanilla version of Superset but the fork I just added these lines of code above in the main code.

**Comment by jtotoole** [comment]
gotcha, thanks a bunch!
