### ISSUE TITLE
[Native Filter] Options for value filter should refresh when dashboard refresh but currently only when page refresh

### ISSUE THREAD

**Issue by rosemarie-chiu** [apache/superset#15808]
I found that when my charts are refreshed with newest data, value filter is still not refresh with the latest data. 
Filter option only refreshed when I refresh the page entirely, not when dashboard is refreshed.

### Expected results
On dashboard refresh, native filter should also refresh.

### Actual results
Native filter only refresh on "page refresh"

#### Screenshots

https://user-images.githubusercontent.com/52086618/126416469-24a7a2ad-3f6b-4da9-9dfd-68d724a1e1eb.mp4

#### How to reproduce the bug
Using my example to describe here:
1. I have a big number charts showing total of 176 feature tags, observe that value filter showing 177 (also counted NULL)
2. I removed one of the feature tag `viz:explore:gallery` from my data
3. Click refresh dashboard, observe that my chart is updated to 175 now
4. Observe that on native filter, the number of options is not updated, and I can still find `viz:explore:gallery` as an option
5. Refresh the entire page, observe that only after page refresh, value filter options refresh.

### Environment
Latest master tested locally

**Comment by junlincc** [comment]
@rosemarie-chiu thank you for filing this issue! definitely a case that we missed. 
@geido 🙏
