### ISSUE TITLE
In ingonito getting Security error when embedding dashboard in iframe

### ISSUE THREAD

**Issue by saurabnigam** [apache/superset#15819]
In tag, 1.0.0 things worked perfectly in incognito when the dashboard is embedded as an iframe. CORS and CSRF are disabled.
In tag 1.2.0 it gives an Unexpected error: SupersetApiError: An attempt was made to break through the security policy of the user agent.

**Comment by junlincc** [comment]
can you provide more information, screenshots video etc. and verify if that;s still happening in latest master? thanks @saurabnigam

**Comment by saurabnigam** [comment]
The dashboard is embedded using an iframe.
parent domain: a.y.com
superset domain: b.y.com ie domain is same, subdomain is different. Nginx is used as a reverse proxy and all headers are passed. No cors or csrf restrictions are there. 

Normally in chrome or firefox if I open this page it works. When I open this in incognito or private browsing in chrome or firefox respectively the error comes.

According to my findings, Superset is trying to access browser storage for caching which is getting security issues in incognito mode due to cross domain, but I might be wrong!

Screenshot for reference. 
![Capture](https://user-images.githubusercontent.com/20903614/126999923-60b7709d-4004-45e9-9cb6-8bec05bee8f6.PNG)


Let me know if more info is required

**Comment by saurabnigam** [comment]
@junlincc is there a way I can disable using local storage of browser for caching?

**Comment by saurabnigam** [comment]
@junlincc Do you need any more information 
I was able to narrow down the code at which this exceptions occurs. But I don't know how to fix this. Could you guide me ?
https://github.com/apache-superset/superset-ui/blob/4be2c55f8fcf035aee3f39f31dbd264ecda8f2c7/packages/superset-ui-core/src/connection/callApi/callApi.ts#L72

**Comment by jhult** [comment]
Also related to #13697, #15737, and #16718.

**Comment by vikas-nykaa** [comment]
@jhult after doing all changes,in firefox it is working fine

<img width="1271" alt="Screenshot 2021-11-18 at 3 23 49 PM" src="https://user-images.githubusercontent.com/86848951/142392558-333aadcd-23e6-444c-b387-4d07ea239873.png">

But in chrome, after login "superset/welcome" again redirecting me to /login page
 
<img width="1435" alt="Screenshot 2021-11-18 at 3 26 48 PM" src="https://user-images.githubusercontent.com/86848951/142393129-4de27c6f-093a-4654-8b76-d92646bdc5e1.png">

And in logs i am getting
WARNING:root:Class 'werkzeug.local.LocalProxy' is not mapped

Please help on this

**Comment by jhult** [comment]
@vikas-nykaa, can you compare the request and response headers between Chrome and Firefox? That might give you a clue as to what is different between the two.

Also, try using an incognito (Chrome) or private (Firefox) window to ensure no cookies are interfering.

**Comment by pnzz7** [comment]
semi solution / workaround for chrome: **Allow all cookies** in chrome://settings/cookies will do it.

**Comment by vikas-nykaa** [comment]
working fine after setting SESSION_COOKIE_SAMESITE=None 
Because login api was not able to set cookie due to cross oriign
