### ISSUE TITLE
[db_specific]Data schema retrieval from Athena incorrect

### ISSUE THREAD

**Issue by oscarxanda** [apache/superset#15814]
Assuming an account that has column level access defined in an AWS Data Lake.
When using this account to connect to Athena, when Superset retrieves the table structure, it retrieves also the columns the user does not have access to. 
The preview will also fail, as instead of the preview working by "SELECT *..." it does a "SELECT column_1, column_2...".

### Expected results

Schema retrieval will only return the columns the account  has access to.
Table preview will work by not adding the columns the account does not have access to.

### Actual results

Table schema shows fields with no access.
Preview mode fails.

#### Screenshots

Preview mode failing, schema showing the column "class" that the account does not have access to.
![image](https://user-images.githubusercontent.com/74599263/126460277-3f6d915f-ae65-4a7f-ab50-ff8177054d6b.png)

Expected result
![image](https://user-images.githubusercontent.com/74599263/126460292-3c87686e-c659-4e18-919f-9766a66a639c.png)

#### How to reproduce the bug

1. Create an account with column level permissions
2. Create a DB connection using that account
3. Go to SQL Lab
4. Select a table the account has access to (but won't have access to all columns)
5. See error

### Environment

Using the docker image available on git

- superset version: `superset version`
Loaded your LOCAL configuration at [/app/docker/pythonpath_dev/superset_config.py]
logging was configured successfully
2021-07-21 08:52:52,080:INFO:superset.utils.logging_configurator:logging was configured successfully
2021-07-21 08:52:52,096:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
/usr/local/lib/python3.7/site-packages/flask_caching/__init__.py:202: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  "Flask-Caching: CACHE_TYPE is set to null, "
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Superset 0.999.0dev
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

- python version: `python --version`
Python 3.7.9

- node.js version: `node -v`
/bin/sh: 4: node: not found

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

No additional context

**Comment by rusackas** [comment]
@oscarxanda can you confirm this is still an issue in recent releases, or especially on master? I think some libraries related to Athena were bumped in recent months, and MAYBE we'll get lucky with this one.

**Comment by rusackas** [comment]
@yousoph do we have anyone that can easily repro this one?

**Comment by oscarxanda** [comment]
> @oscarxanda can you confirm this is still an issue in recent releases, or especially on master? I think some libraries related to Athena were bumped in recent months, and MAYBE we'll get lucky with this one.

I would need to reinstall as ended up moving away because of this limitation at the time.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
