### ISSUE TITLE
[db_specific] CockroachDB does not support to_timestamp

### ISSUE THREAD

**Issue by korpa** [apache/superset#15825]
### Expected results

Graph should appear

### Actual results
Error is shown:

> CockroachDB Error
>
> unknown function: to_timestamp() 

#### Screenshots

Without timefilter:

![image](https://user-images.githubusercontent.com/2982785/126559336-6547e183-9b9b-4167-908b-6f282f9ff77f.png)

With timefilter:

![image](https://user-images.githubusercontent.com/2982785/126559509-77692b3f-9743-4fca-9728-097c6abb846a.png)

#### How to reproduce the bug

Create a graph on database "CockroachDB" and add a time filter

### Environment

(please complete the following information):

- superset version: 1.2
- python version: 3.8
- node.js version: `node -v`
- CockroachDB 21.1.6

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

In Superset 1.0 CockroachDB works fine with time filters. After upgrading to 1.2 this issue appears

**Comment by junlincc** [comment]
Hi @korpa , we may not get to any db specific issues soon enough, feel free to open a PR, we are happy to review!

**Comment by korpa** [comment]
This issue still exists. Please do not close

**Comment by korpa** [comment]
It seems that someone implemented this feature in CockroachDB  https://github.com/cockroachdb/cockroach/pull/82523

Hopefully this will released in a minor version that we do not have to wait another 6 months for the next big release of CockroachDB

**Comment by leecjohnny** [comment]
Currently, I face this error when using `Version: 2023.23.1` via preset.io.

Specifically, it says `Error: unknown signature: to_timestamp(string, string)`

CockroachDB doesn't have that exact `to_timestamp` function that returns a timestamp-like datatype. Though it does have `strptime(input: string, format: string) → timestamptz`

https://www.cockroachlabs.com/docs/stable/functions-and-operators.html#date-and-time-functions

is this a sqlalchemy driver issue or superset?

driver: https://github.com/cockroachdb/sqlalchemy-cockroachdb

**Comment by elewis787** [comment]
Any advice for this issue? - running into this as well and am happy to dig in if there is some rough guidance on where the root issue may exist.

**Comment by elewis787** [comment]
@yousoph @junlincc - seems like this is a matter of updating the db spec for crdb here https://github.com/apache/superset/blob/master/superset/db_engine_specs/cockroachdb.py 

I am going to play around with getting a local superset env set up and will see if I can validate that is the correct spot to implement how to handle time filters.

**Comment by elewis787** [comment]
I have a fix for this running locally and in a prod env using version 2.1.0. 

I will link the pr once I have it submitted and show some work arounds.
