### ISSUE TITLE
[cosmetic][pivot table v2]

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15826]
Currently Pivot table chart border is styled in grey, pivot table v2 is styled in blue, can we make both table border in grey?

## Screenshot
Pivot table
<img width="1111" alt="Screen Shot 2021-07-21 at 2 16 01 PM" src="https://user-images.githubusercontent.com/81597121/126561821-2623687f-0373-4b9d-899c-4bffeaf77eff.png">

Pivot table v2
<img width="1117" alt="Screen Shot 2021-07-21 at 2 16 20 PM" src="https://user-images.githubusercontent.com/81597121/126561769-61352469-491a-4599-a7ae-3df70ef58730.png">

**Comment by geido** [comment]
Fixed in https://github.com/apache-superset/superset-ui/pull/1286
