### ISSUE TITLE
[explore] customize tab is broken

### ISSUE THREAD

**Issue by rosemarie-chiu** [apache/superset#15829]
Custom tab > chart options section is broken

### Expected results
Chart options should be expanded by default when user click on custom tab

### Actual results
1. Customize tab isn't expanded by default
2. Buggy, sometimes expand doesn't show anything

#### Screenshots

https://user-images.githubusercontent.com/52086618/126574252-c1fb3e64-712e-4dc9-abf0-fd4306b36b44.mov

#### How to reproduce the bug

1. Go to Explore > select a chart from gallery view
2. Click on 'customize tab'
3. Observe that need to expand chart options to see settings
4. Observe in the second half of the attached video, expand chart options show all blank

### Environment
Latest master

**Comment by junlincc** [comment]
@geido 🙏
