### ISSUE TITLE
Cross-filtering applies only to some charts

### ISSUE THREAD

**Issue by milenioz** [apache/superset#15835]
Using USA birthNames dashboard some Charts have been modified to emit cross filters. 
However only some of the charts are updated. The others are refreshed, but are not updated with the filter.
Opening the not updated ones in Explorer view are correctly filtered.

### Actual results
![Cross-filtering_1](https://user-images.githubusercontent.com/37159591/126630702-d657b55a-398c-4296-8cac-d0bc21898deb.JPG)
![Cross-filtering_2](https://user-images.githubusercontent.com/37159591/126630704-8cfe90b2-cb63-4cbb-bb27-968a25f27f20.JPG)

what actually happens.

### Environment

(please complete the following information):

- superset version: 1.2.0
- python version:3.9.5
- node.js version: v.12.21.0

**Comment by junlincc** [comment]
Hi @milenioz by design, we only enable x-filter emitting events in a few new charts. for receiving, all charts should be able to. can you list a list of charts that don't work? 

You may wanna get on lastest master since a lot have changed since we cut 1.2

**Comment by milenioz** [comment]
Hi junlincc.
Actually it was nodejs version and my ignorance to be blamed. I got 12.21, but upgraded to v14.17 and it x-filters work great. 
Will keep following the master branch update for further news.
