### ISSUE TITLE
[Advanced Analytics] Rolling function is not reflected in the title of data 

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15845]
**Is your feature request related to a problem? Please describe.**
Currently, when user using the advanced analytics rolling function, the function is not reflected in the data panel, which can be confusing. For example when i use cumsum, i still saw Count in the title of my data, but the data is cumsum:
<img width="1792" alt="Screen Shot 2021-07-22 at 2 19 56 AM" src="https://user-images.githubusercontent.com/81597121/126712768-d430c792-bec8-4a15-b5f0-923c664559ae.png">

**Describe the solution you'd like**
Can we change the data title if rolling function is applied?

**Describe alternatives you've considered**
Or can we a separated column for rolling function in data

**Comment by junlincc** [comment]
@zhaoyongjie let's verify in timeseries and push commit to timeseries Echarts only?

**Comment by zhaoyongjie** [comment]
> @zhaoyongjie let's verify in timeseries and push commit to timeseries Echarts only?

I know this issue. We need a design to rename these `derived columns`(rolling/time comparison/resample).

**Comment by rusackas** [comment]
Closing this since it's more feature request than bug report, and it's been open/silent for years. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
