### ISSUE TITLE
[chart][mixed time series chart] Mixed time series chart only show dashboard filter from query A 

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#15858]
#### How to reproduce the bug

1. Create a mixed time-series chart, a filter box, and add them into a dashboard. see sample dashboard below.
2. apply filter in the dashboard, you will see filter is applied to both queries in the mixed time-series chart.
![AYgZr9z3oV](https://user-images.githubusercontent.com/27990562/126745950-4ea265ff-771a-4d10-b5fd-4c50836b2903.gif)

3. open explore view from dashboard,
4. See filter carried from dashboard: only Query A has correct filter value, but not in Query B:

![Screen_Shot_2021-07-22_at_11_42_23_PM](https://user-images.githubusercontent.com/27990562/126746372-00737481-49a2-462c-9876-d9ba56428687.jpg)

### Environment

latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rumbin** [comment]
Confirming this bug for v 1.4.0
