### ISSUE TITLE
[Gallery]Remove filter plug-ins from Viz gallery 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#15850]
<img width="1138" alt="Screen Shot 2021-07-22 at 4 37 29 PM" src="https://user-images.githubusercontent.com/67837651/126721948-ea5edba8-0173-4fcd-ac7e-0cd0389603f2.png">

This happens when 
    "DASHBOARD_NATIVE_FILTERS": True,
    "DASHBOARD_CROSS_FILTERS": True,
    "DASHBOARD_NATIVE_FILTERS_SET": True,
    "DASHBOARD_FILTERS_EXPERIMENTAL": True,
    "ENABLE_EXPLORE_DRAG_AND_DROP": True,
    "UX_BETA": True,

**Comment by suddjian** [comment]
Not a bug, the charts are intended to be there with the `DASHBOARD_FILTERS_EXPERIMENTAL` flag set so that they can be placed in a dashboard in the style of the old filter box. We should revisit this UI, perhaps look into some kind of drag-and-drop interface from the filter bar.
