### ISSUE TITLE
[explore][table] Pagination showed when 'SERVER PAGINATION' option is unselected in raw records query mode

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15857]
Pagination showed when SERVER PAGINATION option is unselected in raw records query mode

### Expected results
when SERVER PAGINATION is unselected, pagination is not shown

### Actual results
when SERVER PAGINATION is unselected, pagination is still shown

#### Screenshots

https://user-images.githubusercontent.com/81597121/126744189-ac12cd82-2226-4614-ac01-0f65af7388ee.mov

#### How to reproduce the bug

1. Open table chart
2. go to raw records in Query mode
3. unselect SERVER PAGINATION

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by pabrahamusa** [comment]
Do anyone have a commit id for a working version fo this? I can see from other issues that it was working at some point.

**Comment by rusackas** [comment]
I think this is no longer an issue in current-era Superset. Closing this as stale since it's been silent for so long. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
