### ISSUE TITLE
Export Dashboard button cannot be hidden

### ISSUE THREAD

**Issue by Artem-fb** [apache/superset#15855]
There is no permission in roles which can hide button "EXPORT" Dashboard

### Expected results

should be permission for "export" dashboard button 

### Actual results

there is no permission for "export" dashboard button  
now permission "can read on dashboard" makes it possible to export Dashboard to json

#### Screenshots
http://prntscr.com/1en2xm0
http://prntscr.com/1en4qbx

#### How to reproduce the bug

1. Go to list roles create new role, add to this role only two permissions: "menu access on Dasboard"and "can read on Dashboard" 
2. Create new user which has only this role
3. Create some Dashboard and give access for this user 
4. Logout and Login as this new user
5. You can export dashboard to json and see sql queries for this dashboard

install 0.37.1 version, no export button will exist in dashboard menu
install 1.2.0 version this button will appear in dashboard menu

### Environment

- superset version: 1.2.0
- python version: 3.8

**Comment by junlincc** [comment]
good one! @rosemarie-chiu can you pass this request internally? Dashboard Export should be added to RBAC

**Comment by arkonchik** [comment]
So, if we want to disable this button I think we need to do just this https://i.imgur.com/clpi0ad.png
but it didn't work.
What i did wrong @junlincc ? 

diff --git a/superset-frontend/src/views/CRUD/data/dataset/DatasetList.tsx b/superset-frontend/src/views/CRUD/data/dataset/DatasetList.tsx
index 15a009699..93e8b5d42 100644
--- a/superset-frontend/src/views/CRUD/data/dataset/DatasetList.tsx
+++ b/superset-frontend/src/views/CRUD/data/dataset/DatasetList.tsx
@@ -151,7 +151,7 @@ const DatasetList: FunctionComponent<DatasetListProps> = ({
   const canEdit = hasPerm('can_write');
   const canDelete = hasPerm('can_write');
   const canCreate = hasPerm('can_write');
-  const canExport = hasPerm('can_read');
+  const canExport = False;

**Comment by kamalkeshavani-aiinside** [comment]
Another similar request.
From 1.2, "Import Dashboard" is moved from Settings->Dashboards list view. So now 'menu access on Import Dashboards' permission does not work anymore to hide this feature.

v1.0.1
<img src="https://user-images.githubusercontent.com/74634977/127244636-52f7293d-a58e-4a4f-8836-ebc136762527.png" height="400" >


So, even though user can not actually import dashboard without 'can import dashboard on Superset' permission, the UI button to Import Dashboard can not be hidden.

v1.2
![image](https://user-images.githubusercontent.com/74634977/127244693-8ebb2416-0711-4012-a77d-97b9433ad7e6.png)

**Comment by rosemarie-chiu** [comment]
cc @yousoph

**Comment by heoun** [comment]
@betodealmeida  , @junlincc  - has there been any follow up on this? There still does not seem to be a way to disable this.

**Comment by ElTarget** [comment]
我在URL后面添加"standalone=1"，可以只显示chart或dashboard
I add "standalone = 1" after the URL to display only chart or dashboard

**Comment by Artem-fb** [comment]
Hello guys! Any news on this issue?  @betodealmeida @junlincc 
Thanks in advance

**Comment by heoun** [comment]
@rosemarie-chiu @betodealmeida @junlincc  - Following up on this again. Its been 42 + days since this critical security feature has been open.

Any idea on timeline of this bug?

**Comment by Artem-fb** [comment]
hello guys! @betodealmeida @junlincc 
what about this problem? Do you have some estimate whet it will be done?

**Comment by rosemarie-chiu** [comment]
We fixed permission on import button but missed out on export button. Following up on this. @betodealmeida @yousoph

**Comment by Artem-fb** [comment]
Hi @eschutho! do you have any news?

**Comment by eschutho** [comment]
We've been discussing this issue and have found a short-term solution that we'll be working on. We should have a solution soon.

**Comment by Artem-fb** [comment]
@eschutho, hello! Another month has passed. Have you found a solution to this problem?

**Comment by hughhhh** [comment]
#17527 allows users to explicitly set can_export for any resource (Chart, Dashboard, etc)

**Comment by eschutho** [comment]
I'm closing this issue as per #17527 but feel free to reopen if you have any other findings related to this request.

**Comment by Artem-fb** [comment]
First of all thanks for this bug fix.
Hi guys, @betodealmeida, @eschutho could you help, please?
I've checked this https://github.com/apache/superset/commit/2e29f36e7885b693a0af2cf8b0b8ca86d2970f64 in the master and it exist and it exist in this tag https://github.com/apache/superset/releases/tag/v0.19.0
But why this changes are missing from 1.4.0 and 1.4.1? How can I get the oldest stable version with this solved issue?

**Comment by ChunshengZhao** [comment]
The problem still exists(v1.4.1).

**Comment by Artem-fb** [comment]
hello, @eschutho! You wrote that I can reopen this task if there are a problems.
But I can't do that 
I need your help. Please

**Comment by Artem-fb** [comment]
hello, guys! @betodealmeida @eschutho @hughhhh  
Could you please clearfy what version has this fix? Please, it's really important fix

**Comment by ChunshengZhao** [comment]
> hello, guys! @betodealmeida @eschutho @hughhhh Could you please clearfy what version has this fix? Please, it's really important fix

1.5 no export button.

**Comment by Paulo456** [comment]
set flag VERSIONED_EXPORT=True helps. then u can disable/enable can export
