### ISSUE TITLE
[explore][time series chart] SORT DESCENDING is not taking effect in data panel

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15859]
SORT DESCENDING is not taking effect in data panel

### Expected results

when SORT DESCENDING is selected，data will be sorted in DESC

### Actual results
when SORT DESCENDING is selected，data is in random order

#### Screenshots
<img width="1790" alt="Screen Shot 2021-07-22 at 11 49 46 PM" src="https://user-images.githubusercontent.com/81597121/126750226-c4aa3eac-4153-4aa2-b119-7e4db4accdcc.png">

#### How to reproduce the bug

1. open time series chart
2. Select sort by and select SORT DESCENDING option
3. run query and observe data panel

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
I believe this was resolved... it worked when I was tinkering with it the other day.
