### ISSUE TITLE
[cosmetic][dashboard edit] side menu of the dashboard component will scroll out of dashboard

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15862]
## Screenshot

https://user-images.githubusercontent.com/81597121/126758633-73a0ebb0-fff0-49a8-b71c-068b7b5a7754.mov

## Description

side menu of the dashboard component will scroll out of dashboard

**Comment by junlincc** [comment]
Top priority 🙏 @michael-s-molina please add top level tabs while testing as well.
