### ISSUE TITLE
[cosmetic][native filter] time range filter menu will go out of dashboard when user scroll 

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15861]
https://user-images.githubusercontent.com/81597121/126756640-3bfd4d44-bfec-4aa1-806f-c508a113bbd5.mov

## Description
time range filter menu will go out of dashboard when user scroll

**Comment by junlincc** [comment]
Same limitation from AntD component. 🤦🏾‍♀️ let's close all the popover, indicator etc on scroll to avoid this issue. 
@michael-s-molina @geido 🙏

**Comment by geido** [comment]
This is still under my radar. The first attempts failed as they would either create a bad experience or interfere with the native filters. We'll keep trying.

**Comment by rusackas** [comment]
I do believe this is fixed! Closing... but correct me if I'm wrong.
