### ISSUE TITLE
[dashboard][native-filter]Filter indicator overlay in Dashboard on scroll

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15873]
## Screenshot

<img width="1490" alt="Screen Shot 2021-07-23 at 11 06 09 AM" src="https://user-images.githubusercontent.com/81597121/126823332-4bb59efa-6f48-4f86-9735-b4eb2d678e91.png">

**Comment by junlincc** [comment]
there is an open issue for this one you may have to dig it out. and this is not easy to fix AFAIK.
