### ISSUE TITLE
[native filter] new time range filter initially show advance section then re-edit filer see advance section gone

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15871]
In preset 2021.29.0 dev, New time range filter initially show advance section then re-edit filer see advance section gone. Checked in superset master, also see advance section for time range filter, and this section stay when user re-edit time filter.

### Expected results
Time range filter do not have advance section

### Actual results

Time range filter have advance section initially, then edit the filter the advance section is gone

#### Screenshots

https://user-images.githubusercontent.com/81597121/126816833-8e882f30-ac5c-4295-bd6b-d7b6156f9ca8.mov

#### How to reproduce the bug

1. Create a time range filler
2. Observe the Configuration
3. Save time range filter and re-edit
4. In Preset (2021.29.0 dev) the advance section is gone, for superset master, advance section still there

### Environment

(please complete the following information):

- superset version: `master
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
I do remember Time range filter didn't have an advanced section. curious to know what changes caused this regression? 
@michael-s-molina 🙏
