### ISSUE TITLE
[dashboard] 'Download as image' in chart 3 dot menu on dashboard did not work

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15872]
'Download as image' in chart 3 dot menu on dashboard did not work

### Expected results

Chart can be downloaded as image when select

### Actual results
nothing is downloaded

#### Screenshots

<img width="1199" alt="Screen Shot 2021-07-23 at 10 34 30 AM" src="https://user-images.githubusercontent.com/81597121/126820243-a5f81aa2-b15b-4b91-bad2-0013f27a01de.png">

#### How to reproduce the bug

1. Go to  dashboard 
2. Open 3 dot menu of a chart on dashboard
3. Select ''Download as image'

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
I thought we fixed it a while back, now it's broken again 🤦🏾‍♀️

@michael-s-molina can you do some investigation what caused it? many thanks! 🙏
