### ISSUE TITLE
[pivot table] Totals for pivot table is not correct, not showing the sum of the rows/columns

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15875]
Totals for pivot table not correct, not showing the sum of the rows/columns

<img width="1484" alt="Screen Shot 2021-07-23 at 12 54 25 PM" src="https://user-images.githubusercontent.com/81597121/126836171-7a21fc34-c1e8-40c3-a976-1d75cdda59cc.png">

### Expected results

Totals will show sum of all columns and sum of all rows

### Actual results

Totals show sum of one columns and sum of one rows

#### How to reproduce the bug

1. Create a pivot table
2. Select 'Totals'
3. See error

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
Thanks for filing! We will NOT fix this issue but to accelerate the process of migrating Pivot table to Pivot table v2. 
assigning to @zhaoyongjie 
Task: Write a migration script and make sure the existing pivot table is showing properly in the v2. no need to address this pivot table issue specifically. 🙏
