### ISSUE TITLE
Sort By in Pivot Table

### ISSUE THREAD

**Issue by matthewphua** [apache/superset#15883]
Sort by field in pivot table does not work.
### Expected results

Enter a metric/custom sql for the pivot table to sort its entries. 

### Actual results

The sort by field is not implemented into the pivot table chart but it is visible in underlying query

#### Screenshots
Pivot table not sorted by max(rank) 
<img width="518" alt="Screen Shot 2021-07-23 at 4 49 20 PM" src="https://user-images.githubusercontent.com/85198947/126850832-b684b9c1-3ec9-400f-b642-c7a91984a231.png">

Visible in query
<img width="472" alt="Screen Shot 2021-07-23 at 4 47 54 PM" src="https://user-images.githubusercontent.com/85198947/126850776-1a54238f-5de7-4fc4-8b54-06ab64541c50.png">

**Comment by junlincc** [comment]
so... there's a sortby metric added to the south table/data, it's just not impacting the pivot table itself....
it seems to be a simple fix BUT we are not fixing it. pivot v2 doesn't support sort by metric yet, and it should. 
@kgabryje see if we can reach feature parity by mid august.

**Comment by kgabryje** [comment]
@matthewphua @junlincc Sort by in pivot table v1 seems to be working though

https://user-images.githubusercontent.com/15073128/126996248-4cd71144-38ab-4a13-8e26-52dcf026d1ee.mov

Anyway, implemented in v2 as well
https://github.com/apache-superset/superset-ui/pull/1240

**Comment by junlincc** [comment]
Pivot v1 and Table has different behavior on sort by metric(when it's different than the metric) .. anyway, for V2 we should at least show the data in the south table
