### ISSUE TITLE
Unable to display Chinese characters

### ISSUE THREAD

**Issue by OneRain233** [apache/superset#15884]
Chinese characters cannot be displayed
![image](https://user-images.githubusercontent.com/73395917/126864706-5f24847c-1d9a-4aba-914b-2a6e5094e91e.png)

**Comment by zhaoyongjie** [comment]
@OneRain233 It looks like a database codec issue. What database do you use? Could you share your database config?

**Comment by OneRain233** [comment]
![image](https://user-images.githubusercontent.com/73395917/126890822-25b3c2c3-69e0-413c-ae83-74e3d2a58cda.png)

**Comment by zhaoyongjie** [comment]
@OneRain233 Please refer to: https://stackoverflow.com/questions/10819192/sqlalchemy-result-for-utf-8-column-is-of-type-str-why

**Comment by OneRain233** [comment]
Ok, it works well now. Thanks very much.

**Comment by zhaoyongjie** [comment]
You are welcome!
