### ISSUE TITLE
clickhouse error: 'NoneType' object has no attribute 'startswith' 

### ISSUE THREAD

**Issue by lijc210** [apache/superset#15892]
superset==1.2.0

clickhouse error: 'NoneType' object has no attribute 'startswith'

**Comment by zhaoyongjie** [comment]
@lijc210, Please fill up the origianl issue template.  How to reproduce this issue? How do you config Clickhouse? How do you connect from Superset to Clickhouse?

**Comment by lijc210** [comment]
superset==1.2.0
clickhouse-sqlalchemy  0.1.6

clickhouse://ck_readonly:XXXXXXXXXX@xxx.xxx.xxx.xxx:8123/ads?secure=true

If the data from SQL query contains none, an error will be reported

clickhouse error: 'NoneType' object has no attribute 'startswith'

In addition, the page does not display the correct field name, and the first row of data will be used as the field name

**Comment by zhaoyongjie** [comment]
Which version of CK are you using?

**Comment by lijc210** [comment]
CK version 21.3.14.1

**Comment by lijc210** [comment]
@zhaoyongjie 

I solved this problem

I used this connection before
clickhouse://ck_readonly:XXXXXXXXXX@xxx.xxx.xxx.xxx:8123/ads?secure=true

Now use this connection，It works normally
clickhouse+native://ck_readonly:XXXXXXXXXX@xxx.xxx.xxx.xxx:9000/ads
