### ISSUE TITLE
Athena query execution

### ISSUE THREAD

**Issue by oscarxanda** [apache/superset#15894]
A query fails on Superset indicating lack of data lake permissions. The same exact query executes as expected on Athena's console, or using Athena's AWS SDK.
However this behaviour is not clear, as some queries do not fail. Adding the database name before the table however fixes the issue (this is not required when using Athena's UI or SDK however!).

### Expected results

The query should execute sucessfully.

### Actual results

Returns an error: awsathena error: Insufficient permissions to execute the query. Insufficient Lake Formation permission(s) on table

#### How to reproduce the bug

1. Create an Athena connection using an IAM role
2. Set permissions on AWS Data lake formation for that role
3. Attempt to execute a query.
### Environment

(please complete the following information):

Using the docker image available on git

superset version: superset version
Loaded your LOCAL configuration at [/app/docker/pythonpath_dev/superset_config.py]
logging was configured successfully
2021-07-21 08:52:52,080:INFO:superset.utils.logging_configurator:logging was configured successfully
2021-07-21 08:52:52,096:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
/usr/local/lib/python3.7/site-packages/flask_caching/init.py:202: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
"Flask-Caching: CACHE_TYPE is set to null, "
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Superset 0.999.0dev
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

python version: python --version
Python 3.7.9

node.js version: node -v
/bin/sh: 4: node: not found

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ X] I have reproduced the issue with at least the latest released version of superset.
- [ X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for multiple years, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
