### ISSUE TITLE
Global async query -  Unserializable object {} of type <class 'datetime.time'>

### ISSUE THREAD

**Issue by jerwen** [apache/superset#15905]
Impossible to render a chart, say a TableView, presenting a Time column when the global async query feature is enabled.

### Expected results

We expected the chart to be rendered with the data on display.

### Actual results

Error message on display.

#### Screenshots

<img width="1407" alt="Capture d’écran 2021-07-27 à 12 13 02" src="https://user-images.githubusercontent.com/20145870/127137342-1e86a9a7-545b-4665-b5ef-9b0bf76360a4.png">

#### How to reproduce the bug

1. Enable Global Async Query feature
2. Make sure to have a Redis configured for caching the result
3. Open a dashboard with a table view presenting a column Time
From the logs we have the following message
`{"asctime": "2021-07-27 13:46:01,004", "name": "superset.views.base", "levelname": "WARNING", "process": 18, "message": "Unserializable object 10:30:00 of type <class 'datetime.time'>"}`

### Environment

(please complete the following information):

- superset version: `1.2`
- python version: `3.7.9`
- node.js version: `Unknown`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I looked up in the code base to see where the message was coming from. I found out two different methods aiming to perform the same job which is to json serialize dates
```python
def json_iso_dttm_ser(obj: Any, pessimistic: bool = False) -> str:
    """
    json serializer that deals with dates

    >>> dttm = datetime(1970, 1, 1)
    >>> json.dumps({'dttm': dttm}, default=json_iso_dttm_ser)
    '{"dttm": "1970-01-01T00:00:00"}'
    """
    val = base_json_conv(obj)
    if val is not None:
        return val
    if isinstance(obj, (datetime, date, time, pd.Timestamp)):
        obj = obj.isoformat()
    else:
        if pessimistic:
            return "Unserializable [{}]".format(type(obj))

        raise TypeError("Unserializable object {} of type {}".format(obj, type(obj)))
    return obj


def json_int_dttm_ser(obj: Any) -> float:
    """json serializer that deals with dates"""
    val = base_json_conv(obj)
    if val is not None:
        return val
    if isinstance(obj, (datetime, pd.Timestamp)):
        obj = datetime_to_epoch(obj)
    elif isinstance(obj, date):
        obj = (obj - EPOCH.date()).total_seconds() * 1000
    else:
        raise TypeError("Unserializable object {} of type {}".format(obj, type(obj)))
    return obj
```
It seems to me that the second might be at fault here.

**Comment by rubypollev** [comment]
This bug is preventing us from rolling out this feature.

**Comment by frafra** [comment]
I can confirm that `json_int_dttm_ser` is the problem. This is my log:

```
superset_app            | Traceback (most recent call last):
superset_app            |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
superset_app            |     rv = self.dispatch_request()
superset_app            |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
superset_app            |     return self.view_functions[rule.endpoint](**req.view_args)
superset_app            |   File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/security/decorators.py", line 61, in wraps
superset_app            |     return f(self, *args, **kwargs)
superset_app            |   File "/app/superset/views/base_api.py", line 85, in wraps
superset_app            |     raise ex
superset_app            |   File "/app/superset/views/base_api.py", line 82, in wraps
superset_app            |     duration, response = time_function(f, self, *args, **kwargs)
superset_app            |   File "/app/superset/utils/core.py", line 1461, in time_function
superset_app            |     response = func(*args, **kwargs)
superset_app            |   File "/app/superset/utils/log.py", line 242, in wrapper
superset_app            |     value = f(*args, **kwargs)
superset_app            |   File "/app/superset/charts/api.py", line 726, in data
superset_app            |     return self.get_data_response(command)
superset_app            |   File "/app/superset/charts/api.py", line 543, in get_data_response
superset_app            |     return self.send_chart_response(result, form_data)
superset_app            |   File "/app/superset/charts/api.py", line 522, in send_chart_response
superset_app            |     ignore_nan=True,
superset_app            |   File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 412, in dumps
superset_app            |     **kw).encode(obj)
superset_app            |   File "/usr/local/lib/python3.7/site-packages/simplejson/encoder.py", line 296, in encode
superset_app            |     chunks = self.iterencode(o, _one_shot=True)
superset_app            |   File "/usr/local/lib/python3.7/site-packages/simplejson/encoder.py", line 378, in iterencode
superset_app            |     return _iterencode(o, 0)
superset_app            |   File "/app/superset/utils/core.py", line 614, in json_int_dttm_ser
superset_app            |     raise TypeError("Unserializable object {} of type {}".format(obj, type(obj)))
superset_app            | TypeError: Unserializable object 14:06:00 of type <class 'datetime.time'>
```

My setup is a standard Superset started using docker-compose, connected to a mssql database containing a table with a `TIME` column.

**Comment by frafra** [comment]
There are various places in the code where such method is used as default when dumping the JSON (look for `default=json_int_dttm_ser`):

https://github.com/apache/superset/blob/1669947bcd429e926c6e8de5ceaafcfe5496b28b/superset/charts/api.py#L518-L523

https://github.com/apache/superset/blob/0f16177bde156163643c55e5cd24fab996f40971/superset/utils/core.py#L618-L619

...and others.

Here is the problematic function:

https://github.com/apache/superset/blob/0f16177bde156163643c55e5cd24fab996f40971/superset/utils/core.py#L604-L615

It was meant to handle date, datetime, but not time. It actually uses a generic function before trying to dealing with date and datetime, such `base_json_conv`:

https://github.com/apache/superset/blob/0f16177bde156163643c55e5cd24fab996f40971/superset/utils/core.py#L550-L573

It would be enough to add a specific case:

```
> python3
Python 3.8.10 (default, May 05 2021, 15:36:36) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> str(datetime.time())
'00:00:00'
```
