### ISSUE TITLE
Cannot save a chart when schema is not selected in sql_lab

### ISSUE THREAD

**Issue by dharmic6** [apache/superset#15902]
Issue1: When schema is not specified in sql_lab, cant save a chart using the sql.
Issue2: Similarly, I can save the chart even though the schema specified in the sql_lab is wrong.

### Expected results

Sql_lab should verify the schema selected before exploring the data.

### Actual results

A user can select schema A, but write a query on schema B and save it. Superset saves it as a base on schema A which confuses later to know where is chart pulling data from.

#### How to reproduce the bug

1. make a query with no schema specified on the left side of the screen
![image](https://user-images.githubusercontent.com/25113963/127086127-106c180f-80a6-4a9c-b92f-929b84a2aecb.png)

2. hit explore and hit save and explore and save on the chart screen. 
![image](https://user-images.githubusercontent.com/25113963/127085964-f9d6d7b0-b906-4eaf-aefb-e1026165d582.png)
followed by 
![image](https://user-images.githubusercontent.com/25113963/127085991-8d65ee0a-dbc4-429f-bbb0-464cee785b9b.png)

3. Cant save the chart 
![image](https://user-images.githubusercontent.com/25113963/127086022-b78abc0c-a9f5-4efc-afda-b6f91fbc2b95.png)

### Environment

- superset version: `1.2.0`
- python version: `3.7`
- node.js version: `v16.5.0`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- 

- [ x] I have checked the superset logs for python stacktraces and included it here as text if there are any.

- [ x] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
