### ISSUE TITLE
Move cross-filtering control to data panel

### ISSUE THREAD

**Issue by villebro** [apache/superset#15910]
To make the cross-filtering feature stand out better, we should do the following changes to all ECharts control panels:
- Move the cross filter control from the "Customize" tab to the "Query" tab under the "(adhoc) filter" control.
- Rename from "Enable emitting filters" to "Emit dashboard cross filters"

If it's possible to make the code more generic (=avoiding copy-pasting the same control in many places etc), now would probably be a good time to do that.

**Comment by junlincc** [comment]
@stephenLYZ
