### ISSUE TITLE
Cursor jumps around when editing sql expression in calculated column

### ISSUE THREAD

**Issue by michellethomas** [apache/superset#15919]
If you edit a datasource and when entering a `sql expression` for a `Calculated Column` you can get into a weird state where the cursor jumps around while entering text. It seems to happen when you delete text already entered for `sql expression` and get the message `Calculated column [...] requires an expression` and then try to enter text again.

### Expected results

Cursor stays in the correct place as you enter text

### Actual results

Cursor jumps around as you enter text

#### Screenshots

![image](https://user-images.githubusercontent.com/817955/127236752-11e939b1-5480-409d-922b-3dc53fba50bb.png)

#### How to reproduce the bug

1. Edit datasource (I've tested this from the edit modal on explore view)
2. Create a calculated column
3. Enter text in sql expression
4. Remove the text so you get a message at the top `Calculated column [...] requires an expression`
5. Try to type text again

### Environment

(please complete the following information):

- superset version: `master`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
Hi @michellethomas, this issues should have been resolved on latest master. unless you are using PC. please lmk.

**Comment by michellethomas** [comment]
Oh thanks @junlincc ! Sorry my branch must have been a few days behind when I tested. Great the issue is resolved!
