### ISSUE TITLE
[x-filtering]emitting x-filtering from time series stacked bar should send out 2 filters 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#15913]
https://user-images.githubusercontent.com/67837651/127205188-0990d679-3bd8-4281-8354-fe7d2b02e9d6.mov

Expected behavior: When user click on the stacked bar in Time-series Echarts, is should emit 2 filters 1) time filter 2)series filter 

0. Create a Time-series chart and change the viz type to Bar in CUSTOMIZE, Enable stacked bar
1. Enable X-filtering 
2. Add any other charts that shares the same dataset 
3. Click on one series of one bar 
4. View query on other charts and see only one WHERE clause was added 

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
Adding support for emitting a time filter might require some additional work as we currently don't support time grain based filters. So I'd recommend putting this on the drill down/drill through project backlog and tackle that then once we have a better understanding of that roadmap.

**Comment by jamesrayoub** [comment]
would really love this feature! emitting a dimension/series filter on a time-series chart is not nearly as useful as filtering on a specific time grain

**Comment by rusackas** [comment]
@yousoph @kgabryje is this still of interest and/or on anyone's radar?

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
