### ISSUE TITLE
Unexpected DATETIME column happened to query when running the chart

### ISSUE THREAD

**Issue by StephLec76** [apache/superset#15924]
I'm using a dataset with many DATETIME columns (3 to be precise). Data coming from ElasticSearch.

I'm currently working with a bar chart (the issue is reproducable with other charts as well). I'm setting the "Time Column" element I want to filter my data on.

I expect that when running (press "Run" button) the chart, only the column I've picked (for the time section) is used to "compute" the query. 

But unfortunately the computed query is happened with one unexpected DATETIME column.

Therefore the resulting chart is wrong according to criterias.

Here is the "TIME COLUMN" item selected
![time column selected](https://user-images.githubusercontent.com/88092697/127323711-b3b5d51c-06a9-40ee-8a2a-05e65739585d.PNG)

Here is the query (retrieved by clicking on "View query" in the burger menu on top of the chart) that is performed against my dataset:
![created date passed](https://user-images.githubusercontent.com/88092697/127324029-197a5032-a495-449f-9447-f09e742af439.PNG)

So the steps are:
1. get a dataset which contains many DATETIME columns
2. create a bar chart
3. select one column for the Time section
4. Run the chart
5. Check the computed query

### Environment

- superset version: 1.2.0
- python version: 2.7.5

**Comment by villebro** [comment]
This sounds highly irregular! @StephLec76 are you able to reproduce this on master?

**Comment by StephLec76** [comment]
Yes the issue is still reproducable on master.

**Comment by junlincc** [comment]
@StephLec76 thanks for reporting, if you have the capacity to work on it, we will be happy to review the PR, otherwise we will look into it in 3-4 weeks.

**Comment by StephLec76** [comment]
I'll do my best in term of skills and time in regards to this 3-4 weeks time window

**Comment by StephLec76** [comment]
Hi,

I took a look to source code to try to figure out how to fix the issue.
It looks to complex in regards of my skills.

Is there any chance, someone could take a look and either fix it or provide further details about how the issue occur so that people could work it around?

Thanks in advance to anyone who would provide a feedback on this ticket

**Comment by DavidHowlett** [comment]
This issue is currently breaking the generation of some charts at my company. I am currently considering digging into the superset code and fixing it. Does anyone have any helpful pointers? Are there any other URLs with useful information or duplicate bugs that I should read? I am new to the superset codebase. I already know to read the contributing guidelines before creating a PR.

**Comment by changwuf31** [comment]
Comment this code on around Line 14xx at app/superset/connectors/sqla/models.py

Looks like this is dependent on your database engine.
```
# Use main dttm column to support index with secondary dttm columns.
#            if (
#                db_engine_spec.time_secondary_columns
#                and self.main_dttm_col in self.dttm_cols
#                and self.main_dttm_col != dttm_col.column_name
#            ):
#                time_filters.append(
#                    columns_by_name[self.main_dttm_col].get_time_filter(
#                        from_dttm,
#                        to_dttm,
#                    )
#                )
```

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
