### ISSUE TITLE
Not able to aggregate group by column

### ISSUE THREAD

**Issue by rahull95** [apache/superset#15926]
I recently migrated to Superset 1.1.0 from an older version. I have a column that I like to get distinct values of:

![image](https://user-images.githubusercontent.com/63130522/127338884-30d94dc3-7b92-41cd-8fc9-655287b6a680.png)

What I'd like to see as the query is this (this was what happened in the previous version):

```
SELECT lj_link
FROM table1
GROUP BY lj_link
LIMIT 5000;
```

Instead what I see is:

```
SELECT lj_link
FROM table1
LIMIT 5000;

```
I know we could create a work around by creating an aggregate field but I don't understand why aggregate would return just the raw records instead

Superset version: `1.1.0`

**Comment by rusackas** [comment]
This version of Superset is no longer supported. If anyone is still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
