### ISSUE TITLE
[scroll]inconsistent scrolls with sticky header 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#15935]
As we implement more sticky headers on tables and forms across the product lately to improve the user experience of viewing large context, the behavior of scroll bars start falling out of shape. 

Scroll in Change dataset modal 
Problem: place scroll bar between header and the bottom of last row item, should not extend to the pagination area
<img width="878" alt="Screen Shot 2021-07-28 at 10 41 38 AM" src="https://user-images.githubusercontent.com/67837651/127398200-713c6564-496b-4bbf-b82b-bcf05401ba26.png">

Scroll on table 
Work as expected. between the top of the first row and bottom of last row 
https://user-images.githubusercontent.com/67837651/127396629-cc0ca091-9e44-4ecc-9646-f55090a547b2.mov

Scroll on Pivot table v2 On dashboard, without a horizontal scroll
Problem: scroll bar is detached from the table, scroll bar is extended to the top of the header 
https://user-images.githubusercontent.com/67837651/127397232-c3c88d9a-81c9-42fc-8673-a4e7391f854c.mov

Scroll on Pivot table v2 On dashboard, with a horizontal scroll
Problem: scroll bar is extended to the top of the header 
https://user-images.githubusercontent.com/67837651/127397457-74a3cf94-a472-467c-9a71-79fd9917a688.mov

Scroll on Pivot table v1 on dashboard with a horizontal scroll 
Problem: see screen shot, but we can skip addressing this one.. 
<img width="618" alt="Screen Shot 2021-07-28 at 11 20 28 AM" src="https://user-images.githubusercontent.com/67837651/127397891-af1b7325-9dbe-4229-82b2-a27669e554be.png">

There are more scrolls on sticky in the product, I'm listing a few for now. We should spend a cycle polishing standardize this behavior like we are doing for Select and other components.

**Comment by junlincc** [comment]
@geido higher priority than omnibar 🙏 also can we have an audit?

**Comment by geido** [comment]
@junlincc unfortunately only some of the asks in this issue are feasible without an extensive refactor of the tables throughout the whole project. I will create separate PRs with what I can achieve without having to rewrite them entirely.

**Comment by geido** [comment]
@junlincc I am moving this to you as there isn't much more that we can do without a full refactor. Let me know how you want to approach this. Thank you!

**Comment by rusackas** [comment]
I believe the bulk of this has been resolved. If anyone spots any instances that need addressing, let's open individual Issues for each.
