### ISSUE TITLE
Export CSV in public role [dashboard]

### ISSUE THREAD

**Issue by solomoup** [apache/superset#15943]
I need to share a dashboard with anonymous users (without login) and these users must have the option to export the data of each chart on the dashboard as a CSV. So I added the "can csv on Superset" permission to Public Role. But as you can see in the screenshot below there is no "Export CSV" option. In the Admin Role however everything works fine.
![image](https://user-images.githubusercontent.com/67665217/127502376-c29de35d-222c-49c1-9c41-1f5ad88ee222.png)

**Comment by tmanolat** [comment]
We face the same issue - any thoughts from the community would be precious

**Comment by justin-tomlinson** [comment]
I still have this issue in 1.5.0

**Comment by justin-tomlinson** [comment]
even if you change the guest role to from public to another higher level role like Gamma, the permission doesnt add the option in the embedded dashboard. Im not sure if #20261 is the fix for this

**Comment by duonghuyom** [comment]
has anyone can fix this problem ?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and is a feature request rather than a bug. If this is relevant in current versions (currently 3.x) please open a new Ideas discussion or a PR to address the problem.
