### ISSUE TITLE
[d&d][pivot table 2] Drag and drop rows to column result in error

### ISSUE THREAD

**Issue by rosemarie-chiu** [apache/superset#15945]
With Drag and Drop, Cross filtering, Native filter, and Beta UX Feature flags enabled.

I was trying to switch rows and column on pivot table 2 by drag & drop and encounter error

### Expected results
Can drag and drop to switch row <-> column successfully

### Actual results
https://user-images.githubusercontent.com/52086618/127515642-276f5de9-9c20-46c1-9bef-c7a70fa9fa2e.mov

#### How to reproduce the bug
1. In Explore, create a pivot table 2
2. Drag and drop columns, rows, metrics and hit run
3. Try to change data column from row to column

### Environment
Latest master
With Drag and Drop, Cross filtering, Native filter, and Beta UX Feature flags enabled

**Comment by junlincc** [comment]
Thanks for catching! Cross-fields DND is not yet supported, but we should. @kgabryje let's try to get it done by 8/12 🙏

**Comment by kgabryje** [comment]
Huh, I know that we can't move between rows and columns, but it shouldn't be causing an error... Thanks for catching! I'll look into it on Monday

**Comment by kgabryje** [comment]
Fixed by https://github.com/apache/superset/pull/16020
