### ISSUE TITLE
[pivot table v2] no remove button for DATE format

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15947]
[pivot table v2] no remove button for DATE format

### Expected results

User can remove date format and use original format

### Actual results

User can not remove date format (not consistent behavior as value format)

#### Screenshots

<img width="1791" alt="Screen Shot 2021-07-29 at 9 18 04 AM" src="https://user-images.githubusercontent.com/81597121/127528820-04f1c952-c09d-4ae0-9b35-6b6d4eaff6cf.png">

#### How to reproduce the bug

1. Go to CUSTOMIZE panel
2. Observe DATE FORMAT option

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by jinghua-qa** [comment]
@kgabryje

**Comment by kgabryje** [comment]
https://github.com/apache-superset/superset-ui/pull/1261
