### ISSUE TITLE
Problems with Public role after upgrading from apache superset 1.1.0 to 1.2.0 version

### ISSUE THREAD

**Issue by ghost** [apache/superset#15940]
Hello! I've been running an 1.1.0 version of Superset without a problem, where I embed some dashboards on my website and through the Public user role permissions it is possible to see and use the dashboards.

In order to fix an issue ( https://github.com/apache/superset/issues/13544 ), we decided to upgrade to 1.2.0

However, after updating to version 1.2.0 I've been having problems providing public access to my dashboards. I get "Unexpected error: TypeError: can't convert undefined to object" message when before I was able to access the dashboard.

#### Below is the Superset upgrade log information (from 1.1.0 to 1.2.0)

#pip install apache-superset --upgrade

#export SUPERSET_CONFIG_PATH=/home/ubuntu/supersetconf/superset_config.py

$superset db upgrade

Loaded your LOCAL configuration at [/home/ubuntu/supersetconf/superset_config.py]
logging was configured successfully
2021-07-29 08:25:06,295:INFO:superset.utils.logging_configurator:logging was configured successfully
2021-07-29 08:25:06,302:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
/home/ubuntu/venv-superset/lib/python3.7/site-packages/flask_caching/__init__.py:202: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  "Flask-Caching: CACHE_TYPE is set to null, "
No PIL installation found
2021-07-29 08:25:06,731:INFO:superset.utils.screenshots:No PIL installation found
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.

$ superset init

Loaded your LOCAL configuration at [/home/ubuntu/supersetconf/superset_config.py]
logging was configured successfully
2021-07-29 08:25:39,035:INFO:superset.utils.logging_configurator:logging was configured successfully
2021-07-29 08:25:39,042:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
/home/ubuntu/venv-superset/lib/python3.7/site-packages/flask_caching/__init__.py:202: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  "Flask-Caching: CACHE_TYPE is set to null, "
No PIL installation found
2021-07-29 08:25:39,249:INFO:superset.utils.screenshots:No PIL installation found
Syncing role definition
2021-07-29 08:25:41,275:INFO:superset.security.manager:Syncing role definition
Syncing Admin perms
2021-07-29 08:25:41,302:INFO:superset.security.manager:Syncing Admin perms
Syncing Alpha perms
2021-07-29 08:25:41,523:INFO:superset.security.manager:Syncing Alpha perms
Syncing Gamma perms
2021-07-29 08:25:41,733:INFO:superset.security.manager:Syncing Gamma perms
Syncing granter perms
2021-07-29 08:25:41,944:INFO:superset.security.manager:Syncing granter perms
Syncing sql_lab perms
2021-07-29 08:25:42,185:INFO:superset.security.manager:Syncing sql_lab perms
Copy/Merge Public to Public
2021-07-29 08:25:42,414:INFO:superset.security.manager:Copy/Merge Public to Public
Fetching a set of all perms to lookup which ones are missing
2021-07-29 08:25:42,423:INFO:superset.security.manager:Fetching a set of all perms to lookup which ones are missing
Creating missing datasource permissions.
2021-07-29 08:25:42,736:INFO:superset.security.manager:Creating missing datasource permissions.
Creating missing database permissions.
2021-07-29 08:25:42,749:INFO:superset.security.manager:Creating missing database permissions.
Cleaning faulty perms
2021-07-29 08:25:42,751:INFO:superset.security.manager:Cleaning faulty perms

#### How to reproduce the bug

Install Superset version 1.1.0
upgrade to Superset version 1.2.0

### Environment

- superset version: 1.2.0
- python version: 3.7.5

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by ElTarget** [comment]
UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
"Flask-Caching: CACHE_TYPE is set to null, " 
显示内容：缓存类型设置为null，缓存被有效禁用。缓存类型设置为空。原因是因为初始化config.py还没配置好。

解决办法：缓存配置为redis
DATA_CACHE_CONFIG = {
    'CACHE_TYPE': 'redis',
    'CACHE_DEFAULT_TIMEOUT': 60 * 60 * 24,  # 1 day default (in secs)
    'CACHE_KEY_PREFIX': 'superset_results',
    'CACHE_REDIS_URL': 'redis://localhost:6379/0',
}
CACHE_CONFIG = {
    'CACHE_TYPE': 'redis',  # 使用 Redis
    'CACHE_REDIS_HOST': '192.168.0.134',  # 配置域名
    'CACHE_REDIS_PORT': 6379,  # 配置端口号
    'CACHE_REDIS_URL': 'redis://192.168.0.134:6379'  # 配置 URL
}


No PIL installation found ，you need pip install pillow。

**Comment by bill-tulskie** [comment]
ElTarget, can you please elaborate regarding your comment?  will 'pip install pillow' fix this problem?

**Comment by ElTarget** [comment]
Because the prompt:&nbsp;No PIL installation found




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月20日(星期五) 上午9:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/superset] Problems with Public role after upgrading from apache superset 1.1.0 to 1.2.0 version (#15940)






El Target ，你能详细解释一下你的评论吗？' pip 安装枕头'能解决这个问题吗?

—
你收到这个是因为你评论了。
直接回复此邮件，在 GitHub 上查看或取消订阅.
GitHub Mobile 上的分流通知监督办或机器人.

**Comment by alemarte** [comment]
Unfortunately we encounter the same problem upgrading to 1.2.
After investigating the root cause, it seems that user roles fetched from the state are undefined when hydrating the Dashboard and it crash the redux flow.
I've implemented a workaround to temporary fix the bug here https://github.com/alemarte/superset/commit/3cb51820cae0beb5f76597ed9d885061cd3090f7

**Comment by rusackas** [comment]
Closing this since it's gone quiet, and we no longer support 1.2... or even a few versions after that. I hope you found a way in the end! 🤞
