### ISSUE TITLE
Time Series Table Numbers are cut off

### ISSUE THREAD

**Issue by matthewphua** [apache/superset#15957]
The numbers on the edges of a time series table sometimes may get cut off. It would seem like they should properly fit within the container size and not get cut off. Maybe a potential solution would be to alter the spacing between the graph and table text. 

<img width="419" alt="Screen Shot 2021-07-29 at 2 09 47 PM" src="https://user-images.githubusercontent.com/85198947/127566252-eb601c9f-8ba9-4915-895e-53003511762e.png">

**Comment by junlincc** [comment]
@geido 🙏
