### ISSUE TITLE
[Advanced Analytics][line chart] 2nd time shift option is not shown on the chart and tooltip show same value as 1st time shift

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15968]
2nd time shift option is not shown on the chart and tooltip show same value as 1st time shift 

### Expected results
2nd time shift also shown on the chart and tooltip show correct value

### Actual results

2nd time shift not shown on the chart and tooltip show same value as 1st time shift

#### Screenshots

<img width="1792" alt="Screen Shot 2021-07-29 at 7 55 19 PM" src="https://user-images.githubusercontent.com/81597121/127616121-18a19d9a-b29b-4f03-8faa-aeb8535f3431.png">

#### How to reproduce the bug

1. use 'cleaned_sales_data', create line chart with Sum(sales)
2. in Advance Analytics, choose time shift "1 year ago" and "1 year later", and show actual value
3. observe error on the chart

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by jinghua-qa** [comment]
@zhaoyongjie

**Comment by rusackas** [comment]
@jinghua-qa do you know if this is still an issue these days?

**Comment by zhaoyongjie** [comment]
Hi @rusackas, I think this issue is about Legacy Line Chart viz, the Line Chart v2 can't reproduce.
