### ISSUE TITLE
deck.gl Polygon does not work when column name is "Polygon" or "polygon"

### ISSUE THREAD

**Issue by sarthak** [apache/superset#15965]
deck.gl Polygon chart does not appear to work when the column name corresponding to polygon is 'Polygon' or 'polygon'.

### Expected results

A polygon to be rendered.

### Actual results

Error message `An error occurred while rendering the visualization: TypeError: right-hand side of 'in' should be an object, got undefined`.

#### Screenshots

_Not needed_

#### How to reproduce the bug

1. Go to SQL Lab > Query Editor
2. Type this query 
```sql
SELECT '[[-106.69921875,46.92025531537451],[-116.19140625,37.996162679728116],[-90.17578124999999,32.99023555965106],[-106.69921875,46.92025531537451]]'
AS polygon
```
3. Click Run and then Explore
4. Select chart type as deck.gl Polygon, and polygon column as polygon.
5. Press Run, error message will be displayed
6. Now, click on edit dataset, press the lock icon
7. Change the query by renaming polygon -> contour
8. Click Save
9. Click again on edit dataset, and go to columns and click sync columns from source, then click save again
10. Go back to chart and change polygon column to contour.
11. Re run the chart, now a triangle should be visible over the united states.

### Environment

Using `docker-compose`, so latest version from master.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

This is a serious issue, for a chart called deck.gl polygon, a column name polygon not working is deal breaker.

**Comment by sfirke** [comment]
I'm getting this error on a bar chart v2, as the result of adding annotations.  Did you have annotations on this chart?

**Comment by rusackas** [comment]
Is anyone still experiencing this in Superset 3.x? I'm quite tempted to close this as stale, but it seems like just an edge case that likely hasn't been fixed. Not sure the repro steps for the bar chart bug — is that also failing with a column named "polygon" or is that a separate thing?

**Comment by rusackas** [comment]
Closing this as stale, but happy to revisit/reopen if folks are still facing this in 4.x. Maybe @dosu-bot can leave some helpful thoughts here as well, just for good measure :)
