### ISSUE TITLE
[chart viz] Tooltip and Adaptative formatting of Time of first data point did not show correct timestamp

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15963]
Tooltip and Adaptative formatting of Time of first data point did not show correct timestamp, i found this issue in many charts, like time-series, line, area etc.

### Expected results

Time format of Tooltip and X-Axis of First data  should show month, which is same as other data on the chart

### Actual results

Time format of Tooltip and X-Axis of First data  should show year,  while the other data show month

#### Screenshots
First data on the chart did not show correct timestamp, only show '2004'
<img width="1787" alt="Screen Shot 2021-07-29 at 8 23 40 PM" src="https://user-images.githubusercontent.com/81597121/127596208-8aaf7cad-23ca-411d-92c2-7f455e4c2ff3.png">

This is expected:
<img width="1788" alt="Screen Shot 2021-07-29 at 8 23 51 PM" src="https://user-images.githubusercontent.com/81597121/127596079-2a68d282-1e4f-4e50-8d17-fde48409106a.png">

.

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
It seems this has gone stale, but I'm also seeing that the tooltips match the ticks, which is an improvement over the reported issue.
