### ISSUE TITLE
[Advance Analytics][Time series chart] period is not work for rolling function 'cumsum' 

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15974]
period is not work for rolling function 'cumsum' 

### Expected results

cumsum can be calculated on defined period

### Actual results

cumsum is not affected by different period

#### Screenshots
Setting different period is not changing the cumsum value
<img width="1789" alt="Screen Shot 2021-07-30 at 1 30 47 AM" src="https://user-images.githubusercontent.com/81597121/127631726-75257a7d-a1dc-4763-9564-601efaf62de5.png">
<img width="1789" alt="Screen Shot 2021-07-30 at 1 30 37 AM" src="https://user-images.githubusercontent.com/81597121/127631738-7fd1a08a-6611-499c-84c4-6c250e87ee89.png">
 on defined period

#### How to reproduce the bug

1. Go to rolling function of time-series chart, select 'cumsum'
2. Select different period
3. Observe data panel and compare result for different period
4. cumsum is same for different periods

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by jinghua-qa** [comment]
@zhaoyongjie

**Comment by junlincc** [comment]
this is an existing behavior/bug in nvd3. 😞 let's not fix it before we have a new design for AA as a whole @zhaoyongjie

**Comment by Shazad-khan** [comment]
![image](https://user-images.githubusercontent.com/100838455/226568661-7ba93061-43c4-4213-8bd9-ab557da85be9.png)

![image](https://user-images.githubusercontent.com/100838455/226568994-99b23306-b56c-4040-a753-bbd2db42f5d7.png)

I have tested this issue and in the current version i felt like its working as expected

**Comment by benrapport** [comment]
hello -- believe that this has become an issue again. Seeing this same pattern of cumsum producing anomalous data results

**Comment by Shazad-khan** [comment]
Hi --  Can you add a screen shot with the steps required to reproduce the same which you are facing.

**Comment by rusackas** [comment]
Sounds like this isn't an issue anymore, but if it is, please open a new Issue with updated context and a reproducible example. Thanks!
