### ISSUE TITLE
[explore]RUN in chart area is missing + Run in panel is not highlighted on switching viz

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15973]
### Expected results

when change chart type, run button should show and the "run" in data panel should be highlighted

### Actual results

when change chart type, run button not showed and the "run" in data panel  is not highlighted

#### Screenshots

https://user-images.githubusercontent.com/81597121/127630867-80b8c909-0b2e-4b5e-b3c6-eaf5f7d737eb.mov

#### How to reproduce the bug

1. open a chart
2. Click chart type and change to another chart 
3. See error

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
regression from gallery modal redesign. @suddjian can you take a look? 🙏

**Comment by jinghua-qa** [comment]
Before we have run button shown when change chart type 
<img width="1528" alt="Screen Shot 2021-07-30 at 10 57 53 AM" src="https://user-images.githubusercontent.com/81597121/127693509-bca9602a-76b9-4fca-bc01-dc8889f77db4.png">

**Comment by suddjian** [comment]
I tried the repro steps and can't repro. @jinghua-qa can you provide what feature flags you're running with  and possibly steps involving specific chart types?

**Comment by jinghua-qa** [comment]
> I tried the repro steps and can't repro. @jinghua-qa can you provide what feature flags you're running with and possibly steps involving specific chart types?

I turned on D&D, Dashboard native filter,Dashboard filter set and cross filter. I think it is d&d related, can you try if you can reproduce with DD feature flag?
