### ISSUE TITLE
[cosmetic][time range] Time range option are in random order with user selection

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15972]
Time range option are in random order with user selection, can we make option in Alphabet order?
<img width="595" alt="Screen Shot 2021-07-30 at 1 52 39 AM" src="https://user-images.githubusercontent.com/81597121/127628637-1e14522c-4e44-4459-93c7-65e6bb91fd80.png">
<img width="578" alt="Screen Shot 2021-07-30 at 1 52 29 AM" src="https://user-images.githubusercontent.com/81597121/127628643-8ee782cd-4978-41cf-899b-24d951ffe983.png">
![image (2)](https://user-images.githubusercontent.com/81597121/127628652-2ad99a45-1013-414c-8e1a-73db5b71f17e.png)

**Comment by rusackas** [comment]
There was a [PR opened](https://github.com/apache/superset/pull/17976) to resolve this thread by changing the behavior of the Select component, but it was decided that we should keep the behavior consistent throughout the application. For that reason, I'll close this as a "won't fix" issue. 

That said, the order of the list here IS pretty questionable. I could see sorting alphabetically, or by usage, or by complexity. Maybe @jess-dillard will want to take this issue into consideration in a larger design-revisit.
