### ISSUE TITLE
[Add Database] Adding Apache Druid database entry is broken

### ISSUE THREAD

**Issue by vivek-kandhvar** [apache/superset#15976]
### Expected results

Should be able to add Apache Druid database entry, when a valid and working SQLALCHEMY URI is specified.

### Actual results

The UI fails to make an api request and hence doesn't add an entry for the druid database.
However, test connection works well.

#### Screenshots

![image](https://user-images.githubusercontent.com/29149291/127643236-242fde30-1ed4-427d-980c-d4c796317dce.png)

#### How to reproduce the bug

1. Go to 'Data -> Databases'
2. Click on '+Database button' 
3. Scroll down to 'Supported databases dropdown' and select Apache Druid
4. Enter a valid url of the druid database
5. Click Connect, and nothing happens
4. Open browser console to see error

### Environment

(please complete the following information):

- superset version: `master`
- python version: `Python 3.8.2`
- node.js version: `v12.21.0`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by vivek-kandhvar** [comment]
The issue is because of this code which was recently merged - https://github.com/apache/superset/pull/15801/files#diff-71cc773d8c82d06647d0f3627aba355398f065d15df3f96a25b4ae19bf1f79beR560

**Comment by junlincc** [comment]
thanks for reporting, @vivek-kandhvar are you on master or 1.2? im confused.

**Comment by vivek-kandhvar** [comment]
Oh sorry, I am on master.

**Comment by junlincc** [comment]
@betodealmeida 🙏

**Comment by junlincc** [comment]
Prioritized!

**Comment by betodealmeida** [comment]
Working on it.

**Comment by jinghua-qa** [comment]
test case updated
