### ISSUE TITLE
[cosmetic][home page] Alignment of the add button in each section

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15983]
I think the add button for each section on homepage should be align to the left?

## Screenshot
<img width="1781" alt="Screen Shot 2021-07-30 at 11 07 23 AM" src="https://user-images.githubusercontent.com/81597121/127694480-0e84f7b8-89f0-4d12-918d-c57aafd1002e.png">

**Comment by junlincc** [comment]
I think the homepage should be redesigned from scratch. the overall UX goes down every time we try to make an incremental change to address specific issues/complaints, where non of them was actually critical. I suggest not to make small changes anymore from this point until we have large amount of user data to support a change. 

@mistercrunch @rusackas

**Comment by rusackas** [comment]
If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
