### ISSUE TITLE
[Question] Can I define a new method notification?

### ISSUE THREAD

**Issue by nvlong198** [apache/superset#15999]
Currently, we can alert & report send to email/slack, but I want them to send to my 3rd app or simply save a snapshots' dashboard to the file system.
Is there any way to config a new method of notification and action for each method?
![image](https://user-images.githubusercontent.com/23328191/127774857-484b21ae-a8b8-4b69-b578-c5542cf96f16.png)

**Comment by nytai** [comment]
You would need to change source code to support this
