### ISSUE TITLE
[pivot table v2] Same metric added multiples times will show sum in pivot table v2

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15997]
Same metric added multiples times will show sum in pivot table v2 rather than showing multiple same metrics

### Expected results

Same metric added multiples times will show multiple same metrics

### Actual results

Same metric added multiples times will show sum

#### Screenshots

<img width="1493" alt="Screen Shot 2021-08-01 at 2 15 43 AM" src="https://user-images.githubusercontent.com/81597121/127765933-a2f60764-b1f2-44f5-ac95-a554d8398767.png">
<img width="1492" alt="Screen Shot 2021-08-01 at 2 16 31 AM" src="https://user-images.githubusercontent.com/81597121/127765936-8c937b3a-7ce5-45e1-944f-f5ce5741a8fa.png">

#### How to reproduce the bug

1. open pivot table v2 with a dataset
2. add the same metrics multiple times
3. observe the table

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by jinghua-qa** [comment]
@kgabryje

**Comment by junlincc** [comment]
i'm not sure if we should allow the same metric being added twice, i remember we have discussed this in pivot(legacy) and table before. 
Thanks for QAing this is awesome!!

**Comment by mistercrunch** [comment]
Solution is probably to improve `MetricControl` and add a new `allowDuplicates` prop that is `false` by default. I don't think we have any place where we need to allow duplicates. This could be categorized `P3`

**Comment by kgabryje** [comment]
Fixed by https://github.com/apache/superset/pull/16020

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
