### ISSUE TITLE
[d&d]Only show tooltip when full text doesn't fit + close tooltip as Drag starts

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15996]
Reordering in 'FILTERS'/'GROUP BY' with drag and drop will be blocked when the tooltip showed.

### Expected results

Reordering in 'FILTERS'/'GROUP BY' with drag and drop will  not be blocked

### Actual results

Reordering in 'FILTERS'/'GROUP BY' with drag and drop will be blocked when tooltip is showed in the way, user need to drag in a direction to avoid blocking by the tooltip

#### Screenshots

https://user-images.githubusercontent.com/81597121/127755037-06ef6cba-a6c6-49a3-812d-47e1a5a9a2d6.mov

#### How to reproduce the bug

1. Enable drag and drop 
2. In Filter or Group-by, drop multiple 
3. wait for tooltip and do drag and drop

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by jinghua-qa** [comment]
For tooltip with long name, it is blocking the window of the above filter and hard to move filter up with d&d
<img width="321" alt="Screen Shot 2021-08-01 at 3 05 35 PM" src="https://user-images.githubusercontent.com/81597121/127786640-4100c6c3-27db-4276-b079-f80b61ba52b6.png">

**Comment by junlincc** [comment]
Thanks for filing, this is awesome!! @jinghua-qa

**Comment by mistercrunch** [comment]
We should never show a tooltip that repeats the exact same text as the component. I noticed this is many places in Explore. I also would advocate for info bubbles (the little `i` with a circle around it as the trigger point for the tooltip when it provides extra information)

**Comment by junlincc** [comment]
@mistercrunch technically difficult if we wanna show long text, as the panel is resizable. we can remove behind feature flag UX_Beta though.

**Comment by junlincc** [comment]
@rusackas @michael-s-molina I renamed this issue, since user can always resize the panel to show all text, i am totally fine with removing tooltip. let's put it behind UX_BETA.

**Comment by kgabryje** [comment]
In that case, should we also remove the limit of 33% max width for the resizable panels?

**Comment by junlincc** [comment]
> In that case, should we also remove the limit of 33% max width for the resizable panels?

let's do it. but it will increase the QA workload. or increase the max to 40%/50%? @michael-s-molina need some experiment.

**Comment by junlincc** [comment]
https://user-images.githubusercontent.com/67837651/127862880-94ebfaa1-ef35-465d-a24a-6a288399bf24.mov
