### ISSUE TITLE
clearer instructions in the Swagger API Docs how to set the CSRF token

### ISSUE THREAD

**Issue by EMCP** [apache/superset#16003]
### Motivation

I've been trying to get started with a basic empty apache superset.. and add a single data source (Postgresql).  So far I accidentally started wiring it via `superset -set-database-uri` which I later learned will change my apache supersets backend... not start examining my data.. no problem I start switching to the REST api.. but then I get stuck on the create database step because of CSRF 

### Proposed Change

On the Swagger API docs (and perhaps the part around `superset -set-database-uri` make it cleaer what we're doing with databases.. even just a simple prompt in the `superset --help` telling me to go examine the REST api can clue me in .. in places where I should not be trying to use the CLI

### New or Changed Public Interfaces

In the Swagger Docs I just need to know where or how to set the CSRF token... I am almost there but.. just not sure where FLASK is expecting to find the CSRF token.. so I just get constant 400 errors when trying to create my first DB

```
Traceback (most recent call last):
  File "/scratch.py", line 96, in <module>
    response = create_db_connection(jwt_token=bearer_tokens['access_token'], db_ip=db_host, db_port=db_port, username=db_user, password=db_password, db_name=db_name)
  File "/scratch.py", line 43, in create_db_connection
    response.raise_for_status()
  File "/home/emcp/anaconda3/envs//lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: BAD REQUEST for url: http://someip:8088/api/v1/database/
```

**Comment by EMCP** [comment]
response.text reads

```
'{"errors": [{"message": "400 Bad Request: The CSRF token is missing.", "error_type": "GENERIC_BACKEND_ERROR", "level": "error", "extra": {"issue_codes": [{"code": 1011, "message": "Issue 1011 - Superset encountered an unexpected error."}]}}]}'
```

**Comment by EMCP** [comment]
additionally noticed the public docs do not list the `api/v1/security/csrf_token` .. only when i go to the live swagger docs hosted on my instance

**Comment by nytai** [comment]
You need to include the header `X-CSRFToken` with the token. Yes public docs have not been updated in a while.

**Comment by nytai** [comment]
I opened a PR to update the api docs: https://github.com/apache/superset/pull/16005

You can configure superset to disable CSRF protection: https://superset.apache.org/docs/installation/configuring-superset#configuration

**Comment by EMCP** [comment]
That sounds great,

I'm trying to hit the ground running with as secure an installation as possible, but I understand I could disable if needed.

I posted my sequence of events and even tried that `X-CSRFToken` in the header.. but will try again 

full code at https://stackoverflow.com/questions/68614350/cannot-post-a-new-db-to-apache-superset-400-error-with-csrf

**Comment by EMCP** [comment]
just want to confirm, I got it to work finally after a bit of your help.  thank you @nytai !

For others

```
    sqlalchemy_url = "postgresql://" + db_user + ":" + db_pass + "@" + db_ip + ":" + str(db_port)+"/" + db_name

    data_out = {
      "allow_csv_upload": True,
      "allow_ctas": True,
      "allow_cvas": True,
      "allow_dml": True,
      "allow_multi_schema_metadata_fetch": True,
      "allow_run_async": True,
      "cache_timeout": 0,
      "database_name": db_name,
      "expose_in_sqllab": True,
      "impersonate_user": True,
      "sqlalchemy_uri": sqlalchemy_url
    }

    head = {
        "Authorization": "Bearer " + bearer_token,
        "X-CSRFToken": csrf_token
    }

    response = session.post(url=url, headers=head, json=data_out)
    response.raise_for_status()

    return response
```

**Comment by EMCP** [comment]
After I created the connection seems to be unhappy.. I am diffing it with a connection I made manually.. seems I need to make sure to add certain things like

```
{
    "metadata_params": {},
    "engine_params": {},
    "metadata_cache_timeout": {},
    "schemas_allowed_for_csv_upload": []
}

```

in the extras section

**Comment by EMCP** [comment]
Closing issue is okay from my side.. 

I now have a working JSON to pass which seems to get a good test connection on POSTGresQL

```
    data_out = {
      "allow_csv_upload": True,
      "allow_ctas": False,
      "allow_cvas": False,
      "allow_dml": False,
      "allow_multi_schema_metadata_fetch": False,
      "allow_run_async": False,
      "cache_timeout": 0,
      "database_name": db_name,
      "expose_in_sqllab": True,
      "impersonate_user": False,
      "sqlalchemy_uri": sqlalchemy_url
    }

```

**Comment by nytai** [comment]
closing this for now as it seems the core issue is resolved
