### ISSUE TITLE
[d&d][bubble chart] 'Bubble size' seems able to accept drop from 'Metric for color' and Run query will lead to chart fail

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16007]
'Bubble size' seems able to accept drop from 'Metric for color' without any highlight, after drop a component, the Run button will show, but the 'Bubble size' did not change to option, then after clicking Run will show error for chart

### Expected results
'Bubble size' able to accept drop from 'Metric for color' with highlight and change to new drop name, then show Run button.

### Actual results
'Bubble size' able to accept drop from 'Metric for color ' without highlight and did not change to new drop name, but Run button show.

#### Screenshots

https://user-images.githubusercontent.com/81597121/127794284-dfe486d6-7017-40ce-9640-ecfeeeecf0ac.mov

#### How to reproduce the bug

1. Open bubble chart 'Location of current Developer'
2. Drag and Drop the 'Metric for color' option to 'Bubble size'
4.See error

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by kgabryje** [comment]
Fix: https://github.com/apache/superset/pull/16020
