### ISSUE TITLE
[d&d][Table]Unexpected error show when accept drop from 'Metric' in 'Percentage Metric'

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16009]
Unexpected error show when drop from 'Metric' in 'Percentage Metric'

### Expected results

No error show

### Actual results

Unexpected error show when drop from 'Metric' in 'Percentage Metric'

#### Screenshots
https://user-images.githubusercontent.com/81597121/127795512-1d5c1b6a-cfbf-47b4-ae22-5af20d339e21.mov

=

#### How to reproduce the bug

1. Open Table 'Breakdown of developer Type'
2. Drop COUNT(Developer_type) to Metrics from left column 
3. Drop COUNT(First time developer) to Percentage Metrics from left column 
4. Drop COUNT(Developer_type) from Metric to Percentage Metrics
5. see error

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
this is a feature request, not a bug. but we should have better indication for non-supported cross field

**Comment by mistercrunch** [comment]
Feels to me that `Unexpected errors` are bugs

**Comment by junlincc** [comment]
> Feels to me that `Unexpected errors` are bugs

For this stage, the expected behavior should be to highlight cross field dropping in Red. but we can certainly skip to make it support drop. @mistercrunch

**Comment by kgabryje** [comment]
@junlincc I bet that's the same problem as with dragging column from rows to columns control. Of course it's a bug, but I'm fairly sure that it used to work as expected

**Comment by jinghua-qa** [comment]
@junlincc I saw 'Filter' can accept drop from other fields, is this expected? should i field bugs for that?

**Comment by jinghua-qa** [comment]
Saw same issue in example chart 'Parallel Coordinates' chart, when drag and drop "Metrics' to "color metrics'

https://user-images.githubusercontent.com/81597121/127830289-8239f789-af0c-45dd-bb54-7c4134f2f395.mov

**Comment by kgabryje** [comment]
@jinghua-qa in general the issue occurs when we have 2 controls of the same type. The fix is in progress

**Comment by kgabryje** [comment]
> @junlincc I saw 'Filter' can accept drop from other fields, is this expected? should i field bugs for that?

Could you please show a recording/steps to reproduce? Filter works fine for me

**Comment by kgabryje** [comment]
Fix: https://github.com/apache/superset/pull/16020
