### ISSUE TITLE
[drag & drop][Calendar Heatmap]Example chart 'Calendar Heatmap' is not shown automatically with d&d on  

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16016]
Example chart 'Calendar Heatmap' is not shown automatically with d&d on , user need to click 'Run' to show the example chart. When d&d is off, this example chart show automatically after open in explore.

### Expected results

Example chart 'Calendar Heatmap' show in explore

### Actual results

Example chart 'Calendar Heatmap' did show in explore, user need to click 'Run' to show

#### Screenshots

https://user-images.githubusercontent.com/81597121/127823568-44d0af0c-0b2d-47d5-9f2d-288620c02ac6.mov

#### How to reproduce the bug

1. Go to chart list
2. Select example chart 'Calendar Heatmap' show in explore
3. See error

### Environment

(please complete the following information):

- superset version: `latest master`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by jinghua-qa** [comment]
Same issue found in example chart 'Arcs','Grid'

**Comment by suddjian** [comment]
I don't have this issue on a newly created chart, only on newly created example charts. Will continue investigating. We may want to lower the priority level here.
