### ISSUE TITLE
[cosmetic][TODO]Stack all checkboxes in control for all charts 

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16013]
In heatmap, information and instant effect icons too closed to the edge at DATA panel default size, instant effect icon completely cut at default size.
<img width="1788" alt="Screen Shot 2021-08-01 at 10 58 15 PM" src="https://user-images.githubusercontent.com/81597121/127811715-8f708112-f395-48c2-9a6a-8250101259b9.png">

**Comment by noobyogi0010** [comment]
Hi @jinghua-qa !
I would like to work upon this issue.
Thanks.

**Comment by geido** [comment]
Hello @noobyogi0010 that's great. I'd be happy to help you with that. Are you in the [Superset Slack ](https://join.slack.com/t/apache-superset/shared_invite/zt-uxbh5g36-AISUtHbzOXcu0BIj7kgUaw) already? We can chat over there. I go with the same username (geido). Thanks!

**Comment by rusackas** [comment]
I believe this is done for the most part... there may be a few lingering antiquities kicking around, but I think the issue, in spirit, has been addressed, and we should open up any lingering concerns as more specific issues to tackle..
