### ISSUE TITLE
[drag&drop][Dual line chart] not able to drag and drop to Right Axis Metric

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16018]
Not able to drag and drop to 'Right Axis Metric' in example Dual line chart 'Average and Sum trends' with D&D on, user is not able to add metric through the '+' logo, but able to select metric from 'add metric' field

### Expected results

Able do drag and drop column to 'Right Axis Metric' with D&D on

### Actual results

Not Able do drag and drop column to 'Right Axis Metric' with D&D on

#### Screenshots

https://user-images.githubusercontent.com/81597121/127825976-07cb9bb8-a75d-4139-b651-7d2b720e3271.mov

#### How to reproduce the bug
Precondition: Turn on D&D

1. Open example chart 'Average and Sum trends'
2. Go to 'Right Axis Metric' and try drag and drop
3. See error

### Environment

(please complete the following information):

- superset version: `latest master`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by kgabryje** [comment]
Fix https://github.com/apache-superset/superset-ui/pull/1259

**Comment by kgabryje** [comment]
Sorry @junlincc, the fix was ready before you added `will-not-fix` label. It was a really quick one though
