### ISSUE TITLE
[drag&drop] Removing filter option will open popover for the next 

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16019]
Removing filter option from top to bottom opened popover for the next,  removing options in other fields (for example Metrics, Group by) do not have this issue.

### Expected results

Removing filter option will not open popover for the next

### Actual results

Removing filter option opened popover for the next

#### Screenshots

https://user-images.githubusercontent.com/81597121/127835955-8473397f-6486-4303-9e0b-7a0f8fac758b.mov

#### How to reproduce the bug
Precondition: Enable Drag and drop
1. Drag and drop multiple selection in 'Filters'
2. remove options from top to bottom
3. See error

### Environment

(please complete the following information):

- superset version: `latest master`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@pkdotson please take on this one 🙏

**Comment by kgabryje** [comment]
https://github.com/apache/superset/pull/16024
