### ISSUE TITLE
[drag & drop][Tree chart] 'Metric' for Tree chart is not drag and droppable

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16021]
'Metric' for Tree chart is not drag and droppable when d&d enable.

### Expected results

Metrics for Tree chart is drag and droppable 

### Actual results

Metrics for Tree chart is not drag and droppable 

#### Screenshots

<img width="1791" alt="Screen Shot 2021-08-02 at 2 40 44 AM" src="https://user-images.githubusercontent.com/81597121/127840940-50e21496-7b16-4712-836d-cc55e6863c9a.png">

#### How to reproduce the bug

1. Select Tree chart in viz type
2. go to 'Metric'
3. See error

### Environment

(please complete the following information):

- superset version: `lastest master`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by kgabryje** [comment]
Fix: https://github.com/apache-superset/superset-ui/pull/1260
