### ISSUE TITLE
Update: Server side pagination is functional on 1.2 but requires the below feature flags set as `True`. Closing the issue due to it working. Although documentation for this would have been helpful.

### ISSUE THREAD

**Issue by RSanjeevi** [apache/superset#16028]
Update: Server side pagination is functional on 1.2 but requires the below feature flags set as `True`. Closing the issue due to it working. Although documentation for this would have been helpful.

https://github.com/apache/superset/blob/eb78f4332fd931b8f8990c9d177b990fa49f189c/superset/config.py#L368-L370

_Originally posted by @RossMoir in https://github.com/apache/superset/issues/15706#issuecomment-889901379_

supersets 1.2
It works with default charts. Not works when we create charts from the SQL lab

**Comment by Veonms** [comment]
It's the same issue as #14727. If you save the chart first, then you should be able to use server side pagination. We found this out after testing yesterday
