### ISSUE TITLE
SQL Lab commit connection even if no CTA query is made

### ISSUE THREAD

**Issue by jbouzekri** [apache/superset#16036]
SQL Lab query editor on run commit the connection even if all we do is a select on a database without CTA enabled. This is not really an issue with most database system however there are problems when using superset with Mongo BI connector which does not support transaction and I assume any other system which does not too.

### Expected results

The commit should only be done if a CTA query needs to be run

### Actual results

A commit is always done

### Environment

- superset docker image version: `1.2`
- mongo: `5.0`
- mongo bi connector: `2.14`

### Checklist

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

The commit is done here : https://github.com/apache/superset/blob/6d3e19d85715b3f93b6dbe154e40ed3eefde775f/superset/sql_lab.py#L501

I think that just replacing it like this would do the trick : 

```python
# Commit the connection so CTA queries will create the table.
if apply_ctas:
    conn.commit()
```

**Comment by rusackas** [comment]
This looks like it should have been closed by the linked PR, and has gone stale anyway.... holler if there's a need to keep this open!
