### ISSUE TITLE
[API Rest] Redirecting to /login when doing a POST to /api/v1/database/import/

### ISSUE THREAD

**Issue by MrAmonix** [apache/superset#16030]
Hello!

I tried to import a zip file of my databases (previously obtain using the /export route of the API) to my superset server but I keep getting redirected to /login (I tried something with csrf_token but I get the same redirection)

There is may be something I am missing.

### Expected results

I expect to be able to see my databases added to my superset server and receive a 200 OK response

### Actual results

I am getting a redirection to /login 

#### How to reproduce the bug

I am using this curl:

curl -H "Authorization: Bearer $token" -H 'accept: application/json' -H 'Content-Type: multipart/form-data' -F "formData=@databases.zip;type=multipart/form-data" -X POST http://localhost:8088/api/v1/database/import/

Note: token is an access_token generate by the route /security/login

- superset version: `1.3`
- python version: `3.7.9`
- node.js version: `14`
- any feature flags active: "ALERT_REPORTS": True, "VERSIONED_EXPORT": True

**Comment by oma-it** [comment]
Hi,
we are facing the same issue. 
any potential solution ?

**Comment by junlincc** [comment]
Hi! Thanks for reporting, can you help verify this is still an issue on master? if so, lmk with a screenshot or videos, we will look into it right away 🙏

**Comment by oma-it** [comment]
thanks @junlincc 
#token compute
[cs_superset@superset-vm ~]$ token=`curl -k -H "Content-Type: application/json" -d '{"password": "#masked#","provider": "db", "refresh": true, "username": "admin"}' -X POST http://localhost:8088/api/v1/security/login | jq -r .access_token`
#api call using the token to import superset_export.zip file
[cs_superset@superset-vm ~]$ curl -H "Authorization: Bearer $token" -H 'accept: application/json' -H 'Content-Type: multipart/form-data' -F "formData=@superset_export.zip;type=multipart/form-data" -X POST http://localhost:8088/api/v1/database/import/
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a href="/login/">/login/</a>.  If not click the link.[cs_superset@superset-vm ~]$

**Comment by MrAmonix** [comment]
thanks here is a screenshot of what I get, it is pretty similar to the above
![superset_import](https://user-images.githubusercontent.com/25547683/128197331-bd7e70d5-bab7-42a7-8d61-ba4688734259.png)

**Comment by janantos** [comment]
HI @junlincc , 
Any progress here? I am facing the same issue with current docker latests image while importing dataset, here is verbose curl output.

```> POST /api/v1/dataset/import/ HTTP/2
> Host: superset.janantos.com
> User-Agent: curl/7.64.1
> accept: application/json
> Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MjkyODY1NTUsIm5iZiI6MTYyOTI4NjU1NSwianRpIjoiMGZmODU0YzktY2QxMy00ZTljLTgwY2EtMGRmZTk0NjI1MDc5IiwiZXhwIjoxNjI5Mjg3NDU1LCJpZGVudGl0eSI6MywiZnJlc2giOnRydWUsInR5cGUiOiJhY2Nlc3MifQ.7OrFU8CjrV7BXvddLVCui0BCOCtybmuq7tExdW0pNbE
> Content-Length: 3506
> Content-Type: multipart/form-data; boundary=------------------------0fcee28eab4e279a
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
} [3506 bytes data]
* We are completely uploaded and fine
< HTTP/2 302 
< content-type: text/html; charset=utf-8
< date: Wed, 18 Aug 2021 11:35:55 GMT
< location: http://superset.janantos.com/login/
< server: gunicorn/20.0.4
< content-length: 221
< 
{ [221 bytes data]
100  3727  100   221  100  3506    863  13695 --:--:-- --:--:-- --:--:-- 14558
* Connection #0 to host superset.janantos.com left intact
* Closing connection 0
api_response: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"> <title>Redirecting...</title> <h1>Redirecting...</h1> <p>You should be redirected automatically to target URL: <a href="/login/">/login/</a>. If not click the link.
```

**Comment by youngsol** [comment]
@MrAmonix 
may be X-CSRFTOKEN?
```
csrf_token : GET /security/csrf_token
headers = {"Authorization": "Bearer Token", "X-CSRFToken": "cstf token"}
```

**Comment by MrAmonix** [comment]
Thanks for the response, 

I succeeded to get my csrf_token but I still have the redirection to /login even with the csrf_token in "X-CSRFToken" header

Here is the request I tried
![import_superset](https://user-images.githubusercontent.com/25547683/131340889-c95e1739-7b32-4caf-991e-eef7c3fd1c3f.png)

**Comment by janantos** [comment]
HI @junlincc, any idea what can be done, can you please point me to the fraction of code my engineer should investigate?

**Comment by pedrohdemedeiros** [comment]
Hi, all.

Any progress on this issue? I'm trying to overcome it rigth now =/

**Comment by long-tranvan** [comment]
Hi @pedrohdemedeiros
You can try this workaround (at least it works for me)
```sh
  export SUPERSET_BASE_URL=#your superset endpoint
  export URL_AUTH=$SUPERSET_BASE_URL"/api/v1/security/login"
  export URL_CSRF_TOKEN=$SUPERSET_BASE_URL"/api/v1/security/csrf_token/"
  export URL_DATASET_IMPORT=$SUPERSET_BASE_URL"/api/v1/dataset/import/"
  curl -H "Content-Type: application/json" -X POST --data "{\"username\":\"$SUPERSET_AD_USER\",\"password\":\"$SUPERSET_AD_PWD\",\"provider\":\"db\"}" $URL_AUTH >> auth_token.json
  export ACCESS_TOKEN=$(jq '.access_token' auth_token.json | sed 's/"//g')
  curl -c cookies.txt -H "Authorization: Bearer $ACCESS_TOKEN" -L $URL_CSRF_TOKEN >> csrf_token.json
  export CSRF_TOKEN=$(jq '.result' csrf_token.json | sed 's/"//g')
  value=$(cat cookies.txt) && found=${value##*session} && export COOKIE=$(echo $found | sed -e 's/\t//g')
 
 curl --location --max-redirs 5 \
       --request POST $URL_DATASET_IMPORT \
       --header "Cookie: session=$COOKIE" \
       --header "X-CSRFTOKEN: $CSRF_TOKEN" \
       --header "Authorization: Bearer $ACCESS_TOKEN" \
       --form 'overwrite="true"' \
       --form 'formData=@"artifact.zip"'
 # or
  curl -b cookies.txt --location --max-redirs 5 \
       --request POST $URL_DATASET_IMPORT \
       --header "X-CSRFTOKEN: $CSRF_TOKEN" \
       --header "Authorization: Bearer $ACCESS_TOKEN" \
       --form 'overwrite="true"' \
       --form 'formData=@"artifact.zip"'
```
After investigating, I think the root cause is that superset try to check valid token together cookie which has been provided while getting csrf token.

**Comment by rusackas** [comment]
@long-tranvan is correct, you need to provide an auth token and a CSRF token. If you're working on local testing, which seems to be the case, you can disable CSRF checking by setting `WTF_CSRF_ENABLED = False` in `config.py` but obviously you won't necessarily want to do that with production deployments. At this point, this seems to be more of a support/Q&A discussion than an actual bug/issue. I'm going to close this, but it can be continued on [Discussions](https://github.com/apache/superset/discussions) or [Slack](https://join.slack.com/t/apache-superset/shared_invite/zt-1jp6hjzrq-H0PlFtToyLWuPiJDuRWCNw).
