### ISSUE TITLE
Is there a way to merge 2 pie chart? (or use multiple datasets)

### ISSUE THREAD

**Issue by ghost** [apache/superset#16047]
Hi guys, very nice and excellent project!

In our project we decide to make your solution to build a dashboard app, and we faced with such issue

We need to build a Pie Chart using data from 2 separate databases (actually postgres and druid), and present this data in a single Pie chart.
Is there a way to use multiple datasets (from different databases) and multiple queries to build a single chart?
Or maybe we can somehow use the results of 2 different Pie Charts?
Or maybe your app provides some interface for customizing result of SQL query which will be used in order to build a chart?

Hope you can help us to decide what should we do, thanks!

**Comment by xupengrun** [comment]
We faced ths same issue,wo want to merge multiple datasets with data from two datasource to build single chart

**Comment by rusackas** [comment]
There's not really a way to do cross-database joins like this in Superset. This is where you'd want to get into the wide world of other tools that cater to ETL/pipelines/etc.
