### ISSUE TITLE
Failed taking a screenshot 'WebDriver' object has no attribute 'screenshot'

### ISSUE THREAD

**Issue by lozbrown** [apache/superset#16059]
I'm trying to set up alerts and reports but currently they fail and the execution log shows "Failed taking a screenshot 'WebDriver' object has no attribute 'screenshot'"

### Expected results

Expected Email report to be received by target user

### Actual results

Execution report states 
"Failed taking a screenshot 'WebDriver' object has no attribute 'screenshot'"

#### Screenshots

![image](https://user-images.githubusercontent.com/9961593/128187973-699ce22c-094d-4057-9284-556ec55a7b27.png)

#### How to reproduce the bug

1. Go to 'Settings > Alerts and reports'
2. Click on '+ sign in reports tab'
3. Configure a report for any chart to email 
4. check execution log

### Environment

(please complete the following information):

- superset version: 1.2.0
- python version: Python 3.7.10
- node.js version: N/A
- selenium version: 3.141.0
- any feature flags active:

```
[ec2-user@ip-10-166-211-136 logs]$ egrep "ALERT|SMTP" /usr/local/lib/python3.7/site-packages/superset/config.py | grep -v \#
    "ALERT_REPORTS": True,
    "ALERTS_ATTACH_REPORTS": True,
SMTP_HOST = "<REDACTED>"
SMTP_STARTTLS = True
SMTP_SSL = False
SMTP_USER = "<REDACTED>"
SMTP_PORT = 587
SMTP_MAIL_FROM = "<REDACTED>"
ENABLE_ALERTS = False
ALERT_REPORTS_CRON_WINDOW_SIZE = 59
ALERT_REPORTS_WORKING_TIME_OUT_KILL = True
ALERT_REPORTS_WORKING_TIME_OUT_LAG = 10
ALERT_REPORTS_WORKING_SOFT_TIME_OUT_LAG = 1
ALERT_REPORTS_NOTIFICATION_DRY_RUN = False


 chromedriver --version
ChromeDriver 85.0.4183.87 (cd6713ebf92fa1cacc0f1a598df280093af0c5d7-refs/branch-heads/4183@{#1689})

/usr/bin/google-chrome-stable --version
Google Chrome 85.0.4183.121

**Comment by mustafacse** [comment]
I am also facing the issue with this feature but its slightly different, on the dashboard email schedule. I keep getting below error in celery task and utilmately it timed out.

[2021-08-09 15:28:40,721: DEBUG/ForkPoolWorker-7] POST http://127.0.0.1:57379/session/283e5b685c73b8fbb40f4515cdbac0bf/element {"using": "css selector", "value": ".grid-container"}
[2021-08-09 15:28:40,729: DEBUG/ForkPoolWorker-7] http://127.0.0.1:57379 "POST /session/283e5b685c73b8fbb40f4515cdbac0bf/element HTTP/1.1" 404 838
[2021-08-09 15:28:40,730: DEBUG/ForkPoolWorker-7] Finished Request

It could be chrome driver version support with Selenium, I am using 3.141.0 version and chrome version Google Chrome 92.0.4515.131

@lozbrown - can you tell me how can I install 85 version that you have installed.??

I am using below script to install chrome.
sudo unzip chromedriver_linux64.zip
sudo mv chromedriver /usr/bin/chromedriver
sudo curl https://intoli.com/install-google-chrome.sh | bash
sudo mv /usr/bin/google-chrome-stable /usr/bin/google-chrome

# run chromium driver and chrome browser
screen -S chromeDriver -d -m chromedriver
screen -S chrome -d -m google-chrome

**Comment by mustafacse** [comment]
In the config file its mentioned - 
# chrome:
#   Requires: headless chrome
#   Limitations: unable to generate screenshots of elements

Does it mean we cant use chrome for reporting and firefox is the only option?

**Comment by mustafacse** [comment]
There is comment here which mentions its buggy at certain version. https://github.com/apache/superset/blob/master/superset/tasks/schedules.py#L271

Could you guys suggest what is the recommended versions of Selenium and Firefox, Geckodriver to make it work

**Comment by lozbrown** [comment]
I tried this with firefox and gecko driver and got similar issues eg
"Report Schedule execution failed when generating a screenshot."

If anyone can comment here on the combination of browser / driver /selenium they have had this working with that would be great

**Comment by aaronfeng** [comment]
I upgraded from 1.1.0 to 1.2.0.  Pretty sure 1.1.0 this feature was working but I'm getting the same error as above now.

**Comment by rusackas** [comment]
Closing due to the updates. Thanks @sfirke !
