### ISSUE TITLE
[cosmetic] NULL value should display prettier on Pie and Funnel chart

### ISSUE THREAD

**Issue by rosemarie-chiu** [apache/superset#16057]
## Screenshot
![CleanShot 2021-08-04 at 00 22 33](https://user-images.githubusercontent.com/52086618/128146452-1d147ee3-21ce-49c3-83fe-0e6f4131c119.png)

## Description
I think instead of `<NULL>` should try to display null value like how tree map and gauge chart `null`

**Comment by junlincc** [comment]
if i remember correctly, sql lab is using `NULL`? Just need to make sure it's consistent across the board.
