### ISSUE TITLE
Example datasets created with incorrect schema

### ISSUE THREAD

**Issue by betodealmeida** [apache/superset#16051]
When running `load-examples`, the example datasets defined in `superset/examples/configs/` are loaded without a schema.

### Expected results

Datasets should have the correct schema.

### Actual results

Datasets end without a schema, even if one is being used.

#### Screenshots

N/A

#### How to reproduce the bug

1. Run `superset load-examples`
2. Check the schema of all datasets, the ones loaded from configs have it set to null.

### Environment

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

N/A

**Comment by rusackas** [comment]
@betodealmeida do you know if this issue still exists, or if it was resolved by https://github.com/apache/superset/pull/16041 ?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
