### ISSUE TITLE
[Explore][Safari] Scroll bar is gone when open explore in Safari

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16072]
Scroll bar is gone when open explore in Safari

### Expected results

User can scroll up and down in data panel

### Actual results

User can not scroll up and down in data panel when open in Safari

#### Screenshots

https://user-images.githubusercontent.com/81597121/128250323-7e4f10c1-0431-4a84-8736-ff046011efa7.mov

#### How to reproduce the bug

1. Open superset in Safari
2. go to explore
3. try scroll up and down

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
also cosmetic issues on the scroll bars .vertical scroll is not needed 

https://user-images.githubusercontent.com/67837651/128252691-fbdc40ed-6651-4259-910b-4112f65d71a0.mov
