### ISSUE TITLE
[x-filtering]Time-series line x-filtering not working when rich tooltip is turned off

### ISSUE THREAD

**Issue by junlincc** [apache/superset#16070]
Step, smoothline, both dont work when richtooltip is off. 

https://user-images.githubusercontent.com/67837651/128245122-a6592d98-e508-41bb-a4af-21bdb56da918.mov

**Comment by stephenLYZ** [comment]
In fact, ECharts' line chart does not support click event without richtooltip (so it can not emit x-filtering), which is a limitation of ECharts itself. One hack way is to set a 0 size of marker, and it has a lower priority than marker control.

**Comment by villebro** [comment]
This is now fixed on master
