### ISSUE TITLE
[drag&drop]categorical bar unexpected error when series and breakdown are the same 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#16071]
Categorical Bar gets an unexpected error when Series and Breakdowns are the same

Expected behavior : If user drop a same column that's placed in SERIES already into BREAKDOWNS, the drop zone should be highlighted in RED -meaning does not accept value input, throwing an unexpected error is not that helpful. 
Since we still have awhile to get to generic x-axis in bar, let's fix this. :) 🙏

https://user-images.githubusercontent.com/67837651/128246220-8b5a2561-0af0-45cb-86a0-030997925f22.mov

**Comment by kgabryje** [comment]
That's strange, I'm getting a nice, comprehensive error 
![image](https://user-images.githubusercontent.com/15073128/128357731-104f6e60-83d1-4c65-a41b-aad82dbe2c25.png)

**Comment by kgabryje** [comment]
https://github.com/apache-superset/superset-ui/pull/1276 - fix for the issue
