### ISSUE TITLE
Date default to 1970-01-01 in case of null values

### ISSUE THREAD

**Issue by renjithpaul27** [apache/superset#16087]
It looks like supeset defaults null valued date/timestamp values to 1970-01-01 instead of null values in table charts.

### Expected results

Expected to see null or NA for null valued date,datetime,timestamp values.

### Actual results

It defaults to 1970-01-01 for null valued rows.

#### How to reproduce the bug

Use a mysql backend and create a table with some valid/null values for a date field. Derive it as a table chart in superset.

**Comment by junlincc** [comment]
Thanks for filing the issue, could you use the bug report template? additional information is needed before troubleshooting. @renjithpaul27

**Comment by hieulw** [comment]
I face the same problem when all my expected null date values is somehow converted to `1970-01-01 00:00:00` in datasource, while difference type like `TEXT`, `VARCHAR` is keep `N/A`
![image](https://user-images.githubusercontent.com/13571960/130379430-b61b55b1-3ac4-46ba-be5f-1cdf5742923e.png)

**Comment by ValentinC-BR** [comment]
The same goes for me, all my NULL values in DATE fields are replaced by 1970-01-01 00:00:00 ...

**Environment**
superset version: 1.3.0
python version: 3.7.9
node.js version: doesn't apply, I run on Kubernetes, using gunicorn as server
source : Athena

**Comment by henry145145** [comment]
I ran into this issue also in version 1.3.0

the re-format for value null to value 1970-01-01 is happening in @superset-ui/plugin-chart-table:

https://github.com/apache-superset/superset-ui/blob/881e25c7ee72f9b4f28db7e76ee977b9a5e8f2e5/plugins/plugin-chart-table/src/transformProps.ts#L53-L78

and the formatters are from '@superset-ui/core', and it looks like the formatters are using d3 format.

My workaround is clone/fork the table chart plugin and name it table_v2 and modify the code above so it won't format anything if the value is null. Then, use it as a custom plugin (put it under `visualization` directory).

**Comment by ChunshengZhao** [comment]
Also in version 1.4.2, DB is MSSQL.

**Comment by vpicavet** [comment]
I can reproduce on Superset 1.4.1 and PostgreSQL.

**Comment by Stefan-Blandin** [comment]
Can reproduce as well. My coworkers have a solution to use the "Expression" parameter in the table's .yaml file to reformat it as a string, but that removes the ability to filter it properly.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for a year and a half, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.

**Comment by vpicavet** [comment]
As of 2.1 problem seems gone anyway.
