### ISSUE TITLE
[cross-filtering] emitting timestamp filter break the dashboard

### ISSUE THREAD

**Issue by rosemarie-chiu** [apache/superset#16080]
Clicking on timestamp on table chart to emit filter break the dashboard

### Expected results
Should be able to filter by that timestamp i clicked on

### Actual results
Dashboard error

#### Screenshots

https://user-images.githubusercontent.com/52086618/128303039-30890b2a-843e-4acc-8dfe-3239f0ca4f7a.mp4

### Environment
cross-filtering flag, native filter flag, UX_BETA flag, d&d flag on

**Comment by villebro** [comment]
This has been fixed by https://github.com/apache-superset/superset-ui/pull/1281, closing
