### ISSUE TITLE
OAuth Sign In UX is confusing

### ISSUE THREAD

**Issue by NikolaiGulatz** [apache/superset#16082]
## Screenshot

<img width="593" alt="Bildschirmfoto 2021-08-05 um 08 58 19" src="https://user-images.githubusercontent.com/11081876/128305825-d2def689-37e6-4223-a6d9-0e1f45083eb3.png">

<img width="591" alt="Bildschirmfoto 2021-08-05 um 09 00 40" src="https://user-images.githubusercontent.com/11081876/128306037-fa6fa88c-638c-4e10-8537-547fbb8f66d8.png">

## Description

The OAuth Sign In UX is confusing:

1. It is not clear to me that I have to click on one of the providers in order to continue
2. When I click on "REGISTER" or "SIGN IN" without clicking on a provider first, I don't get any visual feedback
3. The visual selected state of the provider icon is not recognizable as selected, especially if there is only one provider

**Comment by junlincc** [comment]
@NikolaiGulatz thanks for suggesting! this is actually the first time i see this modal. We are currently short in Design support. If you have a mockup ready to start, can you share?

**Comment by stevetracvc** [comment]
We only use one provider, so we completely bypass that page. It's actually a flask thing, not superset. This is the location in the (old, maybe v0.37) docker container.

# /usr/local/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/general/security/login_oauth.html
```

!-- extend base layout -->
{% extends "appbuilder/base.html" %}

{% block content %}

<script type="text/javascript">

    var baseLoginUrl = "{{appbuilder.get_url_for_login}}";
    var baseRegisterUrl = "{{appbuilder.get_url_for_login}}";
    var next = "?next={{request.args.get('next', '')}}"

    var currentSelection = "";

    function set_openid(pr) {
        $('.provider-select').removeClass('fa-black');
        $('#' + pr).addClass('fa-black');
        currentSelection = pr;
    }


    function signin() {
        if (currentSelection != "") {
            window.location.href = baseLoginUrl + currentSelection + next;
        }
    }

    function register() {
        if (currentSelection != "") {
            window.location.href = baseRegisterUrl + currentSelection + '/register' + next;
        }
    }

    set_openid("{{ providers[0].name }}");
    signin();

</script>

{% endblock %}
```

Our edits are just the last two lines of JS:

```
    set_openid("{{ providers[0].name }}");
    signin();
```
which automatically selects the first provider and runs the signin function. If you don't want to auto sign in, just use the set_openid line.

**Comment by rusackas** [comment]
It sure looks like this was resolved by the linked PR. Closing.
