### ISSUE TITLE
Connection Oracle DB

### ISSUE THREAD

**Issue by leire23** [apache/superset#16084]
Hi, 

I set an oracle connection as your instructions at `https://superset.apache.org/docs/databases/oracle`, but it fails, I must to use cx_oracle connection as `https://docs.sqlalchemy.org/en/12/core/engines.html#oracle` (the second option) because sqlalchemy gets error with listener if you use SIDNAME. 

Best regards!

**Comment by junlincc** [comment]
Thanks for reporting! My understanding is our docs needs to be updated. do you @leire23 mind opening a PR for the update? 🙏

@srinify
