### ISSUE TITLE
[pivot table] conditional formatting: color value

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#16099]
Thank you @villebro implements pivot_table_v2 chart, help our users migrate from old params to the new params and UI controls.

But there is a little difference between the old and new charts:

Before:
![pivot_heatmat_before-2](https://user-images.githubusercontent.com/27990562/128437926-b8a59932-24ee-43de-8c87-feaafd5b9aa9.jpg)

After:
![pivot_heatmap_after](https://user-images.githubusercontent.com/27990562/128437998-71bcc875-a62f-4d55-931a-911dc999b474.jpg)

You will see that in the old chart, color's value seems ranges from min value to max value. So that cell with min value is white, cell with max value is the darkest.
But in the new chart, red color seems range from 0? this cause not much visual difference between min cell and max cell.

Feature improvement request:
Could we use range color from min value? cc @villebro

**Comment by villebro** [comment]
Good point @graceguo-supercat - I agree we should increase the contrast to make it more in line with the previous behavior. Will follow-up with a PR shortly.

Ping @kgabryje

**Comment by kgabryje** [comment]
@graceguo-supercat Done in https://github.com/apache-superset/superset-ui/pull/1284. Would you like to test it?
