### ISSUE TITLE
[metric]Rename column name with non-english string

### ISSUE THREAD

**Issue by heartcored98** [apache/superset#16108]
**Is your feature request related to a problem? Please describe.**

Hi, I am really enjoying superset, but I am frustrated when I have to rename column with non-english string. 
Because if I try to change the column name in Korean (for example metrics column),  then generated sql query contains Korean with `AS` statement. Therefore, BigQuery engine is broken. 

**Describe the solution you'd like**
I would like to manually assign column names of group by and metrics with any-language string, through the chart explore ui. 

Since [bigquery column name rule](https://cloud.google.com/bigquery/docs/schemas#column_names) does not allows non-english character, I think a field name variable should be prepared separately from the column name in SQL query.

**Describe alternatives you've considered**

**Additional context**

Following images is error message when I assign '날짜' string to one of the metrics column.

![image](https://user-images.githubusercontent.com/33013451/128461280-71edde5a-3e81-441a-9d70-51e47963c6c7.png)

![image](https://user-images.githubusercontent.com/33013451/128461991-28c23603-f443-4a56-bccc-77d5684e6824.png)

**Comment by zhaoyongjie** [comment]
we will consider this issue in metric refactor project. cc: @junlincc

**Comment by junlincc** [comment]
@heartcored98 we will start the metrics redesign/refactoring in later Q3 to include more column customization.

**Comment by zertyuiop** [comment]
Are there any updates on the issue? This issue is very annoying when using Superset with BigQuery.

**Comment by zertyuiop** [comment]
Same issue: https://github.com/apache/superset/issues/3136

**Comment by rusackas** [comment]
Closing in favor of https://github.com/apache/superset/issues/21658 - please take the discussion there.
