### ISSUE TITLE
[filter] Time Grain dropdown in filter layout in Dashboard

### ISSUE THREAD

**Issue by kamalkeshavani-aiinside** [apache/superset#16109]
## Screenshot

![filter](https://user-images.githubusercontent.com/74634977/128464920-d91e5edb-0ada-42c7-8e9b-06f985feda15.gif)

## Description

Usually all filter dropdown have layout above the filter chart in dashboard, making them easy to use and scroll. But In case of Time Grain dropdown, it opens inside the Filter chart box of the dashboard, making it hard to use and scroll.

## Design input
I would suggest to keep behavior of Time Grain dropdown same as others.

**Comment by junlincc** [comment]
Hi @kamalkeshavani-aiinside , we have moved on from the FilterBox to Dashboard filter and are only making improvement on Dashboard native filter. Please try 1.3 or latest master with feature flag  "DASHBOARD_NATIVE_FILTERS_SET": True. let us know what you think. thanks!

**Comment by kamalkeshavani-aiinside** [comment]
@junlincc, Thanks for the update. I was not aware of this decision of moving from FilterBox to Native Filters.

Is there any way I can propose to continue with both options? A lot of our dashboards have filters with limited scope, although I understand that scoping is possible in Native Filters as well, but it makes using filters very difficult for end users.

Consider a case where I have 8 tabs in dashboard, each with its own filter for whole tab and some extra filters for only limited charts in tab. By placement of filterbox, it is very easy for end users to understand the scope of the filter, but it may get complicated with native filters. Our users will be confused looking at so many filters in native filter pane, trying to understand which filter works for which tab and chart!!

**Comment by villebro** [comment]
> Consider a case where I have 8 tabs in dashboard, each with its own filter for whole tab and some extra filters for only limited charts in tab. By placement of filterbox, it is very easy for end users to understand the scope of the filter, but it may get complicated with native filters. Our users will be confused looking at so many filters in native filter pane, trying to understand which filter works for which tab and chart!!

@kamalkeshavani-aiinside native filters actually moves filters that don't apply to the currently active tab into a "Filters out of scope" collapsible panel (collapsed by default). See the attached video:

https://user-images.githubusercontent.com/33317356/128840236-0e46d5ac-4ee4-4c13-ba62-b35e09d58206.mp4

There is a feature flag `DASHBOARD_FILTERS_EXPERIMENTAL` which makes it possible to place native filters on the dashboard much like the filter box, but as of right now it's not clear in what form this feature will be supported going forward. So keep in mind that there may be breaking changes related to that feature if you consider using it in production.
