### ISSUE TITLE
Databricks sql analytics broken with pyodbc

### ISSUE THREAD

**Issue by saurabnigam** [apache/superset#16112]
in tag 1.0.0 databricks with pyodbc worked very well

But after this code its stopped working

https://github.com/apache/superset/blob/423ff50768cd1d70fc63a29ac3312916d4aaf65e/superset/db_engine_specs/databricks.py#L21

Solution add support for pyodbc as well not only hive as SQL analytics relies on that

**Comment by junlincc** [comment]
@saurabnigam feel free to open a PR for the regression, we will review your code.

**Comment by rusackas** [comment]
Closing as stale, but happy to re-open or review a  PR if there's a need.
