### ISSUE TITLE
Loadin superset in iframe different domain

### ISSUE THREAD

**Issue by ajknol** [apache/superset#16114]
### Expected results

Superset dashboard to load in iframe on website different domain

### Actual results

Unexpected error message 'Unexpected token < in JSON at position 0' shown on charts

![screen](https://user-images.githubusercontent.com/9432283/128508577-b60c751f-fe28-4dce-8c7d-46164ec96110.png)

#### How to reproduce the bug

<!DOCTYPE html>
<html>
  <head>
    <title>title</title>

  </head>
  <body>
	<iframe src="https://superset-dashboard-url" height="900" width="1900" title="Iframe Example"></iframe>
  </body>
</html>

### Environment

- superset version: `0.0.0dev`
- python version: `python 3.8.10`

**Comment by cdmikechen** [comment]
maybe try to use firefox or Chrome under 80?
