### ISSUE TITLE
[table editor] Change virtual dataset won't work

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#16124]
#### How to reproduce the bug

1. Go to a chart using virtual dataset, which has sql query
2. Click on Edit dataset
3. change sql: (in my case, change `> '2021-07-01'` to `= '2021-07-01'` )
<img width="874" alt="Screen Shot 2021-08-06 at 12 06 53 PM" src="https://user-images.githubusercontent.com/27990562/128560368-0c7cd64b-5710-4ad0-bb5c-a3bd578524c1.png">

4. save it
5. It looks dataset is updated with success message
6. But if you open Edit dataset modal, yo will see old sql
7. in the API, you can see the old sql is sent out in the update API:
<img width="1203" alt="Screen Shot 2021-08-06 at 12 07 26 PM" src="https://user-images.githubusercontent.com/27990562/128560302-e5dfe5eb-5a75-44f0-9a8f-87e4a54e249c.png">

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

cc @junlincc

**Comment by junlincc** [comment]
thanks for filing, we also noticed it. moved it to p0
this is pretty sever so we are picking it up from you guys.  @eschutho

**Comment by graceguo-supercat** [comment]
@junlincc thanks for prioritizing this!!

**Comment by yousoph** [comment]
Dataset settings also aren't getting saved

**Comment by graceguo-supercat** [comment]
I think the root cause is from [this PR](15887)

**Comment by zhaoyongjie** [comment]
@graceguo-supercat I am on it.
