### ISSUE TITLE
[dashboard list] Loading indicator won't disappear after exporting a Dashboard from the list

### ISSUE THREAD

**Issue by geido** [apache/superset#16143]
## Screenshot

https://user-images.githubusercontent.com/60598000/128696248-4ac191b6-e6b1-4422-a0b1-290a51131121.mp4

## Steps to reproduce

1. Go to Dashboards
2. Hover a Dashboard and click on the "export" icon
3. Wait for the Dashboard to be downloaded
4. Observe that the loading icon in the middle of the screen does not disappear

## Expected behavior

Once a Dashabord has been downloaded successfully the loading indicator should disappear

**Comment by geido** [comment]
@junlincc @rosemarie-chiu @jinghua-qa

**Comment by jinghua-qa** [comment]
testenv is not up

**Comment by junlincc** [comment]
> /testenv up Feature_VERSIONED_EXPORT=true

LOL

**Comment by rusackas** [comment]
Working fine now-a-days!
