### ISSUE TITLE
Some countries maps do not render correctly on country_map visualization 

### ISSUE THREAD

**Issue by mohamedmossadaeye** [apache/superset#16142]
trying to plot some aggregations on egypt map for some governorates
here is the data :
![dataset](https://user-images.githubusercontent.com/80886596/128688786-b3b5c57e-340e-4f57-9390-9bbde795ed6c.png)

### Expected results

i was expecting to get something like i got when plotting on usa map 
![usa](https://user-images.githubusercontent.com/80886596/128689030-d4c2afee-697f-4795-9c94-cbc459ce79a3.png)

### Actual results

what actually happens.

![egy](https://user-images.githubusercontent.com/80886596/128689310-4e765197-1a8d-4fd9-b14d-0808e7ffe28a.png)

#### How to reproduce the bug

1. use this data 
[egy-states.csv](https://github.com/apache/superset/files/6953509/egy-states.csv)
[us-states.csv](https://github.com/apache/superset/files/6953514/us-states.csv)

2. add them by upload csv
3. plot country map with any aggregation you want

### Environment

(please complete the following information):

- superset version: `latest`
- python version: `Python 3.7.11`
- node.js version: `unknown for me , i use superset as pip package with latest superset version`
- any feature flags active: alerts and reports
- note that i am using superset inside python virtualenv and installed superset as pip package 

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ok ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ok] I have reproduced the issue with at least the latest released version of superset.
- [ ok] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
The example dataset you've provide is working just fine in Superset 2.0, I'm happy to report!

<img width="577" alt="image" src="https://user-images.githubusercontent.com/812905/212457750-dde61007-3ad9-4d8d-a0e0-674558f8f054.png">

**Comment by graffio-m** [comment]
Same problem for me.
Trying to plot the country map of Italy regions with this csv file imported in a corrected way in Superset, the map show only one region colored.

![immagine](https://github.com/apache/superset/assets/3777519/fae70a4c-b0f9-4785-aeeb-08e865e36d26)

Thanks in advance

**Comment by rusackas** [comment]
@graffio-m it might be worth filing a new issue, with some sanitized data provided so we can reproduce your issue using that de-sensitized data file to test.
