### ISSUE TITLE
API: Export: Exporting 2 physical datasets with the same table name but different schema returns only 1 dataset

### ISSUE THREAD

**Issue by sann05** [apache/superset#16141]
If you try to export with API 2 datasets with the same database, the same table name but different schemas, it returns you only 1 dataset

### Expected results

Exporting of 2 datasets should give you 2 datasets (files)

### Actual results

As the export feature uses table name as the file name for export it returns only 1 file for 2 datasets

#### Screenshots
![Created datasets](https://i.ibb.co/tzVG2bf/2021-08-09-11-41-18.png)

![Exported datasets](https://i.ibb.co/BB539XN/exported-datasets.png)

#### How to reproduce the bug

1. Go to SuperSet web
2. Create a database (I used Vertica)
3. Create 2 tables with the same name but with the different schema in the DB
4. Create 2 SuperSet datasets for the tables from step the previous step.
5. Create 2 simple table charts for the 1 for each dataset from the previous step. (This step needs to be done as the export dataset endpoint doesn't work as expected, so I'm using chart export endpoint)
6. Send GET request to `https://{superset_host}:{port}/api/v1/chart/export/` and save archive in the response
7. Unzip the archive and check the amount of files for datasets in `{extracted_archive}/dataset/{database_name}/`

### Environment

(please complete the following information):

- superset version: `Superset 1.1.0`
- python version: `Python 3.7.9`
- node.js version: `not found`

**Comment by sann05** [comment]
It seems like there is no reason to export charts. Everything that you need to export/import dashboard in the exported json from dashboard endpoint

**Comment by jhua8970** [comment]
This is still an issue if users need to use the YAML exports to manage assets in Superset. The same issue exists for dashboard export in YAML format, since the exported files are named using dashboard titles/names.

**Comment by iamed2** [comment]
Dashboards and charts use IDs to disambiguate between same-named entities, but datasets do not; this issue is still present on 4.0.1. 

Unfortunately the original reporter closed the issue. Can maintainers please reopen it?

**Comment by sann05** [comment]
> Dashboards and charts use IDs to disambiguate between same-named entities, but datasets do not; this issue is still present on 4.0.1 with YAML dataset exports.
> 
> Unfortunately the original reporter closed the issue. Can maintainers please reopen it?
I can reopen that

**Comment by lxrvan** [comment]
> Dashboards and charts use IDs to disambiguate between same-named entities, but datasets do not; this issue is still present on 4.0.1 with YAML dataset exports.
> 
> Unfortunately the original reporter closed the issue. Can maintainers please reopen it?

Hi! please tell me if there is any news on solving this problem in v4.0.1/4.0.2?

**Comment by rusackas** [comment]
No news that I'm aware of, but I'll ping @betodealmeida and @eschutho since they were looking at what to include (or not) with imports/exports in the not-so-distant past. 

Obviously we're open to a PR if anyone needs to dig into this more urgently.

**Comment by eschutho** [comment]
@geido can we put a bug bounty on this?

**Comment by Arunodoy18** [comment]
I’m interested in working on this.

From reading the thread, it seems the core issue is that dataset YAML exports rely on dataset names for file identity, which can lead to collisions or ambiguity during import workflows, especially in asset-management or CI/CD use cases.

Instead of changing dataset identity behavior globally, I’m considering exploring improvements limited to export/import handling, such as:

• Including UUID-based disambiguation in exported dataset filenames
• Ensuring dataset UUID is consistently preserved and prioritized during import resolution
• Maintaining backward compatibility with existing exports

Would that direction align with current maintainers’ expectations for this issue?
