### ISSUE TITLE
[feat]Develop a feature to export/import Row Level Security filters from one instance to another

### ISSUE THREAD

**Issue by lulugll** [apache/superset#16157]
Problem: We don’t want to manually create Row Level Security filters in each instance. 

We are using `flask fab export-roles` and `flask fab import-roles` to export/import Roles with permissions. However, we are still facing the problem of exporting/importing Row Level Security filters from one instance to another in Superset.

**Comment by rusackas** [comment]
Closing this as inactive, and because it's not a bug but a feature request. I'd recommend opening an Ideas thread in Discussions if you still want this, and we can ping a few people there to get the discussion rolling.
