### ISSUE TITLE
[dashboard cache] Reset all caches when Force Refresh Dashboard

### ISSUE THREAD

**Issue by kamalkeshavani-aiinside** [apache/superset#16159]
**Is your feature request related to a problem? Please describe.**
Current behavior of Dashboard cache:
- User loads a dashboard, which generates cache for all the charts.
- User changes a filter to value X, which generates cache for all charts with changed filter value.
- User returns to dashboard later, and clicks on 'Refresh Dashboard', which generates new cache for all the charts.
- User again changes the filter to value X, which loads the cached charts with changed filter value.

So the user assumes that clicking on 'Refresh Dashboard' will load new data in dashboard, but actually user has to click 'Refresh Dashboard' with every new filter value change.

**Describe the solution you'd like**
When a user clicks 'Refresh Dashboard', all the cache for that particular dashboard should be removed.

**Describe alternatives you've considered**

**Additional context**
I tried and confirmed this behavior in 1.2, not sure about in master.

**Comment by kamalkeshavani-aiinside** [comment]
Also forgot to mention that, same happens in dashboard tabs as well. User need to refresh the dashboard in each tab, but ideally only one click on 'Refresh Dashboard' should do the job.

**Comment by kamalkeshavani-aiinside** [comment]
@junlincc Please add the necessary labels.

**Comment by villebro** [comment]
@michael-s-molina let's consider if this is something we could solve with the new key-value store (an extension of the "invalidate all cached chart data for dataset x").

**Comment by kamalkeshavani-aiinside** [comment]
@villebro Can you pin this issue, if you are still working on it?

**Comment by kamalkeshavani-aiinside** [comment]
@villebro Understood. If you have some time, can you share some details on how the cache and cache reset works currently? Where in the code should I look?
Also, let me know if I should create a SIP for this. Maybe we can make [cache warm up](https://github.com/apache/superset/pull/17895) work again.
