### ISSUE TITLE
[cell formatting]False warning of Conditional Formatting validation in Table & Pivot Table V 2

### ISSUE THREAD

**Issue by vnnw** [apache/superset#16169]
False warning in Conditional Formatting validation in Table & Pivot Table V 2.
It seems that the current compare logic is string based instead of real number based.

#### Screenshots

![image](https://user-images.githubusercontent.com/4979571/128890722-7429922a-c871-4c66-85ae-8bcd594a96f1.png)

![image](https://user-images.githubusercontent.com/4979571/128891119-2c52f3b1-1309-4956-a530-169151569006.png)

### Environment

- superset version: Git master

**Comment by junlincc** [comment]
got it! thanks for reporting and trouble shooting!! we will get to it ASAP
