### ISSUE TITLE
[chart viz][time series bar chart] Rich tooltip is not highlighted when hover on series and not able to scroll 

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16177]
In time series bart chart, Rich tooltip is not highlighted when hover on series and not able to scroll when there is long series.

### Expected results

Rich tooltip can show highlight when hover on series, and able to scroll with long series

### Actual results

Rich tooltip not able to show highlight when hover on series, and able to scroll with long series.

#### Screenshots

https://user-images.githubusercontent.com/81597121/128940880-b3194124-fccc-4127-9b1e-e0dc933d490b.mov

#### How to reproduce the bug

1. Go to time series bar chart 
2. add multiple metrics (5-10)
3. hover over on each series and observe tooltip

### Environment

(please complete the following information):

- superset version: latest master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by jinghua-qa** [comment]
@junlincc

**Comment by junlincc** [comment]
https://user-images.githubusercontent.com/67837651/129129492-9a6f513e-732f-4f16-a84d-378f07f5b8dd.mov

**Comment by stephenLYZ** [comment]
working on it
