### ISSUE TITLE
"Sync columns from source" broken for complex datasource names

### ISSUE THREAD

**Issue by michellethomas** [apache/superset#16172]
Our virtual datasources get automatically created with complex names like `Untitled Query 2 08/10/2021 0...` to make them unique. The "Sync columns from source" feature seems to be broken because that name gets split up in the url `datasource/external_metadata_by_name/table/Presto/null/Untitled%20Query%202%2008/10/2021%2009:15:26/`. 

It looks like maybe this happened when changing datasource metadata updating to pull using the name instead of the id ([here](https://github.com/apache/superset/pull/15887/files#diff-a17a45fe0d0a8a3079cfe67ede4def65af02cef20ba94e9ee827b62edf51df23R491)). CC: @zhaoyongjie 

### Expected results

Datasource should update

### Actual results

Error

#### How to reproduce the bug

1. Create a virtual datasource with `/` in the name
2. Try to update the datasource and "sync columns from source"

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@jinghua-qa let's update our test case with `/` in virtual dataset name for the Sync columns from source(?) thanks! 
@zhaoyongjie let's get it fixed asap as it's a regression.

**Comment by zhaoyongjie** [comment]
> Our virtual datasources get automatically created with complex names like `Untitled Query 2 08/10/2021 0...` to make them unique. The "Sync columns from source" feature seems to be broken because that name gets split up in the url `datasource/external_metadata_by_name/table/Presto/null/Untitled%20Query%202%2008/10/2021%2009:15:26/`.
> 
> It looks like maybe this happened when changing datasource metadata updating to pull using the name instead of the id ([here](https://github.com/apache/superset/pull/15887/files#diff-a17a45fe0d0a8a3079cfe67ede4def65af02cef20ba94e9ee827b62edf51df23R491)). CC: @zhaoyongjie
> ### Expected results
> 
> Datasource should update
> ### Actual results
> 
> Error
> #### How to reproduce the bug
> 
>     1. Create a virtual datasource with `/` in the name
> 
>     2. Try to update the datasource and "sync columns from source"
> 
> 
> ### Environment
> 
> (please complete the following information):
> 
>     * superset version: `master`
> 
>     * python version: `python --version`
> 
>     * node.js version: `node -v`
> 
>     * any feature flags active:
> 
> 
> ### Checklist
> 
> Make sure to follow these steps before submitting your issue - thank you!
> 
>     * [x]  I have checked the superset logs for python stacktraces and included it here as text if there are any.
> 
>     * [ ]  I have reproduced the issue with at least the latest released version of superset.
> 
>     * [x]  I have checked the issue tracker for the same issue and I haven't found one similar.

Thanks for fille this issue. On it.

**Comment by jinghua-qa** [comment]
Verified fixed in 2021.34 and added test cases.
