### ISSUE TITLE
adjust space between charts.

### ISSUE THREAD

**Issue by Narendra678** [apache/superset#16187]
## Screenshot 
![Space charts](https://user-images.githubusercontent.com/88739186/128984543-fdc031c4-f16c-46ec-b73e-d812920cbf0c.PNG)
![Space charts](https://user-images.githubusercontent.com/88739186/128984684-21ee8305-a612-47c8-b22b-35fe470dedd9.PNG)

[drag & drop image(s) here!]

## Description

[describe the issue here!]:

I need to reduce space between charts and with in chart border space is high. can we reduce this?

## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

**Comment by junlincc** [comment]
Please provide you rational along with a high res mockup for any UI change proposal, using one of the issue templates. Closing the issue for now.
