### ISSUE TITLE
[dashboard]Omnibar issues and enhancements

### ISSUE THREAD

**Issue by geido** [apache/superset#16198]
#### Issues with the current implementation
There are several issues currently affecting the experimental Omnibar functionality:

- The Omnibar only opens up on a Dashboard page but not on the Dashboards' list
- The Omnibar does not reset the input when closed and opened back. Currently, it keeps the previous search
- Selecting an option in the dropdown is not possible with the arrow keys due to the autocomplete
- Closing the Omnibar is only possible through reloading. The Omnibar should be closable with the ESC key (this PR introduces this ability https://github.com/apache/superset/pull/16168). I suggest it should close also when clicking outside of the modal.

_(thanks to @michael-s-molina for spotting some of these)_

#### Solutions
- Make the Omnibar appear on the Dashboards' list with _cmd + k_ or _ctrl + k_
- Clear up the search when the Omnibar is closed
- Disable autocomplete
- Close the Omnibar when clicking outside

#### Looking forward
I believe that the Omnibar does not provide much value right now as its only ability is to search for Dashboards. Also, it is only available on the Dashboard page (soon on the Dashboards' list) and nowhere else. 

It would make more sense if the Omnibar was available everywhere and would allow searching for the main items in Superset, including the Charts.

**Comment by geido** [comment]
I'll start working on the solutions that I have proposed up there as soon as priorities will allow

**Comment by srinify** [comment]
cc @hughhhh as well who I believe did some of the Omnibar work

**Comment by geido** [comment]
@junlincc FYI

**Comment by junlincc** [comment]
@geido @michael-s-molina thank you for spotting it and taking it on. feel free to work on any low hanging fruit to uplevel superset, while I am planning for Q4. :)

**Comment by junlincc** [comment]
And let's remove the feature flag once all the enhancement goes in :)  @rusackas sgty?

**Comment by rusackas** [comment]
I believe the omnibar has been removed as of 2.0, and this is no longer relevant. If I'm taking crazy pills, let me know.
