### ISSUE TITLE
Sort by Entry on Bar Chart not sorting correctly

### ISSUE THREAD

**Issue by kevin-struckhoff** [apache/superset#16204]
The rendering of a Bar Chart does not adhere to the Sort By column setting. As shown in the attached file, the bar chart does not sort according to the Sort By column setting. The data set produced does it correctly. The query produced is correct:

SELECT day_of_week_ord AS day_of_week_ord,
       day_of_week_short AS day_of_week_short,
       AVG(avg_calories) AS "AVG(avg_calories)"
FROM public.calories_wk_agg
GROUP BY day_of_week_ord,
         day_of_week_short
ORDER BY day_of_week_ord ASC
LIMIT 10000;

![Bar-Chart-Sort-By-Error](https://user-images.githubusercontent.com/88514509/129090418-9f664a65-9b02-4cf3-b0b3-a3fc0d57b82f.png)

- superset version: `1.2`
- python version: `3.8`

**Comment by junlincc** [comment]
It should have been fixed in master(?)

**Comment by kevin-struckhoff** [comment]
Doesn't appear to be. I'm on version 1.2.0:

superset version
logging was configured successfully
2021-08-11 13:53:57,158:INFO:superset.utils.logging_configurator:logging was configured successfully
2021-08-11 13:53:57,165:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
/root/venv/lib64/python3.8/site-packages/flask_caching/__init__.py:201: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn(
No PIL installation found
2021-08-11 13:53:57,442:INFO:superset.utils.screenshots:No PIL installation found
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Superset 1.2.0
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

running the command 'pip3.8 install apache-superset -U' returns many lines of 'Requirement already satisfied:" and then exits w/o updating anything. It's not fixed in my version.
