### ISSUE TITLE
[Graph]color scheme change does not take effect

### ISSUE THREAD

**Issue by junlincc** [apache/superset#16217]
Please see video, latest master
To repro, open the example chart Energy Force Layout, and try to change the color scheme, see no change. 

https://user-images.githubusercontent.com/67837651/129135822-edd8c458-d6ac-4293-97a0-a1e03e402b5a.mov

**Comment by jinghua-qa** [comment]
color theme did not apply when change the color theme in dashboard

**Comment by rusackas** [comment]
This does indeed still seem to be the case as of Superset 2.0.1. @mayurnewase do you think you might have bandwidth to take a look at this since you made the (fantastic) [initial PR](https://github.com/apache/superset/pull/13111)?

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
