### ISSUE TITLE
Time range filter not working with Trino.

### ISSUE THREAD

**Issue by rvazquezglez** [apache/superset#16223]
I have created a query for Trino DB using SQL explorer, one of the columns is a time column (`timestamp(3) with time zone` type on Trino), if I try to apply a time filter over that column (either the same SQL explorer or a filter box on a dashboard), I'm getting this error:

```
Error: line 19:19: Cannot apply operator: timestamp(3) with time zone <= varchar(26)
```

### Expected results

Date filter applied and get results

### Actual results

Getting an error.

#### Screenshots

![image](https://user-images.githubusercontent.com/373814/129142467-d06d2ea7-e497-48db-a460-68e1c06aa0f7.png)

#### How to reproduce the bug

1. Setup a connection to a Trino instance
2. Visualize a table with a timestamp or date column
3. Try to apply a date or timestamp filter

### Environment

- superset version: `1.2.0`
- python version: `3.8`
- node.js version: `not present`
- any feature flags active: not activated any.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I believe the root cause is that [Trino (formerly PrestoSQL) doesn't automatically convert `VARCHAR` to `TIMESTAMP` or `DATE`](https://stackoverflow.com/a/38041684/1195507), and this could be fixed by adding the word `date` or `timestamp` in the query.

If I go to "view query" I see the date is passed as a varchar: 

```
WHERE seated_time >= '2021-08-11 00:00:00.000000'
  AND seated_time < '2021-08-12 00:00:00.000000'
  ```

**Comment by rvazquezglez** [comment]
I was able to work around this by not selecting a time column, [enabling `ENABLE_TEMPLATE_PROCESSING`](https://medium.com/geekculture/interactive-dashboards-in-apache-superset-ec4a3bf9bc82) and using templates like:

```
WHERE objectid_timestamp(_id) >= parse_datetime('{{from_dttm}}','YYYY-MM-dd''T''HH:mm:ss') 
     AND objectid_timestamp(_id) < parse_datetime('{{to_dttm}}','YYYY-MM-dd''T''HH:mm:ss') 
     ```

**Comment by rvazquezglez** [comment]
There are some graphs that require a time column, for example, area charts:
![image](https://user-images.githubusercontent.com/373814/131690512-30749dd9-18ca-40ff-87b3-178a63af1c03.png)

After selecting a time column
![image](https://user-images.githubusercontent.com/373814/131690419-c90fd4db-895f-4376-9a38-4fc7e7a03b22.png)

A similar error is shown:
![image](https://user-images.githubusercontent.com/373814/131690092-9cd750e1-630c-4834-a4dc-64c85e8565d8.png)

**Comment by iercan** [comment]
We are experiencing same issue. It is broken after we changed sqlalchemy-trino==0.4.1 with trino==0.315.0. I reverted package and problem solved. Seems like there is a compatibility issue with new trino client

**Comment by drummerwolli** [comment]
bump. still a problem in 2023 ...

**Comment by cristovamperes** [comment]
same problem using amazon athena

**Comment by michael-s-molina** [comment]
It seems this is fixed in the latest supported versions 3.0.4 and 3.1.1. Please, feel free to reopen if that's not the case.

**Comment by dinoel93** [comment]
I have same problem with Superset Version: 3.1.1

**Comment by dinoel93** [comment]
@rusackas , done: https://github.com/apache/superset/issues/27621
