### ISSUE TITLE
[cross filter] clicking on the magnifier in cross filter indicator did not bring to emitting chart

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16220]
When user have a long list of chart on dashboard, clicking on cross filter indicator did not bring user to the emitting chart or highlight on emitting chart, can we implement this feature ? 

https://user-images.githubusercontent.com/81597121/129140015-a5d5cd6b-07ad-470e-b3cf-17cd26c3c76c.mov

**Comment by junlincc** [comment]
Expected behavior: when user click a slice to emit x-filter, and hover to the magnifier on the indicator, it should take user to the emitting chart (with a highlight?)
