### ISSUE TITLE
Dashboard loads very slowly with 15+ charts

### ISSUE THREAD

**Issue by niclas-grahm-d2v** [apache/superset#16224]
I have a dashboard with many charts. All the charts load data from the same dataset, and the dataset has ~300 rows in it. I have data cache setup with redis (snippet from superset_config.py below).

When opening the dashboard, the frontend client freezes for 10-30 seconds before all the charts are rendered. Going through the logs, it seems like the chart data is served from cache properly.

What can I do to increase performance in this scenario? Thanks.

###  Environment
* superset version: master, commit `fbe6f1605230cfc0a390b8fe52f3c96e35dea6a6`
* python version: 3.8.10
* node.js version: 10.19.0
* any feature flags active: ENABLE_TEMPLATE_PROCESSING, DASHBOARD_RBAC, ROW_LEVEL_SECURITY, OMNIBAR, DASHBOARD_NATIVE_FILTERS_SET, DASHBOARD_CROSS_FILTERS

### superset_config.py
```
ROW_LIMIT = 5000
SUPERSET_WORKERS = 4
SUPERSET_WEBSERVER_ADDRESS = xxxxxxx
# The base URL to query for accessing the user interface
WEBDRIVER_BASEURL = xxxxxxx
# The base URL for the email report hyperlinks.
WEBDRIVER_BASEURL_USER_FRIENDLY = WEBDRIVER_BASEURL
SUPERSET_WEBSERVER_PORT = 8088

SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = True
SECRET_KEY = xxxxxxx
SQLALCHEMY_DATABASE_URI = 'postgresql+psycopg2://xxxxxxx:xxxxxxx@xxxxxxx/xxxxxxx'
# SQLALCHEMY_DATABASE_URI = 'sqlite:////home/ubuntu/.superset/superset.db'
WTF_CSRF_ENABLED = True
WTF_CSRF_TIME_LIMIT = 60 * 60 * 24 * 365

CACHE_DEFAULT_TIMEOUT = 86400

ENABLE_ROW_LEVEL_SECURITY = True


CACHE_CONFIG = {'CACHE_TYPE': 'simple'}
DATA_CACHE_CONFIG = {
'CACHE_TYPE': 'redis',
'CACHE_DEFAULT_TIMEOUT': 86400,
'CACHE_KEY_PREFIX': 'superset_',
'CACHE_REDIS_HOST': 'localhost',
'CACHE_REDIS_PORT': 6379,
'CACHE_REDIS_DB': 1,
'CACHE_REDIS_URL': 'redis://localhost:6379/1'
}

FEATURE_FLAGS = {
        'ENABLE_TEMPLATE_PROCESSING': True,
        'DASHBOARD_RBAC': True,
        'ROW_LEVEL_SECURITY': True,
        'OMNIBAR': True,
        'ROW_LEVEL_SECURITY': True,
        'DASHBOARD_NATIVE_FILTERS_SET': True,
        # 'DASHBOARD_NATIVE_FILTERS': True,
        'DASHBOARD_CROSS_FILTERS': True
}
```

**Comment by junlincc** [comment]
https://github.com/apache/superset/issues/15687 

Apologize for the regression! We are actively working on the dashboard perf issue, you can find update in above ticket. Closing this one for now.  

cc @kgabryje @stephenLYZ
