### ISSUE TITLE
[gallery][advanced analytics] some time series charts under #Advanced-Analytics did not have AA in data panel

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16238]
Some time series charts under #Advanced analytics did not have AA in data panel.

Charts missing Advance Analytics under the #Advanced-Analytics tag:
Time-series Line Chart
Time-series Area Chart
Time-series Bar Chart v2
Time-series Scatter Plot
Mixed Time-Series
Time-series Table
Time-series Smooth Line

Also some charts have AA did not show under #Advanced-Analytics tag:
Line chart
Area chart

### Expected results

All charts under #Advanced analytics in gallery should have Advance analytics in data panel

### Actual results

Some time series charts under #Advanced analytics in gallery should have Advance analytics in data panel

#### Screenshots
<img width="1791" alt="Screen Shot 2021-08-12 at 11 14 37 AM" src="https://user-images.githubusercontent.com/81597121/129247703-a8b2f6ef-1451-495f-b1a8-54e369d9a8fb.png">

### Environment

(please complete the following information):

- superset version: `superset master`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
Mixed Time-Series  
Time-series Table
Please remove from the tag, i thought we had enough time to add it to those chart... but we didn't 🤦🏾‍♀️
Time-series Line Chart  
Time-series Area Chart  
Time-series Bar Chart v2  
Time-series Scatter Plot
Time-series Smooth Line
can be easily added back, they got lost when we split time-series echarts to different entry points

**Comment by junlincc** [comment]
@stephenLYZ @zhaoyongjie do you guys know how AA got lost in the transition? 

I would probably not promote NVD3 Line chart Area chart since they will be deprecated soon
