### ISSUE TITLE
explore: Change dataset modal shows unnecessary blank space

### ISSUE THREAD

**Issue by geido** [apache/superset#16249]
## Screenshot

https://user-images.githubusercontent.com/60598000/129256458-4a582b35-11d2-42a0-afb0-c3911b5957d8.mp4

## Description

The "Change dataset" modal shows a big blank space at the bottom when the pagination is disabled

**Comment by geido** [comment]
I'll be fixing this as soon as https://github.com/apache/superset/pull/16232 is merged

**Comment by junlincc** [comment]
issue resolved, closing the issue:) thanks @geido
