### ISSUE TITLE
Use Regex and Wildcards in Dashboard/Chart Search

### ISSUE THREAD

**Issue by matthewphua** [apache/superset#16244]
**Is your feature request related to a problem? Please describe.**
It would be great if one could use regex or wildcard sql search in the search bar for dashboards and charts.

**Describe the solution you'd like**
Ability to use regex/wildcards

**Describe alternatives you've considered**
None

**Comment by rusackas** [comment]
I know there's complexity around this, which is why it hasn't already happened. Nonetheless, I like the idea. If you want to open an Ideas thread on the Discussions tab, that's the right place to put these things nowdays. Closing this issue since it's inactive, and not a bug.
