### ISSUE TITLE
[Gauge]Cross Filtering for Gauge Chart Issue (Filter Icon not appearing on other charts) 

### ISSUE THREAD

**Issue by matthewphua** [apache/superset#16255]
When you select a category on gauge chart for cross-filtering. Even though other charts are impacted by the filter, the filter icon at the top of each chart doesn't appear.

The filter icon should appear signifying that the gauge chart filter is affecting the other chart. 

#### Screenshots

https://user-images.githubusercontent.com/85198947/129422102-383470f3-9994-455c-93f9-fc08000d25cb.mov

**Comment by junlincc** [comment]
@stephenLYZ Hey Stephen, can you please help take a look at this issue? also, there's an open PR in superset-ui, that partially address comments in  https://github.com/apache/superset/issues/14209. if you can take care of all the bug fixes and enhancement requests listed with/without refreshing the open PR, that will be great! 🙏

**Comment by stephenLYZ** [comment]
@junlincc I will take look at it. Maybe I need to open a new PR as I cant edit this PR directly https://github.com/apache-superset/superset-ui/pull/1070

**Comment by junlincc** [comment]
@stephenLYZ thank you so much for taking it on!
