### ISSUE TITLE
[dashboard] page title does not change back after navigating away from dashboard

### ISSUE THREAD

**Issue by nytai** [apache/superset#16254]
### Expected results

When navigating away from a dashboard the page title change back to "Superset"

### Actual results

The page title is still the dashboard's title 
#### Screenshots

<img width="252" alt="Screen Shot 2021-08-13 at 2 04 07 PM" src="https://user-images.githubusercontent.com/10255196/129418323-43356bd6-e617-4a44-8ff7-2bcdb404b76b.png">
<img width="942" alt="Screen Shot 2021-08-13 at 2 04 19 PM" src="https://user-images.githubusercontent.com/10255196/129418325-69d98d44-f583-4575-a42d-56633c9b840f.png">

#### How to reproduce the bug

1. view a dashboard, eg "World Bank's Data"
2. notice title of the page/tab/document is the name of the dashboard, eg "World Bank's Data"
3. navigate away via the menu, eg Data > Databases
4. notice the title of the page/tab/document is still the title of the dashboard, eg "World Bank's Data"

### Environment

- superset version: `master`
- python version: `3.7.5`
- node.js version: `14`
- any feature flags active: None

### Additional context

Very minor issue, likely happened when we move the dashboard "app" into the SPA bundle.

**Comment by junlincc** [comment]
i didn't notice before. 🤦🏾‍♀️ tyty @nytai 🙏 

@geido slightly higher priority 🙏
