### ISSUE TITLE
[SQLLab] Timestamp column type metadata shows up incorrectly in left panel

### ISSUE THREAD

**Issue by michellethomas** [apache/superset#16258]
If you look up a table in sqllab on the left hand side to see the table metadata, tables with timestamp types show up as: 

<class 'superset.models.sql_types.base.literal_dttm_type_factory.<locals>.TemporalWrapperType'>

### Expected results

The correct type.

### Actual results

<class 'superset.models.sql_types.base.literal_dttm_type_factory.<locals>.TemporalWrapperType'>

#### How to reproduce the bug

1. Add schema and a table to the left panel for a table with a timestamp type to see the table metadata (we noticed this in Presto)
2. When the table metadata shows up see "<class 'superset.models.sql_types.base.literal_dttm_type_factory.<locals>.TemporalWrapperType'>" for the type instead of the correct type

Left panel
![image](https://user-images.githubusercontent.com/817955/129428555-a71a9f8e-bbab-4483-9f06-5850df66b5a1.png)

### Environment

(please complete the following information):

- superset version: master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by caoquyvu** [comment]
Got the same error

**Comment by villebro** [comment]
I'll look into this
