### ISSUE TITLE
ALerts and Reports execution log

### ISSUE THREAD

**Issue by bretton7700** [apache/superset#16267]
I am able to activate the alerts and reports by changing the feature flag for alerts to true. However after creating reports that should trigger every minutes i do not receive any email and the log remains as no data. i have configured redis and set up a celery beat but no avail still. will appreciate any help.Thank you.

![issue](https://user-images.githubusercontent.com/65695871/129475618-6d09396e-4f1c-4c67-967f-ddd1e71dbf68.png)

**Comment by lizheng404** [comment]
I have the same problem.

**Comment by rusackas** [comment]
A LOT of updates have been made in this area, and the issue has largely gone cold here, so I'm going to optimistically close this in hopes that it's been resolved. If anyone encounters such issues in currently supported versions of Superset (e.g. 2.0.x) please let us know so we can re-open the issue!

CC @eschutho for good measure :)

**Comment by eschutho** [comment]
Not sure if this was the issue here, but for anyone reading this thread, if you're using docker, be sure to set `ALERT_REPORTS_NOTIFICATION_DRY_RUN = False` in your `docker/pythonpath_dev/superset_config_docker.py` local overwrite file in order to execute the emails.
