### ISSUE TITLE
Sqllab results columns are not sortable for large number of columns

### ISSUE THREAD

**Issue by michellethomas** [apache/superset#16261]
For a sqllab query that returns a large number of columns (I observed this in a query with ~70 columns), the sorting functionality is broken. Columns do not sort at all.

I'm not sure how easy this is to fix. Do we want to consider this a limitation of sqllab or is this fixable?

### Expected results

Columns have the ability to sort

### Actual results

When you click on the column header it does not sort and does not show the sorting arrow

#### How to reproduce the bug

1. Go to sqllab and run a query with 70 columns
2. Try to sort the results

### Environment

(please complete the following information):

- superset version: `master`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by averma111** [comment]
I will have a look into it

**Comment by junlincc** [comment]
Similar issue happened before when # of columns is over 60is, i remember. @averma111 thanks for volunteering, let us know if you need help :)

**Comment by averma111** [comment]
@junlincc sure I will let you know.

**Comment by averma111** [comment]
@junlincc and @yousoph   I am looking at superset-frontend--->src-->components-->SqlLab-->QueryTable-->Index.jsx file, for object modalTitle={t('Data preview')} to check if the  sorting arrow is poping up for table less then 50 columns.

**Comment by averma111** [comment]
@etr2460 I am working on finding the issue with UI of the super set. Give me couple of days

**Comment by etr2460** [comment]
Hi @averma111 were you able to find the issue/are you still working on this issue?

**Comment by averma111** [comment]
@etr2460  my apologies I didnt get time to work on this bug.I am pulling out my self.

**Comment by rusackas** [comment]
Looks like this was resolved without being auto-closed.
