### ISSUE TITLE
[Dataset]missing datatype/NULL in virtual dataset(?)

### ISSUE THREAD

**Issue by zhugw** [apache/superset#16265]
Why if it is virtual, call `/datasource/external_metadata/table/{id}/ ` some type is null
```
    {
        "name": "APPID",
        "type": "INT",
        "is_date": false
    },
    {
        "name": "INDEX1",
        "type": null,
        "is_date": false
    },
    {
        "name": "INDEX13",
        "type": null,
        "is_date": false
    },
    {
        "name": "AFFLISTSTKCODE",
        "type": "STRING",
        "is_date": false
    }
```
![image](https://user-images.githubusercontent.com/4953871/129466478-4269ab99-5fb2-4bff-9b20-5696a9539550.png)
but if it's physical table it's not null

**Comment by zhaoyongjie** [comment]
Hi @Zhugw,
I guess the column type was not inferred in the API. Do you mind share SQL of virtual dataset?

**Comment by zhugw** [comment]
@zhaoyongjie 

it's oracle table and the sql see below
```
select statdate,appname,appid,index1,index13,AFFLISTSTKCODE from t where appname in (
    select appname
    from (select appname
          from t
          where statdate = (select max(statdate) from t)
          order by index1 desc)
    where rownum <= 100
)
```

**Comment by junlincc** [comment]
Looks like you are on an older version of Superset, can you please fill out the issue template and verify this is still an issue on Superset master?

**Comment by zhugw** [comment]
@junlincc I'm using v.1.2.0

**Comment by junlincc** [comment]
gotcha, to clarify, the issue is - when there's null in a virtual dataset, the data type can be inferred? @zhugw

**Comment by zhugw** [comment]
@junlincc 
"when there's null in a virtual dataset"

Do you mean INDEX1 and INDEX13 column include null value so it cannot infer, but AFFLISTSTKCODE still has null value

**Comment by rusackas** [comment]
Closing this since it has gone inactive AND refers to an old version. Happy to re-open if this issue persists in 2.1.0.
