### ISSUE TITLE
[charts] Keep similar features across all charts

### ISSUE THREAD

**Issue by kamalkeshavani-aiinside** [apache/superset#16271]
**Is your feature request related to a problem? Please describe.**
Currently there are many charts with different kind of features. Ex.,
1. Line Chart can add a title for X-axis but Mixed Time-series cannot.
2. Bar chart can show values in chart, but line or area charts can not.
3. I can have different formatting in tooltip only in Time-series chart.

When our end user see one feature in a chart, they expect to be able to use the same feature in all other charts. But due to this limitation this is not possible right now.

**Describe the solution you'd like**
There should be guidelines for every chart type for all the types of controls/features available to the user for that chart based on its type.
Here are some I could think of, but clearly more should be added by contributors and maybe even community can add their suggestions.

**X-axis:**
1. Add title
2. Show bounds
3. Set bottom margin
4. Set tick layout
5. Reduce X ticks
6. Show/hide Major-minor gridlines
7. Set minor ticks and gridlines granularity
8. Value formatting

**Y-axis:**
1. Add title
2. Show bounds
3. Set bounds
4. Set left/right margin
5. Set tick layout
6. Reduce Y ticks
7. Show/hide Major-minor gridlines
8. Set minor ticks and gridlines granularity
9. Value formatting
10. Make logarithmic axis

**Tooltip:**
1. Set new formatting for all values, and default to formatting of each axis(This is helpful when we want to keep chart clean, but show more accuracy/decimal points in the tooltip)
2. Set Rich Tooltip
3. Chose to show null values in Rich Tooltip
4. Show total or % distribution in Rich tooltip if possible

**Line Chart:**
1. Show markers
2. Change marker size
3. Show values on points

**Bar Chart:**
1. Set Stack or Group
2. Set order of bars in stack or group: by metric order, by group by element value, by group by element alphabetical, by another metric
3. Show bar values on top/center
4. Show total bar values when stacked or individual bar values
5. Set minimum width of a bar
6. Set minimum distance between bars when grouped

**Area Chart:**
1. Change opacity of area
2. Show markers
3. Change marker size
4. Show values on points

**Additional context**
I guess that no re-work can be expected on legacy charts, but the least I can expect is to start following such guidelines for the new echarts.
And if making this possible is not very hard, I would really appreciate doing the changes(atleast the easy ones) in legacy charts as well, since they will be used for some more time(until advanced analytics are enabled for echarts).

**Comment by junlincc** [comment]
Thanks for the detailed proposal. I believe you are referring to all the NVD3 legacy charts that we are no longer maintaining? 
There's a lot to cleanup besides charts mentioned above. However, It's a bit harder just to remove a feature from any specific charts in an OSS BI tool. Even when we migrate NVD3 to Echarts, we have to make sure to reach feature parity and backward compatible. There are ways to better hide some inconsistent control in certain charts, which we will be working on in Q4.

**Comment by kamalkeshavani-aiinside** [comment]
@junlincc Thanks for your comment.
Just to clarify, I am not requesting for removal of any feature. Rather I am requesting that if a we come up with a feature/control in one chart, then it should be made available to all other charts which can use that.

**Comment by junlincc** [comment]
yes i agree. @kamalkeshavani-aiinside 
the difficulty is that all charts have different author/creator, and many of them were created without design support which caused the inconsistency. it's a long process to replace/redesign/change library in order to reach feature parity. but thanks for your suggestion!

**Comment by codek** [comment]
it's a shame this didnt get actioned, the tooltip thing is mentioned in https://github.com/apache/superset/issues/4462 and https://github.com/apache/superset/issues/23406
