### ISSUE TITLE
[Pivottable]Time column formatter doesn't apply correctly when time grain is added 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#16283]
In Pivot table v1, when time grain is added, and have the temporal column as row or column, time formatter doesn't work properly. 

Actual result - the end date is not formatted. 
![image (18)](https://user-images.githubusercontent.com/67837651/129641035-0462ea40-85a8-41b5-baee-ec1147c4ef28.png)

Expected result - in legacy pivot table, both ends show properly. 
![image (17)](https://user-images.githubusercontent.com/67837651/129640824-48d539a3-2a71-4766-bd17-b7c7ff32aad7.png)

@kgabryje

**Comment by kgabryje** [comment]
https://github.com/apache-superset/superset-ui/pull/1315

**Comment by rusackas** [comment]
Reopening since the `superset-ui` changes have not been brought over to `superset` yet. This will take place in #16350 which should close this issue once and for all.
