### ISSUE TITLE
[echarts]Support `Extra Controls` on the Time-Series Area Chart for feature parity

### ISSUE THREAD

**Issue by etr2460** [apache/superset#16298]
**Is your feature request related to a problem? Please describe.**
The new time series area chart doesn't allow the viewer of a chart on a dashboard to toggle between a stacked view (with the metric values) and the expanded view (showing percent contribution). This is a really commonly used feature on the nvd3 area chart that should be supported in the new one for feature parity.

The control on the nvd3 area chart:
![image](https://user-images.githubusercontent.com/7409244/129792061-bf2ea1e1-7cfc-41ae-865a-7aa7590fb4d7.png)

**Describe the solution you'd like**
Allow a chart viewer to switch between stacked and expanded views for the area chart using a control on the chart itself

cc: @junlincc and maybe @villebro? Not sure who's owning the echarts migration

**Comment by junlincc** [comment]
@etr2460 absolutely! it's in our todo list. will get to it asap. please file issues if you see anything is missing in new time-series bar, area and line. we would love to get to feature parity asap

**Comment by junlincc** [comment]
@stephenLYZ i don't think echarts offer those option out of the box, feel free to open a PR in Echarts and we can expedite it. 

cc @villebro

**Comment by junlincc** [comment]
@stephenLYZ ^^ lmk if you've seen this issue, take your time to finish other tasks first. thank you thank you!🙏
