### ISSUE TITLE
[time series scatter plot] rich tooltip still show when pointing at blank area

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16304]
In time series scatter plot chart,  rich tooltip still show when pointing at blank area

### Expected results

 rich tooltip do not show when pointing at blank area

### Actual results

 rich tooltip still show when pointing at blank area

#### Screenshots

https://user-images.githubusercontent.com/81597121/129813490-70cc4f6b-c749-4481-9e0a-1eb2d1f50163.mov

#### How to reproduce the bug

1. create a time series scatter plot with large interval
2. hoover over on the blank region to see rich tooltip
3. See error

### Environment

(please complete the following information):

- superset version: latest master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@stephenLYZ mind taking a look?

**Comment by stephenLYZ** [comment]
working on it

**Comment by stephenLYZ** [comment]
After some attempts, I found that it was difficult for us to control this behavior. This is the logic of ECharts itself, which finds the closest series and keeps showing it (as long as the mouse is on the graph). Maybe we'd better open an issue for the ECharts repo.

**Comment by junlincc** [comment]
@stephenLYZ thanks for investigating! if we do open a pr in echarts repo, what solution should be? only show the tooltip when hover on the exact series? this is one of the echarts features that are "too smart for the users" 😁

**Comment by rusackas** [comment]
The time axis still shows, but not the data/legend/labels. This seems resolved, so I'll close it.
