### ISSUE TITLE
[listview]add dataset description to dataset listview on hovering 

### ISSUE THREAD

**Issue by zhxjdwh** [apache/superset#16309]
**Is your feature request related to a problem? Please describe.**
The dataset name is too unfriendly for non-English users!!!

**Describe the solution you'd like**
The dataset name is too unfriendly for non-English users, I hope to add a "dataset display name " field, allowing users to modify according to their own language

**Describe alternatives you've considered**

**Additional context**

**Comment by zhxjdwh** [comment]
![image](https://user-images.githubusercontent.com/9401765/129830633-6c315511-b76f-466f-97d1-b46e752832d9.png)

**Comment by junlincc** [comment]
you can add a description to the dataset,, the description will show up in the viz gallery when you hover on it. 
we probably should add tooltip to display description on hovering in listview as well. 

@michael-s-molina 🙏 wdyt?
