### ISSUE TITLE
[Explore]Druid Time Series Error

### ISSUE THREAD

**Issue by matthewphua** [apache/superset#16302]
A Druid Error is generated when creating any time series chart. There error is cause by this line: 
`WHERE FLOOR("__time" TO QUARTER) = '2015-07-01T00:00:00.000Z'`

### Expected results
An expected line chart should appear. 

### Actual results

A Druid error appears: 
<img width="1786" alt="Screen Shot 2021-08-17 at 3 49 37 PM" src="https://user-images.githubusercontent.com/85198947/129810739-b676a493-5b45-4c52-b2ef-7c9090e4721b.png">

<img width="944" alt="Screen Shot 2021-08-17 at 3 53 52 PM" src="https://user-images.githubusercontent.com/85198947/129811072-c85fd4c9-868f-4665-a2fd-e78de70a251c.png">

#### How to reproduce the bug

1. Use a Druid DB
2. Create a line chart, enter a time grain (optional, I think with or without a time grain, it causes an error) 
3. Fill out all required fields
4. Run and See error

**Comment by junlincc** [comment]
it can be reproduced in table chart. but not nvd3. @matthewphua thank you for reporting! 🙏

@zhaoyongjie let's take a look? thanks

**Comment by zhaoyongjie** [comment]
Hi @matthewphua @junlincc,  this issue exists in all databases/data warehouse with Calcite as the SQL parser(Druid/Kylin/Drill), because Calcite doesn't make an implicit conversion for difference data type.

the SQL should be
```
WHERE FLOOR("__time" TO QUARTER) = case('2015-07-01T00:00:00.000Z', timestamp)
```

**Comment by betodealmeida** [comment]
A few comments on this:

- If you remove `__time` from the group bys the query works. You shouldn't add `__time` to the group bys because you're already using it for the time grain.
- Druid already supports joins, if we turn it on for the DB engine spec then the query also works.
- We should still fix 2-phase queries so that the predicate for the top N works regardless of types.

**Comment by rusackas** [comment]
@betodealmeida do we still need to make changes here? Was tempted to close this as stale, but it sounds like a legit problem might be lurking still.

**Comment by betodealmeida** [comment]
I think it should be fine to close, @rusackas. There's a lot of people using Superset with Druid, and I think we'd get more reports if this was still happening.
