### ISSUE TITLE
[d&d hybrid] place holder for temporal column 

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16307]
place holder for temporal column  should be 'Drop temporal column here or click'

<img width="1781" alt="Screen Shot 2021-08-17 at 6 17 10 PM" src="https://user-images.githubusercontent.com/81597121/129821190-e7d08f3f-7cb3-4776-bd2d-1159253f9bd4.png">

### Environment

(please complete the following information):

- superset version: latest master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
right right, different versions of control panel should have different place holders. @kgabryje

**Comment by kgabryje** [comment]
https://github.com/apache-superset/superset-ui/pull/1317

**Comment by rusackas** [comment]
Reopening since the `superset-ui` changes have not been brought over to `superset` yet. This will take place in #16350 which should close this issue once and for all.
