### ISSUE TITLE
[explore] add clear button on the search filed on left panel in explore?

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16300]
can we add clear button on the search filed on left panel in explore? it will be more convenient for user to delete long words

<img width="1792" alt="Screen Shot 2021-08-17 at 2 28 21 PM" src="https://user-images.githubusercontent.com/81597121/129803216-25a89c95-fab9-4670-998f-7625a582c14e.png">

**Comment by junlincc** [comment]
@kgabryje Let's do it! 

@jinghua-qa good one thanks for suggesting! 🙏
