### ISSUE TITLE
[sort by][time series bart chart v2]Sort by is not working for time series bar chart v2

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16305]
Sort by is not working for time series bar chart v2

### Expected results
When Sort DESCENDING is select, data is return in descending 
 
### Actual results

When Sort DESCENDING is select, data is not 

#### Screenshots

<img width="1785" alt="Screen Shot 2021-08-17 at 4 54 04 PM" src="https://user-images.githubusercontent.com/81597121/129815528-349a2027-ffbb-46bf-bf20-8b7cf65d3c71.png">
<img width="1787" alt="Screen Shot 2021-08-17 at 4 54 14 PM" src="https://user-images.githubusercontent.com/81597121/129815532-c32be1f2-9426-4228-ad0e-cb2c132d1bcd.png">
return in descending 

#### How to reproduce the bug

1. create a time series bar  chart, select SORT BY and select Sort DESCENDING
2. observe data panel
3. See error

### Environment

(please complete the following information):

- superset version: lastest master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
thanks for catching!! @villebro

**Comment by villebro** [comment]
We may need to reconsider what the expected behavior here is. AFAIK, the primary role of the sort control is to make sure that we can pick the top n series based on a certain metric (see the subquery that queries for the top 100 series based on `count` in descending order). The ordering is done correctly in the analytical database, so the data is returned in descending order based on the `count` column. However, the data in the result pane shows the data after the pivot operation, where each series is given a column of their own. We can of course resort the pivoted data, but that wouldn't change how the bars are rendered.

**Comment by SamRozhkov** [comment]
I fixed post processing for correct work sorting data.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.

**Comment by bobi-saputra** [comment]
still happened in versions 3.1.0 ,

**Comment by bobi-saputra** [comment]
> Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.

still happened in versions 3.1.0 ,

**Comment by rusackas** [comment]
OK... I'll just re-open this for now. PRs welcome/encouraged. If this goes stale again, we may close it again :)

**Comment by rusackas** [comment]
It's been another four months or so, so I'm going to close this as stale again. Also, from @villebro 's comment above, it seems that this is a design/messaging issue more so than a bug. If anyone wants to take this up as something to improve, I think it might be wise to open up either an Ideas thread on Github Discussions, or open a (probably pretty small) SIP to get some official consensus around this before implementing.
