### ISSUE TITLE
[time series table] Run button did not light up or show when change time series column settings

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16319]
Run button did not light up or show when change time series column settings

### Expected results

Run button will light up or show when change time series column settings to remind user to click and show effect

### Actual results

Run button did not light up or show

#### Screenshots

https://user-images.githubusercontent.com/81597121/129859621-f051094f-bc49-4e1e-ad6b-e4c5432b74f1.mov

#### How to reproduce the bug

1. open time series table
2. change setting in time series column
3. See error

### Environment

(please complete the following information):

- superset version: latest master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
This issue is reproducible when dnd on, dnd off, dnd on+dnd hybrid on

**Comment by junlincc** [comment]
thanks for filing!! awesome qa work!! 👀
