### ISSUE TITLE
[cosmetic][pivot table v2] missing bottom table line 

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16316]
## Description
Missing the bottom line of the table in pivot table V2

## Screenshot
<img width="1786" alt="Screen Shot 2021-08-17 at 10 53 51 PM" src="https://user-images.githubusercontent.com/81597121/129845372-eacc823c-6d35-4d1f-b876-4c069b99f5f5.png">

**Comment by junlincc** [comment]
could it be the color change? @geido 🙏

**Comment by rusackas** [comment]
Unable to replicate this, so I'm closing it, but feel free to re-open if I'm mistaken.
