### ISSUE TITLE
SQL Lab cancel query in Redshift database connection does not work

### ISSUE THREAD

**Issue by yourssvk** [apache/superset#16325]
Issue:

Cancel query in Redshift queries does not work

Steps to reproduce the issue:

1. Create a Redshift Database connection in Superset
2. Run a long-running query on the Redshift Database connection on SQL Lab
3. Try to cancel the query in the middle of execution and check the Redshift Running queries and the query may not be killed.
4. The only option to kill the query is to kill it from Redshift administrative console. 

Expected results:

The query is cancelled and the transaction is rolled back on Redshift database

Actual results:

The query is left running on Redshift

**Comment by matrixhead** [comment]
hey, can i work on this

**Comment by yourssvk** [comment]
Thanks folks...

**Comment by yourssvk** [comment]
@AAfghahi any further update on this issue?

**Comment by AAfghahi** [comment]
Hi! I was assigned so that I could redirect a newer engineer to this ticket. I don't think that they ended up getting to it, but I can prioritize it :)

**Comment by yourssvk** [comment]
Thanks @AAfghahi - please :-)

**Comment by michael-s-molina** [comment]
Fixed by https://github.com/apache/superset/pull/16326
