### ISSUE TITLE
Could not load database driver: KylinEngineSpec

### ISSUE THREAD

**Issue by koureasstavros** [apache/superset#16328]
I am not sure if I did something wrong, but I just installed the Superset on Kubernetes using helm and with the following adjustments:
```
additionalRequirements:
   - kylinpy
```

I also tried some things like this:
https://stackoverflow.com/questions/68830218/apache-superset-could-not-load-database-driver-kylinenginespec
But still, I am getting this driver error even with this extra configuration, any ideas?

**Comment by srinify** [comment]
Hi @koureasstavros have you fired up the shell for the Docker container that's running Superset? I'm not a k8s expert, but once you get that shell up -- you can do something like `pip freeze | grep 'kylinpy'` to confirm that the library is available in the same Python context as Superset!

**Comment by rusackas** [comment]
Closing since this has gone inactive, and it's not clear if the advice from the thread was followed. Please feel free to ask for help in `#helm-k8-deployment on [Superset Slack](http://bit.ly/join-superset-slack) if you're still facing this.
