### ISSUE TITLE
[explore][south tables] column title with integer will mess up with the order of column in data table

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16338]
column title with integer will mess up with the order of column in data table, also column title like '6-10' cause error when viewing samples

### Expected results

1, column title with integer will not mess up with the column order when viewing in data table
2, sample table will be able to show when column title contains title like '6-10'

### Actual results

1, column order is different because column title contains integer
2, sample table show error

#### Screenshots

<img width="1790" alt="Screen Shot 2021-08-18 at 3 39 04 PM" src="https://user-images.githubusercontent.com/81597121/129981304-7650c504-5a5a-410e-8eaa-83374d218c4a.png">

<img width="1792" alt="Screen Shot 2021-08-18 at 3 39 17 PM" src="https://user-images.githubusercontent.com/81597121/129981211-a667fe54-b785-4942-84a5-9cc599fb9c00.png">

#### How to reproduce the bug

1. create a table with columns title contains string and integer as in above screenshot
2. observe data table and sample table
3. See error

### Environment

(please complete the following information):

- superset version: master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

**Comment by jinghua-qa** [comment]
@AAfghahi

**Comment by rusackas** [comment]
@jinghua-qa is this still an issue?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
