### ISSUE TITLE
Owner Permission to dashboard problem

### ISSUE THREAD

**Issue by JoaquinPretell92** [apache/superset#16337]
Hello,

Im trying to give a user owner permission to a dashboard, but when i try to save the configuration i get this error with a 400 Bad Request.

{
  "timed_refresh_immune_slices": [],
  "filter_scopes": {
    "737": {
      "estado": {"scope": ["ROOT_ID"], "immune": [697, 740]},
      "tipo_falla": {"scope": ["ROOT_ID"], "immune": [697, 740]},
      "rs_entel": {"scope": ["ROOT_ID"], "immune": [697, 740]},
      "tipo_sitio": {"scope": ["ROOT_ID"], "immune": [697, 740]},
      "tecnologias_afectadas": {"scope": ["ROOT_ID"], "immune": [697, 740]},
      "vendor": {"scope": ["ROOT_ID"], "immune": [697, 740]},
      "tipo_correlacion": {"scope": ["ROOT_ID"], "immune": [697, 740]},
      "causal_cierre": {"scope": ["ROOT_ID"], "immune": []},
      "__time_range": {"scope": ["ROOT_ID"], "immune": [697, 740]}
    }
  },
  "expanded_slices": {},
  "refresh_frequency": 0,
  "default_filters": "{\"91\": {\"__time_range\": \"No filter\"}}",
  "remote_id": 5,
  "import_time": 1628190701,
  "color_scheme": null
}

![image](https://user-images.githubusercontent.com/73810312/129978529-7a911c3f-bd16-4890-9e27-40d0d0de4c15.png)

My superset version is 1.0.1 and the user i want to give the permission have alpha role.

Regards

**Comment by amitmiran137** [comment]
Dashboard rbac wasn't implemented in 1.0.1
So not sure how to help out here
