### ISSUE TITLE
[echarts][feature-parity]display custom metric label in legend on multiple metrics

### ISSUE THREAD

**Issue by jamesrayoub** [apache/superset#16332]
## Screenshot

![image](https://user-images.githubusercontent.com/31777200/129956117-1af732f8-492f-42cf-8723-12333eadced4.png)

## Description

The legend does not show the metric label when multiple metrics are displayed despite the existence of a metric label

## Design input
Show the label instead of the name

**Comment by junlincc** [comment]
![129956117-1af732f8-492f-42cf-8723-12333eadced4](https://user-images.githubusercontent.com/67837651/129956875-229b2c0c-d4c2-4203-a2c9-642ce25e42e7.png)
Thanks James! this is a feature parity we need to reach to deprecate nvd3 charts. see legacy chart below. 

<img width="1194" alt="Screen Shot 2021-08-18 at 12 05 50 PM" src="https://user-images.githubusercontent.com/67837651/129957408-4dc3c21d-ff4c-4a6c-ad40-fce52c3e9beb.png">

**Comment by junlincc** [comment]
@suddjian can you work on this one? and make sure it works in timeseries line, smoothline, bar, scatter and step charts 🙏

**Comment by stephenLYZ** [comment]
@junlincc 
For custom metric, NVD3 seems to have the same logic, showing name instead of label
![image](https://user-images.githubusercontent.com/11830681/130359649-6a40a913-d6af-4aa6-a2ff-ba9331751a91.png)

custom metric settings:
![image](https://user-images.githubusercontent.com/11830681/130359680-53e5efe7-07a2-4f9b-85ab-bc6674e59e4f.png)

**Comment by jamesrayoub** [comment]
@stephenLYZ I do not see the same behavior... see the screenshots below. In the nvd3 line chart, the label is displayed

![image](https://user-images.githubusercontent.com/31777200/130625761-df966fed-b82e-43d9-8bb2-72b787f6e65b.png)
![image](https://user-images.githubusercontent.com/31777200/130625847-a3247b64-fdcb-4d5a-aa33-7e82a965a33d.png)

**Comment by stephenLYZ** [comment]
@jamesrayoub You are right! I think I found a way to reproduce and open a PR to fix it.

**Comment by jinghua-qa** [comment]
Test case added
