### ISSUE TITLE
[editdataset]add sql validator, potentially collapsible data table section for sql expression 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#16348]
as a user, when i create/edit a custom sql expression, I would like to receive a validation to understand whether my input is valid or not before going back to Explore, to avoid back and forth and seeing errors later. Since we are gonna redesign the whole modal, I suggest to keep this enhancement lightweight by having a VALIDATE button near/in the input field(STEP 1 @kgabryje ). in long term, we should probably display sample query data in a collapsible section(STEP 2 - @kgabryje).  

<img width="794" alt="Screen Shot 2021-08-18 at 6 34 51 PM" src="https://user-images.githubusercontent.com/67837651/129993728-d8a9a710-d292-40cd-bc06-0e0123a23777.png">
<img width="765" alt="Screen Shot 2021-08-18 at 6 34 35 PM" src="https://user-images.githubusercontent.com/67837651/129993734-cc5a6c3b-de9e-484d-99d4-09736c0ce630.png">

I would also like to add it to the metrics popover but during the popover redesign (STEP 2 @zhaoyongjie)

**Comment by rusackas** [comment]
Closing this out since it's not a bug. If anyone seeing this wants it in Superset, please open an Issues thread on Discussions, or open a PR. Thank you!
