### ISSUE TITLE
[gallery] Remove the "Formattable" tag for chart types

### ISSUE THREAD

**Issue by ktmud** [apache/superset#16340]
## Screenshot

![image](https://user-images.githubusercontent.com/335541/129983137-f11e8731-6488-4449-b145-e36d2b0a2aac.png)

## Description

The "Formattable" tag is causing frivolous matches when searching for "table" chart in the viz type gallery. I doubt people would actually want to filter by whether a chart is formattable----ideally, all charts in Superset should be formattable.

**Comment by junlincc** [comment]
@ktmud please feel free open a pr to remove :)

**Comment by rusackas** [comment]
PR opened.
