### ISSUE TITLE
[time series scatter plot]set marker size for scatter plot threshold 0-20

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16343]
Current range for marker size in time series scatter plot is too wide.
## Screenshot

<img width="1519" alt="Screen Shot 2021-08-18 at 4 35 13 PM" src="https://user-images.githubusercontent.com/81597121/129985495-39263f53-a1e2-46e9-b9d6-c6426f1344e2.png">

**Comment by junlincc** [comment]
@stephenLYZ 🙏

anything above 20 is too big for scatter. im not sure if we wanna apply the new range to all time series chart, or separate the plugins

**Comment by junlincc** [comment]
<img width="1453" alt="Screen Shot 2021-08-18 at 6 15 41 PM" src="https://user-images.githubusercontent.com/67837651/129992223-c5d9b782-8e8b-4e95-b867-c6be30dac817.png">
so is line, let's keep marker under 20

**Comment by stephenLYZ** [comment]
@junlincc yeah. I think it can be controlled in the range of 0-20, both line chart and scatter chart

**Comment by zhaoyongjie** [comment]
Maker size can be controlled by a specific metric value, a narrow range is acceptable. Improvements will be made in the future.
