### ISSUE TITLE
[time series Echarts] legend margin is not work in time series Echarts and radar chart

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16345]
Legend margin is not work in time series Echarts and radar chart

### Expected results
change legend margin will change marge

### Actual results
large number of  legend margin did not change marge

#### Screenshots
<img width="1790" alt="Screen Shot 2021-08-18 at 4 39 00 PM" src="https://user-images.githubusercontent.com/81597121/129986238-f60d694e-1bc8-462b-b24b-25e078ed937c.png">

**Comment by SamuelHaleMN** [comment]
I can also confirm that the margin field does not seem to be applied.

If you have a very long list of series in the legend, it also overflows into the chart view.

Quite frustrating!

**Comment by jinghua-qa** [comment]
verified fixed.
