### ISSUE TITLE
[scatter-plot] remove contribution mode from time-series scatter chart

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16342]
Request to remove contribution mode from time-series scatter chart from @junlincc 
<img width="1782" alt="Screen Shot 2021-08-18 at 4 32 27 PM" src="https://user-images.githubusercontent.com/81597121/129985272-b29132fe-a9d8-4b0e-bd97-bf117e9bbdf5.png">

**Comment by junlincc** [comment]
@stephenLYZ sorry for overwhelming you with all the echarts requests 😅
