### ISSUE TITLE
[explore]provide option for preserving selected control values or not when switching dataviz/dataset

### ISSUE THREAD

**Issue by junlincc** [apache/superset#16344]
Different voices around whether we should preserve control select e.g. Metrics, Groupby, Filters etc. while changing data viz and dataset. 
Some users complaint that they have to manually clear all the preserved fields after changing dataset and dataviz, as their intention is actually to start a new visualization exploration from scratch. It especially doesn't make sense while switching dataset because the chances of 2 datasets have same column names is low.... To address it, we opened a PR to reset Explore page while changing dataset and data viz. 

On the other hand, 1. some users argue that they may have 2 datasets with same column names but different content for testing and production, so  it would be helpful to keep all the selected items on switching dataset. 
2. As we better organize the viz plug-ins and the control panel items, it would make sense to preserve some key input when user switch between similar chart types. e.g. timeseries bar-> timeseries line -> table; Pie->funnel->treemap etc. 

Did some audit on the current state of the product. Current behavior is very inconsistent due to recent rapid development on different chart. idk. as you can see in the long video, metric is clear inconsitently on viz change. it also happens to dataset change. 

https://user-images.githubusercontent.com/67837651/129982962-f758ba7e-4c55-46dc-9032-bca18898705a.mov

Proposed change: when user click the pill to change viz, or Change datase, we prompt user to choose whether to carry the basic selected values(metrics, groupby, filters) from current chart to the next, regardless the content/column make sense. If they don't apply as expected, at least it would be user's conscious decision so that manually clearing all is not too annoying.  

In terms of UI, I'm thinking modal like below with revised content. we will need 2 designs for different scenarios for change dataset and change viz. the one for change viz can be tricky because user have to interact with the viz gallery first... 
 
<img width="408" alt="Screen Shot 2021-08-18 at 4 40 34 PM" src="https://user-images.githubusercontent.com/67837651/129985734-4cd6bb44-346f-4ee3-a14c-51b022eab9d6.png">

The downside is, at least one more click is required for ALL user when they perform either of above actions.

**Comment by junlincc** [comment]
@kicaak would you like to contribute to this small project?😁 cc  @kgabryje

**Comment by rusackas** [comment]
This is better/fixed now! Closing :)
