### ISSUE TITLE
[pivotable][feature parity]display time range with grain when temporal column is selected as row and column

### ISSUE THREAD

**Issue by junlincc** [apache/superset#16351]
With the legacy pivot table, users are able to select a temporal columns as row or column and apply d3 formatting. When time grain is apply, e.g. week, the time format header turns into a range, with d3 formatting still correctly applied. see image 1. 

![image (17)](https://user-images.githubusercontent.com/67837651/130024676-eccfd9d9-9f78-4277-90be-9217616c222d.png)

We recently added time formatter to new pivot table. it works only without time grain is added. see image 2, End date/time was not showing at all. 

![image (18)](https://user-images.githubusercontent.com/67837651/130024647-fc263231-4307-4f3c-bea1-9b8f19c6b89b.png)

Let's add the additional support to reach full feature parity of legacy pivot. 

@suddjian 🙏

**Comment by kgabryje** [comment]
@junlincc Isn't that the same task https://github.com/apache/superset/issues/16283? I've already done that, it should work on master

**Comment by kgabryje** [comment]
![image](https://user-images.githubusercontent.com/15073128/130124390-71c98085-e392-4cef-99be-db2a8a78b48c.png)

**Comment by junlincc** [comment]
omg i remember i filed this ticket but couldn't find it so i thought it was lost in a draft....... but you actually closely with a fix.!! @kgabryje you are amazing!
