### ISSUE TITLE
Error on docker compose up

### ISSUE THREAD

**Issue by arnadidenanda** [apache/superset#16352]
i got an error while installing superset via docker, here is the error message :

`{"errors": [{"message": "(psycopg2.errors.UndefinedTable) relation \"ab_permission_view_role\" does not exist\nLINE 2: FROM ab_permission_view JOIN ab_permission_view_role ON ab_p...\n                                     ^\n\n[SQL: SELECT ab_permission_view.id AS ab_permission_view_id, ab_permission_view.permission_id AS ab_permission_view_permission_id, ab_permission_view.view_menu_id AS ab_permission_view_view_menu_id \nFROM ab_permission_view JOIN ab_permission_view_role ON ab_permission_view.id = ab_permission_view_role.permission_view_id JOIN ab_role ON ab_role.id = ab_permission_view_role.role_id JOIN ab_permission ON ab_permission.id = ab_permission_view.permission_id JOIN ab_view_menu ON ab_view_menu.id = ab_permission_view.view_menu_id \nWHERE ab_permission.name = %(name_1)s AND ab_role.id IN (%(id_1)s)]\n[parameters: {'name_1': 'menu_access', 'id_1': 2}]\n(Background on this error at: http://sqlalche.me/e/13/f405)", "error_type": "GENERIC_BACKEND_ERROR", "level": "error", "extra": {"issue_codes": [{"code": 1011, "message": "Issue 1011 - Superset encountered an unexpected error."}]}}]}`

**Comment by srinify** [comment]
Hey @arnadidenanda this is frustrating but unlikely to be a bug with Superset. I've run into issues like this when I have an older version of Superset that I started via docker compose, and then I update the code, and then try to do docker-compose up afterwards.

This error is almost surely a database migration issue that happened between Superset updates. You have a few options:

1. Back up the metadata database for Superset and then delete all of the Docker volumes (https://www.digitalocean.com/community/tutorials/how-to-remove-docker-images-containers-and-volumes) and then when you do `docker-compose up` it'll start from a clean slate.

2. You could try running a manual db migration a la `superset db upgrade`. While docker compose is running, you can fire up the shell for the superset_app container and then run the command there.

**Comment by butching** [comment]
2. You could try running a manual db migration a la `superset db upgrade`. While docker compose is running, you can fire up the shell for the superset_app container and then run the command there. -- how do you do this?
