### ISSUE TITLE
[dashboard][cosmetic]undo and redo buttons weird alignment 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#16365]
1. I'm not sure where else in the product is using these unicorns, the purpose of these icons seem unclear to me. and they are not even centered. 🤦🏾‍♀️

https://user-images.githubusercontent.com/67837651/130163663-ae995c1f-1454-49eb-8a33-2db5bc6cdbed.mov

we could consider go straight to implement new design in sip 34, or simply center the icon for now. low priority.

**Comment by junlincc** [comment]
@maxhui wanna try fixing this one?

**Comment by MaxHuiYYDS** [comment]
![image](https://user-images.githubusercontent.com/51693396/130310468-a67d2881-35ba-481a-a7cd-b5c1d3bedfe5.png)
I found without the :first-of-type css, then it turns out correct, I may still need to check where this css being used, and try to decoupled them.
