### ISSUE TITLE
[Time-series table]make chart sort edit sticky and carry sort order to dashboard 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#16363]
I currently can click the sort icons to sort columns value alphabetically or numerically in the time-series table. The problems are
1) the sort result is not sticky on refresh 
2) sort result is not being carried to the dashboard 

short term solution is to make them sticky  p1
long term is to add sort-by metric control to the time-series table p2
We should get to both done in one PR or separately. 

https://user-images.githubusercontent.com/67837651/130152388-ef45b1a9-9ca6-4ad8-b7d9-f991dc13db6d.mov

one more request, can we remove the blue + button for Time-series columns?

**Comment by zhaoyongjie** [comment]
Hi @junlincc, “the sort results are not sticky on refresh” exists in all table-like viz. currently, Time-series viz is a legacy chart, and used deprecated API to process the transformation of data. I think that the sorting can be handled in post-processing with the new API(sort operator). Could we do the migration for this chart and resolve this issue?

@villebro What do your think about this issue?

**Comment by junlincc** [comment]
> Could we do the migration for this chart and resolve this issue?

is it risky? how long will it take?

**Comment by rusackas** [comment]
Closing since this feature is not currently planned. If anyone is still clamoring for it, we can open an Ideas thread, catalog the viz that it pertains to, and start working on a proposal to address this systematically. Thanks!
