### ISSUE TITLE
Dataset Offset Works only for some charts

### ISSUE THREAD

**Issue by manb911** [apache/superset#16370]
So when we use the Time-series bar chart in an Hourly manner, the data does shift towards the current timezone. Once we move to Day intervals, it doesn't seem to aggregate with the offset.

![image](https://user-images.githubusercontent.com/15208978/130218847-46af46b7-32ac-4e5b-a7bf-a19e0f12d384.png)

So if you look, with the offset, the "Traffic This Week" the latest day should been an aggregate equal to the chart above until the "20" mark which marks the "Midnight" of the day.
This is from Docker with Superset version 1.0

**Comment by rusackas** [comment]
Closing this as inactive, but if anyone is still encountering this in 2.1.0, and can provide a reproducible test case, we're happy to re-open it! Thanks!
