### ISSUE TITLE
Treemap v2 not showing on Chart Explorer

### ISSUE THREAD

**Issue by afrihar** [apache/superset#16385]
Hi,
Why Treemap v2 not showing on Chart Explorer.

### Expected results

I need to use Treemap v2

### Actual results

Treemap v2 not showing on Chart Explorer

#### Screenshots

<img width="1007" alt="Screen Shot 2021-08-20 at 23 24 34" src="https://user-images.githubusercontent.com/2375613/130299909-2d70ec91-a16e-4511-84e2-4c596a340e44.png">

#### How to reproduce the bug

1. Go to *Visualization Type*
2. Search on *Select a Visualization Type*
3. Type  'Treemap v2'

### Environment

- superset version: 1.2.0
- python version: 3.8.10

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [v] I have reproduced the issue with at least the latest released version of superset.
- [v] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
treemap v2 didn't make it to 1.2 i believe. it's safe to get on 1.3 with new treemap and new gallery modal even it's not officially released yet. closing issue for now.
