### ISSUE TITLE
[gauge] displaying field name instead of label

### ISSUE THREAD

**Issue by kevinhodes** [apache/superset#16387]
Gauge char displaying field name instead of label

### Expected results
In the images attached, it should say Año (year), instead it says ano (asshole literally)

### Actual results

what actually happens.

#### Screenshots

* Definition of the columns
![columns](https://user-images.githubusercontent.com/89279983/130298405-856c6c39-0731-4ae8-85d9-48466285eb94.jpg)
* Gauge char displaying the work word.
![resultado](https://user-images.githubusercontent.com/89279983/130298570-15a79518-e5ad-403c-962a-01d81cc1a465.jpg)

### Environment

(please complete the following information):

- superset version: `0.999.0dev`
- github image: '2db7d9c927ca'

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
😂 is it only happening to gauge? or other charts as well (?)

**Comment by kevinhodes** [comment]
I've only seen it in gauge

**Comment by rusackas** [comment]
Is this still an issue in 2.0.1? Hoping to validate this, as some changes were made to that chart.

**Comment by rusackas** [comment]
Looks like this should've been closed by the linked PR.
