### ISSUE TITLE
[explore][save as ] rename a chart in explore and do 'save as' also change the name of original chart

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16403]
Rename a chart in explore and do 'save as' also change the name of original chart

### Expected results

When save as, will save as a new chart with name change, original chart did not change

### Actual results

When do save as, original chart also change for new the chart name

#### Screenshots

https://user-images.githubusercontent.com/81597121/130482129-a1570b7d-1b80-482b-a65d-28be34ce7e12.mov

#### How to reproduce the bug

1. open a chart in explore
2. change name and save as a new chart
3. go to chart list and observe the new chart name

### Environment

(please complete the following information):

- superset version: lastest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@geido if this seems to be an easy fix, let's prioritize it 🙏 thank you, Diego and Jinghua! @jinghua-qa

**Comment by geido** [comment]
@jinghua-qa @junlincc I might be missing the point but I don't see any bug in the flow that you are presenting.
First, you changed the name of the current chart by editing its properties. Then you went to save it again, but this time saving it as a new chart. However, you already changed the name while editing the properties, that is why the names of the original and new chart are now the same.

To show you what I mean, I recorded the following flow where I first edit the name by editing the properties of the original chart, then I change the name again and save it as a new chart. As you will see, the behavior works as expected.

https://user-images.githubusercontent.com/60598000/130594661-af0433e5-e171-4cdc-bf75-2e84208e846b.mp4

**Comment by junlincc** [comment]
sorry the issue title was not clear. 

expected behavior: if user change name from the edit properties modal, and click save to exit the modal, and click save as in Explore, original chart's name should be changed. 
if name change happens in the Save chart modal, the original chart's name should stay the same.
