### ISSUE TITLE
LDAP not working with superset

### ISSUE THREAD

**Issue by mandeeplohan** [apache/superset#16402]
[ldaplogin.txt](https://github.com/apache/superset/files/7033336/ldaplogin.txt)

We are trying to setup ldap login. We configured below in superset_config.py:

from flask_appbuilder.security.manager import AUTH_OID, AUTH_REMOTE_USER, AUTH_DB, AUTH_LDAP, AUTH_OAUTH, AUTH_OAUTH
from mysecurity import MySecurityManager
CUSTOM_SECURITY_MANAGER = MySecurityManager

AUTH_TYPE = AUTH_LDAP
AUTH_LDAP_USE_TLS = False
AUTH_USER_REGISTRATION = True
AUTH_LDAP_SERVER = "ldap-server"
AUTH_LDAP_SEARCH ="CN=Users,DC=ms,DC=xxx,DC=xxx,DC=com"
AUTH_LDAP_UID_FIELD = "sAMAccountName"
AUTH_LDAP_EMAIL_FIELD = "@xxx.com"
#RECAPTCHA_PUBLIC_KEY = "public"

#AUTH_ROLES_MAPPING = {​​​
#"cn=fab_users,ou=groupname,dc=ms,dc=com": ["User"],
#"cn=fab_admins,ou=groupname,dc=ms,dc=com": ["Admin"]
#}

#from superset.security import CustomSecurityManager
#CUSTOM_SECURITY_MANAGER = CustomSecurityManager

# the LDAP user attribute which has their role DNs
AUTH_LDAP_GROUP_FIELD = "memberOf"

# if we should replace ALL the user's roles each login, or only on registration
AUTH_ROLES_SYNC_AT_LOGIN = True

# force users to re-auth after 30min of inactivity (to keep roles in sync)
#PERMANENT_SESSION_LIFETIME=1800​​​

**********With above config we are not able to login.******

[ldaplogin.txt](https://github.com/apache/superset/files/7033341/ldaplogin.txt)
2. Then we tried to provide a custom pythong script ldaplogin.txt (attached along). With that we are able to authenticate user and get ldap related user details. However there  is this below error:

superset_app            | attribute 'is_active' not found
superset_app            | Traceback (most recent call last):
superset_app            |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
superset_app            |     rv = self.dispatch_request()
superset_app            |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
superset_app            |     return self.view_functions[rule.endpoint](**req.view_args)
superset_app            |   File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/security/views.py", line 520, in login
superset_app            |     login_user(user, remember=False)
superset_app            |   File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 158, in login_user
superset_app            |     if not force and not user.is_active:
superset_app            |   File "/usr/local/lib/python3.7/site-packages/ldap3/abstract/entry.py", line 202, in __getattr__
superset_app            |     raise LDAPCursorAttributeError(error_message)
superset_app            | ldap3.core.exceptions.LDAPCursorAttributeError: attribute 'is_active' not found
superset_app            | 2021-08-23 16:04:08,958:ERROR:superset.views.base:attribute 'is_active' not found
superset_app            | Traceback (most recent call last):
superset_app            |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
superset_app            |     rv = self.dispatch_request()
superset_app            |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
superset_app            |     return self.view_functions[rule.endpoint](**req.view_args)
superset_app            |   File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/security/views.py", line 520, in login
superset_app            |     login_user(user, remember=False)
superset_app            |   File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 158, in login_user
superset_app            |     if not force and not user.is_active:
superset_app            |   File "/usr/local/lib/python3.7/site-packages/ldap3/abstract/entry.py", line 202, in __getattr__
superset_app            |     raise LDAPCursorAttributeError(error_message)
superset_app            | ldap3.core.exceptions.LDAPCursorAttributeError: attribute 'is_active' not found
superset_app            | 

We are not able to resolve this. Please help

**Comment by mandeeplohan** [comment]
Hi Team, Any help here? Please

**Comment by dpgaspar** [comment]
Hi @mandeeplohan, from my understanding your overriding FAB ldap Auth, can you:
- Offer a detailed explanation of what your trying to achieve with the override
- If without the override LDAP auth works

**Comment by Hermain** [comment]
In my case it helped to set: AUTH_TYPE = 2

However I am now stuck because the python_ldap is not intalled in the docker container and installing it fails due to missing dependencies from the system.

**Comment by mandeeplohan** [comment]
@Hermain I tried AUTH_TYPE = 2 as well. However, no luck. Strange thing is i am not getting error in the logs. On the login screen only it says invalid. Even admin:admin wont work after enabling ldap configs.

**Comment by mandeeplohan** [comment]
@dpgaspar any help here?

**Comment by metalshanked** [comment]
facing the same issue after upgrading to 1.4.1 from 1.3.1. LDAP was working perfectly on 1.3.1

**Comment by rusackas** [comment]
> did anybody find a solution to fix this? I'm having the same issues trying to setup ldap authentication

I was actually just going to check to see if anyone is still encountering this. I was going to consider closing it since it sounded more like a configuration problem than a bug. Also, the bug was filed quite a few versions of Superset ago, so I'd hoped it wasn't relevant anymore. But... alas, here we are. 

@88fingerslukee are you experiencing this issue on modern Superset (e.g. 2.0.1 or `master`)? 

I don't think we can support custom security managers here, for the record. That'd be more of a topic for the `#customizing-superset" channel on Slack, or a Q&A Discussion here on the repo. If this is a _bug_ with Superset itself, I'm happy to leave it open, but otherwise tempted to close. Thoughts, anyone?

**Comment by 88fingerslukee** [comment]
I actually ended up solving this. I had to docker exec into the image and install all the python-ldap dependencies using aptitude before it would start working. There's obviously a better way through a docker file to do this but it would be nice if the docker image just built with ldap by default.

**Comment by apyshonkin** [comment]
> > did anybody find a solution to fix this? I'm having the same issues trying to setup ldap authentication
> 
> I was actually just going to check to see if anyone is still encountering this. I was going to consider closing it since it sounded more like a configuration problem than a bug. Also, the bug was filed quite a few versions of Superset ago, so I'd hoped it wasn't relevant anymore. But... alas, here we are.
> 
> @88fingerslukee are you experiencing this issue on modern Superset (e.g. 2.0.1 or `master`)?
> 
> I don't think we can support custom security managers here, for the record. That'd be more of a topic for the `#customizing-superset" channel on Slack, or a Q&A Discussion here on the repo. If this is a _bug_ with Superset itself, I'm happy to leave it open, but otherwise tempted to close. Thoughts, anyone?

Yes, I'm still experiencing the exact same issue on superset 2.1.0.

**Comment by 88fingerslukee** [comment]
> > > did anybody find a solution to fix this? I'm having the same issues trying to setup ldap authentication
> > 
> > 
> > I was actually just going to check to see if anyone is still encountering this. I was going to consider closing it since it sounded more like a configuration problem than a bug. Also, the bug was filed quite a few versions of Superset ago, so I'd hoped it wasn't relevant anymore. But... alas, here we are.
> > @88fingerslukee are you experiencing this issue on modern Superset (e.g. 2.0.1 or `master`)?
> > I don't think we can support custom security managers here, for the record. That'd be more of a topic for the `#customizing-superset" channel on Slack, or a Q&A Discussion here on the repo. If this is a _bug_ with Superset itself, I'm happy to leave it open, but otherwise tempted to close. Thoughts, anyone?
> 
> Yes, I'm experiencing the exact same issue on superset 2.1.0.

See https://github.com/apache/superset/issues/23090 to find out how to add a file to make this happen at build time

**Comment by rusackas** [comment]
Thanks for the insight @88fingerslukee - I've added that link to our Documentation backlog. If you'd ever like to participate in this realm, hit us up in the `#documentation` channel on [slack](http://bit.ly/join-superset-slack).

Meanwhile, this seems like a solved problem, so I'll close it out.
