### ISSUE TITLE
[dashboard edit] when user save dashboard change and direct to other link, click go back and not able to see saved changes

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16426]
when user save dashboard change and direct to other link, then user click 'go back' button and not able to see saved changes. User need to go to dashboard link and re-enter the dashboard again to see changes.

### Expected results

after save dashboard, user will be able to see save changes when click go back button from other link

### Actual results

after save dashboard, user not able to see save changes when click go back button from other link

#### Screenshots

https://user-images.githubusercontent.com/81597121/130666629-bc950073-7196-4004-8909-e6da0741e957.mov

#### How to reproduce the bug

1. Go to dashboard edit and add a chart and add markdown
2. save the changes and click the outside link on markdown
3. direct to other pages and click go back button

### Environment

(please complete the following information):

- superset version: master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@MaxHuiYYDS 🙏 good first issue, not urgent :)

**Comment by rusackas** [comment]
Seems half resolved. When you go back, your stuff is there. That's a win.

It's still actually a little weird, though, because when you go back, you're in edit mode. You saved it, so I would expect that navigating back would bring you to the saved dashboard (not in edit mode).

I'll close this and open a fresh issue.
