### ISSUE TITLE
[bar chart] do not show value individually when select stacked bar

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16427]
For bar chart, bar value currently only show 'total value' when it is stacked,  individual value is not shown. Can we also show individual value when it is stacked? Especially when Y Axis is in %, individual bar value for stacked bar will be more meaningful.

When it is not stacked, individual bar value is shown:
<img width="1495" alt="Screen Shot 2021-08-24 at 11 11 52 AM" src="https://user-images.githubusercontent.com/81597121/130668733-e2609d30-2986-43e0-bdfb-ca6a9a4b10f8.png">

When it is stacked, only show bar value for total:
<img width="1494" alt="Screen Shot 2021-08-24 at 11 12 06 AM" src="https://user-images.githubusercontent.com/81597121/130668741-cca62321-8bb6-4656-b4ff-e17d13e6c571.png">

**Comment by junlincc** [comment]
will not fix this nvd3 bar chart. 
@stephenLYZ has resolved similar issue for echarts time bar. https://github.com/apache-superset/superset-ui/pull/1313
and we dont have a non-categorical bar echarts yet. so let's punt.
