### ISSUE TITLE
superset-websocket Error

### ISSUE THREAD

**Issue by j0narch3r** [apache/superset#16432]
### Expected results

Running `docker-compose up` on a clean clone of Superset will launch the app

### Actual results

- I need to register the Snowflake driver for my use case which appears to require `docker-compose up` after adding the snowflake sqlalchemy driver to ./requirements-local.txt

- Superset will run when using docker-compose-non-dev.yml as described <a href="https://superset.apache.org/docs/installation/installing-superset-using-docker-compose">here</a>  but not when running `docker-compose up`. 

- Instead what happens is I get `superset-websocket Error` (see screenshot) which leads to other errors and eventual failure

- This is also on a fresh install of Docker for Mac

#### Screenshots

![image](https://user-images.githubusercontent.com/1578205/130688017-dc7c5a40-b8a0-4b55-8d3c-bc07c647ee5c.png)

#### How to reproduce the bug

1. Install Docker for Mac
2. Follow instructions <a href="https://superset.apache.org/docs/installation/installing-superset-using-docker-compose">here</a>
3. Run `docker-compose up`

### Environment

(please complete the following information):

- superset version: `superset version` -bash: superset: command not found (but I cloned it two days ago)
- python version: `python --version` Python 3.7.4
- node.js version: `node -v` v16.7.0
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by nytai** [comment]
You shouldn't need the superset-websocket service unless you plan to configure global async queries. You can probably just comment that out in your docker-compose file. Looks like your error is related to being able to reach the npm registry from your computer.

**Comment by j0narch3r** [comment]
@nytai Ok good to know. I can try commenting that out. I have no problem installing from npm in general, and EAI_AGAIN at the end apparently suggests a network issue. Do you have any advice for reaching the npm registry from within docker? I ran through suggested steps here for a similar sounding case, but no luck so far:

https://github.com/moby/moby/issues/32106

**Comment by rusackas** [comment]
Closing this as stale, but @j0narch3r  if you are still facing any issues here, we'll be happy to re-open it.

**Comment by IlhomJumayevUrish** [comment]
Hello, I don't fix this bug on last version branch master
please help me 
 => ERROR [superset-websocket build 4/4] RUN npm ci &&   npm run build                         6.0s
------
 > [superset-websocket build 4/4] RUN npm ci &&   npm run build:

**Comment by IlhomJumayevUrish** [comment]
![Uploading photo_2024-01-06_16-11-07.jpg…]()

**Comment by IlhomJumayevUrish** [comment]
![photo_2024-01-06_16-11-07](https://github.com/apache/superset/assets/79079612/3a77b372-09f0-4d5c-bb7c-17563955734a)

**Comment by IlhomJumayevUrish** [comment]
Hi help me

**Comment by l3v1k** [comment]
@IlhomJumayevUrish i was able to run compose by changing `superset-websocket/Dockerfile`, replacing lines to explicitly use node arm64 version 
```
FROM arm64v8/node:16-alpine as build
...
FROM arm64v8/node:16-alpine
```
