### ISSUE TITLE
[dataset] change column to be 'Is temporal' is not working with time grain

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16430]
Change column to be 'Is temporal' under 'COLUMNS' in dataset edit is not working with time grain, but same column added in 'Calculated Columns' with SQL Expression ::TIMESTAMP can work. I think select is temporal should work the same as added calculated column as timestamp?

### Expected results

select column 'Is temporal' for a text column to be temporal column can work with time grain

### Actual results

select 'Is temporal' is not work with time grain, but add as calculated column with SQL Expression ::TIMESTAMP work

#### Select column to be 'Is temporal' did not work with time grain
<img width="1792" alt="Screen Shot 2021-08-23 at 3 39 52 PM" src="https://user-images.githubusercontent.com/81597121/130671927-6fa66691-44f7-4571-bc1a-d84f7df649d6.png">
<img width="1792" alt="Screen Shot 2021-08-23 at 3 40 51 PM" src="https://user-images.githubusercontent.com/81597121/130671936-ec103268-2be8-48f4-9cd9-7d92e7ffa323.png">

#### add the same column to calculated column with SQL Expression will work with time grain
<img width="1792" alt="Screen Shot 2021-08-23 at 3 49 48 PM" src="https://user-images.githubusercontent.com/81597121/130671941-b02f124d-a9f7-427a-a285-954cfbc79f55.png">
<img width="1792" alt="Screen Shot 2021-08-23 at 3 49 58 PM" src="https://user-images.githubusercontent.com/81597121/130671945-7ed13595-d4c0-47a4-be96-4b3f44d84b82.png">

#### How to reproduce the bug
use dataset FCC 2018 survey
1. in dataset edit, select 'Is temporal' for time_end column
2. create a time-series chart and select time grain
3. error will shown
4. add time_end in calculated column and add SQL Expression time_end::TIMESTAMP
5. create time series chart again and this time chart will work

### Environment

(please complete the following information):

- superset version: master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
@jinghua-qa is this still valid in current Superset, or was this resolved somewhere along the way?

**Comment by geido** [comment]
Hello @jinghua-qa thanks for reporting this issue. I tested on the most recent version of Superset and could not repro. I am closing this for now.
