### ISSUE TITLE
The table wants to add some optimizations

### ISSUE THREAD

**Issue by panqingdian** [apache/superset#16435]
There is a problem when using form drawing, when the interview on words in the table, this time if the word too much can cause table height is different, hope there is a place to set, when the word too much can only show the front part of the text, ellipses instead of the rest of the text, can click on the need to look at the details, will appear in full. It is very urgent to have this feature.
think you !

![Uploading image.png…]()

**Comment by srinify** [comment]
Hi @panqingdian FYI we can't see the image you uploaded, can you try again!

**Comment by rusackas** [comment]
I believe these text truncation issues were resolved quite some time ago, which is probably why this issue has been quiet for so long. I'll optimistically close this Issue as resolved, but if you see this again, we can re-open the issue in hopes of someone can add truncation/tooltips where necessary.
