### ISSUE TITLE
[dashboard] chart reload forever if delete attached dataset

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16431]
if you delete a dataset that has charts attached to them, they reload forever in the dashboard

### Expected results

chart did not reload forever if attached dataset deleted

### Actual results

chart  reload forever if attached dataset deleted

#### Screenshots

<img width="1792" alt="Screen Shot 2021-08-24 at 12 14 34 PM" src="https://user-images.githubusercontent.com/81597121/130676566-94e30d06-f4a7-4da3-a44f-23b5f42f97d9.png">

#### How to reproduce the bug

1. delete a dataset attached to the chart
2. go to dashboard with this chart
3. See error for reloading the chart forever

### Environment

(please complete the following information):

- superset version: master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
expected behavior : it works properly in Explore, with a a clear error message on the control panel. we can reuse that one
