### ISSUE TITLE
Issue adding chart to dashboard in version 1.3

### ISSUE THREAD

**Issue by stevensuting** [apache/superset#16436]
In version 1.3 when adding a chart to a dashboard via dashboard edit mode, it throws an error in an arbitrary fashion. So cannot share exact steps to recreate the issue.
<img width="400" alt="Add chart to dashbaord" src="https://user-images.githubusercontent.com/8875448/130743298-6acbd473-ca28-4e73-9695-0be262d4882e.png">

### Stacktrace
`Traceback (most recent call last):`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/superset/views/base.py", line 204, in wraps
    return f(self, *args, **kwargs)`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/superset/utils/log.py", line 241, in wrapper
    value = f(*args, **kwargs)`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/superset/utils/cache.py", line 167, in wrapper
    return f(*args, **kwargs)`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/superset/views/utils.py", line 472, in wrapper
    return f(*args, **kwargs)`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/superset/views/core.py", line 664, in explore_json
    return self.generate_json(viz_obj, response_type)`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/superset/views/core.py", line 462, in generate_json
    payload = viz_obj.get_payload()`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/superset/viz.py", line 455, in get_payload
    payload["data"] = self.get_data(df)`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/superset/viz.py", line 936, in get_data
    df = df.stack(0).unstack().reindex(level=-1, columns=metrics)`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/pandas/util/_decorators.py", line 312, in wrapper
    return func(*args, **kwargs)`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/pandas/core/frame.py", line 4176, in reindex
    return super().reindex(**kwargs)`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/pandas/core/generic.py", line 4811, in reindex
    return self._reindex_axes(`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/pandas/core/frame.py", line 4016, in _reindex_axes
    frame = frame._reindex_columns(`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/pandas/core/frame.py", line 4058, in _reindex_columns
    new_columns, indexer = self.columns.reindex(`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3509, in reindex
    _, indexer, _ = self._join_level(`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3880, in _join_level
    assert isinstance(left, MultiIndex)`
`AssertionError`
`2021-08-24 07:31:36,933:ERROR:superset.views.base:`

### Environment
- superset version: `1.3`
- python version: `3.9`
- pip install method

cc: @villebro

**Comment by villebro** [comment]
I have unfortunately not been able to reproduce this bug. Is someone else seeing this bug?

**Comment by PowerPlop** [comment]
I just experienced this bug on a preset instance. Was randomly drag and dropping dashboard components. Seemed to occur when I used a combination of tabs and markdown components.
