### ISSUE TITLE
[dragndrop] Feature request: Clarify drop and replace for single metric control

### ISSUE THREAD

**Issue by michellethomas** [apache/superset#16476]
**Is your feature request related to a problem? Please describe.**
The UX for drop and replace single-select metric is confusing. With a single metric, dragging a new metric in replaces the existing metric. There is no clear indication that some Metric input only accepts one metric.

**Describe the solution you'd like**
Clarify the drop and replace behavior for the single select metric.

**Additional context**
Feature request originally mentioned [here](https://github.com/apache/superset/pull/16362#issuecomment-902179092)

**Comment by ShaliniIruvuru** [comment]
Working fine. The feature is already added.

1.If we want to add multiple metrics.so we have an option under the metric Drop columns/metrics here or click.

Screenshot
![image](https://user-images.githubusercontent.com/115684419/225626648-613fb67b-9b07-49d9-acc6-44600636e1b8.png)

2.When we have a single metric , so we don’t have an extra  option to add metric.
![image](https://user-images.githubusercontent.com/115684419/225626742-d17dbcda-8871-49e9-ade4-f40fee01c6f5.png)



Screenshot:-
