### ISSUE TITLE
[chart viz][table]  different types of columns align differently in chart viz

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16481]
In table,  metric column and # column has right alignment while other type of column has left alignment, should we have the same alignment for all different columns?

### Expected results

all column has same alignment in table

### Actual results

# column has center alignment and others have left

#### Screenshots

<img width="1789" alt="Screen Shot 2021-08-27 at 12 57 22 AM" src="https://user-images.githubusercontent.com/81597121/131093456-2d75fcf5-67fd-4c22-b7c1-c1745290e625.png">

<img width="1787" alt="Screen Shot 2021-08-27 at 12 24 00 AM" src="https://user-images.githubusercontent.com/81597121/131092829-c6555bb4-4e54-4cc1-b97e-888e16df6ed6.png">

#### How to reproduce the bug

1. Go to table chart , select different type of column in raw 
2. Click on run and observe the table chart
3. See error

### Environment

(please complete the following information):

- superset version: latest master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
I see there's a PR open to resolve this... I'll add some thoughts and reach out for opinions there.

**Comment by rusackas** [comment]
Closing this issue since it was discussed among some contributors that the current behavior is 
• the more desirable state (left-aligned text, right-aligned numbers for easier comparison)
• overridable via existing chart controls under "customize"

If anyone finds this controversial (particularly @jinghua-qa) then we can re-visit this, possibly taking the discussion to the mailing list or another venue for a wider audience.
