### ISSUE TITLE
Superset CSV upload Create table is executed before `Drop` table completes with Trino

### ISSUE THREAD

**Issue by rijojoseph07** [apache/superset#16480]
When trying to upload a CSV to Trino with Replace option, getting `table already exist` error on create table query execution. Upon checking found that the create table query started executing before the drop table query completed. 

### Expected results

Create table query to execute after the drop table query is executed. 

### Actual results

Create table is failing with `Table already Exist` since it is called before DROP completes. Verified by checking end time of drop query and start time of create query

#### Screenshots
<img width="1440" alt="Screen Shot 2021-08-27 at 12 25 40 PM" src="https://user-images.githubusercontent.com/22840697/131085409-c07dc55a-99a0-453e-997f-a763c92a8453.png">

#### How to reproduce the bug

- Upload CSV
- Choose Replace (make sure table already exist)
- Save

### Environment

(please complete the following information):

- superset version: 1.2
- python version: `3.7`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
@rijojoseph07 are you still facing this, did you find a solution, or did you just move on? Tempted to close this as stale, but it sounds like it might need more attention?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
