### ISSUE TITLE
[save][explore] highlight of save button when there is unsaved change

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16484]
Currently, when we do some edit in explore, like change chart type, adding filter etc, the Save button did not highlight to remind user there is unsaved changes, can we add that to be more user friendly? Also will be helpful if there is a reminder msg for unsaved changes when user try to leave the page

https://user-images.githubusercontent.com/81597121/131170274-3e2879aa-1b5f-461b-952d-8b752607a223.mov

**Comment by rusackas** [comment]
This should no longer be an issue, these controls have been revamped.
