### ISSUE TITLE
Cannot enables Alert & Report feature

### ISSUE THREAD

**Issue by caoquyvu** [apache/superset#16497]
Cannot get the right url of Alert & Report feature

### Expected results

Expected get the screen of Alert & Report feature

### Actual results

![ảnh](https://user-images.githubusercontent.com/19485589/131327256-65d06a0a-0b49-4c53-b651-4bfef2d8f217.png)

![ảnh](https://user-images.githubusercontent.com/19485589/131327139-0d3e38d6-71ad-4227-ba9a-a8561761bd8f.png)

### Environment

(please complete the following information):

- superset version: 1.3.0
- python version: Python 3.7.10
- node.js version: v8.10.0
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x ] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by betodealmeida** [comment]
@caoquyvu how did you enable it? Can you share your `superset_config.py`?

**Comment by rusackas** [comment]
Closing due to a lack of follow-up from the original poster for over a year.
