### ISSUE TITLE
Trino connector  - Prepare statement and session settings are not working 

### ISSUE THREAD

**Issue by rijojoseph07** [apache/superset#16494]
Prepared statements are failing with the `Prepared statement not found` exception in trino. Also, session properties are not propagated to the queries executed. 

Looks like both the issues are caused by the connector creating new connections for every query execution and hence prepared statements or session properties set in the previous session are lost.

### Expected results

Test 1 : 
```
PREPARE test FROM /* ping */ Select 1;
EXECUTE test;
```
Expect to print 1

Test 2

SET SESSION optimize_hash_generation = true;
Select 1;

Expect session properties to be applied for the second query. 

### Actual results

Test 1: Gets `Prepared statement not found` exception. 
Test 2: Not session property visible for the second query in trino UI

what actually happens.

#### How to reproduce the bug

1. Go to 'SQL Editor'
2. Run the following queries

```
PREPARE test FROM /* ping */ Select 1;
EXECUTE test;
```
3. Will create a Prepared statement not found. 
4. 
### Environment

(please complete the following information):

- superset version: `1.2`
- python version: `3.7`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
This is an old/inactive issue on an old/unsupported verison of Superset. That said, I'd understand if this is still totally legit! If you're still seeing this issue in Superset 2.0.1, I'm more than happy to re-open it, and would appreciate updated context on the original post or in the thread. Thanks!
