### ISSUE TITLE
500 Error in listing report schedule because of cron expression descriptor

### ISSUE THREAD

**Issue by anilvpatel21** [apache/superset#16495]
A cron expression with "7" as sunday is accepted while creating a report using an API. But its unable to read "7" as sunday using cron_descriptor, and throwing 500 internal server error. 

### Expected results

It should read 0 or 7 as Sunday. 

### Actual results

Unable to read 7 as Sunday. 

#### How to reproduce the bug

1. Edit any existing alert with new crontab expression using an API endpoints. 
put request to /api/v1/report/{pk}
```
{
  crontab: "* * * * 7"
}
```
 It will be successful. 
2. Now go to 'Report & Alert' section, you won't be able to see the list of alerts & report. 
3. In the backend, it has this error
```
line 147, in get_full_description
    raise FormatException(description)
cron_descriptor.Exception.FormatException: An error occured when generating the expression description.  Check the cron expression syntax.
```

### Environment
- superset version: Superset 1.1.0
- python version: Python 3.7.10
- node.js version: v12.16.1
- any feature flags active:
```
DEFAULT_FEATURE_FLAGS = {
     'ALERT_REPORTS': True,
}
```
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- 
- [ yes ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ yes ] I have reproduced the issue with at least the latest released version of superset.
- [ yes ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
Need to upgrade the cron-descriptor PYPI package to the latest version. 

Earlier 1.2.24 version does not support 7 as Sunday. Only Supports 5 or 6 (w/ seconds) part cron expressions.

**Comment by anilvpatel21** [comment]
Similar #13392

**Comment by rusackas** [comment]
I'm guessing this has been fixed (similar to speculation on the linked/related issue) so I'll optimistically close this one out, especially since it's been stale for so long. Holler if you're still experiencing this!
