### ISSUE TITLE
Error loading tables from Hive2/SparkSQL

### ISSUE THREAD

**Issue by piffall** [apache/superset#16509]
While adding a _dataset_ from Apache Spark SQL / Hive form incorrectly loads tables on **Add dataset** form. It affects to tables and views. The number of tables + number of views, the number of `default` on **Add dataset**  select box (see screenshot).

In contrast, querying database using SQL Lab is working perfectly (see screenshot).

### Expected results

Add a dataset to Superset.

### Actual results

Cannot add the dataset to Superset. No errors or warnings in logs.

#### Screenshots

![image](https://user-images.githubusercontent.com/1277789/131357294-e6cf635a-029f-482f-a776-22569074f8a7.png)
![image](https://user-images.githubusercontent.com/1277789/131359663-d2a80b6e-6d06-43ab-aa20-e8938ee43db0.png)

#### How to reproduce the bug

1. Add new database
2. Select Apache Spark SQL
3. Enter the SQLAlchemy URI: `hive://x.x.x.x:10000/default` (tested withoud db name also)
4. Click on Connect
5. Go to Datasets and add new dataset
6. Select the new connection
7. Select the Schema
8. Table select will be populated with `default` table names.

### Environment

Running the latest version of `docker-compose-non-dev.yaml`

**Comment by danielewood** [comment]
This should be resolved with the changes I upstreamed to the impyla connector.

try impala:// or ascend://

Both use the impyla driver, the difference is the ascend connection string uses postgres date formats.

```ascend://{username}:{password}@{hostname}:{port}/{database}?auth_mechanism=PLAIN;use_ssl=true```

**Comment by piffall** [comment]
Thanks @danielewood , that worked for me!

**Comment by SKhakhulin** [comment]
when I try same method, I get `ERROR: Could not load database driver: ImpalaEngineSpec`

**Comment by penghuo** [comment]
here is a quick fix in docker image. 

```
# 1. edit docker images
docker run -u root -it apache/superset:latest-dev /bin/bash

# 2. edit phhive in shell
vim /usr/local/lib/python3.8/site-packages/pyhive/sqlalchemy_hive.py

change https://github.com/dropbox/PyHive/blob/master/pyhive/sqlalchemy_hive.py#L364
    def get_table_names(self, connection, schema=None, **kw):
        query = 'SHOW TABLES'
        if schema:
            query += ' IN ' + self.identifier_preparer.quote_identifier(schema)
        return [row[1] for row in connection.execute(query)]
        
change https://github.com/dropbox/PyHive/blob/master/pyhive/sqlalchemy_hive.py#L314
    if col_name == '# Partitioning':        


# 3. in another console, commit the change
docker ps
CONTAINER ID   IMAGE         COMMAND       CREATED              STATUS                          PORTS      NAMES
374249e4ac34   superset   "/bin/bash"   About a minute ago   Up About a minute (unhealthy)   8088/tcp   brave_jang

docker commit 374249e4ac34 superset-test

# 4. replace superset-image in docker-compose-non-dev.yml as superset-test 
```

**Comment by jbguerraz** [comment]
related https://github.com/apache/superset/issues/10940

**Comment by rusackas** [comment]
This issue seems to have largely gone stale. It sounds like there were a couple pending solutions on the thread. Can anoyone confirm or deny whether this issue should remain open?

**Comment by pedrosalgadowork** [comment]
Same here, this is particularly important regarding catalog metadata fetch, currently, we can't use physical references to the tables, only virtual SQL queries, and metadata exploration using the UI is blocked.

**Comment by bkyryliuk** [comment]
Pyhive is not maintained. If anyone is interested in polishing https://github.com/dropbox/PyHive/pull/247 and doing a couple rounds of testing / adding integration test for superset or pyhive - I am happy to review & release a new version

**Comment by rusackas** [comment]
Hi all. It sounds like this is not a Superset issue, per se, and we're no longer supporting Superset 2.x or prior. It's been a while since this thread saw any activity, so I'm closing this as stale. If it is still an issue in Superset 3.x, we can re-open this, or feel free to open a new issue with updated context.
