### ISSUE TITLE
Add custom k8s labels

### ISSUE THREAD

**Issue by cmanzur** [apache/superset#16503]
**Is your feature request related to a problem? Please describe.**
In some logging scenarios, is useful to use proper kubernetes labels to ship logs. The current Helm chart don't have this possibility. 

**Describe the solution you'd like**
Add a podLabels field in values.yml

**Comment by rusackas** [comment]
Closing this since it's gone stale and is more feature request than bug report, but I'd encourage you to take this up on `#kubernetes-deployment` or `#helm-k8-deployment` on [Superset Slack](http://bit.ly/join-superset-slack)
