### ISSUE TITLE
Dashboards and Charts drop a red 'Unexpected error' message when user is anonymous

### ISSUE THREAD

**Issue by trepmag** [apache/superset#16507]
This issue happens when user is anonymous.

### Expected results

List of public dashboards or charts

### Actual results

Red 'Unexpected error' message

#### Screenshots

![Selection_343](https://user-images.githubusercontent.com/875021/131353924-73ad2070-a27a-4bcf-8d84-ff107bed6c9b.png)

#### How to reproduce the bug

1. Add dashbords and charts and set access to public
2. Browse dashboards or charts unconnected (anonymous)
3. See the error as show in the screenshot

### Environment

- superset version: `1.3.0`
- python version: `as distributed in the superset 1.3.0 image`
- node.js version: `as distributed in the superset 1.3.0 image`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

This was tested with the the 1.3 branch using `npm run prod` and `npm run dev-server`

**Comment by mignaulo** [comment]
@trepmag This is a really great find. We also ran into this same issue. Thanks for reporting and fixing it!
I'm not sure how superset deals with external contributions, are you able to submit a PR with your code change?

**Comment by jhult** [comment]
Did the fix for this get merged?
