### ISSUE TITLE
[time_series][feature_parity] no options to add x-axis label in customize panel for new echarts time series

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16512]
Some new charts do not have x-axis tile option in customize panel, can we add that?

https://user-images.githubusercontent.com/81597121/131388308-d2112754-dae0-4c1c-b46d-0a3fe915c06e.mov

- list of charts missing x-axis tile option:
- time series line chart, 
- time series area chart, 
- time series bar chat, 
- time series scatter plot, 
- mix time series, 
- time series chart, 
- time series smooth line, 
- time series stepped line, 
- box plot

For the old charts, current filed name call 'x-axis label' and in new charts field, axis label is referred to the label on each point on the axis, maybe we should just rename those filed to be axis title?

old charts with field name 'x-axis label' or 'y-axis label' currently:
- area chart, 
- bar chart ,
- bubble chart, 
- histogram, 
- line chart, 
- time-series percent change, 
- time series period pivot

**Comment by junlincc** [comment]
@MaxHuiYYDS would you like to work on this one? 

 cc @stephenLYZ

**Comment by MaxHuiYYDS** [comment]
> @MaxHuiYYDS would you like to work on this one?
> 
> cc @stephenLYZ

OK, I will look at it

**Comment by zhaoyongjie** [comment]
fixed by https://github.com/apache-superset/superset-ui/pull/1351
@junlincc @MaxHuiYYDS @jinghua-qa
