### ISSUE TITLE
Didn't support russian language, getting question mark in place ????

### ISSUE THREAD

**Issue by zeeshan-IH** [apache/superset#16529]
Need everything in Russian, labels as well for that we stored russian in db but its coming as ???(question mark) 
### Expected results

what you expected to happen.
Want Russian data which is stored in the db
### Actual results
???Question mark is coming instead russian data
what actually happens.

#### Screenshots
https://paste.pics/DQ2KM
https://paste.pics/DQ2L7

#### How to reproduce the bug

1. Store any Russian data in the table
2. Click on 'SQL lab'
3. Select SQL Editor
4. Open network tab in your browser.
5. Write a simple select query to get the Russian data from the table you stored russian data.
6. you can see API returning question mark(???) in data key, also in result you can see ????

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by recoshet** [comment]
Set in ADDITIONAL PARAMETERS `charset=utf-8`.
This error occurred to me when connecting to MySQL. Because the default is the wrong encoding for your data in the database.

**Comment by m-ocean-it** [comment]
> Set in ADDITIONAL PARAMETERS `charset=utf-8`. This error occurred to me when connecting to MySQL. Because the default is the wrong encoding for your data in the database.

Hi, @recoshet! What "additional parameters" are you talking about? Where can I set them?

**Comment by m-ocean-it** [comment]
Never mind, found it! It's in the basic settings of the database connection

**Comment by rusackas** [comment]
Assuming this has been resolved thanks to the above input (thanks @recoshet!). Optimistically closing, but willing to re-open if the issue is truly unresolved.
