### ISSUE TITLE
Gunicorn not releasing the memory(RAM) after completing the request

### ISSUE THREAD

**Issue by umesh11111** [apache/superset#16523]
we have deployed our superset application in kubernetes env by using Gunicorn webserver.when application started,default ram utilized size is 500MB,after accessing the superset application, memory got utilized 1.5GB out of 2 GB RAM.
when there is not superset application usages, still memory utilization is same 1.5GB,its not releasing the memory.
RAM will be cleared only if we restarted the superset application(Kubernetes Pod).

### Expected results

Memory should get released after completing the request.
### Actual results

same amount of  memory is getting occupied by the Gunicorn server after completing the request
### Environment

(please complete the following information):

- superset version: 0.36
- python version: 3.7.6
 

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Any help would be appreciated

**Comment by srinify** [comment]
hi @umesh11111 hmm I'm not sure if this is a Superset issue / bug in Superset per say or something with gunicorn / your specific setup.

**Comment by umesh11111** [comment]
Hi @srinify when we deployed our application using gunicorn webserver,we are getting the memory leakage issue.we are also trying to understand where and why its causing the issue.
