### ISSUE TITLE
[native filter] click on native filter indicator did not show highlight effect

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16520]
When clicking on native filter indicator, the corresponding filter on the native filter list should be high light in a blue frame

### Expected results

show highlight effect when clicking on native filter indicator

### Actual results

no highlight effect

#### Screenshots

https://user-images.githubusercontent.com/81597121/131456618-57bbc452-aaf0-4eab-9d7e-64da1470cc0a.mov

#### How to reproduce the bug

1. create native filter, and apply to chart
2. click on the corresponding chart on filter indicator
3. See error

### Environment

(please complete the following information):

- superset version: master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by kgabryje** [comment]
Fixed by https://github.com/apache/superset/pull/18793
