### ISSUE TITLE
DASHBOARD_RBAC feature flag doesn't work

### ISSUE THREAD

**Issue by niclas-grahm-d2v** [apache/superset#16524]
### Short description

I have a fresh install of superset. I have created a dashboard `dashboard1` as well as a role `role1`. Since I have the `DASHBOARD_RBAC` feature flag enabled, I can go into the dashboard settings and add `role1` in the settings -> roles dropdown. 

I have created a new user `user1` and given them the `role1` as well as the `Gamma` role. 

### Expected results

I expect `user1` to be able to access `dashboard1`. 

### Actual results

The user doesn't have access to any dashboards.

### Environment

- superset version: `docker using master branch, commit 90e2f09c6 `

- any feature flags active:
```
FEATURE_FLAGS = {
        "ALERT_REPORTS": True,
        'ENABLE_TEMPLATE_PROCESSING': True,
        'DASHBOARD_RBAC': True,
        'ROW_LEVEL_SECURITY': True,
        'OMNIBAR': True,
        'DASHBOARD_NATIVE_FILTERS_SET': True,
        'DASHBOARD_NATIVE_FILTERS': True,
        'DASHBOARD_CROSS_FILTERS': True,
        "GLOBAL_ASYNC_QUERIES": True
}
```

**Comment by iercan** [comment]
Be sure you published dashboard.

**Comment by niclas-grahm-d2v** [comment]
Ah yes, that worked. Perhaps obvious for everyone else, but not for me :D
