### ISSUE TITLE
[native filter][cascading] Confusing user experience

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#16532]
#### How to reproduce the bug
![i3f8A5SMiW](https://user-images.githubusercontent.com/27990562/131583020-2f48cf34-2a2b-4da3-967b-b746ef0e640c.gif)

1. I created a simple dashboard with cascading filter component: 
- Simple gender filter, 
- Name filter, and State filter (under Name filter)
2. Click on Name filter, there are 2 dropdown list for all Names filter showing up;
3. Pick a name for Name filter, you will see Name filter title became `State filter`, and there are 2 dropdown list for state.
4. If there are 2+ nested filter under same parent filter, the experience is totally chaotic....

**Proposed solution:**

When user created a nested filter component, what's the best way to display dropdown list(s)? Right now we show 1 in the main component list, and also show another copy in the popover with child filter...this is definitely not desirable. Please reconsider the design and implementation. 

How about only remove the popover for the family of drop-downs, just show all in the main filter list, but align them with some indent or box?

### Environment

latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

cc @junlincc @michael-s-molina @villebro

**Comment by michael-s-molina** [comment]
Just linking this [comment](https://github.com/apache/superset/pull/15433#issuecomment-885685647) to add more context to the discussion.

**Comment by graceguo-supercat** [comment]
Hi @michael-s-molina thanks for the link, i am happy to know someone else had same concern as me. But from those merged PRs i couldn't get this problem is kind of _resolved_,  or there will extra work to do to improve? At least, currently showing 2 dropdown controls for the same filter is totally wrong:
<img width="1393" alt="Screen Shot 2021-09-01 at 10 17 49 AM" src="https://user-images.githubusercontent.com/27990562/131715175-6c386d01-1482-413f-8f7b-7bc735d5530d.png">

if it's preferred always show parent filter in the filter bar, i agree, could we not show parent filter in its popover? 
thanks for your feedback. @rusackas @michael-s-molina @villebro @junlincc

**Comment by junlincc** [comment]
@graceguo-supercat i totally agree your sentiment "If there are 2+ nested filter under same parent filter, the experience is totally chaotic...." 

changes made in cascading popover were not well thought through due to the lack of design support. do you mind if i remove the p1 priority for now, and have a design sesh later on?

**Comment by michael-s-molina** [comment]
@graceguo-supercat this problem is not resolved. I just linked that comment to include even more context for when we discuss the solution.

**Comment by graceguo-supercat** [comment]
thank you all for the quick response! I am ok with the priority (not p1). As you know airbnb is also preparing to enable native filter, if we can have an ETA will be the best :grimacing:

**Comment by kgabryje** [comment]
Closing - we've redesigned the filter bar, so the issue os no longer relevant
