### ISSUE TITLE
No Access to dashboard list for Public User in 1.3.0

### ISSUE THREAD

**Issue by lilila** [apache/superset#16547]
I upgraded from 1.3.0rc1 to 1.3.0 and public users do not have access to the list of dashboard anymore. 
If they have the link of a dashboard they can access it but the dashboard list page returns : 

<img width="1150" alt="Screenshot 2021-09-01 at 16 21 22" src="https://user-images.githubusercontent.com/607430/131688291-7bbd3973-bbf4-40cd-bfe1-6e02ddc91444.png">

**Comment by sholtoarmstrong-iot** [comment]
@lilila Any luck resolving this issue? I have a similar issue that I am unable to open a dashboard as a public user.
