### ISSUE TITLE
Support REDIS as datasource

### ISSUE THREAD

**Issue by ohhappy1986** [apache/superset#16551]
We would like superset can read data from REDIS in query and can combine with query from other datasource to build final report query.

In our case we have stores some data in REDIS and some data in SQL server, and we need to build report based on both data.

It could be similar like the link below:
https://www.cdata.com/kb/tech/redis-python-sqlalchemy.rst
https://www.cdata.com/kb/tech/redis-connect-google-data-studio.rst

**Comment by betodealmeida** [comment]
The CData connector is commercial, so we can't really ship a DB engine spec in Superset that depends on it, and it's going to be hard to find developers interested in adding support for it. I tried searching an open source SQAlchemy dialect for Redis, but didn't find anything.

One way to move forward is for you to write your own DB engine spec for Superset, as a separate package, leveraging the CData SQLAlchemy dialect. Your package can define an entry point that enables Superset to find it and use it. If you're interested in doing this I can give more pointers on how to do it.

**Comment by rusackas** [comment]
I'm not sure whether to label this as stale or solved (thanks Beto!), but I'll close it out either way. Thanks all!
