### ISSUE TITLE
[pie_echart]sort to ignore NULL in pie when ROW(series) limit is set 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#16555]
i created pie chart with a row/series limit to visualize the average number of children each age group has, with sort by metric checked by default. when the limit is set to 25, more than half of the rows return NULL, which are not showing as slices( as expected). when i set limit to 10, no data shows, while my expectation was to see the top 10 slices from the non-NULL rows. 

https://user-images.githubusercontent.com/67837651/131741523-fef3fb69-918a-4552-8819-7109b75b3024.mov

@villebro please help delegate 🙏😉

**Comment by zhaoyongjie** [comment]
@junlincc 
Hi, you should add a filter for getting `Top-N` metric.
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/2016594/131849608-cad275f9-2e9d-4a0c-a2d8-e362dd4a626f.png">

**Comment by rusackas** [comment]
Sounds like this was effectively answered, and is also very stale. Closing, but happy to re-open if there's still an issue here. :)
