### ISSUE TITLE
Celery background run fail

### ISSUE THREAD

**Issue by randalee** [apache/superset#16562]
I tried to run celerybeat and celery worker in the background for alarm and report functionality.
I tried using init script with reference to "https://docs.celeryproject.org/en/v4.4.7/userguide/daemonizing.html". However, those scripts that use "multi start" do not use superset app config.

### Expected results
Normal background execution.

### Actual results
**beat**
Alerts are not registered normally.

**worker**
As a result of checking the log, the log accessing ampq instead of the redis.

#### Screenshots
foreground - OK
![image](https://user-images.githubusercontent.com/21075211/131782968-27d4219f-0ea4-4332-a67b-3344d53a103f.png)

backgroud - Fail
![image](https://user-images.githubusercontent.com/21075211/131782998-f80050ff-5d3b-46ee-9b10-a018b817ef31.png)

#### How to reproduce the bug
**foreground**
celery worker --app=superset.tasks.celery_app:app --pool=prefork -O fair -c 4

**background**
celery multi start worker --app=superset.tasks.celery_app:app --pool=prefork -O fair -c 4 --logfile='log'
tail -f log

### Environment

(please complete the following information):
superset 1.3.0
python 3.9.6
celery 4.4.7 (cliffs)

any feature flags & celery setting
```.python
FEATURE_FLAGS = {
    "ENABLE_TEMPLATE_PROCESSING": True,
    "ENABLE_TEMPLATE_REMOVE_FILTERS": True,
    "ALERT_REPORTS": True,
    "DASHBOARD_NATIVE_FILTERS": True,
    "DASHBOARD_CROSS_FILTERS": True,
    "DASHBOARD_NATIVE_FILTERS_SET": True
}

class CeleryConfig(object):
    BROKER_URL = 'redis://localhost:6379/0'
    CELERY_IMPORTS = (
        'superset.sql_lab',
        'superset.tasks',
        'superset.tasks.thumbnails'
    )
    CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
    CELERYD_LOG_LEVEL = 'DEBUG'
    CELERYD_PREFETCH_MULTIPLIER = 10
    CELERY_ACKS_LATE = True
    CELERY_ANNOTATIONS = {
        'sql_lab.get_sql_results': {
            'rate_limit': '100/s',
        },
        'email_reports.send': {
            'rate_limit': '1/s',
            'time_limit': 120,
            'soft_time_limit': 150,
            'ignore_result': True,
        },
    }
    CELERYBEAT_SCHEDULE = {
        'email_reports.schedule_hourly': {
            'task': 'email_reports.schedule_hourly',
            'schedule': crontab(minute=1, hour='*'),
        },
        'reports.scheduler': {
            'task': 'reports.scheduler',
            'schedule': crontab(minute='*', hour='*'),
        },
        'reports.prune_log': {
            'task': 'reports.prune_log',
            'schedule': crontab(minute=0, hour=0),
        },
        'alerts.schedule_check': {
            'task': 'alerts.schedule_check',
            'schedule': crontab(minute='*', hour='*'),
        },
    }

CELERY_CONFIG = CeleryConfig
```

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [v] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [v] I have reproduced the issue with at least the latest released version of superset.
- [v] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
Due to this issue, running the script in the background by configuring it as shown below.

```.bash
source /home/ec2-user/superset/env/bin/activate

nohup celery worker --app=superset.tasks.celery_app:app --pool=prefork -O fair -c 4 --logfile=/home/ec2-user/superset/worker.log --pidfile=/home/ec2-user/superset/worker.pid --loglevel=DEBUG > /dev/null 2>&1 &
nohup celery beat --app=superset.tasks.celery_app:app --logfile=/home/ec2-user/superset/beat.log --pidfile=/home/ec2-user/superset/beat.pid --loglevel=DEBUG > /dev/null 2>&1 &
```

In this case, the reports and alarm functions registered by the superset work normally.

**Comment by rusackas** [comment]
Closing this since it's a configuration issue rather than a bug. Hopefully you've solved this by now one way or another, but if not, please join us on [Superset Slack](http://bit.ly/join-superset-slack)  in `#deploying-superset` since these Celery issues are tackled there often.
