### ISSUE TITLE
Owner report  modifications doesn't work properly.

### ISSUE THREAD

**Issue by stayunique-reporting** [apache/superset#16567]
Renata needs to modify our owner reports according to the owner features 

what you expected to happen.

### Actual results: When we erase an item the pictures and the selection of the rest of the report became a mess

what actually happens.

#### How to reproduce the bug

1. Go to any owner report already created
2. Erase the first item and text will disappears, but not the pictures or the section selected.
3. You will see that next item text will be mixed with the picture of the erased item. And old item section keeps appearing.

### Environment 
- Owner report App
- Owner report item list on admin

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

[](url)https://sustorage.s3.eu-west-1.amazonaws.com/owner_reports/272d6705b13054d3ec5ac9ed1Owner_Report_RamblaCat42-At2B_%28STFM%29_02_09_2021.pdf

**Comment by rusackas** [comment]
I'm not quite understanding exactly what this bug is reporting. 
> Please: compare the Owner's PDF created on Rambla 42 nº 75 and nº 171
I'm not sure what this means...

The issue is nearly two years old, so I'm hoping it's not an issue anymore, and can be closed due to inactivity. If you're still facing this, please provide reproduction steps and screenshots where applicable (preferably using example datasets) so we can better debug the issue. Thanks!
