### ISSUE TITLE
[Authentication]Disable auth from superset

### ISSUE THREAD

**Issue by mjmanas0699** [apache/superset#16575]
I created my own docker image with these changes . 'uncommented   AUTH_ROLE_PUBLIC = 'Public'  but the issue is still there 
it is asking login same as the previous image 

```
### Uncomment to setup Public role name, no authentication needed
AUTH_ROLE_PUBLIC = 'Public'
### AUTH_USER_REGISTRATION_ROLE = "Public"
## Grant public role the same set of permissions as for a selected builtin role.
PUBLIC_ROLE_LIKE: Optional[str] = None
class CeleryConfig:  # pylint: disable=too-few-public-methods
ROBOT_PERMISSION_ROLES = ["Public", "Gamma", "Alpha", "Admin", "sql_lab"]

```
![Screenshot from 2021-09-02 12-47-22](https://user-images.githubusercontent.com/43311295/131961456-66f471c1-0c40-4958-801d-646534446191.png)

**Comment by epa095** [comment]
@mjmanas0699 : have you tried actually setting PUBLIC_ROLE_LIKE to e.g. "Gamma"? In your example it is None

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
