### ISSUE TITLE
Displaying issue with tablechart

### ISSUE THREAD

**Issue by kevinhodes** [apache/superset#16588]
I have a table chart with 2 rows. But the height is not enough to show both rows.
when displayed on a 1920x1080 it displays the vertical scroll bar, but in the 2560 x 1440,  I get the attached image

### Expected results
There are 2 options either resize the table to include everything.  There is space as you can see from the image.

what you expected to happen.

### Actual results
![image](https://user-images.githubusercontent.com/89279983/132062496-07514452-b58c-4d81-b4ad-73d551f5bd77.png)

### Environment

(please complete the following information):
- docker image 
REPOSITORY        TAG       IMAGE ID       CREATED       SIZE
apache/superset   latest    2ec670d63104   2 weeks ago   1.44GB
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [*] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [*] I have reproduced the issue with at least the latest released version of superset.
- [* ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing since this has gone well over a year without any other reports corroborating the issue.
