### ISSUE TITLE
Extra features for Range Filters

### ISSUE THREAD

**Issue by stevetracvc** [apache/superset#16582]
**Is your feature request related to a problem? Please describe.**
Range filters are fantastic, but there is no simple way to adjust the step size or the scale of the range. Scale is useful for large ranges, eg a log scale, so that you can easily select small and large values

**Describe the solution you'd like**
I've already implemented this on my own fork. 

- Step Size is just an additional Advanced Config dropdown box with several pre-populated choices, as well as a free form option. The tricky part was getting it to properly work in the Native Filter Config modal, since they're expecting all parameters to be checkboxes.
- Scale is a little trickier, but it could possibly be set up as multiple options (eg log, power, etc). Currently I implemented a log scale option, which would make zeros hard. I'm currently ignoring that :)

**Describe alternatives you've considered**

- Simplest option for Scale would be to ditch antd ranges and use material-ui, as it appears to be built in https://material-ui.com/api/slider/
- Another option would be to add text boxes to allow the user to manually enter values

**Additional context**
Here's what I have so far:

Config Screen Usage
![config screen use](https://user-images.githubusercontent.com/70416691/132033938-6d095135-698b-448c-aeb7-2ec359388038.gif)

Log Scale with 0.01 step size
![log-scale and 0 01 step](https://user-images.githubusercontent.com/70416691/132033942-06eda7eb-1f09-49c9-a3bf-847de4848a5e.gif)

Linear Scale with 100k step size
![linear-scale and 100k step](https://user-images.githubusercontent.com/70416691/132033945-2b592134-3614-4ac4-84eb-d6eb497e9e36.gif)

Config Screen Defaults
![config screen defaults](https://user-images.githubusercontent.com/70416691/132033950-9f026b6b-b364-465a-81c1-c224869b4c65.png)

This works both as a Native Filter and as an experimental Cross Filter

**Comment by rusackas** [comment]
@stevetracvc I just came across this... is this something there's still interest in pursuing, or is it old news by now?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
