### ISSUE TITLE
Calendar Heatmap - Can not see the current month

### ISSUE THREAD

**Issue by aivorra** [apache/superset#16585]
The calendar heatmap with filter like 'last week' only show me some days from the last month.

### Expected results

Today 09/03, calendar should show August and September with all the days in gray and only with color from 08/27 to 09/02.

### Actual results

I only see last 5 days of August. I do now see September.

#### Screenshots

This is what I see:

![queries-por-dia-2021-09-03T19-54-03 990Z](https://user-images.githubusercontent.com/10197214/132060637-0d09d923-51d7-40c0-8821-1407f8157863.jpg)

I should see something like this:

![Captura de pantalla de 2021-09-03 17-11-02](https://user-images.githubusercontent.com/10197214/132060827-b2dd9fd5-c53f-4231-a442-dfbf7d82852f.png)

#### How to reproduce the bug

Set 'last week' in "time range" or set a small period of time than a month.

### Environment

- superset version: `1.3.0`
- python version: `3.7.5`
- node.js version: `not installed`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

Best regards.

**Comment by rusackas** [comment]
I'm assuming this is still happening and hasn't magically resolved itself?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
