### ISSUE TITLE
Question: helm install/upgrade: how to add or replace files in /app/superset/static/ folder?

### ISSUE THREAD

**Issue by ecc256** [apache/superset#16596]
Guys,
What is the best/easiest way to add or replace files, like custom logo, css, etc. for _helm install_?
The files in question are in `/app/superset/static/` folder.
There were few similar questions asked earlier, but they were about local and docker compose install, not helm...
Thanks!

**Comment by rusackas** [comment]
Sorry this fell between the cracks for so long. If you're still looking for an answer here, please join us on Slack and/or open up a Q&A thread on the discussions page. Closing as inactive for now. Thanks!
