### ISSUE TITLE
Folder structure for SQL scripts and tagging of SQL scripts

### ISSUE THREAD

**Issue by yourssvk** [apache/superset#16598]
Problem Description:

Users coming from thick client tools look for a File explorer to organize their queries by category and tag their queries etc.
(like a folder structure to SQL scripts on the left-hand side like more query thick client tools have). The folder structure and tagging may be required for dashboards as well.

Workaround/ Resolution:

We have to find a way to manage query folder structure and tags outside of Superset.

**Comment by rusackas** [comment]
I believe this is _sort of_ happening now that we have a feature flag to turn on content tagging. I'm not sure if this is happening with saved queries yet, but that was part of the plan. This thread has gone dormant for quite a while, and we're moving this sort of feature request over to Discussions in the Issues section. If you still have interest in the feature (particularly if you have a design/architecture proposal, or any bandwidth to help contribute to it), I'd encourage you to do so. Thanks!
