### ISSUE TITLE
Including column headings while copying to clipboard (sq lab)

### ISSUE THREAD

**Issue by yourssvk** [apache/superset#16604]
Problem Statement:

Right now, the Copy to Clipboard button does not copy the column names, but only the data below. It will be good to include the column names as well

Workaround/ Resolution:

Use other tools to get the column names separately

**Comment by sfirke** [comment]
@villebro I believe your PR https://github.com/apache/superset/pull/23720 closed this?

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
