### ISSUE TITLE
Allow supersetNode in Helm chart to have its own ENV variables.

### ISSUE THREAD

**Issue by dd-willgan** [apache/superset#16625]
I'm using [Vault env variable injection](https://banzaicloud.com/blog/inject-secrets-into-pods-vault-revisited/) for passing secrets for my Superset k8s cluster. How this works is that a web-hook looks at the env variables and if they're of the form `vault:` it'll pull the secret. The pod, however, needs to have the proper annotations for this. My issue is that `extraEnv` adds the variables to `supersetNode`, `supersetWorker`, and the init job but the init job doesn't support `podAnnotations` through the chart. Since only `supersetNode` needs the secret I want, as a solution, to have a separate `env` section under `supersetNode` in `values.yaml` that only creates env variables for it.

**Comment by wiktor2200** [comment]
@dd-willgan Hi! Have you managed to use vault injected variables in form: vault:PATH#SECRET?
I need to pass credential for OAuth (https://github.com/apache/superset/discussions/13915#discussioncomment-1883043)
But it fails. I'm asking because maybe you were able to use it some way?

**Comment by dd-willgan** [comment]
@wiktor2200 Hi yes I've been able to. Based on the error message in the comment it seems like `client_secret` is being set but is just incorrect? When I was having issues with Vault the Kubernetes pod would Error before running.

**Comment by wiktor2200** [comment]
Thanks for answer! Sorry, I've not noticed notification earlier. You were right the problem was caused by wrong vault policies setting.

**Comment by rusackas** [comment]
Sounds from the discussion here that this was effectively resolved over a year ago. Holler if I'm misinterpreting, and we can revisit/reopen.
