### ISSUE TITLE
Add option to show legend to sunburst type chart

### ISSUE THREAD

**Issue by fauzialhari** [apache/superset#16641]
**Problem**
Currently sunburst type chart doesn't have any option to show legends, and the detail of data of sunburst chart only visible on hover.
![image](https://user-images.githubusercontent.com/32444439/132491364-d0ed7ddc-40d4-4fc3-b0e2-70a6dba80eaf.png)
This is painstaking for users when users need to see the whole context of data and try to understand the whole information on the chart at one sight. To see the detail information, they have to hover one by one color to see what the color represents of and the data. The other problem, when users download as image, they will not have any clue about what the chart tries to tell about. So without hovering and when download the image all they can see just this, which is not very informational.
![vaccine-candidates-per-country-stage-2021-09-09T05-03-52 818Z](https://user-images.githubusercontent.com/32444439/132626152-e87013ae-f86b-43f3-9bc5-750c811136d6.jpg)

**Proposed Solution**
It would be helpful to user if sunburst chart has option to show or hide legend. Something like this:
![image](https://user-images.githubusercontent.com/32444439/132627830-05993b40-d194-48d9-ab2b-e24a120dc555.png)

**Alternative Solution**
Another alternative that I think would be helpful is user has option to show label. Something like this:
![image](https://user-images.githubusercontent.com/32444439/132631704-41e790fa-2722-4b94-8402-b13980665e46.png)
https://www.researchgate.net/figure/Sunburst-chart-of-most-altered-ncRNAs-This-type-of-visualization-shows-hierarchy-through_fig2_328829976

Thank you

**Comment by rusackas** [comment]
Closing this issue since it's stale, and more of a feature request than a bug report. I think the new (linked above) ECharts based Sunburst chart handles a lot of what's being asked for here. If there are more features that are needed, I'd suggest taking this up in an Ideas thread and trying to drum up more support or seeking someone able/willing to open a PR. Thanks!
