### ISSUE TITLE
Failed to start superset from Docker-compose

### ISSUE THREAD

**Issue by SunnyZ-L** [apache/superset#16659]
superset_app, superset_worker, and superset_worker_beat cannot be started when installing superset from the instructions
https://superset.apache.org/docs/installation/installing-superset-using-docker-compose

#### Screenshots

![图片](https://user-images.githubusercontent.com/56599784/132811633-e952aab1-5745-4fa0-942b-ad9845ace816.png)

**Comment by SunnyZ-L** [comment]
By adding the Privileged configuration to compose, the appeal issue has been resolved, but a new issue has arisen
![图片](https://user-images.githubusercontent.com/56599784/132818675-918809cf-b385-41e2-9c08-5c758f3e9365.png)

**Comment by srinify** [comment]
@SunnyZ-L hm can't replicate at all. Have you tried updating your docker images and seeing if it still occurs? Have you made any tweaks to your docker compose file that could be impacting this?

**Comment by clementchong** [comment]
Not sure if it is just me, I need to prefix with sudo to pull successfully.

$ sudo docker-compose -f docker-compose-non-dev.yml pull

Below command able to start but I run into multiple errors. Seems some issues with the pull operation.

$ sudo docker-compose -f docker-compose-non-dev.yml up

Found https://github.com/apache/superset/issues/17949

Below command works after git clone but still getting SQL errors and unable to startup. Hopefully, we can get help from superset experts to at least have a working copy of fresh superset locally.

cd superset
sudo docker build -t apache/superset:latest-dev .

**Comment by rusackas** [comment]
Things seem to be working just fine. I can't repro this either, and it was opened in the era of a version that's no longer supported. If you're facing this with versions of Superset that are current (e.g. 2.0.1) let's open a fresh issue with fresh context. Thanks!
