### ISSUE TITLE
NaN in legend dimension

### ISSUE THREAD

**Issue by wildsonc** [apache/superset#16655]
### Expected results

In the chart created before the upgrade, the legend appears normally:

![image](https://user-images.githubusercontent.com/72408418/132760137-339cdc40-1406-4835-897e-6774f6ed67ca.png)

### Actual results

But any new chart don't work

![image](https://user-images.githubusercontent.com/72408418/132760208-6df6f471-efc0-42dd-a1ac-f696eb76cfbb.png)

When I try to create the first chart that is working, the same error occurs, but if I edit the legend/dimension and change it keeps working

#### How to reproduce the bug

1. Go to 'charts'
2. Create a new Scatterplot view
3. Choose a column for dimension

### Environment

- superset version: `1.3.0`

**Comment by rusackas** [comment]
Unable to replicate in current-era Superset. Also the issue has been stale for a while. Ping me if this needs revisiting!
