### ISSUE TITLE
How can I use Row Level Security in Superset version 1.1.0?

### ISSUE THREAD

**Issue by norpriest** [apache/superset#16651]
Hi,

In version 0.0.0dev, there was this option to set up RLS, but in version 1.1.0 there's none.

How can I use RLS in Superset version 1.1.0? 

![lpo](https://user-images.githubusercontent.com/72668447/132688217-851470d4-3e7b-4dfe-9315-03fbc751c08a.png)

**Comment by vivek-kandhvar** [comment]
Why are you using outdated version? 1.3.0 is out and you can try with that.

**Comment by rusackas** [comment]
Closing since this is a very old (and stale!) issue (we're currently on 2.0.1) and this is not a bug in the first place, but rather a question that could be answered on Slack or in the Discussions Q&A tab :)
