### ISSUE TITLE
Ability to remove share url from dashboard tabs

### ISSUE THREAD

**Issue by JMGGarcia** [apache/superset#16667]
Is it possible to remove the urls for sharing a tab? I wanted to share this dashboard with the public and wouldn't want them to have the ability to create sharing urls.

I tried to see if the Role Attributes had something that affected this but I couldn't find them (but there are a lot of them, I might have missed it!). 

### Expected results

Simple tabs

### Actual results

Tabs with sharing options. 

#### Screenshots

![image](https://user-images.githubusercontent.com/6731738/132889157-e34f3baa-8413-48a5-a373-98f0eaca6fae.png)

#### How to reproduce the bug

1. Create dashboard with tabs
2. Hover over the tabs button and see the sharing button

### Environment

(please complete the following information):

- superset version: 1.3.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
The feature is still there, though the URL format of these permalinks has changed.
<img width="673" alt="image" src="https://user-images.githubusercontent.com/812905/216421673-49a45beb-d3e3-431c-b15f-5bf79b7170e3.png">

I don't know of a permission/config to disable this, and didn't spot anything obvious in the code. CC @michael-molina in case he knows of one by chance. I believe we'd be open to reviewing a PR that adds such a config/permission, or you can open up an Ideas thread on the Discussions tab above to make a proposal for a new feature.

**Comment by Aponte145** [comment]
Hello,

you can remove it using this code in css in edit css of your dashboard

.anchor-link-container .short-link-trigger {
display: none;
}
