### ISSUE TITLE
Superset Show Detailed Error Message Instead of Custom Error Message

### ISSUE THREAD

**Issue by Pajri** [apache/superset#16663]
Hi,
I'm using superset Version: 1.2.0. When I access user listing page (/users/list/) and left some field blanks, it show a detailed error message. We are using superset version 1.2.0

 

This is the step to reproduce the issue :

1.  Access user listing page (/users/list)
2.  Click Filter List, choose :
- Created By (Leave it Blank)

- Changed By (Leave it Blank)

- First Name (Input Garbage)

- Last Name (Input Garbage)

- Click Refresh

3. A detailed error message will be shown.
![image](https://user-images.githubusercontent.com/6915392/132837977-776eafa1-0241-421d-9b08-6a23dede6834.png)

This also happen when accessing this path /superset/schemas_access_for_csv_upload?db_id=2

Is there any way to show a custom/common error page instead the detailed error page ? We have set the env to prod mode but the error message is still shown.

**Comment by dpgaspar** [comment]
@Pajri thank you for reporting this issue, the first errors on `users/list` seems like a FAB bug with PG, I'll address that.
Still investigating the detailed error message and if it's possible to optionally make it less detailed .

**Comment by dpgaspar** [comment]
Hi @Pajri the fix is ready on FAB, for superset you can disable this output by not running your app in debug more, see here: https://github.com/apache/superset/blob/master/superset/views/base.py#L414

**Comment by rusackas** [comment]
Sounds like this thread is resolved, but it's also stale anyway. Holler if this needs to be revisited for any reason.
