### ISSUE TITLE
[native filter] long list of parent filters is not scrollable

### ISSUE THREAD

**Issue by adam-stasiak** [apache/superset#16664]
The problem is that when I try to scroll list of options in parent filters menu - then I am scrolling whole window and cannot scroll to the bottom when list has many items.
### Expected results
Select is scrollable.
### Actual results
Select is not scrollable.Window is scrolled while doing scroll in this area.
what actually happens.

#### Screenshots

https://user-images.githubusercontent.com/25153919/132868318-4fa79ec7-2908-4091-a3ef-248c7b33f4c9.mov

#### How to reproduce the bug

1. Go to Dashboard
2. Add many native filters
3. Try to make hierarchal filter

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by kgabryje** [comment]
I think this issue is outdated

https://user-images.githubusercontent.com/15073128/145575478-9c49eff8-1f9b-4e6a-b478-4784d9a2fd3f.mov

**Comment by stephenLYZ** [comment]
I think this [PR](https://github.com/apache/superset/pull/16702) has fixed it, lets turn it off.

**Comment by kgabryje** [comment]
Thanks for clarification Stephen, I'm closing this issue.
