### ISSUE TITLE
[native filter] Time range filter when going back to "No filter" value should cause this filtered shown as Unset

### ISSUE THREAD

**Issue by adam-stasiak** [apache/superset#16665]
When going back from value to No Filter - charts on dashboard should present this filter as unset.
### Expected results

Filter should land in unset filters section on chart.
### Actual results

Filter should be presented in unset section.
#### How to reproduce the bug

1. Go to dashboard
2. add time range native filter
3. set value to last month and apply
4. set value to no filter and apply
5. check unset section of chart

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
This works just fine in current Superset.
