### ISSUE TITLE
Superset multilingual support？

### ISSUE THREAD

**Issue by qiaofeng1227** [apache/superset#16671]
![image](https://user-images.githubusercontent.com/43192516/132944503-4b6e622e-8437-4afc-ad3f-6bb9c56f6b1c.png)

Install superset through docker. There is no language selection menu. The official website documents have the function of selecting languages.Does the docker version of superset have a multi language selection menu，Please confirm it，thank you very mach.

**Comment by etr2460** [comment]
you can configure this with a custom config, see the specific flags and options here: https://github.com/apache/superset/blob/master/superset/config.py#L296-L313

**Comment by DEVLHK** [comment]
I have change "ABEL_DEFAULT_LOCALE" to "zh", but it doesn't work, pls help!

**Comment by LovelyShiba** [comment]
> ![图片](https://user-images.githubusercontent.com/43192516/132944503-4b6e622e-8437-4afc-ad3f-6bb9c56f6b1c.png)
> 
> 通过 docker 安装超集。没有语言选择菜单。官网文档有选择语言的功能。docker版superset有没有多语言选择菜单，请确认一下，非常感谢mach。

大哥，解决了嘛？我试了一周了，还是切换不了
