### ISSUE TITLE
NO_TOKEN_WARNING broken URL

### ISSUE THREAD

**Issue by frafra** [apache/superset#16686]
`Note on Map Tokens` link, which is triggered by `NO_TOKEN_WARNING` by the MapBox visualization type, is broken.

### Expected results

A working link.

### Actual results

https://uber.github.io/react-map-gl/#/Documentation/getting-started/about-mapbox-tokens is broken

#### How to reproduce the bug

1. Run `docker-compose-non-dev.yml`
2. Create a dataset with a time column, latitude and longitude
3. Set up a MapBox visualization
4. Click on Run
5. Click on the link to get extra information

### Environment

(please complete the following information):

- superset version: `Superset 0.0.0dev`
- python version: `3.7.9`
- node.js version: `command not found`
- any feature flags active:

Docker image: `apache/superset@sha256:7c7d0b1c05380c884c0f0825b8864b364d8e6c4ba997d1eb9e526f278a7b7175`
`docker pull apache/superset:4dc859f89e5668ed3f94cd1ef0532a301a3ab85a`

Tip: bug report template could include some suggestion on how to extract those data for Docker users.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by frafra** [comment]
Should https://docs.mapbox.com/help/getting-started/access-tokens/#how-access-tokens-work be used instead?

**Comment by frafra** [comment]
Not stale.

**Comment by rusackas** [comment]
I don't think it even shows this warning anymore, if I'm not mistaken.
<img width="860" alt="image" src="https://github.com/apache/superset/assets/812905/12e03545-a267-4cca-9a45-1e99961c8de3">

If I'm misinterpreting, I'm happy to re-open this, but otherwise I think this can finally be closed :)
