### ISSUE TITLE
Superset - auto cancel oracle query parameter

### ISSUE THREAD

**Issue by nirajtambat** [apache/superset#16684]
In superset if there is a long running query running more than 3 mins (for example), is it possible to kill the query automatically and take the next one in the queue. application should auto-cancel the query. Also Query time out option is set but still on backend query is running. It's not cancelling query execution on database server.  Let us know any solution for this.

**Comment by rusackas** [comment]
@nirajtambat is this still an issue in newer versions of Superset?

@villebro do you think this might be related in shape to your recent query cancellation PR?

**Comment by villebro** [comment]
I think we'd need to implement query cancellation for Oracle. See here for details: https://stackoverflow.com/questions/9545560/how-to-kill-a-running-select-statement

I think it should be fairly straight forward if you have an Oracle instance handy.
