### ISSUE TITLE
the query result in sql lab has no column names when I connect to clickhouse.

### ISSUE THREAD

**Issue by fancyfreeman** [apache/superset#16691]
### Expected results

query result has column names.

### Actual results

the query result in sql lab has no column names when I connect to clickhouse.

#### Screenshots

![image](https://user-images.githubusercontent.com/3318440/133126704-41078215-8f1c-4982-ae30-fcd4a1cff56f.png)

### Environment

(please complete the following information):

- superset version: 1.3.0
- python version:  3.7

**Comment by junlincc** [comment]
@IKkSssDendi @asafcombo @boomballa looks like you all are using clickhouse, do you also experience this issue?

**Comment by sas1024** [comment]
I confirmed this bug.
Also superset 1.3.0
<img width="956" alt="Screenshot 2021-10-11 at 17 33 52" src="https://user-images.githubusercontent.com/7388179/136808352-372a3fdc-f7ec-4b9d-ac0d-47a2e2a25174.png">

**Comment by rusackas** [comment]
@andrey-zayats took a look at this and was unable to reproduce the issue. I'm going to go ahead and remove the `validation:required` label and close the issue. If anyone sees this happening in Superset 2.0.x or later, or on `master`, we're open to revisiting this conversation, re-opening the ticket, or triaging a new Issue with updated context. Thank you!

**Comment by Paulo456** [comment]
clickhouse_sqlalchemy/drivers/http/transport.py
ver 0.1.10 you can set patch
@@ -164,6 +164,7 @@
         params = params or {}
         params['database'] = self.db_name
         params.update(self.ch_settings)
+        params['default_format'] = 'TabSeparatedWithNamesAndTypes'

         # TODO: retries, prepared requests
         r = self.http.post(
