### ISSUE TITLE
Provide functionality to set custom base URL

### ISSUE THREAD

**Issue by eagle8089** [apache/superset#16690]
I have been trying to deploy superset with istio ingress. For this I need to set a URL in the format : http://<IP>:<PORT>/superset

I have tried using reverse proxy, but faced multiple issues and was not able get a satisfactory solution.

**Comment by cberge908** [comment]
I've had the exact same issue @eagle8089 - for me this did the trick:

https://superset.apache.org/docs/installation/configuring-superset/#configuration-behind-a-load-balancer

-> Just add `ENABLE_PROXY_FIX = True` to your superset config (secret `superset-config`) and restart your pods.

**Comment by geido** [comment]
Hello @eagle8089 given the suggestion above and the issue being inactive for a long time I am going to close it. Thanks!
