### ISSUE TITLE
[bubble chart] should allow user set min and max y-axis bounds

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#16709]
**Describe the solution you'd like**
bubble chart should allow user set min and max y-axis bounds. Otherwise it's really hard when 2 bubble charts side by side comparison.

<img width="1138" alt="Screen_Shot_2021-09-14_at_4_58_42_PM" src="https://user-images.githubusercontent.com/27990562/133349269-75b6e2b8-d0e8-4e6a-a2e6-00bf7265bb21.png">

cc @junlincc @villebro

**Comment by junlincc** [comment]
the plan is to add size to scatter plot echarts as a new bubble chart and deprecate the old one. the process may take a while. seems to be a relatively easy task. maybe we can work on it? 
@pkdotson cc @villebro

**Comment by zhouyao1994** [comment]
look great~

**Comment by pkdotson** [comment]
closes https://github.com/apache/superset/issues/16709
