### ISSUE TITLE
[annotation] table event annotation is broken after recent superset-ui upgrade

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#16708]
### Actual results

`Table` type Event Annotation didn't show on chart any more after #16601.

#### Screenshots

<img width="831" alt="Screen_Shot_2021-09-14_at_4_35_48_PM" src="https://user-images.githubusercontent.com/27990562/133348143-588ef4af-3e36-4b5a-a81b-c5bdb0c3673d.png">

### Environment

latest master.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

cc @villebro

**Comment by junlincc** [comment]
@pkdotson may not be that straightforward but let's give it a try/ higher priority

**Comment by pkdotson** [comment]
@graceguo-supercat  can you please add steps to reproduce this with an example chart or add some steps to help our qa pinpoint this. I'm not able to reproduce this easily as the annotation does show on chart.

**Comment by yousoph** [comment]
Haven't been able to repro this either, please reopen with more details if you are still able to repro. Thanks!!
