### ISSUE TITLE
[TODO] Add multiple databases and schemas to the test environment

### ISSUE THREAD

**Issue by ktmud** [apache/superset#16714]
To help test PRs like https://github.com/apache/superset/pull/16393

We should create multiple databases & schemas for the ephemeral test environment.

**Comment by junlincc** [comment]
@ktmud I don't fully understand. Can you give an example? 🙏

**Comment by ktmud** [comment]
<img width="522" alt="Xnip2021-09-17_11-12-17" src="https://user-images.githubusercontent.com/335541/133834794-9f0bd730-aa67-4011-8fca-5378987f22cd.png">

So that this dropdown can have multiple values.

**Comment by jinghua-qa** [comment]
i think we have max 3 schemas in our current internal testing db

**Comment by Rispectech** [comment]
so these changes are only on the UI and passing the option to the DBMS  or do we need to do more?

**Comment by rusackas** [comment]
In an effort to trim up the Issues backlog, I'm wondering if we want to:
a) close this as stale (since it hasn't been touched in over a year)
b) move it to an Ideas thread, and see if we can drum up any support/discussion there.

Thoughts @ktmud ?

**Comment by Shazad-khan** [comment]
I have added 5 databases on my test environment and i think this issue dosen't exist any more. please cross check it in the latest version and close the issue if already resolved.

**Comment by rusackas** [comment]
Thank you @Shazad-khan! Closing for now, but happy to revisit if needed!
