### ISSUE TITLE
[native_filter] add single select and inverse selection to numeric range

### ISSUE THREAD

**Issue by junlincc** [apache/superset#16722]
"As a user... I would like to target a specific value and not a range of values using a single value slider.  For example, I would like to target a single value in a growth rate of 2x.  By having a single value slider, this allows me to better target the growth rate." 
this request is similar to [[native-filter][ux]hard to specify the min and max in slider when the range is huge](https://github.com/apache/superset/issues/15605)

As a workaround, user may use a Value filter to select a single numeric value in a numeric column.
![image](https://user-images.githubusercontent.com/67837651/133701466-d89cabe7-6cc3-423e-967d-6575f7e69859.png)

**Comment by rusackas** [comment]
Closing as stale, but this might be better served by using a single value select, and sorting the options. If people still want this as a feature, please open an Ideas thread, and we can see if it gathers steam.
