### ISSUE TITLE
ClickHouse metrics always be count()

### ISSUE THREAD

**Issue by liumengkai** [apache/superset#16737]
python3.8
superset version 1.3.0

whatever I select ,the metrics always be count

eg:

![image](https://user-images.githubusercontent.com/31892927/133885233-464b98dc-6015-4786-891d-508be1d230ac.png)

what I got from the “view query” like this:

![image](https://user-images.githubusercontent.com/31892927/133885297-3571013d-29ea-425d-a791-66fbe8098bed.png)

what I excepted is:

COUNT_DISTINCT(event_name) AS "COUNT_DISTINCT(event_name)"
COUNT(device_id) AS "COUNT(device_id)"

the example demo works fine, I think it's mysql database.
It's there something I missed up? thx a lot!

**Comment by villebro** [comment]
This appears to be a bug in the Clickhouse SQLAlchemy dialect. Which Clickhouse connector and version are you using?

**Comment by liumengkai** [comment]
@villebro thanks for your reply

I think the version should be like this : clickhouse-driver==0.2.0 && pip install clickhouse-sqlalchemy==0.1.6

which version do you recommend？

thanks!

**Comment by liumengkai** [comment]
@villebro 
sorrry for my careless,after my checking I found out that what  I really use is 'sqlalchemy-clickhouse-0.1.5.post0', I uninstall it and use the right sqlalchemy which is "clickhouse-sqlalchemy==0.1.6",everything is ok!
thx!
