### ISSUE TITLE
Adding a new custom item in superset SQL LAB menu

### ISSUE THREAD

**Issue by amitBhardwaj12** [apache/superset#16744]
### Discussed in https://github.com/apache/superset/discussions/16642

Adding a new item in SQL LAB menu .
Added below code in app.py for appBuilder to add new item link. Also handled the below url on front end side. But new item with driftUI is still not visible. 
appbuilder.add_link(
            __("Drift UI"),
            href="/superset/sqllab/drift/",
            icon="fa-search",
            category="SQL Lab",
        )</div>

**Comment by junlincc** [comment]
Hi @amitBhardwaj12 ! Could you share more about the purpose of this change? Is there any UI implications? if it's feature request, please fill out the issue template. 🙏
