### ISSUE TITLE
Duplicate configurations for Row level security 

### ISSUE THREAD

**Issue by syazwan0913** [apache/superset#16746]
**Is your feature request related to a problem? Please describe.**
Problem to duplicate configuration when using row level security feature. Need to create one by one. 

**Describe the solution you'd like**
Should be able to duplicate just like duplicate user roles. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rusackas** [comment]
Closing since this is a stale feature request at this point. If you still want the feature, I'd suggest adding updated context in an "Ideas" thread in the Discussions tab.
