### ISSUE TITLE
[Explore]add new operators to ad hoc filter

### ISSUE THREAD

**Issue by junlincc** [apache/superset#16765]
- Add new operators: "Contains", "Starts with" and "Ends with" (`'%str%'`, `'str%'` and `'%str'` respectively) that will escape underscores, do **case insensitive** matching when writing all lowercase (e.g. "ma") and **case sensitive** when writing mixed case (e.g. "Ma"). These would be primarily geared towards less technical business users. The reason for deciding when to do case sensitive vs insensitive matching is to keep the basic UX as simple as possible and avoid having to add separate case sensitive and insensitive variants of these operators.

Someone will undoubtedly want to do case sensitive all lowercase matching, but for those cases they should probably just learn to use the full `LIKE` operator.

_Originally posted by @villebro in https://github.com/apache/superset/issues/16396#issuecomment-920672125_

as comment to #16277 and #16396

**Comment by rusackas** [comment]
Closing as stale, but if people are still interested in this, let's refresh it as an Ideas thread.
