### ISSUE TITLE
[report] Open alert/report configuration modal by URL

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#16764]
**Describe the solution you'd like**
When user want to check the configuration of a report/alert, right now they can open report/alert list page, and find his/her report by title or owner. it is not convenient if you have a lot of reports in the list. 

Could we generate a static url for each report or alert configuration (like dashboard url)? 
When user open URL, configuration modal should simply open for edit.

cc @eschutho

**Comment by graceguo-supercat** [comment]
No...my feature request is more likely used by admin, or someone not the owner of a report. 
For example, our user asked me, "i wanted to schedule a report sending out at every Monday 3:00 EST but it didn't send out, could you help me check if my setting is correct?"
if we can share report configuration by URL, it will be easier than search by name (right now).

**Comment by eschutho** [comment]
Ok, that makes sense, thanks @graceguo-supercat. @yousoph let's see how we can implement this. Maybe we can utilize this url in the email itself, too.

**Comment by graceguo-supercat** [comment]
it will be best if users can share a static url like dashboard. For example, for scheule_id = 101, the url will be
`https://superset.d.musta.ch/superset/report/101/`. When user open url from browser, it could be the report list page, but the modal for the report 101, should be open.

**Comment by rusackas** [comment]
@yousoph @eschutho is this still on the radar? If not, maybe we should migrate it to an Ideas thread or just close it as stale.

**Comment by eschutho** [comment]
No, no plans to work on this in the near future.

**Comment by rusackas** [comment]
Closing as stale, then. Thanks all!
