### ISSUE TITLE
Absolute value diff is incorrect

### ISSUE THREAD

**Issue by rubypollev** [apache/superset#16766]
Absolute value diff is `t1 - t2` when it should be `|t1 - t2|`. The absolute value function is not being applied.

https://github.com/apache/superset/blob/4e3d4f6daf01749b8f28e0770e138db5ed8fae91/superset/viz.py#L1434

**Comment by zhaoyongjie** [comment]
@rubypollev The absolute function is not necessarily applied to diff results. cc: @junlincc 

`diff` In the tableau
![image](https://user-images.githubusercontent.com/2016594/135038295-5bc63c57-c4d6-44f6-8218-e278bcb65601.png)

**Comment by rubypollev** [comment]
Tableau's implementation makes sense. This is a "difference." It can be negative.

Superset's implementation claims this same function is an "absolute difference," though, which it's not:
<img width="1538" alt="time_comparison_absolute_difference" src="https://user-images.githubusercontent.com/45610410/135128264-8142b9b0-a3c0-4831-8674-069c5c4325b3.png">

An [absolute difference](https://en.wikipedia.org/wiki/Absolute_difference) is non-negative by definition.

**Comment by zhaoyongjie** [comment]
Hi @rubypollev, thanks for your Issue, I will fix it asap.
