### ISSUE TITLE
Unable to add URL link to column value with pivot table

### ISSUE THREAD

**Issue by VikramKumarArammeem** [apache/superset#16778]
![image](https://user-images.githubusercontent.com/90202730/134302723-8572720d-d777-4fd8-94aa-245013114595.png)

> While trying to add external link(url) with pivot table column value its not converting them as link. its simply pasting the html code with column value.

> At same time if chart is simple table it is successfully generating link with column value...

what you expected to happen.

I was expecting that while adding link to column value using html text it should reflect value with click enable.

what actually happens.
Actual result: Pivot column value unable to convert html syntax to add link to text/number. it just showing entire html text with number

#### Screenshots
Expected: Need value should be clickable with added link
![image](https://user-images.githubusercontent.com/90202730/134302288-1a5b72e5-e82c-4f9c-9b39-5c3c0996cbdf.png)

This is what happening now:

![image](https://user-images.githubusercontent.com/90202730/134302647-ee80f3f4-06b3-49f9-964a-971561f0378a.png)

Any help would be highly appreciated

**Comment by junlincc** [comment]
hi @VikramKumarArammeem, we can confirm that this functionality is not designed or being supported in both legacy(the one you are using) and pivot table v2(in latest master or 1.3). 
Having a clickable link may open up some security concerns, and supporting it as an optional feature is a bit of a maintenance burden. 

We can embed a google sheet table that contains linked cells to the dashboard though.

**Comment by rusackas** [comment]
I'm not aware of this being on anyone's roadmap at the moment, but like open source project always say, we're happy to help review PRs :)

**Comment by moksh-enf** [comment]
I figured out a way to add links into the Pivot table but not sure if a lot of people require this feature which is why I did not raise a PR.

However, if needed, I could create a PR and with some help add that feature.

**Comment by AnidhaCo** [comment]
> I figured out a way to add links into the Pivot table but not sure if a lot of people require this feature which is why I did not raise a PR.
> 
> However, if needed, I could create a PR and with some help add that feature.

It would be great if you could let me know the way you have figured out to add links to the Pivot table.

**Comment by moksh-enf** [comment]
Make the following changes in TableRenderers.jsx

![image](https://user-images.githubusercontent.com/105234138/183975846-9dedc474-ffb8-48b7-8d6d-8684a72f6765.png)


![image](https://user-images.githubusercontent.com/105234138/183975893-0fccc2a6-b349-4d70-b8c9-c4f523a8b373.png)

![image](https://user-images.githubusercontent.com/105234138/183975967-0c0d94b6-c087-403f-ade3-54ab271e44e7.png)

**Comment by Enzozzzz** [comment]
> Make the following changes in TableRenderers.jsx
> 
> ![image](https://user-images.githubusercontent.com/105234138/183975846-9dedc474-ffb8-48b7-8d6d-8684a72f6765.png)
> 
> ![image](https://user-images.githubusercontent.com/105234138/183975893-0fccc2a6-b349-4d70-b8c9-c4f523a8b373.png)
> 
> ![image](https://user-images.githubusercontent.com/105234138/183975967-0c0d94b6-c087-403f-ade3-54ab271e44e7.png)

userful! thanks~
