### ISSUE TITLE
[Explore] Inconsistent button styles in AntD confirmation modal 

### ISSUE THREAD

**Issue by ktmud** [apache/superset#16775]
## Screenshot

<img width="1034" alt="Xnip2021-09-21_16-32-10" src="https://user-images.githubusercontent.com/335541/134261030-e25fccc6-bd3c-44b6-9069-cd4b143a6dff.png">

## Description

We should probably update the button styles in AntD's confirmation modal to be consistent with other parts of the page.

**Comment by toth2000** [comment]
I am looking into it.

**Comment by luecarrio** [comment]
Can you, please, specify the files to be taken a look into in order to update those buttons?

**Comment by rusackas** [comment]
Based on the linked issue's thread, I _believe_ this was effectively closed by https://github.com/apache/superset/pull/22737
