### ISSUE TITLE
[Gallery]Hide the bottom info section when no chart is being selected

### ISSUE THREAD

**Issue by junlincc** [apache/superset#16771]
In current viz gallery modal, we show a big empty section at the bottom to prompt users to 'select a visualization type'. This area is no being used properly as 1) it takes up half of the real estate that could be used to show more categories and chart types. 2) visually uneven 

Suggest: hide this section when no charts is selected. Only show after users click on one chart. 
<img width="1363" alt="Screen Shot 2021-09-21 at 3 04 22 PM" src="https://user-images.githubusercontent.com/67837651/134254304-f7fe3804-01f9-4f74-9a48-e4a4c329d463.png">

https://user-images.githubusercontent.com/67837651/134254313-0c52b7e1-a1c0-41da-99e6-f7f0830dde8b.mov

**Comment by jess-dillard** [comment]
+1  – As @junlincc mentioned, this is taking up a lot of valuable space that could be used to display more charts initially. Additionally, the "Choose chart type" label above the chart selection area should be enough instruction for users.

**Comment by junlincc** [comment]
@jess-dillard  many thanks for the design input! 

@stephenLYZ wanna give it a quick improvement?

**Comment by stephenLYZ** [comment]
@junlincc Sure.

**Comment by zhaoyongjie** [comment]
closed by: https://github.com/apache/superset/pull/16840
