### ISSUE TITLE
Read MAPBOX_API_KEY from environment

### ISSUE THREAD

**Issue by frafra** [apache/superset#16781]
All the settings are read from environment variables, except `MAPBOX_API_KEY`, which requires modifying `superset_config.py`.
https://github.com/apache/superset/blob/master/docker/pythonpath_dev/superset_config.py

https://github.com/apache/superset/blob/a330b664c13e34a4c7ca954f9a3a527a43a5535f/docs/src/pages/docs/frequently-asked-questions-page.mdx#why-is-the-map-not-visible-in-the-geospatial-visualization

It would be better just to add `MAPBOX_API_KEY = get_env_variable("MAPBOX_API_KEY")` somewhere in `superset_config.py` and add `MAPBOX_API_KEY=''` in `docker/.env*` files, and update the documentation accordingly.

**Comment by Lawful2002** [comment]
@frafra I would like to work on this issue if it is still open.

**Comment by frafra** [comment]
@Lawful2002 sure, it is yours :)

**Comment by frafra** [comment]
Not stale.
