### ISSUE TITLE
[Advanced_Analytics]Show advanced analytics time comparison timestamps 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#16786]
As a user, when I use apply time comparison time shift in Time-series charts, and there're more than one series showing on the graph, I expect to see multiple timestamps that reflect the comparing dates in tooltip. 

Currently, user only seeing one base datetime in tooltip, which is the beginning datetime of selected time range. 

<img width="1767" alt="Screen Shot 2021-09-22 at 6 44 03 AM" src="https://user-images.githubusercontent.com/67837651/134355182-25bc75de-5862-4cd0-bd87-ec4ba6e78834.png">

**Comment by rusackas** [comment]
This hasn't gotten any love for over a year, so I'll close it out. If we want to revisit this, let's do it on an Ideas thread.
