### ISSUE TITLE
[SQL LAB]Virtual dataset created from SQLab with incorrect schema

### ISSUE THREAD

**Issue by akotuc** [apache/superset#16791]
When I write a query into `SQLab` by hand and create a dataset using `explore` button incorrect schema (probably from the selection on the left side of SQLab screen) is assigned to the dataset.
E.g. I'm a user with access to schema `A` and `B` of a database (Postgres). I select schema `A` from schema dropbox in SQLab screen and write a query select a table from schema `B`. When I click on `explore` button and save virtual dataset, schema `A` is assigned to the dataset despite query is selecting from a table from schema `B`. This allows users with acces only to schema `A` access data from schema `B`.

### Expected results
I'd expect to be schema of virtual dataset in sync with schema used in the query.

### Actual results
Differenct schema is assigned to virtual dataset and other is actually used in the query.

#### Screenshots
![image](https://user-images.githubusercontent.com/64490668/134396510-84ca0b57-5568-45ec-8021-5ef3c891fa77.png)

#### How to reproduce the bug

1. Go to SQLab
2. Select database and schema from the left dropboxes
3. Write a query by hand selecting from a different schema.
4. Click explore and save virtual dataset
5. Check dataset - assigned schema to the dataset vs schema accessed by the query of the virtual dataset

### Environment
- browser type and version: Chrome Version 93.0.4577.82
- superset version: 1.3.0
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

**Comment by jinghua-qa** [comment]
I am able to reproduce this issue

https://user-images.githubusercontent.com/81597121/134434168-fca58374-a8b7-4cb0-81e9-7684f6780934.mov

**Comment by eschutho** [comment]
we're looking into this, thank you!

**Comment by akotuc** [comment]
Any ETA on this please? Thank you

**Comment by eschutho** [comment]
@akotuc the schema in the virtual dataset is not the schema used in the sql query but rather the default schema that the dataset uses when one isn't defined. Would it make more sense @yousoph to say "Default Schema" instead? cc @rusackas

**Comment by rusackas** [comment]
Since we haven't heard back on the last pending question for a year and a half, I'll close this as stale. We're trying to steer toward a more actionable Issues backlog, so if people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
