### ISSUE TITLE
[Examples] metadata is missing schema in example datasets 

### ISSUE THREAD

**Issue by michael-s-molina** [apache/superset#16793]
<img width="1773" alt="Screen Shot 2021-10-12 at 7 35 22 AM" src="https://user-images.githubusercontent.com/70410625/136940429-4ea71d1a-889b-44cb-9b6d-955d7ab28ef2.png">

**Comment by castellanos-ricardo** [comment]
@michael-s-molina Got it, I will work on this issue.

**Comment by mnunez1023** [comment]
Hi, I've been working on this with @castellanos-ricardo and @ARES-79. Looks like #16041 fixes this issue and this issue is a duplicate of #16051.

**Comment by rusackas** [comment]
Closing in favor of #16051, and hopeful that #16041 fixed this (and maybe that one too!)
