### ISSUE TITLE
[Proposal] Superset Frontend Testing Guidelines

### ISSUE THREAD

**Issue by michael-s-molina** [apache/superset#16792]
# Superset Frontend Testing Guidelines

We feel that tests are an important part of a feature and not an additional or optional effort. That's why we colocate test files with functionality and sometimes write tests upfront to help validate requirements and shape the API of our components. Every new component or file added should have an associated test file with the `.test` extension.

We use Jest, React Testing Library (RTL), and Cypress to write our unit, integration, and end-to-end tests. For each type, we have a set of best practices/tips described below:

### Write simple, standalone tests
The importance of simplicity is often overlooked in test cases. Clear, dumb code should always be preferred over complex ones. The test cases should be pretty much standalone and should not involve any external logic if not absolutely necessary. That's because you want the corpus of the tests to be easy to read and understandable at first sight.

### Avoid nesting when you're testing 
Avoid the use of `describe` blocks in favor of inlined tests. If your tests start to grow and you feel the need to group tests, prefer to break them into multiple test files. Check this awesome [article](https://kentcdodds.com/blog/avoid-nesting-when-youre-testing) written by [Kent C. Dodds](https://kentcdodds.com/) about this topic.

### No warnings!
Your tests shouldn't trigger warnings. This is really common when testing async functionality. It's really difficult to read test results when we have a bunch of warnings.

## Example
You can find an example of a test [here](https://github.com/apache/superset/blob/e6c5bf4/superset-frontend/src/common/hooks/useChangeEffect/useChangeEffect.test.ts)

### Keep accessibility in mind when writing your tests
One of the most important points of RTL is accessibility and this is also a very important point for us. We should try our best to follow the RTL [Priority](https://testing-library.com/docs/queries/about/#priority) when querying for elements in our tests. `getByTestId` is not viewable by the user and should only be used when the element isn't accessible in any other way.

### Don't use `act` unnecessarily
`render` and `fireEvent` are already wrapped in `act`, so wrapping them in `act` again is a common mistake. Some solutions to the warnings related to `act` might be found [here](https://kentcdodds.com/blog/fix-the-not-wrapped-in-act-warning).

### Be specific when using *ByRole
By using the `name` option we can point to the items by their accessible name. For example:

`screen.getByRole('button', { name: /hello world/i })`

Using the `name` property also avoids breaking the tests in the future if other components with the same role are added.

### userEvent vs fireEvent
Prefer the [user-event](https://github.com/testing-library/user-event) library, which provides a more advanced simulation of browser interactions than the built-in [fireEvent](https://testing-library.com/docs/dom-testing-library/api-events/#fireevent) method.

### Usage of waitFor
- [Prefer to use `find`](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#using-waitfor-to-wait-for-elements-that-can-be-queried-with-find) over `waitFor` when you're querying for elements. Even though both achieve the same objective, the `find` version is simpler and you'll get better error messages.
- Prefer to use only [one assertion at a time](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#having-multiple-assertions-in-a-single-waitfor-callback). If you put multiple assertions inside a `waitFor` we could end up waiting for the whole block timeout before seeing a test failure even if the failure occurred at the first assertion. By putting a single assertion in there, we can improve on test execution time.
- Do not perform [side-effects](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#performing-side-effects-in-waitfor) inside `waitFor`. The callback can be called a non-deterministic number of times and frequency (it's called both on an interval as well as when there are DOM mutations). So this means that your side-effect could run multiple times.

### Example
You can find an example of a test [here](https://github.com/apache/superset/blob/a0a00e6/superset-frontend/src/dashboard/components/PublishedStatus/PublishedStatus.test.tsx).

### Prefer to use Cypress for e2e testing and RTL for integration testing
Here it's important to make the distinction between e2e and integration testing. This [article](https://www.onpathtesting.com/blog/end-to-end-vs-integration-testing) gives an excellent definition:

> End-to-end testing verifies that your software works correctly from the beginning to the end of a particular user flow. It replicates expected user behavior and various usage scenarios to ensure that your software works as whole. End-to-end testing uses a production equivalent environment and data to simulate real-world situations and may also involve the integrations your software has with external applications.

> A typical software project consists of multiple software units, usually coded by different developers. Integration testing combines those software units logically and tests them as a group 
> Essentially, integration testing verifies whether or not the individual modules or services that make up your application work well together. The purpose of this level of testing is to expose defects in the interaction between these software modules when they are integrated.

Do not use Cypress when RTL can do it better and faster. Many of the Cypress tests that we have right now, fall into the integration testing category and can be ported to RLT which is much faster and gives more immediate feedback. Cypress should be used mainly for end-to-end testing, replicating the user experience, with positive and negative flows.

### Isolated and standalone tests
Tests should never rely on other tests to pass. This might be hard when a single user is used for testing as data will be stored in the database. At every new test, we should reset the database.

### Cleaning state
Cleaning the state of the application, such as resetting the DB, or in general, any state that might affect consequent tests should always be done in the `beforeEach` hook and never in the `afterEach` one as the `beforeEach` is guaranteed to run, while the test might never reach the point to run the `afterEach` hook. One example would be if you refresh Cypress in the middle of the test. At this point, you will have built up a partial state in the database, and your clean-up function will never get called. You can read more about it [here](https://docs.cypress.io/guides/references/best-practices#Using-after-or-afterEach-hooks).

### Unnecessary use of `cy.wait`
- Unnecessary when using `cy.request()` as it will resolve when a response is received from the server
- Unnecessary when using `cy.visit()` as it resolves only when the page fires the load event
- Unnecessary when using `cy.get()`. When the selector should wait for a request to happen, aliases would come in handy: 
```
cy.intercept('GET', '/users', [{ name: 'Maggy' }, { name: 'Joan' }]).as('getUsers')
cy.get('#fetch').click()
cy.wait('@getUsers') // <--- wait explicitly for this route to finish
cy.get('table tr').should('have.length', 2)
```

### Accessibility and Resilience
The same accessibility principles in the RTL section apply here. Use accessible selectors when querying for elements. Those principles also help to isolate selectors from eventual CSS and JS changes and improve the resilience of your tests.

### References
- [Avoid Nesting when you're Testing](https://kentcdodds.com/blog/avoid-nesting-when-youre-testing)
- [RTL - Queries](https://testing-library.com/docs/queries/about/#priority)
- [Fix the "not wrapped in act(...)" warning](https://kentcdodds.com/blog/fix-the-not-wrapped-in-act-warning)
- [Common mistakes with React Testing Library](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library)
- [ARIA Roles](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles)
- [Cypress - Best Practices](https://docs.cypress.io/guides/references/best-practices)
- [End-to-end vs integration tests: what's the difference?](https://www.onpathtesting.com/blog/end-to-end-vs-integration-testing)

**Comment by geido** [comment]
### RTL

> https://kentcdodds.com/blog/avoid-nesting-when-youre-testing 
+1

> Our test files use the test suffix. We should migrate those that use the spec suffix. 
+1

#### Priorities
I think priorities should be remarked as it is a common mistake:
https://testing-library.com/docs/queries/about/#priority

#### Using `act` unnecessarily
> render and fireEvent are already wrapped in act
https://kentcdodds.com/blog/fix-the-not-wrapped-in-act-warning

#### Using `*ByRole`
By using the `name` option we can point to the items by their accessible name. 

`screen.getByRole('button', {name: /hello world/i})`

Roles reference: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles

#### Prefer userEvent over fireEvent
The user-event library better represents the actual user actions.
@testing-library/user-event

#### Usage of `waitFor`
Do not use it for elements that can be queried with `find`
It should only have one assertion at a time
Do not perform side-effects actions inside `waitFor`. Use it only for assertions

####  Materials:
https://kentcdodds.com/blog/common-mistakes-with-react-testing-library

.....to be continued

**Comment by michael-s-molina** [comment]
These are great points @geido. Thank you!

**Comment by geido** [comment]
### RTL
...continuing on the topic of RTL

#### Simplicity
I believe it's often overlooked how much simplicity is important in test cases. I believe clear, dumb code should always be preferred over complex ones. The test cases should be pretty much standalone, easy to read, should not involve any external logic if not absolutely necessary. That's because you want the corpus of the tests to be understandable at first sight.

**Comment by geido** [comment]
### Cypress
I am not much of a Cypress expert and I am taking what I think are the most relevant points for us from the official documentation, as well as adding some thoughts from my times working with it.

#### Do not use Cypress :)

Do not use Cypress when RTL can do it better and faster. Many of the Cypress tests that we have right now can be ported into RLT that is much faster and gives a more immediate feedback. Cypress should be used mainly for processes from A to B, B to C, etc. replicating the exact user experience, positive and negative flows.

#### Isolated and standalone tests

Tests should never rely on other tests to pass. This might be hard when a single user is used for testing as data will be stored into the database. At the end of each test we should reset the database. This discussion goes a bit out of the scope of the testing guidelines but might be worth pursuing.

#### Cleaning state

Cleaning the state of the application, such as resetting the db, or in general any state that might affect consequent tests, should always be done in the `beforeEach` hook and never in the `afterEach` one as the `beforeEach` is guaranteed to run, while the test might never reach the point to run the `afterEach`hook.

#### Unnecessary use of `cy.wait`
- Unnecessary when using `cy.request()` as it will resolve when a response is received from the server
- Unnecessary when using `cy.visit()` as it resolves only when the page fires the `load` event
- Unnecessary when using `cy.get()`. When the selector should wait for a request to happen, aliases would come handy. For example:

```
cy.intercept('GET', '/users', [{ name: 'Maggy' }, { name: 'Joan' }]).as(
  'getUsers'
)
cy.get('#fetch').click()
cy.wait('@getUsers') // <--- wait explicitly for this route to finish
cy.get('table tr').should('have.length', 2)
```

#### Resilience

Prefer `data-*` attributes to isolate selectors from eventual CSS, JS or text content changes. Creating dedicated data selectors specifically for Cypress might increase the boilerplate a bit but comes with the advantage of being super resilient while making it apparent that the code is being tested. For example:

`cy.get('[data-cy=submit]').click()`

Alternatively using text might work but it is not as resilient. For example:

`cy.contains('Submit').click()`

#### Materials:

https://docs.cypress.io/guides/references/best-practices
https://www.youtube.com/watch?v=5XQOK0v_YRE

**Comment by michael-s-molina** [comment]
@geido @eschutho @lyndsiWilliams I compiled the contributions so far, added some more, and mounted the first version in the PR's description.

**Comment by rusackas** [comment]
One small nit... the philosophy of using data attributes for Cypress is accurate, but thus far we've been preferring `data-test` instead of `data-cy` as outlined above.

**Comment by michael-s-molina** [comment]
> e've been preferring `data-tes`

Thanks for the review. Fixed.

**Comment by etr2460** [comment]
Top level comment, do we want to summarize a list of Dos and Don'ts like Evan did for the emotion guidelines at the top? Not sure if that pattern always works

**Comment by etr2460** [comment]
One other comment, if you could link an example test file or two to the guidelines (ideally a direct link to the current sha so it never changes) that could be helpful. Sometimes showing works better than telling (and honestly, i love being able to copy a test file as a template for the new one i'm making)

**Comment by etr2460** [comment]
Oh sorry, one more thing (but not blocking):

Under cypress you have:
>Prefer data-test attributes to isolate selectors from eventual CSS, JS or text content changes.

Isn't that the opposite as what we recommend for RTL? If it's best practices, then I guess it's fine. But maybe we should further call out why we have 2 different recommendations?

**Comment by michael-s-molina** [comment]
> Top level comment, do we want to summarize a list of Dos and Don'ts like Evan did for the emotion guidelines at the top? Not sure if that pattern always works

That was my initial thought also but I preferred to add more context to each DOs and Don'ts because some are not very clear without the context, e.g. "Do not use Cypress". But it's following the Do's and Don't approach:
Dos:
- Write simple, standalone tests
- Avoid nesting when you're testing
- Keep accessibility in mind when writing your tests
...

Don'ts:
- No warnings!
- Don't use act unnecessarily
- Do not use Cypress :)
...

> One other comment, if you could link an example test file or two to the guidelines (ideally a direct link to the current sha so it never changes) that could be helpful. Sometimes showing works better than telling (and honestly, i love being able to copy a test file as a template for the new one i'm making)

Great suggestion. Will do.

> Isn't that the opposite as what we recommend for RTL? If it's best practices, then I guess it's fine. But maybe we should further call out why we have 2 different recommendations?

Wow! Nice catch. I do agree with you. We can query for elements in Cypress using accessible attributes like `role`. I was reading the [Cypress Best Practices](https://docs.cypress.io/guides/references/best-practices#Selecting-Elements) and it seems their main concern is to use selectors that don't change over time. So I think we'll be fine following RTL query [Priority](https://testing-library.com/docs/queries/about/#priority) and only use the `data-test` as a last resort.

**Comment by eschutho** [comment]
Can we add more explanation to these points so that people reading in the future also understand the why: 
>Usage of waitFor
Do not use it for elements that can be queried with find
It should only have one assertion at a time

**Comment by geido** [comment]
> > when does the afterEach not run? I think it's better to clean up after yourself than after someone else. :)
> 
> @geido Can you detail this?

@michael-s-molina @eschutho The official documentation goes in great length explaining the logic behind this. It is not only the fact that the `afterEach` might not be reached (for instance, by refreshing Cypress in the middle of the test you would build a partial state) but also to keep the ability to work with dangling state https://docs.cypress.io/guides/references/best-practices#Using-after-or-afterEach-hooks

**Comment by eschutho** [comment]
Thanks @geido that article makes sense in the context of Cypress and interacting with the test after it has ran. I think it would be helpful to link that article in the docs, too.

**Comment by lyndsiWilliams** [comment]
Hi! Sorry for chiming in while this is being voted on, but I think it's important to add that we should make sure not to change the codebase in order to fix a test. The only changes that should be added to code regarding tests should be adding a test-id if absolutely necessary.
