### ISSUE TITLE
[native_filter] Inexistent filter value creation can be confusing to novice

### ISSUE THREAD

**Issue by junlincc** [apache/superset#16797]
In the video below, there are 1000+ filter values in the underlying dataset's `name` column. 
With `Search all filter options` box in native filter modal - Advanced section checked, users are able to search and grab filter values beyond the 1000 values display limit. for examples, dropdown list only contains names that start w letter A to J(Julia). name "Max" is a name value that doesn't show in the dropdown, but I can type to search/grab "Max" as a valid filter. 

In this case, "junlin" is not a valid value in the selected column, new name value was "created" in the dropdown list, charts that are mapped to the name filter responded but no data returned. It's incredibly confusing. Since the action enables use to type to select, novice users may accidentally _create_ invalid values by typing, either a typo or inexistent value in the field and mistakenly believe that charts are being filtered by their input. 

**Proposed change:** 
If we have to keep the "type to search/select" functionality in native filter for the 'Search all filter options' feature, we should at least add a validator to distinguish valid and invalid inputs. 

https://user-images.githubusercontent.com/67837651/134428765-51a118c8-3349-4d1e-9282-e3ad6fafd09a.mov

**Comment by rusackas** [comment]
I think this has largely been resolved by numerous revisions in the Select components, so I'm closing optimistically.
