### ISSUE TITLE
hive connect

### ISSUE THREAD

**Issue by zfq314** [apache/superset#16804]
<html>
<body>

pip install pyhive
--

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by zfq314** [comment]
ERROR: Unexpected error occurred, please check your logs for details

**Comment by zfq314** [comment]
![image](https://user-images.githubusercontent.com/33599707/134463948-f6748ca3-1644-4fcc-bcb5-171445056724.png)

**Comment by zfq314** [comment]
superset version 0.38.1
and 

pip install pyhive instered successfully 

hive version 1.2.1

call you tell me ?thanks

**Comment by junlincc** [comment]
> call you tell me ?thanks

can you file issue using bug report template?
