### ISSUE TITLE
Floating Box is located out of chart and can not be visible in Sankey Diagram

### ISSUE THREAD

**Issue by parkjaeman** [apache/superset#16802]
## Screenshot
![sankey diagram issue](https://user-images.githubusercontent.com/4987534/134456561-a58b27c6-0e62-454a-8dca-c45eeb6e159a.png)

## Description
Floating Box is located out of chart and can not be visible in Sankey Diagram

**Comment by Shazad-khan** [comment]
![image](https://user-images.githubusercontent.com/100838455/225292814-4dc904bd-7337-45ac-851a-461a2dd626d5.png)

It is working as expected in the recent release

**Comment by rusackas** [comment]
Scrollbars have been surprisingly tricking, but this is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
