### ISSUE TITLE
"Python Functions" and "Upload a Columnar file" doesn't appear when Installing Superset from Scratch

### ISSUE THREAD

**Issue by ismaildawoodjee** [apache/superset#16801]
A clear and concise description of what the bug is:

`Python Functions` in the `Advanced Analytics` section of `Explore Chart` page doesn't appear when installing Superset from scratch (local installation with pip). 

After I installed `openpyxl` and `xlrd`, the `Upload Excel` option appears, but after installing `parquet` and `pyarrow`, `Upload a Columnar file` still doesn't appear.

### Expected results

what you expected to happen:

Expect all 3 options for file uploads to appear. Expect `Python Functions` to be available in the `Advanced Analytics` section.

### Actual results

No `Upload Excel` (unless I install `openpyxl` and `xlrd`), `Upload a Columnar file`, and no `Python Functions`.

#### Screenshots

![local_installation](https://user-images.githubusercontent.com/58870992/134449124-9b6c77d1-a325-4fbc-893a-4618e4c1be72.png)

#### How to reproduce the bug

1. Install [Superset from Scratch](https://superset.apache.org/docs/installation/installing-superset-from-scratch)
2. Login at `localhost:8088`
3.a. Create a chart. Go to Advanced Analytics and see that there's no Python Functions.
   b. Hover over `Data` tab, and see that there's no `Upload Excel` and `Upload a Columnar file` options
4. Stop server, run `pip install openpyxl xlrd parquet pyarrow`, run `superset db upgrade; superset init`, start server.
5. Go to `localhost:8088` and see that `Upload Excel` has appeared, but no `Upload a Columnar file`

### Environment

(please complete the following information):

- browser type and version: Firefox Version 92.0 (64-bit)
- superset version: `1.3.0`
- python version: `3.9.6`
- node.js version: `v14.16.0`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Add any other context about the problem here:

This bug doesn't appear when Installing Superset Locally Using Docker Compose.

**Comment by junlincc** [comment]
@ismaildawoodjee have you tried install via docker?

**Comment by ismaildawoodjee** [comment]
I installed using Docker first. No problems there. Then I tried out Installing from Scratch, and the functionalities I mentioned above do not appear.

**Comment by junlincc** [comment]
is there a reason you needed to uninstall Docker and build it from scratch?
