### ISSUE TITLE
[native filter] Filter indicator do not show correctly on all charts when time filter applied

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16806]
Filter indicator do not show correctly on all charts when time filter applied

### Expected results
Indicator show correctly when filter applied

### Actual results
Indicator do not show correctly when filter applied

#### Screenshots
issue 1: indicator did not show when filter applied but query is applied.
<img width="1789" alt="Screen Shot 2021-09-23 at 12 21 24 AM" src="https://user-images.githubusercontent.com/81597121/134470385-dbef1d74-290f-46bc-a52d-873f04a65270.png">

issue 2: indicator did not show when filter applied and query is not applied
<img width="1789" alt="Screen Shot 2021-09-23 at 12 23 11 AM" src="https://user-images.githubusercontent.com/81597121/134470685-fb45fd43-7896-4da6-adb6-7bb80a048a4f.png">

issue3: when clear filter, the indicator still exist and filter still show old actual value when no filter applied
<img width="1787" alt="Screen Shot 2021-09-23 at 12 45 39 AM" src="https://user-images.githubusercontent.com/81597121/134471633-981626af-c849-4563-aa0e-1468f4b533f6.png">

<img width="1787" alt="Screen Shot 2021-09-23 at 12 47 10 AM" src="https://user-images.githubusercontent.com/81597121/134471661-f7ff1ac1-4fee-4352-a213-9d3b66c7e72a.png">

#### How to reproduce the bug

1. Go to dashboard
2. create a time range filter
3. applied filter to all

### Environment

(please complete the following information):

- browser type and version:
- superset version:  2021.38.1 dev
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
regression from recent dashboard perf optimization work.

**Comment by jinghua-qa** [comment]
test case added
