### ISSUE TITLE
Add CA bundle to superset docker container

### ISSUE THREAD

**Issue by manishbansal8843** [apache/superset#16811]
I need to add root certificates to the superset container so that it can communicate to my secured authorization server.

As of now, i could not find any environment variable or mount path where i can add the certificates and same get updated to the `cacert.pem` at runtime. 

As of now, what i have done is, I logged into my container and appended my root.pem file to the certifi `cacert.pem` for which I found the path from `certifi.where()` command on python terminal inside the container which is `/usr/local/lib/python3.7/site-pacakges/certifi/cacert.pem`

Is there any standard way to do it?

**Comment by manishbansal8843** [comment]
Update: I tried passing `--ca-certs` param to the `gunicorn` command as well but it did not work.

**Comment by manishbansal8843** [comment]
Update 2: I also tried passing 2 commands in docker-compose `command` parameter where first command is to append my root.pem to cacerts.pem and then run gunicorn command but after that my container does not start. Not sure if its an issue with my docker command or something else.

**Comment by manishbansal8843** [comment]
Final Update: I created one sh file called as `start.sh` and mounted it on superset container with below code.

```
cat /app/docker/mycacert.pem >> /usr/local/lib/python3.7/site-pacakges/certifi/cacert.pem

gunicorn --bind  0.0.0.0:443 --access-logfile - --error-logfile - --workers 5 --worker-class gthread --threads 4 --timeout 200 --limit-request-line 4094 --limit-request-field_size 8190 'superset.app:create_app()'
```
Further, docker-compose.yml is modified and replaced command parameter as below.
`command: ["/my/mount/path/start.sh"]`

However, this feels like a hack and it would be great if some standard solution is made available. Thanks

**Comment by manisha-tanwar** [comment]
looking for same option with kubernetes installation.

**Comment by rusackas** [comment]
Taking a cue from stalebot here and closing this out since it's nearly a year old, and seems to represent more of a configuration issue than a still-standing bug. Holler if I'm misinterpreting and this needs a revisit.
