### ISSUE TITLE
Row level security in embedded charts [Guidance needed]

### ISSUE THREAD

**Issue by sadiqkhoja** [apache/superset#16812]
Hi,

I need some guidance on how to embed superset charts with row level security. Here is what I am thinking to do:

1- Create an user in superset for my custom application
2- When an user wants to see any chart, custom app sends its credentials to superset from backend and set the row level security RLS (where clause). A JWT token return to the front end
3- Front end passes JWT token to iFrame.

So the question is is it possible to set some session details to be used for RLS when logging in from external application?

**Comment by junlincc** [comment]
@amitmiran137 Hey fellow PMC, If you happen to know, please help. 🙏

**Comment by amitmiran137** [comment]
This is such an interesting topic for me these days . 
We have a few different solutions for that but lately we are considering a few other options to what would be the ultimate row level security solution .
I'll update here soon once we'll finish up with the details

**Comment by vedangparasnis** [comment]
@sadiqkhoja @amitmiran137  I have a question we are using OAUTH with flask using keycloak as authorization server. However, when my application tries to initiate a new session in superset on its behalf the browser based authorization flow works but the charts required re login (assuming keycloak does not work with xhr when token exchange is done) and yes we are also passing id which we want the role level security applied on it. (We dont send any token in iframe url) assuming global session is inititated.

**Comment by rusackas** [comment]
@amitmiran137 not sure if you are able to circle back to this, and @sadiqkhoja I'm not sure if this is still a pressing need. I'm tempted to close this ore move it to a Discussion if it's not an "issue" really, but I don't mean to be overly dismissive.

**Comment by rusackas** [comment]
Haven't heard anything in a couple weeks here, so I'm closing as a "won't fix." I'll still be happy to convert to a Q&A Discussion if needed.
