### ISSUE TITLE
Rate value totals in pivot table not works as the same way in table.

### ISSUE THREAD

**Issue by Kingflyinger** [apache/superset#16829]
rate value totals in pivot table not works as the same way in table.
when it changes in the future please let me know, it helps a lot 
![image](https://user-images.githubusercontent.com/41682019/134652726-caeb9960-62f7-4b21-8369-81dbc90fd043.png)

**Comment by junlincc** [comment]
Hi! I have a very hard time understanding the issue. can you please reopen the issue using the bug template. with screenshot in Superset? thank you for troubleshooting though.
