### ISSUE TITLE
[explore][Advanced Analytics] View sample show html when query percentage change in time series line chart

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16820]
`View sample` show html when query percentage change in time series line chart
#### How to reproduce the bug

1. use vehicle sales data and create a time series line chart 
   time column: orderdate
   time grain: month
   time range:2003-2004
   metrics: sum(sales)
   time comparison: 1 year later
   calculation type: percentage change
2. Click on 'View samples
3. See error

### Expected results

Show sample correctly

### Actual results

sample is showing html

#### Screenshots
<img width="1790" alt="Screen Shot 2021-09-23 at 2 22 10 PM" src="https://user-images.githubusercontent.com/81597121/134586798-598834b8-3831-4e3f-93ad-b0f6a90390b1.png">

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
@jinghua-qa is this still an issue, or shall we close it?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
