### ISSUE TITLE
Mixed Time-Series chart rendering issue

### ISSUE THREAD

**Issue by yongchand** [apache/superset#16834]
Unexpected error shows when rendering chart occasionally. 

### Expected results

Chart should show the rendering result

### Actual results

Occasionally, chart fails on rendering and shows "An error occurred while rendering the visualization: TypeError: Cannot read properties of undefined (reading 'data')"

#### Screenshots

<img width="1120" alt="Screen Shot 2021-09-24 at 8 03 26 PM" src="https://user-images.githubusercontent.com/43336767/134702697-62a247f6-c52f-4b2d-a0e5-b603e121188b.png">

#### How to reproduce the bug

1. Update to Superset 1.3 (specific commit_sha: 6d19de8f66e6409cc82d6d1e5db2496c1ca2290d)
2. Create a mixed timeseries chart
3. Render multiple times and check error 

### Environment

(please complete the following information):

- browser type and version: Chrome 93
- superset version: 1.3
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active: GLOBAL_ASYNC_QUERIES

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
hi! what do you mean by "rendering multiple times"?  is it only happening to said chart? can you reproduce it constantly? thanks!

**Comment by yongchand** [comment]
@junlincc So based on what we have found out until now, we found out that if cache does not exist, rendering mixed timeseries was totally fine. If cache exist, we found out that this error was reproduced. As explained on #15877 , we have turned on GLOBAL ASYNC QUERIES.

**Comment by junlincc** [comment]
Gotcha, thanks for reporting! another feature flag conflict 🤦🏾‍♀️
@villebro can you walk @stephenLYZ through the process of adding the support? Thanks!

**Comment by yongchand** [comment]
My coworker @yougyoung94 might know how to solve this issue

**Comment by suddjian** [comment]
@yongchand Happy to collab or review a PR

**Comment by yougyoung94** [comment]
@suddjian I opened a PR:):) Waiting for your review 🙏
