### ISSUE TITLE
Export/Import Error

### ISSUE THREAD

**Issue by Amanda-Chiang** [apache/superset#16848]
Error occurred when importing dashboard from Superset's latest version into Preset instance.
### Expected results

Import dashboard zip file successfully

### Actual results

Error pop up

#### Screenshots

See video
![ezgif com-gif-maker](https://user-images.githubusercontent.com/57576886/134837759-ed11cd58-6487-4b2a-ba34-abd8a469e704.gif)

#### How to reproduce the bug

1. Go to Superset dashboard and click export
2. Go to Preset dashboard and click import
3. Choose the zip file

### Environment

(please complete the following information):

- browser type and version: Google Chrome
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by betodealmeida** [comment]
@Amanda-Chiang are you able to share the ZIP file that's causing problems?

**Comment by yousoph** [comment]
Hi @Amanda-Chiang , are you still seeing this error with your import? If so, would you be able to share the zip file or more info about the dashboard so we can try to reproduce it? Thanks!

**Comment by rusackas** [comment]
@Amanda-Chiang we're assuming this is no longer an issue, so we're closing it. If indeed this is still somehow an issue, please let any of us on the thread here know, and we can re-open it, or you can open a new issue. Thanks!

**Comment by ssuyong2** [comment]
If you solved it, please tell me how..
