### ISSUE TITLE
[explore] when changing column of an existing filter, the existing filter value did not changed

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16844]
When changing column of an existing filter, the existing filter value did not changed, the new filter will still show previous filter values which are not exist in the new filter

### Expected results

when i change the column of an existing filter, i expect the old value can be remove 

### Actual results

when i change the column of an existing filter, old value did not remove

#### Screenshots

https://user-images.githubusercontent.com/81597121/134817660-10d9dd15-a150-4bdd-96f6-bf09ccc2b694.mov

#### How to reproduce the bug

1. Go to explore, select column A for filter and select value for column A and save
2. Go to filter and change column A to column B
3. Observe the filter value and see error

### Environment

(please complete the following information):

- browser type and version:
- superset version: superset 1.3 RC2
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
im not sure this is a regression from select refactoring or an old bug. @geido would you like to take a look?
