### ISSUE TITLE
 superset get all resource client

### ISSUE THREAD

**Issue by Fm371** [apache/superset#16841]
Hi

I created a dashboard in Superset. When I open it in the browser(chorom or firefox ) It takes all the resources(ram and cpu) of the client system and crashes the browser. 

- browser type and version: Google Chrome Version 92.0.4515.131
- superset version: 0.999.0dev
- python version:  3.8

**Comment by villebro** [comment]
To make this bug report more actionable for contributors, it would be very helpful if you could shed some more light on the dashboard in question (what type of charts you have, the datasets referenced, the database type, potential native filters etc). Better yet, providing clear reproduction steps would make it much easier to reproduce the bug locally, after which we could start working on a fix.

**Comment by rusackas** [comment]
Closing this since it's stale and no more actionable than it was a year and a half ago. Happy to revisit this if we can get updated context!
