### ISSUE TITLE
[dnd] reordering of multiple column/metrics is not working smoothly（superset 1.3 only）

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16846]
Reordering of multiple column/metrics is not working smoothly, some times can not drag a component to the desired order by dnd

### Expected results
can drag component to desired position for ordering

### Actual results

sometimes can not drag component to desired position for ordering

#### Screenshots

https://user-images.githubusercontent.com/81597121/134820334-40d6a271-42f9-4f5d-80d2-540f4f8ec61b.mov

#### How to reproduce the bug
Precondition: Turn on drag and drop
1. Go to explore
2. add multiple metric or add multiple column to filter
3. reordering the metrics or columns by dnd

### Environment

(please complete the following information):

- browser type and version:
- superset version: superset 1.3 RC2
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by stephenLYZ** [comment]
@jinghua-qa I tested it in my local master branch and it works fine. Is there more reproduce context?
