### ISSUE TITLE
why cant add dataset？

### ISSUE THREAD

**Issue by lctlover** [apache/superset#16842]
i add dataset ，but cant add or next？？？

like this。

![图片](https://user-images.githubusercontent.com/25808895/134790280-a9791bde-2524-4e17-82b7-34248eca1fb2.png)

**Comment by lctlover** [comment]
docker-compose -f docker-compose-non-dev.yml up

**Comment by akshay26031996** [comment]
Facing the same issue. Followed the steps on the docker hub, as well as tried starting using docker-compose.

**Comment by junlincc** [comment]
can you fill out the bug report template.... @akshay26031996 @lctlover ?

**Comment by akshay26031996** [comment]
https://github.com/apache/superset/issues/16864

**Comment by lctlover** [comment]
but i cant reappear this bug。
i reinstall n times；

and this not the table reason。



CREATE TABLE "mini"."app_behavior" (
"app_behavior_id" int4,
"create_src" text COLLATE "default",
"operator_id" int4,
"building_project_id" int4,
"create_time" timestamp(6),
"behavior_type" int4,
"behavior_content" text COLLATE "default",
"remark" text COLLATE "default",
"building_project_ids" text COLLATE "default",
"role_type" int4
)
WITH (OIDS=FALSE)
;

and now ，it is ok...
![图片](https://user-images.githubusercontent.com/25808895/135044202-d5a1e736-1953-4a0c-b81a-5869a23a110f.png)

**Comment by srinify** [comment]
hey @lctlover glad you were able to resolve this issue (even if it was by dark magic). Please re-open this / a new issue if you run into it again.

Closing for now :]
