### ISSUE TITLE
Id issues with import/export

### ISSUE THREAD

**Issue by kevinhodes** [apache/superset#16858]
- In docker container 1:  I created several dashboards pointing to a postgresql database. (Export 1)
- In docker container 2:  I imported the dashboards from "Export 1" and made a few changes but it was left mostly as it was.  Enabled VERSIONED_EXPORT and exported the whole thing again (Export 2).
- In docker container 3: Imported from "Export 2" and faced several issues.

### Expected results

Import without any issues.

### Actual results

- Issue 1 (Can´t import).

`Traceback (most recent call last):
  File "/app/superset/dashboards/commands/importers/dispatcher.py", line 58, in run
    command.run()
  File "/app/superset/commands/importers/v1/__init__.py", line 71, in run
    raise self.import_error() from ex
superset.dashboards.commands.exceptions.DashboardImportError: Import dashboard failed for an unknown reason
2021-09-11 17:46:25,228:ERROR:superset.dashboards.commands.importers.dispatcher:Error running import command
Traceback (most recent call last):
  File "/app/superset/commands/importers/v1/__init__.py", line 67, in run
    self._import(db.session, self._configs, self.overwrite)
  File "/app/superset/dashboards/commands/importers/v1/__init__.py", line 128, in _import
    config = update_id_refs(config, chart_ids, dataset_info)
  File "/app/superset/dashboards/commands/importers/v1/utils.py", line 106, in update_id_refs
    for old_id, value in default_filters.items()
  File "/app/superset/dashboards/commands/importers/v1/utils.py", line 106, in <dictcomp>
    for old_id, value in default_filters.items()
KeyError: 138`
This error was because Key 138 changed to 163
`"default_filters": "{\"163\": {\"cct\": [\"09PES0800E\"], \"turno\": [\"Matutino\"]}}",`
I cleared the default filters in container 2 and re-exported and the export went through.

- Issue 2 (Empty dashboards)

All the slices were there but with a message that the slice was making reference to a chart that it did not exist. (Sorry that the wording of the message is incorrect).  

- Issue 3 (List of charts was empty)

I tried to delete and recreate and recreate the slice but the list of charts was empty.  
To overcome the issue I created a new dashboard but the list still remained empty.  
The solution was to get into chart explorer and saved it to the new dashboard.

### Environment

(please complete the following information):

- browser type and version: chrome (Version 93.0.4577.82 (Official Build) (64-bit))
- superset version: latest (created: 2021-08-20T19:19:15.311631677Z)
- python version: 3.7.9
- node.js version: 
- any feature flags active:
    "DASHBOARD_NATIVE_FILTERS":False,
    "ENABLE_TEMPLATE_PROCESSING":True,
    "ROW_LEVEL_SECURITY":True,
    "VERSIONED_EXPORT": True

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
thank you so much for the detailed report, this is very helpful! @kevinhodes 
@betodealmeida can you take a look along with #16848 ? thanks! 🙏

**Comment by rusackas** [comment]
`VERSIONED_EXPORT` is True by default nowadays, and will be deprecated in 3.0, and removed in 4.0. I think since this thread hasn't been bumped in over a year, and many improvements have been made in this area, it's safe to close as inactive. If anyone is still facing this or has updated/simpler reproduction steps that may help folks diagnose it, we can most certainly re-open it.
