### ISSUE TITLE
Big Number visualization doesn't show decimal value?

### ISSUE THREAD

**Issue by norpriest** [apache/superset#16863]
It should be 4.25

How can I do to fix this?

![U](https://user-images.githubusercontent.com/72668447/135013920-730d5b43-fe8d-471a-8337-a2a3fa5842af.PNG)

**Comment by junlincc** [comment]
have you tried D3 format?

https://user-images.githubusercontent.com/67837651/135029854-09b30700-ec76-48b5-9c70-87d558fa7599.mov

**Comment by norpriest** [comment]
> have you tried D3 format?
> 
>  Screen.Recording.2021-09-27.at.10.42.05.PM.mov

its ok I got it now. Thanks
