### ISSUE TITLE
Unable to add dataset

### ISSUE THREAD

**Issue by akshay26031996** [apache/superset#16864]
When we try to add a dataset from the superset UI, the "Add" button is disabled.

#### How to reproduce the bug

1. Add `pyhive` in `docker/requirements-local.txt`
2. Run `docker-compose -f docker-compose-non-dev.yml up`
3. Connect to a database. I have connected with presto.
4. Click on Data -> Datasets
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10262118/135036767-4dbbaf57-6685-4227-835b-63cac30e405f.png">

4. Click on `+ Datasets`
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10262118/135037080-f22e56df-beb7-4305-ac54-b2cc28e664a7.png">

5. Fill in all the details. Still the Add button is disabled.
<img width="1440" alt="screenshot" src="https://user-images.githubusercontent.com/10262118/135035912-5a79840e-dbdf-44bb-806a-3da3a61414ae.png">

### Expected results

After filling in the required details we should be able to proceed with adding the datasets.

### Actual results

Add button is disabled.

### Environment

- browser type and version: Tested in both Firefox and Chrome
- superset version: `superset version`: Dev

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I am able to query the table in the SQL editor.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10262118/135038134-3870b91c-beb6-41ed-9652-b625b40ad6e0.png">

**Comment by yousoph** [comment]
Looks like the add button is disabled when you select the first table, but if you go back and select a second table from the dropdown, the add button gets enabled (as a temporary workaround)
