### ISSUE TITLE
DASHBOARD_CROSS_FILTER causes some bugs and performance issues

### ISSUE THREAD

**Issue by iercan** [apache/superset#16866]
Hi.
I was unable to edit filter scopes on dashboards and also when I changed time range and save as dashboard they weren't persistent. We were also experiencing very slow load when dashboard size gets bigger. 
After some test I realized this is because DASHBOARD_CROSS_FILTER flag enabled. After disabled it, dashboard get much faster and I can save scopes and times of filter. 

Although this flag listed as stable looks like it has serious bug and performance issue. 

#### How to reproduce the bug

1. Enable DASHBOARD_CROSS_FILTER in feature flag.
2. Add some filter box and chart to dashboard
2. Try to change filter scopes and default time range
3. Refresh dashboard

### Expected results

Scopes should be persistent
Time settings should be saved
Dashboard should load faster

### Actual results

Scopes are not saved
Time settings are not saved
Dashboard loads slow

### Environment

- browser type and version: Chrome 94
- superset version: using apache/superset:1.3 docker image
- enabled feature flags:

```
    "SQLLAB_BACKEND_PERSISTENCE": True,
    "THUMBNAILS": True,
    "THUMBNAILS_SQLA_LISTENERS": True,
    "ALERT_REPORTS": True,
    "DASHBOARD_NATIVE_FILTERS": True,
    "DASHBOARD_CROSS_FILTERS": True,
    "DASHBOARD_RBAC": True,
    "ENABLE_EXPLORE_DRAG_AND_DROP": True,
```

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
Hi @iercan thanks for reporting this issue! 

So there are _ issues here. 
- When Cross-filtering is enabled, dashboard perf is being affected 
  Question: 1. how large is your dashboard? number of charts, types of charts etc.
                   2. is it happening when you try to emit filters? or while you perform other tasks in dashboard, or just slow in 
                        general? 
- Unable to edit filter scope of NATIVE FILTER when Cross-filtering is enabled (?) or Cross-filter scope 
- Time range issue also happen only when Cross-filtering is enabled? or without it as well? 

@villebro let's wait for more information before jumping in

**Comment by junlincc** [comment]
Also, is there a specific reason you are still adding filterbox to the dashboard while native filter is available? these two are not compatible, especially on time filter. and we dont have plan to maintain the combination. can you try remove filter box to see if the time range issue still persist?

**Comment by iercan** [comment]
> Hi @iercan thanks for reporting this issue!
> 
> So there are _ issues here.
> 
> * When Cross-filtering is enabled, dashboard perf is being affected
>   Question: 1. how large is your dashboard? number of charts, types of charts etc.
>   2. is it happening when you try to emit filters? or while you perform other tasks in dashboard, or just slow in
>   general?

Dashboard has about 80 chart and 3 different filter box. It slows on loads and also navigating through tabs in the dashboard. and also while selecting filters
> * Unable to edit filter scope of NATIVE FILTER when Cross-filtering is enabled (?) or Cross-filter scope

Problem is not about native filter, we added filter boxes. 
> * Time range issue also happen only when Cross-filtering is enabled? or without it as well?

It happens when option is enabled. Again this is also for filter boxes, not native filter. 

> Also, is there a specific reason you are still adding filterbox to the dashboard while native filter is available? these two are not compatible, especially on time filter. and we dont have plan to maintain the combination. can you try remove filter box to see if the time range issue still persist?

We experienced very slow load and navigate with native filter when dahsboard gets too big. Thats why we decided to use filter boxes for big dashboards.

**Comment by junlincc** [comment]
@iercan thanks for the details! We suspect that having FilterBox coexist in Native filter enabled dashboard caused some of the issues your mention. Can you please remove your filterbox and create the same filters using native filters? and let us know if perf is still an issue. If so, we are happy to address. 

I'm pretty sure time range and scoping works as expected in that case. 

We are in the process of deprecating filterbox, im afraid that we can not help you troubleshoot Filterboxes are on your dashboard.

**Comment by kgabryje** [comment]
Thanks for clarifying! I've created a test dashboard with ~80 charts and ~15 native filters and the performance after load is pretty similar with and without cross filtering and native filters feature flags. Would you be able to share a recording of your dashboard so that I can reproduce it as closely as possible? If you can't, can you share some details like the layout of your dashboard (like the number of tabs, nested tabs, number of charts under each tab)?

**Comment by iercan** [comment]
I've tested 1.4.0 and problem still exist. We are still not able to use native filters for big dashboards.

**Comment by cyanoboy** [comment]
The same happens to me. 
Superset v1.3.2 with DASHBOARD_CROSS_FILTER enabled, big dashboards take a few seconds to switch from one tab to the other. By disabling DASHBOARD_CROSS_FILTER it works flawlessly.

**Comment by iercan** [comment]
I've tested 1.5.0rc3 and this issue looks resolved.

**Comment by kgabryje** [comment]
Glad that problem FINALLY went away @iercan 🙂

**Comment by iercan** [comment]
Native filter does not slowing dashboard now but we still can not save filter scopes (in case filter box used) if DASHBOARD_CROSS_FILTER enabled. At least we can migrate native filters to get rid of this. Thanks for the effort.

**Comment by bhargavi1234567890** [comment]
Hi Team,

I have couple of issues where i need your help to resolve.

1. I have enabled  DASHBOARD_CROSS_FILTER in config file, but not finding ENABLE DASHBOARD CROSS FILTERS in the charts to make use of drill down.
2. How to create red, amber, green symbol and color for the data in Superset (Table chart). Is there any option. Please provide any sample chart if available.
3. Is there any option to add external link to the chart. ( i want to show the react app table in the Superset dashboard. is it possible)

**Comment by kunitdmi** [comment]
> Hi Team,
> 
> I have couple of issues where i need your help to resolve.
> 
> 1. I have enabled  DASHBOARD_CROSS_FILTER in config file, but not finding ENABLE DASHBOARD CROSS FILTERS in the charts to make use of drill down.
> 2. How to create red, amber, green symbol and color for the data in Superset (Table chart). Is there any option. Please provide any sample chart if available.
> 3. Is there any option to add external link to the chart. ( i want to show the react app table in the Superset dashboard. is it possible)
>    ![Corss filter not visible](https://user-images.githubusercontent.com/117968382/203279671-9f286c63-2ac2-409a-9985-590ae4132885.PNG)

I deal with the same.. Use version 2.0.1 for apache/superset.

**Comment by villebro** [comment]
@kunitdmi the feature flag is called `DASHBOARD_CROSS_FILTERS`, can you check the exact spelling?
