### ISSUE TITLE
[color theme] color theme 'D3 category 10' is duplicated in explore

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16886]
color theme 'D3 category 10' is duplicated in explore

#### How to reproduce the bug

1. Go to explore
2. Click on color theme
3. See error

### Expected results
color theme is unique in the drop down menu

### Actual results

D3 category 10 is duplicated in color theme

#### Screenshots

<img width="321" alt="Screen Shot 2021-09-28 at 10 13 34 PM" src="https://user-images.githubusercontent.com/81597121/135207322-9e160945-4382-4811-9708-95f7225d9d2e.png">

### Environment

(please complete the following information):

- browser type and version:
- superset version: superset master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
This doesn't seem to be the case any more.
