### ISSUE TITLE
[native filter] when user undo delete of a native filter, the options under column is gone

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16887]
For value filter, when user undo delete of a native filter, the options under column is gone, however if user go to another filter and come back, the options will appear again

#### How to reproduce the bug

1. Create a value native filter
2. Click on delete and then undo delete
3. open dropdown menu for column

### Expected results

When user undo delete, the options in column dropdown list will not disappear

### Actual results

When user undo delete, the options in column dropdown list will disappear

#### Screenshots

https://user-images.githubusercontent.com/81597121/135208961-d9acdead-f57a-4ae7-9283-82e613bf3486.mov

### Environment

(please complete the following information):

- browser type and version:
- superset version:  superset master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Resolved by #17951
