### ISSUE TITLE
[color theme] stacked bar chart with 'Superset color' theme will change color when save to dashboard

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16891]
stacked bar chart with superset color theme will change color (within the same color theme) when save to dashboard

#### How to reproduce the bug

1. Go to a chart, pie chart or bar chart from example charts
2. Click on CUSTOMIZE panel and select 'Superset color theme'
3. Save the chart with superset color theme to dashboard

### Expected results
When save chart to dashboard, chart color did not change

### Actual results

When save chart to dashboard, chart color changed to other color within the same color theme

#### Screenshots

https://user-images.githubusercontent.com/81597121/135226103-a6b7ab5a-8010-4c4d-8103-886da3c67cdc.mov

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by jinghua-qa** [comment]
This issue also seen in pie chart

**Comment by geido** [comment]
@jinghua-qa my observation is that this issue affects all the charts not any chart in particular

**Comment by jinghua-qa** [comment]
It looks to me bar and area chart is the most inconsistent one amount popular charts, when add bar chart and area chart to dashboard the color change. I think i saw pie chart but i can not repro now.
<img width="1167" alt="Screen Shot 2021-10-01 at 1 36 28 AM" src="https://user-images.githubusercontent.com/81597121/135591181-2c3109df-272c-4423-80bb-e7cfa92a1c7d.png">
<img width="1140" alt="Screen Shot 2021-10-01 at 1 39 42 AM" src="https://user-images.githubusercontent.com/81597121/135591164-d43e56eb-4472-4347-bfa7-c05f5b66d062.png">

**Comment by geido** [comment]
I was sure that I have seen the issue affecting most of the charts. When saving the chart again after adding it to the dashboard, the color would change. However, I cannot reproduce it now and after re-testing, it seems to work fine for the charts that I tested so far.
