### ISSUE TITLE
Add a custom item in main menu

### ISSUE THREAD

**Issue by amitBhardwaj12** [apache/superset#16892]
How to reproduce the bug
<img width="1421" alt="Screenshot 2021-09-29 at 2 14 45 PM" src="https://user-images.githubusercontent.com/90375231/135235106-c44dc26c-70b1-4b9e-a01d-a325cbc61dd5.png">

Try to add any new item in menu.
If I add any new item in backend side for the menu its not visible.

Expected results
SQL lab menu should show a new item with the given name for newly added item

Actual results
Newly added item not appear

Checklist
I have reproduce the issue number of times.
I have checked the issue tracker for the same issue and I haven't found one similar.

Additional context
Approach  I have followed:  I have added the link into SQL Lab category as I want this new item in SQL Lab Category
appbuilder.add_link(
            __("Drift"),
            href="/superset/sqllab/drift/",
            icon="fa-search",
            category="SQL Lab",
        )

**Comment by rusackas** [comment]
Closing since this is stale, but I also think that this is more of a customization request than a bug report. I'd suggest taking this up in the #customizing-superset channel on Slack, or a Q&A discussion on the Discussions tab above. Thanks!

**Comment by ShaliniIruvuru** [comment]
Working as Expected.

![image](https://user-images.githubusercontent.com/115684419/225640487-560a9f22-6969-42b3-b729-7f80121353d1.png)
