### ISSUE TITLE
ApacheDrill: Column 'method__' is ambiguous

### ISSUE THREAD

**Issue by cxplonka** [apache/superset#16897]
Hello Superset-Team,

when i use time series chart to query apache drill then this statement(see bottom) is generated, but apache drill give me an error "VALIDATION ERROR: From line 17, column 37 to line 17, column 44: Column 'method__' is ambiguous". Everything works fine when we use "anon_1.method__". Is there a possiblity to fix this problem?

thanks and best greets
christian

```sql
SELECT NEARESTDATE(`eventDateTime`, 'DAY') AS __timestamp,
       `method` AS `method`,
       sum(duration) AS `SUM(duration)`
FROM
  (select *
   from dfs.`/data/server.log`
   where duration > 0) AS virtual_table
JOIN
  (SELECT `method` AS method__,
          sum(duration) AS mme_inner__
   FROM
     (select *
      from dfs.`/data/server.log`
      where duration > 0) AS virtual_table
   GROUP BY `method`
   ORDER BY mme_inner__ DESC
   LIMIT 5) AS anon_1 ON `method` = method__
GROUP BY `method`,
         NEARESTDATE(`eventDateTime`, 'DAY')
LIMIT 10000
```

**Comment by raupat** [comment]
A workaround for this problem ist proposed in #17035 by not setting up a series limit. The Join Subquery will not be added and therefore the error will not occur.

The missing "anon_1" reference in the join condition is however still a bug from my point of view, when using a series limit.

**Comment by rusackas** [comment]
Just noticing this issue has been inactive for quite some time. Can either of you confirm whether it's still worth keeping this issue open as of Superset 2.0.1?

**Comment by cxplonka** [comment]
It can be closed, im not look for it long time.
