### ISSUE TITLE
[feature_parity]Support series limits in Pivot Table v2

### ISSUE THREAD

**Issue by etr2460** [apache/superset#16901]
**Is your feature request related to a problem? Please describe.**
There's no way currently to limit the number of rows in a pivot table v2. It would be good to support series limit here like we do in other charts

**Describe the solution you'd like**
Allow the user to specify a series limit in the pivot table v2

to: @kgabryje @villebro @junlincc

**Comment by kgabryje** [comment]
@etr2460 Is that what you expect? (labels will be changed of course)

![image](https://user-images.githubusercontent.com/15073128/145188552-b47486e8-da5e-4fde-bd92-bfa4928875d3.png)
