### ISSUE TITLE
Add Quarter Functionality to DATETRUNC Function in Advanced Time Range

### ISSUE THREAD

**Issue by jamesrayoub** [apache/superset#16937]
**Is your feature request related to a problem? Please describe.**
When I want to display metrics at a quarterly grain, I sometimes want to restrict the time range to the last few quarters and not include the current quarter. Unlike other grains, I cannot truncate to the beginning of the quarter in the Advanced Time Range filter

**Describe the solution you'd like**
Ability to truncate by filter

**Describe alternatives you've considered**
Writing custom SQL filter which uses BigQueries date_trunc capabilities

**Additional context**
![image](https://user-images.githubusercontent.com/31777200/135655370-a1f8e1fa-85b5-46cc-9a22-ee3002927338.png)

**Comment by rusackas** [comment]
Closing this since we're moving feature requests from Issues over to Discussions (in the Ideas) tab. Please feel free to open it there if you're still clamoring for this. Thanks!
