### ISSUE TITLE
Pivot table summary returning wrong results 

### ISSUE THREAD

**Issue by djouallah** [apache/superset#16952]
I am using Preset Cloud, so not sure which version is used, as far as I can see Pivot table summary generate only 1 SQL Query, I would expect that it generate two.
- one for the rows
- another for the summary

see the results of the division which is wrong Actual/ Budget, I don't know how to tell superset to keep the same metric definition for the summary rows
![image](https://user-images.githubusercontent.com/12554469/135802536-bae2c468-7610-4061-8394-1a87bf4f0291.png)

**Comment by grafke** [comment]
+1

**Comment by rusackas** [comment]
I'm not so sure this is a common use case. The `Total (Sum)` row is just that, a sum of the values in the column. By that definition, this chart is quite correct. If you want to use these totals formulaically against each other, that seems like it would be adding spreadsheet functionality that goes beyond the typical scope of a pivot table. @kgabryje @villebro curious your thoughts on this, if they differ.

**Comment by djouallah** [comment]
yes, it is the default expectation how the measure works in any BI tools, I expect the summary row to respect the measure definition not doing a sum, if I want a sum, then I create a measure that explicitly say, for a summary row do a sum of a column

**Comment by robjuffermans** [comment]
@djouallah Correct me if I'm wrong but problem is summing up the percentages in the Progress column in the Total (sum) row, right?
This should be a weighted percentage. Summing percentages is useless.

**Comment by djouallah** [comment]
@robjuffermans what I am saying having an option to do a sum in the first place is a wrong,  I expect the summary row to respect the metric definition , that pretty much how any BI tools works (Tableau, PowerBI, Google Data Studio etc)

**Comment by djouallah** [comment]
something like this see the percentage works at all level even in the summary rows
![image](https://user-images.githubusercontent.com/12554469/142846300-774982ac-96a2-496a-b07f-483c9b25228a.png)

**Comment by robjuffermans** [comment]
exactly, that's what I'm missing also. @rusackas this should be regarded normal functionality for a pivot table from my point of view.

**Comment by rusackas** [comment]
CC @lauderbaugh and @yousoph in case you know how we can revisit this (and related issues) holistically. Adding @kgabryje since he's a SME on the implementation

**Comment by mtthsbrr** [comment]
@djouallah Did you find any workarounds already. I could imagine to build a chart per aggregation level but it feels far from perfect.

Ideally one can fold/unfold on all the dimension and (sub)totals should always respect the formula behind the metric instead of creating a sum of the metric results.

**Comment by wkolbnik** [comment]
+1

**Comment by jjlabuda** [comment]
+1
