### ISSUE TITLE
Boxplot only shows a `<NULL>` in x-axis

### ISSUE THREAD

**Issue by akizminet** [apache/superset#16951]
Boxplot only shows a `<NULL>` on the example chart.

Generated query:

```sql
SELECT DATE_TRUNC('day', year) AS year,
       region AS region,
       sum("SP_POP_TOTL") AS "sum__SP_POP_TOTL"
FROM wb_health_population
WHERE year >= TO_TIMESTAMP('1960-01-01 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.US')
  AND year < TO_TIMESTAMP('2021-10-04 04:03:20.000000', 'YYYY-MM-DD HH24:MI:SS.US')
GROUP BY DATE_TRUNC('day', year),
         region
LIMIT 50000;
```

#### How to reproduce the bug

1. Clone superset from github and start with `docker-compose -f docker-compose-non-dev.yml up -d`
2. Login and go to Chart. Choose Box plot
3. See error

### Expected results

Boxplot shows multiple regions in x-axis 

### Actual results

Boxplot only shows a NULL in x-axis

#### Screenshots

![image](https://user-images.githubusercontent.com/52618539/135791247-ab24309b-a410-42e5-bc27-773891b2e4fe.png)

### Environment

- browser type and version: Chrome 94
- superset version: `Superset 0.0.0dev`
- python version: `3.7.9`
- any feature flags active: None

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by bayesfactor** [comment]
I have the same issue with boxplot on v0.0.0dev, Firefox
