### ISSUE TITLE
[LEGACY DATASOURCE EDIT]Java script validation is missing when user enters a 3rd party Default endpoint

### ISSUE THREAD

**Issue by dharmic6** [apache/superset#16969]
#### How to reproduce the bug

1. Authenticate to the application as a valid user. From "Data" tab click on the "Datasets" link.
2. For any available data set click on "Edit" button.
3. Click on the "USE LEGACY DATASOURCE EDITOR" button.
4. Fill up the form. Use the JavaScript payload "javascript:alert('NetSPI')" as the value of the "Default Endpoint" field and submit the form.
5. Navigate back to the datasets page. Click on the dataset name.
6. Observe the JavaScript payload getting executed in the browser.

### Expected results

Validation is needed when user can add a malicious javascript inside the default endpoint.

### Actual results

Javascript is being executed without any errors.

#### Screenshots

![image](https://user-images.githubusercontent.com/25113963/135936330-6936b0c7-15a1-416b-8fba-9c921560b96d.png)

![image](https://user-images.githubusercontent.com/25113963/135936344-db4c79b2-608e-4977-a703-af66c2cd1c32.png)

![image](https://user-images.githubusercontent.com/25113963/135936358-409cd0a4-11bd-4421-b230-735996c2b810.png)

Now, Navigate back to the datasets page. Click on the dataset name and observe the JavaScript payload getting executed in the browser.

### Environment

(please complete the following information):

- browser type and version: chrome 94.0.4606.61
- superset version: 1.3
- python version: 3.7
- node.js version: v16.5.0
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@dharmic6 Unfortunately, we will not be able to fix any issues in the legacy datasource edit form. is it a specific reason that you are still using it, instead of the new modal?

**Comment by bnitesh** [comment]
@junlincc we are not using the old modal. This surfaced in our security scans so if we can provide a sunset date, will be fine to ignore. Thanks!

**Comment by rusackas** [comment]
Setting this feature flag to False and noting the deprecation was part of 2.0 I believe. We cannot remove the flag and functionality without it constituting a breaking change, meaning it won't happen until Superset 3.0 when such breaking changes can be introduced. The date for this is not set, but I think we can safely close this as won't-fix. If anyone DOES want to open up a PR around this, we can certainly review it nonetheless.
