### ISSUE TITLE
An authenticated user can gain unauthorized access to sensitive information or functionality by manipulating specific parameters within the application.

### ISSUE THREAD

**Issue by dharmic6** [apache/superset#16966]
1. Login As User A
2. Go to user profile /superset/profile/userA/
3. Change the url from user A to user B like (/superset/profile/userB/)
4. Now you can see the dashboards, charts and activities of userB.

### Expected results

User A is not supposed to see dashboards, charts unless user B or admin provides access to it.

### Actual results

An authenticated User Can see all other users' information including queries in charts.

Impacted urls:

/superset/profile/[UserName]/
/superset/recent_activity/[User_ID]/
/superset/created_dashboards/[User_ID]/
/superset/fave_slices/[User_ID]/
/superset/fave_dashboards/[User_ID]/
/superset/dashboard/[Dashboard_Name]/
/superset/created_slices/[User_ID]/

### Environment

(please complete the following information):

- browser type and version: chrome 94.0.4606.61
- superset version: 1.3
- python version: 3.7
- node.js version: v16.5.0
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X ] I have reproduced the issue with at least the latest released version of superset.
- [ X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
hi @dharmic6, please follow instruction in https://github.com/apache/superset/security/policy to file security related issue. 🙏 thanks for filing and understanding, I will have to close and wipe this issue for now.
