### ISSUE TITLE
[native filters] Filters displayed as out of scope for dashboard with nested tabs 

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#16972]
#### How to reproduce the bug

1. Create a new dashboard with nested tabs like this layout:
<img width="1199" alt="Screen Shot 2021-10-04 at 9 00 26 PM" src="https://user-images.githubusercontent.com/27990562/135958048-4b97e68e-6bb0-4026-87e4-32290d65a6f3.png">

Tab1 has 1 row of markdown, and a few nested Tabs.
In tab "nested Tab1" and "nested Tab2", each has only 1 chart.

2. Add a few filter components:
- State Filter: Apply to **nested tab 2**
- Time Filter: Apply to **nested tab 1**  and **nested tab 2**

![poia0jBbAf](https://user-images.githubusercontent.com/27990562/135958854-a36ed0af-6a87-4b6b-9d9a-30dc426197dd.gif)

3. Save dashboard
4. Go to dashboard list page, and visit the just created dashboard again: in nested tab 1, filter bar shows all filters out of scope.

![lW7lFlQwOC](https://user-images.githubusercontent.com/27990562/135958997-217e803c-2339-4675-9b56-913dc52f9a2d.gif)

#### Note ####
1. the filter scope data stored in dashboard metadata, is correct,
2. if i switch a few tabs back and forth, the in-scope filters and out-of-scope filters will display correct,
3. But if the landing tab has nested tab, it always show all filters are out of scope.

### Environment

(please complete the following information):

Latest master
- any feature flags active: dashboard filter component is enabled.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
I label this bug as P1, it looks scary since most users will feel their filter scope is totally messed up when they first seeing this issue. But probably this is only a small React render issue. 

@michael-s-molina @kgabryje @junlincc

**Comment by kgabryje** [comment]
@graceguo-supercat Thanks for adding very detailed description and repro steps, that cut down time spent on debugging by half! 👍

**Comment by jinghua-qa** [comment]
test case added
