### ISSUE TITLE
[dashboard][color theme] chart color are changed when refreshing dashboard

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16970]
chart color are changed when refreshing dashboard

#### How to reproduce the bug

1. Go to dashboard with multiple charts
2. Applied color theme to dashboard, for example supers color
2. Refresh dashboard
3. Observe color of each chart

### Expected results

Refresh dashboard did not change color of chart

### Actual results

Refresh dashboard did not change color of chart

#### Screenshots
https://user-images.githubusercontent.com/81597121/135937535-016cd613-cbf5-48a4-9849-7b0010a68176.mov

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@geido Let's create a new project in Projects for the color consistency ticket in one place

**Comment by geido** [comment]
Hello @amitmiran137 I can move this to the top of my list. No problem

**Comment by amitmiran137** [comment]
@geido  thanks friend ✌️

**Comment by D3nn3** [comment]
For us this happens again after migrating from 2.0.1 to 3.0.2. Can anyone else confirm?

**Comment by geido** [comment]
> For us this happens again after migrating from 2.0.1 to 3.0.2. Can anyone else confirm?

Thanks for the heads up. We are investigating the issue. Please try to disable AVOID_COLORS_COLLISION and see if that fixes it

**Comment by D3nn3** [comment]
Thanks for the reply @geido . I did test it and it seemed to have helped int that regard but this introduced a new issue: two different labels in the same chart could have the same color (which imho is even worse).

Seems to me like one has to decide with v3 between one of the two:
- changing colors of labels when refreshing a dashboard page
- or the possibility of two labels in one chart having the same color

I don't know how others handle it currently on their production environment but for us this is fairly annoying and we couldn't find any solution to it. I'm surprised that only few other people are reporting this issue

**Comment by shubham19may** [comment]
Happening with us also. @geido in SS 3.0.x

**Comment by zakaryanla** [comment]
Actual for 3.0.3

**Comment by progressive-scaler** [comment]
Actual for 3.1.0
I will test disabling AVOID_COLORS_COLLISION to see if its a valid workaround, or if the @D3nn3 collateral issue happens

**Comment by geido** [comment]
Thanks everyone for reporting these issues. Working on a longer term solution here https://github.com/apache/superset/pull/27439
