### ISSUE TITLE
[sql_lab] Sqllab results not sorting float column correctly

### ISSUE THREAD

**Issue by michellethomas** [apache/superset#16971]
When I query a `float` column and try to sort the values in the sqllab results, the values do not always get sorted correctly (especially for larger numbers).

#### How to reproduce the bug

1. Go to sqllab
2. Query a column along with a float column (this typically happens with larger numbers)
3. Click the results header to sort the float column and see some numbers not in the correct order

For example if you use the superset examples and query

```
SELECT status, year, sum(sales)
FROM main.cleaned_sales_data
GROUP BY status, year
```

The `sales` column is not always sorted in the correct order. It should be sorting smallest to largest but some of the values are not in the correct order (for example it shows `144729.96000000002` as smaller than `26260.210000000003 `).

### Expected results

Expected that float numbers should be sorted in the correct order.

### Actual results

Float column values are not always sorted correctly.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version `
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [] I have reproduced the issue with at least the latest released version of superset. (branch I am testing on is around a week old)
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
thanks @michellethomas, is it a regression in latest deploy?

**Comment by etr2460** [comment]
@junlincc this is not a recent regression, it's been around for a while now
