### ISSUE TITLE
Multiple Line Charts doesn't work since 1.3.1

### ISSUE THREAD

**Issue by alexryndin** [apache/superset#16989]
#### How to reproduce the bug

1. Go to Charts
2. Click on any Multiple Line Charts
3. See error. 
Actually after a little loading nothing is displayed except whole gray screen, and developer console shows a whole lot of errors, including, but not limiting to `Uncaught TypeError: colnames is undefined", "The above error occurred in the <DataTablesPane> component:`, `Warning: Each child in a list should have a unique "key" prop.`, `Warning: Failed prop type: The prop standalone is marked as required in ExploreViewContainer, but its value is null.`
![grim-06 10 2021-140730](https://user-images.githubusercontent.com/8342078/136191526-84dcf7dd-8dd6-41d2-83f6-b80850ba4a4d.png)

All of that happens with the latest dev version (https://github.com/apache/superset/commit/0b7704a2693dd4883020779b7cdeb8557d9de991)
Latest release (1.3.1) is also bug-prone, but dev console is much less descriptive and shows only `TypeError: e is undefined`
![grim-06 10 2021-142258](https://user-images.githubusercontent.com/8342078/136193495-e0c44a60-5fa2-4014-b0b2-8047749c5044.png)

 

### Expected results

I expect to see Multiple Line Chart

### Actual results

Superset shows Chart page which tries to load requested chart but instantly fails, resulting in gray screen 
![grim-06 10 2021-141200](https://user-images.githubusercontent.com/8342078/136192071-d7cb081e-8788-4635-9ac5-211132f09060.png)

### Environment

(please complete the following information):
I have got the environment using default docker-compose provided by repo (https://github.com/apache/superset/commit/0b7704a2693dd4883020779b7cdeb8557d9de991)
- browser type and version: Firefox 93
- superset version tested: latest dev AND 1.3.1 release

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [+] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [+] I have reproduced the issue with at least the latest released version of superset.
- [+] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
gotcha. I agree, it will be removed soon. 
@zhaoyongjie @villebro can we easily migrate the old multi-line chart to mixed time series chart?

**Comment by rusackas** [comment]
This issue seems to have gone cold, and doesn't seem to be corroborated by others. Also, it's true that we prefer the modern ECharts replacement these days and will work to deprecate the old version soon-ish. Closing this in hopes that all is well, but holler if this needs a revisit/reopening.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
