### ISSUE TITLE
[Explore] Owner can not change the name by just clicking on the title

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16995]
Owner can not click and edit on the chart name when open a saved chart, can only do click edit when creating a new chart.

#### How to reproduce the bug
1, Explore saved chart own by you
2, Hover mouse over to chart's title
3, Click on chart title

### Expected results
1,Should see tooltip "Click to edit"
2,Title is successfully edit and saved

### Actual results
There is no opportunity to edit chart title by click

#### Screenshots

![ezgif com-gif-maker (6)](https://user-images.githubusercontent.com/81597121/136271109-a8b5a14d-4ecd-49f3-b319-bee16b1e1fc4.gif)

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by belgren** [comment]
@junlincc @jinghua-qa I opened a [draft pr](https://github.com/apache/superset/pull/17047) to explicitly allow owners of the chart to edit the title. If this approach makes sense, I'll change the status from draft to ready.

**Comment by jayakrishnankk** [comment]
@jinghua-qa - I believe this can be closed since the related pull request is now merged. #17047

**Comment by junlincc** [comment]
@belgren Thank you for your contribution!
