### ISSUE TITLE
Sql lab not loading on fresh db init

### ISSUE THREAD

**Issue by manavjaiswal** [apache/superset#16996]
After fresh installation, chose not to load examples and added my own charts and a dashboard to test. Works fine till here. Then click on SQL Editor from under SQL Lab, the page does not load with no api calls as in the screenshot. I only see an error in console ( attached screenshot).

#### Screenshots

![Screen Shot 2021-10-06 at 1 50 47 PM](https://user-images.githubusercontent.com/13721953/136281355-c93c970d-edd1-4791-ba7d-e4036cbb6f12.jpg)

![Screen Shot 2021-10-06 at 1 51 16 PM](https://user-images.githubusercontent.com/13721953/136281380-7927a96b-496c-4dad-b039-8969cfdb65ed.jpg)

### Environment
(please complete the following information): dev

- browser type and version: Chrome Version 94.0.4606.61 (Official Build) (x86_64)
- superset version: GIT sha 87baac7650bdb6a8f8f82cf4992567a2c5c73cba Superset 0.0.0dev
- python version: 3.7.5
- node.js version: 14.18.0

**Comment by eschutho** [comment]
This is fixed now in the latest master.
