### ISSUE TITLE
[KPI with trendline] Time comparison isn't displayed when the value is stable and equal to 0

### ISSUE THREAD

**Issue by ValentinC-BR** [apache/superset#17012]
When a KPI is equal to 0 during 2 periods, the time comparison (+ 0%) isn't displayed

#### How to reproduce the bug

1. Create a KPI with trendline
2. Write "0" in Metrics / Custom SQL
3. Chose time comparison period = 1
4. Run

### Expected results

"+ 0%" (and the subheader !) should be displayed next to the number

### Actual results

There is no subheader nor time comparison.
However, this works with stable trendlines not equal to 0

#### Screenshots

![image](https://user-images.githubusercontent.com/79460908/136375628-4484b621-13f5-4ab7-bff0-20863a961fdd.png)

![image](https://user-images.githubusercontent.com/79460908/136375819-7208f00b-5b08-4c28-9ef5-c3b57ba139b7.png)

### Environment

(please complete the following information):

- browser type and version: Google Chrome Version 94.0.4606.71 (Oficial build) (x86_64)
- superset version: 1.3.0
- python version: 3.7.9
- node.js version: doesn't apply, I run on Kubernetes, using gunicorn as server
- source : AWS Athena
- any feature flags active: /

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by ValentinC-BR** [comment]
I may have been too evasive on this point.
What would be nice would be to display a subheader whether there is a change or not.

Otherwise, we have this kind of graphical incoherences : 
![image](https://user-images.githubusercontent.com/79460908/164183033-82220197-09fa-44cd-9f6e-007d1e8ea0cd.png)

**Comment by rusackas** [comment]
This looks to be resolved by the linked PR, so I'll go ahead and close it. If I'm misinterpreting here, say the word and we can re-open this :)
