### ISSUE TITLE
Chart config is reset when changing the datasource

### ISSUE THREAD

**Issue by ValentinC-BR** [apache/superset#17010]
The chart configuration (time column and grain, metrics, filters, etc.) is lost if the dataset (= source table) is changed.

#### How to reproduce the bug

1. Edit a chart (or create a new one)
2. Click on change dataset
3. Choose another dataset
4. See error (the configuration is lost)

### Expected results

The chart configuration should remain unchanged

### Actual results

The chart configuration is lost

#### Screenshots

![image](https://user-images.githubusercontent.com/79460908/136372755-f9d4d5ec-8dac-431a-ab88-7b855817fe4f.png)

### Environment

(please complete the following information):

- browser type and version: Google Chrome Version 94.0.4606.71 (Oficial build) (x86_64)
- superset version: 1.3.0
- python version:  3.7.9
- node.js version: doesn't apply, I run on Kubernetes, using gunicorn as server
- source : AWS Athena
- any feature flags active: /

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

This bug wasn't present in Superset v1.1

**Comment by ValentinC-BR** [comment]
What's more, we could previously (in v.1.1) change the datasource and use a pretty different table, and only the missing column was "broken". All other config parameters (dimensions to group by, filters, etc.) remained functional.

**Comment by rusackas** [comment]
That's an interesting use case. My recollection (which I'll try to confirm) is that the nuking of the fields when switching dataset is by design. Almost always, a full reset is in order to prevent things from breaking. But, we can certainly take a look at adding/enhancing logic here to clear things only *if* there's not an (exact?) match of schema. 🤔

**Comment by nytai** [comment]
+1 on this issue, it's quite common for orgs to have multiple datasets that are identical in schema but different data size (eg, test, staging, production). A common workflow is to build charts against a test dataset then switch it over to prod once the chart is built as chart building does require running  lots of queries which might be expensive against a larger dataset.

**Comment by ChengzhiZhao** [comment]
+1 on this one. This is still a very useful feature, we have multiple environments with similar columns and it saves a lot of time copying from an existing chart to a new one in the old version. To us, it is users' responsibility to validate after copying and superset can provide error would be helpful. Could we should give warning if the schema somehow doesn't match but still enable this feature?

**Comment by kasiazjc** [comment]
Hi! Hope I am understanding the problem well (if not - let me know) and would like to propose solution. 

When user is changing dataset or chart type, by default we keep the control panel/chart settings if possible, but we would give them a possibility to clear the form. There may be cases in which the settings would be lost (controls do not match, etc). I think having two types of banners in the control panel could help. 

_In short this would be the solution (components):_ 

![image](https://user-images.githubusercontent.com/36897697/146029563-b8a9d3cf-3b5d-48f4-ba9a-40b526970572.png)

_Flow and placement:_ 

![image](https://user-images.githubusercontent.com/36897697/146030262-2b3d217b-8f67-44ad-860e-0ecdc4f39bd7.png)

![image](https://user-images.githubusercontent.com/36897697/146030296-5fecb997-b7b8-4c73-ac5b-24ae2885f39a.png)

![confirmation](https://user-images.githubusercontent.com/36897697/146030855-aaf67e5a-8794-4e0b-9c46-86c962c86870.gif)

![ezgif-4-8ae7abb172ed](https://user-images.githubusercontent.com/36897697/146030874-06327330-7e8a-4d1d-8ebf-5600d98bad17.gif)

**Comment by imbra** [comment]
+1 on this issue, same behavior as @ValentinC-BR described (except for version 1.32). This worked in 1.2. Has the design changed or is this a bug?

**Comment by ValentinC-BR** [comment]
Up here.

I've tested the 1.5.

When I change my dataset, I ether get a message saying "the chart configuration couldn't be kept" (or something like that) or I get a message saying "successfully kept the config) but the config is almost reset : 

### The Original chart
![Capture d’écran 2022-06-14 à 13 22 55](https://user-images.githubusercontent.com/79460908/173566437-ba918cb5-7942-4f2f-8846-a560cfb9b4eb.png)

### When changing the dataset (same structure, same name)
![Capture d’écran 2022-06-14 à 13 23 15](https://user-images.githubusercontent.com/79460908/173566459-3dd35f3e-da9b-4ea5-bad0-70e395e54a8c.png)

**Comment by rusackas** [comment]
This has improved quite a bit since this thread was last touched. If people are still encountering this in current versions (3.x) please open a new Issue with reproducible examples, or open a PR to address the problem(s). Thank you!
