### ISSUE TITLE
CLIENT_CACHE flag in superset 1.2 breaks the dataset in explore page

### ISSUE THREAD

**Issue by kevinwen2k** [apache/superset#17021]
Hi guys, I found a bug with the flag CLIENT_CACHE in config.py that break the explore page (/superset/explore/?form_data=%7B"viz_type"%3A"table"%2C"datasource"%3A"281__table"%2C"url_params" ). Here’s the step to reproduce:

1. In superset/config.y, set the flag to true by "CLIENT_CACHE": True, .
2. Restart server (superset/gunicorn).
3. Go to Dataset list page (/tablemodelview/list/).
4. Click on one of the dataset and you will land on the explore page (/superset/explore/).
5. Under VISUALIZATION TYPE, change Table to any other type, like Line Chart.
6. An error message pops up as screenshot below.

We’re using superset 1.2 and have the redis server used for caching. It happens on Mac/Linux with both superset and gunicorn.

I tracked down a little bit and found out that it’s because the datasource_id in the url (281__table) can’t be captured. Hope the information here is enough for the team to work on. Thanks!
![Screen Shot 2021-10-04 at 12 42 53 AM](https://user-images.githubusercontent.com/4207782/136442333-f90f7ba7-ba56-45bd-b403-76921e3e9727.png)

**Comment by rusackas** [comment]
Closing this as stale since it hasn't been corroborated or prioritized for over a year, plus we no longer officially support that version of Superset. if you can validate that this still takes place in 2.0.1, we're happy to reopen and investigate. Thanks!
