### ISSUE TITLE
Examples do not have datasource field via API

### ISSUE THREAD

**Issue by alfmarcua** [apache/superset#17032]
In a fresh install from scratch, after loading superset examples, those examples do not have the field datasource from /api/v1/chart/{id}. If we create a new chart, it appears correctly.

### Expected results

Example's charts should have datasource field when accessing them via API: /api/v1/chart/{id}.

### Actual results

Only new charts have datasource  field when accessing them via API: /api/v1/chart/{id}.

### Environment

(please complete the following information):

- superset version: 1.3.1
- python version: 3.8.5
- node.js version: 12.22.6

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing as stale since this has been open with no discussion/corroboration for over a year. Happy to re-open if this is still occurring in current-era Superset.
