### ISSUE TITLE
[Native filter] Numerical filter can not select when the column has value range 0-1

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#17043]
In my dataset, column value is from 0-1, when i create numerical filter using that column, i can not select on the filter range.

#### How to reproduce the bug
Precondition:
Have column with value from 0-1
1. Go to native filter and create numerical filter using the column with value 0-1
2. Try adjust the filter range
3. See error

### Expected results

Numerical filter can work with column value 0-1

### Actual results

Numerical filter can not be selected with column value 0-1

#### Screenshots

https://user-images.githubusercontent.com/81597121/136623959-08362543-dd1d-42c7-b1c9-f5f556cc2067.mov

### Environment

(please complete the following information):

- browser type and version: chrome
- superset version: master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by stevetracvc** [comment]
This is related to an enhancement I'm proposing. The Select component has a step size option, but it isn't implemented in the UI. See #16591

**Comment by rusackas** [comment]
@stephenLYZ wondered if you have any insights here...

**Comment by rusackas** [comment]
Thanks for the PR to fix this @stevetracvc - I think your open PR solves it. Also, thanks @geido for helping that PR through. I'll assign this issue to both of you since you seem to have it in-hand :)

**Comment by rusackas** [comment]
Just updating this thread to mention that @stevetracvc is hoping to revisit a PR to close this issue out, and mark the thread as active again.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
