### ISSUE TITLE
[native filters][cascading filter] Parent level filter component is hidden 

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#17053]
#### How to reproduce the bug

1. Create a new dashboard with native filters like this:

<img width="1451" alt="Screen Shot 2021-10-10 at 8 29 59 PM" src="https://user-images.githubusercontent.com/27990562/136729287-b717944c-6426-4cc1-8378-af55171942d0.png">

in the dashboard, 1 chart is only filtered by "Region", 1 chart is only filtered by "Country".  Country filter is dependent on Country filter.

3. Open dashboard, you will only see "Region" filter.
4. select a value for region filter, you will only see "Country" filter.
5. Things became even worse, if multiple children filters depends on one parent filter, but children filters are not in the same scope (out of scope children filters should be folded in the filter bar).

### Expected results

Since both "Region" and "Country" filter are used in dashboard, it should all show up in the filter bar.

### Environment

Latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

CC @michael-s-molina @junlincc @rusackas Since we are redesign / fix cascading filter behavior, please consider this use case.

**Comment by rumbin** [comment]
I just stumbled on this issue in 1.4.0.
That's really a pretty awkward bug, as newbie users will be easily confused by this.
On the other hand, if we implement the dashboard filters in a non-cascading fashion, users will be confused by filter options that will not have intersecting result sets.

Is there any progress on the redesign?

**Comment by rusackas** [comment]
This doesn't appear to be a problem anymore. Closing as resolved.
