### ISSUE TITLE
Apache Impala Error is not descreptive enough 

### ISSUE THREAD

**Issue by gregmazur** [apache/superset#17058]
#### How to reproduce the bug

1. Go to 'SQL Lab'
2. Click on 'Run' for a query that has certain number of rows, usually more then 100 rows
`2021-10-11 14:41:41,504 WARNING: superset.views.base: [SupersetError(message='impala error: bytes expected', error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'Apache Impala', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
Traceback (most recent call last):
  File "/home/superset/venv/lib/python3.7/site-packages/superset/views/base.py", line 204, in wraps
    return f(self, *args, **kwargs)
  File "/home/superset/venv/lib/python3.7/site-packages/superset/utils/log.py", line 241, in wrapper
    value = f(*args, **kwargs)
  File "/home/superset/venv/lib/python3.7/site-packages/superset/views/core.py", line 2573, in sql_json
    return self.sql_json_exec(request.json, log_params)
  File "/home/superset/venv/lib/python3.7/site-packages/superset/views/core.py", line 2762, in sql_json_exec
    session, rendered_query, query, expand_data, log_params
  File "/home/superset/venv/lib/python3.7/site-packages/superset/views/core.py", line 2558, in _sql_json_sync
    [SupersetError(**params) for params in data["errors"]]
superset.exceptions.SupersetErrorsException: [SupersetError(message='impala error: bytes expected', error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'Apache Impala', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
Triggering query_id: 2447`

### Expected results

result. Or at least more detail stacktrace to investigate with impyla as there is no exception on Impala log

### Actual results

Apache Impala Error

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: `superset 1.3.1`
- python version: `python -3.7`
- any feature flags active: more descriptive stack trace

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

trying to connect to Impala 

Docker image python:3.7.9
impyla==0.15.0
thrift==0.13.0
thrift-sasl==0.4.2
thriftpy2==0.4.0

**Comment by rusackas** [comment]
Closing as stale since this has gone untouched for so long, but also because this in reference to a VERY old version of Superset. If this issue still persists in Superset 2.0.1, we can revisit/reopen, or open a new Issue with updated context. Thanks!
