### ISSUE TITLE
The results returned by the superset and clickhouse clients are different, and the client is correct

### ISSUE THREAD

**Issue by liumengkai** [apache/superset#17073]
superset 1.3.0
jdbc:clickhouse-driver==0.2.0 clickhouse-sqlalchemy==0.1.6

I have two fields 'pid' and 'eid'

1.group by pid & eid,I got data like this（Part of the data）
![image](https://user-images.githubusercontent.com/31892927/136934599-14c5f294-e79b-4838-abed-92e768860c89.png)

2.add fliter  'pid in 6909' then run the query ,I got data like this, only one row , but I should get at least two rows for eid = '302' or '304'

![image](https://user-images.githubusercontent.com/31892927/137079405-c7c072be-18b9-49c3-ba74-9176fda167d9.png)

![image](https://user-images.githubusercontent.com/31892927/136934985-4ce7caed-3174-43a8-bcec-d39a7688a9aa.png)

3.view query and run it in client
![image](https://user-images.githubusercontent.com/31892927/137079545-43d74b18-6393-4c2f-bfd1-4a1acd48c2d9.png)

we can get diferent values from superset and client,maybe is the jdbc bug,I am not sure. Its there anyone else has something about this?

**Comment by zhaoyongjie** [comment]
> superset 1.3.0 jdbc:clickhouse-driver==0.2.0 clickhouse-sqlalchemy==0.1.6 A clear and concise description of what the bug is.
> 
> I have two fields 'pid' and 'eid'
> 
> 1.group by pid & eid,I got data like this（Part of the data） ![image](https://user-images.githubusercontent.com/31892927/136934599-14c5f294-e79b-4838-abed-92e768860c89.png)
> 
> 2.add fliter 'pid in 6909' then run the query ,I got data like this, only one row , but I should get at least two rows for eid = '302' or '304'
> 
> ![image](https://user-images.githubusercontent.com/31892927/136947927-ca5d63ea-e87a-49e7-89e0-c5f3e4939076.png)
> 
> ![image](https://user-images.githubusercontent.com/31892927/136934985-4ce7caed-3174-43a8-bcec-d39a7688a9aa.png)
> 
> 3.view query and run it in client ![image](https://user-images.githubusercontent.com/31892927/136935863-4b7f4716-bd1e-480c-9cf7-179dbe049764.png)
> 
> we can get diferent values from superset and client,maybe is the jdbc bug,I am not sure. Its there anyone else has something about this?

Could you post SQL generation from Superset? Did you have `eid == 303` records?

**Comment by chen-ABC** [comment]
@liumengkai    you can see this issue:  https://github.com/xzkostyan/clickhouse-sqlalchemy/issues/14

btw:
add FORMAT TabSeparatedWithNamesAndTypes 
![image](https://user-images.githubusercontent.com/30097790/137072158-3f6c6dbe-bccd-4eb6-959e-0bcd4339719d.png)

sqllab retuen data is correct
![image](https://user-images.githubusercontent.com/30097790/137072382-da1ef583-96b2-4d8d-9e41-7a5d9286960e.png)

**Comment by liumengkai** [comment]
@chen-ABC thanks !
That's exactly what I want , not the filter problem,  after change my clickhouse url like 
 'clickhouse+native://username:password@hostname/default' Everything works fine!
By the way,There are some errors in the information in the picture I submitted for the first time. They are different screenshots of the two queries. I have modified them. sorry about that:-)
