### ISSUE TITLE
[chart viz][heatmap] Max and min value in heat map show 100% and 0%

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#17071]
Max and min value in heat map show 100% and 0% in heatmap tooltip, which seems in accurate.

#### How to reproduce the bug

1. Go to cleaned sales data, open in explore
2. Select  following for explore options:
    viz type: heatmap,
    time column: order_date,
    X axis: country, 
    Y axis: year, 
    Metrics: avg(sales)    
3. Select show percentage and legend, leave other option as default.
4. Run query and see error

### Expected results

Max and Min value show corresponding percentage in tooltip

### Actual results

Max and Min value show 100% and 0% in tooltip

#### Screenshots

<img width="1775" alt="Screen Shot 2021-10-12 at 12 49 46 AM" src="https://user-images.githubusercontent.com/81597121/136915243-7c554c8c-96e8-4d52-8340-d90fb4a976e4.png">
<img width="1785" alt="Screen Shot 2021-10-12 at 12 49 55 AM" src="https://user-images.githubusercontent.com/81597121/136915254-f4b01fa2-f3b4-4bb1-97e6-e014fb32d125.png">
Query and data return:
<img width="1792" alt="Screen Shot 2021-10-12 at 11 50 16 AM" src="https://user-images.githubusercontent.com/81597121/137012606-8053eda3-631d-45a9-a6ac-94583b65ae74.png">

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
@yousoph and others did a lot of digging in here, and validated that things seem to be working. We added some updates to the UI to clarify some of the math involved. In short, I think this issue is effectively closable. I might be wrong about this, and the plugin probably needs some holistic revisiting of the UI, so please feel free to re-open this if you want to keep it around :D
