### ISSUE TITLE
[Urgent] Unable to load superset stuck in welcome page post login

### ISSUE THREAD

**Issue by Maannniii** [apache/superset#17076]
Superset docker-compose deployment not proceeding after login. Returns 404 for  `/static/assets/images/loading.gif`

#### How to reproduce the bug
1. Clone superset repo.
2. `cd superset` and use `docker-compose up -d` to bring up containers.
3. Open developer tools and log in to Superset with admin creds.
4. Post login it redirects to http://localhost:8088/superset/welcome/ and is stuck there

### Expected results

Should Proceed to further screens.

### Actual results

Page is stuck at http://localhost:8088/superset/welcome/ and in developer tools, under Network we can see http://localhost:8088/static/assets/images/loading.gif returning 404.

#### Screenshots

![image](https://user-images.githubusercontent.com/24808028/137004997-1aa95c85-32c6-4885-aff4-62c91d15b3e6.png)

### Environment

- browser type and version: Chrome - Version 94.0.4606.61 (Official Build) (64-bit)
- superset version: Observed in docker images on both `apache/superset:latest-dev (sha256:a430759eb60d3dc1ddf905eb5b3afdeccdd17c8ece7370c71901ed1b68f5fbbb)` and `apache/superset:latest (sha256:f7afd84becc688f239228b2460910e316c1e140baf943115c3eca1be00ef6ccc)`
- python version: `3.8.12` (python verso=ion found in apache/superset:latest-dev image)
- node.js version: `node:16` (sha256:ed7bbdf4d76e3083f22827edc444b061b6562cb08341be973bfde0a972b65272)(docker image)
- any feature flags active: not sure. nothing has been changed in code/config post cloning.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I have cloned the repo and used docker-compose to bring up the system. I can also see that containers superset_worker_beat, superset_worker to be unhealthy. 
![image](https://user-images.githubusercontent.com/24808028/137006198-f05d2242-0605-4f92-a9d2-27545e8303fb.png)

### Superset app logs
```
127.0.0.1 - - [12/Oct/2021 18:00:24] "GET /health HTTP/1.1" 200 -
2021-10-12 18:00:24,588:INFO:werkzeug:127.0.0.1 - - [12/Oct/2021 18:00:24] "GET /health HTTP/1.1" 200 -
172.25.0.1 - - [12/Oct/2021 18:00:25] "GET / HTTP/1.1" 302 -
2021-10-12 18:00:25,596:INFO:werkzeug:172.25.0.1 - - [12/Oct/2021 18:00:25] "GET / HTTP/1.1" 302 -
2021-10-12 18:00:25,791:DEBUG:superset.stats_logger:[stats_logger] (incr) welcome
172.25.0.1 - - [12/Oct/2021 18:00:25] "GET /superset/welcome/ HTTP/1.1" 200 -
2021-10-12 18:00:25,818:INFO:werkzeug:172.25.0.1 - - [12/Oct/2021 18:00:25] "GET /superset/welcome/ HTTP/1.1" 200 -
2021-10-12 18:00:25,894:WARNING:superset.views.base:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
172.25.0.1 - - [12/Oct/2021 18:00:25] "GET /static/assets/images/loading.gif HTTP/1.1" 404 -
2021-10-12 18:00:25,895:INFO:werkzeug:172.25.0.1 - - [12/Oct/2021 18:00:25] "GET /static/assets/images/loading.gif HTTP/1.1" 404 -
```

**Comment by jomach** [comment]
+1 here

**Comment by sukupandachu** [comment]
+1 here too, installed yesterday and bumped into the same issue
Ubuntu server 20.04, Docker

**Comment by jomach** [comment]
I had the same issue. Wait for 10 or 15 minutes then npm has installed all packages. This is imho a bug

**Comment by maartenbreddels** [comment]
Docker didn't work for me, I checked out the `docker/docker-frontend.sh` script, and ran those commands manually. i.e.:
```
# get nodejs from conda-forge in my case
conda install -c conda-forge nodejs
cd superset-frontend
npm install -f --no-optional --global webpack webpack-cli
npm install -f --no-optional
npm run dev
```

My guess is some of the init scripts should have run this, but because nodejs is not installed it skipped it. I guess the installation docs can be improved on this.

**Comment by jasonoberme** [comment]
> I had the same issue. Wait for 10 or 15 minutes then npm has installed all packages. This is imho a bug

Agree with this feedback. +1 for me.

**Comment by jasonoberme** [comment]
> Docker didn't work for me, I checked out the `docker/docker-frontend.sh` script, and ran those commands manually. i.e.:
> 
> ```
> # get nodejs from conda-forge in my case
> conda install -c conda-forge nodejs
> cd superset-frontend
> npm install -f --no-optional --global webpack webpack-cli
> npm install -f --no-optional
> npm run dev
> ```
> 
> My guess is some of the init scripts should have run this, but because nodejs is not installed it skipped it. I guess the installation docs can be improved on this.

To run these I had to first run:
`export NODE_OPTIONS=--openssl-legacy-provider`

**Comment by cdutr** [comment]
I am getting the same error here. After waiting around 20 min it finished installing and got an error with webpack installation, on `superset_node`:

```superset_node            | webpack 5.52.1 compiled with 48 errors and 9 warnings in 138433 ms```

This is the kind of problem that discourages a lot of people who are having their first contact with the project following the tutorial. I would like to fix it, is anyone already working on it? Any suggestion on the best approach?

Comment: I didn't have this issue when running `docker-compose-non-dev.yml`.

**Comment by nikhil-kuyya** [comment]
can you share the logs of superset_node.

**Comment by nikhil-kuyya** [comment]
if you see something fail in the installation of packages. 
for more removing node_modules working.
Also if you  see something related to [CYPRESS INSTALL ISSUE](https://apache-superset.slack.com/archives/C0170U650CQ/p1643276871208900)
add this to environment : CYPRESS_CACHE_FOLDER='/app/.cache/Cypress'

**Comment by pa-mike** [comment]
> Docker didn't work for me, I checked out the `docker/docker-frontend.sh` script, and ran those commands manually. i.e.:
> 
> ```
> # get nodejs from conda-forge in my case
> conda install -c conda-forge nodejs
> cd superset-frontend
> npm install -f --no-optional --global webpack webpack-cli
> npm install -f --no-optional
> npm run dev
> ```
> 
> My guess is some of the init scripts should have run this, but because nodejs is not installed it skipped it. I guess the installation docs can be improved on this.

I had this same issue, running those node items solved my lockup on docker-compose. Looks like non-dev works fine, but the dev docker-compose has this challenge.

> This is the kind of problem that discourages a lot of people who are having their first contact with the project following the tutorial. I would like to fix it, is anyone already working on it? Any suggestion on the best approach?

Agree this issue is a bit discouraging, requires getting your hands dirty.

**Comment by bhowmik23** [comment]
I think the problem was solve by following this steps:
1. Remove Node stage codes from Dockerfile
2. Remove node_modules from superset-frontend dir if exist
3. Run cd superset-frontend in cmd
4. Run npm install&&npm run dev
5. Run docker-compose up
Hopefully it will be work

**Comment by muhsinfazal** [comment]
This worked for me `docker-compose -f docker-compose-non-dev.yml up`

**Comment by Paulo456** [comment]
the problem is in the image of the js node. To fix it, you need to fix version nodejs . to do that u need to fix the file docker/docker-frontend.sh like this:
.....
apt install -y chromium
# add new strings 
apt install -y npm
npm install npm -g
npm install -g n
n 16.18.1

n will install node js with version 16.18.1 .  by the way npm also need some packages to start correctly

**Comment by SyakeerRahman** [comment]
This worked for me docker-compose -f docker-compose-non-dev.yml up.  Thank you @sukupandachu

**Comment by krakzk** [comment]
How can we get this in dev, running docker-compose up?

**Comment by sfirke** [comment]
I'm closing this old issue as it pertains to a resolved issue from 2021-22 and even if a new version of this problem occurs in the future, it would have a different cause.  Folks who experience something similar should please search for a newer issue and, if none exists, either post in the Superset Slack chat or create a new issue if you believe it's a new bug.

**Comment by avnav88** [comment]
> I'm closing this old issue as it pertains to a resolved issue from 2021-22 and even if a new version of this problem occurs in the future, it would have a different cause. Folks who experience something similar should please search for a newer issue and, if none exists, either post in the Superset Slack chat or create a new issue if you believe it's a new bug.

i'm having this same exact issue...:
https://github.com/apache/superset/issues/24579#issuecomment-1662806410

**Comment by sfirke** [comment]
That doesn't seem like the same issue as this old one, your error code there is `The CSRF session token is missing` and there's no mention of CSRF in any of the posts on this issue.  But I'm glad you found that issue, that one does seem like the right place to discuss the problem you're having.

**Comment by liisaxin** [comment]
changing the node verison to v16.9.1  can help u

**Comment by vaguptaqw** [comment]
i am facing the same issue as reported. i tried **docker-compose -f docker-compose-non-dev.yml up** it worked, but now while logging in using admin id, it does not go through. anyone help on this please.

**Comment by Captain404** [comment]
Same issue here...after battling to get the default creds issue resolved.

**Comment by lclerigues** [comment]
> Docker didn't work for me, I checked out the `docker/docker-frontend.sh` script, and ran those commands manually. i.e.:
> 
> ```
> # get nodejs from conda-forge in my case
> conda install -c conda-forge nodejs
> cd superset-frontend
> npm install -f --no-optional --global webpack webpack-cli
> npm install -f --no-optional
> npm run dev
> ```
> 
> My guess is some of the init scripts should have run this, but because nodejs is not installed it skipped it. I guess the installation docs can be improved on this.

did this, found 24 vulnerabilities
![image](https://github.com/apache/superset/assets/115978584/f4f5296c-b527-4ddf-a15b-d5aacaa82048)

including malware?
![image](https://github.com/apache/superset/assets/115978584/023c74b1-059a-4c07-a209-b23af20174f9)

did anyone else find this? should I worry?

**Comment by elburro1887** [comment]
Same issue here, just pulled the superset repo and ran docker as instructed in the docs:

`git clone --depth=1  https://github.com/apache/superset.git`
`docker compose up`

So im pretty sure this issue needs to be re-opened...

**Comment by ereztaiar** [comment]
I don't know if my solution is correct but what work for me is adding
```
apt install zstd
```
to docker_frontend.sh file before npm run dev
looks like simple-zstd requires it in the image
https://www.npmjs.com/package/simple-zstd

**Comment by rusackas** [comment]
I think https://github.com/apache/superset/pull/30279 intends to take care of any remaining zstd issues.

**Comment by Anudeep-Kolluri** [comment]
still no solution?

**Comment by Anudeep-Kolluri** [comment]
THIS WORKED FOR ME

https://github.com/apache/superset/issues/30670

cd /path/to/superset-frontend
npm install
npm run build

**Comment by dvlieghe** [comment]
I had the same issue, turns out that the default nodejs version on Ubuntu is way too low. Was v12.something. After upgrading to v20.something, it worked fine for me. I also did the npm install/npm run build part, but I am not sure that was still necessary

**Comment by Ilphrin** [comment]
I just installed the project locally through docker, and had the same issue...

I can confirm that @Anudeep-Kolluri's process fixes it
