### ISSUE TITLE
Add databases from linked servers.

### ISSUE THREAD

**Issue by litsovyu** [apache/superset#17082]
Hello.
It would be very convenient to add databases from linked servers (we are talking about mssql).

Something like this: 
mssql+pymssql://user:password@host:1433(port)/linkedserver.database

![Screenshot_2](https://user-images.githubusercontent.com/82654310/137100825-0911f748-170f-4947-aa90-ed6a2f0f5a89.jpg)

**Comment by rusackas** [comment]
Sadly, this didn't get any traction for over a year, so I'll close it as stale. I'm not sure the current state of this as a feature, but if your needs are not met by Superset 2.0.1 or what's on `master` I'd suggest opening up an Ideas thread on Github Discussions. Thanks!
