### ISSUE TITLE
Dashboard import fails due to schema mismatch

### ISSUE THREAD

**Issue by krsnik93** [apache/superset#17083]
Command `superset import-dashboards` fails because of following schema mismatches:

1. `ValidationError({'extra': {'allows_virtual_table_explore': ['Unknown field.']}})` on schema `ImportV1DashboardSchema` in https://github.com/apache/superset/blob/7e4c940314ab6b09a89cb6938b02cf5d3028ad8a/superset/dashboards/schemas.py#L279
2. `ValidationError({'query_context': ['Unknown field.']})` on schema `ImportV1ChartSchema` in https://github.com/apache/superset/blob/7e4c940314ab6b09a89cb6938b02cf5d3028ad8a/superset/charts/schemas.py#L1228

Removing the fields fixes the import. The archive was created by exporting from another Superset host.

#### How to reproduce the bug

1. Export dashboards from one Superset host
2. Try to import on another Superset host

### Expected results

Expect import to succeed.

### Actual results

Import fails with validation errors as above.

### Environment

(please complete the following information):

- browser type and version:
- superset version: 1.3.0 on source host, 1.2.0 on destination host
- python version: 3.8.10
- any feature flags active:
```
FEATURE_FLAGS = {
    "DYNAMIC_PLUGINS": True,
    "ROW_LEVEL_SECURITY": True,
    "VERSIONED_EXPORT": True,

    "THUMBNAILS": True,
    "THUMBNAILS_SQLA_LISTENERS": True,
    "LISTVIEWS_DEFAULT_CARD_VIEW": True,
}

```

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing this as stale since it didn't get any answers or corroboration in so long. Sorry for that. if you're still facing this issue in Superset 2.0.1, particularly with the `VERSIONED_EXPORTS` flag turned on (which is preferred by now), let us know and we can revisit/reopen.
