### ISSUE TITLE
SQL Lab UI does not persist schema in the query tab

### ISSUE THREAD

**Issue by harshgadhia** [apache/superset#17104]
### Steps to reproduce:

1. Go to SuperSet  -> SQL Lab -> SQL Editor
3. Choose Database `examples` (default postgres provided out-of-box as example) -> schema: `information_schema`
4. In the editor, run a query like: 
`select * from collations`

### Expected results
The database selection done on the left side should be persisted in the query tab, and should be able to run a query without using fully qualified database.table name. 

That is, when a query like `select * from collations` is run, it should be automatically converted to `select * from information_schema.collations`, this is respecting the schema selections done on the left in the UI.

### Actual results
The database returns an error, complaining that the table / relation does not exists when not using fully qualified name.

#### Error Scenario

![image](https://user-images.githubusercontent.com/10794287/137235425-485358fc-8d94-4ff2-b860-0019942e4f94.png)

#### Positive scenario
Only Works when using fully qualified table / relation name:
![image](https://user-images.githubusercontent.com/10794287/137235389-9362c178-ca6b-4148-bbd8-3c57d716ffcf.png)

### Environment
- browser type and version: Google Chrome Version 94.0.4606.81 (Official Build) (x86_64)
- superset version: `superset version`
- python version: `python --version` 3.8.12
- node.js version: `node -v` 16
- any feature flags active: NO

### Checklist

Make sure to follow these steps before submitting your issue - thank you!
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by geido** [comment]
Hello @harshgadhia could you please provide the Superset version for which you are experiencing this problem?

**Comment by harshgadhia** [comment]
@geido I am on Apache Superset version 1.3.1.

**Comment by rusackas** [comment]
Or perhaps @yousoph can validate as well, since this has the `preset:cares` label on it still

**Comment by geido** [comment]
Hey @harshgadhia I am having a fresh look at this and realized that the dropdown on the left is not meant to dictate the schema for the SQL editor (which can accept cross-schema queries as well). That is just an exploration tool for the tables in the schema. I am going to close this issue. Thanks!
