### ISSUE TITLE
Operational Metrics for SuperSet

### ISSUE THREAD

**Issue by harshgadhia** [apache/superset#17103]
**Problem**
I have installed SuperSet for some of our querying and visualizing needs. However, sometimes queries take longer than expected time to execute. Once the application is installed and running in a production, it is very vital to get operational insights for the application's performance. This kind of metrics is missing in SuperSet.

I am leveraging Apache SuperSet to enable stakeholders / users to query data from various pre-configured data sources. 
As a product owner, I would like to get insights on:
1. Query metrics such as `query/count`, `query/success/count`, `query/failed/count`, `query/interrupted/count`, `query/timeout/count`, `user`, `execution_time` etc.
2. Number of queries ran over time (e.g. how many queries ran in the past hour / day etc) 

**Describe the solution you'd like**
There should be a way to expose the operational metrics for a metrics server to use as a part of the API specification available [here](https://superset.apache.org/docs/rest-api). So potentially an API endpoint like `/api/v1/metrics` that can have all the operational metrics in TSDB format.
Having this type of insights via Apache SuperSet seems to be missing. 

**Additional context**
Please let me know if there is any way community is deriving these insights at the moment from Apache SuperSet?

**Comment by nytai** [comment]
Superset currently has a log event emitter, where user events are published. By default these events are sent to the metadata db in the logs table
