### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by Cocktailpy** [apache/superset#17110]
superset use this command:
gunicorn -w 10  -k gevent --timeout 120 -b  0.0.0.0:16666 --limit-request-line 0 --limit-request-field_size 0 --statsd-host localhost:8125 "superset.app:create_app()"

but get error like this:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/instrument/statsd.py", line 127, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by geido** [comment]
Hey @Cocktailpy I am closing this one as I think it's related to #17599 and that contains a little bit more information.
