### ISSUE TITLE
Mixed Time Series Chart: X-Axis scaling is odd, when adjusting Time Filterbox

### ISSUE THREAD

**Issue by LalaGabor** [apache/superset#17128]
When I adjust a time Filter the scaling on the X-Axis of my Mixed Time Series Chart is wonky.

#### How to reproduce the bug

1. Go to a Dashboard with a Mixed Time Series Chart and a Filter Box (Date Filter, or regular filter with Time column)
2. My Filter has multiple Options enabled and Required
3. Baseline Status: All years (1, 2 & 3) from the time filter are selected
4. Select Years 1& 2 only

### Expected results

Mixed Time Series Chart X-axis adjust to only show Years 1 & 2

### Actual results

Mixed Time Series Chart X-Axis expands to show Years -1, 0, 1, 2, 3, 4

#### Screenshots

![image](https://user-images.githubusercontent.com/44199231/137463279-5f9e2356-ca6f-4f6b-ba36-4ee0fc8dcc72.png)

### Environment

(please complete the following information):

- browser type and version: Firefox
- superset version: `superset version` 1.2
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by kamalkeshavani-aiinside** [comment]
related https://github.com/apache/superset/issues/15674

**Comment by rusackas** [comment]
I believe this has been resolved, and is DEFINITELY quite a stale issue by now. If this is still happening in 2.0.x, please provide updated repro steps (i.e. not with the deprecated Filter Box) and we can revisit/reopen.
