### ISSUE TITLE
[explore][time-series bar] SHOW VALUE issues

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#17136]
#### How to reproduce the bug

1. Go to Explore view, create a time-series bar chart V2 like this:

<img width="1153" alt="Screen Shot 2021-10-15 at 4 26 20 PM" src="https://user-images.githubusercontent.com/27990562/137564043-35b7a4e4-426d-4da2-8202-1d09a20be851.png">

2. Add Custom options like this: SHOW VALUE, STACK SERIES, SHOW TOTAL 
<img width="318" alt="Screen Shot 2021-10-15 at 4 27 07 PM" src="https://user-images.githubusercontent.com/27990562/137564070-43f1bde2-fb7b-453c-bc7a-35925f036e31.png">

3. You should see total value on top of each bar
4. click `boy` label,  `girl` label, the total value display is not consistent
when you select boy only: there is no total value
when you select girl only: total value show on top of bar. and this total value seems like the value for girl only, this is very misleading. 
![pmJMItwCKR](https://user-images.githubusercontent.com/27990562/137564276-86c0456d-e6bd-4462-b27b-66735fede656.gif)

### Expected results

Should not show total value when only girl (or part of data) category is selected.

### Environment

latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

cc @junlincc @zuzana-vej

**Comment by stephenLYZ** [comment]
working on it

**Comment by graceguo-supercat** [comment]
user selected `ONLY TOTAL`. Does this mean only show TOTAL as marker on top of stacked bar, and not show selected category at all?

Maybe this `ONLY TOTAL` label is misleading, could you add description to explain what will show?

**Comment by rusackas** [comment]
I believe this was fixed by the linked PR, and has gone quite stale anyway. If anyone still sees this issue or one like it, let's open a fresh report with renewed context. Thanks!
