### ISSUE TITLE
List user own charts + dashboard listing with RBAC

### ISSUE THREAD

**Issue by jkleinkauff** [apache/superset#17139]
#### How to reproduce the bug

- give a user `gamma` + `sql_lab`  roles + database access(for SQL lab work properly)
- create a chart coming from SQL Lab Explore
- Save it, an error will occur but the tip "Chart xxx saved" will appear

### Expected results

User could list the charts he created

### Actual results

User could not list the charts he created
Maybe related to the error message (??)

#### Screenshots

![image](https://user-images.githubusercontent.com/58440667/137651453-9a82345d-56c0-4a9f-bb6f-ff9dd3788842.png)

### Environment

- Chrome Version 94.0.4606.71 (Official Build) (64-bit)
- [helm 0.3.10](https://apache.github.io/superset/index.yaml) - 0.0.0dev
- Python 3.7.9
- any feature flags active: ENABLE_TEMPLATE_PROCESSING, DASHBOARD_NATIVE_FILTERS, DASHBOARD_RBAC
- Redshift

### Additional context

I think this could be related to https://github.com/apache/superset/issues/12041, https://github.com/apache/superset/issues/8927 but the problem is if I add `'schema access on [database].[schema]'` to a role, in dashboard/list I can see all published dashboards, even if I don't have permissions(role) to the dashboard.
While I can see the dashboard on the list, when I try to access it an "Unexpected error" occurs. (correct as I don't have permission)

**Comment by rusackas** [comment]
Since this hasn't received validation/corroboration in over a year, I'll close it as stale. If you're still facing this issue in Superset 2.0.1, I'm happy to reopen it for you.
