### ISSUE TITLE
Druid SQL dataset __time column registered as a LONG rather than TIMESTAMP 

### ISSUE THREAD

**Issue by john-bodley** [apache/superset#17154]
#### How to reproduce the bug

1. Add a Druid dataset and notice that the `__time` column is assigned the type `LONG`.
2. Go to SQL Lab and fetch the metadata for said dataset. Notice that the `__time` column is of type `TIMESTAMP` which is correct.
3. Observe the discrepancy.

By registering the `__time` column as a `LONG` the right-hand-side of the time comparisons are not formatted corrected—which is handled by the [`convert_dttm`](https://github.com/apache/superset/blob/4cc095c10aa0e1c756fe77a31a2988773fc8993d/superset/db_engine_specs/druid.py#L96-L103) method. Thankfully it seems like Druid might do implicit casting.

### Expected results

1. The metadata for fetching a dataset should be consistent, be that via the add dataset or SQL Lab flow.
2. For Druid datasets the `__time` column should be `TIMESTAMP`.

### Actual results

See above. Note https://github.com/apache/superset/issues/15378 may be related.

#### Screenshots

<img width="874" alt="Screen Shot 2021-10-19 at 10 09 58 AM" src="https://user-images.githubusercontent.com/4567245/137960405-16937bb8-afb4-4fc9-8c8d-b27fda254636.png">

![Screen Shot 2021-10-19 at 10 10 46 AM](https://user-images.githubusercontent.com/4567245/137960297-56dec8ce-d5c6-4fef-ab80-6d82dc729fdc.png)

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: `master`
- python version: 3.8
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by john-bodley** [comment]
@villebro do you recall where and how these two workflows fetch the dataset metadata or how these could differ?

**Comment by rusackas** [comment]
@john-bodley is this still an issue? I'd be tempted to close it as stale, but figure you can help validate here ;)

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
