### ISSUE TITLE
Alpha Role Permission Bug

### ISSUE THREAD

**Issue by bizimarda** [apache/superset#17152]
Hello,

I noticed the authorization problem in user roles. When I logged in alpha roles user, SQL Lab menu disappears but if I try to reach to SQL Lab with url, it allows me to.  

1. Go to register with alpha role
2. Login with new alpha role user
3. Look up nav/tab bar and see that SQL Lab button is hidden.
4. Try to reach with this url : ./superset/sqllab/

### Expected results

I expected that if the sql lab button is hidden, SQL lab menu can not be reachable. 

### Actual results

Role permission is available for sqllab domains but  button is hidden.

#### Screenshots

![image](https://user-images.githubusercontent.com/32847220/137891049-807f7b9f-68bb-456c-948f-9e9c96354360.png)

![image](https://user-images.githubusercontent.com/32847220/137891282-2131ad91-f69e-4189-89ef-e39ebeb16b86.png)

![image](https://user-images.githubusercontent.com/32847220/137891365-d443bc48-fd62-4640-8a55-bda80eca54ca.png)

### Environment

latest

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ +] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ +] I have reproduced the issue with at least the latest released version of superset.
- [+ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by YMGYM** [comment]
I found the issue like this..
I can use Run in SQL Lab button and can reach /superset/sqllab/ url even I logged in alpha role (not have permission to sql lab)
![image](https://user-images.githubusercontent.com/41364201/188820974-8564963a-e041-46d9-a4a0-561776e1cf48.png)

Environment is latest docker image

**Comment by ShaliniIruvuru** [comment]
Working as Expected
Screenshot:-
![image](https://user-images.githubusercontent.com/115684419/225613766-d4507ed2-a146-4975-b905-97aa18cbefe5.png)

Loom video:-
https://www.loom.com/share/f851be59f1d54f668506b0551153f46d

**Comment by rusackas** [comment]
Closing as resolved. Thanks for the testing @ShaliniIruvuru
