### ISSUE TITLE
Problem pulling image from docker

### ISSUE THREAD

**Issue by JoaquinPretell92** [apache/superset#17150]
Hello,

I'm trying to deploy another superset environment to do some upgrade tests. We use superset 1.0.1.
We deploy on GCP and run via his own shell, but when i launch my terraform run, i get and imagepullerror:

![image](https://user-images.githubusercontent.com/73810312/137837299-f65e201f-7881-4f69-b313-f0318f71c91f.png)

and when i do a describe, i got an unauthorized error:

![image](https://user-images.githubusercontent.com/73810312/137837380-338fba00-b3a1-4c9f-839e-e03f5e01ed64.png)

{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"apache/superset","Action":"pull"}]}]}

![image](https://user-images.githubusercontent.com/73810312/137837404-a97299ad-0278-492f-a0fe-8acb5408a598.png)

its weird because if i do a docker pull apache/superset:1.0. we dont get the authentication error.

![image](https://user-images.githubusercontent.com/73810312/137837964-a4bd937f-1b58-474e-9b09-16ed2fd05a18.png)

i want to know if someone got this error before.

Regards

**Comment by srinify** [comment]
Hi there @JoaquinPretell92 at first glance -- this seems like a DockerHub issue :/ Docker over time has gotten more restrictive on who can pull images and have started to impose restrictions. A side effect is that you're required to login to Dockerhub in some cases. 

Check: https://github.com/docker/hub-feedback/issues/1484#issuecomment-726446687 as wel
