### ISSUE TITLE
How do i add margin box in Composed Chart

### ISSUE THREAD

**Issue by nattapat0255** [apache/superset#17163]
<img width="1436" alt="Screen Shot 2564-10-20 at 11 47 41" src="https://user-images.githubusercontent.com/81974292/138030379-5ad65fae-2917-4204-bcff-8b037f7db55c.png">

From the image, I want to add a margin box because I want the name column displayed in one line.

Please help!

**Comment by amitmiran137** [comment]
We'll check if this is possible .
Could you please open an issue under **nielsen-oss/superset-viz-plugins** repository bc composed chart is not provided by Apache superset directly
