### ISSUE TITLE
[alert/report] Searching for user in Email Report / Alert doesn't work properly

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#17162]
When searching for a user in the Email Alert & Report page, not all users are displayed - there seem to be a limit in the typehead or the search is broken. I can find reports with some user names, but if I type some of my colleagues names, their names are not found. 

### Expected results

All users should show up when name is typed.

### Actual results

No user is found.

#### Screenshots
<img width="704" alt="Screen Shot 2021-10-19 at 5 18 04 PM" src="https://user-images.githubusercontent.com/61221714/138028890-f262444c-8a03-4e53-b52d-73db67486902.png">

<img width="567" alt="Screen Shot 2021-10-19 at 5 17 49 PM" src="https://user-images.githubusercontent.com/61221714/138028878-530dafaf-99d3-4736-934b-f49cdc94985e.png">

<img width="372" alt="Screen Shot 2021-10-19 at 5 13 28 PM" src="https://user-images.githubusercontent.com/61221714/138028883-b76ee194-c005-4595-a6a5-688ec5e39b04.png">

### Environment
Master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zuzana-vej** [comment]
cc @yousoph @graceguo-supercat @m-ajay

**Comment by zuzana-vej** [comment]
Possibly related to https://github.com/apache/superset/issues/16963

**Comment by etr2460** [comment]
@yousoph any updates here?

**Comment by zuzana-vej** [comment]
fixed by the PR @graceguo-supercat linked above
