### ISSUE TITLE
docker documentations

### ISSUE THREAD

**Issue by jot4p** [apache/superset#17186]
Hi, 

The documentation for integrations with docker is not updated.  Please fix. (broken url for requirements.. etc) 

I'm trying to use: https://superset.apache.org/docs/databases/dockeradddrivers but this is not ok. 

Maybe  the best driver is this : https://pypi.org/project/mysql-connector-python/ 

But I get : mysql+mysqlconnector://root:root@localhost/table

"ERROR: (mysql.connector.errors.DatabaseError) 2004 (HY000): Can't create TCP/IP socket (97)
(Background on this error at: http://sqlalche.me/e/13/4xp6)" 

Can you check ?

**Comment by srinify** [comment]
Hi @jot4p this is helpful feedback, I'll investigate what we can do on the docs side.

At first glance -- it seems like the container running Superset can't connect to your MySQL database. So this could be a networking configuration issue! 

One thing I would try is firing up the shell for the docker container running `superset_app` and see if you can connect to your MySQL database from within that container. If it can't / you ran into a similar error, then you need to configure your network surrounding your MySQL database to accept connections from your computer, VM, etc.
