### ISSUE TITLE
[SIP-75] Proposal for Embeddable Dashboards

### ISSUE THREAD

**Issue by suddjian** [apache/superset#17187]
### Motivation

Embedding Superset dashboards into a third-party application is currently only possible if the dashboard is made public, or if users authenticate through Superset. We would like to add a feature to integrate dashboards into third-party applications ("Host Apps") with authentication handled by the Host App.

There should be no need to log in to an integrated dashboard if the user is already logged in to the Host App.

Example use cases:
- A storefront wants to offer engagement metrics to each of its vendors, integrated into the store management experience.
- A bank wants to offer a curated financial wellness dashboard to account holders.

Superset currently allows for a variety of valid strategies for granting API access, which can include various types of API Keys, depending on the deployment. Rather than force a specific API Key system into Superset, we’ve designed this spec to be agnostic to those details and depend on the existing security manager features as much as possible.

### Proposed Change

1. Dashboard creator marks their dashboard as "embedded" in the dashboard UI. This design isn’t done yet, but it’ll likely be a modal or a new panel in the edit mode sidebar. Dashboard creator defines a list of allowed referrer domains. When a creator makes a dashboard embedded, documentation is displayed on how to actually embed the dashboard.

1. Introduce a new endpoint `POST /embedded-resource/`, which returns an Embed Token that can be used to view the embedded resource. This token will be a JWT containing user info, row-level-security parameters (could be encoded either as a filter expression or as a RLS rule id), and grants of access to certain dashboards. It expires fairly quickly, so it must be refreshed periodically.

1. A Superset SDK is available for the Host App frontend to use, which will render the embedded dashboard page in an iframe, and pass the Embed Token through to the iframe using [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage). The Host App will pass a function to the SDK which fetches a new Embed Token, so when the token is about to expire, the SDK can get a new one.

1. A new page, `superset/dashboard/:id/embed` will be used as the url for the iframe. This page acts as a wrapper around the dashboard. It receives the message from Host App containing the Embed Token, validates the sender of the message, and ensures that all requests use the token as auth.

1. When a request is made using an Embed Token, security manager will use the information in the token to do its checks rather than looking up user, role and RLS info from the database.

Sequence diagram of the embedded dashboard auth flow:

![Embedded Dashboard Access Control - Embed Token](https://user-images.githubusercontent.com/1858430/139161229-c75bce4d-dfaf-4ca1-b373-8fe1408e5ff8.png)

### New or Changed Public Interfaces

`POST /embedded-resource/` endpoint

A new frontend SDK that will expose functions to embed a dashboard into the Host App

### New dependencies

flask-jwt-extended for handling jwt embed tokens

### Migration Plan and Compatibility

Will create new table `embedded_dashboards` containing a dashboard id reference, an allowlist of referrers, and any additional configurations of the embedded dashboard

### Rejected Alternatives

OAuth login - requires users to sign in to the iframe, lower UX
Generating a url or token in the Host App - better to keep generation on Superset side to avoid exposing implementation details, and so that we don’t have to define a specific API key spec
Passing a signed url instead of an embed token - This makes revoking access more complex

**Comment by suddjian** [comment]
This SIP is approved! Thanks for the discussion, all. Closing it now.

**Comment by nytai** [comment]
This should be considered as part of this work 
https://github.com/apache/superset/issues/17187

**Comment by gokhansari** [comment]
Thank you @suddjian for the proposal and your commits. It'll be life saver.
There is one thing that I would like to mention before you guys finalizing this feature. 

[Custom Url Parameters](https://superset.apache.org/docs/installation/sql-templating/#available-macros) feature is one of the handy functionalities and It is not dispensable. When I check the master branch, for now It seems Embedded SDK only takes dashboardID parameter.
To be able to use `{{ url_param('custom_variable') }}` and reference It in dataset SQL queries, I think there should be an other SDK parameter like `url_params: string` as we all used to use a lot of url parameters. 

Example from doc:
```
www.example.com/superset/sqllab?countrycode=ES&language=EN

SELECT count(*)
FROM ORDERS
WHERE country_code = '{{ url_param('countrycode') }}' AND language_code = '{{ url_param('language') }}' 
```

**Comment by suddjian** [comment]
Thanks for the comment, @gokhansari. Rather than using URL parameters, we can use the message channel shared by the SDK and Superset-within-iframe to accomplish this.

**Comment by idears-org** [comment]
Hi @suddjian I'm trying to use the embedded SDK and integration the SDK into my project like this:
``` javascript
embedDashboard({
      id: "3", // given by the Superset embedding UI
      supersetDomain: "http://localhost:62421/superset",
      mountPoint: document.getElementById("superset-container"), // any html element that can contain an iframe
      fetchGuestToken: () => {setTimeout(() => "a token from swagger ui", 10) },
      debug: true,
    });
```

but the sdk inject an url http://localhost:62421/superset/dashboard/3/embedded in iframe which showing "page not found" am I doing wrong?

<img width="582" alt="image" src="https://user-images.githubusercontent.com/13452500/154981894-6b8f0dd4-fd39-47ed-9495-c00bf8a02b56.png">

**Comment by idears-org** [comment]
I'm using the kubernetes deployment, and already set the EMBEDDED_SUPERSET to True in pythonpath/superset_config.py by modify the configOverrides value in my values.yaml

![image](https://user-images.githubusercontent.com/13452500/155091360-f77f7065-ba58-4bac-a492-61d551dee97d.png)

<img width="362" alt="image" src="https://user-images.githubusercontent.com/13452500/155091473-34ec709f-d267-45d3-802f-90728f0e4bad.png">

**Comment by idears-org** [comment]
Updates, I'm now able to use the embedded sdk by these settings:
<img width="468" alt="image" src="https://user-images.githubusercontent.com/13452500/155241944-414889ef-54d3-40e4-898d-ee5b65674a19.png">
![image](https://user-images.githubusercontent.com/13452500/155241996-2dd9b27a-7471-42d7-8cc5-23a2e25c4a8a.png)

**Comment by campino2k** [comment]
> Updates, I'm now able to use the embedded sdk by these settings: <img alt="image" width="468" src="https://user-images.githubusercontent.com/13452500/155241944-414889ef-54d3-40e4-898d-ee5b65674a19.png">

Where did you put these values, @idears-org? I run superset from docker

**Comment by idears-org** [comment]
@campino2k 
 I'm using helm to deploy on my cluster, and these setting are placed in my values.yaml
```
# A dictionary of overrides to append at the end of superset_config.py - the name does not matter
# WARNING: the order is not guaranteed
configOverrides: 
  override:: |
    FEATURE_FLAGS = {
      "EMBEDDED_SUPERSET": True
    }
    ENABLE_PROXY_FIX = True
    PUBLIC_ROLE_LIKE = "Gamma"
    WTF_CSRF_ENABLED = False
```
It will automatically set the `superset_config.py`
There should be a way to set the same by using docker.

**Comment by campino2k** [comment]
Thanks. I inspected the config.py and found it also uses Environment Variables as overrides, so:

![grafik](https://user-images.githubusercontent.com/209926/156736195-fc1fcf46-cef5-4ffc-b88e-f5cc1d028a62.png)

works like a charm.

**Comment by suddjian** [comment]
Heads up for anyone using this feature. Some time soon (after #19364 is merged) there will be an update pushing out a breaking change.

Instead of using the *Dashboard* id, and any dashboard being embeddable via the sdk, your app will need to use an *Embedded Dashboard* uuid that can be found through the dashboard options menu. See that PR I mentioned for more info on that.

I'll post here again when that update goes out. I don't anticipate further breaking changes after this update.

**Comment by wemod123** [comment]
Is this feature available now in test? 
Or no way to have a try?

**Comment by shenrie** [comment]
@suddjian I am curious about this new embedded feature. Does it require that all users are precreated on the SS application before a dashboard can be accessed from an iframe in the host app?

I have successfully embedded SS reports in our app using standard OAuth SSO. I had to write some custom python code in the values.yaml which the helm install injects into superset_config.py, but after that it works like a charm and does not require the user to be precreated in SS or to login to view reports. 

I use a shared OAuth service provider, Keycloak in my case, which our app uses to request the JWT access token and operates no differently than when using Google or some other authentication provider to provide SSO.  I simply have to pass the signed JWT as an access token parameter with each dashboard URL request, which of course contain the user's scoped info and appropriate roles, and our dashboards are configured with using the SS dashboard role-based access feature. New users are created on the fly and SS roles are updated from the JWT token as needed, so very minimal ongoing coordination needed between our app and the SS app as our user base grows.

**Comment by fstn** [comment]
Could we filter embedded data by userid?
I mean I would like to embed superset into my application and would like to display only data that are relative to the current login user.

**Comment by weitang2022** [comment]
Hi, I am able to embed superset into our website. It works fine as read-only dashboard. However, when I click "Enter fullscreen", or "Edit Dashboard" -> "Discard", it shows this error:
```
{"errors": [{"message": "403 Forbidden: You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.", "error_type": "GENERIC_BACKEND_ERROR", "level": "error", "extra": {"issue_codes": [{"code": 1011, "message": "Issue 1011 - Superset encountered an unexpected error."}]}}]}
```

"Edit chart" shows a blank page.

"CREATE NEW CHART" gives this error in the browser console:
```
Blocked opening 'https://superset.example.com/chart/add?dashboard_id=5' in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set.
```

I have given the guest role "Admin" and the rls is empty when getting the guest token. 

Please keep up the great work! Hopefully, these issue can be resolved soon.

**Comment by cwegener** [comment]
> Could we filter embedded data by userid? I mean I would like to embed superset into my application and would like to display only data that are relative to the current login user.

I think it should work by using Jinja templating. There is a `{{ current_user_id() }}` macro available which should work just fine with the Guest Token that is used by the Embedded dashboard. https://superset.apache.org/docs/installation/sql-templating

**Comment by faycal-merouane** [comment]
> Hi, I am able to embed superset into our website. It works fine as read-only dashboard. However, when I click "Enter fullscreen", or "Edit Dashboard" -> "Discard", it shows this error:
> 
> ```
> {"errors": [{"message": "403 Forbidden: You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.", "error_type": "GENERIC_BACKEND_ERROR", "level": "error", "extra": {"issue_codes": [{"code": 1011, "message": "Issue 1011 - Superset encountered an unexpected error."}]}}]}
> ```
> 
> "Edit chart" shows a blank page.
> 
> "CREATE NEW CHART" gives this error in the browser console:
> 
> ```
> Blocked opening 'https://superset.example.com/chart/add?dashboard_id=5' in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set.
> ```
> 
> I have given the guest role "Admin" and the rls is empty when getting the guest token. Most other menu links seem to work.
> 
> Please keep up the great work! Hopefully, these issue can be resolved soon.
> 
> @shenrie Do you mind sharing your changes to superset_config.py? I am interested to see how to hide the superset top navigation menu.



hey, can you provide me documentation to embed an iframe in my web application ? I'm trying to use the jwt from the security api but no result .

**Comment by weitang2022** [comment]
@faycal-merouane Here is an online instruction you can try:
https://medium.com/@khushbu.adav/embedding-superset-dashboards-in-your-react-application-7f282e3dbd88

**Comment by phamhuong7420** [comment]
![image](https://user-images.githubusercontent.com/75262904/204992668-8daaca82-c108-4551-91b2-1ce2a4ebe01b.png)
I don't see this in my workspace. thanks for any help

**Comment by Gokuyamatos12** [comment]
> ![image](https://user-images.githubusercontent.com/75262904/204992882-7bf953d6-5664-4458-b010-7c5c711acf39.png)
> 
> I don't see this in my workspace. thanks for any help

I think you need to set ["EMBEDDED_SUPERSET": True] in your configuration file for superset under default feature flags for the embed feature to be shown.

**Comment by Gokuyamatos12** [comment]
Does anyone know how to control the layout of the embedded dashboard.
I used the following to pick a specific chart on the dashboard since I need to customize it with react components but my react app still shows the entire dashboard.

```
embedDashboard({
        local:'en',
        id: '28c544a1-c74e-46ef-b466-f2e6e67a6ed3', // Replace with the ID of your dashboard
        supersetDomain: 'http://localhost:8088', // Replace with the URL of your Superset server
        mountPoint: document.getElementById('superset-container'), // Replace with the ID of the DOM element in which you want to render the dashboard
        fetchGuestToken: () => embedToken,
        layout: [
          {
            components:[
              {
                id:'2106',
                type:'slice',
              }
            ]
          }
        ],
        dashboardUiConfig: {
          // Custom options for the dashboard, if needed
        },

      });
```
      
 I'm also not sure what the type is for a specific chart in a dashboard, so I used 'slice'.

**Comment by benjaminlhai** [comment]
Regarding URL Parameters for template dashboards.

https://github.com/apache/superset/issues/17187#issuecomment-1045047163

Hi @suddjian 

> Thanks for the comment, @gokhansari. Rather than using URL parameters, we can use the message channel shared by the SDK and Superset-within-iframe to accomplish this.

Could you expand upon this or provide an example of how this might be achieved? I've looked all over for an example and can't find anything of value

**Comment by temuujinmo4** [comment]
Hi. returned {"errors": [{"message": "403 Forbidden: You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.", "error_type": "GENERIC_BACKEND_ERROR", "level": "error", "extra": {"issue_codes": [{"code": 1011, "message": "Issue 1011 - Superset encountered an unexpected error."}]}}]}
`EMBEDDED_SUPERSET": True`

**Comment by cwegener** [comment]
> Hi. returned {"errors": [{"message": "403 Forbidden: You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.", "error_type": "GENERIC_BACKEND_ERROR", "level": "error", "extra": {"issue_codes": [{"code": 1011, "message": "Issue 1011 - Superset encountered an unexpected error."}]}}]}
> 
> config on `EMBEDDED_SUPERSET": True`

I think this discussion will help you. You need to configure a Superset Role on your Superset server that will be used to apply permissions for your embedded Guest Token:
https://github.com/apache/superset/discussions/18814#discussioncomment-2776733

**Comment by temuujinmo4** [comment]
Hi guys HELP ME. 403 Forbidden: You don't have the permission to access the requested resource. It is either read-protected or not readable by the server

My backend superset_conifg.py
    PUBLIC_ROLE_LIKE_GAMMA = True
    GUEST_ROLE_NAME = "Gamma"SQLALCHEMY_ECHO = True
    SESSION_COOKIE_SAMESITE = None
    ENABLE_PROXY_FIX = True
    FEATURE_FLAGS = {
    "EMBEDDED_SUPERSET": True
}

I got guest token, My Frontend:
<div style="height: 100vh;">
    <iframe id="superSet" width="100%" height="100%"></iframe>
</div>

getToken = () => {
        $.ajax({
            'type': 'POST',
            'url': "**************",
            'data': {},
            'headers': {
                'X-CSRFToken': "{{csrf_token}}",
            },
            'dataType': 'json',
            'success': function (data) {
                getGuestToken(data.access_token, data.refresh_token)
            },
        });
    }

    getGuestToken = (access_token, refresh_token) => {
        $.ajax({
            'type': 'POST',
            'url': "******",
            'data': {
                'access_token': access_token,
                'refresh_token': refresh_token
            },
            'headers': {
                'X-CSRFToken': "{{csrf_token}}",
            },
            'dataType': 'json',
            'success': function (data) {
                supersetEmbeddedSdk.embedDashboard({
                    id: "*******************************",
                    supersetDomain: "********,
                    mountPoint: document.getElementById("superSet"),
                    fetchGuestToken: () => data['token'],
                });
            },
        });
    }

**Comment by chandrasekharjandhyam** [comment]
> @suddjian I am curious about this new embedded feature. Does it require that all users are precreated on the SS application before a dashboard can be accessed from an iframe in the host app?
> 
> I have successfully embedded SS reports in our app using standard OAuth SSO. I had to write some custom python code in the values.yaml which the helm install injects into superset_config.py, but after that it works like a charm and does not require the user to be precreated in SS or to login to view reports.
> 
> I use a shared OAuth service provider, Keycloak in my case, which our app uses to request the JWT access token and operates no differently than when using Google or some other authentication provider for SSO capability. I simply have to pass the signed JWT as an access token parameter with each dashboard URL request, which of course contain the user's scoped info and appropriate roles, and our dashboards are protected using the SS dashboard role-based access feature. New users are created on the fly and SS roles are updated from the JWT token as needed, so very minimal ongoing coordination needed between our app and the SS app as our user base grows, which was an important requirement for our use case. We cannot precreate or have to manage users in SS beyond standard OAuth capacity.
> 
> I have attached a screen capture of our app showing an example SS report embedded in an iframe. We are still iterating on the UI and style of the SS reports for a better experience, but this demonstrates the point.
> 
> <img alt="image" width="1443" src="https://user-images.githubusercontent.com/768977/173165660-cb94d93b-055b-4fe0-848a-e91ea4ae3b34.png">

Hi Shenrie ,

could you please provide the custom code that you have developed to use SSO and get JWT token for embedding, from official rest api documentation, login API does not support SSO based authentication.

**Comment by andrecamara** [comment]
Any updates on this? Does anyone have a reference on how to get the tokens for embedding a dashboard, when oauth is enabled?
Thanks in advance

**Comment by okayakdeniz** [comment]
> Thanks for the comment, @gokhansari. Rather than using URL parameters, we can use the message channel shared by the SDK and Superset-within-iframe to accomplish this.

Could you please share about an introduction how to we use the message channel?

**Comment by ameen7626** [comment]
Hi everyone, so I have a different use case, I'm trying to embed a dashboard(lets say it is landing page) which contains link to other dashboards  so the landing page is getting embedded correctly but the issue I faced is when I try to access the other dashboard it is casusing error the error is occuirng at  these api's image attached 
![image](https://github.com/apache/superset/assets/116628630/ad9e188e-aeb4-4c78-a5a4-e282aa738bcb)

https://github.com/apache/superset/assets/116628630/8a72d51c-1bb8-4cbe-9ca9-81e60b648588

**Comment by rusackas** [comment]
Hi all... this SIP was passed and implemented forever ago. It's not really sustainable to pile on with more questions/bugs/requests, so I'm going to (politely as possible, I thank you all!) lock this thread, and encourage anyone seeing this to open either a new [issue](https://github.com/apache/superset/issues/new/choose) or [discussion](https://github.com/apache/superset/discussions/new/choose). Thanks!
