### ISSUE TITLE
Dashboard user filter cache resets

### ISSUE THREAD

**Issue by professionalgamethrower** [apache/superset#17188]
After applying report filters, the filters are not saved in user cache and there is no wat for users to save the filters. 

#### How to reproduce the bug
Create a Filter chart. Add the chart to a dashboard, publish the dashboard.
Open the dashboard and apply filters to the Filter chart. Close the dashboard.
Open the dashboard again. 

### Expected results
Last filters are saved.

### Actual results
Last filters are not saved.

### Environment
superset v.1.2.0
python v.3.7

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ X ] I have reproduced the issue with at least the latest released version of superset.
- [ X ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
All caching were disable for real time data retrieval.

**Comment by geido** [comment]
Hello @professionalgamethrower thanks for reporting this issue. We are moving away from the filter box viz type to the native filters. I'll close this issue. Let me know if you require additional assistance. Thank you!
