### ISSUE TITLE
Line chart and histogram format the group by labels differently

### ISSUE THREAD

**Issue by scimas** [apache/superset#17190]
Specifically, histogram seems to replace `-`s (hyphens) in the lables with `_`s (underscores). Which means the same group by labels get different colours in different charts in the same dashboard.

#### How to reproduce the bug

1. Have a column in a dataset with hyphens in the values.
2. Use said column for Group By in a line chart and in a histogram.

### Expected results

Both the line chart and histogram create same labels in the legend.

### Actual results

They don't create the same labels in the legend, histogram seems to replace hyphens with underscores.

#### Screenshots
Line chart:
![image](https://user-images.githubusercontent.com/16473290/138347843-9c312f89-3923-43f6-b06d-4fc5268e1cd6.png)

Histogram:
![image](https://user-images.githubusercontent.com/16473290/138347989-3c831880-2921-42ca-8b62-4dbb62f72826.png)

### Environment

- Firefox 93.0:
- superset version: `1.3.2`
- python version: `3.7.9`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
I'm unable to reproduce this in current Superset. The inputs have changed a bit, but things seem to stay as hyphens with MySQL, and the custom series color is working a-ok!
