### ISSUE TITLE
The filter mapping settings are not working 

### ISSUE THREAD

**Issue by vivekdixit2510** [apache/superset#17198]
The filter mapping settings are not valid

Expected results
Configure filter scopes will take effect after saving

Actual results
Configure filter scopes, unable to save effectively.
1. Uncheck first 3 box(scope) and save .
![image](https://user-images.githubusercontent.com/80536487/138439865-9e6b3151-3fcf-40f4-8609-b3c036db1747.png)

2. Save dashboard
![image](https://user-images.githubusercontent.com/80536487/138440129-6e48d560-c069-4b28-a022-8799664cfbd6.png)

3. Refresh url，the setting is not saved.
![image](https://user-images.githubusercontent.com/80536487/138440290-23cdc33b-b9a5-4c84-b69c-323185f295ed.png)

How to reproduce the bug
Set configure filter scopes and cancel one filter scopes

Refresh after saving

Configure filter scopes is still in their original state and has not been saved

**Comment by lorenzo-latta** [comment]
I have more or less the same issue.
Moreover, without touching filter config I have lost all the config.

**Comment by rusackas** [comment]
@andrey-zayats took a look at this and was unable to reproduce the issue. I'm going to go ahead and remove the `validation:required` label and close the issue. If anyone sees this happening in Superset 2.0.x or later, or on `master`, we're open to revisiting this conversation, re-opening the ticket, or triaging a new Issue with updated context. Thank you!
