### ISSUE TITLE
[Chart Description] Can we show chart description in info tooltip like dataset does?

### ISSUE THREAD

**Issue by rosemarie-chiu** [apache/superset#17204]
**Is your feature request related to a problem? Please describe.**
I like how I can see the description of a dataset on dataset list simply hover over to the "i" icon. I can't do that with chart and I always have to open chart description to see it.

**Describe the solution you'd like**
If we can do something like this for chart that would be nice!
<img width="445" alt="CleanShot 2021-10-23 at 07 19 15@2x" src="https://user-images.githubusercontent.com/52086618/138532587-a04d3c3a-be7c-42d7-8b02-a379c8a5f3d9.png">

![CleanShot 2021-10-23 at 07 18 06](https://user-images.githubusercontent.com/52086618/138532550-e3792f39-f6de-4910-a288-bfe64a9ba047.gif)

**Describe alternatives you've considered**

**Additional context**

**Comment by rusackas** [comment]
This was resolved by https://github.com/apache/superset/pull/17207
