### ISSUE TITLE
The filter mapping configuration can not be  saved in V1.2.0 +

### ISSUE THREAD

**Issue by xinjingqing** [apache/superset#17230]
1、set the param DASHBOARD_CROSS_FILTERS = True
2、click "Edit Dashborad"
3、set filter mapping
4、config filter scopes
5、click “save” to save the filter mapping info.
6、click “save” to save the dashboard info.
7、refesh the current page or relogin the system
8、The filter scopes configured a momen ago are invalid...

**I have fixed the BUG...**

![1635224579(1)](https://user-images.githubusercontent.com/10738633/138812020-081cae7e-c436-4aef-86b0-e3e4feea891b.png)

**Comment by amitmiran137** [comment]
You'd better turn on DASHBOARD_NATIVE_FILTERS as well 
And in addition I would upgrade to the latest version bc filters are still not stable in 1.2
