### ISSUE TITLE
Charts data does not update based on cache timeout, refreshing the charts doesn't work

### ISSUE THREAD

**Issue by spouria** [apache/superset#17240]
I have set up superset using mysql and redis on ubuntu server. I have set these config in my config file:

SQLALCHEMY_DATABASE_URI = '[my mysql connection]'
DATA_DIR = os.path.join(os.path.dirname(__file__), 'data_dir')

CACHE_DEFAULT_TIMEOUT = 600
CACHE_CONFIG = {
'CACHE_TYPE': 'redis',
'CACHE_DEFAULT_TIMEOUT': 600,
'CACHE_KEY_PREFIX': 'superset_',
'CACHE_REDIS_HOST': 'localhost',
'CACHE_REDIS_PORT': 6379,
'CACHE_REDIS_DB': 1,
'CACHE_REDIS_URL': 'redis://localhost:6379/1'
}

I expect the cache to be 10 minutes for my charts, so the dashboard will be updated with new data from my database every 10 minutes. However it updates them every 24 hours and does not use the cache timeout. It neither updates the charts when I use "force refresh' on a chart. However, when I use the 'explore chart' and re-save it, it gets the new data from the database.

#### How to reproduce the bug

1.set up the superset with these config.
2- create a chart.
3- add some new records to the data source.
4- go to the dashboard after the the time of cache timeout
5- refresh the page

### Expected results

The charts are updated with new data added to the datasource

### Actual results

The charts are not updated. They will be updated tomorrow.

### Environment

(please complete the following information):

- browser type and version: firefox 93.0
- superset version: 0.38.1
- python version: 3.6.7
- node.js version: 14.16.0
- redis-server version: 5:4.0.9

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by jkleinkauff** [comment]
Hello! Did you find any solution for this? Thank you.

**Comment by sirpuria** [comment]
> Hello! Did you find any solution for this?

No, unfortunately it still ignores all the cache settings and dashboards get updated every 24 hours.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
