### ISSUE TITLE
[Dashboard] Color scheme won't be discarded when discarding changes

### ISSUE THREAD

**Issue by geido** [apache/superset#17243]
#### How to reproduce the bug

1. Go to a Dashboard
2. Click on Edit dashboard properties
3. Change the color scheme and click Save
4. Without saving the whole dashboard, click on "Discard changes"
5. The page will refresh and the color scheme change hasn't been discarded

### Expected results

Saving changes in the "Edit dashboard properties" Modal should only be effective when the whole Dashboard is saved. When discarding the changes, any change should reset.

### Actual results

The color scheme is not discarded

#### Screenshots

https://user-images.githubusercontent.com/60598000/139059213-79862427-72a5-466d-b4e0-82ae74f00efc.mp4

### Environment

- browser type and version: Chrome
- superset version: `master`

**Comment by jinghua-qa** [comment]
I have a question when I set a color theme in the chart and add it to a dashboard, why I can not see the color theme information in the dashboard edit mode?

https://user-images.githubusercontent.com/81597121/141337464-fe174a4b-8d9f-4abd-b371-62dfd7cf065e.mov
