### ISSUE TITLE
Replaced the dataset without clearing the dimensions/metrics in controls

### ISSUE THREAD

**Issue by MeggieRong** [apache/superset#17261]
## Description
We planned to create some standard charts as official company charts, so that other users can use the official charts by simply changing the data source(the new data source is exactly the same as the old data source, only the table data values are different).
However, in version 1.3.2, we found that when we changed the data source for a chart that was created, the chart was automatically cleared and needed to be recreated.

## Requirements
I wish superset could support replacing datasets without clearing the dimensions/metrics in the control, like Tableau does

## Situation Replay
![Animation](https://user-images.githubusercontent.com/30862103/139416077-8cae08cf-1ff8-468b-8b28-41ea919eb001.gif)

## Environment
superset version :1.3.2
ubuntu

**Comment by sporaans** [comment]
Hi @geido are there any updates on this? I also have this issue.

**Comment by La1x** [comment]
Hi team.
Any updates on this issue?
I have the same behavior on version 1.4.2.

**Comment by swanitzek** [comment]
What is the current status of this issue? Is there any workaround available or is it fixed in the current version of Superset?
