### ISSUE TITLE
Metric lingers around after switching chart type from big number with trendline to line chart

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#17271]
### Description:
When switching from a populated big number with trendline chart to a line chart and choosing a different metric, the old metric will still show in the line chart. This is also valid when switching to time series line chart. If you share the new chart through a link, the old metric goes away. See attachments.

### Platform Details:
Browser: Chrome
Device: MBP

### Steps to Reproduce:

Open a big number with trendline chart (possibly also works with big number)
Switch the chart type to line chart or time series line chart. The metric box will clear.
Add a new metric, different from the previous one.
Run the chart.

### Result:
You will see both the old and new metrics.

### Expected Result:
Only the new metric should show up.

### Environment

latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
A whole slew of changes have taken place in terms of switching visualization types, thanks to @zhaoyongjie. I suspect this is no longer an issue at all, but if you think it is, I'm happy to revisit/reopen with updated context of what you might be seeing in 2.0.1 or on `master`. Thanks!
