### ISSUE TITLE
Conflict between Domain Sharding and Webdriver Configuration

### ISSUE THREAD

**Issue by jsanko9** [apache/superset#17272]
Bug happens between two config parameters:
WEBDRIVER_BASEURL
SUPERSET_WEBSERVER_DOMAINS

Once SUPERSET_WEBSERVER_DOMAINS is set, it is used for resource requests  on "standalone page", resulting in timeout by selenium. This seems as logical conflict. Worst part is amount of testing I had to do to find out which interaction was causing problem.

**Workaround** is to set WEBDRIVER_BASEURL to same value as WEBDRIVER_BASEURL_USER_FRIENDLY and bypass internal kubernetes service routing.

### Expected results
WEBDRIVER_BASEURL should take precedence by knowing, or notification should be generated that there is logical conflict

### Actual results
Selenium Timed out receiving message from renderer

### Environment

superset version 1.3.2 
chrome driver
Python 3.8.12
Node 14

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
    -  sorry, already lost them
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by geido** [comment]
Hello @jsanko9 thanks for reporting this issue. If you would be interested in opening a PR to fix this I'd be glad to help you through that process!

**Comment by rusackas** [comment]
Closing this as stale since no further discussion or issue validation/corroboration has taken place in over a year. If folks are still facing this, we're open to revisiting/reopening, or a new issue with update context. Thanks!
