### ISSUE TITLE
[Lists] Searching for & produces a fatal error in the API

### ISSUE THREAD

**Issue by geido** [apache/superset#17288]
Searching for & produces a fatal error in the API

#### How to reproduce the bug

1. Go to Dashboard lists
2. Search for the & character in the search box
3. Observe the error

### Expected results

Searching for & should not produce a fatal error

### Actual results

Searching for & produces a fatal error

#### Screenshots

https://user-images.githubusercontent.com/60598000/139466344-d3e3c93e-6d6e-4758-9fbc-ae8345643a04.mp4

### Environment

- superset version: `master`

**Comment by rusackas** [comment]
Fixed by https://github.com/apache/superset/pull/18056
