### ISSUE TITLE
Unable to Connect to Amazon Athena 

### ISSUE THREAD

**Issue by youcefjd** [apache/superset#17295]
Hi - Superset is unable to connect to Athena. I created a role in IAM that has Athena full access and attached it to the EC2 instance running Superset. However, when I try to login, using this connection string (URI): `awsathena+rest://@athena.us-east-1.amazonaws.com/?s3_staging_dir=s3://bucket/output-athena/` it gives me this error when I check the logs in the UI: 
`db_creation_failed.DatabaseTestConnectionFailedError`
I checked CloudTrail, and the attempt to connect doesn't generate an error. I tried modifying the URI by including the key/secret key, but nothing works. I systematically get this error: A`n error occurred while creating databases: Connection failed, please check your connection settings`

Help, please!

**Comment by eschutho** [comment]
You may be redacting your string for security, but are you including everything that is here in this example: 
https://superset.apache.org/docs/databases/athena
`awsathena+jdbc://{aws_access_key_id}:{aws_secret_access_key}@athena.{region_name}.amazonaws.com/{schema_name}?s3_staging_dir={s3_staging_dir}&...`
I didn't see the access key id and key for example in your URI. You may also want to try putting the port after `amazonaws.com` (port 443 is the default for https)
We're in the process of building out forms for each db to make this process easier.
