### ISSUE TITLE
SAWarning: Oracle version - maximum identifier length

### ISSUE THREAD

**Issue by jhult** [apache/superset#17291]
#### How to reproduce the bug

```
/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/oracle/base.py:1409: SAWarning: Oracle version (19, 13, 0, 1, 0) is known to have a maximum identifier length of 128, rather than the historical default of 30. SQLAlchemy 1.4 will use 128 for this database; please set max_identifier_length=128 in create_engine() in order to test the application with this new length, or set to 30 in order to assure that 30 continues to be used.  In particular, pay close attention to the behavior of database migrations as dynamically generated names may change. See the section 'Max Identifier Lengths' in the SQLAlchemy Oracle dialect documentation for background.
```

### Expected results

No warning to occur.

### Actual results

I receive the above warning.

### Environment

(please complete the following information):

- Docker: Using a Dockerfile similar to this: https://github.com/jhult/superset/commit/ae374f1d6b2830910cf9120c8d8f2aae943265b9
- browser type and version: All
- superset version: `superset version`: latest master
- python version: `python --version`: 3.8.12
- any feature flags active:
```
FEATURE_FLAGS = {
    "DASHBOARD_NATIVE_FILTERS": True,
    "DASHBOARD_CROSS_FILTERS": True,
    "DASHBOARD_NATIVE_FILTERS_SET": True,
    "DASHBOARD_FILTERS_EXPERIMENTAL": True,
    "ENFORCE_DB_ENCRYPTION_UI": True,
    "DASHBOARD_RBAC": True,
    "OMNIBAR": True,
    "TAGGING_SYSTEM": True,
    "SQLLAB_BACKEND_PERSISTENCE": True,
    "LISTVIEWS_DEFAULT_CARD_VIEW": True,
    "ALERT_REPORTS": True,
    "ENABLE_TEMPLATE_PROCESSING": True,
    "UX_BETA": True
}
```

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sergun** [comment]
@jhult do you have other problems likely connected to this issue? I see that sometimes Superset substituces long field names with some numeric preficies like "_1". That causes error messages.
See https://github.com/apache/superset/issues/19468

**Comment by jhult** [comment]
@sergun, I don't believe I've seen any other issues that I believe are connected to this.

**Comment by rusackas** [comment]
@sadpandajoe / @eschutho do we know anyone that can validate troubleshoot Oracle issues like this and #19468?

**Comment by rusackas** [comment]
@sadpandajoe / @eschutho do we know anyone that can validate troubleshoot Oracle issues like this and #19468?

**Comment by rusackas** [comment]
Not sure if you're still facing this, but I'm closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
