### ISSUE TITLE
Unauthorized Page Returns 302 Instead of 403

### ISSUE THREAD

**Issue by Pajri** [apache/superset#17301]
Hi, 
I tried to remove logmodelview/ access permission in a role. However, when access page /logmodelview/list/, it returns 302 instead of 403.

How to handle unauthorized access to a page ?

#### How to reproduce the bug

1. Remove logmodelview permission in a role (all of them)
2. Access logmodelview/list/
3. It returns 302 

### Expected results

It should return 403

### Actual results

It returns 302

#### Screenshots

![image](https://user-images.githubusercontent.com/6915392/139638887-ac8a0b2b-4b9d-4385-81d7-b34b4809ed91.png)

### Environment

(please complete the following information):

- microsoft edge

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by etr2460** [comment]
What version was this on? I believe this was resolved in https://github.com/apache/superset/pull/17100. Closing preemptively, but feel free to reopen if you're still having issues
