### ISSUE TITLE
[question] does anyone encounter this weird green drop shadow in line chart Echart? 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#17316]
## Screenshot
<img width="616" alt="Screen Shot 2021-11-01 at 8 30 37 PM" src="https://user-images.githubusercontent.com/67837651/139782623-536a2da7-020f-412f-9357-6757732f8020.png">

**Comment by stephenLYZ** [comment]
Is it on the dashboard?

**Comment by rusackas** [comment]
I think we can call this one closed by now... or to answer the direct question: nope! :D
