### ISSUE TITLE
[Explore] Metrics shuffle randomly in explore

### ISSUE THREAD

**Issue by TechAuditBI** [apache/superset#17322]
While trying to change metrics order in explore by dnd they appear to jump randomly.

#### How to reproduce the bug

1. Go to any viz that allow to use multiple metrics
2. Select a bunch of metrics
3. Try to reorder them via dnd

### Environment

- browser Chrome version: 95.0.4638.54
- superset version: 1.3.2
- any feature flags active:

### Additional context

This bug is around since superset ver 1.1
It seemes that this bug does not apear if you move metrics slow enough

In this clip if I move metrics slowly (1st part) their order stays correct but when I start to move faster (2nd part) you can clearly see how their order becomes completely random. Used viz type - table
https://user-images.githubusercontent.com/88540994/139858871-163a0c69-624b-4149-a092-914967d72507.mp4

**Comment by junlincc** [comment]
Thanks for reporting, this is a known limitation. we should be able to get to it next year, but early contribution is welcomed! :)
