### ISSUE TITLE
Fatal error when export dashboards

### ISSUE THREAD

**Issue by jordiisidro** [apache/superset#17334]
I want to export a dashboard with the api and I have the result "Fatal error"

I try to export the default dashboard: World Bank's Data 
With the url:
 http://localhost:8089/api/v1/dashboard/export/?q=[1]

It returns the message: "Fatal error"

I have the same result with docker installation or installation from scratch
![imatge](https://user-images.githubusercontent.com/19467312/140058144-7a9cbff2-7d37-4ae0-9998-f223739c8b64.png)

### Environment
- browser type and version: chrome/firefox
- superset version: 1.3.1
- python version: 3.8.19
- node.js version: v.17.0.1

**Comment by junlincc** [comment]
what feature flags did you enable. can you provide detailed repo steps? thanks!

**Comment by jordiisidro** [comment]
These are the configurations and the commands that I execute:

_Ubuntu 20.04.3 LTS
Python 3.8.10_

_pip freeze_

aiohttp==3.7.4.post0
alembic==1.7.4
amqp==2.6.1
apache-superset==1.3.1
apispec==3.3.2
async-generator==1.10
async-timeout==3.0.1
attrs==21.2.0
Babel==2.9.1
backoff==1.11.1
billiard==3.6.4.0
bleach==3.3.1
Brotli==1.0.9
cachelib==0.1.1
celery==4.4.7
certifi==2021.10.8
cffi==1.15.0
chardet==4.0.0
click==7.1.2
colorama==0.4.4
convertdate==2.3.2
cron-descriptor==1.2.24
croniter==1.0.15
cryptography==35.0.0
defusedxml==0.7.1
deprecation==2.1.0
dnspython==2.1.0
email-validator==1.1.3
Flask==1.1.4
Flask-AppBuilder==3.3.3
Flask-Babel==1.0.0
Flask-Caching==1.10.1
Flask-Compress==1.10.1
Flask-JWT-Extended==3.25.1
Flask-Login==0.4.1
Flask-Migrate==3.1.0
Flask-OpenID==1.3.0
Flask-SQLAlchemy==2.5.1
flask-talisman==0.8.1
Flask-WTF==0.14.3
geographiclib==1.52
geopy==2.2.0
graphlib-backport==1.0.3
gunicorn==20.0.4
h11==0.12.0
holidays==0.10.3
humanize==3.12.0
idna==3.3
importlib-metadata==4.8.1
importlib-resources==5.2.2
isodate==0.6.0
itsdangerous==1.1.0
Jinja2==2.11.3
jsonschema==3.2.0
kombu==4.6.11
korean-lunar-calendar==0.2.1
Mako==1.1.5
Markdown==3.3.4
MarkupSafe==2.0.1
marshmallow==3.13.0
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.23.1
msgpack==1.0.2
multidict==5.2.0
numpy==1.21.2
outcome==1.1.0
packaging==21.0
pandas==1.2.5
parsedatetime==2.6
pgsanity==0.2.9
pkg_resources==0.0.0
polyline==1.4.0
prison==0.2.1
psycopg2==2.9.1
psycopg2-binary==2.8.5
pyarrow==4.0.1
pycparser==2.20
PyJWT==1.7.1
PyMeeus==0.5.11
pyOpenSSL==21.0.0
pyparsing==2.4.7
pyrsistent==0.18.0
python-dateutil==2.8.2
python-dotenv==0.19.1
python-geohash==0.8.5
python3-openid==3.2.0
pytz==2021.3
PyYAML==6.0
redis==3.5.3
selenium==4.0.0
simplejson==3.17.5
six==1.16.0
slackclient==2.5.0
sniffio==1.2.0
sortedcontainers==2.4.0
SQLAlchemy==1.3.24
SQLAlchemy-Utils==0.36.8
sqlparse==0.3.0
tabulate==0.8.9
trio==0.19.0
trio-websocket==0.9.2
typing-extensions==3.10.0.2
urllib3==1.26.7
vine==1.3.0
webencodings==0.5.1
Werkzeug==1.0.1
wsproto==1.0.0
WTForms==2.3.3
WTForms-JSON==0.3.3
yarl==1.7.0
zipp==3.6.0



I execute:
superset run -p 8089 --with-threads --reload --debugger

_Login in:_
http://localhost:8089/superset/welcome/

_I execute:_
http://localhost:8089/api/v1/dashboard/export/?q=[5]  

It works.

_I execute:_

http://localhost:8089/api/v1/dashboard/export/?q=[1]
I have the message: {"message":"Fatal error"}

**Comment by rusackas** [comment]
Seems to be working just fine in Superset 2.0.1 as far as I can currently tell. Worth noting, perhaps, that I have the `VERSIONED_EXPORT` flag turned on. If you're still encountering this behavior in newer versions, let us know here or on Slack, and we can re-open this issue with additional/updated details. Thanks!
