### ISSUE TITLE
An error is reported when querying the SAP HANA database.

### ISSUE THREAD

**Issue by tiexiw** [apache/superset#17339]
The SAP HANA database query data reported an error, and the query statement was placed in another ide to return the correct result.

#### How to reproduce the bug

1. Install the SAP Hana SQLAlchemy driver.
2. Configuration data information: hana://HC_DW:XXXXXXXXXX@192.172.1.23:30015
3. Create data set: An error occurred while creating data set s: Unable to create data set.
4. SQL editor query data: hana error:'pyhdbcli.Cursor' object has no attribute'tzinfo_factory'.

### Expected results

Return a preview of the query data result.

### Actual results

Error message is returned.

### Environment

(please complete the following information):

- browser type and version: Chrome 94.0.4606.61
- superset version: `superset 1.3.2`
- python version: `python 3.8.5`
- node.js version: `node v12.20.0`
- any feature flags active:

**Comment by junlincc** [comment]
Hi @tiexiw, thanks for reporting. we prioritize db related issues based on the DB's popularity and usage. SAP HANA is a bit low on both currently, so we may not be able to get to it anytime soon. If you and your team are interested in providing a solution, feel free to reach out, we will definitely help push it forward. :) also, let us know if you need help navigating the codebase

**Comment by rusackas** [comment]
Closing as stale since we haven't had any reports to corroborate this issue in over a year. If you're still facing it in current era Superset (e.g. 2.0.1), we can most certainly re-open it!
