### ISSUE TITLE
Get the data that is shown in a specific viz

### ISSUE THREAD

**Issue by alicehua11** [apache/superset#17346]
When viewing a visualization, it would be helpful to get a raw output if the data that is being visualized and able to export as a csv for example. 

For example: when viewing a max number of some dataset col, we would like to see the raw data where that max number is extracted from without having to go on a hunt over to SQLlab.

**Comment by srinify** [comment]
Hey @alicehua11 are you hoping to extract the raw data or the aggregated data that Superset is using specifically for the chart?

**Aggregated data**
For the aggregated data, the .csv button while you're Explore accomplishes just this: https://share.descript.com/view/K1Ds1f8QPds

**Raw data**
For raw data, this is tricky if you think about it. The raw data pre-aggregated could be millions or *billions* of rows. Exporting that much data is technically very difficult and also a massive strain on your database (which is also why pretty much no BI tool out there will let you export more than a few thousand rows of the raw data).

One escape valve for you that could get you more mileage is to write the raw query in SQL Lab, remove the row limit, and export from SQL Lab. You'll be able to export quite a number of rows this way!

**Comment by alicehua11** [comment]
Hey @srinify, I'm looking for the Raw data from the chart, just a single row on where that max number comes from for our example, not all rows. 
One way I to get this is do a separate query in SQL Lab for the row to which the chart shows a max for. I was thinking that it would be helpful if we have this feature for getting that specific row without having to do an additional query.

**Comment by junlincc** [comment]
<img width="1471" alt="Screen Shot 2021-11-10 at 10 42 54 PM" src="https://user-images.githubusercontent.com/67837651/141250522-81ee36b1-8b50-4943-b8f4-40ed015c1b82.png">
Have you tried the clipboard in the south table, view sample tab?

**Comment by alicehua11** [comment]
This is what I mean originally. 
For our use case, if we can find out which row it is that took 233.26 sec to process, that would allow us to pin down the problem in our model. Does this make sense what the ask is?
![image](https://user-images.githubusercontent.com/43593804/141426135-c19c93bc-01d3-4663-be28-fe42e59fdf9f.png)

**Comment by srinify** [comment]
Hi @alicehua11 that makes sense. Have you seen Junlin's suggestion? That data view will show you the final results data before Superset visualizes it.

**Comment by srinify** [comment]
Closing this thread for now, as this isn't an "Issue" per say :)

If you'd like more guidance here Alice, you're welcome to ping me in the Superset Slack community (https://join.slack.com/t/apache-superset/shared_invite/zt-uxbh5g36-AISUtHbzOXcu0BIj7kgUaw). I'm "Srini Kadamati" in the Slack.
