### ISSUE TITLE
unable to update dataset metric's label via the rest PUT api

### ISSUE THREAD

**Issue by xingyuli** [apache/superset#17390]
It's not possible to update dataset metric's label (i.e., verbose_name) via the PUT API.

#### How to reproduce the bug

Visit the online rest documentation. You could see the payload is not able to receive verbose_name:

![image](https://user-images.githubusercontent.com/3337431/141077783-8d93d2cd-c160-4ded-8f9e-e4b41d7bdf81.png)

### Expected results

Possible to update the metric label (verbose_name).

### Actual results

Unable to do so.

#### Screenshots

See above.

### Environment

(please complete the following information):

- browser type and version:
- superset version: 1.1.0(which I'm using), and the latest version from the online rest doc

**Comment by junlincc** [comment]
Hi @xingyuli, thanks for reporting the issue! 
I'm not familiar with this functionality - edit dataset via the rest PUT api. While I loop the domain expert in, would you mind giving some more details 1) your use case 2) is there a workaround that you may be aware of? thanks

**Comment by xingyuli** [comment]
> Hi @xingyuli, thanks for reporting the issue! I'm not familiar with this functionality - edit dataset via the rest PUT api. While I loop the domain expert in, would you mind giving some more details 1) your use case 2) is there a workaround that you may be aware of? thanks

The rest PUT API has been used to sync from one dataset to another dataset. These two datasets refer two tables which are created by absolutely same ddl statement. You may think of these datasets as blue-green (or prod-vs-backup) version against each other. I have so many datasets created via the GUI, but I wish to programmatically  maintain the plenty of datasets.

As it's not possible to specify the metric's label (verbose_name) via the API, I have to update them one by one, going through all the datasets, which is quite time consuming and convenient. As far as I see, I think there is no workaround to do this.

For wider insight, Superset is missing features of sync one set of datasets to another set of datasets, which would be useful for cases e.g.,

- blue-green dataset
- full dataset and its hot dataset (which means a subset of whole dataset)

**Comment by villebro** [comment]
Repro'd - working on this now
