### ISSUE TITLE
NameError: name 'AUTH_OAUTH' is not defined

### ISSUE THREAD

**Issue by code23rus** [apache/superset#17401]
I want to set up OAuth2 authorization, but it not work.

#### How to reproduce the bug

1. Install superset according to the instructions: https://superset.apache.org/docs/installation/installing-superset-using-docker-compose
2. According documentation https://superset.apache.org/docs/installation/configuring-superset add the lines to the end of the superset_config.py file:

	AUTH_TYPE = AUTH_OAUTH
	OAUTH_PROVIDERS = [
		{   'name':'egaSSO',
			'token_key':'access_token',
			'icon':'fa-address-card', 
			'remote_app': {
				'client_id':'myClientId',
				'client_secret':'MySecret',
				'client_kwargs':{
					'scope': 'read'              
				},
				'access_token_method':'POST', 
				'access_token_params':{        
					'client_id':'myClientId'
				},
				'access_token_headers':{   
					'Authorization': 'Basic Base64EncodedClientIdAndSecret'
				},
				'api_base_url':'https://myAuthorizationServer/oauth2AuthorizationServer/',
				'access_token_url':'https://myAuthorizationServer/oauth2AuthorizationServer/token',
				'authorize_url':'https://myAuthorizationServer/oauth2AuthorizationServer/authorize'
			}
		}
	]
	AUTH_USER_REGISTRATION = True
	AUTH_USER_REGISTRATION_ROLE = "Public"

3. Restart docker-compose containers

	superset_app            | NameError: name 'AUTH_OAUTH' is not defined
	superset_app            | Failed to create app
	superset_app            | Traceback (most recent call last):
	superset_app            |   File "/app/superset/app.py", line 34, in create_app
	superset_app            |     app.config.from_object(config_module)
	superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask/config.py", line 174, in from_object
	superset_app            |     obj = import_string(obj)
	superset_app            |   File "/usr/local/lib/python3.8/site-packages/werkzeug/utils.py", line 568, in import_string
	superset_app            |     __import__(import_name)
	superset_app            |   File "/app/superset/config.py", line 1303, in <module>
	superset_app            |     import superset_config  # pylint: disable=import-error
	superset_app            |   File "/app/docker/pythonpath_dev/superset_config.py", line 116, in <module>
	superset_app            |     AUTH_TYPE = AUTH_OAUTH
	superset_app            | NameError: name 'AUTH_OAUTH' is not defined
	superset_app            | [2021-11-11 09:58:28 +0000] [12] [ERROR] Exception in worker process
	superset_app            | Traceback (most recent call last):
	superset_app            |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
	superset_app            |     worker.init_process()
	superset_app            |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
	superset_app            |     super().init_process()
	superset_app            |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
	superset_app            |     self.load_wsgi()
	superset_app            |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
	superset_app            |     self.wsgi = self.app.wsgi()
	superset_app            |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
	superset_app            |     self.callable = self.load()
	superset_app            |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
	superset_app            |     return self.load_wsgiapp()
	superset_app            |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
	superset_app            |     return util.import_app(self.app_uri)
	superset_app            |   File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 411, in import_app
	superset_app            |     app = app(*args, **kwargs)
	superset_app            |   File "/app/superset/app.py", line 44, in create_app
	superset_app            |     raise ex
	superset_app            |   File "/app/superset/app.py", line 34, in create_app
	superset_app            |     app.config.from_object(config_module)
	superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask/config.py", line 174, in from_object
	superset_app            |     obj = import_string(obj)
	superset_app            |   File "/usr/local/lib/python3.8/site-packages/werkzeug/utils.py", line 568, in import_string
	superset_app            |     __import__(import_name)
	superset_app            |   File "/app/superset/config.py", line 1303, in <module>
	superset_app            |     import superset_config  # pylint: disable=import-error
	superset_app            |   File "/app/docker/pythonpath_dev/superset_config.py", line 116, in <module>
	superset_app            |     AUTH_TYPE = AUTH_OAUTH
	superset_app            | NameError: name 'AUTH_OAUTH' is not defined
	superset_app            | [2021-11-11 09:58:28 +0000] [12] [INFO] Worker exiting (pid: 12)
	superset_app            | [2021-11-11 09:58:28 +0000] [10] [INFO] Shutting down: Master
	superset_app            | [2021-11-11 09:58:28 +0000] [10] [INFO] Reason: Worker failed to boot.

### Environment

Environment latest, according latest docker-compose images.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by kamalkeshavani-aiinside** [comment]
You need to import `AUTH_OAUTH` in your config file.
```
from flask_appbuilder.security.manager import AUTH_OAUTH
```

**Comment by code23rus** [comment]
Thanks for the answer. I added import but now another error:

	Failed to create app
	superset_worker         | Traceback (most recent call last):
	superset_worker         |   File "/app/superset/app.py", line 37, in create_app
	superset_worker         |     app_initializer.init_app()
	superset_worker         |   File "/app/superset/initialization/__init__.py", line 594, in init_app
	superset_worker         |     self.init_app_in_ctx()
	superset_worker         |   File "/app/superset/initialization/__init__.py", line 557, in init_app_in_ctx
	superset_worker         |     self.configure_fab()
	superset_worker         |   File "/app/superset/initialization/__init__.py", line 634, in configure_fab
	superset_worker         |     appbuilder.init_app(self.superset_app, db.session)
	superset_worker         |   File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/base.py", line 202, in init_app
	superset_worker         |     self.sm = self.security_manager_class(self)
	superset_worker         |   File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/sqla/manager.py", line 54, in __init__
	superset_worker         |     super(SecurityManager, self).__init__(appbuilder)
	superset_worker         |   File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/manager.py", line 257, in __init__
	superset_worker         |     from authlib.integrations.flask_client import OAuth
	superset_worker         | ModuleNotFoundError: No module named 'authlib'
	superset_worker         | 2021-11-12 11:44:07,533:ERROR:superset.app:Failed to create app
	superset_worker         | Traceback (most recent call last):
	superset_worker         |   File "/app/superset/app.py", line 37, in create_app
	superset_worker         |     app_initializer.init_app()
	superset_worker         |   File "/app/superset/initialization/__init__.py", line 594, in init_app
	superset_worker         |     self.init_app_in_ctx()
	superset_worker         |   File "/app/superset/initialization/__init__.py", line 557, in init_app_in_ctx
	superset_worker         |     self.configure_fab()
	superset_worker         |   File "/app/superset/initialization/__init__.py", line 634, in configure_fab
	superset_worker         |     appbuilder.init_app(self.superset_app, db.session)
	superset_worker         |   File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/base.py", line 202, in init_app
	superset_worker         |     self.sm = self.security_manager_class(self)
	superset_worker         |   File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/sqla/manager.py", line 54, in __init__
	superset_worker         |     super(SecurityManager, self).__init__(appbuilder)
	superset_worker         |   File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/manager.py", line 257, in __init__
	superset_worker         |     from authlib.integrations.flask_client import OAuth
	superset_worker         | ModuleNotFoundError: No module named 'authlib'
	superset_worker         | Error:
	superset_worker         | Unable to load celery application.
	superset_worker         | The module authlib was not found.
	
Also i installed authlib in superset container

	docker-compose exec superset bash
	pip install Authlib
	
but the error remained.

**Comment by aniaan** [comment]
What you need is to `pip install authlib` when the container starts, not afterwards.
You can do this,
1.  `echo "Authlib" > ./docker/requirements-local.txt`
2. start docker-compose

https://github.com/apache/superset/blob/34d7f0a860caa254f45bec55dc893f8a5997b8cb/docker/docker-bootstrap.sh#L21-L37

**Comment by code23rus** [comment]
Thanks for the answer. 
I seem to have configured authorization and my user is being created with the Gamma role.
But now not work local authentication with user/password. 
How can I make local authorization work too?

**Comment by aniaan** [comment]
It seems that oauth and local can only choose one at present

**Comment by code23rus** [comment]
Thank you very much for your help.

**Comment by yunszhang** [comment]
thanks very much
