### ISSUE TITLE
can not find 1.0 version

### ISSUE THREAD

**Issue by qinlz-1** [apache/superset#17418]
### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

/usr/local/bin/pip3.6 install apache-superset==
Collecting apache-superset==
  Could not find a version that satisfies the requirement apache-superset== (from versions: 0.34.0, 0.34.1, 0.35.1, 0.35.2, 0.36.0, 0.37.0, 0.37.1, 0.37.2, 0.38.0, 0.38.1)

**Comment by srinify** [comment]
Hi there, I've encountered this issue whenever I'm on an older Python version. Python 3.7+ (ideally 3.8) is recommended:

https://pypi.org/project/apache-superset/
