### ISSUE TITLE
HTML not displaying in Markdown when RBAC flag is TRUE

### ISSUE THREAD

**Issue by LalaGabor** [apache/superset#17421]
#### How to reproduce the bug

1. Enable Role based access control
2. Create a Dashboard
3. Create a markdown Field in the dashboard
4. Write in the markdown field: 123
5. Result: 123 is displayed in the markdown field
6. Write in the markdown Field: <h1>123</h1>

### Expected results

Text: 123 is displayed as a header in the markdown field

### Actual results

No Text is displayed

#### Screenshots
![image](https://user-images.githubusercontent.com/44199231/141434516-1296b475-2f36-44a1-a00c-6d33150e491f.png)
![image](https://user-images.githubusercontent.com/44199231/141434617-480a779a-86f0-4272-bf20-da218990603a.png)

### Environment

(please complete the following information):

- browser type and version: Firefox
- superset version: 1.2
- any feature flags active: RBAC

**Comment by LalaGabor** [comment]
Hi, just wanted to add that Escape Markdown is set to FALSE and Display Markdown is set to TRUE

**Comment by rusackas** [comment]
This does not appear to be reproducible in the newer versions of Superset. I'll call it resolved, but let me know if you still see this somehow happening in 2.0.1 or 1.5.2. Thanks!
