### ISSUE TITLE
SQLLAB AutoComplete: add space after double quotation mark

### ISSUE THREAD

**Issue by likecodingloveproblems** [apache/superset#17435]
autocomplete feature in sqllab add space after selection it works nice when there is not any ", but when the name is within a double quotation marks, the desired behaviour is adding space after double quotation.

### Environment

(please complete the following information):

- browser type and version: Chrome Version 95.0.4638.69 (Official Build) (64-bit)
- superset version: 
- python version: 3.8.12
- node.js version: `node -v`

**Comment by rusackas** [comment]
This does indeed still seem to be happening on current-era Superset. Curious if @yousoph @eschutho have heard any complaints about this one.

**Comment by Charlygraphy23** [comment]
Can you provide some more details, how to reproduce the issue?

**Comment by rusackas** [comment]
The repro steps are:
* type a double quote
* start typing a column for it to auto complete
* click/tab to let autocomplete happen
* observe that the space is inside the quotes, rather than outside.

Here's a GIF to illustrate
![space placement](https://github.com/apache/superset/assets/812905/3537e15b-ae9c-4cf1-8d64-710119a3b75b)

**Comment by AnalogAnt** [comment]
I'd like to help fix this bug. Can you guide me?

**Comment by rusackas** [comment]
@AnalogAnt that would be great... what kind of guidance do you need? I have no idea what's causing the issue, but if you can track it down in the code, I'm happy to help you through the PR process. Please feel free to reach out on the `#contributing` channel on [Superset Slack](http://bit.ly/join-superset-slack) if you want to talk about that process, or start a thread in `#debug-together` if you want help with the diagnostic parts.

**Comment by AnalogAnt** [comment]
I need help identifying the part of the code to change for the bug fix. Being new to open source, I could use some guidance.

**Comment by bgreenlee** [comment]
I can't reproduce this in 3.1.0 or HEAD.

**Comment by rusackas** [comment]
Same here... seems we're good now!
