### ISSUE TITLE
[color consistency][pie chart] Confused color behavior When #series is one more than #color in pie chart

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#17443]
When #series is one more than #color, pie chart has 2 consecutive same color

#### How to reproduce the bug

1. Go to cleaned sales data
2. create a pie chart with Metric for count(*) and group by month
3. Select color theme Echart v4.x colors
4. Observe the color of the 1st section and last section on pie chart

### Expected results
1st section and last section in pie chart in different color 

### Actual results

1st section and last section in pie chart in same color and seem connected 

#### Screenshots

<img width="1790" alt="Screen Shot 2021-11-15 at 6 11 53 PM" src="https://user-images.githubusercontent.com/81597121/141883669-94b5d1ab-87fb-48ce-8caa-e0ef95f870da.png">

### Environment

(please complete the following information):

- browser type and version:
- superset version: master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Optimistically closing this since there has been a lot of progress made in this area since this was filed. @jinghua-qa or @geido please feel free to re-open if you observe/suspect this is still an issue.

**Comment by rusackas** [comment]
Optimistically closing this since there has been a lot of progress made in this area since this was filed. @jinghua-qa or @geido please feel free to re-open if you observe/suspect this is still an issue.
