### ISSUE TITLE
Changing the language of Superset doesnt change the month's language in a chart

### ISSUE THREAD

**Issue by imanollew** [apache/superset#17447]
Changing the language of Superset doesnt change the months language in a chart

#### How to reproduce the bug

1. Enable Languages on Superset, by modifying the file "config.py"; adding LANGUAGES = { "en": {"flag": "us", "name": "English"},"es": {"flag": "es", "name": "Spanish"}}

2. Click on the flag, switch the language.
3. Now, the whole interface is in the desired language EXCEPT the months on any kind of chart.

### Expected results

The name of each month should be in my desired language.

### Actual results

The name of each month is still in english.

![ss1](https://user-images.githubusercontent.com/31854621/142002612-90f440da-ca64-4794-86f7-5b9222c198c6.png)
### Environment

(please complete the following information):

- firefox:
- superset version: 1.3.0
- python version: Python 3.7.11
- node.js version: v12.22.2
- any feature flags active:  "ALERT_REPORTS": True,
			               "ENABLE_TEMPLATE_PROCESSING": True,
			               "DASHBOARD_NATIVE_FILTERS": True,
                                       "VERSIONED_EXPORT":True,
			                "DASHBOARD_RBAC":True

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X ] I have reproduced the issue with at least the latest released version of superset.
- [X ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing this as stale, BUT there's hope! Now that Superset is a monorepo, it's MUCH easier to make charts support translation... there have been a flurry of such PRs lately, and I'm hopeful they improve the situation for you. If you see more of these that need help and want to contribute, I can find some example PRs, and we can certainly help review PRs if you're willing to keep things going in this positive direction!

**Comment by matheusbsilva** [comment]
@rusackas Any updates on this feature request? If not, can you give a direction on how can I add this feature?
