### ISSUE TITLE
[heatmap] color range is not reflecting the metric range correctly

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#17448]
In heatmap, the color range for the metric seems not correct, I create a heatmap and the metric is range from 1-500, i saw metric with value 26 is same color as metric with value 219

#### How to reproduce the bug

1. create heapmap 
2. select show value 
3. change color theme

### Expected results

color range will reflect the metric range correctly

### Actual results

color range is not reflecting the metric range

#### Screenshots

<img width="1161" alt="Screen Shot 2021-11-16 at 8 25 28 AM" src="https://user-images.githubusercontent.com/81597121/142025942-95594c26-f2bc-4195-8688-b17f3ba81bfd.png">

### Environment

(please complete the following information):

- browser type and version:
- superset version: master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
@yousoph did we decide if there were additional changes to be made in this area? I believe we did verify that the colors here are _correct_ but just difficult to interpret. We changed some of the language in the controls to better clarify the intent, but I'm not sure if that effectively resolves this issue or not. 

@jinghua-qa what are your thoughts here.... it's a pretty stale issue, and _some_ improvements have been made. Is it closeable?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
