### ISSUE TITLE
How to i add Regression chart?

### ISSUE THREAD

**Issue by Geetha-Ponnuvel** [apache/superset#17459]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by villebro** [comment]
Hi @Geetha-Ponnuvel - unfortunately Superset does not currently support adding a regression fit to charts. If you wish to propose adding this feature, please fill out all the required fields in the feature request template.
