### ISSUE TITLE
When importing a dashboard, it has no owner

### ISSUE THREAD

**Issue by imanollew** [apache/superset#17467]
When importing a dashboard, it has no owner.

#### How to reproduce the bug
By UI:
1. Go to dashboards list
2. Click on "import dashboard"
3. Select the zip file
4. Check the dashboard list again. If you are using an admin user you will be able to see the dashboard. It wont have an owner. If you are not an admin you wont be able to see the dashboard.

By CLI:

1. superset import-dashboards -p /home/superset/superset-1.3.0/dash_imp/dashboard_export_20211117T190343.zip --username user1
2. Check the dashboard list. If you are using an admin user you will be able to see the dashboard. It wont have an owner. If you are not an admin you wont be able to see the dashboard.
### Expected results

The expected result is to have an exported dashboard and it has to have an owner.

### Actual results

The exported dashboard has no owner.

#### Screenshots

As you can see in the picture, the dashboard has no owners.

![issue3](https://user-images.githubusercontent.com/31854621/142273591-ebf4b8a1-3e69-497c-b6d6-d69c0fbc807f.jpg)
###Environment

(please complete the following information):

    firefox:
    superset version: 1.3.0
    python version: Python 3.7.11
    node.js version: v12.22.2
    any feature flags active: "ALERT_REPORTS": True,
    "ENABLE_TEMPLATE_PROCESSING": True,
    "DASHBOARD_NATIVE_FILTERS": True,
    "VERSIONED_EXPORT":True,
    "DASHBOARD_RBAC":True

###Checklist

Make sure to follow these steps before submitting your issue - thank you!

    [X ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
    [X ] I have reproduced the issue with at least the latest released version of superset.
    [X ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by andrzejmartyna** [comment]
I believe this was fixed here: https://github.com/apache/superset/pull/16656
