### ISSUE TITLE
does superset support multi-lang?

### ISSUE THREAD

**Issue by stormszhang** [apache/superset#17475]
I did set my default lang to zh, but it did not work. 

![image](https://user-images.githubusercontent.com/10903558/142348012-1220326b-6282-45c7-bd98-5a15e37705bb.png)

and there is no language switch

![image](https://user-images.githubusercontent.com/10903558/142348362-aa5ebef0-9801-4de2-bdc7-d5574feab718.png)

**Comment by junlincc** [comment]
@stormszhang https://github.com/apache/superset/issues/2242
