### ISSUE TITLE
SIP-74 sub-proposal: Create missing APIs : Roles/Users/ row level security

### ISSUE THREAD

**Issue by suddjian** [apache/superset#17487]
Originally added under "please consider" by @amitmiran137. See [SIP-74](https://github.com/apache/superset/issues/17081).

I think that adding new API endpoints is generally not considered a breaking change, therefore this does not need to be included in the list of 2.0 breaking changes and could be implemented any time. Amit, do you agree? Or if it truly is a breaking change, would you expand more on the idea?

**Comment by amitmiran137** [comment]
I agree that this is an independent task that don't involve any breaking changes and is more an enhancement

**Comment by rusackas** [comment]
I believe this is a lingering task from the 2.0 release process, and doesn't comprise an immediate bug or body of work that anyone's signed up for. It also doesn't sound like a breaking change that'll be carried into 3.0, so I'll just close it. If we need an Issue for this, more context on exactly what needs to be carried out would be appreciated.
