### ISSUE TITLE
SIP-74 sub-proposal: Migrate away from /superset endpoints

### ISSUE THREAD

**Issue by suddjian** [apache/superset#17486]
See [SIP-74](https://github.com/apache/superset/issues/17081).

This was originally added to the "to consider" column by @craig-rueda. It sounds like the work required to do this is just deleting `/superset` from the route names everywhere. Is there more to it than that?

**Comment by nytai** [comment]
this seems like a huge task, lot of endpoint on the `/superset` api are still in use. Is the idea that we will break existing chart/dashboard/explore links or will setting up redirects to the new urls?

**Comment by rusackas** [comment]
Closing this as stale, but it seems obsolete anyway since it was created for a project board. If this has work we want to consider for 3.0, we should add a new proposal to that board instead. Thanks all!
