### ISSUE TITLE
 The upload excel button is not showing, I can only upload the CSV to Apache Superset 1.3.2

### ISSUE THREAD

**Issue by jedgarccoa** [apache/superset#17494]
1. Go to Data and try upload Excel file,  but the button does not show.

![Sin título](https://user-images.githubusercontent.com/34683815/142724186-9b7e78ec-6b9e-482a-a77d-186b5f038eb6.png)

### Expected results

Uplod excel file 

#### 

### Environment

- Google Chrome Versión 95.0.4638.69
- superset version: `1.3.2`
- python version: `3.8.1`
- OS Ubuntu Server 20.0.4

The installation is on venv environment.

**Comment by aniaan** [comment]
This is not a bug, first make sure you install the `xlrd` dependency, you can execute `pip install apache-superset[excel]` or `pip install xlrd`

code ref: 
https://github.com/apache/superset/blob/66d756955b961ed8dd379783f453d1f2531fad9e/superset/initialization/__init__.py#L393-L411

**Comment by junlincc** [comment]
Hey @aniaan thank you for helping and answering question in Superset community. We notice that if recently adopted Superset and actively contributing. Please join our webinar in Dec if you want to get on a path to committer-ship. https://www.meetup.com/Global-Apache-Superset-Community-Meetup/events/282147090/

You can also reachout to me on Slack to know more. Thanks!
