### ISSUE TITLE
Filter mapping does not apply when configuring charts on nesting tabs level 3 or more 

### ISSUE THREAD

**Issue by TechAuditBI** [apache/superset#17508]
While trying to configure filter mapping on nesting tabs structure everything works perfectly until I try to configure charts on level 3 and more.

Superset ver. 1.3.2

P.S. I think my description provides enough info for bug understanding, please ask for more details if it does not.

**Comment by geido** [comment]
Hello @TechAuditBI please follow the template provided when submitting issues. I think the information provided are not sufficient. Can you provide screenshots or videos of what you are experiencing?
