### ISSUE TITLE
for pie chart, api: /superset/explore_json/ return {"error":"'pie'"}, but for dist_bar chart it works well

### ISSUE THREAD

**Issue by wanwengang** [apache/superset#17519]
### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: 1.0
- python version: 3.8.12 
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
Hey, please try submitting the issue again with bug template all filled out
