### ISSUE TITLE
Why export is YAML vs JSON in  superset

### ISSUE THREAD

**Issue by Narendra678** [apache/superset#17526]
#### How to reproduce the bug
When i export report it is downloading as YAML and it is accepting only JSON to import.

### Expected results
When download it should be as JSON
###what you expected to happen.
When download it should be as JSON
### Actual results
It is downloading as YAML
what actually happens.

### Environment

(please complete the following information):

- browser type and version: 
- superset version: `superset version`: 1.3.1
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@eschutho Hi Elizabeth, I remember we used to have it downloaded in JSON format, is this change recent? Is there any documentation that can explain why we go with YAML? Thanks!

**Comment by srinify** [comment]
Hi @Narendra678 do you have the `VERSIONED_EXPORT` flag enabled? This should export all relevant assets as gzipped JSON files!

https://github.com/apache/superset/blob/master/RESOURCES/FEATURE_FLAGS.md#in-testing

Here's how you can enable feature flags:

https://superset.apache.org/docs/installation/configuring-superset#feature-flags

**Comment by junlincc** [comment]
@srinify I tried on our Pro, it's also YAML export file. Which is strange....

**Comment by srinify** [comment]
Oh that's right, YAML is actually the direction the project wants to go in for export. Not sure about Import tho :/

**Comment by Narendra678** [comment]
C

> Hi @Narendra678 do you have the `VERSIONED_EXPORT` flag enabled? This should export all relevant assets as gzipped JSON files!
> 
> https://github.com/apache/superset/blob/master/RESOURCES/FEATURE_FLAGS.md#in-testing
> 
> Here's how you can enable feature flags:
> 
> https://superset.apache.org/docs/installation/configuring-superset#feature-flags

But below article says it will not work. May i know how to enable JSON Export
https://github.com/apache/superset/pull/7935

**Comment by Narendra678** [comment]
Or can we change Import option to YAML?
As of now it is accepting only JSON. Please help here.

**Comment by junlincc** [comment]
@eschutho @betodealmeida 
did we announce the changes before rolling it out? I might have missed it

**Comment by betodealmeida** [comment]
To clarify a few things:

1. Import/export used to be a mix of YAML and JSON. YAML for datases and JSON for dashboards.
2. With the new feature flag `VERSIONED_EXPORT` the exports are ZIP files with YAML inside.
3. With the new feature flag `VERSIONED_EXPORT` Superset can import ZIP, YAML, or JSON (all currnet and previous export formats).

Now to my question: @Narendra678 you keep pointing at a ticket that has nothing to do with export, so it's still unclear to me what you want to do. You mention "export report", but it's not possible to export reports in Superset.

Can you clarify what you want to export?

**Comment by Narendra678** [comment]
I want to export dashboard to JSON format. See below screen please.

![image](https://user-images.githubusercontent.com/88739186/143371201-f0df1df0-aa60-4d8b-9d91-645ce470b93d.png)


Currently it is exporting as YAML format with Zip file.

**Comment by betodealmeida** [comment]
Thanks for clarifying!

To export the dashboard as JSON you need to turn off the `VERSIONED_EXPORT` feature flag in `superset_config.py`. The default is off, so someone must have turned it on. Are you the admin for your Superset instance? If you're not you would have to talk to them.

You can see the documentation for feature flags here: https://superset.apache.org/docs/installation/configuring-superset#feature-flags

**Comment by Narendra678** [comment]
Thanks much Buddy.

You mean i have to enable as below?

FEATURE_FLAGS = {
    'CLIENT_CACHE': False,
    'ENABLE_EXPLORE_JSON_CSRF_PROTECTION': True,
    'PRESTO_EXPAND_DATA': False,
}

**Comment by betodealmeida** [comment]
To turn it off:

```python
FEATURE_FLAGS = {
    "VERSIONED_EXPORT": False,
    # other keys would go here as well
}
```

**Comment by Narendra678** [comment]
Thanks Betodealmedia.

Can you please look on below issue
https://github.com/apache/superset/issues/17558

**Comment by eschutho** [comment]
It looks like this question has been resolved and a new follow up question posted. I am going to close this issue. Feel free to reopen if you feel there is still an issue/ bug here.
