### ISSUE TITLE
SSL_CERTIFICATE_VERIFICATION_FAILED

### ISSUE THREAD

**Issue by bbarclay** [apache/superset#17523]
Somewhere in the documentation. We should show that this error might occur with Mac. That it cannot use ssl with python to install test data. The way to solve it is to open python and click on install certificate. I've added a screenshot. SSL_CERTIFICATE_VERIFICATION_FAILED. The solution came from here. https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate

![Screen Shot 2021-11-23 at 2 52 56 AM](https://user-images.githubusercontent.com/374088/143003817-2d93fd81-e65c-4f57-80f2-1a84cd2c8d17.png)

**Comment by junlincc** [comment]
@bbarclay Thanks for suggesting! Would you like to contribute the change? It should be fairly easy. and @riahk can help you with it. Let us know if that works :)

**Comment by prakashcc** [comment]
@junlincc I am interested to contribute. Please let me know if I can do this.

**Comment by rusackas** [comment]
Closing this since the thread has gone cold, and it doesn't seem to still be an issue. @prakashcc if you're interested in contributing documentation updates for this or any other area, we would _more_ than appreciate the help! Thanks!
