### ISSUE TITLE
Documentation update for OAuth configuration

### ISSUE THREAD

**Issue by alejandroparra** [apache/superset#17544]
Hi there!

I was trying to set up the Custom OAuth2 Configuration but found out that one very important and necessary import is missing from the documentation in order to make the sample code work without any problem.

the import missing is with the library OAuth, after several hours of search de reading, importing only that library doesn't work, what it works is to import the full OAuth library from flask_appbuilder.security.manager.

I would like to open a pull request adding these lines of code

thanks for this awesome software

**Comment by mandeeplohan** [comment]
Is Oauth working for you? mine is not working and need help here?

**Comment by dpgaspar** [comment]
Hi,

You can find more detailed documentation here: https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-oauth

Going to close this now, feel free to open if this is still an issue
