### ISSUE TITLE
Helm installation uses `latest` tag by default

### ISSUE THREAD

**Issue by alexander-onesoil** [apache/superset#17540]
Using `latest` tag in helm releases is really dangerous story. I've faced the issue today, because new latest tag expects to have 'dashboards.certifiedBy" column in the table which leads to dashboards fetching error.
It's much more better to manage app version tag using standard helm approach.

#### How to reproduce the bug

1. Install helm release (current version)
2. Go to superset UI
3. Will have issue

### Expected results

Works

### Actual results

Dashboards fetching fails 

#### Screenshots

![image](https://user-images.githubusercontent.com/91125723/143283495-e5f804aa-fcc9-48d8-a8d2-162cd583ef5c.png)

```log
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column dashboards.certified_by does not exist
LINE 2: ..._position_json, dashboards.css AS dashboards_css, dashboards...
                                                             ^

[SQL: SELECT count(*) AS count_1
```

**Comment by quenchua** [comment]
Yes, this is an issue we faced as well. I noticed that the Superset version was frequently getting updated whenever the pods restarted.
We have now uploaded an image to ECR and pull from there each time.

**Comment by CarpathianUA** [comment]
Expiriencing the same

**Comment by CarpathianUA** [comment]
It's still actual

**Comment by NK74** [comment]
Same issue with ECS Setup (upgrade to 1.5.0)

**Comment by Noamstrauss** [comment]
Expiriencing the same issue

**Comment by cberge908** [comment]
Is this still recent? At least by looking at the current helm templates it should default to the appVersion of the chart:

https://github.com/apache/superset/blob/9a4839f45c6d9a2cae89f5c77b434910be129f48/helm/superset/templates/deployment.yaml#L88

**Comment by sfirke** [comment]
Can anyone confirm if this is still a current issue?

**Comment by sfirke** [comment]
Looks like @cberge908 is correct, there's the line he linked to which points to appVersion here, that gets bumped manually but consistently after official releases: https://github.com/apache/superset/blob/master/helm/superset/Chart.yaml#L18

Currently 3.1.0.  I'm going to close this as fixed.
