### ISSUE TITLE
Unexpected 

### ISSUE THREAD

**Issue by Narendra678** [apache/superset#17558]
#### How to reproduce the bug
Getting Unexpected error as below:

<html><head> <meta http-equiv="content-type" content="text/html;charset=utf-8"> <title>500 Server Error</title> </head> <body text=#000000 bgcolor=#ffffff> <h1>Error: Server Error</h1> <h2>The server encountered an error and could not complete your request.<p>Please try again in 30 seconds.</h2> <h2></h2> </body></html>

### Expected results
Should show data
what you expected to happen.

![image](https://user-images.githubusercontent.com/88739186/143541581-711b020e-74c9-4399-94eb-9f6c6a7e0707.png)

From past 5 days we are working on this but no luck. And it is happening some times.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`: 1.3.1
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by Narendra678** [comment]
Can i get reply on this? Please

**Comment by jhult** [comment]
@Narendra678,

1. What action is occurring when you receive this error? It looks like it may be occurring when trying to click to a tab on a dashboard.
2. When you receive this error, check the Superset server logs for any related errors and post them here.
