### ISSUE TITLE
Which docker tag I can use ?

### ISSUE THREAD

**Issue by ToryZhou** [apache/superset#17559]
**Describe the solution you'd like**
I need a stable docker tag to use. What is the stable tag?

Using the following comand will always update some features, This is a risk for us. so I need a stable tag to test and using on the production environment.
docker pull apache/superset

**Comment by srinify** [comment]
Hi @ToryZhou good question! I recommend the 1.3.2, which is the most recent stable release. 

- You can find all of the release versions here: https://github.com/apache/superset/releases
- This should be the tag for 1.3.2 in DockerHub: https://hub.docker.com/layers/apache/superset/1.3.2/images/sha256-459c653ce3db6931bd7f9911e2fbfb93f5385f815cddf63a897fcbc6d1d73f33?context=explore
