### ISSUE TITLE
How to connect to different database for different  with customers (e.g. via oAuth parameter or similar)

### ISSUE THREAD

**Issue by rickgoud** [apache/superset#17565]
Hi,

we are considering using this awesome tool as an environment to let different customer organizations get insight into their data. From a security/privacy perspective we have a separate DWH-table set per customer. Is there a way to use one Powerset-environment that connects to a different Postgresql database dependent on a characteristic of the user, e.g. passed along in an oAuth2 parameter or something similar?
Any help on how to realize this would be greatly appreciated, as I can imagine this being a requirement to many different organizations too?
Thanks!

**Comment by rickgoud** [comment]
Anyone any suggestions/tips/experiences to share?

**Comment by kamalkeshavani-aiinside** [comment]
You can ask your queries in https://github.com/apache/superset/discussions, instead of raising an issue.

**Comment by rickgoud** [comment]
Thanks! Started discussion here: https://github.com/apache/superset/discussions/17617

**Comment by kamalkeshavani-aiinside** [comment]
Thank you, please close this issue.
