### ISSUE TITLE
Error Installation : pip install apache-superset

### ISSUE THREAD

**Issue by jaspreetjhans** [apache/superset#17574]
Defaulting to user installation because normal site-packages is not writeable
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:877)'),)': /simple/apache-superset/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:877)'),)': /simple/apache-superset/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:877)'),)': /simple/apache-superset/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:877)'),)': /simple/apache-superset/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:877)'),)': /simple/apache-superset/
Could not fetch URL https://pypi.org/simple/apache-superset/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/apache-superset/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:877)'),)) - skipping
ERROR: Could not find a version that satisfies the requirement apache-superset (from versions: none)
ERROR: No matching distribution found for apache-superset
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:877)'),)) - skipping

**Comment by srinify** [comment]
Hi there @jaspreetjhans it looks like the computer or VM that you're running this on can't connect to the pypi.org servers. 

While this is frustrating, this isn't a bug :) so I'm closing this issue!
