### ISSUE TITLE
Converting chart types to each other. 

### ISSUE THREAD

**Issue by daydinodakent** [apache/superset#17571]
Is it possible to convert a certain chart type to other type. 

Example. bar chart to line chart or radar chart etc. Even chart to table or table to chart. Table to thenatic map, map to table 

![image](https://user-images.githubusercontent.com/29478810/143848135-52d7fbc0-9214-4ffb-bd95-761995e35c62.png)

**Comment by srinify** [comment]
Hi @daydinodakent this feature isn't available in Superset and isn't really on anyone's roadmap as far as I know.

I will say that in Explore (our no-code chart builder), if you switch chart types ... many of the column / settings for the chart are mapped over to the new chart type. So you can switch chart types more easily, which may emulate some of what you're looking for!
