### ISSUE TITLE
Can superset be deployed completely with front-end and backend separation

### ISSUE THREAD

**Issue by cdmikechen** [apache/superset#17588]
**Is your feature request related to a problem? Please describe.**

Cookies are subject to more and more strict restrictions on current browsers.
Is it possible to use the deployment mode of front-end and backend separation to enable the cookie by flask and use rest token?

**Describe the solution you'd like**

Reuse the rest interface without using cookie.

**Describe alternatives you've considered**

At present, the development of superset has separated python and react. During debugging, it also supports using `npm run dev server` to run a standalone front-end server and backend server. 
I think this model can also be used in production

**Additional context**

no

**Comment by junlincc** [comment]
Not sure if this is changed after monorepo? Brining in @zhaoyongjie

**Comment by amitmiran137** [comment]
You can't 
Superset frontend is still being served under the flask ecosystem in order to have basic context
