### ISSUE TITLE
[mixed time-series] Metric name is shown in legend instead of label

### ISSUE THREAD

**Issue by kamalkeshavani-aiinside** [apache/superset#17586]
#### How to reproduce the bug

1. Create a metric with a custom label
2. Use this metric in Mixed Time-series Chart

### Expected results

Custom label for metric is shown in legend.

### Actual results

Metric name is shown in legend.

#### Screenshots

![image](https://user-images.githubusercontent.com/74634977/144000668-24cd3025-4bf1-4ffd-834b-c05cb3e09d5d.png)

### Environment

(please complete the following information):

- browser type and version: Chrome 96
- superset version: `master`
- python version: `3.9`
- node.js version: `14.15.5`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

This issue is not present in other time-series echarts

**Comment by junlincc** [comment]
We would love to get a volunteer, it seems to be an easy fix. 
@zhaoyongjie is the community safe to work on the issue?

**Comment by Yahyakiani** [comment]
@junlincc I would like to work on this issue if it's available . Also, any direction regarding this issue would be appreciated. Thanks

**Comment by stephenLYZ** [comment]
There is a related pr can refer to, https://github.com/apache-superset/superset-ui/pull/1337 is to fix the timeseries chart, the logic is basically the same.

**Comment by Yahyakiani** [comment]
I am unable to reproduce this issue . The custom and default labels seem to be working in this case whenever they are enabled from the legend option. Perhaps I am doing something wrong ? @riahk @zhaoyongjie 
![superset](https://user-images.githubusercontent.com/42173629/144583007-735c2337-b587-4d05-84cb-af4113e22b00.PNG)

**Comment by kamalkeshavani-aiinside** [comment]
@Yahyakiani I think you have created a Custom SQL metric from explore view. The issue is with Custom metric, which can be added in Edit Dataset view.

**Comment by villebro** [comment]
It sounds like `verbose_name` isn't mapped

**Comment by Yahyakiani** [comment]
> @Yahyakiani I think you have created a Custom SQL metric from explore view. The issue is with Custom metric, which can be added in Edit Dataset view.

Thanks I found the issue
