### ISSUE TITLE
secure_filename return only ASCII so that superset can not export some chart/dashboard named like chinese or else characters not used english

### ISSUE THREAD

**Issue by cdmikechen** [apache/superset#17583]
#### How to reproduce the bug

1. Press `Export` in dashboard 
2. Open exported zip and find that some file names are removed. After checking the names, I found that non ASCII characters have been deleted.

### Expected results

The exported file needs to retain non ASCII text, otherwise some imported information will be lost.

### Actual results

Look Screenshots

#### Screenshots

![Xnip2021-11-30_11-39-26](https://user-images.githubusercontent.com/12069428/143981700-b136c905-4a26-4a25-bf88-8f7c3cb16614.jpg)

### Environment

(please complete the following information):

- browser type and version: Edge  93.0.961.44
- superset version:  1.0.1
- python version: 3.8.9
- node.js version: v17.0.1
- any feature flags active: no

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
I found the PR of the codes https://github.com/apache/superset/pull/11532
I think the codes may need to be modified to adapt to this situation.

**Comment by cdmikechen** [comment]
@stale No it is still a bug

**Comment by Gouwenbo** [comment]
When importing a compressed package of such content, get_contents_from_bundle function will ignore file names starting with. or _ , import may fail or be incomplete

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new/updated Issue or a PR to address the problem. At the very least, we would need a reproducible flow to replicate the bug and thus tackle it.
