### ISSUE TITLE
`401 Unauthorized` on route `/datasource/external_metadata_by_name/

### ISSUE THREAD

**Issue by jafournier** [apache/superset#17592]
Hi

I am currently using superset with `gitlab SSO`, everything is working fine with it, EXCEPT while doing a `sync column from source` , trying to sync my dataset (defined in AWS glue datacatalog).

The `sync` functionality was working so far.

I got a message saying `An error occured`.

While trying to see what's going on with api calls I see:

`401 Unauthorized` on route `/datasource/external_metadata_by_name/

However my user has been granted the `Admin` role.
I am using the superset docker image tagged `1.3.2`
<img width="737" alt="Screen Shot 2021-11-30 at 11 13 50" src="https://user-images.githubusercontent.com/16292862/144028313-673520d9-8d6c-4d31-a1de-b32200e0bfcf.png">

Thanks

**Comment by junlincc** [comment]
Hi, what do you mean by "While trying to see what's going on with api calls I see:" 

Can you provide detailed repro steps? thanks!

**Comment by villebro** [comment]
@jafournier do I understand correctly, that syncing the same dataset while authenticated via another authentication mechanism works fine, but not for GitLab SSO?

**Comment by jafournier** [comment]
Hi, actually doing a `superset init` fixed the permission issue.
