### ISSUE TITLE
Unable to access time_grain in custom SQL

### ISSUE THREAD

**Issue by dneelapareddy** [apache/superset#17598]
#### How to reproduce the bug

1. Go to 'Create Chart'
2. Click on 'METRICS' and select 'Custom SQL' tab

### Expected results

Should be able to access time_grain value

#### Screenshots

![image](https://user-images.githubusercontent.com/43841180/144085838-774a111b-2b5f-468b-96f2-cb2a799f938f.png)

**Comment by villebro** [comment]
@dneelapareddy have you set the `ENABLE_TEMPLATE_PROCESSING` config flag to `True`? See the docs for more info: https://superset.apache.org/docs/installation/sql-templating

**Comment by dneelapareddy** [comment]
@villebro I have enabled `ENABLE_TEMPLATE_PROCESSING` to `True`, 
I am able to get the `'{{ current_username() }}'` from custom sql,

![image](https://user-images.githubusercontent.com/43841180/144841057-348b6ceb-56a7-4065-af70-6e8f970abe1f.png)

But Jinja template is unable to evaluate `'{{ to_dttm }}' - '{{ from_dttm }}' AS Duration`

![image](https://user-images.githubusercontent.com/43841180/144840723-f4188384-4104-4f63-a2fc-fdda21286792.png)

I have even tried it in the SQL lab, but not working there too:
![image](https://user-images.githubusercontent.com/43841180/144841331-dd46dd67-46ee-4261-8306-339d4a617394.png)

Is there anything else i need to enable to get this working?

**Comment by villebro** [comment]
Which version are you on? I believe the template processor was until fairly recently only implemented in certain query controls, but should now be universally supported on the current master branch. See also this PR that added more temporal variables to the template processor context: #16680

**Comment by rusackas** [comment]
Closing due to lack of follow-up details after over a year. If this is still an issue, holler and we can re-open!

**Comment by villebro** [comment]
FYI this should be fully resolved on master branch (I can dig out the PRs if needed)
