### ISSUE TITLE
Superset over Clickhouse doesn't handle well nullable columns

### ISSUE THREAD

**Issue by yoavo-datricks** [apache/superset#17629]
When building a chert over a clickhouse dataset with nullable columns all columns are listed as just "nullable" without the actual data type.
![image](https://user-images.githubusercontent.com/72439961/144375901-b78a1120-128c-4d13-91e7-7c5da71e5f21.png)

### Expected results

The actual data types - Int, String, Array, etc...

### Environment

- browser type and version: Chrome
- superset version: 1.3.2
- clickhouse-alchemy - 0.16

This was solved here using the "get_datatype" enhancement but was never merged to the clickhouse.py, can it be pushed to 1.4?
https://github.com/HeinzMayer/superset/blob/1.0.MIC/superset/db_engine_specs/clickhouse.py

**Comment by rusackas** [comment]
@shreesham if you have time to look into this one, it would be greatly appreciated :)

**Comment by rusackas** [comment]
@andrey-zayats took a look at this and was unable to reproduce the issue. I'm going to go ahead and remove the `validation:required` label and close the issue. If anyone sees this happening in Superset 2.0.x or later, or on `master`, we're open to revisiting this conversation, re-opening the ticket, or triaging a new Issue with updated context. Thank you!

**Comment by jzhou-cognitiv** [comment]
Hi, sorry to comment on an old issue! 

I am getting the same problem, but only for Nullable(Float32) or Nullable(Float64) types in the ClickHouse table. Nullable(Int32) and other integer types work fine.

The type in Superset is Unknown and displays with a question mark. Specifically, I'd like to plot histograms for these columns.

superset version: 5.0.0
clickhouse-connect version: 0.10.0
