### ISSUE TITLE
Chart in this dashboard dont refresh

### ISSUE THREAD

**Issue by JoaquinPretell92** [apache/superset#17625]
Hello,

We are using Superset version 1.4.0rc1 and we deploy the next chart in our dashboard, but we saw its not refreshing by itself.

![6546546](https://user-images.githubusercontent.com/73810312/144325166-77e98aad-c9c3-4774-a6c9-ecac9d9f6b1b.PNG)

As you can see it has a message that its not refreshed by 19 hours, we hit the button but it didnt work the data didnt refresh. it has diferent records when we check the chart on the "charts section"

![6463546346436](https://user-images.githubusercontent.com/73810312/144325342-dd5f0033-d6ef-4d11-8caf-f9cdabd447e6.PNG)

We saw there is a sync button now for the dataset on the chart section and when we hit the button the chart on the dashboard get refresh but only work for one day. Today we have the same problem again. 

![643634643634](https://user-images.githubusercontent.com/73810312/144325663-ba668892-b4a2-4c7f-bb58-05ea2f3730b1.PNG)

We want to know if this is a bug or maybe something change in the configuration between versions.

Regards

**Comment by geido** [comment]
Hello @JoaquinPretell92 I could not reproduce this issue. Can you give us a little bit more information about your configuration please?

**Comment by rusackas** [comment]
Closing as stale since this couldn't be reproduced as of a year ago. If this is still an issue in 2.0.1, we can discuss re-opening it with updated repro steps. Thanks!
