### ISSUE TITLE
[Pivot 2]  fonts are not suited to numbers (Inter)

### ISSUE THREAD

**Issue by squalou** [apache/superset#17633]
## Screenshot

I've added a red vertical ruler so that you see the issue

![image](https://user-images.githubusercontent.com/4623644/144409765-5e880603-4305-49a4-8474-e5ea0e00030c.png)

## Description

As already explained in numerous issues, the use of 'Inter' font is problematic, it does not allow to align dates for instance,
and does not play nice with numbers either.

In my superset, I've changed `superset-frontend/src/assets/stylesheets/less/variables.less` to remove 'Inter'.
As a result it uses Helvetica, which is fine.

Except ! Go wonder why and how, Pivot Table V2 still uses 'Inter.'

At least I'd like a workaround to explain me how to build a superset docker image without Inter even for this viz.

## Design input

I'm not asking for marvelous fantasies, just having *aligned* data in table colums, for dates and numbers.

**Comment by suddjian** [comment]
Iter is quite full-featured and allows for [tabular numbers](https://rsms.me/inter/#features/tnum). We probably can/should figure out how to activate that rather than using a different font.

**Comment by squalou** [comment]
@suddjian that would be **awesome** and please consider checking other visualizations.

apparently pivot2 and others do not share the same css magic. Tabular numbers with Inter everywhere in tables would be fantastic

**Comment by squalou** [comment]
stale .. but true.
I'll check with 1.5.0 as soon as it's out

**Comment by rusackas** [comment]
This is fixed in the current Superset (and... probably a few versions prior, but definitely now). It still doesn't work in other areas for intricate reasons, but it _does_ work in the (newer) pivot table. :)
