### ISSUE TITLE
Closing all tabs on SQL Lab leaves the screen blank

### ISSUE THREAD

**Issue by villebro** [apache/superset#17630]
When closing all tabs on SQL Lab, the whole screen goes blank due to there not being a single open tab left. 

#### How to reproduce the bug

1. Go to SQL Lab
2. Close all tabs
3. Notice how the whole screen goes blank

### Expected results

A new empty tab should be opened automatically. The same can now be achieved by clicking on SQL Lab in the menu, which correctly opens an empty tab.

### Actual results

The screen goes blank

#### Video

https://user-images.githubusercontent.com/33317356/144376770-4872c145-5e57-4efc-9862-5e4909d58f4d.mp4

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by Yahyakiani** [comment]
@junlincc  Could I have this issue ? Furthermore, what is the expected solution for this problem ? Automatically open an empty SQL tab if tabs count falls to zero upon closing ?

**Comment by nytai** [comment]
@Yahyakiani Doesn't seem like anyone has taken it, go for it! Yes either recreating a new empty tab or just raising an error that the last tab cannot be closed should be enough

**Comment by yousoph** [comment]
https://github.com/apache/superset/pull/18817
