### ISSUE TITLE
How to run superset process in background or create a process

### ISSUE THREAD

**Issue by jaspreetjhans** [apache/superset#17648]
I am using 0.38 Version of Superset

Running below command but it is showing **"Error: No such command 'runserver'."** 
                    superset runserver -d --h 0.0.0.0 p 8088

**Comment by zhaoyongjie** [comment]
> 

The version-0.38 has been out-of-date, please update to the latest version.

You can input command: `superset`, to get all sub-command in the terminal.

**Comment by jaspreetjhans** [comment]
Thanks
