### ISSUE TITLE
Fill one chart into an entire row on dashboard

### ISSUE THREAD

**Issue by Max-beep** [apache/superset#17651]
**Is your feature request related to a problem? Please describe.**

I hope there is a way to change the size of the charts on the dashboard. Sometimes when my line/bar chart has a broader time frame  I'd hope it to fill out the entire row so the bars don't look super crowded. 
![image](https://user-images.githubusercontent.com/52082519/144727728-b9028a8d-fadd-4782-9a09-87a1cf5663e6.png)

**Describe the solution you'd like**

This is what I hope to happen: filling one chart into an entire row on the dashboard. 
![image](https://user-images.githubusercontent.com/52082519/144727209-42cb66bd-686b-43ff-bc3c-1c34580c39ae.png)

**Describe alternatives you've considered**
N/A
**Additional context**

**Comment by geido** [comment]
Hello @Max-beep I think you can. When Editing a Dashboard just drag the side of the Chart.
