### ISSUE TITLE
Track dashboard's RBAC role in CLI export/import

### ISSUE THREAD

**Issue by EBoisseauSierra** [apache/superset#17660]
## Problem

I build dashboards on a “dev” instance, export them, and import the archive on the “prod” one; all via CLI.
I grant access to these dashboards to certain roles using RBAC — i.e. I edit dashboard properties and add one (or more) user group(s) to the “Role” selector (e.g. `guest` in the example below):

![bépobépo_shadow](https://user-images.githubusercontent.com/37387755/144847565-b01a7b74-e9be-4d95-8533-772d6f727093.png)

However, **the dashboard's YAML file in the export does not include any mention of the role(s) I grant access to**.

So I then need to grant access to these roles again, after the exported archive get imported on “prod”.  
 
## Wished solution

I would like that **the imported dashboards grant the same RBAC authorisations as their exported counterpart**.

Practically, this means that I would like to:

- be able to track RBAC roles on the YAML file of an exported dashboard,
- be able to set RBAC roles of an imported dashboard, based on the imported YAML file data.

## Alternative

Manual work… but I'm afraid I'm lazy :wink: 

## Additional context

Both dev and prod are running Superset 1.3.2, alongside the following feature flags:

```python
FEATURE_FLAGS = {
    "VERSIONED_EXPORT": True,
    "DASHBOARD_RBAC": True,
}
```

**Comment by EBoisseauSierra** [comment]
I understand that this could have unwanted security implications, or may not always be wanted (e.g. if the roles are not the same in dev and in prod)… so this feature could be activated as an optional flag in the export and/or import CLI.

**Comment by geido** [comment]
Duplicates #17564
