### ISSUE TITLE
how to installing python_ldap in docker image ?

### ISSUE THREAD

**Issue by fschmid** [apache/superset#17669]
I try to integrate superset with a Samba AD LDAP Directory.

After adding the required configs to "docker/pythonpath_dev/superset_config.py" and adding "python-ldap" to "docker/requirements-local.txt" I get the following error when starting with "docker-compose -f docker-compose-non-dev.yml up":

superset_worker_beat    |   running build_ext
superset_worker_beat    |   building '_ldap' extension
superset_worker_beat    |   creating build/temp.linux-x86_64-3.8
superset_worker_beat    |   creating build/temp.linux-x86_64-3.8/Modules
superset_worker_beat    |   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=3.4.0 -DLDAPMODULE_AUTHOR=python-ldap project -DLDAPMODULE_LICENSE=Python style -IModules -I/usr/local/include/python3.8 -c Modules/LDAPObject.c -o build/temp.linux-x86_64-3.8/Modules/LDAPObject.o
superset_worker_beat    |   In file included from Modules/LDAPObject.c:3:
superset_worker_beat    |   Modules/common.h:15:10: fatal error: lber.h: No such file or directory
superset_worker_beat    |      15 | #include <lber.h>
superset_worker_beat    |         |          ^~~~~~~~
superset_worker_beat    |   compilation terminated.
superset_worker_beat    |   error: command 'gcc' failed with exit status 1
superset_worker_beat    |   ----------------------------------------
superset_worker_beat    |   ERROR: Failed building wheel for python-ldap
superset_worker_beat    | Failed to build python-ldap
superset_worker_beat    | ERROR: Could not build wheels for python-ldap which use PEP 517 and cannot be installed directly
superset_worker_beat    | WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
superset_worker_beat    | You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.

seem to be related with some missing libraries but no clue on how to fix this.

**Comment by ziggekatten** [comment]
Probably some libraries are missing in the Docker file.

Ensure you have the following in your Dockerfile
`RUN apt-get update && apt-get upgrade -y && apt-get install -y libsasl2-dev libldap2-dev libssl-dev `

Sidenote, we have spent two month trying to get LDAP to work with active directory and TLS with no success what so ever. Clearly broken.

**Comment by fschmid** [comment]
thx for the answer I have

RUN mkdir /app \
        && apt-get update -y \
        && apt-get upgrade -y \
        && apt-get install -y \
            build-essential \
            default-libmysqlclient-dev \
            libpq-dev \
            libsasl2-dev \
            libecpg-dev \
            libldap2-dev \
            libssl-dev \
        && rm -rf /var/lib/apt/lists/*

in my Dockerfile (apt-get upgrade,  libldap2-dev and libssl-dev were missing) but after "docker-compose -f docker-compose-non-dev.yml up --build --force-recreate" still the same error.

**Comment by srinify** [comment]
A good bet is to remove the old Docker image and re-build.

https://www.digitalocean.com/community/tutorials/how-to-remove-docker-images-containers-and-volumes

I'm closing this for now, as this is a Docker thing and not a Superset "issue"!

**Comment by romankevich** [comment]
@fschmid Has there been a solution to this issue? Still relevant
