### ISSUE TITLE
Dataset not visible to normal user when save it without specifying schema

### ISSUE THREAD

**Issue by airbots** [apache/superset#17666]
When we use sql editor to create a query and get the derived data. If we want to save it, Superset does not check if schema is not configured or not. It should. 

If we let be null and click "save as", the schema will be null. And non-superuser will never see this dataset anymore when they click the datasets on the navigation  bar and can not create a chart based on the derived data. 

### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by geido** [comment]
Hello @airbots thanks for reporting this issue. It appears that the scheme is always pre-selected in Superset and there is no way to clear it currently. This should ensure that your issue won't occur. Thank you!
