### ISSUE TITLE
It is not working inside iframe with different domain. It works in same domain and Direct URL access

### ISSUE THREAD

**Issue by cxsphereraja** [apache/superset#17668]
#### How to reproduce the bug

embed the below snippet into any place. it must work.

` <iframe src="https://analytics.abc.com/login?auth_code=123code&amp;redirect=https://analytics.abc.com/superset/dashboard/41/" width="100%" height="700"></iframe> `

I have tried and played around with CORS & Content Policy & CSRF & Session Cookies. Nothing works.

### Expected results

It must authenticate and show the superset dashboard.

### Actual results

![image](https://user-images.githubusercontent.com/79897931/145086580-31f0f4d0-2b8a-496d-b77a-66c05d02ab4a.png)

### Environment

(please complete the following information):

- browser type and version: chrome 96.0
- superset version: 0.35.1
- python version: 3.7.4
- node.js version: 10.4.1
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stack traces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by JyotsnaC** [comment]
We are seeing the same issue. Other observation to add is this happens only chrome . It works perfectly in Firefox and safari for us. Would like to get an estimate on when can we get the fix as we already see some tasks are focused on this defect.

**Comment by rusackas** [comment]
This should all now be supported by the Embedded SDK, if it wasn't fixed by other PRs anyway. Closing as stale, but if you still see this issue persist, we can revisit/reopen!

**Comment by lokeshMrudhul** [comment]
any  update on this
