### ISSUE TITLE
MAX of Date field returns null on Big Number Chart

### ISSUE THREAD

**Issue by michellethomas** [apache/superset#17667]
Big number chart is not working for finding the max of a date field. It returns `No data` instead of the date.

#### How to reproduce the bug

1. Create a big number chart
2. Create a metric with max() of a date field
3. Run chart

### Expected results
Chart should return a date

### Actual results
Chart returns `No data`

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

Similar issue to this one that was fixed a while ago: https://github.com/apache/superset/issues/11042

**Comment by michellethomas** [comment]
This is still an issue, the workaround for users for now is to use a table chart instead of a big number for displaying max of date, but it would be good to resolve this issue.

**Comment by rusackas** [comment]
I suspect that this has been resolved, but adding the appropriate validation tag and assigning to @yousoph for validation that this is behind us nowadays :)

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
