### ISSUE TITLE
[dashboard edit] edit native filter info (title, description etc) in metadata of dashboard properties is not updated 

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#17665]
I found a bug that edit native filter in metadata of dashboard properties did not reflect changes after save. See video for details:

#### How to reproduce the bug
Precondition: user has created native filter for dashboard

Steps:
1. Go to dashboard edit mode
2. Click on 3 dot menu and open dashboard properties
3. Scroll down to metadata section and change native filter information, for example native filter title
4. Save the change and save the dashboard, and look for the native filter information.

### Expected results

native filter information will be updated after edit metadata

### Actual results

native filter information is not updated after edit metadata

#### Screenshots

https://user-images.githubusercontent.com/81597121/144770187-2df63a4e-9f46-48f6-a568-b3acb5aa1e24.mov

### Environment

(please complete the following information):

- browser type and version:
- superset version: master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
This should be resolved, but @jinghua-qa if you still see this in testing, we can most certainly re-open.
