### ISSUE TITLE
[dragndrop] Clicking "show all" on explore left panel freezes page for large dataset

### ISSUE THREAD

**Issue by michellethomas** [apache/superset#17674]
If you are creating a chart on dataset with a large number of columns and metrics and you click "show all" on the left panel, the page freezes. We have a dataset that is quite large (> 1000 columns) so I'm not sure exactly at what point this happens.

#### How to reproduce the bug

1. Create a dataset with a large number of columns and metrics.
2. Create a chart for that dataset
3. Click on "show all" on the left panel

### Expected results

Left panel will show all columns.

### Actual results

Page freezes

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
These lists were virtualized at one point, and also the layout of these components have been tweaked significantly since this was opened. I'm assuming this is resolved, but if anyone sees it in 2.0.x, let's revisit in a new issue with updated repro steps (e.g. number of columns where it starts to hurt, etc.).
