### ISSUE TITLE
Slack links is expired

### ISSUE THREAD

**Issue by korjavin** [apache/superset#17677]
## Screenshot

![image](https://user-images.githubusercontent.com/148765/145108089-5ded12af-5dc5-4727-a7cf-7eab5b37802d.png)

## Description

Link to slack points to nothing

**Comment by srinify** [comment]
Thanks for pointing this out, I'll work on this now!

**Comment by srinify** [comment]
Thanks for catching this!

Included fix here: https://github.com/apache/superset/pull/17650

**Comment by etr2460** [comment]
resolved by https://github.com/apache/superset/pull/17650
