### ISSUE TITLE
Echart "Time-series" rolling function cumsum

### ISSUE THREAD

**Issue by suedschwede** [apache/superset#17682]
rolling function 'cumsum' wrong visualization

### Expected results

When I use "Line Chart" I get the correct visualization 

![image](https://user-images.githubusercontent.com/25843519/145188509-ad16350a-f6c1-4b1e-8878-32d60cc9a5d7.png)

### Actual results
When I use "Time-series Line Chart" the visualization is wrong
 
![image](https://user-images.githubusercontent.com/25843519/145188562-d91c1e2e-f95e-42aa-bbe5-43306c7f3011.png)

### Environment

Superset 1.3.2
Clickhouse Database

**Comment by zhaoyongjie** [comment]
@suedschwede Could you provide more context for this issue?

**Comment by rusackas** [comment]
Not sure if you're comfortable sharing data or other means to help reproduce this issue, but from what I can see it might not _be_ an issue. Both series go constantly up and to the right. If a line went downward, I'd say it's a bug, but it's hard to say based on the screenshot.

**Comment by geido** [comment]
Hello @suedschwede as we didn't get a reply from you recently I am tentatively closing this issue. Feel free to ping me if you need more assistance. Thank you!

**Comment by suedschwede** [comment]
The problem is solved in 1.4
