### ISSUE TITLE
Third party plugin not working anymore due to monorepo migration

### ISSUE THREAD

**Issue by kaihenzler** [apache/superset#17686]
I'm maintaining a third party viz plugin over at: https://github.com/w11k/superset-chart-plugins

With the recent merge of the superset-ui repo and the main repo (https://github.com/apache/superset/issues/13013) a issue with local development for third party plugins was introduced.

#### How to reproduce the bug

When using `npm link` with any third party viz plugin and starting the superset dev server like usual I now get the following React error message (see below): which leads to the following page: https://fb.me/react-invalid-hook-call

### Expected results

The third party plugin works like usual when using `npm link`

### Actual results

React error message:
![Bildschirmfoto 2021-12-08 um 13 06 32](https://user-images.githubusercontent.com/4253453/145206411-cb3179ae-0456-4031-8bc7-665ede748962.png)

#### Screenshots
...

### Environment

(please complete the following information):

- browser type and version: Every Browser
- superset version: latest (master)`1.3.2`
- python version: -
- node.js version: `14.x`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Can be fixed by adding an alias to react in the [`webpack.config.js` Line 286](https://github.com/apache/superset/blob/c4b04952d0e446b2347d2e6928478e2207102567/superset-frontend/webpack.config.js#L286)

```javascript
    alias: {
      react: path.resolve('./node_modules/react'),
    },
```

**Comment by nytai** [comment]
yup, guessing somehow you ended up with another version of react running.

**Comment by villebro** [comment]
@kaihenzler yes, the recent monorepo work caused this, and adding that alias does indeed fix it. FYI, you may very well run into other problems, too, but the good news is I've rebuilt the hello world plugin this week and totally decoupled it from the old `superset-ui` monorepo. The new template
- has build scripts and everything necessary to both develop, build and publish to npm
- can be npm linked with minimal effort from the main repo

I should have the `generator-superset` package updated early next week.

**Comment by kaihenzler** [comment]
@villebro thanks a lot for the update. I'm looking forward to try the new template

**Comment by villebro** [comment]
@kaihenzler I took a look at your repo, very exciting to see custom viz plugins in the wild! If you want to get a head start on this stuff please ping me on Slack so I can share my WIP code. The new template should simplify your repo considerably by removing the `lerna` dependency, unless you want to keep it as a monorepo, that is. I consider the new template quite stable, but as it may still change in the coming days I want to wait a few more days before opening a PR for it.

**Comment by kaihenzler** [comment]
Thanks a lot. I'll probably take a look at it after the holidays

**Comment by amitmiran137** [comment]
Take a look at nielsen-oss/superset-viz-plugins 
We manage to overcome all of the new setup issues

**Comment by villebro** [comment]
@kaihenzler to add to @amitmiran137 's answer, the Yeoman generator template has been updated to work with the new monorepo, and the currently valid instructions can be found in the updated docs here: https://github.com/apache/superset/blob/master/docs/src/pages/docs/Contributing/creating-viz-plugins.mdx . The code that the new template creates is easier to work with, incl. no npm linking required.

**Comment by kaihenzler** [comment]
Thanks a ton! I will have a look at it soon
