### ISSUE TITLE
Control panel not showing controls on initial load for custom plugins

### ISSUE THREAD

**Issue by krsnik93** [apache/superset#17683]
![image](https://user-images.githubusercontent.com/13034472/145193336-e4ee7f19-1a13-43f4-8746-12d1e5f133b3.png)

Workaround seems to be to change either the datasource/dataset or the viz type. However, on initial load, the controls are missing. The reason it says "Empty Query?" is because it tries to query the backend because the validator constraints for all the controls are not in play as the controls are not rendered.

#### How to reproduce the bug

1. Point to a plugin in Settings -> Plugins
2. Initiate creating a new chart via Charts -> + Chart

### Expected results

Expect control panel to load normally.

### Actual results

Control panel missing controls. They reappear only after changing datasource or viz type (does not matter from which to which).

#### Screenshots

Above.

### Environment

(please complete the following information):

- browser type and version: Chromium 95
- superset version: 1.3.2
- python version: 3.7.3
- any feature flags active:
```
FEATURE_FLAGS ={
    "DYNAMIC_PLUGINS": True,
    "ROW_LEVEL_SECURITY": True,
    "VERSIONED_EXPORT": True,
    "THUMBNAILS": True,
    "THUMBNAILS_SQLA_LISTENERS": True,
    "LISTVIEWS_DEFAULT_CARD_VIEW": False,
    "ALERT_REPORTS": True,
}
```
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by viewers** [comment]
Hi Guys,

I've reproduced the issue on 2.0.1,
It seems that the plugin is called before it finished initialisation.

Looking into the code of **superset-frontend/./src/explore/components/ExploreViewContainer/index.jsx**, 
it looks as we try to triggerQuery on a component that did not complete loading,
The following fix works, but needs to be checked for side effects. 
 
***************
*** 387,393 ****
        control =>
          control.validationErrors && control.validationErrors.length > 0,
      );
!     if (!hasError) {
        props.actions.triggerQuery(true, props.chart.id);
      }
    }, []);
--- 390,396 ----
        control =>
          control.validationErrors && control.validationErrors.length > 0,
      );
!     if (!hasError && !isDynamicPluginLoading ) { // If we have a Dynamic plug in, make sure it finished loading
        props.actions.triggerQuery(true, props.chart.id);
      }
    }, []);

**Comment by geido** [comment]
Hello @krsnik93 thanks for reporting this. As this issue has been stale for a while I'll be closing it. Feel free to re-open it if you are still experiencing this problem in recent versions of Superset.
