### ISSUE TITLE
How to make an appeal to the internal api?

### ISSUE THREAD

**Issue by MamonovaMaria** [apache/superset#17688]
Hi
When trying to make a request there from an external api/v1 using requests.get, when making requests to api/v1 through a proxy, the internal api gives an error 401. I transfer there the same Cookies that come to api/v1

**Comment by amitmiran137** [comment]
You should be elaborating more on the steps you are trying to take with all the context that we need in order to assist 
Please open a new issue and follow the template, otherwise it would be cumbersome to answer
