### ISSUE TITLE
[Dashboard] Enable opening chart from dashboard in a new tab

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#17696]
**Is your feature request related to a problem? Please describe.**
Enable opening chart from dashboard in a new tab; some users are frustrated that if they want to look into the chart explore they have to leave the dashboard and would prefer opening the chart in a new tab

**Describe the solution you'd like**
It could be an additional option on the dropdown

**Comment by amitmiran137** [comment]
They can just right click on the explore chart option and then open in new tab

**Comment by geido** [comment]
Hello @zuzana-vej I also agree that they can just right-click. This seems to be a pretty standard functionality of the browser. I'll close this issue for now but I'll be happy to re-open it if more people show interest in this. Thank you for your suggestion!
