### ISSUE TITLE
[explore][south table] timestamp column in data panel did not show correctly

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#17699]
timestamp column in data panel did not show correctly

#### How to reproduce the bug

1. Open example chart 'Participants' in superset
2. Observed timestamp column in 'view result tab' under data table

### Expected results

Timestamp column show correct date format

### Actual results

timestamp column show in long number other than date format

#### Screenshots
<img width="1791" alt="Screen Shot 2021-12-08 at 10 29 07 PM" src="https://user-images.githubusercontent.com/81597121/145345557-e2452549-fd7d-412c-a81f-e56efdab5c3a.png">

### Environment

(please complete the following information):

- browser type and version:
- superset version: lastest master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
That table now lets you choose between integer and human-readable timestamps. I believe this is resolved, but correct me if I'm mistaken!
