### ISSUE TITLE
v1.3.superset clickhouse database，limit and offset are not working as expected.

### ISSUE THREAD

**Issue by prs1022** [apache/superset#17701]
as the title display, when  I develop based on V1.3 superset , I have a clickhouse database,
create a chart using the viz_type table , there is an experimental function : server paging

So I choose it for my query. But I found the bug:

for example , I choose page limit 10,when I choose the second page, it show me 20 results.

So I debug find that clickhouse engine compile limit m offset n  to limit 0 ,n to lead this result.

**Comment by prs1022** [comment]
I found this is sqlalchemy-clickhouse problem:

https://github.com/cloudflare/sqlalchemy-clickhouse/issues/56

**Comment by srinify** [comment]
hey there @prs1022 -- I'm having trouble following your original issue. Can you post a screen recording?

What's your recommended course of action and are you able to contribute a fix?

**Comment by prs1022** [comment]
> hey there @prs1022 -- I'm having trouble following your original issue. Can you post a screen recording?
> 
> What's your recommended course of action and are you able to contribute a fix?

Thank you for your reply，I do a test , Here is my test program, you can find the reason for this bug.
when I want limit 5 offset 10, mysql is good, but clickhouse get a bad result.
```
def test_sql():
    t = table('t', column('x'))
    sa = select([t])
    LIMIT = 5
    OFFSET = 10
    s = sa.where(t.c.x == 5).limit(LIMIT).offset(OFFSET)

    engine = create_engine("mysql://root:123456@127.0.0.1:3306/aaaa")
    print(s.compile(engine,compile_kwargs={"literal_binds": True}))
    print("==="*10)
    engine = create_engine("clickhouse://root:123456@127.0.0.1:8123/test")
    sql = str(s.compile(engine,compile_kwargs={"literal_binds": True}))
    print(sql)
```
here is the result
```
SELECT t.x 
FROM t 
WHERE t.x = 5 
 LIMIT 10, 5
==============================
SELECT x 
FROM t 
WHERE x = 5
 LIMIT 0,10

```
I have a temporary solution for the clickhouse database:
`sql.replace(f'LIMIT 0,{OFFSET}', f'LIMIT {OFFSET},{LIMIT}')`

 and I haven't found this bug with other data sources.  I record this in my [zhihu blog](https://zhuanlan.zhihu.com/p/443630138).

**Comment by save-my-heart** [comment]
Just change sqlalchemy-clickhouse to [clickhouse-sqlalchemy](https://github.com/xzkostyan/clickhouse-sqlalchemy) will solve your problem.
This pr is not necessary at all. #17721

**Comment by prs1022** [comment]
> Just change sqlalchemy-clickhouse to [clickhouse-sqlalchemy](https://github.com/xzkostyan/clickhouse-sqlalchemy) will solve your problem. This pr is not necessary at all. #17721

@save-my-heart thank you for reply, I remove sqlalchemy-clickhouse ,it seems good. I close pr now.
