### ISSUE TITLE
d3 format selection widgets should use case sensitive matching for determining uniqueness

### ISSUE THREAD

**Issue by john-bodley** [apache/superset#17716]
The d3 [time format](https://github.com/d3/d3-time-format) selection widgets which are used for customizing x- and x-axis formatting etc. seems to match using case insensitive whereas the formatting is case sensitive, which prevents users from inputing formats which match in a case insensitive manner.

#### How to reproduce the bug

1. Go to 'explore'
2. Create a new 'Time-series Line Chart' (or similar)
3. Click on the 'CUSTOMIZE' tab
4. Try entering the '%b %Y' d3 format for the X-Axis TIME FORMAT (or some other format which matches in a case insensitive way)
5. See that the UI component senses this is a match with '%B %Y' even though these are different

### Expected results

The  d3 format UI components should be case sensitive.

### Actual results

The UI component thinks '%b %Y' and '%B %Y' are the same and thus the new '%b %Y' entry cannot be entered.

#### Screenshots

<img width="310" alt="Screen Shot 2021-12-11 at 7 53 55 AM" src="https://user-images.githubusercontent.com/4567245/145627765-8aced441-f85a-481a-b3e7-33ca9a51bfbd.png">

### Environment

(please complete the following information):

- browser type and version:
- superset version: `master`
- python version: `3.9`
- node.js version: `v12.16.2`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by geido** [comment]
@michael-s-molina this might be of our interest

**Comment by michael-s-molina** [comment]
> @michael-s-molina this might be of our interest

Interesting. I think if we consider case-sensitivity a common requirement for Select search then we should add a configuration to the component API. If we think this is an outlier behavior, then we can handle it using the `filterOption` prop.

**Comment by rusackas** [comment]
I believe this was closed by https://github.com/apache/superset/pull/19159
