### ISSUE TITLE
CI is extremely flaky when running Presto/Hive tests

### ISSUE THREAD

**Issue by suddjian** [apache/superset#17750]
These tests are the same ones that run against other analytics DBs, but for some reason when we run them against Presto/Hive we get false positives (or are they false negatives? 🤔) at a much greater rate. These tests also seem to take much longer to run, which may be related.

If we can get to the bottom of this it will massively improve the experience of contributing to Superset.

#### How to reproduce the bug

Run CI a few times.

### Expected results

CI should pass if the PR hasn't introduced any bugs.

### Actual results

It fails a lot. Often multiple times in a row, with different tests.

### Additional context

I want to start putting together a list of the tests that have failed, to see if there is some sort of pattern. Feel free to add new entries to this list (only if you are certain that it really is a false positive!). Please also link to a relevant line of the GitHub Action where the test failed.

- [ERROR tests/integration_tests/dashboards/filter_state/api_tests.py::test_delete_not_owner](https://github.com/apache/superset/runs/4524150250?check_suite_focus=true#step:8:2363)
- [ERROR tests/integration_tests/security_tests.py::TestRolePermission::test_admin_permissions](https://github.com/apache/superset/runs/4525283552?check_suite_focus=true#step:8:2420)

**Comment by zhaoyongjie** [comment]
A little clue for this issue. I will try update images version or increase Java heap memory for fixing it.

https://github.com/apache/superset/runs/4530486125?check_suite_focus=true#step:9:5105

**Comment by rusackas** [comment]
Just one more case:

In [this](https://github.com/apache/superset/pull/17768) PR, I've had repeated failures of `test-postgres-presto (3.8)` on the test `test_get_dashboard_view__user_access_with_dashboard_permission`. The error I see is:

> ERROR at setup of TestDashboardRoleBasedSecurity.test_get_dashboard_view__user_access_with_dashboard_permission

I'm on my third run now... wish me luck 🤞

**Comment by rusackas** [comment]
Dropping a link to the [Slack thread](https://apache-superset.slack.com/archives/G013HAE6Y0K/p1639515691164400) where there's more discussion on this.

**Comment by zhaoyongjie** [comment]
I found that some large SQL insert tasks will cause Presto null-pointer error.  I submit the same SQL through presto-cli or JDBC without any problems.

![image](https://user-images.githubusercontent.com/2016594/146384237-b2d53563-a7b0-4169-8d28-4a4b144ccccb.png)

![image](https://user-images.githubusercontent.com/2016594/146384259-5f46a1f4-6e9b-4e55-a414-2ba89bc4a37b.png)
