### ISSUE TITLE
Superset translation native filters bug

### ISSUE THREAD

**Issue by aeperalta** [apache/superset#17779]
#### How to reproduce the bug

1. Active other language, for example, German in `superset_config.py`.
2. Change the language of superset.
3. Create a dashboard with some charts.
4. Create a native filter of type 'Time grain' and other of type 'Time range'.
5. Save the filter configuration.
6. Click on time grain select. You will see the grains in english.
7. The time range chip will be set to 'No filter', but if you click on it, you will see 'Kein Filter' (german) as selected in the Popup.

### Expected results

The expected result of the Time grain select would be in german, and the chip in german too. I reviewed `messages.po` and `messages.json` and the translations are there. This happens in other languages that have the translations too.

### Actual results

Time grain is in english, and the chip is in english too.

#### Screenshots

Granularity:
![granularity](https://user-images.githubusercontent.com/26123928/146398660-4c5dda29-8332-48dd-b487-7629e6345d8d.png)

Time range chip:
![Time range chip](https://user-images.githubusercontent.com/26123928/146399091-9429fcc3-9a10-4c25-b76d-0df8fdcca687.png)

### Environment

- browser type and version: Google Chrome Versión 96.0.4664.93
- superset version: master head

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
@AndVK opened up a [AWESOME PR](https://github.com/apache/superset/pull/21479) that fixes this issue. I'll tag it so that it automatically closes this, if it gets a rebase and a couple of open questions answered.

**Comment by hbruch** [comment]
Most causes of the issues described here have been solved via https://github.com/apache/superset/pull/22150, which made many strings available for localization. In case they still not appear translated, the language specific .po file would need to be updated. See [CONTRIBUTING](https://github.com/apache/superset/blob/master/CONTRIBUTING.md#updating-language-files) for a how-to. 

However, `No filter` for many charts still is not localized.
