### ISSUE TITLE
Duplicate dashboard with optionally duplicate charts

### ISSUE THREAD

**Issue by kevinwen2k** [apache/superset#17793]
**Is your feature request related to a problem? Please describe.**
We would like to have a feature that allow users to duplicate dashboard, and optionally duplicate (deep copy of ) charts associated with the dashboard.

**Describe the solution you'd like**
It would be great to have such feature as one of the items in the Action column in the dashboard list page (/dashboard/list/). 

**Describe alternatives you've considered**
Also, it would be great to have such icon next to the report scheduling icon and before the 3 dots in the upper right corner of the single dashboard page, or put such icon in both dashboard list page and the single dashboard page.

**Additional context**
![Screen Shot 2021-12-16 at 10 25 34 PM](https://user-images.githubusercontent.com/4207782/146499358-fb466309-b94d-49d7-8cd6-c93a75fe5f69.png)
![Screen Shot 2021-12-16 at 10 26 04 PM](https://user-images.githubusercontent.com/4207782/146499373-2c80ae9e-2668-45dd-9d82-cef78cc47799.png)

**Comment by kevinwen2k** [comment]
The red circle in attachments show the positions of the icon for this feature.

**Comment by villebro** [comment]
FYI, this can already be done in the dashboard view by clicking on `...` in the top right hand corner, clicking "Save as", after which you're presented with this modal:
![image](https://user-images.githubusercontent.com/33317356/146520726-c602601a-e3b2-4b8f-9b1b-b5c0d4b82382.png)

Having this feature in the list view might be useful in some cases, but this might be viewed as cluttering the view for users that don't need this feature.

**Comment by nytai** [comment]
@kevinwen2k can you confirm this meets your use case and if so, close this issue.

**Comment by kevinwen2k** [comment]
Yes, I just tested and it works! Closing it.
