### ISSUE TITLE
Version mismatch between googlechrome and chromedriver in k8s supersetWorker documentation

### ISSUE THREAD

**Issue by gideonn** [apache/superset#17809]
The documentation makes the worker always fetch the latest chrome but a hardcoded version is used for the chromedriver. Many a times this mismatches and alerts/reports screenshot stop working since the versions are not compatible.

Superset worker should always fetch the latest version for chromedriver, like it does for the browser

#### How to reproduce the bug

1. Do a new installation of superset on k8s with alerts and reports configured
2. Setup a dashboard/chart
3. Setup alerts with screenshot against that dashboard/chart
4. Will get blank email, on checking the logs, it'll say the screenshot didn't work because of the browser and chrome driver being incompatible.

### Expected results
Screenshot of the chart/dashboard in the email

### Actual results
No screenshot in the email

#### Screenshots
N/A

### Environment

Below fields are not applicable. This is relevant for all kubernetes deployments that have alerts and reports configured.
(please complete the following information):

- browser type and version: 
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
I do believe this has been fixed! Closing, but happy to re-open if the current state of affairs is incorrect.

**Comment by gideonn** [comment]
Hey @rusackas , this has not been fixed in the latest documentation. I can re-base and update the PR.

**Comment by rusackas** [comment]
Ok, thank you @gideonn! Please feel free to ping me on Slack if that PR needs more attention to get it merged. And also feel free to put "Fixes: #17809" on your PR description to auto-kill this issue when it merges :D

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
