### ISSUE TITLE
New docker installation comes with Error: Internal server error 500

### ISSUE THREAD

**Issue by hannody** [apache/superset#17822]
Following the installation instructions available here: https://superset.apache.org/docs/installation/installing-superset-using-docker-compose, after the image is up and running, I have opened http://localhost:8088 to do a first time login as admin, howerver, I am getting an error the web-page with the following message:" Internal server error
Sorry, something went wrong. We are fixing the mistake now. Try again later or go back to home." and there is 500 number.
### Expected results
Admin Login Page
what you expected to happen.

### Actual results
Internal server Error 500.
what actually happens.

### Environment
Linux Ubuntu 20.04 LTS
(please complete the following information):

- browser type and version: Chrome latest, Firefox latest.
- superset version: `superset version` latest from docker compose available at: https://github.com/apache/superset.git
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by xusongtao** [comment]
yep, I met the same error。（docker installation ）

**Comment by jakubczaplicki** [comment]
Check the comments in https://github.com/apache/superset/pull/17687 to see if it's related to your what you're seeing. (especially the docker pull comment)

**Comment by hannody** [comment]
Hi @jakubczaplicki, the error comes up after the installation is done and opening  http://localhost:8088 for the first time.
I have reviewed  #17687 but I did not find a solution for the error I am facing.

**Comment by Ribo01** [comment]
This is the same issue I am encountering anyone has a fix ?

**Comment by MCBoarder289** [comment]
I'm seeing this issue as well... Noticed errors in db:

```
db_1                    | 2022-03-25 21:20:31.629 UTC [37] ERROR:  relation "ab_permission_view_role" does not exist at character 292
db_1                    | 2022-03-25 21:20:31.629 UTC [37] STATEMENT:  SELECT ab_role.id AS ab_role_id, ab_role.name AS ab_role_name, ab_permission_view_1.id AS ab_permission_view_1_id, ab_permission_view_1.permission_id AS ab_permission_view_1_permission_id, ab_permission_view_1.view_menu_id AS ab_permission_view_1_view_menu_id 
db_1                    | 	FROM ab_role LEFT OUTER JOIN (ab_permission_view_role AS ab_permission_view_role_1 JOIN ab_permission_view AS ab_permission_view_1 ON ab_permission_view_1.id = ab_permission_view_role_1.permission_view_id) ON ab_role.id = ab_permission_view_role_1.role_id
```

and superset_init:
```superset_init           | 
Cleaning up slice uuid from dashboard position json.. Done.      osition json..
superset_init           | 
superset_init           | Traceback (most recent call last):
superset_init           |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
superset_init           |     self.dialect.do_execute(
superset_init           |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
superset_init           |     cursor.execute(statement, parameters)
superset_init           | psycopg2.errors.UndefinedTable: relation "ab_permission_view_role" does not exist
superset_init           | LINE 2: FROM ab_role LEFT OUTER JOIN (ab_permission_view_role AS ab_...
superset_init           |                                       ^
```

**Comment by zhaolandelong** [comment]
Same error

**Comment by IvanRibakov** [comment]
I found solution at the [DockerHub page](https://hub.docker.com/r/apache/superset):

```
// Setup your local admin account
$ docker exec -it superset superset fab create-admin \
              --username admin \
              --firstname Superset \
              --lastname Admin \
              --email admin@superset.com \
              --password admin

// Migrate local DB to latest
$ docker exec -it superset superset db upgrade

// Setup roles
$ docker exec -it superset superset init
```

**Comment by Trolann** [comment]
Had the exact same issue, @IvanRibakov's instructions were correct. Checking the installation page and looks like I just didn't do all the steps. 

Maybe a quick update to breakout those steps a little cleaner? I think this one can be closed tho.

**Comment by mahajnay** [comment]
I faced the similar issue due to incomplete configuration.

https://hub.docker.com/r/apache/superset

this link on docker superset setup helped me

**Comment by boulund** [comment]
The root of my issue was that I had a previous docker-compose based deployment on the same machine that I don't want to stop, leading to the persistent docker volumes conflicting. I solved my issue by making a custom Docker image with a custom configuration (https://github.com/ctmrbio/ctmr-superset)

**Comment by averri** [comment]
I have the same issue and tested with versions 1.4.0 and 2.0.0.

**Comment by sfirke** [comment]
A lot of change has happened since this issue last had activity, and the above content pertains to old versions of Superset.  I'm going to close this.  If anyone experiences similar issues deploying with `docker compose` on the latest official release (3.0.0 as of this writing but please check), please open a new issue.

**Comment by WeskerC** [comment]
> I faced the similar issue due to incomplete configuration.
> 
> https://hub.docker.com/r/apache/superset
> 
> this link on docker superset setup helped me

This is the solution that works for me!
