### ISSUE TITLE
Doubt: How can I check the version of Superset and update it if needed?

### ISSUE THREAD

**Issue by devbrunorm** [apache/superset#17831]
Sorry for posting this doubt as an issue, but I am struggling to find an answer to this question. I am using this repo and Docker to test Superset as recommended at the tool's Documentation. Although, I am having problems with the versions of the software. As I run the "docker-compose-non-dev.yml" file, the service appears to be running the 0.0.0dev version, is that truly the case? If so, how can a update into version 1.2.0?

**Comment by CodeingBoy** [comment]
This should be a problem, since `docker-compose-non-dev.yml` is using an image tagging `latest-dev`. You can change `x-superset-image: &superset-image apache/superset:latest-dev` to `x-superset-image: &superset-image apache/superset:latest` to resolve this.

**Comment by jakubczaplicki** [comment]
We have deployed Superset on K8S and we also see the 0.0.0dev version
![image](https://user-images.githubusercontent.com/147901/147097708-0860926f-54fd-45cb-9731-643d41bdc5b5.png)

**Comment by devbrunorm** [comment]
I tried changing the docker image from `latest-dev` to `lastest`, but I had no effect. My intention with version 1.2.0+ is to use the cross filter feature which, from what I have seen, is a feature of this version.

**Comment by rusackas** [comment]
Relates to https://github.com/apache/superset/issues/13674

**Comment by geido** [comment]
Closing this in favor of #13674
