### ISSUE TITLE
save dashboard after edit properties is failing

### ISSUE THREAD

**Issue by amitmiran137** [apache/superset#17830]
save a dashboard after editing from the properties window. result in a failure
no way to save a dashboard

#### How to reproduce the bug

1. create an empty dashboard
2. go to dashboard properties and edit the then click save
3. click save on the dashboard level

### Expected results

dashboard. should be saved

### Actual results

get an error message

save error response:  
PUT https://superset-maf.dev.apps.nielsen.com/api/v1/dashboard/231 400
{"message":{"certification_details":["Unknown field."],"certified_by":["Unknown field."]}}

https://user-images.githubusercontent.com/47772523/146814956-c2af9fcc-b8bf-4c8b-b089-91bd11f7992f.mov

### Environment

(please complete the following information):

- browser type and version:  chrome 96
- superset version: `1.4rc2`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

    "ENABLE_TEMPLATE_PROCESSING": True,
    "ROW_LEVEL_SECURITY": False,
    "DASHBOARD_NATIVE_FILTERS": False,
    "DASHBOARD_NATIVE_FILTERS_SET": False,
    "DASHBOARD_CROSS_FILTERS": False,
    "VERSIONED_EXPORT": True,
    "DASHBOARD_RBAC": True

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by eschutho** [comment]
@rusackas do you know if there's a fix for this already that we can cherry in?

**Comment by amitmiran137** [comment]
We cherrypicked the relevant PR

**Comment by hadiismanto** [comment]
for me color scheme cannot be emptied
