### ISSUE TITLE
CSS Templates between dashboards are getting overridden (CSS Scoping issue between dashboards)

### ISSUE THREAD

**Issue by kiranharry89** [apache/superset#17868]
In the superset 1.3.0 version, When we apply different custom CSS for 2 different dashboard having same chart components, while navigating between the dashboards the styles of 1st Dashboard are getting overridden by the 2nd dashboard CSS styles
Same is working in earlier version of superset

Due to the above issue - User experience has gone for a toss, Very critical bug when it comes to user experience 

#### How to reproduce the bug

1. Create a dashboard and add Big Number Chart
2. Go to Dashboard Add a custom CSS using Edit Dashboard (Border/Background colour)
3. Save the dashboard 
4. Repeat step 1, 2 & 3 for a 2nd dashboard and Apply different CSS styles for the Big Number chart
5. Navigate to 1st Dashboard Big Number chart displays the styles as is
6. Now Navigate to 2nd Dashboard (I see the Dashboard 1st Big Number chart styles and have been applied to 2nd Dashboard Big Number Chart)
7. I see that the CSS scoping has not been working properly in dashboard specific

### Expected results
Chart Component Customer css should be scoped per dashboard and not at the chart component level

### Environment

(please complete the following information):

- browser type and version: Chrome Version 96.0.4664.110 (Official Build) (x86_64)
- superset version: `superset version` 1.3.0
- python version: `python --version` 
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by eschutho** [comment]
I wasn't able to repro this on 1.4. Once that version is released, @kiranharry89 can you test and see if it's resolved for you as well?

**Comment by rusackas** [comment]
Sounds like this is resolved, and the versions in the thread are no longer officially supported anyway. If anyone sees this sort of behavior in 2.0.x (or _maybe_ 1.5.x) versions, we can re-open this issue.
