### ISSUE TITLE
Unable to add table from kylin database

### ISSUE THREAD

**Issue by HezhichaoGH** [apache/superset#17870]
After superset adds the kylin database, the table in the database cannot be added

### Expected results

I can add table from kylin database

### Actual results

When I added the dataset, an error message was report 'An error occurred while creating datasets: Dataset could not be created.'

#### Screenshots

![image](https://user-images.githubusercontent.com/62866158/147347044-833e5173-e522-4f51-8e75-769302bb2272.png)
![image](https://user-images.githubusercontent.com/62866158/147347097-e0b83ad0-dabb-4928-bbb7-6fb4f71ae060.png)
![image](https://user-images.githubusercontent.com/62866158/147347607-63e75124-43ac-48c0-8c14-865c076e7fbf.png)

### Environment
- browser type and version: chrome(96.0.4664.110)
- superset version: 1.4.0rc3
- python version: 3.8.12
- node.js version: /
- kylin version: 4.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by arabasco** [comment]
Hi, I'm having this exact same problem right now. Is there any solution?

**Comment by tholsar** [comment]
Hi, I am also facing exactly the same issue. If anybody have any solution please help...

**Comment by haimingOu** [comment]
Hi, I'm having this exact same problem right now. Is there any solution?

**Comment by slnxyr** [comment]
Hi, I'm having this exact same problem right now. Is there any solution?

**Comment by F2017065293** [comment]
@hezhichaoKLCat  i got the same issue please can you describe the solution !!
