### ISSUE TITLE
Default value filter box

### ISSUE THREAD

**Issue by Riskatri** [apache/superset#17871]
I have a case to make a default filter based on current year,
For example, if this year is 2021 -> default filter is 2021
If next year is 2022 -> default filter is 2022

So, i want to make the filter is dynamic with default value based on current year.
Can superset handle this issue ?
Can the default value field in the filter box be changed to a query form?  to add a now() condition if want to create a filter based on the current year. 

Thankyou

**Comment by amitmiran137** [comment]
Filter box Is depracated and will not be added new features

On native select filter you have the default first item option that you can leverage that by returning a column with years like 2021,2020 and when new years comes first on the list
