### ISSUE TITLE
Helm chart configure and create custom service account

### ISSUE THREAD

**Issue by wiktor2200** [apache/superset#17879]
**Is your feature request related to a problem? Please describe.**
There was lack of service account management while using helm charts.

**Describe the solution you'd like**
Being able to create service account for superset and configure its name.

**Additional context**
There was `ServiceAccountName` variable added in the past, so I've implemented new feature as enhancement beside the current solution.

PR: https://github.com/apache/superset/pull/17880

**Comment by amitmiran137** [comment]
Thank you for helping our efforts on improving superset helm chart

**Comment by wiktor2200** [comment]
As #17880 and #17920 is merged this issue can be closed.
