### ISSUE TITLE
How to enable .XLS export in superset dashboard

### ISSUE THREAD

**Issue by Narendra678** [apache/superset#17889]
Hi Team,

I want to see export xls option.
and i want exact code to apply backend(config.py).

![image](https://user-images.githubusercontent.com/88739186/147669422-509e7ad8-023c-4394-9ba8-c7db4dbeb969.png)

Please do the needful.

Regards,
Narendra

**Comment by amitmiran137** [comment]
Option do not exist

**Comment by Narendra678** [comment]
![image](https://user-images.githubusercontent.com/88739186/147910413-6e64c9f2-0b48-412b-836e-3c5913982948.png)


How about this?

Regards,
Naren
