### ISSUE TITLE
deck-gl polygons not displayed under iOS Safari 15.1

### ISSUE THREAD

**Issue by hbruch** [apache/superset#17892]
Opening a deckgl-polygon map does not show any polygons under iOS Safari 15.1.

In the console an error message `WebGL: INVALID_OPERATION: useProgram: program not valid` is logged. 

#### How to reproduce the bug

1. Under iOS, open Safari browser
2. Go to a deckgl ploygon map, e.g. http://dashboard.wattbewerb.de/r/15 (tab "Bestand")
3. See a map without polygons, legend shows black squares for all categories

### Expected results

Polygons should be rendered, tthe legend should show sequential color palette.

### Actual results
The map is rendered without polygons, legend shows black squares for all categories

#### Screenshots

![grafik](https://user-images.githubusercontent.com/2187389/147694072-6041cb9e-f5f7-468a-96ff-371d74b78ef5.png)

### Environment

- browser type and version: iOS Safari 15.1.1
- superset version: master

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Probably caused by an underlying deck-gl issue, as some more issues/error reports point into this direction, e.g. https://github.com/visgl/deck.gl/issues/6414 or https://developer.apple.com/forums/thread/688561

**Comment by spkompella** [comment]
Having a similar problem using a pydeck map in Safari 15.1 or Chrome for iOS15.1. Problem is not seen in 15.0 and I have not tried future versions of Safari.

**Comment by rusackas** [comment]
This appears to be working in Safari 16, so I'll go ahead and close this since it's stale and folks have _probably_ upgraded their browser by now.
