### ISSUE TITLE
Email Dashboard Not sending email

### ISSUE THREAD

**Issue by nitinbansude** [apache/superset#17905]
getting message **Ignoring deactivated schedule** even after activating scheduler for email dashbaord.

### Check celery log after set scheduler 

Should be sent test email 

### Environment

(please complete the following information):

- browser type and version:
- superset version: `0.38.1`
- python version: `3.6`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by amitmiran137** [comment]
To better update to 1.4 once release to get all latest changes and fixed
Not sure that schedijg is stable in 0.38

**Comment by nitinbansude** [comment]
@amitmiran137 how to update 0.38 to 1.4 is there any dashboard loss while upgrading?

**Comment by amitmiran137** [comment]
You should clone your existing environment and then:

Follow and adjust the Updating.MD from 0.38 till 1.3 to adjust to all of the breaking changes 

Get the 1.3 version(either docker or pip or whatever method you downloaded before)

Run `superset init
Run `Superset db upgrade`

Then re run the webserver (gunicorn?) to run the new version 


The above are just high level guidelines , most of it is dependent on your deployment

On my setup I already have k8s setupped and I just deploy a newer image and everything works like magic 

Good luck
