### ISSUE TITLE
Enable Native filter/Enable emitting filter

### ISSUE THREAD

**Issue by Narendra678** [apache/superset#17910]
Hi Team,

I am not able to see 'Enable emitting filter' option.

Can someone please help me to enable this feature in my Superset. 
I am using 1.3.1 version

Expecting below:
![image](https://user-images.githubusercontent.com/88739186/147955645-5f49d433-3866-456a-aa1f-c464e58ac00e.png)

Regards,
Naren

**Comment by kamalkeshavani-aiinside** [comment]
You may need to enable `DASHBOARD_CROSS_FILTERS` feature flag in you config file.
Also, can you please move this query to [here](https://github.com/apache/superset/discussions/categories/q-a) and close this issue?

**Comment by Narendra678** [comment]
Hi Kamalakeshavani,

Thanks for your reply.

But i am looking for Native/Emitting filters. See below screen. To enable this which code i have add?
![image](https://user-images.githubusercontent.com/88739186/148047615-ca3adbd8-34aa-405c-bad1-87651c4ee48b.png)


Regards,
Naren

**Comment by Narendra678** [comment]
Thanks for your response
