### ISSUE TITLE
Cannot use a dashboard while accessing on public network

### ISSUE THREAD

**Issue by jaspreetjhans** [apache/superset#17922]
I had this issue when i tried use my dashboard while accessing on public network with SSL. but able access with private ip Look at the screenshot below:

![image](https://user-images.githubusercontent.com/82465223/148097260-4bbd9de7-3eb2-4bb7-8352-b521b73f0867.png)

### Environment

(please complete the following information):

- browser type and version:       Chrome & Edge
- superset version: `superset version`   1.32
- python version: `python --version`     Python 3.9.5
- node.js version: `node -v`
- any feature flags active:

**Comment by srinify** [comment]
Hi there @jaspreetjhans if you can access in one network setup but not another, then this is definitely a Networking setup issue. I'm closing this issue for now, as this isn't a Superset bug :)

But if you do identify a specific bug, please open a new issue with as much context as possible!
