### ISSUE TITLE
Dashboard url slug won’t be really saved when edit in dashboard edit mode.

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#17938]
Dashboard url slug won’t be really saved when edit in dashboard edit mode.

#### How to reproduce the bug
Repro steps
1, go to dashboard edit mode
2, in dashboard edit mode, edit url slug
3, save the changes and save dashboard
4, refresh page
5, see error

### Expected results
edit dashboard url can be saved in dashboard edit mode

### Actual results
edit dashboard url can be not be saved in dashboard edit mode

#### Screenshots

https://user-images.githubusercontent.com/81597121/148278382-40f8169c-3b0c-42a1-838d-4eb72ba43031.mov

### Environment

(please complete the following information):

- browser type and version:
- superset version:  master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by geido** [comment]
Hello @jinghua-qa as discussed I am moving this to @pkdotson as this problem seems related to the changes in PR #17680. Thank you both!

**Comment by rusackas** [comment]
Closed by https://github.com/apache/superset/pull/17961
