### ISSUE TITLE
No new versions have been pushed to PyPI since version 1.3.2

### ISSUE THREAD

**Issue by bhavishya123** [apache/superset#17948]
No new versions have been pushed to PyPI since version 1.3.2 . i want pip to install superset
i want to use databricks sqlendpoint

**Comment by etr2460** [comment]
We haven't released any new versions since then. version 1.4 is currently in voting, and will hopefully be released soon

**Comment by deepak-rai** [comment]
We too are looking for DataBricks connector, releasing this would help us a lot.
