### ISSUE TITLE
exported csv file from Mixed Time-Series chart only contains one series

### ISSUE THREAD

**Issue by heroygt** [apache/superset#17960]
2 series in chart, only the first serie can be exported

**Comment by geido** [comment]
Hello @heroygt thanks for reporting this issue.

Following the template before submitting the issue would be very helpful as it is hard to reproduce a problem with so little information provided.

Would you mind providing screenshots or videos as well as a more detailed explanation of the bug, environment, etc.?

Thank you!

**Comment by bnitesh** [comment]
Hello, 
We are facing this bug as well. We are using Superset version 1.3.0. Here are general steps to reproduce -

1. Create a mixed time-series chart
2. Configure metrics for query A and B
3. Run query to make sure chart is configured correctly and can display results
4. Open data below chart to confirm both metrics along with timestamp are present in table
5. Export to CSV. **Only column for Query A is present in downloaded file.**


Image 1: Superset Mixed time-series chart configuration showing 2 query metrics and table with both columns as well
![image](https://user-images.githubusercontent.com/1517491/149987042-164a50d9-146f-487a-bc85-f055d568eb1a.png)

Image 2: Downloaded csv showing column for only Query A
![image](https://user-images.githubusercontent.com/1517491/149987308-8c2bb8ba-d7e0-4d5b-ae07-3b9e67a78b96.png)

**Comment by syazwan0913** [comment]
I also have the same issue as above .
