### ISSUE TITLE
[native filters] native filter values is not sorted when select "Sort filter value" in Advance

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#17989]
native filter values is not sorted when select "Sort filter value" in Advance

#### How to reproduce the bug
Repro steps
1, create value filter for "Video Game Sales" dashboard, select 'Genre' column to filter
2, select Sort filter value in advance
3, observe filter value order on the left panel in dashboard

### Expected results
Values in table should be filtered

### Actual results
Values isn't filtered as expected

#### Screenshots

https://user-images.githubusercontent.com/81597121/148853371-791141c8-51a6-4db0-a219-bdfa6e4ad646.mov

### Environment

(please complete the following information):

- browser type and version:
- superset version: master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
@stephenLYZ if you could take a look at this, it would be much appreciated!

**Comment by rusackas** [comment]
Closed by https://github.com/apache/superset/pull/18145
