### ISSUE TITLE
Superset with Postgresql gets timezone error

### ISSUE THREAD

**Issue by leftluoyi** [apache/superset#17997]
**Versions**
Apache Superset: 0.5.3, actually is docker image with tag *latest*
Postgresql 11.6

**Expected results**
run `select now()` get the current time

**Actual results**
Have two instances of Apache Superset, one is installed locally using docker image just as [dockerhub](https://hub.docker.com/r/apache/superset). The other one is installed on Kubernetes cluster using helm just as [this tutorial](https://superset.apache.org/docs/installation/running-on-kubernetes). The actual results is:
1. On the local docker instance, the `select now()` command ran successfully
![image](https://user-images.githubusercontent.com/7591374/148901784-8bd2d15c-9b59-4a9f-bd7e-88230e548662.png)

2. But the Kubernetes instance got the following error
![image](https://user-images.githubusercontent.com/7591374/148901882-8a3eaa7c-1d18-4b50-9347-1c353a3d2829.png)

This is the Trackback of the error in the pod
```
Traceback (most recent call last):
  File "/app/superset/views/base.py", line 205, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/utils/log.py", line 242, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/views/core.py", line 2484, in sql_json
    command_result: CommandResult = command.run()
  File "/app/superset/sqllab/command.py", line 104, in run
    raise ex
  File "/app/superset/sqllab/command.py", line 96, in run
    status = self._run_sql_json_exec_from_scratch()
  File "/app/superset/sqllab/command.py", line 138, in _run_sql_json_exec_from_scratch
    raise ex
  File "/app/superset/sqllab/command.py", line 133, in _run_sql_json_exec_from_scratch
    return self._sql_json_executor.execute(
  File "/app/superset/sqllab/sql_json_executer.py", line 111, in execute
    raise SupersetErrorsException(
superset.exceptions.SupersetErrorsException: [SupersetError(message="'+00'", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'PostgreSQL', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
10.244.1.123 - - [11/Jan/2022:07:52:34 +0000] "POST /superset/sql_json/ HTTP/1.1" 500 236 "https://superset.deepsensing.team:88/superset/sqllab/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.57"
```

Actually, querying any column with `TIMESTAMP WITH TIME ZONE` type leads to the same error.

**Steps to reproduce**
Run `select now();` in the SQL Lab -> SQL Editor.

**Comment by villebro** [comment]
Thanks for reporting - please check the proposed fix here: #17999
