### ISSUE TITLE
can not add compont/chart in dashboard after chrome update

### ISSUE THREAD

**Issue by DachengChen** [apache/superset#18002]
Drag/Drop into dashboard with Tab/Row/Chart/etc. not work anymore, after chrome update.

Chrome version : Version 97.0.4692.71 (Offizieller Build) (64-Bit) in ubuntu 

works with firefox.

**Comment by geido** [comment]
Hello @DachengChen I could not reproduce this issue. What version of Superset are you currently running?

**Comment by DachengChen** [comment]
i deploy with docker image: apache/superset , pulled some day ago, in mene setting show version: 0.0.0dev

**Comment by geido** [comment]
@DachengChen it would be super helpful if you could show a video of the problem and some logs from your console. I can help you with that, just ping me on the [Superset Slack](https://join.slack.com/t/apache-superset/shared_invite/zt-uxbh5g36-AISUtHbzOXcu0BIj7kgUaw) just in case.

**Comment by afrish** [comment]
I experience the same issue, also with drag-n-dropping columns in the Explore. Same Chrome version, Ubuntu 20.04. Nothing in the browser console, no visible errors, no visual response, it just silently does not accept the operation

**Comment by geido** [comment]
Hello @afrish which Superset version are you currently running?

**Comment by afrish** [comment]
> Hello @afrish which Superset version are you currently running?

Superset v1.3.1
