### ISSUE TITLE
Can i remove day, week and hour from native filters list?

### ISSUE THREAD

**Issue by Narendra678** [apache/superset#18000]
Hi Team,

Can we remove day, week and hour from native filters list? Means i want to see only Year and month in the list.

![image](https://user-images.githubusercontent.com/88739186/148947792-9a00c943-ba20-4a99-98e5-d173295a609a.png)

Regards,
Naren

**Comment by geido** [comment]
Hello @Narendra678 I think this question might get more attention in the [Superset Slack ](https://join.slack.com/t/apache-superset/shared_invite/zt-uxbh5g36-AISUtHbzOXcu0BIj7kgUaw). I invite you to use the issues for bug reporting mainly. As you marked this as a bug I am going to close it now. I'd be happy to help over Slack. Thank you!
