### ISSUE TITLE
Histogram charts don't display percentile correctly in the tooltip

### ISSUE THREAD

**Issue by etr2460** [apache/superset#18008]
See title and screenshot

#### Screenshots
![Screen Shot 2022-01-11 at 5 25 08 PM](https://user-images.githubusercontent.com/7409244/149047442-b64eaaf8-c69f-4428-8550-fe0d16004ec0.png)

### Environment

(please complete the following information):

- browser type and version:
- superset version: `master`

**Comment by kamalkeshavani-aiinside** [comment]
Issue already raised, https://github.com/apache/superset/issues/17550

**Comment by etr2460** [comment]
Ah, good catch, thanks @kamalkeshavani-aiinside . I'll close this one as a duplicate
