### ISSUE TITLE
Queries are changed before being sent to spark/Spark hints are stripped from query

### ISSUE THREAD

**Issue by simonvanderveldt** [apache/superset#18023]
We're using superset on top of the Spark Thriftserver. We noticed that the queries we enter are being changed before they are sent to Spark. For example [Spark hints](https://spark.apache.org/docs/3.2.0/sql-ref-syntax-qry-select-hints.html) that we included in the query in Superset don't make it to the Spark Thriftserver. Running the same query against the Spark thriftserver using beeline works as expected and the hints make it to/are shown in the Spark Thriftserver and are applied to the execution plan.

#### How to reproduce the bug
- Run superset on top of Spark Thriftserver, config like so `hive://hive@{hostname}:{port}/{database}` as described in the docs https://superset.apache.org/docs/databases/spark-sql
- Run a query like
```
SELECT /*+ BROADCAST(Table 2) */ COLUMN
FROM Table 1 join Table 2
on Table1.key= Table2.key
```
- Check the query in the SQL tab of the Spark Thriftserver and notice the `/*+ BROADCAST(Table 2) */` part is missing
- Check the execution plan and notice the broadcast isn't there
- Rinse and repeat but use beeline instead of superset and see it working

### Expected results
Queries aren't changed before being sent to the underlying query engine.

### Actual results
Query is changed before being sent to the underlying query engine and an important part of the query is lost.
I did a brief search trying to find why/where this is happening in the code but couldn't find it.

### Environment
- Superset 1.3.2
- Spark 3.2.0

**Comment by simonvanderveldt** [comment]
:gun: stale

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
