### ISSUE TITLE
Unable to up the docker file after adding a new python file for custom authentication

### ISSUE THREAD

**Issue by nikhilmahawar** [apache/superset#18026]
I have a requirement in which i need to add custom authentication. For it I followed below steps:

#### How to reproduce the bug

1. Go to superset/superset folder. Create a new file e.x. CustomSecurityManager.py.
2. Add below code
 

> from superset.security import SupersetSecurityManager
> 
> class MySecurityManager(SupersetSecurityManager):
>     def __init__(self, appbuilder):
>         super(MySecurityManager, self).__init__(appbuilder)

3. Edited superset_config.py file that is present in docker/pythonpathtodev. Edited below entry

> from CustomSecurityManager import MySecurityManager
> CUSTOM_SECURITY_MANAGER = MySecurityManager

4. In the docker file I have also entry for the above file to copy.
5. In the superset/__init__.py file I have entry 

> from CustomSecurityManager import MySecurityManager

6. Then I am using docker-compose -f docker-compose-non-dev.yml up command. See the below error

### Expected results

Docker should be up

### Actual results

 
![image](https://user-images.githubusercontent.com/97673730/149333425-97e1291c-9fef-4d57-b340-6c0adc4824c9.png)
![image](https://user-images.githubusercontent.com/97673730/149333322-2f299bae-a072-446e-b277-c223bcfe6173.png)

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: `superset version`
- python version: `python --version`  -- 3.9.7
- node.js version: `node -v` --v12.22.5
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by srinify** [comment]
Hi @nikhilmahawar the non-dev yml is exactly that, focused on just getting the common default functionality working quickly (e.g. using prebuilt frontend assets, etc).

You'll likely be better off just doing `docker-compose up` instead

**Comment by srinify** [comment]
Can you post in #debug-together in the Superset Slack community? This isn't a bug or feature request, which is what Github issues are best used for!

You can join the Slack here: https://join.slack.com/t/apache-superset/shared_invite/zt-uxbh5g36-AISUtHbzOXcu0BIj7kgUaw
