### ISSUE TITLE
Dataset fuzzy search in "Create a new chart" UI isn't searching all available datasets when there are more than 100 datasets

### ISSUE THREAD

**Issue by cesar-loadsmart** [apache/superset#18034]
Hey Everyone!

Clicking the +CHART on the Charts tab, when selecting the dataset, not all of them are available. From the Charts tab I looked for the **Dataset Bar Limit** and I couldn’t find it, but when I searched it in the Datasets tab it was available (evidence attached).

#### How to reproduce the bug

1. Go to Chart Tab
2. Click on +CHART button
3. Search for a Dataset
4. You won't see them all
PS: I have almost 600 datasets on my Superset env.

### Expected results

Show all available datasets to be selected before creating the chart.

### Actual results

Display only a few datasets.

#### Screenshots
Searching for the dataset on the Charts tab:
![image](https://user-images.githubusercontent.com/89807801/149353347-f87f6dee-ed0b-49e7-a8bc-307303590b01.png)

When Searching for the dataset on the Datasets tab:
![image](https://user-images.githubusercontent.com/89807801/149354542-960cd585-ad25-4e9f-81c3-fe4a4ae68512.png)

### Environment

- browser type and version: Google Chrome - Version 97.0.4692.71 (Official Build) (x86_64)
- superset version: `1.3.2`
- python version: `3.8`
- node.js version: `node 16`
- any feature flags active: ALERT_REPORTS, DASHBOARD_NATIVE_FILTERS, ENABLE_TEMPLATE_PROCESSING
- I have 596 datasets on my env.
- My Superset is running via Kubernets

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
@mayurnewase has told me, that this issue is related to the fuzzy limiting the number of datasets, as follows:
![image](https://user-images.githubusercontent.com/89807801/149354697-fd983b55-234d-4d48-b026-904f7998075e.png)

Looks like this happens because fuzzy search for dataset on chart creation page, but on dataset page search is on db.

**Comment by codemaster08240328** [comment]
@cesar-loadsmart , it is not absolutely related to dataset fuzzy search in frontend.
If you type sth, and track the network tab, you must be able to see hitting endpoint with filter option.

To specify this issue more, can you add screenshot of tracking network tab when you search by `Dataset Bar Limit`?

**Comment by yousoph** [comment]
We've been unable to repro this now. 
@cesar-loadsmart if you are still seeing this issue and can provide more info, please reopen the ticket with more info. Thanks!
