### ISSUE TITLE
Dataset and Chart options vertical scroll not working

### ISSUE THREAD

**Issue by Hammad-Raza** [apache/superset#18047]
Vertical scroll stopped working on Chrome.

**Steps to Reproduce:**

- Go to Create Chart or open the existing chart.
- on Chart explorer page, dataset and chart options column vertical scroll is disabled

Superset Version 1.1
Browser: Chrome 97.0

**Actual Result:**
https://user-images.githubusercontent.com/15028724/149542278-dccc1ced-12e9-4556-8ef6-0d74d4e8b9ee.mov

**Expected Result:**
https://user-images.githubusercontent.com/15028724/149541419-c74088c2-22d3-429b-8e88-b5b5b8c7c801.mov

**Comment by rumbin** [comment]
Our users experienced the same. Even with recent versions of Edge (not quite surprising) and Firefox (more surprising to me).

After a quick test with Superset 1.4rc3 it seems that this issue does not exist there any more.

**Comment by bitappo** [comment]
This problem occurred after Chrome update. 
Is there a chance to solve it if we downgrade the chrome?

**Comment by syazwan0913** [comment]
Is it can follow the fix from here?

#16089

**Comment by rusackas** [comment]
I'm thus far unable to reproduce the issue on recent versions of `master` or in 1.4.0, using Chrome 97.0.4692.71 or FF 90.0.2 
or FF 96.0.1, all on Mac. 

@Hammad-Raza can you tell us which OS you are/were seeing this on? Also, 1.1 is fairly old now, do you have any opportunity to upgrade? 1.4.0 is being released today 🚀 

@rumbin can you tell us specifically which browsers/versions/OS this issue was occurring on for your users?

**Comment by Hammad-Raza** [comment]
@rusackas I am also on Mac. Chrome Version 97.0.4692.71

Our users are facing this issue since last week. Prior to that it was working fine.

**Comment by Hchiker** [comment]
same problem on PC WIndows, 
- FireFox 96.0.2 (64-bit) and 
- Chrome Version 97.0.4692.99 (Official Build) (64-bit)

**Comment by geido** [comment]
Hello @Hchiker which Superset version are you running?

**Comment by Hchiker** [comment]
Hello Geido !
I am using the version 1.1.0. 

Thanks!
Hicham

**Comment by knowvishnu** [comment]
This commit will fix the issue https://github.com/apache/superset/pull/16089.

**Comment by rusackas** [comment]
Looks like this was resolved and has gone quiet. Closing!
