### ISSUE TITLE
UI texts are truncated after localisation

### ISSUE THREAD

**Issue by kvaleev** [apache/superset#18055]
### How to reproduce the bug

1. Update translation of one of the locales (Russian) according to instructions: https://github.com/apache/superset/blob/master/CONTRIBUTING.md#translating
2. Build and run the services

### Expected results

UI texts are updated according to locale changes.

### Actual results

Some strings are truncated.

<img width="291" alt="Screenshot 2022-01-14 at 23 19 08" src="https://user-images.githubusercontent.com/3600063/149579985-99a0f44c-bbc4-441c-8f5c-97d822c03c05.png">

**Comment by geido** [comment]
Hello @kvaleev which Superset version are you running?

**Comment by rusackas** [comment]
Looking OK to me in current-era Superset!
<img width="201" alt="image" src="https://user-images.githubusercontent.com/812905/211117285-91386026-6c3c-4e55-9368-7df86205adf7.png">
