### ISSUE TITLE
Disable Strict Mode in SQL Lab

### ISSUE THREAD

**Issue by FaidJalal19** [apache/superset#18065]
Whenever I use GROUP BY in SQL Lab, I am getting an error stating

MySQL Error
mysql error: Expression #5 of SELECT list is not in GROUP BY clause and contains nonaggregated column 

How to disable the strict mode?

**Comment by betodealmeida** [comment]
This is an issue with MySQL, not Superset. You can disable `ONLY_FULL_GROUP_BY` by doing something like [this](https://stackoverflow.com/a/37508414/807118):

```sql
SET sql_mode=(SELECT REPLACE(@@sql_mode, 'ONLY_FULL_GROUP_BY', ''));
```

Alternatively, you can fix your SQL to ensure that all non-aggregated columns are listed in the `GROUP BY`.

Before:

```sql
SELECT
  COUNT(*),  -- aggregation
  country,  -- non-aggregation, should be in the group by
  gender  -- non-aggregation, should be in the group by
FROM my_table
GROUP BY
  country;  -- missing "gender"
```

After:

```sql
SELECT
  COUNT(*),
  country,
  gender
FROM my_table
GROUP BY
  country,
  gender;  -- ADDED "gender"
```
