### ISSUE TITLE
python-ldap package installation not working for ldap

### ISSUE THREAD

**Issue by curious86** [apache/superset#18074]
I was trying to set ldap based auth for superset, while running superset in docker. I have updated superset_config.py with the LDAP auth code.  Then ran the following command:
`docker-compose -f docker-compose-non-dev.yml up
`
But got the following error when tried to login:
`2022-01-18 08:55:35,505:ERROR:flask_appbuilder.security.manager:python-ldap library is not installed`

Can anyone give an example of how to install this package?

I have tried various ways to install python-ldap, but nothing seems to work:
1. Added following lines in Dockerfile:
```
RUN apt-get install -y libsasl2-dev python-dev libldap2-dev libssl-dev
RUN pip install python-ldap
```
2. Tried the following commands as well:
```
touch ./requirements/requirements-local.txt
echo "python-ldap" >> ./requirements/requirements-local.txt
```
^^trying this above commands and then running docker is throwing the below error for : superset, superset-worker, superset-worker-beat:
```
AP_R -DLDAPMODULE_VERSION=3.4.0 "-DLDAPMODULE_AUTHOR=python-ldap project" "-DLDAPMODULE_LICENSE=Python style" -IModules -I/usr/local/include/python3.8 -c Modules/LDAPObject.c -o build/temp.linux-x86_64-3.8/Modules/LDAPObject.o
superset_tests_worker    |   In file included from Modules/LDAPObject.c:3:
superset_tests_worker    |   Modules/common.h:15:10: fatal error: lber.h: No such file or directory
superset_tests_worker    |      15 | #include <lber.h>
superset_tests_worker    |         |          ^~~~~~~~
superset_tests_worker    |   compilation terminated.
superset_tests_worker    |   error: command '/usr/bin/gcc' failed with exit code 1
superset_tests_worker    |   ----------------------------------------
superset_tests_worker    |   ERROR: Failed building wheel for python-ldap
superset_tests_worker    | Failed to build python-ldap
superset_tests_worker    | ERROR: Could not build wheels for python-ldap which use PEP 517 and cannot be installed directly
superset_tests_worker    | WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
superset_tests_worker    | You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
superset_worker_beat     |   Installing build dependencies: started
superset_tests_worker exited with code 1
```

My mac python version is: Python 3.8.9

Please let me know , what is the right way to install the python-ldap package, while running superset in docker??

**Comment by curious86** [comment]
This is is resolved after installing the missing package (python-ldap) and prerequisites through the container's (superset-app container) interactive shell.

step 1:  (container name was superset-app in my case)
`docker exec -it <container name> /bin/bash
` 
step 2: (please verify if all the packages are needed)
`apt-get update -y && apt-get install -y python3-dev libldap2-dev libsasl2-dev ldap-utils tox lcov valgrind
`
step 3:
`pip install python-ldap
`
Ideally no need to restart the containers, but if it does not resolve the issue, try restarting specific container or all containers.
`docker-compose -f docker-compose-non-dev.yml restart`

**Comment by joaocosta123** [comment]
Hi, how can I make this permanent, aperently I lose this configuration after some time

**Comment by 88fingerslukee** [comment]
> Hi, how can I make this permanent, aperently I lose this configuration after some time

Has anybody found out how to make this permanent?
