### ISSUE TITLE
The union of two timestamptz changes the time of the stamps

### ISSUE THREAD

**Issue by polmonso** [apache/superset#18079]
The union of two timestamptz changes the time.

#### How to reproduce the bug

Go to sqleditor and run

```
select '2022-01-17T00:00:00+01:00'::TIMESTAMPTZ
UNION 
select '2022-01-18T00:00:00+01:00'::TIMESTAMPTZ
```

this produces

```
timestamptz
2022-01-16T23:00:00+01:00
2022-01-17T23:00:00+01:00
```

instead of 

```
timestamptz
2022-01-17 00:00:00+01
2022-01-18 00:00:00+01
```

Without the union the timestamptz is displayed correctly.

If the query is ran directly on postgresql it is displayed correctly.

This is more than a timezone display bug because `2022-01-16T23:00:00+01:00` and `2022-01-17 00:00:00+01` are different times.

Our guess is that since superset uses pandas internally, pandas doesn't handle datatimes with non-utc timezones very well and sometimes defines the column as 'object' instead of datetime[ns,UTC]. However, the superset must be doing something more wrong because the displayed time is not even the same input string anymore since the timezone offset is there but also applied on the time, as if it were mixing a conversion to UTC and using the original timezone offset when printing.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `1.3.2`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rumbin** [comment]
What timezone is your Superset installation set to?
I.e., what is the session timezone of Superset's connection to Postgres?

Not quite sure yet, but I suspect that it has to do with Postgres' timestamptz type which is represented internally as UTC and which only gets translated to/from the session timezone upon querying.

You might want to try a client like DBeaver where you can set the session timezone. Then run the above code while using different timezone settings.

**Comment by polmonso** [comment]
It's on Europe/Madrid

```
show timezone;
'Europe/Madrid'
```

We can of course change that, but superset should behave correctly regardless since postgres will return the timezone with the data. Changing the database default timezone to UTC would be a workaround.

**Comment by rusackas** [comment]
@john-bodley has a good PR [here](https://github.com/apache/superset/pull/19056) explaining many of the timezone intricacies of Superset. I hope it helps!

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
