### ISSUE TITLE
With latest update to Chrome, Scroll is missing while using Create Charts functionality

### ISSUE THREAD

**Issue by PraneshVG** [apache/superset#18072]
## Screenshot

[drag & drop image(s) here!]

## Description

When tried creating charts, the scroll option for Query section is missing. Due to which users are not able to access some of the functionality.

## Design input
Scrolling CSS is missing for <div class='css-gcs5mj'>

**Comment by geido** [comment]
Hello @PraneshVG please provide more information, such as your Superset version. Videos / GIFs are also appreciated. Thank you!

**Comment by geido** [comment]
Duplicate of #18047
