### ISSUE TITLE
deck.gl Multiple Layers doesn't work

### ISSUE THREAD

**Issue by hashbash** [apache/superset#18095]
deck.gl Multiple Layers doesn't work

#### How to reproduce the bug

1. Go to Scatterplot chart from examples
2. Change visualisation type to `deck.gl Multiple Layers`
2. Select `Screen Grid` chart in menu `DECK.GL CHARTS` and `Run query`

### Expected results

Map with multiple layers

### Actual results

Empty screen

#### Screenshots

![Screen Shot 2022-01-19 at 21 45 40](https://user-images.githubusercontent.com/10183440/150194687-8590f4ac-db9e-4167-aebc-3e2c70e77955.png)
![Screen Shot 2022-01-19 at 21 47 21](https://user-images.githubusercontent.com/10183440/150194701-c1f83941-f341-45d1-830a-2bbefdf0cf55.png)

### Environment

browser type and version: Chrome Version 97.0.4692.71 (Official Build) (x86_64)
superset version: 1.4.0
python version: Python 3.8.10
node.js version: v10.19.0
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04

### Logs

```
Cache key: None
2022-01-19 18:48:59,163:INFO:superset.viz:Cache key: None
2022-01-19 18:48:59,182:INFO:werkzeug:89.208.120.68 - - [19/Jan/2022 18:48:59] "POST /superset/explore_json/?form_data=%7B%22slice_id%22%3A73%7D HTTP/1.1" 200 -
2022-01-19 18:49:00,295:INFO:werkzeug:89.208.120.68 - - [19/Jan/2022 18:49:00] "POST /superset/log/?explode=events HTTP/1.1" 200 -
```

**Comment by stephenLYZ** [comment]
Hey @hashbash Thanks for reporting this issue. I believe https://github.com/apache/superset/pull/17703 has fixed this problem but 1.4.0 does not `cherry-pick` this commit. cc  @rusackas

**Comment by rusackas** [comment]
Whoops... meant to tag the PR, not this Issue. We'll make sure that fix gets into 1.4.1. @hashbash I'll take it that the PR closes this issue for now. Please re-open it if the issue resurfaces in 1.4.1 or later.

**Comment by leafant** [comment]
This issue still exist in 1.4.1.

**Comment by leafant** [comment]
> This issue still exist in 1.4.1.

This issue still exist in 1.4.1.

**Comment by riazarbi** [comment]
I'm using Superset 1.4.2 and just discovered this bug as well.

**Comment by JTvdWal-WUR** [comment]
Just wondering, to what version of Superset should we upgrade to get free of this problem?
