### ISSUE TITLE
Javascript editor duplicate characters

### ISSUE THREAD

**Issue by hashbash** [apache/superset#18094]
Javascript editor duplicate characters

#### How to reproduce the bug

1. Go to new chart with deck.gl Screen Grid
2. Enable ENABLE_JAVASCRIPT_CONTROLS and start input characters into window
3. Input "1234"

Expected characters in this window "1234", actual characters "1234123121"

### Expected results

`1234`

### Actual results

`1234123121`

#### Screenshots

![image](https://user-images.githubusercontent.com/10183440/150188688-425686ba-fba5-4094-b3a0-50c80987f4ab.png)

### Environment

- browser type and version: Chrome Version 97.0.4692.71 (Official Build) (x86_64)
- superset version: `1.4.0`
- python version: `Python 3.8.10`
- node.js version: `v10.19.0`
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [V] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [V] I have reproduced the issue with at least the latest released version of superset.
- [V] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by srinify** [comment]
Hey @hashbash did the fix address your issue?

https://github.com/apache/superset/pull/18146

If so, please close this issue :)
