### ISSUE TITLE
[Dashboard Editor] Cmd + Z should not revert layout changes when editing chart title

### ISSUE THREAD

**Issue by ktmud** [apache/superset#18096]
#### How to reproduce the bug

1. Go to dashboard edit mode
2. Make some layout changes. For example, resize a chart.
3. Click on a chart title to edit it:
    <img width="420" alt="Xnip2022-01-19_11-40-07" src="https://user-images.githubusercontent.com/335541/150202161-a1364779-9442-40b1-8470-1b45fa034a30.png">
4. Enter something and click on Ctr + Z (Windows) or Cmd + Z (macOS)

### Expected results

The input value revert to previous edits. The layout doesn't change.

### Actual results

The layout change was reverted but the input value didn't change.

#### Screenshots

N/A

### Environment

Latest `master` branch

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

N/A

**Comment by stephenLYZ** [comment]
Agree. I think it makes sense. And I open a https://github.com/apache/superset/pull/18137 to improve this behavior.

**Comment by rusackas** [comment]
Looks like the fix was merged. Closing this, but happy to re-open if anyone sees this behavior being exhibited.
