### ISSUE TITLE
Time-series Area Chart not showing any filling anymore after update to 1.4.0

### ISSUE THREAD

**Issue by D3nn3** [apache/superset#18129]
As the title says, with Superset 1.4.0 Area Charts don't show any filling anymore. The "Area chart opacity" also doesn't have any effect anymore.

**Comment by bundgus** [comment]
Same here.

**Comment by villebro** [comment]
FYI I did a custom release of the `@superset-ui/plugin-chart-echarts` that includes the area chart opacity bug fix and which should be compatible with the 1.4 release branch. Here's the bump PR (I expect this to be made available in the 1.4.2 release): #18566

**Comment by rusackas** [comment]
@andrey-zayats took a look at this and was unable to reproduce the issue. I'm going to go ahead and remove the `validation:required` label and close the issue. If anyone sees this happening in Superset 2.0.x or later, or on `master`, we're open to revisiting this conversation, re-opening the ticket, or triaging a new Issue with updated context. Thank you!
