### ISSUE TITLE
Line chart csv does not use rolling window values

### ISSUE THREAD

**Issue by serenajiang** [apache/superset#18132]
Previously, when a rolling window function was applied to a line chart in explore view, the resulting averaged values were reflected in the csv download. Now, the csv download only contains the raw data.

Unsure when this change began - estimated sometime between October 19, 2021 -> January 20, 2021 based on user report.

#### How to reproduce the bug

1. Create a line chart.
2. Apply a rolling window function (ex. mean, period length 7)
3. Download csv
4. Compare csv results against chart data.

### Expected results

Values in csv download should reflect the averaged values plotted in the line chart.

### Actual results

Values in csv download correspond to the raw data.

### Environment

Up to date with apache/master as of January 18, 2022

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I'm guessing this may be intended behavior, but since it is different from previous behavior and requires some more advanced post processing,  it might be a pain point for users.

**Comment by serenajiang** [comment]
```
ds	b
2022-01-01	1
2022-01-02	2
2022-01-03	3
2022-01-04	4
2022-01-05	5
2022-01-06	6
2022-01-07	7
```
A minimal example like this should work using SUM(b) as the metric in the line chart and any window function. Downloading the chart data previously used to download the results after the window function was applied, but now it downloads the results of the query.

A user reported this issue when they downloaded the csv from a chart and compared it to a previous download. There have been a lot of changes since October, so I'm not sure exactly when this happened or what caused it.

**Comment by villebro** [comment]
It's like this:
- the raw data is always returned for the legacy NVD3 line chart
- the final data is always returned for the new ECharts line chart

I double checked, and I can confirm this is correct. So the solution is to just use the new line chart.

**Comment by rusackas** [comment]
Everyone should be using the new line chart by now, so I'll close this out :D
