### ISSUE TITLE
Number of rows returned from the database and listed in Chart Explore > Data section (and drawn on charts) differs by 2

### ISSUE THREAD

**Issue by igor-lukyanov** [apache/superset#18155]
After migration to 1.4.0 from a previous version (1.0.1) some charts (mainly with low number of dots) got a different (wrong) look (for instance, some area chart became falling instead of growing before). Short investigation indicated that all area charts started to lose first 2 rows in the result set somewhere between fetching them from a database (which returns 16 rows, for example) and drawing data drawn on the chart (when dataset, according to the Data section, contains only 14 rows). Clickhouse database is used.

Notably, exactly 2 first rows are missed - when 'Sort descending' option is enabled in chart settings, 2 greatest values are lost, and when it's disabled - 2 least values. Sorry for a bit framed screenshots (production data). 

The same problem is appliable affects pie charts (also with Clickhouse).

#### How to reproduce the bug

1. Open area or pie chart in Chart Explorer. 
2. Wait until the data is loaded and chart is rendered
3. Scroll down to 'Data' section.
4. Check the row counter
5. Copy the query and execute manually without using Superset, in some IDE, for instance.
6. Check the row counter there and compare with that one from Superset, they differ by 2.

(please complete the following information):

- browser type and version: Safari
- superset version: 1.4.0

<img width="596" alt="Screenshot 2022-01-24 at 23 02 31" src="https://user-images.githubusercontent.com/4200212/150857207-1789e817-ff3d-4a33-8042-a26246ffd528.png">
<img width="736" alt="Screenshot 2022-01-24 at 23 02 01" src="https://user-images.githubusercontent.com/4200212/150857210-0c2e4a67-2430-4fa7-9676-02f09d384b56.png">

**Comment by igor-lukyanov** [comment]
UPD: does not affect Postgresql databases, Clickhouse only.

**Comment by igor-lukyanov** [comment]
Created MRE as a virtual query
```select all 1 as test
     union all select 2 as test
     union all select 3 as test
     union all select 4 as test
```

AND table chart, please check the screenshot.
<img width="1054" alt="Screenshot 2022-01-26 at 17 16 13" src="https://user-images.githubusercontent.com/4200212/151179320-4fafa82c-da4f-4491-ac4f-a9ec1e5f9006.png">

**Comment by mayurnewase** [comment]
cant reproduce on master
![image](https://user-images.githubusercontent.com/12967587/152105157-a8b4307e-e5a4-498c-9fbb-2c6eb90c0a47.png)

**Comment by rusackas** [comment]
This was marked as unable to repro over a year ago so I'll close it as stale/fixed.

**Comment by geido** [comment]
Hello @igor-lukyanov thanks for reporting this issue. As we are not supporting this version of Superset anymore, I am going to close this one. Please, feel free to re-open it if you think this problem affects recent versions of Superset.
