### ISSUE TITLE
Markdown with iframe (Echart type - Big Number ) error: "Unexpected token < in JSON at position 0"

### ISSUE THREAD

**Issue by gndsnts** [apache/superset#18150]
Hey, 

I'm trying to create simple html page, that use iframe with link from superset.

In this dashboard , there are 2 echarts:
1 Timeseries - MarkDown element  with iframe 
1 Big Number -Markdown Element  with iframe

Print from superset:
![image](https://user-images.githubusercontent.com/78511708/150815638-28398af8-947a-4fd3-a21e-75dfe78f6593.png)

Print from my created page, that contain a iframe with url dashboard:
![image](https://user-images.githubusercontent.com/78511708/150815750-ba1488a5-8d32-4c91-91ed-cb0df26a2bd4.png)

I don't know how this happen, one iframe work's and the other have the error: "Unexpected token < in JSON at position 0"

In devtools from chrome, i have this result:
![image](https://user-images.githubusercontent.com/78511708/150816213-79b64200-5907-4808-92c9-da2e7b215b88.png)

At the moment in file config.py, I have wtf_crsf_enable = true(default), and use this cors configuration:
# CORS Options
ENABLE_CORS = True
CORS_OPTIONS: Dict[Any, Any] = {}
#I add my domain to list SUPERSET_WEBSERVER_DOMAINS, example:
SUPERSET_WEBSERVER_DOMAINS = {"domain1","domain2","domain3"}

My config.py: [config.py.txt](https://github.com/apache/superset/files/7926696/config.py.txt)

I think this is the most important changes that I did, but it's not enought... if any one can help me, I would appreciate it

Best regards

**Comment by geido** [comment]
Hello @gndsnts which Superset version are you running?

**Comment by geido** [comment]
Related or duplicate of #18126

**Comment by mbcsa** [comment]
Hi, something similar happens to me. 
In my case, I think it has something to do with legacy charts.





![image](https://user-images.githubusercontent.com/92950610/150996648-d5eecff3-ef98-4d8f-b7c0-b8e85c477da7.png)

1- When I embed a public dashboard with "echarts" and "legacy charts" only "echarts" works making requests to 
**domain.com/api/v1/chart/data?form_data=...**   ( 200 OK )
2-  while legacy charts makes requests to:
**domain.com/superset/explore_json/?form_data=...**    (302 FOUND - then redirects to /login)
**domain.com/login/** 

![image](https://user-images.githubusercontent.com/92950610/150996888-71f3a60f-1572-4a2d-a48d-fd78f5e170c3.png)

**Comment by geido** [comment]
Related or duplicate of #17436

**Comment by mbcsa** [comment]
> Hi, something similar happens to me. In my case, I think it has something to do with legacy charts.
> 
> ![image](https://user-images.githubusercontent.com/92950610/150996648-d5eecff3-ef98-4d8f-b7c0-b8e85c477da7.png)
> 
> 1- When I embed a public dashboard with "echarts" and "legacy charts" only "echarts" works making requests to **domain.com/api/v1/chart/data?form_data=...** ( 200 OK ) 2- while legacy charts makes requests to: **domain.com/superset/explore_json/?form_data=...** (302 FOUND - then redirects to /login) **domain.com/login/**
> 
> ![image](https://user-images.githubusercontent.com/92950610/150996888-71f3a60f-1572-4a2d-a48d-fd78f5e170c3.png)

In my case, I solved it by adding

WTF_CSRF_ENABLED = False

to superset_config.py

It allowed me to show Legacy Charts.

**Comment by suddjian** [comment]
> In my case, I think it has something to do with legacy charts.

That's exactly right, legacy charts use an older data endpoint that wasn't added to the CSRF excempt list.

> However, I believe that it is not a good option to disable this CSRF protection.

Also correct, disabling CSRF protection can open you up to XSS vulnerabilities.

We ran into the same problem independently, and just merged a PR that changes the CSRF exempt list, here: https://github.com/apache/superset/pull/17530/files#diff-c99ae4b2b09b756ab2189a99a9685229f9d12633fc2616c368ea869770f603bfR202. The endpoint is safe to make exempt from CSRF, because although it is a `POST`, it does not alter any application state and can't be used for XSS attacks.

I believe that commit should solve this issue, and the other related ones.

**Comment by gndsnts** [comment]
Thanks to everyone for the help.
