### ISSUE TITLE
[explore][filter] IN filter select box will be loading forever when there is null value in the column

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#18178]
IN filter select box will be loading forever when there is null value in the column

#### How to reproduce the bug
use example data 'Covid Vaccine'
1. Go to explore, select chart type 'Big number'
2. add Metrics: count, add Filter:  fda_approval_indicators (with all null value)
3. select 'IN' for filter type, 
4. Observe filter value file and See error

### Expected results
Able to show null for user to select

### Actual results

loading forever

#### Screenshots

<img width="1790" alt="Screen Shot 2022-01-24 at 8 32 24 PM" src="https://user-images.githubusercontent.com/81597121/151215080-87acadbd-8f1d-4dbc-a4f3-2421a7a4cf5c.png">

### Environment

(please complete the following information):

- browser type and version:
- superset version:  master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
closed by https://github.com/apache/superset/pull/18171
