### ISSUE TITLE
Seeing 404 Not Found with SQLLAB_BACKEND_PERSISTENCE Enabled

### ISSUE THREAD

**Issue by chris-befoul** [apache/superset#18184]
Latest Version of Apache Superset from docker image.

When the feature flag SQLLAB_BACKEND_PERSISTENCE is set to true in SQL lab upon selecting a schema receiving superset error trouble finding schema.  

And seeing this error in logs upon trying to select schema: 
404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

![image](https://user-images.githubusercontent.com/55672717/151259802-d464d044-d809-442e-8728-30004d8a920c.png)

The next call where I am still able to select the schema executes no problem with a 200 status and I am able to run a query against it. When SQLLAB_BACKEND_PERSISTENCE is set to false, I am not seeing these errors but will receive the local storage error which I am trying to eliminate.

Relevant code:

 
![image](https://user-images.githubusercontent.com/55672717/151260977-e426601d-e62f-4874-a736-80646bd93471.png)
![image](https://user-images.githubusercontent.com/55672717/151261727-acffe3b8-a8ab-4e3a-b736-d06dee48054b.png)

Any help would be greatly appreciated!

**Comment by rusackas** [comment]
@chris-befoul this issue hasn't gotten any attention for quite a while. Sorry about that, yet optimistic that perhaps that means it's no longer an issue. Can you confirm whether or not you're still facing this, or if it was resolved in a newer version of Superset (e.g. 2.0.1)?

**Comment by chris-befoul** [comment]
@rusackas this issue has been resolved, thanks!
