### ISSUE TITLE
Long Running Queries -  Auto Cancellation/Kill process in superset

### ISSUE THREAD

**Issue by nirajtambat** [apache/superset#18191]
In superset if there is a long running query running more than 3 mins (for example), is it possible to kill the query automatically and take the next one in the queue. application should auto-cancel the query. Also Query time out option is set but still on backend query is running. It's not cancelling query execution on database server.  Let us know any solution for this.

**Comment by srinify** [comment]
Hey Niraj! Do you mind posting in the #debug-together channel in the Superset Slack or over in Github Discussions? You can find a link to our Slack here: https://superset.apache.org/community

We'd like to keep Github issues focused on bugs with reproduction instructions that can be validated, etc.
