### ISSUE TITLE
Unable to use view chart in explore feature on 1.4.0

### ISSUE THREAD

**Issue by iercan** [apache/superset#18198]
After upgrading to 1.4.0, we are unable to use view chart in explore feature for some charts. When I try to open in explore, I'm getting a blank chart as seen in the picture.

Only thing I detected common between these charts is that they all have `../superset/explore/?URL_IS_TOO_LONG_TO_SHARE&...` in their urls. Maybe something wrong with url conversion?

#### How to reproduce the bug
Try to open chart in explore

### Expected results
Charts need to be opened in explore mode

### Actual results

Getting blank chart
#### Screenshots

![Screenshot from 2022-01-27 16-22-29](https://user-images.githubusercontent.com/3406152/151367523-6d91d24a-dd4c-498d-baf7-2df2156a5d7a.png)

![image](https://user-images.githubusercontent.com/3406152/151366353-ea255643-0583-47a2-804a-2b8148bd3e77.png)

### Environment
- browser type and version: Chrome 97
- superset version: 1.4.0 installed with official docker image.

**Comment by srinify** [comment]
Hi @iercan how do you suggest someone replicate this? For example -- should someone setup Superset in 1.3, make a time series chart, then upgrade and try to recreate this?

**Comment by iercan** [comment]
@srinify Unfortunately  I'm not sure how to replicate it. I'm just suspecting URL_IS_TOO_LONG_TO_SHARE conversion. We were using 1.3.2 for long time and didn't encountered this. I'm pretty sure it happened after 1.4.0 upgrade.

**Comment by villebro** [comment]
@iercan you appear to be running into a long standing problem in Superset which @michael-s-molina has been hard at work to solve once and for all. Here's the PR that should fix this problem for good: #18181. Not sure what's causing the URL to overflow in 1.4 compared to 1.3, but can you check how big the chart metadata blob is?

**Comment by fritzb** [comment]
We also noticed the same issue. I noticed, it happened on all large size dashboard, and our large dashboard are with tabs. Small dashboard without tabs seemed to be okay.

**Comment by iercan** [comment]
> can you check how big the chart metadata blob is?

@villebro  Sorry I don't know how to get this information, can you explain it?

**Comment by villebro** [comment]
@iercan you can do the following:
1. Go to the "Charts" page and hover over the chart in question. You'll see a link similar to this: `http://localhost:9000/superset/explore/?form_data=%7B%22slice_id%22%3A%20747%7D`. For this chart the chart id is `747`
2. Go to the following url, replacing `747` with the chart id: `http://localhost:9000/chart/edit/747`
3. Here you'll see the "Parameters" secion which contains the chart metadata

One question: does the error only come up when you go from the Dashboard page and click on "View chart in Explore", or does it also happen when going to Explore from the "Charts" page?

**Comment by iercan** [comment]
It happens only from dashboard page. Charts menu works fine. If I click it from charts menu I don't see `URL_IS_TOO_LONG_TO_SHARE` keyword in the url which kinda validate my suspects right? 

I saved metadata to a file and it seems 77 line and about 3kB.

**Comment by villebro** [comment]
My initial hunch is that these cherries would be needed: #16621 and #17123. But it appears they're already included in 1.4.0. So maybe there's yet another cherry that's needed. @iercan and @fritzb can one of you copy the link from the "View chart in Explore" menu item and post it here so we can see what additional metadata the URL contains?

![image](https://user-images.githubusercontent.com/33317356/151508266-b621a87d-bc0c-4281-ad75-b99051f322e9.png)

**Comment by iercan** [comment]
This is the url before I click. (I decoded them for easy read)

`https://superset.mydomain.com/superset/explore/?URL_IS_TOO_LONG_TO_SHARE&form_data={"datasource":"129__table","viz_type":"echarts_area"}`

and this is converted url after I click

`https://superset.mydomain.com/superset/explore/?form_data={"viz_type":"echarts_area","datasource":"129__table","time_range_endpoints":["inclusive","exclusive"],"granularity_sqla":"__time","time_grain_sqla":"P1D","time_range":"No filter","groupby":[],"adhoc_filters":[],"order_desc":true,"row_limit":10000,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","color_scheme":"supersetColors","seriesType":"line","opacity":0.2,"only_total":true,"markerSize":6,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","rich_tooltip":true,"tooltipTimeFormat":"smart_date","y_axis_format":"SMART_NUMBER","truncateYAxis":true,"y_axis_bounds":[null,null],"extra_form_data":{}}`

**Comment by villebro** [comment]
I tried to repro on 1.4.0, but I don't have any massive enough dashboards that would cause this. Out of curiosity, do you have a lot of different labels on the problematic dashboard? That's the main thing I can think of that might bloat the URL..

**Comment by iercan** [comment]
Dashboard I get this error is not so big actually. Here is some characteristics of it if helps.

* There is 9 native filters. 2 of them is nested. And 2 of them have another scopes. 
* There is 3 tab in the dashboard.  First one have 10 charts, second one have 5 charts and last one have just 1 charts. 
* There is 2 different dataset. Charts that have this problem shares same dataset. I also checked another dashboard that use same dataset and saw they don't have this problem. 
* There is some predefined filter in the charts. I also tried to remove them but result didn't change. 

I also forgot to send a working url sample of a chart If I open it from Charts menu.

`https://superset.mydomain.com/superset/explore/?form_data={"viz_type":"echarts_area","datasource":"129__table","slice_id":1151,"time_range_endpoints":["inclusive","exclusive"],"granularity_sqla":"__time","time_grain_sqla":"PT5M","time_range":"Last+day","metrics":["total_user"],"groupby":[],"adhoc_filters":[{"clause":"WHERE","comparator":"0","expressionType":"SIMPLE","filterOptionName":"filter_2hk7pthcti9_4t133u8ju3w","isExtra":false,"isNew":false,"operator":"!=","operatorId":"NOT_EQUALS","sqlExpression":null,"subject":"integer_userId"},{"clause":"WHERE","comparator":"0","expressionType":"SIMPLE","filterOptionName":"filter_svpaf2824g_6azb3l7o3de","isExtra":false,"isNew":false,"operator":">","operatorId":"GREATER_THAN","sqlExpression":null,"subject":"integer_pageView"}],"limit":null,"timeseries_limit_metric":[],"order_desc":true,"row_limit":null,"rolling_type":null,"time_compare":["1+day+ago","1+week+ago"],"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","color_scheme":"googleCategory10c","seriesType":"line","opacity":0.2,"only_total":true,"markerSize":6,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","rich_tooltip":true,"tooltipTimeFormat":"smart_date","y_axis_format":"SMART_NUMBER","truncateYAxis":true,"y_axis_bounds":[null,null],"extra_form_data":{}}`

**Comment by villebro** [comment]
@iercan and @fritzb are either of you able to help trying to debug this issue using a slightly modified build of 1.4? I can open a branch with a small code change that will print out some info that should show what's causing this problem.

**Comment by iercan** [comment]
@villebro We are using official docker image to deploy and we also have another deployment for debug purpose. I can test easily if you can provide me a docker image.

**Comment by villebro** [comment]
Ok I'll see if I can make one

**Comment by iercan** [comment]
Problem still exists on 1.4.1

**Comment by villebro** [comment]
FYI: This issue is solved in the forthcoming 1.5.0 release.

**Comment by iercan** [comment]
I've tested 1.5.0rc3. It seems resolved. Thanks.
