### ISSUE TITLE
Issue with calendar heatmap - a 0 is not getting coloured red

### ISSUE THREAD

**Issue by navnathedb** [apache/superset#18193]
We're trying to integrate Github with Superset. In that, we have created some dashboards with charts.
We're getting an issue with the calendar heatmap chart -  a 0 is not getting coloured red
#### How to reproduce the bug
1. Create a calendar heatmap chart from GitHub or any Github sort of data 
2. Open chart by clicking in charts tab or even in create chart section 
3. There is no actual error but as per chart settings cell data with '0' value should be colored with red but on the chart it's white in color (check the attached screenshot)

### Expected results

Data with cell value '0' should be in red colour
### Actual results

It's white in colour
#### Screenshots

<img width="533" alt="Screenshot 2022-01-25 at 7 12 52 AM" src="https://user-images.githubusercontent.com/47140549/151327834-eb5b9f38-3353-4fa6-b17b-5e6d65660d0e.png">

### Environment

(please complete the following information):

- browser type and version: Google chrome Version 97.0.4692.71 (Official Build) (x86_64)
- superset version: `1.3.2`
- python version: `3.8`
- any feature flags active: No

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Also check chat on Slack - https://apache-superset.slack.com/archives/C016B3LG5B4/p1643075312076400

**Comment by rusackas** [comment]
Closing this since it didn't get any love for about a year now, and didn't get any traction on Slack either. @navnathedb if you're still facing this in 2.0.x we can re-open this. Ping me on Slack if you'd like, too. Hopefully it's magically solved by now... or if you've done any investigation, there's probably just some equality/range operator somewhere in the code that needs a tweak if you want to open a PR :)

**Comment by dineshws** [comment]
Is there any plan to fix this? Because this issue is still there in Preset as we are using Preset. 0 should be considered as a valid value and should be treated as other valid values.

**Comment by adamcunnington-mlg** [comment]
We were tripped up by this today too. Had to manually adjust our metric to be `GREATEST(..., 0)` - silly!

**Comment by eszterszarka** [comment]
This is still a really annoying issue, 0 is showing as a missing value
