### ISSUE TITLE
How to create drop-down list to switch between different data tables

### ISSUE THREAD

**Issue by Vishal2816** [apache/superset#18209]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
I have 3 different data tables which I just want to display the raw data in a table format, but would like to create a drop-down list for user to switch between the 3 different data tables. I have experience creating drop-down list which switch between values in a column, but can't seems to figure out how to do the same for tables. Is there a way to do.

**Comment by Vishal2816** [comment]
Kindly let me know if we have this option in Apache Superset

**Comment by srinify** [comment]
Hey @Vishal2816 do you mind asking over in the Discussions tab or in the Superset Slack? We'd love to keep Github issues focused on bugs that need to be validated, replicated, and fixed 🙏 

- Discussions: https://github.com/apache/superset/discussions
- Slack: https://superset.apache.org/community/

**Comment by Vishal2816** [comment]
Hi Srini, Thankyou for the reply will post in the slack channel and in
GitHub issue.

Kind regards
Vishal Sharma
