### ISSUE TITLE
Field table_columns.type varchar(32) is too short

### ISSUE THREAD

**Issue by igor-lukyanov** [apache/superset#18203]
Superset version 1.4.0

Particularly in Clickhouse column types may be quite long: 
'type': "ENUM8('V1' = 0, 'V2' = 1, 'V3' = 2, 'V4' = 3, 'V5' = 4, 'V6' = 5, 'V7' = 6, 'V8' = 7)"

which leads to `(psycopg2.errors.StringDataRightTruncation) value too long for type character varying(32)` error while creating a new dataset from a table with long enough enums. The solution is to `ALTER TABLE superset.table_columns 
ALTER COLUMN type TYPE varchar`. 

Sorry for not submitting a patch, not quite familiar with superset internals.

**Comment by villebro** [comment]
I'm closing this as it's already been fixed on master branch here: #17360 . However, pinging @eschutho (release manager for 1.4 branch): do you consider this a viable cherry for a 1.4.x patch release, or should we wait until 1.5?
