### ISSUE TITLE
Blinking Native dashboard filter

### ISSUE THREAD

**Issue by BeckersJ** [apache/superset#18213]
When I zoom in on any dashboard with native dashboard filter enabled, the #rc-tabs-1-more start to blink at 125% and stop at 150% zoomlevel. See attached video. 

#### How to reproduce the bug

1. Go to any dashboard
2. Zoom from 100% to 125%
3. See error
4. Zoom further to 150% error disappears

### Expected results

Nothing, the responsive design should allow the width of the native filter box to be enough to accommodate both the all filter and filter sets tabs. It works fine in 100% zoom and 150% zoom.

### Actual results

The div with the .ant-tabs-nav-more class starts to blink.

#### Screenshots

https://user-images.githubusercontent.com/96041225/151526792-5067ce37-06f9-4bc5-bb0e-f30b39330097.mp4

### Environment

(please complete the following information):

- browser type and version: Edge (97.0.1072.69 (64-bits)) Chrome (97.0.4692.99 (64-bits))
- superset version: `1.4.0`
- python version: `3.8`
- any feature flags active:
  - "ROW_LEVEL_SECURITY": True,
  - "ALERT_REPORTS": True,
  - "THUMBNAILS": False,
  - "DASHBOARD_NATIVE_FILTERS": True,
  - "DASHBOARD_CROSS_FILTERS": True,
  - "DASHBOARD_NATIVE_FILTERS_SET": True,
  - "ENABLE_TEMPLATE_PROCESSING": True,
  - "DASHBOARD_RBAC": True,

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rumbin** [comment]
Confirming this one. On a large screen (42", 4k) this effect is also observable in 100% zoom level.
