### ISSUE TITLE
Unexpected error: ListViewError: Invalid filter config, id is not present in columns

### ISSUE THREAD

**Issue by ramesh2744** [apache/superset#18210]
Prevent 'undefined' error when viewing the dashboard (or charts) listview in an anonymous mode.

#### How to reproduce the bug

Reproduce the error as follows:

Allow anonymous access by setting `PUBLIC_ROLE_LIKE = "Gamma"`
Without logging in, click on dashboards or charts. This error displays:
_Unexpected error:ListViewError: Invalid filter config, id is not present in columns_

### Expected results
Dashboards/charts must be visible without any issues/errors.

### Actual result
This issue observed when we make upgrade from v1.3 to v1.4

#### Screenshots

![image](https://user-images.githubusercontent.com/59677029/151490917-7314668d-518b-49d4-9899-7d32909c4e1c.png)

### Environment

(please complete the following information):

- browser type and version: `Chrome Version 97.0.4692.71`
- superset version: `1.4`
- python version: `Python 3.7.5`
- node.js version: `v8.10.0`

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Browser console log:

_**ListViewError: Invalid filter config, id is not present in columns
    at 87c5db28d6d4ce263182.chunk.js:932:15
    at Array.forEach (<anonymous>)
    at ListView (87c5db28d6d4ce263182.chunk.js:930:13)
    at oh (vendors.866d9853ec9ca701f3b8.entry.js:54972:146)
    at Rj (vendors.866d9853ec9ca701f3b8.entry.js:55080:496)
    at Qj (vendors.866d9853ec9ca701f3b8.entry.js:55065:199)
    at Kj (vendors.866d9853ec9ca701f3b8.entry.js:55065:128)
    at yj (vendors.866d9853ec9ca701f3b8.entry.js:55058:172)
    at vendors.866d9853ec9ca701f3b8.entry.js:54942:115
    at exports.unstable_runWithPriority (vendors.866d9853ec9ca701f3b8.entry.js:55173:467)**_
    
    
![image](https://user-images.githubusercontent.com/59677029/151502303-1fe8a756-38ca-4ddd-a1be-2c9d18a48638.png)

**Comment by geido** [comment]
Thanks @ramesh2744 for reporting this issue. We are looking into this problem and we'll keep you posted

**Comment by ramesh2744** [comment]
Thank you @geido

**Comment by zufolo441** [comment]
Hi, same problem here.

**Comment by NoorAhmd** [comment]
Any solution for this? I still have this problem

**Comment by swanitzek** [comment]
Is this fix included in any release of Apache Superset yet?
