### ISSUE TITLE
[dashboard] Scrolling table viz overlaps next chart

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#18223]
If you have a chart on dashboard, which isn't fully displayed - e.g. need scrolling to see other records, it overlaps the next item on the dashboard (eg. a title, or another chart). Upon some investigation, we determine it is specifically a bug with chart that have descriptions. If you toggle the chart description off and then on again, all works well, but when you refresh the bug is back.

In case the table has pagination, the pagination bar is overflowing - see screenshots.

There is a workaround which minimizes the impact when user adds empty row below the chart, but then they see the grey text "empty row" so it's still not ideal. (instead of scrolling over chart or title, it's over the grey text"empty row").

#### How to reproduce the bug
described above

#### Screenshots
without toggle (correct)
<img width="694" alt="Screen Shot 2022-01-28 at 3 59 58 PM" src="https://user-images.githubusercontent.com/61221714/151637264-8ee88800-8f2f-45b1-97db-a8101b5d72c9.png">

(with toggle description - overflow)
<img width="682" alt="Screen Shot 2022-01-28 at 3 59 49 PM" src="https://user-images.githubusercontent.com/61221714/151637265-40cb33ca-65bb-46d1-ab79-72ad589cac4b.png">

Another example of the same issue:
<img width="690" alt="Screen Shot 2022-01-28 at 4 01 25 PM" src="https://user-images.githubusercontent.com/61221714/151637418-eb2a9b0a-a12d-46c1-bc20-2452272f4897.png">

### Environment
latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by geido** [comment]
Hello @zuzana-vej I was looking back into this issue and I cannot reproduce it right now. Could you please try again with the latest master? If you still encounter the issue please provide more information such as browser and version used. Thanks!

**Comment by zuzana-vej** [comment]
Here are exact steps to repro this:
Chart has description. If you just toggle the description it will be ok and it will shift the title of the next section down. If you leave the description toggled, and then refresh the page, it will load the chart with description toggled and the bottom of the table will overlap the next section. 
If you put white background to the header which is below the chart, it will not overlap, but it will have half of the last row unreadable which is even worse.

Step 1: toggle chart description --> no problem.
Step 1b: if you untoggle & toggle --> no problem.
<img width="114" alt="Screen Shot 2022-02-22 at 4 03 12 PM" src="https://user-images.githubusercontent.com/61221714/155234420-0a6e6fea-b4cb-48f7-8612-14851e4d3574.png">

Step 2: Keep toggled and refresh page (ctrl+R). Overlap - --> problem with overlap.
<img width="103" alt="Screen Shot 2022-02-22 at 4 01 41 PM" src="https://user-images.githubusercontent.com/61221714/155234394-a09d2aa1-8307-4ee5-959e-cbe55c2e2d51.png">

Browser Google Chrome Version 98.0.4758.102 (Official Build) (x86_64)
Latest master - released from master on 02/17

**Comment by serenajiang** [comment]
Thanks for the fix!
