### ISSUE TITLE
Big Number does not handle DECIMAL metrics

### ISSUE THREAD

**Issue by serenajiang** [apache/superset#18222]
If the metric for a big number chart has the type DECIMAL, the chart displays an error: `No data after filtering or data is NULL for the latest time record`

From inspecting the request result for `/api/v1/chart/data`, it seems like this occurs because the decimal is analyzed as a string.

#### How to reproduce the bug
1. Run query in sqllab: `SELECT CAST(1 AS DECIMAL) AS x, DATE('2022-01-27') AS ds`
2. Explore chart
3. Select big number chart, use `SUM(x)` as metric
4. Run. 

### Expected results

Chart shows big number with value `1`. Data returned from `/api/v1/chart/data` is `[{SUM(x): 1}]`
### Actual results
Error is shown. Data returned from `/api/v1/chart/data` is `[{SUM(x): "1"}]`

#### Screenshots

![image](https://user-images.githubusercontent.com/14146019/151634523-9cf3780c-babe-4151-89f8-e01ea4864085.png)

### Environment
Up to date with apache/master as of 2022-01-26.

Presto SQL

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by jinghua-qa** [comment]
I can not reproduce in the latest superset master

https://user-images.githubusercontent.com/81597121/152401153-98d97cc7-da11-4102-a7d5-9a860294044b.mov

**Comment by serenajiang** [comment]
@jinghua-qa We deployed master yesterday and I am still able to reproduce this issue :/ Perhaps it is specific to certain SQL engines?

In Presto, the column `x` is identified as a numeric column in explore with data type `DECIMAL(38, 0)`

**Comment by serenajiang** [comment]
I put out a PR in PyHive: https://github.com/dropbox/PyHive/pull/430
