### ISSUE TITLE
[mixed time-series] collection of related issues

### ISSUE THREAD

**Issue by rumbin** [apache/superset#18236]
This is a issue collection which bundles the various open issues that the _Mixed Time-Series_ chart is currenlty exhibiting.

I am hoping that this compilation helps bundling the development efforts for this otherwise great chart type.
Presumably, some of these issues can be fixed in a single PR.
Thus, I'll try to categorize these issues a bit...

**Note:**  
Some of the issues are also related to "Time-series Bar Chart v2"

## Two queries

These issues arise from the fact that this chart type is building on _two_ distict queries, Query A and Query B.
It seems that other Superset components are not handlich this circumstance gracefully:

* #16816
* #17960
* #15858

### X-Axis

* #17128
* #15674
* #18232

### Values formatting

* #15672
* #18234

### Second Y-Axis

* #15672
* #18235

## Environment

- browser type and version: Chrome  96.0.4664.93
- superset version: 1.4.0
- all other versions: as defined in Superset's Docker image
- Feature flags:

```
# stable:
      "THUMBNAILS": True,
      "SQLLAB_BACKEND_PERSISTENCE": True,
      "ENABLE_TEMPLATE_PROCESSING": True,
      "DASHBOARD_CROSS_FILTERS": True,

      # experimental:
      "ALERT_REPORTS": True,
      "ALERTS_ATTACH_REPORTS": True,
      "DASHBOARD_NATIVE_FILTERS": True,

      # unclassified:
      "ENABLE_EXPLORE_DRAG_AND_DROP": True,
      "ENABLE_DND_WITH_CLICK_UX": True,

      # development:
      "DASHBOARD_NATIVE_FILTERS_SET": True
```

## Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rumbin** [comment]
This issue should not be closed by the stale bot, in my eyes.

**Comment by huyhandes** [comment]
1 upvote, still not fixed I think

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering any of these issues, can we file separate issues for each item that needs to be addressed? That'll help make sure items get tackled and closed more expediently.
