### ISSUE TITLE
[mixed time-series] Secondary y-axis title is disguised/misplaced

### ISSUE THREAD

**Issue by rumbin** [apache/superset#18235]
The Mixed Time-Series chart type allows for configuring the title of the primary and the secondary y-axis.
However, while only the title of the primary axis is shown next to the axis, the title of the secondary one is placed at the upper end of the axis where it gets hidden by bar values and zoom controls.

#### How to reproduce the bug

1. Create a _mixed time-series_ chart
2. Configure axis titles for both y-axes
3. Check the Data Zoom checkbox

### Expected results

Both axes carry the titles as configured

### Actual results

Only the left/primary y-axis has a title shown at the center of the axis.  
The title of the right/secondary axis is misplaced at the end of the axis and thus overprinted/disquised by bar values and/or zoom controls.

#### Screenshots

![mixed_time-series_y2_title](https://user-images.githubusercontent.com/1220356/151826673-71b592fe-c29e-48cf-acc2-155942c2246f.gif)

### Environment

- browser type and version: Chrome  96.0.4664.93
- superset version: 1.4.0
- all other versions: as defined in Superset's Docker image
- Feature flags:

```
# stable:
      "THUMBNAILS": True,
      "SQLLAB_BACKEND_PERSISTENCE": True,
      "ENABLE_TEMPLATE_PROCESSING": True,
      "DASHBOARD_CROSS_FILTERS": True,

      # experimental:
      "ALERT_REPORTS": True,
      "ALERTS_ATTACH_REPORTS": True,
      "DASHBOARD_NATIVE_FILTERS": True,

      # unclassified:
      "ENABLE_EXPLORE_DRAG_AND_DROP": True,
      "ENABLE_DND_WITH_CLICK_UX": True,

      # development:
      "DASHBOARD_NATIVE_FILTERS_SET": True
```

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
Repro'd - I started working on a fix but I identified multiple inconsistencies in this area, so will need to circle back slightly later due to lack of time right now.

**Comment by rumbin** [comment]
This issue should not be closed by the stale bot, in my eyes.

**Comment by vaibhav-malpani** [comment]
Any updates on this?
We are using mixed-time series on our dashboard.. and this issue really does not look good.

**Comment by srikary12** [comment]
Can someone help me with the file.

**Comment by webobite** [comment]
Hi @rumbin / @srikary12 / @vaibhav-malpani  ,

**What should the expectation be? (Both axes carry the titles as configured)**
As per the control change for `Y-Axis Title Position,` The y-axis title should be displayed to the Left or top.
As I can see It has a single control for Primary Y Axis Title Position control.
something like this: - 
I made the change on my local was able to come up with these scenerios
Scenario 1 :
![image](https://github.com/apache/superset/assets/28811018/f55ee7f0-cb4a-476c-8101-4b378850103b)
Scenario 2: 
![image](https://github.com/apache/superset/assets/28811018/6b00d6cf-1928-4471-8a3d-32aad114757d)

**Comment by geido** [comment]
Fixed by https://github.com/apache-superset/superset-ui/pull/1351
