### ISSUE TITLE
Web UI doesn't show app version when deployed using Helm chart

### ISSUE THREAD

**Issue by manisha-tanwar** [apache/superset#18256]
#### How to reproduce the bug

1. Go to 'Deploy helm chart using https://github.com/apache/superset/tree/master/helm/superset'
2. Click on 'Setting'
3. Scroll down to 'About'
4. See error : Version as 0.0.0dev

### Expected results

App version should be v1.4.0/latest tag

### Actual results
App version shows v0.0.0dev

#### Screenshots

<img width="1440" alt="Screenshot 2022-02-02 at 14 03 05" src="https://user-images.githubusercontent.com/63790657/152168969-e2d914c5-20f1-404f-81e6-b44604b93c52.png">

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: `superset version` 

> Superset 0.0.0dev

- python version: `python --version` 

> Python 3.8.12

- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by S-eb** [comment]
Observing similar situation on our deployment

**Comment by manisha-tanwar** [comment]
Also if I use `apache/superset:1.4.0` instead of `apache/superset:latest`, Can't get it deployed and see errors like [https://github.com/apache/superset/issues/17712](https://github.com/apache/superset/issues/17712)

**Comment by manisha-tanwar** [comment]
Followed https://github.com/apache/superset/issues/18172 with some changes and it worked as a workaround until v1.4.1 is released.
