### ISSUE TITLE
Does SQLLab / Query Editor support Row Level Security?

### ISSUE THREAD

**Issue by srinisubramanian** [apache/superset#18595]
I created a datasource for a table and limited the data with RLS.  This works fine when I use the dataset to design the dashboard.

When I work with SQLLab (The query editor) and open the same table as in the dataset, the entire data set is now displayed.  The RLS does not seem to limit the data for SQLLab.  Is that how its expected to work or is this an issue to be resolved?

**Comment by srinify** [comment]
Hi there @srinisubramanian do you mind posting in the Superset Slack or over in Github discussions? We're hoping to keep Github Issues focused on bugs & issues :)
