### ISSUE TITLE
Date  Casting from timestamp[us] to timestamp[ns]

### ISSUE THREAD

**Issue by maduvnj** [apache/superset#18596]
When using Superset 1.3.0., and when querying oracle database with query SELECT to_date('9999-12-31','yyyy-MM-dd') from dual; we get 

**Casting from timestamp[us] to timestamp[ns] would result in out of bounds timestamp: 253402214400000000**

 It has to do with pandas dataframe and timestamp how can we change it. In previous releases of Superset we changed the source code to get rid of this error, but when getting new releases the error is here again.

Thanks,
Matej

**Comment by villebro** [comment]
Hi @maduvnj you need to provide some more information about how this is happening. Can you add at least what database this is happening on? (looks like Oracle?)

**Comment by maduvnj** [comment]
Yes we are connecting to Oracle database.
