### ISSUE TITLE
After DB migration and "Invalid decryption key" fix, correct schemas not displaying

### ISSUE THREAD

**Issue by alee68** [apache/superset#18602]
I have two Superset instances, Instance A on an EKS cluster, Instance B on a local Kind cluster. I've run a pg_dump on Instance A and restored the data to Instance B.

After hitting the "Invalid decryption key" error, I used [these steps to resolve it](https://github.com/apache/superset/issues/8538#issuecomment-922061313); however, I am facing some additional issues.

^ To quickly summarize the above steps, I'm:
1) Creating new DBs via the Superset web UI (I named them "newdb_Dev" and "newdb_Prod")
2) Migrating existing DBs' (let's call them "originaldb_Dev" and "originaldb_Prod") data to newdb_Dev and newdb_Prod
3) Deleting originaldb_Dev and originaldb_Prod
4) Renaming newdb_Dev, newdb_Prod to originaldb_Dev, originaldb_Prod

While these steps resolve the "Invalid decryption key" error, the issue is, Superset seems to still point at the "newdb_Dev" and "newdb_Prod" entries, so I cannot access the schema I need (which are under "originaldb_Dev" and "originaldb_Prod" now.

If you look at this comparison, I have Instance A's ab_view_menu table (LEFT), and Instance B's. You can see Instance B's ab_view_menu table still contains references to "newdb_Dev" and "newdb_Prod", which are no longer needed and only contain the "information_schema" and "public" schemas.
![ab_view_menu comparison 3](https://user-images.githubusercontent.com/9437481/152824401-e5f12225-5d1c-422d-a583-44863bada43b.png)

Looking at both instances, if I try to add datasets, Instance A's SCHEMA dropdown shows the entire schema list (presumably populated from ab_view_menu), while Instance B's SCHEMA dropdown only shows "information_schema" and "public".
<img width="372" alt="schemascorrect" src="https://user-images.githubusercontent.com/9437481/152827002-3bca8080-5971-4190-939f-188a9ebfebec.png">
<img width="378" alt="schemasincorrect" src="https://user-images.githubusercontent.com/9437481/152827012-7b188821-510c-485d-8db6-8d73aa399af1.png">

How can I have Instance B's SCHEMA dropdown display the correct values?

#### How to reproduce the bug

1) pg_dump (as plain text file) of Instance A
2) psql restore of dump file to Instance B
3) [Go through these steps](https://github.com/apache/superset/issues/8538#issuecomment-922061313) to fix "Invalid decryption key" error
4) In Instance B's web UI, attempt to add dataset; SCHEMA dropdown will be incorrect

### Expected results

I expected to see the correct, full SCHEMA dropdown when adding a dataset in Instance B. I am assuming this dropdown gets populated from the ab_view_menu table.

### Actual results

Instance B's SCHEMA dropdown only displays "information_schema" and "public".

### Environment

- browser type and version: Edge 98.0.1108.43 (Official build) (x86_64), Firefox 96.0.3 (64-bit), Chrome 98.0.4758.80 (Official Build) (x86_64)
- superset version:  Superset 0.0.0dev
- python version: Python 3.8.12
- node.js version: n/a

### Checklist

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by alee68** [comment]
A related question is simply, where is the SCHEMA dropdown list (when adding a new dataset) populated from? I assumed from ab_view_menu, but I was able to remove the extra rows (see above screenshots of ab_view_menu; I got my table down to 258 rows, with only 257 | DashboardFilterStateRestApi, 258 | ExploreFormDataRestApi as the last two). Yet, the SCHEMA dropdowns are still only showing "information_schema" and "public".

**Comment by rusackas** [comment]
@alee68 sorry this issue seemed to fall through the cracks for so long... are you still experiencing this, or did you find some form of a workaround? I'm also curious if this is an issue at all in newer versions of Superset, e.g. 2.0.1. Let me know if we can close this, or if it should remain open. Thanks!

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
