### ISSUE TITLE
Can't use property ingressClassName in Helm Chart value file from 0.5.5 to 0.5.6

### ISSUE THREAD

**Issue by joatkh** [apache/superset#18617]
Can't use property ingressClassName in Helm Chart value file from 0.5.5 to 0.5.6

#### How to reproduce the bug

Deploy Helm chart 0.5.5 or 0.5.6 using values:
```
ingress:
  enabled: true
  ingressClassName: nginx
```

### Expected results

Superset deployed and accessible through the ingress

### Actual results

Missing property ingressClassName in the Helm chart values [schema](https://github.com/apache/superset/blob/1fbdabd2cf88ce4da0b99897ce00afd03ae47d27/helm/superset/values.schema.json#L136) 

#### Screenshots

![image](https://user-images.githubusercontent.com/92088801/152966972-d56617da-c5f9-4c28-b9c7-df24a9c619e2.png)

**Comment by ad-m** [comment]
@joatkh that validation was introduced in #18161. It looks like we miss some fields. Could you try associated PR?

**Comment by ad-m** [comment]
@joatkh could you confirm that the issue was fixed by #18619?

**Comment by rusackas** [comment]
Sounds like potentially _multiple_ fixes were merged for this, and this has gone quiet for almost a year.. Closing (perhaps optimistically) as resolved, but happy to revisit/reopen if needed.
