### ISSUE TITLE
Superset not able to connect to Spark thrift server even though Spark is showing a connection was established

### ISSUE THREAD

**Issue by raefezzeldin** [apache/superset#18627]
I am deploying Apache Superset on Azure Kubernetes Cluster, and Trying to connect Spark thrift server deployed on the same cluster. when creating database it waits for 60 secs then 504 Gateway timeout appears. However from Spark I can see that there is a connection establlished and two statements was sent :
1- use 'default'
2- Select 1

#### How to reproduce the bug

1. Go to 'Databases'
2. Click on 'Create new Database'
3. Scroll down to 'Apache Spark SQL'

### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `latest'
- helm chart 0.5.7

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by srinify** [comment]
Hi @raefezzeldin I would strongly encourage adding significantly more context so someone in the community can try to help you out. Right now, it's difficult for anyone to help or attempt to replicate the issue unfortunately. Things that help:

- Backend error logs
- Simple diagram of your network architecture

**Comment by rusackas** [comment]
Closing as "won't fix" since there has been no additional context added in approximately a year.
