### ISSUE TITLE
NameError: name 'OIDCSecurityManager' is not defined

### ISSUE THREAD

**Issue by shashi5678** [apache/superset#18625]
I tried to configuring superset and keycloak in SSO using opencconect 
but always getting 

NameError: name 'OIDCSecurityManager' is not defined

### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by ad-m** [comment]
It sound like misconfiguration. Apache Superset does not have any references to `OIDCSecurityManager` ( https://github.com/apache/superset/search?q=OIDCSecurityManager ). Could you provide your config file and tutorial which you try to follow (if any)?

**Comment by PatBriPerso** [comment]
I try to configure superset to use keycloak as an IdP too.
I follow these posts:
- https://stackoverflow.com/questions/54010314/using-keycloakopenid-connect-with-apache-superset/54024394#54024394
- https://github.com/apache/superset/discussions/13915

Hope this helps.

My setup works well except when I try to access the users list (/users/list) as an Admin (unauthorized). I'll open a new issue for that.

**Comment by rusackas** [comment]
Sounds from the helpful comments here that this is most likely a non-issue after so long. If you're still facing this on Superset 2.0.x or on the `master` branch, holler, and we can revisit/reopen.

**Comment by rusackas** [comment]
This seems like the bug report template isn't filled out, the issue is stale, and it might be more of a configuration issue than a bug report in the first place. Does anyone see a valid reason to keep this open as a bug? This might otherwise be more appropriate in the #deploying-superset channel on Slack or as a Github Q&A discussion.
