### ISSUE TITLE
Can't refresh dashboard with css in Win10

### ISSUE THREAD

**Issue by gndsnts** [apache/superset#18623]
Hello, 

I hope some of you could help me to understand why, when I'm loading a dashboard for the first time page for the first, it will be load correctly, but when page is refreshed, I get an error and page don't load css.

This issue occours on Windows10 and with last version of superset.

I installed Virtual Box Machine with Ubuntu, to replicate this issue and it works just fine.

#### How to reproduce the bug

1. Get last version of superset 
2. Run in Windows 10
3. Create Dashboard for test (background blue on css)
4. Open Dashboard and Refresh Page

### Expected results

When dashboard page is refreshed, css load is required

### Actual results

After refresh page the css won't be loaded.

#### Screenshots
Loading the first time
![image](https://user-images.githubusercontent.com/78511708/153038841-2d0850b1-faca-4c50-84b4-674593f64104.png)

After refresh:
![image](https://user-images.githubusercontent.com/78511708/153038974-6ebffb81-ba69-4a44-a682-6bc221645b59.png)

Error
![image](https://user-images.githubusercontent.com/78511708/153039591-5513fdaa-1143-42ae-9fd6-799666b4ca64.png)

### Environment

(please complete the following information):

- Windows 10
- superset version: `latest `
- Docker Desktop
- Chrome - localhost:8080

if any one can help me, I would appreciate it

Best regards

**Comment by rusackas** [comment]
@andrey-zayats took a look at this and was unable to reproduce the issue. I'm going to go ahead and remove the `validation:required` label and close the issue. If anyone sees this happening in Superset 2.0.x or later, or on `master`, we're open to revisiting this conversation, re-opening the ticket, or triaging a new Issue with updated context. Thank you!
