### ISSUE TITLE
Add proper selection and clipboard behaviour to SQL Lab results grid.

### ISSUE THREAD

**Issue by MBRGA** [apache/superset#18636]
**Is your feature request related to a problem? Please describe.**
It is really painful to get results out of Superset's Results Grid. We should be able to select cells, and copy results with keyboard shortcuts as in any other database query tool.
Also, current Clipboard button doesn't seem to output line separators that work on Windows - have to copy the results into another tool to fix them before using them in anything else.

**Describe the solution you'd like**
Use something like react-grid to render query results. Common keyboard shortcuts in other programs are Ctrl-C to copy selected cells without headers, and Ctrl-Insert to copy with them.

**Describe alternatives you've considered**
At least improve current Clipboard button behaviour

**Additional context**
This is also referenced in the discussion below:

I second the part about making the results grid interactive. Being able to drag to select individual cells/rows/columns and pressing Ctrl-C to copy to clipboard (some software uses Ctrl+Insert is used to include headers) is a standard database query tool feature and would be so much more efficient than having to copy the whole results set to the clipboard.

_Originally posted by @MBRGA in https://github.com/apache/superset/discussions/18541#discussioncomment-2139880_

**Comment by rusackas** [comment]
@MBRGA I see this feature request hasn't gotten much attention in upwards of a year. I'm going to close it as stale, but if you're still pursuing this, I urge you to ping me here and/or propose it in a Issues thread on Github Discussions, which is where we're directing feature requests these days. Thank you!

**Comment by MBRGA** [comment]
@rusackas well I definitely still think it's something that many users would find valuable.

**Comment by rusackas** [comment]
Fair enough... I'll convert this to an Ideas discussion.
