### ISSUE TITLE
Word Cloud not displaying in Superset 1.0

### ISSUE THREAD

**Issue by vksamu** [apache/superset#18630]
Hi, I am using latest version of apache-superset. I am trying to create word_cloud chart, the records are not displaying when I am inspecting the webpage it is showing font-size: 0px for all the records. Please refer to the attached screenshot. Thanks
<img width="1382" alt="Screenshot 2022-02-09 at 11 40 01 AM" src="https://user-images.githubusercontent.com/39452972/153132468-b2f4f2a8-2507-4f3b-9b0a-bc3f951a0b3f.png">

**Comment by srinify** [comment]
Hi there @vksamu 2 things:

- Can you share some sample data (you can anonymize it) + the query that's generated + the database you're using? So we can rule out any issues with the data itself vs Superset (unlikely to be the issue but still)
- Are you able to replicate this issue in Superset v1.4? Superset v1.0 is quite old at this point and the issue may have already been fixed

**Comment by rusackas** [comment]
Since there's no response on the thread, and we're now only supporting 1.5/2.0 (which seems to work!), I'll close this one out as resolved.
