### ISSUE TITLE
No Results - Cache Issue: Force refresh several times

### ISSUE THREAD

**Issue by OlafKocanda** [apache/superset#18639]
### Bug
In our superset the configured cache does not seem to work right. While loading a dashboard (or in browser refreshing with ctrl + r) sometimes leads to missing data in some charts with the error message: 

`No Results
No results were returned for this query. If you expected results to be returned, ensure any filters are configured properly and the datasource contains data for the selected time range.`

#### How to reproduce the bug
We have the following cache settings with a redis deployed

```
CACHE_CONFIG = {
      'CACHE_TYPE': 'redis',
      'CACHE_DEFAULT_TIMEOUT': 300,
      'CACHE_KEY_PREFIX': 'superset_results',
      'CACHE_REDIS_HOST': env('REDIS_HOST'),
      'CACHE_REDIS_PORT': env('REDIS_PORT'),
      'CACHE_REDIS_PASSWORD': env('REDIS_PASSWORD'),
      'CACHE_REDIS_DB': env('REDIS_DB', 1),
}
DATA_CACHE_CONFIG = CACHE_CONFIG


RESULTS_BACKEND = RedisCache(
      host=env('REDIS_HOST'),
      port=env('REDIS_PORT'),
      password=env('REDIS_PASSWORD'),
      key_prefix='superset_results'
)

```

### Expected results

Superset charts are always returning data.

### Actual results

Only sometimes the charts are returning data. Force refreshing the chart for several times leads to the charts showing data eventually.

#### Screenshots

Sometimes "Force refresh" works instantly (see gif below)
![Force refresh](https://user-images.githubusercontent.com/58265203/153176498-55a7e9a9-ae3c-49bb-bff4-b933a749fc3a.gif)

Sometimes "Force refresh does not work for several times (up to 5-10 times) until data is returned in the charts.
The network monitor of firefox does not seem to distinguish between the situation when data is returned or not (see picture below). 
![Network Monitor in Firefox](https://user-images.githubusercontent.com/58265203/153176926-9c7cd630-e05c-47cf-8b22-16acd195a100.png)

Already tried different browser (chrome Version 96.0.4664.45 (64-bit) and firefox 96.0.3 (64-bit) ) with both leading to similar results.

Interestingly in my search with the google chrome network monitor, I found that it seems like actually no data is returned:
![image](https://user-images.githubusercontent.com/58265203/153180154-58d99951-eb0a-40c1-8040-092315750087.png)
![image](https://user-images.githubusercontent.com/58265203/153179844-c47b8eeb-f00c-401d-b77e-66900ffefd72.png)

### Logs

The following logs are coming back when force refreshing the chart. Here the data appears after the third refresh (third block). Though it does not seem that it is visible in the logs whether data comes back or not:
```
2022-02-09 10:39:45,937:DEBUG:parsedatetime:eval - with context - False, False
Cache key: 99de8cd44f9823c1f5045776491405f3
2022-02-09 10:39:45,946:INFO:superset.viz:Cache key: 99de8cd44f9823c1f5045776491405f3
57.20.4.138 - - [09/Feb/2022:10:39:46 +0000] "POST /superset/explore_json/?form_data=%7B%22slice_id%22%3A70%7D&force=true&dashboard_id=17 HTTP/1.1" 200 2030 "https://<SUPERSET-URL>/superset/dashboard/17/?native_filters=%28%29" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"
57.20.4.138 - - [09/Feb/2022:10:39:47 +0000] "POST /superset/log/?explode=events&dashboard_id=17 HTTP/1.1" 200 1 "https://<SUPERSET-URL>/superset/dashboard/17/?native_filters=%28%29" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"

2022-02-09 10:39:50,740:DEBUG:parsedatetime:eval - with context - False, False
Cache key: 99de8cd44f9823c1f5045776491405f3
2022-02-09 10:39:50,749:INFO:superset.viz:Cache key: 99de8cd44f9823c1f5045776491405f3
57.20.4.138 - - [09/Feb/2022:10:39:51 +0000] "POST /superset/explore_json/?form_data=%7B%22slice_id%22%3A70%7D&force=true&dashboard_id=17 HTTP/1.1" 200 2030 "https://<SUPERSET-URL>/superset/dashboard/17/?native_filters=%28%29" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"
57.20.4.138 - - [09/Feb/2022:10:39:52 +0000] "POST /superset/log/?explode=events&dashboard_id=17 HTTP/1.1" 200 1 "https://<SUPERSET-URL>/superset/dashboard/17/?native_filters=%28%29" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"

2022-02-09 10:39:54,067:DEBUG:parsedatetime:eval - with context - False, False
Cache key: 99de8cd44f9823c1f5045776491405f3
2022-02-09 10:39:54,076:INFO:superset.viz:Cache key: 99de8cd44f9823c1f5045776491405f3
57.20.4.138 - - [09/Feb/2022:10:39:54 +0000] "POST /superset/explore_json/?form_data=%7B%22slice_id%22%3A70%7D&force=true&dashboard_id=17 HTTP/1.1" 200 2129 "https://<SUPERSET-URL>/superset/dashboard/17/?native_filters=%28%29" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"
57.20.4.138 - - [09/Feb/2022:10:39:55 +0000] "POST /superset/log/?explode=events&dashboard_id=17 HTTP/1.1" 200 1 "https://<SUPERSET-URL>/superset/dashboard/17/?native_filters=%28%29" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"

```

### Environment

(please complete the following information):

- browser type and version: `chrome Version 96.0.4664.45 (64-bit) and firefox 96.0.3 (64-bit)` 
- superset version: `Superset 1.3.2`
- python version: `Python 3.7.9`
- node.js version: `N/A`
- any feature flags active:
```
FEATURE_FLAGS = {
    "ALERT_REPORTS": True,
    "DASHBOARD_NATIVE_FILTERS": True,
    "DASHBOARD_CROSS_FILTERS": True,
    "ENABLE_TEMPLATE_PROCESSING": True,
    "ENABLE_SCHEDULED_EMAIL_REPORTS": True,
    "EMAIL_NOTIFICATIONS": True
}
``` 

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by shal-kumari** [comment]
I'm facing the exact same issue. No Results in maximum refreshes. Cache seems to be empty alot of times.

**Comment by villebro** [comment]
@shal-kumari what version of Superset are you running?

**Comment by rusackas** [comment]
@OlafKocanda Just checking in on this issue. I _really_ appreciate the detailed issue you've filed! That said, it's been open a long time, and I'm wondering if you still face this, or found a solution/workaround. I'm hoping this is no longer an issue with 2.0.1, but wondering if you or @shal-kumari can validate if the issue remains.

**Comment by OlafKocanda** [comment]
@rusackas 
Sorry for the late reply. I am not working for the company and on this topic anymore. I have forwarded the topic to my successor and waiting for a reply.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!

**Comment by vioao** [comment]
Get the same problem in version 4.0.2
