### ISSUE TITLE
Time-Series Table results not sorting correctly

### ISSUE THREAD

**Issue by michellethomas** [apache/superset#18646]
Columns in the Time-Series Table are not sorting correctly if results have N/A values. 

#### How to reproduce the bug

1. Create a time series table chart
2. Add a metric, a group by, and a simple time series column (like time comparison with actual values)
3. Make sure some of the group by results don't have values resulting in N/As in the time series column
4. Sort using the arrows near the column title

### Expected results

Results are sorted correctly

### Actual results

![image](https://user-images.githubusercontent.com/817955/153259141-e3bd6e75-7545-4b98-bed9-0708756ba167.png)

### Environment

(please complete the following information):

- browser type and version:
- superset version: near master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by ShaliniIruvuru** [comment]
This is not a bug.Working as Expected. When select results having N/A values.

Screenshot:-

1.When update a chart
![image](https://user-images.githubusercontent.com/115684419/227455141-5cd0463e-bb78-4d0c-a740-fa55c58d2d56.png)
2.When click on sorted up arrow from Time-sries column ,it is sorting.

![image](https://user-images.githubusercontent.com/115684419/227455225-15a65682-d47c-480f-b333-372218af3f0a.png)
3.without selecting arrows

![image](https://user-images.githubusercontent.com/115684419/227455289-4ffd1937-ee91-4898-9e71-7185fd5ce429.png)
Loom video:-

https://www.loom.com/share/11d8e84b81624ee890f8e7606323ac2b

**Comment by rusackas** [comment]
Sounds like this is fixed.... closing! Happy to review a new Issue if there are related bugs in 3.x or greater.

**Comment by gcleaves** [comment]
I don't think this is working, the sorting makes no sense. It only sorts alphabetically by the dimension.
