### ISSUE TITLE
[Helm Chart] Wrong filename for import_dashboards in documentation and values.yaml

### ISSUE THREAD

**Issue by wiktor2200** [apache/superset#18641]
## Description
There is wrong filename mentioned in documentation for helm chart deployment.
`datasources_init.yaml` instead of `import_datasources.yaml` which is actually loaded in: https://github.com/apache/superset/blob/62009773a63b9a149b259135d762102aedaae2b3/helm/superset/values.yaml#L346

## Fix
I've fixed it in # so please review.

**Comment by ad-m** [comment]
@wiktor2200 could you confirm that the issue was fixed?

**Comment by wiktor2200** [comment]
Yes, it was fixed in #18668 i commit: https://github.com/apache/superset/pull/18642/commits/a72fc7131c7be4dbf728e89afb1e04587f459f3a
So I'm closing it, thanks for reminder.
