### ISSUE TITLE
Dataset modal doesn't work correctly in dev server mode

### ISSUE THREAD

**Issue by villebro** [apache/superset#18655]
When running Superset in dev server mode (`npm run dev-server`), the dataset edit modal doesn't work properly. For instance, when I add a label to a column and save, the updated value isn't persisted in the dataset metadata. See the screen recording below:

https://user-images.githubusercontent.com/33317356/153366245-f733f6b6-c7c1-4322-b16a-91eb1d156b1c.mp4

However, when running a production build (`npm run build`), the modal works correctly:

https://user-images.githubusercontent.com/33317356/153366827-204f7a14-73ec-4153-a071-afe68b68112b.mp4

#### How to reproduce the bug

1. Go to Dataset list view and edit your favourite dataset
2. Click on Columns and add a label to a column
3. Save and reopen the dataset Column view
4. Notice that the updated column label is no longer present on dev server mode, but works correctly on the prod build

### Expected results

Dataset should update correctly in both `dev-server` and `build` mode

### Actual results

Dataset doesn't update correctly in `dev-server` mode

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zhaoyongjie** [comment]
closed by [PR](https://github.com/apache/superset/pull/18658)
