### ISSUE TITLE
Import database also imports 'examples' database

### ISSUE THREAD

**Issue by MarcinZegar** [apache/superset#18667]
When importing a database through the UI or API, an 'examples' database connection is also created which contains sensitive information. There was no examples.yaml file in the dashbaord zip.

![superset_bug](https://user-images.githubusercontent.com/11165176/153490851-b77313fd-12dd-42c6-afc3-5f9ac76fd7e2.gif)

#### How to reproduce the bug

1. Create a database connection in Superset (I used https://rnacentral.org/help/public-database) 
2. Add a dataset to this databse
2. Export Database
3. Import Database

### Expected results

Onle the Postgres Database is created

### Actual results

Postgres and Examples Databases are created

#### Screenshots

![superset_bug](https://user-images.githubusercontent.com/11165176/153490851-b77313fd-12dd-42c6-afc3-5f9ac76fd7e2.gif)

### Environment

- browser type and version: Firefox  97.0
- superset version: `1.3.2`
- python version: `3.7.9`
- node.js version: N/A
- any feature flags active:
`VERSION_EXPORT  = True`
`SUPERSET_LOAD_EXAMPLES` is not in .env file

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by logicwic** [comment]
Hi is there documentation on how to import dataset or database through API.
Or can you provide an example python file please?

**Comment by MarcinZegar** [comment]
> Hi is there documentation on how to import dataset or database through API. Or can you provide an example python file please?

Look into the API documentation for superset: https://superset.apache.org/docs/api/

**Comment by discointheair** [comment]
Any new findings here? 
I can reproduce this and for me its a security issue and not just a bug. 
The connection is created with the superset init credentials to its config DB. Therefore all superset users can "work" on it. 
Also an existing connection named "examples" will be just overwritten without any feedback before.

**Comment by MarcinZegar** [comment]
@discointheair I have not seen a fix for this issue. As a work around, in our import scripts, we have a function which checks to see if the examples data base exists and then deletes it. Not ideal but it works

**Comment by discointheair** [comment]
@MarcinZegar 
Thank you. Good Idea. Will think about it.
So you use the API to delete the connection? https://superset.apache.org/docs/api/

I hope we update to 2.0.0 this year. Will also check this issue within the preparation.

**Comment by MarcinZegar** [comment]
> @MarcinZegar Thank you. Good Idea. Will think about it. So you use the API to delete the connection? https://superset.apache.org/docs/api/

Exactly. We use the API to import databases and as part of that script we also check the existence of the examples database and delete it when appropriate.
