### ISSUE TITLE
Superset only shows the header row

### ISSUE THREAD

**Issue by mapshen** [apache/superset#18680]
When we run queries in the 'SQL Editor', sometimes only the header row shows up whereas the real data are not. However, once you open up the “Developer tools”, the full results would appear right away

#### How to reproduce the bug

1. Go to 'SQL Editor'
2. Run queries from time to time
3. See error under the "RESULTS" tab

### Expected results

All returned rows show up.

### Actual results

Only the header row shows up

![image](https://user-images.githubusercontent.com/7225879/153630362-2fb3d026-0cbf-450f-909b-79a2a7b68c47.png)

### Environment

- browser type and version: Chrome Version 97.0.4682.71
- superset/python/node.js version:  [apache/superset:1.4.1](https://hub.docker.com/layers/apache/superset/1.4.1/images/sha256-5e1e0f0cc5ba4a6a955219f5655c110d67b5220df09977374f06809792ef231a?context=explore)

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zhaoyongjie** [comment]
Hi @mapshen, What do you use DB engine and SQLAlchemy driver?

**Comment by mapshen** [comment]
@zhaoyongjie we use sqlalchemy-trino==0.4.1

**Comment by rusackas** [comment]
Hi @mapshen - thanks for the report. I was unable to repro this issue... have you seen it in recent versions? I know we have a lot of folks out there using Trino, so I'm hopeful that this was a fluke. If you still see a problem, I'm happy to re-open this issue and dig further!
