### ISSUE TITLE
Saving a copy of Dashboard is broken

### ISSUE THREAD

**Issue by LalaGabor** [apache/superset#18718]
## Screenshot

<img width="959" alt="should be" src="https://user-images.githubusercontent.com/44199231/153891745-588fa9e2-3906-45f4-b4a0-9da8db5ea84b.png">

<img width="958" alt="actual" src="https://user-images.githubusercontent.com/44199231/153891706-cfe95d8d-9c73-4c22-b133-286d38bf732b.png">

When saving a copy of a dashboard, the copy does not apply the same layout as in the original dashboard

Firefox, Superset version 1.4, no CSS applied

**Comment by zhaoyongjie** [comment]
Hi @LalaGabor, I'm unable to reproduce this on the master branch.
- latest master branch
- latest Firefox

https://user-images.githubusercontent.com/2016594/154204634-d1f83afc-8742-4ee9-a140-37d57c15fe9d.mov

**Comment by rusackas** [comment]
Sounds like this is resolved. If anyone sees this error occoring, let's re-open!
