### ISSUE TITLE
cannot connect to Mysql Database when DATABASE NAME contains @

### ISSUE THREAD

**Issue by alan345** [apache/superset#18719]
cannot connect to Mysql Database when DATABASE NAME contains `@` (at sign)

When you create a new database: 
databaseview => + Database

### Expected results

Connect successfully to the databse

### Actual results

I got his error `Unknown MySQL server host "prod".` on the field `HOST`
If I remove the `@` just to check the behavior, the error is now legit on the field `DATABASE NAME` as this database name doesn't exist.
The database is called `nacho@prod`

#### Screenshots

<img width="501" alt="image" src="https://user-images.githubusercontent.com/15246526/153905773-b0651860-423b-4190-8352-eac525367016.png">
<img width="501" alt="image" src="https://user-images.githubusercontent.com/15246526/153905829-c6c3f6cd-2bba-4fde-b057-50a2092385cc.png">

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: 0.5.8

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ X] I have reproduced the issue with at least the latest released version of superset.
- [ X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by minho95** [comment]
Can I ask what is the version of the MySQL server? I am trying to reproduce it, but during the creation of the database with a name containing '@' I get the error: 
`ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '@name' at line 1`

**Comment by zhaoyongjie** [comment]
Hi @alan345 @minho95, I have validated on the master branch and MySQL 5.7.
1. login MySQL
2. create database from MySQL cli
```
mysql> create database `foo@bar`;
Query OK, 1 row affected (0.00 sec)

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| foo@bar            |
| infodumps          |
| mysql              |
| performance_schema |
| sample_data        |
| sampling           |
| sys                |
+--------------------+
8 rows in set (0.00 sec)

mysql>
```

3. can't sent testing query for `foo@bar`
<img width="558" alt="image" src="https://user-images.githubusercontent.com/2016594/154043396-dca0e7a1-90d5-4b8a-bc59-09f3aac2a0f8.png">

**Comment by villebro** [comment]
While in general I would not encourage using these types of characters in a database name, I believe this should be fairly easy to fix by making sure we urlencode the database name when constructing the SQLAlchemy URI.

**Comment by rusackas** [comment]
I'm assuming this is still an issue in Superset 2.x.x, but can anyone confirm or deny that?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
