### ISSUE TITLE
The order by does not work well - Bar graph

### ISSUE THREAD

**Issue by Uria55** [apache/superset#18713]
I want to sort the values by column names 'value_overrides_ration'.
The superset thinks it's a string, but it's actually a number.

The data view is good but the bar graph doesn't work.

### Expected results
I expected the graph will perform as a table date

### Actual results
The data in the table show but in graph does not.

#### Screenshots
![image](https://user-images.githubusercontent.com/99117138/153866327-7a13c7bc-b0c4-4d22-a75a-4525fd9b8a48.png)

### Environment
- browser type and version:
- Chromium: Version 98.0.4758.80 (Official Build) snap (64-bit)

**Comment by zhaoyongjie** [comment]
Hi @Uria55, Bar Chart will be deprecated in the Superset community. There is a new Bar Chart released, please try the new one, feel free to file an issue if you have any questions about the new chart.

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/2016594/154209537-68f43853-e638-4444-8a57-fe0c2b7bc4aa.png">

**Comment by Uria55** [comment]
Thank you.
I will try.

**Comment by rusackas** [comment]
This issue has been resolved on `master` quite some time ago. If you find any issue with 2.0 or the current `master` branch, holler, and we can re-open this!
