### ISSUE TITLE
'Total' contribution mode for time series chart doesnt work

### ISSUE THREAD

**Issue by alexamy** [apache/superset#18774]
When using 'Total' from 'contribution mode' there is no data.

#### How to reproduce the bug

1. Create new time series chart 
2. Add metrics / group by clause
3. Set 'contribution mode' to 'total'
4. See no data

### Expected results

Expect to see accumulated data chart.

### Actual results

No data presented on the chart.

#### Screenshots

![image](https://user-images.githubusercontent.com/596195/154384939-5d48f851-153b-4543-b844-9c9c09fbfe57.png)

Relates to #11792, I've tried to repeat steps in [this video](https://github.com/apache/superset/issues/11792#issuecomment-800051008), and got different results. [My attempt](https://user-images.githubusercontent.com/596195/154355807-1ca34b3e-455d-4a0f-aff9-18b28aeebba0.mp4).

### Environment

- browser version: Google Chrome 98.0.4758.102 

I'm using superset in container from this docker image: 
`docker pull apache/superset:993278d8ad2d9be90c5484e3cfe61936c22b850d`

These commands were runned in the container:
- superset version: Superset 0.0.0dev
- python version: Python 3.8.12
- node.js version: (no executable found in $PATH in container)
- any feature flags active: PREVENT_UNSAFE_DB_CONNECTIONS = False

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by alexamy** [comment]
@zhaoyongjie Have you tried to repeat case with `birth_names` chart, as in video?  
I'm using last version from master and run it with `docker compose`, but have empty results again.

**Comment by zhaoyongjie** [comment]
Hey @alexamy, It works in my local environment(latest master branch). BTW, do you get **Contribution mode** selection change?

<img width="1522" alt="image" src="https://user-images.githubusercontent.com/2016594/154718337-88ec6b90-151b-46f7-bded-8105930651f2.png">

<img width="513" alt="image" src="https://user-images.githubusercontent.com/2016594/154718399-f875e722-5b78-493c-acfa-287317748c3d.png">

**Comment by jaimefr** [comment]
@alexamy @zhaoyongjie this is a bug from version 1.4.1 that will be resolved in the next release? I am facing the same issue and I don't even have the Contribution mode = Row option

**Comment by alexamy** [comment]
@jaimefr Hi! I'm using docker compose for local installation, installation guide: https://superset.apache.org/docs/installation/installing-superset-using-docker-compose/.
You need to pull latest docker images with command `docker-compose -f docker-compose-non-dev.yml pull`. 

I saw updated version of contibution mode after perfoming these steps.

**Comment by jaimefr** [comment]
@alexamy @zhaoyongjie I have upgraded to Superset 1.4.2 and this still doesn't work. Do you have if the fix has been excluded of the release?

**Comment by zhaoyongjie** [comment]
> @alexamy @zhaoyongjie I have upgraded to Superset 1.4.2 and this still doesn't work. Do you have if the fix has been excluded of the release?

Do you try the master branch? I think this issue has been fixed in the latest master but not been released yet.

**Comment by villebro** [comment]
@jaimefr @alexamy: @zhaoyongjie is right - the 1.4 branch is unfortunately so old that these recent PRs weren't possible to cherry into 1.4.2. Having said that 1.5.0 is currently in the works, and the first release candidate should be made available this week.

**Comment by jaimefr** [comment]
@villebro  thanks, so we can expect this to be solved in 1.5
@zhaoyongjie no, we haven't tried, we only deploy official releases
