### ISSUE TITLE
cannot view Dashboards or Charts After Overriding SECRET_KEY with new value.

### ISSUE THREAD

**Issue by aryeh98** [apache/superset#18785]
After updating my SECRET_KEY value and changing it from its default value,When I try to navigate to see the a dashboard or a chart,I get an error. It seems like superset isnt fetching any of the data

#### How to reproduce the bug
1)Update SECRET_KEY value
2) Run superset in DEV mode

### Expected results

Superset will fetch all the charts and dashboards, and Once I click on one of the dashboards or charts ,It will route me to them

### Actual results

When I click on a dashboard, it routes me to the dashboard page but it just shows an error message: ***Unexpected error***
When I click on a chart it takes me to a blank page with an error message:
```
{"errors": [{"message": "(sqlite3.OperationalError) no such column: slices.is_managed_externally\n[SQL: SELECT slices.uuid AS slices_uuid, slices.created_on AS slices_created_on, slices.changed_on AS slices_changed_on, slices.id AS slices_id, slices.slice_name AS slices_slice_name, slices.datasource_id AS slices_datasource_id, slices.datasource_type AS slices_datasource_type, slices.datasource_name AS slices_datasource_name, slices.viz_type AS slices_viz_type, slices.params AS slices_params, slices.query_context AS slices_query_context, slices.description AS slices_description, slices.cache_timeout AS slices_cache_timeout, slices.perm AS slices_perm, slices.schema_perm AS slices_schema_perm, slices.last_saved_at AS slices_last_saved_at, slices.last_saved_by_fk AS slices_last_saved_by_fk, slices.certified_by AS slices_certified_by, slices.certification_details AS slices_certification_details, slices.is_managed_externally AS slices_is_managed_externally, slices.external_url AS slices_external_url, slices.created_by_fk AS slices_created_by_fk, slices.changed_by_fk AS slices_changed_by_fk \nFROM slices \nWHERE slices.id = ?]\n[parameters: (130,)]\n(Background on this error at: http://sqlalche.me/e/13/e3q8)", "error_type": "GENERIC_BACKEND_ERROR", "level": "error", "extra": {"issue_codes": [{"code": 1011, "message": "Issue 1011 - Superset encountered an unexpected error."}]}}]}
```

#### Screenshots

![superset-error-1](https://user-images.githubusercontent.com/73904529/154503168-15ac250b-60bd-4615-a47f-1fb35928c9f6.png)

![superset-error-2](https://user-images.githubusercontent.com/73904529/154503199-ef6952de-3816-4621-ab6c-69ece2019d8e.png)

### Environment

(please complete the following information):

- browser type and version:
- superset version: `Superset 0.0.0dev`
- python version: `Python 3.8.10`
- node.js version: `v16.13.1`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
Did you migrate the `SECRET_KEY` as instructed in `UPDATING.md` as per #17984?

> Default Flask SECRET_KEY has changed for security reasons. You should always override with your own secret. Set PREVIOUS_SECRET_KEY (ex: `PREVIOUS_SECRET_KEY = "\2\1thisismyscretkey\1\2\e\y\y\h"`) with your previous key and use superset re-encrypt-secrets to rotate you current secrets

In other words, adding this to your `superset_config.py:

```python
PREVIOUS_SECRET_KEY = "\2\1thisismyscretkey\1\2\e\y\y\h"
SECRET_KEY = "<my new secret key>"
```

and then running `superset re-encrypt-secrets`?
