### ISSUE TITLE
Dremio Datasets with point (.) in Folder / Schema cannot be queried

### ISSUE THREAD

**Issue by c-thiel** [apache/superset#18783]
In Dremio Folders created in "Spaces" cannot contain points. However in S3 or in other **physical** locations, this is possible. In such a case while we can query the dataset with dremio without problems, Superset breaks.

#### How to reproduce the bug
1. Create Dremio Data Lake Data Source
2. Add some Data at a location with a folder in between which has a point (.) in it's name - i.e. foo/bar/my.folder/my_dataset/parquet_0.parquet
3. Cast the Dataset in Dremio
4. Add the Dremio Datasource in Superset
5. Add the Table as a Dataset - the Schema is correctly identified.
6. Create a Dasbhoard from it and see it fail.
7. Check dremio and see that instead of doing something like: `Select * from "foo"."bar"."my.folder"."my_dataset"` this arrives: `Select * from "foo"."bar"."my"."folder"."my_dataset"` - note the differnce in my folder. Apparently superset makes the assumption that folder names cannot contain points and splits the folder name up into a wrong schema.

### Expected results
The query runs without error.

### Actual results
Superset issues a wrong query and Dremio returns an "Object not found" Error.

### Environment

(please complete the following information):

- browser type and version: Any
- superset version: Dockertag: 8b0634c9edb2919a9e4d03ae81c700368ac0e371 (A pretty recent master commit from a week ago)

**Comment by villebro** [comment]
Thanks for reporting @c-thiel. This appears to be a problem with the Dremio SQLAlchemy dialect; adding a table called `abc.def` to Sqlite renders the schema + table name correctly: 
![image](https://user-images.githubusercontent.com/33317356/155113000-63fcb220-35a2-401b-be1c-13f688e490bc.png)

Which connector are you using to connect to Dremio?

**Comment by c-thiel** [comment]
We are using the default dremio (ODBC) one. Flight is not working for us unfortunately because we are using oAuth and Bearer Tokens seem to be not supported yet by the dialect.

**Comment by jduo** [comment]
@

> Thanks for reporting @c-thiel. This appears to be a problem with the Dremio SQLAlchemy dialect; adding a table called `abc.def` to Sqlite renders the schema + table name correctly: ![image](https://user-images.githubusercontent.com/33317356/155113000-63fcb220-35a2-401b-be1c-13f688e490bc.png)
> 
> Which connector are you using to connect to Dremio?

@villebro , in the SQLite example above, the table name has a period, but @c-thiel's example shows a schema with a period in it that incorrectly gets split into sub-components.

Is there a way to get Superset to treat a schema returned by get_schema_names() as a single name vs. a series of name components?

From the SQLAlchemy connector perspective, each schema name returned by get_schema_names() is just one string and it is ambiguous if a period means it's a multi-part name vs. a single name that has periods in it.

**Comment by villebro** [comment]
@jduo we did a lot of work with @cgivre a few years ago to make similarly named schemas and tables work. I'm pretty sure we can leverage the same code to make this work, too. I'll assign this to myself and try to take a look in the coming week. If I forget, please feel free to ping me, maybe even on Slack, as this may require some sync collaboration.

**Comment by rusackas** [comment]
Is anyone still facing this, or shall we close it out as stale?

**Comment by rusackas** [comment]
Closing this out as stale, but throwing out one last comment to @dosu-bot in case it has any insight of what to change here. Happy to revisit/reopen this if anyone is planning to tackle the issue.
