### ISSUE TITLE
Unable to import Dashboards since Version 1.3

### ISSUE THREAD

**Issue by LalaGabor** [apache/superset#18816]
Since we upgraded to version 1.3 of Superset, we have not been able to import Dashboards, where the datasource already exists (of the same Superset version)
This was still the case for v1.4.

The error we are getting is "datasource already exists". But this is exactly what we are trying to achieve....

![image](https://user-images.githubusercontent.com/44199231/154731294-0714a233-d721-4f56-8422-ed6409f4da77.png)

**Comment by villebro** [comment]
Thanks for reporting @LalaGabor. Can you provide reproduction steps? Alternatively, a stacktrace would be helpful.

**Comment by rusackas** [comment]
Closing as inactive, and for lack of reproduction steps. Import/Export has gotten A LOT better since this was filed, particularly with VERSIONED_EXPORTS turned on.
