### ISSUE TITLE
Clickhouse SQL syntax error in group by time_grain_expressions

### ISSUE THREAD

**Issue by romamur** [apache/superset#18834]
I have clickhouse field DateTime64 in my table. When i use this field in superset chart in both "time column" and in "group by" section - this gives me clickhouse syntax error. 

SQL query (generated by superset):
```
SELECT toMonday(toDateTime(created_date)) AS created_date
FROM default.test_table
GROUP BY toMonday(toDateTime(created_date))
LIMIT 10000
```
As you can see group by sql query missing expression `AS created_date`.

I temporary fix this by edit 2 files:
1. _superset/db_engine_specs/clickhouse.py_ **added AS {col}**
_class ClickHouseEngineSpec(BaseEngineSpec):_
```
_time_grain_expressions = {
        None: "{col}",
        "PT1M": "toStartOfMinute(toDateTime({col})) AS {col}",
        "PT5M": "toDateTime(intDiv(toUInt32(toDateTime({col})), 300)*300) AS {col}",
        "PT10M": "toDateTime(intDiv(toUInt32(toDateTime({col})), 600)*600) AS {col}",
        "PT15M": "toDateTime(intDiv(toUInt32(toDateTime({col})), 900)*900) AS {col}",
        "PT0.5H": "toDateTime(intDiv(toUInt32(toDateTime({col})), 1800)*1800) AS {col}",
        "PT1H": "toStartOfHour(toDateTime({col})) AS {col}",
        "P1D": "toStartOfDay(toDateTime({col})) AS {col}",
        "P1W": "toMonday(toDateTime({col})) AS {col}",
        "P1M": "toStartOfMonth(toDateTime({col})) AS {col}",
        "P0.25Y": "toStartOfQuarter(toDateTime({col})) AS {col}",
        "P1Y": "toStartOfYear(toDateTime({col})) AS {col}",
    }
```
2. _superset/db_engine_specs/base.py **added regex replace (in all sql query) "double AS expression" to "single AS expression"**
_class BaseEngineSpec:_
```
    @classmethod
    def execute(cls, cursor: Any, query: str, **kwargs: Any) -> None:
        if not cls.allows_sql_comments:
            query = sql_parse.strip_comments_from_sql(query)
        if cls.arraysize:
            cursor.arraysize = cls.arraysize
        try:
            if re.search(r"AS\s+\w+\s+AS\s+\w+", query):
                query = re.sub("AS\s+\w+", '', query, 1)
            cursor.execute(query)
        except Exception as ex:
            raise cls.get_dbapi_mapped_exception(ex)
```

Now i get correct SQL query (generated by superset with my fix):
```
SELECT toMonday(toDateTime(created_date)) AS created_date
FROM default.test_table
GROUP BY toMonday(toDateTime(created_date)) AS created_date
LIMIT 10000
```

I'ts not good fix, but worked for me. Sorry for my english

### Environment
Superset 1.3.0
ClickHouse Server: 20.5.4.40

**Comment by villebro** [comment]
Thanks for reporting - this appears to be a bug in how the ClickHouse dialect renders the `ColumnClause` (it should know how to render it, as the object has both the expression and alias available). Which SQLAlchemy connector + version are you using?

**Comment by romamur** [comment]
> Thanks for reporting - this appears to be a bug in how the ClickHouse dialect renders the `ColumnElement` (it should know how to render it, as the object has both the expression and alias available). Which SQLAlchemy connector + version are you using?

Thanks for reply. My drivers versions:
```
clickhouse-sqlalchemy v0.1.6
clickhouse-driver v0.2.3
```
I'm connected to db via http interface. My connection string was:
`clickhouse://secretgithubuser:secretgithubpass@127.0.0.1:8123/secretgithubdb`

BTW this is another bug but I will write about it too. I'm change connection to clickhouse+native and some bugs disappeared. For example "superset filter box chart" show me empty results in dropdown filter (when connection was clickhouse http). DDL of column was Int8 Not Null and contained only values '1' or '0'. When i change connection to clickhouse+native my dropdown filter was showing me the correct values to select '1' or '0'

**Comment by balsilliy** [comment]
I've got the same error .  Wait to fix it. ^_^
<img width="1516" alt="WX20220408-175803@2x" src="https://user-images.githubusercontent.com/26002425/162415878-885aa6f5-3702-407f-81f7-d85dd43119cb.png">
<img width="1734" alt="WX20220408-175830@2x" src="https://user-images.githubusercontent.com/26002425/162415916-044d2c85-bf3b-4eaf-8765-3b6dd69e3f1a.png">
<img width="1161" alt="WX20220408-175920@2x" src="https://user-images.githubusercontent.com/26002425/162415950-8e5dda05-268d-4cba-97aa-675cf255f782.png">

**Comment by balsilliy** [comment]
I tried the scripts then modified . It worked .

@classmethod
    def execute(cls, cursor: Any, query: str, **kwargs: Any) -> None:
        if not cls.allows_sql_comments:
            query = sql_parse.strip_comments_from_sql(query)
        if cls.arraysize:
            cursor.arraysize = cls.arraysize
        try:
            if re.search("AS\s+\"\w+\"\s+AS\s+\"\w+\"", query):
                query = re.sub("AS\s+\"\w+\"\s+", '', query, 1)
            cursor.execute(query)
        except Exception as ex:
            raise cls.get_dbapi_mapped_exception(ex)

**Comment by Carlos-GBF** [comment]
I have the same problem. Is there any update on this issue? If not, are you planning to upload any of the proposed solutions?

**Comment by vbakotin** [comment]
Also seeking any updates. @romamur thanks for the proposed fix! Btw haven't you encountered any issues with your code? Maybe some unwanted behavior in other functionality? Just wonder why not to upload any fix yet

**Comment by athlatif** [comment]
i have the exact same issue, any update in this regard?

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case and some sample data to go with it. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale. If anyone has a fix, we'd love to see a PR submitted!

**Comment by SylphiaWindy** [comment]
It's still an issue in 3.x.
https://github.com/apache/superset/issues/23384

**Comment by rusackas** [comment]
If it's in 3.1, we can reopen this. But if the linked issue covers it, then I'd rather not open a duplicate... let's just leave that one open :)
