### ISSUE TITLE
[Question] Add keppler.gl

### ISSUE THREAD

**Issue by hashbash** [apache/superset#18838]
Is there any way kepler.gl as chart visualisation for superset?

**Comment by villebro** [comment]
If you wish to discuss adding kepler.gl to Superset, please feel free to post on GitHub Discussions or the Superset Slack.

**Comment by mtv2102** [comment]
@hashbash Did you find the way to integrate kepler with Superset ?

**Comment by hashbash** [comment]
> @hashbash Did you find the way to integrate kepler with Superset ?

@mtv2102 
No, there is no way to do integration out of the box
