### ISSUE TITLE
the same promblem , how to fix please?

### ISSUE THREAD

**Issue by timidev** [apache/superset#18842]
I use window 10 , python3.8。

$ source activate py3env
(py3env) preks ~
$ flask fab create-admin
Username [admin]: admin
User first name [admin]: admin
User last name [user]: admin
Email [admin@fab.org]: admin@admin.admin
Password: admin
admin

![abcg](https://user-images.githubusercontent.com/61018536/98088861-fe509e00-1ea7-11eb-868d-1d28abaffc1c.PNG)

I have installed apache superset in my virtual env. I ran the command 'superset db upgrade'
And set the flask app using 'export FLASK_APP=superset'
But when I try to create admin user, I'm not asked to repeat for confirmation, instead it waits for input and when I re-enter the password and hit enter, nothing happens. It again waits for input.

How can I fix it?

_Originally posted by @ericfonsi in https://github.com/apache/superset/issues/9143#issuecomment-721595344_

**Comment by villebro** [comment]
Unfortunately Superset doesn't officially support Windows, so closing this. However, please feel free to ask for help on GitHub Discussions on on the Superset Slack. Also, please always use a descriptive title + fill out the standard template when opening new issues.
