### ISSUE TITLE
[issue][question]: sqllab errored in the new Superset,but work well in V1.0.1

### ISSUE THREAD

**Issue by ljclour** [apache/superset#18841]
My org want to use RLS so we update a new version,but also keep the old one.The new one use the same config and setting from V1.0.1,but somthing wrong ocurr.

In the new one,we can connect the database (DB2),using the chart and dashboard that created in the V1.0.1.While want to write a new sql in sqllab there is an error like the screenshot below.

## Screenshots in New Version 
error sqllab in new version
![image](https://user-images.githubusercontent.com/45123712/155058084-e42d21ae-e21e-4560-9b3f-c55e9e0453e6.png)

but using chat(explore the dataset) and dashboard is ok ,but also raise message,
![image](https://user-images.githubusercontent.com/45123712/155058249-5f2e49a8-9039-422e-9f5c-39708a9bbbb6.png)

![image](https://user-images.githubusercontent.com/45123712/155058600-7f80d216-e3b3-47f6-b302-b6b1bf6e9575.png)

 ### Screenshots in Version V1.0.1
sqllab work well and dashboard do not raised message.
![image](https://user-images.githubusercontent.com/45123712/155058861-6a3c2f36-bef4-4aae-af15-7e81156e5666.png)

**Comment by villebro** [comment]
Thanks for posting @ljclour - would you be able to post a stacktrace of the error?
