### ISSUE TITLE
[Explore] Iterating between chart types in results in broken charts due to unnecessary group by parameters passed

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#18858]
Iterating between chart types in explore view results in broken charts due to unnecessary parameters passed to new charts. For example in this case, the group by gets added into the new chart type query, even though the new chart type don't have group by feature, making it basically broken, **preventing users from iterating between chart types - they would have to start creation of new chart from the scratch**. 

#### How to reproduce the bug

1. In Explore create time series line chart, include group by parameters
2. Switch to Big number with trendline chart
3. Add the metric as necessary
4. Click on See SQL Query and you will see it added the group by parameter from the time series line chart, which however doesn't apply to the new chart type

### Expected results

Do not transfer parameter which do not make sense in new chart type

### Actual results

Wrongly transferred the group-by parameter

#### Screenshots
Step 1: create time series line chart with a group by parameter
<img width="983" alt="Screen Shot 2022-02-22 at 5 11 00 PM" src="https://user-images.githubusercontent.com/61221714/155241630-779fde8b-a7a1-4bfa-a37e-b4972d30dcaa.png">

Step 2: Change to big number with trendline
<img width="267" alt="Screen Shot 2022-02-22 at 5 12 26 PM" src="https://user-images.githubusercontent.com/61221714/155241627-a45c6b44-23c7-4166-b2f0-47007981f647.png">

Step 3: if you click on view query you see the issue it added the group by from previous chart, even though it's not an option to configure on the trendline chart

<img width="983" alt="Screen Shot 2022-02-22 at 5 12 48 PM" src="https://user-images.githubusercontent.com/61221714/155241620-e7e75ec0-19a7-4f6a-90fe-9abe7aad2eca.png">

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: `superset version` latest master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Issue in latest master version (from 02/17/2022)

**Comment by villebro** [comment]
Thanks for reporting @zuzana-vej - I am unable to reproduce the error both with and without DND feature flag.

Step 1: create a Line chart with a groupby:
<img width="1484" alt="image" src="https://user-images.githubusercontent.com/33317356/155275134-81fc88dc-29ea-4013-8120-65fb1b817171.png">

Move to Big Number with Trendline and re-add the metric (this is lost as currently the plural `metrics` control is incompatible with the singular `metric`):
<img width="1484" alt="image" src="https://user-images.githubusercontent.com/33317356/155275229-3de126ef-10b7-4556-9410-98b3efe1232d.png">

**Comment by zuzana-vej** [comment]
Yay! fixed with our latest release!
