### ISSUE TITLE
charts VISUALIZATION TYPE select Time-series Line Chart dashboard view chart in explore have issue

### ISSUE THREAD

**Issue by allenzhg** [apache/superset#18862]
#### How to reproduce the bug

1. Go to 'charts '
2. Click on 'VISUALIZATION TYPE to "Time-series Line Chart"' 
3. Scroll down to 'save'
4. Go to 'dashboards -> a dashboard'
5. select "view chart in explore"
6. See error

### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version: chrome 版本 96.0.4664.110（正式版本） （64 位）
- superset version: `1.4.1`
- python version: `3.8.12`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
@allenzhg thanks for reporting. We would need some more information about the error you are seeing. Please share a screenshot or a copy of the error text you're seeing so we can figure out what the problem is.

**Comment by allenzhg** [comment]
1. ![image](https://user-images.githubusercontent.com/20509543/155275043-19c4c4f0-8ecd-4937-b90f-27e64596c32b.png)
2. ![image](https://user-images.githubusercontent.com/20509543/155275120-a373cde0-48e3-4810-8c9d-3ee94aae4082.png)
3. ![image](https://user-images.githubusercontent.com/20509543/155275159-7ddb7b66-5130-405b-8ed0-33527c57e6de.png)

**Comment by allenzhg** [comment]
i visit this chart for table have a same issue. 
![image](https://user-images.githubusercontent.com/20509543/155638706-4ba843c3-5cf2-4faa-b2c3-75f014d942d5.png)

**Comment by allenzhg** [comment]
已经解决，是因为页面缓存默认配置太小导致。
