### ISSUE TITLE
Element on docs page preventing page to scroll down.

### ISSUE THREAD

**Issue by caioricciuti** [apache/superset#18868]
## Screenshot
![Screenshot 2022-02-23 at 11 52 18](https://user-images.githubusercontent.com/63287675/155305469-ce03e338-8689-401d-a174-13ee9167a841.png)

![Screenshot 2022-02-23 at 11 53 46](https://user-images.githubusercontent.com/63287675/155305680-c74d1da7-fc5f-4398-b6d3-8bbb9b84e3b3.png)

## Description
Element on screenshot are preventing page to scroll down. 

## Design input
It can be solve by setting `position: fixed` to this element.

![Screenshot 2022-02-23 at 11 56 24](https://user-images.githubusercontent.com/63287675/155306169-f497193a-2f7f-4069-82e3-1d187bdc24d3.png)

**Comment by bwgroff** [comment]
Is this related to [this docusaurus issue](https://github.com/facebook/docusaurus/issues/6587)?

**Comment by srinify** [comment]
This is fixed, thanks! Closing
