### ISSUE TITLE
Helm repo not found

### ISSUE THREAD

**Issue by Jukie** [apache/superset#18887]
#### How to reproduce the bug

`$ helm repo add superset https://apache.github.io/superset`
Produces a 404 error:
`Error: looks like "https://apache.github.io/superset" is not a valid chart repository or cannot be reached: failed to fetch https://apache.github.io/superset/index.yaml : 404 Not Found`

### Expected results

Repo should exist, following these docs: https://superset.apache.org/docs/installation/running-on-kubernetes/

### Actual results

Repo and website appears empty

Likely culprit: https://github.com/apache/superset/commit/84f7d6f9005b25146ea26ce100d479a2e2a9f2b9 @srinify

**Comment by srinify** [comment]
Ah oops! I mistook the following documentation here to think it would re-deploy docs to superset.apache.org

https://github.com/apache/superset/tree/master/docs#deployment

**Comment by Jukie** [comment]
Still new here but I think that's referring to the [GtHub Action](https://github.com/apache/superset/blob/master/.github/workflows/superset-docs.yml) setup to update the site which uses https://github.com/apache/superset-site.

**Comment by Jukie** [comment]
@craig-rueda
