### ISSUE TITLE
CSS does not working when I open the dashboard

### ISSUE THREAD

**Issue by testejaneiro** [apache/superset#18881]
#### How to reproduce the bug

1.Go to 'Any dashboard'
2.Click on 'Edit dashboard > Edit CSS'
3.Save CSS template
4.Refresh browser
5.See error

### Expected results

I expected that opens the CSS that i choose 

### Environment

(please complete the following information):

superset version: 0.38.0
python version: based on superset version 0.38.0
node.js version: based on superset version 0.38.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I have found one similar. but does not working - I need more details
#10102

**Comment by rusackas** [comment]
Closing this since it's presumed fixed. This stale issue was filed regarding an old version of Superset, and I *know* this has been tested thoroughly in more recent versions. If anyone finds a use case where we can break it nowdays, let's open a fresh issue with current repro steps and context.
