### ISSUE TITLE
Getting Cannot assign requested address in scheduling reports

### ISSUE THREAD

**Issue by FaidJalal19** [apache/superset#18885]
Hi 

I am scheduling csv reports. The reports gets successfully scheduled and executed but I get following error while sending the mails
**Report state: Failed generating dataframe <urlopen error [Errno 99] Cannot assign requested address>**
**Report state: Failed generating csv <urlopen error [Errno 99] Cannot assign requested address>**
![Screenshot from 2022-02-23 21-06-31](https://user-images.githubusercontent.com/50728863/155352599-58165733-5bb1-42d4-957c-3ca7fba16035.png)

Can anyone help out

**Comment by pearsonhenri** [comment]
Running into the same issue here

**Comment by infl18** [comment]
Hello, faced with the same error, web driver tried both firefox and chrome.

## SETTINGS
```
WEBDRIVER_BASEURL = "http://superset:8088/"
WEBDRIVER_TYPE = "chrome"
WEBDRIVER_OPTION_ARGS = [
    "--force-device-scale-factor=2.0",
    "--high-dpi-support=2.0",
    "--headless",
    "--disable-gpu",
    "--disable-dev-shm-usage",
    "--no-sandbox",
    "--disable-setuid-sandbox",
    "--disable-extensions",
]
```
## DOCKERFILE
```
FROM apache/superset:2.0.0-dev
USER root
RUN apt-get update && \
    wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    apt-get install -y --no-install-recommends ./google-chrome-stable_current_amd64.deb && \
    rm -f google-chrome-stable_current_amd64.deb
RUN export CHROMEDRIVER_VERSION=$(curl --silent https://chromedriver.storage.googleapis.com/LATEST_RELEASE) && \
    wget -q https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip && \
    unzip chromedriver_linux64.zip -d /usr/bin && \
    chmod 755 /usr/bin/chromedriver && \
    rm -f chromedriver_linux64.zip
RUN pip install --no-cache gevent psycopg2 redis
USER superset
```
## LOGS
```
Init selenium driver
[2023-01-19 11:44:01,306: INFO/ForkPoolWorker-1] Init selenium driver
Taking a PNG screenshot of url http://superset:8088/superset/dashboard/62/?standalone=3&force=true
[2023-01-19 11:44:18,409: INFO/ForkPoolWorker-1] Taking a PNG screenshot of url http://superset:8088/superset/dashboard/62/?standalone=3&force=true
A downstream exception occurred while generating a report: 47e5d40a-552d-4728-8512-89daec8285b4
Traceback (most recent call last):
  File "/app/superset/tasks/scheduler.py", line 79, in execute
    AsyncExecuteReportScheduleCommand(
  File "/app/superset/reports/commands/execute.py", line 659, in run
    raise ex
  File "/app/superset/reports/commands/execute.py", line 655, in run
    ReportScheduleStateMachine(
  File "/app/superset/reports/commands/execute.py", line 624, in run
    state_cls(
  File "/app/superset/reports/commands/execute.py", line 525, in next
    raise first_ex
  File "/app/superset/reports/commands/execute.py", line 503, in next
    self.send()
  File "/app/superset/reports/commands/execute.py", line 409, in send
    self._send(notification_content, self._report_schedule.recipients)
  File "/app/superset/reports/commands/execute.py", line 400, in _send
    raise ReportScheduleNotificationError(";".join(notification_errors))
superset.reports.commands.exceptions.ReportScheduleNotificationError: [Errno 99] Cannot assign requested address
[2023-01-19 11:44:18,863: ERROR/ForkPoolWorker-1] A downstream exception occurred while generating a report: 47e5d40a-552d-4728-8512-89daec8285b4
Traceback (most recent call last):
  File "/app/superset/tasks/scheduler.py", line 79, in execute
    AsyncExecuteReportScheduleCommand(
  File "/app/superset/reports/commands/execute.py", line 659, in run
    raise ex
  File "/app/superset/reports/commands/execute.py", line 655, in run
    ReportScheduleStateMachine(
  File "/app/superset/reports/commands/execute.py", line 624, in run
    state_cls(
  File "/app/superset/reports/commands/execute.py", line 525, in next
    raise first_ex
  File "/app/superset/reports/commands/execute.py", line 503, in next
    self.send()
  File "/app/superset/reports/commands/execute.py", line 409, in send
    self._send(notification_content, self._report_schedule.recipients)
  File "/app/superset/reports/commands/execute.py", line 400, in _send
    raise ReportScheduleNotificationError(";".join(notification_errors))
superset.reports.commands.exceptions.ReportScheduleNotificationError: [Errno 99] Cannot assign requested address
```

Has anyone encountered the same problem?

**Comment by divick** [comment]
Running into the same issue

**Comment by kokoroX** [comment]
Running into the same issue

```
[2023-03-23 08:02:17,053: ERROR/ForkPoolWorker-7] A downstream exception occurred while generating a report: 10d38277-6a5e-4a11-b4e4-59dbae998741. [SupersetError(message='[Errno 99] Cannot assign requested address', error_type=<SupersetErrorType.REPORT_NOTIFICATION_ERROR: 'REPORT_NOTIFICATION_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra=None)]
Traceback (most recent call last):
  File "/app/superset/tasks/scheduler.py", line 87, in execute
    AsyncExecuteReportScheduleCommand(
  File "/app/superset/reports/commands/execute.py", line 723, in run
    raise ex
  File "/app/superset/reports/commands/execute.py", line 719, in run
    ReportScheduleStateMachine(
  File "/app/superset/reports/commands/execute.py", line 677, in run
    state_cls(
  File "/app/superset/reports/commands/execute.py", line 578, in next
    raise first_ex
  File "/app/superset/reports/commands/execute.py", line 547, in next
    self.send()
  File "/app/superset/reports/commands/execute.py", line 445, in send
    self._send(notification_content, self._report_schedule.recipients)
  File "/app/superset/reports/commands/execute.py", line 434, in _send
    raise ReportScheduleSystemErrorsException(errors=notification_errors)
```

**Comment by infl18** [comment]
> Тоже столкнулась с этой проблемой ![Снимок экрана от 2023-06-08 12-46-52](https://user-images.githubusercontent.com/79561412/244322201-561bbfd1-8658-464f-818f-cb023c626efb.png)
> 
> Как решили?

чекайте smtp настройки. где-то ошибка.

**Comment by sfirke** [comment]
The issue may be that you haven't specified the SMTP server.  I believe that `[Errno 99] Cannot assign requested address` message is coming from the smtplib library, you'll see Airflow-related questions on the web with this same problem.  Either you didn't specify the SMTP server at all, or Superset isn't able to connect to it, or you specified it in a config that isn't getting picked up or is being overwritten.

Look at the SMTP-related values in the `config.py` file that contains all the default config values, then override the relevant ones with your settings.  For a docker-compose deployment, you would do this in `superset_config.py` or `superset_config_docker.py` in the `docker/pythonpath_dev/` directory.

Someone wrote this in the Superset Slack chat in February 2023 after they debugged this error:

> What I didn't really quite understand from the documentation regarding this, is whatever you specify in config.py, if you running on docker, you HAVE to migrate these settings to superset_config.py otherwise settings will not persist. My error is that I was not setting the SMTP settings inside the superset_config.py
Assuming you have all the settings correct, your SMTP credentials are good, you can get this one working quite easily, (it took me days to figure this out, but I didn't quite understand the structure in the begining, now everything is clear)

**Comment by martyweb** [comment]
If it helps anyone, I was having this same problem and fixed it by moving all the SMTP:* variables from the "extraEnv" section to the "configOverrides" section. All the values were exactly the same but it appears they were not getting picked up in extraEnv.

**Comment by jesperbagge** [comment]
> If it helps anyone, I was having this same problem and fixed it by moving all the SMTP:* variables from the "extraEnv" section to the "configOverrides" section. All the values were exactly the same but it appears they were not getting picked up in extraEnv.

Can confirm that this is still an issue and the suggested solution by @martyweb works!

**Comment by rusackas** [comment]
@jesperbagge @martyweb it seems we've had a few people running into this. Do you think that adding some comments in the config file would help? And/or adding some notes in the docs? Would love to improve the situation rather than have more people googling for an antique GitHub issue :D 

(cc @villebro / @sfirke who might also know a good way to improve this).

**Comment by sfirke** [comment]
@rusackas it looks to me like what @jesperbagge and @martyweb are dealing with are related to deploying with the Kubernetes Helm chart.  Can they confirm and is that also what you're seeing elsewhere?

If so maybe they or someone else can implement this in the Helm chart via a PR.

**Comment by rusackas** [comment]
Ahh, if it's implementable/fixable in the helm chart, that's ideal. I thought maybe it was a case of adding a line to the docs somewhere :) As it stands, this thread is the only resource for others who run into the issue.

**Comment by martyweb** [comment]
> @rusackas it looks to me like what @jesperbagge and @martyweb are dealing with are related to deploying with the Kubernetes Helm chart. Can they confirm and is that also what you're seeing elsewhere?
> 
> If so maybe they or someone else can implement this in the Helm chart via a PR.

Yep, I'm deploying to k8s using Helm

**Comment by jesperbagge** [comment]
> @rusackas it looks to me like what @jesperbagge and @martyweb are dealing with are related to deploying with the Kubernetes Helm chart. Can they confirm and is that also what you're seeing elsewhere?
> 
> If so maybe they or someone else can implement this in the Helm chart via a PR.

Yes, I’m also deploying with the Helm chart. Ideally the solution would be to make the `extraEnv` key work as expected. Unfortunately, K8s is still magic to me. I do a victory dance every time I manage to do something that works.
