### ISSUE TITLE
Superset install (pip) fails because of a broken dependency (Linux/Ubuntu)

### ISSUE THREAD

**Issue by dat-linux** [apache/superset#18888]
#### How to reproduce the bug

python3 -m pip install apache-superset
superset db upgrade
export FLASK_APP=superset
superset fab create-admin
superset load_examples

**ImportError: cannot import name 'soft_unicode' from 'markupsafe'**

It seems latest **markupsafe** pkg broke backwards compatibility by removing the **soft_unicode** module.

**Comment by jacobcroope** [comment]
Came up in other dependence errors conversation. 

https://github.com/apache/superset/issues/18723#issuecomment-1045160120

**Comment by zhaoyongjie** [comment]
This issue was resolved by [disscussion](https://github.com/apache/superset/issues/18723#issuecomment-1049107830).
