### ISSUE TITLE
[2.0] Turn on `SQLLAB_BACKEND_PERSISTENCE` by default

### ISSUE THREAD

**Issue by suddjian** [apache/superset#18898]

**Comment by rusackas** [comment]
Airbnb will revisit this feature, and see if old concerns need addressing before we can flip this. CC @betodealmeida who asked for this to be in the 2.0 BOM.

**Comment by rusackas** [comment]
To re-word: we need to revisit Airbnb's concerns, and see if any of them are concerns that the community may have that need addressing.
