### ISSUE TITLE
Registration is  not working in superset (Authentication:Database)

### ISSUE THREAD

**Issue by aakanshajecrc** [apache/superset#18919]
I am trying to do authentiction(database) in superset using the guide at: 
https://flask-appbuilder.readthedocs.io/en/latest/security.html

Please note that I am attempting it on Ubuntu 20.04 VMs behind a proxy. And I am running superset on http://localhost:9000/(in dev mode)  

#### How to reproduce the bug

1 Clone Superset repository
2 cd superset
3 docker-compose up
4 in another terminal(cd superset/superset-frontend)
5 npm run dev-server

what you expected to happen.

Login Successfully.

what actually happens.

register is working.but after registration(save)

i am getting this type of error:
{"errors": [{"message": "<urlopen error [Errno -3] Temporary failure in name resolution>", "error_type": "GENERIC_BACKEND_ERROR", "level": "error", "extra": {"issue_codes": [{"code": 1011, "message": "Issue 1011 - Superset encountered an unexpected error."}]}}]}

Screenshots

### Environment

OS: Ubuntu Server 20.04
Python on VM: 3.8.10
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing this one since it's been nearly a year, and it hasn't gained any traction. Lots of folks use this workflow, and lots of folks are using Ubuntu. I'm assuming this was a fluke of configuration. If you're still seeing an issue like this, I'm more than happy to re-open it.
