### ISSUE TITLE
Module not found Error Building custom viz plugins in superset

### ISSUE THREAD

**Issue by pm20202** [apache/superset#18912]
I am trying to install Superset for building custom visualization using the guide at: https://superset.apache.org/docs/installation/building-custom-viz-plugins/

Please note that I am attempting it on Ubuntu 20.04 VMs behind a proxy. And I am running superset on http://localhost:9000/(in dev mode)

However, for tinkering with custom visualizations, I need to go https://superset.apache.org/docs/installation/building-custom-viz-plugins/#add-your-plugin-to-superset-with-npm-link. After following all the steps successfully when I run it on 9000 port
I got this error. _"Module not found: Error: Can't resolve '@superset-ui/plugin-chart-hello-world' in '/home/rrscw/superset/superset-frontend/src/visualizations/presets''_

### Expected results

hello world chart plugin visible in superset on port 9000 in dev mode.

### Actual results
https://superset.apache.org/docs/installation/building-custom-viz-plugins/#add-your-plugin-to-superset-with-npm-link
After adding package in package.json using above link and successfully doing changes in MainPreset.js file I got this error:
 
ERROR in ./src/visualizations/presets/MainPreset.js 40:0-74
Module not found: Error: Can't resolve '@superset-ui/plugin-chart-hello-world' in '/home/rrscw/superset/superset-frontend/src/visualizations/presets'

### Environment

(please complete the following information):

OS: Ubuntu Server 20.04
Python on VM: 3.8.10

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
@pm20202 thanks for reporting - it appears this documentation is the old one. Let me see if the documentation has been reverted at some point.

**Comment by villebro** [comment]
This is the correct page: https://superset.apache.org/docs/contributing/creating-viz-plugins . I'll make sure the old one gets removed. Please also check out a blog post + an example plugin I wrote for the article: https://preset.io/blog/building-custom-viz-plugins-in-superset-v2/

**Comment by pm20202** [comment]
Thanks a lot! It worked for me

**Comment by pm20202** [comment]
Thanks ! It worked for me

**Comment by alex1404** [comment]
This is not working , any solution ?
