### ISSUE TITLE
If the same table name exists in multiple databases, hard to distinguish dataset when adding charts

### ISSUE THREAD

**Issue by srinisubramanian** [apache/superset#18942]
Lets assume that the same table USERS exists in DB1 and DB2.  Both datasets can be added and since Database is also shown its easy to add.  However when adding a chart (for e.g.) only dataset name is shown and USERS appears twice.  Hard to distinguish if its from DB1 or DB2.  If the Database or datasource name is displayed in addition to dataset name it will be easy to distinguish

#### How to reproduce the bug

1. Go to Database and add two databases that have a common table like USERS.  Also add the USERS table (for .e.g) from both databases to the datasets
2. Click on Charts and search for USERS.  Its displayed twice and cannot be distinguished

### Expected results
Should be possible to distinguish between the two entries

what you expected to happen.

### Actual results

what actually happens.

#### Screenshots

![image](https://user-images.githubusercontent.com/8343179/155703155-e3825291-17a0-4458-8b19-5d65e346551b.png)

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by srinify** [comment]
Agree with this @srinisubramanian ! Check out the new designs, which should help address the issue by providing a better UX for finding & filtering datasets, contextualized to the database / schema they originate from:

https://github.com/apache/superset/discussions/18803

**Comment by srinisubramanian** [comment]
This still needs to be addressed

**Comment by rusackas** [comment]
@kasiazjc @yousoph have there been any discussions to figure out a better way to handle this scenario that you're aware of?

**Comment by rusackas** [comment]
This is no longer an issue... you see the DB and schema in the list.
