### ISSUE TITLE
Is Microsoft SQL server supported as the metadata engine

### ISSUE THREAD

**Issue by parker-pu** [apache/superset#18961]
#### Error executing "superset db upgrade"
![image](https://user-images.githubusercontent.com/46392095/155974278-bdf71491-583c-4de0-b6ad-5a234dc39d14.png)

```
sqlalchemy.exc.ProgrammingError: (pymssql._pymssql.ProgrammingError) (208, b"Invalid object name 'alembic_version'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")
[SQL: UPDATE alembic_version SET version_num='b4456560d4f3' WHERE alembic_version.version_num = 'bb51420eaf83']
```

**Comment by villebro** [comment]
Unfortunately no - Only Postgres and MySQL are supported.

**Comment by parker-pu** [comment]
thank you

**Comment by AnanthaGopi0** [comment]
I want to configure the Microsoft SQL server as the metadata is there any process for this?

**Comment by villebro** [comment]
Only MySQL and Postgres are officially supported. MSSQL might work, but is not guaranteed to do so. But I don't recommend using anything other than Postgres and MySQL for anything else than experimental usage.

**Comment by AnanthaGopi0** [comment]
Thank You for your reply and suggestion.

**Comment by sfirke** [comment]
Update that someone just reported in Slack trying Superset version 2.1.0 with Microsoft SQL Server as a backend and it did not work.  So the answer to this question remains "No."

**Comment by cumulate** [comment]
> Update that someone just reported in Slack trying Superset version 2.1.0 with Microsoft SQL Server as a backend and it did not work. So the answer to this question remains "No."

@sfirke  May I know if there are any technical limitations in extending support to SQLServer to use for metadata db?? Can you please let me know the feasibility of customizing the superset to support SQLServer? If it can be done, then I want to evaluate the efforts of customizing to extend the support for SQL Server, as it's a pressing need for me now!

TIA

**Comment by sfirke** [comment]
That's a good question @cumulate .  I'm not sure about the feasibility.  You might want to join the Superset Slack chat and see this thread: https://apache-superset.slack.com/archives/C01SS4DNYG5/p1691659469935669

In it someone answers:
> Basically if flask-migrate cannot support mssql, then superset can't either

If it would be possible to address this by getting flask-migrate to substitute characters in strings or wrap them differently for SQL Server, that would be a great contribution to that project.  This is not a technical area I'm familiar with so I can't help more.  It does seem like you'd contribute to the flask-migrate project to fix this, or maybe SQL Alchemy.  Possibly related: https://github.com/miguelgrinberg/Flask-Migrate/issues/328

Let us know here if you submit a fix for this upstream - if Superset becomes able to use MSSQL as a backend I'd happily update the docs!

**Comment by lokeshMrudhul** [comment]
I was able to connect to MSSQL for the metadata engine, and it’s working absolutely fine. I made a few changes to the version files.

**Comment by sfirke** [comment]
@lokeshMrudhul interesting, thanks for letting us know! If those changes you made were specific to accommodating SQL Server as a metadata store, I would be curious to hear what they were.
