### ISSUE TITLE
Superset MapBox Clustering radius (pixel) not working with Gamma user roles

### ISSUE THREAD

**Issue by vikram1840** [apache/superset#18977]
## Screenshot

[drag & drop image(s) here!]
**Alpha/Admin Role user**
![Cluster radius with Alpha Admin Role](https://user-images.githubusercontent.com/54261950/156136394-847b75b7-fe41-4e9c-afb8-50a67fd6643d.png)

**Gamma Role user**
![Mapbox cluster radious with Gamma Role](https://user-images.githubusercontent.com/54261950/156136502-6396414b-433a-4671-ab0c-5a4eadcdcc42.png)

## Description
Dashboard developed using mapbox with feature **CLUSTERING RADIUS** option does not work with Gamma role users.

[describe the issue here!]
When the same dashboard has been accessed with Admin or Alpha role user can see mapbox with highlighted cluster radius but Gamma role user(dataset access already provided) unable to see that highlighted bubble cluster radius . 

Please suggest if we need to chnage something during role definition or any suggestion .

**Comment by VikramKumarArammeem** [comment]
I found the issue. This was happening because of browser issue.
When I used to open chart in Mozilla Firefox there was no clusters radius option  while same chart opened in Google chrome and MS Edge it worked fine.

**Comment by rusackas** [comment]
Seems to work just fine in Firefox these days. I'll close this as resolved, but I'm happy to re-open it if anyone finds otherwise! Thanks for the bug report nonetheless!!
