### ISSUE TITLE
rison library used for query param encoding not correctly escaping

### ISSUE THREAD

**Issue by cancan101** [apache/superset#18994]
The `rison` used for query param encoding (e.g. [see here](https://github.com/apache/superset/blob/2491b89f2911482d9951064e541d616e396f75eb/superset-frontend/src/components/Datasource/DatasourceEditor.jsx#L642-L644)) does not correctly encode `=` or `?`.

See for example here https://runkit.com/agrothberg/rison-issues how this `rison.encode({table_name: 'a?a=b'})` is encoded as `(table_name:a?a=b)`.

Trying to parse that using the `prison` library on python (CC @betodealmeida): `prison.loads("(table_name:a?a=b)")` leads to `prison.decoder.ParserException: missing ',`.

This is the underlying issue that I first saw on: https://github.com/apache/superset/issues/18993 however that is an independent issue.

#### How to reproduce the bug

1. Use legacy datasource editor
2. Define a table with an `=` in its name
3. Click sync columns from source

### Expected results

Ideally it should handle the table name (it looks like the string is not properly `rison` encoded. If it isn't going to allow these strings, then at the very least the 400 error should be properly generated.

### Actual results

Table name not parsable by the backend.

#### Screenshots

n/a

### Environment

- browser type and version: Chrome 98.0.4758.102 
- superset version: `Superset 1.4.1`
- python version: `Python 3.7.3`
- node.js version: `v15.4.0`
- any feature flags active: n/a

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar. This might be a duplicate with: https://github.com/apache/superset/issues/13708, though I can't tell if that was supposed to have been fixed in: https://github.com/apache/superset/pull/18056

### Additional context

n/a

**Comment by eschutho** [comment]
Oh, good call. We'll take a look at that. Thank you!

**Comment by cancan101** [comment]
OK, I think the issue as initially reported is in fact fixed by https://github.com/apache/superset/pull/18056 that being said, my comment still stands that there may also be some other case where rison is used in a query param but the correct call to encode is not being used.

**Comment by Neoky** [comment]
We found an example in our project. Here is an example URL with everything changed to foo/bar. The problem is the ampersand '&' between Foo and Bar in the database name. When we renamed the database it started working.

https://superset/datasource/external_metadata_by_name/?q=(database_name:%27Foo&Bar%27,datasource_type:table,schema_name:foo_bar,table_name:%27MASTER_foo%20Activator_bar%27)
