### ISSUE TITLE
create table charts from elasticsearch

### ISSUE THREAD

**Issue by loongWoong** [apache/superset#18995]
#### How to reproduce the bug

1. create a new chart choose dataset elasticsearch data"filebeat-6.8.3-2022.03.02"
---elasticsearch version:7.10.1
2. check "server pagination" option selected
4. click "run" to view the table
5. click page 2 is error

### Expected results

the table show next page

### Actual results

therre is error code put out 

#### Screenshots

Unexpected error

Error: Error (parsing_exception): {'error': {'root_cause': [{'type': 'parsing_exception', 'reason': "line 4:1: mismatched input 'OFFSET' expecting <EOF>"}], 'type': 'parsing_exception', 'reason': "line 4:1: mismatched input 'OFFSET' expecting <EOF>", 'caused_by': {'type': 'input_mismatch_exception', 'reason': None}}, 'status': 400}

### Environment

(please complete the following information):

- browser type and version: Firefox 79
- superset version: `1.4.1`
- python version: 3.7
- elasticsearch version:7.10.1

**Comment by zhaoyongjie** [comment]
Hi @loongWoong, I am just running Elasticsearch 7.17.0 on a development server. Could you tell me how to get `filebeat-6.8.3-2022.03.02` for testing?

**Comment by loongWoong** [comment]
> Hi @loongWoong, I am just running Elasticsearch 7.17.0 on a development server with standalone mode. Could you tell me how to get `filebeat-6.8.3-2022.03.02` for testing?

it's the log data collect from filebeat-6.8.3 . I guess if the elasticsearch 7.10.1 version is not supported. I can't find the supported version description on the official website

**Comment by zhaoyongjie** [comment]
@loongWoong Does this problem exist in any table of Elasticsearch?

**Comment by rusackas** [comment]
Closing this one since it seems to have gone inactive for nearly a year. If this is still an issue in Current Superset with supported versions of Elasticsearch, let's re-open it, and add updated context. Thanks!
