### ISSUE TITLE
superset.views.datasource.views.Datasource does not implement a response_400

### ISSUE THREAD

**Issue by cancan101** [apache/superset#18993]
When this error handler is hit:
https://github.com/dpgaspar/Flask-AppBuilder/blob/2d505e819d496308a34c5f623d70331a37599cc4/flask_appbuilder/api/__init__.py#L145-L146 in the `superset.views.datasource.views.Datasource` view, a a further Exception is raised as there is no 400 handler for that view:
```
Traceback (most recent call last):
  File "/Users/alex/.pyenv/versions/3.7.3/envs/app/lib/python3.7/site-packages/superset/views/base.py", line 203, in wraps
    return f(self, *args, **kwargs)
  File "/Users/alex/.pyenv/versions/3.7.3/envs/app/lib/python3.7/site-packages/flask_appbuilder/api/__init__.py", line 145, in wraps
    return self.response_400(
AttributeError: 'Datasource' object has no attribute 'response_400'
```

#### How to reproduce the bug

1. Use legacy datasource editor
2. Define a table with an `=` in its name
3. Click sync columns from source

### Expected results

Ideally it should handle the table name (it looks like the string is not properly `rison` encoded. If it isn't going to allow these strings, then at the very least the 400 error should be properly generated

### Actual results

A toast showing: "'Datasource' object has no attribute 'response_400'"

#### Screenshots
The dataset:
![image](https://user-images.githubusercontent.com/51059/156256040-4b71d68e-20af-4cf4-9b5f-709084f0b405.png)

The error toast:
![image](https://user-images.githubusercontent.com/51059/156256007-1ebc7578-332f-4d9b-9405-1411cce4f22a.png)

### Environment

(please complete the following information):

- browser type and version: Chrome 98.0.4758.102 
- superset version: `Superset 1.4.1`
- python version: `Python 3.7.3`
- node.js version: `v15.4.0`
- any feature flags active: n/a

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by cancan101** [comment]
So it looks like https://github.com/apache/superset/pull/18056 did fix the rison encoding meaning that the 400 error is no longer generated by that code path. That being said, if something else does generate a 400 error at some point the view does not correctly handle it and will then raise an error that `response_400` is not defined. This can be tests using a CLI tool and `GET`ing against `/datasource/external_metadata_by_name/` with `q=<invalid rison string>`.

**Comment by zhaoyongjie** [comment]
Hi @cancan101, thanks for the debug. Today, I tested the endpoint in my local test environment. It looks works.

![image](https://user-images.githubusercontent.com/2016594/157155431-4eced28d-f9e1-4438-9eb1-2c55da1e3619.png)

**Comment by cancan101** [comment]
I just ran this:
```bash
curl 'http://127.0.0.1:8088/datasource/external_metadata_by_name/?q=(database_name:SWAPI,datasource_type:table,schema_name:main,table_name:allSpecies?foo=1)' ....
```
(omitting the full curl line)
and got back:
```
{"error": "'Datasource' object has no attribute 'response_400'"
```
this is running against master.

**Comment by zhaoyongjie** [comment]
@cancan101 You should quote the table_name with single quotation. 

```
curl "http://127.0.0.1:8088/datasource/external_metadata_by_name/?q=(database_name:SWAPI,datasource_type:table,schema_name:main,table_name:'allSpecies?foo=1')" ....
```

**Comment by cancan101** [comment]
Right , I intentionally misquoted it to be consistent with the prior broken rison escaping logic. That logic is now fixed in Master however this endpoint should return a 400 error not a 500 error in the case of a malformed query param.

**Comment by zhaoyongjie** [comment]
Hi @cancan101,  Thanks for point this out.

The endpoint `external_metadata_by_name` base on a [BaseSupersetView](https://github.com/apache/superset/blob/e89f0abf95a5b49291bfa11f1d0277ade43eb2c0/superset/views/datasource/views.py#L57). `BaseSupersetView` hasn't `response_400` method, so that when we invoke `self.response_400(message="Not a valid rison argument")` in `rison` [decorator](https://github.com/dpgaspar/Flask-AppBuilder/blob/2d505e819d496308a34c5f623d70331a37599cc4/flask_appbuilder/api/__init__.py#L128-L159), it raise a 500 exception.

I think we have 2 ways to fix this.
1. Use `BaseSupersetModelRestApi` instead of `BaseSupersetView` in datasource.views
2. The `rison` decorator raise a `ValueError` exception instead a HTTP response.

@dpgaspar What do you think about this issue?

**Comment by eschutho** [comment]
@zhaoyongjie We're doing some work on the dataset models and apis. I think we can take this on and migrate the datasource api to v1, which would use the restApi base model.

**Comment by cici1210** [comment]
Check if your dataset name contains special characters.

**Comment by rusackas** [comment]
Also tagging @hughhhh here since I know he's working on some API V1 refactors/migration currently.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
