### ISSUE TITLE
STACKED BARS VALUES did not show  correctly when data has negative value

### ISSUE THREAD

**Issue by zhoulijuanmiao** [apache/superset#18996]
#### How to reproduce the bug

1. go to example chart of "Quarterly Sales (By Product Line)"
2. change METRICS of query to custom sql "SUM(sales) - 40000"
3. check option "BAR VALUES"
4. click "RUN QUERY"

### Expected results
when the option "STACKED BARS" was checked，the "BAR VALUES" should align on the top of bar if sum of the bar values is positive

### Actual results

when the option "STACKED BARS" was checked，the "BAR VALUES" always align on the bottom if  values of the bar exist 
negative value

#### Screenshots
<img width="316" alt="Screen Shot 2022-03-02 at 5 58 47 PM" src="https://user-images.githubusercontent.com/23090803/156340476-f5ecfe3f-f180-4ca1-8d9b-d488df8850fc.png">

<img width="306" alt="Screen Shot 2022-03-02 at 5 58 37 PM" src="https://user-images.githubusercontent.com/23090803/156340925-e7973158-892f-4d61-9c7c-fe3186763362.png">

![Screen Shot 2022-03-02 at 5 26 39 PM](https://user-images.githubusercontent.com/23090803/156340952-a49da9c5-aff7-4f17-b8f0-c2e81a8b1d9d.png)

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
I don't know where the PR is offhand, but I know this has been solved :)
