### ISSUE TITLE
Table name autocomplete broken in SQL Lab

### ISSUE THREAD

**Issue by villebro** [apache/superset#19008]
Currently table names are not added to autocomplete in SQL Lab

#### How to reproduce the bug

1. Go to SQL Lab
2. Choose the Examples database and related schema (Pubic for Postgres)
3. Check a name of a table ("Flights" should be present)
4. Type "select * from Fli" in the Editor and notice that "Flights" doesn't appear in the dropdown

### Expected results

All table names should be added to the autocomplete dropdown

### Actual results

No tables are visible in the autocomplete dropdown

#### Screenshots

In the database, we see that the table "Flights" is present:
<img width="417" alt="image" src="https://user-images.githubusercontent.com/33317356/156534052-d04dd41f-f8f1-4adc-aa85-93a9b1f67ae4.png">

 However, the table isn't available in the autocomplete dropdown:
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/33317356/156534198-c60f7c62-5289-4d6f-b5cf-013a6dfca074.png">

### Environment

(please complete the following information):

- browser type and version:
- superset version: master
- python version: Python 3.8
- node.js version: Node 16
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by kamiljune** [comment]
Same problem on master branch, rollback to 1.4.1 solved this problem.
When you doing this, pls remember to downgrade database:
`superset db downgrade 32646df09c64`
