### ISSUE TITLE
Not Able to import Saved Queries

### ISSUE THREAD

**Issue by VivekGupta97** [apache/superset#19007]
Hi everyone , Actually I want to ask about the import API of superset .
As we know the API documentation is not quite understandable of superset.  When I tried to import Saved Queries to the superset sometimes it shows Internal server error and sometimes it shows user conformation needed.
If anyone could help me to resolve this issue it will be really appreciable.
![013565a0-1fa2-43e4-9a01-f5c7d18ee53a](https://user-images.githubusercontent.com/68772150/156518266-3eaaddde-2222-45fc-82c3-800393eda159.jpg)
![96d6b7e7-64be-4c92-a1ef-9b8fccaa4386](https://user-images.githubusercontent.com/68772150/156518298-e0adbbed-ee4e-415c-ac77-6029ad9c7b0f.jpg)

**Comment by VivekGupta97** [comment]
![65085e77-8891-4739-950e-86d5b1aef852](https://user-images.githubusercontent.com/68772150/156520948-6abad801-f4cc-4071-bc10-d0d1393bf7ad.jpg)
even i tried with cmd it is not picking up

**Comment by zhaoyongjie** [comment]
Hi @VivekGupta97, are the same version of Superset instance for import&export? Which version do you use?

**Comment by rusackas** [comment]
Since this issue has gone cold, and the question about version was never answered, I'm going to go ahead and close it. @VivekGupta97 please let us know if you ever did find a solution to your problem or not, and if you're still experiencing this in newer/current version of Superset. Thanks!
