### ISSUE TITLE
[2.0] generally remove all code marked as "deprecated" (front end)

### ISSUE THREAD

**Issue by rusackas** [apache/superset#19015]
Look for comments stating that things that will be removed for, and remove them

**Comment by graceguo-supercat** [comment]
Elizabeth and I went through superset-frontend code base and found 2 deprecation candidates:

- https://github.com/apache/superset/blob/e632193eb00803594a1bbc20c2f6cb6fb29deb1f/superset-frontend/packages/superset-ui-core/src/time-format/TimeFormatterRegistrySingleton.ts#L78
in use by "OMNIBAR" feature

- https://github.com/apache/superset/blob/e6ef7da7584d6ab40ff090213b16ed0e53550ef2/superset-frontend/src/components/OmniContainer/Omnibar.tsx#L30
in use by `table`, `pivot table`, `big number` visualization.

But both of them are currently in use and no replacement code available. So we think it's not a right time to deprecate them right now.

**Comment by rusackas** [comment]
Sweep through and change any comments like "will be deprecated in 2.0" to be "will be deprecated in a future version"

**Comment by rusackas** [comment]
Consider removing Omnibar for 3.0 - @suddjian we should start 3.0 proposals board

**Comment by graceguo-supercat** [comment]
Given this discussion: https://github.com/apache/superset/pull/13305#issuecomment-812646781, we should consider remove this feature (now or 3.0)

**Comment by rusackas** [comment]
I believe that since it was already marked as deprecated in the code, it's fair game to remove as part of this initiative. That work could be part of this Issue, or filed a separate one if need be, but I have no objection to the removal as part of 2.0.
