### ISSUE TITLE
Announce native Druid NoSQL connector as no longer supported in UPDATING.MD

### ISSUE THREAD

**Issue by eschutho** [apache/superset#19028]
More details in Sips 11 and 68.

**Comment by gpmidi** [comment]
Any details about why Druid support is being deprecated? Or is it just one access method of many?

**Comment by eschutho** [comment]
It's just the native druid nosql connector that is being deprecated. Druid (through pydruid) will still be supported.

**Comment by gpmidi** [comment]
Awesome, thanks!
