### ISSUE TITLE
deck.gl scatterplot showing legend as NaN for String column

### ISSUE THREAD

**Issue by VikramKumarArammeem** [apache/superset#19036]
## Screenshot
![image](https://user-images.githubusercontent.com/90202730/156852260-a934844a-df82-4eee-a889-906a3e0d5927.png)
[drag & drop image(s) here!]

## Description
For deck.gl scatterplot case when used any string column as dimension , legend showing NaN but if we take any integer type column as dimension its showing legend name correctly.
[describe the issue here!]
For deck.gl scatterplot case when used any string column as dimension , legend showing NaN but if we take any integer type column as dimension its showing legend name correctly.

Need suggestion to work string as dimension with legend visible

**Comment by villebro** [comment]
Thanks @VikramKumarArammeem - what version are you on? I'm unable to reproduce on master: 
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/33317356/156988988-aefcbb8d-c786-42bb-8980-b1150767a860.png">

I remember having fixed something similar a long time ago, and this fix should be included in the current 1.4.1 version: https://github.com/apache-superset/superset-ui-plugins-deckgl/pull/43

**Comment by VikramKumarArammeem** [comment]
@villebro I am currently using version 1.3.2.
it would be great help if you can suggest some workaround you performed then.

**Comment by villebro** [comment]
@VikramKumarArammeem as this bug has been fixed in the current stable release, I suggest upgrading to 1.4.1.

**Comment by VikramKumarArammeem** [comment]
@villebro   We had planned to upgrade to version 1.4 but then I found this link-https://github.com/apache/superset/issues/18696.
I have to use tooltip generator in map and with this bug with 1.4 and above we decided not to update.
