### ISSUE TITLE
Not able to type comma (,) in Select component

### ISSUE THREAD

**Issue by ktmud** [apache/superset#19081]
I don't know whether it's antd doing something fishy or it's us, but I'm not able to type comma (,) in the Select component. 

This results in users not able to create new custom number formats with commas.

#### Screenshots

<img width="357" alt="image" src="https://user-images.githubusercontent.com/335541/157488199-216c1140-88fc-484a-82f1-aab95305cc52.png">

### Environment

Latest master

**Comment by MarcinZegar** [comment]
I have the same issue

**Comment by rusackas** [comment]
Seems to be working fine nowdays :D
