### ISSUE TITLE
Remove 'All' option from Show All,10, 20....200 entries in dashboard.

### ISSUE THREAD

**Issue by Narendra678** [apache/superset#19093]
Hi Team,

I need to remove All option from Show All,10, 20....200 entries.
Reason: As we have lakhs records when select 'All' page is getting stuck.

### Expected results
![image](https://user-images.githubusercontent.com/88739186/157612819-c47466bd-24d2-4158-908e-b88fc79911c5.png)

Appreciate quick response.

Regards,
Naren

**Comment by Narendra678** [comment]
we can remove with CSS templete

**Comment by titigmr** [comment]
> we can remove with CSS templete

Do you have an example?
