### ISSUE TITLE
sqllab cursor misplaced

### ISSUE THREAD

**Issue by emotschen** [apache/superset#19094]
## Screenshot
![image](https://user-images.githubusercontent.com/17001185/157632489-5384becb-3595-49a9-a221-464cfc44dee4.png)

## Description
When writing SQL through sqllab, the cursor is unknown and misplaced, which is ugly。
we use browser  is edge!

## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

**Comment by emotschen** [comment]
<img width="849" alt="企业微信截图_1646904797144" src="https://user-images.githubusercontent.com/17001185/157633153-b0f717d8-b015-477d-9521-6853519f8553.png">

**Comment by rusackas** [comment]
Assigning this to @ktmud just because they're working working on replacing this code editor, so this problem should naturally go away in due time.

**Comment by mdeshmu** [comment]
I am also facing the same issue.
Chrome Version 103.0.5060.114 (Official Build) (64-bit)
Apache Superset 1.5.1

**Comment by chintanp** [comment]
@rusackas @ktmud any updates on this? Any workarounds? The editor is pretty useless without a fix. This is happening with v2.0.0 and Chrome (104.0.5112.101) and Firefox.

**Comment by mdeshmu** [comment]
Either removing both Menlo and Lucida Console or disabling the font-family entirely solves the problem

![image](https://user-images.githubusercontent.com/57723564/188197122-2389c44a-6124-413a-a5e2-9b96438cccb9.png)

**Comment by chintanp** [comment]
Still not working well in v1.5.3

**Comment by rusackas** [comment]
I believe it's in 2.0.1.
