### ISSUE TITLE
'MSDialect_adodbapi' has no attribute 'dbapi'

### ISSUE THREAD

**Issue by filipposampligo** [apache/superset#19109]
After connecting Superset to a Trino instance (which in its turn is connected to a remote MongoDB server), I am unable to access the SQL Editor page in Superset SQL Lab.

Superset is running from `docker-compose-non-dev.yml` and Trino is running as a separate docker app based on the MongoDB-Trino implementation by [bitsondatadev/trino-getting-started](https://github.com/bitsondatadev/trino-getting-started.git).

I have edited requirements-local.txt to include `sqlalchemy-trino`.

### Expected results

I would expect to see the SQL Editor page and be able to query Trino as usual.

### Actual results

I get the following error in the docker-compose logs

`superset_app          | Unable to load dialect <class 'sqlalchemy.dialects.mssql.adodbapi.MSDialect_adodbapi'>: type object 'MSDialect_adodbapi' has no attribute 'dbapi'
superset_app            | 2022-03-10 18:21:18,084:WARNING:superset.db_engine_specs:Unable to load dialect <class 'sqlalchemy.dialects.mssql.adodbapi.MSDialect_adodbapi'>: type object 'MSDialect_adodbapi' has no attribute 'dbapi'`

#### Screenshots

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/95853439/157730779-a1a60c15-d91c-4614-b8c2-5e5245947a93.png">

### Environment

(please complete the following information):

- browser type and version: Chromium: 98.0.4758.109 (Official Build) (x86_64)
- superset version: `apache/superset:latest`
- python version: `3.8.12`
- node.js version: `v16`

**Comment by rylativity** [comment]
I'm seeing the same behavior with the exact same setup

**Comment by filipposampligo** [comment]
I believe that as a result of this bug I am getting another error when trying to reconnect to Trino

`Error: list indices must be integers or slices, not IsolationLevel`

**Comment by nikhil-kuyya** [comment]
i have facing this issue when authenticating with okta, seen this logs
`Error returning OAuth user info: missing_token:` followed by `'MSDialect_adodbapi' has no attribute 'dbapi'`

**Comment by filipposampligo** [comment]
For anyone looking for a temporary solution to being able to create custom views and explore data, I suggest connecting all your databases to Trino and saving queries as tables to use in Superset.

**Comment by TawaraKaito** [comment]
> i have facing this issue when authenticating with okta, seen this logs `Error returning OAuth user info: missing_token:` followed by `'Unable to load dialect 'sqlalchemy.dialects.mssql.adodbapi.MSDialect_adodbapi` `MSDialect_adodbapi' has no attribute 'dbapi'`.
> 
> also issue of `sqlalchemy-trino was not found` which was not coming when added the dependency in requirement-local.txt

I suddenly face a similar problem and can't login with OAuth.

**Comment by maya-harel** [comment]
which version of `sqlalchemy-trino` are you using?

**Comment by rusackas** [comment]
Looks like there are some solutions on the thread, and unanswered questions that have been open for quite some time. Closing this one out as stale with hopes that it was effectively resolved for the original authors, but if this needs revisiting/reopening, holler and we'll sort it out!
