### ISSUE TITLE
Module not found: Error: Can't resolve 'mapbox-gl/dist/mapbox-gl.css' in 'C:\Users\Admin\Downloads\LEARNING\SUPER_SET\superset-frontend\plugins\legacy-plugin-chart-map-box\src'

### ISSUE THREAD

**Issue by NithiKrishK** [apache/superset#19117]
### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by srinify** [comment]
Hey there, it looks like you're using Windows which isn't supported (even WSL isn't tested though it may work). Closing for now unless you can replicate in a Unix based environment!

**Comment by bng-src** [comment]
npm install mapbox-gl
