### ISSUE TITLE
Filter chart error when no time column

### ISSUE THREAD

**Issue by itziarmj** [apache/superset#19123]
#### How to reproduce the bug
Create a chart type filter with a dataset that has no time column.
Uncheck "date filter" in data.
Time column is empty.
When clicking on "run", the following error appear:
Unexpected error
Time column "timestamp" does not exist in dataset

### Expected results

In previous version, the filter runs without timestamp column

### Actual results

It returns an error. 

### Environment
- browser type and version:
 Chrome Version 99.0.4844.51 (Official Build) (64-bit)
Firefox 98.0 (64-bit)
- superset version: `superset version` 1.4.1
- python version: `python --version` : 3.8.12

### Checklist

- [ x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x ] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing this as a "won't fix" since the FilterBox is on a long path toward deprecation, and Dashboard Native Filters should be replacing this in day to day use. If anyone wants to go after this, we'll be happy to review PRs.
