### ISSUE TITLE
[Alert] Avoid caching charts when sending as text

### ISSUE THREAD

**Issue by chonyy** [apache/superset#19134]
Hi all, 

I have set up an alert to send a chart as text. However, the values in the chart, which is the content of the alert, sometimes are cached. It’s sending the chart value of the previous alert.
Is this an expected behavior? Ideally, whenever the alert is triggered, I would like to get the real-time value of the chart. Is there a way to guarantee to get the real-time value for every single alert?

After this [PR](https://github.com/apache/superset/pull/18795), I believe we could already bust the cache when alerting the screenshot of the dashboard. I'm looking for a similar feature that will allow the user to bust cache when sending a chart as text when alerting.

CC the contributor of the mentioned PR, @hughhhh @betodealmeida . 
Hope someone could help me look into this. Thanks 🙏

**Comment by rusackas** [comment]
@chonyy that PR from @hughhhh does sound like it did exactly what you want... busting the cache for charts in dashboards on alerts (however they're sent) if I'm interpreting correctly. Are you still facing this issue, or is this resolved by now so we can close out the fairly stale bug report (which _might_ be more of a feature request anyway)?
