### ISSUE TITLE
Superset slack reports screenshots show loading.

### ISSUE THREAD

**Issue by Shubham21k** [apache/superset#19135]
**DESCRIPTION**

<img width="1270" alt="Screenshot 2022-03-05 at 12 23 16 PM (1)" src="https://user-images.githubusercontent.com/85898765/158142690-0ae84381-4807-4000-8291-322446101ce4.png">

Hi All
We have recently upgraded to superset v1.4.0. In some slack reports, we are frequently getting these kind of screenshots where screenshot shows loading image instead of chart data. This didn't use to happen in previous versions for the same data.
Please help with this.

**Comment by agusfigueroa-htg** [comment]
Same here, did you reach out to the community already?

**Comment by rusackas** [comment]
Seems this has run a bit cold. Is anyone able to reproduce this on Superset 2.0, or shall we close it?

**Comment by Shazad-khan** [comment]
![image](https://user-images.githubusercontent.com/100838455/226520217-cafc1cb4-1010-403a-968b-6e6773aad463.png)

I have tested this in the latest version 2.1.0 and it is working as expected. please recheck it and close if resolved.

**Comment by agusfigueroa-htg** [comment]
This is great news
