### ISSUE TITLE
ImportError: cannot import name 'soft_unicode' from 'markupsafe' 

### ISSUE THREAD

**Issue by Jianghaohua** [apache/superset#19150]
add "markupsafe=2.0.1" into setup.py
` install_requires=[
        "MarkupSafe==2.0.1" # add
        "backoff>=1.8.0",
        "bleach>=3.0.2, <4.0.0",
        "cachelib>=0.4.1,<0.`

**Comment by alanorth** [comment]
On a fresh pip install of Superset 1.4.2 I get the same error. Downgrading MarkupSafe to 2.0.1 fixes it.

**Comment by rusackas** [comment]
This was bumped to 2.1.1 in https://github.com/apache/superset/pull/22355

CC @EugeneTorap for context here.

Assuming this is now resolved, and the issue seems like it's gone stale anyway. If there are still issues here, we can certainly revisit/reopen! Thank you!
