### ISSUE TITLE
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-02274: duplicate referential constraint specifications [SQL:

### ISSUE THREAD

**Issue by adrianpostoaca** [apache/superset#19237]
#### How to reproduce the bug

1. Download apache/superset image
2. Extend the image with cx_Oracle + Oracle instantclient_21_5
3. Start docker run -d -p 8080:8088 --name superset apache/superset
4. Connect to container and update SQLALCHEMY_DATABASE_URI with Oracle connection string into /app/superset/config.py
6. Execute docker exec -it superset superset db upgrade
7. Receive error:

INFO  [alembic.runtime.migration] Running upgrade  -> 4e6a06bad7a8, Init
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
cx_Oracle.DatabaseError: ORA-02274: duplicate referential constraint specifications

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/superset", line 33, in <module>
    sys.exit(load_entry_point('apache-superset', 'console_scripts', 'superset')())
		.............................
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-02274: duplicate referential constraint specifications
[SQL:
CREATE TABLE metrics (
        id INTEGER NOT NULL,
        metric_name VARCHAR2(512 CHAR),
        verbose_name VARCHAR2(1024 CHAR),
        metric_type VARCHAR2(32 CHAR),
        datasource_name VARCHAR2(255 CHAR),
        json CLOB,
        description CLOB,
        PRIMARY KEY (id),
        FOREIGN KEY(datasource_name) REFERENCES datasources (datasource_name),
        FOREIGN KEY(datasource_name) REFERENCES datasources (datasource_name)
)

From what we noticed, same column reference is reference twice.

**Comment by villebro** [comment]
Hi @adrianpostoaca - unfortunately only MySQL and Postgres are officially supported as metadata backends. You are of course welcome to try to use an Oracle instance as a metadata backend and we're happy to receive PRs to improve support for this if it doesn't break support for MySQL and Postgres, but the Superset project will not make any guarantees that this will be supported going forward.

**Comment by villebro** [comment]
Having said that, it does appear that this line is redundant: https://github.com/apache/superset/blob/b5e9fad11a2146c471c7f27d88cc425d928f94dd/superset/migrations/versions/4e6a06bad7a8_init.py#L170 as it's already declared a few lines above: https://github.com/apache/superset/blob/b5e9fad11a2146c471c7f27d88cc425d928f94dd/superset/migrations/versions/4e6a06bad7a8_init.py#L165 . Feel free to open a PR removing that - if it passes CI I'm sure we can merge it.

**Comment by adrianpostoaca** [comment]
Hi @villebro 

Thank you for your quick feedback.

We've made the change proposed, cleaned Oracle DB schema and run again "docker exec -it superset superset db upgrade". 
The above ORA-02274 was fixed but unfortunately we encountered another issue:

INFO  [alembic.runtime.migration] Context impl OracleImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 4e6a06bad7a8, Init
INFO  [alembic.runtime.migration] Running upgrade 4e6a06bad7a8 -> 5a7bad26f2a7, empty message
~~~~~~~~~~~~~
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00904: : invalid identifier
[SQL:
CREATE TABLE query (
        id INTEGER NOT NULL,
        client_id VARCHAR2(11 CHAR) NOT NULL,
        database_id INTEGER NOT NULL,
        tmp_table_name VARCHAR2(256 CHAR),
        tab_name VARCHAR2(256 CHAR),
        sql_editor_id VARCHAR2(256 CHAR),
        user_id INTEGER,
        status VARCHAR2(16 CHAR),
        name VARCHAR2(256 CHAR),
        schema VARCHAR2(256 CHAR),
        sql CLOB,
        select_sql CLOB,
        executed_sql CLOB,
        limit INTEGER,
        limit_used SMALLINT,
        select_as_cta SMALLINT,
        select_as_cta_used SMALLINT,
        progress INTEGER,
        rows INTEGER,
        error_message CLOB,
        start_time NUMERIC(20, 6),
        changed_on DATE,
        end_time NUMERIC(20, 6),
        PRIMARY KEY (id),
        FOREIGN KEY(database_id) REFERENCES dbs (id),
        FOREIGN KEY(user_id) REFERENCES ab_user (id),
        CHECK (limit_used IN (0, 1)),
        CHECK (select_as_cta IN (0, 1)),
        CHECK (select_as_cta_used IN (0, 1))
)
~~~~~~~~~~~~~~~~~~~~
Apparently, "rows" is reserved word in Oracle DB and cannot be used in DDL statement.
Thank you

**Comment by mgorsk1** [comment]
I've submitted a PR to facilitate this @adrianpostoaca - feel free to test it. It's linked to this issue.

**Comment by rusackas** [comment]
The PR seems to have died off, and I'm not sure if this is still an issue in the current era of Superset/Oracle.

Closing this as stale since it's been silent for so long, and hasn't ben corroborated by others. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a new PR to address the problem.
