### ISSUE TITLE
Error returning OAuth user info: missing_token due to AuthLib V1.0.0

### ISSUE THREAD

**Issue by JZ6** [apache/superset#19255]
The latest AuthLib breaks Oauth, returns the "Error returning OAuth user info: missing_token".
Downgrading back to authlib==0.15.5 fixes this error and allows SSO to work again.

#### How to reproduce the bug

1. Setup Google Oauth
2. Install Authlib 1.0.0
3. Try to login
4. See Error returning OAuth user info: missing_token

### Expected results

Login via google SSO keeps working.

### Actual results

Latest AuthLib releases throws a missing_token error.

#### Screenshots

![image](https://user-images.githubusercontent.com/10971263/159022342-2223774a-8881-4ec2-bc0f-fb46a7e341ed.png)

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: `1.4.0` 
- python version: `3.9.7`
- node.js version: `16.9.0`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Is this still an issue on 2.0.1?

**Comment by longtomjr** [comment]
I can confirm that it is still an issue on on the latest dev docker build. (At 2023-03-30)

**Comment by longtomjr** [comment]
I have tested this again. It does not seem to be an issue anymore. Just note that it does not work if using:
`          'server_metadata_url': 'https://accounts.google.com/.well-known/openid-configuration',`

The URLs have to be manually defined.

**Comment by rusackas** [comment]
Thanks @longtomjr!
