### ISSUE TITLE
Week-based time grains not working with databricks engine since spark 3.0

### ISSUE THREAD

**Issue by jleute** [apache/superset#19260]
#### How to reproduce the bug

1. Use databricks engine "Databricks Interactive Cluster" with Spark 3.0 or larger
2. Create Time-series Bar Chart
3. Select "Week" as Time Grain and run the query
4. See the following error:
`'*java.lang.IllegalArgumentException:All week-based patterns are unsupported since Spark 3.0, detected: u, Please use the SQL function EXTRACT instead:312:21', `

### Environment

- browser type and version: not relevant 
- superset version: docker apache/superset:1.4.1
- python version: 3.8.12
- node.js version: node:16
- any feature flags active: DASHBOARD_CROSS_FILTERS, ENABLE_TEMPLATE_PROCESSING, DASHBOARD_RBAC, VERSIONED_EXPORT

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by srinify** [comment]
Hey @jleute can you also share the query that Superset has generated (should be in the CLI output, or in your log files) and sent to Databricks Interactive Cluster?

I want to confirm that `DATE_TRUNC('week')` is the problem, as suggested in `superset/db_engine_specs/databricks.py`:

https://github.com/apache/superset/blob/master/superset/db_engine_specs/databricks.py#L30

**Comment by jleute** [comment]
It looks like the problem was already fixed 10 days ago. We are using the latest release, which generates a different query:
`date_format(date_sub(`date`, CAST(7-from_unixtime(unix_timestamp(`date`), 'u') as int)), 'yyyy-MM-dd 00:00:00')`
