### ISSUE TITLE
Native Filter can't work when face NULL value or empty string

### ISSUE THREAD

**Issue by zhaoyongjie** [apache/superset#19264]
Native Filter can't work when facing NULL value or an empty string, and this behavior is not consistent with explore page. 

https://user-images.githubusercontent.com/2016594/159150669-a4cb27cf-9049-4caa-b983-b18ab5d69d1a.mov

#### How to reproduce the bug
1. make a temporary table with a single text column by database client or SQLLab
```SQL
create table testing_empty_string(
  name varchar(255)
);
insert into testing_empty_string
values
  (null),
  (''),
  ('foo');
```
2. create a dataset from above table
3. create a chart and dashboard from above dataset
4. create a Native Filter from the dashboard 
5. got error when select `<NULL>` on dashboard
6. got an empty placeholder when select `<empty string>` on dashboard
7. got an error when select `<NULL>` on explore

### Expected results

1. Native filter should work with NULL
2. Native filter should show <empty string> when got a empty string
3. filter should work with NULL on explore page

### Actual results

Native filter can't work when facing NULL or Empty string

### Environment

- browser type and version: latest Firefox
- superset version:  current master branch(d645579cd)

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
Repro'd, thanks for reporting!

**Comment by michael-s-molina** [comment]
Fixed by https://github.com/apache/superset/pull/19326
