### ISSUE TITLE
Labels in the Dataset cannot be displayed normally in the Gauge Chart. 

### ISSUE THREAD

**Issue by ChunshengZhao** [apache/superset#19281]
- superset version: `[1.4.1](https://pypi.org/project/apache-superset/1.4.1/)`

![图片](https://user-images.githubusercontent.com/9263377/159254876-c8380e15-2685-4c7c-99cc-1820cc0e202b.png)

Always show column names:
![图片](https://user-images.githubusercontent.com/9263377/159254917-67c099ae-56e9-41da-bd47-54c6206eb8aa.png)

**Comment by ChunshengZhao** [comment]
The same problem is in PivotTable v2.
![图片](https://user-images.githubusercontent.com/9263377/160611459-d6719109-ec91-453f-890f-d2328bb1d536.png)

**Comment by BeckersJ** [comment]
Yes we have the same lissue on superset v2.0.0
![bug_superset_gauge_name_label](https://user-images.githubusercontent.com/96041225/188086990-879f5fa7-ddeb-4a23-a942-dc80a22a5959.png)

**Comment by rusackas** [comment]
Is anyone facing this in 3.x?

**Comment by rusackas** [comment]
Closing as stale, but happy to revisit/reopen if anyone is facing this in 4.x
