### ISSUE TITLE
Annotation line chart color cannot be changed 

### ISSUE THREAD

**Issue by fuxiaodun** [apache/superset#19299]
When use line chart as an annotation, I cannot set color of the annotation.
#### How to reproduce the bug

1. Go to Explore Chart, chart type select Time-series line chart
2. Click on Annotation Layers
3. In Edit Annotation Layer, select Time Series as layer type, Line Chart as Annotation Source, select a Line chart.
4. In Display Configuration, choose a color, click Apply and Run Query
5. See error, annotation color is not changed

### Expected results

The annotation color is as you choose

### Actual results

The color never change to your selected color

#### Screenshots

https://user-images.githubusercontent.com/22674597/159418102-26a02612-932e-4448-803e-fbb478c6a10f.mp4

### Environment

- browser type and version: Chrome Version 99.0.4844.51 (Official Build) (64-bit)
- superset version: 1.4.0

**Comment by zuzana-vej** [comment]
We have gotten different but potentially related bug reported; Specifically on e-chart time series chart. When there are multiple annotation lines, users can't define the colors (not even in dashboard metadata). This seems like a feature parity before migration to e-charts.
<img width="831" alt="Screen Shot 2022-04-11 at 2 46 06 PM" src="https://user-images.githubusercontent.com/61221714/162838935-467f15ef-7291-4830-b61b-8dd38ad124f2.png">
<img width="389" alt="Screen Shot 2022-04-11 at 2 46 11 PM" src="https://user-images.githubusercontent.com/61221714/162838945-2c8a83b1-657a-465e-81e6-093a91310e04.png">

**Comment by fuxiaodun** [comment]
Actually I was using only one single line not multiple lines in the annotation. And all other configuration like Style, Opacity, Width can work just except for Color. So shall I wait for further update on the migration?

**Comment by zuzana-vej** [comment]
@fuxiaodun maybe someone else is better to answer your question (not me) - I just reported similar. bug basically commenting here instead of opening new ticket. 

@yousoph? I know this is echart related - any right person to tag here?

**Comment by stephenLYZ** [comment]
@fuxiaodun @zuzana-vej  Hi, late to the party. I have opened a [PR](https://github.com/apache/superset/pull/19758) for this issue. And please feel free to @ me If you have any questions about echart.

**Comment by rusackas** [comment]
Looks like this issue didn't get closed with the linked/merged PR. Closing, but holler if this needs a revisit for any lingering issues.
