### ISSUE TITLE
slug is ignored when importing a dashboard

### ISSUE THREAD

**Issue by ndbu** [apache/superset#19336]
#### How to reproduce the bug

1. Create a new dashboard, and in the properties add a slug for it
2. Export this dashboard into a JSON file
3. Verify that the JSON file contains the slug
4. Delete the newly created dashboard
5. Now import the dashboard via the UI or superset import-dashboards
6. Go to the properties of this dashboard

### Expected results

The slug should be imported again

### Actual results

The slug is empty

### Environment

(please complete the following information):

- browser type and version: Chrome 99.0.4844.82
- superset version: latest apache/superset container
- python version: 3.8.12
- node.js version: v16.14.2

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by ndbu** [comment]
This is a test to validate:

https://user-images.githubusercontent.com/6776270/159863291-f256f24b-d18a-42b7-a315-4bb3a8be54ac.mp4

**Comment by srinisubramanian** [comment]
I did report this issue and was suggested to try the new import mechanism with Feature Flag VERSIONED_EXPORT set to true.  While the slug works, there are other issues with that.  See #19297

**Comment by rusackas** [comment]
@ndbu a few questions to triage this issue, since it's been a while:
1) is this still an issue in newer versions of Sueprset, e.g. 2.0.1?
2) Have you tried using the `VERSIONED_EXPORT` flag as suggested to work around the issue?

Hoping the answer to one of those would suffice to close the issue.

**Comment by ShaliniIruvuru** [comment]
This is working as Expected.
![Screenshot from 2023-03-16 12-05-09](https://user-images.githubusercontent.com/115684419/225534896-b14fd6c3-8825-4cca-accc-290239c481e1.png)


https://www.loom.com/share/07b16c10d70a4909a9dd27b5658de245
