### ISSUE TITLE
docs: tiny: Closing backticks and plain text appear inside code block

### ISSUE THREAD

**Issue by kaapstorm** [apache/superset#19330]
## Screenshot

![image](https://user-images.githubusercontent.com/708421/159699392-9c03e944-f4aa-4fcd-958c-4b5eeffaba32.png)

## Description

A tiny issue in **CONTRIBUTING.md**: A code block is opened with four backticks, attempted to be closed with three backticks, and then a second code block is opened with three backticks and closed with four. The result is that the three backticks appear inside the code block as code, along with a line of plain text.

**Comment by srinify** [comment]
Good catch! Closing this issue and approving your PR!
