### ISSUE TITLE
Unexpected return from SQLLab query -- no column names

### ISSUE THREAD

**Issue by rgresino** [apache/superset#19375]
![image](https://user-images.githubusercontent.com/7713938/160221578-07abfb50-50fc-477c-a3c1-cbd2943a775d.png)

I expect SELECT column names, but get the first row of data in SQLab while querying from Clickhouse? 
apache-superset        0.38.1
SQLAlchemy             1.3.24
SQLAlchemy-Utils       0.36.8
clickhouse-driver      0.2.0
clickhouse-sqlalchemy  0.1.6

**Comment by tclwh** [comment]
这个问题好像出现了好久，一直没有被解决，我用的superset1.4.1版本也是这个问题

**Comment by haimingOu** [comment]
I have the same problem

**Comment by rusackas** [comment]
Just checking in... are you still experiencing this in newer versions of Superset, e.g. 2.0.1 or current `master`?

**Comment by rusackas** [comment]
Since we're now on 3.1, on the verge of 4.0, we're not supporting 2.x  or prior versions actively. If anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)
