### ISSUE TITLE
Frontend cannot be build

### ISSUE THREAD

**Issue by 9en9i** [apache/superset#19385]
#### How to reproduce the bug

1. Clone master
2. Run docker-compose up
3. Scroll down container logs superset-node

### Expected results

Frontend was build

### Actual results

Frontend was not build and container has stopped

#### Screenshots

<img width="626" alt="image" src="https://user-images.githubusercontent.com/44907258/160272319-2d848f78-db27-4259-acb9-6acd14665523.png">

### Environment

- os: macos 12.3 (m1)
- superset version: `5ae7e549` / `0.0.0dev`
- docker version: `Docker version 20.10.13, build a224086`

### Checklist

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
If this is indeed an M1 chip issue, I think it's safe to say that this has been resolved by now, as we have a lot of folks at Preset using these machines on the day to day. If I'm mistaken, and anyone is still seeing this in 2.0.1 or newer, let's revisit/reopen.
