### ISSUE TITLE
Table Column Max Width

### ISSUE THREAD

**Issue by stevetracvc** [apache/superset#19382]
**Is your feature request related to a problem? Please describe.**
Sometimes the text for a cell can be really long. It'd be nice to be able to control the maximum width of the column instead of just the minimum width. 

**Describe the solution you'd like**
One option would be to truncate the cell entirely (as per linked PR), and display the whole cell's value upon hovering.

**Describe alternatives you've considered**
Another option could be to restrict the max width of the column and then just wrap the text, but with really long values, this could lead to a row of data taking up tens of lines or more in the table.

**Additional context**
PR linked

**Comment by sup** [comment]
+1

**Comment by rusackas** [comment]
The PR was merged forever ago, but the issue never got closed. Thanks for the contribution!
