### ISSUE TITLE
Ability to Group Charts And Dashboards via Tags or Folders

### ISSUE THREAD

**Issue by kevinpostlewaite** [apache/superset#19398]
### Discussed in https://github.com/apache/superset/discussions/19194

<div type='discussions-op-text'>

<sup>Originally posted by **kevinpostlewaite** April 15, 2020</sup>
**Is your feature request related to a problem? Please describe.**
It's difficult to find specific charts and dashboards that I've created.

**Describe the solution you'd like**
As a user, I would like to be able to logically group my charts and my dashboards. I would like either folders or to be able to filter by tags when accessing the list of charts and dashboards.

**Additional context**
This was originally an issue submitted in April 2020. It was recently and inexplicably converted to a discussion, I am resubmitting it as an issue.

This is a much requested feature with many closed issues:
- [Allow users to tag dashboards](https://github.com/apache/incubator-superset/issues/3821) from November, 2017
- [Folder structure for dashboard and slice](https://github.com/apache/incubator-superset/issues/4055) from December, 2017
- [Organising Charts List](https://github.com/apache/incubator-superset/issues/7367) from April, 2019
- [Group Dashboards folders or tags](https://github.com/apache/incubator-superset/issues/7239) from April, 2019
- [Ability to Tag Charts for Easy Filtering](https://github.com/apache/incubator-superset/issues/7968)

There's even a PR but it appears that it may need to be rewritten to be accepted:
[Tagging frontend](https://github.com/apache/incubator-superset/pull/7418#pullrequestreview-251214308)

</div>

**Comment by francescomucio** [comment]
In a big organization with multiple teams using the same BI tool, folders will provide a way to organize our dashboards and provide a better user experience (less confusion).

The global search functionality solves a different kind of problem

**Comment by rascasse83** [comment]
Preset has the concept of "workspaces" which could help with this requirement.
Superset would benefit from something similar, even if it is not a workspace, but rather a folder structure.
Alternatively, we could place a web based reporting catalog on top of superset, to have a additional layer of categorisation & security (using the new embedded dashboard functionality, or even the query URL parameter &standalone=true technique).

**Comment by vietvudanh** [comment]
[Metabase's Collections](https://www.metabase.com/docs/latest/exploration-and-organization/collections) is a good way to manage dashboards and queries too.
Structure dashboards and charts into folders make authorization much easier too.

**Comment by goldjee** [comment]
Agree, object grouping is a must for a large BI product. Given that a dashboard usually consists of several charts, the full list of them gets bloated as well. Say, you have 10 dashboards with 4 charts per dashboard on average. That's 40 charts. Quite a big list. Working alongside with other departments on the same instance of Superset becomes unnecessarily complicated because of that.

**Comment by MaslikovEgor** [comment]
In company we have lots of charts and dashboards in different segments. So tags of folder grouping is really what we interesting in and waiting for! 

Hope someone will implement this feature

**Comment by LeoDiep** [comment]
is there any update on Folder grouping of dashboard yet, cause we are desperately needing it

**Comment by juanchristensen** [comment]
In other platforms you create Dashboards -> Charts -> Queries, which intrinsically means there is partitioning of the entities.
Given that in Superset the model is inverted (Datasets -> Charts -> Dashboards), this feature request seems extremely necessary for any medium to large sized organization.

Not having a basic capability for grouping entities (datasets, charts, dashboards, and potentially columns/metrics as well), takes you down on an unsustainable road where the whole partitioning depends on naming convention and search.

**Comment by raags** [comment]
Tags via `TAGGING_SYSTEM` seem to have been merged recently: https://github.com/apache/superset/pull/20876

**Comment by michael-s-molina** [comment]
Closing this as tags have been implemented.

**Comment by hverlin** [comment]
`TAGGING_SYSTEM` is still marked as in development. Is it safe to use?
https://github.com/apache/superset/blob/master/RESOURCES/FEATURE_FLAGS.md#in-development

I see that there are some issues such as this one: https://github.com/apache/superset/issues/28020
