### ISSUE TITLE
Slack invite link broken in README

### ISSUE THREAD

**Issue by MCBoarder289** [apache/superset#19396]
When trying to join the community Slack linked in the README, you receive a page with the following message:
```
This link is no longer active
To join this workspace, you’ll need to ask the person who originally invited you for a new link.
```

#### How to reproduce the bug

1. Go to 'README.md'
2. Click the "[Join our community's Slack](https://join.slack.com/t/apache-superset/shared_invite/zt-uxbh5g36-AISUtHbzOXcu0BIj7kgUaw)" link
3. See error

### Expected results

Get an invite to the Slack community

### Actual results

Get an inactive link error message

### Environment

(please complete the following information):

- Chrome 99.0.4844.84
- superset version: `master` branch
- python version: N/A
- node.js version: N/A
- any feature flags active: no

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Seems similar to this older issue: https://github.com/apache/superset/issues/8613

**Comment by srinify** [comment]
Thanks @MCBoarder289 for the catch! I will fix this ASAP
