### ISSUE TITLE
DASHBOARD_RBAC and ENABLE_ACCESS_REQUEST are incompatible

### ISSUE THREAD

**Issue by xneg** [apache/superset#19405]
**Is your feature request related to a problem? Please describe.**
We want to use role based access for our dashboards but also we want to use granter role so that some group of user (dashboard creators) could give access to their dashboards to other users.
Now it is impossible cause [endpoint `dashboard`](https://github.com/apache/superset/blob/d304849b46b39bb6a261b735b7ca658962bc31e0/superset/views/core.py#L1942) where a check for `ENABLE_ACCESS_REQUEST` parameter is made has also check decorator `@check_dashboard_access`.
Inside this decorator there is a check for `DASHBOARD_RBAC`:

```
if is_feature_enabled("DASHBOARD_RBAC"):
    try:
        current_app.appbuilder.sm.raise_for_dashboard_access(dashboard)
    except DashboardAccessDeniedError as ex:
        return on_error(self, ex)
    except Exception as exception:
        raise exception
```
So the user's request simply doesn't make it to `ENABLE_ACCESS_REQUEST` and returned with excpetion `You don't have access to this dashboard.`

**Describe the solution you'd like**
I'm not sure if it will help but maybe we can add additional condition in `check_dashboard_access` [decorator](https://github.com/apache/superset/blob/d304849b46b39bb6a261b735b7ca658962bc31e0/superset/utils/decorators.py#L88) like this
```
if is_feature_enabled("DASHBOARD_RBAC") and not is_feature_enabled("ENABLE_ACCESS_REQUEST"):
```

**Describe alternatives you've considered**
Maybe I didn't understand how RBAC works and if it is compatible with requesting access. But still we need for dashboard creators to grant access to their dashboards to definite group of users and somehow manage this group.

**Comment by rusackas** [comment]
This issue has gone a bit cold, but judfing by the emoji, you aren't/weren't alone! Assigning to @eschutho and @jinghua-qa in hopes that we can repro/validate/triage this issue. @xneg If you find that newer versions of Superset (i.e. `master` or 2.0.x) miraculously solve this, let us know and we'll close the issue. Thanks!

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
