### ISSUE TITLE
Getting an error while installing superset using pip

### ISSUE THREAD

**Issue by swapniljariwala** [apache/superset#19433]
#### How to reproduce the bug
```
git clone git@github.com:your-username/superset.git
cd superset
python3 -m venv venv # setup a python3 virtualenv
source venv/bin/activate
# Install external dependencies
pip install -e .
```
### Expected results
Normal installation

### Actual results
Installation failing

```python
ERROR: Could not find a version that satisfies the requirement sqloxide==0.1.15 (from apache-superset) (from versions: 0.1.0, 0.1.1)
ERROR: No matching distribution found for sqloxide==0.1.15
```

### Environment

No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

### Additional context

Probable issue:
in `setup.py`
```python
 install_requires=[ ....
                     "sqloxide==0.1.15",
           ]
```
The said version of sqloxide is not available on pypi

**Comment by swapniljariwala** [comment]
This is probably due to older Python version 3.7, I'll close it if version upgrade fixes it

**Comment by srinify** [comment]
Yeah I would try 3.8!

**Comment by swapniljariwala** [comment]
Tried with 3.8, still facing issue,

I am in docker dev environment. Looks like debian container.

**Comment by kakoni** [comment]
@swapniljariwala Are you running your docker env on M1 Mac? (Or generally on ARM based platform)?
Looks like sqloxide (see this issue https://github.com/wseaton/sqloxide/issues/108) isn't currently releasing aarch based wheels.

**Comment by patrickchoi** [comment]
Also have this problem on Ubuntu 18.04.6 LTS, not running docker or on an M1 mac

Had to downgrade to 1.4.2

**Comment by Khalizo** [comment]
@swapniljariwala I got it to work by installing python 3.9.8. I'm using a Mac though - macOS Big Sur, Version 11.6.6

**Comment by MeganBeckett** [comment]
I have had the same issue on Ubuntu 20.04.4 LTS. I tried with various versions of python (3.8 and 3.9), but had to downgrade to using 1.4.2 as @patrickchoi suggested.

**Comment by zzmg** [comment]
I encountered this error on python 3.8.12

**Comment by harrychristianx** [comment]
I am on MacOS Monterey 12.5 running on a Macbook Pro M1 and encountered this issue on superset 2.0.0

Whenever I build the repository, I always gets stuck on 6/6 stating that:
`ERROR: No matching distribution found for sqloxide==0.1.17`

What solved my issue is forcing docker to run linux/amd64 with the command "`DOCKER_DEFAULT_PLATFORM=linux/amd64 docker-compose build`"

**Comment by DaiZack** [comment]
Using a ARM server on Oracle, tried "DOCKER_DEFAULT_PLATFORM=linux/amd64 docker-compose build"

And 

install with pip latest and 0.34.0, 0.34.1 none of them work

**Comment by lazuardi21** [comment]
yes this happen to me with ERROR: No matching distribution found for sqloxide==0.1.15 (from apache-superset==1.5.1)

**Comment by developersteve** [comment]
> I am on MacOS Monterey 12.5 running on a Macbook Pro M1 and encountered this issue on superset 2.0.0
> 
> Whenever I build the repository, I always gets stuck on 6/6 stating that: `ERROR: No matching distribution found for sqloxide==0.1.17`
> 
> What solved my issue is forcing docker to run linux/amd64 with the command "`DOCKER_DEFAULT_PLATFORM=linux/amd64 docker-compose build`"

Yeah this fixed the same issue was having too

**Comment by rusackas** [comment]
Sounds like this one was resolved, and we're no longer supporting Superset <3.x anyway, so I'll close this. If it's still an issue, I would suggest opening a new one with updated context.
