### ISSUE TITLE
Error when fetch saved queries

### ISSUE THREAD

**Issue by PaulKov** [apache/superset#19449]
#### How to reproduce the bug

1. Go to superset/welcome/
2. See error

Error message:
![image](https://user-images.githubusercontent.com/74862786/160931718-07fec5ca-f302-4c98-9fb7-de17e859fbda.png)

Failed api request in web developer tools:
![image](https://user-images.githubusercontent.com/74862786/160933749-0cbfc4cb-1891-491d-a10f-9c890088945e.png)

Response to failed API request: {"message":"Filter column: owners not allowed to filter"}.

### Environment

- superset version: apache/superset:latest-dev (installed using docker-compose)
- python version: 3.8.12

**Comment by villebro** [comment]
Fixed by #19372
