### ISSUE TITLE
SQL Lab - Blank window after selecting Table to query in

### ISSUE THREAD

**Issue by vdobes** [apache/superset#19459]
SQL Lab error when accessing SQL query. There is only a blank white view with no SQL query editor view.

#### How to reproduce the bug

1. Go to SQL Lab -> SQL Editor
2. Select Databse, Scheme, and Table to query

### Expected results

There should be a Query editor window

### Actual results

There is only a blank white view with no query editor. You must clear the browser cache, to get working at least the main SQL Lab view.

#### Screenshots

Here is the video of this bug:
https://user-images.githubusercontent.com/12327524/161045918-9e92da0d-6a3a-47c2-aea1-aca560dd2fd6.mp4

The only error whats dev console shows:
![image](https://user-images.githubusercontent.com/12327524/161046370-d4090efa-28d0-464a-b0a5-99c055e7c6d7.png)

### Environment

- browser type and version: All kind of browsers on latest version
- superset version: latest docker-compose version with Redis cache
- any feature flags active:
    "DASHBOARD_NATIVE_FILTERS": True,
    "ENABLE_TEMPLATE_PROCESSING": True,

**Comment by rusackas** [comment]
I think the lack of corroborated reports of this issue for upward of a year points to it being a fluke of some sort. I'll optimistically close this out, but if you're still facing this issue as of Superset 2.0.1 or later, we can certainly revisit/reopen.
