### ISSUE TITLE
Superset adds numeric suffix to some table field names

### ISSUE THREAD

**Issue by sergun** [apache/superset#19468]
#### How to reproduce the bug

I just executed SELECT * from ser_greedy_21 query in SQL lab
But Superset adds numeric suffix to some table field names and shows error:
oracle error: ORA-00904: xxx: invalid identifier

### Expected results

Table preview filled.
Output with results.
No error messages.

### Actual results
Table preview filled. OK
Output with results. OK
No error messages. FAIL. There is error message (see the screenshot)

Looks like superset uses modified table name. It adds some numeric suffix

#### Screenshots

![image](https://user-images.githubusercontent.com/15171173/161089395-ba217b4c-11ef-49af-b93c-99481925cad6.png)

### Environment

(please complete the following information):

- browser type and version: Chrome: 99.0.4844.51 
- superset version: apache/superset:latest from dockerhub installed through docker-compose-non-dev.yml today (do not have access ti the version)
- Oracle Database 19c

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any. Don't have access to logs
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
It seems there's a little pile of Oracle bugs piling up. Hopefully we can find someone with an Oracle DB to help repo/troubeshoot this. In the meantime, can you confirm this is still an issue in 2.0.1 or on `master`?

**Comment by mohimirza** [comment]
@rusackas  I'm facing similar issue with Oracle in master. I think#15752 pull request was supposed to fix it but it hasn't. 

Screenshot:
![image](https://user-images.githubusercontent.com/8817713/216618907-db46f3eb-4f23-454d-96c1-e22ad8fce9a8.png)

**Comment by rpysz** [comment]
@rusackas Yes, issue still exists in 2.0.1
![image](https://user-images.githubusercontent.com/125353602/226373749-8f28644b-626f-4d9d-a89a-9637e5c0843f.png)

**Comment by rusackas** [comment]
It's been another year (well, basically). I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
