### ISSUE TITLE
Install Elasticsearch db engine in kubernetes without helm

### ISSUE THREAD

**Issue by ciolo** [apache/superset#19469]
Hi,
I installed Superset in a Kubernetes cluster without helm. I mounted the `superset_config.py` file in a volume under `PYTHONPATH`. I connected a postgres db instance successfully. Everything is fine. 
Now I would like to connect an Elasticsearch instance. I tried to mount the `requirements_local.txt` with `elasticsearch-dbapi` inside, like README states, but it didn't work; when I try to connect with SQLALCHEMY URI and check the logs I see the message `Error: could not load database driver superset`. I tried to run `pip install elasticsearch-dbapi` inside the pod but same error appears. 
Can u help me?

**Comment by rusackas** [comment]
Given the provided answer, and the lack of follow-up for quite a while, I'll consider this one case-closed. Thanks to both of you! We can certainly revisit/reopen if this needs further discussion, of course.
