### ISSUE TITLE
Export Dashboard - Data Sources Ordering Is Volatile

### ISSUE THREAD

**Issue by pnadolny13** [apache/superset#19478]
When using the `export_dashboards` command on the CLI, everything is working great but I noticed that sometimes the order of the datasources changes in the list with no updates. I'm attempting to use the export functionality to git version my dashboard definitions and a reordering of my datasources with no changes ends up causing noise in my diffs.

#### How to reproduce the bug

1. Create dashboard with multiple data sources
2. Export dashboard
3. Make a tweak to the dashboard but dont change anything in the data sources
4. Export again and diff the files

Step 3/4 might need to be repeated a couple times as I don't know that it happens every time.

### Expected results

The export outputs should not be volatile, if I dont change a data source then there should be no diff when exporting multiple times. Exporting multiple times produces the same result always.

### Actual results

I have 2 tables in my data sources list and they switched positions without any changes.

#### Screenshots

An example of a dashboard with 1 chart. Changing the chart name from "AOV" to "AOV - New" caused a huge diff between the original and new export.

<img width="1725" alt="Screen Shot 2022-03-31 at 3 06 52 PM" src="https://user-images.githubusercontent.com/27376735/161157176-703b8dab-c25b-4659-a7e5-72d9c2d35b97.png">
<img width="1727" alt="Screen Shot 2022-03-31 at 3 07 26 PM" src="https://user-images.githubusercontent.com/27376735/161157161-37dc22d4-18eb-4572-a949-8cef7ebac476.png">
<img width="1701" alt="Screen Shot 2022-03-31 at 3 07 09 PM" src="https://user-images.githubusercontent.com/27376735/161157172-2b0f365e-9059-4211-9aaf-f7a62c7920a5.png">

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I'm wondering if using a [set in the export_dashboards](https://github.com/apache/superset/blob/ab3770667c0b11043b177838f8c2eddd717fcfcc/superset/models/dashboard.py#L370) method is causing the list reordering in inconsistent ways.

I'm happy to help implement a change! Let me know if you think thats the issue or if something else might be causing it.

**Comment by rusackas** [comment]
@pnadolny13 I'm trying to get a little attention drawn back to the PR, so we can conclude this. Thanks for opening that, byt the way, and sorry it didn't get more eyes sooner. Are you able to rebase it, so it can trigger a fresh CI run and be mergeable?

**Comment by Shazad-khan** [comment]
its working as expected now if the issue has been resolved please close the issues

**Comment by mdeshmu** [comment]
@Shazad-khan in which Superset version was this fixed?

**Comment by rusackas** [comment]
I can reopen this if the problem persists, just let me know... let's try to get that PR through if it's the real fix.
