### ISSUE TITLE
Need a way to change a forgotten password

### ISSUE THREAD

**Issue by dzar-aker** [apache/superset#19498]
**Is your feature request related to a problem? Please describe.**
When a user forgets their password, there is no way to get into the system to change it. The admin cannot change it, and the user cannot change it without logging in first.

**Describe the solution you'd like**
There are a few possible solutions:

- Have a "forgot password" link on the login screen that will allow a reset password link to be sent to the user's email address in their account. That link would let them change their password so they could reset it and then log in again.
- Allow the Admin account to do the same: send a reset password link to the user
- (Less desirable) Allow the Admin account to reset the password to a known value (as done when setting up the account in the first place). This is a security issue as it allows Admins to change passwords, then people can use the account who should not be able to, then change it, again, for example. But if the above two are not implemented, this is a solution.

**Describe alternatives you've considered**
As it stands, now, I have to delete the user account and recreate it. This works, but then I also have to set up all of the ownerships that this user had to the new account. So it's a bit of a PITA for many users.

**Additional context**
This is a necessary feature for this tool to be used in an enterprise setting (meaning allowing anyone but the user who set this up). If we allow even one user who is not an admin into the system, this will happen at some point. Guaranteed!

**Comment by jordiisidro** [comment]
The admin user can change the user's password in the menu List users -> show record.
![imatge](https://user-images.githubusercontent.com/19467312/161555568-3efb60b8-0940-4668-abda-181642631287.png)

But I prefer that users can recover or regenerate a new password without the administration support.

Regards

**Comment by dzar-aker** [comment]
Ah ha! Not sure why this is not (also?) in "Edit User," but it's not. I see it in "Show User" as noted. And I agree having the ability for the user to change this is important as mentioned.

Thank you!

**Comment by rusackas** [comment]
It might not be perfect, but it sounds like this is resolved! Thank you!

**Comment by almereyda** [comment]
"not perfect" and "confusing" are two different ways of calling this.

Would it be worth a separate issue about moving the passwort reset button over to the "Edit user" view instead?

**Comment by helpwise** [comment]
moving the passwort reset button over to the "Edit user"

Yes. View does not show the password it allows edit of the password.  Edit does not allow edit of the password it shows nothing.  I'm guessing its a little bit of "it was easier to add it to info" going on there..

**Comment by rusackas** [comment]
@almereyda @helpwise we're very open to proposals or PRs on this front. We're also open to documentation updates as well. We would certainly appreciate any help/improvements you'd want to make on either front.

**Comment by helpwise** [comment]
Happy to help. Not sure how this works.  Just came across the issue (trying to change a password) and it took two of us a few minutes to work it out..  Ended up here..  Love teh product btw :)

**Comment by ckhatton-pvfscaffolding** [comment]
> Ah ha! Not sure why this is not (also?) in "Edit User," but it's not. I see it in "Show User" as noted. And I agree having the ability for the user to change this is important as mentioned.

Thank you @dzar-aker! I was scratching my head wondering why there wasn't a reset password button when staring at the "Edit User" page 😅 I do not know why the "View User" was chosen to place the button.
