### ISSUE TITLE
Search from whole dataset not only limit rows

### ISSUE THREAD

**Issue by zhugw** [apache/superset#19497]
There is a table chart and the total count of the dataset is `1249068` , when search some keyword there is no result, but just because the keyword not exists in the 10000 rows, actually there are many rows contain this keyword.

so business want to search from whole dataset not only these 10000 rows.

Current superset version is `1.1.0` , now my plan is to develop an external Api, 
e.g.
```
http://127.0.0.1:8080/customSearch?keyword=XXX&pageNum=1&pageSize=10
```
to implement this purpose and the response as `/api/v1/chart/data?form_data=%7B%22slice_id%22%3A2%7D`

but `front-end` still met many problem e.g.
- Call external api very frequently when user input in search box
- Dynamically pagination for query result

**Comment by Narendra678** [comment]
I am also facing same issue.

**Comment by k20ameer** [comment]
@zhugw @zhugw facing same issue. Please could you suggest your solutions ?

**Comment by zhugw** [comment]
@k20ameer As mentioned in the text, explicitly developed a backend api (Java), then front-end modified the source code, when user input keyword to call backend api, and resolved ensuring problems.  In short, we modified front-end code to work around it. But you could upgrade to latest version, maybe there is an official solution.

**Comment by k20ameer** [comment]
Thank you @zhugw  for your response. The used version is  1.5.0.

**Comment by rusackas** [comment]
Since we're now on 3.1, on the verge of 4.0, we're not supporting 2.x  or prior versions actively. If anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)
