### ISSUE TITLE
Export/Import Dashboard does not import chart changes

### ISSUE THREAD

**Issue by srinisubramanian** [apache/superset#19502]
When changes are made to a dashboard and chart(s) and exported and imported the chart changes are not imported.  Only dashboard changes seem to be imported.

#### How to reproduce the bug

Create a dashboard, add a few charts and export (VERSIONED_EXPORT= True).  Import it into another instance for the first time and all changes are imported.

Make some changes to the dashboard AND to the charts.  Export and Import.  The changes to the dashboard are imported but not the changes to the charts.  Some of the changes that were not imported were:
1.  Pie chart for e.g. Emit Cross Filter
2. Big Number with trend line - Time filter, changes to filter

A simple test is to for e.g. add/change the filter for the chart.  After exporting, unzip the file and verify the Chart YAML.  The new filter is present.  Now import, the filter change is not present in the target.

### Expected results
Chart modifications are also imported

### Actual results
Only dashboard changes seem to be imported

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: 1.4.1
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:
- VERSIONED_EXPORT
- DASHBOARD_RBAC
- DASHBOARD_CROSS_FILTER

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by gbusch** [comment]
I had the same problem:
In the file "superset/dashboards/commands/importers/v1/__init__.py" there are calls to functions like import_chart, import_dataset etc. where the parameter "overwrite" is set to False.
I set them to True and it works. But this is obviously just a hack and requires you to modify the source code.

**Comment by srinisubramanian** [comment]
@villebro I know a few issues have been fixed wrt import/export and also planned for 1.5.0 .. can this issue as pointed out by @gbusch  above be looked into?

**Comment by srinisubramanian** [comment]
@villebro  Request to check if this issue that seems to be fixed in master is to be included in 1.5 as it seems to relate to overall import/export and VERSIONED_EXPORT developments.

**Comment by villebro** [comment]
AFAIK all PRs that have been merged to master as of this moment related to import/export improvements should be included in 1.5.0rc1.

**Comment by srinisubramanian** [comment]
Closing this as a more detailed issues for 1.5.0 is created #20037
