### ISSUE TITLE
[Timeseries Bar Chart] The bar colors are not coherent with other charts in a dashboard

### ISSUE THREAD

**Issue by ValentinC-BR** [apache/superset#19508]
The Timeseries bar chart colors are not harmonized with other charts (since 1.4 ?)

This might look like a mere cosmetic issue (actually, it is) but it is very annoying in a dashboard.

#### How to reproduce the bug

1. Add a timeseries bar chart to a dashboard
2. Add another chart to your dashboard, with the same legend (GROUP BY field in most charts)
3. Check colors

### Expected results

The bars have the same colors the bar chart or line chart series

### Actual results

The colors are different

#### Screenshots

![image](https://user-images.githubusercontent.com/79460908/161521939-023842ce-ac01-402c-a76f-aa677bf33535.png)

### Environment

- Browser type and version: Google Chrome Version 99.0.4844.51 (Oficial build) (x86_64)
- Superset version: 1.4.1
- Python version: 3.8.12
- Node.js version: doesn’t apply, I run on Kubernetes, using gunicorn as server
- Source : AWS Athena
- Any feature flags active: ALERT_REPORTS, ENABLE_TEMPLATE_PROCESSING, DASHBOARD_NATIVE_FILTERS

Checklist

[X] (not relevant) I have checked the superset logs for python stacktraces and included it here as text if there are any.
[X] I have reproduced the issue with at least the latest released version of superset.
[X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by ValentinC-BR** [comment]
All charts have the same definition : 
![image](https://user-images.githubusercontent.com/79460908/161522454-6a741c7f-f1a3-4bae-883f-c735061076cd.png)

**Comment by stephenLYZ** [comment]
hey @ValentinC-BR Have you tried setting the color scheme of the dashboard?

**Comment by ValentinC-BR** [comment]
I tried to choose a color scheme : Nothing changed.

What I didn't try is setting my own values in `color_labels` parameter (Edit dashboard properties/Advanced).

**Comment by rusackas** [comment]
There were a bunch of PRs around color consistency since this issue was opened. This _should_ be resolved, so I'll optimistically close it. If you apply a color theme to your dashboard in the Dashboard Properties modal, it should apply consistently across all charts. It should even carry those applied colors into the Explore context when heading into Explore from such a dashboard. Happy to revisit/reopen if there are issues you're encountering here on 2.0.1 or in `master`.
