### ISSUE TITLE
Help: How to get Pivot V2 sort by dimension?

### ISSUE THREAD

**Issue by clementchong** [apache/superset#19509]
#### How to reproduce the bug

1. Go to '...' Create Chart, Pivot V2
2. Click on '....' Select a date field into Rows. Select a metric. Try to add sort by the same date field descending.

### Expected results

The last date I have with data is 03 Apr. I would expect to see the counts by descending TranDate.

### Actual results

The sort by field expects a metric with aggregation function. If I use custom to specify only "TranDate", I get an error on duplicate field names. I changed to "DATE(TranDate)" but output is still not sorted. The SQL generated also looks incorrect with "ORDER BY `DATE(TranDate)`"

#### Screenshots

![image](https://user-images.githubusercontent.com/100477931/161522856-be7e1d8d-095a-450f-a59d-72f27f78338b.png)

### Environment

(please complete the following information):

- browser type and version: Chrome 99
- superset version: `superset version` 1.4.2
- python version: `python --version` 3.8.10
- node.js version: `node -v` 12.14.1
- any feature flags active: None

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
