### ISSUE TITLE
After restarts docker compose and server, superset using clean sqlite not postgresql with old data

### ISSUE THREAD

**Issue by tarumgod** [apache/superset#19511]
When i try to login, in superset_app i see:

`superset.db_engine_specs:Unable to load SQLAlchemy dialect <class 'pydruid.db.sqlalchemy.DruidHTTPSDialect'>: No module named 'sqlalchemy_trino'
`
postgresql base with table and data in table its ok, but apache superset using new sqlite db with admin:admin credentials

#### How to reproduce the bug

1. First start apache superset docker compose up -d
2. docker-compose down
3. restart server
4. docker-compose up -d
5. try to login with last credentials

### Expected results

login with last credentials and saw all my datas in posetgresql

### Actual results

i saw clean start with SQLite base

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [yes] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [yes] I have reproduced the issue with at least the latest released version of superset.
- [yes] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long (and hopefully you figured something out by now!). We're trying to steer toward a more actionable Issues backlog, so if people are still encountering this in current versions (currently 3.x) please open a new Issue with reproducible steps, or open a PR to address the problem.  Thanks!
