### ISSUE TITLE
Export Dashboard button cannot be hidden

### ISSUE THREAD

**Issue by Artem-fb** [apache/superset#19531]
As The problem still exists(v1.4.1) and I can't reopen my previous tikket (https://github.com/apache/superset/issues/15855), I create this one

There is no permission in roles which can hide button "EXPORT" Dashboard

Expected results
should be permission for "export" dashboard button

Actual results
there is no permission for "export" dashboard button
now permission "can read on dashboard" makes it possible to export Dashboard to json

Screenshots
http://prntscr.com/1en2xm0
http://prntscr.com/1en4qbx

How to reproduce the bug
Go to list roles create new role, add to this role only two permissions: "menu access on Dasboard"and "can read on Dashboard"
Create new user which has only this role
Create some Dashboard and give access for this user
Logout and Login as this new user
You can export dashboard to json and see sql queries for this dashboard
install 0.37.1 version, no export button will exist in dashboard menu
install 1.4.1 version this button will appear in dashboard menu

Environment
superset version: 1.4.1
python version: 3.8

**Comment by rusackas** [comment]
Hi @Artem-fb - sorry this issue's predecessor AND this issue haven't gotten more attention. We do all we can, but it's hard to keep up!

Anyway, I've confirmed that if you remove the "Can export on Dashboard" permission from a given role, then it indeed removes the action as you'd hoped for:
<img width="101" alt="image" src="https://user-images.githubusercontent.com/812905/214685212-da132b31-92d8-4e41-a8ee-97e0847cff40.png">
