### ISSUE TITLE
Error while accessing SQL Editor - 1.5.0rc1

### ISSUE THREAD

**Issue by sujiplr** [apache/superset#19547]
SQL Editor is not loading and showing only a blank screen. Below goes the stack trace. 
#### How to reproduce the bug

Click on the SQL Editor and check. This is not coming always. 

#### Screenshots

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/31705464/161924010-5a7cd247-fcb0-4cfa-bd77-ff9abe4e2cb3.png">

Unable to load dialect <class ‘sqlalchemy.dialects.mssql.adodbapi.MSDialect_adodbapi’>: type object ‘MSDialect_adodbapi’ has no attribute ‘dbapi’
2022-04-06 07:43:36,481:warning:superset.db_engine_specs:Unable to load dialect <class ‘sqlalchemy.dialects.mssql.adodbapi.MSDialect_adodbapi’>: type object ‘MSDialect_adodbapi’ has no attribute ‘dbapi’
10.0.2.215 - - [06/Apr/2022:07:43:36 +0000] “GET /superset/sqllab/ HTTP/1.1” 200 27957 

### Environment
K8 deployment. 
- superset version: 1.5.0rc1`

**Comment by sujiplr** [comment]
This is related with browser.

**Comment by sujiplr** [comment]
This might be fixing this issue as well. https://github.com/apache/superset/pull/19664

**Comment by villebro** [comment]
Closing as it's fixed by #19664
