### ISSUE TITLE
when heatmap chart is used in iframe, tooltip is hidden in the top and left

### ISSUE THREAD

**Issue by YananDong** [apache/superset#19556]
![042bb81a41d501250e91603cfcc1c8a](https://user-images.githubusercontent.com/25118843/161948564-44c3aec0-1879-4614-85aa-3b815f0adb90.png)

superset: 1.1.0
As the image shows: the heatmap is using in iframe, tooltip is hidden.

**Comment by rusackas** [comment]
Can you confirm if this is still an issue for you, particularly in newer versions of Superset, e.g. 1.5.x or 2.0.x?

**Comment by YananDong** [comment]
I'm not sure about different version. We haven't updated to a newer version yet. I corrected the code.

**Comment by Shazad-khan** [comment]
![image](https://user-images.githubusercontent.com/100838455/226319752-a0c2bc68-ec41-4a41-b40b-e5e064f1106e.png)

It is working as expected in this version 2.1.0 please recheck the issue and close it
