### ISSUE TITLE
Could not save sync column from source - Error OLD_API_CHECK_DATASET_OWNERSHIP

### ISSUE THREAD

**Issue by shalnice** [apache/superset#19568]
Hello, I tried to add new column to my dataset in superset (launch with docker-compose) using sync column from data source (postgresql). 
but when I click "Sync colum from source" the new column appears on the list, but when I clicked save, an error message appear : 
 Error **OLD_API_CHECK_DATASET_OWNERSHIP**

I tried the following things in the config.py file  and relaunch superset : 
-  changing OLD_API_CHECK_DATASET_OWNERSHIP = True to False
- remove the entire line OLD_API_CHECK_DATASET_OWNERSHIP

But I still get the same error message. Do you have any idea how to debug this ?

![image](https://user-images.githubusercontent.com/98736099/162003717-711bfa8d-c6dc-4316-b1b5-a338466b03fb.png)

- browser type and version: Chrome Version 100.0.4896.75 (Build officiel) (64 bits)
- superset version: 1.4.2
- python version: 3.9.12
- node.js version:  do not know where to check

**Comment by zhaoyongjie** [comment]
I think that this issue was fixed by [PR](https://github.com/apache/superset/pull/19452).

**Comment by rusackas** [comment]
I can't seem to reproduce this. Closing as fixed, but if you're still seeing this, we can revisit/reopen!
