### ISSUE TITLE
Adhoc filter popover simple tab on explore view does not render subject multi select if no suggestions are present

### ISSUE THREAD

**Issue by cccs-RyanS** [apache/superset#19592]
In the explore view for a dataset there are a set of conditions which causes the the subject select to not render in the adhoc filter pop over control (AdhocFilterEditPopoverSimpleTabContent) . These condition are met when a column is selected and an operator belonging to the MULTI_OPERATORS list has also been selected and no suggestions have been populated. 

I believe this to be caused by this line [here](https://github.com/apache/superset/blob/6d5771af346e1ae821b1ac0598751508265481a6/superset-frontend/src/explore/components/controls/FilterControl/AdhocFilterEditPopoverSimpleTabContent/index.tsx#L411) this seems to cause the behaviour that if you have a MULTI_OPERATOR and no suggestions the select will not render. The intention seems to be to delay rendering until suggestions are loaded, however there are cases where the suggestions will never load in some of our datasets. 

If this is not intended behaviour I would also be more than happy to take a look and attempt a fix. 
 

#### How to reproduce the bug
The bug is data source dependent but here are some steps to create a simple fake dataset that this bug will appear in 

1. SQL Lab and input a query such as `select 1 as col1, 2 as col2, 3 as col3`
2. Save this query as a virtual dataset by clicking the explore button
3. Open the dataset in the explore view 
4. click on filters to open the popover
5. select any col (col1, col2, col3) and select the IN operator
6. The multislect for the subject will not render

OR 

1. Disable suggestions on a dataset 
2. repeat steps 3-6

### Expected results

The multi select would render even if there are no suggestions loaded. 

### Actual results

The subject multi select does not render.

#### Screenshots

![Capture2](https://user-images.githubusercontent.com/71385290/162224640-d50ae2a3-1e8f-414e-878e-714adf5c8412.PNG)

### Environment

- browser: Firefox
- superset version: superset master branch and 1.5.0rc1
- python version: python 3.8.10
- node.js version: v16.13.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have not reproduced the issue with at least the latest released version of superset.  however I have reproduced it for 1.5.0rc1
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
Thanks for reporting - I was able to reproduce, working on a fix
