### ISSUE TITLE
Apache superset bypassing login mechanism

### ISSUE THREAD

**Issue by Pythonbratty** [apache/superset#19596]
Hi,

Iam still not able to bypass login of admin user from apache superset. Please let me know I tried Cypress and other autologin as well.

Help me unlock this issue 
Thanks,

**Comment by Dumisani2** [comment]
Hi

I am a learner in superset and facing a similar issue as well. I was logged in successfully by default login, i.e. username: admin and password: admin; but the next day I wasn't able to. Please help me to be able to log in and continue with my studies. 

Thanks

**Comment by MarcinZegar** [comment]
Make sure you run the  `superset db upgrade` and `superset init`  commands after starting the application. You can also create an admin role running `superset fab create-admin`

**Comment by Dumisani2** [comment]
Afternoon

Sorry I’m new on superset. I may have forgotten to mention that I’m using superset through docker, so the commands suggested below are not recognized, e.g. I’m getting error message saying “superset: command not found”. See next image: ***@***.***

**Comment by falgunifb** [comment]
can anyone please tell how to fetch value of guest token in superset_config.py file ...as in url am passing token and that token need to verify in config file so it bypass the login screen of superset for user.
http:/localhost.com:8080/login?token=1234&next=/superset/dashboard/11?standalone=true

Thanks in advance!!!!!!

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
