### ISSUE TITLE
Filter space is cut off if user is not an admin or the owner of the dashboard when no filter is specified

### ISSUE THREAD

**Issue by kevinwen2k** [apache/superset#19604]
We programed to collapse the filter by default so that user will have more space to view those graphs. We're using Superset 1.3.2.

Steps to reproduce:

1. Dashboard creator:
2. Create a dashboard without filter

Results:

1. The filter space on the left side shows up on behalf of the owner or admin user
2. The filter space on the left side is missing on behalf of a user just viewer

Expected: The filter space should remain for all of users
![non_admin_user_viewing_dashboard_without_filter](https://user-images.githubusercontent.com/4207782/162322390-d3b9df51-67ef-4b8d-acda-809ac2f0
![owner_and_admin_user_viewing_dashboard_without_filter](https://user-images.githubusercontent.com/4207782/162322451-010d0afa-8a81-4ecb-8adb-441cd52fa0a7.png)
1f69.png)

**Comment by kevinwen2k** [comment]
![non_admin_user_viewing_dashboard_without_filter](https://user-images.githubusercontent.com/4207782/162323489-91d41419-7490-4dff-96be-b8a89da4d98d.png)

**Comment by rusackas** [comment]
Unless I'm mistaken, the filter bar IS closed by default. There have also been a lot of layout improvements in that title bar (making more room!) which should also help with this sort of thing. I'll close this as resolved, but if you're still facing a problem here, we can certainly revisit/reopen.
