### ISSUE TITLE
Unable to connect Trino coordinator using SSL/LDAP

### ISSUE THREAD

**Issue by DwijadasDey** [apache/superset#19639]
Hi
I am unable to connect Trino coordinator using SSL/LDAP by using following configuration parameters.

Basic->SQLALCHEMY URI*
trino://trinouser1:password123@application.mydomain.net:8443/example/

Advanced-> Security->Secure extra
{
"connect_args":{
"auth": "ldap",
"verify": "/u01/venv/lib/python3.8/site-packages/superset/trino.pem"
}
}
![Screenshot from 2022-04-10 14-13-04](https://user-images.githubusercontent.com/12824049/162610146-25be1892-5c96-479f-9284-2961b5e71703.png)

I am getting following error:
ERROR: (builtins.AttributeError) 'str' object has no attribute 'set_http_session'
[SQL: SELECT version()]

![Screenshot from 2022-04-10 14-14-33](https://user-images.githubusercontent.com/12824049/162610237-5f89cfcc-0f21-4436-ab7f-3f186d39a318.png)

The debug logs contains following errors:

```
[SupersetError(message="(builtins.AttributeError) 'str' object has no attribute 'set_http_session'\n[SQL: SELECT version()]", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'Trino', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
2022-04-10 03:45:06,494:WARNING:superset.views.base:[SupersetError(message="(builtins.AttributeError) 'str' object has no attribute 'set_http_session'\n[SQL: SELECT version()]", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'Trino', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
2022-04-10 03:45:06,496:INFO:werkzeug:172.16.10.87 - - [10/Apr/2022 03:45:06] "POST /api/v1/database/test_connection HTTP/1.0" 422 -
```
Installed pyhive/sqlalchemy library for trino:

```
pip3 install 'pyhive[trino]'
pip3 install sqlalchemy-trino
```

There is no issue while connecting Trino coordinator in SSL mode.

`curl -v --cacert trino.pem  https://trinouser1:password123@application.mydomain.net:8443
`

Shall i need to pass some other parameters in Other->ENGINE PARAMETERS in connection settings ?

Thanks

Superset 1.4.0
Pyhive 0.6.5
sqlalchemy_trino-0.4.1

**Comment by DwijadasDey** [comment]
I need to add "http_scheme": "https" in connect_args parameter in the secure extra section to make it work!

```
{
"connect_args":{
"http_scheme": "https",
"port": "8443",
"verify": "/u01/venv/lib/python3.8/site-packages/superset/trino.pem"
}
}
```

**Comment by lipan1024** [comment]
`{
  "connect_args":{
    "http_scheme": "https",
    "verify": false
  }
}`
It worked fine when I used version 1.4.1.
When I upgraded superset to version 1.5.1, the same configuration error was reported...
`ERROR: HTTPSConnectionPool(host='xxx', port=xxx): Max retries exceeded with url: /v1/statement (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')))`

**Comment by istiyaksiddiquee** [comment]
Hi, I am getting the same issue with latest version of trino (>2.1.0). Any resolution?

**Comment by Dwijad** [comment]
Hi, I donot have Apache Superset > 2.1.0 running in my dev environment at this moment ! What i can suggest, Try to connect Trino using SSL from CLI using curl and if it succeeds then try to connect it from Superset. While connecting from Superset, get as much debug information from superset logs to pinpoint the issues.
