### ISSUE TITLE
kylin table in the database cannot be added

### ISSUE THREAD

**Issue by haimingOu** [apache/superset#19645]
hi all
After superset adds the kylin database, the table in the database cannot be added

Expected results

I can add table from kylin database

Actual results
When I added the dataset, an error message was report 'An error occurred while creating datasets: Dataset could not be created.

Screenshots
![图片1](https://user-images.githubusercontent.com/50991240/162734506-18d0bc82-aabf-4482-b4a8-37623d61d94b.png)

![图片2](https://user-images.githubusercontent.com/50991240/162734518-07d7890d-6138-4c64-8565-30017caa28a1.png)
![图片3](https://user-images.githubusercontent.com/50991240/162734529-69ab7b4d-f41d-4026-a20f-7bf2048f52b3.png)

Environment
browser type and version: chrome(100.0.4896.75)
superset version: 1.4.1
python version: 3.7.13
node.js version: /
kylin version: 3.0
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by slnxyr** [comment]
I have the same problem.

**Comment by aliakberfaiz** [comment]
facing same issue any update on this ?

**Comment by zhuanshan123** [comment]
Implementing sqla in the kylinpy plugin_ Has in dialect.py_ Table method. You can find it on kylinpy/sqla_ Found it in dialect. py

return table_name in self.get_table_names(connection, schema)

**Comment by rusackas** [comment]
@zhaoyongjie do you see any way forward with this issue? I'm tempted to close it as stale, but don't want to if it's still a valid problem, or the linked PR has a chance of merging.

**Comment by zhaoyongjie** [comment]
@rusackas this issue seems from Kylin Driver, I opened a pull request some years ago, we can close this issue, feel free reopen if needed.
