### ISSUE TITLE
Filter column: database_name not allowed to filter

### ISSUE THREAD

**Issue by lxf-lxf** [apache/superset#19655]
<img width="770" alt="image" src="https://user-images.githubusercontent.com/61101384/162849762-d0e5ba07-74b3-43d0-8574-96a17f32e1bf.png">
<img width="553" alt="image" src="https://user-images.githubusercontent.com/61101384/162849798-86d04125-72be-4bc5-a20d-07d7215a3bb9.png">
<img width="1936" alt="image" src="https://user-images.githubusercontent.com/61101384/162850874-380faa92-816f-46dc-b632-6388d7fc2269.png">

**Comment by lxf-lxf** [comment]
<img width="970" alt="image" src="https://user-images.githubusercontent.com/61101384/162850915-fe7fc6b1-c7e1-4894-b6b0-39f2097f78f2.png">

**Comment by vinhhap** [comment]
Having the same problem. Has anyone came up with a solution?

**Comment by lxf-lxf** [comment]
> Having the same problem. Has anyone came up with a solution?

I think it is an error prompt returned by the database. I don't see it in the code

PostgreSQL

**Comment by HeathLee** [comment]
same issue

**Comment by villebro** [comment]
FIx PR: #19662
