### ISSUE TITLE
Support apache doris

### ISSUE THREAD

**Issue by mzyfree** [apache/superset#19657]
**Is your feature request related to a problem? Please describe.**
Does superset support doris [https://doris.apache.org/](url)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wangyjx** [comment]
+1

**Comment by villebro** [comment]
As Doris appears to be compatible with the MySQL protocol, it should already be supported by Superset. Screenshot from homepage:

<img width="266" alt="image" src="https://user-images.githubusercontent.com/33317356/162941934-c84d5f07-1c7e-4fbe-8e38-f36b52762610.png">

Therefore closing this issue.
