### ISSUE TITLE
Regression - Echarts Bar and Line chart label values changed unexpectectly when using Group By

### ISSUE THREAD

**Issue by cwegener** [apache/superset#19654]
After #19116, the label values for Echarts Bar and Line chart (possibly more, but those are the only ones I noticed) have changed on charts that use a Group By field.

#### How to reproduce the bug

1. Install Superset from commit 375c03e08
2. Load example dataset
3. Create a new Echarts bar chart (i.e. Time-Series Bar Chart v2) using any example dataset (e.g. `cleaned_sales_data`)
4. Pick a metric for the new chart (e.g. `SUM(sales)`)
5. Pick a "Group By" field for the new chart (e.g. `status`)
6. Observe the chart labels. This is the easiest when showing the Legend.

### Expected results

The chart label values will be the values from the "Group By" field

### Actual results

The chart label values are a concatenation ("flattened") the metric key (i.e. `SUM(sales)` in my example) + ", " + the value from the "Group By" field

#### Screenshots

Behaviour at `git checkout 375c03e08`:

![image](https://user-images.githubusercontent.com/2950544/162840466-984c4e16-a85a-44b0-9173-c1297f5653a7.png)

Behaviour at `git checkout 375c03e08~`:

![image](https://user-images.githubusercontent.com/2950544/162840549-81b7da3c-8f0c-43e9-ae25-da41ffd230d8.png)

### Environment

(please complete the following information):

- browser type and version: Firefox 99
- superset version: `git checkout 375c03e08`
- python version: Python 3.10.4
- node.js version: Node v16.9.1
- any feature flags active: Default

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

NVD3 charts do not appear to exhibit this regression.

**Comment by zhaoyongjie** [comment]
This issue was fixed by #19716, so closed.
