### ISSUE TITLE
Can't set verbose name for time grain columns in a slice dropdown

### ISSUE THREAD

**Issue by ypankovych** [apache/superset#19687]
#### How to reproduce the bug

1. Go to any dashboard with a slice that has time grains
2. Click on it and see actual column names and not the verbose ones

### Expected results

I'd like to set a verbose name for each column there

### Actual results

Superset backend sends a list of tuples with 2 elements in each, those 2 elements suppose to be column name and verbose name, but there's column name * 2 (doubled): `[(column_name, column_name)]`. When I manually set the second element to its verbose version, superset UI just ignores it and by default gets the element in index 0.

#### Screenshots

here's that dropdown 

![image](https://user-images.githubusercontent.com/31005942/163145071-2427b738-e937-4532-910c-9918dba060f8.png)

### Environment

(please complete the following information):

- superset version: `1.4`
- python version: `3.6`

### Additional context

Here's why it happens. Superset sends the wrong data here: https://github.com/apache/superset/blob/6e8e29ce53faffbedfd8e9657d894d87d70eff54/superset/connectors/sqla/models.py#L745 as you can see it simply does `choicify` on it.  And here https://github.com/apache/superset/blob/6e8e29ce53faffbedfd8e9657d894d87d70eff54/superset/connectors/sqla/models.py#L683 it just returns column names without a verbose version of it

**Comment by rusackas** [comment]
There have been quite a few changes in this area since this was reported. @ypankovych can you confirm whether or not you're still facing this on `master` or in Superset 2.0.x?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
