### ISSUE TITLE
[SIP-81] Set default user to the first owner of its alert(report) schedule prior to the 'THUMBNAIL_SELENIUM_USER' value in config

### ISSUE THREAD

**Issue by jileeon** [apache/superset#19693]
### Motivation

When an alert or a report is sent by schedule, its data depends on the 'THUMBNAIL_SELENIUM_USER' value in config.
so we can't apply RLS(Row Level Security) for a specific purpose.

### Proposed Change

If an operator sets the 'THUMBNAIL_SELENIUM_USER' to None in superset_config.py, the user will be set as the first owner of its alert(report) schedule for sending an alert(or a report) by default.

### New or Changed Public Interfaces

No - As far as I know...

### New dependencies

N/A

### Migration Plan and Compatibility

N/A

### Rejected Alternatives

Improve 'Notification Method'(in a schedule setting) can support like 'Login as' feature. so just one schedule setting covers sending multiple reports with different RLS. In this case, we also have to think about the security problem.(which user can be set as a 'login as' and is it valid.)

**Comment by jileeon** [comment]
I confirmed 'EMAIL_REPORTS_USER' will be no longer exists in apache-superset 2.0.0. (in 0968f86584ba751bd665bb3e684b7aae0a28fa60).

So changing the code related to 'THUMBNAIL_SELENIUM_USER'  to achieve this.

**Comment by rusackas** [comment]
Sounds like this is a done deal then? Closing it out, but happy to revisit/reopen if I'm misconstruing things.

**Comment by jileeon** [comment]
@rusackas, This pull request(https://github.com/apache/superset/pull/21931) contains what I wanted.

It's a done deal finally.

Thanks.
