### ISSUE TITLE
Update geojson for India's map

### ISSUE THREAD

**Issue by swapniljariwala** [apache/superset#19729]
Request you to correct geojson map file of India as per latest state list

https://github.com/apache/superset/blob/master/superset-frontend/plugins/legacy-plugin-chart-country-map/src/countries/india.geojson

**Comment by shydrate** [comment]
is it updated? I still see India map not updated. How to update the map in superset instance. I have installed superset instance directly using `pip install`. Even though i get the india.geojson file from other portals, superset is not able to recognise it.

**Comment by Yaswanth-Perumalla** [comment]
@swapniljariwala  Check if this is the one you are looking for.
➡️ https://github.com/apache/superset/pull/24927

**Comment by swapniljariwala** [comment]
Yes, thanks

**Comment by swapniljariwala** [comment]
You sir are a soldier and a hero!

Not all heros wear capes..
