### ISSUE TITLE
webpack-cli throws 'Unknown option' error when using --superset arg

### ISSUE THREAD

**Issue by jdbranham** [apache/superset#19743]
#### How to reproduce the bug

1. execute the example command from - 
https://github.com/apache/superset/blob/master/CONTRIBUTING.md#webpack-dev-server  

```bash
npm run dev-server -- --superset=https://my-superset
```

### Expected results

Webpack dev server should proxy to the remote superset backend.  

### Actual results
Error is thrown -  
`[webpack-cli] Error: Unknown option '--superset=https://my-superset'`

### Environment

- browser type and version: Chrome [NA]
- superset version: `master`
- python version: `3.9.10`
- node.js version: `v16.14.2`
- any feature flags active: none

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by vivostar** [comment]
@jdbranham wow! thanks for your contribution, your patch fix my building dev enviroment problem. I think the patch should be merged into Main Branch
