### ISSUE TITLE
Wrong data plotted when using Timeshift with GROUP BY columns populated in e-charts Time Series Line Chart

### ISSUE THREAD

**Issue by pradhangn** [apache/superset#19741]
When using the new timeshift line chart with 'group by' columns, the timeshifted data has the same number for all the different groups. This works fine in the legacy line chart:

This is the correct plot using legacy line chart
![old](https://user-images.githubusercontent.com/40589807/163671946-84263ba8-a92b-4b3f-8173-5e77586a1f83.jpg)

This is the same chart in the new Time Series line chart
![new](https://user-images.githubusercontent.com/40589807/163671967-704cc9c3-da9b-43af-91e0-f9bea38c7075.jpg)

It would also be nice if the new charts had same colour but dashed type lines for the timeshifted group. It is very difficult to visually match the data otherwise.

**Comment by zhaoyongjie** [comment]
@pradhangn, this issue has been addressed by [PR](https://github.com/apache/superset/pull/19776), so closed it. If you have any questions about it, feel free to reopen the issue.
