### ISSUE TITLE
SQL Lab UI Error: Objects are not valid as a React child

### ISSUE THREAD

**Issue by EugeneTorap** [apache/superset#19746]
There are such errors in browser console.
> Uncaught Error: Objects are not valid as a React child (found: object with keys {data, query}). If you meant to render a collection of children, use an array instead.

> The above error occurred in the <defaultRenderer> component:

#### How to reproduce the bug

1. Go to SQL Lab
2. Click on 'RUN'
3. Click on 'Query history'

### Expected results

No error

### Actual results

There's error

#### Screenshots

![image](https://user-images.githubusercontent.com/29536522/163711301-a22163fe-676b-4b1d-89a8-73effeb0a02e.png)

https://user-images.githubusercontent.com/29536522/164038206-370664ac-96b6-4329-a76e-8c2fcb0e2b06.mov

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by EugeneTorap** [comment]
@rusackas @codemaster08240328 @dpgaspar @kgabryje @villebro
This #19370 PR causes this error. Should this PR revert or fix?

**Comment by EugeneTorap** [comment]
@diegomedina248 Can you check your merged #19370 PR and try to fix it

**Comment by villebro** [comment]
@EugeneTorap I believe this fixes the bug you've observed: #19664

**Comment by diegomedina248** [comment]
@EugeneTorap cannot reproduce on master.
Can you share what SQL are you running?

**Comment by EugeneTorap** [comment]
@diegomedina248 @villebro 
https://user-images.githubusercontent.com/29536522/164037916-ca556a8b-304a-4d95-9cf5-fb44e0af02e9.mov

**Comment by EugeneTorap** [comment]
@diegomedina248 Locally I have reverted your #19370 PR and the issue is resolved

**Comment by diegomedina248** [comment]
@EugeneTorap thanks for reporting! https://github.com/apache/superset/pull/19783 should fix the issue
