### ISSUE TITLE
Recently viewed Dashboards do not appear in the Recents section

### ISSUE THREAD

**Issue by VosmirkoSergey** [apache/superset#19775]
#### How to reproduce the bug

With administrator privileges, I go sequentially to several dashboards
At the same time, 2 specific dashboards are constantly displayed in the Recents section and new dashboards that I just went to do not appear

#### Screenshots
1. the initial state
![image](https://user-images.githubusercontent.com/102529439/164004225-63cd7a6b-51da-4961-bef3-35138f306b7f.png)
2.sequentially open several dashboards
![image](https://user-images.githubusercontent.com/102529439/164004429-79f6b758-db12-4d40-b30e-22c9f7c8b252.png)
3.
![image](https://user-images.githubusercontent.com/102529439/164004780-74feafa9-bee9-4f6d-948e-3b62c62c27c6.png)

In the Recents section, nothing changes

### Environment

SuperSet 1.4.1
Python 3.8.13
- node.js version: v16.14.2
Google Chrome 100.0.4896.127

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
