### ISSUE TITLE
Filters' search/user input is lost after option selection

### ISSUE THREAD

**Issue by aspedrosa** [apache/superset#19788]
## Screenshot
Native filters:
![Peek 2022-04-20 10-12](https://user-images.githubusercontent.com/23409890/164198102-a2db35fb-47eb-471d-b80c-90397f50508f.gif)

Filter box:
![Peek 2022-04-20 10-33](https://user-images.githubusercontent.com/23409890/164198438-1e221a32-6096-4fb9-b345-9cfdb3e82b93.gif)

## Description

In a situation where a filter contains a lot of options and also the "Dynamically search all filter options" option is activated, users will type in the search filter to get to the desired value. However, they might want to select multiple options from the newly updated options list. This is hard to do because: 1) using native filters the options list will reset after a given time; 2) on the filter box component the list will disappear after any option is selected. This leads to users having to retype their search to select all desired options.

**Comment by rusackas** [comment]
Having a hard time deciding if this is a bug or a feature request... but I can confirm that this still happens in the latest Superset, and it can be annoying. 

Pinging @kasiazjc in case any obvious design solution jumps out.

**Comment by josepfranquetf** [comment]
Hi @rusackas, @kasiazjc and @aspedrosa,

Any updates on this topic? 

We have tested a little bit and detected that:

- For a variable (of type: FLOAT), it has added the filter `>= {{introduced_value}}`.
- For other variables (of other types and also FLOAT), it has not applied any filters when a manual value was introduced on the filter.

Any ideas?

Thanks,
Josep

**Comment by rumbin** [comment]
I think this behaviour has now changed on 3.0.1.
Although I stumbled on this GitHub issue while looking for a bug report on the current behaviour.
I.e. I consider the 3.0.1 behaviour to be buggy.

**Comment by rtexelm** [comment]
@rusackas This issue is most likely resolved at this point

**Comment by rusackas** [comment]
Thanks all! Closing :)
