### ISSUE TITLE
Unable to run Superset using Docker - driver in requirements-local is downloading SQLAlchemy-1.4

### ISSUE THREAD

**Issue by yousoph** [apache/superset#19814]
#### How to reproduce the bug

1. Add the following in your requirements-local.txt
```
git+https://github.com/xzkostyan/clickhouse-sqlalchemy
pyhive
shillelagh
gsheetsdb
snowflake-sqlalchemy==1.2.4
```
2. Try to spin up Superset using Docker 

### Actual results
Superset is unable to spin up properly because it's using SQLAlchemy-1.4 and Superset doesn't yet work with SQLAlchemy-1.4
![image](https://user-images.githubusercontent.com/10627051/164559305-302c182b-d06a-4131-9165-028187b104c8.png)
![image](https://user-images.githubusercontent.com/10627051/164559395-79d2cc1c-896b-4edc-b894-0640c64f1282.png)

### Environment

- superset version: master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by yousoph** [comment]
Tagging @betodealmeida to add a bit more context since we looked at this together :) Thanks!!

**Comment by genzgd** [comment]
clickhouse-sqlalchemy 0.2.2 (and later) requires SqlAlchemy 1.4, while Superset up to 2.0.0 requires SQLAlchemy 1.3. I believe the latest Superset development version now supports SqlAlchemy 1.4, so one approach is to pull the latest Superset Github or docker version.

You can also try pinning clickhouse-sqlalchemy to 0.2.0 or 0.2.1.

Finally please consider https://github.com/ClickHouse/clickhouse-connect for Superset with ClickHouse, especially if you want HTTP compatibility (proxy/VPN friendly). Full disclosure, I'm the primary author.

**Comment by sfirke** [comment]
Superset now uses SQLAlchemy1.4+, after this pull request: https://github.com/apache/superset/pull/19890 so I'm going to say this is closed.

Also Superset now uses `clickhouse-connect` too 😉
