### ISSUE TITLE
docker-compose.yml error

### ISSUE THREAD

**Issue by jimmy-chow** [apache/superset#19824]
#### How to reproduce the bug

1. Use docker-compose.yml to start superset env

2. The superset_db cannot start
Exec docker logs superset_db --tail 100, we can see logs like:

ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted
ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted
ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted
ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted
ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted
ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted
ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted
ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted

### Solution

Modify the docker-compose.yml file to give root authority when creating db

![image](https://user-images.githubusercontent.com/57430215/164882273-ebfd4258-0284-46db-9d65-a73ce1eb6b22.png)

**Comment by ComeOnGetMe** [comment]
Hi have we resolved this issue properly? Now with this line added it raises the error: 
`validating /home/zhipengy/git/superset/docker-compose.yml: services.db Additional property priviledged is not allowed`

**Comment by rusackas** [comment]
Hi there, and sorry this has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and since it's been a while since this thread saw any activity, I'll close this as stale. If it is still an issue in Superset 3.x or newer, we can re-open this, or feel free to open a new issue with updated context. Thanks!
