### ISSUE TITLE
[line chart] time shift by x year showing misaligned data

### ISSUE THREAD

**Issue by tullis** [apache/superset#19880]
#### How to reproduce the bug

We have a dataset containing value counts in columns, with each row representing a month.

Plotting this data on a line chart with a specific range from 2021-01-01 to 2022-01-01 is fine.
12 values are displayed and aligned with the X-Axis correctly.

Now go to Advanced Analytics -> Time Shift -> enable one or more values of x years time shift

### Expected results

I expected to see each of the additional time shift series overlaid on the original series, without a change in alignment on the X-Axis

### Actual results

Each of these additional series is displayed offset by one month. Some go beyond December, others simply start at February.

#### Screenshots
This screenshot highlights the incorrect alignment.
![image](https://user-images.githubusercontent.com/2117946/165734241-470df2dd-ae83-44f9-a36f-215706c9f125.png)

This screen recording shows the effect when adding those time shifts.
![superset time offset issue](https://user-images.githubusercontent.com/2117946/165733999-e22c1d9e-c51d-4932-b22c-21cdfc4d14fe.gif)

### Environment

- browser type and version: Firefox 99 on Windows (but affects multiple users)
- superset version: 1.3.2 (in production) and 1.4.2 (in staging)
- python version: 3.7.3
- node.js version: 10.24.0
- any feature flags active: Don't think so
- Browser timezone UTC+1

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Here is the output from View Query
```
SELECT date_trunc('month', CAST("month" AS TIMESTAMP)) AS "__timestamp",
       sum("active_editors") AS "SUM(active_editors)"
FROM "cchen"."repo_active_editors"
WHERE "month" >= from_iso8601_timestamp('2021-01-01T00:00:00.000000')
  AND "month" < from_iso8601_timestamp('2022-01-01T00:00:00.000000')
  AND "market" = 'All'
  AND "project_family" = 'All'
GROUP BY date_trunc('month', CAST("month" AS TIMESTAMP))
ORDER BY "SUM(active_editors)" DESC
LIMIT 10000;
```
For any further context, here is our original issue: https://phabricator.wikimedia.org/T301895

**Comment by zhaoyongjie** [comment]
@tullis Could you try the Echart version `Advanced Analytics`? The NVD3 version time shift seems to have some errors.

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/2016594/165896977-0692788c-61d5-40c1-8313-5dfdde9f59c6.png">

**Comment by tullis** [comment]
@zhaoyongjie - Thanks - that workaround works for me and confirms that the issue relates to the nvd3 version. I see that there is a _deprecated_ tag on the nvd3 version too, so maybe this issue won't need to be fixed?
![image](https://user-images.githubusercontent.com/2117946/165935348-2454f981-34b5-4e91-967c-a5cbd88598fb.png)

**Comment by zhaoyongjie** [comment]
@tullis Yes, I think so. 

FYI, @evans @villebro are we considering removing the legacy NVD3 line chart?

**Comment by villebro** [comment]
@zhaoyongjie I propose deprecating all charts that are using `viz.py` in 3.0. It would be very helpful if we could get that chart migration CLI working (may require a SIP?). Also, we could also consider disabling creating new deprecated charts when there is a new version available with full feature parity.

**Comment by rusackas** [comment]
The old line chart is finally fading, and we don't seem to have this issue with new charts, so I'll go ahead and close this. Holler if this needs revisiting.
