### ISSUE TITLE
UI Issue - Access Denied error pops up on initial load even for admin user.

### ISSUE THREAD

**Issue by nijkap** [apache/superset#19884]
Hi Team,

Whenever a user logs in to superset before everything loads up for a brief period of time a "Access is Denied" error comes up below is the screen shot:

![image](https://user-images.githubusercontent.com/104574505/165771761-3651317c-aece-4a8a-9a3f-aedd45fdee02.png)

**Comment by pfinnerty** [comment]
@nijkap - I had a similar issue going on. The root cause for me was related to redirects and how I auth into superset (keycloak). How are you doing auth?

**Comment by nijkap** [comment]
> @nijkap - I had a similar issue going on. The root cause for me was related to redirects and how I auth into superset (keycloak). How are you doing auth?

we are using SSO n superset and redirect it to Dashboard URL directly by passing standalone=true

**Comment by pfinnerty** [comment]
I was linking directly to a dashboard from a separate service. So, it was not hitting the `/login` endpoint first. 

To get around that, I am linking to the dashboard with a URL like this:

`https://superset/.${TLD}/login/?next=https%3A%2F%2Fsuperset.${TLD}%2Fsuperset%2Fdashboard%2F${DASHBOARD_NAME}%2F` 

so it is hitting the `/login` endpoint first and than being redirected to the dashboard I wanted to link to.  I handle the redirect in the `/login` endpoint code.

**Comment by rusackas** [comment]
Closing this out because (a) there's a solution posted, (b) it's stale, and (c) I haven't seen any other mentions of it happening lately. Happy to re-open if anyone is still facing this.

**Comment by cwegener** [comment]
I remember that there was a PR merged in relation to this as well a little while ago ... It might be useful to find and link that PR to this issue in case anybody comes across this issue in the future

**Comment by nijkap** [comment]
We are still facing this issue for 2.0.0, the above workaround is not feasible as we might have to change at lot places and some of query string is added dynamically. Please let me know if this is fixed with 2.1.0?

**Comment by nijkap** [comment]
Please repoen if its not fixed for 2.1.0

**Comment by rusackas** [comment]
I'm not 100% sure. I'll re-open just to play it safe. Perhaps I was a bit too optimistic due to the thread being silent for a year.

**Comment by nijkap** [comment]
Issue still persist after 2.1.0 latest upgrade.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with error reproduction instructions, or raise a PR to address the problem. Thanks!

**Comment by user1500177** [comment]
@rusackas facing the same issue here , could you reopen?
