### ISSUE TITLE
Table Viz - Sorting by multiple columns no longer works

### ISSUE THREAD

**Issue by stevetracvc** [apache/superset#19919]
A recent (Dec) commit to the table viz added something for case-insensitive sorting. Unfortunately, this also broke the ability to shift-click and sort by multiple columns.

#### How to reproduce the bug

1. Explore a table (or find one in a dashboard)
2. Click on the header of an alphanumeric column to sort by that column (make sure there are multiple rows with the same value for this column, eg Video Game Sales -> Overview -> Top 10 Games table, sort by platform column)
3. Shift click on any other column to also sort by that column (eg, global_sales column)
4. See that nothing changed

### Expected results

Any rows with ties in the first column should then be sorted by the second column.

### Actual results

It only sorts by the first column

#### Screenshots

unsorted:
![table_unsorted](https://user-images.githubusercontent.com/70416691/166261682-7ff041ed-f94a-44c9-a8a2-28243d153735.png)

Sorted by Platform
![table_sortby-platform](https://user-images.githubusercontent.com/70416691/166261712-0cb384c5-a265-4179-b829-9807f3979007.png)

Sorted by Platform AND Global Sales (broken)
![table_sortby-platform-globalsales](https://user-images.githubusercontent.com/70416691/166261745-c5cfebdb-beff-4f61-9c49-ee8a3de5440b.png)

How it should sort
![table_sortby-platform-globalsales-correct](https://user-images.githubusercontent.com/70416691/166261786-42630b84-361c-4e5b-b485-02836eb64d9a.png)

### Environment

- superset version: master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
I think this was fixed but never closed. Happy to reopen if I'm misinterpreting

**Comment by LeulAria** [comment]
what's the solution here ? didn't get the context
was implementing multiple sort added


 ```tsx



 {
    ...,
    state:  {
        sorting
    }
    manualSorting: true,
    enableMultiSort: true,
    onSortingChange: setSorting
}
 ```

**Comment by stevetracvc** [comment]
@LeulAria what version of superset are you using? I wrote a fix and it was merged a couple years ago.

You have to shift + click when picking columns for the multi sort, do you have the shift key bound to some other action?
