### ISSUE TITLE
Charts description is missing while export/import dashboards

### ISSUE THREAD

**Issue by stefanocascavilla** [apache/superset#19943]
We are currently using Superset 1.4.2 (but we just checked it also with the 1.5.0 version) and we are experiencing an issue while exporting and importing a dashboard.
All the charts imported don't have the description they had before the export operation was performed. It seems the JSON file representing the dashboard doesn't carry this information.

#### How to reproduce the bug

1. Focus on a Dashboard you want, and export it (you will download the JSON file)
2. Hover on Settings and select Import Dashboards
3. Choose the JSON file you previously downloaded and select the database you want the dashboard to point to
4. Click on Upload
5. Move to the imported dashboard

### Expected results

The expected result is to have the charts in the imported dashboard with their original description.

### Actual results

The imported charts don't have the original description, it's missing.

### Environment

(please complete the following information):

- superset version: 1.4.2
- any feature flags active: We currently have the VERSIONED_EXPORT feature flag disabled.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by andreabrumana** [comment]
+1 on this!

**Comment by souvmaju-us** [comment]
+1 on this

**Comment by mattepstein23** [comment]
+1 on this as well. This would be very useful as we move dashboards between instances.

**Comment by amitagraibm** [comment]
+1 on this

**Comment by Shazad-khan** [comment]
This issue has been resolved i also tried replicating this issue but i haven't found any option to export the dashboard in json file weather it is just available with zip file so, nothing is missing in that case. Just recheck this issue once and close if fixed.

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
