### ISSUE TITLE
Gamma users can use SQL Lab by direct links

### ISSUE THREAD

**Issue by poste0** [apache/superset#19945]
A gamma user is able to open SQL Editor by the direct link.
SQL Lab menu is hidden for gamma but there are still permissions to open SQL Editor, Saved queries, Query History.

#### How to reproduce the bug

1. Copy the link to SQL Editor
2. Login as a Gamma
3. Go to the link to SQL Editor
4. SQL Editor is available

### Expected results

SQL Editor and other SQL Lab sub menus are forbidden for Gamma

### Actual results

SQL Editor and other SQL Lab sub menus are abailable for Gamma

### Environment

- browser type and version: Checked on Chrome 100.0.4896.127 and Microsoft Edge 101.0.1210.32
- superset version: The latest version built from sources on master branch
- python version: 3.8.10
- node.js version: 16.9.1
- any feature flags active: Checked on default superset from master branch

**Comment by rusackas** [comment]
@dpgaspar I would imagine this is resolved by now, but I'll leave the ball in your court :)
