### ISSUE TITLE
Pivot Table Format issue - 1.4.1 

### ISSUE THREAD

**Issue by sujiplr** [apache/superset#19955]
Facing format issue for the pivot chart. Screenshot attached, if change the zoom size of the browser +/- the format is getting corrected. 

### Actual results

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/31705464/166860934-d0cfa540-8e1b-4b9d-911b-9f234c9d4f74.png">

### Environment

(please complete the following information):

- browser type and version:
- superset version: `1.4.1`

**Comment by rusackas** [comment]
Closing this because it's stale, because it's regarding the legacy/deprecated pivot table, and because I can't seem to cause this in either the new or deprecated chart anyway. Happy to re-open if anyone is still facing this.
