### ISSUE TITLE
Timestamp literal Athena

### ISSUE THREAD

**Issue by thinhnd2104** [apache/superset#19969]
![image](https://user-images.githubusercontent.com/90733094/167061986-fce91b54-1f20-4ca4-8c29-1c46f05d407e.png)

Make sure to follow these steps before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
closed by #19970
