### ISSUE TITLE
Reports stopped working, Failed generating dataframe local variable 'response' referenced before assignment

### ISSUE THREAD

**Issue by phifa** [apache/superset#19978]
I had set up superset two days ago with compose and the non-dev configuration and set up smtp data and reporting and created a report. everything worked as expected, emails were sent. but since today the reports are not being sent, instead I receive an error message via Email:

Error Message in reports: 
`Failed generating dataframe local variable 'response' referenced before assignment`

#### How to reproduce the bug

I actually deleted the whole superset instance, removed all containers and volumes and started from scratch. Same thing, it worked for a few hours, then the error comes up and no reports are being sent. 

- i cloned the repo 
- used prod settings 
- config like below 
- `docker compose up`

### Expected results

reports are being sent 

### Actual results

reports are not being sent 

#### Screenshots

<img width="1412" alt="superset reports" src="https://user-images.githubusercontent.com/3061129/167141520-710e682d-6f04-4681-bdfd-fb498ac6248e.png">

### Environment

- browser type and version: firefox 
- superset version: Superset 0.0.0dev (d5ea537b0eb3e102677d63811b99cf2c4b31a3ab)
- python version: Python 3.8.12
- node.js version: idk, doesnt say
- any feature flags active:  superset_config_docker.py is set with these values: 

```
ENABLE_TEMPLATE_PROCESSING = True
ENABLE_JAVASCRIPT_CONTROLS = True
EMAIL_NOTIFICATIONS = True
ENABLE_SCHEDULED_EMAIL_REPORTS = True
ALERT_REPORTS_NOTIFICATION_DRY_RUN = False
SMTP is set 

```

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

```
superset_app          | 127.0.0.1 - - [06/May/2022:13:48:33 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.74.0"
superset_worker_beat  | [2022-05-06 13:49:00,050: INFO/MainProcess] Scheduler: Sending due task reports.scheduler (reports.scheduler)
superset_worker       | [2022-05-06 13:49:00,053: INFO/MainProcess] Task reports.scheduler[0ff76ece-eb1e-4c70-b4ae-55b23cda0f11] received
superset_worker       | Scheduling alert test eta: 2022-05-06 13:49:00
superset_worker       | [2022-05-06 13:49:00,068: INFO/ForkPoolWorker-7] Scheduling alert test eta: 2022-05-06 13:49:00
superset_worker       | [2022-05-06 13:49:00,071: INFO/MainProcess] Task reports.execute[075a2ff2-3463-4728-90d6-c659a8785fb6] received
superset_worker       | [2022-05-06 13:49:00,072: INFO/ForkPoolWorker-7] Task reports.scheduler[0ff76ece-eb1e-4c70-b4ae-55b23cda0f11] succeeded in 0.01864649821072817s: None
superset_worker       | Getting chart from http://superset:8088/api/v1/chart/5/data/?format=json&type=post_processed&force=false
superset_worker       | [2022-05-06 13:49:00,117: INFO/ForkPoolWorker-7] Getting chart from http://superset:8088/api/v1/chart/5/data/?format=json&type=post_processed&force=false
superset_worker       | Report state: Failed generating dataframe local variable 'response' referenced before assignment
superset_worker       | [2022-05-06 13:49:00,143: INFO/ForkPoolWorker-7] Report state: Failed generating dataframe local variable 'response' referenced before assignment
superset_worker       | [2022-05-06 13:49:00,145: INFO/ForkPoolWorker-7] Task reports.execute[075a2ff2-3463-4728-90d6-c659a8785fb6] succeeded in 0.0715110320597887s: None
superset_app          | 127.0.0.1 - - [06/May/2022:13:49:03 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.74.0"
```

The Email looks like this: 
<img width="885" alt="email" src="https://user-images.githubusercontent.com/3061129/167258599-3bba28a6-77e2-4088-b4d7-bdaf527474db.png">

**Comment by phifa** [comment]
Anybody?

**Comment by phifa** [comment]
Now tried it with v.1.5.0, but still no luck. Anybody getting the same error?

**Comment by phifa** [comment]
I created a repo to reproduce: 
https://github.com/phifa/superset_demo

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
