### ISSUE TITLE
Word cloud is blank when using custom sql series

### ISSUE THREAD

**Issue by uwine-fr** [apache/superset#19975]
When using custom sql (instead of a 'Simple' column) for a word cloud, the chart is empty. Looking at the page source, all `<text>` elements are created empty.

#### How to reproduce the bug

1. Create a word cloud chart (eg. Examples > Girl name)
2. Use a custom SQL in the `Series` field, eg. `UPPER(name)`
3. Use any metric, eg. `sum__num`

### Expected results

A word cloud!

### Actual results

A blank chart

#### Screenshots

![image](https://user-images.githubusercontent.com/52753406/167105192-d6f543ac-f533-49bd-ad74-4c1eec72635c.png)

### Environment

- browser type and version: any browser
- superset version: `1.5.0`
- python version: `3.9`
- node.js version: `v.16.15`
- any feature flags active: `ENABLE_EXPLORE_DRAG_AND_DROP, ENABLE_DND_WITH_CLICK_UX`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I had a look at the code in `superset-frontend/plugins/plugin-chart-word-cloud/src/legacyPlugin/transformProps.ts`, and I managed to get a working word cloud with the following changes - though I have no idea if it is actually the correct fix, hence did not submit a PR:

```
@@ -47,10 +47,11 @@ export default function transformProps(chartProps: ChartProps): WordCloudProps {
   } = formData as LegacyWordCloudFormData;

   const metricLabel = getMetricLabel(metric);
+  const textField = getMetricLabel(series);

   const encoding: Partial<WordCloudEncoding> = {
     color: {
-      field: series,
+      field: textField || '',
       scale: {
         scheme: colorScheme,
       },
@@ -68,7 +69,7 @@ export default function transformProps(chartProps: ChartProps): WordCloudProps {
             type: 'quantitative',
           },
     text: {
-      field: series,
+      field: textField || '',
     },
   };
```

**Comment by Shazad-khan** [comment]
This issue has been fixed so please close this issue
