### ISSUE TITLE
annotation layer data update to use plugin instead of LegacyApi

### ISSUE THREAD

**Issue by meyergin** [apache/superset#19989]
In current version, the time-series of annotation layer just support line of n3v. When I try to add canBeAnnotationTypes in other Plugins, the chart page got error 'get_viz() keyError'.  And I read the code (get_viz_annotation_data at query_context_processor.py), seems that it use LegacyAPI.
How could I switch to use new api instead of LegacyAPI viz.py?

**Comment by rusackas** [comment]
Closing this since it's been quiet for a year, but if you're still facing this, and it's still valid in 2.1.0, please ping me on [Superset Slack](http://bit.ly/join-superset-slack) or post a message in `#improving-superset` and we'll try to steer you in the right direction.
