### ISSUE TITLE
[sqllab] Array output in sqllab displays Chinese characters as utf-8 codes

### ISSUE THREAD

**Issue by michellethomas** [apache/superset#19982]
Returning an array of Chinese characters in sqllab shows up as an array of utf-8 codes. Returning the data as a string and not an array shows up fine. Downloading to CSV also has the same issue of showing up as utf-8 codes. 

#### How to reproduce the bug

1. Run a query that returns an array of Chinese characters
2. Try to view it in sqllab

### Expected results

Shows the characters correctly

### Actual results

Shows utf8 characters, when you click on the data it shows a popup window that displays the characters correctly, but when you download it to csv it shows up incorrectly.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sonfire186** [comment]
UP!

**Comment by rusackas** [comment]
Closing this in favor of https://github.com/apache/superset/issues/19388 which has a bit more context on the issue. I tried to take a crack at fixing this, but didn't have much real luck.
