### ISSUE TITLE
/api/v1/explore/form_data?tab_id=7 response 403 FORBIDDEN

### ISSUE THREAD

**Issue by wengieeee** [apache/superset#19985]
PS : we update our superset from v1.4.1 to v1.5.0，Especially the database  

`superset db upgrade`

API  /api/v1/explore/form_data?tab_id=X always error，There are no specific errors reported in the log, and debug can't get in api code ： superset.explore.form_data.api.ExploreFormDataRestApi.post

##### enter chart config page

1. Go to  chart config page
2. api  /api/v1/explore/form_data?tab_id=7  [METHOD POST] responses  403 FORBIDDEN

![image](https://user-images.githubusercontent.com/16257260/167247140-3d53cb38-ee85-4f3f-8417-6354d4bf6ecb.png)

![image](https://user-images.githubusercontent.com/16257260/167246530-4f47dc81-db31-431f-a594-02f7182e13f1.png)

#### click run 
3. Click on 'run' 
4. api /api/v1/explore/form_data?tab_id=7  [METHOD PUT] responses 405 METHOD NOT ALLOWED
![image](https://user-images.githubusercontent.com/16257260/167247173-4fc0dde0-edaf-4def-9298-ab9c20740491.png)

![image](https://user-images.githubusercontent.com/16257260/167246565-504336f8-f190-4780-b491-722b2846493c.png)

### Environment
- browser type and version: chrom
- superset version: `superset version` : 1.4.1 updated to 1.5.0
- python version: `python --version` : 3.9
- DB : mysql

**Comment by uwine-fr** [comment]
Have you run `superset init` after upgrading ? (this will update the default role and permissions)

**Comment by george-zubrienko** [comment]
Can confirm `superset init` fixes the issue.

**Comment by wengieeee** [comment]
> Can confirm `superset init` fixes the issue.

thx ,it works

**Comment by wengieeee** [comment]
> Have you run `superset init` after upgrading ? (this will update the default role and permissions)

thx ,it works
