### ISSUE TITLE
Dashboard property "Roles" not activated when feature flag DASHBOARD_RBAC set to True

### ISSUE THREAD

**Issue by klazaj** [apache/superset#19988]
I am running Superset 1.2.0 with Docker. 

According to [Superset 1.2.0 Release Notes](https://github.com/apache/superset/tree/master/RELEASING/release-notes-1-2#dashboard-level-security), "Roles" filter should be activated in Dashboard properties when the feature flag `DASHBOARD_RBAC` is set to `True`.

I set `"DASHBOARD_RBAC": True` in the [feature_flags](https://superset.apache.org/docs/installation/configuring-superset/#feature-flags) in the config file, but when I run `docker-compose up --force-recreate --build` "Roles" in Dashboard properties does not activate. It looks like so:

![superset](https://user-images.githubusercontent.com/22456202/167369386-726aaf66-29bd-44f7-94e6-6d7ab94a9f33.png)

Why isn't "Roles" activated?

**Comment by saulshao** [comment]
I have the exactly same issue

**Comment by klazaj** [comment]
@saulshao I upgraded to version 1.5.0 and it works there.

**Comment by saulshao** [comment]
I downloaded the docker image from the docker hub but it did not work.
The image on the docker hub was released about 4 hours ago(relates to this comment time), its version can't be identified.

**Comment by humbledude** [comment]
I'm using `apache/superset:1.5.0` image, and I have the same issue.

**Comment by nigzak** [comment]
same issue with 2.0.0, with pervious version 1.4.1 is worked

**Comment by lazuardi21** [comment]
is there any update for this issue? Ping @amitmiran137

**Comment by tkachuk09** [comment]
any updates on this ?

**Comment by oguzhanyediel** [comment]
> having the exact same issue with version 2.1.0 looking similar to this -- no role based access even after adding FEATURE_FLAGS = {"DASHBOARD_RBAC": True} ![image](https://user-images.githubusercontent.com/104241750/257946805-45f1a812-bde8-4924-9677-00382776b93e.png)

++ 
I have the same issue. roles box does not seem to, although enabling DASHBOARD_RBAC flag in a proper way

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
