### ISSUE TITLE
Native filter error.

### ISSUE THREAD

**Issue by thinhnd2104** [apache/superset#19984]
![image](https://user-images.githubusercontent.com/90733094/167237820-ab327efd-e68e-44a7-8d3c-ffd1eee9959e.png)

### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
There are not sufficient details or reproduction steps on this issue, and it's gone quiet for a year, so I'm closing it. If you're still facing this, please provide more details, and we can revisit/reopen. Thanks!
