### ISSUE TITLE
Fails to install on Python 3.10 because of Numpy dependency

### ISSUE THREAD

**Issue by dat-linux** [apache/superset#19986]
#### How to reproduce the bug
`
python3.10 -m pip install apache-superset`

### Expected results

Correct install

### Actual results

errors:
see screenshots

#### Screenshots

![VirtualBox_DAT LInux_07_05_2022_14_31_38](https://user-images.githubusercontent.com/99078210/167254576-c63b32d4-2cbf-4a44-a648-f61cf95cc791.png)
![VirtualBox_DAT LInux_07_05_2022_14_31_52](https://user-images.githubusercontent.com/99078210/167254578-47035105-91cc-4ede-869c-944ed5af0169.png)

### Environment

Ubuntu 22.04 with Python 3.10

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [y ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [y ] I have reproduced the issue with at least the latest released version of superset.
- [ y] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Not sure why **numpy 1.19.4** is being targeted, when the main config file stipulates **numpy=1.21.?** There must be a conflicting internal dependency via another package during the build stage.

It's potentially **pyarrow==5.0.0** causing the problem, as when try to **pip install pyarrow=5.0.0** standalone the same problem arises.

This is conmfirmed by the project.toml for pyarrow=5.0.0:

```
[build-system]
requires = [
    "cython >= 0.29",
    "numpy==1.16.6; python_version<'3.9'",
    "numpy==1.19.4; python_version>='3.9'",
    "setuptools",
    "setuptools_scm",
    "wheel"
]
```

### Recommendation

If possible, Superset's **pyarrow** dependency should be upgraded to 6.0.0:

```
[build-system]
requires = [
    "cython >= 0.29",
    "numpy==1.16.6; python_version<'3.9'",
    "numpy==1.19.4; python_version=='3.9'",
    "numpy==1.21.3; python_version>'3.9'",
    "setuptools",
    "setuptools_scm",
    "wheel"
] 
```

**Comment by applebh** [comment]
Same issue, same build, except my install was:
python3.10 -m pip install apache-superset

**Comment by dat-linux** [comment]
> Same issue, same build, except my install was: python3.10 -m pip install apache-superset

You're right, corrected.

**Comment by MerNat** [comment]
The same here. Any workaround?

**Comment by dat-linux** [comment]
> The same here. Any workaround?

I used [pyenv](https://github.com/pyenv/pyenv) to get 3.9 installed alongside 3.10 in [DAT Linux](https://datlinux.gitlab.io/). 

```
apt-get install --yes libsqlite3-dev libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libgdbm-dev lzma lzma-dev tcl-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev wget curl make build-essential python3-openssl
git clone https://github.com/pyenv/pyenv.git $HOME/skel/.pyenv
$HOME/.pyenv/bin/pyenv install 3.9.13
```

You then use 

`$HOME/.pyenv/versions/3.9.13/bin/python3 -m pip install ..`

Or, create a venv using the above python path, then call *that* python executable when in the venv.

See code here for example: https://gitlab.com/datlinux/cari-plugin-superset/-/blob/main/lib/utils.bash

**Comment by alanorth** [comment]
I was meaning to test installing Superset 2.0.0 again in a different environment to add more feedback to #20717, #20723, and #20199 (werkzeug module not found), but  now I hit this issue on Arch Linux with Python 3.10.5.

**Comment by qisoster** [comment]
It looks like it fails on collecting 'pyarrow<6.0,=5.0.0' dependency of Superset. This version of pyarrow(5.00) needs 'numpy>=1.16.6' which doesn't build of Python 3.10.

**Comment by sranjeeth** [comment]
hi, installing python 3.10 is not working so we have to downgrade python 3.9 and install it.

sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt install python3.9
python3.9 --version
python3.9 -m venv venv
sudo apt-get install python3.9-venv
python3.9 -m venv venv
. venv/bin/activate
pip install apache-superset
sudo apt-get install build-essential libssl-dev libffi-dev python3.9-dev  libsasl2-dev libldap2-dev
pip install apache-superset
superset db upgrade
#<if result = error then run below command>
	export FLASK_APP=superset 
	sudo apt install redis-server
	pip uninstall -y Werkzeug
	pip install Werkzeug==2.0.3
	superset db upgrade
	superset --version
	pip uninstall flask
	pip install flask==2.1.3
	superset db upgrade
	superset fab create-admin
	superset init 
	pip install pillow
	superset init
	superset run -p 8088 --with-threads --reload --debugger
#<else >
       export FLASK_APP=superset 
        superset fab create-admin
	superset init 
        superset run -p 8088 --with-threads --reload --debugger

**Comment by EMCP** [comment]
IMO @betodealmeida this has been closed prematurely.. not everyone can downgrade to py3.9 easily and for now my workaround is I have to back off of using Ubuntu 22.04 in favor of 20.04

**Comment by sdezza** [comment]
Did anyone found a solution apart from downgrading python? Can we reopen this?

**Comment by dat-linux** [comment]
> Did anyone found a solution apart from downgrading python? Can we reopen this?

As far as I'm aware the problem remains for python 3.10. Hopefully addressed in next release of superset.

**Comment by kant777** [comment]
This still happens with 3.10

**Comment by ramashish786** [comment]
I am facing the same issue ,stuck for hours to find solution for this but did not find any thing.
