### ISSUE TITLE
[Explore] SQL popover for calculated columns covered by columns select 

### ISSUE THREAD

**Issue by ktmud** [apache/superset#19980]
#### Screenshot

<img width="653" alt="Xnip2022-05-06_11-25-24" src="https://user-images.githubusercontent.com/335541/167197164-0ace06b5-11e1-49ec-a0e2-626029626c01.png">

#### How to reproduce the bug

1. Make sure DND feature flag is turned off
2. Go to Explore page, choose a chart with columns select
3. Hover on the calculator icon in a calculated column

### Expected results

The popover should be higher than select menu.

**Comment by rusackas** [comment]
Not sure if this is still happening, but I feel compelled to close this issue since it has gone stale, and the UI code paths in question are now deprecated.
