### ISSUE TITLE
Can not create permalink on safari browser

### ISSUE THREAD

**Issue by iercan** [apache/superset#19994]
We've just upgraded superset to 1.5.0. Our users using Safari browser reported that they are not able to create permalink on dashboard or in explore chart. I've also tested it on Safari and confirmed it is not working although it works on Chrome. 

When we click "Copy permalink to clipboard " we see below error. 
<img width="496" alt="Screen Shot 2022-05-09 at 17 26 15" src="https://user-images.githubusercontent.com/3406152/167431725-7b9d7fc9-ed60-4ada-8b89-4f786e336f89.png">

In my investigation I realized backend creates permalink successfully but somehow frontend throw this error. 

#### How to reproduce the bug

1. Open a dashboard with safari
2. Click on 'Copy permalink to clipboard'
3. See error

### Expected results

Permalink should be copied to clipboard

### Actual results

UI throws error although backend return success

### Environment

- browser type and version: Safari 14.1.2, Chrome 101
- superset version: 1.5.0 installed with apache/superset docker image
- any feature flags active:
```
    "SQLLAB_BACKEND_PERSISTENCE": True,
    "THUMBNAILS": True,
    "THUMBNAILS_SQLA_LISTENERS": True,
    "LISTVIEWS_DEFAULT_CARD_VIEW": False,
    "ALERT_REPORTS": True,
    "DASHBOARD_NATIVE_FILTERS": True,
    "DASHBOARD_CROSS_FILTERS": False,
    "DRUID_JOINS": True,
    "DASHBOARD_NATIVE_FILTERS_SET": True,
    "DASHBOARD_RBAC": True,
    "ENABLE_EXPLORE_DRAG_AND_DROP": True,
    "ENABLE_DND_WITH_CLICK_UX": True,
```

**Comment by iercan** [comment]
Also this is the error I see on javascript  console 
<img width="1338" alt="Screen Shot 2022-05-09 at 17 36 32" src="https://user-images.githubusercontent.com/3406152/167433847-a91bd7d3-ad71-4ef6-a033-8d0b36083ae8.png">

**Comment by villebro** [comment]
I was able to repro. It appears we're using the [deprecated copy command](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) which Safari no longer supports:
https://github.com/apache/superset/blob/cede148d4609a9838b6efad9ab9ba26c91af0636/superset-frontend/src/utils/copy.ts#L38

Let's replace it with the current best practice and include it in 1.5.1.
