### ISSUE TITLE
Value not available in TextAreaControl when reopen the chart control panel

### ISSUE THREAD

**Issue by PrabuSarvesan** [apache/superset#19992]
Saved text not available in control panel text area in chart control panel.

#### How to reproduce the bug

1) Create a custom plugin and add TextAreaControl in control panel.
2) Create a new chart from custom plugin and add some text in textarea.
3) Save the created chart.
4) Either refresh or open created chart and see control panel.

### Expected results

Saved text should be available in TextAreaControl as like TextControl.

### Actual results

Saved text not available.

### Environment

- browser type and version: Chrome 101.0.4951.54
- superset version: Latest
- node.js version: 16.8.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [*] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [*] I have reproduced the issue with at least the latest released version of superset.
- [*] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Its working properly in TextControl.

**Comment by ar7max** [comment]
It's cuz widget is using props.initialValue instead of props.value

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
