### ISSUE TITLE
Can't open Explore from chart (v1.5.0)

### ISSUE THREAD

**Issue by RavazziniAndrea** [apache/superset#19990]
When in a dashboard, clicking on "view chart in Explore" on any chart, result in "An error occurred while opening Explore".
The only way to enter in Explore is from the chart list (that keeps working as usual).

#### Screenshot
![exploreError](https://user-images.githubusercontent.com/74816007/167392027-f0a18ee9-135d-437b-b99e-7daf44485b6a.png)

### Environment
- browser type and version: Firefox 91.9.0esr (64-bit) & Chromium 101.0.4951.54 
- superset version: 1.5.0
- python version: 3.8.10
- node.js version: 10.19.0

Thanks

**Comment by uwine-fr** [comment]
I had the same issue when upgrading from 1.4.x to 1.5.0: it was a permission error, because I forgot to update the default permissions with:
```
# Create default roles and permissions
superset init
```

**Comment by RavazziniAndrea** [comment]
Worked! Thank you so much!

**Comment by isabellalacerda** [comment]
I already use superset init, but still can't open explore, same error message
![image](https://user-images.githubusercontent.com/102618441/177805842-3cb62487-5b34-4583-80a2-1c1f7c8e2fa8.png)

**Comment by dheerajathrey** [comment]
I am facing the same issue. I ran the following command post superset upgrade to 1.5.0 <pre>superset init</pre>

**Comment by chriswedgwood** [comment]
I have run superset init but I am still getting the same error
