### ISSUE TITLE
[reports] Dashboard title is rendered in center of email report for long dashboards

### ISSUE THREAD

**Issue by serenajiang** [apache/superset#20007]
For dashboard email reports, if the dashboard is sufficiently long, the title is inserted into the center of the dashboard screenshot.

This is cosmetic, but since the title could partially cover a chart, I think it's a bit more than just a cosmetic issue.

#### How to reproduce the bug

* Make a LONG dashboard. Ex: [dashboard_export_20220509T222033.zip](https://github.com/apache/superset/files/8655787/dashboard_export_20220509T222033.zip)
* Set up an email report
* View generated screenshot in email report: [screenshot link](https://user-images.githubusercontent.com/14146019/167509266-23b7a744-0873-4774-a81d-c3fb94de4eed.png). Note that "long test dash" (the title) was inserted in the middle.

### Expected results

No title in screenshot

### Actual results
[link to screenshot](https://user-images.githubusercontent.com/14146019/167509266-23b7a744-0873-4774-a81d-c3fb94de4eed.png)

### Environment

Up to date with master as of 2022-03-24

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
  - we are a bit behind master so it was hard to verify this for sure, but it doesn't look like there has been very much work on this so I don't thiiiink it's been fixed
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by calfzhou** [comment]
Is there any updates? Facing the same problem, and it messed up almost all our dashboard snapshots :(

**Comment by jileeon** [comment]
Hi, Can I get your dashboard example in JSON format? because I'm currently maintaining the 1.4.2 version

I'm applying a responsive email template that provides the exact image size as the dashboard for most email service providers.

Thanks.

**Comment by rusackas** [comment]
I'm pretty sure this is fixed, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
