### ISSUE TITLE
[Chart] Expanded area chart show wrong values in tooltips

### ISSUE THREAD

**Issue by ktmud** [apache/superset#20003]
#### How to reproduce the bug
1. Go to an Area chart (for example, "Top 10 Boy Name Share" in examples data)
2. Make sure "Stacked Style" is "expanded"
3. Hover on the chart, check the "value" column in tooltip

#### Screenshots

When stacked style is "expanded", the values are showing as decimals:

<img width="1019" alt="Xnip2022-05-09_11-02-18" src="https://user-images.githubusercontent.com/335541/167470280-04b72d9a-3d3e-47b3-8c4b-18508bab643d.png">

But they should be the actual values as in other stacked styles:

<img width="997" alt="image" src="https://user-images.githubusercontent.com/335541/167470248-e3859baf-d1da-4aa0-b20d-6a61c8b12dc0.png">

**Comment by ShaliniIruvuru** [comment]
When we select expand section from stacked styles ,it is showing as actual values as other stacked styles
Screenshots:-
1.When select Expand from stacked style
![image](https://user-images.githubusercontent.com/115684419/227138618-e6453dab-7539-401d-9544-c2400082d4cc.png)
2.When select Stack from stacked style
![image](https://user-images.githubusercontent.com/115684419/227138792-52582428-0559-4a50-8c38-24c71c4bc2d5.png)
Loom video:-
https://www.loom.com/share/77426dd84ec444beaeac1a221a0bb805

**Comment by michael-s-molina** [comment]
Fixed by https://github.com/apache/superset/pull/23469
