### ISSUE TITLE
Upgrading to Superset 1.5.0 via docker-compose results in Error 

### ISSUE THREAD

**Issue by klazaj** [apache/superset#20005]
I am upgrading from Superset 1.1.0 to Superset 1.5.0. 

When I run `docker-compose up`, I get this error from the superset_app container:
    
    superset_app             | Traceback (most recent call last):
    superset_app             |   File "/app/superset/__init__.py", line 21, in <module>
    superset_app             |     from superset.app import create_app
    superset_app             |   File "/app/superset/app.py", line 23, in <module>
    superset_app             |     from superset.initialization import SupersetAppInitializer
    superset_app             |   File "/app/superset/initialization/__init__.py", line 24, in <module>
    superset_app             |     from deprecation import deprecated
    superset_app             | ModuleNotFoundError: No module named 'deprecation'

When I enter the running container and check the python version with `python --version`, I get `Python 3.7.9`. This means that Python hasn't been upgraded to the version that Superset 1.5.0 has, and that the new required modules haven't been installed.

What have I missed here? I do not want to remove the current volumes and start a fresh install.

**Comment by villebro** [comment]
Did you check the docs on how to run a specific version via `docker-compose`? Namely this part:

<img width="869" alt="image" src="https://user-images.githubusercontent.com/33317356/167788801-4f4a79b3-2aac-40d7-aa13-bce1d1cab6b1.png">

Link to docs: https://superset.apache.org/docs/installation/installing-superset-using-docker-compose/#3-launch-superset-through-docker-compose

In your case it should just require running
```bash
TAG=1.5.0 docker-compose pull
TAG=1.5.0 docker-compose up
```

in the source directory of 1.5.0.

**Comment by rusackas** [comment]
We're now on 3.1, on the verge of 4.0, and not supporting 2.x  or prior versions actively. If folks are experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)
