### ISSUE TITLE
Group by filters broken in 1.5.0

### ISSUE THREAD

**Issue by cooley-pe** [apache/superset#20000]
#### How to reproduce the bug

1. Create a `Group by` Native Filter in a Dashboard in 1.5.0

### Expected results

Filters work as expected

### Actual results

The Group by filter displays an error message

#### Screenshots

<img width="776" alt="image" src="https://user-images.githubusercontent.com/64038793/167462402-ddfc44d1-de14-4ad9-8725-5e164a2229c1.png">

### Environment

(please complete the following information):

- browser type and version: Microsoft Edge Version 101.0.1210.39
- superset version: `1.5.0`
- python version: `3.8.12`
- node.js version: n/a
- any feature flags active: 
  - ENABLE_TEMPLATE_PROCESSING
  - ALERT_REPORTS
  - DASHBAORD_CROSS_FILTERS
  - DASHBARD_FILTERS_EXPERIMENTAL
  - DASHBOARD_NATIVE_FILTERS

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by betodealmeida** [comment]
(20 thousand!)

**Comment by rubypollev** [comment]
Hey, just noting this is blocking us from updating to 1.5.X

**Comment by justin-tomlinson** [comment]
This is also broken in 2.0.0 for me

**Comment by justin-tomlinson** [comment]
Noticed in the community slack that another user had fixed this in a cloned repo https://github.com/stevetracvc/superset/commit/6c90e631cccaf5c64a0f46ce5275b2c15cbcba2d#diff-5ded1ce69d8f39d6fc4a6626b4bc22be28aaaa518c35e52ad67b6274080428c8 Is this something that could be applied in the main one?

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
