### ISSUE TITLE
:ERROR:flask_appbuilder.security.sqla.manager:DB Creation and initialization failed: (psycopg2.OperationalError) FATAL:  password authentication failed for user "superset"

### ISSUE THREAD

**Issue by miracletiger** [apache/superset#20012]
when I install superset1.5 with 
get the error as follow:

A Default SECRET_KEY was detected, please use superset_config.py to override it.
> Use a strong complex alphanumeric string and use a tool to help you generate
> a sufficiently random sequence, ex: openssl rand -base64 42
> --------------------------------------------------------------------------------
> --------------------------------------------------------------------------------
> logging was configured successfully
> 2022-05-10 14:24:07,560:INFO:superset.utils.logging_configurator:logging was configured successfully
> 2022-05-10 14:24:07,562:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
> Falling back to the built-in cache, that stores data in the metadata database, for the following cache: `FILTER_STATE_CACHE_CONFIG`. It is recommended to use `RedisCache`, `MemcachedCache` or another dedicated caching backend for production deployments
> 2022-05-10 14:24:07,564:WARNING:superset.utils.cache_manager:Falling back to the built-in cache, that stores data in the metadata database, for the following cache: `FILTER_STATE_CACHE_CONFIG`. It is recommended to use `RedisCache`, `MemcachedCache` or another dedicated caching backend for production deployments
> Falling back to the built-in cache, that stores data in the metadata database, for the following cache: `EXPLORE_FORM_DATA_CACHE_CONFIG`.It is recommended to use `RedisCache`, `MemcachedCache` or another dedicated caching backend for production deployments
> 2022-05-10 14:24:07,567:WARNING:superset.utils.cache_manager:Falling back to the built-in cache, that stores data in the metadata database, for the following cache: `EXPLORE_FORM_DATA_CACHE_CONFIG`. It is recommended to use `RedisCache`, `MemcachedCache` or another dedicatedcaching backend for production deployments
> 2022-05-10 14:24:07,584:ERROR:flask_appbuilder.security.sqla.manager:DB Creation and initialization failed: (psycopg2.OperationalError) FATAL:  password authentication failed for user "superset"
> 
> (Background on this error at: http://sqlalche.me/e/13/e3q8)
> Loaded your LOCAL configuration at [/app/docker/pythonpath_dev/superset_config.py]

#### How to reproduce the bug

docker-compose -f docker-compose-non-dev.yml up

### Environment

centos7
superset1.5

**Comment by miracletiger** [comment]
when I download the tar from https://downloads.apache.org/superset/1.5.0/  and install superset. the error disappeared.

**Comment by thanhdo3044** [comment]
Please give me more information on how to do it

**Comment by thanhdo3044** [comment]
Please give me more information on how to do it

**Comment by rusackas** [comment]
https://superset.apache.org/docs/installation/configuring-superset#specifying-a-secret_key
