### ISSUE TITLE
the version info of superset1.5 does not update

### ISSUE THREAD

**Issue by miracletiger** [apache/superset#20020]
I download the tar package from https://downloads.apache.org/superset/1.5.0/ and install superset1.5,the version info dose not update.
![screenshot-20220511-071859](https://user-images.githubusercontent.com/17160259/167740504-cac65e7e-1a3d-4f97-98ad-e3b28dd14f21.png)

**Comment by villebro** [comment]
@miracletiger how did you install this version? When running `pip install -e .` or `pip install .` in the root of the source, the `superset/static/version_info.json` file is created which is referenced by the About menu item. It's not included in the source files as it gets created during build/installation, but maybe we could consider adding it to the source distribution.

**Comment by b3nk3nobi** [comment]
I have the same problem when using superset helm.

![no_version_info](https://user-images.githubusercontent.com/1058037/171561752-fc5f257a-bfd0-4e47-9f0d-dc2fc260ccc2.png)

**Comment by wowo** [comment]
Hi, any luck with that?

**Comment by rusackas** [comment]
Since we're now on 3.1, on the verge of 4.0, we're not supporting 2.x  or prior versions actively. If anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)
