### ISSUE TITLE
execute  docker-compose -f docker-compose-non-dev.yml pull  get error  like  this

### ISSUE THREAD

**Issue by hijack-621** [apache/superset#20023]
![image](https://user-images.githubusercontent.com/82790351/167793834-1c33f5ed-a1ca-4efc-8711-0ab8d2f4096b.png)

**Comment by srinify** [comment]
Hey there @hijack-621 Docker's looking for the credentials for DockerHub and can't find them. I would do `docker login` to resolve this issue:

https://github.com/docker/docker-credential-helpers/issues/60

Closing as this isn't a Superset issue :)
