### ISSUE TITLE
[native-filter][numerical range][jinja] max value, min value and zero returns no value

### ISSUE THREAD

**Issue by michalgala** [apache/superset#20042]
When I try to get the range from the "Numerical Range" type filter from native filters, with Jinja using filter_values(), it returns:
- [-10,10]  if i choose the range -10,10 (correct)
- nothing if i choose the range from min value to 0
- nothing if i choose the range from 0 to maximum value
- [-10] if i choose the range -10,0
- [-10] if i choose the range -10 and the max value
- [-10] if i choose the range from min value to -10

The last three examples returns the same value, for three different range chosen by the user

In the following example i have a slider with -25 as min value and 9 as max

![image](https://user-images.githubusercontent.com/44247532/168069774-0fe3b149-5035-46c1-bbcd-e96bf474d28a.png)
![image](https://user-images.githubusercontent.com/44247532/168069882-4ac32f1a-39a4-4bba-9e59-f88bbad82a72.png)
![image](https://user-images.githubusercontent.com/44247532/168069928-42d513c3-3d2b-4313-96a4-ebfa9be33676.png)
![image](https://user-images.githubusercontent.com/44247532/168069963-f3a1130d-eef4-42f8-8ba6-19879b57a86b.png)
![image](https://user-images.githubusercontent.com/44247532/168070170-559ddb50-c168-4102-8db4-2895589ee99b.png)

**Comment by michalgala** [comment]
Actually using get_filters() I can distinguish between the negative and positive sides.
But i still have the confusion between, 0 and max value, or 0 and min value

![image](https://user-images.githubusercontent.com/44247532/168073051-2a7e5b29-1079-4ea1-8707-af71d24340b1.png)

**Comment by rumbin** [comment]
I just also tripped over this issue.

From a usability perspective it would be best if `filter_values("my_range_column")` always contained a two-element list.
If one of the range boundaries is undefined this should be reflected as a `None` value or so.

**Comment by rumbin** [comment]
Sharing a workaround here:

```
{#
    This is a minimum working example (MWE) of how to use the range filter slider
    with two range values.
    
    Note: 
    Use this approach only if you really need to (e.g. injecting the filter into a CTE).
    In all cases where it is sufficient to apply the filter on the 
    _whole_ dataset we let Superset do the job for us!
#}


with


dummy_table as (

    select
        *
    from (values 
        (0)
        , (1)
        , (2)
        , (4)
        , (8)
        , (16)
    ) as v(val)

)


select
    *
from dummy_table
where true

    {% for filter in get_filters('my_range') %}
        and val {{ filter.get('op') }} {{ filter.get('val') }}
    {% endfor %}

```

**Comment by rusackas** [comment]
Hopefully, the answer above is sufficient to close this thread. I'll do so anyway since it's been so long since there was a comment here. If this needs revisiting/reopening, just say the word.
