### ISSUE TITLE
Chart Error- Querying AWS Redshift Spectrum nested tables with Superset

### ISSUE THREAD

**Issue by adolitos** [apache/superset#20065]
Hi guys, I'm using Superset 1.4.0 from my Windows 10

I'm trying to create a chart using a small dataset from AWS Redshift

![image](https://user-images.githubusercontent.com/11447594/168382173-f2fa6eb7-7022-4663-bd29-0b0128da6623.png)

The yellow marked columns comes from tag_set struct column.

I can reproduce the same query on Superset SQL Lab

![image](https://user-images.githubusercontent.com/11447594/168382355-43e97adb-a3c1-4462-8a88-d081b675dd34.png)

I started getting errors when move to Chart step

![image](https://user-images.githubusercontent.com/11447594/168382486-72d77001-2b9e-4ed8-b342-411475300b20.png)

Unexpected error
Error: Spectrum nested query error DETAIL: ----------------------------------------------- error: Spectrum nested query error code: 8001 context: A subquery that refers to a nested table cannot contain ORDER BY clause. query: 0 location: nested_query_rewriter.cpp:775 process: padbmaster [pid=10014] -----------------------------------------------

I have changed the query, removing group by, order by and limit clauses... and It worked, but I'm affraid to face scenarios in future where I can get rid of this operations.

Like using ctes, subqueries, jinja templates...

Can you guys help me with that?

Regards,

André Santos

**Comment by serelk** [comment]
have similar issue

**Comment by rusackas** [comment]
> have similar issue

Can you share any details, queries, or steps to reproduce the issue?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
