### ISSUE TITLE
Missing French Translation

### ISSUE THREAD

**Issue by aehanno** [apache/superset#20060]
Issues to add french translation missing

Step : 

- [ ]  The additional French translations
- [ ] Fixing the untranslated strings
- [ ] using gettext instead of lazy_gettext
- [ ] translate variable
- [ ] translate changed_on_delta_humanized

**Comment by aehanno** [comment]
Pull Request : https://github.com/apache/superset/pull/20061

**Comment by aehanno** [comment]
Hi @villebro, I think this issue should be reopened as there are pull requests that have not been merged yet.

**Comment by villebro** [comment]
@aehanno , it appears those PRs need to be rebased. Can you do that so we can rereview and get them merged if all is well?

**Comment by aehanno** [comment]
> @aehanno , it appears those PRs need to be rebased. Can you do that so we can rereview and get them merged if all is well?

@villebro, I merge the master in the four PR but I got some errors that didn't come from my changes, do you know why ?
