### ISSUE TITLE
2 options inside top right '+' button not working

### ISSUE THREAD

**Issue by kamalkeshavani-aiinside** [apache/superset#20072]
Two new options added under 'Data' in the top right '+' button do not work.
<img width="571" alt="image" src="https://user-images.githubusercontent.com/74634977/168519163-3ee1a8c9-cc49-4c69-9519-7439d2762339.png">

#### How to reproduce the bug

1. Scroll over to '+' sign in the top-right corner to open the popup
2. Scroll to 'Data' option to open another popup
3. Click on any of first 2 options

### Expected results

The UI should move to Add Database/Google Sheet screen.

### Actual results

Nothing happens.

#### Screenshots
You can see in the gif, that there are no links associated with the 2 buttons.

![1 5_issue](https://user-images.githubusercontent.com/74634977/168519491-02ee12c8-674f-48a7-a3c1-f2142700c41a.gif)

### Environment

- browser type and version: Chrome v101
- superset version: 1.5.0
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

No error logs are seen in container.

**Comment by diegomedina248** [comment]
Hi @kamalkeshavani-aiinside, thanks for reporting this.

I'm not seeing any issues in master. Couple of questions:
* Are you seeing this with the default admin/admin user? All users?
* Can you check the console to see if there're any errors thrown?

Additionally, for context, those two buttons don't have any urls attached, they trigger a modal in place.

**Comment by kamalkeshavani-aiinside** [comment]
I am seeing this issue with Admin user in 1.5.0, running docker hub image.
I checked the container, but no error logs are seen there.

**Comment by eschutho** [comment]
We have a fix that will be going out in the next 2.0 release that I tagged to this issue.
