### ISSUE TITLE
The handlebars plugin doesn't support order

### ISSUE THREAD

**Issue by xinggit** [apache/superset#20106]
When I used the handlebars plug-in at superset 1.41, I found that it could not support data sorting. Next, I will use the example data to reproduce this problem

#### How to reproduce the bug

1. Select "message" of the example dataset in datasets page
2. Switch to handlebars chart type
3. Next, please look at my picture below

### Expected results

I expect my data to be sorted by the sort column I set

### Actual results

This sort did not take effect, and he did not build the sort data in the submitted form.Here is my form data

{"datasource":{"id":12,"type":"table"},"force":false,"queries":[{"time_range":"No filter","granularity":"bot_profile__updated","filters":[],"extras":{"time_grain_sqla":"P1D","time_range_endpoints":["inclusive","exclusive"],"having":"","having_druid":[],"where":""},"applied_time_extras":{},"columns":["team"],"metrics":["count"],"annotation_layers":[],"row_limit":10000,"timeseries_limit":0,"timeseries_limit_metric":{"expressionType":"SIMPLE","column":{"id":584,"column_name":"last_read","verbose_name":null,"description":null,"expression":null,"filterable":true,"groupby":true,"is_dttm":true,"type":"TIMESTAMP WITHOUT TIME ZONE","type_generic":2,"python_date_format":null,"is_certified":false,"certified_by":null,"certification_details":null,"warning_markdown":null},"aggregate":"COUNT","sqlExpression":null,"isNew":false,"hasCustomLabel":false,"label":"COUNT(last_read)","optionName":"metric_gjlhgpdterd_bmdgrjbzfy"},"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"groupby":["team"]}],"result_format":"json","result_type":"full"}

#### Screenshots

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/30068098/168996459-dff8609f-d632-4204-94d1-bf78967b785f.png">

### Environment

(please complete the following information):

- browser type and version: Google Chrome:101.0.4951.64
- superset version: `1.4.1`
- python version: `3.8.9`
- node.js version: `v16.13.0`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [yes] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ yes] I have reproduced the issue with at least the latest released version of superset.
- [ yes] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
@jdbranham would you have any bandwidth to take a look at this? CC @villebro 

(btw, still loving this plugin!!!!!)

**Comment by rusackas** [comment]
Sorry we still haven't gotten to this... we're aware that the handlebars plugin still needs some upkeep and bugfixes, but it's hard for some of us to give it priority... even if it does keep us up at night sometimes 😅 . We'd love to get some community help here if anyone has bandwidth.

**Comment by rusackas** [comment]
It seems lie it's working now... if anyone finds otherwise, I'm happy to reopen.
