### ISSUE TITLE
Big Number with Trendline chart chops off bottom of trendline in latest master

### ISSUE THREAD

**Issue by rea725** [apache/superset#20117]
## Screenshot
This is what we get in recent master.  Specifically, we're running this build: https://github.com/apache/superset/commit/ee178f47e1be56a90e5d7a549d5d47a5a805012f
![trendline-with-big-number-chopped](https://user-images.githubusercontent.com/276963/169102277-96421940-b65d-48f9-8ba2-ab31d4bafa9a.png)

This is what we got in our old build 
![trendline-with-big-number-working-correctly](https://user-images.githubusercontent.com/276963/169102610-48d0da83-3e9e-42cb-8aa4-0f9a6d4309db.png)
(~v1.2, commit 9c854ff):

## Description
Latest builds are truncating the bottom few pixels of the Big Number with Trendline charts, when these charts are included in a dashboard.  When the chart is maximized, the issue is still presenting itself.  If the browser window is made to be over ~1000px tall, the issue goes away.  It looks as if a padding/border is covering up the bottom x% of the chart.

**Comment by kamalkeshavani-aiinside** [comment]
This issue is also present in release version 1.5.0.

**Comment by michael-s-molina** [comment]
@stephenLYZ Any update on this?
