### ISSUE TITLE
Docker missing files

### ISSUE THREAD

**Issue by ddzobov** [apache/superset#20139]
Hello!
I'm trying to build Superset with OCP 4.8 and getting error.

Checked Dockerfile:
COPY ./requirements/*.txt ./docker/requirements-*.txt/ /app/requirements/

But there is no ./docker/requirements-*.txt/ in this repository.

**Comment by rusackas** [comment]
This is likely fixed by now, and is fairly out of date if not. If people are still encountering this in current versions (e.g 3.1+) please open a new Issue or a PR to address the problem.
