### ISSUE TITLE
Toggling chart description on in Big Number with Trendline chart pushes the chart down

### ISSUE THREAD

**Issue by irinai-code** [apache/superset#20148]
## Screenshot

Description off, dashboard view
<img width="455" alt="Pasted_Image_5_20_22__11_51_AM" src="https://user-images.githubusercontent.com/11417816/169593527-89f18df0-1196-4408-9384-17a44fa5bf20.png">

Description on, dashboard view
<img width="572" alt="Pasted_Image_5_20_22__11_52_AM" src="https://user-images.githubusercontent.com/11417816/169593673-76627105-4173-441a-ba74-a48bed7c541c.png">

## Description

Toggling chart description on in Big Number with Trendline chart pushes the chart down and hides data

## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

**Comment by rusackas** [comment]
We recently saw this, and have it in our backlog to address.

**Comment by rusackas** [comment]
Seems this was addressed, but never closed. Holler if it's an issue at all.
