### ISSUE TITLE
Big Number with Trendline coudn't work with PostgreSQL's date field

### ISSUE THREAD

**Issue by ensky** [apache/superset#20155]
Big Number with Trendline coudn't work with PostgreSQL's date field.

#### How to reproduce the bug
1. Create a table with a column which type is "date" in postgresql
2. Add that database and table as dataset to Superset
3. Try to create a Big Number with Trendline chart with that dataset
4. It shows 
```
Unexpected error
Error: '+08'
```
which +08 is the timezone about your pgsql settings

### Expected results
The chart should be draw successfully

### Actual results
```
Unexpected error
Error: '+08'
```

#### Screenshots
![image](https://user-images.githubusercontent.com/797580/169739356-3dd586ee-d942-4169-b6b6-8baf8262d39e.png)

#### Additional Error Log
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 190, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/utils/log.py", line 245, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/views/core.py", line 2351, in results
    return self.results_exec(key)
  File "/app/superset/views/core.py", line 2419, in results_exec
    obj = _deserialize_results_payload(
  File "/app/superset/views/utils.py", line 625, in _deserialize_results_payload
    df = result_set.SupersetResultSet.convert_table_to_df(pa_table)
  File "/app/superset/result_set.py", line 177, in convert_table_to_df
    return table.to_pandas(integer_object_nulls=True)
  File "pyarrow/array.pxi", line 757, in pyarrow.lib._PandasConvertible.to_pandas
  File "pyarrow/table.pxi", line 1748, in pyarrow.lib.Table._to_pandas
  File "/usr/local/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 789, in table_to_blockmanager
    blocks = _table_to_blocks(options, table, categories, ext_columns_dtypes)
  File "/usr/local/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 1130, in _table_to_blocks
    return [_reconstruct_block(item, columns, extension_columns)
  File "/usr/local/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 1130, in <listcomp>
    return [_reconstruct_block(item, columns, extension_columns)
  File "/usr/local/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 733, in _reconstruct_block
    dtype = make_datetimetz(item['timezone'])
  File "/usr/local/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 758, in make_datetimetz
    tz = pa.lib.string_to_tzinfo(tz)
  File "pyarrow/types.pxi", line 1927, in pyarrow.lib.string_to_tzinfo
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "/usr/local/lib/python3.8/site-packages/pytz/__init__.py", line 188, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: '+08'
2022-05-23 03:27:32,051:ERROR:superset.views.base:'+08'
```

### Environment
- browser type and version: any browser
- superset version: 1.5.0
- python version: 3.8.12
- any feature flags active:
  - VERSIONED_EXPORT
  - ENABLE_TEMPLATE_PROCESSING

### Checklist
- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
- This issue doesn't exists in Superset-v1.4.0

The SQL in the chart is

```sql
SELECT DATE_TRUNC('day', publish_date) AS __timestamp,
       count(*) AS count
FROM
  (SELECT publish_date
   FROM software.package_file) AS virtual_table
GROUP BY DATE_TRUNC('day', publish_date)
LIMIT 50000;
```

The error part seems to be the DATE_TRUNC function, it returns something like "2022-05-23 12:00:00+08". Which format seems to be errorly processed by pyarrow project.

Accourding to pyarrow project, the timezone format seems to be like +08:00 format, maybe it's the root cuase? https://github.com/apache/arrow/blob/apache-arrow-5.0.0/python/pyarrow/types.pxi#L1915

**Comment by villebro** [comment]
@ensky what is the datatype of `publish_date` in the `software.package_file` table?

**Comment by ensky** [comment]
@villebro It's `date` type

```
SELECT 
   table_name, 
   column_name, 
   data_type 
FROM 
   information_schema.columns
WHERE 
   table_name = 'package_file' and column_name = 'publish_date';
```

![image](https://user-images.githubusercontent.com/797580/169767810-0b8838b1-2362-41fb-ad25-97c83228c3c6.png)

**Comment by villebro** [comment]
I'm unable to repro on master: 

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/33317356/169779233-7cc0db56-8bce-479c-8cbf-befaeec50035.png">

I unfortunately don't have an instance of 1.5.0 running right now, but I can start one if needed.

Are you using a cache to store results? And can you check if you're able to view samples for the dataset?

**Comment by ensky** [comment]
@villebro I can reproduce it in SQL Lab with your reproduce step with query

```
SELECT DATE_TRUNC('day', publish_date),
       count(*) AS count
FROM
  (SELECT '2021-01-01'::date as publish_date) AS virtual_table
GROUP BY DATE_TRUNC('day', publish_date)
LIMIT 50000;
```

![image](https://user-images.githubusercontent.com/797580/169784929-43fbffb8-e364-4b7e-bba5-22d5e5ab9ff0.png)

pgsql version
PostgreSQL 12.7 (Debian 12.7-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

![image](https://user-images.githubusercontent.com/797580/169785388-d163833d-e4bd-4d61-8793-0dfb55a0342c.png)

**Comment by kamalkeshavani-aiinside** [comment]
I am facing same issue with all Time-series charts(echarts and legacy both). The issue seems to be handling of `Date` datatype in Postgres.

**Comment by kamalkeshavani-aiinside** [comment]
> I am facing same issue with all Time-series charts(echarts and legacy both). The issue seems to be handling of `Date` datatype in Postgres, casting such column to `Timestamp` solves the issue.

Seems like issue is something else. Local docker setup doesn't show issue, but kubernetes setup shows issue. I have older version of postgres in k8s, so that may be the issue.

**Comment by ensky** [comment]
> but kubernetes setup shows issue

True. Our environment is on the k8s indeed.

**Comment by michael-s-molina** [comment]
What's the Postgres version in k8s?

**Comment by ensky** [comment]
@michael-s-molina As mentioned above, it's 12.7
https://github.com/apache/superset/issues/20155#issuecomment-1134399460

**Comment by michael-s-molina** [comment]
I misunderstood 😄 , I thought that when @kamalkeshavani-aiinside commented:

> I have older version of postgres in k8s

He was already considering the previous comment and that we tested on version 12.7.

**Comment by ensky** [comment]
> It looks like an issue that popped somewhere else, and that was fixed by upgrading `psycopg2` to `2.9.1` in `requirements.txt`

I can confirm that with psycopg2=2.9.1 the problem is solved.

So it seems to be the problem about k8s setup example located in https://superset.apache.org/docs/installation/running-on-kubernetes , and which instructed to `pip install psycopg2==2.8.5` in dependency section.

Anyone may change it to `pip install psycopg2==2.9.1` then this problem is solved.

**Comment by michael-s-molina** [comment]
> So it seems to be the problem about k8s setup example located in https://superset.apache.org/docs/installation/running-on-kubernetes , and which instructed to pip install psycopg2==2.8.5 in dependency section.

Thanks for reporting this @ensky and also for submitting a PR to update the guide 🙂

**Comment by kenho811** [comment]
This is really useful.

Setting psycopg2==2.9.3 works for me (Using superset 2.0.0 Docker Image)

**Comment by fmos** [comment]
Perhaps this is an issue with my PostgreSQL version (14). Anyway, c61ac76 is an updated patch to fix the timezone issue if (like me) the psycopg2 upgrade does not resolve it for you. This is better than my previous patch, because it is also compatible with using Prophet.
