### ISSUE TITLE
Wrong message for dataset import failure (when importing with zip file without database file)

### ISSUE THREAD

**Issue by ag-q** [apache/superset#20161]
When importing dataset without database file, the dataset is not imported, but the import message says that the import was successful.

#### How to reproduce the bug

1. Go to Superset datasets and export any dataset.
2. Delete this dataset from Superset.
3. Unzip exported archive.
4. Delete 'databases' folder in the unzipped archive.
5. Zip the archive without 'databases' folder.
6. Import zipped archive to Superset datasets.

### Expected results

Dataset is not imported and the import message says the import failed because the database file is missing.

### Actual results

The import message says 'Dataset imported', but the dataset is not present in the list of datasets.

### Environment

(please complete the following information):

- browser type and version: Google Chrome 101.0.4951.67
- superset version: `1.5.0`
- any feature flags active:
    - "ENABLE_TEMPLATE_PROCESSING": True
    - "DASHBOARD_NATIVE_FILTERS": True
    - "DASHBOARD_CROSS_FILTERS": True
    - "DASHBOARD_NATIVE_FILTERS_SET": True
    - "VERSIONED_EXPORT": True
    - "SQLLAB_BACKEND_PERSISTENCE": True
    - "ESTIMATE_QUERY_COST": True
    - "ENABLE_EXPLORE_DRAG_AND_DROP": True
    - "ALLOW_FULL_CSV_EXPORT": True
    - "UX_BETA": True
    - "DASHBOARD_FILTERS_EXPERIMENTAL": True
    - "DASHBOARD_RBAC": True
    - "EMBEDDED_SUPERSET": True
    - "OMNIBAR": True
    - "GENERIC_CHART_AXES": True
    - "ALLOW_ADHOC_SUBQUERY": True
    - "ENABLE_FILTER_BOX_MIGRATION": True
    - "ENABLE_DND_WITH_CLICK_UX": True

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
What is the use case for deleting the database from the export, when the dataset relies on the database? We might be able to make the error more useful, but we're not sure what you're trying to accomplish here.

**Comment by rusackas** [comment]
Since we're now on 3.1, on the verge of 4.0, we're not supporting 2.x  or prior versions actively. If anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)
