### ISSUE TITLE
Duplicated table names for Apache Kyuubi / Spark

### ISSUE THREAD

**Issue by pan3793** [apache/superset#20167]
There is [know issue](https://github.com/apache/superset/issues/16509) of using [dropbox/PyHive](https://github.com/dropbox/PyHive) to connect Kyuubi/Spark.

A forked [acryldata/PyHive](https://github.com/acryldata/PyHive) fixed the table name issue, when I try to use this one to connect Kyuubi/Spark Thrift Server, I see duplicated table names in the list.

#### How to reproduce the bug

Follow the docker README to launch apache/superset:1.5.0 in local.

Replace [dropbox/PyHive](https://github.com/dropbox/PyHive) by [acryldata/PyHive](https://github.com/acryldata/PyHive)
```
docker exec -it -u root superset pip uninstall PyHive
docker exec -it -u root superset pip install acryl-PyHive
```

Start a Spark Thrift Server. (Got same result when connect to Kyuubi)

Create database connection in Superset

<img width="483" alt="image" src="https://user-images.githubusercontent.com/26535726/169967845-26fc8bf3-f426-4c1a-8a5b-aca2d6bdbafd.png">

Refresh table list.

### Expected results

No duplicated table name in list.

### Actual results
<img width="404" alt="image" src="https://user-images.githubusercontent.com/26535726/169968680-5f769655-a7cd-4a9b-9a61-41f120a39512.png">

### Environment

- browser type and version: Latest Edge
- superset version: `superset version`: official docker image, apache/superset:1.5.0
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

When click refresh table list button, I see the Spark Thrift Server receives two `SHOW TABLES` queries in log.

```
22/05/24 15:00:10 INFO SparkExecuteStatementOperation: Submitting query 'SHOW TABLES IN `tpcds_s1`' with 3e98efb4-780f-43db-afb1-1d204f1009cc
22/05/24 15:00:10 INFO SparkExecuteStatementOperation: Running query with 3e98efb4-780f-43db-afb1-1d204f1009cc

...

22/05/24 15:00:10 INFO SparkExecuteStatementOperation: Submitting query 'SHOW TABLES IN `tpcds_s1`' with cf3fdb93-cad5-43c8-977e-aa18f44068fa
22/05/24 15:00:10 INFO SparkExecuteStatementOperation: Running query with cf3fdb93-cad5-43c8-977e-aa18f44068fa
```

**Comment by pan3793** [comment]
cc @shirshanka and thanks for maintaining the forked [acryldata/PyHive](https://github.com/acryldata/PyHive)

**Comment by rusackas** [comment]
@bkyryliuk any thoughts on this one?

**Comment by beat4ocean** [comment]
i also had this problem when Using superset to connect spark with acryl-PyHive，my Environment is：superset 2.1.0、acryl-PyHive 0.6.13、spark 3.2.4

**Comment by giovannipapini-agilelab** [comment]
We also have the same problems when connecting to Databricks (superset 2.0.1, spark 3.2.x). Any news about this?

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
