### ISSUE TITLE
Can't see tables in RedShift that are from datashare

### ISSUE THREAD

**Issue by amihaygil** [apache/superset#20184]
#### How to reproduce the bug

1. Create Redshift cluster with datashare to another cluster. 
2. Run in sqllab (you'll data)
3. Run in drop-down filter to see schema name (you'll see ) but table filter doesn't work 

### Expected results

See table list

### Actual results

List is empty

#### Screenshots

![image](https://user-images.githubusercontent.com/86407084/170243336-d8fe1b0e-f7da-4223-88c0-b17aa931e38c.png)

### Environment

(please complete the following information):

version Version: 0.0.0dev

**Comment by rusackas** [comment]
What driver are you using? We've seen a random uptick in redshift issues, but people seem to be using a variety of drivers to connect.

**Comment by amihaygil** [comment]
latest we are using pip to install:
          ...
             sqlalchemy-redshift \
            psycopg2-binary==2.9.1

**Comment by thinhnd2104** [comment]
Like [#122](https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/issues/122). datashare metadata is in SVV_DATASHARES. So you can query it but can't see it in table schema.

**Comment by BhuviTheDataGuy** [comment]
@amihaygil - we are trying to make the connection to a data share. In the database name - We gave the datashare db name, but its throwing error like, use cross-database querying not creating a connection. 

How did you connect the datashare db without mentioning the database name in the SQL query?

**Comment by amihaygil** [comment]
the idea is to map datashare from the sharing side to the shared side
`ALTER DATASHARE prod_datashare ADD SCHEMA mysql_stats_db_statslmn_stats;  -- share from 
CREATE EXTERNAL SCHEMA prod_mysql_stats_db_statslmn_stats
FROM REDSHIFT DATABASE 'prod_dwh' SCHEMA 'mysql_stats_db_statslmn_stats'  -- shared to dev 
 ALTER DATASHARE prod_datashare ADD ALL TABLES IN SCHEMA  mysql_stats_db_statslmn_stats; 
`

**Comment by meixikyi** [comment]
@amihaygil  hello, did you find some way for this issue?

**Comment by amihaygil** [comment]
not yet . we are going to  work this soon

‫בתאריך יום ג׳, 15 בנוב׳ 2022 ב-5:54 מאת ‪meixikyi‬‏ <‪
***@***.***‬‏>:‬

**Comment by mohrman** [comment]
@amihaygil This is the same for all database tools right? Like DataGrip, DBeaver etc? So it's actually related to the specific table not being accessible in a redshift shared database?

**Comment by rusackas** [comment]
> we are going to work this soon 

Let @yousoph , @eschutho or I know if you need any help/input along the way. We look forward to the contribution/resolution!

**Comment by macsir** [comment]
I got this too in the same account but different clusters. Can't see the shared tables from consumers side. Is there any update or fix? Thanks.

**Comment by rusackas** [comment]
Hi there, and sorry this has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale. If it is still an issue in Superset 3.x, we can re-open this, or feel free to open a new issue with updated context.
