### ISSUE TITLE
Unable to disable access.log from superset

### ISSUE THREAD

**Issue by DrissiReda** [apache/superset#20209]
I would like to disable logs, I tried using `SILENCE_FAB = True` but that does nothing.

Also I want to change log level. Using `LOG_LEVEL = 'ERROR'` does nothing. I still get `INFO` logs.

What am I doing wrong?

Superset version 1.4.1. I'm using the docker image: `apache/superset:1.4.1`.

And the official Helm Chart version 0.5.4

**Comment by rgarrigue** [comment]
I'm also interested in this

**Comment by pkesso** [comment]
Still a problem in 2.0.1. Setting LOG_LEVEL from INFO to ERROR reduces _some_ info messages, but I still got a lot of info and warnings in stdout. .

For example:
```
The field `timeseries_limit` is deprecated, please use `series_limit` instead.                                                                                                                 
2023-07-28 11:16:01,180:WARNING:superset.common.query_object:The field `timeseries_limit` is deprecated, please use `series_limit` instead.
```

which is logged with 'warning' level:
```
                logger.warning(
                    "The field `%s` is deprecated, please use `%s` instead.",
                    field.old_name,
                    field.new_name,
                )
```

It is a serious problem because I use paid log collector, charging me for every log message.

**Comment by pkesso** [comment]
@DrissiReda if you want to disable gunicorn's access.log only, you can set ACCESS_LOG_FILE env var to /dev/null:
```
extraEnv:                                                                                                                                                                                      
  ACCESS_LOG_FILE: '/dev/null'
```

**Comment by rusackas** [comment]
Hi there, and sorry this has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale. If it is still an issue in Superset 3.x (which it may well be!), we can re-open this - just let us know. Or, feel free to open a new issue with updated context. As always, PRs are welcome from anyone to fix the issue if it still exists.
