### ISSUE TITLE
database access on [DATABASE] does not allow read data sources

### ISSUE THREAD

**Issue by humbledude** [apache/superset#20208]
#### How to reproduce the bug

1. set permission on Role : `database access on [DATABASE]`
2. login user with the role
3. add a dataset in [DATABASE]

### Expected results

access to the dataset

### Actual results

the dataset is not available (not showing)

### Environment
using helm chart (0.5.10), docker image (apache/superset:1.5.0)

(please complete the following information):

- browser type and version: chrome  101.0.4951.64
- superset version: 1.5.0
- python version: 3.8.12
- node.js version:
- any feature flags active: ldap enabled, 

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

https://superset.apache.org/docs/security/#permissions

documents says `Granting access to a database allows for the user to access all data sources within that database`

and when I grant `schema access on [DATABASE.SCHEMA]` then it works well on the schema only

**Comment by yousoph** [comment]
Currently, the database access gives access to that database in SQL Lab. 
Giving schema or dataset access should give access to the relevant charts and dashboards. 

I agree that it seems like the database access seems like it should give access to all the schemas / datasets in that database...

**Comment by humbledude** [comment]
refer to document, it should give access to all the schemas / datasets in the database, if someone has access to the database.

https://superset.apache.org/docs/security/#permissions

fix document or fix code..?
