### ISSUE TITLE
Setting up Apache Superset with Nginx as Reverse Proxy(prefixed location and authentication)

### ISSUE THREAD

**Issue by missyoyo** [apache/superset#20213]
Hello:
I want set Nginx as superset Reverse Proxy,I want set prefixed location(eg:/superset),So we can access
http://nginx_ip/superset
proxy to 
http://superset_ip:8088/
Some one say I need "[Add a prefix to all Flask routes](https://stackoverflow.com/questions/18967441/add-a-prefix-to-all-flask-routes/36033627#36033627)"
As I am not developer, Can I have some setting in "superset_config.py" to support that?
Another problem is authentication,I want nginx do authentication
I can set "public" role in superset,But as anonymous user do not have "id",so can only see dashbord.but can not change alert config.
So,can superset support basic authentication or http header authentication?
If so, users do not need re-input their superset username and password.
Thank you for your help.

**Comment by zufolo441** [comment]
Hi, 
here is my nginx reverse proxy config for Superset. It's very simple: 
        location / {
                proxy_pass http://192.168.1.75:8088;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_redirect off;
        }

replace location with your desired location.

I have too the problem of anonymous user: I cannot see anything if I use anonymous window of browser....

**Comment by missyoyo** [comment]
@zufolo441 
Thank you, I have some other app take nignx root,so I can not let superset use nignx root,I have see some others meet the same problem.
I think that is hard to do now, so I try to change other app,let superset take root dir.
as anonymous,I think you can try superset logout and retry.
I can see dashbord and chart, but I can not add alert.
May they can fix it in the future

**Comment by vivek-kandhvar** [comment]
Its not supported in superset and there are many hacks which people have tried. iI you are interested, you can give it a try.

**Comment by avnav88** [comment]
having same issue

**Comment by allanlei** [comment]
For the reverse proxy

I haven't tried this myself, but since the underlying python framework is Flask, then you should be able to do this in `superset_config.py`

```python
APPLICATION_ROOT = '/superset/'
```
https://flask.palletsprojects.com/en/2.2.x/config/#APPLICATION_ROOT

This would allow Flask/superset to strip out the `APPLICATION_ROOT` for any incoming requests.  The default is `/`

**Comment by justmike1** [comment]
would like this feature as well

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and is a feature request rather than a bug. If this is relevant in current versions (currently 3.x) please open a new Ideas discussion or a PR to address the problem.
