### ISSUE TITLE
ERR! code 127 node_modules/puppeteer npm ERR! command failed npm ERR! command sh -c node install.js npm ERR! sh: 1: node: Permission denied

### ISSUE THREAD

**Issue by mounikag-tmt** [apache/superset#20211]
I am using 
Node. js - 16
npm - 7
and WSL2 - Ubuntu distribution to run superset frontend and backend. 
For superset Frontend, in superset-frontend module, i did "npm ci" command.

The command should run succesfully and install all the packages without any errors.

I am getting the below error:

npm ERR! code 127
npm ERR! path /mnt/c/Users/mounika.g/Superset/superset/superset-frontend/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! sh: 1: node: Permission denied
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-27T07_57_19_059Z-debug.log

![Screenshot (364)](https://user-images.githubusercontent.com/106060499/170676539-82f39a18-249a-4b3d-9c2b-9160b3c85dc3.png)

**Comment by k-dani** [comment]
Hello,
is there a solution to this problem because i ran into the same / a similar problem while installing superset under the latest Debian and Ubuntu server version:

Using this guide:
https://superset.apache.org/docs/installation/installing-superset-from-scratch/
at the bottom with the npm clean install command.

```
# Build javascript assets
cd superset-frontend
npm ci
```

I get this error as well:

```
npm ERR! code 1
npm ERR! path /home/<user>/superset/apache-superset-2.1.0rc3/superset-frontend/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c -- node install.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/<user>/.npm/_logs/2023-07-07T12_41_35_430Z-debug-0.log
```
