### ISSUE TITLE
Presto JSON data type schema issue in SQL Editor

### ISSUE THREAD

**Issue by xingyc15** [apache/superset#20216]
In the SQL Editor (SQL Lab), with Presto connection, we have a table with a column in JSON data type. When I choose that table, the schema cannot show up, and raise an error called 'An error occurred while fetching metadata'. 

While in our presto backend, the get column sql query has already finished and succeed. So this might be a UI bug in Superset?

And here is the Superset backend error log:

```
2022-05-27 17:53:57,770:DEBUG:urllib3.connectionpool:http://presto-coordinator.pinot:8080 "GET /v1/statement/queued/20220527_175357_00149_rexug/1?slug=xbd39bf9421cd4959b940afc8553b8b30 HTTP/1.1" 200 341
2022-05-27 17:53:57,973:DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): presto-coordinator.pinot:8080
2022-05-27 17:53:57,975:DEBUG:urllib3.connectionpool:http://presto-coordinator.pinot:8080 "GET /v1/statement/queued/20220527_175357_00149_rexug/2?slug=xbd39bf9421cd4959b940afc8553b8b30 HTTP/1.1" 200 867
10.41.44.206 - - [27/May/2022:17:53:57 +0000] "GET /superset/extra_table_metadata/4/metrics/default/ HTTP/1.1" 200 14 "https://superset.staging.xxx.ai/superset/sqllab/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36"
Triggering query_id: 2148
2022-05-27 17:53:58,250:INFO:superset.sqllab.command:Triggering query_id: 2148
Failed to execute query '2148' - 'None': Can't compile non template nodes
2022-05-27 17:53:58,264:ERROR:superset.views.core:Failed to execute query '2148' - 'None': Can't compile non template nodes
10.41.44.206 - - [27/May/2022:17:53:58 +0000] "POST /superset/sql_json/ HTTP/1.1" 500 102 "https://superset.staging.xxx.ai/superset/sqllab/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36"
```
#### How to reproduce the bug

1. Choose a presto db
2. Select the table with a column in JSON data type

### Expected results

The whole schema should show up.

### Actual results

No schema show up.

#### Screenshots

Here is the error message:

![Screen Shot 2022-05-27 at 10 45 15 AM](https://user-images.githubusercontent.com/33602700/170763649-f666f1f5-2b2e-4f5a-9002-9cda80cba76b.png)

### Environment

- superset version: `1.5.0`
- python version: `3.8.12`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [Y] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [Y] I have reproduced the issue with at least the latest released version of superset.
- [Y] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by brouberol** [comment]
Hi @xingyc15! I've recently submitted 2 PRs fixing different `An error occurred while fetching table metadata` errors for Presto: #26892 and #26782. Could you have a look at if either of those could fix your issue?

**Comment by rusackas** [comment]
Assuming based on four months of silence that the merged PR worked and all is well. Thanks for that, @brouberol :) Any interest in carrying the other one across the finish line? We can likely get it some more reviewers if needed.

Meanwhile, optimistically closing this as resolved, but happy to reopen if it's still an issue.
