### ISSUE TITLE
explicit setting colors for range values

### ISSUE THREAD

**Issue by zufolo441** [apache/superset#20224]
Hi, 
I could find extremely useful a more granular control of charts color. In particular, we'd need to set colors for single values or ranges: example:

0-10 black
10-20 blue
20-30 light blue

and so on....

is there a way?

**Comment by yousoph** [comment]
What chart(s) are you trying to do this on?

**Comment by rusackas** [comment]
Closing this since we never got clarification on the issue. If this is still a feature request you'd like to make, please create a more detailed proposal (chart type(s), example use cases, etc.) on a Github Discussion in the Ideas section.
