### ISSUE TITLE
 Elasticsearch Arrays not supported in Superset (SQL API)

### ISSUE THREAD

**Issue by VivekGupta97** [apache/superset#20229]
Hi folks , When I try to run the Query in superset which contain elastic search Array values I am getting following error -
elasticsearch error: TransportError(500, 'ql_illegal_argument_exception', 'Arrays (returned by [decision.certification.comments.user.sn]) are not supported')
My Query is : SELECT "column_1" from "table_1";
where  column_1 contains the Array Values and I am trying to get those values into the table form in superset but Array Values are not getting populated.
If Anyone could help me to resolve this issue it would be Appreciated. @frafra @ryw @moonboots @jeremi @edevil

**Comment by frafra** [comment]
Please do not spam by tagging random people.
