### ISSUE TITLE
[SIP-83] Proposal for copying virtual datasets

### ISSUE THREAD

**Issue by reesercollins** [apache/superset#20232]
### Motivation

There is currently no way for users to copy datasets in superset. Even though they can copy the SQL of a dataset, any changes we make to the field types (e.g. in cases where we turn long, complex types into JSON, or advanced types as described in #17852), to column labels, etc. cannot be easily copied.

### Proposed Change

Add a duplicate action to virtual datasets within the dataset list:
![image](https://user-images.githubusercontent.com/10563996/171485930-09554974-8c77-4509-a18b-c6b6f03d7473.png)

When clicked, it will open a modal which will allow the user to choose a name for the new dataset:
![image](https://user-images.githubusercontent.com/10563996/171486469-2cbe0a42-ca7c-4823-8f81-b0c605f9e805.png)

When OK is clicked, a duplicate of the dataset is created with the chosen name.

Here it is in action:

https://user-images.githubusercontent.com/10563996/171488107-d5377bee-4981-464b-b2f7-446a01ac4d54.mp4 

See [this pull request](https://github.com/apache/superset/pull/20309) for a working demo.

### New dependencies

None.

### Migration Plan and Compatibility

No migration needed.

### Rejected Alternatives

No alternatives have been considered at this time.

**Comment by rusackas** [comment]
@reesercollins Thanks for the proposal and the demo. Could you please post this like (or both links) to the dev@superset.apache.org email list for a proper discussion? If you need help navigating those waters, just say the word and I'll be happy to assist.

**Comment by eschutho** [comment]
Thank you for the SIP! @yousoph. Do you have any concerns with having the copy dataset only for virtual datasets? I wonder how this will look after SIP68 work is complete where there will no longer be a column for virtual or physical?

**Comment by ktmud** [comment]
I think it'd be valuable if there is a copy virtual dataset flow in Explore, too.

**Comment by nytai** [comment]
At some point I think it would be good to add a clone dataset for physical dataset, but give the user the option to choose a new table for the dataset. It is quite common to have the exact same schema for datasets (eg, dev, test, prod data). So far I've been suggesting users use the export dataset feature to change the table and the UUID and reimport as a workaround.

**Comment by reesercollins** [comment]
> At some point I think it would be good to add a clone dataset for physical dataset, but give the user the option to choose a new table for the dataset. It is quite common to have the exact same schema for datasets (eg, dev, test, prod data). So far I've been suggesting users use the export dataset feature to change the table and the UUID and reimport as a workaround.

The duplication of datasets only occurs within a single instance of Superset, not across deployments. Export/Import is still the only way to move data between deployments.

**Comment by jess-dillard** [comment]
Definitely agree with @zuzana-vej and would add only those with dataset edit rights should be able to duplicate to avoid the situation described.

@yousoph Yes - once we combine we'll want that to be the functionality. So we can add in now or address once we get into those dataset CRUD changes.

Small request @reesercollins - Can we change the primary button label from "Ok" to either "Duplicate" or "Create"? Typically we only use "Ok" as a button label if no action was taken in the modal.

**Comment by reesercollins** [comment]
> Definitely agree with @zuzana-vej and would add only those with dataset edit rights should be able to duplicate to avoid the situation described.

Currently there is a permission `can_duplicate`. If someone is concerned with the described situation occurring, they can assign `can_duplicate` and `can_edit` together.

**Comment by eschutho** [comment]
> At some point I think it would be good to add a clone dataset for physical dataset, but give the user the option to choose a new table for the dataset. It is quite common to have the exact same schema for datasets (eg, dev, test, prod data). So far I've been suggesting users use the export dataset feature to change the table and the UUID and reimport as a workaround.

I think @nytai's idea could be the solution for how to have a duplicate button for both datasets when they get merged together when SIP68 work is done.

**Comment by rusackas** [comment]
Closing this as the vote [passed](https://lists.apache.org/thread/ztqdj2n3vtxrofzyq6zbpd2oxgfqlkby). @reesercollins @cccs-rc is there still intent (and a timeline) on which this might get implemented?

**Comment by rusackas** [comment]
This SIP is at risk of being considered discarded due to lack of activity, if nobody has plans to carry it forward in the near future. Please let us know. You can always revisit/reopen.

**Comment by cccs-rc** [comment]
Sorry for missing your previous comment, @rusackas! We seem to have gotten this merged back in August 2022. Here's the PR: https://github.com/apache/superset/pull/20309 

There may be a couple bugs hiding in there that are in our backlog to fix, but the bulk of it seems to have been merged upstream. :)

**Comment by rusackas** [comment]
Thanks for the reminder/clarification.
