### ISSUE TITLE
SQL Server smalldatetime fields are not recognized by superset as time column - No temporal columns found

### ISSUE THREAD

**Issue by afreller-1wa** [apache/superset#20250]
Open a time based chart with a dataset that includes **smalldatetime** (SQL Server) column.

Time Column is not showing anything.

Click on Saved shows message: "**No temporal columns found**"

superset latest git from May25 running using docker-compose.

This is a big problem for us. We would need to create views to solve this imho. I hope this can be fixed quickly.

Best regards,
Alex

**Comment by yousoph** [comment]
Hi @afreller-1wa , are you able to manually mark the columns as "temporal" in the dataset? Or are they already marked as temporal columns and they still aren't showing up as time columns?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
