### ISSUE TITLE
Table visualization does not render \r\n as newline

### ISSUE THREAD

**Issue by lziosi** [apache/superset#20258]
Found using Superset 1.3.2. 
I have a text column called description in Postgresql with strings like: "\r\n\r\nTitle". 
When I display these strings in a Table chart, the carriage return an line feed are not rendered (all text appears on the same line). 
I can workaround this by creating a derived column with the function:

`regexp_replace(description, E'[\\n\\r]+', '</br>', 'g' )`

I have found an old closed defect that should have fixed this:
https://github.com/apache/superset/pull/2118/commits/e762978b42f9d639e0e3073c589eb4039968fc84#diff-e4cefda577d63cfaafae[…]46b45c7fce61e56362e207f915
But the referenced code files (Table.css and Table.js) are not in the latest version of the repository.
This recent change:
https://github.com/apache/superset/pull/18822/commits/66adcc9c8fb8b3987e39fd9c3737962867dcf49a
shows that: `"white-space: nowrap;"` was changed to `"white-space: normal;"`
That would explain why `\r\n `are no longer honored (it used to be `"white-space: pre;"` at the time of the earlier fix).

It seems to me that `"pre-wrap"` might be the most useful option: https://developer.mozilla.org/en-US/docs/Web/CSS/white-space
Would it be possible to change this or introduce an option?

**Comment by yousoph** [comment]
@prosdev0107 could you take a look? thanks!

**Comment by prosdev0107** [comment]
@yousoph I carefully took an enough check and test.
`\r\n` didn't honor even with "white-space: pre" or "white-space: pre-wrap".
I believe that we can't control them by css whitespace property and can only control them by reg expression.

![image](https://user-images.githubusercontent.com/47900232/173892803-a7be8c6d-3ed4-4c0e-baeb-4c7d50b3fbf9.png)

Please let me know your idea.

**Comment by yousoph** [comment]
Hey @lziosi , it looks like this functionality wasn't supported before the most recent change in https://github.com/apache/superset/commit/66adcc9c8fb8b3987e39fd9c3737962867dcf49a 

Do you have a SHA of if/when this worked?

**Comment by Hokwang** [comment]
I have a same problem,
I actually use superset for tables.
table should support newline.

For now, web shows newline to just one space, when I download csv file and load it to google sheet,
it shows newline.

So now I always download and use google sheet for seeing newline.

**Comment by Hokwang** [comment]
I found some link,
https://stackoverflow.com/questions/10937218/how-to-show-multiline-text-in-a-table-cell
https://github.com/apache/superset/pull/2118

**Comment by Hokwang** [comment]
@yousoph Could you check this issue again? I hope someone updated this issue.

**Comment by Hokwang** [comment]
@prosdev0107 Could you check this issue once again? Is there any solution?

**Comment by gaful** [comment]
I have the same issue, we come up with transforming it into <br>, but <br> appears when exporting data so it is not a really good solution.

**Comment by rusackas** [comment]
Closing this out for now, since:
1) the thread has gone pretty stale
2) I think this is a feature request more than a bug.
3) There are valid workarounds, as posted on the thread.

As always, we'd be more than happy to review a PR. And if anyone else disagrees, and thinks this is truly a _bug_, I'm more than happy to re-open this.
