### ISSUE TITLE
Referencing local variable response before initialiazing in get_chart_csv_data error handling 

### ISSUE THREAD

**Issue by zhaorui2022** [apache/superset#20262]
In [this line](https://github.com/apache/superset/blob/4f77824e550bc70d2f6365221b9078004d49b78c/superset/utils/csv.py#L83), it is trying to access `response` before it is initialized if `auth_cookies` is false. Will send a PR after creating this issue.

#### How to reproduce the bug

1. Run with an unauthorized user name to create an alert. When the alerts fails and tries to send a notification, it fails with error message `Failed generating csv local variable 'response' referenced before assignment`.

### Expected results

If running with unauthorized user name, it should just fails to retrieve data.

### Actual results

It fails with error message `Failed generating csv local variable 'response' referenced before assignment`

#### Screenshots
N/A

### Environment

(please complete the following information):

- browser type and version: It is a backend error and is happening to all browsers 
- superset version: `superset version` latest
- python version: `python --version` 3.9
- node.js version: `node -v` N/A
- any feature flags active: N/A

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zhaorui2022** [comment]
PR: https://github.com/apache/superset/pull/20263

**Comment by rusackas** [comment]
@zhaorui2022 thank you for resolving this!!! If there are any outstanding issues, just say the word, and we can re-open it. Let us know if we can assist you in any further contributions to Superset.
