### ISSUE TITLE
Dependencies issue.

### ISSUE THREAD

**Issue by poxeron** [apache/superset#20268]
Please  help

![super set](https://user-images.githubusercontent.com/55221870/172024834-2a2ed161-1cc5-42f7-ab28-2e3115090d17.png)

**Comment by JafarBadour** [comment]
did you try to install that dependency?

**Comment by rusackas** [comment]
Let us know if you were able to install that dependency @poxeron otherwise, we'll probably transfer this issue to a Github Discussion rather than a Github Issue (unless others can corroborate a bug in this area)

**Comment by poxeron** [comment]
Hello  @rusackas  @JafarBadour 
I try to install everything , that was required. 

But when you have issue  : 
"required flask 2.0.0 , but you have flask 2.0.0 which is not compatible."

You do not have a lot of options.
In the end , I uninstalled superset and install grafana

**Comment by rusackas** [comment]
OK... it doesn't seem like others have run into this, and you've moved on, so we'll close this issue.
