### ISSUE TITLE
In Superset, SQL LAB - >SQL EDITOR when running queries, final row is not visible

### ISSUE THREAD

**Issue by erikclark** [apache/superset#20286]
#### How to reproduce the bug
When running query in SQL LAB - SQL Editor, when scrolling through the results, the final record is not visible. This appears to the same issue as previously reported. But issue is still occurring.  If I sort DESC, I can see the final row on top. If I sort ASC, I cannot see the final record.

--Historical tickets that look similar.
https://github.com/apache/superset/issues/11966
https://github.com/apache/superset/issues/9869 

### Expected results

I should see the last record in the set

### Actual results

I cannot see the final record

#### Screenshots

In this screen shot I can see the record because it is on the top:
![image](https://user-images.githubusercontent.com/107008937/172266442-b4461b7d-df32-4756-aadb-88c41cbd3d7f.png)

However, when I sort Ascending, I cannot see this record even though I scrolled to the bottom of the page:
![image](https://user-images.githubusercontent.com/107008937/172266597-aaadbd62-1d8d-42fe-9d58-5e3e88cda939.png)

### Environment

- browser type and version: same behavior in Microsoft Edge 102.0.1245.33 (Official build) (64-bit) 
and
Google Chrome Version 102.0.5005.63 (Official Build) (64-bit)
- superset version: 1.4.1

**Comment by yousoph** [comment]
hi @erikclark ! this PR was recently merged and should resolve your issue: https://github.com/apache/superset/pull/20204 

please feel free to reopen or create a new issue if it doesn't address what you're seeing
