### ISSUE TITLE
Dashboard import asking for password database failed 

### ISSUE THREAD

**Issue by HazemBittar** [apache/superset#20288]
Make sure these boxes are checked before submitting your issue - thank you!

 - [x]    I have reproduced the issue with at least the latest released version of superset
 - [x]   I have checked the superset logs for python stacktraces and included it here as text if any
 - [x]   I have checked the issue tracker for the same issue and I haven't found one similar

Superset version

superset==1.4.1
Expected results

Import dashboard from on instance to another
Actual results

Fails on import after ask me for database password and i added the password with no success! i connect the database and the test connection good! i used sql server as datasource "mssql+pymssql://sa:XXXXXXXXXX@hostname/database"

Steps to reproduce

This is the error:

An error occurred while importing database: Error importing database

Traceback (most recent call last):

 2022-06-07 11:32:40,626:INFO:superset.dashboards.commands.importers.dispatcher:Command failed validation
superset_1                | Error importing dashboard
superset_1                | 2022-06-07 11:32:40,627:WARNING:superset.views.base:Error importing dashboard
superset_1                | Command failed validation
superset_1                | 2022-06-07 11:33:09,308:INFO:superset.dashboards.commands.importers.dispatcher:Command failed validation
superset_1                | Error importing dashboard
superset_1                | 2022-06-07 11:33:09,308:WARNING:superset.views.base:Error importing dashboard
superset_1                | /usr/local/lib/python3.8/site-packages/flask_caching/__init__.py:201: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
superset_1                |   warnings.warn(
superset_1                | Unable to load dialect <class 'sqlalchemy.dialects.mssql.adodbapi.MSDialect_adodbapi'>: type object 'MSDialect_adodbapi' has no attribute 'dbapi'
superset_1                | 2022-06-07 11:33:29,972:WARNING:superset.db_engine_specs:Unable to load dialect <class 'sqlalchemy.dialects.mssql.adodbapi.MSDialect_adodbapi'>: type object 'MSDialect_adodbapi' has no attribute 'dbapi'
superset_1                | 2022-06-07 11:33:30,260:DEBUG:snowflake.connector.ssl_wrap_socket:Injecting ssl_wrap_socket_with_ocsp
superset_1                | /usr/local/lib/python3.8/site-packages/snowflake/connector/options.py:94: UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<6.1.0,>=6.0.0; extra == "pandas"'
superset_1                |   warn_incompatible_dep(
superset_1                | 2022-06-07 11:33:30,263:DEBUG:snowflake.connector.auth:cache directory: /root/.cache/snowflake
superset_1                | Unable to load dialect <class 'sqlalchemy.dialects.mssql.adodbapi.MSDialect_adodbapi'>: type object 'MSDialect_adodbapi' has no attribute 'dbapi'
superset_1                | 2022-06-07 11:34:46,360:WARNING:superset.db_engine_specs:Unable to load dialect <class 'sqlalchemy.dialects.mssql.adodbapi.MSDialect_adodbapi'>: type object 'MSDialect_adodbapi' has no attribute 'dbapi'
superset_1                | 2022-06-07 11:34:46,827:DEBUG:snowflake.connector.ssl_wrap_socket:Injecting ssl_wrap_socket_with_ocsp
superset_1                | /usr/local/lib/python3.8/site-packages/snowflake/connector/options.py:94: UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<6.1.0,>=6.0.0; extra == "pandas"'
superset_1                |   warn_incompatible_dep(
superset_1                | 2022-06-07 11:34:46,833:DEBUG:snowflake.connector.auth:cache directory: /root/.cache/snowflake
superset_1                | Command failed validation
superset_1                | 2022-06-07 11:35:36,352:INFO:superset.dashboards.commands.importers.dispatcher:Command failed validation
superset_1                | Error importing dashboard
superset_1                | 2022-06-07 11:35:36,352:WARNING:superset.views.base:Error importing dashboard
superset_1                | Command failed validation
superset_1                | 2022-06-07 11:35:50,702:INFO:superset.dashboards.commands.importers.dispatcher:Command failed validation
superset_1                | Error importing dashboard
superset_1                | 2022-06-07 11:35:50,703:WARNING:superset.views.base:Error importing dashboard

i tried using commend line give me error 👍🏻 

# superset import-dashboards --path /home/superset/dashboard_export_20220607T122056.zip

Loaded your LOCAL configuration at [/etc/superset/superset_config.py]
logging was configured successfully
2022-06-07 12:36:06,938:INFO:superset.utils.logging_configurator:logging was configured successfully
2022-06-07 12:36:06,946:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
/usr/local/lib/python3.8/site-packages/flask_caching/__init__.py:201: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn(
Command failed validation
2022-06-07 12:36:08,614:INFO:superset.dashboards.commands.importers.dispatcher:Command failed validation
There was an error when importing the dashboards(s), please check the exception traceback in the log
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/superset/cli.py", line 360, in import_dashboards
    ImportDashboardsCommand(contents, overwrite=True).run()
  File "/usr/local/lib/python3.8/site-packages/superset/dashboards/commands/importers/dispatcher.py", line 64, in run
    raise exc
  File "/usr/local/lib/python3.8/site-packages/superset/dashboards/commands/importers/dispatcher.py", line 57, in run
    command.run()
  File "/usr/local/lib/python3.8/site-packages/superset/commands/importers/v1/__init__.py", line 63, in run
    self.validate()
  File "/usr/local/lib/python3.8/site-packages/superset/commands/importers/v1/__init__.py", line 146, in validate
    raise exception
superset.commands.exceptions.CommandInvalidError: Error importing dashboard
2022-06-07 12:36:08,614:ERROR:superset.cli:There was an error when importing the dashboards(s), please check the exception traceback in the log
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/superset/cli.py", line 360, in import_dashboards
    ImportDashboardsCommand(contents, overwrite=True).run()
  File "/usr/local/lib/python3.8/site-packages/superset/dashboards/commands/importers/dispatcher.py", line 64, in run
    raise exc
  File "/usr/local/lib/python3.8/site-packages/superset/dashboards/commands/importers/dispatcher.py", line 57, in run
    command.run()
  File "/usr/local/lib/python3.8/site-packages/superset/commands/importers/v1/__init__.py", line 63, in run
    self.validate()
  File "/usr/local/lib/python3.8/site-packages/superset/commands/importers/v1/__init__.py", line 146, in validate
    raise exception
superset.commands.exceptions.CommandInvalidError: Error importing dashboard

**Comment by Minitour** [comment]
I was facing the same issue with the CLI, so I decided to use the API.
It is a bit hacky but I hope this will help

```python
import requests

new_zip_file = 'path/to/dashboard_export.zip'
username = 'admin'
password = 'admin'

base_url = 'http://localhost:8088'

while True:
    try:
        response = requests.get(base_url, timeout=10)
        response.raise_for_status()
        break
    except Exception:
        pass

login_url = f"{base_url}/login/"
session = requests.Session()

payload = {}
headers = {
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'Accept-Language': 'en-US,en;q=0.9'
}

response = session.request("GET", login_url, headers=headers, data=payload)
csrf_token = response.text.split('<input id="csrf_token" name="csrf_token" type="hidden" value="')[1].split('">')[0]

# perform login

payload = f'csrf_token={csrf_token}&username={username}&password={password}'
headers = {
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'Content-Type': 'application/x-www-form-urlencoded'}

session.request("POST", login_url, headers=headers, data=payload, allow_redirects=False)
cookie = session.cookies.get_dict().get('session')
print(session.cookies.get_dict())

# Import dashboards

import_dashboard_url = f"{base_url}/api/v1/dashboard/import/"

with open(new_zip_file, 'rb') as f:
    payload = {
        'passwords': '{"databases/OMOP_CDM.yaml":"postgres"}',
        'overwrite': 'true'
    }
    files = [
        ('formData', ('dashboards.zip', f, 'application/zip'))
    ]
    headers = {
        'Accept': 'application/json',
        'Cookie': f'session={cookie}',
        'X-CSRFToken': csrf_token
    }

    response = requests.request("POST", import_dashboard_url, headers=headers, data=payload, files=files)

print(response.text)
```

**Comment by HazemBittar** [comment]
Thanks its help to solve the issue

**Comment by markalovell-git** [comment]
This is *exactly* what I've been looking for. Thank you.
