### ISSUE TITLE
Logo Image URL on DockerHub wrong

### ISSUE THREAD

**Issue by leo-schick** [apache/superset#20292]
#### How to reproduce the bug

1. Go to [Dockerhub apache/superset](https://hub.docker.com/r/apache/superset)
2. The logo is missing

![image](https://user-images.githubusercontent.com/67712864/172400584-459fd711-0870-41a1-9c90-8d2bfa74982c.png)

### Expected results

I would have expected a Apache Superset logo here.

**Comment by rusackas** [comment]
Seems like it's working now!
