### ISSUE TITLE
When add one logger locally, how to make it valid by docker-compose command ?

### ISSUE THREAD

**Issue by zjpopo** [apache/superset#20328]
*Please make sure you are familiar with the SIP process documented*
(here)[https://github.com/apache/superset/issues/5602]. The SIP number should be the next number after the latest SIP listed [here](https://github.com/apache/superset/issues?q=is%3Aissue+label%3Asip).

### Motivation

Description of the problem to be solved.

### Proposed Change

Describe how the feature will be implemented, or the problem will be solved. If possible, include mocks, screenshots, or screencasts (even if from different tools).

### New or Changed Public Interfaces

Describe any new additions to the model, views or `REST` endpoints. Describe any changes to existing visualizations, dashboards and React components. Describe changes that affect the Superset CLI and how Superset is deployed.

### New dependencies

Describe any `npm`/`PyPI` packages that are required. Are they actively maintained? What are their licenses?

### Migration Plan and Compatibility

Describe any database migrations that are necessary, or updates to stored URLs.

### Rejected Alternatives

Describe alternative approaches that were considered and rejected.

**Comment by rusackas** [comment]
Hi there @zjpopo. It doesn't seem like you added any details about what you're trying to do, and instead included a blank improvement proposal. I'll close this for now, but if you're able to explain a bit more of what you're trying to accomplish, and what's taking place when you try, we can take this to a Q&A Discussion.
