### ISSUE TITLE
Sequences are not allowed in redshift

### ISSUE THREAD

**Issue by JafarBadour** [apache/superset#20322]
[A clear and concise description of what the bug is.

#### How to reproduce the bug

1. change the database to a DB that lives in redshift
2. add pip install sqlalchemy-redshift==0.8.9

### Expected results

The migrations of db should work 

### Actual results

An error redshift doesnot support sequences happen

#### Screenshots

![image](https://user-images.githubusercontent.com/82835606/172733319-f6717fa3-9b7c-4cbe-ad63-4cfd4085a713.png)

### Environment

(please complete the following information):

.env contains the following
```
COMPOSE_PROJECT_NAME=superset

# database configurations (do not modify)
DATABASE_DB=superset
DATABASE_HOST=redshift-cluster-2.$$$$$$$$$.us-east-1.redshift.amazonaws.com
DATABASE_PASSWORD=$$$$$$$$$
DATABASE_USER=$$$$$$$$$

# database engine specific environment variables
# change the below if you prefers another database engine
DATABASE_PORT=5439
DATABASE_DIALECT=postgresql+psycopg2
POSTGRES_DB=superset
POSTGRES_USER=$$$$$$$$$
POSTGRES_PASSWORD=$$$$$$$$$
#MYSQL_DATABASE=superset
#MYSQL_USER=superset
#MYSQL_PASSWORD=superset
#MYSQL_RANDOM_ROOT_PASSWORD=yes

# Add the mapped in /app/pythonpath_docker which allows devs to override stuff
PYTHONPATH=/app/pythonpath:/app/docker/pythonpath_dev
REDIS_HOST=redis
REDIS_PORT=6379

FLASK_ENV=development
SUPERSET_ENV=development
SUPERSET_LOAD_EXAMPLES=yes
CYPRESS_CONFIG=false
SUPERSET_PORT=8088


```

I also tried to add **redshift-sqlalchemy** and change the dialect to **redshift+psycopg2**
same error as above 
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
