### ISSUE TITLE
text type not display normally

### ISSUE THREAD

**Issue by zhugw** [apache/superset#20327]
At first column as below
```
  `tag_value_name` text COLLATE utf8mb4_bin,
```
then  return chart data as below
```
 b'\\xe6\\x9c\\xaa\\xe7\\x9f\\xa5'
```
after changing column  from text to varchar
```
 `tag_value_name` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL,
```
this time the return data is OK

I think `text` and `varchar` both are string, should have the same display effect.

**Comment by rusackas** [comment]
Maybe @betodealmeida or @john-bodley might have an idea of how/where to direct this one.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
