### ISSUE TITLE
Getting Error while running Queries on SQL LAB for MSSQL

### ISSUE THREAD

**Issue by Asturias-sam** [apache/superset#20329]
#### How to reproduce the bug

1. Enable MSSQL DataSource.
2. Run Query on SQL LAB 
3.  Create Charts

### Expected results

Should able to run query

what you expected to happen.

Should able to run query via SQL Lab

### Actual results

For Point 2 : Run Query on SQL LAB 

I am getting this error : '_AppCtxGlobals' object has no attribute 'user'

For Point 3: If we create charts directly via Charts tab it's working fine

### Environment

(please complete the following information):

- browser type and version:
- superset version:  1.1.0
- python version: `python --version` 3.7.9
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sfirke** [comment]
Does this issue persist for you?  I am able to run queries in SQL Lab on a SQL Server data source, in versions 2.0.0 and 2.0.1.

**Comment by rusackas** [comment]
Closing as resolved, but if you still face this in the versions mentioned by @sfirke, we can revisit the discussion. Thanks!
