### ISSUE TITLE
Annotation Formula not displayed with Generic Chart Axes enabled

### ISSUE THREAD

**Issue by oleg-savko** [apache/superset#20334]
Annotation Layer:  Formula not displayed , if  feature flag:

`"GENERIC_CHART_AXES": True`

Tested Superset version: 1.5.1
Tested Database: Clickhouse

If disable `"GENERIC_CHART_AXES": False` than annotation start to displayed correct

Expected: Annotation Layer:  Formula displayed correct

**Comment by inakianduaga** [comment]
same problem happening to us

**Comment by rusackas** [comment]
@oleg-savko and @inakianduaga just checking in on this old issue. The Generic Chart Axes feature has been updated quite a bit. Would you mind checking to see if this issue still exists on the latest `master` and/or the latest 2.0.1 release candidate? Holler if you need help navigating your way to the release candidate, btw, I'm happy to help!

**Comment by rusackas** [comment]
Pinging @lauderbaugh as well for issue validation/triage (I wish I could assign tickets to you, but I don't think I can unless you comment in the thread) :)

**Comment by geido** [comment]
Tested with Clickhouse and added annotation layers successfully with GENERIC_CHART_AXES. Closing this issue for now. If the issue still persists for you, please provide detailed repro instructions. Thank you
