### ISSUE TITLE
For Time range filter  custom type , If start  is Now, and End is Specific Time Will  cause error 

### ISSUE THREAD

**Issue by kkfnui** [apache/superset#20343]
#### How to reproduce the bug

1. Go to 'And Chart'
2. Click on 'Time'
3. Config custom  start is Now, and End is Specific Time -- as  next hour
4. wait for more than an hour,
5. Dashboard will raise server error, And We can't edit chart from dashboard

error stack
```
File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/api/_init_
•py", line 85, in wraps
return f(self,
*args,
**kwargs)
File "/app/superset/views/base_api.py", line 113, in wraps
ralse ex
File "/app/superset/views/base_api.py"
line 110, in wraps
duration, response = time function(f,
self,
*args,
**wargs)
File "/app/superset/utils/core.py", line 1506, in time_ function
response = func(*args, **kwargs)
File
"/app/superset/utils/log.py".
line 245, in wrapper
value = f(*args,
**kwargs)
File "/app/superset/dashboards/api.py", line 381, in get datasets
datasets = DashboardDAO.get datasets for dashboard(id or slug)
File "/app/superset/dashboards/dao.py
line 52, in get_datasets_for_ dashboard
return dashboard.datasets trimmed for slices()
File "/us/local/lib/python3.8/site-packages/flask caching/_init_-py", line 905, in decorated_ function
return f(*args, **kwargs)
File "/app/superset/models/dashboard.py", line 314, in datasets_trimmed for slices
result.append (datasource.data for slices(slices))
File "/app/superset/connectors/base/models.py™, line 335, in data_ for_slices
query context = slc.get query context()
File "/app/superset/models/slice.py",
line 276, in get query_ context
return self.get query context factory().createl
File
"/app/superset/common/query_context_factory.py", line 60, in create
queries
File "/app/superset/common/query_context_factory.py", line 61, in <listcomp>
self._query_object_factory.create(result type,
**query obi)
File "/app/superset/common/query_object_factory.py", line 65, in create
from dttm, to dttm = self. get dttms (time range, time shift, processed extras)
File "/app/superset/common/query_object_factory.py", line 105, in _get_dttms
return get since untill
File "/app/superset/utils/date parser.py"
line 267, in get_since until
raise ValueError(_ ("From date cannot be larger than to date"))
ValueError:
From
date cannot be larger than to date
```

### Expected results

1. can edit chart from dashboard， ignore the error from chart. At least can edit normal chart
2. If there is any error from chart, Just show error on chart
3. Can we disable the specific time when start is Now?

### Actual results

can't edit chart from dashboard

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x ] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zhaoyongjie** [comment]
Hi @kkfnui the behavior seems expected, thoughts?

<img width="695" alt="image" src="https://user-images.githubusercontent.com/2016594/173085737-b8aa8b15-6393-47ee-9760-4f299b2f0147.png">

**Comment by rusackas** [comment]
Not saying this isn't a bug, but it's indeed a strange one. The *reason* it's failing is that you can't have a Start time that's greater/later than your End time. If your start time of `Now` is suddenly _after_ your end time, then it will fail. 

If you try to set up something like this in the UI, like Start time Now, and End time one hour ago, the UI will warn you about this error. Your situation is that it _starts off_ as a valid range, and then _becomes_ invalid over time. Maybe @zhaoyongjie will have an idea of how to handle this.

However, I'm very curious about your use case here, so I can learn _why_ you ran into this, and see if there's a deeper issue to solve. In short: why are you querying for data from the future, in the first place?

**Comment by rusackas** [comment]
Not that if you DO want to perpetually query data from one hour into the future (again, I'm very curious the use case), then you could use `relative` time for this:
<img width="576" alt="image" src="https://user-images.githubusercontent.com/812905/173086247-7efa59cb-8a61-4cd3-b9ec-71c2fdaf0ae2.png">

**Comment by kkfnui** [comment]
> Not that if you DO want to perpetually query data from one hour into the future (again, I'm very curious the use case), then you could use `relative` time for this: <img alt="image" width="576" src="https://user-images.githubusercontent.com/812905/173086247-7efa59cb-8a61-4cd3-b9ec-71c2fdaf0ae2.png">

Thanks for reply!

Colleagues are not familiar with superset , so this issue is triggered.
If it it ok, try to avoid this wrong use in product design?

**Comment by rusackas** [comment]
Yep... we plan to give this date/time picker a bit of an overhaul in the coming months. You're not the only one that's confused by some aspects of it. For now, if it's working, I'll call this issue closed.
