### ISSUE TITLE
Unable to use gradients as colors for worldmap

### ISSUE THREAD

**Issue by mlmaverick** [apache/superset#20376]
We recently upgraded the Superset version to 1.5.0 and I'm unable to deselect the `Categorical Color Scheme` for a heat map on the world map. From the what I understood, the colors schemes for a dashboard are now fixed to the dashboard but what do we do when we need to show gradients on the plot. 

#### How to reproduce the bug

1. Create a dashboard with multiple charts and one of them is with country data on world map.
2. Create a chart with world map with gradient color scheme.

### Expected results

![image](https://user-images.githubusercontent.com/105640903/173549335-c0abd98a-6cc7-4fef-8b39-1b0a634e524f.png)

### Actual results

![image](https://user-images.githubusercontent.com/105640903/173547661-a3497a5f-e86b-431d-a172-bb0502c1bb99.png)

### Environment

(please complete the following information):

- browser type and version:  Chrome Version 102.0.5005.115
- superset version: `1.5.0`
- python version: `3.8.12`

Any help with this regards would be helpful. Thanks!

**Comment by stephenLYZ** [comment]
@mlmaverick Hey. We've added two color options in this [PR]( https://github.com/apache/superset/pull/19881) to select  categorical color or gradient color, so we might put this in the next release. cc @rusackas

**Comment by mlmaverick** [comment]
@stephenLYZ @rusackas next release would be really helpful. Thank you.

**Comment by stephenLYZ** [comment]
Will release in [2.0](https://github.com/apache/superset/pull/20490). Close this one.
