### ISSUE TITLE
Charts show applied filter although no filter is applied

### ISSUE THREAD

**Issue by vivekdixit2510** [apache/superset#20379]
When applying a filter from the filter box, it is showing some charts filter indicator are giving unset filter, however, if I set No-filter box, there are charts wherein filter indicator is not changed to unset filter. This behavior is not affecting the filtering of the data but created confusion if the filter is applied or not.

![image](https://user-images.githubusercontent.com/80536487/173576406-5be15680-680b-4777-b3e3-590e9789d02f.png)
![image](https://user-images.githubusercontent.com/80536487/173576549-f9314956-5af3-4801-ae65-1bce3fce0234.png)

**Comment by vivekdixit2510** [comment]
Hello Team, 

Please update the status. If we can resolve this issue.

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
