### ISSUE TITLE
Roles page are now headerless / footerless

### ISSUE THREAD

**Issue by ktmud** [apache/superset#20370]
## Screenshot

<img width="1547" alt="image" src="https://user-images.githubusercontent.com/335541/173467015-dfb006c5-aaea-4e85-8e63-54fba659bb2f.png">

## Description

Roles page now don't have a header or footer. We should either prioritize migrating them to React or add a basic header back.

**Comment by rusackas** [comment]
This doesn't seem to be the case anymore. Closing!
