### ISSUE TITLE
Superset Celery TypeError: 'tuple' object is not callable

### ISSUE THREAD

**Issue by parker-pu** [apache/superset#20374]
Superset: 1.5.1
Run command：superset run -p 8080 --with-threads --reload --debugger
Result:
![2022-06-14 14-08-08屏幕截图](https://user-images.githubusercontent.com/46392095/173505537-ba3ede44-641e-476f-bb2a-e3be35479487.png)

Attempt to print error location
![image](https://user-images.githubusercontent.com/46392095/173506705-3631fa1c-0156-47b0-a0ea-ddf9e5b1e6ce.png)

![image](https://user-images.githubusercontent.com/46392095/173506715-e3a20a3f-47ee-430e-92a6-a7ca1cd2ca0a.png)

**Comment by parker-pu** [comment]
I turned on “GLOBAL_ASYNC_QUERIES” configuration，Normal after shutdown

**Comment by rusackas** [comment]
Given how old this is, it's probably no longer an issue, but we're now on 3.1, on the verge of 4.0, and not supporting 2.x  or prior versions actively. If folks are experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)
