### ISSUE TITLE
csv export menu is missing when accessing report with no authentication, configured public role='Admin' and by passed the sign in page

### ISSUE THREAD

**Issue by shafad1** [apache/superset#20389]
I have configured config.py with 
AUTH_ROLE_PUBLIC = 'Admin'  to by pass sign in page while hitting report url, but the report not showing export to csv option in the menu , only available download image.. 
![image](https://user-images.githubusercontent.com/107529872/173736323-5d042407-6310-4fbd-8ae3-b3cc717c623b.png)

**Comment by shafad1** [comment]
can anyone helpe on the above case

**Comment by sfirke** [comment]
I'm closing as this is old and I can't replicate it in 2.1.0.
