### ISSUE TITLE
Toolbar is missing on some pages

### ISSUE THREAD

**Issue by eschutho** [apache/superset#20386]
Toolbar is missing on SqlLab and Explore, and maybe a few other places. 
The error I'm seeing is: 
```
LocationProvider.js?e373:13 Uncaught Error: useQueryParams must be used within a QueryParamProvider
    at useLocationContext (LocationProvider.js?e373:13:1)
    at useQueryParams (useQueryParams.js?5bf2:71:1)
    at RightMenu (MenuRight.tsx?488f:99:1)
```

#### How to reproduce the bug

1. Go to SqlLab or Explore
2. See error (no toolbar)

### Expected results
Toolbar should be present

### Actual results

No toolbar

#### Screenshots

![_DEV__Games_per_Genre](https://user-images.githubusercontent.com/5186919/173706874-df35ccf3-85c4-4439-9a36-e5723c6555d2.png)
![_DEV__Superset](https://user-images.githubusercontent.com/5186919/173706893-1f16efe5-2779-46e6-9cd0-e24a80063661.png)

### Environment

- browser type and version: Chrome
- superset version: `superset version` Master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
I believe #20363 should resolve this, which just got merged. It's surprising that Cypress doesn't fail on this.

**Comment by rusackas** [comment]
The above PR restored
