### ISSUE TITLE
Dataset edit UI can't show all `SQL expression` content

### ISSUE THREAD

**Issue by kkfnui** [apache/superset#20388]
#### How to reproduce the bug

1. Go to 'Dataset'
2. Click on 'edit' any dataset 
3. Change tab to metrics
4. Add any longer  sql expression  like   `count(distinct if(event='hello', user_id, null))`

### Expected results

A clear UI,

### Actual results

what actually happens.

#### Screenshots
<img width="836" alt="iShot_2022-06-15_11 50 03" src="https://user-images.githubusercontent.com/1238381/173734070-8e7597c6-7e53-44d2-b177-87add0f3a836.png">

## Any More

Can we redesign  this UI?

**Comment by rusackas** [comment]
This seems to scroll quite well, and the textarea field is expandable. If you're not encountering this behavior, we can re-open this bug, or take it to a design discussion in Github's Discussions under the "Ideas" category. Whichever is prudent. Thanks!
