### ISSUE TITLE
Pivot v2 doesn't apply color weight for values of Conditional formatting metrics

### ISSUE THREAD

**Issue by huypn1106** [apache/superset#20391]
## Description
I recently upgraded superset to newest version and I'm unable to create Conditional formatting for Pivot table v2 as before. When I select color, it apply the same color weight for all values of metric.

Settings of older version still here but when I change to another color, the color weight the same for all values. I think it cause by the change of color value from rgb(0,255,0) to color hex code.

Working settings from old version display on new version:
![image](https://user-images.githubusercontent.com/32066762/173777448-abf8d962-88aa-4294-bb4d-ba2d65093127.png)

## Screenshot
Current Version:
![image](https://user-images.githubusercontent.com/32066762/173775214-fab481a3-72b4-4261-b611-32a2eebf9a2f.png)

Expected as Older version:
![image](https://user-images.githubusercontent.com/32066762/173774657-88c5e06e-6776-40ed-9fe8-8e5601d0ae86.png)

**Comment by stephenLYZ** [comment]
@huypn1106 Hi. Please let me know if this [fix](https://github.com/apache/superset/pull/20396) can help you. Thanks!

**Comment by huypn1106** [comment]
LGTM !! Thanks @stephenLYZ .
