### ISSUE TITLE
Auto run start as a service on Windows

### ISSUE THREAD

**Issue by bumasl** [apache/superset#20426]
Good morning everyone.
To automatically start the Superset service, without starting the Windows session, every time I restart my computer I have to start my Windows session and open the CMD terminal and execute the following lines.
C:\> set FLASK_APP=superset
C:\> superset run -p 8088

Can someone help me automate starting the service.
Thank you very much for your attention.

**Comment by RickGanKL** [comment]
Hello, @bumasl 
I strongly suggest that you run superset in the IIS.
Please check https://learn.microsoft.com/en-us/iis/extensions/httpplatformhandler/httpplatformhandler-configuration-reference.

**Comment by rusackas** [comment]
This issue has gone stale, but also SUperset officially dues not support Windows. If you want to contribute toward windows support (package management, testing, documentation, etc) please feel free to contribute... lots of folks would be thankful. :)
