### ISSUE TITLE
"The CSRF session token is missing" and "Unexpected token < in JSON at position 0" with CORS and Domain Sharding

### ISSUE THREAD

**Issue by ndrluis** [apache/superset#20424]
#### How to reproduce the bug

1. Go to Dashboards
2. Click on some dashboards with legacy and new charts 

### Expected results

Show the results

### Actual results

![image](https://user-images.githubusercontent.com/1859449/174305840-f83d177c-d8c7-43f0-9e83-c5b6b1c89143.png)

#### Screenshots

![image](https://user-images.githubusercontent.com/1859449/174305900-c1ac9f58-22d0-4a3b-981c-27e0817521d9.png)
![image](https://user-images.githubusercontent.com/1859449/174305926-f02262f6-c2b5-455f-925e-7924c75199ff.png)

### Environment

- browser type and version: Chrome 102.0.5005.115 (Official Build) (arm64)
- superset version: 1.5.0
- python version: 3.8.12
- any feature flags active: VERSIONED_EXPORT and ALERT_REPORTS

#### CORS Configuration

```python
   ENABLE_CORS = True
   
   CORS_OPTIONS = {
      'supports_credentials': True,
      'allow_headers': ['X-CSRFToken', 'Content-Type', 'Origin', 'X-Requested-With', 'Accept', 'Referer'],
      'resources': [
        '/superset/csrf_token/',
        '/api/v1/formData/',
        '/superset/explore_json/',
        '/api/v1/query/',
        '/superset/fetch_datasource_metadata/',
        '/superset/explore_json/',
        '/superset/log/',
        '/api/v1/chart/data',
        '/login/'
      ],
      'origins': [
        'https://superset.internal.hmg.someaddress.io', 
        'https://superset1.internal.hmg.someaddress.io', 
        'https://superset2.internal.hmg.someaddress.io'
      ]
    }
```
#### Session Cookie

```python
    SESSION_COOKIE_SAMESITE = None
```

#### Domain Sharding

```python
    SUPERSET_WEBSERVER_DOMAINS = ['superset1.internal.hmg.someaddress.io', 'superset2.internal.hmg.someaddress.io']
```

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I am Using Google OAuth

**Comment by tejaskatariya** [comment]
@ndrluis Did you find any solution to this?

**Comment by ndrluis** [comment]
> @ndrluis Did you find any solution to this?

No

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
