### ISSUE TITLE
Time formatting does not take effect

### ISSUE THREAD

**Issue by tenglong3158** [apache/superset#20439]
#### How to reproduce the bug

1. Open a Bar Chart V2 chart;
2. Edit the dataset, and set the label of the time column;
![image](https://user-images.githubusercontent.com/20203245/174587032-e0880d81-3412-4637-b36c-071ba5e32532.png)

3. Set the time column as the X axis and specifies the time formatting；
4. Run；
5. Observe the X-axis time format。

### Expected results
Displays correct time formatting

### Actual results
The original values are displayed

#### Screenshots

![image](https://user-images.githubusercontent.com/20203245/174586174-bed77cd1-c906-4bbf-ba00-7476c39b56d0.png)

### Environment

(please complete the following information):

- browser type and version:
- superset version: 1.5.0
- python version: 3.8.12
- node.js version: 16.9.1
- any feature flags active: “GENERIC_CHART_AXES”: True

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
