### ISSUE TITLE
Cursor falls behind in SQL Lab

### ISSUE THREAD

**Issue by LuPan2015** [apache/superset#20436]
When typing in SQL Lab, the cursor slowly falls behind the characters.

# Expected results
Typing to be normal

# Actual results 
```
SELECT
    database,
    table,
    partition,
    sum(rows) AS rows,
    count() AS part_count
FROM system.parts
WHERE (active = 1) AND (table ='game_match_log') AND (database ='gem') and partition =  ''
GROUP BY
    database,
    table,
    partition
ORDER BY part_count DESC;
limit 30;
```

https://user-images.githubusercontent.com/10804128/174222924-b61f595e-59cb-467d-b00e-662196fd242f.mp4

**Comment by stephenLYZ** [comment]
@LuPan2015 Hi. I'm curious if there are any errors in the console, looks like I can't reproduce in the latest master branch.

**Comment by LuPan2015** [comment]
> @LuPan2015 Hi. I'm curious if there are any errors in the console, looks like I can't reproduce in the latest master branch.
The error in console is as follows:

![image](https://user-images.githubusercontent.com/10804128/174926196-8d9e8314-7998-4d37-81f9-3902deb17653.png)
