### ISSUE TITLE
superset do not support on arm64 platform, can add this version in future?

### ISSUE THREAD

**Issue by jeff-xiao-2021** [apache/superset#20431]
I have a VM on Oracle Cloud, and, I have installed Ubuntu on Oracle Cloud's arm64 VM, and I also  installed docker. Other tools support the platform of arm64 architecture, but our superset does not yet support it. Can I add support for arm64 in future development?
waiting for superset response, thanks.

**Comment by rusackas** [comment]
This is now supported!

**Comment by AlphaJack** [comment]
@rusackas when will it be available as arm64 docker image?

**Comment by mistercrunch** [comment]
Official docker builds are dual platform moving forward with 3.1.0 being the first instance. We're a bit more selective for master and pull request builds.

Docs at https://superset.apache.org/docs/installation/docker are right, but need I need to add a note about dual platform release builds. Top-level images like latest, dev, or anything with a release number in the tag should be dual platform moving forward.
