### ISSUE TITLE
Copy and paste commands from tutorial doesn't work

### ISSUE THREAD

**Issue by cdeil** [apache/superset#20430]
## Screenshot

<img width="788" alt="Screenshot 2022-06-18 at 13 28 02" src="https://user-images.githubusercontent.com/852409/174435526-70da13c4-d1e3-4687-b923-c0f39a21c463.png">

## Description

At https://superset.apache.org/docs/installation/installing-superset-using-docker-compose the copy command button doesn't just copy the command, it also includes the leading `$ ` character:

```
$ git clone https://github.com/apache/superset.git
```

Pasting this in a terminal then gives this error:

```
% $ git clone https://github.com/apache/superset.git
zsh: command not found: $
```

Is it possible to change that so that only the actual command is copied?
Or alternatively just remote the leading `$ `?

**Comment by stephenLYZ** [comment]
@cdeil Hi. Thanks for your suggestion! You are right. We actually don't need `$` symbol and the fact that we need to filter out this symbol when copying.

**Comment by stephenLYZ** [comment]
Fix in https://github.com/apache/superset/pull/20480.
