### ISSUE TITLE
Hide column on Table chart

### ISSUE THREAD

**Issue by juanmantelli** [apache/superset#20453]
It would be great if there is any way to hide columns on the table chart.

For example, I have two table charts next to each other. Both use the same date field and I would like to hide it on the right table keeping granularity.

Regards,

**Comment by juanmantelli** [comment]
Finally I realized that it is possible using CSS:

`#chart-id-146 .css-1yzpsg4 {
    display: none;
}

#chart-id-146 .table>colgroup+thead>tr>th:first-child{
    display: none;
}`

**Comment by manan9676** [comment]
How to get the chart id ?
And also can you explain this in a little detailed manner , it would be really helpful
Thanks

**Comment by juanmantelli** [comment]
> How to get the chart id ? And also can you explain this in a little detailed manner , it would be really helpful Thanks

Hi, 

To see a chart ID, go to any chart and you will find it on the URL as a parameter, for example: slice_id=666.

Then, open your dashboard and edit it. On your right, you will find a 3 points menu (...). Click there, click Edit CSS and use my code, replacing 146 for your chart id, in this example it is 666.

**Comment by vvmirajkar** [comment]
Can you help on how to get the **css-1yzpsg4**

**Comment by sjk7524068** [comment]
> Thank you for your response , it is not working for my case Problem Statement : I have two columns in my tabular chart I want to hide the second column as first column is a style image and the second one is style_code for that style but I don't want to display style_code in the table can you please help me out ?

try using browser debug mode, locate your chart id will be no problem
