### ISSUE TITLE
[DECK.GL SCATTERPLOT] Wrong legend color

### ISSUE THREAD

**Issue by audelorAd** [apache/superset#20458]
On a deck.gl scatterplot I have a categorical color for the point color.
It's working fine except that the categories color in legend is not the same as the point on the map.

#### How to reproduce the bug

1. Create a deck.gl scatterplot dataviz
2. Put something in "Point Color > Categorical Color" parameter
3. Run to see result

### Actual results

![2022-06-21_17h45_02](https://user-images.githubusercontent.com/63049494/174842132-e69ac633-17d9-46cb-a428-4dfabd4d4ee8.png)

### Expected results

Same color on the map and in the legend.

### Environment

(please complete the following information):

- browser type and version: Firefox 91.10 esr
- superset version: 1.5.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you! 
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dkrat7** [comment]
Maybe there are multiple points with the same location in your dataset and they have different category? (visualization of overlapping points should be handled differently)

**Comment by audelorAd** [comment]
> Maybe there are multiple points with the same location in your dataset and they have different category? (visualization of overlapping points should be handled differently)

I checked, there is no overlapping points.

**Comment by cphilibien** [comment]
I have the same issue.

![2022-11-30_16-07](https://user-images.githubusercontent.com/112178756/204908288-0535d46e-2ede-4563-8a67-245a3783658a.png)

**Comment by ShaliniIruvuru** [comment]
Working as Expected.In latest release of superset version 2.1.0. ,It is working fine.
Screenshots:-
![image](https://user-images.githubusercontent.com/115684419/231090145-c68c325f-2f1b-4401-82ad-ed01bd21e6dc.png)
![image](https://user-images.githubusercontent.com/115684419/231090196-bf350ed7-605e-4b5c-9d24-7c6f52af0dd6.png)
loom video:-
https://www.loom.com/share/59a4a12898e94fc7b5156bb8d130926b

**Comment by rusackas** [comment]
Agreed, seems fixed! Closing :D
