### ISSUE TITLE
Import Dashboard Failed with command validation error

### ISSUE THREAD

**Issue by Naresh-Challa** [apache/superset#20463]
#### How to reproduce the bug
Create a dashboard, save and export it (VERSIONED_EXPORT = true)
Try to import and fails with a validation error
import the dashboard using the /import API.
The issue is that a simple dashboard with just one or two charts seems to work. A more involved dashboard such as the one I am building fails

### Expected results

Import Dashboard should be successful

### Actual results

Fails import
Error:
Superset 1.5.0
API Version:
POST //api/v1/dashboard/import/ HTTP/1.1" 302 221 "-" "curl/7.65.0"

curl -k -X 'POST' 'https://superset-URL/api/v1/dashboard/import/' -H 'accept: application/json' -H "Authorization: Bearer $token" -H 'Content-Type: multipart/form-data' -F 'formData=@test1.zip;type=application/x-zip-compressed' -F 'overwrite=true' -F 'passwords={ "databases/MySQL_test.yaml":"Pwd", "databases/mysql_test2.yaml" : "PWD"}'

### Environment
UAT

API superset version 1.5.0
any feature flags active:
VERSIONED_EXPORT=True from superset_config file
(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by chathawee** [comment]
I got the same error when trying to import the dashboard, chart, dataset, and database.

**Comment by reesercollins** [comment]
Are there any errors being thrown in your server's console?

**Comment by Naresh-Challa** [comment]
405 Method Not Allowed: The method is not allowed for the requested URL.
2022-06-22 11:23:15,272:WARNING:superset.views.base:405 Method Not Allowed: The method is not allowed for the requested URL.
172.23.0.1 - - [22/Jun/2022:11:23:15 +0000] "GET /api/v1/dashboard/import/ HTTP/1.1" 405 271 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36"
172.23.0.1 - - [22/Jun/2022:12:23:46 +0000] "POST /api/v1/security/login HTTP/1.1" 200 559 "-" "curl/7.65.0"
Command failed validation
2022-06-22 12:24:31,483:INFO:superset.dashboards.commands.importers.dispatcher:Command failed validation
Error importing dashboard
2022-06-22 12:24:31,484:WARNING:superset.views.base:Error importing dashboard
172.23.0.1 - - [22/Jun/2022:12:24:31 +0000] "POST /api/v1/dashboard/import/ HTTP/1.1" 422 339 "-" "curl/7.65.0"
172.23.0.1 - - [22/Jun/2022:15:06:26 +0000] "GET / HTTP/1.1" 302 243 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.124 Safari/537.36 Edg/102.0.1245.44"

**Comment by Naresh-Challa** [comment]
![image](https://user-images.githubusercontent.com/40595608/175296623-0272f6b7-c1d2-4934-8858-585808e688a1.png)

**Comment by rusackas** [comment]
I think this might have been resolved somewhere along the way, since we haven't heard of this issue in some time now. Since we're now on 3.1, on the verge of 4.0, we're not supporting 2.x  or prior versions actively. If anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)
