### ISSUE TITLE
Exported dashboards do not have "id" property causing re-importing to create duplicate dashboards

### ISSUE THREAD

**Issue by ghost** [apache/superset#20497]
I am trying to use the CLI to export a dashboard from one cluster and then import it into another cluster - essentially promoting updates between clusters (dev -> staging).

However, when I do this, I end up with duplicate dashboards after the import.

I tracked it down to https://github.com/apache/superset/blob/1.5.1/superset/dashboards/commands/importers/v0.py#L231 and noticed that the exported dashboards actually don't have an "id" property, so that if statement will never yield an existing dashboard object.

#### How to reproduce the bug

1. Export a dashboard via UI or CLI
2. Import it again via UI or CLI

### Expected results
Dashboard will be updated and not duplicated

### Actual results
Duplicate dashboards

#### Screenshots
N/A

### Environment

(please complete the following information):

- browser type and version: Chrome/102.0.0.0
- superset version: `1.5.1`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
N/A

**Comment by pfinnerty** [comment]
Any updates on this issue?

**Comment by rusackas** [comment]
I seem to recall this being fixed, but in any case, I'm closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem, or we can happily re-open this one.
