### ISSUE TITLE
Inconsistent storage time in metadata database

### ISSUE THREAD

**Issue by tenglong3158** [apache/superset#20501]
I find that the default values of the time types stored in the metadata database are inconsistent, both system local time and utc time. Does this cause confusion in how the program handles time and displays errors in different time zones?
As shown below:
![image](https://user-images.githubusercontent.com/20203245/175773486-61be83b6-f7e9-4366-9d22-1a8582de4466.png)

### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
