### ISSUE TITLE
SqlLab preview permissions error

### ISSUE THREAD

**Issue by mporracindie** [apache/superset#20511]
Permissions error on sql lab preview even tho the user has schema access.

#### How to reproduce the bug

1. Create a rol X with schema access on Y 
2. Give a user the following roles: X, Gamma and SqlLab
3. The user can now query the schema but the preview fails with:

```
You need access to the following tables: `%60___%60.%60___%60`,
            `all_database_access` or `all_datasource_access` permission
```

#### Screenshots

<img width="1204" alt="Screen Shot 2022-06-27 at 17 16 13" src="https://user-images.githubusercontent.com/42622776/176028028-9a884895-8dfd-4218-8011-f91917f1188b.png">

<img width="571" alt="Screen Shot 2022-06-27 at 17 16 38" src="https://user-images.githubusercontent.com/42622776/176028071-ab66e887-d129-45c6-8f3e-8d07c0b018f4.png">

### Environment

(please complete the following information):

- browser type and version: Chrome Version 102.0.5005.115 (Official Build) (arm64)
- superset version: `1.4.1`
- python version: `3.8.12`
- any feature flags active: No

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Since we're now on 3.1, on the verge of 4.0, we're not supporting 2.x  or prior versions actively. If anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)
