### ISSUE TITLE
static limit  for native filters recoreds

### ISSUE THREAD

**Issue by moathOSA** [apache/superset#20521]
i'm using a native filters in my dashboard and i have a filter with more than 1000 record
i noticed that there is now way to increase this filter limit ?
any key or config i missed ?

superset v1.5.0

=============================================================================

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mlmaverick** [comment]
@moathOSA any solution for this? Thanks!

**Comment by stasDomb** [comment]
I saw the old issue. And looks the solution wasn't merged:
https://github.com/apache/superset/issues/7971
But there are FilterBox, and the native filters are more actual now.
So, I don't know how I can resolve this issue

**Comment by rodmax** [comment]
Hi there.

looking through the code i found a couple of things

1️⃣ appropriate parameter from config:

```python
FILTER_SELECT_ROW_LIMIT = 10000
```
already set to `10000` but it does not affect **native filters** behavior

2️⃣  As i can see from front-end code the `row_limit` value just hard-coded
(I'm not sure, maybe somewhere further in the code this parameter is overridden)

https://github.com/apache/superset/blob/d130b4a24f67a6440101f267d2d3640e34f4a154/superset-frontend/src/dashboard/components/nativeFilters/utils.ts#L78 

It seems to me, native filter should use `FILTER_SELECT_ROW_LIMIT` or its own config parameter

**Comment by julizet** [comment]
@rodmax I am currently working on a Superset project and ran into the same project. 

I set `FILTER_SELECT_ROW_LIMIT = 10000` without any effect. If I trigger the query in the GUI I can see that the SQL statement still comes with `LIMIT 1000`.

Did you find any solution to increase the maximum rows that are returned by the native filters?
Appreciate any help.

**Comment by rodmax** [comment]
@julizet unfortunately no.
Native filters have too many limitations, so
We implemented our own filter as superset chart plugin, and now use it

**Comment by cleslie** [comment]
We're also having the same issue.

After some digging, as mentioned above, changing this value changes the default filter row limit: https://github.com/apache/superset/blob/d130b4a24f67a6440101f267d2d3640e34f4a154/superset-frontend/src/dashboard/components/nativeFilters/utils.ts#L78

Some potential options to improve this could be:
- Make this limit configurable via superset config file (not familiar enough with the project to understand if this is easy/acceptable since it is on the frontend)
- Implement new feature to allow users to set default row limit per filter via the UI (likely a much bigger change)

Keen to hear any other thoughts/suggestions.

**Comment by cleslie** [comment]
Have raised a draft PR with a way to customise this via a config value, any comments or feedback welcome: https://github.com/apache/superset/pull/24043

**Comment by rusackas** [comment]
PR merged!

**Comment by vivek-kandhvar** [comment]
> @julizet unfortunately no. Native filters have too many limitations, so We implemented our own filter as superset chart plugin, and now use it

@rodmax Do you mind sharing the code if you have forked? Even I am exploring in implementing our own filters.

**Comment by mayanklalwani** [comment]
did the changes in this PR work fine for anybody?

I am using superset version 2.0 and made changes in my code base in the 3 files mentioned in this PR, but they seem to have no effect for me.
