### ISSUE TITLE
Azure AD auth question

### ISSUE THREAD

**Issue by haripraghash** [apache/superset#20520]
#### How to reproduce the bug

Configure Azure AD OAuth

### Expected results
Should be able to login using Azure AD Creds.

### Actual results

what actually happens.

ERROR:flask_appbuilder.security.views:Error returning OAuth user info: 'upn'

#### Screenshots

`AUTH_TYPE = AUTH_OAUTH

      OAUTH_PROVIDERS = [
      {
        "name": "azure",
        "icon": "fa-windows",
        "token_key": "access_token",
        "remote_app": {
            "client_id": "id",
            "client_secret": "pass",
            "api_base_url": "https://login.microsoftonline.com/tenantid/v2.0",
            "client_kwargs": {
                "scope": "openid email profile offline_access",
                "resource": "clientid",
            },
            "request_token_url": None,
            "jwks_uri": "https://login.microsoftonline.com/common/discovery/v2.0/keys",
            "access_token_url": "https://login.microsoftonline.com/tenantid/oauth2/v2.0/token",
            "authorize_url": "https://login.microsoftonline.com/tenantid/oauth2/v2.0/authorize",
          }
          }`

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sfirke** [comment]
The following works successfully for me - a little different than yours, including I have `upn` in my scope:

```
OAUTH_PROVIDERS = [
{
    "name": "azure",
    "icon": "fa-windows",
    "token_key": "access_token",
    "remote_app": {
        "client_id": [client_id],
        "client_secret": [secret],
        "api_base_url": "https://login.microsoftonline.com/[tenantid]/oauth2",
        "client_kwargs": {
            "scope": "User.read name preferred_username email profile upn groups",
            "resource": client_id,
        },
        "request_token_url": None,
        "access_token_url": "https://login.microsoftonline.com/[tenantid]/oauth2/token",
        "authorize_url": "https://login.microsoftonline.com/[tenantid]/oauth2/authorize",
    },
},
]
```

**Comment by rusackas** [comment]
Assuming fixed based on the helpful comment from @sfirke (thanks!)

**Comment by Narender-007** [comment]
i am following above azure that but getting upn error


<img width="563" alt="image" src="https://github.com/apache/superset/assets/57932042/883ca210-9935-45dc-a46a-bf81fcaddcef">

**Comment by houqp** [comment]
@Narender-007 in your azure ad app registration view, make sure you have upn added as an optional claim.

**Comment by dcarvalhal** [comment]
How resolve the problem of authentication URL of superset is http and azure AD just accept https url?

**Comment by CisorKnight** [comment]
@dcarvalhal Facing the same issue here, did you manage to find a solution ?

**Comment by Narender-007** [comment]
> > i am following above but getting upn error
> > { "name": "azure", "icon": "fa-windows", "token_key": "access_token", "remote_app": { "client_id": "******************, "client_secret": "*****************************15", "api_base_url": "https://login.microsoftonline.com/*************************7e/oauth2", "client_kwargs": { "scope": "User.read name preferred_username email profile upn groups", "resource": "************************e2", }, "request_token_url": None, "access_token_url": "https://login.microsoftonline.com/******************7e/oauth2/token", "authorize_url": "https://login.microsoftonline.com/**********************7e/oauth2/authorize", }, },
> > <img alt="image" width="563" src="https://user-images.githubusercontent.com/57932042/256450529-883ca210-9935-45dc-a46a-bf81fcaddcef.png">
> 
> Hello guys ,

user this steps then login successfully have worked.

steps:
Go to Active Directory page select users
Create new user remember username and password
select app registration name
left side navigation Select owners click add users 
Add this library authlib in  requirements-local.txt file
restart docker container.

**Comment by Narender-007** [comment]
> > > i am following above but getting upn error
> > > { "name": "azure", "icon": "fa-windows", "token_key": "access_token", "remote_app": { "client_id": "******************, "client_secret": "*****************************15", "api_base_url": "https://login.microsoftonline.com/*************************7e/oauth2", "client_kwargs": { "scope": "User.read name preferred_username email profile upn groups", "resource": "************************e2", }, "request_token_url": None, "access_token_url": "https://login.microsoftonline.com/******************7e/oauth2/token", "authorize_url": "https://login.microsoftonline.com/**********************7e/oauth2/authorize", }, },
> > > <img alt="image" width="563" src="https://user-images.githubusercontent.com/57932042/256450529-883ca210-9935-45dc-a46a-bf81fcaddcef.png">
> > 
> > 
> > Hello guys ,
> Microsoft main din't login in superset 

> user this steps then login successfully have worked.
> 
> steps: Go to Active Directory page select users Create new user remember username and password select app registration name left side navigation Select owners click add users Add this library authlib in requirements-local.txt file restart docker container.

**Comment by CisorKnight** [comment]
Thanks @sharky93 redirection works with ENABLE_PROXY_FIX = True

I still have the error so I can't login but I feel like it's more Azure-side
![image](https://github.com/apache/superset/assets/36819171/16175a5f-33c6-4ea6-889f-07c9fd02fac7)

**Comment by sfirke** [comment]
For future Superset admins using Azure AD, FYI that I have updated my Superset config to use the `/v2.0` OAuth2 endpoint. This fixed a problem where we required 2-factor authentication on the Azure side but Superset login was only triggering a username/password login, causing the login to fail.

I have submitted the updated config back to Flask-AppBuilder as a pull request, in the meantime you can see it here: https://github.com/dpgaspar/Flask-AppBuilder/pull/2350
