### ISSUE TITLE
[Big Number with Trendline] Tooltip value is hidden

### ISSUE THREAD

**Issue by ValentinC-BR** [apache/superset#20531]
There is a "cosmetic issue" on "Big Number With Trendline" charts.
We can't read the tooltip value anymore.

I labelled it as "Bug" as it is very painful and clearly affect our end-users (dashboard readers).

#### How to reproduce the bug

1. Create a big number with trendline 
2. Add it to a dashboard
3. Save the dashboard
4. Hover on the line and try to read the value

### Expected results

We should be able to read the line value.

### Actual results

The value is hidden.

#### Screenshots

![image](https://user-images.githubusercontent.com/79460908/176377903-cbd9ed1f-182f-4917-8c9a-fb13ce38c749.png)

### Environment

(please complete the following information): 
- browser type and version: Google Chrome Version 103.0.5060.53 (Official Build) (x86_64)
- superset version: 1.5
- python version: 3.9
- node.js version: /
- any feature flags active: /

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

The bug wasn't present in the earlier version of Superset (1.4 and before)

**Comment by stephenLYZ** [comment]
@ValentinC-BR Hi, this issue has been fixed by https://github.com/apache/superset/pull/20029. Please let me know if it makes sense and then we can close this one.

**Comment by ValentinC-BR** [comment]
Is this bug fix included in the current 1.5 release ?
