### ISSUE TITLE
[Area Chart] Can't change the Y-axis name

### ISSUE THREAD

**Issue by ValentinC-BR** [apache/superset#20538]
## Screenshot

![image](https://user-images.githubusercontent.com/79460908/176387228-60163112-095d-4369-bc9d-8b3e0456673c.png)

## Description

There is no option to change the name of the Y-axis in an area chart.

We can't use the TimeSeries area chart (which includes this option), because there are regressions that need to be handled.

## Design input

There should be the same option as the X-axis : "Y axis label"

**Comment by stephenLYZ** [comment]
@ValentinC-BR Hi,  We currently recommend using area chart v2, please let me know if it meets your needs. Thanks

**Comment by ValentinC-BR** [comment]
Hello,

As I said right above, we can't use the TimeSeries area chart, because there are regressions that need to be handled, especially the expand/stack option.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we've made a lot of improvements with axis controls. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
