### ISSUE TITLE
Calculated columns can't be used in time filters - Wrong data type

### ISSUE THREAD

**Issue by ValentinC-BR** [apache/superset#20539]
If a calculated column is used as a time column, an error occurs : the WHERE clause is not adapted.

### How to reproduce the bug

1. Create a calculated column with DATETIME type and tick the "time column" checkbox
2. Create a chart and use this calculated column as time column
3. Filter on "Last week"
4. Run
5. See error

### Expected results

The query should run without any problem

### Actual results

An error occurs : `Error: SYNTAX_ERROR: line 5:20: '>=' cannot be applied to date, varchar(26)`

##### Config 

![image](https://user-images.githubusercontent.com/79460908/176393222-a3fb79e5-3f22-4f37-9113-e9564a9785fa.png)

#### Error

![image](https://user-images.githubusercontent.com/79460908/176393028-f98382a2-abe2-477f-ae67-bb4ba7b13000.png)

#### Cause

![image](https://user-images.githubusercontent.com/79460908/176393464-44c33efd-6fee-4d9b-b218-9373f0c9370b.png)

### Environment

(please complete the following information):

- browser type and version: Google Chrome Version 103.0.5060.53 (Official Build) (x86_64)
- superset version: 1.5
- python version: 3.9
- node.js version: /
- any feature flags active: /

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Already present in the earlier versions of Superset

**Comment by ShaliniIruvuru** [comment]
Working as Expected. Got the result that new calculated column passed to time column.

Screenshots:-
![image](https://user-images.githubusercontent.com/115684419/230375558-2880872f-fe8c-416e-a725-09a92a6b07ca.png)
![image](https://user-images.githubusercontent.com/115684419/230375611-69335103-ee93-4104-a39c-0a7e3d91c6d2.png)
Loom video:-
https://www.loom.com/share/341e157f81c943f6ac5943e6a27c9be0

**Comment by rusackas** [comment]
Sounds like we can close this. Thanks again for the help @ShaliniIruvuru !
