### ISSUE TITLE
[Boxplot] A (unrelevant) sampling is done when building the chart

### ISSUE THREAD

**Issue by ValentinC-BR** [apache/superset#20533]
The boxplot makes a sampling by reading only the 10k first rows.
By doing this, it takes the 10k first rows of the database, which is not random at all and the displayed boxplot is completely wrong (Med, Q1, Q2 are <b>really</b> different)

#### How to reproduce the bug

1. Make a boxplot on a database containing more than 10k rows
2. Display the results

### Expected results

The boxplot should be made on the total database (using a GROUP BY function in the query for instance)

### Actual results

The boxplot is made on the 10k first rows

#### Screenshots

/

### Environment

(please complete the following information):

- browser type and version: Google Chrome Version 103.0.5060.53 (Official Build) (x86_64)
- superset version: 1.5
- python version: 3.9
- node.js version: /
- any feature flags active: /

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

/

**Comment by rusackas** [comment]
I don't know of a good way to get random rows, but we're open to proposals/PRs here. Meanwhile, closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog.

**Comment by ValentinC-BR** [comment]
Hi,
The issue is still present, and to be honest, we never use this chart in our company because the results are wrong.

I wonder if it wouldn't be better to remove the chart rather than letting it display false results.

**Comment by ValentinC-BR** [comment]
A possibility would be to build the histogram inside the query, rather than selecting ALL the rows in the query (hence reaching the limit) and making the distribution afterwards.

**Comment by rusackas** [comment]
Agreed, a virtual dataset could solve this... but like this issue's parallel thread we have going, maybe enhancing the plugin to query random rows is possible... I'm just not sure.
