### ISSUE TITLE
[Dataset] "Owners are invalid" when editing a dataset

### ISSUE THREAD

**Issue by ValentinC-BR** [apache/superset#20535]
We often get an error message when editing a table : "Owners are invalid"
This is due the owner of the datasource being set (automatically) to "unknown unknown"

We need to manually remove the owner and save the datasource afterwards

#### How to reproduce the bug
 
<b>WARNING</b> : I am not sure how to exactly reproduce the bug, but it often occurs

### Expected results

I should be the owner of the chart

### Actual results

The owner of the chart is "Unknown unknown"

#### Screenshots

![image](https://user-images.githubusercontent.com/79460908/176645746-11927fb9-7392-4489-b746-1e3086e55499.png)

### Environment

(please complete the following information):

- browser type and version: Google Chrome Version 103.0.5060.53 (Official Build) (x86_64)
- superset version: 1.5
- python version: 3.9
- node.js version: /
- any feature flags active: /

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

/

**Comment by rusackas** [comment]
I recall this being fixed quite some time ago, but is pretty stale if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem, or we can re-open this issue.
