### ISSUE TITLE
Logged in user when disabled is not logged out

### ISSUE THREAD

**Issue by ThiagoAndrad** [apache/superset#20547]
#### How to reproduce the bug

1. login with an admin user
2. login with another user in a private tab
3. Deactivate the second user with admin user
4. Go back to the private tab where the second deactivated user is logged in. See that it is still possible to continue using the platform

### Expected results

The deactivated user should be redirected to login page

### Actual results

The deactivated user continues to use the platform normally

#### Screenshots
...

### Environment

(please complete the following information):

- browser type and version: Brave 1.37.109
- superset version: 1.5.1
- python version: official superset docker image
- node.js version:
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
Sorry for the delayed answer here, I've got a fix for this issue: https://github.com/dpgaspar/Flask-AppBuilder/pull/2192
Will make a release soon and integrate it on Superset.
