### ISSUE TITLE
In chart editor opening existing filter will not show actual operation

### ISSUE THREAD

**Issue by comdiv** [apache/superset#20542]
When edit existing filter options - operation is not shown correctly in edit form

#### How to reproduce the bug

1. Open any example chart, for example `Commute Time`
2. Click on any filter option in FILTERS 
3. SIMPLE tab shown in editor
4. Operation is not set!

### Expected results

Actual operation shown

### Actual results

No operation is choosed in list box

#### Screenshots

![image](https://user-images.githubusercontent.com/2387862/176423208-f51b0a00-02dd-4574-93b1-1b0061994e96.png)

**Comment by rusackas** [comment]
I believe this was fixed.... I'm not able to replicate this in current Superset.
