### ISSUE TITLE
Cannot localize Superset to RU language when run with docker compose.

### ISSUE THREAD

**Issue by comdiv** [apache/superset#20541]
Try to set it with docker/pythonpath_dev/superset_config.py

#### How to reproduce the bug

1. go to `superset` root
2. open docker/pythonpath_dev/superset_config.py  add `BABEL_DEFAULT_LOCALE = "ru"` and save
3. launch `docker-compose -f docker-compose-non-dev.yml up -d`
4. open `127.0.0.1:8088`

### Expected results

UI would be in Russian language

### Actual results

UI still in English language

**Comment by artemonsh** [comment]
Solution is probably the same as described here: https://github.com/apache/superset/issues/14848#issuecomment-1313322076

**Comment by rusackas** [comment]
Hopefully, the answer above is sufficient to close this thread. I'll do so anyway since it's been so long since there was a comment here. If this needs revisiting/reopening, just say the word.
