### ISSUE TITLE
personal reports not working when other reports exist for same dashboard

### ISSUE THREAD

**Issue by MM-Lehmann** [apache/superset#20544]
When a dashboard has any associated report (can be deactivated) already, personal reports cannot be created. webserver container complains: `Resource already has an attached report.`
#### How to reproduce the bug

1. schedule report for any dashboard (from the alerts & reports section)
2. go to same dashboard
3. Click on report icon (calendar icon)
4. click on `add`
5. See error in UI & console (webserver)

### Expected results

report gets scheduled without errors

### Actual results

error in UI & webserver console. Report will not create unless first report is removed.

#### Screenshots

![image](https://user-images.githubusercontent.com/15945561/176431346-1c4baadb-4e8f-4a0c-b296-49075893c2f2.png)

### Environment

(please complete the following information):

- browser type and version:
- superset version: `1.5.0`
- python version: `3.8.12`
- any feature flags active: alerts_reports

**Comment by rusackas** [comment]
We're now on 3.1, on the verge of 4.0, and not supporting 2.x  or prior versions actively. If anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)
