### ISSUE TITLE
Unexpected number of applyed filters in some charts

### ISSUE THREAD

**Issue by comdiv** [apache/superset#20558]
While same filters are applyed to all charts of the dashboard - different charts shown different count of filters

#### How to reproduce the bug

1. Open `Sales dashboard` example
2. Go to `Exploratory` tab
3. Set `Time Range Filter` and `Product Line Filter`
4. Back to `Sales overview`
5. All charts shows same `2 filters applyed`
6. Go to `Exploratory`
7. Reset `Time Range Filter` to `No filter`
8. Back to `Sales overview`
9. Some of charts show expected `1 filter`, but some still show `2 filter`

### Expected results

Same filter setting would cause same visible indicataion

### Actual results

Filter apply indication is not based just on filters itself, but has some entropy due to chart type (?)

#### Screenshots

![image](https://user-images.githubusercontent.com/2387862/176585630-75ea7b52-47af-4a57-a928-45162f89597f.png)

**Comment by rusackas** [comment]
Can you please confirm if this is still an issue, particularly in 2.0.0 and/or the latest 2.0.1 release candidate?
