### ISSUE TITLE
Invalid indication and reedit of CUSTOM SQL columns in Chart Editor

### ISSUE THREAD

**Issue by comdiv** [apache/superset#20562]
In `pivot table v2` setup, columns section (may be in all similar UI) - if you create CUSTOM SQL column, while it will be working - you will not see it's name in columns list, if you reopen it for edit  - you will not see custom function - it will be lost.

#### How to reproduce the bug

1. Create Pivot Table v2 for any dataset
2. In column list click `add column`
3. Choose `custom sql`
4. Assign name for query and write any legal sql function for column in text area
5. Save column
6. Empty column line will be in UI
7. Apply columns to table - all will be working fine
8. Reopen column for editing - all data - name and content will be lost!

### Expected results

1. After setup UI shows title for custom coolumn or it's function digest
2. Reopen for edit will keep custom function in editor box

### Actual results

1. Column information not shown
2. Reopen for edit opens empty editor without previous state

#### Screenshots

![image](https://user-images.githubusercontent.com/2387862/176612280-008773ea-485f-4355-bead-1591b86b268f.png)

![image](https://user-images.githubusercontent.com/2387862/176612389-af348a25-4dca-496e-b520-d3731ee95b06.png)

![image](https://user-images.githubusercontent.com/2387862/176612522-753528ef-fe6b-4b1d-afe5-e1b8f99955b7.png)

**Comment by rusackas** [comment]
I'm unable to reproduce this in current Superset (3.1)
