### ISSUE TITLE
No valid indication of progress and/or button locking in CSV upload interface

### ISSUE THREAD

**Issue by comdiv** [apache/superset#20563]
When pressing `Save` button in upload csv interface - no any indication that process is running, no button locking to prevent invalid double-send, secondary click on `save` couses real double send.

#### How to reproduce the bug

1. Go to databases -> upload file
2. Fill form with valid and large CSV (upload time should be long)
3. Press save
4. Nothing is changin on page, only (if tab size is big and your browser shows them) tab header of browser shows `loading`
5. You still can press Save twice and tripple and force duplicate upload to occure

### Expected results

When user presses `Save` button (`Upload` name would be clear) UI should
1. lock `Save` button to preven duplicate send of same file - it's **required**
2. explicitly show some indication that opearation is in progress (text box with message at least) - it's **suggested**

### Actual results

Form not reacts ergonomically on `Save` button press. 
The only indication is provided by browser (and it's not guarantee, while if you have many tabs - you don't see load indication)
But along to ergonomy problem - it is buggy, while Save button still allowed and can cause duplicate upload

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current-era Superset, but I'm closing it as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
