### ISSUE TITLE
/dashboard/new/ redirect http 302 with http scheme is not a good idea cause web page can not load in https web site

### ISSUE THREAD

**Issue by missyoyo** [apache/superset#20577]
#### How to reproduce the bug

1. When we click 'add dashboard' BTN, We access URI is "/dashboard/new/"  which superset return http 302 location like this "http://superset_ip/superset/dashboard/20/?edit=true"
2. I think this is not a good idead,because http:// is not needed here,superset only need return http 302 location like this "/superset_ip/superset/dashboard/20/?edit=true"
3. with http scheme will cause issue when we use https site and use iframe, as our site use https, browser will not load any http content as "Mixed content blocking"
4. So is it possible to change it return relative path?

#### Screenshots

![图片](https://user-images.githubusercontent.com/19371588/176820795-32828b0d-fdf2-4c2e-a5cf-5aa18e71b672.png)

### Environment

(please complete the following information):

- browser type and version: Firfox 90
- superset version: `superset version`1.5.0
- python version: `python --version`
- node.js version: `node -v` 
- any feature flags active:

**Comment by alldoami** [comment]
I am running into this same issue when trying to iframe my charts.

**Comment by binodyadav6119** [comment]
Hi @missyoyo @alldoami Any idea to resolve above issue

**Comment by emrekmrc** [comment]
I've same problem. Any idea to resolve ?

**Comment by orkunevran** [comment]
same issue here. any workaround or progress?

**Comment by Sopholos** [comment]
thread up. same issue here

**Comment by rusackas** [comment]
This bug was reported on Superset 1.5.0. Can anyone confirm if it's still an issue in 3.1/4.0?

**Comment by orkunevran** [comment]
> This bug was reported on Superset 1.5.0. Can anyone confirm if it's still an issue in 3.1/4.0?

After versiyon upgrade, issue is resolved.

**Comment by rusackas** [comment]
Awesome! Closing, but happy to revisit/reopen if warranted.

**Comment by ericsong** [comment]
I'm actually still seeing this issue in 3.1.3 and 4.0.1. This PR https://github.com/apache/superset/pull/28754 fixes it for me.
