### ISSUE TITLE
[SQL Lab] Saved Queries do not include parameters

### ISSUE THREAD

**Issue by kamalkeshavani-aiinside** [apache/superset#20576]
If a query with parameters is saved, the parameters are not stored with the query. So when executing a saved query, query fails without the necessary parameters.

#### How to reproduce the bug

1. Create a query with parameters
2. Run and save the query
3. Go to Saved Queries, and run in SQL Lab

### Expected results

Saved Query should have the parameters.

### Actual results

Saved Query does not have parameters.

### Environment

- browser type and version:
- superset version: `master`
Dockerhub image
- any feature flags active: ENABLE_TEMPLATE_PROCESSING

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

In 'saved_query' table of metadata, there is column 'extra_json' which can/should be used to store the parameters.

**Comment by nbalusu** [comment]
I have the same issue in 1.5.1. I was able to set parameters, after I saved the query I am not able to see saved parameters.. The only work around I figured is to save the parameters in description. copy params from description every time I run. Can someone please let me know If I miss any config to save params. Thanks!

**Comment by kenho811** [comment]
I confirm that this same behaviour persists in 2.0.0.

![image](https://user-images.githubusercontent.com/57944769/193412031-f9412abf-d5d1-42ae-ac6e-989fdd9d8790.png)


I am not sure if it's meant to be like this, but It would be great that when the SQL template is saved in SQL Lab, the parameters are saved together as well.
