### ISSUE TITLE
Allow Chart owners (not admins) to explore their charts.

### ISSUE THREAD

**Issue by BETEP0K1** [apache/superset#20599]
a user without administrator rights does not see their own Charts. Right - can read on Chart, can write on Chart he has. superset/superset/config.py
  DASHBOARD_RBAC : true

**Comment by BETEP0K1** [comment]
1.5.2. tested -  bug not fixed yet.

**Comment by rusackas** [comment]
I don't quite understand the issue... can you confirm this is a problem on 2.0, and if so, provide some more steps or a reproducible scenario to test this bug?

**Comment by rusackas** [comment]
This version of Superset is no longer supported. If anyone is still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
