### ISSUE TITLE
Dahsboard doesn't load on Opera Browser until I click the "Filters out of scope" button

### ISSUE THREAD

**Issue by NikosSpanos** [apache/superset#20592]
I have created a quite large Dashboad on Superset and when I refresh the Opera Browser window the Dashboard won't show any Tab or Chart until I press the "Filters out of scope". I have also tested this in Chrome Browser.

So briefly I will post some screenshots to elaborate more.

1st image: The dashboard loading screen after refresh

![289831735_572160291292367_1424599434960135324_n](https://user-images.githubusercontent.com/38804710/176996188-60c052fa-8f49-4b4a-bf4a-8476451e0437.png)

As you can see the dashboard refreshes non-stop.

Then when I click "Filters out of scope" button (genuinely the filters) I can see the dashboard visuals.

![289060560_716095922948431_8012930165700553370_n](https://user-images.githubusercontent.com/38804710/176996238-b6c8b94a-500a-452e-9b98-029b795bd05e.png)

Is there any configuration that I am might missing here? Is this fixable? Thanks in advance for any help and comment.

**Comment by nytai** [comment]
@NikosSpanos do any of your filters have `select first filter value by default` enabled? I have noticed this issue when that option is selected. Disabling it should fix this issue as a workaround, but it does appear to be a bug with that config.

**Comment by sfirke** [comment]
This was fixed in https://github.com/apache/superset/pull/23299.
