### ISSUE TITLE
Translation process in Dockerfile does not work.

### ISSUE THREAD

**Issue by flowerkzj** [apache/superset#20597]
https://github.com/apache/superset/blob/8a57a71bed30a781a1d5e5b2ce42ccd08045b3e9/Dockerfile#L108

The superset only can be translated partly which only translate the codes in js but not python.

Therefore I replace it with codes below:

```
&& pybabel compile -d superset/translations || echo "warning: something is wrong"
```

Although it can solve some way, it seems not an elegant way. Hope for an official solution.

**Comment by artemonsh** [comment]
Sadly, I have the same issue but the requested solution does not work for me

**Comment by vivek-kandhvar** [comment]
Right, the `flask fab babel-compile --target superset/translations` command they are using is not a blocking call, and it moves on to the next step without waiting for this command to finish.  

The above proposed solution works fine.

@artemonsh What's the issue?

**Comment by rusackas** [comment]
Is this still an issue? I presume so. I thought the backend uses the `.mo` files that are produced by the script, but ignored by git. I haven't validated all that... but I'm curious if this is still an issue, or if we need documentation updates, or what.

**Comment by rusackas** [comment]
Closing as stale, but probably also irrelevant. A lot of this has been revamped lately. Certain build processes take care of generating .mo/.json files automatically, and the .pot/.po file generation process has been smoothed out a bit. We'll continue to add CI and make this more automatic in the future.
