### ISSUE TITLE
[SIP-86] Migrate away from pyhive

### ISSUE THREAD

**Issue by sjoerd222888** [apache/superset#20608]
### Motivation

[PyHive](https://github.com/dropbox/PyHive) is currently unsupported.

### Proposed Change

Migrate away from pyhive and use impyla https://github.com/cloudera/impyla instead. This can be done already, the main objective would probably be to update the documentation.
Maybe there are other references (be it in code or documentation) that would need to be removed.

### New or Changed Public Interfaces

No new feature

### New dependencies

No new dependencies

### Migration Plan and Compatibility

No migration needed

### Rejected Alternatives

Stay with PyHive as the default recommendation to connect to Hive.

**Comment by bkyryliuk** [comment]
I believe it would be even easier to just implement hive / presto connectors through impala & switch the defaults to it + allow users to choose pyhive if desired via connection string.

**Comment by rusackas** [comment]
Is there intent to carry this forward to a [DISCUSS] thread on the dev mailing list?

**Comment by bkyryliuk** [comment]
closing as it is inactive
contributions to use impala are definitely welcome !
