### ISSUE TITLE
Docker install dremio driver gives error

### ISSUE THREAD

**Issue by mstoffel-sag** [apache/superset#20603]
In a docker environment including Dremio driver results in an error

#### How to reproduce the bug

Follow docker install docs. Have a running superset. Follow the instructions to add driver in docker 
add  requirements-local.txt to docker dir 
docker-compose build --force-rm
docker-compose up

### Expected results

working Dremio driver

### Actual results

superset_worker_beat    |   Running setup.py install for pyodbc: finished with status 'error'
superset_worker_beat    |   error: subprocess-exited-with-error
superset_worker_beat    |   
superset_worker_beat    |   × Running setup.py install for pyodbc did not run successfully.
superset_worker_beat    |   │ exit code: 1
superset_worker_beat    |   ╰─> [14 lines of output]
superset_worker_beat    |       running install
superset_worker_beat    |       running build
superset_worker_beat    |       running build_ext
superset_worker_beat    |       building 'pyodbc' extension
superset_worker_beat    |       creating build
superset_worker_beat    |       creating build/temp.linux-x86_64-3.8
superset_worker_beat    |       creating build/temp.linux-x86_64-3.8/src
superset_worker_beat    |       gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DPYODBC_VERSION=4.0.32 -I/usr/local/include/python3.8 -c src/buffer.cpp -o build/temp.linux-x86_64-3.8/src/buffer.o -Wno-write-strings
superset_worker_beat    |       In file included from src/buffer.cpp:12:
superset_worker_beat    |       src/pyodbc.h:56:10: fatal error: sql.h: No such file or directory
superset_worker_beat    |          56 | #include <sql.h>
superset_worker_beat    |             |          ^~~~~~~
superset_worker_beat    |       compilation terminated.
superset_worker_beat    |       error: command 'gcc' failed with exit status 1
superset_worker_beat    |       [end of output]
superset_worker_beat    |   
superset_worker_beat    |   note: This error originates from a subprocess, and is likely not a problem with pip.
superset_worker_beat    | error: legacy-install-failure
superset_worker_beat    | 
superset_worker_beat    | × Encountered error while trying to install package.
superset_worker_beat    | ╰─> pyodbc
superset_worker_beat    | 
superset_worker_beat    | note: This is an issue with the package mentioned above, not pip.
superset_worker_beat    | hint: See above for output from the failure.
superset_worker_beat    | WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
superset_worker_beat    | You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
superset_worker_beat    |   Preparing metadata (setup.py): finished with status 'done'
superset_worker_beat    | Requirement already satisfied: pyarrow in /usr/local/lib/python3.8/site-packages (from sqlalchemy_dremio->-r /app/docker/requirements-local.txt (line 1)) (5.0.0)
superset_worker_beat    | Requirement already satisfied: numpy>=1.16.6 in /usr/local/lib/python3.8/site-packages (from pyarrow->sqlalchemy_dremio->-r /app/docker/requirements-local.txt (line 1)) (1.22.1)
superset_worker_beat    | Building wheels for collected packages: pyodbc
superset_worker_beat    |   Building wheel for pyodbc (setup.py): started
superset_worker         |   Building wheel for pyodbc (setup.py): finished with status 'error'
superset_worker         |   error: subprocess-exited-with-error
superset_worker         |   
superset_worker         |   × python setup.py bdist_wheel did not run successfully.
superset_worker         |   │ exit code: 1
superset_worker         |   ╰─> [14 lines of output]
superset_worker         |       running bdist_wheel
superset_worker         |       running build
superset_worker         |       running build_ext
superset_worker         |       building 'pyodbc' extension
superset_worker         |       creating build
superset_worker         |       creating build/temp.linux-x86_64-3.8
superset_worker         |       creating build/temp.linux-x86_64-3.8/src
superset_worker         |       gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DPYODBC_VERSION=4.0.32 -I/usr/local/include/python3.8 -c src/buffer.cpp -o build/temp.linux-x86_64-3.8/src/buffer.o -Wno-write-strings
superset_worker         |       In file included from src/buffer.cpp:12:
superset_worker         |       src/pyodbc.h:56:10: fatal error: sql.h: No such file or directory
superset_worker         |          56 | #include <sql.h>
superset_worker         |             |          ^~~~~~~
superset_worker         |       compilation terminated.
superset_worker         |       error: command 'gcc' failed with exit status 1
superset_worker         |       [end of output]
superset_worker         |   
superset_worker         |   note: This error originates from a subprocess, and is likely not a problem with pip.
superset_worker         |   ERROR: Failed building wheel for pyodbc
superset_worker         |   Running setup.py clean for pyodbc

### Environment

(please complete the following information):
Docker of version 0.6.3 git repo
- browser type and version: safari
- superset version: `0.6.3`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
This is likely not an issue any longer, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
