### ISSUE TITLE
Stackable bar sort by value. Is it possible?

### ISSUE THREAD

**Issue by lyckety** [apache/superset#20609]
Good afternoon!

I have a dataset that describes how many steps a person has taken at a time.

I build a stackable bar chart from this data so that I can see how many steps a certain person took in an hour.

I'm having difficulty with a stackable column. I would like to sort inside a column of people not alphabetically, but by number of steps taken. For example, a person named "John" has walked the most and should be at the top of the column.

![Screen 2022-07-05 17-04-07](https://user-images.githubusercontent.com/42245827/177348860-52b747c8-bcab-437e-a994-cd02937a43a4.png)

Is it possible to sort group by name within a stackable column?

To build a chart I use "Time-series Bar Chart v2"

I would be very grateful for your help and advice.

**Comment by sfirke** [comment]
No, I believe this functionality is missing from Bar Chart v2 as of version 2.0.0.  You can control sorting in the older bar chart types.  Here's a feature request discussion: https://github.com/apache/superset/discussions/20885.

**Comment by lyckety** [comment]
@sfirke, thank you for your reply.

There is one nuance in the legacy diagram. Sorting in bars takes place not within the selected time duration, but for the last day (by filter).

If the filter is Last day and Kate has walked more than John during this day, but less during a single hour, then in the bar at this hour she will stand in front of him
