### ISSUE TITLE
(docs) Broken navigation in the docs

### ISSUE THREAD

**Issue by a-mroz** [apache/superset#20634]
When docs page is not opened through the main [page](https://superset.apache.org/) the link to the `Installing Superset Locally Using Docker Compose` on the `Introduction` page is broken.

#### How to reproduce the bug

1. Go to https://superset.apache.org/docs/intro (directly, not using the link on the main page).
2. Click on `Docker Compose` (in the `Setup Superset locally with one command using Docker Compose` string).
3. Observe redirect to `https://superset.apache.org/docs/intro/installation/installing-superset-using-docker-compose` (notice the `/intro/` part of the URL – it should not be there).
4. Refresh and observe `Not Found` standard httpd website. 

### Expected results

Internal navigation should work regardless of the entry point.

### Actual results

We're redirected to an incorrect URL (it thinks it's a child page of the current page, while it's not).

#### Screenshots
![image](https://user-images.githubusercontent.com/505546/177701331-16e09dec-b812-4612-85fb-8499fd4cb0ba.png)

![image](https://user-images.githubusercontent.com/505546/177701372-fbcad8ff-360e-4efe-9f07-50340ba8d06a.png)

### Environment
Chromium 103.0.5060.53
Firefox 102.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [N/A] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset. (documentation website should have the latest released version) 
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

- I wasn't able to reproduce it with other URLs, possibly it's connected to navigation between two sections? (from `Introduction` to `Installation and Configuration`). I wasn't able to find such a link.
- It seems to work fine when you: open the intro docs page; go, through the left side panel, to the `Installing Locally Using Docker Compose`; go back to `Introduction`; open `Docker Compose` through the link.

**Comment by stephenLYZ** [comment]
@a-mroz Hi Thanks for your attention! I think it might be related to some links not working. It would be great if you could open a PR to fix it.

**Comment by rusackas** [comment]
This no longer seems to be the case. Closing :)
