### ISSUE TITLE
[Import] Unable to import Dashboard using Rest API

### ISSUE THREAD

**Issue by rahul149386** [apache/superset#20655]
Hi, 

I'm implementing importing dashboard using REST API. The response received 200 but when I checked in the Superset, it is not published. It is happing for the existed or new dashboard. Could you recommend me pls to resolve this isse.

 
![image](https://user-images.githubusercontent.com/56782848/178014510-c9b162de-e246-432f-b4c3-f0d95be24a21.png)

**Comment by rahul149386** [comment]
Any Update on this ticket.

**Comment by rahul149386** [comment]
I'm using couple of methods to import superset dashboard but I'm getting failed. Anyone kindly have a look into this.

Method1: Using Request : 

session  = requests.session()
r = session.post(base_url + '/api/v1/security/login', json=payload)
access_token = r.json()

headersAuth = {
    'Authorization': 'Bearer ' + access_token['access_token']
}
csrf_token = requests.get(
    url=base_url+'/api/v1/security/csrf_token/',
    headers=headersAuth
).json()["result"]
data = {
        'username': 'admin',
        'password': 'password',
        'csrf_token':csrf_token
}
session.post(f'{base_url}/login/', data=data)
cookies=dict(session.cookies)
cookies=cookies['session']
dashboard_path='dashboard_path'

import_url=base_url+'/api/v1/dashboard/import/'
headers = {
    'accept': 'application/json',
    'Authorization':headersAuth['Authorization'],
    'X-CSRFToken': csrf_token,
    'Cookies':f'Session={cookies[1:]}',
    'Referer': import_url
}

files = {
    'formData': (
        dashboard_path,
       open(dashboard_path, 'r'),
        'application/json'
    )
}
response = requests.post(import_url, files=files, headers=headers)
print(response)
session.close()
Eroor:
Getting an Response 200 but unable to see the dashboard in the superset
![image](https://user-images.githubusercontent.com/56782848/178491686-5bbc2cce-a8cb-4df2-b9f3-a04e205d16eb.png)

Method2: Running a Curl though python
lst1=f'curl --location --request POST {import_url}\ -H "X-CSRFToken:{csrf_token}"\ -H "Authorization:{Authorization}"\ -H "Cookie:session={cookies}"\--form "formData=@"{dashboard_path}""\ --form "overwrite="true"'
args = lst1.split(maxsplit=-1)
print(args)
process = subprocess.Popen(args,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
stdout,stderr= process.communicate()
Error:
Could not resolve host:\ncurl: (3) URL using bad/illegal format or missing URL\n'

Anyone responses will be apprciated.

**Comment by musicmuthu** [comment]
Hi @rahul149386  
Can you please share the right one
