### ISSUE TITLE
Redis not found when installing superset using helm

### ISSUE THREAD

**Issue by Jap8nted** [apache/superset#20658]
I am installing superset using helm chart, when service is running and want to create a new chart I get this:

#### How to reproduce the bug

1. Create new chart
2. See error

### Expected results
Chart gets created

### Actual results

what actually happens.

``` File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -2 connecting to apps-dev-superset-redis-headless:6379. Name or service not known.
```
#### Screenshots
![grafik](https://user-images.githubusercontent.com/5432705/178060220-40cd73d7-0aa8-4dd4-be05-01cf57bfbfe2.png)

### Environment
Python 3.8.13
Flask 2.0.3
Werkzeug 2.0.3
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by albertopinardi** [comment]
Hey @Jap8nted, could you please provide some further information like: the values that you used to deploy Superset using Helm or the command line with all the parameters. That would be useful to understand your environment and direct you towards the solutions without too many guesses.

**Comment by Jap8nted** [comment]
superset:
  serviceAccountName: superset

  bootstrapScript: |
    #!/bin/bash
    rm -rf /var/lib/apt/lists/* && \
    pip install --upgrade pip && \
    pip install \
      psycopg2-binary==2.9.1 \
      redis==3.5.3 \
      pyathena \
      elasticsearch-dbapi && \
    if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi


  supersetNode:
    connections:
      db_host: "XXXX"
      db_port: "5432"
      db_user: "sms"
      db_pass: "sms"
      db_name: "sms"

  postgresql:
    enabled: false

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: k8s.xarvio.com/instancegroup
                operator: In
                values:
                  - persistent

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
