### ISSUE TITLE
Resample with mean values doesn't help to fill empty values in chart (it still breaks)

### ISSUE THREAD

**Issue by katerina-glushko** [apache/superset#20650]
#### How to reproduce the bug

1. Create a new time series line/area chart using:
    - Metrics: sum(numeric) (`sum(attempt_cost)`),
    - Group by: str (`project_name`, without NULL values),
    - Contribution mode, Filters, Series Limit, Sort by: n/a
2. In Advanced analytics/Resample, select:
    - Calculation type: `Actual values`
    - Rule: `1 calendar day frequency`
    - Fill Method: `Mean values` (same with Median, Backward, Forward, Zero)
4. Click on Run

Dataset example: 
[sqllab_untitled_query_2_20220708T071434.csv](https://github.com/apache/superset/files/9069797/sqllab_untitled_query_2_20220708T071434.csv)

### Expected results

A chart is generated and has no breaks

### Actual results

Chart still breaks

#### Screenshots

<img width="1440" alt="Screenshot 2022-07-08 at 12 39 33" src="https://user-images.githubusercontent.com/15249191/177964464-7886c508-5238-4e0a-8b63-8b44f17dff73.png">

### Environment

- browser type and version: Google Chrome Version 102.0.5005.115 (Official Build) (x86_64)
- superset version: `1.5.1`
- python version: `3.8.5`
- any feature flags active: ENABLE_TEMPLATE_PROCESSING

### Checklist

- [ x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x ] I have reproduced the issue with at least the latest released version of superset.
- [ x ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by Venya331** [comment]
was it solved somehow?

**Comment by rusackas** [comment]
Hi there, and sorry this has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale. If it is still an issue in Superset 3.x (which it may well be!), we can re-open this - just let us know. Or, feel free to open a new issue with updated context. As always, PRs are welcome from anyone to fix the issue if it still exists.
