### ISSUE TITLE
Access is denied for some charts in an embedded dashboard

### ISSUE THREAD

**Issue by ficapal18** [apache/superset#20654]
We are building an AI cognitive tool for personalized medicine in cancer, and we would like to have an analytics dashboard in it.

For this reason, we embedded a Superset dashboard in the tool. So far, we are very satisfied with the outcomes and how the dashboard fits in the tool. We are close to make it work, but we require the help from an expert in Superset that can help us with the following problem:

Some charts in the dashboard return an "Access is Denied" error and are not shown. However, the other charts are correctly displayed. We already granted owner access to the "public" account to the dashboard, which is the one used to access an embedded dashboard. Surprisingly, when the dashboard is visualized by an admin account on the superset platform, without being embedded in our tool, all the charts are displayed and there's not such error.

Any ideas on what is happening? 

### Environment

- superset version: apache/superset:1.5.1
- any feature flags active:  
"EMBEDDED_SUPERSET":True,
"DASHBOARD_CROSS_FILTER":True,
"DASHBOARD_CROSS_FILTERS":True,
"DASHBOARD_NATIVE_FILTERS_SET":True,
"DASHBOARD_RBAC":True,
"DASHBOARD_FILTERS_EXPERIMENTAL" :True,
"ENABLE_TEMPLATE_PROCESSING": True

**Comment by catherinetrn** [comment]
I just had the same issue today. In my case, only bar charts where the x-axis is a category and not a date/time gave me an `Access Denied`. While inspecting the network calls in chrome I find out that it was the `explore_json` endpoint that returned 403 so I added to the role I use for embed the right `can explore json on Superset`. 

I hope it helps :)

**Comment by Jaykin001** [comment]
i am getting this error when i am trying to drill to detail on the map on embedded dashboard

**Comment by lucasfernando** [comment]
I just added "can log on Superset" permission to **Public** role and that solved the problem for me.

**Comment by Griffith88** [comment]
Hi i have similar problem with public (no login) access to dashboards
I created role Guest and added in superset_config.py
![image](https://github.com/apache/superset/assets/42404689/fb9f8e77-6a3e-44e6-b859-b352dfe2a1a9)


```py
PUBLIC_ROLE_LIKE = "Guest"

DEFAULT_FEATURE_FLAGS = {
    "DASHBOARD_RBAC": True,
    "ENABLE_TEMPLATE_PROCESSING": True,
    "DASHBOARD_NATIVE_FILTERS": True,
    "DASHBOARD_CROSS_FILTERS": True
}
```
when i publish and share via link any embedded dashboard or chart i get Access is Denied and its redirect me on Log In Page.

Any suggestions how to evade it ?

**Comment by Griffith88** [comment]
Embedded dashboards without URL SLUG will not be opened

**Comment by rusackas** [comment]
I'm hopeful that the solutions above panned out, and that's why this thread has gone quiet. We're no longer supporting Superset 2.x or prior, and since it's been a while since this thread saw any activity, I'll close this as stale. If it is still an issue in Superset 3.x or newer, we can re-open this, or feel free to open a new issue with updated context. Thanks!

**Comment by himanshudube97** [comment]
This solution worked for me too. I wanted to make a dashboard public, but one chart (Geographical coverage using the map) was giving the error Access Denied. Added `can explore json on Superset` in the permissions and it worked perfectly.
