### ISSUE TITLE
Show comment for ColumnElement/TableElement

### ISSUE THREAD

**Issue by eriendeng** [apache/superset#20667]
1. I notice that common db_engine_spec has function `get_table_comment`, so it's easy to get comment in api `superset/views/core.py::tables()` and it could be filterable in frontend.
2. similar to point 1, I think `ColumnElement` is able to do the same thing, and maybe it could be a tooltip to show column comment or sth else.
![image](https://user-images.githubusercontent.com/30573371/178269828-30ea9db3-12a2-41a1-8654-98689967272f.png)

**Comment by kevinmarsh** [comment]
So pulling an [example from the Django docs](https://docs.djangoproject.com/en/4.2/ref/models/fields/#enumeration-types):
```python
class Card(models.Model):

    class Suit(models.IntegerChoices):
        DIAMOND = 1
        SPADE = 2
        HEART = 3
        CLUB = 4

    suit = models.IntegerField(choices=Suit.choices)
```

The `suit` column is stored as an integer from `1`-`4` however you lose the context of what those integers represent when viewing the data in Superset.

---

[Starting in Django 4.2](https://docs.djangoproject.com/en/dev/releases/4.2/#comments-on-columns-and-tables), you can provide both table and column comments which would be really valuable to expose in this view as a comment or tooltip

```diff
suit = models.IntegerField(
	choices=Suit.choices,
+    db_comment="1 represents 'Diamond', 2 represents 'Spade', etc."
)
```

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, it's unclear if it's a bug _per se_, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
