### ISSUE TITLE
 clickhouse result no column header when using formatDateTime function

### ISSUE THREAD

**Issue by phpsxg** [apache/superset#20664]
#### How to reproduce the bug

SQL Lab
clickhouse result no column header when using formatDateTime function

![abc](https://user-images.githubusercontent.com/19278211/178183561-2f619869-6f98-491c-8bdb-769a3a4c3e61.png)
![bcd](https://user-images.githubusercontent.com/19278211/178183578-6accd0bb-bb01-4986-904a-0bee456afa97.png)

### Environment

- browser type and version:
- superset version: `apache/superset:latest-dev`
- python version: ` 3.8.13`
- clickhouse-sqlalchemy `0.1.0`
- clickhouse-driver `0.2.0`

**Comment by Slach** [comment]
could you try upgrade clickhouse-sqlalchemy to 0.1.8 and check again?

**Comment by phpsxg** [comment]
> could you try upgrade clickhouse-sqlalchemy to 0.1.8 and check again?

Sorry, I wrote wrong, I used clickhouse-sqlalchem==0.1.9, there is this problem

**Comment by dzanto** [comment]
I have same issue.

superset version: apache/superset:2.0.0 and apache/superset:1.5.1
clickhouse-sqlalchemy 0.1.6
clickhouse-driver 0.2.0

![image](https://user-images.githubusercontent.com/65130082/179487538-4c31903d-f400-4434-b3a6-a816da564f8b.png)

**Comment by dzanto** [comment]
clickhouse-driver==0.2.1 and clickhouse-sqlalchemy==0.1.9 fixed it

**Comment by Slach** [comment]
formatDateTime return string (documentation is unclear in this part)

SELECT toTypeName(formatDateTime(now(),'%Y-%m'))

so if you want return Date
you should use
```toDate(toStartOfMonth(BUSI_DATE))```

**Comment by Slach** [comment]
could you check these bug with
https://github.com/ClickHouse/clickhouse-connect

https://clickhouse.com/docs/en/connect-a-ui/superset-and-clickhouse/

**Comment by genzgd** [comment]
This seems to work just fine with ClickHouse Connect.

**Comment by Paulo456** [comment]
clickhouse-sqlalchemy==0.1.10 need to patch clickhouse_sqlalchemy/drivers/http/transport.py
set params 'default_format' to:
params['default_format'] = 'TabSeparatedWithNamesAndTypes'
in method _send of class RequestsTransport

```
--- /usr/local/lib/python3.8/site-packages/clickhouse_sqlalchemy/drivers/http/transport.py.orig
+++ /usr/local/lib/python3.8/site-packages/clickhouse_sqlalchemy/drivers/http/transport.py
@@ -164,6 +164,7 @@
         params = params or {}
         params['database'] = self.db_name
         params.update(self.ch_settings)
+        params['default_format'] = 'TabSeparatedWithNamesAndTypes'

         # TODO: retries, prepared requests
         r = self.http.post(
```

**Comment by rusackas** [comment]
It sounds like this is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue with updated context or a PR to address the problem. Thanks!
