### ISSUE TITLE
Update of Roles from Keycloak to Superset is not working

### ISSUE THREAD

**Issue by avinash-Github** [apache/superset#20694]
When we add roles to the existing user in keycloak, then the roles are not getting updated in superset.
Roles are not getting synchronized between keycloak and superset.

#### How to reproduce the bug

1. Go to Keycloak and add a superset role to an existing user
2. Login to superset and verify newly added roles
3. You will not find the roles updated/added

### Expected results

Roles should be synchronized between keycloak and superset for an existing user in keycloak

### Actual results

Roles are not getting synchronized between keycloak and superset.

### Environment

(please complete the following information):

- browser type and version: Chrome Browser 103.0.5060.114
- superset version: `1.4.0`
- python version: `3.8.12`
- node.js version: `14`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [Y] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [Y] I have reproduced the issue with at least the latest released version of superset.
- [Y] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by MM-Lehmann** [comment]
Can you try with 2.0 please? Also, make sure the feature flag `AUTH_ROLES_SYNC_AT_LOGIN` is set to true and the user logs out and in again.

**Comment by shiva-rakshith** [comment]
> 

After enabling AUTH_ROLES_SYNC_AT_LOGIN = True also still facing the same issue.
Is there any other configuartion to be made to sync keycloak user roles to superset.

**Comment by shiva-rakshith** [comment]
@avinash-Github Please share if you found any resolution.

**Comment by shiva-rakshith** [comment]
> AUTH_ROLES_SYNC_AT_LOGIN

@MM-Lehmann - I have tried this, but still facing the issue. Not able to see keycloak roles in superset, Can you please help?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long with no response to the last suggested approach, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
