### ISSUE TITLE
[SQL Lab] MultiSelector component render twice

### ISSUE THREAD

**Issue by EugeneTorap** [apache/superset#20702]
When you select 3 or more tables in drop-down and Click remove all chosen tables then MultiSelector component render values twice

#### How to reproduce the bug

Click SQL Lab and select SQL Editor in drop-down menu.
Select DB connection in Databases drop-down
Select schema in Schema drop-down
Select 3 or more tables in drop-down
Click remove all chosen tables in 'Select table…' field

### Expected results

MultiSelector component render once.

### Actual results

MultiSelector component render twice.

#### Screenshots

https://user-images.githubusercontent.com/29536522/178799559-f07e7f1a-397b-4edc-8126-7d0baba47dcf.mov

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

@michael-s-molina @kgabryje @codyml @zhaoyongjie @diegomedina248 @jinghua-qa

**Comment by michael-s-molina** [comment]
@diegomedina248 Can you take a look?

**Comment by diegomedina248** [comment]
@michael-s-molina yeah, will do.
