### ISSUE TITLE
Labelled column name is shown on Chart Edit page but not on Dashboard

### ISSUE THREAD

**Issue by NikosSpanos** [apache/superset#20707]
I downloaded the superset docker image the last month (between 15 and 30 of June 2022) on a production Linux VM.
However, I have been working on some dashboards and charts on a much older version, from late January 2022. So from a 6-month different version, I downloaded the dashboards from my local machine with the older version of the superset image and imported the dashboard to June's version of the superset.

Even though most of the charts were imported/migrated successfully, on some **Table** type charts I see the following. Apologize for the Greek characters. Columns **dt_quarter** and **ΕΚΜ_ΚΛΕΙΔΙ**. As seen below, those two columns in the dashboard view panel seem wrong without the correct **LABEL** applied. Like dt_quarter to the word **ΤΡΙΜΗΝΟ**, 
(1)
![Screenshot from 2022-07-14 15-51-04](https://user-images.githubusercontent.com/38804710/178987647-e944eda8-32d9-4405-9206-867ca5117191.png)

When I go to the EDIT CHART panel I can change the name of the column and apply a different so-called **LABEL** (by editing the data source table).
(2)
![Screenshot from 2022-07-14 16-00-06](https://user-images.githubusercontent.com/38804710/178988195-6742daf8-acd5-40c3-8655-d405c74999c4.png)

Even though I make the change and it's shown in the EDIT CHART TAB like below,
(3)
![Screenshot from 2022-07-14 15-54-32](https://user-images.githubusercontent.com/38804710/178987556-9ca93a50-32a0-4f64-9a22-385a011e969b.png)

When I refresh the dashboard image (1), the column of the saved table is still shown as **dt_quarter**  (the old name) without having applied the labeled tag **ΤΡΙΜΗΝΟ**.

Has something changed between the two versions of the superset (from February to June 2022) and the **Table** chart types? Or am I missing a configuration for the charts metadata that migrated from one version of superset to another?

Thanks in advance for any help.

**Comment by ljclour** [comment]
I have the same problem, have you solved it?

My Superset version is 2.0.1
![image](https://user-images.githubusercontent.com/45123712/215310040-e4fd341c-13b9-4b61-8ded-79c5ba3a910d.png)

**Comment by ziritrion** [comment]
I am having the same issue. Labeled columns on physical datasets are being displayed properly in the Edit Chart view but they are ignored in the Dashboard view.

**Comment by ziritrion** [comment]
LOL solved it!

In the Edit Chart view, when you edit the dataset, click on the 3 dots next to the data source and select Edit dataset. Then go to the Columns tab and click on the "Sync columns from source" button and save. The columns will now be displayed with their proper labels in the dashboard.

**Comment by rusackas** [comment]
Closing... thanks for the Sync Columns reminder, I'll close this issue I want to mention that on another issue, but I can't seem to find it now :)

**Comment by arnavgoyal17** [comment]
@ziritrion -- Could you elaborate on the steps? I followed what you've written and still facing the same issue. Edit Chart View shows the correct labels and the Dashboard reverts them to the physical table column names.

**Comment by arcuellar88** [comment]
@tomvolckaert @arnavgoyal17 we had the sale issue with the metrics. The Dashboard was reverting the metrics to the id. Our solution was to create a new copy of the Dashboard and charts. I think our problem is related with migration from (2.X to 4.X). The Dashboard was showing this error https://github.com/apache/superset/issues/25269
