### ISSUE TITLE
ModuleNotFoundError on fresh Superset 2.0.0 install

### ISSUE THREAD

**Issue by alanorth** [apache/superset#20717]
I installed Superset 2.0.0 via pip. I get the following error when running `superset` after installation:

```console
$ superset
...
ModuleNotFoundError: No module named 'werkzeug.wrappers.etag'
```

#### How to reproduce the bug

I installed Superset via pip in a clean Python 3.8 virtual environment on Linux:

```console
$ mkdir superset-2.0.0
$ cd superset-2.0.0
$ python3.8 -m venv venv
$ source ./venv/bin/activate
$ pip install --upgrade setuptools pip wheel
$ pip install apache-superset==2.0.0
$ pip install pillow mysqlclient gevent
$ vim superset_config.py
$ export PYTHONPATH=/home/superset/superset-2.0.0
$ export FLASK_APP=superset
$ superset
...
ModuleNotFoundError: No module named 'werkzeug.wrappers.etag'
```

### Expected results

Superset runs without error.

### Actual results

Superset crashes with Python `ModuleNotFoundError`.

### Environment

- superset version: Superset 2.0.0
- python version: Python 3.8.10

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional Information

I notice that `requirements/base.txt` lists `werkzeug==2.0.3` so I installed that manually and superset runs fine after.

**Comment by srinify** [comment]
Closing, as this is a duplicate:

https://github.com/apache/superset/issues/20723
