### ISSUE TITLE
Export full CSV downloads only first page with pagination enabled on table chart

### ISSUE THREAD

**Issue by mdeshmu** [apache/superset#20724]
When multiple pages are present in a table chart and user clicks on Export full CSV, only the data from first page is getting exported in CSV.

#### How to reproduce the bug

1. Go to 'Dashboard'
2. Click on 'Export full CSV' on a table chart
3. A zip should be downloaded
4. Analyze csv file to see only first page of the table downloaded

### Expected results

CSV file with entries from all pages should get downloaded.

### Actual results

CSV file with entries of first page getting downloaded

#### Screenshots

![image](https://user-images.githubusercontent.com/57723564/179233773-6355f1d8-23d9-4ee0-bb83-82307dfb8efc.png)

![server-pagination](https://user-images.githubusercontent.com/57723564/179235460-605b6708-b33c-4dc5-9ac9-ffd54155ee07.png)

### Environment

- browser type and version: Chrome Version 103.0.5060.114 (Official Build) (64-bit)
- superset version: 1.5.1
- python version: 3.8.12
- node.js version: 
- any feature flags active: ALLOW_FULL_CSV_EXPORT

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mdeshmu** [comment]
@LahmerIlyas can you please create a PR for this one just like we discussed in [17861](https://github.com/apache/superset/issues/17861)

**Comment by LahmerIlyas** [comment]
@mdeshmu I would be glad to help with a solution to this issue.

**Comment by mdeshmu** [comment]
@LahmerIlyas did you get time to look into this?

**Comment by mdeshmu** [comment]
@LahmerIlyas ping!  cc: @rusackas

**Comment by LahmerIlyas** [comment]
@mdeshmu sorry for taking too long on this. I created a PR for a fix for the issue. You can see it here: https://github.com/apache/superset/pull/23554

**Comment by LahmerIlyas** [comment]
@geido Can we get a review for my PR please.

**Comment by mdeshmu** [comment]
Thanks @LahmerIlyas

**Comment by rusackas** [comment]
I just came across this issue and PR again. Maybe I'm taking crazy pills, but I couldn't get reproduce this issue on current master. Is it still a problem on `master` or did some other PR resolve it in some other way?

**Comment by LahmerIlyas** [comment]
> I just came across this issue and PR again. Maybe I'm taking crazy pills, but I couldn't get reproduce this issue on the current master. Is it still a problem on `master` or did some other PR resolve it in some other way?

@rusackas Thanks for testing. I just managed to reproduce it on the master branch. Here is a recording:

[USA-Births-Names.webm](https://user-images.githubusercontent.com/31275446/232185651-dd10092d-51f1-4a39-b700-ff214b636b32.webm)

**Comment by hzdx943** [comment]
> @mdeshmu sorry for taking too long on this. I created a PR for a fix for the issue. You can see it here: #23554

@LahmerIlyas hi，I hava same issues, I modified the local code according to #23554,and enable ALLOW_FULL_CSV_EXPORT flag,I exported all the data when I used Export FULL CSV and Export CSV,The value of variable formDataCopy.result_type is full.
Is this a normal result? Thanks you~

**Comment by hzdx943** [comment]
> @mdeshmu sorry for taking too long on this. I created a PR for a fix for the issue. You can see it here: #23554

@LahmerIlyas hi,After applying this modification,I have encountered a new problem,The data refreshed after clicking on the page number will always be the data from the first page！

**Comment by geido** [comment]
Closing this one as stale. Related to #17861
