### ISSUE TITLE
It should be able to clone visualizations

### ISSUE THREAD

**Issue by comdiv** [apache/superset#20738]
It should be alowed to make clone (save as) of visualization! It's very
strange to create every single visualisation (with many common parameters and setup) from scratch

**Comment by jacobcroope** [comment]
There are existing options to duplicate an existing chart. You can export an existing chart and then import it and modify from that point or you can go into an existing chart and save as a new chart. Both let you start from a common base and modify as needed.

**Comment by rusackas** [comment]
Agreed with the above comment. I use the "Save as" feature for this, personally. If you want to add a "clone" button, I think that could be cool, but should be opened as an Ideas Discussion here on the repo, or as a PR. Closing since this isn't a bug :D

**Comment by ePaul** [comment]
I created feature idea https://github.com/apache/superset/discussions/29896 for making this a bit easier to find.
