### ISSUE TITLE
unable to render anymore a slice from URL

### ISSUE THREAD

**Issue by zufolo441** [apache/superset#20745]
Hi all, 
we have a software that get json data of a slice, modifies it and calls Superset to render it.
Example: 
/superset/explore/?form_data={%22adhoc_filters%22:[{%22clause%22:%22WHERE%22,%22comparator%22:null,%22expressionType%22:%22SQL%22,%22filterOptionName%22:%22filter_8xr2gav9b4y_6vxzunrcblp%22,%22isExtra%22:false,%22isNew%22:false,%22operator%22:null,%22sqlExpression%22:%22selterr%20=%20%271%27%22,%22subject%22:null}],%22datasource%22:%2277__table%22,%22entity%22:%22codterr%22,%22granularity_sqla%22:null,%22linear_color_scheme%22:%22red_yellow_blue%22,%22metric%22:{%22aggregate%22:null,%22column%22:null,%22expressionType%22:%22SQL%22,%22hasCustomLabel%22:true,%22isNew%22:false,%22label%22:%22Territorio%22,%22optionName%22:%22metric_7245v57ui48_oabopvdwa7k%22,%22sqlExpression%22:%22SUM(selterr)%22},%22number_format%22:%22SMART_NUMBER%22,%22select_country%22:%22toscana_comuni_2018%22,%22slice_id%22:%22381%22,%22time_range%22:%22No%20filter%22,%22viz_type%22:%22country_map%22,%22applied_time_extras%22:{},%22where%22:%22(selterr%20=%20%271%27)%22,%22having%22:%22%22,%22having_filters%22:[],%22filters%22:[]}&standalone=1

In particular, we realized this software because we need to change at runtime the representad country map.
In latest versions, it doens't work anymore, and Superset rewrite URL and reload data from original slice (381 in this example), in a form like this: 
/superset/explore/?form_data_key=RIY3H2um5wOe0vRlCNHuSJIc2ys-NLTQLScOuvN5JiSEuOpFtqeuMl1Kro1ZQKkD&slice_id=381&standalone=1 
Is there a way to newly obtain this?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
