### ISSUE TITLE
Apache superset pivot table download 

### ISSUE THREAD

**Issue by manojrustagi79** [apache/superset#20759]
Hi,

I have created a pivot table. When i am trying to download the pivot table, it is downloading the underlying data but not the pivot table. I am python 3.6 for Apache superset. Please let me know how can download the pivoted data from superset. Also i am not able to see pivot V2 table in my Apache superset version 

Thanks

**Comment by kamalkeshavani-aiinside** [comment]
Please mention the Superset version where you faced this issue.

**Comment by manojrustagi79** [comment]
Hi, 

Can please let me know how to check version of Apache superset? I installed the same using pip command on python 3.6 version.

Thanks

**Comment by kamalkeshavani-aiinside** [comment]
In UI, you can check from Top Right dropdown
<img width="211" alt="image" src="https://user-images.githubusercontent.com/74634977/179679879-645bb5dc-44c7-4b2c-b733-05c2060311e2.png">

**Comment by manojrustagi79** [comment]
It is showing as 0.38.1...

But when i have installed this using pip command i haven't specified any version. Ideally this should take latest version. But it has taken the old version

Is there any dependency it checks to install the latest version.

Thanks

**Comment by kamalkeshavani-aiinside** [comment]
Can you please share the installation command?

**Comment by manojrustagi79** [comment]
I have used below command to install superset 

pip install apache-superset

Python 3.6 and os is : cent os 7

**Comment by manojrustagi79** [comment]
Also let me know how can I upgrade this env. With latest compatible version.

**Comment by kamalkeshavani-aiinside** [comment]
Latest version of Superset is 2.0.0 which is supported only on Python 3.8 and above. After upgrading python, you can install superset.

For installation queries, please add a question in Discussions and close this bug.

**Comment by manojrustagi79** [comment]
Just to let you know that while installing superset on 3.9 version we were getting the error.

**Comment by manojrustagi79** [comment]
I have installed the Apache Superset 2.0.0 version on Python 3.8 version on Cent OS : 7.  But still there is no option is appearing to download pivot table data as pivoted. Please suggest the next action.
