### ISSUE TITLE
Endpoint `chart/{chart_id}/data/` doesn't return chart data (Fails with error: 'Dataset does not exist')

### ISSUE THREAD

**Issue by AdrianKoszalka** [apache/superset#20766]
We create via API a dashboard with charts. When we try to fetch the charts via API we are not able to get a successful response with data. Via GUI we are able to see all charts with data. If we editing the charts via GUI + save them, we able to get a successful response with data.

### How to reproduce the bug

1. Create a new dashboard with the charts via API.
2. Try to get data from chart (chart type: table) via API using endpoint `chart/{chart_id}/data/`

### Expected results

Response should contain data from chart.

### Actual results

Response: 
```
{'errors': [{'message': 'Dataset does not exist', 'error_type': 'GENERIC_COMMAND_ERROR', 'level': 'warning', 'extra': {'issue_codes': [{'code': 1010, 'message': 'Issue 1010 - Superset encountered an error while running a command.'}]}}]}

```
The only possible way to get these data via this API endpoint is to go first (before I call the endpoint) to the Superset GUI, open the chart in explore mode and Save(Overwrite), even without makes any changes. Then the response contains the chart data. 

### Screenshot:
Logs:
<img width="863" alt="Screen Shot 2022-07-19 at 10 33 23 AM" src="https://user-images.githubusercontent.com/70269475/179705428-df5eb7c6-03be-48b0-88e1-7ecb6d7a9f87.png">

### Environment
- browser type and version: Google Chrome Version 103.0.5060.114 (Official Build) (arm64)
- superset version: 1.3.2
- python version: 3.8
- node.js version: v12.22.7

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
