### ISSUE TITLE
[2.0.0] ROW_LEVEL_SECURITY feature not working - unable to filter via Charts nor SQL Lab

### ISSUE THREAD

**Issue by nusrath432** [apache/superset#20774]
Hi,
I am trying to test the ROW_LEVEL_SECURITY feature which is by default enabled in Superset:v2.0.0. However, it does not seem to work.

#### How to reproduce the bug
1. Create a role eg: `rw-examples-flights-only` with a single permission `datasource_access_on[examples].[flights](id:6)`

2. Add a row level security filter as following:
- Filter Type: Regular
- Tables: `public.flights`
- Roles: `rw-examples-flights-only` (from step 1)
- Group Key: 
- Clause: `AIRLINE = 'AS'`

3. Add a new user as follows:
- Firstname: Flights
- Lastname: Analyst
- Username: flightsanalyst
- Is Active: Yes
- Email: flightsanalyst@email.com
- Role: rw-examples-flights-only, sql_lab, Gamma
- Password: <random>

4. Now login as flightsanalyst user.

5. Click on SQL Lab --> Database (Postgresql:examples) --> Schema (Public) --> See Table Schema (flights)

7. Click Preview: `FLIGHTS`

### Expected results

- Would expect a default `WHERE AIRLINE = 'AS'` is applied to any query on `flights` table and only data for `AIRLINE = 'AS'` be displayed for the logged in user `flightsanalyst` and should not be allowed to query data of other flights.

### Actual results

- Data for all flights is displayed as if no `WHERE AIRLINE = 'AS'` is applied.

#### Database Queries
```
         created_on         |         changed_on         | id |      clause      | created_by_fk | changed_by_fk | filter_type | group_key 
----------------------------+----------------------------+----+------------------+---------------+---------------+-------------+-----------
 2022-07-19 18:24:58.772926 | 2022-07-19 18:24:58.772931 |  1 | AIRLINE='AS' |             1 |             1 | Regular     | 
```
Tried: `AIRLINE='AS'` / `AIRLINE = 'AS'` / `AIRLINE="AS"`  etc 

#### Screenshots

![image](https://user-images.githubusercontent.com/20503315/179885214-9fb7eab7-17a7-46bf-bf87-4d5d6bbc78fe.png)

![image](https://user-images.githubusercontent.com/20503315/179827651-dcce17d7-fdbc-42cd-b554-c64927c6a11f.png)

![image](https://user-images.githubusercontent.com/20503315/179827921-2b923264-2abe-4394-8519-8f62f9927783.png)

![image](https://user-images.githubusercontent.com/20503315/179828076-ea606eee-cc5b-4010-9d2a-a835c1560788.png)

![image](https://user-images.githubusercontent.com/20503315/179828210-44c6e174-4797-416d-8f8b-a873641fc6d9.png)

![image](https://user-images.githubusercontent.com/20503315/179828276-07d35d13-a5a8-414b-a1eb-fc7b282af6d5.png)

### Environment

(please complete the following information):

- browser type and version: Chromium: Version 103.0.5060.53 (Official Build) snap (64-bit)
- superset version: `superset version`: Superset 2.0.0
- python version: `python --version`: Python 3.8.12
- node.js version: `node -v`: 
- any feature flags active: No feature touch - default settings of superset:tag:2.0.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by nusrath432** [comment]
SOLUTION: We have to defined the clause as `"AIRLINE" = 'AS'` 

Note: This works in Charts now but SQL LAB will still let you see data of other airlines (rows) - is this by design?

**Comment by nusrath432** [comment]
If I set RLS_IN_SQLLAB = True within superset/config.py and try to run a query `SELECT * FROM FLIGHTS`, it tries to pick the WHERE clause `"AIRLINE" = 'AS'` but still fails due to prefixing it with public.flights.AIRLINE which is not a valid Column name.

![image](https://user-images.githubusercontent.com/20503315/180015937-80d830f9-21e9-4a32-8343-2dc4e5939e7f.png)

**Comment by anastasiu** [comment]
In file **sql_parse.py** change line 550:
```
-  Token(Name, token.get_name()),
+ Token(Name, "\""+token.get_name()+"\""),
```
and restart you Superset

**Comment by rusackas** [comment]
Hi there, and sorry this has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale. If it is still an issue in Superset 3.x, we can re-open this, or feel free to open a new issue with updated context.
