### ISSUE TITLE
Dashboard does not load when a filter is configured "Select first filter value by default" option  

### ISSUE THREAD

**Issue by nytai** [apache/superset#20797]
It seems when "Select first filter value by default" is configured for a filter and the dashboard has tabs the dashboard stays in a loading state and filters remain out of scope. Clicking the filters that are out of scope triggers the fetch for the first value and the dashboard can render. 

#### How to reproduce the bug

- Import the attached dashboard export (you might have to edit the database to use your examples db instead of the SQLLite one I used). 
- load the imported "video game sales" dashboard. 
- You should see the bug that looks like the attached screenshot
- click on the "filters out of scope" and the dashboard should load correctly. Refreshing the dashboard (as long as the url contains the `native_filters_key` query param, also results in the dashboard loading correctly.

### Expected results

The dashboard loads correctly when opened from the dashboard list/ home page or a link (that does not contain the `native_filters_key` query param. 

### Actual results

The dashboard stays in a loading state until "filters out of scope" is clicked or the dashboard is refreshed

#### Screenshots

<img width="2557" alt="Screen Shot 2022-07-20 at 1 52 56 PM" src="https://user-images.githubusercontent.com/10255196/180080011-b2702b25-a6da-4a8a-a6b5-91781a62a9cc.png">

### Environment

 version `1.5.1`

### Additional context

Dashboard export:
[dashboard_export_20220720T134744.zip](https://github.com/apache/superset/files/9154399/dashboard_export_20220720T134744.zip)

**Comment by nytai** [comment]
note: this might be the same issue, or related to https://github.com/apache/superset/issues/20748

**Comment by retairmars** [comment]
We have encountered the same issues on Select first filter value by default and work around by using "Filter has default value" instead.

**Comment by jacobcroope** [comment]
Has any progress been made on this?

**Comment by sfirke** [comment]
This also covers the 2nd part of this two-part bug report: https://github.com/apache/superset/issues/20930#issuecomment-1218112933

**Comment by Sonalit23** [comment]
Issue is reproducible with horizontal filter. Dashboard having multiple tabs and one of the filter is configured 'Select first filter value by default'.

https://github.com/apache/superset/assets/69430512/dbcf68c9-49fc-491e-ac2a-690edff0cb5b
