### ISSUE TITLE
Embedded dashboard reloads automatically every few seconds

### ISSUE THREAD

**Issue by dali-trabelsi** [apache/superset#20800]
### Environment
- browser type and version: Chrome
- superset version: 2.0.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x ] I have reproduced the issue with at least the latest released version of superset.
- [ x ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by j-goldsmith** [comment]
I'm running into a similar bug, followed by 403 errors when the embed iframe makes requests to the api.

v 2.0.0
Firefox

`<script>
        async function fetchGuestTokenFromBackend() {
            let response = await fetch('/superset/embed/FetchGuestToken/<uuid>');

            if (response.status === 200) {
                return await response.text();
            }
            return null;
        }

        supersetEmbeddedSdk.embedDashboard({
            id: "<uuid>", 
            supersetDomain: "https://viz.domain.com",
            mountPoint: document.getElementById("viz"), 
            fetchGuestToken: () => fetchGuestTokenFromBackend(),
            dashboardUiConfig: {}, 
        });

    </script>`

Guest token seems to be generated fine, except that after the "Buffer is not Defined" error, the subsequent request from the iframe to https://viz.domain.com/api/v1/me/roles/ sends back inaccurate isActive, roles, and permissions.

`
[HTTP/2 200 OK 111ms]
{"result":{
"firstName":"first",
"isActive":false,
"isAnonymous":false,
"lastName":"last",
"permissions":{},"roles":{},
"username":"user"}}
`

That user is active, has roles and was authorized for the dashboard being embedded. I tried adding a browserfied version of Buffer with no luck, but that may be my lack of frontend bundling experience.

**Comment by vivek-kandhvar** [comment]
Same problem for us too!

**Comment by dali-trabelsi** [comment]
@frafra @ryw @moonboots can you check this out please? it's really urgent

**Comment by frafra** [comment]
@dali-trabelsi Please do not tag random people. I just did minor contributors, I am not a maintainer.

**Comment by pabloascarza** [comment]
Any updates on this?

**Comment by dali-trabelsi** [comment]
@pabloascarza unfortunately I even tried to modify the lib code inside node_modules of the packages but was still getting the same problem, I couldn't identify why it's auto-reloading. Please let me know if you tried anything from your end.

**Comment by pabloascarza** [comment]
> 

To temporarily fix it i add buffer as dep and then
import { Buffer } from 'buffer';

window.Buffer = Buffer;

**Comment by rusackas** [comment]
Passing this around on Slack to some folks that have knowledge in this general area, but not sure if/when they'll have the bandwidth to go very deep on it.

**Comment by dali-trabelsi** [comment]
> @dali-trabelsi to temporarily fix it i add buffer as dep and then import { Buffer } from 'buffer';
> 
> window.Buffer = Buffer;

thank you @pabloascarza  it does fix the buffer error but not the main problem of the page reloading automatically way too often

**Comment by dali-trabelsi** [comment]
> 



> Passing this around on Slack to some folks that have knowledge in this general area, but not sure if/when they'll have the bandwidth to go very deep on it.

Thank you so much!

**Comment by dali-trabelsi** [comment]
@rusackas any updates please? we're still facing the same frustrating problem
