### ISSUE TITLE
Embedded dashboard, how to handle token timeout issue

### ISSUE THREAD

**Issue by sanjayssk** [apache/superset#20817]
I successfully embedded a dashboard using embedDashboard with a guest token. But when I wait for the time out (5 mins) when the guest token is supposed to expire, doing any filter Apply interactions on the dashboard starts giving errors on permissions, same as if guest token is invalid. Shouldn't there be an event from embedDashboard on such errors so that I can then see if a refresh token solves the problem and prompt the user to refresh?

#### How to reproduce the bug
Embed any dashboard using embedDashboard. Wait for 5 minutes and then do some interaction. 

### Expected results
The dashboard interactions should keep working once embedded

### Actual results
Error like the following appears on any interaction on a popup.
```
This endpoint requires the datasource app1_demo.tbl_1_locationwise, database or
            `all_datasource_access` permission
```

### Environment
- Chrome Version 103.0.5060.134 (Official Build) (64-bit)
- superset version: don't know as it says latest and the UI menu shows 0.0.dev. Docker image was used in April 2022.
- python version: 3.9.5
- node.js version: 12.16.1
- any feature flags active: "EMBEDDED_SUPERSET": True,

**Comment by sanjayssk** [comment]
BTW, a related question, I had installed this docker image in April and want to know what version it is. But UI menu shows 0.0.dev and nothing can be found by "docker image" command. How to find version? Shouldn't there by a release file or changelog file for the superset as a whole keeping a version to find in such cases?

**Comment by sanjayssk** [comment]
My bad. I was using a constant for guest token in the hope that it will be used from a useState. It should be a function that returns a promise that gets resolved to token. Changing to function fixed it.

**Comment by alfredxinglkey** [comment]
> My bad. I was using a constant for guest token in the hope that it will be used from a useState. It should be a function that returns a promise that gets resolved to token. Changing to function fixed it.

Hi, I am confused about how to embed dashboard with guest token, would you be willing to share sample code to help me implement embedding using guest token?

**Comment by apole** [comment]
@sanjayssk , I am facing same issue, can you please elaborate on your fix? How is refreshed token being automatically picked up by embedDashboard and is it reloading the dashboard again or filters and state is presevred?
