### ISSUE TITLE
GET /ws HTTP/1.1 werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.

### ISSUE THREAD

**Issue by JunTech** [apache/superset#20815]
when i click welcome pages,it will request the /ws api,then the backend will cause notFound error

#### How to reproduce the bug

1. start the server,and click welcome pages,it will request /ws api
2. the backend will cause notFound error
3. See error
![image](https://user-images.githubusercontent.com/54126696/180344008-fb520541-d7a0-41d4-9304-629ceb93185e.png)

![image](https://user-images.githubusercontent.com/54126696/180343611-5b1f5af9-1bfe-4cbe-ba38-6287a9f7b128.png)

### Expected results

what you expected to happen.

### Actual results

raise notFound error

#### Screenshots

![image](https://user-images.githubusercontent.com/54126696/180343665-402f3efb-e02d-4f47-a371-d0cc2673c256.png)

### Environment

(please complete the following information):

- browser type and version: chrome 96
- superset version: `2.0
- python version: `anaconda 3.8`
- node.js version: `16`
- any feature flags active: 

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by n15902179169** [comment]
我有同样的问题

**Comment by DingZhengCN** [comment]
I have the same question

**Comment by hushaoqing** [comment]
Adding `host` to[ config.json](https://github.com/apache/superset/blob/15c3c342680e041019eab9a327034c77f6456966/superset-websocket/config.example.json#L2) worked in my case.
![image](https://user-images.githubusercontent.com/10289162/192680610-253d44b2-ba1a-43e1-9a80-f754e8e17e2c.png)

**Comment by wangkun723** [comment]
我也存在这个问题，有任何进展吗

**Comment by rusackas** [comment]
Hi there, and sorry this has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and since it's been a while since this thread saw any activity (around 6 months), I'll close this as stale. If it is still an issue in Superset 3.x or newer, we can re-open this, or feel free to open a new issue with updated context. Thanks!

**Comment by alephpt** [comment]
I get the same error in current versions as well
