### ISSUE TITLE
Issues trying to get non-temporal plots with `GENERIC_CHART_AXES` feature flag

### ISSUE THREAD

**Issue by ekorman** [apache/superset#20814]
Charts are still trying to use time column even with `GENERIC_CHART_AXES` feature flag

#### How to reproduce the bug

This is actually two, possibly related bugs.

I have a deployment with `FEATURE_FLAGS = {"GENERIC_CHART_AXES": True}`. I have a dataset that has some temporal columns (one of which is called `"Timestamp"`) but I want to create a box plot of a numeric column against a boolean column. The boxplot forces me to choose a time column. 

First bug: I edited the dataset columns and unchecked "is temporal" for all time columns. Then I don't need to set a time column and I get the following:

![image](https://user-images.githubusercontent.com/9574559/180298955-f2fc7e58-701c-455d-971a-05298a67fbb5.png)

However, if I click "view query" it looks like it is still grouping by the `Timestamp` column: 

![image](https://user-images.githubusercontent.com/9574559/180299228-7a8559a7-35b8-4cd3-b20b-0afafa892bcb.png)

Second bug: if I now edit the dataset and delete all the temporal columns, then I get the following error:

![image](https://user-images.githubusercontent.com/9574559/180299404-e506baeb-2d62-462f-aa6e-d0eb3fbe0af8.png)

This also happens in a line plot:
![image](https://user-images.githubusercontent.com/9574559/180299451-e498fc17-2951-4ace-b04b-00b93a515076.png)

### Expected results

I'd expect to be able to produce a box plot and line plot like this without needing or using any temporal columns.

### Environment

I have superset installed via helm (chart version is 0.6.5).

My overriding values yaml is:

```yaml
configOverrides:
  mapbox: |
    MAPBOX_API_KEY = ""
  generic_charts_axes: |
    FEATURE_FLAGS = {"GENERIC_CHART_AXES": True}
```

**Comment by srinify** [comment]
One thing to note @ekorman is that I believe this flag only enables this feature for the time series charts written in Apache ECharts. Boxplot isn't one of them :/

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
