### ISSUE TITLE
Not able to take URL_PARAM in explore chart

### ISSUE THREAD

**Issue by syedgufran95** [apache/superset#20825]
#### How to reproduce the bug

1. Go to 'http://localhost:8088/superset/sqllab/?name=can_read'
2. Write query on default dataset on sqllab 'select * from ab_permission where name = '{{ url_param('name') }}''
3. Click on explore after running the query (it should return one row)
4. click on explore.
5. now write &name=can_read in the URL.

### Expected results
URL parameters should persist in the URL and should be read by charts

### Actual results
URL parameters disappear

#### Screenshots
URL params working in SQL lab
![Screenshot from 2022-07-22 16-41-26](https://user-images.githubusercontent.com/43085010/180427546-97a70f40-6571-4b6e-a283-ccc7ef02957a.png)

URL param disappears from url
![ezgif com-gif-maker(4)](https://user-images.githubusercontent.com/43085010/180427449-375f9d8a-55d7-4589-a193-769594379162.gif)

### Environment

(please complete the following information):

- browser type and version: persists on all browser (chrome ,Mozilla,brave)
- superset version: `[2.0.0](https://github.com/apache/superset/releases/tag/2.0.0)`

### Additional context
I am using jinja templating and I am using URL parms to get the data. I have change feature flag as well still it is not working.

**Comment by FaidJalal** [comment]
Hey @syedgufran95 I have encountered same issue and was looking someone to report it. I tried changing the config as well but nothing went through.

**Comment by burhanaslam** [comment]
I have similar issue, haven't found solution yet

**Comment by Tabinda788** [comment]
I am facing the same issue on the newest version after pull

**Comment by YiouZuo** [comment]
I run into the same issue.

**Comment by syedgufran95** [comment]
@YiouZuo 
The problem is with the docker image. The latest docker image is breaking. I resolved the issue by making changes in the docker-compose. and moved back to the previous version. In docker-compose make changes

> From 

`x-superset-image: &superset-image apache/superset:${TAG:-latest-dev} `
To
`x-superset-image: &superset-image apache/superset:44c5e2879b912b33c902b955eebdaa52ea6e5354 `
this id I got from an older version of the docker image from the official docker.

**Comment by YiouZuo** [comment]
@syedgufran95 Thank you for your suggestion! One caveat of rolling back to an older image is that some of the newer functions are lost -- one that matters in my case is the ability to save datasets from sqllab. I'll just need to wait until Superset fix their bug :(.
