### ISSUE TITLE
Label colors are not working properly for Mixed Time Series Chart from 1.5

### ISSUE THREAD

**Issue by radhakvnr** [apache/superset#20827]
After upgrading to 1.5 from 1.3.2 we have noted that, the Label colors which we define at JSON Metadata of Dashboard is not having any affect. Only the first metric is getting the label color where as other metrics are falling back to the color schemes

#### How to reproduce the bug

1. Create a Mixed time Series chart
2. Add that to a Dashboard and choose a color scheme
3. Apply the Label colors for two metrics
4. you can see only the first metric gets affected where as second metric is having default color.

### Expected results
It should display the colors based on label colors what we defined at Dashboard JSON

### Actual results

Only the first metric gets the color from Json Label where as second metric is having default color.

### Environment

(please complete the following information):

- Chrome 103:
- superset version: `1.5`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by andnig** [comment]
Can confirm this behavior with superset 2.0 (current master)

**Comment by Phonom** [comment]
For mixed time series charts, you have to add "(1)" to the labels of the second metrics to make it work:
`
"label_colors": {
"MyLabel (1)": "red"
}
`

**Comment by ianr21** [comment]
It works! Thank you for posting this!

Any idea how to fix this if we have two metrics on the secondary Y-Axis?

I tried these combinations, but can't change the color of the last metric.

`
"label_colors": { "MetricOne": "gray", "MetricTwo (1)": "red", "MetricThree (1)": "blue" }
"label_colors": { "MetricOne": "gray", "MetricTwo (1)": "red", "MetricThree (2)": "blue" }
`

**Comment by BrianWakhutu** [comment]
> For mixed time series charts, you have to add "(1)" to the labels of the second metric to make it work: `"label_colors": { "MyLabel (1)": "red" }`

Thanks for this ... It worked like mirth!
