### ISSUE TITLE
Can't add new database

### ISSUE THREAD

**Issue by elestranobaron** [apache/superset#20839]
Hi, i'm using last version of superset on docker

when i'm at step three of adding a mysql database (didn't try any other but i expect the same result) i click on "finish" and it does nothing

Except i get this error message :
![Capture2](https://user-images.githubusercontent.com/12266455/180671711-9faf7d0a-8d16-430e-84a0-bceb16c1c8cd.png)

**Comment by elestranobaron** [comment]
Expect result: the modal close and a new database appear on the list

Happened result: nothing close and no database appear on the list

**Comment by elestranobaron** [comment]
![Capture4](https://user-images.githubusercontent.com/12266455/180672106-b110dfc3-e5d4-4e9b-aca3-1dfc89ae4169.png)

Get this when i click on empty label texts, dont know if it's related or not

**Comment by syedgufran95** [comment]
@elestranobaron could you please specify whether your database is inside seperate docker or not? if you're using docker installation for you db then in hostname you need to give the docker IP( which you can get by using ifconfig) and if you have standard installation then you need to specify local IP... since superset docker might be searching in its own localhost.

**Comment by elestranobaron** [comment]
ip given is in 172.0 so yes and has you can see the connection is successful

even i checked with wrong password or wrong db name and it reacts accordingly

**Comment by elestranobaron** [comment]
It's like the connection has been done but no database has been saved

**Comment by elestranobaron** [comment]
![Capturecreated](https://user-images.githubusercontent.com/12266455/180770535-d2ec2ae5-f5aa-425e-8144-54560f0ee8f8.PNG)
![Capturecrrted2](https://user-images.githubusercontent.com/12266455/180770551-71bf1d6b-33f0-4b60-8552-cabf3a9e7ba5.png)
![Capturecrted2](https://user-images.githubusercontent.com/12266455/180770553-29cbe238-1b1f-4caf-91ba-4c4aba781be7.png)
![Capturecratedd2](https://user-images.githubusercontent.com/12266455/180770555-d1c0d7fe-1d8f-44dd-adf5-8b7169bdbf83.png)
![Capturecrrrrted2](https://user-images.githubusercontent.com/12266455/180770556-3c0e3e22-a23a-462f-be08-eec7cb76e7a0.png)


So Obviously it seems like the db is successfully created under the id 13 (which is my number of attempts right now)
But i can't access this very endpoint /13 cause apparently it dont exist wasnt created in fact ?

**Comment by elestranobaron** [comment]
Ok my bad it was tricky, version was 4 month old the last one is good not shite as the other
