### ISSUE TITLE
Getting error while installing  'superset db upgrade ' Please help on this issue.

### ISSUE THREAD

**Issue by sreehari83** [apache/superset#20844]
Getting error while installing  'superset db upgrade ' Please help on this issue.

~# **superset db upgrade**

Traceback (most recent call last):
  File "/homes/sreehari/venv/bin/superset", line 33, in <module>
    sys.exit(load_entry_point('apache-superset==0.38.1', 'console_scripts', 'superset')())
  File "/homes/sreehari/venv/bin/superset", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/homes/sreehari/venv/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/homes/sreehari/venv/lib/python3.6/site-packages/superset/__init__.py", line 21, in <module>
    from superset.app import create_app
  File "/homes/sreehari/venv/lib/python3.6/site-packages/superset/app.py", line 24, in <module>
    from flask_appbuilder import expose, IndexView
  File "/homes/sreehari/venv/lib/python3.6/site-packages/flask_appbuilder/__init__.py", line 5, in <module>
    from .api import ModelRestApi  # noqa: F401
  File "/homes/sreehari/venv/lib/python3.6/site-packages/flask_appbuilder/api/__init__.py", line 21, in <module>
    from .convert import Model2SchemaConverter
  File "/homes/sreehari/venv/lib/python3.6/site-packages/flask_appbuilder/api/convert.py", line 4, in <module>
    from flask_appbuilder.models.sqla.interface import SQLAInterface
  File "/homes/sreehari/venv/lib/python3.6/site-packages/flask_appbuilder/models/sqla/interface.py", line 40, in <module>
    from sqlalchemy_utils.types.uuid import UUIDType
  File "/homes/sreehari/venv/lib/python3.6/site-packages/sqlalchemy_utils/__init__.py", line 1, in <module>
    from .aggregates import aggregated  # noqa
  File "/homes/sreehari/venv/lib/python3.6/site-packages/sqlalchemy_utils/aggregates.py", line 372, in <module>
    from .functions.orm import get_column_key
  File "/homes/sreehari/venv/lib/python3.6/site-packages/sqlalchemy_utils/functions/__init__.py", line 1, in <module>
    from .database import (  # noqa
  File "/homes/sreehari/venv/lib/python3.6/site-packages/sqlalchemy_utils/functions/database.py", line 11, in <module>
    from .orm import quote
  File "/homes/sreehari/venv/lib/python3.6/site-packages/sqlalchemy_utils/functions/orm.py", line 14, in <module>
    from sqlalchemy.orm.query import _ColumnEntity
ImportError: cannot import name '_ColumnEntity'

**pip install apache-superset**

WARNING: The directory '/homes/sreehari/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Requirement already satisfied: apache-superset in ./venv/lib/python3.6/site-packages (0.38.1)
Requirement already satisfied: backoff>=1.8.0 in ./venv/lib/python3.6/site-packages (from apache-superset) (1.11.1)
Requirement already satisfied: bleach<4.0.0,>=3.0.2 in ./venv/lib/python3.6/site-packages (from apache-superset) (3.3.1)
Requirement already satisfied: cachelib<0.2,>=0.1.1 in ./venv/lib/python3.6/site-packages (from apache-superset) (0.1.1)
Requirement already satisfied: celery!=4.4.1,<5.0.0,>=4.3.0 in ./venv/lib/python3.6/site-packages (from apache-superset) (4.4.7)
Requirement already satisfied: click<8 in ./venv/lib/python3.6/site-packages (from apache-superset) (7.1.2)
Requirement already satisfied: colorama in ./venv/lib/python3.6/site-packages (from apache-superset) (0.4.5)
Requirement already satisfied: contextlib2 in ./venv/lib/python3.6/site-packages (from apache-superset) (21.6.0)
Requirement already satisfied: croniter>=0.3.28 in ./venv/lib/python3.6/site-packages (from apache-superset) (1.3.5)
Requirement already satisfied: cryptography>=2.4.2 in ./venv/lib/python3.6/site-packages (from apache-superset) (37.0.4)
Requirement already satisfied: flask<2.0.0,>=1.1.0 in ./venv/lib/python3.6/site-packages (from apache-superset) (1.1.4)
Requirement already satisfied: flask-appbuilder<4.0.0,>=3.0.1 in ./venv/lib/python3.6/site-packages (from apache-superset) (3.4.5)
Requirement already satisfied: flask-caching in ./venv/lib/python3.6/site-packages (from apache-superset) (1.10.1)
Requirement already satisfied: flask-compress in ./venv/lib/python3.6/site-packages (from apache-superset) (1.12)
Requirement already satisfied: flask-talisman in ./venv/lib/python3.6/site-packages (from apache-superset) (1.0.0)
Requirement already satisfied: flask-migrate in ./venv/lib/python3.6/site-packages (from apache-superset) (3.1.0)
Requirement already satisfied: flask-wtf in ./venv/lib/python3.6/site-packages (from apache-superset) (0.14.3)
Requirement already satisfied: geopy in ./venv/lib/python3.6/site-packages (from apache-superset) (2.2.0)
Requirement already satisfied: gunicorn<20.1,>=20.0.2 in ./venv/lib/python3.6/site-packages (from apache-superset) (20.0.4)
Requirement already satisfied: humanize in ./venv/lib/python3.6/site-packages (from apache-superset) (3.14.0)
Requirement already satisfied: isodate in ./venv/lib/python3.6/site-packages (from apache-superset) (0.6.1)
Requirement already satisfied: markdown>=3.0 in ./venv/lib/python3.6/site-packages (from apache-superset) (3.3.7)
Requirement already satisfied: msgpack<1.1,>=1.0.0 in ./venv/lib/python3.6/site-packages (from apache-superset) (1.0.4)
Requirement already satisfied: pandas<1.2,>=1.1.2 in ./venv/lib/python3.6/site-packages (from apache-superset) (1.1.5)
Requirement already satisfied: parsedatetime in ./venv/lib/python3.6/site-packages (from apache-superset) (2.6)
Requirement already satisfied: pathlib2 in ./venv/lib/python3.6/site-packages (from apache-superset) (2.3.7.post1)
Requirement already satisfied: polyline in ./venv/lib/python3.6/site-packages (from apache-superset) (1.4.0)
Requirement already satisfied: python-dateutil in ./venv/lib/python3.6/site-packages (from apache-superset) (2.8.2)
Requirement already satisfied: python-dotenv in ./venv/lib/python3.6/site-packages (from apache-superset) (0.20.0)
Requirement already satisfied: python-geohash in ./venv/lib/python3.6/site-packages (from apache-superset) (0.8.5)
Requirement already satisfied: pyarrow<1.1,>=1.0.1 in ./venv/lib/python3.6/site-packages (from apache-superset) (1.0.1)
Requirement already satisfied: pyyaml>=5.1 in ./venv/lib/python3.6/site-packages (from apache-superset) (6.0)
Requirement already satisfied: retry>=0.9.2 in ./venv/lib/python3.6/site-packages (from apache-superset) (0.9.2)
Requirement already satisfied: selenium>=3.141.0 in ./venv/lib/python3.6/site-packages (from apache-superset) (3.141.0)
Requirement already satisfied: simplejson>=3.15.0 in ./venv/lib/python3.6/site-packages (from apache-superset) (3.17.6)
Requirement already satisfied: slackclient==2.5.0 in ./venv/lib/python3.6/site-packages (from apache-superset) (2.5.0)
Requirement already satisfied: sqlalchemy<2.0,>=1.3.16 in ./venv/lib/python3.6/site-packages (from apache-superset) (1.4.39)
Requirement already satisfied: sqlalchemy-utils<0.37,>=0.36.6 in ./venv/lib/python3.6/site-packages (from apache-superset) (0.36.8)
Requirement already satisfied: sqlparse==0.3.0 in ./venv/lib/python3.6/site-packages (from apache-superset) (0.3.0)
Requirement already satisfied: wtforms-json in ./venv/lib/python3.6/site-packages (from apache-superset) (0.3.5)
Requirement already satisfied: aiohttp>3.5.2 in ./venv/lib/python3.6/site-packages (from slackclient==2.5.0->apache-superset) (3.8.1)
Requirement already satisfied: six>=1.9.0 in ./venv/lib/python3.6/site-packages (from bleach<4.0.0,>=3.0.2->apache-superset) (1.16.0)
Requirement already satisfied: webencodings in ./venv/lib/python3.6/site-packages (from bleach<4.0.0,>=3.0.2->apache-superset) (0.5.1)
Requirement already satisfied: packaging in ./venv/lib/python3.6/site-packages (from bleach<4.0.0,>=3.0.2->apache-superset) (21.3)
Requirement already satisfied: vine==1.3.0 in ./venv/lib/python3.6/site-packages (from celery!=4.4.1,<5.0.0,>=4.3.0->apache-superset) (1.3.0)
Requirement already satisfied: billiard<4.0,>=3.6.3.0 in ./venv/lib/python3.6/site-packages (from celery!=4.4.1,<5.0.0,>=4.3.0->apache-superset) (3.6.4.0)
Requirement already satisfied: pytz>dev in ./venv/lib/python3.6/site-packages (from celery!=4.4.1,<5.0.0,>=4.3.0->apache-superset) (2022.1)
Requirement already satisfied: kombu<4.7,>=4.6.10 in ./venv/lib/python3.6/site-packages (from celery!=4.4.1,<5.0.0,>=4.3.0->apache-superset) (4.6.11)
Requirement already satisfied: cffi>=1.12 in ./venv/lib/python3.6/site-packages (from cryptography>=2.4.2->apache-superset) (1.15.1)
Requirement already satisfied: Werkzeug<2.0,>=0.15 in ./venv/lib/python3.6/site-packages (from flask<2.0.0,>=1.1.0->apache-superset) (1.0.1)
Requirement already satisfied: Jinja2<3.0,>=2.10.1 in ./venv/lib/python3.6/site-packages (from flask<2.0.0,>=1.1.0->apache-superset) (2.11.3)
Requirement already satisfied: itsdangerous<2.0,>=0.24 in ./venv/lib/python3.6/site-packages (from flask<2.0.0,>=1.1.0->apache-superset) (1.1.0)
Requirement already satisfied: marshmallow-enum<2,>=1.5.1 in ./venv/lib/python3.6/site-packages (from flask-appbuilder<4.0.0,>=3.0.1->apache-superset) (1.5.1)
Requirement already satisfied: marshmallow-sqlalchemy<0.27.0,>=0.22.0 in ./venv/lib/python3.6/site-packages (from flask-appbuilder<4.0.0,>=3.0.1->apache-superset) (0.26.1)
Requirement already satisfied: Flask-Login<0.5,>=0.3 in ./venv/lib/python3.6/site-packages (from flask-appbuilder<4.0.0,>=3.0.1->apache-superset) (0.4.1)
Requirement already satisfied: Flask-OpenID<2,>=1.2.5 in ./venv/lib/python3.6/site-packages (from flask-appbuilder<4.0.0,>=3.0.1->apache-superset) (1.3.0)
Requirement already satisfied: marshmallow<4,>=3 in ./venv/lib/python3.6/site-packages (from flask-appbuilder<4.0.0,>=3.0.1->apache-superset) (3.14.1)
Requirement already satisfied: Flask-JWT-Extended<4,>=3.18 in ./venv/lib/python3.6/site-packages (from flask-appbuilder<4.0.0,>=3.0.1->apache-superset) (3.25.1)
Requirement already satisfied: Flask-Babel<3,>=1 in ./venv/lib/python3.6/site-packages (from flask-appbuilder<4.0.0,>=3.0.1->apache-superset) (2.0.0)
Requirement already satisfied: apispec[yaml]<4,>=3.3 in ./venv/lib/python3.6/site-packages (from flask-appbuilder<4.0.0,>=3.0.1->apache-superset) (3.3.2)
Requirement already satisfied: prison<1.0.0,>=0.2.1 in ./venv/lib/python3.6/site-packages (from flask-appbuilder<4.0.0,>=3.0.1->apache-superset) (0.2.1)
Requirement already satisfied: Flask-SQLAlchemy<3,>=2.4 in ./venv/lib/python3.6/site-packages (from flask-appbuilder<4.0.0,>=3.0.1->apache-superset) (2.5.1)
Requirement already satisfied: jsonschema<5,>=3 in ./venv/lib/python3.6/site-packages (from flask-appbuilder<4.0.0,>=3.0.1->apache-superset) (3.2.0)
Requirement already satisfied: PyJWT<2.0.0,>=1.7.1 in ./venv/lib/python3.6/site-packages (from flask-appbuilder<4.0.0,>=3.0.1->apache-superset) (1.7.1)
Requirement already satisfied: email-validator<2,>=1.0.5 in ./venv/lib/python3.6/site-packages (from flask-appbuilder<4.0.0,>=3.0.1->apache-superset) (1.2.1)
Requirement already satisfied: WTForms<3.0.0 in ./venv/lib/python3.6/site-packages (from flask-appbuilder<4.0.0,>=3.0.1->apache-superset) (2.3.3)
Requirement already satisfied: setuptools>=3.0 in ./venv/lib/python3.6/site-packages (from gunicorn<20.1,>=20.0.2->apache-superset) (59.6.0)
Requirement already satisfied: importlib-metadata>=4.4 in ./venv/lib/python3.6/site-packages (from markdown>=3.0->apache-superset) (4.8.3)
Requirement already satisfied: numpy>=1.15.4 in ./venv/lib/python3.6/site-packages (from pandas<1.2,>=1.1.2->apache-superset) (1.19.5)
Requirement already satisfied: py<2.0.0,>=1.4.26 in ./venv/lib/python3.6/site-packages (from retry>=0.9.2->apache-superset) (1.11.0)
Requirement already satisfied: decorator>=3.4.2 in ./venv/lib/python3.6/site-packages (from retry>=0.9.2->apache-superset) (5.1.1)
Requirement already satisfied: urllib3 in ./venv/lib/python3.6/site-packages (from selenium>=3.141.0->apache-superset) (1.26.10)
Requirement already satisfied: greenlet!=0.4.17 in ./venv/lib/python3.6/site-packages (from sqlalchemy<2.0,>=1.3.16->apache-superset) (1.1.2)
Requirement already satisfied: brotli in ./venv/lib/python3.6/site-packages (from flask-compress->apache-superset) (1.0.9)
Requirement already satisfied: alembic>=0.7 in ./venv/lib/python3.6/site-packages (from flask-migrate->apache-superset) (1.7.7)
Requirement already satisfied: geographiclib<2,>=1.49 in ./venv/lib/python3.6/site-packages (from geopy->apache-superset) (1.52)
Requirement already satisfied: asynctest==0.13.0 in ./venv/lib/python3.6/site-packages (from aiohttp>3.5.2->slackclient==2.5.0->apache-superset) (0.13.0)
Requirement already satisfied: idna-ssl>=1.0 in ./venv/lib/python3.6/site-packages (from aiohttp>3.5.2->slackclient==2.5.0->apache-superset) (1.1.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in ./venv/lib/python3.6/site-packages (from aiohttp>3.5.2->slackclient==2.5.0->apache-superset) (4.0.2)
Requirement already satisfied: attrs>=17.3.0 in ./venv/lib/python3.6/site-packages (from aiohttp>3.5.2->slackclient==2.5.0->apache-superset) (21.4.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in ./venv/lib/python3.6/site-packages (from aiohttp>3.5.2->slackclient==2.5.0->apache-superset) (2.1.0)
Requirement already satisfied: aiosignal>=1.1.2 in ./venv/lib/python3.6/site-packages (from aiohttp>3.5.2->slackclient==2.5.0->apache-superset) (1.2.0)
Requirement already satisfied: yarl<2.0,>=1.0 in ./venv/lib/python3.6/site-packages (from aiohttp>3.5.2->slackclient==2.5.0->apache-superset) (1.7.2)
Requirement already satisfied: typing-extensions>=3.7.4 in ./venv/lib/python3.6/site-packages (from aiohttp>3.5.2->slackclient==2.5.0->apache-superset) (4.1.1)
Requirement already satisfied: frozenlist>=1.1.1 in ./venv/lib/python3.6/site-packages (from aiohttp>3.5.2->slackclient==2.5.0->apache-superset) (1.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./venv/lib/python3.6/site-packages (from aiohttp>3.5.2->slackclient==2.5.0->apache-superset) (5.2.0)
Requirement already satisfied: importlib-resources in ./venv/lib/python3.6/site-packages (from alembic>=0.7->flask-migrate->apache-superset) (5.4.0)
Requirement already satisfied: Mako in ./venv/lib/python3.6/site-packages (from alembic>=0.7->flask-migrate->apache-superset) (1.1.6)
Requirement already satisfied: pycparser in ./venv/lib/python3.6/site-packages (from cffi>=1.12->cryptography>=2.4.2->apache-superset) (2.21)
Requirement already satisfied: idna>=2.0.0 in ./venv/lib/python3.6/site-packages (from email-validator<2,>=1.0.5->flask-appbuilder<4.0.0,>=3.0.1->apache-superset) (3.3)
Requirement already satisfied: dnspython>=1.15.0 in ./venv/lib/python3.6/site-packages (from email-validator<2,>=1.0.5->flask-appbuilder<4.0.0,>=3.0.1->apache-superset) (2.2.1)
Requirement already satisfied: Babel>=2.3 in ./venv/lib/python3.6/site-packages (from Flask-Babel<3,>=1->flask-appbuilder<4.0.0,>=3.0.1->apache-superset) (2.10.3)
Requirement already satisfied: python3-openid>=2.0 in ./venv/lib/python3.6/site-packages (from Flask-OpenID<2,>=1.2.5->flask-appbuilder<4.0.0,>=3.0.1->apache-superset) (3.2.0)
Requirement already satisfied: zipp>=0.5 in ./venv/lib/python3.6/site-packages (from importlib-metadata>=4.4->markdown>=3.0->apache-superset) (3.6.0)
Requirement already satisfied: MarkupSafe>=0.23 in ./venv/lib/python3.6/site-packages (from Jinja2<3.0,>=2.10.1->flask<2.0.0,>=1.1.0->apache-superset) (2.0.1)
Requirement already satisfied: pyrsistent>=0.14.0 in ./venv/lib/python3.6/site-packages (from jsonschema<5,>=3->flask-appbuilder<4.0.0,>=3.0.1->apache-superset) (0.18.0)
Requirement already satisfied: amqp<2.7,>=2.6.0 in ./venv/lib/python3.6/site-packages (from kombu<4.7,>=4.6.10->celery!=4.4.1,<5.0.0,>=4.3.0->apache-superset) (2.6.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./venv/lib/python3.6/site-packages (from packaging->bleach<4.0.0,>=3.0.2->apache-superset) (3.0.9)
Requirement already satisfied: defusedxml in ./venv/lib/python3.6/site-packages (from python3-openid>=2.0->Flask-OpenID<2,>=1.2.5->flask-appbuilder<4.0.0,>=3.0.1->apache-superset) (0.7.1)

**Comment by rusackas** [comment]
Since we're now on 3.1, on the verge of 4.0, we're not supporting 2.x  or prior versions actively. If anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)
