### ISSUE TITLE
Bypassing the login for Supreset using iframe

### ISSUE THREAD

**Issue by yogitabhardwaj2407** [apache/superset#20888]
I am using apache-superset. I wants to embed a slice into my webpage using its iframe. But when I logged out from superset at localhost port it gets logged out from that slice too on my webpage. Is there any way to prevent the logout from embed slice on webpage.

**Comment by srinisubramanian** [comment]
You can consider the guest login. There is an embed SDK to help implement that.

**Comment by yogitabhardwaj2407** [comment]
How can I integrate sdk in my Django Application?

Sent from Mail for Windows

**Comment by rusackas** [comment]
Closing this since it's been so long without interaction, and it's more of a support thread than a Superset bug. Please feel free to take further embedded questions to [Slack](http://bit.ly/join-superset-slack) or to Github Discussions.
