### ISSUE TITLE
Redis isn't working

### ISSUE THREAD

**Issue by Ragib01** [apache/superset#20896]
#### How to reproduce the bug
```
git clone https://github.com/apache/superset.git
cd superset
docker-compose -f docker-compose-non-dev.yml pull
```
**Then I configure to use Redis for caching**
In _superset/config.py_

```
import redis
...
CACHE_CONFIG = {
    'CACHE_TYPE':'redis', # Use Redis
    'CACHE_REDIS_HOST':'localhost', # Configure domain name
    'CACHE_REDIS_PORT': 6379, # Configure port number
    'CACHE_REDIS_URL':'redis://localhost:6379' # Configure URL
}

```
Then
```
docker-compose up
docker-compose -f docker-compose-non-dev.yml up
```
1. Go to _SQL Editor_
2. Run some query 
3. Create charts
4.  Run 
```
docker exec -it superset_cache redis-cli
```

5. No key value pairs with redis create

### Expected results
```
127.0.0.1:6379> KEYS '*'
1) "_kombu.binding.celeryev"
2) "_kombu.binding.celery"
3) "_kombu.binding.celery.pidbox"
4) "flask_cache_bf................"
5) "flask_cache_6c................"
```

### Actual results
```
127.0.0.1:6379> KEYS '*'
1) "_kombu.binding.celeryev"
2) "_kombu.binding.celery"
3) "_kombu.binding.celery.pidbox"
```

### Environment
- ubuntu version: 20.04.4 LTS

**Comment by sfirke** [comment]
Try changing `localhost` to `redis` in your URL: https://stackoverflow.com/a/63972247/4470365
And you need several types of cache, https://stackoverflow.com/a/72145437/4470365  The full set are documented in `/superset/config.py`

These fixed it for me.  If they fix it for you too, maybe the default config is wrong?

**Comment by rusackas** [comment]
Assuming this is fixed by the comment, or the original author isn't around. Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.

**Comment by mtovmassian** [comment]
I made the same observation with Superset v3.1.0. Whereas my cache configuration is well set, when I inspect the key/value pairs stored in redis I got only:
```shell
127.0.0.1:6379> keys *
1) "_kombu.binding.celery"
2) "_kombu.binding.celery.pidbox"
3) "_kombu.binding.celeryev"
```
Then I understand that there are actually two databases:
```shell
127.0.0.1:6379> info keyspace
# Keyspace
db0:keys=3,expires=0,avg_ttl=0
db1:keys=16,expires=16,avg_ttl=84395431
```
And If I select the second `db`, I find the expected Superset key/value pairs:
```shell
127.0.0.1:6379> select 1
OK
127.0.0.1:6379[1]> keys *
 1) "superset_explore_cachesRY7u3miuZUUW-YxMgUfcyec8dVfMfp0lNmEfMc-j5hckiQkPUHHS-hzEEsfHqcj"
 2) "superset_filter_cache2;lwT4VFo4S-24ljI2ALt-jt3BYSxTFlP9Z67HaMnZ2KS9mSztblVoM3FFujHTXkBc"
 3) "superset_explore_cache432b454caa649faa0133735bd34cab457c4f5f528d4b50beead61d32000d75bcd0640386a780b2498ce757c29a5322589e5f7f511cc391ee9cc5781c55afed73;3;8;30;table"
...
```
