### ISSUE TITLE
support fips compliance by replacing md5 with sha256

### ISSUE THREAD

**Issue by actionjax** [apache/superset#20904]
Hello, we work on fips compliant systems and superset will not work unless all the hashes are replaced with encryption stronger than md5. Can superset be modified to use sha256? I think it should be as simple as replacing all md5() calls with sha256(). Notably the uuid generation (key_value/utils.py) is the source of the compliant. I can work on a PR on my spare time if desired.

**Comment by rusackas** [comment]
Closing this issue since it's a feature request more than a bug. We're still hopeful that the PR can be picked up by a volunteer, but in the meantime, we're trying to whittle the Issues backlog to bugs only, so we'll close this. Thanks for the contributions!

**Comment by mamccorm** [comment]
Some of these are related to dependencies? Filed PRs:

- https://github.com/dpgaspar/Flask-AppBuilder/pull/2234
- https://github.com/pallets-eco/flask-caching/pull/563
