### ISSUE TITLE
Ignore columns when syncing datasets that already contain calculated columns with the same name

### ISSUE THREAD

**Issue by manikanta-dornala** [apache/superset#20907]
Refreshing datasets is blocked when there is a 'calculated column' with the same name as an incoming column. 

It would be good if superset ignores the new incoming column and honors the existing calculated column with the same name

The workaround for this currently is to delete the newly imported column from ‘columns’ tab and then hit save.

We are using the same name to not confuse users and to make dashboards and charts backwards compatible. Updating the column name everywhere is not feasible. So we created a calculated column with the same name but with some underlying sql and all dashboards/charts work as is but with calculated data.

Columns sync could be smarter in this aspect.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
