### ISSUE TITLE
Problem with Admin permissions in Superset 2.0.0

### ISSUE THREAD

**Issue by wiktor2200** [apache/superset#20913]
Dashboards of all users are not shown to anyone except `Admin` role. Even when Admin role is copied and assigned to user it's impossible to see other users' dashboards.

#### How to reproduce the bug
0. As `Admin` user create any dashboard (no matter if it's published or not) and it will be available in "Dashboards" menu.
1. Go to `List Roles`
2. Select `Admin` role and in `Actions` list select `Copy role` and rename it whatever you want e.g. "copied" (so role has the same permissions as Admin.
4. Create (if not exist) new user and assign `copied` role to it.
5. Login as user with assigned `copied` role and no dashboards are shown in `Dashboards` menu.

What is more when you assign `Admin` role to user from point 4. above dashboards will be shown.
 
### Expected results
Dashboards view should be managed by permission, not role name.

#### Screenshots

Admin role:
![Admin_role](https://user-images.githubusercontent.com/29948368/181742036-aa8279b7-fa82-404a-8648-a1392baeb9bc.png)
copied role:
![copied_role](https://user-images.githubusercontent.com/29948368/181742045-16882b40-2453-4d6d-9e68-76ccce216137.png)
Dashboard view for `Admin` role (the same user):
![dashboard_view_admin_role](https://user-images.githubusercontent.com/29948368/181750077-99573204-c63a-4f4d-8a1d-d2ff1090b95b.png)
Dashboard view for `copied` role (the same user):
![dashboard_view_copied_role](https://user-images.githubusercontent.com/29948368/181750079-d3a5dd11-2a4f-44d6-baaf-7dc8631fb145.png)

### Environment

(please complete the following information):

- browser type and version: FF/Chrome (all browsers are affected)
- superset version: `2.0.0` and `latest` (29th of July)
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active: no

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset. (both `2.0.0` and `latest`)
- [x] I have checked the issue tracker for the same issue and I haven't found one similar. (I think this is #20638 similar, but solved problem only for published dashboards for others problem still exists.)

**Comment by wiktor2200** [comment]
Update: the same applies for other features (alerts in my case) managed by user with attached Admin permission. When user is co-owner of Alert he is able to modify alert or turn it on or off. But for other users can only list and see configuration but when trying to apply changes gets Forbidden 403 error.
![alert list](https://user-images.githubusercontent.com/29948368/181779506-548e9ca3-6432-4613-b1f9-8fb2c4a58d97.png)
![users](https://user-images.githubusercontent.com/29948368/181779511-915ed05a-400a-4e32-8f15-e3c93cd90790.png)
User is using `copied` Admin role, so has the same permissions as `Admin` but is not able to do the same things.

**Comment by Noamstrauss** [comment]
I have the same issue while trying to create a chart, i get forbidden.

**Comment by KillenMr** [comment]
Can confirm superset init fixes the issue.

**Comment by wiktor2200** [comment]
`superset init` doesn't work for me, problem still exists.

**Comment by rusackas** [comment]
Since we're now on 3.1, on the verge of 4.0, we're not supporting 2.x  or prior versions actively. If anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)
