### ISSUE TITLE
[Navigation] - Navigate Across All The Dashboards Directly From Any Where In The App

### ISSUE THREAD

**Issue by pankajsoni22** [apache/superset#20926]
### Discussed in https://github.com/apache/superset/discussions/20897

<div type='discussions-op-text'>

<sup>Originally posted by **pankajsoni22** July 28, 2022</sup>
# Purpose of discussion:
This discussion has a purpose of improving user experience in terms of switching between different dashboard or want to land on a particular dashboard from anywhere in the app.

# Issue with current design:
Current design does not provide one click redirection to any dashboard if user is not on `/dashboard/list` page. User has to go to '/dashboards/list' page first and then select from there, as you can see in the following diagram current design is
![superset-nav-old](https://user-images.githubusercontent.com/39917736/181445578-3cd25ecb-b319-40b3-8eb6-8a856ec91ad4.png)

Cons:
1. It takes more time for the user to land on dashboard if he/she is working some where in explore/sql editor/saved queries.
2. It waste resources on client side (like bandwidth), page rendering.
3. Every time going through dashboard list makes unnecessary calls to backend.

# Proposed solution:
The solution gives an idea towards a new item ingestion in menu i.e. Navigate which holds list of all current dashboards allowed to particular user, these all items are links to dashboards and with one click user will be directly landing on corresponding dashboard he/she selected. Proposed solution has the following flow and design changes
![superset-nav-new](https://user-images.githubusercontent.com/39917736/181448477-4b724fdc-6d86-4f21-98f8-54fdd54a4cc0.png)

Pros:
1. Bypass dashboard list page as no more required to get list of dashboards - this saves time of user.
2. This saves client side resources as this is a quick landing without useless rendering of dashboard list page.
3. Bypassing dashboard list page will naturally reduce calls to backend.

Above solution on typical superset dashboard may look like following screenshots:
1. Introduction of one more item in top-menu: 
![super-nav-dropdown-highlight](https://user-images.githubusercontent.com/39917736/181449003-a3502e92-1adf-4f21-b3ed-90a9491d37d9.png)

2. List of dashboard in top-menu from `dashboard/list` page:
![super-nav-from-dashboard-list](https://user-images.githubusercontent.com/39917736/181449453-c84052bf-7e5a-4bb6-a293-3b065e9a73f1.png)

3. List of dashboard in top-menu from `superset/lsqllab` page:
![super-nav-from-sql-editor](https://user-images.githubusercontent.com/39917736/181449662-5e14ea3c-4a4c-4144-befe-135fc0d4a228.png)

4. List of dashboard in top-menu from `chart/list` page:
![super-nav-from-charts-list](https://user-images.githubusercontent.com/39917736/181449748-c9a44c44-8f9e-4e98-970d-d64fd1f994d7.png)

5. List of dashboard in top-menu from `databaseview/list` page:
![super-nav-from-databases](https://user-images.githubusercontent.com/39917736/181450083-8e280dc9-8f7d-420b-9f71-a7fcdbe1b7b0.png)

6. Switch among dashboards:
![super-nav-from-within-dashboard](https://user-images.githubusercontent.com/39917736/181450285-1ff3d753-1673-4e2a-9bed-b61110ce950a.png)

# Final Comments:
Superset community may allow or reject this design but the idea should be accepted, design may change as everytime going to dashboard list page is a hactic for user.

Please comment you thoughts and let me know if any design changes are required or this easy but impactable solution works.
</div>

**Comment by rusackas** [comment]
Thanks for opening this issue. Since it's an enhancement/feature, I don't think we need this issue. We're trying to keep the issues backlog under control, which means we're limiting it to bugs. We can convert this to a discussion if you'd like, but I think it's probably easier to just close the issue and continue to try to bring the PR back to life. Thanks for the contribution by the way, let's take the conversation there!
