### ISSUE TITLE
Do not deprecate the filter box charts

### ISSUE THREAD

**Issue by ypankovych** [apache/superset#20943]
Do not remove the Filter Boxes. 

New dashboard filter components CANNOT replace the old Filter Boxes. Instead of having a single filter box for all the dashboards, I need to go through every dashboard to create its own filter. Now it's impossible to modify the filter box chart and change the filters for all the dashboards that use that filter box.

I suggest keeping both filter boxes and dashboard native components. 

Filter boxes are useful for global filters that could be changed in a single place. Meaning that the N dashboards gonna have a single filter box that can be modified just ONCE and not N times (for each dashboard). That allows developers to do all sorts of automation (dynamic column creations for the filter boxes/etc)

Dashboard native components for on-premise filter boxes. Meaning that there gonna be dashboards with very specific filters that cannot be reused anywhere else.

**Comment by Sandy381** [comment]
+1
Yes Filter Box is needed to filter components for entire dashboard.

**Comment by jmcapra** [comment]
What is the latest on this? Were filter boxes deprecated? 

It would be really great if we were able to set global filters, controllable via URL params, that are shared by multiple dashboards. 
E.g., if I want to generate a link for a dashboard filtered by "Country", I currently need to do this separately for each dashboard, depending on which NATIVE_FILTER_ID is associated with "Country" for that dashboard. 

As @ypankovych suggested above:

> Filter boxes are useful for global filters that could be changed in a single place. Meaning that the N dashboards gonna have a single filter box that can be modified just ONCE and not N times (for each dashboard). That allows developers to do all sorts of automation (dynamic column creations for the filter boxes/etc)

**Comment by nemccarthy** [comment]
One giant step backwards

**Comment by ImadYamane** [comment]
+1

**Comment by leandroembu** [comment]
+1

**Comment by etadelta222** [comment]
+1

**Comment by artemonsh** [comment]
+1

**Comment by NattikaNJ** [comment]
+1

Now I get a problem, when I set up multiple filters on native filter,  which works with "AND" combination, but I need to switch from "AND" to "OR"

![Capture](https://github.com/apache/superset/assets/32167235/b176c218-8103-4409-b838-622375d69ff1)

**Comment by timalive** [comment]
+1

**Comment by kevigwilson** [comment]
+1
Filter boxes are also super useful for dashboard flow and useability; having a filter above a specific table in a nested tab is much more useable than having a central filter down the side. The filter scope is intuitive and implied by its positioning.

**Comment by rusackas** [comment]
They've already been deleted as part of the 4.0 effort, after much discussion, gathering official community consensus, and giving everyone migration plans and years of warning. If people aren't happy about this, they can stick on 3.x versions and/or contribute to the future of Dashboard Native filters (adding OR logic, putting them in dashboards, whatever else you think is missing). Superset will be a more sustainable project thanks to this deprecation.

**Comment by sfirke** [comment]
> contribute to the future of Dashboard Native filters (adding OR logic, putting them in dashboards, whatever else you think is missing)

Ditto this.  The `OR` logic is a great example.  If folks can contribute code to make this happen for dashboard native filters, that would be incredible.  If not, it's still helpful to file a specific feature request in GitHub Discussions to capture community voice and details re: how to improve dashboard native filters.  Just please search first to see if such a discussion already exists.  Thanks for constructive input on how to improve Superset 🙏

**Comment by kleky** [comment]
I'm also baffled that this was deprecated.

Superset is up against the likes of power BI, and such a simple feature is a filter where I can select from list of X labels, which filters using the selected values. E.g. List of currencies (GBP, USB...), but the selected currency exchange rate is used in the filter.
