### ISSUE TITLE
How to Enable Row level security and other data access roles in superset. Not visible in menu list.

### ISSUE THREAD

**Issue by maahivikas** [apache/superset#20944]
Hi, 
i have deployed superset using helm and yaml file('https://superset.apache.org/docs/installation/running-on-kubernetes/'). 
i have read your security documentation from- [https://superset.apache.org/docs/security/"](url), and tried to implement OAuth for that i configured yaml from - [https://flask-appbuilder.readthedocs.io/en/latest/security.html](url) .
Superset is using its by default webserver. 
I want to enable "row level security" feature in superset but i am unable to do it.  It is not showing in its menu. 
I am attaching snapshot of my menu list. 
![Screenshot (370)](https://user-images.githubusercontent.com/48925341/182377074-46feda39-5610-4a7d-97a2-746b6761b1d1.png)
For reference:
I have configured the yaml from : [https://github.com/apache/superset/blob/master/helm/superset/values.yaml](url)
please can you suggest how can i enable row level security feature and other data access control features in it.

**Comment by maahivikas** [comment]
i have upgraded the version to 1.4.1 but there is issue in database connectivity. I am using CrateDB for database purpose. 
Also i use command superset db upgrade.
After running superset init command i got error: 
![Screenshot 2022-08-04 104004](https://user-images.githubusercontent.com/48925341/182992255-04357144-caa3-4344-acd1-b47cb122572b.png)
can anyone suggest how to fix it ?

**Comment by rusackas** [comment]
Since we're now on 3.1, on the verge of 4.0, we're not supporting 2.x  or prior versions actively. If anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)
