### ISSUE TITLE
Connect database from top right corner button doesn't work in 1.5.1

### ISSUE THREAD

**Issue by mayurnewase** [apache/superset#20951]
#### How to reproduce the bug

1. Go to homepage
2. Hover on + sign on top right corner -> hover on data -> click "Connect database"

It works in master, happening because Antd tab component in this version is calling onclick handler with key of the parent element instead of the actual element being clicked so onclick handler doesn't recognise the key and ignores the event.

### Expected results
Should open Add database modal

### Actual results

Nothing happens

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by michael-s-molina** [comment]
Thanks for reporting this issue @mayurnewase. A fix has been included in the [1.5 branch](https://github.com/apache/superset/commits/1.5) and it will be available as part of 1.5.2
