### ISSUE TITLE
Got 504: Gateway time-out after a minute even with --timeout 600  gunicorn's param.

### ISSUE THREAD

**Issue by pashkash** [apache/superset#20963]
Hey.

I changed the gunicorn parametters via env variables, but still getting 504 error during the Chart creation or SQL lab.

#### How to reproduce the bug

1. Setup Trino ORM with Hive connector. Change `GUNICORN_KEEPALIVE` param to 600 in `.env-non-dev` and `superset_config.py`.
2. Run the Superset with `docker-compose -f docker-compose-non-dev.yml up`
3. Enter the docker container and check that params are passed with `ps` `...  /usr/local/bin/python /usr/bin/gunicorn --bind 0.0.0.0:8088 ... --timeout 600`
5. Go to "Create new chart" in the web UI. Fill query params. Run the query.
6. Get "504: Gateway time-out" after a minute of waiting.

### Expected results
A chart should be shown with data from connectors even if my query was processing for 1m+.

### Actual results
I got the 504 response after a minute.

#### Screenshots
![image](https://user-images.githubusercontent.com/5039134/182683101-b5ac1ca0-575f-4186-8159-32025e0f929e.png)

### Environment

- browser type and version: Safary, Chrome;
- superset version: the latest superset-image

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar. found [this](https://github.com/apache/superset/issues/5993) but closed and not helpful.

### Additional context
If a query is finished in less than a minute - i can see my chart.

**Comment by pashkash** [comment]
@sfirke sorry for disturbing you, but maybe you know what I need to check also? thank you a lot!

**Comment by sfirke** [comment]
I don't know anything about gunicorn, unfortunately.

**Comment by pashkash** [comment]
@mdeshmu thank you, man, but tried this before posting this. any other ideas?

**Comment by nytai** [comment]
Are you sure there isn't nginx or a load balancer in front of superset? 504 is usually thrown by a proxy and not gunicorn

**Comment by nytai** [comment]
just fyi, I have been able to use increase the timeout using the `GUNICORN_TIMEOUT` env var on `gunicorn==20.1.0`. I am running nginx though (k8s ingress) and I also had to increase timeouts there.

**Comment by pashkash** [comment]
ty a lot! it seems we have cloudflare http proxy; let me check if it will work after devops make changes in dns;

**Comment by nytai** [comment]
closing this as it seems this is not actually an issue
