### ISSUE TITLE
Error Install Superset 2.0 - ModuleNotFoundError: No module named 'werkzeug.wrappers.etag'

### ISSUE THREAD

**Issue by fredericksalazar** [apache/superset#20967]
when installing the apache-superset package using pip install apache-superset in local mode, I proceed to initialize the database with the command superset db upgrade which throws the error ModuleNotFoundError: No module named 'werkzeug.wrappers.etag the same happens to try to start with the command superset run -p 8088 an environment with python 3.8.13 is being used

what you expected to happen.

what actually happens.

#### Screenshots

<img width="1130" alt="Captura de Pantalla 2022-08-03 a la(s) 19 27 17" src="https://user-images.githubusercontent.com/1855499/182737708-39e9c516-c6a8-45ad-8225-a5745f048f90.png">

### Environment

(please complete the following information):

- browser type and version:
- superset version: `2.0`
- python version: `python 3.8.13´

**Comment by srinisubramanian** [comment]
Please follow comments in #20942 for resolution

**Comment by rusackas** [comment]
Since we're now on 3.1, on the verge of 4.0, we're not supporting 2.x  or prior versions actively. If anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)
