### ISSUE TITLE
DB engine Error

### ISSUE THREAD

**Issue by nightbear1009** [apache/superset#20968]
after upgrade to superset helm 0.7.0 global filter is not working the error message is shown as below

i am connect to Bigquery and I find out when using filter with `=` it works. But when using `in` filter shown error
```
Unexpected param: (2, 3)

This may be triggered by:
Issue 1011 - Superset encountered an unexpected error. 


Please reach out to the Chart Owner for assistance.

Chart Owner: Admin Admin
```

error message as below
<img width="961" alt="image" src="https://user-images.githubusercontent.com/5819643/182790717-b76d0c8c-1a3b-407b-9b36-16735f874b9c.png">

and the image is shown as below 

<img width="995" alt="image" src="https://user-images.githubusercontent.com/5819643/182741826-4f0fe2d0-eb5a-4026-bcf6-5ff20dadfea9.png">

**Comment by venkatAkula8** [comment]
Hi [nightbear1009](https://github.com/nightbear1009), I'm also facing same issue. Did you find any solution? 
Thank you

**Comment by nightbear1009** [comment]
prevent pip install elaticsearch  solve my problem

**Comment by Yatagani** [comment]
Hi @venkatAkula8, I had the exact same issue. Install `sqlalchemy-bigquery` instead of `pybigquery` in the `values.yaml` config file. Seems like `pybigquery` is outdated. https://pypi.org/project/pybigquery/

**Comment by pthirumalai** [comment]
Hi @Yatagani , I created a dashboard with filter and when I tried to use the filter to manipulate the dashboard, I am getting "DB engine error". We installed sqlalchemy-bigquery and uninstalled pybigquery but still we have this issue. Do we need to make any changes to the values.yaml file ? 

![apache superset filter error](https://user-images.githubusercontent.com/114579758/192766791-b8852431-00c4-4a9b-bd84-8747cddb4567.png)

**Comment by Yatagani** [comment]
Hi @pthirumalai,
Can you ensure that the update was successfully made? And the  helm chart now has the right configuration. 
To upgrade chart on Kubernetes run: helm upgrade --install --values values.yaml superset superset/superset
To see if your current chart config run: helm get values superset 

My output:
```
bootstrapScript: |
  #!/bin/bash
  rm -rf /var/lib/apt/lists/* && \
  pip install \
    psycopg2-binary==2.9.1 \
    sqlalchemy-bigquery==1.4.0 \
    redis==3.5.3 && \
  if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi
```

**Comment by pthirumalai** [comment]
Hi @Yatagani 

We have installed Apache superset in Docker, How can we check whether we have configured correctly in Docker ?

Thanks

**Comment by saghatelian** [comment]
Hi @pthirumalai 
We also have a Docker installation. 
Changing `pybigquery` to `sqlalchemy-bigquery` in `docker/requirements-local.txt` solved the issue for me.

**Comment by pthirumalai** [comment]
Hi @saghatelian 

The issue got resolved after we made changes to the docker/requirements-local.txt as per your suggestion. Thanks.

**Comment by duchuynh** [comment]
Hi, bumping this because I am having the same error when I shut down Superset and start it again...

**Comment by rusackas** [comment]
Sounds like the author of this issue resolved their issue, this spun out into another issue, and that was likely resolved as well. Closing this as stale, but if anyone is still facing this stuff, I'd suggest opening a fresh bug report with updated context for any bugs, and taking any config discussions to Q&A thread or Slack. It's been a while since this thread saw any action though, so I'm hoping all is well!
