### ISSUE TITLE
JINJA_CONTEXT_ADDONS: call existing function inside custom new one: error

### ISSUE THREAD

**Issue by d9k** [apache/superset#20991]
#### How to reproduce the bug

`superset_config_docker.py`:

```
def filter_value_first(
  self, column: str, default = None, remove_filter: bool = False
):
  return self.filter_values(column, default, remove_filter)[0]

JINJA_CONTEXT_ADDONS = {
  "filter_value_first": filter_value_first,
}
```

sql query template:

```
{% set val = filter_value_first('my_filter') %}
```
### Expected results

`filter_value_first` returns first value from filter.

### Actual results

Error:

```
filter_value_first() missing 1 required positional argument: 'column'
```

### Environment

(please complete the following information):

- superset version: `1.5.0rc4`

### Additional context

So I can't use `self` argument.
How can I get existing jinja template processor object in my `filter_value_first()` function?

**Comment by rusackas** [comment]
Since we're now on 3.1, on the verge of 4.0, we're not supporting 2.x  or prior versions actively. If anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)
