### ISSUE TITLE
/dashboard/export API compatibility issue between v1.5 and v2.0

### ISSUE THREAD

**Issue by xingyc15** [apache/superset#21001]
We have some dashboard developed in v1.5.0. After we upgrade the dashboard into v2.0.0, and use the /dashboard/export API endpoint to export the dashboards, there are unreadable characters in the exported json file.

#### How to reproduce the bug

1. Develop a dashboard under superset version 1.5.0
2. Upgrade superset to version 2.0.0
3. Use /dashboard/export API to export the dashboard into a json file

### Expected results

The dashboard json exported from v1.5.0 should be able to be successfully parsed by superset v2.0.0

### Actual results

There are some unreadable characters.

The json file starts with this:
`PK!�gٝMM.dashboard_export_20220806T005733/metadata.yamlversion: 1.0.0
type: Dashboard
timestamp: '2022-08-06T00:57:33.133934+00:00'
PK!?�8���Fdashboard_export_20220806T005733/datasets/pinot/map_labeling_logs.yamltable_name: map_labeling_logs
...`

### Environment

- superset version: `1.5.0 and 2.0.0`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by grumpy-miner** [comment]
It is because in v2.0.0 dashboard is downloaded as zip file.
If you want to continue exporting dashboard as json file you need to add `VERSIONED_EXPORT` as `False` in `FEATURE_FLAGS`
```py
FEATURE_FLAGS = {
        ...
        "VERSIONED_EXPORT": False,
    }
```

**Comment by Agos88** [comment]
Any update about this bug?
If we use `FEATURE_FLAGS = {
        ...
        "VERSIONED_EXPORT": False,
    }` this condition will be always false
`const canExport =
    hasPerm('can_export') && isFeatureEnabled(FeatureFlag.VERSIONED_EXPORT);`

**Comment by vergenzt** [comment]
@Agos88 I think what you're talking about is a separate issue, and has been reported/is being tracked at https://github.com/apache/superset/issues/26417

**Comment by rusackas** [comment]
I'm assuming that since this has been quiet for so long, we're all good now? `VERSIONED_EXPORT` has been deprecated, and we no longer support versions prior to 3.1/4.0. If this needs more discussion, we can certainly revisit/reopen.
