### ISSUE TITLE
直接写sql绘制图表不需要再去构建charts

### ISSUE THREAD

**Issue by micaimanong1** [apache/superset#21013]
使用起来太难用了, 我构建了一个sql 的数据集之后 还必须用软件指定的聚合方式进行图表绘制, 如果我的sql产生的数据可以直接绘制图还强行指定聚合这实在是难用到无法忍受. 而且我的时间字段已经是格式化好了的时间字段, 但是这个软件非要把我的时间字段改成数值型的时间戳. 
可以借鉴一下metabase, 那个用起来就清爽很多. 可以通过拖拽的方式构建数据集直接绘制图标或者通过sql 产生数据集快速构建图表, 简直比这个好用了太多了!!
希望得到改进!加油!!

**Comment by ieayoio** [comment]
我们也打算找一款这样的软件，问一下，那Metabase有什么缺点呢，导致你在已经使用了Metabase情况下再来了解superset

**Comment by zhaoyongjie** [comment]
@micaimanong1 请您用具体例子来说明issue. 什么是"时间字段已经是格式化好了的时间字段"?

**Comment by micaimanong1** [comment]
> @micaimanong1 请您用具体例子来说明issue. 什么是"时间字段已经是格式化好了的时间字段"?

![图片1](https://user-images.githubusercontent.com/25268128/184059400-43a41f0e-f80e-4642-a3c6-8117931c0055.png)
@zhaoyongjie  你好是这样的: 我的日期格式是做好了的, 但是在这边出现了格式化出错了.
另外你能反馈一下可不可以不用必须使用superset的聚合方式直接使用sql产生的数据进行图表绘制.

**Comment by micaimanong1** [comment]
> 我们也打算找一款这样的软件，问一下，那Metabase有什么缺点呢，导致你在已经使用了Metabase情况下再来了解superset

metabase没有导航栏,( superset 可以使用tab嵌套tab 的方式实现导航栏 ) 绘制的图不够满足我们的需求. 颜色比较单一, 图表的布局不太适合我们.  当然你可以试一下DataEase 各个bi软件有各自的优点. 有交流需要可以联系我 ssbgxwj@163.com

**Comment by ieayoio** [comment]
> > 我们也打算找一款这样的软件，问一下，那Metabase有什么缺点呢，导致你在已经使用了Metabase情况下再来了解superset
> 
> metabase没有导航栏,( superset 可以使用tab嵌套tab 的方式实现导航栏 ) 绘制的图不够满足我们的需求. 颜色比较单一, 图表的布局不太适合我们. 当然你可以试一下DataEase 各个bi软件有各自的优点. 有交流需要可以联系我 [ssbgxwj@163.com](mailto:ssbgxwj@163.com)

非常感谢，我们再研究下

**Comment by zhaoyongjie** [comment]
@micaimanong1 

> 我的日期格式是做好了的, 但是在这边出现了格式化出错了.

这是个 treemap v2 的 label bug, 您可以开一个issue, 同样问题在其他图上是没有的(我刚测试了主分支)

> 另外你能反馈一下可不可以不用必须使用superset的聚合方式直接使用sql产生的数据进行图表绘制.

即便是 materialize view (已经聚合的结果集) 和如何绘制 chart 看起来没有什么关系.
