### ISSUE TITLE
Format the same size of picture  for better part of  "Supported Databases" document.

### ISSUE THREAD

**Issue by zhouyao1994** [apache/superset#21028]
### Motivation
I'm learning how to use Photoshop. At same time ,I think the Part of  "Supported Databases"  in  README’s picture is not align better. Since the picture of logos is not the some size.

I think we can learn from the part of "who is using Kylin" of [Apache Kylin](https://kylin.apache.org/)‘s  website,that is more beauty,

[the keylin website]
<img width="512" alt="image" src="https://user-images.githubusercontent.com/5468589/183650282-8c3d2455-1647-4679-af12-5ee6eb429470.png">
[the superset readme]
<img width="512" alt="image" src="https://user-images.githubusercontent.com/5468589/183655634-48a727ac-e15a-4722-874e-2851dfbee28b.png">

So I porpose this SIP to improve document better.
We can format the logo in the same format at the some size (for example,png, 400*160)

If accept, May be i can help.😁

### Proposed Change
No code change ,Just pictures and Readme file

format the logo in the same format at the some size . type:png  size:400*160

### New or Changed Public Interfaces
no change

### New dependencies

no change

### Migration Plan and Compatibility

no change

### Rejected Alternatives

other format, 200* 80 or something else

**Comment by srinify** [comment]
Hey @zhouyao1994 agreed! This doesn't need a SIP, which is reserved for major / controversial changes that require lots of discussions. 

Feel free to open a PR with improvements :)

https://preset.io/blog/tutorial-contributing-code-to-apache-superset/

**Comment by rusackas** [comment]
Looks like this should have been closed by the PR. Thanks for the contribution!
