### ISSUE TITLE
DISTINCT command error Incorrect syntax near the keyword on SQLLab when connect MSSQL database

### ISSUE THREAD

**Issue by unnyns-307** [apache/superset#21027]
When connect to MSSQL database cannot use DISTINCT command. SQLLab shows mssql error: 156, b"Incorrect syntax near the keyword 'DISTINCT'

#### How to reproduce the bug

1. Go to SQLLab editor 
2. Connect to MSSQL database connection
3. Query data with 'DISTINCT' command

### Expected results

Get data result of unique value normally

### Actual results

Get this following error:
> mssql error: (156, b"Incorrect syntax near the keyword 'DISTINCT'.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n")

#### Screenshots
![image (25)](https://user-images.githubusercontent.com/82924994/183552496-51cb1f0d-267d-4b71-90f1-1cf9ef1d349e.png)

### Environment

(please complete the following information):

- browser type and version: Chrome Version 104.0.5112.81 (Official Build) (64-bit)
- superset version: 2.0.0
- python version: 3.8.12
- node.js version:16
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

-

**Comment by sfirke** [comment]
I get this behavior too, Superset 2.0.0 connecting to MSSQL.

**Comment by EcoleKeine** [comment]
Same, any news?

**Comment by TerryLines** [comment]
same here. Also syntax errors on count(column) from table

**Comment by sfirke** [comment]
An idea: modify https://github.com/apache/superset/blob/b2b8c3e05b69cc19cbb8394f621c1b9095bda132/superset/db_engine_specs/base.py#L897-L899.  It currently finds the first select keyword (dialect-specific) and injects the TOP there.  It could instead find the first select keyword _followed by a non-select keyword_.

Then in `superset/db_engine_specs/mssql.py`, specify `select_keywords = {"SELECT", "DISTINCT"}`.  Then the TOP 1000 would get injected after SELECT DISTINCT.
