### ISSUE TITLE
[SIP] Dynamic number of bins in Histogram

### ISSUE THREAD

**Issue by vinibs** [apache/superset#21039]
### Motivation

At my company, we started to use Superset to generate some charts for our data and we faced troubles when using the Histogram visualization due to its number of bins: our data, for the same time interval, could bring values whose ranges can vary a lot (in a scenario, they could be from 1 to 3, in another, from 1 to 27, for example) and we need the bins to be exactly one for each value - if our interval is from 1 to 5, we need 5 bins; if it's from 1 to 27, we need 27 bins. We can only set a fixed number of bins regardless of which is our data interval.

### Proposed Change

We thought about two possible ways to solve it: the first one would be setting, as the Histogram's default number of bins, the `MAX()` value in the data range, so, if we haven't defined a fixed number of bins, it would make a histogram with one bin for each value of our data; The second approach would be to allow to set a number of bins based on a query (for example, this `MAX()` function over the generated data) to dynamically set the number of bins based on our data's range.
For the second approach, it would involve changing the "Number of bins" select input, probably by also adding an extra window to insert the query we need to use on it.

### New or Changed Public Interfaces

This would affect mostly the Histogram visualization and the "Number of bins" selection component, in terms of User Interface and mainly the behavior of the bin calculation when generating the visualization.

### New dependencies

We don't think it would be necessary to add any new dependency.

### Migration Plan and Compatibility

At first, we don't see a need for any migration.

### Rejected Alternatives

We didn't think of any alternative that was already been rejected. The idea is to bring some discussion to find the best approach here.

We're planning to try to implement it here at my company to solve our problem as quickly as possible and, if this solution is good enough to merge as an improvement for the project, we'd be happy to do so.

**Comment by rusackas** [comment]
Closing this, and adding a reference on[ the relevant Github discussion](https://github.com/apache/superset/discussions/24215), where we're accumulating the feature requests for a new ECharts histogram/distribution chart.
