### ISSUE TITLE
Connection and host liveness checks use only ipv4

### ISSUE THREAD

**Issue by vin01** [apache/superset#21041]
Hi,

currently hostname validation (https://github.com/apache/superset/blob/master/superset/utils/network.py#L42) and port check (https://github.com/apache/superset/blob/master/superset/utils/network.py#L25) use only ipv4 addresses (because of `gethostbyname` and `AF_INET` respectively)

This results in ipv6 only hostnames being marked as invalid and ports show up as closed.

Both of these can be. fixed by using `getaddrinfo`.

- https://docs.python.org/3/library/socket.html#socket.gethostbyname
- https://docs.python.org/3/library/socket.html#socket.getaddrinfo

I am creating this single issue to track both these bugs as they are related. Hopefully that is alright with the [guidelines](https://github.com/apache/superset/blob/master/CONTRIBUTING.md#pull-request-guidelines) ;)

Please review related patches.

Thanks!

**Comment by betodealmeida** [comment]
Thanks for the PRs!
