### ISSUE TITLE
Unknown option '--devserverPort=9001'

### ISSUE THREAD

**Issue by wang-valdanito-chao** [apache/superset#21049]
#### How to reproduce the bug

1. I start the frontend according to [this post](https://preset.io/blog/tutorial-contributing-code-to-apache-superset/#setting-up-your-local-development-environment-frontend).
2. I passed two parameters:
```
npm run dev-server -- --devserverPort=9001 --supersetUrl=http://127.0.0.1:8088
```
3. Terminal output error:
```
> superset@1.5.1 dev-server
> cross-env NODE_ENV=development BABEL_ENV=development node --max_old_space_size=4096 ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --mode=development "--devserverPort=9001" "--supersetUrl=http://127.0.0.1:8088"

[webpack-cli] Error: Unknown option '--devserverPort=9001'
[webpack-cli] Run 'webpack --help' to see available commands and options
```

### Expected results

The frontend starts success and the passed parameters take effect.

### Actual results

```
[webpack-cli] Error: Unknown option '--devserverPort=9001'
```

### Environment

- superset version: `1.5.1`
- python version: `miniconda  python 3.8.12`
- node.js version: `v16.15.1`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by stephenLYZ** [comment]
@wang-valdanito-chao Hi. Some of the content in this article is out of date, so I recommend referring to the official superset documentation. https://github.com/apache/superset/blob/master/CONTRIBUTING.md#webpack-dev-server

```
# Run the dev server on a non-default port
npm run dev-server -- --port=9001
```

**Comment by rusackas** [comment]
Closing this since it's likely obsolete after following the provided docs :)
