### ISSUE TITLE
treemap V2  bug 

### ISSUE THREAD

**Issue by micaimanong1** [apache/superset#21056]
## Screenshot

![image](https://user-images.githubusercontent.com/25268128/184088729-d35cd884-f2f7-4f7e-ad8d-089f33fd6aae.png)

## Description

版本: superset 2.0.0
绘制图表时间展示不对

**Comment by stephenLYZ** [comment]
@micaimanong1 Hi. 看起来需要调整一下 time format：
<img width="315" alt="image" src="https://user-images.githubusercontent.com/11830681/184608403-3d694289-5eb9-495e-b512-3e12666f9e3d.png">

**Comment by micaimanong1** [comment]
> @micaimanong1 Hi. Looks like you need to change your time format: <img alt="image" width="315" src="https://user-images.githubusercontent.com/11830681/184608403-3d694289-5eb9-495e-b512-3e12666f9e3d.png">

![image](https://user-images.githubusercontent.com/25268128/184836954-d38bdd3a-2f8f-4044-8e21-5e8a195e7a24.png)
Has been modified   time format:
![image](https://user-images.githubusercontent.com/25268128/184837575-fb86b28a-5445-48ba-998d-7c300888def9.png)

**Comment by rusackas** [comment]
Since we're now on 3.1, on the verge of 4.0, we're not supporting 2.x  or prior versions actively. I think this might even be fixed, but if anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps, or we can re-open this one.
