### ISSUE TITLE
Big Number with Trendline is unable to handle time column

### ISSUE THREAD

**Issue by micaimanong1** [apache/superset#21059]
## Screenshot
你好目前遇到这个图形不能处理好时间.
版本: 2.0.0 和1.5.1

查询出来的结果
![image](https://user-images.githubusercontent.com/25268128/184141138-792e8567-7a84-4926-aa24-e78e9456b220.png)

![image](https://user-images.githubusercontent.com/25268128/184143018-d42854f4-6eb2-41e9-8a57-91e55bf58ff9.png)

绘制图形的时候报错
![image](https://user-images.githubusercontent.com/25268128/184141231-ef9ea5e6-3548-47e3-9014-60652b260250.png)
![image](https://user-images.githubusercontent.com/25268128/184141395-2880c852-d4f1-45c9-ab06-f5d52326829a.png)
类型配置的都没有问题吧
![image](https://user-images.githubusercontent.com/25268128/184141435-22ebe77d-cbf4-486f-b2ae-f338c6265f7c.png)

**Comment by zhaoyongjie** [comment]
Hi @micaimanong1

> 
> 绘制图形的时候报错 ![image](https://user-images.githubusercontent.com/25268128/184141231-ef9ea5e6-3548-47e3-9014-60652b260250.png) ![image](https://user-images.githubusercontent.com/25268128/184141395-2880c852-d4f1-45c9-ab06-f5d52326829a.png) 类型配置的都没有问题吧 ![image](https://user-images.githubusercontent.com/25268128/184141435-22ebe77d-cbf4-486f-b2ae-f338c6265f7c.png)

这个很明显是SQL报错. 请检查action_time数据类型. 

Hi, It seems a SQL syntax error, please check out the data type of the `action_time` column and make sure it's datatime/timestamp/date

![image](https://user-images.githubusercontent.com/2016594/184277869-e408290c-988a-4930-adb0-eb92487f3b6a.png)

此外, 为了让这些issue可以被更多人参考, 请您简单翻译成英文. 多谢.

**Comment by micaimanong1** [comment]
> 你好@micaimanong1
> 
> > 绘制图形的时候报错 ![图片](https://user-images.githubusercontent.com/25268128/184141231-ef9ea5e6-3548-47e3-9014-60652b260250.png) ![图片](https://user-images.githubusercontent.com/25268128/184141395-2880c852-d4f1-45c9-ab06-f5d52326829a.png) 类型配置的都没有问题吧 ![图片](https://user-images.githubusercontent.com/25268128/184141435-22ebe77d-cbf4-486f-b2ae-f338c6265f7c.png)
> 
> 这个很明显是SQL报错. 请检查action_time数据类型.
> 
> 您好，似乎是 SQL 语法错误，请检查该`action_time`列的数据类型并确保它是 datatime/timestamp/date
> 
> ![图片](https://user-images.githubusercontent.com/2016594/184277869-e408290c-988a-4930-adb0-eb92487f3b6a.png)
> 
> 此外, 为了让这些issue可以被更多人参考, 请您简单翻译成英文. 多谢.

中文: 可以看到的是这个字段图标是对应的时间类型的图标, 两个时间类型的字段都被转化成了时间戳, 这个会不会是因为superset对vertica 的支持的问题呀?
English: This field icon is the icon of the corresponding time type, and both time type fields are converted into timestamp numbers. Will this be because of superset and vertica problems?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.   Thanks!
