### ISSUE TITLE
[SIP-89] Integrate role, permission, user APIs on Flask-AppBuilder into Apache Superset

### ISSUE THREAD

**Issue by jileeon** [apache/superset#21050]
### Motivation

To manage roles, permissions, and users automatically via APIs

### Proposed Change

Initialize them using appbuilder extension.

### New or Changed Public Interfaces

Yes. These APIs can be used on Apache Superset Web Service. See the screenshot below.

![스크린샷 2022-08-11 오후 2 59 57](https://user-images.githubusercontent.com/5166067/184072831-8e4bbb49-21fc-45d8-b370-1b6308329b17.png)

### New dependencies

Already satisfied with Superset 2.0

### Migration Plan and Compatibility

N/A

### Rejected Alternatives

N/A

**Comment by jileeon** [comment]
References: 
- Étienne Boisseau-Sierra shares changes on Flask-AppBuilder https://apache-superset.slack.com/archives/C016B3LG5B4/p1645530259348389?thread_ts=1643809338.286369&cid=C016B3LG5B4
- the PR about this feature on Flask-AppBuilder https://github.com/dpgaspar/Flask-AppBuilder/pull/1801

**Comment by trixieboyle** [comment]
> ### Motivation
> 
TammyBoyle
> To manage roles, permissions, and users automatically via APIs
> 
> ### Proposed Change
> 
> Initialize them using appbuilder extension.
> 
> ### New or Changed Public Interfaces
> 
> Yes. These APIs can be used on Apache Superset Web Service. See the screenshot below.
> 
> ![스크린샷 2022-08-11 오후 2 59 57](https://user-images.githubusercontent.com/5166067/184072831-8e4bbb49-21fc-45d8-b370-1b6308329b17.png)
> 
> ### New dependencies
> 
> Already satisfied with Superset 2.0
> 
> ### Migration Plan and Compatibility
> 
> N/A
> 
> ### Rejected Alternatives
> 
> N/A
>

**Comment by rusackas** [comment]
@jileeon it sounds like this effort might not be needed any more, if I'm understanding the comments on your closed PRs. Is there any need/intent to carry this SIP forward and initiate a discussion and vote on the Apache mailing list?

**Comment by jileeon** [comment]
@rusackas, it is no longer needed. please close it. thanks.
