### ISSUE TITLE
[SIP-90] Provides filter bar visibility setting on embedded dashboards

### ISSUE THREAD

**Issue by jileeon** [apache/superset#21069]
### Motivation

Want to hide the native filter bar by default

### Proposed Change

Control filter bar visibility by using query parameters which already been implemented. See https://github.com/apache/superset/pull/18741

### New or Changed Public Interfaces

embedded-sdk supports them 

### New dependencies

N/A

### Migration Plan and Compatibility

N/A

### Rejected Alternatives

N/A

**Comment by ShaliniIruvuru** [comment]
We can hide the native filter bar visibility.It is working fine
Screenshot:-
![Screenshot from 2023-03-17 17-38-34](https://user-images.githubusercontent.com/115684419/225901343-5b818219-c203-41db-a826-497326c2526d.png)
Loom video:-
https://www.loom.com/share/20deea2ed40c4a728437bfa8430c6c2e

**Comment by rusackas** [comment]
I'll close this as it seems to be resolved by https://github.com/apache/superset/pull/21070/files

CC @michael-s-molina (who reviewed the PR) and @john-bodley as fellow SIP-steward, for context.

@jileeon let me know if there's more work to be done as part of this SIP, and we can re-open it and start the discussion/voting process.

Hat tip to @Vitor-Avila for making the PR/SIP association here :)
