### ISSUE TITLE
Total on Table Chart gets cut off on the Dashboard if the Chart is re-sized

### ISSUE THREAD

**Issue by rusackas** [apache/superset#21063]
The total count from an aggregated Table Chart gets cut off on the Dashboard, after re-sizing it.

#### How to reproduce the bug

1. Access Superset.
2. Create a **Table Chart** using the **Vehicle Sales** Dataset.
3. Set `product_line` on the **Dimensions**.
4. Set `SUM(price_each)` on the **Metrics**.
5. Enable **SHOW TOTALS**.
6. Click on **Create Chart**.
7. Access the **CUSTOMIZE** tab.
8. Change the `SUM(price_each)` D3 format to **Original value**.
9. Save the Chart and add it to a **new** Dashboard.
10. Edit the Dashboard, and decrease the Chart height so that a horizontal scroll bar appears.
11. Increase the height so that all rows are visible.
12. Save your changes

### Expected results

The **Total** number should display as expected.

### Actual results

The **Total** number is cut off
(will paste screenshot/video here - Github is being problematic here at the moment)

### Known Workarounds

Manually re-sizing the Chart so that the number is properly displayed _might_ fix the issue. Reports are mixed.

### Environment

(please complete the following information):

- browser type and version: Chrome (on PC)
- superset version: latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by reesercollins** [comment]
This seems to be solved by removing the `table-layout: fixed` from the "Total" wrapper element. Not sure what other problems doing this may cause, but I can't seem to see any at the moment.
