### ISSUE TITLE
ENABLE_JAVASCRIPT_CONTROLS is true in config.py/superset_config.py but does not work

### ISSUE THREAD

**Issue by MrTrakez** [apache/superset#21061]
I have set "ENABLE_JAVASCRIPT_CONTROLS" to true in config.py file and even added ENABLE_JAVASCRIPT_CONTROLS: True in superset_config.py and then restarted Superset Apache. However, it still shows that I can't use javascript and is still grayed out.

![image](https://user-images.githubusercontent.com/111070577/184160894-0c256ba8-2d37-4516-9423-df7bc8a90b7c.png)

**Comment by MyTruQs** [comment]
Same problem here, did you manage to solve it? @MrTrakez

**Comment by MrTrakez** [comment]
@MyTruQs just install the  apache superset version 1.3 and add the  ENABLE_JAVASCRIPT_CONTROLS: True as a Feature Flag in the superset_config.py

**Comment by MyTruQs** [comment]
how did you configure the flag? could you show please, @MrTrakez

**Comment by MrTrakez** [comment]
@MyTruQs
 FEATURE_FLAGS = {
    'ENABLE_JAVASCRIPT_CONTROLS': True
}
