### ISSUE TITLE
Color of the lines does not change in JAVASCRIPT DATA INTERCEPTOR 

### ISSUE THREAD

**Issue by MrTrakez** [apache/superset#21077]
Hello all,
I have a table with two columns. One column contains the hexcode for the color and the other one contains the geojson. I added the database in superset and wanted to change the color using javascript. Since I need multiple lines with different colors, I don't know what to do. 

Do you guys have a solution?
![Help](https://user-images.githubusercontent.com/111070577/184448321-dc2ee3ba-3fef-4fb9-bd77-677b57bb5886.png)

**Comment by HansalShah007** [comment]
@MrTrakez how did you manage to resolve this issue? Can you provide some details? Thanks.
