### ISSUE TITLE
SUPERSET_VERSION_RC might not be set and lead to failing tarball creation.

### ISSUE THREAD

**Issue by Joel-Haeberli** [apache/superset#21082]
#### How to reproduce the bug

1. Execute [SOURCE_DIR]/RELEASING/make_tarball.sh in an environment you never used before and the release ENV-Variables are not set.
```
./make_tarball.sh [VERSION] [RC] [PGP_KEY_NAME]
```
2. The script fails with 
```
gpg: can't open '/[YOUR_RELEASE_DIR]/svn/superset_dev/2.0.0rc2/apache-superset--source.tar.gz': No such file or directory
gpg: signing failed: No such file or directory
```

### Expected results

I expect the script to build the correct versioned tarball.

### Actual results

Tarball without the correct name leading to errors in the script which expects the name with the correct version.

#### Screenshots

see Point 2 in 'How to reproduce the bug'

### Environment

- Theoretically all environments.
- Versions of browsers etc. not relevant.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
@Joel-Haeberli we were checking in on that PR still, but is this still an issue at all as of Superset 3.x? We'll leave it open for now.

**Comment by rusackas** [comment]
Closing as stale. This issue is quite old, but if perchance you still face it, we can revisit/reopen as needed.
