### ISSUE TITLE
connect mysql 422

### ISSUE THREAD

**Issue by zhugw** [apache/superset#21092]
Python3.8 and superset version 1.1.0, why not support
```
mysql://{username}:{password}@{host}/{database}
```
but support
```
mysql+mysqlconnector://{username}:{password}@{host}/{database}
```

and use it in Python console is Ok
```
import sqlalchemy
engine = sqlalchemy.create_engine('mysql://{username}:{password}@{host}/{database}')
connection = engine.connect()
```
and it does not tell reason, just 422 status
```
POST /api/v1/database/test_connection HTTP/1.0" 422 
```

So why in superset UI does not support `mysql://` connection string?

**Comment by Yoann-tildev** [comment]
same for PostgreSQL

**Comment by zhugw** [comment]
There is such a problem when using `mysql+mysqlconnector://` , if column type  is `text`, in chart it would be displayed as `b'\xXX\xxx...'`.

**Comment by rusackas** [comment]
AFAIK, it does support `mysql://` URIs. This is likely fixed by now, or seems out of date if not. If you are still encountering this in current versions (3.x) please we can re-open this.
