### ISSUE TITLE
NULL does not get shown when grouping by a column

### ISSUE THREAD

**Issue by dimakern** [apache/superset#2110]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
"version": "0.15.4"

### Expected results
Note that by setting series limit to 0, we're able to get expected result, which includes num_candidate_type is NULL (0 on legend)
![screen shot 2017-02-03 at 12 06 15 pm](https://cloud.githubusercontent.com/assets/11357615/22606609/4bca705c-ea09-11e6-9ad0-83df101bd4cc.png)

### Actual results
Actual result does not include NULL values for num_candidates_type.  Looking at the query, there is an extra join added on num_candidates_type and as a result, when num_candidates_type IS NULL, those rows get dropped.

![screen shot 2017-02-03 at 12 09 12 pm](https://cloud.githubusercontent.com/assets/11357615/22606689/9c166764-ea09-11e6-9ab1-bbadbd7f155d.png)

### Steps to reproduce
1) for Group By, select a column that has NULL values
2) count(*) for metric
3) Select Line time series
4) Time Column should be one that contains string dates in the format "2017-01-01"
5) Select day as the Time Grain
6) Select some time range

@bkyryliuk FYI

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 443 days. Feel free to comment and request for this issue to be reopened.

**Comment by BartlomiejSkwira** [comment]
This is still a valid issue in November 2019. I did a pie chart and NULL values are not included in the chart.

**Comment by nipunn1313** [comment]
Hi - I've continued to notice this issue in Dec 2020. I made a line chart with a group-by and the NULL values aren't represented as data points. When I poke at the query created - I see this

```
SELECT "git_wrapper_version" AS "git_wrapper_version",
       date_trunc('day', CAST("day" AS TIMESTAMP)) AS "__timestamp",
       COUNT(*) AS "count"
FROM "default"."pal_git_wrapper_metrics"
WHERE "day" >= '2020-12-09'
  AND "day" < '2020-12-16'
GROUP BY "git_wrapper_version",
         date_trunc('day', CAST("day" AS TIMESTAMP))
ORDER BY "count" DESC
LIMIT 50000;
```

But I don't see a line in the resulting graph for when git_wrapper_version = NULL.

Note that the following slightly different query w/o a GROUPBY does show a line. The moment you add git_wrapper_version to the group-by the null line goes away.
```
SELECT date_trunc('day', CAST("day" AS TIMESTAMP)) AS "__timestamp",
       COUNT(*) AS "count"
FROM "default"."pal_git_wrapper_metrics"
WHERE "day" >= '2020-12-09'
  AND "day" < '2020-12-16'
  AND "git_wrapper_version" IS NULL
GROUP BY date_trunc('day', CAST("day" AS TIMESTAMP))
ORDER BY "count" DESC
LIMIT 50000;
```

**Comment by villebro** [comment]
@nipunn1313 please open a new ticket for this if you can confirm that it's still happening on `master` branch or the latest stable release (the original ticket is referring to version `0.15.4` which is very old).

**Comment by bkyryliuk** [comment]
It is still happening when grouped by 2 values and both of them are nulls, will try to find a way to repro on the example datasets

**Comment by junlincc** [comment]
@bkyryliuk would you mind opening a new ticket for this issue with details e.g. db and charts that are being affected. Thanks!
