### ISSUE TITLE
Helm: Global resources are not used in most containers

### ISSUE THREAD

**Issue by martimors** [apache/superset#21109]
#### How to reproduce the bug

1. Specify [resources](https://github.com/apache/superset/blob/master/helm/superset/values.yaml#L199) at the global scope in `values.yml`
2. `helm install`
3. Observe that the containers get default resources instead of the ones you specified

### Expected results

All containers, including jobs and init containers, should get the same resources unless overridden by their specific setting

### Actual results

Resources are heeded in the superset container and the worker container(s). In other pods it has no effect.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x ] I have reproduced the issue with at least the latest released version of superset.
- [ x ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Should be an easy fix, I don't mind taking a stab at it.

**Comment by rusackas** [comment]
Closing as stale. This issue is quite old, but if perchance you still face it, we can revisit/reopen as needed.
