### ISSUE TITLE
Time Series Chart Showing Only Year on Jan 1

### ISSUE THREAD

**Issue by hannahyhwang** [apache/superset#21103]
## Screenshot

<img width="1247" alt="Screen Shot 2022-08-16 at 9 20 36 AM" src="https://user-images.githubusercontent.com/97560511/184929573-8071a748-e94f-4056-a347-16afa95e6da2.png">
<img width="1246" alt="Screen Shot 2022-08-16 at 9 19 54 AM" src="https://user-images.githubusercontent.com/97560511/184929577-22517ec4-13b2-470e-8a27-f167a3ea8c48.png">

## Description

In the time series chart, I'm unsure why the chart doesn't display 2019-01-01 when it does for all other months. For January months, it only displays the year. 

## Design input
N/A

**Comment by cass-simplelegal** [comment]
Have you tried casting your timestamp column into a month-year (e.g., YYYY-MM) to see if that works?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
