### ISSUE TITLE
in chart original data converted to b'...'

### ISSUE THREAD

**Issue by zhugw** [apache/superset#21119]
version 1.4.1
below way to connect mysql (8.0.27)
```
mysql+mysqlconnector://{username}:{password}@{host}/{database}
```
when upload a csv to mysql, and to create chart with this data,
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/4953871/185294052-de5c2425-7012-41c0-9acf-8c2040100e09.png">

Why original data is converted to b'...'? how to fix it?

**Comment by rusackas** [comment]
This version of Superset is no longer supported. If anyone is still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
