### ISSUE TITLE
Helm: Default busybox init container does not reference `.Values.envFromSecrets`

### ISSUE THREAD

**Issue by martimors** [apache/superset#21110]
#### How to reproduce the bug

1. Specify a custom externally managed secret in `.Values.envFromSecrets`
2. `helm install`
3. Observe that the busybox container init scripts cannot find the env variable you wanted to give it

### Expected results

The secrets should be available here as in all other containers by default

### Actual results

In my case, the netcat call failed because the DB host could not be found

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

It could be a bit finnicky to do because the default script only exists in valyes.yml, thus using if/else would cause a circular dependency. It would therefore involve moving the default init container into `_helpers.tpl`. What do you think, is it worth the effort and complexity? I don't mind implementing it myself but would love some community feedback before I start.

**Comment by rusackas** [comment]
Closing as stale. This issue is quite old, but if perchance you still face it, we can revisit/reopen as needed.
