### ISSUE TITLE
Download report into excel and pdf  format with graph and data.

### ISSUE THREAD

**Issue by shafad1** [apache/superset#21134]
It will be good if we have this feature in superset.. which is the basic export options . its not good to tell to customers that we do not have this export option. 

is there any customiation to achieve this.. it would be fine if someone can help me on this

**Comment by mdeshmu** [comment]
There is an open PR for excel format https://github.com/apache/superset/pull/19810 and the contributor is willing to extend for pdf as well.

**Comment by shailendrasingh98** [comment]
Checkout the PR for PDF report [https://github.com/apache/superset/pull/23170](https://github.com/apache/superset/pull/23170)

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and is a feature request rather than a bug. If this is relevant in current versions (currently 3.x) please open a new Ideas discussion or a PR to address the problem (or help the current PRs across the finish line!)
