### ISSUE TITLE
How to present people in custom space using their x and y coordinates?

### ISSUE THREAD

**Issue by JovanBosic** [apache/superset#21137]
Hi,

I have file where I store timestamps, bounding box coordinates and person ID, I would like to make a heat map, where background would be a custom image, I would like to have a slider where I can change time, and present with scater plot or heat map where people are on that custom image. Is that possible?

**Comment by rusackas** [comment]
Hi there. Sorry this didn't get attention sooner. I can safely say that there's no stock visualization that meets these requirements. There is indeed a heatmap (but not with a customizable background. The only viz with a timerange slider are the ECharts timeseries charts (e.g. line/area). The Timeseries Scatter Plot also includes this "Data Zoom" checkbox, so I think that's about as lose as we're going to get here. Beyond that, I'd suggest opening an Ideas discussion for a feature request, or working to create a custom visualization type.
