### ISSUE TITLE
Timezone ignored when formatting

### ISSUE THREAD

**Issue by hosswald** [apache/superset#21149]
#### How to reproduce the bug

* Have a Druid Database with UTC timestamps in __time column
* Connect it to Superset
  * Add Engine Parameters: {"context":{"sqlTimeZone":"Europe/Berlin"}}

Two tests:
* Query __time column in SQL lab
* Create a table chart with only the __time column
  * Format with something like %Y-%m-%d %H:%M:%S

### Expected results
Formatted timestamps should be in the timezone configured via context.sqlTimeZone

### Actual results
SQLLab:
![image](https://user-images.githubusercontent.com/32925139/185933293-83dbc186-848b-4a83-a8e3-95de076bf8c9.png)

Chart:
![image](https://user-images.githubusercontent.com/32925139/185933375-55ca4976-c852-4684-9401-4d96e0099486.png)

### Environment

- browser type and version: Chrome 104.0.5112.82
- superset version: 2.0.0 via Helm Chart 0.7.1
- druid version: 0.23.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by hosswald** [comment]
Older versions of superset at least let me keep the unformated (ISO) timestamp (the one that can be seen in the SQLLab screenshot), but Superset now seems to automatically format time columns.

**Comment by hosswald** [comment]
Related: #6768/#19176, #3928

**Comment by rusackas** [comment]
Closing this since it's stale, is arguably a feature request rather than a bug, and because the relevant discussion seems to be happening over in  https://github.com/apache/superset/issues/6768
