### ISSUE TITLE
Increase Filter Limit in Apache Superset (1000 is too low)

### ISSUE THREAD

**Issue by progettoautomazione** [apache/superset#21166]
Hi, as per my understanding the Filter Chart Component will be soon deprecated so we have to use the Dashboard Native Filtering component. But in this component, for select boxes you apply a limit of 1.000 records max. That's too low, I mean, let's suppose I want a filter by Client: it's very common having more than 1.000 clients... Any way to change this parameter in order to increase it? Any workaround while you (hopefully) make this setting dynamic?

Thanks

**Comment by rusackas** [comment]
We might want to move this to an Ideas Discussion if we're to add configuration for this, or we would be happy to review a PR. Assigning to @geido and @michael-s-molina since they know their way around this component better than most :)

**Comment by michael-s-molina** [comment]
Hi @progettoautomazione. You can use the "Dynamically search all filter values" option in the filter configuration.

<img width="896" alt="Screenshot 2023-01-14 at 1 15 30 PM" src="https://user-images.githubusercontent.com/70410625/212488922-0e6a76cf-f866-423a-9e4a-e87ac94b495b.png">
