### ISSUE TITLE
The menu bar is accessible through the login screen using OAuth (Google)

### ISSUE THREAD

**Issue by bonamim** [apache/superset#21164]
After changing the **Apache Superset** to use the **OAuth (Google)** setting. The **menu bar** started to appear on the login screen ⚠️ 

#### How to reproduce the bug

1. We tried to use the steps described [**here**](https://superset.apache.org/docs/installation/running-on-kubernetes/#setting-up-oauth);
2. The config inside the Pod:
```
  config_oauth: |
    CSRF_ENABLED = True
    # This will make sure the redirect_uri is properly computed, even with SSL offloading
    ENABLE_PROXY_FIX = True

    from flask_appbuilder.security.manager import AUTH_OAUTH
    AUTH_TYPE = AUTH_OAUTH
    OAUTH_PROVIDERS = [
        {
            "name": "google",
            "icon": "fa-google",
            "token_key": "access_token",
            "remote_app": {
                "client_id": os.getenv("GOOGLE_KEY"),
                "client_secret": os.getenv("GOOGLE_SECRET"),
                "api_base_url": "https://www.googleapis.com/oauth2/v2/",
                "client_kwargs": {"scope": "email profile"},
                "request_token_url": None,
                "access_token_url": "https://accounts.google.com/o/oauth2/token",
                "authorize_url": "https://accounts.google.com/o/oauth2/auth",
                "authorize_params": {"hd": os.getenv("AUTH_DOMAIN", "")}
            },
        }
    ]

    # Map Authlib roles to superset roles
    AUTH_ROLE_ADMIN = 'Admin'
    AUTH_ROLE_PUBLIC = 'Gamma'

    # Will allow user self registration, allowing to create Flask users from Authorized User
    AUTH_USER_REGISTRATION = True

    # The default user self registration role
    AUTH_USER_REGISTRATION_ROLE = "Gamma"
```

### Expected results ✅ 

Login screen **without** available menu bar:

![image](https://user-images.githubusercontent.com/36086878/186178495-15b9de19-c377-47dc-88f3-4eabf8b5984a.png)

You **cannot** access the dashboard list even if you are not logged in:

![image](https://user-images.githubusercontent.com/36086878/186179200-f027fbd2-6149-448d-b7e2-195ddef7ad4e.png)

### Actual results ❌ 

Login screen **with** available menu bar:

![image](https://user-images.githubusercontent.com/36086878/186178308-06bc4706-1266-49d6-8a1b-9f3a0b22214d.png)

You **can** access the dashboard list even if you are not logged in:

![image](https://user-images.githubusercontent.com/36086878/186178767-43548d7f-ebe3-4859-b035-b105d6a619ec.png)

### Environment

- browser type and version: Chrome (Version 104.0.5112.101)
- superset version: `superset version` 2.0.0
- any feature flags active:
  - ENABLE_TEMPLATE_PROCESSING

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

- Helm Chart

**Comment by mrigbysmoove** [comment]
"AUTH_ROLE_PUBLIC = 'Gamma'" means that users not logged in have the Gamma role. if you want only authenticated users to have any access, you want that setting to just not be configured at all

**Comment by bonamim** [comment]
Thanks @mrigbysmoove 👍
