### ISSUE TITLE
Only owner and admin user are able to see drafts dashboards - no permission to grant access

### ISSUE THREAD

**Issue by wiktor2200** [apache/superset#21182]
Only owner and admin user are able to see drafts dashboards. I want create "almost Admin" user with access to everything except Database and Security configs, but being able to edit all dashboards.

#### How to reproduce the bug

1. When dashboard is not published it's not visible to non-admin users.

### Expected results

There should be permission to grant view on all dashboards (of all users) - published and drafts.

### Actual results

Only owner and admin user are able to see drafts dashboards.

### Environment

(please complete the following information):

- browser type and version: ALL
- superset version: `2.0.0`
- python version: `3.8`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by wiktor2200** [comment]
It could be related with this bug which I reported some time ago: https://github.com/apache/superset/issues/20913

**Comment by kamalkeshavani-aiinside** [comment]
This is expected behavior and not a bug. You can request this as a new feature by posting in Discussions and close this issue.

**Comment by wiktor2200** [comment]
But I think copied `Admin` role not getting the same permissions as original `Admin` is a bug.

**Comment by kamalkeshavani-aiinside** [comment]
> But I think copied Admin role not getting the same permissions as original Admin is a bug.

Then you can raise a new issue for that

**Comment by rearranged** [comment]
I agree with @wiktor2200  and also see it as a bug. I have the same use case by the way.

**Comment by rusackas** [comment]
This doesn't sound like it should be considered a bug, and is a pretty out of date report even so. If people are still encountering an issue in current versions (3.x) please open a new Issue or a PR to address the problem.
