### ISSUE TITLE
Unable to define the 'SameSite' for Global Async Query async-token cookie

### ISSUE THREAD

**Issue by rdubois** [apache/superset#21183]
For the session cookie, the Superset configuration allows to override the default behaviour and configure the SameSite option through the `SESSION_COOKIE_SAMESITE` variable.
That option is not available for the Global Async Token JWT cookie. The default value `None` is then considered.

### Environment

(please complete the following information):

- superset version: 1.5.1 / 2.0.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
@rdubois @ftom if [this](https://github.com/ftom/superset/commit/10ef046c22af9563995f0ae68473b34e268178b5) resolves this issue, would you mind opening a PR against Superset master?
