### ISSUE TITLE
Apache Superset 2.0.0 : Pivot V2 table download as pivootted option at Dashboard not available but available at chart level

### ISSUE THREAD

**Issue by manojrustagi79** [apache/superset#21192]
I have created a pivot table with Pivot V2. At chart level, it is showing an option to download data as pivotted csv. But when this pivot chart is placed on dashboard then this option to download the data as pivotted csv is not available. 

Python-3.8
Apache Superset 2.0.0

**Comment by Asta6406** [comment]
Hi @manojrustagi79, Although my versions of the problems differ from yours, I am also experiencing them.

Python = 3.7.10
Apache Superset = 1.4.0

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and is a feature request rather than a bug. This is still relevant to 3.0, but there are threads/issues discussing the feature elsewhere, so I'll close out this older thread. Prs welcome, if anyone wants to add this!
