### ISSUE TITLE
Correct URI format, superset cannot connect to Postgres database

### ISSUE THREAD

**Issue by LuozhuZhang** [apache/superset#21196]
I use [docker](https://superset.apache.org/docs/installation/installing-superset-using-docker-compose/) to start superset

Enter the `URI` according to the format of the [official document](https://superset.apache.org/docs/databases/postgres) (it can be connected locally, indicating that the URI format is correct) 👇

`postgresql://{username}:{password}@{host}:{port}/{database}`

After that I received an error notification, and I checked the console and found that I received a `422` error notification

<img width="667" alt="Screen Shot 2022-08-25 at 19 43 39" src="https://user-images.githubusercontent.com/70309026/186655619-d0e794db-16fc-4d57-bd5d-33b867297d01.png">

![image](https://user-images.githubusercontent.com/70309026/186655674-78842f8b-abb1-4071-a76a-abb4937fcd01.png)

---

I want to ask what is the reason for this, is there any related issue you can refer to?

I am used to using docker to start superset, does it have anything to do with this error?

**Comment by gideonn** [comment]
Check the stack trace in superset logs.

**Comment by LuozhuZhang** [comment]
![Uploading Screen Shot 2022-08-26 at 14.54.09.png…]()

Yes, I have checked active logs

> Check the stack trace in superset logs.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
