### ISSUE TITLE
password contains '@' , can not connect database. 

### ISSUE THREAD

**Issue by matianhe3** [apache/superset#21206]
docker-compose-non-dev 
![image](https://user-images.githubusercontent.com/24929062/186877529-b7eaf484-7683-4886-b11b-8d201752e3f8.png)

![image](https://user-images.githubusercontent.com/24929062/186877892-883767d5-1edd-46fd-a52c-a16b95620348.png)

i tried mysql, postgresql, mssql.
i change password , remove '@' , it connected.

only SQLAlchemy URI failed. UI connector successed.
![image](https://user-images.githubusercontent.com/24929062/186878412-3d51f9b5-1a20-4252-a181-88a7be2639fe.png)

**Comment by danielhass** [comment]
@matianhe3 have you tried to escape the `@` in the URI as described in the SQLAlchemy docs?

https://docs.sqlalchemy.org/en/14/core/engines.html#escaping-special-characters-such-as-signs-in-passwords

**Comment by matianhe3** [comment]
> @matianhe3 have you tried to escape the `@` in the URI as described in the SQLAlchemy docs?
> 
> https://docs.sqlalchemy.org/en/14/core/engines.html#escaping-special-characters-such-as-signs-in-passwords

i tried it , but same error.
