### ISSUE TITLE
duckdb  - unable to list the table schema

### ISSUE THREAD

**Issue by forestlzj** [apache/superset#21210]
After setting duckb connection to a local file,  in "SQL Editor",  it can show list of duckdb connecton and schema correctly, when select a duckdb schema, it can't show the table names in the "See Table schema" drop down box.  In superset oupt log, it shows error:

**Engine no attribute 'exec_driver_sql'**

### Environment

(please complete the following information):

- browser type and version: chrome 104.0.5112.102
- superset version: 2.0
- python version: 3.9.13
- duckdb version: 0.4.0
- duckdb-engine version: 0.6.2
- any feature flags active:

### Checklist

OS: Redhat 7.9

**Comment by forestlzj** [comment]
supplement: It can execute sql on duckb correctly but can't show table list and table schema

**Comment by forestlzj** [comment]
I think it can be fixed after this merge:  https://github.com/Mause/duckdb_engine/pull/393

**Comment by Mause** [comment]
@forestlzj are you able to try with the latest duckdb-engine version? (0.6.3)

**Comment by forestlzj** [comment]
@Mause  duckdb-engine version (0.6.3, 0.6.4) works now,  but it still needs to make some minor code change in duckdb_engine specs in superset to fix the said problem.  I will submit a PR in superset .
