### ISSUE TITLE
Chart table search box return unexpected results by some searching items

### ISSUE THREAD

**Issue by lubumu** [apache/superset#21214]
When "12" was give into a search box in a table chart. Records without containing "12" were listed.

#### How to reproduce the bug

1. Go to "World Bank's Data" dashboard 
2. Click on 'Most populared countries" menu 
3. Scroll down to 'Edit Chart'
4. Go to "Customize"
5. Check "SEARCH BOX"
6. Give "12" in "Search" input above the table 
7. Check results

### Expected results

Result contains only rows contains "12"

### Actual results

Part of the results do not contain string "12"

#### Screenshots

![image](https://user-images.githubusercontent.com/87641336/186925832-de9f12f6-14e0-467f-b23c-06288b568efc.png)

### Environment

(please complete the following information):

- Microsoft Edge Version 104.0.1293.70 (Official build) (x86_64)
- superset version: `1.4.2 - 2.0`
- python version: `3.8.9`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by Shazad-khan** [comment]
![image](https://user-images.githubusercontent.com/100838455/225599630-e71a48b0-daa7-4f99-9d04-ac6b83fedf25.png)

It is working as expected. So what it is doing is when we have a chart with large no like in billions or in millions it will search for the number in that and it will filter the chart.

Please recheck it and close the ticket
