### ISSUE TITLE
Authorization issue with user roles in embeddable dashboards

### ISSUE THREAD

**Issue by rickscolaro** [apache/superset#21211]
Hello, I'm working on a Vue.js project and I would like to embed some dashboards in my application.
For that reason, I decided to use the latest docker image apache/superset latest-dev 
To get it done, I followed the official tutorial on Superset's GitHub: https://github.com/apache/superset/tree/master/superset-embedded-sdk

The problem is:
For each user of my application, they're going to have a specific Role, and for each Role, it is going to have a specific list of Row Level Security.
I'm trying to use the endpoint "guest_token", binding the specific User created within superset. But everytime it returns me a user with a Public Role,
no matter the specific user who I Bound in the token, it always get ignored, showing the public role dashboard, and it is not what I'm looking for.

The Questions are:
Is there any way, by the guest_token, access these dashboards with users created within Superset with their List Roles and Row Level Security?
Am I going to the right way?
Has someone passed through this particular problem?

 Following my problem’s example, I have a logged and autheticated user called “richard”
![image](https://user-images.githubusercontent.com/88251175/186900757-0ec73e4b-d866-460f-8819-5f85b79f1668.png)

It has two Row Level Security Filter, “Rick” and “Rick2”, which are assigned to a role called “Wii Platform”
![image](https://user-images.githubusercontent.com/88251175/186901355-08dc3b47-3a9b-439f-9605-a4767b971900.png)

 
With these configurations, the filter can’t be applied, because it is logged with public role, and my role is Wii Platform 
![image](https://user-images.githubusercontent.com/88251175/186901455-62bc5b44-7226-4d7d-ab02-825699157e33.png)
![image](https://user-images.githubusercontent.com/88251175/186901503-d3ab265b-bef0-4a18-b052-d9c4a4a498ea.png)

 
But, if I add a Public role, the ‘Wii Platform” role filter is applied
![image](https://user-images.githubusercontent.com/88251175/186901610-0e595881-85da-4b4f-8da0-a06e4ba7a1a4.png)
![image](https://user-images.githubusercontent.com/88251175/186901640-978e8ed4-be06-45bd-a373-84c1c6ee9a33.png)

**Comment by baffonso** [comment]
Having the same issue.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!

I'd also encourage you to hit up the `#embedded` channel on [Superset Slack](http://bit.ly/join-superset-slack) for help, too, or take advantage of GitHub Discussions.
