### ISSUE TITLE
Superset not get loaded properly in local environment

### ISSUE THREAD

**Issue by mtv2102** [apache/superset#21230]
I just cloned the code from git and tried running with the following command but it shows the url in the attached way,
docker-compose up
![Screenshot 2022-08-25 at 2 28 08 PM](https://user-images.githubusercontent.com/112002949/187149346-4ec1eef8-22bb-4875-bec9-e6465cd036bb.png)

But when I tried with the following commands in prod env. It is working ,
docker-compose -f docker-compose-non-dev.yml pull
docker-compose -f docker-compose-non-dev.yml up

At the same time with the docker-compose.yml file, when I tried comment the following highlighted line ,it works.But I am sure that will not be the right fix.
![Screenshot 2022-08-29 at 3 19 26 PM](https://user-images.githubusercontent.com/112002949/187150031-08903028-8ab4-4f80-bff6-d3743ac7d271.png)

I tried by increasing docker size from 6 to 8GB..Does it require an additional storage? Any help would be appreciated....

**Comment by mtv2102** [comment]
I tried the above changes, but it still remains the same.

Steps I tried,
1.Change the code in RightMenu.tsx (as per your last commit)
2.docker-compose down -v
3.docker-compose up

**Comment by sinhashubham95** [comment]
@mtv2102 the commands you tried won't use the local files, for this can you try running a dev-server and try again.
`cd superset-frontend && npm install && npm run dev-server`.

**Comment by mtv2102** [comment]
Yeah Great, It works now...Thank you for the help...And I am recently started working on integration with Kepler, are you aware of any implementations that has been done so far...?

**Comment by sinhashubham95** [comment]
You mean the plugin of deck-gl?

**Comment by mathianandhan21** [comment]
> You mean the plugin of deck-gl?

@sinhashubham95  Yeah, but I am not sure whether there is plugin support for that in the superset.

**Comment by mtv2102** [comment]
> You mean the plugin of deck-gl?
@sinhashubham95 yeah

**Comment by mtv2102** [comment]
worked
