### ISSUE TITLE
Typos on france.geojson in country map legacy plugin

### ISSUE THREAD

**Issue by tberriot** [apache/superset#21233]
## Screenshot

![image](https://user-images.githubusercontent.com/14890945/187169005-9b9677e1-6050-4898-b266-b720bf8a726c.png)

![image](https://user-images.githubusercontent.com/14890945/187169050-bd06a91a-5a33-4c6c-8d54-be1e367754df.png)

## Description

Two typos :
- line 22 : "Haute-Rhin" is "Haut-Rhin"
- line 99 : Seien-et-Marne" is "Seine-et-Marne"

**Comment by xavier-GitHub76** [comment]
Hello,
I updated the names.
A pull-request is created (https://github.com/apache/superset/pull/22999)

**Comment by rusackas** [comment]
This is likely fixed now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
