### ISSUE TITLE
Trying to open dashboards, but it crashes after a few seconds.

### ISSUE THREAD

**Issue by Kishorerh1993** [apache/superset#21231]
Hi,

While trying to open dashboards, it crashes after a certain point of time(15 Second). This happens only for certain tabs in the dashboard, not for all.
Adding a video for reference.

https://user-images.githubusercontent.com/33930513/187161844-7d7d45c5-b6c7-4556-9735-2b37c17bdab8.mov

Superset Version: `1.4.0`
Python Version: `3.7.9`

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
