### ISSUE TITLE
Bug with SQL Lab : DB engine Error

### ISSUE THREAD

**Issue by maliklamblin** [apache/superset#21235]
Hello all,

I have a problem since a few days, I have this error as soon as I want to launch a query in SQL Lab or even just view a table :
'Data could not be retrieved from the results backend. You need to re-run the original query.'

![image](https://user-images.githubusercontent.com/106805975/187191320-7ed451e6-8c72-4cc1-a35a-0ac18e5029eb.png)

Do you have any idea what it might be due to? I feel like I haven't changed anything though.

I should point out that the error occurs absolutely all the time, and with all databases that are on superset.

**Comment by mishamsk** [comment]
Have the same issue. Version 2.0.0. I am suspecting that this is happening after I restored a backup. Surprisingly it doesn't affect anything else: charts, dashboard and scheduled reports all work.

**Comment by ShaliniIruvuru** [comment]
It is not a bug.I didn’t  get DB engine error in Version 2.1.0 .But After launched the query i need to re run the query to see the results.

Loom video:-
https://www.loom.com/share/340f58920eea44bfb1bbb2339361533c

**Comment by zhujian0805** [comment]
has this been fixed? @mishamsk

**Comment by mishamsk** [comment]
@zhujian0805 afaik no, but I haven't upgraded beyond 2.0.1, so not sure about the latest release

**Comment by zhujian0805** [comment]
I see this on 2.1.0 now :(

**Comment by ShaliniIruvuru** [comment]
Hi,Can you Please confirm is it fixed or not?

**Comment by zhujian0805** [comment]
I still see this in the docker image with version 2.1.0

**Comment by ShaliniIruvuru** [comment]
Hi, Can you provide detail information with the steps required to reproduce the same which you are facing.

**Comment by zhujian0805** [comment]
Actually it's hard to reproduce, i just click the "RUN" button few times and i will get chance to see the error. is it because cache expired?

**Comment by zhujian0805** [comment]
I could have found the issue, here are the findings:
1. I used local file system cache, now i have changed to REDIS cache
```
+# Config RESULTS_BACKEND
+RESULTS_BACKEND = RedisCache(
+      host=REDIS_HOST,
+      key_prefix='superset_results'
+)

```
2. another thing to notice is that i have 3 superset hosts running behind a loadbalancer, each were using local file system cache, so once i changed to use my redis cache results backend, it works fine.

**Comment by ShaliniIruvuru** [comment]
Since you feel the issue is resolved, can you please close the issue?

**Comment by ShaliniIruvuru** [comment]
Since you feel the issue is resolved, can you please close the issue?

**Comment by zhujian0805** [comment]
I'm fine to close. i'm not the guy created the issue. would ask if @maliklamblin is ok with closing. :)

**Comment by ShaliniIruvuru** [comment]
Hi @maliklamblin ,It is working fine.can you please recheck it and close the issue
