### ISSUE TITLE
Examples DB is always created, even for a `import-directory` CLI function

### ISSUE THREAD

**Issue by rdubois** [apache/superset#21256]
The Superset CLI `import-directory` function, behind the scene, reuse the `ImportExamplesCommand`. In that [commit](https://github.com/apache/superset/commit/62d8ab7f9c044e2887de794484c30c2108213e0b), the `ImportExamplesCommand` systematically creates the Examples DB.
It doesn't make sense in the case a user used the `import-directory` command in order to create the objects they provided in the command argument. In that case, the user expects their resources to be created, but nothing else.

#### How to reproduce the bug

1. Run the command `superset import-directory [PATH]`
2. See that the `examples` database has been created, in addition to those that are part of the configs passed to the command

### Expected results

Only the configs passed to the command should have been considered, and created.

### Actual results

The `examples` database is created

#### Screenshots

![image](https://user-images.githubusercontent.com/1133383/187450895-724bdf53-f559-494f-bd96-53ad7adbc9d1.png)

### Environment

(please complete the following information):

- superset version: 1.5.1 and 2.0.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rdubois** [comment]
In order to fix that issue, would it be acceptable to make it simple, and add a parameter to the `ImportExamplesCommand`, named `need_examples_database`, `False` by default, and then, conditionally create the database.
The command would set the boolean to True in the `load_examples_from_configs` method, and keep the default False value in the `load_configs_from_directory` folder ?

**Comment by rusackas** [comment]
Looks like this should have been closed with the merged PRs. Holler if I'm mistaken!
