### ISSUE TITLE
Missing application context in the `import_directory` CLI function

### ISSUE THREAD

**Issue by rdubois** [apache/superset#21254]
When running the `import-directory` CLI function, an error occurs. The application context is missing to execute the underlying function:

```
No application found. Either work inside a view function or push an application context
```

It looks like the issue has been introduced when [the CLI file has been split into different fragments](https://github.com/apache/superset/commit/9e2bc72fb9687eb1d4563fd02853fea6b94a978d). The `@with_appcontext` decorator was there before the refactoring. It's no longer there after.

#### How to reproduce the bug

1. Connect to a Superset node
2. Run the `superset import-directory` command
3. See error

### Expected results

The command should run successfuly

### Actual results

Error:

```
No application found. Either work inside a view function or push an application context
```

### Environment

(please complete the following information):

- superset version: 1.5.1 / 2.0.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by Shazad-khan** [comment]
I have alredy tested and its working as expected. It has already been fixed. Please recheck the issue and close if alredy fixed
