### ISSUE TITLE
Can't remove "Day" option from time grain.

### ISSUE THREAD

**Issue by frassinier** [apache/superset#21268]
If you try to override the superset configuration, 
When you change the `TIME_GRAIN_DENYLIST` values, 
By adding `P1D`, in order to exclude the `Day` option,
You will still see `P1D`, as the default value, for TIME GRAIN select.

#### How to reproduce the bug

1. Edit your `superset_config.py` and add `TIME_GRAIN_DENYLIST = ["P1D"]`
2. Reload superset server
3. Create a new chart
4. See Time grain select having "P1D" default value 

### Expected results

The expected behavior can be to either:
1. Have no default value `Select...`
2. Have the first value selected by default, `Original value` 
3. Have a way to specify the default value from the config file

### Actual results

For now, this value is hardcoded. 
Whatever if it's added to the denylist, you will see `P1D` default value.

https://github.com/apache/superset/blob/622304205058d31b34a6590f4c0d652421730464/superset-frontend/packages/superset-ui-chart-controls/src/shared-controls/index.tsx#L315

#### Screenshots

<img width="289" alt="image" src="https://user-images.githubusercontent.com/18534166/187689166-591d9bae-40c7-473a-addf-ea41263720bd.png">

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by ShaliniIruvuru** [comment]
Working as Expected.We can able to remove Day option from the time grain. 

But this field when we add  from superset  in config.py file not in superset_config.py file.

1.Without adding  TIME_GRAIN_DENYLIST = ["P1D"] field in config.py
blob:https://zemoso.atlassian.net/24cfa8fd-a96c-45d8-8d83-412b2a3cc54b#media-blob-url=true&id=44c91b8a-cfa2-4035-999a-55082b9e2a10&collection=&contextId=50483&height=1080&width=1920&alt=
2.After adding TIME_GRAIN_DENYLIST = ["P1D"] field in config.py
![image](https://user-images.githubusercontent.com/115684419/225851207-98e5a517-59b8-42c0-b4f8-c9ea7921c5b7.png)

**Comment by frassinier** [comment]
Seems to be fixed indeed, thanks @ShaliniIruvuru
