### ISSUE TITLE
Dataset creating issues in SQL Lab

### ISSUE THREAD

**Issue by EugeneTorap** [apache/superset#21271]
I found 2 interesting bugs when we want to create a dataset in SQL Lab:

1. When we create a dataset and provide some name and then want to do it again with the same name. In second dataset creation we got `Untitled Query 7 08/31/2022 17:58:02` name but input has `qwe1` name
2. [FIXED] When we reload page and create a duplicate name of dataset for example name=`qwe1` then modal window is disappeared and don't handle error from server.

### Expected results

We handle server error response and show "Dataset [qwe1] already exists" on UI side to user.

### Actual results

Server error response is not handled.

#### Screenshots

https://user-images.githubusercontent.com/29536522/187712014-c11971cb-1634-4287-a540-163eba57b83a.mov

https://user-images.githubusercontent.com/29536522/187713956-c98bf383-b42f-49b4-b82e-5684272f4a7a.mov

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

@michael-s-molina @kgabryje @villebro @lyndsiWilliams

**Comment by kgabryje** [comment]
@yousoph Should this get prioritized?

**Comment by EugeneTorap** [comment]
@diegomedina248 Can you take a look at these issues?

**Comment by yousoph** [comment]
I believe https://github.com/apache/superset/pull/21244 fixes #2 issue mentioned

**Comment by yousoph** [comment]
For the first issue - looks like it happens if you use the same tab to try to save the dataset. If you refresh the SQL Lab tab, the error message appears properly. I think the modal shouldn't keep the previous name when it's closed and reopened - I think that might fix the problem? Would you be up to opening a PR for a fix @EugeneTorap ? (Thanks for the find, btw!)

**Comment by EugeneTorap** [comment]
> I believe #21244 fixes the second issue mentioned

Yes, I check it out the second issue. It's fixed after this merged PR

**Comment by EugeneTorap** [comment]
@AAfghahi Can you take a look at first issue?

**Comment by AAfghahi** [comment]
@EugeneTorap sure i can look into it.
