### ISSUE TITLE
Datewise filter in dashboard for time based charts

### ISSUE THREAD

**Issue by snehlata08** [apache/superset#21288]
In grafana there is filter option automatically provided to filter out data based on the date and time in the dashboard which is currently not available in superset. 
![image](https://user-images.githubusercontent.com/79985986/187887747-c63cb825-9d7c-4586-8289-3a9f45bc7736.png)

So it would be great if such feature is implemented in superset beacuse datewise filter is always needed. And i know we can create a filter box and add it but that is like a 2 step thing, if we can get it automatically then it would be great.

**Comment by mayurnewase** [comment]
there is time range filter in native filter for this.
