### ISSUE TITLE
hide preselected native filter

### ISSUE THREAD

**Issue by zufolo441** [apache/superset#21290]
Hi everyone,

I'd need to prefilter some dashboards. 
in older versions I used to pass parameters by url: &preselect_filters={"465":{"idambito":["3Hmux"]}}
this filter chart was placed in an hidden tab, so the user couldn't (easily) change it.

in newer versions, with native filters, I use the very complex syntax 
native_filters=(NATIVE_FILTER-:(__cache:(label:'',validateStatus:!f,value:!('')),extraFormData:(filters:!((col:,op:IN,val:!('')))),filterState:(label:'',validateStatus:!f,value:!('')),id:NATIVE_FILTER-,ownState:()))
and it works.
Is there a way to hide or lock filter, so the user cannot change this value?

**Comment by goto-loop** [comment]
As a workaround, you could enable [Jinja Templating](https://superset.apache.org/docs/installation/sql-templating/), pass a custom parameter with the URL and process it in the charts' SQL queries (e.g. with a `WHERE` statement). This way the data would get filtered without a filter element appearing on the dashboard.

**Comment by zufolo441** [comment]
Thanks, I already use this mechanism, but in some dashboard I have to let author set filters before publishing.

**Comment by rusackas** [comment]
Currently there is not such a feature. It seems perfectly reasonable to add a "hidden" checkbox in the filter editor to this effect, which could hide it's rendering through React or CSS. Prs welcome, but I'm closing this since it's a feature request rather than a bug :D
