### ISSUE TITLE
Deck.gl chart tooltips do not work properly

### ISSUE THREAD

**Issue by thegoldenhop** [apache/superset#21301]
#### How to reproduce the bug

1. Go to charts
2. Open a deck.gl scatterplot chart. (example: deck.gl demo scatterplot)
3. hover over points

### Expected results

Each points tooltip should have different tooltip values.

### Actual results

The majority of points on the map will have the exact same values.

#### Screenshots
![screenshot1](https://user-images.githubusercontent.com/112657983/187994985-1b823035-12f1-4a3d-9d70-f9fac2d7e858.png)
![screenshot2](https://user-images.githubusercontent.com/112657983/187995040-59c51bd7-5e7a-4645-9756-cdb8f123b4b5.png)

### Environment

- Google chrome Version 104.0.5112.101 (Official Build) (64-bit)
- superset version: recent pull from master branch
- python version: 3.8.10
- node.js version: 16.17.0

**Comment by Shazad-khan** [comment]
![image](https://user-images.githubusercontent.com/100838455/226317765-bfd63b0c-d072-4260-90d0-b75d4322d311.png)
![image](https://user-images.githubusercontent.com/100838455/226317835-698be0f2-fb03-4d4f-9d05-e2f32b319fc1.png)

Deck gl maps all the different points have different locations please recheck the issue and close if fixed

**Comment by rusackas** [comment]
Same result here, seems to be working as expected.
