### ISSUE TITLE
Gauge chart shows incorrect interval colors when using minimum value

### ISSUE THREAD

**Issue by goto-loop** [apache/superset#21328]
When using the Gauge chart, it is possible to define interval bounds and interval colors, e.g. for marking a range of "good" values. It is also possible to set minimum and maximum values to define the left and right boundaries of the Gauge.

When interval bounds and colors are in place and then a min value is set, the position of the interval color boundary does not change.

#### How to reproduce the bug

1. Create a new Gauge chart, e.g. with exported_stats example dataset
2. Select AVG(daily_members_posting_messages) as Metric
3. On Customize tab, set INTERVAL BOUNDS to 10, 16.53 and INTERVAL COLORS to 3, 6
4. Set MIN to 8
5. Observe how the boundary between green and red does not move when MIN is updated

### Expected results

The color boundary should move to a new position depending on the value of MIN.

### Actual results

The color boundary stays where it was when MIN was 0.

#### Screenshots

Without MIN value set:
![Screenshot_20220905_115353](https://user-images.githubusercontent.com/102797966/188432966-77427f69-be0e-4305-8a4e-9df0bfec62f3.png)

With MIN value set:
![Screenshot_20220905_115410](https://user-images.githubusercontent.com/102797966/188432960-3416a06b-9f20-4583-8426-35fb0ae98e16.png)

### Environment

- browser type and version: Firefox 104.0.1
- superset version: 2.0.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [N/A] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by Shazad-khan** [comment]
![image](https://user-images.githubusercontent.com/100838455/226290162-5ed562b5-65f6-486f-b03a-7986a0e036ac.png)

I have checked it. It is working as expected please recheck the issue and close if resolved

**Comment by goto-loop** [comment]
Correct me if I'm wrong, but your screenshot seems to confirm the issue I've described: You've defined an interval bound at value 10, but the green and red sections of the gauge meet around 13.12

**Comment by Shazad-khan** [comment]
![image](https://user-images.githubusercontent.com/100838455/226577932-5972c6f9-75d9-4ee2-a3d9-2c00104fe665.png)

I got your point and tried once again and you can see this time its working as you are expecting.

**Comment by rusackas** [comment]
@goto-loop is this still an issue in Superset 3.x? I presume so, but thought I should ask.

**Comment by goto-loop** [comment]
@rusackas Yes, I've just tried it with Superset 3.1.0 and the issue is still the same.

**Comment by rusackas** [comment]
Thanks for the validation, @goto-loop. If anyone reading this thread wants to open a PR, a fix would be much appreciated. While a legit bug, it's not likely to become a high priority for the core committers anytime soon.

**Comment by goto-loop** [comment]
It actually doesn't look too complicated, I'm working on it and should be able to submit a PR soon.
