### ISSUE TITLE
APACHE SUPERSET CHANGE FILTER VALUE ORDER

### ISSUE THREAD

**Issue by MrTrakez** [apache/superset#21340]
The order of these values in the Age filter is not quite right. I want the value "6 - 13" to be below "0 - 5". Is there any way to set that in Apache Superset?

![image](https://user-images.githubusercontent.com/111070577/188601299-57161576-cd0b-45f2-b8dd-d10be1bcffde.png)

**Comment by mayurnewase** [comment]
they are treated like strings and sorted accordingly, don't think its possible to find integers in the string then sort.
also this should be a feature request in the discussions.
