### ISSUE TITLE
Virtual Dataset becoming Physical after a while

### ISSUE THREAD

**Issue by Vicinius** [apache/superset#21345]
Whenever I create a Virtual Dataset from "Explore" button, after running a query on SQL Lab > SQL Editor, I start to work on charts on top of it, and at some point, my virtual Dataset becomes Physical, and for some reason this breaks all my previous work. The flow I've been doing is creating a table chart, then a bar chart (I have created a metric on this bar chart, a COUNT(DISTINCT X)... and then it breaks everything when I try to run or save my bar chart. And I get the error after running it: 

```
Unexpected error
Error: (1142, "SELECT command denied to user '' for table ''")
```

#### How to reproduce the bug

1. Go to SQL Lab into SQL Editor
2. Query something from a schema/table
3. Save it as a **Virtual** Dataset using the "Explore" Button on SQL Editor
4. On top of it, create a table chart 
5. Then, create a bar chart and some metrics on it
6. It should turn the dataset into physical

### Expected results

Do not turn my dataset into physical

### Actual results

It does turn it into a physical one

#### Screenshots

![image](https://user-images.githubusercontent.com/59844324/188724087-9b44d5fb-ad02-4a3c-9671-ff821d3a18cf.png)
After becoming Physical

### Environment

- browser type and version: Chrome 105.0.5195.102
- superset version: Sadly I don't know for sure, because I don't have acess to the actual server running my superset at the moment
- python version: Same as above
- node.js version: Same as above
- any feature flags active: none

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

First time opening a bug here. Couldn't check logs of reproduce with the latest version because I really can't acess it.

**Comment by mayurnewase** [comment]
couldn't repro on current master.
