### ISSUE TITLE
superset-sdk / embedDashboard / dashboardUiConfig

### ISSUE THREAD

**Issue by YangtzeQi** [apache/superset#21354]
#### How to reproduce the bug
After the dashboard is embedded in the React app, the Dashboard duiconfig is set 
`dashboardUiConfig: {
        hideTitle: true,
        hideChartControls: true,
        hideTab: true,
  }, `
  
### Expected results

user can not click to edit chart

### Actual results

can do this by clicking on the title

#### Screenshots
<img width="389" alt="image" src="https://user-images.githubusercontent.com/99391585/188830056-210bf5cc-2443-466e-860b-cdcffe7e9d17.png">

**Comment by rusackas** [comment]
I _think_ this has been address, so I'll close this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
