### ISSUE TITLE
Tree chart: Add option to sort nodes by ID or NAME column

### ISSUE THREAD

**Issue by goto-loop** [apache/superset#21405]
## Description

The nodes of the Tree Chart visualization are currently arranged based on an unknown principle and it's not possible to customize their order.

## Screenshots

![Screenshot_20220909_080916](https://user-images.githubusercontent.com/102797966/189283412-efc52201-e0a2-4ba0-a96e-bd278d03d3f1.png) ![Screenshot_20220909_080220](https://user-images.githubusercontent.com/102797966/189283452-b70fccfa-612d-4eb0-9361-257b3ed51bba.png)

![Screenshot_20220909_080802](https://user-images.githubusercontent.com/102797966/189283566-13415bc7-011b-4adc-8646-d56a74735000.png) ![Screenshot_20220909_080830](https://user-images.githubusercontent.com/102797966/189283581-67e962b5-d1f3-4548-b38f-2d123f28b166.png)

## Design input

It would be great to have an option to sort the nodes either by the ID or the NAME column. There are several use cases where the order of the nodes does matter, for example you would want to see:
- Location A
- Location B
- Location C

... instead of:
- Location C
- Location A
- Location B

Similarly you would want to have:
- Humidity (sensor 1)
- Humidity (sensor 2)
- Temperature (sensor 1)
- Temperature (sensor 2)

... instead of:
- Humidity (sensor 2)
- Temperature (sensor 1)
- Humidity (sensor 1)
- Temperature (sensor 2)

**Comment by mayurnewase** [comment]
don't think echarts provide this option.

**Comment by mayurnewase** [comment]
this should be a feature request in discussion.
