### ISSUE TITLE
CSV export doesn't include timeshifted data

### ISSUE THREAD

**Issue by pradhangn** [apache/superset#21408]
#### How to reproduce the bug

Build any line chart with any time-shift comparison. Export a CSV.

### Expected results

All data shown on chart must be exported.

### Actual results

The timeshifted data (like say 1 week ago) is not exported into the CSV

#### Screenshots

![new-chart-2022-09-09T07-39-59 334Z](https://user-images.githubusercontent.com/40589807/189298347-77a6874b-0638-4784-85d7-e2ab6c8f743e.jpg)

### Environment

- browser type and version: Chrome
- superset version: 2.0.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [N] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [Y ] I have reproduced the issue with at least the latest released version of superset.
- [Y] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

This hinders the user experience a lot because if they like a chart and want to take out the data, they now have to modify the chart before exporting a CSV.

**Comment by mayurnewase** [comment]
I created echart's time-series line chart with 1 year time shift on "video games sales" with this config in master.

![Screenshot from 2022-09-17 07-15-42](https://user-images.githubusercontent.com/12967587/190835757-00f1570e-81f1-4a68-ab61-65d34a791748.png)

can see exact data in csv as in results pane at the bottom.

**Comment by pradhangn** [comment]
Thanks for checking on this @mayurnewase. Looks like the legacy 'Line chart' shows the behaviour I had captured but the e-charts ones are fine.

I think we can close this as the legacy line chart is on its way out.
