### ISSUE TITLE
Charts reinserted into dashboards they were deleted from after save(overwrite)

### ISSUE THREAD

**Issue by C-monC** [apache/superset#21434]
Hi,

Reproduction steps:
Dashboard A and dashboard B had chart A in.
Delete chart A from dashboard B.
Modify chart A and save(overwrite)
Chart A then reappears in dashboard B.

I can see there is a link to dashboard B in the columns query_context and params:
`....,"conditional_formatting":[],"extra_form_data":{},"dashboards":[11,42],"force":false,"result_format":"json......`
Dashboard B has id 11 and Dashboard A has id 42.

The dashboard column does not include the chart A anywhere. Searched for the id in its json columns.

A workaround is just recreating the chart and not inserting into dashboard B. 
This is a major security concern because there's no indication it happened. I need to manually review dashboards to look for data leakage.

**Comment by C-monC** [comment]
This also blocks saving if the dashboard does not exist - Response "Dashboard does not exist".

**Comment by codyml** [comment]
I think this was fixed in https://github.com/apache/superset/pull/21497.  Let me know if you can still reproduce!

**Comment by C-monC** [comment]
This was fixed, thanks.
