### ISSUE TITLE
Couldn't downlaod csv in given location

### ISSUE THREAD

**Issue by mtv2102** [apache/superset#21437]
I tried downloading csv file of the chart(table format) in the local location, when I debug the code it gets into the exportChart function inside explore/exploreUtils/index.js and when it reaches the final line , the output is in the form of payload response such as,
{datasource: {…}, force: true, queries: Array(1), form_data: {…}, result_format: 'csv', …}
datasource: {id: 2, type: 'table'}
force: true
form_data: {datasource: '2__table', viz_type: 'table', slice_id: undefined, cache_timeout: undefined, url_params: undefined, …}
queries: [{…}]
result_format: "csv"
result_type: "full"
[[Prototype]]: Object

I expanded the output and checked, but there were only the table name and id in the place of datasource, I coulnd't understand whether how to download that datasource as a csv file in local location ?

**Comment by mayurnewase** [comment]
not reproducible on master, I am able to download csv of table chart.
if you could provide superset version, chart version someone will be able to help.

**Comment by mtv2102** [comment]
> not reproducible on master, I am able to download csv of table chart. if you could provide superset version, chart version someone will be able to help.

@mayurnewase Did you able to download by editing the code and giving the location manually (making it to download inside certain folder) ? Because when I tried changing the code, as it is a react some article mentioned that it is not possible to give the location explicitly in client side

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
