### ISSUE TITLE
[SIP-89] Proposal for adding latin america countries to country map

### ISSUE THREAD

**Issue by bryanjtc** [apache/superset#21440]
*Please make sure you are familiar with the SIP process documented*
(here)[https://github.com/apache/superset/issues/5602]. The SIP number should be the next number after the latest SIP listed [here](https://github.com/apache/superset/issues?q=is%3Aissue+label%3Asip).

### Motivation

I'm working on a project where I need to visualise data from latin america countries, but there a lot of countries missing from the country map.

### Proposed Change

I propose to add the following countries: argentina, bolivia, chile, colombia, costa rica, cuba, dominican republic, ecuador, el salvador, guatemala, haiti, honduras, nicaragua, panama, paraguay, puerto rico, saint barthelemy, saint martin and venezuela by using the guide detailed in this [documentation](https://superset.apache.org/docs/miscellaneous/country-map-tools/#adding-a-new-country).

### New or Changed Public Interfaces

19 new countries are going to be added to the country map visualization tool

### New dependencies

None

### Migration Plan and Compatibility

None

### Rejected Alternatives

None

**Comment by betodealmeida** [comment]
We probably don't need a SIP for this, I think it's just an extension of an existing feature. :)

**Comment by bryanjtc** [comment]
@betodealmeida Should I close this and open a feature request issue? I already made a pr, I just need someone to review it.

**Comment by betodealmeida** [comment]
> @betodealmeida Should I close this and open a new discussion? I already made a pr, I just need someone to review it. 

Yeah, we can close and I can review the PR for you.

**Comment by rusackas** [comment]
Dropping a link to the PR [here](https://github.com/apache/superset/pull/21352). I added @betodealmeida as a reviewer there (and a couple others for good measure).

Agreed, we can close this issue, and move on with development. Thank you for raising our awareness and for your contributions, @bryanjtc!
