### ISSUE TITLE
Helm: deploy websocket for the benefit of query async feature

### ISSUE THREAD

**Issue by benjaminrene** [apache/superset#21457]
I would like to be able to deploy superset-websocket to benefit of async query over the whole superset-ui with Helm chart.

In this feature, we are focused on helm chart to deploy superset-websocket service with Helm. Requires #21373 to be resolved (PR #21379)

**Comment by rusackas** [comment]
Closing, since https://github.com/apache/superset/pull/21806 was merged. Holler if there are further issues to address.
