### ISSUE TITLE
The feature flags list is not up to date

### ISSUE THREAD

**Issue by bonamim** [apache/superset#21467]
Supposedly we should find the `DRILL_TO_DETAIL` flag available in this list:

https://github.com/apache/superset/blob/2.0.0/RESOURCES/FEATURE_FLAGS.md

#### How to reproduce the bug

1. Go to: https://github.com/apache/superset/blob/2.0.0/RESOURCES/FEATURE_FLAGS.md

### Expected results

The `DRILL_TO_DETAIL` flag should be in one of these classifications:

- In Development
- In Testing
- Stable
- Deprecated Flags

### Actual results

I can't find the flag.

### Environment

- superset version: superset version 2.0.0

### Additional context

I would like to know if this feature flag can be used in production environment.

**Comment by rusackas** [comment]
Also, a CC to @eric-briscoe since this is relevant to some organizing you were doing last week ;)

**Comment by rusackas** [comment]
Opened [a PR](https://github.com/apache/superset/pull/21474) with this and all the others that are apparently missing
