### ISSUE TITLE
always return with this error. ["There was an error loading the tables"]

### ISSUE THREAD

**Issue by TrendTech** [apache/superset#21476]
![image](https://user-images.githubusercontent.com/48197920/190302852-e6ce7aa1-6134-49f4-90b5-15b6a47b2afc.png)
![image](https://user-images.githubusercontent.com/48197920/190303353-ddf09ae8-6a71-4afa-beff-3a48efc7d000.png)

1. i follow the install instruction
2. i add a mysql database.
3. when i try to visit the tables. it bring this error. i try old version. still the same
4. what i miss in my install process?

**Comment by novice-gamer** [comment]
I also have this problem

**Comment by novice-gamer** [comment]
I also encountered this problem

**Comment by GeorgeSpring** [comment]
I also encountered this problem

**Comment by mAd-DaWg** [comment]
Same issue here. It lists the tables fine, but when trying to select a table this error occurs. I noticed that its putting /undefined/false on the end of the request url. when removing it, it seems to load fine.

werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[15/Sep/2022:10:40:18 +0000] "GET /superset/tables/4/exampletable/undefined/false/ HTTP/1.1" 404 334 "[http://0.0.0.0:8088/tablemodelview/list/?pageIndex=0&sortColumn=changed_on_delta_humanized&sortOrder=desc"](http://0.0.0.0:8088/tablemodelview/list/?pageIndex=0&sortColumn=changed_on_delta_humanized&sortOrder=desc%22) "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"

**Comment by bumasl** [comment]
same error marks me, someone could already solve the error?

![image](https://user-images.githubusercontent.com/20816899/190440647-2c2380e9-285d-4167-95cb-eab96ae73344.png)

**Comment by C-monC** [comment]
Same issue, huge block currently

**Comment by andrearoota** [comment]
Same issue

**Comment by garystafford** [comment]
Same issue with latest tag (3ed6d3e979351616cd5474b2404e136604d74cf50e4eeaf2e5a74f6f8a32130a)

**Comment by C-monC** [comment]
If you use superset in production and want to track the fix https://github.com/apache/superset/pull/21470

**Comment by bumasl** [comment]
Can someone explain me the detailed steps to solve this problem?
I thank you for your kind attention

**Comment by C-monC** [comment]
Pulling the latest version should work.
Make sure to clear cache.

**Comment by bumasl** [comment]
Thank you very much for your prompt response, I did the next step.
1 - delete container
docker-compose -f docker-compose-non-dev.yml down -v
2- Start the container again
docker-compose -f docker-compose-non-dev.yml up

I keep getting the same error, am I doing something wrong?

**Comment by C-monC** [comment]
Try with docker-compose.yml - it should work.

**Comment by sjmillius** [comment]
I'm still seeing this issue in our setup on Google cloud.
We're using Postgres proxy to Cloud SQL, Redis and depoly via helm using apache/superset:latest.

It still produces the error in sqllab: [There was an error loading the tables] as described here.
How can this be resolved?
