### ISSUE TITLE
apache-superset 0.0.0.dev0 requires sqlalchemy!=1.3.21

### ISSUE THREAD

**Issue by hehetown** [apache/superset#21503]
#### How to reproduce the bug
# pip install clickhouse-sqlalchemy
ERROR:
Collecting clickhouse-sqlalchemy
  Downloading clickhouse-sqlalchemy-0.2.2.tar.gz (35 kB)
Collecting sqlalchemy<1.5,>=1.4
  Downloading SQLAlchemy-1.4.41-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 20 kB/s
Requirement already satisfied: requests in /usr/local/lib/python3.8/site-packages (from clickhouse-sqlalchemy) (2.26.0)
Collecting clickhouse-driver>=0.1.2
  Downloading clickhouse_driver-0.2.4-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (732 kB)
     |████████████████████████████████| 732 kB 24 kB/s
Requirement already satisfied: pytz in /usr/local/lib/python3.8/site-packages (from clickhouse-driver>=0.1.2->clickhouse-sqlalchemy) (2021.1)
Collecting tzlocal
  Downloading tzlocal-4.2-py3-none-any.whl (19 kB)
Collecting greenlet!=0.4.17
  Downloading greenlet-1.1.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (157 kB)
     |████████████████████████████████| 157 kB 28 kB/s
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.8/site-packages (from requests->clickhouse-sqlalchemy) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/site-packages (from requests->clickhouse-sqlalchemy) (3.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/site-packages (from requests->clickhouse-sqlalchemy) (1.26.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/site-packages (from requests->clickhouse-sqlalchemy) (2021.5.30)
Collecting pytz-deprecation-shim
  Downloading pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
Collecting backports.zoneinfo
  Downloading backports.zoneinfo-0.2.1-cp38-cp38-manylinux1_x86_64.whl (74 kB)
     |████████████████████████████████| 74 kB 72 kB/s
Collecting tzdata
  Downloading tzdata-2022.2-py2.py3-none-any.whl (336 kB)
     |████████████████████████████████| 336 kB 59 kB/s
Building wheels for collected packages: clickhouse-sqlalchemy
  Building wheel for clickhouse-sqlalchemy (setup.py) ... done
  Created wheel for clickhouse-sqlalchemy: filename=clickhouse_sqlalchemy-0.2.2-py3-none-any.whl size=46945 sha256=b3e81a6ffaee6df786eebaba7274211aa1d703def2d4a8c401791e360c476fa4
  Stored in directory: /root/.cache/pip/wheels/fb/39/b2/82f886ce2e5df1ed5e28230890c6f28bac9faac69e429f399f
Successfully built clickhouse-sqlalchemy
Installing collected packages: tzdata, backports.zoneinfo, pytz-deprecation-shim, tzlocal, greenlet, sqlalchemy, clickhouse-driver, clickhouse-sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 1.3.24
    Uninstalling SQLAlchemy-1.3.24:
      Successfully uninstalled SQLAlchemy-1.3.24
**ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flask-appbuilder 3.4.1 requires SQLAlchemy<1.4.0, but you have sqlalchemy 1.4.41 which is incompatible.
apache-superset 0.0.0.dev0 requires sqlalchemy!=1.3.21,<1.4,>=1.3.16, but you have sqlalchemy 1.4.41 which is incompatible.**
Successfully installed backports.zoneinfo-0.2.1 clickhouse-driver-0.2.4 clickhouse-sqlalchemy-0.2.2 greenlet-1.1.3 pytz-deprecation-shim-0.1.0.post0 sqlalchemy-1.4.41 tzdata-2022.2 tzlocal-4.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour withthe system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 21.2.4; however, version 22.2.2 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.

**Comment by genzgd** [comment]
clickhouse-sqlalchemy 0.2.2 requires SqlAlchemy 1.4, while Superset up to 2.0.0 requires SQLAlchemy 1.3.  I believe the latest Superset development version now supports SqlAlchemy 1.4, so one approach is to pull the latest Superset Github or docker version.

You can also try pinning clickhouse-sqlalchemy to 0.2.0 or 0.2.1.

Finally please consider https://github.com/ClickHouse/clickhouse-connect for Superset with ClickHouse, especially if you want HTTP compatibility (proxy/VPN friendly).  Full disclosure, I'm the primary author.

**Comment by rusackas** [comment]
Since we're now on 3.1, on the verge of 4.0, we're not supporting 2.x  or prior versions actively. If anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)
