### ISSUE TITLE
Unable to see roles in drop down in edit dashboard

### ISSUE THREAD

**Issue by ankesh1705** [apache/superset#21538]
We have defined  few roles as per department but we can't see list of roles in the dropdown after superset upgrade to 2.0
![super_set_roles](https://user-images.githubusercontent.com/6988476/191502782-8d665794-f6d1-473b-bdd5-9fa7ef042b1e.png)

**Comment by mayurnewase** [comment]
regression from : https://github.com/apache/superset/pull/20837

**Comment by ankesh1705** [comment]
Still not able to figure out.  There is no inactive users, Still roles are not reflecting in dropdown in edit dashboard

**Comment by mayurnewase** [comment]
yeah thats the problem with using bleeding edge version of any app, for prod better stick to LTS.
