### ISSUE TITLE
Predictive Analytics (Prophet) forecast not affected by changing time grain in Dashboard filter

### ISSUE THREAD

**Issue by goto-loop** [apache/superset#21548]
When using the Predictive Analytics feature found in different time-series charts, the options TIME GRAIN and FORECAST PERIODS control the forecast granularity and the number of forecasted datapoints, respectively. For example:
- TIME GRAIN = Day, FORECAST PERIODS = 10 &rarr; forecast the next 10 days
- TIME GRAIN = Week, FORECAST PERIODS = 3 &rarr; forecast the next 3 weeks

When adding a chart with Predictive Analytics to a dashboard, TIME GRAIN can be controlled through a dashboard filter. However, when the value is changed on the dashboard level, the option is ignored by the forecast.

#### How to reproduce the bug

1. Create new Time-series Line Chart with new_members_daily dataset.
2. Under METRICS, select AVG(new_members).
3. Open Predictive Analytics section, check ENABLE FORECAST.
4. Click CREATE CHART and save it.
5. Create new dashboard, add chart created above, save.
6. Add new filter of type Time grain, save.
7. Select Month and hit APPLY FILTERS.
8. Look at the length of the prediction: The distance between forecasted datapoints is still a day, not a month.

### Expected results

The selected time grain gets applied to the Prophet forecast in the chart.

### Actual results

The forecast is performed using the same time grain the chart has been saved with.

#### Screenshots

TIME GRAIN = Month set on Chart level – this is the expected result.
![Screenshot_20220922_134018](https://user-images.githubusercontent.com/102797966/191738304-ce775c77-9d74-4847-a567-1dfdfd9c2475.png)

TIME GRAIN = Month set on Dashboard level – the actual result. As above, the forecast contains 10 values, but the distance between them is one day, not one month.
![Screenshot_20220922_133919](https://user-images.githubusercontent.com/102797966/191738307-d72920e5-94e3-4fd6-ab97-75b080184d16.png)

### Environment

- browser type and version: Firefox 105.0
- superset version: 2.0.0
- python version: 3.9.13
- node.js version: 16.16.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by Cmagno13** [comment]
Goodnight!
I also have this error when generating the forecast
![01](https://user-images.githubusercontent.com/97127080/195237918-66b05345-dc2b-4c76-8b6a-7fa7f4e1e6c9.png)
![02](https://user-images.githubusercontent.com/97127080/195238014-0cbe8fbf-ed90-4aa3-b705-9ecf4e39c4d3.png)

**Comment by Cmagno13** [comment]
Environment
browser type and version: Firefox 105.0.3 (64-bits)
superset version: 2.0.0
python version: 3.9.2
node.js version: 16.16.0

**Comment by koterin** [comment]
Same issue with "No results were returned" in 2.0.0 ver

**Comment by Zebedeu** [comment]
Same issue

**Comment by rbgav-gmm** [comment]
Same issue

**Comment by sevaroy** [comment]
Same issue

**Comment by rusackas** [comment]
Hi there, and sorry this has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale. If it is still an issue in Superset 3.x (which it may well be!), we can re-open this - just let us know. Or, feel free to open a new issue with updated context. As always, PRs are welcome from anyone to fix the issue if it still exists.
