### ISSUE TITLE
Docker overlay2 consuming lot of storage

### ISSUE THREAD

**Issue by Hammad-Raza** [apache/superset#21540]
I am running superset since 1 year now and after every month we need to increase storage of server.
The app directly contains lot of core.* files that is consuming space.
Any pointers how to fix it or it is intended behavior of superset.

<img width="923" alt="Screen Shot 2022-09-21 at 7 56 44 PM" src="https://user-images.githubusercontent.com/15028724/191553334-252da0f4-7f83-435d-a44b-c50f5eb1838e.png">

<img width="237" alt="Screen Shot 2022-09-21 at 8 01 23 PM" src="https://user-images.githubusercontent.com/15028724/191554055-8af38679-ab40-4f3f-9339-edb0b0054511.png">

Superset Version 1.1

[docker-compose.yml.zip](https://github.com/apache/superset/files/9618362/docker-compose.yml.zip)

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
