### ISSUE TITLE
Cannot display embedded dashboard if blocking cookies 

### ISSUE THREAD

**Issue by frassinier** [apache/superset#21556]
Using the default behavior of Firefox or [Brave](https://brave.com/fr/), which blocks all cookies for security reasons, the iframe will not render at all.

#### How to reproduce the bug

1. Go to any website which has an embedded dashboard
2. Wait for the dashboard to load
3. See a generic unexpected error

### Expected results

I expect to see the iframe renders without cookies.

### Actual results

Depending on the web browser, you can either read:
- `Unexpected error: SupersetApiError: The operation is insecure.`
- `Unexpected error: SupersetApiError: An attempt was made to break through the security policy of the user agent.`

#### Screenshots

<img width="1675" alt="image" src="https://user-images.githubusercontent.com/18534166/191831879-c79a9b13-6c44-45ae-b2c9-388be5971e7b.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/18534166/191831928-ad48f4c9-afcc-4086-88fb-7b1314da2afb.png">

### Environment

(please complete the following information):

- browser type and version: Firefox 105 or Brave 1.43.93

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by frassinier** [comment]
Already fixed by #20019

**Comment by abh006** [comment]
From which release is this fix available?
