### ISSUE TITLE
Unnecessary queries when interacting with the menus

### ISSUE THREAD

**Issue by michael-s-molina** [apache/superset#21569]
#### How to reproduce the bug
https://user-images.githubusercontent.com/70410625/191964851-73da9581-d80b-4ca9-b620-a66a09f75f15.mov

@rusackas @yousoph 

### Expected results
Queries are fired only when necessary.

### Actual results
Queries are fired on every interaction.

### Environment

master

### Checklist
- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Seems like this is fixed! Closing
