### ISSUE TITLE
Not possible to email a raw csv via "Alerts and Reports"

### ISSUE THREAD

**Issue by binome74** [apache/superset#21568]
The Old Reports feature allowed us to send raw CSV files. The new "Alerts and Reports" feature operates only with postprocessed data and it breaks some use cases. While for some charts like Pivoted Table using postprocessed data is OK, there are many plain tables (Table) that we just want to see in a raw format (and email them). We can manually export raw data using the "Export to .CSV format" button, but there is no way to email the same csv file using "Alerts and Reports" which looks like a now broken feature Superset used to have.

#### How to reproduce the bug

1. Create some chart of "Table" type and fill it with 1000+ rows.
2. Create a report with Message content set as chart, send as csv, Notification method email
3. Schedule the report to send in the next 5 minutes.
4. Receive the email and review the attached csv file.

### Expected results
Raw untouched csv data as returned by database

### Actual results
There is an extra unnamed column which seems to be filled with row_number() function call results used by superset for pagination. The formats of some columns are chhanged, e.g. boolean columns are capitalized (true -> True).

### Environment
- browser type and version: Google chrome macOs Version 105.0.5195.125 (Official Build) (x86_64)
- superset version: `superset version` apache-superset==1.5.1
- python version: `python --version`  3.8
- node.js version: `node -v` bash: node: command not found
- any feature flags active: 'ENABLE_TEMPLATE_PROCESSING': True, 'ALERT_REPORTS': True

### Checklist
Make sure to follow these steps before submitting your issue - thank you!
- [ X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by bnitesh** [comment]
I also observe the same, on Superset 2.0. @binome74 you can check reproduced with latest released version 

Also if we add the row total to table chart, it generates 2 CSVs (1 for table data and 1 for totals row) for export but while generating a csv report for the same chart, it tries to combine into 1 csv and introduces many special characters rendering the CSV unreadable by most number editors like Excel, Numbers, etc.

**Comment by eschutho** [comment]
cc @yousoph

**Comment by Antonio-RiveroMartnez** [comment]
I was able to reproduce it. We are going to triage it. Thanks @binome74

**Comment by rusackas** [comment]
If I'm understanding correctly, we can close this in favor of https://github.com/apache/superset/issues/22981. Correct me if I'm mistaken, and we can re-open.
