### ISSUE TITLE
Line chart with several dimensions in view

### ISSUE THREAD

**Issue by stasDomb** [apache/superset#21574]
Hi All. I try to migrate from Tableau to Superset. And everything looks fine, except one type of chart which I couldn't create in Superset. I'm talking about a chart which splitted to a several pieces, and the number of pieces is the diversity of some of the dimensions. For instance:
<img width="1498" alt="Screenshot 2022-09-24 at 11 35 01" src="https://user-images.githubusercontent.com/27229336/192088802-b369f4c4-4a69-4993-8e10-4454421e36da.png">

So,  we can see 7 pieces with graphs regarding to the number of filter_id and in the each area I have another dimension and can see the diversity  of this dimension inside each area.

In the Superset's plugins I see some types but there are not so flexible and convenient. For instance (Time Series Table and Horizon):
<img width="1072" alt="Screenshot 2022-09-24 at 11 41 44" src="https://user-images.githubusercontent.com/27229336/192089116-d1daa97d-7bfd-4dd1-bfa6-fb2bc166394a.png">
<img width="1061" alt="Screenshot 2022-09-24 at 11 43 32" src="https://user-images.githubusercontent.com/27229336/192089121-13f05f0f-f575-4dc5-bfe1-b606dc538fd1.png">

Could you please help me? Maybe I missed something which I could use.
What do you think?
Thanks

**Comment by joshuaclausen** [comment]
I'm looking for the same thing.  Have you found any ways achieve something like this?

**Comment by stasDomb** [comment]
> I'm looking for the same thing. Have you found any ways achieve something like this?

Unfortunately, no. I'm so surprised that this visualisation type is missing in Superset

**Comment by rusackas** [comment]
You're not the only one to wish for such things, but this is more of a feature request than a bug. We're open to proposals and PRs to enhance the product. Meanwhile, closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. Thanks!
