### ISSUE TITLE
Mixed Time-Series Chart: Missing data when toggle "Stack Series" on Query options

### ISSUE THREAD

**Issue by abifauzann** [apache/superset#21597]
I have created Mixed Time-Series Chart with Bar Chart (in Query A) and Line Chart (in Query B). When I toggle `Stack Series` option in Query A, the data in Bar chart is not fully updated, which will cause several data is missing in query A. When the `Stack Series` option is not checked in Query A, we can see the data is rendered as expected.

#### How to reproduce the bug

1. Access superset
2. Create Mixed Time-Series Chart with Public Sales Dataset
3. Run query as I attach below
4. Set Chart type in Query A to Bar Chart
5. Set Chart type in Query B to Line Chart
6. Toggle "Stack Series" checkbox option in Query A in order to stack several country data

### Expected results

It should render stacking country data when we toggle "Stack Series" option in Bar Chart (Query A).

Query A: 
```
SELECT DATE_TRUNC(`order_date`, MONTH) AS `__timestamp`,
       `country` AS `country`,
       sum(`sales`) AS `GMV`
FROM
  (SELECT *
   FROM db.publiccleaned_sales_data) AS `virtual_table`
GROUP BY `country`,
         `__timestamp`
ORDER BY GMV DESC
LIMIT 10000;
```

Query B:
```
SELECT DATE_TRUNC(`order_date`, MONTH) AS `__timestamp`,
       sum(`quantity_ordered`) AS `Total_Qty_a2b26`
FROM
  (SELECT *
   FROM db.publiccleaned_sales_data) AS `virtual_table`
GROUP BY `__timestamp`
ORDER BY Total_Qty_a2b26 DESC
LIMIT 10000;
```

### Actual results

There are missing country data when toggle "Stack Series" in Bar Chart (Query A).

#### Screenshots

**Before toggle "Stack Series" option in Query A:**
<img width="1030" alt="Screen Shot 2022-09-27 at 14 44 05" src="https://user-images.githubusercontent.com/110159065/192465127-18fc120c-b661-4345-a891-c2dd8d5222ed.png">

**After toggle "Stack Series" option in Query A:**
<img width="1040" alt="Screen Shot 2022-09-27 at 14 41 45" src="https://user-images.githubusercontent.com/110159065/192465177-69abdc94-f4de-46b5-80b4-651509653068.png">

### Environment

(please complete the following information):

- browser type and version: Google Chrome Version 105.0.5195.125 (Official Build) (x86_64)
- superset version: `2.0.0`
- python version: `Python 3.8.9`
- node.js version: `node 16`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sfirke** [comment]
I wonder if this will fix it: https://github.com/apache/superset/pull/21450  Could you try this on the latest dev to see?  That PR and associated bugs are focused on filters with mixed charts, yours isn't about filters but seems close.

**Comment by abifauzann** [comment]
I've tried to apply this fix #21450 but the issue still remains the same. I think my issue is close to the toggling "Stack Series" option in Bar Chart and I didn't apply any filtering on Query A or B.

**Comment by doornot** [comment]
couldn't reproduce in my local environment (last master branch commit sha: 28c7636c591f39547f1201ff02da822e4a1bdf88)

<img width="1156" alt="截屏2022-10-21 下午2 40 31" src="https://user-images.githubusercontent.com/10323102/197129917-d1c07a50-896c-4213-a857-91ad51f4a6d0.png">


Query A
```sql
SELECT DATETIME(order_date, 'start of month') AS __timestamp,
       country AS country,
       sum(sales) AS "SUM(sales)"
FROM cleaned_sales_data
GROUP BY country,
         DATETIME(order_date, 'start of month')
ORDER BY "SUM(sales)" DESC
LIMIT 10000
OFFSET 0;
```

Query B
```sql
SELECT DATETIME(order_date, 'start of month') AS __timestamp,
       sum(quantity_ordered) AS "SUM(quantity_ordered)"
FROM cleaned_sales_data
GROUP BY DATETIME(order_date, 'start of month')
ORDER BY "SUM(quantity_ordered)" DESC
LIMIT 10000
OFFSET 0;
```

**Comment by ShaliniIruvuru** [comment]
Working as Expected.

Screenshots:

1.Without selecting the Stack Series checkbox
![image](https://user-images.githubusercontent.com/115684419/235114473-310834ac-b7b0-4be2-be42-e103a171db3a.png)

2.With Selecting Stack Series Check box.
![image](https://user-images.githubusercontent.com/115684419/235114602-cc433188-2b8d-4d46-b14b-b02572ee600d.png)
