### ISSUE TITLE
Allow sqlalchemy URIs longer than 1024

### ISSUE THREAD

**Issue by epa095** [apache/superset#21590]
#### How to reproduce the bug

Try to add a a sqlalchemy URI with more than 1024 characters, and one gets an error:
`{"message":{"sqlalchemy_uri":["Length must be between 1 and 1024."]}}`

### Why would anyone need more than 1024 characters in the URI?
I want to use databricks SQL. It accepts both PAT and Azure AD tokens. The Azure AD tokens are actually JWT tokens, and are roughly 1200 characters long. And the way to provide the token is to put it as part of the URI.

### Environment
- superset version: 2.0
- python version: 3.8

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by chanyou0311** [comment]
I had same problem.
I got around it by defining the `DB_CONNECTION_MUTATOR` function to override password in url.

**Comment by rusackas** [comment]
I was about to close this as stale, but it sounds like a loose thread. Do we (a) need a docs entry about the `DB_CONNECTION_MUTATOR` approach, (b) need a more systemic way to handle this (e.g. URI length limit increase), or (c) not worry about it and close this as stale?

CC @betodealmeida @dpgaspar for input if warranted.

**Comment by rusackas** [comment]
Closing this as stale, since it seems no further action is being taken here. If anyone wants to improve the docs, we'd welcome a PR, or you can just give me a little snippet/statement here and I'll open the PR myself :)
