### ISSUE TITLE
Dashboards with instant filtering showing stale results 

### ISSUE THREAD

**Issue by zhaorui2022** [apache/superset#21607]
Dashboards with instant filters sometimes show stale results after the filters have been changed. 

#### How to reproduce the bug

Note: This bug might need a big dataset to reproduce. I have tried a few example datasets but they seem too small to reproduce the issue.

1. Create a dashboard with a filter box, and make sure the filter box has instant filtering checked and it allows to select multiple values
2. Add any chart in the same dashboard and make sure the filter does change the result of the other chart (Big number is easier to observe)
3. Select a value from the filter box
4. Select another value from the filter box. 
5. Remove the value selected from step 4.
6. Repeating step 4 and 5. Eventually the chart added in step 2 shows the results without the filter value selected from step4, even though that filter value is selected.

### Expected results

Dashboard showing results showing results reflecting current filters.

### Actual results

Dashboard showing stale results not reflecting the current filters.

#### Screenshots

We have screenshots with bigger dataset, however, the data is confidential and I can't share it here.

### Environment

(please complete the following information):

- browser type and version: Chrome Version 105.0.5195.125 (Not browser specific)
- superset version: Superset 2.0.0
- python version: 3.8
- node.js version: not specific to node.js version
- any feature flags active: N/A

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zhaorui2022** [comment]
By the way, we can reproduce this in our production environment with presto as the query engine.

**Comment by rusackas** [comment]
Pinging @kgabryje @michael-s-molina @stephenLYZ in case they happen to have any insights here.

**Comment by ShaliniIruvuru** [comment]
Working as expected.

Screenshots

1.without giving the filter values
![image](https://user-images.githubusercontent.com/115684419/225546086-932ff1ed-cf99-4821-a5c4-00efd5de7761.png)
2.After add the filter value
![image](https://user-images.githubusercontent.com/115684419/225546260-91935f7d-c2e8-41fa-a631-542d130e922d.png)
3.Add another value from filter
![image](https://user-images.githubusercontent.com/115684419/225546386-8bf95aeb-8375-447c-98f5-3c8632b0b5d3.png)
4.remove the filter value recently added
![image](https://user-images.githubusercontent.com/115684419/225546528-8d084d06-4bb2-4dd0-9d49-c58e4608f1f1.png)

**Comment by rusackas** [comment]
Hopefully, based on the above comment, this is likely fixed by now. It is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue, a PR to address the problem, or at least give us updated context so we can re-open and reproduce this Issue.
