### ISSUE TITLE
display databases more than role real has

### ISSUE THREAD

**Issue by zhugw** [apache/superset#21600]
superset version 1.4.1
SQLALCHEMY URI
```
mysql+mysqlconnector://superset:XXXXXXXXXX@192.168.0.8/smart_auth
```
has specified the database: `smart_auth`
and then create a role with only this permission

<img width="670" alt="image" src="https://user-images.githubusercontent.com/4953871/192511327-8795d954-fa5c-4b49-84ec-966ab5cc56e5.png">

but when user assigned this role login, it could see many databases  

<img width="407" alt="image" src="https://user-images.githubusercontent.com/4953871/192511708-66b4b9d6-dff9-474f-a8ba-44b01cdf86e3.png">

not only could see these additional databases, but also could query data from tables of these databases

how to let it only see `smart_auth` database only?

**Comment by mayurnewase** [comment]
couldn't repro on latest master (last sha: 8f74e46d45ca94f5656f7b881f1096c16657c829)
I gave below permissions, 

![Screenshot from 2022-10-14 07-41-18](https://user-images.githubusercontent.com/12967587/195746127-eeb77f89-7232-4ad9-8657-03950bb4396e.png)


and can see only that db in sqllab, and only tables in that db.
![Screenshot from 2022-10-14 07-41-38](https://user-images.githubusercontent.com/12967587/195746158-de9e20b2-f421-4d56-95f1-7b8f48a6362a.png)

also when providing reproduction steps, please give all other details like all permissions set on that role to be able to query in sqllab.
