### ISSUE TITLE
Permissions for Filters and FilterSets don't works.

### ISSUE THREAD

**Issue by Always-prog** [apache/superset#21606]
Permissions for Filters and FilterSets don't works as well.

#### How to reproduce the bug

1. Enable DASHBOARD_RBAC in Feature flags.
2. Go to Users list
3. Create a new user, and assign to him the Gamma role
4. Check that _can edit FilterSets_, _can list FilterSets_ and other permissions for Superset is added.
5. Go to any dashboard, edit properties, and add Gamma role to Roles list.
4. Login as that new user
5. Go to dashboard and see problem, user can't see/add/delete Filters or FilterSets.

### Expected results

User can change Filters and FiltersSet if him have a permissions for this in himself role.

### Actual results

User can't see Filters and FiltersSet, because him isn't owner of dashboard.

#### Screenshots

Here's Gamma role permissions. It contains permissions to Filters.
![image](https://user-images.githubusercontent.com/66589759/192612036-6494643e-d9e0-433c-bf4b-2e2bafa2dd5e.png)

Here's screenshot of what user with permissions for adding/deleting Filters see. It can't delete or change anything.
![image](https://user-images.githubusercontent.com/66589759/192612545-fcd89312-31ce-4e80-9859-6261048e1775.png)

### Environment

(please complete the following information):

- Docker-non-dev.
- any feature flags active: DASHBOARD_RBAC

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mayurnewase** [comment]
DASHBOARD_RBAC is for giving readonly access, if you wan't gamma user to be able to add/edit new native filters you can add that user as a owner and add `can_write` on that role.
Feel free to reopen if that doesn't work.

**Comment by itziarmj** [comment]
Then, is it necessary to give the user write permission to the dashboard so that the filtersets work?

**Comment by Gokul2023-work** [comment]
Is there any way to make this work without adding that user as an owner to the dashboard. 

I am facing the same issue and in my case the dashboard is embedded into my react application. The dashboard is designed to be used by customers of the app. So if every user can create their own filter sets, that would be great. Currently when I am trying to achieve this, I am getting 403 forbidden error. Also I cannot add every single user as owner to the dashboard. I have tried giving every single permission available for gamma role in superset and that does not seem to work.

**Comment by jyamihaylova** [comment]
I use superset 2.1.1 and it still does not work. I gave the user all the permissions mentioned above (+gamma role), and still he is unable to see/add FilterSets.

**Comment by pa-mc** [comment]
@Always-prog This is my bare minimum permissions sets for a user to have readonly access to a dashboard. The user can interact and filter on the dashboard. 

![Screenshot 2023-11-21 at 18 16 24](https://github.com/apache/superset/assets/98042349/71ebd47e-c3ac-433a-a30a-90ce2c21333c)
