### ISSUE TITLE
connect apache iceberg  hive error: TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=['*org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: RuntimeException java.lang.ClassNotFoundException: org.apache.iceberg.mr.hive.HiveIcebergInputFormat:28:27',

### ISSUE THREAD

**Issue by penggewudi** [apache/superset#21618]
## Description

Hello, I have a problem when I use SUPERSET to connect to iceberg. I only use hive to connect, and I can see the required database and table, but when I want to view the data, he appears I have the following question, I don't know how to deal with this, I hope I can answer it, thank you
![image](https://user-images.githubusercontent.com/34574151/192740306-f53bf511-7e3f-411a-a411-48eae3cbac2c.png)

hive error: TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=['*org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: RuntimeException java.lang.ClassNotFoundException: org.apache.iceberg.mr.hive.HiveIcebergInputFormat:28:27', 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:335', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:199', 'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:260', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:247', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:541', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementAsync:HiveSessionImpl.java:527', 'sun.reflect.GeneratedMethodAccessor79:invoke::-1', 'sun.reflect.DelegatingMethodAccessorImpl:invoke:DelegatingMethodAccessorImpl.java:43', 'java.lang.reflect.Method:invoke:Method.java:498', 'org.apache.hive.service.cli.session.HiveSessionProxy:invoke:HiveSessionProxy.java:78', 'org.apache.hive.service.cli.session.HiveSessionProxy:access$000:HiveSessionProxy.java:36', 'org.apache.hive.service.cli.session.HiveSessionProxy$1:run:HiveSessionProxy.java:63', 'java.security.AccessController:doPrivileged:AccessController.java:-2', 'javax.security.auth.Subject:doAs:Subject.java:422', 'org.apache.hadoop.security.UserGroupInformation:doAs:UserGroupInformation.java:1762', 'org.apache.hive.service.cli.session.HiveSessionProxy:invoke:HiveSessionProxy.java:59', 'com.sun.proxy.$Proxy37:executeStatementAsync::-1', 'org.apache.hive.service.cli.CLIService:executeStatementAsync:CLIService.java:312', 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:562', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1557', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1542', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286', 'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1149', 'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:624', 'java.lang.Thread:run:Thread.java:750', '*java.lang.RuntimeException:java.lang.ClassNotFoundException: org.apache.iceberg.mr.hive.HiveIcebergInputFormat:39:12', 'org.apache.hadoop.hive.ql.metadata.Table:getInputFormatClass:Table.java:324', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:getMetaData:SemanticAnalyzer.java:2191', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:getMetaData:SemanticAnalyzer.java:2075', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genResolvedParseTree:SemanticAnalyzer.java:12033', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:analyzeInternal:SemanticAnalyzer.java:12129', 'org.apache.hadoop.hive.ql.parse.CalcitePlanner:analyzeInternal:CalcitePlanner.java:330', 'org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer:analyze:BaseSemanticAnalyzer.java:285', 'org.apache.hadoop.hive.ql.Driver:compile:Driver.java:659', 'org.apache.hadoop.hive.ql.Driver:compileInternal:Driver.java:1826', 'org.apache.hadoop.hive.ql.Driver:compileAndRespond:Driver.java:1773', 'org.apache.hadoop.hive.ql.Driver:compileAndRespond:Driver.java:1768', 'org.apache.hadoop.hive.ql.reexec.ReExecDriver:compileAndRespond:ReExecDriver.java:126', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:197', '*java.lang.ClassNotFoundException:org.apache.iceberg.mr.hive.HiveIcebergInputFormat:44:5', 'java.net.URLClassLoader:findClass:URLClassLoader.java:387', 'java.lang.ClassLoader:loadClass:ClassLoader.java:418', 'java.lang.ClassLoader:loadClass:ClassLoader.java:351', 'java.lang.Class:forName0:Class.java:-2', 'java.lang.Class:forName:Class.java:348', 'org.apache.hadoop.hive.ql.metadata.Table:getInputFormatClass:Table.java:321'], sqlState='42000', errorCode=40000, errorMessage='Error while compiling statement: FAILED: RuntimeException java.lang.ClassNotFoundException: org.apache.iceberg.mr.hive.HiveIcebergInputFormat'), operationHandle=None)

This may be triggered by:
Issue 1002 - The database returned an unexpected error. 

See less

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!

**Comment by hiteshmusale** [comment]
Hi I am facing similar issue 
Please help.
