### ISSUE TITLE
Advanced Analytics time comparison is feature is not working

### ISSUE THREAD

**Issue by stephanclaus** [apache/superset#21610]
#### How to reproduce the bug

1. Create a new chart with Line or Smooth Line
2. Add a date column into the time column and select the same column for the x axis
3. Use the Advanced Analytics Section to create a lagging Metric with Time Shift (e.g. 1 year) and selection Actual Values
4. Click Update Chart
5. see error: Unexpected error Error: A time column must be specified when using a Time Comparison.

### Expected results

The chart will be rendered as expected with a YoY comparison

### Actual results

An error is thrown: Unexpected error Error: A time column must be specified when using a Time Comparison. 

#### Screenshots

<img width="323" alt="config_1" src="https://user-images.githubusercontent.com/75787042/192631106-8e81e56a-ec9b-46e0-ab60-34b29243c4b3.png">
<img width="322" alt="config_2" src="https://user-images.githubusercontent.com/75787042/192631113-483fe6d3-7962-4e0c-9def-ecbd0d94cc15.png">
<img width="818" alt="error" src="https://user-images.githubusercontent.com/75787042/192631117-80d5c89e-730a-4f25-a42e-4ba4cb002e1b.png">

### Environment

(please complete the following information):

- browser type and version: chrome Version 105.0.5195.102
- superset version: `2.0.0`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Used to work before in superset 1.5.1. When I remove the configuration in the Advanced Analytics Section, the chart will render just fine. I assume Superset is too restrictive when a date column is added but the Advanced Analytics really expect a time column.

**Comment by zhaoyongjie** [comment]
Hi @stephanclaus, which database do you use? I have fixed an issue at [PR](https://github.com/apache/superset/pull/21378) recently for the SQLite.

**Comment by stephanclaus** [comment]
Hi @zhaoyongjie, we are using Snowflake.

**Comment by zhaoyongjie** [comment]
@stephanclaus Could you reproduce this issue on the other database as well?

**Comment by stephanclaus** [comment]
I just tried it again with a PostGres database and there the feature works as expected.
