### ISSUE TITLE
BUG: DRILL_TO_DETAIL in dashboard will cause sql parse error when chart add a jinjia2 template condition

### ISSUE THREAD

**Issue by JunTech** [apache/superset#21617]
I add a chart which i add a jinjia2 template filter to solve something  to dashboard , it seems works fine,however,when i open the flags 'DRILL_TO_DETAIL',it cause the sql error like 
'
Error: syntax error at or near ")"
LINE 68:   AND ()
',

#### How to reproduce the bug

1. add a chart with jinjia2 template filter,eg:
![image](https://user-images.githubusercontent.com/54126696/192715792-b0dbbe1c-4b74-4976-b80c-c4853940b07e.png)

2. add another filter_box chart   to fill the filter,eg:
 
![image](https://user-images.githubusercontent.com/54126696/192716463-19eebab3-cf83-4425-9ef0-058f75c2bba7.png)

3. right click the pie,drill to detail
![image](https://user-images.githubusercontent.com/54126696/192716679-f16f4e20-5d25-4798-9f25-dbf1dbc8738f.png)

![image](https://user-images.githubusercontent.com/54126696/192716795-1f3d7f10-a09c-493e-a1b2-f38d3f8a3a3a.png)

5. backend error 
position: superset/connectors/sqla/models.py:1660
![image](https://user-images.githubusercontent.com/54126696/192717320-b422dd65-cc94-43d5-aa41-74b929c52aa5.png)
template.render(context) get '()' 
however,it works good in chart, click  'edit chart' to chart
![image](https://user-images.githubusercontent.com/54126696/192717911-52d12446-4cdf-4c30-a481-fc71bd2f4f70.png)
jinjia2 render the true template what i expected
![image](https://user-images.githubusercontent.com/54126696/192718307-ee49aada-bb19-4377-8086-ab0c42f0242d.png)
 

### Expected results

drill to detail get the right  sql which rendered right result by jinjia2

### Actual results

it get nothing

### Environment

(please complete the following information):

- browser type and version: chrome 105
- superset version: `master`
- python version: `3.8.13`
- node.js version: `16`
- any feature flags active:
DRILL_TO_DETAIL,ENABLE_TEMPLATE_PROCESSING,cross_filter
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
