### ISSUE TITLE
Superset dashboard filter error

### ISSUE THREAD

**Issue by pthirumalai** [apache/superset#21619]
Hi

I created a dashboard in Apache superset with some filters. When I tried using the filters, I am getting an error. The screenshot is attached. 
![apache superset filter error](https://user-images.githubusercontent.com/114579758/192763906-8d6ba3c1-6d99-4d3f-9058-6e8377fd6f96.png)

I noticed string based filters are causing issues and numerical range filters are working fine.

Thanks

**Comment by zhaoyongjie** [comment]
@pthirumalai Do you have more context for this issue?

**Comment by pthirumalai** [comment]
@zhaoyongjie I created a dashboard in superset, the data is sourced from Google Bigquery. Without filters, the data is being retrieved and I am able to see data in dashboard, but when I add filters to the dashboard and try to manipulate the dashboard using the filters, I am getting "DB Engine Error". Please let me know if you need more details. Thanks.

**Comment by saghatelian** [comment]
Hi
I have the same problem. Let me try to add some more context. 
My dataset is from BigQuery.
When I create a dashboard filter with multiple possible values, it adds a where clause "[field] IN ([values])" which gives the error mentioned above. Writing **exactly the same** SQL in filter's CUSTOM SQL tab works perfectly.

Here are some screenshots. This gives an error:

![image](https://user-images.githubusercontent.com/43491361/195015823-c07eca72-a224-4b7d-bf48-055bf2d67c60.png)

This one works (I just went to CUSTOM SQL tab, added a space and saved):
![image](https://user-images.githubusercontent.com/43491361/195016615-d3f59e7e-2862-48cc-b658-21d2cbfadd28.png)

**Comment by pthirumalai** [comment]
Hi @saghatelian , Thanks for your reply. I have already tried uninstalling pybigquery and installed sqlalchemy-bigquery, but still the issue persists.

**Comment by pthirumalai** [comment]
Hi @saghatelian , Thanks for your reply. I have already tried uninstalling pybigquery and installed sqlalchemy-bigquery, but still the issue persists.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
