### ISSUE TITLE
Support IAM authentication for AWS RDS databases

### ISSUE THREAD

**Issue by gforien** [apache/superset#21624]
Currently Superset only supports connections to postgre-compatible databases with credentials.
The connection URI must be like `postgresql://username:password@host/db_name`.

AWS RDS provides IAM authentication [1] which allow to connect to a database with a role ARN and a session token (regularly refreshed).
This would allow to use Superset without the need for credentials on the underlying database.

Superset connector PyAthena [2][3] already supports assuming an IAM role, which removes the need for credentials on AWS Athena. Allowing the same kind of feature on RDS databases would be great 🚀 

Thank you for your help !

References
[1] https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html
[2] https://superset.apache.org/docs/databases/athena
[3] https://github.com/apache/superset/discussions/15739

**Comment by kamalkeshavani-aiinside** [comment]
@gforien This is a feature request, which should be raised under 'Discussions'. Please close this issue.

**Comment by gforien** [comment]
@matt-anon Yes this can surely be achieved by a simple python script for fetching & refreshing the token.
Google even maintains an example of this script for GCP https://github.com/GoogleCloudPlatform/cloud-sql-python-connector

The point was that this script could be provided by Superset, instead of having every cloud-based customer implementing it themselves 🙂
