### ISSUE TITLE
Full screenshot is not happening for sending mail

### ISSUE THREAD

**Issue by shafad1** [apache/superset#21636]
#### How to reproduce the bug

1. Go to Alert and Reports
2. Click on Reports
3. Schedule
4. partial image only rendering on email body

Pls help me on this.   due to not working this , customers are not satisfied with superset.

**Comment by mayurnewase** [comment]
adjust `WEBDRIVER_WINDOW` variable in superset/config.py file.

**Comment by shafad1** [comment]
> l

its not working , it was already tried

**Comment by superMarioB** [comment]
I see that this item is closed. What was the resolution? I'm having the same issue, only part of the dashboard is sent. I tried adjusting the WEBDRIVER_WINDOW in the config.py file and didn't work

**Comment by superMarioB** [comment]
@mayurnewase thoughts?

**Comment by mayurnewase** [comment]
apologies if the solution I gave didn't work for you and if this issue still exists.
I adjusted `WEBDRIVER_WINDOW` in our deployments which are based on 1.5 and it has been working correctly as expected.
reopening this so someone might take a look.

**Comment by superMarioB** [comment]
Thank you @mayurnewase. Maybe I have the wrong syntax? All I did is add this line in the file:

 WEBDRIVER_WINDOW = {"dashboard": (1600, 2000), "slice": (3000, 1200)}

**Comment by mayurnewase** [comment]
syntax is correct.
I have much bigger defaults set.
```
WEBDRIVER_WINDOW = {
    "dashboard": (1600, 10000),
    "slice": (3000, 1200),
    "pixel_density": 1,
}
```

**Comment by superMarioB** [comment]
Thanks! I'll try yours and let you know.

**Comment by superMarioB** [comment]
@mayurnewase tried that but didn't work :( 
what version of superset do you have installed? We are using v2.0.0

**Comment by rusackas** [comment]
This version of Superset is no longer supported. If anyone is still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
