### ISSUE TITLE
Dataset filter by schema is not working

### ISSUE THREAD

**Issue by stephanclaus** [apache/superset#21639]
#### How to reproduce the bug

1. Login to superset as an admin
2. go to Data/Datasets
3. Enter a value in the schema input
4. see error message below

### Expected results

The datasets are filtered by schema

### Actual results

see error message below

#### Screenshots

![schema_filter](https://user-images.githubusercontent.com/75787042/192954416-8dca53e2-c37e-465e-9148-7ce9ef18ef1d.png)

![error_message](https://user-images.githubusercontent.com/75787042/192954230-3d3da506-bff3-4ac9-9ae5-190160dd1c5f.png)

### Environment

(please complete the following information):

- browser type and version: Chrome Version 105.0.5195.102 (Official Build) (x86_64)
- superset version: `2.0.0`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

- Databases connected are Snowflake and PostGres
- all other filters work as expected

**Comment by mayurnewase** [comment]
fixed in https://github.com/apache/superset/pull/20711
