### ISSUE TITLE
@superset-ui/embedded-sdk NPM version not updated with the source code

### ISSUE THREAD

**Issue by lirannh** [apache/superset#21640]
#### How to reproduce the bug

1. npm install --save @superset-ui/embedded-sdk
1. Go to node_modules/@superset-ui/embedded-sdk/dist/index.d.ts 
2. see the UiConfigType have old version of type 
![image](https://user-images.githubusercontent.com/51078686/192969065-d176c67f-d701-44c6-9df0-63dae641ff7a.png)

3. on the source repo we have newer version of type

https://github.com/apache/superset/blob/master/superset-embedded-sdk/src/index.ts#L36
![image](https://user-images.githubusercontent.com/51078686/192969259-c61e34ec-e369-4a64-8883-c7f574a60664.png)

### Expected results

the code of the package should be the same as the source of the repository updated.

what you expected to happen.

npm install --save @superset-ui/embedded-sdk will give us the most updated version of the package.

Thank you

**Comment by fordsworth** [comment]
The latest changes are not reflected  @superset-ui/embedded-sdk. It looks like the package.json version is not being updated with the latest changes. The latest changes have the bug fixes we need but not published to npm.

**Comment by mehmetfatihturkmenoglu** [comment]
Hi there, do you have any update on this?  Thank you.

**Comment by rusackas** [comment]
The SDK was released much more recently than this issue was opened, so I'll close it as completed. That said, it's been 6 months since the `npm` module was published, so perhaps @eschutho and @michael-s-molina and others can discuss how we want to address this in the Release Strategy sync.
