### ISSUE TITLE
Duplicate log messages

### ISSUE THREAD

**Issue by SaTae66** [apache/superset#21646]
Every log message (except event logs) is logged 2 times, once in the custom format set in the "superset_config.py" (or the default one in "config.py" if not set otherwise) and the second time just the message without any context.

#### How to reproduce the bug
1. Run apache/superset image locally with docker
2. Look at logs

### Expected results
See every log entry once

### Actual results
See every log entry twice

### Logs from docker logs
`logging was configured successfully`
`2022-09-29 12:14:17,528:INFO:superset.utils.logging_configurator:logging was configured successfully`

**Comment by SaTae66** [comment]
From what I managed to find out, superset logs itself but somehow the messages are propagated up to gunicorn, which itself logs everything again. My knowledge about python is very limited, so I could not locate the root of the problem, however I found a workaround.

I disabled all logging for superset by adding the following to the conifg.py:

```
class NoLoggingConfigurator(  # pylint: disable=too-few-public-methods
    LoggingConfigurator
):
    def configure_logging(
        self, app_config, debug_mode
    ) -> None:
        logger.info("logging was configured successfully")


# disable logging for superset; logs are handled by gunicorn
LOGGING_CONFIGURATOR = NoLoggingConfigurator()
```

Furthermore, I added those 2 files to the root dir of superset:
1. gunicorn_logging.conf from [stackoverflow](https://stackoverflow.com/questions/34753214/json-formatted-logging-with-flask-and-gunicorn)
2. jsonlogging.py from [github](https://github.com/sebest/json-logging-py/blob/master/jsonlogging.py)

Now add `--log-config gunicorn_logging.conf` to the gunicorn command when starting superset and there will be only the json loggs from gunicorn. I am also setting the env variable `PYTHONWARNINGS=ignore` to prevent any (non-json) warnings from showing up.

------------------------------------------------------------------------------------------------------------

I still believe that logging should work properly without such a workaround, especially if it explicitly recommanded in the docs to use gunicorn.

**Comment by rusackas** [comment]
Is this still an issue in 3.x? I feel like I remember there were some improvements made in this area. Tempted to close as stale/obsolete since we don't support 2.x anymore.

**Comment by drummerwolli** [comment]
still a problem in 4.0.0 but seems like @jessie-ross is already on it in #27777
