### ISSUE TITLE
Charts with non-English names cannot be imported.

### ISSUE THREAD

**Issue by zertyuiop** [apache/superset#21657]
The chart cannot be imported if there are non-English characters in the name.

#### How to reproduce the bug

1. Create a chart with Russian (or perhaps any non-English) title
2. Export it
3. Delete it
4. Import it (Import successful message)

### Expected results

The chart should appear in the list of charts

### Actual results

The chart does not appear in the list. When trying to re-import, there is no overwriting suggestion, the chart is imported successfully, but it still does not appear in the list.

### Environment

(please complete the following information):

- browser type and version: Microsoft Edge 105.0.1343.53
- superset version: `2.0.0`, `0dda5fe`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

In the exported zip file, the chart files are named _55x.yml, where x is a number in order from 1 (at least in my case). Replacing the "_" character with any letter allows you to import charts.

**Comment by JunTech** [comment]
it cause by flask,maybe you can use pypinyin to change the name of the dashboard or chart like this;
![image](https://user-images.githubusercontent.com/54126696/194788656-fafd9444-2fe2-4e1c-b601-47b6bc664ac2.png)

**Comment by EugeneTorap** [comment]
@zertyuiop You can see my PR fix the bug and you can close your issue
