### ISSUE TITLE
ClickHouse Error: year 54725 is out of range

### ISSUE THREAD

**Issue by hermanzdosilovic** [apache/superset#21678]
Whatever query I run in SQL Lab I get the following error:
```
ClickHouse Error
year 54725 is out of range

This may be triggered by:
Issue 1002 - The database returned an unexpected error.
```

#### How to reproduce the bug

1. Go to SQL -> SQL Lab
2. Choose any `clickhouse` database
3. Write **any** query, for example: `select version()`, `select 1`, `select now()`, or `select 'hello, world'`

### Expected results

A query should run successfully.

### Actual results

I get the following error:
```
ClickHouse Error
year 54725 is out of range

This may be triggered by:
Issue 1002 - The database returned an unexpected error.
```

#### Screenshots

![image](https://user-images.githubusercontent.com/7927278/193559652-ffb8e96d-ffed-451e-ba31-f6b954e6f51b.png)
![image](https://user-images.githubusercontent.com/7927278/193559859-ea204310-cec4-4398-80e3-c3cfafed6000.png)
![image](https://user-images.githubusercontent.com/7927278/193560571-798d44c3-b3b5-4259-8d12-36f229168d7e.png)
![image](https://user-images.githubusercontent.com/7927278/193560617-e0fd1313-5170-41c3-bca2-f809eeb6316e.png)

### Environment

- browser type and version: `Version 1.44.105 Chromium: 106.0.5249.91 (Official Build) (x86_64)`
- superset version: `apache/superset:31895f412eba60e274c7158a39cf0a8455ffd671` (Docker image)
- python version: `3.8.13`
- node.js version: N/A since I am using official Docker image
- any feature flags active:
    ```
    FEATURE_FLAGS = {
        "ALERT_REPORTS": True,
        "DASHBOARD_RBAC": True,
        "ENABLE_TEMPLATE_PROCESSING": True,
        "SCHEDULED_QUERIES": True
    }
    ```

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any. [Logs are available here](https://github.com/apache/superset/files/9696884/log.txt).
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

1. ClickHouse version: `21.12.2.17`
2. Using `clickhouse-sqlalchemy==0.2.2`

**Comment by zhaoyongjie** [comment]
Hi @hermanzdosilovic, this issue has been resoved by https://github.com/apache/superset/pull/21667, so I close it. Feel free to reopen this one if you have the same issue yet.
