### ISSUE TITLE
[Chart] Can't use custom SQL in chart since 2.0.0 upgrade

### ISSUE THREAD

**Issue by zhaorui2022** [apache/superset#21689]
We have an issue reported from our user where chart fails when adding a column using custom SQL. The case we have seen is a column with type BIGINT. The user was trying to do some simple calculation like `column_name/6000`, however, it throws an error both on the UI and in the backend server where it says `Expected text or file-like object, got <class 'dict'>`. This should not be chart type specific and we have reproduced this error with both histogram and data table.

This functionality was working as expected before upgrading to 2.0.0, so it is likely to be a regression. And I can reproduce this error in the latest master branch as of 10/03/2022 3:30PM.

#### How to reproduce the bug

1. Go to chart, create a new chart
2. When adding a new column, select custom SQL, and put any valid SQL statement
3. Click on save, and update chart

### Expected results

Chart updated with custom SQL.

### Actual results

Fails due to `Expected text or file-like object, got <class 'dict'>`

#### Screenshots
![Google Chrome - Superset - 2022-10-03 at 3 48 29 PM](https://user-images.githubusercontent.com/105950525/193699807-f249323d-68ee-4972-952f-6b1c86a0a3a6.gif)

### Environment

(please complete the following information):

- browser type and version: not browser specific
- superset version: 2.0.0, can be reproduced with latest commit on master branch as of 10/03/2022 3:30PM PST
- python version: 3.8
- node.js version: N/A
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zhaorui2022** [comment]
I was also able to reproduce this error in the latest master branch with `docker-compose up`

**Comment by mayurnewase** [comment]
regression from : https://github.com/apache/superset/pull/19454/files
also exists in 1.5
looks critical.

**Comment by mayurnewase** [comment]
I did little digging, and looks like there is issue in `sqla/models.py/SqlaTable/get_sqla_query` function.
and attached patch would be helpful, if no one takes this on I will take it later when I get some time.

[21689_diff.txt](https://github.com/apache/superset/files/9707717/21689_diff.txt)
