### ISSUE TITLE
Forbidden Error - Chart - Samples Section

### ISSUE THREAD

**Issue by bonamim** [apache/superset#21695]
You can create charts using a dataset created by **someone else**, but you **are not able** to explore the data in the **sample section**.

#### How to reproduce the bug

1. Create a chart using a dataset created by someone else;
2. Try exploring the data from the sample section

### Expected results ✅ 

- Results section
![image](https://user-images.githubusercontent.com/36086878/193815601-9da5412c-ca46-491f-8792-1f5c5e6a0720.png)

- Samples section
![image](https://user-images.githubusercontent.com/36086878/193817368-183a7cb6-9322-4b16-bbe6-0d264a1ffcfa.png)

### Actual results ❌ 

- Results section
![image](https://user-images.githubusercontent.com/36086878/193815601-9da5412c-ca46-491f-8792-1f5c5e6a0720.png)

- Samples section
![image](https://user-images.githubusercontent.com/36086878/193816253-621eb237-1ff5-4027-a714-f54009445733.png)

### Environment

- browser type and version: Chrome (Version 104.0.5112.101)
- superset version: `superset version` 2.0.0
- any feature flags active:
  - ENABLE_TEMPLATE_PROCESSING

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

- Helm Chart;
- I've already tried copying the *Admin role* to see if I was missing any permissions, but it didn't help.

**Comment by zhaoyongjie** [comment]
Hi @bonamim, I guess you upgrade the existing Superset Application instead of a new one. Could you run `superset init` after upgrading it? This problem seems to lack of permission in the new Samples endpoint.

**Comment by bonamim** [comment]
Hi @zhaoyongjie,
This command is supposed to run when we restart containers, isn't it? Because we restarted the instance recently.

**Comment by bonamim** [comment]
@zhaoyongjie, we upgraded to version 2.0.1, then ran the command: `superset init`, but it didn't fix the problem.

**Comment by radaniba** [comment]
@bonamim I am experiencing the same issue did you fix this issue ? if yes you recall how ?

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.

**Comment by MohamedRhimii** [comment]
Hi @rusackas , this is still an issue. I'm using superset v3.1.0. One of our users is forbidden to save charts although given the appropriate permissions. Please re-open, I'm seeking support.
