### ISSUE TITLE
[Chart Explore] Weird scroll bar jumping issue when Search Box is active

### ISSUE THREAD

**Issue by stevetracvc** [apache/superset#21699]
Video explains it way better. Disabling the search box fixes it. This only occurs in the explore view.

#### How to reproduce the bug

1. Edit a table
2. Click on Search Box to add the search box
3. Watch the fireworks

### Expected results

It to not go crazy

### Actual results

It goes crazy. You can see the CSS class keeps toggling between two options.

#### Screenshots

https://user-images.githubusercontent.com/70416691/193972638-ce489936-b579-48d4-9014-5590b9b72af2.mp4

### Environment

(please complete the following information):

- browser type and version: Chrome 102.0.5005.61 on Ubuntu
- superset version: checked out fresh, tag 2.0.0, docker

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by stevetracvc** [comment]
Hmm...I finally got master to run, and it looks fixed, so I'm closing

**Comment by gerpang** [comment]
Hey, I'm facing this issue as well. I'm using Chrome 106 and Superset 2.0.0, and toggling on the Search Bar or specifying a page length in any Table causes the scroll bars to start dancing. If I repeatedly open and close the Results/Sample panel it sometimes stops. 

How did you manage to fix it?

**Comment by stevetracvc** [comment]
I didn't. It was working fine on the master branch so someone fixed it somewhere, I don't know where. I don't even know where to look for that. Have you tried any of the 2.0.1 releases?

**Comment by artemonsh** [comment]
The change was made here: https://github.com/apache/superset/pull/20833

**Comment by stevetracvc** [comment]
thanks @artemonsh. Twitch is a good descriptor, I didn't search for that.

**Comment by cakmapilot** [comment]
We are using 2.0.1 and it's still the same. It's still twitchting. Not fixed on 2.0.1.

**Comment by DiegoZoracKy** [comment]
> We are using 2.0.1 and it's seems still the same. It's still twitchting.

Same behavior around here on version 2.0.1
