### ISSUE TITLE
Iframe embedding throws Internal Server Error

### ISSUE THREAD

**Issue by abh006** [apache/superset#21703]
I'm trying to embed one of our superset charts into a svelte UI. I've been trying to copy-paste the iframe code generated in the superset explore page and it is showing internal server error.

#### How to reproduce the bug

1. Create an HTML page. 
2. Copy the iframe code snippet generated by the Superset chart explore page.
<img width="712" alt="image" src="https://user-images.githubusercontent.com/26924922/194071065-150b13d6-4bd4-42f2-bd96-7dff959f346f.png">

### Expected results

It should show the chart

### Actual results
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/26924922/194071164-c0503170-8a31-4d34-8567-6db6c2d81435.png">

### Environment

(please complete the following information):

- browser type and version: Firefox Developer Edition 106.0b7 (64-bit)
- superset version: `superset version` 1.5.2
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Python Logs
```
You don't have access to this dataset.
2022-10-05 13:26:21,407:WARNING:superset.views.base:You don't have access to this dataset.
172.18.0.1 - - [05/Oct/2022:13:26:21 +0000] "GET /superset/explore/p/O08vxH8Pn03/?standalone=1&height=400 HTTP/1.0" 500 0 "http://localhost:5173/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0"
```

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sfirke** [comment]
Those Python logs make it appear that it's a permissions issue, that your user - probably Public but maybe you're having people log in - can't view that data source.  I can confirm that embedded iframe charts work on Superset 2.0.0 if permissions are configured correctly.

**Comment by felipegirotti** [comment]
I believe this is related: https://github.com/apache/superset/pull/22462/files, the latest version of image with new version of flask

**Comment by waleedshabbir1** [comment]
@sfirke I also see this error on latest version of superset. I can see the page but in the API I can see the error "you dont have access to this dataset". 
Although dataset is public and public user is given all the permission to read dataset and charts

Can you post your solution?

**Comment by sfirke** [comment]
I am using the `DASHBOARD_RBAC` feature flag so instead of giving a public _user_ permissions to access resources, I grant access to the Public _role_ at the dashboard level.  Then I can embed it as an iframe in another site.

**Comment by rusackas** [comment]
Given the above suggestion, I'm not sure if this is still an issue or not. Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
