### ISSUE TITLE
How do I rename legend from dimension?

### ISSUE THREAD

**Issue by fMagVen** [apache/superset#21718]
I have a time series plot where I measure the amount of entries in a column with count distinct, and group them by a boolean value from another column, throughout the months. I know I can rename any entry from metrics, but how do I rename legends generated by dimensions?
![dimensionlegend](https://user-images.githubusercontent.com/78576546/194317504-959740b9-5650-4120-a505-0b3608ba2bde.png)

**Comment by kamalkeshavani-aiinside** [comment]
You can't rename them like metrics. Assuming you want to show different values than True/False as legends, one way of doing this is to create a calculated column, which has new values for your existing values and use calculated column as your dimension, ex. `CASE cliente_de_alto_spending WHEN TRUE THEN 'A' WHEN FALSE THEN 'B' END`.

Also, for questions like this 'Discussions' would be a better place than Issues. Please close the issue.

**Comment by fMagVen** [comment]
a better idea would be to turn it into a feature request, but how do i do that

**Comment by kamalkeshavani-aiinside** [comment]
New feature are also requested in the 'Discussions'.

**Comment by mayurnewase** [comment]
you can't rename legends, also please use discussion for this as Kamal said.

**Comment by BzCoder** [comment]
the same issue, and not convenient when using it

**Comment by njoguhmureithi** [comment]
I appreciate the earlier discussions and I would like to request a feature that allows one to rename the legends. Currently, i'm working on big data, and modifying individual entries is taxing.
