### ISSUE TITLE
Embedded Dashboards Bulk Delete Error

### ISSUE THREAD

**Issue by asarro99** [apache/superset#21746]
If you try to delete more than one embedded dashboard in a row using the bulk delete function you will get an error.

#### How to reproduce the bug

1. Enable **EMBEDDED_SUPERSET** option in **config.py**.
2. Go to Dashboards.
3. Embed more than one dashboard.
4. Try to delete more than one embedded dashboard in a row. 
5. See error

### Expected results

Both dashboards are successfully deleted.

### Actual results

An error is returned.

#### Screenshots

![bulk_delete_error](https://user-images.githubusercontent.com/44396182/194717660-7af8dd75-6381-4f23-b293-a96c871f21f4.png)

### Environment

- browser type and version: `Firefox 105.0.3 `
- superset version: `aef6217`
- python version: `3.10.7`
- node.js version: `18.10.0`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Resolved by https://github.com/apache/superset/pull/21911
