### ISSUE TITLE
failed to build numpy wheel even inside virtual environment  using 'pip install apache-superset'

### ISSUE THREAD

**Issue by AnirbanPatragithub** [apache/superset#21751]
[Apache_Superset_Numpy_Wheel Error.txt](https://github.com/apache/superset/files/9743569/Apache_Superset_Numpy_Wheel.Error.txt)

I have followed the installation process diligently but still numpy wheel build is failing.I have later tried to install numpy == 1.22.1 as required by apache_superset,though the installation was success yet it failed while pip install apache superset.

**Comment by artemonsh** [comment]
Look at the error at the line 149: setup.py:67: RuntimeWarning: NumPy 1.19.4 may not yet support Python 3.10

Try using python 3.8

**Comment by AnirbanPatragithub** [comment]
@artemonsh  But I am already using python 3.10 with numpy in other environments without any problem.
Yet I will try what You said.

But I am not getting any proper guide as to how should downgrade python 3.10 with python 3.8.


You can help by pointing in the right direction or just directly helping me with pip commands


thanks a lot

You help is much appreciated.

**Comment by artemonsh** [comment]
I think you may use another version of numpy (not 1.22.1) in python3.10. 
I cannot provide you with the link until I know what OS do you use

**Comment by jimmybutton** [comment]
I'm having exactly the same issue as @AnirbanPatragithub. Running python3.10 on Ubuntu 22.04 LTS.

**Comment by jaksmid** [comment]
The problem on 3.10 and numpy 1.22.1 installed is caused by pyarrow as it triggers 1.19.4 numpy installation

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently Superset 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
