### ISSUE TITLE
about add database for clickhouse

### ISSUE THREAD

**Issue by gcoder5** [apache/superset#21777]
#### How to reproduce the bug

1. Go to Main Page
2. Click on Connect database
3. select Clickhouse
4. if my clickhouse password incloude '@' or '+',i will test connect failure.

### Expected results

when my password incloude  '@' or '+', i can test connect successful and add database successful.

### Actual results

 test connect failure.

#### Screenshots

![image](https://user-images.githubusercontent.com/55041518/195230668-8e6f4ab1-b3ac-4d86-a945-ed792fe17ed5.png)

### Environment

(please complete the following information):

- browser type and version:chrome 105.0.5195.125
- docker images version:apache/superset     latest

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ √] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ √] I have reproduced the issue with at least the latest released version of superset.
- [ √] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mayurnewase** [comment]
you have escape it.

**Comment by mayurnewase** [comment]
feel free to reopen if that doesn't work.
