### ISSUE TITLE
Error: persistentvolume-controller  waiting for pod superset-postgresql-0 to be scheduled

### ISSUE THREAD

**Issue by misumme-pg** [apache/superset#21774]
I'm trying to install superset in my eks cluster but keep running into following error 

 Normal   WaitForPodScheduled   4m6s (x23 over 19m)  persistentvolume-controller  waiting for pod superset-postgresql-0 to be scheduled

Failed to provision volume with StorageClass "gp2": failed to create encrypted volume: the volume disappeared after creation, most likely due to inaccessible KMS encryption key

Error: failed post-install: timed out waiting for the condition
$ kubectl get pods
NAME                               READY   STATUS     RESTARTS   AGE
superset-67cf764f44-cbmp6          0/1     Init:0/1   0          6m47s
superset-init-db-vn7rb             0/1     Init:0/1   0          6m47s
superset-postgresql-0              0/1     Pending    0          6m47s
superset-redis-master-0            1/1     Running    0          6m47s
superset-worker-867678fb57-jnkgd   0/1     Init:0/1   0          6m47s

I'm not sure what do ? How do I resolve this error

**Comment by mayurnewase** [comment]
looks like issue with AWS permissions, doesn't look like relaeted to superset.
I have deployed current latest in EKS without any problem.

This could be helpful for your case -> https://stackoverflow.com/questions/66270171/kubectl-apply-failing-to-create-ebs-volume-persistent-volume-claim

feel free to reopen if you think its related to superset's helm charts.
