### ISSUE TITLE
User unable to view datasets/charts/dashboards created by other users although relevant DB permission is granted

### ISSUE THREAD

**Issue by deepudelap** [apache/superset#21795]
- Created a new user and a new DB connection (Trino). 
- Created new Role (Aplha Plus) - Copied the Alpha role and removed 'all datasource access on all datasources' and 'all database access on all databases' 
- Added 'database access on Trino' permission to this new role.
- Now assigned the user with this new role.
- The user is able to run SQL queries, create chart, dashboards, datasets from the DATA that is from Trino DB connection.
- But the user is unable to view the list of datasets/charts/dashboards created by other users using the Trino DB connection. If the user is given the link of the objects created by other users, only then the user is able to view them.

**#### How to reproduce the bug**

- Create a new User (test_user)
- Create a new DB connection (Trino). 
- Create new Role (Aplha Plus) by Cloning the Alpha role and remove 'all datasource access on all datasources' and 'all database access on all databases' permissions.
- Add 'database access on Trino' permission to this new role Alpha_Plus.
- Now assigned the test_user with this new role Alpha_Plus

**### Expected results**

1. The test_user is able to run SQL queries, create chart, dashboards, datasets from the DATA that is from Trino DB connection.
2. The test_user can view the datasets/charts/dashboards created by other users, given that they have been created using data from Trino DB connection.

**### Actual results**

1. The test_user is able to run SQL queries, create chart, dashboards, datasets from the DATA that is from Trino DB connection.
2. The test_user **CANNOT** view the datasets/charts/dashboards created by other users, although they have been created using data from Trino DB connection.

### Environment

(please complete the following information):

- browser type and version: Chrome Version 105.0.5195.125
- superset version: `superset version` : 2.0
- python version: `python --version`: 3.8.13
- node.js version: `node -v`: 16
- any feature flags active: ENABLE_PROXY_FIX = False
                                            WTF_CSRF_ENABLED = False
                                            SUPERSET_DASHBOARD_POSITION_DATA_LIMIT = 100000
FEATURE_FLAGS = {"DASHBOARD_CROSS_FILTERS": True, "ALERT_REPORTS": True, "THUMBNAILS": True, "ENABLE_TEMPLATE_PROCESSING": True, "PRESTO_SPLIT_VIEWS_FROM_TABLES": False}

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any - **YES**
- [x] I have reproduced the issue with at least the latest released version of superset - **YES**
- [x] I have checked the issue tracker for the same issue and I haven't found one similar - **YES**

**Comment by ryandawsonuk** [comment]
My current project is also being affected by this bug

**Comment by rusackas** [comment]
We no longer support 2.0 officially... is this still ann issue in 3.x?

**Comment by rusackas** [comment]
Closing as stale. Happy to revisit/reopen if this is still an issue people are facing in 4.x. Meanwhile, perhaps @dosu-bot can leave some helpful thoughts just in case they help others.
