### ISSUE TITLE
Feature to avail provision of a HTTP/HTTPS API (get/post) to act as a data source for Superset

### ISSUE THREAD

**Issue by mksbiz** [apache/superset#21798]
For a multi-tenancy deployment, we want to isolate our DB from Superset deployment. A minimal and trusted approach will be to use an API as a data source for Superset. With API we will have better control of what data is exposed to each user, to terminate access as per the requirement and implement a unified architecture for a front-end application which uses reactjs. I have gone through these two repos:
https://github.com/betodealmeida/shillelagh
https://github.com/cancan101/graphql-db-api

But an officially released and validated module as part of Superset's DB engine will be very helpful in implementing this out-of-the-box.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and is a feature request rather than a bug. If this is relevant in current versions (currently 3.x) please open a new Ideas discussion or a PR to address the problem.
