### ISSUE TITLE
Field formatting is not working on [Mixed Time-Series] chart type

### ISSUE THREAD

**Issue by bonamim** [apache/superset#21801]
Field formatting is not working on [**Mixed Time-Series**] chart type.

#### How to reproduce the bug

1. Create a [**Mixed Time-Series**] chart;
2. Add any metric;
3. Try to format this metric.

### Expected results ✅ 

- Table Chart
![image](https://user-images.githubusercontent.com/36086878/195560161-3cc153a7-25d4-42c8-b64c-feda0a88f08a.png)

- Time Series Bar Chart
![image](https://user-images.githubusercontent.com/36086878/195560200-2533ca69-21c7-4adf-b8f4-bc0dd1ab7d3d.png)

### Actual results ❌ 

- Mixed Time-Series
![image](https://user-images.githubusercontent.com/36086878/195560410-7af4411d-00bb-4d15-8768-c79391707fa6.png)

### Environment

- browser type and version: Chrome (Version 104.0.5112.101)
- superset version: `superset version` 2.0.0
- any feature flags active:
  - ENABLE_TEMPLATE_PROCESSING

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

- Helm Chart;

**Comment by shalnice** [comment]
similar issue with [#23161](https://github.com/apache/superset/issues/23161)

**Comment by Shazad-khan** [comment]
![image](https://user-images.githubusercontent.com/100838455/225594402-afdf036a-5da3-4a47-96af-789fd79f0f12.png)

Working as expected please recheck it and close the issue

**Comment by rusackas** [comment]
It does sound like this is working as expected (the control is for the axis, not the data points). If there's still a current _bug_ in supported versions (3.x) please open a fresh issue with updated context and a reproducible example. Otherwise, if you're looking to support more/better ways to format data points, we're open to reviewing a PR! Thanks!
