### ISSUE TITLE
MSSQL Async Query using Celery fails with error year 54755 is out of range

### ISSUE THREAD

**Issue by v-giannis** [apache/superset#21810]
#### How to reproduce the bug

1. Enabled async quries using celery via https://superset.apache.org/docs/installation/async-queries-celery
2. Enabled async database queries through database configuration for mssql server
3. open the sql tab and run the query 

### Expected results

Get back the query results like when I had the async queries disabled

### Actual results

  fails with error year 54755 is out of range
### Environment
docker running superset 

(please complete the following information):

 
- superset version
- 2022-10-14 08:20:43,968:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
Falling back to the built-in cache, that stores data in the metadata database, for the following cache: `FILTER_STATE_CACHE_CONFIG`. It is recommended to use `RedisCache`, `MemcachedCache` or another dedicated caching backend for production deployments
2022-10-14 08:20:43,973:WARNING:superset.utils.cache_manager:Falling back to the built-in cache, that stores data in the metadata database, for the following cache: `FILTER_STATE_CACHE_CONFIG`. It is recommended to use `RedisCache`, `MemcachedCache` or another dedicated caching backend for production deployments
Falling back to the built-in cache, that stores data in the metadata database, for the following cache: `EXPLORE_FORM_DATA_CACHE_CONFIG`. It is recommended to use `RedisCache`, `MemcachedCache` or another dedicated caching backend for production deployments
2022-10-14 08:20:43,977:WARNING:superset.utils.cache_manager:Falling back to the built-in cache, that stores data in the metadata database, for the following cache: `EXPLORE_FORM_DATA_CACHE_CONFIG`. It is recommended to use `RedisCache`, `MemcachedCache` or another dedicated caching backend for production deployments
/usr/local/lib/python3.8/site-packages/flask_appbuilder/models/sqla/interface.py:68: SAWarning: relationship 'SqlaTable.slices' will copy column tables.id to column slices.datasource_id, which conflicts with relationship(s): 'Slice.table' (copies tables.id to slices.datasource_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="table"' to the 'SqlaTable.slices' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for prop in class_mapper(obj).iterate_properties:
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Superset 0.0.0-dev
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
 
- python version: 3.8.13
 
 
 

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

![Screen Shot 2022-10-14 at 11 12 35](https://user-images.githubusercontent.com/56992973/195799198-e7dab881-fdaa-4af7-acb3-d4062cf3e588.png)
![Screen Shot 2022-10-14 at 11 12 45](https://user-images.githubusercontent.com/56992973/195799205-9ffca45d-aabd-4ae9-87de-092d0a80826e.png)
![Screen Shot 2022-10-14 at 11 13 31](https://user-images.githubusercontent.com/56992973/195799210-423d92b0-2735-4a30-8206-7b74a16e6165.png)

### Additional context
no idea really how to investigate furher.

Regards

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) feel free to re-open this, open a new Issue, or open a PR to address the problem.
