### ISSUE TITLE
SupersetError : 'Expecting value: line 1 column 1 (char 0)', error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'

### ISSUE THREAD

**Issue by musolinimayilvaganan** [apache/superset#21835]
#### How to reproduce the bug

1. Go to 'Data -> Databases and click on "+database"'
2. Click on 'Select Trino from the support database and enter the connect string as'
 trino://{username}:{password}@host:port/dbname
4. scroll down to bottom and Click on "Test connection"
5. See error
****************************************************************************
File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 98, in wraps
return f(self, *args, **kwargs)
File "/app/superset/views/base_api.py", line 113, in wraps
raise ex
File "/app/superset/views/base_api.py", line 110, in wraps
duration, response = time_function(f, self, *args, **kwargs)
File "/app/superset/utils/core.py", line 1507, in time_function
response = func(*args, **kwargs)
File "/app/superset/utils/log.py", line 245, in wrapper
value = f(*args, **kwargs)
File "/app/superset/views/base_api.py", line 83, in wraps
return f(self, *args, **kwargs)
File "/app/superset/databases/api.py", line 709, in test_connection
TestConnectionDatabaseCommand(g.user, item).run()
File "/app/superset/databases/commands/test_connection.py", line 166, in run
raise DatabaseTestConnectionUnexpectedError(errors) from ex
superset.databases.commands.exceptions.DatabaseTestConnectionUnexpectedError: [SupersetError(message='Expecting value: line 1 column 1 (char 0)', error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'Trino', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]

### Expected results

The test connection should be successful, and we should be able to create datasets once the connection successful

### Actual results

Expecting value: line 1 column 1 (char 0) 

### Environment

(please complete the following information):

- browser type and version: Chrome - Version 106.0.5249.119 
- superset version: V2.0.0
- python version: 3.8
- node.js version: `node -v`
- any feature flags active: ENABLE_TEMPLATE_PROCESSING , ALLOW_FULL_CSV_EXPORT

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by musicmuthu** [comment]
i have the same issue after update the trino plugin in superset 
working version of the plugin is sqlalchemy-trino==0.4.1

**Comment by musicmuthu** [comment]
superset version is 2.0.0 and 2.0.1 i tested with the latest plugin pip install trino

**Comment by musolinimayilvaganan** [comment]
The below string with verify=false should work.. Also please check the connection request hits the trino service

trino://{username}:{password}@host:port/catalogname?verify=false
