### ISSUE TITLE
Chart width not refreshed properly while tab switch

### ISSUE THREAD

**Issue by PrabuSarvesan** [apache/superset#21852]
#### How to reproduce the bug

1. Open Sales dashboard in Superset application.
2. Go to Exploratory tab and toggle(expand/collapse) the dashboard filter.
3. Switch back again to Sales Overview tab.

### Expected results

Total revenue chart should be resized based on modified size.

### Actual results

Total revenue chart was not resized with modified size. This issue occurs for all charts.

#### Screenshots

![image](https://user-images.githubusercontent.com/18459529/196418314-cafcb173-bf23-4b72-bce8-2a647ab60464.png)

### Environment

- browser type and version: Chrome 
- superset version: Latest source from GitHub

### Checklist

- [*] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [*] I have reproduced the issue with at least the latest released version of superset.
- [*] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

**shouldComponentUpdate returns false** in **superset-frontend/src/dashboard/components/gridComponents/Chart.jsx** while tab switch. Following condition was not met,
if (
        nextProps.width !== this.props.width ||
        nextProps.height !== this.props.height
      ) {
        clearTimeout(this.resizeTimeout);
        this.resizeTimeout = setTimeout(this.resize, RESIZE_TIMEOUT);
      }

**Comment by Shazad-khan** [comment]
![image](https://user-images.githubusercontent.com/100838455/226266939-bfca030a-441e-45c0-a666-6508c848ca43.png)

It is working as expected please recheck it and close the issue
