### ISSUE TITLE
when i run command with `npm run build`, it tell me react not support css property

### ISSUE THREAD

**Issue by mengzhigang** [apache/superset#21851]
/Users/mengzhigang/Desktop/python_workspace/Superset/superset-frontend/src/views/components/RightMenu.tsx
  396:24  error  Unknown property 'css' found                     react/no-unknown-property
  401:24  error  Unknown property 'css' found                     react/no-unknown-property
  406:24  error  Unknown property 'css' found                     react/no-unknown-property
  411:24  error  Unknown property 'css' found                     react/no-unknown-property
  471:3   error  State initialization should be in a constructor  react/state-in-constructor

/Users/mengzhigang/Desktop/python_workspace/Superset/superset-frontend/src/visualizations/TimeTable/TimeTable.jsx
  245:11  error  Unknown property 'css' found  react/no-unknown-property

✖ 383 problems (163 errors, 220 warnings)

just like this.

报错的都是div，span这种基础标签

**Comment by rusackas** [comment]
I'm not sure why there are so many snyk links here, but this no longer seems to be the case in current-era Superset. Let us know if this needs revisiting for some reason.

**Comment by CollinEMac** [comment]
> I'm not sure why there are so many snyk links here, but this no longer seems to be the case in current-era Superset. Let us know if this needs revisiting for some reason.

I've recently upgraded to Superset v3.1.2 and I'm now encountering the same issue. Example:

```
#31 201.2 ERROR in src/pages/SqlLab/index.tsx:67:9
#31 201.2 react/no-unknown-property: Unknown property 'css' found
#31 201.2     65 |     <LocationProvider>
#31 201.2     66 |       <div
#31 201.2   > 67 |         css={css`
#31 201.2        |         ^^^^^^^^^
#31 201.2   > 68 |           flex: 1 1 auto;
#31 201.2        | ^^^^^^^^^^^^^^^^^^^^^^^^^
#31 201.2   > 69 |           position: relative;
#31 201.2        | ^^^^^^^^^^^^^^^^^^^^^^^^^
#31 201.2   > 70 |           display: flex;
#31 201.2        | ^^^^^^^^^^^^^^^^^^^^^^^^^
#31 201.2   > 71 |           flex-direction: column;
#31 201.2        | ^^^^^^^^^^^^^^^^^^^^^^^^^
#31 201.2   > 72 |         `}
#31 201.2        | ^^^^^^^^^^^
#31 201.2     73 |       >
#31 201.2     74 |         <SqlLabGlobalStyles />
#31 201.2     75 |         <App />
```

I've managed to get around it by doing something [like this](https://github.com/emotion-js/emotion/issues/2878#issuecomment-1236384580) but it doesn't feel like I should have to do that.
