### ISSUE TITLE
When exporting to CSV with the 'Pivoted' option, all row fields are concatenated into one column in Excel. Is this a known issue?

### ISSUE THREAD

**Issue by cass-simplelegal** [apache/superset#21854]
When I export a 'Pivoted' CSV with multiple rows, for example, all of the row values are concatenated together into one large CSV/Excel cell. I would hop that the file being exported would instead match the pivot chart UI that has multiple cells per row instead.

#### How to reproduce the bug

1. Explore a pivot table chart
2. Click on 'Export CSV'
3. Scroll down to 'Pivoted' option
4. Multiple Rows concactenate into one cell for the CSV

### Expected results

Have a new cell per row output in CSV format.

### Actual results

Has one cell per x rows by concatenating all of the rows together

#### Screenshots

Actual Results:

![pivot_screenshot](https://user-images.githubusercontent.com/116036593/196445229-2248e8de-3457-4c13-ab9d-06379dee522a.png)

### Environment

(please complete the following information):

- browser type and version: Google Chrome, version 106.0.5249.119
- superset version: latest dev version locally and version 1.5 in production
- any feature flags active:
    "ROW_LEVEL_SECURITY": True,
    "ENABLE_TEMPLATE_PROCESSING": True,
    "VERSIONED_EXPORT": True,
    "ENABLE_EXPLORE_DRAG_AND_DROP": True,
    "DASHBOARD_NATIVE_FILTERS": False,
    "ENABLE_FILTER_BOX_MIGRATION": False,

**Comment by artemonsh** [comment]
+1

**Comment by rusackas** [comment]
Looks like this should have been closed by the linked PR. Closing now :)
