### ISSUE TITLE
Superset not stopping when I press stop button.

### ISSUE THREAD

**Issue by M3gar00** [apache/superset#21865]
I'm attempting to run a simple test query:
```SELECT count(*) from table_x;```

I'm currently sitting at `22:35:59.00` and counting.

I've reset the server multiple times (I'm working on a different problem that has required the server to be re-deployed).

#### How to reproduce the bug

No clue, this query has worked almost instantaneously in the past.

### Expected results

The query to A) run quickly and B) stop when I hit the stop button.

### Actual results

The query is still going almost a full day later, and I get an error of `Failed at stopping query. z-Bk9XLonv` when I click on Stop.

#### Screenshots

![Screen Shot 2022-10-18 at 1 35 52 PM](https://user-images.githubusercontent.com/77980332/196503978-4f7016bd-a075-44a9-97e5-6ac3818d1c90.png)

### Environment

- Chrome Version 106.0.5249.103 (Official Build) (arm64)
- superset version: `2.0.0`
- any feature flags active:
FEATURE_FLAGS = {
    "ALERT_REPORTS": True,
    "DASHBOARD_RBAC": True,
}
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [?] I have reproduced the issue with at least the latest released version of superset.
- I have found the issue in issue tracker, and there was no resolution posted. Issue: [Link](https://github.com/apache/superset/issues/18787)

### Additional context

I started another query in a tab (Similar to the first), and I recorded the logs from when the query started:
![Screen Shot 2022-10-18 at 1 40 27 PM](https://user-images.githubusercontent.com/77980332/196504885-ced0ef18-a5b0-4e1e-b434-a85d9eb0d15f.png)

**Comment by eschutho** [comment]
HI, what database are you running the query on? Some databases haven't been enabled yet with stop query functionality.

**Comment by M3gar00** [comment]
@eschutho Sorry, I should have included that in my OP. I'm using MySQL.

**Comment by phihung** [comment]
I have the same problem with `superset + trino`.
Even after the trino query was time-out (I even tried restarting trino container), superset UI keeps showing "running".
`POST /stop_query` results on 422 UNPROCESSABLE ENTITY error.

**Comment by eschutho** [comment]
@M3gar00 Yeah, MySQL should work for this. We'll have to test more on both MySQL and Trino.

**Comment by hughhhh** [comment]
currently tested this locally on the same build, and I'm able to properly stop the query

https://user-images.githubusercontent.com/27827808/206781569-923244b0-3f0d-454a-961e-fbb5a3a44657.mov

**Comment by lgingerich** [comment]
Hello @eschutho, you mentioned above that some databases haven't been enabled yet with stop query functionality. Has it been enabled for Google BigQuery yet?

I am using Google BigQuery and the stop query functionality isn't working for me, but I want to make sure it's not another issue causing this.

**Comment by eschutho** [comment]
Right now, I see the cancel functionality in mysql, postgres, redshift, snowflake and trino. So, no, I don't see the method built out for BigQuery yet @lgingerich.

**Comment by christianxiaobai** [comment]
When I use SQL Lab with Impala as the data source, I often encounter the following error message when I click the stop button during query execution:Failed at stopping query. WUJFsUIaJ

**Comment by iabhinavkaundal** [comment]
Hello Team,
We have added Mysql and Postgresql in my machine and it facing the same issue on "Failed at stopping query. D-pibT97ZN".
Please help
![Group 2](https://user-images.githubusercontent.com/127467585/224224374-32d4731d-9cd0-4835-8ab5-6991969c57e9.png)

**Comment by iabhinavkaundal** [comment]
> Hello Team, We have added Mysql and Postgresql in my machine and we are facing the same issue on "Failed at stopping query. D-pibT97ZN". Please help ![Group 2](https://user-images.githubusercontent.com/127467585/224224374-32d4731d-9cd0-4835-8ab5-6991969c57e9.png)

Please help in this as we are stuck

**Comment by eschutho** [comment]
The `failed at stopping query` error can happen when the query has already finished its execution before the request to stop the execution reached the database. Can you try running a very long query to make sure that that isn't the case?

**Comment by eschutho** [comment]
> When I use SQL Lab with Impala as the data source, I often encounter the following error message when I click the stop button during query execution:Failed at stopping query. WUJFsUIaJ

Impala stop query was implemented recently in https://github.com/apache/superset/pull/22635. You can test this out on the 2.1 release.

**Comment by MateusCastello** [comment]
I'm having the same problem with `superset + trino` on Superset 2.1.0

**Comment by eschutho** [comment]
ccing @villebro - he mentioned that he can test out Trino.

**Comment by villebro** [comment]
Hi, I'm looking into this, and I can indeed confirm that the queries appear to execute regardless of the stop button having been pushed. This may somehow be related to the migration of the query stopper from the legacy view to the v1 API.

**Comment by Lucian63** [comment]
Hi @eschutho, we ran into the same issue in Production that "Stop" button doesn't response in v2.1.0 Superset. We are using the "Clickhouse" as the database. Could you help to check whether this is enabled or not? If not, is there any ETA? Appreciate your help in advance.

**Comment by eschutho** [comment]
> Hi @eschutho, we ran into the same issue in Production that "Stop" button doesn't response in v2.1.0 Superset. We are using the "Clickhouse" as the database. Could you help to check whether this is enabled or not? If not, is there any ETA? Appreciate your help in advance.

Hi @Lucian63, stop query functionality for clickhouse has not been implemented yet. We're open to PRs though!

**Comment by shubhamverma6594** [comment]
Hi @eschutho @Lucian63, stop query functionality for Bigquery has not been implemented yet

**Comment by hcai** [comment]
We use MySql and Superset 3.0.2, the stop button only works if they queries are executed in synchronous mode

**Comment by rusackas** [comment]
Closing this since it's a confluence of databases being reported (some have been fixed, some maybe not), and it's on a no-longer-supported version of Superset, and it's been stale for upward of 6 months. If anyone is still facing these issues, please post a new Issue with a single database and updated context. Thanks for understanding.
