### ISSUE TITLE
Please add SingleStoreDB to the list of supported database systems

### ISSUE THREAD

**Issue by VeryFatBoy** [apache/superset#21871]
SingleStoreDB is a MySQL-wire compatible database system. It works with Apache Superset as shown by this article:

https://dev.to/veryfatboy/quick-tip-connecting-apache-superset-to-singlestoredb-35a5

However, there is a JDBC connector available that is optimised for use with SingleStoreDB:

https://github.com/memsql/S2-JDBC-Connector

The request is to please add SingleStoreDB support to Apache Superset.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and is a feature request rather than a bug. If this is relevant in current versions (currently 3.x) please open a new Ideas discussion or a PR to address the problem.
