### ISSUE TITLE
NotFound()werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

### ISSUE THREAD

**Issue by liuyu2013** [apache/superset#21881]
i use "pip install --no-cache -r requirements/local.txt", and write a run.py to start on localhost. 
run.py as follows：
```
import imp
import os
from superset import create_app
os.environ["superset_dev"] = os.path.join(os.getcwd(), 'superset_dev/Scripts')
if __name__ == '__main__':
    superset_app = create_app()
    superset_app.run(host="localhost", port = "3000",debug=True )
```

when i run it， something is wrong, like this, what should i do? Please help me,thanks!

> 1516, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "d:\xuelangyun\superset\.venv\lib\site-packages\flask\app.py", line 1492, in dispatch_request
>     self.raise_routing_exception(req)
>   File "d:\xuelangyun\superset\.venv\lib\site-packages\flask\app.py", line 1474, in raise_routing_exception      
>     raise request.routing_exception  # type: ignore
>   File "d:\xuelangyun\superset\.venv\lib\site-packages\flask\ctx.py", line 376, in match_request
>     result = self.url_adapter.match(return_rule=True)  # type: ignore
>   File "d:\xuelangyun\superset\.venv\lib\site-packages\werkzeug\routing.py", line 2042, in match    raise NotFound()werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
