### ISSUE TITLE
SQL Lab: status should be set to timeout instead of failed for timed out queries instead + end_time not set for timed out queries

### ISSUE THREAD

**Issue by simonvanderveldt** [apache/superset#21888]
When a query times out it's status is written as `failed` into the `query` table of the Superset database, this makes it impossible/difficult to distinguish timeouts from actual failures (i.e. issue in the query, crash of the SQL engine, etc).
Also `end_time` isn't set for timed out queries, making reporting on query runtimes incorrect, since the longest running ones (the ones that time out) can't be counted.

We use the query status as well as the runtimes (which we have to derive from by subtracting start_time from end_time) from the Superset database to monitor how well our Superset + SQL environment is doing. The lack of a dedicated status for timeouts makes it difficult to get an overview of how many queries are timing out.
The lack of an end_time for timed out queries means our reporting heavily skewed because the runtimes of the longest running queries can't be included in the reporting.

#### How to reproduce the bug
- Run a query that times out
- Check in the `query` table of the Superset database and notice that it's `status` column has the value `failed` instead of `timeout` (or `timed out`, whatever you prefer) and `end_time` isn't set

### Expected results
- `status` is set to `timeout` when a query times out
- `end_time` is set when a query times out

### Actual results
- `status` is set to `failed`
- `end_time` isn't set

### Environment
- Superset version: 2.0.0 (we're using the `apache/superset:2.0.0` Docker image)
- In case it matters we're using Spark Thriftserver as our SQL engine
```
FEATURE_FLAGS = {
    "SQLLAB_BACKEND_PERSISTENCE": True,
    "ENABLE_TEMPLATE_PROCESSING": True,
    "ENABLE_TEMPLATE_REMOVE_FILTERS": True,
}
```

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
