### ISSUE TITLE
Sync columns from source does not sync columns unless dataset is saved first

### ISSUE THREAD

**Issue by yeachan153** [apache/superset#21907]
In charts, editing the query of a virtual dataset and clicking `Sync columns from source` in the columns tab does not result in the columns being updated. Superset claims that the `Metadata has been synced`, which is incorrect.

In order to actually sync from the source, the dataset must first be saved after editing the query. After saving, going back to the `edit dataset` menu and clicking `Sync columns from source` correctly retrieves the new/removed/modified columns.

#### How to reproduce the bug

1. Create a virtual dataset with a custom query, and create a chart
2. Click `Edit Dataset` in the chart
3. Change the SQL and add/remove/modify columns
4. Click the lock to lock the changes to the query
5. In the columns tab, click `Sync columns from source`

### Expected results

Metadata information should be synced. This includes showing any added/removed/modified columns correctly.

### Actual results

Changes to the columns will not be reflected, but Superset will show:
![image](https://user-images.githubusercontent.com/30076090/197194882-26edfd00-9d73-416c-82c6-6708a5115047.png)

To get the desirable result, the virtual dataset must first be saved. Then, click `Edit Dataset` again and click `Sync columns from source`. This will actually refresh the metadata.

### Environment

- browser type and version: `Chrome (106.0.5249.119)`
- superset version: `2.0.0`
- python version: `3.8.12`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Since we're now on 3.1, on the verge of 4.0, we're not supporting 2.x  or prior versions actively. If anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps, or let us know to re-open this one. Thank you for understanding :)
