### ISSUE TITLE
superset v1.5.2 with mysql cannot import dashboards from csv exported from superset v1.1.0 with sqlLite

### ISSUE THREAD

**Issue by asagjj** [apache/superset#21929]
#### How to reproduce the bug

1. export dashboard from superset v1.1.0
2. import dashboard to superset v1.5.2
3. See error

### Expected results

what you expected to happen.

### Actual results
![75fd6d8bed9cdafc5cccc754d1ce16b](https://user-images.githubusercontent.com/10152847/197743172-8f7a5a0b-7988-49d7-a2e7-c3a63b3a84f2.jpg)
![image](https://user-images.githubusercontent.com/10152847/197743279-57553879-f1e7-4d8c-bdb7-6b7b042b562d.png)

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Since we're now on 3.1, on the verge of 4.0, we're not supporting 2.x  or prior versions actively. If anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)
