### ISSUE TITLE
Please help, I want to pass parameters to superset， how can i do

### ISSUE THREAD

**Issue by liuyu2013** [apache/superset#21939]
##I need to modify the data value of  the ”Upload a CSV“,such as 
```
df_empty = g.lytmp
            database.db_engine_spec.df_to_sql(
                database,
                csv_table,
                df_empty,
                to_sql_kwargs={
                    "chunksize": 1000,
                    "if_exists": form.if_exists.data,
                    "index": form.index.data,
                    "index_label": form.index_label.data,
                },
            )

```

[drag & drop image(s) here!]

## and  I use the global variable g to save the incoming value， such as 
```
def create_app(data) -> Flask:
    app = SupersetApp(__name__)
    with app.app_context():
        g.lytmp = data 
    try:
        # Allow user to override our config completely
        config_module = os.environ.get("SUPERSET_CONFIG", "superset.config")
        app.config.from_object(config_module)

        app_initializer = app.config.get("APP_INITIALIZER", SupersetAppInitializer)(app)
        app_initializer.init_app()
       
        return app

    # Make sure that bootstrap errors ALWAYS get logged
    except Exception as ex:
        logger.exception("Failed to create app")
        raise ex
```

[And when i run it, its wrong, Error message: '_AppCtxGlobals' object has no attribute 'g.lytmp', what should i do ,please help me]

## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
