### ISSUE TITLE
No cascading delete for table `public.dbs`

### ISSUE THREAD

**Issue by gforien** [apache/superset#21950]
## Context
On Superset v1 with a pgsql DB (not the default SQLite), I need to delete a connection.
I didn't find a way to do it on the UI or in the documentation, so I connected to the pgsql DB and tried to delete it directly.

What am I doing wrong ?

#### How to reproduce the bug

1. `pgsql postgres://superset:pass@my.superset:5432`
2. `superset=> DELETE FROM public.dbs WHERE id=xx;`

### Expected results

Cascading delete allows to delete a row from the `public.rds` table.

### Actual results

```
ERROR:  update or delete on table "dbs" violates foreign key constraint "query_database_id_fkey" on table "query"
DETAIL:  Key (id)=(xx) is still referenced from table "query".
```

### Environment

- superset version: `1.5.0`

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest minor released version of superset.
- [x] I have checked the issue tracker and the discussions for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long (we no longer support 2.x or prior), and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
