### ISSUE TITLE
[Report] Ambiguous error sent to report owners if selenium times out when taking a screenshot

### ISSUE THREAD

**Issue by zhaorui2022** [apache/superset#21957]
In https://github.com/apache/superset/blob/2263a76f4d97ef4f3d93e4b45a31e8c3e522e589/superset/utils/webdriver.py#L140, if it times out when taking a screenshot, TimeoutException is swallowed and it will be treated as a generic error in https://github.com/apache/superset/blob/master/superset/reports/commands/execute.py#L233. 

From users' perspective, they will see an error on the execution log but there is no error message. 

Previously there was a line `img=element.screenshot_as_png` inside the TimeoutException handling logic https://github.com/apache/superset/blob/00ca21e0161e55e9f4275cd1f59ac85df02851d3/superset/utils/webdriver.py#L144. However, doing it this way could end up with showing users errors that are not related with TimeoutException. For example, if it times out on [this line](https://github.com/apache/superset/blob/00ca21e0161e55e9f4275cd1f59ac85df02851d3/superset/utils/webdriver.py#L122), it ends up with error "trying to access a variable before initialization". [Line 144](https://github.com/apache/superset/blob/00ca21e0161e55e9f4275cd1f59ac85df02851d3/superset/utils/webdriver.py#L144) could also end up with a StaleElemenetReferenceException if it times out at a later point, and because the error is thrown inside the except block, the StaleElementReferenceException won't be caught and will eventually be surfaced to report owners.

#### How to reproduce the bug

1. Change all timeout values to a very low number to make it easier to time out when taking screenshots https://github.com/apache/superset/blob/edce57904728156312b795923019a1520147d045/superset/config.py#L587-L596
2. Create any alert or report
3. Wait for it to time out
4. Open execution log and observe the incorrect error message. Meanwhile, on the server side, a timeout exception should be logged for the same alert or report.

### Expected results

Either show a partial screenshot (components timed out are not shown properly) or show a timeout error message to users.

### Actual results

Shows a ReportScheduleScreenshotFailedError error to users without saying why exactly it fails

#### Screenshots

N/A

### Environment

(please complete the following information):

- browser type and version: not browser specific
- superset version: latest master branch
- python version: 3.8
- node.js version: N/A
- any feature flags active: ALERT_REPORTS = True

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
@zhaorui2022 I'm tempted to close this as stale (we're cleaning up the backlog) but I'm curious if this is still an issue in 3.x. We can keep it open if it's still a problem.

**Comment by rusackas** [comment]
Closing as stale, but happen to reopen if this is still an issue in 4.x.
