### ISSUE TITLE
Calling MySql Function from an Alert

### ISSUE THREAD

**Issue by backtothedesert** [apache/superset#21979]
### Discussed in https://github.com/apache/superset/discussions/21891

<div type='discussions-op-text'>

<sup>Originally posted by **backtothedesert** October 20, 2022</sup>
Good day,

I have a MySql Function which makes updates to a table, inserts a row into another table and returns an integer value.

When I call this function from Superset's MySQL lab (e.g select myfunc()), all parts of the function execute as expected.

However when the same function is called from a scheduled Alert (under Alerts and Reports), none of the update and insert functions are performed and only the the return value is returned.

I have tried granting full privileges to the supersert user in MySql with no luck; but again the most strange aspect of this is that when called from MySql Lab (using the same username) everything is fine, but not when called from an Alert.

Grateful for any assistance.

Thanks,

Ali</div>

**Comment by geido** [comment]
Hello @backtothedesert this is quite an old issue and we haven't seen any activity around it. If you are still experiencing this issue in a recent version of Superset, please feel free to open a new one. Thanks!
