### ISSUE TITLE
No alert message when trying to save dashboard properties with invalid content

### ISSUE THREAD

**Issue by sfirke** [apache/superset#21991]
## Description

I edited my dashboard properties -> Advanced to specify custom colors and I missed a comma.  It wouldn't let me hit "APPLY" to save my changes.  That's good.  But there was no alert message saying "input is currently not valid JSON.  Please correct to save your changes."  Or something like that.  It took me a while to figure out why the apply button was not functional.

I think users would benefit from an alert message and the graying out of the apply button while saving is not allowed.  The ideal error message would also identify the invalid chunk of code, if possible.

The invalid JSON looked like `"Fire": "#CE2029", "Fires": "#CE2029" "EMS": "#0000FF"`, missing a comma.

**Comment by geido** [comment]
Hello @sfirke, I just tested a similar scenario and it looks like there is an error message popping up "JSON metadata is invalid!". I am closing this issue. Thank you!

**Comment by sfirke** [comment]
Thanks for testing and for the update! I see it looks like this was fixed in #20823
