### ISSUE TITLE
Dev setup installation is failing

### ISSUE THREAD

**Issue by zweack** [apache/superset#22021]
I am following dev setup installation instructions from [here](https://github.com/apache/superset/blob/master/CONTRIBUTING.md#setup-local-environment-for-development)

`superset db upgrade` is failing with following error

```
ModuleNotFoundError: No module named 'wtforms.ext'
```

Tried installing this module using pip but error remains the same.

**Comment by sfirke** [comment]
Possible duplicate of https://github.com/apache/superset/issues/20914
