### ISSUE TITLE
custom filter not working on charts

### ISSUE THREAD

**Issue by Hammad-Raza** [apache/superset#22028]
Superset version 2.0.1rc2

Steps:

- Click on add chart button
- select any dataset and chart type
- on chart screen, click on edit date range and select 'Custom' fro drop-down menu

Expected Result
<img width="781" alt="Screen Shot 2022-11-03 at 7 44 03 PM" src="https://user-images.githubusercontent.com/15028724/199768729-020613c5-2e23-4e28-bc76-82825ccf885d.png">

Actual Result
![image](https://user-images.githubusercontent.com/15028724/199768785-4c6b1aa3-fcf6-48cd-b80d-c984fb2fcef2.png)

**Comment by Stoicode** [comment]
I have this issue as well in 2.0.1rc2

**Comment by geido** [comment]
Hello @Hammad-Raza we are not supporting Superset versions prior 3.X. I am closing this for now, but if you think this is still an issue in recent versions of Superset, please feel free to open a new one. Thank you!
