### ISSUE TITLE
Excel sheet upload throwing 500 error

### ISSUE THREAD

**Issue by yashu183** [apache/superset#22025]
I am uploading an excel sheet but superset is throwing 500 Internal Server Error
It uploads files to this directory `UPLOAD_FOLDER = BASE_DIR + "/app/static/uploads/"`
`BASE_DIR ` is the superset directory in `site-packages` but I cant find `app` directory in `superset` directory

On dev server its shown File not found error

**Comment by hanvince** [comment]
Hi, I got the same issue while uploading excel sheet to server, any solution?
