### ISSUE TITLE
PDF Download

### ISSUE THREAD

**Issue by pruthviraj529** [apache/superset#22035]
1) Is Designing PDF in the Superset is possible?
2) Other than csv what all formats we can download?
3) Is Amount/Date formatting allowed while downloading the CSV format?

**Comment by pruthviraj529** [comment]
Hi Team,

Let us know your view on the timelines and let us know the enhancements on the product.

**Comment by rusackas** [comment]
Agreed with the above comments... I just added a couple more reviewers for that open PR. I think the immediate questions here are answered. If you'd like to discuss further, please open up a Discussion in the "Ideas" category. Thanks!
