### ISSUE TITLE
Time grain is empty when temporal column is selected

### ISSUE THREAD

**Issue by BowenXiao1999** [apache/superset#22033]
The time grain is empty when temporal column is selected.

#### How to reproduce the bug

I was testing against a new database in postgresql protocol. Just find that the time grain is empty.
<img width="1505" alt="image" src="https://user-images.githubusercontent.com/36908971/199903804-948a07f4-3aa4-4aab-a721-f5731a67895c.png">

<img width="867" alt="image" src="https://user-images.githubusercontent.com/36908971/199904154-f388ac83-dccc-4162-94d7-402ec92e8447.png">

Are there something missed in my Superset setup or should be the database problem?
### Expected results

See the time grain with different options

### Actual results

The time grain is empty.

### Environment

Mac M1.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by geido** [comment]
Hello @BowenXiao1999 thanks for reporting this. We have been moving away from the temporal column in favour of generic chart axes. This issue should not affect the most recent versions of Superset (3.x), thus I am closing it for now.
