### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by nimei66** [apache/superset#22034]
superset Version: 2.0.1
![image](https://user-images.githubusercontent.com/24385081/199924279-19d74ad1-34dd-43ac-bed6-4d0aa4d1eef9.png)
![image](https://user-images.githubusercontent.com/24385081/199924372-9a382240-c109-4932-b5a4-0cbd361d0f0d.png)
![image](https://user-images.githubusercontent.com/24385081/199924413-1561d9e6-c071-48a5-b855-9fd074f21cce.png)

[object Object]

**Comment by geido** [comment]
Hello @nimei66 we are not supporting this version of Superset at this time. If you are still experiencing this problem in one of the most recent versions of Superset (3.x and above), please feel free to open another issue. Thank you!
