### ISSUE TITLE
Plotting data with different time granularity in a time series line chart does not always render the lines

### ISSUE THREAD

**Issue by GerbenvdHuizen** [apache/superset#22061]
When plotting data with hourly and daily granularity in a timeseries line chart, the lines of daily data will not render when the time grain of the chart is set to hourly. This makes it difficult to compare daily and hourly data in the same chart. We would expect to at least have an option to render lines between existing data points, despite what time grain is set.

In the example screenshot you can see the time grain is set to hourly, so the daily data points do not have a drawn/rendered line.
 
#### How to reproduce the bug

1. Create a chart timeseries line chart with both daily and hourly data (granularity).
2. Set time grain of the chart to hourly
3. The chart will only plot lines for the hourly data, and show only data points for the daily data.

### Expected results

Have an option to draw/render lines between data points despite what time grain is currently set on a graph

### Actual results

If time grain is set for example to hourly, the chart will only render lines for hourly data not for daily (or weekly, monthly etc.).

#### Screenshots

![Screenshot 2022-11-08 at 11 07 02](https://user-images.githubusercontent.com/7879764/200536526-0b1468f9-2521-4bc3-b22a-a8e17a82af85.png)

### Environment

- Superset version: 2.0.0 (we're using the `apache/superset:2.0.0` Docker image)
- In case it matters we're using Spark Thriftserver as our SQL engine

```
FEATURE_FLAGS = {
    "SQLLAB_BACKEND_PERSISTENCE": True,
    "ENABLE_TEMPLATE_PROCESSING": True,
    "ENABLE_TEMPLATE_REMOVE_FILTERS": True,
}
```

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by ashgorithm** [comment]
This is similar to this issue:
https://github.com/apache/superset/issues/4257

When there is missing data then the line is not continuous. For the line to be smooth, you need to use resample option in advanced Analytics section.

**Comment by Shazad-khan** [comment]
https://www.loom.com/share/1e0b3f96326548cd8980309da3c1845c

It is not a bug it's working as expected
