### ISSUE TITLE
Deck.gl scatter plot: point size maximum radius issue 

### ISSUE THREAD

**Issue by mike-fischer1** [apache/superset#22060]
After changing point size for maximum radius in deck.gl scatter, the points disappears.  Even after changing the value back to original maximum radius, the points will not reappear. 

### Expected results
The points can have larger maximum radius.

### Actual results
The point disappears and cannot return. 

#### Screenshots
Original
![image](https://user-images.githubusercontent.com/99682876/200533778-00306d5d-79b3-47ef-80d7-d976850286fe.png)

After change
![image](https://user-images.githubusercontent.com/99682876/200533931-92181b3d-fafd-4c31-8c45-8103359063d7.png)

Put back original value

![image](https://user-images.githubusercontent.com/99682876/200534082-889abfab-c5ec-4516-921e-4a287ec23fcb.png)

### Environment
Superset Version: 2.0
Browser Type: Chrome: Version 107.0.5304.87 (Official Build) (arm64)

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sbernauer** [comment]
I'm also running into this with Superset 1.5.3

**Comment by lydia-wu** [comment]
I am also running into this issue!!
