### ISSUE TITLE
Building superset locally and Customizing favicon

### ISSUE THREAD

**Issue by Vijay-LionOrbit** [apache/superset#22079]
I am a beginner in python. I have the task of customizing superset for our client. I need to change the favicon and other UI elements.
The problem is i have no idea how to set up the dev environment. And also no idea how to  build/start the app locally.

Any help is greatly appreciated.

**Comment by kamalkeshavani-aiinside** [comment]
You can refer to the official documentation available here: https://superset.apache.org/docs/installation/installing-superset-using-docker-compose

For further questions, you can ask in '[Discussions](https://github.com/apache/superset/discussions)' section in github or join the slack community here: https://join.slack.com/t/apache-superset/shared_invite/zt-16jvzmoi8-sI7jKWp~xc2zYRe~NqiY9Q

Please close this issue.

**Comment by Vijay-LionOrbit** [comment]
@kamalkeshavani-aiinside Thank You. FYI Slack link is not working.

**Comment by kamalkeshavani-aiinside** [comment]
@Vijay-LionOrbit Please try the below link:
https://join.slack.com/t/apache-superset/shared_invite/zt-1jp6hjzrq-H0PlFtToyLWuPiJDuRWCNw
