### ISSUE TITLE
werkzeug.exceptions.NotFound and get_screenshot() error

### ISSUE THREAD

**Issue by Rohit-pawar902** [apache/superset#22087]
werkzeug.exceptions.NotFound:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
I have simple compose the docker-compose -f docker-compose.yml up -d

And i getting this 
And 2nd one is 
get_screenshot() this method is giving error when i apply email-alert to my report then i got this

``superset_worker          | [2022-11-10 05:35:01,172: ERROR/ForkPoolWorker-7] A downstream exception occurred while generating a report: e11bc1a7-635d-4ac1-9004-6deeec9fdd96
[2022-11-10 05:36:01,197: ERROR/ForkPoolWorker-7] A downstream exception occurred while generating a report: 4b1d334b-9b57-4513-88d8-c2b1e56b6b72
superset_worker          | Traceback (most recent call last):
superset_worker          |   File "/app/superset/reports/commands/execute.py", line 217, in _get_screenshots
superset_worker          |     image = screenshot.get_screenshot(user=user)
superset_worker          |   File "/app/superset/utils/screenshots.py", line 76, in get_screenshot
superset_worker          |     self.screenshot = driver.get_screenshot(self.url, self.element, user)
superset_worker          |   File "/app/superset/utils/webdriver.py", line 111, in get_screenshot
superset_worker          |     driver = self.auth(user)
superset_worker          |   File "/app/superset/utils/webdriver.py", line 89, in auth
superset_worker          |     driver = self.create()
superset_worker          |   File "/app/superset/utils/webdriver.py", line 86, in create
superset_worker          |     return driver_class(**kwargs)
superset_worker          |   File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
superset_worker          |     RemoteWebDriver.__init__(
superset_worker          |   File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
superset_worker          |     self.start_session(capabilities, browser_profile)
superset_worker          |   File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
superset_worker          |     response = self.execute(Command.NEW_SESSION, parameters)
superset_worker          |   File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
superset_worker          |     self.error_handler.check_response(response)
superset_worker          |   File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
superset_worker          |     raise exception_class(message, screen, stacktrace)
superset_worker          | selenium.common.exceptions.InvalidArgumentException: Message: Argument --marionette can't be set via capabilities
superset_worker          | 
superset_worker          | 
superset_worker          | The above exception was the direct cause of the following exception:
superset_worker          | 
superset_worker          | Traceback (most recent call last):
superset_worker          |   File "/app/superset/tasks/scheduler.py", line 85, in execute
superset_worker          |     AsyncExecuteReportScheduleCommand(
superset_worker          |   File "/app/superset/reports/commands/execute.py", line 681, in run
superset_worker          |     raise ex
superset_worker          |   File "/app/superset/reports/commands/execute.py", line 677, in run
superset_worker          |     ReportScheduleStateMachine(
superset_worker          |   File "/app/superset/reports/commands/execute.py", line 639, in run
superset_worker          |     state_cls(
superset_worker          |   File "/app/superset/reports/commands/execute.py", line 540, in next
superset_worker          |     raise first_ex
superset_worker          |   File "/app/superset/reports/commands/execute.py", line 518, in next
superset_worker          |     self.send()
superset_worker          |   File "/app/superset/reports/commands/execute.py", line 415, in send
superset_worker          |     notification_content = self._get_notification_content()
superset_worker          |   File "/app/superset/reports/commands/execute.py", line 335, in _get_notification_content
superset_worker          |     screenshot_data = self._get_screenshots()
superset_worker          |   File "/app/superset/reports/commands/execute.py", line 222, in _get_screenshots
superset_worker          |     raise ReportScheduleScreenshotFailedError(
superset_worker          | superset.reports.comm``

uperset.reports.commands.exceptions.ReportScheduleScreenshotFailedError: Failed taking a screenshot Message: Argument --marionette can't be set via capabilities

 
**Reproduce_Bug**
simple compose the docker-compose -f docker-compose.yml up -d

**Comment by sfirke** [comment]
For the 404 error, the worker probably can't browse to the page to take the screenshot.  Try in your superset_config_docker.py:
```
WEBDRIVER_BASEURL="http://superset_app:8088"
SUPERSET_WEBSERVER_ADDRESS=WEBDRIVER_BASEURL 
```
I'm not sure that second line is needed.  If your main application container is called something other than `superset_app`, use that value instead of `superset_app`.

**Comment by Rohit-pawar902** [comment]
superset_config.py file i have to make in the same folder ,where config.py file exists or i have to make newdir/conf/ inside i have to make it .

**Comment by sfirke** [comment]
If deploying with docker-compose, I suggest doing all of your config overrides in a new file `/superset/docker/pythonpath_dev/superset_config_docker.py` - it's mentioned here, https://github.com/apache/superset/blob/master/docker/pythonpath_dev/superset_config.py#L113.

Anything in that file will override values in `superset_config.py`, which in turn will override `config.py`.  It's simplest to edit values in just that `superset_config_docker.py` and leave the others with their default values.

**Comment by Rohit-pawar902** [comment]
ok thanks i got it

**Comment by Rohit-pawar902** [comment]
superset.reports.commands.exceptions.ReportScheduleScreenshotFailedError: Failed taking a screenshot Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
