### ISSUE TITLE
Deploying with helm how to import clickhouse driver

### ISSUE THREAD

**Issue by HotPotJ** [apache/superset#22098]
Deploying with helm how to import clickhouse driver？

I found in the documentation how to add clickhouse when deploying with docker and docker-compose, but did not find how to add clickhouse driver when deploying with helm.

I try to modify the image like

```
# dockerfile
FROM apache/superset:latest
RUN pip install clickhouse-connect
```

but that doesn't seem to work

**Comment by genzgd** [comment]
The `clickhouse-connect` package does not require clickhouse-driver to work with Superset.  Once ClickHouse Connect is installed you should see `ClickHouse Connect` as one of the supported databases.  What about it doesn't seem to work?

Note that If you want to use clickhouse-driver *instead* you can install that without clickhouse-connect:

```
pip install clickhouse-driver
pip install clickhouse-sqlalchemy
```

**Comment by NikoJ** [comment]
You will need to create a `values.yaml` file where you override `bootstrapScript`. 
Example:
```yaml
...

bootstrapScript: |
  #!/bin/bash
  pip install psycopg2==2.9.1 \
    redis==3.2.1 \
    clickhouse-connect==0.5.3 &&\
  if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi

...
```

Read more [here](https://superset.apache.org/docs/installation/running-on-kubernetes/)

**Comment by jleni** [comment]
any tips wrt to 

```
2023-08-08 12:01:14,883:INFO:superset.datasets.commands.importers.v0:Importing 1 databases
Importing new dbs [pro] ClickHouse
2023-08-08 12:01:14,890:INFO:superset.models.helpers:Importing new dbs [pro] ClickHouse
Error running import command
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: can't adapt type 'dict'
```

extraConfigs:
 import_datasources.yaml: |
    databases:
    - database_name: '[pro] ClickHouse'
      sqlalchemy_uri: clickhousedb+connect://default:xxxxxxxxxx@clickhouse.yyyyyy.zz:8123/__default__
      cache_timeout: null
      expose_in_sqllab: true
      allow_run_async: false
      allow_ctas: false
      allow_cvas: false
      allow_dml: false
      allow_csv_upload: false
      extra:
        allows_virtual_table_explore: true
        cost_estimate_enabled: true
      uuid: 28c824c5-222-3333-4444-f5b177c94c8b
      version: 1.0.0

**Comment by rusackas** [comment]
Hi there, and sorry this has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale. If it is still an issue in Superset 3.x (which it may well be!), we can re-open this - just let us know. Or, feel free to open a new issue with updated context. As always, PRs are welcome from anyone to fix the issue if it still exists.
