### ISSUE TITLE
Docs: Adding Restack as a way to deploy Superset on Kubernetes

### ISSUE THREAD

**Issue by kuberaspeaking** [apache/superset#22097]
This contribution will add [Restack](https://www.restack.io) as a way to deploy Superset on k8s in your own AWS infrastructure.
I will be adding this under Documentation/Installation and Configuration next to [Running on Kubernetes](https://superset.apache.org/docs/installation/running-on-kubernetes)
I have gone through the contribution guide. 
Do let me know if you have any preferences like screenshots or no screenshots.

**Comment by geido** [comment]
Hello @kuberaspeaking as this has been inactive for a long time and we don't typically mention commercial products in our docs, I'll be closing it. Thanks for your interest in contributing to Superset!
