### ISSUE TITLE
Can't save dashboard after adding pie chart

### ISSUE THREAD

**Issue by toddlamothe** [apache/superset#22106]
I deployed Superset to AWS with the [quickstart-apache-superset](https://github.com/aws-quickstart/quickstart-apache-superset) Cloud Formation template, Superset 2.0 is running inside an ECS cluster connected to a MySql RDS database.

I created a few datasets and time series graphs, added them to a dashboard and everything works fine. After creating a simple pie chart, I opened the dashboard, added a empty row and got the following error attempting to save the dashboard:

`Sorry, there was an error saving this dashboard: [object Object]`

Note that I hadn't added the pie chart to the dashboard. Just creating the pie chart seems to cause the error in the dashboard.

If I delete the pie chart and re-start Superset, I can edit and save the dashboard, everything works again.

**Comment by rusackas** [comment]
Since we're now on 3.1, on the verge of 4.0, we're not supporting 2.x  or prior versions actively. If anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)
