### ISSUE TITLE
Create a default custom role in superset

### ISSUE THREAD

**Issue by kalyan4uonly** [apache/superset#22117]
Hi,

I am new to superset, how we can create a default custom role like gamma, alpha etc.. with specific permissions programmatically? Could anyone explain me in detail.

Thanks

**Comment by kamalkeshavani-aiinside** [comment]
For questions like this, it is suggested to use '[Discussions](https://github.com/apache/superset/discussions)' section. Also please provide more details about your question when you post there. Please close this bug.
