### ISSUE TITLE
Publish websocket container

### ISSUE THREAD

**Issue by Yann-J** [apache/superset#22126]
PR #21954 was hoping to publish a superset-websocket container to Docker Hub, but this has apparenlty not worked... Since this is really CI-related I'm not sure external contributors like myself can really fix that, so raising this as an issue instead.

See also related PR #21379, also attempting to enable image publication...

In the meantime, our organization maintains an up-to-date fork [over here]() (kept in sync using [pull app](https://probot.github.io/apps/pull/)), which has auto-builds into [this image](https://hub.docker.com/r/oneacrefund/superset-websocket/tags).

**Comment by Yann-J** [comment]
Hey @craig-rueda any idea why the websocket image isn't being published?

**Comment by Yann-J** [comment]
Oops, after looking at the logs I guess I see the problem! The image is built but not pushed... Fix on its way with #22181

**Comment by rusackas** [comment]
Fix is merged, closing issue.
