### ISSUE TITLE
Ldap Auth setup can't debug what is the problem

### ISSUE THREAD

**Issue by Rohit-pawar902** [apache/superset#22139]
**My configurations**
```
from flask_appbuilder.security.manager import AUTH_LDAP

AUTH_TYPE = AUTH_LDAP 
AUTH_ROLE_ADMIN = 'admin'
AUTH_USER_REGISTRATION = True 
AUTH_LDAP_SERVER = "ldap://localhost:389"
# AUTH_LDAP_SEARCH="ou=people,dc=superset,dc=com"
AUTH_LDAP_SEARCH= "cn=admin,dc=ramhlocal,dc=com"
# AUTH_LDAP_APPEND_DOMAIN = "XXX.com"
AUTH_LDAP_UID_FIELD="cn"
AUTH_LDAP_FIRSTNAME_FIELD= "Rohit"
AUTH_LDAP_LASTTNAME_FIELD= "sn"
AUTH_LDAP_USE_TLS = False

AUTH_LDAP_BIND_USER= "ou=people,dc=superset,dc=com"

AUTH_LDAP_ALLOW_SELF_SIGNED= True
AUTH_LDAP_APPEND_DOMAIN= False

```

**Expected results**
It will make me log onto superset by using ldap user.

**Actual results**
I can't log to superset by normal password as well the ldap one password. 
And I can be able to debug because no error came related to ldap.

**Environment**
- superset version: `superset-2.0.0-dev`

**I already did**
I install the python-ldap package in my container.

Just I want a way to get **logs** of what i am making wrong , yet i can't get any msg related to ldap in all container logs .
Any way

**Comment by parkjiyeon0** [comment]
I'm a beginner and I've built in docker-compose, what can I do?

**Comment by Rohit-pawar902** [comment]
@parkjiyeon0  
What is the problem just run it!

**Comment by Rohit-pawar902** [comment]
For Ldap problem anyone can Refer this :- 

```
from flask_appbuilder.security.manager import AUTH_LDAP

AUTH_TYPE = AUTH_LDAP 
AUTH_ROLE_ADMIN = 'admin'
AUTH_USER_REGISTRATION = True 
AUTH_LDAP_SERVER = "ldap://xxxx/389"
AUTH_LDAP_SEARCH= "dc=xxx,dc=io"
AUTH_LDAP_UID_FIELD="cn"
AUTH_LDAP_FIRSTNAME_FIELD= "admin"
#AUTH_LDAP_LASTTNAME_FIELD= "sn"
AUTH_LDAP_USE_TLS = False

AUTH_LDAP_BIND_USER = "cn=admin,dc=xxxx,dc=io"
AUTH_LDAP_BIND_PASSWORD = "your main password for login in ldap"
```
Might need for installing dependency inside the container

sudo apt-get install python-dev libldap2-dev libsasl2-dev libssl-dev
sudo pip install python-ldap


#13836

**Comment by parkjiyeon0** [comment]
@Rohit-pawar902 Thanks
