### ISSUE TITLE
[Chart] Area chart ignores null values

### ISSUE THREAD

**Issue by zhaorui2022** [apache/superset#22146]
Currently area chart ignored null values. 

For users who is trying to track null values, additional processing on the dataset is needed (currently the workaround is changing null values to string "null"s). 

Ideally we should treat null values as valid values. And for the use cases where null values are supposed to be ignored, we can still use filters to achieve it.

#### How to reproduce the bug

1. Add a dataset with null values in at least one columns
2. Create an area chart using that dataset
3. Observe null values are being ignored

### Expected results

null values are being considered and visualized

### Actual results

null values are being ignored

#### Screenshots

N/A

### Environment

(please complete the following information):

- browser type and version: not browser specific 
- superset version: 2.0.0
- python version: 3.8
- node.js version: N/A
- any feature flags active: N/A

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by Shazad-khan** [comment]
![image](https://user-images.githubusercontent.com/100838455/225593466-1568204f-f3fb-4142-9636-c843f1a29390.png)

It is working as expected please recheck it and close the issue

**Comment by rusackas** [comment]
Closing. Note that you can also use Advanced Analytics to do zero imputation on null values.
