### ISSUE TITLE
[deck.gl] dashboard view is repositioned when deck.gl chart legend category is clicked

### ISSUE THREAD

**Issue by dkrat7** [apache/superset#22159]
Deck.gl charts with legend (tested with scatter and polygon) get out of visual scope when legend category is clicked (on dashboards that don't fit screen).

#### How to reproduce the bug

1. Open the dashboard with deck.gl visualization (i.e. Deck.gl demo).
2. Scroll down to the deck.gl chart (issue is only visible when dashboard doesn't fit screen)
3. Click (select/deselect) legend category

### Expected results

Legend category is filtered and **dashboard view stays in the same position**.

### Actual results

Legend category is filtered and **dashboard is scrolled to the top**.

#### Screenshots

https://user-images.githubusercontent.com/9586713/202557683-e7d1dfbd-a951-4dc7-a7ea-5e1446057b13.mp4

### Environment

(please complete the following information):

- browser type and version: firefox 106, chrome 107
- superset version: 2.0.0 (official docker image: apache/superset:2.0.0)

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
It seems this is still an issue in 3.x, but based on the lack of conversation here, I'm not sure anyone is worried about it. If anyone wants to raise a PR, please do, otherwise we may mark this as stale and close it.

**Comment by rusackas** [comment]
Not sure if this is still an issue in 4.x, but it seems this thread has gone quite cold, so I'll close it as stale. Holler if anyone wants to tackle this, and we can revisit/reopen.
