### ISSUE TITLE
Some charts (Pivot Table) suddenly error. Cannot use 'View chart in Explore' for the whole dashboard.

### ISSUE THREAD

**Issue by LeoDiep** [apache/superset#22161]
Hi everyone,
 I am using Superset version 1.5.0 on AWS EC2 Linux and connect to AWS Athena to query database, python 3.8. It's been okay for 5 months and suddently I got this problem yesterday.

When go to the dashboard or hit F5 to refresh, there is a notification on the bottom right said 'Error loading chart datasources. Filters may not work correctly.'
![image](https://user-images.githubusercontent.com/99783557/202614147-3a38466e-c5df-4124-9707-97b7578fecc3.png)

One of my dashboard has several charts appear error to load (only Pivot Table chart). 'Unexpected error: An error occurred while rendering the visualization: TypeError: Cannot read properties of undefined (reading 'Num. of Deal')  -- 'Num. of Deal' is the name of metric'
![image](https://user-images.githubusercontent.com/99783557/202614330-8e518260-937e-4355-9c5b-b2d87f899beb.png)

Plus, in the error dashboard I cannot use 'View chart in Explore', including normal charts which are not error. Notification appear said: 'An error occurred while opening Explore'.
![image](https://user-images.githubusercontent.com/99783557/202614421-fac1de30-e13d-431a-ac14-ba5e80eb25de.png)

### Additional context
- I ran  '1 week ago' back up version of the Superset in another EC2 and all dashboards work well, there is no error at all. 

- I have tried remove all the filter of the error dashboard, didn't solve the problem. I deteled error charts from that dashboard, didn't solved the problem too. 

- I tried deleting the dataset of error pivot table and create a new one, visualize it as Pivot Table then it work on another dashboard. But when bring it to the error dashboard, the error occur again.  If I try visualize that dataset as Pivot Table v2, it can appear on the error dashboard, but the 'View chart in Explore' function still didn't work.

- Other dashboard are normal with no error. Other Pivot Table charts on other dashboards are also normal.

Please help me fix it. Thank you so much.

**Comment by LeoDiep** [comment]
Just found out that there is 1 chart in this dashboard which I modified dataset earlier causing this problem. By deleting that chart out of the dashboard, then the dashboard become normal. 

I created new dataset with the same query as the faulty dataset and put it back in the dashboard, it works normal.
Still don't know what make that dataset become faulty and causing the problem

**Comment by sfirke** [comment]
Interesting, thanks for following up.  I had a user with Gamma role report today that he is getting "An error occurred while opening Explore" when he tries to edit any chart on a dashboard.  He thinks he used to be able to edit them.

I did recently update from 2.0.0 -> 2.0.1 and didn't run `superset init` which I saw mentioned in another Github issue ... but all of my roles are there and look good so I don't think that's related.

I made him an owner of the chart's dataset and that solved it for him and this case 🤷

**Comment by LeoDiep** [comment]
@santosh-sahoo334 
I also faced a lot of errors when I upgraded my Superset from v0.28.1 to 1.5.0, so I decided to recreate all dashboards (same Athena data source) on Superset v1.5.0 new. It takes a while but I didn't have to fix errors that I couldn't fix so it's worth it.

I guess in your case, if after spending time fixing it with no success, you should probably recreate that dashboard instead of importing it.

**Comment by santosh-sahoo334** [comment]
Thanks much @LeoDiep. Yeah. seems like some compatibility issue between the versions. I tried creating a separate dashboard (though its painful to create 70 charts :) ), its fine. So finally decided to create a new one from scratch.

**Comment by rusackas** [comment]
This is likely fixed by now, but is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
