### ISSUE TITLE
In the line chart, the legend does not preserves the order of metrics

### ISSUE THREAD

**Issue by M1s4k1** [apache/superset#22162]
#### How to reproduce the bug

1. set the query metrics in the line chart
2. as shown here
3. view the Legend

### Expected results

preserve query metrics order in Legend

### Actual results

In alphabetical order.
In a bar chart, the legend preserves the order, But in the line chart, the legend is reordered

#### Screenshots
![WX20221118-151319](https://user-images.githubusercontent.com/34932975/202647194-22906d30-2d84-4165-b854-6ae44fc93d53.png)

### Environment

chrome 107.0.5304.110
superset 0.7.7

**Comment by rusackas** [comment]
THe linked PR seems to be in need of discussion and touch-up, and this issue hasn't seen any action for well over a year. I'll close this as stale for now, but we can revisit/reopen this issue and/or the PR at any time if this is still an issue in Superset 3.x.
