### ISSUE TITLE
Don't working export dashboard by API in last master branch

### ISSUE THREAD

**Issue by mikri2017** [apache/superset#22191]
I have error when export dashboard by API:

```
import requests

url = "http://test-spsetdev.local:8088/api/v1/dashboard/export/"

params = {
    'q': 34
}

res = requests.get(url, params=params)
```

Receive error:
`{"message":"Not a valid rison schema 34 is not of type 'array'\n\nFailed validating 'type' in schema:\n    {'items': {'type': 'integer'}, 'type': 'array'}\n\nOn instance:\n    34"}`

Also, this error in swagger:
`http://test-spsetdev.local:8088/api/v1/dashboard/export/?q=%5B%2234%22%5D`

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
