### ISSUE TITLE
Pivot Table v2 does not occupy full width of chart box on dashboard

### ISSUE THREAD

**Issue by sfirke** [apache/superset#22198]
#### How to reproduce the bug

I create a Pivot Table v2 and put on dashboard.  It only occupies a small portion of the chart area I allot when I expect it to expand to fill the full width.

In edit mode:
![image](https://user-images.githubusercontent.com/7569808/203394838-9486df6d-247b-44f8-bfd7-48c751336522.png)

Display:
![image](https://user-images.githubusercontent.com/7569808/203395634-e3bd2cdc-d251-4592-b9c4-9c253e55a707.png)

### Environment

- browser type and version: Firefox 102
- superset version: 2.0.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by talk2morris** [comment]
why has this not reflected in the source, I installed superset just last month and the pivot table issue is still there

**Comment by sfirke** [comment]
What version are you running?  If you click on the associated PR https://github.com/apache/superset/pull/23393, you'll see it merged in and is included in 2.1.1rc1.  If you're running `latest` you should see this, if you're running 2.1.0 you'll need to upgrade to 2.1.1 when it's released (soon).

**Comment by sfirke** [comment]
Fixed in 2.1.1rc1 so closing this.
