### ISSUE TITLE
Echarts BarChartv2 - Incorrect tick label for final tick on Time Axis

### ISSUE THREAD

**Issue by cwegener** [apache/superset#22202]
In the Echarts Bar Chart v2, the tick label value for the final tick on the time axis is incorrect.

#### How to reproduce the bug

1. Go to dataset 'birth_names'
2. Click on 'Time series bar chart v2'
3. Drag 'sum__num' metric into the metric field
4. Click on create chart
5. See error

### Expected results

Final tick label string should be '2008'

### Actual results

Final tick label string is '23:27:17'

#### Screenshots

See comparison between Bar Chart v2 and Line Chart v2.

**Bar Chart** (Not as expected)

https://user-images.githubusercontent.com/2950544/203458501-d47d06f1-79cf-421a-b94e-6249e90e1c7e.mp4

### Environment

(please complete the following information):

- browser type and version: Firefox 107
- superset version: master (2022-11-23)
- python version: 3.10.8
- node.js version: 16.9.1
- any feature flags active: None (all default)

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by bonamim** [comment]
The same issue ⚠️ 

### Environment

- browser type and version: Chrome (Version 104.0.5112.101)
- superset version: `superset version` 2.0.0
- any feature flags active:
  - ENABLE_TEMPLATE_PROCESSING

**Comment by rusackas** [comment]
This one doesn't seem to be an issue any more:

<img width="685" alt="image" src="https://github.com/apache/superset/assets/812905/61109395-70c4-4fac-a335-02d7b6705eb8">
