### ISSUE TITLE
An error occurred while opening Explore

### ISSUE THREAD

**Issue by Max-beep** [apache/superset#22228]
We just upgraded our superset from 1.4 to 2.0.
This error occurs to all charts when we click on 'edit chart' in the dashboards. 
![image](https://user-images.githubusercontent.com/52082519/204052363-2c3d518e-764c-4e77-b0a1-3d75fe03e222.png)

**Comment by rusackas** [comment]
Can you provide any errors you might be seeing in the browser's console, or any other context (i.e. is this happening with every chart, in every dashboard?)

**Comment by Max-beep** [comment]
thanks for the reply, our issue has been solved.

**Comment by vinaybabunaidu** [comment]
@Max-beep how did u resolve the issue.
I am facing the same error

**Comment by sfirke** [comment]
See also https://github.com/apache/superset/issues/22228.

@vinaybabunaidu was yours after upgrading versions?  I wonder if @Max-beep's issue was the same as this: https://github.com/apache/superset/issues/19990.
