### ISSUE TITLE
Unable to access Filter Box Chart from a custom role on Superset

### ISSUE THREAD

**Issue by KarthikGhorpade** [apache/superset#22227]
I have created a dashboard with multiple visual reports, and I am trying to add a 'Filter Box' Chart to the dashboard. I am able to access and use the filter when using the dashboard with the 'Admin' role but unable to figure out the permission to be provided for a different custom role in order to provide the ability to use this Filter Box chart. 

Currently, when trying to access this chart from the custom user role, the filter box says 'Unexpected error' and "Access is Denied" when trying to probe further.

Please find below the 2 snips showing the filter box chart when accessed from Admin and the custom user role respectively.

![1](https://user-images.githubusercontent.com/100119407/203986457-973b3641-5be3-41e2-9498-772c7cecc010.jpg)
Admin View

![2](https://user-images.githubusercontent.com/100119407/203987160-f312bad4-4066-466c-b40a-7fdaba934048.jpg)
Custom Role User View

The permissions provided to the Custom Role is as follows:

![3](https://user-images.githubusercontent.com/100119407/203986728-e89b2de3-7fd6-4ea9-82e4-0884b2762234.jpg)

Please help with providing the appropriate permission so as to enable access to the filter box chart.

Note: The same user is able to access the filter box chart when provided with the 'Gamma' role.

**Comment by rusackas** [comment]
Not sure if @john-bodley knows anyone that can support FilterBox at a time like this, but the filter box is on a long path toward deprecation, as voted in by a recent SIP. Can Dashboard Native Filters support your workflow instead? If so, I'm hopeful we can close this issue out rather than put much engineering effort into the old FilterBox. 🤞

**Comment by IbrahimElkadiSpryker** [comment]
I had the same issue, and by looking at the API calls fired when loading the dashboard, the missing permission was the `can explore json on superset`. Adding it to the role seems to fix this issue.

**Comment by KarthikGhorpade** [comment]
@IbrahimElkadiSpryker Thanks! Let me check on this.

**Comment by rusackas** [comment]
Sounds by the thread like the issue might have been solved, and the FIlterBox is being removed as part of the forthcoming 4.0 release. I'll close this out, but feel free to reopen if there's something that can be addressed for legacy versions.
