### ISSUE TITLE
addAlpha is not to be rgb(x,x,x)

### ISSUE THREAD

**Issue by ruijielou** [apache/superset#22241]
```typescript
export function addAlpha(color: string, opacity: number): string {
  // opacity value should be between 0 and 1.
  if (opacity > 1 || opacity < 0) {
    throw new Error(`The opacity should between 0 and 1, but got: ${opacity}`);
  }
  // the alpha value is between 00 - FF
  const alpha = `0${Math.round(opacity * 255)
    .toString(16)
    .toUpperCase()}`.slice(-2);
  return `${color}${alpha}`;
}
```
This method does not take rgb color conversion into account, which will lead to incorrect results, such as' rgb (209124178) 98 ';

**Comment by rusackas** [comment]
@ruijielou are there any implementations of this method that are resulting in a known issue? As far as I can see, this is used only with hex colors in the codebase right now. Unless this is a bug, I'd be more inclined to call this a feature request. Of course, it might not be rocket science to either support RGB(A) colors in this function, or add an extra color utility for `rgbToHex`, so you can `addAlpha(rgbToHex(someHex),someAlpha)`. Happy to discuss further, or re-open this if something is broken, but I'm going to politely close it for now in hopes that everything is working :D

**Comment by ruijielou** [comment]
Yes, I have tried to solve it with rgbToHex (someHex) method

> @ruijielou are there any implementations of this method that are resulting in a known issue? As far as I can see, this is used only with hex colors in the codebase right now. Unless this is a bug, I'd be more inclined to call this a feature request. Of course, it might not be rocket science to either support RGB(A) colors in this function, or add an extra color utility for `rgbToHex`, so you can `addAlpha(rgbToHex(someHex),someAlpha)`. Happy to discuss further, or re-open this if something is broken, but I'm going to politely close it for now in hopes that everything is working :D
