### ISSUE TITLE
error getting credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY`

### ISSUE THREAD

**Issue by anas1509** [apache/superset#22259]
I'm facing the below issue just after I try to run the container with docker compose, here is a screenshot of it

![Screenshot 2022-11-29 123628](https://user-images.githubusercontent.com/67197816/204493102-75ece4f3-edb9-4bee-9ad1-dc565af2aadc.png)

Appreciate your support and thanks a lot.

**Comment by rusackas** [comment]
Hi there,

I'm curious what you've already tried to mitigate this error. A quick google turns up several results, [this one](https://anto.online/guides/cannot-autolaunch-d-bus-without-x11-display/#:~:text=What%20is%20the%20solution,need%20to%20install%20two%20applications.) being the first. I'm curious if this helps resolve the issue, but if not, I'll try to assist further.
