### ISSUE TITLE
When are opened superset iframe (as embedDashboard) and superset ui in different tabs, one of them is off.

### ISSUE THREAD

**Issue by alekssakovsky** [apache/superset#22281]
#### How to reproduce the bug

1. Go to 'one of page with embedDashboard'
2. Go to '.../superset/welcome/'
![image](https://user-images.githubusercontent.com/39739131/204879123-13ce387f-89ff-4dee-a7fa-20582a2b9ff4.png)

### Expected results

both work

**Comment by rusackas** [comment]
I suspect this is some configuration error if we're not getting lots of reports about this, but I think we'll need more details on this report. Curious if @lilykuang or @cwegener have seen this before, or know the right questions to ask here :)

**Comment by cwegener** [comment]
I'm not quite grasping the core of the question either.

**Comment by rusackas** [comment]
@alekssakovsky please let us know if you can provide some clarity, otherwise we might close the issue for lack of understanding the issue's intent and repro steps.

**Comment by alekssakovsky** [comment]
it's very strange but last week it didn't work when I opened superset UI and superset with embedded-sdk. If it repeat I'll open issue again
