### ISSUE TITLE
[Translations] Lots of console warnings in embedDashboard

### ISSUE THREAD

**Issue by alekssakovsky** [apache/superset#22282]
## Screenshot
![image](https://user-images.githubusercontent.com/39739131/204879514-c8f46560-3469-4a04-88a1-1b6ea30f2287.png)

**Comment by rusackas** [comment]
This is still true, but it doesn't seem to be causing any bugs/issues. There are a lot of cleanup efforts going on in linting/warnings, and we'd welcome some investigation and a PR.
