### ISSUE TITLE
in embedDashBoard doesn't work debug mode.

### ISSUE THREAD

**Issue by alekssakovsky** [apache/superset#22283]
I use embedded-sdk": "^0.1.0-alpha.7", when I set flag "debugMode" in true I doesn't see any debug information in browser console.

**Comment by rusackas** [comment]
Hi @alekssakovsky please elaborate with a description of the error, reproduction steps, version of Superset you're running, things you might have tried tor resolve the issue, etc., or we'll be forced to close this issue. Thanks!

**Comment by alekssakovsky** [comment]
I use embedded-sdk": "^0.1.0-alpha.7", when I set flag "debugMode" in true I doesn't see any debug information in browser console.

**Comment by rusackas** [comment]
@alekssakovsky is this still an issue?

**Comment by rusackas** [comment]
I guess it's not still an issue... or at least it's not getting much attention. Please feel free to try `#embedding-superset` on [slack](http://bit.ly/join-superset-slack) to find more help, or open a GitHub discussion.... or we can always revisit/reopen this report :)
