### ISSUE TITLE
Error importing default assets

### ISSUE THREAD

**Issue by adimyth** [apache/superset#22298]
There's an error with one of the preloaded charts (`Multi_Line_69.yaml`). This particular chart does not have a dataset attached to it. Hence exporting & importing default assets fail

#### How to reproduce the bug

1. Simple export all assets using the `/api/v1/assets/export/` api
2. Try importing the exported zip file using the `/api/v1/assets/import/` api

### Expected results
Successful import of the exported dashboards

### Actual results
Importing throws an error -

Curl Request
```bash
curl -X 'POST' \
  'http://localhost:8088/api/v1/assets/import/' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'bundle=@sample-dashboard.zip;type=application/zip' \
  -F 'passwords={"databases/examples": "superset"}'
```

Error Response
```json
{
  "errors": [
    {
      "message": "Error importing assets",
      "error_type": "GENERIC_COMMAND_ERROR",
      "level": "warning",
      "extra": {
        "charts/Multi_Line_69.yaml": {
          "dataset_uuid": [
            "Missing data for required field."
          ]
        },
        "issue_codes": [
          {
            "code": 1010,
            "message": "Issue 1010 - Superset encountered an error while running a command."
          }
        ]
      }
    }
  ]
}
```

#### Screenshots
Notice in the screenshot below that the chart is missing the `dataset_uuid` field
![Screenshot 2022-12-01 at 1 59 20 PM](https://user-images.githubusercontent.com/26377913/205003718-ba0b6735-ff37-4af8-a0e8-ea8cb411edbf.png)

### Environment

(please complete the following information):

- browser type and version: Chromium

### Checklist
Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
