### ISSUE TITLE
ERROR:flask_appbuilder.security.sqla.manager:DB Creation and initialization failed: (psycopg2.OperationalError) could not translate host name "db" to address: Name or service not known

### ISSUE THREAD

**Issue by nagarajmmu** [apache/superset#22375]
Hi Team

I have installed a superset latest version using Docker in Linux (Centos) machine.
When I tried to run superset by below docker command, it worked fine, and I am able to login to superset
--docker-compose -f docker-compose-non-dev.yml up

But when I tried to run the below docker command, it gave me ERROR: flask_appbuilder.security.sqla.manager:DB Creation and initialization failed: (psycopg2.OperationalError) could not translate host name "db" to address: Name or service not known
--docker-compose -f docker-compose.yml up

#### How to reproduce the bug
1. download the superset from git URL: https://github.com/apache/superset.git
2. run commandto run superset: docker-compose -f docker-compose.yml up
3. in log, I am able to see error: DB Creation and initialization failed: (psycopg2.OperationalError) could not translate host name "db" to address: Name or service not known
4. also this keep repeating in log.

### Expected results
Superset should up and running and user should be able to login.

#### Screenshots
![image](https://user-images.githubusercontent.com/61146310/206593159-729c7ae6-41d6-4e81-9fec-b60bf95e1b0b.png)

### Environment

superset version: 0.0.0-dev (Latest)
python version: 3.8

Please let me know, how to resolve this issue.

Thanks
Nagaraj M M

**Comment by nagarajmmu** [comment]
Hi AIl

This issue resolved automatically, when I install Superset in Ubuntu machine and run Superset with below command.
_docker-compose -f docker-compose.yml up_

It will take long time to setup, around one hour or more, but work successfully.

Thanks
Nagaraj M M

**Comment by rusackas** [comment]
Closing since this appears to be resolved! Thanks for following up with the explanation of _how_ you resolved it, as well.
