### ISSUE TITLE
Edit dataset button is disabled after superset upgrade to 2.0

### ISSUE THREAD

**Issue by prasadpatunkar** [apache/superset#22385]
I upgraded superset from 1.4.0 to firstly 1.5.0 and then 2.0.0

When I upgraded to 2.0.0, as a Admin, option to Edit Dataset is disabled (greyed out) when I am on Edit Chart Page.
But when I go to Datasets and try to Edit, I am able to Edit the datasets.

Is there a feature flag or permission to fix this issue ?

**Comment by rusackas** [comment]
Can you test out the new 2.0.1rc5 (currently up for a vote) and let us know if this issue persists? If so, I'm sure @eschutho and/or @AAfghahi might be interested in recruiting some help to fix it for this to get into a 2.0.2 release.

**Comment by rusackas** [comment]
CC @lyndsiWilliams

**Comment by prasadpatunkar** [comment]
Hi @rusackas , we looked at the code from Git repository and found that - 
line 242 needs improvement- 
https://github.com/apache/superset/blob/2.0/superset-frontend/src/explore/components/controls/DatasourceControl/index.jsx

The Admin user is not included in the Editallow permission. OR clause is missing.

Can somebody please make the update and share the tag ?

Thanks.

**Comment by rusackas** [comment]
@prasadpatunkar Would you be willing to open up a PR? You might beat us to this one :D

**Comment by prasadpatunkar** [comment]
@rusackas , can you please mention which branch I raise PR ?
Usually PR is created against master branch and master branch already has thing change incorporated.

**Comment by rusackas** [comment]
I might be a little confused here... 

If the fix you are seeking is already incorporated into `master`, then the work is done and we should close this issue (a link here would be appreciated)

If you're looking to author a code change, you can fork the repository, create your own branch, and open a pull request against `master`. When the PR is open, link it here, and we'll see it through.

Thanks either way!

**Comment by mayurnewase** [comment]
this regression was added by https://github.com/apache/superset/pull/20296 in 2.0 (this is weird patch, there was a discussion on this and was added without tests.)

was fixed on master by https://github.com/apache/superset/pull/20613

this patch should be included in next releases.
