### ISSUE TITLE
Superset Table UI unusable with infinite scrollbar flashing

### ISSUE THREAD

**Issue by opqpop** [apache/superset#22393]
https://user-images.githubusercontent.com/5566843/207159358-9e2fba12-0cda-405a-9e56-4801387c0748.mov

See video where both vertical and horizontal scroll for the table is flashing initially, but is sometimes fixed when we click "Aggregate" and then switch back to "Raw Records". Doesn't always fix it however

#### How to reproduce the bug

Go to any Superset Table UI and select a column, then scrollbar starts flashing

### Expected results

No flashing

### Actual results

See video

### Environment

(please complete the following information):

- browser type and version: Chrome Version 107.0.5304.110 (Official Build) (arm64)
- python version: `python --version`: Python 3.10.8
- any feature flags active: none

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Pinging @lauderbaugh and @kgabryje for a little triage/repro/troubleshooting on this one.

**Comment by rusackas** [comment]
@opqpop are you seeing this issue in Explore only, or in the Dashboard view too?

And is it happening with any other chart types, or just the Table?

**Comment by sfirke** [comment]
Thanks for reporting this, I had meant to.  A teammate and I can both reproduce it on some of our charts.  We opened the developer tools in the browser (Chrome and Firefox) and could see the page code changing as the chart flickered.

**Comment by opqpop** [comment]
> @opqpop are you seeing this issue in Explore only, or in the Dashboard view too?
> 
> And is it happening with any other chart types, or just the Table?

ah sorry for the delayed reponse, I see it in Explore only

Only seeing the issue for Tables

**Comment by rusackas** [comment]
Out of curiosity, are you using a PC with Chrome? And did your table chart have the "Show Totals" checkbox enabled? If so, I just merged a PR that _might_ fix this. Please check the latest `master` and see if this resolves your issue.

**Comment by sfirke** [comment]
> is sometimes fixed when we click "Aggregate" and then switch back to "Raw Records". Doesn't always fix it however

This sounds sketchy but I can 100% replicate this.  I am sitting here with my table chart in 2.0.1rc6 and clicking back and forth between Aggregate and Raw Records.  Sometimes it flashes after changing that, sometimes it doesn't.

**Comment by opqpop** [comment]
> Out of curiosity, are you using a PC with Chrome? And did your table chart have the "Show Totals" checkbox enabled? If so, I just merged a PR that _might_ fix this. Please check the latest `master` and see if this resolves your issue.

I'm using a mac to access our superset instance that's hosted on

I'm having trouble finding the "Show Totals" checkbox, where can I find it?

**Comment by frabenetti** [comment]
Hi all, I have the same issue.
Windows 11, Chrome Version 109.0.5414.75 (Official Build) (64 bit) and of course MS Edge. It does not happen with Firefox Version 109 (64-bit).

**Comment by frabenetti** [comment]
hi all, just testing around this issue. It seems related to the **vertical scroll bar,** if you enlarge the the window till the bottom, it stops flashing. Hope this helps.

**Comment by rusackas** [comment]
Closing in favor of https://github.com/apache/superset/issues/22784 which includes a link to the fix PR, https://github.com/apache/superset/pull/20833.

Thanks @sfirke for the duplication alert, and thanks @Antonio-RiveroMartnez for the fix!
