### ISSUE TITLE
Handlebars Chart: ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by molschimke2** [apache/superset#22402]
An error is shown whenever a handlebars chart should be configured.

#### How to reproduce the bug

1. Create a new dashboard and dataset
2. add handlebars chart
3. Configure the handlebars chart with some metrics
4. Hit preview

### Expected results

the handlebars chart should present the rendered script

### Actual results

error message is shown:

"Unexpected error
An error occurred while rendering the visualization: ReferenceError: exports is not defined"

#### Screenshots

![2022-12-13_01-19-20](https://user-images.githubusercontent.com/81193827/207194469-6d82495f-98b5-484c-82d3-ec4466a67fe3.png)

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: latest
- python version: not sure
- node.js version: not sure
- any feature flags active: not sure

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Which version of Superset are you using? This should be addressed in the 2.0.1rc5 release candidate, or on the current `master` branch. Let me know if you find otherwise.

**Comment by rusackas** [comment]
Assuming this is fixed... it should be, in current versions. Correct me if I'm mistaken :)
