### ISSUE TITLE
LDAP:AUTH_USER_REGISTRATION NOT WORKING

### ISSUE THREAD

**Issue by ljclour** [apache/superset#22403]
----
i deployed Superser with Docker-Compose,and want to login in and authory with ldap.
Thus I install slapd on my Ubuntu Server,my `superset_config.py` like 
----
#AUTHENTICATION FONFIG
104 AUTH_TYPE = AUTH_LDAP
105 AUHT_USER_REGISTRATION = True
106 AUTH_USER_REGISTRATION_ROLE = "Alpha"
107 AUTH_LDAP_UID_FIELD = "cn"
108 AUTH_LDAP_FIRSTNAME_FIELD = "givenName"
109 AHTU_LDAP_LASTNAME_FIELD= "sn"
110 AUTH_LDAP_EMAIL_FIELD = "mail"
112 AUTH_LDAP_SERVER = "ldap://xxxxxx:389"
114 AUTH_LDAP_SEARCH = "cn=%s,ou=groups,dc=xx,dc=xx"
-----
With the above configuration,I can login wiht ldap user，but already in Superset.It is Seem that  `AUHT_USER_REGISTRATION = True' not working.Because when login with the user both in ldap and Superset, ldap can verify the password.
If the user not in Superset,it can not login.

Thank you from the bottom of my heart for your help or advices

**Comment by ljclour** [comment]
User in Superset
![image](https://user-images.githubusercontent.com/45123712/207219571-a695d685-6bec-4e90-997b-6793a5fe4c98.png)
---
User in ldap
![image](https://user-images.githubusercontent.com/45123712/207219782-e0ed2c71-054c-4af8-856a-09b888aa0211.png)
---
i can login when use admin,test1 or test2, but test3 just failed.

**Comment by ljclour** [comment]
ldap logs output like this when login with test1,but when login with test3,there is noting came out.
![image](https://user-images.githubusercontent.com/45123712/209790369-c8dcba1f-8542-4e2d-b5c9-0f58c0f0f48f.png)

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
