### ISSUE TITLE
Handlebars doesn't work anymore

### ISSUE THREAD

**Issue by zufolo441** [apache/superset#22410]
Hi all, 
I'm using a lot the new handlebars from 2.0
Now, I downloaded latest git, and it doesn't work anymore.
I' obtain empty text with CSS content, or html tags.
Please see attachments.
![Screenshot_20221213_145216](https://user-images.githubusercontent.com/45826835/207347117-d5ee4a11-03d9-4a1a-b772-1d814ac279f2.png)
![Screenshot_20221213_145150](https://user-images.githubusercontent.com/45826835/207347131-ea82ea28-c0ef-440f-97e2-9126ba07b8c0.png)

**Comment by michael-s-molina** [comment]
Fixed by https://github.com/apache/superset/pull/22417
