### ISSUE TITLE
Superset deployment for production with docker

### ISSUE THREAD

**Issue by anas1509** [apache/superset#22425]
I had clone and configure superset locally but I can't see any instructions how to deploy it using docker for production environment.
Just looking for basic instructions and best practices!  

Appreciate your support and thanks a lot.

**Comment by kamalkeshavani-aiinside** [comment]
For any questions, please use the '[Discussions](https://github.com/apache/superset/discussions)' section and close this issue.

**Comment by anas1509** [comment]
Okay, Thanks a lot.

**Comment by anas1509** [comment]
move this issue to the Discussion
