### ISSUE TITLE
docker build failed

### ISSUE THREAD

**Issue by yashu183** [apache/superset#22429]
I cloned the official github repo and I want to build the docker file. So I executed `docker build .`
It was failing on `npm run build` in `superset-node` container

#### How to reproduce the bug

1. clone the officila github repo
2. cd superset
3. Run `docker build .`

### Expected results

I should see the image that I built 

### Actual results

<img width="946" alt="Screenshot_20221214_030522" src="https://user-images.githubusercontent.com/70622860/207841864-99b86a45-ab33-4e97-9ebc-1bfc694ca500.png">

**Comment by rusackas** [comment]
In your [other issue](https://github.com/apache/superset/issues/22428) you said you were building a custom image. Is there anything particularly custom you've done with Superset that we should be aware of?

**Comment by yashu183** [comment]
No,
I jst want to download chart as xlsx instead of csv
This is the only thing I have changed

**Comment by rusackas** [comment]
Currently, I have to suspect that the changes you've made are somehow tied into this problem. I've tested building the docker image on the latest `master` and it seems to be working just fine. Please let me know if you have issues building the docker image with the stock code, and we can re-open this. Alternatively, if you want to open a PR with your mods to allow XLSX download, we might be able to troubleshoot the issue there and help add a feature for others to use! Thanks either way!

**Comment by yashu183** [comment]
Continuing our convo on slack,

I started `docker build .` on the master branch
<img width="948" alt="Screenshot_20221216_120919" src="https://user-images.githubusercontent.com/70622860/208039349-4761a36b-a4d4-4e2d-b681-483304a0e5cb.png">
I got error while executing `npm run build` ( same step failed while executing in `superset-frontend` dir
<img width="948" alt="Screenshot_20221216_121745" src="https://user-images.githubusercontent.com/70622860/208039437-d3e9c920-951e-4523-926a-3e204fe6b378.png">

dev server is working even after my changes
I am running `superset-node` container in non-dev docker-compose for temporary. It seems to be working

I will work on this further to raise a PR

Thanks.

**Comment by yashu183** [comment]
Hello @rusackas 
I jst tried `docker build .` on mac using recent `master` branch 
It seems to be having the issue. Can you recheck once.

Still failing at the same step `npm run build`
