### ISSUE TITLE
How to add a private db_engine_specs outside of superset code

### ISSUE THREAD

**Issue by idling11** [apache/superset#22423]
hi,  I have a private sqlalchemy for our own project and I want to fit it to superset.  Our customs maybe using diff versions of superset  so we want to create the `db_engine_specs`  in our own codes. Is there any way to accomplish it goal ?

**Comment by rusackas** [comment]
Hopefully [this](https://preset.io/blog/building-database-connector/) addresses your question. If not, please restate the question (with pertinent additional details) in Discussions as a Q&A thread, as this is not really a bug.
