### ISSUE TITLE
Filtered aggregation to filter + aggregation while querying Apache Druid 

### ISSUE THREAD

**Issue by tijoparacka** [apache/superset#22438]
Currently, Superset creates the query using Filtered Aggregation while creating the Druid native query.  Filtered aggregation on the String dimension is not optimal due to performance reasons while applied in a big dataset.  

This request is to add the filter used in the filtered aggregation to the query itself.

Eg: Aggregation query  

{
  "queryType": "timeseries",
  "dataSource": {
    "type": "table",
    "name": "wikipedia"
  },
  "intervals": {
    "type": "intervals",
    "intervals": [
      "-146136543-09-08T08:23:32.096Z/146140482-04-24T15:36:27.903Z"
    ]
  },
  "granularity": {
    "type": "all"
  },
  "aggregations": [
    {
      "type": "filtered",
      "aggregator": {
        "type": "longSum",
        "name": "en_cnt",
        "fieldName": "added"
      },
      "filter": {
        "type": "selector",
        "dimension": "channel",
        "value": "#en.wikipedia"
      }
    },
    {
      "type": "filtered",
      "aggregator": {
        "type": "longSum",
        "name": "ar_cnt",
        "fieldName": "added"
      },
      "filter": {
        "type": "selector",
        "dimension": "channel",
        "value": "#ar.wikipedia"
      }
    }
  ]
}

This will scan all the segments within the interval.  

To improve the performance we need to add  the filters in the Query filter 

eg:
{
  "queryType": "timeseries",
  "dataSource": {
    "type": "table",
    "name": "wikipedia"
  },
  "intervals": {
    "type": "intervals",
    "intervals": [
      "-146136543-09-08T08:23:32.096Z/146140482-04-24T15:36:27.903Z"
    ]
  },
  "filter": {
    "type": "in",
    "dimension": "channel",
    "values": [
      "#ar.wikipedia",
      "#en.wikipedia"
    ]
  },
  "granularity": {
    "type": "all"
  },
  "aggregations": [
    {
      "type": "filtered",
      "aggregator": {
        "type": "longSum",
        "name": "a0",
        "fieldName": "added"
      },
      "filter": {
        "type": "selector",
        "dimension": "channel",
        "value": "#en.wikipedia"
      },
      "name": "a0"
    },
    {
      "type": "filtered",
      "aggregator": {
        "type": "longSum",
        "name": "a1",
        "fieldName": "added"
      },
      "filter": {
        "type": "selector",
        "dimension": "channel",
        "value": "#ar.wikipedia"
      },
      "name": "a1"
    }
  ]
}

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
