### ISSUE TITLE
Superset with DuckDB engine parameters dialog gives error

### ISSUE THREAD

**Issue by sapcode** [apache/superset#22467]
#### How to reproduce the bug

1. Install superset using the current helm chart and pass the following modified helm values: https://github.com/apache/superset/blob/master/helm/superset/values.yaml
`
bootstrapScript: |
  #!/bin/bash
  rm -rf /var/lib/apt/lists/* && \
  pip install \
    psycopg2-binary==2.9.1 \
    duckdb-engine==0.6.5 \
    redis==3.5.3 && \
`
2. Open Superset and add new databases 
3. In the dropdown select DuckDB database and fill in SQL Alchemy URI: duckdb:///:memory:
4. Click to Advanced and go to ENGINE PARAMETERS
5. Parameter Test 1: Fill in Engine Parameters as JSON String with parent Tag engine_params:
`{ "engine_params": { "connect_args":{ "preload_extensions": ["httpfs"], "config": { "s3_endpoint": "minio:9000", "s3_access_key_id": "XXX", "s3_secret_access_key": "XXX", "s3_url_style": "path", "s3_use_ssl": "False" } } } }`
6. Parameter Test 2: Fill in Engine Parameters as JSON String with parent Tag connect_args:
`{ "connect_args":{ "preload_extensions": ["httpfs"], "config": { "s3_endpoint": "minio:9000", "s3_access_key_id": "XXX", "s3_secret_access_key": "XXX", "s3_url_style": "path", "s3_use_ssl": "False" } } }`

### Expected results
Parameter Test 1 or Parameter Test 2 should be added and used in the connection setup.

### Actual results

We always get the same error:
```
An error occurred while fetching databases: "Connection failed, please check your connection settings"
In chrome debug we see: PUT http://superset.mini.kube/api/v1/database/1 422 (UNPROCESSABLE ENTITY)
Response {type: 'basic', url: 'http://superset.mini.kube/api/v1/database/1'
```

When we remove the parent tag "engine_params" we get also the error:
`File "/app/superset/sqllab/sql_json_executer.py", line 111, in execute superset raise SupersetErrorsException( superset superset.exceptions.SupersetErrorsException: [SupersetError(message="'str' object does not support item assignment", error_type=<SupersetErrorType.GENERIC_DB`

### Environment

- browser type and version: Chrome 
- superset version: newest version from current helm chart
- python version: version from current helm chart
- node.js version: version from current helm chart
- any feature flags active: no

### Checklist

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

When looking at the core.py line 394 - 405 it looks like that "engine_params" is searched first, then "connect_args"
https://github.com/apache/superset/blob/master/superset/models/core.py

    params = extra.get("engine_params", {})
    if nullpool:
        params["poolclass"] = NullPool

    connect_args = params.get("connect_args", {})
    if self.impersonate_user:
        self.db_engine_spec.update_impersonation_config(
            connect_args, str(sqlalchemy_url), effective_username
        )

    if connect_args:
        params["connect_args"] = connect_args

In Connector Advanced ENGINE PARAMETER dialog, what is the specific connection string which need to be passed ?
Are the any restrictions in usage of double " or single ' quotes in the JSON string ?

This ticket is also raised at https://github.com/Mause/duckdb_engine/issues/482 but it looks like its is a bug in the dialog and how the connect_args are passed down. 

When we create a the DuckDB database without engine parameter but with "Allow DML" and call SQL-Lab we are able to use the connection settings when executing as DML statements and the data is delivered correctly:

```
install 'httpfs';
load 'httpfs';
SET s3_endpoint='minio:9000';
SET s3_access_key_id='XXX';
SET s3_secret_access_key='XXX';
SET s3_url_style = 'path';
SET s3_use_ssl=false;
select count() from 's3://raw/.parquet';
```

**Comment by sapcode** [comment]
In superset log we can find the following entries:

superset superset.exceptions.SupersetErrorsException: [SupersetError(message="'str' object does not support item assignment", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERI │
│ superset 2022-12-09 10:22:57,995:WARNING:superset.views.base:[SupersetError(message="'str' object does not support item assignment", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: │
│ superset Traceback (most recent call last):
│ superset File "/app/superset/views/base.py", line 241, in wraps
│ superset return f(self, *args, **kwargs)
│ superset File "/app/superset/utils/log.py", line 265, in wrapper
│ superset value = f(*args, **kwargs)
│ superset File "/app/superset/views/core.py", line 2408, in sql_json
│ superset command_result: CommandResult = command.run()
│ superset File "/app/superset/sqllab/command.py", line 120, in run
│ superset raise ex │
│ superset File "/app/superset/sqllab/command.py", line 102, in run
│ superset status = self._run_sql_json_exec_from_scratch()
│ superset File "/app/superset/sqllab/command.py", line 157, in _run_sql_json_exec_from_scratch
│ superset raise ex │
│ superset File "/app/superset/sqllab/command.py", line 152, in _run_sql_json_exec_from_scratch
│ superset return self._sql_json_executor.execute(
│ superset File "/app/superset/sqllab/sql_json_executer.py", line 111, in execute
│ superset raise SupersetErrorsException(
│ superset superset.exceptions.SupersetErrorsException: [SupersetError(message="'str' object does not support item assignment", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERI

**Comment by sapcode** [comment]
Following workaround will create a DuckDB Connection with stored Engine Parameter:

1. Create DuckDB database with empty Engine Parameter + Activate Allow DML
2. Open SQLLab and fire the 2 commands: install 'httpfs'; load 'httpfs';
3. Go back and Edit the DuckDB database Engine Parameter and this time paste in the full string:
{ "connect_args":{ "preload_extensions": ["httpfs"], "config": { "s3_endpoint": "argo-artifacts:9000", "s3_access_key_id": "XXX", "s3_secret_access_key": "XXX", "s3_url_style": "path", "s3_use_ssl": "False" } } }
4. Save the DuckDB database -> Now from this point onwards the SQL Lab will always use the Engine Parameter

So finally it looks like that the "preload_extensions" should install the httpfs if it's not present during the first database setup otherwise the first "add database dialog" will not add the DuckDB database.

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
