### ISSUE TITLE
UX for saving JSON metadata is misleading

### ISSUE THREAD

**Issue by polmonso** [apache/superset#22469]
We were setting the expanded slice setting via the json metadata of the Dashboard properties which is saved on the modal menu automatically, but if you then save the Dashboard it gets overwritten.

#### How to reproduce the bug

1. Go to Edit mode of the Dashboard
2. Click on the Three dots -> Dashboard Properties -> Advanced
3. Change the expanded_slices dictionary
4. Save Modal dialog
5. **Save Dashboard** instead 
6. Reopen the Advanced dashboard properties, the setting is not saved

The way to keep the changes is Discarding the changes, which is counterintuitive.

### Expected results

Save Dashboard should not override the modal dialog saved changes

### Actual results

Save Dashboard overrides the modal dialog saved changes

### Environment

- browser type and version: Firefox 108.0
- superset version: `Version: 1.3.2`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by artemonsh** [comment]
Did not manage to recreate the bug on the version 2.0.1. I suppose the issue is related to the version you are using and was solved in later releases. BTW, why do you use the old version of Superset?

**Comment by polmonso** [comment]
Thanks. We'll update the superset version then. No particular reason to stay on pre 2.0.
