### ISSUE TITLE
The "Table" chart displays N/A instead of timestamps with IANA codes

### ISSUE THREAD

**Issue by m-ocean-it** [apache/superset#22505]
The "Table" chart can't display timestamps from Trino with IANA labels added.

I'm not sure if it's Trino specific, though.

### How to reproduce the bug

1. Create a dataset from Trino. It should contain a timestamp. The dates at the source are in UTC. Make sure everything is fetched normally.
2. Create a "Table" chart using that dataset. Make sure the timestamps are displayed properly.
3. Modify the query to convert timestamps to specified time zone using an IANA code: `select t.timestamp at time zone 'America/New_York' from ...`.
4. Rebuilt the chart. You'll see `N/A` in the timestamp column.

### What works
- Everything is properly displayed in the SQL Lab. Example: `2022-12-19 04:30:08.442 America/New_York`.
- The "Time-series Line Chart" properly parses such timestamps nonetheless.
- Using `-05:00` instead of `America/New_York` in the query allows the "Table" chart to properly display timestamps. So, it seems that an IANA code shouldn't be a part of the timestamp to be properly rendered by the "Table" chart.

### Environment

Started with `docker-compose`. Commit: `5e1b8170c`

- browser type and version: `Brave Version 1.46.140 Chromium: 108.0.5359.99 (Official Build) (64-bit)`
- superset version: `0.0.0-dev` (that was displayed in the "About" section of the GUI)
- python version: `python 3.8.13`
- any feature flags active:
  - `ALERT_REPORTS`
  - `DASHBOARD_RBAC`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
This is an interesting one... is this still an issue in 3.x?

**Comment by rusackas** [comment]
Still not sure if it's an issue in 3.x... or by now, in 4.x. Closing as stale, but happy to revisit/reopen if anyone is still experiencing this in currently supported versions.
