### ISSUE TITLE
pxoxy issue while running npm run dev-server

### ISSUE THREAD

**Issue by Ashvi213** [apache/superset#22500]
I was trying to add a custom pluggin with the help of tutorial mentioned in [Building Custom Viz Plugins in Superset v2 (Updated for Monorepo) | Preset](https://preset.io/blog/building-custom-viz-plugins-in-superset-v2/). But at last when I run 'npm run dev-server'. I get the below error (Attaching screenshot for reference)..
Please help me to resolve..
Do i need to run anyother commands instead of 'npm run dev-server' ? (edited)
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/115608385/208939603-d4edbc23-cc73-4e09-80cf-4194cb2230cb.png)

**Comment by artemonsh** [comment]
It seems that you forgot to start backend locally ([instructions here](https://github.com/apache/superset/blob/master/CONTRIBUTING.md#flask-server)). Did you?

**Comment by Ashvi213** [comment]
Ya we forget to start the backend. Thank you for helping.

**Comment by indrarahul2013** [comment]
This issue can be closed if resolved.
