### ISSUE TITLE
Missing "Extra" section and CSV upload checkbox for a SQLite database when running the project as a docker container

### ISSUE THREAD

**Issue by ziadloo** [apache/superset#22514]
#### How to reproduce the bug

1. Start a new container:
```
$ docker run -d -p 8080:8088 --name superset apache/superset
$ docker exec -it superset superset fab create-admin \
              --username admin \
              --firstname Superset \
              --lastname Admin \
              --email admin@superset.com \
              --password admin
$ docker exec -it superset superset db upgrade
$ docker exec -it superset superset init
```
2. Enable adding a new database of SQLite type by adding `PREVENT_UNSAFE_DB_CONNECTIONS = False` to the `/app/superset/config.py` file:
```
$ docker exec -it superset /bin/bash
$ printf "\nPREVENT_UNSAFE_DB_CONNECTIONS = False\n" >>  /app/superset/config.py
$ exit
```
3. Restart the container (for good measure, I'm not sure if it is needed):
```
$ docker restart superset
```
4. Go to `http://localhost:8080/databaseview/list/` (after login of course)
5. Click on the `+ DATABASE` button (top-right corner)
6. Click on the `SQLite` box in the opened dialog
7. As for the `SQLALCHEMY URI` field, enter `sqlite:////tmp/test.db`
8. Click on the `CONNECT` button
9. Once you are back to the database list, hover the mouse pointer over the `Actions` column of the newly created database and click on the `Edit` icon
10. This will open the `Edit database` dialog for the database, now navigate to the `ADVANCED` tab of the dialog
11. Supposedly, there should be an `Extra` accordion with a checkbox letting me enable "CSV uploads" for the database. But there's no such section/checkbox

### Expected results

A way to enable CSV uploads for a SQLite database

### Actual results

Missing checkbox for enabling CSV uploads (such a checkbox cannot be found anywhere)

#### Screenshots

The "Edit database" dialog when the project is run using docker:

![image](https://user-images.githubusercontent.com/3235521/209203241-d92ef19a-1347-4f7f-ae51-9e237e7b9c27.png)

### Environment

- browser type and version: Google Chrome Version 108.0.5359.124 (Official Build) (64-bit)
- superset version: `$ superset version`: `0.0.0-dev` !!! As mentioned before, I'm running the project using docker.
- python version: `Python 3.8.13`
- node.js version: `node -v`: `bash: node: command not found` !!! For some reason, the docker does not come with node but it works which makes me wonder why node is mentioned here?
- `$ superset --version`:
```
Loaded your LOCAL configuration at [/app/pythonpath/superset_config.py]
Python 3.8.13
Flask 2.0.3
Werkzeug 2.0.3
```

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [× ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ✓] I have reproduced the issue with at least the latest released version of superset.
- [ ✓ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

The documentation on how to enable CSV uploads is not showing the same UI as docker's latest. I'm not sure if the documentation is too old or the docker's latest.

This is what the documentation shows:
https://superset.apache.org/docs/creating-charts-dashboards/exploring-data/#enabling-data-upload-functionality

![image](https://user-images.githubusercontent.com/3235521/209205923-e2b71c1c-b70b-45be-aa7a-df46c94bab58.png)

But what I see in my docker's latest UI, it's not a tab but an accordion (see the screenshot provided above).

**Comment by artemonsh** [comment]
It is probably a legacy message about **Extra** tab which was deprecated in later releases. Now you can enable CSV upload in **Security** section: 
![image](https://user-images.githubusercontent.com/53895552/209325195-e45a3684-82e0-4440-b7d4-dce6f3e31fc7.png)
