### ISSUE TITLE
[Suggestion] Feature flag - create a new chart in the same tab

### ISSUE THREAD

**Issue by ohadch** [apache/superset#22527]
**Motivation**

We deployed Superset in our webapp inside an iframe (version 2.0.0). Unfortunately, the "Create new chart" button opens a new tab, instead of redirecting the user to the chart page. As a result, from our point of view, the whole experience is affected to the bad side, as now the user left the iframe to a new tab, and as a result, left our application as well. 😞

**Suggestion**

We would like to suggest the following idea: implement a new `DASHBOARD_CREATE_CHART_IN_NEW_TAB` feature flag, that in order to keep the current behavior, is set to `True` by default. 
If `DASHBOARD_CREATE_CHART_IN_NEW_TAB` is `True`, then clicking on create chart from the dashboard page will open a new tab. Otherwise, the user will only be redirected to the new chart page.

Please share your opinion. 🙏

Regards,
Ohad

</div>

**Comment by geido** [comment]
Hello @ohadch this behaviour has been changed in the recent versions of Superset. Thank you!

**Comment by Kalindu-Abey-sysco** [comment]
Hi @geido what is the solution this to create new chart in the same tab?
