### ISSUE TITLE
Unable to Connect to database. 404 error

### ISSUE THREAD

**Issue by Ashvi213** [apache/superset#22524]
I created custom plugin based on the doc: https://preset.io/blog/building-custom-viz-plugins-in-superset-v2/.
On the development server(localhost:9000) its loading my created plugin but unable to load the data set from the example. While trying to load the existing data set its not loading. Also not able to load data from the csv.  Here is the screenshot. Please help.

![image](https://user-images.githubusercontent.com/115608385/209431777-0c12f9a5-957c-4eca-901a-af462465f34c.png)

**Comment by Ashvi213** [comment]
![image](https://user-images.githubusercontent.com/115608385/209661749-c9b4f8ee-3042-4dae-b891-432843309d4e.png)
also unable to upload data from csv. Please suggest if there is any solution.

**Comment by Ashvi213** [comment]
Hi Everyone....I cloned the project from https://github.com/apache/superset.git and run it using 'npm run dev-server' and working fine in localhost:9000 port.But while I try to check database connection, I'm getting 404 error.Attaching screenshot for referencePlease help  to sort out issueThanks In Advance!!!

![image](https://user-images.githubusercontent.com/115608385/209666266-62893fe6-2d66-4944-9f59-9a6d4f224bc7.png)

**Comment by vonHabsi** [comment]
I am not that familiar with sqlalchemy URIs, but isn't 4 slashes after the `sqlite:` one too many ie `sqlite:///home.ms/...` rather than `sqlite:////home.ms/...` that you have typed?

**Comment by ZiminVladimir** [comment]
I had same error on wsl. If you also work on wsl try to reset your wsl in Windows settings. It helped me.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for almost a year, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
