### ISSUE TITLE
connect with solr

### ISSUE THREAD

**Issue by aboodalfar** [apache/superset#22538]
I'm trying to  connect with solr but I get this  error   

####  Object 'default' not found

![image](https://user-images.githubusercontent.com/57001511/209666962-638403de-4e43-45e9-b1ee-a5b31c972aa0.png)

**Comment by sfirke** [comment]
Is this issue still active?  If so, what connection string are you using for solr as that's where the issue seems to be?

**Comment by rusackas** [comment]
Closing due to lack of response, but happy to re-open if/when this needs further attention with actionable reproduction instructions.
