### ISSUE TITLE
Unable to connect Apache kylin to superset

### ISSUE THREAD

**Issue by aliakberfaiz** [apache/superset#22532]
I'm running Superset on docker on windows, and kylin is runnning on another machine both are in same virtual network. I have installed kylinpy on docker container to enable connection from kylin on superset but I'm unable to connect. I'm getting following error:
`(builtins.NoneType) None [SQL: _compose_select_body() takes 7 positional arguments but 9 were given] (Background on this error at: https://sqlalche.me/e/14/dbapi)`

SQLALCHEMY URI uri that i have used is given below:
`kylin://ADMIN:KYLIN@<IP-address-machine-running-kylin>:7070/learn_kylin`

**Comment by rusackas** [comment]
Looks like this should have been closed when the linked PR was merged.
