### ISSUE TITLE
[Question] Are dashboard thumbnails generated periodically?

### ISSUE THREAD

**Issue by stepcheunghk** [apache/superset#22540]
I have a question.
Thumbnails are shown as blank after they are timed out. All I need to do is to go to dashboard, and trigger the caching and thumbnail generation again.
Is there any way to configure, so that dashboard thumbnails generated periodically in the backend at specific time (saying in the midnight)? How can I configure it?

**Comment by sfirke** [comment]
What version of Superset are you using?  What is your configuration?

**Comment by stepcheunghk** [comment]
@sfirke Thanks for your reply. I am using Superset 2.0.0. Just wonder if there is any way to generate thumbnails periodically without triggering the caching manually (i.e. visit the dashboard).

**Comment by sfirke** [comment]
My understanding from browsing the Superset Slack chat is that cache warmup functionality has existed in the past but is currently broken.  See https://github.com/apache/superset/pull/21076 and its discussion which points to https://github.com/apache/superset/pull/20387.

Alas I am not even able to get thumbnails working myself b/c I'm on Azure and can't figure out how to adapt the existing code in the docs (for AWS) to work with Azure Blobs: https://stackoverflow.com/questions/74194960/use-azure-blob-storage-instead-of-s3-buckets-in-apache-superset-cache 😭
