### ISSUE TITLE
Unserializable object xxx.xxx.xxx.xxx. of type <class 'ipaddress.IPv4Address'>

### ISSUE THREAD

**Issue by owlwc** [apache/superset#22547]
### Expected results

use clickhouse cli can return data:

![image](https://user-images.githubusercontent.com/104346667/209926709-8eb51cdd-e957-46c4-95d0-e98f85ebad69.png)

### Actual results

use superset：

![image](https://user-images.githubusercontent.com/104346667/209926180-2258a662-8c51-408c-92c9-f39fa7f40097.png)

error info:

![image](https://user-images.githubusercontent.com/104346667/209929610-14c35c3d-03e6-4114-86b7-edca6a18ac96.png)

Environment
(please complete the following information):

superset version: 2.0.1
python version: 3.8.16
clickhouse-sqlalchemy  0.1.10

**Comment by owlwc** [comment]
How can I fix it ?

**Comment by rusackas** [comment]
@reesercollins would someone on your team know how best to steer/address this?

**Comment by reesercollins** [comment]
> @reesercollins would someone on your team know how best to steer/address this?

I've actually changed teams and am no longer working on superset. I would direct your attention to @cccs-rc for an answer on that front.

**Comment by cccs-rc** [comment]
> > @reesercollins would someone on your team know how best to steer/address this?
> 
> I've actually changed teams and am no longer working on superset. I would direct your attention to @cccs-rc for an answer on that front.

I don't think this is related to advanced types. As best as I can tell, this is something specific to Clickhouse. Unfortunately Clickhouse isn't part of our tech stack, so I don't think we can offer much help here.

**Comment by rusackas** [comment]
@shreesham do you or anyone you know have a way to repro this?

**Comment by genzgd** [comment]
It looks like this broke with clickhouse-sqlalchemy.  Do you know if it works with ClickHouse Connect?

**Comment by round3d** [comment]
I'll confirm this works correctly with IPv4 datatypes in latest-dev and clickhouse-connect  

clickhouse-connect     0.6.11

![image](https://github.com/apache/superset/assets/3385802/5c3f25e9-71a5-4fb1-96ce-a3782b705608)

**Comment by rusackas** [comment]
Assuming all is well here based on the above comment, and how long it's been since this thread saw any action. Optimistically closing, but happy to reopen if it's still an issue.
