### ISSUE TITLE
add new language in apache superset

### ISSUE THREAD

**Issue by sedanursayer** [apache/superset#22549]
Any idea how to add Turkish language to apache superset?

**Comment by sfirke** [comment]
Yes!  See this documentation: https://superset.apache.org/docs/contributing/translations/  I don't see an existing directory for Turkish `tr` so you could start adding translations for it by following those steps, then submitting a pull request.

**Comment by rusackas** [comment]
@sfirke is correct here... we'd more than welcome addition of Turkish translations. If you don't find what you're looking for in that link, please feel free to reach out to us on [Slack](https://join.slack.com/t/apache-superset/shared_invite/zt-1jp6hjzrq-H0PlFtToyLWuPiJDuRWCNw) and hopefully we can steer you in the right direction. We'd appreciate the contribution(s)!

Meanwhile I'm going to close this as an Issue. Please link the PR to this if you do indeed open one!

**Comment by sedanursayer** [comment]
i followed the steps and got a language pack for Turkish, but it's just for testing at the moment. i can't find an active link for Slack. Could you help?

**Comment by sedanursayer** [comment]
@rusackas Hello there! I created a package for Turkish, but I did very little experimental translations. If I complete it, I'll be happy to share it with you. By the way, although I select other languages ​​in the config file, I cannot see the full translation in the interface. What is the reason of this?

**Comment by rusackas** [comment]
> By the way, although I select other languages ​​in the config file, I cannot see the full translation in the interface. What is the reason of this?

If you mean that you cannot see the full translation meaning it's _partial_ that's probably because the translations are out of date and not everything is translated. 

If it's that the language is _not changing at all_ then there may be a bug.

**Comment by mrtsrdm** [comment]
hi @sedanursayer ,
will you share the Turkish translations ?

**Comment by sedanursayer** [comment]
Hi. I created the necessary files for the Turkish language. I can add Turkish as language. How can I share this with you? @rusackas @sfirke

**Comment by sfirke** [comment]
Nice!  If you completed the files listed in that `/translations` link above, you could submit the change as a pull request to be merged into the main Superset repository.  https://superset.apache.org/docs/contributing/pull-request-guidelines

**Comment by Alperen-orc** [comment]
hi @sedanursayer , @mrtsrdm 
can you share the Turkish translations ?

**Comment by rusackas** [comment]
Yep, just open a PR. If you need assistance with that, you can ping me/us in the #contributing channel on [slack](http://bit.ly/join-superset-slack). Thanks in advance!
