### ISSUE TITLE
Can I modify the display style of the first page of Kanban?  Users are not used to this style and interaction mode

### ISSUE THREAD

**Issue by nh1571** [apache/superset#22558]
This is the default
![1672471332194](https://user-images.githubusercontent.com/18585055/210128892-2eba0e25-f7f6-4fce-afd2-149cf4b48c69.png)
Want to be like this
![c19a847a887620f7a37bf8b219afa4f](https://user-images.githubusercontent.com/18585055/210128909-762ad00f-2056-43f3-a3b0-894e90a07d44.png)

**Comment by sfirke** [comment]
This is probably better suited to Github Discussions.  I haven't tried customizing the homepage but can say that Superset doesn't currently have folder structures or really any way to organize reports or dashboards that I know of.  So that second screenshot is not possible.

**Comment by rusackas** [comment]
Agreeed with Sam... this is not a supported feature of Superset, and thus not a bug/issue. It looks/sounds like you're looking to deeply change the Superset UX/UI - this would be best suited as an [Ideas discussion](https://github.com/apache/superset/discussions/categories/ideas) or on the #customizing-superset channel on [Slack](https://github.com/apache/superset)
