### ISSUE TITLE
Not able to increase superset row limit in table chart

### ISSUE THREAD

**Issue by k20ameer** [apache/superset#22569]
There is a table chart and the total count of the dataset is 50000000. I tried to  increase the row_limit value (more than 10 000) and there is nothing changed in the superset. 

I have changed these values in config.py file :

ROW_LIMIT = 50000000
SAMPLES_ROW_LIMIT = 50000000
FILTER_SELECT_ROW_LIMIT = 50000000
QUERY_SEARCH_LIMIT = 50000000
SQL_MAX_ROW = 500000000
DISPLAY_MAX_ROW = 50000000
DEFAULT_SQLLAB_LIMIT = 50000000

![image](https://user-images.githubusercontent.com/110551654/210319904-e0d0f295-6a8e-4e68-b1b4-3e4aa73b08dc.png)

Superset version : 1.5.0.
Please help me to fix this issue.

**Comment by fniko** [comment]
I have adjusted file `superset_config.py` in `superset/docker/pythonpath_dev` and it works for me.
I am using a `docker-compose` method, described [here](https://superset.apache.org/docs/installation/installing-superset-using-docker-compose/).

I have appended following lines to the file.
```python
# Custom (user) configuration below
SUPERSET_WEBSERVER_TIMEOUT = 600 # Increasing queries timeout
ROW_LIMIT = 1000000
SAMPLES_ROW_LIMIT = 50000000
FILTER_SELECT_ROW_LIMIT = 50000000
QUERY_SEARCH_LIMIT = 50000000
SQL_MAX_ROW = 500000000
DISPLAY_MAX_ROW = 50000000
DEFAULT_SQLLAB_LIMIT = 50000000
```

**Comment by tooptoop4** [comment]
maybe the tsx file is cached, incognito mode might help

**Comment by Shazad-khan** [comment]
![image](https://user-images.githubusercontent.com/100838455/227500634-6ee9c10d-5a24-4730-aaef-e0fd66932f2b.png)


This issue has been fixed in the latest release. I have tested it and it works fine
