### ISSUE TITLE
Error message: Excel file format cannot be determined, you must specify an engine manually, while uploading Excel file in superset

### ISSUE THREAD

**Issue by Raj2598** [apache/superset#22564]
### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sfirke** [comment]
Try the fixes here: https://stackoverflow.com/questions/68478097/pandas-glob-excel-file-format-cannot-be-determined-you-must-specify-an-engi

As is, since this bug report only has the subject line filled in, there's nothing to really go on in terms of troubleshooting or debugging.

**Comment by rusackas** [comment]
Closing this since none of the bug report details are filled in, making this inactionable. If you fill out the bug template, we'll be happy to re-open and take a fresh look.
