### ISSUE TITLE
Filter for datetime value returns "Cannot compile Column object until its 'name' is assigned."

### ISSUE THREAD

**Issue by stephanclaus** [apache/superset#22574]
#### How to reproduce the bug

1. Build a chart on a data set that contains a datetime column 
2. Add this chart to a dashboard
3. add a dashboard filter on the datetime column
4. apply the filter
5. See error

### Expected results

the chart is filtered by the value

### Actual results

An error is raised:

Cannot compile Column object until its 'name' is assigned.

This may be triggered by:
Issue 1011 - Superset encountered an unexpected error. 

#### Screenshots

<img width="601" alt="Screenshot 2023-01-03 at 21 32 45" src="https://user-images.githubusercontent.com/75787042/210437349-3e65e68a-2841-4f5a-9721-1ec239c73430.png">

### Environment

(please complete the following information):

- Chrome Version 108.0.5359.124 (Official Build) (x86_64)
- superset version: `2.0.0`
- connecting to snowflake database

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Superset 2.0.0 and snowflake/sqlalchemy seems to have more problems with date time handling. The same approach is working fine if the filter column is a date field.

**Comment by michael-s-molina** [comment]
@geido @kgabryje This may be related to the bug we were investigating with drill to detail and Snowflake.

**Comment by stephanclaus** [comment]
Hi, so the column you are using the the order_date column? Is this a datetime data type actually?

**Comment by zhaoyongjie** [comment]
yes, it does. `o_orderdate` is a DateTime column in standard TPCH.

**Comment by stephanclaus** [comment]
okay, so it is in the standard TPCH, but not in Snowflake:
![Screenshot 2023-01-26 at 18 45 26](https://user-images.githubusercontent.com/75787042/214923592-c0719c35-48cd-4357-a500-ba8e57f49390.png)
![Screenshot 2023-01-26 at 18 42 12](https://user-images.githubusercontent.com/75787042/214923600-742d9b97-5309-4f57-a838-7c644d7d9eb6.png)

So I think your test case is invalid.

**Comment by villebro** [comment]
Closed by #22872
