### ISSUE TITLE
Python 3.10 support missed from 2.0 branch

### ISSUE THREAD

**Issue by cwegener** [apache/superset#22582]
Python 3.10 support is not included in the 2.0 branch. Was this a deliberate decision or was the relevant commit from master simply overlooked?

#### How to reproduce the bug

1. Install Python 3.10
2. `pip install apache-superset<=2.0.0`

### Expected results

Apache Superset installation completes

### Actual results

```
        ERROR: Failed building wheel for numpy
```

### Additional context

Why was this commit left out from the 2.0 branch? 76d6a9af91a71401d158bc150518b3c9366030ac

**Comment by john-bodley** [comment]
@cwegener Python 3.10 support was added in https://github.com/apache/superset/pull/21002 which occurred after the 2.0 release branch. Future major/minor releases will include Python 3.10 support.

**Comment by cwegener** [comment]
Hi John.

Thanks for the clarification. That does indeed make sense.

Being stuck with a N-2 version of Python for users of the Apache 2.0 release can be a bit of a challenge though.
Not everyone uses Docker and can just run an old Python version inside of a Docker container. And installing multiple versions of Python alongside each other on the same Operating System as an alternative seems even more fraught with potential confusion.

Using Ubuntu as an example, the latest LTS release is Ubuntu 22.04 and comes with Python 3.10 and was released ~8 months ago. And there also is a new non-LTS Ubuntu release (22.10) which ships Python 3.11. Users of this example operating system would pretty much be limited to the version of Python that comes with it.

I'm not sure if I'm barking up the wrong tree and I'm the only person seeing this as a problem at all.

I guess the real question is, who is the target audience for the PyPI Sdist releases of Apache Superset?

The only reason that I became aware of this particular Python 3.10 issue was due to an integration problem of integrating the Apache Superset release into another platform via means of `pip install`. Specifically the Meltano plug-in which runs Superset inside of a Python virtualenv and uses the PyPI releases of Apache Superset. https://hub.meltano.com/utilities/superset

Anyway. I do realise that this issue is part of a larger topic of release strategy which goes beyond this issue.

Closing this issue.
