### ISSUE TITLE
Not able to connect SuperSet to Dremio instance

### ISSUE THREAD

**Issue by altruistcoder** [apache/superset#22601]
We have an openshift cluster where we have deployed SuperSet using its Helm chart. We are trying to connect this Superset instance (running inside a pod) to a Dremio instance running on another different openshift cluster.

But, we are facing the below error while we are trying to connect to a Dremio Database:

![supersetpng](https://user-images.githubusercontent.com/31319270/210723172-69511ec8-552e-4c80-8c80-4cfb3e9ceb41.png)

We have tried installing the required packages for Dremio (viz, **_pyodbc_**, **_sqlalchemy_dremio_**, **_unixodbc_** and _**unixodbc-dev**_ modules) but it seems the problem is still persistent.

I am also attaching below the logs which we are getting from the SuperSet pod:

[superset.log](https://github.com/apache/superset/files/10350182/superset.log)

### Expected results

Dremio getting connected to SuperSet correctly.

### Actual results

Dremio instance is not getting connected to the SuperSet instance.

### Environment

- browser type and version: `Google Chrome (Version 108.0.5359.125)` 
- superset version: `1.3.2`
- python version: `3.8.12`
- sqlalchemy-dremio python module version: `1.2.1`
- pyodbc python module version: `4.0.35`
- pyarrow python module version: `4.0.1`
- apache-superset python module version: `1.3.2`

**Comment by SubhasmitaSw** [comment]
@altruistcoder You can try connecting it via the flight connector the url would be something like `dremio+flight://user:pass@host:32010/dremio`. 

The connection for the above url when tested returns okay, but while fetching the databases in superset UI it returns an error saying `An error occurred while fetching databases: Database parameters are invalid.` 

@rusackas is there any workaround for this?

**Comment by rusackas** [comment]
I'm not sure about any workarounds there... but this thread has also been silent for a long time. Is anyone still facing this? It was reported in the 2.0 era, which we no longer support. I'm closing it as stale, but would be happy to reopen it if it still exists in 3.x or newer.
