### ISSUE TITLE
I want to integrate superset with Prometheus.

### ISSUE THREAD

**Issue by dragonball-wooboo** [apache/superset#22602]
I want to integrate superset with Prometheus.
It has been confirmed that superset does not support Prometheus as a database 

So after installing trino in the middle, I'm trying to link Prometheus. At that time, trino has a problem in that part.

Is there any way to solve this phenomenon?

![image](https://user-images.githubusercontent.com/41145660/210735523-7db070aa-3f6f-405d-b595-8cb2fe47d77d.png)

**Comment by rusackas** [comment]
There's a whole discussion thread on this, since it's a feature request rather than a bug. Feel free to join in the conversation there:
https://github.com/apache/superset/discussions/18381

It seems that really, we just need some volunteer support to champion the cause and make it happen.
