### ISSUE TITLE
create new image docker

### ISSUE THREAD

**Issue by xmagcx** [apache/superset#22627]
#### How to reproduce the bug

1. Step add new drivers (https://superset.apache.org/docs/databases/docker-add-drivers/)
2. Execute command docker-compose build --force-rm
3. it takes a long time to respond
4. Result:
npm ERR! code FETCH_ERROR
npm ERR! errno FETCH_ERROR
npm ERR! network timeout at: https://registry.npmjs.org/yocto-queue/-/yocto-queue-0.1.0.tgz

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-01-06T19_29_02_808Z-debug-0.log

### Expected results

build docker image correctly

### Actual results

npm ERR! code FETCH_ERROR
npm ERR! errno FETCH_ERROR
npm ERR! network timeout at: https://registry.npmjs.org/yocto-queue/-/yocto-queue-0.1.0.tgz

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-01-06T19_29_02_808Z-debug-0.log

#### Screenshots

![image](https://user-images.githubusercontent.com/20447334/211089006-7b1a104d-9252-4e34-b831-4188e59285ff.png)

### Environment

(please complete the following information):

- browser type and version: N/A
- superset version: `superset version` master branch
- python version: `python --version` 3.8
- node.js version: `node -v` 16
- any feature flags active: N/A

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Testing into Dockerfile (https://stackoverflow.com/questions/67657599/npm-err-code-err-socket-timeout-on-creating-new-project-using-ng-new-appname)

![image](https://user-images.githubusercontent.com/20447334/211090185-7b15757d-f46c-4ea2-9cfb-3ad938dae421.png)

**Comment by rusackas** [comment]
It sure looks like it was having trouble retrieving that `yocto-queue` package. Were you able to retrieve it manually at that time? NPM sometimes has outages. Maybe worth trying again? Did you look at the detailed error in the npm logs as it suggests?

**Comment by xmagcx** [comment]
> It sure looks like it was having trouble retrieving that `yocto-queue` package. Were you able to retrieve it manually at that time? NPM sometimes has outages. Maybe worth trying again? Did you look at the detailed error in the npm logs as it suggests?
As indicated, perform the tests that were recommended in different forums. On the other hand, I cannot visualize said error since I am not a react developer to validate the content of the code, so I am only raising the bug.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
