### ISSUE TITLE
Unable to connect to the databases

### ISSUE THREAD

**Issue by lbenothman** [apache/superset#22621]
Hi team,

I deployed superset using the helm chart and everything was working perfectly. Since the last docker version (Tag: master), Superset is not able to connect to the databases, I have linked it to a Redshift and to a Postgres Database. 

When I try to open a dashboard I have the following error:

`(psycopg2.errors.UndefinedTable) relation "ssh_tunnels" does not exist
LINE 2: FROM ssh_tunnels 
             ^

[SQL: SELECT ssh_tunnels.uuid AS ssh_tunnels_uuid, ssh_tunnels.created_on AS ssh_tunnels_created_on, ssh_tunnels.changed_on AS ssh_tunnels_changed_on, ssh_tunnels.extra_json AS ssh_tunnels_extra_json, ssh_tunnels.id AS ssh_tunnels_id, ssh_tunnels.database_id AS ssh_tunnels_database_id, ssh_tunnels.server_address AS ssh_tunnels_server_address, ssh_tunnels.server_port AS ssh_tunnels_server_port, ssh_tunnels.username AS ssh_tunnels_username, ssh_tunnels.password AS ssh_tunnels_password, ssh_tunnels.private_key AS ssh_tunnels_private_key, ssh_tunnels.private_key_password AS ssh_tunnels_private_key_password, ssh_tunnels.created_by_fk AS ssh_tunnels_created_by_fk, ssh_tunnels.changed_by_fk AS ssh_tunnels_changed_by_fk 
FROM ssh_tunnels 
WHERE ssh_tunnels.database_id = %(database_id_1)s]
[parameters: {'database_id_1': 5}]
(Background on this error at: https://sqlalche.me/e/14/f405)

This may be triggered by:
Issue 1002 - The database returned an unexpected error. `

Same when I try to access the databases list

#### How to reproduce the bug

1. Go to any dashboard
2. An error is displayed on every chart
3. Click on see more

#### Screenshots
<img width="1649" alt="image" src="https://user-images.githubusercontent.com/3247643/211000460-75f85346-df32-4980-abc0-57e85924c906.png">

<img width="593" alt="image" src="https://user-images.githubusercontent.com/3247643/211000501-82822dc2-6544-4cb9-b439-d9fb02bf8433.png">

<img width="488" alt="image" src="https://user-images.githubusercontent.com/3247643/211000574-b627d1ba-21ea-4575-9aab-b5e5f8c775fd.png">

### Environment

(please complete the following information):

- browser type and version: Chrome 108.0.5359.124
- superset version: `superset version`: The last master tag

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X ] I have reproduced the issue with at least the latest released version of superset.
- [X ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by lbenothman** [comment]
I fixed the problem by upgrading the database using the command:
superset db upgrade

**Comment by lbenothman** [comment]
I fixed the problem by upgrading the database using the command:
superset db upgrade

**Comment by nickg100** [comment]
Hi @lbenothman I am also facing similar issue. can you please let me know where you applied the command?
