### ISSUE TITLE
Getting "sub" key value as 1 from security/login response token

### ISSUE THREAD

**Issue by khumis01** [apache/superset#22639]
Unable to parse response token received from api/v1/security/login request.

Getting "Unexpected type of JSON object member with key sub" after parsing the token from JWT parser.

**Comment by rusackas** [comment]
I think most people are not running into this issue, and we may need more details, e.g. what version you're running, how you're running it, and any other pertinent repro steps, details, etc.

**Comment by rusackas** [comment]
Closing until we can get more details (i.e. a means to reproduce the issue reliably)
