### ISSUE TITLE
DASHBOARD_CROSS_FILTERS is not enabling in Superset

### ISSUE THREAD

**Issue by therahilshaikh** [apache/superset#22654]
I am having an issue with DASHBOARD_CROSS_FILTERS not being enabled in Superset using the `superset_config_docker.py` configuration file.

I have followed the instructions for configuring Superset, and have ensured that `DASHBOARD_CROSS_FILTERS = True` is set in the `superset_config_docker.py` file. However, when I navigate to a dashboard in Superset, the cross-filtering option is not available.

![remmina_Data warehouse_192 168 178 30_20230110-053618](https://user-images.githubusercontent.com/54621699/211470394-a2b6c7bf-a66f-484a-b400-1e41463707bc.png)
Enabled flag in  `superset_config_docker.py` 

![chart](https://user-images.githubusercontent.com/54621699/211475472-4f815182-4268-4ecf-a06e-b378bb81a3da.png)
No checkbox shown

![logs](https://user-images.githubusercontent.com/54621699/211475829-db742c2c-73b6-467c-9842-453ea8e92938.png)

After inspecting superset page, found that flag is set to false

I have verified that the configuration file is being properly loaded by checking the superset_config log, and I have also tried restarting the Superset server to ensure that any changes to the configuration file are applied.

I am running Superset version 2.0.16, and I am using it on CentOs 7 in docker-compose.

Any assistance with this issue would be greatly appreciated. Thank you in advance for your help!

**Comment by rusackas** [comment]
Closing this as it's on by default in current versions.
