### ISSUE TITLE
typeError: Cannot read properties of null (reading 'offsetHeight')

### ISSUE THREAD

**Issue by uknowzheng** [apache/superset#22675]
# front-end

#### How to reproduce the bug

1. the front-end project startup and then dev-server reload code 
2. npm ci & npm run dev-server
3. then modify anywhere code,will show Unexpected error:

### Expected results

Unexpected error: TypeError: Cannot read properties of null (reading 'offsetHeight')
    in CSSMotion (created by CollapsePanel)
    in div (created by CollapsePanel)
    in CollapsePanel (created by CollapsePanel)
    in CollapsePanel (at Welcome.tsx:292)
    in div (created by Collapse)
    in Collapse (created by Collapse)
    in Collapse (at Collapse/index.tsx:24)
    in Unknown (created by Styled(Component))
    in Styled(Component) (at Welcome.tsx:277)
    in div (created by Styled(div))
    in Styled(div) (at Welcome.tsx:265)
    in Welcome (created by ConnectFunction)
    in ConnectFunction (at App.tsx:72)
    in ErrorBoundary (at App.tsx:71)
    in Suspense (at App.tsx:70)
    in Route (at App.tsx:69)
    in Switch (at App.tsx:68)
    in LocationProvider (created by Context.Consumer)
    in Route (created by QueryParamProvider)
    in QueryParamProvider (at RootContextProviders.tsx:42)
    in DynamicPluginProvider (at RootContextProviders.tsx:41)
    in EmbeddedUiConfigProvider (at RootContextProviders.tsx:40)
    in FlashProvider (at RootContextProviders.tsx:39)
    in Unknown (at RootContextProviders.tsx:38)
    in Provider (at RootContextProviders.tsx:37)
    in ThemeProvider (at RootContextProviders.tsx:36)
    in RootContextProviders (at App.tsx:65)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.tsx:62)
    in QueryClientProvider (at QueryProvider.tsx:33)
    in Queryprovider (at App.tsx:61)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp (at views/index.tsx:22)

### Actual results

hot reload code 

#### Screenshots

![image](https://user-images.githubusercontent.com/4647461/211749198-0cd65eb1-143c-48ef-bb38-bc4efa0b50db.png)

![image](https://user-images.githubusercontent.com/4647461/211748992-b33b9846-54e7-43b8-862b-a48139219778.png)

### Environment

dev env

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
