### ISSUE TITLE
Links to slack are dead

### ISSUE THREAD

**Issue by anthonyorona** [apache/superset#22672]
Within the documentation, I have found 3 links to slack:

Within 

```
https://superset.apache.org/community/
https://github.com/apache/superset/blob/master/CODE_OF_CONDUCT.md
https://github.com/apache/superset/blob/master/README.md
```
It looks like these were last updated a few months ago: https://github.com/apache/superset/pull/22121 and the limit may have been exceeded.

Can we get a new link to join the slack? I am new to superset and it looks like the best community forum. I would like to developer a superset plugin where I can embed a form and make an asynchronous request when a UI component is clicked. I do not need to go through superset's backend.

**Comment by artemonsh** [comment]
Working link: http://bit.ly/join-superset-slack
It will be updated periodically by the PMC members as mentioned here: https://github.com/apache/superset/pull/22631

**Comment by rusackas** [comment]
This should be resolved now :D
