### ISSUE TITLE
shortend url for chart keeps getting updated on refresh

### ISSUE THREAD

**Issue by snehlata08** [apache/superset#22673]
When i open a char like this and click on the embed link 
![image](https://user-images.githubusercontent.com/79985986/211731832-d289484f-bc5f-4972-9f27-3b516da500fb.png)

I get this sort of url which is shortend url
![image](https://user-images.githubusercontent.com/79985986/211732806-c0590731-f350-4c81-bb29-0babbfc36c6e.png)

  Now when I refresh the page or make any changes in the chart this url gets updated. 
![image](https://user-images.githubusercontent.com/79985986/211732934-ca41e5d9-45ad-4ff2-8a40-2909e44bc9fd.png)

The problem is I want to embed this chart in my webpage. Since the url before and after are different I always see a chart which is before version and not the latest one. 
How can we address this problem with a static url so that i always see a latest chart only.

**Comment by michael-s-molina** [comment]
Hi @snehlata08. I can see from the screenshots that you're not using the most up-to-date version of Superset. In the latest version, we use permalinks when generating embeddable code. What version of Superset are you on?

**Comment by snehlata08** [comment]
I am using superset 1.0.0

**Comment by michael-s-molina** [comment]
I suggest you upgrade to 2.0.1 as 1.0.0 is not supported anymore. Make sure you read [UPDATING.md](https://github.com/apache/superset/blob/master/UPDATING.md) and [CHANGELOG.md](https://github.com/apache/superset/blob/master/CHANGELOG.md) before the upgrade 😉

**Comment by snehlata08** [comment]
Thanks
