### ISSUE TITLE
@superset-ui/embedded-sdk 0.1.0-alpha.8 not working

### ISSUE THREAD

**Issue by tejaskatariya** [apache/superset#22683]
After installing latest @superset-ui/embedded-sdk

It is having error that switchboard which gets installed with NPM package has no esm or lib directory

### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by S4dhu** [comment]
Same
Error:
```
ERROR in ./node_modules/@superset-ui/embedded-sdk/lib/index.js 8:19-54
Module not found: Error: Can't resolve '@superset-ui/switchboard' in '/app/node_modules/@superset-ui/embedded-sdk/lib'
```
Reverting to the previous version of @superset/embedded-sdk didn't help.

Temporary fix: 
1. Go to node_modules/@superset-ui/embedded-sdk
2. Change dependencies in **package.json** from **"@superset-ui/switchboard": "^0.18.26-0" to "=0.18.26-0"**
3. Manually run **npm install**

**Comment by rusackas** [comment]
I believe this was all solved, and was a temporary problem. If anyone is experiencing this in the current version, we can revisit/reopen.
