### ISSUE TITLE
Cross-filtering resets the table column sorting

### ISSUE THREAD

**Issue by saghatelian** [apache/superset#22691]
Cross-filtering resets the table column sorting.

#### How to reproduce the bug

1. Create 2 table charts, prefferably with 300+ rows, that have at least one column in common (in my example I use the table birth_names from the Superset example DB for both table charts)
2. Enable "DASHBOARD CROSS FILTERS" for both table charts
3. Put both table charts on a dashboard (let's call them "Table 1" and "Table 2")
4. Click on a column title on "Table 2" to sort by that column.
5. Click on a table cell on "Table 2" to "cross-filter" the data of the "Table 1"  

### Expected results
The "Table 1" data should be filtered, while the "Table 2" should remain unchanged, i.e. sorted by the selected column regardless of the table cell clicked

### Actual results
The sorting is automatically lost (reset) every time I click on any cell. 
Weirdly, although both table charts use the same data source, the bug affects only one of the tables. As you can see from the screen recordings, the sorting is lost when I click on a cell in "Table 2", but isn't lost when I click on a cell in "Table 1".

#### Screenshots
[Screen recording 2023-01-11 11.01.05 PM.webm](https://user-images.githubusercontent.com/43491361/211897861-2d02eb2e-b02a-4b7d-85c0-d99ce9028237.webm)

[Screen recording 2023-01-11 11.02.48 PM.webm](https://user-images.githubusercontent.com/43491361/211897794-13b6c34c-1ffb-4ad7-9996-be57c5f38e1f.webm)

### Environment

(please complete the following information):

- browser type and version:  Google Chrome Version 107.0.5304.110 (Official Build) (64-bit)
- superset version: `2.0.1` (official docker image)
- any feature flags active:
    "DASHBOARD_CROSS_FILTERS": True,
    "ALERT_REPORTS": True,
    "ENABLE_TEMPLATE_PROCESSING": True,
    "ENABLE_TEMPLATE_REMOVE_FILTERS": True,
    "GENERIC_CHART_AXES": True

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [N/A] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Assigning to @kgabryje but I believe @geido is also looking at crossfilter related issues these days.
