### ISSUE TITLE
Helm: Job init-db doesn't support concurrent release in same namespace

### ISSUE THREAD

**Issue by caparisi** [apache/superset#22757]
We deploy many Superset by Helm chart in the same Kubernetes Cluster (and same namespace). Each helm release have a unique name, but all release will create the job to init the db with the name `superset-init-db`, which create conflict ( fail with `Hook post-install superset/templates/init-job.yaml failed: jobs.batch "superset-init-db" already exists`, DB not initialized ....)

#### How to reproduce the bug

1. Deploy many (3-4) Helm char in same time
2. Look your pods, you will see some job be interrupt to be replace by a other one from a other release
3. Look your jobs, you will see only 1 job `superset-init-db` whatever the number of release run in same time

### Expected results

We expect 1 job unique job  `superset-init-db` by Helm release,  with a name like `my-custom-superset-name-init-db`

### Actual results

We have only 1 job which the same name for all Helm release which  not include the specific release name.

### Environment

- HELM chart version: 0.7.6
- superset version: 1.5.3

### Additional context

The root cause look like to come from the job template (https://github.com/apache/superset/blob/master/helm/superset/templates/init-job.yaml#L21) which use `superset.name` instead of `superset.fullname` like in deployment template.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!

**Comment by caparisi** [comment]
We still have the issue, please keep it alive :smile_cat:

**Comment by rusackas** [comment]
Re-opening, but can you add some context, or what might have changed lately, if anything? If nobody else has complained in over a year, there must be a workaround or something... I'm not sure what to make of it :)

**Comment by craig-rueda** [comment]
This type of use case is fairly non-standard. Typically, an instance of superset should be installed in its own namespace.

**Comment by rusackas** [comment]
Closing again, since it's been another four months or so without any activity, and it sounds like we might not be supporting this going forward. If anyone wants to volunteer to tackle this further, I'm happy to re-open it.
