### ISSUE TITLE
500: Internal server error

### ISSUE THREAD

**Issue by Andkov440** [apache/superset#22819]
Command for start superset:
superset run -p 8088 --host 0.0.0.0
The error appeare after login. 

#### Screenshots
![Screenshot_4](https://user-images.githubusercontent.com/25137962/213914717-f7518387-13b9-491f-9a1e-c351ff8ace01.png)
![Screenshot_5](https://user-images.githubusercontent.com/25137962/213914790-947e70b9-6a13-42e4-988d-399ab3fd9e3a.png)

### Environment

- browser type and version: Google Chrome 109
- superset version: 2.0.1
- python version: 3.8.10

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by artemonsh** [comment]
Try this code:
```
pip uninstall wtforms
pip install wtforms==2.3.3
pip uninstall flask
pip install flask==2.0.3
pip uninstall werkzeug
pip install werkzeug==2.0.3
```

**Comment by Andkov440** [comment]
Thank you! The error is gone. Спасибо!

**Comment by rusackas** [comment]
Woohoo! Closing as resolved. Thanks @artemonsh !
