### ISSUE TITLE
How to change/customize the url in superset?

### ISSUE THREAD

**Issue by sedanursayer** [apache/superset#22850]
Hi! i want the URL to look exactly like this. I've seen a few studies on this, but couldn't find anything on how it's done. Like typing "localhost/mycompany/welcome" instead of "localhost/superset/welcome". or as it looks like localhost/mycompany/sqllab.. can someone help with this?

**Comment by rusackas** [comment]
The answer remains the same as yesterday in https://github.com/apache/superset/issues/22842

You'll have to go through and change a fair amount of code in both the frontend and the backend of the application. It isn't built for this. It might be plausible to open a PR that makes this configurable, but that doesn't exist today. 

This isn't a bug, so I'm closing it again. You can see if anyone's willing to help on the #customizing-superset channel on Slack, or open an Ideas thread on the Discussions tab above to see if others are interested in the idea of making it configurable and opening a PR. Or if you want to do the engineering work and open a PR, we're happy to help review it.
