### ISSUE TITLE
Renaming a database triggers thousands of SQL queries in order to update the table permission key

### ISSUE THREAD

**Issue by john-bodley** [apache/superset#22867]
Recently at Airbnb the action of renaming our "Presto" database to "Trino" triggered a SEV-2 incident as the perceived benign action resulted in executing thousands of MySQL queries, per [here](https://github.com/apache/superset/blob/e23efefc462fcc6f76a456f52f57f81e0c241a0a/superset/databases/commands/update.py#L105-L129)—given that we have 100,000+ datasets associated with the Presto database—as the database name (as opposed to the database ID) is included in the permission key encoding.

We (Airbnb) have our own security manager which completely bypasses the FAB permission model, i.e., we ignore the dataset level  permission key. That said the explicit serialization of the permission key has always bemused me. Maybe it's there for efficiency, i.e., doesn't require an additional join(s) to resolve, but it doesn't adhere to the DRY principle and causes issues like the one described here.

Granted aspects of Superset entities are somewhat fluid in nature, i.e., a table, schema, chart, etc. could be rename, but IDs rather than names are likely preferred for encoding a unique—albeit non-human friendly—identifier. This would mean than renaming a database, table, slice, etc. would be a no-op from a permission standpoint.

The permission encoding is currently:

- `slices.perm`.`tables.perm`: `[<database name>].[<dataset name>].(id:<dataset ID>)`
- `slices.schema_perm`/`tables.schema_perm`: `[<database name>].[<schema name>]`

where slices inherit their permissions from the dataset (per [here](https://github.com/apache/superset/blob/050cbe938ff74a3aea829ebf46350777999c81e1/superset/models/slice.py#L356-L363)). The serialization of permissions likely stems from the time when Superset supported multiple connectors: SQL and Druid NoSQL and the dataset ID wasn't unique (hence the datasource ID/datasource type tuple). Personally I think it would be great to make this fully implicit, i.e., using the ID or UUID and/or having dynamically resolved SQLAlchemy properties (which may be needed for the `schema_perm`.

At a bare minimum [this](https://github.com/apache/superset/blob/e23efefc462fcc6f76a456f52f57f81e0c241a0a/superset/databases/commands/update.py#L115-L129) logic could be refactored to be a single query as opposed to a per dataset query using a join.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
@john-bodley closing this as stale, but feel free to re-open/revisit as warranted.
