### ISSUE TITLE
Dashboards api is broken after migration from 1.3 to 1.5

### ISSUE THREAD

**Issue by xneg** [apache/superset#22870]
Hi!
We've used Superset version 1.3 for the last year. Now we try to upgrade to version 2.0. 
Migration applied ok, most things are working but there is a problem with dashboards api. 

When I send request to endpoint `/api/v1/dashboard/` I get this error:
` "Detected unaliased columns when generating joined load.  Make sure to use aliased=True or flat=True when using joined loading with with_polymorphic()."`

Here is the stacktrace:
```
Traceback (most recent call last):
  File "/app/superset/views/base.py", line 210, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/base_api.py", line 423, in get_list_headless
    duration, response = time_function(super().get_list_headless, **kwargs)
  File "/app/superset/utils/core.py", line 1524, in time_function
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/api/__init__.py", line 1517, in get_list_headless
    count, lst = self.datamodel.query(
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/models/sqla/interface.py", line 471, in query
    query_results = query.all()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3531, in __iter__
    context = self._compile_context()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 4085, in _compile_context
    entity.setup_context(self, context)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 4450, in setup_context
    loading._setup_entity_query(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 318, in _setup_entity_query
    value.setup(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/interfaces.py", line 555, in setup
    strat.setup_query(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/strategies.py", line 1560, in setup_query
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Detected unaliased columns when generating joined load.  Make sure to use aliased=True or flat=True when using joined loading with with_polymorphic().
```

I investigated a bit in this and found that the problem was caused by this code from FAB:

```
count, lst = self.datamodel.query(
            joined_filters,
            order_column,
            order_direction,
            page=page_index,
            page_size=page_size,
            select_columns=self.list_select_columns,
        )
```
Specifically, line `select_columns=self.list_select_columns`. This list_select_columns comes from [here](https://github.com/apache/superset/blob/f8edcd7ae2f1a716505327770b5abaa7691c784a/superset/dashboards/api.py#L156).

I'm not very strong in FAB ORM and SQLAlchemy. What I see is that schema of `dashboards` table hasn't changed. So I'm not sure why after migration it doesn't work as intended.
Maybe someone could help me in this question?

P.S. I'm not sure it is a proper bug but I didn't find an appropriate tag for my issue.

### **Edit: The same error when upgrading to version 1.5.**

**Comment by rusackas** [comment]
Pinging @eschutho and @AAfghahi in case this indicates something that needs to be patched in 2.0.2. I'm guessing most people made it to 1.5 before upgrading to 2.0, so I'm wondering if there's something different when making that large of a leap.

**Comment by xneg** [comment]
I finally localized the problem. This error was because I introduced our custom SecurityManager with custom User class:
```
class CustomUser(User):
    __tablename__ = 'ab_user'
    email = Column(String(64), unique=False, nullable=False)


class CustomSecurityManager(SupersetSecurityManager):
    user_model = CustomUser
```
I've done this in the first place to overcome the issue with unique email constraint. It worked for version 1.3 but stopped since 1.5.
So, maybe any suggestions on how properly remove unique email constraint?

**Comment by AAfghahi** [comment]
Since this is a custom feature I don't think that we are going to be able to fix it in 2.0.2. Though to get around the unique-ness clause, instead of creating a custom User, there is a way to use email aliases.

**Comment by xneg** [comment]
@AAfghahi yes, sure it doesn't require any fixes in 2.0.2.
> Though to get around the unique-ness clause, instead of creating a custom User, there is a way to use email aliases.

Can you explain more in detail, please? What I've found in the first place and why I created custom User is this point from FAB docs:
https://flask-appbuilder.readthedocs.io/en/latest/security.html#your-custom-security

**Comment by Step1N** [comment]
I am also getting same error after removing email unique constraint.

Superset version 2.1

**Comment by rusackas** [comment]
We're now on 3.1, on the verge of 4.0, and not supporting 2.x  or prior versions actively. If folks are experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)
