### ISSUE TITLE
 can't find '_main_' module in 'superset'

### ISSUE THREAD

**Issue by zeynepkoyun** [apache/superset#22918]
Hello @eschutho  @craig-rueda  @hughhhh @michael-s-molina 
When I want to run the Superset project directly from the github project instead of installing it in virtualenv, I get the following error.
Error Description: can't find '_main_' module in 'superset'

**Comment by zeynepkoyun** [comment]
Thanks for your answer. I'm working with python 3.8 on a windows machine and I want to install locally instead of docker. However, "gunicorn" used as an application server does not work for windows, can an alternative such as "waitress" be used instead?

**Comment by rusackas** [comment]
Sounds like this is intrinsically tied with https://github.com/apache/superset/issues/22922 - I assume you're working together. Can we close one of these duplicate issues?

As I mentioned on the other thread, @indows is not officially supported, but you can ask around in the #deploying-superset channel on Slack, or start a Q&A Discussion here on the repo look for anyone else attempting this.

**Comment by zeynepkoyun** [comment]
Similar issue but I haven't tried running it with a different application server yet. I will follow up on this issue as well. For now, I'm looking at the installation process from source.
