### ISSUE TITLE
Peru geojson file is huge

### ISSUE THREAD

**Issue by mabhub** [apache/superset#22923]
`@superset-ui/legacy-plugin-chart-country-map` provides geometry for 85 countries.  
Most of these GeoJSON files weight is 50 ~ 300 Ko. The *largest* country (Russia) file is 750 Ko.

→ Peru is **9.5 Mo**. ❗

As compared to neighboring countries, Peru's geometry is over-detailed.

#### How to reproduce the bug

1. List files in `superset-frontend/plugins/legacy-plugin-chart-country-map/src/countries/`

### Expected results

Having homogeneous geometry précisions

### Actual results

The geometry of Peru is extravagantly large compared to other countries.

#### Screenshots

![image](https://user-images.githubusercontent.com/1846633/215825137-6cc74683-f894-4ab1-963e-4ca509757ef1.png)

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Added some screenshots of what the map looks like in testing. It looks like the GeoJson needs some dialing in, but hopefully that can be addressed soon, and we can close out this PR with it. Thanks for both the ticket and the contribution!

**Comment by rusackas** [comment]
It's no longer that big... they were all regenerated and are reasonably sized now.

<img width="480" alt="image" src="https://github.com/apache/superset/assets/812905/63b345b5-df4e-4b66-8290-c04cbab30ac6">
