### ISSUE TITLE
cannot load additional db driver correctly in K8S POD

### ISSUE THREAD

**Issue by sycbbyes** [apache/superset#22962]
#### How to reproduce the bug

1. install superset image on K8S
2. want to add elasticsearch db driver
3. access the linux os ssh , pip install elasticsearch-dbapi
4. but make no sense, becasue OS user superset cannot restart gunicorn application
5. while the K8S POD can only be replaced if restart it
6. at least, superset should provide a shell scripts to restart the superset application  or allow user to pre-install necessary db driver

### Expected results

can easly mantain superset application via command line as OS user superset

### Actual results

not able to restart superset application via command line as OS user superset

### Environment

superset 2.0.1

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ 1] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ 1] I have reproduced the issue with at least the latest released version of superset.
- [ 1] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

sycbbyes@163.com

**Comment by sycbbyes** [comment]
any idea?

**Comment by rusackas** [comment]
This is not my forté, but does it need to be that user that installs/restarts things? Can you do so with another admin user account? I've pinged @craig-rueda who's more knowledgeable here to answer or redirect the issue, but you might also consider taking this up on the `#deploying-superset` channel on the Superset Slack workspace.

**Comment by sycbbyes** [comment]
thanks, you are right, wo copy it to discussion, it should not be an issue. @craig-rueda

**Comment by sycbbyes** [comment]
close it.

**Comment by sycbbyes** [comment]
close it.

**Comment by rusackas** [comment]
Closing as requested. Thanks!
