### ISSUE TITLE
superset not able to connect to Trino with SSL+Keycloak

### ISSUE THREAD

**Issue by debimishra89** [apache/superset#22978]
#### How to reproduce the bug

1. Go to superset UI
2. Click on 'Data'. then "+" database
3. choose Trino conection, put trino connection string, then click on 'test connection'
4. See error: 'unauthorized'

### Expected results

connection should be successful

### Actual results

throwing error: 'unauthorized'

### Environment

(please complete the following information):

- browser type and version: chrome
- superset version: 1.4.2
- python version: 3.8.10
- node.js version: not installed

### Checklist

Error logs from Superset:
`[SupersetError(message="error 401: b'Unauthorized'", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'Trino', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
2023-02-03 17:17:48,221:WARNING:superset.views.base:[SupersetError(message="error 401: b'Unauthorized'", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'Trino', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
2023-02-03 17:17:48,223:INFO:werkzeug:10.10.1.26 - - [03/Feb/2023 17:17:48] "POST /api/v1/database/test_connection HTTP/1.1" 422 -
`
Trino conection string used in superset:
`trino://test124:xxxxxx@dasec-trino.dastc.stee.com:8081/postgresql`

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

FYI, I am able to access trino UI

Trino config.properties file:
`coordinator=true
node-scheduler.include-coordinator=true
http-server.https.enabled=true
http-server.https.port=8081
http-server.https.keystore.path=/opt/darc/trino/ssl/dasec-trino.dastc.stee.com.p12
http-server.https.keystore.key=trino
discovery.uri=https://dasec-trino.dastc.stee.com:8081
http-server.authentication.type=oauth2
http-server.authentication.oauth2.issuer=https://dasec-keycloak.dastc.stee.com:8443/auth/realms/darc
http-server.authentication.oauth2.client-id=trino
http-server.authentication.oauth2.client-secret=xxxxxxxxxxxxxxxxxxx
internal-communication.shared-secret=xxxxxxxxxxxxxxxxxxxxxxxxxxx
http-server.authentication.oauth2.oidc.use-userinfo-endpoint=true
web-ui.authentication.type=oauth2
web-ui.enabled=true
`

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
