### ISSUE TITLE
Unable to get data of Present Month in Apache Superset

### ISSUE THREAD

**Issue by hassan-turi** [apache/superset#22976]
I am using Apache Superset for reporting purpose. I am want to draw a chart to show the graph for present Month. I used several ways but it is showing me the last day of the month. I used this method and other like start of this month It is showing me end of this month. Please show me the correct way to get the data of the current month.
![image](https://user-images.githubusercontent.com/87395528/216524257-b86ee8af-e2c1-4427-b2df-52544b0d2ca4.png)

**Comment by rusackas** [comment]
This isn't a bug, but I'll answer it to close it. These questions can be asked on the Superset Slack workspace (let me know if you want the link) or in the Q&A section of the DIscussions tab. 

That said, it sounds like you're looking for the first day of the current month until now. There's probably more than one way, but you can do that like so:
<img width="588" alt="image" src="https://user-images.githubusercontent.com/812905/216667561-9b2aa11f-766c-455b-8013-33228a6a16ca.png">
