### ISSUE TITLE
Superset default table chart adding 8 hours to the timestamp when using time grain.

### ISSUE THREAD

**Issue by vipulneo** [apache/superset#23008]
When a user changes the time grain for example timestamp to seconds/day/ the widget add 8hrs(offset) to it most likely treats it as a local timestamp.
Users ahead of UTC get a different Month as it fall to the last month when -offset to it.

#### How to reproduce the bug

See the attachment
Orignal Value:
<img width="824" alt="Screenshot 2023-02-06 at 3 44 06 PM" src="https://user-images.githubusercontent.com/381002/217112373-b71734bb-c3ff-47a1-ace2-ca3cae56bbde.png">

After applying time grain.
<img width="796" alt="Screenshot 2023-02-06 at 3 48 43 PM" src="https://user-images.githubusercontent.com/381002/217113144-2b169c16-5115-4d7b-9760-1546cb23a62f.png">

### Expected results
Should not add the offset.
what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: `2.0`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
Query Engine: Trino

**Comment by Shazad-khan** [comment]
![image](https://user-images.githubusercontent.com/100838455/226522489-8eac5716-3c99-4353-b4ce-666bffef2fbb.png)

The issue has already been resolved we can see different time other than 8:00. please cross check and close this issue.
