### ISSUE TITLE
Time Series Graph with other non-main druid table column generates error

### ISSUE THREAD

**Issue by albertojarabo** [apache/superset#23002]
Im trying to create a Time Series V2 Graph on Superset based on a time column that is not the main that Druid works with. So I create a Dataset based on a Select with a CAST from a VARCHAR field to TIMESTAMP. The query works well, the Graph form seems to be working but when I try to update results, it appears an error.

#### How to reproduce the bug

1. Create a druid connection
2. Create a druid dataset from a table
3. Open SQLEditor
4. Create a query that uses other field (varchar field with timestamp) and cast it to timestamp
5. Run the query and check that works.
6. Press on Create Chart when query has finished
7. Check that no time field is set on Time Column, and the CASTed field is still a Varchar field.
8. Try to cast inside the CustomSQL tab in Time Column and CAST it again.
9. See error

### Expected results

Superset should use the new Time Field for the ghrap.

### Actual results

No time field is found despite having configured it. And If you try to force the cast inside the Time Column's CustomSQL it shows an error.

#### Screenshots

![image](https://user-images.githubusercontent.com/7034464/217032286-965649c1-d676-4119-8b38-2d4e75c1325b.png)

![image](https://user-images.githubusercontent.com/7034464/217032655-5fe7275e-cd10-4574-ad88-6ddfa2d2dce8.png)

![image](https://user-images.githubusercontent.com/7034464/217032742-391be4ad-0889-4f67-a631-1699fc546f1f.png)

![image](https://user-images.githubusercontent.com/7034464/217032952-5f830955-4a53-4f4f-8b5b-b448537213b8.png)

![image](https://user-images.githubusercontent.com/7034464/217033107-f0001b84-e00d-433d-8653-5e6504b8f679.png)

###  Environment

(please complete the following information):

- browser type and version: Chrome 109.0.5414.120 (Build oficial) (64 bits)
- superset version: `superset version`: 2.0.0
- python version: `python --version` 3.8.12
- druid version: 25.0.0

**Comment by rusackas** [comment]
Hmm... as you can see by the `abc` label next to the `__time` column, Superset is not picking this up as a Temporal column. Can you try editing the dataset (via the three dots next to the table name in the left column) and explicitly marking that `__time` column as "temporal"? That _might_ kick it into gear, but I'm not sure why it didn't pick that up automatically.

**Comment by albertojarabo** [comment]
it worked well, thank you!
