### ISSUE TITLE
Remove chart from dashboard results in `cannot read properties of undefined (reading 'type')`

### ISSUE THREAD

**Issue by rumbin** [apache/superset#23015]
#### How to reproduce the bug

1. Go to a dashboard which shows thus behavior (which will be the trickiest part about this issue)
2. Click EDIT DASHBOARD
3. Click the Trash icon of any affected chart (not all charts of the dashboard are necessarily affected)

### Expected results

I can remove the chart from the dashboard.

### Actual results

Error message:

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/1220356/217196328-e20c4d58-0c5a-4138-8d57-86ae6fe461b8.png">

This is what the browser console says:
<img width="815" alt="image" src="https://user-images.githubusercontent.com/1220356/217196512-a2aa18c6-eea8-4665-8bb4-6addf724e723.png">

```
TypeError: Cannot read properties of undefined (reading 'type')
    at $i (activeAllDashboardFilters.ts:47:21)
    at activeAllDashboardFilters.ts:66:5
    at Array.forEach (<anonymous>)
    at $i (activeAllDashboardFilters.ts:65:26)
    at activeAllDashboardFilters.ts:66:5
    at Array.forEach (<anonymous>)
    at $i (activeAllDashboardFilters.ts:65:26)
    at activeAllDashboardFilters.ts:66:5
    at Array.forEach (<anonymous>)
    at $i (activeAllDashboardFilters.ts:65:26)
```

Refresh the web page when the error is shown; it jumps our of edit mode and the chart is still at its place.

* Trying to remove the whole dashboard row results in the same error.
* Copying the dashboard and trying to remove the chart from the copy does not help.
* Removing all dashboard filters does not help.
* Removing all cross filter settings from the dashboard's JSON does not help.

#### Screenshots

See above...

### Environment

We run Superset 2.0.1 from the docker images.

- browser type and version: Chrome, Version 109.0.5414.119 (Official Build) (arm64)
- superset version: 2.0.1
- python version: `python --version` FIXME
- node.js version: `node -v` FIXME
- feature flags:
```python
FEATURE_FLAGS = {
    "SQLLAB_BACKEND_PERSISTENCE": True,
    "ENABLE_TEMPLATE_PROCESSING": True,
    "DASHBOARD_CROSS_FILTERS": True,
    "ALERT_REPORTS": True,
    "DASHBOARD_NATIVE_FILTERS": True,
    "GENERIC_CHART_AXES": True,
    "DASHBOARD_NATIVE_FILTERS_SET": True,
    "DASHBOARD_CACHE": True,
}
```

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

We experienced similar issues before on the same Superset instance. In these cases the dashboards got imported from an instance which runs the current dev version of the `master/main` branch. We assumed that importing from a different Superset version caused the error in these cases.

However, the case that I am describing above is happening on a dashboard which was exclusively created and modified on the same instance.

Any help is welcome. I'll happily add more debugging info if you tell me what is needed.

**Comment by rumbin** [comment]
Nevermind, I just learned that the dashboard actually _was_ and imported one.
So, the issue remains, but I'm currently not willing to investigate this any further, as I suppose the issues come from version mismatches...

**Comment by rumbin** [comment]
It just happened again on a non-imported dashboard.
After adding a chart from the Explore workflow, it appeared twice on the dashboard:
* once on a tab within a tab
* and once outside of all dashboard tabs.

Trying to remove any of the two instances will result in the error reported above.

**Comment by rumbin** [comment]
I was able to revive the broken dashboard by manually tweaking the Superset metastore:
* remove the affected chart-dashboard association in `dashboard_slices`
* remove all occurrences of the chart in the dashboard's `position_json` field:
    * paste the content to e.g. VS code and format it to have human readable JSON
    * remove all occurrences of the chart's ID in `CHART-*` nodes, e.g. `CHART-explore-332-1`
    * remove all `ROW-*` instances that contain the chart ID
    * remove the `ROW-*` IDs, that we just deleted, from any `GRID_ID.children` nodes
    * paste the modified JSON back to the DB table
* Reload the dashboard
* Add the chart again via the dashboard edit mode

Pretty ugly hack, but it was at least an ad-hoc solution of my issue.

However, this bug is definitely nasty, as it renders the dashboard virtually unusable for further edits.

**Comment by rumbin** [comment]
It seems to me that the following had gone wrong when adding the chart to the dashboard from Explore:
It was added at the bottom at the dashboard, as it's supposed to be.

But it **seemed to have replaced an existing chart** in a nested tab as well.

After I deleted the broken chart positions as described above, the chart that had been replaced, reappeared at the bottom of the dashboard.

**Comment by rodionxabibov** [comment]
@rumbin I faced the same problem, thanks for solving the problem!

**Comment by rusackas** [comment]
I'm guessing from the long period of silence that this is effectively resolved. Let me know if I'm wrong, and/or you think any docs need to be updated to help others in the future.
