### ISSUE TITLE
No warning when deleting a dataset used in dashboard native filters

### ISSUE THREAD

**Issue by sfirke** [apache/superset#23034]
It's helpful that Superset will tell you when you go to delete a dataset, "this is used in 2 charts that appear in 3 dashboards."  But it doesn't report on usage in dashboard _filters_.  When replacing one dataset with another, the native filter usage needs to be replaced, too, and Superset should alert if deleting the dataset will break filters.

#### How to reproduce the bug

1. Create a dashboard and use a dataset column in a filter
2. Delete the dataset
3. View the dashboard.  It will have a red box "Cannot load filter"

### Expected results

When I try to delete the dataset, the statement about usage should include "and is used in X filters on Y dashboards."

### Actual results

No warnings about usage in filters.  Deletion proceeds and the dashboard filters silently break.

### Environment
Superset 2.0.1

*Edit: I removed a related but separate and less-important part of this issue to focus on the main problem: not warning before deleting.*

**Comment by sfirke** [comment]
Related: the user should be warned if a report they try to delete is used in a scheduled report or alert (#23059).

**Comment by rusackas** [comment]
tempted to close this as stale, but let me know your thoughts @sfirke :)

**Comment by sfirke** [comment]
I can try to reproduce it. It was an annoying bug, I deleted a dataset and inadvertently broke a dashboard.

**Comment by rusackas** [comment]
As nice as it would be if someone tackled this, it seems to have gone stale. Feel free to reopen if you see it in current versions and/or want to tackle it ;)

**Comment by sfirke** [comment]
I'm fine with closing it ... it would be a nice addition, but so low priority that it doesn't help to have it linger forever on our open issues.

**Comment by rusackas** [comment]
Exactly... while people don't like their issues closed, wouldn't it be nice to get to a number of issues where we have even a vague idea of what they are and what the priorities might be?
