### ISSUE TITLE
Azure OAuth Redirect is http instead of https

### ISSUE THREAD

**Issue by ironhacker** [apache/superset#23036]
Using OAuth2 for Azure, the redirect URI sent on sign in is "http" when it needs to be "https" and I cannot find a way to override it.  I did configure the redirect URI on Azure, but it MUST be "https".

#### How to reproduce the bug

1. Install Superset using Docker Compose
2. Configure Nginx to proxy behind SSL.
3. Configure Azure App and get Application ID, Tenant ID, and Secret.
4. Configure OAUTH_PROVIDERS in superset_config_docker.py according to docs:  https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-oauth
5. Restart and attempt to sign in.

### Expected results

Successful Sign In

### Actual results

Azure Error:  AADSTS50011: The redirect URI 'http://[my-domain]/oauth-authorized/azure' specified in the request does not match the redirect URIs configured for the application.

### Environment

(please complete the following information):

- Google Chrome Current:
- superset version: git latest 2023-02-08 - Docker Compose

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

In OAUTH_PROVIDERS, I tried defining redirect_uri, and redirect_url under the root, remote_app, and remote_app/client_kwargs to no avail.

**Comment by ironhacker** [comment]
I spent sooooooooooo much time on this. Fix by ENABLE_PROXY_FIX=True

**Comment by xiaolu-tan** [comment]
@ironhacker  - Hello, I had faced the same issue. but it didn't worked with your solution(ENABLE_PROXY_FIX=True). Could you please share the config file without confidential info to me? thank you.

**Comment by scott01272001** [comment]
I slove this issue by modified the 'run-server.sh'  and 'docker-bootstrap.sh' located in the docker folder of the source code.

Here are the changes I made:
- run-server.sh:
    add arguments --certfile and --keyfile to gunicorn command

- docker-bootstrap.sh
    changed the path from ''/usr/bin/run-server.sh' to '/app/docker/run-server.sh', the original path pointed to the script that was 
    created during image building. It should point to the file we mounted.

**Comment by mummyhen** [comment]
Is there a fix for this? I have configured Azure Oauth2 with `ENABLE_PROXY_FIX = True`, HTTPS traffic is terminated on the Network Load Balancer but I still get redirected to HTTP

**Comment by shxpark** [comment]
Any other suggestions than the ENABLE_PROXY_FIX? Still running into this issue on v4.1.1. SSL is terminated behind ELB.

**Comment by mohag** [comment]
Looking [at the docs, the `X-Forwarded-Proto` header needs to be set to `https`](https://superset.apache.org/docs/configuration/configuring-superset/#configuration-behind-a-load-balancer) as well...
