### ISSUE TITLE
Superset is adding unnecessary Group By clause in MapBox query

### ISSUE THREAD

**Issue by ali-xflow** [apache/superset#23043]
#### How to reproduce the bug

1. Create a new chart.
2. Choose a Dataset
3. Save the dataset
4. Choose mapbox in the chart options
5. Click on view query

### Expected results

Mapbox should show results with all values of longitude and latitude.
### Actual results

Mapbox only show results with distinct, unique values of longitude and latitude, and it adds a group by clause in query.

#### Screenshots
This is the result i am getting
<img width="655" alt="image" src="https://user-images.githubusercontent.com/114662678/217726756-5bf24a96-760d-45db-874d-9d2dc70b0b08.png">
Total rows should be 983:
<img width="482" alt="image" src="https://user-images.githubusercontent.com/114662678/217726841-99af3683-5492-4987-8e59-15ac3708d938.png">

### Environment

(please complete the following information):

- Edge
- Using default docker-compose-non-dev.yml to set the environment

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

The mapbox works perfectly in a development environment, but this issue exists only in production environment. Is there any way to modify query so it removes the group by clause so i get all the values

**Comment by malihaque** [comment]
I am facing the same issue ,Kindly someone please recommend the possible solution

**Comment by asadal12** [comment]
<img width="161" alt="image" src="https://user-images.githubusercontent.com/85455544/219030218-0397988d-d447-4b6a-be5e-4a6b28a77db4.png">
Add the primary key, along with latitude and longitude in Dimension and the issue will be resolved.

**Comment by ali-xflow** [comment]
Thank you, It works
