### ISSUE TITLE
Adding custom color palettes/ Color themes to Charts and Branding in Superset

### ISSUE THREAD

**Issue by srinichalla9** [apache/superset#23045]
Hi team,

I've a requirement to customize the legends' colors in Pie Charts and also needs to change the font size and colors for headers and titles as per our organization standards for our superset instance.

By default I could see a limited color schemes for Pie Charts, but I wanted to change the legend colors for categories as per our standard color codes and similarly fonts formatting as well.

![image](https://user-images.githubusercontent.com/117988954/217739684-45e740f4-0824-4607-a423-2a94f8f4e454.png)

Could you please guide me on this requirement.

Please let me know if you have any questions.

Thanks,
Srini

**Comment by shalnice** [comment]
Hello @srinichalla9 

To force specific colors on the chart legends, you do it via JSON metadata in the << Edit dashboard properties >>. Please refer to tutorial below on how to do it : https://www.youtube.com/watch?v=AMC-WOgSBBg

As for the header, i believe the only way to do it to modify the CSS template. Try the following code : 

.dashboard-component-header {
  color: white;
  background : blue;
  text-align : center;
  font-size : 20px;
  font-family : sans-serif;
}

**Comment by irina-popov** [comment]
You can specify your custom color scheme in config.py (or superset_config.py.) Then when you edit a dashboard your color scheme will appear in the dropdown list.
<img width="850" alt="Screenshot 2023-04-13 at 12 15 10" src="https://user-images.githubusercontent.com/36771748/231713986-f82eca7b-2e53-4442-83e0-f5e586cadf0c.png">

**Comment by hxj8059** [comment]
> You can specify your custom color scheme in config.py (or superset_config.py.) Then when you edit a dashboard your color scheme will appear in the dropdown list. <img alt="Screenshot 2023-04-13 at 12 15 10" width="850" src="https://user-images.githubusercontent.com/36771748/231713986-f82eca7b-2e53-4442-83e0-f5e586cadf0c.png">

Hi, do I need restart superset after add color schemes？

**Comment by rusackas** [comment]
Yep, you need to restart Superset after any config change. Hopefully this is all settled, but otherwise closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering issues in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
