### ISSUE TITLE
home page error message

### ISSUE THREAD

**Issue by evolution232634** [apache/superset#23046]
In k8s, After the installation and login are successful, an error message is displayed on the home page
![87365aa3021655d6a9b68a0acb2a97d](https://user-images.githubusercontent.com/46314984/217745516-aac9fce5-f217-4183-a69a-d4ba0f405529.png)

**Comment by sfirke** [comment]
This needs more information to be a useful bug report.  If you are still facing this problem and working on it, please complete the issue template and include your Superset version, details about deployment, what you've tried, etc.

**Comment by evolution232634** [comment]
> This needs more information to be a useful bug report. If you are still facing this problem and working on it, please complete the issue template and include your Superset version, details about deployment, what you've tried, etc.

superset version is 0.8.5
this is k8s container log


[container.log](https://github.com/apache/superset/files/10780109/container.log)

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
