### ISSUE TITLE
Change the chart type by clicking

### ISSUE THREAD

**Issue by ostmal** [apache/superset#23050]
Hello!
Recently I started to master Superset. I would be grateful for a hint: is it possible to place icons (buttons) next to the visualization and when clicking on the icon, the chart (visualization) would change to a different type with the same dimensions and measures?

**Comment by sfirke** [comment]
No, this is not something that can be made user-facing.  Some of the chart types retain their measures and dimensions when switching between them in editing mode, but that's only when editing a single chart.

**Comment by rusackas** [comment]
Agreed with @sfirke here. These TRY to normalize/denormalize form (control input) data when switching from viz to viz, but it's not bulletproof enough (nor will it likely be) to make this happen in the dashboard context. I'll close this for now in terms of being an issue/bug, but you're welcome to propose designs/ideas in an Ideas thread in the Discussions area here on Github.
