### ISSUE TITLE
HTTPS POST /api/v1/security/guest_token to Superset in AWS is directed to HTTP GET causes HTTP status code, 405

### ISSUE THREAD

**Issue by little-grain-of-wheat** [apache/superset#23060]
I have deployed Superset as a Docker container in AWS and would like to embed dashboard in my front-end.

My back-end sends 2 Superset requests below:
1. POST /api/v1/security/login (to login to Superset)
    
    The API returned HTTP status code, 200 with access_token and refresh_token.
    
2. POST /api/v1/security/guest_token (to fetch guest token which will be used by my front-end to embed the dashboard)

    The API returned HTTP status code, 405 (Method Not Allowed).
    
    Based on stacktrace, HTTPS POST /api/v1/security/guest_token request has been redirected to HTTP GET /api/v1/security/guest_token and thus caused the issue. 

I am able to embed dashboard for my Superset running locally as a Docker container (without gunicon) in my machine.

### Dockerfile

FROM apache/superset:2.0.0

USER superset

Thus, I suspected it could be due to wrong Superset configuration in AWS.

Please help.

Below are some configurations in AWS:

### Dockerfile
FROM apache/superset:2.0.0

USER root

COPY ./docker/apache/superset/pythonpath/superset_config.py /app/pythonpath/superset_config.py

COPY ./entrypoint/entrypoint.sh /app/entrypoint.sh

RUN chmod +x /app/entrypoint.sh

USER superset

EXPOSE 8088

ENTRYPOINT /app/entrypoint.sh

### superset_config.py

ENABLE_PROXY_FIX = True
PROXY_FIX_CONFIG = { 'x_for': 1, 'x_host': 1, 'x_port': 0, 'x_prefix': 1, 'x_proto': 1 }

// Other configurations like FEATURE_FLAGS and SQL_XXX

### entrypoint.sh

// superset commands like superset fab... and superset init

gunicorn --forwarded-allow-ips="*" --workers=2 'superset.app:create_app()' -b 0.0.0.0:8088

**Comment by sovitacharya** [comment]
You are running your superset in port 8088 , which will only support http request calls , but you are calling for https , which inturn will redirect your request to something running in 443 port.
There is two solution for this , 
either you can use any proxy like nginx or envoy to route your request to 8088 from 443 port , or you can change the config of the superset to listen at port 443 . 
The first step is always preferred in a production environment .

**Comment by rusackas** [comment]
Hoping the above helped, but otherwise I'm closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!

**Comment by stockarea** [comment]
Hello, I am facing this same issue, I have nginx as a proxy server, but still getting this exact issue.
