### ISSUE TITLE
"Table object has no attribute 'engine'" error while uploading CSV into new ClickHouse table

### ISSUE THREAD

**Issue by PrinceGallywix** [apache/superset#23098]
It is not possible to upload a csv file to a new table in Clickhouse, but this is fine when the table already exists. 

I assumed that the error was due to internal Clickhouse limitation: you can't create table without specifying an engine.
I was hoping there was a way out by adding a core parameter to Clickhouse database: SET default_table_engine = 'MergeTree';
With this setting it is possible to create a table without specifying an engine.

But the error is the same :(

I understand that Clickhouse support is experimental, uploading a CSV into ClickHouse is not supported, but are there any workarounds how to achive uploading a csv into this database using Superset? Especially when uploading into an existing table is possible.

Let's assume that CSV uploading is only used with ClickHouse database in our organization and it's ok if a possible fix will break the compatibility with other databases :)

#### How to reproduce the bug

1. Add a ClickHouse connection
2. Push "Upload csv" 
3. Specify a ClickHouse connection and non-existent table

### Expected results

CSV file has been uploaded

### Actual results

Unable to upload CSV file (file name) to table (table name) in database (Connect name). Error message: 'Table' object has no attribute 'engine'

#### Screenshots
![image](https://user-images.githubusercontent.com/77333963/219412900-b62d55c5-dcaf-4e7e-adae-2d0a017f2565.png)

### Environment

- python 3.9.2
- superset 2.0.0 (also tried on 2.0.1)
- clickhouse-connect 0.5.10
- sqlalchemy 1.3.16
- ClickHouse 23.2.1.1652

**Comment by genzgd** [comment]
This is non-trivial to implement because of the way that Superset actually uploads CSVs.  There are plenty of ways to do this outside of Superset, but the current Superset implementation requires several SQLAlchemy features that are not implemented for ClickHouse and are not currently on the roadmap.  At some point it would be nice if Superset added an upload API in the EngineSpec that was not SQLAlchemy dependent.
