### ISSUE TITLE
Is ther a way to add some spacing between values and x labels in Bar charts?

### ISSUE THREAD

**Issue by hqgaofeng** [apache/superset#23116]
## Screenshot

![image](https://user-images.githubusercontent.com/5953744/219909444-50a4e754-a1b9-408f-b643-cc810b29db27.png)

## Description
Is ther a way to add some spacing between values and x labels in Bar charts?

## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]
![image](https://user-images.githubusercontent.com/5953744/219909425-f8dfa9c7-de5d-42e6-aaa0-eb0754b1c753.png)

**Comment by sfirke** [comment]
Enable the `GENERIC_CHART_AXES` feature flag, then use the Bar Chart V2 chart.  Then on the Customize tab you should see a field `AXIS_TITLE_MARGIN`, increase that value to separate the labels.
