### ISSUE TITLE
Translation problem with zh

### ISSUE THREAD

**Issue by zRich** [apache/superset#23127]
translation encountered errors when translating .

error: translations/zh/LC_MESSAGES/messages.po:8895: positional format placeholders are unbalanced
error: translations/zh/LC_MESSAGES/messages.po:11413: positional format placeholders are unbalanced
error: translations/zh/LC_MESSAGES/messages.po:12046: placeholders are incompatible
error: translations/zh/LC_MESSAGES/messages.po:12141: placeholders are incompatible
error: translations/zh/LC_MESSAGES/messages.po:12161: placeholders are incompatible
error: translations/zh/LC_MESSAGES/messages.po:13408: placeholders are incompatible
error: translations/zh/LC_MESSAGES/messages.po:13581: unknown named placeholder 'column_name'
error: translations/zh/LC_MESSAGES/messages.po:13586: unknown named placeholder 'location'
error: translations/zh/LC_MESSAGES/messages.po:14167: placeholders are incompatible

#### How to reproduce the bug

pybabel compile -d translations

### Expected results

all msgid and msgstr  in messages.po translated into Chinese without problem. 

### Actual results

pybabel compile -d translations

#### Screenshots

![image](https://user-images.githubusercontent.com/2752413/220198620-8f4eec8a-2c1c-4a40-ba7f-332602109e72.png)

### Environment

(please complete the following information):

- superset version: `superset version`

docker image with latest version
- python version: `python --version`
Python 3.8.16

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Looks like this should have been closed by the linked PR. Closing it now.

**Comment by rusackas** [comment]
Thanks for the contribution :D
