### ISSUE TITLE
 why does only the thumbnail function in the chart work? The dashboard does not appear.

### ISSUE THREAD

**Issue by dragonball-wooboo** [apache/superset#23120]
I installed superset with helpm. Added thumbnail function. By the way, why does only the thumbnail function in the chart work? The dashboard does not appear.

If you look at the superset worker log below, it is as follows.
What's interesting is that the charts come out well.

Why do dashboards have timeouts?
Why doesn’t the chart time out?
│ superset [2023-02-20 04:37:36,200: WARNING/ForkPoolWorker-2] Selenium timed out requesting url http://superset:8088/superset/dashboard/8/

│ superset Traceback (most recent call last):
│ superset   File "/app/superset/utils/webdriver.py", line 177, in get_screenshot
│ superset     element = WebDriverWait(driver, self._screenshot_locate_wait).until(
│ superset   File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 80, in until
│ superset     raise TimeoutException(message, screen, stacktrace)
│ superset selenium.common.exceptions.TimeoutException: Message:

**Comment by dragonball-wooboo** [comment]
slice <- chart 's thumbnail is OK... 

 superset Taking a PNG screenshot of url http://superset:8088/superset/slice/6/?standalone=true as user admin
│ superset [2023-02-20 05:21:52,913: INFO/ForkPoolWorker-1] Taking a PNG screenshot of url http://superset:8088/superset/slice/6/?standalone=true as user admin
│ superset Caching thumbnail: cea906ac23e5a315b0ae43b1fe5ec71c
│ superset [2023-02-20 05:21:53,073: INFO/ForkPoolWorker-1] Caching thumbnail: cea906ac23e5a315b0ae43b1fe5ec71c

**Comment by villebro** [comment]
Hi @dragonball-wooboo , there was a regression on master branch that caused dashboard thumbnails to fail. This was fixed by #23003 which was recently merged. Closing as fixed.
