### ISSUE TITLE
Outdated Doc/Installing Superset from Scratch (installing-superset-from-scratch.mdx)

### ISSUE THREAD

**Issue by Sweepi** [apache/superset#23159]
The installation procedure given in 
https://superset.apache.org/docs/installation/installing-superset-from-scratch

does not work.
Parts or maybe most of the issue might be that I am an idiot, but some things seem to be definitely wrong, e.g. 

> superset db upgrade

does not work because superset no longer has a 'db' command.

Issues observed with Superset v2.0.2 and v1.5.3:
Docker install: Worked for the most part, but loading the the example database seems to be incomplete/incompatible, in the dashboard ~30% of items worked, ~70% did return "SQLite Error" or "Unexpected error"
Ubuntu 22.04 LTS (Python 3.10): lots of incompatible dependencies
Ubuntu 20.04 LTS (Python 3.8): still some incompatible dependencies, ultimately failed at "superset db upgrade"

I cannot contribute much since I am not familiar at all with software and just wanted to check it out.
My suggestion: Someone experienced with the software setups a fresh Ubuntu VM and tries to follow the setup steps in the docs.

In the mean time, if someone is in the same position as me and just wants to give superset a try, here is how I got Superset v1.4.2 to work:

Ubuntu 20.04 LTS (on WSL2)

```
#
# update OS
# 
sudo apt update
sudo apt full-upgrade
#
# install Superset OS Dependencies
# 
sudo apt-get install build-essential libssl-dev libffi-dev python3-dev python3-pip libsasl2-dev libldap2-dev default-libmysqlclient-dev
#
# Use a python virtual environment
#
python3 -m venv CHOOSE_NAME
. CHOOSE_NAME/bin/activate
pip install --upgrade pip
pip install --upgrade wheel
pip install apache-superset==1.4.2
superset --version # this will fail
#
# Downgrade dependencies to working versions
#
pip install pyopenssl==22.1.0
pip install markupsafe==2.0.1
superset --version
#
# continue Superset setup
#
superset db upgrade
export FLASK_APP=superset
superset fab create-admin # will ask you questions (name, login, password) for user creation. mail can be skipped.
superset load_examples
superset init
superset run -p 12144 --with-threads --reload --debugger # port 8088 does not work for me
```

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ -] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by paulvanharen** [comment]
I ran into the same issue. Then I found out, that removing the default database in ~/.superset solves this problem. Hopes this works for you too.

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
