### ISSUE TITLE
Bug with option "reduce x tickets" in time-series bar chart

### ISSUE THREAD

**Issue by bsdpst** [apache/superset#23162]
Hello!
In time-series bar chart it's not possible to change the customizing option "reduce x tickets". Nothing happens when I turn it on/off. For me it's important it turn it off so I can see all axis months. Fix it please. Thank you.

![445](https://user-images.githubusercontent.com/123375799/220745379-07ccd9bf-c284-414f-91f2-2070e09daef7.png)

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.  I suspect this may have changed with all the work that went into the X Axis heading into 3.1 and (soon) 4.0
