### ISSUE TITLE
Bug with data labels format in Mixed chart

### ISSUE THREAD

**Issue by bsdpst** [apache/superset#23161]
Hello!

When I use mixed chart it's not possible to change data labels format. When I change axis format from adaptive to "%" it just changes exactly axis format but not the data labels format. After that axis format looks like [10%], [20%], but the chart data labels still have format like [0.7456848464]. 

I've tried to change it using CSS, but it's possible to change only dashboard properties, but not chart objects properties using CSS.

Fix it please. Thank you.

  
![445](https://user-images.githubusercontent.com/123375799/220743919-c48f6930-19a6-4329-a08f-500255127987.png)

**Comment by shalnice** [comment]
Hello, I encountered the same problem here with mixed chart. I am using Superset version 2.0.0
When I plotted it with other type time-series charts, data label format works fine though.

**Comment by rusackas** [comment]
Hi there... we're open to a PR adding a control for this if there still isn't one. Meanwhile, this isn't a bug, per se, we don't support Superset 2.x any more, and this thread has gone silent for nearly a year, so I'll close this. Thanks!
