### ISSUE TITLE
Issue with GENERIC_CHART_AXES feature

### ISSUE THREAD

**Issue by wigwamitus** [apache/superset#23172]
**superset version 2.0.1
GENERIC_CHART_AXES enabled (yes)
==
Created dataset**

select
      p0.day as day,
      p0.host as host,
      p0.referrer as referrer,
      sum(p0.total) as page_views,
      max(p2.t_page_views) as total_page_views,
      (sum(p0.total)/max(p2.t_page_views)) as percent
 from default.daily_page_views_dist  as p0 
 GLOBAL inner JOIN
            (   
        select
        day as p2day,
        sum(total) as t_page_views
       from default.daily_page_views_dist as p1
where
(
    {%- if ','.join(filter_values('host')) != '' -%}
        host in ({{ "'" + "','".join(filter_values('host')) + "'" }})
    {%- endif -%}
    {%- if ','.join(filter_values('host')) == '' -%}
        true
    {%- endif -%})
and
    referrer not in ('', '-')  
  AND total > 25  
  AND (
                {% if from_dttm is not none %}
                  day >= toDateTime('{{ from_dttm }}', 'America/Chicago') AND
                {% endif %}
                {% if to_dttm is not none %}
                  day <=  toDateTime('{{ to_dttm }}', 'America/Chicago') AND
                {% endif %}
                true
              )  
    group by 
      day
      ) as p2 
      on  day = p2day 
   
where   
(
    {%- if ','.join(filter_values('host')) != '' -%}
        host in ({{ "'" + "','".join(filter_values('host')) + "'" }})
    {%- endif -%}
    {%- if ','.join(filter_values('host')) == '' -%}
        true
    {%- endif -%})

and
referrer not in ('', '-')
and
 total > 25
  AND (
                {% if from_dttm is not none %}
                  day >= toDateTime('{{ from_dttm }}', 'America/Chicago') AND
                {% endif %}
                {% if to_dttm is not none %}
                  day <=  toDateTime('{{ to_dttm }}', 'America/Chicago') AND
                {% endif %}
                true
              )
group by 
  referrer,
  host,
  day
  
order by day, host

==

**Created chart** 

![image](https://user-images.githubusercontent.com/7084524/220942507-dc990278-79c6-4208-a872-b27cf1753870.png)

![image](https://user-images.githubusercontent.com/7084524/220942613-0edfde21-af5f-4963-9ea4-9c47b035fb02.png)

**Chart works in chart builder as we can see via the above screen shots ^^** 

**Next, add chart to dashboard**
![image](https://user-images.githubusercontent.com/7084524/220943017-6ad5d2c5-2d79-4efc-a3a7-2085736541b7.png)

**See "select as day" code generated by dashboard as wrapper around the view query for the chart

See error msg caused by this generated code**

![image](https://user-images.githubusercontent.com/7084524/220943455-e0ae1225-e445-4446-8fd8-f9eda6a6c985.png)

==

**posted in superset slack, received input from members**

![image](https://user-images.githubusercontent.com/7084524/220944023-d201fb86-160a-4c19-bfbc-d8f4b5e82644.png)

![image](https://user-images.githubusercontent.com/7084524/220944333-27e95f5c-cdbc-4ec4-a921-529dec41a6da.png)

**posted this ticket**

Happy to help anyway we can !!!    Please let me know how I can help get this resolved sooner !    We have report requests from both internal and external users requiring this feature !!

Joe Wilkerson
Data Engineer
True Anthem

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.... or we can re-open this if it's still a problem. The feature flag is enabled by default now, ad will be gone in 4.0, so I hope it's all good now :)
