### ISSUE TITLE
tuple() gets appended to the query for all charts in where condition and throws error in embedded iframe but works in superset chart

### ISSUE THREAD

**Issue by believe-Mahesh** [apache/superset#23182]
Hello all,
I am Mahesh and I am new to apache superset. Firstly, Congratulations and kudos to this entire open source community for building this awesome product.

#### Issue: 
I created a sample dashboard in superset and tried embedding it in my angular app using superset-embedded sdk. I was able to embed the dashboard. But the charts are not getting rendered in the iframe. But its getting displayed in the Superset ui.

I am using Clickhouse DB.

The error I get in the  iframe ui is
Error: :HTTPDriver for <<clickhouse host name>> returned response code 500)
 Code: 42. DB::Exception: Function tuple requires at least one argument.: While processing SELECT Id AS Id, DueDate AS DueDate, BillEmail AS BillEmail, TotalAmt AS TotalAmt FROM default.invoices WHERE tuple() AND (1 = 1) LIMIT 1000
 
 
 But the above chart is rendered in the superset ui without issues.

#### How to reproduce the bug

1. Connect Clickhouse DB
2. Create Dataset
3. Create a table chart from dataset
4. add it to dashboard
5. Embed the dashboard in the ui

#### Screenshots

![image](https://user-images.githubusercontent.com/47143320/221118892-2b995afb-5854-4daf-8ec8-b4353ee24c3e.png)

#### Logs

I was able to capture the logs when the charts are loaded in the iframe.

superset_app          | 2023-02-24 07:00:09,654:WARNING:superset.connectors.sqla.models:Query SELECT COUNT(*) AS `count`
superset_app          | FROM `default`.`customers`
superset_app          | WHERE ()
superset_app          | LIMIT 50000 on schema default failed
superset_app          | Traceback (most recent call last):
superset_app          |   File "/app/superset/connectors/sqla/models.py", line 1894, in query
superset_app          |     df = self.database.get_df(sql, self.schema, mutator=assign_column_label)
superset_app          |   File "/app/superset/models/core.py", line 547, in get_df
superset_app          |     self.db_engine_spec.execute(cursor, sqls[-1])
superset_app          |   File "/app/superset/db_engine_specs/base.py", line 1367, in execute
superset_app          |     raise cls.get_dbapi_mapped_exception(ex) from ex
superset_app          |   File "/app/superset/db_engine_specs/base.py", line 1365, in execute
superset_app          |     cursor.execute(query)
superset_app          |   File "/usr/local/lib/python3.8/site-packages/clickhouse_connect/dbapi/cursor.py", line 50, in execute
superset_app          |     query_result = self.client.query(operation, parameters)
superset_app          |   File "/usr/local/lib/python3.8/site-packages/clickhouse_connect/driver/client.py", line 144, in query
superset_app          |     return self._query_with_context(query_context)
superset_app          |   File "/usr/local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 186, in _query_with_context
superset_app          |     response = self._raw_request(self._prep_query(context),
superset_app          |   File "/usr/local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 354, in _raw_request
superset_app          |     self._error_handler(response)
superset_app          |   File "/usr/local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 298, in _error_handler
superset_app          |     raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
superset_app          | clickhouse_connect.driver.exceptions.DatabaseError: :HTTPDriver for <<clickhouse host>> returned response code 500)
superset_app          |  Code: 42. DB::Exception: Function tuple requires at least one argument.: While processing SELECT count() AS count FROM default.customers WHERE tuple() LIMIT 50000. (NUMBER_OF_ARGUMENTS_DOESNT_MATCH) (version 22.13.1.24460 (official build))

### Environment

- browser type and version: Google Chrome 110.0.5481.96 (Official Build) (64-bit)
- superset version: latest master
- node.js version: 14.17.6
- any feature flags active: Embedded_superset=True

Please provide any suggestions. 
Note : I am a java developer and have very little knowledge on python.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
