### ISSUE TITLE
Chart with a filter on an aggregated calculated column creates incorrect SQL

### ISSUE THREAD

**Issue by Pastryboy** [apache/superset#23193]
#### How to reproduce the bug
I created a calculated column, Commission, on a chart dataset, used by Time-series by Area chart. Commission = base dataset field NetCommission
I then put a filter on the chart query for the sum of the calculated column, Commission, to be >0

### Actual results

the following message "Error: Flight returned invalid argument error, with message: Column 'CommissionGBP' not found in any table"

In other words the calculated column on the dataset is being sent to the database, where it doesnt exist. Specifically it is happening on the HAVING clause as a result of the filter. The relevant parts of the SQL sent to the database are below;

SQL Query SELECT  ..
       sum(NetCommissionGBP) AS "SUM(CommissionGBP)"
FROM …
GROUP BY  …
**HAVING ((SUm(CommissionGBP)**>0))
ORDER BY "SUM(CommissionGBP)" DESC

Clearly what should have been generated by the filter is the datasource column, not the calculated dataset column, ie it should be HAVING ((Sum(**Net**CommissionGBP)>0))

 

### Environment

- browser type and version: Chrome Version 110.0.5481.104 (Official Build) (64-bit)
- superset version: 2.0

**Comment by rusackas** [comment]
This version of Superset is no longer supported. If anyone is still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
