### ISSUE TITLE
Timestamp appears at end of x-axis for ECharts with long filtered interval

### ISSUE THREAD

**Issue by sfirke** [apache/superset#23197]
This is a regression from 2.0.1, revealed when testing 2.1.0rc1 and also present on master branch as of 2023-03-22.

#### How to reproduce the bug

Create a time series Bar Chart v2, add to dashboard, set a filter to include time range from >1 year ago to now.

### Expected results

Here's how this chart looks in 2.0.1 dashboard in production:
![image](https://user-images.githubusercontent.com/7569808/221279888-ea7d416e-0b19-4e94-bf37-2ebc176786a8.png)

### Actual results
Here is this chart in 2.1.0rc1 - note the timestamp value at the end of the x-axis, bottom-right of screenshot:
![image](https://user-images.githubusercontent.com/7569808/221280028-239073f2-6ec3-497f-95db-a6bce3803774.png)

If I change the time grain to Week, the timestamp value changes:
![image](https://user-images.githubusercontent.com/7569808/221280114-ca3e224d-8345-496f-ad84-6d1d1723147b.png)

If I put in 2022-12-01 as the start date, the timestamp goes away:
![image](https://user-images.githubusercontent.com/7569808/221280444-39895338-811d-48b3-9b33-d818c84cc8e2.png)

But it is present with 2022-11-01 as the start date.

### Environment

(please complete the following information):

- browser type and version: Firefox
- superset version: 2.1.0rc1 and latest as of March 22 2023
- any feature flags active: GENERIC_CHART_AXES

The only maybe-relevant thing I see in the logs is `DEBUG:parsedatetime:eval now with context - False, False`

*Edit*: I also see it on the 2nd chart in this issue https://github.com/apache/superset/issues/23453#issue-1635335324.

**Comment by sfirke** [comment]
This persists in 2.1.0rc2.  I see it also affects line charts:
![image](https://user-images.githubusercontent.com/7569808/225109618-22711da2-e918-49d8-9b1c-9e5415582ee4.png)

**Comment by D3nn3** [comment]
Can confirm with the final v2.1.0 release, even without the `GENERIC_CHART_AXES` feature flag enabled.

**Comment by yousoph** [comment]
Some related discussion here: https://github.com/apache/superset/pull/20627#issuecomment-1436684100 

The original fix was to address an issue where the last month wasn't displaying on the x-axis: 
![image](https://github.com/apache/superset/assets/10627051/547809ef-1fb8-4b77-a33b-5a625669ad3e)

**Comment by eschutho** [comment]
@sfirke what do you think about us reverting https://github.com/apache/superset/pull/20627#issuecomment-1436684100 for 2.1.1 while we wait for a fix?

**Comment by sfirke** [comment]
@eschutho yes my two cents is that the prior behavior of omitting the latest month's label is better than the current behavior.  A revert for 2.1.1 sounds like an improvement to me.

Would it also make sense to include the revert in 3.0.0rc2?

**Comment by mpostelnicu** [comment]
i too think it should be reverted for 2.1.1 until a better solution is found. This makes all yearly charts present with an artifact at the end of the axis.

**Comment by sfirke** [comment]
Can confirm that the reversion fixed this in 2.1.1rc3.
