### ISSUE TITLE
"SHOW LABEL" checkbox for an annotation does nothing

### ISSUE THREAD

**Issue by sfirke** [apache/superset#23218]
In both 2.0.1 and 2.1.0rc1, nothing happens when I check the "SHOW LABEL" box.  Whether or not it's checked, the label appears on the chart legend and does not show on the chart.  I'm not sure what it's supposed to do, but it should do something.

This is the box:
![image](https://user-images.githubusercontent.com/7569808/221648639-e09e2c12-80ee-4397-9f6b-0f09a6d54b2e.png)

**Comment by D3nn3** [comment]
Can confirm, also just experienced this bug. I didn't test this, but the `GENERIC_CHART_AXES` feature flag could have something to do with this. Afaik before enabling the feature flag we didn't have this problem on our production environment.

@sfirke : Do you guys have the feature flag enabled too or do you have this problem without having it enabled?

**Comment by sfirke** [comment]
Yes I have that feature flag enabled.

**Comment by rusackas** [comment]
This version of Superset is no longer supported. If anyone is still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.

**Comment by sfirke** [comment]
This is still the case in 3.0.1.  I'm planning to upgrade to 3.1.x shortly and can verify it's the case there, then re-open.

**Comment by D3nn3** [comment]
Is this maybe related to the following issue? https://github.com/apache/superset/issues/26206
