### ISSUE TITLE
Time Series Bar Chart v2 parity issues

### ISSUE THREAD

**Issue by etr2460** [apache/superset#23219]
There are several parity issues between the echarts bar chart and nvd3 version

- The total values at the top of the bar chart do not update when some series are filtered out (ie. reflect the wrong total)
- Double clicking on the legend values doesn’t select only that value as it does for the non-V2 bar chart
- The series are no longer ordered from largest to smallest, which degrades the interpretability imo (see screenshot below)

#### Screenshots
![image (37)](https://user-images.githubusercontent.com/7409244/221656469-7e6a37f8-5331-47bf-9ac2-c339dc0a3b59.png)
<img width="677" alt="image (36)" src="https://user-images.githubusercontent.com/7409244/221656472-e85ee766-ad66-46bc-93bb-bab755aa3f27.png">

### Environment
Close to master

**Comment by etr2460** [comment]
Note that this first issue: "The total values at the top of the bar chart do not update when some series are filtered out (ie. reflect the wrong total)" is actually a misrepresentation error and is a bug that should probably be addressed sooner rather than later

**Comment by rusackas** [comment]
Closing this since the official migration has already been made. Any shortcomings should be opened as new, individual, issues. Thanks!
