### ISSUE TITLE
Formula Annotation is not showing under Annotation Layer

### ISSUE THREAD

**Issue by srinichalla9** [apache/superset#23214]
#### How to reproduce the bug

1. Go to  Line or Area chart
2. Click on Add Annotation Layer
3. Under Add Annotation tab, I could see only Interval and Event, not Formula Annotation.
![image](https://user-images.githubusercontent.com/117988954/221555531-11747c86-b21f-4995-99d0-16425992d0a1.png)

### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by srinichalla9** [comment]
My current version is 1.4.0

**Comment by srinichalla9** [comment]
Thanks for the update! @sfirke . We will migrate to the latest version.

**Comment by rusackas** [comment]
Closing since this is resolved in the current version(s).
