### ISSUE TITLE
Bug report - Time series bar 

### ISSUE THREAD

**Issue by agus921** [apache/superset#23221]
Hello, i need help with the following error. I have made a query that show data from the last two years, including the current but when the chart is created, the chart shows 2024 and i don't know why. I checked with ppl in slack and they told me that maybe could be a bug. I have included an image with the result of the sample and also an image with the visualization.

QUERY:

`select 
ifnull(max(ueyepc.porcen_avance_eepp_c/100),0) as "Avance mensual de EEPP",
	str_to_date(CONCAT(ueyepc.anio_periodo_carga_c, '-01-01'), '%Y-%m-%d') as "Año"
FROM
	(
					`upebm_equipamiento_y_espacio_publico_cstm` `ueyepc`
					JOIN `upebm_equipamiento_y_espacio_publico` `ueyep` ON ( `ueyepc`.`id_c` = `ueyep`.`id` )) 
WHERE
	`ueyep`.`deleted` = 0 
	AND year(str_to_date(CONCAT(ueyepc.anio_periodo_carga_c, '-01-01'), '%Y-%m-%d')) BETWEEN year(DATE_SUB(current_date, INTERVAL 2 YEAR)) and year(CURRENT_DATE)
GROUP BY `Año`

RESULT SAMPLE:
`
![image](https://user-images.githubusercontent.com/46030633/221670819-46032e3c-e764-4b9e-a0dc-5d3f917b2c3f.png)

CHART VIZUALIZATION:

![image](https://user-images.githubusercontent.com/46030633/221670333-59dd388c-1d59-4039-98bc-1500cecba0f6.png)

Thanks in advance for your help.
Agustin.

**Comment by agus921** [comment]
Hi all, anyone could understand the problem?
Thanks!

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
