### ISSUE TITLE
"Enable cross-filtering" checkbox icon + command offered to unauthorized users

### ISSUE THREAD

**Issue by sfirke** [apache/superset#23220]
In Superset 2.1.0rc1.  On a public-facing dashboard, the public user can see this:
![image](https://user-images.githubusercontent.com/7569808/221663558-f37bb92f-9ea6-4ce2-8d7a-443ecfcc91ca.png)

When they uncheck the box, they see the flash of a modal popup message: "Sorry there was an error saving this dashboard: UNAUTHORIZED" before being bounced to the login screen.

### Expected results

The user should not be offered this gear icon and the associated checkbox if they don't have privileges to manipulate it.

### Actual results

It's visible to the user.

**Comment by kgabryje** [comment]
Fixed
