### ISSUE TITLE
superset 2.1.0rc1 Setup fail 

### ISSUE THREAD

**Issue by santoshmallah** [apache/superset#23267]
I want to run superset 2.1.0rc1 in my windows machine 

I have follow steps from this link [https://preset.io/blog/tutorial-contributing-code-to-apache-superset/](url)

when i run ```npm run dev-server```  its runs successfully but it has some error 

![image](https://user-images.githubusercontent.com/51262721/222555819-d4a8ee1d-0d8a-4add-9b75-c51bd4b44607.png)

And when i try to access superset home page it give me error msg 

![image](https://user-images.githubusercontent.com/51262721/222555993-a6705d0e-3590-4a03-b5cb-529826ca5e86.png)

and After that I have also referred some steps given below

#!/bin/bash

# Extract new installation
Downloads/apache-superset-2.1.0rc1-source.tar.gz 
extract it in  superset2.1 folder
cd superset2.1

# Create enviornment and install
python3.10 -m venv venv
. ./venv/bin/activate
pip install --upgrade pip 
pip install .

# Set up
superset db upgrade
export FLASK_APP=superset
superset fab create-admin
superset init

But still i am getting same error msg 

# Can anyone suggest to me steps to build superset-frontend and superset-ui and run superset  or steps to run superset2.1.0rc1 completely without missing asset files from static folder in the superset 

### Environment

- browser type and version:
- superset version: `2.1.0rc1`
- python version: `3.8`
- node.js version: `16.14.2`

Thanks in advance

**Comment by eschutho** [comment]
Hi @santoshmallah are you also running `npm ci` to package the dependencies before running `npm run dev-server`?

**Comment by santoshmallah** [comment]
Yes, I have run 
```
cd superset-frontend
npm ci
```
and then I run npm run ```npm run dev-server```

**Comment by rusackas** [comment]
Since we're now on 3.1, on the verge of 4.0, we're not supporting 2.x  or prior versions actively. If anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps. We also don't officially support Windows, but welcome any PRs to improve that experience for those who try it. Thank you for understanding :)
