### ISSUE TITLE
npm i build failed

### ISSUE THREAD

**Issue by santoshmallah** [apache/superset#23275]
When i running ```npm i```  in this ```superset-frontend\packages\generator-superset``` location I am getting this error msg

D:\superset\superset-frontend\packages\generator-superset>npm i
npm ERR! Workspaces not supported for global packages

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Santosh Mallah\AppData\Local\npm-cache\_logs\2023-03-03T14_07_51_036Z-debug-0.log

added 526 packages, and audited 528 packages in 46s

46 packages are looking for funding
  run `npm fund` for details

1 high severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

![image](https://user-images.githubusercontent.com/51262721/222809516-bae9bd1e-39b9-4cb2-9622-712a3d11bbf4.png)

- browser type and version:
- superset version: `2.1.0rc1`
- python version: `3.8.0`
- node.js version: `16.4.0`
- any feature flags active:

Is anything I am missing or why I am getting this error msg

**Comment by rusackas** [comment]
I suspect this is a Windows issue... we don't officially support WIndows, but maybe someone here knows how to work around this.

**Comment by Ha0ran2001** [comment]
npm ci, not npm i
# Build javascript assets
cd superset-frontend
npm ci
npm run build
cd ..

**Comment by Donny2333** [comment]
@Ha0ran2001 请教下，你是用哪个版本执行npm run build成功的呀，我这边尝试多个版本都打包失败了

**Comment by rusackas** [comment]
Closing this since it's gone silent for nearly a year, and we don't officially support Windows.
