### ISSUE TITLE
I can create/update/delete an annotation layer without permission

### ISSUE THREAD

**Issue by xavier-GitHub76** [apache/superset#23285]
Superset v.1.5.2

A user without permission (read/write on annatation) can create/update/delete an annotation layer

1. User has only the permission 'menu access on Annotation Layers'
![image](https://user-images.githubusercontent.com/82046143/223182238-853dc37d-19cc-4dc4-8e1e-f1771123dda8.png)

2. He access to 'Annotation Layers'
![image](https://user-images.githubusercontent.com/82046143/223182451-667e9ca7-fb5e-4d7f-8d6b-c0c592109445.png)

3. He can create an annotation without write permission 
![image](https://user-images.githubusercontent.com/82046143/223182843-28595bd1-cb17-42bf-85a0-2b15d2c7a9fa.png)
![image](https://user-images.githubusercontent.com/82046143/223183318-cd99958b-1479-4b1a-a206-fa4564a1b42b.png)

4. An Error message is present but the annotation layer is created
![image](https://user-images.githubusercontent.com/82046143/223183409-adba95c8-3e22-4b8a-b4bf-50365e63ddf8.png)
![image](https://user-images.githubusercontent.com/82046143/223183507-750fe392-5d77-4c99-a35f-c5d0b3a650d3.png)

Creation functionnality should be enabled only with 'can write on Annotation' permission.
Annotation Layers should be displayed only with 'can read on Annotation' permission.

Best regards

**Comment by rusackas** [comment]
This version of Superset is no longer supported. If anyone is still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
