### ISSUE TITLE
`superset` Flask CLI fails to launch in Debug mode: Refusing to start due to insecure SECRET_KEY

### ISSUE THREAD

**Issue by cwegener** [apache/superset#23288]
After #23186 , the `superset` Flask cli no longer starts unless a non-default SECRET_KEY is configured.

#### How to reproduce the bug

1. Checkout PR #23186 
2. Enable Flask Debug: `export FLASK_DEBUG=True`
3. Run `superset --help`
4. See error: `Refusing to start due to insecure SECRET_KEY`

### Expected results

`superset` CLI prints out the help page

### Actual results

error: `Refusing to start due to insecure SECRET_KEY`

### Environment

(please complete the following information):

- browser type and version: NA
- superset version: PR #23186 
- python version: `3.10`
- node.js version: NA
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by cwegener** [comment]
**UPDATE** As a workaround when only using built-in Flask commands, substituting `superset` for `flask` will fix the problem.

**Comment by ngogia20** [comment]
Refusing to start due to insecure SECRET_KEY

Same issue when I run docker-compose -f docker-compose-non-dev.yml up

**Comment by cwegener** [comment]
Another more reliable workaround is to add `TESTING = 1` into your custom superset config file, which is probably more suitable for docker container folks.

**Comment by rusackas** [comment]
Can you not just set the secret key to something more custom, as it's warning you to do?

**Comment by cwegener** [comment]
> Assuming you have set your own `SECRET_KEY` for your environment, if the cli still fails this probably mean the cli is not picking up your config override with your `SECRET_KEY`
> 
> example:
> 
> ```shell
> export SUPERSET_CONFIG=superset_config; superset 
> ```

Nope. I am not setting my own `SECRET_KEY`. Sorry if that wasn't clear from the original description.

The problem is that PR #23186 does not seem to work as advertised when running in Flask Debug mode.

**Comment by rusackas** [comment]
Seems like this is all good now and should've been closed. Let me know if I'm mistaken, and we can re-open with updated context.
