### ISSUE TITLE
ClickHouse DB engine spec fails: Unrecognized common setting product_name

### ISSUE THREAD

**Issue by cwegener** [apache/superset#23291]
Superset fails to start when installing with the `clickhouse` extra requirement.

#### How to reproduce the bug

1. Install apache-superset using the clickhouse extra (`pip install 'apache-superset[clickhouse]'`)
2. Run Superset: `superset run`
3. Attempt to access the Superset UI: `curl http://localhost:5000/login/`
4. See error:  `{"errors": [{"message": "Unrecognized common setting product_name", "error_type": "GENERIC_BACKEND_ERROR", "level": "error", "extra": {"issue_codes": [{"code": 1011, "message": "Issue 1011 - Superset encountered an unexpected error."}]}}]}`

### Expected results

Superset server functions correctly and users are able to log in successfully.

### Actual results

Superset server fails to login users

```
2023-03-07 13:10:16,143:ERROR:superset.views.base:Unrecognized common setting product_name
```

```
{"errors": [{"message": "Unrecognized common setting product_name", "error_type": "GENERIC_BACKEND_ERROR", "level": "error", "extra": {"issue_codes": [{"code": 1011, "message": "Issue 1011 - Superset encountered an unexpected error."}]}}]}
```

### Environment

(please complete the following information):

- browser type and version: `curl`
- superset version: PR #23185 
- python version: `3.10`
- node.js version: NA
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

PR #23185 Introduces support for ClickHouse Connect but the version constraints for the `clickhouse-connect` package do not align with the API features used  in PR #23185

The PR requires at least ClickHouse Connect version `0.5.4` which is the first version that introduces the `product_name` common setting. https://github.com/ClickHouse/clickhouse-connect/commit/d6bfb61a13bae9742d1f14804391e3e650cad661

**Comment by villebro** [comment]
@cwegener would you consider fixing this by opening a PR that bumps the required version of `clickhouse-connect`? FYI @genzgd

**Comment by cwegener** [comment]
Sorry. Forgot to open the PR. But yes, what @genzgd did in #23296 is exactly what is need for installations that use the `clickhouse` extras requirement in a pip installation. (tbh. most installations probably install `clickhouse-connect` directly without using the extras requirement ...)

**Comment by eschutho** [comment]
I merged https://github.com/apache/superset/pull/23296, and will close this PR with the hopes that it's fixed now.
