### ISSUE TITLE
Illegible display when editing role permissions in 2.1.0rc1 with Firefox

### ISSUE THREAD

**Issue by sfirke** [apache/superset#23312]
This is a regression from 2.0.1, specific to Firefox.  Possibly specific to Windows as @rusackas and @eschutho couldn't reproduce on Mac.

**Firefox with Superset 2.1.0rc1**
Not usable.  The users and permissions get printed on top of each other and the permissions display as bullet points:
![image](https://user-images.githubusercontent.com/7569808/223787012-ebd0614d-1732-47de-874d-f08b2ae4a9b9.png)

It looks fine in **Chrome with Superset 2.1.0rc1** and Microsoft Edge:
![image](https://user-images.githubusercontent.com/7569808/223787339-92b3e1d1-c415-42c0-b115-214c7723ef23.png)

And looks good in **Firefox with Superset 2.0.1:**
![image](https://user-images.githubusercontent.com/7569808/223787483-6936965f-4bf9-4098-be13-50c308c2f4ab.png)

**Comment by rusackas** [comment]
Did some troubleshooting with @sfirke and it seems this one is a peculiarity of the deployment he was looking at. We both managed to test things successfully on other installations. Somehow it seems that the styles from `/static/appbuilder/select2/select2.css` are being served and are directly accessible by the browser when you visit that URL, but they are NOT being applied to the page for some reason. I'm not sure why ¯\\\_(ツ)_/¯
