### ISSUE TITLE
Edit native filter make crash

### ISSUE THREAD

**Issue by HeathLee** [apache/superset#23311]
I have a dashboard with 17 native filters. When I click on the Edit Filter button, the page becomes very slow, and sometimes I can't even move the mouse. If the edit box appears, performing some actions on it or even if the box doesn't appear at all, the page may crash.

#### Screenshots
before edit filters
![image](https://user-images.githubusercontent.com/7382922/223710220-19587919-bf1b-4ee4-b947-ca63f1979e83.png)
open edit
![image](https://user-images.githubusercontent.com/7382922/223710564-b3fc55cf-df3f-4e17-bf14-b203a0c92543.png)
if edit some filter,page crash
![image](https://user-images.githubusercontent.com/7382922/223712036-cd1f8b04-94d6-414c-901b-291c20e5ea14.png)

![image](https://user-images.githubusercontent.com/7382922/223711834-3f58dee5-6085-4219-b82a-43934e1552a6.png)

### Environment

(please complete the following information):

- browser type and version: chrome 110.0.5481.177
- superset version: 2.0.1
- python version: 3.8

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
