### ISSUE TITLE
Bulk select for filters

### ISSUE THREAD

**Issue by ASchmidtGit** [apache/superset#23315]
Heyho, is it possible to bulk select / select all values in a filter?
E.g. in my filter for article numbers i type "art-25116", so the filter shows all article numbers starting with "art-50876".
From this point i want to either select all or multiple values but as soon as i click on one the filter resets.

Edit: I selected "_Can select multiple values_" but this only allows multiple values to be selected but not selected at once

Current behavior:
![NoBulkSelect](https://user-images.githubusercontent.com/83596606/224013828-d555ab9c-a7b7-4480-ab49-e2690b56dcb2.gif)

Behavior i want (gif made from sellerboard):
![BulkSelect](https://user-images.githubusercontent.com/83596606/224013849-f5518130-a6aa-4c83-9a89-b20336f36a38.gif)

**Comment by mrmooon** [comment]
Hey! Have you checked the _Can select multiple values_ in the filter configuration? That should allow both defining multiple filters and selecting all values at once.
<img width="334" alt="Screenshot 2023-03-09 at 20 05 23" src="https://user-images.githubusercontent.com/24896223/224129653-d58f2e8c-6990-493e-985e-fbe19c08bbab.png">

**Comment by Govindarajan-D** [comment]
Hi. I am able to do multiselect in the same dropdown instance. I took the most recent build from the website. 
![MultipleSelectSuperset](https://user-images.githubusercontent.com/10530605/225514443-44374123-f8de-41c5-943e-50a521dd22de.gif)

**Comment by ASchmidtGit** [comment]
Because you dont search for a value in the filter first.
If i just open the filter dropdown and click on the first items shown i can select multiple items too without the list being resetted.

**Comment by Govindarajan-D** [comment]
Ok got it. Let me check what I can do for that!

**Comment by Govindarajan-D** [comment]
Hi. I made the change on my local and it works good. When we search and select, the search term doesn't get cleared. But one thing though, after I make selections, if I click on the input box, the search term vanishes and if I select outside, the search term gets added as a new filter. 

You can watch the entire gif to see what I am speaking about. Would this be correct behaviour?

![MultipleSelectSuperset](https://user-images.githubusercontent.com/10530605/226130296-04915358-451c-4b86-a74c-d872f4e8e829.gif)

**Comment by ASchmidtGit** [comment]
@Govindarajan-D Yes, that looks exactly like the behavior im looking for

**Comment by Govindarajan-D** [comment]
Let me do more testing to see if everything is ok and create pull request for it

**Comment by Govindarajan-D** [comment]
@michael-s-molina With respect to this issue, I tried using autoClearSearchValue = false in SelectFilterPlugin.tsx. Previously it worked and I was able to test it and it was fine. But after some new commits, I am not able to make it work again using this. Can you help me on this? Thanks!

**Comment by michael-s-molina** [comment]
> @michael-s-molina With respect to this issue, I tried using autoClearSearchValue = false in SelectFilterPlugin.tsx. Previously it worked and I was able to test it and it was fine. But after some new commits, I am not able to make it work again using this. Can you help me on this? Thanks!

Sure. Do you have a PR with your changes?

**Comment by Govindarajan-D** [comment]
No. Actually, I was making changes in my local, but since it didn't work I didn't push it yet. Shall I push the changes?

**Comment by michael-s-molina** [comment]
> @michael-s-molina With respect to this issue, I tried using autoClearSearchValue = false in SelectFilterPlugin.tsx. Previously it worked and I was able to test it and it was fine. But after some new commits, I am not able to make it work again using this. Can you help me on this? Thanks!

@Govindarajan-D `autoClearSearchValue` should be applied to the `Select` component instead of `SelectFilterPlugin`. Here's a [PR](https://github.com/apache/superset/pull/23869) to implement the requested feature.

**Comment by Govindarajan-D** [comment]
Thanks @michael-s-molina for working on this! I was stuck for few days on this!
