### ISSUE TITLE
Failed taking a screenshot Working outside of request context

### ISSUE THREAD

**Issue by yatendra99** [apache/superset#23332]
Hi Team,

I am trying to setup the reporting in Superset. I am trying to use the firefox Driver: Below are the configuration i am using: 

`WEBDRIVER_OPTION_ARGS = ["--headless"]
WEBDRIVER_WINDOW = {
    "dashboard": (1600, 2000),
    "slice": (3000, 1200),
    "pixel_density": 1,
}
EMAIL_PAGE_RENDER_WAIT = 300
SCREENSHOT_LOCATE_WAIT = 1000
SCREENSHOT_LOAD_WAIT = 6000
SCREENSHOT_SELENIUM_RETRIES = 5
SCREENSHOT_SELENIUM_HEADSTART = 3
SCREENSHOT_SELENIUM_ANIMATION_WAIT = 5
SCREENSHOT_REPLACE_UNEXPECTED_ERRORS = False
SCREENSHOT_WAIT_FOR_ERROR_MODAL_VISIBLE = 5
SCREENSHOT_WAIT_FOR_ERROR_MODAL_INVISIBLE = 5
EMAIL_REPORTS_SUBJECT_PREFIX = "[Fleet Scanner] "
ALERT_REPORTS_NOTIFICATION_DRY_RUN = False
ENABLE_ALERTS = True
ENABLE_SCHEDULED_EMAIL_REPORTS = True
EMAIL_NOTIFICATIONS = True
EMAIL_REPORTS_USER="admin"
SUPERSET_WEBSERVER_ADDRESS = "localhost"
EMAIL_REPORTS_WEBDRIVER = "firefox"
WEBDRIVER_TYPE= "firefox"

WEBDRIVER_OPTION_ARGS = [
    "--force-device-scale-factor=2.0",
    "--high-dpi-support=2.0",
    "--headless",
    "--disable-gpu",
    "--disable-dev-shm-usage",
    "--no-sandbox",
    "--disable-setuid-sandbox",
    "--disable-extensions",
]

WEBDRIVER_BASEURL = "http://superset:8088/"
WEBDRIVER_BASEURL_USER_FRIENDLY = WEBDRIVER_BASEURL

SQLLAB_CTAS_NO_LIMIT = True

FEATURE_FLAGS = {
    "ALERT_REPORTS": True,
    "EMBEDDED_SUPERSET": True,
    "GENERIC_CHART_AXES": True,
    "ALERTS_ATTACH_REPORTS": True,
    "THUMBNAILS": True,
}
'

Below are the errors I am seeing in Worker nodes: 

`This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
Traceback (most recent call last):
  File "/app/superset/reports/commands/execute.py", line 221, in _get_screenshots
    image = screenshot.get_screenshot(user=user)
  File "/app/superset/utils/screenshots.py", line 82, in get_screenshot
    self.screenshot = driver.get_screenshot(self.url, self.element, user)
  File "/app/superset/utils/webdriver.py", line 170, in get_screenshot
    driver = self.auth(user)
  File "/app/superset/utils/webdriver.py", line 149, in auth
    return machine_auth_provider_factory.instance.authenticate_webdriver(
  File "/app/superset/utils/machine_auth.py", line 63, in authenticate_webdriver
    elif request.cookies:
  File "/usr/local/lib/python3.8/site-packages/werkzeug/local.py", line 316, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.8/site-packages/werkzeug/local.py", line 520, in _get_current_object
    return get_name(local())  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/flask/globals.py", line 33, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/superset/tasks/scheduler.py", line 87, in execute
    AsyncExecuteReportScheduleCommand(
  File "/app/superset/reports/commands/execute.py", line 719, in run
    raise ex
  File "/app/superset/reports/commands/execute.py", line 715, in run
    ReportScheduleStateMachine(
  File "/app/superset/reports/commands/execute.py", line 673, in run
    state_cls(
  File "/app/superset/reports/commands/execute.py", line 574, in next
    raise first_ex
  File "/app/superset/reports/commands/execute.py", line 543, in next
    self.send()
  File "/app/superset/reports/commands/execute.py", line 440, in send
    notification_content = self._get_notification_content()
  File "/app/superset/reports/commands/execute.py", line 347, in _get_notification_content
    screenshot_data = self._get_screenshots()
  File "/app/superset/reports/commands/execute.py", line 226, in _get_screenshots
    raise ReportScheduleScreenshotFailedError(
superset.reports.commands.exceptions.ReportScheduleScreenshotFailedError: Failed taking a screenshot Working outside of request context.

**Comment by sfirke** [comment]
What version of Superset are you using?

**Comment by yatendra99** [comment]
I am using the latest version of Superset

**Comment by rusackas** [comment]
> I am using the latest version of Superset

Do you mean `master`, 2.0.1, or 2.1.0 RC2?

**Comment by rusackas** [comment]
Do you have the `GLOBAL_ASYNC_QUERIES` feature flag enabled?

**Comment by rusackas** [comment]
I don't think this will help, but have you tried the chrome driver?

**Comment by yatendra99** [comment]
@rusackas Yes I am using the master one .. 

No I didnt use GLOBAL_ASYNC_QUERIES config.. Let me check .. I have also tried the chrome driver, but the chrome driver was keep on crashing ..

**Comment by amason09** [comment]
I was having the same issues earlier, few things that I did to fix it. I followed the setup alert documents on the [official docs website](https://superset.apache.org/docs/installation/alerts-reports/) and switched from firefox to chrome. With that switch to chrome set the CHROMEDRIVER_VERSION to LATEST_RELEASE_111 in our custom dockerfile. Additionally our deploy login uses a custom SSO setup that prevents the default Selenium login so setting THUMBNAIL_SELENIUM_USER = {user} that has proper dashboard permissions fixed it. This was on version 2.1.0rc3.

**Comment by rusackas** [comment]
@yatendra99 let us know if @amason09 's comments (thank you!) help address this issue so we can close it.

**Comment by yatendra99** [comment]
@rusackas @amason09 seems i am not getting this error now .. hence closing the issue

**Comment by Medaziz-Effios-expertise** [comment]
hi , currently im facing the same issue , using superset/2.1.0 , ChromeDriver 114.0.5735.90 , Google Chrome 115.0.5790.170  , same with the firefox version aswell ,Mozilla Firefox 113.0.2, geckodriver 0.29.0. But I think since I'm using keycloak SSO , that's what causing the auth issue for the worker, or at least i guess , so any tips how to overcome this issue , thanks in advance .

**Comment by rahulpuri14493** [comment]
@Medaziz-Effios-expertise, I'm using keycloak SSO, that's causing auth issue for the worker. Did you found any answer for this ?

**Comment by rahulpuri14493** [comment]
@yatendra99 how did you resolve this issue
