### ISSUE TITLE
how to integrate in apache echart ? (https://echarts.apache.org/en/index.html)

### ISSUE THREAD

**Issue by dragonball-wooboo** [apache/superset#23337]
How to integrate in apache echart ? 

Can you guys also provide a way to install additional echart as easily as grafana-cli?
https://github.com/VolkovLabs/volkovlabs-echarts-panel

The interface is too bad compared to Grafana.
I want to add all charts from that echart, can you guide me how to do that?
https://echarts.apache.org/en/index.html

**Comment by rusackas** [comment]
This isn't a bug, and there's plenty of documentation out there about building charts (and plenty of ECharts sample code). There's also lots of room to improve on our plugin interface, for sure. Proposals and PRs are more than welcome :) Thanks!
