### ISSUE TITLE
Unable to call custom api in non-dev mode. Is there a way to add custom api in config file which uses application context?

### ISSUE THREAD

**Issue by sughosh-kaushik-eightfold** [apache/superset#23355]
#### How to reproduce the bug
1. Add a custom api to SecurityRestAPI class.
2. Spin up dev docker.
3. Able to hit the api.
4. Spin up non-dev docker
5. Getting 404 error.

### Expected results
Able to access api in non-dev mode too.

### Actual results

unable to access api in non-dev mode.

### Environment

(please complete the following information):

- browser type and version: chrome 65
- superset version: `latest master branch`
- python version: `3.8.11`
- node.js version: ``
- any feature flags active: 
None

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Since this is a request regarding custom APIs, I think we'll have a hard time supporting it. It's not a bug, so I'll close it, and encourage you to try the `#customizing-superset` channel on [Superset Slack](http://bit.ly/join-superset-slack)
