### ISSUE TITLE
How to use feature DrillDown in Apache Superset?

### ISSUE THREAD

**Issue by duclinh1599** [apache/superset#23362]
I am trying to use the DrillDown feature of superset without knowing how to install it? Anyone who knows the answer or has already used this feature, please give feedback for me. I would like to thank you.

**Comment by sfirke** [comment]
There was a webinar this week that covered everything you'd want to know about drilling in Superset: https://www.youtube.com/watch?v=GrlRuOELJRw

**Comment by sfirke** [comment]
I am trying the "Drill to detail" feature in 2.1.0 release candidate 2 and it's nice.  You might also be interested in cross-filtering: https://preset.io/blog/cross-filtering-in-Superset-and-Preset/.

To install you'd install 2.1.0 once it's released (soon), then enable the `DRILL_TO_DETAIL` feature flag.

**Comment by duclinh1599** [comment]
> I am trying the "Drill to detail" feature in 2.1.0 release candidate 2 and it's nice. You might also be interested in cross-filtering: https://preset.io/blog/cross-filtering-in-Superset-and-Preset/.
> 
> To install you'd install 2.1.0 once it's released (soon), then enable the `DRILL_TO_DETAIL` feature flag.

Thanks for your answer. But I want to use Superset's Drilldown and the two features you say, I have finished setup and use it ok.

**Comment by sfirke** [comment]
It sounds like this answered your question about drilling.  If you have a question related to installation and usage, I'd suggest posting that as a Github "discussion" post or joining the Slack chat and asking there.
