### ISSUE TITLE
Incorrect UserDefinedType for columns when using Apache Drill on parquet files

### ISSUE THREAD

**Issue by C0ntroller** [apache/superset#23363]
I currently try to query data from parquet files using Apache Drill and visualize them in Superset.
Drill can access the original database and the parquet files in a S3-Store (which contain exports from the original DB)

When using Drill CLI directly to query the original database (where the parquet files are exported from) or the parquet files, in both cases the resulting schema of the records is correct. 
In the Database the column type is `NUMBER`, in Drill and parquet it's correctly converted to `DECIMAL`.

When using the SQL Lab in Superset and running the same queries to Drill it **will** work when using the connection to the original database but when running a query against a parquet file it will incorrectly show the `DECIMAL` data type as `UserDefinedType`.

#### How to reproduce the bug

1. Prepare Apache Drill and a storage plugin to access parquet files in S3
2. Prepare a parquet file with a `DECIMAL`-column (specifically `DECIMAL(38,0)`)
3. Add Drill as data srouce to superset
4. Go to SQL Lab in superset and show the schema for a "table" which is a parquet file
5. See `UserDefinedType` as column type

### Expected results

It should use `DECIMAL` as type

### Actual results

`UserDefinedType` as column type

### Environment

(please complete the following information):

- MS Edge 110.0.1587.69
- Using latest Superset docker container

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
