### ISSUE TITLE
Superset defaulting to local DB

### ISSUE THREAD

**Issue by collins-b** [apache/superset#23383]
I upgraded my superset environment with the master branch. The superset container is not starting because of:

```
2023-03-15 11:00:43,041:ERROR:flask_appbuilder.security.sqla.manager:DB Creation and initialization failed: (psycopg2.OperationalError) could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

### Expected results

I expected it to use the managed PSQL in AWS. The DB_HOST is pointing to the AWS URL but the container is defaulting to local psql.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sfirke** [comment]
Seems like this could be an issue with Superset latest on master, or a matter of your config.  Either way probably hard to debug here in a way that would be useful to anyone else.  If this issue persists, it might be a good candidate for joining the Slack and asking there?

**Comment by nytai** [comment]
Why is it defaulting to local? What is the value of `SQLALCHEMY_DATABASE_URI` in config?

**Comment by collins-b** [comment]
It turned out that my password had some special characters which conflicted with the SQLALCHEMY_DATABASE_URI. The host was hence invalid. Though the error message was misleading as you'd think it was trying to connect to local DB. To this, I remove those special characters from the DB string. The characters were @ and ). I'm thus closing this issue.
