### ISSUE TITLE
Druid on superset how to create a post-aggregation metric

### ISSUE THREAD

**Issue by Maplejw** [apache/superset#23381]
## Screenshot

![image](https://user-images.githubusercontent.com/24646597/225254666-d97f5889-e613-4cec-9a10-a7433da5af16.png)

## Description

apache superset 2.0.1

where I can add post-aggregations metric on superset 2.0.1? I do not find.

**Comment by sfirke** [comment]
Hello, this seems more like a usage question than a bug report.  This post might be better suited to a Github discussion or a post in the Superset Slack chat.

**Comment by Maplejw** [comment]
It is not a bug report.
