### ISSUE TITLE
"Cross filter scoping" offered to unauthorized users

### ISSUE THREAD

**Issue by aehanno** [apache/superset#23397]
In Superset 2.1.0rc2. On a public-facing dashboard, the public user can see this:
![image](https://user-images.githubusercontent.com/104373599/226372869-97ccb4d9-23ea-43fb-8acb-811defa8de8d.png)

Expected results
The user should not be offered cross filter scoping menu item.

Actual results
It's visible to the user.

**Comment by mdeshmu** [comment]
IMO, Even edit chart option shouldn't appear. Ping @eschutho !

**Comment by aehanno** [comment]
> IMO, Even edit chart option shouldn't appear. Ping @eschutho !

Sorry, I was not with the right user, I updated the screenshot

**Comment by eschutho** [comment]
I think this may be fixed in master as part of some new feature work around cross-filters. @geido or @kgabryje if you know which PR removes the menu item from embedded, then we can pull it into the 2.1.1 release.

**Comment by Sonalit23** [comment]
Hi, Could you please provide an update on the issue. It is required to restrict the read only users so that they can only view the dashboards/charts without changing the cross-filter scoping even though cross-filter is enable for the dashboard.

**Comment by aehanno** [comment]
Hey, yes it's fine, thanks
