### ISSUE TITLE
Duplicated permissions when display name of database is updated

### ISSUE THREAD

**Issue by xavier-GitHub76** [apache/superset#23394]
Hello,

an issue is present on Superset v1.5.2, permissions are duplicated when the display name of database is updated.

Steps to reproduce :
I add a database connection with the display name "ECOSQL_1".
After, I only update the display name to "ECOSQL_2"

I have following permissions :
![image](https://user-images.githubusercontent.com/82046143/225577669-d25a5ab4-5e05-4b5d-9206-3b991201056c.png)

As you could see permissions "ECOSQL_1" still exist and new permissions "ECOSQL_2" are created rather than updated.

This implies having to redefine the rights when it is only a simple update of the display name of connection.

Thanks for your support.

Best regards

**Comment by mdeshmu** [comment]
This was fixed in #20081.
Please upgrade.
