### ISSUE TITLE
cannot signin when make "AUTH_USER_REGISTRATION = false"

### ISSUE THREAD

**Issue by mrtsrdm** [apache/superset#23407]
I am trying to make Custom OAuth2 Configuration.

This is my "superset_config.py" file ->

**from flask_appbuilder.security.manager import AUTH_OAUTH
from custom_sso_security_manager import CustomSsoSecurityManager
CUSTOM_SECURITY_MANAGER = CustomSsoSecurityManager
AUTH_TYPE = AUTH_OAUTH
OAUTH_PROVIDERS = [
    {   'name':'egaSSO',
        'token_key':'acces_token', # Name of the token in the response of access_token_url
        'icon':'fa-address-card',   # Icon for the provider
        'remote_app': {
            'client_id':'ca4ca995-3b1e-4e01-81e1-1f226686a3f7',  # Client Id (Identify Superset application)
            'client_secret':'86086186-f97a-442e-925b-35ed25882d0a', # Secret for this Client Id 
            'client_kwargs':{
                'scope': 'offline_access'               # Scope for the Authorization
            },
            'access_token_method':'POST',    # HTTP Method to call access_token_url
            'access_token_params':{        # Additional parameters for calls to access_token_url
                'grant_type':'authorization_code',
                'client_id':'ca4ca995-3b1e-4e01-81e1-1f226686a3f7',
                'client_secret':'86086186-f97a-442e-925b-35ed25882d0a'
            },
            'api_base_url':'http://my-test.com:5100',
            'access_token_url':'http://my-test.com:5100/oauth/token',
            'authorize_url':'http://my-test.com:5100/connect/authorize',
            "request_token_url": None,
        }
    }
]
_AUTH_USER_REGISTRATION = True_
AUTH_USER_REGISTRATION_ROLE = "Public"**

and this is my "custom_sso_security_manager.py" file ->

**from superset.security import SupersetSecurityManager
class CustomSsoSecurityManager(SupersetSecurityManager):
    def oauth_user_info(self, provider, response=None):
        if provider == 'egaSSO':
            return { 'name' : 'mrt', 'email' : 'murat.test@test.com.tr', 'id' : '1', 'username' : 'mrt', 'first_name':'', 'last_name':''}**

There is no issue with these configs. However, when ı make _AUTH_USER_REGISTRATION = False_  , 
ı cannot signin. Do ı need to add another configs when ı make it false ?

**Comment by mdeshmu** [comment]
I don't think a Public role can login. You will need Minimum Gamma role to allow login.

**Comment by mrtsrdm** [comment]
@mdeshmu how can ı assign Gamma role, if ı make "AUTH_USER_REGISTRATION = false" ?

**Comment by mdeshmu** [comment]
If you are using AUTH_USER_REGISTRATION = True then change AUTH_USER_REGISTRATION_ROLE = "Gamma"

If you are using AUTH_USER_REGISTRATION = False then you will have to manually adjust roles using an admin user. If you do not have an admin then probably you should fallback to AUTH_TYPE = AUTH_DB, connect using admin/admin, update the user role then enable oauth again with AUTH_TYPE = AUTH_OAUTH

**Comment by mrtsrdm** [comment]
thank you @mdeshmu
