### ISSUE TITLE
DASHBOARD_CROSS_FILTERS didn't work

### ISSUE THREAD

**Issue by HelloValue** [apache/superset#23418]
#### How to reproduce the bug

1. docker pull apache/superset:latest
2. docker run -d -p 8080:8088 --name myperset apache/superset
3. docker exec -it mysuperset superset fab create-admin
4. docker exec -it mysuperset superset db upgrade
5. docker exec -it mysuperset superset init
6. create superset_config.py
`FEATURE_FLAGS = { 
    'DASHBOARD_NATIVE_FILTERS': True, 
    'DASHBOARD_CROSS_FILTERS': True,
    'DASHBOARD_NATIVE_FILTERS_SET':True,
    'DASHBOARD_FILTERS_EXPERIMENTAL': True } `
7. docker cp superset_config.py  mysuperset:/app/pythonpath/
8. docker exec -it mysuperset superset init
9. docker restart mysuperset
10. create chat by piechat

### Expected results
**i can use DASHBOARD_CROSS_FILTERS**

### Actual results
i can't use  DASHBOARD_CROSS_FILTERS in piechat

#### Screenshots
![image](https://user-images.githubusercontent.com/33114091/226123530-2342679d-e356-41ff-adb5-a617c1670ff4.png)

### Environment

(please complete the following information):

- superset version: `superset latest image from dockerhub`

**Comment by HelloValue** [comment]
> Control is moved to dashboard now. Please refer #22785

tks. 
so table are not supported now?

**Comment by mdeshmu** [comment]
Whatever was supported through explore should still be supported from dashboard.

**Comment by HelloValue** [comment]
> 

tks.
