### ISSUE TITLE
cannot logout completely

### ISSUE THREAD

**Issue by mrtsrdm** [apache/superset#23443]
I am trying to use superset with Custom OAuth2 Configuration.

This is my "superset_config.py" file ->

from flask_appbuilder.security.manager import AUTH_OAUTH
from custom_sso_security_manager import CustomSsoSecurityManager
CUSTOM_SECURITY_MANAGER = CustomSsoSecurityManager
AUTH_TYPE = AUTH_OAUTH
OAUTH_PROVIDERS = [
{ 'name':'egaSSO',
'token_key':'acces_token', # Name of the token in the response of access_token_url
'icon':'fa-address-card', # Icon for the provider
'remote_app': {
'client_id':'ca4ca995-3b1e-4e01-81e1-1f226686a3f7', # Client Id (Identify Superset application)
'client_secret':'86086186-f97a-442e-925b-35ed25882d0a', # Secret for this Client Id
'client_kwargs':{
'scope': 'offline_access' # Scope for the Authorization
},
'access_token_method':'POST', # HTTP Method to call access_token_url
'access_token_params':{ # Additional parameters for calls to access_token_url
'grant_type':'authorization_code',
'client_id':'ca4ca995-3b1e-4e01-81e1-1f226686a3f7',
'client_secret':'86086186-f97a-442e-925b-35ed25882d0a'
},
'api_base_url':'http://my-test.com:5100',
'access_token_url':'http://my-test.com:5100/oauth/token',
'authorize_url':'http://my-test.com:5100/connect/authorize',
"request_token_url": None,
}
}
]
AUTH_USER_REGISTRATION = True
AUTH_USER_REGISTRATION_ROLE = "Gamma"
AUTH_ROLES_SYNC_AT_LOGIN = True

and this is my "custom_sso_security_manager.py" file ->

from superset.security import SupersetSecurityManager
class CustomSsoSecurityManager(SupersetSecurityManager):
def oauth_user_info(self, provider, response=None):
if provider == 'egaSSO':
return { 'name' : 'mrt', 'email' : '[murat.test@test.com.tr](mailto:murat.test@test.com.tr)', 'id' : '1', 'username' : 'mrt', 'first_name':'', 'last_name':''}

---->

scenario to explain promlem:
1- ı click signin button in the superset login page
2- page redirects me to my own custom signin page
3- ı enter my username and pasword, and login succesfully
4- ı click logout button
5- page redirects me to superset lgin page
6- ı click signin button in the superset login page
7  The page redirects me directly to the welcome page as logged-in instead of redirecting me to my own signin page 

the system somehow stores my username and pasword info and make me logged-in. What can ı do to prevent this situation ?

**Comment by mrtsrdm** [comment]
hi @mdeshmu ,

ı think the problem is not about termination of token, because it takes new code with user credentials and takes new token with new code.

**Comment by mdeshmu** [comment]
You will have to replace OKTA_BASE_URL with base url of your provider.

In previous example, i just gave hint of the code. I didn't give full code. You will have to override AuthOAuthView for it to effect.

**Comment by mdeshmu** [comment]
@mrtsrdm are we good to close this issue?

**Comment by DataMinerR** [comment]
Hello @mdeshmu,

I am having the same issue.

Should that function be defined in superset_config_docker.py and the called under AuthOAuthView? And then just restart the superset_app container?

Thank you in advance!

**Comment by thanushcst** [comment]
Here the full example for logout with WSO2 as auth provider, You can replace it with others
`from superset.security import SupersetSecurityManager
from flask_appbuilder.security.views import AuthOAuthView
from flask_appbuilder.baseviews import expose
from flask import redirect
import os
import logging

class CustomSsoAuthOAuthView(AuthOAuthView):

    @expose("/logout/")
    def logout(self, provider="wso2", register=None):
        provider_obj = self.appbuilder.sm.oauth_remotes[provider]
        url = ("{}/oidc/logout?client_id={}&response_type={}&redirect_uri={}".format(
                    os.getenv("WSO2_BASE_URL"),
                    provider_obj.client_id,
                    provider_obj.server_metadata.get('response_type'),
                    provider_obj.server_metadata.get('logout_redirect_uri')
                    ) )

        ret = super().logout()
        return redirect(url)


class CustomSsoSecurityManager(SupersetSecurityManager):
    # override the logout function
    authoauthview = CustomSsoAuthOAuthView

    def oauth_user_info(self, provider, response=None):
       if provider == 'wso2':
            wso2_base_url = os.getenv("WSO2_BASE_URL")
            me = self.appbuilder.sm.oauth_remotes[provider].get(f'{wso2_base_url}/oauth2/userinfo').json()
            logging.debug(" user_data : %s", me)

            prefix = 'Superset'
            return {
                    'username' : me['username'],
                    'id': me['sub'],
                    'email': me['email'],
                    'roles' : me['roles']
            }
       
`

**Comment by rusackas** [comment]
Closing this one out since (a) it's gone silent, (b) we no longer support versions of Superset prior to 3.1, and (c) it seems like there are solutions on the thread that got positive feedback as working. If this needs revisiting/reopening, say the word, and we'll see what we can do.

**Comment by leezj-cbm** [comment]
Hi I am having the exact same issue as OP. I have tried using flask-oidc to logout. I also manually tried to delete the cookies and setting it to expire, however it doesnt work. Any solution will be greatly appreciated.


Pardon my code, I'm a beginner in python/flask.


keycloak_security_manager.py (Logging in no issues)
```
 @expose('/logout/', methods=['GET', 'POST'])
    def logout(self):
        logging.debug("🔵 KeyCloak_Security_Manager: Logout ")
        oidc = self.appbuilder.sm.oid   
        redirect_url = request.url_root.strip('/') + self.appbuilder.get_url_for_login   
        oidc.logout()
        super(AuthOIDCView, self).logout()
        client_id = oidc.client_secrets.get('client_id')
        id_token = self.get_id_token()
        cookieInitial = request.cookies.get('session')
        # log out redirect
        response = make_response(redirect(oidc.client_secrets.get('issuer') + 
                                          '/protocol/openid-connect/logout?post_logout_redirect_uri='+
                                          quote(redirect_url)+f"&client_id={client_id}&id_token_hint={id_token}"))
        self.modify_or_delete_cookie(response,cookieInitial)
        #response = make_response(redirect(oidc.client_secrets.get('issuer') + '/protocol/openid-connect/logout'))
        return response
    
    def modify_or_delete_cookie(self,response,cookieInitial):
        logging.debug(f"🔵 KeyCloak_Security_Manager: Attempting to delete / modify cookie ")
        response.set_cookie('oidc_id_token',value='',max_age=0,expires=0, path='/',domain=request.host,secure=False, httponly=False, samesite=None)
        response.delete_cookie('oidc_id_token',path='/',domain=request.host)
        cookieAfter = request.cookies.get('session')
        if cookieAfter == None :
            logging.debug(f"🟢 KeyCloak_Security_Manager: Succesful cookie deletion")
        elif cookieInitial != cookieAfter:
            logging.debug(f"🟢 KeyCloak_Security_Manager: Succesful cookie modification")
        else:
            if cookieAfter == cookieInitial:
                logging.debug(f"🔴 KeyCloak_Security_Manager: Unsuccesful cookie modification ")
            else:
                logging.debug(f"🔴 KeyCloak_Security_Manager: Unsuccesful cookie deletion ")    
        
    def get_id_token(self):
        sm=self.appbuilder.sm
        oidc=sm.oid
        token_uri = oidc.client_secrets.get('token_uri')
        client_id = oidc.client_secrets.get('client_id')
        client_secret = oidc.client_secrets.get('client_secret')
        refresh_token=oidc.get_refresh_token()
        
        data={
            'grant_type':'refresh_token',
            'client_id':client_id,
            'client_secret': client_secret,
            'refresh_token' :refresh_token,
        }
        logging.debug(f"🔵 KeyCloak_Security_Manager: Requesting for refresh token") 
        response= requests.post(token_uri,data=data,verify=False,)
        
        if response.status_code == 200:
            tokens=response.json()
            id_token= tokens.get('id_token')
            logging.debug(f"🟢 KeyCloak_Security_Manager: Succesfully obtained id_token") 
            return id_token
        else:
            logging.debug(f"🟡 KeyCloak_Security_Manager: Could not obtain id_token , code :{response.status_code} message:{response.text} ") 
        return None
            
```

Logs:

```
2024-07-19 15:22:20,546:DEBUG:root:🔵 KeyCloak_Security_Manager: Logout
2024-07-19 15:22:20,552:DEBUG:root:🔵 KeyCloak_Security_Manager: Requesting for refresh token
2024-07-19 15:22:20,553:DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8080
2024-07-19 15:22:20,560:DEBUG:urllib3.connectionpool:http://localhost:8080 "POST /realms/cbm-willowmore-dev/protocol/openid-connect/token HTTP/1.1" 200 4399
2024-07-19 15:22:20,561:DEBUG:root:🟢 KeyCloak_Security_Manager: Succesfully obtained id_token
2024-07-19 15:22:20,561:DEBUG:root:🔵 KeyCloak_Security_Manager: Attempting to delete / modify cookie
2024-07-19 15:22:20,561:DEBUG:root:🔴 KeyCloak_Security_Manager: Unsuccesful cookie modification
2024-07-19 15:22:20,563:INFO:werkzeug:127.0.0.1 - - [19/Jul/2024 15:22:20] "GET /logout/ HTTP/1.1" 302 -
```
