### ISSUE TITLE
How to cache a screenshot using rest API in superset

### ISSUE THREAD

**Issue by Karthik-art** [apache/superset#23449]
I want to get the chart image by hitting the API in our web application. 
I have modified the superset configuration using https://github.com/apache/superset/issues/20756#issuecomment-1211457084 link.

```
let request1 = Axios.get(baseUrl + '/api/v1/chart/86/cache_screenshot/?q=%7B%0A%20%20%22force%22%3A%20true%2C%0A%20%20%22thumb_size%22%3A%20%5B%0A%20%20%20%200%0A%20%20%5D%2C%0A%20%20%22window_size%22%3A%20%5B%0A%20%20%20%20100%0A%20%20%5D%0A%7D', 
                { headers: header }).then(record => {

	let imageHeader = {                  
		'accept': 'accept: image/*',                                 
		'Authorization': `Bearer ${token}`,
	};
	let request2 = Axios.get(record.data.image_url, { headers: imageHeader })
	.then(response => {                          
	}).catch( error => {                        
	});	
}).catch( error => {	
});
```
I'm getting response in request1 /api/v1/chart/{pk}/cache_screenshot
but request2 returns Not found.

**Comment by nytai** [comment]
The cache screenshot kicks off a job to capture the screenshot, it isn't immediately available

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
