### ISSUE TITLE
Language Selection doesn't always switch language

### ISSUE THREAD

**Issue by IamJeffG** [apache/superset#23456]
Language Selection doesn't always switch language

#### How to reproduce the bug

1. Run superset with `LANGUAGES` set in config.  I'm using `LANGUAGES={"en": {"flag": "us", "name": "English"}, "pt_BR": {"flag": "br", "name": "Português"}, "es": {"flag": "mx", "name": "Español"}, "fr": {"flag": "fr", "name": "Français"}, "nl": {"flag": "sr", "name": "Nederlands"}}`
2. Open web browser. You can replicate this from any page, including before logging in.
4. Click the flag in the top-right corner. Select a different language.
5. The page flashes to refresh in the new language.  Sometimes (not always) the language has changed, sometimes you are still seeing the old language!

### Expected results

The page flash to refresh is fine.  But afterward it should show in the language I just clicked on.

### Actual results

Sometimes you are still seeing the old language after having clicked a different one.  Specifically
- the flag icon remains unchanged
- the text strings on the rest of the page remain unchanged

#### Screenshots

![Peek 2023-03-22 11-54](https://user-images.githubusercontent.com/2002703/226981074-8ac3208e-6c58-4d02-bfbb-651be5d1fb6b.gif)

### Environment

**I did not** see this bug when running from the docker image `apache/superset:2.0.1`
**I do see this bug** running from the docker image `apache/superset:2.1.0rc3`.

- browser type and version: Firefox 111.0 (64-bit) on Linux.  Also Chromium Version 111.0.5563.64 (Official Build) (64-bit) on Linux
- superset version: `Superset 2.1.0`
- python version: `Python 3.8.16`
- node.js version:
```
$ docker exec -it superset_app node -v
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "node": executable file not found in $PATH: unknown
```
- any feature flags active:
```
FEATURE_FLAGS = {
    "ALERT_REPORTS": True,
}
```

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
    * no errors, just logs from the `/lang/nl` (or whatever language code) route and other routes needed for the current page.
    * the `/lang/nl` route returns a 302 redirect with `Location: /`
- [x] I have reproduced the issue with at least the latest released version of superset.
    * no bug on 2.0.1
    * bug on 2.1.0rc3
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dawnmarch** [comment]
We encountered the same problem. Changing the language works fine in versions 2.0.0 and 2.0.1, but it doesn't work as expected in version 2.1.0rc3.

**Comment by evvs** [comment]
> We encountered the same problem. Changing the language works fine in versions 2.0.0 and 2.0.1, but it doesn't work as expected in version 2.1.0rc3.

We have the same issue. That's why we don't update to the latest version ☹️

**Comment by andrey-pervushin** [comment]
this bug is still actual

**Comment by mpostelnicu** [comment]
same issue in 2.1.1rc1

**Comment by eschutho** [comment]
Thank you for reporting this. We'll find someone to take a look, unless anyone else wants to open a PR for it.

**Comment by mpostelnicu** [comment]
still happening in [2.1.1rc2](https://github.com/apache/superset/releases/tag/2.1.1rc2)

**Comment by rusackas** [comment]
I believe this was resolved by the linked PR, but the issue was never closed. Closing now, bu happy to revisit if needed.

**Comment by AghastyGD** [comment]
> this bug is still actual

yes, it's still with this

**Comment by rusackas** [comment]
@AghastyGD in which version of Superset? I was able to switch languages no problem on current `master`

**Comment by AghastyGD** [comment]
> @AghastyGD in which version of Superset? I was able to switch languages no problem on current `master`

@rusackas I am using the version 4.0.1 from PyPi Package, when I change to Brazilian the screen goes into blank with an infinite loading of superset logo

**Comment by rusackas** [comment]
Weird... I'm on `master` but I'm able two switch between all languages, including both Portuguese variants. Are you getting any browser console errors or server errors or something? Do you have any customized Superset code that might not be handling redirects correctly?

**Comment by AghastyGD** [comment]
Hi, thank you for your assistance, I was making a small mistake in the language selection in the feature flags, I was using "br" instead of  "pt-BR", I just changed that, and now it's working correctly. that's why it was giving me this error in the console:
![image](https://github.com/apache/superset/assets/95558305/42136de6-a543-4e65-a2c3-878ddf230bb8)

just changed to this:
![image](https://github.com/apache/superset/assets/95558305/f71176d8-820e-4197-9b72-5dffdcb2e054)

I'm sorry for any misunderstandings

**Comment by q631599119** [comment]
now I'm on master but this bug is still actual,
