### ISSUE TITLE
Embedding charts

### ISSUE THREAD

**Issue by waleedshabbir1** [apache/superset#23485]
Hello, 

I can see there are workarounds to embed the complete dashboard into the external react website but is there a way we can embed single chart into our blogging react website without exposing data sources and without authentication? 

I just want to display chart on a public website.

**Comment by eschutho** [comment]
Have you turned on the feature: EMBEDDABLE_CHARTS?

1. Click on the "Share" button in the top right corner of the chart editor.
2. In the "Share" dialog box, select the "Embed" tab.
3. Configure the chart's settings as needed, such as the chart size and any filters or parameters.
4. Copy the generated HTML code snippet.
5. In your React website, add an HTML container element where you want the chart to appear.
6. Paste the HTML code snippet from step 6 into this container element.
7. Save and publish your website.

This will embed the chart into your website using an iframe, which isolates the chart content and does not expose any data sources or require authentication. Note that this approach assumes that your Apache Superset instance is publicly accessible and that the chart is not restricted by any permissions or filters.

**Comment by waleedshabbir1** [comment]
@eschutho I tried that but it still shows authentication page. Any idea how to fix that?

**Comment by waleedshabbir1** [comment]
anyone?

**Comment by zs-err** [comment]
Did you find a solution? @waleedshabbir1 
I'm researching the same issue.

**Comment by eschutho** [comment]
@Antonio-RiveroMartnez maybe you might have some insight on this?

**Comment by Antonio-RiveroMartnez** [comment]
@waleedshabbir1  based on your description about getting redirected to login page, I believe it's not the chart itself nor the embedded solution but some missing configuration on the public role.

In order to your chart to be publicly accessible you must specify have a public role or use the `PUBLIC_ROLE_LIKE` in the config, this role must have permissions set so it can properly read the chart and also you must add public role to access the chart.

some permissions you might need are:

```
can write on ExploreFormDataRestApi,
can read on ExploreFormDataRestApi,
```

**Comment by zs-err** [comment]
I am not using embedded SDK because in my production it will not be allowed.

I'm trying to find best solution on using iframes for both the dashboard and charts. And how to integrate them inside angular application.

I'm trying to find solution how to do authentication in those and I'm not finding some. What I want is 3 things:

1. Access charts without user needing to log in to apache superset. I don't know how to make the chart itself public
2. Use custom authentication for dashboard so that user doesn't need to log in into dashboard if he is already logged in into my site. What I've seen this is not possbile?
3. Can I use the chart API to get the emphasized part of this url `http://localhost:8088/superset/explore/p/**_vxmXWAx1RA9_**/?standalone=1&height=400`. I want that part (the vxmXWAx1RA9 part) so I can dinamically add/remove embedeed charts without having to rebuild the whole frontend page. But I couldn't find that info on swagger?

IF this is out of scope for this issue I can create a new one or a new discussion

**Comment by jean-baka** [comment]
OK, but @eschutho kindly note we humbly disagree on your "which isolates the chart content and does not expose any data sources", which is also present in the [Preset docs](https://preset.io/blog/feature-flags-in-apache-superset-and-preset/). For instance, if I then get the URL of the iframe itself as `XXXX/superset/explore/p/Gpr7VLoz4bn/?standalone=1&height=400`, immediately rewritten into `XXXX/superset/explore/?form_data_key=CYG3Zfmw7IYHmRXLZppIO-59C3TfOb9L_QWqOpt4jSQsb28UcAJ8nU4_hvJP7DDi&slice_id=628&standalone=1&height=400` showing the same embed standalone in the page, and then trim the tail of the URL by removing the `&standalone=1&height=400`, you get access to the full underlying dataset and are able to edit the visualization, etc. How is that not "exposing the data source"?

Can't Superset just export to the iframe the necessary data to display the chart, and nothing else?

**Comment by apole** [comment]
Trying same thing, with iframe.  Get redirected back to login page.  

http://<superset server>/superset/dashboard/mydashboard/?standalone=1&edit=false&show_filters=1&access_token=<access token>

Tried sending access token derived using api/v1/security/guest_token/

Any input on how to pass the token  to iframe?

**Comment by waleedshabbir1** [comment]
@zs-err did you find any solution for "Access charts without user needing to log in to apache superset. I don't know how to make the chart itself public" ?

**Comment by zs-err** [comment]
@Antonio-RiveroMartnez Can I ask you to take a look at my questions or if you can provide me some source of info? (If you have the time, that is).

All options I find either use embedded SDK or I have to log in inside the iframe.

Is SDK no recommended for production?

**Comment by Antonio-RiveroMartnez** [comment]
Hey @zs-err I invite you to join our community's slack: https://superset.apache.org/community/ . There is channel exclusively open for embedding superset. Here's the link to one possible solution: https://apache-superset.slack.com/archives/C01EP56QGTS/p1667072833711929

**Comment by JollyGood97** [comment]
perhaps this might help https://www.tetranyde.com/blog/embedding-superset

**Comment by leandroembu** [comment]
I wonder why it's so difficult to share a single chart without log in.

**Comment by eschutho** [comment]
> OK, but @eschutho kindly note we humbly disagree on your "which isolates the chart content and does not expose any data sources", which is also present in the [Preset docs](https://preset.io/blog/feature-flags-in-apache-superset-and-preset/). For instance, if I then get the URL of the iframe itself as `XXXX/superset/explore/p/Gpr7VLoz4bn/?standalone=1&height=400`, immediately rewritten into `XXXX/superset/explore/?form_data_key=CYG3Zfmw7IYHmRXLZppIO-59C3TfOb9L_QWqOpt4jSQsb28UcAJ8nU4_hvJP7DDi&slice_id=628&standalone=1&height=400` showing the same embed standalone in the page, and then trim the tail of the URL by removing the `&standalone=1&height=400`, you get access to the full underlying dataset and are able to edit the visualization, etc. How is that not "exposing the data source"?
> 
> Can't Superset just export to the iframe the necessary data to display the chart, and nothing else?

I looked into this and found the extra information that you're referring to. We are working on removing extra response information from the embedded api that isn't necessary. This should be fixed in one of the upcoming releases.

**Comment by eschutho** [comment]
@jfrag1 or @lilykuang, can you help answer this question?

**Comment by FadeiKholyavo** [comment]
@waleedshabbir1 From official documentation. [https://superset.apache.org/docs/security/#public](url)
To allow logged-out users to access some Superset features, you can use the PUBLIC_ROLE_LIKE config setting and assign it to another role whose permissions you want passed to this role.

For example, by setting PUBLIC_ROLE_LIKE = "Gamma" in your superset_config.py file, you grant public role the same set of permissions as for the Gamma role. This is useful if one wants to enable anonymous users to view dashboards. Explicit grant on specific datasets is still required, meaning that you need to edit the Public role and add the public data sources to the role manually.

**Comment by frainfreeze** [comment]
> Hello,
> 
> I can see there are workarounds to embed the complete dashboard into the external react website but is there a way we can embed single chart into our blogging react website without exposing data sources and without authentication?
> 
> I just want to display chart on a public website.

For this usecase I recommend exporting static image and hosting on cdn, or if you want dynamic data you can export chart data and load on the client in apache echarts. I think this is the best option safety wise. It can be automated using APIs and should be better for caching IMHO.

**Comment by rusackas** [comment]
Hi all... this thread's been quiet for half a year, and the last two comments provide good suggestions for public embedding and single-chart embedding workarounds, so I'm going to close it out. It's true our single-chart embed isn't part of the Superset Embedded SDK. If someone wants to make contributions to that end, it would be welcomed, but as it stands, anything remaining on this thread seems more like feature requests than bugs, so I'd encourage migrating this to a GitHub Discussion if anyone wants to continue here. Let me know if that's the case.

**Comment by sohaibqasem** [comment]
Hi all. There is no official way to share charts securely so to achieve charts embedding for public (without authentication) you need to give the `public` role the needed permissions:

You can do this on two ways:

**First way:**
go to `superset/config.py` then go to `PUBLIC_ROLE_LIKE` and make it equal to `Gamma` and then run `superset init`

**Second way (more `specific` for chart-embed flow):**
Go to settings >> list Roles >> public >> edit
You need these permissions to be added (can remove or add if needed):
`can read on chart` `can read on Explore` `can read on ExploreFormDataRestApi` `can write on ExploreFormDataRestApi`
`can read on ExplorePermalinkRestApi` `can write on ExplorePermalinkRestApi` `can list on dynamicPlugin`
`can query form data on Api` `can query on Api` `can explore json on Superset` 
`all datasource access on all_datasource_access`

**Note that you need to keep track down what public role can really access**

**After** this you will be allowed to embed charts without Auth required and here also you have two options:
**Use** `embed code option` on the chart page (options list) **OR** the `/explore` end-point

The first one easy so i will give more details about `/explore` end-point which allow you to have **filters** on the **same embed URL**.

```
{{SUPERSET_HOST}}/explore/?form_data=encode(form_data_obj&slice_id=10&standalone=1)&slice_id=10&standalone=1
```

```js
form_data_obj = { adhoc_filters: [{}], slice_id: <number>}
```

**Example:**

```
{"adhoc_filters":[{"clause":"WHERE","comparator":2024,"expressionType":"SIMPLE","operator":"IN","subject":"year"}],"slice_id":10}&slice_id=10&standalone=1
```

Then **encode** it
```
%7B%22adhoc_filters%22%3A%5B%7B%22clause%22%3A%22WHERE%22%2C%22comparator%22%3A2024%2C%22expressionType%22%3A%22SIMPLE%22%2C%22operator%22%3A%22IN%22%2C%22subject%22%3A%22year%22%7D%5D%2C%22slice_id%22%3A10%7D%26slice_id%3D10%26standalone%3D1
```

**Final** URL:
```
{{SUPERSET_HOST}}/explore/?form_data=%7B%22adhoc_filters%22%3A%5B%7B%22clause%22%3A%22WHERE%22%2C%22comparator%22%3A2024%2C%22expressionType%22%3A%22SIMPLE%22%2C%22operator%22%3A%22IN%22%2C%22subject%22%3A%22year%22%7D%5D%2C%22slice_id%22%3A10%7D%26slice_id%3D10%26standalone%3D1&slice_id=10&standalone=1
```

**Final Thoughts:**
Until there is something **official** from **Superset** to handle this feature, i think you can do more complex solutions and keep Superset **secure** like embed Superset charts securely by rendering chart HTML on a server and delivering it to a client-side iframe, simplifying authentication and rendering handling (server).

**Comment by hug0b** [comment]
Here is a discussion for this feature request: https://github.com/apache/superset/discussions/26051
