### ISSUE TITLE
"Create new chart" link is not working

### ISSUE THREAD

**Issue by anait-lama** [apache/superset#23516]
When I open any dashbord, click on "Edit dashboard" -> "Create new chart", the link is broken.

**Comment by anait-lama** [comment]
Version 2.0.0

**Comment by sfirke** [comment]
This works fine for me on 2.0.1.  I'm trying to think if there could be an issue in your setup.  Could your user be missing a necessary permission?  What role are you?

**Comment by rusackas** [comment]
All seems to be woking just fine in 3.x. Say the word if you're still encountering this and we can revisit.
