### ISSUE TITLE
How can I draw a line chart with the X-axis as row ID instead of the date format? 

### ISSUE THREAD

**Issue by rindy8707** [apache/superset#23528]
How can I draw a line chart with the X-axis as row ID instead of the date format? 
Even though I selected the Line Chart instead of the Time-Series Line Chart, it is still requiring the X-axis to be in the Date format.

**Comment by sfirke** [comment]
This is probably more of a post for Slack or Github Discussions since it's not a bug report.  That said, what version of Superset are you using?  If you are using >= 2.0.0 and have the GENERIC_CHART_AXES feature flag enabled this should be possible.
