### ISSUE TITLE
Copy Dashboard Permission

### ISSUE THREAD

**Issue by kpolyd** [apache/superset#23532]
Removing the 'can copy dash on superset'  permission does not remove the option from the menu. 
Instead, when selecting 'save as'  and pressing 'save' the following error is displayed: 'Sorry, an unknown error occurred'
 
#### How to reproduce the bug
1. Remove permission 'can copy dash on superset'
2. Open the 3-dots menu and select 'Save as' 
3. Click 'SAVE'
4. A popup with the error  'Sorry, an unknown error occurred' is displayed

### Expected results

The option 'Save As' should not be displayed

### Environment
- browser: `FireFox Developer 112.0b8 (64-bit)`, `Google Chrome Version 111.0.5563.147 (Official Build) (64-bit)`
- superset version: `2.0.1`
- python version: `3.8.12`

### Additional context
Logs: 

> 2023-03-30 14:29:54 superset_app          | 172.22.0.1 - - [30/Mar/2023:11:29:54 +0000] "POST /superset/copy_dash/11/ HTTP/1.1" 403 51 "http://host.docker.internal:8088/superset/dashboard/11/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0"

**Comment by rusackas** [comment]
Since we're now on 3.1, on the verge of 4.0, we're not supporting 2.x  or prior versions actively. If anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)
