### ISSUE TITLE
2.1.0rc3 - Creation of Dataset from DB View with "/" symbol in name doesn't work

### ISSUE THREAD

**Issue by andrey-pervushin** [apache/superset#23540]
Creation of a Dataset from table with "/" symbol in name doesn't work. When you try to choose such table at the dataset creation screen it shows an error "Unable to load columns for the selected table. Please select a different table." It seems that the system uses http API call without URL encoding.

#### How to reproduce the bug

1. Go to "*/dataset/add/" URL, or push "+DATASET" button.
2. Choose database and schema.
3. Choose a table with "/" symbol in name

### Expected results

A list of fields with types should appear.

### Actual results

An error "Unable to load columns for the selected table. Please select a different table."

#### Screenshots
![2023_03_30_17_48_42_Superset](https://user-images.githubusercontent.com/129408742/229088379-eb7732e4-f885-437e-89e7-06ca0a0c9be0.png)
![2023_03_31_12_49_58_Superset](https://user-images.githubusercontent.com/129408742/229089217-d5aac08a-2165-46fa-87c5-52dedf46995a.png)

### Environment

- browser type and version: `MS Edge 111.0.1661.41`
- superset version: `2.1.0rc3`
- python version: `3.8.16-slim`
- node.js version: `16-slim`
- any feature flags active:
```javascript
{"ALERT_REPORTS": True,
 "RLS_IN_SQLLAB": True,
 "DASHBOARD_CROSS_FILTERS": True,
 "ENABLE_TEMPLATE_PROCESSING": True}
 ```

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Nothing to add.

**Comment by andrey-pervushin** [comment]
up^

**Comment by dbrultra** [comment]
Having the same issue, our schema has a  `/` in it giving the same error.

**Comment by andrey-pervushin** [comment]
Many thanks to @Always-prog !
