### ISSUE TITLE
type object 'Query' has no attribute 'query_class'

### ISSUE THREAD

**Issue by SyXuan** [apache/superset#23568]
Unexpected error happened when create charts
`type object 'Query' has no attribute 'query_class'`

It may be the issue with the `sqlalchemy` version

#### How to reproduce the bug

1. Create Line chart or heapmap
2. Click UPDATE CHART

### Expected results

Create a chart

### Actual results

Unexpected error
`type object 'Query' has no attribute 'query_class'`

```
Traceback (most recent call last):
  File "/app/superset/viz.py", line 580, in get_df_payload
    df = self.get_df(query_obj)
  File "/app/superset/viz.py", line 291, in get_df
    self.results = self.datasource.query(query_obj)
  File "/usr/local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
AttributeError: type object 'Query' has no attribute 'query_class'
```

### Environment

(please complete the following information):

- browser type and version: Chrome 111.0.5563.147
- superset version: docker `apache/superset:latest-dev`
- python version: `3.8.16`
- node.js version: `node -v`
- any feature flags active: docker-compose-non-dev.yml

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [v] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [v] I have reproduced the issue with at least the latest released version of superset.
- [v] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
I am not able to reproduce this... both charts are working fine in 3.x
