### ISSUE TITLE
Drill to Detail is not filtered if using Cross Filter

### ISSUE THREAD

**Issue by ilyaswp** [apache/superset#23583]
Hi i was wondering if it's possible to see the Drill to Detail data in the chart which i am using as a cross filter as well. 

#### How to reproduce the bug

1. Go to Dashboard
2. Click the Bar Chart to cross filter
3. Click on three dot vertical, to access Drill to Detail
4. Click Drill to Detail
5. The error

### Expected results

The product line in Pie Chart filtered Classic Car because in the Pie Chart i clicked Classic Car (The Dark Blue One)

### Actual results
![image](https://user-images.githubusercontent.com/75712631/229986723-cec6a104-a147-4ae7-8536-90f9826b168f.png)

#### Screenshots

Here is you can see if i am hovering to other charts and Drill to Detail is filtered by Classic Cars 
![image](https://user-images.githubusercontent.com/75712631/229986961-86b38c21-ff7b-4a02-b8fd-402eebd671e2.png)

### Environment

- superset version: `2.0.0`
- python version: `3.7.5`

Thank you.

**Comment by rusackas** [comment]
It seems that this is fine in current-era Superset. Closing, but happy to revisit.
