### ISSUE TITLE
Upgrade from 2.0.1 to 2.1.0 - no database menu

### ISSUE THREAD

**Issue by ziggekatten** [apache/superset#23608]
A running 2.0.1 installation  (Superset docker image at Docker hub)

Database: Postgres  14 

After deploy of 2.1.0 image:
superset db upgrade -> success
superset init ->success

Logging in as admin, and the menu option for adding/edit database is gone:

2.0.1:
![image](https://user-images.githubusercontent.com/55629049/230326987-2e0482cd-dd68-45bb-a145-0baf843ed11c.png)

2.1.0:
![image](https://user-images.githubusercontent.com/55629049/230327148-733fdded-8d7a-4b50-92f4-076b67563a13.png)

Have no clue on what to do, as the Admin role seems to have all menu accesses

**Comment by ziggekatten** [comment]
Update.

Running an superset init again, and it seems to try to create missing permissions every time, but starts with an warning:

`
/usr/local/lib/python3.8/site-packages/flask_appbuilder/models/sqla/interface.py:67:** SAWarning: relationship 'SqlaTable.slices' will copy column tables.id to column slices.datasource_id, which conflicts with relationship(s): 'Slice.table' (copies tables.id to slices.datasource_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="table"' to the 'SqlaTable.slices' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for prop in class_mapper(obj).iterate_properties:



Syncing role definition
2023-04-06 11:04:57,253:INFO:superset.security.manager:Syncing role definition
Syncing Admin perms
2023-04-06 11:04:57,276:INFO:superset.security.manager:Syncing Admin perms
Syncing Alpha perms
2023-04-06 11:04:58,043:INFO:superset.security.manager:Syncing Alpha perms
Syncing Gamma perms
2023-04-06 11:04:58,847:INFO:superset.security.manager:Syncing Gamma perms
Syncing granter perms
2023-04-06 11:04:59,646:INFO:superset.security.manager:Syncing granter perms
Syncing sql_lab perms
2023-04-06 11:05:00,352:INFO:superset.security.manager:Syncing sql_lab perms
Fetching a set of all perms to lookup which ones are missing
2023-04-06 11:05:01,239:INFO:superset.security.manager:Fetching a set of all perms to lookup which ones are missing
Creating missing datasource permissions.
2023-04-06 11:05:02,073:INFO:superset.security.manager:Creating missing datasource permissions.
Creating missing database permissions.
2023-04-06 11:05:02,555:INFO:superset.security.manager:Creating missing database permissions.
Cleaning faulty perms
2023-04-06 11:05:02,583:INFO:superset.security.manager:Cleaning faulty perms
`

**Comment by hienduyph** [comment]
`Settings > Data > Database Connections` is where you're looking for.

<img width="188" alt="image" src="https://user-images.githubusercontent.com/94601620/230701753-7f9307e0-1b12-4a27-8ecb-67cbc8306852.png">

**Comment by ziggekatten** [comment]
Uhhh....I thought I looked there and didn't see it. But yes, there it is!

**Comment by rusackas** [comment]
Sounds like we're all good, but holler if this needs further attention!

**Comment by ralphkretzschmar** [comment]
just to mention it:
a clean installation of 2.1.0 is starting and working. but running the following command:
"sudo docker exec -it superset_app superset db upgrade"

i get the same notification:
/usr/local/lib/python3.9/site-packages/flask_appbuilder/models/sqla/interface.py:67: SAWarning: relationship 'SqlaTable.slices' will copy column tables.id to column slices.datasource_id, which conflicts with relationship(s): 'Slice.table' (copies tables.id to slices.datasource_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="table"' to the 'SqlaTable.slices' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for prop in class_mapper(obj).iterate_properties:

**Comment by perugini** [comment]
Same as @ralphkretzschmar 

/usr/local/lib/python3.8/site-packages/flask_appbuilder/models/sqla/interface.py:67: SAWarning: relationship 'SqlaTable.slices' will copy column tables.id to column slices.datasource_id, which conflicts with relationship(s): 'Slice.table' (copies tables.id to slices.datasource_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="table"' to the 'SqlaTable.slices' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)

@rusackas, do you have any clues about it?

**Comment by vndroid** [comment]
> 与...一样@ralphkretzschmar
> 
> /usr/local/lib/python3.8/site-packages/flask_appbuilder/models/sqla/interface.py:67：SAWarning：关系“SqlaTable.slices”会将列tables.id复制到列slices.datasource_id，这与关系：'Slice.table'（将tables.id复制到slice.datasource_id）。如果这不是目的，请考虑这些关系是否应与 back_populates 链接，或者如果它们是只读的，是否应将 viewonly=True 应用于一个或多个关系。对于不太常见的外键约束部分重叠的情况，可以使用 orm.foreign() 注释来隔离应写入的列。要消除此警告，请将参数“overlaps="table"”添加到“SqlaTable.slices”关系中。（此错误的背景位于：https://sqlalche.me/e/14/qzyx）
> 
> @rusackas，你有什么线索吗？谢谢 ：）

I'm facing the same issue, No idea about it.
