### ISSUE TITLE
Manual update failure from 2.0.1 to 2.1.0

### ISSUE THREAD

**Issue by ngurmen** [apache/superset#23616]
I tried to manually update a Superset installation from 2.0.1 to 2.1.0 on a Ubuntu 20.04.6 LTS cloud instance.  It first gave a warning about pip to be updated.  With that I updated pip first and then apache-superset.  The update mentioned conflicts for pyopenssl and cryptography so I used pyopenssl cryptography==39.0.2.  However, the db upgrade step failed as it cannot connect to db although superset_config.py file is just working fine on 2.0.1.

#### How to reproduce the bug

1. pip install --upgrade pip
2. pip install apache-superset --upgrade
3. pip install pyopenssl cryptography==39.0.2
4. superset db upgrade

### Expected results

`superset db upgrade` command to succeed and db to be updated.

### Actual results

`superset db upgrade` command fails with an error that it cannot connect to the database.  The log connection string seems to be wrong but it works as expected on 2.0.1.

### Environment

(please complete the following information):

- Latest Chrome
- superset version: 2.0,1
- python version: 3.8.10
- any feature flags active: 
    "ALERT_REPORTS": True,
    "DASHBOARD_NATIVE_FILTERS": True,
    "DASHBOARD_CROSS_FILTERS": True,

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by eschutho** [comment]
hi @ngurmen can you add more details about the error if it's still happening? I haven't heard of similar reports, so I think this may be something related to your config or system.

**Comment by ngurmen** [comment]
hi @eschutho, I did not try further to upgrade to 2.1.1.  Since then I upgraded my server instance to support Python 3.10.  The earlier server was on Python 3.8.  With that I was able to upgrade to 3.0.0 skipping the 2.1.1.

**Comment by eschutho** [comment]
Ok, great. I'm glad that you were able to resolve it.
