### ISSUE TITLE
On save handlebars plugin template reverts to previous version of the code.

### ISSUE THREAD

**Issue by modidim2021** [apache/superset#23628]
On save handlebars plugin template reverts to previous version of the code.

#### How to reproduce the bug

1. Modify a handlebars template
2. Save it (do not go to dashboard)

### Expected results

Keep the modifications made.  The modifications are saved, It saves the template

### Actual results

Old code displayed

#### Screenshots

[If applicable, add screenshots to help explain your problem.](https://user-images.githubusercontent.com/130187722/230684753-4ec7dc77-8e9c-4935-a401-b1a83fc52eec.mp4)

### Environment

(please complete the following information):

- browser type and version:  Chrome (Version 111.0.5563.147 (Official Build) (64-bit))
- superset version: docker hub latest (as of 4/6/23)
- python version: 
- node.js version: 
- any feature flags active:
     HTML_SANITIZATION = False
     CONTENT_SECURITY_POLICY_WARNING = False

     "GENERIC_CHART_AXES": True,

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by kartikdhar** [comment]
+1 can confirm the same issue, on Superset 2.1.0

**Comment by rusackas** [comment]
Is this still an issue in 3.x? I've heard things are working better now, but would like confirmation on this one.

**Comment by rusackas** [comment]
Closing as stale... happy to reopen if people are facing this in currently supported versions.
