### ISSUE TITLE
Vulnerable issues (CVE)  with dependencies in Superset

### ISSUE THREAD

**Issue by hash-data** [apache/superset#23621]
Superset currently using :
WTForms version: 2.3.3

In there is a CVE vulnerability that can be found here https://pyup.io/v/42852/f17/
Tried to update the version but there is an error while running the flask-server with the newest version of WTForms: https://github.com/wtforms/wtforms/issues/781 (issue listed here)

Superset Currently using flask app-builder that is using sqlalchemy <1.5 restrict  (all versions  of flask app builder depend on sqlalchemy < 1.5)
Which have a CVE vulnerability for more info visit: https://pyup.io/v/51668/f17/

**Comment by hash-data** [comment]
hi  @dpgaspar any update on it

**Comment by dpgaspar** [comment]
I find this confusing, could not find any related CVE, snyk for example reports that: https://security.snyk.io/package/pip/wtforms/2.3.3 so 2.3.3 is considered safe

**Comment by hash-data** [comment]
can you please check the URL's I have provided

**Comment by dpgaspar** [comment]
I've checked. I don't doubt the accuracy of pyup.io, but it's confusing to not have a CVE and having a number of non oficial security scanners with conflicting reports.

Anyway, thank you for reporting this, It's truly appreciated. Bumping wtforms should have no blockers, but the major sqlalchemy bump will require a big effort

**Comment by dpgaspar** [comment]
> bumping wtforms will also have efforts as I tried and listed the issue on wtforms repo [wtforms/wtforms#781](https://github.com/wtforms/wtforms/issues/781)

Ivestigating the issue, seems like it's related with wtform_json (left a more detailed comment on the issue you created on wtforms)

**Comment by hash-data** [comment]
@dpgaspar any update on other vulnerability?

**Comment by dpgaspar** [comment]
I've found no CVE's that need to be patched on Superset regarding sqlalchemy: https://www.cvedetails.com/vulnerability-list/vendor_id-11979/Sqlalchemy.html

Wtforms is fixed
