### ISSUE TITLE
[Question]Are there any plans to automatically display all filtering values in the “Charts Filters” section of the Charts page, instead of requiring manual entry of filter items?

### ISSUE THREAD

**Issue by yuanoOo** [apache/superset#23630]
Are there any plans to automatically display all filtering values in the “Charts Filters” section of the Charts page, instead of requiring manual entry of filter items?

**Comment by rusackas** [comment]
Closing this since it's not a bug and is nearly a year old, but I'm not quite sure what you're asking for. Feel free to open a Discussion in the "Ideas" section and propose some examples/use cases.
