### ISSUE TITLE
Can not load init data when install superset with dock compose in windows OS

### ISSUE THREAD

**Issue by Zhengchaoqiang** [apache/superset#23632]
When follow the steps in doc, found one issue that no example data can be initialized.
Command:
- docker-compose -f docker-compose-non-dev.yml pull
- docker-compose -f docker-compose-non-dev.yml up 
Question:
Do not know how to configure for loading data successfully? Thanks.
------------------------------------------Logs as below----------------------------------------------------
superset_init         | Init Step 4/4 [Starting] -- Loading examples
superset_init         |
superset_init         |
superset_init         | ######################################################################
superset_init         |
superset_worker_beat  | [2023-04-10 00:26:00,000: INFO/MainProcess] Scheduler: Sending due task reports.scheduler (reports.scheduler)
superset_worker       | [2023-04-10 00:26:00,003: INFO/MainProcess] Task reports.scheduler[73708002-de11-4d06-be9b-f21b58c0d03d] received
superset_worker       | [2023-04-10 00:26:00,032: INFO/ForkPoolWorker-15] Task reports.scheduler[73708002-de11-4d06-be9b-f21b58c0d03d] succeeded in 0.02658774400015318s: None
superset_init         | logging was configured successfully
superset_init         | 2023-04-10 00:26:01,675:INFO:superset.utils.logging_configurator:logging was configured successfully
superset_init         | 2023-04-10 00:26:01,680:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
superset_init         | We haven't found any Content Security Policy (CSP) defined in the configurations. Please make sure to configure CSP using the TALISMAN_ENABLED and TALISMAN_CONFIG keys or any other external software. Failing to configure CSP have serious security implications. Check https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP for more information. You can disable this warning using the CONTENT_SECURITY_POLICY_WARNING key.
superset_init         | 2023-04-10 00:26:01,680:WARNING:superset.initialization:We haven't found any Content Security Policy (CSP) defined in the configurations. Please make sure to configure CSP using the TALISMAN_ENABLED and TALISMAN_CONFIG keys or any other external software. Failing to configure CSP have serious security implications. Check https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP for more information. You can disable this warning using the CONTENT_SECURITY_POLICY_WARNING key.
superset_init         | Falling back to the built-in cache, that stores data in the metadata database, for the following cache: `FILTER_STATE_CACHE_CONFIG`. It is recommended to use `RedisCache`, `MemcachedCache` or another dedicated caching backend for production deployments
superset_init         | 2023-04-10 00:26:01,682:WARNING:superset.utils.cache_manager:Falling back to the built-in cache, that stores data in the metadata database, for the following cache: `FILTER_STATE_CACHE_CONFIG`. It is recommended to use `RedisCache`, `MemcachedCache` or another dedicated caching backend for production deployments
superset_init         | Falling back to the built-in cache, that stores data in the metadata database, for the following cache: `EXPLORE_FORM_DATA_CACHE_CONFIG`. It is recommended to use `RedisCache`, `MemcachedCache` or another dedicated caching backend for production deployments
superset_init         | 2023-04-10 00:26:01,684:WARNING:superset.utils.cache_manager:Falling back to the built-in cache, that stores data in the metadata database, for the following cache: `EXPLORE_FORM_DATA_CACHE_CONFIG`. It is recommended to use `RedisCache`, `MemcachedCache` or another dedicated caching backend for production deployments
superset_init         | Loaded your LOCAL configuration at [/app/docker/pythonpath_dev/superset_config.py]
superset_init         | Loading examples metadata and related data into examples
superset_init         | Creating default CSS templates
superset_init         | Loading [World Bank's Health Nutrition and Population Stats]
superset_init         | /usr/local/lib/python3.8/site-packages/flask_appbuilder/models/sqla/interface.py:67: SAWarning: relationship 'Tag.objects' will copy column tag.id to column tagged_object.tag_id, which conflicts with relationship(s): 'SavedQuery.tags' (copies tag.id to tagged_object.tag_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="tags"' to the 'Tag.objects' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
superset_init         |   for prop in class_mapper(obj).iterate_properties:
superset_init         | /usr/local/lib/python3.8/site-packages/flask_appbuilder/models/sqla/interface.py:67: SAWarning: relationship 'TaggedObject.tag' will copy column tag.id to column tagged_object.tag_id, which conflicts with relationship(s): 'SavedQuery.tags' (copies tag.id to tagged_object.tag_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="tags"' to the 'TaggedObject.tag' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
superset_init         |   for prop in class_mapper(obj).iterate_properties:
superset_init         | /usr/local/lib/python3.8/site-packages/flask_appbuilder/models/sqla/interface.py:67: SAWarning: relationship 'Slice.tags' will copy column slices.id to column tagged_object.object_id, which conflicts with relationship(s): 'SavedQuery.tags' (copies saved_query.id to tagged_object.object_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="tags"' to the 'Slice.tags' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
superset_init         |   for prop in class_mapper(obj).iterate_properties:
superset_init         | /usr/local/lib/python3.8/site-packages/flask_appbuilder/models/sqla/interface.py:67: SAWarning: relationship 'Slice.tags' will copy column tag.id to column tagged_object.tag_id, which conflicts with relationship(s): 'SavedQuery.tags' (copies tag.id to tagged_object.tag_id), 'Tag.objects' (copies tag.id to tagged_object.tag_id), 'TaggedObject.tag' (copies tag.id to tagged_object.tag_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="objects,tag,tags"' to the 'Slice.tags' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
superset_init         |   for prop in class_mapper(obj).iterate_properties:
superset_init         | /usr/local/lib/python3.8/site-packages/flask_appbuilder/models/sqla/interface.py:67: SAWarning: relationship 'SqlaTable.slices' will copy column tables.id to column slices.datasource_id, which conflicts with relationship(s): 'Slice.table' (copies tables.id to slices.datasource_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="table"' to the 'SqlaTable.slices' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
superset_init         |   for prop in class_mapper(obj).iterate_properties:
superset_init         | /usr/local/lib/python3.8/site-packages/flask_appbuilder/models/sqla/interface.py:67: SAWarning: relationship 'Dashboard.tags' will copy column dashboards.id to column tagged_object.object_id, which conflicts with relationship(s): 'SavedQuery.tags' (copies saved_query.id to tagged_object.object_id), 'Slice.tags' (copies slices.id to tagged_object.object_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="tags,tags"' to the 'Dashboard.tags' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
superset_init         |   for prop in class_mapper(obj).iterate_properties:
superset_init         | /usr/local/lib/python3.8/site-packages/flask_appbuilder/models/sqla/interface.py:67: SAWarning: relationship 'Dashboard.tags' will copy column tag.id to column tagged_object.tag_id, which conflicts with relationship(s): 'SavedQuery.tags' (copies tag.id to tagged_object.tag_id), 'Slice.tags' (copies tag.id to tagged_object.tag_id), 'Tag.objects' (copies tag.id to tagged_object.tag_id), 'TaggedObject.tag' (copies tag.id to tagged_object.tag_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="objects,tag,tags,tags"' to the 'Dashboard.tags' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
superset_init         |   for prop in class_mapper(obj).iterate_properties:
superset_init         | Traceback (most recent call last):
superset_init         |   File "/usr/local/lib/python3.8/urllib/request.py", line 1354, in do_open
superset_init         |     h.request(req.get_method(), req.selector, req.data, headers,
superset_init         |   File "/usr/local/lib/python3.8/http/client.py", line 1256, in request
superset_init         |     self._send_request(method, url, body, headers, encode_chunked)
superset_init         |   File "/usr/local/lib/python3.8/http/client.py", line 1302, in _send_request
superset_init         |     self.endheaders(body, encode_chunked=encode_chunked)
superset_init         |   File "/usr/local/lib/python3.8/http/client.py", line 1251, in endheaders
superset_init         |     self._send_output(message_body, encode_chunked=encode_chunked)
superset_init         |   File "/usr/local/lib/python3.8/http/client.py", line 1011, in _send_output
superset_init         |     self.send(msg)
superset_init         |   File "/usr/local/lib/python3.8/http/client.py", line 951, in send
superset_init         |     self.connect()
superset_init         |   File "/usr/local/lib/python3.8/http/client.py", line 1418, in connect
superset_init         |     super().connect()
superset_init         |   File "/usr/local/lib/python3.8/http/client.py", line 922, in connect
superset_init         |     self.sock = self._create_connection(
superset_init         |   File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
superset_init         |     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
superset_init         |   File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
superset_init         |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
superset_init         | socket.gaierror: [Errno -2] Name or service not known
superset_init         |
superset_init         | During handling of the above exception, another exception occurred:
superset_init         |
superset_init         | Traceback (most recent call last):
superset_init         |   File "/usr/local/bin/superset", line 33, in <module>
superset_init         |     sys.exit(load_entry_point('apache-superset', 'console_scripts', 'superset')())
superset_init         |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
superset_init         |     return self.main(*args, **kwargs)
superset_init         |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 567, in main
superset_init         |     return super().main(*args, **kwargs)
superset_init         |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
superset_init         |     rv = self.invoke(ctx)
superset_init         |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
superset_init         |     return _process_result(sub_ctx.command.invoke(sub_ctx))
superset_init         |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
superset_init         |     return ctx.invoke(self.callback, **ctx.params)
superset_init         |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
superset_init         |     return __callback(*args, **kwargs)
superset_init         |   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
superset_init         |     return f(get_current_context(), *args, **kwargs)
superset_init         |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 407, in decorator
superset_init         |     return __ctx.invoke(f, *args, **kwargs)
superset_init         |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
superset_init         |     return __callback(*args, **kwargs)
superset_init         |   File "/app/superset/cli/examples.py", line 116, in load_examples
superset_init         |     load_examples_run(load_test_data, load_big_data, only_metadata, force)
superset_init         |   File "/app/superset/cli/examples.py", line 49, in load_examples_run
superset_init         |     examples.load_world_bank_health_n_pop(only_metadata, force)
superset_init         |   File "/app/superset/examples/world_bank.py", line 60, in load_world_bank_health_n_pop
superset_init         |     pdf = pd.read_json(url, compression="gzip")
superset_init         |   File "/usr/local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
superset_init         |     return func(*args, **kwargs)
superset_init         |   File "/usr/local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
superset_init         |     return func(*args, **kwargs)
superset_init         |   File "/usr/local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 733, in read_json
superset_init         |     json_reader = JsonReader(
superset_init         |   File "/usr/local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 818, in __init__
superset_init         |     data = self._get_data_from_filepath(filepath_or_buffer)
superset_init         |   File "/usr/local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 858, in _get_data_from_filepath
superset_init         |     self.handles = get_handle(
superset_init         |   File "/usr/local/lib/python3.8/site-packages/pandas/io/common.py", line 713, in get_handle
superset_init         |     ioargs = _get_filepath_or_buffer(
superset_init         |   File "/usr/local/lib/python3.8/site-packages/pandas/io/common.py", line 363, in _get_filepath_or_buffer
superset_init         |     with urlopen(req_info) as req:
superset_init         |   File "/usr/local/lib/python3.8/site-packages/pandas/io/common.py", line 265, in urlopen
superset_init         |     return urllib.request.urlopen(*args, **kwargs)
superset_init         |   File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
superset_init         |     return opener.open(url, data, timeout)
superset_init         |   File "/usr/local/lib/python3.8/urllib/request.py", line 525, in open
superset_init         |     response = self._open(req, data)
superset_init         |   File "/usr/local/lib/python3.8/urllib/request.py", line 542, in _open
superset_init         |     result = self._call_chain(self.handle_open, protocol, protocol +
superset_init         |   File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
superset_init         |     result = func(*args)
superset_init         |   File "/usr/local/lib/python3.8/urllib/request.py", line 1397, in https_open
superset_init         |     return self.do_open(http.client.HTTPSConnection, req,
superset_init         |   File "/usr/local/lib/python3.8/urllib/request.py", line 1357, in do_open
superset_init         |     raise URLError(err)
superset_init         | urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
superset_init exited with code 1
superset_app          | Loaded your LOCAL configuration at [/app/docker/pythonpath_dev/superset_config.py]
superset_app          | 127.0.0.1 - - [10/Apr/2023:00:26:17 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.74.0"
superset_app          | 127.0.0.1 - - [10/Apr/2023:00:26:47 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.74.0"
superset_worker_beat  | [2023-04-10 00:27:00,025: INFO/MainProcess] Scheduler: Sending due task reports.scheduler (reports.scheduler)
superset_worker       | [2023-04-10 00:27:00,028: INFO/MainProcess] Task reports.scheduler[dee39d8e-2baf-48a4-8d86-2c51a96b2003] received
superset_worker       | [2023-04-10 00:27:00,038: INFO/ForkPoolWorker-15] Task reports.scheduler[dee39d8e-2baf-48a4-8d86-2c51a96b2003] succeeded in 0.009468134999679023s: None
superset_app          | 127.0.0.1 - - [10/Apr/2023:00:27:17 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.74.0"
superset_app          | 127.0.0.1 - - [10/Apr/2023:00:27:47 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.74.0"
superset_worker_beat  | [2023-04-10 00:28:00,046: INFO/MainProcess] Scheduler: Sending due task reports.scheduler (reports.scheduler)
superset_worker       | [2023-04-10 00:28:00,048: INFO/MainProcess] Task reports.scheduler[228650fc-2f43-4136-abff-5bcce5ba0dff] received
superset_worker       | [2023-04-10 00:28:00,060: INFO/ForkPoolWorker-15] Task reports.scheduler[228650fc-2f43-4136-abff-5bcce5ba0dff] succeeded in 0.010970463000376185s: None
superset_app          | 127.0.0.1 - - [10/Apr/2023:00:28:17 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.74.0"
superset_app          | 127.0.0.1 - - [10/Apr/2023:00:28:47 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.74.0"
superset_worker_beat  | [2023-04-10 00:29:00,051: INFO/MainProcess] Scheduler: Sending due task reports.scheduler (reports.scheduler)
superset_worker       | [2023-04-10 00:29:00,053: INFO/MainProcess] Task reports.scheduler[f4b15833-f26b-4eeb-8048-171386bdfc9e] received
superset_worker       | [2023-04-10 00:29:00,066: INFO/ForkPoolWorker-15] Task reports.scheduler[f4b15833-f26b-4eeb-8048-171386bdfc9e] succeeded in 0.01158978900002694s: None
superset_app          | 127.0.0.1 - - [10/Apr/2023:00:29:17 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.74.0"
superset_app          | 127.0.0.1 - - [10/Apr/2023:00:29:47 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.74.0"
superset_worker_beat  | [2023-04-10 00:30:00,000: INFO/MainProcess] Scheduler: Sending due task reports.scheduler (reports.scheduler)
superset_worker       | [2023-04-10 00:30:00,003: INFO/MainProcess] Task reports.scheduler[01d3b04b-a095-4d2a-bf9b-e16c8d612425] received
superset_worker       | [2023-04-10 00:30:00,015: INFO/ForkPoolWorker-15] Task reports.scheduler[01d3b04b-a095-4d2a-bf9b-e16c8d612425] succeeded in 0.011264064000442886s: None
superset_app          | 127.0.0.1 - - [10/Apr/2023:00:30:17 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.74.0"

**Comment by rusackas** [comment]
What instructions are you following? Superset doesn't officially support Windows. I'll close this since I don't believe it's a bug, but you're welcome to join us on [Slack](http://bit.ly/join-superset-slack) in the #debugging-superset channel.
