### ISSUE TITLE
Bar Chart and area chart not handling epoch_ms dates properly (Out of bounds nanosecond timestamp error)

### ISSUE THREAD

**Issue by kartikdhar** [apache/superset#23645]
In Superset v2.1.0 - When trying to create a bar chart or area chart (new one), with a dataset that uses epoch_ms as datetime object, the calculations under the hood are incorrect. Superset is not handling the conversion correctly. This is a new issue that was not the case in previous version we were using (2.0.1)

#### How to reproduce the bug

1. With a dataset with epoch_ms as datetime value
2. Create a bar chart (new one)
3. Select any time grain or filters

### Expected results

Bar chart should be rendered as per the correct dates

### Actual results

Error:
```Out of bounds nanosecond timestamp: 167-01-01 00:00:00```

#### Screenshots

![CleanShot 2023-04-11 at 17 10 20](https://user-images.githubusercontent.com/5626803/231151940-c6a1f682-ee5a-43c1-a818-38e45c619bfd.jpg)

### Environment

(please complete the following information):

- Arc version 112
- superset version: `2.1.0`

- any feature flags active: ENABLE_TEMPLATE_PROCESSING, HTML_SANITIZATION = False

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

No addition context

**Comment by HeathLee** [comment]
Similar issue. With version 2.1.0
We have a column  `start_time` in millisecond timestamp format, and set epoch_ms in dataset

**Comment by HeathLee** [comment]
Hi @eschutho   is this issue still being addressed?

**Comment by rusackas** [comment]
Hi there, and sorry this has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale. If it is still an issue in Superset 3.x, we can happily re-open this, or feel free to open a new issue with updated context if that makes more sense. Thanks!
