### ISSUE TITLE
Unquoted datetime values in a generated query when using time column filter with Vertica

### ISSUE THREAD

**Issue by heyroman** [apache/superset#23661]
Superset generates invalid datetime filters that look like this
```
WHERE "timestamp_column" >= 2023-04-05 00:00:00.000000
  AND "timestamp_column" < 2023-04-12 00:00:00.000000
```
The values it inserts are unquoted which leads to query failing a syntax check.

#### How to reproduce the bug

1. Use a connection to Vertica
2. Create any chart with a time column
3. Try to add a filter on this time column (for example, "last week")

### Expected results

The generated query has a filter formatted as
```
WHERE "timestamp_column" >= '2023-04-05 00:00:00.000000'
  AND "timestamp_column" < '2023-04-12 00:00:00.000000'
```

### Actual results
```
WHERE "timestamp_column" >= 2023-04-05 00:00:00.000000
  AND "timestamp_column" < 2023-04-12 00:00:00.000000
```

### Environment
I'm trying superset out so I run it with docker-compose. Currently this issue is reproduced with `latest-dev` and `master` tags.
I have not made any changes to the configuration apart from adding 1 feature flag.
- any feature flags active: [ALERT_REPORTS, TAGGING_SYSTEM]

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ X ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ X ] I have reproduced the issue with at least the latest released version of superset.
- [ X ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by heyroman** [comment]
The issue is not reproduced with images tagged with `2.1.0` and `2.1.0-dev`

**Comment by rusackas** [comment]
This is likely fixed by now, but is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
