### ISSUE TITLE
Cannot import dashboard zip file from the same version superset

### ISSUE THREAD

**Issue by wyc990122** [apache/superset#23673]
- I used the superset in both dev and production environments in my company. Usually we make up the dashboards in dev environment first, then export the zip file to my local computer and then import the zip file to the production environment. But the zip file cannot be imported. I have recorded the way of the process to the video and it can't be uploaded here because of the internet reason.

#### How to reproduce the bug

1. Go to Dashboard in dev environment
2. Click on Export button
3. Waiting for the download process finish
4. Go to Dashboard in production environment
5. Click on Import dashboard button
6. Select the zip file downloaded at 4th step
7. Upload the file, input the password of the database, then the hints shows 'Dashboard imported' with no dashboard imported successfully

### Expected results
what you expected to happen.
- The dashboard can be imported correctly into superset.

### Actual results

what actually happens.

- It hints 'Dashboard imported',but the dashboard cannot be imported.
#### Screenshots

![Uploading image.png…]()
### Environment
- browser type and version:
- superset version: 2.0.0
- python version: 3.7
- node.js version: unknown
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ✔ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ❌ ] I have reproduced the issue with at least the latest released version of superset.
- [ ✔ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by Agos88** [comment]
Hi, any update about this bug? Currently, I'm using the superset version: 2.0.1 but I have the same issue.

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
