### ISSUE TITLE
🐛 Error 405 for chart preview update in boxplot chart editor

### ISSUE THREAD

**Issue by AOphagen** [apache/superset#23691]
Changing the chart preview for a boxplot, e.g. editing the y axis title, sends a PUT to `.../api/v1/explore/form_data?tab_id=<n>` and results in Error `405 METHOD NOT ALLOWED`. Presumably, a `POST` is expected? Accepting a `PUT` would be clearer for a change of only the preview? Also, that may be true for all chart editors, I found it editing a boxplot.

**Comment by marselbairam** [comment]
The problem is solved by updating the superset version.

**Comment by rusackas** [comment]
Assuming since this has been silent for so long that upgrading the version worked. Let me know if that's not the case :)
