### ISSUE TITLE
Feasibility to pass ID in where clause with Name in Filter box

### ISSUE THREAD

**Issue by jyoti-075** [apache/superset#23706]
Hi,

We are using superset with deprecated filter boxes where name column is used for charts. 
But in the database, we have an associated id for the name column.

The name column is being changed frequently, due to which we are losing the data on charts for previous names (as the where clause is going with name instead of id) 

We do not want to change the filter box to id column as that would not be user friendly.
Is there any way we can pass the id in where clause while still showing the name in the filter box?

Thanks in advance,
Jyoti

**Comment by rusackas** [comment]
Sorry, we're no longer supporting Filter Box. It'll be gone in the forthcoming 4.0 release.
