### ISSUE TITLE
During setup with docker, containers failing and 404 for static resources 

### ISSUE THREAD

**Issue by jyoti-075** [apache/superset#23703]
Hi ,

I am setting up superset in development mode, below were the steps followed for setup using docker 

https://superset.apache.org/docs/installation/installing-superset-using-docker-compose/

My system is Mac OS with version 12.5

I have cloned the superset repo and tried to bring up using docker compose up command

Post that i see 2 issues: 

1. I am able to login to http://localhost:8088/superset/welcome/ but for static loading.gif i am getting a 404 

Screenshot for reference : 
![Screenshot 2023-04-16 at 10 44 15 PM](https://user-images.githubusercontent.com/102945869/232329185-e1f66086-30c0-41ea-9c6c-1661d1089e46.png)

2. Out of 9 containers, 3 of my containers health check keeps failing 

![Screenshot 2023-04-16 at 10 45 17 PM](https://user-images.githubusercontent.com/102945869/232329249-529d0ad0-9dcd-4f57-93f2-b9d2f122863c.png)

Attaching the container logs which are exited 

[superset_init.docx](https://github.com/apache/superset/files/11242983/superset_init.docx)
[superset_websocket.docx](https://github.com/apache/superset/files/11242984/superset_websocket.docx)
[superset_worker.docx](https://github.com/apache/superset/files/11242985/superset_worker.docx)

Can someone please help in correcting the setup

**Comment by craigers521** [comment]
i'm having this same issue

**Comment by craigers521** [comment]
> i'm having this same issue

I moved the stack over to a linux and used the non-dev compose file and working now.  no worries.

**Comment by ForecastHealth** [comment]
I'm having the exact same issue, building on Ubuntu 20.04

**Comment by alberttwong** [comment]
related. https://github.com/apache/superset/issues/26170

**Comment by williamyuan86** [comment]
which version works? I run docker-compose on 3.1.0rc3, but this issue still exists. It seems some paths not mapping in the docker-compose.yml, Does anyone know how to change it?

**Comment by lllong33** [comment]
@williamyuan86 @jyoti-075  FYI
`sudo docker-compose -f docker-compose-non-dev.yml up -d` # success

**Comment by rusackas** [comment]
I think this is all largely resolved, and docker runs better/faster than ever, with improved documentation. I think this is closeable now, but let me know if you disagree, and we can reopen.
