### ISSUE TITLE
Error when translations work when setting the default language

### ISSUE THREAD

**Issue by AndVK** [apache/superset#23710]
Hi,

If you set another default language (for example, Russian), then when you switch to English, some menu items are not translated.

#### How to reproduce the bug

1. Set the following options in config.py
```
BABEL_DEFAULT_LOCALE = "ru"
# Your application default translation path
BABEL_DEFAULT_FOLDER = "superset/translations"
# Turning off i18n by default as translation in most languages are
# incomplete and not well maintained.
LANGUAGES = {
    "ru": {"flag": "ru", "name": "Russian"},
    "en": {"flag": "us", "name": "English"},
}
```
2. Login to the app
Make sure the default language is applied
![image](https://user-images.githubusercontent.com/89656461/232479642-5c2469a8-7876-4594-9a2e-dd990bea7056.png)

4. Switch language to English
![image](https://user-images.githubusercontent.com/89656461/232479933-08513d16-c1aa-4f29-8427-4bea380510ed.png)

### Expected results

The entire interface is translated into English

### Actual results

Some of the menu items were not translated into English.
message files contain all relevant translations. 
If you return the default English language, then all pages are translated correctly!
![image](https://user-images.githubusercontent.com/89656461/232484769-f431ec80-c106-4af2-902a-872ec928238f.png)

### Environment

- browser type and version: Google Chrome 110.0.5481.177
- superset version: `superset version` 2.0.1
- python version: `python --version` 3.10.0
- node.js version: `node -v` v14.19.3
- any feature flags active:
```
FEATURE_FLAGS = {
    "TAGGING_SYSTEM": True,
    "LISTVIEWS_DEFAULT_CARD_VIEW": True,
    "DASHBOARD_NATIVE_FILTERS_SET": True,
    "DASHBOARD_CROSS_FILTERS": True,
    "ENABLE_EXPLORE_DRAG_AND_DROP": True,
    "OMNIBAR": True,
    "ENABLE_TEMPLATE_PROCESSING": True,
    "ENABLE_TEMPLATE_REMOVE_FILTERS": True,
    "GENERIC_CHART_AXES": True,
    "DASHBOARD_RBAC": True,
}
```

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

The same problem was  described in the issue [#19431](https://github.com/apache/superset/issues/19431). But I didn't find a solution for it.
All compilations are done according to the [documentation](https://superset.apache.org/docs/contributing/translations)

Thanks in advance,
Andrew

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.

**Comment by AndVK** [comment]
@rusackas, the problem was resolved by updating the Superset to version (3.x)
