### ISSUE TITLE
Excel export option missing in dashboard

### ISSUE THREAD

**Issue by leo-schick** [apache/superset#23711]
New excel feature #22006 was added in 2.1.0, but the export option is not available in dashboards.

#### How to reproduce the bug

1. Go to Dashboard
3. Open "Download
4. See that there is no "Export to Excel" option

#### Screenshots

Download menu in dashboards:

![image](https://user-images.githubusercontent.com/67712864/232535615-7bb65485-5a87-47c8-ba23-dcd11a00d573.png)

Download menu in charts:

![image](https://user-images.githubusercontent.com/67712864/232535659-2142d6fc-cd98-4a7a-92bb-3ead99ca73f5.png)

### Environment

- superset version: `2.1.0`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Pinging @igorsinc here in case you have the wherewithal to take this on as an add-on to your prior work 🤞 

I'm on the fence as to whether this qualifies as a bug (and should stay open) or is a feature request (and should be moved to DIscussions). ¯\\\_(ツ)_/¯
