### ISSUE TITLE
There was an error loading the schemas (Azure)

### ISSUE THREAD

**Issue by gerickt** [apache/superset#23727]
Im trying to connect to a Mysql database in Azure, I include ssl and certificate root and added without problems... but, when try to get the schema in sql lab, i get this error:

`There was an error loading the schemas`

Im using docker, latest non-dev compose yml file.

Regards

**Comment by gerickt** [comment]
The log say this:

```
MySQLdb._exceptions.OperationalError: (1045, "Access denied for user 'my_user'@'154.53.60.47' (using password: YES)")
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 123, in Connect
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1045, "Access denied for user 'my_user'@'154.53.60.47' (using password: YES)")
superset.databases.commands.exceptions.DatabaseTestConnectionFailedError: [SupersetError(message='Either the username "my_user" or the password is incorrect.', error_type=<SupersetErrorType.CONNECTION_ACCESS_DENIED_ERROR: 'CONNECTION_ACCESS_DENIED_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'invalid': ['username', 'password'], 'engine_name': 'MySQL', 'issue_codes': [{'code': 1014, 'message': 'Issue 1014 - Either the username or the password is wrong.'}, {'code': 1015, 'message': 'Issue 1015 - Either the database is spelled incorrectly or does not exist.'}]})]
```

**Comment by gerickt** [comment]
the logs say this:

```
File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 123, in Connect
File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1045, "Access denied for user 'my_user'@'my_ip' (using password: YES)")
superset.databases.commands.exceptions.DatabaseTestConnectionFailedError: [SupersetError(message='Either the username "my_user" or the password is incorrect.', error_type=<SupersetErrorType.CONNECTION_ACCESS_DENIED_ERROR: 'CONNECTION_ACCESS_DENIED_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'invalid': ['username', 'password'], 'engine_name': 'MySQL', 'issue_codes': [{'code': 1014, 'message': 'Issue 1014 - Either the username or the password is wrong.'}, {'code': 1015, 'message': 'Issue 1015 - Either the database is spelled incorrectly or does not exist.'}]})]

```

**Comment by gerickt** [comment]
I move to 2.1.0 tag and toggle `show_compatibility_56=ON` on azure server parameters inside the resource.
Problem solved

**Comment by sfirke** [comment]
Can you, outside of Superset, query the schemas + tables with the same credentials you're using?  To test the credentials + connection setup.

**Comment by gerickt** [comment]
> Can you, outside of Superset, query the schemas + tables with the same credentials you're using? To test the credentials + connection setup.

Yes, without problems.
I use DBeaver/DataGrip in Windows to manage all my mysql and postgres databases in Azure without problems.

Regards.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for nearly a year, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!


Side note, are you running Superset on Windows? That might be a big part of the problem, since Windows is not officially supported.
