### ISSUE TITLE
Error to create datasets - after update from Supserset 2.0.1 to 2.1.0

### ISSUE THREAD

**Issue by T-Herrmann-WI** [apache/superset#23728]
Since the update to version 2.1 it is no longer possible to create datasets.

Querying databases or existing dashboards is no problem at all, but new dataset creation does not work. 

There seems to be some problem to write in the Superset internal SQLite DB.

The following error message appears:

psycopg2.errors.InvalidTextRepresentation) invalid input value for enum objecttypes: "dataset"
LINE 1: ..., '2023-04-18T16:06:27.768287'::timestamp, 2, 56, 'dataset',...
^

[SQL: INSERT INTO tagged_object (created_on, changed_on, tag_id, object_id, object_type, created_by_fk, changed_by_fk) VALUES (%(created_on)s, %(changed_on)s, %(tag_id)s, %(object_id)s, %(object_type)s, %(created_by_fk)s, %(changed_by_fk)s) RETURNING tagged_object.id]
[parameters: {'created_on': datetime.datetime(2023, 4, 18, 16, 6, 27, 768283), 'changed_on': datetime.datetime(2023, 4, 18, 16, 6, 27, 768287), 'tag_id': 2, 'object_id': 56, 'object_type': 'dataset', 'created_by_fk': 2, 'changed_by_fk': 2}]
(Background on this error at: https://sqlalche.me/e/14/9h9h)

**Comment by T-Herrmann-WI** [comment]
Ok, but it works on a new fresh installation with version 2.1.0 without this error. It looks that some migrations won't work correct of the DB's, Dataset's etc.

**Comment by ShenglanLuCPH** [comment]
> We are experiencing the same errors after upgrading to from 2.0.1 2.1.0. Both when creating the datasets and when deleting the dataset.

After reading the error message carefully, we think it might be related to a feature flag that we enabled. After removing the feature flag `TAGGING_SYSTEM`, then we can create and delete dataset again.

**Comment by T-Herrmann-WI** [comment]
Thank you. This works!! Our alternative workaround was to export all dashboards, make everything new and reimport the dashboards. After this the datasets can be created again.

**Comment by NikitaUshanov** [comment]
Check "objecttypes" type table in your DB. 
It must contain "dataset" type.
If it not, recreate "objecttypes" type table with code:

```SQL
DROP TYPE db_name."objecttypes";

CREATE TYPE db_name."objecttypes" AS ENUM (
	'query',
	'chart',
	'dashboard',
	'dataset');
```

**Comment by rusackas** [comment]
Hopefully, the answers above are sufficient to close this thread. I'll do so anyway since it's been so long since there was a comment here, and we're no longer supporting Superset 2.x. The tagging system has come a long way! If this needs revisiting/reopening, just say the word and give us a context update!

**Comment by T-Herrmann-WI** [comment]
Yes it is solved
