### ISSUE TITLE
Apache superset export to excel

### ISSUE THREAD

**Issue by maneesh8123** [apache/superset#23739]
The excel export is available in the edit chart, but not in the charts in the dashboard.
Could it be possible to add this functionality also to the charts included in a dashboard?
This way, users that do not have edit permission can also access this feature

**Comment by sfirke** [comment]
Hello, this is a great point but also has been posted already at https://github.com/apache/superset/issues/23711.  This one is a duplicate and can be closed.

**Comment by rusackas** [comment]
Closing duplicate
