### ISSUE TITLE
Deployment behind nginx proxy manager

### ISSUE THREAD

**Issue by radaniba** [apache/superset#23740]
Hi team,
I am trying to deploy superset using docker but also using nginx proxy manager to add SSL and a domain name that points to my IP and port in production.

My Setup looks like this image attached here.

![image](https://user-images.githubusercontent.com/1666443/233109337-8abb92af-f839-46f5-a801-1372d383c690.png)

It is working fine to some extent, but I noticed that the redirection after nginx proxy manager always adds the PORT number to the domain name, which is not supposed to happen, thus breaking the link and the access.

Instead of ending up with [domain.com/superset/welcome](http://domain.com/superset/welcome) or [domain.com/login](http://domain.com/login)

I always have domain.com:8088/superset/welcome or domain.com:8088/login

This is breaking the access obviously to the app

I know that nginx proxy manager is doing its job here as I have the same procedure working with many services, the problem is in the routing Is it something I can fix in superset ? if yes how ?

I tried to change WEBDRIVER_BASEURL but still not working properly

Thanks

Rad

**Comment by radaniba** [comment]
Issue resolved in NPM sorry

**Comment by lianstemp** [comment]
> Issue resolved in NPM sorry

Hi, May I know how you fixed this problem, as this is my problem now
