### ISSUE TITLE
Superset Inconsistent with SQL LAB csv downloads

### ISSUE THREAD

**Issue by rey2107** [apache/superset#23749]
when we are running the query on superset the query gives output ,although our limit is set to 10L, also the table has crores of rows, but only sadly in each iteration I download 10k,12k,15k records come. Also when I hit the API from backend via python its working fine but via superset UI wanted to know why is it so inconsistent

**Comment by rey2107** [comment]
The database is PostgreSQL

**Comment by rey2107** [comment]
Should I try this with 2.0.1 ? or 2.1.0 is stable?

**Comment by rusackas** [comment]
We no longer support 2.x, even. If anyone is still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
