### ISSUE TITLE
export for dashboard is not working

### ISSUE THREAD

**Issue by rindy8707** [apache/superset#23761]
superset 2.0.1
python 3.8

ON dashboard page, I clicked export button.
but It is not working just loading.

In the config.py, I write "VERSIONE_EXPORT=TRUE"

### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by LiJoinGit** [comment]
https://github.com/apache/superset/issues/23349  You can refer to this

**Comment by rusackas** [comment]
I believe this is fixed, and this version of Superset is no longer supported. If anyone is still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
