### ISSUE TITLE
Fail to send several alerts triggered at the same time

### ISSUE THREAD

**Issue by Bill0412** [apache/superset#23763]
#### How to reproduce the bug

1. Go to 'Alerts and reports'.
2. Set two or more slack alerts with the same time and make sure they will be triggered at the same time.

### Expected results

All of the screenshots should be sent, but only one is sent.

### Actual results

 One screenshot is taken and sent, another fails.

#### Screenshots

```
[2023-04-21 02:07:00,177: INFO/ForkPoolWorker-16] Init selenium driver
Init selenium driver
[2023-04-21 02:07:00,183: INFO/ForkPoolWorker-1] Init selenium driver
[2023-04-21 02:07:01,324: INFO/ForkPoolWorker-1] Task reports.execute[32f9e0dd-9773-4f77-b2b7-e05f5cdb8066] succeeded in 1.2880826219916344s: None
Taking a PNG screenshot of url http://superset:8088/explore/?form_data=%7B%22slice_id%22%3A%2015%7D&force=true&standalone=true as user admin
[2023-04-21 02:07:11,077: INFO/ForkPoolWorker-16] Taking a PNG screenshot of url http://superset:8088/explore/?form_data=%7B%22slice_id%22%3A%2015%7D&force=true&standalone=true as user admin
Report sent to slack
[2023-04-21 02:07:13,268: INFO/ForkPoolWorker-16] Report sent to slack
```

### Environment

(please complete the following information):

- browser type and version: not related to browser
- superset version: 2.1.0
- python version: 3.8.16
- node.js version: `node -v`(unable to get it)
- google-chrome version: Google Chrome 112.0.5615.165
- ChromeDriver 112.0.5615.49 (bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936})
- any feature flags active:

```
WEBDRIVER_TYPE = 'chrome'
WEBDRIVER_OPTION_ARGS = [
    "--no-sandbox",
    "--force-device-scale-factor=2.0",
    "--high-dpi-support=2.0",
    "--headless",
    "--disable-gpu",
    "--disable-setuid-sandbox",
    "--disable-extensions",
    "--disable-dev-shm-usage",
    "--remote-debugging-port=9222"
]
```

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by Bill0412** [comment]
Sometimes the error is different:
```
Failed taking a screenshot Message: disconnected: not connected to DevTools (failed to check if window was closed: disconnected: not connected to DevTools) (Session info: headless chrome=112.0.5615.49)
```

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
