### ISSUE TITLE
Pie chart doesn't reflect data in table

### ISSUE THREAD

**Issue by dtlhlbs** [apache/superset#23788]
The pie chart is missing a sizeable slice of data that is shown in the corresponding table. Yet it shows smaller slices.

#### How to reproduce the bug

1. Create a pie chart
2. Set a filter
3. Select "View as Table" for the pie chart

### Expected results

Pie chart reflects the table data

### Actual results

Pie chart is missing key data so is misrepresenting data.

#### Screenshots

![image](https://user-images.githubusercontent.com/49377835/233870575-0639be34-4625-4037-9a5c-ab8a3c033bdd.png)

- browser type and version: Chrome latest
- superset version: `superset version`: 'docker:latest' (`Superset 0.0.0-dev`) **Please tag your docker images according to releases.**
- python version: `python --version` from docker image `3.8.16`
- node.js version: `node -v` from docker image 
- any feature flags active: n/a

**Comment by 353913575** [comment]
maybe the filters which In the upper right corner affects the final output result

**Comment by dtlhlbs** [comment]
> maybe the filters which In the upper right corner affects the final output result

The hours in the table are the same as the hours on the pie chart, the filter isn't trying to filter out the missing rows, the filter is active and outputting the correct values in the table. The pie chart reflects the data in the table, but it's just missing two rows.

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
