### ISSUE TITLE
In SQL Server, superset supports temporary tables in SQL lab, but not in chart,(Incorrect syntax near the keyword 'INTO')

### ISSUE THREAD

**Issue by lssdo12** [apache/superset#23781]
#### How to reproduce the bug

- Using temporary tables in SQL lab can return data
  ```
  SELECT
    *
  INTO
    #temp
  FROM
    ptype
  
  SELECT * FROM #temp
  ```

- Then save dataset(save and explore), add any columns to DIMENSIONS, click 'CREATE CHART'

### Expected results

use temp table in Chart,
return data as in SQL Lab

### Actual results

- Error occurred when I created a Chart from Datasets

  ```
  Unexpected error
  Error: (156, b"Incorrect syntax near the keyword 'INTO'.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n")
  ```

#### Screenshots

- This is running in Sql Lab and the results can be obtained
![issue1](https://user-images.githubusercontent.com/59727014/233758109-34812c09-4546-4d90-b41b-4be15e95293a.png)

- Error occurred when I created a Chart from Datasets

![issue2](https://user-images.githubusercontent.com/59727014/233758149-cccf0c99-59ac-4775-80fc-e9eceb4114b9.png)

### Environment

(please complete the following information):

- browser type and version: Chrome newest
- superset version: Pulled from the docker on 2023-04-21
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I really need to use temporary tables to improve my query performance

**Comment by benjaminlhai** [comment]
I am also experiencing this issue

**Comment by rusackas** [comment]
Is this still an issue in 3.x? We no longer support 2.x or prior. I think we just need queries to be a single statement, so we don't ONLY run the last query, rather than the two in sequence like a workbook or something. CC @justinpark @john-bodley to make sure I'm not misinterpreting.

**Comment by rusackas** [comment]
We never heard back if this was happening in 3.x, and now we'll soon only be supporting 4.x and up. I'll close this out as stale but if anyone is still facing this in 4.x, we're more than happy to reopen it. :)
