### ISSUE TITLE
Import database fails

### ISSUE THREAD

**Issue by lozbrown** [apache/superset#23799]
A functional and working database that was configured via the UI and exported cannot be imported to superset via the cli

#### How to reproduce the bug

Use superset import_datasources -p to import 

### Expected results

Database successfully imported and updated 

### Actual results

> `root@superset-7759bb8887-sj9ln:/app# superset import_datasources -p /app/import_datasources_fmt.yaml
> Loaded your LOCAL configuration at [/app/pythonpath/superset_config.py]
> logging was configured successfully
> 2023-04-24 15:04:46,625:INFO:superset.utils.logging_configurator:logging was configured successfully
> 2023-04-24 15:04:46,630:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
> We haven't found any Content Security Policy (CSP) defined in the configurations. Please make sure to configure CSP using the TALISMAN_CONFIG key or any other external software. Failing to configure CSP have serious security implications. Check https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP for more information. You can disable this warning using the CONTENT_SECURITY_POLICY_WARNING key.
> 2023-04-24 15:04:46,631:WARNING:superset.initialization:We haven't found any Content Security Policy (CSP) defined in the configurations. Please make sure to configure CSP using the TALISMAN_CONFIG key or any other external software. Failing to configure CSP have serious security implications. Check https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP for more information. You can disable this warning using the CONTENT_SECURITY_POLICY_WARNING key.
> /usr/local/lib/python3.8/site-packages/flask_caching/__init__.py:201: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
>   warnings.warn(
> Falling back to the built-in cache, that stores data in the metadata database, for the following cache: `FILTER_STATE_CACHE_CONFIG`. It is recommended to use `RedisCache`, `MemcachedCache` or another dedicated caching backend for production deployments
> 2023-04-24 15:04:46,633:WARNING:superset.utils.cache_manager:Falling back to the built-in cache, that stores data in the metadata database, for the following cache: `FILTER_STATE_CACHE_CONFIG`. It is recommended to use `RedisCache`, `MemcachedCache` or another dedicated caching backend for production deployments
> Falling back to the built-in cache, that stores data in the metadata database, for the following cache: `EXPLORE_FORM_DATA_CACHE_CONFIG`. It is recommended to use `RedisCache`, `MemcachedCache` or another dedicated caching backend for production deployments
> 2023-04-24 15:04:46,635:WARNING:superset.utils.cache_manager:Falling back to the built-in cache, that stores data in the metadata database, for the following cache: `EXPLORE_FORM_DATA_CACHE_CONFIG`. It is recommended to use `RedisCache`, `MemcachedCache` or another dedicated caching backend for production deployments
> Importing dataset from file /app/import_datasources_fmt.yaml
> 2023-04-24 15:04:48,007:INFO:superset.datasets.commands.importers.v0:Importing dataset from file /app/import_datasources_fmt.yaml
> Importing 1 databases
> 2023-04-24 15:04:48,007:INFO:superset.datasets.commands.importers.v0:Importing 1 databases
> Importing new dbs prestodev2
> 2023-04-24 15:04:48,025:INFO:superset.models.helpers:Importing new dbs prestodev2
> Error running import command
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
>     self.dialect.do_execute(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
>     cursor.execute(statement, parameters)
> psycopg2.ProgrammingError: can't adapt type 'dict'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/app/superset/datasets/commands/importers/dispatcher.py", line 57, in run
>     command.run()
>   File "/app/superset/datasets/commands/importers/v0.py", line 261, in run
>     import_from_dict(db.session, config, sync=self.sync)
>   File "/app/superset/datasets/commands/importers/v0.py", line 225, in import_from_dict
>     session.commit()
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
>     return getattr(self.registry(), name)(*args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1046, in commit
>     self.transaction.commit()
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 504, in commit
>     self._prepare_impl()
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
>     self.session.flush()
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2540, in flush
>     self._flush(objects)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2682, in _flush
>     transaction.rollback(_capture_exception=True)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
>     compat.raise_(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
>     raise exception
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2642, in _flush
>     flush_context.execute()
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
>     rec.execute(self)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
>     persistence.save_obj(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
>     _emit_insert_statements(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1135, in _emit_insert_statements
>     result = cached_connections[connection].execute(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
>     return meth(self, multiparams, params)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
>     return connection._execute_clauseelement(self, multiparams, params)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
>     ret = self._execute_context(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
>     self._handle_dbapi_exception(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
>     util.raise_(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
>     raise exception
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
>     self.dialect.do_execute(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
>     cursor.execute(statement, parameters)
> sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'dict'
> [SQL: INSERT INTO dbs (uuid, created_on, changed_on, verbose_name, database_name, sqlalchemy_uri, password, cache_timeout, select_as_create_table_as, expose_in_sqllab, allow_run_async, allow_file_upload, allow_ctas, allow_cvas, allow_dml, force_ctas_schema, allow_multi_schema_metadata_fetch, extra, encrypted_extra, impersonate_user, server_cert, is_managed_externally, external_url, created_by_fk, changed_by_fk) VALUES (%(uuid)s, %(created_on)s, %(changed_on)s, %(verbose_name)s, %(database_name)s, %(sqlalchemy_uri)s, %(password)s, %(cache_timeout)s, %(select_as_create_table_as)s, %(expose_in_sqllab)s, %(allow_run_async)s, %(allow_file_upload)s, %(allow_ctas)s, %(allow_cvas)s, %(allow_dml)s, %(force_ctas_schema)s, %(allow_multi_schema_metadata_fetch)s, %(extra)s, %(encrypted_extra)s, %(impersonate_user)s, %(server_cert)s, %(is_managed_externally)s, %(external_url)s, %(created_by_fk)s, %(changed_by_fk)s) RETURNING dbs.id]
> [parameters: {'uuid': UUID('48bc9058-3e74-48d4-85ef-8b94f5044165'), 'created_on': datetime.datetime(2023, 4, 24, 15, 4, 48, 27077), 'changed_on': datetime.datetime(2023, 4, 24, 15, 4, 48, 27082), 'verbose_name': None, 'database_name': 'prestodev2', 'sqlalchemy_uri': "presto://MYDEVUSER:MYDEVPASSWORD@quasar-query-dev.macbank:4039", 'password': <psycopg2.extensions.Binary object at 0x7efd2d8a0ed0>, 'cache_timeout': None, 'select_as_create_table_as': False, 'expose_in_sqllab': True, 'allow_run_async': False, 'allow_file_upload': False, 'allow_ctas': False, 'allow_cvas': True, 'allow_dml': False, 'force_ctas_schema': None, 'allow_multi_schema_metadata_fetch': False, 'extra': {'engine_params': {'connect_args': {'protocol': 'https', 'source': 'superset 2.0.1', 'requests_kwargs': {'verify': '/app/mac-ca-bundle'}}}, 'metadata_params': {}, 'schemas_allowed_for_csv_upload': []}, 'encrypted_extra': None, 'impersonate_user': False, 'server_cert': None, 'is_managed_externally': False, 'external_url': None, 'created_by_fk': None, 'changed_by_fk': None}]
> (Background on this error at: http://sqlalche.me/e/13/f405)
> 2023-04-24 15:04:48,028:ERROR:superset.datasets.commands.importers.dispatcher:Error running import command
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
>     self.dialect.do_execute(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
>     cursor.execute(statement, parameters)
> psycopg2.ProgrammingError: can't adapt type 'dict'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/app/superset/datasets/commands/importers/dispatcher.py", line 57, in run
>     command.run()
>   File "/app/superset/datasets/commands/importers/v0.py", line 261, in run
>     import_from_dict(db.session, config, sync=self.sync)
>   File "/app/superset/datasets/commands/importers/v0.py", line 225, in import_from_dict
>     session.commit()
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
>     return getattr(self.registry(), name)(*args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1046, in commit
>     self.transaction.commit()
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 504, in commit
>     self._prepare_impl()
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
>     self.session.flush()
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2540, in flush
>     self._flush(objects)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2682, in _flush
>     transaction.rollback(_capture_exception=True)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
>     compat.raise_(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
>     raise exception
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2642, in _flush
>     flush_context.execute()
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
>     rec.execute(self)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
>     persistence.save_obj(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
>     _emit_insert_statements(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1135, in _emit_insert_statements
>     result = cached_connections[connection].execute(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
>     return meth(self, multiparams, params)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
>     return connection._execute_clauseelement(self, multiparams, params)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
>     ret = self._execute_context(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
>     self._handle_dbapi_exception(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
>     util.raise_(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
>     raise exception
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
>     self.dialect.do_execute(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
>     cursor.execute(statement, parameters)
> sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'dict'
> [SQL: INSERT INTO dbs (uuid, created_on, changed_on, verbose_name, database_name, sqlalchemy_uri, password, cache_timeout, select_as_create_table_as, expose_in_sqllab, allow_run_async, allow_file_upload, allow_ctas, allow_cvas, allow_dml, force_ctas_schema, allow_multi_schema_metadata_fetch, extra, encrypted_extra, impersonate_user, server_cert, is_managed_externally, external_url, created_by_fk, changed_by_fk) VALUES (%(uuid)s, %(created_on)s, %(changed_on)s, %(verbose_name)s, %(database_name)s, %(sqlalchemy_uri)s, %(password)s, %(cache_timeout)s, %(select_as_create_table_as)s, %(expose_in_sqllab)s, %(allow_run_async)s, %(allow_file_upload)s, %(allow_ctas)s, %(allow_cvas)s, %(allow_dml)s, %(force_ctas_schema)s, %(allow_multi_schema_metadata_fetch)s, %(extra)s, %(encrypted_extra)s, %(impersonate_user)s, %(server_cert)s, %(is_managed_externally)s, %(external_url)s, %(created_by_fk)s, %(changed_by_fk)s) RETURNING dbs.id]
> [parameters: {'uuid': UUID('48bc9058-3e74-48d4-85ef-8b94f5044165'), 'created_on': datetime.datetime(2023, 4, 24, 15, 4, 48, 27077), 'changed_on': datetime.datetime(2023, 4, 24, 15, 4, 48, 27082), 'verbose_name': None, 'database_name': 'prestodev2', 'sqlalchemy_uri': "presto://MYDEVUSER:MYDEVPASSWORD@quasar-query-dev.macbank:4039", 'password': <psycopg2.extensions.Binary object at 0x7efd2d8a0ed0>, 'cache_timeout': None, 'select_as_create_table_as': False, 'expose_in_sqllab': True, 'allow_run_async': False, 'allow_file_upload': False, 'allow_ctas': False, 'allow_cvas': True, 'allow_dml': False, 'force_ctas_schema': None, 'allow_multi_schema_metadata_fetch': False, 'extra': {'engine_params': {'connect_args': {'protocol': 'https', 'source': 'superset 2.0.1', 'requests_kwargs': {'verify': '/app/mac-ca-bundle'}}}, 'metadata_params': {}, 'schemas_allowed_for_csv_upload': []}, 'encrypted_extra': None, 'impersonate_user': False, 'server_cert': None, 'is_managed_externally': False, 'external_url': None, 'created_by_fk': None, 'changed_by_fk': None}]
> (Background on this error at: http://sqlalche.me/e/13/f405)
> There was an error when importing the dataset(s), please check the exception traceback in the log
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
>     self.dialect.do_execute(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
>     cursor.execute(statement, parameters)
> psycopg2.ProgrammingError: can't adapt type 'dict'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/app/superset/cli/importexport.py", line 193, in import_datasources
>     ImportDatasetsCommand(contents, overwrite=True).run()
>   File "/app/superset/datasets/commands/importers/dispatcher.py", line 68, in run
>     raise exc
>   File "/app/superset/datasets/commands/importers/dispatcher.py", line 57, in run
>     command.run()
>   File "/app/superset/datasets/commands/importers/v0.py", line 261, in run
>     import_from_dict(db.session, config, sync=self.sync)
>   File "/app/superset/datasets/commands/importers/v0.py", line 225, in import_from_dict
>     session.commit()
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
>     return getattr(self.registry(), name)(*args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1046, in commit
>     self.transaction.commit()
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 504, in commit
>     self._prepare_impl()
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
>     self.session.flush()
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2540, in flush
>     self._flush(objects)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2682, in _flush
>     transaction.rollback(_capture_exception=True)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
>     compat.raise_(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
>     raise exception
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2642, in _flush
>     flush_context.execute()
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
>     rec.execute(self)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
>     persistence.save_obj(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
>     _emit_insert_statements(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1135, in _emit_insert_statements
>     result = cached_connections[connection].execute(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
>     return meth(self, multiparams, params)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
>     return connection._execute_clauseelement(self, multiparams, params)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
>     ret = self._execute_context(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
>     self._handle_dbapi_exception(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
>     util.raise_(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
>     raise exception
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
>     self.dialect.do_execute(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
>     cursor.execute(statement, parameters)
> sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'dict'
> [SQL: INSERT INTO dbs (uuid, created_on, changed_on, verbose_name, database_name, sqlalchemy_uri, password, cache_timeout, select_as_create_table_as, expose_in_sqllab, allow_run_async, allow_file_upload, allow_ctas, allow_cvas, allow_dml, force_ctas_schema, allow_multi_schema_metadata_fetch, extra, encrypted_extra, impersonate_user, server_cert, is_managed_externally, external_url, created_by_fk, changed_by_fk) VALUES (%(uuid)s, %(created_on)s, %(changed_on)s, %(verbose_name)s, %(database_name)s, %(sqlalchemy_uri)s, %(password)s, %(cache_timeout)s, %(select_as_create_table_as)s, %(expose_in_sqllab)s, %(allow_run_async)s, %(allow_file_upload)s, %(allow_ctas)s, %(allow_cvas)s, %(allow_dml)s, %(force_ctas_schema)s, %(allow_multi_schema_metadata_fetch)s, %(extra)s, %(encrypted_extra)s, %(impersonate_user)s, %(server_cert)s, %(is_managed_externally)s, %(external_url)s, %(created_by_fk)s, %(changed_by_fk)s) RETURNING dbs.id]
> [parameters: {'uuid': UUID('48bc9058-3e74-48d4-85ef-8b94f5044165'), 'created_on': datetime.datetime(2023, 4, 24, 15, 4, 48, 27077), 'changed_on': datetime.datetime(2023, 4, 24, 15, 4, 48, 27082), 'verbose_name': None, 'database_name': 'prestodev2', 'sqlalchemy_uri': "presto://MYDEVUSER:MYDEVPASSWORD@quasar-query-dev.macbank:4039", 'password': <psycopg2.extensions.Binary object at 0x7efd2d8a0ed0>, 'cache_timeout': None, 'select_as_create_table_as': False, 'expose_in_sqllab': True, 'allow_run_async': False, 'allow_file_upload': False, 'allow_ctas': False, 'allow_cvas': True, 'allow_dml': False, 'force_ctas_schema': None, 'allow_multi_schema_metadata_fetch': False, 'extra': {'engine_params': {'connect_args': {'protocol': 'https', 'source': 'superset 2.0.1', 'requests_kwargs': {'verify': '/app/mac-ca-bundle'}}}, 'metadata_params': {}, 'schemas_allowed_for_csv_upload': []}, 'encrypted_extra': None, 'impersonate_user': False, 'server_cert': None, 'is_managed_externally': False, 'external_url': None, 'created_by_fk': None, 'changed_by_fk': None}]
> (Background on this error at: http://sqlalche.me/e/13/f405)
> 2023-04-24 15:04:48,032:ERROR:superset.cli.importexport:There was an error when importing the dataset(s), please check the exception traceback in the log
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
>     self.dialect.do_execute(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
>     cursor.execute(statement, parameters)
> psycopg2.ProgrammingError: can't adapt type 'dict'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/app/superset/cli/importexport.py", line 193, in import_datasources
>     ImportDatasetsCommand(contents, overwrite=True).run()
>   File "/app/superset/datasets/commands/importers/dispatcher.py", line 68, in run
>     raise exc
>   File "/app/superset/datasets/commands/importers/dispatcher.py", line 57, in run
>     command.run()
>   File "/app/superset/datasets/commands/importers/v0.py", line 261, in run
>     import_from_dict(db.session, config, sync=self.sync)
>   File "/app/superset/datasets/commands/importers/v0.py", line 225, in import_from_dict
>     session.commit()
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
>     return getattr(self.registry(), name)(*args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1046, in commit
>     self.transaction.commit()
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 504, in commit
>     self._prepare_impl()
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
>     self.session.flush()
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2540, in flush
>     self._flush(objects)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2682, in _flush
>     transaction.rollback(_capture_exception=True)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
>     compat.raise_(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
>     raise exception
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2642, in _flush
>     flush_context.execute()
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
>     rec.execute(self)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
>     persistence.save_obj(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
>     _emit_insert_statements(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1135, in _emit_insert_statements
>     result = cached_connections[connection].execute(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
>     return meth(self, multiparams, params)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
>     return connection._execute_clauseelement(self, multiparams, params)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
>     ret = self._execute_context(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
>     self._handle_dbapi_exception(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
>     util.raise_(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
>     raise exception
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
>     self.dialect.do_execute(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
>     cursor.execute(statement, parameters)
> sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'dict'
> [SQL: INSERT INTO dbs (uuid, created_on, changed_on, verbose_name, database_name, sqlalchemy_uri, password, cache_timeout, select_as_create_table_as, expose_in_sqllab, allow_run_async, allow_file_upload, allow_ctas, allow_cvas, allow_dml, force_ctas_schema, allow_multi_schema_metadata_fetch, extra, encrypted_extra, impersonate_user, server_cert, is_managed_externally, external_url, created_by_fk, changed_by_fk) VALUES (%(uuid)s, %(created_on)s, %(changed_on)s, %(verbose_name)s, %(database_name)s, %(sqlalchemy_uri)s, %(password)s, %(cache_timeout)s, %(select_as_create_table_as)s, %(expose_in_sqllab)s, %(allow_run_async)s, %(allow_file_upload)s, %(allow_ctas)s, %(allow_cvas)s, %(allow_dml)s, %(force_ctas_schema)s, %(allow_multi_schema_metadata_fetch)s, %(extra)s, %(encrypted_extra)s, %(impersonate_user)s, %(server_cert)s, %(is_managed_externally)s, %(external_url)s, %(created_by_fk)s, %(changed_by_fk)s) RETURNING dbs.id]
> [parameters: {'uuid': UUID('48bc9058-3e74-48d4-85ef-8b94f5044165'), 'created_on': datetime.datetime(2023, 4, 24, 15, 4, 48, 27077), 'changed_on': datetime.datetime(2023, 4, 24, 15, 4, 48, 27082), 'verbose_name': None, 'database_name': 'prestodev2', 'sqlalchemy_uri': "presto://MYDEVUSER:MYDEVPASSWORD@quasar-query-dev.macbank:4039", 'password': <psycopg2.extensions.Binary object at 0x7efd2d8a0ed0>, 'cache_timeout': None, 'select_as_create_table_as': False, 'expose_in_sqllab': True, 'allow_run_async': False, 'allow_file_upload': False, 'allow_ctas': False, 'allow_cvas': True, 'allow_dml': False, 'force_ctas_schema': None, 'allow_multi_schema_metadata_fetch': False, 'extra': {'engine_params': {'connect_args': {'protocol': 'https', 'source': 'superset 2.0.1', 'requests_kwargs': {'verify': '/app/mac-ca-bundle'}}}, 'metadata_params': {}, 'schemas_allowed_for_csv_upload': []}, 'encrypted_extra': None, 'impersonate_user': False, 'server_cert': None, 'is_managed_externally': False, 'external_url': None, 'created_by_fk': None, 'changed_by_fk': None}]
> (Background on this error at: http://sqlalche.me/e/13/f405)`
> 

### Environment

(please complete the following information):

- superset version: 2.0.1
- python version: Python 3.8.1 inside official docker image
- node.js version: `node -v` /N/A
- any feature flags active:

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.

Not sure if @betodealmeida sees any action worth taking on this, but I'll leave the ping just in case :)
