### ISSUE TITLE
How to Enable Native filter/Enable emitting filter in Apache superset? In which version this feature is available? Any document for Apache superset?

### ISSUE THREAD

**Issue by SadanaVeereshPatil** [apache/superset#23800]
Currently I'm using version 2.1.0 Below screenshot is the reference. I can't see the enable emitting [filter.](url)

![Screenshot (380)](https://user-images.githubusercontent.com/66872116/234099699-aa58bd31-7336-46de-9968-c20c656f294c.png)

![Screenshot (381)](https://user-images.githubusercontent.com/66872116/234099710-3ab821d7-ed0a-4ea3-879d-b206716c780a.png)

![Screenshot (378)](https://user-images.githubusercontent.com/66872116/234099671-6987520d-79ca-4963-83ad-03d603826d62.png)
 
![Screenshot (379)](https://user-images.githubusercontent.com/66872116/234099694-f1d02c15-2114-4a6b-8bd7-f99f1488fb2a.png)

![Screenshot (377)](https://user-images.githubusercontent.com/66872116/234099640-ccf48f64-da8b-4401-8098-715ebfb70cd6.png)

**Comment by rusackas** [comment]
The "enable emitting crossfilters" checkbox (or similar wording to that, in any case) has been removed... that was a temporary way to turn on the emitting of cross filters back when not many charts supported emitting or receiving them. Now, if you have the `DASHBOARD_CROSS_FILTERS` feature flag, it will work for all charts that support it. No checkbox required!
