### ISSUE TITLE
fail to npm install on superset-frontend at 2.1 version 

### ISSUE THREAD

**Issue by brianMacao** [apache/superset#23803]
backgroud: upgrade project to 2.1.0 version

1. Use Webstorm open folder superset-frontend
2. nvm use 16
3. npm install

### Expected results
E:\python_project\superset\superset-frontend>nvm use 16
Now using node v16.14.2 (64-bit)

E:\python_project\superset\superset-frontend>npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @superset-ui/plugin-chart-pivot-table@2.1.0
npm ERR! Found: @ant-design/icons@5.0.1
npm ERR! node_modules/@ant-design/icons
npm ERR!   @ant-design/icons@"^5.0.1" from the root project
npm ERR!   peer @ant-design/icons@"^5.0.1" from @superset-ui/chart-controls@2.1.0
npm ERR!   packages/superset-ui-chart-controls
npm ERR!     @superset-ui/chart-controls@2.1.0
npm ERR!     node_modules/@superset-ui/chart-controls
npm ERR!       workspace packages\superset-ui-chart-controls from the root project
npm ERR!       26 more (@superset-ui/legacy-plugin-chart-calendar, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @ant-design/icons@"^4.2.2" from @superset-ui/plugin-chart-pivot-table@2.1.0
npm ERR! plugins/plugin-chart-pivot-table
npm ERR!   @superset-ui/plugin-chart-pivot-table@2.1.0
npm ERR!   node_modules/@superset-ui/plugin-chart-pivot-table
npm ERR!     workspace plugins\plugin-chart-pivot-table from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @ant-design/icons@4.8.0
npm ERR! node_modules/@ant-design/icons
npm ERR!   peer @ant-design/icons@"^4.2.2" from @superset-ui/plugin-chart-pivot-table@2.1.0
npm ERR!   plugins/plugin-chart-pivot-table
npm ERR!     @superset-ui/plugin-chart-pivot-table@2.1.0
npm ERR!     node_modules/@superset-ui/plugin-chart-pivot-table
npm ERR!       workspace plugins\plugin-chart-pivot-table from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See E:\nodejs\node_cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     E:\nodejs\node_cache\_logs\2023-04-25T03_31_44_646Z-debug-0.log

### Actual results
i have try to npm --force install, but it's also fail to update module.

### Environment
- os: Windows 10
- superset version: 2.1.0
- python version: 3.10
- node.js version: 16.14.2

thanks for your help and opinion. I don't have much experience on frontend, may be it's not clearly description and plz help me to clarify problem.

**Comment by linxt20** [comment]
i get the same problem +1

**Comment by rusackas** [comment]
Are you both using Windows?

**Comment by linxt20** [comment]
Yes, I use the windows. In the master branch , the frontend is builded successfully , but it get this error in the branch 2.1

**Comment by brianMacao** [comment]
Yes, i have the same problem, i have pull the master branch before and run stable. but after upgrade to 2.1, the backend is stable but frontend is fail to build.
thanks for you remind, i will put the os env into my issue content.

**Comment by eschutho** [comment]
can you try running `npm ci` instead of `npm install`?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and because we don't officially support Windows. We're trying to steer toward a more actionable Issues backlog, but if people are still encountering this in current versions (currently 3.x) we can consider re-opening this issue, opening a new Issue with updated context, or you're welcome to raise a PR to address the problem. Thanks!
