### ISSUE TITLE
Missing groupby option while creating charts

### ISSUE THREAD

**Issue by gobismarttechie** [apache/superset#23827]
Hi, 
I am a recent user of apache superset, While creating the charts **groupby option** is **missing** under **Data** section, i presume because of that only i am not able to access the drill down feature. Inorder to get groupby option, Whether i need to set any Feature flags to true? and also need a walkthrough of drilldown in superset

<img width="897" alt="git issue" src="https://user-images.githubusercontent.com/61461284/234569087-4d5ac861-bf12-4292-b433-e865dc1c54c7.png">

**Comment by khaldoun92** [comment]
Group by is same as "Dimensions", so add the columns that you want to group by in Dimensions
