### ISSUE TITLE
使用SQLAlchemy方式连接不上数据库

### ISSUE THREAD

**Issue by xxy6910** [apache/superset#23837]
docker-compose -f docker-compose-non-dev.yml pull 
docker-compose -f docker-compose-non-dev.yml up
我是通过这种方式安装的superset , 通过SQLAlchemy (postgresql://<UserName>:<DBPassword>@<Database Host>/<Database Name>)的方式连接不上任何数据库，其中测试了postgresql 和 elasticsearch, 但是我通过 dynamic的方式可以连接postgresql

**Comment by armgong** [comment]
try  postgres://    this should be doc typo

**Comment by armgong** [comment]
why not change the password, remove @

**Comment by brianMacao** [comment]
有關密碼中的特殊符號，是可以提前用urlencode方式手動轉義錄入
不過後端有某一個組件解釋轉義時有問題，因此目前最佳的解決方案是密碼不帶特殊符號
更優的解決方案是修復轉義的問題

**Comment by rusackas** [comment]
Agreed with the proposed solution, and closing this issue. If you wish to open a PR to add encoding/decoding features, we can discuss that, but I seem to recall there are reasons we don't do that already. The easiest option is to not use the @ in your password.
