### ISSUE TITLE
LOG_FORMAT not properly respected

### ISSUE THREAD

**Issue by philicious** [apache/superset#23866]
#### How to reproduce the bug

set a `LOG_FORMAT` , e.g. `'{"severity":"%(levelname)s","message":"%(message)s","timestamp":"%(asctime)s"}'` 

### Expected results

all logs respect it

### Actual results

some log messages get logged duplicated, once with and once w/o the format

```
Serving from cache                                                                                                                                                                                 │
{"severity":"INFO","message":"Serving from cache","timestamp":"2023-04-28 15:47:30,865"}                                                                                                           
Cache key: 7003a08fde69f54ab83686bded041a57
{"severity":"INFO","message":"Cache key: 7003a08fde69f54ab83686bded041a57","timestamp":"2023-04-28 15:47:30,877"}

The field `timeseries_limit` is deprecated, please use `series_limit` instead.                                                                                                                     
{"severity":"WARNING","message":"The field `timeseries_limit` is deprecated, please use `series_limit` instead.","timestamp":"2023-04-28 15:48:00,513"}
```

### Environment

- superset version: `2.1`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by SaTae66** [comment]
Can confirm, see my ticket #21646 from September 2022. Anybody know how to get this working properly?

**Comment by philicious** [comment]
ah @SaTae66 , didnt see yours, only searched for `LOG_FORMAT` in open issues

**Comment by philicious** [comment]
duplicate of #21646

**Comment by SaTae66** [comment]
Added a workaround, maybe this helps you too @philicious 
https://github.com/apache/superset/issues/21646#issuecomment-1532535695
