### ISSUE TITLE
fix(ocient): convert GIS data types to geoJSON for the Ocient engine

### ISSUE THREAD

**Issue by jwilliams-ocient** [apache/superset#23907]
The Ocient engine currently emits GIS objects that are incompatible with any of the deck.gl visualization charts. The existing implementation attempts to emit coordinate arrays which are invalid for polygons with holes and a few other edge cases. 

**The Ocient engine should emit geoJSON for _all_ geospatial types.**

Ocient alse has a... unique way of encoding geometry collections that results in Point or LineString objects being encoded as Polygons. Obviously, a geoJSON polygon containing a single point in its exterior ring produces invalid geoJSON,  

See: https://github.com/apache/superset/pull/23814

#### How to reproduce the bug

1. Execute any query emitting a polygon object using SQL Lab
2. Create a dataset from the query in (1)
3. Create any deck.gl chart

### Expected results

N/A

### Actual results

N/A

#### Screenshots

N/A

### Environment

All environments

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
I'd love to support this, but I'm not sure how. Is it something you'd be willing to propose/submit a fix for?

Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. We can re-open this if you think it's needed.
