### ISSUE TITLE
Unable to access dashboard that contains only markdown after updating to version 2.1.0

### ISSUE THREAD

**Issue by Larissa-Rocha** [apache/superset#23906]
I have a dashboard that contains only markdown elements. Since I updated Superset to version 2.1.0, the users of that dashboard started to get the following error:
![image](https://user-images.githubusercontent.com/69212483/235703539-7b3e8135-45b1-4814-9cc8-43cb61cb5eed.png)

I found out that when I add any chart of a dataset that reads from a schema, the user is able to access the dashboard as usual. 

#### How to reproduce the bug

1. Create a dashboard with a markdown element
2. Click to publish the dashboard
3. Ask a non-admin user to open that dashboard and see the error
4. Edit the dashboard to add a chart that reads from any dataset
5. Ask a non-admin user to open that dashboard again and see that works

### Expected results

The user should be able to access the dashboard with only the markdown element

### Actual results
The user is able to access the dashboard after I add a chart

### Environment

(please complete the following information):

- browser type and version: Google Chrome 112.0.5615.165
- superset version: `2.1.0`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
