### ISSUE TITLE
Simple proxy custom SupersetSecurityManager returns error

### ISSUE THREAD

**Issue by giacomochiarella** [apache/superset#23932]
Hi everyone! I have the following custom SupersetSecurityManager:
```
class CustomSsoSecurityManager(SupersetSecurityManager):

    def __init__(self, appbuilder):
        super(CustomSsoSecurityManager, self).__init__(appbuilder)

    def oauth_user_info(self, provider, response=None):
        logging.info("=================> provider: {0}.".format(provider))
        try:
            u = self.appbuilder.sm.oauth_remotes[provider].get('userDetails')
            logging.info(f"=================> {u}")
        except Exception as e:
            logging.info(f"=================> {e}")
        return super().oauth_user_info(provider, response)
```
The final idea is to override the username assigned when a user login using google sso. Right now it is something like google_12342346566367. I would like to set the email. Is that possible?

**Comment by joshuaclausen** [comment]
I know this issue has been closed, but I want to do the same thing (use the email as the username for both Google and Azure), with the goal of allowing someone to login with either Google oauth or Azure oauth.  My assumption is that if I could get both providers to return the same username string, then a user could login with either one.

@giacomochiarella Have you been able to get this working?
