### ISSUE TITLE
Period's filter : Mix different date format

### ISSUE THREAD

**Issue by aehanno** [apache/superset#23938]
When I put those date in the advanced filter 
Start : 01/09/2022
End : 30/09/2022

For a period from September 1st 2022 to September 30th 2022

![image-2023-04-03-17-34-13-451](https://user-images.githubusercontent.com/104373599/236256318-da696de2-50d6-4d40-885e-c4912a83d4c0.png)

But as we can see Superset, save the period like that :
Start :  01/01/2022
End : 30/09/2022

### Expected results

I expect to have that in the preview 
Start : 01/09/2022
End : 30/09/2022

**Comment by rusackas** [comment]
The preview is using ISO dates, to disambiguate the (flexible) inputs. I don't think this is a bug, but happy to keep the discussion alive... we may be revisiting this design sometime soon.

**Comment by aehanno** [comment]
I understand we use ISO dates but wy we don't have the same display between the first composant where we choose are date and the second where we display it

**Comment by rusackas** [comment]
Thos inputs for the Advanced don't require that you type them in any particular format. You can type the dates as you have in the screenshot, or you can type ISO dates, or you can type "last Tuesday" to "next month"
