### ISSUE TITLE
"Object contains forbidden constructor property" error when using specific word

### ISSUE THREAD

**Issue by kapustor** [apache/superset#23953]
If I understand it correctly, if a reserved word `constructor` is used somewhere in returned data, there is a rendering error, both in charts and in the SQL lab. Quite a funny bug if so :)

#### How to reproduce the bug

1. Go to 'SQL Lab'
2. Run a query that returns a string containing `constructor`. It can be a select from a table or even a simple select of a static string: `select 'constructor'`

Or, alternatively, create a table containing `constructor` word in one of the fields, and build a chart from this table that actually shows the `constructor` word in group by, bar name, column name, etc.

### Expected results

The query in SQL Lab will not fail, and the chart will render.

### Actual results

You got error `Object contains forbidden constructor property`

#### Screenshots
![image](https://user-images.githubusercontent.com/25294423/236581914-ea2f0500-163e-4a81-8740-97e2b144e69a.png)
![image](https://user-images.githubusercontent.com/25294423/236582061-30358e37-5f82-4f2b-ae1d-ca26dde00ec3.png)

### Environment

- browser type and version: `Chrome 112.0.5615.138`
- superset version: `2.1.0` - SQL Lab error reproduces in 1.5.3, but charts with `constructor` work in 1.5.3 and don't work in 2.1.0
- python version: `3.8`
- node.js version: `N/A`
- any feature flags active: None

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I have searched for similar issue, but found only this that can be related: https://github.com/apache/superset/issues/22778

**Comment by kapustor** [comment]
Reproduces in 2.1.1.
@sfirke can you please help with this? Looks like a really small issue, but I have no skills to fix it...

**Comment by sfirke** [comment]
I will take a shot at reproducing it this week. It does seem like something that should be a small fix.

**Comment by kapustor** [comment]
Seems like it may be related: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1777

**Comment by kapustor** [comment]
Also can be related: https://github.com/elastic/elasticsearch-js/issues/1408#issuecomment-792520572

**Comment by mshustov** [comment]
The problem seems to have been caused by `json-bigint` library in Superset.
https://github.com/sidorares/json-bigint/blob/3391780b2a3f613bb51536c47e6cddbca31013eb/test/proto-test.js#L38

There is a way to configure them via `protoAction` property https://github.com/sidorares/json-bigint#optionsprotoaction-boolean-default-error-possible-values-error-ignore-preserve
Which is not used by Superset.

**Comment by rusackas** [comment]
Can anyone validate if this is still an issue in Superset 3.x or newer? I assume so. CC @betodealmeida in case there are thoughts about how this is tackled. CC also @SpencerTorres in case you'd like to rebase your PR and see if we can get that across the finish line.

**Comment by SpencerTorres** [comment]
@rusackas Updated to master and fixed merge conflicts, let me know if anything else needs to be done on that PR
