### ISSUE TITLE
Set filters not showing in applied filters list for some charts

### ISSUE THREAD

**Issue by Larissa-Rocha** [apache/superset#23950]
I'm trying to filter a dashboard but when I apply a filter, for some of the charts, the filter is set but does not appear in the applied filters list. The filters work as usual, they just don't appear as "applied filters".
For instance, two of the charts use the same dataset: in the bar chart I can see this behavior and in the big number everything works fine.

#### How to reproduce the bug

I'm not sure how to reproduce that because it seems to happen just for some charts and some filters.

### Expected results

The filters applied appear in the "applied filters" list

### Actual results

The filter I set is in the "unset list"

#### Screenshots
In the first image, I applied "Período" and "Porte" filters but only one of them appear as applied:
![image](https://user-images.githubusercontent.com/69212483/236524409-76d464d1-9e86-4191-b854-60dce6f79f3e.png)
In the second image I tested another filter: 
![image](https://user-images.githubusercontent.com/69212483/236524454-5d3d4716-817d-41ee-8aa4-1df02fc7d7f2.png)
In the third image, I added another filter and the four of them appear as applied:
![image](https://user-images.githubusercontent.com/69212483/236529119-d29268fb-419b-4622-ad74-3bd0f0d121da.png)

### Environment

(please complete the following information):

- browser type and version: Google Chrome 112.0.5615.165
- superset version: 2.1.0
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
