### ISSUE TITLE
Superset app loads infinitely or throws unexpected error occasionally.

### ISSUE THREAD

**Issue by theshivthakur** [apache/superset#23959]
While using the superset app, I sometimes face two issues which might be related:
1. The superset app is stuck on the loading screen until refreshed manually.
2. When a dashboard is opened it gives an unexpected error.

#### How to reproduce the bug

1. Host the latest version of the superset app deployed using docker, in an EC2 instance.
2. Connect the superset with a database and create multiple dashboards.
3. Use it continuously for a while.

### Expected results

The Superset App and the dashboards inside it should load without any error.

### Actual results

1. When the superset app is opened, it sometimes gets stuck on the loading screen. when the console is checked for any error message it shows : 
     <img width="572" alt="Screenshot 2023-05-08 at 3 42 17 AM" src="https://user-images.githubusercontent.com/105853597/236759136-eab5d33c-e79c-44d4-81a6-d333482aaaa7.png">
 
4. While opening a dashboard in the superset app, sometimes an unexpected error is thrown.
`Unexpected error: ChunkLoadError: Loading chunk 8774 failed. (error: https://{base-url}.com:8088/static/assets/91cbc4a8fc60b3fa349c.chunk.js)`

#### Screenshots

1. 
![ScreenRecording](https://user-images.githubusercontent.com/105853597/236758804-df6f0756-f1da-48f4-884e-be95cf8b0d36.gif)

2. 
<img width="1674" alt="Screenshot 2023-05-08 at 3 47 44 AM" src="https://user-images.githubusercontent.com/105853597/236825246-e7e6ceb8-ebd5-458e-bfef-bc120a74fa04.png">

### Environment

(please complete the following information):

- browser type and version: chrome
- superset version: 2.1.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sfirke** [comment]
Try clearing your browser cache?  I was getting that ChunkLoadError after updating from 2.0.1 to 2.1.0 and had to clear my cache, after which I did not see it again.

**Comment by Shisir99** [comment]
@shuagar did you found any resolution?

**Comment by hrisheekeshr-cs** [comment]
Any updates on this?

**Comment by rusackas** [comment]
Hi there, and sorry this has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and since it's been a while since this thread saw any activity, I'll close this as stale. If it is still an issue in Superset 3.x or newer, we can re-open this, or feel free to open a new issue with updated context. Thanks!
