### ISSUE TITLE
Automatic Email of CSV report with Show totals will corrupt the CSV

### ISSUE THREAD

**Issue by steliosph** [apache/superset#23966]
When downloading a CSV report with multiple queries attached to it it will download a zip file with the multiple data.
When setting that Report to be send over the Reporting Email as CSV it will only send a single Email and introduce some weird data on the start of the file and such corrupting the CSV file

![image](https://user-images.githubusercontent.com/3367401/236803252-0b0c48ba-7580-4646-8aac-705bd34777fc.png)

#### How to reproduce the bug

Create simple Table Chart.
Aggregate some data
Enable to Show totals.
Downloading the CSV will download a zip folder at this point.
Sending the email will introduce the extra data in the start of the file

Superset v2.1.0

**Comment by rusackas** [comment]
Closing this (fairly silent/stale) issue in favor of #25647, which I think resolves this one as well.
