### ISSUE TITLE
CSV export Characters Starting with @

### ISSUE THREAD

**Issue by steliosph** [apache/superset#23967]
When downloading any data that are starting with @ superset will automatically add the ' 

![image](https://user-images.githubusercontent.com/3367401/236811862-8168ff44-e8e3-4835-bf4b-b4eca509ac14.png)

This provides an extra complexity in order to process the data.
Would it be ideal to not included the ' and let the users handle the data as they are entered.

Superset v2.1.0

**Comment by tirkarthi** [comment]
Probably an effect of https://github.com/apache/superset/pull/13735 to prevent csv injection.

https://github.com/apache/superset/blob/58e1bcde9e1643cb4f2b3855a586305e75e23f84/superset/utils/csv.py#L33-L64

**Comment by rusackas** [comment]
Is this still happening in 3.x?

**Comment by rusackas** [comment]
Wasn't sure if this was happening in 3.x, and not sure if it's happening in 4.x. Closing this one as stale, but more than happy to reopen it if it's still happening in supported (4.x, currently) versions.
