### ISSUE TITLE
In production superset up, after login, only close and remove button visible, nothing else.

### ISSUE THREAD

**Issue by nagarajmmu** [apache/superset#24014]
After superset login, only close and remove button is visible, nothing else, in log I fond the below exception.

#### How to reproduce the bug

1. Start superset by below command
 _sudo docker-compose -f docker-compose.yml up_
2. After superset is started, login with credentials. 
3. After login, you will see only close and remove button, nothing else.
4. See error in log/console
 Traceback (most recent call last):
superset_app           |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
superset_app           |     rv = self.dispatch_request()
superset_app           |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
superset_app           |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
superset_app           |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 509, in <lambda>
superset_app           |     view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
superset_app           |   File "/usr/local/lib/python3.8/site-packages/flask/scaffold.py", line 322, in send_static_file
superset_app           |     return send_from_directory(
superset_app           |   File "/usr/local/lib/python3.8/site-packages/flask/helpers.py", line 676, in send_from_directory
superset_app           |     return werkzeug.utils.send_from_directory(  # type: ignore
superset_app           |   File "/usr/local/lib/python3.8/site-packages/werkzeug/utils.py", line 586, in send_from_directory
superset_app           |     raise NotFound()
superset_app           | werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

what actually happens.
It should show welcome page with dashboard and menu.
### Environment

Superset 2.1
Python 3.8
OS Ubuntu 18

Please help me how can I resolve this issue.

**Comment by rusackas** [comment]
You might need to use the non-dev docker compose file. The dev one points at latest master, so isn't always reliable. Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!

**Comment by kerem-coemert** [comment]
This issue still remains for me.

I use `docker-compose-non-dev.yml`. Once it completes, I create a new user via: `docker exec -it superset_app superset fab create-admin`. It works when I first login and I can see all the example graphs like the COVID-19 graph etc.

But once I reopen the same frontend URL either from the same browser or through the private window, I get the exact same issue in my next login.

I always have to run:

```
docker compose -f docker/docker-compose.yml down -v --remove-orphans
docker image ls | grep superset | awk '{print $3}' | xargs docker rmi -f
```

and create the user again, before I can get the frontend working again. So clearly some resource gets corrupted in that second login.

Looking forward to any help you could provide in this direction.
