### ISSUE TITLE
sql_lab.py uses PyArrow API that was removed in pyarrow 12.0.0

### ISSUE THREAD

**Issue by wjones127** [apache/superset#24030]
This:

https://github.com/apache/superset/blob/7a55625243e4d405ce27d72ee869cb8e8c785f6b/superset/sql_lab.py#L362-L367

Should be replaced with 

```python
sink = pa.BufferOutputStream()
with pa.ipc.new_stream(sink, result_set.pa_table.schema) as writer:
    writer.write_table(result_set.pa_table)

data = sink.getvalue().to_pybytes()
```

Will likely need to update the deserialization code as well, where ever that is.

Issue reported on Arrow mailing list here: https://lists.apache.org/thread/93sj6hzgnzz3j0gt5sw0l8pxg6b546ho

**Comment by wjones127** [comment]
@robdiciuccio is looks like you implemented this, so you might be in the best position to update this. (I haven't yet worked on superset myself.) I'm happy to provide more guidance on the use of PyArrow if needed, though.

**Comment by EugeneTorap** [comment]
Hi @wjones127! Thanks for this issue!
@sebastianliebscher Can we prepare a PR for upgrading pyarrow to 12.0.0 and replace that sql lab code?
