### ISSUE TITLE
Need RBAC consultation

### ISSUE THREAD

**Issue by bukreevai** [apache/superset#24057]
Can someone help with RBAC on Apache Superset: what grants are needed for the Charts tab to display user charts I tried everything, nothing is given to the interface
/chart/list/ page

**Comment by mdeshmu** [comment]
DASHBOARD_RBAC is only for dashboards

To view charts, Minimum Gamma role + permissions to dataset on which chart is created, is required

**Comment by bukreevai** [comment]
I need create my role. Added  grants into this role (for Charts) : 
`can read on Chart`,
`can write on Chart`,
`can export on Chart`

and I don't see anything on the Charts page

**Comment by bukreevai** [comment]
Charts page
![image](https://github.com/apache/superset/assets/18184117/95f4495f-75e0-4d3e-b525-ea38c264039c)
charts in Dash
![image](https://github.com/apache/superset/assets/18184117/7edac112-1ee1-46c9-b7a5-44114acade3d)

**Comment by mdeshmu** [comment]
try `menu access on Charts`

**Comment by mdeshmu** [comment]
more permissions in https://github.com/apache/superset/blob/master/RESOURCES/STANDARD_ROLES.md

**Comment by bukreevai** [comment]
> try `menu access on Charts`

I have this grant too.

**Comment by bukreevai** [comment]
But if I try do Explore chart from dashboards 
![image](https://github.com/apache/superset/assets/18184117/30687816-a441-4bec-a65d-a7b82e28de43)
Query on - 
`/api/v1/explore/form_data?tab_id=2`

I get 403 response

**Comment by bukreevai** [comment]
Version 1.5.1

**Comment by bukreevai** [comment]
> more permissions in https://github.com/apache/superset/blob/master/RESOURCES/STANDARD_ROLES.md

I added all the permissions from the Alpha role, but the problem persists

**Comment by bukreevai** [comment]
It was problem with grants to datasets. Issue can be closet.
