### ISSUE TITLE
Replace deprecated `set-output` command with environment file

### ISSUE THREAD

**Issue by jongwooo** [apache/superset#24061]
**Describe the issue**
In workflow, `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

**Comment by rusackas** [comment]
@john-bodley @dpgaspar I feel like I've indeed seen these warnings, so this still seems relevant. 

I'm hoping @jongwooo can rebase the PR, so we can review and merge if it's still warranted.
