### ISSUE TITLE
Histogram bars aren't always stacking on dimension

### ISSUE THREAD

**Issue by atpage** [apache/superset#24064]
I have a dataset like:

```
 category_a | category_b | value
------------+------------+--------
 x          |  a         |  6.988
 x          |  b         |  6.994
 y          |  b         |  6.995
 z          |  b         |  6.996
 z          |  a         |  6.997
 z          |  c         |  7.001
...
```

I generated a Histogram Chart of `value` using `category_b` as a Dimension.  Here is the result, where the categories (a, b, c) are represented in 3 different colors:

![image](https://github.com/apache/superset/assets/4260357/e5fd6bdc-a86b-4074-b74b-01f0a19a4487)

The problem is, bars are sometimes hidden/overlapping, not stacked.  This can be detected when mousing over some of the bars where data appears to be missing.  For example:

![image](https://github.com/apache/superset/assets/4260357/dc8b6df1-b830-4018-b62f-9aa43c58cc20)

The opacity changes on mouseover, to reveal hidden bars behind the first one.  It happens for at least 3 boxes in this example, not just the final one in the screenshot.

#### How to reproduce the bug

The process was described above.  I can provide a CSV of my actual data if it helps.

### Expected results

No bars are hidden, they are all stacked vertically when using Dimensions.

### Actual results

Some bars are randomly hidden.

### Environment

- browser type and version: tested in Firefox 113 and Chrome 113
- superset version: 2.1.0
- python version: (docker)
- node.js version: (docker)
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Yep... this still seems to be an issue in 3.x. We're open to PRs here if you're up for it, or help building a new histogram chart built on ECharts and using the newer chart data API.
