### ISSUE TITLE
I can't create anything on the site

### ISSUE THREAD

**Issue by FarmaczevT** [apache/superset#24078]
When any actions are performed, the page is updated and displays errors
An error occurred while fetching dashboard info: Forbidden
An error occurred while fetching chart info: Forbidden
There was an issue fetching your saved queries: [object Response]
There was an issue fetching your dashboards: [object Response]
There was an issue fetching your chart: [object Response]
There was an issue fetching your recent activity: Forbidden
Access is Denied

**Comment by christianxiaobai** [comment]
I have the same situation, please ask you to solve it

**Comment by khanakia** [comment]
I just installed superset on docket and having same errors after i login

**Comment by abrahamlsirleaf4life-del** [comment]
Can anyone help me, please, cause I am finding it difficult to with these errors below keep coming:
An error occurred while fetching dashboard info: Forbidden
An error occurred while fetching chart info: Forbidden
There was an issue fetching your saved queries: [object Response]
There was an issue fetching your dashboards: [object Response]
There was an issue fetching your chart: [object Response]
There was an issue fetching your recent activity: Forbidden
Access is Denied

**Comment by abrahamlsirleaf4life-del** [comment]
> I just installed superset on docket and having same errors after i login

I am facing the same problem...Can you help me resolve this problem

**Comment by abrahamlsirleaf4life-del** [comment]
> I have the same situation, please ask you to solve it

I am facing the same problem...Can you help me resolve this problem
