### ISSUE TITLE
Adding AS `Cost` to jinja code gets overridden

### ISSUE THREAD

**Issue by jonathan-incentiveq** [apache/superset#24108]
When adding AS `Cost` to jinja, it still add's AS `original label`. I am not sure if this is a bug or just how the code is written. I am not good with python or i would handle this. Or if someone can point me in the direction of where the AS is constructed, I could take a crack at it.

**Comment by rusackas** [comment]
I feel like this was already fixed, but it is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.  Or we can re-open this with some updated context. Thanks!
