### ISSUE TITLE
Multiple columns in Big Number Chart

### ISSUE THREAD

**Issue by nandanalluri** [apache/superset#24103]
Can we add multiple columns to big number chart ?

<img width="1125" alt="Screen Shot 2023-05-17 at 1 56 08 PM" src="https://github.com/apache/superset/assets/121057993/b8bbdf05-b39e-4d02-8c08-6fd1fad6b37a">

Thanks

**Comment by rusackas** [comment]
Nope, you'd want to add multiple Big Number charts.
Or, if you want icons/emoji, you could probably get clever with the Handlebars plugin (though it's admittedly a bit beta-esque)
