### ISSUE TITLE
how to use filter When superset + shillelagh to get data from api

### ISSUE THREAD

**Issue by j491424570** [apache/superset#24133]
I installed shillelagh on superset to get data from api
I am running weatherapi demo and datasettes demo which works fine
but filter function seemed not working. How to make superset filter working?
Any suggestions are welcome

SQL on superset:
SELECT * FROM "https://san-francisco.datasettes.com/sf-trees/Street_Tree_List" LIMIT 5
![filter1](https://github.com/apache/superset/assets/13111464/c11f0bc2-1291-44ab-a092-dc22b34d3556)
![filter not working](https://github.com/apache/superset/assets/13111464/c2ee1c8f-423c-4a07-b668-7000b306dfd6)

**Comment by sanjeev-99** [comment]
Did you press UPDATE CHART button at the bottom? The chart says "Your chart is not up to date" (means it has not been refreshed after you changed your settings)

**Comment by j491424570** [comment]
> Did you press UPDATE CHART button at the bottom? The chart says "Your chart is not up to date" (means it has not been refreshed after you changed your settings)

yes. i did clicked the update chart button. then the "Your chart is not up to date" tip show
