### ISSUE TITLE
`/api/v1/dataset/{pk}/refresh` overrides `columns.filterable` and `columns.groupby` to `true`

### ISSUE THREAD

**Issue by one-data-cookie** [apache/superset#24136]
API method `/api/v1/dataset/{pk}/refresh` overrides `columns.groupby` and `columns.filterable` to `true` regardless of their settings. Surprisingly, this doesn't happen when the same is triggered from UI.

#### How to reproduce the bug

1. Create/Use a dataset with columns that have `Is filterable` and/or `Is dimension` unticked
2. Sync columns from source (to see it working from UI)
3. Call `/api/v1/dataset/{pk}/refresh` on given dataset (to see it _not_ working via API)

### Expected results
Columns are kept untouched (provided there is no change to the underlying query/data, ofc, no matter from where the refresh is triggered.

### Actual results
`filterable`/`Is filterable` and `groupby`/`Is dimension` are changed to `true`

#### Screenshots

Before anything.
![image](https://github.com/apache/superset/assets/57877739/3b3b8f44-4375-45f8-9871-7ba4dd5b0eb4)

After refreshing from UI.
![image](https://github.com/apache/superset/assets/57877739/1130dcec-ac64-4fb5-bee9-af182e4e322c)

After refreshing via API.
![image](https://github.com/apache/superset/assets/57877739/7fb2b890-8786-4262-bdc6-15656d396b18)

### Environment
- superset version: `2.1.0`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by a-othman** [comment]
Hello @one-data-cookie , is this end point "/api/v1/dataset/{pk}/refresh" working with you, cause I can't get it to work with me. it gives me  "405 Error: METHOD NOT ALLOWED". I am using a PUT method as per the documentation?

**Comment by one-data-cookie** [comment]
@a-othman As far as I know `PUT` requests are only supported if CSRF tokens are disabled in Superset (`WTF_CSRF_ENABLED=False`).

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case we can try. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
