### ISSUE TITLE
create database in superset through ssh tunnel using a .pam file

### ISSUE THREAD

**Issue by ZeidLennart** [apache/superset#24150]
## Hi everyone
I have an issue with my superset project. I'm running a AWS MySQL server and It's secured through a SSH tunnel. This tunnel is using a .pam keyfile. I found the option to set  "SSH_TUNNELING": True, in the config.py file but it didn't changed anything in the UI of superset. Is this even the right way to do it or is there a better one? Until now I always opened up a separate port and connected the SSH tunnel to that port and then created a mySQL database connection to my local port. But now I have to share the project with someone and want to make it more easy :) Thanks in advance

**Comment by metropolis-ameer** [comment]
Did you enable it in the feature flag?  Are you using 2.1.0?

<img width="243" alt="image" src="https://github.com/apache/superset/assets/62971911/e4f24097-63fa-4a24-a5eb-eabaf1594bdf">

**Comment by ZeidLennart** [comment]
In the config.py file I sited the default_feature flag for this to true but I can't find the superset_config.py file where this code is supposed to be in. I'm using the newest version. Where can I find this file / how can I create it do you know that?

**Comment by ZeidLennart** [comment]
Okay I found that file but still it didn't change anything in the frontend

**Comment by metropolis-ameer** [comment]
I have that setting in my `superset_config.py` and I have the `superset_config.py` baked into my docker image in the `/app/pythonpath/` directory.  Aside from that, perhaps one of the contributors will share more robust knowledge on this.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
