### ISSUE TITLE
Fatal error when fetching data from cache using a Guest Token with RLS

### ISSUE THREAD

**Issue by OskarSorensen** [apache/superset#24171]
#### How to reproduce the bug

With GLOBAL_ASYNC_QUERIES enabled view an embedded dashboard with the `superset-ui/embedded-sdk` NPM package using a guest token. When Superset has finished processing the queries and notifies the frontend to go fetch the specific cache key (`api/v1/chart/data/{cache_key}`) a fatal error and a HTTP 422 Unprocessable Entity is returned instead. After some experimentation I've found out that this only happens if a RLS clause has been added to the quest token. It seems like the presence of an RLS clause causes this - even if the clause is simply `1 = 1`. If a guest token without RLS is used then it works as expected.

### Expected results

That the request with the guest token containing an RLS clause can successfully fetch data from `api/v1/chart/data/{cache_key}`

### Actual results

Fatal error and HTTP 422 Unprocessable Entity

### Environment

- browser type and version: `Chrome 113.0.5672.127`
- superset version: `2.1.0`
- python version: (docker)
- node.js version: (docker)
- any feature flags active: `ENABLE_TEMPLATE_PROCESSING, DASHBOARD_RBAC, DASHBOARD_CROSS_FILTERS, EMBEDDED_SUPERSET, DRILL_TO_DETAIL, DASHBOARD_NATIVE_FILTERS, HORIZONTAL_FILTER_BAR, GLOBAL_ASYNC_QUERIES, GLOBAL_ASYNC_QUERIES_TRANSPORT = "polling"`

**Comment by OskarSorensen** [comment]
and I have just confirmed that this is an issue that is experienced by others than just me https://apache-superset.slack.com/archives/C01EP56QGTS/p1676555390391469

**Comment by Ben-Vencill** [comment]
I have replicated these steps and get the following result when `GLOBAL_ASYNC_QUERIES` is enabled:

 - `api/v1/chart/data/{cache_key}` returns 422 Unprocessable Entity
 - `/superset/explore_json/data/{cache_key}` returns 400 Bad Request
 - `api/v1/chart/{chart_id}` returns 404 Not Found
 
 I see none of these errors when making the same calls on the deployment when `GLOBAL_ASYNC_QUERIES` feature flag is not enabled.

**Comment by rusackas** [comment]
The related PR seems stuck, but hopefully we can get that picked back up. If anyone else wants to adopt it, that's fine too. Otherwise we may close this issue as stale at some point.

**Comment by rusackas** [comment]
Seems this was resolved in 3.1. Closing!
