### ISSUE TITLE
Could not locate a Flask application error in Windows11.

### ISSUE THREAD

**Issue by gangilseo** [apache/superset#24187]
### Expected results

Test and initialize superset in Windows environment

### Actual results

I installed apache-superset in Windows11 with python venv.
But I have still error FLASK_APP cannot locate error. Result is below.
set FLASK_APP=superset is not working. Of course, not any command is not work because of flask error.
How can I solve this?

#### Screenshots

![image](https://github.com/apache/superset/assets/77883846/b825a4b6-c433-4eb9-a508-f539760aa48d)

### Environment

- Python 3.10.9
- Flask 2.1.3
- Werkzeug 2.3.4

**Comment by mdeshmu** [comment]
Superset is not officially supported on Windows, unfortunately. Refer "Windows" sections for other options

https://superset.apache.org/docs/installation/installing-superset-using-docker-compose#1-install-a-docker-engine-and-docker-compose

**Comment by sfirke** [comment]
If you search your exact error message + "Superset" you'll get some hits, like https://stackoverflow.com/questions/72140507/issue-in-running-apache-superset.  Maybe something will work.  Like @mdeshmu said it's unsupported and IMO a risky path to take.  You could try running it in Windows using Docker with WSL2, though I have had a lot of headaches getting that combination to work consistently.

**Comment by rusackas** [comment]
Closing this for the above reasons (Windows not being supported, and many resources being out in the wild). You can also search [Superset Slack](http://bit.ly/join-superset-slack) for threads on the topic, or even see about recruiting for a #windows channel to see if it can be made stable through coordinated efforts. Thanks!
