### ISSUE TITLE
Dashboard embedded issue in standaloan mode with 2.1.0

### ISSUE THREAD

**Issue by santoshmallah** [apache/superset#24199]
I have integrated my angular application and superset with keycloak for SSO
I am trying to embed a superset dashboard in my angular application using iframe
```
<iframe
  class="supersetIframe"
  seamless
  frameBorder="0"
  scrolling="yes"
  src="https://localhost:7012/superset/dashboard/14/?standalone=2"
  >
</iframe>
```
on the first load it gives error 

![image](https://github.com/apache/superset/assets/51262721/e38fb6bd-fcb3-4773-a67e-ee236c99d075)

![image](https://github.com/apache/superset/assets/51262721/621c0a2e-27d1-4bad-bc3e-5800a1a627b3)

![image](https://github.com/apache/superset/assets/51262721/13980133-8264-4d5b-803f-696702815ef2)

I have enable 
```json
FEATURE_FLAGS = {
        "ALERT_REPORTS": True,
        'EMBEDDABLE_CHARTS':True,
        'EMBEDDED_SUPERSET':True,
        'ENABLE_TEMPLATE_PROCESSING': True
        }
```
Keyclok Setupe in superset_config.py
```python
from flask_appbuilder.security.manager import AUTH_OID
from security import OIDCSecurityManager
AUTH_TYPE = AUTH_OID
OIDC_CLIENT_SECRETS = '/app/docker/pythonpath_dev/client_secret.json'
OIDC_ID_TOKEN_COOKIE_SECURE = False
OIDC_REQUIRE_VERIFIED_EMAIL = False
CUSTOM_SECURITY_MANAGER = OIDCSecurityManager
OIDC_CLOCK_SKEW = 560
OIDC_VALID_ISSUERS = 'https://klayx:8000/auth/realms/klay'
AUTH_USER_REGISTRATION = True
AUTH_USER_REGISTRATION_ROLE = 'Gamma'
#AUTH_USER_REGISTRATION_ROLE = 'Public'
#AUTH_ROLE_ADMIN = 'Admin'
#PUBLIC_ROLE_LIKE = 'Gamma'
OIDC_SCOPES = ['openid', 'email', 'profile', 'read']


SUPERSET_WORKERS=2
SUPERSET_WEBSERVER_TIMEOUT=120

ENABLE_CORS = True
CORS_OPTIONS = {
  'supports_credentials': True,
  'allow_headers': ['*'],
  'resources':['*'],
  'origins': ['*','https://klayx:8000', 'https://klayx:1003']
}
```
### Public role
![image](https://github.com/apache/superset/assets/51262721/e722584b-d100-47c2-8080-f1bacc4df741)

It does not load the dashboard on the first load but after reloading the page it's working.

### Not working on 2.1.0 why ??

- browser type and version:
- superset version: `2.1.0`
- python version: `3.9`
- node.js version: `16.14.2`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mabhub** [comment]
up?

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
