### ISSUE TITLE
Default Secret Key although i set a new/custom one

### ISSUE THREAD

**Issue by ASchmidtGit** [apache/superset#24201]
Hey, we want to update from 1.5.0 to 2.1.0 and did not change our secret key in older deployments.

I generated a key with "openssl rand -base64 42" and received the previous key with:
```
superset shell
from flask import current_app; print(current_app.config["SECRET_KEY"])
```

Then i changed my superset_config.py to include the following:

PREVIOUS_SECRET_KEY = "CHANGE_ME_TO_A_COMPLEX_RANDOM_SECRET"   
SECRET_KEY = "MYGENERATEDKEY"

and mounted my Pythonpath: "/app/pythonpath:app/docker/pythonpath_dev" which includes the superset_config.py.

But i still get the following error:
```
--------------------------------------------------------------------------------
                                    WARNING
--------------------------------------------------------------------------------
A Default SECRET_KEY was detected, please use superset_config.py to override it.
Use a strong complex alphanumeric string and use a tool to help you generate 
a sufficiently random sequence, ex: openssl rand -base64 42
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Refusing to start due to insecure SECRET_KEY
[2023-05-24 15:05:11 +0000] [215] [INFO] Worker exiting (pid: 215)
Loaded your LOCAL configuration at [/app/pythonpath/superset_config.py]
[2023-05-24 15:05:11 +0000] [222] [INFO] Booting worker with pid: 222
```

Using "superset re-encrypt-secrets" does not work either and just returns the same warning. (i ran this command in the Superset webb app container)

Did i miss something?

**Comment by houssam-13** [comment]
i got the same problem but i'm not using docker

**Comment by ASchmidtGit** [comment]
The fresh install on test environsment worked but now i need to update prod. And here same error, i added the previous (default key) and a new one, but superset wont start up since only the default key gets recognized

**Comment by kornatskyi** [comment]
So it seems like `SECRET_KEY` actually gets resigned in `config.py` on line `183` to `SUPERSET_SECRET_KEY`, but it `SUPERSET_SECRET_KEY` is empty or None then `SECRET_KEY` is set to `CHANGE_ME_SECRET_KEY` and then this Warning appears. 
I set `SUPERSET_SECRET_KEY` environment variable
```bash
export SUPERSET_SECRET_KEY="some_random_base64_string"
```
after that it worked.
I believe the Warning message can be improved

**Comment by rusackas** [comment]
Warning message improvement PRs are more than welcome. Otherwise, it seems like this is all set. Closing. Thanks!
