### ISSUE TITLE
dashboards table missing certified_by and certification_details columns 

### ISSUE THREAD

**Issue by ahaffar** [apache/superset#24236]
#### How to reproduce the bug

1. Go to 'dashboards'

2. See the error `https://sqlalche.me/e/14/f405`
```2023-05-29 04:15:37,863:ERROR:superset.views.base:(psycopg2.errors.UndefinedColumn) column dashboards.certified_by does not exist ```

--

<br class="Apple-interchange-newline">

### Expected results

Dashboards should be open and able to create a new dashboard

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `2.1.0`
- python version: `Python 3.8.16`
- node.js version: `node -v`
- any feature flags active:  `FEATURE_FLAGS = {"ALERT_REPORTS": True,  "EMBEDDED_SUPERSET": True, "EMBEDDABLE_CHARTS": True, "ENABLE_EXPLORE_DRAG_AND_DROP": True}`

the dashboards table missing 2 columns `certified_by, certification_details`
```sh
superset=> SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'dashboards';
      column_name      |          data_type
-----------------------+-----------------------------
 id                    | integer
 created_by_fk         | integer
 changed_by_fk         | integer
 published             | boolean
 uuid                  | uuid
 is_managed_externally | boolean
 created_on            | timestamp without time zone
 changed_on            | timestamp without time zone
 external_url          | text
 dashboard_title       | character varying
 position_json         | text
 css                   | text
 description           | text
 slug                  | character varying
 json_metadata         | text
(15 rows)```

### Additional context

can i table a pgdump from a fresh DB and create the missing two columns manually ?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
