### ISSUE TITLE
docker compose change db to mysql error

### ISSUE THREAD

**Issue by qinlz-1** [apache/superset#24243]
when i change docker compose db to mysql
  db:
    env_file: docker/.env-non-dev
    #image: postgres:14
    image: mysql:5.7
    container_name: superset_db
    restart: unless-stopped
    volumes:
      - db_home:/var/lib/mysql
      #- db_home:/var/lib/postgresql/data

docker-compose -f docker-compose-non-dev.yml up

superset_worker   :ERROR:flask_appbuilder.security.sqla.manager:DB Creation and initialization failed: (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to MySQL server on 'db' (115)")

superset_worker_beat  :ERROR:flask_appbuilder.security.sqla.manager:DB Creation and initialization failed: (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to MySQL server on 'db' (115)")

superset_init  :ERROR:flask_appbuilder.security.sqla.manager:DB Creation and initialization failed: (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to MySQL server on 'db' (115)")

**Comment by sebastianliebscher** [comment]
You also need to change your new database settings in `docker/.env-non-dev`:

```ini
# database engine specific environment variables
# change the below if you prefer another database engine
DATABASE_PORT=5432
DATABASE_DIALECT=postgresql
POSTGRES_DB=superset
POSTGRES_USER=superset
POSTGRES_PASSWORD=superset
#MYSQL_DATABASE=superset
#MYSQL_USER=superset
#MYSQL_PASSWORD=superset
#MYSQL_RANDOM_ROOT_PASSWORD=yes
```

**Comment by qinlz-1** [comment]
@sebastianliebscher 
I've already modified it
#DATABASE_PORT=5432
DATABASE_PORT=3306
#DATABASE_DIALECT=postgresql
DATABASE_DIALECT=mysql
#POSTGRES_DB=superset
#POSTGRES_USER=superset
#POSTGRES_PASSWORD=superset
MYSQL_DATABASE=superset
MYSQL_USER=superset
MYSQL_PASSWORD=superset
MYSQL_RANDOM_ROOT_PASSWORD=yes

**Comment by sebastianliebscher** [comment]
This does not seem to be a bug to me. For questions regarding the use of Superset please use the [Discussions](https://github.com/apache/superset/discussions) or join the [Superset Slack](http://bit.ly/join-superset-slack). There you can share more information like your full docker logs in order to debug your issues effectively.

**Comment by puneetjindal** [comment]
I am trying to connect with mysql 5.7 which is hosted on GCP cloud sql.  I made some updates in docker-compose.yml for local run. I am running this superset installation on Google cloud VM.

  ```
db:
    env_file: docker/.env
    image: mysql:5.7
    container_name: superset_db
    restart: unless-stopped
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - db_home:/var/lib/mysql
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
```

Am i configuring it correctly? Any detailed reference documentation

**Comment by rusackas** [comment]
Agreed that this is not a bug, but more of a configuration help topic. Since it's been silent for nearly six months, I recommend anyone interested in this topic utilize Github Discussions or [Slack](http://bit.ly/join-superset-slack)
