### ISSUE TITLE
Add New Driver for Amazon Timestream

### ISSUE THREAD

**Issue by Hugh-Guan** [apache/superset#24244]
### Installation mode
Superset Version: 2.0.0
Installation Mode: docker compose
### Problem Description
Superset 2.0.0 does not seem to have the driver support of Amazon Timestream. 
I have consulted the Superset documentation on Add New Database, and it seems that it is not easy to implement it with my python knowledge.
[https://superset.apache.org/docs/databases/docker-add-drivers](url)
[https://preset.io/blog/building-database-connector/](url)
I noticed that there was a discussion about a Driver for Amazon Timestream, but it didn't seem to come to anything.
#12544 
The PYPI search found that SqlAlchemy does not appear to have a driver for Amazon Timestream.
[https://pypi.org/search/?q=timestream](url)
In Amazon Timestream documentation, boto3 and awswrangler are supported for joining and querying.
[https://docs.aws.amazon.com/zh_cn/timestream/latest/developerguide/accessing.html](url)
[https://boto3.amazonaws.com/v1/documentation/api/latest/index.html](url)
### Describe the solution you'd like
Support Amazon Timestream Driver

**Comment by sfirke** [comment]
Per the last comment in the thread you linked (thanks for including that!), this would be better suited as a feature request in Github Discussions, since it is not a bug report.

**Comment by rusackas** [comment]
Agreed. If you're able to open a PR for this, that would be fantastic. If you'd like to continue seeking community support of this feature request, please open a new [Ideas thread](https://github.com/apache/superset/discussions/categories/ideas) in our [Github Discussions](https://github.com/apache/superset/discussions) area. Thank you!
