### ISSUE TITLE
`/api/v1/dataset` returns empty "owners" array for each dataset

### ISSUE THREAD

**Issue by alibertz** [apache/superset#24257]
#### How to reproduce the bug
1. Open native filter/filter bar within a dashboard
2. Open "Add and edit filters" dialog
3. Click "DATASET" dropdown (with browser network tab open)
4. Open/view API call response that was just made after clicking the DATASET dropdown
5. Open "results" that is an array of Dataset objects that populate DATASETS dropdown options
<img width="1438" alt="Screenshot 2023-05-31 at 9 45 27 AM" src="https://github.com/apache/superset/assets/28662778/f680c8b9-2ae6-4cb1-8576-3bfac1bbe53a">
6. See that "owners" array is empty
7. Compare with `/api/v1/charts` API response that has non-empty "owners" field

### Expected results
Each dataset object in "results" field of `/api/v1/dataset` API response payload should have a non empty "owners" field with relevant owner information so the DATASET dropdown can be filtered to by relevant owners.

### Actual results
"owners" data missing from `/api/v1/dataset` API response payload

#### Screenshots
Another screenshot of 'owners' info missing from `/api/v1/dataset` API response payload
![image](https://github.com/apache/superset/assets/28662778/5c46b220-22b2-4d82-8888-a768d6c8b8b1)

Proof that it should be included as it is listed in the schema:
![image (1)](https://github.com/apache/superset/assets/28662778/13d23e36-2ee8-4453-b429-1b4015c9bc1b)
![image (2)](https://github.com/apache/superset/assets/28662778/d50e37f3-73e3-447f-b227-a0a34afd3459)

### Checklist
- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

Please let me know if there's anything additional I can provide. Thank you!

**Comment by alibertz** [comment]
@hughhhh @rusackas Any updates on this issue?

**Comment by alibertz** [comment]
@hughhhh @rusackas Any updates on this issue?

**Comment by rusackas** [comment]
I'm unable to repro this in current Superset (3.0 or newer) - I see the owners in the API response when loading the dashboard. I'm also not sure why it would be needed when creating a filter, but in any case, I see it!
