### ISSUE TITLE
Embedded Superset Dashboard: Access Denied Error for Bar and Timeseries Charts

### ISSUE THREAD

**Issue by fuadchonora** [apache/superset#24259]
When using the [@superset-ui/embedded-sdk](https://www.npmjs.com/package/@superset-ui/embedded-sdk) library (version 0.1.0-alpha.9) to embed a Superset dashboard into an application, bar chart and time-series chart types fail to load. Instead, the error message "Access is Denied" is displayed. This issue is observed consistently across all bar chart and time-series chart types.

#### How to reproduce the bug

1. Create an application that uses the @superset-ui/embedded-sdk library to embed a Superset dashboard.
2. Load a Superset dashboard containing bar charts or time-series chart types.
3. Observe that the charts fail to load and display the "Access is Denied" error message.
4. Check the API responses for the following endpoint:
    - `/api/v1/chart/:id` (returns 404 status with the message "Not found")

### Expected results

Bar chart and time-series chart types load successfully when using the @superset-ui/embedded-sdk library to embed a Superset dashboard into an application. The charts should display the expected data without any "Access is Denied" errors. 

### Actual results

Bar chart and time-series chart types fail to load when using the @superset-ui/embedded-sdk library to embed a Superset dashboard into an application. Instead of the expected charts, an "Access is Denied" error message is displayed.

#### Screenshots
![Screenshot 2023-06-01 at 10 05 31 AM](https://github.com/apache/superset/assets/49869778/d9d68909-672c-4a5c-8262-6656917aaf72)
![Screenshot 2023-06-01 at 10 15 49 AM](https://github.com/apache/superset/assets/49869778/e2631d78-421f-4bea-a681-2fcfb9173b2b)
In the above screenshot, the last two APIs (63, 62) are the bar charts (uses `/api/v1/chart/:id` API). There are two pie charts that loaded successfully (uses `/api/v1/chart/data?form_data=...` API).

### Environment

- Apache Superset version: 1.5.2
- @superset-ui/embedded-sdk version: 0.1.0-alpha.9
- Browser: Google Chrome Version 113.0.5672.126

**Comment by Anshu1294** [comment]
experiencing the same issue. (I'm on 1.5.1), we are seeing a 400 CSRF token issue, for the two 'data' POST Requests, 404 for the two 'chart' requests as shown here with id 62/63. Although if i make the same request from the swagger UI, it works, but it shows up as 404 when making request from embedded sdk. Been stuck on this for the last 2 days

**Comment by Anshu1294** [comment]
https://github.com/apache/superset/issues/22715

As seen from this thread, it would seem that in my case the exempt list is not being honoured. not sure what it is in your case, but i recommend using "GUEST_ROLE_NAME" = "GAMMA" and seeing if that would fix the 403 for you

**Comment by Anshu1294** [comment]
figured out the 404 issue, it's because the dashboard was not published, you have to embed a publish dashboard or publish your dashboard that is in draft. Best of luck. I'm still stuck at the 400 CSRF Token issue

**Comment by huamichaelchen** [comment]
You are spot on the published dashboard part as well as the necessary role permission in Supsert. Regarding the CSRF token, that needs to be invoked through Superset API. 

Wrote a guide on it, hopefully, it helps someone 😄 Choose your preferred media 😝

https://huamichaelchen.substack.com/p/end-to-end-example-of-setting-up

https://medium.com/@huamichaelchen/end-to-end-example-of-setting-up-superset-embedded-dashboard-f72fc985559

**Comment by rusackas** [comment]
Hopefully, the answers above are sufficient to close this thread. I'll do so anyway since it's been so long since there was a comment here. If this needs revisiting/reopening, just say the word.
