### ISSUE TITLE
Pivot table sorting issue

### ISSUE THREAD

**Issue by ET-CS** [apache/superset#24255]
When using "Columns total" in pivot tables AND "sort rows" in customize tab is in "value descending" or "value ascending"
The total row is separated from the rows. and collapsing it will hide unrelated rows.

![image](https://github.com/apache/superset/assets/1791696/9bb58dc5-e2d7-4ef4-8b9f-736e844a2abc)

Note that when collapsed - the lower row just disappeared

![image](https://github.com/apache/superset/assets/1791696/4e3b4078-a4ed-4208-96b3-4ef94d2f6bf3)

We expected to have one row with everything inside like:

![Screenshot 2023-05-29 171658](https://github.com/apache/superset/assets/1791696/71ebaa76-0f03-4e41-bc80-8f7c9c8be8a8)

Is there is anyway to have the behavior as we expect?

---

The full configuration is with the flights database:

![image](https://github.com/apache/superset/assets/1791696/65c9cb29-26cd-4878-abe9-2d09eace9c19)

![image](https://github.com/apache/superset/assets/1791696/7ddc4db2-7487-4a23-9a32-ebe60c881d9f)

P.S The same issue exactly happens when using "transpose pivot". we thought maybe we can walkaround it this way.

**Comment by rusackas** [comment]
Is this still happening in 3.x?

**Comment by rusackas** [comment]
Haven't heard back if it's happening in 3.x, and now we're supporting 4.x versions. Closing, but if anyone is still facing this, I'm more than happy to re-open it!

**Comment by kiddi-abler** [comment]
This is still an issue in 4.0.1. The expanded child rows are separated from the subtotal row because the sorting rule sorts them lower than all the subtotal. The row sorting needs to exclude the child rows to keep them next to the parent row. They are still correctly included in the subtotal row though. 

+1 on this being re-opened @rusackas. I'm happy to provide more insights or examples if needed.

**Comment by propellerjet** [comment]
+1
Same issue in 4.0.2, please re-open.
Here is example
![image](https://github.com/user-attachments/assets/e67adb5f-9548-4f37-a2f3-48c550b0fe06)

**Comment by ilvenini** [comment]
Still existing in 4.0.2:

![Image](https://github.com/user-attachments/assets/81f4d3a7-aef9-467e-bb65-8415ef734c40)
