### ISSUE TITLE
Toast Message: Filters may not work correctly

### ISSUE THREAD

**Issue by NormskiJJO** [apache/superset#24261]
After upgrading to 2.0.1 when loading a public dashboard I get a toast message 
"Error loading chart datasources. Filters may not work correctly."

Although the dashboard loads correctly and functions as normal.

**Comment by LeoDiep** [comment]
+1
I was importing dashboards from Superset v1.5.0 to new Superset v2.1.0 and this error notice appear everytime I access or reload the dasboard. On the old superset, these dashboards only use filter sidebar on the left, and when they are imported to new superset, I have to edit the scope manually again but they work just fine, the charts running the same as the old superset.
However the error notice is confusing other users and it's annoying them.

**Comment by villebro** [comment]
@NormskiJJO @LeoDiep are you able to post any additional details from the failed network call? I assume you should be seeing errors in the backend logs when this is happening, could you post those?

**Comment by LeoDiep** [comment]
> @NormskiJJO @LeoDiep are you able to post any additional details from the failed network call? I assume you should be seeing errors in the backend logs when this is happening, could you post those?

Hi, I also commented about it in this https://github.com/apache/superset/issues/19944 
Sorry I don't know how to check the back end logs to see the errors. But I figured out the way to fix it, which is going to every charts in the dashboard and hit Save again. Then the notification dissapear.

**Comment by villebro** [comment]
> Sorry I don't know how to check the back end logs to see the errors. But I figured out the way to fix it, which is going to every charts in the dashboard and hit Save again. Then the notification dissapear.

Without these it's very difficult to help debug the issue. But that workaround can maybe help identify what's causing the issue. Let me think.. In the meantime, if anyone can provide backend logs for the failed dataset request that would be really helpful.

**Comment by nizantz** [comment]
Have been facing the same issue with exporting and importing dashboards in v2.1.0 across environments.

What worked for me , as a workaround, is 

1. Import the charts first and then import the dashboards

or

2. If you have imported the dashboard then update the chart first and the update the dashboard by making some minor changes

However , I believe this issue has been addressed here
https://github.com/apache/superset/pull/23582

**Comment by dustin-liu-bgl** [comment]
Facing the same error on 2.1.0, any update on this?

**Comment by rusackas** [comment]
Hi there, and sorry this has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and since it's been a while since this thread saw any activity, I'll close this as stale. If it is still an issue in Superset 3.x or newer, we can re-open this, or feel free to open a new issue with updated context. Thanks!
