### ISSUE TITLE
password authentication failed for user "superset"

### ISSUE THREAD

**Issue by julianofischer** [apache/superset#24268]
I'm trying to connect an external Postgres database but superset is using a user different from the one I'm providing, resulting in the error password authentication failed for user superset.

#### How to reproduce the bug

1. connect to a database through sqlalchemy string
2. try to create a data source
3. try to select the schema
4. schema is not loaded
### Expected results
schemas are loaded

### Actual results
schemas are not loaded
qlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "db" (172.27.0.2), port 5432 failed: FATAL:  password authentication failed for user "superset"

#### Screenshots

![image](https://github.com/apache/superset/assets/158303/8a24311b-5c57-4182-aa01-4d6570e5c478)

### Environment

(please complete the following information):

- browser type and version: google chrome 113.0.5672.126
- superset version: latest docker-compose version
- python version:  latest docker-compose version
- node.js version:  latest docker-compose version
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x ] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

My other database is running in a container through docker compose.
I've created a shared network and put it in the official docker compose non-dev superset file.

**Comment by julianofischer** [comment]
Forget it.
I had 2 'db's.

**Comment by JunseoChoJJ** [comment]
@julianofischer what do you mean by 2db s? I am struggling with this problem too.
Could you give me more details that how you solve?

**Comment by vmaksimenko** [comment]
@julianofischer Can you give detailed information on this issue, I am also experiencing the same problem. We have PostgreSQL database and configured database connection. A set of charts was created based on this database and placed on the dashboard. When the dashboard is opened some charts are refreshed normally, some fail with the same error. When I refresh failed charts manually they are reloaded successfully, sometime it takes several attempts.

**Comment by vmaksimenko** [comment]
Update for those who are experiencing the same problem. In our case the issue is not related to Superset but provided  source configuration which is running on Kubernetes and instead service name, IP address was provided, load balancer was not doing right request routing
