### ISSUE TITLE
Dependent Filters aren’t working as expected.

### ISSUE THREAD

**Issue by santosh-sahoo334** [apache/superset#24285]
#### How to reproduce the bug
I have something like an “Advertiser” column, and an “Advertisement Date” column, the dependent features aren’t working as expected. I have a table like this -- 
```
2021-03-01 | Ford
2021-03-01 | Honda
2021-03-01 | Mazda
2021-06-01 | Ford
2021-06-01 | Chevy
2021-09-01 | Mazda
2022-03-01 | Ford
2022-03-01 | Tesla
```
If I set up “Advertisers” as a `value` filter, and make it a "dependent filter" based on a `Time Range` filter for the "Advertisement Date" column, the expectation would be:
1. Select a date range of 2021-2022, and Tesla **would NOT** be in the Advertisers menu.
2. Select a data range of 2021-06-01 to 2023, and Honda **would NOT** be in the menu, but **Tesla would be**.

### Environment
(please complete the following information):

- browser type and version: Google Chrome Version 113.0.5672.129 (Official Build) (64-bit)
- superset version: `2.1.0`
- python version: `3.8.16`
- node.js version: `v16.20.0`
- any feature flags active:

**Comment by rusackas** [comment]
I think this may have been resolved by https://github.com/apache/superset/pull/23319

**Comment by rusackas** [comment]
Oops, didn't mean to click the close button there. Please check and confirm that I can, though ;)

**Comment by santosh-sahoo334** [comment]
Sure @rusackas Will do. Thanks!

**Comment by rusackas** [comment]
Any update @santosh-sahoo334?

**Comment by santosh-sahoo334** [comment]
Apologies for the delayed response @rusackas. Verified the functionality and its working fine now. Thanks for the follow up!

**Comment by santosh-sahoo334** [comment]
Closing as it is resolved now.
