### ISSUE TITLE
Can we schedule reports to SFTP as like of Email and Slack

### ISSUE THREAD

**Issue by rohitpawar2811** [apache/superset#24284]
Hello.

I need to schedule the reports on a daily basis to SFTP-Server so Is this feature exists in superset?

Or if not, can you integrate this feature in the future in a superset  ( I mean is it in the roadmap or not)?

@rusackas

**Comment by rusackas** [comment]
Currently, Superset does not support this. We'd welcome a PR if you're inclined to build out such a feature. Or, if you'd like to seek community support for this feature request, please open a new [Ideas thread](https://github.com/apache/superset/discussions/categories/ideas) in our [Github Discussions](https://github.com/apache/superset/discussions) area insead. Thanks!
