### ISSUE TITLE
Helm install timed out waiting for condition

### ISSUE THREAD

**Issue by kalkrishnan** [apache/superset#24292]
#### How to reproduce the bug

1. Ran the helm command to install superset as provided in documentation:
helm upgrade --install --values values.yaml superset superset/superset --debug
Below is my values.yaml:

supersetNode:
  replicaCount: 1
supersetWorker:
  replicaCount: 1
configOverrides:
  secret: |
    SECRET_KEY = '+k2Z2vhUxso2oQwOKqndZ08O7m8kRJHcIumqYZvyxHH9IAPtdh8nnnn'
                                                  
### Expected results

Based on documentation should result in worker pods starting where you can portforward and login

### Actual results
Gives the below error:
history.go:56: [debug] getting history for release superset
install.go:200: [debug] Original chart version: ""
install.go:217: [debug] CHART PATH: /private/var/kal/Library/Caches/helm/repository/superset-0.10.1.tgz

client.go:134: [debug] creating 16 resource(s)
client.go:478: [debug] Starting delete for "superset-init-db" Job
client.go:482: [debug] Ignoring delete failure for "superset-init-db" batch/v1, Kind=Job: jobs.batch "superset-init-db" not found
client.go:134: [debug] creating 1 resource(s)
client.go:706: [debug] Watching for changes to Job superset-init-db with timeout of 5m0s
client.go:734: [debug] Add/Modify event for superset-init-db: ADDED
client.go:773: [debug] superset-init-db: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:734: [debug] Add/Modify event for superset-init-db: MODIFIED
client.go:773: [debug] superset-init-db: Jobs active: 1, jobs failed: 1, jobs succeeded: 0
client.go:734: [debug] Add/Modify event for superset-init-db: MODIFIED
client.go:773: [debug] superset-init-db: Jobs active: 1, jobs failed: 2, jobs succeeded: 0
Error: failed post-install: 1 error occurred:
	* timed out waiting for the condition

helm.go:84: [debug] failed post-install: 1 error occurred:
	* timed out waiting for the condition

State of pods after:

superset-6465bdcf9c-g6kdg                                        0/1     Init:0/1     4 (2m17s ago)   10m
superset-init-db-5t244                                           0/1     Init:Error   0               10m
superset-init-db-7l5n8                                           0/1     Init:Error   0               8m54s
superset-init-db-fvqdq                                           0/1     Init:Error   0               4m16s
superset-init-db-n47r2                                           0/1     Init:0/1     0               93s
superset-init-db-vmln5                                           0/1     Init:Error   0               6m41s
superset-postgresql-0                                            0/1     Pending      0               10m
superset-redis-master-0                                          1/1     Running      0               10m
superset-worker-6f99f98c48-67jb6                                 0/1     Init:0/1     4 (2m17s ago)   10m

The worker keeps crashing and wont let me see any logs as to why

### Environment

(please complete the following information):

- superset version: latest helm chart

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by matheuscarreirod** [comment]
i'm having the same issue, did you solve it?

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.

**Comment by jrgilman** [comment]
I'm running into this issue as well @rusackas 

```
minikube@ip-172-22-159-19:~$ helm upgrade --install --values superset-values.yaml superset superset/superset --debug
history.go:56: 2024-10-16 20:50:09.380462312 +0000 UTC m=+0.032188958 [debug] getting history for release superset
Release "superset" does not exist. Installing it now.
install.go:224: 2024-10-16 20:50:09.38265876 +0000 UTC m=+0.034385411 [debug] Original chart version: ""
install.go:241: 2024-10-16 20:50:09.628328749 +0000 UTC m=+0.280055395 [debug] CHART PATH: /home/minikube/.cache/helm/repository/superset-0.12.11.tgz

client.go:142: 2024-10-16 20:50:10.09668368 +0000 UTC m=+0.748410327 [debug] creating 16 resource(s)
client.go:486: 2024-10-16 20:50:10.170143707 +0000 UTC m=+0.821870357 [debug] Starting delete for "superset-init-db" Job
wait.go:104: 2024-10-16 20:50:10.191085613 +0000 UTC m=+0.842812260 [debug] beginning wait for 1 resources to be deleted with timeout of 5m0s
client.go:142: 2024-10-16 20:50:10.265166746 +0000 UTC m=+0.916893393 [debug] creating 1 resource(s)
client.go:712: 2024-10-16 20:50:10.275878823 +0000 UTC m=+0.927605470 [debug] Watching for changes to Job superset-init-db with timeout of 5m0s
client.go:740: 2024-10-16 20:50:10.284641528 +0000 UTC m=+0.936368201 [debug] Add/Modify event for superset-init-db: ADDED
client.go:779: 2024-10-16 20:50:10.284676903 +0000 UTC m=+0.936403551 [debug] superset-init-db: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:740: 2024-10-16 20:50:10.292421504 +0000 UTC m=+0.944148154 [debug] Add/Modify event for superset-init-db: MODIFIED
client.go:779: 2024-10-16 20:50:10.292690615 +0000 UTC m=+0.944417264 [debug] superset-init-db: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:740: 2024-10-16 20:52:13.754452578 +0000 UTC m=+124.406179231 [debug] Add/Modify event for superset-init-db: MODIFIED
client.go:779: 2024-10-16 20:52:13.755182843 +0000 UTC m=+124.406909489 [debug] superset-init-db: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:740: 2024-10-16 20:52:13.773206393 +0000 UTC m=+124.424933042 [debug] Add/Modify event for superset-init-db: MODIFIED
client.go:779: 2024-10-16 20:52:13.773234499 +0000 UTC m=+124.424961148 [debug] superset-init-db: Jobs active: 1, jobs failed: 1, jobs succeeded: 0
client.go:740: 2024-10-16 20:54:16.935538102 +0000 UTC m=+247.587264749 [debug] Add/Modify event for superset-init-db: MODIFIED
client.go:779: 2024-10-16 20:54:16.935567555 +0000 UTC m=+247.587294201 [debug] superset-init-db: Jobs active: 1, jobs failed: 1, jobs succeeded: 0
client.go:740: 2024-10-16 20:54:16.952248256 +0000 UTC m=+247.603974903 [debug] Add/Modify event for superset-init-db: MODIFIED
client.go:779: 2024-10-16 20:54:16.952274821 +0000 UTC m=+247.604001467 [debug] superset-init-db: Jobs active: 1, jobs failed: 2, jobs succeeded: 0
Error: failed post-install: 1 error occurred:
        * timed out waiting for the condition


helm.go:86: 2024-10-16 20:55:10.288846193 +0000 UTC m=+300.940572842 [debug] failed post-install: 1 error occurred:
        * timed out waiting for the condition


minikube@ip-172-22-159-19:~$ helm search repo superset
NAME                    CHART VERSION   APP VERSION     DESCRIPTION                                       
superset/superset       0.12.11         4.0.1           Apache Superset is a modern, enterprise-ready b...
```

**Comment by jrgilman** [comment]
@rusackas I found the issue, my server is running an ARM processor and is using arm64, the postgres version referenced in the helm chart is ancient and does not support ARM (only x86): https://hub.docker.com/r/bitnami/postgresql/tags?name=14.6.0-debian-11-r13

You can manually change this by changing the tag, but I think the default probably should be updated to an image that does support both architectures?

**Comment by er-sarjan** [comment]
@rusackas : I'm trying to setup superset by following the installation page from docs using minikube but get following error:

https://superset.apache.org/docs/installation/kubernetes

`kubectl get pods`

> NAME                               READY   STATUS             RESTARTS     AGE
> superset-76f7886779-7kfhb          0/1     Init:0/1           0            27s
> superset-init-db-9654s             0/1     Init:0/1           0            27s
> superset-postgresql-0              0/1     CrashLoopBackOff   1 (4s ago)   27s
> superset-redis-master-0            0/1     Running            0            27s
> superset-worker-5df96cfccc-phhw8   0/1     Init:0/1           0            27s

`kubectl logs superset-postgresql-0`

> exec  /opt/bitnami/scripts/postgresql/entrypoint.sh: exec format error

Ubuntu server with arm64 architecture

`uname -m`
> aarch64

I searched but it seems, the postgre arm64 is not available as mentioned by @jrgilman
