### ISSUE TITLE
Logical issue: filter on range filters on Seconds level, while chart grain is set to Day leading to wrong chart info

### ISSUE THREAD

**Issue by j-a-a-p** [apache/superset#24300]
In the custom fillter of the bar chart, Days get translated to Seconds. For a chart set to Seconds time grain, perhaps a line chart, this would be OK, but a chart that aggregates to a courser time grain, this will lead to faulty data.

Below the screenshot of the filter. The setting is on Day level, but it can be seen already that a seconds level value will be used. '7 days before'. actually means '604,800 seconds before'.
<img width="600" alt="image" src="https://github.com/apache/superset/assets/97532277/b3106167-6a98-4d04-a2c5-6be133792a0b">

In the screenshot below you can see the ramnifications. On a day-level aggregated bar chart the value of the first column is not correct.

#### How to reproduce the bug

1. Creating a bar chart based on time based, transactional data set
2. Set Time Grain to Day
3. Add a Custom filter on the time, set it to between 7 days before, and Now. (See also screenshot above)
4. Bug: Notice that the first column will show a decreasing value during the course of the day.

### Expected results
For a chart that is set to a certain time grain, make the filter obey this setting.
Or
Obey the granularity of the filter. If it is set to Days before, go back only that in days. If set in Hours, Seconds, go back to that level of granularity

### Actual results
Customer filer always gets translated to the lowest granularity level.

#### Screenshots
Chart at 13:30.
<img width="608" alt="image" src="https://github.com/apache/superset/assets/97532277/4db19c52-700f-4b2d-9c1c-ef37c1bcd403">

Same chart 2 hours later.
<img width="612" alt="image" src="https://github.com/apache/superset/assets/97532277/d4729e38-3fe6-41d9-b213-3d1db92acc19">

### Environment
Mac, Chrome

### Checklist
- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sfirke** [comment]
I believe there's an option "Midnight" instead of "Now" - does choosing that cause the behavior you're seeking?

**Comment by j-a-a-p** [comment]
Used Midnight before, but that sets to last midnight filtering the data of today.

**Comment by rusackas** [comment]
I can see your point... Today would be a nice add-on, and we'd be open to a PR if you want to add that. But it's more of a feature request than a bug.

For your use case, you can use the Advanced time range editor, and do something like this:

<img width="587" alt="image" src="https://github.com/apache/superset/assets/812905/38f94b11-bf95-4ac8-bf39-374bfebc9a56">

Hopefully that suffices to close this, but let us know if you think it warrants reopening.
