### ISSUE TITLE
(table) multi sort not work

### ISSUE THREAD

**Issue by Hokwang** [apache/superset#24318]
#### How to reproduce the bug

I have a table dashboard and then
1. click first column name twice for sort asc -> it shows "N/A" first and other values 
2. shift+click forth column name -> nothing can change. it's not working

### Expected results

show forth column ordering

### Actual results

not working

#### Screenshots

![image](https://github.com/apache/superset/assets/1247030/e1a99de1-5666-45eb-875d-8f4a458a8671)

### Environment

- browser type and version: chrome
- superset version: 2.1.0

installed using helm chart.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

when order forth column first and then order first column -> it works!
forth column does not have N/A value.

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.

**Comment by Hokwang** [comment]
@rusackas Hi, I tested this on 3.1.1. (latest). This bug still exists. Please re-open this.

**Comment by Hokwang** [comment]
@rusackas Please take care "table". I am waiting #24319 also.

**Comment by justinpark** [comment]
I am currently in the process of planning a SIP proposal using ag-grid table as a replacement for the sqllab result table. This library would allow for multi-order sorting.

@Hokwang I'll tag this post in the SIP proposal to ensure that you receive updates on its progress.

**Comment by rusackas** [comment]
Closing this out since (a) it's gone stale, but mainly (b) it's a feature request more than a bug. The current table may does not support multi-sort. PRs to change that are welcome if anyone wants to improve things.
