### ISSUE TITLE
Password not masked in Database connection when datasource added through YAML file.

### ISSUE THREAD

**Issue by MalavikaN1** [apache/superset#24321]
#### How to reproduce the bug

1. Click on setting
2. Go to Database Connections
3. Click on edit button in Actions for a dataset

### Expected results

The password in the SQLAlchemy URI should be masked with XXXX

### Actual results

The password is initially displayed, but once you click on the input box change something  and click on finish and then reopen it, it becomes masked.
### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: `superset version` : latest

![2](https://github.com/apache/superset/assets/60867680/36ec1a58-a8c5-4e09-97dc-26c729a412da)
![1](https://github.com/apache/superset/assets/60867680/36a13305-476b-4e1e-a707-fa06caba5d82)

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x ] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Hi there, and sorry this has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale. If it is still an issue in Superset 3.x, we can re-open this, or feel free to open a new issue with updated context.
