### ISSUE TITLE
swagger/v1/dataset/import not working 

### ISSUE THREAD

**Issue by jenarosm** [apache/superset#24336]
When trying to import a dataset from an exported dataset yaml I can´t seem to get it to work.
Also tried using python following the notebook found in the API presentation but no luck either.

#### How to reproduce the bug

Using swagger/v1/dataset/export to get the yaml file
Delete this dataset from Superset.
Using swagger/v1/dataset/import upload previously exported yaml file

### Expected results

Dataset imported succesfully

### Actual results

Code: 200 
Response body: A html page

#### Screenshots

![image](https://github.com/apache/superset/assets/51678677/d0c5c4a1-246a-4b21-a463-319aedac7bd1)

### Environment

- browser type and version: Microsoft Edge 114.0.1823.41 
- superset version: 1.3.2
- python version: 3.7.12

### Additional context
Also tried using superset version 2.1.0
Someone suggested adding  a random value to password string solves this issue but it does not seem to work

**Comment by sebastianliebscher** [comment]
Did you disable CSRF or tried providing a CSRF token?

Here's an example how to pass this token: https://github.com/apache/superset/discussions/18337#discussioncomment-6050820

**Comment by jenarosm** [comment]
I still get an error while trying to import the dataset as a yaml file.
That yaml file is the same file generated by exporting a dataset.

**Comment by rusackas** [comment]
This version of Superset is no longer supported. If anyone is still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
