### ISSUE TITLE
Table Visual: Displaying records on searching for wrong records

### ISSUE THREAD

**Issue by NehaAwasthi9616** [apache/superset#24356]
The search tab for table visualization is enabled for all the columns. On searching a random record (like 100 in this case), it is showing records which do not contain "100" or similar record. 
Can you please advise?
It would be great if we can enable the search tab for specific columns in the visual.

<img width="760" alt="image" src="https://github.com/apache/superset/assets/136068155/4cc21d57-f690-4b71-a275-a7284e284a4c">

**Comment by rusackas** [comment]
I can't seem to reproduce this in 3.1, so I'll close it. Adding search to column headers _would_ be awesome, but that's a feature request rather than a bug. We'd be happy to review a PR or join a GitHub Discussion thread if you're interested in contributing toward it.
