### ISSUE TITLE
Treemap: Not showing all the data

### ISSUE THREAD

**Issue by NehaAwasthi9616** [apache/superset#24355]
We want to display the charges by multiple fee items in our Tree map and enable the cross-filtering. There are 5 rows in the table however treemap is only showing 3 items.
<img width="767" alt="image" src="https://github.com/apache/superset/assets/136068155/519d8a99-fbab-4d73-933f-52b833ded1c1">

### Expected results
It should show five tiles for all the rows of the table.

**Comment by sfirke** [comment]
What version of Superset are you using?  I cannot replicate this on 2.1.0.  Here's what I get:

![image](https://github.com/apache/superset/assets/7569808/f5739769-6821-4266-8ddb-54feb31000d8)

**Comment by sfirke** [comment]
I am out of ideas 😕 I wonder if anyone else can replicate this or has ideas for troubleshooting it further.  If you change this to another visualization type, like bar chart, do all five categories appear?

**Comment by sfirke** [comment]
I wonder if this is the same issue: https://github.com/apache/superset/issues/23788

**Comment by NehaAwasthi9616** [comment]
Yeah, it shows all the values when changed to bar graph. 
I am using postgres SQL

**Comment by sfirke** [comment]
If you try this with a dataset that has say, 10 categories instead of the 5 here, how many are shown on the treemap?  If it's always two missing, then maybe it's the same as #18155.

**Comment by NehaAwasthi9616** [comment]
Yeah it might be, Also few of my pie charts are also showing one out of two rows. 
<img width="623" alt="image" src="https://github.com/apache/superset/assets/136068155/375de9d1-12d1-43b1-b7dd-962b2ace020a">

This is pretty weird as this issue is there for a few of them. Few others are displaying the correct data.

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
