### ISSUE TITLE
(Superset 2.1.0)Database connection driver issues: Unable to connect to mongobi database

### ISSUE THREAD

**Issue by ChristopheBear** [apache/superset#24352]
Our team was able to connect to the mongobi database without any problem in the old version, however, when we upgraded to superset version 2.1.0, we had a problem that we could not connect to the mongobi database(Not mongodb database).

#### How to reproduce the bug

1. Go to settings -> databases -> edit(choose an existed mongobi database which was connected successfully before in the old version of superset) 
2. Click on Test Connection
3. See error

### Expected results

Mongobi database can be successfully connected.

### Actual results

After starting the local debugger, the front-end tests the mongobi database connection and finds the error message.

#### Screenshots

![image](https://github.com/apache/superset/assets/52247106/281c912e-f372-48c9-9787-c9c222be1e66)
![image](https://github.com/apache/superset/assets/52247106/d32617e6-2ebe-47df-afc9-1df14b3a58a9)
![image](https://github.com/apache/superset/assets/52247106/2e76c229-d9b0-4ccf-8d99-a60d53483a0c)

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset 2.1.0`
- python version: `python --3.9.12`
- SQLAlchemy version:  `SQLAlchemy 1.4.24 ` 
- sqlalchemy-mongobi version:`sqlalchemy-mongobi  0.2.1`
- PyMySQL version:`PyMySQL 1.0.3` 

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Additional Information about mongobi(MongoDB Connector for Business Intelligence):
Traditional business intelligence tools work with flat, tabular data. These tools aren't sophisticated enough to understand three-dimensional data stored in MongoDB databases.
The MongoDB Connector for Business Intelligence (BI) allows you to create queries with SQL to visualize, graph, and report on your three-dimensional MongoDB data using relational business intelligence tools such as Tableau and Power BI.
For more information, please see https://www.mongodb.com/docs/bi-connector/master/what-is-the-bi-connector/

**Comment by rusackas** [comment]
Looking at the [docs](https://pypi.org/project/sqlalchemy-mongobi/) you'd want to specify a dbapi, like `mongobi+mysqldb://user?source=auth_db:password@url:port/database` or `mongobi+pymysql://user?source=auth_db:password@url:port/database` - have you tried that?

Also, is this still the case in Superset 3.x? We're closing most 2.x or earlier issues since that version is no longer suported.

**Comment by rusackas** [comment]
I just realized that driver hasn't been updated in over 5 years. I'm not sure if it's rock-solid-stable (unlikely) or unsupported (more likely). I'll close this Issue since the thread is stale anyway, but we can re-open it if there's more to work on here. I'd suggest we move toward natively SQL-speaking Mongo tools like Atlas (linked above) or an intermediary like Presto/Trino, unless there's a better-supported SQLAlchemy driver for mongo.

**Comment by hetz** [comment]
Thanks for reporting this issue.

To apply a temporary fix, you can patch the SQLAlchemy `default.py` file inside the `superset_app` container to conditionally skip the `rollback()` call when connecting to a specific MySQL port (e.g., 3307). This is useful in scenarios where the underlying database (like some MySQL setups) does not expect or properly handle explicit rollback calls.

You can apply the patch and restart the container using the following commands:

```bash
docker exec -i superset_app bash <<'EOF'
sed -i."$(date +%Y%m%d_%H%M%S)_bak" '/def do_rollback(self, dbapi_connection):/{
    N
    s/dbapi_connection\.rollback()/\
try:\\n    if getattr(dbapi_connection, "port", None) == 3307:\\n        return\\nexcept Exception:\\n    pass\\n    dbapi_connection.rollback()/
}' /app/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py
EOF

docker restart superset_app
```

**Explanation:**
- The `sed` command creates a timestamped backup of the original file.
- It modifies the `do_rollback` method to skip calling `rollback()` if the connection's port is 3307 (commonly used for certain MySQL proxies or read replicas).
- This change is ephemeral and will be lost if the container is rebuilt, so consider baking this into a custom image for production use.

> ⚠️ **Note**: Modifying files inside a running container is not recommended for production environments. This workaround is intended for testing or temporary mitigation. A more robust solution would involve upgrading SQLAlchemy, patching the application, or adjusting the database driver behavior.
