### ISSUE TITLE
Superset upgrade issue: no such column: dbs.allow_multi_schema_metadata_fetch

### ISSUE THREAD

**Issue by cphilibien** [apache/superset#24370]
After upgarde superset 2.0.0 to 2.1.0, I lost my databases connection
I had 2 database: 1 sqlite for superset's users and metadata and 1 BD postgres for my data.
![image](https://github.com/apache/superset/assets/112178756/50d711c1-7f1d-4209-8584-d22d3eeaaead)

The text error
```shell
An error occurred while fetching databases: (sqlite3.OperationalError) no such column: dbs.allow_multi_schema_metadata_fetch
[SQL: SELECT count(*) AS count_1
FROM (SELECT dbs.changed_on AS dbs_changed_on, dbs.id AS dbs_id, dbs.database_name AS dbs_database_name, dbs.sqlalchemy_uri AS dbs_sqlalchemy_uri, dbs.password AS dbs_password, dbs.expose_in_sqllab AS dbs_expose_in_sqllab, dbs.allow_run_async AS dbs_allow_run_async, dbs.allow_file_upload AS dbs_allow_file_upload, dbs.allow_ctas AS dbs_allow_ctas, dbs.allow_cvas AS dbs_allow_cvas, dbs.allow_dml AS dbs_allow_dml, dbs.force_ctas_schema AS dbs_force_ctas_schema, dbs.allow_multi_schema_metadata_fetch AS dbs_allow_multi_schema_metadata_fetch, dbs.extra AS dbs_extra, dbs.created_by_fk AS dbs_created_by_fk, created_by.id AS created_by_id, created_by.first_name AS created_by_first_name, created_by.last_name AS created_by_last_name
FROM dbs LEFT OUTER JOIN ab_user AS created_by ON dbs.created_by_fk = created_by.id) AS anon_1]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
``` 

#### How to reproduce the bug
I upgrade superset:
1. `pip install apache-superset --upgrade` => ok, you can see the version of superset 
![image](https://github.com/apache/superset/assets/112178756/b765f0b7-8107-4835-bef9-a0a44afe78bf)
2. `superset db upgrade`
     if I config SQLALCHEMY_DATABASE_URI with slqlite => upgrade stop at INFO  [alembic.runtime.migration] Will assume transactional DDL.
scrrenshot: 
![image](https://github.com/apache/superset/assets/112178756/11dc7e05-a025-4303-a227-4814291fa03f)
    if I config SQLALCHEMY_DATABASE_URI with postgres  => upgrade show any errors
3. `superset init`
4. I connect to superset 
     if I config SQLALCHEMY_DATABASE_URI with slqlite => I have the error
    if I config SQLALCHEMY_DATABASE_URI with postgres  => my user login not working (logical)

I don't find solution to solve my issue, if someone can help with a tips or the solution, it could be appreciate
Thanks a lot!!!!

**Comment by cphilibien** [comment]
I find my issue!!! it's was my python env

**Comment by franz3452** [comment]
> I find my issue!!! it's was my python env

Hello! I have the same problem. What was wrong with your env?

**Comment by cphilibien** [comment]
I didn't active the good env and I install this version for sqlparse sqlparse=='0.4.3’

**Comment by rusackas** [comment]
This version of Superset is no longer supported. If anyone is still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
