### ISSUE TITLE
show columns from table not support

### ISSUE THREAD

**Issue by busgo** [apache/superset#24382]
When I configure datasets using hive data source, I find that hive cannot support the show columns from table statement, which makes it impossible to configure datasets. Is there a corresponding version that is compatible with lower versions of hive?
### Expected results
   hive table column collection result 

### Actual results

  empty columns  result

### Environment

- superset version:  master
- python version:  3.9
- hive  2.1.1

**Comment by sfirke** [comment]
Is this the same problem as https://github.com/apache/superset/issues/23676?

**Comment by sfirke** [comment]
Is this the same problem as https://github.com/apache/superset/issues/24031 ?

**Comment by rusackas** [comment]
Based on the linked threads, this is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please let us know so we can reopen this. Or you're welcome to open a new Issue with updated context or a PR to address the problem.
