### ISSUE TITLE
BarChart (Legacy) doesn't take the timerange filter on dashboard

### ISSUE THREAD

**Issue by ShabanGerber** [apache/superset#24398]
The timerange Filter for the BarChart (Legacy) ist not working on the dashboard.
If you have a look in the generated sql query, you can not see the timerange was not used.

#### How to reproduce the bug

1. Generate a new BarChart (Legacy)
2. Set your preferred filters
3. Save the BarChart
4. Add the BarChart to your dashboard
5. Select Filter for the barchart on your dashboard e.g. 'last day'
6. Prove the SQL Statement for this barchart
7. You cann see that in the where clause the timerange filter is missing

### Expected results

We expect that the timerange filter will be used correct.

### Actual results

the timerange filter is not used in barchart

### Environment

(please complete the following information):

- browser type and version: Safari 114.0 (64-Bit)
- superset version: we have updated to the current version today
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sfirke** [comment]
When you say you updated to the current version, is that 2.1.0?  Or 0.0.0dev (master branch)?  This looks like an issue that should have been fixed by this https://github.com/apache/superset/pull/23865 which would be on 0.0.0-dev but not 2.1.0.

**Comment by ShabanGerber** [comment]
Hi sfirke,

first thank you for your response :)
yes we have the 0.0.0-dev branch. We will update our superset to  2.1.1 as mentioned here: https://github.com/apache/superset/pull/23865 and test the BarChart (Legacy) again.

When we will be finished at all. I will let you know her about our test result.

**Comment by sfirke** [comment]
That sounds good.  So you know, 2.1.1 is currently being tested for release as 2.1.1rc1.  So if you're looking for a version to test, you could run 2.1.1rc1, or wait for 2.1.1 to be officially released (likely in the coming weeks) and test it then.

**Comment by sfirke** [comment]
@ShabanGerber Superset 2.1.1 was officially released yesterday!  Are you able to upgrade + see if your problem is resolved?

**Comment by rtexelm** [comment]
@rusackas might want to change the status here

**Comment by rusackas** [comment]
Indeed, we're no longer officialy supporting 2.x, the legacy bar chart has been migrated away, and this thread has gone cold. Closing! :D
