### ISSUE TITLE
running site on https

### ISSUE THREAD

**Issue by nk8291** [apache/superset#24424]
### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by nk8291** [comment]
Community, we are trying to access superset on https, we did setup the nginx and passed the reverse proxy configuration in nginx.conf file and did relevant changes in superset_config.py and config.py , but still we are unable to get site running on https

**Comment by rusackas** [comment]
This is a configuration issue, rather than a bug. We won't be able to support you without reproducible steps (e.g. what was changed in what files, what your config looks like, etc). I'd suggest opening a thread in `#deploying-superset` on [Superset Slack](http://bit.ly/join-superset-slack)

**Comment by nk8291** [comment]
Hi team, I was able to fix the setup.
