### ISSUE TITLE
the help menu never shows.. if you've not got the default key setup.. this is bad UX

### ISSUE THREAD

**Issue by EMCP** [apache/superset#24439]
I pip install latest version of superset.. I want to inspect the commands but.. it basically chokes because I am still setting things up

```
buntu@juju-3091f8-35:~$ .local/bin/superset --help
--------------------------------------------------------------------------------
                                    WARNING
--------------------------------------------------------------------------------
A Default SECRET_KEY was detected, please use superset_config.py to override it.
Use a strong complex alphanumeric string and use a tool to help you generate 
a sufficiently random sequence, ex: openssl rand -base64 42
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Refusing to start due to insecure SECRET_KEY

```

I just want to look at the help menu...

**Comment by EMCP** [comment]
I'd additionally request that there be a option to perform `superset init` with a `--silent` option

**Comment by rusackas** [comment]
You can start in dev mode with a default secret key, but not in prod mode (for good reason). 


> I'd additionally request that there be a option to perform superset init with a --silent option

As they say in open source: PRs welcome! It sounds great, but isn't likely to get prioritized by most core committers.
