### ISSUE TITLE
Help! I can't find the location of the API for querying the dashboard list in the source code. Can someone assist me? Thank you very much!

### ISSUE THREAD

**Issue by xulcdev** [apache/superset#24450]
I couldn't find the API for querying the dashboard list in superset/dashboards/api.py. Is it located somewhere else? I've been searching for a long time and haven't found it.

**Comment by sebastianliebscher** [comment]
For questions about Superset please use the [Discussions](https://github.com/apache/superset/discussions) or join the [Superset Slack](http://bit.ly/join-superset-slack).

The endpoint is auto generated via FAB's auto CRUD feature. More info here: https://flask-appbuilder.readthedocs.io/en/latest/rest_api.html#model-rest-api
