### ISSUE TITLE
An error occurred while fetching chart info:Forbidden

### ISSUE THREAD

**Issue by christianxiaobai** [apache/superset#24469]
superset version: `superset 2.0`
python version: `python 3.9`
mysql version: `mysql 5.6`

I have made the following changes to the configuration file.
vim config.py

  SQLALCHEMY_DATABASE_URI = 'mysql://user_name:password@host/dbname'
  
  class CeleryConfig:
      broker_url = "sqla+mysql://user_name:password@host:3306/dbname"
      imports = ("superset.sql_lab",)
      result_backend = "db+mysql://user_name:password@host:3306/dbname"

I am admin user,But I see the picture below 
![Uploading image.png…]()

**Comment by christianxiaobai** [comment]
<img width="1429" alt="image" src="https://github.com/apache/superset/assets/70797042/4fe03444-b4af-43b0-b2eb-57cfcf14f00a">

**Comment by christianxiaobai** [comment]
I remodified the metadata database

**Comment by isaiasjusto** [comment]
Para aqueles que assim como eu tiveram a mesma duvida eu fiz o seguinte:
Observei que esse erro normalmente é causado por conta de permissão que o seu usuario não tem, então, precisamos dar
Mas antes segundo o site que confirma a minha afirmação
https://www.restack.io/docs/superset-knowledge-superset-api-error-forbidden-guide
"Common Causes
User Role Restrictions: Users may be assigned roles with limited permissions. Attempting actions outside of these permissions will result in a Forbidden error.
Incorrect Credentials: Providing incorrect authentication details can lead to a Forbidden response.
API Endpoint Restrictions: Some API endpoints may have stricter access controls, requiring specific roles or permissions."
Seguindo primeiro utilizando o ubuntu (por onde fiz a instalação) verifiquei o ls -la ~/.superset para entender minhas permissões então depois chmod -R 700 ~/.superset ai pronto funcionou e estou utilizando ele .

**Comment by lboross-ia** [comment]
I had issues with this as well. It seems like the superset db upgrade is broken or incomplete for Postgres.

If you compare the SQLite Meta database to the Postgres after a fresh db upgrade and superset fab create-admin, you will notice ab_role, ab_user_role, ab_view_menu, ab_permission_view, ab_permission_view_role etc are missing rows.

My hack for this was to open the SQLite database in dbeaver and export these tables to my postgres meta database. You will need to work around the primary key ID's and sequence numbers but its possible to make it work.

**Comment by xueyun0512** [comment]
Hi!

I'm using **apache-superset==5.0.0**  with Postgres as well. Using the user "admin", I got several error on the web UI. 
The log shows:
`2025-12-09 17:00:30,689:INFO:werkzeug:100.76.210.16 - - [09/Dec/2025 17:00:30] "GET /api/v1/log/recent_activity/?q=(distinct:!f,page_size:24) HTTP/1.1" 403 -
2025-12-09 17:00:30,689:INFO:werkzeug:100.76.210.16 - - [09/Dec/2025 17:00:30] "GET /api/v1/dashboard/?q=(filters:!((col:owners,opr:rel_m_m,value:'1')),order_column:changed_on_delta_humanized,order_direction:desc,page:0,page_size:5) HTTP/1.1" 403 -
2025-12-09 17:00:30,814:INFO:werkzeug:100.76.210.16 - - [09/Dec/2025 17:00:30] "GET /api/v1/saved_query/?q=(filters:!((col:created_by,opr:rel_o_m,value:'1')),order_column:changed_on_delta_humanized,order_direction:desc,page:0,page_size:5) HTTP/1.1" 403 -
2025-12-09 17:00:30,816:INFO:werkzeug:100.76.210.16 - - [09/Dec/2025 17:00:30] "GET /api/v1/chart/?q=(filters:!((col:owners,opr:rel_m_m,value:'1')),order_column:changed_on_delta_humanized,order_direction:desc,page:0,page_size:5) HTTP/1.1" 403 -
2025-12-09 17:00:30,934:INFO:werkzeug:100.76.210.16 - - [09/Dec/2025 17:00:30] "GET /api/v1/saved_query/_info?q=(keys:!(permissions)) HTTP/1.1" 403 -
`

Why do I got this while I'm admin? I didn't compare the postgres db and sqlite but is postgres deprecated if database upgrade is not working as mention by @lboross-ia ?

Also, I didn't find any documentation about metadata management. 
Does someone find it?

Anything help would be appreciate :) 
Thanks!
