### ISSUE TITLE
Transition of Navbar from dark to light is not smooth

### ISSUE THREAD

**Issue by git-init-priyanshu** [apache/superset#24478]
## Screenshot

https://github.com/apache/superset/assets/110045644/f8c985f5-30a9-4ac3-a854-2f77c7930a97

## Description

While scrolling the transition of Navbar from dark to light or vice-versa is not smooth.

## Design input
May I submit a pull request to address this issue? I just added a transition of 0.5 sec to the navbar and it looks much better now.

https://github.com/apache/superset/assets/110045644/377c11a7-a7f6-475f-8c6b-da4be1ba7380

**Comment by rusackas** [comment]
Oops, this issue never got closed with your PR. Thanks for that!

**Comment by git-init-priyanshu** [comment]
> Oops, this issue never got closed with your PR. Thanks for that!

Haha, thanks for merging my first open-source PR. Now that I look at it, I realize it is not very impactful, but it was a good start, I guess.
