### ISSUE TITLE
Error with Docker contenarized deployment

### ISSUE THREAD

**Issue by PowerDinosaur** [apache/superset#24483]
Hi guys!
We would like to deploy Superset in a Docker contenarized enviroment, our DevOps team trying to make it work for days but without success. Now they are getting this message ( i attach the full log):
superset pkg_resources.DistributionNotFound: The 'cryptography<40,>=39.0.1' distribution was not found and is required by apache-superset
. Does anyone have any idea for this kind of problem ?
We would like to use Superset for our product and it works super cool in our VMs but of course that's not a solution for production where we need HA, LDAP, etc...
Thank you for your answers in advance and have a nice day!
[superset-error.txt](https://github.com/apache/superset/files/11832855/superset-error.txt)

**Comment by sfirke** [comment]
I'm closing this issue as there's been no response.  If it persists and you're able to provide additional information, feel free to reopen.  Or come join the Apache Superset Slack and ask your question there.
