### ISSUE TITLE
Having a trailing backslash in supersetDomain when embedding silently fails

### ISSUE THREAD

**Issue by Nisden** [apache/superset#24526]
When you attempt to embed an Superset dashboard using the `@superset-ui/embedded-sdk` package, having an trailing backslash in the `supersetDomain` will silently fail.

The IFrame will display the superset loading indicator, and make an request to `/roles` however nothing more happens.

#### How to reproduce the bug

1. Enable embedding in Superset
2. Create an application where you want to embed a dashboard
3. Generate a Guest_Token
4. Embed Superset using the following snippet
```
embedDashboard({
                id: yourembedid,
                supersetDomain: http://localhost:8088/, // Notice the trailing backslash
                mountPoint: document.getElementById("dashboard"),
                fetchGuestToken: async () => {
                    return "Your guest token";
                }
            })
```

### Expected results

I expect the embedded dashboard to either load, or throw an error in the console.

### Actual results

The loading indicator is display, but afterwards no error or dashboard is displayed

### Environment

(please complete the following information):

- browser type and version: Microsoft Edge - Version 114.0.1823.58 (Official build) (64-bit)
- superset version: `superset version` - Superset 0.0.0-dev / Based off apache/superset:latest@sha256:de1fc7e9e51cda19aa8e510c6dce683a949d7515d4d76b774ec940332761fdfa
- python version: `python --version` Python 3.9.16
- node.js version: `node -v` command not found
- any feature flags active: EMBEDDED_SUPERSET

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Is this still an issue in current Superset?

**Comment by rusackas** [comment]
Looks like this was resolved by https://github.com/apache/superset/pull/25020
