### ISSUE TITLE
superset time filter problem

### ISSUE THREAD

**Issue by victortony** [apache/superset#24529]
#### How to reproduce the bug

1. Go to "Datasets" 
2. Click on 'dataset name'
3. look at 'Time' section
4. there are to problems

The first question:
I have set DEFAULT_TIME_FILTER = "Last day" in my superset_config.py.
Look at the circle on the pic, "time range" does not use "last day". It still use "No Filter" 
<img width="432" alt="image" src="https://github.com/apache/superset/assets/13748044/c363b91a-7fd1-47c9-8605-71d001efe590">

Another question is how to set the "time grain" ? There is only one in my chart, which is "P1D"?

please 

### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by victortony** [comment]
> What database are you connecting to and what version of Superset are you running?

superset: 2.0.0
database: clickhouse

**Comment by sfirke** [comment]
Thanks.  I don't have a solution unfortunately.  You might try searching Github issues for "time" and "clickhouse", there are a few issues that seem to be clickhouse-specific.  And if you're able to test this issue on 2.1.0 or (even better) latest master branch commit to see if it persists, that would be helpful.

**Comment by round3d** [comment]
I'll confirm that this works correctly with latest with this in my config

``` python
DEFAULT_TIME_FILTER = "Last day"
```

superset: latest-dev (docker)
database: clickhouse  23.8.2.7 (23.8 LTS)
clickhouse-connect     0.6.11

A new chart shows correctly generated 
![image](https://github.com/apache/superset/assets/3385802/e97cf762-690c-4a38-8144-08bbb3bc2690)

**Comment by rusackas** [comment]
It sounds like this is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue with updated context or a PR to address the problem. Thanks!
