### ISSUE TITLE
Default credentials don't work with Digital Ocean Apps Docker Hub deployment

### ISSUE THREAD

**Issue by maciejtrybilo** [apache/superset#24566]
#### How to reproduce the bug

1. Start creating an App on Digital Ocean
2. Pick Docker Hub and enter `apache/superset` as the Repository and keep the Tag as `latest`
3. Add the SUPERSET_SECRET_KEY environment variable in the component Environment Variables
4. Set the HTTP Port to 8088
5. The app deploys successfully
6. On the login page enter admin:admin for username and password

### Expected results

Logged in

### Actual results

The page displays the "Invalid login. Please try again." error

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sfirke** [comment]
Did you follow the steps here to create an admin user?  https://hub.docker.com/r/apache/superset

**Comment by maciejtrybilo** [comment]
Ah, the image itself doesn't set everything up. I'll use a droplet anyway. Thank you!
