### ISSUE TITLE
Ability to support indian numbering system

### ISSUE THREAD

**Issue by sahoss** [apache/superset#24562]
## Screenshot

[drag & drop image(s) here!]

## Description
Indian numbering system has numbers such as [lakh](https://en.wikipedia.org/wiki/Lakh)(100,000), [crore](https://en.wikipedia.org/wiki/Crore) (10,000,000) etc 

This issue is to check if there is already a support for formatting numbers in this way in superset. if not, what would it take to do so? is it a concern of superset or of the d3-format library? 

PS: I'd like to contribute the code to implement this feature, if it doesnt exist yet :)

[describe the issue here!]

## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

**Comment by Raymanrrr** [comment]
I guess the new option D3_FORMAT in superset_config.py on the master branch can set the number format to Indian locale,

how ever, even if it's implemented, d3-format looks like have some limitations:

Can not format two columns with different currency prefixes.
Some regions do not use large number suffixes such as 'G' or 'M' , but insted use large number suffixes in their local language.

**Comment by rusackas** [comment]
Closing this as stale, and because it's more feature request than bug... but that said, the situation HAS improved since this thread was touched. You can now add currency prefix/suffix in many spots, and you can also implement these numbering systems in config. If this needs further improvement, we're open to PRs and proposals on Github Discussions

![Uploading image.png…]()

**Comment by himanshudube97** [comment]
Hi @Raymanrrr @rusackas  , did this feature request to include the Indian Number formats got processed? I am facing the issue  where I want to show a number in Indian format eg 3.2 crore OR 4lakhs , but superset or specifically the d3.js dosent support this. So any suggestions?
