### ISSUE TITLE
ModuleNotFoundError: No module named 'bleach' - latest-dev tag (docker image)

### ISSUE THREAD

**Issue by seminip** [apache/superset#24589]
Using docker to run Apache Supset locally. No issue with other tags such as 2.1.0
But getting this error (following screenshot shows logs of superset-init container) for latest-dev tag:
![image](https://github.com/apache/superset/assets/138104778/d57841fa-beff-40ff-9791-79628ffba850)
Sorry first time opening a ticket.

**Comment by matheusbsilva** [comment]
@seminip what was the solution?

**Comment by seminip** [comment]
> @seminip what was the solution?

It got fixed when I completely removed the docker images, associated volumes, and pulled and upped everything again. I also cloned a fresh superset repository and ran npm ci locally as well in superset-frontend.

**Comment by roxxrroy** [comment]
Hello @seminip ,
I am doing these step to first clone,install and run the superset code repo in my local system -

git clone https://github.com/apache/superset.git
cd superset
git checkout 2.1.0
docker-compose up

but i am getting error that - superset_worker | ModuleNotFoundError: No module named 'bleach'

Even i asked question here on below link -
 https://stackoverflow.com/questions/76668038/facing-issue-in-installation-of-superset2-1-0-for-creating-visualization-plug

**Comment by seminip** [comment]
Hi @roxxrroy 
Can you try these steps:

go to superset-frontend folder and remove your node modules if you have them.
`rm -rf node_modules`
then install node modules using:
`npm ci`

Then:
```
docker-compose down -v
docker-compose build --no-cache
docker-compose up -d --force-recreate
```

**Comment by roxxrroy** [comment]
Thanks a lot  @seminip Above Steps worked  ,FInally  i was able to open the Superset dashboard in development mode.Now i can proceed with my development work.

**Comment by seminip** [comment]
> Thanks a lot @seminip Above Steps worked ,FInally i was able to open the Superset dashboard in development mode.Now i can proceed with my development work.

No worries, glad to help! Also, hope you don't mind if I post the answer in your stackoverflow link as well (over there, my username is Jolly Good)

**Comment by roxxrroy** [comment]
Yes sure, please add your answer there as well.

**Comment by m-usai-almaviva** [comment]
For others getting here from google, the solution for me was adding `TAG=2.1.0` before any `docker compose up` command.

From [Here](https://github.com/apache/superset/discussions/24721#discussioncomment-6472104)

**Comment by alephpt** [comment]
none of the above worked for me on 2.1.1 or 2.1.0
