### ISSUE TITLE
Unable to build for linux/arm64 architecture

### ISSUE THREAD

**Issue by rodmaz** [apache/superset#24591]
When building a multi-architecture Docker image of Superset (v2.1.0) for architectures `linux/amd64` and `linux/arm64`, the latter fails.  

#### How to reproduce the bug

Build a multi-architecture version of Superset:

```[shell]
  docker buildx build \
    --platform linux/amd64,linux/arm64 \
    --tag apache/superset:2.1.0 \
    --load ./source
```

### Actual results

```
#0 4683.1 npm notice 
#0 4683.1 npm notice New major version of npm available! 8.19.4 -> 9.7.2
#0 4683.1 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.7.2>
#0 4683.1 npm notice Run `npm install -g npm@9.7.2` to update!
#0 4683.1 npm notice 
#0 4683.3 npm ERR! code 1
#0 4683.3 npm ERR! path /app/superset-frontend/node_modules/@parcel/watcher
#0 4683.4 npm ERR! command failed
#0 4683.4 npm ERR! command sh -c -- node-gyp-build
#0 4683.4 npm ERR! gyp info it worked if it ends with ok
#0 4683.5 npm ERR! gyp info using node-gyp@9.3.1
#0 4683.5 npm ERR! gyp info using node@16.20.1 | linux | arm64
#0 4683.5 npm ERR! gyp ERR! find Python 
#0 4683.5 npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
#0 4683.5 npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
#0 4683.5 npm ERR! gyp ERR! find Python checking if "python3" can be used
#0 4683.5 npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
#0 4683.5 npm ERR! gyp ERR! find Python checking if "python" can be used
#0 4683.5 npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
#0 4683.5 npm ERR! gyp ERR! find Python 
#0 4683.5 npm ERR! gyp ERR! find Python **********************************************************
#0 4683.5 npm ERR! gyp ERR! find Python You need to install the latest version of Python.
#0 4683.5 npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#0 4683.5 npm ERR! gyp ERR! find Python you can try one of the following options:
#0 4683.5 npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#0 4683.5 npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
#0 4683.5 npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
#0 4683.5 npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
#0 4683.5 npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#0 4683.5 npm ERR! gyp ERR! find Python For more information consult the documentation at:
#0 4683.5 npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#0 4683.5 npm ERR! gyp ERR! find Python **********************************************************
#0 4683.5 npm ERR! gyp ERR! find Python 
#0 4683.5 npm ERR! gyp ERR! configure error 
#0 4683.5 npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
#0 4683.5 npm ERR! gyp ERR! stack     at PythonFinder.fail (/app/superset-frontend/node_modules/node-gyp/lib/find-python.js:330:47)
#0 4683.5 npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/app/superset-frontend/node_modules/node-gyp/lib/find-python.js:159:21)
#0 4683.5 npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/app/superset-frontend/node_modules/node-gyp/lib/find-python.js:202:16)
#0 4683.5 npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/app/superset-frontend/node_modules/node-gyp/lib/find-python.js:294:16)
#0 4683.5 npm ERR! gyp ERR! stack     at exithandler (node:child_process:410:5)
#0 4683.5 npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:422:5)
#0 4683.5 npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
#0 4683.5 npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
#0 4683.5 npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:485:16)
#0 4683.5 npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
#0 4683.5 npm ERR! gyp ERR! System Linux 5.15.49-linuxkit-pr
#0 4683.5 npm ERR! gyp ERR! command "/usr/local/bin/node" "/app/superset-frontend/node_modules/.bin/node-gyp" "rebuild"
#0 4683.5 npm ERR! gyp ERR! cwd /app/superset-frontend/node_modules/@parcel/watcher
#0 4683.5 npm ERR! gyp ERR! node -v v16.20.1
#0 4683.5 npm ERR! gyp ERR! node-gyp -v v9.3.1
#0 4683.5 npm ERR! gyp ERR! not ok
#0 4683.6 
#0 4683.6 npm ERR! A complete log of this run can be found in:
#0 4683.6 npm ERR!     /root/.npm/_logs/2023-07-05T01_42_21_425Z-debug-0.log
------
Dockerfile:37
--------------------
  35 |     
  36 |     COPY superset-frontend/package*.json ./
  37 | >>> RUN npm ci
  38 |     
  39 |     COPY ./superset-frontend .
--------------------
ERROR: failed to solve: process "/bin/sh -c npm ci" did not complete successfully: exit code: 1
```

### Environment

- superset version: [2.1.0](https://github.com/apache/superset/releases/tag/2.1.0)
- macOS 13.4.1
- Docker version 24.0.2, build cb74dfc

**Comment by lekhanhtoan37** [comment]
Any solution ?

**Comment by MB1967** [comment]
Still same.
Error communicating with plugin service. Please try again later.
But I think problem is when I choose the Scholar AI.

Regards

***@***.***
0000-0001-6534-9252
TTG Uluslararası Ltd
keep smiling we are here to help
http://www.ttgint.com<blocked::blocked::http://www.ttgint.com/>
+ 90 (0) 850 800 0884
+ Fax:+90 216 4295749
Mobile: +90 542 698 8446
Address
Resadiye Mah. Resadiye Cad. No:110/1 Cekmekoy 34799 Istanbul -Turkey
 ***@***.******@***.***>
Disclaimer
This message and attachments are confidential and intended solely for the individual(s) stated in this message.  If you received this message although you are not the addressee you are responsible to keep the message confidential. The sender has no responsibility for the accuracy or correctness of the information in the message and its attachments. Our company shall have no liability for any changes or late receiving, loss of integrity and confidentiality, viruses and any damages caused in anyway to your computer system.

Bu mesaj ve ekleri mesajda gonderildigi belirtilen kisi/kisilere ozeldir ve gizlidir.Bu mesajin muhatabi olmamaniza ragmen tarafiniza ulasmis olmasi halinde mesaj iceriginin gizliligi ve bu gizlilik yukumlulugune uyulmasi zorunlulugu tarafiniz icin de soz konusudur. Mesaj ve eklerinde yer alan bilgilerin dogrulugu ve guncelligi konusunda gonderenin ya da sirketimizin herhangi bir sorumlulugu bulunmamaktadir. Sirketimiz mesajin ve bilgilerinin size degisiklige ugrayarak veya gec ulasmasindan, butunlugunun ve gizliliginin korunamamasindan, virus icermesinden ve bilgisayar sisteminize verebilecegi herhangi bir zarardan sorumlu tutulamaz.

**Comment by myangw** [comment]
When running superset in arm64 machine I also got an error. My error log was different, but hope this helps:
* turn 'use Rosetta' option on (update my macOS to 13.x or more if needed) and then build superset docker image. (I use Orbstack instead of docker desktop)
![image](https://github.com/apache/superset/assets/26712339/5df9c271-7686-4d37-ac13-beecc6007ab7)

- I did this because it seems superset only provides images for amd64. (https://hub.docker.com/r/apache/superset/tags)

**Comment by sebaxtian** [comment]
Hello @rodmaz I created this Superset image for arm64 architecture:

https://hub.docker.com/r/sebaxtian/superset-arm64

I tested it on my Raspberry Pi 4 and it works well,

Let me know if that image works for you.

🚀

**Comment by rusackas** [comment]
Most of the docker workflows have been revamped (thanks @mistercrunch) and I believe this has largely been resolved on current versions.

**Comment by mistercrunch** [comment]
Yup all of our official builds are multi-platform now (arm + amd)
