### ISSUE TITLE
Swagger API page is empty

### ISSUE THREAD

**Issue by last-Programmer** [apache/superset#24616]
After deploying superset in docker, the swagger page(/swagger/v1) displayed nothing except the superset menu header.
The configuration FAB_API_SWAGGER_UI has been set to True in config.py.

Expected results
All superset APIs should be listed.

Actual results
An empty page.

How to reproduce the bug
Go to https://host:port/swagger/v1
An empty page was displayed

**Comment by michael-s-molina** [comment]
@kgabryje I checked and it seems CSP is blocking the Swagger inline scripts.

**Comment by dpgaspar** [comment]
Thank you for reporting this issue. A fix was done on FAB to support nonce's also, currently release on 4.3.4rc1. Hope to publish a final release soon

**Comment by dpgaspar** [comment]
FAB 4.3.4 is out and considered a new minor version on Superset

**Comment by mtthsbrr** [comment]
Hi. I still get an empty page for /swagger/v1 when using the latest-dev image. I built from that image 6 days ago. Any help would be appreciated.

**Comment by Stefan781** [comment]
As of 3.0.0, I also get an empty page.

**Comment by Stefan781** [comment]
Disabling Talisman fixed this issue for me. I am not sure how the two should be related. Logging in as the administrator from the UI should give you access to Swagger's UI.

**Comment by dpgaspar** [comment]
> Disabling Talisman fixed this issue for me. I am not sure how the two should be related. Logging in as the administrator from the UI should give you access to Swagger's UI.

Talisman sets CSP that is currently preventing a swagger css and a js code block from running

**Comment by kevinverelst** [comment]
I still have an empty page with v3.0.0. Should I still need to disable Talisman for this?
