### ISSUE TITLE
Queries that exceed 10 seconds result in unexpected errors.

### ISSUE THREAD

**Issue by xddpool** [apache/superset#24622]
#### How to reproduce the bug
When accessing Superset remotely through the public IP, I encounter an issue while creating a new chart. It only allows queries within 10 seconds, and if it exceeds 10 seconds, it displays an "Unexpected error".

I have deployed Superset on Linux using Docker, and it worked fine when tested locally. However, when accessing it remotely through the router's forwarded public IP, I encounter this issue. The sample dashboards and permission features of Superset work without any problems. The issue only occurs when creating a new chart and the query takes longer than 10 seconds, it throws an error (without any specific error code). But when I refresh the page, the query results are displayed, and the console shows everything is normal without any relevant error logs.

Expected results
To see the preview of query results.

Actual results
Unexpected error
And after refreshing the page, I get the results.
I tried the same query in SQL Lab and encountered the same results.

The following are the configurations I have overridden in the superset_config.py file:

SESSION_COOKIE_HTTPONLY = True # Prevent cookie from being read by frontend JS?
SESSION_COOKIE_SECURE = False # Prevent cookie from being transmitted over non-tls?
SESSION_COOKIE_SAMESITE = "Lax"

TALISMAN_ENABLED = False

SESSION_PROTECTION = "basic"

#### Screenshots
error
![1231231231](https://github.com/apache/superset/assets/88379635/7d5f28e9-df23-4580-98bc-a61e3758e8ed)

click update chart
![1243131weq](https://github.com/apache/superset/assets/88379635/3ea4d0bb-19ca-4643-bf82-f66c0b2f13b3)

![WX20230708-145717@2x](https://github.com/apache/superset/assets/88379635/ddb4c644-4cf9-4ebb-a0e5-32e8f66ea7d7)

### Environment
centOS7
docker 

- browser type and version:chorme
- superset version: latest-dev

**Comment by rusackas** [comment]
Are you still facing this issue in 3.x? What are you using as your web server, and what do you see in the logs? Hard to tell where the timeout is happening exactly, from this.

**Comment by rusackas** [comment]
Still unsure if you were/are facing this in 3.0, but it's been long enough that we're really only supporting 4.x upon the imminent release of 4.1. I'll close this as stale, but if you face it in 4.x, let us know and we're more than happy to reopen it.
