### ISSUE TITLE
 superset breaks down when i try to build own docker image with custom css style and custom 404 and 500 pages.

### ISSUE THREAD

**Issue by Nello-Angelo** [apache/superset#24639]
FROM apache/superset:2.1.0

COPY permission.json /app/configs/
COPY assets/loading.gif assets/*.png /app/superset/static/assets/images/
COPY assets/loading.cff8a5da..gif assets/theme.5fb6aaa7430ffb2cbd6c.entry.css assets/500.html assets/404.html /app/superset/static/assets/

RUN pip install dbt-greenplum && \ 
    pip install pymssql && \ 
    pip install hdbcli sqlalchemy-hana && \ 
    pip install clickhouse-connect && \ 
    pip install pyhive && \ 
    pip install mysqlclient && \ 
    pip install cx_Oracle && \ 
    pip install psycopg2 && \ 
    pip install teradatasqlalchemy && \ 
    pip install sqlalchemy-vertica-python && \
    pybabel compile -d superset/translations; exit 0

App breaks down when i try to login in superset

![Screenshot_2](https://github.com/apache/superset/assets/82488489/da8aa90a-2736-4947-8942-f7c35f58f542)

[superset-dockerfile.zip](https://github.com/apache/superset/files/12005888/superset-dockerfile.zip)

**Comment by Nello-Angelo** [comment]
I figured out why this happens - it's because the superset works in more than one replica

**Comment by mounikaberrybox** [comment]
Im getting the same issue when i  try to run locally.  The code before 2 months worked fine but not now
