### ISSUE TITLE
column formatting return wrong time

### ISSUE THREAD

**Issue by victortony** [apache/superset#24637]
#### How to reproduce the bug

1. click on "create chart"
2. choose "table" charttype
3. generate a query with time column

My time column  called “partition_time”  which format is "%Y%m%d%H"。The time filter get the right time formatting, but  the result of time column is wrong formatting, which converted "2023071000" to "1970-01-24 09:57:51". The actual result is 2023071000, like the pic below:
<img width="244" alt="image" src="https://github.com/apache/superset/assets/13748044/c9a56f83-5364-45d2-8bb1-667c5a0569c7">

### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `2.0.1`
- python version: `3.8`
- node.js version: `v6.17.1`
- any feature flags active:
datasource: clickhouse
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by yousoph** [comment]
Hi @victortony ! 

The setting that you selected (Formatted Date and Original Date) is for the Results table at the bottom of the page. 

If you'd like to format the time column in the table, use the Customize panel in Explore / Chart Builder, and select the date format in the Customize Columns section: 
![image](https://github.com/apache/superset/assets/10627051/657b93da-f292-4d33-ba94-55de6b22fc02)
