### ISSUE TITLE
Can queries initiated through chart can be recorded in historical records

### ISSUE THREAD

**Issue by yehaotong** [apache/superset#24678]
I want to record the query records initiated by each user through chart to track some non-standard queries, but I haven't found any historical records of chart queries anywhere. Can this be achieved？

**Comment by yehaotong** [comment]
I find that queries run in [SQL Editor] can recorded to the Query History screen. But I run query on chart no query records appear on the Query History screen. Can this be recorded？

**Comment by rusackas** [comment]
Nope, I don't think so... but we're open to technical proposals and/or PRs!

**Comment by rusackas** [comment]
Just closing this since it's a feature request / Q&A thing. We're trying to whittle back to bugs only :)
