### ISSUE TITLE
Facing Database driver error while connecting with snowflake from superset

### ISSUE THREAD

**Issue by tpatni** [apache/superset#24695]
https://drive.google.com/file/d/1vklt_Tu246kZ4i4RamaVd46r9r5FKbv_/view?usp=sharing
anyone can help in resolving this issue?

**Comment by sebastianliebscher** [comment]
Hi @tpatni, please don't just drop a link but instead try to describe your issue here with the help of the bug report template. Thank you!

**Comment by rusackas** [comment]
Whatever that doc is you've linked to, it's private. 

I agree with @sebastianliebscher - there's nothing to act on. Lots of folks are using Snowflake with success, so if we don't have repro steps, we'll be forced to close this.

**Comment by laurafroelich** [comment]
I have access to a Snowflake account with a database and warehouse that I can query through Python, but I get the error "ERROR: Could not load database driver: SnowflakeEngineSpec" when trying to add the database in Superset. 

I used the connection string specified at https://superset.apache.org/docs/databases/installing-database-drivers/ (snowflake://{user}:{password}@{account}.{region}/{database}?role={role}&warehouse={warehouse}), substituting in the correct values. 

I have apache-superset==2.1.1, snowflake-connector-python==2.9.0 and snowflake-sqlalchemy==1.2.4 installed.

**Comment by rusackas** [comment]
@laurafroelich are you still experiencing this in Superset 3.x? If so, can you post it as a new issue? I'm closing this one out due to lacking details in the intail report. Hopefully we can follow up on your more actionable details if the issue still exists.

**Comment by laurafroelich** [comment]
@rusackas Thank you for looking at this and your reply. I ended up getting it to work with this connection string format: snowflake://{user}:{password}@{account}.{region}/{database}, i.e. dropping the parts after '?'. I forgot to come back here and report this, sorry for the inconvenience.
