### ISSUE TITLE
Can Gamma role user configure Alerts & Reports for Dashboards he has access to ?

### ISSUE THREAD

**Issue by nandanalluri** [apache/superset#24720]
We are  Integrating SS Dashboards in the UI application and assigned "Gamma" role to the Application users for viewing the dashboards. Everything works great and we want to provide "Alerts & Reports" capabilities to the application users for scheduling alerts and reports of the dashboards/charts of their choice. 
1. Right now i see "Alerts & Reports " for Admin users under settings menu. How can i show this at chart level ? 
2. How can i enable this for "Gamma" role users ?

I really appreciate your inputs on this.

Thanks

**Comment by Valinaa** [comment]
1. I'm not clear what `show at chart level` is, just only for charts? There doesn't seem to be such a classification in permission.
2. It's not recommended to edit the default role, you can add a new role such as `Alert` and give it the `Alerts & Reports` permission, and set the user with "Gamma" and "Alerts" roles finally.

**Comment by nandanalluri** [comment]
Thanks for the Details. But currently "Alerts & Dashboards" are available at Dashboard level. In my use case, I want to use it for Specific charts and not for all the charts in the Dashboard.

**Comment by Valinaa** [comment]
`Alerts & Reports` obtains the corresponding dashboard or chart list through the interface `/api/v1/report/related/{columnname}`, which is located in `/superset/views/base_api`. It filters data through specified filters, as shown in the figure below. 

![image](https://github.com/apache/superset/assets/102314964/fecc9357-b847-4b00-9780-12b8c2a23650)
![image](https://github.com/apache/superset/assets/102314964/4b24d835-5497-45e5-be60-47a046d1b20d)

Perhaps you can customize constraints in these filters or lambda to implement your ideas.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and is a feature request rather than a bug. If anyone is considering contributing this or finding someone who is, please open a new Ideas discussion or a PR to address the problem.
