### ISSUE TITLE
Error thrown when corrupted native dashboard filter metadata referencing obsolete filter ID

### ISSUE THREAD

**Issue by john-bodley** [apache/superset#24729]
The dashboard native filters throws an unexpected error due to corrupted dashboard metadata.

#### How to reproduce the bug

Currently we're uncertain how the metadata becomes corrupted, though it likely occurs when people delete a filter. The issue surfaces when a the `cascadeParentIds` array references an ID which is not associated with any filters, e.g.

```
{
    "native_filter_configuration": [
        {
            "id": "NATIVE_FILTER-4vk933fy2",
            "cascadeParentIds": [
                "NATIVE_FILTER-Fvk_h6yN"
             ],
             ...
        }
    ]  
}
```

Removing the hanging `NATIVE_FILTER-Fvk_h6yN` reference remedies the issue.

### Expected results

The `cascadeParentIds` array should only contain the IDs of currently defined filters.

### Actual results

An error is thrown.

#### Screenshots

![error](https://github.com/apache/superset/assets/4567245/d6dc37b7-f729-4985-92e1-29d191158c8c)

### Environment

(please complete the following information):

- browser type and version: Chrome 114.0.5735.198
- superset version: `master`
- python version: `3.9`
- node.js version: `16`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by michael-s-molina** [comment]
Closed by https://github.com/apache/superset/pull/24749
