### ISSUE TITLE
[SIP-101] Decouple Service and Container port to support adding reverse proxy 'sidecar'

### ISSUE THREAD

**Issue by abelstam12** [apache/superset#24727]
*Please make sure you are familiar with the SIP process documented*
(here)[https://github.com/apache/superset/issues/5602]. The SIP will be numbered by a committer upon acceptance.

### Motivation

To efficiently serve the static files, the use of a reverse proxy http server is possible with the extraContainers value and a shared volume between the two containers. The problem is that the service forwards traffic to the superset port (Values.service.port) on the POD. To allow the nginx sidecar to serve traffic and split between static and the supersetNode container, the service needs to serve traffic on the nginx port of the POD.

### Proposed Change
I propose the values.service.port gets decoupled from the newly introduced supersetPort value. The supersetPort value will be used in the deployment.yaml to set the containerPort and SUPERSET_PORT env variable, whereas the values.service.port will be used to point to the port that should be used as the http interface. To avoid breaking changes maybe the supersetPort can default to the service.port?

### New or Changed Public Interfaces
-

### New dependencies
-

### Migration Plan and Compatibility
-

### Rejected Alternatives
-

Happy to open a PR!

**Comment by abelstam12** [comment]
@rusackas @craig-rueda is there an idea on the timeline for this sip? Would it speed things up if I open a PR?

Cheers

**Comment by craig-rueda** [comment]
Not sure this needs to be a SIP. Pls feel free to update the containerPort in the `service` definition to reference a separate value (it's currently hard-coded to point at `http`).
