### ISSUE TITLE
Really small icons on Explore

### ISSUE THREAD

**Issue by michael-s-molina** [apache/superset#24730]
Text and number icons are way smaller than time icons

#### How to reproduce the bug

1. Go to Explore
2. You'll see that text and number icons are way smaller than time icons

### Expected results

Both text and number icons are adjusted to match the time icon size.

### Actual results

Text and number icons are unreadable.

#### Screenshots

<img width="635" alt="Screenshot 2023-07-18 at 15 33 27" src="https://github.com/apache/superset/assets/70410625/11e0cc0b-eee9-4160-a330-ce99fd49c681">

### Environment
- browser type and version: Chrome
- superset version: master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by eschutho** [comment]
@michael-s-molina were you able to repro this locally?

**Comment by eschutho** [comment]
@michael-s-molina This should also change the underlying issue from the svgr bump: https://github.com/apache/superset/pull/24747
