### ISSUE TITLE
"Rich tooltip" no longer highlights hovered-over data series in stacked barchart

### ISSUE THREAD

**Issue by stitheridge** [apache/superset#24738]
The "rich tooltip" that lists all the series in a stacked bar chart when hovering over a column no longer highlights the series the mouse pointer is hovering over. This makes it very hard to identify which series the user is looking at and what the value is. This behaviour has changed between version 2.1.0 and the "latest" docker image. I assume this is not a deliberate change as it is a loss of usability for stacked bar charts.

#### How to reproduce the bug

1. For a stacked bar chart with "Rich tooltip" option enabled, hover pointed over a chart data item in a stacked column
2. Observe the tooltip with listing of each data series in the column and the amounts for each for that column

### Expected results

The data series listed in the tool tip is highlights text describing the series that the pointer is hovering over to differentiate it from the other series

### Actual results

Each data series listed in the tool tip is presented the same way, without differentiating between the series that the pointer is hovering over and all the other series.

#### Screenshots
Latest behaviour (incorrect):
![latest](https://github.com/apache/superset/assets/13503413/e15951e3-9002-43fd-9831-e48c93da5977)

2.1.0 behaviour (correct):
![2 1 0](https://github.com/apache/superset/assets/13503413/44993a2f-1435-4e35-9315-603d72d126ea)

Sorry, mouse pointer was not captured by the screenshot. It is actually hovering over the "DairyEggs" series in each case.

### Environment
- Chrome 114.0.5735.198 (Linux)
- superset version: Docker apache/superset:aa01b51177a59dd0dcf4e66221a58e2331591716
- python version: As per docker image
- node.js version: As per docker image
- any feature flags active: None

**Comment by michael-s-molina** [comment]
Thank you so much for the detailed description @stitheridge! I assigned this ticket to myself and will try to fix it for 3.0.
