### ISSUE TITLE
Asset import/export functionality, role and cross-filter are still ID-based, not uuid-based.

### ISSUE THREAD

**Issue by enzo-dechaene** [apache/superset#24743]
I have two Superset, one for the testing environment where I have two datasets (**indicator-monthly [id:1]** and **indicator-daily [id:2]**).
I do an asset export from the testing Superset and import on the second environment. But it seems that the id of my datasets has changed to **indicator-daily [id:1]** and **indicator-monthly with [id:2**]

If I do an export and import in the first environment, the identifier doesn't change.
I don't know the process but it seems that some content are based on uuid but not this one.

#### How to reproduce the bug

1. Create the dataset **indicator-monthly** and then the dataset **indicator-daily** on the first instance of Superset
2. Then export it with the api **/api/v1/assets/export**
3. Import the previous dataset on the new Superset with the api **/api/v1/assets/import** 
4. Finally, go to **Settings > List roles > edit a role > check permission** with datasource access

### Expected results

what you expected to happen.

![image](https://github.com/apache/superset/assets/107003976/5d10dcee-ff7a-4770-91ce-b6440f407999)

### Actual results

what actually happens.

![image](https://github.com/apache/superset/assets/107003976/5c588e4c-f583-4be4-adb1-2d3bb90b0547)

### Environment

(please complete the following information):
- installation type: **helm chart 0.6.5**
- browser type and version: **Brave Version 1.52.130 Chromium: 114.0.5735.198 (Build officiel)  (64 bits)**
- superset version: **2.1.0**
- python version: **3.8.16**
- any feature flags active:
>         dashboard_feature: |
>          FEATURE_FLAGS = {
>            "EMBEDDED_SUPERSET": True,
>            "ENABLE_TEMPLATE_PROCESSING": True,
>            "DRILL_TO_DETAIL": True,
>            "HORIZONTAL_FILTER_BAR": True,
>            "DASHBOARD_CROSS_FILTERS": True
>          }

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Hi there... sorry this hasn't seen much activity. Can you confirm if this is still an issue in Superset 3.x?

**Comment by rusackas** [comment]
I believe this relates to the UUID SIP here: https://github.com/apache/superset/issues/27194

Really, we should be using UUIDs everywhere. Closing this since it's not being perceived as a bug, but any contribution toward this _improvement_ is more than welcome!
