### ISSUE TITLE
fetchGuestToken callback running in an Infinite Loop.

### ISSUE THREAD

**Issue by fir0j** [apache/superset#24765]
- I'm using superset `@superset-ui/embedded-sdk` npm package in react to embed superset dashboard.
- What I found is that, once the dashboard is rendered into the page by invoking `embedDashboard({})` like so
  ```jsx
   useEffect(() => {
    embedDashboard({
      id: "superset-dashboard-id", // given by the Superset embedding UI
      supersetDomain: "https://superset-bas-dev.bridge.propelmarine.com",
      mountPoint: document.getElementById("superset-container") as HTMLElement, // any html element that can contain an iframe
      fetchGuestToken: async () => {
        console.log("fetchGuestToken");
        return guestToken;
      },
      dashboardUiConfig: {
        // dashboard UI config: hideTitle, hideTab, hideChartControls, filters.visible, filters.expanded (optional)
        hideTitle: true,
        filters: {
          expanded: false,
        },
      },
    });
  }, []);
   ```
then fetchGuestToken is being called infinitely, which i expect it to be called only once.

#### How to reproduce the bug

1. Go to 'https://codesandbox.io/p/sandbox/dazzling-rain-p4qcjc'
2. Click on 'new tab icon of code-sandbox's browser to open in new tab'
3. Open the console of that new tab
4. You will see "fetchGuestToken" being logged infinitely.

### Expected results
The Dashboard should be rendered without running fetchGuestToken callback infinitely.

what you expected to happen.
The `fetchGuestToken` callback should be called only once, instead of infinitely.

### Actual results
The `fetchGuestToken` callback  is being called infinitely, which i see as  a problem.

#### Screenshots
[Bug-image](https://drive.google.com/file/d/1tUS4gCGka4teoqfmfM5Ben1xxhUD8YUl/view)

**Comment by huamichaelchen** [comment]
I suspect the infinite loop bit is because of `useEffect(() => {}`. Because that runs on each rendering. 

In terms of getting the embedded dashboard to work, that is more involved. There are a lot stuff have to be considered, the superset configuration, the proxy configuration if your superset is sitting behind a proxy, and the backend to fetch a guest token which passes along to the frontend which invokes the backend to get the token. 

Wrote a guide on it, hopefully, it helps someone 😄 Choose your preferred media 😝

https://huamichaelchen.substack.com/p/end-to-end-example-of-setting-up

https://medium.com/@huamichaelchen/end-to-end-example-of-setting-up-superset-embedded-dashboard-f72fc985559

**Comment by rusackas** [comment]
Hopefully, the answer above is sufficient to close this thread. I'll do so anyway since it's been so long since there was a comment here. If this needs revisiting/reopening, just say the word.

**Comment by bronz3beard** [comment]
not great practice in react but this could be a solution, less involved than the above suggestion.

```
import { useEffect, useRef } from 'react';

const useEffectOnce = (effect: () => void) => {
  const hasRun = useRef(false);

  useEffect(() => {
    if (!hasRun.current) {
      hasRun.current = true;
      return effect();
    }
  }, [effect]);
};

export default useEffectOnce;

```


```
useEffectOnce(() => {
  embedDashboard({
    id: "superset-dashboard-id", // given by the Superset embedding UI
    supersetDomain: "https://superset-bas-dev.bridge.propelmarine.com",
    mountPoint: document.getElementById("superset-container") as HTMLElement, // any html element that can contain an iframe
    fetchGuestToken: async () => {
      console.log("fetchGuestToken");
      return guestToken;
    },
    dashboardUiConfig: {
      // dashboard UI config: hideTitle, hideTab, hideChartControls, filters.visible, filters.expanded (optional)
      hideTitle: true,
      filters: {
        expanded: false,
      },
    },
  });
});
```
