### ISSUE TITLE
Missing groupby and no Groupby option while creating charts

### ISSUE THREAD

**Issue by sandeeppennant** [apache/superset#24763]
![Uploading Superset_Chart_Groupby.png…]()
While creating the chart not getting Group by option under query

**Comment by sandeeppennant** [comment]
![Uploading Superset_Chart_Groupby.png…]()

**Comment by rusackas** [comment]
Sorry, thos images don't work, and I think this (pretty stale) issue is from a no-longer-supported version of Superset. If you're still facing this in 3.x let us know and we'll do our best to reopen/revisit this as needed.
