### ISSUE TITLE
Issue of adding the new plugin in dashboard of development mode

### ISSUE THREAD

**Issue by htvenkatesh** [apache/superset#24778]
Hi, I am facing these issues in the development mode of superset
**Issue 1 :** After adding the new plugin into the development environment, able to create the charts but after saving it is showing the unexpected error of plugin not registered.
![image](https://github.com/apache/superset/assets/68595990/3c9ff197-91b0-4dda-9984-f366df3f68c9)

**Issue 2 :** I am not able to save the dashboard for frontend ( http://localhost:9000 ) in development environment after editing getting the below showed screenshot error, 
![image](https://github.com/apache/superset/assets/68595990/0f36405b-6f58-471f-b203-20a6cdc7e6d5)
and the API put method is throwing 400 error
![image](https://github.com/apache/superset/assets/68595990/716dabcd-10d5-4023-9130-056fcb2fd144)

**Comment by rusackas** [comment]
Sounds like you didn't register your plugin in Superset, in the MainPreset.js file. This isn't a bug with Superset, and has gone quiet for quite some time, so I'll close it as stale. I hope you found a way forward! 🤞
