### ISSUE TITLE
Can note EDIT Dashboard on Version 2.1

### ISSUE THREAD

**Issue by DHaiDang** [apache/superset#24775]
## Screenshot

[drag & drop image(s) here!]
<img width="1722" alt="image" src="https://github.com/apache/superset/assets/50817453/3e754268-4a1a-45f6-843f-961d2b427f1d">

## Description

After i Click Edit Dashboard. I can not see any button for save the dashboard. And add exsiting chart to the dashboard. 
I install git clone https://github.com/apache/superset.git and run docker-compose-non-dev.yaml with branch master.

Anyone can help. Thank alot

**Comment by sfirke** [comment]
If you are running off master branch, that would default to `latest` commit, not 2.1.0.  Did you first run `latest`, then switch the image to 2.1.0?  Someone else had this problem when they did the same thing: https://github.com/apache/superset/issues/24685#issuecomment-1639910245

If you can afford to lose the dashboards and users you've created, you could reset your database (by deleting the container volumes, if you're using the PostgreSQL container as your metadata database).

**Comment by rusackas** [comment]
Since we're now on 3.1, on the verge of 4.0, we're not supporting 2.x  or prior versions actively. If anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)
