### ISSUE TITLE
bug: Hive `async` kwarg unexpected keyword when connecting to Databricks Unity Catalog

### ISSUE THREAD

**Issue by alldoami** [apache/superset#24786]
Hello! I'm currently getting an error from this line: https://github.com/apache/superset/blob/master/superset/db_engine_specs/hive.py#L548 when running a query in sqllab against a databricks unity catalog table. The error is in the screenshot. I think the `async` kwarg might be outdated and may have been referenced in one of the installed packages on an older version, but now it is no longer recognized. Wondering if I need to pin a package to an older version but I'm not sure how to find which package is implementing `execute` and which version it should be on. I'm on all the required versions by superset (https://github.com/apache/superset/blob/master/requirements/base.txt)

#### How to reproduce the bug

1. Create a Databricks unity catalog database connection (right now I have all permissions allowed on the tables so it's not a permissions issue)
2. Try to query any table from unity catalog
3. Find logs in kubernetes pods that show the above description

### Expected results

Connect to Databricks Unity Catalog and display data.

### Actual results

Unable to show results from the tables.

#### Screenshots

![image](https://github.com/apache/superset/assets/16328889/07be54ac-5628-4dc0-9ced-77c14b3e955a)

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: building image off of this [sha](https://hub.docker.com/layers/apache/superset/abb8e28e4914ad46ef50e33934ec97c1e8fcf5b4/images/sha256-2876555bbb7773c5e1dfc5149ab1d150edce668189e741d3816089610a4e2895?context=explore)
- python version: `Python 3.9.17`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by alldoami** [comment]
I am believing that one of the python packages has a breaking change. Here is my pip freeze:
```
# Editable install with no version control (apache-superset==0.0.0.dev0)
-e /app
Babel==2.9.1
Brotli==1.0.9
Deprecated==1.2.13
Flask-AppBuilder==4.3.3
Flask-Babel==1.0.0
Flask-Caching==1.10.1
Flask-Compress==1.13
Flask-Cors==3.0.10
Flask-JWT-Extended==4.3.1
Flask-Limiter==3.3.1
Flask-Login==0.6.0
Flask-Migrate==3.1.0
Flask-SQLAlchemy==2.5.1
Flask-WTF==1.0.1
Flask==2.2.5
Jinja2==3.1.2
Mako==1.2.4
Markdown==3.3.4
MarkupSafe==2.1.1
Pillow==9.5.0
PyHive==0.6.5
PyJWT==2.4.0
PyMeeus==0.5.11
PyNaCl==1.5.0
PyYAML==5.4.1
Pygments==2.15.0
SQLAlchemy-Utils==0.38.3
SQLAlchemy==1.4.36
WTForms-JSON==0.3.5
WTForms==2.3.3
Werkzeug==2.3.3
XlsxWriter==3.0.7
alembic==1.6.5
amqp==5.1.0
apispec==6.3.0
asn1crypto==1.5.1
astroid==2.6.6
asttokens==2.2.1
async-timeout==4.0.2
attrs==23.1.0
auth0-python==3.19.0
backcall==0.2.0
backoff==1.11.1
bcrypt==4.0.1
billiard==3.6.4.0
boto3==1.26.130
botocore==1.29.130
cached-property==1.5.2
cachelib==0.4.1
celery==5.2.2
certifi==2023.5.7
cffi==1.15.1
chardet==5.1.0
charset-normalizer==3.1.0
click-didyoumean==0.3.0
click-option-group==0.5.5
click-plugins==1.1.1
click-repl==0.2.0
click==8.1.3
colorama==0.4.6
convertdate==2.4.0
cron-descriptor==1.2.24
croniter==1.0.15
cryptography==39.0.1
databricks-sql-connector==2.8.0
decorator==5.1.1
deprecation==2.1.0
dnspython==2.1.0
email-validator==1.1.3
et-xmlfile==1.1.0
executing==1.2.0
filelock==3.12.2
flask-talisman==1.0.0
func-timeout==4.3.5
future==0.18.3
geographiclib==1.52
geopy==2.2.0
gevent==22.10.2
greenlet==2.0.2
gunicorn==20.1.0
hashids==1.3.1
hijri-converter==2.2.4
holidays==0.23
humanize==3.11.0
idna==3.2
ijson==3.2.0.post0
importlib-metadata==6.6.0
importlib-resources==5.12.0
ipython==8.12.2
isodate==0.6.0
isort==5.12.0
itsdangerous==2.1.2
jedi==0.18.2
jmespath==1.0.1
jsonlines==3.1.0
jsonschema==4.17.3
kombu==5.2.4
korean-lunar-calendar==0.2.1
lazy-object-proxy==1.9.0
limits==3.4.0
linear-tsv==1.1.0
lz4==4.3.2
markdown-it-py==2.2.0
marshmallow-sqlalchemy==0.23.1
marshmallow==3.19.0
matplotlib-inline==0.1.6
mccabe==0.6.1
mdurl==0.1.2
msgpack==1.0.2
mysqlclient==2.1.0
nh3==0.2.11
numpy==1.23.5
oauthlib==3.2.2
openpyxl==3.1.2
ordered-set==4.1.0
oscrypto==1.3.0
packaging==23.1
pandas==2.0.3
paramiko==2.11.0
parsedatetime==2.6
parso==0.8.3
pexpect==4.8.0
pgsanity==0.2.9
pickleshare==0.7.5
polyline==2.0.0
prison==0.2.1
progress==1.6
prompt-toolkit==3.0.38
psycopg2-binary==2.9.6
psycopg2==2.9.6
ptyprocess==0.7.0
pure-eval==0.2.2
pure-sasl==0.6.2
pyOpenSSL==23.2.0
pyarrow==12.0.0
pyasn1-modules==0.3.0
pyasn1==0.5.0
pycparser==2.20
pycryptodomex==3.18.0
pydruid==0.6.5
pyinstrument==4.4.0
pylint==2.9.6
pyparsing==3.0.6
pyrsistent==0.19.3
python-dateutil==2.8.2
python-dotenv==0.19.0
python-editor==1.0.4
python-geohash==0.8.5
python-ldap==3.4.3
pytz==2021.3
redis==4.5.4
requests==2.30.0
rfc3986==2.0.0
rich==13.3.4
s3transfer==0.6.1
sasl==0.3.1
selenium==3.141.0
shortid==0.1.2
simplejson==3.17.3
six==1.16.0
slack-sdk==3.21.3
snowflake-connector-python==3.0.4
snowflake-sqlalchemy==1.4.7
sortedcontainers==2.4.0
sqlalchemy-databricks==0.2.0
sqloxide==0.1.33
sqlparse==0.4.4
sshtunnel==0.4.0
stack-data==0.6.2
tableschema==1.20.2
tabulate==0.8.9
tabulator==1.53.5
thrift-sasl==0.4.3
thrift==0.16.0
toml==0.10.2
traitlets==5.9.0
typing_extensions==4.4.0
tzdata==2023.3
unicodecsv==0.14.1
urllib3==1.26.6
vine==5.0.0
wcwidth==0.2.5
wrapt==1.12.1
xlrd==2.0.1
zipp==3.15.0
zope.event==5.0
zope.interface==6.0
```

**Comment by alldoami** [comment]
I'm also able to query Databricks Unity Catalog by using the `databricks+connector` dialect driver, but the schemas won't load in sqllab, you have to include the full catalog, schema, and table in the query. Ideally, I don't have to do this though as it isn't straightforward for our users. The schemas/tables show up using the `databricks` dialect driver, but the error I described above appears preventing me to query.

**Comment by alldoami** [comment]
My proposal would be to remove the `kwargs` here https://github.com/apache/superset/blob/master/superset/db_engine_specs/hive.py#L548 and just do `cursor.execute(query)`, I haven't tested this out as I'm not forking superset.

**Comment by doyeon1001** [comment]
hi, i have same problom.
is this a bug right?
I have two workspaces, one is working and the other is having the same issue as this.

**Comment by alldoami** [comment]
@doyeon1001 I think it's a bug? Hoping someone can look into it soon!

**Comment by bkyryliuk** [comment]
I would encourage to use https://github.com/databricks/databricks-sql-python
This is what databricks develops and supports. We are leveraging v2 I think, did not explore v3 of the connector.

Here is an example of the conn string:
```
databricks+connector://token:XXXXXXXXXX@company_name.cloud.databricks.com:port?catalog=default
```

In other section of the db conn you should also specify:
```
{"connect_args":{"http_path":"/sql/1.0/warehouses/id","catalog":"default"}}
```

Please give it a try and reopen the issue if you still experience it.

In terms of impersonation feature, I don't think databricks support that.

**Comment by Vitor-Avila** [comment]
I believe this PR could help supporting Unity Catalog: https://github.com/apache/superset/pull/28393
