### ISSUE TITLE
Gamma user can clone a dashboard and all of its charts without being owner of dashboard, chart and its underlying dataset

### ISSUE THREAD

**Issue by mdeshmu** [apache/superset#24782]
Folks, 

Sorry, but I am confused & annoyed with this behavior which I have described below. 

We are using DASHBOARD_RBAC to give read-only dashboard access to users without giving them any access to charts, datasets, and databases. We have assigned only the default Gamma role to the user profile and to the dashboard roles.

see below, SERVICEACCOUNT user is not the owner of the dashboard. The dashboard has the Gamma role assigned.
![image](https://github.com/apache/superset/assets/57723564/545a3866-558d-4659-9cf6-b7bdc5d9f319)

see below, SERVICEACCOUNT user has only Gamma role assigned. 
![image](https://github.com/apache/superset/assets/57723564/3b13799b-d45a-4e9d-a21f-5c2de6c3183a)

Here are the two issues we are observing:

1) In 2.1.0, 3.0.0rc1, and in the current master, a Gamma user can save a copy of a dashboard not owned by them. More importantly, they can make copies of all charts in the dashboard with the "also copy (duplicate) charts" checkbox. This is very undesired behavior and a maintenance nightmare for us.

see below, SERVICEACCOUNT user can use "save as" on the dashboard and duplicate all charts. 
![image](https://github.com/apache/superset/assets/57723564/77d55d54-007e-4656-ad17-a235f49499c8)

2) They can edit the chart from the dashboard and "save as" a new chart, even though the chart is not owned by them. 

see below, SERVICEACCOUNT user can edit a chart from the dashboard and save it as a new chart from the chart builder.
![image](https://github.com/apache/superset/assets/57723564/e0a37ab9-678d-4bc3-8437-4773f453e9fe)

![image](https://github.com/apache/superset/assets/57723564/25f6c348-8535-451d-81ee-676d8ca7ee8c)

see below, SERVICEACCOUNT user is not the owner of the chart.
![image](https://github.com/apache/superset/assets/57723564/61f88c25-a5c8-4c08-b1da-e2603ae17df3)

The irony is, Gamma users can't list any charts from the Charts Menu (including cloned charts). An admin can see that charts are being cloned.  

![image](https://github.com/apache/superset/assets/57723564/17e9f4d4-13dd-4458-8be5-4823949951ef)

They can't see any dataset from the Datasets menu. 

![image](https://github.com/apache/superset/assets/57723564/7b4e08d9-69de-48d3-a831-ee069cfc6bfe)

They can't see any dataset when trying to create a new chart.

![image](https://github.com/apache/superset/assets/57723564/32013bea-21e1-4639-8ec7-0d2a56f1fec0)

This was reported by another user here as well: https://apache-superset.slack.com/archives/CCKHMGRRB/p1688356037634189

This behavior didn't exist in 1.5.3. Is this a deliberately added behavior or is it a bug with DASHBOARD_RBAC or somewhere else in the code?

### Expected results

Gamma users who are not owners of the dashboard shouldn't be able to save a dashboard.
Gamma users who are not owners of the charts shouldn't be able to edit a chart from the dashboard and should not be able to save it as a new chart from the chart builder.

### Actual results

Gamma users can save a dashboard and chart even if they are not owners. 

#### Screenshots

Added above. 

### Environment

- browser type and version: Version 114.0.5735.134 (Official Build) (64-bit)
- superset version: 3.0.0rc1
- python version: 3.9.x
- node.js version: NA
- any feature flags active: This feature flags are set to true ->
ALERT_REPORTS, DASHBOARD_CROSS_FILTERS, DASHBOARD_RBAC, GENERIC_CHART_AXES, ALLOW_FULL_CSV_EXPORT, DRILL_TO_DETAIL, HORIZONTAL_FILTER_BAR

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for Python stack traces and included them here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of the superset.
- [x ] I have checked the issue tracker for the same issue and haven't found one similar.

### Additional context

NA

**Comment by john-bodley** [comment]
@betodealmeida , @mdeshmu, @michael-s-molina, @sfirke et al. I'm trying to get up to speed with the RBAC for dashboards. Per the documentation it states,

> Granting a role access to a dashboard will bypass dataset level checks. Having dashboard access implicitly grants read access to all the featured charts in the dashboard, and thereby also all the associated datasets.

is the _intended_ behavior that by adding an RBAC role than users of said role are _only_ allowed to see the charts in the context of the dashboard, i.e., should not be able to either explore it, save it (via save-as), or directly access the underlying dataset?

**Comment by betodealmeida** [comment]
> is the _intended_ behavior that by adding an RBAC role than users of said role are _only_ allowed to see the charts (and access the data backing said charts) in the controlled context of the dashboard, i.e., they should not be able to either explore it, save it (via save-as), or directly access the underlying dataset?

I think in theory yes, that was in the intention, but in practice it might've been too complicated to implement it this way and the access just "cascades".

(I'm not super familiar with dashboard RBAC since we don't use it.)

**Comment by john-bodley** [comment]
As a follow up I gather creating a copy of the dashboard (see screenshot) should also likely be forbidden, i.e., said user is stepping beyond the intent of the dashboard owner(s) who provided the RBAC to the role.

<img width="235" alt="Screenshot 2023-07-24 at 3 41 04 PM" src="https://github.com/apache/superset/assets/4567245/b0f4a0a8-173b-45e6-91ca-f4aa325fb69a">

Spelunking through the code I _think_ [this](https://github.com/apache/superset/blob/master/superset/security/manager.py#L1850-L1853) is likely one part of the logic which should change, i.e., access to the underly ing dataset should be context aware—granted only in the context of an accessible dashboard.

Sadly complicated logic doesn't bode well from a security/access perspective and thus I wonder in a future release whether we should consider reverting this feature given the complexity of how/where these controls are enforced—be that within the security manager, filters, etc.

**Comment by mdeshmu** [comment]
Thank you so much @john-bodley for looking into this issue.

**Comment by mdeshmu** [comment]
@john-bodley Really appreciate your effort (series of PRs) to extensively address the issues I have raised here. 

IMO, In this case, A user should not be able to open a chart in Explore by clicking on the chart title in the dashboard. 

![image](https://github.com/apache/superset/assets/57723564/282af559-f22e-4d83-8b77-9b6ee3bf1794)

Do you already have an open PR to address this?

**Comment by john-bodley** [comment]
@mdeshmu https://github.com/apache/superset/pull/24789 partially addresses the issue, i.e., though the link will exist when they click through they'll be denied access to the underlying dataset. I'll likely work on a follow up PR which actually results in a redirect to ensure consistent behavior with the dashboard workflow when a user is denied access.

Note the challenge is currently we (many of the committers) don't have a good sense on what the actual desired UX was—the unit/integration tests which initially failed due to my change indicates that chart exploration was viable, albeit the issues surfaced in this issue. I'm hoping that @villebro can provide some additional context on the situation.

**Comment by mdeshmu** [comment]
> IMO, In this case, A user should not be able to open a chart in Explore by clicking on the chart title in the dashboard.

> Note the challenge is currently we (many of the committers) don't have a good sense on what the actual desired UX was—the unit/integration tests which initially failed due to my change indicates that chart exploration was viable, albeit the issues surfaced in this issue. I'm hoping that @villebro can provide some additional context on the situation.

@villebro can you please clarify what is the desired behavior?
