### ISSUE TITLE
How to install Google Sheet Drivers in Apache Superset Docker image?

### ISSUE THREAD

**Issue by AmarNirgunkar** [apache/superset#24799]
Hi,

I am using Apache Superset V1.3.0 Docker image. I have installed the Google Drivers (gsheetsdb) with the help of link below. after installation, Docker rebuild is not taking effect. it is skipping all the things while entering the "docker-compose build --force-rm" command. 

Can anyone help?

**Comment by sfirke** [comment]
Hello - this doesn't seem like a bug report, more like a request for troubleshooting help, so belongs in Github Discussions or in the Apache Superset Slack chat.  If you share in one of those places what you are trying, someone might be able to help.  Though 1.3.0 is a very old and no longer supported version of Superset, hopefully someone can help as it seems like a general Docker issue.
