### ISSUE TITLE
Filters are dependent on the time range filter, but I have no option to set this dependency.

### ISSUE THREAD

**Issue by alextk87** [apache/superset#24811]
I have a dashboard with a complex query and a lot of filters that are dependent on the time-range filter, however I don't have the option to make the queries of the filters execute and gather data, based on the query that is produced with values of the time-range filter. 

I expect to be able to make the rest of the filters of the dashboard to be dependent on the Time-range filter as it is possible for the rest of the filters.

This issue can be easily reproduced:
1. Create a chard with a teporal column;
2. Go to the dashboard screen;
3. Create a new dashboard;
4. Click on the ADD/EDIT FILTERS button;
5. Add a filter of type Time-range;
6. Add a second filter of type Value;
7. On the filter configuration page, mark the checkbox - "Values are dependent on other filters";
The time-range filter is unavailable in the list of the filters that can be dependent on other filters.

### Environment

- browser type and version: Mozilla 
- Superset is working inside a docker container, from the official repo.
The commit 76c865fc563bdc8c7db15286fb23b12fea1879e6 (HEAD)
Author: AAfghahi <48933336+AAfghahi@users.noreply.github.com>
Date:   Mon Oct 24 17:07:21 2022 -0400

**Comment by michael-s-molina** [comment]
This was fixed by https://github.com/apache/superset/pull/23319.

**Comment by michael-s-molina** [comment]
Closing this a the fix is already on master and will also be available in [3.0](https://github.com/apache/superset/blob/3.0/CHANGELOG.md).
