### ISSUE TITLE
Unable to open swagger on local host due to violating Content Security Policy error.

### ISSUE THREAD

**Issue by loktar00** [apache/superset#24818]
I have Swagger enabled in the config via `FAB_API_SWAGGER_UI = True`

When attempting to go to the URL (and logging in as admin) I see the following in Brave and Edge

![image](https://github.com/apache/superset/assets/174857/bf805e47-a2f7-4984-86d4-44143c62d87c)

```
Refused to load the stylesheet 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@4/swagger-ui.css' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline'". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

v1:55 Refused to load the image 'https://fastapi.tiangolo.com/img/favicon.png' because it violates the following Content Security Policy directive: "img-src 'self' data:".

v1:155 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'strict-dynamic' 'nonce-LOs8l9GOnAS1e1K0ek9wV9aSEaJneEQQ'". Either the 'unsafe-inline' keyword, a hash ('sha256-1r8ykd7la2sNxnDBtNms0TqO7HUtu35cLQvWmZ7Tm64='), or a nonce ('nonce-...') is required to enable inline execution.
```

This is a very vanilla / new setup with no additional configuration done.

#### How to reproduce the bug

1. Enable Swagger
2. Go to '`http://localhost:8088/swagger/v1`
3. You're presented with a white content area and errors in the console.

![image](https://github.com/apache/superset/assets/174857/a44f37ae-a6b2-48ad-9493-a1a6a1c38e43)

### Expected results

Swagger documentation loads

### Actual results

Only the header loads.

### Environment

- browser type and version:  Brave v1.56.11
- superset version: `superset version`
- python version: `3.9.17`
- any feature flags active: `{"ALERT_REPORTS": True, "EMBEDDED_SUPERSET": True}`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sebastianliebscher** [comment]
I could replicate this. https://github.com/apache/superset/issues/24616 did not fix the issue

**Comment by loktar00** [comment]
> I could replicate this. #24616 did not fix the issue

Ah I actually didn't see that issue when searching otherwise I would have commented on that. Glad it's reproduceable was worried _maybe_ it was somehow a local thing. 

I should also mention I am on Windows but using WSL2 / Docker. Might not make a difference but worth mentioning.

**Comment by huamichaelchen** [comment]
I suspect all you need is to add `style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net/npm/swagger-ui-dist@4/swagger-ui.css;` into your CSP. 


Wrote a guide on it, hopefully, it helps someone 😄 Choose your preferred media 😝 

https://huamichaelchen.substack.com/p/end-to-end-example-of-setting-up

https://medium.com/@huamichaelchen/end-to-end-example-of-setting-up-superset-embedded-dashboard-f72fc985559

**Comment by vikashrajgupta** [comment]
![Screenshot from 2024-04-04 18-45-35](https://github.com/apache/superset/assets/40394708/9e944074-3cbb-42b4-9124-e3d8d0386a69)

I'm getting this CSP violation issue only when I'm using superset via the domain name, without the domain it's working fine.
For example, I'm running this on _localhost:9888_ and when I'm using this via domain, it shows a CSP error.
That would be great if you guys could help!!

**Comment by manishkr21** [comment]
in my case setting "Header set Content-Security-Policy "img-src 'self' data: https://fastapi.tiangolo.com;" in apache config file works
