### ISSUE TITLE
[BUG] time-series bar chart - display does not match settings

### ISSUE THREAD

**Issue by fcngucci** [apache/superset#24825]
Hello! I use the superset chart type - time-series bar chart(not legacy). When aggregating data and building a chart, when hovering over a column with data, I see a lot of 0 values.I do not understand how they fall into a specific month. I tried to hide them using several methods: show empty columns, using filtering at the query level, using the field filter by metric, using having on metric, none of the attempts gives the desired result.

I use ClickHouse

here my request
'''
SELECT 
    rega_device
    , rega_time
    , tl
    , country
    , goal
    , locale
    , username
    , card_id
    , event_session_start_time
    , event_time
    , event_name
    , user_id
    , toStartOfMonth (rega_time) as rega_m
    , toStartOfMonth(event_time) as buy_m
    , toDayOfMonth(event_time) as day_of_month
    , toFloat32(event_props.event_values[indexOf(event_props.event_keys, 'USD_net')]) as USD_net
    , event_props.event_values[indexOf(event_props.event_keys, 'is_first_logic_purchase')] as is_first_logic_purchase
    , event_props.event_values[indexOf(event_props.event_keys, 'auto_sub')] as auto_sub
    , event_props.event_values[indexOf(event_props.event_keys, 'renewals_count')] as renewals_count
    , event_props.event_values[indexOf(event_props.event_keys, 'billing_method')] as billing_method
    , event_props.event_values[indexOf(event_props.event_keys, 'serviceInterval')] as serviceInterval
    , event_props.event_values[indexOf(event_props.event_keys, 'purchase_product')] as purchase_product 
    , CASE
        WHEN ( (rega_m = buy_m) AND (is_first_logic_purchase = '1') )
          THEN 1
        WHEN ( (rega_m < buy_m) AND (is_first_logic_purchase = '1') )
          THEN 2
        WHEN  is_first_logic_purchase != '1' AND auto_sub = 'True'
          THEN 3
        WHEN  is_first_logic_purchase != '1' AND auto_sub = 'False'
          THEN 4
        ELSE 0
    END AS segment
    , multiIf (
        toUInt16(rega_source) in (122, 43, 3, 4, 5, 6, 7, 29, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 74, 76, 81, 82, 83, 84, 89, 90, 91, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 120, 121, 129, 130, 131, 132, 133, 136, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 166, 167, 168, 169, 170, 171, 173, 184, 185, 186, 207, 208, 209, 210, 211, 213, 214, 218, 221, 231, 232), 'ads',
        toUInt16(rega_source) in (31,33,34,35,36,75,92,93,96,98,125,128,137,176,177,178,179,180,181,182,183,215,217,222,223,224,225,226,227,228,229,230,238,239,240), 'seo',
        'others'
    ) AS marketing_source
    , if (event_props.event_values[indexOf(event_props.event_keys, 'pay_label_id')] == '0', 0, 1) AS label_mark
    , event_props.event_values[indexOf(event_props.event_keys, 'pay_label_id')] AS ll_concrete
FROM
    global_event
WHERE
    event_name  = 'logic_purchase'
AND 
    USD_net >= 1
AND 
    label_mark = 1
'''

I would like to calculate aggregate via Year-Month sum of USD in dimension with ll_concrete(concrete label)
![image](https://github.com/apache/superset/assets/19615671/80da87f0-b0f8-47fb-8036-958f35db6872)

**Comment by michael-s-molina** [comment]
Hi @fcngucci. There's an option at the top right corner (3 dots) called Run in SQL Lab. Could you add a screenshot of the results of your query using that option to add more context to the issue?

**Comment by michael-s-molina** [comment]
It looks like the screenshots you added are not related to the actual query that is being fired by the chart. Could you click on `View query` in the same 3 dots menu and paste the SQL and its results on SQL Lab?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
