### ISSUE TITLE
User without any permissions still sees +DASHBOARD/+CHART buttons on welcome page

### ISSUE THREAD

**Issue by doctorseus** [apache/superset#24844]
On the frontend side there seems to be an issue with the +DASHBOARD and +CHART button on the welcome page. These buttons are always shown to a user, even if the user has no permission at all. The code indicates these should only be shown if user has access to "write" to either "dashboard" or "graph". But this seems to not work correctly.

#### How to reproduce the bug

1. Create role without permissions
2. Create user with this role only
3. Log in, and see that +DASHBOARD and +CHART buttons are still there

### Expected results
If permissions are not set correctly, buttons should be hidden to user.

### Actual results
Buttons are always shown.

#### Screenshots
![image](https://github.com/apache/superset/assets/3695662/0ad1f34a-ccea-4221-af75-2b81bb3155eb)

### Environment
- superset version: `2.1.1rc2`

**Comment by Valinaa** [comment]
@doctorseus I don't know if it can be hidden. On my part, by modifying the query conditions of Superset's Chart and Dashboard's list-API,user will get an empty list if the user doesn't have specific role or permission.

![image](https://github.com/apache/superset/assets/102314964/b8ab6e7e-d69c-46e2-a7f9-0d44e67c077d)

To implement the functionality you need, you may need a PR.

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
