### ISSUE TITLE
Azure Authentication UPN key error in security/manage.py file

### ISSUE THREAD

**Issue by Narender-007** [apache/superset#24852]
when i am login with azure authentication in apche super set i can't login because have got upn key error after authentication token, when i am replacing "upn" to "email" working fine like 

default:
        if provider == "azure":
            log.debug("Azure response received : {0}".format(resp))
            id_token = resp["id_token"]
            log.debug(str(id_token))
            me = self._azure_jwt_token_parse(id_token)
            log.debug("Parse JWT token : {0}".format(me))
            return {
                "name": me.get("name", ""),
                **"email": me["upn"],**
                "first_name": me.get("given_name", ""),
                "last_name": me.get("family_name", ""),
                "id": me["oid"],
                "username": me["oid"],
                "role_keys": me.get("roles", []),
            }

customized:

        if provider == "azure":
            log.debug("Azure response received : {0}".format(resp))
            id_token = resp["id_token"]
            log.debug(str(id_token))
            me = self._azure_jwt_token_parse(id_token)
            log.debug("Parse JWT token : {0}".format(me))
            return {
                "name": me.get("name", ""),
                **"email": me["email"],**
                "first_name": me.get("given_name", ""),
                "last_name": me.get("family_name", ""),
                "id": me["oid"],
                "username": me["oid"],
                "role_keys": me.get("roles", []),
            }
when i am changing that key name successfully login
### Expected results
am expecting token will generate with upn key and successfully login azure authentication in super set 
what you expected to happen.

### Actual results

what actually happens.

#### Screenshots
<img width="608" alt="image" src="https://github.com/apache/superset/assets/57932042/e7e6298b-7710-4f30-84d9-83aaba9b45ff">

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `3.9`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
I believe this should have been closed with https://github.com/apache/superset/pull/26037
Let us know if you still see this in 3.x, and we can revisit.
