### ISSUE TITLE
[mixed time series] x label is errorly turned to timestamp

### ISSUE THREAD

**Issue by Jasmine1004** [apache/superset#24851]
I used mixed time-series chart to plot historical data and predicted data as two different series in one chart.
Two data series are joint in a virtual dataset saved from sql editor.
I accidently found that when data from Query A is missing (this is normal considering my case), the xlabel (which is a time column) of the chart will be turned to timestamp, and it won't change no matter how I toggle with x-label time format box.

#### How to reproduce the bug

1. create virtual dataset
2. create mixed time-series chart
3. select time range so that historical data is absent, but the predicted data is valid

### Expected results

![image](https://github.com/apache/superset/assets/18062742/386120c1-b700-439d-bc91-9107bfa410aa)

### Actual results

![image](https://github.com/apache/superset/assets/18062742/4bd21347-00b6-490c-97d8-f46f4405f6ac)

#### Screenshots
I have set time format of x axis, but it is not working.
![image](https://github.com/apache/superset/assets/18062742/1ae47607-5802-42ca-b228-76c21f699769)

here is my vitual dataset sql:

### Environment

(please complete the following information):

- browser type and version: chrome
- superset version: superset 2.0.0
- python version: 3.9.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not (especially with Generic Chart Axes now enabled by default, and gone in 4.0). If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
