### ISSUE TITLE
Charting on superset display the date dynamically based on local timezone

### ISSUE THREAD

**Issue by rb00000** [apache/superset#24865]
When Loading a Dataset and creating a CHART. 
Date datatypes are automatically displayed on current user local timezone.
 
#### How to reproduce the bug

1. Go to dataset
2. Click on your dataset name (data with date values)
3. from DATA tab, drag your date columns on QUERY MODE [RAW RECORDS]
4. Update Chart, view and sample result shows the difference

### Expected results
date values should show as the same as by default.

### Actual results

With **Adaptive formatting:**
actual data :
dataset_date = 2023-07-24

on charting :
dataset_date = 2023-07-23

With **TIMESTAMP format :**
actual data :
dataset_date = 2023-07-24 00:00:00

on charting :
dataset_date = 2023-07-23 23:00:00

### Environment

(please complete the following information):

- browser type and version: 
MS Edge Version 114.0.1823.79 (Official build) (64-bit)
Chrome Version 114.0.5735.199 
- superset version: `superset version`
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Superset 2.0.1
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

- python version: `python --version`
Python 3.8.12
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [/] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [/] I have reproduced the issue with at least the latest released version of superset.
- [/] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Hopefully these docs clear things up a bit:
https://superset.apache.org/docs/miscellaneous/timezones

Closing this since I don't think we have a bug here (or we would have heard a LOT of complaints). It's also been silent for a long time, so I think it's safe to cal this stale... I hope you found a solution!
