### ISSUE TITLE
filter_scopes Being Removed in Dashboard Properties After Editing Dashboard Slug (2.1.0)

### ISSUE THREAD

**Issue by bendlikeabamboo** [apache/superset#24867]
Our filter_scopes mapping is being removed from the dashboard_properties after changing the dashboard slug

Hello! I have encountered a bug for Superset 2.1.0

#### How to reproduce the bug

1. Create new dashboard
2. Add filter boxes and charts in the created dashboard
3. Using filter-mapping from the edit menu (top-right, three dots), add scope for each filter box that is not the default
4. Check the Dashboard Properties > Advanced > JSON Metadata:  the filter mapping updates the dashboard properties through the filter_scopes key. It exists in this step since the filter mapping is modified.
5. Go back to the Superset dashboard lists > Edit Dashboard and replace the slug
6. Go to the Dashboard > Edit Dashboard > Edit Dashboard Properties > Advanced
7. See the JSON Metadata

### Expected results

The `filter_scopes` key is still there.

### Actual results

The `filter_scopes` key is no longer there. Filter scopes not found.

### Environment

(please complete the following information):

- browser type and version: Microsoft Edge Version 115.0.1901.183 (Official build) (64-bit)
- superset version: Apache Superset 2.1.0
- python version: Python 3.9
- node.js version: `node -v`
- any feature flags active: cross-filter enabled, VERSIONED_EXPORT enabled

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [v] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [v] I have reproduced the issue with at least the latest released version of superset.
- [v] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

#19026

**Comment by rusackas** [comment]
We no longer support Filter Box, as it was deprecated in 3.0, and will be gone in the forthcoming 4.0 release.
