### ISSUE TITLE
Numeric filters show duplicate values and UI issue when scrolling 

### ISSUE THREAD

**Issue by yousoph** [apache/superset#24877]
In numeric chart filters and dashboard filters, after typing and selecting a value in the filter, duplicate values start to show up. 

#### How to reproduce the bug

1. Go to a chart 
2. Add a filter using a numeric column 
3. Type a value into the filter, then select the filter value 
4. Type another value into the filter and select the filter value 

### Expected results

One of each value with the selected ones highlighted 

### Actual results

Duplicate values start to appear. 
After scrolling up and down, more duplicate values show up and replace the actual filter values

#### Screenshots

https://github.com/apache/superset/assets/10627051/ee13139f-0723-49e5-9e25-2fc55035caff

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by yousoph** [comment]
cc @michael-s-molina in case you're interested in taking a look - wasn't sure if this might be related to the recent work on typed values in filters

**Comment by michael-s-molina** [comment]
Assigned to myself. Thanks @yousoph!

**Comment by michael-s-molina** [comment]
Hey @yousoph. It's an Ant Design limitation. I opened an issue [here](https://github.com/ant-design/ant-design/issues/44007) and got a response that there's a warning indicating that we can't use numeric values when the Select mode is `tags`. We'll need to convert numeric columns to strings before using them in the component and then convert them back to numbers when applying the filters 😞
