### ISSUE TITLE
Error connecting to Open Distro for Elasticsearch

### ISSUE THREAD

**Issue by shriny** [apache/superset#24887]
Getting following error when connecting to OpenDistro for elasticsearch,this happens with AMS ESS

ERROR: Could not load database driver: OpenDistroEngineSpec

#### How to reproduce the bug

odelasticsearch+https://my_user:my_password@search-SOME-CLUSTER.us-west-2.es.amazonaws.com:443/
ERROR: Could not load database driver: OpenDistroEngineSpec

### Expected results
connection successful

### Actual results

ERROR: Could not load database driver: OpenDistroEngineSpec

#### Screenshots

ERROR: Could not load database driver: OpenDistroEngineSpec

### Environment

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Sounds like you didn't install the driver. Can you check your dependencies?

**Comment by rusackas** [comment]
Closing since it's been a few months since asking for more details. If you're still facing this, let us know and we can certainly reopen it. Meanwhile, perhaps @dosu-bot can shed some light on the subject for good measure.
