### ISSUE TITLE
Stop button in Chart view doesn't stop async queries

### ISSUE THREAD

**Issue by ganczarek** [apache/superset#24890]
When an async query (`GLOBAL_ASYNC_QUERIES=True`) is run in Chart view, clicking "Stop" button doesn't have any effect. Clicking Stop button, closing tab, refreshing page or going to other page leaves the query running in a database.

#### How to reproduce the bug

1. Go to 'Chart' view 
2. Click on 'Update Chart' to execute query
3. Click on 'Stop' to stop query

### Expected results

Running query is cancelled in a database.

### Actual results

Nothing happens. 

### Environment

- browser type and version:
- superset version: `2.1.0`
- python version: `3.8.13`
- node.js version: `16.9.1`
- any feature flags active: `GLOBAL_ASYNC_QUERIES=True`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Clicking "Stop" button aborts fetch request, but that doesn't cancel running query in a database. With `GLOBAL_ASYNC_QUERIES` enabled that request is very fast, so in most cases there's no even request to abort.

To stop a running async query we need to terminate Celery task and cancel query in a database.

**Comment by cw1427** [comment]
Yeah, I met the same issue. When the PR could got merged?

**Comment by rusackas** [comment]
I'm hopeful that @ganczarek will come back to re-base and help merge https://github.com/apache/superset/pull/24905 - but if not, anyone else is welcome to adopt and credit their work, or open a PR with a different approach.

This was reported as a 2.x issue, but we're closing those out as we only support 3.x and newer. Please let us know if this is still happening in current versions.

**Comment by rusackas** [comment]
This seems to have gone stale, as we no longer even support 3.x. Happy to revisit/reopen if this is still an issue in 4.x
