### ISSUE TITLE
How to serve static files from a custom viz?

### ISSUE THREAD

**Issue by superfrog** [apache/superset#24897]
Having started a custom viz plugin following https://superset.apache.org/docs/contributing/creating-viz-plugins/

How can we HTTP serve static images and other assets from the plugin structure?

**Comment by rusackas** [comment]
I would start by looking at how thumbnails are loaded in the viz gallery. 

Not sure if you're still up against this, but we can take it to a Q&A thread on GitHub Discussions if you'd like.

Closing it since it's not a bug, and it's been silent for so long.
