### ISSUE TITLE
Redshift late-binding views cannot be added as datasets

### ISSUE THREAD

**Issue by ErikIgnatiev** [apache/superset#24907]
When adding Redshift's [late-binding views](https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_VIEW.html) as datasets a "Table [`table name`] could not be found" error is raised, even though the view is seen in the loaded schema and access is granted to the parent table of the view. This stops adding new datasets from views and updating existing ones as the schema is not being loaded.
The vies can be explicitly queried in SQL Lab successfully, but the column list cannot be loaded in the side panel with an `Issue 1030 - The query has a syntax error.`

#### How to reproduce the bug

1. Go to `Datasets`
2. Click on `+Dataset`
3. Select a late-binding view from the populated list in `SEE TABLE SCHEMA` and click Add
4. See `An error occurred while creating datasets: (table_name) Table [*table name*] could not be found, please double check your database connection, schema, and table name`

### Expected results

Expected a new dataset to be created linked to the existing view.

### Actual results

Cannot create dataset as the table is listed as missing.

#### Screenshots

<img width="960" alt="Screenshot 2023-08-07 at 15 03 14" src="https://github.com/apache/superset/assets/28051792/dae1341a-0c70-4fac-827f-fe85ef9b9d5f">

<img width="1263" alt="Screenshot 2023-08-07 at 15 03 05" src="https://github.com/apache/superset/assets/28051792/cf1076e6-5231-4456-b9a0-6d3f99ffae44">

### Environment

(please complete the following information):

- browser type and version: `Chrome v115.0.5790.114`
- superset version: `v2.0.1`
- python version: `N/A`
- node.js version: `N/A`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sfirke** [comment]
@cbuffevant I see you are listed as a Redshift user, is this something you could validate/examine/help with?

**Comment by mdeshmu** [comment]
@ErikIgnatiev Which redshift driver are you using pyscopg2 or redshift-connector? what is the version of sqlalchemy-redshift?

**Comment by ErikIgnatiev** [comment]
> I can query late binding views properly in superset version 2.1.0 @ErikIgnatiev Which redshift driver are you using pyscopg2 or redshift-connector? what is the version of sqlalchemy-redshift?

Our Superset version is `2.0.1`. We're using `psycopg2 = "==2.9.3"` and `sqlalchemy-redshift = "==0.7.1"` in the image. By querying you mean adding a dataset? I can run successful queries in SQL Lab as well but getting the schema for creating new datasets fails.

**Comment by mdeshmu** [comment]
I am able to create a dataset using a late binding view. 

![image](https://github.com/apache/superset/assets/57723564/cad7d62d-3c50-4e2d-9455-f5bf6c2d697c)

![image](https://github.com/apache/superset/assets/57723564/b4f33ed8-e065-461b-9d99-b61e38a85d7e)

![image](https://github.com/apache/superset/assets/57723564/0c3ce62b-a37d-4c58-a618-1081b84556f6)

**Comment by rusackas** [comment]
Hi there, and sorry this has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale. If it is still an issue in Superset 3.x, we can re-open this, or feel free to open a new issue with updated context.
