### ISSUE TITLE
alerts reports not working with kubernetes

### ISSUE THREAD

**Issue by gauti098** [apache/superset#24950]

**Comment by sfirke** [comment]
Hello, this is not currently an actionable bug report.  Lots of people have alerts and reports working with Kubernetes.  If you believe you have discovered a bug in Superset that needs patching, please provide the information from the bug report template like information about your instance, your version, deployment method, what you expect vs. what you're seeing.

Or if you have questions about how to configure and troubleshoot, I suggest asking in the Apache Superset Slack chat or in Github discussions -- though in those places you will also need to provide more detail to get a response.

**Comment by sfirke** [comment]
Closing due to lack of detail.
