### ISSUE TITLE
Cannot add helm repo

### ISSUE THREAD

**Issue by ABashkirtseva** [apache/superset#24954]
When I try to add repo I've got an error that is not found or invalid

#### How to reproduce the bug

Run this command according to your doc: https://superset.apache.org/docs/installation/running-on-kubernetes/

```
helm repo add superset https://apache.github.io/superset
```

### Expected results

See successful message that repo was added

### Actual results

Error:
```
Error: looks like "https://apache.github.io/superset" is not a valid chart repository or cannot be reached: failed to fetch https://apache.github.io/superset/index.yaml : 404 Not Found
```

#### Screenshots

![image](https://github.com/apache/superset/assets/21782312/d920ced3-b43d-4aaf-a604-392d136a391b)

### Environment

Helm version:
```
version.BuildInfo{Version:"v3.12.1", GitCommit:"f32a527a060157990e2aa86bf45010dfb3cc8b8d", GitTreeState:"clean", GoVersion:"go1.20.5"}
```

**Comment by nytai** [comment]
should be fixed now

**Comment by ABashkirtseva** [comment]
Thanks, it works!

**Comment by venkataramanab** [comment]
Occurring again, Please check. Thanks.

**Comment by DhruvBundheliya** [comment]
It's not working again!
