### ISSUE TITLE
Incorrect split dot for databases and schemas

### ISSUE THREAD

**Issue by VitalyKapustin-git** [apache/superset#24978]
https://github.com/apache/superset/blob/571f33536e627ccf8b6cafac1d8c296e442e1ef6/superset/security/manager.py#L316-L317

I've named my database in database connections by FQDN like example.mycompany.local this code will work incorrect.
I'll get `[exampl` for database var and `ny` for schema var.

Could we prevent that if take last element from split array and replace slice to `replace()`?

`schema_name = schema_permission.split(".")[-1].replace('[', '').replace(']', '')`
`database_name = schema_permission.split(".")[0].replace('[', '').replace(']', '')`

**Comment by rusackas** [comment]
@VitalyKapustin-git That does seem more forgiving! Would you be willing to open a PR with that change, and hopefully a unit test that passes with your previously failing case?

**Comment by rusackas** [comment]
The issue found doesn't seem to be in the current code anymore. Closing, but open to discussion/reopening if the problem is still present! Thanks for the suggestions!
