### ISSUE TITLE
Superset Login not working from Remote browser

### ISSUE THREAD

**Issue by thedeceptio** [apache/superset#24975]
I cloned this repo and used docker compose to run an instance of Superset with the following command. 

`sudo docker-compose -f docker-compose-non-dev.yml up`

I see some usual logs and the superset instace is up. I'm able to open the url : http://localhost:8088/ and then enter the default  credentials : admin - admin and login. 

but if I try to login to this instance from a different computer (on the same network) using its ip address. I get the error message saying access denied.   Its is not a network issue because the login page is accessible. The issue is that the credentials which were working from a same machine do not work if I open superset from a different machine.
#### How to reproduce the bug

1. use an external database as the default datastore. (I had used mysql) , I updated the variables in the supetset_config.py file
2. use command `sudo docker-compose -f docker-compose-non-dev.yml up` to create a supetset instance. 
3. Try to access this from the same computer using the url http://localhost:8088/ , login page opens and we are able to login with default credentials 
4. Try to access this from a different computer using this computer's IP address.  we see that login page is opening but default credentials are not working. 

### Expected results
 
the default credentials should work , while accessing superset from any computer

### Actual results
the default credentials work only while accessing superset from localhost:8088 and not with network ip+port

### Environment

(please complete the following information):

- browser type and version: tried from multiple browsers. NO effect. in any case I am using Brave : [Version 1.56.20 Chromium: 115.0.5790.171 (Official Build) (64-bit)](https://brave.com/latest/)
- superset version: `superset version` Latest 
- python version: `python --version` Python 3.10.12
- node.js version: `node -v`  Not installed 
- any feature flags active:
I tried to use external database for storing metadata 
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by VitalyKapustin-git** [comment]
Could you pls check this?
https://github.com/apache/superset/issues/24579#issuecomment-1646360332

**Comment by thedeceptio** [comment]
> Could you pls check this? [#24579 (comment)](https://github.com/apache/superset/issues/24579#issuecomment-1646360332)

Yes, 
`TALISMAN_ENABLED=False`
did it for me.
