### ISSUE TITLE
Security policies prevent restrict display only avalaible db schemas

### ISSUE THREAD

**Issue by VitalyKapustin-git** [apache/superset#24976]
https://github.com/apache/superset/blob/571f33536e627ccf8b6cafac1d8c296e442e1ef6/superset/security/manager.py#L621

By using `can_access_database()` function we prevent granular permissions for schemas.
All users that have access to db will see all available schemas.

If we replace it to something like:
`if hierarchical and (self.can_access_all_datasources() or self.can_access_all_databases())`

then schemas will be displayed just only for users with extended permissions.
All others will get just only schemas from their roles.

**Comment by rusackas** [comment]
This sounds reasonable, but I think @dpgaspar or @john-bodley might be the right ones to weigh in on the topic.

**Comment by dpgaspar** [comment]
I do think the current access check makes sense. The hierarchy is
Database -> Schema -> datasource

If a user as access to the database, then (on SQLLab) the user will have access to all underlying hierarchical entities, on this case schemas and datasources

Giving access to a schema is enough to grant the user implicit partial access to the database (on SQLLab), so no need to give the user wide access to the database itself.

Closing this issue, but feel free to reopen it

**Comment by dulajra** [comment]
> Giving access to a schema is enough to grant the user implicit partial access to the database (on SQLLab), so no need to give the user wide access to the database itself.

If the behaviour is like this then I agree with this statement. But it's not the case with superset (4.1.1). Even if the role has schema access but the database access is not specifically added for the role then you will get the following error when clicking on the table dropdown on SQL lab. 

```
An error occurred while fetching table metadata. Please contact your administrator.
```

You will get the following error when running a SQL query on SQL lab. 

```
can not access the query
```

The above errors will be gone if you grant database access for the role. But then you will see all the schemas on the schema dropdown irrespective of the schema access granted for the role.
