### ISSUE TITLE
Wrong default password for admin user

### ISSUE THREAD

**Issue by XLPI** [apache/superset#24977]
Actually after fresh Docker images installed and run as docker compose up - this password admin doesn't work. What's could be a problem?
https://github.com/apache/superset/blob/be1155679963a90c7a0d699a2ebdceade40fb5a9/docs/docs/installation/installing-superset-using-docker-compose.mdx#L131

**Comment by Edwardveb** [comment]
https://github.com/apache/superset/issues/24975

**Comment by XLPI** [comment]
Actual bug is here https://github.com/apache/superset/issues/24975
