### ISSUE TITLE
Rockset Error: list index out of range

### ISSUE THREAD

**Issue by maxreis86** [apache/superset#24988]
When no results are returned for any query using the Rockset as the backend for a database connection, we receive the error  "Rockset Error list index out of range"
In the other hand, when using postgresql as the backend for a database connection we receive the message "No results were returned for this query"
What we expect would be receiving the same message "No results were returned for this query" for Rockset as well.

#### How to reproduce the bug

1. Create a new database connection using Rockset as the backend and with a SQLALCHEMY URI
2. Go to SQL and SQL Lab
3. Run any query with a filter that returns no results 
4. See error Rockset Error list index out of range

### Expected results

Receiving the same message "No results were returned for this query"  instead of get an error.

### Actual results

We are receiving the error "Rockset Error list index out of range" 

#### Screenshots

![image](https://github.com/apache/superset/assets/33838048/7e8f6c3d-6690-4606-8a31-9b7ad115faef)
![image](https://github.com/apache/superset/assets/33838048/b0c4847d-168a-4116-ad9c-4588909e4abf)

### Environment

(please complete the following information):

- browser type and version: Any
- superset version: 2.1.1rc2
- python version: 3.11
- node.js version: 18.0.0
- any feature flags active: None

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Hopefully this was resolved if you follow the docs updated by https://github.com/apache/superset/pull/24649

I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
