### ISSUE TITLE
Issue with Get API to list all the dashboards

### ISSUE THREAD

**Issue by karan-kumar-by** [apache/superset#24993]
Issue with Get API to list all the dashboards. I have around 25 dashboards and I am trying to get the list of all those using the below GET API
http://127.0.0.1:8088/api/v1/dashboard/

Every time it is returning only the same set of 20 dashboards. I tries using the pagination but the issue remains.

#### How to reproduce the bug

I tried using pagination but it is always returning first 20 dashboards.
Req1 : http://127.0.0.1:8088/api/v1/dashboard/?**page=0**&page_size=100
Resulted dashboard Ids : [222, 221, 220, 219, 218, 217, 216, 215, 214, 213, 212, 211, 210, 209, 208, 207, 206, 205, 204, 203]

Increased the page number to 1
Req2 : http://127.0.0.1:8088/api/v1/dashboard/?**page=1**&page_size=100
Resulted dashboard Ids : [222, 221, 220, 219, 218, 217, 216, 215, 214, 213, 212, 211, 210, 209, 208, 207, 206, 205, 204, 203]

### Expected results

It should return all the 25 dashboard.

### Actual results

Every time it is returning only the same set of 20 dashboards.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `2.1.0`
- CHART VERSION - 0.10.5
- python version: `3.9.16`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by michael-s-molina** [comment]
Hi @karan-kumar-by. You can check https://superset.apache.org/docs/api/ to see the expected request format. `page` and `page_size` are properties of the `q` param. Make sure you also don't have [FAB_API_MAX_PAGE_SIZE](https://flask-appbuilder.readthedocs.io/en/latest/config.html) configured.

**Comment by karan-kumar-by** [comment]
With q it worked but looks like the response headers always return same set of ids for all the subsequent request. So I need to parse the result from the payload.
