### ISSUE TITLE
SSLError when adding Trino as database

### ISSUE THREAD

**Issue by RoseGoldIsntGay** [apache/superset#25004]
When trying to add trino as a database and testing the connection i get the following error:
```
ERROR: (buildins.NoneType) None
[SQL: HTTPSConnectionPool(host='trino.my.dns', port=443): Max retries exceeded with url: /v1/statement (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))]
(Background on this error at: https://sqlache.me/e/14/dbapi)
```

**How to reproduce the bug**
1. Deploy Superset
2. Add a database without valid certificates on the superset machine

I'm using Superset's helm chart, so I went ahead and ran the container locally using docker and ran the following commands:
`curl -i https://trino.my.dns -> curl: (60) SSL certificate problem: unable to get local issuer certificate`
After that I copied my certificates into `/usr/local/share/ca-certificates` and ran `update-ca-certificates --fresh` causing `curl -i https://trino.my.dns` to no longer return an SSL error

Then I tried using python to access my Trino
`python3 -c "import requests;requests.get('https://trino.my.dns')"` which returns the same SSLError mentioned at the top.

I've tried upgrading certifi, setting REQUESTS_CA_BUNDLE, and I even tried manually appending my certificates at the end of certifi's cert bundle (at `/usr/local/lib/python3.9/site-packages/certifi/cacert/pem`) but none seem to solve the issue.

`superset version` returns 0.0.0-dev, probably because im offline
Python version 3.9.17

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by RoseGoldIsntGay** [comment]
Resolved.

**Comment by accorvin** [comment]
@RoseGoldIsntGay can you provide any information on how you resolved this? I'm hitting a similar issue where I believe I'm providing the CA bundle to Superset correctly but it's still complaining about cert problems.

**Comment by groverkaushal** [comment]
@accorvin Hi, I was having the same issue using minikube + helm chart.
Turns out it was not CA certificate or SSL error issue. It was a DNS issue.

when superset container was running as a Kubernetes Pod inside Minikube, its `/etc/resolv.conf` was overwritten by Kubernetes DNS settings.


so to resolve this... once the pod is running you can 
```
kubectl exec -it superset-xxxxxxxxx-xxxxx -- bash
echo "nameserver 8.8.8.8" > /etc/resolv.conf
```
