### ISSUE TITLE
Issue adding a new DB spec: default_driver needs to have a non-empty value.

### ISSUE THREAD

**Issue by danielfernandez** [apache/superset#25023]
Using Superset 2.1.0, I'm trying to add a new db spec and using `BasicParametersMixin` so that a form is shown at database creation time with all the parameters in separate inputs.

```python
class MyEngineSpec(BaseEngineSpec, BasicParametersMixin):  
    engine = "myengine"
     engine_name = "My Engine"
      default_driver = ""
     sqlalchemy_uri_placeholder = ( 
        "my://user:password@host:port/dbname[?key=value&key=value...]"
     )
     encryption_parameters = {"sslmode": "require"} 
    ...
```

My SQL Alchemy dialect does **not** need the specification of a driver, and therefore I've set `default_driver` to the empty string. I've tried that and also `None`, but Superset will not show me the form corresponding with the `BasicParametersMixin` unless I set a non-empty value in `default_driver`... which is wrong and makes SQL Alchemy fail because my dialect does not need any driver names.

Is there any way I can work around this issue?

**Comment by betodealmeida** [comment]
I'm not sure I understand. What happens when you have `default_driver` set to an empty string? Can you share a screenshot?

**Comment by danielfernandez** [comment]
What happens is that, for that data source, the `BasicParametersMixin` is ignored and no multi-input form --with separate server, port, user, password, etc. inputs-- is shown.

Instead, the standard SQL Alchemy URI form is shown.

**Comment by rusackas** [comment]
Hi there, and sorry this has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale. If it is still an issue in Superset 3.x, we can re-open this, or feel free to open a new issue with updated context.
