### ISSUE TITLE
Server side pagination not working!

### ISSUE THREAD

**Issue by GreatAg** [apache/superset#25039]
I connected superset to my elasticsearch instance and created a dataset.
I created a chart table in order to view all of my logs but because of my dataset is huge i need server side pagination.
 When i enabled server side pagination feature i faced an error.

![superset_error](https://github.com/apache/superset/assets/85877807/1daa355e-5e43-4167-ad8d-48f51d59316f)

and here is query output:

![query_error](https://github.com/apache/superset/assets/85877807/9e5740b2-29b2-48a8-b43d-f9c8f5175f9f)

Here is my other chart configurations:

![config_chart](https://github.com/apache/superset/assets/85877807/ec8798b6-9d24-4bae-8417-1a686bb32149)

![customize_config](https://github.com/apache/superset/assets/85877807/7748a6a9-758e-4ed0-abb6-95bea5b687d2)

I think the second query doesn't have a correct syntax and LIMIT 50000 shouldn't be there.
Please let me know if anyone can help me in order to solve this problem.

### Expected results

A table with server side pagination.

### Actual results

I faced following error:
Error: Error (planning_exception): {'error': {'root_cause': [{'type': 'planning_exception', 'reason': 'Found 1 problem\nline 16:4: LIMIT or TOP cannot be used in a subquery if outer query contains GROUP BY, ORDER BY, PIVOT or WHERE'}], 'type': 'planning_exception', 'reason': 'Found 1 problem\nline 16:4: LIMIT or TOP cannot be used in a subquery if outer query contains GROUP BY, ORDER BY, PIVOT or WHERE'}, 'status': 400}

### Environment
- browser type and version: chrome 113.0.0
- superset version: 2.1.1
- python version: 3.9.17

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by GreatAg** [comment]
any idead??

**Comment by rusackas** [comment]
Hi there, and sorry this has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale. If it is still an issue in Superset 3.x, we can re-open this, or feel free to open a new issue with updated context.
