### ISSUE TITLE
Not able to do export CSV/Image for charts if readonly role is assigned to user.

### ISSUE THREAD

**Issue by PShiw** [apache/superset#25041]
## Screenshot

![image](https://github.com/apache/superset/assets/16036189/96c5113d-916a-44e8-8695-fc4fdfbc7870)

## Description

Not able to do export CSV/Image for charts if readonly role is assigned to a user.

## Design input

With attached image we can see that user is able to see the charts as readonly but not able to export it as csv and image. Refer below image for menu list with said roles.

![image](https://github.com/apache/superset/assets/16036189/0d648430-fd28-4694-bc55-a5d28f3d6ee3)

Need to have below menu enabled for exporting chart as csv or image.

![image](https://github.com/apache/superset/assets/16036189/6742ae99-b2d8-4645-8a24-4dc8485dae8b)

Do we have any role with which the user cannot edit dashboard but export it as csv/image?

**Comment by Valinaa** [comment]
@PShiw I think you need to add a permission `can export on Chart`.

**Comment by PShiw** [comment]
No luck with "can export on chart" role. Refer below image where the role is added.

<img width="1032" alt="image" src="https://github.com/apache/superset/assets/16036189/b9e38745-c665-4697-93cd-6b75ab35093d">

Observe that there is no change in chart menu.

<img width="201" alt="image" src="https://github.com/apache/superset/assets/16036189/0e07f250-ebfe-445c-919b-e4d76dd145b5">

**Comment by Valinaa** [comment]
@PShiw Permission `can csv on Superset` works for me. You can try it. No need to use `can export on chart`.

**Comment by rusackas** [comment]
Hopefully, the answer above is sufficient to close this thread. I'll do so anyway since it's been so long since there was a comment here. If this needs revisiting/reopening, just say the word.
