### ISSUE TITLE
save dataset error：Unexpected token '<'

### ISSUE THREAD

**Issue by Amosi66** [apache/superset#25051]
superset version：2.1.0
docker-compose deploy

https://github.com/apache/superset/assets/142192493/6e8f42f5-d5fc-4b1a-a9ef-86ccbab516cf

**Comment by natechoiniere** [comment]
Just saw this today, too. It worked when I removed all the whitespaces from the name of the dataset.

**Comment by Amosi66** [comment]
> Just saw this today, too. It worked when I removed all the whitespaces from the name of the dataset. Edit: Could also just have been that I refreshed the page.
There are no spaces in the name of my dataset, but there are still issues.

**Comment by DaveMaks** [comment]
> Just saw this today, too. It worked when I removed all the whitespaces from the name of the dataset. Edit: Could also just have been that I refreshed the page.

I delete  whitespaces, but it didn't work for me. Any other options for solving this problem?
![image](https://github.com/apache/superset/assets/54938636/3fd588ff-9e69-4c2e-a001-ad1783effbb9)

**Comment by jschell12** [comment]
Getting the same error. Removing spaces does not work

**Comment by jschell12** [comment]
looks like from the server logs I'm seeing a 302 returned for the POST request

```
10.207.149.157 - - [27/Sep/2023:00:43:34 +0000] "POST /superset/sqllab_viz/ HTTP/1.1" 302 361 "https://censusv3-superset.staging.hulu.com/superset/sqllab/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
```

**Comment by jschell12** [comment]
So highly not recommended but I just ran superset using `latest` and also had to run the **init-db** job.

**Comment by konung** [comment]
@jschell12  Hi  . 

I'm also getting the same error. But I'm totally new to Superset - just tryign it out. Could you please clarify what you meant by `superset using latest` and `had to run the init-db job `?

Thank you

**Comment by bryan-oliveira** [comment]
I'm getting this also. Could this be permissions related?

**Comment by NoGroceries** [comment]
> Getting the same error. help!

I solved it。 rerun:  superset init

**Comment by rusackas** [comment]
Seems we have the sufficient answers here to close this out, but let us know if that's not the case!

**Comment by rusackas** [comment]
Closing as some mix of complete/answered/stale. If anyone wants to discuss making further improvements, let me know and i'd be happy to reopen this
