### ISSUE TITLE
Incorrect dashboard opens when clicking on dashboard title

### ISSUE THREAD

**Issue by zhaorui2022** [apache/superset#25064]
In the dashboard list, when clicking on some dashboards, sometimes incorrect dashboard is open. See screen record for details.

#### How to reproduce the bug
It doesn't always happen but reproducible.

1. Go to Dashboard page
2. Click on a dashboard and go back
3. Then click on another dashboard
4. See incorrect dashboard

### Expected results
It always opens the dashboard I select

### Actual results

Sometimes it opens the previous dashboard

#### Screenshots

![Google Chrome - Superset 2023-08-23 at 10 39 58 AM](https://github.com/apache/superset/assets/105950525/1feb6484-089d-4d30-91c6-86292b5afaec)

### Environment

(please complete the following information):

- browser type and version: chrome, Version 112.0.5615.121 (Official Build) (arm64)
- superset version: `superset version` 3.0.0rc2
- python version: `python --version` python 3.9
- node.js version: `node -v` 
- any feature flags active: Not sure if it is related, but we have dashboard native filter and cross filter off (inherited from superset/config in 3.0.0rc2) Before 3.0.0rc2, we didn't have dashboard native filter enabled.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
Not quite sure if these are related but I see such stack trace in browser console
```
tChartIdsInFilterScope.ts:31 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'excluded')
    at getChartIdsInFilterScope.ts:31:20
    at Array.filter (<anonymous>)
    at i (getChartIdsInFilterScope.ts:29:19)
    at g (crossFilters.ts:58:24)
    at hydrate.js:313:9
    at index.js:16:18
    at DashboardPage.tsx:229:9
    at DashboardPage.tsx:241:13
    at il (react-dom.production.min.js:211:320)
    at Oc (react-dom.production.min.js:257:303)
(
```

**Comment by michael-s-molina** [comment]
@zhaorui2022 I was not able to reproduce this bug using the [3.0.0 RC2 test environment](http://34.212.28.153:8080/). 


https://github.com/apache/superset/assets/70410625/a8059910-d23d-4f6c-b809-2cb8d1eb5a59

**Comment by michael-s-molina** [comment]
I noticed the problem always happen when you click on the DB tests dashboard. Maybe it's related to this dashboard? Are you able to generate this error when interacting with the examples dashboard?

**Comment by michael-s-molina** [comment]
I believe the exception you posted might be related to the bug. Could you edit the dashboard, to go Edit properties, and paste the contents of the Advanced tab? The error indicates a problem with your filter scope.

**Comment by zhaorui2022** [comment]
When I reopen the browser and reopen the dashboard directly without clicking on anything else, it does show an error in the console.
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'excluded')
    at getChartIdsInFilterScope.ts:31:20
    at Array.filter (<anonymous>)
    at i (getChartIdsInFilterScope.ts:29:19)
    at g (crossFilters.ts:58:24)
    at hydrate.js:313:9
    at index.js:16:18
    at DashboardPage.tsx:229:9
    at DashboardPage.tsx:241:13
    at il (react-dom.production.min.js:211:320)
    at Oc (react-dom.production.min.js:257:303)
(
```

However, I am not able to click on edit dashboard for this one due to this error causing the entire page not loading. And then if I go back to the list of dashboards, the same issue happens. So maybe it is related with the error showing up in the console.

**Comment by zhaorui2022** [comment]
Oh I just saw this config is set to True https://github.com/apache/superset/blob/3630d6844c0f4668f7196beadd744e582c9219bd/superset/config.py#L443C37-L443C37 while the previous version I tested had it set to False by default. Let me disabling this feature and see if it works.

**Comment by zhaorui2022** [comment]
Confirming after disabling DASHBOARD_CROSS_FILTER feature flag, the issue is gone.

**Comment by michael-s-molina** [comment]
@zhaorui2022 It's just that if you disable `DASHBOARD_CROSS_FILTER` that part of the code won't execute. The 3.0.0RC2 test environment has `DASHBOARD_CROSS_FILTER` enabled and I can't reproduce this error. What I think it's happening is that your dashboard configuration is corrupted for that particular dashboard and that is causing the error.

Can you disable `DASHBOARD_CROSS_FILTER`, execute the steps bellow and share your Advanced tab values?

> I believe the exception you posted might be related to the bug. Could you edit the dashboard, to go Edit properties, and paste the contents of the Advanced tab? The error indicates a problem with your filter scopes.

**Comment by michael-s-molina** [comment]
@zhaorui2022 I think I understood what was happening. If you create a dashboard with `DASHBOARD_CROSS_FILTER` disabled and later enable the feature flag, the error you mentioned will be thrown. I submitted https://github.com/apache/superset/pull/25074 to fix the issue.
