### ISSUE TITLE
iframe内嵌superset时，superset页面中的“api/v1/dashboard/7/filter_state?”接口抛异常“400 Bad Request: The CSRF session token is missing”

### ISSUE THREAD

**Issue by githubid0719** [apache/superset#25062]
When the iframe is embedded with a superset, it can succeed. However, the "API/v1/dashboard/7/" interface in the superset page reported the following error

![image](https://github.com/apache/superset/assets/68492256/663db343-e8d7-44b2-a13d-547338a3a519)

May I ask how to solve it? Is there a solution without closing CSRF?

**Comment by michael-s-molina** [comment]
Possible duplicate of https://github.com/apache/superset/issues/24717.

**Comment by githubid0719** [comment]
Is there any solution without closing CSRF?

**Comment by huamichaelchen** [comment]
It seems you are trying to get the embedded dashboard to work. You could use the superset API to get the CSRF token which subsequently you need to call the `guest_token` endpoint to authenticate. 

Wrote a guide on it, hopefully, it helps someone 😄 Choose your preferred media 😝 

https://huamichaelchen.substack.com/p/end-to-end-example-of-setting-up

https://medium.com/@huamichaelchen/end-to-end-example-of-setting-up-superset-embedded-dashboard-f72fc985559

**Comment by rusackas** [comment]
Hi there, and sorry this has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale. If it is still an issue in Superset 3.x, we can re-open this, or feel free to open a new issue with updated context.
