### ISSUE TITLE
Chart Series Limit doesn't work for Clickhouse datasets

### ISSUE THREAD

**Issue by KSPT-taylorjohn** [apache/superset#25073]
The chart series limit setting doesn't work for Clickhouse datasets.
The generated SQL doesn't contain a limit subquery.

#### How to reproduce the bug

1. Use a clickhouse db
2. Create a chart with a dimension 
3. Add a series limit 
4. Note how the series aren't limited in the generated SQL

### Expected results

The generated query to use the series limit.

### Actual results

The generated query doesn't use the series limit.

#### Screenshots

![image](https://github.com/apache/superset/assets/52164843/c0fd22f0-44c7-4556-8d8f-1eecc71dcaa6)

### Environment

- browser type and version: Firefox 102.14.0esr
- superset version: docker latest-dev     (using docker-compose-non-dev.yml)
- python version: Python 3.9.17
- any feature flags active:      FEATURE_FLAGS = {"ALERT_REPORTS": True, "HORIZONTAL_FILTER_BAR": True, "DRILL_TO_DETAIL": True, "DRILL_BY": True}

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by KSPT-taylorjohn** [comment]
I've tried to debug this and have made some progress.

In models/helpers.py/get_sqla_query  there is logic to try to generate a group by.

https://github.com/apache/superset/blob/29355577f148d1210c40043ef6028804469d2c30/superset/models/helpers.py#L1590-L1608



One thing it does is use convert_tbl_column_to_sqla_col if the groupby column is also in the select list. For clickhouse db spec using _mutate_label 

https://github.com/apache/superset/blob/29355577f148d1210c40043ef6028804469d2c30/superset/db_engine_specs/clickhouse.py#L395-L401

So the sqla col that is created will have a name like ItemId_08ce3f  for the original column name ItemId
![image](https://github.com/apache/superset/assets/52164843/d90a6448-db4a-47fb-aedb-44c0bbab97a1)

The problem is that the population of the groupby_series_columns dictionary is based on checking the name of the converted column with the mutated name against a list of series_column_names that is based on the original column names .
That means they will never match so groupby_all_columns will never be populated

https://github.com/apache/superset/blob/29355577f148d1210c40043ef6028804469d2c30/superset/models/helpers.py#L1622-L1626

**Comment by sfirke** [comment]
paging @pasqualtroncone and @villebro who are listed as ClickHouse users in the Superset community database rolodex

**Comment by villebro** [comment]
@KSPT-taylorjohn thanks for the thorough debugging here. I believe you're right in your findings, and this will likely be affecting other databases as well that have to mutate column labels if certain conditions are met (Oracle, BigQuery etc). Do you think you'd be comfortable opening a PR to fix this, or do you need help with it? Essentially what needs I believe needs to be done is mutating the labels in the outer join so that they match the labels from the inner query.

**Comment by pasqualtroncone** [comment]
@KSPT-taylorjohn Confirmed. Tested locally with Superset 2.1.0. This happens only when using clickhouse-connect as a connector to clickhouse, but I think you are already aware of that. If you can do a PR as @villebro suggested, then great!. Otherwise, you can still use the previously recommended driver by installing `clickhouse-driver==0.2.6` and `clickhouse-sqlalchemy==0.2.4`.

**Comment by villebro** [comment]
@pasqualtroncone if the mutator is no longer needed, let's remove it. However, when developing the engine spec I distinctly remember there being some reason for having it there, but I forget exactly what. So let me refresh my memory on that..

**Comment by KSPT-taylorjohn** [comment]
Thanks @villebro.
I might not be understanding correctly, but I don't think the problem is the labels matching of the outer and inner queries the join built starting at  
https://github.com/apache/superset/blob/29355577f148d1210c40043ef6028804469d2c30/superset/models/helpers.py#L1964-L1965

Because the ```groupby_series_columns``` isn't being populated in the first place.

What I did to fix it was simply change the outer.name to outer.key for checking if the created outer column is in the list of the series_column_names

```python
    if (
                    is_timeseries and not series_column_names
                ) or outer.key in series_column_names:
                    groupby_series_columns[outer.name] = outer
                select_exprs.append(outer)
```

**Comment by KSPT-taylorjohn** [comment]
Hi @villebro 
Thanks. I like that better since it makes more explicit what is happening.  The dependence on .key, (https://pydocbrowser.github.io/sqlalchemy/latest/sqlalchemy.sql.elements.Label.html#key) is definitely less clear.

**Comment by villebro** [comment]
@KSPT-taylorjohn I'm open to both - feel free to open a PR and tag me for a review, or let me know if you want me to do it!

**Comment by villebro** [comment]
Btw looking at that query, it could be nice to give an alias to the series limit subquery, similar to how we're aliasing virtual datasets to `virtual_table`. Maybe something like `series_limit`. But totally optional.

**Comment by jsvdvis** [comment]
This issue still seems to exist for Pivot tables, at least under version 4.02. The series limit gets completely ignored, similar to the original bug report. I couldn't see an immediately obvious cause, if I can find the time I can do a deeper dive later.
