### ISSUE TITLE
How to remove the ... in superset dashboard for end users?

### ISSUE THREAD

**Issue by Gokul2023-work** [apache/superset#25075]
## Screenshot
<img width="270" alt="Screenshot 2023-08-24 at 8 04 47 PM" src="https://github.com/apache/superset/assets/129675794/ab1e2afa-856f-4880-9a1f-a9f7589b9f77">

<img width="1153" alt="Screenshot 2023-08-24 at 8 01 55 PM" src="https://github.com/apache/superset/assets/129675794/11d4a1b8-1c9a-4822-b145-7ac5e785fab5">

## Description

I am designing a dashboard to be used for reporting purposes. I have embedded the dashboard into my application. I have given gamma permission to end users who will be customers for our application. I want to know how to remove the three dots button that appear in the right top side corner in the dashboard as that is a requirement. Can somebody help me with this. This is my first time designing dashboards in superset. I have attached the screenshots of the permissions used for the end user.

**Comment by matheusbsilva** [comment]
Have you tried setting `hideTitle` , `hideTab` and `hideChartControls` options to true on the [embedding sdk](https://github.com/apache/superset/tree/master/superset-embedded-sdk)?
```js
embedDashboard({
      id: '...',
      supersetDomain: '...',
      mountPoint: element,
      fetchGuestToken: this.fetchGuestToken.bind(this),
      dashboardUiConfig: {
        hideTitle: true
        hideTab: true,
        hideChartControls: true
      }
    })
```

**Comment by Valinaa** [comment]
@Gokul2023-work You can try to add param `?standalone=2` while viewing dashboard to hide the title and dots(actually it hides the whole row), perform like below.

![image](https://github.com/apache/superset/assets/102314964/e5def78e-231a-4e08-914b-f894e6862ee1)

**Comment by Gokul2023-work** [comment]
Both of these options are good, for my use case, I went with @matheusbsilva suggestion. It hid the title bar as well, so I added a new header to show the title. The help you both provided is much appreciated. Thank You.
