### ISSUE TITLE
The order of the columns in the charts is disordered

### ISSUE THREAD

**Issue by kk467415728** [apache/superset#25084]
Dear Team,
   When I use charts,after synchronizing columns from source, the order of the displayed columns is disordered.
Can you optimize it? The order in which columns are displayed on the web can be controlled by us.
In addition, Can you add a folder management feature to all columns? when we have a lot of dimension columns, similar dimension columns can be placed in one folder for easy management and search.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and is a feature request rather than a bug. If this is relevant in current versions (currently 3.x) please open a new Ideas discussion or a PR to address the problem.
