### ISSUE TITLE
The front-end uses the '@ superset ui/embedded sdk' sdk to embed the superset dashboard page. Click on '...' in the upper right corner of the page When the button is clicked and the 'Enter fullscreen' menu option is clicked, the embedded dashboard page remains loaded. How can I fix this?

### ISSUE THREAD

**Issue by githubid0719** [apache/superset#25122]
The front-end uses the '@ superset ui/embedded sdk' sdk to embed the superset dashboard page. Click on '...' in the upper right corner of the page When the button is clicked and the 'Enter fullscreen' menu option is clicked, the embedded dashboard page remains loaded. How can I fix this?

**Comment by Vitor-Avila** [comment]
@githubid0719 not sure if this could be related with https://github.com/apache/superset/pull/26412 -- let me know!

**Comment by rusackas** [comment]
Seems related... the fullscreen button wasn't working before (and wasn't supposed to). Now that it's hidden, I think this issue is a moot point. Closing as resolved, but happy to revisit/reopen if there's anything further to do here.
