### ISSUE TITLE
Side native filters in a dashboard is causing Superset to completely freeze

### ISSUE THREAD

**Issue by vcianciarelli** [apache/superset#25132]
I'm using a side native filters in one of my dashboards and it breaks Superset. I'd have to exit the browser tab because nothing is clickable.

#### How to reproduce the bug

1. Create a dashboard
2. Add a chart.  
3. Click `ADD/EDIT FILTERS`. I used filter type, `value` and set up filter configuration in this way:
<img width="870" alt="Screenshot 2023-08-30 at 4 01 34 PM" src="https://github.com/apache/superset/assets/37092143/2f4f91c1-5057-4198-8042-5bda4f2d2119">

And click Save.
4. Then the dashboard freezes and nothing is clickable. After a few minutes, then I get this popup:

<img width="453" alt="Screenshot 2023-08-30 at 3 54 59 PM" src="https://github.com/apache/superset/assets/37092143/d0b615ff-bc65-4003-afbb-06baa6ba843f">

5. Anytime I go to the dashboard, it immediately crashes and I can't do anything. 

### Expected results

To be able to view the dashboard

### Actual results

Superset crashes

#### Screenshots

Let me know if more screenshots are needed

### Environment

(please complete the following information):

- browser type and version: Chrome 115
- superset version: latest master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar. --> Not sure if it's the same issue but it also reported that the dashboard crashed. The reason may be due to the fact that there were too many filters (see issue https://github.com/apache/superset/issues/23311). I only used one filter.

### Additional context

Since it immediately crashes, no errors show up in DevTools or in the logs. 

I noticed in the Network tab that the request to `/api/v1/chart/data` sometimes doesn't get a response. This is probably why I don't see the filter whenever I go to the dashboard. Trying to load the filter for Game ID is probably what is causing the crash:

<img width="1011" alt="Screenshot 2023-08-30 at 4 13 17 PM" src="https://github.com/apache/superset/assets/37092143/2a8c8a66-7931-460e-a713-46090897d740">

Before upgrading to Superset 2.x, we didn't have any issue with the native filters.

**Comment by sfirke** [comment]
Does this issue persist?  What version of Superset are you on?  I wonder if this issue is still relevant to be open from the point of view of patching and improving Superset.
