### ISSUE TITLE
Custom SQL with sub queries no longer works

### ISSUE THREAD

**Issue by zhaorui2022** [apache/superset#25155]
We have some charts with sub queries in custom SQL. It was working in 2.0.0, but not in 3.0.0rc3. Not completely sure if it is expected behavior or a regression. We are using Presto as backend.

#### How to reproduce the bug

1. Create a chart, and in the custom SQL filter, use a sub query
2. Refresh the page and see error

### Expected results

Chart renders as expected as in 2.0.0

### Actual results

Chart fails to render

#### Screenshots

In 3.0.0rc3
![Screenshot 2023-08-31 at 2 25 31 PM](https://github.com/apache/superset/assets/105950525/660b7b3e-591c-4eda-b88d-309cf68c4a23)

In 2.0.0
![Screenshot 2023-08-31 at 2 25 46 PM](https://github.com/apache/superset/assets/105950525/220f034e-d36e-465e-912d-c87166a4df20)

### Environment

(please complete the following information):

- browser type and version: Chrome latest stable version
- superset version: `superset version` 3.0.0rc3
- python version: `python --version` 3.9
- node.js version: `node -v`
- any feature flags active: I don't find any related feature flag

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by michael-s-molina** [comment]
Hi @zhaorui2022. Does setting `ALLOW_ADHOC_SUBQUERY = True` resolves this issue? It's `False` by default.

**Comment by michael-s-molina** [comment]
I submitted https://github.com/apache/superset/pull/25161 to include a note in `UPDATING.md` about that change.

**Comment by michael-s-molina** [comment]
@zhaorui2022 Closing this as I believe the feature flag configuration will resolve your problem. Feel free to reopen the issue if that's not the case.
