### ISSUE TITLE
On Windows, After Login I get a Blank Page with a Close Button Only

### ISSUE THREAD

**Issue by dungeontiger** [apache/superset#25171]
I have followed the steps to run superset on Windows via docker. I've deleted everything and tried a number of times which results in the same issue.

#### How to reproduce the bug

I followed this reference: https://superset.apache.org/docs/installation/installing-superset-using-docker-compose/

1. Changed my BIOS to enable virtualization
2. Installed Docker Desktop
3. Updated wsl
4. Cloned the superset repo
5. From the superset folder run `docker compose up`
6. Wait for it to appear to be ready
7. From a Chrome navigate to `localhost:8088`
8. Log in with admin / admin

I have repeatedly tried stopping and starting the system but it always just dumps me in this empty page.

### Expected results

Get the main page for Superset

### Actual results

Get a blank window

#### Screenshots

![image](https://github.com/apache/superset/assets/1786197/15597386-2db9-43f6-ac76-1bfef2cb0efa)

![image](https://github.com/apache/superset/assets/1786197/bc4259f3-fc78-448a-91ba-32fe7d1a78b0)

### Environment

- Chrome Version 116.0.5845.141 (Official Build) (64-bit)
- superset version: `superset version` : this command did not work for me, I have what ever was in develop today in github
- Python 3.11.1
- node.js version: v18.13.0`
- any feature flags active: I have made no changes to the system

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any. 
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar. (the resolution did not work for me)

### Additional context

[console.txt](https://github.com/apache/superset/files/12505958/console.txt)

**Comment by Valinaa** [comment]
@dungeontiger Is the `console.txt` your whole logs of deployment?
It seems that the `frontend` has not been built, and is there `assets` in your `static` directory?
![image](https://github.com/apache/superset/assets/102314964/3c777ee0-911d-432e-9104-301ede67aaad)

**Comment by dungeontiger** [comment]
This is what I see in my static folder:

![image](https://github.com/apache/superset/assets/1786197/385cfc63-636c-47b1-9333-894140930679)

And  yes that is supposed to be the entire output from the console.

**Comment by webobite** [comment]
It’s window system, even I also face the similar issue. can you also check the resources that is been used by the doctor whenever you are trying to run the superset docker file ?

this error usually comes when the note part of the containers does not get billed successfully

one hacks way to run the same is try rebuilding the container manually by getting inside the Linux instance running in docker.

If resources from your system getting lapse before the whole build is complete, try allocating minimum 8 gb to this process in WSL. And do run these two commands 
For deleting the volumes which are unused by `docker compose down - v ` And `docker system prune — all` to do system prune and then do fresh start.

thanks & regards 
Subham

**Comment by dungeontiger** [comment]
That did the trick.  Thank you.  I edited the `.wslconfig` file to allocate 12 GB. I deleted the container and the image and restarted it.  All good!

**Comment by ShafwanAhmedDehan** [comment]
Where you get the .wsconfig file to edit facing same error

**Comment by kevinlbatchelor** [comment]
@ShafwanAhmedDehan you have to create it in your user home dir: C:\Users\<user>

That didn't help me.

 Looks like the node container is crashing or not installing npm packages correctly. I keep getting this error:
`[webpack-cli] Failed to load '/app/superset-frontend/webpack.config.js' config
superset_node         | [webpack-cli] Error: Can not access zstd! Is it installed?`

**Comment by riekusr** [comment]
currently have the same issue with docker on debian 

`> superset@0.0.0-dev dev

> webpack --mode=development --color --watch

[webpack-cli] Failed to load '/app/superset-frontend/webpack.config.js' config

[webpack-cli] Error: Can not access zstd! Is it installed?

    at Object.<anonymous> (/app/superset-frontend/node_modules/simple-zstd/index.js:15:9)

    at Module._compile (node:internal/modules/cjs/loader:1469:14)

    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)

    at Module.load (node:internal/modules/cjs/loader:1288:32)

    at Module._load (node:internal/modules/cjs/loader:1104:12)

    at Module.require (node:internal/modules/cjs/loader:1311:19)

    at require (node:internal/modules/helpers:179:18)

    at Object.<anonymous> (/app/superset-frontend/webpack.proxy-config.js:20:28)

    at Module._compile (node:internal/modules/cjs/loader:1469:14)

    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)`
