### ISSUE TITLE
Filter selects all available options (not just the one you select) when filter is set with "dynamically search all filter values" option

### ISSUE THREAD

**Issue by andresperezitop** [apache/superset#25178]
Hello, I've been experiencing the following issue regarding filters.

#### How to reproduce the bug
Having a filter added on the left hand side panel with the option "dynamically search all filter values" activated:
1. Start typing in the filter field to search a specific value. The search must narrow the values to **only one coincidence**.
2. Click on the value to filter the information and show only that result.

### Expected results

Filtering the information to show what corresponds to the value I chose from the filter field.

### Actual results

It automatically selects all values as if I had clicked the "Select All" option.

#### Screenshots

![image](https://github.com/apache/superset/assets/142980138/306d1fcf-63a6-468a-8f3d-690444b6d88f)
![image](https://github.com/apache/superset/assets/142980138/f4e23a17-fe4d-4712-ae44-02c5586b6c02)
![image](https://github.com/apache/superset/assets/142980138/ef0c6f4a-5c08-498c-bb7a-cf17b0292ba9)

### Environment

- browser type and version: Brave 1.57.57
- superset version: 2.1.0
- python version: Python 3.8.16

**Comment by yousoph** [comment]
I noticed this happening on charts as well. In the case of charts, I'm seeing it happen when multiple filter options are selected  
![image](https://github.com/apache/superset/assets/10627051/ee19057c-d0cb-4d19-8825-6f8d6a1d88db)

After saving, then clicking into the filter again: 
![image](https://github.com/apache/superset/assets/10627051/c2db825d-12a3-49d4-9f5c-977c1ea380bc)


cc @michael-s-molina would you be interested in taking a look? If you're busy, let me know and I can try to help find an owner

**Comment by michael-s-molina** [comment]
@andresperezitop I can't reproduce your issue on master so the a fix was already provided and will be available in 3.0. The fix may also be included in 2.1.1 which was released recently.

@yousoph I was able to reproduce your issue on master and submitted a fix [here](https://github.com/apache/superset/pull/25202).
