### ISSUE TITLE
Superset Alerts & Reports showing unformatted dashboard in email screenshot

### ISSUE THREAD

**Issue by livwel-populus** [apache/superset#25187]
When an Alert or Report is created in Superset, the resulting email does not show the current dashboard.

### Expected results
Here is my dashboard (note the number formatting)
![image](https://github.com/apache/superset/assets/137791345/ad1f6a28-4840-4606-a180-0a44b5e3923a)

### Actual results
Here is the screenshot that is sent to me via email when a report is run
![image](https://github.com/apache/superset/assets/137791345/eba7c6d0-9109-480b-9878-488579c6c7a8)

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: 3.0.0rc3
- python version: 3.11.4
- node.js version: v18.16.0
- any feature flags active:
FEATURE_FLAGS = {"ALERT_REPORTS": True}

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
- Ignore cache when generating report is ON (I have the same error with it off as well)
- Log Retention = 90 days
- Working Timeout = 1000

**Comment by sfirke** [comment]
I can't replicate this on 3.0.0rc3.  I have big number charts formatted as 5,889 and 199M and it looks identical in the email report and the dashboard.

Can you isolate the specific formatting that isn't getting applied?  And are you sure those are the same tab on the same dashboard? The first number varies greatly between those two screenshots.
