### ISSUE TITLE
Refused to evaluate a string as JavaScript ... - CSP error - Handlebars plugin - 3.0.0rc3

### ISSUE THREAD

**Issue by qleroy** [apache/superset#25205]
Handlebars chart do not work in 3.0.0rc3, CSP directive error thrown.

#### How to reproduce the bug

1. Install the 3.0.0rc3
```bash
wget https://dist.apache.org/repos/dist/dev/superset/3.0.0rc3/apache-superset-3.0.0rc3-source.tar.gz
tar xvf apache-superset-3.0.0rc3-source.tar.gz
cd apache-superset-3.0.0rc3
TAG=3.0.0.rc3 docker compose -f docker-compose-non-dev.yml up -d
```
2. Go to http://localhost:8088 and create a new Handlebars chart
3. Drop a column in Dimensions, Update Chart and observe the error thrown in the preview.

### Expected results

My usage of Handlebars plugin was fine with 2.1.1.

### Actual results

The preview throws the following error : 

> Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'strict-dynamic' 'nonce-7KRSJaEnmAisBJqk_9uAC0RXNd4Gc9NE'".

in Safari and Chrome

this error:

> call to Function() blocked by CSP

in Firefox.

#### Screenshots

<img width="1470" alt="Screenshot 2023-09-06 at 15 28 43" src="https://github.com/apache/superset/assets/9881262/11b7b867-a028-4920-aba7-f43510d3063a">

**Comment by michael-s-molina** [comment]
Hi @qleroy. This is a CSP restriction by design. Please check https://superset.apache.org/docs/security/#content-security-policy-csp on how to resolve the issue.

**Comment by goto-loop** [comment]
@michael-s-molina Do I understand correctly that the only way to make the Handlebars Chart work in a production environment is by allowing `unsafe-eval` in our CSP?

**Comment by michael-s-molina** [comment]
> @michael-s-molina Do I understand correctly that the only way to make the Handlebars Chart work in a production environment is by allowing unsafe-eval in our CSP?

I believe so but will tag @rusackas who has more knowledge about the Handlebars chart to confirm.
