### ISSUE TITLE
Can't save dataset when there are column changes in 3.0.0rc3

### ISSUE THREAD

**Issue by zhaorui2022** [apache/superset#25210]
When there are column changes in the source data, after syncing columns from source, it doesn't allow to save the dataset any more.

#### How to reproduce the bug

1. Create any dataset.
2. Use SQL Lab or any other tool to alter the table by adding a dummy column
3. Edit the associated dataset, click on columns tab, click on sync columns from source, wait until it's finished.
4. Save and see error

### Expected results

Being able to save the modified dataset

### Actual results

Unable to save the modified dataset

#### Screenshots

https://github.com/apache/superset/assets/105950525/a745cdcd-b2e4-4812-9cfc-8763a3badb3a

### Environment

(please complete the following information):

- browser type and version: Chrome latest version
- superset version: `superset version` 3.0.0rc3
- python version: `python --version` 3.9
- node.js version: `node -v` N/A
- any feature flags active: I am not aware a feature flag related with this issue

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by michael-s-molina** [comment]
@zhaorui2022 I was not able to reproduce the problem using a Postgres database. 

https://github.com/apache/superset/assets/70410625/240aaff3-3505-4a03-b93b-b204f7ee8fa5

@justinpark Were you able to reproduce this?

**Comment by justinpark** [comment]
> zhaorui2022 I was not able to reproduce the problem using a Postgres database.
> 
>  Screen.Recording.2023-09-07.at.10.16.56.mov 
> justinpark Were you able to reproduce this?

same. I cannot reproduce this problem in my local environment. @zhaorui2022 could you share more details? (or could you check that you have a calculated column(or metric) named `hour_ts`?
