### ISSUE TITLE
Couldn't edit the Time Series Columns in Time Series Table

### ISSUE THREAD

**Issue by minhlb** [apache/superset#25227]
When adding the Time Series Column to a Time Series Table, there isn't any edit button on the bar.

#### How to reproduce the bug

1. Go to: Create Chart, select the Time Series Table
2. Click on: add Time Series Columns
3. See error: cannot find the edit button for new Time Series Column

### Expected results
The Edit button to update the properties for Time Series Column

#### Screenshots

![image](https://github.com/apache/superset/assets/10129165/418108c2-4526-40f5-9691-9e89c5c27eaf)

### Environment

- browser type and version: Google Chrome 
- superset version: superset 2.1.0
- python version: Python 3.10.12
- any feature flags active: ALERT_REPORTS, DASHBOARD_RBAC, HORIZONTAL_FILTER_BAR

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by michael-s-molina** [comment]
Hi @minhlb. I can't reproduce this on `master`. Can you reproduce this on 2.1.1?

**Comment by minhlb** [comment]
> Hi @minhlb. I can't reproduce this on `master`. Can you reproduce this on 2.1.1?

I upgraded to version 2.1.1 and the issue has gone.  Thanks for your suggestion.
