### ISSUE TITLE
Bugs with the currency format control

### ISSUE THREAD

**Issue by michael-s-molina** [apache/superset#25234]
While testing the currency format control I found some bugs:

**When you clear the currency format, the changes are not reflected in the viz.**

https://github.com/apache/superset/assets/70410625/12e5847f-8cff-4ce6-a406-ba864efd0987

https://github.com/apache/superset/assets/70410625/a363cef3-442d-42d6-9d02-2f99a55fb4dc

These are just examples for Table and Pivot Table but we should check all supported charts for this problem. It seems the control is not handling the Select `onClear` event.

Currency format is not working for the Table chart when in Raw Records mode.

https://github.com/apache/superset/assets/70410625/7e9609f6-bf71-4103-9bb0-f954fdb2e4db

### Environment

- superset version: `master`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by michael-s-molina** [comment]
@sadpandajoe @jinghua-qa

**Comment by michael-s-molina** [comment]
@kgabryje I fixed the problem with clearing the Currency Format [here](https://github.com/apache/superset/pull/25238).

**Comment by kgabryje** [comment]
Fix for the treemap bug: https://github.com/apache/superset/pull/25249
Fix for raw table: https://github.com/apache/superset/pull/25248

**Comment by michael-s-molina** [comment]
Closed by the referenced PRs.
