### ISSUE TITLE
How to Embedding Dashboard  Apache Superset to our React app?

### ISSUE THREAD

**Issue by Narender-007** [apache/superset#25232]
*Please make sure you are familiar with the SIP process documented*
(here)[https://github.com/apache/superset/issues/5602]. The SIP will be numbered by a committer upon acceptance.

##How to Embedding Dashboard  Apache Superset to our React app?

### need to Implement embedding dashboard apache superset to external applications.

Description of the problem to be solved.

**Comment by sfirke** [comment]
Hello, this is not a bug report and certainly not a SIP.  I will close this accordingly.

I saw you posted in Slack, that's a good place to ask questions like this although this is so broad that your best bet is to search the web for guides on how to do this.  When I type "embed superset dashboard" into Google the first page of search results look promising.  Good luck and feel free to post in Slack with more specific questions, there is a channel just for embedded Superset.
