### ISSUE TITLE
Dashboard import loses some charts while other charts remain correctly 

### ISSUE THREAD

**Issue by ceeyeoMV** [apache/superset#25256]
Hello, I encountered a problem about importing dashboard.
First, I have deployed a superset service by helm chart, and I configured the data connection, created some meaningful dashboards use the superset UI.
Then, I want deployed another superset service by helm chart and I want to reuse some dashboards in the new service. So I tried to use the export function in the superset UI. Blow is what I did.
1. I chose a wanted dashboard and clicked the export button in the old UI 
![image](https://github.com/apache/superset/assets/138500283/adec9905-b9c3-4c31-954f-ddf104af7bf3)
2. After downloading the .zip file, I chose import button in the new UI
![image](https://github.com/apache/superset/assets/138500283/f03367f6-3424-48df-a710-10984bebdef2)
3. Problem came when I saw the imported dashboard in the new UI, it seemed to implied that I lost the chart information
![image](https://github.com/apache/superset/assets/138500283/d0c3522d-3329-4023-b44f-b7d95459e828)
Meanwhile, there were some charts can be rendered well
![image](https://github.com/apache/superset/assets/138500283/36a79fb3-a21d-4a54-a2d3-5bfab680e3e2)
4. So I checked the content of the .zip file I download, but I found it contains all the charts information, so I wondered what's wrong with my operation? Did I do it correctly( copying dashboard from one to another )?
![image](https://github.com/apache/superset/assets/138500283/c01b9644-4598-4c63-80ed-5185388a8585)

**Comment by ceeyeoMV** [comment]
Besides, I also found that the missing charts did exist in the charts list of the new superset, but the it showed the chart wasn't added to any dashboard.
![image](https://github.com/apache/superset/assets/138500283/871a31bf-3c2a-47bf-b2c4-dca075d7f01f)

**Comment by goto-loop** [comment]
I have exactly the same problem, did you find a solution @ceeyeoMV?

**Comment by AndrewMatveev** [comment]
Were you able to find the cause? I have the same problem.
