### ISSUE TITLE
After PC restart Superset won't fetch databases: Invalid decryption key

### ISSUE THREAD

**Issue by MarkupMaster** [apache/superset#25261]
I installed Superset with Pip (see [here](https://superset.apache.org/docs/installation/installing-superset-from-scratch#installing-superset-from-scratch)) on WSL Manjaro (running on Windows 11) and followed the necessary steps. 

It previously was working and I created several dashboards with it on a PostgreSQL database. However, after I restarted my PC, it found the decryption key to be invalid on the `Database Connections` page. I don't think this is a problem with my `SUPERSET_SECRET_KEY` environment variable. However, I tried to edit the `superset_config.py` file I made in `~/superset-env/lib/python3.11/site-packages/superset` to have a `PREVIOUS_SECRET_KEY` variable (from [here](https://superset.apache.org/docs/installation/configuring-superset#rotating-to-a-newer-secret_key)). I also tried to do the same thing with a `SUPERSET_` environment variable. I even ran the `superset init` command but got a `ValueError: invalid decryption key`  (#8538). Also, I ran the `superset db upgrade` command and just got warnings. (All of my secret keys were generated with `openssl rand -base64 42`**.**) 

Does anyone know how to solve this❔

**Comment by wangkun723** [comment]
Me too!

**Comment by Quartinal** [comment]
My old account was @MarkupMaster due to GitHub's whole two-factor authentication fiasco. 

But, I found a solution (at least for me)! 

The solution was to use `superset re-encrypt-secrets` after you have changed every `utf-8` string found in the file `/home/YOUR_USER/superset-env/lib/pythonX.X.X/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py` to `latin-1` 🎉

**Comment by rusackas** [comment]
Glad you found your answer! Please feel free to add a snippet to our documentation site if you think it'll help others!
