### ISSUE TITLE
CTE queries with 'UNION' are parsed as 'non-select.'

### ISSUE THREAD

**Issue by mapledan** [apache/superset#25278]
The commit #25014 will cause SQL parsing errors.
The following statement is an invalid select statement:
`with base as(select id from table1 union all select id from table2) select * from base`

<img width="835" alt="image" src="https://github.com/apache/superset/assets/16112914/4c9d1e26-7f5d-44f7-baeb-8ba9991488aa">

**Comment by mapledan** [comment]
It's duplicate #25266.

**Comment by sfirke** [comment]
tagging @betodealmeida who reviewed the PR you linked (thanks for finding that!)

**Comment by betodealmeida** [comment]
Fixed in https://github.com/apache/superset/pull/25290
