### ISSUE TITLE
Time offset not applied to timestamp field on table chart when granularity is not selected

### ISSUE THREAD

**Issue by matheusbsilva** [apache/superset#25272]
The time offset configured on the dataset is only applied when a time granularity is select on the table chart.

#### How to reproduce the bug

1. Create a dataset and define a hour offset;
2. Create a chart of type table using the created dataset;
3. Add a timestamp field to the table;
4. Don't select a time granularity;
5. The hour offset will not be applied to the timestamp field.

### Expected results

The hour offset should be applied regardless the granularity is selected or not.

### Actual results

The hour offset is only applied when a time granularity is selected.

#### Screenshots

"Código" is a unique identifier to that record, with the granularity selected to "seconds" the time offset of **-3 hours** is applied to the timestamp field "Data de abertura":
![Captura de tela de 2023-09-12 11-21-58](https://github.com/apache/superset/assets/14370340/97f6cdd9-8f4e-4dd6-b57a-bc6802a425fa)

Without the granularity selected, the offset is not applied:
![Captura de tela de 2023-09-12 11-22-09](https://github.com/apache/superset/assets/14370340/2fb78051-9c9d-4aee-a1b7-a871b196fcec)

### Environment

(please complete the following information):

- browser type and version: Chrome 116.0.5845.179
- superset version: `3.0.0rc3`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active: `ALERT_REPORTS`, `EMBEDDED_SUPERSET`, `DASHBOARD_RBAC`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by michael-s-molina** [comment]
Hi @matheusbsilva. I wasn't able to reproduce this on the 3.0.0 RC3 test environment. Can you try to reproduce there? Here's the [link](http://35.86.112.125:8080/).

https://github.com/apache/superset/assets/70410625/6ade2a35-10d0-48f8-a8ff-ee4889adeb59

**Comment by matheusbsilva** [comment]
Hey @michael-s-molina, thanks for the response. I couldn't connect to the test environment, but I executed the version 3.0.0rc3 using the non dev docker configuration in my local machine and I couldn't reproduce neither, probably I was running an outdated version in my machine when I experienced this problem, sorry for the false alarm. But during my tests I've found another possible bug. The Raw records option on the table chart does not apply the hour offset:
 
https://github.com/apache/superset/assets/14370340/6da41d17-dd68-42a2-919d-d55a4131664a

**Comment by matheusbsilva** [comment]
I noticed the relative timestamp filters do not consider the hour offset. In this example my dataset is set to `-3` hour offset, when I try to search by the last day it searchs based on the UTC time stored at the database, so I get results from `2023-09-11 21:00:00 GMT -3` to `2023-09-12 20:59:59 GMT -3`, I should get results from `2023-09-12 00:00:00 GMT -3` to `2023-09-12 23:59:59 GMT -3`:




https://github.com/apache/superset/assets/14370340/5fd8b4b6-ef71-4d52-ae7b-38c43d9c8102

**Comment by michael-s-molina** [comment]
Hi @matheusbsilva. Thank you for the recordings. It seems the Time Offset feature is not implemented for all use cases as we can see by your videos. Are you able to fix this issues? If not, let's wait for fixes from the community. As soon as they arrive, I'll cherry-pick them into 3.0.X.

**Comment by matheusbsilva** [comment]
I can fix it. Can you give a direction of where on the codebase I should be looking to solve this? I would like to focus on the filtering first, because it's affecting my team.

**Comment by michael-s-molina** [comment]
Thanks @matheusbsilva. I would start with [query_context_processor](https://github.com/apache/superset/blob/master/superset/common/query_context_processor.py). I'll also tag @villebro @zhaoyongjie in case they know something that can help you.

**Comment by matheusbsilva** [comment]
@michael-s-molina I created a PR to solve the filtering issue: #25331.

**Comment by zhaoyongjie** [comment]
@matheusbsilva I think the time offset in dataset has some incorrect design in its initial, as it 1) only accepts integer values, and 2) does not account for daylight saving time. This feature should be redesigned rather than simply patched.

**Comment by matheusbsilva** [comment]
@zhaoyongjie I agree, do you have any idea on how to redesign it?

**Comment by zhaoyongjie** [comment]
@matheusbsilva our owned folk-Superset removed this function and redesign the timezone in the dataset, we can select specific timezone in the dataset and timezone also applied in the time filter as well, the specific timezone function push down to the database rather than convert timezone in superset side. 

<img width="864" alt="image" src="https://github.com/apache/superset/assets/2016594/8246eea4-14c4-404d-ad0b-5d7b1b968701">

**Comment by rusackas** [comment]
Hi all... just checking to see if these contributions are likely to take shape, as the issue is otherwise at risk of being closed as stale. Or feel free to close this if there are no intentions to act on it in the foreseeable future.

**Comment by rusackas** [comment]
Closing as stale... but always happy to reopen if there's renewed interest!
