### ISSUE TITLE
Can't connect to Dedicated SQL pool (formerly SQL DW)

### ISSUE THREAD

**Issue by tffernandes** [apache/superset#25271]
Try to create a new Connect to a database but got a error ussing pyodbc and pymssql, 
anyone got a conected to Dedicated SQL pool  sucessful?

Im running the super set on a docker img.
The paramters of the connection string work on other aplications

#### How to reproduce the bug

1. Go to 'DATA'
2. Click on 'Connect a database'
3. Select  "Azure Synapse"
4. Paste the conection string to a Dedicated SQL pool 
5. click test connection
6. See error

### Expected results

Create a connection to a Dedicated SQL pool 

### Actual results

got many errors

#### Screenshots
Connection string format: mssql+pymssql://User:password@XXXXX.database.windows.net:Port/DataBase
![image](https://github.com/apache/superset/assets/10014026/2ebfade0-409e-4212-98fc-746bfa3efb78)

Connection string format: mssql+pyodbc://User:password@XXXXX.database.windows.net:Port/DataBase?driver=ODBC+Driver+17+for+SQL+Server
![image](https://github.com/apache/superset/assets/10014026/d112b9ee-eb09-44b7-99b2-bd6fc2128827)

### Environment

(please complete the following information):

- browser type and version: Chome VERSION116.0.5845.180 64 bits
- superset version: `apache-superset 0.0.0.dev0`
- any feature flags active: NO

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ X ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ X ] I have reproduced the issue with at least the latest released version of superset.
- [ X ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Im running the super set on a docker img.
The paramters of the connection string work on other aplications

**Comment by stefaan1o** [comment]
I ran into the same issue. I could connect successful after adding `autocommit=True` parameter to the connection string.

```
mssql+pyodbc://<Username>:<Password>@<Host>:<Port>/<DatabaseName>?autocommit=True&driver=ODBC+Driver+17+for+SQL+Server
```

**Comment by rusackas** [comment]
This looks like it was filed right before Superset 3.0.0 came out. Sorry it's has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and since it's been a while since this thread saw any activity, I'll close this as stale. If it is still an issue in Superset 3.x or newer, we can easily re-open this, or feel free to open a new issue with updated context. Thanks!
