### ISSUE TITLE
Emails (alerts/reports) cannot be send via chromium - documentation should be updated to work again with STABLE CHROME

### ISSUE THREAD

**Issue by nigzak** [apache/superset#25284]
The email documentation for email alerts does not work anymore for chromium - probably since V115 
(there was a change where chromium is stored since this date)

=> the docu should be updated

#### How to reproduce the bug

follow https://superset.apache.org/docs/installation/alerts-reports/ to set up chromium

### Problem
Email does not work:

- 1st issue: "stable" is not compatible with V102 in this howto - the howto is complete outdated
- 2nd issue: since V115 the chromium is not able to be downloaded as explained, you cannot use LATEST_RELEASE_117 as example
- 3rd issue: since V115 it seems the default folder of chromium unzip changed (there is a subfolder now)

before V115 chromedriver unzip it was stored into /usr/bin/chromedriver
after 115 is is unzip into /usr/bin/chromedriver-linux64/chromedriver

If the folder is not MANUALLY changed (unzip and use subfolder) superset does not find the executable chromedriver files

```
// from docu 13.09.2023
RUN export CHROMEDRIVER_VERSION=$(curl --silent https://chromedriver.storage.googleapis.com/LATEST_RELEASE_102) && \
    wget -q https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip && \
    unzip chromedriver_linux64.zip -d /usr/bin && \
    chmod 755 /usr/bin/chromedriver && \
    rm -f chromedriver_linux64.zip
```

### Environment

(please complete the following information):

- browser type and version: chrome
- superset version: 2.1.1

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### fix for this issue

This change does fix this behaviour - probably you can still improve it somehow if required/possible

```
RUN apt-get update && \
    wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    apt-get install -y --no-install-recommends ./google-chrome-stable_current_amd64.deb && \
    rm -f google-chrome-stable_current_amd64.deb

# refer https://googlechromelabs.github.io/chrome-for-testing/
RUN export CHROMEDRIVER_VERSION=$(curl --silent https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_STABLE) && \
    wget -q https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${CHROMEDRIVER_VERSION}/linux64/chromedriver-linux64.zip && \
    unzip chromedriver-linux64.zip && \
    mv chromedriver-linux64/* /usr/bin/ && \
    chmod 755 /usr/bin/chromedriver && \ 
    rm -f chromedriver-linux64.zip && \
    rm -f -r chromedriver-linux64
```

IT uses the new chrome-for-testing JSON api to get the current STABLE RELEASE which should match the CHROME_STABLE_RELEASE
It unzips the folder (which is having a SUBFOLDER of "chromedriver-linux64" to the current dir
Than it copies all files from this folder to /usr/bin and chmod the file to 755
than it deletes the zip + extracted folder again from current dir

With this the report works again

![image](https://github.com/apache/superset/assets/102737855/d743cb2f-0137-4829-b3fb-6e5a58552425)

**Comment by sfirke** [comment]
Would you want to submit a pull request with these changes?  Or do you think your suggestion needs input / review from others using Chrome?  I use Firefox for this function so can't be of help here.

**Comment by nigzak** [comment]
Hi @sfirke 

sorry for my late response.
I already made a ticket months ago (or years? dont exactly know :D ) for same reason that this documentation is outdated.
Last time there was mentioned that using "stable" is probably bad and they want to have more control while using a dedicated version.

The "stable" and "fixed version" of chrome in combination with chromedriver this will be always "probably" getting issues after some time and as result this documentation is probably more often outdated and not working.
Because of my last ticket I am not sure if now it is valid for all to use "stable" instead of a fixed version - in any case the current documentation is not working at all if you follow it.

If you let me know how to make a pullrequest for documentation I can also do this? I tought here it is only for the code inside GIT? I am sorry for this, I never did a pull request up to now and probably have to read some documentation for this before I make something bad ... (is there some good link/howto somewhere available which explains it in short words which you could suggest me to read?)

In general I am already using the change live in my superset and it is working already a longer time - so at least it is good enough to bring it to work which is at least better than the current documentation.

**Comment by Naich** [comment]
The current CHROMEDRIVER_VERSION is 114, but the latest version of Chrome may be greater than 114 (for instance, it is currently 119). So the code you suggested might not solve the error.

Unfortunately, there is no officially certified historical version available for download from Google. Considering this, perhaps we should consider using Chromium instead.

> The email documentation for email alerts does not work anymore for chromium - probably since V115 (there was a change where chromium is stored since this date)
> 
> => the docu should be updated
> 
> #### How to reproduce the bug
> follow https://superset.apache.org/docs/installation/alerts-reports/ to set up chromium
> 
> ### Problem
> Email does not work:
> 
> * 1st issue: "stable" is not compatible with V102 in this howto - the howto is complete outdated
> * 2nd issue: since V115 the chromium is not able to be downloaded as explained, you cannot use LATEST_RELEASE_117 as example
> * 3rd issue: since V115 it seems the default folder of chromium unzip changed (there is a subfolder now)
> 
> before V115 chromedriver unzip it was stored into /usr/bin/chromedriver after 115 is is unzip into /usr/bin/chromedriver-linux64/chromedriver
> 
> If the folder is not MANUALLY changed (unzip and use subfolder) superset does not find the executable chromedriver files
> 
> ```
> // from docu 13.09.2023
> RUN export CHROMEDRIVER_VERSION=$(curl --silent https://chromedriver.storage.googleapis.com/LATEST_RELEASE_102) && \
>     wget -q https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip && \
>     unzip chromedriver_linux64.zip -d /usr/bin && \
>     chmod 755 /usr/bin/chromedriver && \
>     rm -f chromedriver_linux64.zip
> ```
> 
> ### Environment
> (please complete the following information):
> 
> * browser type and version: chrome
> * superset version: 2.1.1
> 
> ### Checklist
> Make sure to follow these steps before submitting your issue - thank you!
> 
> * [x]  I have checked the superset logs for python stacktraces and included it here as text if there are any.
> * [x]  I have reproduced the issue with at least the latest released version of superset.
> * [x]  I have checked the issue tracker for the same issue and I haven't found one similar.
> 
> ### fix for this issue
> This change does fix this behaviour - probably you can still improve it somehow if required/possible
> 
> ```
> RUN apt-get update && \
>     wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
>     apt-get install -y --no-install-recommends ./google-chrome-stable_current_amd64.deb && \
>     rm -f google-chrome-stable_current_amd64.deb
> 
> # refer https://googlechromelabs.github.io/chrome-for-testing/
> RUN export CHROMEDRIVER_VERSION=$(curl --silent https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_STABLE) && \
>     wget -q https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${CHROMEDRIVER_VERSION}/linux64/chromedriver-linux64.zip && \
>     unzip chromedriver-linux64.zip && \
>     mv chromedriver-linux64/* /usr/bin/ && \
>     chmod 755 /usr/bin/chromedriver && \ 
>     rm -f chromedriver-linux64.zip && \
>     rm -f -r chromedriver-linux64
> ```
> 
> IT uses the new chrome-for-testing JSON api to get the current STABLE RELEASE which should match the CHROME_STABLE_RELEASE It unzips the folder (which is having a SUBFOLDER of "chromedriver-linux64" to the current dir Than it copies all files from this folder to /usr/bin and chmod the file to 755 than it deletes the zip + extracted folder again from current dir
> 
> With this the report works again
> 
> ![image](https://private-user-images.githubusercontent.com/102737855/267692406-d743cb2f-0137-4829-b3fb-6e5a58552425.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3Mzg4NTIsIm5iZiI6MTcwMTczODU1MiwicGF0aCI6Ii8xMDI3Mzc4NTUvMjY3NjkyNDA2LWQ3NDNjYjJmLTAxMzctNDgyOS1iM2ZiLTZlNWE1ODU1MjQyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQwMTA5MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hN2IxODU2MzUwYTU4YTRjZGVkZjI1NWQ0NzQ1OGNjNTlhNDU0NmE1MWJmNmM2ZDk2NmIxODRiYzE2MmRmMThmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hREEs8TTzWvqDyVxbUdbV3__lVjKEK742KYtmlAmzRY)

**Comment by nigzak** [comment]
closing this old ticket now as it seems outdated or irrelevant
