### ISSUE TITLE
Closed Sqllab tabs come back with no queries after refreshing

### ISSUE THREAD

**Issue by zhaorui2022** [apache/superset#25289]
If we close all the tabs in Sqllab, and then refresh the page, all the previously closed tabs are back, but there is no actual queries in them. This issue happens in 2.0.0 as well since we had users reporting this issue with the production environment which was running on 2.0.0). But in 2.0.0, the query of the last tab still shows up.

#### How to reproduce the bug

1. Go to Sqllab, open a few tabs and run queries
2. Close all the tabs
3. Refresh page

### Expected results

The closed tabs are gone, and it opens a brand new tab

### Actual results

Closed tabs are back with no query in it

#### Screenshots

![Google Chrome - Superset 2023-09-13 at 3 41 20 PM](https://github.com/apache/superset/assets/105950525/44023d7d-2250-4be0-b138-e074b68f8e1b)

### Environment

(please complete the following information):

- browser type and version: Chrome latest version
- superset version: `superset version` 3.0.0rc4
- python version: `python --version` 3.9
- node.js version: `node -v` N/A
- any feature flags active: We have SQLLAB_BACKEND_PERSISTENCE set to False, so the tabs might have been stored in browser's local storage.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zhaorui2022** [comment]
I was trying to do another recording with the browser local storage and realize it seems happening as long as I refresh the page, and don't need to close all the tabs.

https://github.com/apache/superset/assets/105950525/25585ee8-2389-4082-a703-42e06aa62a97

**Comment by zhaorui2022** [comment]
I was trying to do another recording with local storage showing on the side, but found that I didn't need to close all the tabs to reproduce the issue.

![Google Chrome - Superset 2023-09-13 at 3 53 32 PM](https://github.com/apache/superset/assets/105950525/fa524059-0f11-4322-846d-defcc7bf1977)

**Comment by justinpark** [comment]
@zhaorui2022 it is a known issue when PERSISTENCE_MODE sets back to false and the user has the previous persisted data, SQL Lab continuously propagates the previous persisted query editor data to NON persistence mode.
I can take a look for the hotfix.

**Comment by zhaorui2022** [comment]
Thanks.
