### ISSUE TITLE
Dashboard chart data not shown with applied filters after using "copy permalink to clipboard" option

### ISSUE THREAD

**Issue by superset-user** [apache/superset#25298]
#### How to reproduce the bug

1. Go to any dashboard
2. Select few filters (Snapshot 1)
3. Go to "share" -> "copy permalink to clipboard" option OR use chain link (besides each chart tab) to copy permalink
4. Paste copied URL in new tab and hit enter

### Expected results

Dashboard should load with applied filters as shown in Snapshot1 & Snapshot2

### Actual results

Dashboard is loading and we can see selected filters however, chart is loading without any data (Snapshot3)

#### Screenshots
Snapshot1:
![Snapshot1](https://github.com/apache/superset/assets/144122804/37d2ed47-2c34-431f-ad4d-bc0ceb996536)

Snapshot2:
![Snapshot2](https://github.com/apache/superset/assets/144122804/55e3da3b-0b18-4ce4-8f86-37a32c5903f7)

Snapshot3:
![Snapshot3](https://github.com/apache/superset/assets/144122804/2440faf4-4252-44c6-bbaf-3398c653d66e)

### Environment

(please complete the following information):

- browser type and version: Microsoft Edge & Version 116.0.1938.81
- superset version: `2.1.0`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active: Following flags set to true: dashboard_native_filters, dashboard_cross_filters, dashboard_native_filters_set, dashboard_filters_experimental, versioned_export

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Sometimes, I receive expected results after refreshing the page 1 or 2 times, but on first try I never see expected results (Snapshot3). It's weird and seems like a bug or is it known bug and we have a solution for it? Thanks in advance.

**Comment by rusackas** [comment]
Hi there, and sorry this has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale. If it is still an issue in Superset 3.x, we can re-open this, or feel free to open a new issue with updated context.
