### ISSUE TITLE
Data Formatting is applied everywhere in box plot tooltips where it should not 

### ISSUE THREAD

**Issue by tha-bt** [apache/superset#25327]
data number format is applied every where in box plot tooltips where it should not:
   number of sample and number of outlier should have a specific adaptative formatting related to their meaning 

#### How to reproduce the bug
create box plot chart with data of type duration.
Set the number format to duration 
Display the chart and tool tips 
Number of sample and number of outlier are displayed with the wrong unit ( and are potentially converted in something unreadable) 

### Expected results
Have the number of sample and number of outlier using an adaptative 

### Actual results

number of sample and number of outlier are displayed as duration

#### Screenshots

![image](https://github.com/apache/superset/assets/133670033/d5d105a8-8c4d-4f17-938c-36f80f3dcd76)

### Environment

(please complete the following information):

browser type and version: chrome version 117.0.5938.63
superset version: 2.1,3.0RC4
python version: from docker images
node.js version: from docker images
any feature flags active: {"ALERT_REPORTS": True,"EMBEDDED_SUPERSET": True,"DASHBOARD_CROSS_FILTERS":True,"DRILL_BY":True,"DRILL_TO_DETAIL":True, "DASHBOARD_RBAC" : True,"ENABLE_TEMPLATE_PROCESSING" : True}

**Comment by rusackas** [comment]
Thanks for the PR @goto-loop. I assume this issue is alive and well in 3.x or newer... hopefully we can get that PR across the finish line and close this out :)

**Comment by rusackas** [comment]
I approved the PR and restarted CI. Ping me on [slack](http://bit.ly/join-superset-slack) if I'm not responsive here. Let's get this thing merged!
