### ISSUE TITLE
Can't create dashboard with custom role

### ISSUE THREAD

**Issue by sebastiensotoAxelor** [apache/superset#25329]
In my case I would like to make a user who only has access to a database, datasets linked to this database and dashboards linked too. I have for the moment created a custom role with all permissions only a restriction on the database. My user only sees data linked to his database. But he cannot create a dashboard !

<img width="306" alt="Capture d'écran 2023-09-18 160308" src="https://github.com/apache/superset/assets/141150497/db1df406-9cd1-42cd-9755-54d4b190fef0">

#### How to reproduce the bug

1. Go to List roles
2. Select admin role and create a copy
3. Create a user with the role created by copy of the admin 
4. Remove access as all datasource and only as one database
5. Go to dashboard menu
6. Create dashboard 
7. See problem : I can't add chart to my dashboard

<img width="932" alt="Capture d'écran 2023-09-18 160727" src="https://github.com/apache/superset/assets/141150497/76940663-959b-4263-aeb0-20e71626233d">

### Expected results

Ability to add charts that have as data sources the Example database to my dashboards. 

### Actual results

No chart can be added to my dashboard

### Environment

- browser type and version: Chrome, Version 115.0.5790.170 (Official Build) (64-bit)
- superset version: 2.0 (master)
- python version: Python 3.9.18
- node.js version: Node version: 16
- any feature flags active: 
ALERT_REPORTS": True,
    "SCOPED_FILTER": True,
    "ENABLE_TEMPLATE_PROCESSING": True,
    "DRILL_TO_DETAIL": True,
    "EMBEDDED_SUPERSET": True,
    "EMBEDDABLE_CHARTS": True,
    "THUMBNAILS": True,
    "DASHBOARD_RBAC":True,
    "THUMBNAILS_SQLA_LISTENERS": True,
    "LISTVIEWS_DEFAULT_CARD_VIEW" : True,

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Hi there... sorry this has gone silent for so long, but that's likely because we use GitHub Issues for bug reports, whereas this is a configuration question. I hope you found a way forward, but if not, let us know. We can point you to some Slack channels or Github Discussions (i.e. the Q&A section) where this might get more attention.
