### ISSUE TITLE
Horizon Chart are not working any more 

### ISSUE THREAD

**Issue by tha-bt** [apache/superset#25326]
Horizont Chart are not working any more 

Tested (docker-compose) with postgres and clickhouse (same effect) 

#### How to reproduce the bug
Create an horizont chart on a dataset containing date time column
  ( The dataset can be the log table of superset schema) 
   set the metric and dimension to use
click on update chart  

### Expected results

Display the Horizont Chart 

### Actual results
Display an error message : Datetime column not provided as part table configuration and is required by this type of chart

#### Screenshots
<img width="1134" alt="image" src="https://github.com/apache/superset/assets/133670033/f166acfb-e900-473e-8c65-3159cb8e37c3">

### Environment

- browser type and version: chrome version 117.0.5938.63 
- superset version: 3.0RC4
- python version: from docker images
- node.js version: from docker images
- any feature flags active: {"ALERT_REPORTS": True,"EMBEDDED_SUPERSET": True,"DASHBOARD_CROSS_FILTERS":True,"DRILL_BY":True,"DRILL_TO_DETAIL":True, "DASHBOARD_RBAC" : True,"ENABLE_TEMPLATE_PROCESSING" : True}

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
`172.19.0.1 - - [18/Sep/2023:10:29:05 +0000] "GET /api/v1/me/ HTTP/1.1" 200 150 "http://localhost:8088/explore/?form_data_key=fq8MEPBuqVqMJhjE4NzJ_lt88X5FWoo6FgddQ8p9PxRxXXTRQSo5xUpeJJGSEKdI&viz_type=horizon&datasource=2__table&datasource_id=2&datasource_type=table" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
Superset.explore_json This API endpoint is deprecated and will be removed in version 4.0.0
2023-09-18 10:29:07,501:WARNING:superset.views.base:Superset.explore_json This API endpoint is deprecated and will be removed in version 4.0.0
2023-09-18 10:29:07,508:DEBUG:parsedatetime:eval - with context - False, False
Cache key: 75a49a379c8de36f1f3cea158751bba9
2023-09-18 10:29:07,518:INFO:superset.viz:Cache key: 75a49a379c8de36f1f3cea158751bba9
172.19.0.1 - - [18/Sep/2023:10:29:07 +0000] "POST /superset/explore_json/ HTTP/1.1" 400 1068 "http://localhost:8088/explore/?form_data_key=fq8MEPBuqVqMJhjE4NzJ_lt88X5FWoo6FgddQ8p9PxRxXXTRQSo5xUpeJJGSEKdI&viz_type=horizon&datasource=2__table&datasource_id=2&datasource_type=table" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
172.19.0.1 - - [18/Sep/2023:10:29:07 +0000] "GET /api/v1/chart/0 HTTP/1.1" 404 24 "http://localhost:8088/explore/?form_data_key=fq8MEPBuqVqMJhjE4NzJ_lt88X5FWoo6FgddQ8p9PxRxXXTRQSo5xUpeJJGSEKdI&viz_type=horizon&datasource=2__table&datasource_id=2&datasource_type=table" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
172.19.0.1 - - [18/Sep/2023:10:29:08 +0000] "PUT /api/v1/explore/form_data/fq8MEPBuqVqMJhjE4NzJ_lt88X5FWoo6FgddQ8p9PxRxXXTRQSo5xUpeJJGSEKdI?tab_id=137 HTTP/1.1" 200 75 "http://localhost:8088/explore/?form_data_key=fq8MEPBuqVqMJhjE4NzJ_lt88X5FWoo6FgddQ8p9PxRxXXTRQSo5xUpeJJGSEKdI&viz_type=horizon&datasource=2__table&datasource_id=2&datasource_type=table" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
172.19.0.1 - - [18/Sep/2023:10:29:08 +0000] "POST /superset/log/?explode=events HTTP/1.1" 200 1 "http://localhost:8088/explore/?form_data_key=fq8MEPBuqVqMJhjE4NzJ_lt88X5FWoo6FgddQ8p9PxRxXXTRQSo5xUpeJJGSEKdI&viz_type=horizon&datasource=2__table&datasource_id=2&datasource_type=table" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"`

- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar. 
Similar issue in 2.1 from july
https://github.com/apache/superset/issues/24527 
  

Thanks a lot for your help

**Comment by Codes-Lab** [comment]
I am also facing the same issue.

**Comment by vladradishevsky** [comment]
The same issue

**Comment by canimus** [comment]
Same issue on Horizon Chart.

**Comment by rusackas** [comment]
@villebro @michael-s-molina Am I interpreting that the removal of the "Time" section (and perhaps other controls in this case) left this chart as a casualty, and nobody ever noticed? 

I think were open to PRs that will restore this functionality if anyone is interested, but it's not a highly used chart. We'd also be open to contribution of a newer (preferably ECharts-based) plugin if there are any volunteers on that front.

**Comment by jessegli** [comment]
same issue as well.

**Comment by alexray92** [comment]
Same issue on 4.0.1

**Comment by nicoPhil** [comment]
Same here on 4.0.2

**Comment by michael-s-molina** [comment]
I opened https://github.com/apache/superset/pull/30563 to fix this issue. It will be available in 4.1.0.
