### ISSUE TITLE
The checksums are wrong on your official source releases

### ISSUE THREAD

**Issue by tullis** [apache/superset#25333]
#### How to reproduce the bug

1. Download an official source release (any of them) from https://downloads.apache.org/superset/
```
curl --remote-name-all https://downloads.apache.org/superset/2.1.1/apache-superset-2.1.1-source.tar.gz
```
2. Download the sha512 checksum file for the same release
```
curl --remote-name-all https://downloads.apache.org/superset/2.1.1/apache-superset-2.1.1-source.tar.gz.sha512
```
3. Attempt to verify the checksum
```
cat apache-superset-2.1.1-source.tar.gz.sha512 | sha512sum --check --strict
```
```
sha512sum: 'standard input': no properly formatted SHA512 checksum lines found
```
### Expected results

I would expect to see the validation succeed. e.g.
```
apache-superset-2.1.1-source.tar.gz: OK
```

### Actual results
```
sha512sum: 'standard input': no properly formatted SHA512 checksum lines found
```

This seems to affect all version of superset that are hosted here: https://downloads.apache.org/superset/ - from 1.4.2 to 3.0.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any. **n/a**
- [x] I have reproduced the issue with at least the latest released version of superset. **n/a**
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

It would seem to be some kind of systemic problem with your release processes.

**Comment by sebastianliebscher** [comment]
I noticed that too. The checksums are valid, but the file content format is off, so it is hard to compare the checksums.

If you look at the content of `source.tar.gz.sha512` you will notice that it is not a format `shasum` (or `sha512sum`) recognizes. This is because `source.tar.gz.sha512` is generated via 

```bash
gpg --print-md SHA512 "${NAME}" > "${NAME}".sha512
```

so instead you would have to compare the checksums with:

```bash
gpg --print-md SHA512 apache-superset-3.0.0-source.tar.gz | diff - apache-superset-3.0.0-source.tar.gz.sha512
```

but unfortunately this shows you a diff as the full path is included:

```bash
➜  /tmp gpg --print-md SHA512 apache-superset-3.0.0-source.tar.gz | diff - apache-superset-3.0.0-source.tar.gz.sha512
1,4c1,3
< apache-superset-3.0.0-source.tar.gz: 13ACE0D3 B24D150E 3E4462F3 BA235397
<                                      72B754C2 EAAF7FB4 013792BB 0552B0E2
<                                      679A4000 5A29ADE2 74340F33 69F6E2E7
<                                      D04F56CF 1CDF85B1 82B7A5A0 38C7D874
---
> /Users/michael_molina/svn/superset_dev/3.0.0rc4/apache-superset-3.0.0rc4-source.tar.gz: 
> 13ACE0D3 B24D150E 3E4462F3 BA235397 72B754C2 EAAF7FB4 013792BB 0552B0E2
> 679A4000 5A29ADE2 74340F33 69F6E2E7 D04F56CF 1CDF85B1 82B7A5A0 38C7D874
```

I don't think there is a standard file format for `.sha512` files, but if you look at how other Apache projects publish their checksums I'd suggest replacing 

```bash
gpg --print-md SHA512 "${NAME}" > "${NAME}".sha512
```
with
```bash
shasum -a 512 "${NAME}" > "${NAME}.sha512"
```

**Comment by john-bodley** [comment]
@rusackas would you mind commenting on this? According to @michael-s-molina you have worked with checksums per the [VERIFYING APACHE SOFTWARE FOUNDATION RELEASES](https://www.apache.org/info/verification.html) document.

**Comment by tullis** [comment]
Thanks very much for your work on this issue, but it doesn't seem to me to have been fixed in the latest release:

See: https://downloads.apache.org/superset/3.0.2/apache-superset-3.0.2-source.tar.gz.sha512
this file still contains the format created by `gpg --print-md` and the full path to the rc2 candidate release file:
```
/Users/michael_molina/svn/superset_dev/3.0.2rc2/apache-superset-3.0.2rc2-source.tar.gz:
```
