### ISSUE TITLE
Unable to get tables from Athena Database using PyAthenaJDBC

### ISSUE THREAD

**Issue by machaudhary** [apache/superset#25337]
I am unable to get the list of tables while creating a new Dataset in Superset.

#### How to reproduce the bug

1. Connect to Amazon Athena using connection string: awsathena+jdbc://<aws_access_token>:<aws_secret_key>@athena.ap-south-1.amazonaws.com/closeapp?s3_staging_dir=s3%3A%2F%2Fcloseapp-athena%2Fsuperset-analysis-results&work_group=primary
2. Try to create a dataset with this newly connected Athena DB.

### Expected results
It should list the tables of the database.

### Actual results
Error: There was an error fetching tables with the superset logs displaying:

#### Screenshots
Webpage:
<img width="1747" alt="Screenshot 2023-09-19 at 1 04 23 PM" src="https://github.com/apache/superset/assets/121080377/275d1c24-66a7-4908-894f-56d1c9897b34">
Logs:
<img width="1785" alt="image" src="https://github.com/apache/superset/assets/121080377/28e82451-6cd1-468a-8cbf-e5738550a36b">

### Environment

1. Using AWS EC2 machine with Ubuntu 20.04.

2. Installed apache-superset using:

```
sudo apt update
sudo apt upgrade
sudo apt-get install build-essential libssl-dev libffi-dev python3-dev python3-pip libsasl2-dev libldap2-dev default-libmysqlclient-dev
pip install virtualenv
export PATH=/home/ubuntu/venv/bin:$PATH
sudo apt-get install pkg-config
sudo apt install python3.8-venv
python3 -m venv venv
. venv/bin/activate
//install superset
sudo pip install numpy pandas
pip install apache-superset
pip install marshmallow-enum
pip install sqlparse==0.4.3
export FLASK_APP=superset
// created a new secret key using "openssl rand -base64 42" and updated in "venv/lib64/python3.8/site-packages/superset/config.py"
superset db upgrade
superset load_examples

superset init
flask fab create-admin
superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger  
```
3. Versions:
- Superset: 2.1.1 (latest)
- PyAthenaJDBC: 3.0.1 (latest)
- SQLAlchemy: 1.4.49

### Checklist
1. Tried downgrading versions of superset, pyathena, etc. Nothing works for me.
2. Tried installing through docker. Also, not working.

### Additional context
1. I am able to see the tables in csv format in my s3_staging_dir in S3.
3. Also, I am able to see the schemas of tables viewed through: http://127.0.0.1:8088/api/v1/database/2/table/collection_name_comment/closeapp/
4. I found a similar issue already reported (https://github.com/apache/superset/issues/23850#issuecomment-1556779220) but the resolution to use PyAthena>=2.0.0 is already what I am using.

**Comment by vanga** [comment]
@machaudhary were you able to figure out what the problem was?
I am getting the same error when getting table schema, without any useful info in the logs.  I can see that the schema requests on Athena side are succesful. 
```
There was an error loading the tables:
Unexpected error occurred, please check your logs for details
```
