### ISSUE TITLE
Not able to see JS related info in dashboard edit

### ISSUE THREAD

**Issue by mvadodariya** [apache/superset#25338]
I want to add arrow button on the cell of table chart based on some condition. But where can i add my JS for that? Can someone please check it?

**Comment by rusackas** [comment]
This isn't a bug, but rather a Q&A Discussion or a feature request. I'd encourage you to open a Github Discussion of the appropriate flavor. I'll close this, but I'm still wondering your use case. Is this something that can be achieved as a calculated column in your dataset?
