### ISSUE TITLE
Datetime column not provided error when implementing an Annotation Layer

### ISSUE THREAD

**Issue by TomBurdge** [apache/superset#25347]
When embedding a table as an interval annotation layer in a line chart, there is an error.

This is in 3.0.0 - we updated to this (somewhat unexpectedly, by restarting and using the latest image) yesterday.
This release appears to have introduced the bug.

#### How to reproduce the bug

1. Create a dataset, with a BigQuery db connection, as:
SELECT 
  "Latest periods" AS latest_periods, 
  LAST_DAY(CURRENT_DATE(), MONTH) AS end_of_current_month, 
  LAST_DAY(DATE_ADD(CURRENT_DATE(),INTERVAL -1 MONTH), MONTH) AS end_of_previous_month;

2. Try to embed this chart in a line chart.

### Expected results

As with previous superset versions, I would expect an annotation layer to embed (either as an interval or event - both cause an error).

### Actual results

Receives an error as in the  image.

"ERROR: Error: Datetime column not provided as part table configuration and is required by this type of chart"

#### Screenshots

Image attached. 
This does not seem to be limited to my specific table.
![image](https://github.com/apache/superset/assets/114760229/a35716f6-4b09-402e-8a2f-087e22617294)

### Environment

- browser type and version: Google Chrome - latest
- superset version: 3.0.0 
- python version: 3.9.18
- node.js version: not using plugins
- any feature flags active:
{
    "ALERT_REPORTS": False,
    "ENABLE_TEMPLATE_PROCESSING": True,
    'DASHBOARD_CROSS_FILTERS': True,
    'DASHBOARD_RBAC': True,
    'ESCAPE_MARKDOWN_HTML': True,
    'LISTVIEWS_DEFAULT_CARD_VIEW': True,
    'SCHEDULED_QUERIES': True,
    'THUMBNAILS': False,
    'DASHBOARD_NATIVE_FILTERS': True,
    'ENABLE_JAVASCRIPT_CONTROLS': True,
    'FEATURE_GENERIC_CHART_AXES': True,
    'EMBEDDED_SUPERSET': True,
    'HORIZONTAL_FILTER_BAR': True,
    'DRILL_BY': True,
    'DRILL_TO_DETAIL': True
}
and
DEFAULT_FEATURE_FLAGS = {
    # Experimental feature introducing a client (browser) cache
    "CLIENT_CACHE": True
} (just noticed this is deprecated in the latest release notes.)

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rtexelm** [comment]
I came across a similar problem recently but it seemed to be caused by my choice of dataset. Curious if you have had any new experience with this one?

**Comment by rusackas** [comment]
Closing this because:
1) It's gone stale
2) The last clarifying question wasn't responded to
3) We support Superset 3.1 / 4.x at the moment. 

Happy to re-open this if we can gain any updated context :)
