### ISSUE TITLE
Influxdb Connection issue with Superset

### ISSUE THREAD

**Issue by Subarna-kanti** [apache/superset#25355]
There is no support provided for Influxdb connection with Superset. Please add it.
![image](https://github.com/apache/superset/assets/61343231/cf447c7a-3210-46fb-9365-8e2bc9507c96)

**Comment by mfreeman451** [comment]
What about this? I haven't been able to get it to work though, which is why I am here.. https://docs.influxdata.com/influxdb/cloud-serverless/process-data/visualize/superset/

**Comment by rusackas** [comment]
Hopefully, the answer above is sufficient to close this thread. I'll do so anyway since it's been so long since there was a comment here. If this needs revisiting/reopening, just say the word.

**Comment by rajeshpachaikani** [comment]
The article is about connecting Apache Superset to the Influxdb Serverless instance. Anyone know how to connect to a influxdb instance running on a docker container? I am not sure which driver and dialect to use for constructing the SQLAlchemy URL of the influxdb running on a local docker container

> Hopefully, the answer above is sufficient to close this thread. I'll do so anyway since it's been so long since there was a comment here. If this needs revisiting/reopening, just say the word.
