### ISSUE TITLE
Chart with Groupby==null fails to render after upgrading to 3.0.0

### ISSUE THREAD

**Issue by zhaorui2022** [apache/superset#25354]
Hi, I have found a chart we have in production stops working after upgraded to 3.0.0. This is a Time-Series chart with `groupby==null` in the chart properties. The error seems related with [this line](https://github.com/apache/superset/blob/515452c7e2fb5da58bda788f4cf19e854e814852/superset-frontend/plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts#L181)

#### How to reproduce the bug

1. Create a chart or use any existing chart whose chart props has groupby set to null
2. Open the chart in 3.0.0
3. See error

### Expected results

Chart renders as in 2.0.0

### Actual results

Chart fails to render

#### Screenshots

![Screenshot 2023-09-20 at 4 01 57 PM](https://github.com/apache/superset/assets/105950525/be2d1915-3202-4522-96d3-2a79ccb582f7)

chart props in 2.0.0
![Screenshot 2023-09-20 at 4 01 27 PM](https://github.com/apache/superset/assets/105950525/6ec2f3be-56d2-46f1-8bc4-08301491b537)

chart props in 3.0.0

![Screenshot 2023-09-20 at 4 01 44 PM](https://github.com/apache/superset/assets/105950525/11451ed7-a6ef-479d-8395-ec3ee05dbbaa)

### Environment

(please complete the following information):

- browser type and version: Chrome latest version
- superset version: `superset version` 3.0.0
- python version: `python --version` 3.9
- node.js version: `node -v` 20.6.0
- any feature flags active: We have Cross Filter disabled.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zhaorui2022** [comment]
I made a [quick fix ](https://github.com/dropbox/incubator-superset-internal/commit/2e2b8d2e198b30b9e4633820f68cb2e18205e7ec)in our staging env which seems helping the chart to render, but not sure if there is any side effect by setting some default values. Would love to hear more thoughts.

**Comment by michael-s-molina** [comment]
Thanks for the issue @zhaorui2022. This is the problem of not having versioned schemas for the JSON fields 😞 I'm working on a more generic solution to ensure that all required fields, defined by Typescript, exist during runtime. I want to avoid the situation where the type definition does not accurately describe the data and the developers need to check for null values when the type definition clearly states that it shouldn't be the case.

**Comment by rusackas** [comment]
@zhaorui2022 would you still be interested in fixing/contributing to resolve this? I'm not sure if we _need_ to make the broader fix @michael-s-molina is talking about, or if your fix (and perhaps a test for it) would suffice. Seems like it would move the ball forward and let us close this issue as fixed. It's at risk of being closed as stale otherwise.

**Comment by rusackas** [comment]
Closing as stale (and since we don't support 3.0.0 any more)... but happy to reopen this if anyone is interested in contributing a fix.
