### ISSUE TITLE
Superset 3.0 not able to login , getting CSRF error

### ISSUE THREAD

**Issue by shafad1** [apache/superset#25359]
not able to login superset after successfull installation , getting the below error
#### How to reproduce the bug

![image](https://github.com/apache/superset/assets/107529872/a878a512-23f4-4885-bc45-d7075d9f05b5)

**Comment by Stefan781** [comment]
Might be related to https://github.com/apache/superset/issues/25348

**Comment by shafad1** [comment]
> Might be related to #25348

Superset is not a stable tool , we can’t deploy in production confidently . For all the release may have some bugs .. 3.0 is not stable version

**Comment by sfirke** [comment]
I'm sorry you're having a difficult experience with the tool.  It's a tricky dance to get the default configurations working out of the box while also as secure as possible.  For instance you could try disabling Talisman CSP, which lowers your security but could help resolve the issue.  I would recommend disabling/reducing security to get it working, then building it back up, as an easier way to debug.

> Superset is not a stable tool , we can’t deploy in production confidently . For all the release may have some bugs .. 3.0 is not stable version

Here are two ways to fix this:
- Pay for https://preset.io/ hosted SaaS Superset -- then they'll handle these complexities
- Contribute to pre-release testing.  Version 3.0.0 went through four rounds of tests and fixes.  We can always use more rigorous testing.  Please consider joining the project mailing list, then testing 3.0.1 before its release!  https://lists.apache.org/list.html?dev@superset.apache.org

**Comment by Stefan781** [comment]
Disabling Talisman CSP fixed it for me. However, this is not a solution. It would be nice if there is a working guide in the documentation about how to authenticate and use the API.

**Comment by sfirke** [comment]
This is a duplicate of https://github.com/apache/superset/issues/24579 so I'm closing.  See the thread there for more details, including a PR that recently merged that changes a setting which might avoid this behavior happening on initial setup without https.
