### ISSUE TITLE
Couldn't change the column name when editing the dataset

### ISSUE THREAD

**Issue by Micky7788** [apache/superset#25363]
I am using 2.1.0 (development server) and have deployed Superset on EC2. I tried to change the column names to be different from the ones in the database when I created the chart using the physical dataset, but it looks like there is no drop down option for 'column' in 'Edit Dataset' -> 'COLUMNS' that I can type in the name in 'Label'. I even used Admin account, but still has the same issue. How can I fix it?

It should be like this:
![image](https://github.com/apache/superset/assets/134655858/f7474ecd-32e3-4e0f-b3fe-532c36f31dd8)

In my UI:
![Screen Shot 2023-09-21 at 1 21 32 PM](https://github.com/apache/superset/assets/134655858/c088dc53-86ad-41df-b758-087127cc8bc5)

**Comment by rusackas** [comment]
You can use Label as you've surmised, but if you want to change what comes out of the database, you should do it at the query or virtual dataset (also a query) and `SELECT foo as bar`. Hope that helps!
