### ISSUE TITLE
alembic_version error while using mssql for database

### ISSUE THREAD

**Issue by vijayreddybomma** [apache/superset#25364]
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'alembic_version'. (208) (SQLExecDi
[rectW)")]
[SQL: UPDATE alembic_version SET version_num='b4456560d4f3' WHERE alembic_version.version_num = 'bb51420eaf83']

To update the database schema for the superset database using the <superset db upgrade> command iam getting the above error ,but when i try the same using MySql it worked fine,

I see [here](https://github.com/apache/superset/issues/18961) an update regarding that saying it wont work with MSSQL but the issue is closed , any update regarding this?

**Comment by sfirke** [comment]
Is this is a new setup or are you trying to upgrade an existing Superset that uses MSSQL as the metadata DB?  If the latter, I'm surprised it ever worked in the past.  The [Superset docs now officially state that MSSQL is not supported as a metadata backend](https://superset.apache.org/docs/frequently-asked-questions/#what-database-engine-can-i-use-as-a-backend-for-superset).

**Comment by sfirke** [comment]
I'm going to close this as MSSQL is officially not supported as a metadata store.  This comment is the closest I can point to when it comes to the technical details of why: https://github.com/apache/superset/issues/18961#issuecomment-1735629377
