### ISSUE TITLE
Set up development environment error on macos

### ISSUE THREAD

**Issue by derecknowayback** [apache/superset#25376]
Hi, guys. I am setting up development environment as the README.md . But I hit the problem below:
```bash
# Create an admin user in your metadata database
superset fab create-admin \
                    --username admin \
                    --firstname "Admin I."\
                    --lastname Strator \
                    --email admin@superset.io \
                    --password 123123123
--------------------------------------------------------------------------------
                                    WARNING
--------------------------------------------------------------------------------
A Default SECRET_KEY was detected, please use superset_config.py to override it.
Use a strong complex alphanumeric string and use a tool to help you generate 
a sufficiently random sequence, ex: openssl rand -base64 42
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Refusing to start due to insecure SECRET_KEY
make: *** [superset] Error 1
```
It seems that I have to add a secret key to `superset_config.py`, but there is no such file under the repository root. The only file is under the `docker` folder. So do I need to create a file? And where should I place it?

## Environment
Python: 3.8
Os: macos

**Comment by chetat** [comment]
Hi @derecknowayback , I think you should check the file in `docker/pythonpath/` . See here https://github.com/apache/superset/blob/master/docker/pythonpath_dev/superset_config.py

**Comment by derecknowayback** [comment]
> Hi @derecknowayback , I think you should check the file in `docker/pythonpath_dev/` . See here https://github.com/apache/superset/blob/master/docker/pythonpath_dev/superset_config.py

Thanks, bro. I tried but that didn't work, which is quite confusing.

**Comment by dpgaspar** [comment]
@derecknowayback 

`docker/pythonpath_dev/superset_config.py` will be used with `docker-compose` if your running flask on your terminal and you have clonned the repo just create `superset_config.py` on the root. If you have installed superset using pip install create 
 `superset_config.py` and set `PYTHONPATH` to it's directory.

**Comment by derecknowayback** [comment]
> @derecknowayback
> 
> `docker/pythonpath_dev/superset_config.py` will be used with `docker-compose` if your running flask on your terminal and you have clonned the repo just create `superset_config.py` on the root. If you have installed superset using pip install create `superset_config.py` and set `PYTHONPATH` to it's directory.

Much appreciate! Thanks for your time ;-)
