### ISSUE TITLE
[SIP-105] Expose echarts `aria` options

### ISSUE THREAD

**Issue by septatrix** [apache/superset#25379]
### Motivation

To make dashboards accessible for a wide audience it is important to allow configuration of accessibility options. eCharts provides some means to do so under the `aria` options. Especially decals/hatching is very useful and is exposed under [`aria.decal`](https://echarts.apache.org/en/option.html#aria.decal.decals)

### Proposed Change

Expose options to enable decals and if possible even more accessibility options. At least enabling rudimentary decal support could be done as a checkbox (or dropdown) next to the other visualization options (color palette etc.)

### New or Changed Public Interfaces

- I am not sure if REST endpoints will be affects.
- Models might be affected depending on how options like color palette etc. are currently stored. I remember having read somewhere that they are just stored as JSON so it is possible that no changes will be required here.
- The editor React component will have to be updated to expose this option as a checkbox, dropdown or similar (depending on how much control we want to expose - simple checkbox would already be a great improvement).
- Superset CLI and deployment will not be affected.

### New dependencies

None

### Migration Plan and Compatibility

No migration required

### Rejected Alternatives

None that I am aware of. I looked for existing issues covering accessibility, ARIA and decals/hatching and found nothing.

**Comment by rusackas** [comment]
Hi @septatrix, and thanks for the proposal! I think everyone in the community would be appreciative of this step toward improved accessibility. In fact, I'm not sure a SIP is even warranted. In my opinion, as long as the checkbox (e.g. "Show accessibility decals") is coded in a DRY way, and placed consistently in the control panels, you could just open a PR and we'll usher it through. 

I'll seek second opinions on whether the SIP and voting processes are needed for this, in case others don't agree.

**Comment by rusackas** [comment]
We discussed this a bit in a synchronous meeting, but we agree on a few things:
• This needs to be done on a per-user basis. It doesn't make sense to do it on a per-chart basis (difficult to maintain) and doesn't make sense as a deployment configuration setting (not everyone will want it)
• We need such a user preferences feature, but this may or may not be a SIP unto its own.
• We're curious if you're willing to contribute to this, or if this is a request/proposal on its own... a PR might help in the discussion to understand the approach.

Please open. a discuss thread on the dev mailing list (dev@superset.apache.org) to move this forward. We're interested!

**Comment by septatrix** [comment]
> - We're curious if you're willing to contribute to this, or if this is a request/proposal on its own... a PR might help in the discussion to understand the approach.

I do not have the capacity to work on this in the foreseeable future.
