### ISSUE TITLE
A user can't list his own database connections

### ISSUE THREAD

**Issue by manuelmazzuola** [apache/superset#25392]
A user can't list database connections created by himself.  
The user has the **Gamma** and **Gamma plus** roles.  
The Gamma plus role has the following permissions:

<ul class="select2-selection__rendered"><li class="select2-selection__choice" title="can read on Dataset" data-select2-id="350"><span class="select2-selection__choice__remove" role="presentation">×</span>can read on Dataset</li><li class="select2-selection__choice" title="can write on Dataset" data-select2-id="351"><span class="select2-selection__choice__remove" role="presentation">×</span>can write on Dataset</li><li class="select2-selection__choice" title="can read on Database" data-select2-id="352"><span class="select2-selection__choice__remove" role="presentation">×</span>can read on Database</li><li class="select2-selection__choice" title="can write on Database" data-select2-id="353"><span class="select2-selection__choice__remove" role="presentation">×</span>can write on Database</li><li class="select2-selection__choice" title="can export on Database" data-select2-id="354"><span class="select2-selection__choice__remove" role="presentation">×</span>can export on Database</li><li class="select2-selection__choice" title="can duplicate on Dataset" data-select2-id="355"><span class="select2-selection__choice__remove" role="presentation">×</span>can duplicate on Dataset</li><li class="select2-selection__choice" title="can get or create dataset on Dataset" data-select2-id="356"><span class="select2-selection__choice__remove" role="presentation">×</span>can get or create dataset on Dataset</li><li class="select2-selection__choice" title="can export on Dataset" data-select2-id="357"><span class="select2-selection__choice__remove" role="presentation">×</span>can export on Dataset</li><li class="select2-selection__choice" title="can get column values on Datasource" data-select2-id="358"><span class="select2-selection__choice__remove" role="presentation">×</span>can get column values on Datasource</li><li class="select2-selection__choice" title="can list on DynamicPlugin" data-select2-id="359"><span class="select2-selection__choice__remove" role="presentation">×</span>can list on DynamicPlugin</li><li class="select2-selection__choice" title="can this form get on CsvToDatabaseView" data-select2-id="360"><span class="select2-selection__choice__remove" role="presentation">×</span>can this form get on CsvToDatabaseView</li><li class="select2-selection__choice" title="can this form post on CsvToDatabaseView" data-select2-id="361"><span class="select2-selection__choice__remove" role="presentation">×</span>can this form post on CsvToDatabaseView</li><li class="select2-selection__choice" title="can this form get on ExcelToDatabaseView" data-select2-id="362"><span class="select2-selection__choice__remove" role="presentation">×</span>can this form get on ExcelToDatabaseView</li><li class="select2-selection__choice" title="can this form post on ExcelToDatabaseView" data-select2-id="363"><span class="select2-selection__choice__remove" role="presentation">×</span>can this form post on ExcelToDatabaseView</li><li class="select2-selection__choice" title="can this form get on ColumnarToDatabaseView" data-select2-id="364"><span class="select2-selection__choice__remove" role="presentation">×</span>can this form get on ColumnarToDatabaseView</li><li class="select2-selection__choice" title="can this form post on ColumnarToDatabaseView" data-select2-id="365"><span class="select2-selection__choice__remove" role="presentation">×</span>can this form post on ColumnarToDatabaseView</li><li class="select2-selection__choice" title="can list on AccessRequestsModelView" data-select2-id="366"><span class="select2-selection__choice__remove" role="presentation">×</span>can list on AccessRequestsModelView</li><li class="select2-selection__choice" title="menu access on Databases" data-select2-id="367"><span class="select2-selection__choice__remove" role="presentation">×</span>menu access on Databases</li></ul>

#### How to reproduce the bug

1. Go to 'Settings -> Database Connections'
2. Click on the plus icon
3. Setup a Database Connection
4. Go To 'Settings -> Database Connections'
5. The database connections table is empty

### Expected results

The database connection should be listed.

### Actual results

The database connection is not listed.

### Environment

- browser type and version: firefox 117.0.1
- superset version: `2.1.0`
- python version: `3.8.16`
- any feature flags active:

```
ENABLE_PROXY_FIX = True
AUTH_ROLES_SYNC_AT_LOGIN = True
AUTH_ROLE_ADMIN = 'Admin'
AUTH_ROLE_PUBLIC = 'Public'
AUTH_USER_REGISTRATION = True
AUTH_USER_REGISTRATION_ROLE = "Gamma"
GUEST_ROLE_NAME = "Embed" // a custom role
```
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rohitpawar2811** [comment]
@manuelmazzuola Have you got any tye of error?

**Comment by manuelmazzuola** [comment]
> @manuelmazzuola Have you got any tye of error?

no, any errors

**Comment by rusackas** [comment]
Hi there, and sorry this has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and since it's been a while since this thread saw any activity, I'll close this as stale. If it is still an issue in Superset 3.x or newer, we can re-open this, or feel free to open a new issue with updated context. Thanks!
