### ISSUE TITLE
Pivot Table v2 sorting order is not right

### ISSUE THREAD

**Issue by PowerDinosaur** [apache/superset#25393]
Hi guys!
I have a basic count and a ratio of the total value  (displayed as combined metrics). In this case the sorting isn't working in the way it should because for example If the most sales happened in January the counted number will be the first column, however the percentage will be far back because 70% just means 0,7 in this case, but they are not the same metrics, same dimension. This is a problem because we have lot of columns (like ~1000) and users sometimes filter for some of this or just would like to see the top ones. Does anyone has a solution for this?
Thank you in advance and have a nice day!

#### How to reproduce the bug

1. Make a pivot table with 2 metrics
2. Use them as combined metrics
3. Sort them by metrics

### Expected results

See the columns WITH the metrics attached to each other sorted (just like with a-z sorting)

### Actual results

The values won't be represented in pair, but for example if you have a % ratio 70% wont be paired with the first value, it will be only the first of percentage values as it counts as 0,7. 

### Environment

(please complete the following information):

Mozilla Firefox
Superset 3.0 RC4

**Comment by rusackas** [comment]
I assume this is still the case in 3.0 or the 4.0 RC? 

It would be helpful if you should show us screenshots and form values for a test case using example datasets we all have access to. That would allow us to test such things manually, or even write an E2E test to cover this.

**Comment by rusackas** [comment]
We no longer support 3.x, and it's been a long while since I asked for additional info, so I'll close this as stale. Happy to reopen/revisit if warranted.
