### ISSUE TITLE
plz help me with language translation

### ISSUE THREAD

**Issue by TKShimmm** [apache/superset#25406]
## Screenshot
![image](https://github.com/apache/superset/assets/94885511/ec65bc19-1fdd-41e1-928e-b66aa668e5f4)

## Description
as you can see from the image, I've created language file but it won't work.
This happens not only in Row level security filter page, it happeds oftenly in other components as well.

thank you and all the best

**Comment by rusackas** [comment]
Are ANY of the translated strings loading? It looks like the global navigation and Refresh buttons aren't translated either, so I worry your problem is not just the string, but the loading of strings in general.

**Comment by rusackas** [comment]
Also your PR doesn't say what version of Superset you're using. Is this an issue in 3.0 or newer?

**Comment by rusackas** [comment]
Closing since we no longer even support 3.0. This issue seems to have gone stale.
