### ISSUE TITLE
Problems with cross-filtering

### ISSUE THREAD

**Issue by GinkoValery** [apache/superset#25413]
## Screenshot
![image](https://github.com/apache/superset/assets/113714043/2b20cc48-c2ed-4ac4-b2da-dacb5340f5d3)

## Description
My Superset was installed in Docker. I activated feature_flag which allows cross-filtering in superset_config.py ("DASHBOARD_CROSS_FILTERS": True) and restarted the container. After that I was enabled to use cross-filtering but I can not see which filters were applied via cross-filtering on the side filter panel.

But according to video tutorials I might see them (https://www.youtube.com/watch?v=GrlRuOELJRw):
![image](https://github.com/apache/superset/assets/113714043/c16c7fa5-1301-43f6-9ed5-6fa4293440a9)

What should I do to be able to see the emitted cross-filters at the side panel?

**Environment:**
browser type and version: Google Chrome v.116.0.5845.188
superset version: 2.1.1.
python version: Python 3.10.12
node.js version: node not found
any feature flags active: "ALERT_REPORTS": True, "GENERIC_CHART_AXES": True, "DASHBOARD_CROSS_FILTERS": True, "ENABLE_JAVASCRIPT_CONTROLS": True, "DRILL_TO_DETAIL":True

**Comment by sfirke** [comment]
Thanks for including your version number.  I believe that filter visibility is only present in the now-released 3.0.0.  If you can upgrade, that should do it.  I think that video is dated between the release of 2.1.0 and 3.0.0, and Preset (the SaaS vendor of Superset) uses a constantly-changing unofficial version that follows the latest progress -- so they likely had that feature in their software before it was generally available.

I'm going to close this issue, given that - but if you upgrade to 3.0.0 and don't see the cross-filters there please reopen it!
