### ISSUE TITLE
Problems with "drill to details"/"drill to details by" when adding layer in Mixed_chart 

### ISSUE THREAD

**Issue by GinkoValery** [apache/superset#25410]
Hi!
When I add a layer to a **Mixed_chart** in Superset I can not drill down to details for the last element shown in a chart legend.
So in the **Mixed_chart** below with a dashed layer I can drill down to details for "a-e" columns, but when right clicking on the "f " column I can not get any contex menu for drill down (no contex menu is available for "f" column):
![image](https://github.com/apache/superset/assets/113714043/1c326857-9239-43a7-aacc-49df3fa76f5c)

I have tried different variants to understand the nature of this problem. No matter how many bars you have on the chart, drill_down option will not work only for the last bar at a **Mixed_chart** with a layer:
![image](https://github.com/apache/superset/assets/113714043/28123c42-e4d8-4f61-81a6-12dd3770f47c)

The problem appears only for a **Mixed_chart** after adding a layer. If I remove the layer, "drill to details" option works properly:
![image](https://github.com/apache/superset/assets/113714043/9f8df56c-2f96-4a5d-a19c-c473b54e3b5b)

If I choose **Bar_chart** with a layer, there is no problem with "drill to details" for all bars as well:
![image](https://github.com/apache/superset/assets/113714043/e57ea2a7-02c8-41d3-9f91-7e61a3bcb0fc)

The dataset for the issue is attached in an excel file.
[register_bugs.xlsx](https://github.com/apache/superset/files/12725574/register_bugs.xlsx)

### Environment:

- browser type and version: Google Chrome v.116.0.5845.188
- superset version: 2.1.1.
- python version: Python 3.10.12
- node.js version: node not found
- any feature flags active: "ALERT_REPORTS": True, "GENERIC_CHART_AXES": True, "DASHBOARD_CROSS_FILTERS": True, "ENABLE_JAVASCRIPT_CONTROLS": True, "DRILL_TO_DETAIL":True

**Comment by rusackas** [comment]
We're no longer supporting Superset 2.x, and this is at risk of being closed as stale (maybe it's a bit of an edge case and isn't bothering many people?). Let us know if it's still an issue in 3.x or newer and we can keep it open.

**Comment by rusackas** [comment]
Closing this as stale... I might be misunderstanding the issue, but drilling operations seem to be working OK on the current version in Mixed Charts
