### ISSUE TITLE
Superset db upgrade fails.

### ISSUE THREAD

**Issue by rabindragogoi** [apache/superset#25427]
Superset db upgrade fails when upgrading superset from 1.5.2 to 2.1.1 on metastore db : mysql

### Expected results

Superset should upgrade successfully without any errors

### Actual results

Superset upgrade fails with below error.

#### Screenshots

![image](https://github.com/apache/superset/assets/12514180/6774b300-9392-4255-8954-b5be535ad52e)

**Comment by alanorth** [comment]
Welcome to the club, @rabindragogoi. There are a number of users (me included) reporting migration errors on upgrade to 2.1.x. For example, a long discussion with no solutions (yet) here:

https://github.com/apache/superset/issues/23483
