### ISSUE TITLE
Issue with area series stacked chart selecting a value 

### ISSUE THREAD

**Issue by jainrishabh-trellix** [apache/superset#25428]
In a time series stacked chart you can select a value to chart that group by on it's own. When you click again to show the main chart the chart is no longer formatted correctly. It shows all group by values but it has spikes in the data that show the sum of the values as much larger than they actually are.

 I have reproduced the issue with at least the latest released version of superset
 I have checked the issue tracker for the same issue and I haven't found one similar
Expected results
User should click on a value to chart that dimension then click again to show the original chart again.

Actual results
User clicks on a value to chart that dimension then clicking again shows incorrect spikes in the data.

**Comment by jainrishabh-trellix** [comment]
The issue is still not resolved yet.

**Comment by jainrishabh-trellix** [comment]
Hi Evan, Right now we are using the superset 2.1.1 version and this issue we are facing when we have the stacked/stream area chart and whenever we click on any displayed chart value then the value it's displaying is doubled this is the bug already someone raised earlier sharing you the link as well of that. 
Raised Issue link: [https://github.com/apache-superset/superset-ui/issues/743](https://github.com/apache-superset/superset-ui/issues/743)

**Comment by rusackas** [comment]
Sorry for the radio silence here, but 2.1.1 is loooong obsolete. 3.x is no longer supported either. If you can reproduce this in 4.x, and give us a reproducible test case, we can revisit or reopen this as warranted.
