### ISSUE TITLE
Annotation Layer modal doesn't list all table charts when there are more than 100 tables 

### ISSUE THREAD

**Issue by yousoph** [apache/superset#25421]
When creating a chart, users are able to add Annotation Layers that can be set to be powered by an existing table chart. However, the dropdown selector to specify a chart isn't returning all table charts available in the Workspace.

#### How to reproduce the bug

1. Make sure you have over 100 charts (duplicate dashboards to get to 100 more quickly if needed) 
2. Create a new Table Chart -- make sure the name starts with Z to see the bug more easily 
3. Try to use this table chart as an annotation layer source on another chart, like a Mixed chart or a time series chart 

### Expected results

When searching for a chart when adding annotations, the new chart appears 

### Actual results

![image](https://github.com/apache/superset/assets/10627051/7646c3f6-22a0-4608-92e3-40d705b61646)
The new chart doesn't appear in the chart list 

### Environment

(please complete the following information):

- browser type and version: 
- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

It seems that the endpoint to fetch the charts is only returning 100 results - there doesn't seem to be pagination and it also doesn't seem to be filtering by viz_type = table, which might also reduce the number of charts that would be returned.

**Comment by rusackas** [comment]
Looks kike this one is close to getting closed! Thanks for the help @rtexelm!
