### ISSUE TITLE
No ARM support in latest docker image. 

### ISSUE THREAD

**Issue by MathenyCode** [apache/superset#25433]
There appears to be no arm support for the latest docker image on the hub. 
**How to Reproduce the bug**

❯ docker run -d -p 8080:8088 --name superset apache/superset

**Error:**
Unable to find image 'apache/superset:latest' locally
latest: Pulling from apache/superset
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.

Expected Results: 
Documentation strongly suggests apple silicon compatibility, so I expected an image for this platform. 

**Environment**
- Apple M2 Pro Max 
- superset version: master branch

**Comment by atillier** [comment]
Looks like we both got the same issue, see conversation on https://github.com/apache/superset/issues/25434

**Comment by rusackas** [comment]
I think we're probably good here in general now... but there are a lot of old issues to wade through. Closing this one in favor of https://github.com/apache/superset/issues/25434
