### ISSUE TITLE
LDAP auth doesn't work in Superset v.3.0.0

### ISSUE THREAD

**Issue by nvk-r0dney** [apache/superset#25431]
I configured LDAP authorization in version 2.1.0 and it works. Then I deployed version 3.0.0 on the test server. All configs have been moved over there. The authorization form cyclically asks for a password and the page reloads again to this form.

 The application is deployed by docker compose. All parameters are specified  in the `superset_config_docker.py` file.

```py
from flask_appbuilder.security.manager import AUTH_LDAP
#
# LDAP
#
AUTH_TYPE = AUTH_LDAP
AUTH_ROLE_ADMIN = "Admin"
AUTH_ROLE_PUBLIC = "Public"

AUTH_USER_REGISTRATION = True
AUTH_USER_REGISTRATION_ROLE = "Public"

AUTH_ROLES_SYNC_AT_LOGIN = True

PERMANENT_SESSION_LIFETIME = 32400

AUTH_LDAP_SERVER = "ldap://my-dc.home.local"
AUTH_LDAP_SEARCH = "dc=home,dc=local"

AUTH_LDAP_UID_FIELD = "sAMAccountName"

AUTH_LDAP_BIND_USER = "cn=superset-01,ou=Apache_Superset,ou=ServiceAccounts,dc=home,dc=local"
AUTH_LDAP_BIND_PASSWORD = "my_super_secret_password"

AUTH_LDAP_USE_TLS = False
AUTH_LDAP_ALLOW_SELF_SIGNED = False

AUTH_LDAP_UID_FIELD = "sAMAccountName"
AUTH_LDAP_GROUP_FIELD = "memberOf"

AUTH_LDAP_SEARCH_FILTER = "(memberOf=cn=g_srv-superset_all_users,ou=Apache_Superset,ou=ServiceGroups,dc=home,dc=local)"

AUTH_LDAP_FIRSTNAME_FIELD = "givenName"
AUTH_LDAP_LASTNAME_FIELD = "sn"
AUTH_LDAP_EMAIL_FIELD = "mail"

AUTH_ROLES_MAPPING = {.......}
```

Python dependencies are declared in the `requirements-local.txt` file

```txt
pyodbc
clickhouse-connect
python-ldap
gunicorn
trino
ldap3
```

All libraries are installed in the file `docker-bootstrap.sh`

```bash
apt-get install -y libgssapi-krb5-2
apt-get install -y libsasl2-dev libldap2-dev libssl-dev libffi-dev build-essential python3-dev python3-pip 
```

**Comment by sfirke** [comment]
I suspect it's not a problem with LDAP and instead it's with a default value of Talisman CSP or CSRF that changed in config.py and you haven't overwritten.  See https://github.com/apache/superset/issues/24579 which has people describing this same behavior, there are some suggestions for settings to change there.

**Comment by nvk-r0dney** [comment]
@sfirke Thanks a lot for your advice!
I have owerwritten parameters in my `superset_config_docker.py`:

```py
WTF_CSRF_ENABLED = False
TALISMAN_ENABLED = False
SESSION_COOKIE_SAMESITE = None
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = False
```
It works for me.

**Comment by sfirke** [comment]
Good to know it worked! Thanks for sharing the working combination.

For a production instance, disabling those security measures may make your instance more insecure. I would suggest looking into those settings and seeing if you can adjust them so that you have a content security policy, etc but your Superset still runs.

**Comment by quadrakpp** [comment]
Hello,

I'm using docker compose on Windows 11 (docker compose -f docker-compose-image-tag.yml up) to install superset.
I would like to know the location path of **superset_config_docker.py** to override. Because currently I'm putting my code directly into **/app/superset/config.py**

**Comment by sfirke** [comment]
@quadrakpp that's kind of off topic here but you would put the file in the path given here in the docs: https://superset.apache.org/docs/installation/docker-compose/#configuring-further.
