### ISSUE TITLE
Dataset error code 215 with clickhouse

### ISSUE THREAD

**Issue by xcgoo** [apache/superset#25444]
after build a dataset and chart and save it to a dashboard, return to the dashboard will show "Unexpected error, See more", click it, the  detail shows as below:

Unexpected error
Error: Orig exception: Code: 215.
DB::Exception: Column `DATE` is not under aggregate function and not in GROUP BY. Have columns: ['sum(diff)','toStartOfDay(toDateTime(toStartOfDay(toDateTime(DATE))))']: While processing toStartOfDay(toDateTime(DATE)) AS DATE, sum(diff) AS `SUM(diff)`. Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe0c86b5 in /usr/bin/clickhouse
1. ? @ 0x8941cfe in /usr/bin/clickhouse
2. DB::ActionsMatcher::visit(DB::ASTIdentifier const&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x12cf7b66 in /usr/bin/clickhouse
3. DB::ActionsMatcher::visit(DB::ASTFunction const&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x12cfb349 in /usr/bin/clickhouse
4. DB::ActionsMatcher::visit(DB::ASTFunction const&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x12cfb349 in /usr/bin/clickhouse
5. DB::ActionsMatcher::visit(DB::ASTExpressionList&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x12d012a8 in /usr/bin/clickhouse
6. ? @ 0x12ceee35 in /usr/bin/clickhouse
7. DB::ExpressionAnalyzer::getRootActions(std::__1::shared_ptr<DB::IAST> const&, bool, std::__1::shared_ptr<DB::ActionsDAG>&, bool) @ 0x12ccd8fb in /usr/bin/clickhouse
8. DB::SelectQueryExpressionAnalyzer::appendSelect(DB::ExpressionActionsChain&, bool) @ 0x12cdd286 in /usr/bin/clickhouse
9. DB::ExpressionAnalysisResult::ExpressionAnalysisResult(DB::SelectQueryExpressionAnalyzer&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, bool, bool, std::__1::shared_ptr<DB::FilterDAGInfo> const&, std::__1::shared_ptr<DB::FilterDAGInfo> const&, DB::Block const&) @ 0x12ce36be in /usr/bin/clickhouse
10. DB::InterpreterSelectQuery::getSampleBlockImpl() @ 0x135d6f71 in /usr/bin/clickhouse
11. ? @ 0x135cfcba in /usr/bin/clickhouse
12. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::PreparedSets>) @ 0x135c9fb9 in /usr/bin/clickhouse
13. DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) @ 0x1365bd02 in /usr/bin/clickhouse
14. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) @ 0x13659caa in /usr/bin/clickhouse
15. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x13582f50 in /usr/bin/clickhouse
16. ? @ 0x1397f260 in /usr/bin/clickhouse
17. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x1397c9ad in /usr/bin/clickhouse
18. DB::TCPHandler::runImpl() @ 0x14703d39 in /usr/bin/clickhouse
19. DB::TCPHandler::run() @ 0x14719259 in /usr/bin/clickhouse
20. Poco::Net::TCPServerConnection::start() @ 0x1761d1b4 in /usr/bin/clickhouse
21. Poco::Net::TCPServerDispatcher::run() @ 0x1761e3db in /usr/bin/clickhouse
22. Poco::PooledThread::run() @ 0x177a5767 in /usr/bin/clickhouse
23. Poco::ThreadImpl::runnableEntry(void*) @ 0x177a319d in /usr/bin/clickhouse
24. ? @ 0x7fb103875609 in ?
25. __clone @ 0x7fb10379a163 in ?

#### How to reproduce the bug

1. Query data, it's ok;
2. Create chart, the chart preview is ok;
3. Save the dataset and chart, and then save it to a dashboard
4. return to the dashboard, See error

### Expected results

the dashboar will show the chart correctly.

### Actual results

"Unexpected error, see more", click it, will show the detail as above

#### Screenshots

![image](https://github.com/apache/superset/assets/19371643/4d946cf0-f477-4ea5-b51d-ff248ab6c393)

### Environment

- browser type and version: Edge version  11y
- superset version: `3.0.0`
- python version: `python 3.9`
- node.js version: `unknown`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ N ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ Y ] I have reproduced the issue with at least the latest released version of superset.
- [ Y ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing as stale, but happy to reopen if others run into this.

**Comment by rusackas** [comment]
@dosu-bot might have suggestions, too. Worth a shot :)
