### ISSUE TITLE
Download Dashboard as PDF #feature

### ISSUE THREAD

**Issue by Yaswanth-Perumalla** [apache/superset#25446]
### Motivation

Superset Supports downloading Dashboard as an Image. It does not have an option to download the Dashboard as a PDF. 

### Proposed Change

We can use [this](https://www.npmjs.com/package/dom-to-pdf) npm package to add PDF download support.

### New or Changed Public Interfaces

- NA

### New dependencies

- [dom-to-pdf](https://www.npmjs.com/package/dom-to-pdf)

### Migration Plan and Compatibility

- NA

### Rejected Alternatives

- NA

### Supporting Images / Screenshots
- After the change the UI will look like this.
<img width="506" alt="image" src="https://github.com/apache/superset/assets/109591061/a7fdf6d7-7992-497a-91e7-b0095cefdee1">

**Comment by rusackas** [comment]
You can download dashboards as PDF now :) Closing this out accordingly.
