### ISSUE TITLE
EMAIL_NOTIFICATIONS configuration setting is not respected

### ISSUE THREAD

**Issue by lodu** [apache/superset#25459]
In config.py a EMAIL_NOTIFICATIONS with comment "all the emails are sent using dryrun" can be set. This has no effect, since it is called nowhere in the codebase. I expect there to be a dryrun option for e.g. some outward facing dev environments.

#### How to reproduce the bug

1. In `config.py` set `EMAIL_NOTIFICATIONS = False`
2. Create a new email report
3. Trigger email report

### Expected results
1. No Mail is received

### Actual results

1. Mail is received

#### Screenshots
![image](https://github.com/apache/superset/assets/48859312/6b5513c2-1409-4739-8c6f-d10f8b10d0cb)

As seen in screenshot: it just says `dryrun = False` and not requesting said config option.
File: `superset/reports/notifications/email.py`

### Environment
- firefox (v117.0.1 64-bit) 
- superset 3.0.0 Docker image (prod version not rc)
  - also on the current master branch (I git cloned and ran locally)
- any feature flags active: ALERT_REPORTS

### Checklist
- [ x] I have reproduced the issue with at least the latest released version of superset.

### Additional context

[Slack conversation about it](https://apache-superset.slack.com/archives/C015WAZL0KH/p1695972330191929)

**Comment by sfirke** [comment]
Thanks for reporting this and submitting a fix!  I can't dig in this second but wanted to point out an attempt I'd started to address the fact that `EMAIL_NOTIFICATIONS` had been replaced by `ALERT_REPORTS_NOTIFICATION_DRY_RUN`.  I gave up on it and would happily delete my branch if your PR accomplishes this.  Just linking mine for reference in case it's useful to you: https://github.com/apache/superset/pull/24047

**Comment by rusackas** [comment]
Looks like the PR for this was closed due to the head repo being deleted. Is this still an issue that needs tackling?

**Comment by lodu** [comment]
> Looks like the PR for this was closed due to the head repo being deleted. Is this still an issue that needs tackling?

Oh yeah I made a new PR which used the same name, hence why it was deleted I think.

The issue still persists.
However I have not seen anyone else talking about this so I don't think its that big of an issue.
Its dead code and it should probably be replaced by a working system (e.g. something along the lines of what Sam proposed) to avoid tech debt.

**Comment by rusackas** [comment]
Oh, you're right, EMAIL_NOTIFICATIONS isn't really _used_ anywhere. Seems like @sfirke has also taken a closer look at this than I have... not sure what we need to do here. I'll leave this open until one one of your PRs merges (or one like it), but otherwise, would it be fair to just delete `EMAIL_NOTIFICATIONS` if it's vestigial code? Seems like it'd be a non-breaking change to do so, and might be an easier way to close this issue :P

**Comment by rusackas** [comment]
Opening a PR....
