### ISSUE TITLE
Is it possible to customise the table shown via drill to details

### ISSUE THREAD

**Issue by GinkoValery** [apache/superset#25463]
Hi everyone!
Is it possible to customise the table shown via **"drill to details"** option after right clicking at a chart element? I mean I would like to see not all the columns of a dataset used for the chart, but only specific columns.

**Comment by sfirke** [comment]
No, this is not possible.  It would be a nice addition though!  Feel free to open a GitHub Discussion with a feature request describing this.  Someone would be welcome to contribute the feature to the codebase if they are able and willing.

**Comment by sfirke** [comment]
Update: this is being worked on as SIP-160! https://github.com/apache/superset/issues/32793
