### ISSUE TITLE
Issue: While emailing chart in csv, now blank csv also sent

### ISSUE THREAD

**Issue by rohitpawar2811** [apache/superset#25474]
Currently, I have upgraded to superset 3.0.0 version and **I have found that now blank csv is also sent in email** . Previously In 2.0.0 version blank csv were not sended.

I think this thing should be configurable like someone want to go empty reports and some not.

Like this : 
```
            if (not app.config["EMAIL_REPORTS_BLANK"]) and content.header_data["notification_format"] == "CSV" and content.data is None:
                logger.info(
                    "Report Blank is blocked %s", content.header_data
                )
            else :
```

**Any suggestions about that?**

**Comment by rohitpawar2811** [comment]
I have checked the code base, the issue because of now blank csv sent its because of this  b'\n
Now if blank csv comes still it contains a newline character  that's why below check would not work and blank csv sent. 
```
if not csv_data :
                    print("=================Unexpected missing csv file")
                    error_text = "Unexpected missing csv file"
            if error_text:
                return NotificationContent(
                    name=self._report_schedule.name,
                    text=error_text,
                    header_data=header_data,
                )
```

**Solution:** 
1. Either we have to apply this check 

if not csv_data or csv_data == b'\n        

2. Or we can just compare that if csv_data == b'\n    then csv_data = None

**Comment by rohitpawar2811** [comment]
@michael-s-molina

**Comment by rusackas** [comment]
@rohitpawar2811 would you be interested in opening a PR? Since we haven't had any other complaints about this in the last 5 months, it's at risk of being closed as stale.

**Comment by rohitpawar2811** [comment]
@rusackas I think others did not have problem with empty csv sent when there is no data. But this was valid issue for me. yes I am interested in opening a PR.

**Comment by rusackas** [comment]
Closing this issue as stale. If you'd like to pick this up @rohitpawar2811 and open a PR, we can re-open the issue (if it is indeed still an issue in supported versions (4.0/4.1)).
