### ISSUE TITLE
Pivot Table lacking feature parity after migrating from V1 to V2 in 3.0.0 

### ISSUE THREAD

**Issue by zhaorui2022** [apache/superset#25492]
We have received user reports that in Pivot table V2, users can no longer collapse big tables, which was possible in previous version when using Pivot table V1. Consider V1 are migrated to V2 during 3.0.0 upgrade, and it is a regression from users' perspective, I am filing this as a bug report instead of feature request.

#### How to reproduce the bug

1. Create a dataset with many rows of data
2. Create a Pivot Table V2 which displays the data from the dataset created above
3. See error (no option to collapse table)

### Expected results

Users can still collapse tables like what Pivot Table V1 does

### Actual results

Users not able to collapse big tables in Pivot Table V2

### Environment

(please complete the following information):

- browser type and version: Chrome latest version
- superset version: `superset version` 3.0.0
- python version: `python --version` 3.9
- node.js version: `node -v` v 20.6.0
- any feature flags active: I didn't find any feature flag that directly relates to this feature

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by michael-s-molina** [comment]
@kgabryje Could you take a look?

**Comment by rusackas** [comment]
It's been 5 months since this was opened, but remains silent. It would seem most people aren't concerned with it, but we'd still be open to PRs if anyone wants to contribute one. This issue is at risk of being closed as stale otherwise.

**Comment by rusackas** [comment]
CC @yousoph

**Comment by rusackas** [comment]
Closing as stale.
