### ISSUE TITLE
Low performance for large SQL statements

### ISSUE THREAD

**Issue by ganczarek** [apache/superset#25514]
Superset parses the same SQL statement multiple times during a single request. For large SQL queries that may take a few seconds to parse each time it quickly adds up to long execution times.

For example, a 172kB SQL query that I tested (selects hundreds of columns in a wide table) takes about 7 seconds to parse (`sqlparse.parse`) or format  (`sqlparse.format`). Total query execution in Superset was close to 2 minutes for that query, while actual query execution in the database was around 7 seconds. Majority of the time Superset spent parsing and reformatting that query (stripping comments).
 
One source of improvement could be refactoring `ParsedQuery` so it doesn't perform unnecessary SQL parsing and formatting operations. For example, [strip_comments](https://github.com/apache/superset/blob/ff95d0face88f4d62e1041aa13b0fab53b81b6ef/superset/sql_parse.py#L348) method is called multiple time in various `is_*` methods. Each time it takes SQL statement string, strips comments and returns a string which is later parsed again. It happens even if it was already done previously or [during initialisation](https://github.com/apache/superset/blob/ff95d0face88f4d62e1041aa13b0fab53b81b6ef/superset/sql_parse.py#L193). 

For SQL statements which parsing takes more than a few seconds it quickly adds up, because of calls like [is_readonly_query](https://github.com/apache/superset/blob/ff95d0face88f4d62e1041aa13b0fab53b81b6ef/superset/db_engine_specs/base.py#L1756) or [is_select_query](https://github.com/apache/superset/blob/ff95d0face88f4d62e1041aa13b0fab53b81b6ef/superset/db_engine_specs/base.py#L1765).

Another source of improvement would be to use already parsed queries rather than their string representation that later needs to be parsed again. (e.g. in [execute_sql_statement](https://github.com/apache/superset/blob/ff95d0face88f4d62e1041aa13b0fab53b81b6ef/superset/sql_lab.py#L219))

#### How to reproduce the bug

The issue requires a large SQL query that selects hundreds of columns from a very wide table. 

### Expected results

I would expect Superset to parse a query only a few times per request and avoid unecessary parsing and formatting. 

### Actual results

Superset parses and formats SQL statement multiple times per request.

### Environment

- browser type and version: unrelated
- superset version: `2.1.0`
- python version: `3.8.13`
- node.js version: unrelated
- any feature flags active: nothing that could impact this

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing this out, since sqlparse is out of the picture with the (in-progress) [SIP-117](https://github.com/apache/superset/issues/26786). While that's effectively work in progress, I think it's sufficient to close out this issue as a committed solution to the reported problem. CC @betodealmeida in case they would prefer to keep it open until work is completed.
