### ISSUE TITLE
[SIP-106] Adding alternative text or image to charts when they do not return any result

### ISSUE THREAD

**Issue by RaptorRob** [apache/superset#25512]
*Please make sure you are familiar with the SIP process documented*
(here)[https://github.com/apache/superset/issues/5602]. The SIP will be numbered by a committer upon acceptance.

### Motivation

When a chart is showing no results (for instance as part of filtering) it shows:
![image](https://github.com/apache/superset/assets/33096624/0737b586-2c4e-4b3c-a264-a3bc0a196fa5)

I think it doesn't make a dashboard look good if some components look like this in case they don't return any results.

### Proposed Change

It would be great to show a pre-defined text or an image instead.

**Comment by rusackas** [comment]
I think we need a little clarity on the proposal. 

Do you want to replace this image/text globally (like perhaps something in config.py)?

Or are you hoping to have an extra field in the chart control panel that lets you select customized text and/or image for each chart instantiation when they don't turn up data? 

Or is it just a proposal to _replace_ the existing image/text with a different design?

**Comment by rusackas** [comment]
Closing this as discarded... please let us know if you want to move forward with your proposal.
