### ISSUE TITLE
If the virtual (SQL) dataset contains a comment, not possible to synchronize the columns

### ISSUE THREAD

**Issue by bu3tt1** [apache/superset#25527]
If the virtual (SQL) dataset contains the comment `--SELECT` in the clause select is not possible to synchronize the columns.

#### How to reproduce the bug

1. Go to 'Edit Dataset'
2. Modify the query SQL on the virtual (SQL)

> SELECT
> issues.id
> --SELECT
> FROM issues

3. Save
4. Return on 'Edit Dataset' > 'Columns'
5. Click 'Sync columns from source
6. See error:

`(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SELECT\nFROM issues\nLIMIT 1' at line 3")`

### Expected results

Columns must synchronize without error

what actually happens.

<img width="627" alt="Screenshot 2023-10-05 alle 11 10 54" src="https://github.com/apache/superset/assets/6870639/f26dcb5c-31d4-4fdb-afe7-1c95474ec855">

<img width="623" alt="Screenshot 2023-10-05 alle 11 11 03" src="https://github.com/apache/superset/assets/6870639/d804a164-b94b-47c5-93b0-3a821db44654">

### Environment

- superset version: `2.1.1`
- official Docker image:  `apache/superset:2.1.1`

**Comment by rusackas** [comment]
This doesn't seem to be an issue in current Superset on `master` - or at least I wasn't able to reproduce it with the example (BIrth Names) dataset.
