### ISSUE TITLE
Filter does not take effect in chat and dashboard

### ISSUE THREAD

**Issue by zhenlanzhuang** [apache/superset#25544]
see in image,I put a filter in condition box and apply update，condition not be shown in sql box and chat not work right；
![企业微信截图_16965595786923](https://github.com/apache/superset/assets/17018590/0035df51-2a61-4182-bc2b-48a6b030e7f4)
same as dashboard
![image](https://github.com/apache/superset/assets/17018590/ed00266b-bc65-4ad4-8249-f2165845114c)

**Comment by rusackas** [comment]
Seems to be working fine in current versions. Let us know if you encounter this in 3.x.

<img width="660" alt="image" src="https://github.com/apache/superset/assets/812905/c621a2b2-414c-495a-bee3-2a513ad053ad">
