### ISSUE TITLE
Superset 3.0.0 generates invalid SQL for Dremio after releasing #23872

### ISSUE THREAD

**Issue by OskarNS** [apache/superset#25554]
#### How to reproduce the bug

1. Create a new chart that has the options of Series Limit. Eg. Time-Series Chart, Area Chart etc.
2. Set required fields and Series Limit
3. Click Create Chart.

### Expected results

The chart is shown successfully on the right.

### Actual results

Unexpected error returned. Superset generates invalid SQL for Dremio, which then throws an error. See screenshots

#### Screenshots

![image](https://github.com/apache/superset/assets/16308697/d35bc3e8-3563-46f1-a167-8777f789d07d)

Comparison of SQL generated for Dremio for a Time series chart in 3.0.0 and 2.1.1, respectively:
![image](https://github.com/apache/superset/assets/16308697/dcd721ef-0e32-4a70-a9e0-f304a747792e)

### Environment

- superset version: 3.0.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

This pull request has introduced the regression: https://github.com/apache/superset/pull/23872
This is also apparent in the above screenshots. The invalid SQL is due to aliases missing.

How should we proceed from there? Should https://github.com/apache/superset/pull/23872 be reverted?

**Comment by michael-s-molina** [comment]
@betodealmeida Could you take a look?
