### ISSUE TITLE
Duplicate report recipients created for reports

### ISSUE THREAD

**Issue by zhaorui2022** [apache/superset#25558]
We have observed an issue since 2.0 (not sure if the same issue exists before 2.0) where sometimes there are duplicated recipients being created for the same alert/report. They are exactly the same type, same target, and created at the same time.

#### How to reproduce the bug

I have tried to reproduce this error but have no luck with it. However, we have received several users reporting this issue already and they claim they didn't manually create duplicate recipients.

I have two suspected causes:
1. I haven't verified how the db calls are made. But if it is async, maybe the call to save recipient timed out and then another call is made, which led to duplicate entries.
2. Maybe there is something going on with the front end which duplicate this entry in the payload.

### Expected results

No duplicate recipient is created in the alerts/reports.

### Actual results

Sometimes there are duplicate recipients.

#### Screenshots

I have a screenshot from the backend db. I have to remove the actual value of the slack channel but they are identical (no whitespace and etc)

![Screenshot 2023-10-06 at 1 27 13 PM](https://github.com/apache/superset/assets/105950525/207241af-80a8-4457-8f5e-15172564af83)

### Environment

(please complete the following information):

- browser type and version: Chrome latest
- superset version: `superset version` 3.0.0 (observed a few times in 2.0.0 as well)
- python version: `python --version` 3.9
- node.js version: `node -v` v20.8.0
- any feature flags active: ALTER_REPORTS are ON

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

For the backend DB, we are using MySQL.

I thought about maybe making a call and check existing recipients before saving to make sure there is no duplicates. But it's more like a bandaid and might not solve the issue from its root cause.

**Comment by rusackas** [comment]
There doesn't seem to be any update happening here. Since we don't support 2.x or 3.x any more, I'll close this. Holler if it needs a revisit in the context of 4.x or newer!
