### ISSUE TITLE
LOGO_TARGET_PATH Not working as intended from 2.1.0 forward

### ISSUE THREAD

**Issue by rscarborough1996** [apache/superset#25555]
The comment above LOGO_TARGET_PATH in config,py says:
"# e.g. setting it to '/' would take the user to '/superset/welcome/'"

That was true in 2.0.1, but from my testing, it takes the user to a blank page starting in 2.1.0. It is still the case in 3.0.0.

#### How to reproduce the bug

1. Change LOGO_TARGET_PATH from None to '/'
2. Click on the logo

### Expected results
Directed to the welcome screen

### Actual results
Directed to a blank page

**Comment by rusackas** [comment]
Opened a PR to help clarify this. Please review if you feel so inclinded.

**Comment by rscarborough1996** [comment]
Thanks for this!
I left a review with my approval.

**Comment by rusackas** [comment]
With the PR merged and this discussion having gone stale, it seems all is well, so I'll close this out :)
