### ISSUE TITLE
Unable to run superset backend on Ubuntu 20.04 with python3.8.10

### ISSUE THREAD

**Issue by koushik-rout-samsung** [apache/superset#25552]
Pip install failing for python3.8.10
 
#### How to reproduce the bug

1. Clone the master repository.
2. Create a virtual environment.
3. run pip install -r requirements/testing.txt

### Expected results
As per documentation python 3.8 is supported so it should install pip libraries.

### Actual results
ERROR: Package 'apache-superset' requires a different Python: 3.8.10 not in '~=3.9'

### Environment

Ubuntu : 20.04
python : 3.8.10

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Documentation update is required if applicable.
Please find the link below.
https://github.com/apache/superset/blob/master/CONTRIBUTING.md#os-dependencies

**Comment by sfirke** [comment]
Hi and thanks for this issue!  I'm not 100% sure but I believe Superset requires Python 3.9.  For instance in the Dockerfile and Makefile one sees references to 3.9 as a requirement.

Can you point to where in the docs you saw that 3.8 was the minimum supported version?

**Comment by koushik-rout-samsung** [comment]
> Hi and thanks for this issue! I'm not 100% sure but I believe Superset requires Python 3.9. For instance in the Dockerfile and Makefile one sees references to 3.9 as a requirement.
> 
> Can you point to where in the docs you saw that 3.8 was the minimum supported version?

Thanks for the reply. I have updated the link in description.

**Comment by koushik-rout-samsung** [comment]
https://github.com/apache/superset/pull/25885

**Comment by rusackas** [comment]
Assuming this is fixed, since we're on Python 3.9 now (and upgrading from that, too!). Holler if this needs revisiting.
