### ISSUE TITLE
Dashboard access regression in 3.0

### ISSUE THREAD

**Issue by zhaorui2022** [apache/superset#25560]
In 2.0.0, if a user have access to all the charts in a dashboard, even if the dashboard is in draft mode, users can access the dashboard if they have an URL with dashboard ID. However, after upgrading to 3.0.0, this no longer works, and users had to use UUIDs which caused quite a lot of inconvenience. 

After some investigations, we believe it's because in 3.0.0, DashboardDAO is used when rendering the dashboards, and eventually it calls this function to check access. https://github.com/apache/superset/blob/master/superset/dashboards/filters.py#L118 And as we can see in the code, it requires the dashboard to be published for non-owners to see the dashboard. We fixed it by changing `and_` to `or_`. 

I am filing this as a bug report since from users' perspective, it is a regression. But it also makes sense to be a feature request based on what the community expects the behavior to be.

#### How to reproduce the bug

1. log in as an non-admin user, create a dashboard
2. take a note on the URL that contains the dashboard ID in it
3. remove owners
4. try to visit the URL noted in step 2 and see error

### Expected results

Users can still access dashboards as in 2.0.0

### Actual results

Users see an unexpected error (shown in screenshots)

#### Screenshots

![Screenshot 2023-10-06 at 2 00 10 PM](https://github.com/apache/superset/assets/105950525/b05454b5-b3d6-4cee-8da7-9303cd2beda1)

### Environment

(please complete the following information):

- browser type and version: Chrome latest 
- superset version: `superset version` 2.0.0
- python version: `python --version` 3.9
- node.js version: `node -v` v20.8.0
- any feature flags active: We have dashboard role based access disabled, but it shouldn't affect this behavior.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by michael-s-molina** [comment]
@zhaorui2022 I believe this was a security fix. @john-bodley @jfrag1 could you check this?

**Comment by michael-s-molina** [comment]
Closing this issue as this was a breaking change for security reasons.
