### ISSUE TITLE
Redundant connection to databases

### ISSUE THREAD

**Issue by javillor** [apache/superset#25575]
I am connecting Superset to a Clickhouse cluster. All data is replicated among the nodes of the cluster.
When configuring the connection I need to specify a single host name, so I choose any of the nodes of the cluster and connect to it successfully.
However, in case of having any problem with this node, Superset will stop working.

Is there any way to specify any redundant connection to databases?
Ideally, when configuring the connection to databases, it would be great if we can set different hostnames, so in case of failure the connection will try with the next hostname and so on.

**Comment by genzgd** [comment]
Unfortunately this is not currently supported in either of underlying client libraries `clickhouse-connect` or `clickhouse-driver`.  Of course, if you have the resources one solution is to put your cluster behind a load balancer or proxy like `clickhouse-proxy`.  There is an open [issue](https://github.com/ClickHouse/clickhouse-connect/issues/74) for this in `clickhouse-connect` but it's not currently a high priority.
