### ISSUE TITLE
Cross Filtering is not applied to annotation layer ( Table ) 

### ISSUE THREAD

**Issue by ThierryH** [apache/superset#25581]
Create a scatter/bar/line chart A with a Temporal X axis ,
add an annotation layer based on a table chart  B( type event , source table , chart my chart based on the same dataset ) 
When cross filter is triggered , the data from Chart A are correctly filtered , but not the annotation. 
The question is : Is this a wanted behavior ?

Thanks in advance

**Comment by rusackas** [comment]
That sounds correct to me.... the annotation would be considered a "static" snapshot of data as an annotation over a filterable / dynamic chart. If you think I'm misinterpreting, we can re-open this for further feature design discussions.
