### ISSUE TITLE
Is Superset have any limitation on total roles, total users and total databases   

### ISSUE THREAD

**Issue by nagarajmmu** [apache/superset#25583]
Hi All

I am working on superset as our visualization tool, we are keeping dashboards category and product wise, we have a more than a 500 categories and 5 products and data will be in duckdb as a separate file for each category and product combination, 
 
So database connection will be more than a 2000
Dashboard will be more than 2000
charts will be more than 2000 to 4000
user will have a roles based access, for each category and a product, so roles will be more than a 2000

these number are rough estimate, these can increase over a period.

My question:
Is, superset have any restriction on a **database** numbers?
Is, superset have any restriction on a **dashboard** numbers?
Is, superset have any restriction on a **dataset** numbers? 
Is, superset have any restriction on a **user** numbers? 
Is, superset have any restriction on a **role** numbers? 

If any limits are exist, please let us know

we are using superset 2.1.0

Thanks
Nagaraj M M

**Comment by sfirke** [comment]
No, I don't think Superset has any limits like this.  It's used heavily at large companies like AirBNB which I believe have many more dashboards and charts than this.

That said, if you do run into issues with performance, please do report them back to the project and this issue.  I'm not sure how common it is to have 2000+ database connections...

**Comment by nagarajmmu** [comment]
Hi Sfirke

Thanks for the confirmation.
As I said, our data is separated by Category and Product, so each Category and Product combination data will be in each **duckdb** file, 
As you know, need to create one database connection for one **duckdb** file, so as much as duckdb file we have, that much database connection we need to access data in superset.

Thanks
Nagaraj M M
