### ISSUE TITLE
Alert & Reports running into lock issues often after upgraded to 3.0.0

### ISSUE THREAD

**Issue by zhaorui2022** [apache/superset#25580]
After we migrate to 3.0.0, we have seen it happening quite often when modifying alerts that it fails on the front end. In the logs, it says `(MySQLdb._exceptions.OperationalError) (1205, 'Lock wait timeout exceeded; try restarting transaction')`. When the request was still executing, I checked the mysql db but it returns nothing when running `Show open tables where in_use>0;
`. We didn't observe such behavior before upgrading to 3.0.0.

#### How to reproduce the bug

I don't find a definitive way to reproduce the issue. It just happens sometimes.
1. Go to Alerts & Reports page
2. Click on any existing alert
3. Try to modify any field, like owner or query.
4. Click save and see error

### Expected results

Alerts & Reports saved successfully

### Actual results

Cannot save edited alters & reports even after retrying

#### Screenshots

![Screenshot 2023-10-09 at 10 13 45 AM](https://github.com/apache/superset/assets/105950525/c6b949d8-0eaa-42c1-90b0-705629289d27)

![Screenshot 2023-10-09 at 10 13 54 AM](https://github.com/apache/superset/assets/105950525/87fb697c-de10-4b24-9317-10ba1ab05537)

![Screenshot 2023-10-09 at 10 14 12 AM](https://github.com/apache/superset/assets/105950525/100e32d0-73d2-436a-9c9b-49326fc9ac1e)

### Environment

(please complete the following information):

- browser type and version: Chrome latest
- superset version: `superset version` 3.0.0
- python version: `python --version` 3.9
- node.js version: `node -v` v20.8.0
- any feature flags active: ALTERS_REPORTS is set to True

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
@zhaorui2022 are you still facing this? It seems like it's a MYSQL issue. Did `SHOW PROCESSLIST` work (noting that you need sufficient privileges)? You might need to adjust the DB's lock timeout. I also wonder if you've been scaling your alerts/reports, so it makes a lot (potentially thousands — who knows) of queries simultaneously. Beyond that, I'm not quite sure how to diagnose/replicate this.

**Comment by rusackas** [comment]
Not sure if anyone's facing this and we don't support Superset prior to 4.x any more, so I'll close this out. Holler if it needs more attention.
