### ISSUE TITLE
Special characters in a csv export

### ISSUE THREAD

**Issue by dorisbakker** [apache/superset#25589]
When data is exported to a csv document and data contains special characters (e.g. ë/é etc.) this is not correctly shown. 
 So when you go to a dashboard that contains a table chart and you click on export to csv, open the csv report.

This is demo data, for example:
![bug superet](https://github.com/apache/superset/assets/146943906/fece1d8d-0e0e-4286-a177-a3570d6842ff) 

It would help us a lot when this will be fixed.

**Comment by rusackas** [comment]
This seems to be working fine in current Superset. I was able to export the Unicode Test dashboard contents from both the Dashboard and Chart Builder contexts.

**Comment by mvsenin** [comment]
@rusackas Hi Evan, 'm not sure if my case is the same one, but export to CSV with windows-1251 encoding (activated via config.py) fails with the error 500, for instance, when there is a Greek Capital Letter Sigma in a field. Also some others special characters lead to the fail with windows-1251.

Could you please clarify which module is responsible for that? We have a chance to fix that in our environment.

Thank you.

**Comment by rusackas** [comment]
@mvsenin a little `git blame` leads to this PR: https://github.com/apache/superset/pull/3441/files

Hope that helps put you on the trail to a fix. a PR and/or docs to help others would be appreciated!
