### ISSUE TITLE
Switching between tabs in sql lab will clear out any table previews

### ISSUE THREAD

**Issue by sadpandajoe** [apache/superset#25597]
#### How to reproduce the bug

1. Go to sql lab (tab a)
2. Select a database and schema
3. Select a table
4. Wait for the preview to open up
5. Select a couple more tables for more previews
6. Open a new sql lab tab (tab b)
7. Switch back to tab a

### Expected results
The state should be the same as when you let it

### Actual results
The preview is cleared out and you'll have to select your tables again. 

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

This is the new behavior once SPA was implemented but am not sure if this is the behavior we want going forward so could be a won't fix if that's what we want the behavior to be.

**Comment by yousoph** [comment]
I think this might be related - sometimes when switching away from and back to a tab that is in the process of loading a table preview, the table gets duplicated (I think I usually see it there 3 times total) 


https://github.com/apache/superset/assets/10627051/2ef13f5c-0589-4617-a5e5-41d420d79b22

cc @justinpark
