### ISSUE TITLE
Memory usage of worker keeps on increasing

### ISSUE THREAD

**Issue by shauryagoel** [apache/superset#25604]
Memory usage of the worker keeps on increasing even when nothing is scheduled and no one is using superset.

#### How to reproduce the bug

1. Deploy superset using helm chart v0.10.7 on GKE.
2. Wait overnight when no one is using superset and nothing is scheduled.
3. See memory usage in GKE console.

### Expected results

Memory usage should be the same when the Superset was left alone (before night) and after night.

### Actual results

Memory keeps on increasing when the Superset is left unused.

#### Screenshots

![image](https://github.com/apache/superset/assets/6321314/6a84fe86-e26e-4114-8291-96bcd42cc8ed)

![image](https://github.com/apache/superset/assets/6321314/e68756aa-4b3c-4c37-9a39-2e7589bbfe1c)

It can be seen that worker memory increased by around 15MB overnight.

### Environment

- browser type and version: Google Chrome 112.0.5615.165
- superset version: 2.1.0
- python version: 3.8.16
- node.js version:
- any feature flags active: 
- celery version: 5.2.2

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included them here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sfirke** [comment]
Hello, thanks for reporting this.  I do not think this is going to be a high priority to fix, given everything else that needs work ... but if you or any other Kubernetes users want to dig into this, see what's going on, and propose a fix, I will help find a reviewer!  In the meantime you might bring this to the #k8-helm-deployment channel on the Superset Slack and see what people think.

**Comment by rusackas** [comment]
Hi there, and sorry this has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and since it's been a while since this thread saw any activity, I'll close this as stale. If it is still an issue in Superset 3.x or nweer, we can re-open this, or feel free to open a new issue with updated context. Thanks!
