### ISSUE TITLE
Feature request: add labels to init job pod in helm chart

### ISSUE THREAD

**Issue by GoncaloArs** [apache/superset#25613]
### Motivation

The helm chart allows custom labels to be added for every kind available in this chart, except for the init job.

### Proposed Change

Add a podLabels field ([like so](https://github.com/apache/superset/blob/cef68f8a9af41d36c22557fedba42263d94a5ed4/helm/superset/values.yaml#L297)) to `values.yaml` under the `init:` field and inject these labels [here](https://github.com/apache/superset/blob/cef68f8a9af41d36c22557fedba42263d94a5ed4/helm/superset/templates/init-job.yaml#L35) like it's done for annotations.

### New or Changed Public Interfaces

This would change the values.yaml of the helm chart.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. I'm not sure if you were planning to tackle this, or if it was more of a feature request, but we're happy to revisit and reopen this thread if warranted.
