### ISSUE TITLE
An error when share dashboard with copy permalink to clipboard

### ISSUE THREAD

**Issue by cw1427** [apache/superset#25620]
superset verions:2.1.1
When click dashboard share->copy permalink to clipboard
![image](https://github.com/apache/superset/assets/4980410/24b00ced-3bd6-41a9-9436-940c23f61553)
`'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/api/__init__.py", line 110, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/utils/log.py", line 266, in wrapper
    value = f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/views/base_api.py", line 85, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/dashboards/permalink/api.py", line 100, in post
    key = CreateDashboardPermalinkCommand(
  File "/usr/local/lib/python3.8/site-packages/superset/dashboards/permalink/commands/create.py", line 60, in run
    key=get_deterministic_uuid(self.salt, (user_id, value)),
  File "/usr/local/lib/python3.8/site-packages/superset/dashboards/permalink/commands/base.py", line 35, in salt
    return get_permalink_salt(SharedKey.DASHBOARD_PERMALINK_SALT)
  File "/usr/local/lib/python3.8/site-packages/superset/key_value/shared_entries.py", line 51, in get_permalink_salt
    salt = get_shared_value(key)
  File "/usr/local/lib/python3.8/site-packages/superset/key_value/shared_entries.py", line 34, in get_shared_value
    return GetKeyValueCommand(RESOURCE, key=uuid_key, codec=CODEC).run()
  File "/usr/local/lib/python3.8/site-packages/superset/key_value/commands/get.py", line 60, in run
    return self.get()
  File "/usr/local/lib/python3.8/site-packages/superset/key_value/commands/get.py", line 76, in get
    return self.codec.decode(entry.value)
  File "/usr/local/lib/python3.8/site-packages/superset/key_value/types.py", line 78, in decode
    return json.loads(value)
  File "/usr/local/lib/python3.8/json/__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
"superset.log" 991L, 72181C                                                                 `

**Comment by cw1427** [comment]
Figured out the cause: My supersetdb use mariadb which setup charset as utf8mb4 as default. When v2.1.1 use JsonKeyValueCodec decode as utf-8.

**Comment by sfirke** [comment]
Nice sleuthing!  This could be very valuable to someone else so thanks for sharing that back.

Are you using MariaDB as your backend for Superset metadata?  It's [not on the official list of supported DBs](https://superset.apache.org/docs/frequently-asked-questions/#what-database-engine-can-i-use-as-a-backend-for-superset), though MySQL is and obviously they're very similar.  I wonder if we should add a note that MariaDB is _not_ supported as a backend, which is what the Apache Airflow project points out in its docs.

**Comment by longtomjr** [comment]
Hi, just want to note here that I ran into the same issue using PostgreSQL after upgrading to 3.0.1 . I am investigating more on my side and will share additional information if I have any.

**Comment by longtomjr** [comment]
Ok, update on my issue. For some reason when I upgraded, the migration to convert KV entries to json failed: https://github.com/villebro/superset/blob/master/superset/migrations/versions/2023-05-01_12-03_9c2a5681ddfd_convert_key_value_entries_to_json.py

NB: Do a database backup before attempting the following.

I fixed this by running the following in the `superset shell` (NOTE: you might have to run this twice, once for `app` resources and once for `dashboard_permalink` resources:
```python
import io
import json
import pickle

from alembic import op
from sqlalchemy import Column, Integer, LargeBinary, String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session

from superset import db
from superset.migrations.shared.utils import paginated_update

Base = declarative_base()
VALUE_MAX_SIZE = 2**24 - 1
#RESOURCES_TO_MIGRATE = ("app",)
RESOURCES_TO_MIGRATE = ("dashboard_permalink",)


class RestrictedUnpickler(pickle.Unpickler):
    def find_class(self, module, name):
        raise pickle.UnpicklingError(f"Unpickling of {module}.{name} is forbidden")


class KeyValueEntry(Base):
    __tablename__ = "key_value"
    id = Column(Integer, primary_key=True)
    resource = Column(String(32), nullable=False)
    value = Column(LargeBinary(length=VALUE_MAX_SIZE), nullable=False)

for entry in paginated_update(
    db.session.query(KeyValueEntry).filter(
        KeyValueEntry.resource.in_(RESOURCES_TO_MIGRATE)
    )
):
    ent_value = entry.value;
    # NOTE: 123 == b'{'[0]
    # Remove this check when running this for `app` resources
    # or check for `34` (") to filter out already converted app resources
    if len(ent_value) > 0 and ent_value[0] != 123:
        value = RestrictedUnpickler(io.BytesIO(entry.value)).load() or {}
        entry.value = bytes(json.dumps(value), encoding="utf-8")

```
The above is just a hacky modification of the upgrade script. When you see errors, you will have to debug it.

I am unsure why this migration failed. My hunch is that there were entries in the table created on version 2.1.0, before updating to 2.1.1, causing the migration to fail. (https://github.com/apache/superset/blob/master/UPDATING.md#211)

**Comment by emetselaar** [comment]
Thanks @longtomjr

I ran the `#RESOURCES_TO_MIGRATE = ("app",)` version (and removed the check as you said in the comment at the end) and now it works fine.
Running the `RESOURCES_TO_MIGRATE = ("dashboard_permalink",)` did not help me BTW.

**Comment by k7daniel** [comment]
Hey @longtomjr I am having this same issue here after upgrading from 2.1 to 4.0
How and where do you run the python script above? I tried to run it from the superset_app container with python3 script.py from the /app directory and I got a message from SQL Alchemy complaining about not having an app.
```
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in call
return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7fabb09341c0 (otid=0x7fabb13ac5d0) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/app/mig.py", line 31, in <module>
db.session.query(KeyValueEntry).filter(
File "<string>", line 2, in query
File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 24, in _proxied
return self.registry()
File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in call
return self.registry.setdefault(key, self.createfunc())
File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4209, in call
return self.class_(**local_kw)
File "/usr/local/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 174, in init
[self.app](https://self.app/) = app = db.get_app()
File "/usr/local/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1042, in get_app
raise RuntimeError(
RuntimeError: No application found. Either work inside a view function or push an application context. See [http://flask-sqlalchemy.pocoo.org/contexts/.](http://flask-sqlalchemy.pocoo.org/contexts/)
```

**Comment by avecheria** [comment]
Have the same issue. Can @longtomjr please explain in more details how i should start that fix script via superset shell. Thank you.

**Comment by longtomjr** [comment]
@k7daniel @avecheria. I have not upgraded to version 4.0 yet on my side, so I cannot confirm if the above hack works. It is also possible that the upgrade script have changed, so it is probably worth starting from scratch on this.

I don't have capacity at the moment to look at this on my side. It was a hack to resolve the issue on my side, and it might not work for anyone else.

**Comment by k7daniel** [comment]
The way that we were able to fix the error was by deleting specific rows from the 'key_value' table that were breaking. Most likely culprits were rows that had a type 'app' where as all other rows hand types related to permalink.

**Comment by avecheria** [comment]
> @k7daniel @avecheria. I have not upgraded to version 4.0 yet on my side, so I cannot confirm if the above hack works. It is also possible that the upgrade script have changed, so it is probably worth starting from scratch on this.
> 
> I don't have capacity at the moment to look at this on my side. It was a hack to resolve the issue on my side, and it might not work for anyone else.

Tested your method on 4.0 - it works

**Comment by SaTae66** [comment]
Same issue here, have not tried the script yet. As that is "(...) a hack to resolve the issue on my side, and it might not work for anyone else.", I would argue that this issue should be re-opened and get an official fix.

**Comment by gabor-lbl** [comment]
Same issue here. After upgrading to 4.0.2 permalinks can't be created or existing ones opened. Backend is postgresSql. I would love to see an official fix to the problem.

**Comment by rpuglielli** [comment]
It worked for me after updating from 2.1.3 to 4.0.2.
I ran the script shared by @longtomjr twice, and it worked ;)
Thanks!!
