### ISSUE TITLE
Not able to run the superset latest version

### ISSUE THREAD

**Issue by adarsh12102023** [apache/superset#25624]
#### How to reproduce the bug

1. Clone apache-superset branch 3.0
2. after setting up everything try to run the npm run dev from superset-frontend folder
3. facing below errors and not running superset in browser

WARNING in ./node_modules/@data-ui/shared/esm/enhancer/WithTooltip.js 5:39-57
export 'withTooltipPropTypes' (imported as 'vxTooltipPropTypes') was not found in '@vx/tooltip/build/tooltips/TooltipWithBounds' (possible exports: __esModule, default)

WARNING in ./node_modules/moment/min/moment-with-locales.js 2086:16-50
Module not found: Error: Can't resolve './locale' in '/home/sprngyadmin/superset/superset-frontend/node_modules/moment/min'

### Expected results

It should run superset in browser

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by adarsh12102023** [comment]
I am able to resolve above issue but even after successful npm run dev changes are not reflecting on browser

**Comment by jasonweileilei** [comment]
![image](https://github.com/apache/superset/assets/34087073/bc9a5cf6-ab50-4ce7-b795-ecf41e616110)

**Comment by jasonweileilei** [comment]
![image](https://github.com/apache/superset/assets/34087073/d861c2ec-f3b1-40f2-9fbe-b931971aefd1)

**Comment by linwenqiangll** [comment]
> ![图像](https://user-images.githubusercontent.com/34087073/280588615-d861c2ec-f3b1-40f2-9fbe-b931971aefd1.png)
我运行前端也是这样的bug，请问您这个问题解决了吗？能给我说一下怎么解决的吗？

**Comment by rusackas** [comment]
The errors here don't seem to be an issue in current Superset. A couple of the warnings still do, but they don't seem to be impacting anything. PRs welcome for those, of course! Closing this as stale, but also seemingly resolved.

**Comment by aakashcentime** [comment]
> I am able to resolve above issue but even after successful npm run dev changes are not reflecting on browser

how did you resolve the error. i am facing the same issue
