### ISSUE TITLE
Unable to use Multi Stage Engine for Apache Pinot on Superset

### ISSUE THREAD

**Issue by piby180** [apache/superset#25627]
I would like to enable multi stage engine for Apache Pinot on Superset. As per PinotDB [docs](https://github.com/python-pinot-dbapi/pinot-dbapi#using-sqlalchemy), it is possible to enable multi stage engine by providing connect args in create_engine method of SQLAlchemy

```
from sqlalchemy.engine import create_engine

 engine = create_engine(
     "pinot://localhost:8000/query/sql?controller=http://localhost:9000/",     
      connect_args={"useMultistageEngine": "true"}
 )
```

I have tried adding connect_args to Engine Parameters in Superset UI but multistage engine is still not enabled.

![image](https://github.com/apache/superset/assets/8469664/9f27b4da-efb6-4bcc-97e2-fd1b8f7514aa)

### Expected results

Multi stage queries which run fine by using pinotdb in python directly should run in Superset as well

### Actual results

Multi stage queries does not run in Superset

#### Screenshots

Here is one example!

DISTINCT * syntax runs fine in Python with multistage enabled. It also runs fine in Pinot Query Console. It does not work in Superset. 

![image](https://github.com/apache/superset/assets/8469664/bf7194a3-8e27-45cd-979b-5f297789c2d9)

### Environment

superset version: `3.0.0`
pinotdb>=5.1.0
psycopg2-binary==2.9.9
pinot version: release-1.0.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x ] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I have deployed Superset on EKS using Helm chart.

**Comment by rusackas** [comment]
Looks like this was fixed on the linked Issue, but this one was never closed. @piby180 do you think this is something that should be added to the [Pinot docs page](https://superset.apache.org/docs/databases/pinot/)? Please feel free to make an edit!
