### ISSUE TITLE
Wrong Oracle SQL query generation on time filter when using range 'midnight' and 'now'

### ISSUE THREAD

**Issue by fech-dev** [apache/superset#25637]
On the Chart page, when I set any time filter with 'Custom' as the Range type and set Start to 'Midnight' and End to 'Now', the SQL query generated is wrong.

```SQL
...
where created_at >= to_date('2023-10-13', 'yyyy-mm-dd')
  and created_at < to_date('2023-10-13', 'yyyy-mm-dd')  
```

This is giving me no results...

I'm using an Oracle Database.
I guess that the last filter `created_at < to_date('2023-10-13', 'yyyy-mm-dd')` should be like `created_at < to_date('2023-10-13 17:00:00', 'yyyy-mm-dd hh24:mi:ss')`

#### How to reproduce the bug

1. Open a chart
2. Use the pivot table (or a simple table) 
3. Go to the 'Time' section and set a DateTime column, granularity as 'Day' and time range to `custom` with start `Midnight` and end `Now`
4. Click on Apply and then update the chart
5. Get the 'No results were returned for this query' message

### Expected results
The results for the current day until "now".

### Actual results

 Get the 'No results were returned for this query' message

### Environment

(please complete the following information):

- browser type and version: Firefox v118.0.2
- superset version: `2.1.0`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dannymk** [comment]
yup, I get the same results, that should be TO_TIMESTAMP instead of TO_DATE!

**Comment by fech-dev** [comment]
> yup, I get the same results, that should be TO_TIMESTAMP instead of TO_DATE!

`to_date()` it's OK. The problem is that it only considers the date, excluding the time portion....

**Comment by fech-dev** [comment]
as a "workaround" I see that if I convert the DateTime column to a timestamp it generates the query correctly...

**Comment by rusackas** [comment]
I don't have Oracle, but the filters seem to be applying correctly in other DBs. I assume this is fixed (plus, we no longer support 2.x). If this is happening in 3.x/4.x, let us know and we can reopen/revisit.

<img width="593" alt="Pasted_Image_3_21_24__12_39 PM" src="https://github.com/apache/superset/assets/812905/8be5095b-e92f-41c8-9095-4af44b206821">

<img width="839" alt="image" src="https://github.com/apache/superset/assets/812905/7fa69a44-23c0-417f-8017-00d51b03604e">
