### ISSUE TITLE
M1 Chips Require Prophet==1.1.5 and Prophet require Holiday=0.25

### ISSUE THREAD

**Issue by hash-data** [apache/superset#25633]
Hi Superset Team,
To run the superset on M1 there is a requirement of prophet == 1.1.5 which you can check on the following link
https://github.com/facebook/prophet/issues/2402
### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mdeshmu** [comment]
There is a [known bug](https://github.com/facebook/prophet/issues/2354) with prophet that is blocking the upgrade

**Comment by hash-data** [comment]
@mdeshmu  I think it got fixed in prophet  prophet == 1.1.5 so need to upgrade the dependecies carefully.

**Comment by mdeshmu** [comment]
The bug I mentioned in the last comment and one you are talking about are two different issues.

**Comment by rusackas** [comment]
Looks like we're now on `["prophet>=1.1.5, <2"]` and all is well on my M3. Since this has been silent for so long, I'll close it, and assume all is well now days, but happy to revisit as needed!
