### ISSUE TITLE
standalone=true is not working. How to hide the top bar to public shared dashboard?

### ISSUE THREAD

**Issue by ardianp** [apache/superset#25649]
Trying to hide the top bar menu of the application to the public shared dashboard like in documentation:

http://host_IP:8080/superset/dashboard/slug/?standalone=true

The top bar is still shown. The CSS modification still doesn't work!

Anyone knows how to hide the top bar?

**Comment by sfirke** [comment]
Try `standalone=2` not `=true`.  For instance, https://analytics.a2gov.org/superset/dashboard/rain-gauges/?standalone=2.  See the docs here for more: https://superset.apache.org/docs/creating-charts-dashboards/creating-your-first-dashboard/#customizing-dashboard

I'm going to close this as this does not appear to be a bug in Superset, please let me know if it does not address your issue.
