### ISSUE TITLE
PivotTable with two column metrics errors with Dremio backend on 3.0.0

### ISSUE THREAD

**Issue by niyouzhu** [apache/superset#25641]
this bug was occurred in superset version 3.0.0, about pivottable chart. python version is 3.9.
if using 2 metrics and have the same aggregate function, such as COUNT(A), COUNT(B). after then,  will show you undefined with B. i think that this should be urgent issue.

![image](https://github.com/apache/superset/assets/15760569/573e85ed-521d-4271-8c8a-5469488b6346)

updated:
1. the bug only occurred when connecting to dremio database.  I see  the sql query is wrong, for example, it should be 
```
SELECT "FullName",
       DATE_TRUNC('day', "Manmonth"),
       count("Hours") AS count_1,
       count("LeaveHours") AS count_2
FROM "Leave"."ValidManhour"
GROUP BY "FullName",
         DATE_TRUNC('day', "Manmonth")
ORDER BY count("Hours") DESC
LIMIT 10000;
```
but actual is 
```
SELECT "FullName",
       DATE_TRUNC('day', "Manmonth"),
       count("Hours") AS count_1
FROM "Leave"."ValidManhour"
GROUP BY "FullName",
         DATE_TRUNC('day', "Manmonth")
ORDER BY count("Hours") DESC
LIMIT 10000;
```
the field 'count_2' is missing.

**Comment by rusackas** [comment]
Closing this one as stale, since it's gone nearly six months with no further corroboration/discussion/invesitigation. If anyone feels this needs reopening, just say the word.
