### ISSUE TITLE
How to customise x-axis labels for a time series bar chart

### ISSUE THREAD

**Issue by srinidhirao** [apache/superset#25656]
I'm laying out a time series bar chart (v1) and looking to customize the X axis labels. I'm projecting audit scores monthwise and would like to see the categorization to include both month and the year. For example: Sep 22 to indicate September 2022. I did see some options for customizing X axis labels, but none of them suit my requirements.

#### How to reproduce the bug

1. Draw a Time series bar chart with some data.
2. Select the time grain as Month

### Expected results

I would like to see an option to customize the x axis labels so that I can display both month and the year name:

![image](https://github.com/apache/superset/assets/9901457/50869764-9ccc-48a9-849e-6dffc662d6ab)

### Actual results

This is how I see the labels with default options:

<img width="846" alt="image" src="https://github.com/apache/superset/assets/9901457/2650eafe-13af-4bfa-97d8-e245b6c85d57">

#### Screenshots

I can see some options for customizing X-axis, but they don't address my issue:

<img width="327" alt="image" src="https://github.com/apache/superset/assets/9901457/bbf64687-fc19-4757-9f19-d74f0402aa40">

### Environment

(please complete the following information):

- Chrome browser (Version 117.0.5938.149) on Mac OS
- superset version: `2.0.0`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I also explored getting the same data projected on a regular bar chart. That seems to have the options for setting x axis labels, but couldn't find a way to sort the data by date. It always seemed to sort by the x axis labels. Time series bar chart seems to project the data correctly, but I don't see a way to configure x axis labels.

<img width="549" alt="image" src="https://github.com/apache/superset/assets/9901457/1a410b2f-6e61-4bc4-9ac6-04093ef56cef">

**Comment by sfirke** [comment]
Hello, you can type other options into that "X Axis Format" box beyond the list of defaults.  `%b %y%` produces for me what I think you're looking for: 
![image](https://github.com/apache/superset/assets/7569808/2d369c3b-f76f-473a-b690-db448467d76c)

This box uses d3 formatting, I searched the web for "d3 format name of month" to get this result.

Heads up that bar chart v1 is going away in newer versions of Superset.  There should be an automatic migration to what in 2.0.0 is called bar chart v2, but you might want to start working more with the newer one.  Which has nicer sorting options in 3.0.0, which is where I built the above chart!
