### ISSUE TITLE
webpack.config.js [ext] extra dots

### ISSUE THREAD

**Issue by gnought** [apache/superset#25678]
According https://webpack.js.org/configuration/output/#template-strings, webpack template string `[ext]` includes a leading dot.

Is it a bug that webpack.config.js includes extra dots in the following lines?
https://github.com/apache/superset/blob/e58a3aba545fd03f2af33b0075c4cacf09f776a3/superset-frontend/webpack.config.js#L403
https://github.com/apache/superset/blob/e58a3aba545fd03f2af33b0075c4cacf09f776a3/superset-frontend/webpack.config.js#L431

I expect the correction should be
```
filename: '[name].[contenthash:8][ext]', 
```

**Comment by rusackas** [comment]
Wow, I believe you're right! This all seems to have been handled gracefully so nobody ever saw a problem, but I do believe you're right, and I see some double-dotted files in my filesystem from it.
