### ISSUE TITLE
superset v3.0.0 can not login in

### ISSUE THREAD

**Issue by clcl2** [apache/superset#25685]
#### How to reproduce the bug

1. Go to '/superset/welcome'
2. Click on 'login'
3、input ‘admin’/admin to login
![image](https://github.com/apache/superset/assets/41424119/1b02a395-a61d-4b30-86bc-2259f1e1f9f4)

redirect to welcome but login status is error
![image](https://github.com/apache/superset/assets/41424119/c18ee6e6-50f1-4bd6-8a5a-2817373da6ad)

### Expected results

login in

### Actual results

redirect welcome html but login

### Environment

(please complete the following information):
docker compose 
- browser type and version:
- superset version: 3.0.1rc2
- python version: `3.9-slim-bookworm`
- node.js version: `[node -v](node:16-slim)`
- any feature flags active:

logs 

![image](https://github.com/apache/superset/assets/41424119/ecc639fe-7588-458d-b386-4e5bd1399ea1)

**Comment by xavier-GitHub76** [comment]
Hello,
https://superset.apache.org/docs/installation/installing-superset-using-docker-compose#4-log-in-to-superset says admin/admin
but I believe that the page is not up to date with the latest version of superset

You could see users with the following command (in terminal of your container)
`superset fab list-users `

If you have no admin user you can create one with
`superset fab create-admin`

**Comment by michael-s-molina** [comment]
@clcl2 I believe this problem is fixed in the latest Superset release 3.0.2. Let me know if the problem persists and we can reopen the issue.
