### ISSUE TITLE
fix: Error message: data type 'integer' not understood

### ISSUE THREAD

**Issue by xavier-GitHub76** [apache/superset#25690]
With supserset v3.0.0, I want to upload csv file with Column Data Types setted (on "COM" column)

On the screen, the help message is : 
A dictionary with column names and their data types if you need to change the defaults. Example: {"user_id":"integer"}

but with {"COM":"integer"}, I have the error message "data type 'integer' not understood"
![image](https://github.com/apache/superset/assets/82046143/62ee2abc-27f3-4c19-9e68-4f08908a524c)

The import succeded with  {"COM":"int"}
![image](https://github.com/apache/superset/assets/82046143/31688adf-f525-4fb2-a8ff-56aedeff3105)

I don't find documentation about the format keywords for types
I test with : 
- {"COM":"str"}  ✔ 
- {"COM":"string"} ✔  
- {"COM":"int"} ✔  
- {"COM":"integer"}  ❌

![image](https://github.com/apache/superset/assets/82046143/731df5c4-4d50-4e35-9265-588a760f2573)

**Comment by xavier-GitHub76** [comment]
Thanks for your action

**Comment by michael-s-molina** [comment]
The supported data types come from [Pandas dtypes](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dtypes.html) and not from the database. That's why you can't import using `integer` but can with `int` 😉

**Comment by xavier-GitHub76** [comment]
Hello,
Thanks for precision and link to Pandas dtypes.
The example displayed on the import screen is therefore misleading.
It should be: Example: {"user_id":"int"}
Best regards

**Comment by xavier-GitHub76** [comment]
Not seeing how to reopen this anomaly, I declared a new one
https://github.com/apache/superset/issues/27305
I hope this is good practice

**Comment by DarkCoffeeLake** [comment]
> The supported data types come from [Pandas dtypes](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dtypes.html) and not from the database. That's why you can't import using `integer` but can with `int` 😉

As you mentioned I used the data type 'datetime' as referenced in Pandas dtypes but i still got the same error (I need both date and timestamp data type).
`apache superset error message: data type 'datetime' not understood`

I still can't fathom how the data types work and it should be mentioned in the documentation the different supported data types.
@michael-s-molina
