### ISSUE TITLE
Helm chart missing for superset v3.0.1

### ISSUE THREAD

**Issue by cberge908** [apache/superset#25692]
Hi,

it seems that there was no new version of the helm chart for superset v3.0.1
The master branch still refers chart version 0.10.10 which is bound to v3.0.0 - also the 3.0.1 tag refers to a commit with the previous chart 0.10.9 included.

Would be great if this can be added :)

Cheers,
@cberge908

**Comment by sfirke** [comment]
As far as I know two things are true:

1. Lots of people use the Helm chart and it's important to maintain it
2. It is not officially supported by the Superset project and there's no developer from the community taking responsibility for it

Superset could really benefit from someone willing to helm (😉) the maintenance of the Helm chart!  Any takers?  Even better would be a few people!

**Comment by michael-s-molina** [comment]
> 1. Lots of people use the Helm chart and it's important to maintain it

The Superset Community Survey results will be a good indicative of Helm adoption.

> 2. It is not officially supported by the Superset project and there's no developer from the community taking responsibility for it

Yes. We need folks to update these files, especially for major releases where the changes may be significant. We also need to add a section to the [release guide](https://github.com/apache/superset/blob/master/RELEASING/README.md) about Helm.
