### ISSUE TITLE
Superset_init crashes due to failures in migration scripts

### ISSUE THREAD

**Issue by lightofindia1** [apache/superset#25699]
I have cloned the latest copy of Apache Superset from master branch. While running `docker-compose up`, I was not able to login to the application. Upon further investigation I found the superset_init docker container had some issues. The latest migration script was causing some issues and had blocked further steps (such as setting up of admin user and roles). 

#### How to reproduce the bug

1. Checkout latest master branch
2. Run "docker-compose up"
3. See superset_init container logs

### Expected results

Proper setup of superset and completion of superset_init process.

### Actual results

Superset_init pod is crashing with the following error:
[superset_init_crash.log](https://github.com/apache/superset/files/13038988/superset_init_crash.log)

### Environment

- browser type and version: Chrome
- superset version: Superset 0.0.0-dev
- python version: Python 3.9.18
- node.js version: v16.20.2
- any feature flags active: N/A

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by michael-s-molina** [comment]
Hi @lightofindia1. I was not able to reproduce this on master. If the problem still persists for you, please reach out to #deploying-superset Slack channel for help as this is probably something specific with your environment.
