### ISSUE TITLE
Question:Is it posssible to integrate superset with other web application?

### ISSUE THREAD

**Issue by govardhank** [apache/superset#2571]
Is it posssible to integrate superset with other web application?

**Comment by mistercrunch** [comment]
Only through iframes at the moment. We're planning on releasing JavaScript components that leverage our backend in the future.

**Comment by govardhank** [comment]
Hi ,

Thank you for giving me reply.

I am new to superset. Actually what i want is when i click a link in my application, it should redirect to superset and open dashboard page bypassing the login page in a separate window? can you please briefly explain or give me step wise instructions on how to do this.
My mail Id: govardhan.kamle@gmail.com

Thanks & Regards,
Govardhan

**Comment by mistercrunch** [comment]
You can either set the datasource of the dashboard as "public" using the provided `public` role, or set up some sort of automated authentication with something like a reverse proxy (using "remote user" authentication) that would have common authentication for both your applications. Or you can have the users authenticate in Superset within the iframe.

**Comment by mistercrunch** [comment]
Yes it is. Just delayed.

**Comment by akasranjan005** [comment]
>set up some sort of automated authentication with something like a reverse proxy (using "remote user" authentication) that would have common authentication for both your applications. Or you can have the users authenticate in Superset within the iframe.

@mistercrunch can you elaborate more on this. My application is embedding the iframes from superset, and it also create cookies and i want to use the same cookie for superset authentication as well. How can i achieve it? 

Thanks

**Comment by thangbn** [comment]
+1 really looking forward for the js component

**Comment by sashank** [comment]
any timelines for JS component release ?

**Comment by victornoel** [comment]
People, actually there is an issue for this (and there is a timeline there): #3201

**Comment by B121119** [comment]
@akasranjan005  Did you found any solution for superset authentication. I am also searching for that. if you found any solution can you explain me.
Thanks

**Comment by sashank** [comment]
@B121119  you may find this useful , https://medium.com/@sairamkrish/apache-superset-custom-authentication-and-integrate-with-other-micro-services-8217956273c1 ,  we are also searching for some simpler authentication with other services using either API Key or JWT authentication

**Comment by B121119** [comment]
@sashank  Thank you.. Is it for superset auto-login from other web app.

**Comment by sashank** [comment]
yeah that is the goal to achieve

**Comment by Zonalds** [comment]
Any update so far?

**Comment by Neel-rishabhsoft** [comment]
Any updates on this? And how to do the same for windows users..

**Comment by spaszek** [comment]
This issue is closed - I don't think there are any updates coming. Unfortunately.

**Comment by cocodrino** [comment]
@mistercrunch hello! any update about this?...thank you!

**Comment by kishikishore** [comment]
Hello Friends,
   This is kishore can anyone please tell me how to integrate or embedded React with Apache Superset.

**Comment by shanmukhaDurgesh** [comment]
Hello, 
can anyone please help me out with how to integrate apache superset with the angular application?

**Comment by isandyawan** [comment]
Hi,

any update for this issue?

**Comment by musthak24** [comment]
Any update ?

**Comment by winterrobert** [comment]
+1

**Comment by tconticello** [comment]
+1

**Comment by balthapaixao** [comment]
+1

**Comment by bhavik1795** [comment]
+1

**Comment by smaugho** [comment]
+1

**Comment by fabioselau077** [comment]
any update this?
