### ISSUE TITLE
Drill down doesn't work on embedded

### ISSUE THREAD

**Issue by ggam** [apache/superset#25715]
I have successfully configured an embedded dashboard, but the drill down feature fails due to a permissions problem.

Drill down uses a `/datasource/samples` API, which seems to be defined on https://github.com/apache/superset/blob/3.0.1/superset/views/datasource/views.py#L196

Embedded dashboards work with guest tokens, which only allow access to selected dashboards. I suppose that means the "can samples on Datasource" role is not inherited.

#### How to reproduce the bug

1. Get a JWT token for a user with `Admin` role via `http://XXXX/api/v1/security/login`
2. Generate a Guest token so you can use the embedded API with `http://XXXXX/api/v1/security/guest_token/`
3. POST to the samples endpoint on ``http://XXXXXX/datasource/samples?force=false&datasource_type=table&datasource_id=5&per_page=50&page=1` and a `X-GuestToken` header with the JWT guest token. You'll receive a 403.

I've been unable to authenticate to that endpoint with a "normal" JWT token. 

### Expected results

I think the guest token needs to inherit `can samples on Datasource` role so it can execute the endpoint. 

### Actual results

An error is shown:
![imagen](https://github.com/apache/superset/assets/2109040/abab5e8d-8fa6-4609-8e4a-5744384a78fd)

### Environment

Superset 3.0.1 via Docker. Feature flags: `{"ALERT_REPORTS": True,"TAGGING_SYSTEM": True, "HORIZONTAL_FILTER_BAR": True, "DASHBOARD_RBAC": True, "EMBEDDED_SUPERSET": True}`.

Note that I'm not using RBAC on this specific dashboard.

**Comment by Truffula** [comment]
See also #25630

**Comment by ggam** [comment]
Thanks @Truffula, closing this as duplicate. My specific problem was that **the guest role** was missing the `can samples on Datasource`. The guest token gets only that specific role, regardless of the roles the user who created the guest token had.
