### ISSUE TITLE
Residues left while merging

### ISSUE THREAD

**Issue by gnought** [apache/superset#25748]
Merging residues in tag [2.1.2](https://github.com/apache/superset/blob/2.1.2/superset/models/helpers.py#L248-L253)
https://github.com/apache/superset/blob/61837ed41f55a3abe4116c2402c97914770fed31/superset/models/helpers.py#L248-L253

**Comment by michael-s-molina** [comment]
Closing this as `allow_reparenting` is used bellow. Feel free to reopen if I misunderstood the issue.
