### ISSUE TITLE
docs: adding Chinese tutorial for Superset

### ISSUE THREAD

**Issue by yangxifi** [apache/superset#25751]
Users from China, after the installation of superset, often have a strong demand for Chinese, but the online tutorials are more scattered, not easy to find, more have to slowly spend time exploring, more time consuming. Therefore, based on the previous installation of superset experience, summed up a Chinese tutorial, users according to this tutorial, about 10 minutes to complete the Chinese setting, expected its helpful for users from China

**Comment by sfirke** [comment]
Hi @yangxifi, more documentation in Chinese would be great.  Do you know of any existing high-quality resources we could link to from the wiki or documentation?  Or are you able to create something?  I don't think this will be something that any Superset project committers will probably create on their own but I would help boost resources that get created by the community of Chinese-speaking Superset users.

**Comment by sfirke** [comment]
Oh I see you have contributed this yourself in https://github.com/apache/superset/pull/25760.  Thank you!
