### ISSUE TITLE
packaging: conda package issue with v3.0.1

### ISSUE THREAD

**Issue by xmnlab** [apache/superset#25797]
Hey everyone,

Although  it is not directly related to this repository I would like to bring attention to an issue we are having packaging v3.0.1 on conda-forge.

Currently there is an dependency issue with two dependencies flask and flask-caching. Although flask-caching on pypi doesn't have any issue, but just after the release of v1.11.1, a pinning was added in there to flask, and that pinning was also added to flask-caching on conda forge (but not on pypi), That is why apache-superset dependencies doesn't have any issue.

I just started a discussion about that on the repo for flaks-caching on conda-forge: https://github.com/conda-forge/flask-caching-feedstock/issues/23

does anyone know anything about this that could give us some light about this pinning issue?

PS: I am bringing this discussion here too, because I am not sure if there is any negative impact to the superset about this issue from flask-caching.

**Comment by dpgaspar** [comment]
Sorry for the delayed answer here.

Have you tried using Superset 3.1.X? or 3.0.4? on conda?

We don't directly support conda and this restriction is set there, so it does not seem this is actionable on our side.
