### ISSUE TITLE
How do i remove/disable swap dataset feature for a custom user? Which permission do i need to add or remove? Also removing the explore on superset permission also removes the drill to detail option. Is there a way to have drill to detail but not view query and edit chart options?

### ISSUE THREAD

**Issue by vedantgadia** [apache/superset#25790]
### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing this since it's not a bug and has been stale for quite some time anyway. Please feel free to start a Q&A thread on GitHub Discussions or on [slack](http://bit.ly/join-superset-slack) if you're still facing this.

**Comment by adnit** [comment]
Hi @vedantgadia, facing the same issue, did you manage to find a solution regarding this `Is there a way to have drill to detail but not view query and edit chart options?`

**Comment by rusackas** [comment]
I think there are simply a lot of small UI permissions that don't exist. @mistercrunch and @villebro are working toward a proposal to enable (or disable!) these things in a much more granular/composable/declarative way. SIP coming soon!
