### ISSUE TITLE
Helm Chart 0.10.14 fails to deploy on init-db job.

### ISSUE THREAD

**Issue by oliverlambson** [apache/superset#25824]
#### How to reproduce the bug

1. Deploy superset helm chart 0.10.14 (currently successfully deployed version = 0.10.9)

### Expected results

Superset deploys to Kubernetes cluster successfully.

### Actual results

apache-superset-init-db fails to pip install cryptography with this error message:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.apache-superset 3.0.1 requires cryptography<40,>=39.0.1, but you have cryptography 41.0.5 which is incompatible.
```

#### Screenshots

N/A

### Environment

(please complete the following information):

- browser type and version: N/A
- superset version: `3.0.1 (Helm Chart 0.10.14)`
- python version: `defined in Helm Chart`
- node.js version: `defined in Helm Chart`
- any feature flags active: `none`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

We are deploying with ArgoCD.

**Comment by rusackas** [comment]
Closing this as stale (helm charts have moved ahead and are reportedly working well) but if there's more to address here, let us know.
