### ISSUE TITLE
Data not in sorted order in Pivot table

### ISSUE THREAD

**Issue by architmmmec** [apache/superset#25835]
SELECT month AS month,
                month_name AS month_name,
                event_type AS event_type,
                no_of_days AS no_of_days,
                ft AS ft,
                planning_cycle_version_name AS planning_cycle_version_name,
                metric_type_renamed AS metric_type_renamed,
                AVG(drr_converted) AS AVG(drr_converted)
FROM TABLE
GROUP BY month,
         month_name,
         event_type,
         no_of_days,
         ft,
         planning_cycle_version_name,
         metric_type_renamed
ORDER BY CASE
             WHEN metric_type_renamed = 'units_drr' then 1
             WHEN metric_type_renamed = 'gmv_drr' then 2
             WHEN metric_type_renamed = 'units_total' then 3
             WHEN metric_type_renamed = 'gmv_total' then 4
         END ASC
LIMIT 10000;

Able to see this query in superset but metric_type_renamed is still not in sorted order in Superset pivot. Am I missing anything? In SQL data is being shown in sorted order

**Comment by rusackas** [comment]
Closing this as stale, since it's been silent for 5 months. If you're still encountering this in 3.1.x or the 4.0 RC, and can provide an example/screenshots that we can reproduce the issue with (preferably using data from built-in examples or generated by the query) we can revisit/reopen.
