### ISSUE TITLE
feat: Pin The Dashboard Feature

### ISSUE THREAD

**Issue by pankajsoni22** [apache/superset#25841]
### Discussed in https://github.com/apache/superset/discussions/25840

<div type='discussions-op-text'>

<sup>Originally posted by **pankajsoni22** November  2, 2023</sup>
### Pin Feature
I have 150 dashboards on superset and always face issue to search because to search I need to remember something from dashboard title.

It will be good if we can have pin feature so that pinned dashboards stay at the top.

This can be a feature flag enabled feature 
`PINNING=True`</div>

**Comment by michael-s-molina** [comment]
Hi @pankajsoni22. Feature requests are handled through GitHub discussions instead of issues. I suggest presenting your original discussion during the Town Hall or SIP Office Ours meetings to check if the community is aligned with your proposal.
