### ISSUE TITLE
In 3.0.1, cleaning single value native filter doesn't renable the "Apply filter" button -- regression

### ISSUE THREAD

**Issue by ablanchard** [apache/superset#25846]
When using single value native filter in a dashboard, removing a value from the filter seems to have no effect. The `Apply filters` button stays disable. The value is still filtering the charts. The only way to remove the clean the filter is to click on `Clear all`

#### How to reproduce the bug

Create a single value native filter:
1. Load the example dashboard
2. Go to `World Bank's DataWorld Bank's Data` dashboard
3. Click on the native filters side panel
4. Add a new filter, type: `Value`, Name: `country`, dataset: `wb_health_population`, column: `country_name`
5. Disable the checkbox `Can select multiple values`
6. Save the filter
Filter should be as
<img width="873" alt="Screenshot 2023-11-02 at 18 10 19" src="https://github.com/apache/superset/assets/6951980/b47525ee-06b2-4b97-bada-a07c7e6f134c">

Use the filter:
1. Choose a value from the filter
2. Click on `Apply Filters`
3. Hover the filter and click the cross to remove the value
4. KO the `Apply Filters` button is not clickable and the value is still filtering the data

### Expected results
Record from 2.1.0:
https://github.com/apache/superset/assets/6951980/1f71ae6a-7f0e-4c5a-b31f-3bdb6ac339d2

### Actual results
Record from 3.0.1
https://github.com/apache/superset/assets/6951980/e93ffb24-234a-4672-b9aa-82c75a75fc1f

### Environment

(please complete the following information):

- browser type and version: Firefox 119
- superset version: 3.0.1 via docker image `apache/superset:3.0.1`
- python version: 3.9.18
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional remarks
If guided in the right direction, I can propose a fix.
Regards,

**Comment by michael-s-molina** [comment]
Thank you for the great issue description @ablanchard! I created a PR to fix the issue.

**Comment by skannan-maf** [comment]
I am having the same issue... Can someone tell me which superset version fixed this issue?

**Comment by rusackas** [comment]
> I am having the same issue... Can someone tell me which superset version fixed this issue?

Looks like 3.0 _should_ have it, and 3.1 for sure.

**Comment by rusackas** [comment]
It seems to be in 3.0.2, 3.0.3, 3.0.4.
