### ISSUE TITLE
AUTH_ROLES_MAPPING

### ISSUE THREAD

**Issue by mile15myyahoo** [apache/superset#25849]
AUTH_ROLES_MAPPING somehow does not work.
I have this configuration in my values.yaml
   
    AUTH_ROLE_ADMIN = 'Admin'
    AUTH_ROLE_PUBLIC = 'Public'
    ENABLE_PROXY_FIX=  True
    AUTH_USER_REGISTRATION = True
    AUTH_USER_REGISTRATION_ROLE = "Admin"
    AUTH_ROLES_SYNC_AT_LOGIN = True
    AUTH_ROLES_MAPPING = { 
      'SUPERSET_USERS': 'Gamma', 
      'SUPSERSET_ADMIN': 'Admin'
    }

#### 

1. Install superset helm on kubernetes cluster
2. Enable AZURE AD OAUTH
3.  Map AZURE AD Groups to superset roles
4. Login

### Expected results

As a member of SUPERSET_USER group, i expect after login to get Gamma role. Instead, I get the Public role

### Actual results
The user or users from SUPERSET_USERS group do not get the role Gamma as configured

Need some help.

Thank you!

**Comment by sfirke** [comment]
Looks pretty good, only difference is my config has brackets like:
```
AUTH_ROLES_MAPPING = { 
  'SUPERSET_USERS': ['Gamma'], 
  'SUPSERSET_ADMIN': ['Admin']
}
```
Does that fix it?

**Comment by mile15myyahoo** [comment]
Hi @sfirke 

First, thank you for your answer.  I've tried your suggestion also but without any success.
Do you have any special configuration for your azure service principal?

Thanks!

**Comment by sfirke** [comment]
In the Azure app registration I have granted the permission `GroupMember.Read.All`

**Comment by rusackas** [comment]
Since there's no response to the last comment helping to diagnose/fix, I'll assume that it either worked out, or OP has moved on. Closing this one out as stale, but happy to revisit/reopen as warranted.

**Comment by skuchipu** [comment]
/reopen
I'm facing the same issue and was not successful with auth role mapping using Azure SSO
