### ISSUE TITLE
Documentation incorrect: SESSION_COOKIE_SECURE is true by default

### ISSUE THREAD

**Issue by ewan-escience** [apache/superset#25854]
On https://superset.apache.org/docs/security/, it say that the value of `SESSION_COOKIE_SECURE` is by default `False`. However, trying it out through Docker, in the response header you can see that the cookie is set to be `Secure` (and indeed, I cannot login).

Additionally, it would be nice if this could be configured through an `--env` flag when using `docker run`.

**Comment by sfirke** [comment]
I wonder where that value of `Secure` is getting set.  I am looking at the config.py which is the default values if they're not overridden elsewhere and it looks like that variable defaults to `False`: https://github.com/apache/superset/blob/master/superset/config.py#L1475

So somewhere in the process, your Docker deployment is overwriting that, I think.
