### ISSUE TITLE
Accessibility: Associate label with form control on dashboard filters

### ISSUE THREAD

**Issue by yousoph** [apache/superset#25859]
On dashboards, when using a screen reader, the relationship between labels and their form controls is not clear. 

#### How to reproduce the bug

1. Create a dashboard with some filters 
2. Use a screen reader on the dashboard filters 

### Expected results
User can understand the label of the form control using a screen reader 
https://www.w3.org/TR/WCAG22/#info-and-relationships

### Actual results

Label for the filters aren't associated with the controls, so it's hard to understand the context of the filters  
![image](https://github.com/user-attachments/assets/04b98581-2946-421d-970b-b9aea0b852c2)

### Environment

(please complete the following information):

- browser type and version:
- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by ncar285** [comment]
I'll take this one if it's free

**Comment by eschutho** [comment]
Great, thanks @ncar285!

**Comment by sachinks07** [comment]
I would like to work on this issue

**Comment by alexandrusoare** [comment]
I am interested in working on this one
