### ISSUE TITLE
Time Grain Missing in Time-Series Table Chart

### ISSUE THREAD

**Issue by JohnDietrich-Pepper** [apache/superset#25864]
We upgraded our instance of Superset to 3.0 and we are having an issue with the time-series tables, namely the time grain selector is no longer present and thus time grain can no longer be modified beyond the time grain of the underlying column.  

We tried to work around this issue by creating custom sql for the time column, but it appears that the time-series table simply ignores this and defaults to the P1D setting.

Here is where the time grain selector used to be:
![Timegrain](https://github.com/apache/superset/assets/106880343/621e5a1b-e7a0-495e-9254-562a07ad7a82)

The only work around is to export the chart, manually edit the chart.yaml file to set the time grain you want P1W, and then reupload.

**Comment by sfirke** [comment]
Can you post a screenshot of what it looks like now?

**Comment by rusackas** [comment]
Hmm... I'm not sure what might've happened there, but it IS there in current `master` meaning it's _likely_ in 3.1/4.0, but at least it's patched!
<img width="319" alt="image" src="https://github.com/apache/superset/assets/812905/78e3295d-adee-4e3c-8f34-634f7b39b269">
Holler if you think this warrants anything further.
