### ISSUE TITLE
Changing (unintended) graph when using extra controls 

### ISSUE THREAD

**Issue by Vigano-marco** [apache/superset#25892]
Hello everyone , 
I am new to superset and I am making my first Dashboard . However I am experiencing a problem with the "Area Chart (Legacy )" chart and using the extra controls . When I create it I set it to show the chart in "expanded" mode (Figure 1 ) . 

If I then later go to select another view , such as "Stacked" (Fig 2 ) and then go back to display it as "Expanded"  , the graph looks different and obviously wrong (Fig 3 ) . 

I do not understand if it is a Superset error or something I do not understand about using the "EXTRA CONTROLS" function . Would you know how to help me?  

To reproduce the error : 
- create the chart "Area Chart (Legacy)"
- go to "CUSTOMIZE" and unlock the function "EXTRA CONTROLS"
- go to change view by selecting the fields in the top left of the chart 

FIG 1 
![Immagine1](https://github.com/apache/superset/assets/76043482/6660dcd9-c5c2-412f-9159-7cef6f3aaa28)

FIG 2 
![Immagine](https://github.com/apache/superset/assets/76043482/86ab151c-f6a3-4c2f-896c-a544640b218d)

FIG 3 
![Immagine3](https://github.com/apache/superset/assets/76043482/11e32d5e-fc84-4a2d-82e8-60107bd0ac6f)

**Comment by rusackas** [comment]
Hi there. The Legacy Area chart has been deprecated/removed, so this is no longer relevant in current Superset. That said, the chart actually looks right to me. The Expanded mode is a "contribution" chart (note the percentage axis on the left). At any given point in time, the areas are proportionally correct, showing the percentage of each series as it contributes to the whole.
