### ISSUE TITLE
bug: Filters are not updating with force update if cache is enabled for some time

### ISSUE THREAD

**Issue by pankajsoni22** [apache/superset#25893]
When the dashboard has a filter and responses are cached for let say 24 hours, even after force refreshing the entire dashboard, list of values in the filter do not update (considering there are new values in filter)

#### How to reproduce the bug

1. Go to dashboard that has dropdown filter
2. Force refresh the entire dashboard
3. If you expect new value in the filter, it will not be there.

### Expected results

Updated filter value should be there.

### Actual results

Updated list of values.

### Environment
Caching the data for 24 hours. Using superset 3.0.1

**Comment by rusackas** [comment]
@michael-s-molina @kgabryje do either of you happen to know if the cache of the native filters is tied to the linked of the dashboard? Or if there's another way to clear/refresh the cache for the native filters?

**Comment by michael-s-molina** [comment]
@rusackas Using `master`, I can see that the query to retrieve the filters values is being fired but is not using the `force=true` parameter and will return cached values.

https://github.com/apache/superset/assets/70410625/e988b1c9-af93-49db-8d2c-51b427399869

**Comment by jwdalton** [comment]
This patch seems to have fixed it for me. Now when I click "Refresh Dashboard", the refresh calls for the filters also have `force=true` set.

``
diff --git a/superset-frontend/src/dashboard/components/nativeFilters/FilterBar/FilterControls/FilterValue.tsx b/superset-frontend/src/dashboard/components/nativeFilters/FilterBar/FilterControls/FilterValue.tsx
index 5041fa3c97..2e626636c7 100644
--- a/superset-frontend/src/dashboard/components/nativeFilters/FilterBar/FilterControls/FilterValue.tsx
+++ b/superset-frontend/src/dashboard/components/nativeFilters/FilterBar/FilterControls/FilterValue.tsx
@@ -174,7 +174,7 @@ const FilterValue: React.FC<FilterControlProps> = ({
       setIsRefreshing(true);
       getChartDataRequest({
         formData: newFormData,
-        force: false,
+        force: shouldRefresh,
         ownState: filterOwnState,
       })
         .then(({ response, json }) => {
``

**Comment by ka-weihe** [comment]
https://github.com/apache/superset/issues/21234

**Comment by ka-weihe** [comment]
I have opened a PR for fixing this:
https://github.com/apache/superset/pull/29291
