### ISSUE TITLE
Trying to execute "superset compute-thumbnails" returns error: "module 'PIL.Image' has no attribute 'ANTIALIAS' when using Pillow 10.0.0+

### ISSUE THREAD

**Issue by maxgillmaxgill** [apache/superset#25902]
When trying to execute "superset compute-thumbnails", I get an error:
"module 'PIL.Image' has no attribute 'ANTIALIAS'". After some Googling it seems that

ANTIALIAS was removed in Pillow 10.0.0 (after being deprecated through many previous versions). Now you need to use PIL.Image.LANCZOS or PIL.Image.Resampling.LANCZOS.

I fixed it by doing this: pip install Pillow==9.5.0

#### How to reproduce the bug

1. superset compute-thumbnails

### Expected results

No errors.

### Actual results

Errors.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sfirke** [comment]
Thanks for the bug report and reporting what worked for you.  After a quick search of the codebase I'm guessing the fix would be to update this line to one of the newer functions you mention: https://github.com/apache/superset/blob/83b7fa92af3994d2ac0cb296c04e5253f50a96d6/superset/utils/screenshots.py#L204

That's not a part of the codebase I'm familiar with unfortunately.  Would you want to test a fix and submit a pull request if it works?

**Comment by rusackas** [comment]
PR was merged, and this should have been closed. Holler if there's still an issue!
