### ISSUE TITLE
'Drill to detail' and 'Driil by' - Error: {'per_page': ['Must be greater than or equal to 1 and less than or equal to 10.']}

### ISSUE THREAD

**Issue by aszczepanska** [apache/superset#25909]
When I try to use 'Drill to detail' or 'Drill by' features I receive an error message:
Error: {'per_page': ['Must be greater than or equal to 1 and less than or equal to 10.']}

I tried to use the feature in two deployments:
 - docker: docker-compose-non-dev, TAG=3.0.1
 - kebernestes: helm chart 0.10.14, TAG=3.0.1
and on different browsers (Firefox, Chrome, Edge).
The result on both deployments is the same:

superset_app          | 172.28.0.1 - - [08/Nov/2023:08:57:43 +0000] "POST /datasource/samples?force=false&datasource_type=table&datasource_id=18&per_page=50&page=1 HTTP/1.1" 400 95 "http://localhost:8088/superset/dashboard/10/?native_filters_key=rcqz_oA2Id3cQXghURt-88NtzMFENSNF136Fv8RGRkVUxoaroGF-eVdKWxOEgrqx" "Mozilla/5.0 (X11; Linux x86_64; rv:103.0) Gecko/20100101 Firefox/103.0"

superset_app          | 172.28.0.1 - - [08/Nov/2023:08:54:35 +0000] "POST /datasource/samples?force=false&datasource_type=table&datasource_id=18&per_page=50&page=1 HTTP/1.1" 400 95 "http://localhost:8088/superset/dashboard/10/?native_filters_key=tQ6U6Xb_PMEkzflgAQ5r8dlqiyTt-uw1da_9w6BimVVS6_7SjkIo7S12gwobW-gO" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.58"

#### How to reproduce the bug

1. Go to any aggregated chart (can be one of the samples chart)
2. Click on 'Drill to detail' or 'Drill by'
3. See error: Error: {'per_page': ['Must be greater than or equal to 1 and less than or equal to 10.']}

### Expected results

The window with details should occur.

### Actual results

Error message occurs:
Error: {'per_page': ['Must be greater than or equal to 1 and less than or equal to 10.']}

#### Screenshots
![image](https://github.com/apache/superset/assets/118458440/9d84b34f-5eef-43ce-b0d1-d0cee3cdae60)

### Environment

(please complete the following information):

- browser type and version: Mozilla/5.0 (but I also tried in Chrome and Edge)
- superset version: 3.0.1 (helm chart  0.10.14, or docker-compose-non-dev, TAG=3.0.1)
- python version: 
- node.js version:
- any feature flags active:
              "ALERT_REPORTS": True,  
              "EMBEDDED_SUPERSET": True, 
              "EMBEDDABLE_CHARTS": True,
              "DRILL_TO_DETAIL": True,
              "DRILL_BY": True,
              "ENABLE_TEMPLATE_PROCESSING": True,
              "DASHBOARD_CROSS_FILTERS": True,
              "DYNAMIC_PLUGINS": True,
              "VERSIONED_EXPORT": True

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [v] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [v] I have reproduced the issue with at least the latest released version of superset.
- [v] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by michael-s-molina** [comment]
@aszczepanska the results are limited by [SAMPLES_ROW_LIMIT](https://github.com/apache/superset/blob/136ad0ef4fcfab19f1aa60c08780fa676cb00844/superset/config.py#L148C4-L148C4). You probably have set that to 10.
