### ISSUE TITLE
Incorrect data on Time-series chart

### ISSUE THREAD

**Issue by stasDomb** [apache/superset#25930]
Incorrect counts on the graph depends on chosen time period. 

#### How to reproduce the bug
Please, see the pictures:
1) Please, take a look on:
grain - Day
time period ~last 6 months
pay attention on the last mont - many dots
<img width="1777" alt="Screenshot 2023-11-09 at 09 53 36" src="https://github.com/apache/superset/assets/27229336/8ad01023-cafe-435d-9b48-b9499f9c5fb8">

2) Change the time period to last 11 months
pay attention on the last month, since October - only 2 dots
<img width="1772" alt="Screenshot 2023-11-09 at 09 55 45" src="https://github.com/apache/superset/assets/27229336/f2f2dfcf-3064-43b2-9e2d-ce9a995f45b4">
<img width="257" alt="Screenshot 2023-11-09 at 09 56 53" src="https://github.com/apache/superset/assets/27229336/6b6790cb-8f90-45db-9e66-bc9e7ab2cc04">
<img width="227" alt="Screenshot 2023-11-09 at 09 57 01" src="https://github.com/apache/superset/assets/27229336/01698514-7f46-45bd-acf7-ad33b303a847">

It's absolutely incorrect. It's less data, that must be present

### Expected results

The correct data on the graph in any time periods

### Environment

- Safari Version 17.1 (19616.2.9.11.7), Google Chrome 119.0.6045.123 
- superset version: `3.0.1`

**Comment by rusackas** [comment]
Are you able to provide some (sanitized, perhaps) sample dataset as a CSV file, so we can reproduce this issue? Or an example using data from the example charts/dashboards?

**Comment by rusackas** [comment]
This is unactionable without a reproducible test case. If it's still happening in 4.0, and you can help us reproduce it, we can try to tackle it. Happy to reopen if that's the case!
