### ISSUE TITLE
Documentation installing from scratch is missing a reference to the configuration SUPERSET_CONFIG_PATH variable 

### ISSUE THREAD

**Issue by lgharibpmu** [apache/superset#25936]
## Description

When a new user try to install Superset step by step following the `installing-superset-from-scratch.mdx` documentation is missing two pieces of information:

1. How to give access to superset to the `superset_config.py` file
2. How to export FLASK_APP=superset prior to the database generation

**Comment by rusackas** [comment]
Trying to revisit the conversation on this PR. We might want to close this since it's not _really_ a Superset bug, but I'll leave it open for now in hopes that we can get your PR addressed.

**Comment by rusackas** [comment]
Closing this as stale, especially since the PR is closed too... but happy to pick this up again if you're interested.
