### ISSUE TITLE
[SIP] Proposal for customize email subject for reports and alerts

### ISSUE THREAD

**Issue by puridach-w** [apache/superset#25945]
### Motivation

The primary motivation for this feature comes from our need to send parameters along with the subject of the alert or report email. This feature is designed to make the email subject customizable, enhancing users' ability to make targeted and specific email subject lines.

### Proposed Change

I propose a feature that allows users to customize the email subject of a report or alert. In the report submission creation interface, I plan to add a text area for entering the email subject. If a user inputs a value in this field, the email's subject will be this value. If not, the system will assign a default email subject line.

**Before:**

<img width="1171" alt="Screenshot 2566-11-10 at 15 15 52" src="https://github.com/apache/superset/assets/76474644/ec28fb0c-bd8e-4f5d-a577-26df3f7a0e27">

<img width="1173" alt="Screenshot 2566-11-10 at 14 28 09" src="https://github.com/apache/superset/assets/76474644/edb3d66f-2704-48bd-b4ab-21b7a282c8d4">

**After:** 

<img width="1177" alt="Screenshot 2566-11-10 at 14 08 56" src="https://github.com/apache/superset/assets/76474644/4b2e2329-e9cd-49ad-af79-c384a6f45469">

<img width="1172" alt="Screenshot 2566-11-10 at 14 09 34" src="https://github.com/apache/superset/assets/76474644/1fb4a563-522e-42bb-81a8-eccaaf77755d">

### New or Changed Public Interfaces

I will make a small change to the UI in the 'create alert/report' modal section. If the user selects the email sending method, an additional text area will be available for the user to populate the email subject line.

### New dependencies

No new packages or libraries will be required to implement this feature.

### Migration Plan and Compatibility

To incorporate this feature, we will need to initiate a database migration to add columns dedicated to storing email subject lines. We have tested this feature with Superset version 3.0.1 and confirmed that it operates correctly.

### Rejected Alternatives

None

**Comment by michael-s-molina** [comment]
Hi @puridach-w. Thanks for the proposal. I think it would be a good idea to incorporate your changes into this [discussion](https://github.com/apache/superset/discussions/25729) which will become a SIP in the future.

**Comment by rusackas** [comment]
CC @yousoph and @eschutho on the above. I think we can roll this into the discussion/SIP on the other thread, but I'm also wondering if this change even requires a SIP. If the default remains the same, but this just adds a dimension of customization, it feels harmless.

**Comment by puridach-w** [comment]
Move the discussion to following SIP: https://github.com/apache/superset/discussions/25729

**Comment by rusackas** [comment]
It seems this SIP was never numbered or put up for a [DISCUSS] thread. Is there still intent to follow through the process with this one? Are you interested in opening the PR if we do usher it through, @puridach-w ?

**Comment by puridach-w** [comment]
This PR relate to this SIP has been completed. I will now close it. Thank you.
