### ISSUE TITLE
Jinja template does not work for superset 2.1.1

### ISSUE THREAD

**Issue by hectoradrian961030** [apache/superset#25959]
I install superset 2.1.1 following the next steps:

git clone https://github.com/apache/superset.git
git checkout 2.1.1
TAG=2.1.1 docker compose -f docker-compose-non-dev.yml pull

I also change 
DEFAULT_FEATURE_FLAGS: {
    ...
    "ENABLE_TEMPLATE_PROCESSING": True,
     ...
}
in superset/config.py

TAG=2.1.1 docker compose -f docker-compose-non-dev.yml up -d

### Expected results

SELECT '{{current_user_id()}}'

or

SELECT {{current_user_id()}}

should return a number

### Actual results

SELECT '{{current_user_id()}}'

return the literal '{{current_user_id()}}'

without the quotes
SELECT {{current_user_id()}} 

the result is:
PostgreSQL Error
Please check your query for syntax errors at or near "{". Then, try running your query again.

![jinja_superset](https://github.com/apache/superset/assets/49923983/fb1a9513-5751-4217-b9b9-89af8c9f5ac6)
![jinja_superset2](https://github.com/apache/superset/assets/49923983/ae2476aa-c02b-4474-8caa-7132b8399ae3)

**Comment by sfirke** [comment]
Try:

```
FEATURE_FLAGS = {
    "ENABLE_TEMPLATE_PROCESSING": True
}
```
You have a colon, not an equals sign.

**Comment by sfirke** [comment]
I'm going to close this as it appears to be the case of a simple typo.  If that's not the case and you believe there's a bug in the Superset codebase, please feel free to reopen.

**Comment by hectoradrian961030** [comment]
> Try:
> 
> ```
> FEATURE_FLAGS = {
>     "ENABLE_TEMPLATE_PROCESSING": True
> }
> ```
> 
> You have a colon, not an equals sign.

Sorry, I copied it wrong in the question, it's always been like this.

DEFAULT_FEATURE_FLAGS: Dict[str, bool] = {
...
}

The error was that I was editing DEFAULT_FEATURE_FLAGS in superset\config.py

And seeing that you have responded by editing FEATURE_FLAGS, I have edited FEATURE_FLAGS in docker\pythonpath_dev\superset_config.py and it worked. Thank you.
