### ISSUE TITLE
Alerts and Reports - Execution Log Error

### ISSUE THREAD

**Issue by adamhsquared** [apache/superset#25969]
Since upgrading to Superset 3.0.0 new Alerts and Reports are not generating / sending. Existing reports are working without issue, but when I create a new Alert or Report, it is stuck on "report sending" with nothing in the error log. 

#### How to reproduce the bug

1. Create a new report
2. Scheduled for Every minute
3. Select Slack as the notification method.
4. Save

### Expected results

I expect for Reports to be sent and Alerts to trigger when the parameters are met.

### Actual results

Report is stuck on "report sending" and there is nothing in the error log. A journalctl for the celery worker has the following output

```
Nov 13 16:42:00 localhost celery-worker[1112347]: superset.reports.commands.exceptions.ReportScheduleUnexpectedError: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.

Nov 13 16:42:00 localhost celery-worker[1112347]: [SQL: INSERT INTO report_execution_log (uuid, scheduled_dttm, start_dttm, end_dttm, value, value_row_json, state, error_message, report_schedule_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)]

Nov 13 16:42:00 localhost celery-worker[1112347]: [parameters: [{'uuid': UUID('c11763ee-00c9-4d2e-8421-767f581223ec'), 'report_schedule_id': 14, 'scheduled_dttm': '2023-11-13T16:42:00', 'state': 'Working', 'end_dt ... (88 characters truncated) ... e is still working, refusing to re-compute.', 'start_dttm': datetime.datetime(2023, 11, 13, 16, 42, 0, 66614), 'value_row_json': None, 'value': None}]]
```

#### Screenshots

![image](https://github.com/apache/superset/assets/100448184/a5b5e5ca-e040-4ef1-8e8c-72562d897800)

### Environment

(please complete the following information):

- browser type and version: Vivaldi 6.4.3160.41
- superset version: `Superset 3.0.0`
- python version: `Python 3.9.2`
- any feature flags active:

Note : Tagging System was enabled but I was having issues with other parts of superset so I set to False
```
FEATURE_FLAGS = {
    "ALERT_REPORTS": True,
    "DASHBOARD_NATIVE_FILTERS": True,
    "DASHBOARD_CROSS_FILTERS": True,
    "ENABLE_TEMPLATE_PROCESSING": True,
    "ENABLE_SCHEDULED_EMAIL_REPORTS": True,
    "ALERT_REPORTS_NOTIFICATION_DRY_RUN": False,
    "EMAIL_NOTIFICATIONS": True,
    "GENERIC_CHART_AXES": True,
    "TAGGING_SYSTEM": False
}
```
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

If I have missed anything that could be valuable, it was not intentional. I want to provide whatever I can to help, Please let me know if there is additional information I can provide.

This problem arose after upgrading from Version 2 to 3.0.0. I believe but cannot confirm that the reports that are working were created before the upgrade. (There may be a report that has been generated since then that works so I don't want to mislead anyone).

**Comment by sfirke** [comment]
Are you using SQLite for your metadata database?

**Comment by adamhsquared** [comment]
Hi there, 
I was, I found a few others reference that SQLite was a bit of an issue, so I went ahead and rebuilt the server with a PostgreSQL metadata database. I wanted to try to prevent further issues. So far it has been working well.

**Comment by praveenamdas** [comment]
For me, the reports are not showing any log and the last run time

**Comment by sfirke** [comment]
@adamhsquared thanks for letting us know this is resolved by switching to Postgres, I'll keep an eye out to see if SQLite causes this problem for others.  Superset is moving away from it generally.

@praveenamdas that sounds like a different issue than what's reported here.  I'm going to close this issue.  If you would like help troubleshooting alerts & reports, I suggest either posting a Github Discussion or joining the Superset Slack chat where community members help each other.

**Comment by praveenamdas** [comment]
No i am using Postgres only.. you can see it in that screenshot actually

**Comment by sfirke** [comment]
Right, this issue was opened by someone else and is caused (apparently) by SQLite.  Sounds like you have a different problem.  Please create a discussion or Slack post for assistance.
