### ISSUE TITLE
custom auth token validation check for all request coming to any endpoint

### ISSUE THREAD

**Issue by Nivraj** [apache/superset#25964]
I was able to implement and overide superset login logic method, using custom authdb., once the user is logged in and redirected to other dashboard page. im not able to reverify gateway token using custom auth for next incoming requests from same browser as user has session.

how do i override other endpoints to first validate gateway token with auth url and then allow access to components

**Comment by rusackas** [comment]
This doesn't sound like a bug, but rather a custom code / developer issue. I'll close this since nobody has answered in 4 months, but if you still face this, I'd encourage you to check out the `#customizing-superset` channel on [slack](http://bit.ly/join-superset-slack)
