### ISSUE TITLE
Not work swager 3.0.0

### ISSUE THREAD

**Issue by sonfire186** [apache/superset#25979]
Install
```
git checkout 3.0.0
TAG=3.0.0 docker compose -f docker-compose-non-dev.yml pull
TAG=3.0.0 docker compose -f docker-compose-non-dev.yml up
```
http://localhost:8088/swagger/v1
![image](https://github.com/apache/superset/assets/26105224/b6905aff-a06a-4af6-9eaf-b3aee2b6a0ac)

Version 2.1.2 it`s work

**Comment by sebastianliebscher** [comment]
Hi @sonfire186 this is fixed in `3.0.1`, see https://github.com/apache/superset/issues/24818
