### ISSUE TITLE
Heatmap chart value colors don't change when colors on the chart are "NORMALIZED"

### ISSUE THREAD

**Issue by markostefanovic1** [apache/superset#25981]
## Screenshot
First screenshot is showing when "NORMALIZED" checkbox is **unselected** in filters.
![Screenshot 2023-11-14 at 13 04 33](https://github.com/apache/superset/assets/105298890/e97be526-a33e-4f4b-b799-20c669317ab1)

Second screenshot is showing when "NORMALIZED" checkbox is **selected** in filters.

![Screenshot 2023-11-14 at 13 04 37](https://github.com/apache/superset/assets/105298890/9d27e00c-f6b4-4d0e-8d85-8a16428de822)

## Description

This is tested in Preset version 2023.43.2.

The colors of the values on the Heatmap chart stay the same when the "NORMALIZED" checkbox is selected, they stay as if it was not selected, and the colors of the heatmap change, making for a very unpleasant mix of colors which are sometimes almost unreadable.

**Comment by rusackas** [comment]
Quite right, the text/value color is not ideal at all here. I think @yousoph and I came to the same conclusion once, but it just wasn't prioritized. GPT suggests this as a starting point to use RGB color luminance to determine the appropriately contrast-y black or white text color:

```
function calculateRelativeLuminance(rgb) {
    const [R, G, B] = rgb.map(component => component / 255);
    const L = 0.2126 * R + 0.7152 * G + 0.0722 * B;
    return L;
}

function determineTextColor(rgb) {
    const luminance = calculateRelativeLuminance(rgb);
    return luminance > 0.5 ? "black" : "white";
}

// Example usage:
const rgbColor = [128, 128, 128]; // Replace with your RGB color value
const textColor = determineTextColor(rgbColor);
console.log("Recommended text color:", textColor);
```
