### ISSUE TITLE
Unable to read HANA tables containing a "/"

### ISSUE THREAD

**Issue by mennereau** [apache/superset#26032]
I have installed Superset version 3.0.2 release
I have installed HANA drivers with command pip install hdbcli sqlalchemy-hana

I can access to all HANA tables which are named without "/"

When I select a table containing "/" I received this error message:

An Error Occurred
Unable to load columns for the selected table. Please select a different table.

I have read following fix
https://github.com/apache/superset/pull/24796/files

But I already have the corrected files in my superset installation

**Comment by rusackas** [comment]
@mennereau are you still facing this? I'm wondering if it's somehow hana specific, since this thread is effectively stale and we haven't heard any complaints following that PR being merged. I'll close it for now, but we can reopen if you're still seeing it in 3.1/4.0.
