### ISSUE TITLE
2 spaces for permission "can import  on ImportExportRestApi"

### ISSUE THREAD

**Issue by xavier-GitHub76** [apache/superset#26055]
I use Superset v3.0.0.

2 spaces are present for the permission "can import  on ImportExportRestApi"

![image](https://github.com/apache/superset/assets/82046143/d719696e-cbed-430a-acfc-72b8db4fc81d)
![image](https://github.com/apache/superset/assets/82046143/3d5705cb-d317-4138-a72f-0d4bc70a6790)

Regards

**Comment by rusackas** [comment]
This doesn't seem to be the case in current versions anymore. Not sure when it was fixed, but it's fixed! :D
