### ISSUE TITLE
Issue 1035 error Failed to start remote query on a worker.

### ISSUE THREAD

**Issue by prafullazee** [apache/superset#26050]
#### How to reproduce the bug

1. Go to 'SQL Lab'
2. Write a normal SELECT query
3. Click on 'RUN'
```
DB engine Error
Failed to start remote query on a worker.


This may be triggered by:
Issue 1035 - Failed to start remote query on a worker. 

See less
```
### Expected results

Should give result of sql query.

### Actual results

Above error comes on clicking RUN.

#### Screenshots
<img width="1440" alt="Screenshot 2023-11-21 at 12 56 20 PM" src="https://github.com/apache/superset/assets/110979212/437a55eb-2043-45c0-9ed1-d16bf809cd09">

### Environment

(please complete the following information):

- browser type and version: Chrome 118.0.5993.117
- superset version: `superset version`: Superset 2.0
- python version: `python --version`:  3.9.16
- node.js version: `node -v`: 16
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- I have checked the superset logs for python stacktraces and included it here as text if there are any.
- I have reproduced the issue with at least the latest released version of superset.
- I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

From ECS cluster and chart it is working fine.

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
