### ISSUE TITLE
The documentation about permissions is not up to date

### ISSUE THREAD

**Issue by xavier-GitHub76** [apache/superset#26056]
I use Superset V3.0.0

The documentation about permissions is not up to date.
Additions or deletions are necessary.

Documentation : https://github.com/apache/superset/blob/master/RESOURCES/STANDARD_ROLES.md

Following permissions are present on Superset  V3.0.0 but the documentation don't mention them :
- can add on Tags
- can add on UserRemoteUserModelView
- can delete on Tags
- can delete on UserRemoteUserModelView
- can download on Tags
- can edit on Tags
- can edit on UserRemoteUserModelView
- can estimate query cost on SQLLab
- can invalidate on CacheRestApi
- can list on Tags
- can list on UserRemoteUserModelView
- can read on Row Level Security
- can read on RowLevelSecurity
- can read on Tag
- can show on Tags
- can show on UserRemoteUserModelView
- can tags on TagView
- can userinfo on UserRemoteUserModelView
- can warm up cache on Chart
- can warm up cache on Dataset
- can write on Row Level Security
- can write on Tag
- menu access on Tags
- userinfoedit on UserRemoteUserModelView

Following permissions are not present on Superset  V3.0.0 but the documentation mention them :
- can add on UserDBModelView
- can add on UserOAuthModelView
- can delete on UserDBModelView
- can delete on UserOAuthModelView
- can edit on UserDBModelView
- can edit on UserOAuthModelView
- can function names on Database
- can list on UserDBModelView
- can list on UserOAuthModelView
- can schemas access for csv upload on Superset
- can show on UserDBModelView
- can show on UserOAuthModelView
- can userinfo on UserDBModelView
- can userinfo on UserOAuthModelView
- menu access on Upload a Columnar file
- menu access on Upload a CSV
- menu access on Upload Excel
- resetmypassword on UserDBModelView
- resetpasswords on UserDBModelView
- userinfoedit on UserDBModelView
- userinfoedit on UserOAuthModelView

Best regards

**Comment by ajinkyavbhandare** [comment]
Can I work on this?

**Comment by ajinkyavbhandare** [comment]
Could you assign me the same @xavier-GitHub76 . Thankyou

**Comment by xavier-GitHub76** [comment]
Sorry, I don't kwow to do it. I'm a begginer on Github.
I see "Assignees : No one assigned" on this issue but I don't see any button to change this state.
Maybe I have not permission.

**Comment by xavier-GitHub76** [comment]
Hello @ajinkyavbhandare 
have you got worked on this issue ?
I ask the question because I have a doubt on my list
Regards

**Comment by ajinkyavbhandare** [comment]
Hello @xavier-GitHub76, I haven't worked on this issue. I appreciate you checking in.

**Comment by xavier-GitHub76** [comment]
Hello @ajinkyavbhandare ,
I will check the list of permission on the 3.1.1 version and will update this report.
Regards
