### ISSUE TITLE
Docker Compose starts the necessary containers, but the login page is not available and returns an error message about the missing trino package

### ISSUE THREAD

**Issue by yaroslav-serhiichuk** [apache/superset#26067]
#### How to reproduce the bug

1. Pull superset repository
2. Run docker compose up for non-production docker-compose.yml
3. Wait until all containers up
4. Try to open login page http://127.0.0.1:8088/login/

### Expected results

User see the login page

### Actual results

Error displayed in the browser:
{"errors": [{"message": "No module named 'trino'", "error_type": "GENERIC_BACKEND_ERROR", "level": "error", "extra": {"issue_codes": [{"code": 1011, "message": "Issue 1011 - Superset encountered an unexpected error."}]}}]}

Error in container logs:
superset_app           | 2023-11-22 09:09:32,647:ERROR:superset.views.base:No module named 'trino'
superset_app           | Traceback (most recent call last):
superset_app           |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
superset_app           |     rv = self.dispatch_request()
superset_app           |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
superset_app           |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
superset_app           |   File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/security/views.py", line 526, in login
superset_app           |     return self.render_template(
superset_app           |   File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/baseviews.py", line 342, in render_template
superset_app           |     return render_template(
superset_app           |   File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
superset_app           |     return _render(app, template, context)
superset_app           |   File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 130, in _render
superset_app           |     rv = template.render(context)
superset_app           |   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
superset_app           |     self.environment.handle_exception()
superset_app           |   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
superset_app           |     raise rewrite_traceback_stack(source=source)
superset_app           |   File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/templates/appbuilder/general/security/login_db.html", line 2, in top-level template code
superset_app           |     {% extends "appbuilder/base.html" %}
superset_app           |   File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/templates/appbuilder/base.html", line 1, in top-level template code
superset_app           |     {% extends base_template %}
superset_app           |   File "/app/superset/templates/superset/base.html", line 20, in top-level template code
superset_app           |     {% from 'superset/partials/asset_bundle.html' import css_bundle, js_bundle with context %}
superset_app           |   File "/app/superset/templates/appbuilder/baselayout.html", line 20, in top-level template code
superset_app           |     {% import 'appbuilder/baselib.html' as baselib %}
superset_app           |   File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 42, in top-level template code
superset_app           |     {% block body %}
superset_app           |   File "/app/superset/templates/appbuilder/baselayout.html", line 45, in block 'body'
superset_app           |     <div id="app" data-bootstrap="{{ bootstrap_data() }}"></div>
superset_app           |   File "/app/superset/views/base.py", line 540, in serialize_bootstrap_data
superset_app           |     {"common": common_bootstrap_payload()},
superset_app           |   File "/app/superset/views/base.py", line 430, in common_bootstrap_payload
superset_app           |     **cached_common_bootstrap_data(utils.get_user_id(), get_locale()),
superset_app           |   File "/usr/local/lib/python3.9/site-packages/flask_caching/__init__.py", line 872, in decorated_function
superset_app           |     rv = self._call_fn(f, *args, **kwargs)
superset_app           |   File "/usr/local/lib/python3.9/site-packages/flask_caching/__init__.py", line 175, in _call_fn
superset_app           |     return ensure_sync(fn)(*args, **kwargs)
superset_app           |   File "/app/superset/views/base.py", line 409, in cached_common_bootstrap_data
superset_app           |     available_specs = get_available_engine_specs()
superset_app           |   File "/app/superset/db_engine_specs/__init__.py", line 174, in get_available_engine_specs
superset_app           |     for engine_spec in load_engine_specs():
superset_app           |   File "/app/superset/db_engine_specs/__init__.py", line 69, in load_engine_specs
superset_app           |     module = import_module(module_info.name, package=__name__)
superset_app           |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
superset_app           |     return _bootstrap._gcd_import(name[level:], package, level)
superset_app           |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
superset_app           |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
superset_app           |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
superset_app           |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
superset_app           |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
superset_app           |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
superset_app           |   File "/app/superset/db_engine_specs/trino.py", line 30, in <module>
superset_app           |     from trino.sqlalchemy import datatype
superset_app           | ModuleNotFoundError: No module named 'trino'

#### Screenshots

![1](https://github.com/apache/superset/assets/27965478/df344292-dc67-499a-9618-30958077bfee)
![2](https://github.com/apache/superset/assets/27965478/c4fe5045-3679-415b-93fc-4f74ad53ceef)
![3](https://github.com/apache/superset/assets/27965478/520bf034-ddbf-439e-b7b9-5d6a14ca3d13)

### Environment

- browser type and version: Version 119.0.6045.160 (Official Build) (64-bit)
- OS: Ubuntu 22.04.3 LTS
- superset version: 3.0.2rc2
- docker version: 24.0.7, build afdd53b
- python version: 3.10.12
- node.js version: NA
- any feature flags active: NA

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

After entering inside the superset_app container and installing package trino manually https://pypi.org/project/trino/ login page becomes available.
`docker exec -ti superset_app /bin/bash/`
`pip install trino`

**Comment by yaroslav-serhiichuk** [comment]
Duplicates [#26062](https://github.com/apache/superset/issues/26062)

**Comment by sfirke** [comment]
Fixed by #26066
