### ISSUE TITLE
Time filters not being translated, even with appropriate .json, .po & .mo files.

### ISSUE THREAD

**Issue by Ralkion** [apache/superset#26061]
I'm already working on a PR for this - but figured I should create an issue and close the discussion.

===

### Discussed in https://github.com/apache/superset/discussions/25994

<div type='discussions-op-text'>

<sup>Originally posted by **Ralkion** November 15, 2023</sup>
Hello all,

I've been struggling with the translations for a couple of days now and I think I've resolved all my issues except these two. The value displayed in the Time Range filter after selecting a translated option is displayed in English.
![image](https://github.com/apache/superset/assets/90489859/d78be8f7-d695-4efc-aa40-f4678a62160a)

The second issue I've run into is that the Time Grain options are all displayed in English.
![image](https://github.com/apache/superset/assets/90489859/cde0c38a-5961-4d89-aca8-fe685f0bab53)

I've read lots of discussions & MRs around translations - particularly those done by AndVK and hbruch. The most relevant is where hbruch says "No filter for many charts still is not localized." in this issue: https://github.com/apache/superset/issues/17779.

I also found this issue, https://github.com/apache/superset/issues/25728 complaining about the Time Range, and a comment saying that it's fixed in 3.0.0. However when I tried out 3.0.0 I found no changes to the problem outlined in that issue.

Is there something that I've missed in my configuration or are these two not actually translated in the UI?</div>

**Comment by aehanno** [comment]
Hey @Ralkion can you link the PR ? If you have already create one
Thaks
