### ISSUE TITLE
Generated queries contain `LIMIT` even though  `allow_limit_clause = False` in dbEngineSpec.

### ISSUE THREAD

**Issue by Afsalmc** [apache/superset#26068]
#### How to reproduce the bug

1. Go to 'Sqllab'
2. Click on 'SEE TABLE SCHEMA'
3. Scroll down to any schema and click it to preview the table schema.
4. Click the Copy select statement button near table name.
5. In select query you can see LIMIT keyword. 

### Expected results

Generate query with TOP or anything other than LIMIT since allow_limit_clause is false.

### Actual results

Query with LIMIT keyword.

#### Screenshots
![image](https://github.com/apache/superset/assets/48438931/6eaf8edc-22ba-45dc-9916-a79499ed5d07)

### Environment

(please complete the following information):

- browser type and version:
- superset version: `3.0.1`
- python version: `3.10`
- node.js version: `v18.12.1`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!`

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by Afsalmc** [comment]
@michael-s-molina @betodealmeida May I know in the code where it is adding limit 100 ?

**Comment by weikhor** [comment]
I do not  think
