### ISSUE TITLE
No module named 'flask_session'

### ISSUE THREAD

**Issue by gaogaoinvincible** [apache/superset#26070]
#### How to reproduce the bug

1. download the newest version
2. run `docker compose up`

Then output `No module named 'flask_session'`

I use `pip3 install flask_session`

Still output `No module named 'flask_session'`

## bash
superset_worker_beat   | Usage: celery [OPTIONS] COMMAND [ARGS]...
superset_worker_beat   | Try 'celery --help' for help.
superset_worker_beat   |
superset_worker_beat   | Error: Invalid value for '-A' / '--app':
superset_worker_beat   | Unable to load celery application.
superset_worker_beat   | While trying to load the module superset.tasks.celery_app:app the following error occurred:
superset_worker_beat   | Traceback (most recent call last):
superset_worker_beat   |   File "/usr/local/lib/python3.9/site-packages/celery/bin/celery.py", line 53, in convert
superset_worker_beat   |     return find_app(value)
superset_worker_beat   |   File "/usr/local/lib/python3.9/site-packages/celery/app/utils.py", line 384, in find_app
superset_worker_beat   |     sym = symbol_by_name(app, imp=imp)
superset_worker_beat   |   File "/usr/local/lib/python3.9/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
superset_worker_beat   |     module = imp(module_name, package=package, **kwargs)
superset_worker_beat   |   File "/usr/local/lib/python3.9/site-packages/celery/utils/imports.py", line 100, in import_from_cwd
superset_worker_beat   |     return imp(module, package=package)
superset_worker_beat   |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
superset_worker_beat   |     return _bootstrap._gcd_import(name[level:], package, level)
superset_worker_beat   |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
superset_worker_beat   |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
superset_worker_beat   |   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
superset_worker_beat   |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
superset_worker_beat   |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
superset_worker_beat   |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
superset_worker_beat   |   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
superset_worker_beat   |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
superset_worker_beat   |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
superset_worker_beat   |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
superset_worker_beat   |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
superset_worker_beat   |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
superset_worker_beat   |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
superset_worker_beat   |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
superset_worker_beat   |   File "/app/superset/__init__.py", line 21, in <module>
superset_worker_beat   |     from superset.app import create_app
superset_worker_beat   |   File "/app/superset/app.py", line 24, in <module>
superset_worker_beat   |     from superset.initialization import SupersetAppInitializer
superset_worker_beat   |   File "/app/superset/initialization/__init__.py", line 31, in <module>
superset_worker_beat   |     from flask_session import Session
superset_worker_beat   | ModuleNotFoundError: No module named 'flask_session'

**Comment by gaogaoinvincible** [comment]
<img width="204" alt="image" src="https://github.com/apache/superset/assets/13410631/4dcae9d4-b96d-4690-97ab-439ff8e4cd9a">

**Comment by gaogaoinvincible** [comment]
Python 3.11.4

**Comment by sfirke** [comment]
Not sure it will fix this specific problem but I don't think Superset is on Python 3.11 yet.

**Comment by yaroslav-serhiichuk** [comment]
Faced the same issue running 3.0.1 version using docker-compose 
processor: Intel
OS: Ubuntu 22.04.3 LTS
superset version: 3.0.1
docker version: 24.0.7, build afdd53b

**Comment by gaogaoinvincible** [comment]
> Not sure it will fix this specific problem but I don't think Superset is on Python 3.11 yet.

.pyenv/versions/3.9.18

But still no.

**Comment by bhavaysavaliya** [comment]
You made a mistake. Run "pip3 install Flask-Session". I think it should work as given in the official documentation.

**Comment by anthonyorona** [comment]
@bhavaysavaliya I am viewing this guide for latest

https://superset.apache.org/docs/installation/installing-superset-using-docker-compose

Is this the correct doc? I do not see flask_session mentioned

**Comment by Jaszkowic** [comment]
Same error for me. https://github.com/apache/superset on `master` on commit `8644b1a3192ffef3d20357f76cfa1feac20e4147`

Hardware: MacBook with M2 chip

Python 3.11.6

Running `docker-compose up` as suggested in https://superset.apache.org/docs/installation/installing-superset-using-docker-compose yield errors in `superset_app`, `superset_worker` and `superset_worker_beat`:

```
superset_app           | Usage: flask run [OPTIONS]
superset_app           | Try 'flask run --help' for help.
superset_app           |
superset_app           | Error: While importing 'superset.app', an ImportError was raised:
superset_app           |
superset_app           | Traceback (most recent call last):
superset_app           |   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 218, in locate_app
superset_app           |     __import__(module_name)
superset_app           |   File "/app/superset/__init__.py", line 21, in <module>
superset_app           |     from superset.app import create_app
superset_app           |   File "/app/superset/app.py", line 24, in <module>
superset_app           |     from superset.initialization import SupersetAppInitializer
superset_app           |   File "/app/superset/initialization/__init__.py", line 31, in <module>
superset_app           |     from flask_session import Session
superset_app           | ModuleNotFoundError: No module named 'flask_session'
```

```
superset_worker        | Usage: celery [OPTIONS] COMMAND [ARGS]...
superset_worker        | Try 'celery --help' for help.
superset_worker        |
superset_worker        | Error: Invalid value for '-A' / '--app':
superset_worker        | Unable to load celery application.
superset_worker        | While trying to load the module superset.tasks.celery_app:app the following error occurred:
superset_worker        | Traceback (most recent call last):
superset_worker        |   File "/usr/local/lib/python3.9/site-packages/celery/bin/celery.py", line 53, in convert
superset_worker        |     return find_app(value)
superset_worker        |   File "/usr/local/lib/python3.9/site-packages/celery/app/utils.py", line 384, in find_app
superset_worker        |     sym = symbol_by_name(app, imp=imp)
superset_worker        |   File "/usr/local/lib/python3.9/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
superset_worker        |     module = imp(module_name, package=package, **kwargs)
superset_worker        |   File "/usr/local/lib/python3.9/site-packages/celery/utils/imports.py", line 100, in import_from_cwd
superset_worker        |     return imp(module, package=package)
superset_worker        |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
superset_worker        |     return _bootstrap._gcd_import(name[level:], package, level)
superset_worker        |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
superset_worker        |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
superset_worker        |   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
superset_worker        |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
superset_worker        |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
superset_worker        |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
superset_worker        |   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
superset_worker        |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
superset_worker        |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
superset_worker        |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
superset_worker        |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
superset_worker        |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
superset_worker        |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
superset_worker        |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
superset_worker        |   File "/app/superset/__init__.py", line 21, in <module>
superset_worker        |     from superset.app import create_app
superset_worker        |   File "/app/superset/app.py", line 24, in <module>
superset_worker        |     from superset.initialization import SupersetAppInitializer
superset_worker        |   File "/app/superset/initialization/__init__.py", line 31, in <module>
superset_worker        |     from flask_session import Session
superset_worker        | ModuleNotFoundError: No module named 'flask_session'
```

```
superset_worker_beat   | Usage: celery [OPTIONS] COMMAND [ARGS]...
superset_worker_beat   | Try 'celery --help' for help.
superset_worker_beat   |
superset_worker_beat   | Error: Invalid value for '-A' / '--app':
superset_worker_beat   | Unable to load celery application.
superset_worker_beat   | While trying to load the module superset.tasks.celery_app:app the following error occurred:
superset_worker_beat   | Traceback (most recent call last):
superset_worker_beat   |   File "/usr/local/lib/python3.9/site-packages/celery/bin/celery.py", line 53, in convert
superset_worker_beat   |     return find_app(value)
superset_worker_beat   |   File "/usr/local/lib/python3.9/site-packages/celery/app/utils.py", line 384, in find_app
superset_worker_beat   |     sym = symbol_by_name(app, imp=imp)
superset_worker_beat   |   File "/usr/local/lib/python3.9/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
superset_worker_beat   |     module = imp(module_name, package=package, **kwargs)
superset_worker_beat   |   File "/usr/local/lib/python3.9/site-packages/celery/utils/imports.py", line 100, in import_from_cwd
superset_worker_beat   |     return imp(module, package=package)
superset_worker_beat   |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
superset_worker_beat   |     return _bootstrap._gcd_import(name[level:], package, level)
superset_worker_beat   |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
superset_worker_beat   |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
superset_worker_beat   |   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
superset_worker_beat   |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
superset_worker_beat   |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
superset_worker_beat   |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
superset_worker_beat   |   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
superset_worker_beat   |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
superset_worker_beat   |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
superset_worker_beat   |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
superset_worker_beat   |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
superset_worker_beat   |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
superset_worker_beat   |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
superset_worker_beat   |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
superset_worker_beat   |   File "/app/superset/__init__.py", line 21, in <module>
superset_worker_beat   |     from superset.app import create_app
superset_worker_beat   |   File "/app/superset/app.py", line 24, in <module>
superset_worker_beat   |     from superset.initialization import SupersetAppInitializer
superset_worker_beat   |   File "/app/superset/initialization/__init__.py", line 31, in <module>
superset_worker_beat   |     from flask_session import Session
superset_worker_beat   | ModuleNotFoundError: No module named 'flask_session'
```

Manually installing `flask_session` via pip3 did not change anything (and should also not be required based on the official documentation).
