### ISSUE TITLE
How to add Filter selected value in Chart heading in superset dashboard

### ISSUE THREAD

**Issue by Priya359** [apache/superset#26089]
## Screenshot

Is it possible to add filter selected value in chart heading in superset dashboard ?
e.g : If there is month filter and i have selected August month, so can i show august value in chart heading or description in any way ?

**Comment by sfirke** [comment]
No, unfortunately this is not currently possible. People often ask about it, though, so I would encourage you to search GitHub discussions and issues to see if a feature request for it exists. If not, you could create a GitHub discussion for the feature request.

**Comment by debggr** [comment]
I found a hacky way to get it. Not perfect though.

Basically create a dataset that returns the filter value.

Dataset query:

`{% if filter_values('filter_col_name') %}
  SELECT {{ filter_values('filter_col_name')|where_in }} as filter_value
{% else %}
  SELECT 'Filter Not Selected' as filter_value
{% endif %}`

Then create a "WordCloud" chart with dimension `filter_value` as metric set to 0.
