### ISSUE TITLE
Gauge Chart value doesn't update when jinja template filters are set

### ISSUE THREAD

**Issue by Anphisa** [apache/superset#26086]
I have a gauge chart in my dashboard that displays one metric. I apply filters with Jinja templating to the base table. The gauge chart metric doesn't change, not even after a full refresh.

#### How to reproduce the bug

1. Add a filter with jinja templating in a dataset, pseudocode similar to my scenario:
```
SELECT
  a.something
FROM table_A a
INNER JOIN table_B b
ON table_A.id = table_B.id
WHERE 1 = 1
{% if filter_values('val')|length %}
  AND b.val IN {{ filter_values('val')|where_in }};
{% endif %}
```
2. Add a metric in dataset, e.g. COUNT(DISTINCT(something))
4. Add a gauge chart displaying the metric
5. Put it on a dashboard
6. Change filter values
7. See that gauge chart value doesn't update.

### Expected results

Changed metric in gauge chart.

### Actual results

Metric in gauge chart stays as if no filter was applied.

#### Screenshots

No filters set, gauge chart and big number chart with unfiltered metric value:
![image](https://github.com/apache/superset/assets/15688223/9b1630d5-2e05-4a54-8c3b-11eac86656c2)
Filter is set (greyed/whited out, but visible that a filter value was set), big number chart updates, gauge chart doesn't:
![image](https://github.com/apache/superset/assets/15688223/01a5be69-920b-45fc-a7f2-02bc2f973396)

### Environment

(please complete the following information):

- browser type and version: Chrome 
- superset version: `3.0.1`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing this as stale, but it's likely stale because it's hard to reproduce. Can you give us a reproducible test case using example charts/data so not as much has to be redacted? If we can make that happen, and the bug is still present in 3.1/4.0, we can revisit/reopen. Thanks!
