### ISSUE TITLE
The request to sign in was denied.

### ISSUE THREAD

**Issue by antonio-tg** [apache/superset#26095]
I'm working with Apache Superset in an Openshift cluster and authentication with Azure Active Directory, all looks good, but I can't autenticate and I don't know why.

#### How to reproduce the bug

Apache Superset 2.1.1
OCP: 4.12.25
Kubernetes: v1.25.11

### Expected results

Enter the application, in fact with an old version of Apache Superset it works without problem.

### Actual results

I can't enter to the application

#### Screenshots

![](https://github.com/apache/superset/assets/67483811/91360578-c982-4f9b-968a-ffc3fbd75e29)

### Environment

- browser type and version: Google Chrome 119.0.6045.159 
- superset version: 2.1.1
- python version: 3.8.18

### Checklist

The logs show
```logs
10.15.9.149 - - [24/Nov/2023:22:20:08 +0000] "GET /static/appbuilder/js/ab.js HTTP/1.1" 200 896 "https://supersetuat.***************/login/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
[2023-11-24 22:20:08 +0000] [185] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 326, in handle_request
    resp.write_file(respiter)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 385, in write_file
    if not self.sendfile(respiter):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 375, in sendfile
    self.sock.sendfile(respiter.filelike, count=nbytes)
  File "/usr/local/lib/python3.8/socket.py", line 482, in sendfile
    return self._sendfile_use_sendfile(file, offset, count)
  File "/usr/local/lib/python3.8/socket.py", line 346, in _sendfile_use_sendfile
    self._check_sendfile_params(file, offset, count)
  File "/usr/local/lib/python3.8/socket.py", line 460, in _check_sendfile_params
    raise ValueError(
ValueError: count must be a positive integer (got 0)
10.15.9.151 - - [24/Nov/2023:22:20:08 +0000] "GET /static/assets/8047.303867f305db6e4fcadc.entry.js HTTP/1.1" 200 17811 "https://supersetuat.*************/login/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
```

My  configuration in the values file is:
```yml
    OAUTH_PROVIDERS = [
        {
            "name": "azure",
            "icon": "fa-windows",
            "token_key": "access_token",
            "remote_app": {
                "client_id": "***********************************",
                "client_secret": "***********************************",
                "api_base_url": "https://graph.microsoft.com/v1.0/",
                "client_kwargs": {"scope": "User.read openid", "resource": "***********************************"},
                "request_token_url": None,
                "access_token_url": "https://login.microsoftonline.com/***********************************/oauth2/token",
                "authorize_url": "https://login.microsoftonline.com/***********************************/oauth2/authorize" #,
                #"authorize_params": {"hd": os.getenv("OAUTH_HOME_DOMAIN", "")}
            }
        }
    ]
```
### Additional context

Nothing else to say.

**Comment by sfirke** [comment]
I have not seen anyone use `https://graph.microsoft.com` when setting up SSO with Azure.  My config has lines like this instead of what you have ([from the FAB docs](https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-oauth)):

```
            "api_base_url": "https://login.microsoftonline.com/AZURE_TENANT_ID/oauth2",
            "client_kwargs": {
                "scope": "User.read name preferred_username email profile upn",
```

**Comment by antonio-tg** [comment]
Thank you very much, that was the problem.

**Comment by dhruv-bardolia** [comment]
Hi I am also facing the same issue. 
I am trying authentik in place of Azure for SSO. Following is my configuration:
`
      FEATURE_FLAGS = {"DYNAMIC_PLUGINS": True}
      import os
      os.system('pip install packaging==21.3 psycopg2-binary grpcio authlib pillow')

      from flask_appbuilder.security.manager import AUTH_OAUTH
      AUTH_TYPE = AUTH_OAUTH
      ENABLE_PROXY_FIX = True
      SESSION_COOKIE_SAMESITE = "None"
      SESSION_COOKIE_SECURE = True
      OAUTH_PROVIDERS = [
        {
          "name": "authentik",
          "icon": "fa-authentik",
          "token_key": "access_token",
          "remote_app": {
            "client_id": "----",
            "client_secret": "------",
            "api_base_url": "https://----/application/o/",
            "client_kwargs": {"scope": "User.read openid email profile"},
            "request_token_url": None,
            "access_token_url": "https://-------/application/o/token/",
            "authorize_url": "https://----/application/o/authorize/",
            "authorize_params": {
              "redirect_uri" : "https://----/oauth-authorized/authentik"
            }
          }
        }
      ]

      AUTH_USER_REGISTRATION = True
      AUTH_USER_REGISTRATION_ROLE = "Admin"
      AUTH_ROLES_SYNC_AT_LOGIN = True

      # Map OAuth groups to Superset roles if needed
      AUTH_ROLES_MAPPING = {
          "superset": ["Admin"],
          # Add more mappings as needed
      }
      
`
--- denots my DNS for example xyz.xyz.com
![Image](https://github.com/user-attachments/assets/98bd967a-f182-49a1-a8ca-da2ecebd94d4)

**Comment by sfirke** [comment]
@dhruv-bardolia I don't think this is the same issue at all - the original post was about Azure, I pointed out a problem in the Azure config, and that was confirmed to be the problem. So reopening this is not appropriate.

That said, I understand you have a problem. I would suggest asking in GitHub Discussions or the Superset community Slack, since this sounds like a question about how to configure Superset, not a bug report where you have found a problem in the Superset software. You might also ask around the Authentik community and see if they have thoughts.
