### ISSUE TITLE
Unable to load an iframe within Text Element Layout

### ISSUE THREAD

**Issue by gmarendaz** [apache/superset#26102]
I created a Dashboard in which I want to load an iframe to show some informations to the user.

#### How to reproduce the bug

1. Create a new dashboard
2. Use Text in Layout Elements
3. Load iframe in Markdown formatting
4. iframe does not load when saving the dashboard

### Expected results

I want the iframe to be loaded.

### Actual results

The iframe does not load.

### Environment

- browser type and version: Microsoft Edge Version 119.0.2151.72
- superset version: 2.1.0
- python version: 3.11.4
- any feature flags active:
```
FEATURE_FLAGS = {
    "ALERT_REPORTS": True,
    "DASHBOARD_CROSS_FILTERS": True,
    "DASHBOARD_FILTERS_EXPERIMENTAL": True,
    "DASHBOARD_NATIVE_FILTERS": True,
    "DASHBOARD_NATIVE_FILTERS_SET": True,
    "DASHBOARD_RBAC": True,
    "DASHBOARD_RBAC": True,
    "DYNAMIC_PLUGINS": True,
    "EMBEDDABLE_CHARTS": True,
    "EMBEDDED_SUPERSET": True,
    "ENABLE_TEMPLATE_PROCESSING": True
}
```

### Checklist

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

- I created a simple HTML file to call the iframe and it works.

**Comment by gmarendaz** [comment]
This issue can be closed, I finally changed our method to call iframe.
We created a full Dash environment for the Web App.

**Comment by joshuaclausen** [comment]
@gmarendaz Did you get an iframe to load external content into a Superset dashboard?

**Comment by joshuaclausen** [comment]
I got it working.  In my case I wanted to embed PowerBI workbooks that had been published to the web for public consumption.

You need to override the following vars in the superst_config_docker.py file:

```
HTML_SANITIZATION_SCHEMA_EXTENSIONS

TALISMAN_CONFIG
```


Here is what I needed to add to superst_config_docker.py (if you're running in docker):

```
If you wanted to allow iframes in Superset dashboard Text Elements with content coming from PowerBI, add the following to superset_config_docker.py (if you are running in docker):
# allow adding <iframe> tags to the text element in dashboards
# https://github.com/apache/superset/discussions/27064
# note you also have to add the desired remote load locations to the Content Security Policy in the TALISMAN_CONFIG var
HTML_SANITIZATION_SCHEMA_EXTENSIONS = {
  "attributes": {
    "*": ["style","className"],
    "iframe": ["src"]
  },
  "tagNames": ["style","iframe"],
}


# allow loading content in iframes from powerbi (workbooks that have been published to the web)
# this is the content security policy that allows content to be loaded from app.powerbi.com
TALISMAN_CONFIG = {
    "content_security_policy": {
        "src": [
            "'self'",
            "https://app.powerbi.com",
        ],
    }
}
```
