### ISSUE TITLE
"Enter Full Screen" option is not working in Embedded Dashboard, it hangup in loading state

### ISSUE THREAD

**Issue by chandrasekharjandhyam** [apache/superset#26103]
we are able to embed a dashboard in source application successfully.  when the dashboard is embedded, we click on "Enter Full Screen" from the dashboard header controls. it goes to loading state indefinitly. it hangs there. dashboard will not be loaded. 

**the error from the browser console is**
redux.js:426 Unexpected key "embedded" found in preloadedState argument passed to createStore. Expected to find one of the known reducer keys instead: "queryApi", "sqlLab", "localStorageUsageInKilobytes", "messageToasts", "common", "user", "impressionId", "charts", "datasources", "dashboardInfo", "dashboardFilters", "dataMask", "nativeFilters", "dashboardState", "dashboardLayout", "sliceEntities", "reports", "saveModal", "explore". Unexpected keys will be ignored.

Ideally, this option is not applicable for dashboard in embedded view in my opinion. since dashboard is embedded into iframe and it opens in full screen mode always. 
we **should hide** this option from embedded dashboard. 

#### How to reproduce the bug

1. Enable "Embedded Configuration" for dashboard. 
2. embed the dashboard in the source application.
3. click on the header menu dropdown.
4. click on "Enter Full Screen" option.
![image](https://github.com/apache/superset/assets/95915160/d3765b88-cbfb-413b-8788-24c4a06b9202)

### Expected results
dashboard is already in full screen mode, this option should be hidden, or dashboard need to refresh without any issues.

### Actual results
![image](https://github.com/apache/superset/assets/95915160/6df49798-7625-4e2e-b6da-f0d0e7f0f423)
it will be in loaded state only.

### Environment

(please complete the following information):

- browser type and version: Chrome 119.0.6045.160 
- superset version: `superset version` 3.0.0, 3.0.1, 3.0.2
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by michael-s-molina** [comment]
This was disable by https://github.com/apache/superset/pull/26412 which is available in more recent versions of Superset.

**Comment by sandeepr43** [comment]
I'm using superset version 3.1.0 and I'm still getting full screen error as detailed in below discussion:

https://github.com/apache/superset/discussions/27530

Any setting change/ workaround that I must do?

**Comment by michael-s-molina** [comment]
> Any setting change/ workaround that I must do?

Hi @sandeepr43. You need to upgrade to 3.1.1 as the fix was [included in that release](https://github.com/apache/superset/blob/master/CHANGELOG/3.1.1.md). You can always check the [CHANGELOG](https://github.com/apache/superset/blob/master/CHANGELOG) to see in which version a fix is applied.
