### ISSUE TITLE
Just a "click next" or "easy" simple Windows Installer

### ISSUE THREAD

**Issue by simonaubertbd** [apache/superset#26113]
*Please make sure you are familiar with the SIP process documented*
[here](https://github.com/apache/superset/issues/5602). The SIP will be numbered by a committer upon acceptance.

### Motivation

As of today, the installation process for Superset on Windows is really complicated. For reference, the documentation : https://superset.apache.org/docs/intro
`Install Superset [from scratch](https://superset.apache.org/docs/installation/installing-superset-from-scratch/)
    Deploy Superset locally with one command [using Docker Compose](https://superset.apache.org/docs/installation/installing-superset-using-docker-compose)
    Deploy Superset [with Kubernetes](https://superset.apache.org/docs/installation/running-on-kubernetes)
    Run a [Docker image](https://hub.docker.com/r/apache/superset) from Dockerhub
    Download Superset [from Pypi here](https://pypi.org/project/apache-superset/)
    Install the latest version of Superset [from GitHub](https://github.com/apache/superset/tree/latest)
    Download the [source from Apache Foundation's website](https://dist.apache.org/repos/dist/release/superset/)`
    
This is not exactly what I would call "user-friendly" and requires some skills, meaning a huge time spent before installing and using the product on Windows. I would like to reduce this time dramatically to approach what market dataviz solutions offer. Indeed : this doesn't only mean more time and money spent on installation, it also means that many potential users won't even try, either because they don't have the skills either because they can't spend hours on that while other solutions can be deployed in minutes !

### Proposed Change

A dedicated installer, just like most of software on Windows.

### New or Changed Public Interfaces
Only the installer has to change.

### New dependencies
N/A

### Migration Plan and Compatibility
N/A

### Rejected Alternatives
Cf my introduction : the other ways to install Superset on Windows are way too time-consuming.

**Comment by rusackas** [comment]
Superset is not a Windows application, and Windows is not officially supported. If anyone wishes to open any PRs (code and/or documentation) to make the installation process more viable/successful, then we can begin to call it officially supported over time. Similarly, if people wish to contribute Windows (or Mac, or any other OS) installers, we would be open to a proposal about that specifically, i.e. how it would work, how it would be tested/maintained, how it fits into release cycles, etc. As it stands I'm not aware of this being on anyone's roadmap, but if you're interested in contributing, I'd encourage you to open up a Github Discussion on the topic, open a SIP with a more detailed proposal, or put it on the agenda at a Town Hall sync.
