### ISSUE TITLE
Edit Chart Access to Non Admin / Non Owner role User

### ISSUE THREAD

**Issue by maheshkumarkr** [apache/superset#26127]
Hello Team,

Need to know if there is a way for us to provide "Edit Chart" access to Non Admin / Non Owner role user in Superset.

#### How to reproduce the bug

1. Go to 'Dashboard -> Chart -> Edit Chart'

### Expected results
User with appropriate role / access to the dataset/dashboard, should be able to Edit Chart

### Actual results
User is not able to Edit chart.

### Environment

- browser type and version: Chrome
- superset version: `2.1.0`
- python version: `3.8`

**Comment by michael-s-molina** [comment]
Yes. You can use assign the required permissions using the Roles module.
