### ISSUE TITLE
BigInt is throwing error when used as temporal column

### ISSUE THREAD

**Issue by michael-s-molina** [apache/superset#26133]
#### How to reproduce the bug
An error is thrown if a `bigint` is used as temporal column which is the case for some example charts.

Error when opening the Video Games Sales dashboard:

<img width="1776" alt="Screenshot 2023-11-29 at 11 05 37" src="https://github.com/apache/superset/assets/70410625/d2ce2fd0-5e6f-414d-adab-ac59ef30a346">

Error thrown when using `year`, which is a `bigint`, as a temporal column on SQLite:

<img width="1756" alt="Screenshot 2023-11-29 at 10 55 10" src="https://github.com/apache/superset/assets/70410625/927b46b5-da32-4032-8d65-d751dca24268">

Error thrown when using `year`, which is a `bigint`, as a temporal column on Postgres:

<img width="1762" alt="Screenshot 2023-11-29 at 10 56 52" src="https://github.com/apache/superset/assets/70410625/8508b0fc-b226-436b-a504-1b0b34724c7e">

### Environment

- superset version: `master`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by michael-s-molina** [comment]
@villebro @zhaoyongjie @betodealmeida What's your opinion about this issue? Should we try to convert possible column types (`string`, `bigint`, `numeric`, etc) to a `timestamp` or do you think the error is valid because that type (`bigint`) cannot be used as a time column and in that case we should fix the examples?

**Comment by villebro** [comment]
@michael-s-molina IMO the video games sample dataset is incorrectly defined, and is the real cause of this issue. In other words, I think the error is valid. I think fixing it should be fairly straight forward, let's rather do that.
