### ISSUE TITLE
Bar chart with numeric x-axis always starts x-axis at zero regardless of data

### ISSUE THREAD

**Issue by sfirke** [apache/superset#26139]
Trying out 3.1.0rc1 I noticed that one of my bar charts looked wrong.

In version 3.0.0:

![image](https://github.com/apache/superset/assets/7569808/d1e15685-be86-4431-b93c-aaf4ea950ba1)

In version 3.1.0rc1:
![image](https://github.com/apache/superset/assets/7569808/0bdd7640-e585-4213-b060-058b8aa14366)

I tried making a new chart with another dataset where I have year as a numeric and I experienced the same thing, though the x-axis terminated around 2500 instead of 7000 in the screenshot above.

### Environment
GENERIC_CHART_AXES is enabled

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by michael-s-molina** [comment]
@villebro do you think this is related to https://github.com/apache/superset/pull/26087?

**Comment by villebro** [comment]
@michael-s-molina this is indeed likely related to that PR. Let me take a look at what could be causing this - thanks @sfirke for creating the repro case, very helpful!
