### ISSUE TITLE
Custom Viz Plugin throwing error after executing yo @superset-ui/superset

### ISSUE THREAD

**Issue by vivek-cloudloom** [apache/superset#26135]
Trying to create a custom Viz Plugin, followed the steps mentioned in this link.
https://superset.apache.org/docs/contributing/creating-viz-plugins/

When executing the script yo @superset-ui/superset , it throws error saying **Error @superset-ui/superset.Cannot find module './utils.js'**

#### How to reproduce the bug

> 
> npm i -g yo
> cd superset-frontend/packages/generator-superset
> npm i
> npm link
> 
> mkdir /tmp/superset-plugin-chart-hello-world
> cd /tmp/superset-plugin-chart-hello-world
> 
> yo @superset-ui/superset
> 
### Expected results

Expected a prompt to input package name and description

### Actual results

```
macbookpro@MACBOOKs-MacBook-Pro superset-plugin-chart-hello-world % yo @superset-ui/superset
Error @superset-ui/superset 

Cannot find module './utils.js'
Require stack:
- /Users/macbookpro/Documents/blinklink/superset/superset/superset-frontend/node_modules/node-fetch/node_modules/whatwg-url/lib/URL.js
- /Users/macbookpro/Documents/blinklink/superset/superset/superset-frontend/node_modules/node-fetch/node_modules/whatwg-url/lib/public-api.js
- /Users/macbookpro/Documents/blinklink/superset/superset/superset-frontend/node_modules/node-fetch/lib/index.js
- /Users/macbookpro/Documents/blinklink/superset/superset/superset-frontend/node_modules/@octokit/request/dist-node/index.js
- /Users/macbookpro/Documents/blinklink/superset/superset/superset-frontend/node_modules/@octokit/core/dist-node/index.js
- /Users/macbookpro/Documents/blinklink/superset/superset/superset-frontend/node_modules/@octokit/rest/dist-node/index.js
- /Users/macbookpro/Documents/blinklink/superset/superset/superset-frontend/node_modules/github-username/index.js
- /Users/macbookpro/Documents/blinklink/superset/superset/superset-frontend/node_modules/yeoman-generator/lib/actions/user.js
- /Users/macbookpro/Documents/blinklink/superset/superset/superset-frontend/node_modules/yeoman-generator/lib/index.js
- /Users/macbookpro/Documents/blinklink/superset/superset/superset-frontend/packages/generator-superset/generators/app/index.js
```
#### Screenshots
<img width="1034" alt="Screenshot 2023-11-29 at 10 13 40 PM" src="https://github.com/apache/superset/assets/88186667/e53c5bec-be59-4e36-84b9-81226a3de4a8">

### Environment

(please complete the following information):

- node.js version: `v16.20.2`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by gaogaoinvincible** [comment]
Change to yo@4.x

**Comment by michael-s-molina** [comment]
Closing the issue assuming the upgrade fixed the issue. Please reopen if that's not the case.
