### ISSUE TITLE
Alembic revision 317970b4400c missing when upgrading from 3.0 to 3.1.0rc1

### ISSUE THREAD

**Issue by john-bodley** [apache/superset#26163]
The Alembic revision `317970b4400c` is missing when  upgrading from 3.0 to 3.1.0rc1.  

#### How to reproduce the bug

1. Go to http://localhost:5000/chart/list/
2. See the following error

```
An error occurred while fetching charts: (sqlite3.OperationalError) no such column: tables.always_filter_main_dttm
[...]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

### Expected results

The Alembic revisions (which exists in `master`) should have also been present in 3.0 given it's denoted as a direct precursor to `4b85906e5b91`.

### Actual results

A SQLAlchemy error is thrown indicating that the table schema was never updated to include the `tables.always_filter_main_dttm` column.

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: 3.1.0rc1
- python version: 3.9
- node.js version: v16.10.0
- any feature flags active: N/A

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sfirke** [comment]
Closed by #26160
