### ISSUE TITLE
SQL not execute in new superset version (2.1.0 -> 3.0.1)

### ISSUE THREAD

**Issue by VictorDMe** [apache/superset#26213]
I have an SQL query that ran successfully in the previous version (2.1.0), but in the new version (3.0.1), it returns an error. I have two environments, and the same SQL runs smoothly in the production environment with version 2.1.0.

The SQL does not run ONLY IN SQL LAB but also generates graphs using it.

#### Error
![image](https://github.com/apache/superset/assets/67445953/2e8dc875-bd85-4217-b8ab-6b6716d17fd6)
*Sorry the bad quality*

**Comment by rusackas** [comment]
We no longer support 2.x or 3.0. If you run into this in 3.1 or 4.0 and can give us a reproducible test case, we're happy to reopen this. Thanks!
