### ISSUE TITLE
Apache Superset fails to run on Apple M2 (Docker )

### ISSUE THREAD

**Issue by soumilshah1995** [apache/superset#26231]
followed steps 

```
git clone https://github.com/apache/superset.git
export DOCKER_DEFAULT_PLATFORM=linux/amd64
docker-compose up --build 

```

<img width="935" alt="Screenshot 2023-12-10 at 6 00 15 PM" src="https://github.com/apache/superset/assets/39345855/ddb6107e-feff-4d9b-b50d-95a2adfbdb1f">

read few post 
https://github.com/apache/superset/issues/26170

tried 
```
$ docker-compose down && docker image prune -a
$ export DOCKER_DEFAULT_PLATFORM=linux/amd64
$ docker-compose -f docker-compose-non-dev.yml up

```

but again that also does not work

**Comment by ss-ravi** [comment]
hi @soumilshah1995!

How did you solve this problem? I'm having the same problem. tried it with the master branch and with the 3.0.2 tag, but both fails.

**Comment by ss-ravi** [comment]
Sharing what solved for me:

- Increasing the memory in the docker settings (to 20GB)
- Increasing the nodejs memory setting in the build command for the frontend pacakge 
    - `superset-frontend/package.json`
    - `NODE_OPTIONS=--max_old_space_size=16192`

**Comment by soumilshah1995** [comment]
Here is what I did 

```
$ docker-compose down && docker image prune -a
$ export DOCKER_DEFAULT_PLATFORM=linux/amd64
$ docker-compose -f docker-compose-non-dev.yml up



```
