### ISSUE TITLE
Bubble echart no longer loads

### ISSUE THREAD

**Issue by sadpandajoe** [apache/superset#26242]
#### How to reproduce the bug

1. spin up an ephemeral
2. select dashboard
3. select world bank data dashboard
4. select the bubble chart for life expectancy vs rural %
5. change the chart type to the bubble echart

### Expected results

Chart loads in explorer

### Actual results

There is an unexpected error: `An error occurred while rendering the visualization: TypeError: Cannot read properties of undefined (reading 'map')`

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
Thanks for reporting, I'll work on a fix asap
