### ISSUE TITLE
Bar chart with numeric x-axis fails to truncate upper bounds

### ISSUE THREAD

**Issue by sfirke** [apache/superset#26256]
In 3.1.0rc2 my bar chart is showing up like this:
![289988851-1c6c791b-daff-4651-834f-9a72ca3ee64a](https://github.com/apache/superset/assets/7569808/7bd673e1-a139-4904-992b-1ff153c3097c)

It should look like this (3.0.0):
![289989048-d1c5f31f-799e-4a44-a47d-6fd1b5b48364](https://github.com/apache/superset/assets/7569808/b0b6bcfa-5c0c-4326-9c0f-2b2e18975de2)

This issue is sort of a part 2 to #26139, where the issue persists for just the upper bound.  The fix was #26215 which stated:
> If the lower and/or upper bounds are left undefined, they will default to the min and max values from the dataset (calculated automatically by ECharts). This ensures that the data is bounded correctly.

It looks like the lower bounds part is performing okay here, but the upper bound part is not doing what is stated in the PR.

**Comment by michael-s-molina** [comment]
I opened an ECharts [issue](https://github.com/apache/echarts/issues/19397) as it seems to be a problem with the library.
