### ISSUE TITLE
Not work subscription to user_logged_out on session expiration

### ISSUE THREAD

**Issue by berlicon** [apache/superset#26266]
#### How to reproduce the bug
0. Login to Superset.
1. I wrote code with subcription to user logout (see https://flask-login.readthedocs.io/en/latest/#flask_login.user_logged_out ):
    @user_logged_out.connect
    def mark_logout(sender, user, **extra):
    print('LOGOUT')
2. I clicked on "Logout" button and saw the message "LOGOUT" on the cmd where my Superset was running.
3. User was unloginned.
4. I login to Superset again.
5. To force terminate session, I wrote: PERMANENT_SESSION_LIFETIME = 10 in \superset\config.py.
6. After 10 seconds, the Superset browser disconnected the user and redirected him to the login page.
7. I did not see the "LOGOUT" message on the cmd where my Superset was running - THIS IS AN ERROR.

### Environment
- browser type and version: Any - Crome
- superset version: 3.0.0
- python version: 3.10.0
- node.js version: 16.14.0
- Flask version: 2.2.5
- Werkzeug version: 2.3.3

**Comment by dpgaspar** [comment]
You seem to be using Flask signals to catch that event from flask-login. 
On Superset we don't use signals by default, but it should work if you carefully follow https://flask.palletsprojects.com/en/latest/signals/.
I don't consider this an error, please feel free to use our Slack channel for further help on implementing this.
