### ISSUE TITLE
Clicking 'Applied filters' tooltip causes unexpected tab switch

### ISSUE THREAD

**Issue by eram** [apache/superset#26262]
#### How to reproduce the bug

1. On a dashboard with multiple tabs, click open non-default tab
2. Set some filter
3. Click the "Applied filters" icon on the top right of a chart. This would open the tootip.
4. Click anywhere in the tooltip

### Expected results

Nothing other than text selection.

### Actual results

The display switches to show a different tab.

#### Screenshots

I have attached screenshotsand video.
![Screenshot 2023-11-27 at 14 43 12](https://github.com/apache/superset/assets/1045377/0541c053-7a27-4eea-b98e-ac1b282abb11)
![video](https://github.com/apache/superset/assets/1045377/74cf407a-2127-4c97-a347-0de73bf15e0d)

### Environment

(please complete the following information):

- browser type and version: chrome, firefox
- superset version: 3.0
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active: EMBEDDED, CROSS FILTERS

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

The attached screenshot and vid are from an embedded view, but the same issue is reproduced on the main superset dashboard.

**Comment by michael-s-molina** [comment]
@sadpandajoe @jinghua-qa

**Comment by michael-s-molina** [comment]
@kgabryje I think this [PR](https://github.com/apache/superset/pull/23190) is the source for the error.

**Comment by kgabryje** [comment]
Thanks for digging @michael-s-molina ! I’ll check it out

**Comment by kgabryje** [comment]
Thanks for reporting @eram, this PR should fix the issue https://github.com/apache/superset/pull/26340
