### ISSUE TITLE
cnpm i  error

### ISSUE THREAD

**Issue by seveneElevenup** [apache/superset#26274]
Install fail! Error: [dom-to-pdf@0.3.2 › dom-to-image@git+https://github.com/dmapper/dom-to-image.git] A git connection error occurred

**Comment by zhaoyongjie** [comment]
翻墙

**Comment by seveneElevenup** [comment]
> 翻墙

![截图](https://github.com/apache/superset/assets/50972125/33b5aaaf-90c1-47d3-9b2b-3c72ffd6fd68)
superset-frontend文件cnpm i成功后，启动项目报错了，截图如上。

**Comment by zhaoyongjie** [comment]
> > 翻墙
> 
> ![截图](https://private-user-images.githubusercontent.com/50972125/291238699-33b5aaaf-90c1-47d3-9b2b-3c72ffd6fd68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4OTU0MTksIm5iZiI6MTcwMjg5NTExOSwicGF0aCI6Ii81MDk3MjEyNS8yOTEyMzg2OTktMzNiNWFhYWYtOTBjMS00N2QzLTliMmItM2M3MmZmZDZmZDY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDEwMjUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1OWYxYjEzNzFlY2ZjZmI3MTg1MmFlYmYwZGQxOGM3ZDdiNzQ5ZDUwYTYxYWVlYTVlM2IzNTJlYjUyMWZkYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q9nUt4IX88QCj7M1UTXGrP6J8ZNa0kr49QJv5BK5mt4) superset-frontend文件cnpm i成功后，启动项目报错了，截图如上。

try to run following command to fix this issue.

```bash
cd superset-frontend
rm -rf node_modules && npm ci
``

**Comment by rusackas** [comment]
Based on the `C:\Users\...` directory, it seems you're using Windows, which is not officially supported by Superset. I'm guessing there are a fair number of packages that won't play well in this environment. I know a few people have managed to get it to work, but sadly they haven't provided any documentation/blogs/scripts/PRs to solidify things on this front. If you figure this out, please let us know what worked. If not, we might have to close this if it's strictly a Windows issue.
