### ISSUE TITLE
SQL Lab result set panel and timer disappears 

### ISSUE THREAD

**Issue by gaurav7261** [apache/superset#26276]
I have deployed 3.1.0 RC2, but facing weird issue in sqllab, timer is out of display after 10 sec, but when i refresh, it comes again,  tried in chrome, safari, also nothing in logs to debug.

### How to reproduce the bug

1. Go to sqllab
2. Click on run query

### Expected results

timer should be there until query run/failed

### Actual results

timer gone after 10 sec

#### Screenshots

https://github.com/apache/superset/assets/70410625/cb0cc012-f751-41c6-a851-58daa59d484c

### Environment

- browser type and version:
- superset version: `3.1.0-RC2`
- python version: `python --version 3.9`
- node.js version: `v10.19.0`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by michael-s-molina** [comment]
Hi @gaurav7261. Could you complete the template and add a description, screenshots/recording, expected, actual. The problem of linking Slack messages is that they might be deleted or forwarded to a different channel. Having the issue template complete also helps for historical purposes as people might come back to this issue later and understand what happened.

**Comment by michael-s-molina** [comment]
We also display a test environment for 3.1.0 RC2 [here](http://35.92.145.144:8080/). Are you able to reproduce your issue there?

**Comment by gaurav7261** [comment]
not able to find a query that run for more than 10 sec in test env

**Comment by gaurav7261** [comment]
template done

**Comment by michael-s-molina** [comment]
> template done

Did you forget to save? I'm still seeing the old template.

**Comment by gaurav7261** [comment]
yes, thanks

**Comment by michael-s-molina** [comment]
@justinpark could you check if you can reproduce this error?

**Comment by michael-s-molina** [comment]
I'm not sure if this might be related to this issue but I noticed you are using Node 10 but [Superset requires Node 16](https://github.com/apache/superset/blob/master/CONTRIBUTING.md#prerequisite) to run correctly.

**Comment by michael-s-molina** [comment]
@gaurav7261 We were able to reproduce your problem in our internal environment. @justinpark will take a look at the issue.

**Comment by sadpandajoe** [comment]
I also realized when we create a new query tab, the image placeholder is now gone from the results
![Screenshot 2023-12-15 at 9 05 21 AM](https://github.com/apache/superset/assets/47334392/2d589a88-0201-46f7-87f1-4d5f955a2cb6)
