### ISSUE TITLE
bug: Unicode character is not rendered as expected in alert and report feature!

### ISSUE THREAD

**Issue by okayhooni** [apache/superset#26309]
#### How to reproduce the bug
1. Create alert or report on the dashboard with Unicode text (like Korean)
2. Unicode character is not rendered as expected like below.

### Expected results
- Unicode characters are rendered as expected

#### Screenshots
![image](https://github.com/apache/superset/assets/81631424/a61c0890-e988-4a39-bd99-b77d753b402d)

### Environment
- superset `v2.1.3`
- Selenium with firefox driver (same as official `dev` image)
```
ARG GECKODRIVER_VERSION=v0.32.0
ARG FIREFOX_VERSION=106.0.3
``` 

### Checklist
- [v] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [v] I have reproduced the issue with at least the latest released version of superset.
- [v] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
- I installed `fonts-noto` on the image to fix this issue, but it cannot fix the issue.
```
apt-get install fonts-noto
```

**Comment by sfirke** [comment]
What is that screenshot of - the Alerts & Reports UI, the email of the report, ?

**Comment by okayhooni** [comment]
> What is that screenshot of - the Alerts & Reports UI, the email of the report, ?

@sfirke 

It's a screenshot image of dashboard(captured with Selenium) in the report sent to email(or slack)..!

I guess.. there is no valid fonts in the worker container image running Selenium drivers.

**Comment by sfirke** [comment]
Ah okay yep I bet you're right. I wonder if anyone in the community has a fix for this.

**Comment by okayhooni** [comment]
**self answer)**
I solved this issue with installing some additional fonts library on our custom superset image
```
fcitx-lib*
fcitx-hangul*
fonts-nanum*
fonts-noto
firefox-esr-l10n-ko
```

**Comment by kainchow** [comment]
I copied msyh.ttc from windows to the /usr/share/fonts/ directory inside the superset_worker container and it worked for me!
