### ISSUE TITLE
Error when viewing images on dashboards

### ISSUE THREAD

**Issue by omaucosta** [apache/superset#26322]
#### How to reproduce the bug

Import image into the dashboard, whether through HTML, Google Drive, or via Git.

### Expected results

Images loaded on the dashboard correctly.

### Actual results

Image not appearing on the dashboard.

#### Screenshots
 
 
Uploading the image.
<img width="1082" alt="image" src="https://github.com/apache/superset/assets/102234703/f2548141-5b75-43f5-b9e8-f08d888c5bf1">

 
 
 
 
Inspecting the browser page reveals the following error. The same error occurs when importing the image via Google Drive and other methods.
<img width="1039" alt="image" src="https://github.com/apache/superset/assets/102234703/c782e848-9ce8-4e8a-85b8-f7bc87a3f7a4">

### Environment

- browser type and version:  `Google Chrome: Version 120.0.6099.109 (Official Version) (arm64)`
- superset version: `v3.0.2`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

The Superset version 2.1.0 was being used, and the images were displaying. After updating to version 3.0.2, the issue occurred.

**Comment by michael-s-molina** [comment]
This is expected behavior. Please check the [Content Security Policy (CSP)](https://superset.apache.org/docs/security/#content-security-policy-csp) docs for how to resolve you issue.

**Comment by sfirke** [comment]
Other people who encounter this issue should try searching the Superset Slack chat, where it has been discussed how to address this through modifications to the CSP.
