### ISSUE TITLE
In 3.1.0rc3, color rendering of charts displayed in dashboard view is different than color rendering in chart view --regression from 2.1.0

### ISSUE THREAD

**Issue by ablanchard** [apache/superset#26321]
When displaying charts inside a dashboard the color scheme seems not to be resetted after each chart render. This cause the charts to look different whereas they should be harmonized. When we open the chart individually the bug is not present. 
In the steps to reproduce, I am focusing on 1 type of chart but it's something we have noticed on differents type of charts.

#### How to reproduce the bug

1. With superset 3.1.0rc3
2. Go to the `USA Births Names` dashboard from the examples
3. Scroll to the `10 girl name share`
4. Notice that there is no red or orange used. Also notice that the girl and the boy charts are using different colors but they should have the same colors used.
<img width="2050" alt="usa_names_dashboard_310rc3" src="https://github.com/apache/superset/assets/6951980/e05af3f3-e87f-407e-8d65-4417a2e357bd">
5. Go to the chart listing page
6. Search for `10 girl name share`
7. Open it
8. Notice that the chart is displayed with different colors that on the dashboard view including red and orange.
<img width="2050" alt="10_girl_chart_310rc3" src="https://github.com/apache/superset/assets/6951980/38db7bb2-6c78-4547-8a5c-3d2dbd0e33bf">

### Expected results

In version 2.1.0
The dashboard, both girl and boy charts are using the same color:
<img width="2050" alt="usa_names_dashboard_210" src="https://github.com/apache/superset/assets/6951980/4272483b-ad43-4334-8b3e-84426d988337">

The chart individually:
<img width="2050" alt="10_girl_chart_210" src="https://github.com/apache/superset/assets/6951980/14aa34e7-3572-40b0-a9b4-8c4337277c03">

### Actual results

In 3.1.0rc3
The dashboard, girl and boy charts are using different colors for rendering.
<img width="2050" alt="usa_names_dashboard_310rc3" src="https://github.com/apache/superset/assets/6951980/e05af3f3-e87f-407e-8d65-4417a2e357bd">

Whereas individually the chart is displayed the same as 2.1.0:
<img width="2050" alt="10_girl_chart_310rc3" src="https://github.com/apache/superset/assets/6951980/38db7bb2-6c78-4547-8a5c-3d2dbd0e33bf">

### Environment

(please complete the following information):

- browser type and version: firefox 120.0.1
- superset version: 3.1.0rc3 in docker
- python version: 3.9.18
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by michael-s-molina** [comment]
Hi @ablanchard. The same chart might be present in multiple dashboards and each dashboard have its own color scheme. Any time you access a chart individually, using the chart list, it won't match the color of any specific dashboard. If your dashboard have a Color Scheme defined, and you access the chart from the dashboard by clicking on Edit Chart, the chart will inherit the same color scheme defined by the dashboard.

https://github.com/apache/superset/assets/70410625/b7e30a73-8a4a-47ae-93d9-b3644dd1fdf7

**Comment by ablanchard** [comment]
Thanks @michael-s-molina, you are right this issue is not very related with the bug I'm seeing. I'll try to reproduce it more precisely and maybe create a new issue.
