### ISSUE TITLE
Deck.gl maps are not resized when a filter is applied

### ISSUE THREAD

**Issue by Stefan781** [apache/superset#26337]
When using Deck.gl's visualizations, such as the [path](https://superset.datatest.ch/superset/explore/?form_data_key=r_htGGnj4VlkM7Bki0kzsqUAeKOKF5vJfP3B9MdUDAyAcd4isgXYl-xozSw8KP3P&slice_id=70) one, if you have data points in different regions and use a filter to remove or add data that is outside of the current viewport, the map itself will not be resized, even though the displayed data has actually changed. This happens with auto zoom set to both true and false. However, if you refresh the page the viewport changes accordingly.

#### How to reproduce the bug

1. Create a Deck.gl Path visualization that has paths in two different locations that are substantially distanced.
2. Add a column that specifies where each path is located.
3. Add the visualization to a dashboard.
4. Add a filter to the dashboard that filters the column you have created in point 2.
5. Set a value to the filter so that one of the locations will be filtered out.
6. The data changes accordingly, but the map doesn't zoom-in.
7. Refresh the page. The map has zoomed in.

### Expected results

The map should have its viewport updated after each query that changes the displayed paths.

### Actual results

The viewport is updated only when the page is manually refreshed. Force refresh doesn't work either.

### Environment

Superset 3.0.2
Any browser

### Additional context

Having to manually refresh the page is not something that I would like to see in production. If that is an intended behavior, I would at least like to have an option in the dashboard to change it. I have checked other issues and didn't find a similar one.

**Comment by rusackas** [comment]
Closing in favor of https://github.com/apache/superset/issues/25018, but let me know if there's anything I'm missing here that warrants keeping this open separately.

**Comment by Stefan781** [comment]
I missed the other issue, thanks!
