### ISSUE TITLE
RLS Parameters not honored with caching enabled for embedded Dashboards

### ISSUE THREAD

**Issue by sauravhaloi** [apache/superset#26374]
We are using Superset dashboard embedding for some of our dashboards where dashboards are embedded into a web application for the users to consume. We are using RLS to enforce user's persona based security which we are achieving by passing the RLS parameters to Superset while creating a embed token. Additionally we have caching enabled for optimizing the dashboard load performance. 

We have observed that while refreshing the cache, Superset is not honoring the RLS parameters which is leading users from one persona to to view the data of another persona which is not intended and defeating the whole purpose of having the cache. 

#### How to reproduce the bug
1. Create a Dashboard
2. Enable dataset level cache
3. Enable dashboard embedding for the dashboard created in step (1)
4. Generate an embed token with some RLS parameters.
5. Embed the dashboard as an iFrame in another application and using the embed token from step (4)
6. The dashboard will load with RLS parameters properly applied. 
7. Manually refresh the cache from the dashboard / chart options of the embedded dashboard itself
8. The RLS parameters are not honored

### Expected results
The embedded dashboard should have loaded with RLS parameters properly applied with caching enabled.

### Actual results
The RLS filters were not honoured leading to users from different persona seeing each other's data

#### Screenshots

N/A

### Environment

(please complete the following information):

- browser type and version: Google Chrome - v120
- superset version: `2.0.0`
- python version: `3.8`
- node.js version: `v16`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

N/A

**Comment by sauravhaloi** [comment]
It seems the issue we encountered is more related to https://github.com/apache/superset/issues/24745. Has this been fixed in newer versions of Superset?

**Comment by michael-s-molina** [comment]
@villebro @eschutho

**Comment by villebro** [comment]
@sauravhaloi can you reproduce this on a more recent version of Superset?

**Comment by rusackas** [comment]
Based on the above comment, I'll close this as fixed. If anyone sees this happening with 3.x, say the word and we'll re-open.

**Comment by jaden-jin** [comment]
with superset 4.0.1, this issue reproduced. check please.
