### ISSUE TITLE
Cannot import/export Charts, Databases, Datasets, and Dashboards with VERSIONED_EXPORT=False

### ISSUE THREAD

**Issue by CollinEMac** [apache/superset#26417]
Due to [this change](https://github.com/apache/superset/pull/20368/files), imports/exports are hidden from the user when `VERSIONED_EXPORT` is set to `False`. My team requires the ability to allow users to do a non-versioned export and import.

There have been a few questions about this issue before but it doesn't look like there is currently an open issue:

1. https://github.com/apache/superset/pull/20368#issuecomment-1185671671
2. https://github.com/apache/superset/issues/21001#issuecomment-1523029905

#### How to reproduce the bug

1. Set `VERSIONED_EXPORT` to `False` in your config. (it's `True` by default)
2. Go to import or export a Charts, Databases, Datasets, or Dashboards.
3. The import/export button isn't where it normally would be.

### Expected results

I'd expect to be able to import and export as a `JSON` file when `VERSIONED_EXPORT` is turned off.

### Actual results

The import/export button doesn't display.

##### What I'd expect to see (export)
![Screenshot 2024-01-05 at 4 09 13 PM](https://github.com/apache/superset/assets/26743613/bb441071-a198-4977-92dc-a77eeba1508c)

##### What I actually see (export)
![Screenshot 2024-01-05 at 4 09 20 PM](https://github.com/apache/superset/assets/26743613/eb5d8379-ad9d-4b12-8ba7-453d1ab12396)

##### What I'd expect to see (import)
<img width="1271" alt="Screenshot 2024-01-05 at 4 08 47 PM" src="https://github.com/apache/superset/assets/26743613/446ffa07-3079-4ab6-a001-c3a9bffb9e53">

##### What I actually see (import)
<img width="1271" alt="Screenshot 2024-01-05 at 4 08 55 PM" src="https://github.com/apache/superset/assets/26743613/09ca3845-9c57-416c-87f1-31e3c687802c">

### Environment

- browser type and version: Any
- superset version: `2.1.0` (Issue is present in latest - 3.1.0 as well)
- python version: `3.8` (Issue doesn't depend on python version though)
- node.js version: `20` (Issue doesn't depend on node version though)
- any feature flags active: VERSIONED_EXPORT

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Worth noting that prior to Superset version 2.0, exporting and importing was available when versioned or non-versioned.

**Comment by michael-s-molina** [comment]
Hi @CollinEMac. When `VERSIONED_EXPORT` is set to False, you can import dashboards using the legacy feature which is available in the Settings menu.

<img width="247" alt="Screenshot 2024-01-08 at 08 19 31" src="https://github.com/apache/superset/assets/70410625/4ff79f7a-1690-4770-b074-00da5d6d923a">

**Comment by vergenzt** [comment]
@michael-s-molina how do you *export* dashboards using the legacy feature?

**Comment by michael-s-molina** [comment]
> @michael-s-molina how do you export dashboards using the legacy feature? That's an important part of the functionality we're missing.

I'm not sure if it's possible. Let me ping some folks with more context about this feature @eschutho @betodealmeida @hughhhh

**Comment by eschutho** [comment]
HI @CollinEMac and @vergenzt can I ask what the bugs are that you're finding with the new import/export feature? Since we're actively supporting that version, it will be easier for us to address any issues with that feature moving forward rather than supporting the old version. I saw that one of the bug tickets mentioned missing an export button with the flag turned on. You'll want to also give permissions for `can_export` to see the export button. Is that the main issue?

**Comment by CollinEMac** [comment]
Hi @eschutho,

Yes, our primary concern is that the export button is hidden for dashboards. We've verified that `can_export` is `True`. However, it's required that the `VERSIONED_EXPORT` feature flag is also set to `True` (link to related code below). I'm not sure why versioned export would be required to export a dashboard. This feels like unexpected behavior to me.

https://github.com/apache/superset/blob/2.1.0/superset-frontend/src/views/CRUD/dashboard/DashboardList.tsx#L166

**Comment by eschutho** [comment]
@CollinEMac The `VERSIONED_EXPORT` flag is essentially the v2 functionality for import/export which is more robust, and also why we're deprecating the original version. Is there any functionality in the old version that you don't have in the new one? Or another reason why you're unable to use the latest feature? The new version (`VERSIONED_EXPORT`) has import/export for charts, dashboards, datasets, databases and queries and is backward compatible when importing with the older json exports.

**Comment by eschutho** [comment]
If you set `VERSIONED_EXPORT` to true, do you see the export button?

**Comment by CollinEMac** [comment]
Yes, we can see the export button with `VERSIONED_EXPORT` turned on.

**Comment by michael-s-molina** [comment]
Closing this issue assuming that the export button is visible with VERSIONED_EXPORT turned on and that

>  Since we're actively supporting that version, it will be easier for us to address any issues with that feature moving forward rather than supporting the old version.

Please feel free to reopen it if necessary.
