### ISSUE TITLE
[Bug] While applying filter in a chart, there is a bug in it

### ISSUE THREAD

**Issue by sivasathyaseeelan** [apache/superset#26421]
#### How to reproduce the bug

1. Go to edit mode in 'Map of Vaccine Candidates' in COVID Vaccine Dashboard. 
2. Add a filter with column as `country_name` and operator as `In`
3. Now try to add filter value with suggestions, and you can able to see the Bug which I have attached as video in this issue.

### Expected results
When typing filter value and selecting with suggestion, filter value should be selected and the state of filter value should be set to empty string. 

### Actual results
When typing filter value and selecting with suggestion, filter value is selected and the state of filter value doesn't change. 

[![Before Changes]](https://github.com/apache/superset/assets/95441117/e08ae876-7642-44df-ab70-5f1dc50b4b92)

### Environment

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by michael-s-molina** [comment]
Hi @sivasathyaseeelan. Preserving your search input after a selection is an intentional behavior as many times people will search for prefixes and select multiple items. This behavior is only applicable to multiple selects.
