### ISSUE TITLE
Same color is assigned to 2 different consecutive dimension values

### ISSUE THREAD

**Issue by saramoujahid** [apache/superset#26437]
The same color is assigned to 2 different consecutive dimension values, even though the color scheme has other available colors
This happened while creating a stacked bar chart

### Expected results

Colors should alternate across these available ones:
<img width="297" alt="image" src="https://github.com/apache/superset/assets/125974943/891d497b-0e42-4f10-be44-81a17b807041">

### Actual results

For the 3rd and 4th values, they are assigned the same orange color
<img width="410" alt="image" src="https://github.com/apache/superset/assets/125974943/a0f19b7f-fa65-459a-bd02-75ae7c723963">

### Environment

(please complete the following information):

- browser type and version: Chrome Version 120.0.6099.199 
- superset version: 2.1.1
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by michael-s-molina** [comment]
Hi @saramoujahid. I believe this is fixed in 3.0.3 and 3.1.0 which are the [officially supported versions](https://github.com/apache/superset/wiki/Release-Process#schedule). You just need to upgrade your installation to fix the problem.

**Comment by skannan-maf** [comment]
I am in 3.1.0 and I am seeing Superset selecting same color for 2 different lines in a line chart. Any idea how to workaround this?

**Comment by rusackas** [comment]
@skannan-maf we're currently supporting 4.x versions, so if you are seeing the issue after an upgrade, let us know with screenshots/repro steps either here or (preferably) on a new/clean Issue report.

**Comment by skannan-maf** [comment]
Overall, as an end user, I need a way to specify a color of my choice for a series in my chart..... 
|f unspecified, it can use the theme......
This is my expectation as an end user....
(or)
While using the scheme, Superset by default should pick colors so that various charts in the dashboard have consistent color choices based on the name of the series.....

**Comment by azsun1** [comment]
I see that this was falsely claimed to have been fixed in 3.1.0. I am on version 4.0.1 and am still experiencing this issue.

**Comment by f-teyssier** [comment]
@michael-s-molina  The problem is still on with V4.1.4 : could you reopen this issue please ?

<img width="907" height="44" alt="Image" src="https://github.com/user-attachments/assets/eb75b710-2c1f-4e65-b768-253284de5473" />
