### ISSUE TITLE
Custom superset loading gif

### ISSUE THREAD

**Issue by devteam-tb** [apache/superset#26458]
## Description

I want to change the loading gif image. how i can do it ?
 if we replaced the loading.gif  and loading.cff8a5da..gif then it will show but didn't hide that superset loading icon.

**Comment by goncaloacteixeira** [comment]
Hey @devteam-tb , did you happen to come to a solution on this issue?

**Comment by rusackas** [comment]
You can fork the code and change the GIF source — that's the easy way, but probably a bit short-sighted.  You could also open a PR that makes it configurable so _everyone_ wins (kind of like the configurable branding/logo), and can change the path to a GIF of their choice from any host (assuming you allow that URL in your CSP). I, for one, would be happy to review that PR :)
