### ISSUE TITLE
[dashboard][color theme] chart color are changed when refreshing dashboard

### ISSUE THREAD

**Issue by manikarora02** [apache/superset#26456]
chart color is changed when refreshing the dashboard
The chart Color Scheme  Keeps changing in the following scenarios :
1. For the Same User viewing the same dashboard.
2. For different users viewing the same dashboard.

#### How to reproduce the bug

1. Go to the dashboard with multiple charts
2. Applied color theme to the dashboard, for example, superset color
3. Refresh dashboard
4. Observe the color of each chart
5. See error

### Expected results

Refresh dashboard should not change the color of the chart

### Actual results

Refreshing the dashboard changes the color of chart

#### Screenshots

Image 1& 2 shows the same chart with different color schemes opened in a fraction of a few seconds by the same user.
<img width="1265" alt="image" src="https://github.com/apache/superset/assets/111956608/c1844d4c-67c9-42fc-a22a-30e0a1c2395d">
<img width="1261" alt="image" src="https://github.com/apache/superset/assets/111956608/ba9925ad-1289-4280-8993-b9b8a22cf973">
Images 3 & 4 are color schemes of the same chart for different users.
<img width="1652" alt="image" src="https://github.com/apache/superset/assets/111956608/b010ed18-ecae-4b3e-aa3a-aa78bdc2b392">
<img width="1217" alt="image" src="https://github.com/apache/superset/assets/111956608/4da76e82-ad71-4738-adcb-5ad232cd9f0d">

### Environment

- browser type and version: Chrome Version 119.0.6045.199 
- superset version: `3.0.1`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:
1. AVOID_COLORS_COLLISION = True (By default)

### Checklist

- [.] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [.] I have reproduced the issue with at least the latest released version of superset.
- [.] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
I saw a similar issue happening before and attaching the issue link which is closed for now.
https://github.com/apache/superset/issues/16970

**Comment by goto-loop** [comment]
I'm facing the same issue after migrating a dashboard from Superset 2.1.1 to 3.1.0.

As suggested in #16970, disabling `AVOID_COLORS_COLLISION` has solved the problem, but I see this more as a workaround than a fix because it might introduce issues with other charts in the future.

**Comment by geido** [comment]
cc @yousoph @eschutho

**Comment by progressive-scaler** [comment]
This error happens for me in 3.1.0 version.

In my case, disabling `AVOID_COLORS_COLLISION` on the config file did not help, so the problem still persists.

**Comment by geido** [comment]
Working on a solution here https://github.com/apache/superset/pull/27439
