### ISSUE TITLE
Unable to get new install running (webpack errors and /ws endpoint failing)

### ISSUE THREAD

**Issue by ScottChapman** [apache/superset#26475]
#### How to reproduce the bug

1. Clone repo
2. Launch with `docker compose up`
3. wait for everything to settle down.
4. Noticed a few errors during webpack

### Expected results

Clean webpack
### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by ScottChapman** [comment]
Here are the logs from the node:
[_superset_node_logs.txt](https://github.com/apache/superset/files/13923317/_superset_node_logs.txt)

**Comment by rusackas** [comment]
I think all of these warnings have been dealt with, and docker-compose is in a much better place than when this was filed. Closing as resolved, but holler if you're still seeing any of this.
