### ISSUE TITLE
Drill by function error with caching enabled

### ISSUE THREAD

**Issue by kevinremoue** [apache/superset#26471]
Using Drill by on a chart value produces a chart error on the **first time**. The **next time you trigger it on the same value**, it will work. Looks like an issue related to Caching. 

#### How to reproduce the bug

1. Go to a chart and use "Drill by" function
2. It opens a popup with the chart

### Expected results

You see the new chart generated by the "drill by" function

### Actual results

Error message: "There was an error loading the chart data"

#### Screenshots

![image](https://github.com/apache/superset/assets/15704413/35f1eea7-5ada-42b0-aa4a-c11e5a5fbd9d)

### Environment

- browser type and version: Chrome
- superset version: `3.0.2`
- python version: `3.9`
- any feature flags active:
"DASHBOARD_RBAC", "ENABLE_TEMPLATE_PROCESSING", "GLOBAL_ASYNC_QUERIES", "HORIZONTAL_FILTER_BAR", "DRILL_BY", "DRILL_TO_DETAIL"
**- Caching enabled** 

### Additional context

I see the following logs:
"superset.common.utils.query_cache_manager:force_cached (QueryContext): value not found for key 1c80874c0419c1d2902f9274c1a07f94"

**Comment by wuguokai** [comment]
We encountered the same issue during our use. Is there an estimated plan for a fix? The problem occurs when `GLOBAL_ASYNC_QUERIES` is set to `true`, but it can run normally when `GLOBAL_ASYNC_QUERIES` is set to `false`.

**Comment by kgabryje** [comment]
@kevinremoue @wuguokai Thanks for reporting this! Fix in PR #27066

**Comment by kevinremoue** [comment]
Thank you @kgabryje ! I will test it as soon as it is available on the repo.

**Comment by rusackas** [comment]
> Thank you @kgabryje ! I will test it as soon as it is available on the repo.

@kevinremoue looks like it was merged 4 days ago. Test away, and let us know how it goes :D Thanks in advance.

**Comment by wuguokai** [comment]
Thanks! @rusackas @kgabryje 
I have upgraded to the latest version 3.1.1rc1 image and it seems that there are still errors. Is something wrong?
<img width="275" alt="image" src="https://github.com/apache/superset/assets/30334643/3ff9cc7c-c18c-4e9d-a256-63497a372d38">
<img width="1099" alt="image" src="https://github.com/apache/superset/assets/30334643/876e51f9-7010-402d-9785-99f28cc4fe70">
