### ISSUE TITLE
Setting 'Schema cache timeout' causes an error in SQLab

### ISSUE THREAD

**Issue by eram** [apache/superset#26608]
#### How to reproduce the bug

1. Go to settings >> DatabaseConnecctions >> select a Posgres DB connection instance
2. Click on 'postgres' >> edit >> advanced >> performance
3. Scroll down to 'Schema cache timeout' set to 600 and [Finish]
4. Go to SQLLab 
5. Select a DB and refresh to get the list of schema
6. See error

### Expected results

'List refreshed' message and list of schema populated.

### Actual results

error: "There was an error loading the schemas"

what actually happens.

see attached video
https://github.com/apache/superset/assets/1045377/1fb7378f-84fd-4d5d-98d3-38ed23bd24f9

### Environment

- RDS/Postgres DB  << tested of 3 different DB and superset instances
- browser type and version: firefox
- superset version: 3.0
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active: 

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x ] I have reproduced the issue with at least the latest released version of superset.
- [ x ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

-

https://github.com/apache/superset/assets/1045377/1fb7378f-84fd-4d5d-98d3-38ed23bd24f9

**Comment by justinpark** [comment]
@eram I followed the steps but didn't encounter the same bugs as you demonstrated. It doesn't appear to be a bug. Additionally, changing the schema cache timeout won't make a difference.

https://github.com/apache/superset/assets/1392866/4b69d06b-cb02-48dc-a064-838fad218f65

**Comment by rusackas** [comment]
Closing since there was no follow-up to the above request for logs, but if you're still facing this, we're happy to revisit/reopen it.
