### ISSUE TITLE
Edit Role view: permission multi-select list box style changed and not retaining the previously selected item, when clicking on new item

### ISSUE THREAD

**Issue by saran-greytip** [apache/superset#26628]
In an Edit Role view, permission multi-select box style changed and not retaining the previously selected item, when clicking on new item. This happened after upgrading from 2.0 to 3.0.2

#### How to reproduce the bug

1. Go to 'Settings->List Role->'
2. Click on 'Edit Record(pencil icon) on any role.'
3. Permission list box style is changed and it is not allowing to type role and select from dropdown like superset 2.0

### Expected results

Permission multi-select box style should be same as superset 2.0 and allow to enter the role name and select from drop down. Also previously selected permission should be retained.

### Actual results

Permission multi-select box style changed and when clicking on the item, all the existing selected permission is getting unselected.  It is difficult to know what are all previously selected item to select them again.

### Environment

(please complete the following information):

- browser type and version: Chrome is up to date Version 120.0.6099.216 (Official Build) (arm64)
- superset version: `3.0.2`
- python version: `3.9.18`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

<img width="1153" alt="Screenshot 2024-01-16 at 11 17 14 AM" src="https://github.com/apache/superset/assets/125661379/5d15d846-8915-4748-821b-19d19de512f9">
<img width="1172" alt="Screenshot 2024-01-16 at 11 35 23 AM" src="https://github.com/apache/superset/assets/125661379/516c4ea5-ed7c-428d-b64a-825daf7ea19d">

**Comment by saran-greytip** [comment]
@michael-s-molina I waited more than a minute, still it is not working as expected. Looks like some javascript error is causing this problem. PFA the screenshot
<img width="1726" alt="Screenshot 2024-01-16 at 9 17 18 PM" src="https://github.com/apache/superset/assets/125661379/85a93582-230d-4b2b-9703-ea8595b31bf9">

**Comment by michael-s-molina** [comment]
This looks like a dependency problem. What's your `Flask-AppBuilder` version? Could you share the output of `pip list`?

**Comment by saran-greytip** [comment]
@michael-s-molina I hosted superset on Kubernetes using the docker image apache/superset:3.0.2.

Attaching the pip list text file here for your reference.



[superset3_0_2_pip_list.txt](https://github.com/apache/superset/files/13958229/superset3_0_2_pip_list.txt)

**Comment by michael-s-molina** [comment]
Hi @saran-greytip. If you look at Flask-AppBuilder 4.3.9, you'll see that it [used to have a reference to datetimepicker](https://github.com/dpgaspar/Flask-AppBuilder/blob/140e79dc7617575604c0870f4cc0b85759277c9c/flask_appbuilder/static/appbuilder/js/ab.js#L51). In Flask-AppBuilder 4.3.10 the [reference is gone](https://github.com/dpgaspar/Flask-AppBuilder/blob/20d110ff6d702937905ec8acbd041b19bfb30bdd/flask_appbuilder/static/appbuilder/js/ab.js#L54). Given that your `pip list` output shows 4.3.10, I can only think that the `static` folder of Flask-AppBuilder is being cached and returning the old version. Try to clear your browser cache and see if the problem disappears.

**Comment by saran-greytip** [comment]
@michael-s-molina Yes, Clearing the Chache for the superset site resolved the issue.  Thank you so much.

**Comment by saran-greytip** [comment]
This issue is fixed by clearing the browser cache as suggested by @michael-s-molina.
