### ISSUE TITLE
Never-ending loading screen when logging in to superset

### ISSUE THREAD

**Issue by mabra23** [apache/superset#26630]
#### How to reproduce the bug

1. Proceed as described in https://superset.apache.org/docs/installation/installing-superset-using-docker-compose/.
2. Run "docker compose up"
3. Access superset frontend via browser, URL: "[superset_app_IP]/superset/welcome"
4. See loading screen

### Expected results

Getting to the landing page and seeing the full-blown superset app GUI.

### Actual results

Loading screen loads forever.

#### Screenshots

Added:
"image.png" - Browser (edge) console when accessing superset.
"image (1).png" - superset_node container log with error
"image (2).png" - superset_nginx container log with error
"image (3).png" - never ending loading screen

### Environment

(please complete the following information):

- host machine: `Ubuntu 20.04.1 LTS (access via VPN)`
- browser type and version: `Microsoft Edge Version 120.0.2210.133 (Official build) (64-bit)`
- superset version: `Latest from master branch (3.0.2)` 
- python version: `Python 3.8.10`
- node.js version: `v10.19.0`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Hello everybody,

I am currently trying to setup superset via docker on an ubuntu 20.04.1 LTS server in a Cloud environment. After running the `docker compose up`, I can also access the app via the Floating IP and get to the log in page (IP/superset/welcome). After logging in, however, I only for a moment see the loading screen and an "X" & "Close" button on the top left, and then shortly after that only the loading page.

I checked the docker logs and detected some error messages for the docker container "superset_nginx" and the docker container "superset_node" (connection refused and webpack built on html2canvas and canvg). Does Anybody here have experience with this issue and can tell me what I am doing wrong? Is it something about the npm / the webpack or unsolved dependencies?
Also `docker-compose -f docker-compose-non-dev.yml up` does not apply as an alternative, since it does not provide the nginx container for access and I need to customize the frontend.

I attached a snapshot of the loading screen and the logs and the browser console Thanks so much!

Best,
Max

![image (3)](https://github.com/apache/superset/assets/147081310/16299629-ac07-4649-8f5c-07f9dfc90307)
![image (2)](https://github.com/apache/superset/assets/147081310/7293b67b-e53d-4f91-9b42-244b74fdc4bb)
![image (1)](https://github.com/apache/superset/assets/147081310/09e3d747-211c-4f97-9cbd-8ddfe1c245a7)
![image](https://github.com/apache/superset/assets/147081310/8ae62f77-4266-46ce-967d-8672d361a580)

**Comment by mabra23** [comment]
Update: Running `docker compose -f docker-compose-non-dev.yml up` on the local environment and the server environment works. Probably corroborates that there is something with webpack/dependencies in the node worker that are not resolved? Need the dev version, where the above errors persist - thanks for any comments!!

**Comment by rusackas** [comment]
> host machine: Windows 11
We don't officially support Windows, but if you got it working then more power to you :D 

Closing this since it sounds like you got it working with docker-compose-non-dev.yml anyway. Things have also stabilized (and sped up) with Docker in the last couple months, so I hope all is well :)
