### ISSUE TITLE
Time Range type options restrictions

### ISSUE THREAD

**Issue by devteam-tb** [apache/superset#26659]
## Screenshot

![image](https://github.com/apache/superset/assets/128605174/c2d2635d-0c9b-464d-890f-28fb3e71cc78)

## Description

We have the time range options. But, how we can hide or restrict the few options. Eg: I want to show only **Last**, **Previous** on the above option. how i can do it?

**Comment by michael-s-molina** [comment]
Hi @devteam-tb. Currently, there's no configuration to restrict the options. They are hardcoded [here](https://github.com/apache/superset/blob/5e633d2bb0909f1cb4904c07e29a2c683f02131c/superset-frontend/src/explore/components/controls/DateFilterControl/DateFilterLabel.tsx#L288) and you would need to override that part of the code in your branch.
