### ISSUE TITLE
Dead links for installing GeckoDriver WebDriver and Firefox 

### ISSUE THREAD

**Issue by anirudh-hegde** [apache/superset#26706]
### Bug description

Dead links found for installing GeckoDriver WebDriver and Firefox 

 # Install GeckoDriver WebDriver
    && wget -q https://github.com/mozilla/geckodriver/releases/download/${GECKODRIVER_VERSION}/geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz -O - | tar xfz - -C /usr/local/bin \
    # Install Firefox
    && wget -q https://download-installer.cdn.mozilla.net/pub/firefox/releases/${FIREFOX_VERSION}/linux-x86_64/en-US/firefox-${FIREFOX_VERSION}.tar.bz2 -O - | tar xfj - -C /opt \

### How to reproduce the bug

[https://github.com/apache/superset/blob/master/Dockerfile](url)
- When I try to open these two links to install GeckoDriver WebDriver and Firefox, the links are not found.
 
![image](https://github.com/apache/superset/assets/105560839/3f487f38-a611-4293-a726-3669586606fc)

### Screenshots/recordings

- When I try to open these two links, it shows
![image](https://github.com/apache/superset/assets/105560839/cbbb48f3-5e5b-44ac-8481-1a1548b55556)
![image](https://github.com/apache/superset/assets/105560839/790ce8e0-05c3-4933-b7c6-ce070afcb24b)

### Superset version

master / latest-dev

### Python version

3.11

### Node version

16

### Browser

Firefox

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by sfirke** [comment]
`${GECKODRIVER_VERSION` and `${FIREFOX_VERSION}` are variables passed into the Dockerfile so it makes sense that those links did not work.  Please try replacing those with actual version numbers.  I would be surprised if those links are broken given that they would cause the building of new versions and thus active development on Superset to fail.

I'm going to close this, please comment if after this information you believe this is indeed a bug.

**Comment by anirudh-hegde** [comment]
Hey, can you please try to open this link [https://github.com/mozilla/geckodriver/releases/download/](url)
