### ISSUE TITLE
Remove/Hide 'All' 'Inv' icons in Superset charts display

### ISSUE THREAD

**Issue by sandeepr43** [apache/superset#26711]
## Screenshot

![All_inv_icons](https://github.com/apache/superset/assets/134920389/95322bf0-cdbe-411b-9036-3343ddc2b47e)

## Description

There are 2 icons in almost every chart in Superset namely "**All**" and "**Inv**".
We really do not require these icons, but there is not option to hide them or remove them through any options.
Any way we can hide or remove them will be really useful to get more space to show legends of the chart.

## Design input
Any way we can hide/ remove these icons through any properties or CSS templates would be really helpful.

**Comment by sfirke** [comment]
People who end up here might be interested in the similar post as a discussion: https://github.com/apache/superset/discussions/27012
