### ISSUE TITLE
How to disable authentication to bypass login?

### ISSUE THREAD

**Issue by Lufffya** [apache/superset#26737]

**Comment by michael-s-molina** [comment]
Please follow the issue template instructions.

> 🙏 Asking a question or getting help: post in the [Superset Slack chat](http://bit.ly/join-superset-slack) or [GitHub Discussions](https://github.com/apache/superset/discussions) under "Q&A / Help".
> 💡 Requesting a new feature: Search [GitHub Discussions](https://github.com/apache/superset/discussions) to see if it exists already. If not, add a new post there under "Ideas".
