### ISSUE TITLE
Importing a dashboard that uses a dataset with defined metrics does not import the metrics themselves

### ISSUE THREAD

**Issue by Stefan781** [apache/superset#26734]
### Bug description

I have a dataset for which I have defined some metrics. The dataset is used in some visualizations that are then used inside a dashboard. When I export the dashboard, the dataset is exported properly - the metrics are included in the YAML file. However, if I import the dashboard on a different instance of Superset, the metrics seem to not be imported and the charts raise an error when accessed, informing that the metrics are missing.

### How to reproduce the bug

1. Create a new dataset.
2. Add a custom metric to it.
3. Use the dataset in a visualization.
4. Add the visualization to a new dashboard.
5. Export the dashboard. Verify that the metrics are included into the file.
6. Import the dashboard in a new Superset instance.
7. The metrics are not imported.

### Superset version

3.1.0

### Python version

Not applicable

### Node version

Not applicable

### Browser

Not applicable

### Additional context

I am currently using the 3.1.0 Docker image, but found the issue while using the 3.0.2. There are no errors in the logs when I import the dashboard.

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by Stefan781** [comment]
I played around and it turned out that I have another dashboard that uploads the same dataset without the metrics. I am still not sure why this was an issue since I also tried manually uploading the dashboard and ran into the same issue once the dataset has been uploaded once. But it is resolved now.

**Comment by bbaumnn** [comment]
I have the same issue on version 3.0.1 exporting the dashboard via API. I can not see the metrics in the "datasources" section of the exported file. In older versions this used to work.

**Comment by Stefan781** [comment]
@bbaumnn Sounds like a different problem. Perhaps open another issue to get more attention.
