### ISSUE TITLE
Gamma role does not have permissions to drill

### ISSUE THREAD

**Issue by sfirke** [apache/superset#26762]
### Bug description

With out-of-the-box permissions, the Gamma role can right click and see the option to drill, but gets an Access is denied error.  They are missing the "can samples on datasource" permission that is needed for this.  See https://github.com/apache/superset/discussions/25388 for discussion.

### How to reproduce the bug

Try to drill-by a chart from a user with Gamma role permissions.

### Screenshots/recordings

See discussion link above.

### Superset version

3.0.3

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

There is the design question of whether Gamma role should be able to drill by default (or Public, for that matter).  I posted in Slack about this, Tai thought Gamma should be able to drill b/c they can already create charts with that data.  I think Gamma yes to default drilling, Public no.

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by duniang818** [comment]
yes, this solved my same issue
