### ISSUE TITLE
Table Chart - Total values are misaligned

### ISSUE THREAD

**Issue by vasu-ram** [apache/superset#26761]
### Bug description

When aligning values on table chart the column header and total are slightly misaligned, This issue gets worse the more columns are used

### How to reproduce the bug

Create a table chart
Add 6 columns 
Go to Customize the tab > align left (repeat for each column)
Save chart to dashboard

### Screenshots/recordings

![image](https://github.com/apache/superset/assets/55632570/19158851-f03b-4f28-b75e-c9ea6f05057f)

### Superset version

3.1.0

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by kgabryje** [comment]
Hey @vasu-ram! I tried to repro the issue and the totals seem to be aligned correctly (see screenshot). What browser are you on? Do you have some custom css on your dashboard that could affect the table?

<img width="1127" alt="image" src="https://github.com/apache/superset/assets/15073128/f7928cb4-f8a8-4bf3-8ee7-b89c9e78fd5d">

**Comment by vasu-ram** [comment]
@kgabryje Thank you so much for checking. Sorry, I am not using any CSS for the Dashboard, Still I can see the total values are misaligned

![image](https://github.com/apache/superset/assets/55632570/e4666080-dd1b-4531-8006-17380a4942ce)
1. The total values are starting at highest number of the value
2. The total values are starting at second digit of the value
3. The total values are starting at smallest digit of the value

**Comment by kgabryje** [comment]
@vasu-ram http://35.88.169.129:8080/superset/welcome/ Here's a test environment that will probably be active for a while. Could you try to repro the bug there?

**Comment by kgabryje** [comment]
Do you have any browser extensions that might affect fonts?

**Comment by vasu-ram** [comment]
@kgabryje I am using chrome and Edge but both are looks same
![image](https://github.com/apache/superset/assets/55632570/36c66d75-fbf1-4ceb-a4ff-5ab4a2d66942)

**Comment by vasu-ram** [comment]
No I don't have any browser extensions

**Comment by michael-s-molina** [comment]
@kgabryje I'm able to reproduce the issue but it only happens when the scroll is enabled. Totals and headers get misaligned.

https://github.com/apache/superset/assets/70410625/8119ecf2-3d0b-4e32-be04-91dc6a618dae

**Comment by kgabryje** [comment]
Thanks @michael-s-molina for helping me repro! The fix is here: https://github.com/apache/superset/pull/26964. (CC @vasu-ram)

**Comment by vasu-ram** [comment]
Thanks @kgabryje @michael-s-molina
