### ISSUE TITLE
Row limit hardcoded at 100 000 in the UI

### ISSUE THREAD

**Issue by Stefan781** [apache/superset#26779]
### Bug description

It seem that changes in https://github.com/apache/superset/pull/26151 broke the UI. Setting SQL_MAX_ROW above 100 000 and trying to go over this limit results in an error in the UI, saying "value cannot exceed 100 000". Setting SQL_MAX_ROW under 100 000 results in the same error regardless of the changes to SQL_MAX_ROW. Meanwhile, when you view the chart's query from inside a dashboard, the LIMIT changes accordingly based on the SQL_MAX_ROW variable. For example, if the SQL_MAX_ROW limit is 500 000 and your chart was created before migrating to 3.1 with the same limit, the UI will not allow you to edit the chart but the LIMIT in the query itself will be set to 500 000. If you change SQL_MAX_ROW to anything below 500 000, the UI will keep the same error but the LIMIT inside the query will be lowered accordingly.

### How to reproduce the bug

1. Set the SQL_MAX_ROW variable to anything that is different than 100 000.
2. Create a chart.
3. Set the limit to something above 100 000.
4. The UI informs you that the limit is 100 000.
5. If you have set SQL_MAX_ROW to < 100 000, set 100 000 as the limit in the UI and create the chart.
6. Add the chart to a dashboard.
7. View query.
8. The LIMIT is equal to SQL_MAX_ROW .

### Screenshots/recordings

Limits inside the Docker Container:
![image](https://github.com/apache/superset/assets/130654984/6ea3ff7d-584b-4a63-a71c-a4b1abd4b6ba)
Error message:
![image](https://github.com/apache/superset/assets/130654984/c3bbf58f-b970-45cf-bfbb-23966bfd764d)
View query LIMIT:
![image](https://github.com/apache/superset/assets/130654984/0c45cb67-2318-413a-87e5-e96eb9d39225)

### Superset version

3.1.0

### Python version

Not applicable

### Node version

Not applicable

### Browser

Not applicable

### Additional context

One workaround until this is fixed is to export the chart and change the row limit inside the YAML, then import the chart. I tried changing the ROW_LIMIT variable as well, but it did not solve the issue.

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by mujohiddin** [comment]
Hello there. my project is last year september october version but i have row limit not working how to fix it. @mistercrunch
@villebro
@michael-s-molina
@betodealmeida
@john-bodley
@rusackas
![photo_2024-05-22_11-52-17](https://github.com/apache/superset/assets/69301931/135086da-2d31-4857-9237-ea2607f79e9e)
![photo_2024-05-22_11-52-55](https://github.com/apache/superset/assets/69301931/ac513813-844b-4567-8be9-957bbfb62b62)

**Comment by mujohiddin** [comment]
@mistercrunch
@villebro
@michael-s-molina
@betodealmeida
@john-bodley
@rusackas

**Comment by mujohiddin** [comment]
@michael-s-molina

**Comment by mujohiddin** [comment]
@betodealmeida
