### ISSUE TITLE
apache/superset:dockerize amd64 not found

### ISSUE THREAD

**Issue by deebify** [apache/superset#26783]
### Bug description

I tried to install superset helm chart. The chart is fetching apache/superset:dockerize which is exit for arm but not for amd64 on dockerhub. 

### How to reproduce the bug

docker pull apache/superset:dockerize
```
dockerize: Pulling from apache/superset
no matching manifest for linux/amd64 in the manifest list entries

```

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by bmtKIA6** [comment]
same...

**Comment by dpgaspar** [comment]
We are building dockerize for both architectures, but it seems you have to be explicit about the exact SHA you want, you can use initImage.tag to define it.

example: [5040044ee638e5e41d572deaa2f8547d02d05449-dockerize-linux-amd64-3.9-slim-bookworm](https://hub.docker.com/layers/apache/superset/5040044ee638e5e41d572deaa2f8547d02d05449-dockerize-linux-amd64-3.9-slim-bookworm/images/sha256-b5a9d09b12b5f9e1e7e85e395ab65487fba4742006803a07cf4ddf3a61925336?context=explore)

**Comment by mistercrunch** [comment]
Might be my recent PR on docker-related things, let me check

**Comment by samip5** [comment]
Normally you would merge the different tags to one single one after both are built.

Example of such a thing:  [Building](https://github.com/samipsolutions/containers/blob/main/.github/workflows/action-image-build.yaml#L68) and then [Merging](https://github.com/samipsolutions/containers/blob/main/.github/workflows/action-image-build.yaml#L192)

**Comment by Pythoner6** [comment]
Yeah, I'd think the main image really should be multi-arch.

**Comment by mistercrunch** [comment]
First I hear of multi-platform docker images. At least now we'll have a distinct tag for each.

**Comment by merlos** [comment]
Not having `apache/superset:dockerize` to support `linux/amd64` approach is breaking the helm install in all x86

Ideally one single tag can support multiple archs. Indeed superset chart already depends on postgres and redis images that already support both architectures. 

This doc may be helpful:
https://docs.docker.com/build/building/multi-platform/

**Comment by merlos** [comment]
Duplicated.  Also in this issue: #26788

**Comment by arundh93** [comment]
Any update on this?

**Comment by mistercrunch** [comment]
Should be all set, can you confirm? More details here -> https://superset.apache.org/docs/installation/docker

**Comment by merlos** [comment]
@mistercrunch why don't you release tags using multi-architecture images? 

During the build phase you can do something like this: 

```sh
docker buildx create --name mybuilder --bootstrap --use
docker buildx build --platform linux/amd64,linux/arm64 -t <username>/<image>:latest --push .
```
More doc here: 
https://docs.docker.com/build/building/multi-platform/#getting-started

It does not seem a big deal for Superset, and will prevent issues to all ARM users (raspberri pi, Apple M1/2/3... Most of the helm charts I've used just work without needing to change the image architecture.

**Comment by arundh93** [comment]
@mistercrunch the helm installation for superset still fails since it expects the dockerize tag for amd platform.
https://github.com/apache/superset/blob/master/helm/superset/values.yaml#L189

Ideally we should be doing what @merlos is suggesting above

**Comment by deebify** [comment]
@mistercrunch it would be great if the release is a multi-arch image. 

similar to this 
![image](https://github.com/apache/superset/assets/6893368/6090862a-ee71-42f9-b3c1-f61cbb1842fb)

**Comment by mistercrunch** [comment]
The image under the `dockerize` tag is `linux/amd64`

https://hub.docker.com/layers/apache/superset/dockerize/images/sha256-6172f74040aab46c1dc44b75ba07477d3ad91be813ad4b6baa1aab1127349bbe?context=explore&tab=vulnerabilities

About multi-platform builds I agree it's a good idea, but requires more build time, slowing down CI. Given the 2 builds have each a different base, it's pretty much twice the work (presumably twice the clock time too). In theory we could do this on-release only (not for each PR/master merge, but only on official tag, ASF release).

Two approaches:
1. I think there's a way to merge the manifests post build, but that seemed tricky/annoying
1. pass two platform argument (which doubles the build time) and we only want on-release

I'd go with option 2, and on-release only, but it'd require doing a bit of work around the build script. Overall the process would be:
- add support for multi-platform argument [here](https://github.com/apache/superset/blob/master/scripts/build_docker.py#L206-L209)
- remove platform from the matrix [here](https://github.com/apache/superset/blob/master/.github/workflows/docker-release.yml#L46)
- pass the two platform in the call [here](https://github.com/apache/superset/blob/master/.github/workflows/docker-release.yml#L95)
- re-trigger the job for old releases (easy)

For now, can you just suffix the tags to the version you want? Also amd should be the default, not sure why you'd get that error message

**Comment by sergioluka** [comment]
@mistercrunch 

> About multi-platform builds I agree it's a good idea, but requires more build time, slowing down CI. Given the 2 builds have each a different base, it's pretty much twice the work (presumably twice the clock time too). In theory we could do this on-release only (not for each PR/master merge, but only on official tag, ASF release).

This sounds like the right approach imho.

**Comment by mistercrunch** [comment]
Closing this issue, and opened a feature request here https://github.com/apache/superset/discussions/27043
