### ISSUE TITLE
Cannot use anonymous user on Superset(eg: Public Role) when using it along with LDAP

### ISSUE THREAD

**Issue by ImmortalLotus** [apache/superset#26781]
### Bug description

When using LDAP, even with public role as follows: 

![image](https://github.com/apache/superset/assets/72933183/213a68fe-8821-4052-863b-cd6a71693192)

it is not possible to access the home page or rather any such page, such as dashboards that could be usually configured as public when using AUTH_DB, for ex, without logging in.

When using AUTH_DB, you can access the default menus and whatever dashboards were configured for public access even without logging, and this behavior changes without any single explanation that it would change included in the docs, nor there is a flag to allow for this to be configured.

When using LDAP, the Public role behavior should NOT change, or at least there should be warnings on the docs or a flag to change the behavior back into how it works when using AUTH_DB.

### How to reproduce the bug

Use LDAP
Try to access superset without logging in
Get redirected to login page.

### Superset version

3.1.0

### Python version

I don't know

### Node version

I don't know

### Browser

Not applicable

### Additional context

I have read the docs, but I do not use slack

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by sfirke** [comment]
Are you still experiencing this?  I am using OAuth, not LDAP, but it's similar and I've never had a trouble with the public role not working (2.0.0 through 3.1.1.).

**Comment by ImmortalLotus** [comment]
I'm terribly sorry. as it turns out, at the time I had fucked up my talisman configurations in a way that I still do not fully comprehend.
Should've closed this sooner my bad
