### ISSUE TITLE
OAUTH, RLS and the case for {{ current_useremail }}

### ISSUE THREAD

**Issue by modidim2021** [apache/superset#26808]
### Bug description

This is not a a bug per se, but is something missing and I don't believe it needs a SIP.  Sorry if I miscalculated.

I have a superset instance with OAuth (google) authentication and I'm trying to implement RLS for the current user. 

In ab_user I have the following row (I include only the relevant fields):
```
  {
    "id": 1,
    "username": "google_102854032914007021400",
    "email": "victor@gmail.com",
  }
```

In my model the table d_user has the following data (Only meaningful fields):
```
  {
    "user_key": 26,
    "user_id": 100026,
    "name": "Victor Diaz",
    "email": "victor@gmail.com",
  }
```

The templating [page](https://superset.apache.org/docs/installation/sql-templating/) states that the available macros are:  ** {{ current_username() }}** and **{{ current_user_id() }}**.  

With {{ current_user_email() }}, I can apply an RLS right away instead of making ab_user part of the ingestion process to get the username.

### How to reproduce the bug

1. In superset instance that uses OAuth (google) try to add a "row level security filter" for the current_user.

d_user.email = {{ current_?? }}

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Pinging @john-bodley / @villebro in case you happen to know of a way to tackle this.

**Comment by rusackas** [comment]
If there's not a way to get this (I'd be surprised) then we'd be open to a PR, or moving this to an Ideas discussion in hopes of moving the feature request forward.

**Comment by Vitor-Avila** [comment]
there you go: https://github.com/apache/superset/pull/27197. I'm not 100% sure if there could be a security concern of having a jinja macro that returns the logged-in user's email address, but hopefully not 🤞
