### ISSUE TITLE
[regression] `apachesuperset.docker.scarf.sh/apache/superset:latest-dev` no longer contains images for arm64

### ISSUE THREAD

**Issue by CatStudioApp** [apache/superset#26822]
### Bug description

About one week ago, I can download arm64 images from `apachesuperset.docker.scarf.sh/apache/superset`

However, right now it does not support arm64 anymore.

### How to reproduce the bug

```shell
$ docker pull apachesuperset.docker.scarf.sh/apache/superset:latest
latest: Pulling from apache/superset
no matching manifest for linux/arm64/v8 in the manifest list entries
```

### Superset version

master / latest-dev

### Python version

Not applicable

### Node version

Not applicable

### Browser

Not applicable

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by kakoni** [comment]
@CatStudioApp The quick fix as per https://github.com/apache/superset/issues/25434 is to do ```export DOCKER_DEFAULT_PLATFORM=linux/amd64```

**Comment by mistercrunch** [comment]
Suffixing `-arm` should work as in `latest-arm`, documented changes here https://github.com/apache/superset/pull/26923

**Comment by mistercrunch** [comment]
But I don't have the creds to push to docker from local so I can't retag stuff, or I'd have to trick CI into it.

**Comment by rusackas** [comment]
I believe all these ARM issues were solved by @mistercrunch after this ticket was last touched. I'll optimistically close it, but let us know if you're still facing this (and perhaps some updated context) and we can certainly revisit/reopen.

**Comment by mistercrunch** [comment]
Yup we should be good, there was a bit of a long tail of issues around older versions that were cut off master before some of the work took place. Everything should be ironed out now.
