### ISSUE TITLE
France Region file too large and in EPSG 2154 projection instead of EPSG 4326 (WGS 84)

### ISSUE THREAD

**Issue by dmeaux** [apache/superset#26846]
### Bug description

Due to the france_regions.geojson file being in EPSG 2154 and have much more detail than the other maps, its file size is 12MB. The geometries should be simplified and reprojected to WGS 84 (EPSG 4326), the default for GeoJSON files, in order to decrease the file size and speed up the rendering.

### How to reproduce the bug

This bug only occurs on some systems, depending on the exact configuration. The fix is an easy one and will standardize the france_regions.geojson file with the other GeoJSON files.

### Screenshots/recordings

![image](https://github.com/apache/superset/assets/48763344/93a89460-91e8-4842-81f1-00bffb0f36b8)

### Superset version

master / latest-dev

### Python version

3.10

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
I do believe this is resolved :)
