### ISSUE TITLE
Drag table chart preview issue

### ISSUE THREAD

**Issue by justinpark** [apache/superset#26873]
## Screenshot

https://github.com/apache/superset/assets/1392866/fe4acbd4-16a9-43b9-9e7b-cbd2268392a3

## Description

When a table chart is dragged, the preview container appears to overflow beyond the actual chart size, likely due to the inner table chart itself overflowing.

## Design input
We should have a static image for the table chart (or hide the table component on drag preview)

**Comment by michael-s-molina** [comment]
@justinpark do you have any PR to fix this issue? It's pretty bad.

**Comment by rtexelm** [comment]
I've been looking into this issue trying to come up with a fix.
Can anyone else confirm that it's only occurring on Chrome? I just checked it in Firefox and I'm not seeing any overflow.
I found [#832 on react-dnd](https://github.com/react-dnd/react-dnd/issues/832#issuecomment-444080537), seems to be related. Currently trying to implement the quick fix they recommended locally.
