### ISSUE TITLE
Discrepancy between /docs and CONTRIBUTING.md

### ISSUE THREAD

**Issue by fenilgmehta** [apache/superset#26883]
### Bug description

What is the source of truth among the below two?

- https://github.com/apache/superset/blob/master/CONTRIBUTING.md#os-dependencies says `3.9, 3.10 or 3.11`
- https://superset.apache.org/docs/contributing/local-backend says `3.9 or 3.10`

### How to reproduce the bug

1. Visit https://github.com/apache/superset/blob/master/CONTRIBUTING.md#os-dependencies and read it
2. Visit https://superset.apache.org/docs/contributing/local-backend and read it
3. There is discrepancy among them

### Screenshots/recordings

/CONTRIBUTING.md#os-dependencies

![image](https://github.com/apache/superset/assets/42742240/09a672a0-eff2-4dd0-8b4c-9f0a7cfa60d4)

/docs/contributing/local-backend.mdx

![image](https://github.com/apache/superset/assets/42742240/7fc44fe3-5f56-4588-8581-b1dc04f1c7f1)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

It would be nice to have https://superset.apache.org/docs/ as the source of truth and `CONTRIBUTING.md` point/refer to it.

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by sfirke** [comment]
Also see https://superset.apache.org/docs/installation/installing-superset-from-scratch/#os-dependencies, where it says:

> You should install a recent version of Python. Refer to the [setup.py](https://github.com/apache/superset/blob/master/setup.py) file for a list of Python versions officially supported by Superset.

And

> To identify the Python version used by the official docker image, see the [Dockerfile](https://github.com/apache/superset/blob/master/Dockerfile). Additional docker images published for newer versions of Python can be found in [this file](https://github.com/apache/superset/blob/master/scripts/docker_build_push.sh).

**Comment by sfirke** [comment]
Sorry, I clicked "close" accidentally.  I'm going to edit the above comment as if I hadn't just published it mid-thought 😳

**Comment by rusackas** [comment]
That Contributing content has effectively been ported into [the main docs](https://superset.apache.org/docs/contributing/development/#os-dependencies), and deduplicated. Currently 3.9, 3.10, and 3.11 is the current statement :)
