### ISSUE TITLE
docker - only arm64 build?

### ISSUE THREAD

**Issue by JustinGuese** [apache/superset#26884]
### Bug description

Hey guys, is it an accident that you pushed an arm64 only image to docker hub?
at least dockerize is arm64 only, and our build pipeline crashes

<img width="626" alt="image" src="https://github.com/apache/superset/assets/9588843/842499d7-0e65-4e8c-926a-69269041c7a3">

### How to reproduce the bug

`docker run apache/superset:dockerize` on an amd64 machine -> Error "could not find am64 image"

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by arundh93** [comment]
there is already an issue created for this
https://github.com/apache/superset/issues/26783
