### ISSUE TITLE
DB password change not saving in Superset

### ISSUE THREAD

**Issue by muthyas** [apache/superset#26976]
### Bug description

As we rolled out superset into production, we changed the database password. The same was changed in Superset Settings->Data Connections as well. However, none of the datasets are now loading as the schema loading fails. Also see in the logs that password authentication has failed. For some reason, although the password was changed in Superset reflecting new password, the datasets are failing to load the schema.  

### How to reproduce the bug

Start new installation of Superset with psycopg2. . Add a Data Connection pointing to Postgres db. Load a new Dataset / table into superset.

Next change the password in postgres DB. In Superset, click on Settings->Data Connections and edit the Database password to reflect the new password. Once database password is saved in Superset, go back and click on Data Connection. Database schema loading fails. 

### Superset version

3.1.0

### Python version

3.10

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Closing this issue as stale, but if you're still facing it and can provide any additional context (i.e. logs) that might help us troubleshoot this, we can certainly reopen it. Let us know where things stand, and we can go from there. Thanks!

**Comment by As-anonymus** [comment]
@rusackas  this issue still persists when adding the new plain text password it shows connection successful but when going for finish it says an error occurred.

2025-12-09 12:22:54,287:ERROR:flask_appbuilder.api:property 'masked_encrypted_extra' of 'Database' object has no setter
Traceback (most recent call last):
  File "/app/.venv/lib/python3.11/site-packages/flask_appbuilder/api/__init__.py", line 111, in wraps
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/superset/views/base_api.py", line 120, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/superset/utils/core.py", line 1363, in time_function
    response = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/app/superset/utils/log.py", line 303, in wrapper
    value = f(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^
  File "/app/superset/views/base_api.py", line 92, in wraps
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/superset/databases/api.py", line 543, in put
    changed_model = UpdateDatabaseCommand(pk, item).run()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/superset/utils/decorators.py", line 266, in wrapped
    return on_error(ex)
           ^^^^^^^^^^^^
  File "/app/superset/utils/decorators.py", line 236, in on_error
    raise ex
  File "/app/superset/utils/decorators.py", line 259, in wrapped
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/superset/commands/database/update.py", line 87, in run
    database = DatabaseDAO.update(self._model, self._properties)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/superset/daos/database.py", line 62, in update
    return super().update(item, attributes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/superset/daos/base.py", line 161, in update
    setattr(item, key, value)
AttributeError: property 'masked_encrypted_extra' of 'Database' object has no setter
115.117.115.6:43199 - - [09/Dec/2025:12:22:54 +0000] "PUT /api/v1/database/5 HTTP/1.1" 500
