### ISSUE TITLE
The database does not appear in the sqlLab menu

### ISSUE THREAD

**Issue by deviardn** [apache/superset#27006]
### Bug description

Hello everyone. Sorry, my English is not good.
I have more than 200 database connections (SQL Server). Connection established successfully, no problems. Only when I look in SqlLab at the database selection, the database only displays 100 databases. Meanwhile, when I search for my other databases, it doesn't appear. Is it really the limit of 100? If I don't want a limit, where should I change the code? Thank you.

### How to reproduce the bug

![2024-02-04_12-53_sqllab](https://github.com/apache/superset/assets/6567330/1d1956cd-b967-4251-b57c-81db159cda13)
![2024-02-04_12-54_sqllab2](https://github.com/apache/superset/assets/6567330/ec26caee-2116-4ad0-86ea-20e6b59cda8c)

### Superset version

3.0.3

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by andrekef** [comment]
I had a similar issue with sqlite connection.
Establishing a connection, I am assuming wont 100% guarantee that its actually linked to your DB. Check you connection path or even try sqlalcheny connection to define you absolute DB path.
