### ISSUE TITLE
SQL Lab - Joining two different oracle schema is not working

### ISSUE THREAD

**Issue by aks1981** [apache/superset#27004]
### Bug description

Not able to join the two different oracle schema.
Apache Superset version- Version: 3.0.1

I am following the below link
https://superset.apache.org/docs/databases/meta-database/  

Step -1:                     
 - ENABLE_SUPERSET_META_DB as True
- After that I re-stared Superset service.

Step -2 
- Create DB connection with oracle schema1 and second db connection with schema 2
- Open SQL lab write SQL join query and run the query 

-Output  - getting ORA error table view not found.

Please advise

### How to reproduce the bug

Not able to join the two different oracle schema.
Apache Superset version- Version: 3.0.1

I am following the below link
https://superset.apache.org/docs/databases/meta-database/  

Step -1:                     
 - ENABLE_SUPERSET_META_DB as True
- After that I re-stared Superset service.

Step -2 
- Create DB connection with oracle schema1 and second db connection with schema 2
- Open SQL lab write SQL join query and run the query 

-Output  - getting ORA error table view not found.

Please advise

### Superset version

3.1.0

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by Habeeb556** [comment]
Referring to issue #25522, it appears that the Superset Meta DB type was introduced in version 3.1.0. However, I'm currently using version 2.3.1, and I can confirm that querying between two different schemas is working but the meta db is for two different databases.

As below for oracle:
`select * from schema1.table1 join schema2.table2`

**Comment by aks1981** [comment]
Once Superset upgraded to 3.1.0 its working fine 
After upgrade followed below url steps.
https://superset.apache.org/docs/databases/meta-database/ 

1. Select database as below
<img width="395" alt="image" src="https://github.com/apache/superset/assets/24263770/07a8e32f-a5b1-48b2-99cd-14232ab13c82">

2. table name should be in double quotes. e.g. -  
select * from "db_connection_name.schema1.table1"

**Comment by shubhshah01** [comment]
Hey @aks1981, 
when adding superset meta database connection, what is the connection url actually ?
I have 2 db connections say conn1 and conn2... Now what does superset meta database connection url look like ?

**Comment by KhaledBenZina** [comment]
> Once Superset upgraded to 3.1.0 its working fine After upgrade followed below url steps. https://superset.apache.org/docs/databases/meta-database/
> 
> 1. Select database as below
> 
> <img alt="image" width="395" src="https://private-user-images.githubusercontent.com/24263770/302922335-07a8e32f-a5b1-48b2-99cd-14232ab13c82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NjYzMDgsIm5iZiI6MTcxMjY2NjAwOCwicGF0aCI6Ii8yNDI2Mzc3MC8zMDI5MjIzMzUtMDdhOGUzMmYtYTViMS00OGIyLTk5Y2QtMTQyMzJhYjEzYzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDEyMzMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljOTFhZmZjODFjZGYwN2YyODM2NWNmMjc5MTU1Njk4NTQwMTJjNzg3OWJiYzFlMmVlNDE4Y2Y0NmRmZmZmNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w5_3qOz2S511M22KZ25kgVyQUg_ZPibMx8e0kON9NRk">
> 2. table name should be in double quotes. e.g. -
>    select * from "db_connection_name.schema1.table1"

Hey @aks1981 , 
It's working fine for me also but only with SQL type connections. I am using Mysql and MongoDB and only MySql is responding on superset meta database connection. How to you query a mongo database?
