### ISSUE TITLE
When dashboard is long and exported as a image there will have loading charts.

### ISSUE THREAD

**Issue by Lysanleo** [apache/superset#27008]
## Screenshot
![运营数据-2024-02-04T15-22-46 798Z](https://github.com/apache/superset/assets/13273729/bf5c8adc-5d6d-4c1a-bc62-76ffb80ea790)

## Description

I have a long dashboard as shown in the image, when I try to export it as an image, the charts that are far away change to the loading style in the exported image, and I want the exported image to show all the content of the charts.     

## Design input

**Comment by rusackas** [comment]
Can you let us know what version of Superset you're running? I'm thus far unable to replicate this on Preset or on open source Superset, using some pretty long dashboards. Seems to be working fine with image and PDF downloads. If you can provide more details, we can reopen this issue if warranted.
