### ISSUE TITLE
Unable to set a dataset column's datetime format

### ISSUE THREAD

**Issue by prb219** [apache/superset#27059]
### Bug description

Superset version in use: 2.1.0

We are trying to mark a  temporal column in a dataset as 'epoch_s'. However, when we select edit dataset > columns we don't really see a drop down option next to the column name to make this change. Can someone please look into it ? Do we need some permissions to be able to see this option ?
 
Current behavior: 
- No drop down menu seen next to the column name
-
![Screenshot 2024-02-08 at 3 48 13 PM](https://github.com/apache/superset/assets/14629864/2a117f8a-a540-4dbb-a0b6-1586aec43f24)

### How to reproduce the bug

1. Go to any dataset
2. Select edit dataset > columns

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Firefox

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Just confirming... your description says you're running master/latest and it also says 2.1.0. Which is the case? This doesn't seem to be a problem in 3.x, and we no longer support 2.x, so I'm tempted to close this.

**Comment by prb219** [comment]
We are using 2.1.0 version. Would really appreciate if you could guide on this issue as it is blocking us.

**Comment by rusackas** [comment]
You should indeed be able to toggle the little disclosure triangle to see the form to edit things like `label` which I believe is what you're after.
<img width="855" alt="image" src="https://github.com/apache/superset/assets/812905/415ef825-d006-45f6-a4ff-7c7559522734">

Then it'll show up in controls as such.
<img width="324" alt="image" src="https://github.com/apache/superset/assets/812905/370428f9-9298-4d04-a085-4a75cdeeee8b">

If you don't see that, you might have a [permissions issue](https://github.com/apache/superset/blob/master/RESOURCES/STANDARD_ROLES.md). Your role might not have the "Can Edit Dataset" permission, or something along those lines.

**Comment by michael-s-molina** [comment]
Closing this as 2.x versions are not supported anymore. Feel free to continue the conversation in case @rusackas's suggestion does not resolve your problem. I hope it does 🤞🏼

**Comment by prb219** [comment]
Hi @rusackas I am not seeing the disclosure triangle as you correctly mentioned and I think it is a permission issue too. I have the following permissions enabled for this admin user which is all the options i see for Dataset in https://github.com/apache/superset/blob/master/RESOURCES/STANDARD_ROLES.md 

**Permissions currently assigned:** 
can read on Dataset
can write on Dataset
menu access on Datasets
can export on Dataset
can duplicate on Dataset
can get or create dataset on Dataset

**Comment by rusackas** [comment]
Are you still running Superset 2.x?

**Comment by prb219** [comment]
Yes, running 2.1.0. Strangely I remember this option was available when we first on boarded to 2.1.0 as we had to create some new datasets which takes time column in epoch.

**Comment by prb219** [comment]
@rusackas Any suggestions here ? It would be very helpful If I could get some guidance on the permission that affects this particular functionality.

**Comment by rusackas** [comment]
Not really sure... I'm curious if this is still an issue in 3.0/3.1, but if it IS a permissions issue, it probably will be.
