### ISSUE TITLE
Multiple issues with time range dashboard native filters

### ISSUE THREAD

**Issue by axoxymous-coder** [apache/superset#27075]
### Bug description

Hi Team,

I am using Superset v3.0.3, where I am encountering a bunch of weird issues:

1. Dashboard native time range filters doesn't get applied to the charts with dashboard cross filtering. Although the tool-tip shows that the filters are applied, but in the actual query those filters does not show up and hence the queries are executed without the required `WHERE` clauses. I think folks in the community has already reported this before via the below issues:

- https://github.com/apache/superset/issues/23773
- https://github.com/apache/superset/issues/25011

I followed workarounds mentioned in the comments section of #25011 and that seems to help.

2. My Dashboard has two native time range filters. After appliying the above workaround I have observed that one filter to overwrite the another. Meaning even if I specify two different range values for the filters, only one among them is taken by Superset while constructing the query. I stumbled upon the below issue which says that more than one time range dashboard filter is not supported:

- https://github.com/apache/superset/issues/23842
- https://github.com/apache/superset/discussions/24165

Is the above still true for v3.0.3? Although from what I have encountered, it seems its not supported in Superset yet.

### How to reproduce the bug

For reproducing (1), 
- Create a dataset with temporal date time columns
- Create a chart including the date time columns
- Create a dashboard with two filters based on the date time columns using time range filtering
- If you change the filters, the tool-tip will show that the filters are applied but it wont show up in the `WHERE` clause of the query (using the View Query) and hence the data will not be as filtered as desired.

For reproducing (2),
- Use the workaround mentioned in the comments section of #25011 
- If you now try changing the filter, one filter value will overwrite the other (verify using View Query)

### Superset version

3.0.3

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by sfirke** [comment]
Thanks for the bug report.  It seems to me like this is already covered by existing issues:
- #25011 for the filter not getting applied.  You mention cross-filtering, which I don't think appears in the original issue.  Does that have a specific role in this bug report?
- #24165 is the correct feature request for multiple time filters, which is not currently supported in Superset as of 3.1.0

Given that, I'm inclined to close this issue.  What do you think?
