### ISSUE TITLE
missing canvg and html2canvas dependencies when building using docker-compose

### ISSUE THREAD

**Issue by fisjac** [apache/superset#27089]
### Bug description

When building superset using docker compose, the webpack will build node_modules without optional the optional dependencies canvg and html2canvas. This results in an error message when the superset_node container runs.

### How to reproduce the bug

Navigate to superset directory and run docker compose up.

### Screenshots/recordings

![image](https://github.com/apache/superset/assets/41238731/28b34497-841d-4b08-83a3-39873a15720e)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by michael-s-molina** [comment]
Fixed by https://github.com/apache/superset/pull/27091

**Comment by fisjac** [comment]
I'm still seeing this error when running in docker
