### ISSUE TITLE
Wrong URL `/chart/list/[object%20Object]` called

### ISSUE THREAD

**Issue by fenilgmehta** [apache/superset#27097]
### Bug description

It seems at some place in the frontend raw JavaScript object is getting used for the URL.

### How to reproduce the bug

1. Login
2. Visit http://127.0.0.1:9000/dashboard/list/
3. Click on `Charts` in the navigation bar at the top
4. Network call will happen to `http://127.0.0.1:9000/chart/list/[object%20Object]`

### Screenshots/recordings

![image](https://github.com/apache/superset/assets/42742240/1f2ed321-b415-4f20-a21d-c3a51ee26289)

### Superset version

master / latest-dev

### Python version

3.11

### Node version

18 or greater

### Browser

Firefox

### Additional context

Screenshot is that of Edge browser. But, it happens on Firefox too.

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by kgabryje** [comment]
Hi @fenilgmehta! I tried to reproduce the issue on the latest master with Chrome, Firefox and Safari. As you can see on the attached video, there is no failed network call when I follow your repro steps.
I'm closing the issue as non-reproducible, but if the problem persists, feel free to reopen.

https://github.com/apache/superset/assets/15073128/b29ef77b-2be2-4072-a825-2ccc5bee44e3
