### ISSUE TITLE
ssl_cert_req is missing an "s"

### ISSUE THREAD

**Issue by pcop00** [apache/superset#27093]
### Bug description

This error on the Chart page `__init__() got an unexpected keyword argument`

should be `ssl_cert_reqs` (with an "s")

### How to reproduce the bug

Set up Superset with an external redis, but with TLS enabled. Make a chart in the UI, witness the error

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by michael-s-molina** [comment]
Fixed by https://github.com/apache/superset/pull/27094
