### ISSUE TITLE
Unable to save a query as a new dataset

### ISSUE THREAD

**Issue by a15n** [apache/superset#27105]
### Bug description

In SQL Lab I've made a query. I'm unable to "save as dataset". 

When I try to I get a tooltip popup that says "Fatal error". The devtools console shows the API call is returning 500 with this error `Failed to load resource: the server responded with a status of 500 ()     api/v1/dataset/:1`

### How to reproduce the bug

1. Visit `/sqllab/`
2. Write and run a SQL query
3. Click the down caret within the Save button
4. Click "Save dataset"
5. Select "Save as new"
6. Click the "Save & Explore" button

### Screenshots/recordings

![Devtools Screenshot](https://github.com/apache/superset/assets/7050871/86fa03de-25e0-4c41-8850-2f4af2103642)

### Superset version

3.1.0

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

I'm able to overwrite an existing dataset, just not create a new one.

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by john-bodley** [comment]
This issue was due to an internal override.
