### ISSUE TITLE
Superset import-datasources -r : No Such Option

### ISSUE THREAD

**Issue by ddxv** [apache/superset#27100]
### Bug description

Superset import datasources says there is no option `-r` despite there being the option in the docs. 

Using Python3.11 and Superset `3.1.0`

Documentation:
https://superset.apache.org/docs/miscellaneous/importing-exporting-datasources/
```
If you supply a path all files ending with yaml or yml will be parsed. You can apply additional flags (e.g. to search the supplied path recursively):

superset import_datasources -p <path> -r
```

### How to reproduce the bug

Running:
`superset import-datasources -p path/to/a/directory/nested/ymls -r`

Outputs:
```sh
Try 'superset import-datasources --help' for help.

Error: No such option: -r
```

### Superset version

3.1.0

### Python version

3.11

### Node version

Not applicable

### Browser

Not applicable

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by ddxv** [comment]
I realized that per the above documentation, exporting from UI and directly importing is not supported:

> 4. If you want to import an item that you exported through the UI, you will need to nest it inside its parent element, e.g. a database needs to be nested under databases a table needs to be nested inside a database element.

**Comment by ddxv** [comment]
@betodealmeida 

Ah, ok, I got a bit further and hit the same issue again, but this time I think it is a bug in the documentation.

In code I see support for:
`superset/cli/importexport.py`
export: `superset export_datasources -f myfile.zip` This exports to a ZIP file.
import: `superset import_datasources -p /path/to/dir/myfile.zip` This imports a ZIP file.

A leftover (which I can't seem to run from CLI): `superset legacy_import_datasources -p /path/to/dir/yamls/ -r`
 
But the documentation is still referencing the `legacy_import_datasources`. 

Would it be correct to open a PR for the documentation change:
import: `superset import_datasources -p /path/to/dir/myfile.zip` This imports a ZIP file. And remove mentions of recursive import of YAML files?

**Comment by ddxv** [comment]
@betodealmeida I also see issue #17049 that I and many others have encountered that seems docker specific, so if that has any relation to the above please let me know for the documentation update.

**Comment by michael-s-molina** [comment]
Closed by https://github.com/apache/superset/pull/27120
