### ISSUE TITLE
Docker *-dev tag's are not targetting the dev stage of Dockerfile

### ISSUE THREAD

**Issue by lodu** [apache/superset#27111]
### Bug description

the [Dockerfile contains a dev stage](https://github.com/apache/superset/blob/13f1642c73920792c3c5671ec295cc859aa0856f/Dockerfile#L106) but this is not the stage that is targeted when building and releasing the *-dev tags (e.g.: [master-dev on Docker Hub](https://hub.docker.com/layers/apache/superset/master-dev/images/sha256-b14f0ac28ad6cfabc6273f2913dc9ca7e3f26c877894a41177a8713f6e774527).

When looking on the image layers from the [Superset Docker image with tag `master-dev`](https://hub.docker.com/layers/apache/superset/master-dev/images/sha256-b14f0ac28ad6cfabc6273f2913dc9ca7e3f26c877894a41177a8713f6e774527): Layer 29 corresponds to [Dockerfile L103](https://github.com/apache/superset/blob/13f1642c73920792c3c5671ec295cc859aa0856f/Dockerfile#L103) and Layer 30 corresponds to [L141](https://github.com/apache/superset/blob/13f1642c73920792c3c5671ec295cc859aa0856f/Dockerfile#L141) . Anything between those is not present in the *-dev containers (which is the entire dev stage). For example: package libx11-xcb1 does not exist (`docker run apache/superset:3.1.0-dev apk -e info libx11-xcb1`)

### How to reproduce the bug

We first noticed this bug due to geckodriver not working on the *-dev images, so I am using that as an example.

1. Locate executable for geckodriver on a *-dev Docker image:  `docker run apache/superset:3.1.0-dev which geckodriver`  
this does not return a value, but as [per docs it should](https://superset.apache.org/docs/installation/alerts-reports/#check-web-browser-and-webdriver-installation).  

Now what we expect:
1. Git clone the repo  
2. Build the Docker image while using the `dev` stage as the target stage: `docker build -t superset-dev:latest --target dev .` (you can remove a lot of the frontend stuff to increase building speed fyi).
3. Then check the location of geckodriver's executable on that image: `docker run superset-dev:latest which geckodriver`, this returns `/usr/local/bin/geckodriver` (as expected).

### Screenshots/recordings

Result:
![image](https://github.com/apache/superset/assets/48859312/2328dedf-ebc5-4a2d-84e3-32044977ad5d)

Other packages that should be installed on target dev stage.
![image](https://github.com/apache/superset/assets/48859312/23bc6ce8-3961-40c9-ab9d-aa59f3cdc878)

Expected results:
![image](https://github.com/apache/superset/assets/48859312/d81d1114-7832-4cef-8765-99ed2870500f)
![image](https://github.com/apache/superset/assets/48859312/d6cf52a3-e880-4589-b776-2986fd6fcfce)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Not applicable

### Additional context

[Slack discussion.](https://apache-superset.slack.com/archives/C015WAZL0KH/p1707901999901729?thread_ts=1707628146.437669&cid=C015WAZL0KH) Earlier messages in thread are not that relevant.

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by lodu** [comment]
I think the fix is super simple: use [this variable](https://github.com/apache/superset/blob/13f1642c73920792c3c5671ec295cc859aa0856f/scripts/build_docker.py#L182).

**Comment by giftig** [comment]
Just for reference, a related slack discussion: https://apache-superset.slack.com/archives/C015WAZL0KH/p1707628146437669

There's a unit test for this in `tests/unit_tests/scripts/docker_build.py`, so that'll be the best bet for testing this I think.

**Comment by lodu** [comment]
> [...] `docker_build.py`, so that'll be the best bet for testing this I think.

Thanks, I fixed that one just now.
I cannot test the actions I think unless I set up the entire Github Actions to publish to a new Docker hub repo.

**Comment by lodu** [comment]
I just created a PR, when a maintainer approves the workflow for building the dev image (`docker-build (dev, linux/amd64)`) I can actually check in the container whether the issue is fixed.

**Comment by mistercrunch** [comment]
Thanks for the PR @lodu , merged!

**Comment by rusackas** [comment]
Not sure if we should close this now since the PR merged, or close it when the builds are complete, but feel free to close when it's appropriate, and thanks for the help here @mistercrunch !

**Comment by mistercrunch** [comment]
Should be all set, closing!
