### ISSUE TITLE
Superset Row Limit - not updating in web ui

### ISSUE THREAD

**Issue by shubhshah01** [apache/superset#27115]
### Bug description

Even after setting ROW_LIMIT and SQL_MAX_ROW in the config file at /app/superset_config.py file the row limit is not increasing while creating charts.
```
SQL_MAX_ROW = 10000000
ROW_LIMIT = 10000000
```
How do i increase the row limit in superset ?

### How to reproduce the bug

1. add  **_SQL_MAX_ROW = 10000000_** and **_ROW_LIMIT = 10000000_** in mounted config file or directly inside container at /app/superset_config.py file
2. Go to Charts
3. Create charts
4. select any datasource and table chart
5. select any dimension
6. Scroll down and for ROW LIMIT dropdown enter 500000 

### Screenshots/recordings

![image](https://github.com/apache/superset/assets/122277028/ccc05ae2-c36a-4106-9443-e7f7cbce167b)

### Superset version

3.1.0

### Python version

3.9

### Node version

18 or greater

### Browser

Chrome

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by michael-s-molina** [comment]
Hi @shubhshah01. This was fixed by https://github.com/apache/superset/pull/26807 and it will be included in 3.1.1 which is currently being voted and should be available next week.
