### ISSUE TITLE
Remove Python 3.9 support

### ISSUE THREAD

**Issue by fenilgmehta** [apache/superset#27110]
### Bug description

I see that `superset/utils/core.py` and very likely many other code files are using the `New Type Union Operator` (sample code [reference](https://github.com/apache/superset/blob/13f1642c73920792c3c5671ec295cc859aa0856f/superset/utils/core.py#L1792) for `core.py`) which was introduced in `Python 3.10` ([source](https://docs.python.org/3.10/whatsnew/3.10.html#pep-604-new-type-union-operator)). But, `setup.py` and multiple other places in the repository and docs say that 3.9 is supported (`setup.py` [reference](https://github.com/apache/superset/blob/13f1642c73920792c3c5671ec295cc859aa0856f/setup.py#L210)).

### How to reproduce the bug

Refer the bug description for the details of the issue.

### Superset version

master / latest-dev

### Python version

Not applicable

### Node version

Not applicable

### Browser

Not applicable

### Additional context

I believe we should raise the minimum supported Python version to `3.10`.

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by michael-s-molina** [comment]
The New Type Union Operator can be used in Python 3.9 with `from __future__ import annotations`. Check https://peps.python.org/pep-0563/ for more context. Closing this but please reopen if any questions remain.
