### ISSUE TITLE
Table list becoming buggy in sql lab when there is a table view

### ISSUE THREAD

**Issue by shauryagoel** [apache/superset#27123]
### Bug description

I have installed superset v3.0.1 using the helm chart v0.10.11 on GKE. I recently encountered a UI issue (attached below) in sqllab, using a doris database connection and when viewing the table list. Tables names become overlapping as can be seen. `assignator_store_data` is a view in our db and the rest are tables(~15). If I select any of the `assignator_store_data`, I still get data only related to `assignator_store_data` in the data preview. This is the first time we have used a view and got this issue, previously there were only tables in our database and there were no such issue.

### How to reproduce the bug

1. Go to sqllab
2. Select a doris connection
3. Select the desired db/schema which has a view
4. Scroll the list of tables up and down

### Screenshots/recordings

https://github.com/apache/superset/assets/6321314/fbc398c9-a23c-4f1a-a1cb-fd3177d9cb60

### Superset version

3.0.3

### Python version

3.9

### Node version

Not applicable

### Browser

Chrome

### Additional context

My data source is in Doris.

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Hi there! Sorry nobody has corroborated your issue, but we're no longer supporting Superset 3.0.x. If you can repro this issue in 3.1 or better yet 4.x, we can certainly re-open it. Otherwise, I would have probably closed this as stale anyway. Have you found a workaround or any other context you can provide? Thanks!
