### ISSUE TITLE
Supserset Forbidden on SQLLab

### ISSUE THREAD

**Issue by aavanzyl** [apache/superset#27141]
### Bug description

When I upgraded from 3.0.1 to 3.1.0, the following occurred. 

Users were no longer able to access the SQL Lab editor. They received a Forbidden popup on the right side corner. On further investigation, I found that [this pr ](https://github.com/justinpark/superset/commit/4c5b8ab3898ad1eecc7646f84e1050bdcdb49e2d#diff-bcb3868b9e29aea5f6e87ec641120dae35a86d732501f488a7a6dbdeb450f5c1) was the culprit. A new permission was added, however, the migration was not added to enable the new permission. 

I manually added the permission of `can read on SQLLab` in our superset postgres database, applied this permission to the SQL lab permission role. This resolved the issue. So essentially, we are just missing the migration script. 

### How to reproduce the bug

Access SQL Lab on 3.1.0

### Screenshots/recordings

<img width="1042" alt="Screenshot 2024-02-16 at 13 37 35" src="https://github.com/apache/superset/assets/23451086/9a09b4c0-05e3-480d-bffb-4c8fb3c62e71">

### Superset version

3.1.0

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by justinpark** [comment]
Hello @aavanzyl,
With the introduction of SQL Lab SPA migration in Superset 3.1, it's necessary to update the roles for the new SPA resources to ensure uninterrupted service. Just a friendly reminder that, as part of the deployment process and not limited to this case, it's important to execute the 'superset init' command. This initializes Superset and helps set up the required roles and permissions for all users.
Thank you!
