### ISSUE TITLE
shillelagh error: 'str' object has no attribute 'items' in superset

### ISSUE THREAD

**Issue by weeebdev** [apache/superset#27151]
### Bug description

When I try to connect to json api like https://www.boredapi.com/api/activity?participants=1,
it returns me "shillelagh error: 'str' object has no attribute 'items'"

### How to reproduce the bug

Install superset with shillelagh
Try to do an api request
Expected behavior
Normal api response

### Screenshots/recordings

<img width="1067" alt="image" src="https://github.com/apache/superset/assets/48881444/e78d7d68-2723-4599-942d-c95f24a1abac">

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

Also, I created the same issue in shillelagh repo https://github.com/betodealmeida/shillelagh/issues/430
My settings
```json
{
  "connect_args": {
    "adapters": [
      "genericxmlapi",
      "genericjsonapi",
      "datasetteapi",
      "weatherapi"
    ],
    "adapter_kwargs": {
      "weatherapi": { "api_key": "API_KEY" },
      "genericjsonapi": {
        "request_headers": {
          "Content-type": "application/json"
        }
     }
    
}
```

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by betodealmeida** [comment]
This is exclusively a shillelagh bug, I'll follow up on the other ticket.
