### ISSUE TITLE
🐛 Assigning roles to users lead to integrity error message

### ISSUE THREAD

**Issue by hanslemm** [apache/superset#27172]
### Bug description

When trying to assign any new role to a user, a `Integrity error, probably unique constraint` error pops up in the UI.

### How to reproduce the bug

1. Go to list users
2. Edit a user
3. Add a new role to the user
4. Hit save
5. UI lands in list users
6. Error pops up

### Screenshots/recordings

![image](https://github.com/apache/superset/assets/32077629/b2c5a1a9-b98a-42e2-8b72-bf3369a94638)

### Superset version

3.1.0

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by hanslemm** [comment]
FYI @rusackas

**Comment by hanslemm** [comment]
Hey @michael-jordan-23, danke für den Tipp, aber das Problem ist, dass meinem Superset Benutzers sein sollten, es zu ändern. 

Kürzlich habe ich Superset auf 3.1.1 aktualisiert, was das Problem anscheinend behoben hat, aber ich beobachte es immer noch.

**Comment by michael-jordan-23** [comment]
@hanslemm ich hab eine leichte Vermutung, dass das created_on (bzw. changed_on) bei Nutzer Erstellung nicht/falsch gesetzt wird. Im "nächsten" Schritt wird das created_on erwartet, gibt es aber nicht (bzw. im erwartetem Format).

Ich weiß noch nicht ob ich das lösen muss für unsere Zwecke, da wir in der Regel nur per DB Nutzer erstellen.

Falls ich die Lösung finde(n muss), teile ich sie hier.

Falls Du das schaffst, ping mich gerne ich freue mich :)

**Comment by rusackas** [comment]
If this was indeed fixed in 3.1, I think we should close this. If you're still seeing it in 3.1 or 4.x, I'm more than happy to re-open it.

**Comment by etadelta222** [comment]
I'm on 3.1.2 and just ran into this issue @rusackas . I was trying to add role to an existing user. I can manually do an insert in the ab_user_role table but we have other users who need to use the UI to do this.
