### ISSUE TITLE
report exception (email-chart-text)

### ISSUE THREAD

**Issue by liangliangGit** [apache/superset#27222]
### Bug description

I have set up a scheduled report to send emails, where the report specifies the text mode for charts. If the chart results contain no data, the email will not be sent. However, if the chart results do include data, the email will be sent as expected.

In cases where the chart returns no data, the email can still be successfully sent when both CSV and PNG model are selected for the chart.

### How to reproduce the bug

1.go to report
2.choose chart
3.choose Send As Text
4.schedule email to be sent at a specific time.

### Superset version

3.0.4

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
I was tempted to close this out as stale, but I'll just ping @yousoph @eschutho to see if this is something we want to look into.
