### ISSUE TITLE
Server-side session cookie is set for each healthcheck (request to /health)

### ISSUE THREAD

**Issue by andy-clapson** [apache/superset#27251]
### Bug description

When server-side session are enabled, a session cookie is set and returned on calls to the `/health` route. If there are regular healthchecks being done this can easily fill up server-side cache storage.

### How to reproduce the bug

1. docker compose up
2. set server-side cookie cache to redis (`SESSION_SERVER_SIDE`)
3. curl `<superset_baseurl>/health`
4. check response to see session cookie

### Superset version

3.1.1

### Python version

3.10

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by michael-s-molina** [comment]
Hi @andy-clapson. I believe this issue should be reported on the Flask App Builder repository given that Superset is only consuming that feature. @dpgaspar Please correct me if I'm wrong.

**Comment by andy-clapson** [comment]
> Hi @andy-clapson. I believe this issue should be reported on the Flask App Builder repository given that Superset is only consuming that feature. @dpgaspar Please correct me if I'm wrong.

ah! yes, of course. That is fair. I can do that. I'll wait to hear the yay/nay from @dpgaspar

**Comment by rusackas** [comment]
Hi @andy-clapson - just wondered if you heard back from @dpgaspar on this, or if you think we still want to keep this on Superset (if indeed a FAB Issue is more fitting). Just trying to clear up the backlog if we can ;)

**Comment by andy-clapson** [comment]
> Hi @andy-clapson - just wondered if you heard back from @dpgaspar on this, or if you think we still want to keep this on Superset (if indeed a FAB Issue is more fitting). Just trying to clear up the backlog if we can ;)

I can go ahead a move this to FAB instead as I think you guys are right on the money there. good to close!

**Comment by rusackas** [comment]
Thanks, @andy-clapson! Keep us posted on how it goes :D
