### ISSUE TITLE
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused

### ISSUE THREAD

**Issue by Musa10** [apache/superset#27267]
### Bug description

Cannot connect to superset_cache container from superset_app container..although didn't change any thing in docker compose

### How to reproduce the bug

1. run docker compose up

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by michael-s-molina** [comment]
Do you have another Redis instance running locally that would prevent the Docker one from running? Can you share the docker initialization logs?

**Comment by rusackas** [comment]
Closing as stale. I assume you've either fixed this or moved on, but holler if there's still a bug to be dealt with. Docker has smoothed out quite a bit, so I hope/assume all is well.
