### ISSUE TITLE
> I am still getting the same error even after applying all the configurations.

### ISSUE THREAD

**Issue by Rudneer** [apache/superset#27350]
> I am still getting the same error even after applying all the configurations.
> 
> I have tried setting `SESSION_COOKIE_SAMESITE = "None" ` and `SESSION_COOKIE_SAMESITE = None `. I am using HTTPS and I don't want to disable CSRF. I am getting below error
> 
> ```
> "{\"errors\": [{\"message\": \"400 Bad Request: The CSRF session token is missing.\", \"error_type\": \"GENERIC_BACKEND_ERROR\", \"level\": \"error\", \"extra\": {\"issue_codes\": [{\"code\": 1011, \"message\": \"Issue 1011 - Superset encountered an unexpected error.\"}]}}]}
> ```
> 
> It is working fine when i am trying to call API from Postman. However, in the app, I keep getting the same error. I have also attached `"Referer"=>"https://mydomain/api/v1/security/csrf_token/`.

In the "app", when you get the CSRF Token, it responds with a Set-Cookie header alongside the token. You need to use that same cookie when requesting the guest token.

Depending on how you're doing the requests, if you create a "client" that does all of the requests it'll probably store the cookies automatically. If not, you need to add the cookies in manually.

_Originally posted by @Alvie in https://github.com/apache/superset/issues/8382#issuecomment-1690197367_
            I am passing the set-cookie from headers of csrf token and passing it in headers on guest_token, even so i am getting the same error. It seems it works for php but doesn't work for python.
            Even in php i am getting a new error,
            {"errors": [{"message":"400 Bad Request: The referrer header is missing.","error_type":"GENERIC_BACKEND_ERROR"

**Comment by rusackas** [comment]
I'm equally baffled... if a bug report isn't something we can understand and reproduce to troubleshoot, we'll likely have to close it.

**Comment by Alvie** [comment]
> I'm equally baffled... if a bug report isn't something we can understand and reproduce to troubleshoot, we'll likely have to close it.

I'm also confused and I've been tagged into this conversation somehow. I think the issue creator needs help with the guest token generation process but is confused. I tried to help them in the previous ticket (because it was somewhat relevant).

It seems they may have solved the CSRF issue mentioned in the previous issue, but have a new issue. As it's not a bug report, I think it's likely they have something configured incorrectly in their client code.

**Comment by rusackas** [comment]
Ok... closing this until we get more clarity. Happy to revisit/reopen as needed.
