### ISSUE TITLE
Timerange filter empty result

### ISSUE THREAD

**Issue by netliteIT** [apache/superset#27382]
### Bug description

Importing a public data set or using a dataset on an external DB using  "ts" TIMESTAMP WITH TIME ZONE, works fine but using wizard to manage a simple timerange produce an empty result.

### How to reproduce the bug

Follow the first steps of the guide:
https://preset.io/blog/timeseries-cratedb-superset/
CREATE TABLE IF NOT EXISTS "doc"."power_consumption" (
   "ts" TIMESTAMP WITH TIME ZONE,
   "Global_active_power" REAL,
   "Global_reactive_power" REAL,
   "Voltage" REAL,
   "Global_intensity" REAL,
   "Sub_metering_1" REAL,
   "Sub_metering_2" REAL,
   "Sub_metering_3" REAL,
   "meter_id" TEXT,
   "location" GEO_POINT,
   "city" TEXT
)
CLUSTERED INTO 4 SHARDS

Populated with sample data.

Now set a filter on ts like that:
![immagine](https://github.com/apache/superset/assets/5641820/82fa1d66-b3f2-4f4b-919f-5c799212a04f)

Looks like the generated query has a .0 at the ond of timestamps which is not understood by internal superset engine and by external DB.

This is the query generated by SuperSet:

SELECT DATE_TRUNC('day', ts) AS ts,
       sum("Global_active_power") AS "SUM(Global_active_power)"
FROM doc.power_consumption
WHERE ts >= 1172707200000.0
  AND ts < 1206748800000.0
GROUP BY DATE_TRUNC('day', ts)
ORDER BY "SUM(Global_active_power)" DESC
LIMIT 10000

I've tested on external CrateDB and on imported data.
The result is the same.

### Superset version

3.1.1

### Python version

3.9

### Node version

16

### Browser

Firefox

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by hlcianfagna** [comment]
I am thinking that perhaps we need a `(...)::BIGINT` in
- https://github.com/apache/superset/blob/56a6660c167eb64208b6923eddda616ae37cd3f7/superset/db_engine_specs/crate.py#L49
- https://github.com/apache/superset/blob/56a6660c167eb64208b6923eddda616ae37cd3f7/superset/db_engine_specs/crate.py#L62
- and perhaps also https://github.com/apache/superset/blob/56a6660c167eb64208b6923eddda616ae37cd3f7/superset/db_engine_specs/crate.py#L53
It needs to be tested

**Comment by hlcianfagna** [comment]
cc @Vitor-Avila re https://preset.atlassian.net/browse/PPR-714
