### ISSUE TITLE
Embedded dashboard error is always in English

### ISSUE THREAD

**Issue by Ralkion** [apache/superset#27426]
### Bug description

If a failure occurs while attempting to load an embedded dashboard, the error message displayed is always in English.

In the example below, the guest token is invalid. The server is configured to only use French (as laid out in the reproduction steps).

### How to reproduce the bug

Reproduction steps below utilize docker-compose, based on the current master branch.

1. Create the local config file (docker/pythonpath_dev/superset_config_docker.py), and configure it to use French:
```python
LANGUAGES = {
    "fr": {"flag": "fr", "name": "French"}
}

SECRET_KEY="password1234"
FEATURE_FLAGS = {"ALERT_REPORTS": True, "EMBEDDED_SUPERSET": True}
BABEL_DEFAULT_LOCALE = "fr"
```
2. Modify your nginx config file (docker/nginx/nginx.conf) to allow for embedding
```
# Inside http > server > location /
# Add the following lines:
            proxy_hide_header   X-Frame-Options;
            add_header X-Frame-Options ALLOWALL always;
```
3. `docker-compose up`
4. Wait for `superset_init` to load the examples DB (takes some time)
5. Create a local web-server that can host an HTML file (I used live server in VS Code). Take note of the port that will be used by the web-server (in my case, `:5500`).
6. Open up superset in your `http://localhost` and login. Observe that the site is displayed in French (as configured).
7. Pick any dashboard. Open the Embedding dialog via the dashboard options `... > Embed Dashboard` button.
8. Allow the local webserver to embed the dashboard by entering it in the text field (in my case, `http://127.0.0.1:5500`), then click "Save Changes". Take note of the generated UUID for the dashboard.
9.  Create the following HTML file in your local web-server (be sure to replace the UUID in the options):
```html
<html>
<head>
</head>
<body>
  <div class="container" id="container"></div>

  <script src="https://unpkg.com/superset-embedded-sdk"></script>
  <script>
    supersetEmbeddedSdk.embedDashboard({
      id: '<insert embedded id here>', // given by the Superset embedding UI
      supersetDomain: 'http://localhost',
      mountPoint: document.getElementById('container'), // any html element that can contain an iframe
      fetchGuestToken: () => 'asdfasdcad', // guest_token
      dashboardUiConfig: {
        urlParams: {
          lang: 'fr'
        }
      } // dashboard UI config: hideTitle, hideTab, hideChartControls (optional)
    });
  </script>
</body>
</html>
```
10. Open your local webserver `http://127.0.0.1:5500` and observe the English error message.

### Screenshots/recordings

![image](https://github.com/apache/superset/assets/90489859/710b138f-204a-4d93-bf94-58243cef76e9)

![image](https://github.com/apache/superset/assets/90489859/eb435e5a-878c-4d60-b33d-4127607a6f85)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

The code is actually hard-coded to use English. However I have a patch that I'll be creating (to be linked shortly) to fix this, and it still doesn't solve the problem.

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by Ralkion** [comment]
The related PR adds the translatable strings, but does not solve the issue. Even with the translation function added, and the translation strings defined, the error still exists.

**Comment by rusackas** [comment]
At risk of duplicating efforts, I opened a similar PR here using the latest translation scripts, which have been revised a bit since this was opened. Wish me luck!
https://github.com/apache/superset/pull/29782
