### ISSUE TITLE
After successfully logging in, you can view the user's plaintext password via F12 (Developer Tools).

### ISSUE THREAD

**Issue by Eamon6221** [apache/superset#27435]
### Bug description

![image](https://github.com/apache/superset/assets/37013513/43e6521c-1268-4059-bbef-11e1a1a4e19b)

### How to reproduce the bug

1.go to login page and input username、password，and submit "Sign IN"
2.Press F12 to open (Developer Tools) on welcome page

### Superset version

3.0.4

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by dpgaspar** [comment]
This is normal since your viewing your own payload on sent by the form POST on the developer tools.
Feel free to reopen if this is not the case
