### ISSUE TITLE
Mixed time series chart throw error with Elasticsearch backend

### ISSUE THREAD

**Issue by sowo** [apache/superset#27463]
### Bug description

After upgrading to 4.0.0rc1, Mixed Timeseries charts throw and error

Error: Error (parsing_exception): {'error': {'root_cause': [{'type': 'parsing_exception', 'reason': "line 1:8: extraneous input '{' expecting {'(', 'ALL', 'ANALYZE', 'ANALYZED', 'CASE', 'CAST', 'CATALOGS', 'COLUMNS', 'CONVERT', 'CURRENT_DATE', 'CURRENT_TIME', 'CURRENT_TIMESTAMP', 'DAY', 'DEBUG', 'DISTINCT', 'EXECUTABLE', 'EXISTS', 'EXPLAIN', 'EXTRACT', 'FALSE', 'FIRST', 'FORMAT', 'FULL', 'FUNCTIONS', 'GRAPHVIZ', 'HOUR', 'INTERVAL', 'LAST', 'LEFT', 'LIMIT', 'MAPPED', 'MATCH', 'MINUTE', 'MONTH', 'NOT', 'NULL', 'OPTIMIZED', 'PARSED', 'PHYSICAL', 'PIVOT', 'PLAN', 'RIGHT', 'RLIKE', 'QUERY', 'SCHEMAS', 'SECOND', 'SHOW', 'SYS', 'TABLES', 'TEXT', 'TRUE', 'TOP', 'TYPE', 'TYPES', 'VERIFY', 'YEAR', FUNCTION_ESC, DATE_ESC, TIME_ESC, TIMESTAMP_ESC, GUID_ESC, '+', '-', '*', '?', STRING, INTEGER_VALUE, DECIMAL_VALUE, IDENTIFIER, DIGIT_IDENTIFIER, QUOTED_IDENTIFIER, BACKQUOTED_IDENTIFIER}"}], 'type': 'parsing_exception', 'reason': "line 1:8: extraneous input '{' expecting {'(', 'ALL', 'ANALYZE', 'ANALYZED', 'CASE', 'CAST', 'CATALOGS', 'COLUMNS', 'CONVERT', 'CURRENT_DATE', 'CURRENT_TIME', 'CURRENT_TIMESTAMP', 'DAY', 'DEBUG', 'DISTINCT', 'EXECUTABLE', 'EXISTS', 'EXPLAIN', 'EXTRACT', 'FALSE', 'FIRST', 'FORMAT', 'FULL', 'FUNCTIONS', 'GRAPHVIZ', 'HOUR', 'INTERVAL', 'LAST', 'LEFT', 'LIMIT', 'MAPPED', 'MATCH', 'MINUTE', 'MONTH', 'NOT', 'NULL', 'OPTIMIZED', 'PARSED', 'PHYSICAL', 'PIVOT', 'PLAN', 'RIGHT', 'RLIKE', 'QUERY', 'SCHEMAS', 'SECOND', 'SHOW', 'SYS', 'TABLES', 'TEXT', 'TRUE', 'TOP', 'TYPE', 'TYPES', 'VERIFY', 'YEAR', FUNCTION_ESC, DATE_ESC, TIME_ESC, TIMESTAMP_ESC, GUID_ESC, '+', '-', '*', '?', STRING, INTEGER_VALUE, DECIMAL_VALUE, IDENTIFIER, DIGIT_IDENTIFIER, QUOTED_IDENTIFIER, BACKQUOTED_IDENTIFIER}"}, 'status': 400}

The query prodcued by Superset looks like this:

SELECT {func}('year',
              "DATE") AS "DATE",
             sum(X) AS "X"
...

Obviously, the {func} part in the query should be HISTOGRAM

### How to reproduce the bug

1. Create a  Mixed Timeseries chart with an Elasticsearch based dataset

### Superset version

master / latest-dev

### Python version

3.9

### Node version

I don't know

### Browser

Chrome

### Additional context

This error was produced when using the container apache/superset:4.0.0rc1

The error in the log is the same as in the opening comment. The stack trace is:

superset_app    | Traceback (most recent call last):
superset_app    |   File "/usr/local/lib/python3.9/site-packages/es/baseapi.py", line 318, in elastic_query
superset_app    |     response = self.es.transport.perform_request("POST", path, body=payload)
superset_app    |   File "/usr/local/lib/python3.9/site-packages/elasticsearch/transport.py", line 415, in perform_request
superset_app    |     raise e
superset_app    |   File "/usr/local/lib/python3.9/site-packages/elasticsearch/transport.py", line 381, in perform_request
superset_app    |     status, headers_response, data = connection.perform_request(
superset_app    |   File "/usr/local/lib/python3.9/site-packages/elasticsearch/connection/http_urllib3.py", line 277, in perform_request
superset_app    |     self._raise_error(response.status, raw_data)
superset_app    |   File "/usr/local/lib/python3.9/site-packages/elasticsearch/connection/base.py", line 330, in _raise_error
superset_app    |     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
superset_app    | elasticsearch.exceptions.RequestError: RequestError(400, 'parsing_exception', "line 1:8: extraneous input '{' expecting {'(', 'ALL', 'ANALYZE', 'ANALYZED', 'CASE', 'CAST', 'CATALOGS', 'COLUMNS', 'CONVERT', 'CURRENT_DATE', 'CURRENT_TIME', 'CURRENT_TIMESTAMP', 'DAY', 'DEBUG', 'DISTINCT', 'EXECUTABLE', 'EXISTS', 'EXPLAIN', 'EXTRACT', 'FALSE', 'FIRST', 'FORMAT', 'FULL', 'FUNCTIONS', 'GRAPHVIZ', 'HOUR', 'INTERVAL', 'LAST', 'LEFT', 'LIMIT', 'MAPPED', 'MATCH', 'MINUTE', 'MONTH', 'NOT', 'NULL', 'OPTIMIZED', 'PARSED', 'PHYSICAL', 'PIVOT', 'PLAN', 'RIGHT', 'RLIKE', 'QUERY', 'SCHEMAS', 'SECOND', 'SHOW', 'SYS', 'TABLES', 'TEXT', 'TRUE', 'TOP', 'TYPE', 'TYPES', 'VERIFY', 'YEAR', FUNCTION_ESC, DATE_ESC, TIME_ESC, TIMESTAMP_ESC, GUID_ESC, '+', '-', '*', '?', STRING, INTEGER_VALUE, DECIMAL_VALUE, IDENTIFIER, DIGIT_IDENTIFIER, QUOTED_IDENTIFIER, BACKQUOTED_IDENTIFIER}")

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
@sowo I see on your PR, you mention it was just a limitation, and the fix saw not relevant. Is this bug still relevant, or is this just a column type issue in your dataset? It sounds like this was just a schema problem, so I'll close it out, but let me know if this needs to be revisited/reopened.
