### ISSUE TITLE
deck.gl Multiple Layers chart not rendering

### ISSUE THREAD

**Issue by goto-loop** [apache/superset#27474]
### Bug description

In Superset 3.1.1 (and also the current master), the deck.gl Multiple Layers visualization seems to be broken; it only displays an error message:
```
Unexpected error
An error occurred while rendering the visualization: ReferenceError: module is not defined
```

I've noticed there's a 404 in the logs whenever I try to create the chart, not sure if this is relevant:
```
2024-03-12 11:27:06,377:INFO:werkzeug:127.0.0.1 - - [12/Mar/2024 11:27:06] "GET /api/v1/chart/0 HTTP/1.1" 404 -
```

### How to reproduce the bug

1. Create a new deck.gl Multiple Layers chart using the long_lat dataset
2. Select "Deck.gl Scatterplot" and "Deck.gl Screen grid" example charts
3. Click UPDATE CHART

### Screenshots/recordings

![image](https://github.com/apache/superset/assets/102797966/6b17ae0e-2159-4f71-a1b0-1fd27a1dac84)

### Superset version

3.1.1

### Python version

3.11

### Node version

16

### Browser

Firefox

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Hmmm... I can't seem to reproduce this issue currently. Things are working. The results pane doesn't look so hot, but that's a separate issue. 

<img width="778" alt="image" src="https://github.com/user-attachments/assets/29d7461f-24c6-430e-8e34-fb6e72168d46">
