### ISSUE TITLE
Graph and pie chart is not displayed properly 

### ISSUE THREAD

**Issue by Dinesh2019** [apache/superset#27472]
### Bug description

Pie chart is not displayed as expected for example if we have the pie chart for gender which has the data 20 males 10 female and 1 other then other I displayed as an extra line below the chart also if we apply a filter the gender which as the high value color Is displayed as others color The pie other 

### How to reproduce the bug

1. Login to superset
2. see the pie chart and which as the percentage 

version : 2.0.1

### Screenshots/recordings

https://github.com/apache/superset/assets/127730126/1550bafd-742a-4304-8ef4-0bdb31574d0f

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by michael-s-molina** [comment]
@Dinesh2019 is this reproducible in a supported version? 2.x versions are not supported anymore.

**Comment by michael-s-molina** [comment]
Closing the issue as I believe this problem does not happen anymore on current supported versions. Let us know if that's not the case.
