### ISSUE TITLE
HTML attributes being eliminated - Customizing Colors in Markdown Widgets not working

### ISSUE THREAD

**Issue by goldman7911** [apache/superset#27485]
## Screenshot

[drag & drop image(s) here!]

![image](https://github.com/apache/superset/assets/57152650/21a247cf-5ef9-4bb4-8075-fbce96020a15)
![image](https://github.com/apache/superset/assets/57152650/80dccac8-4f67-4d50-a9ad-78b48e6e119d)
![image](https://github.com/apache/superset/assets/57152650/b7bc8ef2-5848-40dc-9989-c00b55d56091)

## Description

[describe the issue here!]
Following a basic markdown styling as bellow:

https://www.restack.io/docs/superset-knowledge-superset-markdown-color-guide

The only attribute being accepted is ID and it is changed when rendered. For instance, 

`<dt id='teste' style="color:red">Firefox</dt>`

the only way for that to work is by live css and use the id "user-content-XXX" that is auto generated based on my id

```
#user-content-teste {
  color: red;
}
```

All other atributes are eliminated.

## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

**Comment by rusackas** [comment]
In your `config.py` file, you can configure which attributes you want to allow on which tags. It's locked down by default for security purposes, but if you want to punch holes, that's up to you :)

It's right around these comments, where you can see some example config:
```
# HTML_SANITIZATION_SCHEMA_EXTENSIONS = {
#   "attributes": {
#     "div": ["style"],
#   },
```

I'll close this out in hopes it answers your question, but we can reopen if there's more to deal with :D
