### ISSUE TITLE
The subtotal in the pivot table doesn't correct or the row item doesn't happen due to the pagination feature

### ISSUE THREAD

**Issue by ngtduc693** [apache/superset#27490]
### Bug description

The subtotal in the pivot table doesn't correct or the row item doesn't happen due to the pagination feature

### How to reproduce the bug

1. Create the pivot table with the large dataset
2. Set limit is 1000 or 10000 or any value

-> The subtotal in the pivot table doesn't correct or the row item doesn't happen in the group
I guess the pagination feature (limit) leads to this issue, the subtotal value will not calculate whenever the item doesn't exist on the page

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
This is at risk of being closed as stale, probably because of lack of reproducibility. Can you provide an example with screenshots, using example datasets? If we can reproduce it, we'll have a better chance of addressing it :)

**Comment by rusackas** [comment]
Closing as stale... happy to reopen if people are still facing this and can provide more details
