### ISSUE TITLE
Unable to create database connection, error: "GENERIC_DB_ENGINE_ERROR"

### ISSUE THREAD

**Issue by EuphoriaCelestial** [apache/superset#27525]
### Bug description

I am using this Superset API to create database connections: `POST {{host}}/api/v1/database/ `
Previously it works fine, I was able to create connection with ease. But now it give this error:
`"message": "(builtins.NoneType) None\n[SQL: error 404: b'<html>\\r\\n<head><title>404 Not Found</title></head>\\r\\n<body>\\r\\n<center><h1>404 Not Found</h1></center>\\r\\n<hr><center>nginx</center>\\r\\n</body>\\r\\n</html>\\r\\n']\n(Background on this error at: https://sqlalche.me/e/14/dbapi)",
            "error_type": "GENERIC_DB_ENGINE_ERROR",`

My trino version in pip: 0.328.0
SQLAlchemy:  1.4.36
Python 3.9
Ubuntu 20.04
All running in virtualenv 

### How to reproduce the bug

1. Send a request to /api/v1/database/
Payload:
`{
  "configuration_method": "sqlalchemy_form",
  "database_name": "Test DB",
  "engine": "trino",
  "expose_in_sqllab": true,
  "extra": "{\"allows_virtual_table_explore\":true}",
  "sqlalchemy_uri": "trino_connection_string"
}`

2. Get error

### Screenshots/recordings

Error message:
`{
    "errors": [
        {
            "message": "(builtins.NoneType) None\n[SQL: error 404: b'<html>\\r\\n<head><title>404 Not Found</title></head>\\r\\n<body>\\r\\n<center><h1>404 Not Found</h1></center>\\r\\n<hr><center>nginx</center>\\r\\n</body>\\r\\n</html>\\r\\n']\n(Background on this error at: https://sqlalche.me/e/14/dbapi)",
            "error_type": "GENERIC_DB_ENGINE_ERROR",
            "level": "error",
            "extra": {
                "engine_name": "Trino",
                "issue_codes": [
                    {
                        "code": 1002,
                        "message": "Issue 1002 - The database returned an unexpected error."
                    }
                ]
            }
        }
    ]
}`

### Superset version

master / latest-dev

### Python version

3.9

### Node version

I don't know

### Browser

Not applicable

### Additional context

Additional information: if I pass an invalid trino connection string on purpose, it still can regconized it and tell me to check the string

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
@EuphoriaCelestial sorry this slipped under the radar, but are you still facing this? I'm assuming not, so I'll go ahead and close it, but if you are, we can re-open it, move it to a Discussion, and ask our AI for a little help here ;) Let us know if it's still an issue!
