### ISSUE TITLE
API call (csstemplateasyncmodelview/api/read) fails with 401 in "Embedded Dashboard/IFrame" for token obtain by Admin User or any other user

### ISSUE THREAD

**Issue by viveknalawade-sgtradextech** [apache/superset#27529]
### Bug description

We are embedding the superset dashboard in one of our sites. When the user clicks on the dahsboard menu (3 dot option on top right corner), he gets 401 error for "csstemplateasyncmodelview/api/read" GET API call. 

Everything else on the dashboard loads properly with all the data. Just this one error shows.

We are generating a guest token in the backend, and using this guest token to load the the superset dashboard within the Iframe in our portal.

Initially we thought it's a permission issue, but even if I use "Admin" user to generate the guest token we face same issue.

### How to reproduce the bug

1. Load superset dashboard in iframe with Guest Token 
2. Try to access(click on 3 dots) dashboard menu within Iframe.

### Screenshots/recordings

[superset-dashboard-error.pdf](https://github.com/apache/superset/files/14612274/superset-dashboard-error.pdf)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Hi there... since this bug is (a) seemingly stale and (b) pre-dating the Superset 4.0 release (now the currently oldest supported version), we'll close this as stale officially. If you're still facing this with Superset 4.0/4.1, we can revisit/reopen this, but clearly we're not getting a lot of corroboration/attention here, so we might need additional repro/setup steps, error details, etc.
