### ISSUE TITLE
Chart Holder Full Screen is not working

### ISSUE THREAD

**Issue by sebint** [apache/superset#27561]
### Bug description

Unable to enter into Fullscreen state in chart container due to 

```
const DragDroppableStyles = styled.div`
  ${({ theme }) => css`
    position: relative;
    /*
      Next line is a workaround for a bug in react-dnd where the drag
      preview expands outside of the bounds of the drag source card, see:
      https://github.com/react-dnd/react-dnd/issues/832#issuecomment-442071628
    */
    transform: translate3d(0, 0, 0);
```
When I remove `transform: translate3d(0, 0, 0);` Its working.

Since its a fix for react-dnd, I would like to know if there are other solutions.

### How to reproduce the bug

1. Go to any dashboard.
2. Go to any chart slice in the dashboard 
3. Click on the slice control
4. Click on dropdown item "Enter fullscreen"

### Screenshots/recordings

![screenshot-localhost_8088-2024 03 19-14_22_42](https://github.com/apache/superset/assets/15358561/7f55da67-cea8-4923-bf27-a89130056c51)
**Default View**

![screenshot-localhost_8088-2024 03 19-14_22_13](https://github.com/apache/superset/assets/15358561/045e2eaa-3056-4a89-9ed3-3682bece9e9b)
**Clicked on "Enter Fullscreen"**

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by maybeyourking** [comment]
I also had the same problem.

**Comment by rusackas** [comment]
This probably isn't _related_ necessarily, but could be a "two birds, one stone" situation:
https://github.com/apache/superset/issues/24752

**Comment by sadpandajoe** [comment]
Heads up this isn't happening with 4.0rc1 from what I can tell from the ephemeral in the PR. So It's probably one of the commits that's happening afterwards.

**Comment by sadpandajoe** [comment]
relates to this PR: https://github.com/apache/superset/pull/27308 if it is `transform: translate3d(0, 0, 0);`

**Comment by rusackas** [comment]
@justinpark do you recall the specifics of that line? I'm guessing it's the GPU hack for the browser, but maybe not. If you know a reliable way to test the original bug you were chasing, I can throw some other CSS approaches at it and hopefully open a PR to fix this.

**Comment by michael-s-molina** [comment]
Fixed by https://github.com/apache/superset/pull/27613
