### ISSUE TITLE
When trying to install Superset on python3.12 I get the error:

### ISSUE THREAD

**Issue by Teesmo** [apache/superset#27585]
When trying to install Superset on python3.12 I get the error:
`AttributeError: module 'pkgutil' has no attribute 'ImpImporter'.`

I believe this can be traced back to Numpy version < 1.26.0:
https://github.com/numpy/numpy/issues/23808

Currently apache-superset is pinned to 1.23.5 while the Numpy v1.26.0 was released this past September.  Is it possible to bump numpy?

_Originally posted by @ddxv in https://github.com/apache/superset/discussions/25963_

**Comment by michael-s-molina** [comment]
Hi @Teesmo. Python 12 is not supported yet as you can see [here](https://github.com/apache/superset/blob/ad7bd09819d3fd6ac8f669c6f884551cbd66bcd6/setup.py#L216). Eventually, we'll support it and have a compatible Numpy version 😉

**Comment by amotl** [comment]
Hi. We are also blocked on this, related to the very strict version pinning on NumPy. Maybe it could be relaxed just a bit?

> Currently apache-superset is pinned to 1.23.5 while the Numpy v1.26.0 was released this past September. Is it possible to bump numpy?

> [NumPy 1.26 is available for Python 3.12](https://pypi.org/project/numpy/1.26.4/#files), so maybe upgrading to that version from NumPy 1.23 might be feasible, because it's not too different?

-- https://github.com/crate/cratedb-examples/pull/336#issuecomment-2489696461
