### ISSUE TITLE
User can access draft dashboard with permalink that established when dashboard was published

### ISSUE THREAD

**Issue by unnyns-307** [apache/superset#27588]
### Bug description

Hi all, 

I got report from our colleague when user can still access our draft dashboard which we once published it and shared dashboard's permalink with user. Normally, user shouldn't be able to access the dashboard once it was set to draft but they still able to access the dashboard with previous permalink we shared with them.  However, they might see the error prompt up at the right bottom of the screen 
Note: Users only have permission of ALPHA role 

### How to reproduce the bug

1. Go to your dashboard > set it status to '**Publish**'
2. Copy the shareable link from your dashboard setting 
3. Share dashboard link with another user who is not an owner on dashboard or doesn't has Admin privilege
4. Let user try to access dashboard through permalink *they shall be able to access
5. Switch the dashboard status to '**Draft**'  
6. Let user try to access dashboard through permalink again *they still can access the dashboard 
but they are not able to search for dashboard on the dashboard page or access dashboard with SLUG URL or dashboard URL link with only dashboard ID

### Superset version

3.0.4

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by dpgaspar** [comment]
Thank you for opening the issue, but we will close this on github, please follow: https://github.com/apache/superset/security/policy

**Comment by Habeeb556** [comment]
Hello @dpgaspar, does this issue resolved? as I still see it in `version 4.1.1 `

**Comment by rusackas** [comment]
Locking issue... please follow up via the process/link provided if needed.
