### ISSUE TITLE
Wrong color of annotation marker

### ISSUE THREAD

**Issue by aikawa-ohno** [apache/superset#27597]
### Bug description

Annotation marker color does not match the specified color.

### How to reproduce the bug

1.Create a new line chart
2.Add a new Annotations and Layers
3.Select 「Time series」 for type
4.Choose 「COLOR」
5.Check 「SHOW MARKERS」

### Screenshots/recordings

![BUG](https://github.com/apache/superset/assets/163083560/6cd4b295-b677-4331-a4e7-3f9e2d22f69d)

### Superset version

3.1.1

### Python version

3.10

### Node version

Not applicable

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Is this still happening in 4.x releases? This may be closed upon the release of 4.1 if we don't know, since 3.1 won't be supported any more.

**Comment by aikawa-ohno** [comment]
It also appears to occur in ver4.x.
However, since LineChart (legacy) seems to be discontinued in ver5, I would like to close it.
