### ISSUE TITLE
Hi @xushiyan, I'd like to add some more information here.

### ISSUE THREAD

**Issue by jayesh2424** [apache/superset#27602]
Hi @xushiyan, I'd like to add some more information here.

I have hard evidence that the delete time is not necessarily correlated with the amount of data being deleted.
_Originally posted by @dmenin in https://github.com/apache/hudi/issues/3975#issuecomment-971612278_
            
Your statement regarding the delete time is absolutely right. **I am facing the similar situation where HUDI is consistently taking longer time in my case (1 hour or more) even for write operation of 1 single row.**

**Comment by jayesh2424** [comment]
@srinisubramanian  Can you please let me know anything related to this issue for HUDI write operations consistently taking longer time ?

**Comment by michael-s-molina** [comment]
Closing the issue as it doesn't seem related to Superset.
