### ISSUE TITLE
Problem Building dev Docker image

### ISSUE THREAD

**Issue by simaolucio** [apache/superset#27606]
### Bug description

When building the Docker images on macOS, there is an issue when installing the dependencies on the Dev image.
Looks like it might be a result of #27505 

M2 Pro
macOS Sonoma 14.2.1

### How to reproduce the bug

Fresh repo clone
Before building, I pruned Docker's cache.

From the project's root dir
`docker compose build`

Output
```sh
[superset-worker dev 2/2] RUN --mount=type=bind,target=./requirements/development.txt,src=./requirements/development.txt     --mount=type=cache,target=/root/.cache/pip     pip install -r requirements/development.txt:

0.345 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements/base.txt'
```

### Superset version

master / latest-dev

### Python version

Not applicable

### Node version

Not applicable

### Browser

Not applicable

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by mistercrunch** [comment]
I was able to reproduce on `master`, submitting a PR to fix shortly. I'm surprised CI was passing, guessing something about cache and how it works around mounts (?) My PR will move towards using `COPY` to get the python requirements files on the image as opposed to mounting them. Seems more readable and easy to reason about, plus we know how cache works around simple COPY statements.

**Comment by mistercrunch** [comment]
@simaolucio this should be addressed on master now, thank you for reporting this issue!
