### ISSUE TITLE
Variables from_dttm and to_dttm are not compatible with timestamps from trino

### ISSUE THREAD

**Issue by dinoel93** [apache/superset#27621]
### Bug description

When i'm using
`WHERE timestamp > '{{from_dttm}}' AND timestamp < '{{to_dttm}}'` 
with [enabling ENABLE_TEMPLATE_PROCESSING](https://medium.com/geekculture/interactive-dashboards-in-apache-superset-ec4a3bf9bc82) on data from trino, i'm receiving:
`Error: TrinoUserError(type=USER_ERROR, name=TYPE_MISMATCH, message="line 7:21: Cannot apply operator: timestamp(3) with time zone < varchar(19)", query_id=20240322_121113_00025_2wtqh)`
I expect that  from_dttm and to_dttm variables should be in timestamp format, not in varchar.
It works well with all another datasources, only appears when trino datasource is using.
It can be fixed by:
`WHERE timestamp > parse_datetime('{{from_dttm}}','YYYY-MM-dd''T''HH:mm:ss') AND timestamp < parse_datetime('{{to_dttm}}','YYYY-MM-dd''T''HH:mm:ss')`
but it looks awkward and a little ugly.
Also the timestamp column is set to 'Is temporal' and 'Default datetime' in dataset

### How to reproduce the bug

- Setup a connection to a Trino instance
- Setup a filter inside the virtual dataset using from_dttm and to_dttm variables
- Visualize a table with a timestamp or date column
- Try to apply a date or timestamp filter
- See error

### Screenshots/recordings

![Снимок экрана от 2024-03-22 12-23-54](https://github.com/apache/superset/assets/13899853/9f0f2a8c-4bec-4292-bd34-e218f243cb5d)
![Снимок экрана от 2024-03-22 12-23-45](https://github.com/apache/superset/assets/13899853/dda227dc-f901-4bb7-8876-f146c7d85150)

### Superset version

3.1.1

### Python version

3.10

### Node version

16

### Browser

Chrome

### Additional context

A similar problem is described here https://github.com/apache/superset/issues/16223 

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by mistercrunch** [comment]
I don't think this is a bug IMHO, we can't know the target type of the column you might be using in your virtual dataset, the only thing we can to is better document what you should expect to come out of `from_dttm` and `to_dttm` (ISO) so that you can CAST it properly. Given jinja2 is a text templating framework, we have to output something as text here.

**Comment by rusackas** [comment]
Closing this as probably-not-a-bug and stale even if it is. Happy to re-open if a counter-argument is raised :D

**Comment by villebro** [comment]
FYI @dinoel93 there's a new better feature for handling temporal filters in Jinja that'll be landing in 5.0 (forthcoming). See the new `get_time_filter()` Jinja function introduced here: #30323
