### ISSUE TITLE
When added to a dashboard, Mapbox map charts do not show any data until the user interacts with the map

### ISSUE THREAD

**Issue by rudokemper** [apache/superset#27635]
### Bug description

Across a number of Superset instances, I have noticed that the Mapbox map chart type has an issue where when it is added to a dashboard, the data does not load, until the user interacts with the map by panning or zooming. There do not appear to be any errors in in the browser console or server logs about this. Additionally, none of the Mapbox chart settings (such as Live Render) seem to make a difference.

This issue does not occur when loading a Mapbox map chart in the edit chart view (e.g. in the `/explore/...` route).

### How to reproduce the bug

1. Add a MapBox map chart.
2. Add some lat/long data
3. Notice that the map in Chart Creating / Editing view does always show the data.
4. Add the MapBox chart to a dashboard.
5. Load the dashboard.
6. The chart does not show the data (only the background map of choice is shown).
7. Interact with the map by panning or zooming.
8. The data now shows.

### Screenshots/recordings

Before I interact with the map:
![image](https://github.com/apache/superset/assets/31662219/2bb625b0-73ad-46d8-80f9-a0ece02245c0)

After I interact with the map:
![image](https://github.com/apache/superset/assets/31662219/ec2bcb98-969e-420c-9606-0cc85a300d4d)

### Superset version

3.0.4

### Python version

Not applicable

### Node version

Not applicable

### Browser

Chrome

### Additional context

For the instances where I have seen this issue, they are deployed as an Azure app service using Docker (with the image `apache/superset:3.0.3`). There are no settings in `superset_config.py` that should make a difference.

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by ignasv** [comment]
Duplicate to [#27562](https://github.com/apache/superset/issues/27562)

**Comment by rudokemper** [comment]
Thanks @ignasv not sure how I missed your issue (I did search for previous ones)!
