### ISSUE TITLE
Unable to execute 'ecpg' , you likely need to install it

### ISSUE THREAD

**Issue by MihaMihavich** [apache/superset#27893]
![Снимок экрана от 2024-04-04 09-50-29](https://github.com/apache/superset/assets/113184268/267864f0-db7c-4939-8cb5-566f25a57bba)

## Description
Hello! There is a problem when i'm going to sql lab. 
I have Debian 11 with  Superset 3.1.1 and postgresql 13.13

Superset was installed in venv from pip ( python 3.9)

I checkd that all requirements installed on machine 
(libecpg-dev package installed and pip package pgsanity 0.2.9 too)

I'm try to install pgsanity 0.2.8 but have another problem, like :
![Снимок экрана от 2024-04-04 10-16-27](https://github.com/apache/superset/assets/113184268/42dcf427-8094-4acc-97ea-a3b1779e4181)

Help me please
If needed more information tell me. Thank you!

**Comment by rusackas** [comment]
Looks like @Habeeb556 has the answer, thanks! Happy to re-open if that doesn't solve it, and I encourage anyone and everyone to open a short PR to add to the Documentation if you think there's a place to stick a note and help others in the future.

**Comment by scriptmaster** [comment]
## On debian (and ubuntu):

`sudo apt install libecpg-dev`

and then verify with:
`which ecpg`

`/usr/bin/ecpg`
