### ISSUE TITLE
Extracted Translation Order

### ISSUE THREAD

**Issue by lscheibel** [apache/superset#27894]
### Bug description

Hello, I’ve noticed that when following the translations extraction process described in https://superset.apache.org/docs/contributing/translations/ the order of the items in the .pot file changes. This leads to a huge git diff, that is basically impossible to merge, even for small translation changes. Would you accept a PR that simply runs the pybabel extract command and updates the translation .pot and .po files with the what I assume to be correct order?

### How to reproduce the bug

1. Run `pybabel extract -F superset/translations/babel.cfg -o superset/translations/messages.pot -k _ -k __ -k t -k tn -k tct .` as stated [in the docs](https://superset.apache.org/docs/contributing/translations)
2. Notice how the .pot file has a long list of changes even if no new messages were added.

### Superset version

master / latest-dev

### Python version

3.10

### Node version

16

### Browser

Chrome

### Additional context

I couldn't find any information on an expected order of the translation items but went through the git history and saw that for the most part it was in a different order.

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Yes, I'd love to see a PR to that effect. Any effort to make these translations more maintainable is a win in my book. I'm far from an expert with pybabel, so every time I touch this stuff, I feel "there's got to be a better way."
