### ISSUE TITLE
Not able to connect MySQL  

### ISSUE THREAD

**Issue by prabhatjon** [apache/superset#27901]
### Bug description

Dear Members, while i am trying to connect with the MySql port is closed error coming.
![Capture](https://github.com/apache/superset/assets/3177187/c073ee2c-1a8b-4486-84de-e4b6bce03faf)
Kindly help to resolve this.

### How to reproduce the bug

1: Run the docker container 
2: Login
3: go to add database

### Screenshots/recordings

![image](https://github.com/apache/superset/assets/3177187/a33b6178-1fcc-46d3-8a8c-e0e10e8145b2)

### Superset version

master / latest-dev

### Python version

3.10

### Node version

16

### Browser

Chrome

### Additional context

While i am using given docker image i am not able to connect with MySQL

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by Thinking80s** [comment]
+1

**Comment by Thinking80s** [comment]
https://stackoverflow.com/questions/73757001/connect-superset-to-postgresql-in-a-docker-container-the-port-is-closed

**Comment by rusackas** [comment]
Are you running in docker? Just saw this come across the wire:

https://github.com/apache/superset/pull/28124

**Comment by sfirke** [comment]
Looks like that PR #28124 that Evan linked will implement the fix from @Thinking80s 's StackOverflow link (which has many upvotes) - hopefully that addresses this case.  Given the lack of response from the original poster, this should be closed when that merges.
