### ISSUE TITLE
empty result dashboard from superset APIs `/api/v1/dashboard` when the Public role has `can read on Dashboard` and `can read on Chart` .

### ISSUE THREAD

**Issue by Attachai77** [apache/superset#27917]
### Bug description

- I would like embedded a superset dashboard on my web app using [@superset-ui/embedded-sdk](https://www.npmjs.com/package/@superset-ui/embedded-sdk). so I assigned the permissions `can read on Dashboard` and `can read on Chart` to Public role
- After that the dashboard could be displayed on my app, it works for embedding the superset dashboard. 
- but APIs `/api/v1/dashboard` and `/api/v1/chart/` return result empty.  but when I remove `can read on Dashboard` and `can read on Chart`  from the Public role, It works.  
- but if I remove the permissions, the embedded dashboard won't work.

### How to reproduce the bug

1. Go to set permission for the Public role

### Screenshots/recordings

- when the Public role has `can read on Dashboard` and `can read on Chart`
    - Dashboard works
    - API does not. return empty result.
<img width="1625" alt="dash-works" src="https://github.com/apache/superset/assets/15119618/7b94e15b-2ade-4c41-96e3-9452f4576519">
     
<img width="1251" alt="api-not" src="https://github.com/apache/superset/assets/15119618/a119ac0b-dfca-48a7-82b2-9a6285315104">

- the Public role has no `can read on Dashboard` and `can read on Chart`
     - Dashboard doesn't work.
     - API work
<img width="1607" alt="dash-not" src="https://github.com/apache/superset/assets/15119618/e41c7259-3b30-48ae-8022-c618a5e95054">

<img width="1262" alt="api works" src="https://github.com/apache/superset/assets/15119618/dd5a757d-2c40-4d60-aacf-b1c1ee9037a2">

### Superset version

master / latest-dev

### Python version

3.10

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by giacomochiarella** [comment]
seems related to [this](https://github.com/apache/superset/issues/25890) issue
