### ISSUE TITLE
Drill by is disabled for Timeseries and Mixed Timeseries charts without dimensions

### ISSUE THREAD

**Issue by sowo** [apache/superset#27940]
### Bug description

Any Timeseries or Mixed Timeseries chart that does not have dimensions configured has context menu item "Drill by" disabled. Yet, "Drill by" would also be most useful to explore anomalies in these types of charts.

### How to reproduce the bug

1. Open any dashboard with dimensionless Timeseries or Mixed Timeseries charts
2. Right click on a data point in one of those charts
3. "Drill by" is not selectable

### Screenshots/recordings

Below chart shows two metrics w/o dimensions.

![image](https://github.com/apache/superset/assets/2765941/d679277e-cbeb-4cd5-bfda-3d8d9dc510a4)

### Superset version

master / latest-dev

### Python version

3.10

### Node version

18 or greater

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by sfirke** [comment]
Do this and #25334 have similar causes, since both are cases of wanting the bar chart series to act like a dimension?

**Comment by rusackas** [comment]
@sfirke looking at the PR, it seems it just opens all dimensions for drilling, which _looks_ to me like a good thing. I'm not sure if @kgabryje or @villebro see any risk on that PR, but it looks like a win. I'll spin up a test env to poke around at it.

**Comment by rusackas** [comment]
Maybe the PR will fix two PRs, who knows!?
