### ISSUE TITLE
"Unexpected error" in charts when using custom SQL column containing string with multiple dots

### ISSUE THREAD

**Issue by kenniy** [apache/superset#27957]
### Bug description

When creating a chart with a custom SQL column made up of a string containing more than one dot, such as `"google.co.uk"`, the chart fails to render with an "Unexpected error" message and `PARSE_SYNTAX_ERROR` details. 

This issue occurs specifically when creating a chart using a dataset with Databricks connection. This is primarily needed to create table columns containing clickable links, i.e. `'<a href="https://google.com.uk">google</a>'`, but the minimal example will demonstrate the error as well. 

### How to reproduce the bug

1. Set up a Connection to Databricks SQL Warehouse in Superset. See [how](https://github.com/apache/superset/discussions/23736#discussioncomment-9064362).
2. Create a dataset using the Databricks connection
3. Create a new Table chart using that dataset
4. For a Dimension, select 'Custom SQL' and enter the string `"google.co.uk"` (including the double quotes)
5. Click Update - the chart will fail to render

### Superset version

3.1.1 & 3.1.2

### Python version

3.10

### Node version

16

### Browser

Firefox

### Additional context

The same custom SQL with a multi-dot string works when:
* Using other database connections. Tested with MySQL, Postgres, Presto
* Executing the SQL directly in SQLLab with a Databricks connection (i.e. `select google.co.uk`)
* See error from local environment below 
```
2024-04-09 21:46:10,486:DEBUG:databricks.sql.thrift_backend:received thrift response: TCloseSessionResp(<REDACTED>)
2024-04-09 21:46:10,492:WARNING:superset.connectors.sqla.models:Query SELECT co.uk" AS `My column` 
FROM `examples`.`users` GROUP BY co.uk"
LIMIT 1000 on schema examples failed
Traceback (most recent call last):
  File "/app/superset/connectors/sqla/models.py", line 1795, in query
    df = self.database.get_df(sql, self.schema, mutator=assign_column_label)
  File "/app/superset/models/core.py", line 612, in get_df
    self.db_engine_spec.execute(cursor, sqls[-1])
  File "/app/superset/db_engine_specs/base.py", line 1596, in execute
    raise cls.get_dbapi_mapped_exception(ex) from ex
  File "/app/superset/db_engine_specs/base.py", line 1594, in execute
    cursor.execute(query)
  File "/usr/local/lib/python3.9/site-packages/databricks/sql/client.py", line 503, in execute
    execute_response = self.thrift_backend.execute_command(
  File "/usr/local/lib/python3.9/site-packages/databricks/sql/thrift_backend.py", line 854, in execute_command
    return self._handle_execute_response(resp, cursor)
  File "/usr/local/lib/python3.9/site-packages/databricks/sql/thrift_backend.py", line 947, in _handle_execute_response
    final_operation_state = self._wait_until_command_done(
  File "/usr/local/lib/python3.9/site-packages/databricks/sql/thrift_backend.py", line 777, in _wait_until_command_done
    self._check_command_not_in_error_or_closed_state(
�  File "/usr/local/lib/python3.9/site-packages/databricks/sql/thrift_backend.py", line 579, in _check_command_not_in_error_or_closed_state
    raise ServerOperationError(
databricks.sql.exc.ServerOperationError: 
�[PARSE_SYNTAX_ERROR] Syntax error at or near '" AS `My column` \nFROM `examples`.`users` GROUP BY co.uk"'. SQLSTATE: 42601 (line 1, pos 12)

== SQL ==
SELECT co.uk" AS `My column` 
------------^^^
FROM `examples`.`users` GROUP BY co.uk"
LIMIT 1000
```

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by shrk18** [comment]
Facing the exact same issue with 3.1.1
Is there a workaround or is this a known issue with a fix planned soon ?

**Comment by bkyryliuk** [comment]
I took a closer look into it and looks like issue happens here: https://github.com/apache/superset/blob/d80f23ed948e9f9111af7a10c4cf6708a30af1d4/superset/models/helpers.py#L872

and it is most likely databricks sqlalchemy connector bug


```
query_obj:

{'apply_fetch_values_predicate': False, 'columns': [], 'extras': {'having': '', 'where': ''}, 'filter': [], 'from_dttm': None, 'granularity': None, 'inner_from_dttm': None, 'inner_to_dttm': None, 'is_rowcount': False, 'is_timeseries': False, 'metrics': [{'aggregate': None, 'column': None, 'datasourceWarning': False, 'expressionType': 'SQL', 'hasCustomLabel': False, 'label': 'MAX(IF ts > 1000, 0.14, 0.11)', 'optionName': 'metric_9xsakmcbifl_jnw2h0nolw', 'sqlExpression': 'MAX(IF ts > 1000, 0.14, 0.11)'}], 'order_desc': True, 'orderby': [], 'row_limit': 50000, 'row_offset': 0, 'series_columns': [], 'series_limit': 0, 'series_limit_metric': None, 'to_dttm': None, 'time_shift': None}

sqla_query:

SELECT MAX(IF ts > 1000, 0.14, 0.11) AS "MAX(IF ts > 1000, 0.14, 0.11)"
FROM "default".my_table
 LIMIT :param_1


sql
SELECT 14, 0.11) AS `MAX(IF ts > 1000, 0.14, 0.11)`
FROM `default`.`my_table`
 LIMIT 50000
```

**Comment by bkyryliuk** [comment]
Fixed by https://github.com/apache/superset/pull/28393
