### ISSUE TITLE
Horizontal bar chart: too much space above the chart

### ISSUE THREAD

**Issue by visharavana** [apache/superset#27966]
### Bug description

When I use the horizontal bar chart, it shows correctly, but when I enable the legend option, it does not show correctly, like there is too much space between the legend and chart. 

Chrome itself works well.

Without legend:
![image](https://github.com/apache/superset/assets/126564878/e151657d-2783-403f-9a4e-8ffd84c3757c)
with legend:
![image](https://github.com/apache/superset/assets/126564878/aae4c7da-e55d-43ed-9fde-b209b50a85db)

### How to reproduce the bug

1. Create horizontal bar chart 
2. Enable Legend option

### Superset version

4.0.0

### Python version

3.9

### Node version

18 or greater

### Browser

Firefox

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.

**Comment by michael-s-molina** [comment]
Hi @visharavana. Do you have a margin configured?

Using the [4.0.0 test environment](http://18.246.209.142:8080/), I'm not able to reproduce this issue.

https://github.com/apache/superset/assets/70410625/9333ba6e-b9d4-4e36-85d3-33774c428b5c

Are you able to reproduce using the test environment?

**Comment by visharavana** [comment]
@michael-s-molina Sorry, it's my mistake. I didn't see the margin. Now it's working well.
