### ISSUE TITLE
Redacted

### ISSUE THREAD

**Issue by abhimittal1992** [apache/superset#27987]
Redacted

**Comment by rusackas** [comment]
I've removed the content of this issue. Please send this or any security concerns to security@superset.apache.org so we can assess/track/fix the issue in private, with you in the loop.

Also, for you or anyone else here looking to report a security issue, note that the GitHub Issue creation flow includes a link/button to all the details/process:

<img width="1188" alt="Pasted_Image_4_11_24__3_32 PM" src="https://github.com/apache/superset/assets/812905/7ad959b5-0613-42fb-9882-a15faa74dd37">

**Comment by rusackas** [comment]
Thank you for caring enough to spot/report it... just closing this so we can tackle it further from public view.
