### ISSUE TITLE
Error message when trying to query mongodb databse using superset meta database connection

### ISSUE THREAD

**Issue by KhaledBenZina** [apache/superset#27989]
### Bug description

Hello, I am running Superset on docker compose along with Apache Drill and a mongodb instance. I am trying to query the MongoDB database using Superset meta database for multiple data sources dashboards. The query: SELECT * from "mongodb_connection.mongo.my_database.my_table";
 I am having this error message when I try to query mongo: "superset error: Catalogs are not currently supported". Is there a workaround or is something wrong with my query? Btw everything works fine when I query the mongodb using the classic mongodb database connection (with Apache Drill)

### How to reproduce the bug

1. Run Apache Drill on top of mongodb 
2. Create a Mongodb connection using Apache Drill this will be called mongo
3. Create a Superset meta database connection with allowed_db the mongodb connection in engine parameters
4. Query the mongodb database on SQL lab using the syntax : SELECT * from "mongodb_connection.mongo.my_database.my_table";
5. Error message superset error: Catalogs are not currently supported

### Screenshots/recordings

![image](https://github.com/apache/superset/assets/56385855/2e8cc0e7-5bea-44b5-a744-73601a8bf73e)

### Superset version

4.0.0

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

I am using docker compose for superset&Drill&mongodb

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Hopefully @betodealmeida can help a bit.

**Comment by mistercrunch** [comment]
This a driver issue? Drill issue? My guess is you can validate with this simple python script (thanks gpt!)
```python
from sqlalchemy import create_engine

engine = create_engine('drill://{{THE_CONN_STR_YOU_PUT_IN_SUPERSET}}')

with engine.connect() as connection:
    result = connection.execute("SELECT * FROM cat.schema.table")  # Replace 'your_table' with your actual table name
    for row in result:
        print(row)

```

**Comment by KhaledBenZina** [comment]
I found a workaround actually. 
I prepare my dataset on Drill directly by writing my query, store it in parquet using Drill filesystem, then query the DFS on Superset. The only difference is that I wont have my data live as I need to recreate the dataset on Drill each time (I will use a seperate python job for that)

**Comment by mistercrunch** [comment]
Just a thought, but I've seen hacks that try to do best of both worlds (perf and realtime) by creating view that that UNION ALL as in
```sql
SELECT * FROM highperf_materalized_table WHERE dt < DATE('{hard_coded_last_etl_job}')
UNION ALL
SELECT * FROM realtime_virtual_external table WHERE dt >= DATE('{hard_coded_last_etl_job}')
```
You need to make sure predicate is properly applied by the optimizer / excution-engine and leveraging some indexed/partitioned field, but it's doable in some systems.
