### ISSUE TITLE
No TreeMap v2 in my 3.1.1 verison of Superset

### ISSUE THREAD

**Issue by sarcoex** [apache/superset#28011]
### Bug description

I have access to the TreeMap but not the TreeMap v2

### How to reproduce the bug

In the dashboard, when I search for "treemap" I don't have the treemap v2. The treemap that I have available represents no hierarchy 

### Screenshots/recordings

![Capture d'écran 2024-04-12 144617](https://github.com/apache/superset/assets/163432171/2ac217af-c3e7-4b8d-8f8b-1efe8a578af6)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
The legacy treemap has been fully migrated to treemap V2, and thus we don't need the V2 anymore :)

The new/current one does indeed support hierarchy... you just need to add additional dimensions to the controls:

<img width="1169" alt="image" src="https://github.com/apache/superset/assets/812905/69daaacc-91ff-47bd-81c4-dd5cbe94cc56">
