### ISSUE TITLE
Unable to put tabs in rows or columns on new dashboard grid

### ISSUE THREAD

**Issue by markostefanovic1** [apache/superset#28025]
## Screenshot

![ezgif-1-240c6f0c5a](https://github.com/apache/superset/assets/105298890/508e5d69-4e0b-40ad-ae82-5a305f1e9bf3)

## Description

Previously we were able to put tabs in columns. This helped a lot for displaying different views of the same data - for example normal line chart in first tab, and cumulative line chart in second tab - allowing the option for user to chose how they see the data on the dashboard.

This new grid severely limits the dashboard layout options by disallowing this kind of positioning.

What is funny is that old dashboards created when this was allowed stayed the same, with tabs in columns, but you can't continue building in the same style on that dashboard if you want to add new charts.

**Comment by michael-s-molina** [comment]
Fixed by https://github.com/apache/superset/pull/28242
