### ISSUE TITLE
CSV to database upload is broken

### ISSUE THREAD

**Issue by boomrollkick** [apache/superset#28043]
### Bug description

![Screenshot 2024-04-15 at 6 16 46 PM](https://github.com/apache/superset/assets/648265/3522a623-ccec-4a8b-b36a-d92d1ecdfdc1)
 It looks like the code to upload the csv has gone missing.

### How to reproduce the bug

1. Make sure you're using superset 4.
2. Make sure you have connected a database with upload functionality
3. Try uploading a csv

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by mistercrunch** [comment]
Good news is there's a big effort taking place at the moment to completely re-implement CSV upload. Bad news is we probably won't touch/fix the previous version.

Merged 2 weeks ago -> https://github.com/apache/superset/pull/27840

Props to @dpgaspar  🔥 🚀

**Comment by rusackas** [comment]
Closing this as stale, but if you're still facing this in currently supported 4.x versions, let us know!
