### ISSUE TITLE
Charts Changing Color with Each Refresh

### ISSUE THREAD

**Issue by hk-the-analyst** [apache/superset#28104]
![image](https://github.com/apache/superset/assets/123436992/6c84e557-d62a-40ce-9847-bd95398c1546)
In Superset We are disabled from modifying the color scheme of the charts, it says it will be following the dashboard color scheme,
and each time we refresh the dashboard a new color will be assigned to the chart,

Even if try to clear the dashboard color scheme it will be automatically rapper

**Comment by hk-the-analyst** [comment]
As A wprk around we explicitally specified color hex code for each label for all charts in Dashboard 
![image](https://github.com/apache/superset/assets/123436992/eb70713e-d9a2-46fd-ba89-5c034ffb87ba)

**Comment by hk-the-analyst** [comment]
` "color_scheme": "supersetColors",
  "refresh_frequency": 0,
  "expanded_slices": {},
  "label_colors": {
    "Paid Production": "#2A57A6",
    "Unpaid Production": "#78A3EF",
    "CANCELLED": "#BCD5FF",
    "NO SHOW": "#78A3EF",
    "CHECKED OUT": "#2A57A6",
    "Net Production": "#5E30CD",
    "Net Collection": "#9E79F4",
    "Not Rescheduled": "#A12259",
    "Rescheduled": "#E96EA5",
    "Net Production(DOS)": "#B8C665",
    "Appointment Count": "#00829A",
    "Procedure Count": "#00829A",
    "Existing Patients": "#ef4444",
    "Existing Patients w/ Future Appts.": "#f87171",
    "New Patients": "#ef4444",
    "New Patients w/ Future Appts": "#f87171",
    "Average Production": "#ef4444"
  },    `

**Comment by Smallhi** [comment]
mark,some issue!

**Comment by geido** [comment]
Hello, thanks for reporting this issue. We are working on a fix here https://github.com/apache/superset/pull/27439
