### ISSUE TITLE
Not able to disable edit chart option and clickable title option In Iframe

### ISSUE THREAD

**Issue by vikashrajgupta** [apache/superset#28141]
![Screenshot from 2024-04-16 18-01-23](https://github.com/apache/superset/assets/40394708/79bd4573-c3dd-413a-ae15-2005bc5bb48c)

![Screenshot from 2024-04-16 18-09-15](https://github.com/apache/superset/assets/40394708/cba4afb7-428b-4d34-939b-7570db6fad7a)

## Description

Hello There,
I'm using Superset Version 3.0.1 and Superset [Embedded SDK](https://www.npmjs.com/package/@superset-ui/embedded-sdk) to retrieve in Iframe.

In this version everything seems working fine except random CSS error and the Chart is clickable as shown above.

I have provided limited permission to this public user as shown below, but still getting the edit chart option as well as chart title is also clickable.

Apart from this Options like "view query" is also there. But when I logged in via public user credential it seemed good to me.

![Screenshot from 2024-04-16 18-01-42](https://github.com/apache/superset/assets/40394708/08f75c70-76fc-4d3a-8038-b05a48a4b5ec)

## Design input
I'm not able to retrieve option any to disable these clicks, so kindly look into it that would be very helpful!.

**Comment by rusackas** [comment]
I swear I just saw something like this reported elsewhere, but I can't seem to find it now. Can you check the owners of that chart/dash and see if your public/guest-token user is among the owners?

**Comment by vikashrajgupta** [comment]
@rusackas Shared example is just a default chart from superset but In my case, I have created a dashboard for which I have provided admin and public access. I'm calling` api/v1/security/login` using the `admin (have all access) username and password` and then passing the access token to` /gues_token` endpoint.

In guest_token I'm passing the embedded dashboard ID and the username for which only provided public access.

When I'm opening the interface using public user credentials I'm only able to see provided access. but I'm fetching the same dashboard in Iframe by the above shared process getting the edit chart and title clickable option.

I'm confused about why this is happening. Am I missing anything in the whole process?

**Comment by vikashrajgupta** [comment]
@rusackas - I checked my code and I was generating access_token from admin credentials that have all of the permissions.
Then passing the access token to the below endpoint
http://localhost:9888/api/v1/security/guest_token/
```
{
"user": {"username": "public_user"}, "resources":[{"type": "dashboard", "id": "833f863b-a10c-483b-bc3b-edc2fbc9cfa2"}],"rls":[]
}
```

It further returns a token and then passes to embedded SDK happens the earlier shared issue.

But Whenever I logged via public user credential everything looks good as per my permission.

**Comment by vikashrajgupta** [comment]
@rusackas - Do let me know if I'm doing anything wrong in this process, waiting for your valuable response

**Comment by rusackas** [comment]
I think you just need to lock down the permissions, possibly by creating a new role. I [think this thread](https://github.com/apache/superset/issues/28172) effectively answers your question, but if not, you might want to ask the other person on that thread. Closing this since it's a config issue, rather than a bug, it appears.
