### ISSUE TITLE
NPM missing peer-dependencies

### ISSUE THREAD

**Issue by lscheibel** [apache/superset#28150]
### Bug description

Follow-up on this issue : https://github.com/apache/superset/issues/21799

I see two problems, the first one being the use of an unsupported Node version 16, while the package.json specifies that the Node version must be `^18.19.1`, which is also the version used in the docker-compose.yml. This is despite the fact that the current package-lock.json seems to have been generated with Node 16.

As suggested by others, another problem are the missing peer-dependencies, namely `currencyformat.js` but also `global-box`. Interestingly enough, when installing all dependencies for superset-frontend with Node 18 and then trying to start the dev-server I get an error about another missing peer-dependency `@react-spring/web`. 

As a solution I could submit a PR that installs the following packages:
- `@react-spring/web@^9.7.3` in the superset-frontend root, [as required by `@visx/xychart`](https://github.com/airbnb/visx/blob/master/packages/visx-xychart/package.json)
- `global-box@^1.2.0` in `plugins/plugin-chart-word-cloud`, [as required by `encodable`](https://github.com/kristw/encodable/blob/master/packages/encodable/package.json)
- `currencyformatter.js@^1.0.5` in `plugins/plugin-chart-handlebars`, [as required by `just-handlebars-helpers`](https://github.com/leapfrogtechnology/just-handlebars-helpers/blob/main/package.json)

### How to reproduce the bug

1. Install and use Node 18.
2. Navigate to superset-frontend.
3. Delete node_modules e.g. `rm -rf node_modules`.
4. Run `npm i`.
5. Run `npm run dev-server`.

Errors like "Can't resolve '@react-spring/web'" appear.

### Superset version

master / latest-dev

### Python version

Not applicable

### Node version

Not applicable

### Browser

Not applicable

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
We'd welcome a PR, or three! However, note that the updates should be made in the relevant plugins' directories, not on Superset's main package.json.

I thought we had everything all set with the node18 upgrade, but perhaps the package-lock file also needs an update thanks to the newer npm version, too.

**Comment by lscheibel** [comment]
After a bit more investigation, it seems that I had `legacy-peer-deps` enabled globally in the Node 18 version of my work laptop. Without this, the peer dependencies are correctly installed and also the lock-file doesn't have any changes anymore. I would guess that this is also the cause for the problem that the original author of the issue had, since peer-deps are installed since npm >=7. 

Sorry for the confusion, I'm pretty sure that both, this issue and https://github.com/apache/superset/issues/21799 can be closed.
