### ISSUE TITLE
"Variable is not set" error while trying to run "docker compose pull"

### ISSUE THREAD

**Issue by josedurigon** [apache/superset#28166]
### Bug description

PS C:\superset\superset> docker compose up -d
time="2024-04-20T21:25:18-03:00" level=warning msg="The \"SCARF_ANALYTICS\" variable is not set. Defaulting to a blank string."
time="2024-04-20T21:25:18-03:00" level=warning msg="The \"CYPRESS_CONFIG\" variable is not set. Defaulting to a blank string."
time="2024-04-20T21:25:18-03:00" level=warning msg="The \"CYPRESS_CONFIG\" variable is not set. Defaulting to a blank string."
validating C:\superset\superset\docker-compose.yml: services.superset-init.env_file.0 must be a string

### How to reproduce the bug

Following the steps on [documentation](https://superset.apache.org/docs/installation/installing-superset-using-docker-compose)
1 - clone the project on [github](https://github.com/apache/superset.git)
2 - run docker compose up 

### Screenshots/recordings

![image](https://github.com/apache/superset/assets/68879294/11081973-589a-41fd-9d25-110d76e25672)

![image](https://github.com/apache/superset/assets/68879294/9ae933aa-a38c-4150-b8bf-8490da61f47b)

![image](https://github.com/apache/superset/assets/68879294/6eee58cf-b877-4aa8-9b31-226f2c03910c)

### Superset version

master / latest-dev

### Python version

3.10

### Node version

18 or greater

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by TK2575** [comment]
Same error occurs on mac, not windows specific

**Comment by josedurigon** [comment]
> Something that worked for me to for now fix this was to change what the env_file variable received, looks like the format they used to represent the paths is not working correctly with YML format.
> 
> Try changing the variables like this, removing both **- path** elements and just sending 1 path as the input.
> 
> `env_file: docker/.env # default`
> 
> Note that you need to do that for all services that use the variable env_file

Removed the `- path:` but still had no success... 
Response was "no configuration file provided: not found"

**Comment by josedurigon** [comment]
> Something that worked for me to for now fix this was to change what the env_file variable received, looks like the format they used to represent the paths is not working correctly with YML format.
> 
> Try changing the variables like this, removing both **- path** elements and just sending 1 path as the input.
> 
> `env_file: docker/.env # default`
> 
> Note that you need to do that for all services that use the variable env_file
Hey thanks for trying to help, but it still doesn't work. I get the same messages.

**Comment by mistercrunch** [comment]
Minimum docker-compose version is `2.24.0` what are you on?

**Comment by dlgldgldgld** [comment]
In my case, It's resolved after updating docker-compose.
before: 2.16, after: 2.26

**Comment by mistercrunch** [comment]
TODO: implement some sort of `superset check-env` command that would check for versions of node, npm, docker, docker-compose and tell you what you need to upgrade.

**Comment by josedurigon** [comment]
> Minimum docker-compose version is `2.24.0` what are you on?

That's it. Worked just fine

**Comment by josedurigon** [comment]
I've updated my Docker and it ran without an issues. Thank you all for the support
