### ISSUE TITLE
[SIP-128] AI/LLM query generation in SQL lab

### ISSUE THREAD

**Issue by surapuramakhil** [apache/superset#28167]
*Please make sure you are familiar with the SIP process documented*
[here](https://github.com/apache/superset/issues/5602). The SIP will be numbered by a committer upon acceptance.

### Motivation

To make Apache superset dashboard/chats creation possible for Non Dev/SQL background users.
https://github.com/apache/superset/discussions/27272

### Proposed Change

Describe how the feature will be implemented, or the problem will be solved. If possible, include mocks, screenshots, or screencasts (even if from different tools).

1. A prompt box on the top of current SQL editor box, Along with generate query button.

![Screenshot 2024-04-21 at 3 33 17 AM](https://github.com/apache/superset/assets/9161543/2634d7a7-7088-45e2-9be4-b9f15c300ff5)
**This is current SQL LAB used for showing SQL editor box**

2. Forward user prompts to LLM Model Along with other system prompts - which shares databases schema information (consider it as RAG) for quality prompt responses. (optional) Some additional query / prompts which are required for understanding data. Maybe sharing first 10 rows. (Or) distinct values for a column, etc. (whatever is necessary)

3. populate the editor with the query generated by the model.

**Query Generation**
there are already pipelines in langchain for this https://python.langchain.com/docs/use_cases/sql/quickstart/#convert-question-to-sql-query.

we can use these pipelines for generating Queries from text. It works for any llm model. we can just piggyback on that. All I am planning to be have llm_provider or llm_factory which creates llm based on user needs and send to their pipeline.

Few Technical Implementations / Considerations

- LLM access will be provided by configuring API Endpoint by Superset admin / owner. (this also included other necessary information like access & secret keys) (this can also be via langChain As i have seen some of the PR's have done this)

LLM access as API would give choice whether they want to use existing services rather than deploying. Packaging LLM in superset deployment is not feasible

- OpenAI standard model interface has become pretty common and a lot of other models follow. (inputs required on this)

Backend Architecture Diagram

![image](https://github.com/apache/superset/assets/9161543/41e6ec4d-7cea-4fef-b6fa-700a38d15014)

### New or Changed Public Interfaces

Describe any new additions to the model, views or `REST` endpoints. Describe any changes to existing visualizations, dashboards and React components. Describe changes that affect the Superset CLI and how Superset is deployed.

### New dependencies

Describe any `npm`/`PyPI` packages that are required. Are they actively maintained? What are their licenses?

### Migration Plan and Compatibility

Describe any database migrations that are necessary, or updates to stored URLs.

### Rejected Alternatives

Describe alternative approaches that were considered and rejected.

**Comment by rusackas** [comment]
We'll need to cover a lot of things that are missing from this SIP:
• What packages/licenses are needed, and are the compatible?
• What are the security/privacy implications?
• How do we (as an open-source solution) stay vendor-agnostic here? What's the abstraction layer?

This will need to be put up for a DISCUSS thread on the mailing list to move forward, but I think the proposal needs more detail/resolution.

**Comment by surapuramakhil** [comment]
Either two Options (draft) - feel free to add what you think

1. Either use HTTP request - where users can configure endpoint.
Or use sophisticated LLM FW like Langchain. Which helps when scaling in terms of functionality

|                | LLM access using LangChain                              | LLM access using HTTP                                                                                                            |
|----------------|---------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------|
| Advantages     | Scalability while adding/extending features             | Little code - leaves LLM to end user                                                                                             |
|                | Supports lot of LLM's but switch might requried         | User configures HTTP endpoint - giving him choice of either self-hosted or  LLM as servie where he can just configure end point. |
| Congigurations | user configures necessary API keys/options con work     | while user define http end point - he will configure headers                                                                     |
|                |                                                         | Code solves for 1 particular usescases. extensibility is tough                                                                   |
|                | levrage Langchain                                       | we might need to add code which FW's like langchain already does                                                                 |
|                | Provider agnostic - as it supports Almost all providers | Provider-agnostic - user configures endpoint                                                                                     |
|                | Less changes requried - as these are SDK's              | Request need to changed whenever releases happens etc                                                                            |
|                |                                                         |                                                                                                                                  |
|                |                                                         |                                                                                                                                  |

We'll need to cover a lot of things that are missing from this SIP:
• What packages/licenses are needed, and are the compatible?
• What are the security/privacy implications? - user configures necessary API keys
• How do we (as an open-source solution) stay vendor-agnostic here? What's the abstraction layer? Either option

**Comment by surapuramakhil** [comment]
Either two Options (draft) - feel free to add what you think. (probably I need to find a way of doing this as collaborative one).

If maintainers can create a sheet that works, else I can create a spreadsheet. For evaluating or suggesting various approaches or implementation ideas

1. Either use HTTP request - where users can configure endpoint.
Or use sophisticated LLM FW like Langchain. Which helps when scaling in terms of functionality

|                | LLM access using LangChain                              | LLM access using HTTP                                                                                                            |
|----------------|---------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------|
| Advantages     | Scalability while adding/extending features             | Little code - leaves LLM to end user                                                                                             |
|                | Supports lot of LLM's but switch might requried         | User configures HTTP endpoint - giving him choice of either self-hosted or  LLM as servie where he can just configure end point. |
| Congigurations | user configures necessary API keys/options con work     | while user define http end point - he will configure headers                                                                     |
|                |                                                         | Code solves for 1 particular usescases. extensibility is tough                                                                   |
|                | levrage Langchain                                       | we might need to add code which FW's like langchain already does                                                                 |
|                | Provider agnostic - as it supports Almost all providers | Provider-agnostic - user configures endpoint                                                                                     |
|                | Less changes requried - as these are SDK's              | Request need to changed whenever releases happens etc                                                                            |
|                |                                                         |                                                                                                                                  |
|                |                                                         |                                                                                                                                  |

**Comment by surapuramakhil** [comment]
@geido based on my research langchain already solves this.
https://python.langchain.com/docs/use_cases/sql/quickstart/#convert-question-to-sql-query.

They wrote pipelines for generating Queries from text. It works for any llm model. we can just piggyback on that. All I am planning to is have llm_provider or llm_factory which creats llm based on user needs and send to their pipeline.

**Comment by surapuramakhil** [comment]
@geido as you said updated description.

> First question that comes to mind, how do you intend to pull the right metadata from the database for the LLM to use? There is a limited context window, and you just can't pull the whole schema for both context and performance limitations.

Let's try with langchain and see its results.

**Comment by geido** [comment]
It looks more like a toy for now:

> Has definitions for all the available tables.

This won't work for production databases that might have hundreds of tables and columns.

**Comment by geido** [comment]
I think having langchain in the repo might be a nice thing to have to enable LLM-related capabilities. However, that would be a separate SIP to illustrate how langchain could be leveraged in the repo. It looks like starting from SQL generation is hard.

**Comment by surapuramakhil** [comment]
> It looks like starting from SQL generation is hard.

Add some supporting info pls. I agree this problem is not fully solved, but at least we can reuse existing. (that's the reason why I considered only query generation - generated query will be reviewed by user before executing (not automated)).

Since very early phase of AI we are living in.

**Comment by tseruga** [comment]
As someone who has actually implemented this exact idea in superset for a hackathon a few months back, this is a pipe-dream at best (to be fairly blunt). Using RAG to pull relevant table metadata at prompt-time still led to unmanageable levels of LLM hallucination that only grows worse as the size of the warehouse being queries increases.

Something like this may be feasible for a user with a handful of tables, but at-scale it simply doesn't work. And a query that is 99% is functionally worthless if this is intended to be utilized by folks who don't have the skills necessary to parse through AI-generated SQL.

**Comment by surapuramakhil** [comment]
> like this may be feasible for a user with a handful of tables, but at-scale it simply doesn't work

This is the problem with Language Model. That's exactly why LLM choice is given to users. If the situation were the scale is high, the best they can with high context size model like Gemini pro-1.5. Thats a separate Data Science problem which Apache Superset doesn't need to solve. just leverage what is available.

---------------------------------------------------------------------------------------------------

> Using RAG to pull relevant table metadata at prompt-time still led to unmanageable levels of LLM hallucination that only grows worse as the size of the warehouse being queried increases.

This is a separate data science problem which Apache Superset doesn't need to solve, currently langchain community (quite popular in datascience) are solving this problem. we just leverage it. 

this might protect from hallucination https://python.langchain.com/docs/use_cases/sql/query_checking/ 
Prompting / RAG strategies while working at scale - https://python.langchain.com/docs/use_cases/sql/large_db/

As both evolve (by time), Quality of Queries will become better & better.

------------------------------------------------------------------------------------------------------

> a query that is 99% correct is functionally worthless if this is intended to be utilized by folks who don't have the skills necessary to parse through AI-generated SQL.
I agree with you about this, this doesn't fully solve who doesn't necessary knowledge to understand AI generated SQL. It's a copilot instead of an auto pilot.

**Comment by surapuramakhil** [comment]
Ah, I have found this. 

# This is a premium feature of Preset.(its a Moat)

https://preset.io/blog/preset-ai-assist/

I think this gets closed or remain stale.

**Comment by rusackas** [comment]
@surapuramakhil do you still intend to move forward with this?

**Comment by ved-kashyap-samsung** [comment]
Hi @rusackas We have implemented LLM based query generation for our use case which is using self hosted model . We have also developed an adapter which can support popular LLM as service platforms like chat GPT etc. using API key configurations. What is the process ahead to move forward on this sip now. Should we create a PR.

**Comment by geido** [comment]
@ved-kashyap-samsung are you on [Apache Superset Slack](https://join.slack.com/t/apache-superset/shared_invite/zt-2be0drwz8-bxPfkdz28ozzk1Iox29ufg)? You can find me there as "Diego Pucci". I was the lead engineer for AI Assist for Preset, I should be able to help with getting the SIP right. Please, get in touch.

**Comment by rusackas** [comment]
@ved-kashyap-samsung I think adding AI to Superset requires a proposal for consensus on the approach. If you want to open a PR with what you have, you're more than welcome to, but it's unlikely it'll get merged without going through a SIP proess. You can add your details/approach here if you want to use this SIP, or you can open your own SIP. Please reach out on [slack](http://bit.ly/join-superset-slack) if you'd like assistance.

**Comment by rusackas** [comment]
Last call for interested parties to sign up and dial in this proposal. In a couple more weeks, this will have gone 6 months without being brought up for discussion on the ASF mailing list, and will be closed as inactive. Thanks to everyone, however it plays out :)

**Comment by HESyang** [comment]
Maybe a less exciting idea for it: could we just use a chrome extension for the purpose? It will be much easier to use it along with superset, without worrying about the main update on Superset.

**Comment by rusackas** [comment]
You can _absolutely_ use/create a chrome plugin. I think it could be a Superset plugin if you want to author such a thing, or something more generalized. Either way, you wouldn't need a SIP, but we'd be happy to help evangelize the effort if it  comes to fruition.

**Comment by mkrishna23** [comment]
Our team started to work on *Superset* plugin. If anyone made progress and wants to collaborate, let us talk. thanks

**Comment by rusackas** [comment]
Closing this one out as Discarded since there seems to be no interest.

**Comment by jiaoyang3** [comment]
This is a pity, I think it's a great feature

**Comment by rpwils98** [comment]
How about leveraging cube.dev semantic layer and allow users to use domain knowledge to interact with the genAI as well as build sql? Have you seen Looker Explore?  You can can then expand that to be able to use genAI across the entire dashboard to drive NLQ and agentic flows

**Comment by shingote15** [comment]
it's useful and must have AI capability in superset.

**Comment by shingote15** [comment]
> Closing this one out as Discarded since there seems to be no interest.

Please don't worry about closing it. it is helpful for everyone.

**Comment by Davidnovarro** [comment]
Why was this proposal rejected? It's probably one of the best ideas ever put forward.

**Comment by lotshin** [comment]
AI features may be the most important feature in the superset. Why was it rejected?
