### ISSUE TITLE
Drawback on latest version 4.0.0 dashboard grid

### ISSUE THREAD

**Issue by JatinVenkatesh** [apache/superset#28210]
**OLD**
![s2](https://github.com/apache/superset/assets/155366940/f2bcce1f-6d95-4ea4-b403-56694c2e36d0)

**NEW**
![s3](https://github.com/apache/superset/assets/155366940/75e6c0db-8eb3-414f-8659-02bc3bf4c84f)

In the older version we were able to create different layout templates, but in the latest version we have some limitations in the dashboard grid.

**Comment by justinpark** [comment]
@JatinVenkatesh The issue is not a regression. You have the option to achieve the same layout using the column layout component, just like in version 3.x.

https://github.com/apache/superset/assets/1392866/c11b6b84-089b-4d4d-803f-dc4a6feea480
