### ISSUE TITLE
Not able to enable DASHBOARD_RBAC in helm chart ?

### ISSUE THREAD

**Issue by abhishekindigg** [apache/superset#28234]
### Bug description

Hello,

I have installed a latest superset in my AWS EKS with Helm chart and I want to enable DASHBOARD_RBAC because even after assigning Gamma role to users, they are not able to view the Dashboards. 

I did following in my values.yaml

configOverrides:
  my_override: |
    FEATURE_FLAGS = {
        "DASHBOARD_RBAC": True,
        "DYNAMIC_PLUGINS": True
    }
    
 Not working as expected. 

### How to reproduce the bug

in values.yaml 

configOverrides:
  my_override: |
    FEATURE_FLAGS = {
        "DASHBOARD_RBAC": True,
        "DYNAMIC_PLUGINS": True
    }

### Screenshots/recordings

In the Gamma role I have added these permissions still users are not able to view the dashboard.

<img width="1151" alt="image" src="https://github.com/apache/superset/assets/141122850/509b8993-e66f-498f-b692-21a8a9885855">

### Superset version

3.1.2

### Python version

Not applicable

### Node version

Not applicable

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by craig-rueda** [comment]
Can you try running `helm template .` to verify that your overrides are being placed inside of the `superset-config` secret correctly?

**Comment by villebro** [comment]
@abhishekindigg have you assigned roles to the dashboards you want your users to see, and assigned users to said roles? Unless they belong to the relevant roles, they won't see the dashboards (this is the whole point of Dashboard RBAC). Also, remember to publish the dashboards you want to share.

**Comment by abhishekindigg** [comment]
@villebro Thanks man!

I had to assign roles for each dashboard. It worked.

**Comment by rusackas** [comment]
@abhishekindigg we always encourage updates to our documentation if you want to edit one of the pages and help others in the future :)
