### ISSUE TITLE
Superset Kubernetes documentation resource offline

### ISSUE THREAD

**Issue by danielrosehill** [apache/superset#28245]
### Bug description

Just by way of FYI:

Searching for your Kubernetes installation documentation brings me to this resource:

![image](https://github.com/apache/superset/assets/40233203/5563b488-060e-44a0-aa4d-a50657cdb68b)

With URL:

https://superset.apache.org/docs/installation/running-on-kubernetes/

But I get this error:

![image](https://github.com/apache/superset/assets/40233203/90499da2-8a5a-43c4-8ba7-18ab4e2ccafe)

Same behavior for the indexed documentation for configuration in general (also on the superset.apache.org domain):

https://superset.apache.org/docs/installation/configuring-superset/

### How to reproduce the bug

As above

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
I've actually been seeing a lot of this as well... and the same with the in-site Algolia-based search. It seems like we need to provide some redirects, check our robots.txt files, or something along those lines. 

CC @sfirke @mistercrunch @artofcomputing

**Comment by mistercrunch** [comment]
Oh docusaurus has a redirect page, I tried to hook those up when I moved the contributing.md recently. 

Not sure if we touched the k8s docs recently but we should set up redirect.

**Comment by mistercrunch** [comment]
Hoping this fixes this link and many others that seemed broken -> https://github.com/apache/superset/pull/28247

Thanks for reporting this!

**Comment by danielrosehill** [comment]
> Hoping this fixes this link and many others that seemed broken -> #28247
> 
> Thanks for reporting this!

Glad to help. Love me some good documentation :-)
