### ISSUE TITLE
Elements of markdown not supported by Text layout Element

### ISSUE THREAD

**Issue by xavier-GitHub76** [apache/superset#28256]
Hello,

with Superset 3.1.1 (and previous), the layout element "Text" does not support markdown syntax for:
• syntax highlighting of code blocks
• the borders of a table

## Screenshot
![image](https://github.com/apache/superset/assets/82046143/543643a9-6356-464e-b186-00aaa3f75833)

## Markdown
The markdown source is joined
[source.md](https://github.com/apache/superset/files/15145653/source.md)

Regards

**Comment by mistercrunch** [comment]
I think we use the python `markdown` lib, on the main branch that's currently `markdown==3.6`. We would support what they support, and while our `requirements/base.txt` pins the lib at a specific version, you're free to upgrade to another version ahead of the pinned one. Our `pyproject.toml` says "markdown>=3.0", meaning you can `pip upgrade markdown` in your local builds

**Comment by rusackas** [comment]
Much of this can be styled as well, so you can (re)add the borders on tables and things like that with dashboard css templates. There are a few examples [here](https://preset.io/blog/customizing-superset-dashboards-with-css/).

**Comment by mistercrunch** [comment]
See their changelog here -> https://python-markdown.github.io/changelog/ . If there are features you'd like to see in Superset around markdown support, it has to go through that library.

**Comment by xavier-GitHub76** [comment]
Thanks for yours responses.

I test a markdown file with the library : 

``` python
import markdown

with open("my_markdown.md", "r", encoding="utf-8") as input_file:
    text = input_file.read()
html = markdown.markdown(text, extensions=['tables', 'fenced_code'])

with open("my_markdown_output.html", "w", encoding="utf-8", errors="xmlcharrefreplace") as output_file:
    output_file.write(html)
```

The rendering is identical to that of Superset. For visual customization, I'll look at the CSS. Thanks again

**Comment by xavier-GitHub76** [comment]
![image](https://github.com/apache/superset/assets/82046143/ba63d218-28d5-4761-a907-41ba2af202a4)
