### ISSUE TITLE
Can not Connect to AWS Redis Serverless 

### ISSUE THREAD

**Issue by dfoley84** [apache/superset#28264]
### Bug description

Unable to Connect to Serverless Redis,
 _Error -2 connecting to superset-redis-ttwfnz.serverless.usw2.cache.amazonaws.com:6379._
 
 Don't see an option for Cache TLS within Superset Config. 

### How to reproduce the bug

Create an AWS Redis Elastic Cache Serverless Instance

### Screenshots/recordings

[2024-04-29 15:07:00,882: ERROR/MainProcess] consumer: Cannot connect to redis://superset-redis-ttwfnz.serverless.usw2.cache.amazonaws.com:6379/0: Error -2 connecting to superset-redis-ttwfnz.serverless.usw2.cache.amazonaws.com:6379. Name or service not known.. Trying again in 32.00 seconds... (16/100)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by mistercrunch** [comment]
We pretty much just use Flask-Caching (https://flask-caching.readthedocs.io/en/latest/) which has a super simple interface and good docs.

Looks like there's something around `rediss://` with 2 s
<img width="921" alt="Screenshot 2024-04-29 at 6 35 28 PM" src="https://github.com/apache/superset/assets/487433/357acab1-0191-497d-be99-0eaad0f3040c">

**Comment by mistercrunch** [comment]
For the record I looked to see if our docs could be improved here https://superset.apache.org/docs/configuration/cache#caching, and pointers are decent. I think pointers to other docs are better then trying to recopy things in our docs (say Rediss TLS-specific stuff) and risk things going out-of-sync over time

**Comment by StephenKing** [comment]
AFAIK ElastiCache *Serverless* enforces TLS, so it seems use _rediss_ is the way to go and I suggest to close this.

**Comment by mistercrunch** [comment]
Perfect, please contribute a docs PR if you think things can be improved.
