### ISSUE TITLE
Superset Guest Token Endpoint Only is not Working     My URL - ( https://superset.mysite.com/api/v1/security/guest_token )

### ISSUE THREAD

**Issue by srivj5** [apache/superset#28337]
### Bug description

I have tried others api's like access_token and refresh token all APIs was working, but Guest token API only Not working.

### How to reproduce the bug

Error:
{
    "errors": [
        {
            "message": "405 Method Not Allowed: The method is not allowed for the requested URL.",
            "error_type": "GENERIC_BACKEND_ERROR",
            "level": "error",
            "extra": {
                "issue_codes": [
                    {
                        "code": 1011,
                        "message": "Issue 1011 - Superset encountered an unexpected error."
                    }
                ]
            }
        }
    ]
}

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Any reproduction steps whatsoever would help someone understand what you're up against. We don't know how you're deploying Superset, how you're embedding it, what role you're using for the guest token, what version you're using, or anything. Server logs would also probably help since it's a server error.

**Comment by srivj5** [comment]
I have set the role as admin and gamma

**Comment by srivj5** [comment]
> Any reproduction steps whatsoever would help someone understand what you're up against. We don't know how you're deploying Superset, how you're embedding it, what role you're using for the guest token, what version you're using, or anything. Server logs would also probably help since it's a server error.

The role is admin and gamma. Enabled the can generate guest token in role management

**Comment by srivj5** [comment]
I have fixed
