### ISSUE TITLE
Superset ALERT & REPORTS not working

### ISSUE THREAD

**Issue by mujohiddin** [apache/superset#28381]
![photo_2024-05-08_11-48-01](https://github.com/apache/superset/assets/69301931/907ccb32-d025-4257-af80-3d664bc8aa9f)
![photo_2024-05-08_11-47-36](https://github.com/apache/superset/assets/69301931/04ac3103-accd-4add-a2db-509f66cf15f9)
 

### How to reproduce the bug

a

### Screenshots/recordings

hi

### Superset version

master / latest-dev

### Python version

3.9

### Node version
16
- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by mujohiddin** [comment]
![Uploading photo_2024-05-08_11-48-01.jpg…]()

**Comment by mujohiddin** [comment]
hi

**Comment by mujohiddin** [comment]
![Uploading photo_2024-05-08_11-48-01.jpg…]()

**Comment by mujohiddin** [comment]
Menda ALERT menejeri ishlamaydi superset 6 oy oldingi versiyasi o'rnatilgan, buni tuzatishning biron bir usuli bormi? qo'shimcha parametrlarni qo'shish kerakmi?
@mistercrunch,@villebro,@michael-s-molina,@betodealmeida,@john-bodley
@rusackas

**Comment by dpgaspar** [comment]
@mujohiddin we use english as a common language on this repo, please add a detailed description for your issue and add server logs showing the alert and reports error(s)

**Comment by mujohiddin** [comment]
@dpgaspar Hi I have ALERT manager not working superset 6 months old version installed, is there any way to fix this? need to add more parameters? @mistercrunch,@villebro,@michael-s-molina,@betodealmeida,@john-bodley
@rusackas

**Comment by mujohiddin** [comment]
![Uploading photo_2024-05-08_11-48-01.jpg…]()

**Comment by mujohiddin** [comment]
![photo_2024-05-08_11-48-01](https://github.com/apache/superset/assets/69301931/e8814875-8e6f-4606-bcbf-eb0bf5d0c017)

**Comment by mujohiddin** [comment]
![Uploading photo_2024-05-08_11-47-36.jpg…]()

**Comment by mujohiddin** [comment]
> 2\. reports.scheduler

where is<< reports.scheduler file

**Comment by mujohiddin** [comment]
@dpgaspar 
![photo_2024-05-08_14-40-14](https://github.com/apache/superset/assets/69301931/89fec80f-31e0-4fc9-8199-5de554d0bc1d)

**Comment by mujohiddin** [comment]
![Uploading photo_2024-05-08_14-41-01.jpg…]()

**Comment by mujohiddin** [comment]
@dpgaspar 
![Uploading photo_2024-05-08_14-41-01.jpg…]()

**Comment by mujohiddin** [comment]
Hello sir, can you help me?
@mistercrunch,@villebro,@michael-s-molina,@betodealmeida,@john-bodley
@rusackas

**Comment by dpgaspar** [comment]
seems like it's a `geckodriver` installation issue, take a look at: https://superset.apache.org/docs/configuration/alerts-reports#using-firefox

**Comment by mistercrunch** [comment]
[mujohiddin](https://github.com/mujohiddin) ple
