### ISSUE TITLE
exp claim on JWT token is not respected and token is still valid after expiration time

### ISSUE THREAD

**Issue by tuan-h** [apache/superset#28450]
### Bug description

Using my Superset secret key, I generated a JWT token for API access. The `exp` claim is not respected.

![image](https://github.com/apache/superset/assets/591646/97d7902e-6026-42f6-92fd-65eacf9fabf8)

From terminal:
```
❯ date +%s
1715592489 # note that this is bigger than exp claim in above screenshot

❯ curl -X 'GET' \
  'https://superset.xxx.com/api/v1/dataset/' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'
{"count":2, ...} # curl should have returned that token has already expired
```

Just as a sanity check, I added a `nbf` claim that is far into the future and it is respected.

```
❯ curl -X 'GET' \                                                                                                                                                                                            18:28:09
  'https://superset.xxx.com/api/v1/dataset/' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...with_nbf'
{"msg":"The token is not yet valid (nbf)"}
```

### How to reproduce the bug

1. Have a running instance of Superset.
2. Generate a JWT token with `sub`, `iat`, and `exp` claims. `exp` should be expired and `sub` should be a user id from `ab_user` table with access to API calls (admin user works fine). https://jwt.io/ can be used for token generation.
3. Run `curl` command from terminal with header `Authorization: Bearer {jwt_token}` as in above bug description.
4. `curl` should return response that token has already expired but it returns actual results instead.

### Superset version

4.0.0

### Python version

Not applicable

### Node version

Not applicable

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by dpgaspar** [comment]
I was not able to reproduce the issue

JWT used:
``` json
{
  "fresh": true,
  "iat": 1715600519,
  "jti": "0072e7d4-cfc1-4ca3-a910-2b66fd957ea8",
  "type": "access",
  "sub": 1,
  "nbf": 1715600519,
  "exp": 1715601419
}
```

```
curl -X 'GET' \
  'http://localhost:8088/api/v1/dataset/' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGci....'
{
  "msg": "Token has expired"
}

$ date +%s
1715604341
```

**Comment by tuan-h** [comment]
This was my mistake. The timestamp I used was in milliseconds when it should have been in seconds. So the expiration was off by orders of magnitude. Thank you for the assistance! Closing the issue.
