### ISSUE TITLE
HTTP Headers Configuration on config.py not overriding.

### ISSUE THREAD

**Issue by spars57** [apache/superset#28491]
### Bug description

When trying to embed a dashboard I can't because "X-Frame-Options" is set to "SAMEORIGIN".

I'm using Superset v3.10.

I tried to override it on config.py file like this:

OVERRIDE_HTTP_HEADERS: dict[str, Any] = {'X-Frame-Options': 'ALLOW-FROM http://localhost:5173'}

I have added the same value to DEFAULT_HTTP_HEADERS and HTTP_HEADERS but nothing seems to work because looks like this variables are being ignored by the server.

"X-Frame-Options" always keeps the same value..

### How to reproduce the bug

Try to embed a dashboard on a different domain 

### Screenshots/recordings

<img width="1175" alt="image" src="https://github.com/apache/superset/assets/79933117/5729ad04-1aa9-4d5f-8485-a80af292f9ae">

### Superset version

3.1.3

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Curious why you closed it... did the bot help? We're still trying to figure out how useful it is :)

**Comment by spars57** [comment]
I found out the solution, I had to configure Talisman like this on config.py:
TALISMAN_ENABLED = True
TALISMAN_DEV_CONFIG = {
        ...
        "frame_options": 'ALLOWALL',
        'frame_options_allow_from': '*',
}
