### ISSUE TITLE
There is no filter box in apache superset version 3.1.3

### ISSUE THREAD

**Issue by Madhuri2000** [apache/superset#28514]
### Bug description

There is no filter box in apache superset version 3.1.3

### How to reproduce the bug

1. login to superset
2. create a new chart by selecting data source and I tried to select filter box chart, but that chart is not there

### Superset version

3.1.3

### Python version

I don't know

### Node version

I don't know

### Browser

Chrome

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
In 3.x, the filter box is deprecated, and might not be visible in the viz picker. In 4.0, it's completely removed from the codebase. If you want to update Superset in the future for performance/features/security reasons, I would recommend steering clear of the FilterBox. If you really want one, you can _probaby_ go to an example dashboard that has one, edit it, and "save as".
