### ISSUE TITLE
DISPLAY_MAX_ROW  10.000 / 100.000

### ISSUE THREAD

**Issue by xavier-GitHub76** [apache/superset#28549]
Hello,

when I run a request with lot of rows, I have an alert message.
The number od rows isn't correct.

![image](https://github.com/apache/superset/assets/82046143/e25abe42-815d-48fd-8aeb-12e73cbf96b7)

10.000 is mentionned / 100.000 

Best regards

**Comment by rusackas** [comment]
Dosu is almost right. There is a `ROW_LIMIT` config, but that's for chart data.

The error you see right there in the UI, however IS correct. 

`DISPLAY_MAX_ROW` in `config.py` is set by default to 10,000, and that's the limit you're hitting, just like it says. You can raise it in your config if you'd like.

Admittedly, it's not a great experience that the UI even _shows_ higher than you're allowed to request... maybe that Select menu should look up and respect the `DISPLAY_MAX_ROW` setting, and/or display it in a tooltip so the user is more aware of it. If you feel like opening a PR to make it better, that would be cool!

**Comment by xavier-GitHub76** [comment]
Hello,

Thank you for the clarifications provided.
There are several ways to limit the number of rows (ROW_LIMIT, DISPLAY_MAX_ROW), the drop-down list could take the most restrictive of these variables as its maximum value.

Thus the user would make a choice that is always achievable.
This would also avoid having a surprising error message.
Currently the message tells the user to modify their query by adding a limit or a filter to display 100,000 values ​​even though they will technically never be able to reach this number of rows.

Sincerely

**Comment by rusackas** [comment]
If you want to propose a change, and/or open a PR to that effect, I think folks would be supportive!

**Comment by xavier-GitHub76** [comment]
This report is linked to https://github.com/orgs/apache/projects/345/views/1?filterQuery=row&pane=issue&itemId=59020979 (and https://github.com/apache/superset/discussions/19195)
