### ISSUE TITLE
[SIP-134] Hide inactive users

### ISSUE THREAD

**Issue by lyndsiWilliams** [apache/superset#28569]
### Motivation

Some users don't want/need to see inactive users in the "Owners" dropdown in list views and on Superset entities.

### Proposed Change

Use the `isActive` attribute to hide any users that are inactive on the front end. We can put this behind a config flag since some users do want to see inactive users.

### New or Changed Public Interfaces

- Any instances of the "Owners" dropdown will only show active users.
- This will be toggled with a config flag so that users have the option to show or hide inactive users.

### New dependencies

None.

### Migration Plan and Compatibility

No changes here.

### Rejected Alternatives

I'm unaware of any rejected alternatives.

**Comment by rusackas** [comment]
What determines whether a user is active or inactive?

Is it better to flag users as "inactive" rather than "isActive" assuming they're active by default, and *may* fall into some lapsed state?

**Comment by rusackas** [comment]
@lyndsiWilliams maybe this isn't a temporal thing, but just based on a flag on the user account that already exists? In an y case, would you mind putting this up for a [DISCUSS] thread if you want to move the ball forward?

**Comment by yousoph** [comment]
My guess is that it would use the is Active checkbox on the List Users page, is that what you were thinking @lyndsiWilliams ?

**Comment by rusackas** [comment]
@lyndsiWilliams just wondering if there's any intent to follow through with this.

**Comment by rusackas** [comment]
Just a heads up, this'll be closed as inactive on October 17th unless there's any follow-up/backing to move it through the process. Thanks!

**Comment by rusackas** [comment]
Closing as discarded
