### ISSUE TITLE
Pivot Table (legacy) sum issues

### ISSUE THREAD

**Issue by konk0n** [apache/superset#28616]
### Bug description

In Pivot Table (legacy) instead of the Sum of the columns and rows I get the Max although I have chosen the Aggregation Function as 'Sum' in the Pivot Options of the table. I use a PostgreSQL dataset. How can I solve this issue?

![Screenshot 2024-05-21 105704](https://github.com/apache/superset/assets/170406003/0a8f59b5-f936-4a6f-883a-1b805ae9c2ef)
![Screenshot 2024-05-21 105826](https://github.com/apache/superset/assets/170406003/a9725ead-457b-4c32-bffa-af4ce676dc18)

### How to reproduce the bug

1. Add a Pivot Table (legacy) as a chart
2. Chose Sum as Aggregation Function in the Pivot Options.
3. Update the Chart.

### Screenshots/recordings

![Screenshot 2024-05-21 105704](https://github.com/apache/superset/assets/170406003/b80803ca-0e23-4922-a828-a7e352df2e83)
![Screenshot 2024-05-21 105826](https://github.com/apache/superset/assets/170406003/e2b8e73a-ca94-4bf1-adb4-343b1354d88e)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Firefox

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
I hope someone here can help, but we no longer actively support the older (legacy) Pivot Table.

**Comment by rusackas** [comment]
Closing as stale, since we don't support that old table, and we don't seem to be getting traction otherwise.
