### ISSUE TITLE
Error in Add Alert form when upgrading to version 4.0.1

### ISSUE THREAD

**Issue by andrec84j** [apache/superset#28612]
### Bug description

When upgrading from version 3.1.3 to 4.0.1, the alert sending configuration form in the Notification method item is validating after adding emails, making it impossible for the alert to be saved.

### How to reproduce the bug

1 - Alert & Reports
2 - + Alert
3 -  fill out form

### Screenshots/recordings

The ADD button remains disabled even when adding emails:
![2024-05-20_183617](https://github.com/apache/superset/assets/49701047/d6ccf12e-35f3-4e06-a4c2-df44dad858ca)

### Superset version

4.0.1

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by amolsr** [comment]
![image](https://github.com/apache/superset/assets/38129418/4c5f6183-0c83-4cb0-9cf4-fec88cac89de)
bump

**Comment by dufour-yohann** [comment]
I'm experiencing the same issue, moreover on existing alerts, I cannot update the recipient list from the modal (the only workaround I've found is doing it from the database...)

**Comment by andrec84j** [comment]
Any chance of a fix coming out for this modal?

**Comment by sfirke** [comment]
This was reported in https://github.com/apache/superset/issues/28149 and fixed in https://github.com/apache/superset/pull/28409.  Sorry for the inconvenience, this pull request should be included in the next version (both 4.0.2 and 4.1.0, unclear which will come out first).  Feel free to test the master branch version of Superset to confirm that it is indeed fixed.
