### ISSUE TITLE
ROW_LIMIT not working

### ISSUE THREAD

**Issue by mujohiddin** [apache/superset#28644]
### Bug description

Hello there. my project is last year september october version but i have row limit not working how to fix it. I don't know how to fix it. Help me pleace
![photo_2024-05-22_11-52-55](https://github.com/apache/superset/assets/69301931/b4180d95-6ee6-43f5-a856-79777af027b8)
![photo_2024-05-22_11-52-17](https://github.com/apache/superset/assets/69301931/4e8bd9c4-50db-4f42-abf3-8dcb582a3055)

### How to reproduce the bug

1

### Screenshots/recordings

@michael-s-molina @betodealmeida @rusackas @jon

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

Hi

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by mujohiddin** [comment]
@michael-s-molina @betodealmeida @rusackas @jon

**Comment by mujohiddin** [comment]
> “ROW_LIMIT” sozlamasining to‘g‘ri qo‘llanilmasligi bilan bog‘liq muammo bir necha omillarga, jumladan, Superset kod bazasidagi so‘nggi o‘zgarishlar, backend konfiguratsiyalari yoki frontend boshqaruv mantig‘iga bog‘liq bo‘lishi mumkin. Ushbu muammoni hal qilishda sizga yordam beradigan ba'zi qadamlar va fikrlar:
> 
> ### Backend konfiguratsiyalari
> Backend konfiguratsiyasi `config.py`sizning “ROW_LIMIT” sozlamangizni bekor qilmasligiga ishonch hosil qiling. Tekshirish uchun asosiy sozlamalar:
> 
> * **SQL_MAX_ROW** : Har qanday analitik ma'lumotlar bazasi so'rovi uchun qaytarilgan satrlarning maksimal sonini belgilaydi.
> * **DISPLAY_MAX_ROW** : SQL Lab UI da ko'rsatiladigan qatorlar sonini cheklaydi.
> * **DEFAULT_SQLLAB_LIMIT** : SQL Lab soʻrovlari uchun standart qator chegarasi.
> * **SUPERSET_META_DB_LIMIT** : Xususiyat bayrog'i `ENABLE_SUPERSET_META_DB`yoqilganda cheklash.
> * **SQLLAB_CTAS_NO_LIMIT** : SQL Lab-ga CTAS funksiyasidan foydalanganda qator cheklovisiz so'rovlarni bajarishga ruxsat beradi.
> 
> ### Frontend boshqaruv mantiqi
> Siz oʻrnatgan qiymat (20.000.000) ruxsat etilgan parametrlar ichida ekanligiga yoki erkin shakldagi kiritish sifatida toʻgʻri tasdiqlanganligiga ishonch hosil qiling. Tekshirish `row_limit`maxsus variantlar va tekshirish mantig'i bilan belgilanadi.
> 
> ### Superset kod bazasidagi so'nggi o'zgarishlar
> "ROW_LIMIT" sozlamasiga ta'sir qilishi mumkin bo'lgan Superset kod bazasida yaqinda o'zgarishlar bo'ldi. Ta'kidlash joizki, [№27700](https://github.com/apache/superset/pull/27700) va [№26151](https://github.com/apache/superset/pull/26151) so'rovlari qator chegaralari bilan bog'liq muammolarni hal qiladi.
> 
> ### Jurnal va disk raskadrovka
> Supersetda “ROW_LIMIT” sozlamasi qanday qoʻllanilishi yoki soʻrovni bajarish vaqtida eʼtiborga olinmasligini kuzatishga yordam beradigan jurnalga yozish mexanizmlari mavjud. Kalit ro'yxatga olish bayonotlari faylda mavjud `superset/commands/sql_lab/execute.py`.
> 
> ### `row_limit`Nazoratning ko'rinishi
> Boshqaruv yoqilmaganligiga ishonch hosil qiling `server_pagination`, chunki bu "ROW_LIMIT" sozlamasining e'tiborsiz qolishiga olib kelishi mumkin.
> 
> Muammo davom etsa, "ROW_LIMIT" sozlamasining ishlashiga ta'sir qilishi mumkin bo'lgan Superset kod bazasidagi so'nggi o'zgarishlarni ko'rib chiqing.
> 
> Bu masala chuqurroq ko'rib chiqishni talab qiladi shekilli,@rusackasIltimos, o'z tajribangizni taqdim eta olasizmi?
> 
> #### Tafsilotlar
> **Sources**
> 
> * [Limit issue](https://github.com/apache/superset/issues/20132)
> * [superset/migrations/versions/2019-06-04_10-12_d7c1a0d6f2da_remove_limit_used_from_query_model.py](https://github.com/apache/superset/blob/master/superset/migrations/versions/2019-06-04_10-12_d7c1a0d6f2da_remove_limit_used_from_query_model.py)
> * [superset-frontend/plugins/plugin-chart-handlebars/src/plugin/controls/limits.ts](https://github.com/apache/superset/blob/master/superset-frontend/plugins/plugin-chart-handlebars/src/plugin/controls/limits.ts)
> * [superset-frontend/src/explore/controls.jsx](https://github.com/apache/superset/blob/master/superset-frontend/src/explore/controls.jsx)
> * [superset/config.py](https://github.com/apache/superset/blob/master/superset/config.py)
> * [docker/pythonpath_dev/superset_config.py](https://github.com/apache/superset/blob/master/docker/pythonpath_dev/superset_config.py)
> * [superset/sql_lab.py](https://github.com/apache/superset/blob/master/superset/sql_lab.py)
> * [superset/commands/sql_lab/execute.py](https://github.com/apache/superset/blob/master/superset/commands/sql_lab/execute.py)
> * [CHANGELOG/3.1.0.md](https://github.com/apache/superset/blob/master/CHANGELOG/3.1.0.md)
> * [CHANGELOG/4.0.1.md](https://github.com/apache/superset/blob/master/CHANGELOG/4.0.1.md)
> * [superset-frontend/packages/superset-ui-chart-controls/src/shared-controls/sharedControls.tsx](https://github.com/apache/superset/blob/master/superset-frontend/packages/superset-ui-chart-controls/src/shared-controls/sharedControls.tsx)
> * [superset-frontend/src/SqlLab/components/ResultSet/index.tsx](https://github.com/apache/superset/blob/master/superset-frontend/src/SqlLab/components/ResultSet/index.tsx)
> 
> 
> **About Dosu** This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> _Suhbatni davom ettirish uchun zikr qiling@dosu._

I have run my superset project version for the first time since September October last year, I tried the above solutions and it didn't work

**Comment by mujohiddin** [comment]
> > “ROW_LIMIT” sozlamasining to‘g‘ri qo‘llanilmasligi bilan bog‘liq muammo bir necha omillarga, jumladan, Superset kod bazasidagi so‘nggi o‘zgarishlar, backend konfiguratsiyalari yoki frontend boshqaruv mantig‘iga bog‘liq bo‘lishi mumkin. Ushbu muammoni hal qilishda sizga yordam beradigan ba'zi qadamlar va fikrlar:
> > ### Backend konfiguratsiyalari
> > Backend konfiguratsiyasi `config.py`sizning “ROW_LIMIT” sozlamangizni bekor qilmasligiga ishonch hosil qiling. Tekshirish uchun asosiy sozlamalar:
> > 
> > * **SQL_MAX_ROW** : Har qanday analitik ma'lumotlar bazasi so'rovi uchun qaytarilgan satrlarning maksimal sonini belgilaydi.
> > * **DISPLAY_MAX_ROW** : SQL Lab UI da ko'rsatiladigan qatorlar sonini cheklaydi.
> > * **DEFAULT_SQLLAB_LIMIT** : SQL Lab soʻrovlari uchun standart qator chegarasi.
> > * **SUPERSET_META_DB_LIMIT** : Xususiyat bayrog'i `ENABLE_SUPERSET_META_DB`yoqilganda cheklash.
> > * **SQLLAB_CTAS_NO_LIMIT** : SQL Lab-ga CTAS funksiyasidan foydalanganda qator cheklovisiz so'rovlarni bajarishga ruxsat beradi.
> > 
> > ### Frontend boshqaruv mantiqi
> > Siz oʻrnatgan qiymat (20.000.000) ruxsat etilgan parametrlar ichida ekanligiga yoki erkin shakldagi kiritish sifatida toʻgʻri tasdiqlanganligiga ishonch hosil qiling. Tekshirish `row_limit`maxsus variantlar va tekshirish mantig'i bilan belgilanadi.
> > ### Superset kod bazasidagi so'nggi o'zgarishlar
> > "ROW_LIMIT" sozlamasiga ta'sir qilishi mumkin bo'lgan Superset kod bazasida yaqinda o'zgarishlar bo'ldi. Ta'kidlash joizki, [№27700](https://github.com/apache/superset/pull/27700) va [№26151](https://github.com/apache/superset/pull/26151) so'rovlari qator chegaralari bilan bog'liq muammolarni hal qiladi.
> > ### Jurnal va disk raskadrovka
> > Supersetda “ROW_LIMIT” sozlamasi qanday qoʻllanilishi yoki soʻrovni bajarish vaqtida eʼtiborga olinmasligini kuzatishga yordam beradigan jurnalga yozish mexanizmlari mavjud. Kalit ro'yxatga olish bayonotlari faylda mavjud `superset/commands/sql_lab/execute.py`.
> > ### `row_limit`Nazoratning ko'rinishi
> > Boshqaruv yoqilmaganligiga ishonch hosil qiling `server_pagination`, chunki bu "ROW_LIMIT" sozlamasining e'tiborsiz qolishiga olib kelishi mumkin.
> > Muammo davom etsa, "ROW_LIMIT" sozlamasining ishlashiga ta'sir qilishi mumkin bo'lgan Superset kod bazasidagi so'nggi o'zgarishlarni ko'rib chiqing.
> > Bu masala chuqurroq ko'rib chiqishni talab qiladi shekilli,@rusackasIltimos, o'z tajribangizni taqdim eta olasizmi?
> > #### Tafsilotlar
> > **Sources**
> > 
> > * [Limit issue](https://github.com/apache/superset/issues/20132)
> > * [superset/migrations/versions/2019-06-04_10-12_d7c1a0d6f2da_remove_limit_used_from_query_model.py](https://github.com/apache/superset/blob/master/superset/migrations/versions/2019-06-04_10-12_d7c1a0d6f2da_remove_limit_used_from_query_model.py)
> > * [superset-frontend/plugins/plugin-chart-handlebars/src/plugin/controls/limits.ts](https://github.com/apache/superset/blob/master/superset-frontend/plugins/plugin-chart-handlebars/src/plugin/controls/limits.ts)
> > * [superset-frontend/src/explore/controls.jsx](https://github.com/apache/superset/blob/master/superset-frontend/src/explore/controls.jsx)
> > * [superset/config.py](https://github.com/apache/superset/blob/master/superset/config.py)
> > * [docker/pythonpath_dev/superset_config.py](https://github.com/apache/superset/blob/master/docker/pythonpath_dev/superset_config.py)
> > * [superset/sql_lab.py](https://github.com/apache/superset/blob/master/superset/sql_lab.py)
> > * [superset/commands/sql_lab/execute.py](https://github.com/apache/superset/blob/master/superset/commands/sql_lab/execute.py)
> > * [CHANGELOG/3.1.0.md](https://github.com/apache/superset/blob/master/CHANGELOG/3.1.0.md)
> > * [CHANGELOG/4.0.1.md](https://github.com/apache/superset/blob/master/CHANGELOG/4.0.1.md)
> > * [superset-frontend/packages/superset-ui-chart-controls/src/shared-controls/sharedControls.tsx](https://github.com/apache/superset/blob/master/superset-frontend/packages/superset-ui-chart-controls/src/shared-controls/sharedControls.tsx)
> > * [superset-frontend/src/SqlLab/components/ResultSet/index.tsx](https://github.com/apache/superset/blob/master/superset-frontend/src/SqlLab/components/ResultSet/index.tsx)
> > 
> > **About Dosu** This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> > Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> > _Suhbatni davom ettirish uchun zikr qiling@dosu._
> 
> I have run my superset project version for the first time since September October last year, I tried the above solutions and it didn't work

@dosu._

**Comment by mujohiddin** [comment]
I have run my superset project version for the first time since September October last year, I tried the above solutions and it didn't work
@dosu._

**Comment by mujohiddin** [comment]
@mistercrunch

**Comment by mujohiddin** [comment]
@rusackas @michael-s-molina

**Comment by gaful** [comment]
Hello, you mentionned a september / october version. I recalled we faced the same issue around the same period, it was solved for us since 3.1.3.

**Comment by michael-s-molina** [comment]
Ho @mujohiddin. This bug was fixed by https://github.com/apache/superset/pull/26807 which is available in 3.1.3 and 4.0.1 so you just need to use one of these versions. You can always check in which version a fix is available using the [CHANGELOG](https://github.com/apache/superset/tree/master/CHANGELOG).

FYI: It's not a good practice to tag multiple people multiple times. Keep in mind that we receive many messages every day and might be busy resolving other issues.
