### ISSUE TITLE
{{ current_user_email() }} doesn't work 

### ISSUE THREAD

**Issue by nhat2008** [apache/superset#28648]
### Bug description

After enabling ENABLE_TEMPLATE_PROCESSING=True 
It doesn't work with "{{ current_user_email() }}"

It works well with "{{ current_user_id() }}" and "{{ current_username() }}"

I have tried 3 version: latest, 4.0.1 and 3.13 , all has same issue!

### How to reproduce the bug

1. Go to SQL Lab
2. Run this query: SELECT "{{ current_user_email() }}"

### Screenshots/recordings

![Current_user](https://github.com/apache/superset/assets/10190695/df3f1788-cea3-474a-8726-aadc73d9ad9a)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by ChernakovEgor** [comment]
Hey @nhat2008 have you managed to find a workaround?
I encounter the same bug on version 3.0.2

**Comment by nhat2008** [comment]
hi @ChernakovEgor , yes, i found a workaround way to solve it 
As the {{ current_user_email() }} is not in the latest released yet, its only available in the master branch , to use it, you may need to override 2 files in your version with the master one: 
superset/jinja_context.py, superset/utils/core.py

**Comment by kraftaa** [comment]
Do you know how to override it if I'm running in kube and only can change `values.yaml` ? 
My helm chart version is `0.12.11` , superset version `4.0.1`  and I see `current_user_email()` in github for that chart tag, but not in the files in my kube pod. I checked the latest docker image with `4.0.2` - it doesn't have `current_user_email()`
