### ISSUE TITLE
Improper Input Validation while creating dashboard and charts

### ISSUE THREAD

**Issue by abhimittal1992** [apache/superset#28711]
### Bug description

It is observed that application fails to validate and [sanitise]([url](<img width="1440" alt="Dashboards" src="https://github.com/apache/superset/assets/10044870/ed2e1d32-0f41-4678-b99e-3c8f8b4f383d">)) user supplied input containing malicious JavaScript which may be executed on browser leading to Stored Cross-Site Scripting.

### How to reproduce the bug

Login to superset 
Try to create dashboard and insert name there is not proper validation on the names

### Superset version

3.1.3

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by dpgaspar** [comment]
Please follow our guidelines: https://github.com/apache/superset/security/policy
