### ISSUE TITLE
Datasource access

### ISSUE THREAD

**Issue by Zarrina1** [apache/superset#28760]
### Bug description

Hello everyone!
I have Superset version 2.1.0
I have an issue while giving access to gamma role on particular dataset .
Normal situation is when I give datasource access to  Gamma role. So after that Gamma-user can see  dashboards where «my_dataset» was used as source  and also Gamma user can see «my_dataset» in Dataset folder .This works with only some datasets .
Result:
Gamma Role with dataset access
![3](https://github.com/apache/superset/assets/171135936/b3deeacd-a047-4988-afd7-7797e973dab9)
What this Gamma Role will see :
Connected dashboard
![4](https://github.com/apache/superset/assets/171135936/874e8e98-5516-49c3-9a16-e973283bd8f9)
Needed dataset
![5](https://github.com/apache/superset/assets/171135936/c483c968-1270-410f-8815-be3ad1861092)

So another situation is when I give also datasource access to  Gamma role but on another dataset (for ex- «dataset2» ) and dataset2 is used in some dashboards .This dashboards are not been displayed at all for the gamma-user but the user can see «dataset2» in Dataset folder .
Giving access process:
![1](https://github.com/apache/superset/assets/171135936/d3850b3e-1b06-445e-aee4-72b4bcf753c6)
So all user is able to see :
![2](https://github.com/apache/superset/assets/171135936/8e4933ed-51ea-472c-8919-b455e87e279a)
But no dashboards !
How to solve it ?Why are dashboards been shown only with some datasets? 

### How to reproduce the bug

1.Create Gamma role with datasourse access on [Cluster].[dataset]
2.Gamma role user can see dataset but no related charts/dashboard 
ps. dashboards are shown with some datasets ,with **other **datasets are not****

### Superset version

master / latest-dev

### Python version

I don't know

### Node version

I don't know

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by Zarrina1** [comment]
def can_access_dashboard(self, dashboard: "Dashboard") -> bool:
    try:
        self.raise_for_access(dashboard=dashboard)
    except SupersetSecurityException:
        return False
    return True 
Where can i write this?

**Comment by Zarrina1** [comment]
@dosu But why using some datasets dashboards are shown ,with other are not?

**Comment by rusackas** [comment]
I hope the AI comments are helpful, but I'm going to go ahead and close this out since we no longer support Superset <3.1. I *think* you can continue the bot talk as long as you'd like, but I'd also encourage you join [slack](http://bit.ly/join-superset-slack) and see if others there are able to help, perhaps in the `#customizing-superset` channel.
