### ISSUE TITLE
There was an error loading the schemas

### ISSUE THREAD

**Issue by juliansyahrifqi** [apache/superset#28778]
### Bug description

First, I  added a database into the superset and it works.

But when I tried to add new dataset, I select the database that I added before and when I select the schemas it doesn't show all schemas but it show an message  `There was an error loading the schemas`

I'm using superset v3.0.0

### How to reproduce the bug

1. Go to menu `dataset`
2. Click `+ Dataset`
3. Select`Database`
4. Select `Schema`
5. Popup error is show with message `There was an error loading the schemas`

### Screenshots/recordings
![image](https://github.com/apache/superset/assets/42226797/41d5b99e-f117-4bac-838d-6c7af9847e61)

### Superset version
3.0.0
3.1.3

### Python version

3.11

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by michael-s-molina** [comment]
@juliansyahrifqi Could you upgrade to 3.1.3 and see if the error still happens? 3.0.0 is not supported anymore. Please check our [Release Process](https://github.com/apache/superset/wiki/Release-Process) for more information.

**Comment by juliansyahrifqi** [comment]
I already upgrade to v3.1.3 and the error still happens

**Comment by juliansyahrifqi** [comment]
The error is from PostgreSQL, after i change the config in `pg_hba.conf`, now it working. Thank you

**Comment by buraktunca** [comment]
hi, what you changed in .conf file

**Comment by Quiago** [comment]
Hi, what you changed in .conf file?

**Comment by juliansyahrifqi** [comment]
Hello

```
host    all             all             0.0.0.0/0            scram-sha-256
```

I just change the `scram-sha-256` to be `md5` and then reconnect again
```
host    all             all             0.0.0.0/0            md5
```

After it working, i change it again to `scram-sha-256`
```
host    all             all             0.0.0.0/0            scram-sha-256
```

**Comment by Quiago** [comment]
Thanks I'll try
