### ISSUE TITLE
Time-series Line Chart Display unnecessary total

### ISSUE THREAD

**Issue by inbreaks** [apache/superset#28832]
## Screenshot

Time-series Line Chart
CONTRIBUTION MODE: None

<img width="686" alt="image" src="https://github.com/apache/superset/assets/1317194/c1e9cde9-f955-4d3b-afc2-50bb9d2d8962">

## Description

In this case, the next day's Retention rate (horizontal axis) for each channel is displayed, and the percentages on the right and total on the bottom are redundant.

## Design input

This logical problem was not caused in some previous versions

<img width="1468" alt="image" src="https://github.com/apache/superset/assets/1317194/8652c362-6139-4067-9fc4-74176d693d86">

**Comment by michael-s-molina** [comment]
Hi @inbreaks. I'm not sure if I fully understand the problem. Given that this new tooltip was not officially released yet, I'm assuming you are using `master`. I just checked the latest master version and I'm not able to reproduce the problem. The percentages are shown when there's no contribution.

<img width="1762" alt="Screenshot 2024-06-04 at 08 58 11" src="https://github.com/apache/superset/assets/70410625/dbfca0af-5bc8-4b20-82d3-3d81af3c9652">
<img width="1755" alt="Screenshot 2024-06-04 at 08 58 59" src="https://github.com/apache/superset/assets/70410625/2cf3400f-9ad4-4f7c-a72b-b2e4eda1b2e1">

The only scenario I can think of that could generate your screenshot is if you formatted the Y-axis to always display as percentage.

**Comment by inbreaks** [comment]
Hi @michael-s-molina  the background of this use case is to calculate the next-day retention rate of new users from each traffic channel, so the Y-axis will always show the percentage, but the total is not 100%, for example

| traffic sources | next-day retention |
| ------- | ------- |
| Google | 20% |
| Facebook | 30% |
| TikTok | 35% |

Therefore, calculating total and percentage is redundant

**Comment by michael-s-molina** [comment]
Hi @inbreaks. To support this use case, we would need some form of control to precisely configure what parts of the tooltip you want to display. We don't have that feature currently. Right now, you might want to disable the Rich Tooltip option until we provide such feature.

**Comment by inbreaks** [comment]
> Hi @inbreaks. To support this use case, we would need some form of control to precisely configure what parts of the tooltip you want to display. We don't have that feature currently. Right now, you might want to disable the Rich Tooltip option until we provide such feature.

Thanks @michael-s-molina , how do I turn off Rich Tooltip? Is it possible to configure `DEFAULT_FEATURE_FLAGS` to do this?

**Comment by michael-s-molina** [comment]
> Thanks @michael-s-molina , how do I turn off Rich Tooltip? Is it possible to configure DEFAULT_FEATURE_FLAGS to do this?

<img width="1770" alt="Screenshot 2024-06-06 at 09 51 16" src="https://github.com/apache/superset/assets/70410625/00e1d9e5-6410-44eb-a5c6-fc6c8063bde9">

**Comment by inbreaks** [comment]
@michael-s-molina 

I noticed that the latest release 4.1.1 has updated this feature compared to 4.0.2. I had to disable the Rich Tooltip option.
