### ISSUE TITLE
On Mac OS X Safari - Using Download As Image option on a chart returns empty image

### ISSUE THREAD

**Issue by pritammobisoft** [apache/superset#29083]
### Bug description

On Mac OS X Safari - When we use "Download As Image" option on a chart using the top right three dots button it returns empty image. 
On Mac OS X Chrome and Edge this feature is working properly. 

The same issue is present on "Master" branch as well as 4.0.1. 

### How to reproduce the bug

1. Go to any dashboard on Mac OS X in Safari.
2. Click on the vertical "..." button in top right of a chart. 
3. Select "Download" > "Download as Image"

This returns and empty image with title

### Screenshots/recordings

1. Safari Output with issue: 
![buggy result - from safari](https://github.com/apache/superset/assets/3992068/1c426c6b-cf2a-4742-afb2-3769dba8b6d6)
2. Chrome with correct output:
![expected result - from chrome](https://github.com/apache/superset/assets/3992068/9f0ec5de-7aaa-4b44-9ef0-7857f4a32553)

### Superset version

4.0.1

### Python version

3.11

### Node version

16

### Browser

Safari

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Thanks for filing, though this is a duplicate issue. Closing this in favor of https://github.com/apache/superset/issues/28713
