### ISSUE TITLE
Histogram dimensions overlay each other (CSS bug)

### ISSUE THREAD

**Issue by YoussefEgla** [apache/superset#29114]
### Bug description

When I create a histogram with dimensions not all dimensions are displayed on the histogram.

### How to reproduce the bug

1. create a histogram chart
2. specify the column and a dimension
3. Hover over columns

### Screenshots/recordings

This is the actual dimensions when I hover over a bar
![Screenshot 2024-06-07 163859](https://github.com/apache/superset/assets/57115457/5aacb057-ccd8-4f83-9fd3-2b3ed9c64571)

and this is how it looks normally
![Screenshot 2024-06-07 164428](https://github.com/apache/superset/assets/57115457/c49b78f3-10a3-4fb8-8e9a-5541032febfb)

### Superset version

4.0.1

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by YoussefEgla** [comment]
@dosu This won't fix the issue is with 2 middle dimension boxes overlaying one another

**Comment by rusackas** [comment]
I'm not sure which version you're on, but there's a new ECharts based Histogram that just merged on the `master` branch. It hasn't been released officially yet, but you're free to try it. There's even a migration to move over to it :)

**Comment by YoussefEgla** [comment]
@rusackas Thanks I will try it. I'm using version `4.0.1`

**Comment by michael-s-molina** [comment]
Fixed by https://github.com/apache/superset/pull/28652. It will be available in 4.1.
