### ISSUE TITLE
50 - Deprecate the KV_STORE feature flag

### ISSUE THREAD

**Issue by justinpark** [apache/superset#29162]
This proposal is to deprecate the `KV_STORE` feature flag and its related assets such as the API endpoint and `keyvalue` table. The main dependency of this feature is the `SHARE_QUERIES_VIA_KV_STORE` feature flag which allows sharing SQL Lab queries without the necessity of saving the query. Our intention is to use the permalink feature to implement this use case before 5.0 and that's why we are deprecating the feature flag now.

https://github.com/apache/superset/pull/26450

**Comment by rusackas** [comment]
Is this supposed to be on the 5.0 board?

**Comment by michael-s-molina** [comment]
There's already a card there. This one was from 4.0 and kept for historical reasons. Closing.
