### ISSUE TITLE
TimeSeries Chart is showing Year for the January month 

### ISSUE THREAD

**Issue by vasu-ram** [apache/superset#29237]
### Bug description

Time series Chart is showing Year instead January. 
we know the month is continuous, seems it is confusing the users

### How to reproduce the bug

1. Create Timeseries chart any
2. Use Timegrain month 
3. filter date Last Year

### Screenshots/recordings

![image](https://github.com/apache/superset/assets/55632570/a14b43dd-49fc-4729-8f8d-63fcc4a2f7f9)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Have you tried adding a date formatter?

**Comment by vasu-ram** [comment]
Tried above it is not working

**Comment by rusackas** [comment]
I mean here in the "Customize" tab of the controls, adding an X Axis format. Here's an example:

BEFORE:
<img width="1058" alt="Screenshot_2024-06-14_at_9_47_43 AM" src="https://github.com/apache/superset/assets/812905/203f2d31-7f78-4041-87f0-9ab7f722c8d0">

AFTER:
<img width="1070" alt="Screenshot_2024-06-14_at_9_48_20 AM" src="https://github.com/apache/superset/assets/812905/ae40ac03-5876-4c19-83b1-69911b923e3f">

**Comment by vasu-ram** [comment]
Thanks @rusackas, I don't know we can change the format on UI, That's fixed

**Comment by RenanLeiteBay** [comment]
You can put %b in x-axis to order by month name

![image](https://github.com/user-attachments/assets/c49015b2-f84c-451e-a382-3a7a9464783b)
