### ISSUE TITLE
4.0.1: Alerting and reports does not take EMAIL RECIPIENTS*

### ISSUE THREAD

**Issue by Kim-frau** [apache/superset#29256]
### Bug description

Unable to save an alert since notification method is allways in red

### How to reproduce the bug

Try to create an alert or a report and follow the steps, unable to save it. 
Also, unable to modify the email recipients of old alerts coming from the 3.1.2 version of superset

### Screenshots/recordings

![Capture d’écran 2024-06-14 173314](https://github.com/apache/superset/assets/77016083/237af436-b5ad-453d-a680-e259ff96efb7)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by akiellor** [comment]
It looks like this has been resolved in [this](https://github.com/apache/superset/pull/28409) Pull Request. But has not yet been released.

**Comment by Kim-frau** [comment]
Great, thanks

**Comment by Kim-frau** [comment]
Allready taken care in https://github.com/apache/superset/pull/28409
