### ISSUE TITLE
snowflake wrong quotes on schema name with dot

### ISSUE THREAD

**Issue by myskaludek** [apache/superset#29341]
### Bug description

When schema name in snowflake has "." then sql lab cannot get list of tables.

Schema in snowflake have for me name "out-c.superset" and in logs for listing table in sql lab is query
```
SHOW /* sqlalchemy:get_table_names */ TABLES IN out."c-superset"
```

insead of
```
SHOW /* sqlalchemy:get_table_names */ TABLES IN "out.c-superset"
```

### How to reproduce the bug

1. Add snowflake-sqlalchemy to docker image
2. Start superset 3.1.0
3. Connectd snoflake database
4. Go to sql lab and let list tables in schema `out-c.superset` 

### Screenshots/recordings

```
2024-06-24 10:20:58,477:DEBUG:snowflake.connector.cursor:running query [SHOW /* sqlalchemy:get_table_names */ TABLES IN out."c-superset"]
```

### Superset version

3.1.3

### Python version

3.10

### Node version

I don't know

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
The Superset PMC doesn't currently have any Snowflake testers/users on the roster. I'd encourage anyone reading this to [sign up here](https://docs.google.com/spreadsheets/d/1U1qxiLvOX0kBTUGME1AHHi6Ywel6ECF8xk_Qy-V9R8c/edit#gid=0) to volunteer to test future Snowflake issues. I hope someone from the community is able to submit a PR for this 🤞
