### ISSUE TITLE
Excess Padding in Horizontal Bar Charts When Legend is Added

### ISSUE THREAD

**Issue by seandiacono** [apache/superset#29342]
### Bug description

Horizontal bar charts in Apache Superset are created with extra padding when a legend is added, affecting the chart's layout and appearance. This issue was introduced in [PR #27883](https://github.com/apache/superset/pull/27883#issuecomment-2182972005).

**Expected Behavior:**
The chart should adjust the layout to accommodate the legend without adding excessive padding.

### How to reproduce the bug

1. Create a horizontal bar chart
2. Ensure that the legend is enabled and the margin is set to 0 or none
3. You should see extra padding between the chart and the legend

### Screenshots/recordings

![image](https://github.com/apache/superset/assets/20338969/f5a0821b-ffdb-4091-a4f8-8ff80b49cba6)

### Superset version

4.0.1

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

This bug was validated by @sfirke in Slack

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by sfirke** [comment]
This caused existing charts to display differently on dashboards upon upgrading from 4.0.0.  The temporary fix is to set legend margin in chart to -100, but that would require modifying every affected chart -- then presumably undoing it once the bug is fixed.
