### ISSUE TITLE
WARNING 'werkzeug.local.LocalProxy' is not mapped

### ISSUE THREAD

**Issue by Habeeb556** [apache/superset#29403]
### Bug description

I got the below error in logs:

```
WARNING:root:Class 'werkzeug.local.LocalProxy' is not mapped
WARNING:root:Class 'werkzeug.local.LocalProxy' is not mapped
WARNING:root:Class 'werkzeug.local.LocalProxy' is not mapped
WARNING:root:Class 'werkzeug.local.LocalProxy' is not mapped
```

### How to reproduce the bug

Noting

### Superset version

4.0.1

### Python version

3.11

### Node version

I don't know

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by sfirke** [comment]
I get this in my logs as well.  I'm running 4.0.2 so while Dosu says a relevant PR was merged in 4.0.0, I confirm it did not quiet this warning.  I believe this warning has existed as far back as 2.0.0, if not farther - I don't think it indicates a warning but it clutters the logs.

**Comment by Habeeb556** [comment]
Yes, it’s the same. Do you have any suggestions for avoiding this clutter in the logs?

**Comment by andy-clapson** [comment]
In a perfect world this warning would go away, but in case you want to simply tune out the log noise you can add something like this to your custom `LoggingConfigurator` class:
```
import warnings
warnings.filterwarnings("ignore", message="Class 'werkzeug.local.LocalProxy' is not mapped")
```
(I am assuming here that you pass in your own `LOGGING_CONFIGURATOR` via a `config.py` override.)

**Comment by rusackas** [comment]
Thanks for the comment... I'll close this issue as a duplicate of https://github.com/apache/superset/issues/26020 in the meantime, and assume people find their way to this tip regardless of which one thread they follow :)
