### ISSUE TITLE
Exception: Unable to execute 'ecpg', you likely need to install it.'

### ISSUE THREAD

**Issue by Habeeb556** [apache/superset#29407]
### Bug description

I got the below error in log:

`Exception: Unable to execute 'ecpg', you likely need to install it.'`

### How to reproduce the bug

When using postgresql v13.3

### Screenshots/recordings

![image](https://github.com/apache/superset/assets/35889071/50575e73-5af9-4db2-bf3c-1d7073386f9c)

### Superset version

4.0.1

### Python version

3.11

### Node version

I don't know

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by Habeeb556** [comment]
Thanks, the issue was resolved after installing `pgdg-redhat-repo-latest.noarch.rpm` and then installing the package.

`sudo yum install postgresql-devel`

**Comment by scriptmaster** [comment]
## On debian (and ubuntu):

`sudo apt install libecpg-dev`

and then verify with:
`which ecpg`

`/usr/bin/ecpg`
