### ISSUE TITLE
DATA URIs are stripped from href attribute

### ISSUE THREAD

**Issue by jeverling** [apache/superset#29469]
### Bug description

I'm trying to include links to PDF files in a chart, where the links include the PDF report as base64 data URI, e.g. 

`<a href="data:application/pdf;base64,JVBERi0xLjcKJeLjz9MKMSAwIG9ia ... PRgo=" download="Report.pdf">PDF Report</a>`

This tag works fine when included in a regular HTML page.

In the Superset _TABLE_ chart, the value of the `href` attribute gets stripped.

Setting `HTML_SANITIZATION = False` in the config doesn't seem to make a difference.

Is this expected, that Superset strips the value of the `href` attribute, when it contains a data URI (or maybe it's related to length), when `HTML_SANITIZATION = False` is set?

### How to reproduce the bug

Add a column with `<a>` HTML tags to a data source, where the href attribute contains a data URI.
Create a _TABLE_ chart that includes that column.
The `href` attribute will not have a value in the resulting links in the chart.

### Superset version

3.1.3

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Seems like the bot pretty much nailed the answer. I'll close this as complete, since it answers the question and gives you the info to work around things. Holler if this needs reopening for any reason.
