### ISSUE TITLE
Database Issue when using mariadb 10.4, illegal mixx

### ISSUE THREAD

**Issue by cosmincioranu** [apache/superset#29483]
### Bug description

Issueing a database connection triggers 
` An error occurred while fetching databases: (MySQLdb.OperationalError) (1267, "Illegal mix of collations (utf8_bin,NONE) and (binary,IGNORABLE) for operation '='")
[SQL: SELECT count(*) AS count_1
FROM (SELECT dbs.uuid AS dbs_uuid, dbs.created_on AS dbs_created_on, dbs.changed_on AS dbs_changed_on, dbs.id AS dbs_id, dbs.verbose_name AS dbs_verbose_name, dbs.database_name AS dbs_database_name, dbs.sqlalchemy_uri AS dbs_sqlalchemy_uri, dbs.password AS dbs_password, dbs.cache_timeout AS dbs_cache_timeout, dbs.select_as_create_table_as AS dbs_select_as_create_table_as, dbs.expose_in_sqllab AS dbs_expose_in_sqllab, dbs.configuration_method AS dbs_configuration_method, dbs.allow_run_async AS dbs_allow_run_async, dbs.allow_file_upload AS dbs_allow_file_upload, dbs.allow_ctas AS dbs_allow_ctas, dbs.allow_cvas AS dbs_allow_cvas, dbs.allow_dml AS dbs_allow_dml, dbs.force_ctas_schema AS dbs_force_ctas_schema, dbs.extra AS dbs_extra, dbs.encrypted_extra AS dbs_encrypted_extra, dbs.impersonate_user AS dbs_impersonate_user, dbs.server_cert AS dbs_server_cert, dbs.is_managed_externally AS dbs_is_managed_externally, dbs.external_url AS dbs_external_url, dbs.created_by_fk AS dbs_created_by_fk, dbs.changed_by_fk AS dbs_changed_by_fk, changed_by.id AS changed_by_id, changed_by.first_name AS changed_by_first_name, changed_by.last_name AS changed_by_last_name, changed_by.username AS changed_by_username, changed_by.password AS changed_by_password, changed_by.active AS changed_by_active, changed_by.email AS changed_by_email, changed_by.last_login AS changed_by_last_login, changed_by.login_count AS changed_by_login_count, changed_by.fail_login_count AS changed_by_fail_login_count, changed_by.created_on AS changed_by_created_on, changed_by.changed_on AS changed_by_changed_on, changed_by.created_by_fk AS changed_by_created_by_fk, changed_by.changed_by_fk AS changed_by_changed_by_fk, created_by.id AS created_by_id, created_by.first_name AS created_by_first_name, created_by.last_name AS created_by_last_name, created_by.username AS created_by_username, created_by.password AS created_by_password, created_by.active AS created_by_active, created_by.email AS created_by_email, created_by.last_login AS created_by_last_login, created_by.login_count AS created_by_login_count, created_by.fail_login_count AS created_by_fail_login_count, created_by.created_on AS created_by_created_on, created_by.changed_on AS created_by_changed_on, created_by.created_by_fk AS created_by_created_by_fk, created_by.changed_by_fk AS created_by_changed_by_fk
FROM dbs LEFT OUTER JOIN ab_user AS changed_by ON dbs.changed_by_fk = changed_by.id LEFT OUTER JOIN ab_user AS created_by ON dbs.created_by_fk = created_by.id
WHERE concat(concat(concat(concat(%s, dbs.database_name), %s), CAST(dbs.id AS CHAR)), %s) IN (NULL) AND (1 != 1) OR dbs.database_name IN (NULL) AND (1 != 1)) AS anon_1]
[parameters: ('[', '].(id:', ')')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)`

### How to reproduce the bug

1. goto to database connection of a newly created user. 

### Screenshots/recordings

![image](https://github.com/apache/superset/assets/166105754/3d1e9ae1-d4df-4648-a02a-67ac47d58229)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

Jul  4 10:32:24 dssuperset python3.9[17740]: 2024-07-04 10:32:24,754:ERROR:superset.views.base:(MySQLdb.OperationalError) (1267, "Illegal mix of collations (utf8_bin,NONE) and (binary,IGNORABLE) for operation '='")
Jul  4 10:32:24 dssuperset python3.9[17740]: [SQL: SELECT count(*) AS count_1
Jul  4 10:32:24 dssuperset python3.9[17740]: FROM (SELECT dbs.uuid AS dbs_uuid, dbs.created_on AS dbs_created_on, dbs.changed_on AS dbs_changed_on, dbs.id AS dbs_id, dbs.verbose_name AS dbs_verbose_name, dbs.database_name AS dbs_database_name, dbs.sqlalchemy_uri AS dbs_sqlalchemy_uri, dbs.password AS dbs_password, dbs.cache_timeout AS dbs_cache_timeout, dbs.select_as_create_table_as AS dbs_select_as_create_table_as, dbs.expose_in_sqllab AS dbs_expose_in_sqllab, dbs.configuration_method AS dbs_configuration_method, dbs.allow_run_async AS dbs_allow_run_async, dbs.allow_file_upload AS dbs_allow_file_upload, dbs.allow_ctas AS dbs_allow_ctas, dbs.allow_cvas AS dbs_allow_cvas, dbs.allow_dml AS dbs_allow_dml, dbs.force_ctas_schema AS dbs_force_ctas_schema, dbs.extra AS dbs_extra, dbs.encrypted_extra AS dbs_encrypted_extra, dbs.impersonate_user AS dbs_impersonate_user, dbs.server_cert AS dbs_server_cert, dbs.is_managed_externally AS dbs_is_managed_externally, dbs.external_url AS dbs_external_url, dbs.created_by_fk AS dbs_created_by_fk, dbs.changed_by_fk AS dbs_changed_by_fk, changed_by.id AS changed_by_id, changed_by.first_name AS changed_by_first_name, changed_by.last_name AS changed_by_last_name, changed_by.username AS changed_by_username, changed_by.password AS changed_by_password, changed_by.active AS changed_by_active, changed_by.email AS changed_by_email, changed_by.last_login AS changed_by_last_login, changed_by.login_count AS changed_by_login_count, changed_by.fail_login_count AS changed_by_fail_login_count, changed_by.created_on AS changed_by_created_on, changed_by.changed_on AS changed_by_changed_on, changed_by.created_by_fk AS changed_by_created_by_fk, changed_by.changed_by_fk AS changed_by_changed_by_fk, created_by.id AS created_by_id, created_by.first_name AS created_by_first_name, created_by.last_name AS created_by_last_name, created_by.username AS created_by_username, created_by.password AS created_by_password, created_by.active AS created_by_active, created_by.email AS created_by_email, created_by.last_login AS created_by_last_login, created_by.login_count AS created_by_login_count, created_by.fail_login_count AS created_by_fail_login_count, created_by.created_on AS created_by_created_on, created_by.changed_on AS created_by_changed_on, created_by.created_by_fk AS created_by_created_by_fk, created_by.changed_by_fk AS created_by_changed_by_fk
Jul  4 10:32:24 dssuperset python3.9[17740]: FROM dbs LEFT OUTER JOIN ab_user AS changed_by ON dbs.changed_by_fk = changed_by.id LEFT OUTER JOIN ab_user AS created_by ON dbs.created_by_fk = created_by.id
Jul  4 10:32:24 dssuperset python3.9[17740]: WHERE dbs.allow_file_upload = 1 AND true = 1 AND (concat(concat(concat(concat(%s, dbs.database_name), %s), CAST(dbs.id AS CHAR)), %s) IN (NULL) AND (1 != 1) OR dbs.database_name IN (NULL) AND (1 != 1))) AS anon_1]
Jul  4 10:32:24 dssuperset python3.9[17740]: [parameters: ('[', '].(id:', ')')]
Jul  4 10:32:24 dssuperset python3.9[17740]: (Background on this error at: https://sqlalche.me/e/14/e3q8)
Jul  4 10:32:24 dssuperset python3.9[17740]: Traceback (most recent call last):
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
Jul  4 10:32:24 dssuperset python3.9[17740]:    self.dialect.do_execute(
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
Jul  4 10:32:24 dssuperset python3.9[17740]:    cursor.execute(statement, parameters)
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/MySQLdb/cursors.py", line 179, in execute
Jul  4 10:32:24 dssuperset python3.9[17740]:    res = self._query(mogrified_query)
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/MySQLdb/cursors.py", line 330, in _query
Jul  4 10:32:24 dssuperset python3.9[17740]:    db.query(q)
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/MySQLdb/connections.py", line 261, in query
Jul  4 10:32:24 dssuperset python3.9[17740]:    _mysql.connection.query(self, query)
Jul  4 10:32:24 dssuperset python3.9[17740]: MySQLdb.OperationalError: (1267, "Illegal mix of collations (utf8_bin,NONE) and (binary,IGNORABLE) for operation '='")
Jul  4 10:32:24 dssuperset python3.9[17740]: The above exception was the direct cause of the following exception:
Jul  4 10:32:24 dssuperset python3.9[17740]: Traceback (most recent call last):
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/superset/views/base.py", line 252, in wraps
Jul  4 10:32:24 dssuperset python3.9[17740]:    return f(self, *args, **kwargs)
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/superset/views/base_api.py", line 487, in get_list_headless
Jul  4 10:32:24 dssuperset python3.9[17740]:    duration, response = time_function(super().get_list_headless, **kwargs)
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/superset/utils/core.py", line 1470, in time_function
Jul  4 10:32:24 dssuperset python3.9[17740]:    response = func(*args, **kwargs)
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/flask_appbuilder/api/__init__.py", line 1619, in get_list_headless
Jul  4 10:32:24 dssuperset python3.9[17740]:    count, lst = self.datamodel.query(
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/flask_appbuilder/models/sqla/interface.py", line 489, in query
Jul  4 10:32:24 dssuperset python3.9[17740]:    count = self.query_count(query, filters, select_columns)
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/flask_appbuilder/models/sqla/interface.py", line 396, in query_count
Jul  4 10:32:24 dssuperset python3.9[17740]:    return self._apply_inner_all(
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/sqlalchemy/orm/query.py", line 3176, in count
Jul  4 10:32:24 dssuperset python3.9[17740]:    return self._from_self(col).enable_eagerloads(False).scalar()
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/sqlalchemy/orm/query.py", line 2893, in scalar
Jul  4 10:32:24 dssuperset python3.9[17740]:    ret = self.one()
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/sqlalchemy/orm/query.py", line 2870, in one
Jul  4 10:32:24 dssuperset python3.9[17740]:    return self._iter().one()
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
Jul  4 10:32:24 dssuperset python3.9[17740]:    result = self.session.execute(
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
Jul  4 10:32:24 dssuperset python3.9[17740]:    result = conn._execute_20(statement, params or {}, execution_options)
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
Jul  4 10:32:24 dssuperset python3.9[17740]:    return meth(self, args_10style, kwargs_10style, execution_options)
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
Jul  4 10:32:24 dssuperset python3.9[17740]:    return connection._execute_clauseelement(
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
Jul  4 10:32:24 dssuperset python3.9[17740]:    ret = self._execute_context(
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
Jul  4 10:32:24 dssuperset python3.9[17740]:    self._handle_dbapi_exception(
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
Jul  4 10:32:24 dssuperset python3.9[17740]:    util.raise_(
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
Jul  4 10:32:24 dssuperset python3.9[17740]:    raise exception
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
Jul  4 10:32:24 dssuperset python3.9[17740]:    self.dialect.do_execute(
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
Jul  4 10:32:24 dssuperset python3.9[17740]:    cursor.execute(statement, parameters)
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/MySQLdb/cursors.py", line 179, in execute
Jul  4 10:32:24 dssuperset python3.9[17740]:    res = self._query(mogrified_query)
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/MySQLdb/cursors.py", line 330, in _query
Jul  4 10:32:24 dssuperset python3.9[17740]:    db.query(q)
Jul  4 10:32:24 dssuperset python3.9[17740]:  File "/opt/superset/lib64/python3.9/site-packages/MySQLdb/connections.py", line 261, in query
Jul  4 10:32:24 dssuperset python3.9[17740]:    _mysql.connection.query(self, query)
Jul  4 10:32:24 dssuperset python3.9[17740]: sqlalchemy.exc.OperationalError: (MySQLdb.OperationalError) (1267, "Illegal mix of collations (utf8_bin,NONE) and (binary,IGNORABLE) for operation '='")
Jul  4 10:32:24 dssuperset python3.9[17740]: [SQL: SELECT count(*) AS count_1
Jul  4 10:32:24 dssuperset python3.9[17740]: FROM (SELECT dbs.uuid AS dbs_uuid, dbs.created_on AS dbs_created_on, dbs.changed_on AS dbs_changed_on, dbs.id AS dbs_id, dbs.verbose_name AS dbs_verbose_name, dbs.database_name AS dbs_database_name, dbs.sqlalchemy_uri AS dbs_sqlalchemy_uri, dbs.password AS dbs_password, dbs.cache_timeout AS dbs_cache_timeout, dbs.select_as_create_table_as AS dbs_select_as_create_table_as, dbs.expose_in_sqllab AS dbs_expose_in_sqllab, dbs.configuration_method AS dbs_configuration_method, dbs.allow_run_async AS dbs_allow_run_async, dbs.allow_file_upload AS dbs_allow_file_upload, dbs.allow_ctas AS dbs_allow_ctas, dbs.allow_cvas AS dbs_allow_cvas, dbs.allow_dml AS dbs_allow_dml, dbs.force_ctas_schema AS dbs_force_ctas_schema, dbs.extra AS dbs_extra, dbs.encrypted_extra AS dbs_encrypted_extra, dbs.impersonate_user AS dbs_impersonate_user, dbs.server_cert AS dbs_server_cert, dbs.is_managed_externally AS dbs_is_managed_externally, dbs.external_url AS dbs_external_url, dbs.created_by_fk AS dbs_created_by_fk, dbs.changed_by_fk AS dbs_changed_by_fk, changed_by.id AS changed_by_id, changed_by.first_name AS changed_by_first_name, changed_by.last_name AS changed_by_last_name, changed_by.username AS changed_by_username, changed_by.password AS changed_by_password, changed_by.active AS changed_by_active, changed_by.email AS changed_by_email, changed_by.last_login AS changed_by_last_login, changed_by.login_count AS changed_by_login_count, changed_by.fail_login_count AS changed_by_fail_login_count, changed_by.created_on AS changed_by_created_on, changed_by.changed_on AS changed_by_changed_on, changed_by.created_by_fk AS changed_by_created_by_fk, changed_by.changed_by_fk AS changed_by_changed_by_fk, created_by.id AS created_by_id, created_by.first_name AS created_by_first_name, created_by.last_name AS created_by_last_name, created_by.username AS created_by_username, created_by.password AS created_by_password, created_by.active AS created_by_active, created_by.email AS created_by_email, created_by.last_login AS created_by_last_login, created_by.login_count AS created_by_login_count, created_by.fail_login_count AS created_by_fail_login_count, created_by.created_on AS created_by_created_on, created_by.changed_on AS created_by_changed_on, created_by.created_by_fk AS created_by_created_by_fk, created_by.changed_by_fk AS created_by_changed_by_fk
Jul  4 10:32:24 dssuperset python3.9[17740]: FROM dbs LEFT OUTER JOIN ab_user AS changed_by ON dbs.changed_by_fk = changed_by.id LEFT OUTER JOIN ab_user AS created_by ON dbs.created_by_fk = created_by.id
Jul  4 10:32:24 dssuperset python3.9[17740]: WHERE dbs.allow_file_upload = 1 AND true = 1 AND (concat(concat(concat(concat(%s, dbs.database_name), %s), CAST(dbs.id AS CHAR)), %s) IN (NULL) AND (1 != 1) OR dbs.database_name IN (NULL) AND (1 != 1))) AS anon_1]
Jul  4 10:32:24 dssuperset python3.9[17740]: [parameters: ('[', '].(id:', ')')]
Jul  4 10:32:24 dssuperset python3.9[17740]: (Background on this error at: https://sqlalche.me/e/14/e3q8)
Jul  4 10:32:25 dssuperset python3.9[17739]: 2024-07-04 10:32:25,588:INFO:flask_wtf.csrf:The CSRF token is missing.
Jul  4 10:32:25 dssuperset python3.9[17739]: Refresh CSRF token error
Jul  4 10:32:25 dssuperset python3.9[17739]: Traceback (most recent call last):
Jul  4 10:32:25 dssuperset python3.9[17739]:  File "/opt/superset/lib64/python3.9/site-packages/flask_wtf/csrf.py", line 261, in protect
Jul  4 10:32:25 dssuperset python3.9[17739]:    validate_csrf(self._get_csrf_token())
Jul  4 10:32:25 dssuperset python3.9[17739]:  File "/opt/superset/lib64/python3.9/site-packages/flask_wtf/csrf.py", line 100, in validate_csrf
Jul  4 10:32:25 dssuperset python3.9[17739]:    raise ValidationError("The CSRF token is missing.")
Jul  4 10:32:25 dssuperset python3.9[17739]: wtforms.validators.ValidationError: The CSRF token is missing.
Jul  4 10:32:25 dssuperset python3.9[17739]: During handling of the above exception, another exception occurred:
Jul  4 10:32:25 dssuperset python3.9[17739]: Traceback (most recent call last):
Jul  4 10:32:25 dssuperset python3.9[17739]:  File "/opt/superset/lib64/python3.9/site-packages/flask/app.py", line 1482, in full_dispatch_request
Jul  4 10:32:25 dssuperset python3.9[17739]:    rv = self.preprocess_request()
Jul  4 10:32:25 dssuperset python3.9[17739]:  File "/opt/superset/lib64/python3.9/site-packages/flask/app.py", line 1974, in preprocess_request
Jul  4 10:32:25 dssuperset python3.9[17739]:    rv = self.ensure_sync(before_func)()
Jul  4 10:32:25 dssuperset python3.9[17739]:  File "/opt/superset/lib64/python3.9/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
Jul  4 10:32:25 dssuperset python3.9[17739]:    self.protect()
Jul  4 10:32:25 dssuperset python3.9[17739]:  File "/opt/superset/lib64/python3.9/site-packages/flask_wtf/csrf.py", line 264, in protect
Jul  4 10:32:25 dssuperset python3.9[17739]:    self._error_response(e.args[0])
Jul  4 10:32:25 dssuperset python3.9[17739]:  File "/opt/superset/lib64/python3.9/site-packages/flask_wtf/csrf.py", line 307, in _error_response
Jul  4 10:32:25 dssuperset python3.9[17739]:    raise CSRFError(reason)
Jul  4 10:32:25 dssuperset python3.9[17739]: flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF token is missing.
Jul  4 10:32:25 dssuperset python3.9[17739]: 2024-07-04 10:32:25,589:WARNING:superset.views.base:Refresh CSRF token error
Jul  4 10:32:25 dssuperset python3.9[17739]: Traceback (most recent call last):
Jul  4 10:32:25 dssuperset python3.9[17739]:  File "/opt/superset/lib64/python3.9/site-packages/flask_wtf/csrf.py", line 261, in protect
Jul  4 10:32:25 dssuperset python3.9[17739]:    validate_csrf(self._get_csrf_token())
Jul  4 10:32:25 dssuperset python3.9[17739]:  File "/opt/superset/lib64/python3.9/site-packages/flask_wtf/csrf.py", line 100, in validate_csrf
Jul  4 10:32:25 dssuperset python3.9[17739]:    raise ValidationError("The CSRF token is missing.")
Jul  4 10:32:25 dssuperset python3.9[17739]: wtforms.validators.ValidationError: The CSRF token is missing.
Jul  4 10:32:25 dssuperset python3.9[17739]: During handling of the above exception, another exception occurred:
Jul  4 10:32:25 dssuperset python3.9[17739]: Traceback (most recent call last):
Jul  4 10:32:25 dssuperset python3.9[17739]:  File "/opt/superset/lib64/python3.9/site-packages/flask/app.py", line 1482, in full_dispatch_request
Jul  4 10:32:25 dssuperset python3.9[17739]:    rv = self.preprocess_request()
Jul  4 10:32:25 dssuperset python3.9[17739]:  File "/opt/superset/lib64/python3.9/site-packages/flask/app.py", line 1974, in preprocess_request
Jul  4 10:32:25 dssuperset python3.9[17739]:    rv = self.ensure_sync(before_func)()
Jul  4 10:32:25 dssuperset python3.9[17739]:  File "/opt/superset/lib64/python3.9/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
Jul  4 10:32:25 dssuperset python3.9[17739]:    self.protect()
Jul  4 10:32:25 dssuperset python3.9[17739]:  File "/opt/superset/lib64/python3.9/site-packages/flask_wtf/csrf.py", line 264, in protect
Jul  4 10:32:25 dssuperset python3.9[17739]:    self._error_response(e.args[0])
Jul  4 10:32:25 dssuperset python3.9[17739]:  File "/opt/superset/lib64/python3.9/site-packages/flask_wtf/csrf.py", line 307, in _error_response
Jul  4 10:32:25 dssuperset python3.9[17739]:    raise CSRFError(reason)
Jul  4 10:32:25 dssuperset python3.9[17739]: flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF token is missing.

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by cosmincioranu** [comment]
Thank you for reply,

In superset_config.py i use

SQLALCHEMY_DATABASE_URI =  
***@***.***/***?collation=utf8_unicode_ci&charset=utf8'

which matches with the database used. Unfortunately this does not work.

-- 
Cosmin CIORANU
Head of IT Department
The Executive Agency For Higher Education, Research, Development And
Innovation Funding (UEFISCDI)
E-mail: ***@***.***
Address: Mendeleev st., no. 21 – 25, room 15, sector 1, Bucharest,
Romania, postal code 010362.

**Comment by sfirke** [comment]
Are you using MariaDB as your metadata store?  Superset is only tested to work with MySQL and Postgres as metadata DBs.  Unfortunately a few other users have reported problems using MariaDB for this purpose.  This does not seem like a bug in Superset, nor is it actionable for the project, so I'm going to close this.  There was discussion about [officially declaring MariaDB unsupported](https://github.com/apache/superset/discussions/26741) -- that was never resolved, and maybe we should warn people away from it so more people don't get into this situation.

That said, if you figure out a way forward -- migrating your data to MySQL or fixing something in your metadata DB -- feel free to report back here as it might benefit others.

**Comment by cosmincioranu** [comment]
Salve,

The issue has been fixed by converting database to utf8mb4 and collation to utf8mb4_unicode_ci, previusly the database was in utf8 (no mb4), I b

At this point I think deeming mariadb as unsuported is a little bit extreeme. Moreover limiting superset of not using mariadb gets at the core of superset versability.

Thank you for your answer.





CC @uefiscdi



-------- Original message --------
From: Sam Firke ***@***.***>
Date: 7/31/24 17:00 (GMT+02:00)
To: apache/superset ***@***.***>
Cc: Cosmin Cioranu ***@***.***>, Mention ***@***.***>
Subject: Re: [apache/superset] Database Issue when using mariadb 10.4, illegal mixx (Issue #29483)


Are you using MariaDB as your metadata store? Superset is only tested to work with MySQL and Postgres as metadata DBs. Unfortunately a few other users have reported problems using MariaDB for this purpose. This does not seem like a bug in Superset, nor is it actionable for the project, so I'm going to close this. There was discussion about officially declaring MariaDB unsupported<https://github.com/apache/superset/discussions/26741> -- that was never resolved, and maybe we should warn people away from it so more people don't get into this situation.

That said, if you figure out a way forward -- migrating your data to MySQL or fixing something in your metadata DB -- feel free to report back here as it might benefit others.

**Comment by sfirke** [comment]
Thank you for sharing what worked for you!  Until Superset is tested continuously to work with MariaDB, I would be worried about people setting up new instances using it as a backend.  That said, if some people insist on using MariaDB as a backend, it's good to have them sharing what problems they find and how to overcome them, as you did - much appreciated.

**Comment by Chase-H** [comment]
I am having the exact same issue with MySQL 8 as a backend

**Comment by cosmincioranu** [comment]
My solution was to reconvert database to utf8mb collation  
utf8mb4_unicode_ci via (the database and all tables within via Alter  
database and alter table convert), and set up the uri in sqlalchemy by  
adding ?collation=utf8mb4&charset=utfmb4_unicode_ci

Also, I would suggest to add all permissions (maybe except grant) to the  
application user on that specific database, otherwise strange errors may  
pop up in your logs.

Hope it helps.

Cosmin

**Comment by Chase-H** [comment]
Thanks for replying. I do not think this actually comes down to a database issue, I think this is an issue with how superset is feeding in params. I have a similar error message as you with the same first set of parameters: `[parameters: ('[', '].(id:', ')')]`. These values are causing the issue, but also, they do not make sense when filled into the actual query. This feels like the source code is just incorrectly parsing parameter values, but it is very unclear where this query originates.
