### ISSUE TITLE
Slack Notification - deprecated API 

### ISSUE THREAD

**Issue by PuszekSE** [apache/superset#29480]
### Bug description

When attempting to send the notification it seems to be failing due to Slack API deprecation:

```
[2024-07-03 04:13:16,531: WARNING/ForkPoolWorker-16] SupersetError(message="The request to the Slack API failed. (url: https://www.slack.com/api/files.upload)\nThe server responded with: {'ok': False, 'error': 'method_deprecated'}", error_type=<SupersetErrorType.REPORT_NOTIFICATION_ERROR: 'REPORT_NOTIFICATION_ERROR'>, level=<ErrorLevel.WARNING: 'warning'>, extra=None)
header_data in notifications for alerts and reports {'notification_type': 'Alert', 'notification_source': <ReportSourceFormat.DASHBOARD: 'dashboard'>, 'notification_format': 'PNG', 'chart_id': None, 'dashboard_id': 1, 'owners': [...]}, taskid, 52c32a04-bce5-45a9-9add-511c252908fa

[2024-07-03 04:13:16,579: INFO/ForkPoolWorker-16] header_data in notifications for alerts and reports {'notification_type': 'Alert', 'notification_source': <ReportSourceFormat.DASHBOARD: 'dashboard'>, 'notification_format': 'PNG', 'chart_id': None, 'dashboard_id': 1, 'owners': [...]}, taskid, 52c32a04-bce5-45a9-9add-511c252908fa
SupersetError(message='[Errno 111] Connection refused', error_type=<SupersetErrorType.REPORT_NOTIFICATION_ERROR: 'REPORT_NOTIFICATION_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra=None)

[2024-07-03 04:13:16,581: WARNING/ForkPoolWorker-16] SupersetError(message='[Errno 111] Connection refused', error_type=<SupersetErrorType.REPORT_NOTIFICATION_ERROR: 'REPORT_NOTIFICATION_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra=None)
A downstream warning occurred while generating a report: 52c32a04-bce5-45a9-9add-511c252908fa. [SupersetError(message="The request to the Slack API failed. (url: https://www.slack.com/api/files.upload)\nThe server responded with: {'ok': False, 'error': 'method_deprecated'}", error_type=<SupersetErrorType.REPORT_NOTIFICATION_ERROR: 'REPORT_NOTIFICATION_ERROR'>, level=<ErrorLevel.WARNING: 'warning'>, extra=None)]
Traceback (most recent call last):
  File "/app/superset/tasks/scheduler.py", line 90, in execute
    AsyncExecuteReportScheduleCommand(
  File "/app/superset/commands/report/execute.py", line 721, in run
    raise ex
  File "/app/superset/commands/report/execute.py", line 717, in run
    ReportScheduleStateMachine(
  File "/app/superset/commands/report/execute.py", line 678, in run
    state_cls(
  File "/app/superset/commands/report/execute.py", line 582, in next
    raise first_ex
  File "/app/superset/commands/report/execute.py", line 551, in next
    self.send()
  File "/app/superset/commands/report/execute.py", line 451, in send
    self._send(notification_content, self._report_schedule.recipients)
  File "/app/superset/commands/report/execute.py", line 442, in _send
    raise ReportScheduleClientErrorsException(errors=notification_errors)
superset.commands.report.exceptions.ReportScheduleClientErrorsException: [SupersetError(message="The request to the Slack API failed. (url: https://www.slack.com/api/files.upload)\nThe server responded with: {'ok': False, 'error': 'method_deprecated'}", error_type=<SupersetErrorType.REPORT_NOTIFICATION_ERROR: 'REPORT_NOTIFICATION_ERROR'>, level=<ErrorLevel.WARNING: 'warning'>, extra=None)]
```

### How to reproduce the bug

1. Setup notification via Slack using SLACK_TOKEN_API
2. Send dashboard as a notification to the channel

### Screenshots/recordings

<img width="466" alt="image" src="https://github.com/apache/superset/assets/4567127/1e7a1e4e-43d7-42f1-8b29-50a81340ab37">

<img width="461" alt="image" src="https://github.com/apache/superset/assets/4567127/358a7620-7975-4ad6-823f-332f77a7ebfc">

<img width="255" alt="image" src="https://github.com/apache/superset/assets/4567127/eb10f2e2-cd92-426e-8111-dac00ddf6916">

### Superset version

master / latest-dev

### Python version

Not applicable

### Node version

Not applicable

### Browser

Not applicable

### Additional context

It's k8s based deployment based on 4.0.2rc-dev image if that matters anyhow.

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by VedantBopardikar** [comment]
Where can i find this code to replace it in superset files?

**Comment by rusackas** [comment]
I think this has recently been patched on master. @eschutho would know the most here, I think.

**Comment by PuszekSE** [comment]
I've checked this on 4.0.2-dev, 1-2 days after its release (although that isn't an option present on the version dropdown list).

**Comment by VedantBopardikar** [comment]
changing the function in  superset/reports/notifications/slack.py. from files_upload to files_upload_v2 worked for me. Also the recipients in superset for slack should be channel IDs and not usernames.

**Comment by PuszekSE** [comment]
https://github.com/apache/superset/pull/29264
https://github.com/apache/superset/pull/29264

I believe those were related PRs

**Comment by eschutho** [comment]
Correct, the above two prs will fix this issue. There's one outstanding issue to be merged to fix the backend runtime migrations: https://github.com/apache/superset/pull/29721

**Comment by Chethanibms** [comment]
With reference to the link https://github.com/apache/superset/issues/29480#issuecomment-2207685012
where do we need to change the slack `files_upload_v2` in my helm chart

**Comment by Chethanibms** [comment]
@dosu getting error 
```
superset.commands.report.exceptions.ReportScheduleClientErrorsException: [SupersetError(message="The request to the Slack API failed. (url: https://www.slack.com/api/files.upload)\nThe server responded with: {'ok': False, 'error': 'method_deprecated'}", error_type=<SupersetErrorType.REPORT_NOTIFICATION_ERROR: 'REPORT_NOTIFICATION_ERROR'>, level=<ErrorLevel.WARNING: 'warning'>, extra=None)]
```
where do i need to change the `files_upload_v2` in my helm chart

**Comment by eschutho** [comment]
If you are running Superset 4.1 or later you will be using the Slack v2 api if your Slack app has the correct scopes. Your logs will say which scopes you need to add if they are missing. You will also need to set this flag to true: `ALERT_REPORT_SLACK_V2`
