### ISSUE TITLE
Unable to create a SQL SERVER database connection

### ISSUE THREAD

**Issue by hmily3913** [apache/superset#29497]
### Bug description

When creating a new database connection, fill in the correct URI, click Test Connection, and the username, password, and database error are displayed, which is actually correct.Error prompts such as pictures

### How to reproduce the bug

1. docker compose 4.0.0 
2. MySQL is used as the metadata database（The data is from version 1.4.0）
3. docker exec -it superset_app /bin/bash，telnet 10.0.0.7 1433 succeed
4. 
pip install pymssql
superset db upgrade
superset init
docker restart superset_app
6. web login，add database connection，select other，use SQLAlchemy URI，“mssql+pymssql://sa:rightpass@10.0.0.7:1433/xx” 
7. test connection ,then Error
8. 

### Screenshots/recordings

![image](https://github.com/apache/superset/assets/3221165/3e637fa5-0413-46f8-9d08-8da6ba42c5dd)

### Superset version

4.0.1

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

2024-07-05 06:20:49,729:DEBUG:superset.stats_logger:[stats_logger] (incr) DatabaseRestApi.test_connection.error
2024-07-05 06:20:49,730:WARNING:superset.views.base:SupersetErrorsException
Traceback (most recent call last):
  File "/app/superset/commands/database/test_connection.py", line 171, in run
    raise DBAPIError(ex_str or None, None, None)
sqlalchemy.exc.DBAPIError: (builtins.NoneType) None
[SQL: (pymssql.exceptions.OperationalError) (20002, b'DB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (10.0.0.7)\nDB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (10.0.0.7)\n')
(Background on this error at: https://sqlalche.me/e/14/e3q8)]
(Background on this error at: https://sqlalche.me/e/14/dbapi)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/base_api.py", line 127, in wraps
    raise ex
  File "/app/superset/views/base_api.py", line 121, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/app/superset/utils/core.py", line 1463, in time_function
    response = func(*args, **kwargs)
  File "/app/superset/utils/log.py", line 255, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/views/base_api.py", line 93, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/databases/api.py", line 920, in test_connection
    TestConnectionDatabaseCommand(item).run()
  File "/app/superset/commands/database/test_connection.py", line 200, in run
    raise SupersetErrorsException(errors) from ex
superset.exceptions.SupersetErrorsException: [SupersetError(message='Either the username "sa", password, or database name "xx" is incorrect.', error_type=<SupersetErrorType.CONNECTION_ACCESS_DENIED_ERROR: 'CONNECTION_ACCESS_DENIED_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'Microsoft SQL Server', 'issue_codes': [{'code': 1014, 'message': 'Issue 1014 - Either the username or the password is wrong.'}, {'code': 1015, 'message': 'Issue 1015 - Either the database is spelled incorrectly or does not exist.'}]})]

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by Habeeb556** [comment]
@hmily3913 The password contains "@", you can escape the "@" character using "%40" instead.

**Comment by hmily3913** [comment]
> @hmily3913 The password contains "@", you can escape the "@" character using "%40" instead.

After modification, prompt
> 错误: (sqlalchemy_uri) Invalid connection string, a valid string usually follows: backend+driver://user:password@database-host/database-name

**Comment by Habeeb556** [comment]
> > @hmily3913 The password contains "@", you can escape the "@" character using "%40" instead.
> 
> After modification, prompt
> 
> > 错误: (sqlalchemy_uri) Invalid connection string, a valid string usually follows: backend+driver://user:password@database-host/database-name

@hmily3913 The standard connection string is as follows:

```
mssql+pymssql://sa:password@10.100.20.30:1433/TEST
```

However, if the password contains an "@", you should replace it. Instead of writing it like this:

```
mssql+pymssql://sa:hello@1@10.100.20.30:1433/TEST
```

You should write it like this:

```
mssql+pymssql://sa:hello%401@10.100.20.30:1433/TEST
```

**Comment by hmily3913** [comment]
> > > @hmily3913 The password contains "@", you can escape the "@" character using "%40" instead.
> > 
> > 
> > After modification, prompt
> > > 错误: (sqlalchemy_uri) Invalid connection string, a valid string usually follows: backend+driver://user:password@database-host/database-name
> 
> @hmily3913 The standard connection string is as follows:
> 
> ```
> mssql+pymssql://sa:password@10.100.20.30:1433/TEST
> ```
> 
> However, if the password contains an "@", you should replace it. Instead of writing it like this:
> 
> ```
> mssql+pymssql://sa:hello@1@10.100.20.30:1433/TEST
> ```
> 
> You should write it like this:
> 
> ```
> mssql+pymssql://sa:hello%401@10.100.20.30:1433/TEST
> ```

thx，password dont contain any special characters

**Comment by hmily3913** [comment]
The version of pymssql is 2.3.0
 Version: freetds v1.3.17
In container, i code a testsql.py like this:
`import pymssql 
 
conn = pymssql.connect(host='10.0.0.7:1433', user='sa', password='loginpwd', database='xxpt')
 
if conn:
    print(f"连接成功{conn}-----")`

Error:
pymssql._mssql.MSSQLDatabaseException: (20002, b'DB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (10.0.0.7)\nDB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (10.0.0.7)\n')

ping 10.0.0.7 ,telnet 10.0.0.7 1433 
Work right

**Comment by hmily3913** [comment]
pymssql version change to 2.2.7

**Comment by shzxd** [comment]
work for me
pymssql._mssql.MSSQLDatabaseException: (20002, b'DB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (10.0.0.7)\nDB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (10.0.0.7)\n')

**Comment by wuji766** [comment]
> pymssql version change to 2.2.7

你问题解决了吗，我连SQL server 2012 遇到了同样的问题
