### ISSUE TITLE
DRILL_TO_DETAIL

### ISSUE THREAD

**Issue by 1sarah** [apache/superset#29491]
### Bug description

Drill to detail doesn't apply filters when using jinja tempating

### How to reproduce the bug

Embedded dashboard

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Thank you, but I'll close this (as a duplicate) in favor of https://github.com/apache/superset/issues/27396.
