### ISSUE TITLE
Histogram Metrics other than COUNT

### ISSUE THREAD

**Issue by arulferiandevops** [apache/superset#29534]
Hi all

I would like to ask related to HISTOGRAM CHART METRICS. "On the histogram chart, I can only find the COUNT metric, but I want to use the percentage metric. Is it possible to do that?

## Screenshot
![Histogram](https://github.com/apache/superset/assets/149508752/44cc08f5-e958-4541-b00a-26245e527c23)

## Description
we aim to create histograms using percentage metrics instead of count. As shown in the attached Histogram.png, there is no option to set the metric in the histogram chart. Is it possible to create?

Thanks

**Comment by arulferiandevops** [comment]
Hi @dosu , I have already deployed Apache Superset using Helm values. To make the code changes you mentioned above (using the normalize property), where in the file/folder should I make the changes?

**Comment by rusackas** [comment]
CC @michael-s-molina as author of the newer (ECharts) histogram chart.

**Comment by michael-s-molina** [comment]
Hi @arulferiandevops. You can check the `normalize` option in the Customize tab.

<img width="1478" alt="Screenshot 2024-07-10 at 15 14 47" src="https://github.com/apache/superset/assets/70410625/890601a6-87e9-428b-8cae-e8de32d9e010">
