### ISSUE TITLE
[Dev build] Stacked chart tooltip highlights a different series than the one I'm hovering over

### ISSUE THREAD

**Issue by clavidk** [apache/superset#29565]
## Screenshot

<img width="693" alt="image" src="https://github.com/user-attachments/assets/7e63ec9b-f40b-4427-a60f-3b26174b831a">

## Description

On a stacked bar chart with data zoom enabled, when I hover over one of the series, the series that gets highlighted in the tooltip does not match the series my cursor is over.

To reproduce:
1. Create a stacked bar chart with multiple series, 
2. Sort stack by total
3. Make sure your dataset is one where the value for each series each day changes such that the series with the largest value is not always the same each day
4. Hover over one of the series, hover to the next series, etc. 
5. Observe which series is highlighted in the tooltip
6. You will see that as you go down the stacked bar, it just moves down the tooltip legend which is not

**Comment by rusackas** [comment]
Hmm, that's odd... I'm unable to reproduce the issue. What version of Superset are you running?

**Comment by clavidk** [comment]
I'm running the latest dev build. I also don't get this with simple stacked charts, but when I have a stacked chart with a LOT of series that differ day to day (many series only show up on a few days).
