### ISSUE TITLE
Error 'DISALLOWED_SQL_FUNCTION' in new superset update 4.0.2

### ISSUE THREAD

**Issue by JatinVenkatesh** [apache/superset#29575]
### Bug description

I updated the Docker image of Superset to the latest in my docker-compose file, which is 4.0.2. After this, I'm unable to read any data from the dataset. But when I revert back to 4.0.1, there is no issue with the SQL executions. 
![image](https://github.com/user-attachments/assets/554c3274-6789-4497-8e56-5bcd0bada3b7)

### How to reproduce the bug

1. Update the docker-compose file to the latest (4.0.2).
2. Create a database connection.
3. Write an query to get data.
4. Error - 'DISALLOWED_SQL_FUNCTION'

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by michael-s-molina** [comment]
Wow. @dosubot nailed!

**Comment by JatinVenkatesh** [comment]
Thank you, @dosu. It's working now.
