### ISSUE TITLE
Compose file './docker-compose.yml' invalid 

### ISSUE THREAD

**Issue by F041** [apache/superset#29583]
### Bug description

I followed https://superset.apache.org/docs/installation/docker-compose/ and I got this
```
~/superset$ docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.db.env_file contains {"path": "docker/.env", "required": true}, which is an invalid type, it should be a string
services.superset.env_file contains {"path": "docker/.env", "required": true}, which is an invalid type, it should be a string
services.superset-init.env_file contains {"path": "docker/.env", "required": true}, which is an invalid type, it should be a string
services.superset-node.env_file contains {"path": "docker/.env", "required": true}, which is an invalid type, it should be a string
services.superset-tests-worker.env_file contains {"path": "docker/.env", "required": true}, which is an invalid type, it should be a string
services.superset-worker.env_file contains {"path": "docker/.env", "required": true}, which is an invalid type, it should be a string
services.superset-worker-beat.env_file contains {"path": "docker/.env", "required": true}, which is an invalid type, it should be a string

```
on an ubuntu ARM machine

### How to reproduce the bug

I followed https://superset.apache.org/docs/installation/docker-compose/

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by mistercrunch** [comment]
I just tried to upgrade to latest docker-compose (ob my macbook pro M2 from 2.25.0 to 2.28.1) and fired `$ docker-compose up` without issues, what version are you on?

**Comment by F041** [comment]
docker-compose version 1.29.2, before running

```
sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

# Apply executable permissions to the binary
sudo chmod +x /usr/local/bin/docker-compose

# Verify the installation
docker-compose version
```
then I got 
`docker-compose version 1.29.2, build unknown
and same error
`

**Comment by mistercrunch** [comment]
Time to upgrade your docker-compose

**Comment by mistercrunch** [comment]
Adding this utility, it should help people set up dev environments -> https://github.com/apache/superset/pull/29609

**Comment by F041** [comment]
Solved doing something I feared: 
`**sudo rm /usr/local/bin/docker-compose**
`
and ofc then 
```
sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
```
now I got v2.29

It took over 10 minutes to complete the docker-compose up, though (ARM, 4VCPU)

**Comment by alephpt** [comment]
In case anyone else ends up here as a result of `SUPERSET_SECRET_KEY=TEST_NON_DEV_SECRET` and you are looking in config.py, constants.py, superset_config.py .. don't forget to check `/docker/.env` and `/docker/.env_non_dev` if you are having issues with these settings.

I spent quite a while chasing down the location of that env over-ride, before realizing where it was.
