### ISSUE TITLE
Superset 4.0.2 : Table Chart - Column Based Total Calculation

### ISSUE THREAD

**Issue by oyku-buyukakin** [apache/superset#29639]
## Screenshot

<img width="230" alt="Ekran görüntüsü 2024-07-17 102630" src="https://github.com/user-attachments/assets/eefac775-acc3-46f3-8aa5-00c3c94e6009">

## Description
Hello, I recently started using Superset 4.0.2. As in the example I added above, I want to create a table with the total of the column below in the table I created. But when I used the table or pivot table chart, I always got the totals added to the right in a new column. I would be very glad if you could help me how I can do this.

## Design input
                            A       B      C
groupa                 1       2      3
groupb                 4       5      6
Total                     5       7      9

**Comment by michael-s-molina** [comment]
https://github.com/user-attachments/assets/4fa33add-8a7b-4eb5-8dc8-9f4bfa54a7e6
