### ISSUE TITLE
superset_node build failure @nx/nx-linux-x64-gnu missing module

### ISSUE THREAD

**Issue by fisjac** [apache/superset#29658]
### Bug description

When trying to deploy using docker compose, I'm receiving a missing module error. It appears this bug first emerged in PR https://github.com/apache/superset/pull/29419 specifically commit hash: c30ca534a38f624bfc87fcfa1c1161b542115822

### How to reproduce the bug

Checkout latest master branch
Clear the docker cache of previous superset images
Rebuild images with docker compose build
Run docker compose up 

### Screenshots/recordings

![image](https://github.com/user-attachments/assets/775fe0db-b65e-4d8a-992c-a28d863b8de0)

### Superset version

master / latest-dev

### Python version

3.10

### Node version

18 or greater

### Browser

Chrome

### Additional context

As a workaround to other build errors, I've edited Dockerfile line 27 from
`ARG NPM_BUILD_CMD="build"`
to
`ARG NPM_BUILD_CMD="build-dev"`

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by bobular** [comment]
I got this too.

Manually adding it as a devDependency seems to work as a workaround for me. Though I am still having problems logging in as admin/admin.

```diff
diff --git a/superset-frontend/package.json b/superset-frontend/package.json
index bb7a2face8..bba6bef5a7 100644
--- a/superset-frontend/package.json
+++ b/superset-frontend/package.json
@@ -226,6 +226,7 @@
     "@emotion/jest": "^11.11.0",
     "@hot-loader/react-dom": "^16.14.0",
     "@istanbuljs/nyc-config-typescript": "^1.0.1",
+    "@nx/nx-linux-x64-gnu": "^18.3.5",
     "@storybook/addon-actions": "^8.1.11",
     "@storybook/addon-controls": "^8.1.11",
     "@storybook/addon-essentials": "^8.1.11",
```

**Comment by rusackas** [comment]
@hainenber have you run into this, or do you see any obvious solutions?

**Comment by fisjac** [comment]
I've gotten around this by debumping to `"lerna": "^6.6.2",` in `package.json`

**Comment by hainenber** [comment]
heya folks, apologies for inconvenience brought upon. I'm checking this issue, was a busy week previously :D

**Comment by hainenber** [comment]
The `@nx` dependencies are optional and in this build script, `docker-frontend`, for building FE module in containerized environment, doesn't install optional dependencies


https://github.com/apache/superset/blob/master/docker/docker-frontend.sh#L26-L29

**Comment by hainenber** [comment]
> I got this too.
> 
> Manually adding it as a devDependency seems to work as a workaround for me. Though I am still having problems logging in as admin/admin. That was just a cookie issue.
> 
> ```diff
> diff --git a/superset-frontend/package.json b/superset-frontend/package.json
> index bb7a2face8..bba6bef5a7 100644
> --- a/superset-frontend/package.json
> +++ b/superset-frontend/package.json
> @@ -226,6 +226,7 @@
>      "@emotion/jest": "^11.11.0",
>      "@hot-loader/react-dom": "^16.14.0",
>      "@istanbuljs/nyc-config-typescript": "^1.0.1",
> +    "@nx/nx-linux-x64-gnu": "^18.3.5",
>      "@storybook/addon-actions": "^8.1.11",
>      "@storybook/addon-controls": "^8.1.11",
>      "@storybook/addon-essentials": "^8.1.11",
> ```

This wouldn't work on larger scale since people's machines are diverse in terms of OS and architecture. Here's what happened on my machine. 

```
(#########⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠴ idealTree:@esri/calcite-components: timing id
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @nx/nx-linux-x64-gnu@18.3.5: wanted {"os":"linux","cpu":"x64"} (current: {"os":"darwin","cpu":"arm64"})
npm ERR! notsup Valid os:   linux
npm ERR! notsup Actual os:  darwin
npm ERR! notsup Valid cpu:  x64
npm ERR! notsup Actual cpu: arm64
```

There's a heavy workaround in the linked PR but if that isn't ideal, I'll downgrade to Lerna 6 asap.
