### ISSUE TITLE
Garbled characters on the agent page in the development environment

### ISSUE THREAD

**Issue by monsterkai233** [apache/superset#29678]
### Bug description

localhost:8088 display normal, but localhost:9000 display garbled code
![image](https://github.com/user-attachments/assets/dcd408e2-d31f-4799-8646-a695b72ebc60)
![image](https://github.com/user-attachments/assets/1e8c017e-bbb7-4f60-b5f0-0fcbdc466eb8)

### How to reproduce the bug

node: 18.19.1
superset: 4.0.1
https://superset.apache.org/docs/contributing/development/#webpack-dev-server

### Superset version

master / latest-dev

### Python version

3.11

### Node version

18 or greater

### Browser

Chrome

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by monsterkai233** [comment]
> 嗨，你好！我在这里帮助您解决任何错误、问题或贡献。让我们一起解决这个问题，同时等待人工维护者。
> 
> 出现乱码可能是由于 Webpack 开发服务器未运行。要解决此问题，请确保 Webpack 开发服务器与 Flask 服务器并行启动。步骤如下：`localhost:9000`
> 
> 1. 在端口上启动 Flask 服务器：`8088`
>    ```shell
>    superset run -p 8088 --with-threads --reload --debugger --debug
>    ```
> 2. 同时，在端口上启动 Webpack 开发服务器：`9000`
>    ```shell
>    npm run dev-server
>    ```
> 
> 在您的 Web 浏览器中访问。此设置可确保前端资产得到正确服务和热重新加载，同时后端请求被代理到在端口上运行的 Flask 服务器`http://localhost:9000``8088` [[1]](https://github.com/apache/superset/blob/master/docs/docs/contributing/development.mdx).
> 
> 如果问题仍然存在，请检查文件是否存在与端口、公共路径或代理设置相关的任何错误配置`webpack.config.js`[[2]](https://github.com/apache/superset/blob/master/superset-frontend/webpack.config.js).
> 
> _要继续与 [Dosu](https://dosu.dev) 交谈，请提及 。_

My webpack.config.js correctly configured, bug is same [https://github.com/apache/superset/issues/29677](url)

**Comment by rusackas** [comment]
Hmm... I'm getting this now too. Not sure how far back this goes...

**Comment by rusackas** [comment]
Ok, turns out this is a duplicate issue. Closing this one in favor of https://github.com/apache/superset/issues/29678

The linked issue provides a solution, but we're still in need of a fix to make localhost rather than your machine's IP address work as expected.

**Comment by SmithAdoph** [comment]
I encountered the same issue. It might be because the frontend and backend are deployed on different servers. When I deployed both locally, there was no garbled text. However, I'm unsure why the issue occurs when deployed on separate servers. The exact reason is unclear
