### ISSUE TITLE
Dev-server page isn't rendered

### ISSUE THREAD

**Issue by goldjee** [apache/superset#29677]
### Bug description

After installing all dependencies and running dev-server, I get broken page at `http://localhost:9000`.

I've found the same very old issue [#12040](https://github.com/apache/superset/issues/12040). The author supposed that it is specific to Chrome. But both Chrome and Firefox show broken page. Also it's worth mentioning that, as far as I see, there are no related errors in terminal or console output.

### How to reproduce the bug

1. Install Superset without Docker

```bash
source venv/bin/activate
pip install -r requirements/development.txt
pip install -e .

cd superset-frontend
npm ci
```

2. Run Superset

```bash
export SUPERSET_CONFIG_PATH=./docker/pythonpath_dev/superset_config_local.py
superset run -p 8088 --with-threads --reload
```

3. Run development server

```bash
npm run dev-server
```

4. Navigate to http://localhost:9000

### Screenshots/recordings

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/674a8225-2388-4c1a-802c-020b908678e6">

### Superset version

master / latest-dev

### Python version

3.11

### Node version

18 or greater

### Browser

Chrome

### Additional context

node.js version: `18.20.4` (same error on `22.5.1`)

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by goldjee** [comment]
@dosu Nope, it didn't work.

**Comment by monsterkai233** [comment]
> 不，它没有用。

I tried the same thing and it didn't work

**Comment by monsterkai233** [comment]
@goldjee hi bro, I use safari and it's working fine

**Comment by goldjee** [comment]
@monsterkai233 Hi! Good tip, Safari works. But I'm much more used to Chrome dev tools, so it would be great if maintainers could take a look.

@rusackas @michael-s-molina

**Comment by michael-s-molina** [comment]
Hi @goldjee. I also noticed this problem but haven't had the time to take a look. Hope other maintainers can fix it. In the meantime, I discovered that it works on Chrome if you use the IP address instead of `localhost`.

**Comment by michael-s-molina** [comment]
Let me tag @geido @rusackas as the leaders of dev experience group.

**Comment by goldjee** [comment]
> Hi @goldjee. I also noticed this problem but haven't had the time to take a look. I hope other maintainers can fix it. In the meantime, I discovered that it works on Chrome if you use the IP address instead of `localhost`.

Hi! Thank you for the suggestion. Just tried `http://127.0.0.1:9000` and had the same result :(

**Comment by michael-s-molina** [comment]
Not 127.0.0.1, your real IP such as 192....

**Comment by goldjee** [comment]
Ah, I see. Yep, internal LAN IP worked.

**Comment by geido** [comment]
I have got around that b6 downgrading to node 16.20. Superset isn't heavily tested on Node 18.

**Comment by michael-s-molina** [comment]
> I have got around that by downgrading to node 16.20. Superset isn't heavily tested on Node 18.

@geido I'm able to reproduce this issue with Node v16.20.2

**Comment by rusackas** [comment]
Node 20 doesn't seem to magically fix this. Still looking for a good fix...

**Comment by geido** [comment]
Setting `COMPRESS_REGISTER = False` in superset config has helped some people getting around this issue.

**Comment by rusackas** [comment]
Fixed! Closing this thanks to https://github.com/apache/superset/pull/30034
