### ISSUE TITLE
Ephemeral instances no longer have any example data

### ISSUE THREAD

**Issue by sadpandajoe** [apache/superset#29694]
### Bug description

When you spin up an ephemeral instance in a PR, example data such as dashboard, charts, etc. no longer exist.

### How to reproduce the bug

1. Go to a PR
2. Spin up an ephemeral
3. Log into the ephemeral
4. Go to the dashboard list

Notice that the dashboard list is empty where we used to have example dashboards.

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by sadpandajoe** [comment]
@michael-s-molina we tracked it down to your PR: https://github.com/apache/superset/pull/28789 that was causing this. Wondering if you have time to take a look at this?

**Comment by michael-s-molina** [comment]
@sadpandajoe @eschutho I executed the load examples command many times in my dev environment so I believe if might be something with the ephemeral environment. Do you have any additional information about the error? Any logs? 

I'm really busy for the next days so feel free to revert the PR if needed.

**Comment by rusackas** [comment]
This might be a clue for anyone looking into this: https://github.com/apache/superset/issues/27633

**Comment by sadpandajoe** [comment]
@michael-s-molina I've created this PR to revert in case if you can't get to this before 4.1 is ready: https://github.com/apache/superset/pull/29766. Will hold off from merging for now.
