### ISSUE TITLE
Slack Invite is Broken

### ISSUE THREAD

**Issue by natesinger** [apache/superset#29701]
### Bug description

Hi team,

I am trying to join the community to contribute a couple of features and I tried joining the slack but it looks like the link is broken. Can someone please update it or provide the invite here so I can access the channels to start these discussions?

r/Nate

### How to reproduce the bug

1. https://superset.apache.org/community/
2. Try to click the link for slack
3. "This link is no longer active, To join this workspace, you’ll need to ask the person who originally invited you for a new link."

### Screenshots/recordings

<img width="630" alt="Screenshot 2024-07-25 at 11 06 33 AM" src="https://github.com/user-attachments/assets/a8d3655a-e4b5-46ac-8bd0-d62536562b50">

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Eek! Thanks for calling this out. OF COURSE the invitations got used up while I was away on vacation :/ 

[this link](http://bit.ly/join-superset-slack) should work now, if you want to try again.
