### ISSUE TITLE
4.1.0rc1 Druid queries with CURRENT_TIMETAMP fails

### ISSUE THREAD

**Issue by iercan** [apache/superset#29729]
### Bug description

I'm testing 4.1.0rc1 and encountering an error with Druid datasets that use the CURRENT_TIMESTAMP function. It seems to be adding parentheses at the end, which is causing the failure, even though we don't define any in the metric.

### How to reproduce the bug

1. Create a metric that use CURRENT_TIMESTAMP on druid dataset
2. Use metric in a chart

### Screenshots/recordings

How metric looks like
![image](https://github.com/user-attachments/assets/32da4ffd-a8ed-4ec0-ab73-0bead7dbc574)

How superset sends query
![image](https://github.com/user-attachments/assets/c1bc6c1d-23a6-439b-94de-7b2eaff8c1f7)

Given error 
![image](https://github.com/user-attachments/assets/d5c31ac7-a8e3-4e85-9a85-975bd9ea6c6b)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Pinging some folks from the [rolodex](https://docs.google.com/spreadsheets/d/1U1qxiLvOX0kBTUGME1AHHi6Ywel6ECF8xk_Qy-V9R8c/edit?gid=0#gid=0) that might be able to help repro/test/fix.

@betodealmeida
@sujiplr
@nytai
@villebro

**Comment by sadpandajoe** [comment]
I don't see anything that has changed in the `DruidEngineSpec` files, but I did see we did bump `pydruid`. @betodealmeida @eschutho do you think that could have affect this?

**Comment by mistercrunch** [comment]
I tried to recreate using `sqlparse.format` but couldn't, got GPT to write this, but wasn't conclusive

```python
import sqlparse

sql = "SELECT case when __time > TIMESTAMPADD(DAY, -7, CURRENT_DATE) AND __time < TIMESTAMPADD(DAY, -7, CURRENT_DATE) FROM t;"
formatted_sql = sqlparse.format(sql, reindent=True, keyword_case='upper', strip_comments=True)

print(formatted_sql)
```

**Comment by mistercrunch** [comment]
Also reviewed https://github.com/apache/superset/blob/master/superset/db_engine_specs/druid.py for SQL mutation logic that would be Druid specific and couldn't find anything...

**Comment by eschutho** [comment]
@iercan can you add the version of your druid db and the driver?

**Comment by mistercrunch** [comment]
@betodealmeida might have some intuition as to what might be adding those `()` after `CURRENT_TIMESTAMP` (?)

**Comment by iercan** [comment]
> @iercan can you add the version of your druid db and the driver?

Apologies for the late reply. Druid version is 30.0.0 and pydruid is 0.6.9.

**Comment by iercan** [comment]
Error has gone on 4.1.0rc3
