### ISSUE TITLE
Bar Chart: Bar Chart Echart X Axis and Y Axis labels not showing

### ISSUE THREAD

**Issue by Candyman1406** [apache/superset#29877]
### Bug description

When creating a bar chart, we are able to add the x axis and y axis labels. However, upon editing the labels, the x axis and y axis labels gets removed. Besides, the x axis label rotation does not function as well. 

### How to reproduce the bug

1. Go to chart page and click on + Chart
2. Select a dataset and bar chart
3. Input the required data and generate the chart. 
4. In the customize tab, add an x-axis and y-axis label together with the label rotation. 
5. Save the chart, exit the page and select the saved chart from the chart list. 
6. Edit the x-axis and y-axis label, the label will the removed. 

### Screenshots/recordings

1. Image when first time creating chart
![image](https://github.com/user-attachments/assets/7f2b91d0-a92c-429c-8704-433629c6a9c0)

2. Image after saving the chart and editing the x axis, y axis label
![image](https://github.com/user-attachments/assets/055eee7c-1346-4701-b27e-dcfc800efc7c)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

1. This issue happens inconsistently, where sometimes only the x-axis is removed and sometimes both are removed. 
2. Certain times, reloading the page fixes the issue. 

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by Candyman1406** [comment]
@dosu the renderTrigger has already been set to true and the configuration in Echarts option are also correctly set. However, this issue is still present.

**Comment by geido** [comment]
---

### 🎉 **Preset Bounty Available: $150 USD** 🎉

To claim this bounty, please carefully follow the steps below.

---

#### 📋 **Steps to Participate**

1. **Review Guidelines:**  
   Read through the [Preset Bounty Program Contribution Guide](https://preset.notion.site/preset-bounty-program-apache-superset) for complete details on bounty requirements.

2. **Show Your Interest:**  
   Complete the [Preset Bounty Program Survey](https://docs.google.com/forms/d/e/1FAIpQLSeDsR1iWvPxFydUIXs2agsUg3kMDaAooeD4P9P1L5sI0Yu5QQ/viewform?usp=sharing) and comment this issue to express your interest.

3. **Join the Slack Channel:**  
   After completing the survey, you’ll receive an invitation to the dedicated [Apache Superset Slack](https://join.slack.com/t/apache-superset/shared_invite/zt-2be0drwz8-bxPfkdz28ozzk1Iox29ufg) channel.

4. **Get Assigned:**  
   To officially start, ensure a **Bounty Program Manager** has assigned you to this issue.

5. **Submit Your Solution:**  
   When ready, submit your solution with the `Fixes #{issue_number}` notation in your Pull Request description.

6. **Claim Your Bounty:**  
   Sign up at [GitPay.me](https://gitpay.me/) and submit your solution via: [https://gitpay.me/#/task/983](https://gitpay.me/#/task/983)

---

#### 💡 **Additional Notes**

- Only developers assigned by a **Bounty Program Manager** should start working on this issue to win the bounty.
- Be sure to follow the guide closely to avoid any delays in payment. Please, allow a few days after your PR has been merged for the bounty to be released.

Good luck, and happy coding! 🎉

**Comment by DamianPendrak** [comment]
Is it related to #30370 ? I created a PR that should fix this issue.

**Comment by DamianPendrak** [comment]
Yes, according to my testing, it solves this issue too.
