### ISSUE TITLE
Importing example dataset failes because of database constraint

### ISSUE THREAD

**Issue by jelu** [apache/superset#29915]
### Bug description

Importing example dataset failes because of unique constraint on table names.

### How to reproduce the bug

```
superset load-examples
```

### Screenshots/recordings

```
2024-08-12 10:36:20,506:INFO:superset.models.helpers:Importing new tables public.wb_health_population
Traceback (most recent call last):
  File "/home/jerry/de-cix/superset/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/jerry/de-cix/superset/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: tables.table_name
```

### Superset version

master / latest-dev

### Python version

3.10

### Node version

I don't know

### Browser

Not applicable

### Additional context

I just followed [flask server setup](https://superset.apache.org/docs/contributing/development/) to hit it.

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by michael-s-molina** [comment]
Fixed by https://github.com/apache/superset/pull/29993
