### ISSUE TITLE
[4.1.0rc1] Building Docker image from sources fails

### ISSUE THREAD

**Issue by exolightor** [apache/superset#29931]
### Bug description

Hello Superset-Team,

we are trying to build the superset docker image from the pre-release 4.1.0rc on GitHub. Running docker build however leads to an error as seen below. This error also occurres in our CI environments. Will this be fixed in the next release? 

### How to reproduce the bug

1. git clone https://github.com/apache/superset.git
2. cd superset
3. git checkout tags/4.1.0rc1
4. docker build -t superset .

### Screenshots/recordings

![superset-docker](https://github.com/user-attachments/assets/edb65fde-ce22-4dfe-ac7d-f5a6e771a8f4)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

18 or greater

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by exolightor** [comment]
yes this workaround fixes it. Running npm install after deleting package-lock.json did not work for me but just running npm install did. Closing the issue.

**Comment by rusackas** [comment]
This is odd... I didn't run into it. Please give 4.1.0rc2 a test for this when it comes out soon. When that happens, it'll be announced on the dev mailing list.

If you haven't already, you can subscribe to the Apache Superset Dev Mailing Listserv ([dev@superset.apache.org](mailto:dev@superset.apache.org), with public visibility [here](https://lists.apache.org/list.html?dev@superset.apache.org)) by sending an email to [dev-subscribe@superset.apache.org](mailto:dev-subscribe@superset.apache.org).
