### ISSUE TITLE
Set Specific Time for Dashboard Refresh

### ISSUE THREAD

**Issue by aprendizlaura** [apache/superset#29968]
Hi there,

I’m currently using the "refresh_frequency" parameter in the JSON Metadata to set my dashboards to refresh every 24 hours. However, I need to know if there’s a way to specify a specific time for the refresh, such as 3 AM.

Is there an existing parameter or method to achieve this? If so, how can I implement it?

Thank you!

**Comment by aprendizlaura** [comment]
@dosu  When I try to set that parameter in my JSON METADATA, I get this error:
Sorry, there was an error saving this dashboard: [object Object]

**Comment by aprendizlaura** [comment]
@dosu if my configuration is:
...
"color_scheme": "",
"refresh_frequency": 86400,
"expanded_slices": {},
"timed_refresh_immune_slices": [],
"cross_filters_enabled": true,
"default_filters": "{}",
...
everything works perfectly. The problem occurs if I change
"refresh_frequency": 86400 to "refresh_frequency": "0 3 * * *"

**Comment by rusackas** [comment]
Sorry, this isn't currently a feature. You can use the Alerts & Reports feature to schedule sending an email or Slack message with the dashboard's content (basically a screenshot) at any given time, but the dashboard refresh rate is currently interval-based. I guess if you want to get up at 3am and refresh it then with a 24 hour rate, you could. Or maybe 9pm with a 6 hour cycle or something ;) If you want to advocate for this as a feature, you can open an Ideas thread here on GitHub Discussions, or if you want to contribute it as a new parameter (e.g. regresh_time), you could open a PR and/or SIP.

**Comment by aprendizlaura** [comment]
@rusackas thank you so so much ;)
