### ISSUE TITLE
Viz Plugin is not building anymore

### ISSUE THREAD

**Issue by victorfonseca** [apache/superset#29995]
### Bug description

When I just follow the basic process to create a plugin, the build process is not working anymore. I did following the README steps, and the error always prompt:

npm ci
npm run build
npm warn deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm warn deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm warn deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm warn deprecated har-validator@5.1.5: this library is no longer supported
npm warn deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm warn deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm warn deprecated left-pad@1.3.0: use String.prototype.padStart()
npm warn deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm warn deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm warn deprecated @boost/core@1.18.7: Package has been deprecated. Core has been split into multiple stand-alone packages. https://github.com/milesj/boost

added 1431 packages, and audited 1432 packages in 21s

110 packages are looking for funding
  run `npm fund` for details

68 vulnerabilities (47 moderate, 17 high, 4 critical)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

> keyward-chart-01@0.1.0 prebuild
> rimraf {lib,esm,tsconfig.tsbuildinfo}

> keyward-chart-01@0.1.0 build
> npm run build-cjs && npm run build-esm && npm run ts-types

> keyward-chart-01@0.1.0 build-cjs
> babel src --extensions ".ts,.tsx,.js,.jsx" --copy-files --out-dir lib

Successfully compiled 7 files with Babel (398ms).

> keyward-chart-01@0.1.0 build-esm
> BABEL_OUTPUT=esm babel src --extensions ".ts,.tsx,.js,.jsx" --copy-files --out-dir esm

Successfully compiled 7 files with Babel (284ms).

> keyward-chart-01@0.1.0 ts-types
> tsc --build

> keyward-chart-01@0.1.0 postbuild
> npm run test

> keyward-chart-01@0.1.0 test
> jest

 FAIL  test/plugin/transformProps.test.ts
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.

    ReferenceError: window is not defined

      17 |  * under the License.
      18 |  */
    > 19 | import { ChartProps, supersetTheme } from '@superset-ui/core';
         | ^
      20 | import transformProps from '../../src/plugin/transformProps';
      21 |
      22 | describe('KeywardChart01 transformProps', () => {

      at Object.<anonymous> (node_modules/@superset-ui/core/lib/utils/logging.js:24:17)
      at Object.<anonymous> (node_modules/@superset-ui/core/lib/utils/index.js:45:39)
      at Object.<anonymous> (node_modules/@superset-ui/core/lib/index.js:13:14)
      at Object.require (test/plugin/transformProps.test.ts:19:1)

 FAIL  test/plugin/buildQuery.test.ts
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.

    ReferenceError: window is not defined

      17 |  * under the License.
      18 |  */
    > 19 | import { buildQueryContext, QueryFormData } from '@superset-ui/core';
         | ^
      20 |
      21 | /**
      22 |  * The buildQuery function is used to create an instance of QueryContext that's

      at Object.<anonymous> (node_modules/@superset-ui/core/lib/utils/logging.js:24:17)
      at Object.<anonymous> (node_modules/@superset-ui/core/lib/utils/index.js:45:39)
      at Object.<anonymous> (node_modules/@superset-ui/core/lib/index.js:13:14)
      at Object.require (src/plugin/buildQuery.ts:19:1)
      at Object.require (test/plugin/buildQuery.test.ts:19:1)

 FAIL  test/index.test.ts
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.

    ReferenceError: window is not defined

      17 |  * under the License.
      18 |  */
    > 19 | import { t, ChartMetadata, ChartPlugin } from '@superset-ui/core';
         | ^
      20 | import buildQuery from './buildQuery';
      21 | import controlPanel from './controlPanel';
      22 | import transformProps from './transformProps';

      at Object.<anonymous> (node_modules/@superset-ui/core/lib/utils/logging.js:24:17)
      at Object.<anonymous> (node_modules/@superset-ui/core/lib/utils/index.js:45:39)
      at Object.<anonymous> (node_modules/@superset-ui/core/lib/index.js:13:14)
      at Object.require (src/plugin/index.ts:19:1)
      at Object.require (src/index.ts:20:1)
      at Object.require (test/index.test.ts:19:1)

Test Suites: 3 failed, 3 total
Tests:       0 total
Snapshots:   0 total
Time:        0.588 s
Ran all test suites.

### How to reproduce the bug

Create the plugin with YO, follow the steps and then:

# keyward-chart-01

This is the Keyward Chart 01 Superset Chart Plugin.

### Usage

To build the plugin, run the following commands:

```
npm ci
npm run build
```

### Superset version

master / latest-dev

### Python version

Not applicable

### Node version

18 or greater

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by victorfonseca** [comment]
I'm still not able to build a plugin, anyone has any recent interactions with it?

**Comment by hainenber** [comment]
> I'm still not able to build a plugin, anyone has any recent interactions with it?

Yes, that was me with this [upgrade PR](https://github.com/apache/superset/pull/29414). Apologies for the inconvenience!

Jest v29 no longer brings along JSDOM so we have to explicitly configure in Jest config and add into `package.json`. If you're getting blocked atm, please help following the changes in linked PR.
