### ISSUE TITLE
Cache setting Redis, still reporting exception upon startup!

### ISSUE THREAD

**Issue by Sdreamery** [apache/superset#30003]
### Bug description

In version 4.0, I have already set the cache storage path and placed it in Redis, where I can see the cached data. However, when starting with gunicorn, I still encounter an exception: UserWarning: Using the in memory storage for tracking rate limits as no storage was explicitly specified This is not recommended for production use. See:  https://flask-limiter.readthedocs.io#configuring -a-storage-backend for documentation about configuring the storage backend.
![image](https://github.com/user-attachments/assets/c22800de-4039-454f-b3bc-5886ba612bdb)
![image](https://github.com/user-attachments/assets/721a5bb6-1d2c-465e-9b43-c4d94f4c9f2f)
![image](https://github.com/user-attachments/assets/7b465867-fe64-4cb3-87c0-b6caf4682283)

### How to reproduce the bug

I don't know what to do.

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by Sdreamery** [comment]
I'm sure the Redis configuration is correct, because in the Redis database, you can see that cached data has been written in! Additionally, my Redis configuration comes with a password, so the configuration link should be: Redis://: password@host :port/0

**Comment by Sdreamery** [comment]
> The warning you're encountering suggests that the rate limiting storage backend is not correctly configured to use Redis. To resolve this, ensure that the `RATELIMIT_STORAGE_URI` is set to your Redis URI in your `superset_config.py` file.
> 
> Here is the relevant configuration you need to add or verify:
> 
> ```python
> RATELIMIT_STORAGE_URI = "redis://host:port"
> ```
> 
> Replace `"redis://host:port"` with the actual URI of your Redis server. Additionally, ensure that the `redis` Python package is installed:
> 
> ```shell
> pip install Flask-Limiter[redis]
> ```
> 
> This should configure Flask-Limiter to use Redis for rate limiting, avoiding the fallback to in-memory storage [[1]](https://github.com/apache/superset/blob/master/superset/config.py)[[2]](https://github.com/apache/superset/blob/master/tests/integration_tests/superset_test_config.py).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

I'm sure the Redis configuration is correct, because in the Redis database, you can see that cached data has been written in! Additionally, my Redis configuration comes with a password, so the configuration link should be: Redis://:password@host :port/0

**Comment by Sdreamery** [comment]
> The warning you're encountering suggests that the rate limiting storage backend is not correctly configured to use Redis. To resolve this, ensure that the `RATELIMIT_STORAGE_URI` is set to your Redis URI in your `superset_config.py` file.
> 
> Here is the relevant configuration you need to add or verify:
> 
> ```python
> RATELIMIT_STORAGE_URI = "redis://host:port"
> ```
> 
> Replace `"redis://host:port"` with the actual URI of your Redis server. Additionally, ensure that the `redis` Python package is installed:
> 
> ```shell
> pip install Flask-Limiter[redis]
> ```
> 
> This should configure Flask-Limiter to use Redis for rate limiting, avoiding the fallback to in-memory storage [[1]](https://github.com/apache/superset/blob/master/superset/config.py)[[2]](https://github.com/apache/superset/blob/master/tests/integration_tests/superset_test_config.py).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

Sure enough, after setting the parameter RATELIMIT-STORAGE-URI, not only did this problem solve, but another alarm (Warning: root: Class' werkzeug. local. LocalProxy 'is not mapped) also disappeared. Thank you very much!

**Comment by rusackas** [comment]
@Sdreamery Glad it worked out! If you can think of a way to improve the code comments and/or documentation, let us know!

**Comment by PHTremor** [comment]
> > The warning you're encountering suggests that the rate limiting storage backend is not correctly configured to use Redis. To resolve this, ensure that the `RATELIMIT_STORAGE_URI` is set to your Redis URI in your `superset_config.py` file.
> > Here is the relevant configuration you need to add or verify:
> > RATELIMIT_STORAGE_URI = "redis://host:port"
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Replace `"redis://host:port"` with the actual URI of your Redis server. Additionally, ensure that the `redis` Python package is installed:
> > pip install Flask-Limiter[redis]
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This should configure Flask-Limiter to use Redis for rate limiting, avoiding the fallback to in-memory storage [[1]](https://github.com/apache/superset/blob/master/superset/config.py)[[2]](https://github.com/apache/superset/blob/master/tests/integration_tests/superset_test_config.py).
> > _To continue talking to [Dosu](https://dosu.dev), mention [@dosu](https://github.com/dosu)._
> 
> Sure enough, after setting the parameter RATELIMIT-STORAGE-URI, not only did this problem solve, but another alarm (Warning: root: Class' werkzeug. local. LocalProxy 'is not mapped) also disappeared. Thank you very much!

I there a way to have the RATELIMIT_STORAGE_URI = "redis://host:port" inside values.yaml?

that way it can be resolved after helm update install...
