### ISSUE TITLE
flask_log.current_user set to None in SQL_QUERY_MUTATOR while using SQLLab

### ISSUE THREAD

**Issue by dmarkey** [apache/superset#30168]
### Bug description

While implementing a SQL_QUERY_MUTATOR to manipulate the SQL.. the `flask_login.current_user` is None, but is set to the correct user while navigating graphs.

### How to reproduce the bug

config.py:

```
MUTATE_AFTER_SPLIT = True


def SQL_QUERY_MUTATOR(  # pylint: disable=invalid-name,unused-argument
    sql: str, **kwargs
) -> str:
    print(flask_login.current_user) ## will be None suring a SQLLab session
    return sql

```

### Superset version

master / latest-dev

### Python version

3.9

### Node version

18 or greater

### Browser

Chrome

### Additional context

Basically reopening https://github.com/apache/superset/issues/20455

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by dmarkey** [comment]
That actually works.. first time I've been impressed by AI.

**Comment by dmarkey** [comment]
closing

**Comment by divick-vama** [comment]
@dosu how to defined SQL_QUERY_MUTATOR in superset_config.py
