### ISSUE TITLE
Superset 4.1.0RC2 - Dashboard embedding - now includes editor and last modified timestamp

### ISSUE THREAD

**Issue by nemccarthy** [apache/superset#30188]
### Bug description

The latest 4.1.0rc2 has in the dashboard header a username and last modified timestamp. This doesn't make sense for the embedded use case and should be hidden from the dashboard title. 

This should be hidden just like the Published tag as this is metadata that doesnt make sense outside of the superset app. 

Introduced in #27857

### How to reproduce the bug

1. Create a dashboard
2. Embed the dashboard in a page 
3. View embedded page with very superset specific metadata. 

### Screenshots/recordings

<img width="264" alt="image" src="https://github.com/user-attachments/assets/44d0b107-d4d9-47f0-a11f-07af20009ed1">

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Looks like `npm run lint-fix` might solve a lot of the CI problems :)
