### ISSUE TITLE
zstd not found by superset_node during docker compose up dev mode

### ISSUE THREAD

**Issue by MialLewis** [apache/superset#30206]
### Bug description

When running `webpack` I get the following error on `master`:

```
superset_node         | [webpack-cli] Failed to load '/app/superset-frontend/webpack.config.js' config
superset_node         | [webpack-cli] Error: Can not access zstd! Is it installed?
```

Related conversation in PR, where I mention a hacky solution: https://github.com/apache/superset/pull/30034#issuecomment-2339582050

Raising this to increase visibility in case anyone else encounters.

### How to reproduce the bug

`docker compose up` on `master` branch.

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by birkskyum** [comment]
I hit this error too.

**Comment by victorfonseca** [comment]
Why they close it? Is still the same for everyone.

**Comment by victorfonseca** [comment]
Same here, anyone found how to workaround this issue?

**Comment by MialLewis** [comment]
> Same here, anyone found how to workaround this issue?

If you read the PR linked in the description there’s a hacky solution to get things moving.

**Comment by riekusr** [comment]
some issue here on ubuntu
