### ISSUE TITLE
Superset-4.1.0rc2: Download to CSV option is not showing up in SQL LAB page.

### ISSUE THREAD

**Issue by rabindragogoi** [apache/superset#30204]
### Bug description

In SqlLab the download to CSV option is not showing up to download the data. This option we can see in 3.0.0 version of superset but in 4.1.0rc2 it is not showing up even though I am assigned as an **_Admin user_**.

Screenshot: 4.1.0rc02:

![image](https://github.com/user-attachments/assets/a04fc0a4-0cc3-4e4a-8083-ccf68dfbce9e)

Screenshot: 3.0.0:

![image](https://github.com/user-attachments/assets/c9e39283-2d1b-4ec8-ba52-2ab03b8086d5)

@michael-s-molina @sadpandajoe : Is there any change in the UI for this functionality.?

### How to reproduce the bug

In superset 4.0.1rc02. 

Run a query in SQL LAB and check if you can see the download to csv option.

### Superset version

master / latest-dev

### Python version

3.11

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rabindragogoi** [comment]
Hi @michael-s-molina , @sadpandajoe : The answer from @dosubot did not helped me here. As I mentioned this download to csv feature is working good in earlier version(3.0.0) of superset. I tried with both ALLOW_FULL_CSV_EXPORT as True and False (though earlier I kept it as false it is still working in 3.0.0), it is not working in 4.1.0rc02.

**Comment by sadpandajoe** [comment]
@rabindragogoi does this work with 4.0.2? Trying to determine if this is a regression as part of 4.1.0rc2 or if it was broken between 3.0.0 and now.

**Comment by rabindragogoi** [comment]
Hi @sadpandajoe : No it is not working in 4.0.2. Infact sql lab with presto database connection is not working in 4.0.2.

**Comment by michael-s-molina** [comment]
> Hi @sadpandajoe : No it is not working in 4.0.2. Infact sql lab with presto database connection is not working in 4.0.2.

@rabindragogoi I believe this is something with your deployment. You can access a test environment for 4.0.2 [here](https://github.com/apache/superset/pull/27174) and the `Download to CSV` option is available.

<img width="1511" alt="Screenshot 2024-09-11 at 14 17 36" src="https://github.com/user-attachments/assets/095e60d9-03f8-4028-9070-1402b597d65b">

**Comment by rabindragogoi** [comment]
Hi @michael-s-molina : Trying with 4.0.2 will not work for me because in this version querying with presto database connection is showing error in SQLLab. I raised this issue earlier and thats why you asked me to try 4.1.0rc2.

Could you check if the download to csv is working in 4.1.0rc2 ?

**Comment by michael-s-molina** [comment]
@rabindragogoi @sadpandajoe It's working for 4.0.2 but not working for 4.1.0RC2. It looks like the `Download to CSV` and `Copy to Clipboard` options are missing on 4.1.0RC2.

<img width="1503" alt="Screenshot 2024-09-12 at 08 17 18" src="https://github.com/user-attachments/assets/fd3efb97-f47e-41d1-aca9-39a227a31e80">

@sadpandajoe This will be a blocker for the release as it's a regression from 4.0.2.

**Comment by michael-s-molina** [comment]
> Hi @michael-s-molina : Trying with 4.0.2 will not work for me because in this version querying with presto database connection is showing error in SQLLab. I raised this issue earlier and thats why you asked me to try 4.1.0rc2.

@rabindragogoi Just to confirm that this is working in 4.0.2 with a Presto connection.

<img width="1506" alt="Screenshot 2024-09-12 at 08 21 04" src="https://github.com/user-attachments/assets/8ee28517-13ae-4cc1-a200-6472aedd2607">

**Comment by rabindragogoi** [comment]
Hi @michael-s-molina : Let me reverify once. I will update here.

**Comment by rabindragogoi** [comment]
Hi @michael-s-molina : Yes. I am able to download data from Superset now .(Version 4.0.2). Issue was with my Flask-AppBuilder version. I was using Flask-AppBuilder==4.4.1. Now I am using Flask-AppBuilder==4.5.0. Which is working now.

**Comment by rabindragogoi** [comment]
Issue closed

**Comment by michael-s-molina** [comment]
@rabindragogoi I reopened the issue as it's happening on 4.1.0RC2.

**Comment by betodealmeida** [comment]
I wasn't able to repro this — I checked out the tag 4.1.0rc2, rebuilt the assets with `npm run build`, started Trino on docker and it works for me:

<img width="1013" alt="Screenshot 2024-09-17 at 5 22 17 PM" src="https://github.com/user-attachments/assets/f047c8b9-7bb7-454c-921c-3ff02cea1aeb">

Is this database-dependent? Should I use Presto instead of Trino?

**Comment by michael-s-molina** [comment]
Thanks for checking this @betodealmeida. I was not able to reproduce either. Let's close this issue and reopen it if necessary.

**Comment by rabindragogoi** [comment]
Hi @michael-s-molina : The csv download option is not showing up in Superset 4.1.1. I raised an another issue ticget for this.

https://github.com/apache/superset/issues/31395
