### ISSUE TITLE
Failed to resolve entry for package "@superset-ui/switchboard". The package may have incorrect main/module/exports specified in its package.json.

### ISSUE THREAD

**Issue by thanhdc-97** [apache/superset#30207]
### Bug description

I am using "vite": "5.3.1" and "react": "18.3.1",

when I run yarn add @superset-ui/embedded-sdk ("@superset-ui/embedded-sdk": "^0.1.0-alpha.12") and import it using import { embedDashboard } from '@superset-ui/embedded-sdk', an error occurs when running yarn dev even though it worked fine before;

### How to reproduce the bug

1. Run yarn add @superset-ui/embedded-sdk
2. Create a file and import as follows:
 - import { embedDashboard } from '@superset-ui/embedded-sdk';
3. Run yarn dev

### Screenshots/recordings

![image](https://github.com/user-attachments/assets/0dfa9792-7fd1-4f8b-8faa-f42d58d1a8bf)
![image](https://github.com/user-attachments/assets/fd6d9b2c-a3d0-4146-8930-27069c8aa611)
![image](https://github.com/user-attachments/assets/884c0bff-6426-47f8-a7c2-fc240f0856cb)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

18 or greater

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by hainenber** [comment]
RC found. When you add `@superset-ui/embedded-sdk`, it'll pull its dependency `@superset-ui/switchboard` which according to [this semver semantic](https://github.com/apache/superset/blob/master/superset-embedded-sdk/package.json#L36), to be `0.18.27`. For some unknown reasons, the compiled codes are purged in this version!

Source: https://www.npmjs.com/package/@superset-ui/switchboard/v/0.18.27?activeTab=code

<img width="843" alt="image" src="https://github.com/user-attachments/assets/d79b9ee1-0174-42f2-9474-7b58573f98df">

I'll probably open a PR to fix this
