### ISSUE TITLE
Superset 4.1.0RC2 - New Sankey charts cannot be embedded = "Guest user cannot modify chart payload"

### ISSUE THREAD

**Issue by nemccarthy** [apache/superset#30205]
### Bug description

When adding the new ECharts version of the Sankey to a dashboard that is embedded using the embedding SDK using a guest user token the chart will not render with error `Guest user cannot modify chart payload` 

### How to reproduce the bug

1. Create a new Sankey chart 
2. Create a new dashboard and add the Sankey chart to the new dash
3. Embed the dashboard into a web app using the embed functionality in Superset to get the embedding ID and add it using the embedding SDK. 
4. Create a guest token using the embedding SDK 
5. Load the page as a guest user (loading chart not logged in the superset UI works fine)

### Screenshots/recordings

<img width="914" alt="image" src="https://github.com/user-attachments/assets/109133db-cc82-4eb8-a8da-4e5f42e9e249">

### Superset version

master / latest-dev

### Python version

3.9

### Node version

18 or greater

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
@betodealmeida I know you'd done some work around an error with the same text. Not sure if we "missed a spot," this is something new, or there's a fix coming in RC3. CC @sadpandajoe who may also have context here.

**Comment by sadpandajoe** [comment]
@nemccarthy does this work with the legacy sankey chart?

**Comment by sadpandajoe** [comment]
@nemccarthy do you also have logs? I wasn't able to reproduce this on one of my embedded dashboards and it shows up just fine.
