### ISSUE TITLE
Bangladesh is missing in country map dropdown selection for Country Map Chart

### ISSUE THREAD

**Issue by hsnbd** [apache/superset#30223]
### Bug description

Bangladesh Missing from Country Map Chart

Apache Superset Version: 4.0.2 (installed via pip in a virtual environment)

Issue: Bangladesh is missing from the Country Map Chart in my installation, despite an update being committed in this github repo 4 months ago that added several countries, including Bangladesh.

[Commit reference](https://github.com/apache/superset/commit/cafc1a2c13eef303480beb8c68ec02b79dea31a9)

Could this be an issue with the 4.0.2 release, or do I need to take additional steps to ensure the Country Map Chart includes Bangladesh?

### How to reproduce the bug

1. Goto charts
2. Select Country Map and Dataset
3. Create a new chart
4. Find `Bangladesh` in Country list dropdown

### Superset version

4.0.2

### Python version

3.10

### Node version

18 or greater

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Features don't get cherried into patch releases. It'll be part of 4.1, which you can test now.
