### ISSUE TITLE
Temporary failure resolving 'deb.debian.org'

### ISSUE THREAD

**Issue by wuf-Gavin** [apache/superset#30249]
### Bug description

=> CANCELED [superset-websocket build 5/5] RUN npm ci &&   npm run build                                                                                                                                                                 210.5s
=> ERROR [superset-worker-beat superset-node  3/14] RUN apt-get update -qq     && apt-get install         -yqq --no-install-recommends         build-essential         python3         zstd                                              168.4s
------
> [superset-worker-beat superset-node  3/14] RUN apt-get update -qq     && apt-get install         -yqq --no-install-recommends         build-essential         python3         zstd:
168.3 W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Temporary failure resolving 'deb.debian.org'
168.3 W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Temporary failure resolving 'deb.debian.org'
168.3 W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Temporary failure resolving 'deb.debian.org'
168.3 W: Some index files failed to download. They have been ignored, or old ones used instead.
168.4 E: Unable to locate package build-essential
168.4 E: Unable to locate package python3
168.4 E: Unable to locate package zstd

**Comment by wuf-Gavin** [comment]
> Hey @wuf-Gavin! I'm here to help you with any bugs, questions, or contributions you have for the project while you wait for a human maintainer. Let's squash those bugs together!
> 
> I found a similar open issue that might be related to your problem: [sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "db" to address: Name or service not known](https://github.com/apache/superset/issues/29492) [[1]](https://github.com/apache/superset/issues/29492). The suggested solution involves ensuring that the database service is up and running before starting Superset, checking the database configuration, and removing old database volumes.
> 
> Additionally, there are known issues in the Superset Docker setup that could affect the `apt-get update` process. The Dockerfile includes multiple `apt-get update` commands followed by `apt-get install` commands, and it also includes the removal of `/var/lib/apt/lists/*` to clean up after installations. This can lead to issues if the `apt-get update` cache is not available when subsequent `apt-get install` commands are run [[2]](https://github.com/apache/superset/blob/master/Dockerfile).
> 
> To resolve the DNS resolution issue during the Docker build process, you can try the following steps:
> 
> 1. **Ensure Proper DNS Configuration:**
>    Add the following to your `docker-compose.yml` to ensure proper DNS resolution:
>    ```yaml
>    services:
>      superset:
>        extra_hosts:
>          - "deb.debian.org:your-dns-server-ip"
>    ```
> 2. **Update Dockerfile:**
>    Modify the Dockerfile to ensure `apt-get update` is run before any `apt-get install` commands and avoid removing the apt cache prematurely:
>    ```dockerfile
>    RUN apt-get update -qq && apt-get install -yqq --no-install-recommends \
>        build-essential \
>        python3 \
>        zstd \
>        && rm -rf /var/lib/apt/lists/*
>    ```
> 3. **Check Network Configuration:**
>    Ensure that your Docker daemon is configured to use a reliable DNS server. You can set this in the Docker daemon configuration file (`/etc/docker/daemon.json`):
>    ```json
>    {
>      "dns": ["8.8.8.8", "8.8.4.4"]
>    }
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Then restart the Docker daemon:
>    ```shell
>    sudo systemctl restart docker
>    ```
> 
> These steps should help resolve the DNS resolution issue and ensure proper package installation during the Docker build process.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._



 => [superset-websocket stage-1 6/6] RUN npm ci --omit=dev                                                                                                                                                                                  2.7s 
 => [superset-websocket] exporting to image                                                                                                                                                                                                 0.4s 
 => => exporting layers                                                                                                                                                                                                                     0.4s
 => => writing image sha256:7d36ee11c88d5e7e8a4088bef36d267017de6a774ed8ee669d217214a655be6c                                                                                                                                                0.0s
 => => naming to docker.io/library/superset-superset-websocket                                                                                                                                                                              0.0s
------                                                                                                                                                                                                                                           
 > [superset-worker-beat superset-node  6/17] RUN apt-get update -qq     && apt-get install         -yqq --no-install-recommends         build-essential         python3         zstd:
300.1 W: GPG error: http://archive.debian.org/debian jessie-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010
300.1 E: The repository 'http://archive.debian.org/debian jessie-backports InRelease' is not signed

**Comment by rusackas** [comment]
You might need to install ztsd on your computer, from the look of it. @geido had seen something quite like this recently, but I'm not sure if it's the same thing.

**Comment by geido** [comment]
I think this should be solved by now, feel free to re-open the issue otherwise.
