### ISSUE TITLE
Test suite failed to run - Custom Plugins

### ISSUE THREAD

**Issue by sam-hieken** [apache/superset#30297]
### Bug description

Hi,

I get the following error after generating and trying to build a custom visualization plugin (without making any code changes). I'm following [the official tutorial from Preset](https://www.youtube.com/watch?v=LDHFY9xTzls). 

```
 FAIL  test/plugin/buildQuery.test.ts
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    
    ReferenceError: window is not defined

      17 |  * under the License.
      18 |  */
    > 19 | import { buildQueryContext, QueryFormData } from '@superset-ui/core';
         | ^
      20 |
      21 | /**
      22 |  * The buildQuery function is used to create an instance of QueryContext that's

      at Object.<anonymous> (node_modules/@superset-ui/core/lib/utils/logging.js:24:17)
      at Object.<anonymous> (node_modules/@superset-ui/core/lib/utils/index.js:45:39)
      at Object.<anonymous> (node_modules/@superset-ui/core/lib/index.js:13:14)
      at Object.require (src/plugin/buildQuery.ts:19:1)
      at Object.require (test/plugin/buildQuery.test.ts:19:1)
```

### How to reproduce the bug

Follow the exact steps taken in [Building Custom Viz Plugins in Superset](https://www.youtube.com/watch?v=LDHFY9xTzls) with the latest repository:

```
# Install yo
npm i -g yo
cd superset-frontend/packages/generator-superset
npm i
npm link

cd /tmp
mkdir my-plugin
cd my-plugin/
yo @superset-ui/superset
```

At this point, when running `npm ci && npm run build`,
you'll receive the error:

```
src/plugin/controlPanel.ts:22:3 - error TS6133: 'sections' is declared but its value is never read.

22   sections,
     ~~~~~~~~
```

This is where the expected output diverges from the tutorial; `npm ci && npm run build` should succeed with no errors or warnings, despite no code changes being made.

But anyway, for testing purposes, I don't care if `sections` isn't used; so I set `"noUnusedLocals": false` in `tsconfig.json`. 

Now when I rerun `npm ci && npm run build`:

```
 FAIL  test/plugin/buildQuery.test.ts
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    
    ReferenceError: window is not defined

      17 |  * under the License.
      18 |  */
    > 19 | import { buildQueryContext, QueryFormData } from '@superset-ui/core';
         | ^
      20 |
      21 | /**
      22 |  * The buildQuery function is used to create an instance of QueryContext that's

      at Object.<anonymous> (node_modules/@superset-ui/core/lib/utils/logging.js:24:17)
      at Object.<anonymous> (node_modules/@superset-ui/core/lib/utils/index.js:45:39)
      at Object.<anonymous> (node_modules/@superset-ui/core/lib/index.js:13:14)
      at Object.require (src/plugin/buildQuery.ts:19:1)
      at Object.require (test/plugin/buildQuery.test.ts:19:1)
```

### Screenshots/recordings

N/A

### Superset version

master / latest-dev

### Python version

3.10

### Node version

18 or greater

### Browser

Not applicable

### Additional context

I'm running Ubuntu 22.04, and my exact Node version is 20.13.1. It's also probably worth mentioning I used the Basic Chart type. Again, I followed the exact steps specified in Preset's official tutorial, which involved no code changes; I can't think of any reason this issue should occur.

Also, if anyone is having the same issue and looking for a workaround, the easiest I've found is to just edit `buildQuery.test.ts` (under the `tests` directory), remove the existing test case, and add in one that will always succeed (my apologies if there's an easier way to do this, I'm not familiar with jest):

```
describe('2a', () => {
  test('my test case', () => {
    expect(true).toBe(true); // Always expect true
  });
}); 
```

Thank you.

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
@sam-hieken it might be as simple as Dosu suggests... would you be willing to open a PR adding this shim inclusion to the yeoman generator? I'd do it myself, but I'm short on time right now.

**Comment by sam-hieken** [comment]
@rusackas Thanks for the reply, I would, but it looks like the only `shim.tsx` file is under `superset-frontend/spec/helpers/shim.tsx`. Doing a recursive search on my generated plugin's directory didn't show a `shim.tsx` file either. I'll tag dosu for more details, but that seems problematic since the generated plugin will be in a separate directory from the frontend.

**Comment by sam-hieken** [comment]
@dosu Where is `shim.tsx` located? I don't see it in the directory generated for my plugin

**Comment by hainenber** [comment]
hi OP, I think my [PR](https://github.com/apache/superset/pull/30069) here would help your case as well. @rusackas might need your peer's approval to unblock folks :D

**Comment by sam-hieken** [comment]
Thank you @hainenber !
