### ISSUE TITLE
Applied native filters do not carry over to the next dashboard

### ISSUE THREAD

**Issue by FaidJalal19** [apache/superset#30312]
### Bug description

I choose a set of native filters and use either `preselect_filters` or `native_filters` in the URL to have them automatically applied in the subsequent dashboard. However, they do not appear to take effect.

### How to reproduce the bug

1.     Choose several filters.
2.     Append these filters and their corresponding values to the preselect_filters dictionary at the end of the dashboard URL.

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by dogukandeniz12-source** [comment]
Is there now a solution or known workaround for Issue #30312?
Has there been any progress since the last update?
