### ISSUE TITLE
Label of permission "can csv on Superset " is not precise

### ISSUE THREAD

**Issue by xavier-GitHub76** [apache/superset#30317]
### Bug description

With permission "can csv on Superset ", a user can download a chart in CSV, Excel, Image format

### How to reproduce the bug

Add "can csv on Superset " on a role
Contextual menu on Chart is :
![image](https://github.com/user-attachments/assets/438de700-9d0a-4e83-9766-29d0c71739ad)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by xavier-GitHub76** [comment]
Label could be update but the permission seems to be deprecated... but used #30384

**Comment by rusackas** [comment]
Closing this in favor of the other issue you've linked to... it is indeed a deprecation that didn't take place, and is on the proposals board for 5.0 https://github.com/orgs/apache/projects/345
