### ISSUE TITLE
Interval annotations on charts broken in master

### ISSUE THREAD

**Issue by martyngigg** [apache/superset#30347]
### Bug description

Annotation layers of type "Interval" no longer seem to appear on line charts in master. They are fine in 4.02-dev and 4.1.0rc2-dev but not on master.

It does not matter if the source is a 'Superset annotation' or a 'Table'.

### How to reproduce the bug

This uses the examples datasets.

1. Spin up the latest development image: `TAG=994de1f-dev docker compose -f ./docker-compose-image-tag.yml up -d`
2. Go to 'Settings -> Annotation Layers'.
  - Click `+ Annotation layer` button
  - Give the layer a name
  - Click `Add`
4. Click on the name of the new annotation layer
  - Click `+ Annotation` button
  - Give the annotation a name
  - Set the start date to `2000-01-01 00:00:00` and end date to `2004-01-01 00:00:00`
  - Click `Add`
5. Click `Charts` in the navigation bar
  - Click `+ Chart`
  - Select the `birth_names` dataset
  - Select the `Line Chart` type
  - Click `Create new chart`
6. Configure the chart
  - Drag the `ds` column to `X-axis`
  - Drag the `num` column to `Metrics`, choose the Sum aggregate and click `Save`
  - Scroll down in the configure panel and click `Annotations and Layers` followed by `+ Add annotation layer`
  - Give the layer a name
  - Check the `Show label` box
  - Change the `Annotation layer type` to `Interval`
  - Change the `Annotation source` to `Superset annotation`
  - Change the `Annotation layer` to the name given to the newly created layer in step 2
  - Click OK
  - Click `Update chart`

I cannot see any errors in the superset logs. I've attached a screenshot of an error in the Firefox console. 

### Screenshots/recordings

![Superset-Missing-Annotations](https://github.com/user-attachments/assets/7576e507-8b5b-4351-aab3-b285b2663ac1)

### Superset version

master / latest-dev

### Python version

3.10

### Node version

18 or greater

### Browser

Firefox

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by kgabryje** [comment]
@martyngigg https://github.com/apache/superset/pull/30348 should have fixed the bug. Closing this issue, feel free to reopen if the bug persists

**Comment by martyngigg** [comment]
@kgabryje Yep looks good in my example now. Thanks!
