### ISSUE TITLE
Native Date Range Filter Not Applying to Subsequent Dashboard

### ISSUE THREAD

**Issue by FaidJalal19** [apache/superset#30341]
### Bug description

1. I apply several filters in my main dashboard.
2. These filters, along with the Date Range filter, are passed to the next dashboard.
3. All filters are automatically applied except the Date Range filter.
4. For the Date Range filter, I need to manually click "Apply Filter" for it to take effect.
5. Otherwise, the dashboard displays all data without filtering by date.

### How to reproduce the bug

1. Goto superset, apply some filters.
2. Using native_filters parameter, pass these filters to subsequent dashboard.

### Superset version

4.0.2

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by EnxDev** [comment]
Hi @FaidJalal19 the issue seems resolved on master.
 If you are still experiencing the problem please feel free to open another issue, thanks.
