### ISSUE TITLE
Cannot add alert items normally

### ISSUE THREAD

**Issue by poweronlevel** [apache/superset#30356]
### Bug description

When I add a new alert, all the required fields are filled in, but the `Add' button stays greyed out and inactive. 

The prompt says:
`Not all required fields are complete. please provide the following: 
notification method: recipients`

Please see the screenshot below

<img width="346" alt="image" src="https://github.com/user-attachments/assets/f3de3f5e-9fe5-4f84-9473-3937535765c0">

### How to reproduce the bug

Click on `settings`-> `Alerts & Reports`. 
Then click on the `+Alerts` button in the top right corner and all the required fields are filled in. 
But the notification method field does not turn into a green tick.
The reason is that superset thinks that my `Email recipients` don't have an email address. 
In fact, I did fill in the email address.

version 4.0.1
<img width="164" alt="image" src="https://github.com/user-attachments/assets/eb95340a-eb2b-41d5-872b-b008c62ee4e7">

### Superset version

4.0.2

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by sfirke** [comment]
This is a known bug (see #28149) and was patched in 4.0.2, please upgrade to fix it.  I appreciate you noting that you are on 4.0.1 but also this is why the bug report template insists that users only report bugs on the latest releases.
