### ISSUE TITLE
X-Axis title disappears when editing bar chart

### ISSUE THREAD

**Issue by BGZ-spec** [apache/superset#30370]
### Bug description

**Description**

When editing a bar chart in Superset, changing the X-axis title causes the title to disappear. Similarly, adjusting the margins leads to unexpected behavior—they either reset or are not applied correctly.

### How to reproduce the bug

    Open an existing bar chart in Superset or create a new one.
    Enter the edit mode for the chart.
    Change the X-axis title to a new value.
    Observe that the X-axis title disappears from the chart.
    Adjust the margin settings.
    Notice that the margins do not update as expected or revert to previous settings.

### Screenshots/recordings

[Screencast from 2024-09-24 10-57-58.webm](https://github.com/user-attachments/assets/67f392ae-9b4f-4eaa-a6d0-408fdadc2980)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Firefox

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by BGZ-spec** [comment]
@dosu
I have the original version of the code and haven't changed anything. I downloaded a clean, fresh version of Superset.

```
controlSetRows: [
        [<ControlSubSectionHeader>{t('X Axis')}</ControlSubSectionHeader>],
        ...createAxisTitleControl('x'),
        [<ControlSubSectionHeader>{t('Y Axis')}</ControlSubSectionHeader>],
        ...createAxisTitleControl('y'),
      ],
```

When I comment out `...createAxisTitleControl('y'),` changing the X-axis title works correctly.

**Comment by viktorfilyk4** [comment]
Hi!
I pulled repo today, setup project using docker-compose and I encounter the same issue. I would like to work on this.
As I read comments above it seems like only frontend issue

**Comment by rusackas** [comment]
@viktorfilyk4 that would very much be appreciated. Ping us here if/when you open a PR. Thanks in advance!

**Comment by BGZ-spec** [comment]
Has anyone managed to fix the problem?

**Comment by viktorfilyk4** [comment]
@BGZ-spec I am currently working on this. Trying to figure out what's the problem. The same for me, when I comment `...createAxisTitleControl('y')` line, it works fine.

Any suggestions?

**Comment by viktorfilyk4** [comment]
@dosu 
Can you suggest how to fix this problem?

**Comment by sfirke** [comment]
I'm experiencing this when creating a bar chart with a categorical x-axis in 4.0.2.

**Comment by DamianPendrak** [comment]
Hi, I noticed the issue has been unassigned and without updates for a while, I went ahead and created a pull request #30821  to address it. I hope this helps! Let me know if there's anything you'd like me to adjust.
@rusackas @sfirke

**Comment by curio77** [comment]
Happens here too with a fresh setup of v4.0.2.
