### ISSUE TITLE
can_csv_on_Superset Deprecated since 3.0.0 but always present in 4.0.2

### ISSUE THREAD

**Issue by xavier-GitHub76** [apache/superset#30384]
### Bug description

Hello,

a deprecated alert is present in the file superset/security/manager.py for the permission "can csv on Superset"
![image](https://github.com/user-attachments/assets/2d81bab8-a4e0-46b9-b15d-946c688b5774)

but the permission is always used in 4.0.2

Without the permission, a user can't download a chart (in CSV, Excel or Image) 

### How to reproduce the bug

Go to Settings > List Roles
Create a Role
Add "can csv on Superset" permission

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
This is already on the proposals board for 5.0, I hope we'll get it taken care of this time :)
https://github.com/orgs/apache/projects/345

I'll link to this issue there, and close this ticket for now, since it's not so much a bug, but a to-do item that we'll continue to track.
