### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Iamtheoldman** [apache/superset#30404]
### Bug description

 > [superset superset-node  2/13] RUN apt-get update -qq     && apt-get install         -yqq --no-install-recommends         build-essential         python3         zstd:                                                                                                      
0.981 W: GPG error: http://deb.debian.org/debian bullseye InRelease: At least one invalid signature was encountered.                                                                                                                                                            
0.981 E: The repository 'http://deb.debian.org/debian bullseye InRelease' is not signed.                                                                                                                                                                                        
0.981 W: GPG error: http://deb.debian.org/debian-security bullseye-security InRelease: At least one invalid signature was encountered.                                                                                                                                          
0.981 E: The repository 'http://deb.debian.org/debian-security bullseye-security InRelease' is not signed.                                                                                                                                                                      
0.981 W: GPG error: http://deb.debian.org/debian bullseye-updates InRelease: At least one invalid signature was encountered.
0.981 E: The repository 'http://deb.debian.org/debian bullseye-updates InRelease' is not signed.

### How to reproduce the bug

Steps to Reproduce
Install Docker if it's not already installed. You can download and install Docker Desktop from here.

Create a New Directory for your project:

bash
Copy code
mkdir docker-apt-bug
cd docker-apt-bug
Create a Dockerfile: Create a file named Dockerfile in this directory:

bash
Copy code
touch Dockerfile
Edit the Dockerfile: Open the Dockerfile in your favorite text editor and add the following content. This is the same as what caused the GPG key errors you described:

Dockerfile
Copy code
FROM debian:bookworm

RUN apt-get update -qq && apt-get install -yqq --no-install-recommends \
    libnss3 libdbus-glib-1-2 libgtk-3-0 libx11-xcb1 libasound2 libxtst6 git pkg-config && \
    rm -rf /var/lib/apt/lists/*
Build the Docker Image: Open your terminal in the directory where the Dockerfile is saved, and run:

bash
Copy code
docker build -t test-apt-bug .
Encounter the Bug: During the build process, you should encounter the error related to the GPG signature, similar to what you saw earlier:

bash
Copy code
W: GPG error: http://deb.debian.org/debian bookworm InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bookworm InRelease' is not signed.

### Screenshots/recordings

![Screenshot 2024-09-26 at 9 56 39 AM](https://github.com/user-attachments/assets/d116a6e6-7ee5-45b3-9ef6-5d703d963dc0)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Closing this, as I agree it's not a Superset issue, and this is working for most folks. You might be able to get help from AI or from others on [slack](http://bit.ly/join-superset-slack) - or I can reopen this and move it to a GitHub Discussion if you'd prefer to keep seeking help on Github.
