### ISSUE TITLE
[SIP] Configuration can use the common yaml format, using py code is not everyone can move py, configuration can be modular, one part of what is what the other part is what

### ISSUE THREAD

**Issue by zhaomingcheng01** [apache/superset#30427]
Configuration can use the common yaml format, using py code is not everyone can move py, configuration can be modular, one part of what is what the other part is what

This configuration is not readable at all

**Comment by rusackas** [comment]
This doesn't seem to be using the SIP concept/template at all, so I'm going to close it for that reason alone. You're welcome to fill out the template for real if you want to make a fleshed out proposal and carry it through the consensus process.

I'd say in general, though, that it's unlikely to get consensus to make such a change. Superset is a python application, and using a python file for config means that you can use python code/logic and data structures, which we currently do in several places. 

Much (but not all) of the config could be moved to other formats (JSON/YAML/etc) but I'm not sure the use case. The tradeoffs/alternatives/use cases should all be part of the proposal if you want to open one.
