### ISSUE TITLE
Dashboard versioning

### ISSUE THREAD

**Issue by crazychaz** [apache/superset#30436]
Hello! Tell me, are there any immediate plans to implement versioning of dashboards on the superset side?

**Comment by rusackas** [comment]
Nope. Some folks are talking about opening a SIP with a proposal to version dashboards (which probably requires versioning charts, and thus datasets and queries, and thus database connections). It gets very complicated very quickly, but you or anyone are able to open a proposal as well if you'd like to implement this feature. I think most of us hope we can get to this state eventually.

**Comment by crazychaz** [comment]
Thanks for the feedback! Let's hope that this functionality will appear in the near future. :)
