### ISSUE TITLE
Disable the download as image feature.

### ISSUE THREAD

**Issue by praveer38** [apache/superset#30513]
### Bug description

How can i disable the download as image feature for charts and dashboards?

### Superset version

4.0.2

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by praveer38** [comment]
@dosu please tell me a way to disable it if I'm running superset as a docker container?

**Comment by praveer38** [comment]
FROM apache/superset:4.0.2

USER root

RUN apt-get update
RUN apt-get install -y build-essential g++ nano
RUN mkdir /app/custom_scripts_rc
COPY public_user_perms.py /app/custom_scripts_rc/public_user_perms.py
RUN pip install mysqlclient Authlib pymssql apache-superset[cors] Flask-OAuthlib psycopg2  pystan==2.19.1.1 prophet

COPY ./docker-init.sh /superset-init.sh
COPY docker-bootstrap.sh /app/docker/docker-bootstrap.sh

COPY zdnlk0yk.png /app/superset/static/assets/images/superset.png
COPY zdnlk0yk.png /app/superset/static/assets/images/superset-logo-horiz.png

COPY superset_config.py /app/pythonpath/superset_config.py
COPY superset_config.py /app/

COPY utils.py /app/superset/connectors/sqla/utils.py
COPY models.py /app/superset/connectors/sqla/models.py

ENV SUPERSET_CONFIG_PATH /app/superset_config.py
ENV PYTHONPATH="/app/pythonpath"
ENV BUILD_SUPERSET_FRONTEND_IN_DOCKER=True



USER superset

CMD ["sh", "-c", "python /app/custom_scripts_rc/public_user_perms.py & /superset-init.sh"]
These are the contents of my dockerfile. Please help with the changes. @dosu

**Comment by praveer38** [comment]
@dosu but the container only has package.json under superset-frontend

**Comment by sfirke** [comment]
Sorry Dosu always wants people to edit the codebase.  There is a permission named "can csv on Superset", try removing that from the role(s) that you want to modify in this way.

**Comment by sfirke** [comment]
Also this should not be a bug report as it is a question.  Please post questions on Slack and/or GitHub Discussions.  I found the answer searching Slack.  I see you have opened a few bug reports today - please be judicious as the Superset project struggles when it comes to triaging bug reports.  Valid, complete bug reports are welcome but it is a help if you keep them to a minimum.

**Comment by praveer38** [comment]
I understand. Thanks for the pointer, although we do want to export the data as csv as well as excel but we want to eliminate the option to export it as an image. But I'll post this as a discussion on GitHub. Thanks!
