### ISSUE TITLE
 npm error Invalid: lock file's dayjs@1.11.12 does not satisfy dayjs@1.11.13

### ISSUE THREAD

**Issue by kalyan540** [apache/superset#30524]
### Bug description

when tried to build the Apache superset Non development version , caught this error " npm error Invalid: lock file's dayjs@1.11.12 does not satisfy dayjs@1.11.13"

### Screenshots/recordings

![image](https://github.com/user-attachments/assets/a36ec170-c790-4b83-b6af-6a007f747f8a)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by hainenber** [comment]
This is fixed in https://github.com/apache/superset/pull/30493. Please help pulling from latest master branch :D

**Comment by kalyan540** [comment]
Thanks @hainenber

**Comment by kalyan540** [comment]
Thanks @hainenber @dosu
