### ISSUE TITLE
Unable to parse escaped tables

### ISSUE THREAD

**Issue by michael-s-molina** [apache/superset#30551]
### Bug description

The following query throws `This database does not allow for DDL/DML, and the query could not be parsed to confirm it is a read-only query. Please contact your administrator for more assistance.`

```
select *
from `birth_names`
```

The ability to escape table names is essential given that we might have names that conflict with reserved keywords.

This bug was introduced in https://github.com/apache/superset/pull/30417.

### Screenshots/recordings

<img width="1913" alt="Screenshot 2024-10-08 at 11 29 55" src="https://github.com/user-attachments/assets/7a4dc925-bcdb-48a2-a3fa-dd38e6a9ea43">

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by betodealmeida** [comment]
@michael-s-molina backticks are not valid Postgres quoting identifiers, you should use double quotes instead: https://www.postgresql.org/docs/17/sql-syntax-lexical.html

```sql
superset=# SELECT * FROM `birth_names`;
ERROR:  syntax error at or near "`"
LINE 1: SELECT * FROM `birth_names`;
```

**Comment by michael-s-molina** [comment]
@betodealmeida backticks are valid quoting identifiers for other databases such as Trino. I just used the Postgres database as an example. We have many queries that use them.

**Comment by betodealmeida** [comment]
@michael-s-molina the parsing is now engine dependent, so if the database uses backticks for quoting then it should work. For MySQL, eg:

![Screenshot 2024-10-08 at 12-25-09 Preset](https://github.com/user-attachments/assets/3b5e9e35-8853-4f53-8215-45c9352716f2)

**Comment by betodealmeida** [comment]
If you have a database where this fails but the SQL is actually valid let me know.

**Comment by sadpandajoe** [comment]
It could also be using a default dialect if there isn't one in sqlglot, right @betodealmeida? If that's the case we'll probably need to just add a dialect file with sqlglot?

**Comment by betodealmeida** [comment]
@sadpandajoe right, if this is happening on a database that doesn't have a [sqlglot dialect](https://sqlglot.com/sqlglot/dialects.html#dialects) it would fallback to the generic dialect, which probably uses double quotes since that's the ANSI SQL standard.

**Comment by michael-s-molina** [comment]
@betodealmeida @sadpandajoe I was able to confirm that the root cause for the error is because we have custom database engine spec which does not map to any SQLGlot dialect in [SQLGLOT_DIALECTS](https://github.com/apache/superset/blob/master/superset/sql_parse.py) and end up using the default dialect which does not support backticks. We'll need a way to extend the [SQLGLOT_DIALECTS](https://github.com/apache/superset/blob/master/superset/sql_parse.py) from the configs to support this use case. I'll work on a fix for this.
