### ISSUE TITLE
Incorrect Vietnam province name in Country map

### ISSUE THREAD

**Issue by tienhung2812** [apache/superset#30607]
## Screenshot

![Screenshot 2024-10-15 at 16 51 23](https://github.com/user-attachments/assets/da367f3e-b94a-40dd-af2e-440831658a30)

## Description
On Vietnam country map chart, there are a list of incorrect mapping ISO-code with the name 

|  ISO 3166-2   | Current name        | Correct Name |
|-------|---------------------|--------------|
| VN-39 | Đông Nam Bộ         | Đồng Nai     |
| VN-53 | Đông Bắc            | Bắc Kạn      |
| VN-66 | Đồng Bằng Sông Hồng | Hưng Yên     |

Source: https://en.wikipedia.org/wiki/ISO_3166-2:VN

**Comment by rusackas** [comment]
I believe this is all resolved, and the issue should be closed now :) Thanks again for the contribution!
