### ISSUE TITLE
Bug Report: Missing Bracket in config.py for OpenID Providers

### ISSUE THREAD

**Issue by Cappybara12** [apache/superset#30673]
### Bug description

To create a professional message for reporting this issue to the Superset team, you can structure it under clear headings and describe the problem precisely. Here's a suggestion:

---

**Subject: Bug Report: Missing Bracket in `config.py` for OpenID Providers**
Issue Description:

I encountered an issue when trying to implement OpenID providers by uncommenting the related lines in the `config.py` file. The functionality does not work due to a missing closing bracket `]` on line 334. This syntax error is preventing proper configuration.
Steps to Reproduce:

1. Navigate to the `config.py` file.
2. Uncomment the lines related to OpenID providers.
3. Attempt to run or test the setup.
4. Observe that the configuration fails due to a syntax error.

Proposed Solution:

Add the missing `]` at line 334 in the `config.py` file to resolve the issue.

Suggested Fix:

```
python
# Line 334, missing closing bracket
# Correct version:
OPENID_PROVIDERS = [
   { 'name': 'Yahoo', 'url': 'https://open.login.yahoo.com/' },
   { 'name': 'Flickr', 'url': 'https://www.flickr.com/<username>' },

]

```

### Screenshots/recordings

![image](https://github.com/user-attachments/assets/837e727b-27c6-49b1-84a4-9071164afe8e)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by samarsrivastav** [comment]
hey @sfirke !! I have created the pr for this issue

**Comment by Cappybara12** [comment]
> hey @sfirke !! I have created the pr for this issue, please review
great , i lost this chat because of my office work . I hope it gets reviewed soon

**Comment by sfirke** [comment]
> hey @sfirke !! I have created the pr for this issue, please review

On it, thank you!
