### ISSUE TITLE
Broken use cases appliying native & cross filters on common columns

### ISSUE THREAD

**Issue by fbgeobit** [apache/superset#30687]
### Bug description

As commented on issue https://github.com/apache/superset/pull/30438 by @Mainer-g00t, proposed fix broken our usual use case. We are providing service to customers with setup described below.
To deal with high cardinality tables on our database, is not an option for us showing all dimensions we need, so:
1. we split data on as many datasets as dimensions we need to show.
2. we create datasets with a custom jinja snippet, same on all datasets we want to filter.
3. we configure cross-filters to work on desired charts.

Result: by implementing that, we are able to filter several charts minimizing high dimensionality derived issues, increasing queries speed. 

We provide tow gifts showing that configuration working on:
- Superset v 4.0.2: works well
- Superset v4.0.1rc3: broken our approach

Please, consider our use case.

### Screenshots/recordings
- Supserset v4.0.2
![sample_sales_dashboard_crossfiltering_distinct_columns_v402](https://github.com/user-attachments/assets/f853837d-affc-4dd0-9b16-67fa63617e18)

- Supserset v4.1.0rc3
![sample_sales_dashboard_crossfiltering_distinct_columns_v410rc3](https://github.com/user-attachments/assets/f4e0be70-c5d3-4a65-b779-7376fd14dea3)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Not applicable

### Configuration file: `superset/docker/pythonpath_dev/superset_config.py`

```
# CUSTOM FEATURE FLAGS
FEATURE_FLAGS = {"ALERT_REPORTS": True,
"ENABLE_TEMPLATE_PROCESSING": True,
"ENABLE_TEMPLATE_REMOVE_FILTERS": True,
"DASHBOARD_NATIVE_FILTERS": True,
"DASHBOARD_CROSS_FILTERS": True,
"EMBEDDED_SUPERSET": True,
"DASHBOARD_RBAC": True,
"DRILL_TO_DETAIL": True,
"HORIZONTAL_FILTER_BAR": True,
"ALERTS_ATTACH_REPORTS": True,
"VERSIONED_EXPORT": True}

# CUSTOM FEATURES
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = False
GUEST_ROLE_NAME = "Admin"
WTF_CSRF_ENABLED = False
ENABLE_PROXY_FIX = False
TALISMAN_ENABLED = False
GUEST_TOKEN_JWT_EXP_SECONDS = 28880

```

#### sample_sales_a_product_name
```
--{# Comment it out #}

  {% set from_dttm = '2022-01-01T00:00:00' %}
  {% set to_dttm   = '2022-01-04T04:00:00' %}

{%
  set filters = {
      'product_name'          : filter_values('product_namedistribution_country'),
      'distribution_country'  : filter_values('distribution_country')
    } 
%}



SELECT
  product_name,
  SUM(sales_amount) AS sales_amount
FROM 
  asd.sample_sales_data
WHERE
  -- from datetime
  {% if from_dttm is not none %}
      sale_date >= '{{ from_dttm }}'::DATE
  {% else %}
      AND sale_date >= (DATE_TRUNC('DAY', CURRENT_DATE ) - INTERVAL '2 DAYS')
  {% endif %}
    
    -- to datetime
  {% if to_dttm is not none %}
      AND sale_date < '{{ to_dttm }}'::DATE
  {% else %}
      AND sale_date < (DATE_TRUNC('DAY', CURRENT_DATE))
  {% endif %}
  
  {% for key, values in filters.items() if values %}
   AND {{ key }} IN ('{{ values | join("','") }}')
  {% endfor %}
GROUP BY 1
```

#### sample_sales_d_disitribution_country
```
--{# Comment it out #}

  {% set from_dttm = '2022-01-01T00:00:00' %}
  {% set to_dttm   = '2022-01-04T04:00:00' %}

{%
  set filters = {
      'product_name'          : filter_values('product_namedistribution_country'),
      'distribution_country'  : filter_values('distribution_country')
    } 
%}



SELECT
  distribution_country,
  SUM(sales_amount) AS sales_amount
FROM 
  asd.sample_sales_data
WHERE
  -- from datetime
  {% if from_dttm is not none %}
      sale_date >= '{{ from_dttm }}'::DATE
  {% else %}
      AND sale_date >= (DATE_TRUNC('DAY', CURRENT_DATE ) - INTERVAL '2 DAYS')
  {% endif %}
    
    -- to datetime
  {% if to_dttm is not none %}
      AND sale_date < '{{ to_dttm }}'::DATE
  {% else %}
      AND sale_date < (DATE_TRUNC('DAY', CURRENT_DATE))
  {% endif %}
  
  {% for key, values in filters.items() if values %}
   AND {{ key }} IN ('{{ values | join("','") }}')
  {% endfor %}
GROUP BY 1
```

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by geido** [comment]
@fbgeobit from a quick test it appears you could just change the select statement to include the filterable columns? In that way the possible dynamic filters will show up as column names for the dataset, effectively enabling cross-filtering between the two datasets.

**Comment by fbgeobit** [comment]
Hi:
We see you worked hard relating to this issue.
Do you need we test your changes in our platform?

**Comment by fbgeobit** [comment]
We tested last changes on our platform and now it's working as expected:
- ![imagen](https://github.com/user-attachments/assets/2f127097-debe-4899-8929-fa9a6b4f2d9e)

- ![sample_sales_dashboard_crossfiltering_distinct_columns_pr-30719](https://github.com/user-attachments/assets/2dedb58f-e070-4168-a396-3bd7f29be977)

Thanks for you dedication!
