### ISSUE TITLE
Annotation layer of type Event not showing

### ISSUE THREAD

**Issue by michael-s-molina** [apache/superset#30690]
### Bug description

In 4.1.0 RC3, an annotation layer of type Event is not appearing on a Line chart. I was not able to replicate the same issue on `master` so I believe we are missing a cherry in 4.1.0 RC3. @sadpandajoe

1 - Create an annotation layer of type event with start on Oct 15, 2004 and end on Oct 16, 2004
2 - Create a Line chart with the `clean_sales_data dataset` 
3 - Add `order_date` to the `x-axis` control with a monthly granularity
4 - Add count(*) to the metrics control
5 - Add an annotation layer of type Event using the previously create annotation
6 - Check that the event is not shown in the chart

### Screenshots/recordings
<img width="1056" alt="Screenshot 2024-10-23 at 11 02 09" src="https://github.com/user-attachments/assets/5bba67e7-65cb-4858-a164-40f2eb3019f9">
<img width="1911" alt="Screenshot 2024-10-23 at 10 59 06" src="https://github.com/user-attachments/assets/24942418-ac46-4398-a741-2ad32628e29d">

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by sadpandajoe** [comment]
I think there was an issue in master that might have been labelled wrong so i cherried it into 4.1.0rc3. Here should be the fix: https://github.com/apache/superset/pull/30348
