### ISSUE TITLE
Dataset Default URL Field Not Working

### ISSUE THREAD

**Issue by yousoph** [apache/superset#30720]
### Bug description

1. Create a dataset 
2. Edit the dataset
3. Go to the Settings tab 
4. Fill in a value for the Default URL field and save changes
5. In the Dataset list, click the Dataset title 

Expected: 
User gets redirected to the Default URL 

NOTE: There is a config PREVENT_UNSAFE_DEFAULT_URLS_ON_DATASET: https://github.com/apache/superset/pull/22038
If the config is set to true, then the user should get an error message if the URL isn't a relative URL 

Current behavior: 
The URL in the browser changes but doesn't redirect. Refreshing the page shows a 404

### Screenshots/recordings

![image](https://github.com/user-attachments/assets/a171f37e-edf2-4438-8482-8b0fd5e2f925)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by Myestery** [comment]
I'll like to work on this if its not assigned yet

**Comment by geido** [comment]
> I'll like to work on this if its not assigned yet

Thanks @Myestery we are still defining the last details for this before attaching a bounty. Keep an eye on this for updates.

**Comment by yousoph** [comment]
Closing - this works when using a relative URL
