### ISSUE TITLE
CSV, Columnar, and Excel Upload Form cosmetic updates

### ISSUE THREAD

**Issue by yousoph** [apache/superset#30737]
## Screenshot

![Screenshot 2024-10-16 at 4 04 20 PM](https://github.com/user-attachments/assets/b96ff151-9f5b-42d0-bece-a794423b6eba)
![Screenshot 2024-10-16 at 4 07 02 PM](https://github.com/user-attachments/assets/92b196bb-e2f5-4d25-a6f6-9f7e4b4a8f44)

## Description

The following updates need to be made in the CSV, columnar, and Excel upload forms: 
* Move the "Preview uploaded file" toggle to be left aligned with the rest of the form fields, under the file upload option and above the Columns field 
* In the first item of "General information" field, it should read "CSV file" and "Columnar file" (file is not capitalized, CSV is, Columnar is) 
* All headers and form fields should be sentence case and not title case. For example, it should be: 
   * CSV upload rather than CSV Upload
   * Columnar upload rather than Columnar Upload
   * Table name rather than Table Name
   * File settings
   * If table already exists
   * Columns to be parsed as dates
   * Decimal character
   * Columns to read
   * Column data types
   * Header row
   * Rows to read
   * Skip rows
   * Data imported rather than Data Imported in the success toast 

To access these forms, connect a database and in the database settings, enable the "Allow file uploads to database" option in the Advanced > Security section. Then you should see an "Upload file to database" option at the top right of the Databases page.

**Comment by geido** [comment]
---

### 🎉 **Preset Bounty Available: $100 USD** 🎉

To claim this bounty, please carefully follow the steps below.

---

#### 📋 **Steps to Participate**

1. **Review Guidelines:**  
   Read through the [Preset Bounty Program Contribution Guide](https://preset.notion.site/preset-bounty-program-apache-superset) for complete details on bounty requirements.

2. **Show Your Interest:**  
   Complete the [Preset Bounty Program Survey](https://docs.google.com/forms/d/e/1FAIpQLSeDsR1iWvPxFydUIXs2agsUg3kMDaAooeD4P9P1L5sI0Yu5QQ/viewform?usp=sharing) and comment this issue to express your interest.

3. **Join the Slack Channel:**  
   After completing the survey, you’ll receive an invitation to the dedicated [Apache Superset Slack](https://join.slack.com/t/apache-superset/shared_invite/zt-2be0drwz8-bxPfkdz28ozzk1Iox29ufg) channel.

4. **Get Assigned:**  
   To officially start, ensure a **Bounty Program Manager** has assigned you to this issue.

5. **Submit Your Solution:**  
   When ready, submit your solution with the `Fixes #{issue_number}` notation in your Pull Request description.

6. **Claim Your Bounty:**  
   Sign up at [GitPay.me](https://gitpay.me/) and submit your solution via: [https://gitpay.me/#/task/969](https://gitpay.me/#/task/969)

---

#### 💡 **Additional Notes**

- Only developers assigned by a **Bounty Program Manager** should start working on this issue to win the bounty.
- Be sure to follow the guide closely to avoid any delays in payment. Please, allow a few days after your PR has been merged for the bounty to be released.

Good luck, and happy coding! 🎉

**Comment by vine-trellis** [comment]
Hi I'd like to work on this.
I just completed the interest survey.
