### ISSUE TITLE
Dashboard Screenshot API Endpooint Gives and Error Message when a Dashboard is Empty or has no Charts 

### ISSUE THREAD

**Issue by yousoph** [apache/superset#30736]
### Bug description

When a dashboard is empty OR has only text elements, when the user tries to send an API call to generate a screenshot, they get an error message instead of a screenshot 

### Repro steps: 
1. Create a dashboard with just a title and save it OR create a dashboard with some text elements only and save it 
2. Find the dashboard ID of the dashboard 
3. Use the API to try to generate a screenshot for the dashboard 

Use POST endpoint `/api/v1/dashboard/{{DashboardID}}/cache_dashboard_screenshot/` 
By default, an empty array can be used as the request body to get the dashboard screenshot. Alternatively, it's possible to include below fields in the body:

-     dataMask (array): Specifies the dataMask configuration (controls applied filters).
-     activeTabs (list): Specify the tab(s) that should be included/selected.
-     urlParams (list): List of URL params to be applied to the dashboard.

The request returns an image_url value, that can be used to download the dashboard. It's also possible to append ?download_format=pdf to download a PDF as opposed to an image.

### Expected results
A blank or text-only dashboard image/PDF will be generated.

### Actual results
{"message":"Not found"} error was shown.

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by geido** [comment]
---

### 🎉 **Preset Bounty Available: $150 USD** 🎉

To claim this bounty, please carefully follow the steps below.

---

#### 📋 **Steps to Participate**

1. **Review Guidelines:**  
   Read through the [Preset Bounty Program Contribution Guide](https://preset.notion.site/preset-bounty-program-apache-superset) for complete details on bounty requirements.

2. **Show Your Interest:**  
   Complete the [Preset Bounty Program Survey](https://docs.google.com/forms/d/e/1FAIpQLSeDsR1iWvPxFydUIXs2agsUg3kMDaAooeD4P9P1L5sI0Yu5QQ/viewform?usp=sharing) and comment this issue to express your interest.

3. **Join the Slack Channel:**  
   After completing the survey, you’ll receive an invitation to the dedicated [Apache Superset Slack](https://join.slack.com/t/apache-superset/shared_invite/zt-2be0drwz8-bxPfkdz28ozzk1Iox29ufg) channel.

4. **Get Assigned:**  
   To officially start, ensure a **Bounty Program Manager** has assigned you to this issue.

5. **Submit Your Solution:**  
   When ready, submit your solution with the `Fixes #{issue_number}` notation in your Pull Request description.

6. **Claim Your Bounty:**  
   Sign up at [GitPay.me](https://gitpay.me/) and submit your solution via: [https://gitpay.me/#/task/968](https://gitpay.me/#/task/968)

---

#### 💡 **Additional Notes**

- Only developers assigned by a **Bounty Program Manager** should start working on this issue to win the bounty.
- Be sure to follow the guide closely to avoid any delays in payment. Please, allow a few days after your PR has been merged for the bounty to be released.

Good luck, and happy coding! 🎉

**Comment by msyavuz** [comment]
Hey @geido, can i work on this?
