### ISSUE TITLE
Images Not Displaying Due to Content Security Policy (CSP) Restrictions

### ISSUE THREAD

**Issue by ruslan-murzag** [apache/superset#30761]
### Bug description

Images hosted on external URLs are not displaying in Apache Superset due to Content Security Policy (CSP) restrictions. Despite configuring TALISMAN_CONFIG to allow all sources, the browser console still reports CSP violations, specifically blocking image loading from external URLs.

**Steps to Reproduce:**

1. Configure TALISMAN_CONFIG in superset_config.py with settings to allow all sources:
```
TALISMAN_CONFIG = {
    "content_security_policy": {
        "default-src": ['*'],
        "img-src": ['*'],
        "worker-src": ['*'],
        "connect-src": ['*'],
        "object-src": ['*'],
        "style-src": ['*'],
        "script-src": ['*'],
    },
    "force_https": False,
    "session_cookie_secure": False,
}
```
2. Attempt to display an image from an external URL in Superset.

The image should display as configured, following the img-src: '*' directive.

**Actual Behavior:**

The image does not load, and the browser console shows a CSP error similar to the following:

```
Refused to load the image 'http://101.30.83.81:9000/images-superset/photo_2024-10-29_13-57-16.jpg' because it violates the following Content Security Policy directive: "img-src 'self' blob: data: https://apachesuperset.gateway.scarf.sh https://static.scarf.sh/".
```
**Impact:**

This CSP restriction prevents images hosted on external URLs from being displayed in Superset, limiting the ability to include necessary external visual content.

**Request:**

An option to fully relax or disable CSP checks specifically for images would provide flexibility, ensuring that Superset can display images hosted on external URLs as intended.

**Additional Context:**

This issue specifically affects the display of externally hosted images within Superset, which are essential for various dashboards and visualizations.

### Screenshots/recordings

![image](https://github.com/user-attachments/assets/0481cd5f-6e12-4658-b414-5d5834204cd9)

### Superset version

4.0.2

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by ruslan-murzag** [comment]
@mistercrunch I considered that and ran the `flask CLI` in the worker container to retrieve the `TALISMAN_CONFIG` variable. Here’s the code I used:

```python
from flask import current_app
print(current_app.config.get("TALISMAN_CONFIG"))
```
This returned the same configuration I had defined in the config file. Is this an appropriate way to verify the TALISMAN_CONFIG, or would you recommend a different method?

**Comment by mistercrunch** [comment]
Seems like a fair way to validate the configuration. In that context, do you still get the `scarf.sh`-related log/error messages? Where could that be coming from if you `TALISMAN_CONFIG` is not referencing it? A zombie/competing process? 

There's a lot of different ways to confirm or double check that the endpoint you are hitting is aligned with the configuration / process you think you are running. Do you still get an error/warning after killing all processes (trying to ensure it's not a zombie or other process) or just no answer as expected? Could you add or alter an exsiting endpoint to serve the `app.config.get("TALISMAN_CONFIG")`?

**Comment by rusackas** [comment]
Does it work without brackets, e.g. `'img-src': '*',`?

**Comment by ruslan-murzag** [comment]
Hello @mistercrunch @rusackas, I found a solution, though it seems unusual. To display images, I need to modify two configurations:
- TALISMAN_CONFIG
- TALISMAN_DEV_CONFIG

However, I’m running docker-compose-image-tag.yml, which indicates a production setup, not a development one.

**Comment by mistercrunch** [comment]
All of our `docker compose` setups, including docker-compose-image-tag.yml, are NOT recommended for production use. 

From https://superset.apache.org/docs/installation/docker-compose/
<img width="1019" alt="Screenshot 2024-11-08 at 1 11 01 PM" src="https://github.com/user-attachments/assets/1bc13819-4cbf-47f9-a5ef-5f24204a66b0">

On top of what is described there, there was a challenge around segmentation while supporting dev AND prod use cases within docker-compose semantics, where there was a lot of conditionality in docker-compose (if dev then do_this else do_something_else) which could lead to confusion and security issues. Because of that we decided to recommend helm/k8s/minikube for prod use cases, where we can make sure all the conditions and configurations point to prod/secure images and configurations.

**Comment by ruslan-murzag** [comment]
@mistercrunch ok i got it.

**Comment by Ananda2k22** [comment]
After updating the content security policy still getting the error
"img-src": ["'self'", "data:", "blob:"] used this


![image](https://github.com/user-attachments/assets/f9f1fbe9-9131-4e10-b99f-73e821db8f4b)

**Comment by varun-verma-code** [comment]
https://github.com/apache/superset/issues/30761#issuecomment-2464357595
@ruslan-murzag I have added the config to both places, however, I still see the same issue. Here's my config:
`TALISMAN_CONFIG = {
    "content_security_policy": {
        "default-src": ["'self'"],
        "img-src": ["'self'", "data:","blob:"],
        "worker-src": ["'self'", "blob:"],
        "connect-src": [
            "'self'",
            "https://api.mapbox.com",
            "https://events.mapbox.com",
        ],
        "object-src": "'none'",
        "style-src": ["'self'", "'unsafe-inline'"],
        "script-src": ["'self'", "'strict-dynamic'"],
    },
    "content_security_policy_nonce_in": ["script-src"],
    "force_https": False,
}
# React requires `eval` to work correctly in dev mode
TALISMAN_DEV_CONFIG = {
    "content_security_policy": {
        "default-src": ["'self'"],
        "img-src": ["'self'", "data:","blob:"],
        "worker-src": ["'self'", "blob:"],
        "connect-src": [
            "'self'",
            "https://api.mapbox.com",
            "https://events.mapbox.com",
        ],
        "object-src": "'none'",
        "style-src": ["'self'", "'unsafe-inline'"],
        "script-src": ["'self'", "'unsafe-inline'", "'unsafe-eval'"],
    },
    "content_security_policy_nonce_in": ["script-src"],
    "force_https": False,
}`

Am I missing anything?

**Comment by mistercrunch** [comment]
@dosubot can you help troubleshoot @varun-verma-code's configuration?

**Comment by mistercrunch** [comment]
@dosubot your answer is pretty generic, now based on his earlier comment and SPECIFIC configuration, can you identify what exactly could be wrong with his configuration given the error message he's getting?
