### ISSUE TITLE
Infinite installation in Ubuntu

### ISSUE THREAD

**Issue by isaacschneuder** [apache/superset#30769]
### Bug description

I'm currenly trying to install Superset on my virtual machine ussing docker

`sudo docker-compose -f docker-compose-non-dev.yml up` 

But after 

`superset_init         | Init Step 4/4 [Complete] -- Loading examples`

The proccess just went on cyclus 

```
superset_app          | 127.0.0.1 - - [31/Oct/2024:14:19:08 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.88.1"
superset_app          | 127.0.0.1 - - [31/Oct/2024:14:19:38 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.88.1"
superset_worker_beat  | [2024-10-31 14:20:00,054: INFO/MainProcess] Scheduler: Sending due task reports.scheduler (reports.scheduler)
superset_worker       | [2024-10-31 14:20:00,057: INFO/MainProcess] Task reports.scheduler[776267e7-e913-420e-a4e1-5b094e23dd65] received
superset_worker       | [2024-10-31 14:20:00,063: INFO/ForkPoolWorker-1] Task reports.scheduler[776267e7-e913-420e-a4e1-5b094e23dd65] succeeded in 0.00419969399990805s: None
superset_app          | 127.0.0.1 - - [31/Oct/2024:14:20:08 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.88.1"
superset_app          | 127.0.0.1 - - [31/Oct/2024:14:20:38 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.88.1"
superset_worker_beat  | [2024-10-31 14:21:00,012: INFO/MainProcess] Scheduler: Sending due task reports.scheduler (reports.scheduler)
superset_worker       | [2024-10-31 14:21:00,015: INFO/MainProcess] Task reports.scheduler[690d92f0-45e5-4e08-8898-33d49370a158] received
superset_worker       | [2024-10-31 14:21:00,021: INFO/ForkPoolWorker-1] Task reports.scheduler[690d92f0-45e5-4e08-8898-33d49370a158] succeeded in 0.004534726000201772s: None
superset_app          | 127.0.0.1 - - [31/Oct/2024:14:21:08 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.88.1"
superset_app          | 127.0.0.1 - - [31/Oct/2024:14:21:38 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.88.1"
```

### Screenshots/recordings

![изображение](https://github.com/user-attachments/assets/92bd416c-7ea5-47b7-b7e9-4f3abe72a1e6)

### Superset version

3.1.3

### Python version

3.10

### Node version

I don't know

### Browser

Firefox

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by mistercrunch** [comment]
I'm not sure if I understand the issue, but looking at the log seems the service is up and available as expected. You should be able to access Superset on port 8088.

@isaacschneuder seem you might be expecting an installation that reports being done or something like that, but `docker-compose up` simply starts the service and is expected to keep running until you CTRL-C to stop the service.

**Comment by isaacschneuder** [comment]
@mistercrunch Thank you for your answer. I'm actually newby in docker and linux, so I'm sorry for asking stupid questions. I'm trying to install Superset on my virtual machine. I followed these instuctions:

`git clone https://github.com/apache/superset.git`

`cd superset`

`git status`

`sudo docker-compose -f docker-compose-non-dev.yml up`

I tried `docker compose up`, and after this i've got an error from screenshot:
![изображение](https://github.com/user-attachments/assets/00635ab4-d4ec-4111-be37-858c6dc4cd9a)

Also, after `docker compose start` seems like the containers started, but when i try in my browser <machine-ip>:8088, nothing is happening.
I thought, maybe I should intall celery and flask through pip, but there are the same errors.

![изображение](https://github.com/user-attachments/assets/82f25bd5-0875-439d-bfb2-e56827e6ad35)

![изображение](https://github.com/user-attachments/assets/4feff0d3-68cd-48b1-88bf-12894dabf789)

**Comment by geido** [comment]
Hello @isaacschneuder from your first screenshot it appears that Superset is running properly. Refer to the docs fore more info https://superset.apache.org/docs/installation/docker-compose/. I am closing this issue for now but feel free to comment if you are still experiencing some problems. Thank you!
