### ISSUE TITLE
iframe refresh

### ISSUE THREAD

**Issue by erdemcer** [apache/superset#30826]
I have a simple application which has iframe contains Superset dashboard. I would like to refresh dashboard from custom button in main page but everytime when refresh button is called full whole iframe is reloading. Is there any way to refresh dashboard in iframe without reloading whole iframe.

Thanks

**Comment by erdemcer** [comment]
Hi @dosu

Thanks for reply . But i have following error while initialize Switchboard in the parent window.

Uncaught ReferenceError: Switchboard is not defined

Could you please give detail about your outline ?

Thanks.

**Comment by erdemcer** [comment]
Hi,
I am not using module system. I am trying to import it from supersetEmbeddedSdk with "onst switchboard = new supersetEmbeddedSdk.Switchboard({ port: channel.port1 });" But gives another error ;
Uncaught TypeError: supersetEmbeddedSdk.Switchboard is not a constructor

Thanks.

**Comment by geido** [comment]
Hello @erdemcer I am closing this issue as this is not supported at the moment, but feel free to open up a PR to make this possible. Thank you!
