### ISSUE TITLE
Superset loading indefinitely at startup 

### ISSUE THREAD

**Issue by isc-jgupta** [apache/superset#30831]
### Bug description

Currently running on superset on an ubuntu container with apache-superset running on python. I am running version 4.0.2 of superset. I have 3 tabs with 6 graphs each and in one tab (called tab3) there are two filters that are required and use 
'Select first filter value by default'. I know that this issue has been resolved [before](https://github.com/apache/superset/issues/20748), but it seems like its an issue for the python library. The screenshot below shows it loading on startup and it stays that way unless I change the filter so that it doesnt select the first value by default. I need this option for my project however. 

### Screenshots/recordings

![Screenshot 2024-11-04 at 11 16 12 AM](https://github.com/user-attachments/assets/76da6e20-eaf2-4f29-8ab4-dc7929128f53)

### Superset version

4.0.2

### Python version

I don't know

### Node version

Not applicable

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by geido** [comment]
Hello @isc-jgupta from your screenshot it seems that all filters are out of scope? I am wondering if this an issue that happens only when every filter is not in scope and 'Select first filter value by default' is enabled for one of those.

**Comment by isc-jgupta** [comment]
i think all the filters are out of scope because the tabs havent loaded. If the tabs loaded it should be fewer filters out of scope and the first tab has all the filters with 'Select first filter value by default'

**Comment by isc-jgupta** [comment]
okay so it looks like the issue was the table with the 'Select first filter value by default' filter applied to it had no data on startup. when I loaded the table with some data, it loaded fine.

**Comment by isc-jgupta** [comment]
okay so it looks like the issue was the table with the 'Select first filter value by default' filter applied to it had no data on startup. when I loaded the table with some data, it loaded fine.
