### ISSUE TITLE
[SIP] Your Title Here (do nothittt add SIP number)

### ISSUE THREAD

**Issue by riikolilover** [apache/superset#30845]
*Please make sure you are familiar with the SIP process documented*
[here](https://github.com/apache/superset/issues/5602). The SIP will be numbered by a committer upon acceptance.

### Motivational 1

Description of the problem to be solved.
@ERROR#NULL # ERROR#NULL 
### Proposed Change

Describe how the feature will be implemented, or the problem will be solved. If possible, include mocks, screenshots, or screencasts (even if from different tools).

### New or Changed Public Interfaces

Describe any new additions to the model, views or `REST` endpoints. Describe any changes to existing visualizations, dashboards and React components. Describe changes that affect the Superset CLI and how Superset is deployed.

### New dependencies

Describe any `npm`/`PyPI` packages that are required. Are they actively maintained? What are their licenses?

### Migration Plan and Compatibility

Describe any database migrations that are necessary, or updates to stored URLs.

### Rejected Alternatives

Describe alternative approaches that were considered and rejected.

**Comment by rusackas** [comment]
Closing ths since it's not filled out... but please feel free to fill it out, and we can reopen it.
