### ISSUE TITLE
Fullscreen mode: Unnecessary vertical scrollbar blocks UI elements on right side of screen

### ISSUE THREAD

**Issue by praveer38** [apache/superset#30879]
## Screenshot

![chrome_j5mjQOUXzT](https://github.com/user-attachments/assets/5663a0ec-9205-46a5-927d-ec2cd6e8372a)
![chrome_8UBAYWGVV9](https://github.com/user-attachments/assets/ea22dc76-904a-4b8f-93b5-025d55bb6b19)

## Description

When a graph is in fullscreen mode, there is an unnecessary vertical scrollbar that blocks some of the UI elements on the right side of the screen (i.e. the “Inv” button).  This vertical scrollbar remains visible regardless of the browser window size.

Expected: 

The scrollbar should not be present. Even if the scrollbar is present, the buttons on the corner should not be affected the way they are getting hidden.

Actual:

The scrollbar is present and obscures some page elements under it

**Comment by samarsrivastav** [comment]
hey @praveer38 !! i have looked into the code and the issue, i think changing the padding of the chart in fullscreen mode will solve the issue 
here is an screenshot of the code and the website-
![Screenshot 2024-11-09 at 8 43 00 PM](https://github.com/user-attachments/assets/a4eb072d-b9e1-4505-928f-37b1f2b06679)
<img width="661" alt="Screenshot 2024-11-09 at 8 42 33 PM" src="https://github.com/user-attachments/assets/8298521e-5744-40dc-8845-0772e2e5331a">
Please letme know your thoughts
