### ISSUE TITLE
Formula Annotation Displays Incorrectly on Horizontal Bar Chart

### ISSUE THREAD

**Issue by yousoph** [apache/superset#30877]
### Bug description

When adding a formula-type annotation to a horizontal bar chart, the annotation does not display as expected. Instead of showing a vertical line to mark a value on the x-axis, the annotation appears as an additional category on the y-axis, which misleads the user and distorts the chart’s layout.

**How to reproduce the bug**
1. Create a horizontal bar chart.
2. Add a formula-type annotation to the chart.
    
![image](https://github.com/user-attachments/assets/00946a72-a73c-4d3e-a188-0427607a9e46)

3. Observe the annotation’s display behavior on the horizontal bar chart.

**Expected results**

The annotation should display as a vertical line across the chart, marking the relevant value on the x-axis, similar to how it works with vertical bar charts.

**Actual results**

The annotation doesn’t appear as a vertical line.

![image](https://github.com/user-attachments/assets/567f6a49-552e-4d2d-abc7-0fa82a3660fb)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by geido** [comment]
---

### 🎉 **Preset Bounty Available: $150 USD** 🎉

To claim this bounty, please carefully follow the steps below.

---

#### 📋 **Steps to Participate**

1. **Review Guidelines:**  
   Read through the [Preset Bounty Program Contribution Guide](https://preset.notion.site/preset-bounty-program-apache-superset) for complete details on bounty requirements.

2. **Show Your Interest:**  
   Complete the [Preset Bounty Program Survey](https://docs.google.com/forms/d/e/1FAIpQLSeDsR1iWvPxFydUIXs2agsUg3kMDaAooeD4P9P1L5sI0Yu5QQ/viewform?usp=sharing) and comment this issue to express your interest.

3. **Join the Slack Channel:**  
   After completing the survey, you’ll receive an invitation to the dedicated [Apache Superset Slack](https://join.slack.com/t/apache-superset/shared_invite/zt-2be0drwz8-bxPfkdz28ozzk1Iox29ufg) channel.

4. **Get Assigned:**  
   To officially start, ensure a **Bounty Program Manager** has assigned you to this issue.

5. **Submit Your Solution:**  
   When ready, submit your solution with the `Fixes #{issue_number}` notation in your Pull Request description.

6. **Claim Your Bounty:**  
   Sign up at [GitPay.me](https://gitpay.me/) and submit your solution via: [https://gitpay.me/#/task/979](https://gitpay.me/#/task/979)

---

#### 💡 **Additional Notes**

- Only developers assigned by a **Bounty Program Manager** should start working on this issue to win the bounty.
- Be sure to follow the guide closely to avoid any delays in payment. Please, allow a few days after your PR has been merged for the bounty to be released.

Good luck, and happy coding! 🎉

**Comment by DamianPendrak** [comment]
Hi, I am interested in working on this
