### ISSUE TITLE
Ant Design 5: Upgrade Alert component

### ISSUE THREAD

**Issue by geido** [apache/superset#30911]
Please refer to SIP-139 https://github.com/apache/superset/issues/29268.

The `Alert` component should be upgraded to Ant Design version 5.

Similar work has been completed [here](https://github.com/apache/superset/pulls?q=is%3Apr+label%3Afrontend%3Arefactor%3Aantd5+is%3Aclosed).

When upgrading the component to Ant Design 5, please ensure to include:

- Proper RTL test coverage if not present yet.
- A Storybook file (if not present) or all necessary changes.
- Include all relevant component options in the Storybook.
- Clean up unnecessary custom styles.

When opening a PR:
- Name your PR refactor({Component}): Upgrade {component} to Ant Design 5
- Add screenshots of BEFORE/AFTER in your PR.
- Update the [project tracker](https://github.com/apache/superset/discussions/29293) when your PR is merged.
- Make sure you or a committer has labeled your PR with [frontend:refactor:antd5](https://github.com/apache/superset/pulls?q=is%3Apr+label%3Afrontend%3Arefactor%3Aantd5+is%3Aclosed).

**Comment by LevisNgigi** [comment]
Hey @geido I would love to work on this

**Comment by geido** [comment]
Hello @fardin-developer feel free to work on issues if you like. However, to be eligible for the Preset bounties, you should be assigned by a bounty manager. It's all explained n the [Preset Bounty Program Contribution Guide](https://preset.notion.site/preset-bounty-program-apache-superset). Thank you!
