### ISSUE TITLE
Missing Docker Hub images for 4.1.0

### ISSUE THREAD

**Issue by padbk** [apache/superset#30919]
### Bug description

The Github Actions to upload the 4.1.0 release images to Docker Hub failed.
https://github.com/apache/superset/actions/runs/11826540775

It looks like this was due to the PR being incorrectly labelled.
https://github.com/apache/superset/actions/runs/11826540775/job/32952794218#step:9:41

Please can a new PR be made to ensure the images are pushed to Docker Hub.

### Superset version

master / latest-dev

### Python version

Not applicable

### Node version

Not applicable

### Browser

Not applicable

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by janhoon** [comment]
commit for 4.1.0 is available: https://hub.docker.com/layers/apache/superset/855f4c4897771cf454c8a0172eb21e47d13f3614/images/sha256-a64435896d2c21cb775a0e08035c68e64ed15cefea916a863ccf575b3babf5f0?context=explore

**Comment by sadpandajoe** [comment]
@padbk unsure why the docker image hasn't published? I see that 4.1.0rc4 was published fine and this is using the same SHA. May need someone with more knowledge of how our Docker pipeline works to take a look at it.

@michael-s-molina @mistercrunch any ideas? Wondering if this is something in the dockerfile in the branch or if it's an issue with the dockerfile in the master branch.

**Comment by villebro** [comment]
@sadpandajoe for some reason the release pipeline hasn't triggered correctly when 4.1.0 was released: https://github.com/apache/superset/actions/workflows/docker-release.yml I wonder if something has changed on this workflow since 4.0 branch that causes it to not trigger..

**Comment by sadpandajoe** [comment]
> @sadpandajoe for some reason the release pipeline hasn't triggered correctly when 4.1.0 was released: https://github.com/apache/superset/actions/workflows/docker-release.yml I wonder if something has changed on this workflow since 4.0 branch that causes it to not trigger..

Yeah really weird that that 4.1.0rc releases aren't there either

**Comment by villebro** [comment]
Hmm, it seems that one has been replaced by this workflow: https://github.com/apache/superset/actions/workflows/tag-release.yml But now I'm confused, why is it publishing the RCs correctly, despite them having failed here, but not the actual release? 🤔

**Comment by sadpandajoe** [comment]
Potentially I see this issue: https://github.com/apache/superset/issues/30928. Weird thing is that RC4 is in docker and the official isn't. I can fast follow with a 4.1.1 to address this as I've already cherried a fix and other things in it. Thoughts?

**Comment by mistercrunch** [comment]
I looked into it yesterday and seems the docker build are running out of memory/getting killed. I checked to see if that's the case in master too, but seems to be ok on master, so I was wondering if there have been docker optimizations since the `4.1` cut that explain that.

To clarify, the GHA uses the Dockerfile from the release branch, meaning if we improved the Dockerfile since then, those improvements wouldn't be in the release. Wondering if we could/should cherry-pick improvements to the Dockerfile/build-process

**Comment by mistercrunch** [comment]
> Potentially I see this issue: https://github.com/apache/superset/issues/30928.

to me it really looked like out-of-memory issue, seeing randomly killed jobs in the middle of their runs

**Comment by mistercrunch** [comment]
As to what to cherry-pick to test my theory, looking at file change history on the dockerfile seems like a decent start -> https://github.com/apache/superset/commits/master/Dockerfile

Unclear how cherry-pickable those PRs are though, can't allocate time to help with this today but sharing the pointers.

**Comment by mistercrunch** [comment]
I feel we've been on the edge of the memory cliff for docker builds, to a point where failures are non-deterministic. Maybe there are some envrionment-related variations, where a worker may have more memory than another (?)

I tried to look for sequential layer builds (docker does parallel layer build when it can), but didn't have success with what I tried. Similar results with trying to reduce parallelization in `apt-get` installation. Could also look at `pip` parallelism

**Comment by sadpandajoe** [comment]
Created a new 4.1.1 patch to hopefully fix the issues. We can see that the docker files are all created for 4.1.1rc1: https://hub.docker.com/r/apache/superset/tags?name=4.1.1. Once we get the votes, we can go ahead and push that out.

**Comment by dpgaspar** [comment]
did a rerun of the action here: https://github.com/apache/superset/actions/runs/11826540775/job/33133371854

seeing this error: Invalid: lock file's luxon@3.4.4 does not satisfy luxon@3.5.0

**Comment by sadpandajoe** [comment]
> did a rerun of the action here: https://github.com/apache/superset/actions/runs/11826540775/job/33133371854
> 
> seeing this error: Invalid: lock file's luxon@3.4.4 does not satisfy luxon@3.5.0

@dpgaspar do we know why this was not a problem during our 4.1.0rc4 cut but it is on the official one? Nothing changed between cuts.

**Comment by gpchandran** [comment]
> Created a new 4.1.1 patch to hopefully fix the issues. We can see that the docker files are all created for 4.1.1rc1: https://hub.docker.com/r/apache/superset/tags?name=4.1.1. Once we get the votes, we can go ahead and push that out.

Hi @sadpandajoe  - can you please help to push this ASAP

**Comment by sadpandajoe** [comment]
> > Created a new 4.1.1 patch to hopefully fix the issues. We can see that the docker files are all created for 4.1.1rc1: https://hub.docker.com/r/apache/superset/tags?name=4.1.1. Once we get the votes, we can go ahead and push that out.
> 
> Hi @sadpandajoe - can you please help to push this ASAP

@gpchandran will need 3 binding +1 votes before I can make it official.

**Comment by sadpandajoe** [comment]
4.1.1 docker image are up so those can now be used.
