### ISSUE TITLE
pdf export when embedding works only on visible graphics

### ISSUE THREAD

**Issue by jpchev** [apache/superset#30913]
### Bug description

exporting to pdf from iframe doesn't work well, only the visible graphics are displayed in the pdf file, the other ones, in the hidden parts of the page (visible by scrolling the iframe) won't appear in the pdf.

### Superset version

4.0.2

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by jpchev** [comment]
this seems a duplicate of #29589 27532

**Comment by rusackas** [comment]
Agreed on the duplication... let's close this in favor of https://github.com/apache/superset/issues/27532 if that's OK :)

**Comment by jpchev** [comment]
ok
