### ISSUE TITLE
Missing helm artifact for 4.1.0

### ISSUE THREAD

**Issue by moshe** [apache/superset#30951]
### Bug description

My be related to https://github.com/apache/superset/issues/30919
it seems like the latest version available in helm registry is 4.0.1 while 4.1.0 already release few days ago.
```
$ helm search repo superset
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
stable/superset         1.1.13          0.36.0          DEPRECATED - Apache Superset (incubating) is a ...
superset/superset       0.13.1          4.0.1           Apache Superset is a modern, enterprise-ready b...
```

### Superset version

4.1.0

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by villebro** [comment]
Closing this, as this discussion is specific to the Docker image, not Helm chart, and is ongoing in #30919.
