### ISSUE TITLE
Tags column in a specific tag's page is not populated

### ISSUE THREAD

**Issue by yousoph** [apache/superset#31009]
### Bug description

Repro steps: 
Make sure the feature flag for TAGGING_SYSTEM is enabled and your user has permission to create tags 
1. Visit the tags page
2. Create 2 or more tags 
3. Tag a chart or dashboard with at least 2 tags 
4. From the Tags page, click on an individual tag to see all assets tagged with that tag 

Note that the tags column should show all OTHER tags (not including the tag whose page you are viewing) but it is blank 

### Screenshots/recordings

<img width="1182" alt="image" src="https://github.com/user-attachments/assets/489dc17a-ce33-4680-8e81-30ee689d9eeb">

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by LevisNgigi** [comment]
Hey @geido I'm interested in taking this.

**Comment by alexandrusoare** [comment]
I am interested in this one
