### ISSUE TITLE
Big Number + Big Number with Trendline get cut off on dashboards

### ISSUE THREAD

**Issue by yousoph** [apache/superset#31010]
### Bug description

Repro: 
1. Create a Big Number chart or a Big Number with Trendline chart 
2. in the Customize tab, set the font size to Normal, large or huge (this bug seems harder to repro when the font size is Small or Tiny, but it might still be possible) 
3. Save the chart and add it to a dashboard 

Currently, the numbers on the right get cut off easily. Typically, giving the chart a lot more horizontal space will fix the issue, but the font should resize correctly to not be cut off if there's not enough space. 

### Screenshots/recordings

![image](https://github.com/user-attachments/assets/935d4177-be3e-43ae-9900-e7e767491301)
<img width="364" alt="image" src="https://github.com/user-attachments/assets/05c81d72-b908-412e-b74e-08a898fab899">

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by fardin-developer** [comment]
Hey would love to work on this issue.

**Comment by aybanda** [comment]
@geido 
Hey, I would love to work on this issue! Please let me know if I can be assigned to it. Thank you!

**Comment by sfirke** [comment]
Anyone know whether this has a common cause with https://github.com/apache/superset/issues/25131, which seems to be the same phenomenon but for horizontal bar charts?
