### ISSUE TITLE
Make Saved Query titles into links 

### ISSUE THREAD

**Issue by yousoph** [apache/superset#31011]
## Screenshot

<img width="1336" alt="image" src="https://github.com/user-attachments/assets/e838e324-58fe-4f70-8630-2774b6d1a282">

## Description

For consistency with the other CRUD pages, we should make the "Name" column of the Saved Query page into links. Links would open the query in SQL Lab (same functionality as the edit button on the right)

**Comment by LevisNgigi** [comment]
Hey I would Love to work on this.
