### ISSUE TITLE
Image Docker not available for 4.1.0

### ISSUE THREAD

**Issue by xavier-GitHub76** [apache/superset#31012]
### Bug description

Images docker are available for 4.0.2 or 4.1.1 but not for 4.1.0
![image](https://github.com/user-attachments/assets/14a6ebf3-27de-4f30-9007-59b24ba896e5)
![image](https://github.com/user-attachments/assets/70d85082-2491-4102-a3cc-f33f59058b64)
![image](https://github.com/user-attachments/assets/eded3478-a009-4327-8c85-880e1d43ec33)

The build is automatised (https://superset.apache.org/docs/installation/docker-builds/)
the 4.1.0 image should be present

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by sadpandajoe** [comment]
There is a whole thread here: https://github.com/apache/superset/issues/30919. We ran into some issues so we bumped to 4.1.1 to fix the docker issue.
