### ISSUE TITLE
Remove Moment.js in favor of Day.js

### ISSUE THREAD

**Issue by geido** [apache/superset#31178]
Moment is a legacy library as mentioned in their GitHub repo https://github.com/moment/moment

> Moment.js is a legacy project, now in maintenance mode. In most cases, you should choose a different library.

We have seen issues arising on the [DatePicker](https://github.com/apache/superset/pull/31019) component related to `Moment.js` which led us to the decision to remove `Moment.js` from the repo in favor of `Day.js`. 

`Day.js` offers a much smaller bundle size, it is supported by Ant Design out of the box and it is already installed in Superset.

**Comment by geido** [comment]
---

### 🎉 **Preset Bounty Available: $500 USD** 🎉

To claim this bounty, please carefully follow the steps below.

---

#### 📋 **Steps to Participate**

1. **Review Guidelines:**  
   Read through the [Preset Bounty Program Contribution Guide](https://preset.notion.site/preset-bounty-program-apache-superset) for complete details on bounty requirements.

2. **Show Your Interest:**  
   Complete the [Preset Bounty Program Survey](https://docs.google.com/forms/d/e/1FAIpQLSeDsR1iWvPxFydUIXs2agsUg3kMDaAooeD4P9P1L5sI0Yu5QQ/viewform?usp=sharing) and comment this issue to express your interest.

3. **Join the Slack Channel:**  
   After completing the survey, you’ll receive an invitation to the dedicated [Apache Superset Slack](https://join.slack.com/t/apache-superset/shared_invite/zt-2be0drwz8-bxPfkdz28ozzk1Iox29ufg) channel.

4. **Get Assigned:**  
   To officially start, ensure a **Bounty Program Manager** has assigned you to this issue.

5. **Submit Your Solution:**  
   When ready, submit your solution with the `Fixes #{issue_number}` notation in your Pull Request description.

6. **Claim Your Bounty:**  
   Sign up at [GitPay.me](https://gitpay.me/) and submit your solution via: [https://gitpay.me/#/task/986](https://gitpay.me/#/task/986)

---

#### 💡 **Additional Notes**

- Only developers assigned by a **Bounty Program Manager** should start working on this issue to win the bounty.
- Be sure to follow the guide closely to avoid any delays in payment. Please, allow a few days after your PR has been merged for the bounty to be released.

Good luck, and happy coding! 🎉

**Comment by msyavuz** [comment]
Hey, as it is a blocker for datepicker  i would like to take this.

**Comment by b4s36t4** [comment]
Hi, would love to work on this. Can I get assigned?!

**Comment by Niharika0104** [comment]
I would like to work on this issue.@geido

**Comment by geido** [comment]
This issue is already assigned and currently being worked on. Thanks
