### ISSUE TITLE
Bar chart v2 hide x-axis labels v.4.0.2

### ISSUE THREAD

**Issue by ReilTride** [apache/superset#31179]
## Screenshot
![image](https://github.com/user-attachments/assets/53d9c8e2-8eb5-4f5a-a109-700230a771b9)

## Description

Is there any way to hide these x-axis labels? And also still be able to see in the bar tooltip?

**Comment by ReilTride** [comment]
@dosu where do i change this param?

**Comment by ReilTride** [comment]
Guess bot is talking about legacy bar chart

**Comment by geido** [comment]
@ReilTride feel free to join us on Apache Superset Slack or open a discussion Q&A thread for this type of questions. Thank you!
