### ISSUE TITLE
slack error in superset

### ISSUE THREAD

**Issue by Chethanibms** [apache/superset#31196]
### Bug description

slack error in superset

### Screenshots/recordings

<img width="1420" alt="Screenshot 2024-11-29 at 1 45 57 PM" src="https://github.com/user-attachments/assets/14283efe-5f6e-49f7-9897-6f85809581e0">

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

superset.commands.report.exceptions.ReportScheduleClientErrorsException: [SupersetError(message="The request to the Slack API failed. (url: https://www.slack.com/api/files.upload)\nThe server responded with: {'ok': False, 'error': 'method_deprecated'}", error_type=<SupersetErrorType.REPORT_NOTIFICATION_ERROR: 'REPORT_NOTIFICATION_ERROR'>, level=<ErrorLevel.WARNING: 'warning'>, extra=None)]

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by geido** [comment]
Hello @Chethanibms please check this PR and make sure you have the correct scopes in place https://github.com/apache/superset/pull/29264. Let me know if you will still be experiencing this problem. For now, I'll close this issue. Thanks!

**Comment by czapajew** [comment]
I'm using the same issue after installing version 4.1.1 with helm chart.

**Comment by czapajew** [comment]
Can we reopen this one?

**Comment by rusackas** [comment]
@czapajew can you give us a little more to go on? Does reviewing/setting the correct scopes as @geido suggested solve the issue?

**Comment by eschutho** [comment]
Can you also try setting this flag to true? `ALERT_REPORT_SLACK_V2`
