### ISSUE TITLE
<Futureeloquencylifeluxlivingbe>military_-_study

### ISSUE THREAD

**Issue by jojo6399** [apache/superset#31276]
### Bug description

> ExemexE
### 
_Exe.exE_
**exE.Exe**
_ExexexE_
### 
> exe.exe

### Screenshots/recordings

![wp6436496-jaguar-4k-wallpapers~2-3](https://github.com/user-attachments/assets/f5ee6035-3172-4365-a5f9-b9caf70a7d73)

### Superset version

4.1.1

### Python version

3.11

### Node version

18 or greater

### Browser

Safari

### Additional context

![wp6436496-jaguar-4k-wallpapers~2-3](https://github.com/user-attachments/assets/10500da5-3696-4044-a0ce-a91b1111b40d)

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Not sure what this is all about, but closing this.
