### ISSUE TITLE
Importing CSV: the csv has a date column but it appears in the database as a string

### ISSUE THREAD

**Issue by Kamilooosx** [apache/superset#31272]
### Bug description

CSV import loads string type every time, instead of date. I check the Columns to be parsed as dates option but it still doesn't work. I tried 
Database:File Uploads 
Schema: main
I checked all data types in CSV for example YYYY-MM-DD or 2024-07-09 09:15:05
Version: 4.1.0.3

### Superset version

4.1.1

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by sfirke** [comment]
Did the same file + upload choices successfully get turned into a date using Superset version 4.0.2?

**Comment by Kamilooosx** [comment]
I hadn't used the CSV import feature before updating to version 4.1.0.3. 
When I uploaded the CSV file to BigQuery and connected it to the database, everything worked correctly. 
I am working with Preset.

**Comment by sfirke** [comment]
I can't replicate this in Superset 4.1.1. I created a CSV with a column called "datetime" and a value of `2024-07-09 09:15:05`. I then uploaded it into Superset, specifying that the column called "datetime" was a date time column. It loaded into my data warehouse with the correct column type and I was able to make time series charts in Superset with it.

My only guess is that there's some invalid date-time value lurking in that column and causing it to be a string.  I once had this problem and finally figured out that a user had inputted some invalid date, like 2023-02-29 when that year wasn't a leap year for instance. Or an invalid time like 25:00. Once I deleted those few rows, it worked correctly.

If you are able to create a reproducible minimal example that indicates this is indeed a problem with Superset, please share it on this issue.

**Comment by Kamilooosx** [comment]
I created a CSV file with random data, where the date format is similar to yours, but the bug still persists.
![image](https://github.com/user-attachments/assets/788b4a3f-92ad-494b-96c5-47263638df4f)
![image](https://github.com/user-attachments/assets/7a382a4f-6428-4c2d-85c8-c40368177351)
![image](https://github.com/user-attachments/assets/aae57a97-0e4b-481c-882d-65a688d5d440)
![image](https://github.com/user-attachments/assets/6e5d0f37-5665-4efd-9091-e1b6c476811e)
![image](https://github.com/user-attachments/assets/1b1a3dcb-b499-4971-82c2-7a0eb7177737)
[health_center_data (1).csv](https://github.com/user-attachments/files/18030580/health_center_data.1.csv)
![image](https://github.com/user-attachments/assets/598a3496-2eb3-4ee5-bcda-43422822ffff)

**Comment by yousoph** [comment]
Hi @Kamilooosx , once the upload has finished, if you're having trouble with the column type, you should be able to go into your dataset under the Columns tab and mark the time column as a temporal column to use it as a time column in charts

<img width="864" alt="image" src="https://github.com/user-attachments/assets/839cb484-14e4-42df-9793-1a42c4bd084d">

**Comment by Kamilooosx** [comment]
Yeah ! It works ! But when i want to filter by Date it's generate error :C 
![image](https://github.com/user-attachments/assets/f79b02a8-eab9-4e81-982d-ea375c806b05)
