### ISSUE TITLE
gear R-1-6-7 {H}

### ISSUE THREAD

**Issue by jojo6399** [apache/superset#31277]
## Screenshot

[drag & drop image(s) here!]

## Description

[describe the issue here!]

## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

**Comment by rusackas** [comment]
Not sure what these two issues are all about, but please don't spam the repo.
