### ISSUE TITLE
Slack invitation links on Superset website and Github README expired

### ISSUE THREAD

**Issue by glothriel** [apache/superset#31280]
## Screenshot

Those:
![image](https://github.com/user-attachments/assets/ec7b4a51-45ee-40aa-b0b8-05738823ac42)
![image](https://github.com/user-attachments/assets/52396baf-b495-4e48-9729-a468ea1e62f6)
![image](https://github.com/user-attachments/assets/cd9db587-18de-417d-bf60-a35dcfaf70b4)

Result in:
![image](https://github.com/user-attachments/assets/a47e94af-e029-4cb7-9182-eadb4729f696)

## Description

It appears that the invitation link has expired.

**Comment by sfirke** [comment]
Thanks for reporting! cc @rusackas who has fixed this in the past 🙏
