### ISSUE TITLE
Unable to parse SQL (Dialects.POSTGRES)

### ISSUE THREAD

**Issue by antonio-tg** [apache/superset#31307]
### Bug description

I just upgraded from version 2.1.3 to 4.1.1 and everything looks great, except that I have problems with some very particular queries, queries like for example:

```sql
select lpad(cast(field as text),4,'0') as "Original_field"
from schema.table
```

These queries worked without problems in superset 2.1.3 and not being able to execute them has made my users go crazy because they have hundreds of queries with the same problem, if I remove the double quotes the query runs without problems, but this is unacceptable for my users because their queries generate tables that in turn are used in other queries which would force them to rework a lot.

This is what the logs show me:

```log
2024-12-05 16:20:26,759:WARNING:superset.sql_parse:Unable to parse SQL (Dialects.POSTGRES): Template(body=[Output(nodes=[TemplateData(data='select lpad(cast(field as text),4,\'0\') as "Original_field"\nfrom schema.table')])])
```

It is worth mentioning that this only happens if the role is given permissions on a certain schema, that is, if I give it permissions on the entire database this does not happen, in that sense it is similar to what was reported by #31183.

### Screenshots/recordings

This is what sql_lab shows me.

![image](https://github.com/user-attachments/assets/2c2dc7bb-f682-4874-86c6-a65d0ac46962)

### Superset version

4.1.1

### Python version

3.10

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by betodealmeida** [comment]
Working on a fix for this.

**Comment by betodealmeida** [comment]
Fix is out, as a workaround you can enable the `ENABLE_TEMPLATE_PROCESSING` feature flag.

**Comment by antonio-tg** [comment]
Thank you so much @betodealmeida,  we really appreciate your support.
