### ISSUE TITLE
when save dashboard, 400error occured. I use superset original source and almost do not change source.

### ISSUE THREAD

**Issue by q631599119** [apache/superset#31317]
### Bug description

![image](https://github.com/user-attachments/assets/c8fcc46e-0e3c-4125-b4d5-45ecf0e30a25)
![image](https://github.com/user-attachments/assets/d0eab58c-ba3e-4753-82cf-6c0a805947d2)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by q631599119** [comment]
python version 3.10
node version 20

> This suggests that the error occurs due to missing or invalid query context data when attempting to save the dashboard

error message is from backend， error is {
  "message": {
    "json_metadata": [
      {
        "map_label_colors": [
          "Unknown field."
        ],
        "shared_label_colors": [
          "Not a valid mapping type."
        ]
      }
    ]
  }
}

**Comment by q631599119** [comment]
> python version 3.10 node version 20
> 
> > This suggests that the error occurs due to missing or invalid query context data when attempting to save the dashboard
> 
> error message is from backend， error is { "message": { "json_metadata": [ { "map_label_colors": [ "Unknown field." ], "shared_label_colors": [ "Not a valid mapping type." ] } ] } }

python version 3.10
node version 20

This suggests that the error occurs due to missing or invalid query context data when attempting to save the dashboard
@dosu
error message is from backend， error is {
"message": {
"json_metadata": [
{
"map_label_colors": [
"Unknown field."
],
"shared_label_colors": [
"Not a valid mapping type."
]
}
]
}
}

**Comment by q631599119** [comment]
request data ：
certification_details
: 
""
certified_by
: 
""
css
: 
""
dashboard_title
: 
"[ untitled dashboard ]"
json_metadata
: 
"{\"chart_configuration\":{\"1\":{\"id\":1,\"crossFilters\":{\"scope\":\"global\",\"chartsInScope\":[]}}},\"global_chart_configuration\":{\"scope\":{\"rootPath\":[\"ROOT_ID\"],\"excluded\":[]},\"chartsInScope\":[1]},\"map_label_colors\":{\"SUM(net_sales_outside_tax)\":\"#1FA8C9\"},\"color_scheme\":\"\",\"positions\":{\"DASHBOARD_VERSION_KEY\":\"v2\",\"ROOT_ID\":{\"type\":\"ROOT\",\"id\":\"ROOT_ID\",\"children\":[\"GRID_ID\"]},\"GRID_ID\":{\"type\":\"GRID\",\"id\":\"GRID_ID\",\"children\":[\"ROW-3ewow1zW_T4gLZE--DRbf\"],\"parents\":[\"ROOT_ID\"]},\"HEADER_ID\":{\"id\":\"HEADER_ID\",\"type\":\"HEADER\",\"meta\":{\"text\":\"[ untitled dashboard ]\"}},\"CHART-S5hNAliZjz5xkRZKM5YZ7\":{\"type\":\"CHART\",\"id\":\"CHART-S5hNAliZjz5xkRZKM5YZ7\",\"children\":[],\"parents\":[\"ROOT_ID\",\"GRID_ID\",\"ROW-3ewow1zW_T4gLZE--DRbf\"],\"meta\":{\"width\":4,\"height\":50,\"chartId\":1,\"sliceName\":\"TRN_POSヘッダ--純売上外税金額\"}},\"ROW-3ewow1zW_T4gLZE--DRbf\":{\"type\":\"ROW\",\"id\":\"ROW-3ewow1zW_T4gLZE--DRbf\",\"children\":[\"CHART-S5hNAliZjz5xkRZKM5YZ7\"],\"parents\":[\"ROOT_ID\",\"GRID_ID\"],\"meta\":{\"background\":\"BACKGROUND_TRANSPARENT\"}}},\"refresh_frequency\":0,\"color_scheme_domain\":[],\"expanded_slices\":{},\"label_colors\":{},\"shared_label_colors\":[],\"timed_refresh_immune_slices\":[],\"cross_filters_enabled\":true,\"default_filters\":\"{}\",\"filter_scopes\":{}}"
owners
: 
[1]
0
: 
1
slug
: 
null
![image](https://github.com/user-attachments/assets/e7c04f0c-9084-4eb5-94c6-636020cfa117)
![image](https://github.com/user-attachments/assets/20227a5c-57db-4083-bcee-66522c00f8c6)
![image](https://github.com/user-attachments/assets/27de1c89-d81e-412a-9dec-09a10326d62f)

![image](https://github.com/user-attachments/assets/e0f98cf6-a485-4dae-bcd8-65a87f5569ae)

@dosu
those are data and source.

**Comment by q631599119** [comment]
@dosu thank you , i continue to check source

**Comment by geido** [comment]
Hello @q631599119 thanks for reporting the issue. However, I could not repro this on Superset. I am closing it for now. Feel free to re-open with reproducible steps if you are still experiencing the problem.

**Comment by Cinal** [comment]
Hey :raised_hand: I'm encountering the same issue. I cannot edit dashboards or add new ones.
The issue arises as soon as I define a new dashboard and add any layout element (e.g., a divider bar). Saving is not possible.
In the payload being sent, I do not see these new fields.

This issue occurs on the commit: 827fe0690327604338125adcf2eafd9bc7701ec0.
It was working correctly on a previous version I used (Commits on Nov 6, 2024): Commit f704b0f5568bc5d07360d8d365510369a6088011.

Could you please reopen the issue? I am happy to provide additional details if necessary.
![Screenshot 2024-12-11 at 01 21 55](https://github.com/user-attachments/assets/dd7e6c09-0122-4f80-84bd-b690249a2b30)
