### ISSUE TITLE
When selecting multiple filter values in the chart,the same color is being applied to both, making it difficult to distinguish between them visually.

### ISSUE THREAD

**Issue by ShwethaSJ** [apache/superset#31368]
### Bug description

Steps to Reproduce:

Navigate to the filter section in the dashboard.
Select multiple filters(Shift A and Shift B) for the scenario explained. Apply the filters.
Scroll to view the charts having a reference of shift A and Shift B.

### Screenshots/recordings

Hi Team,
I have noticed an issue when selecting multiple filter values, such as Shift A and Shift B. In the resulting chart, the same color is being applied to both shifts, making it difficult to distinguish between them visually.

Steps to Reproduce:
1) Navigate to the filter section in the dashboard.
2) Select multiple filters(Shift A and Shift B) for the scenario explained. Apply the filters.
3) Scroll to view the charts having a reference of shift A and Shift B.

I have attached a screenshot for your reference. Please let me know if there’s a way to resolve this issue by ensuring distinct colors for each filter value.
![Multi Filter(Superset)](https://github.com/user-attachments/assets/f804fddd-bf8d-4e51-abea-ad787bd6b5f1)

Looking forward to your support.
Regards,
Shwetha

### Superset version

4.0.2

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Do you have a dashboard color palette applied in the dashboard settings? Any custom "label_colors" in the dashboards json properties? 

Pinging @geido here, who hates these problem but has the unfortunate stance of being the expert here ;)

**Comment by geido** [comment]
Has the color of any of the dimensions changed after applying the filters? If not, I would say this is the expected behaviour. Collisions can happen.

**Comment by ShwethaSJ** [comment]
Hi Geido,
With regard to above concern raised, I have not applied color palette in the dashboard settings or used "label_colors" in the json properties. However to my surprise today, I find on selecting multiple filter values, such as Shift A and Shift B I am able to see different color palette getting reflected in pie-chart but I find same color palette shown for shift A,B in the bar chart. Please find the screenshot attached.
![image](https://github.com/user-attachments/assets/6e9e93e4-a7c2-4cbf-8a6c-97eedbf7c30e)

**Comment by geido** [comment]
> Hi Geido, With regard to above concern raised, I have not applied color palette in the dashboard settings or used "label_colors" in the json properties. However to my surprise today, I find on selecting multiple filter values, such as Shift A and Shift B I am able to see different color palette getting reflected in pie-chart but I find same color palette shown for shift A,B in the bar chart. Please find the screenshot attached. ![image](https://private-user-images.githubusercontent.com/191213033/394626182-6e9e93e4-a7c2-4cbf-8a6c-97eedbf7c30e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MTYxNjIsIm5iZiI6MTczMzkxNTg2MiwicGF0aCI6Ii8xOTEyMTMwMzMvMzk0NjI2MTgyLTZlOWU5M2U0LWE3YzItNGNiZi04YTZjLTk3ZWVkYmY3YzMwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQxMTE3NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTgwYThmNjcxYjAzNjA5OTkyZDQ4ZDM0ODIzODg4Yzk0YzE1ODQyZjBjMTU3YzBhOGZkMzZhZDhiOTYwOWM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6lDUIzDQVPCKvtTG3edh6jjXuys8gzayDKUjmKNCJGY)

Were those colors of A and B different before filtering?

**Comment by ShwethaSJ** [comment]
I have set a default filter for Shift A, which displayed in grey color. Later, when I selected Shift B along with the previously selected Shift A filter, the color for Shift B appeared different today. However, yesterday, under the same conditions, both shifts displayed the same color.

**Comment by geido** [comment]
I am closing this issue for now as this problem should be resolved in 4.1.
