### ISSUE TITLE
Only part of the screen is in Chinese, the rest is in English

### ISSUE THREAD

**Issue by q631599119** [apache/superset#31396]
### Bug description

![image](https://github.com/user-attachments/assets/00e0aeaf-c6c4-4b05-844d-07cb3f2aad7d)
Only part of the screen is in Chinese, the rest is in English

### Superset version

master / latest-dev

### Python version

3.10

### Node version

18 or greater

### Browser

Chrome

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by q631599119** [comment]
@dosu how to use pybabel

**Comment by q631599119** [comment]
@dosu  it does not work

**Comment by q631599119** [comment]
@dosu 出现了下边的错误
(python-10-local-test) PS F:\LT\workspcae_new\superset-master> pybabel compile -d superset/translations
error: superset/translations\ar\LC_MESSAGES\messages.po:164: placeholders are incompatible
error: superset/translations\ar\LC_MESSAGES\messages.po:172: placeholders are incompatible
error: superset/translations\ar\LC_MESSAGES\messages.po:180: unknown named placeholder 'prefix'
error: superset/translations\ar\LC_MESSAGES\messages.po:343: placeholders are incompatible
error: superset/translations\ar\LC_MESSAGES\messages.po:1678: incompatible format for placeholder 1: 's' and 'd' are not compatible
error: superset/translations\ar\LC_MESSAGES\messages.po:2412: placeholders are incompatible
error: superset/translations\ar\LC_MESSAGES\messages.po:3580: placeholders are incompatible
error: superset/translations\ar\LC_MESSAGES\messages.po:3691: unknown named placeholder 'name'
error: superset/translations\ar\LC_MESSAGES\messages.po:5955: placeholders are incompatible

**Comment by q631599119** [comment]
@dosu Change the menu Item， What file is the triggered function in? How was it achieved?

export default function LanguagePicker(props: LanguagePickerProps) {
  const { locale, languages, ...rest } = props;
  console.log('====================================');
  console.log(languages);
  console.log('====================================');
  return (
    <SubMenu
      aria-label="Languages"
      title={
        <div className="f16">
          <StyledFlag className={`flag ${languages[locale].flag}`} />
        </div>
      }
      icon={<Icons.TriangleDown />}
      {...rest}
    >
      {Object.keys(languages).map(langKey => (
        <Menu.Item
          key={langKey}
          style={{ whiteSpace: 'normal', height: 'auto' }}
        >
          <StyledLabel className="f16">
            <i className={`flag ${languages[langKey].flag}`} />
            <a href={languages[langKey].url}>{languages[langKey].name}</a>
          </StyledLabel>
        </Menu.Item>
      ))}
    </SubMenu>
  );
}

**Comment by q631599119** [comment]
@dosu the url is /lang/zh， where will it reach？

**Comment by rusackas** [comment]
Hi there. Indeed, we don't consider incomplete translations to be bugs, but we do welcome additional contributions to the translation effort (basically, editing the `.po` files as documented [here](https://superset.apache.org/docs/contributing/howtos/#contributing-translations).)
