### ISSUE TITLE
docker compose -f docker-compose-image-tag.yml up fails with "uv: command not found"

### ISSUE THREAD

**Issue by 2af** [apache/superset#31510]
### Bug description

I follow the quickstart guide and at the step of 
**docker compose -f docker-compose-image-tag.yml up**
It downloaded all the images and after the DB and REDIS containers initialized all the other containers were constantly spamming the output with messages like:
```

superset_app          | Reinstalling the app in editable mode
superset_app          | /app/docker/docker-bootstrap.sh: line 24: uv: command not found
superset_worker_beat  | Reinstalling the app in editable mode
superset_worker_beat  | /app/docker/docker-bootstrap.sh: line 24: uv: command not found

```

I was able to start Superset with 
**docker compose -f docker-compose-non-dev.yml up**

How can I troubleshoot what happened with the suggested 
**docker-compose-image-tag.yml**
flow?

### Superset version

master / latest-dev

### Python version

Not applicable

### Node version

Not applicable

### Browser

Not applicable

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by kidzen** [comment]
same here

**Comment by small-flowers** [comment]
I have also encountered the same problem. How can I solve it?

**Comment by maeddes** [comment]
I have the same issue on different platfors. It seems that the `uv` command got added in some files, e.g. `docker/docker-boostrap.sh` however it is not present in the underlying superset container image.

Temporary workaround is to go back to a version previous to the commits of December, e.g. https://github.com/apache/superset/releases/tag/4.1.1

`git fetch --tags` if you cloned with `depth=1` and `git checkout 4.1.1` made my docker compose work again with the docker-compose-image-tag.yml file.

I still think there will be a patched base image soon.

**Comment by javalram-ow** [comment]
same here

**Comment by Lucas-87an** [comment]
1. Lack of the package that provides the uv command:
The uv command may be related to the uvicorn package, which is a popular ASGI server for Python applications such as Apache Superset.
If uvicorn is not installed correctly in the environment, the system will not be able to find the uv command (which would normally be a shortcut to uvicorn itself).

in the docker-bootstrap.sh file it worked like this for me
set -eo pipefail

# Ensure uvicorn is installed
pip install uvicorn

# Make python interactive
if [ "$DEV_MODE" == "true" ]; then
    echo "Reinstalling the app in editable mode"
    pip install -e .
fi

REQUIREMENTS_LOCAL="/app/docker/requirements-local.txt"
# If Cypress run – overwrite the password for admin and export env variables
if [ "$CYPRESS_CONFIG" == "true" ]; then
    export SUPERSET_CONFIG=tests.integration_tests.superset_test_config
    export SUPERSET_TESTENV=true
    export SUPERSET__SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://superset:superset@db:5432/superset
fi

if [[ "$DATABASE_DIALECT" == postgres* ]] ; then
    echo "Installing postgres requirements"
    pip install -e .[postgres]
fi

# Make sure we have dev requirements installed
if [ -f "${REQUIREMENTS_LOCAL}" ]; then
  echo "Installing local overrides at ${REQUIREMENTS_LOCAL}"
  pip install --no-cache-dir -r "${REQUIREMENTS_LOCAL}"
else
  echo "Skipping local overrides"
fi

case "${1}" in
  worker)
    echo "Starting Celery worker..."
    # setting up only 2 workers by default to contain memory usage in dev environments
    celery --app=superset.tasks.celery_app:app worker -O fair -l INFO --concurrency=${CELERYD_CONCURRENCY:-2}
    ;;
  beat)
    echo "Starting Celery beat..."
    rm -f /tmp/celerybeat.pid
    celery --app=superset.tasks.celery_app:app beat --pidfile /tmp/celerybeat.pid -l INFO -s "${SUPERSET_HOME}"/celerybeat-schedule
    ;;
  app)
    echo "Starting web app (using development server)..."
    flask run -p 8088 --with-threads --reload --debugger --host=0.0.0.0
    ;;
  app-gunicorn)
    echo "Starting web app..."
    /usr/bin/run-server.sh
    ;;
  *)
    echo "Unknown Operation!!!"
    ;;
esac

**Comment by krisbarker** [comment]
Yes, I've just had the same problem.

**Comment by mistercrunch** [comment]
Can you try `compose -f docker-compose-image-tag.yml up --build` ?

**Comment by small-flowers** [comment]
> I have the same issue on different platforms. It seems that the `uv` command got added in some files, e.g. `docker/docker-boostrap.sh` however it is not present in the underlying superset container image.
> 
> Temporary workaround is to go back to a version previous to the commits of December, e.g. https://github.com/apache/superset/releases/tag/4.1.1
> 
> `git fetch --tags` if you cloned with `depth=1` and `git checkout 4.1.1` made my docker compose work again with the docker-compose-image-tag.yml file.
> 
> I still think there will be a patched base image soon.



> 你能嘗試嗎`compose -f docker-compose-image-tag.yml up --build`？
> 
> 我最近修改了文档，以指导人们使用`--build`。这有点类似于运行`docker compose build && docker compose up`

I used docker compose -f docker-compose-image-tag.yml up --build to execute, but the problem still persists. Please refer to the screenshot for the error message


> Can you try `compose -f docker-compose-image-tag.yml up --build` ?
> 
> I modified the docs recently to instruct people to use `--build`. It's kind of the same as running `docker compose build && docker compose up`

![image](https://github.com/user-attachments/assets/e67613c9-138e-420f-9ba4-0fdeab3f208d)

**Comment by javalram-ow** [comment]
A quick workaround is to modify the scripts which use `uv`. Substituting `uv pip` by just `pip` removes the errors. I did these modification in docker/docker-bootstrap.sh and docker/pip-install.sh and worked. As mentioned in the previous comments, the apache/superset image must be updated to include uv so it does not throw up this error when building.

**Comment by sfirke** [comment]
Users are reporting this has broken the quickstart https://superset.apache.org/docs/quickstart/#2-start-the-latest-official-release-of-superset. Requiring users to build an image doesn't seem appropriate for a quickstart.

I think the ideal fix would be to modify the docker-associated files that reference `uv` to work with the latest release `4.1.1`. That could be reverting or some kind of logic. It won't be necessary at the next major release but we shouldn't leave quickstart broken that long.

An immediate fix would be to add a note to the quickstart docs documenting this problem and pointing users to checkout the 4.1.1 tag and run from there as documented above by @maeddes https://github.com/apache/superset/issues/31510#issuecomment-2553351095.  I can submit a PR for this.

**Comment by mistercrunch** [comment]
Oh. Right. Didn't think this through. The bootstrap script uses `uv` and `uv` is not in older images. Also `--build` doesn't do anything to docker-compose-non-dev and the image-base one as we reuse old binaries there. Let me look into this and report back.

**Comment by mistercrunch** [comment]
This should help -> https://github.com/apache/superset/pull/31588

**Comment by mistercrunch** [comment]
I added a documentation note in https://github.com/apache/superset/pull/31588 which recommends (at least for now) checking out release tag you're trying to release prior to executing `docker-compose`.

A bit of a retro on this is when I altered the docker-compose process, I didn't know or think about the fact that we mount `docker/` on docker-compose-.*.yml, and use whatever is in the branch that's checked out against the image the user points to.

**Comment by small-flowers** [comment]
> I added a documentation note in #31588 which recommends (at least for now) checking out release tag you're trying to release prior to executing `docker-compose`.
> 
> A bit of a retro on this is when I altered the docker-compose process, I didn't know or think about the fact that we mount `docker/` on docker-compose-.*.yml, and use whatever is in the branch that's checked out against the image the user points to.

![image](https://github.com/user-attachments/assets/a9128faf-cdbd-4b71-863a-66f5d1df73b6)
I updated the code and the previous issue no longer exists, but there are new errors regarding UV, as shown in the screenshot

**Comment by luffy-taro** [comment]
Cloning master branch with `--depth=1`, it fails with the above error. Had to checkout `tags/6.0.0rc2`  for it to work. 

`tags/5.0.0` worked. 

Edit - Looks like the uv install step was timing out, and the error I was facing is unrelated.
