### ISSUE TITLE
Edit CSS Live can not @import google fonts?

### ISSUE THREAD

**Issue by psongyoo** [apache/superset#31597]
### Bug description

I try to @import google font in Edit CSS Live section. It not effect ???

@import url('https://fonts.googleapis.com/css2?family=Prompt:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
body{
  font-family:'Prompt';
}

### Superset version

4.1.1

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
You can, but dosubot is rigjt... you will have to punch a hole in TALISMAN_CONFIG for it.

**Comment by rusackas** [comment]
Closing this since it's not a bug, but a question that's now been answered. Holler if you have any further troubles with it :)
