### ISSUE TITLE
/app/superset/extensions/../migrations already exists and is not empty   

### ISSUE THREAD

**Issue by Varick-Wang** [apache/superset#31609]
### Bug description

docker image : apache/superset:latest
-=-=-=-=-=-=-=-=-=-=-
superset version: 4.1.1
-=-=-=-=-=-=-=-=-=-=-
How to solve the error '/app/superset/extensions/../migrations already exists and is not empty' when executing the command 'superset init' during software startup

### Superset version

4.1.1

### Python version

3.10

### Node version

16

### Browser

Chrome

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by Habeeb556** [comment]
I think you should run `superset db upgrade` before `superset init` to ensure it's up-to-date and no migration files are missed.

**Comment by Varick-Wang** [comment]
Yes, you're right.

First, execute 'superset db upgrade`
Then ` superset init `

thanks.
