### ISSUE TITLE
Apache Superset can't connect to Apache Druid

### ISSUE THREAD

**Issue by isiuni01** [apache/superset#31635]
### Bug description

I installed apache superset following the quickstart guide available in the [documentation](https://superset.apache.org/docs/quickstart), while trying to connect Apache druid (running in docker) I get:
`ERROR: (builtins.NoneType) None, I installed pydruid `

the guide to install apache druid on docker can be find here: [link](https://druid.apache.org/docs/latest/tutorials/docker/)

### Superset version

4.1.1

### Python version

3.10

### Node version

I don't know

### Browser

Chrome

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by isiuni01** [comment]
@dosu hi, this issue can be closed this issue i solved problem was 3 thx <3

**Comment by laxmikantbpandhare** [comment]
@isiuni01 what was the issue here? I am also on the same boat. I installed pydruid but still facing the issue.

**Comment by isiuni01** [comment]
Hi, my network configuration was wrong, this is mine: i added this at the end of file named ["docker-compose-image-tag.yml"](https://github.com/apache/superset/blob/master/docker-compose-image-tag.yml)

`networks:
  docker_bridge:
    external: true`

this is the network created by the apache druid yml file

let me know if that was the issue, thx
