### ISSUE TITLE
Chord popups contain wrong information

### ISSUE THREAD

**Issue by izetex** [apache/superset#3342]
### Superset version
Superset 0.19.0

### Expected results
When clicked on Chord diagram bean, it shows the correct flow from source to target

### Actual results
It shows just opposite numbers - from target to source

### Steps to reproduce

1) create a chord diagram, set source and target
2) click on diagram and notice that source and target in popup are switched places

I attach the source data and chord screen to show
![table1](https://user-images.githubusercontent.com/30741870/29489749-b6cb4bd4-8530-11e7-8157-4b754c738687.png)
![hord1](https://user-images.githubusercontent.com/30741870/29489750-b6ccb05a-8530-11e7-8d25-373414c3e855.png)

**Comment by monkevlar** [comment]
This is still an open issue imo. By reverting source and target metrics the problem persists. Could it be necessary to pre-format the data in any way?

**Comment by jonaschn** [comment]
This is still an issue in version: 4.0.2

**Comment by rusackas** [comment]
Reopening for now, pending further investigation.

**Comment by rusackas** [comment]
Closed! Thanks for the fix (even if I couldn't understand the diff at first) @jonaschn

**Comment by jonaschn** [comment]
Yes, sometimes the git diff highlights the wrong parts and is more confusing than helpful.
