### ISSUE TITLE
[Table config] Add SQL query editor functions in SQL Expression box

### ISSUE THREAD

**Issue by vylc** [apache/superset#5417]
Just killed myself trying to edit my SQL formula for a metric in the SQL expression box. Would be really helpful to have the syntax checking/linting/autocompletes of columns from the table - especially with end quotes and parentheses in this box.

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by IndexOutOfRange** [comment]
Not sure if this issue is still relevant as, in the sql editor, there are:

-  autocomplete on a lot of stuff 
- auto end quotes 
- auto closing parenthesis

and various others. Am I missing something ?

**Comment by mistercrunch** [comment]
I think this refers to the SQL Expression box(es), either in the "table editor" or the "metric editor" in the explore view.

**Comment by IndexOutOfRange** [comment]
Not sure if the original issue was about the the boxes in the new edit datasource react UI popup or the legacy edit datasources jinja form. 

The issue seems older than the creation of the react popup but i am unable to assess how frequently the legacy UI is still in use.

**Comment by junlincc** [comment]
@yousoph related to SQL Expression Validator component project

**Comment by betodealmeida** [comment]
Moved this to https://github.com/apache/superset/issues/12899
