### ISSUE TITLE
[SIP-8] Add UI component for user to select and persist category color from Dashboard

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#5887]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.27

### Expected results
- User can use a color picker to choose specific color for chart category.
- With or without define color for chart, each time we refresh dashboard should see same category with a same color.

### Actual results
![m2ojecxt59](https://user-images.githubusercontent.com/27990562/45508441-ac89ae80-b749-11e8-9e43-6c8a22029704.gif)

### Steps to reproduce
Refresh dashboard a few times.

### Design
<img width="1997" alt="screenshot_2018-09-10_17 46 58" src="https://user-images.githubusercontent.com/27990562/45508830-beb81c80-b74a-11e8-9594-d5a0789cd3ef.png">

### Implementation
- Reuse existed API to store category color in dashboard metadata
- refactory color assignment logic [#5815]
- Add color picker UI component (shown in design section) as part of dashboard builder control.

@williaster @elibrumbaugh @kristw @mistercrunch @michellethomas @john-bodley @betodealmeida @xtinec

**Comment by junlincc** [comment]
closing the SIP as we added the project to roadmap https://github.com/apache-superset/superset-roadmap/issues/110 

cc @mihir174 this project requires design
