### ISSUE TITLE
dist_bar row_limit doesn't work well with series and breakdown

### ISSUE THREAD

**Issue by michellethomas** [apache/superset#5904]
The distribution bar chart uses row limit that applies a limit to the end of a single query grouping by series and breakdown. Ideally there should be a limit on a subquery for the series groupby.

Here's an example using contribution, the results are limited to 10 rows so it looks like some states have all boys and 0 girls, showing incorrect data because it's getting truncated by the limit.
![image](https://user-images.githubusercontent.com/817955/45578359-e6d07a00-b835-11e8-9460-19861848c0f3.png)

When the fix is in, add a cypress test for the dist bar chart with series, breakdown, and limit 10.

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
master

### Expected results
The limit applies to the number of series results that show up, and the breakdown of that series shows up and does not get limited.

### Actual results
The limit applies to all rows returned series and breakdown

### Steps to reproduce
Create a dist bar with a series and breakdown and add a low row limit

**Comment by bkyryliuk** [comment]
looks like this is still an issue and the bar chart doesn't have a series limit. will reopen

**Comment by rusackas** [comment]
@bkyryliuk have you tried the ECharts bar chart with the `GENERIC_CHART_AXES` flag turned on? It seems to work splendidly in that situation, and when we default that flag to true soon, I'm hoping it kills this antique issue :)

**Comment by ninaviereckel** [comment]
This is still an issue I think (with both ECharts and legacy). I've checked the GENERIC_CHART_AXES flag, but it's already set to True and there is a comment showing it's deprecated, so I don't think this solved the problem.

See my screenshots (for ECharts bar chart). I have topics on my X-axis and sentiment labels as dimension. What I want is a total of 10 stacked bars that contain all sentiments of the breakdown dimension.

With row limit of 10000:
<img width="767" alt="Screenshot 2023-11-07 at 10 03 59" src="https://github.com/apache/superset/assets/31889312/c1500901-157e-4785-b488-5ee8fd46c5d0">

With row limit of 10:
<img width="770" alt="Screenshot 2023-11-07 at 10 04 17" src="https://github.com/apache/superset/assets/31889312/29e7dc3b-a23d-4287-b027-a8410f023b63">

**Comment by rusackas** [comment]
This issue has gone stale (again). I would believe we might indeed still have some issues with these limit controls in current Superset (3.x and newer, with echarts plugins), but we should file a new issue with updated context and a reproducible test case using example data. Closing this one since the plugin it was reported on no longer exists.
