### ISSUE TITLE
[SIP-9] Remove filter box from chart types and create a filter panel 

### ISSUE THREAD

**Issue by xtinec** [apache/superset#5925]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.27

### Expected results
This is the first of a series of SIPs for the redesign of scoped filters.

Filter exists as its own concept instead of a chart type. This should be reflected both in the code architecture and the UI itself. 

- Filter Box is removed from chart types
- New UI to create filters. Combine existing adhoc filters under the Query panel and the implicit filter under the Time panel as a uniformed filter creation UI (Mockups to come).
- [Stretch goal] use Typescript for new filter code

### Actual results
Filter box is a chart type.

### Steps to reproduce
Add a filter box to any existing chart.

**Comment by junlincc** [comment]
Closing in favor of https://github.com/apache/superset/issues/10285
