### ISSUE TITLE
Make line chart support non-temporal variable for x-axis

### ISSUE THREAD

**Issue by snehalkale41995** [apache/superset#6568]
The x-axis need not necessarily be a time/date, it could just be any number. Would be great to make that possible!

**Comment by davidhassan** [comment]
I like this idea as then I could display threshold lines.

**Comment by mlboy** [comment]
+1

**Comment by vylc** [comment]
@hughhhh

**Comment by Cyprien-Ricque** [comment]
Hello,
Is this feature implemented today ?

**Comment by EricLee0000** [comment]
@Cyprien-Ricque No it has not. It is quite annoying.

**Comment by fschlz** [comment]
please implement this

**Comment by sajidzaidi** [comment]
This would be an amazing feature

**Comment by anivon** [comment]
Yes, it's important to have the capability to do the same behavior than bar charts, with awesome lines 😍

**Comment by cateseale** [comment]
+1 for this. It feels like basic functionality is missing.

**Comment by junlincc** [comment]
reopening this issue to track progress.  we are committed get this feature in 2021, hopefully before Q3. 

@cateseale @anivon @sajidzaidi @fschlz @EricLee0000

**Comment by daniel10012** [comment]
@junlincc do you know where we are on this )

**Comment by diegoscarabelli** [comment]
I think the correct title of this feature should be: `scatter plot`

**Comment by DamienAllonsius** [comment]
Totally agree with @diegoscarabelli I would be very interested as well !

**Comment by rumbin** [comment]
I want to point out that this feature is closely related to #7172, since we'll often require to show unaggregated values on _both_ axes of the scatter plot.

An interesting question, of course, is whether there is also a need to show aggregated values on one or both axes and if so, how to define the group-by dimensions...

Furthermore, I want to emphasize that while it is commonly called scatter plot, the points may sometimes be required to be connected by straight or splined lines, while the points may be shown as markers or be hidden entirely.

**Comment by melnikovmaksimv** [comment]
Hi, im do plugin in PR https://github.com/apache-superset/superset-ui/pull/1214

**Comment by natarajant93** [comment]
@junlincc Do you know when we will get this enhancement?

**Comment by abstractor84** [comment]
This Line chart is very much needed for me, as we frequently create line charts like this, and this is a basic thing when using MS Excel, however in superset it's not supported. As of today, I export the data from superset to excel and create line charts (non-time series) in superset. This defeats the purpose of using superset as our BI-Viz tool.

Here is a sample chart which i created in Excel;

![image](https://user-images.githubusercontent.com/89123291/146027756-298b6211-13d8-4938-8c8e-ff323b2ef555.png)

Sample Data:
![image](https://user-images.githubusercontent.com/89123291/146027985-c889c27e-7179-4957-9dcf-81e52c8ca951.png)

**Comment by shimenglowery** [comment]
Do we have any updates regarding this feature? also need this feature and seems it has been a pain point for many people. Could we get a timeline for this one? thank you!

**Comment by villebro** [comment]
A PR that will add this functionality will be opened within the next few days, stay tuned. However, this will be behind a feature flag until the functionality is stabilized. So keep in mind it will be considered an experimental feature for at least a few months.

**Comment by bayesfactor** [comment]
+1, very interested in this feature

**Comment by cpaoletti** [comment]
+1 on needing this feature

**Comment by abstractor84** [comment]
Thanks @villebro for adding this feature. 💹

**Comment by isegura-eos-eng** [comment]
Thanks @villebro !

**Comment by DhruvaPatil98** [comment]
@villebro Thanks for adding the feature! Is there any way we could use this with 1.4.1 release?

**Comment by arojas314** [comment]
@villebro We are running Superset through a python environment, and we changed the config.py file as per your feature plugin directions. This did not work as I did not see the ECharts time-series charts without the prefix (e.g. line chart, etc.)
Any suggestions?

Thanks for you work.

**Comment by jmorgan-wellovate** [comment]
Definitely need this feature!

**Comment by YayaDaxter** [comment]
Hello,
Is this feature implemented today ?

**Comment by zehraylm** [comment]
Hi,
Is this feature implemented today ?
