### ISSUE TITLE
Stateless Authentication which relies on only Bearer token?

### ISSUE THREAD

**Issue by dbsheta** [apache/superset#6747]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

Currently, Superset uses session-based authentication where the cookie is sent with each request. Can we have stateless authentication i.e the backend will not store any session and will rely on access-token sent in Header by the client? eg. Header: ```Authorization: Bearer eerkjerkcwk.....```

**Comment by brentEich** [comment]
@dbsheta @kristw Have you had any success with this? I'm also looking to implement something of this nature.

**Comment by syazwan0913** [comment]
@dbsheta You got any update on this?

**Comment by nishantmonu51** [comment]
any updates here ? Is anyone working on this ?

**Comment by willbarrett** [comment]
@dbsheta the recommended path forward here is for users to implement their own custom Security Manager to support the requested functionality. Please see the documentation on [Security in Superset](https://superset.incubator.apache.org/security.html) and [Security in Flask App Builder](https://flask-appbuilder.readthedocs.io/en/latest/security.html) as well as [Superset's security manager class](https://github.com/apache/incubator-superset/blob/master/superset/security/manager.py)
