### ISSUE TITLE
[SIP] Proposal for Implemention of dynamic theme in superset

### ISSUE THREAD

**Issue by rasmi-ranjan-guavus** [apache/superset#6929]
**Motivation**:

Supporting dynamic theme in superset will provide end-user to use his/her choice of theme on the go.

**Proposed Change**:

1> Provide option to change theme from UI. 
2> Support of multiple themes
3> Separate theme-able style from other styles (position, size etc) 
4> use scss/less mixin to change theme dynamically

this is how the style for any component will look like:

`.btn-primary {
  width: 200px;
  Padding: 2px;
  position: relative;

}

@mixin btn-primary-theme($theme) {

.btn-primary {

color: get-color($theme, primary);
background-colour: get-color($theme, background);
font-size: font-size($theme, button);
}

}
`

**New or Changed Public Interfaces**:

- if we use SCSS
      mixin the we need sass-loader (MIT license)
       Enable scss  style pre-processor  in superset.

- If we use less. 
    Since Less is already supported in superset, don't need any change

**Migration Plan and Compatibility**

for backward compatibility existing styles will be available. 
To use theme user need to use new styles

**Comment by rasmi-ranjan-guavus** [comment]
@mistercrunch any thought on this?

**Comment by gbrian** [comment]
@rasmi-ranjan-guavus @mistercrunch MVP proposal using existing CSS Templates:
https://github.com/gbrian/incubator-superset/pull/2

**Comment by gbrian** [comment]
@mistercrunch, sorry can't find the issue where you posted about how to customize look and feel.

We are evaluating Superset as an analytics platform for our customers so will need to customize for each of them. Thinking on some sort of Multitenancy so look&feel should be defined at "role" level..

BTW What's the difference/relation between: basic.html, base.html, baselayout.html ?

Thanks

**Comment by rusackas** [comment]
Tempted to close this in favor of https://github.com/apache/incubator-superset/issues/9123

The theme from `superset-ui` used by Emotion in an increasing number of places, is the current inroads to this goal. Over time, there will be less LESS (heh) and more styles using this dynamic theme, which can be overridden or extended in the <ThemeProvider> components in use.

Any objections to closing this one @rasmi-ranjan-guavus ?

**Comment by rusackas** [comment]
This is already being tackled with Emotion, and theming projects for AntD/ECharts/etc. Closing this since it's already WIP.

**Comment by rusackas** [comment]
Since this issue is closed, we'll also consider the SIP/proposal process closed as well. If you want to rekindle this proposal, please re-open this Issue, and send a new [DISCUSS] thread to the dev@ mailing list. Thank you!
