### ISSUE TITLE
Jinja templating is ignored in Metrics definitions

### ISSUE THREAD

**Issue by rmacnguyen** [apache/superset#6983]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.29.0rc7 (latest on pypi)

### Expected results
Not sure if this is intentional, but it seems like Jinja templating used when defining metrics using custom SQL should be parsed and rendered similarly to how it works when defining filters.

### Actual results
Jinja templating in metrics is effectively ignored and sent to the query engine as is.

### Steps to reproduce
Add a metric to a chart that includes Jinja templating. For example, define a metric as `max('{{ from_dttm }}')`. The rendered SQL shows that the templating is ignored.

**Comment by questplatform** [comment]
Has this been looked into @junlincc?

**Comment by mistercrunch** [comment]
Confirming this is still an issue, reopening & pinning

**Comment by guydou** [comment]
This is how I solved it in my use-case https://github.com/apache/superset/pull/15502
