### ISSUE TITLE
[Design Proposal] New Dashboard Creation flow

### ISSUE THREAD

**Issue by dorq** [apache/superset#6997]
This is a proposal for multiple changes to the current dashboard creation flow.  Please share any concerns or comments directly in this issue.

## How to access the new dashboard flow
We recently added a universal “New” button to the Superset navigation bar:

![image](https://user-images.githubusercontent.com/2992086/53995953-9b639e00-40eb-11e9-8c95-4aa63d10975d.png)

This “New” button is available from every page in Superset.  Users enter the flow proposed here by selecting the “New… Dashboard” option.

### If the user doesn’t yet have any of their own charts...

If the user doesn’t yet have any of their own charts, this is what they will see:

![dashboard entry point - new user no charts](https://user-images.githubusercontent.com/2992086/53996769-98b67800-40ee-11e9-88c2-0568d113ad08.png)

Note these changes from the current experience:

- Opening directly into this editor shortcuts the current multi-stage process to get to this point, including a placeholder title.
- Sidebar + toolbar at left of the window rather than the right. We're suggesting to move it to the left for two main reasons:
    1) The Chart and SQL editors use side panels on the left, so this makes all the flows consistent.
    2) New users often don't know what to do, so this new design puts the key actions at the top left of the window where users are more likely to see them.
- What was previously under “Your charts and filters” is expanded to take up the whole sidebar
- Structural tools like tabs, rows, dividers are now contained in a vertical toolbar.  Tooltips will show the associated action (e.g., “Drag to insert tabs”)
- New textual cue on the blank canvas: “Create a chart to place it on the canvas”
- There is a new button to create a new chart.  This “Create new chart” button takes the user to the chart creation flow as described [here](https://github.com/apache/incubator-superset/issues/6996) in a new tab.  This button is sticky at the top of the panel.  Note: If possible, the tabs should communicate so that once the chart is created it shows in the dashboard automatically.

### If the user has already created at least one chart...

If the user has already created at least one chart, this is what they will see:

![dashboard entry point - existing charts](https://user-images.githubusercontent.com/2992086/53996819-c7345300-40ee-11e9-9081-2667486542f7.png)

In addition to the sidebar and toolbar changes mentioned above, note these changes from the current experience:
- Users can preview their charts with thumbnails. This is an optional feature: including a choice to enable/disable it; disabled should be default state.
- New textual cue on the blank canvas: “Drag and drop items here”

### If the user edits an existing dashboard...

If the user edits an existing dashboard, this is what they will see:

![dashboard entry point - existing dashboard](https://user-images.githubusercontent.com/2992086/53996974-52ade400-40ef-11e9-8474-eb2a68629dd6.png)

This is the same as the current editing experience except for the sidebar and toolbar changes mentioned above.

## How to move forward

Lyft is proposing these changes as a result of research and many iterations with multiple teams.  Airbnb (cc @elibrumbaugh) will further iterate if needed, but at the time of this proposal, the general consensus is that this is an improvement on the current UX for dashboard creation, so we would like to enable development of this ASAP.

**Comment by graceguo-supercat** [comment]
Hi @dorq Thanks for the proposal, I like it. Here is my input from engineering point of view:

- `We add Sort and Filter capabilities at the top of this list (sticky at top of panel).` 
Current dashboard editor had sort and filter capabilities for the chart lists, right? is there any difference from current feature?

- I noticed there is a preview in the chart list, which is not available in the current dashboard. We didn't implement mostly from performance concerns. When user open edit mode, the chart list shows all the charts that owned by the user, for airbnb users it may a few hundred items, and each chart is a query (sometimes may be cached data) to backend. So when to send query, send how many queries, how to handle user scrolling in the chart list, etc., to implementation these need a lot of intelligence.  Otherwise user will get stuck waiting for query running and chart render, and the editing dashboard could become unusable.  

If you decided to implement this chart preview, please offer a choice to disable it, and disable should be default state, so that user won't get stuck when we release the new version. If user really want to see chart preview, they can manually enable it.

**Comment by dorq** [comment]
> Current dashboard editor had sort and filter capabilities for the chart lists, right? is there any difference from current feature?

You're exactly right.  I mistakenly noted this as an update while we already have these features.  I've updated the description.

>If you decided to implement this chart preview, please offer a choice to enable/disable it, and disabled should be default state, so that user won't get stuck when we release the new version. If user really want to see chart preview, they can manually enable it.

Also agree with this point.  I've updated this one as well.

Please let me know what you think of the edits!  Thanks for your thoughtful response.

**Comment by elibrumbaugh** [comment]
**Thanks again for sharing this proposal Anita!**

- The create new chart button is outlined while the new button is filled. We should align on a single style for primary actions. In this context create new chart is certainly a primary action. Using the filled style will also help improve discoverability.
- Love the rationale behind moving the panel to the left.
- Re: the name of the dashboard on creation is there a way to make it more human readable? Remove underscore? Also the uppercase U here is at contrast with the lowercase chart placeholder title text.
- I'm on board with removing the charts out of their own tab and bringing them to the forefront. A few things we should consider here is 1. Setting expectations about where the new chart will appear. This could be help text underneath the + Create New Chart button. 
- The way the existing panel improved discoverability of the different components the user could apply to their dashboard was by writing out the entire title. We dual encoded title with icon. To solve for this here would be to write the name of the component under the icon in small text and/or hover tips like you mentioned. It would be cool if we explained purpose of the component as well.
- This structural cue as you called it works better than the button looking style on the create new chart flow. Could we align them?
- Sort by and search/filter your charts looks better here than in create new chart. Seeing the outlined inputs for sort by and search makes me think the create new chart button should be filled to improve the hierarchy.
- Love the thumbnails! Nice considerations for disable as optional.
- Today when I edit a dashboard there is visual context for what charts have and have not been applied. How will this be handled?

Thanks!

**Comment by junlincc** [comment]
We will consider both dashboard and chart creation flow post 1.0. added item to roadmap inbox. https://github.com/apache-superset/superset-roadmap/projects/1

**Comment by rusackas** [comment]
I think we can close this proposal for now after an extended period of inactivity. Some of this is potentially being addressed in forthcoming proposals from @kasiazjc and @jess-dillard
