### ISSUE TITLE
Forced Directed graph is cut off and returns [object Object] after resize

### ISSUE THREAD

**Issue by khtruong** [apache/superset#7246]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar. (There is a similar issue https://github.com/apache/incubator-superset/issues/6525 that has been closed)

### Superset version
Master

### Expected results
To view the entire force directed graph and for it to continue to display after resize

### Actual results
<img width="1035" alt="Screen Shot 2019-04-08 at 4 10 48 PM" src="https://user-images.githubusercontent.com/47833996/55762743-fe14c600-5a18-11e9-9e56-5eaafc0e6359.png">

After resizing:
<img width="955" alt="Screen Shot 2019-04-08 at 4 11 02 PM" src="https://user-images.githubusercontent.com/47833996/55762752-040aa700-5a19-11e9-839a-27e5085724aa.png">

### Steps to reproduce
1. Open sample force-directed graph Energy Force Layout
2. Resize window

**Comment by zyxue** [comment]
Any update on this? Also a question, is force-directed graph zoomable?

**Comment by IndexOutOfRange** [comment]
Simple solution is to resize window and re run the query after that. This way the graph is recreated and may fit in the box. This is more of a work around though...
![force_directed_graph](https://user-images.githubusercontent.com/3482221/75189140-d96b2f00-574d-11ea-9fac-77d98c0ed13d.png)

**Comment by srinify** [comment]
Hey @zyxue @IndexOutOfRange did y'all see the new ECharts Force Directed Graph?

- Video: https://www.youtube.com/watch?v=7HkkVIYxr_I
- Release Notes for 1.1 that mention it (currently being voted on): https://github.com/apache/superset/tree/master/RELEASING/release-notes-1-1
