### ISSUE TITLE
Spreadsheet, or Google Sheets, data source

### ISSUE THREAD

**Issue by brylie** [apache/superset#7565]
We have internal stakeholders who regularly work with data in spreadsheets. We would like to make it simple for them to get spreadsheet data into the data portal. 

Since our staff use Google Sheets (and Drive), it would make sense that they could upload the data spreadsheets to google Drive and then connect them to Superset for dashboarding.

Alternatively, they could upload the spreadsheet to Superset, via the UI.

**Comment by francishemingway** [comment]
Hi Brylie,

This may be of interest to you:
https://github.com/apache/incubator-superset/pull/5915
Francis

**Comment by mistercrunch** [comment]
This works well, though it's hard to get it to work with non publicly shared google sheets. I'm pretty sure it's doable though.

**Comment by brylie** [comment]
By way of example, Redash accesses Google Sheets that are shared to a specific "email"

https://redash.io/help/data-sources/querying/google-spreadsheet

**Comment by brylie** [comment]
I think the @stale bot is a bit misguided. I understand it is important to groom the issues, but this feature may be a while in the works.

**Comment by jaksmid** [comment]
@mistercrunch How do you make it work with non public sheets? 
https://github.com/betodealmeida/gsheets-db-api mentions generated json file but it is not clear to me how would you inject that the sqlalchemy connection in superset without modifying the source code. Thanks!

**Comment by brylie** [comment]
Is it possible to flag issues, so the stale bot doesn't close them? I.e. this feature request seems important, particularly the need for private sheets.

**Comment by mistercrunch** [comment]
@brylie pinned it so it won't get closed

It'd be great to have a blog post walking people step by step.  The short story is something like:
* `pip install gsheetsdb`
* `pip install gsheetsdb[sqlalchemy]`
* create a database connection in Superset with the sqlalachemy url `gsheets://`
* add a "table" by using the url of the spreadsheet as the table name
* you can also in SQL Lab go `SELECT * FROM "{spreadsheet_url}"`

**Comment by hemantaggarwal** [comment]
@mistercrunch :
I tried it after installing gsheetsdb, I am getting error ".NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:gsheets"

**Comment by redko-o** [comment]
@hemantaggarwal 
Did you make correct URI for gsheets?

**Comment by mistercrunch** [comment]
Full URI is `gsheets://`. There is a way to work with private sheets, and to see "public within my org" in GSuite, but it's fairly tricky. @betodealmeida can probably provide pointers. We kind of owe the world a blog post on this whole topic.

**Comment by hemantaggarwal** [comment]
@redko-o : What mistercrunch told is the full URI which works for public sheets but I am unable to find a way to connect private google sheets with Superset. 
@mistercrunch : I figured the URI after few trials and this feature of linking public gsheets is really amazing but my use case is to connect private gsheets inside organization. 
I didn't know there is way to work with private sheets although I tried to Presto as intermediate to connect gsheets and Superset but that also didn't workout completely.  
@betodealmeida Can you please tell us all how to work with organization's google sheet in Superset? It will be a great help.

**Comment by redko-o** [comment]
@hemantaggarwal, @mistercrunch thanks for the hints!
Also, find an example of connecting BigQuery to the Superset (https://superset.incubator.apache.org/installation.html#google-bigquery). They use Google Service Account to do that adding JSON configuration to the Database extras. Probably, It can be the way of gsheets can work :)

**Comment by hemantaggarwal** [comment]
@redko-o 
I also went through this but it didn't work out for me as my organization don't use Big Query. Due to this we tried using Presto as it also uses google service account but google service account is consider as external account inside gsuite domain even if it is created through organization ID, hence cannot use it with private gsheets.

**Comment by anshuman73** [comment]
@hemantaggarwal I think one way might be to give access to that particular service account email ID. I think Redash does something similar.

**Comment by anshuman73** [comment]
Also, sorry if I'm misunderstanding, but was a final way found to connect superset to public Gsheets in an org?

I went through [this](https://github.com/betodealmeida/gsheets-db-api#authentication), but couldn't get how to do this in Superset itself.

**Comment by hemantaggarwal** [comment]
@anshuman73 : Public gsheets are easy to connect like  mentioned above, only issue is with private gsheets. 
If you have organization specific domain then it will treat service account also as outside organization id and hence can't share with it.

**Comment by anshuman73** [comment]
@hemantaggarwal Ahh, okay. Thanks for the clarity

**Comment by ispulkit** [comment]
Can you explain a bit about the workaround for private and org-based gSheets?

**Comment by cmenzelqlp** [comment]
Any update on the workaround for private gSheets?

**Comment by betodealmeida** [comment]
For org-based sheets:

1. Create a service account.
2. Enable domain-wide delegation on the account.
3. Download the key as JSON.
4. Add "client name" to "Manage OAuth clients", with the scope “https://spreadsheets.google.com/feeds”.
5. In the DB configuration add the JSON payload to a key called `service_account_info` under `engine_params`.
6. Alternatively, add a key called `service_account_file` under `engine_params` pointing to the location of the JSON file.

An example:

```json
{
  "metadata_params": {},
  "engine_params": {
    "subject": "roberto@dealmeida.net",
    "service_account_file": "/path/to/file.json",
    "service_account_info": {
      "type": "service_account",
      "project_id": "gsheetsdb",
      "private_key_id": "XXX",
      "private_key": "-----BEGIN PRIVATE KEY-----\nXXX\n-----END PRIVATE KEY-----\n",
      "client_email": "shillelagh@gsheetsdb.iam.gserviceaccount.com",
      "client_id": "109948634192943148536",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/shillelagh%40gsheetsdb.iam.gserviceaccount.com"
    }
  },
  "metadata_cache_timeout": {},
  "schemas_allowed_for_csv_upload": []
}
```

You can also define a `DB_CONNECTION_MUTATOR` to add the credentials and `subject` for each request ("subject" should be the org email for the logged user).
