### ISSUE TITLE
deck.gl Screen Grid doesn't display colour selector

### ISSUE THREAD

**Issue by fzzylogic** [apache/superset#8022]
For current master branch (2019-08-10):

"deck.gl Screen Grid" doesn't display colour selector or grid size. "Switching to deck.gl Grid" shows the colour selector and grid size and setting the colour there, affects the colour displayed when switching back to deck.gl Screen Grid.

### Expected results

Colour selector and grid size controls should display on deck.gl Screen Grid, not just Grid. Not sure if colour selector is supposed to display on Grid, as it doesn't seem to work for Grid.

### Actual results

As described above.

#### How to reproduce the bug

1. Make a new chart of type deck.gl Screen Grid.
2. See error

### Environment

(please complete the following information):

- superset version: `0.999.0dev` as shown in packages.json
- python version: `3.7.2`
- node.js version: `v12.8.0`
- npm version: `6.10.3`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Loving Superset ^^

**Comment by fzzylogic** [comment]
@stale It's only stale if it's been fixed ^^

**Comment by fzzylogic** [comment]
@Stale It's only stale if it's been fixed ^^

**Comment by mistercrunch** [comment]
Do you not see it under the "Customize" tab?
<img width="1168" alt="Screen Shot 2019-12-09 at 10 28 12 PM" src="https://user-images.githubusercontent.com/487433/70501558-36eaca80-1ad3-11ea-9664-fc85aa64b9f3.png">

**Comment by fzzylogic** [comment]
@mistercrunch I got Screen Grid and Grid confused sorry for the mixup. Screen Grid works correctly. At https://demo.superset.cloud/chart/list/ open 'Grid' and expand 'Map'. It has 'Fixed Color' in there too. Adjusting it makes no difference to Grid, but if one subsequently switches 'Visualisation Type' to 'Deck.gl - Screen Grid', the color will have been set there. Thanks.

**Comment by fzzylogic** [comment]
@Stale It's only stale if it's been fixed ^^

**Comment by fzzylogic** [comment]
@Stale It's only stale if it's been fixed ^^

**Comment by fzzylogic** [comment]
'Fixed color' still appears in two places: 1) Deck.gl Grid under the Map accordion and 2) Deck.gl Screen Grid in the Visual properties tab. Changing it under Grid has no effect on the map. Switching visualization type to Screen Grid, shows whatever color was selected under Grid and the color is shown on the map. Superset is fantastic btw.

**Comment by fzzylogic** [comment]
@mistercrunch Screenshots may help.

![grid_colour_change_does_not_work](https://user-images.githubusercontent.com/8237722/84494425-72fe2280-ace4-11ea-9d02-35a08dfbd233.png)

![screen_grid_colour_change_works](https://user-images.githubusercontent.com/8237722/84494459-814c3e80-ace4-11ea-8714-65cab5d60eed.png)

**Comment by fzzylogic** [comment]
https://demo.superset.cloud/chart/list/ open 'Grid' and expand 'Map' -> fixed colour still present, see screenshots above.

**Comment by junlincc** [comment]
@fzzylogic looks like you are on a very old version... i doubt it has been fixed in master but please try..unlikely we will push a fix for deck.gl chart, but if you can open a PR, we will help get it through:)

**Comment by fzzylogic** [comment]
@junlincc Thanks for the reply! This is not a big issue, just kept answering stale bot because it's still a thing. Fwiw, the screenshots are from the [online demo](https://demo.superset.cloud/chart/list/), not sure what version it is. On the demo site, open "deck.gl Demo". Then for the "Grid", click the ellipsis to the right and "Explore chart". As in the screenshot, under the "Map" section, there is a "Fixed Color" option. Changing it has no effect. That's all, thanks ^^.
