### ISSUE TITLE
PUT requests to /tablecolumninlineview/api/update/<id> fail

### ISSUE THREAD

**Issue by etr2460** [apache/superset#8167]
Making a PUT request to the tablecolumninlineview api fails when not all required fields on the model are provided.

### Expected results

Expect a 200 when providing a payload of `{"description": description}`.

### Actual results

Get a 500
`{"error_details":{"column_name":["This field is required."]},"message":"Validation error","severity":"warning"}`

#### How to reproduce the bug

1. Create a dimension in superset
2. Hit the API to change the dimension description
3. Get an error

Note that when I include the `column_name` field, this doesn't fail. It seems like there's an issue with merging the payload with the existing object, perhaps with the model or in FAB. I would expect to not need the `column_name` field when making a PUT request if it already exists on the existing object

### Environment

Repros on superset master, up to date versions of python and js

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

cc @john-bodley @dpgaspar

**Comment by etr2460** [comment]
@dpgaspar do you have any thoughts here?

**Comment by zengqinchris** [comment]
导出 superset的看板的 API 是什么  有没有人知道  export_dashboards
