### ISSUE TITLE
Deck GL Screengrid overlay does not update

### ISSUE THREAD

**Issue by micimize** [apache/superset#8230]
Probably root cause of #5470 - The deck gl screengrid overlay displays the same values for the same locations no matter how you pan and zoom the map

### Expected results
Popup data corresponds to underlying map data

### Actual results
The map renders with the popups misaligned (seems like largest point is in the upper left) and the overlays don't change

#### Screenshots
<img width="940" alt="Screen Shot 2019-09-16 at 12 23 05" src="https://user-images.githubusercontent.com/8343799/64979291-094c0780-d87d-11e9-905e-f1df208fb823.png">

With the following **Javascript tooltip generator** we can illustrate the problem:
`(o) => console.log(o) || JSON.stringify([o.object.position, o.lngLat]);`

<img width="481" alt="Screen Shot 2019-09-16 at 12 17 13" src="https://user-images.githubusercontent.com/8343799/64979007-63000200-d87c-11e9-8c19-e405e21783d1.png">
<img width="473" alt="Screen Shot 2019-09-16 at 12 17 40" src="https://user-images.githubusercontent.com/8343799/64979008-63000200-d87c-11e9-8592-ffea250813c4.png">

#### How to reproduce the bug

1. Create a screengrid visualization
2. Pan and zoom the map

### Environment

(please complete the following information):
- the [`amancevice/superset:edge`](https://hub.docker.com/layers/amancevice/superset/edge/images/sha256-a6ba4bac37c80366c910284a93c6e37bd476c2c61f7bf2aae861ba410d7c79aa) container
- superset version: `Superset 0.999.0dev` (post `0.34.0`)
- python version: `Python 3.6.9`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar (there are, but they were stale-botted

**Comment by micimize** [comment]
worth noting that I've observed this behavior on versions as early as `0.28`. [This deck.gl](https://github.com/uber/deck.gl/issues/1880) issue is possibly related

**Comment by aboganas** [comment]
Also on Screen Grid Play no longer works

**Comment by micimize** [comment]
This should be `.pinned`

**Comment by rusackas** [comment]
Closing this since not because it's resolved, but because it hasn't been commented on in 3 years, and references an long-unsupported version of Superset. If this still exists as an issue and needs triage, let's open a new issue! Thanks to all involved.
