### ISSUE TITLE
Right "schema access on [my_pg_instance].[my_schema]" of uploaded "CSV to Database" table does not appear in Rights list of roles (PostgreSQL)

### ISSUE THREAD

**Issue by sfkeller** [apache/superset#8690]
### Expected results

When importing a CSV e.g. to PostgreSQL database (e.g. "my_pg_instance") through menu item "CSV to Database" (path /csvtodatabaseview/form/ ); and when indicating a schema "my_schema" in field "Schema" (=>"Specify a schema ..."). Then when opening menu item "List Roles" (path /roles/list/) the right "schema access on [my_pg_instance].[my_schema]" should appear.

### Actual results

What actually happens is, that the newly created schema (e.g. "my_schema") does _not_ appear when trying to assign this schema to another role when editing a role in "List Roles" .

#### How to reproduce the bug

1. Go to menu "CSV to Database", select a PostgreSQL instance with CSV upload enabled.
2. Click on field 'Schema' and enter schema "my_schema"
3. Go to menu "List Roles", edit a role and try to add "schema access on [my_pg_instance].[my_schema]".
4. "schema access on [my_pg_instance].[my_schema]" does not appear.

Issue is, that the user who just uploaded a CSV into a table can't handle rights on this table.

### Environment

- superset version: `0.34` 
- python version: `3.7` 
- node.js version: `N/A`
- npm version: `N/A`

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

We're struggling with a Superset Cloud Instance which is multi-tenant, i.e. where "producers" (roles) only see and share own databases, schemas, charts and dashboards with their "consumers" (roles).

**Comment by sfkeller** [comment]
Pls. pin this issue. It doesn't make much sense to label a bug as stale.

**Comment by willbarrett** [comment]
@rusackas @craig-rueda can you pin this?

**Comment by graceguo-supercat** [comment]
close this issue since no recent follow up.
