### ISSUE TITLE
Toggle to NOT render HTML on Table viz

### ISSUE THREAD

**Issue by rubypollev** [apache/superset#8776]
**Is your feature request related to a problem? Please describe.**
Sometimes I'm querying data with URL params. I always get people injecting SQL or HTML in here. Not usually a problem, but the Table viz is rendering this HTML. This is a security concern. 

**Describe the solution you'd like**
I'd like to toggle this ON on a case-by-case basis in the "customize" tab. Might need a config flag for default behaviour, too. 

**Describe alternatives you've considered**
Maybe a feature flag to turn this off for the whole implementation?

**Comment by nytai** [comment]
@rubypollev looks that's a bug in the table implementation. Looking at the logic: https://github.com/apache-superset/superset-ui-plugins/blob/master/packages/superset-ui-legacy-plugin-chart-table/src/Table.js#L154 it seems like the intent is for all content to be DOM/HTML escaped, however it seems like it's only applying it to string columns. 

When you've experienced the issue, have people been injecting SQL and HTML in non-string fields?

**Comment by rubypollev** [comment]
@nytai I've only experience this with string fields. I see that string fields are sanitized, so this is less of a security issue than I thought it was. I'd still like an option to render string fields as... strings and not HTML.

**Comment by nytai** [comment]
yep, looking at https://github.com/cure53/DOMPurify it seems that the content is sanitized and not escaped. 

I wonder if there's a strong case for rendering the strings as HTML in the table. Seems to be like it should default to rendering strings and render HTML based on some config (if there's a strong case for doing so -- I can't think of any right now).

**Comment by mistercrunch** [comment]
There are lots of use cases for allowing links in tables. You might want a "leaderboard" type chart that links out to pages to individual entities, or a list of "support tickets" that links to the ticketing system.

We've also used this feature to link to other dashboards with a preselected filter, meaning clicking on a specific country entity in a data table could open some sort of country scorecard, ...

Do we think there could be a security concern outside of a type string?

**Comment by mistercrunch** [comment]
Side note, I'm not sure if I like this `<span class="like-pre">` wrapping, seems like it could add a lot (tens of thousands) of not super necessary dom elements just to `white-space: pre-wrap;`. We could probably just do that on `table.dataframe td` instead.

**Comment by andro42** [comment]
Hi, I also have a problem with Column being rendered as html. This is not wanted. I want to display text from database, without being rendered as html. In my case, there is text "...<some.email@domain.com>..." in my column, which then disappears in table chart. How can I disable htlm rendering (for this column, or for this chart, or for whole application)? Using docker and superset version "x-superset-image: &superset-image apache/superset:${TAG:-latest-dev}" at the time of this posting, which shows "About Version: 0.0.0-dev"

**Comment by osmangone57** [comment]
SELECT '<span style="color:blue;">Test</span>' AS test_output; use in superset
