### ISSUE TITLE
Ability to parameterize and embed dashboards or charts into external web applications

### ISSUE THREAD

**Issue by denkab** [apache/superset#8924]
**Is your feature request related to a problem? Please describe.**
There is an existing application where addition of charts or dashboards managed in external tools (like Kibana and Tableau) is an established practice.

**Describe the solution you'd like**
I wish to be able to embed (worst case, as an iframe, but ideally, by somehow proxying content of the charts) to make those an inseparable part of another application. This would be beneficial from at least 2 perspectives: convenience and access control. This way, by parameterizing (or pre-selecting filters, either hidden or available in the slice-and-dashboard UI), users can land in an experience that is contextualized to their domain/area, but also, it can be hoped that data belonging to areas that aren't "theirs" can be concealed.

**Describe alternatives you've considered**
IDK, really... Forgoing the superset's UI altogether and interacting with backend does not seem too appealing.

**Additional context**
Nothing else to think of at the moment.

**Comment by amitmiran137** [comment]
This is address in embeddable dashboard work by @suddjian
