### ISSUE TITLE
Users can query bigquery datasets without permissions

### ISSUE THREAD

**Issue by micimize** [apache/superset#9182]
Once a user has permissions to any bigquery dataset, they can query any other dataset superset has access to, just by using the dataset prefix. This is probably because the bigquery client jobs have no dataset restrictions https://github.com/googleapis/google-cloud-python/issues/6042

**Comment by willbarrett** [comment]
As mentioned in the linked ticket, the current correct behavior is to manage access at the Google Cloud API layer. The client library is not able to make restrictions like the one described in this ticket, thus Superset is similarly limited. Thank you for bringing this to our attention.

**Comment by micimize** [comment]
This should probably be `.pinned`

**Comment by micimize** [comment]
The referenced `python-bigquery` issue was closed in favor of [adding conditional IAM support to bigquery](https://issuetracker.google.com/issues/143959429). Once/if that is done, I think superset could add a field to the request with a list of authenticated datasets and have a recommended IAM policy to set.

**Comment by graceguo-supercat** [comment]
close this since no recent follow-up.
