### ISSUE TITLE
Treemap splits labels on `.`

### ISSUE THREAD

**Issue by serenajiang** [apache/superset#9354]
In the treemap viz, labels are split on `.`, and the last "word" is used for the viz.

### Expected results

For the label `google.com`, the label should read `google.com`

### Actual results
![image](https://user-images.githubusercontent.com/14146019/77365155-dc3c4e00-6d12-11ea-9f03-b19ffa12760b.png) 🤔 

#### How to reproduce the bug

1. `SELECT 'google.com' AS col_a` in sqllab
2. Explore chart
3. Create a treemap viz with metric `COUNT`, grouped by `col_a`
4. Run Query

### Environment

(please complete the following information):

- superset version: `superset version`: Up to date with master as of 2020-03-18
- python version: `python --version`: 3.6
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mistercrunch** [comment]
For whoever wants to work on this, here's a pointer to the source:
https://github.com/apache-superset/superset-ui/blob/master/plugins/legacy-plugin-chart-treemap/src/Treemap.js#L135-L158

**Comment by rusackas** [comment]
Closing this issue as stale, since the Legacy Treemap is effectively being replaced by the Treemap (Echarts) plugin, which does not exhibit this issue.
