### ISSUE TITLE
SQL QUERY PROBLEM

### ISSUE THREAD

**Issue by YanXinLiu** [apache/superset#9361]
### connected hive database,when I execute sql,I got this
![1585043136(1)](https://user-images.githubusercontent.com/35486255/77411385-50e8b880-6df7-11ea-9c58-f4e3520cf6b2.jpg)
---
```
some execute work well ,but others can't work.
I can't stop this query,and can't close all these tabs.but when I use mysql,everything seems be ok.
how could I solve this and close all these process? 
Thanks
```

**Comment by john-bodley** [comment]
There has been a lot of changes in SQL Lab over the past 12 months or so. I'm closing this issue for now (in part due to lack of  context) but please create a new issue (choose the `Bug report` option) if you're still running into this.
