### ISSUE TITLE
Chosen colors not reflected in Deck.GL grid

### ISSUE THREAD

**Issue by Sumit12594** [apache/superset#9697]
When we try to set the color of extruded bar, the color reflected on the map is not the same as we set. It shows red and orange only.

### Expected results
I want the color that I set, to be reflected in the map.

### Actual results
![GITquestion](https://user-images.githubusercontent.com/36192149/80674751-63c66b00-8ad0-11ea-9797-6395d33ec10a.PNG)

![Gitquestionmap](https://user-images.githubusercontent.com/36192149/80674754-66c15b80-8ad0-11ea-9559-a63b1c060c8c.PNG)

Like you see in the screenshot, I have set the fixed color to Green but even then I get to see red bars on the map.

### Environment
Windows 10 OS

(please complete the following information):

- superset version: 0.30.1
- python version: 3.6

### Checklist

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
-  I have reproduced the issue with at least the latest released version of superset.
-  I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by JunlinC** [comment]
🏷 chart

**Comment by rusackas** [comment]
This is indeed an antique issue, but I'll leave it open since it still appears to be a problem in 2.0.1. If nobody's complaining about this, I'm wondering if the feature is even needed. 

@mistercrunch @betodealmeida do you recall this control working, or know how crucial it is?

**Comment by rusackas** [comment]
This seems to be resolved... you now can pick a palette rather than the fixed color picker, but it works!
