### ISSUE TITLE
[RBAC]Remove share and favorite

### ISSUE THREAD

**Issue by stefanmo** [apache/superset#9725]
**Is your feature request related to a problem? Please describe.**
Remove the share and favorite buttons

**Describe the solution you'd like**
I would like to be able to remove the share and favorite buttons from the dashboards because in our implementation users will not have direct access to superset but thru iframes and custom authentication.

**Describe alternatives you've considered**
I have looked in other issues on github and read the documentation countless times but I could not find a solution.
Not adding the fave permissions only ends up in an error that says there is no access to the favorite list.

**Additional context**

**Comment by mistercrunch** [comment]
Seems reasonable, it should show based on whether the user (or the Public role) has the right to do favorite or not.

**Comment by junlincc** [comment]
https://github.com/apache/superset/issues/10408 moving conversation to SIP51
