### ISSUE TITLE
[SIP-42] Option to set a user's profile as their welcome page

### ISSUE THREAD

**Issue by altef** [apache/superset#9792]
*Please make sure you are familiar with the SIP process documented*
(here)[https://github.com/apache/incubator-superset/issues/5602]

### Motivation

In certain situations a user's profile page may be more useful than Superset's default welcome page.  And while the welcome dashboard is a nice feature, the option to use the user's profile page might be nice.  It lists their favourite dashboards, rather than a single dashboard (like the welcome dashboard) or all dashboards they can access (like the default welcome page).

### Proposed Change

I propose we add a config setting to allow this, defaulting to false so as not to impact any existing installs.  
`WELCOME_WITH_USER_PROFILE = False`

Welcome dashboards can still take precedence, if supplied - all this will do is swap out the default welcome page for the user's profile page.

### New or Changed Public Interfaces

The only change should be exposing an additional config setting.

### New dependencies

None.

### Migration Plan and Compatibility

None necessary.

### Rejected Alternatives

For our use-case we attempted using the welcome dashboards, but they did not suit our purpose.  An iframe could have worked, however there seems to be no jinja access to the user id there so we can't easily differentiate between users.

**Comment by altef** [comment]
I'm not super clear on if this warrants a SIP, but it does impact the configuration which is specifically mentioned in the list of things to be SIPed.  Apologies if this in fact was inappropriate.

**Comment by craig-rueda** [comment]
Thanks for your submission! As you pointed out in your description, it probably doesn't warrant a SIP. Either way, I'm for this change as it will be behind a flag with a default of the current behavior.

**Comment by robdiciuccio** [comment]
[SIP-34](https://github.com/apache/incubator-superset/issues/8976) includes a design for a new landing/home page experience. While this proposed change does not directly conflict with the direction of SIP-34, due to the config flag, we should evaluate this proposal within that context.

**Comment by mistercrunch** [comment]
@betodealmeida did some work in the past where each user gets their own dashboard as a landing page. That dashboard would be cloned from a template, and contain object lists based on on tags. A cool idea.

**Comment by mistercrunch** [comment]
https://user-images.githubusercontent.com/812905/72391546-4a94dc80-36e2-11ea-8925-16833d2ba81b.png

**Comment by altef** [comment]
That would be nice, especially if combined with some form of dashboard-level permissions, though I guess that's probably not part of that SIP?

**Comment by rusackas** [comment]
I think given the ambiguity, the amount of time this has been in discussion, and how long it's been, we can call this closed for now. There's been a lot of work on the Homepage, and the Profile features/location are on the roadmap for revisit/redesign/rebuild. We'll make it all better, and address at least some of your concerns in this effort :)

**Comment by rusackas** [comment]
Since this issue is closed due to inactivity, we'll also consider the SIP/proposal process closed as well. If you want to rekindle this proposal, please re-open this Issue, and send a new [DISCUSS] thread to the dev@ mailing list. Thank you!
