### ISSUE TITLE
SQL Lab results row height/width is too short for last row

### ISSUE THREAD

**Issue by tooptoop4** [apache/superset#9869]
see attached, if i change height pixels from 32 to 40 in developer tools then it is readable
![last row height cut](https://user-images.githubusercontent.com/33283496/82511042-1c962d80-9b04-11ea-9273-302973e09aae.png)

**Comment by eschutho** [comment]
I'm working on this. Should have a fix soon.

**Comment by nytai** [comment]
fixed by ☝️
