### ISSUE TITLE
[SIP 44] Proposal for Dart Module implementation

### ISSUE THREAD

**Issue by kalimuthu123** [apache/superset#9892]
*Please make sure you are familiar with the SIP process documented*
(here)[https://github.com/SvayamLabs/superset-ui-number-Format]

### Motivation
   **My Google-fu is strong.**

Description of the problem to be solved.
the reason for the migration 
     1) typescript chunk size which makes the browser not responding whenthe data is large
     2)Flutter is multiplatform (native )  we can port to android devices 
     3) some package deprecation leads  tools  as incapable
     4)flutter widget have native performance which reduces  the browser hangover
   

### Proposed Change
the migration of typescripts to flutter Language:
the syntax of typescript and dart language are similar in variable declaration and functional s declarations and OOPs concepts , the process of converting is easily carryout
the difference in between the both the language is vary only in the export and import process

### New or Changed Public Interfaces
AS a native interface we can  create a more animative dashboard which can be competetive with other products like tableau,PowerBi

### New dependencies

dart version > 2.0
flutter version > 1.17

### Migration Plan and Compatibility

formatting modules ,connection modules =======>>  flutter Packages
Superchart , tooltips ,ui-plugins modules  =======>> flutter widgets

my plan is implementing our charting tool  in a stable products like flutter.

Flutter has variety of widgets 
which are suitable  for common 3 interfaces which are

1)Android
2)Ios
3)web Applications

Cupertino (iOS-style) widgets
https://flutter.dev/docs/development/ui/widgets

AS a initial step i  created a module based on the @Superset-ui/Number-Format
the github link of my dart coded package
https://github.com/SvayamLabs/superset-ui-number-Format

**Comment by Vino2530** [comment]
https://github.com/Vino2530/dart.git

**Comment by suddjian** [comment]
Do you have specific data on how typescript impacts chunk size and browser performance?

**Comment by kalimuthu123** [comment]
@suddjian 
![oie_NoPPEtlSz8If](https://user-images.githubusercontent.com/42966797/83321874-aff00100-a270-11ea-8a37-d6e0bc3449a6.png)

when i refer the chunck size of the superset  it looks pretty bigger when data flows
and the major aim of this Proposal is implementing the superset across all platforms
1)Desktop applications
 a)linux
b)mac
c)windows
2)Mobile application
a)ios
b)android
3)web application
flutter having such ability of working across multi platforms compared to other languages
https://github.com/google/flutter-desktop-embedding

**Comment by mistercrunch** [comment]
-1 
I think moving from typescript to dart is a bad idea
<img width="1211" alt="Screen Shot 2020-10-22 at 10 18 33 PM" src="https://user-images.githubusercontent.com/487433/96959310-92883180-14b4-11eb-98eb-49fd1f33128c.png">

**Comment by willbarrett** [comment]
-1 - we already have multiple frontend migrations in process and I don't think changing languages is prudent at this time.

**Comment by rusackas** [comment]
I think that based on the sentiment in the thread, the timeline since last comment, and the lack of a VOTE thread, we'll call this closed. If it needs further attention or you want to push it forward for an official vote, we can re-open this. Thank you for the discussion/ideas!

**Comment by danielleiszen** [comment]
I am really happy to see that there is a proposal at least. I understand this thread is dead, but... can I vote for this?
I use flutter since the beginning and find it a really strong framework. Is it possible to contribute?
