### ISSUE TITLE
Codecov migration to marketplace app

### ISSUE THREAD

**Issue by thomasrockhu** [apache/superset#9930]
Hi, Tom from [Codecov](https://codecov.io) here.

We noticed that you are using Codecov with fairly high frequency, and we’re so excited to see that! However, because you are not using our app, you may have experienced issues with uploading reports or viewing coverage information. This is due to rate-limiting issues from GitHub.

**In order to prevent any future outages, we ask that you move over to our [GitHub app integration](https://github.com/apps/codecov).**

The process is extremely simple and shouldn’t require more than a few clicks, and you should not expect any downtime. By moving to our app, you will no longer need an admin or separate account to manage the relationship with GitHub as the team bot.

Let me know if you have any questions, or if I can help at all with this process.

**Comment by thomasrockhu** [comment]
I noticed that a few other `apache` repositories have migrated over to the integration including [incubator-mxnet](https://github.com/apache/incubator-mxnet/issues/18421) and [skywalking](https://github.com/apache/skywalking/issues/4835). The process should be fairly easy now for the organization in general. Let me know if I can do anything to help.

**Comment by thomasrockhu** [comment]
Bump on this

**Comment by willbarrett** [comment]
Hi @thomasrockhu - we have migrated to the Github application. Apologies for the long delay in responding! We have conditional builds set up for different test suites and often face long CI delays. We find this situation leads to inaccurate results in Codecov. We've updated our configuration recently here: https://github.com/apache/superset/pull/13329 but I'm wondering if you have any other suggestions on how to make Codecov's interaction with Superset's tests more accurate and reliable?

**Comment by thomasrockhu** [comment]
@willbarrett thanks for responding back here! I think you are looking for [carryforward flags](https://docs.codecov.io/docs/carryforward-flags). If I'm reading your comment right, you don't run every test suite for every commit? If so, carryforward flags will pull the coverage data (by flag) from the last applicable commit. Let me know if that's what you were asking or if you had meant something else.

**Comment by john-bodley** [comment]
@ktmud and @jfrag1 can we close this issue now?

**Comment by nytai** [comment]
Yes
