### ISSUE TITLE
How to add greater than filter in apache superset?

### ISSUE THREAD

**Issue by sedhha** [apache/superset#9974]
Has superset changed its folder locations and interface? From a youtube tutorial, I found these options available in filter box:
![image](https://user-images.githubusercontent.com/36355685/83600250-c86f5c80-a58b-11ea-8e90-22c9de9ae1b8.png)
But what my filter looks like is:
![image](https://user-images.githubusercontent.com/36355685/83600336-fb195500-a58b-11ea-853a-003ac6f48a7a.png)

I want to apply a filter box which gives me flexibility to apply a filter over ranges. For example, this is my table:
![image](https://user-images.githubusercontent.com/36355685/83600423-3025a780-a58c-11ea-8354-a2eaa583ccf1.png)

I want to add a filter where it should display only those table results where videos>=100 and videos<=10000. Although filter allows me to select multiple value but what it doesn't allow me is to apply ranges, and as you know there are so many values between these two ranges, it gets very inefficient to apply these filters.

I tried to apply the filter as shown below:
![image](https://user-images.githubusercontent.com/36355685/83601395-2735d580-a58e-11ea-8eac-3d71ee20228e.png)
![image](https://user-images.githubusercontent.com/36355685/83601435-37e64b80-a58e-11ea-80b5-5305fc83288f.png)
![image](https://user-images.githubusercontent.com/36355685/83601480-50566600-a58e-11ea-93fa-69c4187580ba.png)
But how it works is this way:
![image](https://user-images.githubusercontent.com/36355685/83601525-63693600-a58e-11ea-9a83-28d7caa0b52a.png)
When we look at time filter:
![image](https://user-images.githubusercontent.com/36355685/83601599-84318b80-a58e-11ea-826a-5da1a5f9ecd7.png)
It works well and offers tons of customization, I was just curious if we can dynamically filter time then why not other values. Please do let me know if you have something for this.

**Additional context**

**Comment by aussat** [comment]
Agree, this would be great if dynamic filters added to Superset. I am not sure if it works for your problem, but you can try to use CASE function to the range you need to filter. In order to do this, just add a new column in datasource editor with required SQL, 
then use this column in FIlter View.

```
CASE
    WHEN condition1 THEN result1
    WHEN condition2 THEN result2
    WHEN conditionN THEN resultN
    ELSE result
END;
```

**Comment by sedhha** [comment]
Oh amaing @aussat Thanks a lot will try this out.

**Comment by AsjadMahmood** [comment]
Any update how we can add  less than greater than filter in Filter Box so we can apply it on the dashboard, we do get to add these filters in other charts, but not in Filter Box

**Comment by lozbrown** [comment]
@junlincc 
Any chance this might be possible soon?

**Comment by aonurdemir** [comment]
Although we can filter columns by range in explore chart screen, it is weird that we cannot filter columns by range in dashboard filters. Any progress?

**Comment by vialcollet** [comment]
Hi all
I agree this is a missing functionality. 
It can be requiered to offer the user the possiblity to zoom on specific ranges of some numerical fields.
For example I need it for some bubble charts.

**Comment by villebro** [comment]
@aonurdemir @vialcollet the new native filters feature is currently under heavy development, and we've already implemented a range filter which adds this feature (greater than, less than and range). Expect the feature to be in testable state fairly soon, but general availability is probably still a few months away.

**Comment by junlincc** [comment]
while you are waiting for the new features, you could try using jinja template to create range filter as workaround. 
we dont have an exact tutorial for it yet, but you can refer to .. 
https://www.youtube.com/watch?v=AcnNlIkfCiI
https://www.youtube.com/watch?v=dE1QlhunWMs

@vialcollet

**Comment by samah-m8** [comment]
Hello, 
This feature is not in 1.3.2, any idea when will it be added?

**Comment by erfanu25** [comment]
Is there any update for this in superset 2.0 ?

**Comment by villebro** [comment]
@erfanu25 please take a look at the Numerical Range Filter in Dashboard Native Filters which has been available for quite some time.
