### ISSUE TITLE
[Feature request] Bar chart custom ordering

### ISSUE THREAD

**Issue by bkyryliuk** [apache/superset#9998]
**Is your feature request related to a problem? Please describe.**
Enable custom ordering of the bar chart, e.g. currently only alphabetical ordering exists and that makes it hard to work with ranges:
e.g. 101-200 would be before 51-100

Users would love to see the feature to specify custom ordering of the values.
This could be implemented in a similar way to the table `sort_by` 

Similar request was here as well:
https://github.com/apache/incubator-superset/issues/3380

**Comment by rbk-paul** [comment]
Adding a note here.  For some reason, I am not seeing ordering in alphabetical order in its existing state, but seemingly ordered using the metrics from highest to lowest.
My x-axis is just 5 columns (years 2017 ~ 2021 inclusive)

If ordered alphabetically, I would assume the ordering would still be in chronological order, but currently, it's ordered 2018, 2017, 2019, 2020, 2021 from left-to-right.  It just so happens the metrics are from highest-to-lowest in that order.

**Comment by rumbin** [comment]
@rbk-paul have you tried the Sort Bars option in the Chart Options of the Customize tab? This should lead to alphabetical ordering.

**Comment by rbk-paul** [comment]
> @rbk-paul have you tried the Sort Bars option in the Chart Options of the Customize tab? This should lead to alphabetical ordering.

Thanks @rumbin!  That worked!

**Comment by john-bodley** [comment]
@bkyryliuk closing in favor of https://github.com/apache/superset/issues/13792.
